### ISSUE TITLE
gui: CSRF cookie expiring can cause UI to remain out of sync but look "live"

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#1008]
*computer A* runs Syncthing, shares files with *device X* and GUI listens on LAN-IP:8080

Steps
 1. open web GUI on *computer A*
 2. open web GUI  via LAN from *computer A* on *computer B*
 3. add files on *computer A* and sync starts

Result
* web GUI on *computer A* shows: active transfer rate, *device X* with blue header - e.g. syncing (13%)
* web GUI on *computer B* shows: active transfer rate, *device X* with green header - up to date (100%)

Expected
* web GUI always show same status

Workaround
* reloading browser window on *computer B*, then GUI displays correct sync status / values
* only seems to happen if web GUI is accessed *before* Syncthing on *computer A* starts sync

**Comment by calmh** [comment]
This is almost guaranteed an issue with the CSRF cookie. I know the handling of that one is a bit crappy. Retitling to reflect that.
