### ISSUE TITLE
Introducers should be able to remove devices as well as add them

### ISSUE THREAD

**Issue by Rewt0r** [syncthing/syncthing#1015]
If we have 10 devices and someone leaves the company and was using a personal device, our master file server should be able to remove the device (it can) but that device should remove any shares from that server once it's removed so they no longer have access to it.

**Comment by AudriusButkevicius** [comment]
So what we should perhaps do, is scrap the introducer flag all together, and have prompts 'X suggests you add Y?' with `Add`, `Not now`, `Never`

**Comment by Rewt0r** [comment]
That isn't an ideal solution with 10's or 100's of devices.

I've setup 18 machines so far and all I need to do is add our Introducer, the Introducer should also be able to instruct them to delete a device ideally.

**Comment by Rewt0r** [comment]
Just out of curiosity, with the current behaviour, if I remove a device from our Introducer will the other 16 devices still share the updated files with the 1 device I'm trying to remove?? If so that's a big pain and I need to try and access all other 16 machines in order to remove them...

**Comment by AudriusButkevicius** [comment]
Yes, it's an autonomous system where every device in the cluster decides what do to and who to share the files with.

**Comment by dcarosone** [comment]
Also, introducers only add knowledge of nodes, an extra step is (was)
needed on each of the nodes to start sharing specific folders with nodes
learned via an introducer. So it's quite reasonable to require a similar
step to stop, and by no means certain that the whole cluster should fall
apart just because the original node fell off.

**Comment by Rewt0r** [comment]
Could we not just sync list of known devices between nodes on connection or am I missing something?

**Comment by AudriusButkevicius** [comment]
How does that enable removal?

**Comment by dcarosone** [comment]
Related, possibly a separate issue:

   - Node A is known to node B. A is an introducer on B.
   - Node B is known to node C. B is an introducer on C.
   - B connects to C, and introduces A.
   - A is now an introducer on C.

I don't know if this is desired or intended, or even what the behaviour
"should" be, but there's one strange side-effect:

   - On node C, I remove the 'introducer' flag against A.  (None of the
   other nodes that connect to A will ever connect directly to C).
   - When B reconnects to C, A is set as an introducer again.

The latter point, at least, seems clearly wrong.  I don't know if the
config-from-an-introducer is completely overwriting node C's device record,
or it's specific to certain attributes like the introducer flag, but it
seems like local config should take precedence?


On 21 April 2015 at 04:59, Audrius Butkevicius <notifications@github.com>
wrote:

> How does that enable removal?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncthing/syncthing/issues/1015#issuecomment-94540870>
> .
>



-- 
Dan.

**Comment by AudriusButkevicius** [comment]
Well that's not what the code does, hence if you can reliably reproduce it, you should open a separate issue.

**Comment by calmh** [comment]
> if I remove a device from our Introducer will the other 16 devices still share the updated files with the 1 device I'm trying to remove?? If so that's a big pain and I need to try and access all other 16 machines in order to remove them...

We should fix this. Perhaps we need to not remove devices from an introducer, but instead *disable* or *revoke* them and have *that* be a flag that is synced?

**Comment by fsateler** [comment]
Related, when 2 nodes are both introducers to each other (I do this from my laptop to my home server, for example), it becomes very difficult to remove a device, as when removing it from node A, then node B will introduce it back.

**Comment by capi** [comment]
While I absolutely see the need for this, I'd recommend not bloating the "core" Syncthing too much with cluster management functionality.

I think, that it would be possible to create a cluster-management as an external application (similar to e.g. `syncthing-inotify`) where Syncthing itself is used as transport mechanism for distributing commands from the management node to the individual nodes. There we could add functionality like management of devices, shares, etc. for corporate use.

**Comment by dembach** [comment]
maybe we can use the annoucement server for this add/remove feature ?

**Comment by HermanEldering** [comment]
Another approach would be to use a digitally signed file inside the synced folder that contains which devices the folder should be shared with (ie a trusted devices file). If the file is changed it is synced, then the signature and signature timestamp are verified and if  the signature is valid and more recent than the existing file the settings of the folder are updated.

It could be either a separate module, by checking the trusted devices file after it has been synced locally. This has the disadvantage that someone might be able to block correct syncing by pushing invalid files. This would however be detectable so action can be taken manually.

Alternatively, the validity check could be included into the synchronization core. In this case Syncthing would not sync the file if the signature is not valid. This would prevent someone to block the propagation of the trusted devices file.

By selecting which signatures you trust you can control who can introduce/remove devices on your machine.

(this dea originated on the forum: https://forum.syncthing.net/t/feature-request-trusted-ca-for-automatic-trust/6832)
