### ISSUE TITLE
Improve conflict resolution mechanism when merging trees for the first time

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing#1022]
When indexes are rebuild on two machines at the about the same time, newer data can be overwritten by old data (if the machines were not fully synchronized).

23:33 @calmh> basically it's not deterministic which version of a file will win when there are two of them
23:34 @calmh> newest only wins with 50% certainty
23:34  Zillode> there is no use of the timestamp?
23:34 @calmh> no. in normal syncing, latest *change* wins, and we know when the change happens and bump versions etc.
23:35 @calmh> but the change can be to an older version of a file, so the timestamp could move backwards
23:35 @calmh> but when we have to trees that we merge for the first time, some better mechanism should be used

**Comment by AudriusButkevicius** [comment]
Is this still a thing?

**Comment by calmh** [comment]
Kinda maybe. It's different now anyway. But this is on my radar to take care of before v0.11 release.

**Comment by calmh** [comment]
:+1: as far as I'm concerned
