### ISSUE TITLE
Limit CPU usage

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [syncthing/syncthing#1046]
Syncthing use very few CPU when everything is in sync and no directory is being scanned. But when it needs to scan a folder or is compressing files or is encrypting data, it can use a lot of power (up to 98% CPU charge). Sometimes it's quick, sometimes it's not, but in any case I can't use my computer/server for anything else. 

I would rather be able to limit Syncthing CPU (and maybe RAM too), so even if my files aren't synced right away (or right when the the directory is scanned), I still can use my computer as usual. Maybe adding this as an option is the settings. I don't know the feasibility of such a feature, so what do you think about this?

**Comment by Jelmerro** [comment]
My mumble server (murmur) starts lagging every time syncthing starts scanning a folder (core2duo e8400). Any solution for windows? Changing the process priority doesn't do the trick.

**Comment by AudriusButkevicius** [comment]
Try inotify

**Comment by Jelmerro** [comment]
inotify is only for linux? I was personally looking for a windows solution (as mentioned).

**Comment by AudriusButkevicius** [comment]
inotify is just a name, it works on windows too. Alternatively you can run SyncTrayzor which provides an improved native UI + inotify (or whatever it's called under windows)
