### ISSUE TITLE
v0.10.9 Status disappears when the window gets smaller

### ISSUE THREAD

**Issue by bigbear2nd** [syncthing/syncthing#1084]
![unbenann2t](https://cloud.githubusercontent.com/assets/7719800/5310838/8ff08bfa-7c7d-11e4-8884-10983d7691ae.JPG)
![unbenann3t](https://cloud.githubusercontent.com/assets/7719800/5310839/93698606-7c7d-11e4-92e8-0b5c761d1039.JPG)
![unbenannt](https://cloud.githubusercontent.com/assets/7719800/5310846/a2342966-7c7d-11e4-9ebe-847f0b40c64d.png)

With the "Fruit Salad GUI" one still was able to see the current status. Now it is not clear any more.

**Comment by bigbear2nd** [comment]
I added the h3 header:
![asdasd](https://cloud.githubusercontent.com/assets/7719800/5630129/3253f7e4-95fe-11e4-8020-1d98d0416e61.PNG)

I tried to add the CSS mentioned by @uok and i added the following code:


              <h3 class="panel-title">
                <span class="glyphicon glyphicon-hdd hidden-xs"></span>&emsp;{{folder.ID}}
                <span class="pull-right hidden-xs text-{{folderClass(folder)}}" ng-switch="folderStatus(folder)">
                  <span translate ng-switch-when="unknown">Unknown</span>
                  <span translate ng-switch-when="unshared">Unshared</span>
                  <span translate ng-switch-when="stopped">Stopped</span>
                  <span translate ng-switch-when="scanning">Scanning</span>
                  <span translate ng-switch-when="idle">Up to Date</span>
                  <span ng-switch-when="syncing">
                    <span translate>Syncing</span>
                    ({{syncPercentage(folder.ID)}}%)
                  </span>
                </span>
                <span class="pull-right visible-xs text-{{folderClass(folder)}}" ng-switch="folderStatus(folder)">
                  <span  ng-switch-when="unknown">&#9724;</span>
                  <span  ng-switch-when="unshared">&#9724;</span>
                  <span  ng-switch-when="stopped">&#9724;</span>
                  <span  ng-switch-when="scanning">&#9724;</span>
                  <span  ng-switch-when="idle">&#9724;</span>
                  <span ng-switch-when="syncing">&#9724;</span>
                </span>
              </h3>


FireFox:
![firefoxwin7](https://cloud.githubusercontent.com/assets/7719800/5629948/7ccd4408-95fc-11e4-9068-e1d330616720.PNG)

IE7:
![iewin7](https://cloud.githubusercontent.com/assets/7719800/5629949/7e84172c-95fc-11e4-8820-cfcf35b8c0bf.PNG)

So it seems the "nowarp" does not what it should..

without the "nowarp": (This seems more desirable for me)
FireFox:
![firefoxwin7_nonowrap](https://cloud.githubusercontent.com/assets/7719800/5629986/e624a02c-95fc-11e4-992e-723b3014751c.PNG)

IE7:
![iewin7_nonowrap](https://cloud.githubusercontent.com/assets/7719800/5629987/eb669540-95fc-11e4-968b-2f4d548991ce.PNG)

Because I don´t want that space, when we are in the small gui, I changed the above code:
from:

    <span class="glyphicon glyphicon-hdd hidden-xs"></span>&emsp;{{folder.ID}}"


to: 


    <span class="glyphicon glyphicon-hdd hidden-xs">&emsp;</span>{{folder.ID}}"


This happens:
Again FireFox first:
![firefoxwin7_hiddenspace1](https://cloud.githubusercontent.com/assets/7719800/5630053/8d984c28-95fd-11e4-9551-0207d159993e.PNG)
![firefoxwin7_hiddenspace2](https://cloud.githubusercontent.com/assets/7719800/5630054/90ce65e4-95fd-11e4-9aef-48baafcb50fa.PNG)

So all looks fine.

But IE:
![iewin7_hiddenspace1](https://cloud.githubusercontent.com/assets/7719800/5630059/9c10dc16-95fd-11e4-8faa-ee276c7235e6.PNG)
![iewin7_hiddenspace2](https://cloud.githubusercontent.com/assets/7719800/5630063/a076e9ee-95fd-11e4-9060-06e1784755bb.PNG)

My questions would be:
- What about the space situation.
- The way I made the hidden box, is that ok? (with the double text, or can this be done more elegant?)

You can see my changes in https://github.com/bigbear2nd/syncthing/commit/a4042a945363cf5c8cb4fd7a9cd9f359caa25df7

**Comment by uok** [comment]
@bigbear2nd : thanks for trying my idea and the screenshots

my suggestion to keep the code clean

    <span class="hidden-xs" translate ng-switch-when="unknown">Unknown</span><span class="visible-xs" ng-switch-when="unknown">&#9724;</span>
    <span class="hidden-xs" translate ng-switch-when="unshared">Unshared</span><span class="visible-xs" ng-switch-when="unshared">&#9724;</span>

so each status has a single line instead of two "duplicate" big spans <span class="pull-right ...
because the GUI uses angular to translate the strings I think further "minification" is not possible

glyphicons
should be hidden 

spacer
better would be to remove the space `&emsp;` and add a margin-right to the header glyphicon. That way the visible space will also disappear if the icon is hidden.

line-breaks
maybe a smaller font size would help?

**Comment by bigbear2nd** [comment]
I am truly sorry for the above commit and merge + revert nonsense.
Something went wrong with the rebase commands.. I fail to understand git.

Please feel free to use any lines of code from 
https://github.com/syncthing/syncthing/commit/36a6e13fc0c2689c8bb709dee279544ca58f4974
this was working in IE and FireFox the best. 
I hope someone can delete all the nonsense. I tried to delete my fork, but the comments here stay..

**Comment by AudriusButkevicius** [comment]
Sorry but I am completely puzzled about where your commit is.
Can you just commit it to your repo and make a pull request?

**Comment by bigbear2nd** [comment]
Again, i am sorry for all the unnecessary git references. I am still very unfamiliar with all the commiting, squashing and git itself.

I created the section headers as @calmh suggested, but the word "devices" is not in the translation list yet. How can I enter this there?

**Comment by uok** [comment]
As long as the translate-attribute is set it should be fine. AFAIK @calmh has some script magic in the background that creates the necessary string file which is then pulled by transifexe and again pulled back to github together with a new release :tada:
