### ISSUE TITLE
Copy name and IP Address while introducing

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing#1098]
Currently we only introduce the device ID of existing devices. Maybe it is interesting to also copy the name and IP address to further reduce the effort.
For example, when adding a few devices to 8 existing ones, I still need to modify the ip address and naming multiple times. This forces me to manually look up this information every time I notice it is missing.

**Comment by calmh** [comment]
Pretty sure this one is handled by Audrius changes in v0.13

**Comment by AudriusButkevicius** [comment]
Yes, https://github.com/syncthing/syncthing/commit/a323d85d32d94219b70a2cb13ebf8e9520684f14

**Comment by generalmanager** [comment]
Thanks @AudriusButkevicius! It's little details like this which differentiates Syncthing from the lesser alternatives ;-)
