### ISSUE TITLE
Add new kind of ignore pattern for folders containing special files (eg. `CACHEDIR.TAG`)

### ISSUE THREAD

**Issue by em-** [syncthing/syncthing#1114]
A quite widespread standard for tagging directories with volatile contents is the [Cache Directory Tagging Standard](http://www.brynosaurus.com/cachedir/spec.html) which works by adding a `CACHEDIR.TAG` file to mark the folder to be ignored.

Unfortunately there doesn't seem to be a way to tell `syncthing` to ignore such directories since the ignore pattern would simply ignore the `CACHEDIR.TAG` file itself and not the folder recursively.

It would be awesome if we could instruct `syncthing` to ignore such folders, or even if it could ignore them out-of-the-box.

Thanks!

**Comment by djtm** [comment]
Using it with obnam. Great stuff. Works really great. Set up once, use everywhere. Much more comfortable, flexible and precise than exclude rules.

sudo apt-get install cachedir
then 
e.g. sudo cachedir tag /var/tmp

**Comment by calmh** [comment]
#2491
