### ISSUE TITLE
Allow syncing read-only directories as "Master Folders"

### ISSUE THREAD

**Issue by liotcheg** [syncthing/syncthing#1126]
The reason for creating this is strict KitKat [permissions](http://www.androidcentral.com/kitkat-sdcard-changes) for an external SD Card. As a result Syncthing cannot sync data on SD Card except one folder /sdcard1/Android/data/com.nutomic.syncthingandroid/files/

My suggestion is not to stop syncing read-only folders if "Folder Master" option is selected.
An obvious example why we may need it is one-way syncing photos _from_ an Android device.

In this case file .stfolder also cannot be written and a "permission denied" error rises. This needs to be resolved somehow.

Of course, this would be useful not only on Android platform. Generally , this is quite logical to allow one-way sync of read-only directories when "Master Folder" option is selected.

**Comment by Kernald** [comment]
I have the same use-case as #1940 (syncing an encrypted copy of a folder to a potentially unsafe location). The source folder is read-only, and a virtual FS, so I can't write in it at all. Storing the configuration files (`.stfolder` and `.stignore`) in a specific folder would be useful in some cases.

**Comment by AudriusButkevicius** [comment]
Storing stfolder makes it useless, as explained, this file is there to detect when the folder was unmounted, versus all of the content was genuinely removed.

**Comment by Kernald** [comment]
Oh right, I guessed it stored some information. My bad.

**Comment by dcarosone** [comment]
Would it be enough to allow a per folder property for the name of the
.stfolder file?

If, in a read only location, I could find some other existing file that's
unlikely to ever disappear, and tell syncthing to look for that file
instead, it might just solve this.

**Comment by arisada** [comment]
I managed to work around this problem by manually creating a .stfolder file using adb shell + touch in the root of the directory I wanted to synchronize, and it worked. It would probably work by mounting the SD card on a PC, too.

If no good fix can be found, it could be good to send a more comprehensible error message with this workaround proposal instead. It took me a while to understand why it was failing in the first place.

**Comment by calmh** [comment]
How about making the marker file name configurable per folder, of course defaulting to `.stfolder`. For cases where creating an .stfolder maker isn't feasible, the user can instead set it to the name of a folder or file that should always exist.

**Comment by Jip-Hop** [comment]
Making the marker file name configurable per folder would solve my problem. I'm planning to sync my [Seafile library mounted via FUSE](https://manual.seafile.com/extension/fuse.html) via Syncthing to a backup location. The filesystem is read only, so `.stfolder`can't be created. I've worked around this by syncing the parent folder instead (which is writable). But if FUSE or the Seafile server stop working and the mount becomes unavailable, only the .stfolder will remain and it will cause a mass deletion of all my files on the backup location...

**Comment by Jip-Hop** [comment]
Wow that was quick. Thanks!
