### ISSUE TITLE
Folder "Up to Date" still shows "Out of Sync"

### ISSUE THREAD

**Issue by priyadarshan** [syncthing/syncthing#1130]
Hi,

I am sharing a folder between a Mac (OS X 10.9.5), as "Folder Master", and an Ubuntu 14.04 server running on a VPS.

All the files were previously uploaded to the server, I just need to keep them in sync. On the Ubutnu device,  I just pointed the root of the folder to the already uploaded directory.

The folder on the Mac side says "Up to Date":
![screen shot 2014-12-19 at 15 18 47](https://cloud.githubusercontent.com/assets/1652143/5505692/8efafb9c-8793-11e4-977a-0135e6d21f3c.png)

On the Ubuntu side, it says the same, but also "Out of Sync":

![screen shot 2014-12-19 at 15 18 25](https://cloud.githubusercontent.com/assets/1652143/5505673/6a1877e6-8793-11e4-970e-4a05a9a7dd85.png)

On the Mac side, the Ubuntu device shows "Synching (57%):

![screen shot 2014-12-19 at 15 19 06](https://cloud.githubusercontent.com/assets/1652143/5505687/85c7080e-8793-11e4-9e3d-cae06a635a22.png)

I tried to restart `synchting` on both machines, with no change.

They both run `syncthing` v0.10.13

I saw other issues similar to this one here and on the forum, but I still have not found a solution. It seems to me the problem is more on the GUI side?

**Comment by vedranf** [comment]
Hello,

Same issue here. No master folders, no excludes or ignores, nothing in logs. It happened when internet connection broke during the initial folder sync, once it was established again, syncthing refused to sync out of sync files (it shows them in the list) and said both sides were up to date.

Regards,
Vedran

**Comment by Nutomic** [comment]
I am getting the same issue, on two nodes with v0.10.20, no folder master or ignores.

Do you need any logs?

**Comment by AudriusButkevicius** [comment]
Is it actually making any progress though?

**Comment by Nutomic** [comment]
No it completely stops transfering data (after the index exchange it seems).

**Comment by AudriusButkevicius** [comment]
Can you run with STTRACE=model and see what's happening?

**Comment by Nutomic** [comment]
After the index exchange, there's constantly stuff like this running down: 
(but I'm also not sure what I'm looking for)

```
[CDSRV] 2015/01/19 17:27:06.147636 puller.go:148: DEBUG: puller/m_docs@0x11bcae80 skip (curVer == prevVer) 0
[CDSRV] 2015/01/19 17:27:06.151710 puller.go:148: DEBUG: puller/f1_bilder_2@0x11bcac80 skip (curVer == prevVer) 0
[CDSRV] 2015/01/19 17:27:06.154374 puller.go:148: DEBUG: puller/f1_bilder@0x11bcafc0 skip (curVer == prevVer) 0
[CDSRV] 2015/01/19 17:27:06.160633 puller.go:148: DEBUG: puller/f2_music@0x11bcad40 skip (curVer == prevVer) 115211
[CDSRV] 2015/01/19 17:27:06.291761 puller.go:148: DEBUG: puller/f2_pictures@0x11bcadc0 skip (curVer == prevVer) 113772
[CDSRV] 2015/01/19 17:27:06.632637 puller.go:148: DEBUG: puller/michael_dokumente@0x11bcaf40 skip (curVer == prevVer) 0
[CDSRV] 2015/01/19 17:27:06.792717 puller.go:148: DEBUG: puller/f2_sync@0x11bcae00 skip (curVer == prevVer) 115225
[CDSRV] 2015/01/19 17:27:07.151379 puller.go:148: DEBUG: puller/m_docs@0x11bcae80 skip (curVer == prevVer) 0
[CDSRV] 2015/01/19 17:27:07.156707 puller.go:148: DEBUG: puller/f1_bilder_2@0x11bcac80 skip (curVer == prevVer) 0
[CDSRV] 2015/01/19 17:27:07.158746 puller.go:148: DEBUG: puller/f1_bilder@0x11bcafc0 skip (curVer == prevVer) 0
[CDSRV] 2015/01/19 17:27:07.161887 puller.go:148: DEBUG: puller/f2_music@0x11bcad40 skip (curVer == prevVer) 115211
[CDSRV] 2015/01/19 17:27:07.294760 puller.go:148: DEBUG: puller/f2_pictures@0x11bcadc0 skip (curVer == prevVer) 113772
[CDSRV] 2015/01/19 17:27:07.637510 puller.go:148: DEBUG: puller/michael_dokumente@0x11bcaf40 skip (curVer == prevVer) 0
[CDSRV] 2015/01/19 17:27:07.795825 puller.go:148: DEBUG: puller/f2_sync@0x11bcae00 skip (curVer == prevVer) 115225
[CDSRV] 2015/01/19 17:27:08.154501 puller.go:148: DEBUG: puller/m_docs@0x11bcae80 skip (curVer == prevVer) 0
[CDSRV] 2015/01/19 17:27:08.159191 puller.go:148: DEBUG: puller/f1_bilder_2@0x11bcac80 skip (curVer == prevVer) 0
[CDSRV] 2015/01/19 17:27:08.161814 puller.go:148: DEBUG: puller/f1_bilder@0x11bcafc0 skip (curVer == prevVer) 0
[CDSRV] 2015/01/19 17:27:08.166709 puller.go:148: DEBUG: puller/f2_music@0x11bcad40 skip (curVer == prevVer) 115211
```

**Comment by alex2108** [comment]
@Nutomic is it also the first sync of a folder for you? I also had it on the first sync of a folder to a new pc like @vedranf described it and then never saw it again (see the very old issue https://github.com/syncthing/syncthing/issues/803)

**Comment by Nutomic** [comment]
@alex2108 No, the folder was in sync before.

**Comment by AudriusButkevicius** [comment]
@Nutomic is the content actually matching on both sides? Or does the content not match and it stops syncting?
Also, what does the `/rest/need` JSON dump look like? Which section are the files listed under?

**Comment by Nutomic** [comment]
No, there's data missing (the device with missing data also correctly shows the amount of data that's out of sync).

I also added some new files today, and these were synced correctly (in the same repo).

`/rest/need`:
```
{"progress":[],"queued":[],"rest":[]}
```

Should I just delete the index? I assume that would fix it, but then we can't debug it any more :D

**Comment by AudriusButkevicius** [comment]
@Nutomic which folder is in this lingering state?

**Comment by AudriusButkevicius** [comment]
Also, can you run with `STTRACE=files` and provide what `loaded localVersion for ` shows for the folder in question.

**Comment by Nutomic** [comment]
I should probably mention that the log I posted above is only a small part of some hundred lines that were scrolling by, so I have no idea if those are the relevant lines (

`loaded localVersion for`:
```
[CDSRV] 2015/01/21 14:00:53.355988 set.go:77: DEBUG: loaded localVersion for "f2_music": map[protocol.DeviceID]uint64{7777777-777777N-7777777-777777N-7777777-777777N-7777777-77777Q4:0x12a0e}
[CDSRV] 2015/01/21 14:00:54.632465 set.go:77: DEBUG: loaded localVersion for "f2_pictures": map[protocol.DeviceID]uint64{7777777-777777N-7777777-777777N-7777777-777777N-7777777-77777Q4:0x11acb}
```

I ran the `STTRACE=model` again, and it always shows `skip (curVer == prevVer) 113772` after index exchange (all while showing "Out Of Sync 	669 items, ~1.37 GiB").

I also `touch`ed a file, but it didn't get synced (nor curVer/prevVer change).

**Comment by AudriusButkevicius** [comment]
Can you get the STTRACE=scanner for that file after you've touched it?

**Comment by Nutomic** [comment]
On the sending or receiving side?

**Comment by AudriusButkevicius** [comment]
And the skip is for which folder? 

I guess you should run STTRACE=model on the with the problem side, and STTRACE=scanner,model on the side without the problem.
Then touch once of the files with problems, which should get it rescanned, and an update dispatched to the problematic node. Then the problematic node should get the change and try to sync it across.

**Comment by Nutomic** [comment]
My logs are from the receiving side (pictures folder).

After the `touch`, curVer is incremented by one on the sending side, and it prints this quite often:
```
[UE6TV] 2015/01/21 16:55:24.680603 puller.go:148: DEBUG: puller/f2_pictures@0xc2090ea1c0 skip (curVer == prevVer) 76486
[UE6TV] 2015/01/21 16:55:24.940040 model.go:743: DEBUG: model@0xc20812e360 REQ(in): *id of the other node*: "f2_pictures" / "folder/2/file.JPG" o=2228224 s=131072
```

(not sure where that `/2/` in the path comes from and why the `.jpg` became uppercase)

**Comment by AudriusButkevicius** [comment]
This is really hard to debug, as I don't see the full context. Also, you haven't provided no scanner output nor any logs from the receiving side (as this is only getting requests not making any).

**Comment by Nutomic** [comment]
My last post (`"f2_pictures" / "subfolder/2/file.JPG"` etc) is with `STTRACE=scanner` on the sending side. Everything else is on the receiving side.

I realize it's complicated, and I'm sorry my posts are so confusing :s

**Comment by AudriusButkevicius** [comment]
Yeah I understand it's on the sending side. I am asking for logs at the receiving side.

**Comment by Nutomic** [comment]
For some reason, the sync started to work now (I didn't do anything but restart a lot of times). This was also before the v0.10.21 upgrade.

So I can't help any more right now, but will post if it happens again.

**Comment by cdhowie** [comment]
I am seeing the same behavior on a fresh install of v0.11.1, using two devices (Windows 7 64-bit and Debian Jessie 64-bit).

I added the devices to each other and added a folder with the same content on both ends (as in, they should already be in sync).

The Linux device reports the folder as "up to date" but with 863 (out of 13386) files out of sync, and reports its Windows peer as "up to date."

The Windows device reports the folder as "up to date" with nothing out of sync, and the Linux peer as "Syncing (56%)."

There are no ignore rules in play.

**Comment by Zillode** [comment]
@cdhowie please provide logs of both devices.

**Comment by cdhowie** [comment]
I have the log from the Linux device (the one that appears to be out of date) but it's about 900 lines long; where should I send it?

**Comment by Zillode** [comment]
Feel free to use an online pastebin.
It would be better if we get access to the logs of the windows device as well (I think these logs are stored in a txt file)

**Comment by cdhowie** [comment]
Both logs are here: http://static.chrishowie.com/syncthing-debug.txt

I checked their clocks and the Linux machine is about two seconds behind the Windows machine, so the timestamps will not *exactly* line up.

**Comment by calmh** [comment]
All files are out of sync at initial scan. Let the devices sync. If one of them is set to master, either temporarily unset that it hit the override button.

**Comment by calmh** [comment]
(Pretty sure this is not the same issue as the original, and v0.10.13 is dead now, so closing.)
