### ISSUE TITLE
Illegal instruction on armv5 processor

### ISSUE THREAD

**Issue by SebastienDebia** [syncthing/syncthing#1132]
I run syncthing v0.10.13 armv5 on a WD My Book World Edition II (white light) and it regularly crashes with an "Illegal instruction" message.

The crash can be provoked easily by interacting with the terminal for instance if I do ctrl+C or if I resize it (yes...) but it does happen if I don't touch it.

other versions I tried:
v0.10.8 was ok
v0.10.11 was showing the same problem

system details:
```
seb@mike:/opt/syncthing# uname -a
Linux mike 2.6.24.4 #1 Thu Apr 1 16:43:58 CST 2010 armv5tejl unknown
```

```
seb@mike:/opt/syncthing# cat /proc/cpuinfo 
Processor	: ARM926EJ-S rev 5 (v5l)
BogoMIPS	: 183.09
Features	: swp half thumb fastmult edsp java 
CPU implementer	: 0x41
CPU architecture: 5TEJ
CPU variant	: 0x0
CPU part	: 0x926
CPU revision	: 5
Cache type	: write-back
Cache clean	: cp15 c7 ops
Cache lockdown	: format C
Cache format	: Harvard
I size		: 32768
I assoc		: 4
I line length	: 32
I sets		: 256
D size		: 32768
D assoc		: 4
D line length	: 32
D sets		: 256

Hardware	: Oxsemi NAS
Revision	: 0000
Serial		: 00000d312c366e40
```

**Comment by rchovan** [comment]
Same error on Synology DS107+

https://github.com/syncthing/syncthing/issues/1173

```
strace -f ./syncthing
execve("./syncthing", ["./syncthing"], [/* 20 vars */]) = 0
getpid()                                = 1
--- SIGILL (Illegal instruction) @ 0 (0) ---
+++ killed by SIGILL (core dumped) +++
Illegal instruction (core dumped)
```

**Comment by AudriusButkevicius** [comment]
Does this still happen?

**Comment by Zillode** [comment]
Probably, I think https://github.com/syncthing/syncthing-android/issues/336 is the same issue

**Comment by calmh** [comment]
(Needs investigation by people with ARMv5 processors.)

**Comment by Zillode** [comment]
Toolchain was not built with ARMv5 support.
