### ISSUE TITLE
'Last File Synced' rename to 'Last File Received' 

### ISSUE THREAD

**Issue by GoSpursGoNL** [syncthing/syncthing#1145]
Syncthing is syncing perfectly, every file I change gets synced to the other machine without any problems.

However, in the GUI, the 'Last File Synced' information is heavily outdated. It does not display the last file I modified, and on mouseover the date of over a week ago is mentioned.

Using version 0.10.13 on Ubuntu 14.04.

**Comment by Novox** [comment]
Should "Last File Synced" be renamed to "Last File Received"?

**Comment by AudriusButkevicius** [comment]
See https://github.com/syncthing/syncthing/pull/1094 for arguing.
But 'Last File Received' perhaps makes sense.

**Comment by Novox** [comment]
Didn't mean to argue :) but thank you!
