### ISSUE TITLE
Staggered scanning

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#1150]
If you have lots of shared folders and Syncthing detects changes in most of them the resulting scan causes heavy I/O load because all folders are scanned at the same time. A quick test (move files and then do manual scan folder by folder) showed much faster scanning times.

**Comment by calmh** [comment]
^ That's one way of solving the issue of the scans staying in sync. A single queue would be another way, but is much more moving parts and there are cases where you legitimately want to scan folders in parallel (they are on different disks, for example).
