### ISSUE TITLE
Button to rescan all folders

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#1151]
A helpful feature (together with #1150 and #1152) when using lots of shared folders would be a "rescan all" button (could be located next to "add folder"). Current workaround: restart Syncthing

**Comment by p1rox** [comment]
+1

**Comment by krozycki** [comment]
I'll try to do this.

**Comment by uok** [comment]
Thanks! It would be great if you could implement "staggered" scanning, e.g. click on "rescan all" - starts scan folder A, waits until this folder status != scanning any more, then continues folder B, etc.

**Comment by krozycki** [comment]
Is there a limit of somekind on how often StateChanged event can be emitted? I wrote rescaning folders sequentially, but if it ends fast then the statuses aren't able to change appropriately in time.

**Comment by AudriusButkevicius** [comment]
I think the way this should be done is by adding a /rest/rescanAll call in Go land (probably with an optional sequential=true flag) this way you don't need any magic in the JS.

**Comment by AudriusButkevicius** [comment]
Or just have a special case of current /rest/rescan to rescan everything if no folder is provided.
