### ISSUE TITLE
Allow rescan during sync

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#1152]
If you add/remove/etc. files during ongoing syncs the changes are not detected unless you restart Syncthing (which interrupts sync) or wait (long time) for (big) transfers to finish.

**Comment by calmh** [comment]
Sounds like the original issue here is a file modified directly after a scan, plus a long scan interval. I don't think scanning in parallel with pulling would alter this equation that much?

**Comment by AudriusButkevicius** [comment]
Yeah this is invalid.
