### ISSUE TITLE
Deal with nested folders

### ISSUE THREAD

**Issue by marclaporte** [syncthing/syncthing#1167]
If this can be made to work reliably, that's great. I love to be able to have different sync rules per folder. However, I would also love to put them all in one master folder, and have an rsync-like backup of that. There are surely many valid use cases for this. But I can also see it bringing some risk.

If not, it would be great to have a warning upon detection. Ex: "Syncthing has detected nested folders. This is untested, and could cause issues. You should remove the nesting or proceed with cautious and report any issues to the Syncthing bug tracker"

@calmh wrote: "This subfolder concept is something that's completely untested, so I'm not surprised if there are issues. Remember, syncthing has no idea of the nesting here, so changes it itself does on "folder B" will be picked up by the scanner as user generated changes on "folder A", changes received from the outside will be attempted to be applied twice, etc..." Source: https://github.com/syncthing/syncthing/issues/1153#issuecomment-68260905

Synonyms: embedded folders  embedding folders  recursive folders  nesting folders

**Comment by calmh** [comment]
As a side note here for those wanting to do this in the meantime, I think it's probably fine if all but one of the nested folders are "master" folders. That is, for any given file in the filesystem, there's only one folder covering it that is responsible for *changing* it. Other folders should be "master" and thus only pick up changes made to the filesystem by others (or by the non-master folder).

**Comment by RafiKueng** [comment]
I did try using nested folders with three nodes (main, backup, mobile) with `pictures` folder shared between main and backup and a subfolder of it, `DCIM` that was shared between main and mobile. The idea: on the main machine I'll sort photos by taking them from `DCIM` and putting them in designated folders from time to time. This process will then automatically delete the files on the mobile. I always have a backup of all photos, either sorted or not.

Worked fine so far, the only problem I got was when I deleted the doubly shared subfolder on backup, then it couldn't sync because it could not remove the folder, because of the .stfolder file in a subfolder of `pictures`.

I don't have any folder selected as a master, but the "flow of files" is always the same (phone -> main in `DCIM`, main->backup in `pictures`), and no conflicts will be possible (due to the mobile naming the files by date), so it's only a restricted test of this setup..

**Comment by basilweibel** [comment]
I am only a user and cannot help with development. I only want to say that I would appreciate this feature (if I understood correctly). Use case would be sharing with other people:

Folder Structure:
/business_administration/marketing
/business_administration/accounting

Share /business_administration with board members and with backup server.
Share only /business_administration/marketing with marketing people
Share only /business_administration/accounting with accounting people.
Share read only /business_administration/accounting with external consultant.

Or is this already possible and I didn't figure it out. It's kind of having a syncthing folder within a syncthing folder.

**Comment by ctheune** [comment]
I have a similar issue but more about avoiding accidents. I have a similar folder structure:

```
/sync/board
/sync/team
```

So a master folder (that is not synced) and two folders as different syncs for different people, with some people having access to both.

Setting up a new server I accidentally stored both in the same location and caused mayhem of all folders ending up everywhere.

From my perspective it warrants either a warning or blocking an action if syncs are nested inside each other or are on the same path.  Is this right here, or should I open a new ticket?

**Comment by calmh** [comment]
Frankly I'm not 100% sure what this is issue is about, concretely. Nested folders work today, but there are some caveats like @ctheune noted and the fact that a change from another device in one folder gets picked up as a local change by the other folder sharing the same path... I'm not sure what to do about that...

So what's the actual action on this ticket?

**Comment by ctheune** [comment]
From my perspective, I'd love if I could get a warning if I created this situation of cross-nesting - but again, should I make a different ticket?

**Comment by calmh** [comment]
@ctheune Please do, and then we'll see what this gets clarified as.

**Comment by novoid** [comment]
see also https://github.com/syncthing/docs/issues/269

**Comment by calmh** [comment]
Since nothing has clarified since my last question a year ago I'm closing this.

**Comment by LeSam** [comment]
I also want to do the phone camera<->subfolder of shared directory sync. For me it would be enough to say that the global directory media/pictures/camera is sync'd to the phone syncthing folder top level. I think this is not too hard to add, I am willing to write some code to make this happen.
