### ISSUE TITLE
[bug] Removed devices are synced later on

### ISSUE THREAD

**Issue by generalmanager** [syncthing/syncthing#1170]
Version: 0.10.14

To reproduce: 
1. Add device B on device A and vice versa.
2. Remove device B on device A.
3. Add device C on device A and vice versa.
4. Set device A as introducer.

Expected behaviour:
Only currently used devices get synced from A to C.

Witnessed behaviour:
Device B is synced from device A to device C.

**Comment by AudriusButkevicius** [comment]
If the device is not listed, it's impossible for it to be synced.
If it's listed it means it either was not removed, or was reintroduced by someone.

**Comment by generalmanager** [comment]
That's rather funny, as I'm sure that the device wasn't introduced by another source as it wasn't added on another device. I also restarted the node after removing the device.

If you are sure, feel free to close this tough and I'll try to reproduce this in a completely clean environment when I have some spare time.

**Comment by AudriusButkevicius** [comment]
There is a glitch with the web UI, where after restarting syncthing, the GUI actions seem to succeed but they actually fail (because the after a restart the session cookie is no longer valid and the browser doesn't reauthenticate), hence your step 2 might have failed without you even realizing.

**Comment by generalmanager** [comment]
Alright, I'll close this now and investigate later.
