### ISSUE TITLE
incompatibility with  MV-88fxx81

### ISSUE THREAD

**Issue by rchovan** [syncthing/syncthing#1173]
Hi, when I want to run syncthing on Synology DS 107+ I get error 
```
Illegal instruction (core dumped)
```
I have tried latest release (0.10.14) for ARM5, ARM6, ARM7

Strace log:

```
strace -f ./syncthing
execve("./syncthing", ["./syncthing"], [/* 20 vars */]) = 0
getpid()                                = 1
--- SIGILL (Illegal instruction) @ 0 (0) ---
+++ killed by SIGILL (core dumped) +++
Illegal instruction (core dumped)
```

This is my cpu:
```
Processor	: ARM926EJ-Sid(wb) rev 0 (v5l)
BogoMIPS	: 499.71
Features	: swp half thumb fastmult vfp edsp
CPU implementer	: 0x41
CPU architecture: 5TEJ
CPU variant	: 0x0
CPU part	: 0x926
CPU revision	: 0
Cache type	: write-back
Cache clean	: cp15 c7 ops
Cache lockdown	: format C
Cache format	: Harvard
I size		: 32768
I assoc		: 1
I line length	: 32
I sets		: 1024
D size		: 32768
D assoc		: 4
D line length	: 32
D sets		: 256

Hardware	: MV-88fxx81
Revision	: 0000
Serial		: 0000000000000000
```

**Comment by calmh** [comment]
Looks like it generates a core file. Can we have that file uploaded somewhere? It might help with narrowing down what's going on.

**Comment by rchovan** [comment]
yes of course, here: https://www.dropbox.com/sh/gwpgwilyysehpdw/AADZ5MczUjlzo8WcSIokhJsya?dl=0

**Comment by calmh** [comment]
(I couldn't open that core file, maybe due to my amd64 gdb not understanding arm core dumps... Going to look deeper at that later.)

**Comment by rchovan** [comment]
Hi, 
tested latest release v0.10.19, but does not work on my Synology NAS. 
core uploaded to previous dropbox link

**Comment by calmh** [comment]
There have been fixes to Go for ARM lately that I hope affects this. If not, I'm not sure where to go with it.

**Comment by rchovan** [comment]
problem not solved. 
uploaded coredump from latest version to dropbox link ^^^, please reopen

**Comment by Zillode** [comment]
Maybe we can try a gccgo variant
