### ISSUE TITLE
Automatic upgrade: couldn't fetch release information

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#1175]
copied from [forum message](https://discourse.syncthing.net/t/error-0-10-14-automatic-upgrade-couldnt-fetch-release-information/1628)

after starting 0.10.14 I expected, that the automatic update to 0.10.15 started. But instead, I got this messages at the bottom of the website:
17:17:13: Automatic upgrade: couldn't fetch release information
and
17:32:31: upgrading: no such file or directory
I tried to update manually by clicking on the blue update button, but it needs one syncthing restart to get the update.
Seen on Win 8.1 32 bit, Win7 64 bit, FreeBSD 64 bit.

**Comment by jpjp** [comment]
Could the release notes be more explicit that automatic upgrades are currently broken and manual intervention is required? We had this in the past...

**Comment by calmh** [comment]
I'm just looking into how broken it is exactly...

**Comment by calmh** [comment]
Relevant notes added. Most people are probably fine after a single restart.

**Comment by jpjp** [comment]
Thanks! btw release 100 is next :)

**Comment by calmh** [comment]
... which I'm doing *now* due to another fuckup. Sigh. :/

**Comment by calmh** [comment]
There. 100th time is the charm, yes?

**Comment by uok** [comment]
Thanks for quick fix!
Do unattended devices also update to upcoming release(s) if there is no restart in between?
[Syncthing usage report](https://data.syncthing.net/) shows that ~20% never reach the current version (although I don't have any data to compare from other open source projects about the release distribution)

**Comment by AudriusButkevicius** [comment]
No, sadly they won't until the next restart.
