### ISSUE TITLE
.stignore #include file from another drive (windows)

### ISSUE THREAD

**Issue by SebBiber** [syncthing/syncthing#1176]
I browsed the source code of the ignore.go file. If I read the source code correctly, it is not possible to inlcude patterns for the .stignore file from another disk drive. Is that correct?

If yes, could you add this feature?

Use case:
I have several independent folders and one global ignore file that is valid for all folders. Therefore I add in each folder in the .stignore file just one line:
#include x:\publicFolder\globalIgnore.txt (Windos)
#include /home/publicFolder/globalIgnore.txt (Linux)

The advantage of this use case is that I have to extend just one file (the globalIgnore.txt) to add a global ingore pattern (e.g., the .svn or .git folder) rather than changing the .stignore of all my synchronized folders. The problem is that I have to specify an absolute path, e.g., because the global ignore file is on another drive.

If there is a work around, please tell me.

**Comment by AudriusButkevicius** [comment]
Just use symlinks, hardlinks, junctions.

**Comment by SebBiber** [comment]
Yes of course links. Thanks for the hint. Works for me, unless it is a little bit ugly solution ;-)

**Comment by AudriusButkevicius** [comment]
I feel we have the policy of not crossing the boundry of the folder we are asked to sync.
Starting to travel to random locations for random things will eventually make it hard to manage.
