### ISSUE TITLE
New version notification could alert other known nodes

### ISSUE THREAD

**Issue by jpjp** [syncthing/syncthing#1177]
Today one of my nodes noticed v0.10.16 was available. Maybe it could poke the other nodes to tell them to check for an update. Or maybe they could notice when a newer node contacts them.

**Comment by AudriusButkevicius** [comment]
Your other nodes will poke themselves every 12 hours if it's updated.

**Comment by jpjp** [comment]
Yes, but this suggestion would be like a super poke using the intelligence of all nodes together. Like a beowulf cluster.

**Comment by AudriusButkevicius** [comment]
It's possible.

**Comment by StrikerTwo** [comment]
I think this can wait until some kind of update server for nodes not connected to the internet is implemented, as mentioned in #1085 (https://github.com/syncthing/syncthing/issues/1085#issuecomment-65895239). At best you gain 11 hours and some minutes before all nodes are updated - I don't think updates are that time-critical. But YMMV.

**Comment by AudriusButkevicius** [comment]
This is quite easy to implement as we know the nodes version as we connect, hence if his version is > ours, and automatic upgrades are enabled, check for an upgrade.
