### ISSUE TITLE
SyncThing Protocol Definition link on syncthing.net is broken

### ISSUE THREAD

**Issue by brendanlong** [syncthing/syncthing#1178]
On the main page of syncthing.net, you have a section like:

> <ul><li><strong>Open Protocol.</strong> The protocol is a documented standard &mdash; no hidden magic.
<br><a target="_blank" href="https://github.com/syncthing/syncthing/blob/master/protocol/PROTOCOL.md">Syncthing Protocol Definition</a></li></ul>

But the link is broken. Presumable it's supposed to point to somewhere in https://github.com/syncthing/protocol/

**Comment by calmh** [comment]
Fixed, thanks.
