### ISSUE TITLE
Latest release signed with a new key

### ISSUE THREAD

**Issue by tianon** [syncthing/syncthing#1180]
I was downloading the latest release (v0.10.17) and when I checked the GPG signature on the `sha1sum.txt.asc` file I noticed that it was signed by a new key (ie, [00654A3E](http://pgp.mit.edu/pks/lookup?op=vindex&search=0x00654A3E) instead of [BCE524C7](http://pgp.mit.edu/pks/lookup?op=vindex&search=0xBCE524C7), as [mentioned in the README](https://github.com/syncthing/syncthing#signed-releases)).

The new key is signed by the old key, but neither the README nor https://nym.se/gpg.txt were updated so I wanted to make sure this was intentional. :+1:

**Comment by AudriusButkevicius** [comment]
http://syncthing.net/security.html

**Comment by tianon** [comment]
Oh nice, rock on! :+1:

**Comment by tianon** [comment]
Any particular reason why https://syncthing.net/security.html redirects to http://syncthing.net/security.html instead of the other way around? :angel:

**Comment by AudriusButkevicius** [comment]
Interesting.
AFAIK it's hosted on github, so perhaps they are having some issues?

**Comment by pjz** [comment]
I have autoUpgrade on... is the key change why I now get the message

    0:57:36: upgrading: couldn't fetch release information

when I poke the 'Upgrade To v0.10.17' button?

**Comment by calmh** [comment]
It's behind CloudFlare, they do weird stuff with SSL, and it doesn't work with Github (which is the backend).
