### ISSUE TITLE
Discovery logs are cryptic

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#1188]
Which they are.

**Comment by calmh** [comment]
:D Anything in particular? The "ipv6 discovery not work blah blah" stuff?

**Comment by AudriusButkevicius** [comment]
No, the verbose logs, it's just a hexdump.

**Comment by calmh** [comment]
Ah. It was useful to me at the time. :) But agreed, that can be cleaned up, and should be since it's used by users to debug what's going on more than whether the protocol is actually speaking the right language or not...
