### ISSUE TITLE
syncthing changes permissions for files sync from android

### ISSUE THREAD

**Issue by dvarum12** [syncthing/syncthing#1189]
I have syncthing on android syncing to a linux machine, but the permissions are set incorrect on the linux machine.

The android file manager shows the file as having permissions -rw-rw---- (with owner root:sdcard_r).
Then the files that are sync from android to linux has the permissions set to -rw-rw-rw- (the uid and gid are correct)
I have tried to work around this by adding the option UMask=0027 to my systemd service file, but syncthing override this then the file is completely synced. while the files are syncing the permissions are as they should be -rw-r----- (according to the service file)

I do not expect the permissions set by syncthing to allow anybody to edit the files, of course a easy workaround is to change the permission for the folder (to drwxr-x---), but then the group will still be able the edit the file in the folder if the permissions for the files is set to allow write from everybody.

So what I would want is a option for syncthing to ignore permissions and just set it based on umask or something like that.

Syncthing version
Android - Syncthing v0.10.11 (Syncthing-Android 0.5.13)
Linux (ArchLinux) - syncthing v0.10.14 (go1.4 linux-amd64 default)

**Comment by AudriusButkevicius** [comment]
Is ignore permissions flag set to true?

**Comment by dvarum12** [comment]
okay that work and did what I ask for. Had just got in my head that it was for FAT because it does not support permissions.

Thx for the help

**Comment by ovizii** [comment]
Sorry to revive this old thread but in the above use case; syncing Android with Linux, on which side do you set the "ignore permissions" flag?

**Comment by AudriusButkevicius** [comment]
On the receiving end, if you want the receiving end to ignore them
