### ISSUE TITLE
Syncthing destroys all folder and files encrypted with ENCFS

### ISSUE THREAD

**Issue by gunwald** [syncthing/syncthing#1191]
## What happened
I am syncing an folder with many subfolders and files that are encrypted with `ENCFS`. I am syncing to the mounted (decrypted) but the unmounted (encrypted) files. This used to work well but since I updated to v0.10.15 as soon as I start syncthing all files and folders within this folder become unreadable.
![korrespondenz org_002](https://cloud.githubusercontent.com/assets/1161825/5632003/68fba054-95cb-11e4-9ac3-6e0b6049656f.jpg)

It seems that they are not restorable, but permanently lost.

## What did I expect to happen instead of what did happen
Syncthing should sync files independent of there encryption and should never corrupt files 

## What operating system, operating system version and version of Syncthing am I running
I have Syncthing v0.10.15 on Ubuntu 14.04 running on there machine where the incident happened.

## How to reproduce?
Add an ENCFS encrypted folder to Syncthing and start to sync it with an other device

**Comment by AudriusButkevicius** [comment]
Can you check the permissions on the folder?
I think they might become `d---------` which is a known bug.

**Comment by gunwald** [comment]
Yes, I did it. You are right. With this two commands I solved the issue:

    sudo chown myuser:myuser -R /my/path
    sudo chmod 755 -R /my/path

"What have they done to my files ma, what have they done to my files?
It's the only thing I could do half right and they turned them up side down ma!
What have they done to my files?"

**Comment by AudriusButkevicius** [comment]
Duplicate #1186

**Comment by calmh** [comment]
(So not related to the encryptedness of the files, rather a bug triggered by syncing while another device disconnects.)
