### ISSUE TITLE
Syncthing for android crash on Cyanogenmod

### ISSUE THREAD

**Issue by lupa18** [syncthing/syncthing#1193]
Hello, 

We had installed Syncthing for Android on a Revolution Phone with CM 11 (Android 4.4.4) and the program crashes allways. See image: 

![Crashing](http://i.imgur.com/PSYpz4h.jpg)

thanks in advance

**Comment by AudriusButkevicius** [comment]
This is the wrong repo:
https://github.com/syncthing/syncthing-android

Looks simillar to:
https://github.com/syncthing/syncthing-android/issues/201
Please provide logs, logcat output in the other thread.
