### ISSUE TITLE
File Collision issue

### ISSUE THREAD

**Issue by Rewt0r** [syncthing/syncthing#1195]
Just noticed some strange behaviour. I downloaded an archive of the latest release and extracted the folder within to a directory which is synced, I then renamed the folder and performed an upgrade of Syncthing which then automatically restarted.

Upon restart & reconnection to another device the OLD folder reappeared with no contents. I can reproduce this behaviour every time (I created a batch file for our users to run as an administrator that will upgrade their copy, allows me to test each release first).

Batch if anyone wants it

```bat
@echo off
net stop Syncthing
cd %~dp0
copy /V /Y syncthing.exe C:\Syncthing\
net start Syncthing
echo Upgrade complete
pause
```

**Comment by calmh** [comment]
(Nothing obvious comes to mind, needs investigation)

**Comment by calmh** [comment]
I'm going to go ahead and assume this is no longer the case since a lot of stuff around this changed in v0.11. Otherwise please yell when it happens again.
