### ISSUE TITLE
Reduce amount of scanner threads

### ISSUE THREAD

**Issue by Tiefkuehlpizze** [syncthing/syncthing#1199]
Just a quick thought:
I just created a new repo with some video files in it. Just after Syncthing's restart, my HDD broke out in a terrible activtiy. I think it's because multiple scanner-threads that are indexing my video files, which needs some time due to the filesize. The problem is, that the scanning speed is greatly reduced because of the high seek activity of the hdd.
Is there a possibilty to reduce the amount of scanner-threads? Looking at the handles, currently there might be four scanning-threads accessing the same hdd.

**Comment by AudriusButkevicius** [comment]
I guess you should add the folders one by one and allow them to finish scanning before adding a second one.

**Comment by Tiefkuehlpizze** [comment]
I'm talking about the same repo. Let's assume we have 50 files each 2 GB (no subdirectories).
In worst case I create a new repo from the directory. Syncthing has to index all 50 files at once. That sounds good, but on a hdd it results in a very low reading performance (assuming the index itself is on a seperate hdd oder ssd) because of the multiple file handles which all want to read their whole 2 GB.
The best case would be a single thread reading file by file sequentially and all files aren't physically fragmentent on the hdd. The hdd could read without unnecessary seeking resulting in highest transfer rates (typically 80-120 MB per second).

Knowing this issue, I have started this process last night for about 90 GB. From the logs I could see, it took about 4 hours and 30 minutes. That would make a reading rate of roughly 6 MB/s (and of course terribly hdd-noise). Assuming a fixed reading delta at 100 MB/s sequential reading, the whole process could have been finished in less than 20 minutes (if there are no further bottlenecks).

I hope I could make my case clear for you.

**Comment by AudriusButkevicius** [comment]
Ah yes, there is a parallel hasher, which defaults to NumberOfCores threads, you are right.
I guess it was done under the assumption that the kernel is clever enough and reads ahead, hence causing the next read cheap.

@calmh ?

I guess it wouldn't hurt to have an setting for number of hashing routines.

**Comment by uok** [comment]
Thanks, a setting to tame scanning would help a lot (see #1150)

**Comment by calmh** [comment]
Mmmyes, could add such a setting. I'd think most modern operating systems handle it quite well, seeing the four streaming workloads and doing the appropriate readahead, and keeping the filesystem layer "saturated" with requests it can reorder and prioritize is usually the best way to get the most performance out of it. (Of course there are exceptions.) And of course this is a bit selfish, as it doesn't necessarily "leave" much performance on the table for other tasks.

But a `hashers` setting per folder, symmetrical with the existing `copiers`, `pullers` etc settings would work fine. Maybe default to 2 or something more conservative. I wouldn't suggest exposing it in the GUI (either) as it's an advanced setting most users probably shouldn't be fiddling with...

(As an aside, maybe the `finishers` config should go away now that the finisher does almost no work and there is no gain in parallellizing it.)

**Comment by Tiefkuehlpizze** [comment]
Sounds good to me. I would love to see this.
Either you don't notice the heavy load on your SSD or you're completly right and the OS handles this quite good.
But I believe my Win 8.1 (NTFS) can't help, if 4 threads a permanently requesting data from the hdd.
My raspi with it's USB-hdd (ext4) is limited through it's CPU and does the scanning as fast as my tower. That makes me believe, that something could be optimized.
