### ISSUE TITLE
Multiple entries of the same file appear in the receiving host transfer list

### ISSUE THREAD

**Issue by Novox** [syncthing/syncthing#1201]
What happened:
After adding and removing a file multiple times to test another issue, I noticed multiple of the same exact file appear in the receiving host transfer list.

What did you expect to happen instead of what did happen, if it's not crazy obvious:
Not sure... clear the entries out of the list I suppose

What operating system, operating system version and version of Syncthing you are running
Receiving: Windows Server 2012 R2
Sending: Windows 8.1 Pro

Screenshot if the issue concerns something visible in the GUI:
![capture](https://cloud.githubusercontent.com/assets/10436186/5647310/d073304e-9652-11e4-8a8a-8aeb122077b7.PNG)

Console log entries, where possible and relevant:
[XV4KT] 09:29:58 INFO: Puller (folder "Sync", file "[redacted]"): pull: no available source device
[XV4KT] 09:38:32 INFO: Puller (folder "Sync", file "[redacted]"): pull: no available source device
[XV4KT] 09:38:59 INFO: Puller (folder "Sync", file "[redacted]"): pull: no available source device
[XV4KT] 09:39:21 INFO: Puller (folder "Sync", file "PS4UPDATE.PUP"): pull: no available source device
[XV4KT] 09:39:22 INFO: Puller (folder "Sync", file "PS4UPDATE.PUP"): pull: no available source device
[XV4KT] 09:39:23 INFO: Puller (folder "Sync", file "PS4UPDATE.PUP"): pull: no available source device
[XV4KT] 09:39:24 INFO: Puller (folder "Sync", file "PS4UPDATE.PUP"): pull: no available source device
[XV4KT] 09:39:25 INFO: Puller (folder "Sync", file "PS4UPDATE.PUP"): pull: no available source device
[XV4KT] 09:39:26 INFO: Puller (folder "Sync", file "PS4UPDATE.PUP"): pull: no available source device
[XV4KT] 09:39:27 INFO: Puller (folder "Sync", file "PS4UPDATE.PUP"): pull: no available source device
[XV4KT] 09:39:28 INFO: Puller (folder "Sync", file "PS4UPDATE.PUP"): pull: no available source device
[XV4KT] 09:39:29 INFO: Puller (folder "Sync", file "PS4UPDATE.PUP"): pull: no available source device

**Comment by AudriusButkevicius** [comment]
I know why this is happening.
Thanks for the report.

**Comment by AudriusButkevicius** [comment]
I assume the hidden file is also the same on all 4 instances?
It's strange that it shows half downloaded but the progress bar is empty.

**Comment by Novox** [comment]
Yes, the "redacted" file name... (dunno if you guys care about my personal file habits...) was identical (before redaction), and it was transferring, but as you noticed, the progress bar wasn't moving for any of the 4 instances.
