### ISSUE TITLE
While syncing, both sides show "Up to Date" in device status

### ISSUE THREAD

**Issue by Novox** [syncthing/syncthing#1202]
What happened:
The UI in the device area for both sender and receiver shows "Up to Date" WHILE they are syncing... I can understand if the sender is "Up to Date," but the receiver shouldn't also be "Up to Date", right?

What did you expect to happen instead of what did happen, if it's not crazy obvious:
I expected it to say "Syncing..." at least on one side.

What operating system, operating system version and version of Syncthing you are running
Receiving: Windows Server 2012 R2
Sending: Windows 8.1 Pro

Screenshot if the issue concerns something visible in the GUI:
![receiver](https://cloud.githubusercontent.com/assets/10436186/5647396/93c2d7a2-9653-11e4-9b09-0416c445fd08.png)
![sender](https://cloud.githubusercontent.com/assets/10436186/5647397/96746614-9653-11e4-8441-8b9a15d0bdd6.png)

Console log entries, where possible and relevant

**Comment by calmh** [comment]
Weird

**Comment by Alwaysin** [comment]
It has always done this with me, I thought it was per design : display "Syncing..." when retrieving and comparing list of files or whatever (dunno how it works!) and "Up to Date" once it has been done.

**Comment by AudriusButkevicius** [comment]
The network usage could be todo with index transfers rather than file transfers though?

**Comment by Novox** [comment]
As you can see however, both sides are showing "Up to Date" and the "rates" are in the MiB/s so I hope it's evident that it in the middle of a transfer at the time.

**Comment by Novox** [comment]
This was happening while I posted issue #1201 , which contains a screenshot of files being transferred.  So I'm pretty sure it was file data.

**Comment by Novox** [comment]
I'll try to reproduce...

**Comment by AudriusButkevicius** [comment]
I guess it could be the case where the percentage is above %100 due to deleted files, causing it to show up up to date?

**Comment by Novox** [comment]
This was different from #1200 so as I recall, the syncing percentage during this time was correct.  Still trying to reproduce.

**Comment by Novox** [comment]
Confirmed, I can reproduce the issue.  I've attached a screenshot of the sender side:
![sender](https://cloud.githubusercontent.com/assets/10436186/5647900/ffd2ce8a-9657-11e4-8089-53b85fafdb54.png)

and the receiver side:
![receiver](https://cloud.githubusercontent.com/assets/10436186/5647902/0463acb2-9658-11e4-90f3-3f1de077f0ab.png)

I added a ~2.5GB file to the sender side.  Sender took a while to "Scan" it (I assume it's checksumming or something), then when it was done, started transfer with receiver.  Device status on both shows "Up to Date".

ALSO: If I "refresh" the sender web browser, the device status for the receiver properly shows "Syncing (XX%)"  If I refresh the receiver web browser, the device status for the sender stays as "Up to Date" (which I think is technically correct... the Sender is indeed... Up to Date)

Also note that the Global State and Local State of the folder on the sender side, didn't properly update after it scanned, found the new file, and started sending, until after I "refresh" the sending web browser, but I'll open a new issue for that.

**Comment by simplypeachy** [comment]
It occurrs to me that this is a matter of perspective. Having been looking at this I've been interpreting the peer device panels incorrectly, as saying "Local device's sync status with peer device". If you're device B with 50 files, and device A has all 100, then one would expect the peer status to read "Syncing (50%)"

What the peer status panels are telling you is how the peer sees itself. Device A has all 100 files. It is up-to-date. It will see Device B as 50% because that's Device B's status.

One thing that is buggy here is that the peer device status never reads "Scanning". If a large amount of data is being hashed on a peer, it is confusing to see it as "Up to date".

**Comment by calmh** [comment]
Pretty sure the original issue here is solved a long time ago
