### ISSUE TITLE
File addition to sender host does not update "Global State" until browser refresh

### ISSUE THREAD

**Issue by Novox** [syncthing/syncthing#1203]
What happened:
I added a 2.5GB file to my sender side, and after a lengthy scan (checksumming?) it started to send to the receiver, but did not update the Global State until I refreshed the sender host web browser.

What operating system, operating system version and version of Syncthing you are running
Receiver: Windows Server 2012 R2
Sender: Windows 8.1 Pro

Screenshot if the issue concerns something visible in the GUI:

Sender Side after adding 1 ~2.5GB file, but before browser refresh:
![sender before](https://cloud.githubusercontent.com/assets/10436186/5648053/5d1317c0-9659-11e4-975f-55a996d9ec7a.png)

Sender side after browser refresh:
![sender after](https://cloud.githubusercontent.com/assets/10436186/5648057/6486d384-9659-11e4-8a58-990140b17daf.png)

**Comment by AudriusButkevicius** [comment]
This gets refreshed every 10 seconds or so, that could be the cause.
I feel that notifications to update these should be done via the update interface.

**Comment by Novox** [comment]
I waited multiple "Scan" intervals (60 seconds) and the "Up to Date" would momentarily switch to "Scanning,"  but finding no new files to send, almost immediately went back to "Up to Date," so it was definitely more than 10 seconds.  (I wouldn't have been able to get all my screenshots of it was a 10 second window).

How else can I help?  Is there a different test you'd like me to perform?

**Comment by AudriusButkevicius** [comment]
No, I need to look into this first.

**Comment by Novox** [comment]
Certainly... I'll keep an eye on my issues to look for updates from you.

**Comment by calmh** [comment]
Reproducer for this? I've never seen it happen.
