### ISSUE TITLE
Sycning % on Sender side not properly updating

### ISSUE THREAD

**Issue by Novox** [syncthing/syncthing#1204]
What happened:
While transferring a large ~2.5GB file from sender to receiver, sender side shows incorrect Syncing % of 41%, while receiver side updates properly, 87%

What did you expect to happen instead of what did happen:
perhaps the sender host doesn't update Sync % until after each file is transferred, but the receiving side seems to be updating it very frequently during transfer

What operating system, operating system version and version of Syncthing you are running:
Receiver: Windows Server 2012 R2
Sender: Windows 8.1 Pro

Screenshot if the issue concerns something visible in the GUI:

Sender side, Sync % stuck:
![sender](https://cloud.githubusercontent.com/assets/10436186/5648345/cfb2b8e2-965b-11e4-875d-c1f5e0dcda18.png)

Receiver side, Sync % properly updating:
![receiver](https://cloud.githubusercontent.com/assets/10436186/5648352/da1490b2-965b-11e4-8edb-86b380d8b8e9.png)

**Comment by Novox** [comment]
I included the time in my screenshots to show that the shots were taken at about the same time... 1 minute apart, accounting for time zone differences...

**Comment by Novox** [comment]
I should also note, refreshing sender browser has no effect. Sync still at 41%

**Comment by AudriusButkevicius** [comment]
This is expected, as the sender is only notified after the whole file is done.

**Comment by Novox** [comment]
Understood, I figured that might be the case, thanks!
