### ISSUE TITLE
Define a virtualhost for syncthing in nginx

### ISSUE THREAD

**Issue by zaralger** [syncthing/syncthing#1205]
Hi,
I'd like to define a different URL to access my syncthing page like: sync.mydomain.com
is there a simple way to do so with nginx ? 

thanks in advance !

**Comment by AudriusButkevicius** [comment]
Yeah, you just need to setup a nginx proxy, but this is definately not the place.
I think there was a guide on the forums, so I suggest you search through discourse.syncthing.net
