### ISSUE TITLE
New Feature Request: Allow Devices to Override IP reported to Discosrv (for NAT/self hosted discosrv environments)

### ISSUE THREAD

**Issue by Novox** [syncthing/syncthing#1206]
For instance, I run discosrv locally, and I have a local SyncThing node communicating with the local discosrv.

The IP address SyncThing reports to discosrv is the *internal/local* ip address (a non-routable because I'm behind a NAT).  When other external nodes connect to this same discosrv, they are presented with the internal IP for the local SyncThing instance, and therefore, can never contact it...

I tried modifying the "Sync Protocol Listen Addresses" in settings to reflect the External IP, but this seems to crash SyncThing after three attempts (and I'm guessing it's because SyncThing can't bind to listen on an IP address NOT assigned to the node).

i.e.
Local Node A:
Internal IP = 192.168.1.5
External IP = 123.123.123.5 (via nat port forwarding)

SyncThing on Node A reports "192.168.1.5" as its IP to Discosrv.

Remote Node B:
External IP: 234.234.234.5

SyncThing on Node B reports "234.234.234.5" as its IP to Discosrv

Result:
234.234.234.5 can't communicate with 192.168.1.5, but I believe it could if I could override Node A's advertised IP to be 123.123.123.5...

Potential Workaround:
Set Node A Device (on Node B) to have "Addresses" of  "123.123.123.5:22000", but I would have to do this on all Nodes attempting to connect to Node A, defeating the purpose of Discosrv...

Potential Caveats:
If Node A is behind a dynamic IP, and ISP's DHCP refreshes the IP lease to a new IP, Node A's advertised IP would become incorrect.

**Comment by AudriusButkevicius** [comment]
I feel this is a very specific usecase relevant to your scenario and would not gain a lot of use by others though.

**Comment by Novox** [comment]
Fair enough.
