### ISSUE TITLE
New Feature Request: Add a "Last Status Time" to "Up to Date" (connected) remote device status UI

### ISSUE THREAD

**Issue by Novox** [syncthing/syncthing#1207]
Low to Zero Priority :)

When a remote device is "Disconnected", "Last Seen" indicates when it was... last seen...

When a remote device is connected and shows rates, address, version, Folders, etc... perhaps add a "Last Status Time" to the UI to indicate when the connection was last confirmed/online?

If the connected status has a very short check interval, like 60 seconds, then disregard... and one can assume it was last connected <= 60 seconds ago.  If however, the connected status is polled every 5+ minutes or so, it may be worth showing that in the UI?

If not a Date/Time, how about a "Last Update" with values such as:
 "Just Now"
1 second
2 seconds
3 seconds... etc...
using a count up timer...

Some random Mocks...
![mock1](https://cloud.githubusercontent.com/assets/10436186/5649824/0e09678e-9667-11e4-9d67-48b44b94b1f0.png)
![mock2](https://cloud.githubusercontent.com/assets/10436186/5649825/107b50cc-9667-11e4-825e-8fa090096921.png)
![mock3](https://cloud.githubusercontent.com/assets/10436186/5649826/130faa36-9667-11e4-8187-8bb4bcdd5996.png)
![mock4](https://cloud.githubusercontent.com/assets/10436186/5649829/14e19716-9667-11e4-938c-364cf0e0a8b2.png)

**Comment by AudriusButkevicius** [comment]
They ping each other every 5 or so seconds, and exchange indexes when either side notices that something has changed.

**Comment by Novox** [comment]
Understood, at a 5 second "ping" interval, I'll consider the "Up to Date" status to be real-time, and this is a non-issue.

Thanks!
