### ISSUE TITLE
A file I deleted during transfer leaves errant ~syncthing~.{filename}.tmp

### ISSUE THREAD

**Issue by Novox** [syncthing/syncthing#1208]
What happened:
I started syncing a file, then deleted it from the sending host.  The partial file remains on the receiving host as a ~syncthing~.{filename}.tmp file.

What did you expect to happen instead of what did happen, if it's not crazy obvious:
Delete the .tmp file when the file is deleted, however, this then might break "Allow partial downloads to be available for pulling" #950...  

Perhaps if the file is currently transferring or *hasn't* been marked "Deleted," (in the case where either node goes offline during transfer or there is other network connectivity issues) retain the tmp file (to allow resume)?  If the file *has* been marked "Deleted" from the sender, then delete the tmp file?

What operating system, operating system version and version of Syncthing you are running:
Receiver: Windows Server 2012 R2
Sender: Windows 8.1 Pro

**Comment by AudriusButkevicius** [comment]
It will go away in `keepTemporariesH` hours (defined in config.xml).
