### ISSUE TITLE
Receiving many "TLS handshake error[s]" with HTTPS UI enabled

### ISSUE THREAD

**Issue by Novox** [syncthing/syncthing#1210]
What happened:
HTTPS web UI intermittently responds (probably due to handshake errors), but eventually WILL respond after I force browser refresh.

What operating system, operating system version and version of Syncthing you are running
Receiver: Windows Server 2012 R2
Sender: Windows 8.1 Pro

Console log entries, where possible and relevant

2015/01/07 16:01:56 http: TLS handshake error from X.X.X.X:62283: WSARecv tcp 10.215.40.52:8080: An established connection was aborted by the software in your host machine.
2015/01/07 16:01:56 http: TLS handshake error from X.X.X.X:62273: WSARecv tcp 10.215.40.52:8080: An established connection was aborted by the software in your host machine.
2015/01/07 16:01:56 http: TLS handshake error from X.X.X.X:62275: WSARecv tcp 10.215.40.52:8080: An established connection was aborted by the software in your host machine.
2015/01/07 16:01:56 http: TLS handshake error from X.X.X.X:62274: WSARecv tcp 10.215.40.52:8080: An established connection was aborted by the software in your host machine.
2015/01/07 16:01:56 http: TLS handshake error from X.X.X.X:62286: WSARecv tcp 10.215.40.52:8080: An established connection was aborted by the software in your host machine.
2015/01/07 16:01:56 http: TLS handshake error from X.X.X.X:62285: WSARecv tcp 10.215.40.52:8080: An established connection was aborted by the software in your host machine.
2015/01/07 16:01:57 http: TLS handshake error from 127.0.0.1:51974: EOF
2015/01/07 16:02:04 http: TLS handshake error from 127.0.0.1:51975: EOF
...
2015/01/07 16:06:11 http: TLS handshake error from X.X.X.X:62344: EOF
2015/01/07 16:06:11 http: TLS handshake error from X.X.X.X:62346: EOF
2015/01/07 16:06:12 http: TLS handshake error from 127.0.0.1:52032: EOF
2015/01/07 16:06:12 http: TLS handshake error from 127.0.0.1:52028: EOF
2015/01/07 16:06:12 http: TLS handshake error from 127.0.0.1:52034: EOF
2015/01/07 16:06:12 http: TLS handshake error from 127.0.0.1:52036: EOF
2015/01/07 16:06:12 http: TLS handshake error from 127.0.0.1:52035: EOF

**Comment by Novox** [comment]
In both Chrome Version 39.0.2171.95 m and IE 11.0.9600.17498

**Comment by AudriusButkevicius** [comment]
If you use the wrong protocol, then I guess it's expected.

**Comment by AudriusButkevicius** [comment]
It's likely you left a http tab somewhere, and AJAX kept hammering over http oppose to https after the change.

**Comment by uok** [comment]
These log entries seem to happen if a device tries to connect to another device that is not added via Syncthing in the opposite direction

**Comment by Novox** [comment]
overnight, after I was logged out of my workstation (so no browsers were running, otherwise your AJAX comment would make sense), I received many many:

...
2015/01/08 08:17:10 http: TLS handshake error from 127.0.0.1:60513: EOF
2015/01/08 08:29:28 http: TLS handshake error from 127.0.0.1:60632: EOF
2015/01/08 08:35:10 http: TLS handshake error from 127.0.0.1:60675: EOF
2015/01/08 08:35:10 http: TLS handshake error from 127.0.0.1:60677: EOF
2015/01/08 08:35:10 http: TLS handshake error from 127.0.0.1:60676: EOF
2015/01/08 08:39:08 http: TLS handshake error from 127.0.0.1:60717: EOF
2015/01/08 08:39:08 http: TLS handshake error from 127.0.0.1:60716: EOF
2015/01/08 08:39:08 http: TLS handshake error from 127.0.0.1:60715: EOF
2015/01/08 08:40:58 http: TLS handshake error from 127.0.0.1:60738: EOF
2015/01/08 08:40:58 http: TLS handshake error from 127.0.0.1:60737: EOF
2015/01/08 08:40:58 http: TLS handshake error from 127.0.0.1:60739: EOF
2015/01/08 08:41:28 http: TLS handshake error from 127.0.0.1:60747: EOF
2015/01/08 08:42:00 http: TLS handshake error from 127.0.0.1:60752: EOF
2015/01/08 08:42:00 http: TLS handshake error from 127.0.0.1:60753: EOF
2015/01/08 08:47:48 http: TLS handshake error from 127.0.0.1:60802: EOF
2015/01/08 08:48:18 http: TLS handshake error from 127.0.0.1:60808: EOF
2015/01/08 08:48:18 http: TLS handshake error from 127.0.0.1:60809: EOF
2015/01/08 08:48:18 http: TLS handshake error from 127.0.0.1:60810: EOF
2015/01/08 08:48:18 http: TLS handshake error from 127.0.0.1:60811: EOF
2015/01/08 08:48:28 http: TLS handshake error from 127.0.0.1:60816: EOF
2015/01/08 08:48:28 http: TLS handshake error from 127.0.0.1:60815: EOF
2015/01/08 08:48:38 http: TLS handshake error from 127.0.0.1:60819: EOF
2015/01/08 08:48:38 http: TLS handshake error from 127.0.0.1:60820: EOF
2015/01/08 08:56:08 http: TLS handshake error from 127.0.0.1:60891: EOF
...

Which, to me, says localhost cannot access localhost.

Is any part of SyncThing attempting to open a connection to it's own web server?

**Comment by AudriusButkevicius** [comment]
Syncthing never connects to itself.
External utilities such as cli or inotify stuff does though.

The fact that it's the loopback address does not imply syncthing.
Maybe you have some local port scanner, or some other service which expects to hit that port...

I suggest you use some socket watcher to work out what's opening these sockets towards syncthings web UI, as it's definitely not itself.

Nobody else is having this issue, hence I am sure it's specific to your setup.

**Comment by Novox** [comment]
Fair enough, I'll let it be. Thanks.

**Comment by AudriusButkevicius** [comment]
Just to make myself clear, I am not trying to rant, accuse or insult anyone.
But until you provide steps on how to reproduce this issue, I don't believe it exists out of your  environment, hence either you need to do your homework and work out what's causing it, or provide steps of reproduction.

Given the connection is being made every 30 seconds, it's fairly easy for a computer-literate person to work out what's causing these.

**Comment by Novox** [comment]
netstat -a -n -o reveals:

  TCP    127.0.0.1:8080         127.0.0.1:63110        ESTABLISHED     2908
  TCP    127.0.0.1:8080         127.0.0.1:63129        TIME_WAIT       0
  TCP    127.0.0.1:8080         127.0.0.1:63130        ESTABLISHED     2908
  TCP    127.0.0.1:8080         127.0.0.1:63134        TIME_WAIT       0
  TCP    127.0.0.1:8080         127.0.0.1:63136        TIME_WAIT       0
  TCP    127.0.0.1:8080         127.0.0.1:63139        TIME_WAIT       0
  TCP    127.0.0.1:8080         127.0.0.1:63140        TIME_WAIT       0
  TCP    127.0.0.1:8080         127.0.0.1:63148        TIME_WAIT       0
  TCP    127.0.0.1:8080         127.0.0.1:63157        TIME_WAIT       0
  TCP    127.0.0.1:8080         127.0.0.1:63160        ESTABLISHED     2908
  TCP    127.0.0.1:8080         127.0.0.1:63161        ESTABLISHED     2908
  TCP    127.0.0.1:8080         127.0.0.1:63163        ESTABLISHED     2908
  TCP    127.0.0.1:8080         127.0.0.1:63164        TIME_WAIT       0
  TCP    127.0.0.1:8080         127.0.0.1:63165        ESTABLISHED     2908
  TCP    127.0.0.1:8080         127.0.0.1:63166        TIME_WAIT       0
  TCP    127.0.0.1:8080         127.0.0.1:63167        TIME_WAIT       0
  TCP    127.0.0.1:8080         127.0.0.1:63168        ESTABLISHED     2908
  TCP    127.0.0.1:8080         127.0.0.1:63169        ESTABLISHED     2908
  TCP    127.0.0.1:8080         127.0.0.1:63170        ESTABLISHED     2908
  TCP    127.0.0.1:8080         127.0.0.1:63171        ESTABLISHED     2908
  TCP    127.0.0.1:8080         127.0.0.1:63172        ESTABLISHED     2908

PID 2908 is syncthing

![capture](https://cloud.githubusercontent.com/assets/10436186/5667382/6867afc8-9735-11e4-8a67-b948e9f793fc.PNG)

syncting is also listening:

  TCP    0.0.0.0:8080           0.0.0.0:0              LISTENING       2908
  TCP    0.0.0.0:22000          0.0.0.0:0              LISTENING       2908
TCP    [::]:8080              [::]:0                 LISTENING       2908
TCP    [::]:22000             [::]:0                 LISTENING       2908
UDP    0.0.0.0:21025          *:*                                    2908
UDP    0.0.0.0:58067          *:*                                    2908
UDP    [::]:21025             *:*                                    2908

still investigating...

**Comment by AudriusButkevicius** [comment]
I assume 2908 could also imply the receiving end?
Can you provide a dump of your config.xml (or /rest/config ?)

**Comment by Novox** [comment]
Yeah, I must assume PID 2908 is the receiver, since there's no way windows knows the PID of the external process.  So far, it just looks like syncthing is properly handling a ton of web requests.

**Comment by AudriusButkevicius** [comment]
Well, you should look not for inbound but outbound sockets.

**Comment by AudriusButkevicius** [comment]
http://technet.microsoft.com/en-gb/sysinternals/bb897437.aspx

**Comment by Novox** [comment]
Ok, I’m running syncthing as a service, using NSSM (with –home “my config folder”).  It is set for automatic startup.

I rebooted the server twice now, and the issue appears to have gone away... all those estabished/time_wait connections are gone; however, during startup I get two handshake errors.  The timing could be very coincidental (i.e. I have some random process attempting to connect at boot time)…

Reboot 1:
…
2015/01/08 13:20:31 http: TLS handshake error from [::1]:49170: EOF
2015/01/08 13:20:31 http: TLS handshake error from [::1]:49169: EOF
…
[XV4KT] 13:20:33 INFO: Completed initial scan (rw) of folder Sync

Reboot 2:
…
2015/01/08 13:25:21 http: TLS handshake error from [::1]:49169: EOF
2015/01/08 13:25:21 http: TLS handshake error from [::1]:49170: EOF
…
[XV4KT] 13:25:24 INFO: Completed initial scan (rw) of folder Sync

To test coincidental timing, I changed the service to “disabled,” rebooted again, waited about 10 minutes, then started the syncthing service.

[XV4KT] 13:49:53 INFO: syncthing v0.10.18 (go1.4 windows-amd64 default) unknown-user@syncthing-builder 2015-01-06 22:12:40 UTC
[XV4KT] 13:49:53 INFO: My ID: …
[XV4KT] 13:49:55 INFO: Starting web GUI on https://0.0.0.0:8080/
[XV4KT] 13:49:58 INFO: Starting UPnP discovery...
2015/01/08 13:50:01 http: TLS handshake error from [::1]:49175: EOF
2015/01/08 13:50:01 http: TLS handshake error from [::1]:49174: EOF
[XV4KT] 13:50:04 INFO: UPnP discovery complete (found 0 devices).
[XV4KT] 13:50:04 INFO: Starting local discovery announcements
[XV4KT] 13:50:04 INFO: Local discovery over IPv6 unavailable
[XV4KT] 13:50:04 INFO: Starting global discovery announcements
[XV4KT] 13:50:04 OK: Ready to synchronize Sync (read-write)
[XV4KT] 13:50:04 INFO: Device … is "…" at [dynamic]
[XV4KT] 13:50:04 INFO: Device … is "…" at [dynamic]
[XV4KT] 13:50:04 INFO: Device … is "…" at [dynamic]
[XV4KT] 13:50:05 INFO: Completed initial scan (rw) of folder Sync
[XV4KT] 13:50:35 INFO: Established secure connection to … at …
[XV4KT] 13:50:35 INFO: Device … client is "syncthing v0.10.18"
[XV4KT] 13:50:35 INFO: Device … name is "…"

I still have the same 2 TLS handshake errors.

I tested this again by stopping the service, deleting my syncthing log file, and restarting the service.  (I didn’t even bother rebooting):

[XV4KT] 13:54:31 INFO: syncthing v0.10.18 (go1.4 windows-amd64 default) unknown-user@syncthing-builder 2015-01-06 22:12:40 UTC
[XV4KT] 13:54:31 INFO: My ID: …
[XV4KT] 13:54:32 INFO: Starting web GUI on https://0.0.0.0:8080/
[XV4KT] 13:54:34 INFO: Starting UPnP discovery...
2015/01/08 13:54:35 http: TLS handshake error from [::1]:49182: EOF
2015/01/08 13:54:35 http: TLS handshake error from [::1]:49183: EOF
[XV4KT] 13:54:40 INFO: UPnP discovery complete (found 0 devices).
[XV4KT] 13:54:40 INFO: Starting local discovery announcements
[XV4KT] 13:54:40 INFO: Local discovery over IPv6 unavailable
[XV4KT] 13:54:40 INFO: Starting global discovery announcements
[XV4KT] 13:54:40 OK: Ready to synchronize Sync (read-write)
[XV4KT] 13:54:40 INFO: Device … is "…" at [dynamic]
[XV4KT] 13:54:40 INFO: Device … is "…" at [dynamic]
[XV4KT] 13:54:40 INFO: Device … is "…" at [dynamic]
[XV4KT] 13:54:41 INFO: Completed initial scan (rw) of folder Sync
[XV4KT] 13:55:12 INFO: Established secure connection to … at ….
[XV4KT] 13:55:12 INFO: Device … client is "syncthing v0.10.18"
[XV4KT] 13:55:12 INFO: Device … name is "…"

Again, the same 2 TLS handshake errors.

To remove NSSM or Windows Services from the picture, I stopped the service, deleted the log file, and manually ran:

syncthing -home "my config folder"

from the command line.  Again, 2 more TLS errors:
2015/01/08 13:58:17 http: TLS handshake error from [::1]:49190: EOF
2015/01/08 13:58:18 http: TLS handshake error from [::1]:49191: EOF

However, this time, I noticed this happened **JUST AS** syncthing starts IE to show me the UI.  I had an **AHA** moment… 

I disabled the “Start Browser” setting, and again, restarted syncthing, no errors…

As soon as I tried to access syncthing with my browser (IE 1.0.9600.17498), it threw the error again…  I tried accessing it with Chrome (Version 39.0.2171.95 m) and I don’t see the error at all…

**Thus, it would appear that IE 1.0.9600.17498 and SyncThing’s TLS implementation aren’t completely compatible; I tend to blame IE, because it’s IE, and because I get no errors from chrome.**

I am therefore leaving the “Start Browser” option OFF when I run syncthing as a service, and I’ll expect to see those errors if I use IE 1.0.9600.17498.

I suspect that this issue could be reproduced by others by using the latest IE to access an HTTPS protected syncthing.

Regarding my many connections from 127.0.0.1:???? to 127.0.0.1:8080, I suspect that was due to "headless" IE browsers (spawned from Windows Services/NSSM and "Start Browser") cluttering the issue.

Unless you want to research making syncthing’s TLS implementation play nicer with IE, I’d consider this case closed.

**Comment by AudriusButkevicius** [comment]
Syncthing is playing nice, you are not using a valid ssl cert and accessing the ui via ip rather than domai which would have a valid cert, hence the error in IE.

You can replace the certificates, they are in the home directory.

**Comment by andrewufrank** [comment]
i see (with 0.11.26, on a arm debian wheezy but also on an amd64 debian jessie) a series of 
cubie125 syncthing[15082]: 2015/10/04 15:52:45 http: TLS handshake error from 127.0.0.1:53825: read tcp 127.0.0.1:53825: i/o timeout
is this something to worry about? i use https - can i find what tries to to connect by http?

thank you!

**Comment by AudriusButkevicius** [comment]
If it's working, then there is nothing to worry about.
