### ISSUE TITLE
Syncthing and Chwala (Kolab) integration (and an example of a PHP integration)

### ISSUE THREAD

**Issue by marclaporte** [syncthing/syncthing#1211]
Hi!

Kolab.org is a powerful mail / calendar / contact server solution (with Roundcube as the webmail)

One of the features is Chwala (Kolab's File Storage Component), which permits to "save to cloud" and "attach from cloud" for the webmail client. Details here:
https://kolab.org/news/2014/08/04/meet-chwala-kolabs-new-file-storage-component
http://aseigo.blogspot.ca/2014/11/chwala.html

All awesome stuff!  It's a bunch of virtual folders with files. I would like Syncthing to sync that data. 

Aaron J. Seigo wrote: "Writing a Chwala backend is adapting a single PHP interface to the
target system: http://git.kolabsys.com/kolab-chwala/tree/lib/file_storage.php
with the two existing examples found here:
http://git.kolabsys.com/kolab-chwala/tree/lib/drivers
and some documentation on creating new drivers here:
http://git.kolabsys.com/kolab-chwala/tree/README.md
The complexity of writing a backend depends mostly on the complexity of the
target system."

Most of the work will likely be done on the Chwala side, but I am adding the ticket here as a reference and also it may lead to some improvements in Syncthing to make integration with external apps easier.

The Kolab / Chwala wish is "Adding Support for Syncthing as One of Multiple Chwala Backends":
https://issues.kolab.org/show_bug.cgi?id=3672

If you are curious of where I am headed with all the integration:
https://suite.tiki.org/Syncthing
https://suite.tiki.org/Kolab

Thanks!

**Comment by AudriusButkevicius** [comment]
I think this is a wontfix, as then we'd have to deal with `insert any framework here` too

**Comment by AudriusButkevicius** [comment]
Plus, what does file management have todo with syncthing?
Syncthing syncs...

**Comment by calmh** [comment]
Looks nice! Don't forget to update the Wiki for community contributions, and do open tickets on whatever is necessary to make the integration smoother!
