### ISSUE TITLE
Open edit device modal for one-click adding

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#1213]
New feature "Device XYZ wants to connect. Add new device?" (#120) works great - Thanks!
It would be nice to have it open the device modal so that the user can enter a name for this device instead of having "XYZ" in the list of devices

**Comment by AudriusButkevicius** [comment]
The remote name gets picked up on first connect.
And you are always edit the device afterwards.

This adds an extra click to your scenario where you want to change the name, but saves one click when adding a device.

**Comment by uok** [comment]
> The remote name gets picked up on first connect anyway.
ok, thanks!
