### ISSUE TITLE
7:59:13: mkdir permission denied

### ISSUE THREAD

**Issue by ktonini** [syncthing/syncthing#1216]
This worked flawlessly on two of the three computers i'm setting it up on (all osx), but I'm getting a permissions error on one of them -

7:59:13: Stopping folder "iTunes" - mkdir /Volumes/Macintosh\ HD/Music: permission denied

The weird thing is the iTunes folder was already made.  I tried removing the folder and letting snycthing make it to no avail, and I tried settings permissions to drwxrwxrwx all the way up the chain.

Any idea what could be causing this?

Thanks!

**Comment by calmh** [comment]
Could be an after effect of #1186; can you try the build in http://build.syncthing.net/job/syncthing-branch/1568/ and see if it mentions "invlid nil filename"s during startup or when connecting to other devices, and hopefully stops trying to mkdir things it shouldnt?

**Comment by ktonini** [comment]
Thanks for getting back so quickly!

Didn't see the "invlid nil falename" error, it pretty much says the same thing-

9:00:43: Stopping folder "iTunes" - mkdir /Volumes/Macintosh\ HD/Music: permission denied

The permissions that i set on those folders are staying the way I set them though, unlike in 1186.

**Comment by calmh** [comment]
So... What does the config look like (screenshot of the "iTunes" folder expanded in the gui, or paste the config.xml somewhere), and what does "ls -ld /Volumes/Macintosh\ HD/Music" say?

**Comment by calmh** [comment]
Ad if that folder doesn't exist, `ls -ld@ /Volumes/Macintosh\ HD/` please

**Comment by ktonini** [comment]
Aha! I removed the space from the Volume name from "Macintosh HD" to "MacintoshHD" and it started to sync.

**Comment by calmh** [comment]
Oookay... :) Normally, `/Volumes/Macintosh HD` would be equivalent to just `/` but via a symlink... And `/` is not usually writable by normal users. Is `MacintoshHD` another disk, or some special setup?

**Comment by ktonini** [comment]
Actually yeah, my main drive is Macintosh SSD, and Macintosh HD is extra space for media and stuff.

**Comment by calmh** [comment]
Ah, but named without a space, and that was the only issue (because syncthing isn't allowed to create directories in /Volumes)?

**Comment by ktonini** [comment]
It was able to on the two other installs though, but those paths didn't contain any spaces.
