### ISSUE TITLE
More efficient renaming

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#1217]
**normal scenario**
- folder A (e.g. 100 files / 50GB) on computer X is synced to computer Y
- on computer X folder A is renamed to folder B and synced
- Syncthing on computer Y
  - copies existing files (reusing blocks) from folder A to folder B - total size 100GB
  - deletes folder A - total size 50GB
:+1: 

**out of space scenario** (e.g. 6GB free space)
- folder A (e.g. 100 files / 50GB) on computer X is synced to computer Y
- on computer X folder A is renamed to folder B and synced
- Syncthing on computer Y
  - copies existing files (reusing blocks) from folder A to folder B
  - stops copying as disk is full (e.g. total size 56GB)
  - deletes all 100 files folder A
- admin frees up space
- Syncthing needs to transfer 44GB

expected
do not delete old files if running out of space until all changes are made and all blocks are reused

**Comment by AudriusButkevicius** [comment]
I say this is a wontfix. We either suceed or fail on a per file basis.
After deleting the files from A we have enough space to sync stuff to B, not requiring any human intervention.

**Comment by calmh** [comment]
What actually happens though is that we fail to copy/sync the large files, then do the deletes, then retry and fetch everything over the network?

I could see a valid optimization being similar to our current "metadata only"-shortcut to handle renames. I.e. we see a new file with the exact same block checksums as an existing one, and the existing one is marked for deletion, so we just do the rename instead of copy...

**Comment by AudriusButkevicius** [comment]
Actually, not a bad idea.

But this means we either need to hold the need list in memory in full, or traverse the index change atleast twice (if we put files into buckets in memory like my old PR did before blockmap which can be alot of memory for a large repo) doing twice as many db hits or have an n^2 version.

**Comment by ozra** [comment]
Renaming dirs then and when is such a common scenario that I deffo vote for optimizing for it. Especially when having source trees / GTD-project-trees with tons of files in them...

**Comment by ozra** [comment]
Oops. Closed.. hehe.
