### ISSUE TITLE
Auto-update chose wrong architecture

### ISSUE THREAD

**Issue by seidler2547** [syncthing/syncthing#1218]
My NAS instance with "ARMv6-compatible processor rev 5 (v6l)" would not come up anymore, because the ARMv5 instance of syncthing apparently auto-upgraded to the ARMv6 version, which does not work on that device because it has no hardware floating point. That was from 0.10.14. Downloaded manually and works now, but I fear next upgrade could break it again.

**Comment by calmh** [comment]
This is a side effect of #1051 where this behavior was insisted upon by another ARM user. As a non-ARM user, I gotta say your architecture is a huge pain in the ass. ;)

**Comment by seidler2547** [comment]
I know, ARM is a mess. However, I do not understand #1051 really, so my simple view of things is that the upgrade should stick to the build that was previously installed. If a x86-64 user decided to run the x86(-32) version (which should work because the 64 bit kernel also executes 32 bit binaries) then auto-upgrade should not force the 64 bit version. Or is this something different?

**Comment by calmh** [comment]
The thing with that ticket is that previously the syncthing build system required explicitly specifying armv5 armv6 or armv7 as the architecture to build for. But if you're *on* arm, then the default is just "arm" with no architecture information, and that should be a valid build target - all the excitement over there is from me calling out "arm" as an invalid architecture when it's really not. But when that's the case, we no longer know what we were built as (other than just "arm") so we use uname to figure it out at upgrade time.

In this case it seems either your uname lies, or the Go compiler's opinion on what constitutes armv6 is incorrect?

**Comment by seidler2547** [comment]
No, the uname is correct, however hf (hard float) is optional in ARMv6, but the Go compiler assumes it's implemented (and the official stance is "if you're on ARMv6 without hf, use GOARM=5"), and in most ARMv6 processors the FPU is implemented, but not in all. I know, not funny. Would setting GOARM=5 as an environment variable convice the upgrade process to download the v5 variant?

**Comment by calmh** [comment]
Gotcha. No, it doesn't take that into account unfortunate, only the uname result. (Although it could, of course...)

I wonder what the performance penalty for integer code (our crypto and hashing etc) is for running armv5 on arm6/7. If it's small enough, I'd be inclined to just build for v5, call it just "arm", and let those for whom the difference matters build it themselves...

**Comment by seidler2547** [comment]
I will try to see if I can find that performance test that someone (was is @AudriusButkevicius ) once wrote and test it on my other, ARMv7 with hf, platform. Or if you have a benchmark suite that tests exactly the things that Syncthing uses, I could use this.

**Comment by calmh** [comment]
Actually I think that just starting syncthing, going to settings and hitting the link to preview usage stats will do. There's a number in there for sha256 hashing performance in MB/s. That's not the only thing we do, but it's a common bottle neck and representative enough to get a feeling for it I think.

**Comment by seidler2547** [comment]
Hmm, that number is very inconsistent. I got it as high as 8.05 on all three builds, but somehow on the GOARM=5 build is scores often much lower than that, sometimes in the 5-6MB/s. But that might be coincidence,  it also just had 6.something on the ARMv7 build. Maybe there's a slight penalty with regards to how many registers are being used, but I'd say it looks like there's little difference between the builds in pure maximum performance. There might be in multi-core performance, but that's hard to tell.

**Comment by AudriusButkevicius** [comment]
I assume ARM5 on a modern phone will be quite bad.

**Comment by seidler2547** [comment]
What makes you think so? When I last checked, there was still no assembler 
version of SHA256 in Go, and even if, would it use NEON or any of the 
opcodes only available in ARMv7? The major advantages of the newer cores 
are rather out-of-order pipelines and more/faster caches and more MHz?!

**Comment by AudriusButkevicius** [comment]
I am making a wild guess. Though I am sure there will be people screaming for specific builds for their version or ARMv7, atleast I would.

**Comment by seidler2547** [comment]
Ok, tested this on a MSM8260A dual-core, 1.5GHz Qualcomm Krait CPU. No difference. Overall performance is about twice as fast as the other platform I tested.
Scores are between 15 and 18 MB/s, where ARMv5 incidentially reported the highest score.
I don't know if this has to do with the random number pool rather than the CPU performance, but in both tests the certificate generation was A LOT slower with the ARMv6 variant, took almost twice as long as v5 or v7!?

**Comment by seidler2547** [comment]
Oh, one last question (coming back to topic): will auto-upgrade find the new "only arm" version?

**Comment by calmh** [comment]
Nope, as noted in the pull request we need to publish the armv5/6/7 packages as well at least one or two more releases.
