### ISSUE TITLE
mention license in about dialog

### ISSUE THREAD

**Issue by davidak** [syncthing/syncthing#1223]
the user don't sees that Syncthing is free software inside the webinterface.

for me that is very important!

**Comment by marclaporte** [comment]
Good point. And I'll add to the front page as well: http://syncthing.net/

Just need to agree on a wording. There has just been a change:
https://discourse.syncthing.net/t/on-gpl-without-contributor-licenses-the-app-store-and-future-of-pulse/1630/22

Option A (just the final license)
Syncthing is licensed GPL v3 

Option B (has the benefit to promote the MIT part for inclusion in any other app)
Syncthing (the application) is licensed GPL v3. The Syncthing protocol implementation is licensed MIT.

Thoughts?

**Comment by davidak** [comment]
The License of the Protocol should be mentioned where the Protocol is mentioned. A normal user don't need to know about a protocol.

to point out the difference between just Open Source and free Software:
"Syncthing is free Software licensed as GPL v3."

**Comment by calmh** [comment]
http://laslow.net/reactiongifs/Batch02/Free%20Software.gif

**Comment by calmh** [comment]
![free 20software](https://cloud.githubusercontent.com/assets/125426/5755353/a8b4b436-9ca3-11e4-842a-5fcbc016c56e.gif)
