### ISSUE TITLE
help understanding the ignore behavior

### ISSUE THREAD

**Issue by SebBiber** [syncthing/syncthing#1224]
Hi, I looked at the wiki page but I thing the following questions are not answered. However, some answers would be nice to the following questions.

I have the following folder structure:

Folder1
     ->file3.txt
     ->file4.jpg
Folder2
    ->file5.txt
    ->file6.jpg
Folder3
file1.txt
file2.jpg

1) and the following.stignore file (windows system):

!Folder1
!Folder2
*

This works fine, Folder1 and Folder2 are synced but file1, file2 and Folder3 with its content not. Here I wonder, why the content of Folder1 and Folder2 is synced. Is this the intended behavior? I supposed that the content inside the folder is ignored by the "*".

2) If I want to ignore additionally all jpg Files. I add

!Folder1
!Folder2
*.jpg
*
But the *.jpg pattern is ignored, means that all jpg files are synched again (I test it by adding the jpg files later). Why is the *jpg pattern ignored? Is this intended behavior?

Is their another way of exclude files in an included folder?

3) I try to include/exclude a subfolder following this pattern:

Folder1/SubFolder
or
!Folder1/SubFolder

but it does not work. Is it possible to include/exclude a subfolder by specifying the path from the current root directory? This could be usefull if there are folders with the same name in different directories and in one case I want to ignore one of them.

4) What happens with whitespaces in folder names:
   a) in the exclude pattern
   b) in the !exclude pattern
I know that whitespaces are ugly in folder names but on windows I want to ignore for example the "System Volume Information" folder. I have the feeling that whitespaces are no problem but a confirmation would be nice.

Thx

**Comment by SebBiber** [comment]
In addition,

I have a .stignore file with
#include Pattern
\Folder5
!Folder6

The Pattern file consist of the following:
//\Folder1
\Folder2
\Folder3
!Folder4
*.jpg

If I remove the #include Pattern line, the behavior is as I would expect. Folder5 is ignored and Folder6 is synched. (Do not care about the other folders).

If I have the include line only, the behavior is as expected: Folder1 and Folder4 is synced. Folder2 and Folder3 are ignored. Additonally, all jpg files in Folder1 are ignored. Jpg files in Folder4 are synched. Therefore, the Pattern file is obviously found.

Why does the complete .stignore file not work (with the inlcude line and the two extra lines)? If I put all together as show above, Folder5 is synced. So I am really confused now, could you please explain this behavoir for me?

Maybe I should use basic ignore pattern only ;-)

**Comment by AudriusButkevicius** [comment]
1) yes
2 ) order matters, as the first match is the final match.
3 ) you can anchor to the folder root by using / as the first character of the path, just as the docs say.
4 ) try and see

**Comment by SebBiber** [comment]
THX for your explanation

I am still not sure, why in my last example (second comment) Folder5 is synced, because if order matters, no ignore pattern is matched before.

However, I will not mix the #inlcude statement with additional ignore pattern in the .stignore file, so for me the explanation is enough.

Thx again, you do great work and I really like the tool!

**Comment by AudriusButkevicius** [comment]
If you expand your include statement you get:
1
2
3
4
*.jpg
5
6

So I don't understand what you don't understand.

**Comment by SebBiber** [comment]
Exactly, I get
//1 -> synched (because the line is a comment) OK
2 -> ignored OK
3 -> ignored OK
!4 -> synched OK
*jpg
5 -> synched NOT OK, because it is a ingore pattern
!6 -> synced OK

Folder5 was empty, so *.jpg do not match.
The question was, why is folder 5 synched? As already explained, the #include line alone in the stignore file works well. Furthermore, just the two lines:
\Folder5
!Folder6
works well, too (deleting the #include line).
But all together show strange behavior, where the folder 5 is synced, although it is an ignore pattern!

**Comment by AudriusButkevicius** [comment]
I am not sure `\` is a valid character, as ignores expects unix like path separators `\`.
Also, if `/Folder` means the folder and it's content, where as `/Folder/` means only the folders content should be ignored (but the folder itself should be kept)

Also, you don't need to exclude 4 and 6, because neither of the ignore patterns will match and it will be synced anyway without exclusions.

**Comment by SebBiber** [comment]
Ah ok, I will try the unix path separator and report if this works under windows.

**Comment by SebBiber** [comment]
Thank you very much for your help.
The path separator was the right hint and solve the problem. Now all combinations works fine. Even the exclusion of subfolder as for example:
/root/ignoreMe
and
/root/showMeButIgnoreContent/
