### ISSUE TITLE
Out of sync ignore files

### ISSUE THREAD

**Issue by p1rox** [syncthing/syncthing#1227]
On my repo under Mac OS 10.10 I added `.DS_Store` to the .stignore file
![capture d ecran 2015-01-10 a 14 03 13](https://cloud.githubusercontent.com/assets/1545450/5691625/7503f668-98d1-11e4-85bd-d1e64f6f3c53.png)

Now I always have this :
![capture d ecran 2015-01-07 a 18 42 14](https://cloud.githubusercontent.com/assets/1545450/5691626/8a51f7a4-98d1-11e4-8fed-466b02fb0d3c.png)

And the `.DS_Store` files are still on other nodes (nodes under GNU/Linux)

**Comment by calmh** [comment]
This is by design, even though it may be confusing and not the greatest UI setup. In principle, the files need syncing, but you're ignoring them so they stay out of sync.

**Comment by AudriusButkevicius** [comment]
I am pretty sure we can do better though.
