### ISSUE TITLE
Dual boot win / osx with the same config

### ISSUE THREAD

**Issue by ktonini** [syncthing/syncthing#1228]
One of the machines I have syncing is a dual boot system.  Currently I have two separate databases for each OS, but is there any way that they could be combined?  That way with each OS switch the database wouldn't have to re-sync.

It'd be nice to be able to just create a symlink, but the folder paths in the config file differ for each OS.  Also the Windows install complained about some files that it had to skip with characters (such as asterisks) in their names, so I'm not sure if suddenly having those files in it's database would cause any errors.

**Comment by AudriusButkevicius** [comment]
I guess you just reuse the same certificates and symlink the index directory, and have a separate config.

AFAIK the database holds filenames in NFC format which is normalized across all platforms, but obviously there could be issues where file paths are too long or even invalid on Windows causing the files to be deleted and so on, but yourself are choosing to be part of this mess.

**Comment by ktonini** [comment]
That's a great idea!  I'll give it a shot - I don't mind the mess, I have everything that's being synced backed up. :-)

**Comment by calmh** [comment]
The real advantage here is making sure the `index` directory inside the config directory is shared. That's where the current view of the local files is stored. If it's not shared, any changes made will be discovered twice, once by each OS/instance, so announced twice, handled twice by the other devices, etc.
