### ISSUE TITLE
upgrading: rename syncthing.exe -> syncthing.exe.old

### ISSUE THREAD

**Issue by merlinuwe** [syncthing/syncthing#1239]
Hi,

after clicking on the blue button on Windows 7 64bit I got this error-message:

"23:13:54: upgrading: rename C:\Program Files\syncthing\syncthing.exe C:\Program Files\syncthing\syncthing.exe.old: Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist."

Manually renaming solved the problem.

Greetings,

Uwe

**Comment by AudriusButkevicius** [comment]
Sorry, the file was there, or was the file 'in use'?

**Comment by merlinuwe** [comment]
The file syncthing.exe.old was there before the update. See attachment for details.

![win7_64bit](https://cloud.githubusercontent.com/assets/4138869/5697285/7859204c-99ec-11e4-8841-e0cbec037b45.jpg)

**Comment by Moter8** [comment]
And to translate the error: "Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist."

Means: A file can not be created if it already exists.

**Comment by AudriusButkevicius** [comment]
I guess this is just life on Windows.
Sometime the binary is locked, sometimes it's not.
I cannot find any reasonable explanations when each of these happens, so it seems it's all based on luck.

**Comment by schuft69** [comment]
also got a problem with these *old files - under linux every new version creates one more file:

mediacenter@mediacenter:/home/syncthing/bin$ ll
-rwxr-xr-x 1 syncthing syncthing 10843065 Jan 14 16:33 syncthing*
-rwxr-xr-x 1 syncthing syncthing 10845611 Jan 11 22:10 syncthing.old*
-rwxr-xr-x 1 syncthing syncthing 10806446 Jan  6 04:12 syncthing.old.old*
-rwxr-xr-x 1 syncthing syncthing 10806446 Jan  6 16:13 syncthing.old.old.old*
-rwxr-xr-x 1 syncthing syncthing 10810542 Jan  7 04:13 syncthing.old.old.old.old*
-rwxr-xr-x 1 syncthing syncthing 10810542 Jan  7 16:13 syncthing.old.old.old.old.old*
-rwxr-xr-x 1 syncthing syncthing 10806446 Jan  4 15:56 syncthing.old.old.old.old.old.old*

**Comment by AudriusButkevicius** [comment]
Yeah we should clean these up at some point I guess.

**Comment by merlinuwe** [comment]
Hi,

as I see on FreeBSD 64 bit, there are also at least one syncthing.old and some syncthingxxxxxxxxx files. It would be nice to clean them up both.
```
freenas# cd syncthing
freenas# ls -al
total 25468
drwxrwxrwx   6 root  wheel       512 Jan 13 23:21 .
drwxrwxrwx  32 root  wheel      1024 Jan 15 16:27 ..
drwx------   3 root  wheel       512 Jun 28  2014 .config
-rw-r--r--   1 502   staff       511 Aug  7 23:31 CONTRIBUTORS
-rw-r--r--   1 root  wheel     19504 Oct 20 11:17 FreeBSD.log
-rw-r--r--   1 502   staff      1104 Aug  7 23:31 LICENSE
-rw-r--r--   1 502   staff      2184 Aug  7 23:31 README.md
-rwxr-xr-x   1 root  wheel  10842430 Jan 13 23:21 syncthing
drwxr-xr-x   2 502   staff       512 Aug 10 19:38 syncthing-freebsd-amd64-v0.8.19
drwxr-xr-x   2 root  wheel       512 Sep  8 12:15 syncthing-freebsd-amd64-v0.9.13
-rw-r--r--   1 root  wheel   3054987 Sep  8 12:11 syncthing-freebsd-amd64-v0.9.13.tar.gz
drwxr-xr-x   2 502   staff       512 Aug 10 19:37 syncthing-freebsd-amd64-v0.9.2
-rwxr-xr-x   1 root  wheel       236 Aug 10 18:25 syncthing-start.sh
-rw-r--r--   1 502   staff       819 Aug  7 23:31 syncthing.asc
-rwxr-xr-x   1 root  wheel  10840880 Jan 11 23:19 syncthing.old
-rw-------   1 root  wheel    353280 Sep 25 17:38 syncthing630586596
-rw-------   1 root  wheel    746496 Sep 25 17:41 syncthing799846318
freenas#
```
Greetings,

Uwe

**Comment by AudriusButkevicius** [comment]
The xxxx files are temp files, I guess they should go to the temp directory ideally.

**Comment by AudriusButkevicius** [comment]
The situation @schuft69 describes doesn't seem impossible, because we always delete the `syncthing.old` before renaming `syncthing` to `syncthing.old`.

**Comment by schuft69** [comment]
No, I'am not using syncthing-gtk. Running an ubuntu 14.04 LTS. But nevertheless - this is not a real problem I thing. I'll delete the *old and everything is ok. Mybe its somehow connected to local filesystem permissions.

**Comment by AudriusButkevicius** [comment]
or perhaps these .old.old are left from very old versions.
