### ISSUE TITLE
Tries to overwrite folder root

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#1243]
```
Jan 13 09:14:23 acro-syncer syncthing: [SFPK3] WARNING: puller: final: rename /data/Lightroom/.syncthing.. /data/Lightroom: directory not
 empty
```

/data/Lightroom is my folder root. This should not happen.

**Comment by AudriusButkevicius** [comment]
I've noticed the double dot in the end though?
As if the file is called `.`

**Comment by calmh** [comment]
Right, yes, I didn't notice that. That could be the old #1186, given an empty file gets expanded to the folder root, and then we get the relative filename in a few places, which would be `.` from the folder root...

**Comment by calmh** [comment]
Maybe add those to the indexclean commit?
