### ISSUE TITLE
ST freezes with high CPU, no connection to WebGUI

### ISSUE THREAD

**Issue by tvld** [syncthing/syncthing#1249]
Had ST running great for a week between laptop and desktop. Today suddenly:
- freezes the system with continous 34% CPU load. 
- browser unable to connect to http://127.0.0.1:8080/

I wanted to try to run in debug mode but I can not: as soon as I kill process syncthing, it just immmediately restarts before I can start in debug mode.   sudo apt-get remove syncthing stops the CPU, but reinstalling immediately brings to max. I switched off Syncthing on Desktop and had same issue. 
Log file contains:

=============== Jan 13, 2015 (CET) ===============
21:20:02.598559 log@legend F·NumFile S·FileSize N·Entry C·BadEntry B·BadBlock Ke·KeyError D·DroppedEntry L·Level Q·SeqNum T·TimeElapsed

But nothing else
syncthing v0.10.17 (xgcc (Ubuntu 4.9.1-16ubuntu6) 4.9.1 linux-amd64 default) niklas@Niklas-Netbook 2015-01-04 

Ideas how to tackle this?

**Comment by AudriusButkevicius** [comment]
Wrong log file I think to start with, as I think this is the database log which is of no use.
Syncthing logs to stdout by default, hence it depends on how the package maintainer have solved it.

**Comment by tvld** [comment]
Then what to do?  If I delete the ~.config/syncthing folder , it starts nicely all over again.. So the problem is in the configuration somehow. Any tips on how to proceed?

**Comment by AudriusButkevicius** [comment]
Well, get the log out of it for starters.

**Comment by tvld** [comment]
ok.. this is guru versus newbie talk - no idea how, but digging

**Comment by tvld** [comment]
when I reboot, syncthing is again running. I can not kill it & I can not start again as it complains already running. What daemon starts it each time? How can I kill an unresponsice ST ?

**Comment by AudriusButkevicius** [comment]
Ok, one second, I'll check the official package and provide better instructions.

**Comment by tvld** [comment]
Not sure if this helps. But if I sudo apt-get remove syncthing and then apt-get install  and I try to start, it gives me:
[5OFNI] 21:45:52 FATAL: Cannot open database: leveldb: manifest corrupted (field 'comparer'): missing [file=MANIFEST-006740] - Is another copy of Syncthing already running?
[monitor] 21:45:52 INFO: Syncthing exited: exit status 1

**Comment by AudriusButkevicius** [comment]
Yes, that's the right log.
Your database seems corrupt, syncthing will have to rebuild it.
Remove the index directory from ~/.config/syncthing/ and it should continue working.

**Comment by tvld** [comment]
Ok, thank you:)  Removed the index folder and I have the interface back. It is now rebuilding.

Now the question: anyway I can help to figure out why it got corrupted?

**Comment by AudriusButkevicius** [comment]
Power outage, process killed immediately, bug in the database?

**Comment by tvld** [comment]
Yes.... could be: I had Ubuntu Unity desktop freeze and needed to kill it with holding the power button.
