### ISSUE TITLE
Nodes show same transfer rates

### ISSUE THREAD

**Issue by ssemke** [syncthing/syncthing#1257]
Nodes which are transferring data between each other show identical upload and download rates.  I would expect the uploading node's upload rate to be similar to the downloading node's download rate and vice-versa.  I don't recall this before 0.10.20.

![screenshot_20150115174009](https://cloud.githubusercontent.com/assets/9437051/5770483/06d5b7b8-9ce0-11e4-9cfa-931ccc7e8535.png)

**Comment by calmh** [comment]
All rates are from the perspective of the device you are logged in on. The top one is the total, the rest per remove device. (We don't know the full up/down rates for a remote device.)

**Comment by calmh** [comment]
(Transfer rates were broken in general between v0.10.10 and v0.10.20)

**Comment by ssemke** [comment]
Ah, sensible.
