### ISSUE TITLE
upload only changes made to the file instead of the entire file

### ISSUE THREAD

**Issue by ahmadramadan** [syncthing/syncthing#1261]
Hello
I hope we can we see something like this in syncthing
dropbox.com/en/help/8

**Comment by AudriusButkevicius** [comment]
Are you making claims that it doesn't based on an educated decision or are you just being a cowboy?

**Comment by ahmadramadan** [comment]
Im just trying to be good contributor :)
I meant if we have big (zip) file and we made a little changes we dont have to upload the whole file again

**Comment by Zillode** [comment]
See https://discourse.syncthing.net/t/better-delta-sync-algorithm-like-rsync/984/6

**Comment by kozec** [comment]
Point is, Syncthing does this from very begining, if i'm not mistaken.
