### ISSUE TITLE
Append path separator to folder paths

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#1262]
Or do that when validating the config, as `filepath.Rel("C:", "C:\\test")` doesn't work otherwise.

**Comment by rautamiekka** [comment]
Meaning make §C:§ to §C:/§ or §C:\\§ ?

**Comment by AudriusButkevicius** [comment]
Well whatever is local to the given filesystem

**Comment by rautamiekka** [comment]
http://golang.org/pkg/path/filepath/

**Comment by AudriusButkevicius** [comment]
Sorry, are you asking a question or what?

**Comment by rautamiekka** [comment]
Just trying to help you.

Adding the separator explicitly without checking usually doesn't introduce problems but allows to work around the separator not being there by default. It doesn't need much code to check for it, though, before passing the path on.

**Comment by AudriusButkevicius** [comment]
Yeah, I know, `filepath.Separator` returns the OS local separator.
Pull requests always welcome.

**Comment by krozycki** [comment]
Hi. I am new to Syncthing and I would like to start contributing. It seems that this issue is a good one to start with, so I would like to do it, but could you please tell me where have you spotted this problem?

**Comment by AudriusButkevicius** [comment]
We should ideally do it somewhere here in folder validation as we load the config:
https://github.com/syncthing/syncthing/blob/master/internal/config/config.go#L259

As invalid configuration could be inserted into the xml file later causing errors.
