### ISSUE TITLE
Status indicators in web interface are not intuitive.

### ISSUE THREAD

**Issue by vext01** [syncthing/syncthing#1265]
Hey,

I find the status indicators on the syncthing web interface somewhat confusing.

It seems it is possible that a device can show as "up to date" on the right hand side, yet a repository shared with the same device can show as "syncing X%" on the left. This feels like a contradiction to me.

It is clear that I don't understand -- I wonder if there is a better way of presenting the status of syncthing to users?

**Comment by vext01** [comment]
Further, syncthing is now showing "up to date" on both the left and right hand sides of the web interface, yet on the left under the repo, it shows 5 items out of sync.

I wonder if this is because the items are "special" to android (this is an OpenBSD machine syncing to android). The items are: Android, data, .nomedia, org.mariotaku.twidere and cache.

**Comment by AudriusButkevicius** [comment]
Folders show your local state, where as devices show the remote device state.
Device shows `Up to date` because the OTHER device already has everything according to the global model, and your folder shows `Syncing` because YOU are missing files compared to the global state.

Ignored items (part of .stignore) are shown out of sync, as you don't have them compared to the global model.
The remote device has no clue which files you are ignoring and which ones you are not, hence will forever show you out of sync by some percentage.

What is the actual issue you are concerned about?
Or this is more of a question? If it's a question, please use the forum next time.

**Comment by egelmex** [comment]
> It is clear that I don't understand -- I wonder if there is a better way of presenting the status of syncthing to users?

Sounds like an issue to me. The term "up to date" is overloaded, and has slightly different meanings depending on where it is shown in the UI, which might be unclear to new users.

**Comment by AudriusButkevicius** [comment]
Sorry, but what are the different meanings of up to date?

**Comment by vext01** [comment]
I think @egelmex refers to the fact that "up to date" can mean a couple of different things. You almost stated them in your above reply:

 * "Device shows Up to date because the OTHER device already has everything."
 * Folder can show "up to date" to mean the folder has everything in global state.

I still find this counter intuitive. I would expect a device to show as "syncing" if data is flowing in *either* direction. And I guess same for a folder.

Would you agree?

Perhaps between us, @egelmex and I can com up with a proposal?

**Comment by AudriusButkevicius** [comment]
The examples which I've stated seemed to be obvious to me.
I am open for better suggestions though.

**Comment by vext01** [comment]
Give me some time and I will mock something on my whiteboard.

**Comment by jatubio** [comment]
Hello:

First, I want to congratulate the application, and thank it open source and free.

I started using it and windows and I've noticed that sometimes the texts about the "state of the repository" and "state about synchronization" are confusing to me.

Today, while synchronizing a repository on the local computer appeared 'Up to Date' in the repository, and yet in the "Server" label appeared 'Syncing to 83%'. In addition, the repository show in Global State: 449 Mb, when in fact the server only had 371 Mb.

Indeed, on the server computer, you can see that it's synchronizing.

Local: 
	syncthing v0.10.29 (go1.4.2 windows-amd64 default)
	synctrayzor: 1.0.11

![server_26032015_1236](https://cloud.githubusercontent.com/assets/11651768/6846540/5fc85b9e-d3bf-11e4-95b6-e4e7be767c43.png)
	
Sever:
	syncthing v0.10.29 (go1.4.2 windows-amd64 default)
	synctrayzor: 1.0.11
	

![server_26032015_1235](https://cloud.githubusercontent.com/assets/11651768/6846541/5fcc3b74-d3bf-11e4-849b-c19dcc0c7e7a.png)

**Comment by AudriusButkevicius** [comment]
Sorry, what is the issue?

From your screenshots everything seems correct (despite it being confusing).
Servidor is still syncthing hence on your other node it's show as 83%.
The node who's name is hidden is in sync, hence it shows `Up to date`.

Global state defines how much files there are between all nodes,
Local state defines how much files the node currently has, (In Servidor case it has 82% percent of files, 371MiB/449MiB, and the other node has 449/449 which means `Up to date`).

**Comment by jatubio** [comment]
Thanks for reply :)

Yes, it seems a matter about confusing and not a issue.

If I understand correctly, the information on the left side of the screen show information about "Local" computer. So "Up to date" means that this computer has the latest version of the repository. "Global State" shows the total number of files in the repository and "Local State" shows the number of files in the repository that have been downloaded locally.

The Server tab on the right side of the screen displays information about the "Global" process synchronization with the server.

Is it right? If so, I'll create a little explanation, in the wiki doc for people who are as confused as I am;)

Therefore, I understand that there is no way (from the local computer) to check whether a repository is fully synchronized to the server or the remainder percent for synchronization.

**Comment by AudriusButkevicius** [comment]
Yes, the right side represents the overall state of the remote nodes (overall summing all folders).
Left side represents local (my) state.

A wiki page is very welcome in this case.

**Comment by jatubio** [comment]
Thanks for your explanations :)

Thanks for the explanation.

I want to show a snapshot of gui in the wiki, but can not get the gui appears to me in English (I appears in Spanish). Is there any option to force the gui to appear in English?

I have deleted es.pak files but don't work

**Comment by jatubio** [comment]
I have written a small page about it. This is the link if anyone wants to complete: https://github.com/syncthing/syncthing/wiki/A-brief-explanation-of-the-GUI

**Comment by wweich** [comment]
The is an URL Parameter ?lang=en which doesn't work at the moment.
You can change the language your browser request in the settings of your browser.
Firefox: Settings -> Content (TAB) -> Languages -> Choose (Button) and set en to the top of the list
Chrome: "Display advanced settings" at bottom of "normal" settings -> Languages

**Comment by AudriusButkevicius** [comment]
@jatubio thanks alot.
@wweich this is fixed in master branch, though hasn't been released.

**Comment by jatubio** [comment]
@AudriusButkevicius thank you for improving my text on wiki :)
@wweich Thanks for your ideas.

**Comment by imsodin** [comment]
I don't see anything to do here.
