### ISSUE TITLE
Move notice panel to top of page

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#1270]
Can we move the panels (notices, errors, new folder, new device) to the top of the page? 
currently it's very easy to miss infos because of long folder lists :blush: 
if :smile: = PR

**Comment by AudriusButkevicius** [comment]
:smile:

**Comment by uok** [comment]
ok, I created the PR but Github somehow merged it with PR #1269 (because same changed file?) I'm really confused as I don't have a lot of experience with Github. I wanted it to be two separate PRs and add #ref to both of them but I also cannot find undo button :confused:

**Comment by AudriusButkevicius** [comment]
Ideally you do it with two branches.
Branch 1
```
git checkout master
git branch my-new-branch-1
git checkout my-new-branch-1
...do edits...
git commit
git push origin my-new-branch-1
```
Branch 2:
```
git checkout master
git branch my-new-branch-2
git checkout my-new-branch-2
...do edits...
git commit
git push origin my-new-branch-2
```
Then you do separate PRs for each branch.
You can delete the existing branch with `git branch -D name-of-branch`, then create a new branch under the same name with new edits, and then force-push it `git push origin branch-name -f` to your repo causing the PR to be updated.

**Comment by uok** [comment]
Thanks for the clear instructions, your help is truly appreciated.
I reverted the wrong commit so that #1269 is good to go and I will create a separate PR with the newly learned commands tomorrow.
