### ISSUE TITLE
Update link in web interface does not work on OpenBSD.

### ISSUE THREAD

**Issue by vext01** [syncthing/syncthing#1272]
If you click the update link on the web interface on OpenBSD, you will get an error:

`upgrading: readlink /proc/curproc/file: no such file or directory`

OpenBSD (and probably some other UNIXs) does not have `/proc`.

Presumably you are trying to get the server's PID? It is typical to write a PID file into `/var/run`.

Thanks

**Comment by kozec** [comment]
`/proc/curproc/file` will return filename of current process, not PID. Shouldn't that be same thing as `os.Args[0]` ?

**Comment by AudriusButkevicius** [comment]
It seems that:
https://github.com/syncthing/syncthing/blob/8f9b8a8550a4f1ff483065991427c2535440df5c/Godeps/_workspace/src/github.com/calmh/osext/osext_procfs.go

Targets OpenBSD specifically, so I am a bit puzzled why it's not there.

**Comment by AudriusButkevicius** [comment]
I agree though that os.Args[0] should be sufficient.
Though some programs do patch that up to show up under a different name in the process tree.

**Comment by kozec** [comment]
> Targets OpenBSD specifically, so I am a bit puzzled why it's not there.

Unlike Linux, ObenBSD supports procfs only as optional feature on some architectures.

**Comment by AudriusButkevicius** [comment]
I'll have to wait for @calmh to answer this.

**Comment by calmh** [comment]
Right. So this only works on the OpenBSDs that have a /proc. We need /proc to find the location of the binary so we can upgrade it. We should probably just do this check earlier and disable auto upgrades if we can't determine the binary location.

(os.Args[0] is what the user called the binary as, which may not contain the path)

**Comment by AudriusButkevicius** [comment]
Isn't CWD + Args[0] still the same thing?

**Comment by calmh** [comment]
If I just type `syncthing` in my home directory, `os.Args[0]` is `syncthing`, `Getwd()` is my home directory, the binary might be anywhere in my `$PATH`. There are other corner cases, but point is Args[0] isn't the truth.

**Comment by AudriusButkevicius** [comment]
Ah yes, I am just used to not having anything in my path.

**Comment by calmh** [comment]
Without /proc we can't determine our binary location and can't auto upgrade. Closing.

**Comment by mulander** [comment]
Maybe adding an optional binary location config path would help solving the issue? People who prefer auto updates could set their location this way making it independent off /proc.

**Comment by calmh** [comment]
Maybe one of the [three](https://data.syncthing.net/#metrics) OpenBSD users feel strongly enough about this to propose a patch. :D

**Comment by canton7** [comment]
If you look at the github download stats, there are at least 160 of them...

**Comment by calmh** [comment]
No problem then.

**Comment by mulander** [comment]
@calmh I'll provide a patch with the proposed config option solution. Stay tuned ;)

**Comment by calmh** [comment]
@mulander Maybe just fall back to argv[0] and if that's not an absolute path explain the problem to the user?

**Comment by mulander** [comment]
@calmh sounds reasonable to me. I just finished work for today so will spent some time trying out options - will avoid adding new config for it and will report back with a patch or more info.

**Comment by AudriusButkevicius** [comment]
Or check $PATH/srgv[0]

**Comment by mulander** [comment]
@calmh @AudriusButkevicius I was on my way to do a best effort implementation and finally found out how syncthing locates the current executable. It seems that you guys depend on a frozen version of [kardianos/osext](github.com/kardianos/osext) using Godeps.

Seems that this whole issue is already fixed upstream and all you need is to pull this [commit](https://github.com/kardianos/osext/commit/b4814f465fb1f92d46e37f7ef84d732ece7c3e3a) provided by [ajacoutot](https://github.com/ajacoutot) who is an OpenBSD developer.

**Comment by AudriusButkevicius** [comment]
Right, we only need to upgrade that then.

**Comment by plouj** [comment]
On a related note, could you also pull in the changes from https://github.com/kardianos/osext/commit/431e263e413efe4446ede50cec4819b26659fbe7 ? I tried to do it myself, but I can't figure out godep :(

**Comment by calmh** [comment]
There you go. Shutting down this issue to avoid piling more things on it. ;)
