### ISSUE TITLE
There is some changes, but not syncing

### ISSUE THREAD

**Issue by raisertomsk** [syncthing/syncthing#1283]
Глобальное состояние 	46666 элементы, ~4.05 GiB
 Локальное состояние 	46607 элементы, ~4.04 GiB
 Не синхронизировано 	66 элементы, ~16.1 MiB

I can't see any error, but this folder is not in sync and not syncing. Syncthing tells me that it is ok and already synced. v0.10.21. I use gentoo linux.

**Comment by raisertomsk** [comment]
Sync started after an hour

**Comment by AudriusButkevicius** [comment]
Perhaps the receiving node was offline?
It sounds like: #1130 though

**Comment by raisertomsk** [comment]
Problem was with internet connection. There was technical works on internet provider's side, so quality of internet connection was shitty. Thanks and sorry for wrong bug report.
