### ISSUE TITLE
smarter block splitting like rsync

### ISSUE THREAD

**Issue by rwcarlsen** [syncthing/syncthing#1284]
A rolling checksum algorithm could be used to compute split points instead of
using a fixed block size for files.  The blocks would still be hashed and
identified with sha256 - the rolling checksum would be used only for computing
split points.  The gain from this change would be smarter block tranmission
between nodes.  When a file is modified in a way that changes its length, this
algorithm results in nearly all blocks before and after the changed area being
identical - no need to re-transmit.  This is possible because the rolling
checksum operates over a relatively small byte window (~10's of bytes).  Split
points are identified as locations where the rolling sum has so many
consecutive trailing zero bits. All regions in a file where the window doesn't
include modifications, the rolling checksum values are the same - resulting
in split points being identical. This will result in variable sized blocks.

* Add rolling checksum splitting to `internal/scanner` - probably something
  like what bup does (http://github.com/bup/bup).  It might also be a good
  idea to enforce hard minimum and maximum block size limits (e.g. 0.1x
  blocksize and 3x blocksize).

* reduce (avg) protocol.BlockSize to ~65k.  This works better with
  cheaper rolling checksum algorithms.

* Remove fixed-length block code assumptions.  This primarily involves (starts
  with) code in `internal/model/puller.go`'s `copierRoutine` method and it
  spiders out a bit from there.  The most elegant way I have come up with so
  far involves changing the value stored for block keys in leveldb to be the
  byte offset of the block instead of an index.  This is necessary since the
  index can no longer be used to compute the offset for verifying blocks -
  i.e.  `fd.ReadAt(buf, protocol.BlockSize*int64(index)` wouldn't work
  anymore.

With a naive implementation, a version of syncthing doing this would work rather
inefficiently with older versions of syncthing.  Consider a node A running with
this new block splitting communicating with an older node B:

1. A sees a new local file X created and sends its block list to B.

2. B then pull over missing blocks - just like we want.

3. B sees a local modification to file X. It recomputes the block list and
  sends it to A.

4. All the received blocks look new to A because of different split points -
  even though the file might have just had a small change (even an append).  It pulls over all the blocks.

5. A sees a local modification to file X.  It recomputes the block list and sends it to B.

6. All the received blocks look new to B because of different split points -
  even though the file might have just had a small change (even an append).  It pulls over all the blocks.

7. Repeat from 3 ad infinitum.

So new versions are still compatible, but their communication is not very
efficient. One possible solution would be to have nodes change their splitting
behavior based on their peer's version - a workable if inelegant option.

Thoughts?  I'd be happy work on this a bit if there is interest/support.

**Comment by rwcarlsen** [comment]
Another issue is - Even though a peer may already have most blocks for a locally modified file - the peer will still need to update *all* block entries for the file in leveldb with updated offsets even though only the contents of the changed block(s) will need to be broadcasted.

**Comment by AudriusButkevicius** [comment]
Re: another issue

We already do this anyway.we always update the file as a whole and send all block hashes for a file.

Regarding inefficiencies, we can always bump up the version of syncthing and declare as incompatible to older versions.

Also I have thisconcept of 'features' introduced in one of my pr's where nodes negotiate a set of features they support, which could be used to fall back to the older implementation.

I personally support this and would provide you with any help you might need, though @calmh might think it's an overkill. 

I guess it is quite a lot of work for a very specific prepend or append not at the end usecase.
