### ISSUE TITLE
Upgrades should wait until binaries are available

### ISSUE THREAD

**Issue by jpjp** [syncthing/syncthing#1285]
An upgrade will fail if a new release is noticed before the binary is available.

**Comment by AudriusButkevicius** [comment]
I guess we should just change our release process.
Mark it as pre-release, upload binaries, mark it release.

**Comment by rautamiekka** [comment]
Dunno about pre-release, but you have to upload and wait for it to complete before you announce it's done cuz it's no good the the other way.

**Comment by calmh** [comment]
Problem is that the script that uploads the binary uses the Github API, and for some reason the release needs to be published (hence publicly visible) for the API to accept uploads to it. Or at least that was the case a year ago. So as it is, there's a minute or two of race condition between hitting publish and the binaries actually being in place.
