### ISSUE TITLE
godep restore fails

### ISSUE THREAD

**Issue by wararjey** [syncthing/syncthing#1287]
godep restore fails for syncthing/protocol and calmh/xdr, here is the log output:

 # cd .../go/src/github.com/calmh/xdr; git checkout ff948d7666c5e0fd18d398f6278881724d36a90b
fatal: reference is not a tree: ff948d7666c5e0fd18d398f6278881724d36a90b
godep: restore: exit status 128
 # cd .../go/src/github.com/syncthing/protocol; git checkout 15bf5f583a88b7aaf0a5b810fcf5fb21da0a3b3f
fatal: reference is not a tree: 15bf5f583a88b7aaf0a5b810fcf5fb21da0a3b3f
godep: restore: exit status 128

Looging at both repos on github, those git objects do not seem to exist. Perhaps you forgot to push them...

Regards and a lot of thanks for this great tool,

**Comment by AudriusButkevicius** [comment]
yeah I had the same thing, the hashes were part of the PR, and changed once they got merged in.

**Comment by calmh** [comment]
Fixed, thanks for noticing. I'd forgotten to push the updated xdr package as well.
