### ISSUE TITLE
General working

### ISSUE THREAD

**Issue by FromBabylon** [syncthing/syncthing#1291]
My question might be strange but I do not understand the purpose of this app. 
Is it a way to get things sync accross devices without to worry about sync process or is it a way to get things sync whenever I launch syncthing on both devices (assuming I use 2) ? 
For what I do understand I have to launch syncthing on both devices before files get synchronized. Is it possible to set it up like any change on any file would immediately (or in reasonable time) get sync on other devices ? 

Or I just have to get syncthing launched at boot and run in background on both devices ?

Thanks

**Comment by AudriusButkevicius** [comment]
You can call this peer to peer Dropbox. You start it on two machines at boot and it keeps files in sync between the peers.

**Comment by FromBabylon** [comment]
Peer to peer open source Dropbox ;-) 

Ok so that's great idea. I have to see how to integrate it with https://github.com/cozy/cozy-setup. That would be a super stuff.
