### ISSUE TITLE
HTTPS on syncthing.net

### ISSUE THREAD

**Issue by jpillora** [syncthing/syncthing#1292]
As a temporary measure, we could get https://syncthing.net/ with the [free tier of CloudFlare](https://www.cloudflare.com/plans). Note, we'd only have HTTPS to CloudFlare, their traffic to syncthing.net would still be unencrypted though it's better than no HTTPS. When [Let's Encrypt](https://letsencrypt.org/) is ready, this can be solved properly.

**Comment by AudriusButkevicius** [comment]
It seems that @calmh already has cloudflare setup but it's pointing at the wrong ip.

**Comment by uok** [comment]
Cloudflare HTTPS gives a false sense of security and should not be used anywhere, because they hook themselves in the middle but only encrypt one part of the connection. And also the whole traffic (!) is routed through them, not just static assets like JS-libraries. If you really feel that HTTPS for syncthing.net is necessary (which I don't because it's a static page without login or user data and just links to other pages) get a free SSL certificate or use some donation money to buy a cheap one.

**Comment by jpillora** [comment]
> "their [CloudFlare]'s traffic to syncthing.net would still be unencrypted..."

I mentioned this above...

Anyway:

```
$ curl -I syncthing.net
HTTP/1.1 200 OK
Date: Fri, 23 Jan 2015 13:19:40 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive13:19:40 GMT; path=/; domain=.syncthing.net; HttpOnly
Last-Modified: Fri, 09 Jan 2015 07:55:11 GMT
Expires: Fri, 23 Jan 2015 13:29:40 GMT
Cache-Control: max-age=600
Server: cloudflare-nginx
CF-RAY: 1ad448c4bab70b26-SYD
```

Since the traffic is already being intercepted, may as well switch on TLS to protect pages like  http://syncthing.net/security.html - even if it is temporary.

**Comment by iggs0** [comment]
I agree with uok. Ever heard of https://www.startssl.com/  The give a free in all Browser akzepted vaild domain validated certifcate to everyone. As long as you create key and CSR there is not much that can go wrong.

**Comment by jpillora** [comment]
A cert is better, though cloudflare is easier - startssl rejected the last
cert I tried to sign with them - wasn't as easy as I hoped. Next, you'll
need a server, Digital ocean is  probably the cheapest, unless someone
knows how to terminate TLS for free?

**Comment by veeti** [comment]
Note that some CA's also issue free certs for open source projects. [Example.](https://www.globalsign.com/en/ssl/ssl-open-source/)

**Comment by jpjp** [comment]
CloudFare's SSL is anti-security, let's not associate Syncthing with them. SSL certs cost 10 bucks, but if what @veeti said works then even better :)

**Comment by jpillora** [comment]
MitMs are usually local, so I wouldn't say they're anti-security, they just don't protect against NSA style MitMs. It would be nice to protect against all attacks so a real cert would be best, however TLS termination is also required for this, not just the cert. I originally raised this issue to protect they keys on http://syncthing.net/security.html though it's not a huge deal.

**Comment by calmh** [comment]
Syncthing.net is served from Github, who don't support HTTPS (wether Cloudflare fake-SSL or not). There's nothing sensitive there. Potentially the keys on http://syncthing.net/security.html could be something to MITM, but if that's a worry the real source is at https://github.com/syncthing/syncthing.github.io/blob/master/security.html. The stuff that I host myself does have SSL. I don't think this is a problem at this point, and it's anyway not a bug on syncthing...
