### ISSUE TITLE
syncthing.old.old.old.old.old.old.old.old.old.old

### ISSUE THREAD

**Issue by RaymiiOrg** [syncthing/syncthing#1294]
My `/usr/bin/` folder is full with this:

            syncthing.old
            syncthing.old.old
            syncthing.old.old.old
            syncthing.old.old.old.old
            syncthing.old.old.old.old.old
            syncthing.old.old.old.old.old.old
            syncthing.old.old.old.old.old.old.old
            syncthing.old.old.old.old.old.old.old.old
            syncthing.old.old.old.old.old.old.old.old.old
            syncthing.old.old.old.old.old.old.old.old.old.old
            syncthing.old.old.old.old.old.old.old.old.old.old.old
            syncthing.old.old.old.old.old.old.old.old.old.old.old.old
            syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old
            syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old
            syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
            syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
            syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
            syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
            syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
            syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
            syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
            syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
            syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
            syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
            syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old

Is this expected behaviour? Can those old.old files be removed without issues?

**Comment by AudriusButkevicius** [comment]
Yes.i think this was fixed in the recent version. What timestamps do the files have?

**Comment by RaymiiOrg** [comment]
Recent dates:

        -rwxr-xr-x 1 root root 10843065 Jan 15 21:18 /usr/bin/syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
        -rwxr-xr-x 1 root root 10843065 Jan 16 09:19 /usr/bin/syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
        -rwxr-xr-x 1 root root 10843065 Jan 16 21:19 /usr/bin/syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
        -rwxr-xr-x 1 root root 10843065 Jan 17 09:19 /usr/bin/syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
        -rwxr-xr-x 1 root root 10843065 Jan 17 21:19 /usr/bin/syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
        -rwxr-xr-x 1 root root 10843065 Jan 17 22:47 /usr/bin/syncthing.old
        -rwxr-xr-x 1 root root 10860536 Jan 21 22:41 /usr/bin/syncthing

**Comment by AudriusButkevicius** [comment]
Duplicate of #1281 
But thanks for the logs.
