### ISSUE TITLE
File / Dir name length and Windows

### ISSUE THREAD

**Issue by RafiKueng** [syncthing/syncthing#1295]
This is not really a bug in syncthing, but one in windows / ntfs to be aware of and (maybe) to work around:

Pathnames in NTFS are usually restricted to 256 chars (260-4: 'C:\' in the beginning and \NULL at the end; it's complicated, see [1] and [2]):
> "In the Windows API (with some exceptions discussed in the following paragraphs), the maximum length for a path is MAX_PATH, which is defined as 260 characters." [2]

So a perfect valid `long255charfilename.ext` with 255 chars won't be synced, because the creation of the temp file `~syncthing~.long255charfilename.ext.tmp` fails in the sync target (the one receiving the file) [3]

If I read the docs [2] correctly, there are "extended-length path for a maximum total path length of 32,767 characters". So all you should have to do is to prefix your paths with "\\\\?\" if using the proper api calls. But be aware that the conversion of '/' to '\' wont work anymore and relative path using dots neither  (Again, all according to the docs, I did not test this, since I don't have a win machine set up for dev at the moment)

A side effect would then probably be, that those files won't be accessible in windows explorer and certain applications.. But the files are there and applications with proper long file name support should be able to read them. Thats what I would propose as the best way to handle it.

[1] http://stackoverflow.com/questions/265769/maximum-filename-length-in-ntfs-windows-xp-and-windows-vista
[2] https://msdn.microsoft.com/en-us/library/aa365247.aspx
[3] The error message: (running on win8.1 x64)
```
[NLXEG] 23:43:22 INFO: Puller (folder "documents", file "Uni\\Lectures\\INI410 - The Neurobiology of Consciousness - Daniel Kiper, Alex Gamma (Daniel Koch, Heather Berlin) - HS2008\\Lecture Sildes\\Lect 10 - Conclusions to Consciousness from Split-Brain Patients and Agnosias [Dr. H. Berlin].pdf"):
dst create: open s='D:\data\Documents\Uni\Lectures\INI410 - The Neurobiology of Consciousness - Daniel Kiper, Alex Gamma (Daniel Koch, Heather Berlin) - HS2008\Lecture Sildes\~syncthing~.Lect 10 - Conclusions to Consciousness from Split-Brain Patients and Agnosias [Dr. H. Berlin].pdf.tmp': Das System kann den angegebenen Pfad nicht finden.
```

**Comment by AudriusButkevicius** [comment]
This should probably be part of the wiki. And isn't it `\\?\`?

**Comment by RafiKueng** [comment]
Yes, thanks, I corrected it in the original post.

I just saw that one can simply enter the path like this in the gui, then it works.

I would suggest thou to make it happen in the backend automatically for all paths on windows. Or is there anything against this?

**Comment by AudriusButkevicius** [comment]
We are not sure it works with 100% of the calls that we are making, plus this can make some files inaccessible from some applications as they use the old style WIN32 API, so not great default behaviour.

Also, feel free to make a wiki post about this.

**Comment by AudriusButkevicius** [comment]
I guess @calmh should make a decision about this and close it.
I feel it wouldn't make it any worse, but it does involve writing a bit of code to make this happen.

**Comment by StrikerTwo** [comment]
.NET has the same problem, but there are drop-in replacement libraries like http://alphafs.alphaleonis.com that allow your code to use long filenames without changing it (apart from pointing it to the new library).
Maybe there is something comparable for Go?
