### ISSUE TITLE
port 8080 sucks

### ISSUE THREAD

**Issue by naught101** [syncthing/syncthing#1296]
Syncthing uses port 8080 by default. So does Jenkins. So do HTTP caching proxies and a [bunch of other things](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers#Well-known_ports). I'd suggest choosing a different port by default. 

Also, if port 8080 *is* in use, it's not possible to start syncthing (it tries port 8080 five times in 5 seconds, and then gives up). Ideally, there would be a way to manually set the port when running syncthing, maybe there already is, but I can't see it.

**Comment by rumpelsepp** [comment]
I agree, but if port 8080 is not available I thought syncthing chooses another port randomly, doesn't it?

**Comment by AudriusButkevicius** [comment]
It does AFAIK. But I will check. 
You can set the port by `-gui-address=127.0.0.1:12345`

**Comment by AudriusButkevicius** [comment]
Actually it doesn't do it anymore, but I think it's fine.
Rather we fail hard and loud rather than pick a random port silently.
Also, you can edit your config.xml to change the port.

**Comment by naught101** [comment]
Ah, ok.   `-gui-address=""  Override GUI address` in the help text is not very descriptive, and doesn't mention the port, so I missed that.

**Comment by basickarl** [comment]
I agree also, I do a lot of development and 8080 is used way too much by everything.

**Comment by calmh** [comment]
We need to default to something, and 8080 is traditional. At first startup, we do pick another port if 8080 is in use. If you're a developer running a lot of things that expect to listen on 8080, you will know about the issue and how to change it. So I don't think is a real issue for most users.
