### ISSUE TITLE
Unresolvable "leveldb/table: corruption on data-block"

### ISSUE THREAD

**Issue by Nils-TUD** [syncthing/syncthing#1297]
I have read in other issues that the data corruption problem has been solved in v0.10.7+, but it seems to still exist. I already had it a couple of times now. It started 2 months ago or so. Until now it always helped to just remove the index-folder and restart syncthing. This time, this does not seem to work. I've done that a few times now, but I always get the corruption error at some point.

I'm currently using v0.10.21. There are multiple devices in my "syncthing network", but only 2 of them were connected while the problem occurred and I have removed the index on both. I've uploaded a few of the panic-logs I received. Please tell me if you need more:
* http://pastebin.com/ELq60ZaA
* http://pastebin.com/jJE805qS
* http://pastebin.com/jz3j7e4B

Note also that one of my syncthing instances runs on ARM, the other on x86. The problem only occurred on ARM so far.

I hope you can fix this bug very soon, because this is of course a showstopper since I can't use syncthing at the moment. And I really want to stick to it, because it's the best sync-solution for me, apart from these problems :)

**Comment by AudriusButkevicius** [comment]
Hi.

You should stop all nodes, delete all indexes while all nodes are offline, and try bringing the cluster back up again.

The corruption is purely within the index directory, hence once it's removed it shouldn't happen again.

Regardless, the logs do have some interesting info there regarding other things, so I'll mark this as a bug.

**Comment by Nils-TUD** [comment]
I've already done that this morning without success, but have tried that again now. Twice. The first time, the result was the same as this morning. The second time it worked. No idea why. Shouldn't that be deterministic?

But thanks, I can at least use it again now :)

**Comment by AudriusButkevicius** [comment]
Perhaps the drive you are writing to is giving up? Regardless the errors you are getting are very funky, happening at completely random places. 

Also syncthing has two processes so perhaps you were killing the wrong one.

**Comment by Nils-TUD** [comment]
> Perhaps the drive you are writing to is giving up? Regardless the errors you are getting are very 
> funky, happening at completely random places.

Ah, good idea. I've checked dmesg now and it seems that this could really be the reason. There are a couple of lines like "INFO: task flush-8:32:1068 blocked for more than 120 seconds." and a backtrace that contains ext4_da_writepages. So there is definitely something wrong with my disk or so. I need to check that further. Thanks!

> Also syncthing has two processes so perhaps you were killing the wrong one.

Yes, I checked that all were gone.

**Comment by Otto23** [comment]
Hello!
Linux Mint 17.
An error "leveldb/table: corruption on data-block" occurs. I delete all indexes, run the program and then again there is the same error.
The hard disk drive is in good condition, at least dmesg does not give errors "INFO: task flush...". Logs: http://rghost.ru/6MlDvZfnr

**Comment by AudriusButkevicius** [comment]
Is your index being stored in a remote file system?
As you have a lot of CIFS failures in your dmesg log.

**Comment by Otto23** [comment]
Indexes and home directory is stored on the local hard drive.
I have two folders on two different hard drives. The first hard disk are indexes, home directory and folder "Cloudbox". On the second hard drive folder "Distrib".
This problem only occurs because of problems with the hard drive? Prior to that, I had no complaints about the work of the my hard drives.

**Comment by AudriusButkevicius** [comment]
Well perhaps the index is just corrupt, but the fact that it happens immediately after removing it is suspicious, as it should only happen if some writes are failing.

**Comment by AudriusButkevicius** [comment]
Dup of #987
