### ISSUE TITLE
In sync percentage should be weighted to folder size, not just average of folder completion

### ISSUE THREAD

**Issue by Dot-Dash** [syncthing/syncthing#1300]
While syncing a folder of 26 GiB, 12.8GiB of which has been completed, Syncthing shows that as "Syncing (73%)"  at one end, while showing "Syncing (45%)" at the other end. In my case, the Documents folder is being synced. The "Default" folder exists, but has nothing of significant size to contribute. The 45% number looks more accurate to me. 

MacOS 10.10.1. 

![syncing 73 percent](https://cloud.githubusercontent.com/assets/6632885/5909081/30ea1050-a57b-11e4-9293-458464f5c9b3.jpg)
![syncing 45 percent](https://cloud.githubusercontent.com/assets/6632885/5909085/3c1d270a-a57b-11e4-8f26-69139859cf2e.jpg)

**Comment by AudriusButkevicius** [comment]
I think it takes the average for all folders involved, which makes sense as the global state.

**Comment by Dot-Dash** [comment]
Averaging percentages of folders is meaningless. If you are 100% done with a tiny folder and 1% done with a huge folder, you are nowhere near 50% done overall.

**Comment by AudriusButkevicius** [comment]
Well I am 50% done on a folder per folder basis. But yes it could be better. It's just that working out exact percentages means we have to scan the whole database with is damn expensive as it is already.

**Comment by addisonamiri** [comment]
This has been bugging me recently? Has anyone been able to figure out where the discrepancy is? I tried looking through the code but I couldn't figure it out.

**Comment by AudriusButkevicius** [comment]
It was explained in the second post.

**Comment by calmh** [comment]
What's the actual request here - what would be the desired end state to resolve this ticket?

**Comment by Dot-Dash** [comment]
The desired end state is for the percentages at both ends to accurately reflect the amount of work left to complete the sync, compared to the amount of work already done. If you've been syncing for 90 minutes, and the percentage reads 90%, you should be able to expect that the sync will be complete in about 10 minutes more.

**Comment by calmh** [comment]
The percentage really has nothing to do with how long we've been syncing though - it's a measure of how much of the data is in sync. I can shut down Synchting, start it up again, and it's instantly at 90%. This says nothing about the time or effort to complete those remaining ten percentage points.

Currently the percentage is the average of all folders, so if three folders are shared, two of them are in sync and the second is halfway done, the total percentage is (100 + 100 + 50) / 3 = 83% complete. I could see us using the actual space instead, where if the folders are one, two and four gigs large we might have for example (1GB + 2GB + 2GB) / (1GB + 2GB + 4GB) = 71% complete instead.

**Comment by addisonamiri** [comment]
I think that second example, where the size of the folders is taken into
account, is more intuitive. It's more a reflection of how much data is in
sync instead of the number of folders that are in sync (if that makes
sense).

**Comment by capi** [comment]
I tend to agree with @addisonamiri, that using the folder sizes would be a more meaningful metric for progress.

**Comment by AudriusButkevicius** [comment]
Percentages are relative to size, why is that no good?

**Comment by capi** [comment]
No it isn't as, the all folders are weighted identically, regardless of their size. I could have 9 repositories with 1MB, and 1 with 1TB, and once the 9MB have been synced, the synchronization progress would be 90%, which I tend to agree is counter-intuitive.

**Comment by calmh** [comment]
I've changed the issue description to reflect that.

**Comment by Ferroin** [comment]
I'm kind of curious why this has been left untouched.  The current implementations reported metric is at best essentially useless without some extra information (which the UI admittedly does provide) and a not insignificant amount of math, and at worst severely misleading.  The only advantage that it appears to have over a proper weighted average is that it's computationally simpler, which is itself not a good argument for knowingly misleading the user.

**Comment by AudriusButkevicius** [comment]
It's untouched because nobody cares enough about this. Please feel free to solve this is you feel about it strongly. It's an open code base afterall.

Also, close your other ticket if this one covers tye issue.
