### ISSUE TITLE
building with GOPATH

### ISSUE THREAD

**Issue by quite** [syncthing/syncthing#1301]
Disclaimer: I'm a complete newbie to go.

I just tried out a small command-line weather program, written in go: https://github.com/schachmat/wego.git

To build wego, you set the `GOPATH` and do: `go get github.com/schachmat/wego`.
wego will then be fetched and built and `GOPATH/bin/` and `GOPATH/src/` are populated.

It is then very simple to, for example, link the bin to your `~/bin` (even `GOPATH=~` is possible!).

Would it be possible to arrange for syncthing to be built like this? Imagine:

    export GOPATH=~/.go  (typically in ~/.profile)
    go get github.com/syncthing/syncthing
    ln -s -t ~/bin/  ../.go/bin/syncthing

**Comment by quite** [comment]
Ah, yes.

    $ go get github.com/syncthing/syncthing

    can't load package: package github.com/syncthing/syncthing: no buildable Go source files in /home/quite/.go/src/github.com/syncthing/syncthing

**Comment by AudriusButkevicius** [comment]
syncthing itself is located in `github.com/syncthing/syncthing/cmd/syncthing`

**Comment by AudriusButkevicius** [comment]
but to be honest, you should just clone the repo
and run ./build.sh
