### ISSUE TITLE
advanced selective sync

### ISSUE THREAD

**Issue by Gregy** [syncthing/syncthing#1303]
Hello,
thank you very much for syncthing. It is a great software :)

However, currently it is not possible to exactly control which files are synced and which are not synced. Ignore patterns have serious shortcomings (mainly not possible to include file in excluded directory). 

Would it be possible to implement "selective mode" in which only metadata is synchronized. Ideally this would be represented by current directory structure on the client or just menu in gui. Benefit of the directory structure would be that you could interact with it in CLI. For example
```
cd /my/repository/folder1/subfolder1
syncthing ls
# displays all files even ones that are not synced
syncthing sync currentlyNotSyncedFile.Name
# file currentlyNotSyncedFile.Name starts to sync
```

I understand that it is not trivial to do things like this but I still think syncthing's feature request list should have something like this in 'when the high priority stuff is done' category.

Thanks

**Comment by AudriusButkevicius** [comment]
yeah this would need a fuse wrapper and would only work on systems that support them, and outside of the scope of what syncthing is.
So I am sure that this is a won't fix in some sense.
Unless you want to go on the venture implementing this, as it would have pretty much nothing in common with syncthing, just the protocol.

Though there is:
https://github.com/syncthing/syncthing/issues/1185

Which should allow you which subdirectories to sync, but not files.

Also you can already sync certain files in excluded directories, but it's very cryptic syntax (as explained in the forum post linked in that issue)

**Comment by Gregy** [comment]
#1185 looks promising :) If it is implemented to the file level, it pretty much covers this feature request too.

Thank you.

**Comment by AudriusButkevicius** [comment]
I doubt it will be implemented at the file.
Neither dropbox nor onedrive have it.
If you want something at a file level, just use a web server to serve your files.
