### ISSUE TITLE
Locked files stall Puller on MacOS

### ISSUE THREAD

**Issue by Dot-Dash** [syncthing/syncthing#1307]
Any locked file in MacOS leads to "operation not permitted", and "Folder isn't making progress" errors. By "locked", I mean the "Locked" Checkbox in the *Get Info* Finder window. 

MacOS 10.10.1
Syncthing 0.10.21

>[T4Z2Y] 21:02:32 INFO: Puller (folder "Documents", file "xxx.pdf"): shortcut: chmod /Users/jamie/Documents/xxx.pdf: operation not permitted
>[T4Z2Y] 21:02:32 WARNING: Folder "Documents" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.

**Comment by AudriusButkevicius** [comment]
Well what fo you expect to happen?

**Comment by Dot-Dash** [comment]
That's a valid question.  
I would expect that syncthing would synchronize the file to the other end copying all permissions and attributes, including "Locked". That's what Dropbox does. 
I would also expect that if syncthing has a problem with a particular file for any reason, that should not be allowed to stop or significantly slow down the synchronization of other files.

**Comment by AudriusButkevicius** [comment]
Well it seems that it is now the other way around. 
Syncthing is receiving a change for a file which is effectively read only, hence why it fails.

Also, I assume Locked is a OS X specific thing?
We do not support extended attributes of different distribution as they don't always have translations to remote systems, though we do sync standard permissions which are more or less available on all systems.

**Comment by Dot-Dash** [comment]
FYI, OS X lock is apparently a "file flag" named *uchg*. Windows has a file lock attribute behind the scenes, but it is not controllable in the GUI.  When locking this file in OS X, the only thing that appeared to change was the uchg flag. 
>Jamies-iMac-2:Documents jamie$ ls -Ol temp.jpg 
>-rw-r--r--@ 1 jamie  access_bpf  uchg 20475 Jan 28 11:29 temp.jpg

**Comment by AudriusButkevicius** [comment]
Yeah, so I guess this is a won't fix.

**Comment by Dot-Dash** [comment]
Thanks for considering my comments.
