### ISSUE TITLE
Deploying Syncthing on Openshift Online?

### ISSUE THREAD

**Issue by khurshid-alam** [syncthing/syncthing#1310]
I was trying to deploy Syncthing on Openshift as DIY project. On  open only usable ports are `8080` & between `15000 - 35530`. Also one can not use `0.0.0.0 or 127.0.0.1`. one has to use `$OPENSHIFT_INTERNAL_IP` or `$OPENSHIFT_DIY_IP(127.12.x.x)` as in my case.

This is my `OPENSHIFT_REPO_DIR/diy/syncthing/.config/config.xml` (manually created)
```xml
<configuration version="7">
    <device id="YBS7UI3-5Y7V7W2-KPTZZR4-LU3Y5TH-UTE6JJS-ID55PT3-GSI73NW-ZBOHSQU" name="ex-std-node515.prod.rhcloud.com" compression="false" introducer="false">
        <address>dynamic</address>
    </device>
    <gui enabled="true" tls="true">
        <address>127.12.74.128:8080</address>
        <user>jb</user>
        <password>$2a$10$EKXXXXX...</password>
        <apikey>O80CDOJ9LVXXXXXXXXXXXXXXXXXX</apikey>
    </gui>
    <options>
	<listenAddress>127.12.74.128:24097</listenAddress>
        <globalAnnounceServer>udp4://announce.syncthing.net:22026</globalAnnounceServer>
        <globalAnnounceEnabled>true</globalAnnounceEnabled>
        <localAnnounceEnabled>true</localAnnounceEnabled>
        <localAnnouncePort>21025</localAnnouncePort>
        <localAnnounceMCAddr>[ff32::5222]:21026</localAnnounceMCAddr>
        <maxSendKbps>0</maxSendKbps>
        <maxRecvKbps>0</maxRecvKbps>
        <reconnectionIntervalS>60</reconnectionIntervalS>
        <startBrowser>false</startBrowser>
        <upnpEnabled>true</upnpEnabled>
        <upnpLeaseMinutes>0</upnpLeaseMinutes>
        <upnpRenewalMinutes>30</upnpRenewalMinutes>
        <urAccepted>0</urAccepted>
        <urUniqueID></urUniqueID>
        <restartOnWakeup>true</restartOnWakeup>
        <autoUpgradeIntervalH>12</autoUpgradeIntervalH>
        <keepTemporariesH>24</keepTemporariesH>
        <cacheIgnoredFiles>true</cacheIgnoredFiles>
        <progressUpdateIntervalS>5</progressUpdateIntervalS>
        <symlinksEnabled>true</symlinksEnabled>
    </options>
</configuration>
```

But when I run (after ssh to server) `./syncthing -home="$OPENSHIFT_REPO_DIR/diy/syncthing/.config"`, I am getting following error:

```
[monitor] 13:26:33 INFO: Starting syncthing
[YBS7U] 13:26:34 INFO: syncthing v0.10.21 (go1.4.1 linux-386 default) unknown-user@syncthing-builder 2015-01-19 20:40:36 UTC
[YBS7U] 13:26:34 INFO: My ID: YBS7UI3-5Y7V7W2-KPTZZR4-LU3Y5TH-UTE6JJS-ID55PT3-GSI73NW-ZBOHSQU
[YBS7U] 13:26:34 INFO: Starting web GUI on https://127.12.74.128:8080/
[YBS7U] 13:26:36 INFO: Starting local discovery announcements
[YBS7U] 13:26:36 INFO: Starting global discovery announcements
[YBS7U] 13:26:36 INFO: Device YBS7UI3-5Y7V7W2-KPTZZR4-LU3Y5TH-UTE6JJS-ID55PT3-GSI73NW-ZBOHSQU is "ex-std-node515.prod.rhcloud.com" at [dynamic]
[YBS7U] 13:26:36 WARNING: discover udp4://announce.syncthing.net:22026: broadcast: listen udp4 :0: bind: permission denied; trying again in 1m0s
```

As seen from the log, it is starting but It is getting `permission denied` when it tries to bind `udp4 :0:` for `udp4://announce.syncthing.net:22026:`. How to change that bind address? 

What should I do to fix this?

**Comment by AudriusButkevicius** [comment]
`udp4://announce.syncthing.net:22026/?listenaddress=interfaceip`

You cannot set a fixed port though.

**Comment by khurshid-alam** [comment]
@AudriusButkevicius Ok I tried with 
```xml
<globalAnnounceServer>udp4://announce.syncthing.net:22026/?listenaddress=127.12.74.128</globalAnnounceServer>
```
Is that what you mean?

It does not throw any error, but I can not reach GUI from dns.  Browser shows `This webpage has a redirect loop`. ?

LOG:
```
[YBS7U] 02:40:01 INFO: syncthing v0.10.21 (go1.4.1 linux-386 default) unknown-user@syncthing-builder 2015-01-19 20:40:36 UTC
[YBS7U] 02:40:01 INFO: My ID: YBS7UI3-5Y7V7W2-KPTZZR4-LU3Y5TH-UTE6JJS-ID55PT3-GSI73NW-ZBOHSQU
[YBS7U] 02:40:01 INFO: Starting web GUI on https://127.11.74.129:8080/
[YBS7U] 02:40:04 INFO: Starting local discovery announcements
[YBS7U] 02:40:04 INFO: Starting global discovery announcements
[YBS7U] 02:40:04 OK: Ready to synchronize default (read-write)
[YBS7U] 02:40:04 INFO: Device YBS7UI3-5Y7V7W2-KPTZZR4-LU3Y5TH-UTE6JJS-ID55PT3-GSI73NW-ZBOHSQU is "ex-std-node515.prod.rhcloud.com" at [dynamic]
[YBS7U] 02:40:04 INFO: Completed initial scan (rw) of folder default
```

**Comment by AudriusButkevicius** [comment]
This has nothing todo with gui so I am not sure what your problem is. Perhaps you have some reverse proxy loop? Try using curl or something to see if you can access the page, if not provide curls output with headers.

**Comment by khurshid-alam** [comment]
According to this blog (http://samglover.net/bittorrent-sync-amazon-ec2) which describes how to deploy bit torrent sync on Amazon EC2.

The server starts on both local machine & ec2-server & then he used port forwarding with ssh tunnel from local machine to get connected to remote GUI.

`sudo ssh -i keypair.pem -L 8888:127.0.0.1:8888 ubuntu@ec2-##-###-##-##.us-west-2.compute.amazonaws.com`

Maybe something similar is required here? (To be honest I do not like the idea).

Anyway, this is more suitable for stackoverflow (as it is now Openshift's new help forum), so I have posted a question there. http://stackoverflow.com/questions/28249354/

**Comment by AudriusButkevicius** [comment]
I think I answered your question regarding how to fix discovery, so I am not sure what are the questions left.
Reopen if there are any.

**Comment by unixfox** [comment]
Any news ?
