### ISSUE TITLE
LXLE (which bundles Syncthing & Syncthing-GTK): should be a way to disable starting up on login

### ISSUE THREAD

**Issue by marclaporte** [syncthing/syncthing#1313]
Please see:
http://lxle.net/forum/#/discussion/796/disable-syncthing-from-starting-up-on-login-

There must be a single setting somewhere?

Thanks!

**Comment by marclaporte** [comment]
Hi!

I suspect this or another recent change has a few side-effects. I don't know if it's in Syncthing, Syncthing-GTK, the PPA or in LXLE.

I am noticing that my LXLE 14.x instances:
1- Are not syncing with the other devices
2- After a configuration change, I am prompted to restart, which I do, but it doesn't. I need to reboot.
3- I tried changing the settings of the firewall, to no avail (It used to work, but I suspected a change in the firewall app)

Windows and LXDE are fine.
LXLE 12.x (32-bit version) with Syncthing 0.10.1 works well (although, it's not updating, which is a distinct issue.

To reproduce. 
1- Set up two LXLE 14.x instances on a LAN, all with the latest updates
2- Manually set the IPs so each instance should connect without any reliance on UPnP.

Any ideas?

Thanks!

**Comment by kozec** [comment]
I'm afraid this is distribution problem, as it's their package or insinstaller what sets upstart service that way. I can't see how can it be fixed in syncthing or ST-GTK.

**Comment by AudriusButkevicius** [comment]
Yes, you should report this to distro maintainers and not here.

**Comment by kozec** [comment]
Just out of curiosity, who is actually building LXDE packages? That guy on LXDE forum clearly believes that upstart script is syncthing dev's fault and as far as I know, nobody here provides packages officially. It's rather weird situation over there...
