### ISSUE TITLE
Consistency checks

### ISSUE THREAD

**Issue by devurandom** [syncthing/syncthing#1315]
It would be great to have continous consistency checks for all files.

For example [git-annex](http://github.com/joeyh/git-annex) runs a "fsck" every day for an hour and compares the sha256sums of all files with the database to detect corrupt ones. If a broken file is detected, it is retrieved from other, healthy nodes.

One important improvement over git-annex would be to really put the consistency checks into the background, so that they do not clog up the whole IO system, while you actually want to work. Thus an actual "idle" mode would be needed.

**Comment by AudriusButkevicius** [comment]
Continuous consistency check is rescanning to some extent. It will not find bit flips, but size changes, mtime changes, attribute changes will trigger a rescan.

**Comment by devurandom** [comment]
Yes, I am more thinking of re-checksumming.

**Comment by AudriusButkevicius** [comment]
Well, this is CPU intensive and IO intensive so I am not sure how you decide when it's a good time to do it.

**Comment by StrikerTwo** [comment]
This is a very good idea. Once a month should be enough for most purposes.

**Comment by Zillode** [comment]
Dealing with data integrity can be handled by the filesystem, for example BTRFS or ZFS are doing this.

**Comment by jpjp** [comment]
This belongs in the filesystem.

**Comment by StrikerTwo** [comment]
The file system can't restore data from other sources. Yes I know, ZFS and ReFS exist, but that does not help the normal Windows user with only one hard disk. (ReFS is only usable with Storage Spaces, you can't even boot from a ReFS partition).
Is there even a ZFS/BTRFS option for Android? If not, that's another target group right there.

**Comment by AudriusButkevicius** [comment]
Well we cannot `restore data` either, because from our perspective it's just a change to the file, we have no clue if the user introduced the change or there was a bit flip.

Unless we blindly believe that you cannot change file content without modifying mtime, which doesn't make sense, as Android doesn't even support mtimes for SD cards.

**Comment by StrikerTwo** [comment]
Good point. I would (maybe naively) have said that changes in checksum without a corresponding change in mtime are not user intended, so it must be bit rot.
But if that's not reliably the case, I don't see a way to distinguish between real changes and bit rot either.

**Comment by calmh** [comment]
I think this will not be implemented, for reasons above. We could detect changes (and it may be worth it to do a full rescan now and then, perhaps as an option, just to catch that?), but can't reason about whether they are intentional or not. The filesystem can know this, though.
