### ISSUE TITLE
Partial/manual repositories

### ISSUE THREAD

**Issue by devurandom** [syncthing/syncthing#1316]
It would be great if I could use another syncthing node as a "backing store" and only sync files I explicitly want, while the store accumulates all files it can get from all other nodes, and makes them thus available to its peers.

This is useful if you have a machine with big storage, e.g. for your holiday photos, but want to sync only some to your phone. Or when you have a machine which stores your films, but your laptop does not have enough storage to store them all.

For example, [git-annex](https://github.com/joeyh/git-annex) has a "manual" mode for its repositories, where I can select the files that I want to be copied to this node manually, and then git-annex will automatically retrieve them for me from another node that has it.

**Comment by AudriusButkevicius** [comment]
It's called using the `ignores` file.

**Comment by devurandom** [comment]
Are the ignores not synced? And I do not completely understand your comments in #1185, but the ignore file can not only be used to exclude some files from being synced, but also to include a few and exclude all others? In that case it would indeed be sufficient. Then I think I could write a small commandline UI for it, and replicate what git-annex does.

Please understand that I did search the list, but could not find what I wanted.

**Comment by facastagnini** [comment]
Dennis, the .stignore file is not sinced. This is very clear in the
documentation.

What I did is add all my shared rules in .stignore_sinced and then include
this secondary file from the main ignore:

#include .stignore_sinced

**Comment by AudriusButkevicius** [comment]
Yes, you can explicitly exclude everything, and include some specific files.
The syntax for it currently is a bit cryptic, as you have to negate the exclusion for every directory up to the final path (hence why #1185 is there), so it goes like this:

```
!/this/file/I/want
!/this/file/I
/this/file/I/*
!/this/file
/this/file/*
!/this
/this/*
*
```

This ignores everything, including files up to the path to `/this/file/I/want`, but at the same time unignores the required directories (required to build the tree)
