### ISSUE TITLE
Local sync

### ISSUE THREAD

**Issue by devurandom** [syncthing/syncthing#1317]
It would be great if syncthing could sync two folders on the same machine, so I could easily store a copy of my files on an external drive.

**Comment by AudriusButkevicius** [comment]
It already can, just run two copies of syncthing.

**Comment by devurandom** [comment]
That seems inconvenient to me. Especially since it would mean adjusting the ports of each instance.

It would feel way better if this was integrated into the GUI.

**Comment by AudriusButkevicius** [comment]
Feel free to make a contribution.
