### ISSUE TITLE
Random crashes with status=3/NOTIMPLEMENTED

### ISSUE THREAD

**Issue by rumpelsepp** [syncthing/syncthing#1324]
I run syncthing with `systemd --user` and it crashes quite often (especially after resume from suspend) with this log:

```
Feb 01 20:46:48 alderaan syncthing[2724]: [TYZZZ] 20:46:48 INFO: Completed initial scan (rw) of folder camera
Feb 01 20:46:49 alderaan syncthing[2724]: [TYZZZ] 20:46:49 INFO: Completed initial scan (rw) of folder dokumente
Feb 01 20:47:26 alderaan syncthing[2724]: [TYZZZ] 20:47:26 INFO: Established secure connection to GDACTPT-HASVGSG-BVKYKA2-AVHRWHN-TNOQ7IG-HSCGH43-G5FT4V7-RD2T5QU at ...
Feb 01 20:47:26 alderaan syncthing[2724]: [TYZZZ] 20:47:26 INFO: Device GDACTPT-HASVGSG-BVKYKA2-AVHRWHN-TNOQ7IG-HSCGH43-G5FT4V7-RD2T5QU client is "syncthing v0.10.21"
Feb 01 20:47:26 alderaan syncthing[2724]: [TYZZZ] 20:47:26 INFO: Device GDACTPT-HASVGSG-BVKYKA2-AVHRWHN-TNOQ7IG-HSCGH43-G5FT4V7-RD2T5QU name is "archvm"
Feb 01 22:54:15 alderaan syncthing[2724]: [TYZZZ] 22:54:15 INFO: Restarting
Feb 01 22:54:15 alderaan syncthing[2724]: [TYZZZ] 22:54:15 OK: Exiting
Feb 01 22:54:15 alderaan systemd[2721]: syncthing.service: main process exited, code=exited, status=3/NOTIMPLEMENTED
Feb 01 22:54:15 alderaan systemd[2721]: Unit syncthing.service entered failed state.
Feb 01 22:54:15 alderaan systemd[2721]: syncthing.service failed.
```

What exactly does `status=3/NOTIMPLEMENTED` mean? How can I provide more information?

```
# /usr/lib/systemd/user/syncthing.service
[Unit]
Description=Syncthing service for %u
After=network.target

[Service]
Environment=STNORESTART=yes
ExecStart=/usr/bin/syncthing
Restart=on-success

[Install]
WantedBy=default.target
```

```
$ syncthing --version
syncthing v0.10.21 (go1.4.1 linux-amd64 default) builduser@jara 2015-01-19 20:40:36 UTC
```

**Comment by AudriusButkevicius** [comment]
We use exit codes to signal our exit reason to the monitor process.
Now because systemd acts as our monitor process, it simply doesn't know how to handle the exit codes we are sending it.

**Comment by rumpelsepp** [comment]
Yeah I know about exit codes. :) I'm just wondering what the exit code `NOTIMPLEMENTED` is going to tell me. :)

**Comment by AudriusButkevicius** [comment]
Exit codes are defined here:
https://github.com/syncthing/syncthing/blob/master/cmd/syncthing/main.go#L68

I guess you need to add support for them in the service definition:
```
RestartPreventExitStatus=1
SuccessExitStatus=2
RestartForceExitStatus=3 4
```

**Comment by rumpelsepp** [comment]
That makes sense. Thx. I will check it out and let you know if works.

**Comment by AudriusButkevicius** [comment]
You might need to scrap `Restart=on-success` if you want to keep the `Shutdown` feature in the web UI, as it most likely will restart it on exit code 0.

**Comment by rumpelsepp** [comment]
> You might need to scrap Restart=on-success if you want to keep the Shutdown feature

This one is provided by the arch linux service. I think I should open a bug report for this...
