### ISSUE TITLE
huge index folder

### ISSUE THREAD

**Issue by robsonsobral** [syncthing/syncthing#1327]
Hi!

Is there a reason for the index folder be so huge? Mine has 110MB for two shared folders:

- 9 files, 43.31MB
- 5524 files, 122.18GB

Is it normal?

**Comment by uok** [comment]
the index size depends on the total size of the data and not so much on the number of files

**Comment by AudriusButkevicius** [comment]
You can try and remove the index directory, let it rescan and rebuild the index in hopes that it will be smaller.

If you have been renaming files directories a lot that might help.

**Comment by robsonsobral** [comment]
@uok , I posted the size of both folders. Is the size of the `index` related to only the size of the data already download to the folder? I'm asking because otherwise huge folders are going to have problems on mobile devices

@AudriusButkevicius , I deleted the `index` folder. Now, I'm waiting for it to finish scanning. I didn't rename any files in these folders after add them.

Thank you both for your attention!

**Comment by uok** [comment]
the index stores meta data and hashes for blocks of data
you can look for more info in the [forum](https://discourse.syncthing.net) (search for *index size*)

**Comment by alex2108** [comment]
My index folder is 26.8 MB for 15GB with ~25000 files so I would say your 110MB sound correct.

**Comment by robsonsobral** [comment]
Ok. Thanks, guys, speacially @uok, who pointed me to that forum thread.

Thanks!
