### ISSUE TITLE
Auto-update leaves around too many .old files

### ISSUE THREAD

**Issue by ludocode** [syncthing/syncthing#1328]
The syncthing auto-update process leaves around a lot of junk files. It just adds .old repeatedly, leading to a complete mess of binaries after running for a few months:

    nick@nick-server ~/bin $ ls -l
    total 427344
    -rwxr-xr-x 1 nick nick 8760225 Jan 28 16:07 syncthing
    -rwxr-xr-x 1 nick nick 8760225 Jan 29 04:07 syncthing.old
    -rwxr-xr-x 1 nick nick 8760225 Jan 29 16:07 syncthing.old.old
    -rwxr-xr-x 1 nick nick 8760225 Jan 30 04:08 syncthing.old.old.old
    -rwxr-xr-x 1 nick nick 8760225 Jan 30 16:08 syncthing.old.old.old.old
    -rwxr-xr-x 1 nick nick 8760225 Jan 31 04:08 syncthing.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8760225 Jan 31 16:08 syncthing.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8760225 Feb  1 04:08 syncthing.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8760225 Feb  1 16:08 syncthing.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8760225 Feb  2 04:08 syncthing.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8718784 Jan  4 13:10 syncthing.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8722880 Jan 10 01:12 syncthing.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8722880 Jan 10 13:12 syncthing.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8722880 Jan 11 01:12 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8722880 Jan 11 13:12 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8749476 Jan 12 01:12 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8749476 Jan 12 13:12 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8749476 Jan 13 01:12 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8749476 Jan 13 13:13 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8747060 Jan 14 01:13 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8747060 Jan 14 13:13 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8747060 Jan 15 01:13 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8747060 Jan 15 13:13 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8747060 Jan 16 01:13 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8747060 Jan 16 13:13 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8747060 Jan 17 01:13 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8747060 Jan 17 13:13 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8747060 Jan 18 01:14 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8747060 Jan 18 13:15 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8747060 Jan 19 01:15 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8747060 Jan 19 13:15 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8747060 Jan 20 01:15 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8747060 Jan 20 13:15 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8747060 Jan 21 01:15 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8747060 Jan 21 13:15 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8760225 Jan 22 01:15 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8760225 Jan 22 13:16 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8760225 Jan 23 01:16 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8760225 Jan 23 13:16 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8760225 Jan 24 01:16 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8760225 Jan 24 13:16 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8760225 Jan 25 01:16 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8760225 Jan 25 13:16 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8760225 Jan 26 01:16 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8760225 Jan 26 13:17 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8760225 Jan 27 01:17 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8760225 Jan 27 13:17 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8760225 Jan 28 01:17 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8760225 Jan 28 13:17 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    -rwxr-xr-x 1 nick nick 8695266 Dec 29 13:08 syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old

I'd have suggested just naming the binary based on its version, except for the fact that many of these are duplicates. This may point to a larger issue in the auto-updater, like maybe it's replacing an existing binary with the same one.

    nick@nick-server ~/bin $ md5sum *
    04283ae32f681427a259b9a968aeb126  syncthing
    04283ae32f681427a259b9a968aeb126  syncthing.old
    04283ae32f681427a259b9a968aeb126  syncthing.old.old
    04283ae32f681427a259b9a968aeb126  syncthing.old.old.old
    04283ae32f681427a259b9a968aeb126  syncthing.old.old.old.old
    04283ae32f681427a259b9a968aeb126  syncthing.old.old.old.old.old
    04283ae32f681427a259b9a968aeb126  syncthing.old.old.old.old.old.old
    04283ae32f681427a259b9a968aeb126  syncthing.old.old.old.old.old.old.old
    04283ae32f681427a259b9a968aeb126  syncthing.old.old.old.old.old.old.old.old
    04283ae32f681427a259b9a968aeb126  syncthing.old.old.old.old.old.old.old.old.old
    1b649fe99e0f0bcee1618820a4676a2b  syncthing.old.old.old.old.old.old.old.old.old.old
    662cd62f642b1a754d526b9843233f8f  syncthing.old.old.old.old.old.old.old.old.old.old.old
    662cd62f642b1a754d526b9843233f8f  syncthing.old.old.old.old.old.old.old.old.old.old.old.old
    662cd62f642b1a754d526b9843233f8f  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old
    662cd62f642b1a754d526b9843233f8f  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    4e3df2d609d5b5bcfd6aff23ed2baed3  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    4e3df2d609d5b5bcfd6aff23ed2baed3  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    4e3df2d609d5b5bcfd6aff23ed2baed3  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    4e3df2d609d5b5bcfd6aff23ed2baed3  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    d62689cb25f550fcbb11fd848083bafb  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    d62689cb25f550fcbb11fd848083bafb  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    d62689cb25f550fcbb11fd848083bafb  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    d62689cb25f550fcbb11fd848083bafb  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    d62689cb25f550fcbb11fd848083bafb  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    d62689cb25f550fcbb11fd848083bafb  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    d62689cb25f550fcbb11fd848083bafb  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    d62689cb25f550fcbb11fd848083bafb  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    d62689cb25f550fcbb11fd848083bafb  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    d62689cb25f550fcbb11fd848083bafb  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    d62689cb25f550fcbb11fd848083bafb  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    d62689cb25f550fcbb11fd848083bafb  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    d62689cb25f550fcbb11fd848083bafb  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    d62689cb25f550fcbb11fd848083bafb  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    d62689cb25f550fcbb11fd848083bafb  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    d62689cb25f550fcbb11fd848083bafb  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    04283ae32f681427a259b9a968aeb126  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    04283ae32f681427a259b9a968aeb126  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    04283ae32f681427a259b9a968aeb126  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    04283ae32f681427a259b9a968aeb126  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    04283ae32f681427a259b9a968aeb126  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    04283ae32f681427a259b9a968aeb126  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    04283ae32f681427a259b9a968aeb126  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    04283ae32f681427a259b9a968aeb126  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    04283ae32f681427a259b9a968aeb126  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    04283ae32f681427a259b9a968aeb126  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    04283ae32f681427a259b9a968aeb126  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    04283ae32f681427a259b9a968aeb126  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    04283ae32f681427a259b9a968aeb126  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    04283ae32f681427a259b9a968aeb126  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old
    90891e21f07789cb81f603827ebb5d53  syncthing.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old.old

**Comment by ludocode** [comment]
To give a bit more info, I originally installed 0.9.19, and it's now running 0.10.21. I only count 7 distinct files out of 50 total in that list though.

This is the armv6 port running on a Raspberry Pi. This is actually a serious problem for this reason:

    nick@nick-server ~/bin $ du -hs 
    418M    .

This Raspberry Pi has a 4 GB SD card, so nearly 1/8th of the entire space on the disk is used by old syncthing binaries.

**Comment by AudriusButkevicius** [comment]
This is a duplicate and I believe this was addressed. Search the tracker.

**Comment by ludocode** [comment]
I did a search before posting and found nothing. I looked a while longer just now and found #1281 which looks like the same issue (it doesn't actually mention auto-updating, just .old files, which I suppose is why I didn't find it.)
