### ISSUE TITLE
Font size of folder headers

### ISSUE THREAD

**Issue by tvld** [syncthing/syncthing#1330]
Great-great product. One little little cosmetic thing: the headers in the folders now have: green background, larger font size & bold. One of three would be enough, for example only green background & bold. Now it just looks uncool on my Lenovo Yoga (3200px screen)

![screenshot from 2015-02-05 10 19 11](https://cloud.githubusercontent.com/assets/986182/6057793/9edc81ee-ad21-11e4-9762-7f455e8474d6.png)

**Comment by AudriusButkevicius** [comment]
Wrong repo https://github.com/syncthing/syncthing-gtk

**Comment by tvld** [comment]
My bad, sorry.
https://github.com/syncthing/syncthing-gtk/issues/87
