### ISSUE TITLE
Infinite .old directories

### ISSUE THREAD

**Issue by cfarence** [syncthing/syncthing#1334]
Just noticed this today, I don't know if this has already been fixed. I didn't see anything in the commit history. But if I missed it feel free to delete this.

It seems that when syncthing updates it doesn't delete the .old directory it created. So next time when it updates again it creates a new .old.old directory. It looks like this will keep happening indefinitely.

Screenshot from my syncthing installation:
http://prntscr.com/61nf81

**Comment by boomlinde** [comment]
This looks like a duplicate of #1281

**Comment by cfarence** [comment]
Oops my bad :)
