### ISSUE TITLE
Normalize JSONs

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#1338]
DownloadProgress paths use OS specific separator, we should normalize the file names.
ItemStarted, ConfigSaved might have wrong capitalization for the key names, or atleast should try and have lowercase names for the sake of consistency.

**Comment by canton7** [comment]
Bear in mind that changing keys in the JSON will break any consumers of the REST API

**Comment by pascalj** [comment]
I'm writing a consumer of the API and just stumbled across the different capitalizations per endpoint. I'd like to unify the [documented](https://github.com/syncthing/syncthing/wiki/REST-Interface) endpoints and write more detailed documentation for the JSON format.

Do you have anything particular in mind regarding the changes? How "final" is the API?

**Comment by AudriusButkevicius** [comment]
I guess it should be "camelCase", given that's how the larger majority is now.

**Comment by calmh** [comment]
Yes, when we're anyway changing things. I guess the other variant is CamelCase as that's how exported fields in Go are named.

**Comment by AudriusButkevicius** [comment]
Well two different opinions do not necessarily answer the question, hence @calmh make a decision.

**Comment by calmh** [comment]
Sorry for being unclear. We should do `camelCase` on all JSON. The current presence of `CamelCase` is just laziness in not specifying a JSON encoding on the structs.

I don't really care too much whether we always use `/` as path separator or the local OS convention, as long as we always do the same thing. :)
