### ISSUE TITLE
Automatic upgrade not working

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#1340]
I just noticed that Syncthing shows a new version :smile: (0.10.22) but does nothing :confused: 
Exptected: automatic restart/upgrade without clicking blue button
Only me or everyone else? :eyes:

**Comment by AudriusButkevicius** [comment]
It checks once every 12 hours.

**Comment by uok** [comment]
could we improve this?
if (setting.autoupdate = true and blueupdatebuttonshown = true) then update

**Comment by AudriusButkevicius** [comment]
Feel free to fix this.

**Comment by calmh** [comment]
Note that it may also be annoying if it auto upgrades just as you open the web GUI (presumably because you want to do something with it)...

**Comment by uok** [comment]
I thought "blue update button" means that Syncthing knows about update and will update soon(ish)
all nodes updated later without a problem

**Comment by AudriusButkevicius** [comment]
Yeah it does, but only because you opened the page, not because it knew before you opening the page. 

Given you have opened the page and the button is there, you might as well burn some micro calories and click the button.

**Comment by uok** [comment]
> burn some micro calories

:smile: great excuse to get :pizza: and :beer:
