### ISSUE TITLE
Document `master folder` in the Wiki

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#1343]
I am looking at the `Override changes` thing, and still cannot exactly explain how it works.

If on a non-master node I modified the file 10 times, and then later modified the file on a master node, is the global version now the masters version? Or would I need to modify the file 11 times on master for it to propagate?

**Comment by calmh** [comment]
And in the process, consider if we want thus button at all or if the underlying issue should be solved in another way. Perhaps just in the UI? ("There are unsynced files, but we are the master. Click here for the full list." or whatever)

**Comment by AudriusButkevicius** [comment]
We should also have a general section in the wiki about this feature, as many find it confusing, and I've had to explain it in the forums multiple times.

The reason I haven't added a section yet, is because of the question in the initial post.

**Comment by Rewt0r** [comment]
I'm about to implement this because of the issue we hit on Friday but do not quite understand it myself. WOuld the Override Changes button bring all the changes made outside of the master to the master?

**Comment by AudriusButkevicius** [comment]
Its the other way around. It brings masters version back to everyone.

**Comment by Rewt0r** [comment]
So what if I wanted to setup a backup server as Master and then pull the changes from everyone else at set intervals?

**Comment by AudriusButkevicius** [comment]
syncthing != backup

You sort of have 3 options I guess:
1. Enable versioning, which sort of acts as a backup.
2. Toggle master mode on and off when you want to take a snapshot of the global state.
3. Participate in the cluster as normal, doing an rsync with --list-dest every N minutes snapshotting the clusters state.

**Comment by calmh** [comment]
http://docs.syncthing.net/users/foldermaster.html
