### ISSUE TITLE
stops after ~100MB synced

### ISSUE THREAD

**Issue by jl777** [syncthing/syncthing#1344]
I have a folder with ~500,000 files, mostly small but some that are tens of megabytes. it works fine for a while, but then stops. I think it is running out of some resource. does not appear to be a memory leak, so maybe it is just running out of file pointers. I think to limit the number of files being sync'ed at once?

my directory structure is 64 directories of 64 directories, which each have hundreds of files in them. so this is a pretty extreme case probably not expected.

all in all quite a nice thing!

**Comment by AudriusButkevicius** [comment]
Are there any errors in the console?

**Comment by jl777** [comment]
no errors
the xfer rate was doing decently at first, ~200KB/s
but now it is <10KB/s

running with STTRACE=xdr but hardly any prints


 Folder Path	/home/admin1/Sync/
 Global State	353648 items, ~21.7 GiB
 Local State	2233 items, ~172 MiB
 Out Of Sync	352300 items, ~21.6 GiB
 Shared With	mgw1
 Last File Received	327697.B

vs

 Global State	445361 items, ~33.8 GiB
 Local State	445361 items, ~33.8 GiB
 Folder Master	Yes
 Rescan Interval	10 s
 Shared With	mgw0

so the global state hasnt propagated fully and it is doing the small files, they are <100 bytes, so that explains the low bandwidth. There must be some significant delay between files?

**Comment by jl777** [comment]
bandwidth variance is definitely due to file size, so the performance bug is that small files really kill the throughput:

 Download Rate	29.6 KiB/s (25.5 MiB)
 Upload Rate	10.8 KiB/s (151 KiB

less than 10% of the big files, the other strange thing is that the mgw0 has several large files in is Sync folder, but these are not getting to the other node. Could it be due to making the node with 450K files readonly?

also is there a way to have a file that should be the same sourced from different nodes? not sure what will happen if there is disagreement on the file contents, some sort of consensus based process.

**Comment by jl777** [comment]
interesting development. now it is mostly not doing any transfers, but the node without the files got to the same global state and then the bandwidth is now:

 Download Rate	0 B/s (25.6 MiB)
 Upload Rate	0 B/s (238 KiB)

but it still does a bit of transfers then goes comatose.. actually, it seems the display is underreporting as looking at du totals it is going up a lot more than the few bytes per second would make it.

**Comment by jl777** [comment]
I probably shouldnt have set the directory scanning at 10 seconds with so many files. I think that is the cause for the performance drop. it is stuck on "Scanning" (the node with all the files) and i doubt it can get through all half million files in 10 seconds. I will change the time between scans and see what happens

**Comment by AudriusButkevicius** [comment]
Yes, there is locking involved between scanning and sending, so 10s is definitely too low, at least until the initial sync has propagated.
