### ISSUE TITLE
forking process to background

### ISSUE THREAD

**Issue by maffmeier** [syncthing/syncthing#1348]
Hello,

is it possible to fork the process to the background after startup.
This option would it make easier to deamonize syncthing.

For example you start syncthing like: syncthing --deamon

**Comment by AudriusButkevicius** [comment]
Just use your shell to do that:
`syncthing & disown`

**Comment by maffmeier** [comment]
Ok on a Unix-Maschine is this solution no problem.
But how do I di this on a windos maschine?

**Comment by AudriusButkevicius** [comment]
You start syncthing with `-no-console`?
Or if you are trying to script something up:
```
@echo off
call "cmd /c start syncthing.exe -no-console"
```
?

**Comment by maffmeier** [comment]
Ah okay I've over read this option.

I'm sorry!
