### ISSUE TITLE
building on dragonfly bsd - only minor changes required

### ISSUE THREAD

**Issue by sysadminmike** [syncthing/syncthing#1351]
2 files need updating with dragonfly added to the build os and a case for the execute() function

syncthing/Godeps/_workspace/src/github.com/calmh/osext/osext_procfs.go

      // +build linux netbsd openbsd solaris dragonfly

	case "dragonfly":
		return os.Readlink("/proc/curproc/file")

and

syncthing/cmd/syncthing/memsize_unimpl.go

     // +build freebsd openbsd dragonfly

**Comment by AudriusButkevicius** [comment]
PR welcome.

**Comment by sysadminmike** [comment]
have sent a PR i think
