### ISSUE TITLE
Syncthing increases timer frequency on Windows

### ISSUE THREAD

**Issue by seidler2547** [syncthing/syncthing#1354]
On my Windows 8 system, running syncthing will cause the timer interval to be 1ms instead of the default 15.625ms. This is something which is also happening with Chrome, apparently, see here for more information: https://randomascii.wordpress.com/2013/07/08/windows-timer-resolution-megawatts-wasted/

**Comment by calmh** [comment]
Looks like https://github.com/golang/go/issues/8687, not much we can do from our side, but once that is fixed we'll get the fix automatically.

**Comment by defia** [comment]
@calmh you can discard the setting by calling win32api if uou like, i've mentioned how to do that in my comment of the issue. i guess it will not affect much performance.
