### ISSUE TITLE
Just a typo

### ISSUE THREAD

**Issue by grumpycatt** [syncthing/syncthing#1358]
Hi there,

I just successfully compiled syncthing on my test env. and I noticed a typo on the launch output : 

[M4U2O] 22:19:40 INFO: No automatic upgrades; v0.10.22+20-g5d93963 is not a --> relase <-- version.

Regards

**Comment by marclaporte** [comment]
If you click here: https://github.com/syncthing/syncthing/edit/master/cmd/syncthing/main.go you can find it, fix it, and send a pull request :-)
