### ISSUE TITLE
The path in the gui is not the path in my config file (trailing slash issue)

### ISSUE THREAD

**Issue by jpjp** [syncthing/syncthing#1361]
I noticed that the config file contains something like this:

    <folder path="~/yep/">

but the gui shows a path of:

    ~/yep

**Comment by AudriusButkevicius** [comment]
You can remove it from the config and it should be just fine. 
Or just force the config to be re-saved and it should also go away too.

What is the effect on functionality here, apart from just being OCD?

**Comment by jpjp** [comment]
I want to make triply sure my directory is a directory, so I use a trailing slash, just like with other linux tools.

**Comment by AudriusButkevicius** [comment]
I personally prefer not to have the extra character

**Comment by jpjp** [comment]
Well that's okay, personal preference. But adding the character ensures a behaviour, so it's strange that the character is hidden.

**Comment by AudriusButkevicius** [comment]
I don't think the extra character ensures anything.

Index wise, directories are stored without the slash at the end, which then makes pattern matching easier, as go's built in file iterator returns paths without slashes at the end, etc.

So we are already unsafe just by using the standard library.

**Comment by calmh** [comment]
We do slash "harmonization" of the config at startup.

https://github.com/syncthing/syncthing/blob/master/internal/config/config.go#L270

You can enter `~/yep/////` if you like (and this is fine in Unix); we'll normalize to `~/yep`. As Audrius notes, there is no behavioral aspect of `yep` vs `yep/`, and we need to clean it up to some standard because Windows pathnames are not like the other children...

**Comment by eipiminus1** [comment]
For me this does have a behavioral aspect as my folder path is a symlink.
So I have a symlink `/my/path` -> `/the/real/folder`
This means that `/my/path/` works fine right after adding it but after restarting syncthing it gets "harmonized" to `/my/path` which is not a directory and it stops syncing.

I tried to enable `followSymlinks` as described in http://docs.syncthing.net/draft/followsymlinks.html but this does not seem to affect the top folder path.

I think it would be useful to allow trailing slashes at least with the `followSymlinks` option enabled.

**Comment by AudriusButkevicius** [comment]
Given it's a root symlink, why can't you just point it at the right path?

**Comment by calmh** [comment]
We could also ensure that the slash harmonification ensures and ending slash. That ought to be fine for all platforms.

**Comment by eipiminus1** [comment]
@AudriusButkevicius I occasionally move data from one place to another and don't want to worry about all the configs and preferences to be updated. Thats why I use symlinks a lot. But pointing it to the base directory is what I currently use as a workaround.

@calmh I have no expertise about how microsoft systems behave about trailing slashes but I would love to see such a change! I don't have any experience in writing go but would try my best to help testing.

btw: amazing response times ;)

**Comment by calmh** [comment]
Essentially this:

```diff
diff --git a/lib/config/config.go b/lib/config/config.go
index bd19c32..cee6056 100644
--- a/lib/config/config.go
+++ b/lib/config/config.go
@@ -360,7 +360,7 @@ func (cfg *Configuration) prepare(myID protocol.DeviceID) {
                // C:\somedir\ ->  C:\somedir\\   ->  C:\somedir
                // This way in the tests, we get away without OS specific separators
                // in the test configs.
-               folder.RawPath = filepath.Dir(folder.RawPath + string(filepath.Separator))
+               folder.RawPath = filepath.Dir(folder.RawPath+string(filepath.Separator)) + string(filepath.Separator)
 
                if folder.ID == "" {
                        folder.ID = "default"
```

That looks kind of nonsensical, adding and stripping and adding the slash, but it does ensure the end result regardless of the input I think.

**Comment by eipiminus1** [comment]
That solves it for me! Would love to see it in the next release. Thanks for helping and keep up the good work.

**Comment by calmh** [comment]
Main thing is tests need fixing. Probably sufficient to just `filepath.FromSlash("foo/")` everywhere we would test for just "foo".

**Comment by eipiminus1** [comment]
Something like this?
https://github.com/eipiminus1/syncthing/commit/fe97b4f8c36180fc96a62bb5ccaa956c6d6b5140

`./build.sh test` looks good to me.

**Comment by AudriusButkevicius** [comment]
Make a PR please

**Comment by eject-it** [comment]
If   <followSymlinks>true</followSymlinks> is set in the config.xml  it will be removed if the config of that folder is saved at a later point using the gui including Message asking for restart. Which is how I noticed. I did press save to exit but I didn't change anything so there wasn't a reason to restart.

**Comment by AudriusButkevicius** [comment]
Sorry, what does this have to do with this issue? If it says it needs a restart, it means something has changed
