### ISSUE TITLE
Ignored files means puller can't remove deleted directory

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#1362]
Syncthing v0.10.23

1. On Node1, Create Folder/IgnoredFile and Folder/UnignoredFile
2. Add IgnoredFile to .stignores
3. Let Syncthing sync Folder/Unignored file to Node2
4. Remove Folder (and Folder/UnignoredFile) from Node2
5. Watch as Node1 deletes Folder/UnignoredFile, but not Folder/IgnoredFile. It subsequently can't delete Folder, failing with `[UAL5T] 21:34:40 INFO: Puller (folder "Whatever", dir "Folder"): delete: remove C:\Whatever\Folder: The directory is not empty.`

**Comment by AudriusButkevicius** [comment]
What would you expect the correct behaviour to be?

**Comment by canton7** [comment]
Not a spew of errors in the console and the puller being paused, that's for sure! (I encountered this while trying to delete quite a large tree, with lots of ignored .git dirs). I think graceful detection of the situation so as not to trigger slightly unclear errors, and not pause the puller, is the most important thing. After that, a message saying "we tried to delete this folder but there was an ignored file/folder in it so we couldn't. Please remove it yourself" in the gui would be nice, and adding a button to delete the folder anyway would be ideal (although a fair bit more work I'm sure). Thanks!

**Comment by canton7** [comment]
It's probably also worth mentioning that if you have `A/B/C/D/E/IgnoredFile`, then Syncthing will try and fail to delete `A/B/C/D/E`, then try and fail to delete `A/B/C/D`, and so on. So if the ignored file is a few directories deep, the errors quickly add up.

**Comment by AudriusButkevicius** [comment]
Yeah this whole ignore stuff should get replaced with selective sync, which will then give you better control and mitigate these sort of issues.

**Comment by canton7** [comment]
Ah ok, so this is wontfix until selective sync comes in? Fair enough. Do you have a rough timescale for that?

**Comment by calmh** [comment]
This is an old, known (by me at least) issue and I was sure there was already a ticket for it. I can't find one though, so letting this one live. :)

**Comment by canton7** [comment]
Yeah, I had a good search around and couldn't find another mention of this specific issue anywhere.

The large number of culmutative errors (especially if the ignored file is buried deep in a directory hierarchy) does mean that the puller keeps being stopped, and it looks to the casual eye that everything's fallen apart (rather than it being an easily resolvable problem).

**Comment by basilweibel** [comment]
I am having the same problem.

**Comment by lpoujol** [comment]
I have a similar problem when I ignore a directory. No files are syncronized but empty an directory are created on the other node. :(

**Comment by AudriusButkevicius** [comment]
To ignore a directory (and not it's content), make sure that the pattern does not end with a `/`, as `/` assumes the content, not just the directory itself.
