### ISSUE TITLE
Some special characters in ignore patterns should be escaped.

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#1365]
Specifically, `^` and `$` are just regular characters as far as glob matching is concerned.

**Comment by AudriusButkevicius** [comment]
`()|` are equally special.

**Comment by calmh** [comment]
Grargh. `[]` are actually valid for ranges in glob patterns as well, and we have tests for that, so that's fine. Parenthesis is true though.

**Comment by jpjp** [comment]
Does ^ match the file in the path, or the entire path?

**Comment by AudriusButkevicius** [comment]
^ is an anchor which I think is now escaped hence a simple character
