### ISSUE TITLE
v0.10.23 release for solaris missing

### ISSUE THREAD

**Issue by reco** [syncthing/syncthing#1368]
hi there, 
 are there any plans to release a version for solaris(omniOs)?

thanks

**Comment by calmh** [comment]
Erm. I'd missed that it wasn't. I'll look into it!

**Comment by reco** [comment]
hi calmh cool thanks

**Comment by calmh** [comment]
I'm uploading a release now, to the regular release page for v0.10.23. It won't be in the signed md5/sha1 files though. I'll double check on next release that it's included - my best guess is a timing issue, that build is built by a separate box, and it may not have been done when I did the upload. Sorry.
