### ISSUE TITLE
Doesn't sync at all

### ISSUE THREAD

**Issue by zilti** [syncthing/syncthing#1369]
I have a Windows PC with Syncthing v0.10.23 and a FreeBSD Server with v0.10.22 and syncthing-cli. That same server syncs fine with my Android phone with v0.10.21 and with my Linux laptop with the latest version, but none of these sync with the Windows PC. The Windows Syncthing claims everything is "up to date", but nothing is synced and the folder is empty.

**Comment by dzarda** [comment]
You'll have to include the command line Syncthing output, I'm afraid.

**Comment by zilti** [comment]
Well, it turns out that after a random amount of syncthing restarts on all devices it somehow fell back into place...
