### ISSUE TITLE
Full re-sync folder after rotation files

### ISSUE THREAD

**Issue by QVirus** [syncthing/syncthing#1371]
I have backup script like this:
```
#!/bin/bash
BP="/home/syncthing/Sync/test"
LEVEL=30
rm -f $BP/$LEVEL.dmp
while : ; do
  if [ $LEVEL = "1" ] ; then
    break
  fi
  mv $BP/$((LEVEL-1)).dmp $BP/$LEVEL.dmp 2>/dev/null
  LEVEL=$((LEVEL-1))
done

dd if=/dev/urandom of=$BP/1.dmp bs=1M count=50
```

Expectation:
* (Pre?)Remove the file 30.dmp
* Files 1-29.dmp rename/move to 2-30.dmp
* Sync 1.dmp
* (Finally remove 30.dmp?)

What happens:
* Sync 1.dmp
* Part of the file 2.dmp taken from the old file 1.dmp, until synchronized the last block of the file 1.dmp
* Synchronize other files by the same principle

In the final we have the traffic is almost the same as with the full folder sync.

**Comment by AudriusButkevicius** [comment]
I don't see a way to solve this.
We have to choose either ascending or descending order, and whichever way we go, there will always be someone unhappy.

Revert your script to do stuff in reverse order, and you'll be fine.

**Comment by AudriusButkevicius** [comment]
Actually, soon we will have randomized order, which will be non-deterministic all together.

**Comment by calmh** [comment]
Mmmyeah. We handle renames, and "partial renames" (i.e. what happens here, rename + some modification), but only up to a certain point. To handle this correctly we would basically need to keep a complete clone of the entire repository until the sync is done, which would be too expensive disk space wise.

**Comment by jpjp** [comment]
@QVirus switch the rotation to use dates, then you only get one duplicate and everything just works. Backups too.

**Comment by QVirus** [comment]
Thanks guys!
I change my script like this:
```
#!/bin/bash
BP="/home/syncthing/Sync/test"
DATE=`date +"%Y-%m-%d:%H:%M:%S"`
LEVEL=30
rm -f $BP/*-$LEVEL.dmp
while : ; do
  if [ $LEVEL = "1" ] ; then
    break
  fi
  SNAME=`ls -1 $BP/*-$((LEVEL-1)).dmp 2>/dev/null`
  SNAME=${SNAME##*/}
  mv $BP/$SNAME $BP/${SNAME%-$((LEVEL-1)).dmp}-$LEVEL.dmp 2>/dev/null
  LEVEL=$((LEVEL-1))
done

dd if=/dev/urandom of=$BP/$DATE-1.dmp bs=1M count=50
```

**Comment by jpjp** [comment]
Great! (You can also use logrotate and the dateext option).
