### ISSUE TITLE
Disable compression by default

### ISSUE THREAD

**Issue by revogit** [syncthing/syncthing#1374]
I know compression sounds always good, but after a few experiments (not with syncthing, used another syncing solution for this) you should really consider to turn it off by default.

Compression is only effective on uncompressed files (like textfiles, who are, most of the time, only a few kB in size).

In every other case (for music, videos or pictures who are usually bigger in size than textfiles), compression only adds more overhead, uses up cpu-time, but does not effective reduce the files size.

Also, with compression enabled, syncing can (due to the additional time it requires to compress the files) even take longer than without.

So please, consider to disable compression by default.

Edit: Did a short test: With compression (200MB data containing a few pictures (jpg), a few textfiles and a few videos (webm)) the sync lasted 220 seconds, without compression (same data) the sync only needed 165 seconds (I know this is not representative, results might vary depending on hardware, network interface, etc.).

**Comment by calmh** [comment]
The figures on my computer, with 2.0 GB of gzip compressed data (i.e. not at all compressible) is 57 seconds with compression enabled, 51 seconds with compression disabled. So yes, it's something of a loss in that case but not as drastic as in the report - probably depends on the relative speeds of CPU vs network/disk etc.

One thing we could do though is default to compression off (for file data) but always do compression for metadata messages, mainly the index data which is compressible and may be large...

**Comment by dzarda** [comment]
:trophy:

**Comment by revogit** [comment]
@calmh wrote:
> So yes, it's something of a loss in that case but not as drastic as in the report - probably depends on the relative speeds of CPU vs network/disk etc.

Of course it depends on your hardware, network interface, etc :)

Another point is, with compression enabled syncthing consumes more cpu-time. On workstations this shouldn't be a problem, but on mobile devices (smartphones, netbooks/notebooks, tablets) this is a problem (more cpu-time → higher battery usage → probably less uptime).

> One thing we could do though is default to compression off (for file data) but always do compression for metadata messages, mainly the index data which is compressible and may be large...

Sounds like a good idea, +1

**Comment by bherila** [comment]
I think there are pros and cons to enabling or disabling compression by default. One idea which I think would be objectively better would be to define a list of file types that should "always" or "never" be compressed. For example, JPG, MP4, MP3, etc. is almost never worth compressing, right? TXT is probably almost always worth compressing.

**Comment by revogit** [comment]
I'm not sure how you could implement that in an easy way. If you define your filetype using the extension (like .jpg), it's a bad design because it can fail. The „right“ way to create a file type based compression would be to look into the files header (first few bytes) and then decide, if it should be compressed or not. Of course it still needs a global setting for file types it doesn't know.

And don't forget, that txt-files are usually just a few kB in size, so the benefit (on average) is minimal (well, except you've got gigabytes of logfiles).

A compromise could be, that Syncthing only checks if it's a textfile or a binary file and enables compression if it's a textfile and disables it in every other case (But an extra setting would still be necessary: disable compression, enable compression and auto compression)

I know the Block Exchange Protocol handles the compression of messages through a one bit flag, does anybody know if this is also the case for the user data? If yes, this could be a problem.

**Comment by AudriusButkevicius** [comment]
Well each packet has a flag, so you can decide which messages you compress, and which you don't.
If its a protocol message and not a data response, compress always, etc...

**Comment by calmh** [comment]
Note that the LZ4 compression is fairly smart. It does an attempt on the first few KB, and if that doesn't seem to result in any gains it skips compression on the rest of the message.

Either way, I started working on compressing just metadata but it was more than half an hours work so I'll get back to it (mostly in terms of handling the config format changes and the UI).

**Comment by generalmanager** [comment]
@calmh: Only compressing the metadata and index by default seems like the smart way to do this. I've setup ST for over 30 people and 98% of the data were basically uncompressable images, pictures and videos. 
And people who have such significant amounts of textfiles, that it matters are usually coders (source code) or sysadmins (logs) and they will intuitively try to enable compression.

**Comment by TontonSancho** [comment]
Better to add an additional "[  ] Smart compression auto-switch" checkbox that priorly dumbly checks mimetype before transfers ? ... adding at the same time a config list of mimetypes we want to automaticaly compression disabled.

**Comment by endolith** [comment]
@KopfKrieg

> If you define your filetype using the extension (like .jpg), it's a bad design because it can fail. The „right“ way to create a file type based compression would be to look into the files header (first few bytes) and then decide,

Theoretically, sure, if someone names the file wrong, but so what?  Compressing based on file extensions would work well 99% of the time, and in the corner cases it would just take a little longer.

**Comment by calmh** [comment]
Please don't revive several years old closed issues for discussion
