### ISSUE TITLE
CPU Utilization doesn't match value on Task Manager

### ISSUE THREAD

**Issue by robsonsobral** [syncthing/syncthing#1376]
Hi!

I had a huge repository scanning yesterday and I took a look at the task manager. The value GUI showed was approximately 4× the value on Windows task manager.

I'm running v0.10.22 on Windows8.1.

Thanks!

**Comment by kozec** [comment]
Just an idea, as there may be better reason for this, but do you have 4 core CPU by any chance?

**Comment by robsonsobral** [comment]
Yeap! Quad core!

I had the same idea, but I thought you could laugh at me for suggesting that.

**Comment by kozec** [comment]
Why? It's pretty common to sum usage on all cores if only one number is to be displayed.

**Comment by robsonsobral** [comment]
I know nothing about that. On Syncthing, I'm just an user. I thought it's a too obvious situations to pass unnoticed until now. Designers don't know too much about this kind of development.

Is it possible to fix it? Is a Windows only issue?

**Comment by AudriusButkevicius** [comment]
To fix what? The standard way a lot of utilities display cpu usage?

**Comment by kozec** [comment]
> To fix what? The standard way a lot of utilities display cpu usage?

I _think_ that I understand where issue is and it's probably really Windows-only problem :D

Windows task manager doesn't display CPU usage as rest of world does. It sums usage by all threads, as one may expect, but it also sums available CPU time for all cores. So for 4-core CPU, displayed percentage is based on 4 times of actual CPU power and thus 4 times lower than Syncthing displays (or `top` would display)

Now, both approaches have their own logic and showing different values as standard system utility may be confusing for user, but I'm not sure how much of Syncthing bug this is.

**Comment by robsonsobral** [comment]
Yeap, @kozec! That's my point.

Windows reports CPU usage as percentage of total system capacity. I think Syncthing should respect the operational system standard.

**Comment by AudriusButkevicius** [comment]
Well I think it should not.
Syncthing is cross platform, hence we should use one standard and stick to it.
Given Windows is a minority (https://data.syncthing.net/), the current standard wins.

**Comment by robsonsobral** [comment]
The fact that Windows is minority can be an argument to a lot of things. Even to contradict your point. So, I gonna focus on the other point.

A lot of apps are cross platform and this doesn't mean they should behave exactly the same on all of them, but to respect the related user expectation on all of them. For example, on an OS, you can expect the repository scan to work in a way; on other SO the same scan can work in a different way. If the user feels it's the right way, ok! All users get the better experience possible.

To me, looks nonsense to have apps on Windows that I should look at as if they was running on Linux.

Using an analogy of my own professional area: make the website to respect the browser being used instead of try to simulate the behavior of most used one. I think you could think more on a "progressive enhancement / graceful degradation" way.

But... You're the boss. It's your call.

Thanks for hear me!

**Comment by AudriusButkevicius** [comment]
I mean even the windows syscalls returns sum of number of nano seconds spent on each core, which usually more than 100% of real time terms, so I guess this 100% thing is just a Windows legacy going since 1995.

Currently the task manager shows you % per core, which when added up will be more than 100%, so I don't see how they look like if they are running on Linux?

**Comment by robsonsobral** [comment]
I don't think Windows show "% per core" as I never ever saw more than 100% of CPU being used. Task manager shows % per all cores.

Anyway, if Syncthing don't match the way the OS reports the CPU usage, from an user non-tech, non-nerd, non-developer point of view, it looks confusing.

**Comment by AudriusButkevicius** [comment]
I've checked Windows 8, and you are right that they are back to their bad deed of grouping cores together. You have to select to view it separated:

http://snag.gy/ZhnYv.jpg

In Windows 7 it was separate by default as far as I remember.

Your argument does make sense and it's literally a single line to implement, but I personally rather not have any deviation in behaviour between OS'es, and have this perhaps awkward behaviour across the board.

I wonder what others think.

**Comment by robsonsobral** [comment]
I gonna check on a Windows virtual machine.

**Comment by robsonsobral** [comment]
If a virtual machine provides a valid data for this...

The _process_ tab:

![windwos_7-task_manager-processes_tab](https://cloud.githubusercontent.com/assets/931642/6361671/44765e18-bc63-11e4-9293-2adde0ac7d03.PNG)

And the _performance_ tab:

![windwos_7-task_manager-performance_tab](https://cloud.githubusercontent.com/assets/931642/6361674/4bea66e4-bc63-11e4-8308-86bdd51f6531.PNG)

On Windows 8, the _process_ tab always shows the overall usage. The _performance_ tab, as you pointed, has to be set to show "Logical processors".

I agree that to deal with exceptions is annoying. Before the advent of graceful degradation, my life was full of exceptions all the time. But I believe that we all work for the user.

Which is the big boss opinion? Or you can ask on the forum for everybody.

**Comment by AudriusButkevicius** [comment]
Yeah, I am open to a poll ;) We gotta please the crowd

**Comment by jkaberg** [comment]
Well beeing from both camps I clearly see @robsonsobral point

Would it be to much to devide the current % by x cpu cores (on host) if it's a Windows platform?

Psuedo code:

>cpu_cores = 4 
>cpu_usage = 100 # in %
>if sys.platform('windows'):
>    cpu_usage = cpu_usage / 4

Just a tought :-)

**Comment by calmh** [comment]
There are two different ways to present CPU usages. One uses total system capacity as 100%, the other uses one processor (core) as 100%. Both are valid. The second variant is actually slightly easier to calculate. Either way this is not an issue.

*MAYBE* it would be worth changing this, just to the number looks smaller and people are happier about it using less resources and filing less bugs about it...
