### ISSUE TITLE
Do you have an XSD describing the config.xml file ?

### ISSUE THREAD

**Issue by StefH** [syncthing/syncthing#1377]
I wonder if you have and XSD or a document which describes the **config.xml** file.

**Comment by calmh** [comment]
No, sorry. I'd welcome one though.

**Comment by StefH** [comment]
See this link for example:

https://github.com/StefH/SyncthingTray/blob/75793fbd82b16916910b06a2e5248a20329677ef/SyncthingTray/External/SyncThingConfig.xsd
