### ISSUE TITLE
Very slow sync with small files

### ISSUE THREAD

**Issue by Theobald93** [syncthing/syncthing#1379]
Hey!
I often sync a lot of small files (pictures with 100kB-5MB each) with In-Home-WLAN (150MBit/s 5Ghz 100% Quality) but the speed is really really bad. ~300-500KiB/s
Today I sync >2200 pictures with >1,5GB and it takes 1 hours to sync it!
Compression on/off does not help.

Why does not syncthing pack the files in ~3-30 MB Buffer Container, it would be much faster i think. Large files are much much faster to sync.

**Comment by AudriusButkevicius** [comment]
You can try and increase the number of pullers in the config, as by default we download a single file at a time. Also having the UI open while downloading might have an effect.

**Comment by Theobald93** [comment]
Thanks, the speed is now higher!
