### ISSUE TITLE
Syncthing crashes when I close the laptop lid

### ISSUE THREAD

**Issue by jkaberg** [syncthing/syncthing#1382]
As per title, crashes whenever I close the lid (does Syncthing tackle sleep mode?)

Windows 8.1 x64

**Comment by AudriusButkevicius** [comment]
How do you know it crashes? Crashes with what error?

**Comment by jkaberg** [comment]
Well I should rephrase - it exit's, not sure on what error

Looking over the config directory I see a few log files, which one you need?

**Comment by AudriusButkevicius** [comment]
How are you starting syncthing to start with? It usually logs to stdout, hence if it were to crash it would print output there. The fact that you don't have access to console log implies to me that some script/tool that you are using is not doing a proper job.

**Comment by AudriusButkevicius** [comment]
The logs you pointed out are database logs, hence of no use.

**Comment by jkaberg** [comment]
You were right, after some further research I found that this is not related to Syncthing

Thanks for your help
