### ISSUE TITLE
discourse.syncthing.net is innaccesible via IPv6

### ISSUE THREAD

**Issue by hobarrera** [syncthing/syncthing#1384]
```
$ dig +short AAAA discourse.syncthing.net
2001:470:28:4d6::10
$  curl '[2001:470:28:4d6::10]'
curl: (7) Failed to connect to 2001:470:28:4d6::10 port 80: No route to host
```

Or just:
```
curl discourse.syncthing.net
curl: (7) Failed to connect to discourse.syncthing.net port 80: No route to host
```
(you'll want to add `-6` there if you're dual-stacked).

I've confirmed this from my home connection (Argentina), a VPS in California and another in London. The result is always the same.

This is a pretty bit PITA, since I get the email digests occasionally, but I can't just fire up a browser and visit the links (or even unsubscribe!!). I need to run some special IPv4 proxy via a remote VPS (which, honestly, is non-trivial).

The solution is to either:
* Make sure the server at discourse.syncthing.net is listening to all protocols and on the proper interfaces.
* Delete the AAAA record for discourse.syncthing.net.

Dual-stacked hosts that prefer IPv4 should not be affected (unconfirmed). I'm not sure what happens with Dual-stack hosts that prefer IPv6.

**Comment by calmh** [comment]
Fixed, thanks.

**Comment by hobarrera** [comment]
That was fast. Thanks.
