### ISSUE TITLE
Folder "XYZ" isn't making any progress ...

### ISSUE THREAD

**Issue by heinzK1X** [syncthing/syncthing#1386]
Hi there, 
this is a BUG REPORT, I'm using v0.10.23 on OSX Yosemite and v0.10.23 via the app on Cyanogenmod.

I'm syncing files from OSX to the phone. As the phone kept flashing a warning message with "Folder 'XYZ' isn't making any progress." "... pausing puller for a minute (or something like that)" after restarting syncthing / deleting and reinitializing the repository several times, I started looking if specific files were not transferred.

As it turns out, files cannot be transferred if they have a slash, "/", in their name. I tested it with a number of different files in number of different folders and this is reproducibly the cause. 

I had the same issue as well on files not containing a slash. Strangely it was possible to upload such a file to one directory, but not to another. Since I couldn't really pinpoint the problem I have a FEATURE REQUEST: In the given warning message, "Folder 'XYZ' isn't making any progress. ...", please add the name and path of the files that the puller is/was working on. This way one can at least do something with the files that are causing the issue.

**Comment by lewisl9029** [comment]
I'm seeing this issue too, but with this particular torrent file:
https://www.tokyotosho.info/details.php?id=863752

It doesn't have any "/" in its filename, so maybe something else is causing it in my case.

Log output for the error is here: 
```
[GKNHD] 19:21:05 INFO: Puller (folder "Torrents", file "Music\\%5B%EC%96%BC%ED%8
B%B0%EB%A9%94%EC%9D%B4%ED%8A%B8%5D_%5B150218%5D_TV%E3%82%A2%E3%83%8B%E3%83%A1%E3
%80%8C%E3%82%A2%E3%82%AB%E3%83%A1%E3%81%8C%E6%96%AC%E3%82%8B%EF%BC%81%E3%80%8D%E
3%82%AA%E3%83%AA%E3%82%B8%E3%83%8A%E3%83%.torrent"): dst create: open L:\Torrent
s\Music\~syncthing~.%5B%EC%96%BC%ED%8B%B0%EB%A9%94%EC%9D%B4%ED%8A%B8%5D_%5B15021
8%5D_TV%E3%82%A2%E3%83%8B%E3%83%A1%E3%80%8C%E3%82%A2%E3%82%AB%E3%83%A1%E3%81%8C%
E6%96%AC%E3%82%8B%EF%BC%81%E3%80%8D%E3%82%AA%E3%83%AA%E3%82%B8%E3%83%8A%E3%83%.t
orrent.tmp: The system cannot find the path specified.
[GKNHD] 19:21:05 WARNING: Folder "Torrents" isn't making progress - check logs f
or possible root cause. Pausing puller for 1m0s.
```

**Comment by AudriusButkevicius** [comment]
@lewisl9029 you filename is just too long.
See https://github.com/syncthing/syncthing/issues/1278 the part about adding `\\?\` as a prefix of your folder.

**Comment by Jonny007-MKD** [comment]
Hi,
this is my Puller message:
    [QXVFC] 13:36:05 INFO: Puller (folder "DDF", file ".sync\\Archive\\125B Feuermon
d - Der Pfad der Täuschung\\24 - Der Pfad der Täuschung - Baupläne.mp3"): dst st
at dir: GetFileAttributesEx M:\Musik\Die drei Fragezeichen\.sync\Archive\125B Fe
uermond - Der Pfad der Täuschung: Das System kann den angegebenen Pfad nicht fin
den.
I delete .sync so naturally it won't find any subfolder, but Syncthing doesn't remove these files from the index

**Comment by AudriusButkevicius** [comment]
Probably because it hasn't yet rescanned, or you deleted the folder while it was syncing.

**Comment by Jonny007-MKD** [comment]
I suppose the latter :) Do I have to readd it?

**Comment by AudriusButkevicius** [comment]
A rescan might not be enough, but it could be case that this is not handled very well, and you might have to stop syncthing, remove the index directory from the config directory and restart it, so that it rebuilds the index.

**Comment by Jonny007-MKD** [comment]
Removing the index did work :+1:

**Comment by AudriusButkevicius** [comment]
Are you using inotify?

**Comment by heinzK1X** [comment]
Addendum: Filenames with question marks, "?", also make trouble.

**Comment by hobocta** [comment]
I have this warning too.

![screenshot_2015-03-11-20-35-57](https://cloud.githubusercontent.com/assets/711103/6602741/aa854a76-c82e-11e4-90dc-51197fe5381f.jpg)

**Comment by Allezxandre** [comment]
Hi, I had this issue too. 

It turns out, I am excluding `.DS_Store` from syncs. Deleting a folder from a non-Mac OS computer, everything inside that folder gets deleted during sync. However, on my Mac, `.DS_Store` wasn't deleted, because it was excluded from syncs, so while trying to propagate the deletion of a folder, the Mac returned `WARNING: Folder "$FOLDER" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s` because, as the logs state, "`directory not empty`" (it still contained `.DS_Store` and other OS-specific files).

**Comment by Zillode** [comment]
@Allezxandre this would be https://github.com/syncthing/syncthing/issues/1631

**Comment by Zillode** [comment]
I guess this is now a dup of https://github.com/syncthing/syncthing/issues/1437. Adding path information to this message should fix the problem.

**Comment by Allezxandre** [comment]
@Zillode You're right!
