### ISSUE TITLE
WARNING: multicast interfaces: netlink rib: invalid argument

### ISSUE THREAD

**Issue by niklas88** [syncthing/syncthing#1388]
I'm getting the warning in the title, no idea what it means. I'm behing a UPnP router with a configured IPv6 tunnel. A syncing device is on the same LAN and shows an IPv6 address at:

     [fe80::20c:f6ff:feff:ed05%eth1]:53254-[fe80::ba27:ebff:fe0c:560b%eth1]:22000

syncing seems to be working normally though. Also note I'm using a USB gigabit Ethernet adapter though the laptop also has Wifi and Ethernet (that port is physically flimsy)

**Comment by AudriusButkevicius** [comment]
Can you provide more context to see where this is coming from?

**Comment by niklas88** [comment]
I'll try to gather more data, one idea is that it could be a problem of suspending on one network where syncthing can't work (UDP is blocked) and unsuspending on my homenetwork with a local syncthing and fully functional Internet

**Comment by AudriusButkevicius** [comment]
So I think this is not a bug, but rather a configuration issue at your end.
These warnings are removed in the latest release anyway I think.

**Comment by niklas88** [comment]
Ok I'm still getting this this error. I now see it shortly after starting syncthing in my LAN, my laptop has  1 unconnected Ethernet, 1 USB 3.0 Ethernet (that's the one it is supposed to use) and unconnected WiFi. I don't see any errors on the Raspberry Pi that is on the same network and syncs with the laptop. This is my "ip a" output (ipv6 redacted):
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether 00:90:f5:ec:b4:89 brd ff:ff:ff:ff:ff:ff
3: wlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 0c:8b:fd:59:05:ba brd ff:ff:ff:ff:ff:ff
4: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 52:54:00:e0:45:6e brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
5: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel master virbr0 state DOWN group default qlen 500
    link/ether 52:54:00:e0:45:6e brd ff:ff:ff:ff:ff:ff
8: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:0c:f6:ff:ed:05 brd ff:ff:ff:ff:ff:ff
    inet 192.168.178.44/24 brd 192.168.178.255 scope global dynamic eth1
       valid_lft 853888sec preferred_lft 853888sec
    inet6 fd00::20c:xxxx:xxxx:xxxx/64 scope global noprefixroute dynamic 
       valid_lft 6913sec preferred_lft 3313sec
    inet6 2002:b202:xxxx:x:xxx:xxxx:xxxx:xxxx/64 scope global noprefixroute dynamic 
       valid_lft 6732sec preferred_lft 3132sec
    inet6 fe80::20c:f6ff:feff:ed05/64 scope link 
       valid_lft forever preferred_lft forever

```

**Comment by AudriusButkevicius** [comment]
I assume it hasn't gone away with the latest release?
By more context I mean more logs. Ideally also set `STTRACE=beacon` so that it would show the file and line number where the warning is coming from.

**Comment by AudriusButkevicius** [comment]
I think it might be due to the fact that we try to do a multicast over all interfaces, and one of them has no routes or is down?

**Comment by acidicX** [comment]
I'm getting the same on Arch x64, ST 0.11.1
Both on my desktop and laptop, so no hardware issue. Only seems to happen when a device connects.

Might have something to do with having an IPv6 address in LAN that basically does not lead anywhere?

Log with STTRACE=beacon
```
[J2UEK] 2015/04/30 16:49:42.841541 rwfolder.go:268: INFO: Completed initial scan (rw) of folder bla
[J2UEK] 2015/04/30 16:49:43.296788 rwfolder.go:268: INFO: Completed initial scan (rw) of folder bla2
[J2UEK] 2015/04/30 16:50:08.116637 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.25:21025
[J2UEK] 2015/04/30 16:50:11.550045 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp6s0]:21026
[J2UEK] 2015/04/30 16:50:11.550235 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[J2UEK] 2015/04/30 16:50:11.550359 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[J2UEK] 2015/04/30 16:50:11.550416 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.20:21025
[J2UEK] 2015/04/30 16:50:34.816164 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.15:21025
[J2UEK] 2015/04/30 16:50:34.816633 beacon.go:30: DEBUG: recv 56 bytes from [fe80::21a:4bff:fe72:9cd1%enp6s0]:21026
[J2UEK] 2015/04/30 16:50:34.817373 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[J2UEK] 2015/04/30 16:50:34.817482 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[J2UEK] 2015/04/30 16:50:34.817550 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.20:21025
[J2UEK] 2015/04/30 16:50:34.817601 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp6s0]:21026
[J2UEK] 2015/04/30 16:50:34.817850 broadcast.go:68: DEBUG: addresses: [192.168.1.255]
[J2UEK] 2015/04/30 16:50:34.817919 multicast.go:63: DEBUG: sent 56 bytes to [ff32::5222%enp6s0]:21026
[J2UEK] 2015/04/30 16:50:34.817978 broadcast.go:80: DEBUG: sent 56 bytes to 192.168.1.255:21025
[J2UEK] 2015/04/30 16:50:34.818011 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.20:21025
[J2UEK] 2015/04/30 16:50:34.818620 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.25:21025
[J2UEK] 2015/04/30 16:50:34.818869 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.15:21025
[J2UEK] 2015/04/30 16:50:34.819180 beacon.go:30: DEBUG: recv 56 bytes from [fe80::21a:4bff:fe72:9cd1%enp6s0]:21026
[J2UEK] 2015/04/30 16:50:34.819612 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.15:21025
[J2UEK] 2015/04/30 16:50:34.819955 beacon.go:30: DEBUG: recv 56 bytes from [fe80::21a:4bff:fe72:9cd1%enp6s0]:21026
[J2UEK] 2015/04/30 16:50:34.820118 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.15:21025
[J2UEK] 2015/04/30 16:50:34.820184 beacon.go:30: DEBUG: recv 56 bytes from [fe80::21a:4bff:fe72:9cd1%enp6s0]:21026
[J2UEK] 2015/04/30 16:50:35.058206 connections.go:176: INFO: Established secure connection to CLIENTID1 at 192.168.1.20:22000-192.168.1.15:40765
[J2UEK] 2015/04/30 16:50:35.105197 model.go:588: INFO: Device CLIENTID1 client is "syncthing v0.11.1"
[J2UEK] 2015/04/30 16:50:35.105275 model.go:593: INFO: Device CLIENTID1 name is "CLIENT1"
[J2UEK] 2015/04/30 16:50:38.115178 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.25:21025
[J2UEK] 2015/04/30 16:50:41.549791 broadcast.go:50: WARNING: Broadcast: interface addresses: netlink rib: invalid argument
[J2UEK] 2015/04/30 16:51:04.816503 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.15:21025
[J2UEK] 2015/04/30 16:51:04.816896 beacon.go:30: DEBUG: recv 56 bytes from [fe80::21a:4bff:fe72:9cd1%enp6s0]:21026
[[J2UEK] 2015/04/30 16:51:08.114625 beacon.go:30: DEBUG: recv 56 bytes from 192.168.1.25:21025
```

ifconfig:
```
enp6s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.20  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::224:1dff:fe7e:c729  prefixlen 64  scopeid 0x20<link>
```

**Comment by AudriusButkevicius** [comment]
We should silence that line too.

**Comment by calmh** [comment]
Yeah. Perhaps we should also try the `net.InterfaceAddrs()` call in the constructor function, so we can return an error and print the appropriate `No IPv4 discovery` message at startup, since whatever is the root cause is preventing us from sending any discoveries on IPv4... On the other hand, we can still *receive* them, so we're not completely dead in the water...

**Comment by rkfg** [comment]
Happened to me as well and it's indeed a configuration issue. However, I use quite a complicated setup involving network namespaces to run some programs around the VPN so they're not using it (mostly Steam). The issue was that I haven't set up the broadcast address for the veth0 interface inside the namespace. Before:
```
9: veth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 7a:xx:xx:xx:xx:de brd ff:ff:ff:ff:ff:ff
    inet 172.25.10.50/24 scope global veth0
       valid_lft forever preferred_lft forever
```
After:
```
9: veth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 7a:xx:xx:xx:xx:de brd ff:ff:ff:ff:ff:ff
    inet 172.25.10.50/24 brd 172.25.10.255 scope global veth0
       valid_lft forever preferred_lft forever
```
The command I'm using now is ```ip net exec steam ip a a 172.25.10.50/24 b 172.25.10.255 dev veth0```, before the ```b 172.25.10.255``` part was omitted. Now the message is gone and the local discovery works instantly. What confuses me is that after I've added the IPv4 broadcast address both of my devices (Nexus 4 and Nexus 10) connected via local IPv6, before they always connected to the router WAN address. It's like this lack of IPv4 broadcast prevents any broadcasts, even when the local IPv6 is available (and most often it is by default). So there may be a bug buried somewhere.

**Comment by rkfg** [comment]
Hmm, I should be wrong. This started happening again even with broadcast set.

**Comment by Getron** [comment]
I have installed brand new, from 26.05.2015 Fedora 22 x64 KDE 5.3 Spin, and the Linux kernel is 4.0.4-301.

Installed the Syncthing as a service, from here:
https://copr.fedoraproject.org/coprs/tune2fs/syncthing/

or direct:

https://copr-be.cloud.fedoraproject.org/results/tune2fs/syncthing/fedora-22-x86_64/syncthing-0.11.6-1.0.fc22/

And the line still apear, every few seconds.

Don't known what this mean, or what the problem is, but, you can reproduce it, if you try this steps.

The problem still on both, 0.11.6-fc21 and 0.11.6-1.0fc22

**Comment by Getron** [comment]
P.S.:

I found somthing, if i add the devices on both sides, then, the folders are working, shares would founded (shared folders), but, if i do not manually add the devices, nothing happend.

I think, this is somthing wrong with founding devices...

**Comment by RyuzakiKK** [comment]
Same here, only if I set the local ip manually they discover each other.

I'm using Arch Linux.

**Comment by Getron** [comment]
One more thing i discovered:

This message apear to, if there is no devices, or existed devices i manualy delete, and no devices there, like on first start, then the message apear after couple of seconds.

Do someone can fix this problem?

**Comment by AudriusButkevicius** [comment]
It's just a harmless warning, not sure why people are freaking out about it so much.

**Comment by acidicX** [comment]
"harmless warnings" are still very annoying if they pop up every few minutes as a desktop notification (which they will if you use ST-GTK). I don't see anyone "freaking out" in this issue thread, though.

**Comment by Getron** [comment]
Yes, it is very annoying. Please, disable it, if it is not important.

And, what about "not" discovery problem? Devices are on the same lan, and are not able to discover each other, until add one of them manualy.

I have Syncthing installed as plugin on my FreeNAS, and my Fedora Linux 22 KDE on my PC. Both are x64 Systems.

**Comment by Zillode** [comment]
Has been fixed 2h ago, will be part of the next release.

**Comment by AudriusButkevicius** [comment]
You have to always add devices manually, it's just a step in the process, we don't autoaccept devices.

**Comment by Getron** [comment]
No, i don't mean autoaccept, but, for example, i add manualy my PC ID device on my NAS syncthing, and, the PC should ask me, that the NAS device has added it to list, do i want to add the NAS on PC.

But, this not happend. I should add both of devices manualy, on both sides to work.

**Comment by AudriusButkevicius** [comment]
Well that only happens if the other side manages to establish a connection, which might not always be the case if you are behind a NAT.

**Comment by jhonatanpiffer** [comment]
This example worked for me and help me understand how this work.

https://github.com/bjornl/ipv6_multicast_example
