### ISSUE TITLE
Syncthing upgrade restarts monitor process

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#1390]
This relates to #682.

I'm writing a windows utility which hosts syncthing.exe (and act as a REST client). It's therefore responsible for starting and stopping syncthing.exe, and keeps track of whether syncthing.exe is running.

In general all's well and good, apart from when Syncthing upgrades itself. In this event, the monitor process restarts. However this means that my utility sees it exit with a 'success' exit code, and any attempts to start a new process are thwarted by the fact that the now-restarted syncthing.exe has locked the database. Essentially syncthing.exe escapes the process tree it was previously in, and re-established itself outside of the context of my utility.

An ideal solution for me would be a command-line flag which stops Syncthing from automatically restarting. An event could then indicate that an automatic upgrade was complete, and I could manually restart it.

A less ideal solution would be a non-zero exit code when the monitor process restarts, so I can at least inform the user that they should kill all running syncthing.exe processes before attempting to use my utility again.

Thanks

**Comment by Zillode** [comment]
are you aware of "[STNORESTART](https://github.com/syncthing/syncthing/blob/0828a67145377c635e08bb6b54a887587835f9db/cmd/syncthing/main.go#L193)"?
Then exit code 4 [exitUpgrading](https://github.com/syncthing/syncthing/blob/0828a67145377c635e08bb6b54a887587835f9db/cmd/syncthing/main.go#L72) should inform that it exited for an upgrade

**Comment by canton7** [comment]
I was not aware, thanks! Is there any indication available anywhere that Syncthing has upgraded and would like to be restarted? I'm aware of `/rest/upgrade`, but I don't think it provides this piece of information.

The monitor process definitely exits with exit code 0, at least in v0.10.22.

**Comment by Zillode** [comment]
There is no such API at the moment, but the the exit code works for me:
```
user@mb5-btrfs:~/tmp/syncthing-linux-amd64-v0.10.22$ STNORESTART=1 ./syncthing
...
[RHKHL] 20:12:04 WARNING: Automatically upgraded to version "v0.10.23". Restarting in 1 minute.
[RHKHL] 20:13:04 OK: Exiting
user@mb5-btrfs:~/tmp/syncthing-linux-amd64-v0.10.22$ echo $?
4
```

**Comment by canton7** [comment]
Interesting. Think I need to do some more tests, thanks. Maybe I misunderstood the point of STNORESTART - why did syncthing exit if STNORESTART was set?

**Comment by canton7** [comment]
Aha, STNORESTART=1 makes all the difference. I was seeing this:

```
$ ./syncthing.exe
[UAL5T] 19:26:13 WARNING: Automatically upgraded to version "v0.10.23".
ng in 1 minute.
[UAL5T] 19:26:14 INFO: Completed initial scan (rw) of folder Music
[UAL5T] 19:26:18 INFO: Completed initial scan (rw) of folder Docs
[UAL5T] 19:26:27 INFO: Completed initial scan (rw) of folder Pictures
[UAL5T] 19:27:13 OK: Exiting
[monitor] 19:27:13 INFO: Restarting monitor...

$ echo $?
0
```

**Comment by AudriusButkevicius** [comment]
Yes, your manager process should replace the functionality the monitor provides, and all should be well.

Reopen if I am misunderstanding something.

**Comment by canton7** [comment]
Fantastic, thanks a lot for your help.
