### ISSUE TITLE
One file in folder not syncing, other files are

### ISSUE THREAD

**Issue by kurtschelfthout** [syncthing/syncthing#1393]
I have a folder on my Windows laptop with four files in it. I then set up the same folder on my Linux ARMv5 NAS. Both are using the latest version of SyncThing. Both are on the same network, they connect fine. Three files of the folder on my laptop are synched fine. But the fourth file does not sync and the log says:

[LLVJN] 21:26:40 INFO: Puller (folder "default", file "Documents"): pull: no available source device
[LLVJN] 21:26:41 WARNING: Folder "default" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.
[LLVJN] 21:27:54 INFO: Puller (folder "default", file "Documents"): pull: no available source device

There doesn't seem to be anything special about the Documents file; it's an encrypted 100Mb file. I tried deleting the folder on the NAS a couple of times and starting it again, same thing every time with the same file.

**Comment by AudriusButkevicius** [comment]
Are you actually connected to the device which has that file?
Have you tried restarting syncthing?

**Comment by kurtschelfthout** [comment]
Yes, it's connected. It syncs three other files. I've restarted both instances of syncthing muliple times.

**Comment by AudriusButkevicius** [comment]
What does the UI say? Can we have some screenshots?

**Comment by kurtschelfthout** [comment]
This is the UI of the NAS, where sync hangs on the one file:

![image](https://cloud.githubusercontent.com/assets/164917/6458307/0c90cd0a-c17a-11e4-9c64-9dc6f8b4971c.png)

This is the UI of the laptop (where it's trying to copy the file from)

![image](https://cloud.githubusercontent.com/assets/164917/6458332/4e8d8928-c17a-11e4-8a5d-3242343cc177.png)

**Comment by AudriusButkevicius** [comment]
If you click onthe out of sync link, is there any progress being made? Is the file really available on the other device?

**Comment by kurtschelfthout** [comment]
Yes, the file is really there on the laptop. If it definitely doing _something_ as you can tell from the upload and download rates (everything else is up to date). But it stays stuck at 2 or 3%, and no file appears on the NAS.

**Comment by kurtschelfthout** [comment]
Problem solved. Syncthing on the NAS was connecting via the VPN. This probably caused it to connect back from the vpn's exit point back to my laptop, causing all sorts of bad connection problems. Once the NAS was just connecting via my LAN the file sync'ed straight away.

Thanks for your help, and sorry for the confusion.
