### ISSUE TITLE
Connection error in the GUI every 30 secs

### ISSUE THREAD

**Issue by elijahpaul** [syncthing/syncthing#1394]
I'm getting the connection error pop-up (and disappear) every 30 secs in the GUI. Can't figure out what could be causing it. It doesn't seem to affect any functionality, just annoying.

![syncthing_error](https://cloud.githubusercontent.com/assets/478088/6455319/8bbf8434-c14a-11e4-85d7-f58be784940f.png)

I do have the GUI running on port 8081 as opposed to 8080.

**Comment by AudriusButkevicius** [comment]
Is there anything in the console? Perhaps you are running via some proxy? Is rescan interval 30 seconds? What response do the requests get in the browaer debug tools (as this popup happens due to non 200 reponse code)?

**Comment by elijahpaul** [comment]
Rescan is 0, I'm using syncthing-inotify. The GUI is behind HAProxy (how can it cause this behaviour?). In the console I'm getting (every 30secs):
`GET https://syncthing.local:8081/rest/events?since=203 net::ERR_INCOMPLETE_CHUNKED_ENCODING`
`UIOffline`
`UIOnline`
`event 203 Ping null`

**Comment by AudriusButkevicius** [comment]
I am 99.99% sure HAProxy is causing this.
Syncthing uses long polling to check for events, and your HAProxy seems to terminate the connection before syncthing itself devices to timeout.

**Comment by elijahpaul** [comment]
Yep. You're 100% right. The 'Server Timeout' on the backend server pool was 30secs by default. Adjusted it and the pop-up has stopped.

Thanks for you're help. Much appreciated.
