### ISSUE TITLE
flooding IPv6 port 21026 with UDP packets

### ISSUE THREAD

**Issue by westexjeff** [syncthing/syncthing#1395]
Using Syncthing v0.10.23 on two Arch Linux boxes.

I took the extract below from my firewall log. As you can see, two hosts on 
my network are flooding port 21026 UDP packets using the IPv6 Link-Local 
addresses (fe80::) on the two interfaces. This activity ceases the instant I shut 
down the syncthing daemons and starts again the instant I start them. Both 
of these systems have "Enable Global Discovery" un-checked and it should be 
disabled.

Mar 3 06:01:42 	LAN1 [fe80::21d:9ff:fe37:7b86]:21026 [ff32::5222]:21026 UDP
Mar 3 06:01:42 	LAN1 [fe80::21d:9ff:fe37:7b86]:21026 [ff32::5222]:21026 UDP
Mar 3 06:01:27 	LAN1 [fe80::219:d1ff:fe1e:272]:21026 [ff32::5222]:21026 UDP
Mar 3 06:01:27 	LAN1 [fe80::219:d1ff:fe1e:272]:21026 [ff32::5222]:21026 UDP
Mar 3 06:01:12 	LAN1 [fe80::21d:9ff:fe37:7b86]:21026 [ff32::5222]:21026 UDP
Mar 3 06:01:12 	LAN1 [fe80::21d:9ff:fe37:7b86]:21026 [ff32::5222]:21026 UDP
Mar 3 06:00:57 	LAN1 [fe80::219:d1ff:fe1e:272]:21026 [ff32::5222]:21026 UDP
Mar 3 06:00:57 	LAN1 [fe80::219:d1ff:fe1e:272]:21026 [ff32::5222]:21026 UDP
Mar 3 06:00:42 	LAN1 [fe80::21d:9ff:fe37:7b86]:21026 [ff32::5222]:21026 UDP
Mar 3 06:00:42 	LAN1 [fe80::21d:9ff:fe37:7b86]:21026 [ff32::5222]:21026 UDP
Mar 3 06:00:27 	LAN1 [fe80::219:d1ff:fe1e:272]:21026 [ff32::5222]:21026 UDP
Mar 3 06:00:27 	LAN1 [fe80::219:d1ff:fe1e:272]:21026 [ff32::5222]:21026 UDP

This behavior seems odd and it fills up my logs. I love syncthing and 
just wanted to share my observations in case they might be useful. Let 
me know if I can help.

Thanks,
Jeff

**Comment by AudriusButkevicius** [comment]
I think this is actually local discovery?

**Comment by dzarda** [comment]
Yeah, cross-check the 21026 port with your `config.xml`.
In my case, there's a following entry:

    ...
    <localAnnouncePort>21025</localAnnouncePort>
    <localAnnounceMCAddr>[ff32::5222]:21026</localAnnounceMCAddr>
    ...

-----
Do we have a config setting for disabling local discovery?

**Comment by westexjeff** [comment]
Yes I confirmed that setting in config.xml. I'm just running this on my local LAN so I have Global Discovery and UPnP disabled. Disabling Local Discovery stops the flooding but also stops my syncing. 

The reason it fills my firewall log is that it gets blocked as I have no rule to pass IPv6.

So what is the deal with it using IPv6 and that hard-coded [ff32::5222]:21026 target address?

**Comment by AudriusButkevicius** [comment]
So you can disable v6 local discovery by deleting the localAnnounceMCAddr entry from the config.
https://github.com/syncthing/syncthing/blob/master/internal/discover/discover.go#L84

I am not sure, but I think the address [ff32::5222] is just a random multicast address, just like 244.0.0.0 is for v4.
Also, it makes the announcement once every 30 seconds.

**Comment by westexjeff** [comment]
That's great. Thanks. Just to clarify for any future readers, The line in the config can be changed to read like this:
        <localAnnounceMCAddr></localAnnounceMCAddr>
All is well. Thanks again and great work guys.
