### ISSUE TITLE
Custom synchronization

### ISSUE THREAD

**Issue by zertyuiop** [syncthing/syncthing#1396]
Useful feature: if I want to synchronize one or more files from folder, syncthing shows list of files in this folder from remote device and I choose only one I need.

**Comment by AudriusButkevicius** [comment]
This can be done, but probably done easier as a separate client/command line utility which shares some same parts with syncthing, oppose to adding it to syncthing.

This will allow partially be possible using selective sync.

**Comment by schuft69** [comment]
sounds like duplicate to #1303 #687 and #193

**Comment by generalmanager** [comment]
@schuft69 Thanks for digging up related tickets. This one is the last one remaining for something similar:
https://github.com/syncthing/syncthing/issues/1185
