### ISSUE TITLE
Wrong usage help regarding home path

### ISSUE THREAD

**Issue by Jonny007-MKD** [syncthing/syncthing#1397]
Usage:
	  syncthing [options]
	
	Options:
	  -generate=""            Generate key and config in specified dir, then exit
	  -gui-address=""         Override GUI address
	  -gui-apikey=""          Override GUI API key
	  -gui-authentication=""  Override GUI authentication; username:password
	  -home=""                Set configuration directory

I did call `/usr/bin/syncthing -home="/home/osmc/.config/.syncthing"` and syncthing created the specified folder in the default folder

	/home/osmc/.config/.syncthing/"/home/osmc/.config/.syncthing/"/

As far as I can say -generate does not show this behavior.

**Comment by dzarda** [comment]
Interesting. See `main.go` for the flag parsing: https://github.com/syncthing/syncthing/blob/53f1af0cabf9b97210b600a5a95572244b17217d/cmd/syncthing/main.go#L206-L253

-----
Clearly, the `confDir` variable is bound to the "home" flag on line 226.

**Comment by Jonny007-MKD** [comment]
Well, the "home" flag did change the `confDir`, but the value was interpreted as relative path (because of the `"`) and appended to the working directory

**Comment by calmh** [comment]
You have a weird shell of some sort, that's not how parameters usually work...

```bash
jb@syno:~/src/github.com/calmh/travel (master) $ syncthing -home="/Users/jb/somedir"
[monitor] 17:50:23 INFO: Starting syncthing
[ZSOGZ] 17:50:24 INFO: syncthing v0.10.24 (go1.4.2 darwin-amd64 default) unknown-user@syncthing-builder 2015-03-01 20:51:56 UTC
[ZSOGZ] 17:50:24 INFO: My ID: ZSOGZDR-XKXYZI5-NIHKFTM-ET2BCLQ-VJBZDJU-R2664WV-CMOC57R-PGCP5AV
[ZSOGZ] 17:50:24 INFO: Starting web GUI on http://127.0.0.1:8080/
[ZSOGZ] 17:50:24 INFO: Loading HTTPS certificate: open /Users/jb/somedir/https-cert.pem: no such file or directory
[ZSOGZ] 17:50:24 INFO: Creating new HTTPS certificate
[ZSOGZ] 17:50:24 INFO: Generating RSA key and certificate for syno...
^C[monitor] 17:50:25 INFO: Signal 2 received; exiting
jb@syno:~/src/github.com/calmh/travel (master) $ 
```

(note notices about creating certs in the actual directory I specified etc)

**Comment by Jonny007-MKD** [comment]
syncthing was invoked by systemd on Debian Jessie, no fancy shell ;)
But I will try it again tomorrow.

**Comment by calmh** [comment]
So then systemd does something stupid... :)

**Comment by rumpelsepp** [comment]
From the [docs](http://www.freedesktop.org/software/systemd/man/systemd.service.html#Command%20lines)

> Quotes themselves are removed after parsing and escape sequences substituted. In addition, a trailing backslash ("\") may be used to merge lines.

You may use a service file like this one:

```
# …

[Service]
ExecStart=/usr/bin/syncthing -home=%h/.config/.syncthing"
```

Variables are documented here: http://www.freedesktop.org/software/systemd/man/systemd.unit.html#Specifiers

**Comment by Jonny007-MKD** [comment]
Hello together,
this is my systemd unit:

    [Unit]
    Description=SyncThing service for %i
    Documentation=https://github.com/syncthing/syncthing/wiki
    After=network.target
    
    [Service]
    User=%i
    Environment=STNORESTART=yes
    WorkingDirectory=/home/%i/.config/.syncthing
    Nice=17
    ExecStart=/usr/bin/syncthing -home="/home/%i/.config/.syncthing" -no-browser
    SuccessExitStatus=3
    Restart=on-success
    
    [Install]
    WantedBy=multi-user.target

When I start this, it results in this folder structure:
`/home/joni/.config/.syncthing/"/home/joni/.config/.syncthing"`

I confirm that this is a systemd issue (although I don't know how this can make a difference). As they are unneccessary I propose to remove the quotation marks from the usage help.

**Comment by rumpelsepp** [comment]
> Maybe the quotes are not removed because of the = sign. Try to omit them as they should be removed anyway.

Have you tried this? IMO this is intended behaviour. Try this service file:

```
[Unit]
Description=Syncthing - Open Source Continuous File Synchronization for %I
Documentation=https://github.com/syncthing/syncthing/wiki
After=network.target

[Service]
User=%i
Environment=STNORESTART=yes
ExecStart=/usr/bin/syncthing -home=%h/.config/.syncthing" -no-browser
Nice=17
Restart=on-failure
RestartPreventExitStatus=1
SuccessExitStatus=2
RestartForceExitStatus=3 4

[Install]
WantedBy=multi-user.target
```

**Comment by Jonny007-MKD** [comment]
Yes, this works as intended :)
Another alternative is that the argument parser looks for surrounding quotation marks and removes those.
