### ISSUE TITLE
Add icon for windows terminal？

### ISSUE THREAD

**Issue by renyouguo** [syncthing/syncthing#1398]
It is bad to see.

By the way，could I hide it to windows tray just as BTsync？It is useless to show.

**Comment by dzarda** [comment]
This needs to go to the respective project.

I assume you're using [iss0/SyncthingTray](https://github.com/iss0/SyncthingTray)

**Comment by renyouguo** [comment]
thanks，you are right.

**Comment by AudriusButkevicius** [comment]
`-no-console` to hide the window.
There is no way of adding a tray icon across platforms.
