### ISSUE TITLE
Accepting remote scan requests should be more clever

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#1399]
https://github.com/syncthing/syncthing-inotify/issues/22

We should make sure we have indexed everything up to the directory we are being asked to scan.

**Comment by zukoo** [comment]
@AudriusButkevicius the issue is not completely fixed for me:

Seems like the folder verification should be recursive. To reproduce the error :

    mkdir -p A/B/C/
    echo "Hello" >> A/B/C/test.txt

**Comment by AudriusButkevicius** [comment]
```diff
diff --git a/internal/model/model.go b/internal/model/model.go
index 4de15fc..bd88e64 100644
--- a/internal/model/model.go
+++ b/internal/model/model.go
@@ -1128,6 +1128,7 @@ func (m *Model) ScanFolderSub(folder, sub string) error {
 
        // Required to make sure that we start indexing at a directory we're already
        // aware off.
+       l.Debugln("Asked to scan folder", folder, "at", sub)
        for sub != "" {
                if _, ok = fs.Get(protocol.LocalDeviceID, sub); ok {
                        break
@@ -1137,6 +1138,7 @@ func (m *Model) ScanFolderSub(folder, sub string) error {
                        sub = ""
                }
        }
+       l.Debugln("Will scan folder", folder, "at", sub)
 
        w := &scanner.Walker{
                Dir:           folderCfg.Path,
```

Produces:

when `a/` is indexed and scanning `a/k/l/m/n`:
```
[RF545] 13:09:28 DEBUG: Asked to scan folder default at a/k/l/m/n
[RF545] 13:09:28 DEBUG: Will scan folder default at a
```

when nothing is indexed and scanning `q/w/e/r/t`:
```
[RF545] 13:10:18 DEBUG: Asked to scan folder default at q/w/e/r/t
[RF545] 13:10:18 DEBUG: Will scan folder default at 
```
where the empty string implies the root of the folder.

Hence not sure what is not fixed.

**Comment by zukoo** [comment]
Okay, my mistake what I did was: `echo "Hello" >> 1/2/3/4/test.txt` just after deleting the 1 on the other side. Which triggered the same `21:54:02: Folder "Sync" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.`  as it use to with inotify.
