### ISSUE TITLE
local (LAN) / global (internet) choice per folder

### ISSUE THREAD

**Issue by napseis** [syncthing/syncthing#1402]
hi,

Would it be possible to be able to choose wheter or not we want a folder to be synced over the internet , or only on the local network ?

Thanks

**Comment by AudriusButkevicius** [comment]
It always prefers LAN over WAN.
You can either have a special set of devices which only have LAN IPs configured which means they will not be discovered over the internet and only that one folder shared to achieve what you want.

**Comment by napseis** [comment]
My question pertains to the use of a laptop. For instance, a home i would like to have synced with my server and workstation the photos, important documents,etc. When i go to work or elsewhere with my laptop, then i don't want all the heavy files to synchronize with my (now on internet) server.

That is, I would like only specific folders to be always synchronized.

**Comment by AudriusButkevicius** [comment]
You can run two copies of syncthing. One with global discovery, one without.

**Comment by calmh** [comment]
#219 + config per folder instead of just per device...
