### ISSUE TITLE
Bad file name

### ISSUE THREAD

**Issue by YaLiC** [syncthing/syncthing#1403]
Faced with the problem of forbidden symbols in the windows operating system. Synchronization between Linux devices is going well, but when I add the device to the windows as began to get error messages in a bad file name, in particular because of the important symbols ":" (colon).
Suppose another possible problem, Linux systems are susceptible to different registers of letters, and no windows, it can lead to confusion.
I suggest to the window system to use substitutes for forbidden characters.

**Comment by schuft69** [comment]
looks like dublicate to #192

**Comment by calmh** [comment]
We don't do character substitution by design. If you want files to interoperate with Windows, you need to avoid the characters that are forbidden there.
