### ISSUE TITLE
dst create chmod operation not permitted

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing#1404]
Copied from https://github.com/syncthing/syncthing-android/issues/222

Synchronization gets stuck at ~80 percent and android log is full of messages like these:
```
03-05 21:43:03.525 I/SyncthingNativeCode(32092): [6PY5D] 20:43:03 INFO: Puller (folder "telefon", file "Abaddon's gate/Abaddon's Gate (Unabridged) Part 1.m4a"): dst create chmod: chmod /storage/sdcard1/sync/Abaddon's gate/.syncthing.Abaddon's Gate (Unabridged) Part 1.m4a: operation not permitted
```

Ignore permissions setting is set on both android and remote node. I tried to delete everything and start from scratch. That worked for a while but same thing happened again.

I am using version 0.5.17 on android and v0.10.24 on the other linux node.

Thank you for any tips.

**Comment by calmh** [comment]
Is it at all possible to get a `ls -ld /storage/sdcard1/sync/Abaddon's gate/`?

**Comment by calmh** [comment]
Also, is this new? I seem to recall chmod being accepted just fine by Android, but the semantics being that of FAT (i.e. we really only get 0777/0555 for dirs and 0666/0444 for files), while this seems to deny the chmod entirely...

**Comment by Gregy** [comment]
Here is the requested ls.
```
shell@dogo:/ $ ls -la /storage/sdcard1/sync/Abaddon\'s\ gate/                  
-rwxrwx--- root     sdcard_r 50855936 2015-03-05 21:20 .syncthing.Abaddon's Gate (Unabridged) Part 1.m4a
-rwxrwx--- root     sdcard_r 91247538 2015-03-05 21:23 Abaddon's Gate (Unabridged) Part 2.m4a
-rwxrwx--- root     sdcard_r 87431269 2015-03-05 21:23 Abaddon's Gate (Unabridged) Part 3.m4a
shell@dogo:/ $ ls -ld /storage/sdcard1/sync/Abaddon\'s\ gate/                  
drwxrwx--- root     sdcard_r          2015-03-05 21:23 
shell@dogo:/ $
```

**Comment by Gregy** [comment]
I am not sure what you mean by "is this new?" :( The device runs Cyanogenmod 11 (Android 4.4.4)

Also I do not think it is a system problem because the two other files in same folder synced just fine.

**Comment by Zillode** [comment]
It's also possible to get into problems when using ACL permissions:
```
touch myfile
sudo chown root:root myfile
sudo setfacl -m u:user:rwx,g:user:rwx,o::r-x myfile
echo "TEST" >> myfile # Works
chmod 666 myfile
$ chmod: changing permissions of ‘myfile’: Operation not permitted
```

**Comment by Gregy** [comment]
And this works on android? In either case I have done no such thing.

**Comment by calmh** [comment]
Right, I know when/why this happens now. Thanks!

**Comment by Gregy** [comment]
I thank you.
