### ISSUE TITLE
Folders exceeds size limit

### ISSUE THREAD

**Issue by Nerkill** [syncthing/syncthing#1405]
Hi.
I have 142 folders. Sync not work.

`[B7FF7] 11:51:01 INFO: Connection to *************************************** closed: Folders exceeds size limit; 142 > 64`

Version 0.10.24

**Comment by AudriusButkevicius** [comment]
Yes, 64 is tye hardcoded limit. What's the use case here? Could it be solved with subfolders within a folder?

**Comment by Nerkill** [comment]
Yes, the problem can be solved subfolders.
But why choose this limit?

**Comment by AudriusButkevicius** [comment]
Not sure. @calmh knows better. 
But I just felt it was to have reasonable message sizes.

**Comment by AudriusButkevicius** [comment]
But it's not document as part of the protocol though.

**Comment by Nerkill** [comment]
I found https://github.com/syncthing/syncthing/pull/886, but it says about the limit devices.
Maybe it makes sense to also remove the restriction on the number of folders?
If I understand correctly.

**Comment by AudriusButkevicius** [comment]
Yeah, it seems it should be removed.

**Comment by calmh** [comment]
I think this is just legacy, the limit should be removed.

**Comment by flungo** [comment]
Maybe set it to 65,534, if I am not mistaken that is the FAT32 limit. Unless you're interested in keeping FAT16 support in which case 512 would be the limit.

**Comment by AudriusButkevicius** [comment]
I've made a PR which removes the limit.
I feel that it will be part of the next release on sunday.

**Comment by Moter8** [comment]
@AudriusButkevicius Mind linking the PR? Just for archive purposes.

**Comment by AudriusButkevicius** [comment]
https://github.com/syncthing/protocol/pull/6

**Comment by calmh** [comment]
Fixed in 03bbf27 (merge of Audrius' change), I forgot to tag the issue.

**Comment by srameh** [comment]
I had the same issue so i disconnected that particular device and added back. It asked me to upgrade my SyncTrayzor. Once I did that the problem was resolved.
