### ISSUE TITLE
Copy on Modification Feature

### ISSUE THREAD

**Issue by hgn** [syncthing/syncthing#1406]
Use case: one root folder (and a deep subfolder structure) only with media data. E.g. images but can be music/video files too. Now imagine a disk corruption, caused by bad hardware, kernel FS bugs, ...

Result in synchronization and corruption of all images on all nodes. Typical answer: "sync is no backup", probably. But why should I setup a complicated, error-prone backup system which may not work when needed when I already synched the data between several nodes, when the check-summing mechanism knows the integrity of data (i,e.something change)? Similar to git: no one backups his git repository when it is hosted one more then one computer.

Currently I use bittorrent sync with versioned enabled. If a file is modified the old one is saved and the next version number is added to this file. This is nearly perfect: images/audio files never change. But when they change it boils down to an error somewhere and an additional copy is just fine.

I named the feature copy on modification - because what should be possible without a copy is a directory restructuring (i.e. moving files, renaming files, ...). This should not result in a copy operation.

Another possibility is to prohibit file modification at all - this will also fulfills my use case. And I think many users use syncthing to sync unmodifiable media data.

**Comment by AudriusButkevicius** [comment]
`Result in synchronization and corruption of all images on all nodes`
Why? If the mtime hasn't changed, the change will not be propagated.

`Currently I use bittorrent sync with versioned enabled`
Syncthing also has versioning feature too.

`Another possibility is to prohibit file modification at all - this will also fulfills my use case. And I think many users use syncthing to sync unmodifiable media data.`
This is called Master feature, which prevents other nodes from modifying the data.

It seems that everything that you want already exists?

**Comment by hgn** [comment]
Not fully: mtime corruption is possible - sha1 file content checksumming is secure. The master feature may help but if the master sdd/hdd has problems it will not help at all.

Regarding the versioning feature: I saw a github issue which was closed. So I thought there is no feature similar to bittorent sync versioning. My fault to not read the actual documentation. This should do the trick.

Question: a "initial checkin and not-modifiable afterwards" feature is no available (apply for all notes, including master node)?

Anyway, thank you!

**Comment by AudriusButkevicius** [comment]
Well if you have both mtime corruption and content corruption, you should change the disk to start with.

It is possible to have initial checkin and non-modifiable afterwards...
You sync the content, and then stop syncing (or unshare, or mark as master on all nodes)... 
Hence nobody modifies anything after that.
At the point you want to sync again, you start syncthing again.

Now you cannot rename, add files etc, but that's fine right?
Because what if cosmic rays hit FS index and suddenly rename a file or move a file to or from the shared directory... We don't want this corruption to propagate, right?

**Comment by hgn** [comment]
"Initial and no modification afterwards" on a file basis - not on a global basis. Think about your photo (or mp3) collection: you want to add files over time. But you don't want to modify these files afterwards. You also want to add more files and from every computer, not a single one. Think about adding images to a directory from a smartphone, because you shot a photo there. Lets call this "pristine mode" - add content from everywhere, modifications are not allowed. Explicit renames/delete operations on the other hand are allowed.

This is the feature that everybody want's who sync photos/media files. Without this mode and with disk corruption (and yes, there are more common with SSDs) you risk to loose you data - because you sync the files errors to every device. This is not what you want for many files types. Rather txt, doc, xml, are a exception, more file types I synchronize are never touched by myself:

File Type | Normally modified by user?
------------ | -------------
PDF | no modification
ePUB | no modification
Videos |  no modification
mp3 and audio in generall |  no modification
raw, jpg |  no modification (especially in times where lighttable and friends add xml files and describe the change)
doc |  modifications common
xml |  modification common
txt | modification common

You get what I want? For me this is a killer feature!

**Comment by AudriusButkevicius** [comment]
Yeah, I see how this would be useful, but I would just use a periodic rsync with the right set of command line flags.
This is fairly easily solvable problem since the data doesn't change, and what syncthing does is a bit more complex, hence using syncthing for this is an overkill.

**Comment by hgn** [comment]
Ok, I see. Anyway, thank you very much Audrius - great support. For the next time in Germany I will pay you first beer. I will close the issue.
