### ISSUE TITLE
Global Exclusions

### ISSUE THREAD

**Issue by majorsl** [syncthing/syncthing#1408]
Instead of individual directories, it would be useful to have a global exclusions list/section.

For example, no matter what share I've created, I do not want OS X's .DS_Store or Window's ThumbsDB to be copied across.

**Comment by generalmanager** [comment]
@majorsl Your idea seems to be somewhere in between https://github.com/syncthing/syncthing/issues/1392 and https://github.com/syncthing/syncthing/issues/837. Please join the discussions in those tickets to help improve syncthing and close this one. Thanks!

**Comment by majorsl** [comment]
True, but this is a bit different - not saying that either one couldn't solve this. #837 seems like it'd be a static built-in list - which would be good for my examples above, but not something specific to each directory that isn't a system level item. #1392 still seems to be on a per-directory share, not globally, but I do like the idea syncing exclusionseven at that level!

**Comment by flungo** [comment]
I feel that this issue is somewhere between the two other issues #1392 and #837, as @generalmanager says. I would close this ticket as a duplicate and refer to those issues.

**Comment by majorsl** [comment]
Fair enough. I saw someone linked it in those two issues. I'll close it.
