### ISSUE TITLE
Performance Issues on ARMv5

### ISSUE THREAD

**Issue by pkel** [syncthing/syncthing#1409]
Hello everybody,

I'm new to this piece of software and didn't examine every thread. Please forgive me repeating others. 

I'm testing Syncthing with a Synology Diskstation DS211j with a huge folder of ~480GB. The DS has an ARMv5 Single Core CPU at about 1.2 GHz and 128 RAM. Using SAMBA I can read/write from/to the NAS with >30MB/s. DS as Receiver, I'm syncing with only ~1MB/s. Compression is turned off, because the data is already compressed.

As far as this one can argue with insufficient hardware, but I've made two strange observations:
1) I can reproduce the [GUI open <> transfer rate dropping] issue. 
2) Restarting Syncthing on NAS causes a huge(>30min) "heating period" till transfer rate re-increases from <0,3MB/s to 1MB/s

Please tell me if i can do something do support your development.

Edit:
Source System is Core i5 with 8GB RAM running Ubuntu 14.04. 
Syncthing 0.10.24 running on both ends.

**Comment by AudriusButkevicius** [comment]
Reading from samba does not involve crypto, and crypto is your bottleneck.
1. Can you get a block profile? It explains how to do that in -help.
2. We are exchanging indexes initially and doing some scanning which also uses crypto, hence that could contribute to it.

**Comment by pkel** [comment]
I've restarted Syncthing with STBLOCKPROFILE=1 on my NAS. I will post a profiles after the systems have exchanged their indexes and are running on normal speed.

**Comment by pkel** [comment]
Ok. I failed. My hardware did. Since restart it has been freaking out. I have not measured a drop, because it didn't even speed up in the last 5 hours. Perhaps it's time for an upgrade.

**Comment by AudriusButkevicius** [comment]
The block profile might still be useful

**Comment by AudriusButkevicius** [comment]
Is this still an issue?

**Comment by pkel** [comment]
I'm currently doing some travelling and I'm not into the topic. I will reopen on occassion.
