### ISSUE TITLE
Can't delete some devices

### ISSUE THREAD

**Issue by lupa18** [syncthing/syncthing#1413]
As you can see in attached images, I try to delete some devices (two that never couldn't connect with) and got an error. 

Then there still there :(

ST Version: v0.10.24

![captura de pantalla de error-borrando-repo](https://cloud.githubusercontent.com/assets/463429/6540010/dd332c66-c466-11e4-86bd-366590f17470.png)
![captura de pantalla de error-borrando-repo1](https://cloud.githubusercontent.com/assets/463429/6540012/dd424548-c466-11e4-8f0c-bf940685ace3.png)
![captura de pantalla de error-borrando-repo2](https://cloud.githubusercontent.com/assets/463429/6540011/dd40a6de-c466-11e4-988c-e8ad1e121130.png)

**Comment by AudriusButkevicius** [comment]
Haveyou tried refreshing the page?
Are you are using a proxy of some sort?

**Comment by lupa18** [comment]
Yes, I tried refreshing in that moment. 

I don't know why, but finally I got it.
