### ISSUE TITLE
API Key vulnerability?

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#1416]
It might be that I'm missing something here, but just in case...

You need an API Key to make POST requests. However, you *don't* need an API key to fetch the current config, which contains the API Key... It seems a bit like locking the front door, then taping the key to it.

**Comment by calmh** [comment]
There's no authentication per default. That you need an API key to make post requests anyway is kind of incidental - what you *really* need is the CSRF token, to protect against cross site requests, but the API key works as well because it would be annoying for it not to.

**Comment by canton7** [comment]
OK that makes sense, thanks!

**Comment by Rewt0r** [comment]
@calmh I do think @canton7 has found a real  vulnerability here, I personally think the API Key should be hidden from the REST output. Consider this scenario:

 - User gets infected with malicious program
 - Malicious program opens up `/rest/config` (which I can do without the CSRF token with a GET request)
 - Malicious program navigates to `/` and takes the CSRF token from the cookie it receives
 - Malicious program now has complete control over the REST interface

**Comment by canton7** [comment]
It had complete control over the REST interface before getting the CSRF token - you don't need it if you've got the API key. But then, the user has complete control over their configuration - it'd be a bit shit if they didn't. Password-protecting the GUI also protects the REST interface.

**Comment by Rewt0r** [comment]
I think that's missing the point, that means every basic installation will be vulnerable.

**Comment by canton7** [comment]
For every basic installation it doesn't matter. Syncthing is running under the user's privileges, and the user's privileges are minimal. By default, there's nothing that a malicious process could get Syncthing to do, that it couldn't already do itself.

**Comment by Rewt0r** [comment]
Yes but for companies to use Syncthing the majority will not install it this way, it's a pain for sysadmins hence why it's installed as a service under LocalSystem.

Yes we can add a user to each machine that it runs under and set permissions but this is very long winded. I still think the API key should be hidden from the REST output.

**Comment by calmh** [comment]
@Rewt0r But the first two steps of your scenario aren't necessary. It can just as well just be

 - Malicious program navigates to / and takes the CSRF token from the cookie it receives
 - Malicious program now has complete control over the REST POST interface

This assumes the malicious program is running on the user's own computer though, as we only listen on 127.0.0.1 by default. So it could also be simplified to

 - Malicious program writes malicious config to syncthing's config dir.
 - Malicions program wins.

I'm not sure this is in scope for us to protect against?

**Comment by canton7** [comment]
It wouldn't change anything. If you hide the API key, then automation can just grab a CSRF token. 

If a logged-on user can access Syncthing with a password, so can automation.

**Comment by canton7** [comment]
@calmh For background, @Rewt0r wants to install Syncthing as a service, running as Local Admin. The config file would probably be protected in this case, but without password-protecting the GUI, that of course isn't.

My argument is that he shouldn't be running Syncthing as the Local Admin :)

Full discussion starts here: https://discourse.syncthing.net/t/windows-autostart-service-or-start-on-login-comments-please/2042/18?u=canton7

**Comment by calmh** [comment]
Ah, right, yes, the second case is not relevant then.

**Comment by Rewt0r** [comment]
@calmh Fair point! Excuse my non-forward thinking I've been awake for 29 hours or so working!

**Comment by calmh** [comment]
Ouch ;D

**Comment by jpjp** [comment]
It's unexpected though. Why ask for a token at all?

**Comment by canton7** [comment]
http://en.wikipedia.org/wiki/Cross-site_request_forgery

We need to ensure there are two requests, with a value from the first being used in the second. At least, that's my understanding

**Comment by calmh** [comment]
Yes. Regardless of if you e setup auth or not, I shouldn't be able to trick you into making a post request to syncthing from another page.

**Comment by Nutomic** [comment]
Is there any reason to include the API key in `/rest/config`? It should be trivial to exclude it.

**Comment by calmh** [comment]
So that the user can see it the UI?

**Comment by Nutomic** [comment]
Ok that makes sense :D
