### ISSUE TITLE
Files with special chars (á,é,í,ó,ú,others) won't sync

### ISSUE THREAD

**Issue by bicubico** [syncthing/syncthing#1417]
Files with special chars (á,é,í,ó,ú,others) won't sync
In the gui, when trying to sync, message says:

0:41:14: File "2013/INFORME RRHH 2012/Informe Final Práctica.pptx" contains non-NFC UTF-8 sequences and cannot be synced. Consider renaming.

Many words (and files) in Spanish use these chars

**Comment by calmh** [comment]
The characters themselves are fine, they are just not encoded as expected for your platform. Probably you have moved them from a Mac to Windows or vice versa.

https://github.com/syncthing/syncthing/issues/430
