### ISSUE TITLE
"GetAddrInfoW: No such host is known" right after upgrade to 10.25

### ISSUE THREAD

**Issue by hakakou** [syncthing/syncthing#1418]
It just upgraded to version v0.10.25 and every minute I started getting this notice: 
"10:24:50: discover udp6://announce-v6.syncthing.net:22026: broadcast: GetAddrInfoW: No such host is known.; trying again in 1m0s".

Is this normal?

**Comment by AudriusButkevicius** [comment]
Yeah we should be more graceful about this.
