### ISSUE TITLE
Chrome browser get's in a loop loading the page after upgrade 10.25

### ISSUE THREAD

**Issue by fobe** [syncthing/syncthing#1419]
Hi,
I just upgraded to the new version 0.10.25. Now when I go to the site with Chrome browser it's refreshing the pages constantly en never stops. It looks like a "refresh-loop" in Chrome. It works fine witch Firefox & IE.

**Comment by AudriusButkevicius** [comment]
Try shift refreshing, perhaps there is some kind of cache problem.

**Comment by fobe** [comment]
Thanks for the reply. It was indeed a cache issue
