### ISSUE TITLE
Allow API clients to access password-protected GUI

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#1420]
Hi,

The relates to canton7/SyncTrayzor#13. It would be nice if a REST API client (i.e. something that already has access to the API key) could automatically log into the Web interface. It can currently alter the user's config to overwrite the username/password, but this is hardly ideal! Possible options that come to mind are:

 - Allowing a 'magic' username/password derived from the API key (if and only if the API key has been specified on the command-line - otherwise the password hashing in the user's config.xml is somewhat pointless)
 - Allowing an extra username/password to be specified on the command-line (which would operate in addition to the username/password that the user has configured)
 - Allowing a REST API call to set an extra username/password
 - Allowing a REST API call to fetch an extra username/password generated by Syncthing

Thanks!

**Comment by AudriusButkevicius** [comment]
https://github.com/syncthing/syncthing/blob/master/cmd/syncthing/gui_auth.go
It checks for either Basic Auth or API key, if either is present, you can do everything, as the two are no way different.

**Comment by kozec** [comment]
> It checks for either Basic Auth or API key, if either is present, you can do everything, as the two are no way different. Just make sure Cef sends the API key via headers.

But GUI has no way how to force browser of webview component to send X-API-Key header, so it always end with popup asking user for password.

**Comment by AudriusButkevicius** [comment]
I find it hard to believe that you cannot set a custom header.

**Comment by canton7** [comment]
@AudriusButkevicius Aha, I hadn't realised the web UI would accept the API key. That's perfect, thanks!

@kozec In this instance I'm using cefsharp/CefSharp as the browser component, and that lets me do all sorts of nasty stuff, including whatever I want to the headers.

**Comment by canton7** [comment]
Confirmed that this works. Thanks guys!
