### ISSUE TITLE
Incorrect and inconsistent information in the GUI

### ISSUE THREAD

**Issue by unfa** [syncthing/syncthing#1422]
Hey!

I'm testing Synthing with a friend in LAN via WiFi.
I'm sedning files to his machine via "default" folder, and I'm downloading data from his machine through "Speed test" folder.

![synthing](https://cloud.githubusercontent.com/assets/491704/6546284/bce36fa4-c5ae-11e4-8154-3fc470e69cb4.png)

The "default" folder shows that the global state is equal to local state, whitch means that all files from my machine to friend's were transfered already. It's not true however and the right pane proves that - the tranfer rate is sending data back and forth, also the total data transefered amounts are by no means equal to the "default" folder size, so obvously not all data was sent, also all files are not present on my friend's machine, as we can see with a file management application.

So looks like Syncthing shows inconsistent data for some reason. I'm using version 0.10.25 as you can see in my machine's info pane.

PS: You're doing great job with this project! Thank you! :)

**Comment by calmh** [comment]
> The "default" folder shows that the global state is equal to local state, whitch means that all files from my machine to friend's were transfered already.

Now, the "global state" is the description of the ideal, up to date, state. I.e. a fully up to date device should have 155 items totalling 4.24 GiB. Your device has 155 items, totalling 4.24 GiB. It is in sync. The other device has about 60% of those 4.24 GiB and is not up to date (it's "Syncing").

Obviously this is not totally obvious. :) Any suggestions on how to make it more so?

**Comment by lovetox** [comment]
hm, i have to say i didnt get it either from the start, but knowing now, i cant really find a better way.

maybe adding a 100% to the local state, but then the "Up to Date" is redundant in the header ..
maybe tooltips which describe whats what.
