### ISSUE TITLE
discover udp6://announce-v6.syncthing.net:22026: broadcast: listen udp6 :0: address family not supported by protocol; trying again in 1m0s

### ISSUE THREAD

**Issue by frank-github** [syncthing/syncthing#1426]
Installed syncthing first time on my raspberry (rasbian) 
After Installation and first start I got this warning every minute :(
What does it mean and how can I get it away?

discover udp6://announce-v6.syncthing.net:22026: broadcast: listen udp6 :0: address family not supported by protocol; trying again in 1m0s

Sounds like IPv6, but I running IPv4 in my local network.
any hints and tips are welcome

Frank

**Comment by frank-github** [comment]
okay, disabled global discovery in settings and warning is gone.
within config.xml this udp6 adress can be found. Can I delete this entry, if I not using IPv6?
Is this the correct way to turn this feature off??

**Comment by AudriusButkevicius** [comment]
Yes, you can remove that, a fix is already committed and will be there next release.
