### ISSUE TITLE
[UI] Improve UI for non-dualstack connections

### ISSUE THREAD

**Issue by generalmanager** [syncthing/syncthing#1427]
Currently the announce server count is colored red if a device isn't connected to all announce servers. Unfortunately many people are still on IPv4 only or IPv6 only connections.
Thus they will never be connected to the official announce server via UDP4 and UDP6, which means the 1/2 count is always colored red.
But we shouldn't alarm the average user if they can't do anything about it.

I have two proposals, one beeing the better solution and the other one is easier to implement:
- good: color the announce server count red if no connection can be made OR if ST can connect to at least one announce server via UDP4/UDP6, but not others via the same protocol
- easy: only color the announce server count red if no connection can be made

**Comment by generalmanager** [comment]
Wow that was really quick. Thanks!

**Comment by lkwg82** [comment]
Yeah, I still have a beep in my ears ;). Thx.
