### ISSUE TITLE
discover udp6://announce-v6.syncthing.net:22026: broadcast: GetAddrInfoW: No such host is known.; trying again

### ISSUE THREAD

**Issue by dickstar** [syncthing/syncthing#1431]
I installed v0.10.25 in Windows 7.

I saw the alerts appeared repeatedly:

21:02:07: discover udp6://announce-v6.syncthing.net:22026: broadcast: GetAddrInfoW: No such host is known.; trying again in 1m0s

21:03:07: discover udp6://announce-v6.syncthing.net:22026: broadcast: GetAddrInfoW: No such host is known.; trying again in 1m0s

21:04:07: discover udp6://announce-v6.syncthing.net:22026: broadcast: GetAddrInfoW: No such host is known.; trying again in 1m0s

21:05:07: discover udp6://announce-v6.syncthing.net:22026: broadcast: GetAddrInfoW: No such host is known.; trying again in 1m0s

What happened to that address?

**Comment by AudriusButkevicius** [comment]
Please check the issue tracker before opening new issues.
This has already been fixed, and will be part of the next release hopefully on Sunday.

**Comment by jpjp** [comment]
The github issue search defaults to is:open, so maybe we should keep one of these open.

**Comment by dickstar** [comment]
Thanks for your help. I will check the issue tracker before opening new issues in the future.
