### ISSUE TITLE
How to compile to MIPS architecture?

### ISSUE THREAD

**Issue by comtom** [syncthing/syncthing#1432]
Hi, I'm wondering how to compile to MIPS (openWrt) is it possible?

**Comment by AudriusButkevicius** [comment]
https://groups.google.com/forum/#!topic/golang-dev/NAl6NGZ4XeU
I don't think there is official MIPS support in Go.
You can try using CGO.
https://github.com/GeertJohan/openwrt-go/compare/add-gccgo-and-libgo
