### ISSUE TITLE
panic: leveldb/table: corruption on table-footer (pos=1151795): bad magic number [file=000007.ldb]

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing#1433]
syncthing v0.10.25 (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-03-08 07:41:43 UTC

Happens all the time even when clearing the index: http://wilma.vub.ac.be/~lhoste/private/panic-20150309-170321.log

**Comment by AudriusButkevicius** [comment]
Clearing being what?

**Comment by Zillode** [comment]
nevermind, ```panic: write /data/Apps/Syncthing/index/000001.log: input/output error```. Need to check my disks:/
