### ISSUE TITLE
Syncthing GUI can inundate Syncthing with pending requests

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#1434]
Hi,

As mentioned in #867, I'm seeing issues where GUI starts sending polls to Syncthing before the previous polls have completed. This snowballs, resulting in the Syncthing having to process lots of duplicate requests. Everything does recover, but it takes a fair while.

Now, Syncthing is running on a low-power device here - an ODROID-C1 - but the GUI could still play more nicely.

I've yet to find a nice way of capturing a single screenshot which contains all the information I want to convey. So, I'll describe what happens for now:

1. Load the GUI. A bunch of requests go out, and typically 'connections' or 'report' can take up to a minute to respond.
2. In the meantime, the GUI has requested the 'model' resource for all folders, and all connections for all devices on all models. This adds up to quite a lot of pending connections!
3. 'system', 'connections', and 'errors' then start stacking up - I can get quite a few simultaneous sets of these 3 before the original holdup clears.

Suggestions:
 - Don't schedule one poll before the previous poll has finished. 
 - Consider limiting the total number of pending requests.

Thanks!

**Comment by canton7** [comment]
I've also now seen this on a much more powerful machine. Syncthing gets busy hashing stuff (I assume) ,  and the 'system', 'connections', and 'errors' polls start stacking up.

**Comment by Zillode** [comment]
Can you verify if there are pending ```completion``` calls as well? This should be the main problem I believe.

**Comment by canton7** [comment]
I'll check that next time I see it, sure

**Comment by N-Coder** [comment]
I think a bidirectional Publish/Subscribe system via [WebSockets](https://en.wikipedia.org/wiki/WebSocket) would be better suited here (it is the successor of BOSH, Comet, long polling, etc.). The Website/GUI could connect to the Syncthing API via WebSocket and subscribe to all the "channels" that should be updated regularly (as noted in syncthing/syncthing-gtk#66: /rest/system, errors, connections and events) and the server would then send updated data as soon as it changes (or at regular intervals, if changes can't easily be detected, e.g. for the CPU usage in /system). All other requests (mainly POST requests and GETs for data that rarely changes) would still be made via normal HTTP/REST.
This would remove the problem of AJAX requests piling up when the server is too slow to respond, and usually leads to data being updated faster (as it is immediately pushed from the server and not pulled by the clients in regular intervals) at the very low cost of the server managing a stable WebSocket connection per client. As WebSocket is one of the main features of HTML5, it is broadly supported by modern browsers and has various server implementations.
I would really like to help you implementing such improvement, as it would probably solve the problem mentioned in issue #867 (which also affects my syncthing setup). I could help with the design of such an API and the implementation of WebSocket Server and Client, if you want to see such feature implemented. Unfortunately I'm new to the go language and don't know anything about the internals of you API (but I'm also keen on learning more about it ;) ).

**Comment by canton7** [comment]
@N-Coder I think what you're proposing can be broken down into two separate (but related) issues:

1. We already have a long-polled events interface, where lots async data appears, without it having to be polled for. Putting stuff that's currently being polled for (model updates, errors, etc) onto the events interface would significantly reduce the amount of polling. This is (as I understand it) what @calmh's referenced commit does.
2. The events interface doesn't have to be long-polled: using websockets would be another option here, and one that might be worth considering. However do bear in mind that the majority of Syncthing's REST API clients *aren't* web browsers. We've got cli interfaces, custom GIUs, tray icons, you name it, interacting with Syncthing in this way. A long-polled interface is easy to write a client for: a websockets interface is tricky if you don't have a library available.

**Comment by kozec** [comment]
@canton7 
> However do bear in mind that the majority of Syncthing's REST API clients aren't web browsers.

Option to receive events with websocket would be useful even for GUI or desktop app. Staying in IO wait for next event message does practically zero CPU usage, while current polling requires maintaining timer and doing TCP connections ever few seconds (actually pretty crazy thing to do).

OFC, old pooling through HTTP would need to stay as second option, as not even every browser can use websockets.

**Comment by canton7** [comment]
> Option to receive events with websocket would be useful even for GUI or desktop app

Sure, but you need to make sure you can find a third-party library which supports that. Having a desktop app act as a websockets client is hardly a common thing to do.

> While current polling method requires maintaining timer and doing TCP connections ever few seconds (actually pretty crazy thing to do).

The *long polling* requires a thread, a loop, and a new connection about once a minute in the idle case. I think you're mixing up the "1. Use the events interface instead of polling", and "2. Use websockets for the events interface" distinction I made above.

**Comment by N-Coder** [comment]
@canton7 the Pub/Sub WebSocket system should just be another option to blocking GETs via normal HTTP and long polling. Internally, it could probably use the same events which are exposed via long polling, with the only difference that the data is sent via a stable connection here. 

WebSocket clients are very easy to implement and there are already various different libraries for that ((Go)[https://godoc.org/golang.org/x/net/websocket], (Java)[http://autobahn.ws/], (Python)[https://pypi.python.org/pypi/websocket-client],...), so most of the non-webbrowser clients would also benefit from this feature.

**Comment by N-Coder** [comment]
@canton7 the Pub/Sub WebSocket system should just be another option to blocking GETs via normal HTTP and long polling. Internally, it could probably use the same events which are exposed via long polling, with the only difference that the data is sent via a stable connection here. 

WebSocket clients are very easy to implement and there are already various different libraries for that ([Go](https://godoc.org/golang.org/x/net/websocket), [Java](http://autobahn.ws/), [Python](https://pypi.python.org/pypi/websocket-client),...), so most of the non-webbrowser clients would also benefit from this feature.

**Comment by canton7** [comment]
@N-Coder I agree - I tried to make this clear. My point 2 above says exactly that.

**Comment by calmh** [comment]
> Option to receive events with websocket would be useful even for GUI or desktop app. Staying in IO wait for next event message does practically zero CPU usage, while current polling method requires maintaining timer and doing TCP connections ever few seconds (actually pretty crazy thing to do).

This is not how (the current, or hopefully any) long polling works.

**Comment by AudriusButkevicius** [comment]
@kozec @Nutomic @Zillode @canton7 
Just a heads up to everyone, that this is an API change, and that anyone consuming the API should now receive this information via the events interface (rather than hitting the APIs every N seconds)

**Comment by canton7** [comment]
Thanks!

**Comment by canton7** [comment]
Maybe I'm missing something, but the sequence of API calls when the browser is first loaded, and when it's idle, is identical between 0.10.30 and 0.11.0-beta4. The difference appears to be that we no longer hti the `completion` resource when the `LocalIndexUpdated` or `RemoteIndexUpdates` events are received, but that doesn't affect the issue as I reported it.

**Comment by AudriusButkevicius** [comment]
Can you listen on 0.0.0.0 with your phone, and then from your desktop access that, and printscreen the Chrome developer tools network tab so that we could see how long what takes, to understand it better.

**Comment by canton7** [comment]
I'll grab a screenshot tonight - this is on an odroid-c1, which is at home (and I'm currently at work).

**Comment by canton7** [comment]
Right, here we go. Note that this is 3 screenshots pasted together, and time has elapsed between them causing the scales to change. I've lined them up so that the 2.0 min mark is common across them.

Note how there's 11 sets of system+connections+errors before the initial hold-up clears. This *is* on a slow device and I'm not worried about things taking a while to get going. It's this stacking-up behaviour that prompted me to open this issue.

![syncthing](https://cloud.githubusercontent.com/assets/568104/7053946/0e07dd58-de31-11e4-97ca-9ac7d7c1a44d.png)

**Comment by AudriusButkevicius** [comment]
It's not clear which call is to blame to be honest.

**Comment by canton7** [comment]
Anything else I can capture that would help?

**Comment by AudriusButkevicius** [comment]
Can you just for fun, comment out completion and model ajax calls, and see if the rest of the calls return with a reasonable time?
If yes, then comment out only model or only connections?
Also, if you run the beta STTRACE=http would help too.

**Comment by canton7** [comment]
Sure. Give me a day or two

**Comment by ramontayag** [comment]
I'm seeing this too. Syncthing is on a Raspberry Pi. It seems to poll the server still. On `v0.10.30`.

![syncthing___raspberrypi](https://cloud.githubusercontent.com/assets/25332/7218714/c9faef24-e6af-11e4-8cc8-c0d509e89c4f.png)

**Comment by calmh** [comment]
`system`, `errors` and `connections` are still polled. That's fine. `completion` and a few others are polled once when the GUI loads too.

**Comment by ramontayag** [comment]
Forgive me if I missed the answer. If `system`, `errors`, and `connections` stack up and cause the "Connection Error" modal to appear, should they be pushed as well? Btw, I haven't tried `0.11` and it may well have been fixed there.

**Comment by AudriusButkevicius** [comment]
The reason why others stack up is because there is a shared lock which they contend against, hence stack up.
Try 0.11 and see if it's still an issue.

**Comment by ramontayag** [comment]
I will. Thanks!

**Comment by calmh** [comment]
It doesn't do this any more.
