### ISSUE TITLE
udp6 announcement warns indefinitly in case of missing IPv6 device

### ISSUE THREAD

**Issue by lkwg82** [syncthing/syncthing#1435]
Hi,

after upgrading I get warnings in a loop saying: 

```
21:53:03: discover udp6://announce-v6.syncthing.net:22026: broadcast: no suitable address found; trying again in 1m0s
```

I'm on linux and does not have any ipv6 configured.

cheers Lars

P.S. I can remove it from global discovery, but I think this could be considered is an UX bug.

**Comment by lkwg82** [comment]
Related to #1427

**Comment by AudriusButkevicius** [comment]
Fixed already.
