### ISSUE TITLE
WARNING: discover udp6://announce-v6.syncthing.net:22026: broadcast: GetAddrInfoW: No such host is known.; trying again in 1m0s

### ISSUE THREAD

**Issue by lucanos** [syncthing/syncthing#1440]
Seeing this error frequently on Windows 7 PC running Syncthing v0.10.25.

> [ATVKZ] 00:46:16 INFO: syncthing v0.10.25 (go1.4.2 windows-amd64 default) unknown-user@syncthing-builder 2015-03-08 07:41:43 UTC
> [ATVKZ] 00:46:16 INFO: My ID: [[CONCEALED]]
> [ATVKZ] 00:46:32 INFO: Starting web GUI on http://127.0.0.1:8080/
> [ATVKZ] 00:47:12 INFO: Starting UPnP discovery...
> [ATVKZ] 00:47:18 INFO: UPnP discovery complete (found 0 devices).
> [ATVKZ] 00:47:18 INFO: Starting local discovery announcements
> [ATVKZ] 00:47:18 INFO: Local discovery over IPv6 unavailable
> [ATVKZ] 00:47:18 INFO: Starting global discovery announcements
> [ATVKZ] 00:47:18 OK: Ready to synchronize Clients (read-write)
> [ATVKZ] 00:47:18 WARNING: discover udp6://announce-v6.syncthing.net:22026: broadcast: GetAddrInfoW: No such host is known.; trying again in 1m0s
> [ATVKZ] 00:47:23 INFO: Device [[CONCEALED]] is "Alpha" at > [dynamic]
> [ATVKZ] 00:47:23 INFO: Device [[CONCEALED]] is "Bravo" at > [dynamic]
> [ATVKZ] 00:47:23 INFO: Starting usage reporting
> [ATVKZ] 00:47:25 INFO: Established secure connection to [[CONCEALED]] at 192.168.2.50:52766-192.168.2.120:22000
> [ATVKZ] 00:47:25 INFO: Device [[CONCEALED]] client is "syncthing v0.10.25"
> [ATVKZ] 00:47:25 INFO: Device [[CONCEALED]] name is "Bravo"
> [ATVKZ] 00:48:18 WARNING: discover udp6://announce-v6.syncthing.net:22026: broadcast: GetAddrInfoW: No such host is known.; trying again in 1m0s
> [ATVKZ] 00:49:18 WARNING: discover udp6://announce-v6.syncthing.net:22026: broadcast: GetAddrInfoW: No such host is known.; trying again in 1m0s
> [ATVKZ] 00:50:18 WARNING: discover udp6://announce-v6.syncthing.net:22026: broadcast: GetAddrInfoW: No such host is known.; trying again in 1m0s
> [ATVKZ] 00:51:18 WARNING: discover udp6://announce-v6.syncthing.net:22026: broadcast: GetAddrInfoW: No such host is known.; trying again in 1m0s

**Comment by Zillode** [comment]
Please check existing issues, https://github.com/syncthing/syncthing/issues/1435
