### ISSUE TITLE
Download and Upload Rate information from remote device incorrect

### ISSUE THREAD

**Issue by ralder** [syncthing/syncthing#1441]
It swpped around, i.e. I move new file in sync folder in remote deivce("ubu64") and after syncing gui shows same information (uploaded and downloaded bytes) for local and remote device but at remote device it must be vise versa

![syn-device](https://cloud.githubusercontent.com/assets/10889830/6584667/d88e199a-c77d-11e4-9c1a-051ccdf707b4.png)

**Comment by AudriusButkevicius** [comment]
No.
I uploaded 6mb in total.
Out of the 6mb that I have uploaded, 6mb went to ubu64.

**Comment by AudriusButkevicius** [comment]
There has been numerous discussions about this on the issue tracker, search for closed issues if you want to dwell down deeper into discussions.
