### ISSUE TITLE
not work automatic upgrade on windows server 2003 r2

### ISSUE THREAD

**Issue by jpooh** [syncthing/syncthing#1444]
v0.10.24/25
log message - 
INFO: Automatic upgrade: Get https://api.github.com/repos/syncthing/syncthing/releases?per_page=10: x509: certificate signed by unknown authority

Win XP/7 work ok

**Comment by AudriusButkevicius** [comment]
Update your CA certificate store, aa you don't seem to trust githubs certificate.
