### ISSUE TITLE
Configuration location on XP

### ISSUE THREAD

**Issue by kozec** [syncthing/syncthing#1446]
Frankly, I'm not sure if XP is even supported, but one guy tried to run Syncthing-GTK on XP (syncthing/syncthing-gtk#104) and it failed also because of this...

When `syncthing.exe` if launched on Windows XP (manually), it creates `Syncthing/` subdirectory in current working one and stores configuration there. I would expect it to save configuration in `%AppData%/Syncthing` (there is no `%LocalAppData%` on XP), where it could be found and used by ST-GTK or other potential wrapper.

**Comment by AudriusButkevicius** [comment]
Marking as enhancement, given it's not a real operating system anymore.

**Comment by kozec** [comment]
I can't test it as I'm not quite sure how to compile go app on Windows, but here...

https://github.com/syncthing/syncthing/blob/c5838c143c84f4ea5d27813a1d5322f12e47bd4f/cmd/syncthing/main.go#L951

... simple check if value of LOCALAPPDATA is empty would be sufficient. If is empty, APPDATA can /should be used.

**Comment by calmh** [comment]
Huh. It's supposed to work on XP, and the first google hit (http://www.microsoft.com/security/portal/mmpc/shared/variables.aspx) implies it should, but further hits clarify that it doesn't. So I'm surprised this hasn't come up before.

**Comment by simplypeachy** [comment]
I can confirm from my varied experience of Windows systems that %localappdata% has never been present in Windows XP, but it has always had the "userprofile\Local Settings\Application Data" directory, which has similar intentions, but no environment variable. Windows Vista was the first operating system that supported the %localappdata% variable.

I am certain that localisation will mean one cannot rely on XP's Local Settings directory always having that name.

**Comment by kozec** [comment]
AFAIK, `Local Settings\Application Data` is used when XP is part of domain with roaming profiles enabled. Expect path is defined only in registry and nothing but few MS programs actually uses it :)

Thanks for quick help :)
