### ISSUE TITLE
Packing in an RPM latest 0.10.26 reports as unknown-dev

### ISSUE THREAD

**Issue by daniel-lucio** [syncthing/syncthing#1449]
I have packed as an RPM compiling from source the 0.10.26 tarball https://github.com/syncthing/syncthing/releases  and it is reporting me as an unknown-dev release instead to be 0.10.26

**Comment by AudriusButkevicius** [comment]
You need to have the right git tag applied AFAIK.
Or are you saying it started happening after this release?

**Comment by daniel-lucio** [comment]
I am not doing a GIT checkout, I am using the tar.gz you published

I dont know if this has happened before, 0.10.26 was my first RPM for your software

**Comment by AudriusButkevicius** [comment]
I think if you're not building from git, you need to specify the tag manually:
See: https://github.com/syncthing/syncthing/issues/975

**Comment by daniel-lucio** [comment]
But, if you publish a tar.gz i thing it should work without any GIT, right?

**Comment by calmh** [comment]
It does, but you need to build it correctly. (Also, Github publishes the .tar.gz, we have no say in it. :)

`go run build.go -help`

Use the `-version` flag to tag it.

**Comment by calmh** [comment]
I added a note about this to https://github.com/syncthing/syncthing/wiki/Building

**Comment by calmh** [comment]
We could solve this nicer though. Tagging as a build thing...

**Comment by calmh** [comment]
All solutions to this suck somewhat. Am I missing an awesome option?

https://github.com/syncthing/syncthing/wiki/WIP---Build-Strategies

**Comment by kozec** [comment]
git published source tarball always contains to directory syncthing-_<release>/, so if everything fails, build script can look for directory with such name in current path and extract version string from it - <a href="https://github.com/syncthing/syncthing-gtk/blob/master/setup.py#L19">example in python</a>

**Comment by calmh** [comment]
Actually, guessing from directory doesn't work. It works on my system if I download and build like that, but that's because I already have stuff in my GOPATH, but if you just download and try to build from a version-named directory you get this;

```
jb@syno:~/Downloads/syncthing-0.10.26 $ unset GOPATH
jb@syno:~/Downloads/syncthing-0.10.26 $ ./build.sh 
GOPATH is /
GOPATH=/Users/jb/Downloads/syncthing-0.10.26/Godeps/_workspace:/
go install -v -ldflags -w -X main.Version v0.10.26 -X main.BuildStamp 1426237403 -X main.BuildUser jb -X main.BuildHost syno -X main.BuildEnv default ./cmd/...
cmd/stcompdirs/main.go:28:2: cannot find package "github.com/syncthing/syncthing/internal/symlinks" in any of:
	/usr/local/go/src/github.com/syncthing/syncthing/internal/symlinks (from $GOROOT)
	/Users/jb/Downloads/syncthing-0.10.26/Godeps/_workspace/src/github.com/syncthing/syncthing/internal/symlinks (from $GOPATH)
	/src/github.com/syncthing/syncthing/internal/symlinks
...
```

So probably that bit should be reverted (to not give a false impression of that stuff working) and tagged source builds created on Jenkins. Go builds are annoying sometimes.

**Comment by calmh** [comment]
Question: if we build release tarballs (of source), is it worth letting them expand into `src/github.com/syncthing/syncthing/...` so that a cd into that directory and `go run build.go` is guaranteed to work, or is that super annoying and unexpected?

**Comment by AudriusButkevicius** [comment]
That won't work as we'd have to change imports to use vendor imports.

**Comment by calmh** [comment]
No, that's fine, build.go wrangles the GOPATH to manage that. But it can't wrangle the GOPATH correctly unless the path to the source is right to start with.

Although, we may want to do changed-import vendoring in order to avoid having to wrangle GOPATH too much to start with...

**Comment by calmh** [comment]
http://build.syncthing.net/job/syncthing-release/1782/artifact/syncthing-source-v0.10.26.tar.gz

With RELEASE tag (but without the code that uses it, since it's v0.10.26).

**Comment by daniel-lucio** [comment]
Done, my RPMs for Centos6 and 7 are here:https://okay.com.mx/en/linux/rpm-repositories-for-centos-6-and-7.html  ony for 64 bits, I havent had the time to install a 32 bits machine, and cross compilation wont work.  Just type: yum install syncthing   after adding my repo

**Comment by calmh** [comment]
So from v0.10.27, there's be a file called RELEASE in the source tarball, which will be uploaded to to the Github releases page. Note that this is different from the Github auto generated tarballs at the bottom of the page. The build script will pick up this file and tag the binary correctly.
