### ISSUE TITLE
Config directory should use platform default

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#145]
- Windows: `%AppData%/Syncthing`
- Mac: `~/Library/Application Support/Syncthing`
- Others: `~/.config/syncthing` (or `$XDG_CONFIG_HOME/syncthing`)

**Comment by jcrben** [comment]
Having a little bit of difficulty working with the `-home` flag, as mentioned at https://forum.syncthing.net/t/syncthing-and-xdg-base-directory-specification/2023/15?u=jcrben. An environment variable to customize the location would be a bit easier to work with, altho in this case it would have to be set by a LaunchAgent or something. I like to have my dotfiles in the Linux place for OSX for ease of reference and ease of switching to Linux...

**Comment by calmh** [comment]
Do not revive three year old issues please, your forum post is good enough.
