### ISSUE TITLE
Can't upgrade to  v0.10.26 from  v0.10.25 Raspberry Pi

### ISSUE THREAD

**Issue by OIWitteveen** [syncthing/syncthing#1452]
Hi, this is my first issue report ever. I hope i can inform you enough.

The last update of Syncthing gave me a warning about write permissions. Previous updates did not cause any problems.

I am currently running v0.10.25 and trying to update to v0.10.26. After clicking the upgrade button on the web interface the popup comes up informing me that it is upgrading the software. But after a few seconds the popup goes away but the button stays. Even after a refresh the button is still there.

I've clicked the button several times and the last few times it gave my the following two warnings:

10:42:39: Automatic upgrade: open /usr/local/bin/syncthing496416545: permission denied

14:03:46: upgrading: open /usr/local/bin/syncthing429828108: permission denied

I then SSH'd to my pi and went to the directory to only find that the file "syncthing429828108" isnt in that directory.

I presume i have to give syncthing write permission? I already gave it chmod +x.

Am i missing something or is this coincidental?

Some information:
Platform: Raspberry Pi
OS: Linux 3.18.8+ armv6l GNU/Linux (Raspbian)
Syncthing version:  v0.10.25

**Comment by OIWitteveen** [comment]
Update: I've tried chmod 777 but it's still giving me the same error.

**Comment by kozec** [comment]
You need write permissions for `/usr/local/bin/` as well. But it would be better to move syncthing to directory that is owned by user instead.

**Comment by AudriusButkevicius** [comment]
See: https://discourse.syncthing.net/t/upgrading-permission-denied-on-debian-server/2079

**Comment by OIWitteveen** [comment]
Thanks for the help!
