### ISSUE TITLE
Ignore permissions option not working as expected

### ISSUE THREAD

**Issue by madalu** [syncthing/syncthing#1453]
I have syncthing running on several machines (linux and android). If I limit the network to linux devices, everything syncs property and changes in file permissions are propagated across the network (provided there is a file change).

Then I introduce an Android device onto the network. I ensure that Ignore Permissions is true on the shared Android repository.

I expect the file permissions on the Linux machines not to change. However, after the Android device syncs, the permissions on all the files in the shared repository on the Linux machines are set to 666.

**Comment by calmh** [comment]
Yeah, this is probably an interaction with Android not keeping mtimes correctly. Although still, it should work as long as only metadata (such as the mtime) is changed on the Android side. Should try to add some tests for this, without having an actual Android device involved.

**Comment by calmh** [comment]
I'm going to go ahead and assume that this has been handled by the mtime handling changes we've done recently.
