### ISSUE TITLE
Problem with filenames with non-ASCII characters

### ISSUE THREAD

**Issue by seadra** [syncthing/syncthing#1454]
Names of all files with non-ASCII characters are "garbled" on other machines. Sees to be a encoding issue.

$LANG is set to en_GB.UTF-8 and C.UTF-8 on computers.

**Comment by jpjp** [comment]
C.UTF-8 isn't a valid locale, as far as I know.

**Comment by AudriusButkevicius** [comment]
It is a valid locale.
Can you do `LANG=POSIX ls -lab` on both sides?
Also, which distros are we talking about?

**Comment by calmh** [comment]
Garbled where and how?

**Comment by seadra** [comment]
Where: original filename is correct CJK text on the machine where the file originated, filename is garlabed on the other machine (where syncthing copied the file from origin).
How: Looked like CJK text in Latin encoding.

Strangely, after I upgraded to 0.10.26, everything returned to normal. So I guess this is fixed?

**Comment by calmh** [comment]
I don't think we're in any way dependent on the system locale for file names. We interpret and write them as UTF-8 though in all cases. Are you sure the filenames are wrong, or your `ls` or similar just confused about the wrong locale?

**Comment by seadra** [comment]
Isn't it the moment you use a system call, you're using system locale? Like when you ask for the contents of a directory.

The filename was garbled in the web interface as well, and in fact syncthing got stuck with that file and sync never completely until I upgraded to 0.10.26 today.

BTW, I'm switching to LANG="en_US.UTF-8" on all machines to be on the safe side.

**Comment by calmh** [comment]
Got stuck how? Error messages may be useful and illuminating. Not sure about system calls etc, you haven't told us what operating this system is so it's hard to guess...

**Comment by seadra** [comment]
os.Readdirnames calls syscall.Getdents etc.

The UI didn't give any error messages at all. It just didn't sync for many days. The sync always tried to start over. I'm sorry, I don't have any logs from back then.

I actually mentioned that above. It's current Debian Linux. The arch is amd64.

**Comment by AudriusButkevicius** [comment]
You should use the `-b` switch for `ls` to show byte representations for the characters it cannot represent.
Do `LANG=POSIX ls -lab` on both sides, and compare if the byte representations are the same.
I assume they will be, and it's your terminal which is mangling them.

**Comment by seadra** [comment]
@AudriusButkevicius
As I mentioned, the problem is **gone** now.
