### ISSUE TITLE
setting syncthing to run on low priority

### ISSUE THREAD

**Issue by robsonsobral** [syncthing/syncthing#1455]
Hi!

I had to scan a huge folder and to set the syncthing process to run on low priority was the way for me to keep using my computer while that. This is the reason I didn't try to run it on my NAS yet.

Is it possible to add a `run on low priority` configuration right on syncthing? I don't even know if others operational system have this option.

thanks!

**Comment by AudriusButkevicius** [comment]
That's not really available for Windows in Go at the moment.
We could dwell down into the Win32 APIs again though.

Not sure how much value this adds, as the user can adjust this himself.

**Comment by robsonsobral** [comment]
The user can adjust it, yes, but using a not easy way and it have to be set again every time.

I think this could be interesting for all platforms, which implies, as you said, on custom code for every one of them.

**Comment by alex2108** [comment]
you could do something like `Start /low X:\Path\To\syncthing.exe` in a .bat file and run this

**Comment by robsonsobral** [comment]
Thanks, @alex2108, but I'm using Syncthing GTK.

**Comment by calmh** [comment]
This is very OS specific, i.e. basically every OS handles this a little bit differently, even the POSIX ones. I'm not opposed to a clean, self contained pull request but as it stands currently it's much easier to be agnostic of all this stuff and let whoever launches syncthing set the desired priorities in whatever way the OS prefers.

**Comment by rumpelsepp** [comment]
> This is very OS specific, i.e. basically every OS handles this a little bit differently

On linux one could add `Nice=xyz` to the systemd services. I can add it to the systemd section in the wiki.

**Comment by calmh** [comment]
Also, ionice.

**Comment by rumpelsepp** [comment]
AFAIK such a config value does not exist, maybe `IOSchedulingPriority` fits here as well? http://www.freedesktop.org/software/systemd/man/systemd.exec.html#IOSchedulingPriority=

**Comment by peterhoeg** [comment]
@rumpelsepp for systemd, the better option is:
```
IOSchedulingClass=idle
```

**Comment by rumpelsepp** [comment]
> The best option in my opinion is to leave it up to the user. 

Jep. I just suggest that we add it to the wiki.

**Comment by rumpelsepp** [comment]
@peterhoeg, from here: http://www.cyberciti.biz/tips/linux-set-io-scheduling-class-priority.html

> Idle : A program running with idle io priority will only get disk time when no other program has asked for disk io for a defined grace period. The impact of idle io processes on normal system activity should be zero. This scheduling class does not take a priority argument.

Idle seems to be a bad option. When your server does something else syncthing never gets disk access. Setting the priority within 7 available steps using `IOSchedulingPriority` seems to be better IMO. Correct me if I'm wrong.

**Comment by kozec** [comment]
> Thanks, @alex2108, but I'm using Syncthing GTK.

Adding some kind of daemon priority settings to ST-GTK shouldn't be hard, but I don't see how it would help you on your NAS box.

**Comment by robsonsobral** [comment]
Yeap, @kozec. This is the reason I asked for it on Syncthing, instead of on ST-GTK.

It would not help on NAS, but it would help on Windows.

---

Thinking a little, maybe to run on low priority should be the default behavior. Specifically on the first scan, the slowness of Syncthing is scary. The users who don't bother the scan eating all the CPU power are probably the ones who know how to change it. Maybe...

**Comment by ozra** [comment]
Think out of the "scheduling and OS prioritizing box" a little - could it not be implemented better and more simple with an "within application honored niceness"? Laying off a bit, not being so processing eager.

Simply adding a setting for a small sleep of x ms between processing files? That would reduce the "Jet Engine Syndrome" my computer fans suffers at the moment. Hard to sleep in the same room with two machines syncing, or pass the time with a movie.

 (I've just installed and am syncing giiiaant dirs, to give it an initial hard testing, comparing to Dropbox which I've "had to" use before..)

**Comment by joelmo** [comment]
On Linux I am using CPUSchedulingPolicy=batch, this will make the process to be scheduled less often but get longer time slices and is good for CPU bound processes. Syncthing is using alot of cpu time and usually tops when I look in my activity manager. On some issue here I read, it's bound to crypto and the scanner/tree walker. But it's maybe also related to my data, 244311 items, ~4.50 GiB.

**Comment by calmh** [comment]
I think this issue as described is out of scope. We may consider a scanner rate limit at some point, and we already have the transfer rate limit. Those can be used to limit resource usage internally, in addition to using the prioritization tools of the OS

**Comment by TamaHobbit** [comment]
So, can someone add some more explanation here or on the wiki?

I don't know how to use CPUSchedulingPolicy, and [it's not in the wiki](https://docs.syncthing.net/search.html?q=CPUSchedulingPolicy&check_keywords=yes&area=default); do I add a line to syncthing.service or something? I went for the "run as user service" option. And Syncthing spikes to 100% CPU usages occasionally, causing annoying jittery lag.

**Comment by TamaHobbit** [comment]
Once you know that file is called a "systemd service file", it's easy enough to google to [the page that explains the CPUSchedulingPolicy option](https://www.freedesktop.org/software/systemd/man/systemd.service.html), although I'm still not sure where to add what specifically.

**Comment by joelmo** [comment]
Create a service, and under [Service] section put:
CPUSchedulingPolicy=batch
IOSchedulingClass=idle

I use NixOS so I define services a bit differently..

**Comment by canton7** [comment]
> Create a service

Just to elaborate a bit:

1. If you installed Syncthing using a package manager, so the services are already installed, run `systemctl edit syncthing@.service` (or `systemctl edit --user syncthing.service`, if you're using the per-user service). [More details](https://docs.syncthing.net/users/autostart.html#debugging).
2. If you installed the systemd services yourself, [follow the instructions](https://docs.syncthing.net/users/autostart.html#using-systemd) but edit the files as you copy them to your system.

**Comment by peterhoeg** [comment]
Instead of editing the full service definition, it's better to simply use a drop-in fragment. Let's say you are running syncthing from a system user instance - you would do this:

```sh
mkdir -p $HOME/.config/systemd/user/syncthing.d
```

Then create a file named ```priority.conf``` inside the directory created above with the following contents:

```ini
[Service]
IOSchedulingClass=idle
```

You can substitute the ```IOSchedulingClass``` or ```idle``` parts for any other configuration stanza.

Run:

```sh
systemctl --user daemon-reload
systemctl --user restart syncthing
```

Any changes to the upstream configuration will still be handled automatically as you are not overriding the whole config file.

**Comment by canton7** [comment]
> Instead of editing the full service definition, it's better to simply use a drop-in fragment.

Isn't that what `systemctl edit` does, but without all the manual file creation? :smile:

**Comment by peterhoeg** [comment]
Indeed it is @canton7, thanks. ```systemctl edit``` used to override the whole file, but now it seems it requires the ```--full``` parameter to do so. Learning every day...

**Comment by TamaHobbit** [comment]
`systemctl edit` just says "Unknown operation 'edit'."

I followed ["How to set up a user service"](https://docs.syncthing.net/users/autostart.html#using-systemd), but I don't know how I would be able to tell this for debian jessie (stable): "If your distro provides a systemd service file for Syncthing, you can skip step 2" - if it's shipped, should the file already exist then? I probably have to dig into how systemd works to see if I have it configured doubly, which is a shame since the default installation should just not have such high priority; I should only have to configure the service if I want to run a dedicated syncthing machine and need high priority.

**Comment by calmh** [comment]
Systemd operations help is out of scope here. A pull request to tweak our defaults to set a lower priority directly in our shipped systemd units would be fine and welcome though.
