### ISSUE TITLE
Symlinks are disabled, unsupported or require Administrator priviledges. This might cause your folder to appear out of sync

### ISSUE THREAD

**Issue by frank-github** [syncthing/syncthing#1456]
syncthing instance running on windows XP
Syncthing v0.10.26

what will this warning say?
syncthing is running as system service, so it has administration priviledges  :(

**Comment by AudriusButkevicius** [comment]
Sadly WinXP does not have symlinks.

**Comment by frank-github** [comment]
Hmm, is it neccessary to get this warning each time I use web frontend ?

**Comment by AudriusButkevicius** [comment]
Well your folders contain symlinks, which can cause stuff to look out of sync.
I rather you know about that, oppose to start opening issues saying `Syncthing never gets to 100%`
It's only shown once after syncthing has been restarted.
