### ISSUE TITLE
Simplified Chinese garbled

### ISSUE THREAD

**Issue by mapleshadow** [syncthing/syncthing#1459]
Simplified Chinese garbled
Folder, host name, as long as it is simplified Chinese will become a symbol:?

**Comment by AudriusButkevicius** [comment]
Where? In the web UI? Or files that you are syncing?

A screenshot would help.

**Comment by mapleshadow** [comment]
sorry...........
is phone app error..........
Excuse me, is this your application development?

![screenshot_2015-03-13-22-54-50](https://cloud.githubusercontent.com/assets/525478/6640709/16d0f0ee-c9d4-11e4-8637-894c23b35b8f.png)

**Comment by dzarda** [comment]
I see that you have opened a duplicate issue on [syncthing/syncthing-android](https://github.com/syncthing/syncthing-android/issues/237). I vote to close this one, since I'd bet my bottom dollar it's related to the android app.

**Comment by AudriusButkevicius** [comment]
Yeah, I think it's Android only.
We have Chinese translations for the web UI, hence it should work.
