### ISSUE TITLE
How long should discovery take?

### ISSUE THREAD

**Issue by OIWitteveen** [syncthing/syncthing#1460]
Hi, i installed Synctrayzor yesterday and added a device. But neither SyncTrayzor or the new devive shows that a a device is trying to sync a new folder. I tried Host > Android device and Host > Raspberry Pi.
Both RPi en Android don't notice a difference.

I also tried the other way around adding a the "host" on Android and RPi.

NOTE: This is for global detection. Local(LAN) detection works ok.
I installed synctrayzor using the windows x64 installer to default location.
I am running Windows 8.1 x64.

**Comment by AudriusButkevicius** [comment]
Well it should be pretty much instant.
If both sides of the connection are behind a NAT and there is no UPnP (or UPnP fails) you will not be able to connect.

See: https://github.com/syncthing/syncthing/wiki/Firewalls-and-Port-Forwards
