### ISSUE TITLE
Unable to remove device

### ISSUE THREAD

**Issue by Rotkaermota** [syncthing/syncthing#1462]
there are 5 devices: AAA, BBB, CCC, DDD, EEE. When i delete device AAA from device BBB, after restart syncthing of BBB and connect other devices (where AAA device not yet deleted), it returns back to list of device BBB. Same behaviour when Idelete AAA from CCC, or from DDD. AAA always return

**Comment by AudriusButkevicius** [comment]
Make sure other devices are not marked as introducers.

**Comment by Rotkaermota** [comment]
I should unmark introducer on all devices, remove unused device (because hardware is dead), then mark devices as intriducer again (because introducer is good feature). Ok. Good user experience...

**Comment by AudriusButkevicius** [comment]
I know it's terrible, and I am very sorry about that, but that's a separate issue at #1015 

Given devices now prompt when connecting to each other, perhaps you should try relying on that.
