### ISSUE TITLE
can't add server device with Nexus 5

### ISSUE THREAD

**Issue by fobe** [syncthing/syncthing#1464]
Hi,
I just did a fresh reset of my Nexus 5 with Lollipop 5.1. I installed Syncthing and wanted to add the server. I can scan the server ID and fill in the name but when it want's to restart it does nothing.
I tried to exit the app and try it again but it won't add the server. Then i tried to clear the cache and let it generates new keys but no luck. Still unable to add the server...
The server and Nexus 5 have the latest version of Syncthing.

I now tried Android Version 0.5.18 and that works...
https://github.com/syncthing/syncthing-android/issues/245

**Comment by AudriusButkevicius** [comment]
Is that through the web ui?

**Comment by fobe** [comment]
nope. within the android app, add device and then scan he QR from the web page of the server.

**Comment by AudriusButkevicius** [comment]
Ok, then this is not an issue in syncthing, rather than syncthing-android, which you seem to have already opened an issue for.
