### ISSUE TITLE
Recent changes causing syncthing and syncthing-gtk UI errors

### ISSUE THREAD

**Issue by dcarosone** [syncthing/syncthing#1467]
I'm getting a collection of errors when trying to run syncthing (browser interface) or syncthing-gtk and make configuration changes, such as adding a new device.  

It seems to have started with an update overnight to 0.10.26.  This is on ubuntu, via the ppa, so the previous version was a little older (I think 21 or 22 from memory?)

There seems to be a json parsing problem, but there's not much more specific than that in the error message.  I would have guessed that syncthing and -gtk got slight skew with a minor api change, except that it also happens for the browser interface.

![screenshot from 2015-03-16 13 43 19](https://cloud.githubusercontent.com/assets/11495017/6659924/6683d4ce-cbe3-11e4-8a87-bd6ae72da259.png)
![screenshot from 2015-03-16 13 44 30](https://cloud.githubusercontent.com/assets/11495017/6659925/66861658-cbe3-11e4-87a2-7ada69e66461.png)
![screenshot from 2015-03-16 13 44 40](https://cloud.githubusercontent.com/assets/11495017/6659926/66893fea-cbe3-11e4-95ec-af8cd8f7cddd.png)

**Comment by pinapl** [comment]
I didn't even see that much; When I upgraded, the upgrade seemed to take forever, and any connection attempts after the upgrade started showed a barebones GUI with no device or folder info. I have HTTPS enabled.
I downgraded to V0.10.26 and disabled upgrades, and now the GUI works fine. Syncthing will try to upgrade when you start it, so disable automatic upgrades by editing the config file. Edit config.xml, modify `<autoUpgradeIntervalH>12</autoUpgradeIntervalH>` to be `<autoUpgradeIntervalH>0</autoUpgradeIntervalH>`. (Change the 12 to 0)

Locations I've seen the file in:
Ubuntu Linux: `~/.config/syncthing/config.xml`
Windows 8.1: `C:\Users\<User>\AppData\Local\Syncthing\config.xml`

**Comment by dcarosone** [comment]
It appears to be related to devices.
 * a second ubuntu machine, also updated today, but with more existing config, seems to work for exsiting sync pairings, but I can't add a new device
 * the android GUI is not showing any devices at all.  A recent update there said something like "don't abort on JSON errors", so it's not just me :)

**Comment by AudriusButkevicius** [comment]
Are you running behind a proxy?

**Comment by dcarosone** [comment]
Seems to be related: https://github.com/syncthing/syncthing-android/issues/239

So as per previous point, is the web UI also out of sync with this api change?

**Comment by dcarosone** [comment]
> Are you running behind a proxy?

Nope. A firewall prevents outbound access to global discovery (which shouldn't be relevant), but no proxy is configured in either the browser or syncthing-gtk's environment.

**Comment by AudriusButkevicius** [comment]
I think it sometimes slow to start, but I feel that it's two separate issues we are discussing about though.

@dcarosone what is Chrome's debug tools showing for requests when it pops up the red warning? Can you see which requests are failing?

**Comment by dcarosone** [comment]
Oh.  Looking with firebug:
![screenshot from 2015-03-17 09 54 06](https://cloud.githubusercontent.com/assets/11495017/6678200/b9d62908-cc8b-11e4-8687-a4526a89b8d9.png)

That would be a problem..

Also, a little later, 

![screenshot from 2015-03-17 09 56 12](https://cloud.githubusercontent.com/assets/11495017/6678214/e26afb00-cc8b-11e4-99b0-47d5852a988f.png)

**Comment by dcarosone** [comment]
Yeah, there's no CSRF data in the POST, that I can see.

**Comment by dcarosone** [comment]
Ok, partial PEBCAK.  The browser UI was broken by my cookie filter not matching all the forms of 'localhost'.

Web UI seems to work now, which just leaves syncthing-gtk as probable version skew.

**Comment by dcarosone** [comment]
Android has just had a commit to close the issue referenced above.  Going to close this, and raise something specific for syncthing-gtk in case it's not already known there.
