### ISSUE TITLE
GUI: Suppress Folder Master related info if Folder Master

### ISSUE THREAD

**Issue by sciurius** [syncthing/syncthing#1472]
The GUI info for a repository includes Folder Master and Last File Received. When a node is not folder master, the info for Folder Master is suppressed but the Last File Received still shows.
It would be very nice (enhancement) if Last File Received were also suppressed in this case, since it doesn't makes sense.

**Comment by calmh** [comment]
Why would it not make sense?

**Comment by AudriusButkevicius** [comment]
I have given an explicit reason why it still made sense on the forum.

**Comment by sciurius** [comment]
The reason: "Master mode can be toggled, hence last received file can still make perfect sense."

However, toggling master mode will bring the info back so I don't see the problem hiding it.

**Comment by sciurius** [comment]
PR request issued. Feel free to accept or reject. No big deal.

**Comment by calmh** [comment]
Ah. It makes more sense in the code, the subject here is inverted. You are *suppressing* "Last File Received" if the device *is* Folder Master.

**Comment by sciurius** [comment]
Rebased, squashed, pushed. Hope it's better now.

**Comment by sciurius** [comment]
Notice: this does not work yet in 0.10.29 due to a camelCase conflict, but is okay in HEAD.
