### ISSUE TITLE
Assets generation includes editor backup files.

### ISSUE THREAD

**Issue by sciurius** [syncthing/syncthing#1476]
When during development gui files are modified with an Emacs compliant editor, the editor backup files (filenames with a tilde appended) are included by genassets. These files should be skipped.

A simple fix is to include the following lines in function walkerFor in cmd/genassets/main.go:

		if strings.HasSuffix(name, "~") {
			// Skip editor backup files
			return nil
		}

Before issuing a pull request for this, it may be worth to consider to make the generation process a bit more restrictive, i.e. exclude more temp/backup rubbish, or even restrict to a known set of file names/types.

**Comment by calmh** [comment]
Don't generate rubbish and it's solved automatically ;)

But yeah, we could add something like that. It's all just developer stuff so it doesn't matter too much. Ideally it'd follow the `.gitignore` but that may be more annoying to implement...

(I usually just look at the diff and make sure crap isn't included in the commit)

**Comment by calmh** [comment]
Potentially `git ls-files` could be used to get the file list...

**Comment by sciurius** [comment]
Using git ls-files would make it impossible to build outside of the git environment. However, we could use `git ls-files gui` to produce a file list (e.g. `gui/.files`) and check that one in.

**Comment by AudriusButkevicius** [comment]
I don't see how this is fixable. Depending on which editor I use I get,  `file.backup`, `file.hist`, `file.temp` etc.

**Comment by sciurius** [comment]
Yes. I think Jacob's idea to use git ls-files would be the best approach.

**Comment by calmh** [comment]
You wouldn't need `git ls-files` to build though, just to regenerate the built in assets. Which is a developer task, and should certainly only be done by people who have git around.
