### ISSUE TITLE
add configuration / command line option to specify location of cert bundle

### ISSUE THREAD

**Issue by lhoekenga** [syncthing/syncthing#1479]
I would like to be able to specify the name / location of the certificate bundle instead of having to rely on the "known locations" from the OSs / distros that syncthing is aware of.  

I'm trying the ARM version on a DroboFS, and it didn't have a cert bundle by default.  I got syncthing to start by adding a bundle to a location I knew it would check, but having the option to specify it would be nice.

**Comment by calmh** [comment]
Indeed. This is however not something we can fix from the outside, as it's part of the Go runtime.

**Comment by calmh** [comment]
This is now supported by Go natively (https://go-review.googlesource.com/c/go/+/36093/)
