### ISSUE TITLE
>2k .ldb files in %localappdata%/syncthing/index/

### ISSUE THREAD

**Issue by Zixim** [syncthing/syncthing#1480]
in reference to https://discourse.syncthing.net/t/2400-ldb-files/2131/5
win 7, ST v0.10.27

After scanning has completed, expected behaviour is to have about 2 dozen .ldb files.
I have more than 2000 .ldb files in the index folder, 

Also, possibly as result of the above if it thinks it needs to go through 2k index files, syncthing is very sluggish starting up, taking minutes before launching the browser to display the webif.

LOG from index folder : http://pastebin.com/kZLHuyeZ
folder contents  : http://pastebin.com/mnujx9M3

**Comment by AudriusButkevicius** [comment]
Is it still there after some time?

**Comment by Zixim** [comment]
yes.
in fact, it's growing !
up to 3200  ldb files as we speak.

**Comment by Zixim** [comment]
just adding info : I have left this host in peace overnight, disconnected from any other ST hosts.
It has completely settled.
There's a "stable" number of files in the index folder, 2419 of them.
Oldest are 10 days old, most recent are 6h old.
The vast majority are <24h old.

**Comment by Zixim** [comment]
is bumping allowed?

**Comment by AudriusButkevicius** [comment]
It usually has no effect.

**Comment by AudriusButkevicius** [comment]
Perhaps @syndtr has any idea.
I am not familiar with leveldb internals enough to comment.

**Comment by syndtr** [comment]
The delete entries seems to get build up and not getting compacted.
@Zixim could you post MANIFEST-xxxx file? Thanks

**Comment by Zixim** [comment]
MANIFEST file : https://drive.google.com/file/d/0BwCQHV7z4Tg4U245SXZtN1hDVzQ/view?usp=sharing

please note, I have migrated the original install onto fresh hardware, and the behaviour is still present, although less exaggerated.

The .ldb files are stable at just below 2000, but this still seems like a high number, thank god the OS drive is SSD, but even then, starting Syncthing is a work of patience :(

**Comment by AudriusButkevicius** [comment]
I think it might only be included in the v0.11-beta1 or once it's out of the beta.
