### ISSUE TITLE
Poor performance on Raspberry refreshing webpage on laptop

### ISSUE THREAD

**Issue by dinosore** [syncthing/syncthing#1481]
Running Syncthing v0.10.27 on a Raspberry Pi model B using Raspbian Jessie and turbo config.

The Pi is run headless over ssh with no GUI.

Syncthing webgui run from a Win7pro laptop over local network.

With no peers connected to the pi and Syncthing fully running, I ran mpstat 1 to monitor cpu idle.

It was then running 96-100% idle.

I refreshed the webgui page on the laptop.

CPU idle went to 100% for approximately 33 seconds.

I repeated the test and the timing was similar.

**Comment by calmh** [comment]
Yep. #867

**Comment by dinosore** [comment]
Hi Jakob

 

I saw #1481 before I posted this (in fact, I checked at least the title of all open bugs).

 

The symptoms are very different.  Without knowledge of the code, I cannot say whether the cause is the same.

 

I didn’t find performance slowed when the webgui was running, merely when I manually refreshed the webpage on the laptop.

 

N.B. I don’t have a gui or a web browser installed on the laptop.

 

The issue is very different – it has nothing to do with the webgui on the Pi

 

David.

**Comment by dinosore** [comment]
I saw #1481 before I posted this (in fact, I checked at least the title of all open bugs).

The symptoms are very different.  Without knowledge of the code, I cannot say whether the cause is the same.

I didn’t find performance slowed when the webgui was running, merely when I manually refreshed the webpage on the laptop.

N.B. I don’t have a gui or a web browser installed on the laptop.

The issue is very different – it has nothing to do with the webgui on the Pi

**Comment by AudriusButkevicius** [comment]
Sorry, how is this different?
The fact that the PI has to do work to provide information to the UI is the cause.

**Comment by dinosore** [comment]
If the cause is the same and it's being addressed, I'm happy with closure.

**Comment by calmh** [comment]
Yep, it's the same. The reload shows it more clearly, but just having the UI open while stuff is happening (so that the UI is doing automatic reload of a few things) causes the same.
