### ISSUE TITLE
Continuous panics: input/output error on v0.10.27

### ISSUE THREAD

**Issue by dmS0Zq** [syncthing/syncthing#1483]
Running v0.10.27 on Linux example.com 3.2.0-4-amd64 #1 SMP Debian 3.2.54-2 x86_64 GNU/Linux

panic: read /media/sdb1/home/xxxxxxxx/.config/syncthing/index/001187.ldb: input/output error

http://pastebin.com/T5A7UjDJ

**Comment by dmS0Zq** [comment]
All 207 .ldb files in ~/.config/syncthing/index are owned by the user and group "xxxxxxx" and have permissions 600.

**Comment by Zillode** [comment]
Have a look at the output of ```dmesg```, I guess your drive is failing?

**Comment by AudriusButkevicius** [comment]
Feels like it.

**Comment by dmS0Zq** [comment]
Thanks for the input. I forgot to mention, this is a shared system and I do not have root/super user access.

From the output of dmesg, it looks like you may be right. The way the sysadmin mounted my home folder was confusing me. I'm on `/media/sdb1/...` but that is drive/partition `/dev/sdaj1`. Watching dmesg while starting syncthing up, I see this: http://pastebin.com/UNDNtH6c

I will contact the sysadmin. If it is okay, I'll keep the issue open until I hear back.

**Comment by kozec** [comment]
That log O.o
Backup everything you can...

**Comment by dmS0Zq** [comment]
Confirmed as a bad drive. Thanks for the help @Zillode and @AudriusButkevicius. Now just need to wait for sysadmins to migrate me to a different drive.
