### ISSUE TITLE
partialy dupplicate transfer on copying big file

### ISSUE THREAD

**Issue by rudevel** [syncthing/syncthing#1485]
*Szenario:*
Folder is synced and IN SYNC between 3 local Computers- all having syncthing v0.10.27.
Folder contains ONE File with 2.1 GB in size.

*Reproduction:*
Copy the file within the folder e.g. 
cp bigfile.tar.gz bigfile.tar.gz.dup
(my guess: don't use the fastest HDD there is..)

*Observation:*
- On one client (Raspberry Pi 2) syncing starts with
.syncthing.bigfile.tar.gz.dup
constantly increasing it's size.

- About half way (777MB on my simulation) the file is then renamed into
bigfile.tar.gz.dup
as if it were done. But within short a new .syncthing.bigfile.tar.gz.dup is created.
It starts from the beginning and is blown up full size while the original file is unchanged.
Finally it replaces the first file, now beeing the full sized copy.

*Problem:*
Even if the first transfer was a valid "first copy" of the file, a retransmission of the whole 700+MB shouldn't happen acording to the [1] linked discussion.

*Possible Cause:*
- One guess could be the 2nd Machine having finished the transfer much faster and conflict somehow with the existing transfer.
- It might also be that the slow HDD- (Bus) Speed of the RasPI2 covers the fact that the data IS in fact copied (~7MB/s transfer vs. ~11MB/s copy), but for that- not too rare case- it would be better to skip the start and put the new file-portion on top of the original file uppon finishing the transfer.

*Recommended Solution:*
Avoid FINISHING (removing ".syncthing."- prefix)  the transfer of a file still beeing in constant change like when it is still copied from source.

*Last but not least:*
Great tool, great job, big potential!

[1] https://discourse.syncthing.net/t/better-delta-sync-algorithm-like-rsync/984/8

**Comment by AudriusButkevicius** [comment]
I feel your RPI is just slow, it we finished scanning the file first before it finished copying. I am sort of sure that we did not transfer the 700mb (perhaps just one 128kb block) and that we didn't transfer the 2.1gb afterwards. We cannot wait for the file to stop changing because what if it never stops changing? I feel this is a won't fix, as it doesn't seem to be broken to start with? Your stuff gets in sync, and your problem seems to be caused be weak devices.

**Comment by rudevel** [comment]
Well, you made a point here!
Maybe I should have stoped posting this issue when it came to mind the data was copied and not transfered. Still don't love the idea of unfinished syncs, but it's for sure better than no sync at all.

**Comment by AudriusButkevicius** [comment]
It's not really unfinished as far as we are concerned, as we take a snapshot of what's there at that moment and assume that's what it is. If it changes later, we sync it to match the later state.

There is very little cost involved in having to sync the file twice (given it's part of a copy of some existing).
Even if the file is not a copy, we don't redownload data we already have, therefore I am not sure why you are concerned.

I guess we could do something more clever, such as refusing to sync a file while it's size is changing, but this would break syncing logs and other files which can be constantly changing in size. 
But under your terms it could be considered an unfinished sync forever, as we'd always be playing the catch-up game.

**Comment by rudevel** [comment]
Fully understand this. 
Thats why i closed this issue and agree that a snapshot is better than waiting for whatever timing seems suitable to separate "finished" from "unfiinished". 

*I am convinced, not disappointed* ;)
