### ISSUE TITLE
What are allowed characters?

### ISSUE THREAD

**Issue by maikeldus** [syncthing/syncthing#1486]
So i recieved a lot of messages like these:
```
File name "Alex NEGNIY/Alex NEGNIY - Trance Air #151 [TOP10 of SEPTEMBER 2014 & Guest mix: Anna Lee].mp3" contains invalid characters; marked as invalid.
```
I'm syncing from a Rpi (with Raspbian) to my desktop (Windows 7) and saw some other topics about character issues, but I could not find what characters actually work? On what character is Syncthing failing in this example above?

**Comment by kozec** [comment]
: in this case. Windows can't handle those.
