### ISSUE TITLE
REST API collection inconsistencies

### ISSUE THREAD

**Issue by kreischweide** [syncthing/syncthing#1487]
As I'm currently implementing a native client against the REST API, I found a conflict in the current formatting of lists/arrays/collections in various calls.

Lets take /rest/connections

```
{  
   "SJ3BZVN":{  
      "At":"2015-03-18T21:56:46.6428785+01:00",
      "InBytesTotal":4758908,
      "OutBytesTotal":4758728,
      "Address":"192.168.79.45:54689",
      "ClientVersion":"v0.10.27"
   },
   "total":{  
      "At":"2015-03-18T21:56:46.6428785+01:00",
      "InBytesTotal":14348332,
      "OutBytesTotal":14278380,
      "Address":"",
      "ClientVersion":""
   }
}
```

There is a conflict that complicates the processing of the records. SJ3BZVN should be in an array of connections, where total is at the right place. Right now I can map the total result because I know its name. To get actual connections I need to iterate trough the whole thing and exclude total from it (which is not a connection, but a summary). Also I can no longer use automatic mapping as the key is unknown at runtime and no other call offers a correct list of IDs, so I need to write a custom JSON deserializer for this call.

I would propose to change it to the same clean structure as /rest/ignores, /rest/need, /rest/errors and others:

```
{  
   "connections":[  
      {  
         "ID":"SJ3BZVN",
         "At":"2015-03-18T21:56:46.6428785+01:00",
         "InBytesTotal":4758908,
         "OutBytesTotal":4758728,
         "Address":"192.168.79.45:54689",
         "ClientVersion":"v0.10.27"
      }
   ],
   "total":{  
      "At":"2015-03-18T21:56:46.6428785+01:00",
      "InBytesTotal":14348332,
      "OutBytesTotal":14278380,
      "Address":"",
      "ClientVersion":""
   }
}
```

Same also applies, sooner or later, to
```
/rest/system > extAnnounceOK
/rest/discovery
/rest/tree
```

as well as possible POST calls (havent looked at them yet).

Any other ideas?

**Comment by calmh** [comment]
Agreed about `connections`, haven't looked at the others yet. I don't see any reason to avoid dictionaries as structures (they are useful), but we should not mix random keys like device ID:s with known keys like "total" in the same dict.

**Comment by calmh** [comment]
Ideally we do whatever tweaks we want to do this week, before releasing the updated REST stuff into the wild.

**Comment by canton7** [comment]
While I agree with the restructuring, Json.NET's `JsonExtensionDataAttribute` makes deserializing this easy:

```csharp
public class Connections
    {
        [JsonProperty("total")]
        public ItemConnectionData Total { get; set; }

        [JsonExtensionData]
        public Dictionary<string, JToken> DeviceConnectionsRaw { get; set; }

        private Dictionary<string, ItemConnectionData> _deviceConnections;
        public Dictionary<string, ItemConnectionData> DeviceConnections
        {
            get
            {
                if (this._deviceConnections == null)
                {
                    this._deviceConnections = this.DeviceConnectionsRaw == null ?
                        new Dictionary<string, ItemConnectionData>() :
                        this.DeviceConnectionsRaw.ToDictionary(x => x.Key, x => x.Value.ToObject<ItemConnectionData>());
                }
                return this._deviceConnections;
            }
        }
    }
```

Beware DeviceConnections will be null

**Comment by kreischweide** [comment]
Thanks for the hint! I'm doing 

```
var result = JsonConvert.DeserializeObject<Dictionary<string, ItemConnectionData>>(response.Content);
```

now and just filtering by key. Just workarounds though :) Did not make much progress on a possible transformation of the REST APIs, Go is not to be learned on a single day.

**Comment by canton7** [comment]
That's probably a neater way of doing it, to be honest!

**Comment by canton7** [comment]
Has this changed to:
```json
{  
   "connections":[  
      {  
         "ID":"SJ3BZVN",
         "At":"2015-03-18T21:56:46.6428785+01:00",
         "InBytesTotal":4758908,
         "OutBytesTotal":4758728,
         "Address":"192.168.79.45:54689",
         "ClientVersion":"v0.10.27"
      }
   ],
   "total":{  
      "At":"2015-03-18T21:56:46.6428785+01:00",
      "InBytesTotal":14348332,
      "OutBytesTotal":14278380,
      "Address":"",
      "ClientVersion":""
   }
}
```

or:

```json
{  
   "connections": {  
      "SJ3BZVN": {  
         "At":"2015-03-18T21:56:46.6428785+01:00",
         "InBytesTotal":4758908,
         "OutBytesTotal":4758728,
         "Address":"192.168.79.45:54689",
         "ClientVersion":"v0.10.27"
      }
   },
   "total":{  
      "At":"2015-03-18T21:56:46.6428785+01:00",
      "InBytesTotal":14348332,
      "OutBytesTotal":14278380,
      "Address":"",
      "ClientVersion":""
   }
}
```

My Go isn't good enough to figure it out from the patch...

**Comment by AudriusButkevicius** [comment]
the 2nd

**Comment by canton7** [comment]
Thanks!
