### ISSUE TITLE
Show Device ID QR code in "Edit Device" popup

### ISSUE THREAD

**Issue by blakev** [syncthing/syncthing#1494]
I'm suggesting the ability to generate the QR code for a device you've added that isn't the ID of the device you're on. For example...

![Example Flow](http://i.imgur.com/I392jhD.png)

This would allow adding a remote server/device to a phone much easier if you're unable to pull up the screen on the server machine.

**Comment by Zillode** [comment]
I like the idea, feel free to submit a pull request

**Comment by blakev** [comment]
I made the change...it's like two lines in index.html; but I can't build the project on my machine to test it.

I think there's something wrong with my `GOPATH` or maybe it's a Windows thing? I dunno...golang incompetence wasn't covered in [the guide](https://github.com/syncthing/syncthing/wiki/Building) :)
        D:\projects\github\syncthing\syncthing>go run build.go build
        GOPATH is D:\
        rm -r syncthing.exe
        rm -r syncthing.exe.md5
        GOPATH=D:\projects\github\syncthing\syncthing\Godeps\_workspace;D:\
        go build -ldflags -w -X main.Version v0.10.27+25-g5c026cb -X main.BuildStamp 1426770167 -X main.BuildUser blake_desktop\
        Blake -X main.BuildHost BLAKE_DESKTOP -X main.BuildEnv default ./cmd/syncthing
        cmd\syncthing\gui.go:27:2: cannot find package "github.com/syncthing/syncthing/internal/auto" in any of:
                C:\Go\src\github.com\syncthing\syncthing\internal\auto (from $GOROOT)
                D:\projects\github\syncthing\syncthing\Godeps\_workspace\src\github.com\syncthing\syncthing\internal\auto (from
        $GOPATH)
                D:\src\github.com\syncthing\syncthing\internal\auto
        cmd\syncthing\gui.go:28:2: cannot find package "github.com/syncthing/syncthing/internal/config" in any of:
                C:\Go\src\github.com\syncthing\syncthing\internal\config (from $GOROOT)
                D:\projects\github\syncthing\syncthing\Godeps\_workspace\src\github.com\syncthing\syncthing\internal\config (fro
        m $GOPATH)
                D:\src\github.com\syncthing\syncthing\internal\config
        cmd\syncthing\gui.go:29:2: cannot find package "github.com/syncthing/syncthing/internal/db" in any of:
                C:\Go\src\github.com\syncthing\syncthing\internal\db (from $GOROOT)
                D:\projects\github\syncthing\syncthing\Godeps\_workspace\src\github.com\syncthing\syncthing\internal\db (from $G
        OPATH)
                D:\src\github.com\syncthing\syncthing\internal\db
        cmd\syncthing\gui.go:30:2: cannot find package "github.com/syncthing/syncthing/internal/discover" in any of:
                C:\Go\src\github.com\syncthing\syncthing\internal\discover (from $GOROOT)
                D:\projects\github\syncthing\syncthing\Godeps\_workspace\src\github.com\syncthing\syncthing\internal\discover (f
        rom $GOPATH)
                D:\src\github.com\syncthing\syncthing\internal\discover
        cmd\syncthing\connections.go:18:2: cannot find package "github.com/syncthing/syncthing/internal/events" in any of:
                C:\Go\src\github.com\syncthing\syncthing\internal\events (from $GOROOT)
                D:\projects\github\syncthing\syncthing\Godeps\_workspace\src\github.com\syncthing\syncthing\internal\events (fro
        m $GOPATH)
                D:\src\github.com\syncthing\syncthing\internal\events
        cmd\syncthing\connections.go:19:2: cannot find package "github.com/syncthing/syncthing/internal/model" in any of:
                C:\Go\src\github.com\syncthing\syncthing\internal\model (from $GOROOT)
                D:\projects\github\syncthing\syncthing\Godeps\_workspace\src\github.com\syncthing\syncthing\internal\model (from
         $GOPATH)
                D:\src\github.com\syncthing\syncthing\internal\model
        cmd\syncthing\gui.go:33:2: cannot find package "github.com/syncthing/syncthing/internal/osutil" in any of:
                C:\Go\src\github.com\syncthing\syncthing\internal\osutil (from $GOROOT)
                D:\projects\github\syncthing\syncthing\Godeps\_workspace\src\github.com\syncthing\syncthing\internal\osutil (fro
        m $GOPATH)
                D:\src\github.com\syncthing\syncthing\internal\osutil
        cmd\syncthing\main.go:37:2: cannot find package "github.com/syncthing/syncthing/internal/symlinks" in any of:
                C:\Go\src\github.com\syncthing\syncthing\internal\symlinks (from $GOROOT)
                D:\projects\github\syncthing\syncthing\Godeps\_workspace\src\github.com\syncthing\syncthing\internal\symlinks (f
        rom $GOPATH)
                D:\src\github.com\syncthing\syncthing\internal\symlinks
        cmd\syncthing\gui.go:34:2: cannot find package "github.com/syncthing/syncthing/internal/upgrade" in any of:
                C:\Go\src\github.com\syncthing\syncthing\internal\upgrade (from $GOROOT)
                D:\projects\github\syncthing\syncthing\Godeps\_workspace\src\github.com\syncthing\syncthing\internal\upgrade (fr
        om $GOPATH)
                D:\src\github.com\syncthing\syncthing\internal\upgrade
        cmd\syncthing\main.go:39:2: cannot find package "github.com/syncthing/syncthing/internal/upnp" in any of:
                C:\Go\src\github.com\syncthing\syncthing\internal\upnp (from $GOROOT)
                D:\projects\github\syncthing\syncthing\Godeps\_workspace\src\github.com\syncthing\syncthing\internal\upnp (from
        $GOPATH)
                D:\src\github.com\syncthing\syncthing\internal\upnp
        exit status 1
        exit status 1

**Comment by AudriusButkevicius** [comment]
use `./build.sh assets; ./build.sh`

**Comment by blakev** [comment]
hmm...`build.sh assets` seemed to work, but not the second.

Go binary is in, `C:\Go\bin`
Project is in, 'D:\projects\github\syncthing`

...anything else I should try or be aware of?

Really regretting not playing with Go before now.

**Comment by AudriusButkevicius** [comment]
What is the error you are getting when running build?

**Comment by blakev** [comment]
D:\projects\github\syncthing\syncthing>build.sh

        Welcome to Git (version 1.9.0-preview20140217)

        Run 'git help git' to display the help index.
        Run 'git help <command>' to display help for specific commands.
        GOPATH is D:\
        GOPATH=D:\projects\github\syncthing\syncthing\Godeps\_workspace;D:\

        go install -v -ldflags -w -X main.Version v0.10.27+25-g5c026cb-dirty -X main.BuildStamp 1426770167 -X main.BuildUser blake_desktop\Blake -X main.BuildHost BLAKE_DESKTOP -X main.BuildEnv default ./cmd/...

        cmd\stcompdirs\main.go:19:2: cannot find package "github.com/syncthing/syncthing/internal/symlinks" in any of:
                C:\Go\src\github.com\syncthing\syncthing\internal\symlinks (from $GOROOT)
                D:\projects\github\syncthing\syncthing\Godeps\_workspace\src\github.com\syncthing\syncthing\internal\symlinks (from $GOPATH)
                D:\src\github.com\syncthing\syncthing\internal\symlinks
        cmd\stfileinfo\main.go:16:2: cannot find package "github.com/syncthing/syncthing/internal/scanner" in any of:
                C:\Go\src\github.com\syncthing\syncthing\internal\scanner (from $GOROOT)
                D:\projects\github\syncthing\syncthing\Godeps\_workspace\src\github.com\syncthing\syncthing\internal\scanner (from $GOPATH)
        ...
        ...
        exit status 1
        exit status 1

**Comment by AudriusButkevicius** [comment]
Right, you cannot build go code like that, I know it's annoying.
In needs to be in src/github.com/syncthing/syncthing/
For example D:/projects/go/src/github.com/syncthing/syncthing/
Then you need to set GOPATH=D:/projects/go

**Comment by nottinhill** [comment]
Tons of Devs have experiencing builing Syncthing on their servers. The forums and Web is full of it. 

Are you planning on ameliorating your documentaiton on the build process? As it stands it can safely regarded as useless. 

Thanks for understanding

**Comment by AudriusButkevicius** [comment]
https://github.com/syncthing/syncthing/wiki/Building
https://github.com/syncthing/syncthing/wiki/Building-with-Docker
And in general: `./build.sh` usually just works.

Tons of devs are not reading the wiki then I guess.

**Comment by nottinhill** [comment]
Sorry to say but the Installation Guide is useless. Good luck with your project anyway.

**Comment by nottinhill** [comment]
The Guide you linked to won't work. Did you read my blog. I face so many errors, exceeding the amount of fingers on both my hands.

**Comment by AudriusButkevicius** [comment]
More than 80% of your blog post is about building Go 1.4, which we don't really have control off.
Hence why we provide the docker container so that you could skip all of that.

Regarding the error you are getting, I suggest you try building the v0.10 branch which is supposed to be stable, and not master, as that's definitely unstable.

**Comment by nottinhill** [comment]
> # This should output "go version go1.3" or higher.
-- Official Syncthing Wiki

**Comment by AudriusButkevicius** [comment]
That's not true, we build it with 1.4 for official releases, and I build it with 1.4.1 or even tip of go in dev

**Comment by nottinhill** [comment]
Didn't you just say 1.4 is a bad idea?

**Comment by AudriusButkevicius** [comment]
Where did I say that?
