### ISSUE TITLE
panic log (deadlock detected)

### ISSUE THREAD

**Issue by Zixim** [syncthing/syncthing#1495]
as requested in the forum, i'm posting this here.
https://discourse.syncthing.net/t/deadlock-detected-panic-log/2156

**Comment by calmh** [comment]
This looks like hardware or OS issues to me, as it seems we are blocking forever to read a block or two from disk...

**Comment by Zixim** [comment]
yes, i agree.
While waiting for a response to my post I ran a deep diagnostic of the OS drive.
The drive is dying.
