### ISSUE TITLE
unplugging a removal drive should not mass delete everything in a share

### ISSUE THREAD

**Issue by lex148** [syncthing/syncthing#1496]
If you have a share in a mounted drive and un-plug that drive, syncthing sees it as a folder delete and will mass delete everything in your share.

Steps to reproduce: 
1) make a share on a mounted drive (i was using a external harddrive)
2) share with another computer
3) unplug that drive
4) syncthing will see the change as a delete
5) the files on the remote computer(s) will be deleted.

Expected Behavior:
 syncthing should see the share as being no longer available not a delete of all files
 I would also expect a safety catch that prevents a mass delete of all files in a share

Environment: 
I am running v0.10.27 on two arch systems and v0.10.27 on an iMac

Don't worry I had a backup :)

**Comment by AudriusButkevicius** [comment]
Dup #762
