### ISSUE TITLE
Versioning information not displayed

### ISSUE THREAD

**Issue by rumpelsepp** [syncthing/syncthing#1497]
I have built a dev version of syncthing to test the new external file versioning stuff. There is a little bug in the overview:

![screenshot from 2015-03-20 08 13 49](https://cloud.githubusercontent.com/assets/1961699/6747392/126e35ca-ced9-11e4-9267-300b5c21393a.png)

The information of file versioning is empty now.

```
$ syncthing --version
syncthing v0.10.27+25-g5c026cb (go1.4.2 linux-amd64 default) stefan@naboo 2015-03-19 13:02:47 UTC
```

**Comment by AudriusButkevicius** [comment]
#1492

**Comment by rumpelsepp** [comment]
Oh. Okay, sry.
