### ISSUE TITLE
Cannot change the binding address

### ISSUE THREAD

**Issue by viric** [syncthing/syncthing#1499]
I go to preferences, and try to change ::22000 to ::7007, and the changes are never made effective.

Version 0.10.26.

**Comment by AudriusButkevicius** [comment]
::7007 is not valid [::]:7007 is.
Also, refresh the browser, if you restarted syncthing, the session cookie might be expired.

**Comment by viric** [comment]
I think I tried all reloads and restarts possible, and it did not change. Immediately to every change attempt, it says "connection error" in the browser, so it already invites to reload.

**Comment by viric** [comment]
And despite I wrote the full text wrong here, I only replaced the number part of it.

**Comment by AudriusButkevicius** [comment]
So what does the HTTP request return as it posts the config?

**Comment by calmh** [comment]
> Immediately to every change attempt, it says "connection error" in the browser

This does not sound normal. Rather, it sounds like your configuration save does not "take" because the browser fails the CSRF check or similar. Are you behind a proxy, using a weird browser, or doing something else tricky?

**Comment by viric** [comment]
Auhm. Sorry, it seems that I had this problem with v0.10.24, not v0.10.26. And I receive "403 Forbidden" to the POST. I am using a ssh port forwarding to access the web UI (-L 8081:localhost:8080).

**Comment by calmh** [comment]
Are you also using another syncthing on localhost port 8080? If so you are confusing your browser as it has two instances on the domain "localhost" that both are providing authentication cookies. Close your browser, surf *only* to the one on 8081, do your thing.

**Comment by viric** [comment]
Yes, the local is in localhost:8080, and the remote is in localhost:8081. Ah, so there are cookies that work by hostname.....

What an annoying thing then. For me, using a single browser for managing both local and remote syncthing seems a normal use case.

Isn't there any workaround to that?

**Comment by calmh** [comment]
Don't have both open in the browser at the same time. That's how cookies and browsers work unfortunately.

**Comment by viric** [comment]
Wouldn't it be able to work without cookies? I don't know what are they used for. If it's only for auth, maybe http auth could be enough.

**Comment by calmh** [comment]
They are needed for CSRF protection on POST requests.

**Comment by viric** [comment]
For what is worth, I found that I can use "localhost:8080" for one, and "127.0.0.1:8081" for the other. :)
