### ISSUE TITLE
List of unsynced items break when there is too many items

### ISSUE THREAD

**Issue by benapetr** [syncthing/syncthing#1500]
In case there is more than 500 000 unsynced items, clicking on the list would just cause syncthing to produce insanely large list of files, that can hardly be displayed in a browser, usually it just display some script error (ff).

It would be more useful if the list was trimmed for next 100 scheduled items, with optional button "show all items". This way it's kind of unusable for large lists.

**Comment by calmh** [comment]
@AudriusButkevicius Is this because they are queued? Otherwise we used to limit this, right?

**Comment by AudriusButkevicius** [comment]
Yes, we show all queued, if queued is less then N, we add files from the need list until we reach N.

**Comment by calmh** [comment]
Dup #630
