### ISSUE TITLE
Implement uptime

### ISSUE THREAD

**Issue by benapetr** [syncthing/syncthing#1501]
So that web GUI show how long syncthing was running

I have a feeling that my instance is occasionally crashing, but it's not easy to figure out

**Comment by calmh** [comment]
If it crashes, there are crash logs in the configuration directory. Those would be interesting.

**Comment by AudriusButkevicius** [comment]
You can check the process uptime?

**Comment by benapetr** [comment]
How the crash logs would look? There are some binary files with .log suffix. I configured syncthing as service so I don't see its own logs.

**Comment by AudriusButkevicius** [comment]
In the config directory it would create files with `panic-YYYYMMDD-HHMMSS.log`.

**Comment by Zillode** [comment]
@benapetr I think it might have to do with automated restarts. This is intentional and happens when your laptop comes back from sleep/hibernation.

**Comment by calmh** [comment]
It's easy and harmless enough that we could have this and expose it somewhere in the GUI.
