### ISSUE TITLE
List unsyncable files

### ISSUE THREAD

**Issue by benapetr** [syncthing/syncthing#1503]
I am often getting some errors on windows node in terminal that some file can't be synced because of something UTF related.

It would be nice to have an option so see all files that were not synced and which can't be synced because of this. It looks to me that right now syncthing probably just ignore these files pretending that everything is synced.

**Comment by AudriusButkevicius** [comment]
No, it stops completely when it fails to sync something.

**Comment by benapetr** [comment]
Ok so what does that error try to tell me? I say it can't sync something, but it doesn't stop completely, so it actually does sync the files?

**Comment by AudriusButkevicius** [comment]
Actually, I think for files with invalid characters it just skips them printing errors in the log.

**Comment by benapetr** [comment]
Yes hence this feature request: it would be nice to have a list available somewhere in GUI that would display all these files. In case of folder with millions of files, it's not easy to search them in logs, that were already lost in history of terminal

**Comment by AudriusButkevicius** [comment]
I am not sure we can do that.
As there is no difference between file which is ignored versus a file which is invalid.

**Comment by daevski** [comment]
I think (s)he wants to know all the files that were skipped. I would also like this; I had about 5-6 files listed in the web interface, for invalid characters... I fixed those by changing some characters in filenames, then another 5-6 showed up. A complete list of files skipped would let me know which files I need to fix all at one time.... and another list of invalid characters would be nice, too.

So far I can see that on Mac, these characters are allow, but are rejected on Windows:
Forward slash: " / "
Question mark: " ? "

**Comment by AudriusButkevicius** [comment]
There is a large list for Windows, I am sure Google can answer your question.

**Comment by daevski** [comment]
AudriusButkevicius, I now it can; I don't live under a rock. Are you trying to make a product that people will like, or not? Right now your application is surprisingly terrible at communicating to the user and I'm trying to give you feedback on it. And your attitude on the forums and issue tracker leave something to be desired as well. I'm simply trying to be helpful and don't appreciate the answer above.

**Comment by AudriusButkevicius** [comment]
I am not saying this is not an issue, and I am not saying that we report errors very well... hence marked this as an enhancement. 
The reason I said what I said is because you said `So far I can see, and I was just pointing out, given you want to know the whole list of characters (which is quite extensive - 40 or so characters), you can definitely find it via Google.

**Comment by calmh** [comment]
The list of disallowed characters on Windows is unrelated to UTF-8 normalization errors, which seems to be the original issue here. That is #430 and has been resolved (although it's not in any release yet).
