### ISSUE TITLE
Add pagination to `Out of sync` list

### ISSUE THREAD

**Issue by benapetr** [syncthing/syncthing#1509]
I got a folder that I want to sync which got about 300 000 files, from these about 250 000 are small files, about 80KB, but there are also some large files, that have about 2GB each.

When I start syncthing it get stuck for about an hour, just to compute which all files are not synced, and to build that huge queue of files to sync. And then it get stuck again, after syncing few small files on one huge file that needs about a day or more for it to be synced, because it's huge.

If there was an option to sort the sync queue by size, it would get rid of all small files in few hours and whole thing would start working much more smooth, as there wouldn't be hundreds of thousands of files in the queue, which makes syncthing very laggy and unresponsive, thus whole sync process would be incredibly more fast and effective.

**Comment by Zillode** [comment]
It's not a problem of having thousands of files in the queue, we perform batching based on reads in the database. I think this a dup of https://github.com/syncthing/syncthing/issues/1434
With a relation to the expensive ```withNeed``` calls.

**Comment by benapetr** [comment]
another probably related issue is that CPU is alway 99% when there is so large list of files

**Comment by benapetr** [comment]
BTW it is problem for me to have thousands of files in a queue, especially because they don't have to be there if st was smarter it would be matter of few minutes to get rid of all small files, that each take seconds to sync, making the queue small.

**Comment by benapetr** [comment]
or perhaps if scheduler worked in paralel, and synced smallest files in separate thread it would work as well, this was large files would never freeze syncing for long time

**Comment by AudriusButkevicius** [comment]
I don't think the queue has anything to do with this. The queue is just a list of strings, and I think having 250000 strings is perfectly fine to fit in RAM and shouldn't cause CPU load.

The queue is there specifically so that you could prioritize files which you want yourself.

Sending smaller files first is not necessarily always the right answer, there is a large fixed amount of work associated with finalizing receiving a file, hence syncing one large file is more efficient than 250000 small files, as for every file we have to update the database (which is probably where the load comes from).

You might want to increase the number of copiers and pullers in the config which should help syncthing to plow through the queue quicker.

**Comment by benapetr** [comment]
Currently there are so many files in the queue that I can't even display it
in GUI, so I can't really order it nor see why syncing is stuck. I don't
even know if it works at all, I occasionally watch the progress doing find
folder | wc -l and watching how number of files increases, but IMHO it's
much slower than it should be. Sometimes the number even stuck for like 40
minutes and then some more files are added. I don't know why is that, I
can't see in GUI what is going on.

**Comment by benapetr** [comment]
What I hate most is that I have to restart the program with every little change to configs, which results in syncig getting stuck for another hour needed to gt the list of files that ren't snced

**Comment by Zillode** [comment]
We currently have an issue with the GUI calls that consume too much CPU&IO. Please close the GUI if you run into performance issues and let the sync finish first. Afterwards the GUI should be less cpu/io intensive.

**Comment by AudriusButkevicius** [comment]
I feel this is fixed by https://github.com/syncthing/syncthing/commit/454e688c3d626f8e2413d8c0d8acc65c204d8981

Try the beta, and reopen if it's still an issue.

**Comment by AudriusButkevicius** [comment]
Reopening due to the other issue described here.

**Comment by ralder** [comment]
Isn't same https://github.com/syncthing/syncthing/issues/630 ?

**Comment by AudriusButkevicius** [comment]
Thanks for pointing it out.

Previously it was just a list of 100 items which was just long (hence we could live with it), now it's potentially a list of 1 million items which causes the browser to lock up.

Hence this one is more important and that one is now a duplicate in some sense.

**Comment by benapetr** [comment]
The problem is that there is just no way to display all items that are out
of sync, even when I do REST thing I only see small portion of files, while
GUI shows thosands of files that aren't synced (while telling me that
syncing was finished) so I assume that these thousands of files are
actually ignored. I think that whole list of unsynced items need to be
split to multiple lists:

* Files queued to be synced
* Files that are being synced
* Files that are not going to be synced

All these 3 lists should be expandable
