### ISSUE TITLE
Cannot connect through firewall

### ISSUE THREAD

**Issue by thirtythreeforty** [syncthing/syncthing#151]
I have a machine (a Raspberry Pi) behind a university firewall that I'd like my laptop (also behind the firewall, but on a different subnet) to sync with.  Both machines are running ST 0.8.1.

According to Wireshark, the automatic discovery with the global server works fine--ST learns the Pi's IP address, and attempts to connect inward.  However, the university blackholes the inbound SYN packets.

I would like to know more about how TCP hole-punching is accomplished in ST, and then consider how this problem might be worked around.  I think the university routers need to see an outbound connection attempt from the Pi before they would allow a reply (to the same connection) back in.

I should note that when they're on the same network, everything works fine, so this is certainly a firewall issue.

**Comment by MicahChambers** [comment]
I know this is closed, but it would still be a nice feature.

**Comment by AudriusButkevicius** [comment]
#804
