### ISSUE TITLE
option to create case insensitive entry in ignore patterns

### ISSUE THREAD

**Issue by benapetr** [syncthing/syncthing#1511]
so that *.AVI matches *.avi etc

**Comment by AudriusButkevicius** [comment]
No, because having a.AVI and a.avi on Linux is perfectly valid, and they are two separate files.

**Comment by benapetr** [comment]
So what? Everybody knows this, but still there would be probably many users who would happily configure syncthing to ignore case in ignore patterns, so that *.avi matches all avi files, no matter of case used in suffix.

Or you should at least implement regular expressions so that users can define this themselves

**Comment by benapetr** [comment]
Can you give me a valid use case where user would want to ignore all *.mp3 files but not *.MP3 files? Except for some weird freaks, I can't think of any.

**Comment by benapetr** [comment]
Just one random fact to educate you little bit: having two files with same name but different letter case, like a, A has nothing to do with linux (you said "on linux") it's a long term POSIX standard that exists far longer than linux does...

**Comment by AudriusButkevicius** [comment]
Don't forget that ignore files are not only for extensions, hence I can clearly see cases where I would like to ignore *somestring* but not *SOMESTRING*.

Yeah, Linux very rarely uses FAT32 which is the only alive FS which is not case sensitive.
Given majority of the FS'es are case sensitive, I don't see why we shouldn't be case sensitive?

**Comment by kozec** [comment]
While I really don't like being called weird freak, having something like `i:*.avi` translated to `/.*\.avi/i` doesn't sounds impossible...

**Comment by benapetr** [comment]
I didn't know syncthing is designed only for people with no technical background

Anyway, there should be at least option to create case insensitive entry in the list, something like i/pattern goes here/ etc

**Comment by benapetr** [comment]
yes, exactly what kozec meant

**Comment by kozec** [comment]
On other hand, doesn't this...

https://github.com/syncthing/syncthing/blob/d9fd27a9e804aed1a17c17912d9894a26c277439/internal/fnmatch/fnmatch.go#L27

... means that patterns are case-insensitive on Windows anyway?

**Comment by benapetr** [comment]
On windows maybe, but I am using linux

**Comment by canton7** [comment]
FWIW, HSF+ (uses by the macheads out there) is also case-insensitive by default.

**Comment by calmh** [comment]
Patterns are case insensitive on Mac and Windows, case sensitive everywhere else. It would be useful to be able to create case insensitive patterns there as well, I guess.

**Comment by Zillode** [comment]
What about allowing ```(?i)``` as a control parameter?
