### ISSUE TITLE
Expose all defaults, and allow them to be configurable

### ISSUE THREAD

**Issue by rumpelsepp** [syncthing/syncthing#1516]
see here: https://discourse.syncthing.net/t/default-rescan-interval/2191

> Is there any possibility to change the default rescan interval? Since a few weeks I use the syncthing-inotify daemon (which works like a charm!), but I have to increase the rescan interval for every directory manually. Is there any option (or maybe variable?) to change the default rescan interval for recently added directories?

Audrius:
> But I guess we should eventually expose all defaults, and allow them to be configurable, though I am sure there are bigger issues today.

> Perhaps create an issue in the tracker so it's not forgotten.

**Comment by calmh** [comment]
This is just to add all available settings somewhere in the GUI right?

**Comment by AudriusButkevicius** [comment]
I guess it is, you are right.

**Comment by AudriusButkevicius** [comment]
@rumpelsepp do we agree that we should close it?
Given all the settings are exposed, you just set them up at the point you add the folder.

**Comment by rumpelsepp** [comment]
> Given all the settings are exposed, you just set them up at the point you add the folder.

Unfortunately I don't get it, sorry … :) Do you mean that setting up a new folder should internally generate new default values?

**Comment by AudriusButkevicius** [comment]
No. The value is exposed when you add the folder, so what's preventing you from configuring at the point you add it?
You'll have to go through the dialog anyway.

**Comment by rumpelsepp** [comment]
Ahh. Thanks for clarifying. Well, that is a sane argument. I did not set it to my prefered value in the first place because I was too lazy to calculate the amount of seconds of a day... But that's another issue. :-) I agree with closing.

On March 29, 2015 1:01:51 AM CET, Audrius Butkevicius <notifications@github.com> wrote:
>No. The value is exposed when you add the folder, so what's preventing
>you from configuring at the point you add it?
>You'll have to go through the dialog anyway.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/syncthing/syncthing/issues/1516#issuecomment-87331840

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
