### ISSUE TITLE
Automatic disabling of syncing syncthings temp and index files

### ISSUE THREAD

**Issue by merlink01** [syncthing/syncthing#1522]
If the complete home folder is synced it should be good not to sync the
.config/syncthing/index folder, because it creates unwanted traffic.

I know I could exclude it manualy but it is more practically to exclude the syncthing temp and index files
inside the program automatically.

Thanks.

**Comment by AudriusButkevicius** [comment]
You are bound to corrupt the database and end up in a never completing sync if you are using syncthing to sync its own database (and even worse if both instances are running of the same database).

**Comment by merlink01** [comment]
Yes, I know that some workflows might be critical, but here it's a oneway Sync from my Laptop to a Folder on my NAS. So that's more a Backup than a Sync.

I don't sync 2 home directories so there is just this endless syncing of index files from home to the NAS.

I disabled the Folder now, but if syncthing knows the own configdir it could be practical to disable it by default.

**Comment by calmh** [comment]
Possibly related, #1114 to ignore directories with certain files in them.

**Comment by djtm** [comment]
Yes, that could easily be fixed with a cachedir tag in the syncthing index folder. (Once syncthing interprets cache tags.)

**Comment by calmh** [comment]
Considered dup of above mentioned issue.
