### ISSUE TITLE
High CPU usage and constant thrashing of ~/.config/syncthing/index when "idle"

### ISSUE THREAD

**Issue by ToxicFrog** [syncthing/syncthing#1524]
Two systems, both running Syncthing 0.10.29 on amd64 Linux. Starting as soon as the initial scan completes, and continuing forever (even after leaving it running for 3+ hours), ST exhibits 100-130% CPU usage. iotop shows it writing several MBps continuously.

Examination of ~/.config/syncthing/index shows where the writes are going; the ldb files there are constantly being deleted and replaced. The total number and size remains more or less constant, but it's creating about 10 new ones *per second* (and deleting old ones).

Starting it with `STTRACE=events,files,model,scanner,stats,xdr` results in a huge amount of spam:

    device.go:58: DEBUG: stats.DeviceStatisticsReference.WasSeen: 63R6ZOT...

The device ID is always the same and is the ID of the other computer this one is connected to. It generates 500-600 of these log messages per second.

The other device exhibits the same behaviour, except showing the device ID of the first device, of course.

If I shut one of them down, the other one immediately calms down to about 15% CPU usage (which is still high for a service doing nothing, but acceptable) and the WasSeen spam goes away (to be replaced with much gentler log spam from puller.go, on the order of one message per dir per second).

Based on a cursory reading of the source, it looks like there's something calling WasSeen in a busyloop, constantly updating the last-seen timestamp of the connected devices, resulting in maxed out CPU usage and constant disk thrashing by the levelDB files. I'm not sure what, though.

Logs gistable on request, or you can find me in the IRC channel and grill me there.

**Comment by calmh** [comment]
There are a few places were `WasSeen` is called. Obviously, none of them *should* be called that often - do you have some log context that might help narrow down where it came from?

**Comment by AudriusButkevicius** [comment]
Copy from IRC:
```
there is basically two things that can cause WasSeen to get called like crazy
peer completion GUI call, and connection checking loop (which sleeps ReconnectIntervalS seconds between attempts)
```
Hence, what is your reconnection interval set to?

**Comment by AudriusButkevicius** [comment]
From IRC:
```
I can't find reconnect interval in the GUI anywhere, but according to st-cli and config.xml it's 0.
```
