### ISSUE TITLE
OPen leveldb failed IO error: /XX/XX/XX Invalid argument

### ISSUE THREAD

**Issue by jetliwei123** [syncthing/syncthing#1525]
hi, I met Invalid argument when I use leveldb on the cifs file system, could you please help me? thanks
I mount a cifs path on my linux machine, and then run my leveldb program, and the leveldb open failed with "Open leveldb fialed IO error: /XX/XX/XX Invalid argument" and the path is the cifs path.
Is the leveldb did not support cifs file system? looking forward your reply!

**Comment by AudriusButkevicius** [comment]
Is syncthing throwing that error?

**Comment by jetliwei123** [comment]
@AudriusButkevicius : I am not sure, I just do open leveldb and did not do other operator. but there still  product some files about leveldb even if the open leveldb operator failed(.log, CURRENT, LOCK, LOCK, MANIFEST).

**Comment by AudriusButkevicius** [comment]
This repo is for syncthing, not for leveldb though.

**Comment by jetliwei123** [comment]
@AudriusButkevicius: Sorry, I did not understanding what you said, what is relation between syncthing and leveldb? And why this repo is for syncthing but not for leveldb

**Comment by AudriusButkevicius** [comment]
I mean we use leveldb in syncthing, but the question you are asking is related more to leveldb and not to syncthing, hence I want to make sure you've raised the issue in the right repo and to make sure that I am not misunderstanding something.

So when you start syncthing, you get leveldb errors?
Can you post some logs from syncthing to understand where this is happening?

**Comment by jetliwei123** [comment]
@AudriusButkevicius: sorry, there is no log for the code, my code is just a very small code which only call leveldb::DB::Open and return it's status, then the status is not ok and report error. I am not sure are these information usefull

**Comment by AudriusButkevicius** [comment]
Ok, you are definitely in the wrong repo. This is syncthing, a file synchronization engine. We just USE leveldb (like you), we don't support, develop or fix leveldb. You probably want to go to:
https://code.google.com/p/leveldb/

As I think you are using the C++ version.
