### ISSUE TITLE
FATAL: Invalid version string "886b02d" and some regex error

### ISSUE THREAD

**Issue by nottinhill** [syncthing/syncthing#1532]
$ ~/go/src/github.com/syncthing/syncthing/bin$ ./syncthing 

results in 
     
     23:59:22 FATAL: Invalid version string "886b02d";
	does not match regexp ^v\d+\.\d+\.\d+(-[a-z0-9]+)*(\+\d+-g[0-9a-f]+)?(-dirty)?$

I looked into your source code and see something about dev version variables which I dont understand without being involved in the project.

How to solve?

**Comment by AudriusButkevicius** [comment]
How did you build syncthing?

**Comment by nottinhill** [comment]
Its described in my blog, Those were the exact steps. Anyway mate, I'll save you the time for more important tasks and will go down the docker route. Seem like a brilliant plan also for future projects.

**Comment by AudriusButkevicius** [comment]
I think you checked out code from a developers forked repo, hence your problem.

**Comment by nottinhill** [comment]
+1 that is the issue.

**Comment by AudriusButkevicius** [comment]
Case closed then?

**Comment by nottinhill** [comment]
Agree. Docker install worked fine. I untarred the package, cd-ed into the dir and executed the file. Maybe add that to the docks liked in my last post. Cheers!

**Comment by AudriusButkevicius** [comment]
The docs says that the build command produces release files, hence not sure what else to add.

I guess your blog post also deserves updating, because you were building a random repo the whole time.
