### ISSUE TITLE
Options exceeds size limit; 4268616228 > 64

### ISSUE THREAD

**Issue by nottinhill** [syncthing/syncthing#1533]
[PVO5Z] 02:48:37 INFO: Connection to xxxx-xxxx-xxxx closed: Options exceeds size limit;
    4268616228 > 64

I am seeing above error on my "client" at home behind NAT (port forwarding active and UPnP as well) and on the "server" in the cloud I see:  

    Established secure connection to xxxx-xxxxxxxxxxx-xxxxxxxxx at 1.2.3.4:22000-4.5.6.7:36076
    [CWRQW] 21:51:10 INFO: Connection to xxxxxxx-xxxxxxxxxx-x closed: EOF

The shared folder has one `empty.txt` in it.

Any ideas?

**Comment by nottinhill** [comment]
Might be a firewall issue. Do yo have any guides on how to firewall with your app and docker?

**Comment by AudriusButkevicius** [comment]
You are using two incompatible verisons.
v0.10 talks to v0.10
v0.11 talks to v0.11

**Comment by AudriusButkevicius** [comment]
v0.11 beta hasn't even been released yet, and it's surely unstable...

**Comment by nottinhill** [comment]
I have now two identical versions running on two identical versions of Linux. I am getting the exact identical error message as above.

**Comment by nottinhill** [comment]
I have gotten it to run by nuking my Ubuntu 12.04 server, installing 14.04, adding the PPA from ytvwld on both client and server, opening both firwewalls on UDP and TCP as per guide, adding iptable rules, flushing them and praying.
