### ISSUE TITLE
Panic with v0.11.0-beta0+31-gc67e2c2 on linux i386

### ISSUE THREAD

**Issue by HealingTek** [syncthing/syncthing#1534]
I just did a new install of syncthing on one of my computers and it keeps panicking, crashing and restarting.

syncthing v0.11.0-beta0+31-gc67e2c2 (go1.4.1 linux-386 default)

There are several panic logs. Here's one:

[Q53XZ] 01:33:23 INFO: syncthing v0.11.0-beta0+31-gc67e2c2 (go1.4.1 linux-386 default) foo@ebi 2015-03-27 13:08:03 UTC
[Q53XZ] 01:33:23 INFO: My ID: Q53XZ3U-PTFZWXP-HNQXOTJ-WE7O2V2-7LUVC3C-6ZNW62U-G5BD2RO-6NMQNAB
[Q53XZ] 01:33:23 INFO: Starting web GUI on http://0.0.0.0:8888/
[Q53XZ] 01:33:29 INFO: Starting UPnP discovery...
[Q53XZ] 01:33:35 INFO: UPnP discovery complete (found 0 devices).
[Q53XZ] 01:33:35 INFO: Starting local discovery announcements
[Q53XZ] 01:33:35 INFO: Starting global discovery announcements
[Q53XZ] 01:33:35 OK: Ready to synchronize default (read-write)
[Q53XZ] 01:33:35 INFO: Device Q53XZ3U-PTFZWXP-HNQXOTJ-WE7O2V2-7LUVC3C-6ZNW62U-G5BD2RO-6NMQNAB is "ebi" at [dynamic]
[Q53XZ] 01:33:35 INFO: Device WZ2R5CQ-BEFOKJO-IMCMPPJ-BWFF5DL-XCKDOSU-HSTHYT4-6GG65CA-YQ6ERAN is "toro" at [dynamic]
...
[Q53XZ] 01:33:35 INFO: No automatic upgrades; v0.11.0-beta0+31-gc67e2c2 is not a release version.
[Q53XZ] 01:33:35 INFO: Completed initial scan (rw) of folder default
[Q53XZ] 01:33:46 INFO: Established secure connection to WZ2R5CQ-BEFOKJO-IMCMPPJ-BWFF5DL-XCKDOSU-HSTHYT4-6GG65CA-YQ6ERAN at 192.168.23.34:22000-192.168.23.23:38333
Panic at 2015-03-28T01:33:46-07:00
panic: runtime error: slice bounds out of range

goroutine 52 [running]:
github.com/calmh/xdr.(*Reader).ReadBytesMaxInto(0x193f4a00, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/foo/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/calmh/xdr/reader.go:79 +0x58b
github.com/calmh/xdr.(*Reader).ReadStringMax(0x193f4a00, 0x40, 0x0, 0x0)
	/home/foo/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/calmh/xdr/reader.go:41 +0x58
github.com/syncthing/protocol.(*Option).DecodeXDRFrom(0x18a8e200, 0x193f4a00, 0x0, 0x0)
	/home/foo/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syncthing/protocol/message_xdr.go:951 +0x40
github.com/syncthing/protocol.(*Device).DecodeXDRFrom(0x18cc62d0, 0x193f4a00, 0x0, 0x0)
	/home/foo/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syncthing/protocol/message_xdr.go:870 +0x195
github.com/syncthing/protocol.(*Folder).DecodeXDRFrom(0x18cc4150, 0x193f4a00, 0x0, 0x0)
	/home/foo/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syncthing/protocol/message_xdr.go:755 +0x11e
github.com/syncthing/protocol.(*ClusterConfigMessage).DecodeXDRFrom(0x18db3d9c, 0x193f4a00, 0x0, 0x0)
	/home/foo/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syncthing/protocol/message_xdr.go:638 +0x164
github.com/syncthing/protocol.(*ClusterConfigMessage).UnmarshalXDR(0x18db3d9c, 0x18d6e000, 0x2b8, 0x2b8, 0x0, 0x0)
	/home/foo/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syncthing/protocol/message_xdr.go:629 +0x117
github.com/syncthing/protocol.(*rawConnection).readMessage(0x18d9a000, 0x0, 0x1, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0)
	/home/foo/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syncthing/protocol/protocol.go:450 +0xb8b
github.com/syncthing/protocol.(*rawConnection).readerLoop(0x18d9a000, 0x0, 0x0)
	/home/foo/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syncthing/protocol/protocol.go:295 +0x116
created by github.com/syncthing/protocol.NewConnection
	/home/foo/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syncthing/protocol/protocol.go:167 +0x283

goroutine 1 [chan receive]:
main.syncthingMain()
	/home/foo/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:631 +0x24eb
main.main()
	/home/foo/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:362 +0x1acc

goroutine 5 [syscall]:
os/signal.loop()
	/home/foo/src/go/src/os/signal/signal_unix.go:21 +0x21
created by os/signal.init·1
	/home/foo/src/go/src/os/signal/signal_unix.go:27 +0x34

goroutine 7 [select]:
github.com/syncthing/syncthing/internal/events.(*Subscription).Poll(0x18a35080, 0xf8475800, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/foo/src/github.com/syncthing/syncthing/internal/events/events.go:173 +0x33f
github.com/syncthing/syncthing/internal/events.(*BufferedSubscription).pollingLoop(0x18a3a450)
	/home/foo/src/github.com/syncthing/syncthing/internal/events/events.go:209 +0x44
created by github.com/syncthing/syncthing/internal/events.NewBufferedSubscription
	/home/foo/src/github.com/syncthing/syncthing/internal/events/events.go:203 +0x175

goroutine 8 [chan receive]:
main.trackCPUUsage()
	/home/foo/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0x11a
created by main.init·3
	/home/foo/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x25

goroutine 10 [chan receive]:
github.com/syncthing/syncthing/internal/config.(*Wrapper).Serve(0x18a28d80)
	/home/foo/src/github.com/syncthing/syncthing/internal/config/wrapper.go:79 +0x6a
created by github.com/syncthing/syncthing/internal/config.Wrap
	/home/foo/src/github.com/syncthing/syncthing/internal/config/wrapper.go:54 +0x10b

goroutine 11 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x18aaa420)
	/home/foo/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x1c5
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/home/foo/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236 +0x1bb

goroutine 12 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0x18a32620)
	/home/foo/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:120 +0x414
created by github.com/syndtr/goleveldb/leveldb.openDB
	/home/foo/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:126 +0x731

goroutine 13 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0x18a32620)
	/home/foo/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_state.go:73 +0x11d
created by github.com/syndtr/goleveldb/leveldb.openDB
	/home/foo/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:127 +0x746

goroutine 14 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0x18a32620)
	/home/foo/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:812 +0x68a
created by github.com/syndtr/goleveldb/leveldb.openDB
	/home/foo/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:130 +0x780

goroutine 15 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0x18a32620)
	/home/foo/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:759 +0x221
created by github.com/syndtr/goleveldb/leveldb.openDB
	/home/foo/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:131 +0x795

goroutine 16 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0x18a32620)
	/home/foo/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x153
created by github.com/syndtr/goleveldb/leveldb.openDB
	/home/foo/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:132 +0x7aa

goroutine 17 [select]:
github.com/syncthing/syncthing/internal/model.(*ProgressEmitter).Serve(0x18ac81e0)
	/home/foo/src/github.com/syncthing/syncthing/internal/model/progressemitter.go:48 +0x6d8
created by github.com/syncthing/syncthing/internal/model.NewModel
	/home/foo/src/github.com/syncthing/syncthing/internal/model/model.go:118 +0x5d3

goroutine 18 [sleep]:
github.com/syncthing/syncthing/internal/model.func·029()
	/home/foo/src/github.com/syncthing/syncthing/internal/model/util.go:17 +0x57
created by github.com/syncthing/syncthing/internal/model.deadlockDetect
	/home/foo/src/github.com/syncthing/syncthing/internal/model/util.go:35 +0xb8

goroutine 19 [sleep]:
github.com/syncthing/syncthing/internal/model.func·029()
	/home/foo/src/github.com/syncthing/syncthing/internal/model/util.go:17 +0x57
created by github.com/syncthing/syncthing/internal/model.deadlockDetect
	/home/foo/src/github.com/syncthing/syncthing/internal/model/util.go:35 +0xb8

goroutine 20 [select]:
github.com/syncthing/syncthing/internal/ignore.(*Matcher).clean(0x18a902d0, 0x61714000, 0x68c)
	/home/foo/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:153 +0x192
created by github.com/syncthing/syncthing/internal/ignore.New
	/home/foo/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:53 +0xb4

goroutine 21 [IO wait]:
net.(*pollDesc).Wait(0x18aa6938, 0x72, 0x0, 0x0)
	/home/foo/src/go/src/net/fd_poll_runtime.go:84 +0x42
net.(*pollDesc).WaitRead(0x18aa6938, 0x0, 0x0)
	/home/foo/src/go/src/net/fd_poll_runtime.go:89 +0x40
net.(*netFD).accept(0x18aa6900, 0x0, 0xb753aeb8, 0x18a2ca20)
	/home/foo/src/go/src/net/fd_unix.go:419 +0x34f
net.(*TCPListener).AcceptTCP(0x18ab01d8, 0x8, 0x0, 0x0)
	/home/foo/src/go/src/net/tcpsock_posix.go:234 +0x48
net.(*TCPListener).Accept(0x18ab01d8, 0x0, 0x0, 0x0, 0x0)
	/home/foo/src/go/src/net/tcpsock_posix.go:244 +0x48
main.(*DowngradingListener).Accept(0x193d8e30, 0x0, 0x0, 0x0, 0x0)
	/home/foo/src/github.com/syncthing/syncthing/cmd/syncthing/tls.go:104 +0x61
net/http.(*Server).Serve(0x18aac580, 0xb753eaf0, 0x193d8e30, 0x0, 0x0)
	/home/foo/src/go/src/net/http/server.go:1728 +0x7b
main.func·001()
	/home/foo/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:183 +0x58
created by main.startGUI
	/home/foo/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:187 +0x10a8

goroutine 22 [IO wait]:
net.(*pollDesc).Wait(0x18aac738, 0x72, 0x0, 0x0)
	/home/foo/src/go/src/net/fd_poll_runtime.go:84 +0x42
net.(*pollDesc).WaitRead(0x18aac738, 0x0, 0x0)
	/home/foo/src/go/src/net/fd_poll_runtime.go:89 +0x40
net.(*netFD).Read(0x18aac700, 0x19341000, 0x1000, 0x1000, 0x0, 0xb753aeb8, 0x18d08848)
	/home/foo/src/go/src/net/fd_unix.go:242 +0x2f0
net.(*conn).Read(0x18ab00d0, 0x19341000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/foo/src/go/src/net/net.go:121 +0xba
bufio.(*Reader).Read(0x18a3a960, 0x19341000, 0x1000, 0x1000, 0xffffffff, 0x0, 0x0)
	/home/foo/src/go/src/bufio/bufio.go:164 +0xe3
main.(*WrappedConnection).Read(0x18a5c3f0, 0x19341000, 0x1000, 0x1000, 0x15d, 0x0, 0x0)
	/home/foo/src/github.com/syncthing/syncthing/cmd/syncthing/tls.go:128 +0x62
net/http.(*liveSwitchReader).Read(0x18a4c444, 0x19341000, 0x1000, 0x1000, 0x193c7b90, 0x0, 0x0)
	/home/foo/src/go/src/net/http/server.go:214 +0x8b
io.(*LimitedReader).Read(0x18a5c430, 0x19341000, 0x1000, 0x1000, 0x18d08810, 0x0, 0x0)
	/home/foo/src/go/src/io/io.go:408 +0xda
bufio.(*Reader).fill(0x18a3a990)
	/home/foo/src/go/src/bufio/bufio.go:97 +0x15c
bufio.(*Reader).ReadSlice(0x18a3a990, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/foo/src/go/src/bufio/bufio.go:295 +0x1ce
bufio.(*Reader).ReadLine(0x18a3a990, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/foo/src/go/src/bufio/bufio.go:324 +0x5a
net/textproto.(*Reader).readLineSlice(0x193f4940, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/foo/src/go/src/net/textproto/reader.go:55 +0x76
net/textproto.(*Reader).ReadLine(0x193f4940, 0x0, 0x0, 0x0, 0x0)
	/home/foo/src/go/src/net/textproto/reader.go:36 +0x48
net/http.ReadRequest(0x18a3a990, 0x18cc40e0, 0x0, 0x0)
	/home/foo/src/go/src/net/http/request.go:598 +0xaf
net/http.(*conn).readRequest(0x18a4c420, 0x0, 0x0, 0x0)
	/home/foo/src/go/src/net/http/server.go:586 +0x24b
net/http.(*conn).serve(0x18a4c420)
	/home/foo/src/go/src/net/http/server.go:1162 +0x60f
created by net/http.(*Server).Serve
	/home/foo/src/go/src/net/http/server.go:1751 +0x2ce

goroutine 37 [IO wait]:
net.(*pollDesc).Wait(0x18a2e578, 0x72, 0x0, 0x0)
	/home/foo/src/go/src/net/fd_poll_runtime.go:84 +0x42
net.(*pollDesc).WaitRead(0x18a2e578, 0x0, 0x0)
	/home/foo/src/go/src/net/fd_poll_runtime.go:89 +0x40
net.(*netFD).readFrom(0x18a2e540, 0x18d42000, 0x10000, 0x10000, 0x0, 0x0, 0x0, 0xb753aeb8, 0x193afd48)
	/home/foo/src/go/src/net/fd_unix.go:269 +0x34f
net.(*UDPConn).ReadFromUDP(0x1935a018, 0x18d42000, 0x10000, 0x10000, 0x83f4ae0, 0x0, 0x0, 0x0)
	/home/foo/src/go/src/net/udpsock_posix.go:67 +0xd3
net.(*UDPConn).ReadFrom(0x1935a018, 0x18d42000, 0x10000, 0x10000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/foo/src/go/src/net/udpsock_posix.go:82 +0xe1
github.com/syncthing/syncthing/internal/beacon.genericReader(0x1935a018, 0x18a2e9c0)
	/home/foo/src/github.com/syncthing/syncthing/internal/beacon/beacon.go:24 +0x8e
created by github.com/syncthing/syncthing/internal/beacon.NewBroadcast
	/home/foo/src/github.com/syncthing/syncthing/internal/beacon/broadcast.go:30 +0x178

goroutine 49 [syscall, locked to thread]:
runtime.goexit()
	/home/foo/src/go/src/runtime/asm_386.s:2287 +0x1

goroutine 38 [chan receive]:
github.com/syncthing/syncthing/internal/beacon.(*Broadcast).writer(0x193ae0a0)
	/home/foo/src/github.com/syncthing/syncthing/internal/beacon/broadcast.go:46 +0x74
created by github.com/syncthing/syncthing/internal/beacon.NewBroadcast
	/home/foo/src/github.com/syncthing/syncthing/internal/beacon/broadcast.go:31 +0x18d

goroutine 39 [chan receive]:
github.com/syncthing/syncthing/internal/beacon.(*Broadcast).Recv(0x193ae0a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/foo/src/github.com/syncthing/syncthing/internal/beacon/broadcast.go:41 +0x6e
github.com/syncthing/syncthing/internal/discover.(*Discoverer).recvAnnouncements(0x193d6900, 0xb7544700, 0x193ae0a0)
	/home/foo/src/github.com/syncthing/syncthing/internal/discover/discover.go:307 +0x47
created by github.com/syncthing/syncthing/internal/discover.(*Discoverer).StartLocal
	/home/foo/src/github.com/syncthing/syncthing/internal/discover/discover.go:76 +0x71c

goroutine 40 [IO wait]:
net.(*pollDesc).Wait(0x18a2ebf8, 0x72, 0x0, 0x0)
	/home/foo/src/go/src/net/fd_poll_runtime.go:84 +0x42
net.(*pollDesc).WaitRead(0x18a2ebf8, 0x0, 0x0)
	/home/foo/src/go/src/net/fd_poll_runtime.go:89 +0x40
net.(*netFD).readFrom(0x18a2ebc0, 0x18d82000, 0x10000, 0x10000, 0x0, 0x0, 0x0, 0xb753aeb8, 0x19398d3c)
	/home/foo/src/go/src/net/fd_unix.go:269 +0x34f
net.(*UDPConn).ReadFromUDP(0x1935a020, 0x18d82000, 0x10000, 0x10000, 0x83f4ae0, 0x0, 0x0, 0x0)
	/home/foo/src/go/src/net/udpsock_posix.go:67 +0xd3
net.(*UDPConn).ReadFrom(0x1935a020, 0x18d82000, 0x10000, 0x10000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/foo/src/go/src/net/udpsock_posix.go:82 +0xe1
github.com/syncthing/syncthing/internal/beacon.genericReader(0x1935a020, 0x18a2f140)
	/home/foo/src/github.com/syncthing/syncthing/internal/beacon/beacon.go:24 +0x8e
created by github.com/syncthing/syncthing/internal/beacon.NewMulticast
	/home/foo/src/github.com/syncthing/syncthing/internal/beacon/multicast.go:34 +0x1c4

goroutine 41 [chan receive]:
github.com/syncthing/syncthing/internal/beacon.(*Multicast).writer(0x193ae0f0)
	/home/foo/src/github.com/syncthing/syncthing/internal/beacon/multicast.go:50 +0x74
created by github.com/syncthing/syncthing/internal/beacon.NewMulticast
	/home/foo/src/github.com/syncthing/syncthing/internal/beacon/multicast.go:35 +0x1d9

goroutine 42 [chan receive]:
github.com/syncthing/syncthing/internal/beacon.(*Multicast).Recv(0x193ae0f0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/foo/src/github.com/syncthing/syncthing/internal/beacon/multicast.go:45 +0x6e
github.com/syncthing/syncthing/internal/discover.(*Discoverer).recvAnnouncements(0x193d6900, 0xb7544738, 0x193ae0f0)
	/home/foo/src/github.com/syncthing/syncthing/internal/discover/discover.go:307 +0x47
created by github.com/syncthing/syncthing/internal/discover.(*Discoverer).StartLocal
	/home/foo/src/github.com/syncthing/syncthing/internal/discover/discover.go:89 +0x629

goroutine 43 [select]:
github.com/syncthing/syncthing/internal/discover.(*Discoverer).sendLocalAnnouncements(0x193d6900)
	/home/foo/src/github.com/syncthing/syncthing/internal/discover/discover.go:298 +0x21b
created by github.com/syncthing/syncthing/internal/discover.(*Discoverer).StartLocal
	/home/foo/src/github.com/syncthing/syncthing/internal/discover/discover.go:99 +0x56f

goroutine 46 [chan receive]:
main.listenConnect(0xee7c7787, 0x6b73998f, 0xa6bbb09d, 0xd5ee139b, 0x5b54ba7e, 0x7bdbb217, 0xa847e846, 0x1a64cdbb, 0x18aaa000, 0x18a00b40)
	/home/foo/src/github.com/syncthing/syncthing/cmd/syncthing/connections.go:34 +0x19c
created by main.syncthingMain
	/home/foo/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:557 +0x1aa7

goroutine 45 [select]:
github.com/syncthing/syncthing/internal/discover.(*UDPClient).broadcast(0x18a6a770, 0x1937a080, 0x38, 0x80)
	/home/foo/src/github.com/syncthing/syncthing/internal/discover/client_udp.go:115 +0xabc
created by github.com/syncthing/syncthing/internal/discover.(*UDPClient).Start
	/home/foo/src/github.com/syncthing/syncthing/internal/discover/client_udp.go:79 +0x385

goroutine 47 [select]:
github.com/syncthing/syncthing/internal/model.(*rwFolder).Serve(0x18a4c060)
	/home/foo/src/github.com/syncthing/syncthing/internal/model/rwfolder.go:122 +0x185d
created by github.com/syncthing/syncthing/internal/model.(*Model).StartFolderRW
	/home/foo/src/github.com/syncthing/syncthing/internal/model/model.go:163 +0x507

goroutine 48 [sleep]:
main.generateEvents()
	/home/foo/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:768 +0x30
created by main.syncthingMain
	/home/foo/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:629 +0x24bd

goroutine 50 [IO wait]:
net.(*pollDesc).Wait(0x18d18af8, 0x72, 0x0, 0x0)
	/home/foo/src/go/src/net/fd_poll_runtime.go:84 +0x42
net.(*pollDesc).WaitRead(0x18d18af8, 0x0, 0x0)
	/home/foo/src/go/src/net/fd_poll_runtime.go:89 +0x40
net.(*netFD).accept(0x18d18ac0, 0x0, 0xb753aeb8, 0x18d11938)
	/home/foo/src/go/src/net/fd_unix.go:419 +0x34f
net.(*TCPListener).AcceptTCP(0x1935a258, 0x83eaf20, 0x0, 0x0)
	/home/foo/src/go/src/net/tcpsock_posix.go:234 +0x48
net.(*TCPListener).Accept(0x1935a258, 0x0, 0x0, 0x0, 0x0)
	/home/foo/src/go/src/net/tcpsock_posix.go:244 +0x48
main.listenTLS(0x18d189c0, 0x18a5cfe0, 0xd, 0x18a00b40)
	/home/foo/src/github.com/syncthing/syncthing/cmd/syncthing/connections.go:158 +0x374
created by main.listenConnect
	/home/foo/src/github.com/syncthing/syncthing/cmd/syncthing/connections.go:27 +0x117

goroutine 51 [sleep]:
main.dialTLS(0x18aaa000, 0x18d189c0, 0x18a00b40)
	/home/foo/src/github.com/syncthing/syncthing/cmd/syncthing/connections.go:256 +0x163
created by main.listenConnect
	/home/foo/src/github.com/syncthing/syncthing/cmd/syncthing/connections.go:31 +0x15f

goroutine 56 [runnable]:
github.com/syncthing/protocol.(*nativeModel).Close(0x1935a050, 0x8a1e75b6, 0xa45c2101, 0xde6382a1, 0xe8a5d890, 0xd20d25ee, 0xe233e5a1, 0xd1bd317e, 0x22f11003, 0x0, ...)
	<autogenerated>:95
created by github.com/syncthing/protocol.func·002
	/home/foo/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syncthing/protocol/protocol.go:664 +0x173

**Comment by Zillode** [comment]
Thanks for the report @HealingTek, please note that this is a beta.

**Comment by AudriusButkevicius** [comment]
I think this is known, and you shouldn't build from the master branch at the moment, because its unstable while between version bumps.

**Comment by calmh** [comment]
Master is currently unstable. Use a release version. :)
