### ISSUE TITLE
Docker and Port Forwarding

### ISSUE THREAD

**Issue by nottinhill** [syncthing/syncthing#1535]
https://github.com/syncthing/syncthing/wiki/Firewalls-and-Port-Forwards

Is there a guide like above that talks about Docker and how to forward ports for syncthing?

**Comment by AudriusButkevicius** [comment]
The docker container is for building, not for running syncthing (though you can).
You just need to make sure that the internal port (container port) and the external port (host port) is the same, or just run with --net=host.

**Comment by nottinhill** [comment]
Is there a full comprehensive guide somewhere that without any question 
will enable us to get this thing to work?

Am 28.03.2015 um 14:46 schrieb Audrius Butkevicius:

**Comment by nottinhill** [comment]
Must I edit ipTables?

Is there a guide?

Am 28.03.2015 um 14:46 schrieb Audrius Butkevicius:

**Comment by Zillode** [comment]
@nottinhill : these are docker specific problems.
To get Syncthing working I suggest you download https://github.com/syncthing/syncthing/releases/latest and follow https://github.com/syncthing/syncthing/wiki/Getting-Started
If you have other questions, please use the forum.
Thanks

**Comment by nottinhill** [comment]
Again directing me to the useless wiki? *sigh

Well this is how its done:

http://meshfields.de/install-go1-4-syncthing-on-ubuntu-server/


Am 28.03.2015 um 16:20 schrieb Zillode:

**Comment by AudriusButkevicius** [comment]
You just don't know how to use docker, it has nothing todo with syncthing sadly.

**Comment by AudriusButkevicius** [comment]
Also, your blog is full of lies about go versions and incompatibilities between patch versions.

**Comment by calmh** [comment]
@nottinhill Perhaps you can clarify what is useless so that it can be improved? I see nothing on your blog post that isn't covered in https://github.com/syncthing/syncthing/wiki/Firewalls-and-Port-Forwards (network wise) and, as Audrius notes, the stuff about protocol and Go versions is incorrect.

**Comment by nottinhill** [comment]
Except that you are recommending it on official docks for your app and fail to provide guidance. 10 minutes of your time to enhance the wiki, saving hours of research for hundrets of users, this kind of thinking is what you lack, mate.                                                                                                                                                                                                                                                                          Bitte beachten: Diese Mail wurde von Unterwegs gesendet.                                                                                                                                                                                                                                         Von: Audrius ButkeviciusGesendet: Samstag, 28. März 2015 16:36An: syncthing/syncthingAntwort an: syncthing/syncthingCc: Stephan KristynBetreff: Re: [syncthing] Docker and Port Forwarding (#1535)You just don't know how to use docker, it has nothing todo with syncthing sadly.

—Reply to this email directly or view it on GitHub.

**Comment by AudriusButkevicius** [comment]
We recommend using docker to build it, not to run it.

**Comment by rumpelsepp** [comment]
https://github.com/syncthing/syncthing/wiki/Building-with-Docker

> The Docker based build image exactly replicates the official build process and is a quick way to get up and running with the full cross compiled stup.

It is talking about *building*. So @nottinhill where is the problem? A little site note for you: the wiki is public. So feel free to improve it. ;)

**Comment by nottinhill** [comment]
I will.
