### ISSUE TITLE
feature: hide ignored files from list of unsynced files

### ISSUE THREAD

**Issue by benapetr** [syncthing/syncthing#1538]
When you ignore a file it shouldn't list it as unsynced file, when you have thousands of ignored files, the list of unsynced files become huge and unusable and you can't watch the progress of files that are now transferred to server

**Comment by Zillode** [comment]
Well, some ppl like to verify which files are unsynced, including ignored ones.
Maybe we can add a checkbox to hide ignored items in the unsynced list (we welcome PRs for this!)

**Comment by AudriusButkevicius** [comment]
I guess this is actually a bug/oversight, as I thought it already hit all of that.

**Comment by benapetr** [comment]
Yes and that is why I call this a feature.

I would prefer to have ignore files not there by default and list trimmed
to like 100 files and another list called "list all unsynced files" that
would eventually display not just unsynced but also all files. Right now
"list of unsynced files" is completely useless on large repos because if
you got 5k+ files it just hang up the browser if you open it

**Comment by AudriusButkevicius** [comment]
Yeah that's a separate issue though, #1500

**Comment by benapetr** [comment]
No, this one is about making ignored files not in list of unsynced files,
which may be related but different feature

**Comment by dcarosone** [comment]
Can we move them to a new list / count of ignored files? That will address
all the use cases above

**Comment by calmh** [comment]
Ignored files no longer count as unsynced, at least after a reconnect.

**Comment by grogi** [comment]
I am still getting the same issue with 0.12.6... :(

**Comment by AudriusButkevicius** [comment]
you need to restart all instances simultaniously

**Comment by grogi** [comment]
That sounds more of a workaround, not a fix. 

Nevertheless, can I shut them all down, and then bring up one by one?

**Comment by AudriusButkevicius** [comment]
Yes, it is a workaround.
There is a big ticket for ignore refactor which would probably fix this.

As long as you can have them down all at the same time, even if for a short period of time, it will be fine.
