### ISSUE TITLE
Potentially useful protocol changes before v0.11

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#1544]
1. Adding flags to announcement/query messages or changing to string based address definitions.
2. Adding announcement signing (even if its via UDP just by sending public part, address and signature over the address)
3. Adding more flags to Devices in ClusterConfig, so that settings such as hard-coded IP addresses of devices and perhaps compression could be copied across when introducing.

**Comment by calmh** [comment]
1-2 I think are not something we need to do for v0.11 specifically (rather, it should be done when it's done, not in preparation), 3 should be covered by the new Options added on Device?

**Comment by AudriusButkevicius** [comment]
Yes, you are right, there is no urgency for these in reality, as we can roll them out at any point without a lot of hassle.
