### ISSUE TITLE
Suggest Default Port Change for Web UI

### ISSUE THREAD

**Issue by sez11a** [syncthing/syncthing#1547]
Port 8080 is the "default alternate web port" (see the [Wikipedia article](http://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers), widely used by many web applications, including the following list (and I'm sure there are more): 

- Apache Tomcat
- Glassfish
- JBoss/Wildfly
- Microsoft IIS in developer mode
- Any applications running on those platforms that might have been bundled with the app servers (Liferay, etc.). 

Web developers who use these platforms will probably understand that they need to move Syncthing to another port, but others may not. You could probably cut down on support/forum questions by changing the default port. My suggestion, which is what I use on my systems, is port 8088.

**Comment by AudriusButkevicius** [comment]
You are 3 days late:
https://github.com/syncthing/syncthing/pull/1528

**Comment by AudriusButkevicius** [comment]
Oh sorry, this is inverse of what was done I guess.

Don't think I fully agree, though, if its 8080 or 8384 you still need to know which port it is, hence there isn't much difference.

**Comment by sez11a** [comment]
Looking at the pull request, this is exactly what I was looking for (change it from 8080 to something else). If that's what was done, this can be closed. :-)
