### ISSUE TITLE
Last File Received Not Accurate

### ISSUE THREAD

**Issue by CodyPChristian** [syncthing/syncthing#1551]
Hello,

I'm noticing that Last File Received is not accurate at all. I have this setup in a 3-region cluster on 3 separated installs and out of all clusters/regions the Last File Received is at least 10-15 files behind what actually was the last file received.

Any ideas?

**Comment by AudriusButkevicius** [comment]
How do you know wether or not it's behind?

**Comment by CodyPChristian** [comment]
The actual files are in sync, the label in the UI just does not reflect the most recent file that was synced or received. I know in what order I sent files to the cluster so I can tell in what order they should have been synced.

**Comment by AudriusButkevicius** [comment]
They get synced once every rescan interval (which by default is 60 seconds), hence the order in which you send the files to the cluster is not necessarily preserved.

**Comment by AudriusButkevicius** [comment]
Can we close this, or do you still have concerns?
