### ISSUE TITLE
Document FolderSummary and FolderCompletion events in the Wiki

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#1555]
Just not to be forgotten.

**Comment by kozec** [comment]
Until this is closed, let me ask: FolderCompletion event looks like replacement for calling `/rest/db/completion`; Did I understood correctly?

**Comment by AudriusButkevicius** [comment]
Exactly.

**Comment by kozec** [comment]
Great. And by wild guess, other one would be for old `/rest/model`. Can I rely on FolderCompletion to be emited somehow regularly, or at least after DeviceConnected event?

**Comment by AudriusButkevicius** [comment]
Both of them are emitted when remote/local index gets updated, or after us running a scan, and while clients are actually connected and waiting for events.

**Comment by kozec** [comment]
Great, implemented. Thanks for those two, this pretty-much fixes high CPU load problem in ST-GTK (syncthing/syncthing-gtk#66). Are you planing events for remaining three calls that are to be called repeatedly (`system/error`, `system/status` and `system/connections`) ?

**Comment by AudriusButkevicius** [comment]
These are fairly light-weight.

**Comment by canton7** [comment]
As someone who knows less than he should about the API, would it make sense to publish errors on the events interface?

**Comment by AudriusButkevicius** [comment]
We could, the only problem is that if you arrive late to the party and read all events (which is expensive) you're not sure which ones were already dismissed.

**Comment by canton7** [comment]
That's a good point.

**Comment by calmh** [comment]
Done.
