### ISSUE TITLE
recursive duplication of a folder structure

### ISSUE THREAD

**Issue by umamiMike** [syncthing/syncthing#1559]
I am a user, not so much a developer yet.  As I was setting up sync via vpn I accidentally synced a parent folder as its own child folder and so had the folder and file structure duplicate itself down a LOONG way, fortunately the files were not large so it didn't cache out the hard drive.  I just thought I would bring it up.  It seems it should be able to catch a situation like that and not duplicate.  Thanks for your attention.

**Comment by AudriusButkevicius** [comment]
I feel this is a wont-fix.
There are too many ways you could still do even if we are super careful.

**Comment by calmh** [comment]
I don't think we can detect this reliable in all cases (i.e. with bind mounts and aliases and all other kinds of platform specific weirdness out there), so I'm not convinced we should necessarily try to catch the obvious cases either. Especially as there are valid configs out there that sync both a certain directory and a child of that same directory into different folders...
