### ISSUE TITLE
Feature: allow logging to be sent to file

### ISSUE THREAD

**Issue by lhoekenga** [syncthing/syncthing#1561]
When used with something like start-stop-daemon and told to background the process, it no longer is possible to capture the logs from stdout / stderr.  (I'm trying this is on a DroboFS w/ start-stop-daemon from BusyBox)

Could you offer the ability to specify a log file instead of / in addition to logging to stdout / stderr?

**Comment by AudriusButkevicius** [comment]
Just redirect stdout to file?

**Comment by AudriusButkevicius** [comment]
See: https://github.com/syncthing/syncthing/issues/411

**Comment by lhoekenga** [comment]
Sorry for the dupe.
