### ISSUE TITLE
OSX: Local discovery over IPv6 unavailable

### ISSUE THREAD

**Issue by vhbit** [syncthing/syncthing#1563]
I have that message on all available Macs although all of them are configured to use IPv6.

While debugging iOS version, I've found that IPv6 multicasting on iOS requires to configure IPV6_MULTICAST_IF and IPV6_ADD_MEMBERSHIP with an exact interface index set, i.e. passing 0 will not work.

I think that should do the trick on OS X too.

**Comment by calmh** [comment]
Hmm, we do this already I think, with the comparable Go API:s... [Here](https://github.com/syncthing/syncthing/blob/master/internal/beacon/multicast.go#L23) we join the group when listening and [here](https://github.com/syncthing/syncthing/blob/master/internal/beacon/multicast.go#L62) we do the send on a specific interface.. 

```
[P56IO] 2015/04/02 10:22:21.751814 beacon.go:30: DEBUG: recv 56 bytes from 172.21.21.222:21025
[P56IO] 2015/04/02 10:22:21.751890 multicast.go:65: DEBUG: write udp: no route to host on write to {ff32::5222 21026 lo0}
[P56IO] 2015/04/02 10:22:21.751946 broadcast.go:80: DEBUG: sent 56 bytes to 172.21.21.255:21025
[P56IO] 2015/04/02 10:22:21.752151 discover.go:319: DEBUG: discover: Received local announcement from 172.21.21.222:21025 for P56IOI7-MZJNU2Y-IQGDREY-DM2MGTI-MGL3BXN-PQ6W5BM-TBBZ4TJ-XZWICQ2
[P56IO] 2015/04/02 10:22:21.752178 multicast.go:68: DEBUG: sent 56 bytes to [ff32::5222%en0]:21026
[P56IO] 2015/04/02 10:22:21.752302 multicast.go:65: DEBUG: write udp: no route to host on write to {ff32::5222 21026 en1}
[P56IO] 2015/04/02 10:22:21.752415 multicast.go:65: DEBUG: write udp: no route to host on write to {ff32::5222 21026 en2}
[P56IO] 2015/04/02 10:22:21.752524 multicast.go:65: DEBUG: write udp: no route to host on write to {ff32::5222 21026 p2p0}
[P56IO] 2015/04/02 10:22:21.752664 multicast.go:65: DEBUG: write udp: no route to host on write to {ff32::5222 21026 awdl0}
[P56IO] 2015/04/02 10:22:21.752790 multicast.go:65: DEBUG: write udp: no route to host on write to {ff32::5222 21026 bridge0}
```

(sending successfully on `en0` above)

**Comment by AudriusButkevicius** [comment]
We join with a nil interface though.

**Comment by calmh** [comment]
True, but that works for me...

**Comment by calmh** [comment]
The above error ("discovery unavailable") is printed if we fail to resolve the UDP address or fail to listen. @vhbit If you run with `STTRACE=discover`, what's the actual error quoted by `discover: Start local v6: <some error>`?

**Comment by calmh** [comment]
I wonder why it works for me on 10.10 then...

**Comment by calmh** [comment]
I don't seem to have any interfaces that are UP and don't have MULTICAST capability (in ifconfig), only except is stf0 that is neither. @vhbit what does an ifconfig on your system report?

**Comment by calmh** [comment]
Also, does

```diff
diff --git a/internal/beacon/broadcast.go b/internal/beacon/broadcast.go
index 647bbc1..e3497b3 100644
--- a/internal/beacon/broadcast.go
+++ b/internal/beacon/broadcast.go
@@ -16,7 +16,7 @@ type Broadcast struct {
 }
 
 func NewBroadcast(port int) (*Broadcast, error) {
-       conn, err := net.ListenUDP("udp", &net.UDPAddr{Port: port})
+       conn, err := net.ListenUDP("udp4", &net.UDPAddr{Port: port})
        if err != nil {
                return nil, err
        }
diff --git a/internal/beacon/multicast.go b/internal/beacon/multicast.go
index 557c765..51c4f24 100644
--- a/internal/beacon/multicast.go
+++ b/internal/beacon/multicast.go
@@ -16,11 +16,11 @@ type Multicast struct {
 }
 
 func NewMulticast(addr string) (*Multicast, error) {
-       gaddr, err := net.ResolveUDPAddr("udp", addr)
+       gaddr, err := net.ResolveUDPAddr("udp6", addr)
        if err != nil {
                return nil, err
        }
-       conn, err := net.ListenMulticastUDP("udp", nil, gaddr)
+       conn, err := net.ListenMulticastUDP("udp6", nil, gaddr)
        if err != nil {
                return nil, err
        }
```

make any difference on your system? Currently there's nothing inherently v4 or v6 about the broad- vs multicast sockets; perhaps there's something enabled or disabled around v4 multicast on your system that's not the case on mine...

**Comment by vhbit** [comment]
The same result for `ifconfig` - multicast is enabled on all interfaces but `stf0`.

Patches you've provided make port 21025 IPv4 only, but unfortunately IPv6 is still unbound. I have no ideas why it might happen - if you're using 10.10 the only difference between our setups should be drivers and routers.

**Comment by calmh** [comment]
OK, so this should probably be refactored for a separate socket (reader+writer) per interface.

**Comment by vhbit** [comment]
JFYI, just reproduced it on old machine with 10.9.

**Comment by calmh** [comment]
@vhbit How does ^ work for you?

**Comment by vhbit** [comment]
@calmh checked https://github.com/calmh/syncthing/commit/65d36d6e90a2a97d1a3c5d71ecd76723dc2c4f70, it worked fine
