### ISSUE TITLE
Problem: App wont install on Android

### ISSUE THREAD

**Issue by Lighter007** [syncthing/syncthing#1565]
Hi!
I´ve got a problem with the Android App because I can´t install it. It starts the android installer when you use the .apk directly and Google Play Store also begins but the actual installing progress doesn´t start. There are just this blue lines going from left to right again and again.
Phone: LG-P880
Android Version: 4.1.2
Fix please, I love syncthing ;)

**Comment by AudriusButkevicius** [comment]
Wrong repo:
https://github.com/syncthing/syncthing-android
