### ISSUE TITLE
Ubuntu/Debian package archive

### ISSUE THREAD

**Issue by pedrocr** [syncthing/syncthing#157]
This is a wishlist item. It would be really nice if there was an Ubuntu/Debian PPA that packaged syncthing so it was easy to install it and keep it updated on those platforms.

**Comment by bobcanthelpyou** [comment]
Searched for deb-packages of Syncthing and found the issue here and a bug report for a Debian package: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=749887
