### ISSUE TITLE
Transfer very slow

### ISSUE THREAD

**Issue by davidak** [syncthing/syncthing#1572]
the 3 nodes are an the same network, gigabit ethernet.
2x OS X, 1x Ubuntu, modern hardware

the transfer rate varies from 0 and 35MB/s and very long only some KB!
also the cpu load is very high.

![sync](https://cloud.githubusercontent.com/assets/91113/6970967/6de536ec-d979-11e4-93b0-f8624164a7ab.png)

**Comment by AudriusButkevicius** [comment]
Keep the web ui closed, or try the beta.

**Comment by jumoog** [comment]
maybe your cpu sucks your use high compression?

**Comment by davidak** [comment]
@AudriusButkevicius yes, that helps. cpu load 10-15% instead of 300% and the transfer is now complete!
