### ISSUE TITLE
SyncThing substancially reduces battery life on large folders (Windows)

### ISSUE THREAD

**Issue by cbuschardt** [syncthing/syncthing#1574]
The problem appears to be the periodic directory scan.

The WIN32 API makes it easy to block on changes to a directory sub-tree.
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365261(v=vs.85).aspx 

If it comes to it, I wouldn't mind donating the code!
I'm unfamiliar with Go and more importantly how to access C ABI functions from it.

**Comment by wweich** [comment]
https://github.com/syncthing/syncthing-inotify can already do this.
For Windows you should take a look at [SyncTrayzor](https://discourse.syncthing.net/t/synctrayzor-windows-host-for-syncthing-installer-auto-start-built-in-browser-tray-icon-folder-watcher-and-more/). It has inotify built in, hides the DOS box and has a tray icon.
