### ISSUE TITLE
0.11 doesn't work on windows

### ISSUE THREAD

**Issue by benapetr** [syncthing/syncthing#1575]
When I start last beta I get this error:

[monitor] 14:13:27 FATAL: log file: open ${config}/syncthing.log: The system can
not find the path specified.

**Comment by Moter8** [comment]
Can reproduce on Windows 10 Pro Technical Preview 64-Bit Build 9926.

```
D:\Downloads\W10DL\syncthing-windows-amd64-v0.11.0-beta1>syncthing.exe
[monitor] 17:38:56 FATAL: log file: open ${config}/syncthing.log: The system cannot find the path specified.
```

**Comment by JensMagnus** [comment]
Just start it with "syncthing.exe -logfile -".
Works fine here, you can optionally add the -no-console too.

**Comment by Moter8** [comment]
@JensMagnus Thanks!

Workaround so people don't have to open cmd etc:

Download this [bat file](https://gist.github.com/Moter8/549590d43299ff68f492) by rightclicking on the "Raw" button and on "Save URL as...". Move the bat file into the folder where syncthing.exe is at. Double-click the bat file to start Syncthing.

**Comment by calmh** [comment]
Whoops.
