### ISSUE TITLE
Massive logs

### ISSUE THREAD

**Issue by borissamardzija** [syncthing/syncthing#1579]
Hi,

is there any possibility to limit log size? I am transitioning from BTsync, and hitting various issues...

Today, I noticed that 5GB's is missing so I investigated a bit, it seems syncthing and SyncTrayzor ate ~6GB of logs.

![1](https://cloud.githubusercontent.com/assets/1290335/6989867/65ecb1d4-da61-11e4-859d-26a9c8043175.png)

**Comment by wweich** [comment]
This Logs aren't directly from syncthing, but from SyncTrayzor.
You should open a ticket there: https://github.com/canton7/SyncTrayzor/issues

**Comment by calmh** [comment]
Syncthing does create a log file as well on windows, but it's fairly low volume and emptied on each startup so should not grow to ridiculous sizes.

**Comment by canton7** [comment]
@borissamardzija, mind taking a look at canton7/SyncTrayzor#42?
