### ISSUE TITLE
Sharing directory request

### ISSUE THREAD

**Issue by volkisegler** [syncthing/syncthing#1580]
Hi there,

I have the Windows 64 bit version an two android gadgets. When sharing an android-directory, the sharing request appears in the windwos system browser and I can confirm sharing.

However, I can not share a directory of my windows computer. The request can be directed to either of the android gadgets but newer shows up there. Is this a fault or am I missing something?

Thanks for helping,

Volker

**Comment by Zillode** [comment]
dup https://github.com/syncthing/syncthing-android/issues/295
