### ISSUE TITLE
Provide /post/rescaninterval

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing#1591]
Enable external programs to set the rescan interval for a folder
See https://discourse.syncthing.net/t/default-rescan-interval/2191/5

**Comment by AudriusButkevicius** [comment]
What? Just post the config which has that?

**Comment by Zillode** [comment]
Posting a config requires a restart, this option should only be there if there is an inotify client connected

**Comment by AudriusButkevicius** [comment]
The fact that we are unable to modify settings without restarting doesn't mean that we should add extra api calls as hacks around our incompetence.

**Comment by Zillode** [comment]
Sorry, I should have split my sentence in two. It should also be non persistent, such that it will only be set if an inotify client is connected (although it would not cover a disconnect, but this won't happen too often I guess)

**Comment by AudriusButkevicius** [comment]
To me this sounds just like some black magic. If you are able to setup inotify, you should be able to adjust the rescan interval. This temporary runtime value perhaps makes sense, but I am not too comfortable with that.

**Comment by calmh** [comment]
I don't think it's too bad. I was thinking in terms of a parameter to /rest/scan, `/rest/scan?folder=default&next=86400` to reschedule the next scan into the future, one time. I haven't looked at if that makes sense in the code yet. :)

**Comment by AudriusButkevicius** [comment]
Right, I don't mind extra parameters to functions we export. Given it's used once within the invocation of the function. If it's reused, then it should be a config value, and you should modify the config.
