### ISSUE TITLE
Anonymous data reporting doesn't work on IPv6-only hosts. (still)

### ISSUE THREAD

**Issue by DarkHelmet433** [syncthing/syncthing#1592]
Presumably such things are fairly rare, but it does make a small amount of noise in the logs.

07:51:26 INFO: Usage report: Post https://data.syncthing.net/newdata: dial tcp 194.126.249.13:443: can't assign requested address
etc.

The log collector has an ipv4 address only.  Obviously the workaround is to turn it back off, but I wanted to actually give you the stats.

**Comment by calmh** [comment]
Indeed. I've added an `AAAA`, should work better now.

**Comment by DarkHelmet433** [comment]
For what its worth, this doesn't actually work properly.

[NKNUY] 06:52:44 INFO: Usage report: Post https://data.syncthing.net/newdata: dial tcp 194.126.249.13:443: no route to host

# host data.syncthing.net
data.syncthing.net has address 194.126.249.13
data.syncthing.net has IPv6 address 2001:470:28:4d6::13

I checked with tcpdump, it only tries the ipv4 address.

**Comment by calmh** [comment]
Huh. I'll look into it.

**Comment by DarkHelmet433** [comment]
I did some quick searches, and came across things like this:
https://groups.google.com/forum/#!topic/golang-nuts/_VgvTySj25o
They're talking about DualStack transport etc.

Following the bug report links I ended up
https://github.com/golang/go/issues/8573
and
https://github.com/golang/go/issues/8847

They're not really directly applicable but it seems there are some weird things going on with the resolver stub.  The clients I'm seeing this behavior on use a resolv.conf resolver pointing to 127.0.0.1 but the rest of the connectivity is ipv6-only.  I'm pondering whether there could be a go heuristic based on the transport to the resolver in use.

The clients *do* reach and use the v6 discovery server:
udp6://announce-v6.syncthing.net:22026

**Comment by calmh** [comment]
The go network stack is rather clumsy in regards to dual stack stuff, so I wouldn't be surprised if there's a bug there. In go 1.5 the socket connects are supposed to do "happy eyeballs" which is better. On the discovery side of things the v6 server has *only* an aaaa record, so there's no way for go to screw up the connect. :)

**Comment by DarkHelmet433** [comment]
I was going to ask if data-v6.syncthing.net as an aaaa-only fallback makes sense but then I remembered it is "only" telemetry, go 1.5 is in rc1, and I haven't exhausted options for forcing the issue locally yet.

Of course, it doesn't make any difference at all while the v6 listener on data.syncthing.net is refusing connections.

**Comment by calmh** [comment]
So, data.syncthing.net now actually speaks v6 correctly. In theory that means it *should* work as is, if not we'll revisit once we're running under Go 1.5. [These builds](http://build.syncthing.net/job/syncthing/) are compiled using rc1 so could be tested now as well.
