### ISSUE TITLE
Tidy up the REST interface

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#1593]
The URL:s are somewhat of a mess and don't follow a pattern or system where we could. Take the time to rethink it and make a breaking change some time before v1.0.

**Comment by calmh** [comment]
i.e. maybe something along these lines

```go
	// The GET handlers
	getRestMux := http.NewServeMux()
	getRestMux.HandleFunc("/rest/db/completion", withModel(m, restGetCompletion))
	getRestMux.HandleFunc("/rest/db/file", withModel(m, restGetFileStatus))
	getRestMux.HandleFunc("/rest/db/ignores", withModel(m, restGetIgnores))
	getRestMux.HandleFunc("/rest/db/need", withModel(m, restGetNeed))
	getRestMux.HandleFunc("/rest/db/status", withModel(m, restGetModel))
	getRestMux.HandleFunc("/rest/db/tree", withModel(m, restGetTree))
	getRestMux.HandleFunc("/rest/events", restGetEvents)
	getRestMux.HandleFunc("/rest/stats/device", withModel(m, restGetDeviceStats))
	getRestMux.HandleFunc("/rest/stats/folder", withModel(m, restGetFolderStats))
	getRestMux.HandleFunc("/rest/svc/deviceid", restGetDeviceID)
	getRestMux.HandleFunc("/rest/svc/lang", restGetLang)
	getRestMux.HandleFunc("/rest/svc/report", withModel(m, restGetReport))
	getRestMux.HandleFunc("/rest/system/browse", restGetAutocompleteDirectory)
	getRestMux.HandleFunc("/rest/system/config", restGetConfig)
	getRestMux.HandleFunc("/rest/system/config/insync", restGetConfigInSync)
	getRestMux.HandleFunc("/rest/system/connections", withModel(m, restGetConnections))
	getRestMux.HandleFunc("/rest/system/discovery", restGetDiscovery)
	getRestMux.HandleFunc("/rest/system/error", restGetErrors)
	getRestMux.HandleFunc("/rest/system/ping", restPing)
	getRestMux.HandleFunc("/rest/system/status", restGetSystem)
	getRestMux.HandleFunc("/rest/system/upgrade", restGetUpgrade)
	getRestMux.HandleFunc("/rest/system/version", restGetVersion)

	// The POST handlers
	postRestMux := http.NewServeMux()
	postRestMux.HandleFunc("/rest/db/prio", withModel(m, restPostBump))
	postRestMux.HandleFunc("/rest/db/ignores", withModel(m, restPostIgnores))
	postRestMux.HandleFunc("/rest/db/override", withModel(m, restPostOverride))
	postRestMux.HandleFunc("/rest/db/scan", withModel(m, restPostScan))
	postRestMux.HandleFunc("/rest/system/config", withModel(m, restPostConfig))
	postRestMux.HandleFunc("/rest/system/discovery", restPostDiscoveryHint)
	postRestMux.HandleFunc("/rest/system/error", restPostError)
	postRestMux.HandleFunc("/rest/system/error/clear", restClearErrors)
	postRestMux.HandleFunc("/rest/system/ping", restPing)
	postRestMux.HandleFunc("/rest/system/reset", withModel(m, restPostReset))
	postRestMux.HandleFunc("/rest/system/restart", restPostRestart)
	postRestMux.HandleFunc("/rest/system/shutdown", restPostShutdown)
	postRestMux.HandleFunc("/rest/system/upgrade", restPostUpgrade)
```

**Comment by vvllaadd** [comment]
Please add a method for retrieving a folder ID based on a folder path. I would like to know if a particular folder on my web server is shared or not via Syncthing. To achieve this, I currently need to get the whole config (GET /rest/config), parse the list of "Folders" and match the path. It is very inefficient.

**Comment by vvllaadd** [comment]
I have tried to replace Dropbox with BitTorrent Sync. That failed, because of the sucky API BitTorrent Sync 2.0 provides and other various reasons. I am now considering to replace BitTorrent Sync with Syncthing, but this app seems to be designed for very very limited usage. If I have 100 users, each with 3 devices, each wanting to sync 10 different devices, that brings the number of folders to 1000. Getting the full config with that long list of folders, each with useless details attached to it, and full config which includes a useless list of devices, just to let the user know that one folder on the server is shared or not, is most probably going to get the server unusable. And this is very modest usage. Imagine a university with 2000 students.

**Comment by calmh** [comment]
You're right, that's probably not the currently envisioned use case. Per https://data.syncthing.net "almost noone" has more than ~10 devices or folders in their cluster.

**Comment by garagatyi** [comment]
```"almost noone" has more than ~10 devices or folders in their cluster```
Probably because of poor support of thousands of folders. 

I wanted to use ST in that way, but found that addition of new folders require restarting synchronization for all of them. So it will be too slowly.
Another point is that I have to add new folder to ST with: parse config -> add new folder to config -> send whole config to ST API

**Comment by calmh** [comment]
@garagatyi Maybe. Or maybe because it's a niche use case. But this is not the issue that makes or breaks that use case, so perhaps open issues for the suggested improvements?

**Comment by garagatyi** [comment]
https://github.com/syncthing/syncthing/issues/1596
https://github.com/syncthing/syncthing/issues/1597

**Comment by vvllaadd** [comment]
Talking about niche, ST is currently addressing a very tiny one. It is designed only for IT people with good technical knowledge who mostly wish to use it for themselves and less with other users. It can work in some small groups of peoples, if there is always the IT person available to configure folders and devices on the server. Most people use nowadays an online server for storing files and not their personal computers. If ST would provide a way for the IT person to allow the layperson to add and remove folders itself, through a simplified user interface (which uses the REST API) then ST might start be adopted by the mainstream and not just developers.
In it's current form, ST is almost useless for a company as small as three employees, if the company doesn't have a full-time knowledgeable person to manage devices and folders on the main install of ST.

**Comment by calmh** [comment]
@vvllaadd Can you please take this to the forum or something, I'm trying to keep this issue clean for the purpose it was created?

**Comment by vvllaadd** [comment]
#calmh I have deleted the comment, with the purpose of pasting it in the forum, but lost the clipboard :P Anyway, I hope you just got my perspective on the app and hopefully some day this superb app you've created will be accessible to more people. Keep up to good work and thank you for sharing!
