### ISSUE TITLE
Add overview of lately synced files

### ISSUE THREAD

**Issue by hashworks** [syncthing/syncthing#1594]
Since I'm syncing my home directory I often get files synced which should be in the .stignore. A list of lately synced files helps for this, currently I only see the last one.

**Comment by step21** [comment]
yeah would be great. +1

**Comment by AudriusButkevicius** [comment]
Dup of #1683 (or vica versa) ?

**Comment by hashworks** [comment]
Yup. I'll close this one since you already added tags etc. on the other one.
