### ISSUE TITLE
Make it possible to start/stop synchronization of folder without restarting synchronization for all existing folders

### ISSUE THREAD

**Issue by garagatyi** [syncthing/syncthing#1597]
When I add new folder in ST (or remove existing), I have to restart synchronization for all existing folders to start synchronization of the new one.
It is slowing ST in the case when I add/remove folders frequently.

**Comment by benapetr** [comment]
You actually have to restart syncthing everytime you change something, even ignore patterns or anything else. It's extremely annoying and slows down sync of large folders by hours.... (for large folders it may take about hour for ST to even start up)

**Comment by AudriusButkevicius** [comment]
You don't need to restart after changing ignores.

**Comment by benapetr** [comment]
ST always tell me I have to and I do that

**Comment by benapetr** [comment]
in last release
