### ISSUE TITLE
Make it possible to configure explicitly ST system files path

### ISSUE THREAD

**Issue by garagatyi** [syncthing/syncthing#1598]
I don't want to keep .stfolder .stignore files in the folder I sync. 
It would be very useful to configure these files placement in the config.

**Comment by rumpelsepp** [comment]
`.stfolder` is there for reasons: https://github.com/syncthing/syncthing/issues/762

**Comment by AudriusButkevicius** [comment]
`.stignore` could eventually go in the config, but `.stfolder` and other folders related to archiving will most likely stay there.

**Comment by garagatyi** [comment]
@AudriusButkevicius can you explain why .stfolder can't be moved?

**Comment by calmh** [comment]
It's there to protect against a certain class of user errors; things like the folder being a disk that is not currently mounted.

**Comment by AudriusButkevicius** [comment]
I think the ticket @rumpelsepp pointed to explains the problem quite well.

**Comment by garagatyi** [comment]
ok, I understood your point.

**Comment by AudriusButkevicius** [comment]
I feel this can now be closed. Reopen if you still have concerns.
