### ISSUE TITLE
QR Code not fully visible on small Android screen

### ISSUE THREAD

**Issue by marclaporte** [syncthing/syncthing#1602]
And when touch screen is used to move QR code to be fully visible, it's the background page which moves, and not the overlay with the QR code.

This was using the web interface (Bootstrap) on an older small Android phone. On a modern phablet, it works well.

![2015-04-07-syncthing-qrcode-small-screen](https://cloud.githubusercontent.com/assets/1004261/7029715/a66b111e-dd2d-11e4-8767-d87f14585ade.png)

**Comment by bigbear2nd** [comment]
I am not sure if this is a bug.. I can still scroll on my device to see the full QR code..

**Comment by Zillode** [comment]
I tested this for Android 2.3.3 and this is definitely a bug in the webgui.

**Comment by bigbear2nd** [comment]
How about simply changing the order? 
![unbenannt](https://cloud.githubusercontent.com/assets/7719800/7262279/8d0e3dee-e878-11e4-8f17-c21714021afd.PNG)

Or would you like to make the modal scrollable / different in xs instead?

**Comment by Zillode** [comment]
@bigbear2nd Your PR is welcome

**Comment by bigbear2nd** [comment]
@Zillode I am not sure if i understand. I tried a (workaround and not nice) solution which is within my skills. :wink: in the Pull request @calmh mentioned that it is not what solves the problem and I agree. 

I think a more skilled person should take over here. :wink:

**Comment by calmh** [comment]
So, it seemed to me like the scrolling issue is a browser bug, as the modal *is* scrollable on for example my iPhone. If we can work around that somehow, that'd be nice. If we think the QR code is more important than the text, changing the order is a workable workaround too (but won't someone just complain that they can see the QR code but not the text?). But breaking it out into two separate dialogs on xs screens I don't like, since this negatively affects all other small screens where it actually does work.

**Comment by Zillode** [comment]
Ah I missed that PR. Note that scrolling actually works on (1) newer Android versions and (2) when using a proper browser on old devices.

**Comment by calmh** [comment]
Sounds like "device bug, wontfix" to me?

**Comment by wweich** [comment]
If you want to share the device id via QR Code, you will have an app installed to scan that QR code (at least on the receiving device).
So one could assume, that you also have such an app installed on your current device and you can simply share the device id from within the android app to that app to show the QR code. (tested with barcode scanner)

**Comment by lkwg82** [comment]
no more activity on this topic, I ll close it as 'wont fix'

**Comment by marclaporte** [comment]
Hi!

I tested again on what I think was the old phone I used to report this (Motorola XT860 with Android 2.3.6) and Syncthing is unable to upgrade from 0.6.6 to 0.7.x via F-Droid.

Let's just give up and focus on more modern devices.

Thanks!
