### ISSUE TITLE
Devices stay unconnected ("connection attempt failed")

### ISSUE THREAD

**Issue by newtom80** [syncthing/syncthing#1611]
Hi,

I unpacked synthing v0.10.30 to two computers, added firewall exceptions on both computers, introduced the two devices to each other based on their IDs, then added and shared a folder between the two devices, and finally, restarted syncthing on both ends.

Unfortunately, the devices cannot connect to each other. This is what the trace says (on both sides):

c:\Programs\SyncThing>syncthing.exe
[monitor] 2015/04/08 21:49:51.032149 monitor.go:64: INFO: Log output saved to file "C:\Users\XXXXXXX\AppData\Local\Syncthing\syncthing.log"
[monitor] 2015/04/08 21:49:51.032149 monitor.go:95: INFO: Starting syncthing
[QHAP4] 2015/04/08 21:49:51.546156 main.go:398: INFO: syncthing v0.10.30 (go1.4.2 windows-amd64 default) unknown-user@syncthing-builder 2015-03-29 07:46:44 UTC
[QHAP4] 2015/04/08 21:49:51.546156 main.go:399: INFO: My ID: XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX
[QHAP4] 2015/04/08 21:49:51.569159 main.go:665: INFO: Starting web GUI on http://127.0.0.1:8080/
[QHAP4] 2015/04/08 21:49:51.894191 upnp.go:97: INFO: Starting UPnP discovery...
[QHAP4] 2015/04/08 21:49:57.894791 upnp.go:124: INFO: UPnP discovery complete (found 0 devices).
[QHAP4] 2015/04/08 21:49:57.894791 main.go:916: INFO: Starting local discovery announcements
[QHAP4] 2015/04/08 21:49:57.894791 discover.go:86: INFO: Local discovery over IPv6 unavailable
[QHAP4] 2015/04/08 21:49:57.894791 main.go:921: INFO: Starting global discovery announcements
[QHAP4] 2015/04/08 21:49:57.895791 main.go:570: OK: Ready to synchronize Sync_Folder (read-write)
[QHAP4] 2015/04/08 21:49:57.895791 main.go:586: INFO: Device XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX is "PC1" at [dynamic]
[QHAP4] 2015/04/08 21:49:57.895791 main.go:586: INFO: Device YYYYYYY-YYYYYYY-YYYYYYY-YYYYYYY-YYYYYYY-YYYYYYY-YYYYYYY-YYYYYYY is "PC2" at [dynamic]
[QHAP4] 2015/04/08 21:49:57.895791 connections.go:145: DEBUG: listening on 0.0.0.0:22000
[QHAP4] 2015/04/08 21:49:57.955797 rwfolder.go:242: INFO: Completed initial scan (rw) of folder Sync_Folder
[QHAP4] 2015/04/08 21:50:28.935895 connections.go:222: DEBUG: dial YYYYYYY-YYYYYYY-YYYYYYY-YYYYYYY-YYYYYYY-YYYYYYY-YYYYYYY-YYYYYYY III.III.III.III:22000
[QHAP4] 2015/04/08 21:50:49.928994 connections.go:236: DEBUG: dial tcp III.III.III.III:22000: ConnectEx tcp: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

<the last two messages repeat indefinitely>

Any help would be appreciated!
Tamas

**Comment by AudriusButkevicius** [comment]
Are they both behind a NAT?
The message probably just informs about a timeout.

**Comment by newtom80** [comment]
Yes, they are behind their own NATs and firewalls. BT Sync works flawlessly between them, though. (But I would like to move away from that piece of software.)

**Comment by AudriusButkevicius** [comment]
You'll have to enable UPnP or enable port forwarding on one of the machines for them to be able to connect.

There are plans of a UDP based solution which helps get around firewalls, but that does not exist today.

**Comment by newtom80** [comment]
Oh, that's a pity.
