### ISSUE TITLE
Panic on v10.30

### ISSUE THREAD

**Issue by Supersonic24** [syncthing/syncthing#1612]
Panic logs generating from one ldb file on version 10.30.  Running on OS X 10.  Should I delete the .ldb file noted in log file or is there a bigger issue here?  Thought this was fixed?

**=============== Terminal Output ===============**
[monitor] 17:19:51 INFO: Starting syncthing
[TNCPV] 17:19:51 INFO: syncthing v0.10.30 (go1.4.2 darwin-amd64 default) unknown-user@syncthing-builder 2015-03-29 07:46:44 UTC
panic: leveldb/table: corruption on data-block (pos=189405): checksum mismatch, want=0xf245488d got=0x35b5bd9b [file=1100503.ldb]
[monitor] 17:19:52 WARNING: Panic detected, writing to "/Users/username/Library/Application Support/Syncthing/panic-20150408-171952.log"
[monitor] 17:19:52 WARNING: Please create an issue at https://github.com/syncthing/syncthing/issues/ with the panic log attached
[monitor] 17:19:52 INFO: Syncthing exited: exit status 2
[monitor] 17:19:53 WARNING: 4 restarts in 46.877536719s; not retrying further
logout

**=============== Panic Log File ==================**
[TNCPV] 17:19:51 INFO: syncthing v0.10.30 (go1.4.2 darwin-amd64 default) unknown-user@syncthing-builder 2015-03-29 07:46:44 UTC
Panic at 2015-04-08T17:19:52-04:00
panic: leveldb/table: corruption on data-block (pos=189405): checksum mismatch, want=0xf245488d got=0x35b5bd9b [file=1100503.ldb]

goroutine 1 [running]:
github.com/syncthing/syncthing/internal/db.ldbCheckGlobals(0xc20800c160, 0xc209421e48, 0x5, 0x8)
	/go/src/github.com/syncthing/syncthing/internal/db/leveldb.go:1030 +0xd46
github.com/syncthing/syncthing/internal/db.NewFileSet(0xc208104170, 0x5, 0xc20800c160, 0xc2083f7e70)
	/go/src/github.com/syncthing/syncthing/internal/db/set.go:56 +0x1be
github.com/syncthing/syncthing/internal/model.(*Model).AddFolder(0xc2087341c0, 0xc208104170, 0x5, 0xc2080637e0, 0x14, 0xc2080f0ea0, 0x2, 0x4, 0x0, 0x12c, ...)
	/go/src/github.com/syncthing/syncthing/internal/model/model.go:1046 +0x19e
main.sanityCheckFolders(0xc208050480, 0xc2087341c0)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:686 +0x173
main.syncthingMain()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:519 +0x1a95
main.main()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:362 +0x20ed

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [select]:
github.com/syncthing/syncthing/internal/events.(*Subscription).Poll(0xc20801e6a0, 0xdf8475800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:173 +0x3bf
github.com/syncthing/syncthing/internal/events.(*BufferedSubscription).pollingLoop(0xc20802e340)
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:209 +0x48
created by github.com/syncthing/syncthing/internal/events.NewBufferedSubscription
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:203 +0x1c4

goroutine 8 [chan receive]:
main.trackCPUUsage()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0xec
created by main.init·3
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x25

goroutine 10 [chan receive]:
github.com/syncthing/syncthing/internal/config.(*Wrapper).Serve(0xc208050480)
	/go/src/github.com/syncthing/syncthing/internal/config/wrapper.go:79 +0x75
created by github.com/syncthing/syncthing/internal/config.Wrap
	/go/src/github.com/syncthing/syncthing/internal/config/wrapper.go:54 +0x133

goroutine 11 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc2080a80e0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x21e
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236 +0x24c

goroutine 12 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc20800c160)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:120 +0x48c
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:126 +0x849

goroutine 13 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc20800c160)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_state.go:73 +0x14a
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:127 +0x863

goroutine 14 [runnable]:
github.com/syndtr/gosnappy/snappy.emitLiteral(0xc209d85c41, 0xfee96, 0xfee96, 0xc209af4093, 0x1f, 0x231d45, 0x20)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/gosnappy/snappy/encode.go:15
github.com/syndtr/gosnappy/snappy.Encode(0xc209d26000, 0x15ead7, 0x15ead7, 0xc209a86000, 0x12c92b, 0x29fdd8, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/gosnappy/snappy/encode.go:129 +0x4cb
github.com/syndtr/goleveldb/leveldb/table.(*Writer).writeBlock(0xc20807e300, 0xc20807e358, 0x2, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/writer.go:171 +0x225
github.com/syndtr/goleveldb/leveldb/table.(*Writer).finishBlock(0xc20807e300, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/writer.go:225 +0x7e
github.com/syndtr/goleveldb/leveldb/table.(*Writer).Append(0xc20807e300, 0xc2096001a0, 0xc9, 0xd0, 0xc209958184, 0x12c7dc, 0x12c7e4, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/writer.go:258 +0x3ef
github.com/syndtr/goleveldb/leveldb.(*tWriter).append(0xc2085ae120, 0xc2096001a0, 0xc9, 0xd0, 0xc209958184, 0x12c7dc, 0x12c7e4, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table.go:481 +0x303
github.com/syndtr/goleveldb/leveldb.(*tableCompactionBuilder).appendKV(0xc2090c6000, 0xc2096001a0, 0xc9, 0xd0, 0xc209958184, 0x12c7dc, 0x12c7e4, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:412 +0x200
github.com/syndtr/goleveldb/leveldb.(*tableCompactionBuilder).run(0xc2090c6000, 0xc20917e0d0, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:530 +0x7aa
github.com/syndtr/goleveldb/leveldb.(*DB).compactionTransact(0xc20800c160, 0x6545d0, 0xb, 0xd72740, 0xc2090c6000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:215 +0x277
github.com/syndtr/goleveldb/leveldb.(*DB).tableCompaction(0xc20800c160, 0xc209186000, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:596 +0x10d4
github.com/syndtr/goleveldb/leveldb.(*DB).tableAutoCompaction(0xc20800c160)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:641 +0x50
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc20800c160)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:833 +0x3a0
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:130 +0x8a7

goroutine 15 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc20800c160)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:759 +0x283
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:131 +0x8c1

goroutine 16 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc20800c160)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x197
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:132 +0x8db

goroutine 19 [select]:
github.com/syncthing/syncthing/internal/model.(*ProgressEmitter).Serve(0xc209130d80)
	/go/src/github.com/syncthing/syncthing/internal/model/progressemitter.go:48 +0x8b8
created by github.com/syncthing/syncthing/internal/model.NewModel
	/go/src/github.com/syncthing/syncthing/internal/model/model.go:117 +0x60c

goroutine 20 [sleep]:
github.com/syncthing/syncthing/internal/model.func·029()
	/go/src/github.com/syncthing/syncthing/internal/model/util.go:17 +0x4a
created by github.com/syncthing/syncthing/internal/model.deadlockDetect
	/go/src/github.com/syncthing/syncthing/internal/model/util.go:35 +0xd6

goroutine 21 [sleep]:
github.com/syncthing/syncthing/internal/model.func·029()
	/go/src/github.com/syncthing/syncthing/internal/model/util.go:17 +0x4a
created by github.com/syncthing/syncthing/internal/model.deadlockDetect
	/go/src/github.com/syncthing/syncthing/internal/model/util.go:35 +0xd6

**Comment by AudriusButkevicius** [comment]
Dup #987

**Comment by AudriusButkevicius** [comment]
You probably need to remove your index and let it reindex.

**Comment by Supersonic24** [comment]
Remove the entire index folder or just the .ldb noted in the log file?

**Comment by AudriusButkevicius** [comment]
Don't know honestly, not familiar enough with leveldb internals. Try the file first, if that still causes issues, then try zapping the whole index.
