### ISSUE TITLE
Index reset should result in conflicts to resolve

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#1613]
If a device resets it's index (i.e. the files are removed or corrupt for whatever reason), and files are not in sync with the cluster, we should take care not to overwrite them when it rejoins the cluster. Differences should be marked and handled as conflicts.

**Comment by AudriusButkevicius** [comment]
Looks good, but can we have a test that tests how the conflict is resolved after the device comes back?

**Comment by calmh** [comment]
Yeah I need to cook some integration tests for "initial merge" and stuff like that anyway, I'll get that included here.
