### ISSUE TITLE
Total transfer rate not updating (v0.11)

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#1615]
![screen shot 2015-04-09 at 10 19 38](https://cloud.githubusercontent.com/assets/125426/7062896/05935758-dea2-11e4-9876-502ecbce01e8.png)

**Comment by AudriusButkevicius** [comment]
I thought I fixed that.
Did you rebuild your assets?

**Comment by AudriusButkevicius** [comment]
Oh, I fixed totals, rather than the rates.
