### ISSUE TITLE
DCIM folder not syncronized

### ISSUE THREAD

**Issue by craibuc** [syncthing/syncthing#1620]
## Summary

The contents of the DCIM folder are not being synchronized between my Android device and my laptop.

### Workstation

819 files:
![screen shot 2015-04-09 at 10 30 26](https://cloud.githubusercontent.com/assets/216592/7070365/247dfd88-dea4-11e4-8036-a079ac94c05a.png)

?:
![screen shot 2015-04-09 at 10 30 39](https://cloud.githubusercontent.com/assets/216592/7070402/5bb7cc8e-dea4-11e4-9b90-1c44462f11ad.png)

### Camera

866 files:
 
![screenshot_2015-04-09-10-18-28](https://cloud.githubusercontent.com/assets/216592/7070293/a1659af0-dea3-11e4-8cac-39ad4f1dbbd2.png)

Marked as 'up to date':

![screenshot_2015-04-09-10-19-05](https://cloud.githubusercontent.com/assets/216592/7070304/bed6f6c4-dea3-11e4-8898-12362b1993b7.png)

### OSX
 - OSX: 10.10.3
 - Syncthing: v0.10.30

### Android
 - Android: 4.2.1
 - Syncthing: 0.5.28

**Comment by AudriusButkevicius** [comment]
Can you try opening the web ui on the phone and hitting rescan, and perhaps provide a screenshot of the web ui on the phone?

**Comment by craibuc** [comment]
## Web GUI

![screenshot_2015-04-09-11-00-02](https://cloud.githubusercontent.com/assets/216592/7070963/f259548e-dea7-11e4-88c5-dd065171c494.png)

### Devices
#### Camera
![screenshot_2015-04-09-11-00-22](https://cloud.githubusercontent.com/assets/216592/7071003/3547fa66-dea8-11e4-9878-01f9a22948c4.png)

#### Workstation
![screenshot_2015-04-09-11-00-34](https://cloud.githubusercontent.com/assets/216592/7071057/7f0dac2c-dea8-11e4-972f-a577bf834e99.png)

**Comment by AudriusButkevicius** [comment]
Well it seems that the folder is not shared with the workstation?

**Comment by wweich** [comment]
You should also disable the compression, as multimedia files cannot really be compressed and it will slow down your Android and the transfer.

**Comment by craibuc** [comment]
Fixed.  I enabled the device (toggled the checkbox to the right of the workstation's name) in the `camera` folder's `Devices` view.  After a minutes or so, I was prompted to authorize folder synchronization on my workstation.  Once authorized, sync'ing occurred rapidly.

BTW, is there a way to change the name of the `camera` folder to something more meaningful?

**Comment by wweich** [comment]
Once a folder name is set, it cannot be changed. But you can remove the folder from both devices and add it again with a different name.

**Comment by AudriusButkevicius** [comment]
@craibuc you should have closed the issue.
