### ISSUE TITLE
syncing is stuck.

### ISSUE THREAD

**Issue by chrismuench** [syncthing/syncthing#1622]
the folder is showing as up to date.  however it shows 12GB out of sync.  running the latest version on both sides.
![screenshot 2015-04-09 19 28 50](https://cloud.githubusercontent.com/assets/8158602/7081032/a270ec18-def0-11e4-91be-63e6a26ec1f3.png)

**Comment by AudriusButkevicius** [comment]
Can you get the json output from both sides from:
`/rest/db/file?folder=shows&file=<one of the out of sync files>`

**Comment by chrismuench** [comment]
and where do I get the full relative path?  Is there any logging available in the app?

**Comment by AudriusButkevicius** [comment]
relative path to the directory.
If your syncthings folder is at a/b/c and the absolute path which is stuck is a/b/c/d/e/f then the relative path of the file is d/e/f

**Comment by iglosiggio** [comment]
I have the same problem and GET /rest/need gave me no files in progress or queued, only in rest where the list of files that can't sync.

Can it be a time-related problem? Windows uses UTC -3 as the time in the clock. Linux uses UTC 0 and corrects it per-user (UTC -3 in my case). (Maybe a call to get the system hour doesn't get corrected by go stdlib)

**Comment by AudriusButkevicius** [comment]
I don't think it's timing relates. This is such a generic problem that bundling everything under the same ticket might not be a good idea. I guess start by asking on the forum so we could help you debug this. I doubt its timing related.

**Comment by iglosiggio** [comment]
Ok, finally syncthing synced when i put a new file on the unsynced PC (i was copying the files from my PC via smb://).

**Comment by calmh** [comment]
I think this is a valid issue, but taking it to #1765 as that has a little bit better subject and description.
