### ISSUE TITLE
Improve error message when Syncthing can't remove a folder due to having ignored files present in it

### ISSUE THREAD

**Issue by sez11a** [syncthing/syncthing#1626]
Currently, when someone deletes a folder that contains ignored files that were already synced before the ignore configuration was added, Syncthing displays a message like this: 

Apr 10 10:50:54 ds9 syncthing[9579]: [N5SUI] 10:50:54 INFO: Puller (folder "afc-share", dir "Jack-Ray/PICTURES"): delete: remove /home/sezovr/Documents/draid/afc-share/Jack-Ray/PICTURES: directory 
Apr 10 10:50:54 ds9 syncthing[9579]: [N5SUI] 10:50:54 WARNING: Folder "afc-share" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.

When Syncthing encounters this error, it should check to see if there's a file in the folder that matches a file in the ignore list. If it does, you can print a different error message in the log and on the console that tells the user that someone deleted the folder but an ignored file is still in it, and the user should take some action with the ignored file (delete it, move it, etc.) so Syncthing can continue syncing the folder.

**Comment by AudriusButkevicius** [comment]
This should get fixed by selective sync as you will not be able to exclude parts of directory.
Just need to get my stuff together and finish it.

**Comment by calmh** [comment]
Yeah that, plus #1631 so that we can nuke directories with ignored files in them.
