### ISSUE TITLE
Allow restarting 'stopped' folders without restarting syncthing (better removable disk support)

### ISSUE THREAD

**Issue by hickinbottoms** [syncthing/syncthing#1627]
I guess this issue is similar to the more generic #1597, but as the use case is different I'll separately list it in case the solution is different.
I have a folder present on a removable disk that is not mounted at the time syncthing starts (ST starts on boot, but the disk is encrypted and so is mounted when the user unlocks it).
The result of this is that ST always finds that folder "missing but in database" and puts it into the *STOPPED* state. There is then no way to restart that folder when I've mounted the disk without restarting ST completely. As reported elsewhere, this can be quite slow.
It would be nice to have a *RESTART* button or similar on that folder. A bonus would be a flag on the folder to say it was "removable" and then ST would periodically check if it had come back and, if so, restart it automatically.

**Comment by AudriusButkevicius** [comment]
Fixed in 0.11.

**Comment by hickinbottoms** [comment]
Excellent news -- sorry for the noise.
