### ISSUE TITLE
"No availabile source device" - sync is stuck

### ISSUE THREAD

**Issue by unfa** [syncthing/syncthing#1628]
Me and a friend are sharing a folder. It worked fine for two weeks, now one file is stuck.
On my side the GUI says it's syncing 77% and that's not changing. No error messages.
The file is on my machine and the remote machine is unable to fetch it for some reason.

I have experienced numerous system crashes recently, maybe that could have caused the trouble?
I can remove that file, but it doesn't seem like a solution to me.

Here's a log from the friend's machine (I removed IPs, names and syncthing IDs):

	[monitor] 16:37:17 INFO: Starting syncthing
	[OCBUJ] 16:37:18 INFO: syncthing v0.10.30 (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-03-29 07:46:44 UTC
	[OCBUJ] 16:37:18 INFO: My ID: OCBUJGQ-[sensitive data]
	[OCBUJ] 16:37:18 INFO: Starting web GUI on http://127.0.0.1:8080/
	[OCBUJ] 16:37:18 INFO: Starting UPnP discovery...
	[OCBUJ] 16:37:21 INFO: dial tcp: missing port in address 192.168.0.1
	[OCBUJ] 16:37:24 INFO: UPnP discovery complete (found 0 devices).
	[OCBUJ] 16:37:24 INFO: Starting local discovery announcements
	[OCBUJ] 16:37:24 INFO: Starting global discovery announcements
	[OCBUJ] 16:37:24 OK: Ready to synchronize [sensitive data] (read-write)
	[OCBUJ] 16:37:24 INFO: Device OCBUJGQ-[sensitive data] is "[sensitive data]" at [dynamic]
	[OCBUJ] 16:37:24 INFO: Device ZZMHPOP-[sensitive data] is "[sensitive data]" at [dynamic]
	[OCBUJ] 16:37:24 INFO: Device 4B7NWP2-[sensitive data] is "[sensitive data]" at [dynamic]
	[OCBUJ] 16:37:24 INFO: Starting usage reporting
	[OCBUJ] 16:37:24 INFO: Completed initial scan (rw) of folder [sensitive data]
	[OCBUJ] 16:38:00 INFO: Established secure connection to 4B7NWP2-[sensitive data] at 192.168.0.187:43360-109.[sensitive data]:13911
	[OCBUJ] 16:38:00 INFO: Device 4B7NWP2-[sensitive data] client is "syncthing v0.10.30"
	[OCBUJ] 16:38:00 INFO: Device 4B7NWP2-[sensitive data] name is "[sensitive data]"
	[OCBUJ] 16:38:02 INFO: Puller (folder "[sensitive data]", file "Unfa/unfa-01-23.wav"): pull: no available source device
	[OCBUJ] 16:38:03 INFO: Puller (folder "[sensitive data]", file "Unfa/unfa-01-23.wav"): pull: no available source device
	[OCBUJ] 16:38:04 INFO: Puller (folder "[sensitive data]", file "Unfa/unfa-01-23.wav"): pull: no available source device
	[OCBUJ] 16:38:05 INFO: Puller (folder "[sensitive data]", file "Unfa/unfa-01-23.wav"): pull: no available source device
	[OCBUJ] 16:38:06 INFO: Puller (folder "[sensitive data]", file "Unfa/unfa-01-23.wav"): pull: no available source device
	[OCBUJ] 16:38:07 INFO: Puller (folder "[sensitive data]", file "Unfa/unfa-01-23.wav"): pull: no available source device
	[OCBUJ] 16:38:08 INFO: Puller (folder "[sensitive data]", file "Unfa/unfa-01-23.wav"): pull: no available source device
	[OCBUJ] 16:38:09 INFO: Puller (folder "[sensitive data]", file "Unfa/unfa-01-23.wav"): pull: no available source device
	[OCBUJ] 16:38:11 INFO: Puller (folder "[sensitive data]", file "Unfa/unfa-01-23.wav"): pull: no available source device
	[OCBUJ] 16:38:12 INFO: Puller (folder "[sensitive data]", file "Unfa/unfa-01-23.wav"): pull: no available source device
	[OCBUJ] 16:38:14 INFO: Puller (folder "[sensitive data]", file "Unfa/unfa-01-23.wav"): pull: no available source device
	[OCBUJ] 16:38:14 WARNING: Folder "[sensitive data]" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.
	[OCBUJ] 16:39:15 INFO: Puller (folder "[sensitive data]", file "Unfa/unfa-01-23.wav"): pull: no available source device
	[OCBUJ] 16:39:16 INFO: Puller (folder "[sensitive data]", file "Unfa/unfa-01-23.wav"): pull: no available source device
	[OCBUJ] 16:39:17 INFO: Puller (folder "[sensitive data]", file "Unfa/unfa-01-23.wav"): pull: no available source device
	[OCBUJ] 16:39:18 INFO: Puller (folder "[sensitive data]", file "Unfa/unfa-01-23.wav"): pull: no available source device
	[OCBUJ] 16:39:19 INFO: Puller (folder "[sensitive data]", file "Unfa/unfa-01-23.wav"): pull: no available source device
	[OCBUJ] 16:39:20 INFO: Puller (folder "[sensitive data]", file "Unfa/unfa-01-23.wav"): pull: no available source device
	[OCBUJ] 16:39:21 INFO: Puller (folder "[sensitive data]", file "Unfa/unfa-01-23.wav"): pull: no available source device
	[OCBUJ] 16:39:22 INFO: Puller (folder "[sensitive data]", file "Unfa/unfa-01-23.wav"): pull: no available source device
	[OCBUJ] 16:39:23 INFO: Puller (folder "[sensitive data]", file "Unfa/unfa-01-23.wav"): pull: no available source device
	[OCBUJ] 16:39:24 INFO: Puller (folder "[sensitive data]", file "Unfa/unfa-01-23.wav"): pull: no available source device
	[OCBUJ] 16:39:25 INFO: Puller (folder "[sensitive data]", file "Unfa/unfa-01-23.wav"): pull: no available source device
	[OCBUJ] 16:39:26 WARNING: Folder "[sensitive data]" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.

**Comment by AudriusButkevicius** [comment]
Can you get the json values for:
`/rest/db/file?folder=<folder>&file=<full relative path to one of the out of sync files>`
from both sides?

**Comment by unfa** [comment]
What's that and how do I do that?

**Comment by AudriusButkevicius** [comment]
Well that that probably just means that the file was changing while syncthing was trying to get it in sync.

**Comment by unfa** [comment]
Hmm but that lasted for an hour, while I wasn't doing anything with the file.

**Comment by AudriusButkevicius** [comment]
How fast that get's picked up repends on the rescan interval.

**Comment by unfa** [comment]
It's set to 5 seconds.

2015-04-11 20:08 GMT+02:00 Audrius Butkevicius <notifications@github.com>:

> How fast that get's picked up repends on the rescan interval.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncthing/syncthing/issues/1628#issuecomment-91893924>
> .
>



-- 
Tobiasz *unfa*

-----BEGIN GEEK CODE BLOCK-----
Version: 3.1
GIT/MU/P d->-- s+:-(--)> a? C++(+++)>$ ULC+(++)>$ !P? L+++>++++$ E? W++>$
!N-? !o--? K-? !w-- O? !M-- V? PS++ PE++ !Y+ !PGP+? !t(+) 5? !X !R+ tv
b+>+++ DI>+ D+ G e h-->- !r y--()
------END GEEK CODE BLOCK------

**Comment by calmh** [comment]
If the file changed without the modification time or size changing, we would not pick up the new contents and the error would persist...
