### ISSUE TITLE
Is domain announce-v6.syncthing.net neccessary?

### ISSUE THREAD

**Issue by Jonny007-MKD** [syncthing/syncthing#1629]
Hello together,

I really appreciate that you are offering an IPv6 server (although I cannot use it yet).
Why do you differentiate the domain names for IPv4 and IPv6? Isn't this what A and AAAA is for?

**Comment by AudriusButkevicius** [comment]
To have it exclusively resolve to v6 rather than v4 or v6 depending wether or not you support that, as far as I understand.

**Comment by calmh** [comment]
If `announce` had A and AAAA, the client would chose one to announce itself it. That would leave the clients using the other protocol without information. Using two records, we get separate announcements over v4 and v6.
