### ISSUE TITLE
No event exposed for remote device start/stop syncing

### ISSUE THREAD

**Issue by imanel** [syncthing/syncthing#1630]
When accessing `/rest/events` endpoint there are several events showing when file is downloaded (`RemoteIndexUpdated` is called, state changes from `idle` to `syncing`, then `ItemStarted`, `DownloadProgress` and `ItemFinished` and `LocalIndexUpdated` are called in order, followed by state change back to `idle`).

However no such behavior can be spotted when files are changed on my side and other instances need to be synced. All I can see is several `LocalIndexUpdated ` events with appropriate files and some time later `RemoteIndexUpdated` for other servers with no information about which files were synced. I'm well aware that this is dictated by performance reasons, but what I'm really lacking is some event that will tell me that other server started (and possibly ended) sync (similar to changing state from `idle` to `syncing` when my side is downloading).

Here's why I need it: I'm trying to build status bar app that will work similar to Dropbox icon - when you are either downloading or uploading data it changes to show you information about it. It's obviously easy for when we're downloading data (I'm monitoring state and change icon when `syncing` is on). However I can see no way of obtaining reverse information - in theory I can monitor `LocalIndexUpdated` and `RemoteIndexUpdated` and react to them by checking `/rest/completion` for each machine, but this look like huge performance killer (not to mention it's not very reliable).

So here's the question: are there any plans to add such event? If no then what is preventing it? If yes then is there some way I could help? (I could work on pull request if you could provide me some vague directions where should I start)

**Comment by AudriusButkevicius** [comment]
There is no concept of remote state apart from what we know the global index is, and what we know their current index is (which is what completion uses to compute the percentage).

Other devices just make requests to some offset within one of the files that they need, and we have no clue how that translates to their progress, all we know is that they are downloading something.
Heck, we might not even know that, just because they might be firing off all requests to some other node and not to us.

**Comment by imanel** [comment]
If they fire request to other node then it's not our problem - what I'm missing is event that fires when we have newer version than some other node (it's `LocalIndexUpdated`, but it doesn't contain some kind of current index number to compare with `RemoteIndexUpdated` - that would solve this issue).

**Comment by AudriusButkevicius** [comment]
Well LocalIndexUpdated on 0.11 is batched and returns a list of files which are have been updated (hence newer).

**Comment by calmh** [comment]
Just a count. But we fire a `FolderCompletion` events as well, for each folder and device. That tells you if the device in question is up to date for the given folder (completion=100) or not. Is that what you're looking for?

**Comment by imanel** [comment]
`FolderCompletion` event is not described on [wiki](https://github.com/syncthing/syncthing/wiki/Event-Interface), so I'm assuming it's new in 0.11? Is there written description somewhere about changes in events? Unfortunately I will be unable to test this branch during next couple days :(

**Comment by calmh** [comment]
Yes. Not yet.

**Comment by imanel** [comment]
I can see in code that there are [not too many](https://github.com/syncthing/syncthing/search?utf8=✓&q=FolderCompletion) references in code to `FolderCompletion`. From what I understand from [this code](https://github.com/syncthing/syncthing/blob/ba4a6fc0c54cd69dc7eadcae633daa8e0880ba8f/gui/scripts/syncthing/core/controllers/syncthingController.js#L257-L274) it will be triggered in similar way to `DownloadProgress` - once in a while it will push event with percentage (with the difference that here it will be per-directory instead of per-file). If it will trigger on both 0% and 100% then that's exactly what I'm looking for:

For pulling data I'm able to watch `StateChanged` between `to='syncing'` and `from='syncing'`.
For pushing data (or remote exchange) I'm able to watch `FolderCompletion` between `completion=0` and `completion=100`.

**Comment by calmh** [comment]
Mostly yes. If a new or changed file is detected locally, `FolderCompletion` will be fired for the connected devices that are missing the file, with `comp=98.423` or something (i.e. less than 100), and then with higher completion ratio as that device announces files it has pulled, until it reaches 100.
