### ISSUE TITLE
Use copy instead of rename for version folder on other file systems

### ISSUE THREAD

**Issue by hashworks** [syncthing/syncthing#1634]
I've set the version folder to a different device for staged file versioning, now I'm getting the following errors:

```
Puller: final: rename /home/hashworks/filename /mnt/WDGREEN2TB/Backups/Cloud/filename: invalid cross-device link
```

Syncthing should use soft links here.

**Comment by AudriusButkevicius** [comment]
Symbolic link is just a reference to an existing file, it does not make a copy of it, hence if you were to delete the original file the link pointed to, the link would be invalid, and versioning would be useless (as it would be a bunch of invalid symlinks).

I guess what you are referring to is copying the file (rather than renaming it).

**Comment by hashworks** [comment]
You're right, I've adjusted the title.

**Comment by AudriusButkevicius** [comment]
We should try renaming, but resort to copying I guess.

**Comment by lkwg82** [comment]
is this still relevant? switching from copy to rename seems a no brainer or on the other side a seldom edge case.

**Comment by AudriusButkevicius** [comment]
It is still relevant when we cross device boundaries.

**Comment by lkwg82** [comment]
so the other question is thisdifficult to change from copy to rename?

**Comment by AudriusButkevicius** [comment]
No, someone just needs to do it.

**Comment by lkwg82** [comment]
Are we talking about?

```go
osutil.Rename(filePath, dst)
```
https://github.com/syncthing/syncthing/blob/4eb23a38b1ceb2c522cb589db2b6e987fd9e915c/lib/versioner/simple.go#L82

**Comment by AudriusButkevicius** [comment]
Potentially have a osutil.Move which does a rename or a copy if the rename fails.

**Comment by calmh** [comment]
I'm not super keen on doing that in the general case. This would need to be a special thing for versioning, if we're going to do it. There should be no case where we need to do a copy+delete to rename a temp file to it's real name, and if we would do that we would need to do it with hashing and crap as well

**Comment by lkwg82** [comment]
mhm, so you in general say that some logic in `osutil.go` need a review to maybe cleaned up? Because I see some lines in here, which do exactly this.

**Comment by AudriusButkevicius** [comment]
Hence why I proposed osutil.Move which is used explicitly for versioning.

**Comment by endolith** [comment]
Ohhh, am I getting this error because I'm syncing the files to a https://github.com/trapexit/mergerfs drivepool made up of multiple drives?

**Comment by calmh** [comment]
If your folder is on some pretend FS that doesn’t support rename and stuff, yeah, expect weirdness.
