### ISSUE TITLE
Start Syncthing minimized to tray on Windows

### ISSUE THREAD

**Issue by petrovnn** [syncthing/syncthing#1635]
Tried to add a command in the shortcut:

```
-tray
--tray
-minimized
```

does not work. Flashing Syncthing window and immediately closed. The program does not start.

In the shortcut properties I set «Run: Minimized», it turns to the Taskbar window but does not move the window to the tray.

Maybe I need to write a .bat file that minimizes startup Syncthing to tray? If it is possible, where to start?

![f0c18ee6ec](https://cloud.githubusercontent.com/assets/1567284/7115739/db77d49e-e1f3-11e4-8f41-b20d3c835fd4.png)

**Comment by AudriusButkevicius** [comment]
If you want to hide the console, use `-no-console`, as described in `-help`.

**Comment by petrovnn** [comment]
Thank you, it works!

To this day, almost did not use the console, and did not know about «-help» command
