### ISSUE TITLE
SyncThing and files.

### ISSUE THREAD

**Issue by audiogamer22** [syncthing/syncthing#1641]
Hi.

I was shown a link on IRC chat, and was hoping this is the rite place to post this kind of thing.

It would be nice i think, if we could see what files and folders are being downloaded/uploaded to and from our computers.

At the moment I am unable to see the files being downloaded and think that having this feature would be nice.
 
I'm blind and use NVDA, (It's a screen reader, a piece of software that talks to me and tells me what is on the screen.) If you want to see more about it, go to www.nvaccess.org

I'm very impressed with this program and how easy it is for those of us who can't see to use.

I know that there are other blind Syncthing users and I'm sure we'll find things that don't exactly work, although at the moment we haven't and that's great! But if we all work on these together we'll have an amazing program and an amazing community of people.

**Comment by AudriusButkevicius** [comment]
So there already exists a list of files which syncthing is downloading to your machine.
We technically know that some other machine is missing some files to be in sync, but we don't expose that anywhere. Is that what you are looking for?

**Comment by audiogamer22** [comment]
Hi.

No, I've already found what I was looking for.

I wanted a way to see what file was being downloaded, but instead of 
that, I found the last file downloaded part of the table and can read it 
fine.

Thanks for the reply.

**Comment by AudriusButkevicius** [comment]
There ia also a list of files which are downloaded which are shown in a popup if you click on 'out of sync' items.
