### ISSUE TITLE
'out of memory' on Raspberry Pi during index

### ISSUE THREAD

**Issue by CzarDestructo** [syncthing/syncthing#1642]
Ever since the latest update to BTsync I've been trying to get Syncthing working on my raspberry pi's off and on. To date I've been unable to get it working, it keeps crashing with an 'out of memory' error while attempting to index the folders. I moved the home directory to an external hard drive so I don't shred the SD card and there is about 1.5TB of data that I'm trying to index. What I find interesting is that graphing the memory usage shows plenty of memory followed by a quick dip in available memory all at once, then syncthing crashes, restarts, then the memory ticks right back up. I'm a bit perplexed and was hoping for some direction.

Raspi B+ running Raspbian, syncthing v0.10.30

This picture shows the quick dip zoomed in and the bottom of the picture shows the several instances of the crashes. Very re-producible.
![image](https://cloud.githubusercontent.com/assets/11969787/7171833/cc521358-e3ab-11e4-8714-8879469e2777.png)

```
fatal error: runtime: out of memory

runtime stack:
runtime.SysMap(0x26840000, 0x29c0000, 0x68801, 0x7dacf0)
	/usr/local/go/src/runtime/mem_linux.c:159 +0x134
runtime.MHeap_SysAlloc(0x7ddac8, 0x29c0000, 0x1)
	/usr/local/go/src/runtime/malloc.c:284 +0x140
runtime.MHeap_Alloc(0x7ddac8, 0x14de, 0x0, 0xb6e20101, 0x1384ca80)
	/usr/local/go/src/runtime/mheap.c:240 +0x50

goroutine 83 [running]:`
runtime.switchtoM()
	/usr/local/go/src/runtime/asm_arm.s:193 +0x4 fp=0x1156553c sp=0x11565538
runtime.mallocgc(0x29bb544, 0x421fd0, 0x1, 0x29bb544)
	/usr/local/go/src/runtime/malloc.go:194 +0x9f8 fp=0x11565594 sp=0x1156553c
runtime.newarray(0x421fd0, 0x29bb544, 0x292ce2b)
	/usr/local/go/src/runtime/malloc.go:365 +0xec fp=0x115655b0 sp=0x11565594
runtime.makeslice(0x419548, 0x292cd64, 0x0, 0x29bb544, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/slice.go:32 +0x1fc fp=0x115655d4 sp=0x115655b0
github.com/syndtr/goleveldb/leveldb.(*Batch).grow(0x116cf140, 0xc7)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/batch.go:64 +0x1bc fp=0x1156561c sp=0x115655d4
github.com/syndtr/goleveldb/leveldb.(*Batch).appendRec(0x116cf140, 0x1, 0x14882300, 0xb8, 0xb8, 0x115656c4, 0x4, 0x4)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/batch.go:75 +0x64 fp=0x11565668 sp=0x1156561c
github.com/syndtr/goleveldb/leveldb.(*Batch).Put(0x116cf140, 0x14882300, 0xb8, 0xb8, 0x115656c4, 0x4, 0x4)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/batch.go:97 +0x5c fp=0x1156568c sp=0x11565668
github.com/syncthing/syncthing/internal/db.(*BlockMap).Update(0x11a9a780, 0x10a52a00, 0x64, 0x64, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/internal/db/blockmap.go:79 +0x344 fp=0x11565860 sp=0x1156568c
github.com/syncthing/syncthing/internal/db.(*FileSet).Update(0x10bb0380, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0x10ae4000, ...)
	/go/src/github.com/syncthing/syncthing/internal/db/set.go:127 +0x754 fp=0x11565a30 sp=0x11565860
github.com/syncthing/syncthing/internal/model.(*Model).ScanFolderSub(0x10a441b0, 0x10aae2a0, 0xc, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/internal/model/model.go:1147 +0xef0 fp=0x11565d44 sp=0x11565a30
github.com/syncthing/syncthing/internal/model.(*Model).ScanFolder(0x10a441b0, 0x10aae2a0, 0xc, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/internal/model/model.go:1093 +0x50 fp=0x11565d64 sp=0x11565d44
github.com/syncthing/syncthing/internal/model.(*rwFolder).Serve(0x11e94000)
	/go/src/github.com/syncthing/syncthing/internal/model/rwfolder.go:123 +0x1368 fp=0x11565fe4 sp=0x11565d64
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:1322 +0x4 fp=0x11565fe4 sp=0x11565fe4
created by github.com/syncthing/syncthing/internal/model.(*Model).StartFolderRW
	/go/src/github.com/syncthing/syncthing/internal/model/model.go:162 +0x528

goroutine 1 [chan receive, 377 minutes]:
main.syncthingMain()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:479 +0x22e8
main.main()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:251 +0x1bc0

goroutine 5 [syscall, 393 minutes]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1c
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x40

goroutine 7 [select]:
github.com/syncthing/syncthing/internal/events.(*Subscription).Poll(0x10a0b060, 0xf8475800, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:173 +0x340
github.com/syncthing/syncthing/internal/events.(*BufferedSubscription).pollingLoop(0x10a48450)
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:209 +0x40
created by github.com/syncthing/syncthing/internal/events.NewBufferedSubscription
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:203 +0x1f4

goroutine 8 [chan receive]:
main.trackCPUUsage()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0x120
created by main.init·3 
```

**Comment by calmh** [comment]
Go processes on 32 bit architectures are limited to ~500-700 MB (I can't immediately find the exact truth here) of allocated memory, which may be less than the system actually has available. Syncthing may temporarily use quite a lot of memory when indexing, especially for large files. If you can start syncthing as `STTRACE=scanner syncthing` it will print a fair amount of debug information about what happens during scanning up to the point it crashes. This may help to narrow down the reason; if it is as I expect (a large file), perhaps that can be optimized. If it is not, perhaps it points to other areas...

**Comment by CzarDestructo** [comment]
I think you're spot on with the large file issue because I noticed it always failed to index beyond a certain amount of gigs/file count in a share which would imply that it keeps crashing on a certain file. I restarted it this morning with the flag you recommended, I'll report back with my findings. Thank you for responding so quickly! :)

**Comment by calmh** [comment]
Cool. Whatever the result of that, give this one a spin afterwards and see if it makes a difference:

http://build.syncthing.net/job/syncthing/1001/artifact/

If the crash is due to a single huge file, it may not make much of a difference. If it's due to several semi-large ones, it may.

**Comment by CzarDestructo** [comment]
I'm confused. The available memory looks fine leading up to a 270meg and 134meg file which are the last two in a folder. As soon as it starts hashing the 134meg file the available memory starts to drop. It then changes folder to one containing 13 video files, 8 are over 3.5gigs each but it never gets to hashing a file. The next line after the folder switch is the 'out of memory' error and it occurs 40 seconds later. Would just the preliminary scanning of a folder containing large files crash it or will hashing the actual files crash it?

I removed the 134meg file from the hard drive to see what it does once it reaches that folder again, then I'll try that new executable to see if it helps.

```
[C2BXP] 2015/04/17 12:50:48.517977 walk.go:149: DEBUG: to hash: **270 meg file**
[C2BXP] 2015/04/17 12:51:46.542624 walk.go:149: DEBUG: rescan:  **270 meg file**
[C2BXP] 2015/04/17 12:51:46.548874 walk.go:149: DEBUG: to hash: **134 meg file**
[C2BXP] 2015/04/17 12:52:47.741670 walk.go:149: DEBUG: dir: **dir with 29.6gigs of videos**
fatal error: runtime: out of memory
[monitor] 2015/04/17 12:53:31.464463 monitor.go:173: WARNING: Panic detected, writing to "/mnt/bleh/panic-20150417-125331.log"
```
![image](https://cloud.githubusercontent.com/assets/11969787/7213289/e2f9f93a-e546-11e4-92aa-0e5f6bc89c0d.png)

**Comment by CzarDestructo** [comment]
That's interesting, removing that file didn't help but that new executable you pointed me to seems to be working perfectly. I'll let this run for a few days to see if it hashes everything. Were you expecting that to work?

**Comment by Zillode** [comment]
The odds were high because that build flushes batches that become too big in filesize (and not only in number of files). This has already been [merged](https://github.com/syncthing/syncthing/commit/a624c302ab28532175dd43f8449e95a02c9e81ac) into master which means the next version should fix this for good.
Feel free to reopen if the problem returns.
