### ISSUE TITLE
Command line client for syncthing 0.11+

### ISSUE THREAD

**Issue by celogeek** [syncthing/syncthing#1643]
Hi,

I start to write a command line client for syncthing 0.11+. The main reason is that the web interface, in case of huge directory to sync (100GB), is very cpu intensive, so I need to be able to only fetch what I want.

https://github.com/celogeek/Syncthing-Cli

The command line is read only now, but I will add easy to add directory method in the config.

For now this is the possibilities :
```
syncthing-cli [-h host] [-p port] [-s] command options

  * -h: set the host, default 127.0.0.1
  * -p: set the port, default 8888
  * -s: ssl protocol

  * list: list all directory id and path
  	-p: list path only
	-f: list folder only
	-r: filter read only
  * status: get status
        * [ directory ] [ directory ] ...
        * -a: only active one
  * live: display live events
  * override: force override all read only folders
  * download: show downloads progression
  * version: get current client version
  * checkupdate: check if a new version is available
````

If any one can try and give me feedback, thanks.

**Comment by AudriusButkevicius** [comment]
There already exists a semi-working one.
I haven't maintained it for ages, hence probably has a bunch of settings/options missing:
https://github.com/syncthing/syncthing-cli

**Comment by celogeek** [comment]
Yeah, I cannot propose any patch yet for this. First I need to learn the language. I more efficient on perl.
