### ISSUE TITLE
Document exit codes on manpage

### ISSUE THREAD

**Issue by Profpatsch** [syncthing/syncthing#1650]
It would be nice to know which exit codes there are, as most other manpages document it.

e.g. I got a 143 [here](https://github.com/syncthing/syncthing-android/issues/361).

**Comment by AudriusButkevicius** [comment]
They are "documented" https://github.com/syncthing/syncthing/blob/master/cmd/syncthing/main.go#L57

143 is an exit code emitted by the signal handler (SIGTERM in this case AFAIK) and is not a standard exit code of syncthing.

**Comment by Profpatsch** [comment]
Hm, it looks like this is a Java thing: http://stackoverflow.com/questions/4192364/always-app-java-end-with-exit-143-ubuntu

**Comment by AudriusButkevicius** [comment]
Nope...
http://tldp.org/LDP/abs/html/exitcodes.html
128+15 (SIGTERM) = 143

**Comment by Profpatsch** [comment]
Ah, nice to know.
