### ISSUE TITLE
"Restart needed" dialog confusing.

### ISSUE THREAD

**Issue by jvasile** [syncthing/syncthing#1651]
I added a device and got a dialog that said a restart was needed and I could select from "restart later" and "ok". This dialog is confusing in that I initially wasn't sure whether it meant a restart of the whole phone or just the app. 

It also wasn't clear what the "OK" button did. I pressed it to acknowledge the message, and the app restarted. That's fine, but perhaps the button could be labeled "Restart now" to be more explicit about what it does.

Thanks!

**Comment by Cronus89** [comment]
I agree with this, had the same thing. While I figured it out quickly.  I think renaming it to "Restart Now" is better.

**Comment by AudriusButkevicius** [comment]
I guess this relates to https://github.com/syncthing/syncthing-android and not to syncthing directly?

**Comment by AudriusButkevicius** [comment]
Yeah, we don't have an Ok dialog.
Please reopen in the android repo.
