### ISSUE TITLE
Expose discovered device IDs in Web interface

### ISSUE THREAD

**Issue by techtonik** [syncthing/syncthing#1653]
I want to connect two computers in LAN that don't have any other channel of communication. If I enable STTRACE=discover, I can see the device id in the log. But it would be more convenient to show available (and synced) devices in web interface.

```
YYYYY] 2015/04/18 10:03:25.001338 discover.go:319: DEBUG: discover: Received local announcement from 192.168.1.3:21025 for RRR1RRR-...
YYYYY] 2015/04/18 10:03:25.001338 discover.go:369: DEBUG: discover: Caching RRRRRR-... addresses: [{192.168.1.3:22000 2015-04-1 10:03:25.0013386 +0300 FET}]
```

**Comment by AudriusButkevicius** [comment]
I don't understand the use case here.
Cannot you just copy the device ID from your other device and be done with it?

Synced devices are shown, and you should know which device you want to connect to.
We shouldn't burden the UI with whats available on the network, as for a university campus, that potentially could be a lot.

**Comment by techtonik** [comment]
How to you propose to copy the device ID from computers that are not connected? Writing to paper?

**Comment by AudriusButkevicius** [comment]
Email yourself the ID of the other device?

**Comment by techtonik** [comment]
These are not connected to internet.

**Comment by AudriusButkevicius** [comment]
`nc -l 25025` on one side.
`echo [DEVICE ID]>/dev/tcp/[ipaddress]/25025` on the other side.

**Comment by jkufner** [comment]
You don't need Internet to use e-mail ;)

Alternatively you can use QR codes. Klipper (KDE clipboard manager),
Barcode Scanner (Android app) and other tools can generate them for any
text and then you can scan them on the second device.

Question is, how to synchronize devices that are not connected?

**Comment by jpjp** [comment]
@techtonik I also think this could be better. When I add a device it will show as a dropdown in the device id field. Does it for you?

**Comment by AudriusButkevicius** [comment]
That's actually true as well, and solves this issue as far as I am concerned.
@jpjp provide a screenshot to explain what you mean, I am sadly the only one in the network with syncthing.

**Comment by techtonik** [comment]
@jpjp no, I don't see any dropdowns with device IDs. A screenshot will be very useful.

**Comment by alex2108** [comment]
here you have a screenshot in chromium: (German version of the "Add Device" menu)
![screenshot](https://cloud.githubusercontent.com/assets/6099511/7428068/94fe6a7e-efe9-11e4-94ef-5b7726a50e37.png)
In firefox it's less obvious, you have to click in the field and press arrow down or double click in the field to get the list. We should maybe make that a bit more obvious that this exists.

**Comment by techtonik** [comment]
Now I see.. Probably a counter of connected/unknown nodes will be nice. Maybe directly on `Add device` button..

**Comment by calmh** [comment]
The GUI here could use some improvement, especially as not everything supports the datalist widget. But that goes for many parts of the GUI, so I'll close this specific issue as it is in fact exposed, albeit crappily.
