### ISSUE TITLE
[0.11] UPnP not working between a Xubuntu 14.10 laptop and a D-Link DSL-2730E router

### ISSUE THREAD

**Issue by marcelpaulo** [syncthing/syncthing#1657]
Following discussion [2436](https://forum.syncthing.net/t/tips-on-how-to-make-upnp-work/2436) on the forum.

syncthing multicasts SSDP M-SEARCH requests, the router multicasts back SSDP NOTIFY replies, but syncthing appears not to recognize them. The router takes around 5—10s to reply, so branch *0.10* timed out. Thanks to @AudriusButkevicius, *0.11* exposes `upnpTimeoutSeconds` in *config.xml*, which I configured (to cater for my lazy router):
```
<upnpTimeoutSeconds>30</upnpTimeoutSeconds>
```

Running version *v0.11.0-rc0*.

My tests:

1. Enabled UPnP on the router and syncthing. Here's my [config.xml](http://paste.ubuntu.com/10845201/)
2. Started a wireshark capture with filter `udp port 1900`
3. Started syncthing: `STTRACE=upnp syncthing &> >(tee syncthing.log)`
4. Waited for UPnP discovery to fail, stopped wireshark capture and syncthing

The logs: [pcap capture](https://docs.google.com/file/d/0B6eQjhXV-AqueWdBTThCMW5lc0U/edit?usp=drivesdk), [syncthing log](http://paste.ubuntu.com/10845221/)

I can see that syncthing multicasts 2 SSDP M-SEARCH requests, and 7s later the router multicasts 60+ SSDP NOTIFY replies back, but either the replies are wrong or syncthing can't decode good ones. Don't know enough SSDP to tell the difference.

I hope I haven't forgotten anything. If you need more debugging to nail this, I'm eager to help.

***PS***: Wrote to D-Link about this problem. First level support was clueless, they asked me if UPnP was configured on Windows ! I sent back more details, the capture and log, I'm waiting for a better informed feedback from them.

**Comment by AudriusButkevicius** [comment]
Comparing to my router, I think the response is incorrect.
My router responds to me directly saying where the service is available, yours starts advertising which services it supports to the whole network...

**Comment by AudriusButkevicius** [comment]
Are you able to compile sything yourself?
I have an idea what it could be, but not sure.

**Comment by marcelpaulo** [comment]
> My router responds to me directly saying where the service is available, yours starts advertising which services it supports to the whole network

SSDP mandates strictly unicast replies ?

I'm getting sick and tired of my router ! UPnP is not the only flaky thing about it. It's an ADSL2+ modem + router, leased by my ISP.

> Are you able to compile sything yourself?

I'm fairly green about building stuff from source, but I'll sure try it. I'll shout for help if I get stuck.

**Comment by AudriusButkevicius** [comment]
http://en.wikipedia.org/wiki/Simple_Service_Discovery_Protocol
"Responses to such search requests are sent via unicast addressing to the originating address and port number of the multicast request."

The thing which might potentially help is changing all the headers to be full caps at:
https://github.com/syncthing/syncthing/blob/master/internal/upnp/upnp.go#L163

**Comment by AudriusButkevicius** [comment]
It should respond saying `X is at http://...`, rather than `I have X`

**Comment by marcelpaulo** [comment]
> The thing which might potentially help is changing all the headers to be full caps

But if the router is replying, doesn't it mean that it's understanding the requests ?

> It should respond saying X is at http://..., rather than I have X

Please correct me if I'm speaking nonsense here: isn't it the router who responds ?

Tallying the code with [syncthing.log](http://paste.ubuntu.com/10845221/), `parseResponse` doesn't spit any errors on the router replies, so it seems to be understanding them, but somewhere somehow it doesn't turn them into valid device descriptions.

**Comment by AudriusButkevicius** [comment]
So syncthing is not even getting any response, as it's expecting to get a response on the same socket it sent the request from.
The router sends a response to the multicast group which syncthing is not even part of.
And the reply it sends back is not the reply we are even looking for. I says `I have X` rather than `X is at http://...`

Example of my UPnP discovery:
https://onedrive.live.com/redir?resid=205123AD90CCC043!54369&authkey=!AE5VafQlvoTm0CI&ithint=file%2cpcap
Look at what my router responds with, and where it responds to, versus yours.

Yes, I do think we should close this, as this is todo with your router and there's not a lot we can do here.

**Comment by marcelpaulo** [comment]
> Look at what my router responds with, and where it responds to, versus yours

Yeah, I see, you get a single HTTP unicast response.

But ... it just occurred to me: when I tested for forum issue [2436](https://forum.syncthing.net/t/tips-on-how-to-make-upnp-work/2436/6?u=marcelpaulo), I have just reviewed the pcap file, my router was sending the HTTP unicast responses, but the problem then was timeout, which we can work around now with `upnpTimeoutSeconds`. Let me double-check everything I did then, see if I can reproduce it.

Either way, I can wrap this up: whether it works by reproducing the previous conditions and increasing `upnpTimeoutSeconds`, or writing it off as faulty UPnP implementation by my router.

These routers are leased by Brazilian ISP provider **GVT** when you sign for broadband. I bet other Brazilian syncthing users will choke on the same problem. So it will be useful to exhaust all scenarios and leave a well documented trail behind.

Just give me a moment, and I'll come back with final results.

**Comment by marcelpaulo** [comment]
No joy, can't reproduce it, but if I could, it doesn't look like it would work because the HTTP unicast responses from that [pcap file](https://docs.google.com/file/d/0B6eQjhXV-AquQ05Cejg4M1I2b0k/edit?usp=drivesdk) did not refer to:
```
 urn:schemas-upnp-org:device:InternetGatewayDevice:1
```
but rather to:
```
uuid:63041253-1019-2006-1228-c0a0bb0fc2ce::upnp:rootdevice
uuid:f5c1d177-62e5-45d1-a6e7-c0a0bb0fc2ce::upnp:rootdevice
```
I throw in the towel, let's wrap this up. Thanks, @AudriusButkevicius !
