### ISSUE TITLE
Sycthing 0.11 returns 500 when fetching `/rest/db/ignores`

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#1659]
See https://github.com/canton7/SyncTrayzor/issues/55

Syncthing returns "Folder XXX does not exist" along with a 500 status code when fetching `/rest/db/ignores` for some folders. Other folders are fine. 300ms earlier, Syncthing returned those folders as part of its response to `/rest/config`.

**Comment by calmh** [comment]
I haven't looked at the code yet, but if this is during startup, there's an interval where the folders are in the config but haven't been "started" yet, and hence don't fully exist. I'm not sure this is a real bug, if that's the case. If we incorrect return "does not exist" after the `StartupComplete` event though, that's something else.

**Comment by canton7** [comment]
Is there any way of determining whether StartupComplete has occurred, other than catching it on the events interface? Without fetching all events ever (which has its own problems) I can't tell whether I've missed it, or just haven't seen it yet.

**Comment by calmh** [comment]
When initially talking to syncthing, you do fetch all events since forever. Either it's in there,  or you missed because too long has gone by, as it's one of the first events generated and we buffer ... *checks* ... 1000 events. So I'd try using some logic like;

 - get /rest/events.
 - Does the event stream start at the beginning (we see an id=1 event)? If so, we need the "StartupCompleted". Either it's already in the event list you got, or it'll be here soon.
 - If we're missing events at the beginning (first id > 1), assume you missed the StartupCompleted and it's all good.

**Comment by canton7** [comment]
So on connection I need to fetch 1000 events (all of which I'll have to ignore, except the single `StartupComplete` event)? I guess that could be optimised to:

- Get /rest/events with limit=1
- Is the event ID > 1000? If so, startup is complete
- Otherwise, fetch everything and ignore anything that isn't StartupComplete
- Start polling normally.

Thanks

**Comment by calmh** [comment]
Well, if you want to catch an even you need to check for it. :) That said, checking 1000 events once is probably about a millisecond or so worth of work, with deserialization and so on... I wouldn't worry too much about it.

I guess there are conflicting goals here. On the one hand we want the API up as soon as possible, so we do it before a bunch of other stuff. On the other hand, that other stuff is actually necessary so some things won't work until it's done...

**Comment by canton7** [comment]
Presumably it's possible to trip the GUI up here as well? Start Syncthing, then try and view the ignores are quickly as possible. I can't replicate this myself unfortunately (too few folders, or too small, presumably), but I'd imagine it's possible to catch it out.

I guess in my mind there are a number of distinct states that Syncthing can be in, including `Starting` and `Running`. In `Starting` some API resource are available but not others, while in `Running` everything's available. Currently there's an event when we transition between them, but no resource which exposes the current state. I guess in an ideal world I'd like to see:

 - A resource from which the current state can be fetched
 - Documentation to say which API resources are available in which state
 - Resources which aren't available in the `Starting` state will return a 503 (or something else sensible) if they're requested when Syncthing is `Starting`

That way we can bring the API up in stages, but at each stage the API will always behave as expected.

... That said, the current system works and there are doubtless far more important things to be getting on with (plus I'd still have to take an approach as discussed above for 0.10 clients), so I'm not asking you to actually implement anything new!

**Comment by calmh** [comment]
There seems to be about a three second window between the API coming up and folders being added, that being the UPnP timeout. With UPnP disabled (or an actual UPnP router present), it's probably in the milliseconds. You'll have to have a twitchy mousing hand to get to the ignore list in time. ;)

Thing is, 500 is a perfectly cromulent response here (standard says something about "currently unable to fulfill the request" or some such IIRC); it's just that it doesn't differentiate between "not done yet" and "something is actually wrong"...

What you suggest isn't unreasonable though.

**Comment by canton7** [comment]
Are all of the folders really available at once? In the logs I was given, I was seeing some being available and some unavailable (repeatably): I was requesting them all at the time, so my impression was that they were being added one by one?

**Comment by dcarosone** [comment]
Aside: does adding folders have to wait for the upnp time-out?

**Comment by calmh** [comment]
Looks like I was wrong on both accounts; this part changed recently. It happens [here](https://github.com/syncthing/syncthing/blob/master/cmd/syncthing/main.go#L530) - the API ("GUI") is started, and then folders are added immediately. However old indexes are dropped in the same loop, which may take anything from zero to infinity depending on the index size and database status when syncthing last shut down. Strong bias towards "zero" though on real hardware.
