### ISSUE TITLE
First start fails - No Node ID (key) no interface on android 4.4.

### ISSUE THREAD

**Issue by vohe** [syncthing/syncthing#1664]
Hi, 
got a new mobile. Wiko Ridge 4G . Android 4.4.xx
After new installation of the syncthing, the assistant opens up, telling me "generate a key, this may take a while" (translated free from german). 
After half an hour i stop this. Shut down the mobile make restart, and start syncthing app again.
Now it tells me "waiting for interface" which is also for endless time on the screen. 
It seems there is a failure with this mobile/android/syncthing version?

btw.: I got it to run on similar another mobiles and notebooks. (Wiko Rainbow Android 4.4.2, Huawei Y330, Samsung S3, ...)

**Comment by AudriusButkevicius** [comment]
Wrong repo https://github.com/syncthing/syncthing-android
But check existing issues.
