### ISSUE TITLE
High CPU Usage; syncronizing while Web UI is open

### ISSUE THREAD

**Issue by fazky** [syncthing/syncthing#1667]
Hello,

I observe 100% CPU load if I try to check and observe the sync status with the web UI while syncing.  If I close the web UI, the CPU load goes down to normal values.  This was especially painful with my RaspPi, where the initial sync was exceedingly slow because of this and I even expected the Pi to be too slow for `syncthing` (I repeatedly checked the status with the UI and by doing this, syncing completely stalled).

My `syncthing` version is `0.10.30`.  Please tell me, if I can provide log messages.

Thanks,
Dominik

**Comment by AudriusButkevicius** [comment]
This is known should improve in 0.11
