### ISSUE TITLE
List of devices is not sorted alphabetically [v0.11.0-rc1]

### ISSUE THREAD

**Issue by chris-thorn** [syncthing/syncthing#1668]
Similar to issue #1649, the list of devices is not sorted alphabetically in v0.11.0-rc1.

**Comment by calmh** [comment]
They are for me (i.e. cannot reproduce here)...

**Comment by chris-thorn** [comment]
Hmm. This is what I see:

<img src="http://i.imgur.com/UcWbh41.png" />

I have just rebooted the machine on which I am viewing the web UI, and cleared my browser cache (and switched browser), but list of devices remains in the same [unsorted] order.

I wonder if there's something else I should try to get it to work?

PS: Thanks for all your hard work - I *love* using Syncthing.

**Comment by calmh** [comment]
Lol typo :( Thanks! :)

**Comment by calmh** [comment]
And the obligatory typo in the commit message to go with it. Good stuff.

**Comment by chris-thorn** [comment]
lol, nice one :)
