### ISSUE TITLE
Better way of switching upgrade tracks in the gui

### ISSUE THREAD

**Issue by jpjp** [syncthing/syncthing#1670]
Might be a bad idea. Might not!

**Comment by calmh** [comment]
Fairly traditional seems to be a checkbox somewhere `[ ] Upgrade to beta releases` that is unchecked by default (checked by default if starting on a beta)...

**Comment by jpjp** [comment]
Okay. But if you uncheck it, does it upgrade to the next highest stable release?

Alternatively: Upgrade policy: do not upgrade | stable releases | beta releases.

**Comment by AudriusButkevicius** [comment]
Fixed.
