### ISSUE TITLE
Synchronization stuck at 86%

### ISSUE THREAD

**Issue by ManuelSchneid3r** [syncthing/syncthing#1671]
In the visual feedback in the devices section:
![auswahl_001](https://cloud.githubusercontent.com/assets/3252315/7238361/0e01667e-e7a2-11e4-9ede-ab8e09e7152c.png)
Archlinux 3.19.3

**Comment by AudriusButkevicius** [comment]
Check the other side.
It's most likely that some files are ignored or the folder is set to master causing it to look out of sync.

**Comment by fti7** [comment]
I have the same Issue here.
No Master Repos and No Ignored Files

0.11.2 Windows & Linux
Stucked @ 95%

Its just on one Site, the other looks fine
Deleting both Indexes doesnt fix the issue

**Comment by calmh** [comment]
This is by all accounts #1765.
