### ISSUE TITLE
Duplicate folder ID handling is crappy

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#1675]
If two folders both have the ID "default" in the config, we rename them to "default~1" and "default~2". But tilde isn't allowed in folder IDs, and the user can't change folder IDs in the GUI, so it's kinda impossible to recover gracefully from.

Granted, they shouldn't be able to get in this state without editing the config manually to start with, but still...

**Comment by BETLOG** [comment]
loading the saved config more than one resulted in this state for me

**Comment by AudriusButkevicius** [comment]
Again, you are refering to android, which has it's own repo.

**Comment by Zillode** [comment]
(@BETLOG this is fixed for Android in v0.6.0)

**Comment by Zillode** [comment]
I implemented this behavior, however:
- Modifying the folder ID in the webGUI seems to be impossible, even for valid names?
- Changing the tilde to a dash means the folder will become valid for the next session (without any error msg).
