### ISSUE TITLE
.stignore: support `!(?)` combination, and `somepattern/` to match only directories

### ISSUE THREAD

**Issue by rolve** [syncthing/syncthing#1678]
It seems to me that the current .stignore format makes it impossible to implement a simple use case: to only synchronize files with a certain file extension. I think there are two problems with the current format.

First, I tried to mark the files with the desired extension as included:

    !(?)*.jpg
    !(?)*.png

This already did not work, as it is not possible to use both `!` and `(?)` as a prefix. I tried both `!(?)` and `(?)!`, none seemed to be working.

Second, I did not find a satisfying way to exclude the rest of the directory structure. Of course, simply

    *

does not work, as it matches all directories, stopping syncthing from looking inside them. The next best thing is probably

    *.*

but this also excludes directories (and their contents) with a `.` inside. Plus, it does not exclude files without a `.`. What is necessary is a distinction between patterns that match directories and patterns that match files. I think the approach taken by git (http://git-scm.com/docs/gitignore) is sensible: everything that ends with a `/` matches directories only and everything else matches files only.

What do you think?

**Comment by calmh** [comment]
This is currently not possible. I'm not sure it necessarily makes sense as general purpose feature.
I.e. is this only for files? I guess you want to sync .jpg files inside directories not named .jpg? If I delete all jpegs and the directory containing them on one box, what should we do on the other where the directory contains other files to? We have a conflict on that directory now.

**Comment by rolve** [comment]
First, here is my use case. I want to sync my home folder to my Android phone, but I only want to sync files that I can actually use on the phone, e.g., .txt, .pdf, .jpg, etc. All files with these extensions should be synchronized, regardless of where they are located. Is this such an unusual use case?

Then, I don't understand what you mean with "this is currently not possible". I already managed to get close to what I want using

    !*.txt
    !*.pdf
    !*.jpg
    *.*
With this setup, it can also happen that one machine deletes a directory which contains less files than another machine.

**Comment by calmh** [comment]
Well, as you noted, you cannot exclude `*` and still unexclude files in the excluded directories. But yes, you're almost there. But you'll not syncthing on your computer will get unhappy if you delete a directory from the phone, where that directory contains other files on the computer.

**Comment by rolve** [comment]
Ok, so I'm almost there. The way I see it is that the two things to get *all the way* there are the following:

1. Support for both `(?)` and `!` in the same pattern
2. Support for directory-only patterns and/or for file-only patterns. E.g. `*/` matches only directories and `*` matches only files.

Don't you think these two features are reasonable, even independent of my particular use case?

**Comment by calmh** [comment]
I think those seem like reasonable additions/fixes to the current system.

**Comment by rolve** [comment]
Thank you for your answer. You're probably right about the unexpected `*` pattern behavior. I just realize that git does not version empty directories and therefore does not suffer from this problem. I'm not sure why git does it like that, but I think not synchronizing empty directories in general could also be unintuitive. Still, it could be a solution.
Also, I found out that my `!(?)` attempt was double if not triple wrong. First, according to 9fed75d59c1ea5d008eddc41d519c5ddeabc5751, the actual modifier for case-insensitive patterns is `(?i)` and not `(?)`, contrary to what [this wiki page](https://github.com/syncthing/syncthing/wiki/Ignoring-Files) says. Then, I did not even use version 11.0, where the feature was introduced. Finally however, since I am on Windows, according to #1511, my patterns are supposed to be case-insensitive *anyway*! So maybe the first point does not require a fix at all (will try this later), but the second point remains.

**Comment by Zillode** [comment]
Use ```(?i)!*.png``` to solve your problem.

**Comment by rolve** [comment]
Thanks for your help. Unfortunately, this still doesn't seem to be solved. I have set up a very simple folder with the following ignore pattern:

    (?i)!*.txt
    *
Then a placed the three following files into the folder:

    test.txt
    TEST2.TXT
    test3.TxT

None of them are picked up by syncthing (local and global state say "0 items, ~128 B").

**Comment by rolve** [comment]
Sorry to dig this old issue up, but it just it's resolved yet. I just checked again and on my Windows machine, the pattern

    (?i)!*.txt
    *

excludes all of the following files:

    test.txt
    TEST2.TXT
    test3.TxT

So, could somebody reopen this issue?

**Comment by AudriusButkevicius** [comment]
Did you try the beta?

**Comment by calmh** [comment]
This seems to have changed. I added this as a test case, and it passes on `master` (v0.13.0 on monday), but not in v0.12. So it's solved, but not in the current v0.12 release for some reason.

**Comment by calmh** [comment]
In v0.12 you need to express it as

```
!(?i)*.txt
*
```

that is, with the exclamation point first. You also don't need the `(?i)` as patterns are always case insensitive on Windows.

**Comment by rolve** [comment]
Alright, thanks. I haven't tried the beta yet.

(So in 0.13 both `!(?i)` and `(?i)!` will work then?)

**Comment by calmh** [comment]
Yes
