### ISSUE TITLE
v0.10.30 doesn't show upgrade button for v0.11.0

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#1680]
`syncthing -upgrade` works, but the button should be shown? Perhaps with a different note or color or something as it's a major upgrade. We should probably get this out as a last maintenance release on v0.10.

**Comment by NickPyz** [comment]
I am sure there are lots of users like me who are GUI-centric, and a last version 0.10.31 with a big button to upgrade to v0.11.0 will be appreciated.

**Comment by calmh** [comment]
Yes, it'll be there.

**Comment by canton7** [comment]
:+1:

**Comment by p1rox** [comment]
+1

**Comment by calmh** [comment]
This requires some finessing... v0.10 only checks the topmost non-beta release, so we need to let a v0.10 release be the latest for a while to get older v0.10 clients on board. v0.11 is smarter and actually looks for the highest version among the most recent releases. So probably we want to release time for v0.11.1, then release v0.11.1 tightly followed by v0.10.31, then let it hover there for a week or so. The downside is that the "latest release" links will point to v0.10.31.

**Comment by calmh** [comment]
(Merged into v0.10)
