### ISSUE TITLE
Broadcast: interface addresses: netlink rib: invalid argument

### ISSUE THREAD

**Issue by jpjp** [syncthing/syncthing#1682]
Shall I investigate more or is this okay?

**Comment by AudriusButkevicius** [comment]
Looks like dup of #1388.
If it's still showing up, can you enable STTRACE=beacon and get the file and line number where it's happening?

**Comment by jpjp** [comment]
I can't reproduce this any more. I have a feeling it was a kernel bug (I have since updated). I will add a comment here if it happens again.

**Comment by Somasis** [comment]
I think this is also a kernel bug, upgrading to 4.0.1 (only affected machines were ones running 4.0.0) seemed to fix it.

**Comment by apastuszak** [comment]
I'm on Arch with kernel 4.0.1 and still getting this error.  Also having problems with syncthing-gtk not being real happy with syncthing any more

**Comment by kylemanna** [comment]
I'm seeing this on Arch with kernel package 4.0.1-1

**Comment by Somasis** [comment]
It might be a good idea to upgrade to 0.11.2, it fixed some upnp stuff
which I believe that relates to...

**Comment by Barthalion** [comment]
0.11.2 is still broken.
