### ISSUE TITLE
Private multi-user sync server

### ISSUE THREAD

**Issue by jkufner** [syncthing/syncthing#1684]
I'm not sure if it is missing feature or missing documentation. Anyway, ...

Lets say a small group of users own a server (head-less non-stop running dedicated Debian Linux PC with good Internet connection) and they want to use this server to sync some files from their Android cell phones and Linux laptops. Sync server should act as always awailable node. Basic idea is that photos and other files from cell phone will get synchronized to the server and other devices owned by the same user may access them as well. Also automated daily backups of this server are made, so phone files are backed up automatically (after sync by syncthing).

So question is: What is recommended way of setting up the sync server for all users at once, where each user has his own private data storage?

**Comment by AudriusButkevicius** [comment]
If all users trust this server, then the the server can run a single instance of syncthing having ALL the devices of ALL users added, as well as ALL of their folders, and only share the relevant folders with the relevant devices.
 
The introducer feature might help adding new devices and new folders, though folder names have to be unique, which is unlikely to be true in a multi-tenant environment.

**Comment by AudriusButkevicius** [comment]
You can ask any further questions, regardless if the issue is closed.
Or visit the forum where it's a more appropriate place to discuss things.

**Comment by jkufner** [comment]
So you are practically saying that it is not possible. Then please consider this question to be a feature request.

**Comment by calmh** [comment]
On the contrary, this seems fairly straight forward as I understand it, assuming the users sharing a syncthing instance trust each other. What Audrius is saying (I think) is that discussing use cases is better in the forum than in the bug tracker. :)

**Comment by jkufner** [comment]
This is about each user having his own namespace not accessible by any other user, just like having his own home directory.

**Comment by dcarosone** [comment]
Then each user can run his own process with his own file permissions on the
shared server.

In practice, they'll probably want some things shared and some private.

On 23 April 2015 at 11:26, Josef Kufner <notifications@github.com> wrote:

> This is about each user having his own namespace not accessible by any
> other user, just like having his own home directory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncthing/syncthing/issues/1684#issuecomment-95382613>
> .
>



-- 
Dan.

**Comment by jkufner** [comment]
Daniel Carosone wrote, on 23.4.2015 03:48:
> Then each user can run his own process with his own file permissions on the
> shared server.

Yes. And question is, how to prepare such setup in a clean and easily
maintainable way (i.e. service running on single port and using unix
users or some virtual accounts, just like any other unix daemon).

**Comment by calmh** [comment]
Right. Syncthing is not multiuser in any way. Making it so would be a major undertaking, and not in scope for 1.0 at least.

**Comment by jkufner** [comment]
According to what I saw in documentation and in your reactions, there is
one relatively simple sollution:

Lets create daemon, which will run as root and listen for incomming
connections for all users. This daemon will know local device IDs of all
users and their owners -- each user will generate keys (certificates) in
their home to enable the service, daemon will have index of these keys
(automatically updated). So it will be like if each user is running his
own instance, but without actually running it.

When incomming connection arrives, the daemon determines whose device is
requested (just like Gitolite does with SSH keys) and it forwards the
connection to correct instance of the Syncthing running under correct
unix user account (and starting it if it is not running yet).

I see three primary challenges here:
  1. Determine correct user by requested device ID.
  2. Connect users' instances to the daemon and dass connections
     to users' instance with as little overhead as possible.
  3. Automatically reload configuration when changed or new user is
     created.

This approach is similar to what is used by web servers to invoke CGI
scripts under different users (apache + suexec).

**Comment by AudriusButkevicius** [comment]
Yeah, I guess it's feasible, you could write a MITM proxy which external clients trust, and forwards requests to the relevant internal clients... but how is this different/better than just running an instance of syncthing under every user to start with?

**Comment by jkufner** [comment]
Great difference is in launching and setting up the service. With this
proxy/daemon you can easily prepare packages for general use without
conflicts in configurations between users (port number and firewall
config at least).

Also the configuration and keys can be generated on first login of a
user into web interface, where he gets server's device ID and other
info. So no per-user setup won't be required anymore.

**Comment by calmh** [comment]
There needs to be an interface or mechanism to transport the user's public key to the "multiplexing service", but sure, it's feasible.

**Comment by jkufner** [comment]
Simple scanning of all home directories should be enough.

**Comment by jult** [comment]
So, anybody ever planning to implement this? As I see it, it's the only feature missing in syncthing. Thus far the only multi-user GUI system that found a workaround for jkufner and my multi-user scenario is [the OpenMediaVault plugin of syncthing](http://forums.openmediavault.org/index.php/Thread/8759-Syncthing/?postID=105086#post105086), but that has its own issues, like right now for example it fails to even offer the correct instance to the different OVM system users. It used to work though, but it's a memory hog this way.

**Comment by marclaporte** [comment]
@jult done: http://wikisuite.org/How-to-install-Syncthing-on-ClearOS

As a bonus: With two factor authentication (via email for now) to access the Syncthing GUI.

This is in the context of WikiSuite, but you can just use Syncthing on ClearOS without using the rest of WikiSuite. This is where we are headed: http://wikisuite.org/Syncthing-in-WikiSuite

I hope you join us!
