### ISSUE TITLE
File versioning on Windows

### ISSUE THREAD

**Issue by Shishking** [syncthing/syncthing#1690]
Syncthing doesn't delete old files with "simple file versioning" on WinXP, and deletes correct with "Staggered File Versioning".
On Linux (Ubuntu) simple versioning works fine - keeps only two old versions (as I set).

**Comment by calmh** [comment]
`help-wanted` because I don't have XP any more to reproduce, and it seems to work on other platforms...

**Comment by davidbaumann** [comment]
Do we really want to support Windows XP?

**Comment by AudriusButkevicius** [comment]
I want to check perhaps it's an easy fix.

**Comment by calmh** [comment]
I see no reason it *shouldn't* work on XP, so no need to break compatibility if we can avoid it.

**Comment by AudriusButkevicius** [comment]
So the issue is that the new `\\?\` prefix to support longer path names breaks globbing
