### ISSUE TITLE
`-upgrade` should explain the solution more clearly when Syncthing is already running. 

### ISSUE THREAD

**Issue by step21** [syncthing/syncthing#1692]
As I understood it, while automatic upgrading does not work, upgrading with `-upgrade` option or `-no-exit` should work. However it says that another version of syncthing is running. This is partially true, but if the same version is run I would expect it to halt its other instantiation (or well, pass on the arguments given) and then perform the function. (such as upgrade or exit)
Is this expected behaviour? At least a more helpful error message would be great if it is.

**Comment by step21** [comment]
For me the solution was that when using upstart or similar to run/start (and respawn) that has to be used to stop it. Then it should work.

**Comment by step21** [comment]
This is an idea for a fix. Please comment if you think this is inaccurate or not helpful.
https://github.com/step21/syncthing/commit/b8cc86c71827c21eb3d5b0d994b41aee6d51a131

**Comment by AudriusButkevicius** [comment]
We know when `-upgrade` is used, in that case we should print a different message all together.

**Comment by step21** [comment]
Ok, makes sense. However, as I understand it, for `-upgrade` doUpgrade is the bool that checks whether it is set or not. So the placement of the text is correct right? Or is this also run when auto-updating?

**Comment by calmh** [comment]
That's the right place for -upgrade, looks like text in the right direction to me. If we wanted to be real nifty about it, we could parse the configuration for the GUI address and API key and throw a `POST /rest/system/upgrade` towards that. If that fails, try to lock the database and do the update ourselves. If that fails, we're confused and can legitimately print an error...

**Comment by canton7** [comment]
This approach breaks if the running syncthing exe isn't the exe being upgraded. While this approach probably works well in the majority case, can we please have a flag to re-instate the old behaviour?

Part of my release process involves upgrading the syncthing exes that I include in my installer. If I'm also running syncthing on that machine (as an entirely independent exe to the ones that will get packaged), then things get a bit confused and broken...

**Comment by canton7** [comment]
Actually, passing `-home` as a temp dir is a viable workaround. Maybe improving the documentation of `-upgrade` is the only worthwhile thing doing?

**Comment by Zillode** [comment]
I'm ok with reverting this commit. It could be done via syncthing-cli as well I think?
