### ISSUE TITLE
Can't access to REST

### ISSUE THREAD

**Issue by Zebradil** [syncthing/syncthing#1695]
I tried to use [syncthing-inotify](https://github.com/syncthing/syncthing-inotify) file watcher, but it does not work in case of request to /rest/system/config return 404. What's wrong?

```
wget https://localhost:8080/rest/system/config --no-check-certificate
--2015-04-25 11:23:02--  https://localhost:8080/rest/system/config
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
WARNING: cannot verify localhost's certificate, issued by ‘/CN=syncthing’:
  Unable to locally verify the issuer's authority.
    WARNING: certificate common name ‘syncthing’ doesn't match requested host name ‘localhost’.
HTTP request sent, awaiting response... 401 Unauthorized
Reusing existing connection to localhost:8080.
HTTP request sent, awaiting response... 404 Not Found
2015-04-25 11:23:02 ERROR 404: Not Found.
```

**Comment by AudriusButkevicius** [comment]
Are you using 0.10?
As the latest inotify release is only compatible with 0.11.

**Comment by Zillode** [comment]
Updated release notes of syncthing-inotify with some bangs.

**Comment by Zebradil** [comment]
Yes. Old version in Arch community repo. Thanks!

**Comment by rumpelsepp** [comment]
> Yes. Old version in Arch community repo. Thanks

I recently added the version info `syncthing>0.10` to the aur package as well: https://aur.archlinux.org/packages/syncthing-inotify
