### ISSUE TITLE
Ignored files remain "out of sync"

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#1701]
As per:
https://forum.syncthing.net/t/ignore-pattern-modification-and-override-changes/2531/12
```

 1. Create an empty sync folder pair on node A & B. Check folder master on A. By default the there is no .stignore file so there is no ignore pattern on either A or B.
 2. Create empty file Test1.txt on A. Wait for a while, it will appear on B. This is normal.
 3. Create the .stignore file on A and put "/Test1.txt" in it. This makes A ignore the file created in last step.
 4. Open Test1.txt on A and type in something. Save and close it.
 5. Create empty file Test2.txt on A.
 6. Wait for a while and Test2.txt appears on B. Test1.txt on B is still empty. This is normal as Test1.txt is in A's ignore list now so A will not transfer any content update of Test1.txt. This proves the ignore pattern on A is correct and working.
 7. Delete Test1.txt from A. Wait for a while.
 8. The Override Change button appears on A. Click the Out of Sync link on A will list Test1.txt. This is normal as B has Test1.txt but A though it don't have(because ignored).
 9. Click the override button on A. It will disappear for one second but back again in the next second. You can click the override button again and again, it always comes back. The Test1.txt is always listed as out of sync. The Test1.txt file never get deleted on B. This is not normal, and this is the issue I'm talking about.
 10. Create empty file Test3.txt on **B**.
 11. Now on A the out of sync link shows both Test1.txt and Test3.txt.
 12. Click the override button on A. Test3.txt disappears from out of sync link and B's folder. This is normal.
```

**Comment by AudriusButkevicius** [comment]
How does the test fix the issue? I assume step 9 is the problem.

**Comment by calmh** [comment]
Eh, good question.

**Comment by simplypeachy** [comment]
I also notice that the debug output is somewhat misleading in this circumstance when the "Override changes" button is pressed. "Excluded file.txt" is in the same situation as this issue's "Test1.txt" file:

model.go:1049: DEBUG: not sending update for ignored/unsupported symlink File{Name:"Excluded file.txt", Flags:020644, Modified:1441710228, Version:[{8709063819142425859 4}], Size:0, Blocks:[]}

**Comment by AudriusButkevicius** [comment]
It says that symlinks are not handled because you are not running as admin. This has nothing todo with this issue.

**Comment by simplypeachy** [comment]
I should have clarified - the file is not a symlink, nor are there any symlinks in the shared folder. It's just a normal file that is:
* Matched by an ignore pattern
* Present on the device, which is a Master
* Present on another device

**Comment by AudriusButkevicius** [comment]
Right, sorry, misread the error message. It's simply ignored.

But I still don't understand why you think the output misleading?

**Comment by simplypeachy** [comment]
Ah my apologies, I assumed it meant "ignored or unsupported symlink", where it's saying "ignored file or unsupported symlink"...whoops.

**Comment by calmh** [comment]
This is a straight up bug of some kind, unrelated to master mode. Simpler reproduction:

- Two clean nodes, A and B
- Create test1.txt on A, let it sync to B
- Ignore test1.txt on A
- Change test1.txt on B

A is out of sync.

Index on A when it's idle/disconnected/looks happy:

```
$ stindex h1/index-v0.11.0.db
Path: h1/index-v0.11.0.db
[device] F:"default" N:"test1.txt" D:7777777-777777N-7777777-777777N-7777777-777777N-7777777-77777Q4
  N:"test1.txt"
  F:020644
  M:1448192628
  V:[{5157751870738175669 1} {11395144714346075690 1}]
  S:0
  B:0
```

Index on A when it's connected to B, out of sync:

```
$ stindex h1/index-v0.11.0.db
Path: h1/index-v0.11.0.db
[device] F:"default" N:"test1.txt" D:JMFJCXB-GZDE4BN-OCJE3VF-65GYZNU-AIVJRET-3J6HMRQ-AUQIGJO-FKNHMQU
  N:"test1.txt"
  F:0644
  M:1448192628
  V:[{11395144714346075690 1}]
  S:4
  B:1
[device] F:"default" N:"test1.txt" D:7777777-777777N-7777777-777777N-7777777-777777N-7777777-77777Q4
  N:"test1.txt"
  F:020644
  M:1448192628
  V:[{5157751870738175669 1} {11395144714346075690 1}]
  S:0
  B:0
[global] F:"default" N:"test1.txt" V:00000001000000019e23afbe5ec4962a0000000000000001000000204b0a915c26c8c9c0b84926ea5f74d8cb408aa6249ed3e3b220a41064b8aa69d9
```

Note that it's accepted test1.txt into the global list. Not sure why it did that.

**Comment by AudriusButkevicius** [comment]
In completion et al we never check the flags, which I think is the issue.
