### ISSUE TITLE
Problem with case between Linux and Windows

### ISSUE THREAD

**Issue by Petemir** [syncthing/syncthing#1702]
I have a folder synced between Windows and Linux. For some reason, one of the sub-folders of the  synced folder appeared duplicated with case differences ("plp" and "PLP" being both names) in my Linux box, although of course just one of them ("PLP") appeared in the Windows box.

"PLP" had all the files, and "plp" was just empty. I removed the "plp" folder from the Linux machine and now the Windows one says that the synced folder isn't making any progress, that it cannot delete "plp" because the directory is not empty. Nothing appears in Linux CLI.

I suppose I can fix the error by deleting the synced folder from syntching in the Windows machine and re-adding it, but I wanted to report this issue just in case, because I don't know how the linux folder got duplicated originally.

I tried to reproduce the error creating both "test" and "TEST" (this one with one empty file, "helloworld") folders in the linux machine, but after syncing to the windows machine, the file appeared in both folders in Linux (so, when deleting one of the folders, the windows one disappeared and then the other linux one also disappeared), so I couldn't... also in my actual problem, if I add "plp" again in the linux machine, the error stops, and the folder stays empty, unlike when I try to reproduce the error.

Any log I can attach that can help? I don't know for how many days this has been going though.

OSes: Windows 8, Linux Mint KDE
Syncthing versions: both v0.10.30

**Comment by AudriusButkevicius** [comment]
Dup https://github.com/syncthing/syncthing/issues/439

**Comment by Petemir** [comment]
Sorry, searched and didn't find it

**Comment by AudriusButkevicius** [comment]
No worries.
Sadly, there isn't remedy.
Just make sure that you don't have duplicate directory names, as it's dangerous when a FS which is case-insensitive is involved.
