### ISSUE TITLE
GUI bug in ver. 0.11.1 - "About" screen not displaying

### ISSUE THREAD

**Issue by NickPyz** [syncthing/syncthing#1707]
Selected "Settings > About" ... the browser screen dims, but the "About" window fails to pop open. The other Settings options (Show ID, Shutdown, Restart) work as expected.

OS: Windows 7 - 64
Browser: Chrome 42.02311.90 m (64 bit)

Fails with Internet Explorer too.

**Comment by jpjp** [comment]
Broken on Firefox too.

**Comment by chucic** [comment]
In built-in in SyncTrayzor (CefSharp) too.
