### ISSUE TITLE
Fails to delete files after rename failed

### ISSUE THREAD

**Issue by hub101** [syncthing/syncthing#1710]
Cluster: 5 Windows machines (x32 and x64), 10.30 and later 11, star topology, shared folder with 5 midsized (200mb) files in different folders. Files updates about twice at week from any node. Time at nodes the same.

I update 1 file on node. Syncing begins. Looking console at remote node i see: "cant delete folder because not empty". WTF?! There are no any folder operations, only 1 file update! Restarting remote node. Remote syncthing restarts and deletes folder. Next move - its syncing back to my machine and remove this folder, destroying my data and makes me sick, finally removing this folder from cluster!

**Comment by AudriusButkevicius** [comment]
Have you got ignores set up?

**Comment by hub101** [comment]
No any ignores.
I think file operations is weakest part of syncthing. Folders or files removes unpredictable, sometimes making conflicts. Now at central node tuned on simple versioning, only this saves data from lost, i manually move it from archive back to sync.

**Comment by hub101** [comment]
And what means:
Global State	179 items, ~1.04 GiB
 Local State	175 items, ~620 MiB
 Out Of Sync	4 items, ~449 MiB
on _Unshared_ folder?

**Comment by AudriusButkevicius** [comment]
What that means is that we've got someone elses state of the folder before it was unshared.

If you restart syncthing (which if not mistaken you have to do in order to "save" the unshared state), that would fix itself.

There are over 10k machines running syncthing right now, and if everyone would have data loss, nobody would use it.

If you have network mounts or some sort of encrypted mountable volumes involved, a temporary unavailability of that volume can cause this behaviour.

Regardless, you can enable more verbose logging `STTRACE=model` on one of the nodes to figure out which one of your devices decides to delete the folder and then investigate further on that device with `STTRACE=scanner` to see why it suddenly sees the folder as removed.

**Comment by hub101** [comment]
All files are local. I'll try to check logs.

**Comment by hub101** [comment]
may be this
remote node:
[S2C3E] 22:37:06 INFO: Puller (folder "1s", file "buh2\\2.0.64.21.cf"): delete "Buh2\\2.0.64.21.cf" after failed rename: GetFileAttributesEx \\?\C:\Sync\1s\Buh2\2.0.64.21.cf: The system cannot find the file specified.

**Comment by AudriusButkevicius** [comment]
What's the OS?

**Comment by AudriusButkevicius** [comment]
Can you also provide your config, and how the path looks like?

**Comment by AudriusButkevicius** [comment]
Also, there should be more context in the logs, so a larger portion of the log would be useful.

**Comment by hub101** [comment]
Windows 7 x64
<script src="https://gist.github.com/hub101/54afba80fb677f7631e6.js">config</script> (some private info removed)
path looks like C:\Sync\1s\Buh2\2.0.64.21.cf
<script src="https://gist.github.com/hub101/6827ef52bdff31e70f5f.js">log</script>

**Comment by calmh** [comment]
This could be #1391?

**Comment by AudriusButkevicius** [comment]
It could. But perhaps I missed something with the rename code.

**Comment by hub101** [comment]
No connected peers, massive cyclic output:
[HQPQU] 2015/04/30 09:06:43.621536 rwfolder.go:181: DEBUG: rwFolder/foto@0x11d54500 skip (curVer == prevVer) 0
[HQPQU] 2015/04/30 09:06:43.624536 rwfolder.go:181: DEBUG: rwFolder/Acc@0x11d54400 skip (curVer == prevVer) 0
[HQPQU] 2015/04/30 09:06:43.632536 rwfolder.go:181: DEBUG: rwFolder/doc@0x11d54480 skip (curVer == prevVer) 0
[HQPQU] 2015/04/30 09:06:44.621593 rwfolder.go:181: DEBUG: rwFolder/foto@0x11d54500 skip (curVer == prevVer) 0
[HQPQU] 2015/04/30 09:06:44.624593 rwfolder.go:181: DEBUG: rwFolder/Acc@0x11d54400 skip (curVer == prevVer) 0
[HQPQU] 2015/04/30 09:06:44.632594 rwfolder.go:181: DEBUG: rwFolder/doc@0x11d54480 skip (curVer == prevVer) 0
[HQPQU] 2015/04/30 09:06:45.621650 rwfolder.go:181: DEBUG: rwFolder/foto@0x11d54500 skip (curVer == prevVer) 0

it's ok?

**Comment by Zillode** [comment]
@hub101 This is OK

**Comment by calmh** [comment]
Old, this code has changed somewhat, similar things fixed, if this is reproducible please yell.
