### ISSUE TITLE
Solution to the nssn service for syncthing (windows).

### ISSUE THREAD

**Issue by alatnet** [syncthing/syncthing#1713]
While this might not be an issue for syncthing, i thought i'd share how to set up syncthing to start automatically without using nssn, as a service, or using the programs\startup folder.

Have it set as a task in windows.
1. create the bat file as normal.
2. go to "Computer Management" (right click my computer and manage)
3. go to "Task Scheduler".
4. under "Actions" click on "Create Task".
5. under "Triggers" tab, add a new trigger and set it to "At Log on" (Optional, set it to a specific user)
6. under "Actions" tab, add a new action and set it to "Start a program", browse to the bat file and select it, also copy the location of where the bat file resides.  Using the location copied, paste it into "Start in (optional)".  This is important because it will not start up at all without this.
7. disable all conditions under "Conditions" tab.
8. disable "Stop the task if it runs longer than:" and "If the running task does not end when requested, force it to stop" under the "Settings" tab.
9. hit "Ok".
10. ???
11. profit.

Using this method, you can have syncthing run at startup of the system without having the security problem that nssn will introduce.

Add this method to the windows installer when you create it.

**Comment by rumpelsepp** [comment]
Maybe this fits better into the [forum](https://forum.syncthing.net/)? :)

**Comment by AudriusButkevicius** [comment]
Or the wiki

**Comment by alatnet** [comment]
Yea... sorry about that... didnt realize that there was a forum or wiki...

**Comment by lovetox** [comment]
maybe i am understanding something wrong here

but this process does not setup syncthing as a service.
its basically a over complicated autostart.

why not just putting a link into the autostart folder of the user?
i dont see the benefits

**Comment by wweich** [comment]
Me neither.
If I would want syncthing to be "service-like" on Windows, I would set the task to start on system startup in the context of my user. That way every configured syncthing instance would run always, not only if the user for that instance is logged on.

**Comment by lovetox** [comment]
the problem i see is though, you simply cant start a program as "service" with the task planner.
the task planner is nothing other than a more sophisticated autostart folder, where you can define conditions and time for example.

so the topic is misleading, this does not start syncthing as a service and therefor is not a substitute for NSSN

**Comment by alatnet** [comment]
it can go either way.
you can set it to start up when the computer starts under the triggers tab and it would act like a service if you'd like, but i'd believe that this would open it up to the same issue that installing syncthing as a service would introduce as it is being started by the "System" account, i think, and not a user account.

**Comment by lovetox** [comment]
it cant go either way.

this method can only start the process as a non-service.
so mentioning NSSM, which is a Service Manager and starts programs as a service, is misleading.

you named the topic "Solution to the nssn service"

whats the solution? to not start the program as a service?

i think there is some confusion about what a windows service is, and what NSSM does.

**Comment by alatnet** [comment]
ok, so i made a mistake in naming this...  I guess i should have named it as an alternative instead of a solution.
But there is a trigger in task manager to have the program start when the computer starts.
I honestly do not know the difference between a service, besides it being under the services section, and a task that starts a program at the start of a computer.

**Comment by AudriusButkevicius** [comment]
A service is monitored by the service manager, and restarted if it crashes, etc.

**Comment by alatnet** [comment]
settings tab: "If the task fails restart every:"  kind of the same thing right there only with the task scheduler instead of the service manager.
but this is a different way if you'd like to have more control over how syncthing stars.
i have it set to start up after login after 15 minutes.  it works quite well.
