### ISSUE TITLE
Document external File Versioning

### ISSUE THREAD

**Issue by senden9** [syncthing/syncthing#1716]
Please write some lines about the "protocol" for the external File Versioning. Maybe under [File-Versioning](https://github.com/syncthing/syncthing/wiki/File-Versioning)?
The feature was Introduced at commit d3f1eaf1a3d131aadb1877da0bb3b048cc2053e3.

**Comment by AudriusButkevicius** [comment]
We could just copy the description which is provided in the web ui as you select the option.

**Comment by hashworks** [comment]
Examples would be great, f.e. for usage with git.

**Comment by senden9** [comment]
Expect syncthing a special returnvalue?

**Comment by AudriusButkevicius** [comment]
Yes, expects a 0 exit code, otherwise will assume failure and stop syncing.

**Comment by inyun2u** [comment]
I have no idea how to use with this feature, could anybody show some commands examples please?

**Comment by patcon** [comment]
+1

**Comment by patcon** [comment]
nevermind -- this works:
http://docs.syncthing.net/users/versioning.html#external-file-versioning

Could probably close this out?

**Comment by senden9** [comment]
Here is a example: http://docs.syncthing.net/users/versioning.html#external-file-versioning
