### ISSUE TITLE
No sync at all between Ubuntu and android machines - "connection reset by peer"

### ISSUE THREAD

**Issue by Nixbligger** [syncthing/syncthing#1717]
Hello there,

I have a problem trying to setup an initial, simple folder sync with my Ubuntu and my two android mobile devices connected via wifi over my private LAN.
All went well in terms of connection and mutual device visibility until I shared the desired local folder with the two devices (with and without "omit file permissions" flag set). Suddenly they are not able to connect to each other and syncing does neither start nor proceed.
The syncthing service on the devices have been restarted multiple times, but to no avail.

The terminal log of the Ubuntu machine repeatedly states for both peers:
>[VMKXK] 12:31:01 INFO: Established secure connection to [Device-ID] at 192.168.1.210:22000-192.168.1.209:35025
>[VMKXK] 12:31:01 INFO: Connection to [Device-ID] closed: read tcp 192.168.1.209:35025: connection reset by peer

What could be the reason for this behaviour? Any hints would be highly appreciated.
And please do not hesitate to ask if further information should be required.

Cheers and thx for the consideration,
Nix

---
PS: syncthing protocol versions -
Ubuntu v0.11.0, Linux (32 bit);
Android 2x v0.10.30 (App 0.5.28)

**Comment by AudriusButkevicius** [comment]
Android is still at 0.10.

**Comment by dcarosone** [comment]
Hitting "refresh" obsessively in the Google Play Apps widget is now a
thing. :-)

On 27 April 2015 at 21:35, Audrius Butkevicius <notifications@github.com>
wrote:

> Android is still at 0.10.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncthing/syncthing/issues/1717#issuecomment-96616128>
> .
>



-- 
Dan.
