### ISSUE TITLE
Obfuscating published discovery information.

### ISSUE THREAD

**Issue by Stebalien** [syncthing/syncthing#1726]
From reading the documentation, it appears that device IDs are published to directory servers "in the clear". Unfortunately, this makes it trivial to use Syncthing Device IDs to track users (you can get a pretty accurate physical location from an IP address). Instead, please consider publishing `Hash(DeviceID, DiscreteTime)` where `DiscreteTime` is the current time rounded down to the last half-hour. When trying to establish a connection to a peer, Syncthing would lookup directory information using the hashed DeviceId for the current and the last half-hour intervals.

Second, to make enumeration harder (in case there's a vulnerability discovered in Syncthing), it would be nice if the discovery information itself were encrypted with a symmetric key derived from the device ID.

**Comment by AudriusButkevicius** [comment]
Sorry, but if I want to track X, what's preventing me from asking the discovery server where `Hash(X, Time)` is?

**Comment by calmh** [comment]
The purpose of the discovery server is to provide mappings from device ID to IP number. As long as it does that, it's unavoidable that you can track someone's IP by knowing their device ID.

**Comment by Stebalien** [comment]
The idea here is to ensure that (a) you can learn a device's IP address iff you know the device's ID and (b) Syncthing never exposes the device ID. This makes it harder for both the discovery server operator (as you noted) and anyone listening in on the network to track users. If users really wanted to avoid being tracked, they could talk to the discover server through tor.

**Comment by calmh** [comment]
> Syncthing never exposes the device ID.

This is unavoidable in a MITM situation though. Syncthing uses TLS, and TLS sends certificates in the clear.

**Comment by Stebalien** [comment]
I didn't realize that. That's unfortunate; it's effectively an internet-visible name-tag. Unfortunately, switching to another protocol is probably quite a bit of work.

**Comment by calmh** [comment]
Just so we're on the same page for the discussion, have you read through https://github.com/syncthing/syncthing/wiki/Information-Leakage? It clarifies how some of the things work, and perhaps points to more areas that need mitigation to achieve what you're looking for.

**Comment by jkufner** [comment]
This document is very scary. Syncthing leaks private data in multiple
ugly ways. It should be fixed.

Device ID may be safe to publish, but sending it every 30 minutes is
very helpful when tracking people. It also helps with piring devices
together, so atacker will know which devices belong to one user.

Not sending usage reporting by default is funny in this context.

Both Global and Local discovery should be off by default. Why it is
required anyway? Ok, syncthing needs to detect running instances, but it
can do so without disclosing device ID. Just broadcast some encrypted
random data plus device ID and if other client finds known device ID
after decrypting this blob, it can establish communication with snding
device. If decryption fails, the obtained device ID will be some other
random, but syntactically correct, device ID. So attacker will know
syncthing is running, but leaking user's identity.

**Comment by Stebalien** [comment]
> Both Global and Local discovery should be off by default. Why it is
required anyway? Ok, syncthing needs to detect running instances, but it
can do so without disclosing device ID. Just broadcast some encrypted
random data plus device ID and if other client finds known device ID
after decrypting this blob, it can establish communication with snding
device. If decryption fails, the obtained device ID will be some other
random, but syntactically correct, device ID. So attacker will know
syncthing is running, but leaking user's identity.

You can't just "broadcast" to the internet. If you "broadcast" to the discovery server, the peers would have to download and decrypt the entire discovery server.

> Just so we're on the same page for the discussion, have you read through https://github.com/syncthing/syncthing/wiki/Information-Leakage? It clarifies how some of the things work, and perhaps points to more areas that need mitigation to achieve what you're looking for.

I did but I only read the first paragraph of that section and didn't really think about it's ramifications (I thought eh, certificates are public). I ignored local discovery because I plan on turning it off (I need global discovery anyways and I can configure my local network so I don't need local discovery).

I'll close this so I can come up with a more complete proposal.
