### ISSUE TITLE
Stuck on Starting UPnP Discovery

### ISSUE THREAD

**Issue by dax0** [syncthing/syncthing#1727]
I have two devices, the first one is able to get up and running fine. The second one gets stuck on Starting UPnP Discovery. Can anyone point me in the right direction?

**Comment by AudriusButkevicius** [comment]
There is a 10 second timeout. Alternatively start with STTRACE=upnp env var set.

**Comment by AudriusButkevicius** [comment]
Also check the build at https://github.com/syncthing/syncthing/issues/1721#issuecomment-97331597 as I feel this could be a dupe.

**Comment by calmh** [comment]
Please do try the [latest dev release](http://build.syncthing.net/job/syncthing/lastSuccessfulBuild/artifact/) as this sounds very much like that issue just resolved.

**Comment by calmh** [comment]
Resolved.
