### ISSUE TITLE
"Release Notes" link in "Major Upgrade" modal dialog points to latest release, not the one to which you're upgrading

### ISSUE THREAD

**Issue by cyphase** [syncthing/syncthing#1728]
When you click on the button to upgrade to v0.11.1 from v0.10.31, it brings up a modal dialog with a link to the release notes. However, the link is actually to the *latest* release's notes, not the release notes of the release to which you're upgrading. I think it should explicitly link to the release notes of the new version in question.

I realize Jakob (@calmh) already acknowledged this in a comment to issue #1680, and that it'll likely never be a problem again now that Syncthing has smarter upgrading logic, but IMHO it's better to have an explicit link. At the very least I figured I'd mention it for the record :).

**Comment by cyphase** [comment]
Here's a link to the offending line as of the latest commit (as of this comment):

https://github.com/syncthing/syncthing/blob/32fe2cb65959d658eae32fcc384268407f4c360c/gui/index.html#L504

Of course you can't just modify the link there before every release; it has to be a dynamic value.

**Comment by calmh** [comment]
Yeah. It's mostly going to be right. But we could probably extract the right URL from the Github API and send it over the relevant place in the UI.

**Comment by LordLandon** [comment]
Started looking at this, and think I've got a fix, but updating the index.html doesn't seem to make it into the binary? Am I doing something wrong here? How does the html get packaged in?
