### ISSUE TITLE
"Override changes" button text not clear

### ISSUE THREAD

**Issue by SjonHortensius** [syncthing/syncthing#1731]
I have a share where changes from the Folder-Master are no longer propagated. The web-interface of this master shows a red 'Override changes' button when I expand the share. The state of this share is 'up-to-date' but all files are also out-of-sync.

How should I know what this button does, would it override files on the master; or on the 'slaves'?

**Comment by calmh** [comment]
It shows up when the master doesn't have the latest version of everything, and clicking it promotes whatever version is actually on the master to latest. Thus, it overrides changes made anywhere else in the cluster. How do you suggest labeling it?

**Comment by SjonHortensius** [comment]
In this case, the master does have the latest version, and all slaves are lagging. Maybe the button should explicitly say *Override changes on slaves*. Alternatively the button could have a title attribute saying 'Override changes made anywhere in the cluster'

**Comment by kozec** [comment]
I'm not sure how much it helps, but ST-GTK displays "Cluster out of sync" as state when override option is available, so there is at least _something_ what implies what is going to be overridden.

**Comment by SjonHortensius** [comment]
@kozec, but that also isn't clear as to what files will end up where? Maybe renaming to *Override remote changes* is a simple alternative?

**Comment by djtm** [comment]
+1 Override remote changes
Right now it always makes me fear that the master node's changes are overwritten with version from other nodes.

**Comment by scotepi** [comment]
+1 Override remote changes

You could also add a title/tooltip that give more of an in depth reason. Right now it is very confusing what the purpose of the button is. I initaly thought it was a way to allow the master to be overwritten.

**Comment by noreye** [comment]
What about 'Commit master changes to remote devices' or 'Update master changes to remote devices'

Its a bit more text but could be more clear. What do you guys think?

**Comment by calmh** [comment]
It doesn't fit on the button. And I don't think it's any less ambiguous. "Override remote" could work though, it's just noone has tried actually writing it on the button yet.

**Comment by xor-gate** [comment]
At time of writing we are at stable version 0.11.26 and still it feels weird to overwrite changes (to where?) maybe a tooltip or so could mention what happens if the button is hit. Because it feels i throw away local changes, but it changes the remote nodes.

**Comment by dancinglightning** [comment]
came here from google to find out what changes i am asked to overwrite.
+ 1 for changing the text , but
+2 for not having it. Imho having a master folder means that that folder is authoritative, no questions asked

**Comment by AudriusButkevicius** [comment]
Well but the master folder is a decision made by the clients, so two clients mark it as master, what happens then?

**Comment by larslemberg** [comment]
Perhaps there should be a restriction to allow only one master folder in a cluster. Since it is a master folder, it can never be out of sync, and the Override Changes button becomes unnecessary.

**Comment by AudriusButkevicius** [comment]
And how do you restrict in a distributed system where there is no authority?

**Comment by calmh** [comment]
We could detect it as a misconfiguration and stop the folder. But we're not going to do that because there are valid use cases for multiple masters. See also all the forum threads about automatic override for why *that* isn't happening. ;)

**Comment by calmh** [comment]
Incorporated into #2679.
