### ISSUE TITLE
.stignore - Document how to handle spaces in path elements

### ISSUE THREAD

**Issue by dwvisser** [syncthing/syncthing#1736]
I don't see how I'm supposed to handle whitespace in path elements in .stignore, from looking at https://github.com/syncthing/syncthing/wiki/Ignoring-Files. (In various shells, spaces in filenames usually have to be escaped or quoted somehow.)

My use case is syncing my ~/Documents folder on Windows, which contains symbolic links named "My Pictures", "My Videos", etc., that I add entries for into .stignore. Even if .stignore handles unescaped spaces in patterns, I would like to see that explicitly documented.

**Comment by AudriusButkevicius** [comment]
the wiki is publicly writable, feel free to contribute.

**Comment by dwvisser** [comment]
I don't know enough to answer my own question here. I was hoping somebody who does could update the wiki and close this or let me know.

**Comment by calmh** [comment]
There's a pattern per line, so spaces are just a character like anything else.

Ignore the folder "My Pictures":

```
My Pictures
```
