### ISSUE TITLE
"About" pop-over not working in 0.11.1

### ISSUE THREAD

**Issue by Gutza** [syncthing/syncthing#1739]
At least under Windows, the "about" pop-over... doesn't.

Steps to reproduce:
1. Open the web interface
2. Click the gear menu, then click the "About" menu entry.

Result: the background dims, and all controls are disabled, but there's no pop-over, and since there's nothing to close, you end up with an unusable interface; you have to reload the page.

**Comment by Zillode** [comment]
Dup of #1709 and #1707
