### ISSUE TITLE
Staggered versioning creates folder path when it should just be stopped

### ISSUE THREAD

**Issue by ech1965** [syncthing/syncthing#1749]
Syncthing V0.11.1 on  OSX 10.10.3

I have a syncthinged folder stored on an external disk. (Named HDD so when I plug the disk, the file system is mounted on /Volumes/HDD

Now the problem:

If I boot mac laptop without the external disk attached, syncthing starts and creates an empty directory named /Volumes/HDD. ( I checked by stopping syncthing, deleting the directory and restarting syncthing: the directory reappears)

in the main window I receive those messages:

----log
10:25:52: Versioner: error scanning versions dir lstat /Volumes/HDD/ec/Gold/CalibreKOBOEtienne/.stversions: no such file or directory

10:25:52: Stopping folder "CalibreKOBOEtienne" - folder path missing
----log

Of course, if I plug the disk, as the /Volumes/HDD directory exists, OSX creates "HDD 1" and mount the filesystem there -> syncthing never finds the directory to sync...

----folder paramters
Folder Path	/Volumes/HDD/ec/Gold/CalibreKOBOEtienne
 Global State	2757 items, ~502 MiB
 Local State	2757 items, ~502 MiB
 Rescan Interval	10 s
 File Versioning	Staggered File Versioning
 Shared With	mediatank, pc-etienne
 Last File Received	

------

**Comment by calmh** [comment]
This is a bug in staggered versioning.

**Comment by ech1965** [comment]
Whoua ! That's fast !!
My syncthing's updated to 0.11.2 and the bug is fixed !!!

Thanks à lot !
