### ISSUE TITLE
Web UI reloads ad infinitum "unkown device", v0.11.2

### ISSUE THREAD

**Issue by ozra** [syncthing/syncthing#1753]
I installed version 0.11.2 just now.
On node A, the web ui pops up, and the ui barely blinks up in view until it reloads. From the title bar I can tell "device {{device-id}}" --> "Device unknown" - something like that.
This reloads and reloads for a minute until it finally settles and produce the UI with machine name in place. However the folders are reported as empty. After yet 1 or 2 minutes, it finally updates the folders in the UI with their correct contents.
On node B, everything works as usual.
I installed 0.11.2 on both before restarting them.

**Comment by calmh** [comment]
Javascript logs or something from the browser that keeps reloading? Seems like a strange thing for it to do. We do force a reload if we detect the version has changed, so may be an issue there somewhere...

**Comment by ozra** [comment]
The whole browser tab keeps reloading.
I stopped both syncthing (0.11.1, installed yesterday..)
I installed 0.11.2 on both.
I started syncthing on both.
node A displayed above behaviour (nothing strange in the output from syncthing in the terminal)
node B behaved all good and dandy (UI loaded in browser and was correct)
Anyway, it is all working as should now. Though, I will restart A again now and see if it repeats:
Nope. Now it works. It says "unknown device" for a short short while, but then updates with the machine-name (I expect this is normal async behaviour of the app), it doesn't reload even once now, and the folder contents (I refer to it as folders in the web-ui context) are updated correctly within 30s (it's a slower machine, use it for mirroring/live backup).

**Comment by ozra** [comment]
(
oh, and as a parantheses - hard to know where to "report" praise ;) - fucking amazing effort! I love being able to ditch Dropbox - **this project rocks**!! :)
)

**Comment by MoodyMoon** [comment]
This happened to my setup as well. During its first startup after upgrading from v0.11.1, the web ui opened using Google Chrome 42.0.2311.135 m keeps reloading even after refreshing a couple of times but this doesn't occur using Mozilla Firefox 37.0.2. This problem resolves itself after restarting Syncthing. At least, I hope it did. ^^

**Comment by calmh** [comment]
I think this may be a cache issue in the upgrade. We've changed how we set the "Last changed" date on HTML assets. In v0.10 it was set to when syncthing started; in v0.11, it's when we compiled syncthing (basically). If your v0.10 was started after the v0.11 version was *built* (which is quite likely), the browser might not understand that the files have changed and continues using the v0.10 GUI, which doesn't work.

As such, I think this is a one time thing on upgrading - annoying, but really a problem in v0.10 and not something we can solve after the fact.

**Comment by ozra** [comment]
I might add to this that I did not experience it going from 0.10 to 0.11.1 (no problems), but rather when going from 0.11.1 to 0.11.2.

**Comment by calmh** [comment]
That makes less sense to me though... :/

**Comment by MoodyMoon** [comment]
> I might add to this that I did not experience it going from 0.10 to 0.11.1 (no problems), but rather when going from 0.11.1 to 0.11.2. - ozra

Similar situation for me too.
