### ISSUE TITLE
local path on network drive

### ISSUE THREAD

**Issue by tjldtf** [syncthing/syncthing#1758]
Starting syncthing 0.11.2 (Windows 7) for the first time. First, the error message is 

WARNING: Stopping folder "default"  - open \\?\U:\Sync\.stfolder: The system cannot find the path specified.

With the second start of syncthing that folder U:\Sync is then created. "U:" is a network folder which is not always available and thus the default folder should better be at "C:".

**Comment by calmh** [comment]
Huh. So `U:\` is your `%UsePrrofile%` location?

**Comment by tjldtf** [comment]
echo %userprofile% gives C:\Users\_profilename_. There is also a folder C:\Users\_profilename_\AppData\Local\Syncthing.

**Comment by tjldtf** [comment]
The W7 machine is member of a domain. The %homedrive% is "U:"

**Comment by tjldtf** [comment]
Sorry mistyped before; echo %userprofile% shows C:\Users\_profilename_
Seems that

"home":   homeDir()
locDefFolder:     "${home}/Sync"

and

func homeDir() string {
	home, err := osutil.ExpandTilde("~")
	if err != nil {
		l.Fatalln(err)
	}
	return home
}

is the cause. For Windows the local Sync folder should rather be at the location %UserProfile%.

**Comment by tjldtf** [comment]
The second backslash after "C:\Users" disappeared again, but you know what I mean...

**Comment by calmh** [comment]
Looks like we prefer `%HomeDrive%/%HomePath%` when that is set, otherwise `%UserProfile%`. I've been led to believe this is the right behavior on Windows, but I'm not a user myself. :)

**Comment by SafwatHalaby** [comment]
It's might the Markdown. You can the following to avoid it:

 \`\`\`
Your code and literal stuff here
Good looking stuff, line 2
Good looking stuff, line 3
\`\`\`

The result is something like this:
```
Your code and literal stuff here
Good looking stuff, line 2
Good looking stuff, line 3
```

For an inlined code/path string, use \`these back ticks\`
It would look like this:
For an inlined code/path string, use `these back ticks`

**Comment by tjldtf** [comment]
The variable %UserProfile% points to the user's logon profile whereas %HomeDrive%\%HomePath% points to the user's home folder, but which can be set to anything.
Not sure, whether to decide it as a Windows issue or to use with %UserProfile% instead of %HomeDrive%/%HomePath%.

**Comment by calmh** [comment]
Far as I understand it, the profile is for settings and stuff, and the home path is for documents and such. I think this is the correct behavior as it is, although there seems to be an issue in your setup specifically. I assume that U:\ may not be available when syncthing tries to start? Although I suppose it ought to have been auto mounted when you logged in?

**Comment by tjldtf** [comment]
The profile has also the folders Desktop, Downloads, Contacts, My Documents etc. and is thus also for personal documents and stuff. On a single PC that makes no difference. On a domain there are more possibilities. Yes, U:/ is auto mounted with the login. I tested the scenarios coming with these cases.
In the moment, Syncthing will install locally at %UserProfile%/Sync if a laptop is offline and at %HomeDrive%/%HomePath%/Sync if it's online. In the first case, if the laptop is again online, everything is locally and works fine. In the second case, if the traveling laptop is offline, the Sync folder is inaccessible.
I think now, it's better to use UserProfile only. Because, both, the HomeDrive/HomePath and UserProfile can be local or on a server, but the UserProfile is always dedicated to a user, whereas the HomeDrive/HomePath can, but has not to be dedicated that way. Even a roaming UserProfile has a local copy.
Therefore, I suggest to change in "getHomeDir()"  the

	case "windows":
		home = filepath.Join(os.Getenv("HomeDrive"), os.Getenv("HomePath"))
		if home == "" {
			home = os.Getenv("UserProfile")
		}

to 

	case "windows":
		home = os.Getenv("UserProfile")

which holds the Sync folder locally and thus always accessible.

**Comment by calmh** [comment]
This needs some sort of investigation and consensus from the Windows using community... Yell/reopen/submit PR when such exists.
