### ISSUE TITLE
Strange Sync Stats Calculations / more than 100% / negative percentage

### ISSUE THREAD

**Issue by fti7** [syncthing/syncthing#1759]
After some simple Stress Test with:
<pre>
for i in `seq 1 10000`; do echo "$i" > test$i; done;
</pre>
I've got very Strange Stat Calculations on the connected Nodes
![syncthingbug](https://cloud.githubusercontent.com/assets/7014664/7462966/f4435b74-f2b5-11e4-9c9d-60303386a3b4.PNG)

Sync Direction: Linux -> Linux + Windows
Version: 0.11.2

**Comment by calmh** [comment]
Yeah, that's weird. Good with a reproducer, I'll see if that happens on my side as well. :)

**Comment by calmh** [comment]
```
[JMFJC] 23:53:11 VERBOSE: Summary for folder "default" is map[localDeleted:0 needFiles:10000 needBytes:48894 inSyncFiles:0 state:idle version:10002 globalBytes:48894 localBytes:0 inSyncBytes:0 localFiles:0 globalDeleted:0 globalFiles:10000]
[JMFJC] 23:53:16 VERBOSE: Summary for folder "default" is map[needFiles:9000 needBytes:-87050 globalBytes:48894 inSyncFiles:1000 state:syncing globalFiles:10000 localFiles:1000 localDeleted:0 localBytes:4872 inSyncBytes:135944 version:11005 globalDeleted:0]
[JMFJC] 23:53:19 VERBOSE: Summary for folder "default" is map[localFiles:5363 localBytes:26205 needFiles:4637 inSyncBytes:157277 version:15368 localDeleted:0 needBytes:-108383 inSyncFiles:5363 state:syncing globalFiles:10000 globalDeleted:0 globalBytes:48894]
[JMFJC] 23:53:22 VERBOSE: Summary for folder "default" is map[needFiles:3034 inSyncFiles:6966 inSyncBytes:165118 needBytes:-116224 version:16971 state:syncing globalFiles:10000 globalDeleted:0 globalBytes:48894 localFiles:6966 localDeleted:0 localBytes:34046]
[JMFJC] 23:53:25 VERBOSE: Summary for folder "default" is map[globalFiles:10000 needBytes:-126941 inSyncFiles:9155 globalDeleted:0 localBytes:44763 version:19160 localFiles:9155 inSyncBytes:175835 state:syncing globalBytes:48894 localDeleted:0 needFiles:845]
[JMFJC] 23:53:26 VERBOSE: Summary for folder "default" is map[localDeleted:0 globalBytes:48894 localFiles:10000 version:20005 globalFiles:10000 needFiles:0 needBytes:0 inSyncBytes:48894 state:scanning globalDeleted:0 localBytes:48894 inSyncFiles:10000]
```

**Comment by calmh** [comment]
I think this is "just" a race condition. When doing this test, there's a lot of updates going on as the files are being synced. The things that calculate the sizes and how many bytes we need are not atomic. I.e. we summarize how many bytes we need "now" and then subtract the number of bytes transferred during the current pulling iteration, but we may have added and fully processed files between those two calls.

**Comment by sbechet** [comment]
Confirmed when synchonizing a new empty folder from large existing share.
Example: 0.11.7 32 bits version : -33%
GlobalState 87058 files, ~1.48GiB
LocalSTate 1763 files, ~13.0 MiB
NotSync 115103 files, ~1.96GiB

Note: sync is _really_ slow (read: impossible to sync) and remote device (64 bits) come offline, then online from IHM without good reason.

**Comment by calmh** [comment]
Quite sure this does not happen anymore.
