### ISSUE TITLE
Strange Sync connections ?

### ISSUE THREAD

**Issue by chrisidefix** [syncthing/syncthing#1760]
Today I upgraded all machines to syncthing v0.11.2 - in the process I noticed syncthing connected to some strange IP. I was wondering what the need for syncthing is to connect to this address or if you have any idea why this may occur:
`pimage.timespeople.nytimes.com`

I also took a screenshot of the connection history:
![syncthing_connections](https://cloud.githubusercontent.com/assets/382555/7470957/bb605f84-f321-11e4-956c-8b784c7b01f2.jpg)

**Comment by calmh** [comment]
```
jb@syno:~ $ host pimage.timespeople.nytimes.com
pimage.timespeople.nytimes.com is an alias for s3.amazonaws.com.
..
```

My guess is this is your firewall picking a name on random out of possibly thousands (?) that are aliased towards amazon s3. Github serves upgrades from amazon s3, among other things, which may be why there's a connection to it.

**Comment by chrisidefix** [comment]
Thanks, I thought it would probably be something simple like that.

*Off-topic:* I somehow expected updates to be hosted and served through github - are the related costs for Amazon all covered through donations or are you guys paying for this yourselves ?

**Comment by AudriusButkevicius** [comment]
Github uses amazon, hence it's a cost for github.
