### ISSUE TITLE
Network device "disconnected"

### ISSUE THREAD

**Issue by bittorrenter** [syncthing/syncthing#1761]
Hi,

LOVE Syncthing

Three devices in Windows network - all visible in File Explorer on Win 8.1 via Asus RT16 router

Win 8.1: connected: Laptop W7 (wireless), "disconnected" Desktop W7 LAN (the computers are 1 metre apart and LAN connected to the router)
Laptop W7: connected: Win 8.1 (wireless), Desktop W7 (wireless)
Desktop W7: connected: Win 8.1 (LAN), Laptop W7 (wireless),

Over.

**Comment by AudriusButkevicius** [comment]
Not sure what the question is.

**Comment by Zillode** [comment]
I think there is a connection problem between his Win8.1 and Desktop W7 pcs in a local network.
@bittorrenter is local discovery enabled?

**Comment by bittorrenter** [comment]
Hi,
Thanks for your reply.
It looks like my VPN program was interfering with local discovery.
 Regards,
