### ISSUE TITLE
android folder picker shows duplicated folders

### ISSUE THREAD

**Issue by BETLOG** [syncthing/syncthing#1764]
Syncthing Version:0.10.30
Syncthing-Android Version:0.5.28

Android displays /storage/sdcard0 twice and incorrectly sorted.
ie:
/storage/sdcard0
/storage/sdcard1
/storage/sdcard0

**Comment by AudriusButkevicius** [comment]
Wrong repo. 
https://github.com/syncthing/syncthing-android/
