### ISSUE TITLE
FAIL: TestReset, file in use [Windows]

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing#1768]
http://build.syncthing.net/job/syncthing-windows-integration/115/console
(and http://build.syncthing.net/job/syncthing-windows-integration/116/console)

```
--- FAIL: TestReset (3.16s)
	reset_test.go:124: Failed to reset indexes%!(EXTRA *errors.errorString=Reset "": status code 500: remove h1\index-v0.11.0.db\000002.ldb: The process cannot access the file because it is being used by another process.
		)
```

**Comment by calmh** [comment]
This one looks genuine

**Comment by calmh** [comment]
This is probably a timing issue with the tests on Windows, where the test database is still locked by some previous thing when the reset test runs...
