### ISSUE TITLE
Big file broken

### ISSUE THREAD

**Issue by franz-benjamin** [syncthing/syncthing#1780]
I am using v0.11.2 on OSX. I was transferring a file of 25GB size, and the transfer had started during the creation of the file. The file size of the original file as well of the transferred file are identical, but the content has another md5 sum. How can this happen? Is there any way of how to prevent this?
Thanks!

**Comment by dcarosone** [comment]
I would guess a block size mismatch between writer and reader (syncthing).
Syncthing read a partially written app block, transferred it, and then
didn't rehash the block when the rest was written.

Perhaps mtime granularity plays a role, and perhaps the app writing
pre-extended the file (or wrote using lseek) before filling in the gaps.

If you could confirm where in the file the difference is, that could
confirm if it's the last block.

Clearly a bug. Workaround would be to touch(1) the file at the valid
source.

One of the things I recall btsync saying was the they detected files being
closed (presumably via inotify) before starting to send.

Alternately, we may need to keep the time our hash was last taken
(started), and rehash if it+fuzz is earlier than mtime. This probably
overlaps with the virtual mtime work.

**Comment by dcarosone** [comment]
Other options include hardware / memory corruption at the writer after
syncthing sent good data to the os. Can happen more often than you might
think.

**Comment by franz-benjamin** [comment]
I did another test with a similar file, same result if the file is transferred at the same time as when it is written. This speaks against hardware/memory corruption. I did a "touch" to the file but syncthing did not try to send it again. (I do this regularly to smaller files, and it always works.) Mh, strange issue. One of the other reasons you name may be true.

**Comment by dcarosone** [comment]
At least it's repeatable.

Time for some extra logging.

**Comment by AudriusButkevicius** [comment]
Can you define the exact steps of reproduction?

**Comment by franz-benjamin** [comment]
I can try but it does not always occur but regularly:
(1) Two computers (I call them A and B), both OS X Yosemite and v0.11.2. Upload from the A to B is 1.5 MB/s.
(2) I render a scene using Blender (blender.org) on A. The file creation takes about 30 hours to complete and produces a 25GB file. (The bug occurres also with much smaller files but not that often.)
(3) During the rendering process, computer A is using all its cpu for blender, and syncthing does usually stop syncing; it just waits and doesn't do anything, and then "suddenly" starts syncing parts from A to B after some hours.
(4) When the rendering process is completed, the rest of the file is transferred to B.
(5) When I try to open the file on A, it works like a charm. When I try to open the file on B, I get the message that it is corrupted.
(6) I zipped the file and transferred it via sftp from A to B. Then, I can open the file on B.
I hope that this helps. I know how hart it is to find a bug like this! So good look, and thank you! ;)

**Comment by calmh** [comment]
Possibly blender changes blocks in the file without updating the modification time - syncthing doesn't detect this. If you update the modification time on the source after the render is complete, does it sync over and become non-corrupted?

**Comment by franz-benjamin** [comment]
Actually, I believe that you are right. When I simply copy the video file during the rendering process (both, copying and rendering, on the same computer - no syncthing involved), I cannot play the file. I get the same error message that I get when it is transferred by syncthing. This behaviour can be explained the way you did. This would mean that syncthing is in fact behaving as expected.

But: When I touch the file (i.e. when I update the modificatino time) after it has completely been generated, it is not synced correctly either. This could be due to the file size. Mh.

**Comment by calmh** [comment]
> But: When I touch the file (i.e. when I update the modificatino time) after it has completely been generated, it is not synced correctly either. This could be due to the file size. Mh.

That shouldn't happen though. It should end up identical on the other side compared to the source, or it's a bug. Does it not?

**Comment by franz-benjamin** [comment]
It does not for big files. On my system, it just ignores that I have updated the modification time, even after letting syncthing run for some hours + restart of the system.

**Comment by calmh** [comment]
Then there's something weird going on. At the very minimum, a touch should trigger a rescan and a copy of the new modification time to the other side. Can you reproduce this while running the sending side with "STTRACE=scanner syncthing" to show more information about what happens when it scans for changes?

**Comment by franz-benjamin** [comment]
Where do I have to type "STTRACE=scanner syncthing"? Thanks!

**Comment by MyPod** [comment]
In a terminal of the user that Syncthing usually runs as.

**Comment by calmh** [comment]
So, I found this one...

**Comment by franz-benjamin** [comment]
I am still testing but the problem did not occur again ... maybe it has something todo with the new version that I installed, or it's just Murphy. I will keep you updated when it happens again.

**Comment by Zillode** [comment]
It's a bug which is only triggered under certain circumstances. This is actually an important issue and a new Syncthing version needs to be released asap

**Comment by calmh** [comment]
Yeah. Basically it means some local changes won't be picked up; especially if there's just a few of them (such as you touching a single file).

**Comment by calmh** [comment]
Actually no, that wasn't the case. False alarm.

**Comment by calmh** [comment]
Not an actual issue, I think?
