### ISSUE TITLE
Sync aborts

### ISSUE THREAD

**Issue by MartijnLievaart** [syncthing/syncthing#1781]
I get 
[CEIBN] 23:01:01 INFO: Connection to RWPBWNT-AFSJATI-553F6NN-4MUEG3F-DW4PAT4-5TXSGJP-J5MPFOR-XRYD7AN closed: xdr read: bytes field exceeds size limit; 4156239770 > 32
 on one side and 
[RWPBW] 23:01:01 INFO: Established secure connection to CEIBNY2-MQH5BGZ-NRINJ7T-KYPDJFP-VQL6SSE-22OYRIZ-KUFFGCY-DC4J2A5 at 10.0.1.144:22000-10.0.3.3:48145
[RWPBW] 23:01:01 INFO: Connection to CEIBNY2-MQH5BGZ-NRINJ7T-KYPDJFP-VQL6SSE-22OYRIZ-KUFFGCY-DC4J2A5 closed: EOF
on the other.

This used to work, it suddenly stopped working.

v0.10.30 in three way sync, third leg is down.

**Comment by AudriusButkevicius** [comment]
Please search closed issues.

**Comment by MartijnLievaart** [comment]
OK, I searched the closed issues. Removing the index did not solve it and I don't run 0.11. Do you suggest I upgrade to 0.11?

**Comment by MyPod** [comment]
The issues appears when some machine run 0.10 and some 0.11. There's an
incompatibility in the protocol. Either upgrade every machine or disable
autoupdating

**Comment by MartijnLievaart** [comment]
Egg. Meet face. One was running 0.11. Sorry for the noise.

**Comment by AudriusButkevicius** [comment]
It's impossible it updated itself.major updates never happen automatically.
