### ISSUE TITLE
panic: upnpSvc cannot stop

### ISSUE THREAD

**Issue by HermanEldering** [syncthing/syncthing#1782]
The actual trace is VERY long, so I only copy-pasted some from the top. In the log I saw that during the run time there were many lines "unrecognized UPNP device of type ...". Like the log suggests the laptop woke from standby, the lines about the unrecognized upnp device were from before the sleep. After a manual restart it works fine.

Version is v0.11.2, Windows (64 bit).

```
<before sleep>
[...] 00:02:14 INFO: No UPnP device detected
[...] 00:02:16 INFO: Paused state detected, possibly woke up from standby. Restarting in 1m0s.
<snip>
[...] 00:03:17 INFO: Restarting
[...] 00:03:17 OK: Exiting
panic: upnpSvc cannot stop
goroutine 35449 [running]:
main.(*upnpSvc).Stop(0xc08207a780)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/upnpsvc.go:57 +0x6b
github.com/thejerf/suture.func·008()
```

**Comment by calmh** [comment]
Yeah, should be fixed.
