### ISSUE TITLE
Puller tries to chmod and fails

### ISSUE THREAD

**Issue by ddfreyne** [syncthing/syncthing#1783]
After upgrading to v0.11.2, I started seeing a lot of errors about failed chmods, like these:

```
May  9 09:03:52 bhakti syncthing: [5VLZB] INFO: Puller (folder "srv-http", dir "nanoc.ws/docs/api/Nanoc/Extra/Piper"): chmod /srv/http/nanoc.ws/docs/api/Nanoc/Extra/Piper: operation not permitted
May  9 09:03:52 bhakti syncthing: [5VLZB] INFO: Puller (folder "srv-http", file "nanoc.ws/docs/api/Nanoc/Filters/Markaby.html"): shortcut: chmod /srv/http/nanoc.ws/docs/api/Nanoc/Filters/Markaby.html: operation not permitted
May  9 09:03:52 bhakti syncthing: [5VLZB] INFO: Puller (folder "srv-http", file "nanoc.ws/docs/api/Nanoc/Filters/Less.html"): shortcut: chmod /srv/http/nanoc.ws/docs/api/Nanoc/Filters/Less.html: operation not permitted
May  9 09:03:52 bhakti syncthing: [5VLZB] INFO: Puller (folder "srv-http", file "nanoc.ws/docs/api/Nanoc/Filters/AsciiDoc.html"): shortcut: chmod /srv/http/nanoc.ws/docs/api/Nanoc/Filters/AsciiDoc.html: operation not permitted
May  9 09:03:52 bhakti syncthing: [5VLZB] INFO: Puller (folder "srv-http", file "nanoc.ws/the-road-to-nanoc-4-0/index.html"): shortcut: chmod /srv/http/nanoc.ws/the-road-to-nanoc-4-0/index.html: operation not permitted
```

Possibly related: #154, #146

**Comment by calmh** [comment]
What OS etc?

**Comment by AudriusButkevicius** [comment]
I don't understand how the issues you suggested are related. To me this sounda like a permission/ownership issue introduced by external means after the files have been synced. Did you verify that the files in question are owned by the same user as syncthing is running?

**Comment by ddfreyne** [comment]
Interestingly, the ownership of the files in `/srv/http` _did_ change. I’m not quite sure how that happened, since Syncthing is the only one managing this.

I’ll close the issue for now, since I think this probably an operator error. Thanks for looking in to this.

**Comment by calmh** [comment]
:+1: (Syncthing doesn't change ownership, so I'd go suspect your coworkers;)

**Comment by EnMod** [comment]
Huh...I had an error similar to this in my Windows/Linux setup where sync would not progress, could tell because on my Linux node there was a `Puller: final: (--file here--): dst create: operation not permitted` error spamming the log.  After changing the folder in question to ignore permission bits it synced properly.

**Comment by calmh** [comment]
Ignoring permissions means we don't call chmod, so that makes sense. But there is a different, non-Syncthing, root cause to why chmods are suddenly failing.

**Comment by EnMod** [comment]
Ah.  I mean, I did check all my permissions and all was well for everything to go smoothly...might have been that my owner permissions were not set correctly even though my group permissions were.  Thanks for the comment.

**Comment by calmh** [comment]
@EnMod Yeah sorry I didn't read your previous comment well enough and went by the context of the issue. No chmod in your case, it looks like the create failed because it didn't have access to the directory? But if fixed, then all good. :)
