### ISSUE TITLE
BlackBerry OS 10

### ISSUE THREAD

**Issue by Glaedr** [syncthing/syncthing#1785]
Can you provide SyncThing for BlackBerry OS 10.3.1 as well?
BlackBerry has great support for Android Apps, it would be cool if i could sync it with my PC ...
Moreover, BlackBerry is completly POSIX compilant, which would make it easy to port it, all you have to do is to write a simple QtQuick gui...

**Comment by calmh** [comment]
Possibly, I don't know. Try in https://github.com/syncthing/syncthing-android, unless Blackberry can run command line programs in which case trying one of the linux builds here might do the trick.

**Comment by bimawa** [comment]
syncthing for droid not work, can't create config file.  
syncthing for BB 10 must be like DropBox or Box on it OS. 
Maybe to plan this feature? i see in BB store ownCloud service, but not test it.

**Comment by calmh** [comment]
There are no plans for this feature. For this to happen it requires a passionate blackberry user to do the port, test it, and maintain it perpetually.

**Comment by bimawa** [comment]
@calmh tempting offer. Thanks for comment.
