### ISSUE TITLE
Too long file name prevents sync completion

### ISSUE THREAD

**Issue by rkfg** [syncthing/syncthing#1786]
Today I've upgraded the program to 11.2 and this happened (probably not upgrade-related):

```
[NKCV4] 15:42:20 INFO: Puller (folder "dina-dropbox", file "GREAT BRITAIN/Great Britain. Pictures/Great Britain - England, Wales/Достопримечательности Лондона « Экскурсионные туры в Лондон 2014 « Туры в Англию 2014 « Туристическая компания ВСЕВЕД ТРЕВЕЛ. Цены на отдых..html"): dst create: open /home/user/Dropbox/GREAT BRITAIN/Great Britain. Pictures/Great Britain - England, Wales/.syncthing.Достопримечательности Лондона « Экскурсионные туры в Лондон 2014 « Туры в Англию 2014 « Туристическая компания ВСЕВЕД ТРЕВЕЛ. Цены на отдых..html: file name too long
```

The file name is long enough but it doesn't violate any limitation of the source filesystem (ext4). However, on the target there's a prefix added, ".syncthing.", until the file is fully transferred. Its name becomes too long and the puller stalls. A relatively simple solution would be to replace the filename with a temporary guaranteed to be non-existent name that's mapped to the real name via a hashmap. Then after the file is synced it's renamed to the real name.

Another potential (though not solvable IMHO) problem is that filenames on Windows (NTFS) are limited by 255 characters while on Linux (most of filesystems) it's 255 bytes. For ASCII filenames it's ok but anything outside of it (cyrillics etc.) could be problematic as 255 2-byte chars are effectively 510 bytes.

**Comment by calmh** [comment]
Fair enough. We could use `.syncthing.$sha-of-actual-filename` or something that's guaranteed to be a short enough path component.

**Comment by MarkusTeufelberger** [comment]
Please don't use MD5 for anything user controllable (e.g. file names) that should be unique. How about SHA256?

**Comment by AudriusButkevicius** [comment]
This is for temporary files, using an integer would be good enough.

**Comment by MarkusTeufelberger** [comment]
I agree, so why use something that might collide depending on user input instead of just using a random number or a global counter?

**Comment by AudriusButkevicius** [comment]
We only download a handful of files at a time, how is `~syncthing~.DE4DB33F` going to collide?

**Comment by MarkusTeufelberger** [comment]
More likely than just using a random number and it even requires more computation too.

**Comment by dcarosone** [comment]
Extra computation: normally, sure, but not in this case since we already
know the hash :-)

**Comment by MarkusTeufelberger** [comment]
As far as I understand the patch, the hash is computed over the file name in lines 29 and 30. I really hope MD5 is not used anywhere else in the project too...

**Comment by calmh** [comment]
You guys are talking about nonissues. Stop it. :)

**Comment by rkfg** [comment]
Hmm, does this fix really work? For me the behavior is all the same and there's no hash in the filename. It's just .syncthing.orginal_filename.tmp. All my nodes are at v0.11.7.

**Comment by rkfg** [comment]
Ah, sorry, it was changed so that if the filename is shorter than 240 chars it uses the old behavior.
