### ISSUE TITLE
Logging could be more helpful

### ISSUE THREAD

**Issue by jpjp** [syncthing/syncthing#179]
Today I spent some time looking at why a node wasn't syncing with another node. The answer was that the node id was old, and this was silently ignored.
Then I had a problem where one node was an old version and didn't agree with the cluster config of the node it was connecting to.
And right now I am getting tons of warnings about "Connected to already connected node" and "Connected to myself - should not happen"

It seems like a lot of the messages in the web gui log at the moment show entries which are not very useful, but the useful entries are not shown.

Perhaps log levels would be useful.

(Yes I know I can go into trace mode! But I start without that, call me old fashioned)

**Comment by calmh** [comment]
Is there something concrete we can do to resolve this? (Pull requests on just the log strings are always welcome, if some things are unnecessarily cryptic and we haven't yet realized it ourselves...:)

**Comment by AudriusButkevicius** [comment]
discovery shouldn't use hex dumps to start with.

**Comment by merlink01** [comment]
Why not generally logging to files per syncfolder.

It could be nice to have a "download_log" button for a folder to see why it's not making progress for example.
Also the debug levels could be configured in the Advanced Syncthing Settings.

I know there are other options available now (starting per parameters or journalctl) but they are not easy to use for beginners and not really confortable.
