### ISSUE TITLE
Syncthing dies when out of space in filesystem

### ISSUE THREAD

**Issue by tokudan** [syncthing/syncthing#1790]
Syncthing just died on me due to an out of space issue:
Mai 10 01:15:17 aerith syncthing[26253]: [V2IUA] INFO: Puller (folder "tmp", file "abc.iso"): dst write: write /Sync/tmp/.syncthing.abc.iso: no space left on device
Mai 10 01:15:20 aerith syncthing[26253]: panic: write /somewhere/.config/syncthing/index-v0.11.0.db/000077.log: no space left on device

OS: Linux-amd64 (debian jessie)

I would have preferred to see a meaningful message in the GUI instead of just the message that Syncthing is unavailable.
I guess the best solution would be to just disable the failing Folder with an error message in the GUI?

**Comment by Zillode** [comment]
I don't think there is a better thing to do than just exit as soon as possible... You should expect things to fail if you are running out of disk space (especially a synchronization application).
I also quickly checked for golang libraries to obtain the available disk space but it seems there exists no cross-platform compatible API yet.
A PR in this direction is welcome, but this is a `wontfix` I believe

**Comment by AudriusButkevicius** [comment]
Agree with Zillode.
 In this case it's the database library that panics, and I guess we have to respect the library developers decision in this case, as not having space to perform database writes is fatal.
