### ISSUE TITLE
panic and disconnect

### ISSUE THREAD

**Issue by dodekeract** [syncthing/syncthing#1797]
## What happened:
My syncthing suddenly appears to be offline. So I checked the logs. These logs told me it restarted due to a panic.

## Versions:
Ubuntu 14.04.2 LTS 64-bit
Syncthing v0.11.0 64-bit

## Logs:
https://gist.github.com/dodekeract/6038cf5018a8d1a83ec3

**Comment by calmh** [comment]
You're running an old version, compiled in an unsupported manner. You probably need to talk to whoever built the package for you, sorry.

**Comment by dodekeract** [comment]
I'm not sure if this is the right place to ask, but is there some better/official ppa for syncthing? I really don't like not using my package manager (apt-get) and having to update manually.

**Comment by calmh** [comment]
Syncthing updates itself automatically is you use the release build from github. But no, no PPA yet, maybe some day we'll put together something official.

**Comment by calmh** [comment]
There are official packages now: http://apt.syncthing.net/

**Comment by dodekeract** [comment]
Thank you so much for your hard work on this amazing project. <3
