### ISSUE TITLE
Transmission direction not correct for both sides

### ISSUE THREAD

**Issue by klorydryk** [syncthing/syncthing#1798]
On the emittor, localhost "send" (this is correct), but receiver send at the same speed (which is incorrect). And on the receiver, it receive (this is correct), and the emitter receive at the same speed (which is incorrect) !
Wrong direction somewhere !
Emitter : ![screenshot_2015-05-11-22-56-51](https://cloud.githubusercontent.com/assets/1232047/7575037/25069a6a-f832-11e4-8e8d-6993b553a0e9.png)
Receiver : ![capture d ecran_2015-05-11_22-54-36](https://cloud.githubusercontent.com/assets/1232047/7574992/c714ca58-f831-11e4-8e04-d4b4304ca92b.png)

**Comment by calmh** [comment]
All rates are from the perspective of the device you are looking at. The rates for the local device (the one at the top) is the sum of the rates to/from the other devices.
