### ISSUE TITLE
Global Announcement after Disabling Option

### ISSUE THREAD

**Issue by alexkoay** [syncthing/syncthing#1799]
I've already disabled the option to perform Global Discovery but I found this in the logfile regardless:

    2015/05/12 11:37:52.091414 client_udp.go:126: DEBUG: discover udp4://announce.syncthing.net:22026: broadcast: Sending self announcement to 194.126.249.5:22026
    2015/05/12 11:37:52.486454 client_udp.go:106: DEBUG: discover udp6://announce-v6.syncthing.net:22026: broadcast resolve: GetAddrInfoW: No such host is known.; trying again in 1m0s

Does this still make connections back to the global server even though I've explicitly disabled it?
Running on v0.11.3

**Comment by calmh** [comment]
There may be a bug here. Do you maybe have UPnP enabled and an actual UPnP router available?

**Comment by calmh** [comment]
Pretty sure that's the problem.

**Comment by alexkoay** [comment]
Looks to be it.
I do have UPnP enabled.
Thanks for the quick reply.
