### ISSUE TITLE
Panic fatal error on system resume from suspend

### ISSUE THREAD

**Issue by cdmatter** [syncthing/syncthing#1809]
I have had issues with syncthing failing to restart after resuming my laptop from suspend.  I am running Ubuntu 15.04 with the 3.19.0-16 kernel with the latest 0.11.3 version of syncthing.  I do not run into this issue on my other Ubuntu machines which I do not suspend.  I also had this problem in later versions of 0.10 (it was something like v0.10.20+).  The browser GUI states "Syncthing seems to be down, or there is a problem with your Internet connection. Retrying…" and when I check my terminal, I get the following message:

[monitor] 10:19:39 INFO: Starting syncthing
unexpected fault address 0xffffffffffffffec
fatal error: fault
[monitor] 10:19:39 WARNING: Panic detected, writing to "/home/matthew/.config/syncthing/panic-20150514-101939.log"
[monitor] 10:19:39 WARNING: Please create an issue at https://github.com/syncthing/syncthing/issues/ with the panic log attached
[monitor] 10:19:39 INFO: Syncthing exited: exit status 2
[monitor] 10:19:40 WARNING: 4 restarts in 4.090650751s; not retrying further

and when I check the log, this is what is says:

...
Panic at 2015-05-14T10:19:39-04:00
fatal error: fault
[signal 0xb code=0x1 addr=0xffffffffffffffec pc=0x5b7067]

goroutine 1 [running]:
runtime.gothrow(0xa47990, 0x5)
	/usr/local/go/src/runtime/panic.go:503 +0x8e fp=0xc2080e63e0 sp=0xc2080e63c8
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:29 +0x265 fp=0xc2080e6430 sp=0xc2080e63e0
github.com/thejerf/suture.New(0xa4cf90, 0x4, 0xb882e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:194 +0x97 fp=0xc2080e6490 sp=0xc2080e6430
main.syncthingMain()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:429 +0xad fp=0xc2080e77a8 sp=0xc2080e6490
main.main()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:378 +0x21cc fp=0xc2080e7f98 sp=0xc2080e77a8
runtime.main()
	/usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc2080e7fe0 sp=0xc2080e7f98
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080e7fe8 sp=0xc2080e7fe0

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [runnable]:
text/template/parse.lexText(0xc208084000, 0xb88a78)
	/usr/local/go/src/text/template/parse/lex.go:228 +0x37b
text/template/parse.(*lexer).run(0xc208084000)
	/usr/local/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
	/usr/local/go/src/text/template/parse/lex.go:191 +0x1ac

goroutine 7 [runnable]:
main.trackCPUUsage()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:20
created by main.init·2
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x25

Thanks for your help!

**Comment by AudriusButkevicius** [comment]
Are you sure this is the whole panic log?

**Comment by cdmatter** [comment]
There were 4 logs listed after my last resume as synthing tried to restart several times.  The one listed above was the most recent one.  Below are the output of those first 3 log files in chronological order.

1st Log File
...
Panic at 2015-05-14T10:19:35-04:00
fatal error: fault
[signal 0xb code=0x1 addr=0xffffffffffffffec pc=0x5b7067]

goroutine 1 [running]:
runtime.gothrow(0xa47990, 0x5)
	/usr/local/go/src/runtime/panic.go:503 +0x8e fp=0xc2080ee3e0 sp=0xc2080ee3c8
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:29 +0x265 fp=0xc2080ee430 sp=0xc2080ee3e0
github.com/thejerf/suture.New(0xa4cf90, 0x4, 0xb882e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:194 +0x97 fp=0xc2080ee490 sp=0xc2080ee430
main.syncthingMain()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:429 +0xad fp=0xc2080ef7a8 sp=0xc2080ee490
main.main()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:378 +0x21cc fp=0xc2080eff98 sp=0xc2080ef7a8
runtime.main()
	/usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc2080effe0 sp=0xc2080eff98
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080effe8 sp=0xc2080effe0

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [runnable]:
text/template/parse.lexText(0xc208076000, 0xb88a78)
	/usr/local/go/src/text/template/parse/lex.go:228 +0x37b
text/template/parse.(*lexer).run(0xc208076000)
	/usr/local/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
	/usr/local/go/src/text/template/parse/lex.go:191 +0x1ac

goroutine 7 [runnable]:
main.trackCPUUsage()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:20
created by main.init·2
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x25



2nd Log File
...
Panic at 2015-05-14T10:19:37-04:00
fatal error: fault
[signal 0xb code=0x1 addr=0xffffffffffffffec pc=0x5b7067]

goroutine 1 [running]:
runtime.gothrow(0xa47990, 0x5)
	/usr/local/go/src/runtime/panic.go:503 +0x8e fp=0xc2080e43e0 sp=0xc2080e43c8
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:29 +0x265 fp=0xc2080e4430 sp=0xc2080e43e0
github.com/thejerf/suture.New(0xa4cf90, 0x4, 0xb882e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:194 +0x97 fp=0xc2080e4490 sp=0xc2080e4430
main.syncthingMain()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:429 +0xad fp=0xc2080e57a8 sp=0xc2080e4490
main.main()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:378 +0x21cc fp=0xc2080e5f98 sp=0xc2080e57a8
runtime.main()
	/usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc2080e5fe0 sp=0xc2080e5f98
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080e5fe8 sp=0xc2080e5fe0

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [runnable]:
text/template/parse.lexText(0xc20806e000, 0xb88a78)
	/usr/local/go/src/text/template/parse/lex.go:228 +0x37b
text/template/parse.(*lexer).run(0xc20806e000)
	/usr/local/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
	/usr/local/go/src/text/template/parse/lex.go:191 +0x1ac

goroutine 7 [runnable]:
main.trackCPUUsage()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:20
created by main.init·2
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x25


3rd Log File
...
Panic at 2015-05-14T10:19:38-04:00
fatal error: fault
[signal 0xb code=0x1 addr=0xffffffffffffffec pc=0x5b7067]

goroutine 1 [running]:
runtime.gothrow(0xa47990, 0x5)
	/usr/local/go/src/runtime/panic.go:503 +0x8e fp=0xc2080dc3e0 sp=0xc2080dc3c8
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:29 +0x265 fp=0xc2080dc430 sp=0xc2080dc3e0
github.com/thejerf/suture.New(0xa4cf90, 0x4, 0xb882e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:194 +0x97 fp=0xc2080dc490 sp=0xc2080dc430
main.syncthingMain()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:429 +0xad fp=0xc2080dd7a8 sp=0xc2080dc490
main.main()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:378 +0x21cc fp=0xc2080ddf98 sp=0xc2080dd7a8
runtime.main()
	/usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc2080ddfe0 sp=0xc2080ddf98
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080ddfe8 sp=0xc2080ddfe0

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [runnable]:
text/template/parse.lexText(0xc20806e000, 0xb88a78)
	/usr/local/go/src/text/template/parse/lex.go:228 +0x37b
text/template/parse.(*lexer).run(0xc20806e000)
	/usr/local/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
	/usr/local/go/src/text/template/parse/lex.go:191 +0x1ac

goroutine 7 [runnable]:
main.trackCPUUsage()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:20
created by main.init·2
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x25

**Comment by AudriusButkevicius** [comment]
Please post the whole file, including tge beginning and not `...` as it matters

**Comment by cdmatter** [comment]
Sorry, maybe I am missing something but that is how each of the panic logs begin.  I selected all of the text in each file and pasted it here.  Is there anywhere else I should look?

**Comment by AudriusButkevicius** [comment]
I am basically after the log up to the point it crashes, which potentially has the version number, compiler type etc.

**Comment by calmh** [comment]
Looks like it crashes just at the top of syncthingMain(), so none of that output yet... Unclear to me why it would crash there though. Can you post a `syncthing -version` output? The really weird crashes usually seem to come accompanied with having been built with xgcc or so.

**Comment by cdmatter** [comment]
syncthing -version output:
syncthing v0.11.3 (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-05-10 12:59:12 UTC

**Comment by calmh** [comment]
Looks official enough. Then I have even less of clue what's going on. That's a SIGSEGV, which is usually bad stuff. Broken binary? Broken system?

**Comment by cdmatter** [comment]
Ok, so I have installed syncthing version 0.11.5 on another laptop, Xubuntu Core 15.04 with 3.19.0-18 kernel.  There are only a few applications installed (since this is Xubuntu Core) and currently syncthing is not syncing to any other devices.  So after a couple of suspend/resume cycles, I get the following message:

[XLN2O] 20:40:59 INFO: Paused state detected, possibly woke up from standby. Restarting in 1m0s.
[XLN2O] 20:41:59 INFO: Restarting
[XLN2O] 20:41:59 OK: Exiting
[monitor] 20:41:59 INFO: Syncthing exited: exit status 3
[monitor] 20:42:00 INFO: Starting syncthing
SIGILL: illegal instruction
PC=0x5b8003

goroutine 9 [running]:
github.com/thejerf/suture.(*Supervisor).Serve(0xc2080f6000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:391 +0x143 fp=0xc20801afd8 sp=0xc20801acb8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801afe0 sp=0xc20801afd8
created by github.com/thejerf/suture.(*Supervisor).ServeBackground
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:373 +0x32

goroutine 1 [chan send]:
github.com/thejerf/suture.(*Supervisor).ServeBackground(0xc2080f6000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:374 +0xb4
main.syncthingMain()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:430 +0xc3
main.main()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:378 +0x21cc

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan receive]:
main.trackCPUUsage()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0xec
created by main.init·2
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x25

rax     0x0
rbx     0xc20801adf0
rcx     0xc208001c20
rdx     0xb8ba88
rdi     0x46fbe0
rsi     0xe0a640
rbp     0xc20801afd8
rsp     0xc20801acb8
r8      0xb8cc90
r9      0xab24c0
r10     0x959f40
r11     0xa250e0
r12     0x9
r13     0x0
r14     0x2
r15     0x10
rip     0x5b8003
rflags  0x10202
cs      0x33
fs      0x0
gs      0x0
[monitor] 20:42:00 INFO: Syncthing exited: exit status 2
[monitor] 20:42:01 INFO: Starting syncthing
SIGILL: illegal instruction
PC=0x5b8003

goroutine 8 [running]:
github.com/thejerf/suture.(*Supervisor).Serve(0xc2080f6000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:391 +0x143 fp=0xc20801afd8 sp=0xc20801acb8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801afe0 sp=0xc20801afd8
created by github.com/thejerf/suture.(*Supervisor).ServeBackground
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:373 +0x32

goroutine 1 [chan send]:
github.com/thejerf/suture.(*Supervisor).ServeBackground(0xc2080f6000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:374 +0xb4
main.syncthingMain()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:430 +0xc3
main.main()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:378 +0x21cc

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 9 [runnable]:
runtime.timerproc()
	/usr/local/go/src/runtime/time.go:151
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [chan receive]:
main.trackCPUUsage()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0xec
created by main.init·2
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x25

rax     0x0
rbx     0xc20801adf0
rcx     0xc2080e8360
rdx     0xb8ba88
rdi     0x46fbe0
rsi     0xe0a640
rbp     0xc20801afd8
rsp     0xc20801acb8
r8      0x1c73a
r9      0x8
r10     0x8
r11     0x872360
r12     0x9
r13     0x0
r14     0x2
r15     0x10
rip     0x5b8003
rflags  0x10202
cs      0x33
fs      0x0
gs      0x0
[monitor] 20:42:01 INFO: Syncthing exited: exit status 2
[monitor] 20:42:02 INFO: Starting syncthing
SIGILL: illegal instruction
PC=0x5b8003

goroutine 8 [running]:
github.com/thejerf/suture.(*Supervisor).Serve(0xc2080ea000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:391 +0x143 fp=0xc20801afd8 sp=0xc20801acb8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801afe0 sp=0xc20801afd8
created by github.com/thejerf/suture.(*Supervisor).ServeBackground
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:373 +0x32

goroutine 1 [chan send]:
github.com/thejerf/suture.(*Supervisor).ServeBackground(0xc2080ea000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:374 +0xb4
main.syncthingMain()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:430 +0xc3
main.main()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:378 +0x21cc

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 9 [runnable]:
runtime.timerproc()
	/usr/local/go/src/runtime/time.go:151
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [chan receive]:
main.trackCPUUsage()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0xec
created by main.init·2
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x25

rax     0x0
rbx     0xc20801adf0
rcx     0xc2080ec000
rdx     0xb8ba88
rdi     0x46fbe0
rsi     0xe0a640
rbp     0xc20801afd8
rsp     0xc20801acb8
r8      0x62ce4
r9      0x8
r10     0x8
r11     0x872360
r12     0x9
r13     0x0
r14     0x2
r15     0x10
rip     0x5b8003
rflags  0x10202
cs      0x33
fs      0x0
gs      0x0
[monitor] 20:42:02 INFO: Syncthing exited: exit status 2
[monitor] 20:42:03 INFO: Starting syncthing
SIGILL: illegal instruction
PC=0x5b8003

goroutine 8 [running]:
github.com/thejerf/suture.(*Supervisor).Serve(0xc2080e6000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:391 +0x143 fp=0xc2080177d8 sp=0xc2080174b8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080177e0 sp=0xc2080177d8
created by github.com/thejerf/suture.(*Supervisor).ServeBackground
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:373 +0x32

goroutine 1 [chan send]:
github.com/thejerf/suture.(*Supervisor).ServeBackground(0xc2080e6000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:374 +0xb4
main.syncthingMain()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:430 +0xc3
main.main()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:378 +0x21cc

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 9 [runnable]:
runtime.timerproc()
	/usr/local/go/src/runtime/time.go:151
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [chan receive]:
main.trackCPUUsage()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0xec
created by main.init·2
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x25

rax     0x0
rbx     0xc2080175f0
rcx     0xc208062480
rdx     0xb8ba88
rdi     0x46fd00
rsi     0xe0a640
rbp     0xc2080177d8
rsp     0xc2080174b8
r8      0x12
r9      0xc207ffff87
r10     0x8
r11     0x872360
r12     0x9
r13     0x0
r14     0x2
r15     0x10
rip     0x5b8003
rflags  0x10202
cs      0x33
fs      0x0
gs      0x0
[monitor] 20:42:03 INFO: Syncthing exited: exit status 2
[monitor] 20:42:04 WARNING: 4 restarts in 4.205108059s; not retrying further

**Comment by AudriusButkevicius** [comment]
This is some really freaky stuff. Can you verify that it runs fine in general?
Also, the version line would help.

**Comment by cdmatter** [comment]
As far as I can tell, yes everything seems to work.  I will look into this a little more to verify.

Is this the version line you were looking for:

[XLN2O] 22:01:23 INFO: syncthing v0.11.5 (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-05-15 08:46:47 UTC

Another interesting thing is that I cannot restart syncthing right away after this error otherwise it just gives me the same output.  However, if I wait a while or after a couple of failed restarts it will start again just fine.

**Comment by calmh** [comment]
TBH this smells like hardware error to me. Memory issues?

**Comment by AudriusButkevicius** [comment]
Nothing changes in the binary, so waiting a minute for the binary to suddenly have valid instructions makes no sense. This has to be some side effect of some dodgy hardware or caching software.
