### ISSUE TITLE
FATAL: Upgrade: couldn't fetch release information

### ISSUE THREAD

**Issue by paulhargreaves** [syncthing/syncthing#1812]
$ syncthing -version
syncthing v0.11.1 (go1.4.2 freebsd-amd64 default) unknown-user@syncthing-builder 2015-04-26 11:10:14 UTC
$ syncthing -upgrade-check
21:53:22 FATAL: Upgrade: couldn't fetch release information
$ uname -a
FreeBSD syncthing 10.1-RELEASE FreeBSD 10.1-RELEASE #0 r274401: Tue Nov 11 21:02:49 UTC 2014     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
$ 

Rest of my machines have auto-updated to v0.11.3, this one hasn't for some reason. Any steps to diagnose?

**Comment by calmh** [comment]
`STTRACE=upgrade syncthing -upgrade-check`

This is usually because the system CA certificates can't be found, or something similar.

**Comment by paulhargreaves** [comment]
$ STTRACE=upgrade syncthing -upgrade-check
2015/05/17 21:56:23.005837 main.go:339: FATAL: Upgrade: couldn't fetch release information
$ ping syncthing.com
PING syncthing.com (72.52.4.119): 56 data bytes
64 bytes from 72.52.4.119: icmp_seq=0 ttl=243 time=112.066 ms

**Comment by Zillode** [comment]
`curl https://api.github.com/repos/syncthing/syncthing/releases/latest`
`wget https://api.github.com/repos/syncthing/syncthing/releases/assets/583521`
?

**Comment by paulhargreaves** [comment]
$ wget https://api.github.com/repos/syncthing/syncthing/releases/assets/583521
--2015-05-18 06:49:34--  https://api.github.com/repos/syncthing/syncthing/releases/assets/583521
Resolving api.github.com (api.github.com)... 192.30.252.139
Connecting to api.github.com (api.github.com)|192.30.252.139|:443... connected.
ERROR: cannot verify api.github.com's certificate, issued by 'CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US':
  Unable to locally verify the issuer's authority.
To connect to api.github.com insecurely, use `--no-check-certificate'.
$ 

 sudo pkg install ca_root_nss
Password:
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	ca_root_nss: 3.19
[snip]

$ wget https://api.github.com/repos/syncthing/syncthing/releases/assets/583521
--2015-05-18 06:53:54--  https://api.github.com/repos/syncthing/syncthing/releases/assets/583521
Resolving api.github.com (api.github.com)... 192.30.252.138
Connecting to api.github.com (api.github.com)|192.30.252.138|:443... connected.
ERROR: cannot verify api.github.com's certificate, issued by 'CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US':
[snip]

but...

$ syncthing --upgrade-check
06:55:31 INFO: Upgrade available (current "v0.11.1" < latest "v0.11.5")
$ 

Hurrah. So, might be worth a) adding more info to the error message and b) adding something to the installation instructions for BSD users that they need to manually install that package

**Comment by Zillode** [comment]
:+1:
