### ISSUE TITLE
Size mismatch when installing debian package

### ISSUE THREAD

**Issue by ChrisPurves** [syncthing/syncthing#1813]
Attempted to install debian package today and received the following error:

    Get: 1 http://apt.syncthing.net/ syncthing/release syncthing i386 0.11.4 [3,075 kB]
    Fetched 3,079 kB in 2s (1,128 kB/s)
    E: Failed to fetch http://apt.syncthing.net/dists/syncthing/release/binary-386/syncthing_0.11.4_i386.deb: Size mismatch

**Comment by jpjp** [comment]
Did you try an apt-get update?

**Comment by ChrisPurves** [comment]
Well...that did it.  I had performed an update seconds before trying to install.  Bad timing, I guess.
