### ISSUE TITLE
windows symlinks not works, syncthing not see changes in it

### ISSUE THREAD

**Issue by MasterDimmy** [syncthing/syncthing#1815]
i've done:

mklink /d music1 D:\music
mklink /d music2 E:\music
mklink /d pics C:\pics

got folders

C:\sym>dir /r
15.05.2015  17:37    <SYMLINKD>     music1 [M:\music1]
15.05.2015  17:38    <SYMLINKD>     music2 [L:\music]
15.05.2015  17:38    <SYMLINKD>     pics [E:\pics]

C:\sym used as sync folder in syncthing, but it is not ever been synchronized, also changes in syminks are ignored.

Windows symlinks are very usefull with syncthing. Please fix it.

**Comment by AudriusButkevicius** [comment]
You need to run syncthing as administrator for it to be able to create symlinks, and symlinks are already synced (links not content).

**Comment by MasterDimmy** [comment]
>>run syncthing as administrator for it to be able to create symlink
approve. it works, thanks.

but error still exist.
in other PC1 appear symlink "music1" which also targets to M:\music1.
In PC1 there is no drive M, and others.

Like common behavior, syncthing should work with symlink like a folder in other pc.
So, after sync, in PC1 should be created folder "music1" with files, not symlink.

Or, maybe, it'l be better to add a configurable value to the whole syncing folder "convert symlinks to folder on other devices". So, it can support multiple drives, etc.

**Comment by AudriusButkevicius** [comment]
You can use junctions which will get treated as folders. The configurable part has already been requested.

**Comment by calmh** [comment]
That #1776 otherwise.

**Comment by MasterDimmy** [comment]
unhopefully, 
>>You can use junctions which will get treated as folders. 

Is not working, you can check it yourself.

i've created junction , and  got in many tries following:
[OO5VG] 19:25:55 WARNING: Puller: final: creating symlink: invalid argument

Please check it, there is no way to do this. Also in #1095 you wrote that junctions not working in Go, so the problem is still exists.

Syncthing runs as an adminstrator (windows7) account.
