### ISSUE TITLE
Creating a new folder on C:\ fails (Windows 7)

### ISSUE THREAD

**Issue by towlie** [syncthing/syncthing#1822]
I added a new folder with the following path: "C:\test"
Syncthing fails to create this folder with the following output: 
```INFO: Skipping folder dsad scan due to folder error: mkdir \\?: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch. ```

Which means: wrong syntax for filename, directory or volume label.

Creating subfolders works.

**Comment by kozec** [comment]
Did you really put that space there, between \\ and t? Because that really is invalid filename on Windows.

**Comment by chucic** [comment]
I tested with and without that space and both produced same error.

**Comment by towlie** [comment]
Oh. I did it without the space of course.

**Comment by calmh** [comment]
So `osutil.MkdirAll` then... \o/
