### ISSUE TITLE
panic: read /Users/.…./Library/Application Support/Syncthing/index-v0.11.0.db/005451.ldb: input/output error

### ISSUE THREAD

**Issue by DWomack** [syncthing/syncthing#1828]
Any suggestions to recover?

panic: read /Users/.…./Library/Application Support/Syncthing/index-v0.11.0.db/005451.ldb: input/output error

goroutine 1 [running]:
github.com/syncthing/syncthing/internal/db.ldbCheckGlobals(0xc20800c6e0, 0xc20e53e950, 0xa, 0x10)
	/go/src/github.com/syncthing/syncthing/internal/db/leveldb.go:1041 +0xd53
github.com/syncthing/syncthing/internal/db.NewFileSet(0xc208108814, 0xa, 0xc20800c6e0, 0xc20f52e2d0)
	/go/src/github.com/syncthing/syncthing/internal/db/set.go:55 +0x285
github.com/syncthing/syncthing/internal/model.(*Model).AddFolder(0xc20e24b800, 0xc208108814, 0xa, 0xc20810f820, 0x1a, 0xc2080bfd80, 0x2, 0x4, 0x0, 0x3c, ...)
	/go/src/github.com/syncthing/syncthing/internal/model/model.go:1107 +0x19e
main.syncthingMain()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:607 +0x20c4
main.main()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:378 +0x21cc

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan receive]:
main.trackCPUUsage()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0xec
created by main.init·2
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x25

goroutine 9 [select]:
github.com/thejerf/suture.(*Supervisor).Serve(0xc2080f8000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:411 +0xf64
created by github.com/thejerf/suture.(*Supervisor).ServeBackground
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:373 +0x32

goroutine 10 [chan receive]:
github.com/syncthing/syncthing/internal/config.(*Wrapper).Serve(0xc2080e2200)
	/go/src/github.com/syncthing/syncthing/internal/config/wrapper.go:84 +0x75
created by github.com/syncthing/syncthing/internal/config.Wrap
	/go/src/github.com/syncthing/syncthing/internal/config/wrapper.go:59 +0x28d

goroutine 12 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc2080b20e0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x21e
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236 +0x24c

goroutine 13 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc20800c6e0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:120 +0x48c
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:126 +0x849

goroutine 14 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc20800c6e0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_state.go:73 +0x14a
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:127 +0x863

goroutine 15 [syscall]:
syscall.Syscall(0x5f, 0x14, 0x0, 0x0, 0x1a0d81, 0x69ab, 0x0)
	/usr/local/go/src/syscall/asm_darwin_amd64.s:20 +0x5
syscall.Fsync(0x14, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:543 +0x55
os.(*File).Sync(0xc211239108, 0x0, 0x0)
	/usr/local/go/src/os/file_posix.go:129 +0x6a
github.com/syndtr/goleveldb/leveldb/storage.fileWrap.Sync(0xc211239108, 0xc2112564e0, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:347 +0x3a
github.com/syndtr/goleveldb/leveldb/storage.(*fileWrap).Sync(0xc21127a380, 0x0, 0x0)
	<autogenerated>:46 +0xb1
github.com/syndtr/goleveldb/leveldb.(*tWriter).finish(0xc2111e77a0, 0x0, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table.go:504 +0x106
github.com/syndtr/goleveldb/leveldb.(*tableCompactionBuilder).flush(0xc20f664000, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:420 +0x55
github.com/syndtr/goleveldb/leveldb.(*tableCompactionBuilder).run(0xc20f664000, 0xc20f62a0d0, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:481 +0x986
github.com/syndtr/goleveldb/leveldb.(*DB).compactionTransact(0xc20800c6e0, 0x688070, 0xb, 0xbc5888, 0xc20f664000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:215 +0x277
github.com/syndtr/goleveldb/leveldb.(*DB).tableCompaction(0xc20800c6e0, 0xc20f638000, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:596 +0x10d4
github.com/syndtr/goleveldb/leveldb.(*DB).tableAutoCompaction(0xc20800c6e0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:641 +0x50
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc20800c6e0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:833 +0x3a0
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:130 +0x8a7

goroutine 16 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc20800c6e0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:759 +0x283
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:131 +0x8c1

goroutine 17 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc20800c6e0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x197
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:132 +0x8db

goroutine 33 [select]:
github.com/syncthing/syncthing/internal/events.(*Subscription).Poll(0xc2090d9460, 0xdf8475800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:178 +0x356
github.com/syncthing/syncthing/internal/events.(*BufferedSubscription).pollingLoop(0xc20802f400)
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:215 +0x48
created by github.com/syncthing/syncthing/internal/events.NewBufferedSubscription
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:209 +0x292

goroutine 23 [select]:
github.com/syncthing/syncthing/internal/model.(*ProgressEmitter).Serve(0xc20e512640)
	/go/src/github.com/syncthing/syncthing/internal/model/progressemitter.go:49 +0x8f2
created by github.com/syncthing/syncthing/internal/model.NewModel
	/go/src/github.com/syncthing/syncthing/internal/model/model.go:125 +0x93c

goroutine 24 [IO wait]:
net.(*pollDesc).Wait(0xc20f518300, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20f518300, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20f5182a0, 0x0, 0xb15dd8, 0xc209ae4090)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20e309620, 0xc209168040, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20e309620, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
main.(*DowngradingListener).Accept(0xc20f525720, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/tls.go:99 +0x85
net/http.(*Server).Serve(0xc2080c0060, 0xbc5510, 0xc20f525720, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1728 +0x92
main.(*apiSvc).Serve(0xc20e52c080)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:215 +0x190a
github.com/thejerf/suture.func·007()
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:516 +0xf6
created by github.com/thejerf/suture.(*Supervisor).runService
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:519 +0x11e

goroutine 34 [select]:
github.com/thejerf/suture.(*Supervisor).Serve(0xc20e47c900)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:411 +0xf64
created by github.com/thejerf/suture.(*Supervisor).ServeBackground
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:373 +0x32

goroutine 35 [select]:
main.(*folderSummarySvc).listenForUpdates(0xc2080c0e40)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/summarysvc.go:67 +0x5c6
main.*folderSummarySvc.(main.listenForUpdates)·fm()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/summarysvc.go:47 +0x27
main.serviceFunc.Serve(0xc20e521f70)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/summarysvc.go:202 +0x20
github.com/thejerf/suture.func·007()
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:516 +0xf6
created by github.com/thejerf/suture.(*Supervisor).runService
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:519 +0x11e

goroutine 36 [select]:
main.(*folderSummarySvc).calculateSummaries(0xc2080c0e40)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/summarysvc.go:115 +0x2e4
main.*folderSummarySvc.(main.calculateSummaries)·fm()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/summarysvc.go:48 +0x27
main.serviceFunc.Serve(0xc20e521f80)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/summarysvc.go:202 +0x20
github.com/thejerf/suture.func·007()
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:516 +0xf6
created by github.com/thejerf/suture.(*Supervisor).runService
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:519 +0x11e

**Comment by AudriusButkevicius** [comment]
Out of disk space?

**Comment by DWomack** [comment]
No.  There is 200 gig free on the boot drive, and 300 gig on the data drive where the folders being shared are located.


Dennis

**Comment by Zillode** [comment]
check `sudo dmesg` for errors

**Comment by calmh** [comment]
Yeah. I/O error is returned by the OS here. That indicates a problem...
