### ISSUE TITLE
Upgrade failure on BSD (and probably Linux) as non-root user if not directory owner 

### ISSUE THREAD

**Issue by paulhargreaves** [syncthing/syncthing#1829]
$ ls -la /usr/local/bin/syncthing
-rwxr-xr-x   1 paulhargreaves  wheel  11160528 Apr 28 15:15 syncthing
$

$ ls -la /usr/local/
total 64
drwxr-xr-x  13 root  wheel    512 May 18 06:53 .
drwxr-xr-x  16 root  wheel    512 Apr 21 20:24 ..
drwxr-xr-x   2 root  wheel   4096 May 18 06:59 bin
[snip]

So root owns /usr/local/bin, I own the syncthing file.

$ pwd
/home/paulhargreaves
$ 

I'm in my home, so stuff can be written here.

$ syncthing --upgrade
06:58:44 INFO: Upgrade available (current "v0.11.1" < latest "v0.11.5")
06:58:46 FATAL: Upgrade: open /usr/local/bin/syncthing975553546: permission denied
$

Makes sense because I can't create new files in /usr/local/bin, but if the syncthing97xxx file had been created somewhere else, the copied over the top, it would have succeeded. E.g cp "${HOME}/syncthing97xxxxx" "/usr/local/bin/syncthing" would work.

So, 
$ sudo syncthing --upgrade
06:59:14 INFO: Upgrade available (current "v0.11.1" < latest "v0.11.5")
06:59:21 OK: Upgraded to "v0.11.5"
$ ls -la /usr/local/bin/syncthing
-rwxr-xr-x  1 root  wheel  11293072 May 18 06:59 /usr/local/bin/syncthing
$ 

Can upgrade as root but now the file is owned by root, and that isn't how I started. Trivial to chown back, but unless I checked I wouldn't have realised.

I'll probably move syncthing out of /usr/local/bin and into my home folder so that future upgrade 'just work' but seems like the upgrade code could easily handle this type of use case.

**Comment by AudriusButkevicius** [comment]
We cannot move files across different filesystems, which /tmp usually is, hence there is no good place to put the file in.

**Comment by jpjp** [comment]
This is quite a convoluted example though: I'd expect to put binaries you manage under ~/bin/ or  under /opt/somethingYouHaveWriteAccessTo.

**Comment by calmh** [comment]
This is a setup thing, not something syncthing can control. We don't want to (and on some systems *can't*) overwrite the running executable; we must upgrade it with a rename.
