### ISSUE TITLE
No UPnP device detected ...

### ISSUE THREAD

**Issue by tjldtf** [syncthing/syncthing#1832]
On Windows 7, with the latest syncthing I get "No UPnP device detected" and "INFO: Local discovery over IPv6 unavailable". The machines are in a local subnet now + therefore, I have a connection. Outside the local subnet the machines have no connection to each other. The Windows firewall of the machines are off. Any ideas what to change?

**Comment by AudriusButkevicius** [comment]
This is a known bug on Windows, and already has a PR pending.

**Comment by tjldtf** [comment]
I've found some pages on this. Can you please point me to the pending review your mention? Thank you.

**Comment by AudriusButkevicius** [comment]
https://github.com/syncthing/syncthing/pull/1826
