### ISSUE TITLE
Add dates to the timestamps

### ISSUE THREAD

**Issue by rkfg** [syncthing/syncthing#1833]
It's hard to guess when the particular error happened if the program was running for days:
![2015-05-18-211508_968x320_scrot](https://cloud.githubusercontent.com/assets/184066/7687033/fa39cf52-fda2-11e4-9a77-6cf15a3523b8.png)

What? Was it a day ago? Or two? I have no idea. If there's only one error it's even harder to guess. I suggest adding a day-month-year combination to all the timestamps in the logs, both console and web. Would be much easier to track if something is still broken or fixed itself a while ago.

**Comment by calmh** [comment]
Console is controlable with the -logflags option. Web is not, currently, so we could fix that (although I don't see it being worth configurability, just always showing `YYYY-MM-DD HH:MM:SS` seems fine.
