### ISSUE TITLE
Support escaping of slash character in all config fields

### ISSUE THREAD

**Issue by Nutomic** [syncthing/syncthing#1835]
The Java JSON API escapes all `/` characters as `\/`.

Syncthing fails to parse this: 
Posting a config containing
`"globalAnnounceServers":"udp4:\/\/194.126.249.5:22026, udp6:\/\/[2001:470:28:4d6::5]:22026` 
gives 
`[4VBPJ] 20:41:27 WARNING: decoding posted config: json: cannot unmarshal string into Go value of type []string`

[JSON spec](https://tools.ietf.org/html/rfc4627) (see strings section)
[stackoverflow](https://stackoverflow.com/questions/1580647/json-why-are-forward-slashes-escaped)

**Comment by calmh** [comment]
Yeah, looks like `\/` should be parsed as slash, but isn't. However, this is a property of the Go standard library, so not something we can fix (other than by fixing it there, which I'll actually look into). In the meantime, it's a wontfix unfortunately. There's also no need to escape slashes in JSON.

**Comment by calmh** [comment]
Actually no, that's not it at all. The global announce servers should be a list of strings: `["foo", "bar"]`. Backslashed slashes are handled correctly: http://play.golang.org/p/2NAIDbG1Pm.

**Comment by Nutomic** [comment]
Hm, maybe I have a bug in my formatting then.

Sorry to bother you :)
