### ISSUE TITLE
Build of syncthing failing on Linux

### ISSUE THREAD

**Issue by MStrecke** [syncthing/syncthing#1836]
I'm the guy who needs a statically linked version of syncthing for my diskstation. See issue #714 #642 #639 #567.

For this I've set up a virtual build machine... and there I build the new version from time to time mostly according to the steps mentioned [here](https://github.com/syncthing/syncthing/wiki/Building) and [here](http://tuxpool.blogspot.de/2014/10/updating-syncthing-on-dm1812-part-2.html).

However the build process failed:

    mike@buildmachine:~/src/github.com/syncthing/syncthing$ go run build.go 
    GOPATH is /home/mike
    GOPATH=/home/mike/src/github.com/syncthing/syncthing/Godeps/_workspace:/home/mike
    go install -v -ldflags -w -X main.Version v0.11.5 -X main.BuildStamp 1431679607 -X main.BuildUser unknown-user -X main.BuildHost buildmachine -X main.BuildEnv default ./cmd/...
    github.com/bkaradzic/go-lz4
    github.com/calmh/logger
    github.com/calmh/luhn
    github.com/calmh/xdr
    golang.org/x/text/transform
    ...
    github.com/syncthing/syncthing/internal/scanner
    github.com/syncthing/syncthing/cmd/stindex
    github.com/syncthing/syncthing/internal/stats
    github.com/syncthing/syncthing/cmd/stfileinfo
    github.com/syncthing/syncthing/internal/model
    github.com/syncthing/syncthing/cmd/syncthing
    - No go vet, no vetting. Try "go get -u golang.org/x/tools/cmd/vet".
    - No go vet, no vetting. Try "go get -u golang.org/x/tools/cmd/vet".
    - No golint, not linting. Try "go get -u github.com/golang/lint/golint".
    - No golint, not linting. Try "go get -u github.com/golang/lint/golint".

I was able to execute the recommended commands by:

    export GOPATH=/home/mike:/home/mike/src/github.com/syncthing/syncthing/Godeps/_workspace
    go get -u golang.org/x/tools/cmd/vet
    go get -u github.com/golang/lint/golint

Please note that the order of the folders in GOPATH is reversed (compared to the one build.go is using),

I presume those error messages shouldn't occur in the first place.

Cheers

Michael

**Comment by Zillode** [comment]
I was under the impression that those are just warnings?

**Comment by MStrecke** [comment]
Yes - you're right. Sorry.

The last times it compiled perfectly without any "warnings".
Couldn't they at least write "warning" in front of it instead of scaring the unsuspecting admin :-)

Perhaps a small note in the build instructions .... thanks
