### ISSUE TITLE
Cannot delete directories if it contains ignored files

### ISSUE THREAD

**Issue by TiZ-EX1** [syncthing/syncthing#1837]
Whenever I delete a folder from a repo, just, like, get rid of it completely, I'll get a puller error on other peers. It complains about being unable to delete directories because they're not empty.

    [X6IU7] 20:54:17 INFO: Puller (folder "School", dir "CIT383/Labs/mcpheronw1-lab17/ruby-1.8.6/lib/soap"): delete: remove /home/trent/School/CIT383/Labs/mcpheronw1-lab17/ruby-1.8.6/lib/soap: directory not empty
    [X6IU7] 20:54:17 INFO: Puller (folder "School", dir "CIT383/Labs/mcpheronw1-lab17/ruby-1.8.6/lib"): delete: remove /home/trent/School/CIT383/Labs/mcpheronw1-lab17/ruby-1.8.6/lib: directory not empty
    [X6IU7] 20:54:17 INFO: Puller (folder "School", dir "CIT383/Labs/mcpheronw1-lab17/ruby-1.8.6"): delete: remove /home/trent/School/CIT383/Labs/mcpheronw1-lab17/ruby-1.8.6: directory not empty
    [X6IU7] 20:54:17 INFO: Puller (folder "School", dir "CIT383/Labs/mcpheronw1-lab17"): delete: remove /home/trent/School/CIT383/Labs/mcpheronw1-lab17: directory not empty
    [X6IU7] 20:54:17 INFO: Puller (folder "School", dir "CIT383/Labs"): delete: remove /home/trent/School/CIT383/Labs: directory not empty
    [X6IU7] 20:54:17 INFO: Puller (folder "School", dir "CIT383"): delete: remove /home/trent/School/CIT383: directory not empty

Eventually, the error resolves itself for no discernible reason, but it's kind of annoying to see it happen at all.

Running Syncthing 0.11.3 through Syncthing-GTK 0.7.0.2 on Linux 64-bit.

**Comment by AudriusButkevicius** [comment]
Do you have a set of steps to reliably reproduce this? Thanks

**Comment by uok** [comment]
I had the same problem - seems that Syncthing tries to delete the folder(s) before the file(s) inside. this causes linux to get confused

**Comment by calmh** [comment]
We try to take care to delete everything inside a directory before the directory itself, so that *shouldn't* happen. If it can be reproduced we can surely fix the problem, though...

**Comment by Zillode** [comment]
Maybe the inotify implementation of Syncthing-GTK propagates changes to directories first in case of a recursive removal.
@kozec ?

**Comment by Zillode** [comment]
sorry, doesn't make sense as Syncthing will scan the top folder and discover that it's gone...

**Comment by mjmvisser** [comment]
I'm not sure if it's the same issue, but starting with 0.11.13 (or possibly 12, I think we skipped over that one) I'm seeing shares marked as "Out of Sync", with messages like this in the log:

    [RBSEU] 10:12:47 INFO: Puller (folder "ep11", dir "vfx11_0040"): delete: remove /prod/projects/413_quake/ducks/anima/ep11/vfx11_0040: directory not empty
    [RBSEU] 10:12:48 INFO: Puller (folder "ep11", dir "vfx11_0040/Audio"): delete: remove /prod/projects/413_quake/ducks/anima/ep11/vfx11_0040/Audio: directory not empty
    [RBSEU] 10:12:48 INFO: Puller (folder "ep11", dir "vfx11_0040"): delete: remove /prod/projects/413_quake/ducks/anima/ep11/vfx11_0040: directory not empty
    [RBSEU] 10:12:48 INFO: Puller (folder "ep11", dir "vfx11_0040/Audio"): delete: remove /prod/projects/413_quake/ducks/anima/ep11/vfx11_0040/Audio: directory not empty
    [RBSEU] 10:12:48 INFO: Puller (folder "ep11", dir "vfx11_0040"): delete: remove /prod/projects/413_quake/ducks/anima/ep11/vfx11_0040: directory not empty
    [RBSEU] 10:12:48 INFO: Puller (folder "ep11", dir "vfx11_0040/Audio"): delete: remove /prod/projects/413_quake/ducks/anima/ep11/vfx11_0040/Audio: directory not empty
    [RBSEU] 10:12:48 INFO: Puller (folder "ep11", dir "vfx11_0040"): delete: remove /prod/projects/413_quake/ducks/anima/ep11/vfx11_0040: directory not empty
    [RBSEU] 10:12:48 INFO: Puller (folder "ep11", dir "vfx11_0040/Audio"): delete: remove /prod/projects/413_quake/ducks/anima/ep11/vfx11_0040/Audio: directory not empty
    [RBSEU] 10:12:48 INFO: Puller (folder "ep11", dir "vfx11_0040"): delete: remove /prod/projects/413_quake/ducks/anima/ep11/vfx11_0040: directory not empty
    [RBSEU] 10:12:48 INFO: Folder "ep11" isn't making progress. Pausing puller for 1m0s.

The directories only contain files created by syncthing (I can tell by ownership). The shares are all bi-directional (i.e. not Folder Master on either side), there are only two peers, using Simple Versioning and Ignore Permissions).

**Comment by assigerasiate** [comment]
i have the same problem.

**Comment by AudriusButkevicius** [comment]
Dup #1362
