### ISSUE TITLE
Syncthing for backup

### ISSUE THREAD

**Issue by skandragon** [syncthing/syncthing#1840]
It would be very nice to have a way to specify a set of directories which appear to be a single unit when transmitted to a remote.  This would make it quite easy to use Syncthing to back up a server to a NAS:

* Set up a local directory to "virtual directory" mapping.
* Tell SyncThing this is the master copy.

Example of a mapping:

/etc -> etc
/home -> home
/u0/data -> u0-data

To the cluster, this would look like the sync published had three directories, "etc", "home", and "u0-data"

**Comment by kozec** [comment]
mount -o bind may help here.

**Comment by AudriusButkevicius** [comment]
Yeah, bind mounts solve this.

**Comment by canton7** [comment]
Symlink support, when someone gets around to writing it (and claiming the bounty) will also solve this, I believe

**Comment by AudriusButkevicius** [comment]
True. There is already a ticket for that I believe.
