### ISSUE TITLE
Conflict resolution outcome should be based on mtime and only then on id

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#1848]
To make it more likely that the right file wins I guess?
Any problems with this?

**Comment by Zillode** [comment]
:thumbsup:

**Comment by calmh** [comment]
No problems. The sorting here just needs to take the mtime into account:

https://github.com/syncthing/syncthing/blob/master/internal/db/leveldb.go#L494

**Comment by lfam** [comment]
Are you talking about the vector clock ID?

If so, wouldn't this proposal negate the advantage of the vector clock almost entirely? I thought the point of vector clocks was to establish a logical history so that we don't have to rely on the unreliable system clocks of our computers.

Sorry if I've misinterpreted the discussion...

**Comment by AudriusButkevicius** [comment]
Well vector clocks allow detecting the conflict, as in - two clocks moved concurrently, but the fact that two clocks ticked by 1 version does not imply that either of them is newer, it just implies that both of them changed.

The decision on which one is the original and which one is the conflict is based on the first 64 bits of device ID (so that the whole cluster has a consensus on which file wins).
But this could also be based on mtime of the file two files in conflict, and then based on the device ID given the mtimes are exactly the same.

**Comment by calmh** [comment]
Yes. This is only to decide which file wins when there is a conflict.

**Comment by lfam** [comment]
Right, I definitely misinterpreted AudriusButkevicius's original post. Carry on!

**Comment by djtm** [comment]
:+1: 

Does that mean there's (possibly also) an issue currently with people use the ext4 mount option noatime (instead of relatime)? -> if mtime is updated, but atime isn't?

**Comment by calmh** [comment]
No. atime is never used for anything useful (at least not by syncthing) and is pretty much always better disabled. :)
