### ISSUE TITLE
Malformed md5 checksum file for the syncthing binary in syncthing-linux-amd64-v0.11.5

### ISSUE THREAD

**Issue by aliassmoller** [syncthing/syncthing#1849]
Hi

Do not know if it is on purpose, but the "syncthing" binary name is missing in the md5 sum file. This result in a malformed error from md5sum when calling "md5sum -c syncthing.md5". The name of the binary must be added to avoid md5sum the error.

This may be applicable for other md5 sum files

**Comment by calmh** [comment]
The md5 file included in the package is primarily for consumption by the automatic upgrades for simple checks against accidental corruption. For humans, the md5sum.txt.asc and sha1sum.txt.asc files are recommended, as they are also PGP signed.

**Comment by aliassmoller** [comment]
One more use of the syncthing.md5 file could be similar corruption validation during docker build compilation. The guidelines in https://syncthing.net/security.html must of course be used to validate the binary tar.gz file.

I am only advocating for well formed md5 checksum file as it allows for md5sum to be used without reinventing stuff :)

**Comment by calmh** [comment]
Yeah... Well, anyway there is no standard format as far as I'm aware. It depends on what utility you use and what comes with the OS.

```bash
jb@syno:~ $ uname
Darwin
jb@syno:~ $ md5 bin/syncthing
MD5 (bin/syncthing) = dd7e573049f47c5e7defec45653d10b2

jb@zlogin4:~ $ uname
SunOS
jb@zlogin4:~ $ openssl dgst -md5 bin/syncthing
MD5(bin/syncthing)= e17e4aba1cf96aae2da814ab72644129
```

and so on
