### ISSUE TITLE
Syncing 101%

### ISSUE THREAD

**Issue by rocky1138** [syncthing/syncthing#1850]
![syncthing-101-percent](https://cloud.githubusercontent.com/assets/573315/7759963/697aa182-ffe4-11e4-95fc-bf7750fb248f.png)

I checked my Raspberry Pi today after leaving it on all night with my other machine to sync some files. My second machine is a Windows laptop.

Is it okay to go above 100% syncing? It seems counter-intuitive.

**Comment by calmh** [comment]
Mmmyeah, rather. Probably similar to the issue about negative percentages - a timing issue. Those errors at the top aren't awesome though. Is this FAT or NTFS mounted on Linux? You may need to set the `ignorePermissions` attribute in `config.xml`.

**Comment by rocky1138** [comment]
It's listed as vfat in my fstab. I set the umask to 000 so that it was read/writeable by all the users.

It's a 500GB external USB 3.0 drive. How could that be FAT? I thought FAT had some crazy low partition size limitation...

I will take a look at ignorePermissions. Thanks!

**Comment by calmh** [comment]
vfat is fat, for these purposes (i.e. it doesn't track permissions, from a Unix point of view).

**Comment by rocky1138** [comment]
Well without the umask stuff all the files were owned by root and set to
rx..r..r so syncthing was grumpy it couldn't remove files.

**Comment by calmh** [comment]
#1759
