### ISSUE TITLE
Broken symlink causing issues across OSes

### ISSUE THREAD

**Issue by mastodon** [syncthing/syncthing#1851]
Situation.

Linux: symlink file to a non-existent directory
Windows: ?? (don't know the situation)
Mac: regular file with contents of the symlink pointer

This situation causes my Linux to overheat. It shows it wants to download the symlinked file under Linux and on the console there is repeat of:

    [JJZK5] 16:17:46 INFO: Puller (folder "xx", file "BROKENSYMLINKFILE"): shortcut: chmod: chmod BROKENSYMLINKFILE: no such file or directory

Then

    Pausing puller for 1m0s.

**Comment by calmh** [comment]
Can you post the contents of `curl 'http://localhost:8384/rest/db/file?folder=xx&file=BROKENSYMLINKFILE'` (using the actual correct values for folder id and file name)? Do you know how you ended up in this situation?

(Also - overheat...?)

**Comment by mastodon** [comment]
Sadly I managed to delete the file as the fan was doing its nasty. But I could recreate the file so we are set here.

Curl gives me:

    {"availability":[],"global": {"flags":"0","localVersion":0,"modified":"1970-01-01T03:00:00+03:00","name":"","numBlocks":0,"size":0,"version":[]},"local":{"flags":"0","localVersion":0,"modified":"1970-01-01T03:00:00+03:00","name":"","numBlocks":0,"size":0,"version":[]}}

And ls -la gives me:

    lrwxrwxrwx 1 irve irve   28 mai   22  2012 BROKENSYMLINKFILE -> /non/existent

As of the situation: the file was initially untarred from an archive its date being in 2013. Quite many Syncthing versions back. Then there have been three computers on and offline with it. Other computers have it with the same 1970 epoch start date.

To recreate the file on Linux I stopped syncthing, then used:

    ln -s /non/existent BROKENSYMLINKFILE # whatever was in the symlink
    touch -h -d '3 years ago' BROKENSYMLINKFILE

Then re-ran Syncthing.

On Mac the content of the file (according to the example; my real dir is a bit different) with cat is:

    /non/existent 

And the timestamp is 0 as the file is basically from 1 Jan 1970.

**Comment by AudriusButkevicius** [comment]
You must have made a typo, as rest call returns an empty file implying that it didn't find it.
Did you allow it to finish rescanning first?

**Comment by mastodon** [comment]
Thanks! I used the full path in dir.

    {"availability":["XX1","XX2"],"global":{"flags":"0666","localVersion":242911,"modified":"1970-01-01T03:00:00+03:00","name":"FILENAME","numBlocks":1,"size":28,"version":["1318301936741524753:1","5364542102470381494:3","17707741320395967288:2"]},"local":{"flags":"0700666","localVersion":375884,"modified":"1970-01-01T03:00:00+03:00","name":"FILENAME","numBlocks":1,"size":28,"version":["1318301936741524753:1","5364542102470381494:3","17707741320395967288:1"]}}

**Comment by calmh** [comment]
There is weirdness here as the global version does not have the symlink bit set, so we think it's a regular file and mistreat it...

**Comment by mastodon** [comment]
The issue here is that for some reason this causes high CPU load. Can we do anything about it or shall we consider it an unicorn event and close the issue here and now?

**Comment by Zillode** [comment]
Could you document the way how we can recreate this problem?
