### ISSUE TITLE
panic: leveldb/table: corruption on data-block (pos=136879): checksum mismatch, want=0xae84a12e got=0xf52cc938 [file=003491.ldb]

### ISSUE THREAD

**Issue by treker** [syncthing/syncthing#1853]
Create the issue by the suggestion of output

Can't attach the log file here. Please check it from

https://www.dropbox.com/s/08l8ogf3dm4x0zc/panic-20150523-135141.log?dl=0
https://www.dropbox.com/s/c1yfm6t1gi148le/panic-20150523-135154.log?dl=0
https://www.dropbox.com/s/af45082ch44xe41/panic-20150523-135208.log?dl=0

**Comment by dodekeract** [comment]
I have the same issue in 0.11.7 on Ubuntu. I tried deleting the index, but that only fixed the problem for about 2 hours or sth.
http://pastebin.com/wYHTesE3

**Comment by calmh** [comment]
Any other issues on your boxes? It seems a common factor in many of these have actually been hardware errors (bad memory, dying disks...).

**Comment by treker** [comment]
No. it keep happening every time I start it. I have to delete the db to
make it work.

**Comment by dodekeract** [comment]
No, my system is completely fine overall. The only notable thing about it is, that I recently lost my syncthing configuration and had to re-add the folders again. As I assume(d) that syncthing will recognize the files as already synced I left them in the newly-added folders. This worked out quite well, but then syncthing suddenly crashs after hours of indexing.

**Comment by calmh** [comment]
Gotcha. It's a tricky one though, because we've never been able to reproduce it under healthy circumstances so far...

**Comment by dodekeract** [comment]
Well. Is there any way how I can help you reproduce it? Perhaps sending more logs, configs, databases?

**Comment by AudriusButkevicius** [comment]
Can you check your hard disk for smart errors and the kernel log (given your on Unix) for errors first.
Also, are you using some magical caching software/file system which causes writes to be reordered?

**Comment by calmh** [comment]
I honestly don't know. The "root cause" here is that the database layer gets something different back from the disk than it wrote (the checksum is different). We've ran database stress tests for days on various boxes without reproducing it, and I've never seen it myself with syncthing either. If this was a software bug, it should really have been reproduced by some of those tests even on good hardware. Multiple cases of this (by searching the forum and issue tracker) have been solved by people replacing disks or turning of dodgy acceleration software like Audrius mentions.

**Comment by dodekeract** [comment]
Couldn't do a memory test right now, because I can't shutdown that system atm, but here is the smart result for that drive. As I don't know anything about all I can really do is to paste the results:
http://pastebin.com/wxm5tgM8

Here is the kern.log: http://pastebin.com/VBhnF8D4

**Comment by calmh** [comment]
Drive looks fine. I doubt LVM is the issue as that's underneath the filesystem... Sorry, no idea.

**Comment by dodekeract** [comment]
Could this issue be fixed, by verifying the database, after it was saved, or does syncthing do this already?

**Comment by AudriusButkevicius** [comment]
Well that's exactly what happens I think, it performs some writes which updates the checksum, when it later performs a read the data is corrupt.

**Comment by dodekeract** [comment]
But if this is not a software bug, shouldn't it just re-write the corrupted parts?
Also: why does it read the re-written parts later, and not directly after writing so that it can re-write/re-hash again?

**Comment by AudriusButkevicius** [comment]
Well how do you recover something that is corrupt, once it has been corrupt?

The reason it doesn't read what has been written is that it would be a performance penalty, and it tries to rely on hardware to do it's job.

It only discovers the corruption much later (in terms of operations, not necessarily time), when it tries to read something, and the checksum doesn't match.

You can try running:
https://github.com/syndtr/goleveldb/tree/master/manualtest/dbstress
to see what happens, or the general test suite available with the library.

**Comment by dodekeract** [comment]
I assumed that syncthing would know, what it writes at the time it writes it. Therefore it should be able to verify it? Is that wrong?

**Comment by dodekeract** [comment]
Does that stresstest end automatically? Or how do I get the results?

**Comment by dodekeract** [comment]
Okay: the stresstest seems to be succeeding. I ran it for about 1.5 hours. http://pastebin.com/Gf84qg7j

**Comment by AudriusButkevicius** [comment]
Perhaps we need to set some options to replicate syncthings configuration better.

**Comment by AudriusButkevicius** [comment]
It seems the only option out of the 3 syncthing uses is openfilescachecap, which is already set to 500.

**Comment by davidak** [comment]
i also got this error now with syncthing v0.11.16  (64-Bit) on elementary OS Freya (Ubuntu 14.04 based) with LVM and encrypted home folder.

```
panic: leveldb/table: corruption on table-footer (pos=2128428): bad magic number [file=006963.ldb]
```

http://davidak.basecom.de/paste/?1d600f71914f9c12#KGEx2J0GqLh17pLQJvzKxYF8o/IlK5yQ5d4kNqE+FZo=

**Comment by Zillode** [comment]
@treker @dodekeract and @davidak please try our bolt db backend, details [here](https://forum.syncthing.net/t/beta-test-of-syncthing-build-with-alternate-database-backend-boltdb/3070).
Vote +1 for bolt if this solves your problem

**Comment by calmh** [comment]
Startup related panics should be handled better by 8783688, corruption of existing data on disk has only ever been either unexplained or related to provable hardware errors.

**Comment by Getron** [comment]
I have the same panics, and it do the full snycthing client to go offline on my FreeNAS.

Can we not just say, if the block error, or checksum error is with the database, to just put out this particular db, and to not shut down the full client, and all other sync are offline then?

To say, if db error happen, then, put this db (just this one, with errors, no matter what for errors are) offline, or this share to put offline. Maybe, to show an error somwhere on GUI, on this particular db corrupted share, that this share is offline, because of db error?

I think, this would be much better than putting the full Syncthing offline, while, db panic.

**Comment by AudriusButkevicius** [comment]
It's a single db for everything. If you are getting panics, you storage /RAM is about to die.

**Comment by Getron** [comment]
I have 5240 db files on syncthing index db folder, and just one of them, particular one, from an folder with pics, it make the client to crash and shutdown., every time, just this one, from this pics folder. I don't think, the hardware going to die. all othe stuff it works perfectly, and there are no smart errors on hard drives. 

The hard drives, are the WD red, 10 of them, in a ZFS2 FreeNAS.

Memory test is ok to.

I think, maybe is a prticular one photo maybe, or one file, who has errors on it (but i have millions of fotos...) and this one, do the crash.

Unfortunatly, syncthing does not say, what file is corrupt, just that db is corrupt. And this db comes from a pics folder.

Therefore, the idea, to shutdown the just one particular share, where the file corruption or error happend.

**Comment by AudriusButkevicius** [comment]
The fact that you have a million files in the index directory does not  imply a million databases. It's still a single database, made out of multiple files. If one of the files is corrupt, the whole database is corrupt. This can only be apparent when we actually try reading that file, and that file might hold information for multiple shares.

Again, its nothing todo with your files, its the database that is corrupt, not the files.

**Comment by kadeeaguila** [comment]
has anyone found a fix for consistently getting

CRIT [06-15|06:51:41] Failed to store last header's hash err="leveldb/table: corruption on data-block (pos=1577926): checksum mismatch, want=0xc6b28462 got=0xe8e09878 [file=035058.ldb]"

how do we fix this? i keep doing removedb adn start over

i'm on MACOSX SAMSUNG EVO850

**Comment by AudriusButkevicius** [comment]
It's a 2 year old post, please don't bring zombies back to life.

Use the forum, the answer is most likely behind the search feature.
