### ISSUE TITLE
Stop going through all the files and indexing them after re-adding a folder with existing content

### ISSUE THREAD

**Issue by THPubs** [syncthing/syncthing#1865]
If im correct in BTsync, if we re-add a folder which have been synced before (Removed from syncing or in a new OS (while dual booting)) it won't re-scan the whole folder. It saves those data inside the folder in .sync. Im not sure but i think that's what's happening.

In Syncthing, it re-scans everything and a large folder can take hours to complete indexing! Is there a way to change this behavior? It will be better right?

**Comment by calmh** [comment]
Why would we assume the files in a folder you added now are the same as the files in some other folder you removed a while back?

**Comment by THPubs** [comment]
Hehe a tricky question... This is what happened... I had a folder added to sync. I had to re-format my machine (The synced folder is in a different partition). Now when added, back, it goes through all the files. Sorry I don't know much but is it possible to maintain an index database inside the folder itself and just compare those two files when adding?

**Comment by calmh** [comment]
If you restored the files from backup, you could also restore the Syncthing config folder (containing the database)?

**Comment by THPubs** [comment]
Ah can you please let me know where's the config folder? One thing... is it better to put the database from that folder to the directory we sync? Then even if we loose that sync folder, if we have the folder we need to sync, it have the database :-)

**Comment by calmh** [comment]
`syncthing --help` will print the path.

The folder may be read only, so having the database in there may not work.

**Comment by THPubs** [comment]
Ah now I see. Great! No issues!
