### ISSUE TITLE
Add a link to download last release on update failure

### ISSUE THREAD

**Issue by BenjaminSchubert** [syncthing/syncthing#1867]
On some systems, syncthing might run as user but can be stored in a root owned directory, therefore the automatic upgrade would not work. Having a link to automatically download the latest release or to the github page of releases would be very practical !

**Comment by Zillode** [comment]
Please read the FAQ: https://github.com/syncthing/syncthing/wiki/FAQ#how-do-i-update-syncthing
and https://github.com/syncthing/syncthing/wiki/FAQ#where-do-i-find-the-latest-release

**Comment by BenjaminSchubert** [comment]
@Zillode thanks, I did know this. What I meant is, the auto-update of syncthing could be replaced by a button to download the latest release in the case where the auto-upgrade would not work (due to permissions). That would allow a much quicker update for people not wanting to let syncthing auto-update itself !

**Comment by Zillode** [comment]
Where would you click on? There is a link on the website if you want to download it yourself. We cannot do this for you if you don't give Syncthing the permission to update itself. You could also kill syncthing, run `syncthing -upgrade` as root and start syncthing again with a regular user account.

**Comment by BenjaminSchubert** [comment]
I meant, instead of the button "upgrade syncthing", a download button if rights are not correct.

But if this is not a desired feature I totally understand.

**Comment by Zillode** [comment]
Now I understand, thanks.
It is however not too easy to implement because we don't know the upgrade is going to fail before you click the button. If demand is big we could reopen this issue, a PR is always welcome of course.

**Comment by BenjaminSchubert** [comment]
Ok, I see no problem, thanks to you !

Sadly I don't know go, but a check if write rights on linux are set or not would allow this (don't know for the rest).

Otherwise, when the download fails, adding a link to the message ? that would make the process quicker !
