### ISSUE TITLE
Linux: logfile param error

### ISSUE THREAD

**Issue by eduncan911** [syncthing/syncthing#1870]
Tried search a good bit, through open and closed.  Didn't see this reported anywhere.  I'm new to syncthing.

```
$ syncthing -home="/home/eric/.syncthing/" -logfile="/home/eric/.syncthing/log.txt"
flag provided but not defined: -logfile
```

Directory exists.

I've tried a number of combinations.  

-logfile="/home/eric/.syncthing"
-logfile="/home/eric/.syncthing/"
-logfile="/home/eric/.syncthing/log"
-logfile="~/.syncthing"
-logfile="~/.syncthing/"
-logfile="~/.syncthing/log"
-logfile="~/.syncthing/log.txt"

All give the same error.

On the positive side, the latest Windows version works fine.  :)

```
$ syncthing -version
syncthing v0.11.5 (go1.4.2 linux-amd64 default) builduser@jara 2015-05-15 08:46:47 UTC

$ cat /proc/version 
Linux version 4.0.4-2-ARCH (builduser@foutrelis) (gcc version 5.1.0 (GCC) ) #1 SMP PREEMPT Fri May 22 03:05:23 UTC 2015
```

**Comment by calmh** [comment]
`-logfile` is a Windows only flag. On other OS:es, use something more powerful, or just `syncthing > somelogfile` which is essentially equivalent to that flag on Windows.

**Comment by eduncan911** [comment]
Ah, maybe a comment in the docs, or even the -h help, that it's for windows only.  :)

**Comment by calmh** [comment]
Yeah, could be clearer. It's not in the `-h` output though, except on Windows. ;)

**Comment by eduncan911** [comment]
Well I'll be... You're right.  Serves me right for setting it up on my
Windows server first, before moving onto my linux clients.  :)
