### ISSUE TITLE
GUI improvement - Devices in folder

### ISSUE THREAD

**Issue by Mayccoll** [syncthing/syncthing#1877]
Hi,
I made a couple of screenshot to illustrate my idea.
The goal is to know on what devices the folder is shared without open the accordion.

![sync](https://cloud.githubusercontent.com/assets/2009698/7818944/43874926-03a4-11e5-8514-34f5ff1d0516.png)

![sync2](https://cloud.githubusercontent.com/assets/2009698/7818945/43976bc6-03a4-11e5-801f-df8c636708bc.png)

**Comment by dcarosone** [comment]
Syncthing gtk does something similar, with a roll over highlight. When you
hover over a host or folder, the host and other folders it shares are
highlighted.

**Comment by Eddy2909** [comment]
what do you think about: https://forum.syncthing.net/t/my-thoughts-for-a-gui-2-0/3002

**Comment by lkwg82** [comment]
nice. But my gut says it comes to a dashboard with simply to many information.

**Comment by uok** [comment]
agreed (more devices, more confetti)

**Comment by AudriusButkevicius** [comment]
I am closing this as this proposal does not work.for bigger setups.
