### ISSUE TITLE
Web GUI updates too fast

### ISSUE THREAD

**Issue by jangrewe** [syncthing/syncthing#1881]
I have Syncthing running on a couple of devices, one of them is an rather weak ARM-based NAS. The webinterface seems to periodically call the API to update its data, but if the API doesn't answer fast enough, the load on the system increases with the next call and slows down the system even further.

Would it be possible to add some kind of queueing, so that API calls are only made if the previous call has finished? Thanks!

**Comment by calmh** [comment]
This should not be the case. What calls are you thinking of specifically?

**Comment by jangrewe** [comment]
Here's an example, the list below goes on and on...
![screenshot](https://cloud.githubusercontent.com/assets/126137/7837879/1c8612e4-048a-11e5-8441-5b99e40cc099.png)

**Comment by calmh** [comment]
Yeah, those calls are quick and do not put any load on the device. However there is an initial call per folder (when the gui is loaded) which is fairly expensive, and it looks from the "Unknown" status that these have not completed yet. In this case it seems you just need to have patience, unfortunately. It's known that the performance here isn't great...
