### ISSUE TITLE
Add python-syncthing to Community Contributions: REST API Bindings

### ISSUE THREAD

**Issue by blakev** [syncthing/syncthing#1886]
Hey, I was wondering if you'd add my Python REST bindings to the contributions page.

The other Python package under the listing is considerably outdated. [python-syncthing](https://github.com/blakev/python-syncthing) will automatically update the REST bindings to the newest spec via the documentation, keeping the bindings up to date with current and future Syncthing releases.

https://github.com/syncthing/syncthing/wiki/Community-Contributions

https://github.com/blakev/python-syncthing

https://pypi.python.org/pypi/syncthing

**Comment by AudriusButkevicius** [comment]
The wiki is freely editable.

**Comment by calmh** [comment]
It's not, actually :) But the change can be done at https://github.com/syncthing/docs - I'll do this one, thanks.
