### ISSUE TITLE
WARNING: Panic detected

### ISSUE THREAD

**Issue by raseldasel** [syncthing/syncthing#1887]
I've got a "WARNING: Panic detected" followed by automatic restart. 

Logging from console:
...
unexpected fault address 0x7f3300000011
fatal error: fault
[monitor] 20:13:39 WARNING: Panic detected, writing to "/home/weise/.config/syncthing/panic-20150528-201339.log"
[monitor] 20:13:39 WARNING: Please create an issue at https://github.com/syncthing/syncthing/issues/ with the panic log attached
[monitor] 20:13:39 INFO: Syncthing exited: exit status 2
[monitor] 20:13:40 INFO: Starting syncthing

Logfile:
[L7VP5] 20:03:36 INFO: syncthing v0.11.0 (xgcc (Ubuntu 4.9.1-0ubuntu1) 4.9.1 linux-amd64 default) niklas@Niklas-Netbook 2015-04-26 13:15:08 UTC
[L7VP5] 20:03:36 INFO: My ID: L7VP5IZ-6DBGBDQ-OUY477H-CPNZ7LD-JWFNHMB-52G5GMV-AXS6CGQ-A4YDEAM
[L7VP5] 20:03:36 INFO: Starting web GUI on http://127.0.0.1:8080/
[L7VP5] 20:03:37 INFO: Starting local discovery announcements
[L7VP5] 20:03:37 OK: Ready to synchronize default (read-write)
[L7VP5] 20:03:37 OK: Ready to synchronize Dokumente-Privat (read-write)
[L7VP5] 20:03:37 INFO: Device 6PVUU4Q-QDYUSRK-D6TZ46G-4NK7Y2X-OZX5W6E-QKSQDHJ-NPUQT7G-6G4Z2QO is "Weise-MacBook-Air" at [dynamic]
[L7VP5] 20:03:37 INFO: Device L7VP5IZ-6DBGBDQ-OUY477H-CPNZ7LD-JWFNHMB-52G5GMV-AXS6CGQ-A4YDEAM is "Weise-Latitude-E6420" at [dynamic]
[L7VP5] 20:03:37 INFO: No automatic upgrades; STNOUPGRADE environment variable defined.
[L7VP5] 20:03:37 INFO: Starting usage reporting
...
[L7VP5] 20:03:37 INFO: Completed initial scan (rw) of folder default
[L7VP5] 20:03:38 INFO: Completed initial scan (rw) of folder Dokumente-Privat
Panic at 2015-05-28T20:13:39+02:00
fatal error: fault
[signal 0xb code=0x1 addr=0x7f3300000011]

goroutine 333 [running]:

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

	:0

goroutine 1 [chan receive]:
main.syncthingMain
	/build/buildd/syncthing-0.11.0/cmd/syncthing/main.go:639
main.main
	/build/buildd/syncthing-0.11.0/cmd/syncthing/main.go:368

goroutine 3 [syscall]:
	goroutine in C code; stack unavailable

goroutine 5 [chan receive]:
main.trackCPUUsage
	/build/buildd/syncthing-0.11.0/cmd/syncthing/gui_unix.go:24
created by __go_init_main
	/build/buildd/syncthing-0.11.0/cmd/syncthing/blockprof.go:7

goroutine 7 [chan receive]:
github.com_syncthing_syncthing_internal_config.Serve.pN54_github.com_syncthing_syncthing_internal_config.Wrapper
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/config/wrapper.go:79
created by github.com_syncthing_syncthing_internal_config.Load
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/config/wrapper.go:72

goroutine 8 [select]:
github.com_syndtr_goleveldb_leveldb_util.drain.pN51_github.com_syndtr_goleveldb_leveldb_util.BufferPool
	/build/buildd/syncthing-0.11.0/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205
created by github.com_syndtr_goleveldb_leveldb_util.NewBufferPool
	/build/buildd/syncthing-0.11.0/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236

goroutine 9 [select]:
github.com_syndtr_goleveldb_leveldb.compactionError.pN38_github.com_syndtr_goleveldb_leveldb.DB
	/build/buildd/syncthing-0.11.0/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:120
created by leveldb.openDB
	/build/buildd/syncthing-0.11.0/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:126

goroutine 10 [select]:
github.com_syndtr_goleveldb_leveldb.mpoolDrain.pN38_github.com_syndtr_goleveldb_leveldb.DB
	/build/buildd/syncthing-0.11.0/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_state.go:73
created by leveldb.openDB
	/build/buildd/syncthing-0.11.0/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:127

goroutine 11 [select]:
github.com_syndtr_goleveldb_leveldb.tCompaction.pN38_github.com_syndtr_goleveldb_leveldb.DB
	/build/buildd/syncthing-0.11.0/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:812
created by leveldb.openDB
	/build/buildd/syncthing-0.11.0/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:130

goroutine 12 [select]:
github.com_syndtr_goleveldb_leveldb.mCompaction.pN38_github.com_syndtr_goleveldb_leveldb.DB
	/build/buildd/syncthing-0.11.0/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:759
created by leveldb.openDB
	/build/buildd/syncthing-0.11.0/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:131

goroutine 13 [select]:
github.com_syndtr_goleveldb_leveldb.jWriter.pN38_github.com_syndtr_goleveldb_leveldb.DB
	/build/buildd/syncthing-0.11.0/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37
created by leveldb.openDB
	/build/buildd/syncthing-0.11.0/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:132

goroutine 14 [select]:
github.com_syncthing_syncthing_internal_model.Serve.pN61_github.com_syncthing_syncthing_internal_model.ProgressEmitter
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/model/progressemitter.go:48
created by github.com_syncthing_syncthing_internal_model.NewModel
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/model/model.go:118

goroutine 15 [select]:
github.com_syncthing_syncthing_internal_events.Poll.pN59_github.com_syncthing_syncthing_internal_events.Subscription
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/events/events.go:179
github.com_syncthing_syncthing_internal_events.pollingLoop.pN67_github.com_syncthing_syncthing_internal_events.BufferedSubscription
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/events/events.go:215
created by github.com_syncthing_syncthing_internal_events.NewBufferedSubscription
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/events/events.go:209

goroutine 16 [select]:
github.com_thejerf_suture.Serve.pN36_github.com_thejerf_suture.Supervisor
	/build/buildd/syncthing-0.11.0/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:411
main.Serve.pN21_main.folderSummarySvc
	/build/buildd/syncthing-0.11.0/cmd/syncthing/summarysvc.go:41
created by main.startGUI
	/build/buildd/syncthing-0.11.0/cmd/syncthing/gui.go:192

goroutine 17 [IO wait]:
main.Accept.pN24_main.DowngradingListener
	/build/buildd/syncthing-0.11.0/cmd/syncthing/tls.go:99
main.$nested0
	/build/buildd/syncthing-0.11.0/cmd/syncthing/gui.go:195
created by main.startGUI
	/build/buildd/syncthing-0.11.0/cmd/syncthing/gui.go:194

goroutine 18 [select]:
main.listenForUpdates.pN21_main.folderSummarySvc
	/build/buildd/syncthing-0.11.0/cmd/syncthing/summarysvc.go:61
main.Serve.N16_main.serviceFunc
	/build/buildd/syncthing-0.11.0/cmd/syncthing/summarysvc.go:193
suture.$nested5
	/build/buildd/syncthing-0.11.0/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:516
created by github.com_thejerf_suture.Serve.pN36_github.com_thejerf_suture.Supervisor
	/build/buildd/syncthing-0.11.0/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:405

goroutine 19 [select]:
main.calculateSummaries.pN21_main.folderSummarySvc
	/build/buildd/syncthing-0.11.0/cmd/syncthing/summarysvc.go:109
main.Serve.N16_main.serviceFunc
	/build/buildd/syncthing-0.11.0/cmd/syncthing/summarysvc.go:193
suture.$nested5
	/build/buildd/syncthing-0.11.0/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:516
created by github.com_thejerf_suture.Serve.pN36_github.com_thejerf_suture.Supervisor
	/build/buildd/syncthing-0.11.0/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:405

goroutine 20 [select]:
github.com_syncthing_syncthing_internal_ignore.clean.pN54_github.com_syncthing_syncthing_internal_ignore.Matcher
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:153
created by github.com_syncthing_syncthing_internal_ignore.New
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:53

goroutine 22 [select]:
github.com_syncthing_syncthing_internal_ignore.clean.pN54_github.com_syncthing_syncthing_internal_ignore.Matcher
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:153
created by github.com_syncthing_syncthing_internal_ignore.New
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:53

goroutine 23 [IO wait]:
beacon.genericReader
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/beacon/beacon.go:24
created by github.com_syncthing_syncthing_internal_beacon.NewBroadcast
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/beacon/broadcast.go:30

goroutine 24 [chan receive]:
github.com_syncthing_syncthing_internal_beacon.writer.pN56_github.com_syncthing_syncthing_internal_beacon.Broadcast
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/beacon/broadcast.go:46
created by github.com_syncthing_syncthing_internal_beacon.NewBroadcast
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/beacon/broadcast.go:31

goroutine 25 [chan receive]:
github.com_syncthing_syncthing_internal_beacon.Recv.pN56_github.com_syncthing_syncthing_internal_beacon.Broadcast
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/beacon/broadcast.go:41
github.com_syncthing_syncthing_internal_discover.recvAnnouncements.pN59_github.com_syncthing_syncthing_internal_discover.Discoverer
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/discover/discover.go:334
created by github.com_syncthing_syncthing_internal_discover.startLocalIPv4Broadcasts.pN59_github.com_syncthing_syncthing_internal_discover.Discoverer
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/discover/discover.go:96

goroutine 26 [IO wait]:
beacon.genericReader
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/beacon/beacon.go:24
created by github.com_syncthing_syncthing_internal_beacon.NewMulticast
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/beacon/multicast.go:40

goroutine 27 [chan receive]:
github.com_syncthing_syncthing_internal_beacon.writer.pN56_github.com_syncthing_syncthing_internal_beacon.Multicast
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/beacon/multicast.go:58
created by github.com_syncthing_syncthing_internal_beacon.NewMulticast
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/beacon/multicast.go:41

goroutine 28 [chan receive]:
github.com_syncthing_syncthing_internal_beacon.Recv.pN56_github.com_syncthing_syncthing_internal_beacon.Multicast
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/beacon/multicast.go:51
github.com_syncthing_syncthing_internal_discover.recvAnnouncements.pN59_github.com_syncthing_syncthing_internal_discover.Discoverer
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/discover/discover.go:334
created by github.com_syncthing_syncthing_internal_discover.startLocalIPv6Multicasts.pN59_github.com_syncthing_syncthing_internal_discover.Discoverer
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/discover/discover.go:124

goroutine 29 [IO wait]:
beacon.genericReader
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/beacon/beacon.go:24
created by github.com_syncthing_syncthing_internal_beacon.NewMulticast
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/beacon/multicast.go:40

goroutine 30 [chan receive]:
github.com_syncthing_syncthing_internal_beacon.writer.pN56_github.com_syncthing_syncthing_internal_beacon.Multicast
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/beacon/multicast.go:58
created by github.com_syncthing_syncthing_internal_beacon.NewMulticast
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/beacon/multicast.go:41

goroutine 31 [chan receive]:
github.com_syncthing_syncthing_internal_beacon.Recv.pN56_github.com_syncthing_syncthing_internal_beacon.Multicast
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/beacon/multicast.go:51
github.com_syncthing_syncthing_internal_discover.recvAnnouncements.pN59_github.com_syncthing_syncthing_internal_discover.Discoverer
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/discover/discover.go:334
created by github.com_syncthing_syncthing_internal_discover.startLocalIPv6Multicasts.pN59_github.com_syncthing_syncthing_internal_discover.Discoverer
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/discover/discover.go:124

goroutine 32 [IO wait]:
beacon.genericReader
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/beacon/beacon.go:24
created by github.com_syncthing_syncthing_internal_beacon.NewMulticast
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/beacon/multicast.go:40

goroutine 33 [chan receive]:
github.com_syncthing_syncthing_internal_beacon.writer.pN56_github.com_syncthing_syncthing_internal_beacon.Multicast
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/beacon/multicast.go:58
created by github.com_syncthing_syncthing_internal_beacon.NewMulticast
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/beacon/multicast.go:41

goroutine 34 [chan receive]:
github.com_syncthing_syncthing_internal_beacon.Recv.pN56_github.com_syncthing_syncthing_internal_beacon.Multicast
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/beacon/multicast.go:51
github.com_syncthing_syncthing_internal_discover.recvAnnouncements.pN59_github.com_syncthing_syncthing_internal_discover.Discoverer
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/discover/discover.go:334
created by github.com_syncthing_syncthing_internal_discover.startLocalIPv6Multicasts.pN59_github.com_syncthing_syncthing_internal_discover.Discoverer
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/discover/discover.go:124

goroutine 35 [select]:
github.com_syncthing_syncthing_internal_discover.sendLocalAnnouncements.pN59_github.com_syncthing_syncthing_internal_discover.Discoverer
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/discover/discover.go:325
created by github.com_syncthing_syncthing_internal_discover.StartLocal.pN59_github.com_syncthing_syncthing_internal_discover.Discoverer
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/discover/discover.go:82

goroutine 36 [chan receive]:
main.listenConnect
	/build/buildd/syncthing-0.11.0/cmd/syncthing/connections.go:34
created by main.syncthingMain
	/build/buildd/syncthing-0.11.0/cmd/syncthing/main.go:567

goroutine 37 [select]:
github.com_syncthing_syncthing_internal_model.Serve.pN54_github.com_syncthing_syncthing_internal_model.rwFolder
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/model/rwfolder.go:135
created by github.com_syncthing_syncthing_internal_model.StartFolderRW.pN51_github.com_syncthing_syncthing_internal_model.Model
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/model/model.go:162

goroutine 38 [IO wait]:
main.listenTLS
	/build/buildd/syncthing-0.11.0/cmd/syncthing/connections.go:158
created by main.listenConnect
	/build/buildd/syncthing-0.11.0/cmd/syncthing/connections.go:27

goroutine 39 [sleep]:
main.dialTLS
	/build/buildd/syncthing-0.11.0/cmd/syncthing/connections.go:256
created by main.listenConnect
	/build/buildd/syncthing-0.11.0/cmd/syncthing/connections.go:31

goroutine 40 [select]:
github.com_syncthing_syncthing_internal_model.Serve.pN54_github.com_syncthing_syncthing_internal_model.rwFolder
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/model/rwfolder.go:135
created by github.com_syncthing_syncthing_internal_model.StartFolderRW.pN51_github.com_syncthing_syncthing_internal_model.Model
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/model/model.go:162

goroutine 41 [select]:
main.usageReportingLoop
	/build/buildd/syncthing-0.11.0/cmd/syncthing/usage_report.go:102
created by main.syncthingMain
	/build/buildd/syncthing-0.11.0/cmd/syncthing/main.go:610

goroutine 42 [select]:
main.sendUsageReport
	/build/buildd/syncthing-0.11.0/cmd/syncthing/usage_report.go:93
main.$nested12
	/build/buildd/syncthing-0.11.0/cmd/syncthing/main.go:613
created by main.syncthingMain
	/build/buildd/syncthing-0.11.0/cmd/syncthing/main.go:611

goroutine 43 [sleep]:
main.standbyMonitor
	/build/buildd/syncthing-0.11.0/cmd/syncthing/main.go:945
created by main.syncthingMain
	/build/buildd/syncthing-0.11.0/cmd/syncthing/main.go:621

goroutine 44 [sleep]:
main.generatePingEvents
	/build/buildd/syncthing-0.11.0/cmd/syncthing/main.go:722
created by main.syncthingMain
	/build/buildd/syncthing-0.11.0/cmd/syncthing/main.go:635

goroutine 70 [finalizer wait]:

goroutine 308 [semacquire]:
github.com_syncthing_syncthing_internal_events.Since.pN67_github.com_syncthing_syncthing_internal_events.BufferedSubscription
	/build/buildd/syncthing-0.11.0/gopath/src/github.com/syncthing/syncthing/internal/events/events.go:240
main.restGetEvents
	/build/buildd/syncthing-0.11.0/cmd/syncthing/gui.go:668
main.$nested1
	/build/buildd/syncthing-0.11.0/cmd/syncthing/gui.go:209
main.$nested4
	/build/buildd/syncthing-0.11.0/cmd/syncthing/gui.go:260
main.$nested10
	/build/buildd/syncthing-0.11.0/cmd/syncthing/gui_csrf.go:63
main.$nested5
	/build/buildd/syncthing-0.11.0/cmd/syncthing/gui.go:267

goroutine 331 [IO wait]:
main.Read.pN22_main.WrappedConnection
	/build/buildd/syncthing-0.11.0/cmd/syncthing/tls.go:123

**Comment by wweich** [comment]
Do you also get the panic when using the latest official version?

The version you are using is neither current nor official.
You can find the latest version [here](https://github.com/syncthing/syncthing/releases/latest) or use the [official Debian / Ubuntu repository](http://apt.syncthing.net/)

**Comment by AudriusButkevicius** [comment]
Please use the official release, the repo maintainers have compiled it using an unsupported compiler.
You'll find a ton of the same issue if you search closed issues.
