### ISSUE TITLE
Syncthing version error

### ISSUE THREAD

**Issue by blacktrooper2** [syncthing/syncthing#1888]
Hi all,

I'm encountering a strange issue with Syncthing.
I've updated to the version to 0.11.6 on one computer (mac) and the web gui says the proper version.
The other one (mac too) sees it with the good version with the web GUI but the LOG file says it is still on the previous version (0.11.1).

----------------------------------------------------------------------------------------------------------------------------------------
[ASFUX] 12:10:07 INFO: Connection to QKX4CIP-7BJHAGC-QPMK6LE-K72KPZR-MYA5DWP-JLFQNTF-RGXKIPT-6CRIEAN closed: read tcp 192.168.1.22:22000: connection reset by peer
[ASFUX] 12:12:11 INFO: Established secure connection to QKX4CIP-7BJHAGC-QPMK6LE-K72KPZR-MYA5DWP-JLFQNTF-RGXKIPT-6CRIEAN at 192.168.1.28:58301-192.168.1.22:22000
[ASFUX] 12:12:11 INFO: Device QKX4CIP-7BJHAGC-QPMK6LE-K72KPZR-MYA5DWP-JLFQNTF-RGXKIPT-6CRIEAN client is "syncthing v0.11.1"
[ASFUX] 12:12:11 INFO: Device QKX4CIP-7BJHAGC-QPMK6LE-K72KPZR-MYA5DWP-JLFQNTF-RGXKIPT-6CRIEAN name is "ServerComposit"
----------------------------------------------------------------------------------------------------------------------------------------

I've noticed that because web GUI tells me, the folder sync progress failed:
----------------------------------------------------------------------------------------------------------------------------------------
Folder "ххх" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.
----------------------------------------------------------------------------------------------------------------------------------------

I've checked  the log file but is not really clear to the newbie I am.
Is there anyone who can give me a hand on it ?

Thanks in advance,

Note : I'm a french user so if it is not in good english, don't hesitate to correct me !

Chris

**Comment by AudriusButkevicius** [comment]
I don't think this is a bug but more like a question, hence closing.
You can try using the forum or the IRC channel, but I am sure that it's just an old log line which is causing you confusion perhaps.
