### ISSUE TITLE
Syncthing don't remove the pull request sync tmp when "no space left on device"

### ISSUE THREAD

**Issue by psabater** [syncthing/syncthing#1890]
Problems with disc space like  #302

Tested on:
 - Syncthing version v0.11.6.
 - Node 1: linux amd64 with 100GB disc space.
 - Node 2: linux arm with 8GB disc space.

Steps:
1. Setup 2 nodes that syncs without shared files.
2. Node 1 share one file called 'shareFile' with 10GB size.
3. Node 2 start to sync and stops (in my case by 81%).
4. Node 1 delete shared file.

Node 2 don't remove shareFile.tmp that was created by sycthing. It would be great that when syncthing stop by a critical error, all files it tried to sync will remove their temporal files.

**Comment by AudriusButkevicius** [comment]
It will delete it in 12 hours, but the reason it keeps it, is in case someone restores the file, it will not need to redownload what it already has, which is more beneficial than freeing up space in 99% of cases.

I feel this is a `wontfix`

**Comment by psabater** [comment]
Hi @AudriusButkevicius

It's true that in this case its better to have the tmp file but the problem is when the node 1 remove the file "shareFile" this object isn't in the "Global State". In this case the tmp file should disappear.

**Comment by AudriusButkevicius** [comment]
As I said, it will, in 12 hours.

**Comment by psabater** [comment]
Oh sorry i didn't see it well (It's a wontfix).

Thanks for the info.
