### ISSUE TITLE
“xdr read: bytes field exceeds size limit”

### ISSUE THREAD

**Issue by AntoineVe** [syncthing/syncthing#1891]
Hi,

I try to use syncthing but nothing is synced. It's between my laptop and a server.
They're connected over 802.11n WiFi then optical fibre transmission (i.e. ping is good, bandwith is good, network and firewall are knowed and configured).

My laptop is on FreeBSD : 
 - « FreeBSD io.van-elstraete.net 10.1-RELEASE-p6 FreeBSD 10.1-RELEASE-p6 #0: Tue Feb 24 19:00:21 UTC 2015     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64 »
 - syncthing v0.10.23 (go1.4.2 freebsd-amd64 default) root@io.van-elstraete.net 2015-05-29 13:00:28 UTC

Server is on ArchLinux : 
 - « Linux centauri.van-elstraete.net 3.14.43-2-lts #1 SMP Fri May 22 03:36:10 UTC 2015 x86_64 GNU/Linux »
 - syncthing v0.11.6 (go1.4.2 linux-amd64 default) builduser@jara 2015-05-23 23:58:46 UTC

On my laptop I get : « INFO: Connection to [...ID...] closed: Options exceeds size limit; 465343650 > 64 »

On my server I get : « INFO: Connection to [...ID...] closed: EOF »

Nothing more with «STTRACE="xdr"» or «STTRACE="net"».

**Comment by AntoineVe** [comment]
I just tested syncthing for android and it's perfectly syncing with the same server on the same network. I seems that only the freebsd package is touched by this issue.

**Comment by rumpelsepp** [comment]
On Freebsd you write:
> syncthing v0.10.23

On arch you have:
> syncthing v0.11.6

Version 0.11 is not compatible to 0.10, see also: https://forum.syncthing.net/t/syncthing-v0-11-0-release-notes/2426?u=rumpelsepp

So please upgrade your FreeBSD machine. AFAIK there is 0.11.5 already available, so `pkg upgrade` may be enough.

**Comment by AntoineVe** [comment]
Ok, it work with this version. Shame on me, I've missing a portsnap update...
