### ISSUE TITLE
Error renewing UPnP port mapping for external port 31828 on device 

### ISSUE THREAD

**Issue by seth-space** [syncthing/syncthing#1892]
setting up two local syncthing installs for a sync. ( 192.168.1.145 syncing music with 192.168.1.223) The syncing seems to work but stays at 0%. 192.168.1.1 is the gateway.
One error keeps popping up: Error renewing UPnP port mapping for external port 31828 on device 

complete error: 1:04:03: Error renewing UPnP port mapping for external port 31828 on device 'RT-AC66U' (192.168.1.1): Post http://192.168.1.1:50004/ctl/IPConn: dial tcp 192.168.1.1:50004: connection refused etc.. etc..

seems syncthing wants to get out the lan? dial tcp sounds wrong.

**Comment by AudriusButkevicius** [comment]
Disable UPnP and global discovery if you only plan to use it in lan.

**Comment by calmh** [comment]
Seems like your gateway is saying "talk to me on port 50004" and then answering that with a connection refused when we try to do so. It sounds like a bug on the gateway...
