### ISSUE TITLE
"Folder Path" autocomplete should be case-insensitive

### ISSUE THREAD

**Issue by cdhowie** [syncthing/syncthing#1893]
When typing the path for a new folder, say `D:\FooBar` into the "Folder Path" field, in order for completion to suggest this folder I *must* type it in its exact case.  If I type `D:\f` then this folder is not suggested.

While I understand that not all filesystems are case-sensitive, the completion mechanism for this field should be.  Otherwise, it's very awkward entering the name of a folder that's not all lowercase (or at least not lowercase for the first few characters).

**Comment by uok** [comment]
duplicate #1347
