### ISSUE TITLE
Add Gentoo Linux package link to docs/web

### ISSUE THREAD

**Issue by timboudreau** [syncthing/syncthing#1895]
I noticed there was not a Gentoo Linux package - an ebuild - for syncthing (with Gentoo, you compile everything from source, and an ebuild downloads sources and builds and installs).  So I created one, [hosted here](https://github.com/timboudreau/gentoo).

That repository is not an official repo, but it *is* in the list of available 3rd-party repositories for Gentoo users.  So, to install syncthing on Gentoo linux:

```sh
layman -a timboudreau && eix-update && emerge syncthing
```

which will install `go` if needed, download the source, and build and install `syncthing` along with `/etc/init.d/syncthing` which will run it on startup (you need to configure the user to run as in `/etc/conf.d/syncthing`).

**Comment by calmh** [comment]
This should be listed on http://docs.syncthing.net/users/contrib.html -- do you mind opening a PR for that page?
