### ISSUE TITLE
Language setting not stored independently from the browser history

### ISSUE THREAD

**Issue by lblblb** [syncthing/syncthing#1898]
Syncthing 0.11.7
Windows 7 64bit
Firefox 38.0.1

I noticed the new language selector at the top of the GUI. Whenever I click it to select my preferred language and close the browser and open it later again, the language jumped back to my system language. I'd like to have that setting to get saved, so that it will stay, otherwise the new feature doesn't help much at all in my opinion.

**Comment by calmh** [comment]
It's saved in a datastore in your browser. If that doesn't work, there's a bug in that code or the browser. Can you check the Javascript console for errors when you do this?

**Comment by dcarosone** [comment]
Or the user users multiple browsers, doesn't save (or clears) history, uses
localhost vs 127.0.0.1, syncthing Web ui changes port number, or various
other scenarios...

**Comment by calmh** [comment]
Yeah. It also uses whatever language the browser requests primarily, so...

**Comment by lblblb** [comment]
– I use Firefox all the time.
– I clear the browser history, my expectation was that Syncthing saved the language setting to his own database
– I use the localhost address with the same port each time
I hope this helps, if not I'll try to get the console output.

**Comment by AudriusButkevicius** [comment]
Well it could be a side-effect of clearing browser history, as it's not exactly clear what that does.

**Comment by lblblb** [comment]
OK, I've tested keeping all browser history and it keeps the language setting. So my request would be to make this setting more permanent, i.e. introducing a new setting in the config file that keeps the setting.

**Comment by jpjp** [comment]
This is a weird request really: the user's browser is already requesting a specific language. If that doesn't work, the user can set a language as preference. Your request is to set a permanent language for every user that overrides those things?

**Comment by lblblb** [comment]
It's just me who has a specific browser language setting and prefers to have Syncthing in another language, permanently, without having to keep the browser history. I agree it's a very specific request and I don't see it as a top priority one, but I wanted to bring it up.

**Comment by calmh** [comment]
There is actually a workaround for this specific situation. Bookmark and use `http://localhost:8383/?lang=ru` (or whatever language code you prefer).
