### ISSUE TITLE
Shared Dropbox folder icon 'contains invalid characters' 

### ISSUE THREAD

**Issue by noreye** [syncthing/syncthing#1899]
Hi there,

I use Syncthing to sync between my windows and mac machines.

I have a dropbox folder (OSX side) and I have a few shared folders inside (dropbox shared). THese folders have an extra file named 'iconx.

Syncthing says they contain invalid characters.

File name "Dropbox/nori/nerdland/Icon\r" contains invalid characters; marked as invalid.

Is this normal behaviour?

**Comment by calmh** [comment]
The newline at the end is not an allowed character in file names on Windows.

**Comment by noreye** [comment]
Ok. Thanks.
Is there a way to set Syncthing to ignore \r files?
I get a big list of flags in the Syncthing GUI (ca 10-12 lines). I can imagine for some with many shared folders, this could be very annoying.

**Comment by calmh** [comment]
Sure. Adding `Icon?` to the `.stignore` file (or edit ignore patterns among the folder settings in the GUI) should do it. The question mark matches the newline.

**Comment by noreye** [comment]
great thanks!
