### ISSUE TITLE
Change name of files while exists Sync

### ISSUE THREAD

**Issue by robertookode** [syncthing/syncthing#1900]
hello ,

If while rename a file exists sync, syncthing restarts the file upload or continuous? how does this process ?

In the parameter "keepTemporariesH",  I can change value by seconds?

Thanks!!

**Comment by AudriusButkevicius** [comment]
If you rename it mid-sync, it will redownload the whole file, as the blocks in the temporary file would not have made into the database.

If you rename it or copy it after it has been synced it should not re-transfer anything.
You cannot change `keepTemporariesH` by seconds, as H implies hours.

I guess this is a question, and not actually a an issue. Are we good to close this?

**Comment by robertookode** [comment]
is a question.

Thanks!!
