### ISSUE TITLE
Sync problems when changing folder case.

### ISSUE THREAD

**Issue by bwmarrin** [syncthing/syncthing#1904]
If I create a folder on my Windows computer, called "toolbox" and add a few files.  All of these get synced as you would expect, to my other 2 computers (1 Linux, and another Windows).

On my Linux computer, if I change the name of this folder to "Toolbox" than I start having sync errors.

After doing this, I'll start getting errors like below.  In one case, when I first noticed it, it seemed that at some point it ended up deleting the whole toolbox folder but I can't seem to replicate that.  But, I do get these errors which I can only fix by removing the folder myself.

```
[MLEDZ] 12:21:17 INFO: Puller (folder "default", file "toolbox/browsinghistoryview-x64/BrowsingHistoryView.chm"): dst stat dir: stat /home/bruce/Sync/toolbox/browsinghistoryview-x64: no such file or directory
[MLEDZ] 12:21:17 WARNING: Folder "default" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.
```

**Comment by calmh** [comment]
Yeah, this is #1787
