### ISSUE TITLE
syncthing service using nssm

### ISSUE THREAD

**Issue by cedricbrx** [syncthing/syncthing#1908]
Hi
I'm followed the instruction on docs.syncthing.net to get syncthing working on windows as a service.
I got a strange behaviour, syncthing is turning twice on my machine now. Is that normal? If it is it would be great to explain it in the documentation.

![syncthing](https://cloud.githubusercontent.com/assets/11331696/7948461/657d7646-0984-11e5-9251-d39670cb6a72.png)

Regards

**Comment by lfam** [comment]
It is normal, see here: http://docs.syncthing.net/users/faq.html#why-do-i-see-syncthing-twice-in-task-manager

**Comment by wweich** [comment]
Oft cause it is running twice.
You configured it as a service and are still using syncthing-gtk, which starts its own instance of syncthing.
