### ISSUE TITLE
Change default time for keepTemporariesH

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#1910]
I just helped a friend solving the situation between his two devices (slow connection) which never finished transfer of big files: since both devices are often not online at the same time (or not long enough) the setting `keepTemporariesH` kicks in and downloads start from the beginning on the next day(s).

Since free hard disk space is not a big problem nowadays I suggest to change the default time of `keepTemporariesH` to a higher value (e.g. 1 week). This would help save a lot of bandwidth and time, especially in Europe where internet connections are asynchronous most of the time (= slow upload, fast download) or in rural regions with slow connections.

**Comment by calmh** [comment]
I'm not convinced this is the case for a majority of users.

**Comment by AudriusButkevicius** [comment]
Agree with calmh, if we don't finish it in 24 hours we might as well redownload it, or just declare civil war on ISPs

**Comment by canton7** [comment]
Is the timeout from when the temp file was first created, or last written to?

**Comment by AudriusButkevicius** [comment]
mtime I believe
