### ISSUE TITLE
panic: leveldb/table: corruption on data-block

### ISSUE THREAD

**Issue by fidian** [syncthing/syncthing#1914]
Log file at http://public.rumkin.com/syncthing/ and I put in another file there that is the end of my syncthing.log

Nothing shows up in /var/log/syslog for that time period.

Probably similar to #1853.

How do I get this working again?

**Comment by AudriusButkevicius** [comment]
Just delete the index directory from syncthings home directory.
This can also be caused by a power outage, etc.

**Comment by fidian** [comment]
Any idea what caused the issue?  Is there additional information I can provide?  The machine was up consistently for over two months and on a RAID that wasn't experiencing issues.

**Comment by AudriusButkevicius** [comment]
Out of order writes are usually the cause.
Could be due to caching software/wierd filesystem/hardware issues/bugs in the database potentially?
