### ISSUE TITLE
Allow Filter to exclude files older than date

### ISSUE THREAD

**Issue by bmunro-peralex** [syncthing/syncthing#1917]
HI

We would like to sync Development Folders between Remote sites, But due to bandwidth limitations syncing everything is not practical. Is it possible to sync files only from this year and keep the current directory structure.

Eg: Exclude files older than: 1/1/2015

**Comment by AudriusButkevicius** [comment]
I don't think any other sync solution around supports that, hence my personal view would be `won't fix`

**Comment by bmunro-peralex** [comment]
We are currently using FileReplicationPro which does support it, But its file walk takes forever each sync.

**Comment by calmh** [comment]
Old files don't change though, so they require zero bandwidth?

(If they change then they are no longer old files, so they would be synced anyway)

**Comment by bmunro-peralex** [comment]
I get what you saying, and it is valid. Our connection to remote sites are to slow for the amount of data. As we do a one way sync both ways. And then we looking  at a few days to a week of downtime for the initial sync of data both ways. I do think a filter by date would be nice to have as that's what we are currently doing.

so this is actually a two part issue, Saving Disk space on remote hardware ( Not syncing 10 Years worth of files) + bandwidth.

**Comment by calmh** [comment]
Gotcha. This would need some thinking to make sure it's done right, if implemented, as a file can move between non-ignored to being ignored and back again without any changes happening to the ignore patterns. I think it could be a valid feature, possibly, but care needs to be taken.

**Comment by dcarosone** [comment]
There is already 'pull newest first', which will at least get you working
sooner, but won't help keep the link from being flattened with the rest.

Consider using the rate limiting feature, after you've pulled down enough
current data to work, and let the rest trickle in?

Another thing I've had success with in cases like these is a travelling
sync box (eg laptop) that moves between sites and helps catch up on bulk
data changes.

I agree it would be a good feature, just some suggestions on how to get
closer with existing features.

**Comment by calmh** [comment]
I think this is something we should not do, as it's somewhat complex and unintuitive. If there is disagreement, I now have a requirements gathering issue in #2491 where it can be discussed.
