### ISSUE TITLE
Random hanging and low speed of syncing

### ISSUE THREAD

**Issue by alexandr-kn** [syncthing/syncthing#1920]
Hello!
We have a workbench with two servers:

Server 1: device1
<pre>
CentOS release 6.6 (Final)
2x Intel® Xeon® Processor E5320 (8M Cache, 1.86 GHz, 1066 MHz FSB)
12Gb memory:
    2x 4GB DDR2-667MHz
    2x 2Gb DDR2-667MHz
</pre>

Server 2: device2
<pre>
FreeBSD 10.1-RELEASE
Intel(R) Core(TM)2 Quad CPU    Q9400  @ 2.66GHz
12Gb memory:
    2x 4GB DDR2-800MHz
    2x 2Gb DDR2-800MHz
</pre>

We have syncthing v0.11.5 installed on both servers.
Servers are directly connected via 1000BASE-T twisted pair.
Firewall is turned off on both servers.
We are trying to syncronize 6Tb of data (about 50K files of size from 100kb to 10Gb) stored on device1 with device2
When Syncthing is running we see  full utilization of physical memory and 3 of 8 physical cores loaded at 100% on "device1"
Maximum transmission speed we ever noticed is 170Mbps.
Maximum size of successfully transfered data is 1Tb.
Both "device1" and "device2" randomly lose connections
Sometimes sync just freezes while connections are still active. It can be resolved either with restart Syncthing on both servers or, sometimes, with just entering Syncthing web interface.
We're having same issue with all versions of Syncthing.
With rsync we have a stable transfer at 500-600Mbps

Config files from both servers are linked below

"Device1"
http://pastebin.com/N9Mgpmvh

"Device2" 
http://pastebin.com/6ezhjGqs

https://forum.syncthing.net/t/random-hanging-and-low-speed-of-syncing/2979

**Comment by AudriusButkevicius** [comment]
Let's keep it on the forum for now, and if we actually find a bug, we'll reopen this.
