### ISSUE TITLE
Syncthing creates a directory literally named "~"

### ISSUE THREAD

**Issue by matiashf** [syncthing/syncthing#1924]
I noticed that I have a file literally named ```~``` in my home directory. I'm assuming it was created by syncthing based on its contents. Note that I'm running syncthing 0.11.5, not the latest version.

```
mhf@t-rex:~$ ls -ld \~
drwx------ 3 mhf mhf 4096 juni   3 16:03 ~
mhf@t-rex:~$ tree -a \~
~
└── .config
    └── syncthing

2 directories, 0 files
```

```
mhf@t-rex:~$ lsb_release --description
Description:	Ubuntu 14.10
mhf@t-rex:~$ syncthing --version
syncthing v0.11.5 (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-05-15 08:46:47 UTC
```

There are no environment variables containing tilde, but the syncthing binary does contain the string ```~/.config/syncthing```:
```
mhf@t-rex:~$ for pid in $(pidof syncthing); do cat /proc/$pid/environ | tr '\0' '\n' | grep \~; done
mhf@t-rex:~$ 
mhf@t-rex:~$ grep \~/.config/syncthing $(which syncthing)
Binary file /usr/bin/syncthing matches
```

**Comment by AudriusButkevicius** [comment]
Can you post your config, anonimized preferably

**Comment by calmh** [comment]
I'm guessing you've started it via some process manager with a `-home ~/.config/syncthing` parameter?

**Comment by calmh** [comment]
To clarify, we don't do any expansion of the path given to `-home`. The shell does though, if started that way. Maybe your service manager doesn't, and it's configured to pass that parameter.

```
jb@syno:~ $ ls -ld foo
ls: foo: No such file or directory
jb@syno:~ $ syncthing -home ~/foo
[monitor] 13:26:49 INFO: Starting syncthing
[start] 13:26:49 INFO: Generating RSA key and certificate for syncthing...
^C
jb@syno:~ $ ls -ld foo
drwx------  6 jb  staff  204 Jun 10 13:26 foo/
jb@syno:~ $ rm -r foo
jb@syno:~ $ syncthing -home \~/foo
[monitor] 13:27:01 INFO: Starting syncthing
[start] 13:27:01 INFO: Generating RSA key and certificate for syncthing...
^C
jb@syno:~ $ ls -ld foo
ls: foo: No such file or directory
jb@syno:~ $ ls -ld \~
drwx------  3 jb  staff  102 Jun 10 13:27 ~/
jb@syno:~ $ rm -r \~
```

**Comment by matiashf** [comment]
Correct, I started syncthing with ```syncthing -no-browser -home="~/.config/syncthing"```, thus the tilde was quoted and not expanded. My bad! Thank you for your prompt response though. :+1:
