### ISSUE TITLE
Theme selector for different bundles css files

### ISSUE THREAD

**Issue by Getron** [syncthing/syncthing#1925]
Here a proposal of dark skin for Syncthing:

![syncthing dark](https://cloud.githubusercontent.com/assets/5913218/8073589/7924cb92-0f27-11e5-9324-418257da3d36.png)

I use on my Linux all the dark themes of desktop software and desktop itself, like, for example, on Fedora 22 KDE - dark breeze theme.

For me, the dark themes are more eye candy, and, for work at the night, is the best for eyes. The white sites, or white backgrounds are terrible, if you work on night (at least for me).

Maybe, we can add this dark theme to be able to change it from somwhere, maybe on options, or maybe on the footer menu, right side, to can choose light or dark theme of Syncthing.

I think, this theme is helpfull for many other user, who like dark themes.

I can provide the css, if you decide to add this theme to.

Thank you in advance.

**Comment by dcarosone** [comment]
+1

**Comment by calmh** [comment]
We could add something similar to the language chooser, for being able to select a stylesheet from multiple included ones.

**Comment by Getron** [comment]
@calmh yes, that would be great.

**Comment by Getron** [comment]
@calmh how can i send you the 2 css files?

I have re-worked it completly, and hope, that you will add somthing like language selector for the Style. I think, the best place would be on the footer, on the right side, named as "Style". What you think?

Would be this added?

**Comment by calmh** [comment]
I'd accept a pull request with a style selector as described, and the style sheets in question being the first "alternate" style. And probably we'd need to look in a specific folder in the config dirs for more stylesheets and present those as choices as well if they exist, so it's more easily themed by the user. Without that, I think it would be a little bit half baked.

**Comment by Getron** [comment]
@calmh Unfortunatly, i'm not so good on programing, i'm just good on designing, i can't make pull request. I have done this theme on browser, and not on the raw software.

I'l be very thankfull, if you, or someone, who can programing and adding theme selector would make this on Syncthing.

If someone can do this theme selector, i'm sure, the Syncthing would be more professional. And i would make more themes after, to have many themes for selecting.

Thanks in advance to every one would do this theme selector. I apreciate work of all peaople doing Syncthing more and more better.

**Comment by Getron** [comment]
Do someone implements this? And if yes, where i can put, or send the css files? Theme is done, just need to put the css and create theme selector.

Thanks

**Comment by calmh** [comment]
This is now the ticket for the theme selector functionality. :)

**Comment by marclaporte** [comment]
Some easy-to-bundle FLOSS themes: https://bootswatch.com/

In Tiki Wiki CMS Groupware, we included them all :-)

**Comment by snnd** [comment]
@Getron @calmh i would be in for the implementation of the selection dropdown. i am just not quite sure about where to store the custom setting. but i think it should be the same way as synthing stores the language setting, shouldn't it?

@Getron so if you would be so kind to grant me access to a fork where you build the css stuff, that would be great! :)

**Comment by calmh** [comment]
@snnd That'd be my best guess too.

**Comment by Getron** [comment]
@snnd i don't have a fork, i just have the 2 css files. i build them on browser. I can provide this 2 files.

@marclaporte i have revorked the dark theme, with many details, shadows and effects. I would apreciate, if my reworked theme will be added to all these from bootswatch to.

How can i send here this files? i can just images to attach here on this github editor. Should i put this 2 css files somwhere on my private server, better?

@calmh Yes, it would be great to make an drop-down selector like language, but the best position for this, i think is on the lower right corner, footer, i guess. What you think?

**Comment by uok** [comment]
There might be some themes that don't have a footer so I think the setting should be a menu item or a settings modal (and also because you only change it once). 

@Getron: you should spend some time learning how to submit files on github. This would allow the devs to look through your code, comment and merge the files. Other people can work, fork, etc. the themes and also you can help and improve other parts of Syncthing

**Comment by Getron** [comment]
@uok I have done the css on my browser, on chrome, not on github, or original files. Changed on Chrome, saved with Chrome, done.

I just have the 2 css files.

Someone do this selector? If i would be able to do it, i would add it, but, i can't, unfortunatly. I think, this is not so complicated to add for devs, is not a big problem?

**Comment by Getron** [comment]
Anyone working somthing on this?

**Comment by fti7** [comment]
@Getron could you please attach your modified CSS Stylesheet Files? (Just drag&drop it into the textbox here). Thx

**Comment by Getron** [comment]
@fti7 have tryed this, but, doesn't work, here the error here in github editor:

Unfortunately, we don’t support that file type.  Dateien auswählen Try again with a PNG, GIF, JPG.

But, i have pasted it into my web server, here:
http://www.getron.ch/sync/Syncthing-2-CSS-Files.zip

Hope, you can download it, and do the Theme Selector on Syncthing, would be great thing. Thank you.

**Comment by Getron** [comment]
@fti7 Just wonder, do you have started somthing on this?

**Comment by fti7** [comment]
Hi Getron,
havent looking deeper into this yet, sorry. (not enough spare time at the moment)
But i've added it to one of my syncthing instances and i like it :-)

But you should rework the CSS Files a little bit
* bootstrap.min.css -> never touch this file, its vendor specific and all changes made there should be at least go into the overrides.css

* overrides.css
I suggest to move all Color/Theme Specific Settings into a new Css File (like theme-light.css)
So just general (all theme) overrides are in there.

Then we introduce an theme-dark.css with all the theme specific "overrides"... including that one in bootstrap.min.css

So we can easily add this CSS Files to the static gui assets and ship them with syncthing.
With a simple Config Option we let the user Choose between them.

Personally i would like to have only two Themes (Light and Dark; Maintained by Syncthing) and not 1001 User Contributed Themes. Of course there are Pros and Cons for this.

**Comment by Getron** [comment]
@fti7 great to hear that you like my idea of theme.

The problem is, that most changes are in the bootstrap, and here and there, a change in overrides.

We can just rename this 2 files for this theme, to whatever, and leave the origianl bootstrap and overrides untached. The problem, i hope, is solved with renaming. Or, maybe, with an folder, and put this 2 changed css on this folder, to be able to pic it from selector after.

Yeah, i would personaly like 2 themes, light and dark. But, we will see, how after this. It is important, to implement that system, to able to change the themes. Maybe, we can add an extra folder for the dark theme, with this 2 css, and selector should just to pic this 2 css from this folder, and if we change to light one, should pic the original files.

What you think idea with adding a folder, and programing selector to select the theme from this folder, or the original files?

**Comment by xor-gate** [comment]
@Getron very nice!

**Comment by Getron** [comment]
@calmh and @AudriusButkevicius Thank you very much for adding Themes supporting.

@xor-gate Thank you

But, this "Dark" theme is not the one i have proposed. Design is just black, or dark. Don't get me wrong, it is great that this "dark" one is there, it is far more better than the white, original one, for the night hours (in the night).

I apologize, i have build my new server, and don't see that the .zip was missed on the new server.

Here is the link, now it is works, with my 2 css files, for the "Gray" theme, maybe, we can name it so.

This is one re-worked theme, like in start of this post, but better. I spend hours to make it look even better (the link works now).

http://www.getron.ch/sync/Syncthing-2-CSS-Files.zip

Or, how can i make a pull request for this? Can i add the files my self here?

Many thanks to devs. Great work.

**Comment by AudriusButkevicius** [comment]
The ticket was about adding a selector, the selector is there, hence case closed.
Google has plenty of guides explaining how to make a pull request.
