### ISSUE TITLE
FATAL: Cannot open database

### ISSUE THREAD

**Issue by bittorrenter** [syncthing/syncthing#1926]
Hi,
I'm a big fan but recently I can't run Syncthing - runs OK on my other computers

Log follows:
"[Y2DGN] 17:30:11 INFO: syncthing v0.11.8 (go1.4.2 windows-amd64 default) unknown-user@syncthing-builder 2015-06-07 10:57:26 UTC
[Y2DGN] 17:30:11 INFO: My ID: Y2DGNDL-KQPJBRI-MJ6JSS7-4A5GNK6-QPKEI5T-XK6WECU-XGZ3D4B-NI5KSQU
[Y2DGN] 17:30:11 INFO: Database block cache capacity 65536 KiB
[Y2DGN] 17:30:11 FATAL: Cannot open database: leveldb/storage: corrupted or incomplete CURRENT file - Is another copy of Syncthing already running?
[Y2DGN] 17:30:12 INFO: syncthing v0.11.8 (go1.4.2 windows-amd64 default) unknown-user@syncthing-builder 2015-06-07 10:57:26 UTC
[Y2DGN] 17:30:12 INFO: My ID: Y2DGNDL-KQPJBRI-MJ6JSS7-4A5GNK6-QPKEI5T-XK6WECU-XGZ3D4B-NI5KSQU
[Y2DGN] 17:30:12 INFO: Database block cache capacity 65536 KiB
[Y2DGN] 17:30:12 FATAL: Cannot open database: leveldb/storage: corrupted or incomplete CURRENT file - Is another copy of Syncthing already running?
[Y2DGN] 17:30:13 INFO: syncthing v0.11.8 (go1.4.2 windows-amd64 default) unknown-user@syncthing-builder 2015-06-07 10:57:26 UTC
[Y2DGN] 17:30:13 INFO: My ID: Y2DGNDL-KQPJBRI-MJ6JSS7-4A5GNK6-QPKEI5T-XK6WECU-XGZ3D4B-NI5KSQU
[Y2DGN] 17:30:13 INFO: Database block cache capacity 65536 KiB
[Y2DGN] 17:30:13 FATAL: Cannot open database: leveldb/storage: corrupted or incomplete CURRENT file - Is another copy of Syncthing already running?
[Y2DGN] 17:30:15 INFO: syncthing v0.11.8 (go1.4.2 windows-amd64 default) unknown-user@syncthing-builder 2015-06-07 10:57:26 UTC
[Y2DGN] 17:30:15 INFO: My ID: Y2DGNDL-KQPJBRI-MJ6JSS7-4A5GNK6-QPKEI5T-XK6WECU-XGZ3D4B-NI5KSQU
[Y2DGN] 17:30:15 INFO: Database block cache capacity 65536 KiB
[Y2DGN] 17:30:15 FATAL: Cannot open database: leveldb/storage: corrupted or incomplete CURRENT file - Is another copy of Syncthing already running?"

There is no other copy of Synchthing running (Task Manager shows no instances of Syncthing)

 Regards,

**Comment by AudriusButkevicius** [comment]
Just delete the CURRENT file from the index folder in syncthings home folder (check -help).
This can be caused by a sudden power outage/reboot corrupting the database.

**Comment by bittorrenter** [comment]
Worked!

Thank you

**Comment by Shuunen** [comment]
In my case, I had to delete the whole index-vxxxdb folder to make it start again.

**Comment by jefstratiou** [comment]
Same here @Shuunen  , I had to delete the entire index-vx.xx.0.db as well. 

Then... back in business.

**Comment by Shuunen** [comment]
Do we identified how this happen ?

**Comment by AudriusButkevicius** [comment]
Bad hardware, power cut, or cosmic rays.

**Comment by Shuunen** [comment]
Sorry but I think it cannot be cosmic rays because I wrapped my head & keyboard with aluminium.

**Comment by megatog615** [comment]
Sorry to resurrect this, but I can reproduce this issue simply by resuming from suspend. I'm running Copper Cockroach on Debian testing, with F2FS /home partition.

**Comment by AudriusButkevicius** [comment]
Which part, not being able to open it or corruption?

**Comment by ramontayag** [comment]
Deleting `CURRENT` didn't work, so I deleted `LOCK` as well. I upgraded from `0.14.9` 
(I think) to `0.14.23` via Homebrew.
