### ISSUE TITLE
Selective Sync

### ISSUE THREAD

**Issue by Nutomic** [syncthing/syncthing#193]
It would be nice to have repositories that are not stored on the local device, but where files can be accessed on demand. 

This would be useful for Android (and other devices with little storage space). Android has the [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider.html) that allows this to work seamlessly (remote files can be accessed just like local files, and only metadata and maybe cached data is stored locally).

This is something that we might want at some point in the future, not immediately. Just to keep it in mind and plan for it. I will also have a closer look at the API and what exact functionality we need.

Edit: I should probably mention that this should be a per repo setting (not per node).

**Comment by robsonsobral** [comment]
Hi! May I give you a little more to think about?

We could have two more types of folders, beside _master_: _selective_ and _on demand_.

On both we should be able to navigate through the folder right on UI in an accordion menu style. Every item on the _selective_ mode would have `+` signs and checkboxes. The _on deman_ mode would be simpler: `+` and a downwards arrow which allow the users to download the file or folder to their own computer; so, no corner cases, no sync, just download.

_on demand_ could help a lot of people who wants to download their songs or books or presentations for work or references for design, etc...

Both types would cover my use case. I have about five thousands files, on different languages, and the users just need to download some of them.

Thanks for the attention and for the useful software.

**Comment by maikeldus** [comment]
+1

**Comment by jonada** [comment]
This is not solved with .stignore, which is permanent. 

Rather this is issue is the same/related to syncthing/syncthing-android#81.

Support must be added in both syncthing and the anroid app.

**Comment by fnkr** [comment]
+1.

.stignore does not solve the problem.

**Comment by AudriusButkevicius** [comment]
There is a new master ticket for this issue.

**Comment by lkwg82** [comment]
@AudriusButkevicius  Which one?

**Comment by AudriusButkevicius** [comment]
https://github.com/syncthing/syncthing/issues/2491
