### ISSUE TITLE
"Trashcan" versioning strategy

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#1931]
We should implement the simplest possible versioning strategy: when a file is going to be removed or replaced, it's moved to it's place in .stversions. No renaming or fancy stuff - only the latest version is kept. Possible addition to remove files older than x days in a periodic scan thing.

**Comment by cbhushan** [comment]
+1 for this simple strategy. In my opinion maximum age is an important addition.

**Comment by Getron** [comment]
+1
