### ISSUE TITLE
could "x makes no progress" give more information. log file is difficult to find...

### ISSUE THREAD

**Issue by andrewufrank** [syncthing/syncthing#1934]
i have a hard time to find the logs when i get the "x makes no progress" message. would it be possible to include more information there (e.g. what is given in the log) - or at least state where the log is. I have multiple installations (half a dozen) and the log file is not always the same place. 
otherwise: very good tool! thank you!
andrew

**Comment by Zillode** [comment]
Thanks,
Dup of https://github.com/syncthing/syncthing/issues/1437
