### ISSUE TITLE
Can not start in WinXP SP3

### ISSUE THREAD

**Issue by hobby16** [syncthing/syncthing#1936]
Hi all,
Thank you for the great work. I have installed Syncthing and configured with the web UI without problem on 2 laptops with win7. 
But I have an old WinXP laptop with more than 100G of spare disk. It is used as a web browser for the family and I want to make it a backup station.
So I try to start Syncthing on it but it fails immediately (see the timestamps), all I get is the message below. 

[monitor] 16:25:39 INFO: Starting syncthing
[monitor] 16:25:39 FATAL: open NUL: Can not find the specified file

I've tried for hours and hours (changing default folder, environnement variable names...) without success. I know XP is not supported but maybe I am inches from something that works, I wished the error message could be more explicit about what is wrong. 
Maybe could someone help me, please ?

**Comment by AudriusButkevicius** [comment]
can you do `set "STTRACE=all"` in the command prompt before starting, and run it again?

**Comment by hobby16** [comment]
Oh sure, that's exactly what I need, thank you ! 
I'll do it in some hours since the laptop is not available now and I'll report it back.
I presume the error messages will be more detailed and helpfull then.

**Comment by hobby16** [comment]
I typed set "STTRACE=all". Then echo %STTRACE% gives
all
No improvement, I have the same lines of error.

**Comment by calmh** [comment]
What does your configuration look like, exactly? "NUL" seems like a fairly specific string, not "nil" which we would print if there was something uninitilialized. And it's a reserved filename in Windows...

**Comment by hobby16** [comment]
hi calmh,
Where do I find the "configuration" you want to know ? (win XP or syncthing configuration ?).
Two pieces of information, if of any use :
1)  I have updated to the lastest version by typing the syncthing update command in DOS 
2) the exact message is 
"[monitor] 16:25:39 FATAL: open NUL: Le fichier spécifié est introuvable."
since it's partly en French, I have manually translated into "Can not find the specified file" before asking my question.

**Comment by calmh** [comment]
%AppData%/Syncthing/config.xml, wherever that is on xp - at a guess some hidden folder under my documents?

Since you can use the command line, you can also try something like `syncthing -home c:\syncthing` to see if that works better. it sound like some problem with finding its home directory.

**Comment by hobby16** [comment]
@calmh 
Not better, I copy the folder to c:\syncthing but I have the same error :

C:\syncthing>syncthing.exe -home c:\syncthing
[monitor] 08:05:13 INFO: Log output saved to file "c:\syncthing\syncthing.log"
[monitor] 08:05:13 INFO: Starting syncthing
[monitor] 08:05:13 FATAL: open NUL: Le fichier spécifié est introuvable.

Here is the content of the %AppData%/Syncthing/config.xml (it's a link, I don't know how to c&p a code portion)
http://googledrive.com/host/0BxMfsstZ1EMcfkYzSzFmTVRHZGg5UzUwQjlqbk1wTzJTNjJiMG9wRWRKdVZlMnlEbGVqZkE/config.xml

**Comment by calmh** [comment]
Can you try this build: http://build.syncthing.net/job/syncthing-branch/55/

It wont solve it, but it'll print some debug info when starting up that may nail down what the problem is, similar to:

```
[monitor] 08:40:44 DEBUG: os.Args: []string{"syncthing", "-home", "foo"}
[monitor] 08:40:44 DEBUG: Entering loop
[monitor] 08:40:44 INFO: Starting syncthing
[monitor] 08:40:44 DEBUG: cmd: &exec.Cmd{Path:"/Users/jb/bin/syncthing", Args:[]string{"syncthing", "-home", "foo"}, Env:[]st...
```

**Comment by hobby16** [comment]
I downloaded your build syncthing-windows-386-v0.11.9+16-ged1822f 
Same error. Here is what I get :

C:\syncthing>syncthing.exe -home=c:\syncthing
[monitor] 12:36:09 INFO: Log output saved to file "c:\syncthing\syncthing.log"
[monitor] 12:36:09 DEBUG: os.Args: []string{"syncthing.exe", "-home=c:\\syncthin
g"}
[monitor] 12:36:09 DEBUG: Entering loop
[monitor] 12:36:09 INFO: Starting syncthing
[monitor] 12:36:09 DEBUG: cmd: &exec.Cmd{Path:".\\syncthing.exe", Args:[]string{
"syncthing.exe", "-home=c:\\syncthing"}, Env:[]string(nil), Dir:"", Stdin:io.Rea
der(nil), Stdout:(*os.File)(0x1111a710), Stderr:(*os.File)(0x1111a6e8), ExtraFil
es:[]*os.File(nil), SysProcAttr:(*syscall.SysProcAttr)(nil), Process:(*os.Proces
s)(nil), ProcessState:(*os.ProcessState)(nil), lookPathErr:error(nil), finished:
false, childFiles:[]*os.File(nil), closeAfterStart:[]io.Closer{(*os.File)(0x1111
a6e8), (*os.File)(0x1111a710)}, closeAfterWait:[]io.Closer{(*os.File)(0x1111a6e0
), (*os.File)(0x1111a708)}, goroutine:[]func() error(nil), errch:(chan error)(ni
l)}
[monitor] 12:36:09 FATAL: open NUL: Le fichier spécifié est introuvable.

**Comment by hobby16** [comment]
The c:\syncthing\syncthing.log file is empty and its size is 0k

**Comment by hobby16** [comment]
Do you have an idea, calmh ?

**Comment by hobby16** [comment]
Problem solved.
I have tried older versions : 
- all versions lower or equal 0.9.10 are OK on my XP Sp3 
- all versions higher than 0.9.10 have the error above.
I'll stay with 0.9.10 to have a functionning setup. Old version but fine for me.
Maybe it can give you some clues about the bug. 
Thank you anyway for the great software and for trying to help me.

**Comment by calmh** [comment]
Nice research. v0.9.11 introduces the monitor process for handling crashes and restarts. As such, you can probably work around this by setting the environment variable  `STNORESTART=1`, which the caveat that restarting Syncthing won't work any more (as that's handled by the monitor process that is disabled by doing this).

That said, I'm fairly sure recent versions work on *some* XP (at least I used to test on it, and v0.9.10 is quite old) so there's something more going on here that I don't know...

**Comment by Zillode** [comment]
Windows 10 was released today, I suggest an update;)
If more XP users experience this problem I'm willing to examine this further.

**Comment by kozec** [comment]
I really don't think that you can upgrade XP machine to Windows OS X, @Zillode ;-)
