### ISSUE TITLE
After missing folder is found again, the error message stays:

### ISSUE THREAD

**Issue by bigbear2nd** [syncthing/syncthing#1937]
syncthing v0.11.8 (go1.4.2 windows-amd64 default) unknown-user@syncthing-builder 2015-06-07 10:57:26 UTC

![unbenannt](https://cloud.githubusercontent.com/assets/7719800/8138079/30d69d52-1148-11e5-85bb-8f47cdd37c0c.PNG)

How to reproduce:

 - Unmount shared folder
 - Scan
 - Mount again
 - Scan

**Comment by bigbear2nd** [comment]
I guess it also belongs here:
![unbenannt2](https://cloud.githubusercontent.com/assets/7719800/8144183/441f7cac-11d0-11e5-8298-533ace9dbfca.PNG)

When the folder is stopped, the "Rescan" button is missing, but the "Rescan all" button is still available. After mounting the folder again, the only 2 ways to get it back "online" are:
 - click "Rescan all"
 - wait for the automatic rescan time is hit

**Comment by AudriusButkevicius** [comment]
Can you give the exact mount points you have and folder path?

**Comment by bigbear2nd** [comment]
I am using veracrypt to mount a complete Drive into X: (on windows)
my path is: "X:\Bilder" for example.
(any other path works, too)
