### ISSUE TITLE
Blockmap updates can cause too high memory usage

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#1938]
- device A (2GB RAM): folder with 120GB (~ 50 files) shared with device B
- successful sync to device B without any problems
- files are deleted on device B (and moved to .stversions on device A)
- device A crashes: out of memory
- device A now is in loop: restart, scanning, crash, etc.

how can I check what is causing this error and get Syncthing out of this loop?

**Comment by calmh** [comment]
Can we see the crash log?

**Comment by uok** [comment]
found a panic log, hope that helps
http://pastebin.com/RCBRrEUh

**Comment by calmh** [comment]
Yeah, I can see how that's a heavy operation. See if this build gets it through: http://build.syncthing.net/job/syncthing-branch/54/

This needs some improvement...

**Comment by uok** [comment]
0.11.8+17 went through without any problems or crashes, removing (what I can tell from your quick hack) the old meta data step by step instead of all at once. Then I went back to regular 0.11.8 keeping the clean index and all looks good!
Thanks for the quick fix :+1::dancer:

**Comment by calmh** [comment]
Yeah, it's not a fix (because it's too ugly and will have probably terrible performance in som cases) but it proves the problem. Needs to be fixed better.

**Comment by calmh** [comment]
Fairly sure this is fixed by the batching we do in blockmap updates.
