### ISSUE TITLE
Deny Adding of Folders

### ISSUE THREAD

**Issue by Pr0Wolf29** [syncthing/syncthing#1939]
Sometimes people make a mistake and try to share my a folder, but all I have is a "Add" and "Later" buttons. Why not just have a Deny button? If I using Syncthing with others on the internet, this could lead to annoying requests when people mess up. Pressing later just causes it to come back later, and is not a solution to the problem.

**Comment by AudriusButkevicius** [comment]
Ask the other peer to unshare it with you. Simple as that.

**Comment by Pr0Wolf29** [comment]
What if I don't have any way of contacting them?

**Comment by uok** [comment]
you could put a text file in the folder explaining what they need to do and hope they read it :smile:

**Comment by AudriusButkevicius** [comment]
I had this feature implemented when I was adding the popups, but whoever was involved agreed that we don't need this.

**Comment by Pr0Wolf29** [comment]
I suppose I'll just have to add others to myself rather than the other way around if you're not interested in adding this feature. That's the only workaround for not having a block button added.

**Comment by calmh** [comment]
I was the one opposing, as this is a misconfiguration and having an ignore button here would be the Wrong Thing in my opinion. I'm not convinced I was wrong. :)
