### ISSUE TITLE
need to define a folder for .stfolder and .stignore

### ISSUE THREAD

**Issue by rowlar** [syncthing/syncthing#1940]
using fusefs-encfs on freebsd in the reverse mode:

encfs --reverse --public /mnt/p1/pmax/dec /mnt/p1/pmax/enc

where /dec is the decrypt and /enc is the virtual encrypted folder and i try to sync /enc.

i got the problem that syncthing is not able to open its folders. the fusefs-encfs system does not allow this. ZFS also is not able to establish its .zfs folder for snapshorts. Normal copy of the files is possible.

Can not use syncthing for backup my encrypted data in the cloud.

**Comment by AudriusButkevicius** [comment]
I guess the two are not compatible in that case.

**Comment by calmh** [comment]
This is basically #1126.
