### ISSUE TITLE
Anonymous public sharing

### ISSUE THREAD

**Issue by jkufner** [syncthing/syncthing#1942]
It would be nice, if Syncthing could be used as infrastructure to distribute Open Street Maps for Osmand. To achieve this a device ID configuration have to be avoided or automated.

There should be some public identifier (like a magnet link) which would describe a resource and this resource would be shared among everyone. To make sure that only autor is the one publishing the resource, a signing mechanism (GnuPG) has to be mandatory.

In contrast with Bittorrent magnet link, the public identifier should not describe one particular version of a resource, but a resource which can be updated. So user will enter identifier of a map package and download it. Later, whem map is updated (and user presses sync button), the change is detected and old local version is updated to the author's version.

  - [Osmand Google Group thread where need for this feature emerged](https://groups.google.com/d/msg/osmand/u_TvQzC2sLg/yjU7kXVWfqUJ)

**Comment by calmh** [comment]
This won't be fixed in Syncthing as it fits quite badly with the current architecture and protocol. A well thought out proposal to change things so that it *does* fit will of course be entertained and considered, but be aware that that is quite a lot of work. Sorry.

**Comment by jkufner** [comment]
Ok. As I understand syncthing, this feature would require to distribute device IDs and their keys, make author's device read-only and add GnuPG verification to check that downloaded file is genuine. Is there some additional obstacle?
