### ISSUE TITLE
ARMEL (5) binary segfault / build direct works / build cros-comp error use GOARM=5 etc.

### ISSUE THREAD

**Issue by father-mande** [syncthing/syncthing#1944]
Hi,

I use, usually, the binary provide by the team ...
 up to now (suppose 0.11.x I don't remember) all run as well on ARMEL 5 and ARMHF 7 models 
now I have : for armel (arm binary in this site) GOARM=5 : seg fault ???
so I decide to create binary myself ... install GO 1.4.1 on Debian8 (AMD64 (or 386) I have tested the two) install is from source NOT from Debian repo ... some error seem to exist (1.3.3) ...
generate 386 (static)  amd64 (shared lib ... host system) linux binary : work
generate ARM 7 (static) linux binary : work
generate ARM 5 just change GOARM : exec (static) fall ... please use GOARM=5 etc. etc. build is for ARMHF ??? retry multiple time no more success
try on an ARMHF system ... EXACTLY the same result 
AT END I use my armel system : 
generate native shared lib ARM 5 : work as planned ...
generate static i386 / amd64 / ARMHF (change only GOARM for it) : ALL works

QUESTION : do you have any idea about this problem :
1 Why now the arm binary can't run on armel (only on armhf) ? (seg fault)
2 why go cross-compile can't generate armel GOARM=5 ... but ignore and generate ARMHF (7) binary ?

... this is for syncthing and syncthing-notify (nor syncthing-cli BUT it's because they don't provide binary for ARM)

Is it a go version problem ? BUT I don't have problem with other tools (ex. drive for accessing google drivre from a console)
Why old version (arm) work as well on the two ARMEL and ARMHF and now ... no more ? did you change somethings in generation OR is it inside ???

This not a blocking problem ... I have multiple platforms to generate multiple version ... but sure it's better for me (and for users that use my binary) to trust the supplier (you before) than me (now) and to use your binary as is ...

Philippe. (Integrator of syncthing on QNAP)

**Comment by calmh** [comment]
Are you testing the binaries downloaded from Github or the Debian packages? I don't exactly follow the above, but I think the summary is that our ARM binary does not work, but the source compiled *on* an arm5 box does work? Also, can you post the actual crash output?

**Comment by father-mande** [comment]
Hi,

Sorry if I don't explain clearly  : 
The binary downloaded from syncthing.org for arm don't work on armel : 
======== here the console =====
 # ./syncthing
Illegal instruction
 # file syncthing
syncthing: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, not stripped
 # ldd syncthing
        not a dynamic executable
============================
Binary created on a 386 using cross-compile GOOS=linux GOARCH=arm GOARM=5
generate an error : this binary is for ARMHF please use GOARM=5 to generate etc. etc. ... 
I don't keep the exact message but it's like this ... multiple tests ... same

test of generated syncthing on armhf (QNAP TS-431+) ... run fine

Binary created on an Linux Armel system with go 1.4.1
=============================
[/share/Public/new_go/go_app/src/github.com/syncthing/syncthing/bin] # uname -a
Linux NAS219II-aphil 3.4.6 #1 Fri May 22 07:56:30 CST 2015 armv5tel unknown
./syncthing --help
Usage:
  syncthing [options]

Options:
  -audit                  Write events to audit file
etc. etc. etc.
================================

Same problem when generating syncthing-inotify

It is more clear ... I have no idea about the origin ... and as I said ... I have a workaround (an true armel plateform to test) so it's not a blocking problem ... I just try to understand why ...

The Debian ref. is just to said that I don't use the go 1.3.3 provide in debian8 ... because I don't be able to use it ??? ... so (as before) I generate the go compiler myself from source ... so using 1.4.1
=============== My go env ==============
root@NAS219II-aphil:/# go env
GOARCH="arm"
GOBIN=""
GOCHAR="5"
GOEXE=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/share/Public/new_go/go_app/"
GORACE=""
GOROOT="/share/Public/new_go/go"
GOTOOLDIR="/share/Public/new_go/go/pkg/tool/linux_arm"
CC="gcc"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
root@NAS219II-aphil:/# uname -a
Linux NAS219II-aphil 3.4.6 #1 Fri May 22 07:56:30 CST 2015 armv5tel GNU/Linux
root@NAS219II-aphil:/#
==============================================

Philippe.

**Comment by father-mande** [comment]
Hi,

OUPSS! I don't know how I generate large/bold/text ??? sorry and apologize

Philippe.

**Comment by jkufner** [comment]
There is edit button next to your comment.  And preview tab above text
area when editing ;)

**Comment by father-mande** [comment]
Hi,

Yes ... thanks ... I am a little busy ... and take no time to read the page ... again sorry and apologize ...

Philippe.

**Comment by calmh** [comment]
We make sure to build everything with GOARM=5 so I'm not sure why this happens.

**Comment by father-mande** [comment]
Hi,
Ok ... not a problem .. I will check again next release ... thanks for your help ...
Next release I will check myself ... I provide a package for QNAP's system ... with amd64, 386, armhf and armel ... and I don't fall in this case before ... so perhaps it's my error ... and for some model (small armel) I don't use it really for my own usage ... so return comes from others users ... on QNAP.
BUT ... I will prepare a full check next time ... and go back to you with result ... if I fall again ...

In all case I am able to rebuild the binary ... because I always rebuild a static version for amd64 (your is with shared libs) ... and unfortunately auto-update fail due to an incorrect level of libraries (in QNAP's Linux)... so static solve the problem (for one update each time) for people that don't want to wait for my package and want to run update quickly ... but it's not your fault ... it's a plate-form problem.

Thanks again, Appreciate your job. Best regards.
Philippe.

**Comment by Zillode** [comment]
Yeah, don't forget to build Go with `GOARM=5` and `GO386=387` as well. Please reopen if you observer the problem again.
