### ISSUE TITLE
Provide Information About Location of Symlinks

### ISSUE THREAD

**Issue by andreasguther** [syncthing/syncthing#1945]
# Symlink Warning Improvement Suggestion

See also discussion in forum: https://forum.syncthing.net/t/symlinks-are-disabled-unsupported-or-require-administrator-privileges/2826
## Warning message in Web UI

Symlinks are disabled, unsupported or require Administrator privileges. This might cause your folder to appear out of sync.
## Improvement Suggestion

It would be great to know exactly where those Symlinks were found to rectify the problem if needed or wanted. The Warning should list all Symlinks found either inside the warning or on a linked page or a subsection that can be expanded.

**Comment by calmh** [comment]
Rendered moot by the removal of symlink support on windows (symlinks are always enabled on other platforms)
