### ISSUE TITLE
panic: leveldb/table: corruption on data-block (pos=1159571): checksum mismatch, want=0x5484f308 got=0x73091003 [file=008932.ldb]

### ISSUE THREAD

**Issue by fbatogo** [syncthing/syncthing#1949]
I have been getting the above line on the console recently.   It causes Syncthing to restart 3 times rapidly, and then give up.

The Syncthing instance in question is running on an Odroid C-1 (small ARM device similar to Raspberry Pi).   The machines it is syncing with are several different Windows machines, mostly running Win 7, one or two Linux machines, and a couple of Nexus 5 phones.   I am not entirely sure when this started happening as I just noticed today that things weren't syncing anymore.    However, I am wondering if it is happening because not all of the devices in use are upgraded to the latest version of Syncthing.    The Android devices get the new version pushed to them automatically, but I have not upgraded the Linux or Windows devices yet because I lacked the time to upgrade all of them at the same time.   (It will probably take me some time to get them all upgraded even now.)

Oh, one tidbit of information that may or may not be useful.   The ODroid has the syncthing data currently stored on a 64 gig SD card.   I know those cards can lose data almost at random, so if the error seems to indicate that a file has changed when it shouldn't have, then that is certainly a possibility.

Please let me know if there is any additional information that I can provide.    I am a developer myself, so I know that it can be useful to ask questions but sometimes it is hard to find people that are willing to take the time to answer or do things to test.   I am willing to help where I can.

Thanks!

Github doesn't seem to want to let me post the log, so here is a copy/paste of it : 

[IDAEL] 18:58:50 INFO: syncthing v0.10.30 (go1.4.2 linux-arm default) unknown-user@syncthing-builder 2015-03-29 07:46:44 UTC
[IDAEL] 18:58:50 INFO: My ID: IDAELJJ-RFY2E2P-VDWAUZY-CHFKQ4U-PXGYGZ5-PZK36X3-KWX4DBH-BIPDUQJ
...
Panic at 2015-06-14T18:58:50Z
panic: leveldb/table: corruption on data-block (pos=1159571): checksum mismatch, want=0x5484f308 got=0x73091003 [file=008932.ldb]

goroutine 1 [running]:
github.com/syncthing/syncthing/internal/db.ldbCheckGlobals(0x10a3e620, 0x10a386b0, 0xa, 0x10)
	/go/src/github.com/syncthing/syncthing/internal/db/leveldb.go:1020 +0x91c
github.com/syncthing/syncthing/internal/db.NewFileSet(0x10ab9374, 0xa, 0x10a3e620, 0x10ae2cdc)
	/go/src/github.com/syncthing/syncthing/internal/db/set.go:56 +0x174
github.com/syncthing/syncthing/internal/model.(*Model).AddFolder(0x10a32900, 0x10ab9374, 0xa, 0x10aba120, 0x26, 0x10a40270, 0x3, 0x4, 0x0, 0x258, ...)
	/go/src/github.com/syncthing/syncthing/internal/model/model.go:1046 +0x160
main.sanityCheckFolders(0x10a48ea0, 0x10a32900)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:686 +0x104
main.syncthingMain()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:479 +0x1698
main.main()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:251 +0x1bc0

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1c
created by os/signal.initÂ·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x40

goroutine 7 [select]:
github.com/syncthing/syncthing/internal/events.(*Subscription).Poll(0x10a37040, 0xf8475800, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:173 +0x340
github.com/syncthing/syncthing/internal/events.(*BufferedSubscription).pollingLoop(0x10a34450)
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:209 +0x40
created by github.com/syncthing/syncthing/internal/events.NewBufferedSubscription
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:203 +0x1f4

goroutine 8 [chan receive]:
main.trackCPUUsage()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0x120
created by main.initÂ·3
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x34

goroutine 9 [chan receive]:
github.com/syncthing/syncthing/internal/config.(*Wrapper).Serve(0x10a48ea0)
	/go/src/github.com/syncthing/syncthing/internal/config/wrapper.go:79 +0x54
created by github.com/syncthing/syncthing/internal/config.Wrap
	/go/src/github.com/syncthing/syncthing/internal/config/wrapper.go:54 +0x12c

goroutine 10 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x10a60000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x1d4
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236 +0x23c

goroutine 11 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0x10a3e620)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:153 +0x254
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:122 +0x82c

goroutine 12 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0x10a3e620)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_state.go:73 +0x124
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:122 +0x854

goroutine 14 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0x10a3e620)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:759 +0x248
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:122 +0x8d4

goroutine 15 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0x10a3e620)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x17c
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:122 +0x8fc

goroutine 16 [select]:
github.com/syncthing/syncthing/internal/model.(*ProgressEmitter).Serve(0x10ae8960)
	/go/src/github.com/syncthing/syncthing/internal/model/progressemitter.go:48 +0x724
created by github.com/syncthing/syncthing/internal/model.NewModel
	/go/src/github.com/syncthing/syncthing/internal/model/model.go:117 +0x5c4

goroutine 33 [sleep]:
github.com/syncthing/syncthing/internal/model.funcÂ·029()
	/go/src/github.com/syncthing/syncthing/internal/model/util.go:17 +0x70
created by github.com/syncthing/syncthing/internal/model.deadlockDetect
	/go/src/github.com/syncthing/syncthing/internal/model/util.go:35 +0x100

goroutine 34 [sleep]:
github.com/syncthing/syncthing/internal/model.funcÂ·029()
	/go/src/github.com/syncthing/syncthing/internal/model/util.go:17 +0x70
created by github.com/syncthing/syncthing/internal/model.deadlockDetect
	/go/src/github.com/syncthing/syncthing/internal/model/util.go:35 +0x100

goroutine 35 [select]:
github.com/syncthing/syncthing/internal/ignore.(*Matcher).clean(0x10af7500, 0x61714000, 0x68c)
	/go/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:153 +0x1cc
created by github.com/syncthing/syncthing/internal/ignore.New
	/go/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:53 +0xe0

goroutine 36 [select]:
github.com/syncthing/syncthing/internal/ignore.(*Matcher).clean(0x10aba390, 0x61714000, 0x68c)
	/go/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:153 +0x1cc
created by github.com/syncthing/syncthing/internal/ignore.New
	/go/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:53 +0xe0

**Comment by calmh** [comment]
This indicates the database is corrupt. This seems to usually be due to bad hardware - bad memory or bad disks. Check the disk that the index (~/.config/syncthing) lives ion, primarily. As a workaround, remove the index-v0.11.0.db directory inside that directory to clear out the database.

There are already other issues on this, so I'm closing this one as a duplicate.
