### ISSUE TITLE
'Add Device' button is overlapped by footer if 767px< width <1000px

### ISSUE THREAD

**Issue by Donlow** [syncthing/syncthing#1950]
Firefox is resized to half of 1920x1080 screen.

![screenshot](https://cloud.githubusercontent.com/assets/12888718/8152406/d0021866-1346-11e5-8b66-d77024557b9a.png)

I suggest change overrides.css:248
@media (max-width: 767px) {
to
@media (max-width: 1000px) {

**Comment by calmh** [comment]
Yeah, should hide the bottom bar or some of it's links earlier.
