### ISSUE TITLE
0.11.9 RPMS for Centos 6/7

### ISSUE THREAD

**Issue by daniel-lucio** [syncthing/syncthing#1961]
Please enjoy

rpm -ivh http://repo.okay.com.mx/centos/6/x86_64/release/okay-release-1-1.noarch.rpm? for 64 bits Centos 6
rpm -ivh http://repo.okay.com.mx/centos/7/x86_64/release/okay-release-1-1.noarch.rpm? for 64 bits Centos 7

yum install syncthing

**Comment by calmh** [comment]
"okay-release-1-1"? What's this? :)

**Comment by calmh** [comment]
Ah, it adds a source? Anyway, pull request on https://github.com/syncthing/docs, users/contrib.rst ?
