### ISSUE TITLE
Duplicated offsync-files not counted

### ISSUE THREAD

**Issue by Black-LotusCY** [syncthing/syncthing#1971]
Scenario:
- 1x "Server" (master)
- 2x "clients".
All Files are in sync.
Then i delete file A on client 1.
On server (screenshot) it shows "1 Entry ~128 B" is out of sync.
Now i delete the SAME file on client 2.
The status on server never changes. It stays on ONE file being out of sync.
For testing: If i now delete another file on client 1 or 2, the status changes to TWO files being out of sync.
This is reproducable.
![bug1](https://cloud.githubusercontent.com/assets/12686187/8235133/79946aa0-15e0-11e5-9f78-a7c1afec4095.png)
I would count this a bug, since it does matter, if a (big) file is out of sync on one devicee or 100 devices.

**Comment by AudriusButkevicius** [comment]
It's still one file missing in the global dataset, regardless of the fact that two devices have removed it.
This is not a bug, and working as intended, in the sense of comparing global state to local state.
Two different files will show up as two.
