### ISSUE TITLE
Automatic overwrite changes

### ISSUE THREAD

**Issue by Black-LotusCY** [syncthing/syncthing#1972]
Scenario is 1 "Server", 2 "clients".
If files on clients are deleted/changes/addet, these changes have to be overwritten by "server" and by hand.
There should be an option, so server does not have to "override changes" every time.
Made 2 solutions in my screenshot, left top is original.
![bug2](https://cloud.githubusercontent.com/assets/12686187/8235813/778a3b6e-15e4-11e5-879a-e781ed893a82.png)

The dirty solution would be to trigger this by chronjob over API, but there should be an direct option in my opinion.
Didn't find anything about this in your GIT-archive, sorry if duplicated.

**Comment by AudriusButkevicius** [comment]
If you by accident have 2 masters with this enabled, I bet you can work out what effect this has.

**Comment by uok** [comment]
I'm also missing this setting...
@AudriusButkevicius: does device B know that device A is set as folder master? if yes, then there could be a simple check to avoid opening a wormhole and deleting the universe

**Comment by AudriusButkevicius** [comment]
It doesn't.

**Comment by Black-LotusCY** [comment]
@AudriusButkevicius : I don't see the difference between having something automated, that can be just triggered.
If there should be a problem with 2 masters, then this problem is existent at this moment too.
If Master A and B do have writeprotection AND different files, they will never get in 100% sync, am i correct?
So it would be ok to display such situation like "can't overwrite files in node (master?)". But as i wrote above, this is something that can be triggered by API or automated mouseclicks though. So i don't get your point there. Could you tell me some difference in automated and not automated overrides?

**Comment by AudriusButkevicius** [comment]
The problem is non-existent now, because you have to manually click the button for the override to happen.
In the case where you have two masters with this write protection enabled, you can imagine that A overwrites files, then B looks that A overwritten the files, overwrites them back, which then again causes A to overwrite them back, causing an endless loop consuming all of your internet traffic.

**Comment by calmh** [comment]
At the very least this is a duplicate. The use case is valid but I think this is the wrong way of solving it. My order of preference would be to solve this with file permissions on the slave side (syncthing can update files, user cannot, hence situation cannot arise), or as a special "slave" mode that syncthing doesn't currently have. That mode would never send updates for changes files and would cause it to be in socially evil about undoing any changes you do...

**Comment by Black-LotusCY** [comment]
@calmh I am currently using btsync in our company, but we are thinking about an alternative tool, like syncthing.
Our use-case is a central server, that syncs files to the other nodes. Our server has the master-key (btsync), and the nodes only get the readonly-key. Like this, it is working as we want to. If a user deletes a file on a node, it gets synced there again, so the files is there again after a few minutes or so.
A slave-option on a client (syncthing) would be nice and it was discussed in other issues before. This way a client could freely decide on its own to just become a slave-device.
I may look into the code, if this is easy to implement but since i just started to experience both syncthing and github, i may not be the best to do this :/

**Comment by Zillode** [comment]
>  I may look into the code, if this is easy to implement but since i just started to experience both syncthing and github, i may not be the best to do this :/

I think this is a good use case to get started:)

Have a look at [rofolder.go](https://github.com/syncthing/syncthing/blob/b8b5c5ff348c3328d1295a2e1d719f9a97c50ad6/internal/model/rofolder.go#L110). This is a master folder receiving index data from a remote device. Currently this is being ignored, hence the read-only behaviour. If you would bump the local version number of the files that were changed, I think the changes will be propagated back to the remote device and thus implement the behaviour you envision. (See [rwfolder.go](https://github.com/syncthing/syncthing/blob/b8b5c5ff348c3328d1295a2e1d719f9a97c50ad6/internal/model/rwfolder.go#L309) and maybe [here](https://github.com/syncthing/syncthing/blob/b8b5c5ff348c3328d1295a2e1d719f9a97c50ad6/internal/model/model.go#L1124))

**Comment by calmh** [comment]
Or, alternatively, we want the scanner to do the inverse of `Override()` in model.go. When it detects a local change, it resets the local `Version` to essentially zero, making sure we are out of date and refetch from the cluster.
