### ISSUE TITLE
Allow only one Folder Master per folder

### ISSUE THREAD

**Issue by plouj** [syncthing/syncthing#1974]
I feel that syncthing should allow at most one Folder Master per folder. Are there any scenarios where having two or more masters makes sense? It seems that limiting to just one master would avoid a whole lot of cases where things get deleted or synced unexpectedly. Plus it would remove the need for an "override changes" button and dealing with issues like #1972. Am I missing something?

**Comment by AudriusButkevicius** [comment]
If it's only one, which one? Who decides?
The setting is down to the individual user, how are you going to enforce only one when there is no central authority and everything is peer to peer?

**Comment by plouj** [comment]
Given the current trust model where the users of each device trust the other devices they connect to I see it working like so: The first person creating the folder enables the FolderMaster flag. When another device automatically discovers and adds that folder it notices the FolderMaster flag enabled and only receives changes from the originating device and does not send anything back. If a person creates a folder and enables FolderMaster, but when that folder is connected to another folder on a different device which already has FolderMaster enabled the pairing/syncing should fail and the user should be told to resolve the conflict (by enabling FolderMaster only in one place). Are there any problems with this approach?

**Comment by AudriusButkevicius** [comment]
What you are saying also causes DoS.
I have 2 friends (A, B) which sync my master folder.
Accidently B sets the folder to master, what does A do? Trust me or trust B?

Also it's not always exclusively 1 to 1 topology.
How does it work with nodes A, B, C and D and topology (no other connections apart from the ones shown):
A <-> B <-> C <-> D
where A and D have the folder set to master.

**Comment by plouj** [comment]
I think to avoid your scenario syncthing will need to be changed to not allow changing the FolderMaster flag for a folder after it has been created and shared with other devices. Plus a folder with FolderMaster=true should never receive changes from other copies of the folder on other devices. This is similar to how btsync deals with it by encoding the read-only status of a folder in the folder id (URI)

I think it's actually possible to allow changing the FolderMaster flag after a folder has been shared, but thinking about it and implementing it in code is too confusing and not worth the effort. It's much better to expect users to re-create folders with the desired FolderMaster flag from scratch.

Here's a more clear explanation of how I see things working:

#### Normal scenario
1. User A creates a folder ShareX on device MachineM and sets FolderMaster=true for it
2. User A allows device MachineP access to ShareX
3. MachineP notices a new folder ShareX from MachineM and prompts user B to add it. MachineP also automatically notices that MachineM is the master for ShareX so it prevents its own copy of ShareX from sending changes back to MachineM.
4. MachineP does not give user B an option to set FolderMaster=true for his copy of ShareX

#### Race condition scenario

1. User A creates a folder ShareX on device MachineM and sets FolderMaster=true for it
2. User A allows device MachineP access to ShareX
3. MachineP notices a new folder ShareX from MachineM and prompts user B to add it.
4. (this is where things are different) user B ignores the notification about ShareX
5. Later, user B creates ShareX and sets FolderMaster=true for it
6. Then user B shares ShareX with MachineM
7. MachineP contacts MachineM and notices that MachineM is already the master for ShareX and user B gets an error message and pairing fails
  * A malicious MachineP might ignore the fact that MachineM is the master and proceed to setup the pairing, but MachineM, being the master for ShareX will refuse to receive any changes from any of the other devices.

(User A and B can be the same person, but they don't have to be)

**Comment by dcarosone** [comment]
I think we need a better name than Master Folder to express the current
concept and implementation. A name that reflects it as a local policy, even
though one possible use is to implement a master source among a group of
collaborating peers. Read Only folder is closer, but also problematic.

Maybe Send Only Folder?

Your concept of a master folder is then a separate discussion for a new
feature.

**Comment by AudriusButkevicius** [comment]
Well, how does the normal scenario work in the scenario I've described?

**Comment by plouj** [comment]
Point 4. in the Normal Scenario shows how your friend B will not be allowed to set FolderMaster=true for his copy. That option won't even be available in his GUI to accidentally toggle.

**Comment by AudriusButkevicius** [comment]
Yeah, but C will be able to, so will D.

**Comment by bigbear2nd** [comment]
@AudriusButkevicius I think the same information distributing mechanism we discussed in #863 could also be used here.

**Comment by plouj** [comment]
@AudriusButkevicius: Good point. I'm going to post another potentially better approach.
