### ISSUE TITLE
Entering a large number into the renew interval of a share cause Syncthing to crash on startup

### ISSUE THREAD

**Issue by wvdschel** [syncthing/syncthing#1978]
When entering a large enough value (I tried `60000000000`) into the rescanIntervalS property of a shared folder, Syncthing will crash during startup with the following message:

     panic: invalid argument to Int63n

Which is presumably triggered by [this piece of code](https://golang.org/src/math/rand/rand.go#L61) when generating a random number during startup to decide when to perform the initial scan of the folder. (I'm guessing, I don't know Go and I don't know how Syncthing handles startup)

This issue can be reproduced by directly editing config.xml or by changing the value through the web UI, and will be triggered upon the next start up.

I've only tested this on v0.11.9, Linux (64 bit).

**Comment by bigbear2nd** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/7719800/8257885/0a8ac592-16b1-11e5-97c8-448833aac9c6.PNG)
Woah...

**Comment by wvdschel** [comment]
I usually set intervals to ~1 year. I use syncthing-inotify instead.

I have around 40GB of small files in ten or so shared folders, and when I keep intervals low it just brings on so much CPU load.

Regardless, the software should be robust against valid if non-sensible user input, and either handle this correctly and/or enforce some upper limit.

**Comment by Zillode** [comment]
```
  1 [AE3XN] 13:54:50 INFO: syncthing v0.11.9+39-gb8b5c5f-dirty (go1.4 linux-amd64 default) lhoste@mb5-btrfs 2015-06-20 09:43:05 UTC
  2 [AE3XN] 13:54:50 INFO: My ID: AE3XNYF-BMEVD64-RFEHXGG-WVLRSEY-GSG7IFD-BMV6M3R-B3XGTW3-QWVWJQQ
  3 [AE3XN] 13:54:50 INFO: Database block cache capacity 15989 KiB
  4 [AE3XN] 13:54:50 INFO: Starting deadlock detector with 20m0s timeout
  5 [AE3XN] 13:54:50 OK: Ready to synchronize default (read-write)
  6 [AE3XN] 13:54:50 OK: Ready to synchronize ewew (read-write)
  7 [AE3XN] 13:54:50 INFO: Starting web GUI on https://127.0.0.1:8384/
  8 ...
  9 Panic at 2015-06-20T13:54:50+02:00
 10 panic: invalid argument to Int63n
 11
 12 goroutine 20 [running]:
 13 math/rand.(*Rand).Int63n(0xc20800a300, 0x8155a43676e00000, 0x101)
 14 »·/opt/go/src/math/rand/rand.go:61 +0x74
 15 math/rand.Int63n(0x8155a43676e00000, 0xa)
 16 »·/opt/go/src/math/rand/rand.go:185 +0x34
 17 github.com/syncthing/syncthing/internal/model.func·017()
 18 »·/data/Sync-Projects/golang-workspace/src/github.com/syncthing/syncthing/internal/model/rwfolder.go:157 +0x68
 19 github.com/syncthing/syncthing/internal/model.(*rwFolder).Serve(0xc20806a200)
 20 »·/data/Sync-Projects/golang-workspace/src/github.com/syncthing/syncthing/internal/model/rwfolder.go:292 +0x1c2a
 21 created by github.com/syncthing/syncthing/internal/model.(*Model).StartFolderRW
 22 »·/data/Sync-Projects/golang-workspace/src/github.com/syncthing/syncthing/internal/model/model.go:192 +0x5df
 23
```
(RescanIntervalS is an int, but a duration only supports int64: "The representation limits the largest representable duration to approximately 290 years").
