### ISSUE TITLE
Ignore patters not editable from "remote" client

### ISSUE THREAD

**Issue by sisu4syncthing** [syncthing/syncthing#1980]
short question:
Is there a special reason, why it's not possible to edit an Ignore Pattern list from a computers browser, where the syncthing install is not local, or can this be considered as a bug?

long explanation:
-Computer A with installed syncthing v0.11.9, Windows (64 bit), FireFox 38.0.5 browser and tab with URL http://ip_to_computer_B/ pointing to computer B.

-Computer B with installed syncting v0.11.9, Mac OS X (32 bit)

-ip_to_computer_A is 192.168.1.10:8384
-ip_to_computer_B is 192.168.1.20:8384

When trying to edit the Ignore Pattern list of any configured and already saved folder from computer B using the browser from computer A, the Ignore Patterns-button is greyed out and not clickable.
(glitchy behaviour btw: sometimes the button clickable, but with no result other than greying that button out after the click)

What I expected to happen: 
Ignore Patterns List would open up and be editable in the browsers window.

When on computer B with same browserversion, using the webgui via URL ip_to_computer_B or 127.0.0.1:8384 everything works as expected (list opens and user can edit).

Summary:
its not possible to edit an Ignore Pattern list of another syncthing installation from another computer in the LAN. Only from the Computer, where the synthing installation is local.
Other settings, such as File Versioning or Pull Order are editable.

My feature request:
Let user change the whole configuration of syncthing from any computer.

**Comment by Zillode** [comment]
Are you aware that opening two Syncthing sessions in the same browser is not supported? (See the [faq](http://docs.syncthing.net/users/faq.html?highlight=CSRF) and [this issue](https://github.com/syncthing/syncthing/issues/720) and [this PR which I still need to update](https://github.com/syncthing/docs/pull/11))

**Comment by sisu4syncthing** [comment]
Yes, I opened up a new instance of Internet Explorer to basicly verify its not a FireFox issue. 
I Just copied the URL form FF into IE and it has the same effect.
Thanks for your respond and linking.

**Comment by Zillode** [comment]
Right, I just tested this and it seems this is a bit glitchy indeed. However it does work:
After you've clicked Ignore Patterns, it becomes greyed, which means something opened. Apparently the dialog opens a bit slow and is (for some reason) opened in the background. If you click next to the folder setting dialog (so on the greyed background on the main gui), it will show the ignore patterns form.

**Comment by sisu4syncthing** [comment]
I tried, what u've been telling, but having problems to understand, I guess.

Can you explain it in other words, or add a screenshot for "If you click next to the folder setting dialog (so on the greyed background on the main gui), it will show the ignore patterns form." ?

When I have the Edit Folder window open and click on the greyed background, I just end up in the main overview screen of the WebGui. No Ignore Pattern List is opened. (This happens when I clicked the Ignore Patterns-Button after it was greyed out, or was greyed out already, when I entered the Edit Folder window)

**Comment by Zillode** [comment]
```When I have the Edit Folder window open and click on the greyed background, I just end up in the main overview screen of the WebGui.```
For me this opened the ignore patterns form, maybe you need to wait a bit longer to make sure it is loaded.
Anyway, I believe this is a bug and needs to be investigated. For the moment, simply use a commandline text editor (nano/vim) to edit a remote .stignore file.

**Comment by ralder** [comment]
in your case this behavior is caused by http request for getting ignores takes very long time or return error and we in webgui have not good handle this case. Think need after click button Edit Ignores show modal for ignores without waiting response and show loading image in textarea while not given response

**Comment by sisu4syncthing** [comment]
@Zillode: The saved changes from the editor will be loaded into syncthing automaticly without any doing from me?

**Comment by Zillode** [comment]
.stignore gets reloaded when rescanning the folder.

**Comment by calmh** [comment]
What's the bug here? That the modal isn't displayed until we've loaded the patterns?

**Comment by AudriusButkevicius** [comment]
I think this was fixed by @canton7 it was something todo with opening a second modal on top before closing the first one. Can someone still reproduce this on master?

**Comment by canton7** [comment]
> the Ignore Patterns-button is greyed out and not clickable

I don't think it is...

**Comment by AudriusButkevicius** [comment]
So the bug is that we try to get the ignores and get a non-200 which keeps the button grayed out. Could be due to the race condition of starting a folder. I'd close unless the OP can still reproduce on master.

**Comment by canton7** [comment]
Dup of #2063 maybe?

**Comment by sisu4syncthing** [comment]
@AudriusButkevicius  "reproduce on master"

sorry for not knowing the maybe obvious, but how can I assure, I re-test with the correct version?

I'm on autoupdate and my versions show v0.11.16. Is this the version, I can re-test, or what exactly is a master?

**Comment by AudriusButkevicius** [comment]
Can you reproduce it on the latest release?

**Comment by sisu4syncthing** [comment]
seems to work from all OS-instances to other OS-instances.

So a "master" is the latest version? Ok.

**Comment by AudriusButkevicius** [comment]
master is the development version, ala master branch in git.
