### ISSUE TITLE
Main application screen, The folders list sometimes displays negative percentage.

### ISSUE THREAD

**Issue by maks-us** [syncthing/syncthing#1984]
Mac OSx 10.10.3 
I installed syncthing from brew   v0.11.9, Mac OS X (64 bit)

The issue is minor. It have no effect on functionality. 

The issue reproduction :
1) Create a folder and sync the folder between 3+ mac computers 
2) Restart the the application and mac A and add some files to mac B 
3) When application just restarted and it begins to sync more then two computers it displays sync status for some seconds with negative % . More files to sync then bigger negative %. When it begin syncing then it begin count from 0% as normal syncing process. 
![screen shot 2015-06-20 at 9 33 30 pm](https://cloud.githubusercontent.com/assets/8204705/8270020/8d1bba2c-1795-11e5-8cb7-0730e3073fbe.png)

Thank you for great application.

**Comment by fti7** [comment]
https://github.com/syncthing/syncthing/issues/1759
