### ISSUE TITLE
Mac OSx external HDD issue. 

### ISSUE THREAD

**Issue by maks-us** [syncthing/syncthing#1986]
Mac OSx  10.10.3 

The issue reproduction 

1) create a sync folder in external HDD   (  /Volumes/1tb/sync/docs )
2) run Synching 
3) disconnect HDD 
4) run Synching. The application will create the folder with disk name /Volumes/1tb/
5) mount the disk . The disk become mounted to another  /Volumes/1tb 1/  
6) Synching couldn't find the files. 

I solve it by unmounting HDD, deleting /Volumes/1tb/ folder and mounting the HDD. 
It is necessary to do quick. I believe it would create the folder for next directory scan. 

Thank you.

**Comment by AudriusButkevicius** [comment]
Syncthing should only create /Volumes/1tb/sync/docs not /Volumes/1tb, and it should only create it if syncthing never seen files before.

**Comment by AudriusButkevicius** [comment]
Actually you are right, this can be an issue.

**Comment by maks-us** [comment]
thank you

**Comment by AudriusButkevicius** [comment]
This might still happen due to #1997
