### ISSUE TITLE
Syncing between two nas4free-systems (FreeBSD): ST changes owner to root at target

### ISSUE THREAD

**Issue by rowlarx** [syncthing/syncthing#1987]
Source and target directories have both the same owner, group, UID and GID (just for test).
Tried it with several configurations and also reinstallation of syncthing.

The receieved files are unuseable opening the directory via CIFS.

**Comment by Zillode** [comment]
Dup of https://github.com/syncthing/syncthing/issues/1329?

**Comment by calmh** [comment]
Syncthing does not sync or change ownership - files will be owned by the user running Syncthing.

**Comment by rowlarx** [comment]
Unuseable for far away systems.

**Comment by calmh** [comment]
Huh?

**Comment by rowlarx** [comment]
Think about a backup at my friends home. Open the files via openVPN, NFS ore anything else. Or the mobile devices? The files are in the cloud but they are still my files.
Also i open the target full with encrypted files with EcFSMP (encfs4win do it too) across the systems.
After a chown this runs like a charm.

**Comment by calmh** [comment]
> files will be owned by the user running Syncthing.

Run Syncthing as the user that is supposed to own the files. Like any other service.

**Comment by rowlarx** [comment]
For several users? Do you mean the sender or the recevier? Maybe i have no influence to the recevier.

**Comment by rowlarx** [comment]
Also i am thinking about asolution similar to this solutions:
http://lists.freebsd.org/pipermail/freebsd-questions/2014-June/258824.html

Storing my (encrypted) files at dropbox or S3.

**Comment by calmh** [comment]
Syncthing is currently inherently single-user. I'm not sure what the other thing is about, sorry.
