### ISSUE TITLE
ST not able to re-use existing temp data from another ST instance

### ISSUE THREAD

**Issue by lblblb** [syncthing/syncthing#1991]
Hi,
I have downloaded part of a 5GB file on a linux ARM machine and wanted to resume the same file download on my Windows 7 x64 machine. I did the following:
1. Stopped sharing the folder on Syncthing #1 on Linux, to stop the download
2. Moved the temp file from Linux system to Windows
3. Restarted Syncthing #2 on Windows
4. Syncthing #2 now re-downloads the whole file without using the existing temp data.

Is this behaviour a bug or a feature?

**Comment by AudriusButkevicius** [comment]
Temp file naming is different between Linux and Windows, if you would have crafted the right name, it would have worked.
