### ISSUE TITLE
Versioning local edits?

### ISSUE THREAD

**Issue by singpolyma** [syncthing/syncthing#1992]
syncthing has features to allow keeping old versions of files that were changed remotely, but it is configured per-host, and does not count changes made locally before sending, only received changes.  It would be nice if there were a single, consistent, history that is sync'd along with the folder.  It seems that storing the version information in the folder, and configuring versioning on every host the same way, will have close to this effect -- but why not allow syncthing to version changes before it sends them as well as when it receives them?

**Comment by dcarosone** [comment]
Are you sure you don't want a DVCS instead.

That's not meant to be a cheeky comment, just pointing out that this desire
may be a clue that you want a different use case more suited to a tool for
tracking changes. :)

On 23 June 2015 at 08:49, Stephen Paul Weber <notifications@github.com>
wrote:

> syncthing has features to allow keeping old versions of files that were
> changed remotely, but it is configured per-host, and does not count changes
> made locally before sending, only received changes. It would be nice if
> there were a single, consistent, history that is sync'd along with the
> folder. It seems that storing the version information in the folder, and
> configuring versioning on every host the same way, will have close to this
> effect -- but why not allow syncthing to version changes before it sends
> them as well as when it receives them?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncthing/syncthing/issues/1992>.
>



-- 
Dan.

**Comment by calmh** [comment]
> but why not allow syncthing to version changes before it sends them as well as when it receives them

Because we can't know that a file *will change* at some point in the future, so we can't make the version. That versioning needs to be done by whatever program makes the change. Once we detect that a change has happened it's too late.

**Comment by plouj** [comment]
Just as a suggestion: I'm doing something like this by simply having one of the devices auto-commit the changes to the Git repository inside the folder every minute (via a cron job). This plus ```syncthing-inotify``` usually catches and records all of the changes I make to the folder from two other devices. It's good enough for something like personal notes.
