### ISSUE TITLE
Stat: No such file or directory

### ISSUE THREAD

**Issue by Nairou** [syncthing/syncthing#1998]
I just started using syncthing yesterday, and am seeing this problem today. There was another issue open about this same thing, but it was closed, so I'm posting another one. I am not using inotify on either computer.

I setup a sync between two computers (A and B for clarity), for a "Pictures" folder containing thousands of photos in multiple folders. Both computers already had the full set of files, as they were previously sync'd by Bittorrent Sync.

Around this same time, I decided to do some housecleaning and deleted a few of the subfolders within the "Pictures" folder on computer A (the one I was physically using). Afterwards I noticed that both computers said they were disconnected (in the web GUI), so I told syncthing to restart (via the web GUI) on computer B, to see if that would reconnect them. It did, but then computer B proceeded to start copying the files I deleted back to computer A. It apparently didn't know that the deletions were intentional. It was going to transfer a lot of files I didn't want transferred and I didn't know how to stop it, so I logged in to computer B and deleted those subfolders there as well.

Shortly after that, I started getting "Folder 'Pictures' isn't making progress" messages on both computers. I checked the syncthing output on computer B and saw "Stat: No such file or directory" errors about the subfolders I deleted.

**Comment by AudriusButkevicius** [comment]
Sounds like its the similar to #1997 (or perhaps just a race condition between index exchange and rescan), and the no such file problem is #1973. Hence closing.

You can get around the issue by removing the folder on both devices and re-adding it.

This needs a test case to try and reproduce reliably, given we know the steps you took.
