### ISSUE TITLE
Documentation of log-file options

### ISSUE THREAD

**Issue by cbhushan** [syncthing/syncthing#2004]
If I understand correctly, Syncthing writes out log messages on stdout. So, the nature of logging and the location of log file, if any, depends on the how Syncthing was started. Would it be possible to document simple ways of logging (something similar to http://docs.syncthing.net/users/autostart.html would be great)?

I think on windows logfile is saved in configuration directory. Is it too much work to have an option to have the same behavior on all OS?

BTW, I use following on linux to log to syslog. Works great!

```
/home/bin/syncthing-linux-amd64/syncthing 2>&1 | logger -t [SYNCTHING]
```

**Comment by Zillode** [comment]
Thanks, you are welcome to improve our documentation website as well. Just click [edit on Github](http://docs.syncthing.net/users/autostart.html) and file your changes.
