### ISSUE TITLE
Log needs to be available through web interface and not just stdout, e.g. "Actions > Show Log"

### ISSUE THREAD

**Issue by JonasT** [syncthing/syncthing#2005]
I get messages like this all the time: ```
2015-06-27 12:22:37: Folder "sims4mod" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.```
However, on windows I cannot easily check stdout. Also it's really confusing to less experienced users that it mentions a log, but nothing in the web interface mentions it.

Therefore, logging should be somehow stored internally (and not just stdout) and shown with "Actions > Show Log" or some other obvious button in the web interface. The stdout thing is just way too inconvenient and confusing on non-unix platforms (or when it's started in the background and not in a terminal with stdout nicely available).

**Comment by AudriusButkevicius** [comment]
There is a log file on windows in syncthings config directory.
Thought this will be fixed in general by #2001
