### ISSUE TITLE
Add ability to move storage locally

### ISSUE THREAD

**Issue by JohnMaguire** [syncthing/syncthing#2011]
It seems as though, if I want to move the storage of the share on my local machine, I have to delete the share, move it, and then re-create the share.

It'd be nice if the GUI offered a "Move storage" option.

**Comment by arneko** [comment]
While you are right, that this seems to be the case, you can actually just shutdown syncthing, move the data and change the path in the config manually. Syncthing won't reindex the whole folder, which is nice.

**Comment by AudriusButkevicius** [comment]
What @arneko says is correct, you just need to move it yourself, and modify the config.

**Comment by JohnMaguire** [comment]
There's no interest in adding this to the UI for people who don't want to
manually tweak config files? Is this due to the same limitation that's
responsible for needing to restart SyncThing for most changes?

I've been using SyncThing with a couple coworkers to great success but
these sorts of things are hurting adoption. I'd be interested in attempting
to implement the "Move storage" feature myself if it's just about time.

**Comment by AudriusButkevicius** [comment]
So I've checked dropbox, onedrive and google drive, none of which have what you are asking for.
They have the concept of unlinking, and relinking, which is just as manual as it is now.
You remove a folder, move the files somewhere else, readd the folder under a different path.
Yeah, sadly that will cause a reindex, but I am sure that onedrive et all do the same thing (perhaps at a lesser expense not having to use cryptographic hashes)

Regardless, if you feel this is important enough for you, feel free to back this ticket up with a pull request.

**Comment by JohnMaguire** [comment]
Hmm, I understand the parallel you're drawing between OneDrive and Google Drive (where their share is available at a set point, and you can't really move it other than manually), but unfortunately this sort of share is the level at which you "share" your files with other users. For example, in Google Drive you can share a specific folder within your Drive, and rename that folder as you wish.

However, to share a specific folder with SyncThing, you have to do it at the highest level. So being able to rename that level can be useful.

I'm not quite sure I'm explaining this well. But you have a lot of different shares inside SyncThing which you might move around and/or share with people. In Drive, you're drawing a parallel to its top level, but its top level doesn't behave the same as SyncThing's top level. You can rename the folders within it.

I'll look into what it would take to implement this. :) Thanks for the discussion.

**Comment by uok** [comment]
Since everything is synced, moving files has the risk of selecting the wrong target folder which then causes possible mayhem. Also how do you handle things like showing (slow) progress of moving (e.g. copying 450GB of data to another partition on same disk), running out of space on target disk (user forgot to check for free space), etc.?

Wouldn't it be easier to just make the path field editable (everytime, not just when creating) instead of programming Syncthing to move files? Maybe with two clicks and a switch to make sure user knows what he is doing. Or an extra button somewhere that unlocks the system fields

**Comment by AudriusButkevicius** [comment]
I think that this is such an edge case, that people who need it and understand what they are doing can just edit the config.

**Comment by JohnMaguire** [comment]
@uok Making the path field editable wouldn't be bad, but it would definitely be confusing for the user that doesn't understand their data won't be moved for them.

It seems fairly easy to me to create a new goroutine to check the free disk space, start moving files, block shutdown w/ a prompt, and throw up an error event if it fails.

Granted, I'm not familiar with the internal architecture of SyncThing. I understand config changes require restarts which is a bit problematic with blocking on moving. I am curious about the reasoning for most UI settings requiring a restart? Is it not possible to simply reload the config file seamlessly?

**Comment by jpjp** [comment]
If we're going to do all of that, why not add a file manager too? :) How often is this request really ever needed? The number of things that could go wrong is not worth the added complexity..

**Comment by JohnMaguire** [comment]
On another note, your comparison to Google Drive et al is perhaps less of a parallel than with BitTorrent clients: all of which offer a "Move storage" option.

**Comment by JohnMaguire** [comment]
I'm having a hard time seeing the cost / benefit comparison to this. Here's what I see as roadblocks:

1. The need to restart SyncThing on config changes (e.g. adding a new share) means that operations like adding a share would be problematic while in the middle of a move.
2. You would have to make certain checks ("Is there enough room on the destination?", a couple other things, but not much to be honest...)
3. If it fails, you need a way to tell the user (the web UI and the REST event API?)
4. While happening, you need a way to show progress (a little progress bar across the top of the UI?)

This doesn't seem too difficult to me. In the case it does fail, you provide an error (like all other errors SyncThing can provide) to the UI and REST API.

The process for the move would seem to be:

1. Turn the share off from syncing.
2. Move the folder to the destination.
3. Update the config.
4. Turn the share on for syncing.

I don't think this is as complex as it's being made out to be. I do think the issue of config changes requiring restarts would have to be dealt with first.

**Comment by JohnMaguire** [comment]
@jpjp I would also like to point out that a file manager is MUCH more complex to implement than moving some files. Slippery slope arguments aren't really helpful to this discussion. I work on Barracuda Backup's web team, and am familiar with what it takes to implement a file browser / manager. Let's keep this on topic.
