### ISSUE TITLE
Panic on OS X

### ISSUE THREAD

**Issue by davidak** [syncthing/syncthing#2013]
done nothing special; OS X 10.9.5

```
[ZQVPO] 10:43:51 INFO: Puller (folder "Arbeit", dir "code"): delete: remove /Users/davidak/sync/code: directory not empty
panic: open /Users/davidak/Library/Application Support/Syncthing/index-v0.11.0.db/007085.ldb: too many open files
[monitor] 10:43:51 WARNING: Panic detected, writing to "/Users/davidak/Library/Application Support/Syncthing/panic-20150630-104351.log"
[monitor] 10:43:51 WARNING: Please create an issue at https://github.com/syncthing/syncthing/issues/ with the panic log attached
[monitor] 10:43:51 INFO: Syncthing exited: exit status 2
[monitor] 10:43:52 INFO: Starting syncthing
```

Panic: http://davidak.basecom.de/paste/?63496e7d8358cf63#E0pluT1fsaQQD2xSC6/MExs2zyEU4Jx8F0idKAi6KDc=

**Comment by AudriusButkevicius** [comment]
Yeah, that's a limit enforced by the kernel. I am not sure we can do a lot, though listing open file handles per process would be interesting:
http://stackoverflow.com/questions/20974438/get-list-of-open-files-descriptors-in-os-x

**Comment by calmh** [comment]
We shouldn't really be having that many files open though... Wonder what they are.

**Comment by Zillode** [comment]
@davidak are you using syncthing-inotify?

**Comment by davidak** [comment]
@Zillode I'm using a binary downloaded from github.

**Comment by davidak** [comment]
it does not happen again.

the situation was that i deleted the code/ folder what contained ~28k files with git repos on another node after syncthing broke some repos in another syncthing folder and i read the advice from @calmh to not sync git repos. it could not get deleted completely from syncthing because there was something like a .DS_Store file in it. i manually deleted it to solve that.

i had no problems syncing this files.

**Comment by AudriusButkevicius** [comment]
Closing on the basis that it does not happen again.
