### ISSUE TITLE
Request: portable setting in ui

### ISSUE THREAD

**Issue by Gibbz** [syncthing/syncthing#2015]
Would really love to see a portable setting in this software. It would store the settings for the app within its own folder. 
That way theres no need to keep resetting up after each format...

**Comment by calmh** [comment]
Are you looking for the `-home` flag?

**Comment by rumpelsepp** [comment]
> Are you looking for the -home flag?

see also: http://docs.syncthing.net/users/syncthing.html#cmdoption-home

**Comment by Gibbz** [comment]
Awesome! Googling didnt show any results, but that does the trick :)

Thanks! Loving the software!
