### ISSUE TITLE
Conflict files generated when syncing between fast device and slow device

### ISSUE THREAD

**Issue by Nightmaren** [syncthing/syncthing#2016]
My current setup is as follows:
Device 1: Windows 8.1, running SyncThing v0.11.11
Device 2: Linux ARM (Raspberry Pi B+), running SyncThing v0.11.11

Device 1 is a modern computer while Device 2 is a slow headless Raspberry Pi that coordinates back-up operations. Changes are never made on the Raspberry Pi.
In a Sync folder between the two devices, I have a music folder. On Device 1, I copied about ~20 *.mp3 files into the Sync folder. I then began to edit some of the files' tags, which modifies the *.mp3 file. Upon rechecking the Sync folder, I notice that a number of .conflict files have been created.

There should not have been any conflict/collision as there was only one device making changes. I feel that the files were still syncing on the Raspberry Pi when I made the modifications, thus manufacturing a conflict.

Please let me know if I were unclear, misunderstood something, or if I can provide additional information. Thank you.

**Comment by calmh** [comment]
Do you have a FAT filesystem or something on that Pi?

**Comment by Nightmaren** [comment]
The Sync folder on the Pi is mounted on a hard drive with a NTFS filesystem

**Comment by calmh** [comment]
You'll want to set the Ignore Permissions flag on that folder, as Linux won't store permissions correctly on NTFS

**Comment by Nightmaren** [comment]
Hello, your solution corrects the problem. I apologize, I thought that this was a problem due to the speeds of the devices. Thank you very much -- might I suggest mentioning this under the "Ignore Permissions" checkbox in the GUI? Regardless, thank you very much.
