### ISSUE TITLE
Add button to the UI to "force" a resync; by folder, or server.

### ISSUE THREAD

**Issue by blakev** [syncthing/syncthing#2019]
Unless this functionality is against the Syncthing development direction, I'd love the ability to force a sync between automatic polling intervals.

Thanks

**Comment by AudriusButkevicius** [comment]
You can't do that though, as syncing process is kicked off by the fact we've received something from a remote machine, so there is no polling.

**Comment by blakev** [comment]
Would it be faster to use a privately hosted tracker, then? Without digging very deep it seems like it'd be supported, but I have no idea.

**Comment by calmh** [comment]
What would this forced resync do?

**Comment by blakev** [comment]
Update the tracker I suppose. In our team the refresh interval on the folder is 20 seconds...but it can take 10-20 minutes for file changes to propagate.

Maybe a private tracker in the office would solve this problem.

**Comment by calmh** [comment]
There is something else wrong in your setup, updates are sent immediately when detected, and handled immediately when received. There's not tracker as such, all changes are sent peer to peer.

**Comment by AudriusButkevicius** [comment]
Closing as I believe this is just a misunderstanding how syncthing works.
If you have any comments, please let us know so that we could reopen it.
