### ISSUE TITLE
Wher are the log files

### ISSUE THREAD

**Issue by PD75** [syncthing/syncthing#2025]
I get the error message to check the log files, but I can not find them. There is nothing in the help and I find nothing on internet. I have a telnet to the BSD machine where syncthing is running. Some kind of indication where the log file are would be great. Maybe in the settings page. Or at least show the error message so I know what is wrong.

**Comment by wweich** [comment]
Syncthing only writes to a log file on Windows. On every other plattform, it logs to stdout.

So it depends on how you start syncthing on your BSD machine.
If you use a init script, you should check if that redirects the output to a file.
If not, you should stop the daemon and start syncthing manually to see the error in stdout.
