### ISSUE TITLE
Checkboxes in Section 'Share Folders With Device' are always disabled

### ISSUE THREAD

**Issue by sam701** [syncthing/syncthing#2028]
Version: 0.11.12
OS: Mac OS X 10.10.3, Linux CentOS 7

Checkboxes in UI 
 - Devices/Edit/"Share Folders With Device" and 
 - Folders/Edit/"Share With Devices"

are always disabled.

It worked in version 0.11.11.

**Comment by uok** [comment]
dupe of #2029 - please close
