### ISSUE TITLE
Checkboxes in 3-column layout in GUI are unclickable in Chrome

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#2029]
Checkboxes inside divs with class `three-columns` are unclickable in Chrome 43 / CEF 3 on Windows.

Disabling the `-webkit-column-count: 3` directive in the `.three-columns` class "fixes" the issue - i.e. makes the checkboxes clickable again.

This affects CEF 3, which was previously working fine, suggesting that it is not a Chrome update which broke this. However, none of the relevant lines in Syncthing's source seem to have changed lately either...

This means that it's impossible to select which devices to share a folder with, and folders to share a device with, in the GUI.

Firefox seems unaffected.

Forum topic: https://forum.syncthing.net/t/problem-after-updating-to-0-11-12/5055

**Comment by uok** [comment]
Bootstrap update causes this (see old #1121)

**Comment by canton7** [comment]
There was a bootstrap update just before 0.11.12 was released, which fits
