### ISSUE TITLE
not possible to add devices

### ISSUE THREAD

**Issue by SteffenTux** [syncthing/syncthing#2031]
I´m using v0.11.13, Linux (64 bit). It is not possible to add devices with the ID. Tere´s no callback !

**Comment by canton7** [comment]
Please provide more information. What exactly do you mean by "It is not possible to add devices with the ID"? What do you see, and how does that differ from what you expect to see? What do you mean by "Tere´s no callback"?

**Comment by SteffenTux** [comment]
first I copy the ID from device Nr. 1 to the target device.  But after this there is no callback from target device do device Nr. 1. So I cannot share folders between devices. There should be an sign like "device xy wants to share a folder with you".... But nothing happens!

**Comment by canton7** [comment]
You will need to configure each device, and add the other device's ID to its list of trusted devices.

There are circumstances where Syncthing will go "Oh, Device XXX tried to talk to me: do you want to add it". I'm not 100% sure when it will do this - it may require that a folder is shared with that device first...

**Comment by AudriusButkevicius** [comment]
I think this is just a misunderstanding of how Syncthing works.
It shows the connection prompt when possible, and when it manages to connect. 
If it fails to connect, there is no prompt, and devices have to be added manually.

Please refer to the getting started guide.
