### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by jorgebravocarrizales** [syncthing/syncthing#2033]
[P63QZ] 17:17:47 INFO: syncthing v0.11.11 (go1.4.2 darwin-amd64 default) unknown-user@syncthing-builder 2015-06-28 19:10:57 UTC
[P63QZ] 17:17:47 INFO: My ID: P63QZEB-UNR2GZ6-FTA2QB6-FPHGNM4-PYA4ZHE-473BWRO-OPKJEWD-VRJMLAU
[P63QZ] 17:17:47 INFO: Database block cache capacity 65536 KiB
...
Panic at 2015-07-06T17:17:47-05:00
panic: leveldb/table: corruption on data-block (pos=1659220): checksum mismatch, want=0xf62317c3 got=0x92dc4172 [file=011594.ldb]

goroutine 1 [running]:
github.com/syncthing/syncthing/internal/db.ldbCheckGlobals(0xc20800c840, 0xc20827d180, 0x8, 0x8)
	/go/src/github.com/syncthing/syncthing/internal/db/leveldb.go:1053 +0xde0
github.com/syncthing/syncthing/internal/db.NewFileSet(0xc20813a010, 0x8, 0xc20800c840, 0xc20813e350)
	/go/src/github.com/syncthing/syncthing/internal/db/set.go:55 +0x285
github.com/syncthing/syncthing/internal/model.(*Model).AddFolder(0xc20810fc20, 0xc20813a010, 0x8, 0xc208141500, 0x34, 0xc20815dd80, 0x2, 0x4, 0x0, 0x3c, ...)
	/go/src/github.com/syncthing/syncthing/internal/model/model.go:1170 +0x1a1
main.syncthingMain()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:621 +0x2216
main.main()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:383 +0x2288

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan receive]:
main.trackCPUUsage()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0xec
created by main.init·2
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x25

goroutine 9 [select]:
github.com/thejerf/suture.(*Supervisor).Serve(0xc2080f6000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:411 +0xf64
created by github.com/thejerf/suture.(*Supervisor).ServeBackground
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:373 +0x32

goroutine 10 [select]:
github.com/syncthing/syncthing/internal/events.(*Subscription).Poll(0xc20801e9e0, 0xdf8475800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:183 +0x369
github.com/syncthing/syncthing/internal/events.(*BufferedSubscription).pollingLoop(0xc20802ecd0)
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:220 +0x48
created by github.com/syncthing/syncthing/internal/events.NewBufferedSubscription
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:214 +0x292

goroutine 12 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc2080780e0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x21e
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236 +0x24c

goroutine 13 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc20800c840)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:69 +0x55a
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:139 +0x7cc

goroutine 14 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc20800c840)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_state.go:82 +0x14a
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:140 +0x7e6

goroutine 15 [runnable]:
github.com/google/go-snappy/snappy.emitLiteral(0xc2096a395c, 0x2455b, 0x2455b, 0xc2094dabf6, 0x20, 0x2e8d6, 0x21)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/google/go-snappy/snappy/encode.go:16
github.com/google/go-snappy/snappy.Encode(0xc20969c000, 0x2beb7, 0x2beb7, 0xc2094d2000, 0xecd6, 0x374cc, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/google/go-snappy/snappy/encode.go:130 +0x4cb
github.com/syndtr/goleveldb/leveldb/table.(*Writer).writeBlock(0xc208ca2000, 0xc208ca2058, 0x2, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/writer.go:171 +0x225
github.com/syndtr/goleveldb/leveldb/table.(*Writer).finishBlock(0xc208ca2000, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/writer.go:225 +0x7e
github.com/syndtr/goleveldb/leveldb/table.(*Writer).Append(0xc208ca2000, 0xc209b381e0, 0x9c, 0xa0, 0xc2096820a2, 0xec2c, 0xec34, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/writer.go:258 +0x3ef
github.com/syndtr/goleveldb/leveldb.(*tWriter).append(0xc20807c420, 0xc209b381e0, 0x9c, 0xa0, 0xc2096820a2, 0xec2c, 0xec34, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table.go:485 +0x303
github.com/syndtr/goleveldb/leveldb.(*tableCompactionBuilder).appendKV(0xc208dd60a0, 0xc209b381e0, 0x9c, 0xa0, 0xc2096820a2, 0xec2c, 0xec34, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:368 +0x200
github.com/syndtr/goleveldb/leveldb.(*tableCompactionBuilder).run(0xc208dd60a0, 0xc2082de0c0, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:486 +0x7aa
github.com/syndtr/goleveldb/leveldb.(*DB).compactionTransact(0xc20800c840, 0x69bf50, 0xb, 0xb59ab8, 0xc208dd60a0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:164 +0x277
github.com/syndtr/goleveldb/leveldb.(*DB).tableCompaction(0xc20800c840, 0xc20849e000, 0x0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:552 +0x107c
github.com/syndtr/goleveldb/leveldb.(*DB).tableAutoCompaction(0xc20800c840)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:597 +0x50
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc20800c840)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:789 +0x3a0
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:146 +0x9cf

goroutine 16 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc20800c840)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:715 +0x283
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:147 +0x9e9

goroutine 17 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc20800c840)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x197
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:148 +0xa03

goroutine 20 [select]:
github.com/syncthing/syncthing/internal/model.(*ProgressEmitter).Serve(0xc2082a2a80)
	/go/src/github.com/syncthing/syncthing/internal/model/progressemitter.go:52 +0x8f2
created by github.com/syncthing/syncthing/internal/model.NewModel
	/go/src/github.com/syncthing/syncthing/internal/model/model.go:144 +0xb85

**Comment by AudriusButkevicius** [comment]
Duplicate, caused by database corruption.
Check for existing issues or forums for remedy and explanations
