### ISSUE TITLE
Syncthing appears to generate two DeviceConnected events per connection

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#2034]
Syncthing 0.11.13 appears to generate two DeviceConnected events per connection. The first one looks fine, the second one has the same timestamp as the first, but is missing the address field.

**Comment by calmh** [comment]
This is actually two bugs. There is duplication because the event is generated in two places - the first should be removed. The address may be missing because of a race condition...

**Comment by canton7** [comment]
:smile:
