### ISSUE TITLE
unrecognised upnp device....

### ISSUE THREAD

**Issue by Gibbz** [syncthing/syncthing#2035]
Getting a lot of console spam with the following on windows and linux....

[UBCXW] 11:48:13 INFO: UPnP parse: unrecognized UPnP device of type upnp:rootdevice
[UBCXW] 11:48:13 INFO: UPnP parse: unrecognized UPnP device of type upnp:rootdevice
[UBCXW] 11:48:13 INFO: UPnP parse: unrecognized UPnP device of type uuid:00000000-0000-1000-0000-e8de274d9de0
[UBCXW] 11:48:13 INFO: UPnP parse: unrecognized UPnP device of type uuid:00000000-0000-1000-0000-e8de274d9de0
[UBCXW] 11:48:13 INFO: UPnP parse: unrecognized UPnP device of type urn:schemas-wifialliance-org:device:WFADevice:1
[UBCXW] 11:48:13 INFO: UPnP parse: unrecognized UPnP device of type urn:schemas-wifialliance-org:device:WFADevice:1
[UBCXW] 11:48:13 INFO: UPnP parse: unrecognized UPnP device of type urn:schemas-wifialliance-org:service:WFAWLANConfig:1
[UBCXW] 11:48:13 INFO: UPnP parse: unrecognized UPnP device of type urn:schemas-wifialliance-org:service:WFAWLANConfig:1

**Comment by AudriusButkevicius** [comment]
It's your routers fault for not following the standard. These are just info messages hence harmless.
