### ISSUE TITLE
It´s still not possible to connect devices

### ISSUE THREAD

**Issue by SteffenTux** [syncthing/syncthing#2038]
I´m using syncthing from the first time. That´s why I know how it works. Few days ago I rebuilt one of my notebooks. After installing syncthing I´m not able do connect this notebook with other devices. The notebook does not find the IP-adress an shows the target device as "not in use".

**Comment by AudriusButkevicius** [comment]
Not in use means nothing is shared with the device, please follow the getting started guide or atleast provide the logs, as just saying that something doesn't work doesn't help debug it. Did you actually add A on B and B on A? You have to do this on both sides.

**Comment by AudriusButkevicius** [comment]
Also, the fact that it worked before implies that you've misconfigured something, as I am sure nothing related to connections has changed in syncthing.

**Comment by dcarosone** [comment]
One possibility, just a guess since you've given no details: is is possible
the new device is running an 0.11.x version, and the older ones are running
0.10.x?  They're incompatible over the network.

On 9 July 2015 at 04:01, Audrius Butkevicius <notifications@github.com>
wrote:

> Also, the fact that it worked before implies that you've misconfigured
> something, as I am sure nothing related to connections has changed in
> syncthing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncthing/syncthing/issues/2038#issuecomment-119679315>
> .
>



-- 
Dan.

**Comment by SteffenTux** [comment]
there ist not a difference between the syncthing-versions. I removed the Order "syncthing" in the order ./config (fedora 22) an reconfigurated completly. But this didn´t fix the problem. Please watch the logfile I sent you per Email.

**Comment by SteffenTux** [comment]
there ist not a difference between the syncthing-versions. I removed the folder "syncthing" in the folder ./config (fedora 22) and reconfigurated completly. But this didn´t fix the problem. Please watch the logfile I sent you per Email.

**Comment by AudriusButkevicius** [comment]
If you reconfigured completely, you need to readd the devices on both sides.
Well I haven't received any email.

**Comment by SteffenTux** [comment]
of course I added the devices on both sides!!

Here is the logfile again.

[monitor] 23:56:19 INFO: Starting syncthing
[DKO4Q] 23:56:21 INFO: syncthing v0.11.13 (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-07-05 17:44:55 UTC
[DKO4Q] 23:56:21 INFO: My ID: DKO4QXO-AGD6DXO-XAZZLIQ-YVNTUAW-GDQZ5JF-M7OV7PH-ZDZGZFF-FYQRQA7
[DKO4Q] 23:56:21 INFO: Database block cache capacity 13815 KiB
[DKO4Q] 23:56:21 OK: Ready to synchronize default (read-write)
[DKO4Q] 23:56:21 OK: Ready to synchronize schule (read-write)
[DKO4Q] 23:56:21 INFO: Starting web GUI on http://127.0.0.1:8384/
[DKO4Q] 23:56:21 INFO: Completed initial scan (rw) of folder default
[DKO4Q] 23:56:22 INFO: Completed initial scan (rw) of folder schule
[DKO4Q] 23:56:23 INFO: Starting local discovery announcements
[DKO4Q] 23:56:23 INFO: Starting global discovery announcements
[DKO4Q] 23:56:23 INFO: Device DKO4QXO-AGD6DXO-XAZZLIQ-YVNTUAW-GDQZ5JF-M7OV7PH-ZDZGZFF-FYQRQA7 is "mini-tux" at [dynamic]
[DKO4Q] 23:56:23 INFO: Device S7WLP2N-TYTJWMK-4QKJ6AB-IAFP7F3-TIUB67M-CDDXKPX-6GTR5HI-DRVECQT is "papa" at [dynamic]
[DKO4Q] 23:56:23 INFO: API listening on 127.0.0.1:8384
[DKO4Q] 23:56:33 INFO: No UPnP device detected
[DKO4Q] 23:56:47 INFO: Starting usage reporting
[DKO4Q] 23:56:58 INFO: Restarting
[DKO4Q] 23:56:58 OK: Exiting
[monitor] 23:56:58 INFO: Syncthing exited: exit status 3
[monitor] 23:56:59 INFO: Starting syncthing
[DKO4Q] 23:57:01 INFO: syncthing v0.11.13 (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-07-05 17:44:55 UTC
[DKO4Q] 23:57:01 INFO: My ID: DKO4QXO-AGD6DXO-XAZZLIQ-YVNTUAW-GDQZ5JF-M7OV7PH-ZDZGZFF-FYQRQA7
[DKO4Q] 23:57:01 INFO: Database block cache capacity 13815 KiB
[DKO4Q] 23:57:01 OK: Ready to synchronize default (read-write)
[DKO4Q] 23:57:01 OK: Ready to synchronize schule (read-write)
[DKO4Q] 23:57:01 INFO: Starting web GUI on http://127.0.0.1:8384/
[DKO4Q] 23:57:01 INFO: Completed initial scan (rw) of folder default
[DKO4Q] 23:57:01 INFO: Completed initial scan (rw) of folder schule
[DKO4Q] 23:57:03 INFO: Starting local discovery announcements
[DKO4Q] 23:57:03 INFO: Starting global discovery announcements
[DKO4Q] 23:57:03 INFO: Device DKO4QXO-AGD6DXO-XAZZLIQ-YVNTUAW-GDQZ5JF-M7OV7PH-ZDZGZFF-FYQRQA7 is "mini-tux" at [dynamic]
[DKO4Q] 23:57:03 INFO: Device S7WLP2N-TYTJWMK-4QKJ6AB-IAFP7F3-TIUB67M-CDDXKPX-6GTR5HI-DRVECQT is "papa" at [dynamic]
[DKO4Q] 23:57:03 INFO: Starting usage reporting
[DKO4Q] 23:57:03 INFO: API listening on 127.0.0.1:8384
[DKO4Q] 23:57:13 INFO: No UPnP device detected

**Comment by AudriusButkevicius** [comment]
Are they on the same lan? Because if not, upnp is failing, and it's failing to get through the nat if you are bahind a router. Setting STTRACE=discovery environment variable and getting a new log with that set from both sides would help.

**Comment by AudriusButkevicius** [comment]
Also, to be honest, it's a support issue not a genuine bug, hence lets move it to the forums. Start a new thread on the forum and we can carry on the discussion.
