### ISSUE TITLE
Change instructions when a panic happens

### ISSUE THREAD

**Issue by Numeromancer** [syncthing/syncthing#2039]
[4O3YO] 13:25:51 INFO: syncthing v0.11.13 (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-07-05 17:44:55 UTC
[4O3YO] 13:25:51 INFO: My ID: 4O3YOFO-73VDPOC-PG6A7D6-W27BB47-HYCLYJS-UMHFMX5-FIN3M6H-Y44UOAB
[4O3YO] 13:25:51 INFO: Database block cache capacity 63107 KiB
...
Panic at 2015-07-08T13:25:51-04:00
panic: leveldb/table: corruption on data-block (pos=1212571): checksum mismatch, want=0xafe2a749 got=0x65f2f957 [file=001540.ldb]

goroutine 1 [running]:
github.com/syncthing/syncthing/internal/db.ldbGenericReplace(0xc2080e4b00, 0xc208fe54b0, 0x5, 0x8, 0xc20a3ec520, 0x20, 0x20, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/syncthing/syncthing/internal/db/leveldb.go:290 +0x12f6
github.com/syncthing/syncthing/internal/db.ldbReplace(0xc2080e4b00, 0xc208fe54b0, 0x5, 0x8, 0xc20a3ec520, 0x20, 0x20, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/syncthing/syncthing/internal/db/leveldb.go:321 +0xa3
github.com/syncthing/syncthing/internal/db.(*FileSet).Replace(0xc208ebd800, 0x890d3c49446c5466, 0x5293ff8e67e9125f, 0x61be63b16a9fe541, 0x88d4700388f54070, 0x0, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/internal/db/set.go:80 +0x3a7
github.com/syncthing/syncthing/internal/model.(*Model).Index(0xc208e2fc20, 0x890d3c49446c5466, 0x5293ff8e67e9125f, 0x61be63b16a9fe541, 0x88d4700388f54070, 0xc20811e540, 0x5, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/syncthing/syncthing/internal/model/model.go:527 +0xc26
main.syncthingMain()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:626 +0x39c8
main.main()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:383 +0x2288

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan receive]:
main.trackCPUUsage()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0xec
created by main.init·2
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x25

goroutine 9 [select]:
github.com/thejerf/suture.(*Supervisor).Serve(0xc2080f6000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:411 +0xf64
created by github.com/thejerf/suture.(*Supervisor).ServeBackground
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:373 +0x32

goroutine 10 [select]:
github.com/syncthing/syncthing/internal/events.(*Subscription).Poll(0xc20801e9c0, 0xdf8475800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:186 +0x369
github.com/syncthing/syncthing/internal/events.(*BufferedSubscription).pollingLoop(0xc20802c5f0)
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:223 +0x48
created by github.com/syncthing/syncthing/internal/events.NewBufferedSubscription
	/go/src/github.com/syncthing/syncthing/internal/events/events.go:217 +0x292

goroutine 11 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc2080740e0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x21e
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236 +0x24c

goroutine 12 [runnable]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc2080e4b00)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:102 +0x1dd
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:139 +0x7cc

goroutine 13 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc2080e4b00)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_state.go:82 +0x14a
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:140 +0x7e6

goroutine 15 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc2080e4b00)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:715 +0x283
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:147 +0x9e9

goroutine 16 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc2080e4b00)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x197
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:148 +0xa03
Here's the panic log:

goroutine 19 [select]:
github.com/syncthing/syncthing/internal/model.(*ProgressEmitter).Serve(0xc208ebd780)
	/go/src/github.com/syncthing/syncthing/internal/model/progressemitter.go:52 +0x8f2
created by github.com/syncthing/syncthing/internal/model.NewModel
	/go/src/github.com/syncthing/syncthing/internal/model/model.go:144 +0xb85

goroutine 21 [select]:
github.com/syncthing/syncthing/internal/ignore.(*Matcher).clean(0xc2098a9d10, 0x68c61714000)
	/go/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:161 +0x1c9
created by github.com/syncthing/syncthing/internal/ignore.New
	/go/src/github.com/syncthing/syncthing/internal/ignore/ignore.go:53 +0x170

**Comment by AudriusButkevicius** [comment]
It's a corrupt database.

Please search for existing issues before opening new ones. They explain causes and remedies.
There is also an alternative build on the forums.

**Comment by Numeromancer** [comment]
Ok, sorry about the noise.

You might want to change the output of the panic handler; that's what instructed me to submit the report.

**Comment by AudriusButkevicius** [comment]
Good point
