### ISSUE TITLE
"Ignore Patterns" panel Save/Close buttons not always accessible

### ISSUE THREAD

**Issue by simplypeachy** [syncthing/syncthing#2041]
I have SyncThing Android 0.6.5 / 0.11.13 on an HTC One (M8, a smartphone) and a Nexus 7 (2013, a 7 inch tablet) which have resolutions of 1920x1080 and 1920x1200 respectively. When I open a shared folder's "Ignore Patterns" panel, the Save and Close buttons are rendered off-screen, and I cannot scroll/zoom the pane so that they are accessible. As it stands, the Ignore Patterns functionality can't be managed via the Web UI on these sorts of devices.

I also tried this via web browsers and could access the buttons on the Nexus 7, but not the HTC One.
Screenshot:
![screenshot_2015-07-08-20-22-13](https://cloud.githubusercontent.com/assets/4228567/8579990/e75cd52a-25af-11e5-98de-e59fce12fda9.png)

**Comment by canton7** [comment]
This isn't just mobile devices - I'm seeing this on desktop as well. The browser's scrollbar doesn't allow you to scroll down as far as the 'Save' button

**Comment by Zillode** [comment]
possibly related to https://github.com/syncthing/syncthing/issues/1602

**Comment by canton7** [comment]
This is due to the 'modal-open' class not being applied to `body` when the ignores modal is open. Currently investigating why...

**Comment by simplypeachy** [comment]
Thanks for fixing this, much appreciated.
