### ISSUE TITLE
advanced settings page close button not working correctly

### ISSUE THREAD

**Issue by lovetox** [syncthing/syncthing#2042]
If you hit the close button instead of the save button, it still saves every change you made.

**Comment by AudriusButkevicius** [comment]
Yeah, it doesn't save the config, but it modifies it, so that when something else saves it, the changes are actually saved.

**Comment by calmh** [comment]
:+1:

**Comment by lovetox** [comment]
still doesnt work

situation now is

press "close": it doesnt save (as intended)
press "save": it saves, but requires a restart

after restart, config is back to old state

or should i open a new ticket?

**Comment by calmh** [comment]
@lovetox #2058 ?

**Comment by lovetox** [comment]
yes thanks i think this is related :)
