### ISSUE TITLE
Explaon support host names for device address

### ISSUE THREAD

**Issue by brendanlong** [syncthing/syncthing#2044]
I have a server that always runs on a particular host. I don't want to depend on the IP address, so it would be nice if I could tell it that the server is always "brendanlong.com:someport" instead of "dynamic".

**Comment by AudriusButkevicius** [comment]
And why do you think you cannot do that?

**Comment by brendanlong** [comment]
Because it's not listed in the instructions:

<img width="778" alt="screen shot 2015-07-09 at 4 01 13 pm" src="https://cloud.githubusercontent.com/assets/1447206/8607943/c01e3fc2-2653-11e5-853f-8f1cf7b50216.png">

**Comment by calmh** [comment]
Fair enough. It is supported though, although the help text could be more explicit about it.
