### ISSUE TITLE
enhancement: pause and "slow" buttons on web interface/CLI

### ISSUE THREAD

**Issue by akohlsmith** [syncthing/syncthing#2045]
There are times where I don't want syncthing to work as well as it does. Similar to how Transmission (bittorrent client) has "slow" mode, it'd be handy to do the same thing on syncthing. The "slow mode" up/down rate would be configurable items in the normal settings dialog.

**Comment by AudriusButkevicius** [comment]
You already have rate limiting, just use that.

**Comment by akohlsmith** [comment]
The issue with "using the rate limiting we already have" is that anytime you touch any setting you end up restarting the utility to have the change take effect. 

To take your comment to the next level you could say "just use rsync" -- syncthing simplifies a lot of things and adding an ease-of-use feature to the UI seems like a good fit.

**Comment by AudriusButkevicius** [comment]
The restarting issue is a separate issue and already has a ticket. Implementing this would not resolve that and would most likely require a restart at the current stage anyway, as you'd have to tear down all the sockets, reconstruct them and wrap them in rate limiters... Which is just easier done when restarting.

Once the restart issue is resolved, this becomes a non-issue, unless you really care about having button versus inputting values yourself. 

If we drift too far away this way, next thing people will want will be a date time scheduler for different rates at different times, which none of the existing solutions currently provide AFAIK, hence we have to draw the line somewhere and consider what is useful to the masses and what is useful to a handful, and invest development time according to that.

I guess if the feature comes as a contribution by someone who really needs it, is implemented well and sort of fits without causing too much havoc, it's a different story, but for now I think there are more important things to focus on, such as getting the damn thing to work for example.

**Comment by indiajuliet** [comment]
what about a simple "pause" switch?

**Comment by AudriusButkevicius** [comment]
#215

**Comment by jb510** [comment]
I know this is closed, but the other issue is restricted to contributors.  The comment was made above "why not use rate limiting".  For me the issue usually isn't bandwidth it's CPU usage.  It's initial syncs of 300GB folders that take days, and the resulting CPU usage of all that syncing (not so much on my desktop, but on my anemic ARM based NAS).   Need to pause syncing and scanning, while keeping the Syncthing GUI running.

**Comment by AudriusButkevicius** [comment]
You can reduce number of hashers to 1 in the config, use nice/cgroups to achieve that.

**Comment by jb510** [comment]
TY Audrius. I think that sort of helps, but the idea is to have some control from the GUI over CPU usage.  SSH'ing in to tweak config files when I want it to go fast/slow/pause isn't very user friendly. 

Note: I have no idea what you mean by nice/cgroups, but I'll look that up.  Thanks again.

**Comment by AudriusButkevicius** [comment]
Advanced config has the option to tweak hasher count. There will not be controls for cpu usage in the UI as it's the OS job to manage that.

**Comment by jb510** [comment]
TY again.  Lots more in that advanced pane then I remember from a couple months ago. I'll fiddle.  Appreciate the tips.

**Comment by uok** [comment]
see http://docs.syncthing.net/users/config.html for a complete list

**Comment by jb510** [comment]
TY.  The armv5te is actually single core so I don't think changing hashers is going to help.  New NAS is in my near future.  I agree managing CPU usage of a running app is an OS's job.  However, pausing scanning without needing to stop and later to restart syncthing would be nice to do from time to time.

**Comment by AudriusButkevicius** [comment]
That is somewhere on the road map, not sure where though.
