### ISSUE TITLE
enhancement: data rate limits ignored for "LAN" connections

### ISSUE THREAD

**Issue by akohlsmith** [syncthing/syncthing#2046]
There's almost no reason to slow down transfers to other clients on the same LAN. I'm not sure how easy it is to detect whether a client is local or remote, but being able to allow a local LAN connection to sync up as quickly as possible while still rate limiting remote clients would be a handy feature.

**Comment by calmh** [comment]
We actually don't enforce rate limits on LAN connections by default. You need to set the advanced config `limitBandwidthInLan` to *get* that behavior.
