### ISSUE TITLE
enhancement: per-folder rate limiting

### ISSUE THREAD

**Issue by akohlsmith** [syncthing/syncthing#2047]
Use case: My work data I want to sync up quickly, but syncing up my photos directory shouldn't take up all my bandwidth. I'd like to rate limit my folders, rather than all of syncthing.

**Comment by AudriusButkevicius** [comment]
We use the same connection for everything hence it would be difficult. Though you could do it at the protocol level. Next request I see is per device per folder turning it into a UI crysis.

**Comment by MyPod** [comment]
I suppose a workaround would be to run two syncthing instances set with
different home folders, where the one managing the photo has a bandwidth cap

**Comment by mindhash** [comment]
how about setting sync priorities for folders.

**Comment by calmh** [comment]
Folders don't "know" about each other internally, and it's rather neater to keep it that way. Rate limits *could be* per folder, but as Audrius says this will end up being per device, per folder, depending on whether we're on the same LAN or not, and maybe time of day would be nice too. I think simpler is better here until there's something that's obviously critical and useful to a lot of users...

**Comment by lkwg82** [comment]
This seems to me is against our paradigm "simplicity" to end users. I suggest to close this.
