### ISSUE TITLE
reduce need to restart manually

### ISSUE THREAD

**Issue by DrAzraelTod** [syncthing/syncthing#2049]
i just migrated half a dozen devices from seafile to st, what really annoyed the hell out of me was the need to restart st for every smallish change.

Adding a lib? restart
renaming a peer? restart
changing version-history for a lib? restart

it gets even worse because i have to repeat a lot steps for every peer due to decentralised layout and since i didn't really know how it works i needed a lot restarts more than useful. There were some parts where i just waited for something to happen, only to notice 1-2 minutes later that some peer wouldn't do anything, because it still waits, asking for its restart.

**Comment by DrAzraelTod** [comment]
btw: how about auto-restarting if all connected peers are fully synced anyway and st has nothing to do?

**Comment by AudriusButkevicius** [comment]
I am on the phone, but I am sure this is a duplicate.

**Comment by DrAzraelTod** [comment]
i did
i even looked manually over all open tickets and found nothing

so uh.. where?

**Comment by AudriusButkevicius** [comment]
https://github.com/syncthing/syncthing/issues/1597
