### ISSUE TITLE
updating files instead of uploading them again when changing metadata

### ISSUE THREAD

**Issue by Eddy2909** [syncthing/syncthing#2051]
hi there!
I wondered if it's maybe possible to update files instead of uploading them again when files "metadata" (e.g. mp3 - ID tags) have changed? In my case: 1000 new uploads because of rating my mp3 files :+1:

**Comment by AudriusButkevicius** [comment]
The mp3 id tags are inside the file, so the file content actually changes.

**Comment by uok** [comment]
sync should be quite fast because the tags are stored in the header of the mp3 file, the rest remains unchanged - see https://en.wikipedia.org/wiki/MP3

**Comment by AudriusButkevicius** [comment]
subject the header is padded, and does not shift data bytes around.
