### ISSUE TITLE
enhancement: Stop sync when free disk space reaches a minimum level

### ISSUE THREAD

**Issue by hungrywolf27** [syncthing/syncthing#2057]
Feature request:
Instead of continuing to sync files until a device runs out of space and file creation fails, have an option to stop syncing the folder and show an error when the free disk space reaches a user-defined threshold (e.g. 2 Gib).

Knowing a folder's Global State and the amount of files Out of Sync on the local system, it would be possible for Syncthing to tell when a complete sync is going to exceed available space, and warn the user in advance. This would avoid worse problems caused when disk space reaches zero.

(Now I see @Zillode 's comment in #1790 that there is no golang library for getting free disk space. Any news or other thoughts on that matter?) 

Closed issues related to out-of-space errors: 
https://github.com/syncthing/syncthing/issues/302
https://github.com/syncthing/syncthing/issues/1790

**Comment by AudriusButkevicius** [comment]
I feel it's the users job, just like driving a car, before you get in and drive, it's your job to make sure its ina reasonalbe technical state. Personally feel that this is a won't fix.

**Comment by AudriusButkevicius** [comment]
Also I am sure there is specialised software out there that does it, we don't need to make syncthing a swiss army knife which does everything, but poorly.

**Comment by jorangreef** [comment]
Why should a sync tool not make as much use of the information at hand as possible? If it knows the disk has 5 GB remaining, why should it blindly try and download a 10 GB file only to waste bandwidth? Why should the user be expected to keep checking free disk space every few minutes when a machine could do it easily on their behalf?

**Comment by hungrywolf27** [comment]
It seems clear from #1790 that the database library will crash when disk space reaches zero. So why not have a simple check to avoid this happening? I'm not suggesting a complex system of disk quotas, just a simple "safety valve" mechanism that the user can turn on/off if he/she wishes.

**Comment by AudriusButkevicius** [comment]
Because there is no such thing as a simple check. Go stdlib does not provide a way to check this, meaning we dwell down into win32 api land for windows, some magic api for solaris and any other operating system syncthing will support in the future.

Why should syncthing not consume 100% of the space? Same like utorrent or chrome or whatever, it will consume as much space as possible.

I feel this is a lot of work for a limited benefit.

**Comment by cs42** [comment]
@AudriusButkevicius this is not work for a limited benefit. With syncthing someone could render another computer almost unusable by dropping a big file in a synced directory! For many users it's not an easy task to set up quotas to limit disk usage by syncthing...

**Comment by calmh** [comment]
Assuming we can detect the amount of space left on the device, what would we aim for as a limit? We may create temporary copies of (by default) up to 16 files when synchronizing them, so we would need to reserve space for at least copies of the 16 largest files in the repo to be sure a sync is going to work. But that could mean we want 100 GB of free space just to update a text file.

We could try to do the check just before copying a file, possibly, and skipping it if the amount of free space looks marginal. We'll try smaller files in that case (as we always try to sync the next file in the list if one file fails for whatever reason), so we might still get very close to full filesystem - basically as close as the smallest file we have in the repo.

Absolute values are obviously no good (8 GB free would be a good warning limit on my photo folder, but not on a phone), percentages likewise (5% of my data pool is still 900 GB)...

User configurable, possibly, but the less we need to ask for the better...

**Comment by cs42** [comment]
I think having a resonable percentage as default (I'd vote for 10%) should be good and than this could be an advanced option. If a user sets this value to 0%, then it is out of the hands of syncthing.

Your idea of checking before copying a file and if it wouldn't fit just skipping it, sounds reasonable.

How to handle the temporary copies, I do not know. Question is, where are they stored? In /temp on Linux? Then you need the space there. And reserving space for the 16 largest files in a repo sound as too much. And what happens, if I have 5 shared directories on my device? Is it 80 temporary files then?

**Comment by canton7** [comment]
I know many people who are happily operating within 10% of their disk limit. On a 1TB drive that's still 100GB spare. They would be pissed if Syncthing refused to synchronize under those conditions.

**Comment by jpjp** [comment]
Will Syncthing behave if the disk gets full, or could it half-write a file which then looks different to the files on other nodes, and propagate back?

**Comment by Zillode** [comment]
@jpjp that can happen, however I think the db would be corrupted sooner and syncthing will exit. There is a patch on the way that will exit when free disk space < 1GB (configurable).

**Comment by dcarosone** [comment]
This latter presumes that the db and sync folder are in the same
filesystem. Maybe true for small cases but not at all certain for anything
serious. I have dozens of filesystems on most machines, including laptops,
because zfs makes it easy and worthwhile; sync points are a good example.

Another worm of opening this can: if we hit some putative limit, could we
react by pruning .stversions somehow? This can at least be delegated back
to a user extension, but it's all more complexity than seems worthwhile.

**Comment by cs42** [comment]
@dcarosone I think this feature should not be too intelligent. It should just prevent filling up the file system. If the limit is hit it would be sufficient to inform the user and then the user has to react.

**Comment by uok** [comment]
I agree with @cs42, just a simple warning box is enough. Also it would be great if Syncthing does not go crazy during this time, e.g. if the out of space is for a few days: temporary files are usually deleted every 24h, so it will then download the same file again only to find that there is not enough space. Maybe Syncthing can disconnect itself from the other nodes?

**Comment by Zillode** [comment]
@dcarosone sounds interesting, but I believe we should simply exit as a default. Feel free to open a new issue to propose accommodating actions. However, I could see that we start cleaning up files in .stversions because another process is filling the disk, this is not what I want at least.

@uok It will simply exit because changes to the filesystem can increase the size of the db.

**Comment by uok** [comment]
@Zillode I never have ST and the shared folders on the same this, so the DB will always have enough space. I also do not want automatic cleanup of .stversions, since this is sometimes the last resort to get an important file back

**Comment by Zillode** [comment]
@uok the current idea is to routinely check the paths of folders and exit (with a fail exit code) if one of them does not have enough disk space.

**Comment by canton7** [comment]
Can't we just put the appropriate folder(s) into a failed state? If the partition with Syncthing's database on it isn't the one running out of space, there's no reason to quit, surely?

**Comment by Zillode** [comment]
Good idea, will do

**Comment by AudriusButkevicius** [comment]
What if I have bind mounts... Within some subdirectory... In a btrfs volume on which normal space reporting tools don't work... which is mounted using cachefs fuse wrapper...

**Comment by calmh** [comment]
@AudriusButkevicius Then you're insane and deserve whatever happens to you. :D

I think something simple could possibly work here. When starting to pull a file, if we have less than the space required for the file in question, or less than a configurable percentage, then stop and abort. We default to some percentage. The whole thing can be disabled by setting the percentage to zero. If we can't determine the amount of free space, we carry on as before.
