### ISSUE TITLE
Configuration not saved after restart

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#2058]
Syncthing 0.11.14, Windows.

Steps to repro:

1) Add folder using the web UI
2) Restart syncthing as prompted
3) New folder does not appear in the web UI, and is not present in `config.xml`.

By the looks of it, the browser correctly posts the new folder config, and a subsequent get of `rest/system/config` retrieves it. However, it's lost on restart.

**Comment by canton7** [comment]
The new folder is present in the web UI but not the config up until the restart occurs.

**Comment by calmh** [comment]
Hm

**Comment by deepy** [comment]
Also happens on 0.11.12 windows amd64

**Comment by calmh** [comment]
v0.11.12? Are you sure?

**Comment by calmh** [comment]
Fixing...

**Comment by calmh** [comment]
Yeah, my new awesome `atomicwriter` isn't so awesome on Windows, because you can't overwrite a file by rename there. Needs delete+rename. Which is also not *atomic*, but that's Windows...

**Comment by calmh** [comment]
Fixed in v0.11.15, thanks people...

**Comment by dreaddymck** [comment]
Fresh headless install 
Ubuntu 15.10 (GNU/Linux 4.2.0-38-generic i686)

syncthing
v0.13.10, Linux (32 bit) 
"Copper Cockroach"

cannot save settings via gui...

Is there a quick cli fix?

**Comment by calmh** [comment]
Please don't grab a random year old windows specific issue as you are for sure seeing something entirely different. Please gather any error messages and screenshots as appropriate and open a new issue if it seems to be a bug. But reload the browser first.
