### ISSUE TITLE
Sync-conflict on all files in all synced folders after automatic update

### ISSUE THREAD

**Issue by abocanegra** [syncthing/syncthing#2067]
I need to know why, after automatically updating to the latest version of syncthing, all files have been renamed with adding sync-conflict and what looks like a timestamp to hundreds of thousands of files. This has caused a lot of damage to my work. Why did this happen, and are there any suggestions for how to fix the renaming issue with so many files. I am syncing across Linux, windows, and Android. There are no files left with proper names, all now include the sync-conflict. I have never manually deleted the db for any of the syncthing installs as I had seen mentioned in other posts.

**Comment by AudriusButkevicius** [comment]
You must have upgraded from 0.10 on one of the devices, that's the reason. You can do a quick bash script to rename all the files back.

**Comment by abocanegra** [comment]
Thank you. That was a frustrating 6 hours of batch renaming. I used the Bulk Rename Utility on Windows with regex match: (.+).+(sync-conflict-)+([0-9]*).+(-)++([0-9]*)+(.+) and replace \1\5. Now I have to figure out how to either rename or delete all of the conflicting files on my ubuntu server.

**Comment by AudriusButkevicius** [comment]
If you renamed them on one side, the renames can just be synced across.

**Comment by abocanegra** [comment]
Thanks again for all your help. One more question though. I was hoping it would remove the conflicting sync-conflict files automatically. there are about 700gb of them. However, it does not seem to be doing so. So far I have set every folder that is the primary to Master temporarily hoping this would make sure that all folders synced the structure of the master. Can you think of any reason why syncthing would not be able to delete the files? Initially I was getting the override changes popping up on some of the files. I clicked it and it would simply return. I have checked the permissions and syncthing has the ability to delete, and is syncing the new cleaned files, but not removing the conflict files.

**Comment by AudriusButkevicius** [comment]
Sorry, I need to understand what's happening on which side to be able to help you, as it's now not obvious.

**Comment by abocanegra** [comment]
Sorry for being unclear.
The issues have spread across all 7 systems I have syncing. Each system has it's own folders which are primary but all systems can typically change files. For the purposes of this I am focusing on 2 systems and treating the primary folders as master folders so the other systems are read only. 
For this coverersation the windows machine is master and the Linux server is read-only.
The data drive on the windows master is syncing to the server. All of the files on the master drive have been renamed or replaced from external backup so their names are now correct. 

The problem:
The server is receiving the corrected files. 
Syncthing is not removing the files that were renamed with *sync-conflict*
Since there are approximately 700gb of conflicting files having bad duplicates with the wrong names takes a lot of space 1.4 tb total. 
I would like to avoid deleting everything and starting from scratch. 

When I delete a sync-conflict file manually the master windows system shows an override changes button, which I press and eventually it will continue, but syncthing has not synced the read-only server with the master. It hasn't deleted a single sync-conflict file, but has synced the correct files.

Does this help?

**Comment by AudriusButkevicius** [comment]
It's now clear. 
So I think that the master does not have memory of the conflicts existing (did you reset the database?), hence it cannot tell the other device to delete them, as it simply doesn't know about them.

On linux you can do ```find /path/to/folder -name '*sync-conflict*' -delete ``` though I'd choose a more strict pattern.

**Comment by abocanegra** [comment]
I am very grateful for your rapid responses.

I have never reset the database. It is strange because every device shared the sync-conflict files. Since there are so many folders to go through I think I will wipe the back up and folders on all devices and start clean. I will try a recursive delete first.

Again thank you.

**Comment by AudriusButkevicius** [comment]
Unless you have a reproducible case, I don't see why this should be left open?

**Comment by AudriusButkevicius** [comment]
This should now be handled better with the latest release.

**Comment by joopdorresteijn** [comment]
Method described by AudriusButkevicius was to rigid for me, cleaned things up with bash on my end. https://github.com/joopdorresteijn/dotfiles/blob/master/scripts/syncconflict.sh
