### ISSUE TITLE
MacOS Cat not remove directory

### ISSUE THREAD

**Issue by charleyzhu** [syncthing/syncthing#2068]
[GLPQQ] 18:29:59 INFO: Puller (folder "repack", dir "OneMoneyGain/Payload/1MoneyGain.app"): delete: remove /Volumes/iOSData/repack/OneMoneyGain/Payload/1MoneyGain.app: directory not empty

**Comment by AudriusButkevicius** [comment]
Check whats in the directory, and make sure it doesn't match any of your ignores.

**Comment by charleyzhu** [comment]
yes,this directory ignores a file, How should I do.

**Comment by AudriusButkevicius** [comment]
You should remove the file in order for syncthing to be able to continue.
