### ISSUE TITLE
Option to disable UI animations

### ISSUE THREAD

**Issue by cdhowie** [syncthing/syncthing#2069]
I'd love an option that disables the web UI animations.  When manipulating a remote Syncthing over RDP for example, the transitions can take 10+ seconds.  (Changing the GUI listen address and opening an SSH tunnel to the Windows box is a workaround, but sometimes -- particularly when I'm already remoted into the Windows box for something else -- it's easier just to do it within the RDP session.)

**Comment by canton7** [comment]
For reference: https://github.com/twbs/bootstrap/issues/5764 and https://github.com/twbs/bootstrap/pull/16157

**Comment by canton7** [comment]
`$.support.transition = false` seems to help: the accordion animations are disabled and I think some of the animation around modal dialogs goes away, but the modals still slide down from the top of the window.

Adding
```css
* *:before *:after {
    transition: none !important;
}
```

seems to get rid of the modal slides, as well.

**Comment by andersonvom** [comment]
This seems way too specific of a case. It sounds to me this is more of a [userscript](http://userscripts-mirror.org/) use case than something that should be implemented. Adding more complexity to both the code and the UI doesn't seem like the best way to go, IMO.

Unless we want to fully disable all transitions definitely, I'd say this issue can be closed.

**Comment by AudriusButkevicius** [comment]
Agree. The user can customize the UI using STASSETS and satisfy his own usecase. I don't think we should care about this. I wouldn't mind there being a "Plain" theme, but the support for that has a separate ticket.
