### ISSUE TITLE
Global Announce Server Bug / Design Flaw

### ISSUE THREAD

**Issue by coolVariable** [syncthing/syncthing#2071]
Global announce server does not work with multiple devices:
devices (all on the same LAN) connect to the public IP of your discovery server (i.e. not its internal IP). Each device on then LAN sets itself up with a different external port through UPnP, then connects to the discovery server using its external address. 
The discovery server SHOULD then create records for all of the devices having the same IP, but different ports. All device-device connections will then use the same external IP, but different ports. 
This should continue to work as devices leave then LAN.

PROBLEM: IT DOES NOT WORK.

Alternatively, the devices should announce their public and private IP to the announce server, so that it can connect them depending on their location (ie public or private).

AGAIN: THIS DOES NOT WORK!

=> THE GLOBAL ANNOUNCE SERVER DOES NOT WORK AND SEEMS TO BE POINTLESS!!!

**Comment by AudriusButkevicius** [comment]
Wrong repo.
