### ISSUE TITLE
Beta channel for testing

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#2074]
Since we have all advanced settings available in the GUI it would be great to have an option for a "beta channel". Once checked Syncthing automatically updates to the (latest?) dev-builds. This would allow testing new features like delta indexes (#2020), Bolt DB (#2073) etc. with a wider audience and keep things stable as the user base continues to grow.

**Comment by AudriusButkevicius** [comment]
Beta channel of which branch? There are many branches. Given you are clever enough to discover them, you can just copy the jenkins build url and use the -upgrade-to option if you are interested.

I feel this is a reasonable amount of man hours for saving 2 man minutes of the curious 5 users.

**Comment by AudriusButkevicius** [comment]
We already have support for prereleases, though we don't release any.

**Comment by calmh** [comment]
You're already on the beta branch. :) We do a new beta release each week.

**Comment by uok** [comment]
"beta of beta" :wink: https://github.com/syncthing/syncthing/releases/tag/v0.12.0-beta0
this is what I meant with this option, users can opt in and receive versions with a "beta" tag

**Comment by calmh** [comment]
That's not an actual beta release though, it's just a tag to mark the break point between v0.11 and future v0.12. When there is an actual beta, it'll be released as usual and interested parties can shift to the beta track by downloading it - the beta will upgrade automatically to future betas, while non-betas do not.
