### ISSUE TITLE
Unefficient scanning of multi-level folders

### ISSUE THREAD

**Issue by xJMV** [syncthing/syncthing#2080]
Hi guys!

First off thanks for your great works! Syncthing is an awesome solution for my needs.

Here is one use I make of Syncthing: I have folders organized like this : /db/SUBJECT/SUB1/SUB2/FILE.EXT.

I have programs continuously adding files/folders to "/db/". Scan are set to occurs every 10minutes. I see Syncthing scanning and then get back to "Up To Date". Problem is that is takes about 12hours to find out a single new file when there is over 50files added every hours... I actually have around 1milion files in the folders, but only 800k are found yet (36hours running).

I am not JS dev, but the scanning method must be better. If someone can explain me the scanning process, I may try to help out with that issue.

**Comment by calmh** [comment]
Initial scan hashes all the files, which may take some time. After that, the scan simply looks at modification times. If a files modification time has changed, it's rehashed. Also if it's a new file, obviously. Does this answer your question?

**Comment by xJMV** [comment]
Actually I was hoping for more... I am not a Go coder, but I have some experience with PHP, Python, HTML, C++...

From what I just found in the source, the scanner will walk through folders and files and manage everything at once. This is somewhat inefficient in a constant changing folder or a folder containing too many files. It seems more suitable for folders with less files but bigger ones.

For folders with many files (from few b to few mb) it would be more suited to detect every folders and then scan folder by folder for files. It would allow the scanner to complete a scan properly instead of hanging like it does because files/folders that are created during the scan. On the next scan new files/folders will be detected...

I tested the scanner while all operations has been suspended (no files/folders added). After few minutes it returns "up to date" but no files added (counter showed 784230 for several scans). After several manual scan it the counter jumped to 792447 files. There is over 1million files in that folder...

I don't know if it is clear to you... If not let me know...

**Comment by xJMV** [comment]
I just noticed that even if folders do not update when files are added (even with few scans), the overall device stats does and it does update even without any folder scanning...

Actual folder "Local State" 	792493 items, ~1.17 GiB
Actual device "Local State (Total)" 	2015893 items, ~3.35 GiB

Divide device local state by 2 and you should get the folder local state...

**Comment by AudriusButkevicius** [comment]
I don't understand how can walking a directory tree can skip files. Yes it can skip it if it has gone past it, but surely if you are rescanning every 10 minutes and the scan completes within 10 minutes then the files should be found. If they are not, then you might have found a bug in go stdlib. Alternative issue could be the summary service, which recalculates values after a scan... But I'd be skeptical to believe that this takes 36 hours to update.

**Comment by AudriusButkevicius** [comment]
On a side note, @calmh we could compute the local state as we walk without touching the db.

**Comment by xJMV** [comment]
@AudriusButkevicius like I said, I am not a GO dev...

It takes several scans to add up few new files and get them synced. Most of the time, a single scan will not find out new files and will not attempt to sync any files (checked over both instance GUI)...

And for your info... The system used to add files is Debian and system receiving files are Windows7, Windows8 and Debian.

**Comment by AudriusButkevicius** [comment]
I suggest you set STTRACE=scanner envvar and look around for log entries related to the new files.

**Comment by AudriusButkevicius** [comment]
I find it hard to believe this bug, as we use the stdlib function for walking the tree, and I find it hard to believe stdlib has this bug given on the userbase.

 Are you using some fancy filesystem? 

As a work around, you can try and use the inotify bolton but that will probably break given the number of watchers required. But it'd rather understand what the issue is.

**Comment by AudriusButkevicius** [comment]
I don't mean whatever I said in `I don't believe you` kind of way, it more of `This is some crazy shit, this all makes no sense` kind of way.

**Comment by xJMV** [comment]
@AudriusButkevicius I was not mad at you ;) I just wanted to state that I might not be at the same level as you guys/gals are!

BTW no fancy FS... just a plain debian setup on the server not even in a VM...

Now quick question, how do we save logs to a file ? It will be easier to show it up here.

**Comment by AudriusButkevicius** [comment]
`syncthing | tee /tmp/log.file`

**Comment by xJMV** [comment]
Ok so here is a small log made. I changed some names for privacy/security reason... So you get it from the start...

I continue to save logs to file if you ever want something longer, I may send it over email unmodified... During this period, files and folders were added and I pressed rescan button once.

[monitor] 2015/07/22 16:59:40.013424 monitor.go:94: INFO: Starting syncthing
[LBYX3] 2015/07/22 16:59:40.616157 main.go:473: INFO: syncthing v0.11.16 (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-07-19 11:34:11 UTC
[LBYX3] 2015/07/22 16:59:40.616823 main.go:474: INFO: My ID: TNPRBKO-SSNDWTK-46VYNQN-YTXNGTH-TKMPEU6-3UFMUPL-6Q2JNKE-6GAYWAI
[LBYX3] 2015/07/22 16:59:40.621930 main.go:758: INFO: Database block cache capacity 65536 KiB
[LBYX3] 2015/07/22 16:59:43.584488 main.go:631: OK: Ready to synchronize project-library (read only; no external updates accepted)
[LBYX3] 2015/07/22 16:59:51.855993 main.go:631: OK: Ready to synchronize project-index-2015 (read only; no external updates accepted)
[LBYX3] 2015/07/22 16:59:51.856369 walk.go:87: DEBUG: Walk /home/user/PROJECT/database/library [] 131072 &{[] true 0xc208113fe0 d41d8cd98f00b204e9800998ecf8427e 0xc20814a720 0xc20f05e050}
[LBYX3] 2015/07/22 16:59:51.856405 walk.go:373: DEBUG: checkDir /home/user/PROJECT/database/library &{library 4096 2147484096 {63573033394 755035740 0xe1a3e0} 0xc210bdf200}
[LBYX3] 2015/07/22 16:59:51.856551 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:00:27.148510 rofolder.go:97: INFO: Completed initial scan (ro) of folder project-library
[LBYX3] 2015/07/22 17:00:27.148646 walk.go:87: DEBUG: Walk /home/user/PROJECT/database/INDEX/2015 [] 131072 &{[] true 0xc20ed93e20 d41d8cd98f00b204e9800998ecf8427e 0xc20f02e1e0 0xc20d376f50}
[LBYX3] 2015/07/22 17:00:27.148685 walk.go:373: DEBUG: checkDir /home/user/PROJECT/database/INDEX/2015 &{2015 4096 2147484096 {63573192539 324399659 0xe1a3e0} 0xc20dc3e1b0}
[LBYX3] 2015/07/22 17:00:27.148823 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:01:01.513048 rofolder.go:97: INFO: Completed initial scan (ro) of folder project-index-2015
[LBYX3] 2015/07/22 17:02:54.448896 main.go:631: OK: Ready to synchronize project-index-perm (read only; no external updates accepted)
[LBYX3] 2015/07/22 17:02:54.508166 walk.go:87: DEBUG: Walk /home/user/PROJECT/database/INDEX/perm [] 131072 &{[] true 0xc2113bffa0 d41d8cd98f00b204e9800998ecf8427e 0xc20b7b22a0 0xc21092c960}
[LBYX3] 2015/07/22 17:02:54.508200 walk.go:373: DEBUG: checkDir /home/user/PROJECT/database/INDEX/perm &{perm 4096 2147484096 {63573043606 763123260 0xe1a3e0} 0xc20d64a120}
[LBYX3] 2015/07/22 17:02:54.508334 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:02:54.561991 main.go:634: OK: Ready to synchronize project-share (read-write)
[LBYX3] 2015/07/22 17:02:54.689189 main.go:634: OK: Ready to synchronize project-software (read-write)
[LBYX3] 2015/07/22 17:02:54.689313 main.go:813: INFO: Starting web GUI on http://0.0.0.0:8384/
[LBYX3] 2015/07/22 17:02:54.689623 walk.go:87: DEBUG: Walk /home/user/PROJECT/share [] 131072 &{[] true 0xc210808e60 d41d8cd98f00b204e9800998ecf8427e 0xc20b32e480 0xc21137e228}
[LBYX3] 2015/07/22 17:02:54.689649 walk.go:373: DEBUG: checkDir /home/user/PROJECT/share &{share 4096 2147484096 {63573139029 143941060 0xe1a3e0} 0xc20e9e01b0}
[LBYX3] 2015/07/22 17:02:54.689735 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:02:54.690453 rwfolder.go:317: INFO: Completed initial scan (rw) of folder project-share
[LBYX3] 2015/07/22 17:02:54.690586 walk.go:87: DEBUG: Walk /home/user/PROJECT/software [] 131072 &{[] true 0xc2116a5000 d41d8cd98f00b204e9800998ecf8427e 0xc20b32e720 0xc20ed00520}
[LBYX3] 2015/07/22 17:02:54.690602 walk.go:373: DEBUG: checkDir /home/user/PROJECT/software &{software 4096 2147484096 {63573042507 939113843 0xe1a3e0} 0xc20e1ee480}
[LBYX3] 2015/07/22 17:02:54.690689 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:02:54.692790 rwfolder.go:317: INFO: Completed initial scan (rw) of folder project-software
[LBYX3] 2015/07/22 17:02:55.434282 main.go:889: INFO: Starting local discovery announcements
[LBYX3] 2015/07/22 17:02:55.434662 main.go:894: INFO: Starting global discovery announcements
[LBYX3] 2015/07/22 17:02:55.439509 main.go:680: INFO: Device TNPRBKO-SSNDWTK-46VYNQN-YTXNGTH-TKMPEU6-3UFMUPL-6Q2JNKE-6GAYWAI is "MyLaptop" at [dynamic]
[LBYX3] 2015/07/22 17:02:55.439918 main.go:680: INFO: Device UY6D2DU-MBM2G4Q-K7X23B2-LYIJVOU-OY2XCIR-ZZXE5NO-2EXF6YA-5MZHTAG is "SERVER" at [dynamic]
[LBYX3] 2015/07/22 17:02:55.440133 usage_report.go:154: INFO: Starting usage reporting
[LBYX3] 2015/07/22 17:02:55.455987 gui.go:221: INFO: API listening on [::]:8384
[LBYX3] 2015/07/22 17:02:55.769145 upnp.go:215: INFO: UPnP parse: unrecognized UPnP device of type uuid:f99e28d0-1dd1-11b2-af80-87333332f934
[LBYX3] 2015/07/22 17:02:55.769475 upnp.go:215: INFO: UPnP parse: unrecognized UPnP device of type uuid:f99f3d24-1dd1-11b2-b2d4-aacb0ad6c4ee
[LBYX3] 2015/07/22 17:02:55.769637 upnp.go:215: INFO: UPnP parse: unrecognized UPnP device of type uuid:f9a554d4-1dd1-11b2-8c9f-94450f749ee8
[LBYX3] 2015/07/22 17:02:55.769788 upnp.go:215: INFO: UPnP parse: unrecognized UPnP device of type uuid:f9aad24c-1dd1-11b2-ba5e-ad05d39be949
[LBYX3] 2015/07/22 17:02:56.592739 connections.go:176: INFO: Established secure connection to TNPRBKO-SSNDWTK-46VYNQN-YTXNGTH-TKMPEU6-3UFMUPL-6Q2JNKE-6GAYWAI at 192.168.0.103:49628-192.168.0.100:22000
[LBYX3] 2015/07/22 17:02:56.746293 model.go:626: INFO: Device TNPRBKO-SSNDWTK-46VYNQN-YTXNGTH-TKMPEU6-3UFMUPL-6Q2JNKE-6GAYWAI client is "syncthing v0.11.16"
[LBYX3] 2015/07/22 17:02:56.746669 model.go:631: INFO: Device TNPRBKO-SSNDWTK-46VYNQN-YTXNGTH-TKMPEU6-3UFMUPL-6Q2JNKE-6GAYWAI name is "MyLaptop"
[LBYX3] 2015/07/22 17:03:05.750838 upnpsvc.go:81: INFO: New UPnP port mapping: external port 55775 to local port 22001.
[LBYX3] 2015/07/22 17:03:34.966978 connections.go:176: INFO: Established secure connection to UY6D2DU-MBM2G4Q-K7X23B2-LYIJVOU-OY2XCIR-ZZXE5NO-2EXF6YA-5MZHTAG at 192.168.0.103:22001-192.168.0.101:51052
[LBYX3] 2015/07/22 17:03:39.226904 model.go:626: INFO: Device UY6D2DU-MBM2G4Q-K7X23B2-LYIJVOU-OY2XCIR-ZZXE5NO-2EXF6YA-5MZHTAG client is "syncthing v0.11.16"
[LBYX3] 2015/07/22 17:03:39.227010 model.go:631: INFO: Device UY6D2DU-MBM2G4Q-K7X23B2-LYIJVOU-OY2XCIR-ZZXE5NO-2EXF6YA-5MZHTAG name is "WorkLaptop"
[LBYX3] 2015/07/22 17:03:56.631283 walk.go:87: DEBUG: Walk /home/user/PROJECT/software [] 131072 &{[] true 0xc2116a5000 d41d8cd98f00b204e9800998ecf8427e 0xc20b32e720 0xc20ed00520}
[LBYX3] 2015/07/22 17:03:56.631347 walk.go:373: DEBUG: checkDir /home/user/PROJECT/software &{software 4096 2147484096 {63573042507 939113843 0xe1a3e0} 0xc20dfc6d80}
[LBYX3] 2015/07/22 17:03:56.684464 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:04:09.694467 walk.go:87: DEBUG: Walk /home/user/PROJECT/share [] 131072 &{[] true 0xc210808e60 d41d8cd98f00b204e9800998ecf8427e 0xc20b32e480 0xc21137e228}
[LBYX3] 2015/07/22 17:04:09.694503 walk.go:373: DEBUG: checkDir /home/user/PROJECT/share &{share 4096 2147484096 {63573139029 143941060 0xe1a3e0} 0xc208c50360}
[LBYX3] 2015/07/22 17:04:09.694634 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:04:49.361145 walk.go:87: DEBUG: Walk /home/user/PROJECT/software [] 131072 &{[] true 0xc2116a5000 d41d8cd98f00b204e9800998ecf8427e 0xc20b32e720 0xc20ed00520}
[LBYX3] 2015/07/22 17:04:49.361181 walk.go:373: DEBUG: checkDir /home/user/PROJECT/software &{software 4096 2147484096 {63573042507 939113843 0xe1a3e0} 0xc20c168bd0}
[LBYX3] 2015/07/22 17:04:49.361304 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:05:16.735174 walk.go:87: DEBUG: Walk /home/user/PROJECT/share [] 131072 &{[] true 0xc210808e60 d41d8cd98f00b204e9800998ecf8427e 0xc20b32e480 0xc21137e228}
[LBYX3] 2015/07/22 17:05:16.735204 walk.go:373: DEBUG: checkDir /home/user/PROJECT/share &{share 4096 2147484096 {63573139029 143941060 0xe1a3e0} 0xc20da58090}
[LBYX3] 2015/07/22 17:05:16.735291 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:05:54.391462 walk.go:87: DEBUG: Walk /home/user/PROJECT/software [] 131072 &{[] true 0xc2116a5000 d41d8cd98f00b204e9800998ecf8427e 0xc20b32e720 0xc20ed00520}
[LBYX3] 2015/07/22 17:05:54.391523 walk.go:373: DEBUG: checkDir /home/user/PROJECT/software &{software 4096 2147484096 {63573042507 939113843 0xe1a3e0} 0xc213bcfef0}
[LBYX3] 2015/07/22 17:05:54.391676 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:06:26.491661 walk.go:87: DEBUG: Walk /home/user/PROJECT/share [] 131072 &{[] true 0xc210808e60 d41d8cd98f00b204e9800998ecf8427e 0xc20b32e480 0xc21137e228}
[LBYX3] 2015/07/22 17:06:26.492093 walk.go:373: DEBUG: checkDir /home/user/PROJECT/share &{share 4096 2147484096 {63573139029 143941060 0xe1a3e0} 0xc20d3070e0}
[LBYX3] 2015/07/22 17:06:26.589684 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:06:46.961795 rofolder.go:97: INFO: Completed initial scan (ro) of folder project-index-perm
[LBYX3] 2015/07/22 17:06:46.962561 walk.go:87: DEBUG: Walk /home/user/PROJECT/database/INDEX/perm [] 131072 &{[] true 0xc2113bffa0 d41d8cd98f00b204e9800998ecf8427e 0xc20b7b22a0 0xc21092c960}
[LBYX3] 2015/07/22 17:06:46.962703 walk.go:373: DEBUG: checkDir /home/user/PROJECT/database/INDEX/perm &{perm 4096 2147484096 {63573043606 763123260 0xe1a3e0} 0xc212ec2870}
[LBYX3] 2015/07/22 17:06:46.963083 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:07:02.913174 walk.go:87: DEBUG: Walk /home/user/PROJECT/software [] 131072 &{[] true 0xc2116a5000 d41d8cd98f00b204e9800998ecf8427e 0xc20b32e720 0xc20ed00520}
[LBYX3] 2015/07/22 17:07:02.913216 walk.go:373: DEBUG: checkDir /home/user/PROJECT/software &{software 4096 2147484096 {63573042507 939113843 0xe1a3e0} 0xc208381950}
[LBYX3] 2015/07/22 17:07:02.913357 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:07:19.441965 walk.go:87: DEBUG: Walk /home/user/PROJECT/share [] 131072 &{[] true 0xc210808e60 d41d8cd98f00b204e9800998ecf8427e 0xc20b32e480 0xc21137e228}
[LBYX3] 2015/07/22 17:07:19.441997 walk.go:373: DEBUG: checkDir /home/user/PROJECT/share &{share 4096 2147484096 {63573139029 143941060 0xe1a3e0} 0xc2083970e0}
[LBYX3] 2015/07/22 17:07:19.442112 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:07:50.680408 walk.go:87: DEBUG: Walk /home/user/PROJECT/software [] 131072 &{[] true 0xc2116a5000 d41d8cd98f00b204e9800998ecf8427e 0xc20b32e720 0xc20ed00520}
[LBYX3] 2015/07/22 17:07:50.680439 walk.go:373: DEBUG: checkDir /home/user/PROJECT/software &{software 4096 2147484096 {63573042507 939113843 0xe1a3e0} 0xc210c0b830}
[LBYX3] 2015/07/22 17:07:50.680560 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:08:19.787284 walk.go:87: DEBUG: Walk /home/user/PROJECT/share [] 131072 &{[] true 0xc210808e60 d41d8cd98f00b204e9800998ecf8427e 0xc20b32e480 0xc21137e228}
[LBYX3] 2015/07/22 17:08:19.787324 walk.go:373: DEBUG: checkDir /home/user/PROJECT/share &{share 4096 2147484096 {63573139029 143941060 0xe1a3e0} 0xc20c4661b0}
[LBYX3] 2015/07/22 17:08:19.787444 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:08:56.769191 walk.go:87: DEBUG: Walk /home/user/PROJECT/software [] 131072 &{[] true 0xc2116a5000 d41d8cd98f00b204e9800998ecf8427e 0xc20b32e720 0xc20ed00520}
[LBYX3] 2015/07/22 17:08:56.769271 walk.go:373: DEBUG: checkDir /home/user/PROJECT/software &{software 4096 2147484096 {63573042507 939113843 0xe1a3e0} 0xc211e2cd80}
[LBYX3] 2015/07/22 17:08:56.769605 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:09:18.802482 walk.go:87: DEBUG: Walk /home/user/PROJECT/share [] 131072 &{[] true 0xc210808e60 d41d8cd98f00b204e9800998ecf8427e 0xc20b32e480 0xc21137e228}
[LBYX3] 2015/07/22 17:09:18.802521 walk.go:373: DEBUG: checkDir /home/user/PROJECT/share &{share 4096 2147484096 {63573139029 143941060 0xe1a3e0} 0xc20ef482d0}
[LBYX3] 2015/07/22 17:09:18.802627 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:09:45.283064 walk.go:87: DEBUG: Walk /home/user/PROJECT/software [] 131072 &{[] true 0xc2116a5000 d41d8cd98f00b204e9800998ecf8427e 0xc20b32e720 0xc20ed00520}
[LBYX3] 2015/07/22 17:09:45.283106 walk.go:373: DEBUG: checkDir /home/user/PROJECT/software &{software 4096 2147484096 {63573042507 939113843 0xe1a3e0} 0xc20f79b8c0}
[LBYX3] 2015/07/22 17:09:45.283268 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:09:57.610782 walk.go:87: DEBUG: Walk /home/user/PROJECT/database/INDEX/perm [] 131072 &{[] true 0xc2113bffa0 d41d8cd98f00b204e9800998ecf8427e 0xc20b7b22a0 0xc21092c960}
[LBYX3] 2015/07/22 17:09:57.610866 walk.go:373: DEBUG: checkDir /home/user/PROJECT/database/INDEX/perm &{perm 4096 2147484096 {63573043606 763123260 0xe1a3e0} 0xc20ef497a0}
[LBYX3] 2015/07/22 17:09:57.611280 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:10:28.277351 walk.go:87: DEBUG: Walk /home/user/PROJECT/share [] 131072 &{[] true 0xc210808e60 d41d8cd98f00b204e9800998ecf8427e 0xc20b32e480 0xc21137e228}
[LBYX3] 2015/07/22 17:10:28.277436 walk.go:373: DEBUG: checkDir /home/user/PROJECT/share &{share 4096 2147484096 {63573139029 143941060 0xe1a3e0} 0xc216a981b0}
[LBYX3] 2015/07/22 17:10:28.277735 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:10:43.051785 walk.go:87: DEBUG: Walk /home/user/PROJECT/database/INDEX/perm [] 131072 &{[] true 0xc2113bffa0 d41d8cd98f00b204e9800998ecf8427e 0xc20b7b22a0 0xc21092c960}
[LBYX3] 2015/07/22 17:10:43.051870 walk.go:373: DEBUG: checkDir /home/user/PROJECT/database/INDEX/perm &{perm 4096 2147484096 {63573043606 763123260 0xe1a3e0} 0xc2109242d0}
[LBYX3] 2015/07/22 17:10:43.052256 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:10:52.661044 walk.go:87: DEBUG: Walk /home/user/PROJECT/software [] 131072 &{[] true 0xc2116a5000 d41d8cd98f00b204e9800998ecf8427e 0xc20b32e720 0xc20ed00520}
[LBYX3] 2015/07/22 17:10:52.661081 walk.go:373: DEBUG: checkDir /home/user/PROJECT/software &{software 4096 2147484096 {63573042507 939113843 0xe1a3e0} 0xc211ec41b0}
[LBYX3] 2015/07/22 17:10:52.661382 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:11:30.644248 walk.go:87: DEBUG: Walk /home/user/PROJECT/share [] 131072 &{[] true 0xc210808e60 d41d8cd98f00b204e9800998ecf8427e 0xc20b32e480 0xc21137e228}
[LBYX3] 2015/07/22 17:11:30.644337 walk.go:373: DEBUG: checkDir /home/user/PROJECT/share &{share 4096 2147484096 {63573139029 143941060 0xe1a3e0} 0xc21030e360}
[LBYX3] 2015/07/22 17:11:30.644644 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:11:47.083921 walk.go:87: DEBUG: Walk /home/user/PROJECT/software [] 131072 &{[] true 0xc2116a5000 d41d8cd98f00b204e9800998ecf8427e 0xc20b32e720 0xc20ed00520}
[LBYX3] 2015/07/22 17:11:47.083963 walk.go:373: DEBUG: checkDir /home/user/PROJECT/software &{software 4096 2147484096 {63573042507 939113843 0xe1a3e0} 0xc21025da70}
[LBYX3] 2015/07/22 17:11:47.084129 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:12:30.839835 walk.go:87: DEBUG: Walk /home/user/PROJECT/database/INDEX/2015 [] 131072 &{[] true 0xc20ed93e20 d41d8cd98f00b204e9800998ecf8427e 0xc20f02e1e0 0xc20d376f50}
[LBYX3] 2015/07/22 17:12:30.839918 walk.go:373: DEBUG: checkDir /home/user/PROJECT/database/INDEX/2015 &{2015 4096 2147484096 {63573192539 324399659 0xe1a3e0} 0xc20e898360}
[LBYX3] 2015/07/22 17:12:30.840284 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:12:35.851959 walk.go:87: DEBUG: Walk /home/user/PROJECT/share [] 131072 &{[] true 0xc210808e60 d41d8cd98f00b204e9800998ecf8427e 0xc20b32e480 0xc21137e228}
[LBYX3] 2015/07/22 17:12:35.852039 walk.go:373: DEBUG: checkDir /home/user/PROJECT/share &{share 4096 2147484096 {63573139029 143941060 0xe1a3e0} 0xc20b3ce1b0}
[LBYX3] 2015/07/22 17:12:35.852341 walk.go:167: DEBUG: ignored: .stfolder
[LBYX3] 2015/07/22 17:12:36.707345 walk.go:312: DEBUG: dir: /home/user/PROJECT/database/INDEX/2015/SUBJECT/19/106343 File{Name:"SUBJECT/19/106343", Flags:040755, Modified:1437598849, Version:[{6373013433926168058 1}], Size:128, Blocks:[]}
[LBYX3] 2015/07/22 17:12:36.709876 walk.go:312: DEBUG: dir: /home/user/PROJECT/database/INDEX/2015/SUBJECT/19/191425 File{Name:"SUBJECT/19/191425", Flags:040755, Modified:1437599310, Version:[{6373013433926168058 1}], Size:128, Blocks:[]}
[LBYX3] 2015/07/22 17:12:36.711605 walk.go:312: DEBUG: dir: /home/user/PROJECT/database/INDEX/2015/SUBJECT/19/254958 File{Name:"SUBJECT/19/254958", Flags:040755, Modified:1437599367, Version:[{6373013433926168058 1}], Size:128, Blocks:[]}
[LBYX3] 2015/07/22 17:12:36.713762 walk.go:312: DEBUG: dir: /home/user/PROJECT/database/INDEX/2015/SUBJECT/19/31910 File{Name:"SUBJECT/19/31910", Flags:040755, Modified:1437598932, Version:[{6373013433926168058 1}], Size:128, Blocks:[]}
[LBYX3] 2015/07/22 17:12:36.714140 walk.go:312: DEBUG: dir: /home/user/PROJECT/database/INDEX/2015/SUBJECT/19/33435 File{Name:"SUBJECT/19/33435", Flags:040755, Modified:1437598932, Version:[{6373013433926168058 1}], Size:128, Blocks:[]}
[LBYX3] 2015/07/22 17:12:36.717394 walk.go:312: DEBUG: dir: /home/user/PROJECT/database/INDEX/2015/SUBJECT/19/422971 File{Name:"SUBJECT/19/422971", Flags:040755, Modified:1437599265, Version:[{6373013433926168058 1}], Size:128, Blocks:[]}
[LBYX3] 2015/07/22 17:12:36.718789 walk.go:312: DEBUG: dir: /home/user/PROJECT/database/INDEX/2015/SUBJECT/19/46473 File{Name:"SUBJECT/19/46473", Flags:040755, Modified:1437599102, Version:[{6373013433926168058 1}], Size:128, Blocks:[]}
[LBYX3] 2015/07/22 17:12:36.719011 walk.go:312: DEBUG: dir: /home/user/PROJECT/database/INDEX/2015/SUBJECT/19/472617 File{Name:"SUBJECT/19/472617", Flags:040755, Modified:1437599364, Version:[{6373013433926168058 1}], Size:128, Blocks:[]}
[LBYX3] 2015/07/22 17:12:36.719472 walk.go:312: DEBUG: dir: /home/user/PROJECT/database/INDEX/2015/SUBJECT/19/482939 File{Name:"SUBJECT/19/482939", Flags:040755, Modified:1437599322, Version:[{6373013433926168058 1}], Size:128, Blocks:[]}
[LBYX3] 2015/07/22 17:12:36.722808 walk.go:312: DEBUG: dir: /home/user/PROJECT/database/INDEX/2015/SUBJECT/19/97658 File{Name:"SUBJECT/19/97658", Flags:040755, Modified:1437599193, Version:[{6373013433926168058 1}], Size:128, Blocks:[]}
[LBYX3] 2015/07/22 17:12:41.519267 walk.go:152: DEBUG: temporary: SUBJECT_2/7/24/.syncthing.7.data.tmp
[LBYX3] 2015/07/22 17:12:43.269080 walk.go:152: DEBUG: temporary: SUBJECT_3/14/11831/.syncthing.14925.data.tmp
[LBYX3] 2015/07/22 17:12:44.686891 walk.go:152: DEBUG: temporary: SUBJECT_3/17/79035/.syncthing.38783.data.tmp

**Comment by AudriusButkevicius** [comment]
So what are the paths of the files that are missing, and which directory are they in?

**Comment by xJMV** [comment]
Files are inside /home/user/PROJECT/database/INDEX/PERM/SUBJECT_<1-15>/<XXX>/<XXX>/<XXX>.EXT

<XXX> can be replaced by defined index ranging from 0 to 1 000 000 (Generated by my own program)

**Comment by xJMV** [comment]
Proof of error : 
$ ls -R | wc -l
1440900

 Folder Local State 	792493 items, ~1.17 GiB

**Comment by AudriusButkevicius** [comment]
Are you using symlinks?

**Comment by xJMV** [comment]
negative. files stored straight to the said folders...

**Comment by AudriusButkevicius** [comment]
Once the build completes, download it, run it with STTRACE=scanner again and upload the log somewhere (or email it to me) and tell me which files exactly are missing.
This will print every file/dir that it walks, hence expect tons of lines.

**Comment by xJMV** [comment]
Comparing for missing file will be a PITA... I need to stop the programs first (it may takes a while for operations to get done...). For the last 2 or 3 syncs, many files have been synced (around 15mb) and that could have been what was missing...

There is also chances that items count might not be counted properly...

**Comment by AudriusButkevicius** [comment]
Try `find -L /path/to/folder -type l`, I am pretty sure that you have symlinks or some device nodes or something else that syncthing doesn't sync somewhere.

**Comment by xJMV** [comment]
UPDATE: Now both instances GUI show same files count and size after sync. =D

But items count is not right if you compare with OS issued command... I'll stop everything for the weekend and compare both system file listing to see if everything is now properly sync. If everything is synced, then the item count is broken.

as for symlinks : 
s$ find -L ~/project/database/index/ -type l
user@system:~/project/database/index$

**Comment by xJMV** [comment]
Ok, sync process seems to be resumed properly... I followed using some test files and files have been synced on last scan...

I will setup VMs this weekend and try to replicate that using part of data to test it out... Will get back to you if it can be recreated. 

Thanks for your patience and your great work! :+1:
