### ISSUE TITLE
UTF8 encoding

### ISSUE THREAD

**Issue by SJablonska** [syncthing/syncthing#2086]
Hi,

I have autoNormalize switched on on all folders.

However, I am still getting messages such as: 
"2015-07-23 11:32:02: File name "BR_ForexTrada/www.forextrada.com/it-IT/News/L\xe2%80%99impennata del dollaro si ferma dopo la decisione della Fed.html" is not in UTF8 encoding; skipping."

Steve

**Comment by calmh** [comment]
As the error message says, that file name is not in UTF-8 format. We don't know what it means, so we can't properly sync it to some other device.

**Comment by SJablonska** [comment]
I am probably mistaken, but I thought autoNormalize would solve such inconsistent UTF encoding

**Comment by calmh** [comment]
Yes. But this isn't inconsistent UTF-8. This is not being UTF-8 at all. The weird part in that file name is `\xE2%80%90`. It's probably been mangled by some other program earlier. Rename it and you'll be fine.
