### ISSUE TITLE
Reload configuration without restart

### ISSUE THREAD

**Issue by gyger** [syncthing/syncthing#2089]
This is an enhancement request, a lot of changing the configuration needs restarting the application. I think most of the configuration changes could be seamlessly reloaded.

**Comment by rumpelsepp** [comment]
Please search the tracker before posting: https://github.com/syncthing/syncthing/pull/2087

**Comment by calmh** [comment]
Also #2084

**Comment by calmh** [comment]
Although those are pull requests, so not actually returned in the search results on the issue page, by default. Anyway. Progress! :dancers:
