### ISSUE TITLE
Ignoring folder except for one subfolder

### ISSUE THREAD

**Issue by martinraison** [syncthing/syncthing#2091]
I'm trying to setup my `.stignore` such that `/foo/bar` is synced, but the rest of `/foo` is hidden. The following solution doesn't work (`/foo/bar` is ignored)

    !/foo/bar
    /foo

I guess it may be because the walker sees `/foo` first and prunes it, so `/foo/bar` is not even being considered. Is there an obvious workaround that I missed? I temporarily had to modify the source code to be able to pass regexes directly (bypassing the fnmatch.go stuff).

**Comment by AudriusButkevicius** [comment]
Is it actually deeper than foo/bar? And foo/bar is just an example you gave?

**Comment by martinraison** [comment]
Yes, `foo/bar` has a bunch of subfolders (which I want to sync as well): `foo/bar/a`, `/foo/bar/b`, etc.
And `foo/bar` is just an example - but in case you're wondering, my folder names don't have anything fancy, just simple lower-case letters.

**Comment by AudriusButkevicius** [comment]
It's not the names I am referring to. I am referring to the depth of the stuff you are trying to exclude from ignores.

For example if you want to ignore everything apart from a/b/c/d your patterns should be something like this:
```
!a/b/c/d
!a/b/c
!a/b
!a
*
```

**Comment by martinraison** [comment]
The problem is that if I add a `!a`, then `!a/**` gets automatically added as well: https://github.com/syncthing/syncthing/blob/master/internal/ignore/ignore.go#L273-276

So all the subfolders of `a` are included in the sync

**Comment by AudriusButkevicius** [comment]
I think you might need to do `!a/`

**Comment by martinraison** [comment]
If I do that I have the same issue, since `!a/**` will get added as well :) https://github.com/syncthing/syncthing/blob/master/internal/ignore/ignore.go#L268-271

**Comment by martinraison** [comment]
Ah, got it. Cool trick, thanks :)

**Comment by martinraison** [comment]
Btw, for anyone else having the same issue, here is the full final solution for me:

```
!/foo/bar
/foo/
!/foo
```

The trick being the `/` at the end of the second line, which makes sure that subfolders or `/foo` are ignored (except for `/foo/bar`) but `/foo` itself is included (because it doesn't match the second line but it matches the third line).
