### ISSUE TITLE
Global State & Local State match until syncing starts

### ISSUE THREAD

**Issue by rbraddock** [syncthing/syncthing#2095]
Howdy. First of all the project looks great - I love some of the design choices you made and the system seems well thought out. That said I have an issue.

I setup 2 machines and 1 share

Machine 1 is the server (Windows, exFAT) and it currently hosts 15000 files inside this shared folder. I added it, scanned it, and set this to the master and to ignore perms. The scan completed and found all files. At this stage Local & Global state matched which I understood.
![image](https://cloud.githubusercontent.com/assets/1328944/8938829/d5ae4ea4-3558-11e5-9243-fa7d4a9155ff.png)

The single share was shared out to Machine 2 (Debian ext4). The folder I chose on Machine 2 was purposefully empty as I wanted to understand how quickly Syncthing could get Machine 2 up-to-date with Machine 1. 

As soon as the machines start to sync the console on Machine 1 shows it's now out of sync 
![image](https://cloud.githubusercontent.com/assets/1328944/8938868/fd096fe2-3558-11e5-86b9-4d2b10004bce.png)

When I stop Syncthing on Machine 2 the console goes back to Local & Global matching.

Since Machine 2's folder is empty how can it knock down the Global State or make the Master on Machine 1 out of sync?

**Comment by AudriusButkevicius** [comment]
Are you sure that Machine 2 has never seen any files before?
Also, did Machine 2 suddenly bump mtimes/change content of the files causing them to be out of sync?

You can enable `STTRACE=model` to see what indexes you are receiving as you connect.
Given M2 has never seen any files it should not send an index, if it does, it means it has seen some files before.
