### ISSUE TITLE
Message does not always switch vom "Syncing 100% -Synchronisiere 100%" to "Aktuell - Up to date"

### ISSUE THREAD

**Issue by ErichHeer** [syncthing/syncthing#2096]
I have a minor bug. 

The message for the clients/devices is not always updating. Somtimes the message does not switch vom Syning 99% .... 100% to "Up to date". the message "Syncing 100%" stays.

**Comment by AudriusButkevicius** [comment]
It's usually because something stays out of sync, due to some reason. Check the out of sync modal to figure out what it is.

**Comment by ErichHeer** [comment]
Thank you.  You may be correct. It could be an open file. I will check.

 

Thank you for your help.

 

Erich 

 

Von: Audrius Butkevicius [mailto:notifications@github.com] 
Gesendet: Mittwoch, 29. Juli 2015 10:40
An: syncthing/syncthing
Cc: ErichHeer
Betreff: Re: [syncthing] Message does not always switch vom "Syncing 100% -Synchronisiere 100%" to "Aktuell - Up to date" (#2096)

 

It's usually because something stays out of sync, due to some reason. Check the out of sync modal to figure out what it is.
