### ISSUE TITLE
ignore pattern (?i) not working correctly for subfolders

### ISSUE THREAD

**Issue by Andy2244** [syncthing/syncthing#2102]
```
.stignore:
profile/minidumps
profile/*.sqlite-wal
```
vs
```
.stignore:
(?i)profile/minidumps
(?i)profile/*.sqlite-wal
```

The first case will ignore the "minidumps" folder and all "*.sqlite-wal" files inside the "profile" folder. However the second case, which should just do the same but case-insensitive, is not working at all?

It seem to work correctly for single file/folder entries like this, but not if sub-folder filtering is involved?
```
.stignore:
(?i)*.tmp
(?i)*.bak
(?i)System Volume Information
```

PS: Tested on Win7/10 with v0.11.17 (64 bit)

**Comment by AudriusButkevicius** [comment]
Can you get the patterns from the api call (made when opening ignores in the web ui) which should show the regular expressions it produced,for reference.

**Comment by Andy2244** [comment]
I actually use it via "#include .stglobalignore", but if i copy a entry in the ".stignore" file the webgui will show the entries exactly as if opened with a text editor. I don't see any change viewing the entries via webgui?

**Comment by AudriusButkevicius** [comment]
That's not what I am saying. I am saying look at the ajax request that is being fired when you open the ignores editor modal in the webui. If you don't know how to do that, then it doesn't matter.

**Comment by Andy2244** [comment]
```
(?i)profile/*.sqlite-wal
```
produces
```
{"ignore":["(?i)profile/*.sqlite-wal"],"patterns":["(?i)^profile\\\\[^\\\\]*\\.sqlite-wal$","(?i)^.*
\\\\\\([^\\\\]i\\)profile\\\\[^\\\\]*\\.sqlite-wal$","(?i)^profile\\\\[^\\\\]*\\.sqlite-wal\\\\.*$","
(?i)^.*\\\\\\([^\\\\]i\\)profile\\\\[^\\\\]*\\.sqlite-wal\\\\.*$"]}
```

**Comment by AudriusButkevicius** [comment]
Try using `/` and report what the patterns look like then.

**Comment by AudriusButkevicius** [comment]
Also feels like #1953

**Comment by Zillode** [comment]
Dup of #1953 
There is a distinction between text patterns and regex patterns. A regex pattern, i.e. containing ```(?i)``` etc, does not translate to ```.*``` (although ```(?i)profile/.*.sqlite-wal``` would probably not work, unsure)

**Comment by calmh** [comment]
The distinction above isn't intended, this is a clear bug and should be fixed. Sorry.
