### ISSUE TITLE
Backup: Format device, want to use same id + settings as before

### ISSUE THREAD

**Issue by Gibbz** [syncthing/syncthing#2110]
Im about to format my server, which has syncthing installed.
Last time i did this i had to reconfigure syncthing on every device i own. This was a real pain!

Is there a way to backup then restore the syncthing settings? Using linux...

**Comment by wweich** [comment]
This kind of questions should be asked in the forums, not on github ;).

You should backup the 4 `*.pem` files in `~/.config/syncthing` and perhaps the `config.xml`. The `config.xml`should only be reused, if the new server has all the shared folders in the same place.
Depending on your startup script, the files could be located elsewhere. In this case you need to check the script.
