### ISSUE TITLE
Out of Sync error with .stignore in use

### ISSUE THREAD

**Issue by assigerasiate** [syncthing/syncthing#2112]
I am running syncthing version v0.11.17, Linux (64 bit) on Archlinux straigt from the repository, updated 5 seconds ago.

We are using syncthing to syncronize project files across multiple ~10 computers and 2 servers.
To ignore temporary files a file called stignore is included in the directory. We encourage symlinking that to .stignore, but it is quite likely that some users did not do that.

Problem: when opening the SyncthingWebGui or using syncthing-gtk a red Out of Sync is displayed next to our project folder. Looking at the details shows that all Out of Sync items should be ignored by the .stignore. Additionally there is an Entry called Failed items, which does not contain any further information but just  "..." instead.

While this does not really influence our workflow, it is visually distracting and makes people unsure if they are synced or not.

This issue might be related to https://github.com/syncthing/syncthing/issues/561

**Comment by assigerasiate** [comment]
A workaround was to remove the symlink to stignore, restart syncthing, delete all files matching the stignore manually, waiting for that change to be synced, relink stignore to .stignore and restart syncthing.

But thats kinda uncomfy

**Comment by AudriusButkevicius** [comment]
So the console log should have more information as to why the sync failed.
Though its not exactly clear to me what is the issue here.
The fact that ignored files appeared out of sync?
