### ISSUE TITLE
Set “hidden” property on .stfolder and .stignore on Windows

### ISSUE THREAD

**Issue by Aeyoun** [syncthing/syncthing#2114]
To hide it from users and prevent accidental deletion.

**Comment by Zillode** [comment]
This should already be the case, see [here](https://github.com/syncthing/syncthing/blob/b1dd704819e1b76da6d5daa265779f34f11a1b21/internal/config/config.go#L130) and [here](https://github.com/syncthing/syncthing/blob/b1dd704819e1b76da6d5daa265779f34f11a1b21/internal/osutil/hidden_windows.go#L13).

**Comment by AudriusButkevicius** [comment]
Thats marker. I think we loose it on save

**Comment by Aeyoun** [comment]
Ah, they’re only visible until I restart the client once or twice. Then this isn’t as important as I thought.

**Comment by AudriusButkevicius** [comment]
We're missing osutil.Hide here: 
https://github.com/syncthing/syncthing/blob/master/internal/model/model.go#L903

**Comment by Zillode** [comment]
@Aeyoun willing to give it a shot?

**Comment by Aeyoun** [comment]
How about that?  #2121

**Comment by Zillode** [comment]
:+1: Thanks!
