### ISSUE TITLE
Node ID not accepted

### ISSUE THREAD

**Issue by arnotixe** [syncthing/syncthing#2118]
The following ID was generated on a fresh install on a linux mint machine, but was not accepted on the other machine, saying it is wrong:
5LJVIFG-CWUBSTF-5SZOLOL-2N5UJV7-DQRYQOS-JIHN4AG-P5S6FGK-SRAU2Q5

The ID was copied via a text file, not typed.

Reading up on check bits (https://forum.syncthing.net/t/v0-9-0-new-node-id-format/478) I tried removing last character on the end of group 2,4,6,8 and adding that by hand to config.xml:

5LJVIFG-CWUBST-5SZOLOL-2N5UJV-DQRYQOS-JIHN4A-P5S6FGK-SRAU2Q
Successfully started syncthing and opened my by-hand-added-device in the web GUI, and the ID now has the correct(?) check bytes added:
5LJVIFG-CWUBSTF-5SZOLOL-2N5UJV7-DQRYQOS-JIHN4AO-P5S6FGK-SRAU2Q5

Note that, in the GUI, check byte "O" appears instead of "G" at end of block 6. 

Don't know whether the machine actually connects yet (the guy with the computer went home), so I can't tell if it's the checksum that is bad or the ID that is bad... Can probably get more data, or certificates and all, if you need it.

[The check bytes aren't written back to config.xml on syncthing restart, but that might be by design.]

**Comment by calmh** [comment]
Can you paste the keys (and of course throw them away and use a different one) that generates that incorrect node ID? I have a hard time seeing how we would generate one check digit at startup and another when saving the config...
