### ISSUE TITLE
File name limited to 64 characters?

### ISSUE THREAD

**Issue by dpc** [syncthing/syncthing#2120]
Hi,

It seems to me that this code:

https://github.com/syncthing/syncthing/blob/d3972b88f2fe3e50882aa3dc2ca4b06ada29caee/internal/db/leveldb.go#L149

artificially limits the file name length to 64 characters. 

For anyone using encfs, this is simply to little.

**Comment by AudriusButkevicius** [comment]
Its folder (syncthing folder) name limit.
