### ISSUE TITLE
Syncthing corrupts file if a file that's still in the write-process is synced

### ISSUE THREAD

**Issue by KopfKrieg** [syncthing/syncthing#2122]
I know the title might not be easy to understand, so let me explain it:

If you download (for example) a 1GB file using Firefox (or any other webbrowser) into a directory that is synced using Synchting and another device is also running Syncthing, the file gets corrupted.

This only happens if I download large files (>300MB @ 2MB/s) and only, if the file is synced at the same time to another device. Syncthing should just ignore the file, until the write-process (e.g. the download) has finished.

I'm sorry I can't provide code to resolve the issue. My idea is to check if there's an open file descriptor from another program open (should be possible) and just ignore the file.

Tested on Arch Linux (syncthing v0.11.18) and an Android device (syncthing v0.11.13)

**Comment by AudriusButkevicius** [comment]
We don't write to files, we write a temp file and then move it in place once it finishes, so there is no way we could corrupt it, unless tge other side is also writing to it  looking up file descriptors et al requires root/admin and doesn't work reliably cross platform.

**Comment by KopfKrieg** [comment]
So, I tried to provoke the behaviour but it seems impossible now. I swear I ran into the issue multiple times (including a few corrupted files), and it really bugs me that I can't reproduce it at the moment.

I hope it's okay if I just close the issue and apologize for wasting your time (sorry about that).

**Comment by AudriusButkevicius** [comment]
No worries, but please do reopen it if you can reproduce it, as corruption is not something that should be ignored.

**Comment by KopfKrieg** [comment]
Well, if I find a way to reproduce the behaviour, then of course I'll reopen the issue (on the other hand I'm perfectly fine with the fact that no matter what I try my files don't get corrupted).
