### ISSUE TITLE
expose cpu load limit parameter in the web gui

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [syncthing/syncthing#2123]
currently, the following is required to limit cpu load:
https://forum.syncthing.net/t/limiting-syncthings-cpu-load/2237
https://golang.org/pkg/runtime/

it would rather help to expose cpu load limit parameter in the web gui

**Comment by Andrei-Pozolotin** [comment]
granularity is another problem:
GOMAXPROCS can not be a fraction, so 1 unit means 100% CPU 
and that is too much for a laptop use case.
how can we have 10% CPU limit?

**Comment by calmh** [comment]
Is there some other popular program that has such a setting?

**Comment by AudriusButkevicius** [comment]
If yoi run linux, use cgroups, on windows set it to low priority.
I don't think there is a way for the application to tell the OS scheduler to to schedule it at 10% usage limit. GOMAXPROCS tells the OD how many cores it wants to use, which does have an API on most OS'es, so I think what you are asking is impossible.

**Comment by rumpelsepp** [comment]
Since (on linux) syncthing ships with systemd service files, you could enable some features yourself using `systemctl [--user] edit syncthing.service`: http://man7.org/linux/man-pages/man5/systemd.cgroup.5.html

**Comment by Andrei-Pozolotin** [comment]
thank you for reminding me of "linux" :-)
so to achieve CPU limit/usage granularity,
looks like an easy way would be convert all ST instances into docker
and in fact use ```cgroups``` parameters https://docs.docker.com/reference/run/
```
--cpu-period=0: Limit the CPU CFS (Completely Fair Scheduler) period
--cpu-quota=0: Limit the CPU CFS (Completely Fair Scheduler) quota
```

**Comment by AudriusButkevicius** [comment]
Yeah, but that's a job for the user.
