### ISSUE TITLE
Devices not seeing each other

### ISSUE THREAD

**Issue by TheChymera** [syncthing/syncthing#2125]
I want to share a folder with a friend. We exchanged IDs, added each other, and I selected to share that one specific folder with his device. However, our devices each show that the other is offline.

Any ideas what coud be wrong, or how I can debug this further?

**Comment by AudriusButkevicius** [comment]
http://docs.syncthing.net/users/firewall.html#firewall-setup
If both of you are behind a NAT make sure atleast one is forwarding ports or succeeds getting a UPnP mapping (says in log)

**Comment by TheChymera** [comment]
@AudriusButkevicius it seems to me that I, at least, have a UPnP mapping:

```
Aug 06 11:51:01 zenbookhost syncthing[5099]: [2J3KM] INFO: Starting usage reporting
Aug 06 11:51:01 zenbookhost syncthing[5099]: [2J3KM] INFO: API listening on 127.0.0.1:8384
Aug 06 11:51:04 zenbookhost syncthing[5099]: [2J3KM] INFO: New UPnP port mapping: external port 25302 to local port 22000.
```

**Comment by AudriusButkevicius** [comment]
That's fine. Do you both have global discovery enabled?
Try downloading http://build.syncthing.net/job/syncthing-utils/ and using stfinddevice to check what external IP the global discovery server reports for you, and verify that the router is correctly forwarding the UPnP port. The friend can run `openssl s_client connect <address reported by discovery server>` to see if he can actually connect to you.

**Comment by TheChymera** [comment]
ok, it seems my friend got so frustrated that he doesn't want to use syncthing with me anymore....

But I myself have two machines which have trouble seeing each other: my laptop and desktop computers.

my desktop is always on, and I use my laptop every day, at work, and also at home (which is on the same LAN as my desktop). Still, in spite of that it seems they last saw each other July 26. Right now I have them right next to each other, with syncthing opened on each of them, and each happily tells me the last is disconnected. How can I debug this?

**Comment by AudriusButkevicius** [comment]
As I suggested, start a thread in the forums.
