### ISSUE TITLE
GUI Regression: cannot check devices when sharing a folder

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing#2130]
In current version (master 8f2294bbd4ae0012935adfefe38273161c97e644)
Similar to #2029, #2030, works in firefox, does not work in Chrome

**Comment by canton7** [comment]
#1954 messed up - he reverted things like #2030.

This might need a very careful audit to see what else was accidentally reverted.

**Comment by canton7** [comment]
You'll likely find that you can't check folders to share with a device, either
