### ISSUE TITLE
folder marker missing

### ISSUE THREAD

**Issue by Gibbz** [syncthing/syncthing#2132]
ive had to restore my backup on one of my machines of some data. But now i get an error saying 
"folder marker missing"
Is there any way to force a refresh/reset of that one without having to delete and re-add it?

**Comment by uok** [comment]
make sure that you have the right folder and create an empty file named `.stfolder` in it

**Comment by Gibbz** [comment]
ah thats fixed it, can close this bug.
Would be handy to have a feature in the webgui that does this for you however...

**Comment by uok** [comment]
(Syncthing adds .stfolder, if you add a new Syncthing folder)
please click close

**Comment by calmh** [comment]
This is really a special case, as you're doing something that is potentially dangerous (but fine in this case) which the `.stfolder` mechanics is intended to protect against. I think we're Ok as is.
