### ISSUE TITLE
Cannot delete empty folder on windows xp (32 bit) 

### ISSUE THREAD

**Issue by kononenko-nikolay** [syncthing/syncthing#2133]
the problem occurs on a PC with windows xp (32 bit). reproduced in 100% cases. 
If you delete a folder on any node (not windows xp) is a catalog of all deleted and the PC with windows xp remains complete structure of folders (empty). 
syncthing running on system account (the highest law) and ntfs right there and write and delete. no process uses these directories can be easily manually removed.
If you connect this catalog to a different host (for windows7 or linux) is on them is not a problem, all nodes are removed and empty directories remain only on a PC with windows xp

Version v0.11.18, Windows (32 bit)
![screenshot](https://cloud.githubusercontent.com/assets/13704234/9149572/30185b38-3db9-11e5-9b45-11c4738ee073.PNG)

install syncthing a virtual machine with windows xp, problem still exists.

[OOCJB] 01:13:42 INFO: Puller (folder "shop29", dir "TeamViewerPortable\\Data\\settings"): delete: remove \\?\C:\syncthing\shop29\TeamViewerPortable\Data\settings: The process cannot access the file because it is being used by another process.
[OOCJB] 01:13:42 INFO: Puller (folder "shop29", dir "TeamViewerPortable\\Data\\PortableApps.comInstaller"): delete: remove \\?\C:\syncthing\shop29\TeamViewerPortable\Data\PortableApps.comInstaller: The process cannot access the file because it is being used by another process.
[OOCJB] 01:13:42 INFO: Puller (folder "shop29", dir "TeamViewerPortable\\Data"): delete: remove \\?\C:\syncthing\shop29\TeamViewerPortable\Data: The process cannot access the file because it is being used by another process.
[OOCJB] 01:13:42 INFO: Puller (folder "shop29", dir "TeamViewerPortable\\App\\teamviewer"): delete: remove \\?\C:\syncthing\shop29\TeamViewerPortable\App\teamviewer: The process cannot access the file because it is being used by another process.
[OOCJB] 01:13:42 INFO: Puller (folder "shop29", dir "TeamViewerPortable\\App\\DefaultData\\settings"): delete: remove \\?\C:\syncthing\shop29\TeamViewerPortable\App\DefaultData\settings: The process cannot access the file because it is being used by another process.
[OOCJB] 01:13:42 INFO: Puller (folder "shop29", dir "TeamViewerPortable\\App\\DefaultData"): delete: remove \\?\C:\syncthing\shop29\TeamViewerPortable\App\DefaultData: The process cannot access the file because it is being used by another process.
[OOCJB] 01:13:42 INFO: Puller (folder "shop29", dir "TeamViewerPortable\\App\\AppInfo\\Launcher"): delete: remove \\?\C:\syncthing\shop29\TeamViewerPortable\App\AppInfo\Launcher: The process cannot access the file because it is being used by another process.
[OOCJB] 01:13:42 INFO: Puller (folder "shop29", dir "TeamViewerPortable\\App\\AppInfo"): delete: remove \\?\C:\syncthing\shop29\TeamViewerPortable\App\AppInfo: The process cannot access the file because it is being used by another process.

**Comment by calmh** [comment]
> The process cannot access the file because it is being used by another process.

Are you saying this process is Syncthing itself? I don't see how that could be (we would run into the same issue on other Windowses then I expect), and we don't really use any file or directory locking anywhere...

**Comment by kononenko-nikolay** [comment]
forgive me my English. I use the translator. I had a hunch and it was confirmed. installed on a virtual PC, windows xp 64 bit, and ran her syncthing 64 bit. and 64 bit application (OS) is operating normally directories are deleted correctly. what is worth noting is that on kakoeto time you receive a sync error and syncthing cannot delete the directory because "they are not empty" (when they are empty and no files) and after some time, the directories themselves are removed.

p.s I don't use exceptions or some rules to ignore files. files no used I checked process monitor and unlocker

**Comment by calmh** [comment]
It sounds to me like you have something else interfering here. Perhaps antivirus that looks into each directory whenever syncthing does something there, causing it to be locked? I don't see a bug here, sorry.

**Comment by AudriusButkevicius** [comment]
Regardless, XP is 14 years old. I don't think we should waste effort to support a 14 year old OS.
This is also a duplicate of #1308

**Comment by calmh** [comment]
It even seems 32 bit specific if the OP analysis is correct. So yeah, no. If there's a patch somewhere that fixes this it'll be accepted, but I have no XP running anywhere and can't/won't do anything about this, sorry.

**Comment by kononenko-nikolay** [comment]
I thought so too, so I checked it all the newly installed system (virtual pc). I have prepared a file PML would you see? ( https://technet.microsoft.com/ru-ru/sysinternals/bb896645.aspx?f=255&MSPPError=-2147217396 ) https://cloud.mail.ru/public/7Qen/LwLxbxBfW - file

**Comment by calmh** [comment]
Clearly it's important to those unfortunate to be stuck with a 32 bit Windows XP if this is the case, but unfortunately someone of those will need to step up and fix it as well in this case. :/

**Comment by kononenko-nikolay** [comment]
Could you show me the case file in the source code that is responsible for deleting files \ directory. I will try to help yourself and others, myself. 

thank

**Comment by AudriusButkevicius** [comment]
https://github.com/syncthing/syncthing/blob/master/internal/model/rwfolder.go#L691
https://github.com/syncthing/syncthing/blob/master/internal/model/rwfolder.go#L738

I am checking the PML file, can you point me to the event where it fails to delete?

**Comment by AudriusButkevicius** [comment]
I can see sharing violations, but that's pretty much for every directory in the tree...

**Comment by AudriusButkevicius** [comment]
Maybe it's todo with osutil.InWriteableDir magic.

**Comment by kononenko-nikolay** [comment]
The fact of the matter that there is no manifest error. or I did not find that the only thing that is strange when setting (scan the contents of the directory every 600s) syncthing ever seen that passes these directories, and the only thing that can be considered a mistake is "SHARING VIOLATION" when trying to create the file \ directory that exists

**Comment by kononenko-nikolay** [comment]
you changed the architecture of the application? I have after the assembly instructions for the problem. I'm not a programmer, but trying to correct this mistake at least crutch.

**Comment by AudriusButkevicius** [comment]
Sorry, I don't understand the question

**Comment by kononenko-nikolay** [comment]
forgive me my English. I'm trying to find and fix those files that you told me, but I can not find them. you change the structure of the project? I really want to solve this problem.

**Comment by AudriusButkevicius** [comment]
Yes, internal is now lib

I suggest you try removing usage of the following function everywhere and see if that helps: https://github.com/syncthing/syncthing/blob/master/lib/osutil/osutil.go#L65

**Comment by kononenko-nikolay** [comment]
after the upgrade I was going wrong to syncthing, I did everything according to the instructions (git clone) at Saturday (the old version was going correct)

**Comment by AudriusButkevicius** [comment]
Run build.go clean
