### ISSUE TITLE
Change to fontawesome icon font

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#2138]
I suggest to switch to the [fontawesome](http://fontawesome.io) icon font. Besides having a lot more [icons](http://fontawesome.io/icons/) to choose from for future functions in Syncthing it has many every day symbols like desktop, mobile, tablet (which could be used as a user setting instead of the identicon), twitter, wifi, etc. The transition should be fairly quick as most icons have a similar look and same name.

**Comment by uok** [comment]
Work in progress ... https://github.com/uok/syncthing/tree/awesome

**Comment by uok** [comment]
how can I display all the different mini modals (e.g. https://github.com/syncthing/syncthing/blob/master/gui/syncthing/core/httpErrorDialogView.html) for testing? is there a simple javscript hack for that?

**Comment by AudriusButkevicius** [comment]
kill syncthing with the web ui open

**Comment by uok** [comment]
ok worked - still left: `majorUpgradeModalView` and `usageReportModalView`
any ideas how to trigger that?

**Comment by AudriusButkevicius** [comment]
Usage report you can open from the settings menu, (preview), major upgrade you can hack the go part to return something funky when comparing versions.

**Comment by uok** [comment]
usage report has two pieces, I need the one where it asks the user

**Comment by AudriusButkevicius** [comment]
There are some rules, i think its shown only after some time since first visit. You can check the part which adds the cookie and kill it.

**Comment by uok** [comment]
found it  :smile: ... PR tomorrow
