### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by xJMV** [syncthing/syncthing#2150]
French translation has been mainly machine translated and approved. Problem is, it use multiple terms for the same word (ex: Device is translated as appareil, machine or périphérique).

I downloaded the whole translation, edited it and uploaded it back to transifex but I can't change confirmed translation by clicking "Use this" to make the changes.

Anyway to get proper rights so I can make changes to get a constant translation and confirm 100% of the French translation ?

Thanks

**Comment by calmh** [comment]
Hi! I've now gone through Transifex and manually promoted 199 people to "language coordinators" instead of mere "translators". That was a really annoying process. Transifex' user management leaves something to be desired...

**Comment by xJMV** [comment]
Thanks!

BTW wouldn't "folder" takes an 'S' ?:
Original english: Incorrect configuration may damage your folder contents and render Syncthing inoperable.
Proposed: Incorrect configuration may damage your folders contents and render Syncthing inoperable.

**Comment by calmh** [comment]
I don't know, not a native speaker. "folder contents" sounds correct to me though.

**Comment by Zillode** [comment]
Either `your folder's contents` or `your folder contents` works imo (not folders contents)

**Comment by xJMV** [comment]
Speaking of multiple folders.... I would have used folders content... but it is not really major...
