### ISSUE TITLE
Requesting scan of ignored file scans parent

### ISSUE THREAD

**Issue by chenxiaoyu3** [syncthing/syncthing#2151]
Even if I supply with a sub parameter, it still scan all the folders.

**Comment by AudriusButkevicius** [comment]
You should provide an example.

**Comment by Zillode** [comment]
Are you using v0.11.19? There was an improvement related to this recently: https://github.com/syncthing/syncthing/commit/9b9fe0d65cdd29ef2db1f41288828ae231bb1348

**Comment by chenxiaoyu3** [comment]
@AudriusButkevicius  YES. 

@Zillode   like: curl -X POST -H "X-API-Key: xxxx" http://localhost:8384/rest/db/scan\?folder\=Sync\&sub\=test

After I change file in other folder(not int test folder), run this POST, the whole folder Sync will be scanned.

BTW, I'm trying to us fswatch(https://github.com/emcrisostomo/fswatch) to detect changing file and tell Syncthing to scan these files.( I'd like a real-time synchronizing but to small scan interval would bring lots unnecessary costs )

**Comment by AudriusButkevicius** [comment]
Your escaping looks suspicious to me, I'd need to verify if thats correct or not.

Regardless, have you tried syncthing-inotify?

**Comment by chenxiaoyu3** [comment]
That is  DEFINITELY what I need! Thank you! @AudriusButkevicius 

BTW, one of my sync client is behind firewall, it can only accept connections *passively* and output response. I've tried lots sync tools, syncthing is the only one that making it out. How do u accomplish this?

**Comment by canton7** [comment]
If you have two devices, A and B, it doesn't matter whether A can established a connection to B, or B can establish a connection to A: both devices will use any connection. Therefore if A is entirely passive, but B can receive connections, A will managed to connect to B and both will use that connection.

**Comment by chenxiaoyu3** [comment]
Thank you all~ :)

**Comment by fkwp** [comment]
Hi, 

I am also using syncthing-inotify and is does a great job. But I can confirm the behavior regarding the sub parameter as mentioned above: Triggering the ".stfolder" file in the root of a Folder (as periodically done by syncthing-inotify) causes a complete scan of the Folder. In case of a large Picture Library and a lot of xml/sqlite files (e.g., iPhoto-Library) this can take a long time and creates a lot of IO.

In syncthing/lib/model/model.go "func (m *Model) internalScanFolderSubs(folder string, subs []string)" 
only the parent of sub is taken into account. Hence, triggering ".stfolder" as sub causes a complete scan of the folder. Is that the desired behavior?

As workaround I created a ".stfolderInotify" folder in each of my syncthing Folders and patched syncthing-inotify 
-                               callback(folder, []string{".stfolder"})
+                               callback(folder, []string{".stfolderInotify/."})
to trigger  ".stfolderInotify/." periodically.

Kind regards

**Comment by calmh** [comment]
`.stfolder` is magic as it's ignored. This means it does not exist, and we fall back to scan the parent, i.e. the whole folder. We should either handle scan requests for that (i.e. just forget about all requests to scan ignored stuff), or syncthing-inotify should not  be sending them. I'm not sure what's cleanest.

**Comment by calmh** [comment]
Why do we even get scan requests for .stfolder? It should never change so no need to ask for a scan of it?

**Comment by canton7** [comment]
FWIW, SyncTrayzor takes the approach of not informing Syncthing about changes to ignored stuff.

**Comment by Zillode** [comment]
>Why do we even get scan requests for .stfolder? It should never change so no need to ask for a scan of it?

To delay the scan interval timeout

**Comment by calmh** [comment]
Aha. Unfortunate choice, but that makes sense then. We should fix this.

**Comment by plouj** [comment]
For `syncthing-inotify` would it make sense to have a new `/rest/db/reset-scan-delay` API call which would take a folder as an argument and simply reset the scan delay without doing any scanning? I could give this a try.

**Comment by plouj** [comment]
It looks like as of 9b9fe0d6 ```internalScanFolderSubs``` is immediately ignoring the sub's basename (https://github.com/syncthing/syncthing/commit/9b9fe0d65cdd29ef2db1f41288828ae231bb1348#diff-86326b10fb9dfebae06a27c61266c171R1231) and looking up its parent's name instead (https://github.com/syncthing/syncthing/commit/9b9fe0d65cdd29ef2db1f41288828ae231bb1348#diff-86326b10fb9dfebae06a27c61266c171R1234). In the case of ```sub=.stfolder``` parent is ```''``` which ```fs.Get()``` fails to find and ```subs``` ends up containing the empty string. Then in ```Walker.Walk()``` the anonymous function takes the else case (https://github.com/syncthing/syncthing/blob/1353e391/lib/scanner/walk.go#L116) and ```filepath.Walk()``` is called on the parent directory rather than ```.stfolder```. This causes the whole root folder to be scanned. I've verified this by running syncthing under ```strace  -f -e trace=lstat``` and doing ```curl -X POST "http://127.0.0.1:44644/rest/db/scan?folder=default&sub=.stfolder&next=9600"```. As you can see from the pull request the solution seems to be to undo 9b9fe0d6 plus we need to bypass the ```fs.Get()``` call for ```.stfolder``` and ```.stignore``` since they are never indexed (https://github.com/syncthing/syncthing/blob/1353e3916/lib/scanner/walk.go#L243).
