### ISSUE TITLE
Missing API call to force override

### ISSUE THREAD

**Issue by flz** [syncthing/syncthing#2154]
Hi, I'd like to be able to periodically force-resync folders from the master copy to the "slave" clients.

I haven't found a way to do this with the current REST API.

**Comment by AudriusButkevicius** [comment]
https://github.com/syncthing/syncthing/blob/master/cmd/syncthing/gui.go#L161

**Comment by flz** [comment]
Ha, thanks! It's not documented though.

**Comment by uok** [comment]
@flz thanks for reporting, @AudriusButkevicius opened an issue
if you can contribute information, please do at https://github.com/syncthing/docs/issues/39
