### ISSUE TITLE
Default path for new folders

### ISSUE THREAD

**Issue by nille02** [syncthing/syncthing#2157]
It would be great to choose a Default folder, where syncthing can create folders for new shares. 

e.g under Windows "%USERPROFILE%\Syncthing" or Linux "$HOME/Syncthing"

If a Device share now a new Folder with me, i can add the Folder without add a path and syncthing create the folder in this default folder. 

Maybe with a trusted (e.g. for devices under my control) flag for devices, that new shares automatically added.

I have some devices now and add a new folder to all devices manual is annoying. 

This feature exist in Bittorrent sync and is very handy.

**Comment by uok** [comment]
or semi-automatic: a simple text field in the (advanced) settings where you can enter a path. This becomes the prefix for the path in the add folder modal, e.g. default path "D:\data\"
- incoming "user X wants to share ABC with you"
- add folder modal: folder path: "D:\data\ABC"

or if you add a new folder

- add folder modal: folder path: "D:\data\" as default value

**Comment by fti7** [comment]
+1 
Small Change but a great useability improvement

**Comment by gaborgabor** [comment]
+1
I thought that default folder already has this function and auto-accept works also.

**Comment by calmh** [comment]
How would this integrate with #966? Assume that with that change in place, the folder would have an ID like 12E0E35A-A25C-4C12-9388-FE170213153C and a label like "[!!] ~~Awesome files~~ *?*?". What's the default folder path?

**Comment by user514** [comment]
+1 on default folder for all your new incoming syncs. But let me add...

  I'm missing some things from the first day I installed Syncthing. Really small improvements but important in my opinion.

  The order of fields and features of fields when entering a new shared folder, right now are like that:

1-FOLDER LABEL (you have to enter it manually and/or copypaste it from 3rd field)
2-FOLDER ID (could keep being automatic, you don't have to worry about it I think)
3-FOLDER PATH (you have to enter manually the full path. I know popup some options while you are typing the correct path, but...)

I think it will be much easier to enter a new folder as:

1-FOLDER PATH [BROWSE...]. In which you can enter a path manually or use the browse button and select it. Of course, when you enter browse you should fall into the 'Default path' feature commented in this thread. For sure almost all of us have a SYNCTHINGshares (or whatever) folder in which we first create our new folder and copy things in, and then we jump to the web browser to share it. Falling directly into our SYNCTHINGshares, will be great.
2-FOLDER LABEL. It should be taken automatically right after you have selected the folder path, just by adding the folder name as the 'folder label' here. For example with the sample above SYNCTHINGshares\MyMusic, 'MyMusic' should be the auto-proposal of syncthing when filling the 'folder label' field. 99% times user will left folder label with that name.
3-FOLDER ID. This could be even greyed out and not editable, almost transparent for the final user, first time I enter a folder I didn't know if I should change the given name or not or what.

  Just an opion. Of course let me add that syncthing is great!!!. oh, and a taskbar icon when under windows will be great, but that's another thread :)

**Comment by calmh** [comment]
@user514 your improvement suggestions may make sense, but currently they're hidden as a comment on an unrelated one year old issue so will probably not be acted on :)

**Comment by funkyfuture** [comment]
it would also be great to have an option that if enabled restricts the selection of folders to that default parent path. (and may even hide the parent path from users.)

**Comment by AudriusButkevicius** [comment]
No, that makes no sense at all.

**Comment by funkyfuture** [comment]
> No, that makes no sense at all.

that is hardly an argument in that form.

my phrasing may be misleading, but i don't have a clue what the misunderstanding could be if you provide such unfounded judgement.

my motivation in short is: users shouldn't be able to browse the filesystem as a whole.

**Comment by AudriusButkevicius** [comment]
Under what circunstances does a user who installed a piece of software would want to limit himself from being able to access share certain parts of the filesystem? Why would you ever want that?

**Comment by generalmanager** [comment]
I guess this could be useful if the server admin/owner is different from
the syncthing user/users.

I mean it's possible to setup chrooted users with separate Syncthing
configs and ports for the web UI. So if someone wants to offer some kind
of "Syncthing hosting" or allow some friends to use their servers
resources, limiting the filesystem access to a certain root path would
probably be the only feature missing from Syncthing to compartmentalize
the different use cases.

However the only problem I can see with the current behaviour is that
one can explore the files and folder structure via the autocomplete
function in the path field. Which can be remediated by simply chrooting
the user of this specific synctin instance to it's home.

And if one actually wants to protect their own server from certain users
and the public then it's already important to limit the attack surface
by using a special Syncthing user and only allowing access to the web UI
via SSH port forwarding.

Thus this is IMHO not a feature Syncthing should provide, because
compartmentalization is best handled by the underlying OS/rights management.

**Comment by calmh** [comment]
> it's possible to setup chrooted users with separate Syncthing configs and ports for the web UI

... and this is indeed the correct solution to the problem of the installer not being the same person as the user and wanting to limit access to the system at large.

(Syncthing is very easy to chroot. The only thing it needs access to is the DNS resolver config and CA certificates plus one or two required system libraries.)

**Comment by funkyfuture** [comment]
> Under what circunstances does a user who installed a piece of software would want to limit himself from being able to access/share certain parts of the filesystem?

- i'm providing syncfile-instances for users as Docker containers
- with volumes mounted at a certain path that i can guarantee will persist
- the users should be prevented from doing something against their own interest (choosing a path outside that volume)
- the users don't need to be confronted with parts of the filesystem she/he may find rather confusing, but rather enjoy a simple interface

this is not a proposal concerning technicalities, but about that thing they call User Experience. like the initial proposal as i understand it.

**Comment by AudriusButkevicius** [comment]
If you are providing a service to someone else, it's somewhat expected that you'll have to spend some effort to get things you are after. Syncthing as is now is for the individual and I don't see this feature being useful to the individual in anyway.

**Comment by calmh** [comment]
This is unrelated to this issue. Please create one for the purpose.

**Comment by imsodin** [comment]
Somehow Github didn't pick up on #4192 and finally https://github.com/syncthing/syncthing/commit/a04b92332f3ce8560bb339c1afb00037adbdd14e which should have closed this.
