### ISSUE TITLE
pull order: newest first doesn't seem to work

### ISSUE THREAD

**Issue by dcarosone** [syncthing/syncthing#2161]
Just added a new share to back up a set of photos from an android device.  Android is 0.11.18 via syncthing-silk, puller is Linux 0.11.19 via ubuntu ppa.

Set the folder pull order to "newest first", but observed the files getting pulled in filename order (DSC_nnnn.jpg), which is essentially oldest first.  Wondered if the sort order was accidentally reversed, so tried "oldest first", this is pulling in the same order as previously.  Either they're the same, or just ignored?

**Comment by calmh** [comment]
Newest first is based on file modification times. Are those correct on the source, or perhaps all set to the time the photos were imported?

**Comment by dcarosone** [comment]
The file times are as taken; this is the original phone with images being
backed up for the first time. They're being set accordingly on the receiver
too.

I'll try and set up some more controlled tests. I wonder if the synthetic
mtime code is somehow involved?

**Comment by dcarosone** [comment]
Confirmed. Pulling the same dataset to another machine, both linux (so no android complications).
1. Started with "random": got apparently random file order.
2. Set to "oldest first", restarted: got oldest files first.
3. Set to "newest first", restarted: same order as oldest first.

See screenshot, with "newest first" order in the shaded out pane below the popup.

![screenshot from 2015-08-19 09 38 32](https://cloud.githubusercontent.com/assets/11495017/9345706/057d10b6-4657-11e5-9946-df4128094439.png)

**Comment by dcarosone** [comment]
Some sample mtimes, these from the files originally pulled in random order:

```
2185 -rw-rw-r-- 1 dan dan  2227217 Mar  9  2014 DSC_0014.JPG
2857 -rw-rw-r-- 1 dan dan  2913720 Apr  6  2014 DSC_0089.JPG
1813 -rw-rw-r-- 1 dan dan  1843461 Jun 19  2014 DSC_0161.JPG
1929 -rw-rw-r-- 1 dan dan  1964748 Jun 30  2014 DSC_0202.JPG
```

**Comment by calmh** [comment]
Hah. Woops. :( Sorry, that was a stupid bug. Fixed, thanks for narrowing it down!

**Comment by inspector71** [comment]
LOL and here was I thinking I'd forgotten to configure something correctly :)

Thanks for the fix.
