### ISSUE TITLE
[SEVERE] Having client that syncs none of the files in a .stignore can delete all of the files allowed to sync on other clients

### ISSUE THREAD

**Issue by ShadowKyogre** [syncthing/syncthing#2164]
Late last night, I accidentally triggered a bug where having a client that syncs none of the files in a .stignore can delete all of the files allowed to sync on other clients. I'm not sure whether to file this with Syncthing-Android or Syncthing, but judging by the fact that I had Syncthing off on my backup phone after I tried so hard to get sync working, the bug belongs here.

# Operating Systems
* Arch Linux on desktop
* Arch Linux on server
* Stock LG Volt Android Kitkat that's rooted (technically the rooted part isn't important, buut, it still kind of is. I'll explain why later. I've never experienced this with my Samsung Galaxy S2, which is running CM11)

# Syncthing Versions
* Phone client: 0.6.5 Android GUI, 0.11.13 binary
* Arch Linux desktop client: 0.11.19
* Arch Linux server client: 0.11.13 (you're probably wondering at this point why I forgot to upgrade the syncthing version on here)

# Expected Result
The phone to sync the listed files in the .stignore.

# Actual Result
The desktop clients keep trying to purge the files listed on the .stignore. Any files and folders listed on the .stignore will also have 0777 as their permissions. Furthermore, none of the files are able to sync with syncthing even though the 

# Steps to Reproduce
0. Get the syncthing clients running on the two boxes
1. Root the phone.
2. Apply the [SDCard Fix](http://trendblog.net/fix-kitkat-sd-card-write-restriction/). I thought this would allow me to get back to writing to SD cards normally on my volt, but it doesn't even though /system/etc/permissions/platform.xml's been changed as per the steps in link.
3. Add a .stignore that has entries that has some files and folders permitted and anything else not listed in it not to be synced.
4. Place said .stignore into `/storage/external_SD/Android/data/com.nutomic.syncthingandroid/files`
5. Add these other boxes to the phone as devices
6. Select the folder mentioned before in the Android GUI and share it with these devices
7. You should see a list of the number of files that it should be able to sync, right before "0 / ####" files.
8. Close the syncthing Android app.
9. Take a look at the both of the other nodes.
10. On the computer node with syncthing 0.11.13, syncthing has purged all the files and folders that were mentioned in the .stignore.
11. On the computer node with syncthing 0.11.19, syncthing has purged all of the files, but any of the listed folders are now world writeable and readable. It will also complain that it can't pull all of the deletion changes pushed by the other syncthing.

Now, I'll go ahead and mention that you're going to be safe from this if you keep revisions of your files, manually restore them, and purge syncthing 0.11.13's records of your synced folder so this doesn't happen again. That's what I did to recover my data.

I should be able to get the log entries for the syncthing versions on the Arch Linux boxen. However, I'm kind of scared of reproducing this bug because I don't want to accidentally lose some important files again.

**Comment by calmh** [comment]
Can you reproduce this between two devices without the android specific hacks and so on? I'm not fully following what's supposed to be going on here...

**Comment by AudriusButkevicius** [comment]
So I don't see how rooting or non-rooting the device and the device being android can effect this, because it runs the same binary as the desktops.

Regardless, a cut down reproduction case with 2 devices is what we need.

**Comment by calmh** [comment]
Deletion records *should* only be generated if a file doesn't exist any more according to `lstat()` -- of course there may be bugs (whatever happens above sounds like *some* kind of bug for sure), but Android, SD-cards, and hacks to enable putting files on that SD-card that may or may not work as intended makes me suspicious. :)

**Comment by ShadowKyogre** [comment]
Trying to reproduce it with two devices, still not sure why it's not reproducing it again with a fresh install of syncthing.

# Attempt to reproduce with just the two Linux boxen
* Create a test folder on both boxes
* In one copy of the folder, run `mkdir testme{1..3}` to make three folders
* In that same folder, run `mkdir testme{1..3}/iexist.txt` to make test files in those folders
* In that same folder, run `touch iexist.txt` to create a file at the root of the folder
* On the other computer that will have a copy of the folder, create an .stignore like this:
~~~
!/testme1
!/iexist.txt
/*
~~~
* chown the folder so it isn't accessible to the user running syncthing
* set up sharing between the two folders
* That resulted in getting normal permission denied errors. I also noticed that for the ones that were ignored that it would show something like Sync/Delete for the files it wouldn't sync.
![This might be of note](https://cloud.githubusercontent.com/assets/673620/9295427/5e86800c-4422-11e5-9161-f57ef5564e0b.png)
* The file hierarchy on the other computer is fine.
~~~
 _____/[shadowkyogre@AlpheTerra|2015-08-16 14:05:18]\______________)                                                                                                                                                               
(_/[~/t/syncthing_wreckage]\_____________/(($)>--< tree
.
├── iexist.txt
├── testme1
│   └── iexist.txt
├── testme2
│   └── iexist.txt
└── testme3
    └── iexist.txt
3 directories, 4 files
~~~

---

# Attempt at producing it with the phone (Kitkat) and a computer
## In SD Card in `/storage/external_SD/Android/data/com.nutomic.syncthingandroid/files`, no root enabled
* Go to  `/storage/external_SD/Android/data/com.nutomic.syncthingandroid/files`
* On the cellphone that will have a copy of the folder, create an .stignore like this:
~~~
!/testme1
!/iexist.txt
/*
~~~
* set up sharing between the two folders
* Both... just seem to cooperate fine, oddly.

## In SD Card in `/storage/external_SD/Test`, root with sdcard tweak attempt, but no root access to syncthing
* Go to  `/storage/external_SD/Test` (ownership of this folder should be root:sdcard_r when checked with adb after you create it)
* On the cellphone that will have a copy of the folder, create an .stignore like this:
~~~
!/testme1
!/iexist.txt
/*
~~~
* set up sharing between the two folders
* It... still oddly works, frustratingly enough. I'm not sure what happened when I was first setting it up since it was acting all sorts of weird. These tests are done with a fresh install, btw.

## In Internal Storage in `/storage/emulated/0/Android/data/com.nutomic.syncthingandroid/files`, no root enabled
* Go to  `/storage/emulated/0/Android/data/com.nutomic.syncthingandroid/files`
* On the cellphone that will have a copy of the folder, create an .stignore like this:
~~~
!/testme1
!/iexist.txt
/*
~~~
* set up sharing between the two folders
* Both... just seem to cooperate fine, oddly.

**Comment by ShadowKyogre** [comment]
Also, what maybe also be of note is prior to the forced reinstallation, syncthing would often get stuck in a crash loop if root access was explicitly enabled in the settings.

![](https://lut.im/FurMTTQ2/yLjdHGxH)
![](https://lut.im/hBkVahoQ/UG52JfNw)

**Comment by AudriusButkevicius** [comment]
so are you saying it was failing when phone got permission denied errors?

**Comment by ShadowKyogre** [comment]
@AudriusButkevicius: Something like that, although I'm not quite sure how to reproduce it. That's what I was baffled about too. It wasn't syncing to any of the normal directories that were allocated for it nor any other directories.

https://ptpb.pw/8Ycg That's an adb logcat from before the forced install, before I reinstalled it. There seemed to be an odd instance of two running at the same time judging by:
```
[URDFP] 22:28:10 FATAL: Cannot open database: resource temporarily unavailable - Is another copy of Syncthing already running?
```

**Comment by AudriusButkevicius** [comment]
Well, not sure, that could mean that there is a second instance running, or that the mount has failed and it showed up with half the files missing.

**Comment by ShadowKyogre** [comment]
Closing it for now because I can't seem to find a way to reproduce it since the reinstall. I'll open it when I find a way to make it happen again.
