### ISSUE TITLE
Incorrect out-of-memory error, crash

### ISSUE THREAD

**Issue by joatca** [syncthing/syncthing#2166]
Setting up syncthing on new laptop, Ubuntu 15.04, 8G RAM, can't get it to start. On the console it reports a failure allocating a hugely negative amount of memory:

```
[monitor] 21:15:22 INFO: Starting syncthing
[M7YPN] 21:15:24 INFO: syncthing v0.11.20 (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-08-16 13:29:48 UTC
[M7YPN] 21:15:24 INFO: My ID: M7YPNK6-IJ2KBOY-7OYR2QE-TNBHKUG-SXQBQGL-RGEA6JP-BYQHR7F-SAO2PAC
[M7YPN] 21:15:24 INFO: Database block cache capacity 63098 KiB
[M7YPN] 21:15:24 OK: Ready to synchronize default (read-write)
[M7YPN] 21:15:24 INFO: Starting web GUI on http://127.0.0.1:8384/
[M7YPN] 21:15:24 INFO: Completed initial scan (rw) of folder default
runtime: out of memory: cannot allocate -8289131749560221696-byte block (10485760 in use)
fatal error: out of memory
[monitor] 21:15:25 WARNING: Panic detected, writing to "/home/fraser/.config/syncthing/panic-20150817-211525.log"
[monitor] 21:15:25 WARNING: Please check for existing issues with similar panic message at https://github.com/syncthing/syncthing/issues/
[monitor] 21:15:25 WARNING: If no issue with similar panic message exists, please create a new issue with the panic log attached
[monitor] 21:15:25 INFO: Syncthing exited: exit status 2
```

I've got plenty of memory available:

MemTotal:        8076548 kB
MemFree:          217052 kB
MemAvailable:    6178860 kB
Buffers:           59980 kB
Cached:          6441732 kB
[...snip..]

I have the panic log but github won't let me attach it. How do I do that?

**Comment by calmh** [comment]
Hi! You can just paste the first section of it (first 100 lines or so) here.

**Comment by joatca** [comment]
Here you go:

[M7YPN] 21:15:24 INFO: syncthing v0.11.20 (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-08-16 13:29:48 UTC
[M7YPN] 21:15:24 INFO: My ID: M7YPNK6-IJ2KBOY-7OYR2QE-TNBHKUG-SXQBQGL-RGEA6JP-BYQHR7F-SAO2PAC
[M7YPN] 21:15:24 INFO: Database block cache capacity 63098 KiB
[M7YPN] 21:15:24 OK: Ready to synchronize default (read-write)
[M7YPN] 21:15:24 INFO: Starting web GUI on http://127.0.0.1:8384/
[M7YPN] 21:15:24 INFO: Completed initial scan (rw) of folder default
...
Panic at 2015-08-17T21:15:25-04:00
fatal error: out of memory

runtime stack:
runtime.throw(0xea8eea)
	/usr/local/go/src/runtime/panic.go:491 +0xad
runtime.largeAlloc_m()
	/usr/local/go/src/runtime/malloc.c:390 +0xee
runtime.onM(0xc208014400)
	/usr/local/go/src/runtime/asm_amd64.s:257 +0x68
runtime.mstart()
	/usr/local/go/src/runtime/proc.c:818

goroutine 21 [running]:
runtime.switchtoM()
	/usr/local/go/src/runtime/asm_amd64.s:198 fp=0xc208119b48 sp=0xc208119b40
runtime.mallocgc(0x8cf716976b0c9a5a, 0x9be520, 0x0, 0xc20802b870)
	/usr/local/go/src/runtime/malloc.go:199 +0x9f3 fp=0xc208119bf8 sp=0xc208119b48
runtime.newobject(0x9be520, 0xc20802b870)
	/usr/local/go/src/runtime/malloc.go:353 +0x49 fp=0xc208119c20 sp=0xc208119bf8
main.getPostHandler(0x7fd15968b8c8, 0xc20811d110, 0x7fd15968b8c8, 0xc20811d170, 0x0, 0x0)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:286 +0x88 fp=0xc208119c68 sp=0xc208119c20
main.(*apiSvc).Serve(0xc2080e4180)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:178 +0x1435 fp=0xc208119f40 sp=0xc208119c68
github.com/thejerf/suture.func·007()
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:537 +0xf6 fp=0xc208119fe0 sp=0xc208119f40
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208119fe8 sp=0xc208119fe0
created by github.com/thejerf/suture.(*Supervisor).runService
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:540 +0x11e

goroutine 1 [runnable]:
fmt.(*fmt).init(0xc2083cc058, 0xc2083cc010)
	/usr/local/go/src/fmt/format.go:71
fmt.newPrinter(0x1)
	/usr/local/go/src/fmt/print.go:136 +0x96
fmt.Sprintln(0xc2083c81f8, 0x1, 0x1, 0x0, 0x0)
	/usr/local/go/src/fmt/print.go:270 +0x31
github.com/calmh/logger.(*Logger).Infoln(0xc208030000, 0xc2083c81f8, 0x1, 0x1)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/calmh/logger/logger.go:117 +0x93
main.discovery(0x55f0, 0x3)
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:897 +0x1b0
main.syncthingMain()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:658 +0x2695
main.main()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:383 +0x2288

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [chan receive]:
main.trackCPUUsage()
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0xec
created by main.init·2
	/go/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x25

goroutine 8 [select]:
github.com/thejerf/suture.(*Supervisor).Serve(0xc2080e4000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:432 +0xf64
created by github.com/thejerf/suture.(*Supervisor).ServeBackground
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:394 +0x32

goroutine 10 [select]:
github.com/syncthing/syncthing/lib/events.(*Subscription).Poll(0xc20800a760, 0xdf8475800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/syncthing/syncthing/lib/events/events.go:186 +0x369
github.com/syncthing/syncthing/lib/events.(*BufferedSubscription).pollingLoop(0xc20802e500)
	/go/src/github.com/syncthing/syncthing/lib/events/events.go:223 +0x48
created by github.com/syncthing/syncthing/lib/events.NewBufferedSubscription
	/go/src/github.com/syncthing/syncthing/lib/events/events.go:217 +0x292

goroutine 11 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc2080a41c0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x21e
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236 +0x24c

goroutine 12 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc2080e6000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:69 +0x55a
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:139 +0x7cc

goroutine 13 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc2080e6000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_state.go:82 +0x14a
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:140 +0x7e6

goroutine 14 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc2080e6000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:768 +0x858
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:146 +0x9cf

goroutine 15 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc2080e6000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:715 +0x283
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:147 +0x9e9

goroutine 16 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc2080e6000)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x197
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:148 +0xa03

goroutine 17 [select]:
github.com/syncthing/syncthing/lib/model.(*ProgressEmitter).Serve(0xc208124480)
	/go/src/github.com/syncthing/syncthing/lib/model/progressemitter.go:52 +0x8f2
created by github.com/syncthing/syncthing/lib/model.NewModel
	/go/src/github.com/syncthing/syncthing/lib/model/model.go:143 +0xba6

goroutine 18 [select]:
github.com/syncthing/syncthing/lib/ignore.(*Matcher).clean(0xc20802e4b0, 0x68c61714000)
	/go/src/github.com/syncthing/syncthing/lib/ignore/ignore.go:161 +0x1c9
created by github.com/syncthing/syncthing/lib/ignore.New
	/go/src/github.com/syncthing/syncthing/lib/ignore/ignore.go:53 +0x170

goroutine 19 [select]:
github.com/thejerf/suture.(*Supervisor).Serve(0xc2080e40c0)
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:432 +0xf64
github.com/thejerf/suture.func·007()
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:537 +0xf6
created by github.com/thejerf/suture.(*Supervisor).runService
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:540 +0x11e

goroutine 20 [select]:
github.com/syncthing/syncthing/lib/model.(*rwFolder).Serve(0xc2080df680)
	/go/src/github.com/syncthing/syncthing/lib/model/rwfolder.go:195 +0x26b5
github.com/thejerf/suture.func·007()
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:537 +0xf6
created by github.com/thejerf/suture.(*Supervisor).runService
	/go/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/thejerf/suture/suture.go:540 +0x11e

**Comment by Zillode** [comment]
(https://github.com/syncthing/syncthing/issues/1938?)

**Comment by AudriusButkevicius** [comment]
Are you running in a cgroup?

**Comment by calmh** [comment]
```
runtime.mallocgc(0x8cf716976b0c9a5a, 0x9be520, 0x0, 0xc20802b870)
    /usr/local/go/src/runtime/malloc.go:199 +0x9f3 fp=0xc208119bf8 sp=0xc208119b48
```

This tries to allocate 0x8cf716976b0c9a5a bytes. That's the

```
runtime: out of memory: cannot allocate -8289131749560221696-byte block (10485760 in use)
```

I'm thinking runtime bug or memory corruption of some kind here...

@joatca Is this a one time thing, or recurring?

**Comment by joatca** [comment]
It happened every time I tried to run syncthing. However I just
tried again tonight and it now works reliably. The only thing I've
changed is some of the power management and cpu scaling parameters
to improve battery life. I don't know why that would make a
difference, but *shrug*.

Can we leave the issue open for another day or so while I verify the
problem doesn't recur?


On Wed, Aug 19, 2015, at 03:12 AM, Jakob Borg wrote:
> runtime.mallocgc(0x8cf716976b0c9a5a, 0x9be520, 0x0, 0xc20802b870)
    /usr/local/go/src/runtime/malloc.go:199 +0x9f3 fp=0xc208119bf8
    sp=0xc208119b48
>
> This tries to allocate 0x8cf716976b0c9a5a bytes. That's the


> runtime: out of memory: cannot allocate -8289131749560221696-byte
> block (10485760 in use)
>
> I'm thinking runtime bug or memory corruption of some kind here...


> @joatca[1] Is this a one time thing, or recurring?


>


> — Reply to this email directly or view it on GitHub[2].
>


>



Links:

  1. https://github.com/joatca
  2. https://github.com/syncthing/syncthing/issues/2166#issuecomment-132468774
