### ISSUE TITLE
high CPU use when apparently doing nothing (OSX)

### ISSUE THREAD

**Issue by akohlsmith** [syncthing/syncthing#2175]
This has been something I've noticed since I started using syncthing (since 0.11.17 or so). The GUI shows 15-20% CPU use, meanwhile OSX's activity monitor shows the syncthing threads consuming 90-250% CPU. (quad-core 2.0GHz i7) I'm running pretty much with defaults (no advanced features/config settings) and the folder I'm syncing is already synchronized. The only unusual thing I can think of is that I have a bandwidth limit of 16kBps in both directions set.

Sometimes restarting syncthing helps, but most times it does not. I'd like to give a much better bug report but I'm (quite) unfamiliar with debugging Go. If you could give me some guidelines as to what to try or what information to gather to help I will happily do so.

For now I renice the process so my machine isn't sluggish but I would like to figure out why it's consuming so much CPU, why the CPU usage meter on the GUI is off by so much and if there's anything I can do to fix it.

**Comment by MyPod** [comment]
multi cores allow CPU usage to go beyond 100% iirc, and hashing the
contents of your files may take up a lot of processing power. No
traffic, or hardly any is sent trough while this happens, as the index
of what you have hasn't yet been generated. It is expected for the
hashing to do this. I think I read somewhere here that a rescan and
eventual rehash happens every time the binary is started, and at given
intervals.

**Comment by Zillode** [comment]
I believe this can happen when another device connects. We need to calculate their differences and this is currently not done very efficiently, https://github.com/syncthing/syncthing/pull/2020 will fix that.

**Comment by calmh** [comment]
That sounds plausible. Running with `-verbose` should tell you a bit more about what's happening - I don't think there's a state where it uses lots of CPU but doesn't print something about why, with the possible exception of scanning which it does print when it starts and stops but can take a while if there are new large files etc

**Comment by dashbad** [comment]
I am also experiencing this. Currently on 0.11.20 on all my devices. As I type, Syncthing is reporting all devices as up to date and showing 8% in the GUI and 40% in the activity monitor. I suspect the discrepancy is that my CPU has 4 cores, and Syncthing is only showing an average per core?

Running in verbose mode does suggest that it has something to do with indexing. Lots of:

'UUID sent an index update for "shared folder" with xxx items'

appearing in the logs.

I've increased the rescan interval for a particularly large folder I am syncing in the hope that this should reduce the amount of time this happens. Is that assumption correct?

**Comment by calmh** [comment]
> sent an index update for "shared folder" with xxx items

This is another device telling you about things that have changed. Syncthing is processing that, and presumably also pulling down the changed files from the network. It's not doing "nothing" here.

**Comment by dbkaplun** [comment]
+1

When I click Restart in the web interface, the process stays open, using 100% CPU, but the web service shuts down.

**Comment by AudriusButkevicius** [comment]
@dbkaplun providing logs from -verbose would be useful.

**Comment by dbkaplun** [comment]
@AudriusButkevicius how do I do that? I'm using homebrew's syncthing package.

**Comment by AudriusButkevicius** [comment]
Stop syncthing, and start it manually from the command line with the -verbose argument.

**Comment by dbkaplun** [comment]
@AudriusButkevicius [syncthing -verbose](https://gist.github.com/anonymous/fd9d741991508644d5b1)

CPU usage for syncthing has been anywhere between 85% and 200% since the process started. The UI is saying ~25%.

**Comment by AudriusButkevicius** [comment]
Can you make a screenahot of the UI and the process manager or whatever you are using to measure that? Also, providing the log as I've initially suggested would be more useful.

**Comment by dbkaplun** [comment]
@AudriusButkevicius the verbose log is linked in my last comment. Here's a screenshot:
![screenshot](http://i.imgur.com/J3w2oDR.png)

**Comment by AudriusButkevicius** [comment]
Looking at the log, its just syncing stuff from some other peer, hence the load, once that is done, it will settle.

**Comment by dbkaplun** [comment]
@AudriusButkevicius no, look at the timestamps. The log hasn't changed on 15 minutes but CPU usage is still very high.

**Comment by AudriusButkevicius** [comment]
It's probably the database just doing it house keeping in the background. 

The percentage that is shown by the process manager is just relative to the rest of the system, If you look at the stats at the bottom 30% of the time the CPU is still idle, so I don't think it's pegged as such.

I bet that if you look at disk usage, syncthing will be maxing out the disk.

What sort of machine are you running this on? In terms of CPU and in terms of disk speed?

**Comment by dbkaplun** [comment]
Still spinning at ~50% CPU usage after all this time. MacBook Pro 2.6GHz i5 w/SSD.

**Comment by AudriusButkevicius** [comment]
You can run STTRACE=all to get even more verbose logging, perhaps that will have any clues.
I have a suspicion that it's probably scanning, but because the UI didn't manage to load in full at the point you took the screenshot, it's hard to say.

**Comment by calmh** [comment]
"Unknown" in the web interface means its still loading data from the database. Is that a very large folder?
