### ISSUE TITLE
MacOSX - Update for unexpected folder ID

### ISSUE THREAD

**Issue by SylvainLasnier** [syncthing/syncthing#2177]
Hi,
I install syncthing 0.11.20 on MacOSX and Linux server.
Mac share Documents directory and Linux start with empty one

Sync don't seems run.
No upload from Mac and no file is create on Linux.
I get messages "Unexpected folder ID "Documents" sent from device "XXX"; ensure that the folder exists and that this device is selected under "Share With" in the folder configuration."

Any idea?

Mac log:
[EFH26] 06:17:26 INFO: syncthing v0.11.20 (go1.4.2 darwin-amd64 default) unknown-user@syncthing-builder 2015-08-16 13:29:48 UTC
[EFH26] 06:17:26 INFO: My ID: XXX
[EFH26] 06:17:26 INFO: Database block cache capacity 65536 KiB
[EFH26] 06:17:28 OK: Ready to synchronize Documents (read-write)
[EFH26] 06:17:28 INFO: Starting web GUI on http://127.0.0.1:8384/
[EFH26] 06:17:29 INFO: Starting local discovery announcements
[EFH26] 06:17:29 INFO: Starting global discovery announcements
[EFH26] 06:17:29 INFO: Device XXX is "MacBookPro SLA" at [dynamic]
[EFH26] 06:17:29 INFO: Device YYY is "OVH" at [YYY]
[EFH26] 06:17:29 INFO: API listening on 127.0.0.1:8384
[EFH26] 06:17:29 INFO: Established secure connection to YYY at 192.168.1.146:49926-YYY:22000
[EFH26] 06:17:32 INFO: Device YYY client is "syncthing v0.11.20"
[EFH26] 06:17:32 INFO: Device YYY name is "YYY"
[EFH26] 06:17:39 INFO: No UPnP device detected
[EFH26] 06:18:40 INFO: Completed initial scan (rw) of folder Documents

Linux server log:
[Q64HX] 06:18:01 INFO: Established secure connection to XXX at 94.23.250.168:22000-XXX:49926
[Q64HX] 06:18:04 INFO: Device XXX client is "syncthing v0.11.20"
[Q64HX] 06:18:04 INFO: Device XXX name is "MacBookPro SLA"
[Q64HX] 06:18:05 INFO: Unexpected folder ID "Documents" sent from device "XXX"; ensure that the folder exists and that this device is selected under "Share With" in the folder configuration.
[Q64HX] 06:18:05 INFO: Update for unexpected folder ID "Documents" sent from device "XXX"; ensure that the folder exists and that this device is selected under "Share With" in the folder configuration.
...

**Comment by AudriusButkevicius** [comment]
You have to mutually add the same folder on both sides.

**Comment by SylvainLasnier** [comment]
It's work fine. Many thanks
