### ISSUE TITLE
hostname resolution error (DNS)

### ISSUE THREAD

**Issue by exhuma** [syncthing/syncthing#2178]
I am running a local `bind9` server with forwarders defined (requests for unknown hosts are forwarded elsewere). This works:

    $ nslookup announce.syncthing.net
    Server:         127.0.0.1
    Address:        127.0.0.1#53
    
    Non-authoritative answer:
    Name:   announce.syncthing.NET
    Address: 194.126.249.5

IPv6:

    $ nslookup announce.syncthing.net ::1
    Server:         ::1
    Address:        ::1#53

    Non-authoritative answer:
    Name:   announce.syncthing.NET
    Address: 194.126.249.5

`dig` works too:

    $ dig announce.syncthing.net
    194.126.249.5

However, syncthing seems to have trouble with that:

    [XXXXX] 2015/08/21 09:44:27.735583 client_udp.go:106: DEBUG: discover udp4://announce.syncthing.net:22026: broadcast resolve: lookup announce.syncthing.net on 127.0.0.1:53: no such host; trying again in 1m0s

I found a workaround by adding `discover.syncthing.net` into `/etc/hosts`. This works, but is kind of a hacky solution.

**Comment by calmh** [comment]
`syncthing --version`?
What does your `/etc/resolv.conf` look like?

**Comment by calmh** [comment]
It's possibly slightly odd that it returns the name as `.NET`, but it shouldn't be a problem of course...

**Comment by exhuma** [comment]
`/etc/resolv.conf`

    nameserver 127.0.0.1

`syncthing --version`

    syncthing v0.11.20 (go1.4.2 linux-386 default) unknown-user@syncthing-builder 2015-08-16 13:29:48 UTC

**Comment by calmh** [comment]
Can you run the amd64 version? The 386 version is statically linked and uses a builtin DNS resolver, which in this case seems buggy... I'll see if I can reproduce it myself and if so file a bug on Go...

**Comment by calmh** [comment]
Before I do that though, can you try the build at http://build.syncthing.net/job/syncthing/? (386 or amd64 as you like)

That's built with Go 1.5 which is a fair bit newer than Go 1.4.2 that the current release build uses, so it may already be solved.

**Comment by exhuma** [comment]
I tried with the latest build using `syncthing-linux-386-v0.11.20+39-gca4a358.tar.gz` and it seems to work.

Thanks by the way for keeping a backup of the config file ;) Switching back to the old client would have bitten me otherwise.

I have now - as mentioned - switched to the old client as that is the official release. In the mean-time I will continue using the modified `/etc/hosts` file... unless you tell me that `gca4a358` can be considered stable ;)

**Comment by calmh** [comment]
Next version (tomorrow) will use go 1.5 and should then have resolved this. I'll optimistically close, yell if that turns out not to be the case. :)

**Comment by exhuma** [comment]
Just sneaking in to confirm that it works!

Thanks!

**Comment by calmh** [comment]
:+1:

**Comment by exhuma** [comment]
Ehm... today I realised that one of my machines did not properly connect to the announcement server. Looking into the log confirmed that it's the DNS issue again. I've looked up the version and got this:

    STTRACE=beacon,discover /opt/syncthing/syncthing --version
    syncthing v0.11.22 "Aluminium Ant" (go1.4.2 linux-386 default) unknown-user@syncthing-builder 2015-08-24 07:40:21 UTC

Not sure how it worked yesterday. I am *pretty* sure I double checked all my machines. I must have missed this one :(
