### ISSUE TITLE
Syncthing on EC2

### ISSUE THREAD

**Issue by kevhill** [syncthing/syncthing#2180]
Hello, I'm trying to get Syncthing up on an AWS EC2 instance, and can't seem to connect to the web-GUI. I've tried both connecting directly to the instance after opening the correct ports on the EC2 instance security group (TCP and UDP), and ssh port forwarding from my local machine. Here's the syncthing output...

    ubuntu@ip-xx-xx-xx-xx:~$ syncthing
    [monitor] 17:10:39 INFO: Starting syncthing
    [DNJGZ] 17:10:40 INFO: syncthing v0.11.20 (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-08-16 13:29:48 UTC
    [DNJGZ] 17:10:40 INFO: My ID: DNJGZxx-xxxxxxx-xxxxxxx-xxxxxxx-xxxxxxx-xxxxxxx-xxxxxxx-xxxxxxx
    [DNJGZ] 17:10:40 INFO: Database block cache capacity 8192 KiB
    [DNJGZ] 17:10:40 OK: Ready to synchronize default (read-write)
    [DNJGZ] 17:10:40 INFO: Starting web GUI on http://127.0.0.1:8384/
    [DNJGZ] 17:10:40 INFO: Completed initial scan (rw) of folder default
    [DNJGZ] 17:10:40 INFO: Starting local discovery announcements
    [DNJGZ] 17:10:40 INFO: Starting global discovery announcements
    [DNJGZ] 17:10:40 INFO: Device DNJGZxx-xxxxxxx-xxxxxxx-xxxxxxx-xxxxxxx-xxxxxxx-xxxxxxx-xxxxxxx is "ip-xx-xx-xx-xx" at [dynamic]
    [DNJGZ] 17:10:40 INFO: API listening on 127.0.0.1:8384
    [DNJGZ] 17:10:50 INFO: No UPnP device detected

Maybe the UPnP part is causing an issue? Thoughts? Has anyone seen a tutorial out there for setting syncthing up on EC2?

**Comment by wweich** [comment]
UPnP has nothing to do with the WebUI. Its only for the port for data transfer.
Opening ports won't help, as the WebUI only listens on **local** (`127.0.0.1:8384`), but ssh port forwarding should work, as the connection would then come from the host itself.
How exactly did you setup the ssh port forward?

**Comment by AudriusButkevicius** [comment]
If you have more questions, consult on the forums.

**Comment by kevhill** [comment]
doh. I was forwarding to the ec2 instance based on public DNS name, not IP... sorry and double sorry that I didn't see the link to the forum before posting. Keep up the good work.
