### ISSUE TITLE
Limit number of relay connections

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2182]
In the future, https://relays.syncthing.net might hopefully return a whole bunch of relays. It shouldn't be necessary for each client to maintain connections to all of them. I suggest moving the latency measurement stuff from the discovery to the relay code, so that we measure latency to all and pick just the one or two best to maintain connections to.

/cc @AudriusButkevicius for opinions on this, I can do the actual hacking if there's agreement

**Comment by AudriusButkevicius** [comment]
That's fine. Though I'd prefer keeping the `choose the closest relay the other peer provides`. I agree that we should pick the closest relay from relays.st.net

**Comment by calmh** [comment]
Yeah, you're right. Both sides do the latency dance to find the best combination.

**Comment by AudriusButkevicius** [comment]
When I mean closest relay from relays.st.net, I mean closest available (up) single relay.

**Comment by Zillode** [comment]
Either each client tries to get the optimal relay or we control the preferred relays from the server side. I think it is worth considering the second option as well, as we'll probably have slower nodes but with unlimited traffic capabilities.

**Comment by AudriusButkevicius** [comment]
adding priority would be beneficial I guess
