### ISSUE TITLE
Cross compiling with Go 1.5 fails

### ISSUE THREAD

**Issue by Duncaen** [syncthing/syncthing#2183]
For me cross compiling syncthing with GO 1.5 and any target arch fails with following error:
```
go install: cannot install cross-compiled binaries when GOBIN is set
```
More build logs:
http://build.voidlinux.eu/builders/armv7l_builder/builds/16872/steps/shell_3/logs/stdio
http://build.voidlinux.eu/builders/armv7l-musl_builder/builds/3479/steps/shell_3/logs/stdio

Here is how i run the build.go script:
https://github.com/voidlinux/void-packages/blob/795317c4553502800fdbd9267bacac1105359460/srcpkgs/syncthing/template#L22

**Comment by calmh** [comment]
Use `go run build.go -goos windows build` (i.e. `build` at the end instead of the default `install`.)
