### ISSUE TITLE
v0.11.21 web GUI refreshes endlessly

### ISSUE THREAD

**Issue by williamleuschner** [syncthing/syncthing#2186]
I'm running v0.11.21 of Syncthing on Debian Jessie (`3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux`). When I attempt to access the web GUI, running on `0.0.0.0:8384`, the page refreshes endlessly, preventing me from changing anything. This problem was not present in v0.11.20. My Syncthing server is connected to one other device, sharing one folder.
Here is the error in the JavaScript console (angular.min.js:216):  
```
Error: [$compile:tpload] http://errors.angularjs.org/1.2.7/$compile/tpload?p0=syncthing%2Fsettings%2FsettingsModalView.html
http://10.0.1.3:8384/vendor/angular/angular.min.js:6:454
http://10.0.1.3:8384/vendor/angular/angular.min.js:55:443
http://10.0.1.3:8384/vendor/angular/angular.min.js:66:439
y@http://10.0.1.3:8384/vendor/angular/angular.min.js:92:911
http://10.0.1.3:8384/vendor/angular/angular.min.js:94:179
$eval@http://10.0.1.3:8384/vendor/angular/angular.min.js:102:293
$digest@http://10.0.1.3:8384/vendor/angular/angular.min.js:100:55
$apply@http://10.0.1.3:8384/vendor/angular/angular.min.js:103:107
f@http://10.0.1.3:8384/vendor/angular/angular.min.js:67:104
E@http://10.0.1.3:8384/vendor/angular/angular.min.js:71:118
onreadystatechange@http://10.0.1.3:8384/vendor/angular/angular.min.js:72:160
```
In addition, the Syncthing server responds with 500 to requests for `http://[address]:[port]/rest/system/upgrade`

**Comment by calmh** [comment]
This is a bug somewhere. :) the GUI reloads when it detects a new version. Restart out browser or clear its cache, as a workaround

**Comment by williamleuschner** [comment]
Ah, that ~~fixed~~ temporarily rectified it. Thanks!

**Comment by calmh** [comment]
Yeah, I run into it now and then myself, just haven't gotten around to nailing it down. :/

**Comment by uok** [comment]
only have seen this in IE, not in Firefox. The only difference is that I use "?lang=en" in IE. I managed to open the developer tools during this browser loop and it showed an info about "back and forward caching disabled" and a link to https://msdn.microsoft.com/en-us/library/dn265017.aspx - hope this helps to narrow it down

**Comment by williamleuschner** [comment]
Oh, my browser is Safari 8.0.8.

**Comment by calmh** [comment]
Yeah, Safari here too.

**Comment by SamLefebvre** [comment]
I just had the same bug for the version 0.11.22 on Chrome 44.0.2403, windows 7 64 bits in french. After a I clear the cache the bug went away.

**Comment by passuf** [comment]
Same here, Syncthing version 0.11.22 on Chrome 44.0.2403.157 (64-bit), elementary OS Freya (0.3). Clearing the browser cache fixed the issue.
