### ISSUE TITLE
Allowed subnet list per node

### ISSUE THREAD

**Issue by er1z** [syncthing/syncthing#219]
Is it possible to introduce an option to specify which repositories should be synchronized using only LAN connection?

I have some huge data don't need to be synchronized immediately and it could be synchronized within a higher speed connection.

**Comment by flubba86** [comment]
This is more relevant now that syncthing clients are available for Mobile (android) devices. I want my phone to sync with my server only when I am connected to my home network via wifi. Yes I know I can just set a manual (internal) IP address as the destination, but limiting limiting by subnet seems a much cleaner method.

**Comment by LeoVerto** [comment]
I'm running a Syncthing server on my Raspberry Pi as both a no-cloud private filesharing service and a local solution for quickly sharing files between devices.

I really do think a per-folder setting would allow for more flexibility without having to run multiple Syncthing instances.

**Comment by AudriusButkevicius** [comment]
This is somewhat not what OP asks for, but closing as the PR intended to do that
