### ISSUE TITLE
slow sync on armhf (cubietruck)

### ISSUE THREAD

**Issue by andrewufrank** [syncthing/syncthing#2190]
i have three nodes with 300 GB in sync with Cubietruck (Cortex A20). sync with other nodes (intel) work fast as expected; starts in less than a minute (with about 40 GB), cpu goes down to 0.5%.  but the armhf nodes are very slow to start (> 10 minutes), opening a gui is several minutes till ready and cpu usage remains above 50% for more than 3 hours on data which has been synced before and has only very few (<20) small files changed. 
the differenece between intel and armhf implementations are stricking and much (say 10 times) larger than expected. could it be a difference in the implementation of encoding? 
if you need traces or similar, please instruct me!
thank you for help!

**Comment by AudriusButkevicius** [comment]
The device is probably just too weak, probably doesn't have the necessary crypto instructions.
Same goes for RPI's and other small boards.

**Comment by calmh** [comment]
Yeah, sorry. The ARM CPUs aren't very fast to start with, and the compiler probably isn't very optimized for them.

**Comment by AudriusButkevicius** [comment]
It should however settle down after the initial scan, and become usable.
