### ISSUE TITLE
"directory not empty" (When internet goes down?)

### ISSUE THREAD

**Issue by Pr0Wolf29** [syncthing/syncthing#2198]
I was looking at my logs and SUDDENLY they were flooded with entries like this:

Aug 26 02:52:39 Server2 syncthing[17988]: [YOTIT] INFO: Puller (folder "programming", dir "C++/Helper/.git/objects/d6"): delete: remove /RAID-1TB/Programming/C++/Helper/.git/objects/d6: directory not empty

I'm going to assume it should be deleting folders and not throwing errors. I think it's possibly relevant that it happened after my modem went down for a bit, causing a loss in internet connection, even though this was a sync over LAN. I don't know if this is actually causing issues with syncing, but it can certainly flood logs if it happens with a lot of folders. It looks like it's making the folder constantly out of sync.

I'm using "syncthing v0.11.21 "Aluminium Ant" (go1.5 linux-amd64 default) builduser@svetlemodry 2015-08-23 10:03:28 UTC" as per the Arch Linux repos.

Edit: It might be worth noting that it seems like I'm having this issue with the same files on a different device. https://github.com/syncthing/syncthing/issues/1973

**Comment by AudriusButkevicius** [comment]
Do you have any ignores setup? You should not sync git repos, as syncthing can corrupt them. Also, if it fixes itself when the modem comes back up, then it's just a transient issue.

**Comment by Pr0Wolf29** [comment]
I don't have any ignores set up. The problem never solved itself. I just listed the loss of the internet connection as a possible cause.

**Comment by plouj** [comment]
> You should not sync git repos, as syncthing can corrupt them.

That's a pretty scary statement. Is there a particular reason why it corrupts them or a particular situation in which corruption occurs? I sync multiple git repos, both for personal projects as well as syncthing itself (to a backup server and between my personal machines) and so far I haven't noticed any problems, but I haven't actually verified all of the data to be sure of that.

**Comment by AudriusButkevicius** [comment]
There is an answer in the forums, but git is a complex set of files, and presence of some files which get synced across just because they are there on some other machine which was making edits offline can cause corruption to gits tree.
