### ISSUE TITLE
Config option to disable automatic update checks

### ISSUE THREAD

**Issue by Dagger3340** [syncthing/syncthing#2199]
There's an option to disable automatic updates, but no way to disable the automatic version checks without recompiling. That's quite a bit of effort; can we have a config option for it please?

**Comment by AudriusButkevicius** [comment]
What do you mean automatic version checks?

**Comment by calmh** [comment]
I'm guessing this is the call to /rest/upgrade that the GUI does in order to show the upgrade button. I'm nto convinced I *want* that disabled other than by compilation (thus implying that some other package manager is in fact handling upgrades)...

**Comment by Dagger3340** [comment]
It's more the requests to https://api.github.com/repos/syncthing/syncthing/releases that I want to stop. If I have to recompile to disable them, that'll just guarantee that I never upgrade, which is a fate that I'd prefer to avoid.

**Comment by uok** [comment]
This could be used for a local update server in the future. Instead of an on/off switch for the background update check there is an advanced option to edit the address. If it is empty the default Github is used, or change the path to e.g. http://companyLAN/syncthing/releases - The update server runs a small script that reads the json from Github and presents the admin with a list of available updates that he can release. This action creates a json file that is then read by the clients. Maybe it would also be possible to roll back to an earlier release if the client is set to a custom update server and has a higher version than the allowed release on the update server

**Comment by AudriusButkevicius** [comment]
I think its a niche enough usecase that I feel this is a won't fix, and I find it normal that the user has to make his own build.

**Comment by Dagger3340** [comment]
I don't, considering that a config option to just not check for updates is easy (and I'll write the patch myself if that's what it takes) and that making my own builds will be strongly counterproductive on the "keep up to date" front (because I'll just stick with the out-of-date build rather than go through the effort of compiling every new update on Windows). I just want to prevent phoning home, not updates altogether.

Being able to set my own update server would be a usable workaround, so long as it doesn't fall back to the Github one when it can't connect.

**Comment by calmh** [comment]
I could maybe settle for a command line option `-no-upgrade`...

**Comment by Dagger3340** [comment]
That works -- I was thinking more along the lines of a hidden config file option (i.e. in the config file but not the UI), but so long as it works I don't really mind.

**Comment by uok** [comment]
I agree, a config.xml setting would help with larger installations in companies

**Comment by calmh** [comment]
I'm opposed to a conf setting that a user might set and then forget about - and all config settings are changeable in the advanced settings ui. A command line option is better, both as it takes away the control from the GUI user (where this is desirable, eg centralized deployments and wrappers that want to handle upgrades themselves) and as something more deliberate than just a checkbox. Large deployments will deploy a startup script as well (or can at least do so), or can compile with custom options as they please.

**Comment by Dagger3340** [comment]
As I say, I can settle with that. I was unaware that all settings would end up in the UI anyway.

(It does occur to me that some of the wrappers/launchers might not support passing arbitrary command-line flags, but that's fixable.)

**Comment by kozec** [comment]
Just an idea, but if you are on Windows, wouldn't setting 'STNOUPGRADE=1' as system-wide environment variable do a trick?

**Comment by calmh** [comment]
No, that just disables automatic upgrades. It doesn't disable the check when the GUI loads.

It *could* legitimately be made to do exactly that though, and that may be cleaner.

**Comment by calmh** [comment]
Actually, strike that, it should do precisely that. Doh.

**Comment by calmh** [comment]
Indeed it does. Problem solved.
