### ISSUE TITLE
[Relaying] Address/port error

### ISSUE THREAD

**Issue by xJMV** [syncthing/syncthing#2204]
INFO: Unknown Address Schema //24.212.46.207:0/0.0.0.0:22000

Making tests with V0.12.0-Beta0, right after the connection with the relay server, I get <strike>disconnected</strike> (Both GUI shows disconnected... But syncs occurs. After few restart it seems to be working properly) <strike>and then not connecting anymore.</strike>

Full logs: https://gist.github.com/anonymous/d5968d8d17190a9c1ae3

**Comment by xJMV** [comment]
However the bug is open only for the Unknown Address Schema

**Comment by calmh** [comment]
You're running an old, unknown dev version with what looks like a weird configuration. Try a newer development release, and double check your config is migrated to the new format of listen add connect addresses.

(If the latter makes no sense to you, try a release version instead. :)

**Comment by xJMV** [comment]
I use exactly that : https://github.com/syncthing/syncthing/releases/tag/v0.12.0-beta0
Running on 2 Debian Jessie VM, clean install

**Comment by calmh** [comment]
Yeah, don't do that. That tag just signifies the split of v0.11 to v0.12 so that versions compiled after that will say "v0.12.something" in their version instead of v0.11. There's nothing special about it.
