### ISSUE TITLE
Can't connect two devices

### ISSUE THREAD

**Issue by dck** [syncthing/syncthing#2207]
Sorry for such simple topic but this is the real problem.
Two computers are under simple wifi router (not the same, just similar configuration). Port forwarding is not done for syncthing port.
From both computers computer I do:
1) Run syncthing
2) Add other device clicking only one checkbox - share default folder.
And that's all. Both computers show "Never seen".
Global discovery: `1/2`.
Version: `v0.11.22`
OS: `Linux 64 bit` and `Windows 8`. 
The log:
```
[AKBFB] 21:56:18 INFO: Starting web GUI on http://127.0.0.1:8384/
[AKBFB] 21:56:18 INFO: Completed initial scan (rw) of folder default
[AKBFB] 21:56:18 INFO: Starting local discovery announcements
[AKBFB] 21:56:18 INFO: Starting global discovery announcements
[AKBFB] 21:56:18 INFO: Device AKBFBND-MOSPWGW-T6QR4UB-OGMFZK3-B7PRHFZ-KZWPUT7-WP36G3Y-4RU7BAM is "linux" at [dynamic]
[AKBFB] 21:56:18 INFO: Device 5T55RNR-FB2LLCF-HZMVJ56-7EBNRAY-NPIAO3U-4WLMASR-D2BFQFF-HDICHQ6 is "windows" at [dynamic]
[AKBFB] 21:56:19 INFO: API listening on 127.0.0.1:8384
[AKBFB] 21:56:28 INFO: No UPnP device detected
```
Maybe I do something completely wrong, but actually I did nothing unexpected and didn't change any configuration.

**Comment by calmh** [comment]
> [AKBFB] 21:56:28 INFO: No UPnP device detected

In the absence of UPnP, you will unfortunately have to set up a manual port forward since both devices are behind routers.
