### ISSUE TITLE
sync over mobile device as a modem

### ISSUE THREAD

**Issue by pinkkoff** [syncthing/syncthing#2209]
When i connect my mobile phone (iPhone) as a LTE modem, Syncthing spend a lot of time to connect with my home devices. 

Configuration:
outside: laptop, windows, SyncTrayzor + mobile LTE
home: linux ARM, Syncthing, router with NAT and Public static IP. 

In log SyncTrayzor: No UPnP device detected

I use Syncthing and BTSync simultaneously and Btsync connect very quickly, it use another search method? Is there any way to decrease connect time?

Thank you!

**Comment by AudriusButkevicius** [comment]
This sounds like a question for the forums, and not an actual issue
