### ISSUE TITLE
Command line to launch browser only

### ISSUE THREAD

**Issue by ApocalypticOctopus** [syncthing/syncthing#2210]
It would be nice if there was a command line option named e.g. `-browser-only` that causes the Syncthing executable to open the browser (to the configured Syncthing port), then immediately terminate. Alternatively, maybe there should be a separate executable for this.

This would make it easy for packagers to create a shortcut that launches the Syncthing GUI without launching a new syncing process.

**Comment by rumpelsepp** [comment]
`firefox localhost:8384`? :)

**Comment by calmh** [comment]
Mmmyeah the port may be different, and we may be on windows where the obvious grep-sed-whatever pipeline on the config xml doesn't work. I could see this justifying the fairly small complexity of including it.

**Comment by marrie** [comment]
Yeah that would be nice. I'm running the thing in a screen session so if I wanted to bring up the browser again I'd have to terminate the screen session, braking the process, or hit control plus c, and retype the long command as for my system alias commands don't work under  screen.

**Comment by calmh** [comment]
Or, just bookmark http://localhost:8384/ :)

**Comment by marrie** [comment]
Actually that works, I just start typing 127 and it will auto complete. consider this a temprary  fix as the beginning user won't know about this. Lol!

Take care.

**Comment by Moter8** [comment]
Pointers:

https://github.com/skratchdot/open-golang  https://stackoverflow.com/questions/10377243/how-can-i-launch-a-process-that-is-not-a-file-in-go-e-g-open-a-web-page

I've tried to work on it but I was not sure what the best way to read from the config file was. Tested on *nix this works right now.

https://github.com/Moter8/syncthing/commit/f2340ff16d0bcc4315fcb0a539d4e234c0640442

**Comment by calmh** [comment]
Oh it's easier than that. Grep for "openURL" or something similar, we already have code to start the browser in there.
