### ISSUE TITLE
Broken software

### ISSUE THREAD

**Issue by jjpe** [syncthing/syncthing#2214]
I see no way in either the manual or the software to actually make things sync. It looks like it but it's permanently out of sync. Please fix, as-is this whole thing is pointless.

I'm using the server on OS X and the Android app.
The workflow as far as I can figure it out:
1. add a folder to sync on the OS X web interface. Mark it as the folder master.
2. add a folder on the app with the same folder id
3. let 'er rip (well, crash and burn).

If this is not the intended workflow, the GUI needs a lot of work, since that is what it suggests to me.

**Comment by AudriusButkevicius** [comment]
This is just a rant without any actual issue description, steps of reproduction or anything. Open an issue with a proper description.

**Comment by jjpe** [comment]
Read again.

**Comment by NathanSalapat** [comment]
@jjpe You need to add the folders on both devices with the same folder ID as you state. You also have to add the machines on both instances to the other machine, and then in the folders option tell it to share with that other device. If you are doing that, everything is correct and there is some other issue but as AndriusButkevivus said you aren't giving us any error codes to work with.

**Comment by jjpe** [comment]
I've done all of the above. There are no error codes, just a perpetual failure to actually sync the data.

**Comment by NathanSalapat** [comment]
What kind of console output is there. Also make sure both instances are running the same version, though that shouldn't matter so much, might also need to delete the configs from the two and start from fresh.

**Comment by jjpe** [comment]
I just double-checked, both my homebrew version and the android app version are `v0.11.22`.
Also, I installed both today. No console output from the OS X version since I've daemonized it with 

````
==> Caveats
To have launchd start syncthing at login:
  ln -sfv /usr/local/opt/syncthing/*.plist ~/Library/LaunchAgents
Then to load syncthing now:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.syncthing.plist
````

That is part of the output from `homebrew info syncthing`.

**Comment by MyPod** [comment]
That is not the "console output" expected. To clarify, what is wanted and
meant with that is the output of 'syncthing' when run manually - or a
sample of the log if it's kept somewhere. Every other issue provides a
sample of the output of the program - not of brew or apt/dpkg/etc - from
which it can be understood, in most cases, why things don't work as expected

**Comment by calmh** [comment]
There may be new bugs or otherwise interesting issues with android to cause the "override" type of situation. 
Not sure about the 127 Meg's vs 11 gigs thing, thats new. :)

**Comment by calmh** [comment]
In any case, check the files that are apparently out of sync for any clues, and do read the log output.

**Comment by AudriusButkevicius** [comment]
Or post screenshots so others could look at it. Also, to me this seems more like a support issue, and should perhaps be exercised in the forums.
