### ISSUE TITLE
revoking the usage of tls in the gui webinterface

### ISSUE THREAD

**Issue by andywenk** [syncthing/syncthing#2216]
First of all, syncthing is awesome. Thanks a lot for the great work!

I have installed syncthing on a Ubuntu 12.04 box. I have set "Use HTTPS for GUI" in the admin webinterface to true. Unfortunately, due to some stupid server settings an collision with another domain running under SSL, I wanted to change the config in

    ~/.config/syncthing/config.xml

by setting    

<code>
   &lt;gui enabled="true" tls="false"&gt;
</code>

But I was surprised, that it was still set to false. After restarting syncthing with 

    initctl stop syncthing
    initctl start syncthing

there is still a redirect to https. Am I doing sth. wrong? Does it not work like this?

Thanks and all the best

Andy

**Comment by andywenk** [comment]
sorry this was absolutely my fault. Everything is fine! I created a user syncthing and should have looked into

    /home/syncthing/.config/syncthing/config.xml 

instead of

    /root/.config/syncthing/config.xml 

Sorry and thanks again for this awesome piece of software!

**Comment by calmh** [comment]
:) all good
