### ISSUE TITLE
Inconsistent information displayed in Advanced Configuration GUI

### ISSUE THREAD

**Issue by ProactiveServices** [syncthing/syncthing#2217]
Related to https://github.com/canton7/SyncTrayzor/issues/134

Using SyncTrayzor 1.0.27 with Syncthing 0.11.23.
Syncthing's config.xml has the GUI listen address as 127.0.0.1:21245
SyncTrayzor is overriding this to localhost:8384 and Syncthing is obeying this, but in the GUI Syncthing states it is using the config.xml values, which it is not. This caused me some confusion when looking how to connect to Syncthing via a browser.

**Comment by calmh** [comment]
Borderline case... It's showing what's configured, but it's not actually using what's configured because it's been overridden from the outside.

**Comment by canton7** [comment]
It might be nice to note that the value being set here might not have any effect, since Synthing is being launched with `-gui-address`

**Comment by calmh** [comment]
Maybe.

**Comment by imsodin** [comment]
Fixed in #5210 by displaying such a note.
