### ISSUE TITLE
Syncthing crashes

### ISSUE THREAD

**Issue by juh2** [syncthing/syncthing#2219]
Syncthing crashes while sync'ing desktop and macbook. 

```
[RJYAC] 09:00:23 INFO: syncthing v0.11.23 "Aluminium Ant" (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-08-30 11:37:18 UTC
...
[RJYAC] 09:05:30 INFO: Completed initial scan (ro) of folder Musik
Panic at 2015-09-01T09:06:34+02:00
panic: read /home/juh/.config/syncthing/index-v0.11.0.db/144405.ldb: input/output error
```

**Comment by calmh** [comment]
That's an I/O error on the disk holding the database. Your disk may be dying, or the filesystem is corrupted, or similar. Check dmesg and the usual suspects.

**Comment by juh2** [comment]
Damn. Right. I'll order a new disk. :-(

**Comment by juh2** [comment]
I don't get any I/O errors when syncthing isn't running. I new disk is ordered, but before I open the machine – would it make sense to delete the file Syncthing is trying to access? It is an index db file of an old version. Or is it bette to delete the whole syncting folder. I would have no problems to let Syncthing resync the whole directories.

**Comment by AudriusButkevicius** [comment]
You can just delete the index directory and let it rescan, but just follow your dmesg output for disk errors from the kernel.
