### ISSUE TITLE
Should be more responsive to errors from other devices

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2221]
If we try to fetch a block from a device, and we get back a "no such file" error, there's probably no point in retrying that same device for other blocks (or even the same block) in the near future. Likewise if we get back data with an incorrect hash.

Should we mark the file as invalid on behalf of the other device if they give us an error? That seems reasonable to me now, but will be a problem with delta indexes (as we'd have modified the index sent from the other side). (The same applies to ignores, maybe, now that I think of it.)

Perhaps we can have a separate map of file+device => isInvalid that we set and periodically forget?

**Comment by AudriusButkevicius** [comment]
This could be an in-memory thing in the pull loop

**Comment by calmh** [comment]
Yep

**Comment by AudriusButkevicius** [comment]
I think we send the hash already, so the provider can check himself, and if it doesn't match check its own index and rescan, but that means hashing on both sides.

**Comment by calmh** [comment]
Mmm

**Comment by imsodin** [comment]
Related: The provider now does check the hash (#4767).

**Comment by calmh** [comment]
I think this is a non issue now.
