### ISSUE TITLE
Local discovery over IPv4 unavailable with two instances

### ISSUE THREAD

**Issue by DoctorJellyface** [syncthing/syncthing#2222]
I'm running two syncthing instances on my computer. One as my user, for syncing my private files, and one as root, for syncing the pacman cache with my brother's computer which also runs Arch.

However, I keep getting `Local discovery over IPv4 unavailable: listen udp4 :21025: bind: address already in use` errors for my (as in user) syncthing. However, on the first time I launched the root syncthing, and mine was already running, I got the errors on the root one instead.

**Comment by calmh** [comment]
The ipv4 local discovery uses broadcasts on port 21025. Only one process can bind to that port at a time, per machine, unfortunately. So this is as designed. The IPv6 multicasts should work though.

**Comment by DoctorJellyface** [comment]
Is there a way to disable the error message?

**Comment by calmh** [comment]
You can disable local discovery (although that affects IPv6 as well), or change the port to something else among the settings.

**Comment by DoctorJellyface** [comment]
Is there any port I can change it to without ruining anything else?

**Comment by calmh** [comment]
Sure, pick any. 21029. 65232.

**Comment by DoctorJellyface** [comment]
Hm, thanks. Btw, why is this closed? Shouldn't synchting be able to workaround this itself?

**Comment by calmh** [comment]
I haven't found a (working, cross platform) way to listen for broadcasts on the same port on IPv4. I think we'll have to settle for local discovery over IPv6 working under these circumstances.

**Comment by DoctorJellyface** [comment]
Oh well. And at least stopping the error when a second syncthing instance is detected?

**Comment by AudriusButkevicius** [comment]
Change the port on onr of the instances

**Comment by calmh** [comment]
Why? It's a message informing you that local discovery over IPv4 unfortunately can't function under the current circumstances. It's correct. Hiding it would be more confusing, as you'd have no idea why things weren't working properly.

**Comment by DoctorJellyface** [comment]
You did say that it works properly, ust with Ipv6 ;)

What about embedding a message about changing the port into the message?

**Comment by calmh** [comment]
It doesn't solve the problem, as local discovery over IPv4 still won't work - you just won't get an error about it.

**Comment by DoctorJellyface** [comment]
Oh. Sucks. Thanks for the help though, really appreciate it.
