### ISSUE TITLE
Adding system tray or menu bar

### ISSUE THREAD

**Issue by ginbroker** [syncthing/syncthing#2224]
eg. https://github.com/getlantern/lantern on OS X
![screen shot 2015-09-02 at 11 58 47](https://cloud.githubusercontent.com/assets/8635227/9622154/4ae11828-516a-11e5-8a90-1cb7d5895b43.png)

**Comment by AudriusButkevicius** [comment]
Use a thirdparty app for that and more. The problem is that this requires building with cgo, and potentially kills cross compiling.

**Comment by ginbroker** [comment]
ok, thanks.

**Comment by OIBIS-Wikus** [comment]
There is something out for Windows called SyncTrayzor: https://github.com/canton7/SyncTrayzor
You can ask them if they're planning on releasing an OS X version.

**Comment by AudriusButkevicius** [comment]
Syncthing-GTK works on OS X, there is a bunch of other contributions (see docs) which work on OS X. Also there are a few in the forums which are not on the list.
