### ISSUE TITLE
Spurious "home disk is out of space"

### ISSUE THREAD

**Issue by raichu** [syncthing/syncthing#2227]
> rwfolder.go:308: INFO: Skipping folder default scan due to folder error: home disk is out of space

My syncthing directories have a total of 6GB data and my /home partition has 9GBs free space.
This shouldn't happen I guess.

(Syncthing is refusing to sync BTW so it's a real issue.)

**Comment by raichu** [comment]
The / filesystem has only 2GBs though. Maybe it's looking at the wrong place?

**Comment by calmh** [comment]
The "home disk" is where the index lives, by default ~/.config/syncthing - can you post the output of "df" for that partition? The default limit is that it should be no more than 99% full.

You can disable this check in the meantime by setting minHomeDiskFreePct to 0 in the config.xml

**Comment by raichu** [comment]
"it should be no more than 99% full." seems to be the problem, harddisks can be pretty big. 

Mine is an 8TB partition, so unless I have 80GB or more, syncthing won't sync then.

I think the code should be changed such that it checks the available free space (and not the percentage), which is the actual metric to determine whether you can do the sync or not.
You never know the partition size, it can soon be more than 40TB in several years.

**Comment by calmh** [comment]
Right, so setting that to zero should work fine in your case. I'd like to give the current system a but more exposure before reevaluating the defaults.

**Comment by raichu** [comment]
The workaround works fine.

I'm not talking about defaults though --I mean the mechanism is faulty (and most likely unique to syncthing). Like other download programs, syncthing should check the available free space.

This is an obvious flaw in the design for the reasons I mentioned, and you probably don't want to defer this to 1.0+.

**Comment by calmh** [comment]
What should be the threshold we check for?

**Comment by raichu** [comment]
The size of the content that is going to be pulled?
The upper limit would be the total size of the local folder + remote folder.

What most programs do is to let user specify a threshold (default is usually less than 1GB), and they stop syncthing/downloading if the free space gets any lower.

**Comment by Zillode** [comment]
>How about the size of the content that is going to be pulled?
The upper limit would be the total size of the remote directory.

1. Computing this is (currently) quite resource intensive
2. This is about the home folder, i.e. we don't know how much the database engine will grow over time

>What most programs do is to let user specify a threshold (default is usually less than 1GB), and they stop syncing/downloading if the free space gets any lower.

1. Well, you can ask this to new users and some of them have no idea what it will mean. Thus a reasonable default should be picked. Given the fact that Syncthing is used on raspberry Pis, Android phones etc, 1GB would be far less optimal than 1%.
2. If you disk only has 1% free disk space, it is time to check it out. If you want to live on the edge you can set this to 0%.

**Comment by jpjp** [comment]
How about 100 megabytes usable free?

**Comment by Zillode** [comment]
Could be an option for the home folder. However, I think we should go for safety first, because we don't have tests in place that show how Syncthing behaves when you run out of disk space.

**Comment by uok** [comment]
the "problem" is that Syncthing runs on such a wide range of devices that % can never satisfy all scenarios.Mmaybe Syncthing could allow float %, e.g. 0.01% and display the resulting free space in GB next to it. On the other hand a default like 1GB would be easier to understand. If many users don't like this setting they will set it to 0% all the time which may require tests

**Comment by calmh** [comment]
The size of the index has nothing to do with how much we are going to pull. I ranges from essentially zero at start and for small installations, to at least 15 gigs in some recent forum thread. When a device connects, it balloons to receive their index, then compacts down again.

For example 100 megs is completely unnecessary to ask for on a phone that's just going to sync a few photos or so. However it's nowhere near enough when connecting to a device that is going to tell us about it's one million documents.

For the actual *folders* we *do* check that the pull will have space to complete.

**Comment by jpjp** [comment]
But we need space to complete plus a reserve, what's the reserve?

**Comment by calmh** [comment]
For *folders*, we check for 1% free or space to complete the pull, whichever is larger. We can argue about the 1% check there - it's probably unnecessary, as we actually *do* know how much space we're going to need for the pull.

For the *index*, as this issue is about, we check only for 1% of free space as we don't actually know the real requirement ahead of time. We could possibly check for a certain fixed reserve being available instead. We'd probably have to do it prior to each database write which might be annoying.

**Comment by raichu** [comment]
@Zillode

> If you disk only has 1% free disk space, it is time to check it out. If you want to live on the edge you can set this to 0%.

This is the fallacy I've been talking about.
In case you missed my earlier posts, 1% means 80GBs in my case. I can't see how this is "living on the edge". On my phone, however, 1% means only 40MBs. See the gap?

**Comment by calmh** [comment]
#2233
#2234 
#2235
