### ISSUE TITLE
Elegant handling of "No more space left on device"

### ISSUE THREAD

**Issue by gchauras** [syncthing/syncthing#2229]
Ran into a case when my Ubuntu drive was full. The syncthing browser instance hung up. I killed it and I ran syncthing from command line and it tried restarting 4 times and then exited. It might be better to detect this error, display an error or dump it into the log and suspend the application. You may poll the filesystem for available space every 5 minutes after this and restart the server when more space becomes available.

**Comment by AudriusButkevicius** [comment]
It already does that. Which version are you running?

**Comment by gchauras** [comment]
I installed from this ppa
https://launchpad.net/~ytvwld/+archive/ubuntu/syncthing
```
$ syncthing --version
syncthing v0.11.0 (xgcc (Ubuntu 4.9.1-0ubuntu1) 4.9.1 linux-amd64 default) niklas@Niklas-Netbook 2015-04-26 13:15:08 UTC
```

**Comment by AudriusButkevicius** [comment]
Yeah this is fixed in a recent version. Also, the compiler used in that version is not supported.

**Comment by calmh** [comment]
*v0.11.0*?? That's ancient. Don't use that PPA. Use the official Ubuntu builds: http://apt.syncthing.net
