### ISSUE TITLE
Minimum free disk space should be configurable in fractional percentages

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2233]
I.e. 0.1 and so on, as opposed to just integers currently. Goes for both the per folder and the "home disk" one.

**Comment by uok** [comment]
I suggest to rename `minHomeDiskFreePct` to `minIndexFreePct` to avoid confusion

**Comment by calmh** [comment]
I think that would be a bad idea as we refer to is as home in other places, i.e. the `-home` flag and so on. However the actual *error* message should probably refer to something like `volume where the configuration and index resides` or something.
