### ISSUE TITLE
fix aspect ratio of syncthing logo on safari (win&mac)

### ISSUE THREAD

**Issue by Eddy2909** [syncthing/syncthing#2238]
![logo_schrott2](https://cloud.githubusercontent.com/assets/12877411/9699847/c0400f4c-53f0-11e5-9e02-72ff5b0ea19e.JPG)
![logo_schrott1](https://cloud.githubusercontent.com/assets/12877411/9699848/c058fc46-53f0-11e5-9613-5673b321d2d0.JPG)

**Comment by calmh** [comment]
It sure doesn't look like that for me. In neither of the places, including the wacky fonts... I suspect this is something local to your computer, or people would have been pointing and laughing loudly before?

**Comment by Eddy2909** [comment]
maybe yes, they would.. but finding such a strange thing without creating a issue.. oO could not sleep :-)

**Comment by calmh** [comment]
See if you can reproduce it on another box?
