### ISSUE TITLE
Systemd doesn't restart syncthing after web GUI restart (v0.11.23)

### ISSUE THREAD

**Issue by bluewavenet** [syncthing/syncthing#2239]
Running 0.11.23 on Suse Linux 13.2 64 bit using systemd for startup etc. 
Restart pops up "Syncthing is restarting. Please wait...." for ever.

"systemctl status syncthing@rob.service -l " returns the following:
syncthing@rob.service - Syncthing - Open Source Continuous File Synchronization for rob
   Loaded: loaded (/etc/systemd/system/syncthing@.service; enabled)
   Active: inactive (dead) since Sat 2015-09-05 16:14:45 BST; 2min 13s ago
     Docs: http://docs.syncthing.net/
  Process: 902 ExecStart=/usr/bin/syncthing -no-browser -logflags=0 (code=exited, status=3)
 Main PID: 902 (code=exited, status=3)
Sep 05 13:44:35 linux-tosh.site syncthing[902]: [WOEAN] INFO: Local discovery (broadcast writer): write udp4: network is unreachable
Sep 05 13:45:47 linux-tosh.site syncthing[902]: [WOEAN] INFO: Established secure connection to H3HO47M-PTTISGN-GZQ7JGV-UDKJNKB-VTR7IDQ-UKSCMWO-7B3KRUH-6CVDYQB at [fe80::76de:2bff:feb1:7033%wlan0]:50698-[fe80::216:cfff:feab:da4%wlan0]:22000
Sep 05 13:45:47 linux-tosh.site syncthing[902]: [WOEAN] INFO: Device H3HO47M-PTTISGN-GZQ7JGV-UDKJNKB-VTR7IDQ-UKSCMWO-7B3KRUH-6CVDYQB client is "syncthing v0.11.23"
Sep 05 13:45:47 linux-tosh.site syncthing[902]: [WOEAN] INFO: Device H3HO47M-PTTISGN-GZQ7JGV-UDKJNKB-VTR7IDQ-UKSCMWO-7B3KRUH-6CVDYQB name is "linux-inspiron.site"
Sep 05 14:02:54 linux-tosh.site syncthing[902]: [WOEAN] INFO: New UPnP port mapping: external port 19988 to local port 22000.
Sep 05 16:14:45 linux-tosh.site syncthing[902]: [WOEAN] INFO: Restarting
Sep 05 16:14:45 linux-tosh.site syncthing[902]: [WOEAN] OK: Exiting

Manual start is then required to bring it back up. Otherwise seems to run just fine and does the business! Bit of a pain though as it asks to restart for just about any change....

**Comment by calmh** [comment]
This is systemd configuration. Our [recommended systemd setup](https://github.com/syncthing/syncthing/tree/master/etc/linux-systemd) gets this right, so I think someone has screwed up either the packaging in Suse or your local config?

**Comment by bluewavenet** [comment]
Could of course be something local but I'm just using the downloaded syncthing@.service file.
A manual "systemctl restart syncthing@rob.service" works ok. 
I have two instances running for two users, both instances have the same problem. The sync works fine - very impressed by the way. All the hard work is appreciated ;)

**Comment by calmh** [comment]
That's odd. It says "exited, status=3" and 3 is one of the exit codes mentioned in RestartForceExitStatus... But that's also the sum total of my knowledge of systemd, zero exposure so far. Hopefully someone more versed in systemd can chime in.

**Comment by bluewavenet** [comment]
Got it working, not sure if there will be repercussions but it looks ok ...
Changed the line in syncthing@.service as follows:
SuccessExitStatus=2 3 4
to
SuccessExitStatus=2 4
It seems SuccessExitStatus was overriding the entry in RestartForceExitStatus which does make sense. But is this unique to OpenSuse13.2?

**Comment by kozec** [comment]
Those definitions are changing pretty frequently, if you are using systemd, it is something you should be accustomed to :)

**Comment by bluewavenet** [comment]
Yup, new to it - nothing like something new every day :)

**Comment by bluewavenet** [comment]
Looking at systemd man ( http://www.freedesktop.org/software/systemd/man/systemd.service.html ) it makes perfect sense and should be correct for SuccessExitStatus to override RestartForceExitStatus, in which case syncthing@.system and syncthing.system are in error and should in fact have the corrected line:
SuccessExitStatus=2 4
We need someone to verify this. Working perfectly here now.

**Comment by rumpelsepp** [comment]
Changing 

```
SuccessExitStatus=2 3 4
```

to

```
SuccessExitStatus=2 4
```

causes an error in addition to let systemd restart the service, see https://github.com/syncthing/syncthing/commit/da0b78c67a19aa1dbef43e877e975efa765578bd. Unless nothing special in systemd has changed I would say the service files are fine, since I use them on 4 machines without problems. After clicking the restart button in the gui (ExitCode 3) systemd does its job properly on my machine:

```
...
Sep 06 11:14:44 alderaan syncthing[28120]: [TYZZZ] INFO: Device NXFFORR-BPMJIZY-4QLLUIS-T4BYAU3-LBCGNC2-5ZCZ4FL-IN47BLC-F7MFMQ4 client is "syncthing v0.11.10"
Sep 06 11:14:44 alderaan syncthing[28120]: [TYZZZ] INFO: Device NXFFORR-BPMJIZY-4QLLUIS-T4BYAU3-LBCGNC2-5ZCZ4FL-IN47BLC-F7MFMQ4 name is "tatooine"
Sep 06 11:14:46 alderaan syncthing[28120]: [TYZZZ] INFO: New UPnP port mapping: external port 4027 to local port 22000.
Sep 06 11:24:07 alderaan systemd[6026]: syncthing.service: Service hold-off time over, scheduling restart.
Sep 06 11:24:07 alderaan systemd[6026]: Stopped Syncthing - Open Source Continuous File Synchronization.
Sep 06 11:24:07 alderaan systemd[6026]: Started Syncthing - Open Source Continuous File Synchronization.
Sep 06 11:24:07 alderaan syncthing[28598]: [TYZZZ] INFO: syncthing v0.11.23 "Aluminium Ant" (go1.5 linux-amd64 default) builduser@flexiondotorg 2015-08-30 11:37:18 UTC
Sep 06 11:24:07 alderaan syncthing[28598]: [TYZZZ] INFO: My ID: TYZZZEJ-EZXAHJ7-EQVYGOQ-24MYW4Z-NF4YI6J-CHI6YYM-2CRXPUM-BF3HMQR
Sep 06 11:24:07 alderaan syncthing[28598]: [TYZZZ] INFO: Archiving a copy of old config file format
Sep 06 11:24:07 alderaan syncthing[28598]: [TYZZZ] INFO: Database block cache capacity 65536 KiB
...
```

Maybe you use an outdated systemd version?

**Comment by bluewavenet** [comment]
My systemd version is 210-25.16.1
It only restarts from gui here with:
SuccessExitStatus=2 4
With SuccessExitStatus=2 3 4, it just exits. My interpretation of SuccessExitStatus is a list of exit codes indicating a clean shutdown so systemd then stops unless ExecStopPost is defined (of no use here though).

What error do you get with SuccessExitStatus=2 4?

**Comment by rumpelsepp** [comment]
> My interpretation of SuccessExitStatus is a list of exit codes indicating a clean shutdown so systemd then stops unless ExecStopPost is defined (of no use here though).

It is a list of exit codes which systemd considers as *no* errors. The restart action can be triggered generically on error (with an inappropriate error message; https://github.com/syncthing/syncthing/commit/da0b78c67a19aa1dbef43e877e975efa765578bd) or just on a particular exit code; in this case `3`.

> What error do you get with SuccessExitStatus=2 4? 

It is explained in the commit message: https://github.com/syncthing/syncthing/commit/da0b78c67a19aa1dbef43e877e975efa765578bd

> My systemd version is 210-25.16.1

Since systemd 225 is the most recent release I recommand updating first. The `RestartForceExitStatus` setting has been added in systemd 215 (https://github.com/systemd/systemd/blob/c9912c5eafa03fdf53e569eaf2e89d7e0932975b/NEWS#L1660-L1664), so that is most likely causing your problem.

**Comment by bluewavenet** [comment]
You are correct, this is causing the problem. I could compile the latest version and use that but I am wanting to roll this out on the stock distro of OpenSuse 13.2 if possible.
I removed the RestartForceExitStatus line and it is indeed ignored. However it works just fine with SuccessExitStatus=2 4
In your commit I see:
syncthing.service: main process exited, code=exited, status=3/NOTIMPLEMENTED
Is this not syncthing v0.10.30 that was causing the problem with status 3 not implemented?

I get, with SuccessExitStatus=2 3 4:
Main PID: 902 (code=exited, status=3)
indicating it is now implemented and with my version of systemd it just shuts down.

With my workaround It works with no errors so I'm happy to run with it unless someone tells me otherwise ;) A one character change in a config file is a lot easier than compiling and maintaining a non standard implementation (as far as the official distro is concerned).

**Comment by rumpelsepp** [comment]
> syncthing.service: main process exited, code=exited, status=3/NOTIMPLEMENTED
> Is this not syncthing v0.10.30 that was causing the problem with status 3 not implemented?

That message is generated by *systemd* and not syncthing; #1324. Systemd assumes an exit code `0` as success; everything else as failure unless you configured otherwise using `SuccessExitStatus`. So, syncthing 0.10.30 returned `3` and systemd didn't know what that means.

> With my workaround It works with no errors so I'm happy to run with it unless someone tells me 
> otherwise ;) 

Should be ok.

**Comment by AudriusButkevicius** [comment]
Right, case closed, update your systemd, or remove the exit code from success.
