### ISSUE TITLE
Minimum free disk space and network drives

### ISSUE THREAD

**Issue by OllieTerrance** [syncthing/syncthing#2241]
If a sync folder is located on a network drive (e.g. mounted with cifs/smb), the disk space will be that of the parent mountpoint, so will give incorrect results.

I have Syncthing running on a Raspberry Pi (Arch Linux, Syncthing v0.11.23 ARM), with a folder set to sync to a connected network drive.  The drive is 500GB with plenty of space remaining, though with the root filesystem only 4GB and the folder to sync at ~30GB, it refuses to make any progress.

Most of the folder is already synced from copying files manually.  Minimum free disk space for the folder is set to 0.

```
Sep 06 10:13:38 neo syncthing[9432]: [JYWGF] INFO: Completed initial scan (rw) of folder Sync
Sep 06 10:13:56 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 32 files (198.82MB)
Sep 06 10:21:45 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 603 files (3469.89MB)
Sep 06 10:22:04 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 603 files (3469.89MB)
Sep 06 10:23:12 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 604 files (3478.70MB)
Sep 06 10:25:05 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 605 files (3489.28MB)
Sep 06 10:27:13 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 606 files (3497.91MB)
Sep 06 10:30:49 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 607 files (3509.04MB)
Sep 06 10:32:53 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 608 files (3518.16MB)
Sep 06 10:33:52 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 609 files (3526.54MB)
Sep 06 10:35:39 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 610 files (3534.04MB)
Sep 06 10:37:02 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 612 files (3542.62MB)
Sep 06 10:37:16 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 612 files (3542.62MB)
Sep 06 10:38:15 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 613 files (3546.58MB)
Sep 06 10:40:16 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 615 files (3554.11MB)
Sep 06 10:41:25 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 617 files (3559.79MB)
Sep 06 10:42:21 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 619 files (3569.06MB)
Sep 06 10:44:00 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 621 files (3575.47MB)
Sep 06 10:45:20 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 623 files (3581.06MB)
Sep 06 10:46:34 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 625 files (3586.51MB)
Sep 06 10:47:25 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 627 files (3593.75MB)
Sep 06 10:48:31 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 628 files (3598.13MB)
Sep 06 10:49:44 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 629 files (3603.43MB)
Sep 06 10:51:35 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 631 files (3611.97MB)
Sep 06 10:53:49 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 632 files (3616.50MB)
Sep 06 10:54:15 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 633 files (3625.09MB)
Sep 06 10:55:27 neo syncthing[9432]: [JYWGF] INFO: Puller (folder "Sync"): insufficient disk space available to pull 634 files (3630.45MB)
```

**Comment by OllieTerrance** [comment]
(This is when the folder is not a master for this device, unlike #2236.)

**Comment by AudriusButkevicius** [comment]
As a workaroubd, you can disable the check in advanced config, though this should be addressed, I guess it's a bug with the code which checks available space

**Comment by Zillode** [comment]
Hmm, https://github.com/syncthing/syncthing/blob/b2193b23e5e3ae381a0025a39aee3fa9a89b003e/lib/model/rwfolder.go#L515 should already point to resolved path.

**Comment by OllieTerrance** [comment]
Shouldn't that check be _and_, not _or_?

```go
if folderCfg.MinDiskFreePct > 0 || pullFileSize > 0 {
```

We want to check if we're enforcing a minimum free disk size, _and_ there's something to pull.

**Comment by calmh** [comment]
> the disk space will be that of the parent mountpoint

That's weird, I see no reason for that being the case. Sounds like a bug, will investigate.

> Shouldn't that check be and, not or?

Ehh... Yes, it should. :disappointed:

**Comment by calmh** [comment]
To be clear, you have the sync folder on a network share right, you haven't mounted a network share inside the sync folder?

**Comment by OllieTerrance** [comment]
Correct, it's a cifs mount at `/mnt/Oracle`, the sync folder is at `/mnt/Oracle/Sync`.

I was assuming the free space behaviour -- `df` doesn't show the mount, so I guessed it would look for the next mount, which here would be `/`.

Explicitly querying the mountpoint gives:

```
$ df /mnt/Oracle
Filesystem                                 1K-blocks  Used Available Use% Mounted on
//192.168.1.254/USB_Disk/Oracle_0BC2_____1         0     0         0    - /mnt/Oracle
```

...which may be causing interesting results with the free space checks?

**Comment by AudriusButkevicius** [comment]
Well I guess if df can't report, we should fail too somehow, not report space of some other volume.

**Comment by calmh** [comment]
> df doesn't show the mount

Yeah, what's up with that? It sounds broken.

**Comment by OllieTerrance** [comment]
I agree, this may be a quirk in my configuration -- the share is from my router which may well not be providing the disk space info properly.  Obviously out of scope here.

After a few restarts and remounts, it seems to be making some progress now.  (Which is odd as I had tried this before to no avail -- the only change now is that the folder master is running v0.11.24, but that shouldn't affect this?)

In any case, I think 86234db2 will hopefully solve it on the other end...

**Comment by calmh** [comment]
Yeah. So, in the end we just ask the system how much free space there is at the folder root. If your system doesn't itself know about the network mount enough for it to show up in a `df`, it's probably not going to be able to tell us the truth. So I think that part is up to your system, and the other half of the problem is the commit you point to. It'll be in the next release. :/

**Comment by OllieTerrance** [comment]
Looks like we're good as of v0.11.25.  Disabling free space checks isn't ideal, but given I know there's plenty of space, and the mount has no idea, it works for me.  :smile:

On a possibly related note, the new disk space warning doesn't seem to substitute all the variables -- spotted in the logs from last night:

```
...
Sep 14 23:09:10 neo syncthing[5307]: [JYWGF] INFO: Folder "/mnt/Oracle/Sync": insufficient disk space in path/to/file/a for %!s(float64=0): have 8.23 MiB, need %!f(MISSING) MiB
Sep 14 23:09:10 neo syncthing[5307]: [JYWGF] INFO: Folder "/mnt/Oracle/Sync": insufficient disk space in path/to/file/b for %!s(float64=0): have 6.53 MiB, need %!f(MISSING) MiB
Sep 14 23:09:10 neo syncthing[5307]: [JYWGF] INFO: Folder "/mnt/Oracle/Sync": insufficient disk space in path/to/file/c for %!s(float64=0): have 2.16 MiB, need %!f(MISSING) MiB
Sep 14 23:09:10 neo syncthing[5307]: [JYWGF] INFO: Folder "/mnt/Oracle/Sync": insufficient disk space in path/to/file/d for %!s(float64=0): have 5.08 MiB, need %!f(MISSING) MiB
Sep 14 23:09:10 neo syncthing[5307]: [JYWGF] INFO: Folder "/mnt/Oracle/Sync": insufficient disk space in path/to/file/e for %!s(float64=0): have 5.44 MiB, need %!f(MISSING) MiB
...
```

...though this may be because of disabling the checks?  It seemed to sync them over anyway.

**Comment by AudriusButkevicius** [comment]
Reopening as a reminder to fix the format string

**Comment by calmh** [comment]
We fixed the format string but forgot the issue
