### ISSUE TITLE
Pass User Names in syncthing@.service for display on WebGui.

### ISSUE THREAD

**Issue by bluewavenet** [syncthing/syncthing#2244]
I now have a successful set up using 3 laptops running openSuse 13.2. Two or more users on each laptop (same users). Successfully syncing their /home/data directories making it possible for any user to use any laptop with the third laptop not used much doing a traditional backup to a usb storage device.
Works very well so far. 
Big problem is differentiating between instances on the web gui. The hostname is dispayed so that is good. 
Can the user name also be displayed? If not currently this could probably be an easy enhancement, particularly if username is passed to syncthing on the command line by syncthing@.service.
Something like:
ExecStart=/usr/bin/syncthing -no-browser -logflags=0 -user=%i

**Comment by AudriusButkevicius** [comment]
That leaks stuff, so I personally be against it.

**Comment by bluewavenet** [comment]
How will it leak anything?  The users will know nothing of the syncthing cli and if it confuses me which gui instance I am looking at then it will surely confuse the users.
For example I can go to:
http://localhost:8384
or
http://localhost:8385 
for accessing two separate instances. 
or even:
http://192.168.1.94:8385/ etc.
Yes I can set password access to the gui but I commonly have all three instances open in tabs in my browser. 
For a significantly larger rollout with multiple devices and multiple instances running on a server etc it will become very desirable. 
Is it any leakier than displaying the hostname?

**Comment by AudriusButkevicius** [comment]
Yes, you cannot attack an account by knowing a hostname, you can attack an account by knowing a username. I feel that this is a niche single case easily solvable by the user (by just renaming after setup) hence can stay unfixed to avoid infornation leakage.

**Comment by calmh** [comment]
Note that what is sent to the other side is what is set as "device name" in the settings - it just defaults to the hostname. You can set this to "someuser@foo" or whatever you like.

**Comment by bluewavenet** [comment]
@calmh That works, thanks. Another step to remember to do but simple enough. Are there any limitations in characters that can be used? eg spaces, graves, accents etc .

**Comment by calmh** [comment]
I don't think there are any special restrictions on that field

**Comment by calmh** [comment]
No, looks fine;

```
[I6KAH] 09:22:56 INFO: Device JMFJCXB-GZDE4BN-OCJE3VF-65GYZNU-AIVJRET-3J6HMRQ-AUQIGJO-FKNHMQU name is "Räksmörgås Действия 地址列表"
```

**Comment by bluewavenet** [comment]
;)
