### ISSUE TITLE
Relay stuff panics when disabled

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2246]
In this case because global discovery is disabled.

```
[I6KAH] 09:39:21 INFO: syncthing v0.12.0-beta0+76-gf2db1c8 "Beryllium Bedbug" (go1.5 darwin-amd64 default) jb@syno 2015-09-06 19:24:00 UTC
...
[I6KAH] 09:39:21 INFO: Device JMFJCXB-GZDE4BN-OCJE3VF-65GYZNU-AIVJRET-3J6HMRQ-AUQIGJO-FKNHMQU is "s2" at [tcp://127.0.0.1:22002]
Panic at 2015-09-07T09:39:21+02:00
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x306f98]

goroutine 73 [running]:
github.com/syncthing/syncthing/lib/relay.(*Svc).ClientStatus(0x0, 0x1)
        /Users/jb/src/github.com/syncthing/syncthing/lib/relay/relay.go:195 +0x1b8
github.com/syncthing/syncthing/lib/discover.(*Discoverer).announcementPkt(0xc8200b8700, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jb/src/github.com/syncthing/syncthing/lib/discover/discover.go:314 +0x23c
github.com/syncthing/syncthing/lib/discover.(*Discoverer).sendLocalAnnouncements(0xc8200b8700)
        /Users/jb/src/github.com/syncthing/syncthing/lib/discover/discover.go:329 +0x38
created by github.com/syncthing/syncthing/lib/discover.(*Discoverer).StartLocal
        /Users/jb/src/github.com/syncthing/syncthing/lib/discover/discover.go:95 +0x263
```

It's fairly clear cut but a little bit annoying to fix cleanly. Since relaying is disabled, we have `var relaySvc *relay.Svc` in main which is nil, that we then pass to the discovery service. But the discovery service takes a `discovery.relayStatusProvider` interface. Since we're passing a *variable* that is nil, and not a nil *literal*, the other side gets a "typed nil" interface, so the check in there for `relayStatusProvide == nil` ends up being false even though the interface contains a nil pointer.

The cleanest way is probably

```
if relaySvc == nil {
	disc = discover.NewDiscoverer(myID, opts.ListenAddress, nil)
} else {
	disc = discover.NewDiscoverer(myID, opts.ListenAddress, relaySvc)
}
```

in main.go, but goddamn that looks like crap...

**Comment by AudriusButkevicius** [comment]
This is just plain stupid. Can we pass a pointer to an interface?

**Comment by calmh** [comment]
Technically yes, but not of the right type as the interface in discover is unexported. A third option would be to have `relay/Svc.ClientStatus()` actually work and return a nil map when called with a nil receiver.

**Comment by AudriusButkevicius** [comment]
That's the best option.
