### ISSUE TITLE
Problem deleting folders?

### ISSUE THREAD

**Issue by uriel-fanelli** [syncthing/syncthing#2247]
Hello,

I am experiencing a strange behaviour after I re/ordered one of the folder I share. 

I have a machine which I call "fileserver" which keeps a "backupped" folder and some clients (on laptops) which are moving around the world, which I call "roadwarrior". 

Now, I decided to put some order in a folder (on my "roadwarrior" machine) so I deleted some old folders  and created new folders, putting the files in some order. Pretty usual.

But.

The "roadwarrios" are then unable to update the folder. On the "roadwarriors" webconsole the "fileserver" device is blocked at "Syncing 100%" in blue, and on the "fileserver" logs I see the log below.

Seems the "fileserver" needs then to delete the folder to create the new structure, but the output seems the same of the command "rm" when is done on a non-empty folder.(see below).

Now, I guess the temporary solution will be to go on the "fileserver" and clean the folders, but being the "fileserver" a backup machine, it doesn't looks like a good practice to destroy the backup. 

Is it a bug or something I miss? 

<pre>
[TLV2V] 11:32:08 INFO: Puller (folder "default", dir "lalalala"): delete: remove /home/lalalala/lalalala/lalalala: directory not empty
[TLV2V] 11:32:08 INFO: Puller (folder "default", dir "lalala"): delete: remove /home/lalalala/lalalala/lalalala: directory not empty
[TLV2V] 11:32:08 INFO: Puller (folder "default", dir "lalalala"): delete: remove /home/lalalala/lalalala/lalalala: directory not empty
[TLV2V] 11:32:08 INFO: Puller (folder "default", dir "lalalala"): delete: remove /home/lalalala/lalalala/lalalala: directory not empty
[TLV2V] 11:32:08 INFO: Puller (folder "default", dir "lalalala"): delete: remove /home/lalalala/lalalala/lalalala: directory not empty
[TLV2V] 11:32:08 INFO: Puller (folder "default", dir "lalalala"): delete: remove /home/lalalala/lalalala/lalalala: directory not empty
[TLV2V] 11:32:08 INFO: Puller (folder "default", dir "lalalala"): delete: remove /home/lalalala/lalalala/lalalala: directory not empty
[TLV2V] 11:32:08 INFO: Puller (folder "default", dir "lalala"): delete: remove /home/lalalala/lalalala/lalalala: directory not empty
[TLV2V] 11:32:08 INFO: Puller (folder "default", dir "lalalala"): delete: remove /home/lalalala/lalalala/lalalala: directory not empty
[TLV2V] 11:32:08 INFO: Puller (folder "default", dir "lalala"): delete: remove /home/lalalala/lalalala/lalalala: directory not empty
[TLV2V] 11:32:08 INFO: Puller (folder "default", dir "lalalala"): delete: remove /home/lalalala/lalalala/lalalala: directory not empty
[TLV2V] 11:32:08 INFO: Folder "lalalala" isn't making progress. Pausing puller for 1m0s.
[TLV2V] 11:32:19 INFO: Puller: final: remove /home/lalalala/lalalala/Documents/lalalala/lalalala: directory not empty
[TLV2V] 11:32:19 INFO: Puller: final: remove /home/lalalala/lalalala/Documents/lalalala/lalalala: directory not empty
[TLV2V] 11:32:19 INFO: Puller: final: remove /home/lalalala/lalalala/Documents/lalalala/lalalala: directory not empty
[TLV2V] 11:32:19 INFO: Puller: final: remove /home/lalalala/lalalala/Documents/lalalala/lalalala: directory not empty
[TLV2V] 11:32:19 INFO: Puller: final: remove /home/lalalala/lalalala/Documents/lalalala/lalalala: directory not empty
[TLV2V] 11:32:19 INFO: Puller: final: remove /home/lalalala/lalalala/Documents/lalalala/lalalala: directory not empty
[TLV2V] 11:32:19 INFO: Puller: final: remove /home/lalalala/lalalala/Documents/lalalala/lalalala: directory not empty
</pre>

**Comment by OIBIS-Wikus** [comment]
From my experience, the non-master folder should never manually be modified. 

The setup that I'm running is that the clients (user PC's) have their folder set up as the master. If anything changes on the server folder (non master) I have a similar issue than yours. 

I think changing who the master is might solve your problem.

**Comment by uriel-fanelli** [comment]
I am not saying the "master" host is configured as master. I just call it "master" because it is the one which is only keeping a copy. But you are right, this is confusing. I am going to update the issue.

**Comment by AudriusButkevicius** [comment]
It's probably caused by ignored files (thumbs.db et al) in the directories which prevent then from being removed.

**Comment by uriel-fanelli** [comment]
Ok, I see. So, just a question: the ignore list on the "fileserver", if set, could prevent this files to be copied, or it just applies if i put the ignore list on "roadrunners"? Or both? If the roadrunner is the master, putting an ignore list in the "fileserver" will prevent those files to be saved?

**Comment by AudriusButkevicius** [comment]
Putting it on both sides will not fix this as windows generate them on both sides, regardless if you sync them or not. You probably have more chances if you do not ignore them, and as you rename a folder, you send the correct removal command to the other peer. There is work being done to add a file list which removes files if they are the only ones left preventig directory removal.

**Comment by uriel-fanelli** [comment]
The "fileserver" machine is a freebsd machine, so on one side there is nothing generating uncontroled files. The only side it happens are Apple machines (.DS_lala) and windows. Which are "roadrunners". So in this condition, if I put the filter in the freebsd machine, would it work?

**Comment by wweich** [comment]
You should set the ignores on the machines, where the files are created. Otherwise they add them to the index, the "fileserver" ignores them and will be out of sync.

**Comment by uriel-fanelli** [comment]
BTW, It worked. I put a ignore of .DS_store on the "fileserver" running on FreeBSD machine. The result is that the Apple laptop can re-create with no impact on the fileserver. It stopped

1. Annoying "out of sync" errore
2. The behavior of "unable to delete".

just for the record.
