### ISSUE TITLE
translated string not used

### ISSUE THREAD

**Issue by Eddy2909** [syncthing/syncthing#2248]
in "Edit Device" View:
"Enter comma separated "ip:port" addresses or "dynamic" to perform automatic discovery of the address."
![transl](https://cloud.githubusercontent.com/assets/12877411/9716540/faeef632-556a-11e5-9997-26340f4dc814.JPG)

**Comment by wweich** [comment]
The wording of this field comment has been improved a while ago, but not in the v0.11 branch.
Unfortunately the language files used in the v0.11 branch use the new wording as the "to be translated" text.

**Comment by calmh** [comment]
Ah, right. Divergence between v0.11 and v0.12 here. Sorry. We'll be back in business soon enough with the v0.12 release.
