### ISSUE TITLE
Useless files in the freebsd archive

### ISSUE THREAD

**Issue by moviuro** [syncthing/syncthing#2249]
Hi all!

Nothing critical, no need to panic :wink: 

Here is the content of the [freebsd archive](https://github.com/syncthing/syncthing/releases/download/v0.11.24/syncthing-freebsd-amd64-v0.11.24.tar.gz):
```
 % tar xvf syncthing-freebsd-amd64-v0.11.24.tar.gz -C ~/sync
x syncthing-freebsd-amd64-v0.11.24/
x syncthing-freebsd-amd64-v0.11.24/README.txt
x syncthing-freebsd-amd64-v0.11.24/LICENSE.txt
x syncthing-freebsd-amd64-v0.11.24/AUTHORS.txt
x syncthing-freebsd-amd64-v0.11.24/syncthing
x syncthing-freebsd-amd64-v0.11.24/syncthing.md5
x syncthing-freebsd-amd64-v0.11.24/etc/
x syncthing-freebsd-amd64-v0.11.24/etc/README.md
x syncthing-freebsd-amd64-v0.11.24/etc/linux-runit/
x syncthing-freebsd-amd64-v0.11.24/etc/linux-runit/README.md
x syncthing-freebsd-amd64-v0.11.24/etc/linux-runit/log/
x syncthing-freebsd-amd64-v0.11.24/etc/linux-runit/log/run
x syncthing-freebsd-amd64-v0.11.24/etc/linux-runit/run
x syncthing-freebsd-amd64-v0.11.24/etc/linux-systemd/
x syncthing-freebsd-amd64-v0.11.24/etc/linux-systemd/README.md
x syncthing-freebsd-amd64-v0.11.24/etc/linux-systemd/system/
x syncthing-freebsd-amd64-v0.11.24/etc/linux-systemd/system/syncthing@.service
x syncthing-freebsd-amd64-v0.11.24/etc/linux-systemd/user/
x syncthing-freebsd-amd64-v0.11.24/etc/linux-systemd/user/syncthing.service
x syncthing-freebsd-amd64-v0.11.24/etc/macosx-launchd/
x syncthing-freebsd-amd64-v0.11.24/etc/macosx-launchd/README.md
x syncthing-freebsd-amd64-v0.11.24/etc/macosx-launchd/syncthing.plist
x syncthing-freebsd-amd64-v0.11.24/etc/solaris-smf/
x syncthing-freebsd-amd64-v0.11.24/etc/solaris-smf/README.md
x syncthing-freebsd-amd64-v0.11.24/etc/solaris-smf/syncthing.xml
x syncthing-freebsd-amd64-v0.11.24/etc/windows/
x syncthing-freebsd-amd64-v0.11.24/etc/windows/ReadMe.txt
x syncthing-freebsd-amd64-v0.11.24/etc/windows/SyncThingSetup.nsi
x syncthing-freebsd-amd64-v0.11.24/etc/windows/syncthingservice.xml
x syncthing-freebsd-amd64-v0.11.24/FAQ.pdf
x syncthing-freebsd-amd64-v0.11.24/Getting-Started.pdf
x syncthing-freebsd-amd64-v0.11.24/syncthing.sig
```
I'm sure the entire `etc` folder is useless in a FreeBSD archive ;)

**Comment by calmh** [comment]
So it is, but it's included with every OS package. It could be useful for FreeBSD if someone contributed something to it. :)

**Comment by moviuro** [comment]
@calmh OK, I'll look into it :smile:

**Comment by rumpelsepp** [comment]
@moviuro: Maybe this could be useful for you as well: https://svnweb.freebsd.org/ports/head/net/syncthing/files/syncthing.in?view=markup

**Comment by moviuro** [comment]
@rumpelsepp yep, I contact @swills on IRC, but no answer so far. Perhaps mentionning him here would trigger any kind of answer? :wink:

**Comment by rumpelsepp** [comment]
I have written a pm to him using the forum as well; no answer so far. :/

**Comment by swills** [comment]
Hi, just saw this, what can I do to be helpful here?

**Comment by rumpelsepp** [comment]
There is two things you could help:

* Contribute the freebsd start scripts upstream, so they can be reused by other BSDs (does this make sense in this case?)
* I asked you in my message if it is possible to modify the start script to use some kind of logging. But that may be offtopic here....

**Comment by swills** [comment]
What do you mean by contribute it upstream? Like fork and submit a pull request? I guess I could, though if they wanted it they could just grab it, it's public and BSD licensed, just like the rest of FreeBSD ports. I've no idea if it will work on other BSDs. I'm optimistic it might work on NetBSD, since I believe the rc.subr that is used in FreeBSD came from NetBSD at some point, though has been changed a bit since. As for OpenBSD, I'm less optimistic.

On the topic of logging, that could be added, I'll try to get to that.

**Comment by rumpelsepp** [comment]
> What do you mean by contribute it upstream?

On linux it is quite common to submit these scripts (systemd services...) upstream, so that distributions could just pick them. Otherwise everybody has to reinvent the weel again and again. Unfortunately I have no idea what is "best practice" in the BSD* world. :)
