### ISSUE TITLE
Removing large shared folder causes very high RAM usage

### ISSUE THREAD

**Issue by ProactiveServices** [syncthing/syncthing#2250]
I removed a shared folder of 509GB in 350 items. It took 15 minutes for Syncthing to finish "Cleaning data for dropped folder", during which it peaked at 5.2GB private bytes, and spent most of the time above 4GB. This strikes me as being a bit excessive!

**Comment by calmh** [comment]
Yeah, it does sound a bit excessive. You mean the folder contained 350 files, a bit over a gig each (for reproduction)?

**Comment by simplypeachy** [comment]
264 files, 86 folders. One folder had the bulk of the data with 481GB across 43 files, with file sizes ranging from ~1GB to ~48GB.

**Comment by AudriusButkevicius** [comment]
Could this be the block map.

**Comment by calmh** [comment]
Could be, yes.

**Comment by uok** [comment]
reminds me of #1938
