### ISSUE TITLE
Android (CM12.1): Infinite loop while starting application, which is moved to the sd card

### ISSUE THREAD

**Issue by ZdenekBrichacek** [syncthing/syncthing#2253]
When the application is installed, and configured (added some folders), in the internal memory, everything is working correctly (android logcat: http://blog.brichacek.net/files/reports/bugs/syncthing/20150909-internal_memory.txt). But after move application to the sd card, the application goes to infinite loop (picture: http://blog.brichacek.net/files/reports/bugs/syncthing/20150909-syncthing-android-loading.png, logcat: http://blog.brichacek.net/files/reports/bugs/syncthing/20150909-sdcard.txt - including errors from start of the application).

Android version: CyanogenMod 12.1 (Android 5.1.1 http://blog.brichacek.net/files/reports/bugs/syncthing/20150909-android-system_info.png, http://blog.brichacek.net/files/reports/bugs/syncthing/20150909-syncthing-android-on_sdcard.png).
Syncthing: v0.11.22 "Aluminium Ant" (go1.4.2 linux-arm android).

Reboot does not solve this problem, only move back to internal memory.
I didn't try to reinstall syncthing on the phone (in case of upgrade via Google Play, the application is already installed to internal memory).

I'm using own global announce servers.

**Comment by wweich** [comment]
You should open this ticket in the [syncthing-android repo](https://github.com/syncthing/syncthing-android).

**Comment by ZdenekBrichacek** [comment]
Yes, I understand.

I see that you have created the link.

Closing ticket...
