### ISSUE TITLE
UI shows folders to sync as "Del"

### ISSUE THREAD

**Issue by L-P** [syncthing/syncthing#2254]
![screenshot](https://cloud.githubusercontent.com/assets/947312/9795449/0cc284ae-57f1-11e5-8c51-7479b9e05762.png)

```
$ syncthing --version
syncthing v0.11.24 "Aluminium Ant" (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-09-06 06:47:52 UTC
```

Same version running on both sides.

The folder shown as to be deleted is currently being downloaded and is not supposed to be deleted.  
It's only a visual issue but a scary one.

**Comment by AudriusButkevicius** [comment]
Did you perhaps rename it?

**Comment by L-P** [comment]
No. This is an initial import with data untouched for years.

The same thing happens when data is added after the folders are in sync.

**Comment by AudriusButkevicius** [comment]
I cannot repro it.
Once I dump in a large directory, the directory creation happens immediately, and only files are left to sync.

**Comment by L-P** [comment]
I'll try to get a repro.

It happened when the original folder was still being scanned by the sender, this may be relevant.
