### ISSUE TITLE
Insufficient Disk Space error when only metadata needs to be synced

### ISSUE THREAD

**Issue by BlakeIsBlake** [syncthing/syncthing#2255]
OS: Windows Server 2012 R2
Version: v0.11.24 "Aluminium Ant"

I had an Amazon EC2 instance with a ~36.6 GB folder residing within it. I had syncthing running as master-slave from one instance to another. A configuration issue on the slave caused me to need to clone the master again to replace the current slave. In doing so, the ~36.6 GB folder would be retained and would be exactly the same on both devices. I also deleted the Syncthing folder in LocalAppData on the new slave instance to guarantee they wouldn't have the same IDs.

**What happened**

The disk space on the slave instance only had ~25 GB left. Syncthing on the slave instance claimed that the entire folder was out of sync, which seems plausible because at this point both instances had been running and there might be file metadata inconsistencies. However, the slave instance refused to sync the metadata because I didn't have an *extra* ~36.6 GB left, even though clearly the entire amount, twice, didn't need to be synced. 

So the issue is that Syncthing refused to operate on the slave instance because I didn't have enough space for the second copy of a directory that already existed.

Of course, deleting the folder on the slave instance and resyncing worked.

I took this screenshot after another restart, so I don't have the Insufficient Disk Space errors showing here. ![Error](http://i.imgur.com/FsL9RTz.png)

**Comment by AudriusButkevicius** [comment]
You can also set the minimum space requirement to 0 percent which should kill the check.

**Comment by simplypeachy** [comment]
Just tested this using the same version and confirm:

* Take a set of files of total size *x* bytes on Device A.
* Copy these to Device B (outside of Syncthing) on a volume with <2*x* bytes free space.
* On Device A, add the file set's parent folder to a new shared folder, set to Master.
* Share with Device B, set to the parent folder on Device B, not set to Master.

Once Device A and B have finished scanning, Device B will warn that it has insufficient space to pull the files, despite both shared folders being identical.

**Comment by calmh** [comment]
Yeah, that's annoying. The "set to zero to disable" doesn't actually work in 0.11.24 I think, there's a fix in 0.11.25 coming...

**Comment by calmh** [comment]
We should probably try to not increment `pullFileSize` for metadata only changes... Maybe that means looking up the existing block list earlier (mobile; don't have code in front of me).

**Comment by calmh** [comment]
This is fixed, we no longer check for pullFileSize
