### ISSUE TITLE
Three way network - two nodes failing to connect

### ISSUE THREAD

**Issue by kabanus** [syncthing/syncthing#2256]
Hi everyone,

The run down: 
2 nodes in my network (Win 7 Laptop and Linux PC) aren't connecting, but both are connecting two a third (Win10 PC). All computers are on different networks. One of these nodes is a static IP (Linux). Pinging the static IP from the Laptop works (timeout). I couldn't find anything in the logs that isn't standard.

Both Win10 PC and Win 7 Laptop are behind routers, the Win10 with activated UPNP, the Win 7 without - but they both connect fine dynamically.

Does it make sense for the laptop and Linux PC to not be able to connect?
What tracer should I activate to send proper logs? 

Thanks,
Uria

**Comment by AudriusButkevicius** [comment]
What do you mean by works (timeout)?

**Comment by kabanus** [comment]
I mean I ping the IP, and all packets are sent, but none are received. I think this is standard, no? The working PC (that connects) behaves the same.

**Comment by wweich** [comment]
A working ping will have alle packets received which are sent resulting in 0% packet loss.

You say both windows PCs are behind routers. What about the Linux PC? Router, firewall?
As the ping requests seem to be blocked, there should be one (at least a software firewall).

As I see it, the Win10 PC is the only one with working UPnP/port forward/open port in firewall, so it is the only one to which the others can connect.
Neither the Win7, nor the Linux PC have a working port mapping/open port so they cannot connect to each other.

**Comment by kabanus** [comment]
Yea the Linux PC is definitely behind a router, firewall. The local IP (inet addr from /sbin/ifconfig) matches the IP returned from whatmyip - doesn't this mean it's "truly" static?

I was thinking a static IP would be just as good as UPNP (or forwarded port). Anyway, I restarted with sttrace=discovery and the laptop did not connect anymore - even when turning it off I had to restart the laptop to have it connect to my home PC again.

1. @wweich Knowing the Linux PC is static, does this change your answer (requiring mapping/open)?
2. I'll try discovery again, this is weird.

**Comment by kabanus** [comment]
Worked now, this is the current log (still not connecting to Technion-Linux):

[monitor] 2015/09/10 22:58:15.181638 monitor.go:63: INFO: Log output saved to file "C:\Users\uperetz\AppData\Local\Syncthing\syncthing.log"
[monitor] 2015/09/10 22:58:15.218640 monitor.go:94: INFO: Starting syncthing
[FJRIY] 2015/09/10 22:58:15.786672 main.go:475: INFO: syncthing v0.11.24 "Aluminium Ant" (go1.4.2 windows-amd64 default) unknown-user@syncthing-builder 2015-09-
06 06:47:52 UTC
[FJRIY] 2015/09/10 22:58:15.818674 main.go:476: INFO: My ID: FJRIY5V-U3EVF32-RLEJRTE-SNZLUS4-ZRVW5JP-LABR4MW-F7NR5U7-TQNAJAE
[FJRIY] 2015/09/10 22:58:15.821674 main.go:772: INFO: Database block cache capacity 31133 KiB
[FJRIY] 2015/09/10 22:58:15.984684 model.go:194: OK: Ready to synchronize programs (read-write)
[FJRIY] 2015/09/10 22:58:16.024686 model.go:194: OK: Ready to synchronize workspace (read-write)
[FJRIY] 2015/09/10 22:58:16.196696 model.go:194: OK: Ready to synchronize docs (read-write)
[FJRIY] 2015/09/10 22:58:16.224698 model.go:194: OK: Ready to synchronize favorites (read-write)
[FJRIY] 2015/09/10 22:58:16.224698 main.go:827: INFO: Starting web GUI on http://127.0.0.1:8384/
[FJRIY] 2015/09/10 22:58:16.378706 rwfolder.go:331: INFO: Completed initial scan (rw) of folder favorites
[FJRIY] 2015/09/10 22:58:16.658722 rwfolder.go:331: INFO: Completed initial scan (rw) of folder workspace
[FJRIY] 2015/09/10 22:58:16.928738 main.go:904: INFO: Starting local discovery announcements
[FJRIY] 2015/09/10 22:58:16.938738 main.go:909: INFO: Starting global discovery announcements
[FJRIY] 2015/09/10 22:58:17.007742 client_udp.go:106: DEBUG: discover udp6://announce-v6.syncthing.net:22026: broadcast resolve: GetAddrInfoW: No such host is k
nown.; trying again in 1m0s
[FJRIY] 2015/09/10 22:58:17.026743 main.go:689: INFO: Device DQPPHVO-XZN3AKI-GN4KP2G-3B5SJJG-DEZC653-BSVC3WW-77OUIWN-MNP4IQK is "Technion" at [132.68.75.40:2200
0]
[FJRIY] 2015/09/10 22:58:17.026743 main.go:689: INFO: Device FJRIY5V-U3EVF32-RLEJRTE-SNZLUS4-ZRVW5JP-LABR4MW-F7NR5U7-TQNAJAE is "UPERETZ-MOBL" at [dynamic]
[FJRIY] 2015/09/10 22:58:17.026743 main.go:689: INFO: Device GQNNDWD-XXRXFIN-P67H3IU-KE7GIB2-LIVZC22-5R5652S-5SGGUXQ-2P7W5QV is "home" at [192.168.2.101:22000 d
ynamic]
[FJRIY] 2015/09/10 22:58:17.026743 main.go:689: INFO: Device UTVQVDK-HSLULZR-RV5IZGH-6FEYRUS-HMAVOHE-L5M2WH5-NCTWNOX-3DRMJQE is "Technion-Linux" at [132.68.75.4
0:22000]
[FJRIY] 2015/09/10 22:58:17.029744 gui.go:221: INFO: API listening on 127.0.0.1:8384
[FJRIY] 2015/09/10 22:58:17.029744 rwfolder.go:331: INFO: Completed initial scan (rw) of folder docs
[FJRIY] 2015/09/10 22:58:17.034744 client_udp.go:126: DEBUG: discover udp4://announce.syncthing.net:22026: broadcast: Sending self announcement to 194.126.249.5
:22026
[FJRIY] 2015/09/10 22:58:17.105748 rwfolder.go:331: INFO: Completed initial scan (rw) of folder programs
[FJRIY] 2015/09/10 22:58:18.122806 client_udp.go:223: DEBUG: discover udp4://announce.syncthing.net:22026: Lookup(FJRIY5V-U3EVF32-RLEJRTE-SNZLUS4-ZRVW5JP-LABR4M
W-F7NR5U7-TQNAJAE) result: [109.66.178.113:22000]
[FJRIY] 2015/09/10 22:58:18.122806 client_udp.go:142: DEBUG: discover udp4://announce.syncthing.net:22026: broadcast: Self-lookup returned: [109.66.178.113:2200
0]
[FJRIY] 2015/09/10 22:58:27.044316 upnpsvc.go:46: INFO: No UPnP device detected
[FJRIY] 2015/09/10 22:59:17.008174 client_udp.go:106: DEBUG: discover udp6://announce-v6.syncthing.net:22026: broadcast resolve: GetAddrInfoW: No such host is k
nown.; trying again in 1m0s
[FJRIY] 2015/09/10 22:59:42.059607 client_udp.go:164: DEBUG: discover udp6://announce-v6.syncthing.net:22026: Lookup(GQNNDWD-XXRXFIN-P67H3IU-KE7GIB2-LIVZC22-5R5
652S-5SGGUXQ-2P7W5QV): GetAddrInfoW: No such host is known.
[FJRIY] 2015/09/10 22:59:42.146612 client_udp.go:223: DEBUG: discover udp4://announce.syncthing.net:22026: Lookup(GQNNDWD-XXRXFIN-P67H3IU-KE7GIB2-LIVZC22-5R5652
S-5SGGUXQ-2P7W5QV) result: [46.121.146.178:54739]
[FJRIY] 2015/09/10 23:00:03.443830 connections.go:176: INFO: Established secure connection to GQNNDWD-XXRXFIN-P67H3IU-KE7GIB2-LIVZC22-5R5652S-5SGGUXQ-2P7W5QV at
 10.0.0.14:49840-46.121.146.178:54739
[FJRIY] 2015/09/10 23:00:03.455831 model.go:597: INFO: Device GQNNDWD-XXRXFIN-P67H3IU-KE7GIB2-LIVZC22-5R5652S-5SGGUXQ-2P7W5QV client is "syncthing v0.11.24"
[FJRIY] 2015/09/10 23:00:03.455831 model.go:602: INFO: Device GQNNDWD-XXRXFIN-P67H3IU-KE7GIB2-LIVZC22-5R5652S-5SGGUXQ-2P7W5QV name is "kabanus-home"
[FJRIY] 2015/09/10 23:00:17.009606 client_udp.go:106: DEBUG: discover udp6://announce-v6.syncthing.net:22026: broadcast resolve: GetAddrInfoW: No such host is k
nown.; trying again in 1m0s

**Comment by wweich** [comment]
My answer is still valid. You need to open port 22000 (or the one you changed it to in the syncthing settings) in the firewall / router, for syncthing to be reachable.

Static IP does not mean that every port is exposed to the internet.
The only thing that changes for syncthing, is that you can enter the static IP of the Linux PC in the device settings of the other nodes (which you are doing, as I see in your log), instead of "dynamic" and the Linux PC does not need global discovery if you do so.

According to your log, the IPv6 discovery does not work. I can't really tell if it's because your machine can't resolve the upd6 host or if the global recovery server doesn't know the node your requesting.

You have two nodes (Technion and Technion-Linux) which seem to be the same: same IP address and port. That can't be right.

**Comment by AudriusButkevicius** [comment]
He has two nodes with the same IP because they are behind aa NAT and there is no UPnP, hence he should change protocol listen port on one of them and set up manual port forwarding.

**Comment by kabanus** [comment]
One is windows and one Linux, on dual boot - it is :) but I tried removing just in case the windows one to no avail - not to PCs on the same NAT.

from @wweich I understand that probably port 22000 is not open through the university routers, and since the laptop isn't forwarded as well and has no upnp, these two have no chance (whereas the Technion machine can find the Win10 one with upnp and connect to it).

If this is your answer I'll close this as this is a non-issue.

**Comment by AudriusButkevicius** [comment]
Yeah, you need to be exposed to the internet on one of the sides for it to work. 0.12 will bring relays which fix that.

**Comment by wweich** [comment]
If you have no possibility to open the needed ports for the two machines, they will not be able to conect to each other until v0.12 arrives.
The version will have the option to use relay servers, so as long as outgoing connections aren't restricted to specific ports, everyone of your devices should then be able to connect to each other.

**Comment by kabanus** [comment]
Thanks for all your help guys. I guess my the main thing I learned is just because a port is "LISTENING", doesn't mean it's open to the world.
