### ISSUE TITLE
UPnP not retried if unable to detect UPnP device when Syncthing started on boot.

### ISSUE THREAD

**Issue by bluewavenet** [syncthing/syncthing#2263]
I have a setup with multiple instances started by systemctl for users on Linux laptops.
Using Network Manager in Gnome desktop the network is only started once the user logs in so they can scan for wifi etc. 
UPnP fails on boot as the network is not running yet so global discovery fails.
Can Syncthing be made to retry periodically to get a UPnP connection?

**Comment by AudriusButkevicius** [comment]
It is retried, after 30 minutes. You can adjust that in the advanced config.

**Comment by AudriusButkevicius** [comment]
It's UPnPRenewalM setting, but this will also effect how often we ask the router to renew the lease.

**Comment by bluewavenet** [comment]
Excellent thanks will try that. Interestingly upnpRenewalMinutes was set to 30 and upnpLeaseMinutes is set to 60 by default. Do you know how these interact?

Is it possible to set these parameters on the command line? I have 3 users on 4 machines, so 12 configs to edit. With a larger rollout it will grow significantly. Always looking for a useful shortcut ;)

**Comment by AudriusButkevicius** [comment]
RenewalMinutes tells how often we contact the router
LeaseMinutes tells how long of a lease we ask the router for
If you set it tlthe first to something stupid like a minute, it will spam your network like crazy doing broadcasts every minute, so perhaps starting sycthing after login, or network after boot is a better answer.

As for editing, syncthing-cli or python which posts the config with the new values or sed

**Comment by bluewavenet** [comment]
Well I did set renewal to 1 min ;)
Works fine, taking a couple of minutes to establish the link between 2 test devices. 
I'm monitoring the lan with wireshark running on one of the devices and no broadcast storms to report so far, just the normal background stuff.  So one minute it is for now! - 
As long as UPnP comes up on all the instances of one of the devices, the others establish a connection ok as expected.
As these are laptops the  (non-tech) users need to be able to scan for WiFi, so Network Manager is essential and startup of the instances for all users on login of just one of them is complicated although possible. This way is much simpler.
