### ISSUE TITLE
Advanced config can't deal with slices

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#2267]

**Comment by calmh** [comment]
:+1: I was thinking today we should deal with this. It (the entire modal) is also rather sluggish to scroll and interact with on at least my computer.

**Comment by AudriusButkevicius** [comment]
What about the jumbo checkboxes:
http://snag.gy/6lgJP.jpg

**Comment by calmh** [comment]
Haha, that's certainly not how it looks for me. :)

<img width="920" alt="screen shot 2015-09-12 at 13 49 13" src="https://cloud.githubusercontent.com/assets/125426/9831379/160df79a-5955-11e5-86b8-cadb0af55fce.png">

But it seems this dialog may need some love.
