### ISSUE TITLE
ability to have multiple users sharing a folder also share bandwidth

### ISSUE THREAD

**Issue by marrie** [syncthing/syncthing#2268]
Not like bit torrent sync, but the user could grab from everyone until everyone including the master are synced.  For example I have a folder and I'm the master. Joe said he wants the folder so I share it with him. He then starts to upload from me. Marry wants to have access to this master so Joe and I download to her what we can and so on. I think this would make it easier on those of us with limited connections. And as each of us will have different scan intervals it might make it easier on all of our computers. Just a thought, and a minor suggestion. Of corse this could be a toggle for those that just want to grab the folder and not share their bandwidth with anyone else. If the introducer function already does this, please let me know as I'm still learning the program, and am learning it as fast as humanly possible.

Using version 0.11.24, Mac OS X (64 bit)

**Comment by AudriusButkevicius** [comment]
If you Marry and Joe share the same folder, all peers are used to provide content to some new node Bob, regardless if you are master or not.

**Comment by marrie** [comment]
Ah. That works. Thanks much.
