### ISSUE TITLE
Transport of 4.3 Millions of files very slow on restart the Client

### ISSUE THREAD

**Issue by Getron** [syncthing/syncthing#2271]
I transporting from and to my NAS Server (just on one machine) aproximatly 4.3 millions of files, and aproximately 50 folders, and 20 devices.

The problem is (not frustrated, but...) if i restart the client on my Server, restarting duration is about +-3 minutes. Syncthing need to rescan all the folders, but, maybe this is not neccesarly.

I'm not sure, if we can do somthing about this, to have, for example, an index somwhere, a file on config, with informations of the last state, to not rescan the entire folders and devices, to speed up the client on restarting, if someone, like me, transport a such big amount of files.

Don't known, if this is possible, but, i think, BTSync has somthing like this, it was very quick on restarting, not mather what amount of files i have transported.

**Comment by AudriusButkevicius** [comment]
it's just how it's designed to work. We always rescan because we assume we might not have been running for a while, but in case us ourselves initiating the restart, perhaps you are right, we could skip that. Summon @calmh

**Comment by Getron** [comment]
Yes, just in case of "Restarting" i have meant.

On "Starting" should rescaning, it is ok.

The problem is, if i share or add devices, or steps, where the client must restarting, the problem is too long waiting.

It would be great, if we can use the "last state" of client, just on case of "Restarting". Like this, i think the restarting speed it will be great, no matter how many files, folders or devices are there for syncing.

**Comment by AudriusButkevicius** [comment]
You don't need to restart to add a device or a share anymore.

**Comment by Getron** [comment]
Yes, but not overall, for example, if i made any change on sync folders, for example, add to an device, or detach it from a device, the client must restart. Or, in options, almost on all changing the client must restarting.

Therefore, it will be great, if the restarting process should not rescan all the folders, it is just restarting, on the same seconds of time.

**Comment by Getron** [comment]
One more problem is, every time i access the Syncthing client on my NAS Server, local LAN, it rescan all the database, and this go 2-3 minutes to, until finished.

If i close the browser, and access again the client, it rescan again.

I think, should be an index somwhere on config or where the client is installed, with all the infos, about scaned data, and should just this one file be proceded on access the client.

Or maybe another way, but, it take too long to access the client, every time i access, or re-access it (close the browser- and re-open it, and go to client adress).

**Comment by AudriusButkevicius** [comment]
It does not rescan when you access the UI, I am not sure where you are coming up with this information from.

The only thing it does when you access a web ui when you haven't accessed it for a while is recalculate the completion percentages relative to the rest of the cluster.

Yes, we could store it in a file (we store it in memory) but that means we'd have to recalculate it constantly to keep it up to date, which would consume extra resources throughout the process, hence why we stop doing it when no clients are asking for it, and then start doing it again when a new client comes back after a while.

What sort of spec NAS is it that it takes 3 minutes? If this is one of these home NAS'es with calculator-like CPU, I am not surprised.

**Comment by Getron** [comment]
My FreeNAS Server build:

- FreeNAS 9.3 Stable (boot from a 16GB SanDisk USB 3.0 Stick)
- 30TB WD Red HDD (10 x 3TB HDDs) on RAIDZ2
- 256GB Samsung 850 Pro SSD (for L2arc cache)
- Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz (3400.07-MHz K8-class CPU)
- 32GB Corsair Vengeance Quad Channel DDR3-18 PC3-14900 1866MHz 10-11-10-30 RAM
- Gigabyte GA-Z87X-UD5H Mainboard
- 850W Corsair Power Supply.

I think, this is not an weak on machine. And it works perfectly, all the stuff on it. Extremly quick machine, and quick Server Build. I'm very happy with it.

I'm not compared the Syncthing with BTSync, you understand me wrong. I just give an example. And, maybe from this example, we can build somthing much better. It is not going to comparison. Sorry.

Maybe, i put an video, and you can see, what is does. I have tryed right now, just to close the tab on chrome, and re-open again the client adress, all the shared folders have status "unknown", and after this, it starts to show one after other, what the realy status is. But, on ca. 40 shared folders, it take to long, every time.

If you want, i will try to make an video, to show you, what is going on.

**Comment by AudriusButkevicius** [comment]
Yeah it is the summary service, not scanning.
I don't know of ways we could improve this, @calmh ?
Tracking numbers as indexes come in? But it's effectively what we are doing now.

**Comment by Getron** [comment]
I don't known, if this would help, but, the logic is to not scan(or check, whatever you call it, it looks like it scan somthing, or check somthing) the summary service on accessing the client from the browser, or from the same IP of browser, or machine.

- maybe, we can skip this summary service check (or scan)?
or
- maybe, if it is necessarly to do this, doing summary service the first time accessing the client, and write it somewhere on a file. The other browser re-opening of client from the same machine or the same browser should just read this file, and summary service is there. Maybe, Syncthing should write from time to time this summary service on this file, and so, we have the newest infos about what is going on on this file, updated.

I don't known the point of this summary service, but, this is my idea, how maybe we can improve this. I believe, the users would transport more and more files and folders, and this would be a great improvment for the future of Syncthing. To be fast, faster, the fastest Sync client out there! Yeah.

**Comment by AudriusButkevicius** [comment]
I suggest you understand what it does and how it works before proposing suggestions. It already shares the recalculations among different users, so its only recalculated the first time, and then every 2 seconds after that. Are you willing to give up completion percentages for the sake of not doing this?

**Comment by Getron** [comment]
I can't understand somthing i don't have programming myself, without someone tell me what it does, who known, what it does.

Now, i understand, but, the problem is, i can't make anything, until this process is done - that's the problem, i must wait the process everytime i re-access the client.

I don't suggest to not doing that, it should does, but, should not block the user to not be able to do anything until is done. That's the point.

i have now +- 40 shares, but, can you imagine what happen, if someday i, or someone have +-400 or more? I known, you would say, this is insane, no one needs such amount of shared folders, but, i do an Live Backup of files of my customers, and i will have more and more shares, from time to time. I wonder, if i stay the only one with such Backup hosting. I known, there are a bunch of other softwares to do this, but, no one is on live, like Syncthing do.

Therefore the idea, maybe just adding somthing, to do this on background on accessing the client, and not to must waiting, until the full process of all shares ends. It should let the user be able working with client. It would not be a problem, if this would happend just one time i access the client over my browser, but, it does every, and every time, again, and i must every time again, for entire process to be done.

Hope you understand me now, and, maybe, have an idea for improvement for this?

**Comment by AudriusButkevicius** [comment]
Your issue is clear since the first post, and it's not closed, I don't understand why are we even having a discussion here?

I doubt this will be addressed any time soon, just because it's an issue of scale, and given 9%% of the users have 2-3 folders with 2-3 nodes, it's not one of high priority.
Secondly it's a hard issue to reproduce, as it requires the environment you have, which requires effort to replicate, making an even less appealing issue to solve.

**Comment by Getron** [comment]
No, sorry, i don't make a discussion, i just give an example of my problem. I'm a person, i can't describe my problem in a few words, i must explain it. Hope, you are not angry with me, hehe.

Ok, that's great to hear, that this is a valid post. Thank you. It is ok, it must not be resolved now, but, in a near future, i will apreciate to have it solved somehow. Thank you devs.

**Comment by Getron** [comment]
Hi

Just won't to thanks to devs that in the new 0.12.x Version of Syncthing, the refreshing times are improved, and on refreshing pages, it doesn't take long time at all. Wonderfull now.

Thanks to all. Wonderfull release. I'm very happy now.
