### ISSUE TITLE
panic: leveldb/table: corruption on data-block

### ISSUE THREAD

**Issue by my95z34** [syncthing/syncthing#2272]
So, I just noticed that ST wasn't running on my laptop, so I manually attempted to launch it and I received this output 

[monitor] 22:46:11 INFO: Starting syncthing
[R7OGU] 22:46:11 INFO: syncthing v0.11.24 "Aluminium Ant" (go1.4.2 linux-amd64 default) unknown-user@syncthing-builder 2015-09-06 06:47:52 UTC
[R7OGU] 22:46:11 INFO: My ID: *omitted*
[R7OGU] 22:46:11 INFO: Database block cache capacity 29189 KiB
[R7OGU] 22:46:12 OK: Ready to synchronize PC-Downloads (read-write)
[R7OGU] 22:46:12 OK: Ready to synchronize Phone-Camera (read-write)
panic: leveldb/table: corruption on data-block (pos=801737): checksum mismatch, want=0x37b04345 got=0x2ad93a2b [file=090101.ldb]
[monitor] 22:46:12 WARNING: Panic detected, writing to "/home/andrew/.config/syncthing/panic-20150913-224612.log"
[monitor] 22:46:12 WARNING: Please check for existing issues with similar panic message at https://github.com/syncthing/syncthing/issues/
[monitor] 22:46:12 WARNING: If no issue with similar panic message exists, please create a new issue with the panic log attached
[monitor] 22:46:12 INFO: Syncthing exited: exit status 2

So, here's the output of that log file: http://pastebin.com/ydNYkfMr

I have no idea what happened, as I haven't changed anything in quite some time.  It's been running fine for months now.

Any input would be greatly appreciated.

**Comment by AudriusButkevicius** [comment]
Please check existing closed issues.

**Comment by my95z34** [comment]
Totally didn't think to look in closed issues, sorry about that.  But, oddly enough, it seems to have fixed itself....  o_O

**Comment by AudriusButkevicius** [comment]
Check dmsg, your disks or ram slare going bad.
