### ISSUE TITLE
Help on top, and documentations on bottom, allmost the same thing

### ISSUE THREAD

**Issue by Getron** [syncthing/syncthing#2274]
I sugest to put the Help on the footer, along the documentations, or, maybe delete one of them, it is almost the samething, just an link to other starting place on http://docs.syncthing.net/

I sugest to, to put the "Show ID" where now the help is, out from "actions", it is one thing i need allmost on every device adding.
Like now, user should click on actions, and show ID, that's 2 clicks. After, it will be one click, if we put it out from actions menu, on the header bar. We need to shorting clicks, and speed up the working on our Syncthing.

And maybe, on settings, to add an link to advanced settings. Settings should be linked togetter.

**Comment by AudriusButkevicius** [comment]
Ideallt you should back this up with a pull request if you want it changed.

**Comment by Getron** [comment]
Ok, i need to learn how this works, pull request, and changes.

**Comment by calmh** [comment]
It's almost the same thing, but not quite. The "Help" link is a quick help for how the GUI works, and having it at very close to the meny makes it somewhat accessible or the first time user. We have other places with help links to specific topics. The documentation link at the bottom doesn't stand out, but should be there for completeness.

**Comment by Getron** [comment]
What for IDE software i need on linux for GO Language?

I have Kate, Geany, Atom, Sublime Text 3, Umbrello, Glade, QT Creator, QT4 Designer, Netbeans, Eclipse for PHP Developers, Aptana Studio, but, i'm not sure, if this helps for GO programming...?

or maybe should i try with GOClipse (Eclipse and Go Plugin) https://github.com/GoClipse/goclipse ?

I known, this is not the right place to ask such questions, but, i appreciate it, if you would give me an indication to start, then, i would give my effort to make Syncthing more, and more better. Thanks in advice.

**Comment by jpjp** [comment]
@Getron At it's simplest you find the file on github, edit it, then submit it. You don't need to install anything.

For example, say you wanted to edit the README file, just go to https://github.com/syncthing/syncthing/blob/master/README.md, click the edit pencil button and the rest should be easy.

**Comment by Getron** [comment]
@jpjp hmm, yes, that's simple, i known this, but, readme is the simple one.

If i need other stuff, for example, to see how the files interact each other, if i made changes, i need somthing like IDE, to be able to start the project on my machine, and test it, change it, and so on. What if i need to change more than one file, and will see the changes, how it works?

**Comment by Getron** [comment]
@marrie Yeah, it is a good idea to, and maybe, more better, like in Tox Messenger, here in github, the new Tox has a trick to copy very long ID, you don't need at all to select the full code, and then menu, then Copy - it is just done like this: only klicking on the ID number, or the ID QR Code (yes, the Tox has this to), it copy automaticaly. And for user to known this, it is the text after the Tox ID: 

Your Tox ID (click to copy)

The same would be great here in Syncthing, just adding the text after the Device Name (click to copy) - Done.

I'm having to trouble to put this on the source code, but, i decided to learn, how to implement such things here on github. I work on PHP Code, web pages, but, no here on github, and no GO language yet. But, i want to learn it.

**Comment by calmh** [comment]
That would be neat, yes, and has been mentioned before. Luckily you don't even need to know any Go to hack the GUI, being familiar with web programming is all it takes. The GUI is the web app here: https://github.com/syncthing/syncthing/tree/master/gui

**Comment by Getron** [comment]
@calmh Yes, i known, but, the GUI interact with Core, and the core is on GO lang. But, ok, i will try. Maybe i look on youtube, some explanations, how github code, pulls and changes works.

**Comment by AudriusButkevicius** [comment]
No, there is no interaction with the code, it's literally just shifting stuff around.
