### ISSUE TITLE
the ability to have folders appear in some sort or order instead of randomly

### ISSUE THREAD

**Issue by marrie** [syncthing/syncthing#2279]
At least they appear random to me.  I added a few folders and it looks like they appear in a random order, some look like they will appear in ABC order, then a folder starting with w will appear  then maybe a folder name starting the c, etc. If there is an order I can't glean it.
[Here is  a link to a screenshot  of what i mean, all bee it not a good one.](https://www.dropbox.com/s/dyvxxxpie26mng0/Screenshot%202015-09-14%2012.40.35.png?dl=1)

I hope that is clear enough.

**Comment by wweich** [comment]
They are sorted alphanumerically, while upper case is sorted before lower case.

**Comment by calmh** [comment]
Indeed

**Comment by marrie** [comment]
That's an odd way of sorting, but as long as it works. Maybe an idea would be to in the settings have a sorting option wherein it looks a lot like the pull order of files in the folders you are sharing across devices. Just a thought.

thanks.

**Comment by AudriusButkevicius** [comment]
Pull requests welcome.

**Comment by marrie** [comment]
I can't code to save my life.  but I'd be happy to commit an edit to the documentation when such time arrives for this feature. 

Thanks.

**Comment by calmh** [comment]
It may be a slightly computery way of sorting, I'd probably be fine with sorting case insensitively instead. Note though that I don't think there's any point in aiming for a "true" alphabetical sort, as defined by your locale. That is, handling åäö, other accented characters, sorting of Chinese, Korean, Russian correctly, and so on. It's a bit anglocentric, yes, but I think simplicity wins over correctness in this detail.

**Comment by marrie** [comment]
Well, the option could maybe be there for us list nerds like myself who need a precise way of doing things. Of corse it doesn't have to be, but that's just a suggestion. I'm thinking outloud here.

**Comment by AudriusButkevicius** [comment]
Well the way it is now, is the precise way for nerds ;)
66 (A) is less than 97 (a)

**Comment by calmh** [comment]
I don't want an option for how to sort stuff in the UI...
