### ISSUE TITLE
Syncthing “ panic: Can’t unmarshal stored mtime at path” crashes syncthing

### ISSUE THREAD

**Issue by wsmurf** [syncthing/syncthing#2281]
as requested i post on github too

I have syncthing working on a Freenes (freebsd) plugin. Overtime i hooked up a windows machine to the syncthing network and it runs happy until a few houres later i noticed syncthing was offline on the freenas server. I looked at the panic log and saw this error message

Panic at 2015-09-15T09:04:51+02:00 panic: Can't unmarshal stored mtime at path /path to the windows directory which contains mp3/

and then a bunch of errors codes 

To see if it is not the plugin which is faulty i made a new jail with plain freebsd, installed the freebsd 64bit of syncthing and hooked up the same directory. And also this one crashed with similar error. I also tried the same with the linux version and also i get the same panic warnings.

Any solution other then not sync the directory ?

Full Log 
http://pastebin.com/tLvpNdzC

**Comment by calmh** [comment]
That's odd. The mtime storage thing should only kick in on Android or when getting weird errors changing modification times. In this case it seems like your index database (~/.syncthing/index-v0.11.0.db) may be corrupt for whatever reasons - bad disk, bad memory? Haven't seen this particular error before though.

**Comment by AudriusButkevicius** [comment]
You can try to remove the folder, restart syncthing, and readd it under a different name?

**Comment by wsmurf** [comment]
Seems to work now under a different name strange
