### ISSUE TITLE
*.sync-conflict-*.* files growing in numbers, uncontrollably

### ISSUE THREAD

**Issue by jult** [syncthing/syncthing#2282]
Not sure why, but all my synced folders using syncthing show a never-ending (and only growing) number of \*sync-conflict\* files, taking up gigabytes in minutes of having syncthing running.
This 'feature' is killing one of my syncs, since it has a limited volume size of 30GB.
When I try and delete them, they just come back. I don't really understand the use of this. How do I control the number of these files, or avoid ever having more than one per file? I prefer the newest version of any file everywhere, no exceptions. And/or if the conflict disappears, or grows older than x time, have the sync-conflict files deleted automatically.
Can someone please either make this optional, or copy how btsync does this (because I never had it using that). By the way, I have versioning switched off entirely, still the same issue.

**Comment by AudriusButkevicius** [comment]
Best remedy is to stop producing conflicts, or just ignore the files which are causing them, as you clearly have something on both ends constantly modifying the files, hence causing conflicts.

Yes, we should probably add some limits on how many conflicts we keep.
As for BTSync, it's closed source, so there is nothing to copy from.

**Comment by jult** [comment]
You can never stop producing conflicts if you, for instance, sync a browser profile folder. BTSync is closed source, but Sync as used by Mozilla firefox is not, they're doing quite well for me, syncing always the newest everywhere, without losing things. Ask around there, or better yet, get them involved, they're smart guys. (I'll try and help with that.)

**Comment by AudriusButkevicius** [comment]
Mozilla profiles contains SQLite write ahead logs (*.wal, *.shm) which need to be ignored, as they are not necessary to sync the profile and can change a few hundred times a second.

Because Sync as used by Mozilla is meant to sync Mozilla profiles, it knows perfectly well which files do not need to be synced, and simply does not sync them.

**Comment by step21** [comment]
@jult as Audrius has said - there might be a solution, but especially with things like browser profiles that are prone to be used at more than one location - you normally don't want to use a generic sync solution for that, as depending on file format it will fail or if accessed written to at the same time, can also easily produce conflicts. This is also not limited to Mozilla.

**Comment by jult** [comment]
No, I was just giving the mozilla profile as an obvious example. For me almost every folder I've synced has too many (and way too old) *sync-conflict* files in them. Especially their age should be a sign of them not having to be there. By now I've created a separate script that kills them if they're 2 days old (or older).

**Comment by jult** [comment]
Still, it makes me wonder why such files have been generated in the first place. I never use more than one machine at a time, so the newest files are only generated where I'm at. Why the conflicts? The machine I'm using creates new or updated files, they should be synced with my NAS, and nothing on that NAS is using them, so they're just there. How do the conflicts appear?

**Comment by AudriusButkevicius** [comment]
The fact that they appear means that its happening. As I said, your are probably syncing memory mapped files.

**Comment by tkedwards** [comment]
I've come up with a little workaround for this by just using this little script in a cron job to regularly remove these sync-conflict files:
```
#!/bin/bash
/usr/bin/find /home/some_directory/thats/synced -name '*.sync-conflict-20*' -exec rm -f {} \;
```
The use case here is syncing from a Windows laptop up to a VPS, where the files are never touched on the VPS (so one-way sync in effect). So in other situations (e.g. syncing important documents between your laptop and desktop) this kind of thing might not be the best idea.

**Comment by xj25vm** [comment]
I have just had to deal with the same issue - and as some of the posts above mention, this sometimes happens even when the files are clearly only changed on one side of the sync. In my case I had setup sync from a Windows desktop to a Linux server - and they are *only* ever changed on the Windows desktop - never on the Linux server. The desktop is set in master/send only mode. In my case it turned out that the reason why the conflict files were being created was because the desktop computer did not have its time synced with the Internet/NTP, and the clock was slow. I suppose this made the files coming from the desktop to the Linux server look modified, but at the same time older than the ones on the Linux server - which forced Syncthing to conclude the files must have been modified in both places.

I thought I would mention it here in case others are experiencing a similar issue.

**Comment by Ferroin** [comment]
@xj25vm If your clocks were out of sync, then that's almost certainly what was happening, and there's not anything that Syncthing can do about that.  It's well beyond the scope of Syncthing to manage the system's clock, and pretty much any other file sync software chokes when the clocks are out of sync.

I may take the time to add something about this to the documentation later.

**Comment by xj25vm** [comment]
@Ferroin Thank you for your reply. I wasn't suggesting that Syncthing should try to make up for this - just thought I would add a note here in case it helps others.

However, I'm afraid I have spoken too soon - as Syncthing is continuing to create conflict files although the clocks are now correct on both sides. I wonder what could be causing Syncthing to think that files on the Linux server - which are never changed by any human or software - are in conflict with the files on the desktop machine?

**Comment by AudriusButkevicius** [comment]
is the content actually different?

**Comment by xj25vm** [comment]
It shouldn't. This a Sage Accounts installation - with the back-end on the Windows desktop machine - and I use Syncthing to shift data to the Linux server - to include it later in the nightly backup. There is nothing on the server which can change the files - at least I can't think of anything.

**Comment by AudriusButkevicius** [comment]
Hence why I suggest you check the content for differences.

**Comment by xj25vm** [comment]
Would I be best doing that with checksums - or with diff maybe?

**Comment by AudriusButkevicius** [comment]
Whatever works for you. If it's readable data, diff probably makes more sense.

**Comment by xj25vm** [comment]
I've used md5sum, as most of them are binary files. The checksums are different. Looking at the modification time of the files, the latest version has the original file name, and then I get an increasing number of conflict files associated with that name, with older modification times. It seems that Syncthing is updating the main file to the latest version coming from the desktop computer, and then renaming and keeping the previous versions as a conflict files.

**Comment by AudriusButkevicius** [comment]
That would mean that the linux machine thinks the file was modified for some reason. Things like modification timestamp changes (or granularity changes) could still cause this.
