### ISSUE TITLE
CentOS 7 - restrting from web interface

### ISSUE THREAD

**Issue by david-strejc** [syncthing/syncthing#2286]
I got Centos 7 with systemd established for one system user for running syncthing.

When I try to do a restart of syncthing from web interface syncthing goes down without restart.

**Comment by AudriusButkevicius** [comment]
Your systemd files are not handling exit codes correctly, systemd should restart syncthing on certain exit codes.

**Comment by bluewavenet** [comment]
@david-strejc - see #2239
There are numerous versions of systemd out in the wild and it looks like this is a problem for older versions.
I changed the line in syncthing@.service (or syncthing.service depending on which one you are using) as follows:
SuccessExitStatus=2 3 4
to
SuccessExitStatus=2 4
This works for me on Opensuse 13.2.  I very much suspect it will work for you too.
