### ISSUE TITLE
Idle vs Syncing

### ISSUE THREAD

**Issue by boghison** [syncthing/syncthing#2287]
Hi!
This is my first time using syncthing. It was a bit confusing at first, but now I don't understand why it doesn't actually sync. My computer says syncing (0%) with rates of 0. My phone says the same in devices, and Idle in the folder that I want to share. Why isn't it syncing?

**Comment by rumpelsepp** [comment]
You should ask on the [forum](https://forum.syncthing.net/) for support. This is the bug tracker about technical issues. :)

**Comment by boghison** [comment]
Oh nvm, the problem was the master folder state. Sorry for the false alarm :)
