### ISSUE TITLE
ID3 tags not synced

### ISSUE THREAD

**Issue by boghison** [syncthing/syncthing#2289]
I removed a tag and pressed the rescan button, it showed Up to Date and didn't sync the changes

**Comment by wweich** [comment]
IT seems that your ID3-Tag Editor preserves the modification time of the file. As Editing the ID3 Tag will not change the file size. Either size nor modification time are changed.

How should Syncthing know, that the file has changed?

**Comment by AudriusButkevicius** [comment]
We do not support syncing files which don't change size or mtime during modification.
