### ISSUE TITLE
Android needs special handling for the relay pool thing

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2290]
As it needs to get the relays over HTTPS without doing DNS...

**Comment by AudriusButkevicius** [comment]
I think Go 1.5 was supposed to fix the issue, or atleast there id definately a `-t netgo` which uses a non-libc resolver.

**Comment by calmh** [comment]
That'd be awesome. Needs investigation. There's also the `GOOS=android` which I don't know the status of.

**Comment by Nutomic** [comment]
This should  be handled by https://github.com/syncthing/syncthing-android/pull/495 soon.

**Comment by calmh** [comment]
@Nutomic did it work?

**Comment by Nutomic** [comment]
I'll push a beta release today. How can I test relays directly?

**Comment by calmh** [comment]
Check the web ui, if it says 1/1 for relays you're good to go

**Comment by Nutomic** [comment]
Yes it does, and DNS also definitely works (at least on my device). So wen can close this.
