### ISSUE TITLE
Permanently notify about initial connection requests

### ISSUE THREAD

**Issue by generalmanager** [syncthing/syncthing#2291]
When two devices try to connect to each other or especially if a new devices tries to connect to a sync server I host the initial connection workflow is often asynchronous.

But because Syncthing only shows the "device xyz wants to connect, do you want to add it?" message if both devices are connected and syncthing hasn't restarted it would be nice if we saved those requests and showed them to the user until s/he made a decision.

There should of course be an option next to "add device" to always ignore future connection attempts from this device. Otherwise people who intentionally or unintentionally try to connect to the wrong nodes could basically  DOS the GUI by making it unusable/annoying because of the permanent notifications.

**Comment by marrie** [comment]
Agreed. I brought this idea up in the forums about 2 days ago, but many think it sucks. I personally do not as I'm not always near or have the web UI open. I also think it shoudl retin in a data base in case I restart my screen session or the computer for that matter.
