### ISSUE TITLE
discovery on v0.12.0-beta1is b0rked?

### ISSUE THREAD

**Issue by jpjp** [syncthing/syncthing#2295]
Just upgraded to v0.12.0-beta1 on Linux. Nothing can see each other. I think the https discovery servers are all down.

**Comment by calmh** [comment]
Yeah, there's a naming confusion. :/

**Comment by jpjp** [comment]
oops :)

**Comment by calmh** [comment]
It's fixed in DNS, should propagate soon...

**Comment by jpjp** [comment]
Great. Will try again in 148 minutes!

**Comment by calmh** [comment]
Usually a bit faster than that. :)

**Comment by jpjp** [comment]
Is it expected that there were no messages showing the problem when syncthing -verbose is used?

**Comment by calmh** [comment]
Yes. I don't think we've ever complained on the terminal about dead global servers.

**Comment by calmh** [comment]
But maybe we should, at least if all are unavailable.

**Comment by jpjp** [comment]
okay, and are the self-signed certs pinned?

**Comment by jpjp** [comment]
Sorry, haven't tested betas in a while, lots of questions :(

**Comment by calmh** [comment]
They are, that's the `...?id=...` parameter on the servers.
