### ISSUE TITLE
INFO: Folder "xxxxxxx" error is cleared, restarting

### ISSUE THREAD

**Issue by jakoch5876** [syncthing/syncthing#2296]
I have three folders that are synced between two devices.  On the on desktop machine I receive no error warning or info messages.  On the other machine, which is headless, I receive the message INFO: Folder "xxxxx" error is cleared, restarting, for two of the three folders.  I looked at the code the message comes from an if statement at line 1760 in file model.go.

The desktop is running Kubuntu15.04 rev 11.25 of syncthing.
The headless device is running Debian 7.9 rev 11.25 syncthing

**Comment by AudriusButkevicius** [comment]
Here should be a message before that one saying what the error was. Also, if the error has cleared, what is the issue you are seeing?

**Comment by jakoch5876** [comment]
I am trying to find the root cause and fix it.  Since two of the three folders are have the issue I must have configured something wrong or syncthing is seeing something.  The polling frequency is about 80 secs.  So it is throwing out a lot of messages.

**Comment by AudriusButkevicius** [comment]
Check the web ui, the error will be displayed there. Also, you should post the full log.

**Comment by jakoch5876** [comment]
I restarted syncthing on the headless machine using this commandline:
syncthing -logfile="/var/log/syncthing.log" -no-browser

The output of the logfile is:
[SQ4NA] 09:59:48 INFO: Starting global discovery announcements
[SQ4NA] 09:59:48 INFO: Device CZ3T7J7-XVHZX2F-P4GQZK6-HMFSIWK-QUO6T5R-TASO45N-CWYKX2R-7PO2PQW is "emmentaler" at [dynamic]
[SQ4NA] 09:59:48 INFO: Device SQ4NAAI-OZ3HXZU-2FDYES3-3RCI7RA-QADO3EG-WGUA2OJ-7EPXFYF-UJD2OQC is "brie" at [dynamic]
[SQ4NA] 09:59:48 INFO: API listening on 127.0.0.1:8384
[SQ4NA] 09:59:58 INFO: No UPnP device detected
[SQ4NA] 10:00:11 INFO: Established secure connection to CZ3T7J7-XVHZX2F-P4GQZK6-HMFSIWK-QUO6T5R-TASO45N-CWYKX2R-7PO2PQW at 192.168.11.183:22000-192.168.11.204:48351
[SQ4NA] 10:00:11 INFO: Device CZ3T7J7-XVHZX2F-P4GQZK6-HMFSIWK-QUO6T5R-TASO45N-CWYKX2R-7PO2PQW client is "syncthing v0.11.25"
[SQ4NA] 10:00:11 INFO: Device CZ3T7J7-XVHZX2F-P4GQZK6-HMFSIWK-QUO6T5R-TASO45N-CWYKX2R-7PO2PQW name is "Emmentaler"
[SQ4NA] 10:01:31 INFO: Folder "Projects" error is cleared, restarting
[SQ4NA] 10:01:42 INFO: Folder "Documents" error is cleared, restarting
[SQ4NA] 10:03:16 INFO: Folder "Projects" error is cleared, restarting
[SQ4NA] 10:04:11 INFO: Folder "Documents" error is cleared, restarting
[SQ4NA] 10:04:57 INFO: Folder "Projects" error is cleared, restarting
[SQ4NA] 10:06:33 INFO: Folder "Projects" error is cleared, restarting
[SQ4NA] 10:06:34 INFO: Folder "Documents" error is cleared, restarting
[SQ4NA] 10:08:39 INFO: Folder "Projects" error is cleared, restarting
[SQ4NA] 10:09:03 INFO: Folder "Documents" error is cleared, restarting

**Comment by jakoch5876** [comment]
I believe I found the problem.
On the headless device I had a symlink to a RAID where the actual files are stored.  The config file had symlinksEnabled set as true.
I have shutdown both systems. Modified the config file on server to point to the folders on the RAID, bypassing the symlink.
So now that issue is resolved.

However, now that the systems are synced the headless unit is reporting there are six files across the three folders that "The following items could not be synchronized. They are retried automatically and will be synced when the error is resolved."  All six file exist on both machines, have the same sizes and permissions. In the message box the reason given is "no available source device".

**Comment by AudriusButkevicius** [comment]
The fact that the error is not shown when set is a bug.

**Comment by jakoch5876** [comment]
Audrius
Attached is the log from the headless device after bypassing the symlinks.
