### ISSUE TITLE
Some web gui dialogs are not closable with ESC

### ISSUE THREAD

**Issue by jpjp** [syncthing/syncthing#2298]
e.g. "show id" and "about"

**Comment by marrie** [comment]
Yep I can reproduce. the back button does not work for me either. I need to reopen the web UI. every time.

**Comment by calmh** [comment]
That's something else though. We don't mess with the back button, and you should be be able to click on "close" or outside the dialog...

**Comment by jpjp** [comment]
I tried to fix this myself but I got stuck comparing the templates. They look pretty different, so I'm doing something wrong.

**Comment by marrie** [comment]
I think I just closed the tab or window and I was back to where I was, but yeah, an odd one indeed.

**Comment by calmh** [comment]
It seems that modals opened using the modal *directive* (as opposed to the actual modal code directly in the view) don't get the correct handling here, regardless if I use the dynamic `ng-attr-data-keyboard`, a hardcoded `data-keyboard` in the directive or `{keyboard: true}` in the JS that opens the modal.

**Comment by calmh** [comment]
All are closeable with escape, now. I just tested.
