### ISSUE TITLE
RFE: show defaults in gui

### ISSUE THREAD

**Issue by jpjp** [syncthing/syncthing#2304]
Could the settings in the gui show which things are at the default values, and let me change things to default values with a click?

**Comment by AudriusButkevicius** [comment]
Why?

**Comment by jpjp** [comment]
So I can see which things are different from what you provide. The nearer the default config I am the better tested my use case is.

**Comment by AudriusButkevicius** [comment]
No piece of software/hardware I can think of provides this. At best, they provide reset defaults feature.

This brings a huge problem into the equation, such as where should we display them, etc, hence I don't think it will happen wothout a UI redesign.

Reset to defaults is feasible, and solves the problem just as well (screenshot existing settings, reset, see whats changed) but thats essentially just nuking config.xml.

**Comment by jpjp** [comment]
Firefox's about:config does it.

**Comment by AudriusButkevicius** [comment]
But thats not to be accessed by the casual user. My phone doesn't show me default settings, chromes standard dialog doesn't show default settings. I can't think of an applocation which does, which would be classified for standard user consumption.

**Comment by jpjp** [comment]
ok!

**Comment by AudriusButkevicius** [comment]
So we close this, or rename it to restore defaults?

**Comment by jpjp** [comment]
Restore defaults might overwrite something important, I will close it. If someone else wants to file an issue for that I guess they will :)
