### ISSUE TITLE
Alt tags for labels?

### ISSUE THREAD

**Issue by Buzzbegone** [syncthing/syncthing#2305]
HI :) I am writing to inform and explain a a problem I have found with SyncThing. First, please let me take the opportunity to thank you all for your hard work, and wonderful contributions. When SyncThing evolves it will be a large step forward for secure, fast, and simple file sharing.

I am using windows 7 I believe this issue will effect all windows versions however. SyncThing version      0.11.23

The main reason for this post however is sadly to present an issue I am having. Let me explain: I use a peace of assistive technology called NVDA. NVDA allows blind and visually impaired folks the opportunities to navigate a computer, access the internet, and generally participate in the 21st century. NVDA accomplishes this by taking text written to a computer screen and converting it in to speech. I won't go in to large amounts of detail here, if you want to learn more about all that please feel free to check out nvaccess.org 

Ok now that I've explained a little about that, here's my problem. When using NVDA on the SyncThing command page some times NVDA is not reading the edit boxes for device ID and something is getting jumbled up over the folder boxes as well. I think that might be because it's trying to read the entire editable area. The real crucks seems to be the device ID box. Sometimes with NVDA and this doesn't happen with jaws, the $1500 equivalent when tabbing in to the device ID box it says simply section. That's all just section. I also found NVDA wants to try and read that whole area of the page a little wrong,  because NVDA is trying to read a bunch of things it's hard to distinguish the actual device ID box. In a future release of lovely SyncThing would it be possible please to put in alt tags so NVDA and other screen readers can report to us the proper labels? It would make it easier for me, but also! for the person ont he other end who has to put up with me. :) A quick note, jaws seems to read everything fine so it might even just need to be that NVDA is told not! to try and read the whole area, I'm not entirely sure their.

Great work, I hope that SyncThing evolves and all that good stuff.

Sincerely Buzzbegone

**Comment by calmh** [comment]
Sure. Is this where get the current device ID for copy and paste, or where you fill in the device when adding a new device?

**Comment by Buzzbegone** [comment]
It looks like the main troubles are in adding a device. Clear labels would be great on all boxes.The biggy is adding devices how ever.

   Thank you very much! that’s really cool and I look forward to checking out the sweet changes.

Sincerely Jonathan

**Comment by derekriemer** [comment]
To be clear, where are you experiencing this? On the add device page?

**Comment by derekriemer** [comment]
The device ID is not tabbable in the edit dialog. This is not an input element, but if we wish to make this tabbable, we could add tabindex=0 to it.

**Comment by Buzzbegone** [comment]
Oh this is quite a while ago but yes if I remember write the edit boxxes weren’t speaking correctly on the add new devices page.

**Comment by derekriemer** [comment]
I cannot reproduce this here, so I think it might have been fixed.
