### ISSUE TITLE
"out of disk space" occuring when there are 1% space left

### ISSUE THREAD

**Issue by koppor** [syncthing/syncthing#2306]
synthing stops synchronizing on Windows 8.1 Pro when there is some space left

```
$df -h
Filesystem      Size  Used Avail Use% Mounted on
C:/cygwin       239G  236G  2.3G 100% /
```

How can this limit be changed? I did not see any configuration option.

**Comment by jpjp** [comment]
Have a look under Settings> Advanced. Check a folder, and look at minDiskFreePct.

**Comment by koppor** [comment]
Thanx. That should solve it. I'll reopen, if it doesn't. I searched for the item in "Actions" > "Settings", because I thought, it was a global setting.

**Comment by uok** [comment]
you can also set free space for each folder separately by editing the folder settings
