### ISSUE TITLE
Getting "folder path missing" when I'm not logged in to server via SSH

### ISSUE THREAD

**Issue by schikulski** [syncthing/syncthing#2311]
This is strange. When I'm logged into my server using SSH, Synchting works perfectly with no errors in the GUI. But as soon as I log out of SSH the web GUI says `Stopping folder "default" - folder path missing`. When I log in to my server using SSH again the error message disappears. 

![screenshot](http://i.imgur.com/TJts0eL.png)

I'm running Syncthing as a daemon, but was experiencing the same issue when I was running `syncthing` from my user.

What's happening?

Here's my /etc/init/syncthing.conf:

	description "Syncthing P2P sync service"

	start on (local-filesystems and net-device-up IFACE!=lo)
	stop on runlevel [!2345]

	env STNORESTART=yes
	env HOME=/home/simen
	setuid "simen"
	setgid "simen"

	exec /usr/bin/syncthing

	respawn

And my config.xml

	<configuration version="11">
	    <folder id="default" path="/home/simen/Sync" ro="false" rescanIntervalS="60" ignorePerms="false" autoNormalize="false">
	        <device id="XXX"></device>
	        <device id="XXX"></device>
	        <minDiskFreePct>1</minDiskFreePct>
	        <versioning></versioning>
	        <copiers>0</copiers>
	        <pullers>0</pullers>
	        <hashers>0</hashers>
	        <order>random</order>
	        <ignoreDelete>false</ignoreDelete>
	    </folder>
	    <device id="XXX" name="MacBook" compression="metadata" introducer="false">
	        <address>dynamic</address>
	    </device>
	    <device id="XXX" name="elverum" compression="metadata" introducer="false">
	        <address>dynamic</address>
	    </device>
	    <gui enabled="true" tls="true">
	        <address>0.0.0.0:8384</address>
	        <user>simen</user>
	        <password>XXXX</password>
	        <apikey>XXX</apikey>
	    </gui>
	    <options>
	        <listenAddress>0.0.0.0:22000</listenAddress>
	        <globalAnnounceServer>udp4://announce.syncthing.net:22026</globalAnnounceServer>
	        <globalAnnounceServer>udp6://announce-v6.syncthing.net:22026</globalAnnounceServer>
	        <globalAnnounceEnabled>true</globalAnnounceEnabled>
	        <localAnnounceEnabled>true</localAnnounceEnabled>
	        <localAnnouncePort>21025</localAnnouncePort>
	        <localAnnounceMCAddr>[ff32::5222]:21026</localAnnounceMCAddr>
	        <maxSendKbps>0</maxSendKbps>
	        <maxRecvKbps>0</maxRecvKbps>
	        <reconnectionIntervalS>60</reconnectionIntervalS>
	        <startBrowser>true</startBrowser>
	        <upnpEnabled>true</upnpEnabled>
	        <upnpLeaseMinutes>60</upnpLeaseMinutes>
	        <upnpRenewalMinutes>30</upnpRenewalMinutes>
	        <upnpTimeoutSeconds>10</upnpTimeoutSeconds>
	        <urAccepted>1</urAccepted>
	        <urUniqueID>O3u4bIH6</urUniqueID>
	        <restartOnWakeup>true</restartOnWakeup>
	        <autoUpgradeIntervalH>12</autoUpgradeIntervalH>
	        <keepTemporariesH>24</keepTemporariesH>
	        <cacheIgnoredFiles>true</cacheIgnoredFiles>
	        <progressUpdateIntervalS>5</progressUpdateIntervalS>
	        <symlinksEnabled>true</symlinksEnabled>
	        <limitBandwidthInLan>false</limitBandwidthInLan>
	        <databaseBlockCacheMiB>0</databaseBlockCacheMiB>
	        <pingTimeoutS>30</pingTimeoutS>
	        <pingIdleTimeS>60</pingIdleTimeS>
	        <minHomeDiskFreePct>1</minHomeDiskFreePct>
	    </options>
	</configuration>

**Comment by AudriusButkevicius** [comment]
Id suggest getting a separate shell, probably on a separate user and check what happens and if its still there. Its possible that you are using ldap or some other magical auth/automount system, which automounts your home directory upon logging in. Its definately not a syncthing issue, as syncthing has no dependency on your shell session. Its probably your environment depends on your shell session.

**Comment by calmh** [comment]
Home directory encryption is my guess. Which is basically a case of what Audrius suggests.

**Comment by schikulski** [comment]
You are right. The home directory is encrypted. After I closed *all* my open shell connections it worked
