### ISSUE TITLE
Missing service template for upstart-based Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by dkessel** [syncthing/syncthing#2315]
The project currently has system service templates for Systemd-based systems, which works well on Ubuntu 15.10 (and possibly on 15.04, too). However, a service template (and documentation) is needed for Ubuntu 14.04, which is using Upstart as init system. This version is used on my server systems, as it has long-term support.

**Comment by AudriusButkevicius** [comment]
It's not missing per-se, nobody in has yet the community has contributed it.

**Comment by glasen** [comment]
Here is my own upstart.conf-files which i use on my Ubuntu 14.04-server:
`description "Syncthing P2P sync service"
start on (local-filesystems and net-device-up IFACE!=lo)
stop on runlevel [!2345]
setuid "glasen"
setgid "glasen"
env STNORESTART=yes
env HOME=/home/glasen
exec /usr/bin/syncthing respawn`

If you want to start syncthing on login just create a file in the directory ".config/upstart" with the following content:

`description	"P2P sync service"
start on desktop-start
stop on desktop-end
env STNORESTART=yes
respawn
exec /usr/bin/syncthing`

**Comment by dkessel** [comment]
Looks good. glasen, do you want to create a pull request for that?

**Comment by andersonvom** [comment]
Can this be closed, then?
