### ISSUE TITLE
Feature Request: Custom file extensions 

### ISSUE THREAD

**Issue by ChaosTherum** [syncthing/syncthing#2318]
So the problem I'm running into is when auto organizing media files occasionally it will grab a file before it is complete. I was wondering if it would be possibl to append .ignore, or .sync or something of the such while syncing. From what I've seen it prepends the file which doesn't help so much with some organizers.

**Comment by AudriusButkevicius** [comment]
It has a ~synching~ prefix before its finished, so I am not sure why that doesn't help?

**Comment by kozec** [comment]
> it has a ~synching~ prefix before its finished, so I am not sure why that doesn't help?

I believe `~synching~01 Track 01.mp3` is still considered mp3 by any widely used player or media organizer...

**Comment by wweich** [comment]
According to [syncthing/lib/model/tempname.go](https://github.com/syncthing/syncthing/blob/master/lib/model/tempname.go) temp files are `~syncthing~<filename>.tmp` on windows and `.syncthig.<filename>.tmp` on other systems.

So you only need to exclude the `.tmp` file extension.

**Comment by AudriusButkevicius** [comment]
True
