### ISSUE TITLE
11.25 on amd64 linux: crashes ungracefully when disk full

### ISSUE THREAD

**Issue by andrewufrank** [syncthing/syncthing#2319]
syncthing crashed repeatedly with error messages from go as shown later. syncing can easily produce a 'disk full' condition and this should be reported to other nodes. can you include some helpful messages pointing to the cause?
thank you

error messages from syslog:
<autogenerated>:112 +0x197
Sep 27 11:12:58 denver syncthing[8682]: github.com/syncthing/syncthing/lib/model.(*Model).requestGlobal(0xc209ed59e0, 0x2b60e3c86d960d3a, 0x8792909aca52e661, 0xce5959fd6a979a79, 0x5450ecdbe02bcb32, 0xc2081230b4, 0xa, 0xc20b21a060, 0x1e, 0x0, ...)
Sep 27 11:12:58 denver syncthing[8682]: /go/src/github.com/syncthing/syncthing/lib/model/model.go:1128 +0x7d8
Sep 27 11:12:58 denver syncthing[8682]: github.com/syncthing/syncthing/lib/model.(*rwFolder).pullerRoutine(0xc20af997a0, 0xc208fb11a0, 0xc208fb12c0)
Sep 27 11:12:58 denver syncthing[8682]: /go/src/github.com/syncthing/syncthing/lib/model/rwfolder.go:1211 +0x4af
Sep 27 11:12:58 denver syncthing[8682]: github.com/syncthing/syncthing/lib/model.func·020()
Sep 27 11:12:58 denver syncthing[8682]: /go/src/github.com/syncthing/syncthing/lib/model/rwfolder.go:437 +0x4c
Sep 27 11:12:58 denver syncthing[8682]: created by github.com/syncthing/syncthing/lib/model.(*rwFolder).pullerIteration
Sep 27 11:12:58 denver syncthing[8682]: /go/src/github.com/syncthing/syncthing/lib/model/rwfolder.go:439 +0xb46

**Comment by AudriusButkevicius** [comment]
This is not the full stacktrace, plus its mangled by your logger. Can you please provide the whole log, and not mangled by systemd?

**Comment by andrewufrank** [comment]
sorry for not having given the complete information. where can i find the full log? (i am using a debian jessie installation)? 
thank you for the very useful system!

**Comment by AudriusButkevicius** [comment]
It logs to stdout by default

**Comment by rumpelsepp** [comment]
> sorry for not having given the complete information. where can i find the full log? (i am using a debian jessie installation)?
> thank you for the very useful system!

Shutdown syncthing and start it manually from the command line:

```
$ syncthing
```
