### ISSUE TITLE
all devices out of sync when folder removed before transfer completion

### ISSUE THREAD

**Issue by graboluk** [syncthing/syncthing#2323]
I have st 0.11.25 installed on computers A, B, C (all debian testing). On A I add a folder "current" to ~/Sync with 40 Mb data. Then, after B and C start pulling, I realize it's a wrong folder, so I remove it. Finally (I'm not sure if this part is important for what follows), I add another file to ~/Sync on A.

Result is that all three machines report being "out of sync", and all three report the other two to be "up to date". 

~/Sync on A looks the way it should look. ~/Sync on B and C have additionally folder "current" with files in it, but all files have size 0. Machine C keeps reporting (and presumably B as well, but I haven't figured out how to check it) mesasges of the sort:

`[WUZ2F] 00:30:59 INFO: Puller (folder "default", dir "current/Dyson"): delete: remove /home/luke/Sync/current/Dyson: directory not empty`

`[WUZ2F] 00:30:59 INFO: Puller (folder "default", dir "current"): delete: remove /home/luke/Sync/current: directory not empty`

`[WUZ2F] 00:30:59 INFO: Folder "default" isn't making progress. Pausing puller for 1m0s.`

then it pauses for 1m and repeats reporting the same messages.

If now I add files to ~/Sync on either A, B, or C, they seem to be syncing fine.

Addendum: when I removed the folders "current" from B and C all three machines report being up to date (and report both other machines being up to date)

**Comment by graboluk** [comment]
when I removed the folders "current" from B and C all three machines report being up to date (and report both other machines being up to date)

**Comment by AudriusButkevicius** [comment]
If you shut them all down, and restart them again at the same time, they should get back up in state. You probably hit some race condition, but I am sure that there is more than 1 ticket which relate to this issue, sadly none of them have clear 100% reproducible steps.

**Comment by graboluk** [comment]
I don't think it's fair, but ok. The issue  "Sync missing files #2211" describes what seems to be exactly the same problem (i.e. add file, and then delete them before sync completed -> "out of sync" and 0b files), and I've reproduced it in 2 out of 6 tries.

**Comment by AudriusButkevicius** [comment]
You should post a comment under that issue as it will get lost otherwise. As for not fair, I do feel that its the same issue, hence I am not sure why you think its not fair? I am sure that there also exists a few issues with directory not empty, again, there was some explanations how to debug it and what information we need in the other tickers. Sadly I am on my phone, and can't find it right now.

**Comment by graboluk** [comment]
Ok, I posted there. I said I don't think it's fair because I thought you suggest ignoring all those tickets because they are not 100% reproducible. Now I see you meant I should post it there and not open a new ticket which is very fair :-)
