### ISSUE TITLE
disable sync-conflict generation on specific folders (enh)

### ISSUE THREAD

**Issue by ZeerDonker** [syncthing/syncthing#2324]
Hello,

Is there a way to disable sync-conflict file generation for specific folders? 

Read https://github.com/syncthing/syncthing/issues/2282, think this is a slightly different enhancement. 

Use case is switching branches in a git directory, causing conflicts.

**Comment by AudriusButkevicius** [comment]
You will corrupt your git directory by syncing it, I promise.

**Comment by AudriusButkevicius** [comment]
Also, it is the same issue as tge one you've mentiined, and your request is just an implemebtation detail of that.

You should just make a comment that the number should be configurable, with 0 as a potential value.
