### ISSUE TITLE
FATAL: Bad listen address: too many colons in address tcp://0.0.0.0:22000

### ISSUE THREAD

**Issue by fbreve** [syncthing/syncthing#2325]
A button to upgrade to version 0.12 appeared, so I did. When I went to the other machines to do the same, the button is not there anymore. So I must go back to 0.11, but now I get this error:

FATAL: Bad listen address: too many colons in address tcp://0.0.0.0:22000

**Comment by AudriusButkevicius** [comment]
In syncthings home directory there will be a a copy if the old config file with some numeric suffix, replace config.xml with that.

**Comment by fbreve** [comment]
I tried that. It didn't work.
v1, v2, v3, all failed

**Comment by AudriusButkevicius** [comment]
You should use the last one, which should be something like v11 or bigger.

**Comment by fbreve** [comment]
Right. I was looking into Synctrayzor folder instead of Syncthing. Since synctrayzor.exe is actually in Synctrayzor folder, I thought it was that config file.
Now I found v11, renamed it and everything is fine again.
Thank you

**Comment by calmh** [comment]
Sorry for the spurious upgrade notice, that was my fault. :/

**Comment by iav** [comment]
Have same problem - error "FATAL: Bad listen address: too many colons in address tcp://0.0.0.0:22000"
syncthing itself happily start and work. Old and ne config files in syncthing folder are  the same.
