### ISSUE TITLE
Devices do not see eachother, listed as disconnect and unused

### ISSUE THREAD

**Issue by rrik** [syncthing/syncthing#2334]
Hello,

I had my seedbox and server syncing just fine, until recently. Now they cannot recognize each other.

Locally, my seedbox appears as 'unused' whereas on the seedbox side it shows the server as 'disconnected'.

Seedbox running v0.12.0-beta2 linux 64bit, server v0.11.25 linux 64bit

UPNP appears to be functioning, but I am happy to open ports if that is what needs to be done. 

http://pastebin.com/embed.php?i=2J6mPVzZ

Thank you!

**Comment by stratacast** [comment]
I have a similar issue. I'm running syncthing v0.11.25 on all my devices and none of them see each other globally. I can sync over the local network only. I get the "no UPNP devices detected message". I've seen other bug reports on this that are closed, but this issue still doesn't seem to be resolved. Unless I'm missing something, I have port 22000 open on my devices and there still seems to be no cooperation unless I'm on the same LAN

**Comment by wweich** [comment]
You should read the release notes of v0.12.

**v0.12 is incompatible to v0.11 !!**

**Comment by stratacast** [comment]
@wweich yes, I did tonight and I think the one I missed was 21025 or something like that. I rechecked all my devices because I've been toying with this issue in my spare time. I'll be on an external network again tomorrow so I'll confirm if it was just me missing a port or not.

**Comment by AudriusButkevicius** [comment]
One of the sides needs to be on the internet, have UPnP or port forwarding enabled. The fact it says unused implies that no folder is shared with a device. Also, please use the forum for support requests.
