### ISSUE TITLE
badly formatted "insufficient disk space" message

### ISSUE THREAD

**Issue by Dobatymo** [syncthing/syncthing#2338]
While syncing with an almost full hdd, i got this message in the console
```[XXXXX] 17:29:39 WARNING: Folder "\\?\D:\SYNCDIR": insufficient disk space in Path/to/filename.ext for %!s(float64=500.00390625): have 609.03 MiB, need %!f(MISSING) MiB```

**Comment by wweich** [comment]
Syncthing checks, if the disk is full.
It will stop syncing (by default), when 1% is left.
You can change that in the folder settings.

**Comment by wweich** [comment]
It is already worked on: #2317

**Comment by chucic** [comment]
Happened to me also one. Since referenced PR merged long time ago should this be closed now?
