### ISSUE TITLE
Prefer local link

### ISSUE THREAD

**Issue by rumpelsepp** [syncthing/syncthing#2339]
I am running `v0.12.0-beta2+10-g375c9dd` and I discovered an issue according to local discovery. I have two nodes in my local network and they seem to connect through the global discovery machinery (via upnp port forwarding) instead. After disabling upnp in my router they connect through my local network. 

I remember this issue has been there some time ago; maybe a regression?

**Comment by calmh** [comment]
Yes, probably. We don't treat the set of addresses with any internal prioritization, which we should.
