### ISSUE TITLE
Make units for transfer rates configurable

### ISSUE THREAD

**Issue by jedie** [syncthing/syncthing#234]
Change the Down-/Upload rate from "bps" to "KB/s" or "MB/s" because it's more common, isn't it?

EDIT: Also "Outgoing Rate Limit (KBps)" and "Max File Change Rate (KBps)"

**Comment by lkwg82** [comment]
I suggest to close this until we see a PR.

**Comment by AudriusButkevicius** [comment]
Well it's a valid feature request, so I think it should live.

**Comment by canton7** [comment]
I don't think there's any need to go around closing "Unplanned" issues. They're markers saying "hey, we considered this. If you're looking for something to contribute, give it some thought" . People will just open new issues if we close the old ones.

**Comment by calmh** [comment]
Yes. Closing means I *don't* want a PR, or at least is unlikely to accept one without persuasion.

**Comment by lkwg82** [comment]
ok, got it ;) Just went around and thought of cleaning stale issues.

**Comment by AudriusButkevicius** [comment]
Github not doing its job.

**Comment by calmh** [comment]
Yes that's odd. I see nothing wrong with my tagging, but it didn't pick it up at all. For posterity:

https://github.com/syncthing/syncthing/pull/4074
