### ISSUE TITLE
Discovery tooltip looks ugly

### ISSUE THREAD

**Issue by rumpelsepp** [syncthing/syncthing#2344]
It looks quite ugly, as it displays error messages in the tooltip which are too broad.

![screenshot from 2015-10-01 08-53-51](https://cloud.githubusercontent.com/assets/1961699/10214596/062526f4-681a-11e5-86f7-613ab1ba46a1.png)

**Comment by rumpelsepp** [comment]
Ahh, version `v0.12.0-beta2+8-g6f6c1cd`.

**Comment by calmh** [comment]
Yeah it's not super awesome

**Comment by jamespinger** [comment]
New here, not sure re: the typical protocol...
Something like this work?
![discoverymenu](https://cloud.githubusercontent.com/assets/16848469/12528564/98464d90-c168-11e5-9ef3-6be15474f481.png)

**Comment by rumpelsepp** [comment]
I guess you should replace "discovery Server: foo device info: with just the URL.

**Comment by jamespinger** [comment]
I figured 'discovery server' was telling you what server was showing that machine. They're all from different subdomains.
 Doesn't help the end user, but it could be valid either way.

**Comment by AudriusButkevicius** [comment]
I think this whole thing should be turned into a modal, which when opened has more space to describe the errors.
Same goes for the relays.

**Comment by jamespinger** [comment]
Is there enough data to require a modal?  
As far as i can tell, the extent of the errors are 'network is unreachable'. Whether that's because the host is offline, there's a upnp problem, a port isn't forwarded, or there's a firewall blocking it, there isn't anything else being reported to the failed disco array.

**Comment by AudriusButkevicius** [comment]
Agree, but the errors are too long to fit into a tooltip it seems, hence why its ugly.

**Comment by rumpelsepp** [comment]
What about combing this issue with #2218? Some modal with several connection information in one place.

**Comment by calmh** [comment]
+1 for a modal, but -1 for combining it with the connection doctor as that's a much larger feature

**Comment by AudriusButkevicius** [comment]
I am thinking about combining relays + connections + discovery etc.

**Comment by lkwg82** [comment]
I just checked and I cant reproduce it. It seems to be gone. Can someone confirm?

**Comment by AudriusButkevicius** [comment]
Define cannot reproduce.
If discovery is not failing, you won't see them.

**Comment by lkwg82** [comment]
I can reproduce, when I disable ipv6. Thx for help thinking ;)

**Comment by bugith** [comment]
We should be able to translate this "Click to see discovery failures." string
