### ISSUE TITLE
WinXP SP3 panic before malloc heap initialized

### ISSUE THREAD

**Issue by Triquetra** [syncthing/syncthing#2356]
I'm trying to run syncthing from the console in Windows XP, but am running into the following error:

runtime: panic before malloc heap initialized
fatal error: runtime: cannot reserve arena virtual address space

runtime stack:
runtime.throw(0xccb8d2)
	/usr/local/go/src/runtime/panic.go:491 +0x83 fp=0x6fedc sp=0x6fec4
runtime.mallocinit()
	/usr/local/go/src/runtime/malloc.c:223 +0xef fp=0x6ff18 sp=0x6fedc
runtime.schedinit()
	/usr/local/go/src/runtime/proc.c:137 +0x3a fp=0x6ff30 sp=0x6ff18
runtime.rt0_go(0x6ffc8, 0x805491e8, 0x86df7000, 0x2a49, 0x4, 0x0, 0x86def000, 0x1, 0xe76700, 0xff676980, ...)
	/usr/local/go/src/runtime/asm_386.s:100 +0xf9 fp=0x6ff34 sp=0x6ff30

**Comment by AudriusButkevicius** [comment]
You should post the full log.

**Comment by Triquetra** [comment]
Tell me where the log is that you want to see, and I'll post it.  The above is not from a log, it is the full error message given when running syncthing.

**Comment by AudriusButkevicius** [comment]
If that's the first thing it prints, it probably just fails to initialize the runtime.
I guess you should try downloading Go, and compiling it yourself and check if that helps.
If it does, its probably something with the build process, if it doesn't then it's probably a Go bug.

**Comment by AudriusButkevicius** [comment]
Also: http://stackoverflow.com/a/20247369/1508606

**Comment by Triquetra** [comment]
Following those suggestions do  not seem to help.  Running as administrator gives the same error.  I even increased the physical ram from 1 gig to 3 gig, and boosted the virtual ram to 6 gig, but I still get the same error.

**Comment by AudriusButkevicius** [comment]
Ass I said, you should try downloading go, and compiling it yourself.

**Comment by calmh** [comment]
Seems system specific as noone else has rapported this. Unclear/needs repo.
