### ISSUE TITLE
crash because index too big

### ISSUE THREAD

**Issue by andrewufrank** [syncthing/syncthing#2357]
i observed a crash (ungraceful exit of syncthing 0.11.26  on a arm with debian wheezy) because the index became so big that it used up all home (it must have used about 1.5 GB). after i deleted all index files, synching started normally and seems to work ok.
i would recommend:
1. check the growth of the index and keep it under control (i have on another computer (amd64 debian jessie) 1.4 GB
2. produce a useful error message when disk full because the index has grown.
3. add in the instruction a clear message that the index can be deleted without lasting effect (such that it can be googled in a hurry - when the emergency happens)
thank you for an ever improving system!

**Comment by AudriusButkevicius** [comment]
There are space checks which stop syncthing if there is not enough space, so either you fisabled them, or there is a bug. 

Deleing an index can cause a lot of your files to be marked as conflicting 

Also, what do you mean keep it under control?

**Comment by andrewufrank** [comment]
i guess that the space checks are working on the volume where syncthing
writes the files. in this case the index is on a different device (same
hard disk, but different file system). would this explain why it crashed?

unfortunately, i do not have the exact size, but it was several GByte.
it seems to recover and i have not seen more conflicting file
indications. i will not do it again, but keep an eye on the size of the
index.

thank you for the quick reply.
andrew

**Comment by fragtion** [comment]
1.5GB of indexes ??? xD eeek... not sure if your usage case is just way extreme, or if Syncthing's means of indexing is inefficient/inadequade (arguably there is room for improvement anyway), but 1.5GB of pure indexes just sounds completely absurd. That means each time your peers reconnect you'll need to do 1.5GB of network traffic just to ensure that the replicas are in sync

**Comment by AudriusButkevicius** [comment]
Index potentially contains indexes of all other peers, so if he has 100 peers, thats 15MB per peer. Plus, the index contains other info which we don't transfer.

**Comment by andrewufrank** [comment]
i had the same problem again: syncthing did stop working (crashed) 
because the disk was full.
the index had grown to 3.5 gb.
after restart, the index shrank immediately to .5 gb
i read somewhere, that the index is compacted after each reboot, but i 
do not intend to reboot this device, which is just running only 
syncthing. it should automatically compact the index regularly (every n 
days) or when the index grows too much.

i have a standard installation and not changed the checks for space 
available.

is my understanding correct: the index gets only compacted at reboot? if 
this is the case, i will see that reboots are regularly scheduled.

thank you!
andrew

**Comment by AudriusButkevicius** [comment]
Index gets compacted when you restart syncthing, not the machine.

Also, it does compact the index in the background, but every connected device increases the index size, so might comeback when all devices reconnect.

**Comment by andrewufrank** [comment]
thank you for this clear information.
i have made the disk big enough now!
af
