### ISSUE TITLE
Per-folder feature to make symlinks appear as folders/files to syncthing

### ISSUE THREAD

**Issue by hachre** [syncthing/syncthing#2358]
Hi guys,

absolutely love syncthing so far!!!

It is great that it supports real symlinks and they are enabled by default. In some cases, however, I'd like to be able to use symlinks to pull more folders or files into the synced folder structure. I propose a per-folder setting that disables normal symlink behavior for that entire folder and instead behaves as if those symlinks to folders and files were actual folders and files within the sync folder.

If a file / folder that has been pulled in through a symlink were to be deleted on a target machine, syncthing on the source machine should ignore the delete commands and subsequently the contents should be synced back. Under no circumstances should syncthing follow the symlink on the source and delete the real files.

If this feature is at all feasible, it would improve my life in a few cases where I am now currently using mount --bind into the sync folder combined with the "Folder Master" setting to solve the deletion probem.

Thanks!

**Comment by AudriusButkevicius** [comment]
Following symlinks is already there in advanced.config, but it can cause data loss if you disable it. The rest of the request for not deleting stuff is already what master folder does.

**Comment by hachre** [comment]
I thought that the recent introduction of real symlink support essentially removed the followSymlinks flag? In any case I tried that in 0.11.25 and it had no effect. It continued to sync the actual symlink.

**Comment by AudriusButkevicius** [comment]
Actually, I am not sure if it was ever merged. If it wasn't then there should still be a ticket open, effectively making this one a dup.

**Comment by AudriusButkevicius** [comment]
https://github.com/syncthing/syncthing/issues/1776 dup

**Comment by hachre** [comment]
thank you :)

**Comment by plttn** [comment]
FWIW, using the followSymlinks flag on my folder master is showing the symlink in console on the client, but still not following it to the actual file.

**Comment by AudriusButkevicius** [comment]
Yeah, because the feature is not merged.
