### ISSUE TITLE
losing connections - to slow arm devices

### ISSUE THREAD

**Issue by andrewufrank** [syncthing/syncthing#2359]
i use syncthing to synchronize folders for a total of 300 GB on more than half a dozen computers. always on are three arm version (0.11.26 on debian), which are often slow in response, also using slow lines. i have set the pingtimeout to 300 or 600 sec, but i do still see that connections to working systems are not done (global discovery is 1/2 for all). i observe that one computer A connects to B and C, but B does not connect to C. the connection existed and was dropped hours ago.
what could be the cause? are there other timeouts i could set higher? how is re-connection controlled? can i force it?

thank you for your help!

**Comment by AudriusButkevicius** [comment]
Set STTRACE=net,connections env var and see what happens. The reconnection interval is controlled from advancedConfig. You could also try upgrading to 0.12 beta which has better timeout handling.

**Comment by andrewufrank** [comment]
thank you - i will move to 0.12 when it is not beta anymore.
andrew

**Comment by AudriusButkevicius** [comment]
If you are not willing to debug this, can we close this?

**Comment by andrewufrank** [comment]
this time i cannot help (i start for a week long trip). please close. i 
will observe whether 0.12 helps.
thank you!
andrew
