### ISSUE TITLE
Folders after the first one don't sync

### ISSUE THREAD

**Issue by cattledogit** [syncthing/syncthing#2360]
First folder sync works fine, but subsequent folder syncs added for the same device/desktop pair don't sync, though second folder on device shows "Idle (100%)" (55 files), and on desktop shows "Up to Date" (0 items). The second folder on device had 29 files in it when the sync was created, the second folder on the desktop was empty after being created by syncthing.

I've tried deleting the second folder sync and adding it back, but haven't tried deleting the first folder sync which has long stayed in sync. Both folders on device are on extSdCard.

Note 2 with syncthing v0.11.22, Win10 x64 with syncthing v0.11.26

Otherwise, syncthing has been working great for some time. :)

**Comment by AudriusButkevicius** [comment]
You should post screenshots from both sides, as it's not obvious from your descriptions what the actual state is.

**Comment by cattledogit** [comment]
Attached. Note the difference between the contents of DCIM.
![desktop syncthing](https://cloud.githubusercontent.com/assets/10760329/10318382/14b02194-6c37-11e5-83ec-80f8ab45c580.jpg)
![device syncthing](https://cloud.githubusercontent.com/assets/10760329/10318384/167d2e5e-6c37-11e5-9b77-ba15af5393d9.png)

**Comment by AudriusButkevicius** [comment]
Can you get a picture of the web ui on the phone?

**Comment by cattledogit** [comment]
Hopefully, this is what you requested:

![screenshot_2015-10-06-14-56-49](https://cloud.githubusercontent.com/assets/10760329/10319146/c4a51f0c-6c3a-11e5-8e6f-cdbbc64eb459.png)
![screenshot_2015-10-06-14-56-58](https://cloud.githubusercontent.com/assets/10760329/10319147/c62c2942-6c3a-11e5-8c6a-fd9bb623e23f.png)

**Comment by AudriusButkevicius** [comment]
So it looks like the folder is not shared with the other device?
Also, have you tried clicking the rescan button?
Also, I don't know why but all the icons are grey, so can you expand the device you are expecting to connect to?

**Comment by dcarosone** [comment]
External sd card on android will be read only to syncthing, and can't be
used. Alas.

**Comment by AudriusButkevicius** [comment]
But he is sending stuff, not receiving.

**Comment by dcarosone** [comment]
Can't create .stfolder, can't proceed

**Comment by AudriusButkevicius** [comment]
It should show an error, but given its a mobile version maybe that is not visible, so you a most likely right

**Comment by dcarosone** [comment]
Hm. Looking closer, it seems to have indexed local state, so this may not
be it.  A careful check of the logs is probably warranted though.

**Comment by cattledogit** [comment]
Thanks for the help. Device is rooted, and syncthing requested and was granted superuser, but the "sync as Root" option is unchecked (checking it caused syncthing to show "loading" indefinitely on restart). 

dcarosone commented:
> A careful check of the logs is probably warranted though.
I'm not sure where to submit that.

AudriusButkevicius commented:
> So it looks like the folder is not shared with the other device?
Yes, the contents of the device's second or third folder aren't shared with the desktop, or visa versa, but the first folder is shared correctly, and it's in the same directory on each end (including on extSdCard). Device is rooted.

> Also, have you tried clicking the rescan button?
Yes, and anything else I could think of.

> Also, I don't know why but all the icons are grey, so can you expand the device you are expecting to connect to?
![screenshot_2015-10-06-20-19-11](https://cloud.githubusercontent.com/assets/10760329/10326338/0e6a3cc6-6c68-11e5-9287-b4ba0e8a3463.png)

**Comment by cattledogit** [comment]
dcarosone wrote:
> Can't create .stfolder, can't proceed

I tried deleting .stfolder this afternoon, and it was (re)created when I had to recreate the DCIM sync. This was after "(...show "loading" indefinitely on restart)" required that I restore syncthing using Titanium Backup.

**Comment by AudriusButkevicius** [comment]
It says on the mobile under krj3 device that the only shared folders are: Apache, and not Apache, DCIM. So the DCIM folder is simply not shared with the other peer. That fact that you added it is not good enough, you have to share it too.

**Comment by cattledogit** [comment]
Perhaps the text "a Device must be selected" or "Required" could be added to the Device menu item in the Android app. I can no longer recall or find how I knew to select my desktop when I added the first sync folder on the device. Thanks for your help and for syncthing.
