### ISSUE TITLE
Broken aria tags

### ISSUE THREAD

**Issue by tspivey** [syncthing/syncthing#2361]
When trying Syncthing 0.11.26, the first screen (http://127.0.0.1:8080/) has these problems:

1. English reports as expanded, when it should default to collapsed since the list is collapsed by default.
If I expand and collapse it, it reports as expected.
I think the fix here is to just default to aria-expanded="false", not true.
2. Upon first loading the page, Actions doesn't report as collapsed even though I can expand it. It only gets aria-expanded="false" when I expand and collapse it for the first time.
That, too, should default to aria-expanded="false".
3. After adding a folder, there's no indication that the folder is expandable. If I press enter on one, I get more info such as the path.

**Comment by marrie** [comment]
Agreed. I've been having t the  same access issues for a while now.

**Comment by derekriemer** [comment]
These will be fixed with #3297

**Comment by AudriusButkevicius** [comment]
Superseded by #3297
