### ISSUE TITLE
wired layout

### ISSUE THREAD

**Issue by Eddy2909** [syncthing/syncthing#2363]
I often got the following layout after login but before accepting the self signed certificate.. maybe a cache problem?
![wired_layout](https://cloud.githubusercontent.com/assets/12877411/10360764/6f0287be-6da3-11e5-907c-d15b7d66cea7.JPG)

**Comment by AudriusButkevicius** [comment]
Angular app hasn't yet bound to the scope, probably because your browser is slow, or syncthing is slow at providing files because its doin something.

**Comment by Eddy2909** [comment]
this happens almost everytime after standby (with chrome @ a win7 64bit AMD FX8320 eightCore pc with 8GB ram on syncthing running on my desktop pc and on my (linux64 wheezy) cloud device. 
Is chrome maybe displaying the layout out of the cache before accepting the real connection via ssl exception?

**Comment by AudriusButkevicius** [comment]
Potentially. Its easy to fix though, just hide the template tilljavascript kicks in.

**Comment by dcarosone** [comment]
On resume, syncthing may be in the midst of restarting, and not responding
to GUI requests, and chrome seems to have cached the HTML but maybe not the
js

**Comment by calmh** [comment]
We do hide the template until JS kicks in. This is probably a different issue - caching? Closing, if there's somethign interesting we should fix in the javascript console for example, reopen.
