### ISSUE TITLE
Syncing folders list "Out of Sync" in GUI instead of "Out of Sync items". Affects translations

### ISSUE THREAD

**Issue by mateon1** [syncthing/syncthing#2364]
As seen in the below picture, when you open up details for a folder in the web GUI, you see "Out of Sync", instead of "Out of Sync Items".
This affects translations, such as Polish, where "Out of Sync" is used as "Lost Sync", wheras "Out of sync items" is used as "Unsynchronized items".
![Picture of a folder's details during synchronization, "Shared with" device name and last file received are blurred](http://i.imgur.com/fX99Tll.png)

**Comment by calmh** [comment]
Isn't this rather up to the translation to be correct for the intended context? I'm not sure duplicating "items" (as it exists on the right side in the english version) is the right solution.

**Comment by mateon1** [comment]
It isn't possible, as "Out of Sync" is used for both to denote the items that are syncing, and when an error occurs that makes a folder unable to sync, such as a folder unable to get deleted. The Polish translation can't make both usages correct - the current translation is correct for the second case, but not for the first. I can't think of any that would be appropriate in both contexts.

**Comment by uok** [comment]
I agree with @calmh that the translations should always be made in context and not change the strings. For example "Out of sync" can also be "not synced", "not in sync", etc. Translations don't (can't) have to be 100% perfect, but it has to be clear to the user. If the folder status on top of the panel is "out of sync" the label "out of sync" in your screenshot IMHO has the same meaning/translation

**Comment by calmh** [comment]
Ah. So the problem here isn't really that the "out of sync" label is incorrect by itself, but that we're using the same label in two different contexts. I see... That's something we should fix somehow for sure.
