### ISSUE TITLE
Doesn't handle peers changing IP address gracefully

### ISSUE THREAD

**Issue by awilkins** [syncthing/syncthing#2366]
Use case : syncing my big work folder for the first time

* Realise that this is going to take ages over WiFi
* Plug my laptop into a cable
* Syncthing continues to sync over WiFi
* Disable WiFi
* Syncthing stops syncing
* Restart Syncthing
* The peer that the laptop was syncing from now rejects all the connections at the TLS handshake stage
* Restart the other peer as well
* Syncing continues

Ideally, it should cope better with machines moving between IP addresses. Or was I just too impatient?

**Comment by AudriusButkevicius** [comment]
You didn't let the old connection timeout, hence it was refusing because it was thinking it was already connected.
