### ISSUE TITLE
Simpler remote web sync

### ISSUE THREAD

**Issue by stdav** [syncthing/syncthing#2367]
I read the FAQ on remote web, ssh and all ; understood close to nothing about it and I would like to synchronize folders with people overseas who are even less technical than me ; could you provide with a simple way to do so ; I like Syncthing better than Bittorrent Sync and I wish it would handle syncing beyond home network without needing a PHD on network technology.

**Comment by marrie** [comment]
Have them open the appropriate port, read the documentation on the firewall, then have them add your computer id, you except, and choose the folders you want to share. They  then have to accept the folders and it should work.. I know someone who can't even get that to work as they don't understand the concept of a local internal web  browser, and are looking at the Github page instead

**Comment by stdav** [comment]
Sorry. Too technical...

What I need is a step by step description of how to....

Better yet, have the GUI do it for me like it does for sync within home network.

Thank you though.

Sent from Yahoo Mail on Android

**Comment by AudriusButkevicius** [comment]
Issue tracker is for issues. If you just need help, please use the forums. 

There are some videos on the internet explaining how things work etc.
Sadly just like every piece of software ever written by humans, there is always some entry bar of being able to use it.

Just like Excel, not everyone is able to sit down and start writing formulas straight away, and are forced to do their own research into what the functions do or read the manual. 

Same way, if it just doesn't work out of the box, you'll have to do your research to make it work, or ask for help in the forums.

**Comment by stdav** [comment]
I beg to differ ; there are other sync software out there that do not require learning how to open a port, initiate an SSH session or mess around with the firewall ; these are the kind of things you can do in your sleep so you take it for granted but I never had to jump loops to setup Bittorrent sync and if you are serious about making this a competitive software then a new feature (not a help file) will be needed to streamline sync to other networks. Going back to you analogy with Excel, when a user fools around with Excel, they do not risk to compromise the security of their home network by trial and errors ; finally this forum is not just for issues ; it is also for feature request ; my request is for a simpler sync across networks ; I might be able to figure it out but some of the people I want to sync with might never be able to tinker with ports, SSH and firewalls even if they tried for a thousand years...

**Comment by AudriusButkevicius** [comment]
The reason why you need to do these things, is because there is no other way around it.
We don't ask you to open up firewall ports because it's fun for us to do so.
It will simply not work if you don't do that.

**Comment by stdav** [comment]
Thank you for the  clarification and sorry for my ignorance....

Sent from Yahoo Mail on Android
