### ISSUE TITLE
Renice to higher nice value after start

### ISSUE THREAD

**Issue by miclill** [syncthing/syncthing#2374]
I'm just doing the initial scan of ~100GB. It's pretty fast but my system could be more responsive while syncthing is working. Maybe Syncthing should renice itself to about 5 after startup?

**Comment by AudriusButkevicius** [comment]
We can predict what sort of environment we are running in.
Perhaps it's a server dedicated for syncthing?
Perhaps it's my RPI doing a ton of other things?

This should be users responsibility.
Also nice makes no sense in windows, et al.

**Comment by jkufner** [comment]
Also there is `ionice`, which is much more useful with Syncthing than `nice`.

**Comment by AudriusButkevicius** [comment]
This is effectively dup of #1455

**Comment by miclill** [comment]
Ah yes, I searched but didn't find it. Sorry and thanks.
