### ISSUE TITLE
panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by JeanOlivier** [syncthing/syncthing#2376]
I recently started to get this error. Rebooting fixes it for a few minutes. Simply restarting syncthing seems to simply do a start-crash-restart loop. It only happens on one of my devices, the others report the crashed one as disconnected.

I'm using synchthing v0.12.0-beta3, Linux (64 bit), the device it crashes on is running on a derivative of Ubuntu 14.04 I believe.

Log file: http://pastebin.com/10ywFcn6

Thank you!

**Comment by AudriusButkevicius** [comment]
This was fixed, check closed issues.
