### ISSUE TITLE
Log or audit gui login failures

### ISSUE THREAD

**Issue by tylerbrazier** [syncthing/syncthing#2377]
I'd like to have syncthing listening on 0.0.0.0 on my VPS and it would be nice to know if somebody is trying to get in. I'd be willing to work on this but I don't know if this should be an auditable event or just logged to stdout?

**Comment by AudriusButkevicius** [comment]
I guess its something we should print to stdout when running with -verbose or -audit

**Comment by calmh** [comment]
Yeah, I'd suggest generating an event for it. That will be picked up by default by the audit file (when enabled), and printed when run with -verbose (if added to verbose.go).

**Comment by tylerbrazier** [comment]
Ok, I'll work on this and create a PR when it's ready

**Comment by AudriusButkevicius** [comment]
Brilliant! Feel free to ask any questions.

**Comment by tylerbrazier** [comment]
How does this sound for functionality: have a new event type called LoginFailed with a data property of e.g.:

    "data": {
        "username": "some_wrong_user",
        "password": null
    }

The password would always be null if the username is wrong since the code fails early. If the username was correct, `password` will always have a value and you would know who somebody is attempting to log in as. Thoughts?

**Comment by AudriusButkevicius** [comment]
I think we should not leak the password, though having an event is reasonable.

**Comment by tylerbrazier** [comment]
Good point, so `data` would contain only the username then? That way, even with just that information, you would still be able to determine whether the login attempt entered a bad username or a bad password, as long as you know what the correct username is.
