### ISSUE TITLE
high data usage even with low repository updates

### ISSUE THREAD

**Issue by primijos** [syncthing/syncthing#2382]
Hi,

I'm using Syncthing 0.11.22 included in Syncthing-android 0.6.6 and I've noticed very high data usage even when data in the repositories is seldom updated. I've three repositories configured in my android device (LG Nexus 5 right now with Android 6), one of them empty, the second one with just one file not updated since january 2015, and the third one corresponding to the DCIM/Camera folder in Android.

This last repository is the only updated in the current month (october 2015). I've accounted around 20 new files (pictures and videos) that, globally, make less than 80MB. Per the Android Settings data usage activity, Syncthing appears as having transferred a total of 778MB from october 1st to october 14th (today) via mobile plan. Wifi data usage is 1.5GB in the last 30 days (data here is not aligned with mobile data date intervals). That looks like a lot -specially the mobile data, which is finite and expensive- for just 80MB updated.

Does anybody know if those figures make sense?

Syncthing appeared also as one of the top cpu-eating apps, so I decided to extend the update checking interval from 60s to 120s. That -looks- made it less cpu-hungry, but data usage patterns looks more or less the same no matter the update period, and that looks like something to check, since updating 80MB and update-checking translating in aprox X10 traffic looks like a lot...

**Comment by AudriusButkevicius** [comment]
It exchanges the whole index as it connects which is relative to the total size of data handled, so frequently timing out connections/network switching can cause it to exchange a whole lot of indexes, which as a result can make it add up.

Also, do you have more than one android device involved?

**Comment by primijos** [comment]
No, I don't have any other Android device involved. Those repositories are
only shared with three Linux (Ubuntu 14.04) computers, no other mobile
device around.

From your comment, looks like normal behaviour. Perhaps that normal
behaviour should be improved in the presence of mobile data plans?
Bug/request feature?

Best,
Jose

**Comment by AudriusButkevicius** [comment]
Its a duo of #438 in that case.
