### ISSUE TITLE
Failure to delete devices

### ISSUE THREAD

**Issue by KevinBEvv** [syncthing/syncthing#2387]
I had a couple computers running syncthing on a couple computers that had untimely hard drive deaths.  I have tried deleted the defunct devices on other computers syncthing's webGUI's, but it always fails and the devices remain in the list.   I then edit the config.xml with a text editor removing all the appropriate lines, and it STILL persists in the device list.

**Comment by chucic** [comment]
Are you using introducer feature?

**Comment by KevinBEvv** [comment]
That is perhaps the problem.  I will track that down for certain.  Thanks.

**Comment by KevinBEvv** [comment]
Closing
