### ISSUE TITLE
global discovery v12beta4

### ISSUE THREAD

**Issue by cedricbrx** [syncthing/syncthing#2389]
HI,

When global discovery is enabled on my 2 PCs the 2 nodes are not finding each others. When i disabled global discovery on both of them (only local discovery is enabled) then the nodes connect within 10 seconds.
Any idea?

**Comment by AudriusButkevicius** [comment]
From what I am reading, in both cases they connect, so whats the issue?

**Comment by cedricbrx** [comment]
sorry, when global discovery is on, they are not connecting

**Comment by AudriusButkevicius** [comment]
This makes no sense, as global discovery is just a supplement, not a replacement.

**Comment by calmh** [comment]
It's possible this could be caused by having no connectivity to the discovery servers and us lacking a timeout. That could block the discovery lookup call, preventing is from returning local discovery results.
