### ISSUE TITLE
files & folders not updating

### ISSUE THREAD

**Issue by chrisp61** [syncthing/syncthing#2390]
Hi
After v012.0-beta4 upgrade, which solved my issue #2384 (syncthing crashing on XP machine); neither my old XP desktop or new win10 laptop will update their Syncthing folders even though everything appears to be working normally!

I've tried dropping new files and folders into Syncthing folders on each machine and they don't appear to be updating (the Global and Local States stay the same). Also when I select "Rescan" or "Rescan All" it doesn't appear to do anything. The scan process ticks away at it's normal 60 second interval saying everything is "up-to-date" but not true!

Any suggestions?

copied log from XP machine below

[TZ2RH] 17:47:17 INFO: syncthing v0.12.0-beta4 "Beryllium Bedbug" (go1.4.2 windows-386 default) unknown-user@syncthing-builder 2015-10-16 00:29:37 UTC
[TZ2RH] 17:47:17 INFO: My ID: TZ2RHBU-5G4WQFK-CNBMQ5K-7AXAIXB-KKP3DQP-DJGZO45-JORWP7R-PL64MAE
[TZ2RH] 17:47:18 INFO: Database block cache capacity 8192 KiB
[TZ2RH] 17:47:18 INFO: Starting deadlock detector with 20m0s timeout
[TZ2RH] 17:47:27 OK: Ready to synchronize accounts (read-write)
[TZ2RH] 17:47:27 OK: Ready to synchronize default (read-write)
[TZ2RH] 17:47:31 OK: Ready to synchronize electrical-general (read-write)
[TZ2RH] 17:47:32 OK: Ready to synchronize insurance (read-write)
[TZ2RH] 17:47:33 INFO: Completed initial scan (rw) of folder default
[TZ2RH] 17:47:36 INFO: Using discovery server https://discovery-v4-1.syncthing.net/?id=SR7AARM-TCBUZ5O-VFAXY4D-CECGSDE-3Q6IZ4G-XG7AH75-OBIXJQV-QJ6NLQA
[TZ2RH] 17:47:36 INFO: Using discovery server https://discovery-v4-2.syncthing.net/?id=AQEHEO2-XOS7QRA-X2COH5K-PO6OPVA-EWOSEGO-KZFMD32-XJ4ZV46-CUUVKAS
[TZ2RH] 17:47:36 INFO: Using discovery server https://discovery-v4-3.syncthing.net/?id=7WT2BVR-FX62ZOW-TNVVW25-6AHFJGD-XEXQSBW-VO3MPL2-JBTLL4T-P4572Q4
[TZ2RH] 17:47:36 INFO: Using discovery server https://discovery-v6-1.syncthing.net/?id=SR7AARM-TCBUZ5O-VFAXY4D-CECGSDE-3Q6IZ4G-XG7AH75-OBIXJQV-QJ6NLQA
[TZ2RH] 17:47:36 INFO: Using discovery server https://discovery-v6-2.syncthing.net/?id=AQEHEO2-XOS7QRA-X2COH5K-PO6OPVA-EWOSEGO-KZFMD32-XJ4ZV46-CUUVKAS
[TZ2RH] 17:47:36 INFO: Using discovery server https://discovery-v6-3.syncthing.net/?id=7WT2BVR-FX62ZOW-TNVVW25-6AHFJGD-XEXQSBW-VO3MPL2-JBTLL4T-P4572Q4
[TZ2RH] 17:47:43 INFO: Device AEARAOK-JUMQ77D-EJAFPJH-T3IVRYW-AWVRXC7-QRISF3I-BT53NQM-U6UINQI is "CHRIS-LAPTOP" at [dynamic]
[TZ2RH] 17:47:43 INFO: Device SWOB7TD-QVHMIJ7-2BJRNIL-I763JOJ-7ISDTOM-4FY4YQS-D22E347-HDQMTQ6 is "chrisp-computer" at [dynamic]
[TZ2RH] 17:47:43 INFO: Device TZ2RHBU-5G4WQFK-CNBMQ5K-7AXAIXB-KKP3DQP-DJGZO45-JORWP7R-PL64MAE is "NUMBER1" at [dynamic]
[TZ2RH] 17:47:43 INFO: Starting usage reporting
[TZ2RH] 17:47:43 INFO: New UPnP port mapping: external port 65169 to local port 22000.
[TZ2RH] 17:47:46 INFO: Completed initial scan (rw) of folder insurance
[TZ2RH] 17:47:47 INFO: API listening on 127.0.0.1:8384
[TZ2RH] 17:47:47 INFO: GUI URL is http://127.0.0.1:8384/
[TZ2RH] 17:47:49 INFO: Established secure connection to AEARAOK-JUMQ77D-EJAFPJH-T3IVRYW-AWVRXC7-QRISF3I-BT53NQM-U6UINQI at 192.168.1.4:1081-192.168.1.24:22000 (direct-dial)
[TZ2RH] 17:47:49 INFO: Device AEARAOK-JUMQ77D-EJAFPJH-T3IVRYW-AWVRXC7-QRISF3I-BT53NQM-U6UINQI client is "syncthing v0.12.0-beta4"
[TZ2RH] 17:47:49 INFO: Device AEARAOK-JUMQ77D-EJAFPJH-T3IVRYW-AWVRXC7-QRISF3I-BT53NQM-U6UINQI name is "CHRIS-LAPTOP"
[TZ2RH] 17:49:48 INFO: Completed initial scan (rw) of folder accounts
[TZ2RH] 17:50:05 INFO: Completed initial scan (rw) of folder electrical-general
[TZ2RH] 18:31:54 INFO: Connection to AEARAOK-JUMQ77D-EJAFPJH-T3IVRYW-AWVRXC7-QRISF3I-BT53NQM-U6UINQI closed: WSARecv tcp 192.168.1.4:1081: The specified network name is no longer available.
[TZ2RH] 18:34:19 INFO: Established secure connection to AEARAOK-JUMQ77D-EJAFPJH-T3IVRYW-AWVRXC7-QRISF3I-BT53NQM-U6UINQI at 192.168.1.4:1546-192.168.1.24:22000 (direct-dial)
[TZ2RH] 18:34:19 INFO: Device AEARAOK-JUMQ77D-EJAFPJH-T3IVRYW-AWVRXC7-QRISF3I-BT53NQM-U6UINQI client is "syncthing v0.12.0-beta4"
[TZ2RH] 18:34:19 INFO: Device AEARAOK-JUMQ77D-EJAFPJH-T3IVRYW-AWVRXC7-QRISF3I-BT53NQM-U6UINQI name is "CHRIS-LAPTOP"
[TZ2RH] 18:34:31 INFO: Connection to AEARAOK-JUMQ77D-EJAFPJH-T3IVRYW-AWVRXC7-QRISF3I-BT53NQM-U6UINQI closed: WSASend tcp 192.168.1.4:1546: An existing connection was forcibly closed by the remote host.
[TZ2RH] 18:34:51 INFO: Established secure connection to AEARAOK-JUMQ77D-EJAFPJH-T3IVRYW-AWVRXC7-QRISF3I-BT53NQM-U6UINQI at 192.168.1.4:1555-194.126.249.21:443 (relay-accept)
[TZ2RH] 18:34:54 INFO: Device AEARAOK-JUMQ77D-EJAFPJH-T3IVRYW-AWVRXC7-QRISF3I-BT53NQM-U6UINQI client is "syncthing v0.12.0-beta4"
[TZ2RH] 18:34:54 INFO: Device AEARAOK-JUMQ77D-EJAFPJH-T3IVRYW-AWVRXC7-QRISF3I-BT53NQM-U6UINQI name is "CHRIS-LAPTOP"
[TZ2RH] 18:35:13 INFO: Connection to AEARAOK-JUMQ77D-EJAFPJH-T3IVRYW-AWVRXC7-QRISF3I-BT53NQM-U6UINQI closed: switching connections
[TZ2RH] 18:35:14 INFO: Established secure connection to AEARAOK-JUMQ77D-EJAFPJH-T3IVRYW-AWVRXC7-QRISF3I-BT53NQM-U6UINQI at 192.168.1.4:22000-192.168.1.24:57325 (direct-accept)
[TZ2RH] 18:35:14 INFO: Connection to AEARAOK-JUMQ77D-EJAFPJH-T3IVRYW-AWVRXC7-QRISF3I-BT53NQM-U6UINQI closed: use of closed network connection
[TZ2RH] 18:35:15 INFO: Connection to AEARAOK-JUMQ77D-EJAFPJH-T3IVRYW-AWVRXC7-QRISF3I-BT53NQM-U6UINQI closed: use of closed network connection
[TZ2RH] 18:35:26 INFO: Established secure connection to AEARAOK-JUMQ77D-EJAFPJH-T3IVRYW-AWVRXC7-QRISF3I-BT53NQM-U6UINQI at 192.168.1.4:22000-192.168.1.24:57330 (direct-accept)
[TZ2RH] 18:35:26 INFO: Device AEARAOK-JUMQ77D-EJAFPJH-T3IVRYW-AWVRXC7-QRISF3I-BT53NQM-U6UINQI client is "syncthing v0.12.0-beta4"
[TZ2RH] 18:35:26 INFO: Device AEARAOK-JUMQ77D-EJAFPJH-T3IVRYW-AWVRXC7-QRISF3I-BT53NQM-U6UINQI name is "CHRIS-LAPTOP"

**Comment by AudriusButkevicius** [comment]
Please start a thread on the forums, as its most likely a configuration issue. Provide screenshots of the web ui from both sides. Beta4 is just beta3 + crash fix so I doubt its that.
