### ISSUE TITLE
Entering negative numbers in advanced config is impossible

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2392]
As soon as a "-" is typed into a numeric field the entire field disappears from the dialog. WTF?

**Comment by uok** [comment]
Holy :cow:, you are right!  This is one of the weirdest bugs I have seen :crystal_ball: 
(but setting to negative value with up/down arrows seems to work)

**Comment by marrie** [comment]
Why would one want to enter a negative number in to the config dialogue? So far in my short time with syncthing I have not had the need to do such.

**Comment by wweich** [comment]
Because it was suggested by a dev.  To disable scan progress you need to set the interval to -1 as 0  will just cause default.

**Comment by marrie** [comment]
Oh. Yeah I missed that a while ago. Lol!  Well, hope this is fixed in a minor version for those of us who want to disable  a folder scan.

**Comment by calmh** [comment]
Yeah there are valid cases for it. I think the issue is that there is a parse error somewhere when what was previously a number typed value becomes "-" and is no longer a number.

**Comment by marrie** [comment]
In that case I per pose  a merge between this and other tickets regarding such matters, as to me the issue is the same.

**Comment by calmh** [comment]
Which other tickets? I've missed those.

**Comment by marrie** [comment]
Actually that was meant for another issue I was  replying to. For some reason my mail program broke in a big way. Sorry. Please disregard

Take care.
