### ISSUE TITLE
Syncthing filename too long issue

### ISSUE THREAD

**Issue by KeiroD** [syncthing/syncthing#2393]
Hi,

I'm currently using SyncThing on a Linux Mint laptop and a dual-booting Windows/Fedora 22 PC.

Right now, SyncThing is currently set up on the LM laptop and Windows side of the PC.

Linux Mint: v0.11.26, Linux (64 bit)
Windows 7 x64 Professiona: v0.11.26, Windows (64 bit)

The error from my LM laptop says this:

```
[5ZMYH] 16:01:50 INFO: Puller: final: open /home/keiro/Sync/Newstuff/Spice and Wolf Image Pack/.syncthing.Konachan.com - 49831 animal_ears craft_lawrence gray_hair horo long_hair orange_hair red_eyes short_hair spice_and_wolf tail wolfgirl.jpg.tmp: file name too long
[5ZMYH] 16:01:50 INFO: Puller: final: open /home/keiro/Sync/Stuff/Music/.syncthing.The Massed Bands of Scottish Division - Prince Charles Welcome - To Lochaber - The Mingulay Boat Song - The Silver Spear - The Curlew - Captain Horne - Macfarlane's Reel - O'Leudh.mp3.tmp: file name too long
[5ZMYH] 16:01:50 INFO: Folder "default" isn't making progress. Pausing puller for 1m0s.
```

and continues to do so. I've also done a Google search. Setting `\\?\c:\my\folder\path` as per [this thread](https://forum.syncthing.net/t/file-name-too-long/1443/9) for Windows seems to do the trick. The Windows SyncThing status on the lower right for my laptop says 100% whereas my laptop says there's 21 items that're too long and will be continually retried until the error's resolved.

```
 The following items could not be synchronized. They are retried automatically and will be synced when the error is resolved.
Konachan.com - 33481 animal_ears brown_hair craft_lawrence forest gray_hair horo long_hair red_eyes short_hair spice_and_wolf wolfgirl.jpg 	file name too long
Konachan.com - 46056 animal_ears apple ayakura_juu craft_lawrence gray_hair grey_eyes horo long_hair orange_hair red_eyes short_hair spice_and_wolf tail wolfgirl.jpg 	file name too long
```

and so on for all 21 items. How do resolve on the laptop?

**Comment by calmh** [comment]
This error comes from Linux, but I'm not sure why. There's a limit of 255 bytes to a file name (not the whole path, but the actual file name component) that you seem to be running up against. But your file name is "only" around 200 characters. Are you running some home directory encryption or something? If so, that's probably where the error comes from.

**Comment by KeiroD** [comment]
Sorry for the late response, but yes. Yes, I am indeed running home directory encryption.

I take it that this is a limitation of such? If so, how do resolve?

**Comment by AudriusButkevicius** [comment]
Use short names, as its a limitation of the OS not a syncthing limitation, so not much we can do. Syncthing needs a few bytes to add .tmp and so on, and I think its perfectly acceptable to ask for that.

**Comment by KeiroD** [comment]
Alrighty. I'll remove those items and try renaming them so it's shorter. I think this shouldn't be too much of an issue. I'll check and make sure other items don't hit that limit, as well.

Thanks for creating such an awesome product!
