### ISSUE TITLE
Upgrade on Linux with multi instances.

### ISSUE THREAD

**Issue by bluewavenet** [syncthing/syncthing#2396]
I have a number of laptops running opensuse 13.2 with the same set of users on each machine and an instance of syncthing running for/as each user on every machine started by systemd as the user on boot up.

It all works beautifully and any user can log in to any machine and find everything synced up.

The gui upgrade available button does not work (of course - as it is running as the user).
A typical error is as follows:
2015-10-20 13:08:45: upgrading: open /usr/bin/syncthing564113422: permission denied

This is purely cosmetic and I can always disable the upgrade.

However is it possible to make a more user-friendly/meaningful error message?  On a large rollout in a business environment I would have it switched off to prevent the message, but is there a better way?

**Comment by AudriusButkevicius** [comment]
Why do you want the message? Why don't you just disable upgrades?

**Comment by bluewavenet** [comment]
Having the users doing an upgrade for me is attractive. But no I do not want the message and as I said it can be disabled.
If the message can easily be changed to a more user-friendly message like "contact system admin for an upgrade" or somesuch then fine. Ultimately a way for it to be rolled out automatically would be nice.

I was just wondering if anyone had any ideas. 

Syncthing works brilliantly in the way I have set it up, I am looking for more ways to lever it into IT departments ;) Ways to make it look like the tight, slick, efficient package it actually has become!

**Comment by AudriusButkevicius** [comment]
Right, if you want users to be able to upgrade put the binary in ~/bin.

I am my own system administrator, so telling me to contact myself without and explanation about what went wrong makes little sense.

The message can already be disabled, you just need to read the docs.

**Comment by bluewavenet** [comment]
@AudriusButkevicius - This was not intended as a support request. AND I have read the docs thankyou. Syncthing is extremely good and does everything I would want it to do. But it needs credibility, polish and maturity to be taken seriously by the general public, particularly in the business area where its functionality is most definitely needed.

**Comment by AudriusButkevicius** [comment]
You still haven't properly defined what you are after.
