### ISSUE TITLE
Loading bar or sth. similar

### ISSUE THREAD

**Issue by zyx3nzh7** [syncthing/syncthing#2398]
I run syncthing on the raspberry. When active the webinterface needs ~30sec to have current information but you can't tell it's fetching data.
I would like to see something like https://chieffancypants.github.io/angular-loading-bar/
added so users know it's loading in the background.

**Comment by calmh** [comment]
This'll be fixed soon enough so the data is more or less instantly available, at which point this won't be necessary any more. :)
