### ISSUE TITLE
Refactor connections

### ISSUE THREAD

**Issue by 4nd3r** [syncthing/syncthing#2399]
Not sure if duplicate or already mentioned somewhere or developers have better idea(s),
but I have a dream:

I have number of devices and they are all "sit" behind firewall. Some devices move around, some don't - either way I'm not interested opening any ports. Because of reasons I don't want to use public relays and prefer hosting my own relay(s). It would be nice to have ability to define device address as relay://host:port, since devices identify each other using ID anyway... right?

Right now, if I understand correctly, syncthing try to reconnect directly after some time, but my devices never will be directly accessible.

**Comment by AudriusButkevicius** [comment]
So if I understand correctly you are trying to get rid of devices connecting directly?

**Comment by 4nd3r** [comment]
Yes.

**Comment by AudriusButkevicius** [comment]
Why does that matter?

**Comment by 4nd3r** [comment]
Evil corporate firewall admins don't love port forwarding.
Same for many WiFi providers.

And hosting own relaysrv is faster.
Of course, contributing to public pool would be nicer, but that's story for another day.

**Comment by AudriusButkevicius** [comment]
Well, nobody is suggesting to forward ports. My question is, why does it matter that a device tries to establish a direct connection every now and then?

**Comment by 4nd3r** [comment]
Oh, sorry, l misunderstood.

That really doesn't matter... maybe unneccesary noise in traffic logs, but I can live with that.
That last thought was just a marginalia.

I'm probably asking wrong questions,
but maybe the right-ish question I want to ask, is,
if we can cut away discosrv and always use relaysrv?
Becuase there's nothing to "discover", because I know how my devices connect.

**Comment by AudriusButkevicius** [comment]
So i had this idea to refactor connections, which basically falls under this ticket. Probably needs @calmh's head too but the basic principle goes as follows:

1. Move relay:// dynamic:// tcp:// all under listen/device addresses.
2. Move UPnP to the specific tcp:// handler, and not main()
3. Have a ConnectionProvider or what ever interface which exposes the bits we are interested (such as Address() showing UPnP port for TCP, or showing the current relay chosen in case of dynamic relays)
4. Nuke all the relay fields from all messages.

This way you will be able to specify a relay as the only listen address or as a device connection address.

The only problem I feel with this, is that we will no longer be able to expose connection type specific settings (for example a stun server for future dst connection), unlsss we are explicitly ebcoding then in the URI (which I am sort of fine with). @calmh?

**Comment by calmh** [comment]
Sounds sane enough.

**Comment by calmh** [comment]
As to the original problem case, I think this could be handled by configuring each of your devices to:

- Use a specific relay server you set up yourself (not the global pool)
- Disable global discovery
- Enable relaying-without-global-discovery (it's an advanced setting)

Without global discovery, there'll be no attempts at direct connections. Unless the devices are beside each other on the same LAN, in which case you *want* a direct connection.

**Comment by 4nd3r** [comment]
1. disabled global discovery
2. checked `relayWithoutGlobalAnn` in advanced configuration
3. stopped syncthing
4. opened `~/.config/syncthing/config.xml`
5. modified `<relayServer>relay://x.x.x.x:22067/?id=XXXX</relayServer>`
6. started syncthing

In gui I see `Relays 1/1`, but devices are disconnected.

**Comment by AudriusButkevicius** [comment]
Are they on the same lan? Otherwise they won't be able to discover that fact that the other peer is available on the relay. So you need either local discovery or global discovery

**Comment by 4nd3r** [comment]
no, different networks. going to stay with global discovery for now.
and wait for 0.13 with refactored connections... or...
thanks.

**Comment by calmh** [comment]
Someone needs to retitle this issue or I'm going to close it by mistake at some point :)
