### ISSUE TITLE
Syncthing index database unreasonably large (> 100GB)

### ISSUE THREAD

**Issue by cypress-jfro** [syncthing/syncthing#2400]
I'm using Syncthing to sync ~170GB of data across 6 folders and 13 servers. My index directories are growing to consume 10s of GB, with the largest database at 115GB. This seems unreasonable. Not all of the index directories are this large; several have only grown to 2-4GB.

All but one of the servers are running CentOS 6.4, 64-bit; one is running RHEL 6.5. All are running Syncthing 0.11.17.

I've got the log files from all of the servers, but I don't seem to be able to attach them to this issue.

**Comment by calmh** [comment]
That does seem a tad unreasonable. Anything particular on the boxes where it's largest? The index tracks every file on every connected device, so more connected devices means bigger index... Also, it's highly dependent not only on the amount of data but on the number of files. 170 1GB files is probably fairly compact, 170 million 1KB files is going to suck...

**Comment by cypress-jfro** [comment]
Looks like it's syncing 1.7 million files.

There's nothing obviously special about the machines with largest index directories. I haven't had time today to do a thorough investigation.

Of the 13 servers, 2 of them are only syncing one small folder, so the index on those two is only 12M.

6 of the remaining 11 have indicies ranging from 1.9G to 4.6G, while the over 5 range from 69G to 115G. All 11 are syncing the same 6 folders between them. One server is the master for most of the folders. The master server's index is only 1.9G.

The indicies under 5GB are in line with my expectations. I'm a still a little surprised by the larger ones, especially since they have the same sharing configuration as the others. 

Any ideas for what I can do to track down what might be causing the bloat?

**Comment by arneko** [comment]
....as stated some weeks ago, I have a sample of a unusual big index (*just* 15GB as opposed to a normal 700MB). The indexed data-set is close to 500 GB though.
Would this be helpful at all to analyze the issue?

**Comment by AudriusButkevicius** [comment]
Data set size can potentially be irrelevant compared to file count, but I guess we are interesting in a case where 2 nodes sync the same set of folders with the same set of peers, one has 1GB index, the other one 15GB

**Comment by calmh** [comment]
Do you see crashes or something weird like that on the box with the largest indexes? The database code runs a background compaction operation, it seems like if that is allowed to run, things would be fine...

Do files change a lot? More on the device with the large indexes? There could be a bug leaving old blocks around in the database or something similar.

**Comment by arneko** [comment]
Syncthing crashed regularly with this due to insufficient diskspace. That was before the introduction of the free space limit. The crashing machine (laptop) wasn't even the one with the most connected devices or largest data-set (that'd be my server). Also, there weren't ever many changes. To restart syncthing I needed to clear a little space somewhere else on my drive, syncthing would then immediately shrink the db to its normal size.
How would you like me to give you access to this db? My bandwidth is about 1MB/s, so I guess you're looking forward to a 4-5 hour download

**Comment by cypress-jfro** [comment]
I haven't been seeing crashes, except for one machine where it actually ran out of space to keep the index. Uptimes are all consistent with the restart I did yesterday, before I noticed this issue.

I'm syncing static data (IC Manage/Perforce workspace updated with a cron job). When it does change, changes should only come from the master node. Users don't have permissions to modify the data on the remote servers directly, and source repositories for the master folders appear to be getting < 50 changes per day.

It may be significant that I just added a large folder yesterday (~60GB, 680k files), and it's still syncing to some of the nodes. The nodes are all peers of each other. Is it possible that the differing sync rates are causing some nodes to see lots of changes from multiple peers?

Let me know if there's any particular analysis I can do that would help. I'll do some more digging and post here if I find anything significant.

**Comment by AudriusButkevicius** [comment]
@cypress-jfro no, changes are propagated to everyone, in the same fashion, and only as the files are downloaded, so I doubt it's that.

@arneko get which have the same set of folders/peers in sync and then upload both the large and the small index somewhere, and I will have a look.

**Comment by cypress-jfro** [comment]
Thus far, I've been unable to find anything in particular that sets the machines with large databases apart.

The only correlation I've seen is that machines that have a lot of both upload and download activity tend to have larger databases, but that doesn't hold consistently.

Some of the largest databases have shrunk a little over the last 2 days. One of the smaller ones (4.3G) has grown to become the largest at 107G.

**Comment by calmh** [comment]
So theoretically, for a bunch of devices with the same set of files, all connected to each other, the on disk indexes should be the same... I can whip together a database analysis thing to check it for consistency - blocks that shouldn't be in there, things like that, that might point to what is in there that should be. Or possibly, that there is an issue with the database lib itself. 

Not this weekend though, remind me next week if I forget. :)

**Comment by cypress-jfro** [comment]
Sounds good. I was considering blowing away one of the DBs and seeing how large it got after rebuilding, but I can keep these around for a couple weeks.

I can make copies of the existing databases if you want me to.

**Comment by AudriusButkevicius** [comment]
Keep it around.

**Comment by cypress-jfro** [comment]
Keep around as in "Don't delete them" or as in "make a copy of the current state"?

**Comment by AudriusButkevicius** [comment]
Probably make a copy. I'll try to mash up a dump tool tonight.

**Comment by AudriusButkevicius** [comment]
Download utils from: http://build.syncthing.net/job/syncthing-utils/242/
Then run `stindex -mode dumpsize`, pipe the output to a file (as there will be lots), zip it up and email it to me/calmh. It will contain file names, so you might not want to make it public.

Also, you could do the same thing on some other device which supposedly has the same data set (with the same set of peers), but the index is much smaller.

**Comment by AudriusButkevicius** [comment]
This is the right build, because I am a muppet: http://build.syncthing.net/job/syncthing-utils/244/

**Comment by cypress-jfro** [comment]
I've now run stindex on 3 of my index directories, and I've reached two conclusions:

1) The output is far to large to send via email.
2) stindex changing the database size. The database goes back down to ~4G when I run stindex.

**Comment by AudriusButkevicius** [comment]
1) It's a lot of repeated bytes, so zipped up it should acceptable.
2) This indicates that the database just needed compaction. This happens automatically with syncthing, I think once the database calms down. Or are you saying it stays uncompacted forever?

**Comment by arneko** [comment]
I can confirm that running stindex shrinks the database to its usual size. (First run about 570 MB, second run 632 MB, so this seems to be somewhat flexible)
Note that these large databases were never a permanent problem, I just ran out of space quite often, especially when I had "only" about 10 GB  out of 40 GB of free space left. Also, I never had problems on my micro-servers, that ran on 16 GB SDCards.  

The Output doesn't look very suspicious, mine is 127MB when zipped. Uploading it now, in case you're still interested.
Is it maybe possible for syncthing to invoke a database compaction whenever we hit the minHomeDiskFreePct threshold?

**Comment by AudriusButkevicius** [comment]
I can't comment, as I don't know the database well. Lets see what @calmh has to say. If it shrinks by running stindex then I don't think the indez dump will have anything interesting.

**Comment by cypress-jfro** [comment]
My logs seem to indicate that compaction is happening, even on the large databases. I have seen the large databases shrink some given time, though never by more than 30% (so perhaps from 100G to 60G).

**Comment by AudriusButkevicius** [comment]
As I said, the scenario I am interested is two nodes having same set of data with same set of peers and wildly different db sizes which does not change over time, which would indicate we are leaking db keys.

The database being large and then small etc, just indicates that there is alot of activity happening (deletes) and the compaction doesn't manage to kick in as fast as you'd expect

**Comment by calmh** [comment]
It could also indicate the database isn't getting compacted correctly, perhaps because we're doing continuous writes and not giving it time to happen, or something like that. Can you try the build in

https://github.com/syncthing/syncthing/pull/2512

and see if the database shrinks significantly just after startup?

**Comment by cypress-jfro** [comment]
I'll grab that and see, though the databases already seem to shrink anytime I restart syncthing. I'll post back here later today.

**Comment by cypress-jfro** [comment]
That build does cause the databases to shrink (down to ~3GB) on startup, but after a few hours, the databases have grown back up to the 30G to 90G range, and they're still growing.

**Comment by AudriusButkevicius** [comment]
Another thing which might be interesting is sending a SIGSTOP when the index gets to a large size so see what the database compaction routine is doing.

**Comment by bshafer** [comment]
Could someone add the index size next to the RAM/CPU stats?

**Comment by AudriusButkevicius** [comment]
Why?

**Comment by bshafer** [comment]
Well, when the boot drive is an SSD, the space taken up by the index is a valuable resource just like RAM and CPU.

**Comment by AudriusButkevicius** [comment]
Right, but you can surely check the same thing in other means. This would add no value to most users.

**Comment by AudriusButkevicius** [comment]
With deltaxThe DB size should be more or less stable(or as bit as it needs to be) with 0.14.2 and introduction of delta indexes.
