### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by zrml** [syncthing/syncthing#2407]
AWS S3 support for remote off-site ultimate sync/DR/backup safegurading of your data.
Do you have any plan for this?

I'm all set with the syncing of my devices but a fire or other events could leave me without backup.
If I could have an option to supply a S3 buckets then I know I could sleep even better :-)

AWS officialy supports GO too and there is support for S3 buckets... maybe I should start looking into it.

Syncthing would become VERY interesting then with a strong differentiator element :)

all the best & thank you

**Comment by isdn** [comment]
Hello zrml,

You can use s3cmd via crontab to backup the files.

**Comment by zrml** [comment]
I had not thought of it nor investigated that possibility. 
We need to to think about Windows users and making it easier and integrated in the tool IMO.
anywya, Thanks Denis, I'll definately look at it

**Comment by AudriusButkevicius** [comment]
You can use s3fs or whatever if you want, or just sync to an instance in AWs. Still, don't forget syncthing is not backup, because if one device deletes the files all of them delete it.

Regardless S3 OpenSwift et al are out of scope of syncthing, hence closing.

**Comment by zrml** [comment]
@AudriusButkevicius: thank you for the reminder. It fits my use case perfectly. I'm fine with this closed. However, never say never, as tools, business and competition change ;-)

Thanks to all contributors! I love it already. furthermore, it's written with the language I love...I can't ask for more :-D

**Comment by AudriusButkevicius** [comment]
There is no business here, hence no competition ;)
