### ISSUE TITLE
No UX to help when devices can't find each other

### ISSUE THREAD

**Issue by frabcus** [syncthing/syncthing#2408]
I've just set Syncthing up on a server (not behind NAT) and on an Android phone.

I've added the device IDs each way, but the devices can't see each other.

There is nothing in the syncthing user interface (local web browser, or Android) to tell me what to do next.

I expect clear and well written in context help so I can diagnose it - all the log files and ports, and FAQ of things to try and so on. This will also reduce support, and help people find and fix bugs which stop the product working.

**Comment by AudriusButkevicius** [comment]
Dup #2218
