### ISSUE TITLE
Discovery server count wrong

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#2409]
On android it shows 5/8 with 6 servers defined and all 3 v6 being uncontactable.

**Comment by calmh** [comment]
+ local (ipv4) and local (ipv6)

**Comment by AudriusButkevicius** [comment]
Actually thats a bit confusing. Should we get rid of local discovery servers checkbox and just add multicast:// broadcast:// ?

**Comment by calmh** [comment]
Potentially yes
