### ISSUE TITLE
panic: leveldb/table: corruption on data-block

### ISSUE THREAD

**Issue by donnex** [syncthing/syncthing#2411]
Hi, I've been running Syncthing for about a year. It's been working really fine but today I noticed that my workstation was restarting Syncthing over and over and no files were synced.

When checking the cause I got an error log with a bunch of information. Unfortunately I don't know why this is happening or what to do about it. Any ideas?

I think this could be related to a power outage yesterday. I think it worked just fine before.

I've got three nodes. My workstation syncs to my server and my MacBook also syncs to the same server.

The complete error log: https://gist.github.com/donnex/e1ebb2f88b47f1d4da8c

**Comment by AudriusButkevicius** [comment]
Check for existing closed issues or the forum for answers.
