### ISSUE TITLE
URL for Support is not avalible [502 Bad Gateway]

### ISSUE THREAD

**Issue by 0x8BADFOOD** [syncthing/syncthing#2412]
Click on Link at the bottom of page "Support"

https://forum.syncthing.net/

Returns: 502 Bad Gateway

**Comment by wweich** [comment]
Works for me.
Maybe it was unreachable for a brief moment when you tried.

**Comment by uok** [comment]
all working, please close

**Comment by 0x8BADFOOD** [comment]
Ok. Yes looks like temporary issue. Thanks.
