### ISSUE TITLE
Extension only ("nameless") files won't sync -- pull: no available source device

### ISSUE THREAD

**Issue by sebastianlau** [syncthing/syncthing#2419]
Windows 10 x64, Syncthing 0.11.26   (Probably affects all version of Windows)

Where a file has no name and is an extension only (e.g ".suo"); Syncthing will create the temporary file ("~syncthing~.suo.tmp") but never renames or completes the action.
Funnily enough if you try to do it manually Windows will throw a "You must type a filename" error, but in my case at least, the file is valid and automatically created by Visual Studio 2015..

**Comment by AudriusButkevicius** [comment]
There should be an error when it tries to rename the file in the log.

**Comment by sebastianlau** [comment]
Hmm I wasn't able to see a root cause but clearing the indexes on all devices seems to have fixed it (hence my delay in responding, took a while to reindex the ~20m files!)
Will keep an eye out and close this issue
