### ISSUE TITLE
can't delete device

### ISSUE THREAD

**Issue by Rotkaermota** [syncthing/syncthing#2421]
using: v0.11.26, Windows (64 bit)
There is device in my device list with following info:
name: XABJO6 (due never connected)
last seen: never
address: ?
There is folder ZZZ in my folder list, shared to this device (also shared to other devices).
I try to delete device XABJO6 with following combinations:
1. just delete device XABJO6, restart
2. uncheck folder ZZZ in device XABJO6, restart
3. uncheck device XABJO6 in folder ZZZ, restart
4. uncheck folder ZZZ in device XABJO6, uncheck device XABJO6 in folder ZZZ, restart
5. 2, 3, 4 without restart, delete device XABJO6, restart

After restart device XABJO6 is back and folder ZZZ shared to it.

**Comment by AudriusButkevicius** [comment]
You have some node set to introducer, and it keeps reintroducing the device after restart.
Check the forum or existing issues, this has been discussed before.

**Comment by Rotkaermota** [comment]
So, this mean Introducer feature is buggy.
Right, one of devices was marked as introducer, but XABJO6 device never been paired with introducer.
XABJO6 was never online, so how can introducer introduce it to others?

**Comment by AudriusButkevicius** [comment]
XABJO6 was introduced back by someone else that was online, and who is marked as introducer.
