### ISSUE TITLE
Ignoring files result in "not synced"

### ISSUE THREAD

**Issue by theincogtion** [syncthing/syncthing#2428]
I am ignoring files on one device which are not ignored on the other devices.
This results in the message that the folder are not synced. Due to the fact that I ignored them by purpose it would be better to show that the files are synced.
Problem already discussed here:
https://forum.syncthing.net/t/ignore-files-on-just-one-device/5997

**Comment by AudriusButkevicius** [comment]
This is expected.

**Comment by theincogtion** [comment]
Yes it it but I like to ask to change this behaviour

**Comment by AudriusButkevicius** [comment]
Duplicate of #623 #624 in that case.
