### ISSUE TITLE
Connects using WIFI but not using mobile data

### ISSUE THREAD

**Issue by musclemonkeyraw** [syncthing/syncthing#2429]
Hello,

I have been having difficulty connecting when my android (rooted Moto G 4G) is not connected to WIFI.

I can easily connect to websites using the browser but for some reason syncthing cannot load and if loaded on WIFI and I switch off wifi connection, when attempting to load Web GUi, it says cannot connect to https://127.0.0.1:8384

I am not an expert when it comes to networks etc, so I could be out of my depth here.

Can you help?

Thank you!

**Comment by wweich** [comment]
Wrong Repo: https://github.com/syncthing/syncthing-android
Please check your settings. It is probably set to sync only on Wifi.

**Comment by AudriusButkevicius** [comment]
Also, this seems like a support request, hence no need opening tickets. Try getting help on the forum until someone confirms its a bug.
