### ISSUE TITLE
discoveryFailed.join and relaysFailed.join

### ISSUE THREAD

**Issue by fbreve** [syncthing/syncthing#2431]
5 of 5 Windows 10 x64 machines where I've installed v0.12.0 are showing this error:

![syncthing](https://cloud.githubusercontent.com/assets/7475908/10979890/391fa132-83e6-11e5-8b45-5e1227b68298.png)

A single NAS with Linux 32 bits is working just fine.

Even with the error, the machines seems to be synching just fine, at least in the local network (I didn't update non-local machines yet).

**Comment by AudriusButkevicius** [comment]
Which browser?
Also, can you get the content of the JS console which could have errors

**Comment by fbreve** [comment]
I'm using Synctrayzor.

**Comment by AudriusButkevicius** [comment]
Does the same thing happen when navigating with a normal browser?

**Comment by calmh** [comment]
Cache thing - javascript out of sync with the HTML or something?

**Comment by fbreve** [comment]
It is working on Chrome and Edge.
So, it's something on Synctrayzor browser.

**Comment by AudriusButkevicius** [comment]
Right, I guess you should open a bug there.

**Comment by fbreve** [comment]
I did that. Thank you.
