### ISSUE TITLE
Put relay setting in main settings

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#2433]
Since this is a really great feature I suggest to put it into the main settings like this

![newsettings](https://cloud.githubusercontent.com/assets/9367272/10993747/8e923d2e-8471-11e5-806e-ee607cc08ccd.png)

**Comment by AudriusButkevicius** [comment]
I am refactoring connection, which means a relay will become just a listen address.

**Comment by uok** [comment]
Ok, I just wanted to find a way to quickly enable/disable relaying, e.g. at home I don't need relaying

**Comment by calmh** [comment]
Yeah in the meantime we should expose this as a normal setting I think. People will legitimately want to disable it.

**Comment by Eddy2909** [comment]
why is relaying enabled per default?
isnt this a feature only for users who have connection problems (thru firewall etc)?

**Comment by AudriusButkevicius** [comment]
It's only used when no direct connection is possible.

**Comment by canton7** [comment]
The people who *need* a relay are those who probably won't know that relaying exists: i.e. the msot technologically incompetent people who are new to Syncthing, and haven't yet invested the time to learn how it works and what you can do with it.

It needs to be enabled by default.
