### ISSUE TITLE
"Uncomplicated FireWall" (UFW) Integration

### ISSUE THREAD

**Issue by Stefan-Code** [syncthing/syncthing#2435]
It would be a nice to have an application preset for [ufw](https://help.ubuntu.com/community/UFW) in the `etc` folder of the releases (like for the startup scripts).
The file could look like this:
```ini
[syncthing]
title=Syncthing   
description=Sycthing file synchronisation
ports=22000/tcp|21027/udp
```
So (after copying it to `/etc/ufw/applications.d/`) opening the needed ports is as simple as
```
sudo ufw allow syncthing
```
The file could also be automatically added when installing with a package manager I guess.

**Comment by AudriusButkevicius** [comment]
Feel free to make a PR, especially given you've already done most of the work.

**Comment by xHN35RQ** [comment]
thanks for this!!
