### ISSUE TITLE
Update should restart syncthing

### ISSUE THREAD

**Issue by davidbaumann** [syncthing/syncthing#2438]
Hello,

I am running Ubuntu 15.10, using the official apt repository.

So for the last 2 updates, I had this issue.

So now, syncthing updated to version 0.12. After opening the web interface, it was still showing 0.11, so I did restart it. After the restart, it was showing 0.12.

I think it's dangerous, to replace the files but not stop before, and start after.

David.

**Comment by calmh** [comment]
The dpkg packages don't actually include any startup scripts though, so we wouldn't know how to restart the service. This depends on whether the system is using systemd, upstart, runit or something else...

**Comment by davidbaumann** [comment]
Do you think there's need to change this? I guess it's dagerous to just let the daemon run, while the executable file is being replaced... Had some strange issues running chromium while there was an update installed for it, but chromium will not destroj my files, I think...

**Comment by AudriusButkevicius** [comment]
Well there is nothing to change, as we don't provide the scripts which start syncthing with the package, so we have no clue how to restart it while installing the new package. I don't think replacing a file while its running is dangerous,we've been doing that for ages now.

**Comment by KarlHegbloom** [comment]
It won't hurt anything on Linux or Mac but I don't know anything about
Windows. On Unix the file name is associated with an inode, and you can
remove the name while a file is open,  and continue to read from the file.
When it's closed,  it really goes away, freeing the inode and disk blocks.
So if you replace a program binary with rm or mv then create a new file, it
won't change the file the running program has open to execute. Restarting
will perform the file name to inode lookup again, starting the new copy and
releasing the old.

**Comment by AudriusButkevicius** [comment]
We dob't provide an apt repo for windows.

**Comment by davidbaumann** [comment]
So, as soon as the file is being overwritten by another file (horrible thought) or wiped by trim, we don't know what will happen?
I just try to understand.

**Comment by calmh** [comment]
The file is replaced on upgrade, not overwritten (there's a subtle difference). This doesn't affect the running instance at all; but when it restarts, it'll use the new version. Our internal upgrade system does this correctly. Once we decide on what sort of startup mechanism to use, we can do a restart in a post-install script in the Debian package too. In the meantime, a manual restart is necessary but there are no other ill effects.

**Comment by KarlHegbloom** [comment]
Will it restart upon a signal sent via the kill system call? Maybe sigusr1
ought to cause a restart.

**Comment by calmh** [comment]
TERM on the "inner" process if running with internal restarts, otherwise a TERM to the *only* process and the service manager (whatever it is) should restart it.

But you may have a multi user system, with several people running syncthings. Should we restart them for them? Maybe they're not even running the distro-installed binary? :)

**Comment by KarlHegbloom** [comment]
If it restarts based on it's own argv[0] then it ought to work even for
them, once they're up to a version that has the feature... You could add
another configuration option; ... isn't there one already for whether to
restart?

On Sun, Nov 8, 2015 at 1:50 PM, Jakob Borg <notifications@github.com> wrote:

> TERM on the "inner" process if running with internal restarts, otherwise a
> TERM to the *only* process and the service manager (whatever it is)
> should restart it.
>
> But you may have a multi user system, with several people running
> syncthings. Should we restart them for them? Maybe they're not even running
> the distro-installed binary? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syncthing/syncthing/issues/2438#issuecomment-154869253>
> .
>



-- 
Karl.Hegbloom@gmail.com
http://karlhegbloom.blogspot.com

**Comment by calmh** [comment]
Closing, as I don't think this is generally/correctly solvable from the Debian package.

**Comment by KarlHegbloom** [comment]
​The nautilus package does something that makes a dialog pop up after an
upgrade asking the user to manually restart nautilus. There are other
packages that ask the user to run things, perhaps waiting until after they
log in? I think it's done with "hooks" in apt... you know how it waits
until the end, after all packages are installed, to run certain actions
now? (It did not used to do that, a long time ago.) I think you can have it
call a script or drop in a file that makes it do that. If I wasn't so busy
with a very important deadline right now, I'd send you a pull request with
a patch... Maybe after a few months I'll have time for it and think of it
again.
