### ISSUE TITLE
Rework the Debian package building to be cleaner and follow the relevant guidelines

### ISSUE THREAD

**Issue by Stefan-Code** [syncthing/syncthing#2441]
`build.sh` supports building the `deb` directory required to build the `.deb` file, but no option to build the actual `.deb` file. Also, the process to build this file is not documented anywhere (or I didn't find it).

**Comment by MyPod** [comment]
.deb files are usually built trough dpkg-buildpackage, provided there is a
debian subdirectory I'm the project, which contains all the needed info to
build from source and to pick (if needed) only specific parts of the
install tree to make one or more debian packages. I am not sure how things
are done for syncthing in particular and can't check right away from a
phone, but building .debs is rather well documented

**Comment by Stefan-Code** [comment]
@MyPod [I am able to build the `.deb` file](https://github.com/syncthing/syncthing/pull/2440#issuecomment-154731229) , however I'm wondering if I'm doing it right because of the many errors lintian shows.
Do you mean documentation for building `.deb`s in general or for syncthing?

**Comment by MyPod** [comment]
I meant in general. I said I have no idea on the specific procedure used by
syncthing. I can try to have a look no sooner than Monday

**Comment by KarlHegbloom** [comment]
To make it build a .deb just make sure the install target accepts a DESTDIR
parameter,  and wrap the normal build with the debian one by having a tool
like dh_make create the debian/ directory and the files in it
automatically. Those should be checked in and maintained.

**Comment by Stefan-Code** [comment]
Building the debian directory is already handled by the syncthing build in [build.go (buildDeb)](https://github.com/syncthing/syncthing/blob/master/build.go#L285) 
When running `dpkg --build` the resulting file has an awful lot of lintian errors though. So I'm not certain that `dpkg --build` is the actual process used to build the official package or if there are more options supplied.

**Comment by calmh** [comment]
I'm sure the deb packages are horribly incorrect according to the linters; it's basically an ugly hack to build the package as we do. Someone who actually knows Debian well enough to fix it is welcome to do so. In the meantime, the command used by the build system is

```
fakeroot sh -c 'chown -R root:root deb ; dpkg-deb -b deb .'
```

**Comment by Stefan-Code** [comment]
@calmh Thanks for the info, then I guess the config file handling in [my PR](#2440) should be ok.

**Comment by ProfessorKaos64** [comment]
I did try building this source tree using the debian/ folder set from the PPA I was able to find. However, it didn't like to build. I was using dpkg-buildpackge -rfakeroot -us -uc

**Comment by canton7** [comment]
You'll have to provide more information than "it didn't like to build"

**Comment by calmh** [comment]
The only "supported" way to create a deb package is as described in this thread: "build.sh deb" and dpkg-deb as above. Apart from that, experiment as you like and file a PR if you create a better build mechanism. :)

**Comment by ProfessorKaos64** [comment]
I wanted to do a note traditional Debian build. If I can figure it out, sure will. Strange that it is fine for the PPA but those Debian rules don't seem to translate. I'd love to host this for SteamOS-Tools. I suppose for now I may build with you method and then keep looking on a restructure when I have time.  Perhaps a dh override in Debian/rules would do it.

**Comment by spk** [comment]
Hi, I fixed some issues with `debian/control` file with #2798
For you information there is an ITP (Intent To package) on Debian, cf https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=749887
But look like the main developer don't have time to continue on this.
I don't know a lot about Golang ecosystem but can try to help if its needed.

**Comment by hiqua** [comment]
Shouldn't this be closed now that syncthing is packaged in debian/testing and debian/unstable?

**Comment by calmh** [comment]
Yes.
