### ISSUE TITLE
2.1: Confusing global discovery setting

### ISSUE THREAD

**Issue by usego** [syncthing/syncthing#2442]
I'm configuring my own discovery server. Manual says
>
The discovery server prints it’s device ID at startup. In the case where you are using a non CA signed certificate, this device ID (fingerprint) must be given to the clients in the discovery server URL:

https://disco.example.com:8443/?id=7DDRT7J-UICR4PM-PBIZYL3-MZOJ7X7-EX56JP6 -IK6HHMW-S7EK32W-G3EUPQA
>

Ok, I've put into Global Discovery Server textbox (UIDs changed)
https://10.88.0.35:8443/?id=AABBCCD-QU3TSG7-F7HK35Q-W4FJ7LV-2UH3D6A-VSJYRLK-RU3YQH6-DJKXDQO -AABBCCD-PECJDRA-7BHTPAG-3Q37OOV-MDTWIJ5-SAEHJU5-NOKIHXX-DM5PLQO

When I go back, I see in textbox just -AABBCCD-PECJDRA-7BHTPAG-3Q37OOV-MDTWIJ5-SAEHJU5-NOKIHXX-DM5PLQO  which makes me think that something was entered wrong. config.xml contains

        <globalAnnounceServer>-AABBCCD-PECJDRA-7BHTPAG-3Q37OOV-MDTWIJ5-SAEHJU5-NOKIHXX-DM5PLQO</globalAnnounceServer>
        <globalAnnounceServer>https://10.88.0.35:8443/?id=AABBCCD-QU3TSG7-F7HK35Q-W4FJ7LV-2UH3D6A-VSJYRLK-RU3YQH6-DJKXDQO</globalAnnounceServer>

and this confuses even more.

Actually I've noticed this by trying to figure out why 2 servers works with discovery server, but the 3rd one not, so might be this is a "feature", not an issue, but this is confusing.

**Comment by calmh** [comment]
There's an erroneous space in the documentation; there should be no space in the middle of the device ID. I'll fix that. If you do the same, you'll probably be fine.
