### ISSUE TITLE
[Feature request] ACME (letsencrypt) Support

### ISSUE THREAD

**Issue by jpillora** [syncthing/syncthing#2445]
Lets Encrypt is nearly out of beta, it would be awesome if ST could automatically generate signed certificates for a provided domain.

* https://letsencrypt.org/
* Go implementation https://github.com/xenolf/lego/tree/master/acme

**Comment by calmh** [comment]
For the GUI, or what do you mean? Unsure if this is something we really need to handle internally.

**Comment by AudriusButkevicius** [comment]
Yeah I can't understand whats the point of this.

**Comment by jpillora** [comment]
Ah right, it'd just be GUI, closed
