### ISSUE TITLE
Upgrade code needs to be smarter

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2446]
Currently it takes the first file it finds called `syncthing` and uses that as the binary to upgrade to. After #2440 this became the ufw config file, which is entirely wrong.

Luckily that file doesn't pass the signature check so the upgrade was aborted rather than blowing away the binary for the user...

**Comment by Stefan-Code** [comment]
Would checking for the executable bit work?

**Comment by Stefan-Code** [comment]
Maybe something like:
```go
file, error := os.Lstat("test.txt")
var executable = file.Mode() & 0111
if executable != 0  {
        //found the syncthing binary
        fmt.Println("file is executable")
    } else {
        //found the ufw config file
        fmt.Println("file is not not executable")
    }
```
and integrate this in  [archiveFileVisitor](https://github.com/syncthing/syncthing/blob/0a022d38faa16d93f2fc95e8271c4662fc37f69b/lib/upgrade/upgrade_supported.go#L259)?

**Comment by canton7** [comment]
Not a fan of this approach. Why not put the syncthing binary in a known location in the archive (it already is), and make syncthing look for this?

**Comment by calmh** [comment]
Yeah, we should simply look for syncthing(.exe) at the first directory level and no deeper.
