### ISSUE TITLE
syncthing doesn't handle sparse files optimally

### ISSUE THREAD

**Issue by jpjp** [syncthing/syncthing#245]
Sender:

    $ dd of=sparse-file bs=1k seek=5120 count=0
    $ du -sh sparse-file
    0 sparse-file
    $ du -sh --apparent-size sparse-file
    5.0M sparse-file

Receiver:

    $ du -sh sparse-file
    5.0M sparse-file
    $ du -sh --apparent-size sparse-file
    5.0M sparse-file

**Comment by cbluth** [comment]
Does syncthing properly transfer sparse files now?

**Comment by AudriusButkevicius** [comment]
No

**Comment by calmh** [comment]
Sure we do. They just don't become sparse on the other side.

**Comment by AudriusButkevicius** [comment]
So my no was directed at keeping the files sparse, and we might still transfer zeros if we dom't have a matching block of zeros locally in some other file already (as blockmap gets updated after the file gets modified)

**Comment by calmh** [comment]
I know you did, I just wanted to clarify for cbluth :)
