### ISSUE TITLE
Complete Mac crash

### ISSUE THREAD

**Issue by gelobter** [syncthing/syncthing#2451]
Syncthing works well on my windows 10 pc, but within 10 minutes of loading crashes my MacOS every time.  BTW this appears to be true for bittorrent sync as well as cubby. So perhaps there is some underlying sync technology crashing all of these, or some truly toxic file that, when read for purposes of syncing, crashes the OS.  In any case, this is a major and persistent problem for my synchronizing my mac and my pc.

The following is the mac crash report/kernel dump that comes up after the reboot...Thanks in advance for working on this!

*** Panic Report ***
panic(cpu 2 caller 0xffffff8003dd6bba): Kernel trap at 0xffffff800427a7e9, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0xffffff7f0fda5000, CR3: 0x000000001631f126, CR4: 0x00000000001627e0
RAX: 0x0000000000000800, RBX: 0x00000000ffffffff, RCX: 0x0000000000000008, RDX: 0x0000000000000000
RSP: 0xffffff800fd93820, RBP: 0xffffff800fd938a0, RSI: 0x0000000000000000, RDI: 0xffffff80d524e004
R8:  0x0000000000000009, R9:  0x000000000000006b, R10: 0xffffff7f0fda5000, R11: 0xffffff80d524e004
R12: 0xffffff801554c081, R13: 0xffffff800fd93ac0, R14: 0xffffff80d524e554, R15: 0x0000000000000000
RFL: 0x0000000000010246, RIP: 0xffffff800427a7e9, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0xffffff7f0fda5000, Error code: 0x0000000000000002, Fault CPU: 0x2, PL: 0

Backtrace (CPU 2), Frame : Return Address
0xffffff800fd934b0 : 0xffffff8003ce5307 
0xffffff800fd93530 : 0xffffff8003dd6bba 
0xffffff800fd93710 : 0xffffff8003df4313 
0xffffff800fd93730 : 0xffffff800427a7e9 
0xffffff800fd938a0 : 0xffffff800426c127 
0xffffff800fd93960 : 0xffffff7f865e3c57 
0xffffff800fd93a60 : 0xffffff7f865e2ea7 
0xffffff800fd93bc0 : 0xffffff8003f4d0a4 
0xffffff800fd93c20 : 0xffffff8003f4996a 
0xffffff800fd93d20 : 0xffffff8004115452 
0xffffff800fd93db0 : 0xffffff8003f22a80 
0xffffff800fd93e60 : 0xffffff80041c9e3a 
0xffffff800fd93f00 : 0xffffff80041c9ba3 
0xffffff800fd93f60 : 0xffffff800422afd1 
0xffffff800fd93fb0 : 0xffffff8003df4b16 
      Kernel Extensions in backtrace:
         com.apple.AppleFSCompression.AppleFSCompressionTypeZlib(1.0)[15666726-B08C-3361-8E4C-D1AFA962E592]@0xffffff7f865e2000->0xffffff7f865e7fff

BSD process name corresponding to current thread: syncthing

Mac OS version:
15B42

Kernel version:
Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64
Kernel UUID: AB5FC1B4-12E7-311E-8E6F-9023985D8C1D
Kernel slide:     0x0000000003a00000
Kernel text base: 0xffffff8003c00000
__HIB  text base: 0xffffff8003b00000
System model name: MacBookAir6,2 (Mac-7DF21CB3ED6977E5)

System uptime in nanoseconds: 553061450897
last loaded kext at 406354334146: com.apple.filesystems.smbfs	3.0.0 (addr 0xffffff7f86787000, size 409600)
last unloaded kext at 109622824369: com.apple.driver.AppleIntelLpssI2C	2.0.57 (addr 0xffffff7f860d0000, size 36864)
loaded kexts:
com.disc-soft.DAEMONTools.VirtualSCSIBus	1.0.2
com.apple.filesystems.smbfs	3.0.0
com.apple.driver.AudioAUUC	1.70
com.apple.driver.AGPM	110.20.21
com.apple.driver.ApplePlatformEnabler	2.5.1d0
com.apple.driver.X86PlatformShim	1.0.0
com.apple.filesystems.autofs	3.0
com.apple.driver.AppleUpstreamUserClient	3.6.1
com.apple.driver.AppleHDA	272.50.31
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.pmtelemetry	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	4.4.2f1
com.apple.driver.AppleLPC	3.1
com.apple.driver.AppleIntelHD5000Graphics	10.1.0
com.apple.driver.AppleThunderboltIP	3.0.8
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHV	1
com.apple.driver.AppleCameraInterface	5.41.0
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	4.4.2f1
com.apple.driver.AppleSMCLMU	208
com.apple.driver.AppleIntelFramebufferAzul	10.1.0
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleBacklight	170.8.1
com.apple.driver.AppleMCCSControl	1.2.13
com.apple.driver.AppleUSBCardReader	3.7.1
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	37
com.apple.driver.AppleTopCaseHIDEventDriver	86
com.apple.iokit.IOAHCIBlockStorage	2.8.0
com.apple.driver.AppleAHCIPort	3.1.5
com.apple.driver.AirPort.Brcm4360	1010.14.1a4
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleACPIButtons	4.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	4.0
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	163
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.usb.IOUSBHostHIDDevice	1.0.1
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.0.1
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	272.50.31
com.apple.kext.OSvKernDSPLib	525
com.apple.iokit.IOSurface	108.0.1
com.apple.driver.CoreCaptureResponder	1
com.apple.iokit.IOBluetoothHostControllerUSBTransport	4.4.2f1
com.apple.iokit.IOBluetoothFamily	4.4.2f1
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d7
com.apple.driver.AppleHDAController	272.50.31
com.apple.iokit.IOHDAFamily	272.50.31
com.apple.iokit.IOAudioFamily	204.1
com.apple.vecLib.kext	1.2.0
com.apple.AppleGraphicsDeviceControl	3.11.33b1
com.apple.iokit.IOAcceleratorFamily2	203.10
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IOSerialFamily	11
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.AppleSMBusController	1.0.14d1
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.iokit.IOSCSIBlockCommandsDevice	3.7.7
com.apple.iokit.IOUSBMassStorageDriver	1.0.0
com.apple.iokit.IOSCSIArchitectureModelFamily	3.7.7
com.apple.driver.usb.AppleUSBHub	1.0.1
com.apple.driver.CoreStorage	517
com.apple.driver.AppleMultitouchDriver	304.9
com.apple.driver.AppleHIDTransport	5
com.apple.driver.AppleHIDKeyboard	181
com.apple.driver.AppleHSSPIHIDDriver	41.6
com.apple.iokit.IOAHCIFamily	2.8.0
com.apple.driver.AppleThunderboltDPInAdapter	4.1.2
com.apple.driver.AppleThunderboltDPAdapterFamily	4.1.2
com.apple.driver.AppleThunderboltPCIDownAdapter	2.0.2
com.apple.driver.AppleThunderboltNHI	4.0.4
com.apple.iokit.IOThunderboltFamily	5.0.6
com.apple.iokit.IO80211Family	1101.24
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleHSSPISupport	41.6
com.apple.driver.AppleIntelLpssSpiController	2.0.57
com.apple.driver.AppleIntelLpssDmac	2.0.57
com.apple.driver.AppleIntelLpssGspi	2.0.57
com.apple.driver.usb.AppleUSBXHCIPCI	1.0.1
com.apple.driver.usb.AppleUSBXHCI	1.0.1
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.iokit.IOUSBHostFamily	1.0.1
com.apple.driver.AppleUSBHostMergeProperties	1.0.1
com.apple.driver.AppleEFINVRAM	2.0
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.DiskImages	415
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	4.0
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0
Model: MacBookAir6,2, BootROM MBA61.0099.B20, 2 processors, Intel Core i7, 1.7 GHz, 8 GB, SMC 2.13f15
Graphics: Intel HD Graphics 5000, Intel HD Graphics 5000, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E384A544D4C41522D4E544D
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E384A544D4C41522D4E544D
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.21.94.29.1a4)
Bluetooth: Version 4.4.2f1 16391, 3 services, 19 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512F, 500.28 GB
USB Device: USB 3.0 Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB2.0 Hub
USB Device: USB Optical Mouse
USB Device: USB Multimedia Keyboard
USB Device: KVMLite
Thunderbolt Bus: MacBook Air, Apple Inc., 23.6

**Comment by AudriusButkevicius** [comment]
Given it happens with other software, I don't see how its a syncthing bug, and I don't see anything we could do.

The place for you to start would probably be to reinstall your OS.

**Comment by gelobter** [comment]
It only happens with other syncing software. Cubby and bittorrent sync. I wanted to disclose that to help the community figure it out, but it's definitely a problem with the syncing software. I have reinstalled OS 2x and still the same problem.
Thanks!

**Comment by AudriusButkevicius** [comment]
So I don't think this is a wide-spread problem, otherwise we'd have more reports.
And for singular cases, especially ones where the same issue happens with other software, I'd say it's not syncthing's fault, and it's the fault of your configuration/hardware.

If you google around for com.apple.AppleFSCompression.AppleFSCompressionTypeZlib you'll find various reports, bad memory, bad motherboards, kernel extensions, antiviruses etc.

I am closing this, as I think it's a problem with your machine, and there is nothing to fix on syncthing side.
