### ISSUE TITLE
Web GUI - formatting issue

### ISSUE THREAD

**Issue by KevinBEvv** [syncthing/syncthing#2452]
I noticed what might be a formatting problem
![formatting](https://cloud.githubusercontent.com/assets/15109939/11052359/dad18ef8-871c-11e5-8a17-b5d7c3925693.jpg)

**Comment by KevinBEvv** [comment]
notice the digits dropping a wee bit.   This is from Chrome.  Version 0.12.2.  64-bit

**Comment by AudriusButkevicius** [comment]
I think this is just the font, I don't think there is much we can do.

**Comment by wweich** [comment]
It's definitely the font. For some reason [Raleway](http://www.fontsquirrel.com/fonts/raleway) has different "base lines" for different numbers.

**Comment by calmh** [comment]
As designed. https://en.wikipedia.org/wiki/Text_figures
