### ISSUE TITLE
"Global discovery: unsupported scheme udp4" on Windows 7 - Discovery broken

### ISSUE THREAD

**Issue by chauffer** [syncthing/syncthing#2453]
Steps to reproduce:
* Try to add a Linux server running Syncthing through ID only, no IP
* Windows computer cannot find it through discovery
* Gets correctly added if the IP address of the machine is specified.

Works fine:
* Syncthing Linux server trying to add a Syncthing Linux server through ID only, notification pops up which asks for permission to add the machine.

I can only assume this depends on "WARNING: Global discovery: unsupported scheme udp4" from the logs on Windows, nothing else seems to be relevant.
Discovery is green and 2/2 on my Windows machine, 8/8 on the device I want to add.
My computer's running Windows 7, 64 bit. Servers are Ubuntu 12.04/14.04
I'm running SyncThing v0.12.2 everywhere, using the SyncThing repo on Linux, and the Windows binary

**Comment by chauffer** [comment]
Whoops, fixed - Seems like udp4 was a leftover from the 0.11 config.

**Comment by DaveQB** [comment]
@chauffer  So what was the solution? What should the protocol value be?
Thanks.

**Comment by calmh** [comment]
@DaveQB "default" in v0.13.
