### ISSUE TITLE
Hide the bottom bar

### ISSUE THREAD

**Issue by Aeyoun** [syncthing/syncthing#2454]
Please hide the bottom bar (navbar navbar-default navbar-fixed-bottom). At least don't make it fixed so it can be scrolled out of view. It takes up a lot of space on small screens. If you make the window narrow enough, it will drop to the bottom. BUT the @media selector controlling that behavior should also look at the window height. Short windows get two lines of fixed bottom navigation and that uses way too much space. The rest of the layout works fine in these screen sizes.

**Comment by wweich** [comment]
I would suggest either removing one of the items from the bottom nav bar, oder using the following CSS in override.css to change the nav bar to "unstciky" at the first media query break point:
```
@media (max-width: 1199px) {
  .navbar-fixed-bottom {
    position: static;
  }
}
```

**Comment by AudriusButkevicius** [comment]
Pull requests welcome
