### ISSUE TITLE
Blocks are sometimes downloaded which should be reused locally

### ISSUE THREAD

**Issue by Thumbsy** [syncthing/syncthing#2455]
I've been noticing troublesome behaviour lately that started to occur since upgrading to 0.12. I have a repository that is shared with my own PC (Windows 8.1 x64 running Syncthing 0.12.2) and another remote PC (Windows 7 x64 running Syncthing 0.12.2). Both machines are running Syncthing through SyncTrayzor 1.0.29.

Sometimes, when I change the name of a folder that contains files/more folders on my PC, Syncthing on the other PC begins to completely redownload all the files into the new folder and then deletes the old folder and its contents afterwards, instead of creating a new folder and moving the existing files there. The same happens to file renames.

The same goes for changing files, instead of downloading only the changed blocks, Syncthing on the remote PC downloads the entire file and replaces the old one.

This appears to happen randomly as I've seen a few occassions where changing folder/file names does gets handled as expected. I wonder if anyone else has noticed something similar happening. Would it maybe help for me to remake my Syncthing repositories?

**Comment by AudriusButkevicius** [comment]
So it's possible that if you are renaming stuff as it's scanning, it will pick up the deletion, but will not pick up the addition. The integration and unit tests still pass, so I think it should still work as it did before, as there hasn't been any change in that department.

**Comment by Thumbsy** [comment]
I'm afraid the rename-while-scanning scenario is not what's happening in my case. I've been keeping a closer eye on things after I noticed this started happening, and as it turns out, the issue actually occurs roughly 95% of the time. I've tried out enough file/folder renames to rule out the possibility of what you described AudriusButkevicius.

Creating a new test repo which is shared between the concerned machines, containing one folder that contains two files, also displays the misbehaviour.

I think I'm going to do a full rebuild of the indexes on both machines that I have just to see how it affects things.

**Comment by AudriusButkevicius** [comment]
I don't think that will yield much.

Try running with STTRACE=model, get a folder with 2-3 files, and provide the logs.

**Comment by Thumbsy** [comment]
I'm glad you were so quick to reply before I'd rebuild everything, thanks haha. I'll give it a try once the current transfer that's going on is finished. It'll be a while though, but I'll provide the logs here when I get around to it.

I also completely forgot to add that both machines are running Syncthing through SyncTrayzor (both 1.0.29), I don't know whether that might be of significance here but it's worth mentioning.

**Comment by chucic** [comment]
Experiencing same thing (basically).

I have 2 folders (test_orig and test_copy) shared between 2 devices (windows and debian). In test_orig is 104MB of mp3 files, test_copy is empty.

When I copy content of test_orig to test_copy on windows, debian starts pulling. Some blocks are reused, some not. Out of 104MB on 1st run 90MB, 2nd 50MB, 3rd 20MB is redownloaded again despite that both sides have all original blocks in test_orig folder. I tried alternate sides, also with inotify on and off.

Decreasing amount of data being redownloaded is weird, but maybe it is because I used same data several times (always deleted content of test_copy and let it sync).

I can do STTRACE=model when I have more time, but Thumbsy will probably be faster.

**Comment by AudriusButkevicius** [comment]
It's not guaranteed that when moving files between folders all of the blocks will be reused.
Because folders are separate entities, a rescan/inotify of the folder where the files are gone can happen before the folders which gained the files. If you want to make sure blocks are reused, copy, wait for it to sync, and then remove.

**Comment by chucic** [comment]
Audrius, I did copy files, so I expect that blocks should be reused.

**Comment by AudriusButkevicius** [comment]
How do you know, how much was transfered though? Do you use something external to gauge that? Because you can't check that from the web ui.

**Comment by chucic** [comment]
Why not?

**Comment by calmh** [comment]
Yeah, I'm seeing a bit less than 100% reuse here as well. Making a copy of ~2 GB of data results in ~ 200 MB getting transferred to the other side. I was thinking it could be files that were scanned while they were being copied (thus having different blocks), but that's not it - I made sure to get a scan before and after only, not during.

**Comment by Thumbsy** [comment]
I'm glad the issue has been confirmed, as I can't get the debugging to work, as silly as it sounds! This is my first time trying to debug Syncthing, I'm probably doing it wrong because I've entered the following in the command prompt:

`C:\Users\[username]\AppData\Roaming\SyncTrayzor\syncthing.exe STTRACE=model`

But that doesn't seem to have any effect (Syncthing starts normally without additional logging).

**Comment by calmh** [comment]
On windows that needs to be two commands

```
C:> SET STTRACE=model
C:> syncthing
```

So I ran two sides, one with STTRACE=model, and copied a 1 MB file repeated on that side and rescanned after each time. Seemingly randomly there would be nothing transferred or the entire file transferred, as seen by the presence or absence of `REQ(in): ...` log entries on that side. Weird.

**Comment by calmh** [comment]
Woops. Fixed.

**Comment by canton7** [comment]
@Thumbsy to set `STTRACE` in SyncTrayzor, go to File -> Settings -> Syncthing -> Advanced, and add `STTRACE=model` to 'Syncthing Environmental Variables'.

**Comment by Thumbsy** [comment]
@canton7 Pardon the ridiculously late reply, but thank you!
