### ISSUE TITLE
one custom discosrv defined, webui says 3 discovery servers connected

### ISSUE THREAD

**Issue by wararjey** [syncthing/syncthing#2457]
[edit after checking logfiles]

I'm running my own discosrv (upgraded to 0.12 and working nicely). I've changed the discovery setting in the webui of a 0.12.2 syncthing client accordingly:
"https://nameof.discoveryserver.example.com:8443/?id=DEVICEID-OF-DISCOSRV-ETC"
I've checked the new config.xml, and it lists exactly this very one discovery server. There are no other discovery servers defined and there is no "default" entry whatsoever.

However, the web ui always shows the client is connected to 3 discovery servers, and not 1, as I would expect. I've checked the client's logs and those say that the client actually does not seem to connect to any other discovery servers apart from the one I've specified in the config, so this might be merely a web ui display problem.

Btw, the v0.11 config for that client used to list 2 discovery servers, one each for udp4 and udp6, as my custom discovery server is a dual-stack ipv4/ipv6 machine, as well. Perhaps there is some "data residue" outside config.xml that confuses the client?

Regards and thank you very much for making this great tool,

**Comment by AudriusButkevicius** [comment]
2 others is local discovery via v4 and v6

**Comment by wararjey** [comment]
Ah, that's it. Thanks for making that clear.

Regards,
