### ISSUE TITLE
Syncthing 0.12.2 taking excessively long time to complete initial scan

### ISSUE THREAD

**Issue by natebrau** [syncthing/syncthing#2458]
Background-

This is a large project.  Eventually it will encompass 14 servers, but it currently only has 2 in the cluster.  Total data to be sync'ed is about 22TB, and there are about 13.5M files.  

Syncthing is being asked to replace a legacy custom-built rsync process, so most of the 22TB is already present on both the master server (set to be read-only), as well as the peer server (set to be read-write).  All data is encompassed within a single parent folder.

On the peer server, the reported "single thread hash performance" is 163MB/s.  On the master server, the reported "single thread hash performance" is 116MB/s.  Doing quick back-of-the-envelope calculations, if there's only one thread hashing, then it should take about 52 hours to complete an initial scan of 22TB of data.  (22TB/116MB/s).  However, it's now been running for about 5 days, and still hasn't finished its initial scan.  The UI is only reporting its status as "Scanning (14%)," and the Global State is at roughly 14TB, implying it's at best 2/3 of the way done with the initial scan.

I have the rescan interval set to 4 hours (14400s), and am not running inotify yet.

Any assistance would be appreciated.  By way of comparison, the peer node completed its initial scan of the same amount of data in substantially less time, although at the time, I didn't think to mark down the exact length.  When the peer node restarted itself to upgrade to 0.12.2, having already completed its hash, it took roughly 16 minutes to come up:
cat syncthing.log | grep zfsdata.storage
[PWBXO] 23:06:23 OK: Ready to synchronize zfsdata.storage (read-write)
[PWBXO] 23:22:34 INFO: Completed initial scan (rw) of folder zfsdata.storage

However, the master node has still not yet completed its initial scan, 5 days on.

**Comment by calmh** [comment]
What's the OS? What does the CPU usage look like for the syncthing process? Does it have enough memory or is the box swapping? What does `iostat -xn 1` (or the equivalent, assuming this is a unixoid box as zfs is mentioned) look like?

**Comment by dcarosone** [comment]
By read only, assume you mean folder master?

Just a 'me too', in case it matters. I saw something very like this about a
month ago. At the time we put it down to the somewhat anaemic cpu in a
little nas, but it was inordinately slow and that didn't seem enough to
explain it.

But perhaps there's something different in the code path for discovering a
new file in master folder mode? Extra database work, in particular sync
transaction commits?

**Comment by natebrau** [comment]
Everything is CentOS 6.6.  CPU utilization is high (will hit 700% on a 12-CPU server), but bounces around a lot down to 100%, for no noticeable reason.  Memory utilization of syncthing is high, about 5.2GB reserved out of 32GB on the server.  The server itself is not swapping, and reports 11GB free memory.

the iostat -xn 1 result looks something like this:
Filesystem:              rBlk_nor/s   wBlk_nor/s   rBlk_dir/s   wBlk_dir/s   rBlk_svr/s   wBlk_svr/s     ops/s    rops/s    wops/s

Device:         rrqm/s   wrqm/s     r/s     w/s   rsec/s   wsec/s avgrq-sz avgqu-sz   await  svctm  %util
sda               0.00  2444.00    1.00   93.00   256.00 20296.00   218.64     0.02    0.17   0.05   0.50
sdd               0.00     0.00   36.00    0.00   297.00     0.00     8.25     0.40   11.03   6.19  22.30
sdb               0.00     0.00   57.00    0.00   341.00     0.00     5.98     0.61   10.74   6.40  36.50
sdc               0.00     0.00   43.00    0.00   407.00     0.00     9.47     0.55   12.70   6.56  28.20
sdg               0.00     0.00   59.00    0.00   489.00     0.00     8.29     0.51    8.56   4.95  29.20
sdh               0.00     0.00   70.00    0.00   626.00     0.00     8.94     0.70   10.01   4.96  34.70
sdl               0.00     0.00   70.00    0.00   727.00     0.00    10.39     0.87   12.40   6.84  47.90
sde               0.00     0.00   54.00    0.00   377.00     0.00     6.98     0.34    6.30   3.74  20.20
sdm               0.00     0.00   69.00    0.00   662.00     0.00     9.59     0.56    8.09   5.54  38.20
sdf               0.00     0.00   54.00    0.00   362.00     0.00     6.70     0.45    8.30   4.00  21.60
sdk               0.00     0.00   38.00    0.00   274.00     0.00     7.21     0.51   13.37   7.34  27.90
sdi               0.00     0.00   53.00    0.00   651.00     0.00    12.28     0.31    5.92   5.38  28.50
sdj               0.00     0.00   44.00    0.00   310.00     0.00     7.05     0.37    8.55   5.25  23.10

**Comment by natebrau** [comment]
Re: folder master, yes, exactly, the master server has its folder set to be "read only" while the peer servers has its folder set to be "read write".  There's only one folder being sync'ed, that folder contains all 22TB of data.

**Comment by calmh** [comment]
Assuming that sda is your system disk and the rest are the zfs pool, that looks a bit weird. Utilization is low enough, but the average service time is way high. Or are these 5400 RPM disks? Maybe not relevant...

If syncthing is burning 700% CPU I'm inclined to think we have a problem there, if it's running at 100% CPU I'm inclined to suspect your disk setup...

We could take a CPU profile to see where it's burning it all, if it's not hashing; start it with `STCPUPROFILE=1 syncthing`, let it index for 10 minutes or so, then shut it down from the GUI and it should create a `cpu-$pid.pprof` file that may be interesting.

**Comment by calmh** [comment]
There's one other guy in the forum reporting something somewhat similar, essentially a stalled scan on a very large folder. Could be that we have something that scales nonlinearly with the amount of data in the database.

**Comment by AudriusButkevicius** [comment]
Try setting scanProgressInterval to -1 in config.xml and see if that helps.

**Comment by calmh** [comment]
I'm more worried that the block database may not scale to 200 million keys...

**Comment by AudriusButkevicius** [comment]
Well this is about 12.2, I assume it worked fine in the old releases.

**Comment by Getron** [comment]
@natebrau You should use "only" ZFS for such large scale, with proper HDD (best are the WD Red for that), lot of amount of RAM >32GB ECC, and very good CPU (asuming, you just have 12 core CPU, not bad)

On v0.11.x i have such problems, it has take very long time to scan all my files, but, now, on 0.12.x, it is very fast (or to say, enough fast) on read and initialise data and database.

I think, your problem is somwhere between ZFS pool and sda systems.

With 0.12.2, i don't have anymora such problems now. I'm not very sure, what on your systems are wrong, but, i think, it is somthing arround the HDD, or, maybe, you have mixed up HDDs, not the same one (i mean, maybe, one WD HDD, one Samsung, or one of 2 TB, one of 4TB, etc. on the same ZFS pool, or RAID's), and then, voila, you have such problems.

**Comment by calmh** [comment]
@AudriusButkevicius  I interpreted this as being a new setup, probably never having run v0.11.

**Comment by calmh** [comment]
Well, I take that back, there's nothing unexpected happening in the blockmap code at least. I did a test inserting files with 500k blocks, starting with one and then up to 256 files (so 128M blocks). Memory usage is essentially static at ~1 GB and CPU time is just linear on the number of blocks. So that's fine. Possibly expensive, but at least not nonlinearly so.

![picture1](https://cloud.githubusercontent.com/assets/125426/11088276/538516cc-8861-11e5-94a5-0ca90c0fa255.png)

**Comment by natebrau** [comment]
My apologies for disappearing, I now have a cpu profile file (cpu-21915.pprof).  Unfortunately, it's 69MB in size, and github refuses to accept anything >10MB.

I will re-run for a shorter time, and hopefully that will result in a file <10MB I can publicly share here.

To everyone, thanks again for all your help and suggestions.  It's very much appreciated.

**Comment by AudriusButkevicius** [comment]
You can just put it on some file sharing site.

**Comment by natebrau** [comment]
The requested .pprof file:
http://empuje.nathanmoore.netdna-cdn.com/cpu-21915.pprof

**Comment by natebrau** [comment]
A quick note on disks:  this server has 12 identical 4TB WDC disks in a zpool, that's where all the data is stored.  However, it boots and roots off of a single SSD (Samsung 840), which is at /dev/sda.  Home directories are here, too, so /home/syncthing (which is the user SyncThing runs as, and where the .config/syncthing directory is, including the DB directory) is on /dev/sda.

**Comment by jorangreef** [comment]
> Memory utilization of syncthing is high, about 5.2GB

Could be GC pauses of 30-60 seconds or so per pause?

Not sure how Go's GC compares, but for a heap of 5GB with millions of pointers, V8's GC could pause for more than a minute every few seconds.

**Comment by calmh** [comment]
About half of the CPU time in that profile (52%) is attributable to calculating stuff for the web UI. I'm a tad surprised about that as we've done some quite extensive improvements on that front to not poll stuff, but apparently not while scanning? Either way, closing the web UI is a good tip here. About 11% is memory allocation and GC, which is a lot but probably reasonable under the circumstances. About 16% is the database layer - writes, compaction, etc. That's almost 80% of the CPU - the actual hashing doesn't really show up in the profile.

So I'm guessing (still) that your disk reads are slow, and you need to close the GUI to start with. :)

**Comment by cowboystyle** [comment]
Same for me here - 12.2 on ARM (RasPi 2B). Fine on 11.26, can take 30,40 minutes up to an hour to go through 'OK Ready to synchronise xxxxx (read-write)'. My problem is that because this is done before the Web UI starts - & because I run this is a daemon on boot, I have no way of checking to see if Syncthing is up without SSHing into the box it's on.

**Comment by blakev** [comment]
> About half of the CPU time in that profile (52%) is attributable to calculating stuff for the web UI.

Seriously? This can't be acceptable...

**Comment by calmh** [comment]
No, my point exactly, and I'm fairly sure we fixed that a long time ago, so thinking more about it - @natebrau are you doing some extra integration here against the REST interface, rather than using the GUI?

**Comment by calmh** [comment]
So profile actually showed all of that CPU being attributable to calling `/rest/db/completion`, which is called only once at startup by the UI. So I'm thinking either there's something weird going on here, or there is something custom hammering the REST interface?

**Comment by quantum1423** [comment]
Could somebody test this with a version compiled on Go 1.5.x? The newer versions of Go have a drastically improved garbage collector, and for huge heaps it can cut garbage-collection times by orders of magnitude.

**Comment by calmh** [comment]
Indeed. Note though that the Go 1.5 GC mostly reduces GC *latency* and not the total amount of CPU used for GC.

**Comment by quantum1423** [comment]
That's true, although in some "pathological" cases it seems to perform much better; one of them seems to be allocating largish bytes in a loop, something I do a lot in network code when I need to essentially reinvent my own io.Copy. (Possibly because I do too much functional programming, I always find having the caller allocate a shared buffer that is repeatedly filled inside the loop to be just...*dirty*). So for my own code that does this sort of pattern a lot, the total amount of CPU seems to have drastically gone down (at least `go test` tells me throughput increases of 10x and more)

**Comment by natebrau** [comment]
Apologies for belated responses.  

We do not have any custom integration via the REST interface yet.  We did deploy syncthing-inotify, which would use it however.

Thanks to everyone for all your help and suggestions.  However, we've gone ahead and stopped work with SyncThing for the moment and have instead patched our legacy sync system to use in this project.  I will personally come back to SyncThing in the future, as I feel it accomplishes a lot of things in a way I really appreciate- but just not continue with this current project.

Thanks again!
