### ISSUE TITLE
Local Discovery isnt working anymore after Upgrading to 0.12.x

### ISSUE THREAD

**Issue by fti7** [syncthing/syncthing#2459]
STTRACE="discover"
Trying to reach I3P6WD2 locally:

Got an ipv6 & ipv4 announcement:

[RM5D2] 2015/11/10 23:30:10.181112 local.go:172: DEBUG: discover: Received local announcement from [fe80::20c:29ff:fe6c:aaea%{EDFF54AF-3EB7-480E-BDD7-E8118E7BEFFC}]:58745 for I3P6WD2
[RM5D2] 2015/11/10 23:30:38.064221 local.go:172: DEBUG: discover: Received local announcement from 10.1.5.76:46010 for I3P6WD2

Looks like after the failed IPv6 parsing attempt, it would stop and didnt try to connect by ipv4
I3P is reachable by using 10.1.5.76

[RM5D2] 2015/11/10 23:30:47.078684 cache.go:99: DEBUG: lookup for I3P6WD2 at IPv4 local
[RM5D2] 2015/11/10 23:30:47.078684 cache.go:100: DEBUG:   direct: [tcp://10.1.5.76:0]
[RM5D2] 2015/11/10 23:30:47.078684 cache.go:101: DEBUG:   relays: []
[RM5D2] 2015/11/10 23:30:47.078684 cache.go:99: DEBUG: lookup for I3P6WD2 at IPv6 local
[RM5D2] 2015/11/10 23:30:47.078684 cache.go:100: DEBUG:   direct: [tcp://[fe80::20c:29ff:fe6c:aaea%{EDFF54AF-3EB7-480E-BDD7-E8118E7BEFFC}]:0]
[RM5D2] 2015/11/10 23:30:47.078684 cache.go:101: DEBUG:   relays: []
[RM5D2] 2015/11/10 23:30:47.078684 cache.go:124: DEBUG: lookup results for I3P6WD2
[RM5D2] 2015/11/10 23:30:47.078684 cache.go:125: DEBUG:   direct:  [tcp://[fe80::20c:29ff:fe6c:aaea%{EDFF54AF-3EB7-480E-BDD7-E8118E7BEFFC}]:0 tcp://10.1.5.76:0 tcp://188.110.206.229:0]
[RM5D2] 2015/11/10 23:30:47.078684 cache.go:126: DEBUG:   relays:  []
[RM5D2] 2015/11/10 23:30:47.079684 connections.go:301: INFO: Failed to parse connection url: tcp://[fe80::20c:29ff:fe6c:aaea%{EDFF54AF-3EB7-480E-BDD7-E8118E7BEFFC}]:0 parse tcp://[fe80::20c:29ff:fe6c:aaea%{EDFF54AF-3EB7-480E-BDD7-E8118E7BEFFC}]:0: hexadecimal escape in host

Connecting via Global Discovery is working fine. (Another Node)
Before i've had disabled relaying it worked too... but it used then an Relay to connect Two Nodes in the same LAN...

The Log is from an Windows Host (0.12.2)
I3P is an Linux Host (0.12.2)

Both Upgraded from 0.11.x

Best Regards,
Frank

**Comment by AudriusButkevicius** [comment]
#2444 dup

**Comment by AudriusButkevicius** [comment]
Run with STTRACE=dialer,discovery,connections and provide the logs.

**Comment by AudriusButkevicius** [comment]
So the port is 0, which is really strange.

**Comment by fti7** [comment]
I've found the Problem... :persevere:
Looks like i tried to debug on the wrong side... on the I3P Node i found an not converted Config Entry
   <options>
        <listenAddress>0.0.0.0:22000</listenAddress>

After Setting it to tcp://0.0.0.0:22000 it announces the correct port and the connection works.... :blush:
