### ISSUE TITLE
Relays used when on local network.

### ISSUE THREAD

**Issue by kluppy** [syncthing/syncthing#2460]
since v 12.1 I have had to turn off relays on my laptop because when at home my phone and laptop always connect using an external relay even though they are on the same LAN.

**Comment by AudriusButkevicius** [comment]
Do they connect in the lan without a relay?

**Comment by kluppy** [comment]
Yes, once I disabled relays they connected directly again.
I should mention I have just upgraded to 12.2 and re-enabled relays. I will see if the issue continues once I get home.

**Comment by AudriusButkevicius** [comment]
Can you run with STTRACE=discovery,connections env var set, and provide the log.

It might be that it first connect via the relay, but then later reconnects using local network? Or are you sure that is not the case?

**Comment by kluppy** [comment]
I was not able to replicate it last night, I have upgraded to 12.2 since I first posted.

FYI: I had left the nodes for a couple of hours when this was occurring and the GUI showed the address of the relay in stead of local addresses. I did not check the log to see if they had connected to each other directly without the GUI updating.

**Comment by AudriusButkevicius** [comment]
Closing it for now. Reopen if it happens again, and check if refreshing the GUI helps.
