### ISSUE TITLE
Timeouts on Advanced settings are gone

### ISSUE THREAD

**Issue by fbreve** [syncthing/syncthing#2461]
I noticed that those two options to set the timeouts on advanced settings are gone on version 0.12. Aren't they needed anymore? Raising the timeouts was the only way I had to get my NAS synching properly. Now it looks like it is not synching anymore.

**Comment by AudriusButkevicius** [comment]
You shouldn't need it anymore.

**Comment by calmh** [comment]
The timeouts don't exist in the same form anymore, and the ones that do exist shouldn't require tweaking. What are you seeing happening?

**Comment by fbreve** [comment]
I noticed that new files on some large folders are not appearing on the two NAS devices, the same problem I used to see before the option to set the timeouts was implemented.

**Comment by AudriusButkevicius** [comment]
Why do you think that that is related to tineouts? Are there acrually connection errors in the log?

**Comment by fbreve** [comment]
I was judging only by the symptons. I can't find the log files on Windows. There is one in AppData\Roaming\SyncTrayzor but it is really old. There is another one in \AppData\Roaming\SyncTrayzor\logs but it is from the last month.

**Comment by canton7** [comment]
SyncTrayzor stopped writing Syncthing logs, because Syncthing was creating its own logs and there wasn't a lot of point.

However Syncthing appears not to be writing any logs on Windows at the moment, so...
