### ISSUE TITLE
Повторяется ID

### ISSUE THREAD

**Issue by stvJnK** [syncthing/syncthing#2464]
Добрый день!
У меня проблема на 2 разных компьютерах повторяется ID, из-за этого не получается синхронизировать компьютеры с сетевым хранилищем.
версия на обоих компьютерах 0.12.2. 64 бит.

Статистика с 1 компьютера:
{
  "announce": {
    "defaultServersDNS": 1,
    "defaultServersIP": 0,
    "globalEnabled": false,
    "localEnabled": true,
    "otherServers": 0
  },
  "deviceUses": {
    "compressAlways": 0,
    "compressMetadata": 2,
    "compressNever": 0,
    "customCertName": 0,
    "dynamicAddr": 2,
    "introducer": 0,
    "staticAddr": 0
  },
  "folderMaxFiles": 7013,
  "folderMaxMiB": 1726,
  "folderUses": {
    "autoNormalize": 1,
    "ignoreDelete": 0,
    "ignorePerms": 1,
    "readonly": 1
  },
  "longVersion": "syncthing v0.12.2 \"Beryllium Bedbug\" (go1.4.3 windows-amd64 default) unknown-user@build2.syncthing.net 2015-11-09 13:23:26 UTC",
  "memorySize": 7110,
  "memoryUsageMiB": 41,
  "numCPU": 4,
  "numDevices": 2,
  "numFolders": 1,
  "platform": "windows-amd64",
  "relays": {
    "defaultServers": 1,
    "enabled": true,
    "otherServers": 0
  },
  "rescanIntvs": [
    60
  ],
  "sha256Perf": 188.16,
  "totFiles": 7013,
  "totMiB": 1726,
  "uniqueID": "",
  "upgradeAllowedAuto": true,
  "upgradeAllowedManual": true,
  "urVersion": 2,
  "usesRateLimit": false,
  "version": "v0.12.2"
}

Статистика со 2 компьютера:
{
  "announce": {
    "defaultServersDNS": 1,
    "defaultServersIP": 0,
    "globalEnabled": false,
    "localEnabled": true,
    "otherServers": 0
  },
  "deviceUses": {
    "compressAlways": 0,
    "compressMetadata": 2,
    "compressNever": 0,
    "customCertName": 0,
    "dynamicAddr": 2,
    "introducer": 0,
    "staticAddr": 0
  },
  "folderMaxFiles": 0,
  "folderMaxMiB": 0,
  "folderUses": {
    "autoNormalize": 0,
    "ignoreDelete": 0,
    "ignorePerms": 0,
    "readonly": 0
  },
  "longVersion": "syncthing v0.12.2 \"Beryllium Bedbug\" (go1.4.3 windows-amd64 default) unknown-user@build2.syncthing.net 2015-11-09 13:23:26 UTC",
  "memorySize": 8084,
  "memoryUsageMiB": 15,
  "numCPU": 4,
  "numDevices": 2,
  "numFolders": 0,
  "platform": "windows-amd64",
  "relays": {
    "defaultServers": 1,
    "enabled": true,
    "otherServers": 0
  },
  "rescanIntvs": null,
  "sha256Perf": 193.63,
  "totFiles": 0,
  "totMiB": 0,
  "uniqueID": "",
  "upgradeAllowedAuto": true,
  "upgradeAllowedManual": true,
  "urVersion": 2,
  "usesRateLimit": false,
  "version": "v0.12.2"
}

**Comment by rumpelsepp** [comment]
From google translate:

Good afternoon!
I have a problem on 2 different computers repeated ID, because of this it is impossible to synchronize the computers to the network storage.
version 0.12.2 on both computers. 64 bits.

**Comment by dcarosone** [comment]
Is your home directory on shared network storage, so the two syncthing
instances are sharing a config directory?

**Comment by canton7** [comment]
Alternative, Syncthing may be configured to synchronize your home directory.

**Comment by calmh** [comment]
The ID comes from the cert.pem and key.pem files that live in %LocalAppData%/Syncthing. Make sure this directory is not shared or synced between computers.
