### ISSUE TITLE
duplicate folder ID

### ISSUE THREAD

**Issue by le9i0nx** [syncthing/syncthing#2465]
I do the following
```bash
ansicon@debian:~$ syncthing-cli folders add vz_iso /tmp/
ansicon@debian:~$ syncthing-cli folders add vz_iso /tmp/
ansicon@debian:~$ syncthing-cli folders list
```
https://github.com/syncthing/syncthing-cli/issues/20
v0.12.2
I think api should not let me do it
at least in the gui is the defense of this action

**Comment by AudriusButkevicius** [comment]
I've closed that one, and I'll close this one.

The GUI is for users who have no clue what they are doing, hence why we protect them.

The CLI is for advanced users who know what they are doing.
If you are adding a duplicate folder, either you have no clue what you are doing, or you are just unfortunate.

Equality unfortunate as runnig `rm -rf /*`.

If you want this fixed, make a pull request fixing it.
