### ISSUE TITLE
is not working on ubuntu 15.10

### ISSUE THREAD

**Issue by dontspamm** [syncthing/syncthing#2466]
the client cannot connect to other machines if the machine is running ubuntu 15.10

windows clients connect and sync the files correctly so this is not problem for the network

**Comment by AudriusButkevicius** [comment]
I'd suggest thats a problem with ubuntu, and not syncthing.

Run with STTRACE=discovery,connections env var and provide log output.

**Comment by dontspamm** [comment]
ha i figured this out 
on settings 
*Global Discovery Server* i removed the udp4_bla_bla_bla udp6_bla_bla_bla and put *default* that solved the problem
