### ISSUE TITLE
correct discovery number

### ISSUE THREAD

**Issue by Eddy2909** [syncthing/syncthing#2467]
on my windows devices, the used discos are shown uncorrectly. 
eg. If I'm using 2 discos, the gui shows 4/4

**Comment by chucic** [comment]
other 2 are local discos, v4 and v6

**Comment by calmh** [comment]
Yep :+1:

**Comment by Eddy2909** [comment]
but why isnt that the case on debian too? on debian it shows 2/2 oO

**Comment by Eddy2909** [comment]
arghh.. damn.. :+1: sometimes its better to use the own brain. *facepalm*
