### ISSUE TITLE
Syncthing does not respect `<symlinksEnabled>`

### ISSUE THREAD

**Issue by blakev** [syncthing/syncthing#2469]
version 0.12.2, on both a Ubuntu and Windows 8.1 machine

On the linux box, I have a single folder with symlinked folders inside it -- so I only have to share one folder to the other servers to get all the contents; Syncthing reports this folder as having 0 items in it and does nothing further.

On the windows box, I tried sharing juntioned folders -- which were treated like the linux box above. However, from a separate linux machine with a symlinked directory inside another directory that had ALREADY been synced (symlinks added afterwards), it picked up the files and tried to share. However, the Windows machine gave the Notice:

```2015-11-13 23:29:18: Symlinks are disabled, unsupported or require Administrator privileges. This might cause your folder to appear out of sync.```

Yet, in all three config files the attribute is set to `true`.

Thoughts?

![Screenshot](http://i.imgur.com/OrZCzxd.png)

**Comment by calmh** [comment]
`symlinksEnabled` (which defaults to on) means that we synchronize symlinks as symlinks. With it off, symlinks are ignored. There is currently no option to follow symlinks and index the contents at the destination - for that see https://github.com/syncthing/syncthing/pull/1983 and https://forum.syncthing.net/t/600-bounty-for-symlink-handling/2493.

As for the error on your Windows side, it probably means what it says - are you an Administrator, and running on something newer than XP?

**Comment by blakev** [comment]
I searched but didn't see the discussion arround `followSymlinks`

Has there been any further progress since early October? What are the current hang ups from moving forward with the PR?

**Comment by AudriusButkevicius** [comment]
No there hasn't. The hang ups are that toggling the option can lead to data loss. There is a pull request which talks about it.
