### ISSUE TITLE
CheckFolderHealth needs to check for duplicate (invalid) folder IDs and missing Path

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2471]
We set the non-saved config attribute `Invalid` to "duplicate folder id" or "no directory configured" for those two errors when loading the config. We propagate this to the UI so the folder *looks* stopped and shows the error in question. But we never even look at the `Invalid` attribute anywhere else in the code, so the folder is in fact running as usual and doing scans and whatnot.

We need to have `Invalid` actually invalidate a folder, and do it in a way that doesn't get revived by `CheckFolderHealth`. It should be used only for nonrecoverable errors - config error, or potentially the new checksum mismatch error.

Alternatively we could just refuse to load the config when it's broken in this manner, have `CheckFolderHealth` handle the missing path case (it probably already does) and remove the `Invalid` thing altogether?

**Comment by AudriusButkevicius** [comment]
We should have checkfolderhealth check the two cases when its broken

**Comment by calmh** [comment]
Yeah

**Comment by calmh** [comment]
Remind me why we need the "invalid" thing as opposed to just erroring the folder at runtime? Not having a path seems like the same case as the path not existing, so trivially handled by the folder health thing.

Duplicate IDs is worse. That should never ever happen so I'm tempted to just crash at config loading time.

**Comment by AudriusButkevicius** [comment]
Sure, yet crashing doesn't help removing.

**Comment by calmh** [comment]
Current GUI can't handle folders with duplicate IDs anyway so there is no way to remove them even if shown. We used to change the ID on one or both offending folders to allow the GUI to work with them, but that's also not correctable except by hand editing the config file so I'm not convinced of the gain.

**Comment by AudriusButkevicius** [comment]
Ok lets crash then

**Comment by calmh** [comment]
Yes, I think that's appropriate. As one more nail in that coffin, imagine there is a duplicate folder ID (but different paths). The index contains data. The user resolves the situation by selecting the "other" folder compared to what was in the index. Boom, all files that no longer exist in the new folder path are blown away on other devices.
