### ISSUE TITLE
Having trouble using mounted -home=/config directory in docker

### ISSUE THREAD

**Issue by yougotborked** [syncthing/syncthing#2483]
Hi, I have a docker container that i recently updated to 0.12.3. It runs a base image of Debian Jessie, so I am using the apt repository.
It has been working great until this recent upgrade. I am getting 
```
[monitor] 04:21:58 INFO: Log output saved to file "/config/syncthing.log"
[monitor] 04:21:58 INFO: Starting syncthing
[ERA3W] 04:21:58 INFO: syncthing v0.12.3 "Beryllium Bedbug" (go1.4.3 linux-amd64 default) unknown-user@build2.syncthing.net 2015-11-15 17:15:10 UTC
[ERA3W] 04:21:58 INFO: My ID: <id>
[ERA3W] 04:21:59 INFO: Single thread hash performance is ~118 MB/s
[ERA3W] 04:22:05 FATAL: Cannot open database: no locks available - Is another copy of Syncthing already running?
[monitor] 04:22:05 INFO: Syncthing exited: exit status 1
```

the CMD line of my docker container is
```
CMD syncthing -home="/config" -logfile="/config/syncthing.log" -no-browser -verbose
```
my docker run config volume arguments are
```
-v /docker_ssd/var/syncthing:/config
```
/docker_ssd is an nfs mount with the following options
```
<ip_addr>:/docker_ssd /docker_ssd nfs vers=3 0 0
```
The /config folder is writeable, I am able to modify it from inside the docker container.

When I use the same container, and copy my /config into the container /config.test
and do a
```
syncthing -home="/config.test" -logfile="/config/syncthing.log" -no-browser -verbose
```
everything works great
```
[monitor] 04:34:52 INFO: Log output saved to file "/config/syncthing.log"
[monitor] 04:34:52 INFO: Starting syncthing
[ERA3W] 04:34:52 INFO: syncthing v0.12.3 "Beryllium Bedbug" (go1.4.3 linux-amd64 default) unknown-user@build2.syncthing.net 2015-11-15 17:15:10 UTC
[ERA3W] 04:34:52 INFO: My ID: <id>
[ERA3W] 04:34:53 INFO: Single thread hash performance is ~118 MB/s
[ERA3W] 04:34:53 VERBOSE: Starting up (/config.test)
<device_output>
```

**Comment by AudriusButkevicius** [comment]
Thr database requires to be on a filesystem which supports locks (flock/fnctl). It seems that your NFS mount does not support that. Perhaps you need to use a newer version of nfs.

http://unix.stackexchange.com/questions/1777/flock2-versus-fcntl2-over-a-nfs
