### ISSUE TITLE
HTTP still active after selecting HTTPS

### ISSUE THREAD

**Issue by daniel-lucio** [syncthing/syncthing#2487]
As I see, syncthing listen at port 8384 (number doesn't matter). But when selecting HTTPS,  syncthing supports HTTP and HTTPS using one port. This is not good, there is no a simple newbie way to close the clear HTTP.  Syncthing should redirect auto-magically htttp->https if HTTPS is active in the options.

As a non-newbie workaround, there are many projects that can detect the payload and route. One of them is sslsplit.

**Comment by AudriusButkevicius** [comment]
What do you mean `to close the clear HTTP`?
When HTTPS is enabled, it thought it already redirects HTTP to HTTPS.

**Comment by daniel-lucio** [comment]
"to close the clear HTTP"  to forbid the HTTPS

no you dont, it doesn't do the redirect, that is why I am reporting it. I tried on 0.12.2

**Comment by canton7** [comment]
> "to close the clear HTTP" to forbid the HTTPS

Forbid HTTP, or HTTPS? :stuck_out_tongue: 

It works for me in 0.12.2: if I request `http://localhost:8384`, I get redirected to `https://localhost:8384`.

**Comment by daniel-lucio** [comment]
Funny :palm_tree: 

It didnt work here. What kind of debug do you need to verify. It is clearly a bug, and it is hitting here.

**Comment by AudriusButkevicius** [comment]
There is no logging that would tell you that.
I suggest you double check your config, and also do note that for the setting to take effect you need to restart syncthing.

Also, are you sure you are not running behind a reverse proxy or something like that?

**Comment by AudriusButkevicius** [comment]
I'd say same issue as #2488

**Comment by calmh** [comment]
HTTP is supposed to still be active when HTTPS is enabled, but serve redirects. This happens for me:

```
jb@syno:~ $ curl -si http://localhost:8385/
HTTP/1.1 302 Found
Access-Control-Allow-Origin: *
Location: https://localhost:8385/
Date: Wed, 18 Nov 2015 23:12:31 GMT
Content-Length: 46
Content-Type: text/html; charset=utf-8

<a href="https://localhost:8385/">Found</a>.

jb@syno:~ $ curl -sik https://localhost:8385/ | head
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Cache-Control: public
Content-Length: 37583
Content-Type: text/html
Last-Modified: Tue, 17 Nov 2015 21:04:11 GMT
Set-Cookie: CSRF-Token-7DDRT=UhvGhM8vIbW3w6f4CYUvmjfpjnSQrsX8
X-Syncthing-Id: 7DDRT7J-UICR4PM-PBIZYL3-MZOJ7X7-EX56JP6-IK6HHMW-S7EK32W-G3EUPQA
X-Syncthing-Version: v0.12.3+18-g21c9e93-dirty
Date: Wed, 18 Nov 2015 23:12:32 GMT
...
```

So, cannot reproduce here. Your browser may be doing caching and tricking you?

**Comment by marclaporte** [comment]
I can reproduce the issue. Here is screenshot
![2015-12-17-https-redirect-not-working](https://cloud.githubusercontent.com/assets/1004261/11884535/724d69e4-a4e8-11e5-967e-e2a3601c5588.png)

Thanks!

**Comment by AudriusButkevicius** [comment]
You need to restart syncthing for the setting to take effect.

**Comment by calmh** [comment]
I'm not really sure what your screenshot shows. Note also that on most modern browsers, sites with self-signed (or just not EV) certificates are shown equally insecure as HTTP, even though it is HTTPS.

**Comment by canton7** [comment]
For a self-signed cert, Chrome shows a red padlock and a big red strike through the 'https' in my experience.

**Comment by calmh** [comment]
Either way, we *do* serve redirects as shown by curl, the code is fairly clear, and this could be anything from a misunderstanding to a browser error to some antivirus intercepting the request and "securing" it by keeping it on HTTP for inspection. I don't see a bug here.

**Comment by canton7** [comment]
Yeah, not disagreeing there, but let's at least interpret the screenshot correctly :stuck_out_tongue:

**Comment by daniel-lucio** [comment]
No, not working here. I have restarted and done the CURL test
curl -si --basic --user admin  http://IP:8384/ 
Enter host password for user 'admin':
HTTP/1.1 200 OK
Cache-Control: public
Content-Length: 37461
Content-Type: text/html
Last-Modified: Sun, 22 Nov 2015 15:03:35 GMT
Set-Cookie: sessionid-OQR6K=TEfLktPnrN6UhCbQvMs3jGsHb8NRd0hd
Set-Cookie: CSRF-Token-OQR6K=NVss0vgfozn0cH50iwz3grOA73L1sRH8
X-Syncthing-Id: OQR6KWG-3HCM3SP-DFEW3QL-WTLARE6-7FK5ZPM-OIBZ2KR-IPFKMJB-FX6QXQV
X-Syncthing-Version: 0.12.4
Date: Fri, 18 Dec 2015 18:26:32 GMT

What is the path where the settings are save? .local?

**Comment by AudriusButkevicius** [comment]
As I said, the setting requires restart to be enabled.

Can you make a call to /rest/system/config and /rest/system/config/insync via non-https and provide the output?

**Comment by AudriusButkevicius** [comment]
Alternatively you could provide access to the system (or some test environment) which replicates the bug, as none of the devs can repro it.

**Comment by daniel-lucio** [comment]
http://IP:8384/rest/system/config/insync gives {"configInSync":true}
The other has information I can not post here. Let me figure out a way.

**Comment by daniel-lucio** [comment]
Fixed!, I dont know if this is a "feature" or a bug

If you specify the -gui-address=IP:port,  the HTTP->HTTPS redirect wont work. Taking it out fixes the issue.

**Comment by AudriusButkevicius** [comment]
If you want https, prefix it with https://

**Comment by AudriusButkevicius** [comment]
Though I feel we should use whatever is defined in the config if not specified.

**Comment by daniel-lucio** [comment]
Yes, because i was having -gui-address=127.0.0.1:8483,  not http://127.0.0.1  or https://127.0.0.1.  If there is not protocol prefix, you should honored the config

**Comment by calmh** [comment]
Yep, it does that now, Audrius fixed it recently.
