### ISSUE TITLE
username protection disabled when updating from 0.11.x to 0.12.x

### ISSUE THREAD

**Issue by daniel-lucio** [syncthing/syncthing#2488]
Maybe you know, maybe you dont. But when updating from 0.11 to 0.12, I lost my username/password for the port 8384.  

Saving them again works.

**Comment by AudriusButkevicius** [comment]
So I just tested this, upgrading from a v10 to v12, and it works fine, so I think you didn't have the password set in the first place.

**Comment by calmh** [comment]
Cannot reproduce this one either. There's also no change to the config format around the user settings between v0.11 and v0.12 so it would be surprising.

**Comment by wweich** [comment]
I noticed the other day, that there was no password prompt anymore when accessing the WebUI on Android with a browser.
The username and password, which was automatically set by Syncthing Android, were empty.
I can't remember when I last accessed the WebUI and if there was till a password prompt, so it could be that this changed after the upgrade to v0.12.

**Comment by calmh** [comment]
Certainly survives an upgrade from v0.11.26 to 0.12.4 at least, I just tested.
