### ISSUE TITLE
Feature Request: Ignore root directory except some folders

### ISSUE THREAD

**Issue by dlang9159** [syncthing/syncthing#2489]
I got a folder synced between multiple devices. From time to time I use some subdirectories on my mobile pc. Is there a way to ignore the whole root directory on my laptop and use "!" to include the subdirectories I need?

If not I propose an new ignore operator doing that.

Thanks!

**Comment by calmh** [comment]
Doesn't it work to do exactly what you suggest?

```
*
!somedir
```

**Comment by calmh** [comment]
If not, please add input in #2491.
