### ISSUE TITLE
Missing " / " at the beginning folder paths added using dropdown list

### ISSUE THREAD

**Issue by chris-thorn** [syncthing/syncthing#2495]
This applies to Syncthing v0.12.3 on Linux (32-bit, 64-bit and ARM).

When a new folder is added using the dropdown **Folder Path** list, the leading forward slash is omitted, so I get folders listed as `home/chris/sync` instead of `/home/chris/sync`.

**Comment by AudriusButkevicius** [comment]
Can you provide a screenshot of the dropdown showing the wrong path?

**Comment by chris-thorn** [comment]
Sure!

**Folder Path with leading slash**
![Folder Path with leading slash](http://i.imgur.com/T1kOHx8.png)

**Folder Path without leading slash**
![Folder Path without leading slash](http://i.imgur.com/KA6s3Cf.png)

**Comment by AudriusButkevicius** [comment]
But you are typing it that way deliberately, I am sure if you were to put a trailing slash, it would be preserved?

**Comment by chris-thorn** [comment]
Ah, OK, fair point :) Yes, the leading slash is preserved if I begin typing `/home/...`.

In that case, maybe this issue could be considered as an enhancement request: a leading forward slash should be added to the Folder Path as it is being typed (or somehow shown to the left of the input box) to indicate that whatever is typed is relative to the root of the filesystem.

It really is a very minor issue, but it's an inconsitency nonetheless.

**Comment by AudriusButkevicius** [comment]
Does it actually cause any issues?

**Comment by chris-thorn** [comment]
No

**Comment by calmh** [comment]
Relative folder paths are perfectly fine, we depend on having them in a number of situations. In your case I guess you're starting syncthing from a service that sets / as it's cwd, so the two are equivalent. Usually they are not. I think this is a "functions as design" thing. If you typed `/home` and we removed the initial slash, or if you typed `~` and it expanded to a non-absolute path that would be a bug.

**Comment by chris-thorn** [comment]
Ah, OK, that makes sense - I hadn't considered it from that point of view.

Super work guys - this really is a fantascially useful tool :)
