### ISSUE TITLE
CheckFolderHealth wakes up disk at index exchange

### ISSUE THREAD

**Issue by alex2108** [syncthing/syncthing#2497]
When a device is connecting syncthing checks the folder health and thus the disk with the folder starts spinning (folder is 100% in sync).  [Here](https://github.com/syncthing/syncthing/blob/3f94e70/lib/model/rwfolder.go#L243) the check seems to happen during index exchange, maybe this check could be moved to some other place?

**Comment by calmh** [comment]
Maybe, possibly, it could be moved to down [here](https://github.com/syncthing/syncthing/blob/master/lib/model/rwfolder.go#L452) as a `once.Do` kind of thing. Investigation needed. We don't want to do too much work on a folder that doesn't exist any more.

**Comment by bigbear2nd** [comment]
I wouldnt mind more "work" of the pc, if the harddisks stop spinning if there is no change anymore. Maybe this could be added as a feature in a "NAS-mode" of syncthing?

**Comment by calmh** [comment]
Oh it should go in and be the same everywhere. The "do work" comment was related to it not being super obvious at first glance where the first point the code that we actually start touching files is.

We spin up a bunch of routines that are ready to copy and move and stuff, and then feed them the files to handle. This all becomes a no-op if we don't actually feed them any files, but currently the point at which we know there are no files to handle is a bit late - if there *were* files to handle, we would already have done stuff before performing the check.

So some care needs to be taken. But yes, we should not touch the disks unless we were going to anyway.

**Comment by Skaronator** [comment]
Any progress on this 400 days old issue?

**Comment by calmh** [comment]
Nope.

**Comment by alex2108** [comment]
I think my disk does not spin up any more when just connecting because due to delta index there is no actual index exchange happening any more when nothing changed. (the disk where the folders are, index is not on a spinning disk).
When I have time I may verify if it does not access the disk at all or if some caching prevents the spin-up.
