### ISSUE TITLE
Syncthing doesn't appear to log on Windows

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#2502]
Somewhere after v0.11.7, Syncthing stopped writing to its log file on Windows.

**Comment by calmh** [comment]
It logs perfectly fine for me in 0.12.4. I start it without parameters on Windows, 

```
C:\Users\jb\Desktop>syncthing
[monitor] 11:07:36 INFO: Log output saved to file "C:\Users\jb\AppData\Local\Syncthing\syncthing.log"
```

and what it says should happen actually does happen. So no repro on this one.

**Comment by calmh** [comment]
Are you running with STNORESTART=1 by the way? That disables the monitor process, which is the one that does the logging.

**Comment by canton7** [comment]
Ah, that'll be it. This is a change in behaviour v0.11.something?

**Comment by calmh** [comment]
I don't think so, I think we've always logged from the monitor.

**Comment by canton7** [comment]
How very odd - I wonder why Syncthing still logged pre-0.11.7 then. 

Is there any way I can get Syncthing's home directory, before actually starting it (e.g. by passing it a command-line flag?). It would be nice to programmatically determine where the monitor would have logged to had it been running.

**Comment by calmh** [comment]
%LocalAppData%/Syncthing/syncthing.log on Windows

**Comment by canton7** [comment]
Cool, I'll just assume you won't change that, then :smile:

**Comment by calmh** [comment]
Not without letting you know, I promise. :)
