### ISSUE TITLE
"The Syncthing admin interface is configured to allow remote access without a password"

### ISSUE THREAD

**Issue by oderwat** [syncthing/syncthing#2503]
The Message "The Syncthing admin interface is configured to allow remote access without a password" is very annoying!

How can I suppress it? 

We run our Syncthing admin interface on VPN addresses and that message just makes it look like something that is not be safe where in fact it is probably even saver than open net with some password.

**Comment by canton7** [comment]
There's a setting in the advanced config: `insecureAdminAccess1`

**Comment by kozec** [comment]
I'm getting this message on 127.0.0.1 (localhost) as well. Is that intended behavior?

**Comment by canton7** [comment]
What's the listen address in the config?

**Comment by oderwat** [comment]
Imho it could filter all private networks silently. I mean.. if somebody uses 192.168.x.y / 10.x.y.z / 176.16.x.y for example, they may know what they do. But then, setting a flag is easy. Probably just mention how to squelch the message in the warning.

**Comment by kozec** [comment]
> What's the listen address in the config?

0.0.0.0. I'm getting same when connecting to 10.0.0.8 (my local LAN IP), even if I configure daemon to listen only on that address. It looks like only way to not get message is to set *listen* address to localhost.

**Comment by oderwat** [comment]
Well 0.0.0.0 means "bind on all available interfaces" and I guess thats what the message was created for!

**Comment by canton7** [comment]
Correct, it'd a warning that Syncthing is potentially accessible from the outside world, and isn't password protected.

**Comment by kozec** [comment]
> Correct, it's a warning that Syncthing is potentially accessible from the outside world, and isn't password protected.

Well, that machine has only loopback and LAN interface, so outside world can't connect even if daemon listens on 0.0.0.0, but I guess Syncthing doesn't checks for that.

**Comment by oderwat** [comment]
Thing is: It does not depend on that machine if it is accessible from outside. Just imagine a portmap is created in the router. This could point port 12345 to your internal machine port 80 and you may not even know that nor could Syncthing. The only really save address is 127.x.y.z everything else could be reached from another machine in the network and hence from the outside world.
