### ISSUE TITLE
Adding new share/folder changes 'ignoreDelete' tags to 'false'

### ISSUE THREAD

**Issue by sebukoleth** [syncthing/syncthing#2504]
I have some folders on my Linux server that should ignore any deletes made on the folder shared from my other machines. Every time I add a new shared folder to my Lniux box, the 'ignoreDelete' tags of each of those folders that need to ignore deletes changes back to 'false'

**Comment by sebukoleth** [comment]
v 0.12.4

**Comment by calmh** [comment]
Wat

**Comment by calmh** [comment]
Hmm, I can't reproduce this by adding a folder through the web GUI. Can you describe in more detail how you make this happen?

**Comment by AudriusButkevicius** [comment]
I feel this is another one of these csrf issues where we think were authenticated, but the UI is readonly, and the assumption that the setting is saved is actually wrong.
