### ISSUE TITLE
IANA: Service Name and Transport Protocol Port Number Registry

### ISSUE THREAD

**Issue by marclaporte** [syncthing/syncthing#2506]
Please see:
http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml

21027 is available
22000 and 8384 are taken

Is this something we care about? 

If so, perhaps something for 0.13.x or 0.14.x?

Thanks!

**Comment by AudriusButkevicius** [comment]
Why does this matter?

**Comment by calmh** [comment]
No, this is not something we care about. :)
