### ISSUE TITLE
FATAL: stderr: pipe: function not implemented

### ISSUE THREAD

**Issue by ilikeorangutans** [syncthing/syncthing#2507]
Downloaded syncthing 0.12.3 on my DroboFS and it started fine. It soon upgraded to 0.12.4 and since then won't start anymore. I get this error: 
```
# ./syncthing
[monitor] 15:01:55 FATAL: stderr: pipe: function not implemented
```

Additional information:
```
# uname -a
Linux Drobo-FS 2.6.22.18 #1 Fri Aug 14 14:18:12 PDT 2015 armv5tejl GNU/Linux
```

**Comment by AudriusButkevicius** [comment]
How did you install it/start it the first time?

**Comment by ilikeorangutans** [comment]
First time it started just fine, not sure how though. Looking at the history of https://github.com/syncthing/syncthing/blob/master/cmd/syncthing/monitor.go if it changed recently. :/ 
 
Did a little digging. https://golang.org/src/os/pipe_linux.go?s=319:360#L1 : 

> // pipe2 was added in 2.6.27 and our minimum requirement is 2.6.23, so it
> // might not be implemented.

I guess that explains why... You think there's a possible workaround or should I close this issue?

**Comment by AudriusButkevicius** [comment]
Just start it without the monitor process (and wrap it in a service manager to perform restarts instead), see systemd units in etc directory. Basically env var STNORESTART=1, and make sure you handle the exit codes correctly.

**Comment by ilikeorangutans** [comment]
That worked! Thanks! :+1:
