### ISSUE TITLE
Upgrade can delete previous version config file if it is "old"

### ISSUE THREAD

**Issue by simplypeachy** [syncthing/syncthing#2509]
If the user hasn't made any changes to the configuration in a month or more, and they upgrade Syncthing, the previous config file is deleted by the [clean-up routine](https://github.com/syncthing/syncthing/blob/db4f23f3771e56184a93474f1939508044cb1ce0/cmd/syncthing/main.go#L1071).

Presumably this isn't desired behaviour - maybe the config upgrade routine could timestamp the old file, so as not to invoke the wrath of the clean-up routine.

**Comment by AudriusButkevicius** [comment]
I think we constantly save the file as we are running, but I might be wrong. The right thing todo is to touch the file on startup.

**Comment by calmh** [comment]
I don't see how we would do that, regardless of how old the config file is?

**Comment by AudriusButkevicius** [comment]
I guess that's the argument, that if a config is old, and you suddenly decide to upgrade, you lose the ability to rollback.

**Comment by simplypeachy** [comment]
I just upgraded one instance from 0.11.26 to 0.12.4. It logged that it archived the 0.11 config file, and then that it cleaned it up (i.e. deleted it).

**Comment by simplypeachy** [comment]
@AudriusButkevicius: Yeah, I'd rather have the previous version's config file available in case I need to downgrade. Once it reaches the "old age" in the clean-up routine then I would think it's safe to delete it.

**Comment by calmh** [comment]
Aha, I see.
