### ISSUE TITLE
Out of Sync with (modified) Filedate 01.01.1601 on NTFS Drive

### ISSUE THREAD

**Issue by sisu4syncthing** [syncthing/syncthing#2511]
Hi,
I'm using v0.12.4, Windows (64 bit) and same version on Linux.

The source files are on a NTFS Drive and it seems, the problem is related to the filedate (modified date), which is 01.01.1601.
The creation Dates are around the 01.11.2014.

I found the files synced to the linux machine, but always stay in the "Out of Sync files" List on the Windows Machine, which acts as a "Folder Master" here. 

The synced files on the Linux Machine have the (modified) filedate 09.05.1913 (checked via samba and on the linux console)

Is there any way to sync those files, *without* changing the filedate? (...because I'm not allowed to change those files on the local drive)

Foldersettings:
![3](https://cloud.githubusercontent.com/assets/12977080/11353284/20532f1a-9242-11e5-8d4d-0de426ce5b5d.png)

Windows explorer on a concerned file:
![1](https://cloud.githubusercontent.com/assets/12977080/11353282/205218be-9242-11e5-9aac-992f03a28245.png)

Window WebGUI:
![2](https://cloud.githubusercontent.com/assets/12977080/11353283/205324e8-9242-11e5-8903-93252d5439c2.png)

**Comment by AudriusButkevicius** [comment]
No, modification time is necessary to sync, though dates should not be in the past.
Are you saying you deliberately set dates in the past?

Read about master mode to understand what it means. You can press override changes to enforce masters view of things across the cluster.

**Comment by capi** [comment]
@AudriusButkevicius could it be that it's not possible to set 1601 as year for a file on the Linux file system in question and that's the reason it's staying "out-of-sync"?

**Comment by AudriusButkevicius** [comment]
I wonder what int windows returns for that date, given its before the epoch. Regardles OP needs to explain this before we can do anything.

**Comment by capi** [comment]
According to [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724290%28v=vs.85%29.aspx), 1601-01-01 is beginning of epoch for NTFS:

> A file time is a 64-bit value that represents the number of 100-nanosecond intervals that have elapsed since 12:00 A.M. January 1, 1601 Coordinated Universal Time (UTC). The system records file times when applications create, access, and write to files.

So it will return 0. That would explain it.

**Comment by AudriusButkevicius** [comment]
So I am closing this as OP hopes to preserve modification times which is not possible, as syncthing uses that to stay in sync. Furthermore, the issue seems that the mtime.he has on Windows has no meaningful value on linux, hence the value gets replaced with something that works on linux and hence makes the master look out of sync.

**Comment by capi** [comment]
Still, this could be worked around using virtual mtimes like on Android, couldn't it?

**Comment by sisu4syncthing** [comment]
@AudriusButkevicius 
"are you saying you deliberately set dates in the past?"
No, I just encountered them. no clue what or who set those date 01.01.1601.

"You can press override changes to enforce masters view of things across the cluster."
True, but those files will always stay out of sync (at least, when syncthing is restarted on the windows machine)

"I wonder what int windows returns for that date, given its before the epoch. Regardles OP needs to explain this before we can do anything."
Actually, I don't know what you mean. Please let me know, how I can give you the needed informations.

**Comment by AudriusButkevicius** [comment]
So just change the buggy dates to something after 1970 on master and you should be fine. Also, make sure that you are not mounting your filesystem with some funky options which disable modification times. For example open the file, modify it and save it, and the date should become tue current date, and that should fix it.

Virtualmtimes is a workaround for not being able to adjust them, not a solution for not them staying at the same place or travelling backwards.

**Comment by capi** [comment]
@AudriusButkevicius I understood the author that they were at this timestamp from the beginning. And in this case I think one could argue that Syncthing should care about the fact that it cannot synchronize a legitimate file from NTFS to Linux. But I also tend to agree with you, that a proper way of handling rare situations like these tend to complicate matters so much, that in general it's not worth it.

**Comment by sisu4syncthing** [comment]
@AudriusButkevicius @capi 
my userrights on this folder are read only (User in a Domain) and those filedates were there in the beginning.
I was just wondering, how to get rid of the "out of sync"-list for those files, because its irritating to see out of sync files, when they're correctly synced. (execpt the correct filedate)

If its not possible, to solve this "problem" within syncthing, I need to contact the admin here to maybe change the date for some files, or will skip the files unluckily with the ignore list.

Thanks for the help!

**Comment by AudriusButkevicius** [comment]
Well I don't think you can solve this in syncthing, as its not a syncthing problem. It's a problem with linux, so that the oldest date you can have on linux is 1970-01-01.

**Comment by wweich** [comment]
Thats not really true. I just set a file date to 1601 on my ubuntu server with ext4.
```
$ touch -d '1601-01-01 01:00:00' testfile
$ ls -l testfile
-rw-rw-r-- 1 wweich wweich 0 Jan  1  1601 testfile
```

**Comment by AudriusButkevicius** [comment]
Hmm

**Comment by AudriusButkevicius** [comment]
So if you override on master, does that not help?

**Comment by capi** [comment]
@wweich I just tested it on a 32-bit box, there your command fails with "invalid date format", whereas on my 64-bit box it succeeds.

@sisu4syncthing Your Linux box, is it 32 or 64 bit, and which filesystem do you want to sync to?

**Comment by wweich** [comment]
Did try it on ubuntu 8.04 32bit with ext3, which also resulted in `invalid date format`.
The minimum I could find was:
```
$ touch -d '1901-12-13 21:00:00UTC' testfile
$ ls -l testfile
-rw-r--r-- 1 root root 0 1901-12-13 22:00 testfile
$ stat testfile
  File: `testfile'
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 801h/2049d      Inode: 2342917     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 1901-12-13 22:00:00.000000000 +0100
Modify: 1901-12-13 22:00:00.000000000 +0100
Change: 2015-11-24 13:08:33.000000000 +0100
```

**Comment by capi** [comment]
I actually think it's a 32-bit vs. 64-bit issue, since there'll be no negative number in {{size_t}} that can represent times before 1901-12-13 20:45:52UTC on a 32-bit system.

    martin@vdr2:~$ touch -d '1901-12-13 20:45:52UTC' testfile
    martin@vdr2:~$ stat -c "%Y" testfile 
    -2147483648

**Comment by calmh** [comment]
Yeah. `time_t` is 32 bit on 32 bit systems. So there's literally no way to tell the system about dates earlier than that.

**Comment by sisu4syncthing** [comment]
Hi all, sorry for the late reply...

@AudriusButkevicius
 "So if you override on master, does that not help?"
Partially. After overriding, it seems to work, but after restarting Syncthing on Windows, the files show up again in the "Out of Sync"-List.

@capi
"Your Linux box, is it 32 or 64 bit, and which filesystem do you want to sync to?"

The Linux machine is a Synology NAS DS1815+.
`uname -a` gives: `Linux Server 3.10.35 #5644 SMP Wed Oct 28 12:36:28 CST 2015 x86_64 GNU/Linux`
(If there is any other/better way to find out if 32/64 Bit, please let me know...)

I sync from the Windows Machine, which is a Folder Master, to the Linux Machine.


I tried the above commands and here are the results:

`Server> touch -d '1901-12-13 20:45:52UTC' testfile`
`touch: invalid date format '1901-12-13 20:45:52UTC'`
`Server> stat -c "%Y" testfile`
`stat: cannot stat 'testfile': No such file or directory`
now with a "normal" date:
`Server> touch -d '2001-12-13 20:45:52UTC' testfile`
`Server> stat -c "%Y" testfile`
`1008276352`

`stat -c "%Y"`
with the file from my screenshots SAM_1960.JPG returnes this:
`-1787664119`

`stat SAM_1960.JPG` returnes:
`  File: SAM_1960.JPG`
`  Size: 2609539         Blocks: 5104       IO Block: 4096   regular file`
`Device: fd00h/64768d    Inode: 215023747   Links: 1`
`Access: (0644/-rw-r--r--)  Uid: (  100/syncthing)   Gid: (  100/   users)`
`Access: 2015-11-24 17:34:46.953410263 +0100`
`Modify: 1913-05-09 11:38:01.000000000 +0100`
`Change: 2015-11-24 09:55:33.779427328 +0100`

**Comment by capi** [comment]
@sisu4syncthing What I expected, it's a 32-bit box, so no way to represent the file-date correctly. The question for the developers remains, if this is a case which could/should be worked around (e.g. introducing "virtual mtime" (like on Android) for dates too old or if this simply will be an unsupported case.

**Comment by wweich** [comment]
AFAIK "x86_64" means 64Bit. The [NAS Spec Sheat](https://www.synology.com/en-global/products/DS1815+#spec) says 64Bit, too, as does the [Spec Sheat of the Atom C2538](http://ark.intel.com/de/products/77981/Intel-Atom-Processor-C2538-2M-Cache-2_40-GHz).

So it's more likely, that the underlying system has the limitation.

Synology usually uses ext4 in their current nas devices.

**Comment by sisu4syncthing** [comment]
`mount` for the virtual disk  which stores the mentioned files:
`/dev/vg1000/lv on /volume1 type ext4 (usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,synoacl)`

**Comment by calmh** [comment]
Ext4 seems to store timestamps as 32 bit signed unix epoch seconds, plus a separate 32 bit nanosecond field. This gives the "usual" range of ~1902 - ~2038. On 64 bit systems (?) the on disk format is extended to use 34 bits for the first second parts, giving a range of ~1698 - ~2242. Or so I gather from some Googling. It doesn't look like 1601 is a year that can be stored. Which is sort of fine by me as I don't think we were creating or modifying files at that point in time. I think this is a non-bug.
