### ISSUE TITLE
Spelling mistake in German translation

### ISSUE THREAD

**Issue by DustInCompetent** [syncthing/syncthing#2514]
The German info text under the "Device Name" textbox says

> Wenn kein Gerätename **anegegeben** wird, wird der Name des entfernten Gerätes genommen.

It should be

> Wenn kein Gerätename **angegeben** wird, wird der Name des entfernten Gerätes genommen.

**Comment by AudriusButkevicius** [comment]
Feel free to fix it: https://www.transifex.com/syncthing/syncthing/
