### ISSUE TITLE
Syncthing shows the wrong GUI address at startup

### ISSUE THREAD

**Issue by cippaciong** [syncthing/syncthing#2516]
Hello, I downloaded Syncthing 0.12.4 on my server and ran the binary for the first time in order to generate the config files and folder. After that I replaced 127.0.0.1 with 0.0.0.0 in the GUI address field in config.xml and restarted Syncthing. During the startup, even if the change is applied correctly (I can connect to the GUI remotely), this message is displayed.
`19:32:27 INFO: GUI URL is https://127.0.0.1:8384/`

**Comment by calmh** [comment]
That's the URL that you can click or copy into a browser to get the UI, and it works even with a 0.0.0.0 listen address. However https://0.0.0.0:8384/ does not, at least on Windows. From another computer you need another URL of course, but we don't know what is based on just the 0.0.0.0 we have in the config.
