### ISSUE TITLE
A command line flag for disabling relay use would be really helpful!

### ISSUE THREAD

**Issue by sneak** [syncthing/syncthing#2518]
It would be nice to have a command line flag for disabling relay use, much like there are command line flags for disabling restart and such.  I run syncthing from docker and editing XML is much harder to do in a startup script...

Thank you for your time and consideration!

**Comment by calmh** [comment]
Disabling restart affects how we launch and kind of must be known before we parse the config file. Disabling relaying is just one out of the many config options though, so I think special casing it is probably not worth it. You can use for example `sed 's/relaysEnabled>true/relaysEnabled>false/'` to set the option in the config file from the outside.
