### ISSUE TITLE
Should honor umask when creating shared folder

### ISSUE THREAD

**Issue by dhs-rec** [syncthing/syncthing#2519]
SyncThing 0.12.4, sync from Windows to Linux (Ubuntu), "Ignore Permissions" checked when adding a new folder (synched from Windows, if that matters) on Linux side, with umask set to 0022 in /etc/init/syncthing.conf for Upstart.

The umask setting is honored for the folder content, but not for the folder itself, which is always created with permissions 0700 instead of 0755.

**Comment by calmh** [comment]
It only creates it once though, so you can chmod it afterwards. Possibly we should follow the unmask here as well, I'm not sure.

**Comment by dhs-rec** [comment]
chmod'ing afterwards is what I currently do. But that means logging in to N machines for every newly shared folder, with an increasing N. That's not a long term option.

It doesn't make sense not to follow umask here.

**Comment by calmh** [comment]
Almost a matter of just changing a `0700` to a `0777`. However needs investigation what happens on Windows. We don't want to create an all-writeable folder by default.

**Comment by dhs-rec** [comment]
Great, thanks a lot!
