### ISSUE TITLE
SymLinked files get synchronized fine, but not SymLinked directory

### ISSUE THREAD

**Issue by longxk** [syncthing/syncthing#2524]
Both node are running linux version (0.12.4), SymLinked files synchronization is OK, but Syncthing gives error message for SymLinked directory: `INFO: Puller: final: symlink ../aaa/bbb/ccc /home/xxx/yyy/zzz: invalid argument`.
I googled for this error, find out it can happen on platform that don't support symbolic link, but on linux there must be something else going wrong.

**Comment by AudriusButkevicius** [comment]
uname -a ?

**Comment by AudriusButkevicius** [comment]
Also, make sure you have write permissions in the folder above.

**Comment by AudriusButkevicius** [comment]
Also try creating the link yourself by hand

**Comment by longxk** [comment]
definitely have write permission, and symbolic link by hand is ok.

Debian 8.0 64bit VPS:
`Linux 2.6.32-042stab094.8 #1 SMP Tue Dec 16 20:36:56 MSK 2014 x86_64 GNU/Linux`

mount output:
```
/vz/private/37751 on / type simfs (rw,relatime)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,mode=755,gid=500)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
mqueue on /dev/mqueue type mqueue (rw,relatime)
tmpfs on /tmp type tmpfs (rw)
none on /run/shm type tmpfs (rw,relatime)
```

**Comment by longxk** [comment]
definitely have write permission, and symbolic link by hand is ok.

Debian 8.0 64bit VPS:
`Linux 2.6.32-042stab094.8 #1 SMP Tue Dec 16 20:36:56 MSK 2014 x86_64 GNU/Linux`

mount output:
```
/vz/private/37751 on / type simfs (rw,relatime)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,mode=755,gid=500)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
mqueue on /dev/mqueue type mqueue (rw,relatime)
tmpfs on /tmp type tmpfs (rw)
none on /run/shm type tmpfs (rw,relatime)
```

**Comment by AudriusButkevicius** [comment]
Sadly I don't think we can debug this without access to that machine and that kernel. It does seem like a very old (and potentially non-standard) kernel for debian 8. You should try downloading go, and try creating the symlink using the stdlib, if that fails, then you should probably open a bug in the golang tracker. We don't do anything magical, so I don't think its our direct fault.

**Comment by longxk** [comment]
I tried creating a symlink to directory using golang on that machine, the result is ok.
`os.Symlink("../go", "go-test")`
`go version go1.5.1 linux/amd64`

**Comment by AudriusButkevicius** [comment]
Yeah you can email me the details.
