### ISSUE TITLE
Wireshark disector for syncthing

### ISSUE THREAD

**Issue by CanadianJeff** [syncthing/syncthing#2526]
currently its showing up as MNDP Malformed Packet

Screenshot can be found here...
http://i.imgur.com/jXn5HFJ.png

**Comment by AudriusButkevicius** [comment]
It's identifying the wrong protocol. What's the issue here?

**Comment by CanadianJeff** [comment]
thats not a reason to close this

**Comment by AudriusButkevicius** [comment]
Are you willing to implement it?

**Comment by CanadianJeff** [comment]
I dont speak the syncthing protocol so I would not know where to begin

wireshark has been around for years shocked no one else has already

**Comment by AudriusButkevicius** [comment]
Well, because you can read the docs to understand the protocol.
I don't see a reason why anyone would waste time implementing a disector.

**Comment by AudriusButkevicius** [comment]
The other thing is, syncthing uses TLS, with ciphers which ensure forward secrecy, so it would be a lot of effort (if even possible) to even recover the plaintext of the protocol.

**Comment by calmh** [comment]
It isn't, per definition. You need to lobotomize the cipher suite first to be able to decode it after the fact. So at this point, it is impossible.
