### ISSUE TITLE
Connection closed (xdr read: bytes field exceeds size limit)

### ISSUE THREAD

**Issue by gstraube** [syncthing/syncthing#2527]
I am trying to introduce two Syncthing nodes to each other. One of them is running on a Linux notebook:

```syncthing v0.12.4 "Beryllium Bedbug" (go1.4.3 linux-386 default) unknown-user@build2.syncthing.net 2015-11-22 15:05:20 UTC```

The other one is running on Android (Syncthing version: v0.11.22, Syncthing-Android version: 0.6.6).

I get the following error message on the Linux node:
```[54U7I] 2015/11/28 14:56:58.750294 connections.go:233: INFO: Established secure connection to WVSZWFA-A6P4WUB-77JCATN-J6J676E-63YTQKI-OZHVXZA-RFMCUDK-LM5FAAP at 192.168.1.101:51020-192.168.1.232:22000 (direct-dial)
[54U7I] 2015/11/28 14:56:58.751288 model.go:726: INFO: Connection to WVSZWFA-A6P4WUB-77JCATN-J6J676E-63YTQKI-OZHVXZA-RFMCUDK-LM5FAAP closed: xdr read: bytes field exceeds size limit; 1634624626 > 32```

And also on the Android node:
```I/SyncthingNativeCode(27330): [WVSZW] 13:57:42 INFO: Established secure connection to 54U7I3N-HD6E5MS-6NNBVY2-I25IBP3-YV7ABKF-FX7Z5R7-OJWKBFV-TQXIRAF at 192.168.1.232:22000-192.168.1.101:51029
I/SyncthingNativeCode(27330): [WVSZW] 13:57:42 INFO: Connection to 54U7I3N-HD6E5MS-6NNBVY2-I25IBP3-YV7ABKF-FX7Z5R7-OJWKBFV-TQXIRAF closed: xdr read: bytes field exceeds size limit; 1982869041 > 64```

**Comment by AudriusButkevicius** [comment]
You are using incompatible versions.

**Comment by canton7** [comment]
(To expand, v0.11 and v0.12 are incompatible, and can't talk to each other. Make sure you're using v0.12 on both sides)

**Comment by gstraube** [comment]
You're right, updating to the newest version of Syncthing-Android (which uses v0.12) fixed the problem. Thank you!
