### ISSUE TITLE
Syncthing exits with message stderr: pipe: function not implemented on ARMv5

### ISSUE THREAD

**Issue by plafue** [syncthing/syncthing#2528]
In version 0.12.4 syncthing exits right away when running on an ARMv5 processor with the message 

`[monitor] 19:46:52 FATAL: stderr: pipe: function not implemented`.

Version 0.12.3 starts without problems.

See attached strace output: [out.txt](https://github.com/syncthing/syncthing/files/46400/out.txt).

**Comment by AudriusButkevicius** [comment]
Please be a good citizen and check for closed issues before opening new ones:

https://github.com/syncthing/syncthing/issues/2507

**Comment by plafue** [comment]
Sorry for the duplicate and thanks for the prompt reply
