### ISSUE TITLE
Add a option in folders that can explain what a folder it is.

### ISSUE THREAD

**Issue by oska874** [syncthing/syncthing#2533]
Add a option in folders that can explain what a folder it is.So that we can know waht a sync folder  is and what does it used to do.

**Comment by kluppy** [comment]
I take it you would like a description field for each share.
Can you explain the use case a little more?
Would it only be for use in the local GUI or do you mean for it to be presented to a node when it is invited to a share?

**Comment by oska874** [comment]
Because folder name is short and we often add many folders that has different function and function. Sometimes we will forget what does one folder initial do. If add a description ,then we can know what this folder is and make no mistake.

**Comment by wweich** [comment]
Folder names can be 256 bytes. I would not say that this is short. So you have plenty of room to name your folders in a way that can describe its function.

**Comment by AudriusButkevicius** [comment]
Agree, 256 is enough. Also, if you can't recognize whats what, you are naming them wrong.

**Comment by calmh** [comment]
Also #966
