### ISSUE TITLE
Which version of Windows are supported for v0.12.5? how about v0.12.4 and before?

### ISSUE THREAD

**Issue by Enlightenment** [syncthing/syncthing#2536]
In the release notes for v0.12.5...
* https://github.com/syncthing/syncthing/releases/tag/v0.12.5

I noticed the change from 3072-bit RSA certificates to 384-bit ECDSA certificates...
* https://github.com/syncthing/syncthing/pull/2523

so I decided to check this ECC Compatibility list, and noticed that Windows Vista is required...
* https://support.globalsign.com/customer/portal/articles/1995283-ecc-compatibility

which lead me to look for minimum Windows requirements for Syncthing, but I couldn't find any mandatory requirements.  Where are the requirements?  Does this certificate change force a NEW windows requirement?  

Please clarify here, and please state these requirements in the download page or somewhere obvious.  Thanks in advance!

**Comment by Enlightenment** [comment]
by "Windows Vista", I meant "Windows Vista or later Windows"

**Comment by AudriusButkevicius** [comment]
I believe we don't rely on Windows certificate generation, nor the key store nor API's for validating, so I don't see why the minimum requirement would have changed.

If you have questions, please use the forum, rather than polluting the bug tracker.

**Comment by calmh** [comment]
Yeah, this should have no effect on that. We have users on XP, so at least that mostly works. :)

Had this been a change in os requirements the bug tracker would have been an appropriate place to file for a clarification, so "pollution" is a bit strong here.

**Comment by AudriusButkevicius** [comment]
Well, I prefer people would use the forum as first point of contact, as the content just rolls off of without the need to close anything. Same goes for "Oh it doesn't connect" issues which are more support requests than actual bugs. Less management overhead
