### ISSUE TITLE
Can't scroll to bottom of Anonymous Usage Reporting Preview / access close button

### ISSUE THREAD

**Issue by kluppy** [syncthing/syncthing#2537]
My screen size is to small to see the bottom of the Anonymous Usage Reporting Preview and I can't scroll to see it.
![screenshot from 2015-11-30 22 06 39](https://cloud.githubusercontent.com/assets/15791666/11471132/c561c374-97ae-11e5-87cb-2a0c40681c1c.png)

**Comment by canton7** [comment]
I wonder whether this is the same issue as #2041 (fixed in #2062)...

**Comment by AudriusButkevicius** [comment]
I think it is

**Comment by kluppy** [comment]
I am guessing this is similar to #2041 but I cannot follow the JS well enough to fix it for myself.
Adding a break point at line 1418 in syncthingController.js solves the problem for me.

**Comment by canton7** [comment]
Did this occur when attempting to preview the usage reporting into (by clicking 'Preview' in the settings), or when Syncthing actually prompted you to submit usage reporting info?

**Comment by kluppy** [comment]
When clicking preview.

**Comment by canton7** [comment]
Cool, I've got a fix ready to go. 5 mins...

**Comment by canton7** [comment]
See #2538.

**Comment by kluppy** [comment]
I was trying to work on this but got stuck. Changes I made in syncthingController.js didn't seem to be compiled.
Is this because I needed to update gui.files.go as well?

Am I missing something with how the GUI works?

**Comment by canton7** [comment]
For development, it's easiest to set STGUIASSETS to point to your `gui` folder. Then any changes made to any files in `gui` will be immediately reflected.

For deployment, run `./build.sh assets`, which compiles the assets into files in `lib/auto`. You'll then need to rebuild and restart syncthing.

**Comment by kluppy** [comment]
Thank you.
