### ISSUE TITLE
Corruption detected during database compaction at startup should be handled automatically

### ISSUE THREAD

**Issue by razem-io** [syncthing/syncthing#2541]
Hello,

syncthing worked flawless for me since a long time. Recently I switched my root Server and since then I encounter heavy issues which I cannot explain. 

I found out that disabling the IPv6 interface solves the issue. I need IPv6 so this isn't an option.

Sadly I can't see anything good in the logs:

```
[OIXN6] 23:16:26 INFO: Established secure connection to <client-id> at <server-ip>:56135-<client-ip>:22000 (direct-dial)
[OIXN6] 23:16:26 INFO: Device <client-id> client is "syncthing v0.12.5" named "HeimNinja"
tail: syncthing.log: file truncated
[OIXN6] 23:16:26 INFO: syncthing v0.12.5 "Beryllium Bedbug" (go1.5.1 linux-amd64 default) jenkins@build2.syncthing.net 2015-11-29 07:55:38 UTC
[OIXN6] 23:16:26 INFO: My ID: <server-id>
[OIXN6] 23:16:26 INFO: Single thread hash performance is ~175 MB/s
[OIXN6] 23:16:29 INFO: Compacting database: leveldb/table: corruption on data-block (pos=1142353): checksum mismatch, want=0x8c8a19a3 got=0xe0351de0 [file=024164.ldb]
````

One can see that Syncthing just restarts. This happens 2 times in a row every 5 minutes. If more then 2 clients try to connect to the server it restarts so fast that the web interface isn't usable anymore. 

When I issue the following command: `echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6` syncthing will work but IPv6 will be disabled until I restart or revoke the command. Syncthing will stop working / restart after.

The clients show that they where connected but the server does not. 

```
Server last connected timestamp: 2015-11-16 09:35:35
Client last connected timestamp: 2015-11-30 23:26:03
```

Any ideas? What would be userful in order to debug this problem? Thank you for any help regarding this matter.

**Comment by AudriusButkevicius** [comment]
Sorry, but I am sure disabling IPv6 does not fix database corruption.

**Comment by razem-io** [comment]
Ah! Will check that immediately. That might have happend during my efforts to fix the IPv6 issue.

**Comment by razem-io** [comment]
You are right. Sorry! I was able to reproduce the IPv6 issue two month ago several times in a row. Then I just disabled IPv6 and it worked flawless. Then 2 to 3 weeks ago I had to enable IPv6 again and got the error I described above. I jumped to the conclusion that it is the IPv6 problem again without checking if I can reproduce. Sometimes one is lazy sorry.

Might I ask however why the database isn't dismissed and a rescan is done instead?

**Comment by AudriusButkevicius** [comment]
Because it can happen at any part of the program, essentially any thread, so it would be a lot of boilerplate code to try and catch it.

**Comment by razem-io** [comment]
Just a thought. I hope I dont waste your time. Wouldn't it be possible to check the database health on startup? When the database is corrupted it restarts anyway and the check would then detect the error in the database.

**Comment by AudriusButkevicius** [comment]
We could, but that would slow down startup I think.

@calmh what do you think? We could range the whole keyspace.

**Comment by calmh** [comment]
Yeah. We do already handle problems when opening the database (including wipe and rescan), but not in the new compacting code. We should do it there at the very least. I think what will happen if we discover corruption at any other point is we crash, and then the corruption should be noted again by the opening or compaction code and then we wipe the db...

So yes, we *should* recover automatically but we don't at this point since I added the compaction.

**Comment by calmh** [comment]
So this specific issue should be gone as we don't compact on startup any more. However if the database is corrupt we may still crash somewhere else.
