### ISSUE TITLE
syncthing can't sync link file

### ISSUE THREAD

**Issue by mouslee** [syncthing/syncthing#2542]
I created link files by mklink command, but they can't sync by synthing

**Comment by AudriusButkevicius** [comment]
Please provide logs

**Comment by mouslee** [comment]
Thanks for reply.
The system of my computer is Windows x64. I noticed the problem (Can't sync link files, and it links to a folder) when the version is v0.12.3.  I upgrade it to v012.6 and the problem is still existing.
The log seems no wrong, and syncthing just can't recognise link files.
I created link files using mklink command, such as "mklink /d "new folder name" "$absolute path\folder name"

**Comment by AudriusButkevicius** [comment]
You need run syncthing as admin to sync links on Windows.

**Comment by capi** [comment]
Alternatively (if it's just one and your machine): You can grant non-admin users the right to create sym-links on Windows. The user requires the `SeCreateSymbolicLinkPrivilege` and this can be configured via the Local Policy Editor. 

See e.g. [this superuser.com question](http://superuser.com/questions/124679/how-do-i-create-a-link-in-windows-7-home-premium-as-a-regular-user).

**Comment by mouslee** [comment]
Actually, I'm the administrator of my computer, so every software runs as admin all the time, and  `symlinksEnabled` is being selected in `Actions\Advanced\Options`, but the links still can't be synchronized.

**Comment by AudriusButkevicius** [comment]
The fact that you are admin does not mean that software runs as admin (unless you are on WinXP which does not support links in general). If you get warnings about symlinks when you start syncthing, you are not runningthe software as admin.

**Comment by capi** [comment]
Unless you disabled [User Account Control](http://windows.microsoft.com/en-us/windows/turn-user-account-control-on-off) or you explicitly start Syncthing with `Run as administrator`, it will not be launched with admin-privileges required for creating the Syncthing. Have a look at the link I gave you above which enables symbolic links for normal users, if you don't want to have Syncthing running with full administrative privileges.

**Comment by AudriusButkevicius** [comment]
Disabling UAC does not run software as admin on Win8 and newer.

**Comment by mouslee** [comment]
I tried several ways including disabling UAC, right clicking `syncthing.exe` and running it as `administrator`, or opening the privilege of creating symbolic links for normal users,  but it didn't work. Maybe there were some operation mistakes when I fixed this problem if you are sure that syncthing can synchronize symbolic links, and I will have a try later. I'm a little bit busy of these days, and sorry for not replying in time.

Thanks too much for helping me. It is so patient of you to answer my questions although I'm a junior in coding.

Here are other questions I want to say.
* My PC-1 won't connect to my PC-2 when I right click `syncthing.exe` and run it as `administrator`. If it runs as normal, two computers of mine will synchronize data as usual. 
* Chrome is my default browser, and it will be wholly crashed if I select `Run this program as an administrator` in right-click menu `Properties\Compatibility` for `syncthing.exe` and start a new chrome program. Here is the log of syncthing:
```
[OPBLZ] 11:56:17 INFO: syncthing v0.12.6 "Beryllium Bedbug" (go1.4.3 windows-amd64 default) NT-AUTHORITY\SYSTEM@BUILDER-W2K12R2 2015-12-01 10:24:30 UTC
[OPBLZ] 11:56:17 INFO: My ID: OPBLZUS-66ZVILL-WDTFXVB-DV4TGPC-GAFPHMS-DO7PWAX-6OIZS3R-3XCLFAK
[OPBLZ] 11:56:17 INFO: Single thread hash performance is ~199 MB/s
[OPBLZ] 11:56:17 OK: Ready to synchronize E.EndNote (read-write)
[OPBLZ] 11:56:17 OK: Ready to synchronize E.Groups (read-write)
[OPBLZ] 11:56:17 OK: Ready to synchronize E.Study (read-write)
[OPBLZ] 11:56:17 OK: Ready to synchronize F.Music (read-write)
[OPBLZ] 11:56:17 OK: Ready to synchronize G.Mous_xC.Settings (read-write)
[OPBLZ] 11:56:17 OK: Ready to synchronize G.OS (read-write)
[OPBLZ] 11:56:17 OK: Ready to synchronize G.Tools (read-write)
[OPBLZ] 11:56:17 OK: Ready to synchronize E.Books (read-write)
[OPBLZ] 11:56:17 INFO: Using discovery server https://discovery-v4-1.syncthing.net/?id=SR7AARM-TCBUZ5O-VFAXY4D-CECGSDE-3Q6IZ4G-XG7AH75-OBIXJQV-QJ6NLQA
[OPBLZ] 11:56:17 INFO: Using discovery server https://discovery-v4-2.syncthing.net/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[OPBLZ] 11:56:17 INFO: Using discovery server https://discovery-v4-3.syncthing.net/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[OPBLZ] 11:56:17 INFO: Using discovery server https://discovery-v6-1.syncthing.net/?id=SR7AARM-TCBUZ5O-VFAXY4D-CECGSDE-3Q6IZ4G-XG7AH75-OBIXJQV-QJ6NLQA
[OPBLZ] 11:56:17 INFO: Using discovery server https://discovery-v6-2.syncthing.net/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[OPBLZ] 11:56:17 INFO: Using discovery server https://discovery-v6-3.syncthing.net/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[OPBLZ] 11:56:17 INFO: Completed initial scan (rw) of folder G.Mous_xC.Settings
[OPBLZ] 11:56:17 INFO: Completed initial scan (rw) of folder G.OS
[OPBLZ] 11:56:17 INFO: Completed initial scan (rw) of folder E.EndNote
[OPBLZ] 11:56:17 INFO: Completed initial scan (rw) of folder G.Tools
[OPBLZ] 11:56:17 INFO: Completed initial scan (rw) of folder E.Groups
[OPBLZ] 11:56:17 INFO: Completed initial scan (rw) of folder E.Books
[OPBLZ] 11:56:17 INFO: Completed initial scan (rw) of folder F.Music
[OPBLZ] 11:56:18 INFO: Device OPBLZUS-66ZVILL-WDTFXVB-DV4TGPC-GAFPHMS-DO7PWAX-6OIZS3R-3XCLFAK is "MLEE-WC" at [dynamic]
[OPBLZ] 11:56:18 INFO: Device 4UUM36N-HUJUXCR-VEBMIN6-ELASK7S-45SNLLL-VZI3WIN-VQIK36S-2QYKBQS is "MLEE-PC-Windows" at [dynamic]
[OPBLZ] 11:56:18 INFO: API listening on 127.0.0.1:8384
[OPBLZ] 11:56:18 INFO: GUI URL is https://127.0.0.1:8384/
[OPBLZ] 11:56:18 INFO: Completed initial scan (rw) of folder E.Study
[OPBLZ] 11:56:27 INFO: No UPnP device detected
```
And here is the screenshot of chashed chrome:
![crashed chrome](https://ooo.0o0.ooo/2015/12/05/5663b4e2e43fd.png)

**Comment by AudriusButkevicius** [comment]
This is a chrome bug, nothing todo with syncthing. Closing this for now as you still haven't provided logs for failing to sync links.
