### ISSUE TITLE
how sync specific file with syncthing?

### ISSUE THREAD

**Issue by oska874** [syncthing/syncthing#2546]
For example,we sync many files with syncthin. Sometimes out of home or workspace ,we want to using phone get a specific file while sync all files of the whole dirctory is too slow and too expensive.

 How to do this that just sync one or several files?

**Comment by AudriusButkevicius** [comment]
You can try doing this using ignores but there is no way to do this. There is a fuse wrapper which supports read-only operations and downloads files on demand
