### ISSUE TITLE
Leaks go routines

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#2547]
Leaking at https://github.com/syncthing/syncthing/blob/master/lib/relay/client/static.go#L99, because if

**Comment by AudriusButkevicius** [comment]
This is not fixed.

**Comment by canton7** [comment]
What's the cause of this, then? Can https://github.com/syncthing/syncthing/blob/master/lib/relay/client/static.go#L291 block forever?

**Comment by calmh** [comment]
Looks like it can, because I don't see any SetReadDeadline calls

**Comment by canton7** [comment]
What about this one? https://github.com/syncthing/syncthing/blob/master/lib/relay/client/static.go#L83

**Comment by AudriusButkevicius** [comment]
So we should close the connection at the point we get a stop, and wait for messagereader to close the message chan, and only then return.

**Comment by AudriusButkevicius** [comment]
Its not related to timeouts or deadlines, as timeouts are handled in the serve loop, and the read syscall should return with an error as we close the connection.
