### ISSUE TITLE
problems binding ipv6 local dns hostnames

### ISSUE THREAD

**Issue by BrainDamage** [syncthing/syncthing#2551]
i am using syncthing version: 0.12.6

I am trying to bind an ipv6 link-local dns entry, he name has a local scope, so i have to specify interface
the address name is alarmc.local, over interface homevpn

the ipv4 equivalent works fine and is accepted by syncthing ( it doesn't require scoping due to ipv4 nature ): ```tcp://alarmc.local:22000```
the address is resolved, and syncthing binds to the interface fine

the ipv6 version: ```tcp://[alarmc.local%homevpn]:22000```
initially is problematic with the parser asking to escape the %
```FATAL: Failed to parse listen address tcp://[alarmc.local%homevpn]:22000: parse tcp://[alarmc.local%homevpn]:22000: percent-encoded characters in host```
to which i correct the url to: ```tcp://[alarmc.local%25homevpn]:22000```
howrever it seems it still fails to resolve the address:
```FATAL: Bad listen address: lookup alarmc.local%homevpn: no such host```
ping6 on the same machine is capable to resolve the address:
```ping6 -I homevpn alarmc.local```
```PING alarmc.local(alarmc.local) from fe80::9cfe:8fff:fe33:1497 homevpn: 56 data bytes```

the same IPv6 address if bound explicitly works fine, ( howrever, it's a link-local address and subject to change thefore would require constant editing ), but not as dns entry

**Comment by calmh** [comment]
Is there any prior art for allowing the syntax `alarmc.local%homevpn`, that is a hostname with a zone identifier? I can't find any, and I'm not sure how it would work from a resolver point of view.
