### ISSUE TITLE
NetBSD version does not change gui address to 0.0.0.0

### ISSUE THREAD

**Issue by ispmarin** [syncthing/syncthing#2553]
I configured the gui address to 0.0.0.0:8384 on config.xml, but when the service is started the GUI is still using 127.0.0.1:8384 address. 

The weird part is that if I change the port syncthing does change the port, but not the IP address.

**Comment by AudriusButkevicius** [comment]
Thats the address your local client should connect to,not the address its listening on.

**Comment by ispmarin** [comment]
From the manual:
```
Remote Web GUI

To be able to access the web GUI from other computers, you need to change the GUI Listen Address setting from the default 127.0.0.1:8384 to 0.0.0.0:8384. You also need to open the port in your local firewall if you have one.

```

That's exactly what I've done:
```
<gui enabled="true" tls="false">
        <address>0.0.0.0:8384</address>
        <apikey>sTlXFmDX8a-04eElAZRZUEBP00kpS-LR</apikey>
</gui>
```

I installed on a remote machine and I'm trying to configure from my home machine. What it is that I'm not getting? 

Thanks

**Comment by canton7** [comment]
You're expecting the `GUI URL is https://localhost:8384/` message that's printed on startup to print the GUI listen address which you put in the config file, which is incorrect (and IMO a bit misleading). It's instead printing an address which you can use to access the GUI.

Have you tried connecting to the GUI from another computer?

**Comment by ispmarin** [comment]
Yes, exactly.

I tried, with no luck. If indeed the GUI is listening when I change the
address, maybe the problem is somewhere else.

Thanks


Ivan Marin

Data Science Specialist @ Telefonica

Cel    + 55 11 98809 9400

2015-12-05 17:38 GMT-02:00 Antony Male <notifications@github.com>:

**Comment by AudriusButkevicius** [comment]
Well you can use netstat to verify where its listening.

**Comment by calmh** [comment]
Also note that it does print both what it listens to and where it suggests you should connect;

```
[MRIW7] 10:55:13 INFO: API listening on [::]:8082
[MRIW7] 10:55:13 INFO: GUI URL is http://127.0.0.1:8082/
```

Those two lines are talking about the same thing, but the first line gives you the actual listen address and the second line an URL you should be able to click to get there.
