### ISSUE TITLE
Filename pattern #*.*# considered as symlink?

### ISSUE THREAD

**Issue by tr37ion** [syncthing/syncthing#2560]
Emacs is creating temporary files when editing files with the filename patterns like:

    #filename.ext#
    .#filemane.ext

Syncthing considers this as a symlink and pops up a warning.

**Comment by AudriusButkevicius** [comment]
So?

**Comment by dcarosone** [comment]
Actually, look closer, you'll see they *are* symlinks, with the link
destination used to store content (so they can't actually be followed)

**Comment by calmh** [comment]
That's a very ... "interesting" way to do lock files. But yes. They are symlinks, so we're doing the right thing here.
