### ISSUE TITLE
Protocol tests are too slow

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2565]
```
ok  	github.com/syncthing/syncthing/lib/protocol	43.988s	coverage: 51.4% of statements
```

**Comment by AudriusButkevicius** [comment]
Not sure how you are getting these numbers. All tests run in under 10s on my machine, discovery being the longest ones taking 7s dueto bunch of sleeps.

**Comment by calmh** [comment]
Are you running with -short? The build server doesn't... Maybe the slow tests are correctly tagged as such, but still.

**Comment by AudriusButkevicius** [comment]
I am running ./build.sh test, not sure what that runs
