### ISSUE TITLE
Add ability to pause sync on folder for one client

### ISSUE THREAD

**Issue by JohnCardenas** [syncthing/syncthing#2566]
In order to support a use case where a mobile Syncthings client can pause sync for certain events (e.g. wifi connected/charging), please implement pausing folder sync for a given Syncthings client.

**Comment by AudriusButkevicius** [comment]
Can you please be a good citizen check existing issues before opening new ones, as opening duplicates just increases the administrative workload.

Dup #215 

Also, given that was opened a while ago and hasn't been addressed, I wouldnt keep your hopes up, unless you want to chip in and make it happen.

**Comment by wweich** [comment]
There were already 2 tries to implement it: #2185 and #2188
