### ISSUE TITLE
"Override changes" not working

### ISSUE THREAD

**Issue by chrert** [syncthing/syncthing#2567]
I recently added ignore patterns (ignore .git folders) to a master folder. After re-scanning, the folder became "out of sync" which is somehow reasonable. However, if i hit the "override changes" button it disappears for some time but nothing happens.

All devices are running on v0.12.7 linux-amd64.
The log doesn't contain any notable entries and other folders are syncing as expected.

Do you need any other information?

**Comment by AudriusButkevicius** [comment]
Just restart all of your nodes in one go.

**Comment by chrert** [comment]
Tried just now, but it didn't work!

**Comment by AudriusButkevicius** [comment]
When I said all in one go, I meant they have to be all offline at the same time. Restarting a, then b, then c won't work. You have to shut down, a, b, c and then start a, b, c.
