### ISSUE TITLE
multi-user world with server storage

### ISSUE THREAD

**Issue by jult** [syncthing/syncthing#2568]
Lacking in syncthing. Who is running syncthing several times and then have each use a different port etc.? Crazy. For this reason I started using seafile, turns out it's a lot more secure with the client-side enc/dec options as well.
Now running both alongside each other, and seafile is syncing same amount of data faster. No idea why (yet), but it just is.

**Comment by AudriusButkevicius** [comment]
Check existing issues, this has been discussed before and it's out of scope of what we are trying to achieve.
At least for v1.0.0.
