### ISSUE TITLE
0.12.7 Outgoing Rate not honored

### ISSUE THREAD

**Issue by johnjelinek** [syncthing/syncthing#2569]
I set my outgoing rate to 500KiB/s, but I see it hit 3+MiB/s in the `Upload Rate`.

**Comment by AudriusButkevicius** [comment]
That's expected if the device is identified as being on the local network.

**Comment by johnjelinek** [comment]
Hrmm ... tricky. All my devices are servers, not necessarily on the same network, but they have a tunnel connection between each other. Can I force it to obey?



—

**Comment by burkemw3** [comment]
@johnjelinek Yeah, checkout the `limitBandwidthInLan` [config option](http://docs.syncthing.net/users/config.html) (I can't link directly, so use your search!).
