### ISSUE TITLE
Some peers not connecting most times

### ISSUE THREAD

**Issue by fbreve** [syncthing/syncthing#2570]
Since version 0.12 I noticed that some peers are not connecting to each other all the time, even though they are all online. For example, right now, my machine is connected to two peers, but there are four other peers which are online and working just fine, but my machine is not connecting to them and vice-versa.

There are no errors and nothing weird in Synctrayzor log. I don't have syncthing logs since I'm in Windows and it does not log anymore.

This problem happens most of the time, but not all the time, sometimes all the peers connect. I couldn't find any pattern, but I notice that the peers with less shared folders are more easily connectable.

The problem happens in more than one machine in more than one place (work and home), with both local and remote connections, so it is being really hard to track any issue.

Discovery is usually between 5/8 and 8/8. Retransmitters always at 1/1. At work each machine has it own  valid IP address (some have IPv6 too). At home they have NAT addresses and UPnP is on, no valid IPv6.

**Comment by canton7** [comment]
I've been seeing this as well.  Restarting both sides normally sorts it: have you seen that too? My impression is that it started after the new discovery server lookup backoff was introduced, but I haven't confirmed it. I also haven't been able to reproduce it reliably (with logging...) 

If you want better syncthing logging from SyncTrayzor grab one of the Dev builds (click the badge at the top of the readme)

**Comment by fbreve** [comment]
Sometimes restarting solves it, sometimes it connects after a long time. I also noticed that sometimes it stops working silently, the only sympton being the interface not updating anymore and reloading it does not update the status of the connections.

I don't think it is related to Synctrayzor, because my NAS devices also have this problem. It would be nice to have the syncthing log like we used to.

**Comment by fbreve** [comment]
I thought version 0.12.8 had solved it. But now it is happening again, it starts and don't connect to any other machine, neither local nor remote. Something is wrong with discovery.

**Comment by AudriusButkevicius** [comment]
If there was a bug you'd have hundereds of people +1'ing, this, 
therefore I think it's specific to your enironment and should be dealt with as a support request rather than a bug report. There was another thread in the forums related about a simillar issue, I suggest you follow the same instructions, run the same build.

You can carry on the discussion there, or start a new thread on the forums.

Link to the thread: https://forum.syncthing.net/t/since-windows-10-upgrade-all-stopped-syncing/6361
