### ISSUE TITLE
Replacing a directory with a symlink or vice versa is buggy

### ISSUE THREAD

**Issue by wlmb** [syncthing/syncthing#2571]
I found a curious behaviour when deleting directories and creating symbolic links.

Consider two machines One and Two. In One I make a directory A with a file a and a directory B with the same file a and another file b:

> ## 1
> 
>  One:~$ mkdir A B; touch A/a; cp A/a B; touch B/b; ls -R
> A:
> a
> B:
> a b

I wait until both machines are synchronized. Later I remove directory A and replace it by a symbolic link to B

> ## 2
> 
>  One:~$ rm -r A; ln -s B A; ls -R 
>   A:
>   a b
>   B:
>   a b

Synchronization fails at Two when it tries to delete A because the directory is not empty.

> ## 3
> 
> Two:~$ ls -R 
> A:
> a
> B:
> a b

To allow synchronization to complete, I remove the directory A

> ## 4
> 
> Two:~$ rm -r A; ls B
> a b

After synchronization completes A becomes a symbolic link in machine Two, as expected, but with the undesired consequence that in the process file a disappeared from directory B in both machines, whereas it was deleted from directory A in machine Two where it was not linked to directory B.

> ## 5
> 
> One:~$ ls -R
> A:
> b
> B:
> b
> 
> Two:~$ ls -R
> A:
> b
> B:
> b

If I wait after deleting A in machine One in step ##2 above, allowing synchronization to occur, and afterwards make the symbollic link, synchronization doesn't fail and I do not loose any file

> ## 2bis
> 
>  One:~$ rm -r A; sleep 120; ln -s B A; ls -R 
>   A:
>   a b
>   B:
>   a b
> ## 3bis
> 
> Two:~$ ls -R 
> A:
> a b
> B:
> a b

I am scanning my directories every minute. So it seems that syncthing gets confused when I perform the two operations, delete a directory and immediately substitute it by a symbolic link, before the first change is detected and synched.

**Comment by calmh** [comment]
To be resolved by #2540

**Comment by wlmb** [comment]
On Fri, Jan 01, 2016 at 06:59:27AM -0800, Jakob Borg wrote:
> To be resolved by #2540
Thanks!
Luis

**Comment by richvdh** [comment]
I'm seeing this problem, and it's pretty nasty, because it has the ability to delete files.

I see #2540 has been closed - is a fix still on its way?

**Comment by richvdh** [comment]
Unfortunately this is a showstopper for me. I need to use symlinks, and I need to be able to exchange them with directories. I can't have syncthing deleting a load of my work when I do.

**Comment by calmh** [comment]
Workaround in the meantime is to allow a rescan to happen after removing one and before creating the other.

**Comment by klausenbusk** [comment]
How do I recover from this?

I have a folder which was replaced with a symlink on my laptop (`Git/github/kubernetes/vendor/k8s.io/metrics` -> `../../staging/src/k8s.io/metrics`), on my server running Syncthing I got the following error:
```
[ZPRDE] INFO: Puller (folder kristian, file "Git/github/kubernetes/vendor/k8s.io/metrics"): symlink remove: remove /home/backup/st/Git/github/kubernetes/vendor/k8s.io/metrics: directory not empty
```
So I deleted `/home/backup/st/Git/github/kubernetes/vendor/k8s.io/metrics` on the server and did a rescan on both the server and my laptop, and the server successfully created the symlink, but it still tries pulling some files from the directory (ex: `Git/github/kubernetes/vendor/k8s.io/metrics/pkg/apis/custom_metrics/BUILD`), which never succeeds. How can I delete this files from Syncthing database?

Syncthing v0.14.43

**Comment by imsodin** [comment]
@klausenbusk What should work for sure is if you delete both the directory and the symlink on both devices, then get them in sync and after that recreate the symlink. I do not understand why deleting on the server isn't enough, but as #4584 already fixes the underlying problem, it I am not particularly interested in finding out.

**Comment by klausenbusk** [comment]
> @klausenbusk What should work for sure is if you delete both the directory and the symlink on both devices, then get them in sync and after that recreate the symlink.

Thanks, I ended up renaming the symlink on my laptop, rescan on both devices and rename it back, and now everything is working again. :)

**Comment by AudriusButkevicius** [comment]
@imsodin this was reverted/backed out right?

**Comment by imsodin** [comment]
Nope, it was in the reverted combined fs/db scanning stuff but I then fixed it without that: https://github.com/syncthing/syncthing/pull/4765

**Comment by AudriusButkevicius** [comment]
I don't think that yet landed in the release.
@calmh reasonable bot enchantment: to tag PRs when they were/will be released?

**Comment by calmh** [comment]
I add the issues to the milestone. This makes the milestone good as release notes. I think adding PRs as well would muddy the waters, but maybe maybe.
