### ISSUE TITLE
Fetch Download/Upload rate when page loads

### ISSUE THREAD

**Issue by fjanicki** [syncthing/syncthing#2572]
Currently it takes a few seconds to get the download/upload rate on a client. It would be good to get this info as soon at we load the page. It shows 0 kB/s for about 5 seconds after which the real value shows.

- OS: Windows 10
- Same for other connected devices
- Screenshot: http://i.imgur.com/JtP5bnB.png (that's 3sec after the pages has loaded, multiple files are uploading from this workstation)

**Comment by canton7** [comment]
Currently, I believe this is a result of how that value is obtained. The API (which the GUI talks to) returns the number of uploaded/downloaded bytes. The GUI has to fetch two values for this, a number of seconds apart, and use them to create an average transfer rate over that period.

**Comment by AudriusButkevicius** [comment]
Correct, you have to sample the data for some time to work out the average.
Also, you don't want to sample if nobody is looking at the UI, as there is some cost associated with that.
