### ISSUE TITLE
Crash with Illegal Instruction after upgrade to 0.12.7

### ISSUE THREAD

**Issue by karlkec** [syncthing/syncthing#2573]
On a ubuntu 12.04 server (i386) using the v0.12.7 statically-linked syncthing, it reports an illegal instruction and dumps core when starting syncthing. It even does this with -version as the only argument. Here is the output with v0.12.7 downloaded today:
$ ./syncthing -version
Illegal instruction (core dumped)

This machine has been running syncthing version v0.12.2 just fine for several months, then failed after upgrading to v0.12.7 from the apt.syncthing.net repo. Downgraded to v0.12.6 and it works fine on the same machine.

I'm happy to debug this, but am not sure how to proceed.

**Comment by AudriusButkevicius** [comment]
Check closed for for solution.
