### ISSUE TITLE
Since Windows 10 upgrade all stopped working.

### ISSUE THREAD

**Issue by peejaygee** [syncthing/syncthing#2575]
Hey Guys, 

Nothing changed apart from my OS, same firewall, save rules, etc.

Now I can't get it to sync between 3 machines, Windows 10 on 2, Windows 7 on one. 

V 1.0.32 SynTrayor & v0.12.7 Syncthing

What options do I need to 'activate' to provide an output, to allow you god like creatures to see why it's stopped all of a sudden?

**Comment by AudriusButkevicius** [comment]
Please use the forums for support, until we know that there is a bug.

**Comment by peejaygee** [comment]
My Apologies, I wasn't thinking straight was thinking this was the forums.
