### ISSUE TITLE
Syncthing 12.8 on freenas Chmod issues

### ISSUE THREAD

**Issue by Rcola1987** [syncthing/syncthing#2579]
On freenas i have a jail running syncthing 12.8 and it is constantily complaning that "Operation Not Permitted" Its trying to CHMOD files on a windows share that does not support unix file permissions. Is there any way to fix this? Its making me worried that files are not actually being synced bu to it saying out of sync.

**Comment by AudriusButkevicius** [comment]
Search the forums, you need to tweak some ACL business.
