### ISSUE TITLE
issue with Syncthing 12.8 Saying insufficient free space

### ISSUE THREAD

**Issue by Rcola1987** [syncthing/syncthing#2580]
I keep getting errors in windows 7 that a share has stopped due to insufficient free space. the dirve has many GB's free.

**Comment by AudriusButkevicius** [comment]
Percentage wise, how much space does it have?
Also, make sure you are looking at the right drive, as it needs space in both the directory the data lives as well as the directory syncthings database lives.

**Comment by Rcola1987** [comment]
both drives have more than 20 % free

**Comment by AudriusButkevicius** [comment]
Can you provide the actual log message? Is it some network drive/share?

**Comment by Rcola1987** [comment]
[KKDGI] 11:09:32 INFO: Completed initial scan (rw) of folder Pictures
[KKDGI] 11:09:43 INFO: Established secure connection to FZT6OP5-CGO7SBE-PTIBMIE-N7K6CU5-MV43HYG-3P6MITG-LVX4ERJ-PTMDSAZ at 192.168.1.123:53573-192.168.1.11:22000 (direct-dial)
[KKDGI] 11:09:43 INFO: Device FZT6OP5-CGO7SBE-PTIBMIE-N7K6CU5-MV43HYG-3P6MITG-LVX4ERJ-PTMDSAZ client is "syncthing v0.12.8" named "syncthing_NAS"
[KKDGI] 11:11:01 INFO: Connected to already connected device (FZT6OP5-CGO7SBE-PTIBMIE-N7K6CU5-MV43HYG-3P6MITG-LVX4ERJ-PTMDSAZ)
[KKDGI] 11:14:56 INFO: Relay received: xdr read: EOF
[KKDGI] 11:20:19 WARNING: Stopping folder "Accounting" - insufficient free space
[KKDGI] 11:20:19 INFO: Stopping folder Accounting due to error: insufficient free space
[KKDGI] 11:20:27 INFO: Folder "Accounting" error is cleared, restarting
[KKDGI] 11:35:33 INFO: Established secure connection to 2VJTJ47-OLTSWGX-JP4JKVA-D3HMYZR-MRS35KT-CZ7DTNR-PMI2PAY-XHLDRQT at 192.168.1.123:54577-134.184.43.156:22067 (relay-accept)
[KKDGI] 11:35:34 INFO: Device 2VJTJ47-OLTSWGX-JP4JKVA-D3HMYZR-MRS35KT-CZ7DTNR-PMI2PAY-XHLDRQT client is "syncthing v0.12.8" named "SURFACE"

This Is a Local Drive

**Comment by AudriusButkevicius** [comment]
@Zillode any ideas?

**Comment by Rcola1987** [comment]
as a note this error will move from folder to folder and will fix on a manual rescan most times

**Comment by AudriusButkevicius** [comment]
I think some sort of "I can't access this drive right now" is considered as an out of space error.

**Comment by Rcola1987** [comment]
hmmmm

**Comment by Zillode** [comment]
Try this build please: http://build3.syncthing.net/job/syncthing-pr-windows/88/ (still compiling)

**Comment by Rcola1987** [comment]
Im am leaving for vacation and will not be able to test this till i get back at the 1st of the year.

**Comment by AudriusButkevicius** [comment]
Ping then to reopen.
