### ISSUE TITLE
Disconnects leak goroutines (sendIndexes)

### ISSUE THREAD

**Issue by indrora** [syncthing/syncthing#2589]
I've been running SyncThing in a small (4 node) cluster. Total about 4000 files at 5...6GB disk.

On my VPS (which is one of the few with all 4 folder shares) I regularly see a slow memory leak when doing synchronization among clients and when doing scans. SyncThing starts at 40MB memory usage and soon finds itself in the 120MB range.  The VPS it's living on only has 256MB of RAM and I have other services (namely, httpd) competing for time/memory there. 

Top shows SyncThing at 20ish percent of my memory load

```
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
20492 indrora   20   0   60732  55796   8884 S  0.0 21.3   0:05.73 syncthing
```

This just goes up as SyncThing scans folders or synchronizes with devices. I use SyncThing on my phone to back up photos, and a few large photos can churn SyncThing into eating several tens-of-megs of RAM.

**Comment by AudriusButkevicius** [comment]
It's a garbage collected language, so its fairly hard to leak stuff. I think using 120MB of RAM for all DB caches and bells and whitles is reasonable. There are things you could disable which could make it better (for example scanning progress which has to hold metadata about files in memory, ignore pattern cache) but you will either loose features or increase cpu load. Also, you can read about the GOGC environment variable and set that to something lower.

**Comment by indrora** [comment]
I expressed myself poorly -- after several hours, this value balloons to nearly 200MB and gets OOM killed by my VPS. It explicitly happens when I have a short scan interval set on folders.

**Comment by calmh** [comment]
Unfortunately, usage up to a couple of hundred megs even for smallish loads is fairly normal. However, my instances seem to stick at ~100 MB for about 5-10 times the amount of files. Are you running the 32 bit version? The GC there is (I think...) still less efficient than amd64. If you haven't already, do set GOGC=25 or so to enforce a slightly stricter GC as well.

But as Audrius says; we most likely don't have leaks. We do however have memory usage that goes up and down depending on what's going on.

**Comment by AudriusButkevicius** [comment]
And as I've expressed, disabling scan progress iindicators would help reduce memory usage during a scan.

**Comment by indrora** [comment]
I'm on amd64.

What I'm seeing smells like a leak. Memory usage just goes up. When I manually scan, I can regularly see (on an unchanged filesystem) higher memory usage after a scan. If not showing scan indicators alleviates memory load **after** the scan has completed, then that's a *leak*.

**Comment by canton7** [comment]
I don't know exactly how Go's GC works, but it's not uncommon for GC'd languages to gradually consume more and more memory until there's actually some memory pressure, at which point they'll trigger a collection.

**Comment by AudriusButkevicius** [comment]
Well, we have no control over when the memory gets freed, so it's just the runtime defering the GC scan until sometime later, and not a leak. 

A constant growth of 5MB per scan will not be collected.
By default GC kicks in every time we double in memory (GOGC=100).
If the runtime itself takes 120MB, a GC will only kick in at the point we reach 240MB, by which time we might have already been OOM killed.

As calmh said, set GOGC=1 (gc everytime memory growth increases by a percent) and you should see it freed much earlier, but make sure to put ice on the cpu as it will probably spend most of its time crawling trying to find what to free rather than doing anything useful.

I am not sure how Go GC behaves with memory preassure, but I think it simply doesn't care given you are getting OOM killed.

**Comment by Stebalien** [comment]
> It's a garbage collected language, so its fairly hard to leak stuff.

This is couldn't be further from the truth. While one generally you can never really loose track of memory in a GCed system, you can easily accidentally hold on to references that you should let go of. For example, you can spawn a go routine, capture some state, and then hang forever. Basically, nothing will be freed while it could be used (even if it never is). This is actually a *huge* problem in JavaScript.

There's no reason memory usage should increase over time. After starting up and connecting, memory usage should flatten out fairly quickly in a steady state. However, this is clearly not the case. On my machine, syncthing started out at 35MB and then slowly grew to over 90MB in a few hours which is well over double. This is a leak; there is nothing to debate. Unless the number of go routines is growing over time (this should be checked), there's probably some data structure somewhere that's growing linearly. Are you doing any sort of in-memory logging/event recording?

> I am not sure how Go GC behaves with memory preassure, but I think it simply doesn't care given you are getting OOM killed.

On linux at least, there isn't really any concept of memory pressure.

**Comment by calmh** [comment]
> On my machine, syncthing started out at 35MB and then slowly grew to over 90MB in a few hours which is well over double. This is a leak; there is nothing to debate.

No, this is fairly normal. And it also depends on how you measure this growth. You can set down the GOGC env variable to 25 or so (from the default of 100) to trigger earlier GC (at 25% growth instead of the 100% growth that is default). Also memory pressure is relevant, as the mechanism Go uses to free memory back to the OS is to indicate it as not in use using `madvise`. The pages are still allocated to the process, but Linux is free to throw them away if needed.

**Comment by calmh** [comment]
Actually, staring at the gctrace and forcing continuous reconnects by restarting another instance of syncthing, there is a gradual increase I can't obviously explain. @Stebalien are you seeing a lot of reconnects going on for some reason?

**Comment by calmh** [comment]
sendIndexes aren't properly terminated on connection close:

```
goroutine 5765 [select, 1 minutes]:
github.com/syncthing/syncthing/lib/events.(*Subscription).Poll(0xc8201b0120, 0xdf8475800, 0x0, 0x0, 0xffffffff00000000, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jb/src/github.com/syncthing/syncthing/lib/events/events.go:210 +0x4dc
github.com/syncthing/syncthing/lib/model.sendIndexes(0xf85248, 0xc820114390, 0xc820471ec0, 0x2d, 0xc8204dc580, 0xc8204724b0)
	/Users/jb/src/github.com/syncthing/syncthing/lib/model/model.go:1085 +0x63c
created by github.com/syncthing/syncthing/lib/model.(*Model).AddConnection
	/Users/jb/src/github.com/syncthing/syncthing/lib/model/model.go:1000 +0x540
```

**Comment by calmh** [comment]
These get cleaned up when there *is* an index update to send and they notice that the connection is gone. But in an idle state where there are no changes anywhere but a lot of disconnects/connects they can accumulate.

**Comment by AudriusButkevicius** [comment]
There is a nice tool which processes panics and shows where most of the routines are at which could help is spot more if these if they exist. I know relays were leaking stuff too, that should be fixed now.

**Comment by indrora** [comment]
This is especially true if you've got an android device in the cluster, which will tend to leave connections in a half-open state (awaits TCP timeout) due to cellular networks being bad. I had a similar problem in ZNC, which got very confused. 

My cluster consists of two laptops, a phone and a VPS. The VPS instance always has the most memory usage, usually in the 200MB range. The phone regularly gets the second highest usage at ~150MB. The phone eventually will flush out and go to an idle of ~50MB, but will slowly grow again over a few hours.

On January 11, 2016 8:42:04 AM MST, Jakob Borg <notifications@github.com> wrote:
>These get cleaned up when there *is* an index update to send and they
>notice that the connection is gone. But in an idle state where there
>are no changes anywhere but a lot of disconnects/connects they can
>accumulate.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/syncthing/syncthing/issues/2589#issuecomment-170590971

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Stebalien** [comment]
> Are you seeing a lot of reconnects going on for some reason?

I haven't checked but this seems likely; my android phone is a part of my cluster.

**Comment by indrora** [comment]
When I pause my phone on my VPS and relegate my phone to WiFi only, RAM usage stays consistent. This confirms that the interaction of Android devices (or other devices on a cellfi connection) that move between networks regularly causes half open or idle connections to eat memory.

On January 11, 2016 12:08:25 PM MST, Steven Allen <notifications@github.com> wrote:
>> Are you seeing a lot of reconnects going on for some reason?
>
>I haven't checked but this seems likely; my android phone is a part of
>my cluster.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/syncthing/syncthing/issues/2589#issuecomment-170655212

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
