### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by IronicBadger** [syncthing/syncthing#2591]
Hi,

We've packaged Syncthing in an auto-updating Docker container and are about to release it. Before we do we'd like to seek your feedback and see if there any improvements you might suggest. 

[https://github.com/linuxserver/docker-syncthing](https://github.com/linuxserver/docker-syncthing)

Finally, we'd like to know if you'd include our release as an officially supported deployment method? I've been personally using this container for some time without issue.

Regards,
IronicBadger (on behalf of Linuxserver.io)

**Comment by calmh** [comment]
It looks reasonable to me. Although, you are not forwarding in a sync port so the only way to get a connection is outgoing or via relay?

**Comment by calmh** [comment]
Auto-updating as in it installs the latest version at the time of image creation, right, and after that point the user is locked down to that version forever or until they pull a new image?

**Comment by IronicBadger** [comment]
@calmh auto-updating as in when the container restarts, the script for this is in our [baseimage](https://github.com/linuxserver/docker-baseimage/blob/master/20_apt_update.sh) - this philosophy is KISS for the end user. No need to pull a new container just restart to initiate apt-update.

Ports are not specified because we suggest the use of `--net=host`.

**Comment by calmh** [comment]
Ok, cool
