### ISSUE TITLE
Syncing large files requires double the disk space on resume

### ISSUE THREAD

**Issue by JanX2** [syncthing/syncthing#2598]
After restarting an in-progress sync of a large file (87 GB) I get an “insufficient disk space” error.

    2015-12-19 11:50:42: Folder "HAL": insufficient disk space in /Users/jan/Sync/HAL/ for HAL2 HD Julien 2015-11-08 (10.11.1).dmg: have 15773.03 MiB, need 86914.60 MiB

This is using the current release v0.12.8 (from syncthing-0.12.8.dmg).

That looks reasonable at first, but doesn’t account for the fact, that the space required is already reserved by the hidden temp file for the backup image.

I expected syncthing to continue where it left off. Why does it require the additional space?

Anything I can do differently apart from making more space, which currently isn’t an option?

The only workaround I have found is to delete the folder and recreate it on the machine that downloads the image. This is contrary to the idea of syncing, of course. ;)

**Comment by calmh** [comment]
Yeah, this is a bug. You can work around it by setting the required space to zero, thus disabling the check.

**Comment by JanX2** [comment]
Thanks!

**Comment by JanX2** [comment]
Sorry @calmh. Setting it to 0 didn’t work. Had to delete again an restart. :(

**Comment by calmh** [comment]
The check is completely disabled when the required space is set to zero, but it may require a restart for that setting to "take". (It should say so in the GUI as well in that case)

**Comment by calmh** [comment]
Oh! Sorry. It is *not* disabled in this specific case. It should be. That's a separate issue.

**Comment by JanX2** [comment]
Darn. Anything else I can do as a workaround?

**Comment by AudriusButkevicius** [comment]
Free up the space.

**Comment by calmh** [comment]
Use 0.12.9 released tomorrow, with the threshold set to zero.
