### ISSUE TITLE
Upload Limit is being applied to LAN connections

### ISSUE THREAD

**Issue by fbreve** [syncthing/syncthing#2602]
I'm using version 0.12.8 in both sides. It's a Windows 10 device and Synology NAS device, both on the same LAN.

I noticed that the upload limit of 40 KB/s that I set on the Windows 10 device is also limiting the upload to the NAS, which is always around 38~40 KB/s.

No relay is in use. The IP addresses on them are:
[fe80::211:32ff:fe2a:1d3c%Eth
[fe80::6db4:3fa:ad21:f348%eth0]

I don't have DHCP v6, so I guess these are automatic local addresses. I don't know why they are choosing IPv6 local addresses instead of the IPv4.

**Comment by AudriusButkevicius** [comment]
There is no lan detection for v6 addresses in Windows, but it's a Go bug, not a syncthing bug.

**Comment by AudriusButkevicius** [comment]
Supposedly fixed in Go 1.6, which is not out yet.

**Comment by fbreve** [comment]
Thank you.

In this case, is it possible to force IPv4 connections only?

**Comment by AudriusButkevicius** [comment]
You can disable ipv6 discovery by setting localAnnounceMCAddr value to an empty string in the config by hand. Also, you can try asking syncthing to listen explicitly on a v4 address, rather than a wildcard address.

**Comment by calmh** [comment]
v0.12.9 for Windows is built with Go 1.6beta1, so if it's fixed there it may work now. Can give it a try? We could also just add `fe80::/16` to the permanent LAN addresses, as there is no chance of it being anything else.
