### ISSUE TITLE
sync.mywebsite.com (files exposed)

### ISSUE THREAD

**Issue by francesco1119** [syncthing/syncthing#2603]
I have setup a password for the web service. 
The GUI is visible at "sync.mywebsite.com:8080" but at "sync.mywebsite.com" these files are exposed:

Index of /

    AUTHORS.txt
    FAQ.pdf
    Getting-Started.pdf
    LICENSE.txt
    README.txt
    cgi-bin/
    etc/
    nohup.out
    syncthing
    syncthing.conf
    syncthing.old
    syncthing.sig

Is that normal?

**Comment by AudriusButkevicius** [comment]
We don't listen on port 80, only 8384 (usually).

We only serve files of the disk if STGUIASSETS env var is set, so I'd check if you don't have anything else running serving random files.

**Comment by francesco1119** [comment]
I've installed Syncthing on my shared hosting on a subdomain and in order to access to the web gui I need to put port 8080.
The Syncthing folder is now accessible without :8080.
I would like to know if this is a security problem.

Thank you

**Comment by calmh** [comment]
This is your web hosts web server, not syncthing. It is probably a security problem. Syncthing doesn't server directory listings, it doesn't have the code for it.
