### ISSUE TITLE
config: We should limit the number of conflict files by default

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2604]
I suggest the default should be five conflict copies before we clean out. 

(This is already quite bad if the conflicting file is a 100 gig VM image, but I don't think we can have defaults that suit everyone...)

**Comment by canton7** [comment]
Maybe something like `2* <number of devices sharing this folder>`? Or some other metric based on how many conflicts we can reasonably expect to see appear at a time?

Or perhaps something date-based? We can remove a conflict if we have more than `n` conflicts of that file already, and it's over `t` days old. That at least gives the user a reasonable chance of clearing it up themselves.
