### ISSUE TITLE
puller: We should not create conflicts of conflicts

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2605]
If there's a sync conflict on `foo.sync-conflict-20151230.txt` we should not create `foo.sync-conflict-20151230.sync-conflict-20151231.txt` and so on.

What should we do instead? I suggest acting as if we had maxConflicts=0 for these files.

The reason I think we should do this is I think it's very rare indeed that these are intentional, human changes. Most likely it's some automatic thing causing havoc.

**Comment by canton7** [comment]
I'd be more comfortable with `maxConflicts=0` if we logged the fact that we were throwing away conflicted versions.

**Comment by andersonvom** [comment]
Since we'd be discarding information I think this should be both logged and explicitly mentioned in the documentation as well.

**Comment by nrm21** [comment]
What about a simple check if it already contains ".sync-conflict-" and if so do nothing?
