### ISSUE TITLE
Repeated connection errors and reloads in Firefox 43

### ISSUE THREAD

**Issue by Stebalien** [syncthing/syncthing#2607]
Syncthing UI repeatedly complains about a connection error and reloads. This only happens in Firefox (reproducible with a clean profile).

Platform: Linux
Syncthing Version: 0.12.9
Firefox Version: 43.0.1

Note, I have authentication enabled in case that's relevant.

**Comment by calmh** [comment]
Javascript console or something to show what actual error is happening?

**Comment by AudriusButkevicius** [comment]
It's probably some magic 'hide my identity and not accept cookies' extension you are running.

**Comment by canton7** [comment]
> It's probably some magic 'hide my identity and not accept cookies' extension you are running.

I wouldn't be so sure of that...

> (reproducible with a clean profile).

**Comment by AudriusButkevicius** [comment]
Clean profile does not mean no extensions as far as I understand

**Comment by canton7** [comment]
Extensions are stored in the profile

**Comment by Stebalien** [comment]
Yes, by clean profile I mean *clean* profile; no extensions. I'm seeing UIOffline/UIOnline messages and, after coming back online, I'm seeing a 500 error for `http://localhost:8384/rest/system/upgrade` but I don't think that's the issue (I have upgrades disabled and I see the same error on chromium and it doesn't cause a reload).

**Comment by Stebalien** [comment]
Authentication isn't the problem

**Comment by Stebalien** [comment]
I'm also seeing `refreshErrors Object { errors: null }` if that's useful.

**Comment by calmh** [comment]
This doesn't happen for me in a newly downloaded Firefox 43.0.1 on Mac. Without being able to reproduce it I don't know how to fix it. Try stepping through the javascript to figure out what causes the reload? There's a version check that reloads the GUI when the backend version has changed, and another one if we got a network error and then recovered (which sounds more like what you're running into).

**Comment by Stebalien** [comment]
Long polling `rest/events?since=XXX` seems to be broken client side. The client thinks the server is returning a 200 status early without any data (according to the network log) and the onerror function is getting called. curl and chrome work just fine and the server appears to be correctly waiting to send a response (based on `STTRACE=http syncthing`).

**Comment by Stebalien** [comment]
This seems like a browser bug so I'm just going to close this.

**Comment by NathanSalapat** [comment]
@Stebalien I to have been experiencing this, and yes, only in firefox, in fact I just tried having Chrome and Firefox run side by side and I only see the error in Firefox. From watching the system monitor every time Firefox displays the error I have a spike in CPU usage.

**Comment by NathanSalapat** [comment]
Fresh install of syncthing and empty configuration make no difference either. :(

**Comment by Stebalien** [comment]
@NathanSalapat, what version of Firefox?

**Comment by Stebalien** [comment]
And thanks for confirming that it's not my computer (I have a very odd configuration).

**Comment by NathanSalapat** [comment]
Version 43 for Linux Mint on both of my machines. 64bit on both.

**Comment by Stebalien** [comment]
I'm on Arch so it's not distro specific (however, I am using 64bit firefox).

**Comment by NathanSalapat** [comment]
I'm not sure how to get any type of debug information, I suppose I'd start it in a terminal, but I watched my system monitor for a while, and every time I had the error CPU spiked, but when I closed Firefox and Chrome was just displaying the web interface I had no CPU spikes, so it's got to be a Firefox thing.

**Comment by Stebalien** [comment]
The spike is probably just firefox reloading the page.

**Comment by Stebalien** [comment]
Works on firefox 42.

**Comment by NathanSalapat** [comment]
It must be, as I've just watched the terminal output of syncthing running, and I get nothing showing there when the error displays.
I'll have to try and downgrade my browser, or try a nightly build.

**Comment by Stebalien** [comment]
I can reproduce this with netcat so I've submitted a bug report to Mozilla. https://bugzilla.mozilla.org/show_bug.cgi?id=1234751

**Comment by calmh** [comment]
Ah, that explains it. Syncthing (the GUI) will interpret that as syncthing (the daemon) going down, and retry getting /rest/system/version or something, which works, so we're online again and then the whole thing restarts.

**Comment by Stebalien** [comment]
Might it be possible to try again on an empty response with a 200 status? This won't exactly be long polling but at least it will mask this bug until it's fixed upstream.

**Comment by calmh** [comment]
Try it if you like. I suspect this actually manifests as a "connection reset by peer" or something, so is a genuine error and not just an empty response. (In fact, the latter would be a disaster as that would mean the browser is actively lying about our response.)

**Comment by Stebalien** [comment]
Interestingly, I'm not seeing this behavior with this simple flask app:

```python
#!/usr/bin/python

from flask import Flask, Response
app = Flask(__name__)
from time import sleep

@app.route('/')
def main():
    return """
<script>
var myRequest = new XMLHttpRequest();
myRequest.open("GET", "http://localhost:5000/other", true);
myRequest.onreadystatechange = function() {
  console.log(myRequest.readyState);
  console.log(myRequest.status);
};
myRequest.send();
</script>
"""

@app.route('/other')
def other():
    def generate():
        yield "first"
        sleep(20)
        yield "second"
    return Response(generate(), mimetype='text/plain')


if __name__ == '__main__':
    app.run()
```

**Comment by calmh** [comment]
I haven't looked closely at this, but I think your flask app may be doing something different. I would expect it to use some chunked encoding and return the "first" response immediately befor sleeping, if it does what it looks like it could be doing (I don't speak flask:)

**Comment by Stebalien** [comment]
Headers:

```
Connection: close
Content-Type: text/plain; charset=utf-8
Date: Tue, 29 Dec 2015 23:14:37 GMT
Server: Werkzeug/0.11.2 Python/3.5.1
```

It works even if I change the first yield to `yield ""`. The main difference is the `Connection: close` header.

**Comment by AudriusButkevicius** [comment]
There is no length nor transfer encoding header, so I don't think it's not the full headers.

**Comment by Stebalien** [comment]
Those are the full headers (checked with netcat).

**Comment by AudriusButkevicius** [comment]
I wonder if it might be due to the fact that we've upgraded to go 1.5.2/1.6.0 beta.

**Comment by calmh** [comment]
This is our output when built with 1.5.2:

```
jb@syno:~ $ nc localhost 8082
GET /rest/events?since=42 HTTP/1.1
Host: localhost

HTTP/1.1 200 OK
Cache-Control: max-age=0, no-cache, no-store
Expires: Wed, 30 Dec 2015 08:13:36 GMT
Pragma: no-cache
X-Syncthing-Id: MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC
X-Syncthing-Version: v0.12.10+6-g16a2322-dirty
Date: Wed, 30 Dec 2015 08:13:36 GMT
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked
```

This is as expected; the "transfer-encoding: chunked" says that contents will be forthcoming but haven't been sent yet, as I understand it.

This is with go1.6beta1 (on Mac, not that it should matter):

```
jb@syno:~ $ nc localhost 8082
GET /rest/events?since=42 HTTP/1.1
Host: localhost

HTTP/1.1 200 OK
Cache-Control: max-age=0, no-cache, no-store
Expires: Wed, 30 Dec 2015 08:17:37 GMT
Pragma: no-cache
X-Syncthing-Id: MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC
X-Syncthing-Version: v0.12.10+6-g16a2322-dirty
Date: Wed, 30 Dec 2015 08:17:37 GMT
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked

```

LGTM

**Comment by Stebalien** [comment]
Sorry, those headers are from my small flask program above. Also, I must not have restarted my flask server; the following server, which yields nothing before sleeping, exhibits the same behavior as syncthing.

```
#!/usr/bin/python

from flask import Flask, Response
app = Flask(__name__)
from time import sleep

@app.route('/')
def main():
    return """
<script>
var myRequest = new XMLHttpRequest();
myRequest.open("GET", "http://localhost:5000/other", true);
myRequest.onreadystatechange = function() {
  console.log(myRequest.readyState);
  console.log(myRequest.status);
};
myRequest.send();
</script>
"""

@app.route('/other')
def other():
    def generate():
        yield "" # Yielding something here fixes the bug.
        sleep(20)
        yield "second"
    return Response(generate(), mimetype='text/plain')


if __name__ == '__main__':
    app.run()
```

**Comment by Stebalien** [comment]
The work around is to set `network.notify.changed` to false. The bug is now https://bugzilla.mozilla.org/show_bug.cgi?id=1235509.

**Comment by calmh** [comment]
Neat.
