### ISSUE TITLE
Version 0.12.9 Windows: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sisu4syncthing** [syncthing/syncthing#2608]
Hi,
after the automatic update I cannot start syncthing anymore.
On my Win7 64Bit Machine, on the CMD.EXE it type:
`C:\syncthing-windows-amd64>syncthing.exe`
`panic: runtime error: invalid memory address or nil pointer dereference`
`[signal 0xc0000005 code=0x0 addr=0x30 pc=0x42467a]`

`goroutine 1 [running]:`
`main.ensureDir(0xc0820578c0, 0x25, 0x1c0)`
`        e:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:1040 +0x15a`
`main.main()`
`        e:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:318 +0x41c`

I downloaded the 0.12.9 from github manually, with the same result.
I tried the 32Bit version too (copied to the 64bit folder out of lazyness...) :
`C:\syncthing-windows-amd64>syncthing.exe`
`panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x1c pc=0x41e868]`

`goroutine 1 [running]:`
`main.ensureDir(0x11862090, 0x25, 0x1c0)
        e:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:1040 +0x108`
`main.main()
        e:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:318 +0x369`

the log shows nothing interesting. Last lines:
`[FNH3H] 07:22:45 WARNING: Automatically upgraded to version "v0.12.9". Restarting in 1 minute.
[FNH3H] 07:22:45 INFO: New UPnP port mapping: external port 42177 to local port 22000.
[FNH3H] 07:23:45 OK: Exiting`

**Comment by calmh** [comment]
I think you're actually running v0.12.9, and that looks like a genuine bug.

**Comment by sisu4syncthing** [comment]
u're correct with my typo in the version and the dealbreaker :-)
corrected the typo.

**Comment by calmh** [comment]
Can you test the build from here, please:

http://build.syncthing.net/job/syncthing-pr/1374/

**Comment by calmh** [comment]
Possibly it may still exit with a fatal error, but in that case I want to know what it is

**Comment by sisu4syncthing** [comment]
Thank you!
I downloaded syncthing-windows-amd64-v0.12.9+3-g2fde621.zip and the result is:
C:\syncthing-windows-amd64>syncthing.exe
08:54:41 FATAL: Lstat : Das System kann den angegebenen Pfad nicht finden.

means, cannot find the path

**Comment by calmh** [comment]
That's really weird. Your config directory, does it exist? Do you have any symlinks or weird windows junctions or whatever involved? I'll make a build to avoid the error, but I'm not sure why it happens in the first place. :)

**Comment by calmh** [comment]
See what happens with this one?

http://build.syncthing.net/job/syncthing-pr/1375/

**Comment by sisu4syncthing** [comment]
That seems to work:
`C:\syncthing-windows-amd64>syncthing.exe`
`[monitor] 10:38:06 INFO: Log output saved to file "${config}/syncthing.log"`
`[monitor] 10:38:06 INFO: Starting syncthing`
`[FNH3H] 10:38:07 INFO: syncthing v0.12.9+3-g0347036 "Beryllium Bedbug" (go1.5.2 windows-amd64) unknown-user@build2.syncthing.net 2015-12-21 08:35:50 UTC`
`[FNH3H] 10:38:07 INFO: My ID: foo`
`[FNH3H] 10:38:07 INFO: Single thread hash performance is ~152 MB/s`

"Your config directory, does it exist? Do you have any symlinks or weird windows junctions or whatever involved?"
Yes, it exists, *and* I have a Symlink created on 
C:\Users\user\AppData\Local\Syncthing pointing to a drive which has a lot of space, because the left space on C:\ will not suffice with the space needed by the database. Its more than 50GB at some time, so I had to move it, because I did not found a way to change the database path in the config and drive C:\ went full.

Is there a userfriendly way to specify another path for the database, btw?

Also, I recognized, that no logfile is written to the disk anymore, as stated here:
`[monitor] 10:38:06 INFO: Log output saved to file "${config}/syncthing.log"`
Only output to the DOS Window, which is ok by now.

**Comment by canton7** [comment]
> Is there a userfriendly way to specify another path for the database, btw?

Yes, run `syncthing.exe -home C:\Some\Path`. Running `syncthing.exe -help` will describe all of the options available to you.

**Comment by calmh** [comment]
> Log output saved to file "${config}/syncthing.log"

This is broken. I think this is something that has gone wrong in the recent refactorings

**Comment by calmh** [comment]
> I have a Symlink created on  C:\Users\user\AppData\Local\Syncthing pointing to a drive which has a lot of space

This is probably the other root cause.

**Comment by sisu4syncthing** [comment]
>This is probably the other root cause.

I copied the whole content of the symlinks folder to C:\Users\user\AppData\Local\Syncthing\ and started the old and not working version to verify that:

`C:\syncthing-windows-amd64>syncthing.exe`
`[monitor] 11:53:52 INFO: Log output saved to file "${config}/syncthing.log"`
`[monitor] 11:53:53 INFO: Starting syncthing`
`[FNH3H] 11:53:53 INFO: syncthing v0.12.9 "Beryllium Bedbug" (go1.6beta1 windows-amd64) SYNCTHING\admin@builder-w2k12r2 2015-12-20 09:05:17 UTC`
`[FNH3H] 11:53:53 INFO: My ID: foo`
`[FNH3H] 11:53:53 INFO: Single thread hash performance is ~153 MB/s`

Then, I changed it back to the symlink and it did not worked, giving the same error as above.

*So that was the cause*.

Thank you for pointing that out, though its a pitty and annoyance at the same time, because it tells me, I cannot trust symlinks on a Windows7 System... (all other symlinks I've ever used worked as expected...)

I'll take the advice from @canton7 and will modify my syncthing-start.bat to something like `@start "Syncthing" /low syncthing.exe -no-console -no-browser -home="X:\path\to\more\wisdom_and_space"`

Thank you both.
