### ISSUE TITLE
REST API: Improve JSON response for /system/connections

### ISSUE THREAD

**Issue by vlcty** [syncthing/syncthing#2611]
I'm currently developing a Nagios/Icinga check to monitor syncthing and it's connections. I use the built in REST API of syncthing to gather the needed information.
According to the docs under http://docs.syncthing.net/rest/system-connections-get.html a sample response is:

```json
{
   "total" : {
          "paused" : false,
          "clientVersion" : "",
          "at" : "2015-11-07T17:29:47.691637262+01:00",
          "connected" : false,
          "inBytesTotal" : 1479,
          "type" : "direct-accept",
          "outBytesTotal" : 1318,
          "address" : ""
   },
   "connections" : {
          "YZJBJFX-RDBL7WY-6ZGKJ2D-4MJB4E7-ZATSDUY-LD6Y3L3-MLFUYWE-AEMXJAC" : {
             "connected" : true,
             "inBytesTotal" : 556,
             "paused" : false,
             "at" : "2015-11-07T17:29:47.691548971+01:00",
             "clientVersion" : "v0.12.1",
             "address" : "127.0.0.1:22002",
             "type" : "direct-dial",
             "outBytesTotal" : 550
          },
          "DOVII4U-SQEEESM-VZ2CVTC-CJM4YN5-QNV7DCU-5U3ASRL-YVFG6TH-W5DV5AA" : {
             "outBytesTotal" : 0,
             "type" : "direct-accept",
             "address" : "",
             "at" : "0001-01-01T00:00:00Z",
             "clientVersion" : "",
             "paused" : false,
             "inBytesTotal" : 0,
             "connected" : false
          },
          "UYGDMA4-TPHOFO5-2VQYDCC-7CWX7XW-INZINQT-LE4B42N-4JUZTSM-IWCSXA4" : {
             "address" : "",
             "type" : "direct-accept",
             "outBytesTotal" : 0,
             "connected" : false,
             "inBytesTotal" : 0,
             "paused" : false,
             "at" : "0001-01-01T00:00:00Z",
             "clientVersion" : ""
          }
   }
}
```

I would like to see an improvement of the response by using an array containing every connection. For example:

```json
{
   "total" : {
          "paused" : false,
          "clientVersion" : "",
          "at" : "2015-11-07T17:29:47.691637262+01:00",
          "connected" : false,
          "inBytesTotal" : 1479,
          "type" : "direct-accept",
          "outBytesTotal" : 1318,
          "address" : ""
   },
   "connections" : [
           {
             "id": "YZJBJFX-RDBL7WY-6ZGKJ2D-4MJB4E7-ZATSDUY-LD6Y3L3-MLFUYWE-AEMXJAC",
             "connected" : true,
             "inBytesTotal" : 556,
             "paused" : false,
             "at" : "2015-11-07T17:29:47.691548971+01:00",
             "clientVersion" : "v0.12.1",
             "address" : "127.0.0.1:22002",
             "type" : "direct-dial",
             "outBytesTotal" : 550
          },
          {
            "id": "DOVII4U-SQEEESM-VZ2CVTC-CJM4YN5-QNV7DCU-5U3ASRL-YVFG6TH-W5DV5AA",
             "outBytesTotal" : 0,
             "type" : "direct-accept",
             "address" : "",
             "at" : "0001-01-01T00:00:00Z",
             "clientVersion" : "",
             "paused" : false,
             "inBytesTotal" : 0,
             "connected" : false
          },
          {
             "id": "UYGDMA4-TPHOFO5-2VQYDCC-7CWX7XW-INZINQT-LE4B42N-4JUZTSM-IWCSXA4",
             "address" : "",
             "type" : "direct-accept",
             "outBytesTotal" : 0,
             "connected" : false,
             "inBytesTotal" : 0,
             "paused" : false,
             "at" : "0001-01-01T00:00:00Z",
             "clientVersion" : ""
          }
   ]
}
```

The current response is not a RFC violation.

**Comment by canton7** [comment]
See #1487 and linked issues.

Making a change like this without good reason would break a large bunch of applications which currently rely on the current format of this response. The current response format is pretty idiomatic, and personally I see no reason to change it.

**Comment by AudriusButkevicius** [comment]
You have expressed what you want, but no reason why.

**Comment by calmh** [comment]
Maybe we should add some `,omitempty` to those structs, to avoid the empty `clientVersion`, `address` and so on fields in total/disconnected hosts though.

**Comment by vlcty** [comment]
The reason is not a RFC violation but a personal interest.
Currently every connection is stored as "subobject" with the ID as the key. For me that's not object noted style because at runtime you don't know what keys (the IDs) are there.
With an array you can just loop over it an get every connection object with having to know the key name thus the device ID has to be moved in the object.

**Comment by canton7** [comment]
With a dictionary/hashmap you should be able to loop over all key/value pairs. Most languages make it exactly the same as looping over an array, except that elements are unordered. 

I notice you use perl in some of your other projects. Perl definitely supports looping over all keys/values in a hash.

**Comment by vlcty** [comment]
Yes that's possible and I implemented it like that.
Well ok. Let's dismiss this here.

**Comment by canton7** [comment]
Even if it had made sense to make this change, it would still have been several months before such a change could have been released: you can't just make breaking changes to APIs which other people rely on.

**Comment by vlcty** [comment]
I never expected that. Just thought a collection of object should be stored in a list.

**Comment by canton7** [comment]
Yeah, but it's an unordered collection with a very obvious unique identifier, so a dict is fair game.
