### ISSUE TITLE
Cannot override GUI assets

### ISSUE THREAD

**Issue by thgh** [syncthing/syncthing#2621]
Noticed this on 0.12.9 on Windows 8.1

I tried different releases and 0.12.9 is the only one that shows the default interface.

**Comment by AudriusButkevicius** [comment]
Haven't verified but with the runtimeOptions refactor it's possible we broke something.

**Comment by canton7** [comment]
This definitely doesn't look right: https://github.com/syncthing/syncthing/blob/4874301615cf8288293a1b9755f5be5c257cb8df/cmd/syncthing/main.go#L228

Yeah, [this](https://github.com/syncthing/syncthing/commit/d10e81fb3d2c69b7c8595773c3aba9c3ea624c29#diff-90be85495f283f39a39308cf8ffb765cL278) got changed to [this](https://github.com/syncthing/syncthing/commit/d10e81fb3d2c69b7c8595773c3aba9c3ea624c29#diff-90be85495f283f39a39308cf8ffb765cR232) which is definitely wrong. #2592 is at fault.

FYI @andersonvom .

**Comment by calmh** [comment]
@thgh Thanks

**Comment by andersonvom** [comment]
Doh! That was definitely wrong. :(
I wonder if we could run the `expandLocations()` function early on (i.e. before parsing the runtime options or even at the end of `init()`). This way we could centralize the option parsing in a single place, including setting defaults and all, and would get rid of "X needs to happen after Y" type of things. Thoughts?

**Comment by calmh** [comment]
It depends on -home having been processed, so it's a bit of a chicken and egg setup
