### ISSUE TITLE
Android. Constant restarts, aborts

### ISSUE THREAD

**Issue by bzzz2** [syncthing/syncthing#2623]
constant bug on Android. application starts, waits for some time and finally prints out message: "Could not create Syncthing config. See log file" (translated from russian).
Some updates ago, it seems 0.7.3 version, syncthing worked fine.
Android version 4.0.4
Syncthing version 0.7.5. This bug started from 0.7.3 after a week of good work
log file attached [2015-12-16-23-32-02.txt](https://github.com/syncthing/syncthing/files/72496/2015-12-16-23-32-02.txt)

**Comment by Zillode** [comment]
Same issue as described in https://github.com/syncthing/syncthing-android/issues/515
