### ISSUE TITLE
Shared With list starts with comma

### ISSUE THREAD

**Issue by ironmig** [syncthing/syncthing#2626]
I've noticed that the Shared With list under the folder panel sometimes (always?) starts with a comma, and it looks funny. Should be an easy fix.

![screenshot from 2015-12-29 21-47-50](https://cloud.githubusercontent.com/assets/9502636/12045668/d608bd9e-ae75-11e5-8713-baaa4b3df88b.png)

**Comment by ironmig** [comment]
Working on a fix

**Comment by ironmig** [comment]
It occurs when duplicate devices are present. When the syncthing's config has two devices with the same ID, $scope.findDevice returns undefined so an empty string is added to the array.

**Comment by calmh** [comment]
Resolved by #2628, as that prevents duplicate device IDs from being added.
