### ISSUE TITLE
Incorrect handling of vector clocks in 3-way sync

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing#2629]
Syncthing v0.12.9, Linux

Suppose there are 3 devices: A, B, C that share 1 folder. This share contains one subfolder Music containing a number of files (i.e. Music/1.mp3, Music/2.mp3, Music/3.mp3) which is fully synchronized across the devices. When we delete the Music folder on A when B is offline, all files will be resynced to A in the following scenario:

1. B is offline
2. User deletes Music on A
3. Syncthing deletes Music on C
4. A is offline
5. B is online
6. B syncs Music to C, undoing the delete (!)
7. A is online
8. B and C will sync Music to A, undoing the delete

I'm writing a unit test for this, but it's not finished yet. However, I opened this issue because it's probably related to https://github.com/syncthing/syncthing/issues/2619.

**Comment by calmh** [comment]
Sounds odd. I don't see anything here that would cause a conflict. This would happen if the music files where detected as changed on B somewhere along steps 2-4 though, and is in that case as designed.

**Comment by calmh** [comment]
Before writing a test for this (which may be a bit of work), check the files with `/rest/db/file?folder=...&file=...` to see the version vector at step 3 and 6. If it's been incremented by the ID of B (which I suspect), then running with STTRACE=scanner on B should show what modification it's detecting there.

**Comment by Zillode** [comment]
couldn't reproduce, probably missing a step
