### ISSUE TITLE
Scanning of missing folder is not paused correctly

### ISSUE THREAD

**Issue by scienmind** [syncthing/syncthing#2630]
For some reason when performing initial scan, instead of skipping unavailable folders (drive unmounted), syncthing continue posting errors every second about missing .stignore file:
```
 [IDIDID] 21:34:52 WARNING: Loading .stignore: open \\?\D:\Some_Synced_Folder\.stignore: The device is not ready.
 [IDIDID] 21:34:53 WARNING: Loading .stignore: open \\?\D:\Some_Synced_Folder\.stignore: The device is not ready.
 [IDIDID] 21:34:54 WARNING: Loading .stignore: open \\?\D:\Some_Synced_Folder\.stignore: The device is not ready.
 [IDIDID] 21:34:55 WARNING: Loading .stignore: open \\?\D:\Some_Synced_Folder\.stignore: The device is not ready.
 [IDIDID] 21:34:56 WARNING: Loading .stignore: open \\?\D:\Some_Synced_Folder\.stignore: The device is not ready.
 [IDIDID] 21:34:57 WARNING: Loading .stignore: open \\?\D:\Some_Synced_Folder\.stignore: The device is not ready.
...
```

Eventually syncthing will often crash, or show this message (via SyncTrayzor):
![image](https://cloud.githubusercontent.com/assets/11633330/12056503/bfb1ca34-af3f-11e5-8233-b84cb7a4ee3c.png)

OS: Win7 x64
Syncthing v.0.12.10

(Edit: info and formatting)

**Comment by AudriusButkevicius** [comment]
Which exact part of the path is unavailable? What does the web UI show?

**Comment by scienmind** [comment]
The drive containing the folder is not connected. Syncthing used to handle it well few versions back

**Comment by scienmind** [comment]
WebUI:
![image](https://cloud.githubusercontent.com/assets/11633330/12056550/4a1cbb0c-af40-11e5-831c-2f74ebbced2c.png)
![image](https://cloud.githubusercontent.com/assets/11633330/12056620/0c855c58-af41-11e5-8255-0445533d4bf3.png)

**Comment by scienmind** [comment]
Is there any temporary workaround available to "disable" the troublesome folder, without "removing" it until the fix is merged and released? 
(this folder is nearly 3TB in size, and i'd prefer to avoid the initial scan, which is really really long, once the fixed version is released)

Maybe some command line switch or config file edit or something like that?

**Comment by AudriusButkevicius** [comment]
The fix is only going to remove the repeated error message, not anything else.
