### ISSUE TITLE
Add public shares

### ISSUE THREAD

**Issue by henryx** [syncthing/syncthing#2633]
Currently syncthing uses a share system that I need to enable devices to sync a folder with other devices. Is a good idea to set one folder to be "public", so, when I set this flag, folder is automatically shared to others devices

**Comment by rumpelsepp** [comment]
Most likely you are searching this: https://forum.syncthing.net/t/introducer-description-and-functionality/1016

**Comment by henryx** [comment]
Concept is a bit different. If I understand the concept behind the introducer flag, is used to create a chain of trust (e.g. if I declare the machine Aries an introducer, when I add the introducer in Moon, Aries trust for Taurus, Gemini, Cancer and so on). My use case is different. Suppose this:

 - MachineA create a share called Public and flagged as public share;
 - MachineB add MachineA to its chain;
 - MachineA offer Public share to MachineB without ask permissions.
 - MachineB can decide to accept Public share or not

In fact, is the same concept behind to share a Google Drive link which can permit to  view the folder to all users that have the link

**Comment by AudriusButkevicius** [comment]
It should be fairly trivial to add, for anyone who wants to contribute this feature.
Essentially adding a Public boolean flag on the folder, and the taking that into account in all the `IsSharedWith` business.

**Comment by calmh** [comment]
Is this just a folder that is shared by default with new devices, as opposed to the current not-shared-by-default setup?

**Comment by calmh** [comment]
(There's been a lot of discussion about public shares before, but in the sense of shares that are accessible to devices we don't already have a relationship with, a la regular BitTorrent)

**Comment by henryx** [comment]
@calmh when I opened the ticket, I've thinked a share a la regular BitTorrent (I've searched in the issues history, but I've not found anything), but your synthesis is more similar to my explain. In fact, concept is to create a public archive accessible by others without permissions to server, as same as public folders in Google Drive or Dropbox

**Comment by AudriusButkevicius** [comment]
I think that's much harder than what I initially understood you were asking for. I was thinking about public shares with trusted devices. 

Also, I feel its opposing goals of syncthing, namely security, as there would be none.

**Comment by calmh** [comment]
Yeah...

> public archive accessible by others without permissions to server

This is something we've looked at before, but unfortunately it's surprisingly difficult to fit in the current syncthing concept. For this reason and others we've decided that it's out of scope for this project. 

(But someone could create something similar using the same protocol and so on, if they wanted to.)

**Comment by lordloh** [comment]
Sad :( I wanted a public share feature too. Anyone I add to my syncthing, automatically  have the option to start a one way (or two way) sync to public folders.

An extension would be to publicize my server ID and let anyone add my server and sync publicly shared folders. This would also introduce them to all users sharing the same folder.

Hope the team reconsiders this in future.
