### ISSUE TITLE
"Move to top of queue" buttons don't appear on every file

### ISSUE THREAD

**Issue by lblblb** [syncthing/syncthing#2634]
When I click on the list to show out of sync items, there are blue buttons to move the respective files to the top. Why do not all files except the first in this list have this button and why does it sometimes happen, as shown in the screenshot, that only one file will have the button?

![2015-12-31 18_10_47-aspire7750g _ syncthing](https://cloud.githubusercontent.com/assets/12690798/12066563/0ef309aa-afea-11e5-8ab7-4aac65c5e4cb.png)

**Comment by AudriusButkevicius** [comment]
Because one of them is already in progress, and we can stop it, the other one is the next one in line, so moving it up makes no sense, and the last one has arrived in a different batch hence we haven't yet got to processing it.
