### ISSUE TITLE
Sort order of devices by their status

### ISSUE THREAD

**Issue by chauffer** [syncthing/syncthing#2636]
It'd be nice to have an option to sort by the status of the device (such as Disconnected, Up to Date), instead of having it alphabetically.

**Comment by calmh** [comment]
Yep

**Comment by marrie** [comment]
I also agree with this. I can't remember if I  suggested this in the forums or not, but yeah. I think this is a good idea.

**Comment by ebrius** [comment]
There isn't anywhere else in the UI that sorting is allowed, right? So this would be a new design, I'm thinking next to the 'Devices' header (though that may be a little confusing since the first device probably wouldn't be sortable)

**Comment by Kropekk** [comment]
I will try to do it in the next few days.

**Comment by calmh** [comment]
Quoting myself,

> Here's my opinion, which is weakly held and could potentially change: we should not do sorting apart from the alphabetical one. My reasoning behind that is that the device sections are click targets. Moving them around when there are things like pause, edit and resume buttons that users will try to click is counter productive. Likewise that clicking pause on a connected device will re-sort the list and move away the device from where I just clicked on it.
>
> (The last argument is weak because as it is we reload the list and close the device section I just clicked in, which is just as bad. We should not do that either.)
