### ISSUE TITLE
Devices seem to respond badly to mismatching ignore patterns

### ISSUE THREAD

**Issue by porglezomp** [syncthing/syncthing#2637]
One of my devices has
```
#*#
.#*
```
in its ignore list, and the several other ones have no ignore patterns.
The syncing devices tend to get stuck at 99% and stop transferring data.
When I added the ignore patterns to one of the devices, it fully correctly synced.
Devices should probably share their ignore patterns to some extent for this purpose.

**Comment by calmh** [comment]
This is as expected. As the ignore patterns are not shared, devices with ignore patterns will have fewer files than devices without ignore patterns and thus appear as less than 100% in sync to those devices. There are legitimate uses for this; for example a device that shares a certain folder but only syncs .jpg files from it and not .tiff files, etc.

**Comment by porglezomp** [comment]
I feel that the devices should share enough information to say "I have synced every file that I intend to sync," so that they can provide at the least a different indicator of what's happening. I spent hours trying to figure out what was going on.

**Comment by AudriusButkevicius** [comment]
I think there is a big ticket for reworking ignores, which potentially contains a fix for this.
