### ISSUE TITLE
Why not use Slack or Gitter for team communication?

### ISSUE THREAD

**Issue by wildcard** [syncthing/syncthing#2640]

**Comment by AudriusButkevicius** [comment]
You sound like a salesman. Why would we use some proprietary software? 
Why is IRC (what most OSS projects use) not good enough? Why is the forum not good enough?

**Comment by calmh** [comment]
We use Slack at work. It's really neat. It's also quite unsuitable for open source projects; it requires registration and accounts and stuff. I'm not fond of gitter either.

**Comment by calmh** [comment]
That said, gitter looks like it's grown up a bit and it has an irc bridge. So I guess it's friendlier for some people, less so for others. :+1: / :-1:

**Comment by AudriusButkevicius** [comment]
25 people per channel if you don't want to pay

**Comment by calmh** [comment]
Only for "private" rooms as far as I can see. But now I'm just advocating it for the sake of it, I don't particularly see a reason to switch.

**Comment by calmh** [comment]
I tried it out. We're not going to be using gitter at the moment.

**Comment by wildcard** [comment]
I'm not a salesman, but it's not the first time someone thinks I'm a salesman ;)
I'm not saying freenode is bad I'm just saying it's popular to use gitter or slack for open source projects.
Why? Your communications is open so Slack or gitter will be free.
gitter and slack has a growing user base
gitter and slack has mobile applications and desktop application, really easy to use.

I can post here OS projects who use slack or gitter if it's needed.
I just love the projects and I want it to continue to flourish and easy and accessible communication is important for that.

Just my opinion ^_^ continue to be cool.
I see this project as really refreshing and revolutionary, 10x

**Comment by calmh** [comment]
Thanks. At this point we'll stay with the web based forum and the IRC channel. The forum is anyway the more visited of the two, and is open and easy to use for anyone.

**Comment by canton7** [comment]
I don't see any reason given there other than "it's the current fad" :P +1 for staying with IRC: we can add a link to freenode's web interface (defaulting to #syncthing) if that's an issue....

**Comment by calmh** [comment]
That web UI is rather horrible unfortunately :/

**Comment by wildcard** [comment]
Look what this projects is doing https://github.com/rackt/redux

**Comment by wildcard** [comment]
I forgot to mention that these chat clients enable snippets and markdown.

**Comment by AudriusButkevicius** [comment]
So does the forum.
Now you are really trying to sell it.

**Comment by calmh** [comment]
I've linked to https://kiwiirc.com/client/irc.freenode.net/#syncthing from the forum to start with. I think that concludes this. :)
