### ISSUE TITLE
Actual debug UI

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2644]
We have the REST parts for setting debug levels and accessing log data, but no UI for it. We need something that allows setting the various debug facilities, view and download the log data. It should probably be on a page by itself.

**Comment by canton7** [comment]
Bear in mind that you've told me that I can assume that SyncTrayzor is the only thing setting and clearing these flags. If you're going to allow it from within syncthing, I'll remove the corresponding functionality from SyncTrayzor. 

I'm planning the first release which contains the debug stuff in about a week, so please let me know whether I should strip that stuff out before then.

**Comment by AudriusButkevicius** [comment]
`Unplanned (Contributions Welcome)` explains it.

**Comment by calmh** [comment]
Eh? Of course there's no guarantee synctrayzor is the only one changing this, the user could already use curl or something to do so, much like anything else (the config, etc). I think we must have misunderstood one another in that case.

**Comment by canton7** [comment]
The conversation went... 

> However, this means that I need to notice when some other API client changes them, so that I can update my stored record of which ones to set on startup

> I'd suggest ignoring what anyone else does and just do your thing from within Synctrayzor

I don't want to duplicate stuff that's in syncthing, and I don't really want to add some UI now only to remove it later (that will confuse the users) , so i'm not really sure what to do here...

**Comment by calmh** [comment]
The reason we were talking about that at all, I think, was that Syncthing doesn't do any logging when run from within SyncTrayzor (as it doesn't use the monitor process), and this sort of hampers debugging. Since SyncTrayzer has kind of taken over that responsibility, I thought it would be nice if it could enable the logging again. But yeah, I want this UI in Syncthing core and as such there's probably no pressing need to duplicate it from your side. (You're more than welcome to implement it on Syncthing instead, if you feel like hacking some javascript.;)

Maybe you could start with a middle road, and just capture stdout to somewhere accessible as you're the one launching the syncthing process?

I just want it to be easier for the users to get at the relevant logs.

**Comment by calmh** [comment]
I think this was in fact fully resolved by the above PR, the commit message just didn't cover it.
