### ISSUE TITLE
Are there third party developers documentation? Can they use a library?

### ISSUE THREAD

**Issue by timofonic** [syncthing/syncthing#2646]
Hello.

I would like to see SyncThing support in rclone. @ncw (the main developer) asked if there's some library he can use.

https://github.com/ncw/rclone/issues/265

I see there's a lib/ directory, but I'm not a developer so not know if it's usable by third party software. Both projects are written in Go, so maybe there can be some collaborative process.

I leave the discussion to both, thanks for all!

Kind regards.

**Comment by AudriusButkevicius** [comment]
So the libraries have doc strings, and the protocol is documented in docs.syncthing.net, but I don't see how it fits with rclone to start with.

**Comment by calmh** [comment]
There is a protocol library (lib/protocol here), but it's written in Go so not easily usable from another language.

**Comment by timofonic** [comment]
@calmh 

Yes, rclone is developed in Go too ;)

I would love if rclone can be made a syncer tool, then allow to mirror directories between different syncing services (including syncthing).

I often have to deal with directories shared over DropBox, Google Drive, OneSync and such. It's a total pain in the ass.

I'm not a developer, I would like to be one. I'm just a mere user providing feedback and hoping the miracle would happen :P

These issues are somewhat related to the idea. I'm not still a developer, just a lurker...

https://github.com/syncthing/syncthing/issues/2647
https://github.com/ncw/rclone/issues/249

**Comment by calmh** [comment]
Yep. As this was just a query I'll go ahead and close it, but the rclone (or anyone else) is free to drop in on the forum or the IRC channel for questions on how to integrate. The protocol package is there, but I think reading and understanding the protocol spec is probably a prerequisite to using it.
