### ISSUE TITLE
Remote "cloud storage" support for folders

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2647]
It could in some cases be neat to store data somewhere else than on local disk. Primarily I'm thinking of things like Amazon S3 and Joyent Manta - essentially glorified object stores with a REST interface. The use case would be to keep an off site mirror of a folder, perhaps directly used for web serving or something.

There is a complexity in that if we are asked for a block, or need to update a block in a file, we usually would need to download or upload the entire file, not just the block in question. For serving data this could be backed by a local disk cache, so we fetch the file on first reference and keep it around for a while. For updates it would probably mean the same, with upload happening when sync of a file has completed.

An alternate model is to not store _files_ in S3 but the actual block objects, named by hash, plus something like a serialized copy of the index. This makes updates and requests more efficient, at the price of not having the data immediately available in actual file format. As an aside, encryption would be much simpler to implement in this case. The keys and so on would live on the box that runs Syncthing, and the actual remote storage would just store encrypted blocks and have no knowledge of the keys.

**Comment by AudriusButkevicius** [comment]
So I think we could potentially abstract the os.File package away (I know there already was a go library which did that), and plug in whatever storage we want. I think it even had S3 and some other backends implemented.

We could have one backend which stores a block per object, or a file per object, giving different performance characteristics.

Again, folder path could be made into URI's ala `/data/myfiles` or 'file://var/syncthing/`, and then `s3://cloud-provided-by-a-bookshop.com/` could be just a backend.

I know we are a bit too trigger happy with the URI's but they get the job done.

I can't seem to find the go package which abstracted the filesystem away, but it was called something like aerofs or areafs.

**Comment by AudriusButkevicius** [comment]
Here it is:

https://github.com/spf13/afero

**Comment by AudriusButkevicius** [comment]
This could also make testing easier.

**Comment by calmh** [comment]
Yep, I had afero bookmarked as well for that purpose. It just needs extending with lstat and some plumbing.

**Comment by timofonic** [comment]
This is somewhat related, but it's more for file syncing...

https://github.com/ncw/rclone/issues/249

**Comment by praxiq** [comment]
> There is a complexity in that if we are asked for a block, or need to update a block in a file, we usually would need to download or upload the entire file, not just the block in question. 

Just want to point out some interesting bits of the Amazon S3 docs: 

> Using the Range HTTP header in a GET request, you can retrieve a specific range of bytes in an object stored in Amazon S3.

> Using the Multipart upload API... you can upload objects in parts. These object parts can be uploaded independently, in any order, and in parallel. You can't change the value of an S3 object, but you can create a new object by copying some blocks from an existing object, and uploading new blocks representing only the changed parts.

As for changing a file, I think S3 objects are immutable, but the Multipart Upload API lets you create a new object by copying some blocks from an existing S3 object, and only uploading the changed blocks. 

All things considered, these features could make S3 storage pretty practical.

**Comment by calmh** [comment]
Neat.

**Comment by Nutomic** [comment]
If you're already thinking about wrapping the File class and using URIs instead, maybe you can consider file:// URIs used by the Android [Storage Access Framework](http://developer.android.com/guide/topics/providers/document-provider.html).

This would fix syncthing/syncthing-android#29. See golang/go#10588 for more info.

**Comment by AudriusButkevicius** [comment]
We can implement whatever scheme we want, once the abstraction is in place.

**Comment by Nutomic** [comment]
According to [this stackoverflow question](http://stackoverflow.com/questions/9144332/android-accessing-content-provider-data-from-ndk-c-side), they can only be resolved from Java. Seeing as you can't get an actual file from the URI, that means you'd have to send them back to the Java code for each file/folder access (as far as I can see).

**Comment by AudriusButkevicius** [comment]
Is that only for uri to path resolution, or for actual reading too?

**Comment by Nutomic** [comment]
You can't convert the URI to a normal path (if that's what you mean by resolution). You have to use Java API functions for any file access like create, edit, delete etc (see my Storage Access Framework link above for the API).

**Comment by cyplo** [comment]
Heyo ! Any news on this one ?

**Comment by AudriusButkevicius** [comment]
No news as you can see.

**Comment by AudriusButkevicius** [comment]
Closing this as the relevant abstractions are not in place, someone just needs to implement the interfaces for integration.
