### ISSUE TITLE
UPnP port mapping failure

### ISSUE THREAD

**Issue by noodle-** [syncthing/syncthing#2648]
Enabling UPnP causes my router to get filled up with UPnP port mappings because Syncthing opens a new one every 20 minutes.

When the router can't handle any more UPnP port mapping requests (it's not the most high quality router but that's beside the point I'm trying to make here) Syncthing will start showing the following error message: 
"Failed to set UPnP port mapping: external port 0 on device {name} (IP)" as also described here #1824.
and my router's UPnP Port Mapping will look like this

![routerupnp](https://i.imgur.com/iOKvNwA.png)

Things I've tried to no avail; 
(While there's only one device with UPnP enabled) I've set the "Sync Protocol Listen Addresses" for every Syncthing device to a different one.
Enabled UPnP on all other devices, to see wether it was just one device causing the issue. All latest Linux and Windows builds seem to be affected.

My Android device doesn't seem to be affected by this issue, it only has one entry in the list of UPnP port mappings and it seems to be working just fine.

Devices:
- Windows 10 / SyncTrayzor 1.0.32 / Syncthing v0.12.10
- Windows 10 / SyncTrayzor 1.0.32 / Syncthing v0.12.10
- Linux Debian 3.4.108-bananian / Syncthing v0.12.10 
- Android 5.1.1 / Syncthing-Android v0.7.5 / Syncthing v0.12.6

I have no idea why this only started happening recently (as in the last two or three weeks) but that's why I posted this as a seperate issue instead of adding it to #1824.

**Comment by AudriusButkevicius** [comment]
It tries up to 10 first pseudo-random ports per device ID.
Which means that for device ID X, the 10 ports will always be the same.
This could happen if you cycled device ID's multiple times and the lease time you are asking is permanent.

Can you remove the port mappings, and run syncthing with envvar STTRACE=upnp and provide the logs?

**Comment by noodle-** [comment]
>This could happen if you cycled device ID's multiple times and the lease time you are asking is permanent.

I haven't changed any device ID for a while as far as I know. The syncthing setups are relatively old, updates aside. 

I had set the lease time to permanent after the issue occured. I've set it back to 60 on all systems now.

>Can you remove the port mappings, and run syncthing with envvar STTRACE=upnp and provide the logs?

I've removed the mappings and started Syncthing with upnp logging and I'll just keep it running untill I see more than 3 port mappings on my router (because the lease time is 60m and it gets renewed every 20m, right?).

---

So I waited 1+ hour and apparantly the port mappings simply don't get released.

![upnp](https://i.imgur.com/QY0060c.png)

[Here](http://pastebin.com/mSDc1Fyk)'s the full log for you to see that leasetime isn't set to permanent etc.

So even the first port mapping didn't get removed while it's 1.5 hours later now.

Don't know where to go from here myself and wether it's actually Syncthings fault or maybe just my silly router.

**Comment by calmh** [comment]
I *think* the router is at fault here, as I think you're supposed to be able to renew a port mapping like this. But I could be wrong and AddPortMapping isn't the right thing to do. But since your router doesn't expire, a workaround is probably to set syncthing to use permanent leases.

**Comment by calmh** [comment]
Yeah, UPnP spec, http://upnp.org/specs/gw/UPnP-gw-WANIPConnection-v1-Service.pdf (v1 which we're apparently using while v2 is the current one?) says that a request with the same external port and internal ip+port is a renew. I think the root problem is that the router takes our request for a temporary lease and makes it a permanent one, then doesn't permit renew of it.

**Comment by AudriusButkevicius** [comment]
I tried googling around for error codes for some other UPnP issue, but I couldn't find anything.
Perhaps we should handle 904 if that's an official code defined by the protocol.

**Comment by AudriusButkevicius** [comment]
Ok, that doc has most of them (though no 904). I think some routers incorrectly return 718 for the same scenario.

**Comment by noodle-** [comment]
The router is a ZTE H220N that has been provided by my ISP but with that info I can't find anything on UPnP error 904 either.

Why is the external port changed every 20 minutes anyways? I'm guessing for a little improved security?

Would disabling UPnP and port forwarding 22000 (or 22002 for me) provide the same functionality as what UPnP is supposed to do?

**Comment by AudriusButkevicius** [comment]
It's not changed. It's renewed every `renewInterval` which is adjustable in the config.
Yes mapping 22000 to 22000 and disabling UPnP on syncthing would do the trick.

**Comment by AudriusButkevicius** [comment]
I am closing this, as it's not our issue.

**Comment by noodle-** [comment]
Allright, thank you!
