### ISSUE TITLE
Auto-upgrade broken on FreeBSD

### ISSUE THREAD

**Issue by asaddi** [syncthing/syncthing#2650]
On FreeBSD, v0.12.9 successfully auto-upgraded to v0.12.10. But today, I noticed it failed to upgrade automatically to v0.12.11.

The error message was something about readlink failing on /proc/curproc/file. The /proc filesystem is optional in FreeBSD.

The issue is related to [this commit](https://github.com/syncthing/syncthing/commit/37aa89b19df83fab36d2ad2c25db02919bbb626a). The very next day, osext [reverted the commit](https://github.com/kardianos/osext/commit/29ae4ffbc9a6fe9fb2bc5029050ce6996ea1d3bc) that the godep was updated to.

I believe sysctl is the proper way to get the running executable's path on FreeBSD, so [this temporary fix](https://github.com/syncthing/syncthing/commit/aaa75a32a50bf8f5defffff96b681feefae9754b) should also be undone.

**Comment by calmh** [comment]
Yeah. Curiously it was someone who had the opposite problem who wanted me to update the osext package, and me that filed the issue that caused the revert... But I'll update again, to the reverted version. *shrug*

**Comment by plouj** [comment]
Sorry about that! I made the original request for a fix without fully understanding the problem.

**Comment by calmh** [comment]
:D No worries

**Comment by paulhargreaves** [comment]
My system has also stuck at 12.10 and clicking the 'automatic upgrade' just fails with:
2016-01-14 13:47:08: upgrading: readlink /proc/curproc/file: no such file or directory

Do we have to manually update to work around this?

**Comment by calmh** [comment]
Probably

**Comment by rahra** [comment]
You have to mount procfs on your FreeBSD system and the update will work: `sudo mount -t procfs proc /proc`.
