### ISSUE TITLE
gui: In sync percentage can be incorrect for empty folders with deleted files

### ISSUE THREAD

**Issue by 5chdn** [syncthing/syncthing#2652]
After deleting the last file from a sync folder and the status drops to **0 objects**, the sync status shows weird stuff. like **syncing (5220%)**.

![screenshot at 2016-01-03 20 44 27](https://cloud.githubusercontent.com/assets/15729797/12080464/4168368a-b25b-11e5-8a39-02988bf74ad9.png)

this somehow messes up the javascript, showing no details for the connected devices, not even unknown status.

uptime on this instance was 11 days. the backend seems not affected. restarting the syncthing and reloading the frontend turns everything back to normal. syncthing 0.12.9, archlinux kernel 4.0.6-1-ARCH x86_64.

**Comment by AudriusButkevicius** [comment]
Dup #623

**Comment by calmh** [comment]
I think this is a legit bug of some kind; we account deleted files as well in the local state, and apparently the amount of deleted files in the local and global state differs here.

**Comment by calmh** [comment]
Out of curiosity, what happens after restarting Syncthing?

**Comment by 5chdn** [comment]
After restarting it's **up to date**, but the difference in local and global state persists. I understand the size is an estimate. Wondering why 0 objects can be 1 kiB in size.

     Global State 	0 items, ~1.63 KiB
     Local State 	0 items, ~1.13 KiB

This is really a minor issue.

**Comment by calmh** [comment]
Each deleted file in the index is accounted as 128 bytes (for ... reasons).

**Comment by 5chdn** [comment]
Where to find the JS logs by the way?

**Comment by 5chdn** [comment]
I just noticed this again. With v0.12.14 and also on a very slow device (raspberry pi 2). It might be an issue with the javascript, just a frontend issue? Some minor observations: favicon is missing, devices don't show status (see screenshot above), can not switch the language.

**Comment by canton7** [comment]
> Where to find the JS logs by the way?

In most browsers, hit F12. It's typically called something like "developer tools", ans you're after the section called "console" or similar.

**Comment by calmh** [comment]
*Actually* I think this is one of the cases where the in sync percentage is actually correct nowadays. Let me retest.

**Comment by calmh** [comment]
I know I've changed things here again, but I have a couple of things I want to test again when I remember it. This is a reminder. :)
