### ISSUE TITLE
Getting sec_error_unknown_issuer on Firefox

### ISSUE THREAD

**Issue by GijsTimmers** [syncthing/syncthing#2657]
This happens when opening the Syncthing web interface for the first time on a fresh Firefox. The URL is https://localhost:8384.

    Technical details:
    
    localhost:8384 uses an invalid security certificate. The certificate is not trusted
    because it is self-signed.(Error code: sec_error_unknown_issuer)

This isn't really a problem, I have to press <kbd>I understand the risks</kbd> and <kbd>Add an exception</kbd> to resolve this. But it would be nice if this wouldn't be necessary.

**Comment by canton7** [comment]
There's no possible way of avoiding this, unfortunately (other than perhaps installing our own root certificate, which is even more dodgy). Syncthing is available at `localhost`. The connection is HTTPS, therefore a certificate is needed. No-one is ever going to issue a certificate for `localhost`, therefore it needs to be self-signed. It's self-signed, therefore firefox (and all other browsers) display a warning message.

**Comment by canton7** [comment]
I should say, you're welcome to add the certificate to your trusted store on Windows (or whatever OS you're using), but I don't think this is something that Syncthing should do (particularly as this would require both an installation step and root/Administrator privileges, and Syncthing currently requires neither).

**Comment by calmh** [comment]
It is as canton7 says.

**Comment by GijsTimmers** [comment]
I see. Too bad.
