### ISSUE TITLE
feature request: read only node (all changes here will be overwritten by other nodes)

### ISSUE THREAD

**Issue by frank-github** [syncthing/syncthing#2658]
I want to use one node in **readonly** modus, all changes here should NOT be synced to other node. And more, all changes here should be overwritten from changes by other nodes.

Let's say I have 4 nodes A,B,C and R
A,B,C are **work**stations, changes done by one of this nodes shall be distributed to all other nodes and vice versa.
If a file is deleted by node R, it should be resend to node R next time synced with other nodes
If a file is changed by node R, it should be overwritten on node R next sync time
Some systems call node R a kiosk, all people can use this node and do anything, but everything will be overwritten later again.

If I am correct, I can't set A,B,C to master nodes, because no changes will synced between this nodes anymore

seems not to be supported yet
https://forum.syncthing.net/t/three-node-syncthing-with-two-masters/415/7

**Comment by calmh** [comment]
Dup of #62 I think.

**Comment by frank-github** [comment]
yes, after a quick look to link, mine maybe a dup, sorry...
but I'm not alone, I would be happy if it would be part of syncthing in near future

**Comment by calmh** [comment]
Yep
