### ISSUE TITLE
Seperate devices that are added through introducers from 'normal' devices

### ISSUE THREAD

**Issue by l3d00m** [syncthing/syncthing#2659]
Improvement/Feature Request for the Web GUI

**Explanation:** I am using syncthing to download [Tronscript](https://www.reddit.com/r/TronScript/comments/3o7tq1/syncthing_server_up_and_running_testing/). I've added the main device and made it an introducer, so I can sync with the whole cluster and relieve the bandwith usuage of the main device a bit (Syncthing is an alternative to the closed-source BitTorrent Sync for us in this case).

The **problem** I have is that all the devices that are added through this introducer are shown in my devices list together with my "normal" devices. Is it possible to seperate them somehow or to not show them at all?

**Comment by calmh** [comment]
Currently, once added, they are treated in exactly the same way as manually added devices so there's no distinction. We could of course remember where each device came from and mark them as such, but is there something about the distinction that makes this important?

**Comment by l3d00m** [comment]
I think it makes sense to hide the devices when it is used as a swarm sync (like it is in this case). The important point is that it's confusing to see the devices list because it's irrelevant info for the normal user in this case. I would prefer to have them at least at the bottom of the devices.  
This depends on the usuage of the Introducer mode (swarm or not) though.

**Comment by calmh** [comment]
I'm unconvinced about this one, sorry. Hiding the devices completely is not something I want, and the sorting is subjective. There's another ticket on sorting devices based on their current state for example, which would conflict with this one.

**Comment by l3d00m** [comment]
Okay, Thank you for considering this anyway (and thank you for this great tool!).
