### ISSUE TITLE
Add top level Hash field to FileInfo

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2660]
We should have a file-total Hash field directly on the FileInfo structures. This has a couple of use cases:
- It enables comparison of two files to determine if they are identical without loading and walking the entire block list (assuming the hash is secure).
- It can be kept also for deleted files, thus indicating what the contents were of the file that was deleted. This could be used as input to smarter conflict detection around deletes.
- It could (at some point, in the future) be used as a one level Merkle tree, in that we we wouldn't need to send the full block list in the index exchange. The device could then instead ask for the block list for files that have unknown top level hashes.

The top level hash should not be a straight hash of the file contents, it should be a hash of the block hashes. This enables recomputing it quickly when only a few blocks have changed.

Assuming we have configurable hash algorithms, should this follow the configured hash algorithm or always be SHA256? I'm leaning towards the latter as it makes things simpler if we can assume the hash is secure, and the cost is negligible anyway.

**Comment by AudriusButkevicius** [comment]
Well a secure hash over insecure hashes doesn't make it secure.

**Comment by calmh** [comment]
That depends... Even with an insecure hash like Murmur3 we assume that it's secure *enough* that for a given block at a given offset in a given file the same hash implies the same data. If we don't feel we can assume even that, we can't use that hash algo.
