### ISSUE TITLE
Old wording in Add Device -> Device ID 

### ISSUE THREAD

**Issue by cwaffles** [syncthing/syncthing#2662]
When clicking the "add device" button in the web ui, the Device ID section says the following:
The device ID to enter here can be found in the "Edit > Show ID" dialog on the other device. 
![add device](https://cloud.githubusercontent.com/assets/3838856/12110577/77cb450e-b342-11e5-81f0-832646765e59.png)

However, there is no "Edit" menu, only an action menu. Perhaps this needs to be updated in the translations as well.

**Comment by calmh** [comment]
Indeed
