### ISSUE TITLE
Footer is ugly in narrow windows with not a lot of folder/devices

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2663]
Pull request #2620 broke the layout a bit when the view gets narrow enough to cause the switch to non-fixed footer. We go from this (nice):

![screen shot 2016-01-05 at 09 30 00](https://cloud.githubusercontent.com/assets/125426/12110661/ee2a11c0-b38e-11e5-9a5d-fd61b2048b35.png)

to this (ugly):

![screen shot 2016-01-05 at 09 30 05](https://cloud.githubusercontent.com/assets/125426/12110666/f3e51772-b38e-11e5-8f12-fdd13543fc5f.png)

**Comment by calmh** [comment]
(@andersonvom any ideas? :)

**Comment by NYPD** [comment]
Random idea, but maybe adding:

`
  display: inline-block; 
  float: none;
`

to the `<li>` in the footer  and

` text-align: center;`

to the `<ul>`

Would center things out and not make it look bad.

![maybe](https://cloud.githubusercontent.com/assets/6412879/12127098/42415b40-b3c3-11e5-8b4d-129aee7fb298.PNG)

Maybe only doing this when the screen reaches a certain size using a `@media` css rule.

**Comment by calmh** [comment]
That's certainly something. But to clarify, what I refer to as ugly here is that the entire bar is some ways up into the window and not at the bottom, as the browser window is taller than the page is long.

**Comment by NYPD** [comment]
Ah ok, I understand now. Then I think there are 3 things needed to remove the ugly:

1. `position: relative; min-height: 100%;` to the `<html>` 
2. remove `padding-bottom: 0` from the `<body>` in overrides.css line 250
3. Either change `position: static;` to `position: absolute;` from the `.nav-fixed-bottom` in overrides.css line 253 or removing it completely (Not sure what the intention desired is on small screens is) 

![eh](https://cloud.githubusercontent.com/assets/6412879/12151547/b67f62c6-b47d-11e5-9249-f69552289ce2.PNG)
