### ISSUE TITLE
Remove RelayWithoutGlobalAnn option (making it always true)

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2665]
I argued for introducing this option as I didn't think having relaying enabled without global discovery made sense, but we still needed a way to enable it for when it did make sense... Which should have been a strong signal that I was wrong. Now that we expose relaying and global discovery both in the settings interface, it makes sense for privacy conscious users to disable global discovery and change the relaying server to something they themselves control. This should work out of the box.

If a user disables global discovery but not relaying and uses the default relay setting, then they won't get relay connections as the devices can't find each other (as they disabled global discovery). This is a natural result of disabling global discovery I think.

@AudriusButkevicius opinion?

**Comment by AudriusButkevicius** [comment]
So your title of always being true is misleading?
In my comnection refactor mess, relays becomes such a listen or connect address, so all of this is more or less obsolete.

**Comment by calmh** [comment]
What I intend is to always run relaying if relaying is enabled, regardless of the status of global discovery. That means RelayWithoutGlobalAnn=true I think.

**Comment by AudriusButkevicius** [comment]
Yeah I am fine with that.
