### ISSUE TITLE
Allow for secure file deletion/Move files to system recycle bin if available

### ISSUE THREAD

**Issue by kcrkor** [syncthing/syncthing#2666]
Syncthing just deletes files. In order to remove all the leftover bits, it would be necessary to wipe the free space of the disk as it is difficult to find the file and wipe it specifically, which results in large volume of unnecessary writes. A definitive enhancement would be to either:

1. Allow for an option that enables some sort of secure file deletion mechanism that's built into syncthing

2. Implement an option to just move the file out to the system recycle bin (if available as discussed [here](https://forum.syncthing.net/t/deleted-files-by-mistake-can-they-be-recovered/5638)) or a specific "Trash" folder that needs to be set on systems where this isn't available and let another program handle the deletion

**Comment by canton7** [comment]
Do none of the [file versioning](http://docs.syncthing.net/users/versioning.html) schemes do what you need?

**Comment by AudriusButkevicius** [comment]
#1 i think is out of scope of syncthing, as secure has different meanings for different people.

#2 is already sort of there, called versioning. You can also implement your own external versioner which does both #1 and #2

**Comment by calmh** [comment]
Agreed in point one. For point two, I could actually imagine refactoring the existing "Trashcan" versioning to actually use the system trashcan on Windows and Mac and retain the current behavior on Linux.

**Comment by canton7** [comment]
> For point two, I could actually imagine refactoring the existing "Trashcan" versioning to use the system trashcan on Windows and Mac and retain the current behavior on Linux.

:+1:. The Windows Recycle Bin has some nice features, such as a flat view of deleted files along with a record of what folder they were deleted from.

However attempting to delete a path longer than the path length limit will bring you only pain and suffering (and a failed winapi call).

**Comment by calmh** [comment]
Question is the amount of work required to accomplish this. On Mac, you can get away with a simple rename of the file into the ~/.Trash folder. That doesn't give you the "Put Back" command later for the file, but it works otherwise. If we need magic DLL calls to trash stuff on Windows it may be more work than it's worth...

**Comment by canton7** [comment]
It's a [pretty straightforward API call](https://github.com/canton7/SyncTrayzor/blob/develop/src/SyncTrayzor/Utils/RecycleBinDeleter.cs#L106).

**Comment by calmh** [comment]
In C#, yeah. :) In Go we'll need to load the DLL, define and fill out a https://msdn.microsoft.com/en-us/library/windows/desktop/bb759795(v=vs.85).aspx (taking care to convert file names to utf16 and crap like that), look up the method manually and call it through a proxy, ... And then apparently ideally use the IFileOperation interface instead on Vista and newer. But I'll leave all those details to someone who runs Windows, All I'm saying is it's probably not super trivial. :)

**Comment by kluppy** [comment]
I don't understand how moving a file to the system recycle bin is secure but I would suggest using the external command file versioning if you really want to securely delete files.
For windows point the command to Secure Delete and let it run. https://technet.microsoft.com/en-us/sysinternals/bb897443

There are a number of UNIX tools to accomplish this.

In terms of Syncthing scope, is "securely" deleting files something that it shouldn't do?
Most programs just overwrite the file with 0s or random data between 1 and 35 times. This doesn't sound like something that is difficult.

**Comment by calmh** [comment]
It's not difficult. It's also not secure. If you're on an SSD, or using a filesystem like ZFS, nothing was overwritten (new blocks were allocated). The discussion about the recycle bin is because the subject mentions two different things. As such, this is issue is a bit muddled. Closing, but someone can reopen one for the recycle bin stuff if there isn't one already, that seems like something we could do.
