### ISSUE TITLE
Web UI has no logout.

### ISSUE THREAD

**Issue by dhs-rec** [syncthing/syncthing#2669]
When GUI auth is enabled, one needs to login with the configured username/password, but there's no way to logout again (except closing the browser).

**Comment by canton7** [comment]
Not entirely sure where we'd redirect the user on logout. We use basic auth, not a login screen, so there's no page we can send them to where they won't immediately be given another login prompt.

**Comment by kozec** [comment]
AFAIK, you can't logout from http basic auth. Your browser will keep sending same name and password user closes window or until server sends another HTTP/401.

**Comment by calmh** [comment]
That's actually true as far as I know as well. It's possible something could be hacked but I suspect it's too much effort for what it gains us.
