### ISSUE TITLE
Should warn about multiple folders with same path, nested folder paths

### ISSUE THREAD

**Issue by ctheune** [syncthing/syncthing#2672]
We had an issue where accidentally incorrectly configured syncs caused mayhem and I'd like to discuss whether we can protect against this somehow.

We have two folders that are synced - let's call them "Team" and "Management".

On my machine I place those folders this way:

/sync/Team
/sync/Management

This works fine.

However, I configured a new machine and accidentally set it up that both syncs ended up in 

/sync

This caused all content of both folders to end up everywhere. Syncing two different syncs onto the same path seems a rather peculiar configuration and I think this should be either prohibited or require explicit agreement.

This might also be the case if one sync is in a subfolder of another sync.

(Extracted from #1167)

**Comment by AudriusButkevicius** [comment]
I don't think we should handle this any way specially, as there are genuine cases where you'd want the folder to point at the same path (or subdir of an existing folder).

For example having a master and non-master to have multiple rw and multiple ro peers.

A warning is possible (and could be done in JS land, as we have all the paths) but I don't think we should ask for explicit permission.

**Comment by ctheune** [comment]
As long as I can see the warning _before_ hitting save, I'll be fine. :)

**Comment by calmh** [comment]
Yeah, I think a "Whoa, wait a minute, are you sure you want to do this?" somewhere along the way is appropriate here.

**Comment by ctheune** [comment]
Yeah, that would be great!

**Comment by AudriusButkevicius** [comment]
Well a red field validation warning is what I am thinking about

**Comment by calmh** [comment]
Sounds good enough to me.

**Comment by ctheune** [comment]
Happy with that, too!

**Comment by kluppy** [comment]
Dup #1960
