### ISSUE TITLE
Android Syncthing Dropdown Notification Removal

### ISSUE THREAD

**Issue by nrm21** [syncthing/syncthing#2674]
Every time ST is running in Android I have a notification in my dropdown saying "Syncthing is running".  Normally i can swipe away these messages but this one can't be swiped away.  Can we change that behavior or allow the hiding of the notification all together, as I don't need to know every second of the day that ST is running... I kinda already know it's running when Wifi is on.  ;)

Using a Galaxy Note 4 if it matters.

**Comment by calmh** [comment]
Should this have been filed on https://github.com/syncthing/syncthing-android/issues ?

**Comment by ThomasdenH** [comment]
I'm pretty sure it's already hideable by selecting notification type 'none' or something similar.

**Comment by canton7** [comment]
While this issue belongs in the syncthing-android repo, my understanding is that you can't reliably keep a process running in the background on Android without putting a permanent entry thing in the notification list.

**Comment by nrm21** [comment]
OH yes my bad... should have been in the other repo's issues list.  Sorry.
