### ISSUE TITLE
Empty files generating after deletion

### ISSUE THREAD

**Issue by lupa18** [syncthing/syncthing#2675]
Env (3 repos): 
* Desktop version: v0.12.11, Linux (64 bit)
* Desktop version 2: idem
*  Mobile version: 0.7.5

When I delete files from desktop, then they appear again, but empty. For example, I had deleted some image files, and then:

![empty_files](https://cloud.githubusercontent.com/assets/463429/12207285/772a072c-b624-11e5-95d5-e1a6dde79bf0.jpg)

Repos are configured like this:

![config](https://cloud.githubusercontent.com/assets/463429/12207377/07391b1e-b625-11e5-8a72-11c3a2f9bf9c.jpg)

Tanks in advance !!

**Comment by AudriusButkevicius** [comment]
You need to provide steps of reproduction. Also, is there anything in the log?

**Comment by calmh** [comment]
And are you sure it's not something on the mobile that actually recreates the files when they get deleted?

**Comment by shackra** [comment]
I'm experiencing this as well. I'm attaching the logs of Syncthing on my system: [syncthing.txt](https://github.com/syncthing/syncthing/files/85123/syncthing.txt)

I see this happening when my phone and laptop starts syncing.

**Comment by AudriusButkevicius** [comment]
In your case it's most likely caused by ignore files.

**Comment by shackra** [comment]
I don't understand as I don't black list any file in my default (jorge/Sync) directory 

El 10 de enero de 2016 13:03:14 CST, Audrius Butkevicius <notifications@github.com> escribió:
>In your case it's most likely caused by ignore files.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/syncthing/syncthing/issues/2675#issuecomment-170382264

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lupa18** [comment]
I'm not sure how to read and understand the log. 

It seems to be mobile version since I deactivated and let only 2 desktop versions running and error don't appear again. 

To reproduce it, 
1) let 3 instances run, 2 desktop and 1 mobile
2) Share your camera folder
3) Take some photos
4) Go to desktop and delete some photos

The result will be the re-creation of these photo files but without content, ie. with 0Kb

**Comment by calmh** [comment]
Yes, but all you're showing is that something recreates the deleted files. Seeing as we don't have this behavior in general, my suspicion falls on the camera app or something that may not like the files suddenly disappearing underneath it.

**Comment by AudriusButkevicius** [comment]
Or trying to modify metadata as the file gets nuked from under its feet.

**Comment by shackra** [comment]
In my case I'm quite sure I'm not running any app on my phone that may recreate deleted files on my phone's Sync directory

**Comment by calmh** [comment]
@shackra's log is weird:

```
ene 10 12:35:28 abril.charola syncthing[16436]: [NKHS2] INFO: Puller (folder "default", file "frio.mp4"): shortcut: unable to stat file: stat /home/jorge/Sync/frio.mp4: no such file or directory
ene 10 12:35:28 abril.charola syncthing[16436]: [NKHS2] INFO: Puller: shortcut: stat /home/jorge/Sync/frio.mp4: no such file or directory
```

I've not seen that failure mode before. We think we just need to do a metadata update on the file, but the file has disappeared. Not sure what's going on here.

**Comment by AudriusButkevicius** [comment]
Well a rescan should fix thid right?

**Comment by calmh** [comment]
It should, but it still means that the file was deleted on one side and updated on the other, simultaneously, without us noticing the delete yet? Weird.

**Comment by AudriusButkevicius** [comment]
Well we don't rescan at the point we start pulling the file, so I think this is not weird at all?

**Comment by calmh** [comment]
We do, if it exists in the database from before, don't we? And this still means a simultaneous delete on one side + metadata update on the other which seems unusual given both of these devices are under the control of the same person?

**Comment by AudriusButkevicius** [comment]
Unusual, but not impossible.

**Comment by AudriusButkevicius** [comment]
I'd say dup of #1263

**Comment by lupa18** [comment]
Confirmed, this occurs when I run Syncthing android client v. 0.75
