### ISSUE TITLE
Local connections do not work

### ISSUE THREAD

**Issue by isdn** [syncthing/syncthing#2685]
Hello.

Some of my devices are in a local network and have IPs in 192.168.XX.XX. All devices are connected to a router. When I launch syncthing, I receive the following in the log (I replaced the address/id with X):

[GXCII] 2016/01/11 20:02:03.311647 connections_tcp.go:43: DEBUG: dial tcp 46.226.XX.XX:22000: getsockopt: connection refused
[GXCII] 2016/01/11 20:02:03.311960 connections.go:375: DEBUG: dial failed XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX tcp://46.226.XX.XX:22000 dial tcp 46.226.XX.XX:22000: getsockopt: connection refused

I.e. it tries to access my router's external IP (46.226.XX.XX) instead of local IP in 192.168.XX.XX.

Local discovery/announce is enabled in config.
Local connections worked fine in v.0.11.

**Comment by Stebalien** [comment]
The discovery port was changed from 21025 to 21027 in v0.12,.You likely need to update your firewall rules (http://docs.syncthing.net/users/firewall.html#local-firewall)

**Comment by AudriusButkevicius** [comment]
If you have more questions, shout out on the forum.

**Comment by isdn** [comment]
Well, the firewall rules allow all connections for addresses in my local network.
I even tried to disable firewall at all, but got the same results.

[GXCII] 2016/01/11 21:26:36.839604 cache.go:107: DEBUG: lookup for XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX at IPv4 local
[GXCII] 2016/01/11 21:26:36.839631 cache.go:108: DEBUG:   direct: []
[GXCII] 2016/01/11 21:26:36.839645 cache.go:109: DEBUG:   relays: []
[GXCII] 2016/01/11 21:26:36.839778 cache.go:107: DEBUG: lookup for XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX at IPv6 local
[GXCII] 2016/01/11 21:26:36.839800 cache.go:108: DEBUG:   direct: []
[GXCII] 2016/01/11 21:26:36.839815 cache.go:109: DEBUG:   relays: []
[GXCII] 2016/01/11 21:26:36.839929 cache.go:136: DEBUG: lookup results for XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX
[GXCII] 2016/01/11 21:26:36.839949 cache.go:137: DEBUG:   direct:  [tcp://46.226.XX.XX:22000]
[GXCII] 2016/01/11 21:26:36.839961 cache.go:138: DEBUG:   relays:  []
[GXCII] 2016/01/11 21:26:36.840194 connections.go:372: DEBUG: dial XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX tcp://46.226.XX.XX:22000
[GXCII] 2016/01/11 21:26:37.985978 connections_tcp.go:40: DEBUG: dial tcp 46.226.XX.XX:22000: getsockopt: connection refused

**Comment by AudriusButkevicius** [comment]
Well local discovery is clearly not working in your environment. I suggest you check that both sides are 0.12, both sides have firewall rules allowing traffic to flow to the right UDP port, the router allows multicasts. 

You can also enable STTRACE=beacon or use wireshark to inspect that the packets are leaving your machine.

Again, this is a support issue related to your environment (until proven otherwise) so its best to exercise it on the forums as more people can chip in and help.

**Comment by isdn** [comment]
Ok, thanks.
