### ISSUE TITLE
Folder not syncing fully....

### ISSUE THREAD

**Issue by ChiziNist** [syncthing/syncthing#2686]
I have a folder on a windows 2012r2 (de-duplication enabled on the volume) the total folder size according to windows is 15GB with 32,477 files. 
![image](https://cloud.githubusercontent.com/assets/3219132/12242474/5bed916e-b867-11e5-9266-54fb65358707.png)

But Syncthing only sees 108 MB with 15,795 files
![image](https://cloud.githubusercontent.com/assets/3219132/12242503/841cf6e8-b867-11e5-9887-10518493c940.png)

There is nothing special about the folder or the files in it, mainly scripts & binaries. Syncthing runs under the local administrator account.

**Comment by AudriusButkevicius** [comment]
Deduplicated volumes don't work due to a bug in Go. Check go issue tracker for clues.

**Comment by calmh** [comment]
#1845
