### ISSUE TITLE
Sync not working whith high latency / gfw peers (eu<->china)?

### ISSUE THREAD

**Issue by mgcrea** [syncthing/syncthing#2691]
I've been playing with syncthing accross several dedicated servers in europe with no issues.

However I've just added a dedicated server located in China and I've successfully added the device and accepted the default folder sharing. But the folder state (on the chineese server) is stuck on `Up to Date` with `0 items, ~0 B` while on the other side (europe), the status for the chineese server is stuck on `Syncing (0%)`.

It's been 30 minutes so maybe it's a question of time... But I'm not seeing anything in the logs, is there a verbosity option?

```
[G7ASB] 13:27:42 INFO: Established secure connection to SEDK52S-XXX-XXX-XXX-XXX-XXX-XXX-AES5MAQ at 172.17.0.9:22000-122.144.179.33:59260 (direct-accept)
[G7ASB] 13:27:42 INFO: Device SEDK52S-XXX-XXX-XXX-XXX-XXX-XXX-AES5MAQ client is "syncthing v0.12.12" named "zh-xxxx"
```

**Comment by calmh** [comment]
There are many verbosity options. :) It sounds like traffic isn't flowing at all, or else you have a misconfiguration (shared folder mismatch for example). Try `STTRACE=protocol` for lots of info on all data sent/received. It won't be humanly understandable, but it will show if any traffic flows at all.

**Comment by mgcrea** [comment]
@calmh, it took time to start but the sync actually ended up working. Thanks for the debugging options ;-).
