### ISSUE TITLE
fatal error: runtime: cannot map pages in arena address space                                                               

### ISSUE THREAD

**Issue by wolf2k1** [syncthing/syncthing#2693]
Launching on Seagate Central.
Compiling from source 
options
env GOOS=linux GOARCH=arm GOARM=6 go build -ldflags "-R 65536" -v ./cmd/syncthing
How i can compiling source for this platform?

My host os - debian 7 - 386
Target (seagate central)
Linux 2.6.35.13-cavm1.whitney-econa.whitney-econa #1 Wed Sep 16 15:47:59 PDT 2015 armv6l
Panic log
-----------------------------------------------------------------------------------------
[VTV7A] 10:47:47 INFO: syncthing unknown-dev "Copper Cockroach" (go1.5.2 linux-arm) unknown@unknown 1970-01-01 00:00:00 UTC
[VTV7A] 10:47:47 INFO: My ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[VTV7A] 10:47:47 INFO: Single thread hash performance is ~4.0 MB/s
...
Panic at 2016-01-13T10:47:47+03:00
fatal error: runtime: cannot map pages in arena address space

runtime stack:
runtime.throw(0x6a7958, 0x30)
        /root/go/src/runtime/panic.go:527 +0x78
runtime.sysMap(0xb01000, 0x1000, 0x11100001, 0xa353b0)
        /root/go/src/runtime/mem_linux.go:217 +0x180
runtime.mHeap_MapSpans(0xa23058, 0x11500000)
        /root/go/src/runtime/mheap.go:314 +0xc8
runtime.mHeap_SysAlloc(0xa23058, 0x400000, 0x1)
        /root/go/src/runtime/malloc.go:428 +0x198
runtime.mHeap_Grow(0xa23058, 0x200, 0x0)
        /root/go/src/runtime/mheap.go:628 +0x68
runtime.mHeap_AllocSpanLocked(0xa23058, 0x200, 0x0)
        /root/go/src/runtime/mheap.go:532 +0x6c8
runtime.mHeap_Alloc_m(0xa23058, 0x200, 0x0, 0x1, 0x1)
        /root/go/src/runtime/mheap.go:425 +0x23c
runtime.mHeap_Alloc.func1()
        /root/go/src/runtime/mheap.go:484 +0x40
runtime.systemstack(0x10c2df70)
        /root/go/src/runtime/asm_arm.s:256 +0xa8
runtime.mHeap_Alloc(0xa23058, 0x200, 0x0, 0x90101, 0xa29648)
        /root/go/src/runtime/mheap.go:485 +0x58
runtime.largeAlloc(0x400000, 0x1, 0x2d)
        /root/go/src/runtime/malloc.go:748 +0xb4
runtime.mallocgc.func3()
        /root/go/src/runtime/malloc.go:637 +0x34
runtime.systemstack(0x10c14a00)
        /root/go/src/runtime/asm_arm.s:242 +0x80
runtime.mstart()
        /root/go/src/runtime/proc1.go:668

goroutine 1 [running]:
runtime.systemstack_switch()
        /root/go/src/runtime/asm_arm.s:187 +0x4 fp=0x10d2ef2c sp=0x10d2ef28
runtime.mallocgc(0x400000, 0x4fd730, 0x1, 0x1)
        /root/go/src/runtime/malloc.go:638 +0x9e8 fp=0x10d2ef98 sp=0x10d2ef2c
runtime.newarray(0x4fd730, 0x400000, 0x48c108)
        /root/go/src/runtime/malloc.go:780 +0xe4 fp=0x10d2efb8 sp=0x10d2ef98
runtime.makeslice(0x4f3aa8, 0x0, 0x0, 0x400000, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/runtime/slice.go:32 +0x1d8 fp=0x10d2efe0 sp=0x10d2efb8
github.com/syndtr/goleveldb/leveldb/memdb.New(0x35669138, 0x10c0b0d8, 0x400000, 0x35669138)
        /root/src/github.com/syndtr/goleveldb/leveldb/memdb/memdb.go:466 +0xa8 fp=0x10d2f030 sp=0x10d2efe0
github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal(0x10f837a0, 0x0, 0x0)
        /root/src/github.com/syndtr/goleveldb/leveldb/db.go:507 +0x500 fp=0x10d2f298 sp=0x10d2f030
github.com/syndtr/goleveldb/leveldb.openDB(0x10f867e0, 0x0, 0x0, 0x0)
        /root/src/github.com/syndtr/goleveldb/leveldb/db.go:122 +0x914 fp=0x10d2f384 sp=0x10d2f298
github.com/syndtr/goleveldb/leveldb.Open(0x35668ed0, 0x10f97680, 0x11004210, 0x0, 0x0, 0x0)
        /root/src/github.com/syndtr/goleveldb/leveldb/db.go:194 +0x16c fp=0x10d2f3ac sp=0x10d2f384
github.com/syndtr/goleveldb/leveldb.OpenFile(0x10c12780, 0x2d, 0x11004210, 0x0, 0x0, 0x0)
        /root/src/github.com/syndtr/goleveldb/leveldb/db.go:216 +0x80 fp=0x10d2f3d8 sp=0x10d2f3ac
github.com/syncthing/syncthing/lib/db.Open(0x10c12780, 0x2d, 0x634880, 0x0, 0x0)
        /root/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:59 +0x298 fp=0x10d2f450 sp=0x10d2f3d8
main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x60200c, 0x1, 0x0, 0x0, ...)
        /root/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:640 +0x1098 fp=0x10d2fe64 sp=0x10d2f450
main.main()
        /root/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:362 +0x734 fp=0x10d2ff94 sp=0x10d2fe64
runtime.main()
        /root/go/src/runtime/proc.go:111 +0x2b4 fp=0x10d2ffbc sp=0x10d2ff94
runtime.goexit()
        /root/go/src/runtime/asm_arm.s:1036 +0x4 fp=0x10d2ffbc sp=0x10d2ffbc

goroutine 15 [runnable]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x11004370)
        /root/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:202
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
        /root/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x258

goroutine 12 [chan receive]:
main.setupSignalHandling.func2(0x10c3b980)
        /root/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:888 +0x2c
created by main.setupSignalHandling
        /root/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:890 +0x230

goroutine 8 [syscall]:
os/signal.loop()
        /root/go/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.1
        /root/go/src/os/signal/signal_unix.go:28 +0x30

goroutine 9 [chan receive]:
main.trackCPUUsage()
        /root/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0x108
created by main.init.3
        /root/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x24

goroutine 10 [select, locked to thread]:
runtime.gopark(0x710dec, 0x10c1878c, 0x60a1f8, 0x6, 0x7c618, 0x2)
        /root/go/src/runtime/proc.go:185 +0x148
runtime.selectgoImpl(0x10c1878c, 0x0, 0xc)
        /root/go/src/runtime/select.go:392 +0x14d4
runtime.selectgo(0x10c1878c)
        /root/go/src/runtime/select.go:212 +0x10
runtime.ensureSigM.func1()
        /root/go/src/runtime/signal1_unix.go:227 +0x428
runtime.goexit()
        /root/go/src/runtime/asm_arm.s:1036 +0x4

goroutine 11 [chan receive]:
main.setupSignalHandling.func1(0x10c3b880)
        /root/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:878 +0x2c
created by main.setupSignalHandling
        /root/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:880 +0x104

goroutine 13 [select]:
github.com/thejerf/suture.(*Supervisor).Serve(0x10c0d830)
        /root/src/github.com/thejerf/suture/suture.go:441 +0xdb4
created by github.com/thejerf/suture.(*Supervisor).ServeBackground
        /root/src/github.com/thejerf/suture/suture.go:400 +0x2c

goroutine 14 [select]:
github.com/syncthing/syncthing/lib/events.(*Subscription).Poll(0x10c11f90, 0xf8475800, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/src/github.com/syncthing/syncthing/lib/events/events.go:210 +0x3b0
github.com/syncthing/syncthing/lib/events.(*BufferedSubscription).pollingLoop(0x10c12b40)
        /root/src/github.com/syncthing/syncthing/lib/events/events.go:252 +0x38
created by github.com/syncthing/syncthing/lib/events.NewBufferedSubscription
        /root/src/github.com/syncthing/syncthing/lib/events/events.go:246 +0x268

**Comment by AudriusButkevicius** [comment]
Specifying -R is not enough to make it work with non 4k page sizes. You need to modify go's source code in a few other places. Check the forum, there was a writeup by someone.
