### ISSUE TITLE
Seagate central  kernel: internal error: Oops: 17                                                  

### ISSUE THREAD

**Issue by wolf2k1** [syncthing/syncthing#2695]
Running on seagate central.
Compiling with options 
env GOOS=linux GOARCH=arm GOARM=6  go build -ldflags "-R 65536" -v ./cmd/syncthing
if not change _PhysPageSize = 65536- get fatal error: runtime: cannot map pages in arena address space
After change - kernel error and not working gui

------------------------
[WPV5T] 11:32:32 INFO: Single thread hash performance is ~4.0 MB/s
[WPV5T] 11:32:32 INFO: Error loading config file; using defaults for now
[WPV5T] 11:32:32 INFO: Default folder created and/or linked to new config
[WPV5T] 11:32:32 INFO: Defaults saved. Edit /Data/user/.config/syncthing/config.xml to taste or use the GUI
[WPV5T] 11:32:32 VERBOSE: Starting up (/Data/user/.config/syncthing)
[WPV5T] 11:32:32 VERBOSE: Configuration was saved
[WPV5T] 11:32:32 INFO: Starting deadlock detector with 20m0s timeout
[WPV5T] 11:32:32 OK: Ready to synchronize default (read-write)
[WPV5T] 11:32:32 INFO: Using discovery server https://discovery-v4-1.syncthing.net/?id=SR7AARM-TCBUZ5O-VFAXY4D-CECGSDE-3Q6IZ4G-XG7AH75-OBIXJQV-QJ6NLQA
[WPV5T] 11:32:32 INFO: Using discovery server https://discovery-v4-2.syncthing.net/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[WPV5T] 11:32:32 INFO: Using discovery server https://discovery-v4-3.syncthing.net/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[WPV5T] 11:32:32 INFO: Using discovery server https://discovery-v6-1.syncthing.net/?id=SR7AARM-TCBUZ5O-VFAXY4D-CECGSDE-3Q6IZ4G-XG7AH75-OBIXJQV-QJ6NLQA
[WPV5T] 11:32:32 INFO: Using discovery server https://discovery-v6-2.syncthing.net/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[WPV5T] 11:32:32 INFO: Using discovery server https://discovery-v6-3.syncthing.net/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[WPV5T] 11:32:32 VERBOSE: Folder "default" is now scanning
[WPV5T] 11:32:32 INFO: Completed initial scan (rw) of folder default
[WPV5T] 11:32:32 VERBOSE: Folder "default" is now idle
[WPV5T] 11:32:33 INFO: Loading HTTPS certificate: open /Data/user/.config/syncthing/https-cert.pem: no such file or directory
[WPV5T] 11:32:33 INFO: Creating new HTTPS certificate
[WPV5T] 11:32:42 VERBOSE: Relay state changed; connected relay(s) are relay://91.214.169.69:22070/?id=L7CQN6F-ZIOI4FH-QXWQ2PZ-B5RK5PD-LIAOSZ5-5RBMQQ4-JLLD77X-TTF62AE&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=0&statusAddr=:22081&providedBy=ilian.
[WPV5T] 11:32:42 INFO: New UPnP port mapping: external port 62110 to local port 35353.
[WPV5T] 11:32:42 VERBOSE: External port mapping changed; new port is 62110.
[WPV5T] 11:32:57 INFO: Device WPV5TVX-OZDDUVL-ITJCDO2-T46UL2H-GSF5OL2-RY254ZY-WVMEUXD-6XP6MQN is "hdd-tula" at [dynamic]
[WPV5T] 11:32:57 INFO: No automatic upgrades; unknown-dev is not a release version.
[WPV5T] 11:32:57 VERBOSE: Startup complete

Message from syslogd@hdd-tula at Thu Jan 14 11:32:57 2016 ...
hdd-tula kernel: [ 7559.480000] Internal error: Oops: 17 [#17]

Message from syslogd@hdd-tula at Thu Jan 14 11:32:57 2016 ...
hdd-tula kernel: [ 7559.480000] last sysfs file: /sys/fs/ext4/dm-0/lifetime_write_kbytes

Message from syslogd@hdd-tula at Thu Jan 14 11:32:57 2016 ...
hdd-tula kernel: [ 7559.480000] Process syncthing (pid: 4135, stack limit = 0xaad4c268)

Message from syslogd@hdd-tula at Thu Jan 14 11:32:57 2016 ...
hdd-tula kernel: [ 7559.480000] Stack: (0xaad4df48 to 0xaad4e000)

Message from syslogd@hdd-tula at Thu Jan 14 11:32:57 2016 ...
hdd-tula kernel: [ 7559.480000] df40:                   a8bdc060 00000000 00000000 0000000a 8000201d 00000000

Message from syslogd@hdd-tula at Thu Jan 14 11:32:57 2016 ...
hdd-tula kernel: [ 7559.480000] df60: 3566ec58 00000000 00000000 a01029c4 00000000 00000001 aad4dfa4 00000000

Message from syslogd@hdd-tula at Thu Jan 14 11:32:57 2016 ...
hdd-tula kernel: [ 7559.480000] df80: 00000000 00000000 0000016e a0051168 aad4c000 00000000 00000000 aad4dfa8

Message from syslogd@hdd-tula at Thu Jan 14 11:32:57 2016 ...
hdd-tula kernel: [ 7559.480000] dfa0: a0050fc0 a00f3734 00000000 00000000 0000000a 1135dd08 1135dd04 00080800

Message from syslogd@hdd-tula at Thu Jan 14 11:32:57 2016 ...
hdd-tula kernel: [ 7559.480000] dfc0: 00000000 00000000 00000000 0000016e 00000072 00000000 110d27e0 00a27ecc

Message from syslogd@hdd-tula at Thu Jan 14 11:32:57 2016 ...
hdd-tula kernel: [ 7559.480000] dfe0: 10d4305d 1135dcb4 000ab6c8 00158640 60000010 0000000a 00000000 00000000

Message from syslogd@hdd-tula at Thu Jan 14 11:32:57 2016 ...
hdd-tula kernel: [ 7559.480000] Code: e1a0a000 e1a00007 ebff79db e59f3170 (e5902078)
[WPV5T] 11:32:58 INFO: API listening on 127.0.0.1:47138
[WPV5T] 11:32:58 INFO: GUI URL is http://127.0.0.1:47138/

Message from syslogd@hdd-tula at Thu Jan 14 11:32:58 2016 ...
hdd-tula kernel: [ 7559.830000] last sysfs file: /sys/fs/ext4/dm-0/lifetime_write_kbytes

Message from syslogd@hdd-tula at Thu Jan 14 11:32:58 2016 ...
hdd-tula kernel: [ 7559.830000] Internal error: Oops: 17 [#18]

Message from syslogd@hdd-tula at Thu Jan 14 11:32:58 2016 ...
hdd-tula kernel: [ 7559.830000] Process syncthing (pid: 4127, stack limit = 0xaf10c268)

Message from syslogd@hdd-tula at Thu Jan 14 11:32:58 2016 ...
hdd-tula kernel: [ 7559.830000] Stack: (0xaf10df48 to 0xaf10e000)

Message from syslogd@hdd-tula at Thu Jan 14 11:32:58 2016 ...
hdd-tula kernel: [ 7559.830000] df40:                   00171234 00000000 af10df84 af10df60 a0088ec4 a005bf7c

Message from syslogd@hdd-tula at Thu Jan 14 11:32:58 2016 ...
hdd-tula kernel: [ 7559.830000] df60: 10d52c08 00000022 10c10120 00000107 00000000 00000001 00000008 00000000

Message from syslogd@hdd-tula at Thu Jan 14 11:32:58 2016 ...
hdd-tula kernel: [ 7559.830000] df80: 00000000 00000000 0000016e a0051168 af10c000 00000000 00000000 af10dfa8

Message from syslogd@hdd-tula at Thu Jan 14 11:32:58 2016 ...
hdd-tula kernel: [ 7559.830000] dfa0: a0050fc0 a00f3734 00000000 00000000 00000008 10d529c0 10d529bc 00080800

Message from syslogd@hdd-tula at Thu Jan 14 11:32:58 2016 ...
hdd-tula kernel: [ 7559.830000] dfc0: 00000000 00000000 00000000 0000016e 00000072 00000000 10d5ce00 00a27ecc

Message from syslogd@hdd-tula at Thu Jan 14 11:32:58 2016 ...
hdd-tula kernel: [ 7559.830000] dfe0: 10c0fbdd 10d5296c 000ab6c8 00158640 60000010 00000008 00000000 00000000

Message from syslogd@hdd-tula at Thu Jan 14 11:32:58 2016 ...
hdd-tula kernel: [ 7559.830000] Code: e1a0a000 e1a00007 ebff79db e59f3170 (e5902078)

**Comment by AudriusButkevicius** [comment]
Sorry, but its your kernel problem.
