### ISSUE TITLE
capital problem sync with multi-OS (windows - linux)

### ISSUE THREAD

**Issue by doodoori2** [syncthing/syncthing#2700]
1. make a file 'aaa' in windows (machine A)
2. sync the file 'aaa' to linux (machine B) 
3. remove 'aaa' and make 'AAA' in windows (machine A)
4. there are 'aaa' and 'AAA' both exist in linux. (why?) (machine B) 
5. remove 'aaa' in linux (machine B). because aaa is changed to AAA
6. 'AAA' is also automatically remove in linux (machine B), I didn't remove 'AAA'. but remove 'aaa'.

**Comment by calmh** [comment]
Yep

**Comment by calmh** [comment]
Duo of #1787
