### ISSUE TITLE
Add Icons for Master Folder

### ISSUE THREAD

**Issue by mike2003** [syncthing/syncthing#2703]
I think that there is not enough information. I want to know exactly what are the MASTER folder for other devices. Otherwise, I see a monotonous list and nothing is clear.
![Image](http://i.imgur.com/bUKpEMu.jpg)
http://i.imgur.com/bUKpEMu.jpg

**Comment by calmh** [comment]
Reasonable idea.

**Comment by kralo** [comment]
I would go for an icon on the left, because it has to do with the folder, not the sync status
![go-readonly-icon](https://cloud.githubusercontent.com/assets/3055678/13374519/2235683a-dd87-11e5-9068-a8ee856d9a85.png)
