### ISSUE TITLE
Do not require restart when accepting/rejecting request for sharing usage data

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing#2704]
Syncthing v0.12.14, OSX

When accepting or reject the request to share usage data, the user gets greeted with a 'please restart' dialog. This should be a bit more streamlined (maybe simply ignore the fact that we need to restart?)

**Comment by AudriusButkevicius** [comment]
I could say the same thing about progressEmitter interval.
We already handle changing that at runtime, yet it asks for a restart.

**Comment by calmh** [comment]
What is it that triggers the "restart needed" exactly? If I remember correctly the usage data thing actually starts and stops just fine without restart. `STTRACE=config` while doing the change should clarify that

**Comment by calmh** [comment]
```
MSYN5] 2016/01/18 09:47:38.830998 gui.go:267: INFO: API listening on 127.0.0.1:8384
[MSYN5] 2016/01/18 09:47:38.831014 gui.go:268: INFO: GUI URL is http://127.0.0.1:8384/
[MSYN5] 2016/01/18 09:47:41.964636 wrapper.go:145: DEBUG: ProgressEmitter@0xc820484100 verifying configuration
[MSYN5] 2016/01/18 09:47:41.964672 wrapper.go:145: DEBUG: model@0xc820076000 verifying configuration
[MSYN5] 2016/01/18 09:47:41.964682 wrapper.go:145: DEBUG: Service verifying configuration
[MSYN5] 2016/01/18 09:47:41.964695 wrapper.go:145: DEBUG: apiService@0xc82006cf70 verifying configuration
[MSYN5] 2016/01/18 09:47:41.964701 wrapper.go:145: DEBUG: connectionService verifying configuration
[MSYN5] 2016/01/18 09:47:41.964708 wrapper.go:145: DEBUG: usageReportingManager@0xc82017c640 verifying configuration
[MSYN5] 2016/01/18 09:47:41.964725 wrapper.go:145: DEBUG: embeddedStatic@0xc8204601e0 verifying configuration
[MSYN5] 2016/01/18 09:47:41.964735 wrapper.go:156: DEBUG: ProgressEmitter@0xc820484100 committing configuration
[MSYN5] 2016/01/18 09:47:41.964747 wrapper.go:156: DEBUG: model@0xc820076000 committing configuration
[MSYN5] 2016/01/18 09:47:41.964781 wrapper.go:159: DEBUG: model@0xc820076000 requires restart
[MSYN5] 2016/01/18 09:47:41.964789 wrapper.go:156: DEBUG: Service committing configuration
[MSYN5] 2016/01/18 09:47:41.964805 wrapper.go:156: DEBUG: apiService@0xc82006cf70 committing configuration
[MSYN5] 2016/01/18 09:47:41.964817 wrapper.go:156: DEBUG: connectionService committing configuration
[MSYN5] 2016/01/18 09:47:41.964831 wrapper.go:156: DEBUG: usageReportingManager@0xc82017c640 committing configuration
[MSYN5] 2016/01/18 09:47:41.964868 wrapper.go:156: DEBUG: embeddedStatic@0xc8204601e0 committing configuration
[MSYN5] 2016/01/18 09:47:41.964948 usage_report.go:256: INFO: Starting usage reporting
```

This looks like a bug to me: `model@0xc820076000 requires restart`

**Comment by calmh** [comment]
(Also, the thing just calling itself "Service" could be a bit more specific :D)

**Comment by calmh** [comment]
It forces a restart if any of the things in the OptionsConfiguration changes. It doesn't actually use most (any?) of those, so I think this is a remnant to protect other parts of the program that should react to changes there but don't...

**Comment by AudriusButkevicius** [comment]
Service is relay.Service

**Comment by calmh** [comment]
Making the model not require restarts for all options changes is trivial, but we then carefully need to go through other parts that may require restarting. For example it looks like the connection service needs to properly handle changes to the listen addresses, rate limiting etc which it doesn't, and so on for a bunch of options. 

I can fix this specific case by "white listing" a few options that we for sure should not look at.
