### ISSUE TITLE
invalid URL escape "%20" on Windows 7

### ISSUE THREAD

**Issue by kluppy** [syncthing/syncthing#2709]
Hi Guys

I am running Syncthing on one of my Windows 7 machines at work and it doesn't seem to connect to other devices as quickly as the linux machines. The log shows repeated messages like the following:

[VJR5V] 10:06:29 INFO: Failed to parse connection url: tcp://[fe80::cefa:ff:fef3:5fcc%25Wireless%20Network%20Connection]:22000 parse tcp://[fe80::cefa:ff:fef3:5fcc%25Wireless%20Network%20Connection]:22000: invalid URL escape "%20"

It also seems more likely to connect via a relay. Is there a reason the %20 is invalid?
Any info you would like posted from the logs?

Edit:
FYI,
[VJR5V] 09:18:12 INFO: syncthing v0.12.15 "Beryllium Bedbug" (go1.6beta2 windows-amd64) WIN-P6RP886TVDJ\Administrator@WIN-P6RP886TVDJ 2016-01-17 09:57:20 UTC

**Comment by calmh** [comment]
Doesn't feel like it ought to be invalid to me, needs investigation

**Comment by mbdevpl** [comment]
I'm consistently receiving the same errors in my cluster. It happens on Windows 7x64 machines, but the cluster as a whole is heterogeneous. Now it's with ST 0.12.15, but I first noticed it in some previous versions. Didn't think much about it because of its "INFO" status.

What can I do to help with the investigation?

**Comment by canton7** [comment]
Interestingly with 0.12.14 and 0.1.2.15, I see `[fe80::ec42:b11e:b6a0:97de%Wireless Network Connection]` (no escapes). That's on Windows 10. I wonder why you're getting extra escapes - given that '%' is the separator between address and scope, I wouldn't be hugely surprised if it was unparsable elsewhere.

**Comment by kluppy** [comment]
The whole string is percent escaped which is valid, I think it is required for URI which relys on it.

I am surprised the one on windows 10 isn't since it is a URL.

Could it be that it is double encoded and the error string is decoded before printing?

**Comment by AudriusButkevicius** [comment]
Also, you are not running an official build. 
Can you enable STTRACE=connections and work out the line number where this is coming from?

**Comment by canton7** [comment]
> Also, you are not running an official build. 

How did you figure that out? The first log line is identical to mine, and I'm definitely running an official build.

**Comment by kluppy** [comment]
Will do. The computer is at work at the moment so it will have to wait 12 hours.

Non-official build? I got it form the official page and use the internal update.

**Comment by AudriusButkevicius** [comment]
Ok, something must have changed, as we didn't build by P6RP886TVDJ\Administrator@WIN-P6RP886TVDJ

**Comment by canton7** [comment]
> I wonder why you're getting extra escapes - given that '%' is the separator between address and scope, I wouldn't be hugely surprised if it was unparsable elsewhere.

According to https://tools.ietf.org/html/rfc6874 section 2 the escaping is just fine - ignore me.

**Comment by canton7** [comment]
> Ok, something must have changed, as we didn't build by P6RP886TVDJ\Administrator@WIN-P6RP886TVDJ  

The windows builds have been built by that user for a fair while now - I think it coincided with a switch to building on AppVeyor? Not too sure though...

**Comment by mbdevpl** [comment]
Here's the log line in my case:
```
[12345] 2016/01/18 19:49:04.502166 connections.go:362: INFO: Failed to parse connection url: tcp://[1234::5678%25Wireless%20LAN]:22000 parse tcp://[1234::5678%25Wireless%20LAN]:22000: invalid URL escape "%20"
```
where I changed node ID prefix to `12345` and its IP to `1234::5678`. `Wireless LAN` is really what my wireless network is called on the Windows machine (i.e. I've changed it from the default). Anyway, the above log line occurs in case of connection attempt, and what immediately follows is a line that connection to some other node has failed.

This error seems to occur only with IPv6 - I get normal connections between the nodes over IPv4.

This is becoming interesting... I'll do some more tests :)

**Comment by canton7** [comment]
Looking at the code, the uri that's printed should be exactly the same as the one that's passed to `url.Parse`, so I think that disproves the double-escaping theory. `url.Parse` should handle the uri you gave above (at least the version that's used on the go playground...).

Try `STTRACE=discover`

**Comment by mbdevpl** [comment]
OK, I renamed the network on Windows machine to `WLAN` (no spaces now) and sometimes the IPv6 connection succeeds, sometimes it fails. However, in general it seems like it might be connecting faster... Or maybe my perception was biased by other postings ;)

Example log lines with connection success:
```
[12345] 2016/01/18 20:19:22.284132 connections.go:372: DEBUG: dial ABCDEF tcp://[1234::5678%25WLAN]:22000
[12345] 2016/01/18 20:19:22.964133 connections.go:291: DEBUG: Connecting to ABCDEF via tcp://[1234::5678%25WLAN]:22000 succeeded
[12345] 2016/01/18 20:19:22.964133 connections.go:270: DEBUG: Reconnect loop for ZXCVBN
[12345] 2016/01/18 20:19:22.964133 connections.go:309: DEBUG: Not connecting via relay false true false
[12345] 2016/01/18 20:19:22.964133 connections.go:233: INFO: Established secure connection to ABCDEF at [1234::abcd%WLAN]:1506-[1234::5678%WLAN]:22000 (direct-dial)
[12345] 2016/01/18 20:19:22.964133 connections.go:234: DEBUG: cipher suite: C02F in lan: false
[12345] 2016/01/18 20:19:22.969133 model.go:664: INFO: Device ABCDEF client is "syncthing v0.12.15" named "somedevice"
```
and example with failure:
```
[12345] 2016/01/18 20:24:23.671911 connections.go:372: DEBUG: dial ABCDEF tcp://[1234::5678%25WLAN]:22000
[12345] 2016/01/18 20:24:24.956985 connections_tcp.go:40: DEBUG: dial tcp [1234::5678%WLAN]:22000: connectex: No connection could be made because the target machine actively refused it.
[12345] 2016/01/18 20:24:24.956985 connections.go:375: DEBUG: dial failed ABCDEF tcp://[1234::5678%25WLAN]:22000 dial tcp [1234::5678%WLAN]:22000: connectex: No connection could be made because the target machine actively refused it.
[12345] 2016/01/18 20:24:24.956985 connections.go:300: DEBUG: Connecting to ABCDEF via tcp://[1234::5678%25WLAN]:22000 failed
```
where: `ABCDEF` is ID of the non-windows (connecting) node, `ZXCVBN` is of some other (completely offline) node, and `1234::abcd` is the windows (i.e. `12345`/current) machine IP

I've compared the logs and I also noticed that depending on IP version, when I close the other syncthing, the closure differs somehow... Over IPv4 the connections close somehow nicely, but only with network name changed to `WLAN`:
```
[12345] 2016/01/18 20:18:33.842060 model.go:756: INFO: Connection to ABCDEF closed: EOF
```

Wheras in case of IPv6 with any network name (with and without spaces), and in case of IPv4 with network name with spaces, the following happens:
```
[12345] 2016/01/18 20:24:16.188577 model.go:756: INFO: Connection to ABCDEF closed: read tcp [1234::abcd%WLAN]:2325->[1234::5678%WLAN]:22000: wsarecv: An existing connection was forcibly closed by the remote host.
```
and:
```
[12345] 2016/01/18 20:06:44.396902 model.go:756: INFO: Connection to ABCDEF closed: read tcp 192.168.0.14:60114->192.168.0.13:22000: wsarecv: An existing connection was forcibly closed by the remote host.
```

Please notice that the percent character (%), which is encoded in URLs via **%25**, is sometimes logged in its encoded form, while sometimes in not encoded form. I cannot check if it's the same case with space character, because the space character seems to be preventing IPv6 connections, so nothing else than failed connection information is logged.

I really hope this helps somehow ;)

**Comment by mbdevpl** [comment]
@canton7 will try `discover` now.

**Comment by canton7** [comment]
I think you're getting distracted by something else. The original error was `invalid URL escape "%20"`, but I don't see that in your logs above?

**Comment by mbdevpl** [comment]
Since the error message suggests that something is wrong when the space is in wireless network name, I wanted to try without the space. And I simply commented on what differences in logs I saw with and without spaces in wireless network name. Rather than distraction, I think it is a digression if anything ;) And judging by what I saw, the error seems to have quite severe consequences (i.e. prevents use of IPv6 when network name has spaces).

Anyway, I renamed the network back to `Wireless LAN`, and ran with `STTRACE=discover`. Repeating pattern that ends with `invalid URL escape "%20"` seems to look like this:
```
[12345] 2016/01/18 23:05:59.921392 local.go:172: DEBUG: discover: Received local announcement from [1234::5678%Wireless LAN]:52760 for ABCDEF
[12345] 2016/01/18 23:05:59.921392 local.go:199: DEBUG: discover: Registering addresses for ABCDEF
[12345] 2016/01/18 23:05:59.921392 local.go:218: DEBUG: discover: Reconstructed URL is &url.URL{Scheme:"tcp", Opaque:"", User:(*url.Userinfo)(nil), Host:"[1234::5678%Wireless LAN]:22000", Path:"", RawPath:"", RawQuery:"", Fragment:""}
[12345] 2016/01/18 23:05:59.921392 local.go:220: DEBUG: discover: Replaced address 0.0.0.0 in tcp://0.0.0.0:22000 to get tcp://[1234::5678%25Wireless%20LAN]:22000
...
[12345] 2016/01/18 23:06:36.283449 cache.go:107: DEBUG: lookup for ABCDEF at IPv4 local
[12345] 2016/01/18 23:06:36.283449 cache.go:108: DEBUG:   direct: [tcp://192.168.0.13:22000]
[12345] 2016/01/18 23:06:36.283449 cache.go:109: DEBUG:   relays: []
[12345] 2016/01/18 23:06:36.283449 cache.go:107: DEBUG: lookup for ABCDEF at IPv6 local
[12345] 2016/01/18 23:06:36.283449 cache.go:108: DEBUG:   direct: [tcp://[1234::5678%25Wireless%20LAN]:22000]
[12345] 2016/01/18 23:06:36.283449 cache.go:109: DEBUG:   relays: []
[12345] 2016/01/18 23:06:36.283449 cache.go:136: DEBUG: lookup results for ABCDEF
[12345] 2016/01/18 23:06:36.283449 cache.go:137: DEBUG:   direct:  [tcp://[1234::5678%25Wireless%20LAN]:22000 tcp://192.168.0.13:22000]
[12345] 2016/01/18 23:06:36.283449 cache.go:138: DEBUG:   relays:  []
[12345] 2016/01/18 23:06:36.283449 connections.go:362: INFO: Failed to parse connection url: tcp://[1234::5678%25Wireless%20LAN]:22000 parse tcp://[1234::5678%25Wireless%20LAN]:22000: invalid URL escape "%20"
```

Like what I saw with %25 - sometimes the space character is logged as %20, sometimes as a space.

**Comment by canton7** [comment]
Looks like it gained a level of escaping around about here? https://github.com/syncthing/syncthing/blob/ef0a0db07e8075d87ca054452ccd09928f4c261d/lib/discover/local.go#L217

It is weird that it seems to affect you, but not me...

**Comment by canton7** [comment]
Looks like `u.String()` adds a level of escaping which we're not expecting. If we fall into the `if` at L212 we get an overly-escaped URL, whereas if we hit the `else` then nothing is escaped?

**Comment by mbdevpl** [comment]
You can never understand what's under the hood, if there's just a big black box labeled "MS" ;)

I'm not that versed in go, not at all actually, but in [one spot (line 218)](https://github.com/syncthing/syncthing/blob/ef0a0db07e8075d87ca054452ccd09928f4c261d/lib/discover/local.go#L218) there's `u` while in [other spot (line 220)](https://github.com/syncthing/syncthing/blob/ef0a0db07e8075d87ca054452ccd09928f4c261d/lib/discover/local.go#L220) there's `u.String()`. The print results differ, which suggests that https://golang.org/pkg/net/url/#URL.String does something to the URL. This is expected, because in most programming languages `str(x) is not x`, but is this conversion desired there?

**Comment by canton7** [comment]
Heh, same conclusion.

**Comment by mbdevpl** [comment]
Yeah, however I'm very far away from being able to suggest a fix quickly... I'm very happy we managed to narrow the issue down though :)

**Comment by AudriusButkevicius** [comment]
https://golang.org/src/net/url/url.go?s=16958:16987#L627
Seems we need to unescape urls before using then.

**Comment by canton7** [comment]
This looks suspiciously similar to #2444

**Comment by canton7** [comment]
[Changed on Jan 5th](https://github.com/golang/go/commit/8e95654ac84d5a5ad2303bedc26065a057b263fc#diff-6c2d018290e298803c0c9419d8739885L478), just in time got 1.6beta1

**Comment by canton7** [comment]
Hrm, it looks like url.Parse should be able to handle a fully-escaped URL though: https://github.com/golang/go/blob/master/src/net/url/url_test.go#L347.

**Comment by canton7** [comment]
Ah, no it's [this commit](https://github.com/golang/go/commit/a6869d1c5c5172dda7fdbea5e6b6ffbd2f997db1#diff-6c2d018290e298803c0c9419d8739885R180) which broke it. Idiot. If the RFC says something about validating input, it's not a good idea to be *more* restrictive...

**Comment by calmh** [comment]
Adding the URL from above to the test cases in net/url/url_test.go (the ones changed by that commit) actually still passes though.

**Comment by canton7** [comment]
Definitely running 1.6beta2?

**Comment by calmh** [comment]
Yeah, pulled and checked out.

```
jb@syno:/u/l/g/s/n/url $ git describe --tags
go1.6beta2
jb@syno:/u/l/g/s/n/url $ git d
 src/net/url/url_test.go | 1 +
 1 file changed, 1 insertion(+)

diff --git a/src/net/url/url_test.go b/src/net/url/url_test.go
index c31b189..149ddfd 100644
--- a/src/net/url/url_test.go
+++ b/src/net/url/url_test.go
@@ -1246,6 +1246,7 @@ func TestParseAuthority(t *testing.T) {
                {"http://[::1]/%48", false},       // %xx in path is fine
                {"http://%41:8080/", true},        // not allowed: % encoding only for non-ASCII
                {"mysql://x@y(z:123)/foo", false}, // golang.org/issue/12023
+               {"http://[1234::5678%25Wireless%20LAN]:22000", false},
                {"mysql://x@y(1.2.3.4:123)/foo", false},
                {"mysql://x@y([2001:db8::1]:123)/foo", false},
                {"http://[]%20%48%54%54%50%2f%31%2e%31%0a%4d%79%48%65%61%64%65%72%3a%20%31%32%33%0a%0a/", true}, // golang.org/issue/11208
jb@syno:/u/l/g/s/n/url $ go test
PASS
ok  	_/usr/local/go-exp/src/net/url	0.010s
jb@syno:/u/l/g/s/n/url $ 
```

The false in that test line is "do not expect a parse error for this URL"

**Comment by canton7** [comment]
Wait, so... does `url.Parse("tcp://[1234::5678%25Wireless%20LAN]:22000")` succeed in that go version, then? Why is it failing with Syncthing..? Confused. Maybe I need food.

**Comment by calmh** [comment]
No, my "go test" above is confused due to it not being in my default goroot. It fails with 1.6beta2, sorry.

**Comment by calmh** [comment]
I filed a Go bug on it

**Comment by canton7** [comment]
Think it's worth working around this in the meantime? It kinda scuppers local connections on Windows... I suspect manually concatenating `u.Scheme`, `://`, and `u.Host instead of using `u.String()` [here](https://github.com/syncthing/syncthing/blob/ef0a0db07e8075d87ca054452ccd09928f4c261d/lib/discover/local.go#L220) would do it. Happy to put a patch together if you think it's worth it.

**Comment by calmh** [comment]
Yeah, could probably just yank url.Parse from 1.5 and include it in our code or so othewise

**Comment by canton7** [comment]
Outputting a device address to e.g. `/rest/system/connections` which is sometimes escaped and sometimes isn't (depending on internal stuff) is a bit nasty for consumers, whatever the Go library is doing.

**Comment by calmh** [comment]
I don't think I was suggesting that. As far as I'm concerned the URL is correct as is and the Go URL parser is broken.

**Comment by canton7** [comment]
That's correct. One workaround is not to produce escaped URLs which the parser cannot handle. This has the advantage of *also* meaning that we don't give both escaped and unescaped URLs to API consumers.

**Comment by calmh** [comment]
Wait, you mean we have both? Where? 

FWIW it's accepted as a Go bug and probably fixed in the upcoming 1.6 release

**Comment by canton7** [comment]
[Right here](https://github.com/syncthing/syncthing/blob/ef0a0db07e8075d87ca054452ccd09928f4c261d/lib/discover/local.go#L212-L224).

If we hit the `if`, we get an escaped URL, and can't connect. If we hit the `else`, we don't escape the URL, we *can* connect, and we show an unescaped address in `/rest/system/connections`. I'm assuming that if `url.Parse()` gets fixed and we hit the `if`, we'll display an escaped address in `/rest/system/connections`?

**Comment by calmh** [comment]
I don't see how that can happen; that is how we build the escaped URL that we then later cannot parse again...?

Sure, a workaround would be fine.

**Comment by canton7** [comment]
Hmm, I might be wrong in my exact diagnosis.

What I know for sure: Currently, if an IPv6 connection is established between a Windows device and something else, then the address in `/rest/db/connections` is *not* escaped. Note that such connections are only possible if we don't hit the issue this thread is about.

My worry is that, once we fix the issue described in this thread, the address in `/rest/db/connections` could appear as an escaped IPv6 address.

This means that API consumers will have to handle both escaped and unescaped address in `/rest/db/connections`.

My proposal was to construct an unescaped address [here](https://github.com/syncthing/syncthing/blob/ef0a0db07e8075d87ca054452ccd09928f4c261d/lib/discover/local.go#L220), killing both birds with one stone.

**Comment by calmh** [comment]
Ah. `/rest/system/connections` reports raw addresses, not the connection URL. That should probably be fixed at some points, but explains the lack of escaping.

**Comment by calmh** [comment]
This should be fixed in 1.6rc1 I think

**Comment by calmh** [comment]
Release builds from today onwards are on go1.6rc1+ which solves this.

**Comment by ProactiveServices** [comment]
I'm seeing this error on Windows 7, syncthing 1.1.4.

Interface index 11 is my WLAN adaptor, and a device set to use the IPv6 address `tcp://[fe80::f663:1fff:fe22:54ea%11]:22000` causes this error:

`service.go:381: INFO: Parsing dialer address tcp://[fe80::f663:1fff:fe22:54ea%11]:22000: parse tcp://[fe80::f663:1fff:fe22:54ea%11]:22000: invalid URL escape "%11"`

If I use the interface suffix `%%11` then the URL is correctly resolved.
