### ISSUE TITLE
Add support for proxy configuration

### ISSUE THREAD

**Issue by juliohm1978** [syncthing/syncthing#271]
As far as I can tell, sync is done via TCP, so adding support for proxied connections should be on the table, both HTTP and SOCKS.

**Comment by histrio** [comment]
+1 vote

**Comment by nottinhill** [comment]
Not supporting Proxys is like not supporting the Internet. It is very negative for this project.

**Comment by calmh** [comment]
> If someone contributes the code, it is welcome.

**Comment by dboonz** [comment]
+1

**Comment by rumpelsepp** [comment]
Proxy Support has been added with: https://github.com/syncthing/syncthing/commit/175340522f63beaa15e1c301b7da92e3a80cf740
