### ISSUE TITLE
delete: mkdir Access is denied.

### ISSUE THREAD

**Issue by Gibbz** [syncthing/syncthing#2714]
[UBCXW] 11:16:58 INFO: Puller (folder "GameBackups", file "Company of Heroes 2\\Disk_1\\231440_depotcache_7.csm"): delete: mkdir \\?\E:\GameBackups\.stversions: Access is denied.

Getting a pile of these on one of my folders since updating to the latest version. 
Is there a fix coming for this?

**Comment by AudriusButkevicius** [comment]
I don't think it's anything todo with the latest version, never the less, it does look broken.

**Comment by calmh** [comment]
@Gibbz can you show a screenshot of the folder configuration, please?

**Comment by Gibbz** [comment]
![syncthing](https://cloud.githubusercontent.com/assets/650506/12528631/5c647480-c1ec-11e5-8f23-b3707fb86be6.jpeg)

**Comment by calmh** [comment]
Thanks. Your error message in the initial report does not contain a backslash between "gamebackups" and ".stversions" - is this actually what is printed or just an error in copy & paste?

**Comment by Gibbz** [comment]
Heres a few more lines of it, i think it was just a copy paste error

[UBCXW] 11:13:53 INFO: Puller (folder "GameBackups", file "Company of Heroes 2\\Disk_1\\231441_depotcache_1.csd"): delete: rename \\?\E:\GameBackups\Company of Heroes 2\Disk_1\231441_depotcache_1.csd \\?\E:\GameBackups\Company of Heroes 2\Disk_1\231441_depotcache_1.sync-conflict-20160124-111353.csd: Access is denied.
[UBCXW] 11:13:53 INFO: Puller (folder "GameBackups", file "Dungeon Defenders II\\Disk_1\\228990_depotcache_1.csd"): delete: mkdir \\?\E:\GameBackups\.stversions: Access is denied.
[UBCXW] 11:13:53 INFO: Folder "GameBackups" isn't making progress. Pausing puller for 1m0s.

**Comment by Gibbz** [comment]
ok again it didnt copy right, heres a screen grab...
![error](https://cloud.githubusercontent.com/assets/650506/12533785/0aafac36-c28c-11e5-8dc5-5676809025b1.jpeg)

**Comment by AudriusButkevicius** [comment]
Well, syncthing simply does not have permissions to write to that directory

**Comment by Gibbz** [comment]
So how do i fix this? And why would it suddenly change?

**Comment by canton7** [comment]
Can you browse to `E:\GameBackups` in explorer?

**Comment by AudriusButkevicius** [comment]
Well, syncthing hasn't changed it, so you should look for the cause elsewhere.
You can google how to change directory permissions.

**Comment by Gibbz** [comment]
ok deleted the file .stversions and restarted and its fixed now.... odd...

Thanks guys :)
