### ISSUE TITLE
Deleting a folder that contains ignored files/folder break sync

### ISSUE THREAD

**Issue by MoOx** [syncthing/syncthing#2719]
Hi,

First of all, thanks for this tool. So cool.
I am currently dropping Dropbox/Bittorrent Sync for this and I just got something "weird" in term of UX.

I sync my "Development" folder on my 2 machines + NAS. This folder contains git repo and also some "cache" files I can get with my package manager (npm: node_modules) and also builded files (most of the time in a "dist" folder).
So in my .stignore, I added the following. 
```
.DS_Store
node_modules
dist
```

I replicated this .stignore on all of my machine because it's seems useless (and consume CPU) to sync this kind of files that I can get/generate with a simple command.

This works as expected except when I remove a folder which contains an ignored file/folder: if I remove a folder from my machine A, and B had it synced with ignored files inside, Syncthing on B will consider the folder as "Out of sync" and will not delete it completely (to keep the ignored files). So I have to delete it by hand on B to have the sync "ok".

I previously did the same with Bittorent Sync and have my folder removed (which in a way make sense too).

UX of Syncthing (even if I understand the reasons why it's probably like that by default) seems a bit weird. Is this something made on purpose? Is this subject to change (an option to handle this?)

Thanks in advance for your time.

Edit: I also notice this behavior just because of some crappy OS X .DS_Store files.

**Comment by wweich** [comment]
See "Next Gen Ignores: Requirements" (#2491).
>- Must be able to specify if ignored files should be preserved or removed on directory delete.

**Comment by MoOx** [comment]
Oh thanks. I missed this.
