### ISSUE TITLE
Feature request: Deterministic seeds

### ISSUE THREAD

**Issue by ThomasdenH** [syncthing/syncthing#2720]
Bitcoin wallets have implemented an easy to memorize/record seed. (BIP 39). If I reset my phone, I have to configure every application that connects to it again. Would it be possible to have a similar way to store a backup of the keys on paper to restore them at a later time?

The way BIP39 works is it has a dictionary of words and chooses a number of them at random (between 12-20, depending on the wanted security). It can optionally be protected with a password.

**Comment by AudriusButkevicius** [comment]
Android app already as an option to export configs, which does what you want

**Comment by ThomasdenH** [comment]
The reason I ask is because a physical copy on paper is often more useful than a digital one, but I do realise it is a rather trivial improvement compared to the amount of work.

**Comment by calmh** [comment]
We don't generate things based on seeds though. The key and certificate is created based on cryptographically secure random numbers, as it must be. Backing up the key and certificate is our equivalent.

**Comment by AudriusButkevicius** [comment]
You could extract the primes ;D
