### ISSUE TITLE
Syncthing for Android always uploading

### ISSUE THREAD

**Issue by NovaMoon** [syncthing/syncthing#2722]
Since the last android syncthing update it is always using the full upload to upload basically nothing to my server. this doesnt happen on linux or windows. using latest version. if you need more infos i can try to provide more

**Comment by AudriusButkevicius** [comment]
What do you mean?

**Comment by NovaMoon** [comment]
when i have syncthing open on my phone its always uploading something. doesnt happen on linux or windows

**Comment by AudriusButkevicius** [comment]
What do you mean it's uploading something. How do you know?

**Comment by NovaMoon** [comment]
ok my bad here. its actually syncing stuff i want it to sync but the app isnt showing it. everything is on "idle" even tho one folder is syncing with the server. thats why i was confused
