### ISSUE TITLE
Too slow session start through relay, and host connected to relay via internet instead local network

### ISSUE THREAD

**Issue by alex73** [syncthing/syncthing#2723]
Hi. I reported issue to the relaysrv project(see https://github.com/syncthing/relaysrv/issues/30), but Audrius wrote it was wrong repository.

The problem is: devices connected after long delay through my relay server. Up to 10 minutes sometimes. Connection to relay server is really fast(it displays Relays:1/1 immediately), but session between devices starts after long delay. Audrius recommended to change RelayReconnectIntervalM, but it doesn't change anything.

After both syncthing servers connected to one relay, I'm expecting just some seconds for start session. Also, looks like my hosts connected to relay through internet instead local network.

My configuration is: host1 and host2 in the internal network, host3 outside behind NAT, host1 also has public IP

host1/relaysrv has address 192.168.1.1 and external IP (67.x.x.x)
host2/syncthing has address 192.168.1.5 - the same internal network as host1(but routes to worls through 178.x.x.x)
host3/syncthing has address 10.x.x.x behind NAT(other internal network with external ip=86.x.x.x)

So, host1 and host2 can be accessed directly in local network, host3 can access to host1, host2 and host3 can't see each other directly.

host1/relaysrv started with -pools=""
host2 and host3 : adress is dynamic, global discovery enabled, relay enabled
relay server host host2 defined as "relay://192.168.1.1:port"
relay server host host3 defined as "relay://67.x.x.x:port"

Just after starting, syncthing on host2 and host3 finds relay immediately, but display "Disconnected" as device status. Debug of relaysrv displays only "pong" packets.

Probably it will be important: When session started after huge dalay, relaysrv displays source and target very strange. It displays 178.x.x.x but not 192.168.x.x as source address for host2). Target address(host3) displayed as 86.x.x.x(that's good). Additional host that doesn't know about my local relay connects to host2 very fast through public relay server. Shouldn't public relay be disabled if I defined local relay ?

Logs after both syncthing(on the host2 and host3) was started:

21:29:19 listener.go:46: Listener accepted connection from 86.x.x.x tls true
21:29:19 listener.go:105: Message protocol.Pong from UUK...
21:29:21 listener.go:46: Listener accepted connection from 192.168.1.5
21:29:21 listener.go:105: Message protocol.JoinRelayRequest from P3F...
some ...protocol.Pong... messages
21:33:51 listener.go:46: Listener accepted connection from 178.x.x.x tls true
21:33:52 listener.go:105: Message protocol.ConnectRequest from P3F...
21:33:52 session.go:53: New session <a3.../43...>
21:33:52 listener.go:161: Sent invitation from P3F... to UUK...
21:33:52 session.go:121: Session <a3.../43...> serving
21:33:52 listener.go:236: Sending message protocol.SessionInvitation to UUK...
21:33:52 listener.go:187: Closing connection P3F... xdr read: read tcp 178.x.x.x use of closed network connection
21:33:52 listener.go:46: Listener accepted connection from 178.x.x.x tls false
...

Is it possible that problem is in global discovery ? I.e. host2 connected to relay through internet instead local network ?

**Comment by AudriusButkevicius** [comment]
I suggest you to adjust a variable in the previous thread, see if it helps.

**Comment by alex73** [comment]
No, it didn't help. 
Additionaly, very strange behavior: host2 connects to relaysrv through internet, not through local network. Probably, global discovery uses external address. But why it doesn't use local connection to relaysrv ?

**Comment by AudriusButkevicius** [comment]
You should run syncthing with STTRACE=discovery environment variables set.
I don't think the addresses matter in this case, as long as they connect.

**Comment by alex73** [comment]
See [attached log](https://github.com/syncthing/syncthing/files/107734/log.txt) after STTRACE=discovery.
As you can see, discovery returns my relay address at 08:09:32, but devices were connected only at 08:11:42.

I changed relay's address in the /etc/hosts on the host2 for be able to connect to relay locally. Otherwise, host2 connected to relay through internet.

So, as far as I understand, syncthing uses global discovery for connecting to relay, even when relay specified. And, after connection to relay, it doesn't ask to connect to specific hosts asap

.

**Comment by AudriusButkevicius** [comment]
Well there are different parts of the relay connection. One is joining to await anyone to ask to connect to you, and another one is connecting to a relay to find someone you are looking to connect to.

Can you also run with STTRACE=discovery,connections? The default reconnect loop time is 60 seconds, so 2 minutes doesn't look terrible to me.

**Comment by AudriusButkevicius** [comment]
Also, logs from both sides would help.

**Comment by alex73** [comment]
> Well there are different parts of the relay connection. One is joining to await anyone to ask to connect to you, and another one is connecting to a relay to find someone you are looking to connect to.

If connection to relay and start session via relay are in the different part of program, it's clear now why delay exist. In the real world, even 10 minutes timeout will be acceptable for me since session working many hours usually. Last time(probably after RelayReconnectIntervalM change ?) connection initial timeout is about 2 minutes.

The problem possible is more general. As you remember, my relay is in the same local net with host2. I was succeed to setup transfer via relay and host2 locally only by adding external relay name to /etc/hosts on the host2. But it's hack. In standard configuration, host2 always connects to relay via Internet, not via local network. Additionally, connection was established via other relays(when one host configured to use my relay but second host used public relays). And I have to use global discovery for find my boxes even when they are using common relay.

That means, I can't setup relay as really private because:
1) I can't guarantee that not other relay will be used - that means speed can be slow
2) I need global discovery - but common relay if enough to find each other
3) Connection always will be through Internet, not via local network - huge speed reduction

Ideally, I would like to have ability to disable discovery, enable relaying to my relay, then every host that connects to relay will just ask relay about connections to known devices.

P.S. I can send logs from two my hosts and relay if you need.

**Comment by AudriusButkevicius** [comment]
Relays and discovery are different things, relays don't provide discovery and vica versa. You need both for syncthing to function.

At the same time, they were not designed to run on the same local network as one of the syncthing devices (not even talking about on the same machine) because the IPs a discovery/relay would see would either be 127.0.0.1 or some 192.168.0.5 which makes no sense when connecting from the outside of the LAN.

**Comment by alex73** [comment]
Yes, I understood it now. But would it be good to implement such mode for private relay or named it something other ? I mean, when user configured "private relay with address", syncthing should connect to this relay using configured address without any discovery. Just an idea.
