### ISSUE TITLE
Encrypted Read Only Node in the future?

### ISSUE THREAD

**Issue by andrewparadi** [syncthing/syncthing#2726]
Exciting announcement from BitTorrent Sync on new endpoint encryption: https://blog.getsync.com/2016/01/21/understanding-the-sync-encrypted-folder/. Huge plus since I could finally have secure backups on a friend's offsite server with complete security. Will there be a future end point encryption option for Syncthing?

**Comment by canton7** [comment]
See #109 and #2111.

There was work by a contributor, but it seems to have stalled.

**Comment by AudriusButkevicius** [comment]
Please be a good citizen, and go through existing issues first.
