### ISSUE TITLE
update to 0.12.16 on cubietruck running wheezy

### ISSUE THREAD

**Issue by drawkula** [syncthing/syncthing#2728]
...seen on Cubietruck (Cubieez/Wheezy) just some minutes ago:

    Vorbereitung zum Ersetzen von syncthing 0.12.15 (durch .../syncthing_0.12.16_armhf.deb) ...
    Ersatz für syncthing wird entpackt ...
    Trigger für man-db werden verarbeitet ...
    syncthing (0.12.16) wird eingerichtet ...
    pkill: Ungültige Option -- H

    Usage:
     pkill [options] <pattern>

    Options:
     -<sig>, --signal <sig>    signal to send (either number or name)
     -e, --echo                display what is killed
     -f, --full                use full process name to match
     -g, --pgroup <id,...>     match listed process group IDs
     -G, --group <gid,...>     match real group IDs
     -n, --newest              select most recently started
     -o, --oldest              select least recently started
     -P, --parent <ppid,...>   match only childs of given parent
     -s, --session <sid,...>   match session IDs
     -t, --terminal <tty,...>  match by controlling terminal
     -u, --euid <id,...>       match by effective IDs
     -U, --uid <id,...>        match by real IDs
     -x, --exact               match exectly with command name
     -F, --pidfile <file>      read PIDs from file
     -L, --logpidfile          fail if PID file is not locked

     -h, --help     display this help and exit
     -V, --version  output version information and exit

    For more details see pgrep(1).

...all other packages on this box are uptodate, `pgrep` is:

    $ dpkg -S pgrep
    bash-completion: /usr/share/bash-completion/completions/pgrep
    procps: /usr/share/man/man1/pgrep.1.gz
    unzip: /usr/share/man/man1/zipgrep.1.gz
    procps: /usr/bin/pgrep
    unzip: /usr/bin/zipgrep
    $ dpkg -s procps | egrep '^(Pack|Vers)'
    Package: procps
    Version: 1:3.3.3-3

HTH.

**Comment by rumpelsepp** [comment]
weird. The `H` from the symbolic signal name seems to be recognized as a flag (https://github.com/syncthing/syncthing/blob/master/debian/postinst#L5). But that's the correct syntax, though...

**Comment by canton7** [comment]
The synopsis [from here](http://linux.die.net/man/1/pkill) is `pkill [-signal] [-fvx] [-n|-o] [-P ppid,...] [-g pgrp,...] [-s sid,...] [-u euid,...] [-U uid,...] [-G gid,...]`, i.e. the signal comes before anything else. Maybe Debian's version of `pkill` is being particularly anal about the order of its arguments?

**Comment by rumpelsepp** [comment]
from the `pkill(1)` of my current debian box:

```
NAME
       pgrep, pkill - look up or signal processes based on name and other attributes

SYNOPSIS
       pgrep [options] pattern
       pkill [options] pattern
```

Just tried it out, it does't care about the order of the arguments. Maybe my pkill is too new, since I am at testing atm.

```
$ dpkg -s procps | egrep '^(Pack|Vers)'
Package: procps
Version: 2:3.3.11-3
```

**Comment by rumpelsepp** [comment]
@drawkula #2728 may probably fix this. Could you please try these commands on your debian box and give us feedback what's happening?

```
pkill -x -HUP syncthing
pkill -HUP -x syncthing
```

**Comment by drawkula** [comment]
```bash
(yeti@cubietruck0:2)~$ LANG=
(yeti@cubietruck0:2)~$ pkill -x -HUP syncthing
pkill: invalid option -- 'H'

Usage:
 pkill [options] <pattern>

Options:
 -<sig>, --signal <sig>    signal to send (either number or name)
 -e, --echo                display what is killed
 -f, --full                use full process name to match
 -g, --pgroup <id,...>     match listed process group IDs
 -G, --group <gid,...>     match real group IDs
 -n, --newest              select most recently started
 -o, --oldest              select least recently started
 -P, --parent <ppid,...>   match only childs of given parent
 -s, --session <sid,...>   match session IDs
 -t, --terminal <tty,...>  match by controlling terminal
 -u, --euid <id,...>       match by effective IDs
 -U, --uid <id,...>        match by real IDs
 -x, --exact               match exectly with command name
 -F, --pidfile <file>      read PIDs from file
 -L, --logpidfile          fail if PID file is not locked

 -h, --help     display this help and exit
 -V, --version  output version information and exit

For more details see pgrep(1).
(yeti@cubietruck0:2)~$ pkill -HUP -x syncthing
(yeti@cubietruck0:2)~$ ### no output ###
```

**Comment by rumpelsepp** [comment]
So, I guess we have it. :-)

**Comment by canton7** [comment]
Yay Debian ><

**Comment by canton7** [comment]
:+1:

**Comment by calmh** [comment]
Thanks
