### ISSUE TITLE
Linux x86_64 - 0.12.16 update fail - pkill: invalid option -- 'H'

### ISSUE THREAD

**Issue by plittlefield** [syncthing/syncthing#2731]
Just updating to 0.12.16 on Ubuntu 12.04.5 LTS x86_64 using **syncthing_0.12.16_amd64.deb** and I receive the following error...

`Preparing to replace syncthing 0.12.15 (using .../syncthing_0.12.16_amd64.deb) ...`
`Unpacking replacement syncthing ...`
`Setting up syncthing (0.12.16) ...`
`pkill: invalid option -- 'H'`
`Usage: pkill [-SIGNAL] [-fvx] [-n|-o] [-P PPIDLIST] [-g PGRPLIST] [-s SIDLIST]
	[-u EUIDLIST] [-U UIDLIST] [-G GIDLIST] [-t TERMLIST] [PATTERN]`

I can also confirm that if I try again and install it manually, the same error occurs.

`sudo dpkg -i /var/cache/apt/archives/syncthing_0.12.16_amd64.deb`

**Comment by AudriusButkevicius** [comment]
This has been fixed.

**Comment by AudriusButkevicius** [comment]
But not yet released.

**Comment by plittlefield** [comment]
OK.

**Comment by rumpelsepp** [comment]
See #2729
