### ISSUE TITLE
Bad Certificate Error

### ISSUE THREAD

**Issue by alexcampkin** [syncthing/syncthing#2733]
Have installed Syncthing to two AWS instances and linked to each other. However on boot I currently get the error with the disconnected warning next to each device on the GUI:

<b>Bad certificate from HOST02 (192.168.0.91:8384): x509: certificate is valid for ip-192-168-0-91, not syncthing</b>

I have tried to investigate this issue, And the ip-192-168-0-91 appears to be the SSH authentication certificate or may have been created mistakenly by Syncthing as the name of the sever is ip-192-168-0-91. Have been trying for hours to resolve this, If you could shed any light on the issue it would be most appreciated!

Many Thanks,
Alex

**Comment by AudriusButkevicius** [comment]
I assume its presented when accessing the UI. Just ask the browser to skip certificate validation, or disable https for UI access.

**Comment by alexcampkin** [comment]
Hi Audrius,

HTTPS is disabled for the GUI access, this issue appears to be happening when attempting to connect to other device to begin sync.

Thanks!

**Comment by canton7** [comment]
Where exactly do you see the error? Can you give us a screenshot? It's not clear right now.

**Comment by AudriusButkevicius** [comment]
Did you mess around with the file paths? It seems you swapped the certificate used for trust with the certificate used for GUI? Or did you try to install your own certificate?

**Comment by alexcampkin** [comment]
![image](https://cloud.githubusercontent.com/assets/16900469/12583967/2ac0afea-c43d-11e5-9f95-d1d921f6f582.png)

**Comment by alexcampkin** [comment]
Please find attached above. I have made sure all settings insure that HTTPS is not required. Nothing has been messed about with all standard settings as the install guide instructs.

**Comment by AudriusButkevicius** [comment]
You seem to have messed around with the certificates which led to this.

**Comment by canton7** [comment]
Have you changed anything at all in Syncthing's `config` folder?

**Comment by alexcampkin** [comment]
Please take my word. I have not touched certificates, To do this would mess up my SSH access.

**Comment by canton7** [comment]
No, Syncthing's certificates. Nothing to do with SSH.

**Comment by alexcampkin** [comment]
Not touched the 4 certificate files in the config folder, Getting a screen of the config.xml for you now

**Comment by alexcampkin** [comment]
![image](https://cloud.githubusercontent.com/assets/16900469/12584069/addce5f6-c43d-11e5-8d24-d639de957f63.png)
No settings touched except the listen IP as instructed in guides.

**Comment by canton7** [comment]
We're not interested in `config.xml`, just `key.pem` and `cert.pem`.

**Comment by AudriusButkevicius** [comment]
Just delete the certificates and let syncthing regenerate them, which will change the device ID.

**Comment by alexcampkin** [comment]
Ok thanks I will try that now!

**Comment by alexcampkin** [comment]
Hi All,

Thanks alot for your help on this, It appears to be somewhat resolved by not touching the device name. However it attempts to sync and then says a new device wants to connect.. which si the same device as the one thats connected and then I get a out of sync error.

**Comment by wweich** [comment]
You entered the wrong address for `host02`. `8384` is the WebUI port, not the sync port. The sync port is normally `220000`.

**Comment by alexcampkin** [comment]
When devices attempt to connect they connect on the 8384 port, as shown in the message
'Device KTGIH4D-N4E4COK-ELD437D-PSEGQYW-VDQ5SC4-D5ACBWL-ESGNQR7-TRHDWAP (192.168.0.91:8384) wants to connect. Add new device?' I don't think the port is the issue here

**Comment by canton7** [comment]
Boom, well spotted.

**Comment by AudriusButkevicius** [comment]
8384 is used for web UI, 22000 is used for sync protocol. You mixed the two up while fiddling with something, as its trying to connect to the wrong port.

**Comment by alexcampkin** [comment]
Audrius, I don't get where your certainty is coming from, I used the defaults so if something wrong its on your side. I have changed the address to both ports and it works fine either way, Checked in the device and the ports are correct as said above. If your so sure tell me what I have changed to do this? Because I must be much smarter than I think!

**Comment by canton7** [comment]
`Bad certificate from HOST02 (192.168.0.91:8384)`

See how the port is "8384"? Port 8384 is used for the web gui, not for Syncthing's sync protocol. Either your host is trying to connect to HOST02 on `192.168.0.91:8384` (because you said to connect to a static IP, maybe?), or HOST02 has some very bad configuration somewhere (I'm not sure that's even possible).

**Comment by canton7** [comment]
The stuff about your changing the certificate was a red herring: we didn't spot that the port was wrong.

**Comment by calmh** [comment]
@alexcampkin You posted your config; the device is in there, manually configured with an IP address and port 8384. This is incorrect. Use port 22000 or whatever you might have changed the sync port to on the other side. This is not the default.

<img width="345" alt="screen shot 2016-01-26 at 16 38 54" src="https://cloud.githubusercontent.com/assets/125426/12585249/6e4987ba-c44b-11e5-8e68-116a43be63c6.png">

**Comment by alexcampkin** [comment]
Ah I see! Thank you @calmh It actually appears to be working now funnily enough, sync and all but I will make these changes now

**Comment by AudriusButkevicius** [comment]
If it was an issue on our side, we'd have more than a single report about this. If it works, then there isn't much to discuss. If it doesn't, provide settings dialog and remote device edit dialog screenshots from both sides, and we'll tell you where you've gone wrong.

**Comment by alexcampkin** [comment]
As calmh just said we found the error. Apologies for the wording, glad its all sorted out now.

**Comment by calmh** [comment]
:+1: All good.

Even with this config, you may have gotten a successful connection from the other side, so it could potentially work a little bit even with the wrong port set.

**Comment by alexcampkin** [comment]
Okay thanks! should this just be set to port 80 or? Getting Operation not permitted errors with sync but taking a guess that's just a permissions issue so all good as far as I can see!

**Comment by calmh** [comment]
See the `<listenAddress>` tag in the config above, with port `22000` in it? That's the port number you want to set in the `tcp://something:port` address on the other side.

**Comment by alexcampkin** [comment]
I see now! thanks, Completely get how that config file works now I've had a good read through. Thanks for your help!
