### ISSUE TITLE
"WiFi only" should not depend on "background/foreground" and should be turned on by default

### ISSUE THREAD

**Issue by fraternl** [syncthing/syncthing#2736]
I've been an early adopter of btsync and used it for a long time. When things became sour there I started investigating syncthing and watched if I could use it as an alternative.

After successfully running it for a while on both Linux (in datacentre) and Windows I started my first experiment on Android.

I had some trouble loading the sync as I expected "the sync" to be pushed to my Android just like on the other devices. When I did get it to work it immediately started sending all the data that was in the sync I was testing with.

I wasn't prepared that this could happen as all syncing software on mobile devices I've used thus far are made in a way that syncs are by default "on demand".
Now I know this hasn't been implemented (yet??).
This makes it useless for all my real world scenarios I have currently working with other software.

But my bad luck didn't stop there.
Whilst syncing I got a message that my dataplan was running out and before I could stop syncthing it burned 2.6 GB of the 3 GB dataplan.
I had my WiFi turned off because I travelled that morning by train which always gives me a bad WiFi-connection.

Some said I should have turned "WiFi only" off, but at this stage I was still running it as a foreground application. That option is not selectable then,,,,

IMHO the WiFi-only should be the initial setting and this should not depend on ""foreground/background"

I've removed the application for the time being, but I will install it immediately whenever an "on demand" is implemented.

**Comment by fraternl** [comment]
Edit....  just noticed that syncthing for android has a seperate Github...   sorry

**Comment by canton7** [comment]
Yep -> https://github.com/syncthing/syncthing-android/issues/new
