### ISSUE TITLE
Syncthing should be case insensitive by default

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2739]
This is a proposal for solving the case insensitive rename, file name "folding" (i.e., multiple files differing only in case on Linux mapping to a single file on Windows etc) and similar issues.

Currently we're fully case sensitive everywhere, and introducing case insensitivity is a bit tricky. We can't check an incoming index update to see if we already have a file name with the same characters in a different case as the index is case sensitive. Doing that would require having a separate index of (for example) lower-case-folded-name => actual-name-in-index and consulting/updating this index on every operation, which is a significant overhead.

However I think that case insensitivity is the more common use case. Currently (according to usage data) we have 51.5% of users on case insensitive platforms (Windows, Mac and Android), but I'd argue that a vast majority of Linux users also don't _use_ or _want_ files differing only in case. That is of course just a guess. However, I propose that we change the default to case insensitive, which is somewhat simpler than doing it optionally. Specifically, we:
- Use unicode case folding for all file names as keys in the database. This adds some overhead, but only in processing (i.e. no extra index and stuff).
- Add a check in the scanner for seeing more than one case variant of a given name in the same directory. If there is a match, blacklist the file (all variants), tag it as invalid in the database, and log a warning.
- ... there is no step three, we are now case insensitive. We still use the name from the actual FileInfo when performing operations (including renames) so we retain the correct casing.

However, some users will require us to retain the current behavior. Hence,
- Add an advanced per folder config `caseSensitiveFilesystem`. When set, this disables the case folding mechanism described above.
- Announce this behavior as a flag bit on the folder in the ClusterConfig message. A mismatch on this flag between devices is a configuration error and the connection is dropped.

Changing the flag requires dropping the index and rescanning. Or we could live convert the index, if we feel like putting in the effort, but the main point is that we are either in case sensitive mode or not and this affects how we store stuff in the index.

**Comment by AudriusButkevicius** [comment]
Sounds good.

**Comment by AudriusButkevicius** [comment]
Yet I am not sure if I would bother with the extra flag. We are supposed to be cross platform, and it's fine for us to use a set of features that is available on all of them.

**Comment by AudriusButkevicius** [comment]
Yet it doesn't cost much to add that as its just maintaining the original implementation, so maybe it's worth to have.

**Comment by canton7** [comment]
I think that's a fair approach: catch it at the source. Someone's going to complain though...

Having case changes on one device reflected on another would be nice

**Comment by calmh** [comment]
Regarding the flag, I would *love* to simplify this to supporting just one or the other, really. Half as many code paths to test and maintain, etc. We've taken a lowest-common-denominator approach to some other things, so this could be one of those as well. Or we could do a release with this being optional and look at the usage reporting data after a while. If almost noone enables case sensitivity we remove it and clean up.

> Having case changes on one device reflected on another would be nice

This we shall certainly support. Changes to just the case of a file name will be like any other metadata, and we sync it.

**Comment by capi** [comment]
How will your proposal handle the case of case-sensitive file-systems that actually do have two entries with different case in the same directory? I agree that most of the time those are not intentional, but they do exist.

**Comment by Zillode** [comment]
:+1:

**Comment by dcarosone** [comment]
I'm not going to opine about defaults, but I would be highly upset to have
case-insensitivity enforced unconditionally. I do have things I sync only
between Real Systems and that may well be case sensitive, I suppose - at
least I don't want to get burned by case issues that aren't relevant to any
of the nodes in question.

I like the idea of a negotiation flag that indicates incompatible sync
options. I think it might be possible to do better, and essentially flag
that the local state includes data that requires case sensitive backend
storage.

I certainly appreciate the desire for simplicity, and to that end, I worry
whether the various case folding rules of different platforms and
filesystems are actually as simple as one set of consistent rules that can
be guessed by syncthing in a distributed fashion. In other words, whether
this will really solve the problem. I have no idea, but it seems unlikely.

**Comment by calmh** [comment]
> I worry whether the various case folding rules of different platforms and filesystems are actually as simple as one set of consistent rules

That's a perfectly legitimate worry, but apart from Turkish which is Special(tm) (and doesn't have it's sense of case insensitivity really supported by any OS as far as I know) we enforce UTF-8 and the unicode case folding rules are not really simple but at least well defined. This is what's used by at least Mac and Windows, so we're good there.

**Comment by moviuro** [comment]
Just my first two cents here on syncthing:
I only use syncthing on platforms that are case sensitive (Linux, BSD) and I have links in `~` that map to specific files/folders inside a syncthing-ed folder.
```~/.ssh/config -> ~/Documents/Private/setup/ssh/config```
Where `Documents`is kept in sync. Should `syncthing` not respect case, I suspect my configuration will break.

Making case-insensitivity an option is nothing to ban, but making it default will break things for a huge part of the users (48.5% of your userbase can't be dismissed so simply).

**Comment by AudriusButkevicius** [comment]
Why would it break?

**Comment by moviuro** [comment]
@AudriusButkevicius because `Private` may change to `private`, hence breaking my setup.

**Comment by canton7** [comment]
@moviuro If you rename `Private` to `private`, your setup is going to break now, as well.

With @calmh's proposal, Syncthing will not randomly change `Private` to `private`. It will only change `Private` to `private` in response do some other device making that same change, exactly how things are now.

**Comment by moviuro** [comment]
Then it seems I didn't fully grasp the whole case-insensitivity thing.

In any event, I'd expect syncthing to deploy the case along with the files to systems that can manage it.

But actually, this issue will not have any consequences for people using Real Systems:tm:? Just for the devs?

**Comment by wweich** [comment]
As far as I understand: With this change in place and without setting `caseSensitiveFilesystem` in the advanced settings, files and folders will of cause still be transferred with correct case, but you will not be able to have `Private` and `private` inside the same folder, because the internal path identifier will be case insensitive.

**Comment by jcrben** [comment]
Added a $15 bounty: https://www.bountysource.com/issues/30288183-syncthing-should-be-case-insensitive-by-default

**Comment by hobarrera** [comment]
> Add an advanced per folder config `caseSensitiveFilesystem`. When set, this disables the case folding mechanism described above.

This sound awful, the default should be the opposite, since it's safer and sane. Imagine this simple scenario:

* Install syncthing
* Add a directory with a `Downloads` directory and a `downloads` file.
* Boom!

The out-of-the-box behaviour needs to be sane, and not be using workarounds that are only there to support OS's with more primitive file-systems, but brake on modern ones.

**Comment by calmh** [comment]
I'm not sure what you think "boom" is in your description, but under this suggestion there would be none. However if you do what you described *today*, and have both a Linux and Windows machine, you will suffer data loss - boom.

**Comment by Ferroin** [comment]
Doing what he described on a Linux system would also cause data loss if Syncthing were case insensitive by default and you were on a case sensitive FS (The Linux VFS is sane and doesn't let you create new files with names differing only in case on case-insensitive filesystems, so the above would fail locally on a Linux box on FAT32 or a similarly case insensitive filesystem).

Keep in mind also that most people will expect Syncthing to be case-preserving even if it is case-insensitive.  This is how all of the case-insensitive platforms work (Android does it's case insensitivity at a higher level than the OS kernel, OS X has to be case preserving so that the POSIX FS interfaces work (which are case-sensitive), Windows just does it because people expect the OS not to change the case of what they typed).

**Comment by calmh** [comment]
No. You guys are not reading. Quoting myself in the initial description:

> Add a check in the scanner for seeing more than one case variant of a given name in the same directory. If there is a match, blacklist the file (all variants), tag it as invalid in the database, and log a warning.

No data loss. If you wanted case sensitive this is your cue to reconfigure.

> We still use the name from the actual FileInfo when performing operations (including renames) so we retain the correct casing.

Case preserving.

**Comment by QJKX** [comment]
There are significant websites (youtube, imgur) that name things in a case sensitive way, so it's not unlikely that some user somewhere is going to have problems with a clash.

> Add a check in the scanner for seeing more than one case variant of a given name in the same directory. If there is a match, blacklist the file (all variants), tag it as invalid in the database, and log a warning.

Is that blacklist propagated to peers? Do the other peers continue to share and update a file with that name?


Personally I'm against the idea. Having case-clashing files is just an incomplete sync.

**Comment by sirn** [comment]
I ran into this problem today with three machines (Mac, Linux, Mac). Two Macs independently tried to create a directory with different casing ("Projects" and "projects") which are then showed up as two directories on a Linux machine, resulting in both Macs become out-of-sync.

Since both directories has the same content, I (stupidly) tried to clean it up by deleting the wrongly-casing one on the Linux machine. The deletion propagates to the Mac and emptied the directory on both machines.

Personally, I would love to see this implemented regardless of what would be the default.

**Comment by ThomasWaldmann** [comment]
case-insensitivity is not a feature, it is just a source of pain and complications and nobody should do it like that.

**Comment by calmh** [comment]
I'm going to lock this thread since the discussion isn't constructive. The fact is that many of our users' systems have case insensitive file systems, and we must be handle that to do file operations correctly. As implied in the title and explicitly explained in the original description there will always be an option for case sensitivity.
