### ISSUE TITLE
Prompts to share a folder/add a device can be missed if UI is not open at the time of the event

### ISSUE THREAD

**Issue by camsteffen** [syncthing/syncthing#2740]
When another device has shared a folder with me, it should show in a list of available folders with that device with a button to Add Folder.

**Comment by canton7** [comment]
It's shown at the top of the UI, in an alert-style box, with a button to Add Folder.

**Comment by AudriusButkevicius** [comment]
Yeah, you already get prompted, every single time you connect.

**Comment by camsteffen** [comment]
In my experience, the alert often doesn't come until I reconnect a few times. I'm suggesting a persistent UI feature rather than a notification.

**Comment by AudriusButkevicius** [comment]
It comes when we know. We can't make a UI feature for things we don't know.

**Comment by AudriusButkevicius** [comment]
Actually. it currently works based on events, which can be missed if the ui is closed at the point you connect, so something should buffer them.

**Comment by camsteffen** [comment]
Can we improve the logic so that the new folder is announced asap after it is shared?

**Comment by AudriusButkevicius** [comment]
Not sure I follow what you mean, but make a pull request.

**Comment by nickmdowson** [comment]
Hi, I've just added a feature request for something that I think might relate to this bug report. 

In my case the problem is that I don't see these requests normally because I have syncthing running in the background.

**Comment by sirber** [comment]
Doesn't show with UI open for me, have to restart syncthing to get the notification when I add a device or a shared folder.

version: v0.14.25 and older

**Comment by AudriusButkevicius** [comment]
Dup of #2291
