### ISSUE TITLE
Merge syncthing-inotify 

### ISSUE THREAD

**Issue by rumpelsepp** [syncthing/syncthing#2741]
See #9 and https://forum.syncthing.net/t/syncthing-inotify-merge/6653

**Comment by Clete2** [comment]
Thanks for making this. I'm still new to Syncthing, but if I get some time and experience digging into the code, I'll see what I can do. No promises. :+1:

**Comment by calmh** [comment]
For whoever does sink their teeth into this I think the proper approach is similar to what is done externally now, that is use the inotify events to trigger the existing scanner plus do occasional complete scans to be sure.

**Comment by Clete2** [comment]
Sounds like the overall goal is to remove the external running process that it is today and integrate it into the main program itself. That would be opposed to having the main program spin up and monitor a second process.

Furthermore, optionally add a UI checkbox next to the scan interval to allow the user to pick and choose the shares that should use inotify.

**Comment by rumpelsepp** [comment]
I am not sure if we gain anything by spawning a new process and let them communicate over the API. That is done externally now just fine.

**Comment by canton7** [comment]
I don't think the intention is to have the inotify component communicate over the API.

**Comment by calmh** [comment]
No no, that was definitely not my intention. I'm just saying that instead of trying to rearchitect everything to be all filesystem event based, it's probably much easier to keep the current scanner and just "drive" it based on received fs events.

**Comment by capi** [comment]
Merging inotify like it is now may cause some problems as well, since the current inotify implementation is not supported on all platform. For instance, Android client uses the official Android API for this, and I am not sure if inotify would work there (it might).

**Comment by canton7** [comment]
Surely any unsupported platforms would just not get filesystem notifications, and it would still be up to a wrapper to poke the API? Maybe some care needs to be taken to disable settings relating to filesystem notifications if they're not available, but that's cosmetic.

**Comment by capi** [comment]
@canton7 yes, of course. Its just something the one integrating it should consider, that's why I pointed it out.

**Comment by Zillode** [comment]
> For instance, Android client uses the official Android API for this, and I am not sure if inotify would work there (it might).

This works, The Syncthing-Silk Android app uses it this way.
The following platforms are supported:
>   "darwin" => ["amd64"],
  "dragonfly" => ["amd64"],
  "freebsd" => ["386", "amd64", "arm"],
  "linux" => ["386", "amd64", "arm"],
  "netbsd" => ["386", "amd64"],
  "openbsd" => ["386", "amd64"],
  "windows" => ["386", "amd64"]

So there is only linux-ppc* and solaris missing. However, it seems the upstream package recently implemented [support for solaris](https://github.com/rjeczalik/notify/issues/86).

The only real limitation that I see is that the OSX build requires native compilation.

**Comment by calmh** [comment]
That's fine, we build natively for the big platforms anyway, and so probably do the people developing on them.

**Comment by justinmayer** [comment]
If anyone is wondering as to the status of this effort, you might want to have a look at #2807.

**Comment by tsaridas** [comment]
+1

**Comment by AudriusButkevicius** [comment]
Please stop +1, there are emote buttons you can use on the main post.

**Comment by imsodin** [comment]
Completely forgot to look for issues before: First stage towards this has been merged in #3986

The first RC with it is yet to be released and it will at first be in a kind of testing phase, meaning it is not in the folder edit dialog and will be disabled by default. If you feel adventurous (it works for me) you will be able to activate it in advanced settings.

**Comment by AudriusButkevicius** [comment]
@imsodin we should close this and you should claim it.

**Comment by imsodin** [comment]
@AudriusButkevicius claim?

I guess we could close this and open a new one for the UI integration.

**Comment by AudriusButkevicius** [comment]
@imsodin there is a bounty on bountysource

**Comment by imsodin** [comment]
Oh, that's actually some money there. I haven't used it before so I don't know the usual procedure. The money is mainly from @calmh so I guess it's his call whether this should be closed now or when the UI is done. Also the original code was by @plouj (to whom the final squashed commit was attributed to ;) ).

**Comment by calmh** [comment]
Yeah the squash could have been done better, at least as two commits. @plouj should have all credit for his work, but as usual 80% of the work is in the last 20% and in actually surviving the review process... you should claim it as is, I think, and buy @plouj a couple of beers at some opportune time.

Let’s get the UI sorted out for .42 or thereabouts, I think there is a good start on it ready. I’m going to write a ticket with my thoughts on it.

**Comment by plouj** [comment]
For the record seeing this feature finally merged and knowing that I helped along the way is enough of a reward for me.

@imsodin: good job with surviving the review process!

(I'm not much of a beer person so if someone really must get me something then you can gift me a co-op game or two from my steam wishlist: http://steamcommunity.com/id/plouj/wishlist/)

**Comment by imsodin** [comment]
Games for plouj and beer for me sounds good :)
For reference: This is the UI issue: #4552
