### ISSUE TITLE
Synthing appears not synced, global state different on both, last seen days ago

### ISSUE THREAD

**Issue by chrisbramley** [syncthing/syncthing#2742]
Hi

I've had massive trouble setting this on two Synology NAS's. For 6 folders totalling about 1.8TB it has taken literally months to index. Finally both are saying up to date... but they are not. one is missing nearly 100GB from one folder, the other is missing more than that from a different folder. They both show up to date. Last seen is ?. 

Rescan does nothing. I have tried pausing to resume but they will not pause. CPU is hovering around 30% av. with a rescan interval of 3600 (the NAS boxes aren't beefy). I have restarted both boxes more than once. Local states and Global states don't match on the devices. For a short while one wouldn't start because I accidentally removed a < from the config.xml in vi but I replaced it and it starts fine now.

![sync1](https://cloud.githubusercontent.com/assets/12978721/12641102/9853466c-c5a5-11e5-931f-2146f86cb808.PNG)

![sync2](https://cloud.githubusercontent.com/assets/12978721/12641109/9dee3fdc-c5a5-11e5-8d47-e6a611e06205.PNG)

Any thoughts/advice? I have been working at getting this going for literally about 4 months now, it's quite frustrating (an update broke one, I had to restart syncing, etc). 

Cheers.

**Comment by AudriusButkevicius** [comment]
So this is most likely a misconfiguration. 
Please open a thread on the forum so that a wider audience could help.
