### ISSUE TITLE
On-the-fly GUI override option does not work with new theme select option

### ISSUE THREAD

**Issue by norgeous** [syncthing/syncthing#2746]
Using the theme override option indicated here:
https://forum.syncthing.net/t/custom-gui-mockups-and-programming/2921/17
to develop a theme in Syncthing `v0.12.16`...

I copy a file:
https://github.com/syncthing/syncthing/blob/master/gui/default/assets/css/overrides.css

to:
`C:\Users\User\AppData\Local\Syncthing\gui\default\assets\css\overrides.css`
but nothing happens in the GUI instance...

moving the file to:
`C:\Users\User\AppData\Local\Syncthing\gui\assets\css\overrides.css` (removed `\default`)
and now it works!, but selecting different themes has no effect (the override file is applied regardless of theme)

I imagine that the new(er) Theme manager and GUI file override do not work together...

Ideally It would function as follows:

1) I create a new folder at `C:\Users\User\AppData\Local\Syncthing\gui\mynewtheme`
2) This causes a new theme to show in the drop down select `Actions > Settings > GUI Theme`, initially as the folder is empty (no overrides) Syncthing just uses the default theme files.
3) I download any file from: https://github.com/syncthing/syncthing/blob/master/gui/default/ to this folder to override default theme files
4) Coding happiness

**Comment by AudriusButkevicius** [comment]
Override is for overriding, not for complimenting or adding additional themes.

**Comment by AudriusButkevicius** [comment]
Closing this.
If you have a theme you'd like to see, make a pull request, and let's make it part of the normal release.
