### ISSUE TITLE
Kobo - Cannot start GUI

### ISSUE THREAD

**Issue by cascafico** [syncthing/syncthing#2751]
Hello!

I downloaded and copied syncthing-linux-arm-v0.12.16 on Kobo ereader [1].
Once launched:

```
[monitor] 18:34:22 INFO: Starting syncthing
[start] 18:34:22 INFO: Generating ECDSA key and certificate for syncthing...
[KGBNT] 18:34:23 INFO: syncthing v0.12.16 "Beryllium Bedbug" (go1.5.3 linux-arm) unknown-user@build2.syncthing.net 2016-01-24 07:09:28 UTC
[KGBNT] 18:34:23 INFO: My ID: KGBNT5F-5JKQZIZ-U6V2NCS-HO2I3W4-EUYF6MY-DVYOAXS-J3J2FK3-G6HJAQ5
[KGBNT] 18:34:24 INFO: Single thread hash performance is ~7.8 MB/s
[KGBNT] 18:34:24 INFO: Error loading config file; using defaults for now
[KGBNT] 18:34:24 INFO: Default folder created and/or linked to new config
[KGBNT] 18:34:24 FATAL: get free port (GUI): listen tcp 127.0.0.1:0: bind: cannot assign requested address
[monitor] 18:34:24 INFO: Syncthing exited: exit status 1

```
after other 3 attempts, synching informs: "not retrying further"

[1] kobo> uname -a
Linux (none) 2.6.35.3-850-gbc67621+ #617 PREEMPT Mon Apr 22 11:07:47 CST 2013 armv7l GNU/Linu

**Comment by calmh** [comment]
Sounds like you may be missing a loopback adapter or aren't allowed to create listening sockets. What does `ifconfig -a` print?

**Comment by 0r0** [comment]
There is no local interface on the Kobo by default.  This may be helpful for getting Syncthing started on the Kobo:  http://www.mobileread.com/forums/showpost.php?p=3243942&postcount=20

Also, there is a Syncthing installer for Kobo Start Menu that includes a script to enable the local interface and enable/disable Syncthing here:  http://www.mobileread.com/forums/showpost.php?p=3244608&postcount=82

**Comment by calmh** [comment]
:+1: Further discussion on the forum, if you like.
