### ISSUE TITLE
Moving content between two root folders causes re-upload

### ISSUE THREAD

**Issue by indrora** [syncthing/syncthing#2754]
In a hypothetical situation, if I have the two root folders

* camera-pictures
* camera-archive

and I move files from inside `camera-pictures` to `camera-archive`, the node that has the now newer filesystem change will have to push the files from `camera-archive` to the other nodes in the network. This creates unneccesary disk IO, network access, and generally makes it a bit of a hassle.

Suggestion: SyncThing should check adds and removes to see if the files are the same, evaluating adds before deletes, merging adds + deletes as moves (under the "reused" category).

**Comment by calmh** [comment]
We do that, but there is no synchronization between folders. You can set different scan intervals for them, and even if they are they same there is no guarantee that we won't see all the deletes before seeing the additions to the other folder.

To ensure zero transfer renames, they need to happen within a folder.

**Comment by indrora** [comment]
When using `syncthing-inotify` or synctrayzor, these changes are immediately synchronized. As a result, scan intervals have little meaning. 

This means that if a file exists in one folder and then suddenly exists in another and suddenly vanishes from the first, syncthing does not see that. This is actually easier to handle in a way not on the (now) out of date systems but on the (now) up to date system by invoking a scan and looking for the files that were deleted on a previous scan.

If there was a way that synctrayzor or `syncthing-inotify` could say "a file was moved from folder A to folder B" that would really be helpful.

On February 2, 2016 2:04:00 AM MST, Jakob Borg <notifications@github.com> wrote:
>We do that, but there is no synchronization between folders. You can
>set different scan intervals for them, and even if they are they same
>there is no guarantee that we won't see all the deletes before seeing
>the additions to the other folder.
>
>To ensure zero transfer renames, they need to happen within a folder.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/syncthing/syncthing/issues/2754#issuecomment-178456449

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by calmh** [comment]
> This means that if a file exists in one folder and then suddenly exists in another and suddenly vanishes from the first, syncthing does not see that.

This results in two scan requests, essentially at the same time: one on the deleted file and one on the new one. The delete takes very little time to scan (obviously) so it gets sent to the other device and executed. At some later point we finish scanning the new file and send the block list to the other device. But the original file is already deleted.
