### ISSUE TITLE
Consider using a faster globber for ignores

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2756]
https://github.com/gobwas/glob looks good, faster than our regexp-based version.

**Comment by canton7** [comment]
Keep compatibility with the third-party file watchers in mind.

I use the ignores to decide whether to alert Syncthing of a changed file: switching away from regexes will break this. That may be fine, but we (and I assume anyone else who's written a filesystem watcher) will need to coordinate.

**Comment by calmh** [comment]
Are you using the compiled regex patterns for this? Retrieved from the REST API?

**Comment by canton7** [comment]
Yes.

**Comment by calmh** [comment]
I guess that serves us right for exposing it... That was intended as debug output for humans. Ah well.

**Comment by canton7** [comment]
I can alert you for every file change, even for ignored files, if you'd rather: returning nothing in the REST API here (or removing those properties outright) would do that.

**Comment by calmh** [comment]
Okay, noted.

**Comment by canton7** [comment]
... but I don't know if things like Syncthing-GTK will be affected.

**Comment by calmh** [comment]
Yeah. Until then, it would necessarily be an API change anyhow.

**Comment by AudriusButkevicius** [comment]
Dhone!
