### ISSUE TITLE
feature request: tooltips for folder paths in folder preferenes (WebGUI)

### ISSUE THREAD

**Issue by sisu4syncthing** [syncthing/syncthing#2758]
Hi,
for those, who want to know the exact path, this would be vey helpful (because you save clickings to/from the Edit-window).
![screenshot](https://cloud.githubusercontent.com/assets/12977080/12820455/6d89cb94-cb5f-11e5-8c96-b15c77c81425.png)
Cheers!

**Comment by AudriusButkevicius** [comment]
Is there not an alt text on that?

**Comment by sisu4syncthing** [comment]
Hmm. The above screenshot was taken from FireFox 43, which does not show a Tooltip there (I did a restart to be sure). Howevery, it shows Tooltips in the "out of sync" Window.

On the other hand, tooltips are shown within Safari 9, so there must be alt-texts...
![safari](https://cloud.githubusercontent.com/assets/12977080/12821775/2bfa7a4c-cb65-11e5-8a47-76d8570721d0.png)

So I guess, its a local problem...? yes, I guess...

**Comment by wweich** [comment]
>Is there not an alt text on that?

Nope. Just tested with Firefox and Chrome (no Safari/Mac OS here).
There is no `alt` / `title` tag in the DOM. Safari probably makes its own tooltip to show the complete content of the `td`.
For "last file received" there is a `title` tag in the DOM.
