### ISSUE TITLE
More thorough description of AutoNormalize

### ISSUE THREAD

**Issue by entonio** [syncthing/syncthing#2759]
Hi. I've been happily using Syncthing for a variety of purposes. Most of the times I use it to create mirrors of read-only folders. Recently I've set it up to mirror some windows server shares that are read-only.
- I manually create the .stfolder and maintain the .stignore, since syncthing cannot write to the share. Apparently that works like a charm.
- Syncthing often complains about being unable to normalize UTF8 file names it comes across. I understand that even setting the folder up as 'master', normalizing filenames is a separate issue. I could set AutoNormalize to false and avodi the warning, but I'd like to understand what I'm missing.
- The files certainly weren't processed by a Mac. Most of them were created by Windows 8.1 or XP and stored directly in the Windows Server 2008 R2 shares.
- The reason the shares are read-only is that I really don't want tthem to be written to automatically by anyone.

Now, I know that there can be more than one Unicode representation for a given character, so I think I understand the rationale behind normalizing the names. However:
- I'd like to know what normalization is performed, so I could judge on my own whether I can temporarily given RW access to the shares so as to have them normalized without worrying.
- Couldn't the normalization be wholly internal to Syncthing, instead of changing the file entries themselves? That would sound much, much better to me.

Thanks for an awesome product!

**Comment by AudriusButkevicius** [comment]
OS-X uses NFD for others we assume it uses NFC.
We convert them to UTF-8 as far as I understand.

**Comment by entonio** [comment]
I'm not sure about the conversion to UTF8; afaict UTF8 deals with representing 'code points' as bytes, whereas NFC/NFD deal with representing 'characters' as 'code points'. Normalization is a complex issue and if you ask me (ha!) I'd say that if filesystems choose to ignore it (they just care about bytes, and it's not their problem if different byte sequences result in visually equal strings), then so should a filesystem-related utility such as Syncthing. That's of course not an option if the target system decides to change the filename bytes - my impression is that at least NTFS doesn't, but I have no idea about the others - since then unintended duplication might occur. I assume that was your rationale.

I have a suspicion that the 'problem files' were created via a remote desktop connection, with all the software running on a Windows machine but the user connecting from a Mac. It's not the NFD vs NFC thing, but the keyboard input itself was normalized in yet another way to be sent to the destination. I'll try to use only ASCII filenames in that scenario in the future.

You do a very nice job answering folk's questions here, Audrius! Seldom do we come across a project where folks are so patient towards the public :)
