### ISSUE TITLE
Export and Import Share Settings

### ISSUE THREAD

**Issue by stormdragon2976** [syncthing/syncthing#2761]
Would it be possible to add the ability to export your shared deviccs and folders? When installing on a new computer, you could then just import the file of devices and directories, and the people would get requests to share with your new device. Also, as a side note, it would be awesome if you could add a message when sending a request to share a device or directory. E.g. directory name "notes" directory path "/my/notes" message (optional) "Thanks for helping with these notes".

**Comment by MyPod** [comment]
you can move the config directory, which contains the config file and the certificates

**Comment by AudriusButkevicius** [comment]
Yes, what @MyPod said. The location where they live is shown in -help.
