### ISSUE TITLE
Use of go 1.5 vendoring of dependencies

### ISSUE THREAD

**Issue by djc** [syncthing/syncthing#2762]
We're trying to package Syncthing in Gentoo. In doing so, we're interested in unbundling some of the dependencies to that they can be managed centrally. Are you going to use the Go 1.5 vendoring strategy (https://golang.org/s/go15vendor)? That would really help us package Syncthing sanely.

**Comment by williamh** [comment]
Go 1.6 will by default have this feature activated, and it will help us much with packaging because we will not have to worry about the build system attempting to go to the network and retrieve dependencies.
In Go 1.5, you can turn this on by adding GO15VENDOREXPERIMENT=1 to the environment.

**Comment by AudriusButkevicius** [comment]
Why does the current method of vendoring not work?

**Comment by williamh** [comment]
I could be doing something wrong, but when I set GOPATH and change to the syncthing directory and run

go run build.go

 it seems that build.go downloads dependencies from the network
If you use the go1.5 vendoring, I don't think the dependencies are downloaded automatically.

I just noticed the no-upgrade switch to build.go. Should I use that to stop the downloading?

**Comment by calmh** [comment]
build.go uses "go build" and "go install", neither of which download dependencies. All needed dependencies are bundled. I don't want to use 1.5 vendoring just yet as we still support building with 1.3+.
