### ISSUE TITLE
Tooltips in browser (Out of Sync Items): some show path, some not. Please include FULL path.

### ISSUE THREAD

**Issue by sisu4syncthing** [syncthing/syncthing#2763]
Hi,
(win7 64bit, firefox 43.x, st 0.12.17)

please see the screenshots. First shows tooltip w/ path, second w/o.

Problem is, I cannot see, WHERE the files are located.

I'm on a machine, which acts as a **master folder**, so the conflicting files can be anywhere else but on this machine. But where? (Other WebGUIs don't show any conflicting files...)

My humble wish: With a lot of conflicting files, I'd like to know exactly, where they are. 
A lot syncthing clients can have those files, but the "master" just shows poor info about them. 

Without a path, its very hard to find a specific file.
![m](https://cloud.githubusercontent.com/assets/12977080/12870585/3349ed26-cd4c-11e5-84fb-7efdb3df0702.png)
![o](https://cloud.githubusercontent.com/assets/12977080/12870586/334d1e92-cd4c-11e5-8dcc-4e64b5bdb92b.png)

Also, it would be nice, if the empty space would be used for a longer more readable filename:
![s](https://cloud.githubusercontent.com/assets/12977080/12870604/64cfce64-cd4d-11e5-9dae-253a36e9d2f8.png)

**Comment by AudriusButkevicius** [comment]
I don't understand. it tells you it's in ini\usr.

**Comment by sisu4syncthing** [comment]
yes, "ini\usr" but on **what** machine?
and what about the tooltips which does not show a path? 
this is confusing, imho.

**Comment by AudriusButkevicius** [comment]
The ones that do not show a path imply at the root.
There is no such concept of `which machine`, it's probably all of them which do not have master enabled.

**Comment by sisu4syncthing** [comment]
Thank you for clarifying the concept of "which machine". 
From a user perspective, this seems odd, because if syncthing knows of any conflicting files, it should know, from where... but ok, thats the way it works obviously.

For the pull request: I need to read what that is and how it is done. Thank you.
