### ISSUE TITLE
Add info (Days for Maximum Age) on Folders List in WebGUI

### ISSUE THREAD

**Issue by sisu4syncthing** [syncthing/syncthing#2764]
Hi,
can we have a small additional info (Maximum Age in Days) to save 2 clicks and see useful info directly on the sceen?
Like on the screenshot (red color text on).

![d](https://cloud.githubusercontent.com/assets/12977080/12870678/75e2c2bc-cd50-11e5-9a9f-49d262b9741b.png)

reason is, that user might want to equalize some of their folderprefs and then the user can see settings without clicking a lot.

**Comment by AudriusButkevicius** [comment]
No, it's already cluttered enough.
