### ISSUE TITLE
Tests don't work on 32-bits architectures

### ISSUE THREAD

**Issue by djc** [syncthing/syncthing#2765]
When running the tests with `go run build.go test`, I get an error:

`go test: -race is only supported on linux/amd64, freebsd/amd64, darwin/amd64 and windows/amd64`

It  would be nice if the tests could also run on old-school 32-bits systems. Maybe it can run without `-race` in those cases?

**Comment by calmh** [comment]
In the meantime, `GOPATH=$(pwd)/Godeps/_workspace:$GOPATH go test ./...`
