### ISSUE TITLE
Conflict Resolver feature request

### ISSUE THREAD

**Issue by jult** [syncthing/syncthing#2772]
Just one button to select ALL files with the newest modification date for keeping and delete all older ones?
Or, better yet, an option to have syncthing do that without prompting the user about conflicts?

**Comment by AudriusButkevicius** [comment]
It already does that by default (resolves based on newer mtime), and I think you can set a folder to keep 0 conflict files in advanced config.

**Comment by AudriusButkevicius** [comment]
If 0 keeps unlimited conflicts, let me know and I'll reopen it.
