### ISSUE TITLE
CPU usage (debian)

### ISSUE THREAD

**Issue by bombazook** [syncthing/syncthing#2775]
Seeing such peaks (eats 100% of 1 vc) every minute (rescan interval) on Debian 4.8.4-1 with 3.16.0-4-amd64 kernel. It's running under QEMU on 2 vcores. VM uses 2x500Gb logical volumes through virtio with ~300Gb of data. I added 2 folders (one for each of mounted volumes). 
Syncthing version is v0.12.18 "Beryllium Bedbug" (go1.5.3 linux-amd64)
I expected not to use so much cpu for rescan on 300Gb of data without changes. Looks like an issue.
All other VMs are idle at the same time (second screenshot).
Also have a discosrv running under another machine in the same subnet.
Syncthing logs are empty.
![2016-02-11 22 08 03](https://cloud.githubusercontent.com/assets/451327/12987454/2ecacbd4-d10d-11e5-95a3-dcc3e6b7b690.png)
![2016-02-12 0 27 58](https://cloud.githubusercontent.com/assets/451327/12991580/c4c73984-d120-11e5-9cb2-fe9d1d31fc31.png)

**Comment by AudriusButkevicius** [comment]
Are you sure it's syncthing causing the CPU usage and not the kernel/fs while we are issuing a bunch of stat calls?

**Comment by bombazook** [comment]
Used 'top' to measure cpu consumption during one of that moments
![2016-02-12 2 15 49](https://cloud.githubusercontent.com/assets/451327/12994017/a71429de-d12e-11e5-8cff-c9a1eb987b8c.png)

**Comment by AudriusButkevicius** [comment]
Run it with STTRACE=scanner,model and provide the logs at the point the high CPU happens.

**Comment by calmh** [comment]
Also look at the top line stats in top. "us" is us, "sy" is the system, "wa" is waiting for IO. If the majority is in the latter two categories, that could be because the IO is slow and we're essentially waiting for the disks, virtual or not.

<img width="649" alt="screen shot 2016-02-12 at 08 41 09" src="https://cloud.githubusercontent.com/assets/125426/13001276/6bc4eda6-d164-11e5-822b-699d68bcdfca.png">

**Comment by AudriusButkevicius** [comment]
See #2776 as well.

**Comment by bombazook** [comment]
Made some tests and figured out that cpu usage grows almost linearly with files count.
Log with scanner trace looks like:

> Feb 24 19:17:12 photo syncthing[26813]: [DBHPD] DEBUG: Walk /storage/home/a/sync/ [] 131072 &{[] true 0xc821ea71a0 d41d8cd98f00b204e9800998ecf8427e 0xc8215cd7a0 0xc821c86880}
Feb 24 19:17:12 photo syncthing[26813]: [DBHPD] DEBUG: checkDir /storage/home/a/sync/ &{sync 4096 2147484157 {63591925748 601392410 0x104aa20} 0xc820fe1440}
Feb 24 19:17:12 photo syncthing[26813]: [DBHPD] DEBUG: ignored: .stfolder
Feb 24 19:17:14 photo syncthing[26813]: [DBHPD] DEBUG: Walk progress done /storage/home/a/sync/ [] 131072 &{[] true 0xc821ea71a0 d41d8cd98f00b204e9800998ecf8427e 0xc8215cd7a0 0xc821c86880}

>Feb 24 19:17:22 photo syncthing[26813]: [DBHPD] DEBUG: Walk /storage/home/b/sync/ [] 131072 &{[] true 0xc8223016a0 d41d8cd98f00b204e9800998ecf8427e 0xc821f23560 0xc821268750}
Feb 24 19:17:22 photo syncthing[26813]: [DBHPD] DEBUG: checkDir /storage/home/b/sync/ &{sync 4096 2147484157 {63590732439 632000000 0x104aa20} 0xc821e74900}
Feb 24 19:17:22 photo syncthing[26813]: [DBHPD] DEBUG: ignored: .stfolder
Feb 24 19:17:22 photo syncthing[26813]: [DBHPD] DEBUG: Walk progress done /storage/home/b/sync/ [] 131072 &{[] true 0xc8223016a0 d41d8cd98f00b204e9800998ecf8427e 0xc821f23560 0xc821268750}

>Feb 24 19:17:45 photo syncthing[26813]: [DBHPD] DEBUG: Walk /storage/home/c/sync/ [] 131072 &{[] true 0xc821ea65a0 d41d8cd98f00b204e9800998ecf8427e 0xc821ec5b60 0xc820428a30}
Feb 24 19:17:45 photo syncthing[26813]: [DBHPD] DEBUG: checkDir /storage/home/c/sync/ &{sync 4096 2147484157 {63590739947 724000000 0x104aa20} 0xc82138e5a0}
Feb 24 19:17:45 photo syncthing[26813]: [DBHPD] DEBUG: ignored: .stfolder
Feb 24 19:17:45 photo syncthing[26813]: [DBHPD] DEBUG: Walk progress done /storage/home/c/sync/ [] 131072 &{[] true 0xc821ea65a0 d41d8cd98f00b204e9800998ecf8427e 0xc821ec5b60 0xc820428a30}

On 130000 files (about half of number that I tested before) cpu usage looks like
![2016-02-24 19 24 23](https://cloud.githubusercontent.com/assets/451327/13292462/e8aed80a-db2c-11e5-9a59-844fd759418f.png)
![2016-02-24 19 31 03](https://cloud.githubusercontent.com/assets/451327/13292541/3e857fc2-db2d-11e5-807d-a53e12bdeba4.png)

There are absolutely no file changes between scans.

Also found discussion about issue that looks similar  https://forum.syncthing.net/t/cpu-usage-on-large-folder/6744/25

**Comment by bombazook** [comment]
"Model" mode of sttrace adds such lines between rescans:
> Feb 24 19:51:56 photo syncthing[26857]: [DBHPD] DEBUG: rwFolder/a_folder@0xc8204e4500 skip (curVer == prevVer) 0 true
Feb 24 19:52:04 photo syncthing[26857]: [DBHPD] DEBUG: rwFolder/b_folder@0xc82152fe00 skip (curVer == prevVer) 0 true
Feb 24 19:52:04 photo syncthing[26857]: [DBHPD] DEBUG: rwFolder/c_folder@0xc82152ef00 skip (curVer == prevVer) 0 true
Feb 24 19:52:06 photo syncthing[26857]: [DBHPD] DEBUG: rwFolder/a_folder@0xc8204e4500 skip (curVer == prevVer) 0 true
Feb 24 19:52:14 photo syncthing[26857]: [DBHPD] DEBUG: rwFolder/b_folder@0xc82152fe00 skip (curVer == prevVer) 0 true
Feb 24 19:52:14 photo syncthing[26857]: [DBHPD] DEBUG: rwFolder/c_folder@0xc82152ef00 skip (curVer == prevVer) 0 true
Feb 24 19:52:16 photo syncthing[26857]: [DBHPD] DEBUG: rwFolder/a_folder@0xc8204e4500 skip (curVer == prevVer) 0 true
Feb 24 19:52:24 photo syncthing[26857]: [DBHPD] DEBUG: rwFolder/b_folder@0xc82152fe00 skip (curVer == prevVer) 0 true
Feb 24 19:52:24 photo syncthing[26857]: [DBHPD] DEBUG: rwFolder/c_folder@0xc82152ef00 skip (curVer == prevVer) 0 true
Feb 24 19:52:26 photo syncthing[26857]: [DBHPD] DEBUG: rwFolder/a_folder@0xc8204e4500 skip (curVer == prevVer) 0 true
Feb 24 19:52:34 photo syncthing[26857]: [DBHPD] DEBUG: rwFolder/b_folder@0xc82152fe00 skip (curVer == prevVer) 0 true
Feb 24 19:52:34 photo syncthing[26857]: [DBHPD] DEBUG: rwFolder/c_folder@0xc82152ef00 skip (curVer == prevVer) 0 true
Feb 24 19:52:36 photo syncthing[26857]: [DBHPD] DEBUG: rwFolder/a_folder@0xc8204e4500 skip (curVer == prevVer) 0 true
Feb 24 19:52:44 photo syncthing[26857]: [DBHPD] DEBUG: rwFolder/b_folder@0xc82152fe00 skip (curVer == prevVer) 0 true
Feb 24 19:52:44 photo syncthing[26857]: [DBHPD] DEBUG: rwFolder/c_folder@0xc82152ef00 skip (curVer == prevVer) 0 true
Feb 24 19:52:46 photo syncthing[26857]: [DBHPD] DEBUG: rwFolder/a_folder@0xc8204e4500 skip (curVer == prevVer) 0 true

and notifications about beginning and end of rescan:
> Feb 24 19:52:47 photo syncthing[26857]: [DBHPD] DEBUG: rwFolder/a_home@0xc8204e4500 rescan
...
Feb 24 19:52:49 photo syncthing[26857]: [DBHPD] DEBUG: rwFolder/a_home@0xc8204e4500 next rescan in 1m14.621706234s

 without additional info

**Comment by AudriusButkevicius** [comment]
It seems that the CPU load happens basically from accessing the database, thats the only thing that comes to mind. You could run cpu profiler to see where most of the time is spent. -help explains how.

**Comment by bombazook** [comment]
Made some profiling and got such graph.
[callgraph.pdf](https://github.com/syncthing/syncthing/files/147031/callgraph.pdf)
May I ask you to help with that?

**Comment by AudriusButkevicius** [comment]
Yeah, as I suspected most of it is database access and compression. Let's see if @calmh has any ideas, but I feel that there is not much we can do.

**Comment by AudriusButkevicius** [comment]
Also, please make sure the file does not disappear until @calmh had a chance to look at it.

**Comment by acmodeu** [comment]
Looks like I'm also having exactly the same issue with my VM debian. CPU increased usage correlates with syncthing activity.
![debian](https://cloud.githubusercontent.com/assets/17564574/13421628/8ee71cba-dfa0-11e5-8889-351a37c2332f.PNG)

**Comment by calmh** [comment]
That CPU time is all database lookups, yes, which we need to do one pre file we see plus one for each file in the database (that's an iterator, not lookup, but same-same). This is functions-as-designed as far as I'm concerned. Graphs look like a few CPU seconds on each scan; 100% is what we get as we're CPU limited.
