### ISSUE TITLE
400% CPU usage for several minutes when connecting

### ISSUE THREAD

**Issue by vanzomerenc** [syncthing/syncthing#2776]
I have a fairly small (60 MB) folder synced on my home network. Whenever one of my computers loses connection, is reconnected or resumes from suspend, or when syncthing is restarted, everything on that computer stops for several minutes while Syncthing scans the synced folder at 200-400% CPU usage. Last time this happened, it lasted about 6 minutes.

This is regardless of the folder being in or out of sync.

Another folder with over 1 GB of files and a larger number of files syncs within seconds. Unsharing the 60 MB folder "fixes" the issue.

**Comment by calmh** [comment]
That doesn't sound like scanning. This 60 MB folder, does it have, or have had, millions of files or so in it? Maybe over time (i.e. you only have 100 files there, but they are deleted and replaced with other files every day)?

**Comment by vanzomerenc** [comment]
Edited the 

The folder has 303 items, and they aren't updated very often. (it's just a "my documents" folder of sorts)

At one point, it did have several million files due to a mistake using mv, but these were all removed.

Are removed files still tracked once they've been synced?

**Comment by calmh** [comment]
Yep, as we need to tell other devices who may have an older copy of the folder that they should be deleted. There's a ticket somewhere on the future optimization of removing these from the index once we know all nodes are up to date - but knowing that is difficult in the general case. 

In the meantime, a workaround is to remove the folder on all devices, restart to clean the index, then add the folder again.
