### ISSUE TITLE
WebUI lock out with non-ASCII password

### ISSUE THREAD

**Issue by noerw** [syncthing/syncthing#2779]
So I just had the great experience of not being able to access the web UI of my syncthing instance after setting a password (`v0.12.18`).
After resetting the password in config.xml and a bit of testing I found out, it was because of an umlaut (one of those `ä`, `ö`, `ü` characters) in the password.
I suppose, any non ASCII character is not supported.

The dialog for setting a web ui login is not great anyway. Changes should be at least one of the following:

- enable any character in the password
- check if the password is valid before setting it
- require the user to enter the password twice

**Comment by calmh** [comment]
I guess this is an effect of the browser not using the same character encoding on our settings page (utf-8, hopefully, as we request that) and when it then sends the basic auth header. Can you check if your browser default charset is something other than utf-8?

**Comment by calmh** [comment]
This seems spot on:

> Abandon all hope. Basic Authentication and Unicode don't mix.
> 
> There is no standard(*) for how to encode non-ASCII characters into a Basic Authentication username:password token before base64ing it. Consequently every browser does something different:
> 
> - Opera uses UTF-8;
> - IE uses the system's default codepage (which you have no way of knowing, other than it's never UTF-8), and silently mangles characters that don't fit into to it using the Windows ‘guess a random character that looks a bit like the one you wanted or maybe just not’ secret recipe;
> - Mozilla uses only the lower byte of character codepoints, which has the effect of encoding to ISO-8859-1 and mangling the non-8859-1 characters irretrievably... except when doing XMLHttpRequests, in which case it uses UTF-8;
> - Safari and Chrome encode to ISO-8859-1, and fail to send the authorization header at all when a non-8859-1 character is used.

(http://stackoverflow.com/questions/702629/utf-8-characters-mangled-in-http-basic-auth-username#answer-703341)

Indeed, it works fine with test/råksmörgås as user/pass in curl, but Safari fails. I'm unsure if we can do anything sensible about this.

**Comment by calmh** [comment]
Actually we could probably get quite far by attempting to verify it as utf-8; if this succeeds, it's very likely either utf-8 or ascii. If it fails, it's probably iso-8859-1 (as that isn't valid utf-8) and we try that.

**Comment by AudriusButkevicius** [comment]
So let's just limit it to ASCII in the web ui and be done with it.

**Comment by canton7** [comment]
Not hugely friendly to people in cultures that regularly use non-ascii characters, but unless we move away from basic auth there's probably not a lot we can do...

**Comment by calmh** [comment]
I don't think we should limit it; a warning is fair, along the lines of `Passwords containing characters not in A-Z may not work in all browsers`, and then us doing our best to parse it as either utf-8 or iso-8859-1. It won't be many lines of code.

**Comment by noerw** [comment]
woah, now thats an elaborate fast response! :+1:

i'd be happy, if there just was some userfeedback when setting a pw. 
Also, i mistrust myself without retyping the pw, so a second field could be added. 

on a sidenote: why are some options doubled in 'settings' and 'advanced settings'? :o

**Comment by calmh** [comment]
All options are in "advanced", it's essentially just a config file editor so everything that's in the config is visible in there. A subset of the options are visible in the "normal" dialogs - mostly everything non-dangerous and reasonably common.

**Comment by pizzamaker** [comment]
I ran into the same issue. @noerw, could you tell me how you changed your login and password? I can't seem to find this config.xml file.

**Comment by canton7** [comment]
Run `syncthing -paths`, and see the "Configuration file" entry.

On Windows, it's normally `C:\Users\<You>\AppData\Local\Syncthing\config.xml`, on Linux I believe it's `~/.config/syncthing.config.xml`

**Comment by pizzamaker** [comment]
Thanks, that did it!

**Comment by canton7** [comment]
Should we warn about non-ASCII passwords in the UI, when the user sets them?

**Comment by calmh** [comment]
Probably a good idea, yes. Looking back at my paste above, this should handle things now for western scripts except in IE, but that's still quite limited. No idea how asian etc scripts are handled.
