### ISSUE TITLE
Error handling root synced folder symbolic link when ~ used for path on Linux

### ISSUE THREAD

**Issue by PrototypeNM1** [syncthing/syncthing#2782]
I noticed this issue when trying to share SyncThing configuration on a dual boot system. Both Windows and Linux have the SyncThing config folder symbolically linked to a folder on a shared partition.

The synced folder is also being linked to on Linux and Windows each with a symbolic link ~/SyncedFolder.

On Windows this is parsed with no issue. On Linux this does not work with an error saying the symbolic link is not a folder. The error does not occur if the full home path is specified - e.g. /home/username/SyncedFolder.

So issue seems to stem when parsing ~ when the destination folder is a symbolic link to the synced folder. The full error is "/home/username/SyncedFolder: not a directory" when the path specified is ~/SyncedFolder. I've confirmed that the symbolic link was set up correctly under Linux.

**Comment by AudriusButkevicius** [comment]
Can you actually post the logs.

**Comment by PrototypeNM1** [comment]
By log do you mean the daemon output?

[stlog.txt](https://github.com/syncthing/syncthing/files/129443/stlog.txt)

**Comment by AudriusButkevicius** [comment]
I don't see the error you are talking about in the log.

**Comment by AudriusButkevicius** [comment]
Or is the folder as a whole symlinked?

**Comment by PrototypeNM1** [comment]
The folder structure is:
Linux:
/home/usernamee/SyncFolderName <- Symlink
/mnt/Shared/SyncFolderName <- Folder mount point
Path given to SyncThing (config shared between Windows and Linux):
~/SyncFolderName

I'm not sure if the above clarifies the setup, the issue is not syncing a symlink, it's SyncThing finding the root folder through a symlink when the path provided to SyncThing has a ~ in place of the full path the the symlink. If the full path to the symlink in the home directory is provided there is no error. The error only happens on Linux. If I create a new folder in home and specify the path as ~/newFolder to SyncThing it finds the folder without error.

If I create a folder now, symlink to it from the home directory, and then set it up in syncthing with a ~/symlinkToOtherFolder it works (note I have to edit this after setup in the advanced setting, ~ is automatically converted to /home/user/ in the add folder dialogue). If another computer shares a folder with me, the trying to set it up with the symlink produces the "not a folder" error which is only seen in the GUI, the only sign of it in the log is that the log repeatedly says an error is cleared for the affected folders.

**Comment by PrototypeNM1** [comment]
If you have any leads for where this might occur I'd be interested in investigating it. I'd guess it is probably an outdated check is occurring somewhere.

**Comment by AudriusButkevicius** [comment]
https://github.com/syncthing/syncthing/blob/master/lib/config/folderconfiguration.go#L139

**Comment by AudriusButkevicius** [comment]
Or https://github.com/syncthing/syncthing/blob/master/lib/model/model.go#L1774

**Comment by calmh** [comment]
This is probably a case of some code using a trailing slash and some not. When starting up we make sure to add one, as ~/foo/ will correctly be interpreted as the folder ~/foo is pointing to, but ~/foo itself is the symlink and will probably cause the "not a directory" error somewhere...

**Comment by PrototypeNM1** [comment]
So since SyncThing's code never has "not a directory" except where hardcoded in a different format from what I saw, the error is probably originating from a system call. It looks like "not a directory" is probably being pulled from one of the golang.org/x/sys/unix/zerrors_* files, in this case zerrors_linux_amd64.

Any recommended sources for how to navigate Go source code, something [like this ](https://www.youtube.com/watch?v=5Ymoav0nNWQ&index=1&list=WL) would be helpful.

**Comment by calmh** [comment]
If you run with `STTRACE=whatever` (literally whatever, it doesn't matter what the value is) you'll get a line number for where the error is printed. You should be able to backtrace that to where it comes from.

**Comment by PrototypeNM1** [comment]
Ok, so I'm pretty sure I've narrowed down the issue, but haven't been able to test and verify yet.

In [lib/scanner/walk.go line 489](https://github.com/syncthing/syncthing/blob/21e116aa45a3c09953a51ba2a4aead1be7360ed0/lib/scanner/walk.go#L489) isDir() I believe is returning false for symbolic links. I think the fix is to add a check for info.Mode() != FileMode.ModeSymlink. I'm not familiar enough to tell where else checkDir() is used and what impact this change would have, but if it is used for folders other than the root folder then I'd guess the fix would be to created a dedicated checkRootDir() which allows for symbolic links?
