### ISSUE TITLE
Tags are not signed by release key 00654A3E

### ISSUE THREAD

**Issue by siomiz** [syncthing/syncthing#2785]
I'd like a clarification:
https://syncthing.net/security.html only mentions that the `sha1sum.txt(.asc)` files are signed with `00654A3E`.
[README.md](https://github.com/syncthing/syncthing/blob/master/README.md) says the Git tags are also signed using the same key, but none of the v0.12.* tags are signed with `00654A3E`.

```
$ git verify-tag v0.12.19
gpg: Signature made Sun 14 Feb 2016 11:26:47 AM PST using RSA key ID BCE524C7
```
Which way is the Syncthing team going with?

ref. #1818

**Comment by calmh** [comment]
This is true, docs should be fixed. The hash files are signed by the release key, the tags are signed by whoever does the tagging (me, usually).

**Comment by siomiz** [comment]
That's all I needed to know... Thank you! :+1:
