### ISSUE TITLE
glibc vulnerability

### ISSUE THREAD

**Issue by dcarosone** [syncthing/syncthing#2786]
http://arstechnica.com/security/2016/02/extremely-severe-bug-leaves-dizzying-number-of-apps-and-devices-vulnerable/

The syncthing binary on linux is static.  I assume there's a copy of libc buried in there, perhaps indirectly via the go runtime (I'm not sure how that works).

I'm presuming this will need a release compiled with an updated glibc, again perhaps after a corresponding Go update.

**Comment by calmh** [comment]
The static binaries actually don't include (nor, obviously, link to) glibc. The Go runtime does syscalls directly and includes an internal DNS resolver.
