### ISSUE TITLE
rename() files instead of write-then-delete when syncing a rename

### ISSUE THREAD

**Issue by singpolyma** [syncthing/syncthing#2787]
Steps to reproduce:

1. Set up a folder synced between two syncthing instances
2. Add a file named `first` and let it sync to both devices
3. On device B, run: `while true; do echo '----'; ls first second; sleep 0.5; done`
4. On device A, run: `mv first second`
5. Observe in the output of the `ls` loop that both `first` and `second` files exist

Why would I care?  Because I have scripts monitoring the directory for changes, and they end up recording a duplicate.

Proposed fix: if we detect a file rename, propagate it on the remote side using `rename()` instead of add-then-delete

**Comment by AudriusButkevicius** [comment]
Are you using inotify?

**Comment by singpolyma** [comment]
@AudriusButkevicius you mean syncthing-inotify, or as part of my monitoring scripts?  I am using inotify as part of my monitoring.  Currently using `syncthing-inotify` only on one side of this sync operation.

**Comment by AudriusButkevicius** [comment]
I mean inotify to detect the move

**Comment by singpolyma** [comment]
@AudriusButkevicius You mean, do detect that syncthing does not seem to be using `rename()`?  No, I'm using the steps outlined above (ls in a loop).

**Comment by AudriusButkevicius** [comment]
But who reports to syncthing that that has happened, syncthings normal rescan or st-inotify?

**Comment by singpolyma** [comment]
@AudriusButkevicius in `step 4` above, syncthing detects that mv has happend through a normal rescan.  no st-inotify on that machine

**Comment by AudriusButkevicius** [comment]
Can you run with STTRACE=model on B and STTRACE=model,scanner on A and post logs.

**Comment by AudriusButkevicius** [comment]
FYI, by implementation, it already does use rename, hence why I need the logs.

**Comment by singpolyma** [comment]
Ok, so, I reproduced while running with the asked-for environment and sent output to a file.  The command I ran on A was `mv cur/1455816295.18130_0.iweb:2, cur/1455816295.18130_0.iweb:2,S` the syncthing folder name is `Mail`

Logs are named `.zip` to get Github to let me upload them :P  But they are `.xz` files

[A.log.zip](https://github.com/syncthing/syncthing/files/136665/A.log.zip)
[B.log.zip](https://github.com/syncthing/syncthing/files/136664/B.log.zip)

**Comment by AudriusButkevicius** [comment]
Please reproduce this in a contained environment with a single file, traversing megabytes of logs is no fun.

**Comment by singpolyma** [comment]
@AudriusButkevicius yeah, ok.  will do, sorry.  I'll try to get that set up

**Comment by AudriusButkevicius** [comment]
Sorry for being so demanding, but given you've defined the steps it shouldn't be too hard. I'll try to look at this this evening if the new logs are up.

**Comment by singpolyma** [comment]
So I ran clean syncthing instances with only one folder with only one file on my laptop and desktop at home, and the problem is not as "you can see it every time" as it was in my live environment, but I still reproduced it.  Attached are two logs where I sort of do `mv first second` and `mv second first` over and over until I verified with my `ls` loop that the issue had recurred for sure.  I've also attached a log of my `ls` loop to show that both first and second were in the directory (from the perspective of ls) at the same time.  Hopefully this is isolated enough, otherwise I will have to restart syncthing between each attempt to get less log.  Let me know.
[A.log.txt](https://github.com/syncthing/syncthing/files/137097/A.log.txt)
[B.log.txt](https://github.com/syncthing/syncthing/files/137098/B.log.txt)
[ls.log.txt](https://github.com/syncthing/syncthing/files/137099/ls.log.txt)

**Comment by AudriusButkevicius** [comment]
Ok, so imagine 2 threads.

So this is a race condition between us getting an update for 2 files, and then one by one writing to the database saying this needs updating, and another thread waking up and checking if there is anything to update.

This is rare enough that I don't think we care.

**Comment by AudriusButkevicius** [comment]
To be honest, I'll leave this open, and see what @calmh thinks.

**Comment by calmh** [comment]
I just read through this quickly but yeah we do renames as renames. However the reproduction looks like it's both changing the file and renaming it, which we don't detect as such.

**Comment by AudriusButkevicius** [comment]
So no, it's a race condition between adding each file within an index update to the db, and getting stuff we are missing from WithNeed. Essentially the IDX(in) had 2 files, but we only managed to put one in the index, as WithNeed is called.

**Comment by singpolyma** [comment]
I can reproduce this pretty quickly in my test environment, and it also happens often enough in my production system that I notice daily. So I don't think it's super-rare

**Comment by singpolyma** [comment]
So the BEP message does not contain the rename and the other side has to infer to do a rename and the DB update from the message is not done atomically so I doesn't always infer the rename should be done? Is that right?

How performance degrading would atomic database updates from the messages be?

**Comment by AudriusButkevicius** [comment]
It does always infer renaming, it does it by comparing files to be deleted with files to be updated. 

Imagine you update 10k files between rescan intervals, if you lock and do not allow anything to happen until you've written all 10k to the database, you are degrading performance. Where as the way it is now we can start downloading stuff even after 1 file was written.

But regardless, even locking wouldn't help, because you will not send a aingle message for all 10k files, you will send multiple, batches. Now if you start processing and downloading before all batches arrived, it's very possible that you will not be able to infer renaming. 

It's even worse 

Performance degrade would be in locking

**Comment by singpolyma** [comment]
Ok, so I can see the issue in that extreme case. Would be nice if the side where the change was made could infer rename. But even as it is, could there be some sort of middle ground where if a smallish number of files (this is reproducible with just 1, but allowing for a handful more would be nice) are changed that is atomic, but not waiting for 10K to be written? Even a few extra seconds (if it's that much) isn't going to kill you.

**Comment by AudriusButkevicius** [comment]
Well we had people raising tickets and screaming because we were waiting 5 seconds, so I don't there is a way to make everyone happy.

**Comment by singpolyma** [comment]
Wow... ok. That's weird.

What if there was an option on B on a folder "make updates atomic"?

**Comment by AudriusButkevicius** [comment]
What does that mean though? You still need to batch the 10k update into smaller updates, and the rename could consist of item 0 and item 9999 in the list. You have no clue how many batches you will see, so no idea how long to wait for, as we generate them and send them as we discover changes in the scanner, during the scan.

**Comment by singpolyma** [comment]
Right, but I assume some number of changes will be together in one message? So if the number of changes is just a handful, they would be in one message, so all that would be needed I atomic updates for single messages. Since the issue I'm seeing is caused by a race condition on B and not by batching.

It's unfortunate that large updates cannot be reasonably atomic, but if small (more common) ones could be that would be a big win.

**Comment by canton7** [comment]
Well if would be a win for your specific use-case. I can't help but imagine that fixing your tooling would be easier than any number of weird workarounds in Syncthing.

**Comment by singpolyma** [comment]
@canton7 I'm pretty sure "fix a race condition so a feature actually works" is not a "weird workaround" -- I understand that many use cases work without rename detection, any maybe syncthing can't really support I (because of the 10K update case), but it seems like supporting renames for small updates was already a goal (since the code is there) and it just has this bug that makes it fail often

**Comment by canton7** [comment]
I'd (as an outsider) say it's an optimization which occurs where it makes sense. I'm not sure I'd call it call it a "goal" in the sense that it's guaranteed behaviour: more that, where it's not too much effort, it's a nice optimization to make.

**Comment by singpolyma** [comment]
Ok, so, to return to an earlier line of questions, what if senders could detect renames and actually put the rename in the message?  Then B would see "first renamed to second" and would either (a) rename first to second or (b) pull second, depending on if it already had first.

I understand this is a much bigger change.  Just trying to feel out different parts of the problem space.

**Comment by canton7** [comment]
Senders can't detect renames without completing the scan first. We don't want to wait for the scan to complete before sending updates. This was discussed before.

**Comment by AudriusButkevicius** [comment]
The point about sending out batches still prevails, unless you don't send anything until scan is done, growing memory usage phenomenally.

**Comment by AudriusButkevicius** [comment]
So essentially, if you were to compile syncthing with the following value increased, you might have more chances of this not happening:

https://github.com/syncthing/syncthing/blob/master/lib/model/model.go#L1101

**Comment by calmh** [comment]
> So no, it's a race condition. Essentially the IDX(in) had 2 files, but we only managed to put one in the db (as we iterate over the message received), and WithNeed is called in between the loop iterations.

Ah, right. That's a tight and unusual one I think. But more commonly, our scan process is to first traverse the file system and handle all new and changed files. We announce those in batches, as mentioned. At the end of that scan we look for deleted files and announce those. So there'll commonly be a period while the new file is known but the delete is not. Another device syncing in this period will see the rename file as a copy since it hasn't been told about the delete yet. This is slightly ineffiencent for sure, but the focus of the optimization is to avoid the network traffic, not necessarily the on-disk copy.
