### ISSUE TITLE
panic: leveldb: iKey "\x01", len=1: invalid length

### ISSUE THREAD

**Issue by DrStrangepork** [syncthing/syncthing#2789]
I'm running Syncthing on 4 different Windows machines with one as folder master, one as a full clone and two as recipients of only certain folders. On one of those recipient machines, I started getting this error on startup since v0.12.18:

    [YMBII] 11:52:07 INFO: syncthing v0.12.19 "Beryllium Bedbug" (go1.6rc1 windows-amd64) WIN-P6RP886TVDJ\Administrator@WIN-P6RP886TVDJ 2016-02-14 19:26:33 UTC
    [YMBII] 11:52:07 INFO: My ID: YMBII4A-TVOY52Z-X6KWSN6-ABNO2NA-CQDXUQI-IO2TR5I-UE2ID3X-4Q7OHQV
    [YMBII] 11:52:07 INFO: Single thread hash performance is ~122 MB/s
    ...
    Panic at 2016-02-20T11:52:08-05:00
    panic: leveldb: iKey "\x01", len=1: invalid length

    goroutine 1 [running]:
    github.com/syndtr/goleveldb/leveldb.iKey.assert(0xc0824573de, 0x1, 0x42e0)
    	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/key.go:109 +0x233
    github.com/syndtr/goleveldb/leveldb.iKey.ukey(0xc0824573de, 0x1, 0x42e0, 0x0, 0x0, 0x0)
    	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/key.go:114 +0x4d
    github.com/syndtr/goleveldb/leveldb.(*iComparer).Compare(0xc082197420, 0xc0824573de, 0x1, 0x42e0, 0xc082166680, 0x9, 0x9, 0xffffffffffffffff)
    	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/comparer.go:36 +0x51
    github.com/syndtr/goleveldb/leveldb/table.(*block).seek.func1(0xb6, 0x967300)
    	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/reader.go:68 +0x27f
    sort.Search(0xb7, 0xc0820541e8, 0xe8)
    	c:/go/src/sort/search.go:66 +0x59
    github.com/syndtr/goleveldb/leveldb/table.(*block).seek(0xc08241a180, 0x3351c88, 0xc082197420, 0x0, 0xb7, 0xc082166680, 0x9, 0x9, 0xb81bc0, 0x4864ac, ...)
    	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/reader.go:69 +0xb0
    github.com/syndtr/goleveldb/leveldb/table.(*blockIter).Seek(0xc0824164b0, 0xc082166680, 0x9, 0x9, 0x0)
    	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/reader.go:229 +0x115
    github.com/syndtr/goleveldb/leveldb/table.(*Reader).newBlockIter(0xc0820fe270, 0xc08241a180, 0x1267a58, 0xc08219a098, 0xc08216e540, 0x1, 0x0)
    	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/reader.go:736 +0x1e2
    github.com/syndtr/goleveldb/leveldb/table.(*Reader).NewIterator(0xc0820fe270, 0xc08216e540, 0x0, 0x0, 0x0)
    	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table/reader.go:804 +0x35d
    github.com/syndtr/goleveldb/leveldb.(*tOps).newIterator(0xc082049b30, 0xc082420460, 0xc08216e540, 0x0, 0x0, 0x0)
    	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/table.go:409 +0x1ac
    github.com/syndtr/goleveldb/leveldb.(*version).getIterators(0xc08200c4b0, 0xc08216e540, 0x0, 0xc0821940a0, 0x2, 0x2)
    	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/version.go:233 +0x104
    github.com/syndtr/goleveldb/leveldb.(*DB).newRawIterator(0xc082418000, 0xc08216e540, 0x0, 0x0, 0x0)
    	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_iter.go:40 +0xa2
    github.com/syndtr/goleveldb/leveldb.(*DB).newIterator(0xc082418000, 0x3e8902, 0xc08216e510, 0x0, 0xc082166669)
    	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_iter.go:69 +0x1d5
    github.com/syndtr/goleveldb/leveldb.(*Snapshot).NewIterator(0xc08216e4e0, 0xc08216e510, 0x0, 0x0, 0x0)
    	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db_snapshot.go:161 +0x321
    github.com/syncthing/syncthing/lib/db.(*Instance).ListFolders(0xc0821a6030, 0x0, 0x0, 0x0)
    	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:500 +0x10c
    main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc082009500, 0x34, 0x0, 0x0, ...)
    	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:656 +0x18d3
    main.main()
    	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:364 +0x969

**Comment by AudriusButkevicius** [comment]
Just delete the database, it somehow got corrupt

**Comment by DrStrangepork** [comment]
:+1:
