### ISSUE TITLE
Syncthing resurrects deleted files (as 128-byte empty files)

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#2792]
I copied a bunch of files into a Syncthing folder, and Syncthing synchronized them as they were copied. I then deleted a few of them (which may have been before the files finished synchronizing).

About 10 minutes later, Syncthing resurrected three of the files deleted. They all have a size of 128 bytes, and 0 bytes on disk. Checking on the device that these files were synchronized to, I see that these 128-byte files exist there, too.

No messages in the logs (but I didn't have any tracing turned on).

`rest/db/file` on my device (UAL5TFB):

```json
{
   "availability":[
      "3MQH4HE-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX"
   ],
   "global":{
      "flags":"0644",
      "localVersion":95221,
      "modified":"2016-02-16T07:51:12Z",
      "name":"XXX\\SAM_1425.JPG",
      "numBlocks":1,
      "size":128,
      "version":[
         "UAL5TFB:2",
         "3MQH4HE:1"
      ]
   },
   "local":{
      "flags":"0644",
      "localVersion":95221,
      "modified":"2016-02-16T07:51:12Z",
      "name":"XXX\\SAM_1425.JPG",
      "numBlocks":1,
      "size":128,
      "version":[
         "UAL5TFB:2",
         "3MQH4HE:1"
      ]
   }
}
```

and on the device the files were synchronized to (3MQH4HE):

```json
{
   "availability":[
      "UAL5TFB-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX"
   ],
   "global":{
      "flags":"0644",
      "localVersion":95221,
      "modified":"2016-02-16T07:51:12Z",
      "name":"XXX/SAM_1425.JPG",
      "numBlocks":1,
      "size":128,
      "version":[
         "11535928201135251019:2",
         "15789758954675685514:1"
      ]
   },
   "local":{
      "flags":"0644",
      "localVersion":127503,
      "modified":"2016-02-16T07:51:12Z",
      "name":"XXX/SAM_1425.JPG",
      "numBlocks":1,
      "size":128,
      "version":[
         "11535928201135251019:2",
         "15789758954675685514:1"
      ]
   }
}
```

Some version info:
 - UAL5TFB: Windows 10 64-bit, 0.12.19
 - 3MQH4HE: Linux 64-bit, 0.12.14

**Comment by AudriusButkevicius** [comment]
Can you repro it?

**Comment by canton7** [comment]
It happened with 3 files out of about 20... I could try, let me see

**Comment by AudriusButkevicius** [comment]
Try it with STTRACE=scanner,model

**Comment by canton7** [comment]
Looks like I can repro.

Which device are you most interested in the trace output from?

**Comment by AudriusButkevicius** [comment]
One of the receivers

**Comment by canton7** [comment]
Logs emailed directly to your gmail (for privacy reasons)

**Comment by canton7** [comment]
Confusingly, one log is ordered top-bottom and the other is bottom-top. Watch out!

**Comment by AudriusButkevicius** [comment]
Yeah saw that.

**Comment by rumpelsepp** [comment]
Sounds a bit like this: #1355

**Comment by AudriusButkevicius** [comment]
No, it's something else.

**Comment by rumpelsepp** [comment]
k

**Comment by AudriusButkevicius** [comment]
@canton7 can you repro with this, and get the logs which contain `XXX` string from both sides for STTRACE=model.

**Comment by canton7** [comment]
Roger that. Will next have time tomorrow evening, most likely.

**Comment by canton7** [comment]
Repro with #2795 I assume?

**Comment by AudriusButkevicius** [comment]
Y

**Comment by canton7** [comment]
Ack, completely failing to reproduce. Maybe moving up to 0.13 fixed it, or maybe it's just not the right phase of the moon...

**Comment by AudriusButkevicius** [comment]
There is no 0.13 but I did fix a bug like this very recently.

**Comment by canton7** [comment]
The build called itself v0.13.0-beta.0+85-gca9a953

**Comment by AudriusButkevicius** [comment]
ah yeah, that's from the milestone

**Comment by calmh** [comment]
Status?

**Comment by canton7** [comment]
Haven't seen it again, or been able to reproduce. Close for now

**Comment by calmh** [comment]
I have a vague memory of this being fixed somewhere, at some point, even. The cause was that we did a truncate() call with the file size, and deleted files have the synthetic size 128. But I don't remember the details.

**Comment by AudriusButkevicius** [comment]
This happened after that
