### ISSUE TITLE
Detect removed/unshared folders and stop recreating unsynced folders

### ISSUE THREAD

**Issue by gdonval** [syncthing/syncthing#2797]
### 1. Setup

- Two nodes: `Node A` and `Node B`.
- Add a new folder on `Node A`: `id="Test", folder="/tmp/test"`.
- Share the folder `id="Test", folder="/tmp/test"` with `Node B`.
- Accept the new folder on `Node B`.
- Remove/unshare `id="Test", folder="/tmp/test"` on `Node A`.

### 2. What happened

- `Node B` does not detect that `id="Test", folder="/tmp/test"` is currently unshared by `Node A`.
- `Node B` has no clue that `id="Test", folder="/tmp/test"` is only available on itself (for all it knows).
- When `/tmp/test` is deleted, `Node B` keeps recreating `/tmp/test` at each rescan/restart even though there is **nothing** to share with **no one**.

### 3. What was expected

- `Node B` should know whenever any folder is deleted or unsynced on `Node A`.
- If a folder does not exist, `Node B` should check whether it is currently synced with any other device.
    - If **yes**: create the folder and start syncing.
    - If **no**: don't create the folder.

### 4. Rational

- If there is nothing to sync in the first place, don't create unnecessary things.
- This would help to integrate Syncthing with 3rd-party tools such as OwnCloud on a headless server: 
    - new folders could be autoadded from introducer devices (easy using the Event/REST APIs);
    - unused/removed/unsynced folder could easily be deleted within OwnCloud after being removed from the other nodes without "respawning";
    - this would allow to integrate nodes to an existing swarm without letting/forcing the user to access the Syncthing GUI on them.

### 5. Alternative fix

Provide a (non-default) **option** not to auto-create folders: if they do not exist, then just do not sync. Though, knowing that a folder has been deleted by a given device or has been unshared might allow a more fine-grained handling from external apps (possible folder autoremove for instance).

### Version Information
Syncthing Version: v0.12.19
OS Version: Debian 8/Android 6/Archlinux

**Comment by AudriusButkevicius** [comment]
If you want the folder synced, add it, if you don't want it synced, don't add it. I don't think having a half way house is a reasonable request. It makes the code complicated just to satisfy yoyr specific scenario which you can perfectly handle by external means.


Node B can not know anything about Node A as it might not even be connected to Node A. Futhermore an indication that B shares something with A, while A does not share the same thing back is the feature that uses the prompts to pop up, hence the inverse cannot be used for removal.

Also, there is no distinction between "oh this has nobody sharing it now, hence I need to remove it" vs "I just added this and haven't mananed to share it with someone yet"

The right fix here is for whatever application sits on top of syncthing to remove the folder within syncthing before removing the underlying directory.

**Comment by AudriusButkevicius** [comment]
We can continue the discussion on the closed ticket and I am open to hear reasonable reasons why this needs to be reopened.

Essentially it seems you want some centralized point of control which tells other syncthing instances what to do and what to add, which is essentially against syncthings design of being decentralised, which has the high cost of management.

**Comment by AudriusButkevicius** [comment]
Perhaps the not creating a folder is somewhat a reasonable request, but I think it collides with us using it for healthchecks, identifying mount point failures, as well as the user expectation of the folder being created as you add one.

**Comment by gdonval** [comment]
I did not consider it this way but I understand your point about complexity and decentralization.

Then, would deferring folder creation at sync/creation time (instead of restart/rescan time) be an acceptable solution? This way you only create what is needed when it is needed. Or does it still collide with your healthchecks?

**Comment by gdonval** [comment]
Also note, that I did not say that unshared folders should be automatically removed (certainly not by Syncthing itself at the very least). I am just saying that it would be very convenient, at least in my case, if a deleted folder (through the OS) could stay deleted as long as nothing tries to sync it again with Syncthing.

**Comment by gdonval** [comment]
creation time: "folder being created as you add one"
sync time: "folder being created as you need it because another device want to sync something that you allowed it to"

**Comment by AudriusButkevicius** [comment]
So the case I am thinking of is as follows.
1. A and B share F at /mnt/something which has files, and are in sync.
2. A unshares F with B.
3. /mnt/something mount point fails, and /mnt/something disappears.
4. Without A noticing the mount point failure, A shares the folder back to B.
5. Because it's valid for an existing folder F on A not to have a folder on disk, we recreate /mnt/something.
6. Hey presto, all files are nuked on B, because A now points to an empty directory.

**Comment by AudriusButkevicius** [comment]
Furthermore, we break mounting on /mnt, because we created garbage directories in there.

**Comment by gdonval** [comment]
Then wouldn't it be more rigorous to 
- add the mountpoint/UUID in the folder specification;
- ask people to make the underlying directory not Synthing/World-writeable?

If there is a mount point failure, there are still other ways to nuke your shares... You could share `/home/F` which is normally available on a separate partition, but also available in the base partition, in case of failure. The UUID route is more robust.

**Comment by gdonval** [comment]
Moreover, I am not saying that *no folder* should be valid to sync. :)

Actually, in the current implementation, if the mountpoint fails, chances are high that in the next few seconds Syncthing will try to recreate it on A (because it is what it does at each restart/rescan). Then there is absolutely no way to know that something went wrong with the mountpoint.

Whereas if the folder is not present yet tries to sync it with B, there is something wrong and that's detectable.

**Comment by AudriusButkevicius** [comment]
So UUID's only work on linux, and we are somewhat trying to avoid platform specific hacks/implemenatations. If there is a mount failure, and by a coinsidence you have the same structure underneath, we still check for a special hidden file in the folder to verify it's a syncthing folder. I think that folders only get created if they never had any files and only upon restart, which to me sounds pefectly reasonable.

**Comment by gdonval** [comment]
I am not sure that indirect "measurements" are really a win there. UUID might only work on Linux (and actually Android, Mac OS and iOS, AFAIK everything except Windows) but is there a way to define arbitrary mountpoints on the platforms where UUIDs are not available?

If the idea still seem unreasonable, then what do you think of:
- either providing an option to forbid folder **re**creation to let external programs handling it
- or letting the nodes **advertise** that folder `F` is not available anymore?

**Comment by AudriusButkevicius** [comment]
As I said, it should not recreate folders if the folder ever had any files, and it should only do that on startup if it never had any files.

I am not sure what "F is not available anymore" would yield.

**Comment by gdonval** [comment]
Well, we are going in circles and I have other things more useful to do than repeating myself. Thanks for your time.

**Comment by AudriusButkevicius** [comment]
What I am trying to say is that what you are looking for (not recreating folders) already exists, just under certain conditions. If you are exhibiting folders recreated under those conditions, you most likely hit a bug. If you are looking for not creating folders for empty folders I think it's doable, someone just needs to make a pull request.
