### ISSUE TITLE
syncthing.net down -> relays network down -> global discovery not working ?!?

### ISSUE THREAD

**Issue by rdarioc** [syncthing/syncthing#2800]
Today I found out that the syncthing.net web site is down, as consequence the relays network is not reachable.

I tried to connect unsuccessfully both my server node (as per below specs) and my syncthing running on my android phone (Android 4.4.2, SyncThing4Android 0.7.8, SyncThing 0.12.19) using the discovery mode.

I checked uPnP works both on the server and on the mobile (port are re-mapped and found open with a port scanner ran on the official IP address).

I also checked using their standard connection (through the land-line ISP and the mobile ISP) but also via VPN (OpenVPN) both on the server and on the mobile.

How can I check if the server node correctly register itself on the discovery server? Any suggestion on how to trace where the two nodes get lost?

Thanks in advance.

### Version Information
Syncthing Version: v0.12.19
OS Version: Ubuntu 14.04.1 64bit

**Comment by canton7** [comment]
Yep, known issue. An ISP is having issues after a severed fibre cable.

As a short-term workaround (if you, or someone else reading this issue, *needs* relays), you can manually specify relays to use in your config file, search for 'relayServer' here: https://docs.syncthing.net/users/config.html

Two relays (off the top of my head) are:

 - 178.79.161.15:22067
 - 23.92.71.120:443

> port are re-mapped

What exactly do you mean by this? The src and dest ports need to be the same.

Make sure all devices have global discovery enabled. Make sure that your server accepts connections on port 22000 (unless you've changed the default) - test using telnet/netcat from another host.

**Comment by rdarioc** [comment]
Gents, don't know what to say, after about 5 hours trying, still in configuration:
* global discovery on (both pc and mobile),
* local off (both pc and mobile), 
* relay on (although not reachable) on PC, relay off on mobile
* straight DSL link on PC, VPN on mobile

The two nodes found each other?!?

It sounds a bit too much unpredictable, I would leave this open for a bit in case someone else has found similar issues and if the issue will disappear in the next 24 hours, I'll close this myself thanking some planetary alignment.

**Comment by rdarioc** [comment]
@canton7 , thank you for your immediate reply.

As for your question: "What exactly do you mean by this? The src and dest ports need to be the same."

Here is a c&p from the pc log:

"xxx INFO: New UPnP port mapping: external port 24858 to local port 22000."

So I meant, the UPnP protocol was working and the gateway (either the ISP one or the VPN one where working fine).

Would you mind to give me the syntax on how to specify those relays on the PC config window?

**Comment by rdarioc** [comment]
Found the syntax, sorry and thank you again for your immediate reply.

**Comment by canton7** [comment]
> "xxx INFO: New UPnP port mapping: external port 24858 to local port 22000."

That doesn't look right: Syncthing used to require that the external and local ports were the same, and I'm pretty sure it still does.

**Comment by AudriusButkevicius** [comment]
Not for UPnP

**Comment by canton7** [comment]
Ah cool, I stand corrected then.

**Comment by rdarioc** [comment]
Anyway, I shut down the PC node and started again and it is taking ages to discover again the mobile node which has been up and running all the time ... @canton7 do you think this is also has to do with the ISP issue you mentioned above?

**Comment by canton7** [comment]
I wouldn't have thought so? My suspicion would be that the server can't connect directly to the mobile, so we're waiting for the mobile to get around to asking the discovery servers to see if the server's online (which it does regularly, but not too frequently). Prior to the outage, the relays would have stepped in and helped (the server would have connected to the mobile's relay, and that would have caused the mobile to try and connect directly to the server).

**Comment by rdarioc** [comment]
Just an idea, would it be worth when a node restarts try to discover if the old addresses are still working? After all the VPN link on my mobile has been stable and the associated public IP addresses hasn't changed in the past three hours.

**Comment by canton7** [comment]
Who would try and discover if what old address is working?

It's likely that the mobile had a direct connection to the server. This was broken when the server restarted. The majority cause of this is the server shutting down, so there's little point in the mobile constantly trying to reconnect to a device which is thinks is dead.

A better solution might be to properly distribute the relay network (so it isn't affected by a single outage): there are plans for this.

**Comment by rdarioc** [comment]
I didn't mean the mobile keep polling, I meant the PC only once, at boot time, check if the old parties where still reachable at the previous recorded addresses. Anyway, I understand the relays are still up, what is down is the server providing their addresses, is that correct?

**Comment by AudriusButkevicius** [comment]
Yes, the server listing available relays is down.

**Comment by rdarioc** [comment]
Good news, after about 8 minutes the two parties are connected back again. I understand all the things and I believe we can close this thread. If you recall any static list of relays to append in here, that could be great, otherwise we'll just wait until the server is back online.

**Comment by canton7** [comment]
> I didn't mean the mobile keep polling, I meant the PC only once, at boot time, check if the old parties where still reachable at the previous recorded addresses

My hypothesis is that the mobile could establish a connection to the PC, but the PC could not establish a connection to the mobile.

Syncthing only needs to establish a connection in one direction, so the fact that the PC can't connect to the mobile isn't an issue, since the mobile can't connect to the PC.

When Syncthing starts, it does try and connect to all devices. However the PC can't connect to the mobile, so this didn't cause a connection to be established.
