### ISSUE TITLE
Syncthnig unable to sync files with Hebrew letters.

### ISSUE THREAD

**Issue by PaC-mEn** [syncthing/syncthing#2801]
As AudriusButkevicius told me im opening this ticket.
the source post https://forum.syncthing.net/t/is-syncthnig-unable-to-sync-files-with-hebrew-letters/6846
syncthing unable to sync files named in Hebrew. i tried to sync folder with file name in hebrew and all the files are presented in the Failed item zone, of the receiving side, the sending side show that all the files are synced.

when im trying to sync mixed folder, hebrew files and english all the english file are synced and the hebrew files are at the Failed items zone.

[syncthinglogfile.txt](https://github.com/syncthing/syncthing/files/149294/syncthinglogfile.txt)

edit: my FileServer is ubuntuServer and sync files with my win8 (with GTK) laptop, both at v0.12.19

Thanks :slightly_smiling:

the attached log file from my Ubuntu server machine.
[syncthinglogfile.txt](https://github.com/syncthing/syncthing/files/149295/syncthinglogfile.txt)

**Comment by calmh** [comment]
Syncthing requires that file names are in UTF-8. Are you sure this is the case. I'm on a not very capabable device now so can't check for sure, but my eyes don't think the encoding mess in the log file looks like UTF-8.

**Comment by PaC-mEn** [comment]
i know some notepads doesn't support Hebrew and many times if your font is not Arial base you may get gibberish, so i attached screenshot of few lines from the log containing the name files i tried to sync
![syncthingissue](https://cloud.githubusercontent.com/assets/12939352/13494795/496799c0-e14f-11e5-95ac-8648a7e58712.jpg)

**Comment by AudriusButkevicius** [comment]
@calmh the issue is when the error happens. If its an invalid filename, it should be refused, rather than fail on creating the temp file.

**Comment by calmh** [comment]
We might receive a correctly formatted UTF-8 file name from another system and get told to bugger off when attempting to create the file on a system that enforces file names in another non-UTF-8 code page, possibly.

**Comment by PaC-mEn** [comment]
Want live debug to the machine?

**Comment by calmh** [comment]
Currently in the Bangkok airport on a fairly crappy wifi on an iPad, so I'd rather not. :) However, if it's a unixy box what does `locale` and `mount` output? If it's Windows, I'm not sure where the relevant settings live.

**Comment by PaC-mEn** [comment]
```
orangepi@OrangePI:~$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
orangepi@OrangePI:~$ mount
/dev/mmcblk0p2 on / type ext4 (rw,noatime,nodiratime,errors=remount-ro)
proc on /proc type proc (rw,noexec,nosuid,nodev)
sysfs on /sys type sysfs (rw,noexec,nosuid,nodev)
none on /sys/fs/cgroup type tmpfs (rw)
none on /sys/fs/fuse/connections type fusectl (rw)
none on /sys/kernel/debug type debugfs (rw)
udev on /dev type devtmpfs (rw,mode=0755)
devpts on /dev/pts type devpts (rw,noexec,nosuid,gid=5,mode=0620)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,mode=1777)
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)
none on /run/lock type tmpfs (rw,noexec,nosuid,nodev,size=5242880)
none on /run/shm type tmpfs (rw,nosuid,nodev)
none on /run/user type tmpfs (rw,noexec,nosuid,nodev,size=104857600,mode=0755)
/dev/mmcblk0p1 on /media/boot type vfat (rw)
/dev/sda1 on /home/storage type vfat (rw,uid=1000,gid=1000)
systemd on /sys/fs/cgroup/systemd type cgroup (rw,noexec,nosuid,nodev,none,name=systemd)
orangepi@OrangePI:~$
```

still if you want to get full access to my machine or debug let me know

**Comment by calmh** [comment]
/home/storage is of type vfat. A quick google talks about code pages and FAT_DEFAULT_CODEPAGE and whatnot. My bet is it's not UTF-8 (contrary to your locale, which looks fine) and the filesystem tells us to fuck off when creating the file.

**Comment by PaC-mEn** [comment]
GOD iv just tried to sync on my primary sd card and it worked.
do you know how do i my storage device to support utf-8?

**Comment by AudriusButkevicius** [comment]
Not use vfat?

**Comment by PaC-mEn** [comment]
it is vfat

**Comment by AudriusButkevicius** [comment]
Well that's exactly what I said.
Switch to something else than vfat, or check the mount options to see if anything can be done to support UTF-8.

**Comment by PaC-mEn** [comment]
"problem" solved by formatting my storage array to ext4.
sorry for being newbie as child.
