### ISSUE TITLE
DNS config of mailserver (for forum posts)

### ISSUE THREAD

**Issue by evert-mouw** [syncthing/syncthing#2803]
Host `discourse.syncthing.net` should probably point to `194.126.249.10` in DNS.

```
evert@dvalin ~> host discourse.syncthing.net
Host discourse.syncthing.net not found: 3(NXDOMAIN)
```

Yes I know my mailserver is very strict, but it helps to prevent spam. 

```
Feb 27 11:42:18 filter postfix/smtpd[14661]: connect from forum.syncthing.net[194.126.249.10]
Feb 27 11:42:18 filter postfix/smtpd[14661]: NOQUEUE: reject: RCPT from forum.syncthing.net[194.126.249.10]: 450 4.7.1 <discourse.syncthing.net>: Helo command rejected: Host not found; from=<noreply@syncthing.net> to=<******> proto=ESMTP helo=<discourse.syncthing.net>
Feb 27 11:42:18 filter postfix/smtpd[14661]: disconnect from forum.syncthing.net[194.126.249.10]
```

Please fix  :-)

**Comment by canton7** [comment]
More likely that the mail server's got some old config that needs updating. discourse.syncthing.net was renamed to forum.syncthing.net ages ago.

**Comment by calmh** [comment]
The reverse pointer is incorrect. I'll sort this out.

**Comment by calmh** [comment]
Reverse pointer is fine, mail server config had the old hostname in it. Fixed, thanks for pointing it out.
