### ISSUE TITLE
Create panic log failed

### ISSUE THREAD

**Issue by GitHubGeek** [syncthing/syncthing#2810]
`syncthing` crashed but could not create the panic logs. Not sure how to reproduce. Have checked both dirs: `~/.config/syncthing/` and `~/.config/syncthing/index-v0.11.0.db/` and they're of correct user and permissions.

Console output:

```
panic: open /home/foo/.config/syncthing/index-v0.11.0.db/002525.log: no such file or directory
[monitor] 23:09:55 WARNING: Create panic log: open /home/foo/.config/syncthing/panic-2016xxxx-xxxx.log: no such file or directory
```

### Version Information
Syncthing Version: v0.12.19
OS Version: Ubuntu 14.04

**Comment by AudriusButkevicius** [comment]
It seems your home directory or .config directory disappeared from underneath syncthings feet.
A crash in that case its a perfectly reasonable reaction.

**Comment by GitHubGeek** [comment]
Yes it's an encrypted home.

Found this in `dmesg`. Could be causing the system to be unresponsive temporarily.
```
[10953.564421] perf interrupt took too long (2532 > 2500), lowering kernel.perf_event_max_sample_rate to 50000
```
