### ISSUE TITLE
browser hangs when restarting a remote sync server

### ISSUE THREAD

**Issue by andrewufrank** [syncthing/syncthing#2814]
I have several browser tabs open in iceweasel on debian jessie for multiple sync servers (3). one of them is semi-dead (connnection closed for read timeout). i restart this (using an ssh connection and 
use systemd systemctl restart). then the browser (on the machine i work on, not the restarted remote one) goes into high gear - using 100..150% cpu shown in top) and the browser becomes unresponsive (no reaction to changing tabs!). this lasts for a while 20 seconds and i usualy kill icewease.  
if i restart (using systemclt restart..), the remote server recovers and tackles the changes.

my expectations:
restarting a remote closes the window or announces on the window that the remote is restarting with no further effect on the browser.

If your issue is a feature request, simply replace this template text in it's entirety.

### Version Information
Syncthing Version: v0.12.19 (armhf on the remote, linux 64 on the client)
OS Version: debian jessie, xfce, iceweasel (uptodate)

**Comment by andrewufrank** [comment]
additional observation: the browser does not hang if i restart a remote server when it is regularly working. it seems to be related to the situation that the remote server is semi-dead for multiple 'read timeout'. (see issue 2815)

**Comment by AudriusButkevicius** [comment]
So to me this is a browser problem, not a syncthing problem.

**Comment by canton7** [comment]
It might well be a javascript bug: worth making sure it isn't. 

Is this repeatable across different sorts of browser?

**Comment by AudriusButkevicius** [comment]
Even if its a javascript bug, the browser should not freeze.

**Comment by andrewufrank** [comment]
i do not have no computer currently with another browser but can install one (if in debian repository). which one would be interesting (not using the same engine)?

**Comment by canton7** [comment]
If it gets caught in an infinite loop or something most browsers will happily hang... That's still a javascript issue. 

Try chrome/chromium, if you don't mind.

**Comment by andrewufrank** [comment]
i tried with chromium and i did not see the hanging (when i restart a server in the 'read timeout' semi-dead state. it is a firefox related thing therefore. i guess you can close this.

**Comment by AudriusButkevicius** [comment]
Just for sake of sience, check if there is anything funny in javascript log for firefox

**Comment by andrewufrank** [comment]
it happens exactly after i either confirm to share a folder or add a folder (after being prompted). 
the only thing i see in the log is twice in a row and noting in between: 
````
"refreshConnections" Object { 2R  ......
"refreshErrors" Object { errors: null } syncthingController.js:492:16
"refreshErrors" Object { errors: null }
````

if then refresh the page i see in the log 

````
"UIOnline" syncthingController.js:84:12
"refreshConfig" Object { version: 12, folders: Array[36], devices: Array[18], gui: Object, options: Object, ignoredDevices: Array[0] } syncthingController.js:499:16
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.
````

and all the connection infor remains blank
only then appear two read timeout lines in the syncthing log. 

i hope this help a bit - there is somewhere a bug, which appears only when servers are slow (or otherwise overburdened to answer slowly).
thank you for a valuable and useful tool to sync!

**Comment by AudriusButkevicius** [comment]
It's calculating total size at this point, which is an expensive operation, and it seems too much for your hardware.
