### ISSUE TITLE
feature request proxy or tor support

### ISSUE THREAD

**Issue by bluelovers** [syncthing/syncthing#2816]
feature request proxy or tor support

how can hide ip when we sync

**Comment by canton7** [comment]
Syncthing has support for socks proxies: check the docs.

**Comment by canton7** [comment]
Ultimately though, if you want two of your devices to connect to each other, one of them had to know the IP of the other: that's how the internet works (unless you rely on the relays, in which case you'll get a much slower sync speed, and people who use tor are generally opposed to the concept of relays on principle).

**Comment by AudriusButkevicius** [comment]
Yes, socks already supported.
