### ISSUE TITLE
Clarify the GUI/API listen address as opposed to the suggested URL at startup

### ISSUE THREAD

**Issue by ediazrod** [syncthing/syncthing#2819]
If you put you config as 
    <gui enabled="true" tls="true">
        <address>0.0.0.0:8384</address>
syncthing runs only on localhost

M5XMC] 22:51:10 INFO: API listening on [::]:8384
[M5XMC] 22:51:10 INFO: GUI URL is https://127.0.0.1:8384/
[M5XMC] 22:51:20 INFO: No UPnP device detected

if you put http or tcp 
    <gui enabled="true" tls="true">
        <address>tcp://0.0.0.0:8384</address>

[M5XMC] 22:50:53 FATAL: Cannot start GUI: listen tcp: too many colons in address https://0.0.0.0:8384

### Version Information
INFO: syncthing v0.12.19 "Beryllium Bedbug" 
Debian 8 x32

**Comment by AudriusButkevicius** [comment]
You are filling something in the wrong places, such as GUI address in protocol address location or vica versa.

Also, 0.0.0.0 is not localhost.

**Comment by calmh** [comment]
> 0.0.0.0:8384
> syncthing runs only on localhost

It does not. However it prints the 127.0.0.1 address as 0.0.0.0 is not valid in links on some OS:es.

**Comment by canton7** [comment]
That message has confused many people now. Maybe something like "GUI listening on http://0.0.0.0:8384; access at http://127.0.0.1:8384"?

**Comment by calmh** [comment]
Indeed. That is essentially what we're saying though, but I guess people don't recognize the v6 unspecified host...

```
[M5XMC] 22:51:10 INFO: API listening on [::]:8384
[M5XMC] 22:51:10 INFO: GUI URL is https://127.0.0.1:8384/
```

**Comment by canton7** [comment]
Aah I forgot about the API and GUI lines. 

Maybe:

```
INFO: GUI and API listening on [::]:8384 [M5XMC] 
INFO: URL to view GUI is https://127.0.0.1:8384/
```

?

**Comment by canton7** [comment]
(@ediazrod I hope this is making the situation clearer to you: the "API" line shows what addr so the API (and GUI) is listening on, which is correct in the log you posted. The "GUI URL" line gives a clickable link the user (in some terminals at least) to view the GUI: showing 0.0.0.0 or [::] here isn't useful, as browsers don't know what to do with those...

**Comment by ediazrod** [comment]
Sorry my english is very bad, I try to make synching GUI listen in all the interfaces this is why I put 0.0.0.0 but I put 0.0.0.0:8384 the GUI only works on localhost like 127.0.0.1
[M5XMC] 22:51:10 INFO: API listening on [::]:8384
[M5XMC] 22:51:10 INFO: GUI URL is https://127.0.0.1:8384/

I think it is ignoring the parameter...

if I use tcp://0.0.0.0:8348 in the config file the server give to me this error: Cannot start GUI: listen tcp: too many colons in address.

It is clear now?

**Comment by AudriusButkevicius** [comment]
tcp is only used for protocol connections, you have to put 0.0.0.0 for the GUI, which looking at your log IS working. The reason you see 127.0.0.1 is because that is the address your browser should connect to, because connecting to 0.0.0.0 makes no sense, yet it listens on 0.0.0.0

**Comment by ediazrod** [comment]
Sorry It is true, we must close the bug.. my bad.

**Comment by canton7** [comment]
Let's leave it open until we've improved the messages, so other people don't get confused

**Comment by AudriusButkevicius** [comment]
```diff
--- a/cmd/syncthing/gui.go
+++ b/cmd/syncthing/gui.go
@@ -267,8 +267,8 @@ func (s *apiService) Serve() {
        defer s.fss.Stop()
        s.fss.ServeBackground()

-       l.Infoln("API listening on", listener.Addr())
-       l.Infoln("GUI URL is", guiCfg.URL())
+       l.Infoln("GUI and API listening on", listener.Addr())
+       l.Infoln("Access the GUI via the following URL:", guiCfg.URL())
        if s.started != nil {
                // only set when run by the tests
                close(s.started)
```
reasonable?

**Comment by canton7** [comment]
:+1:
