### ISSUE TITLE
GUI Theme Dark: Some texts are too dark

### ISSUE THREAD

**Issue by merlinuwe** [syncthing/syncthing#2820]
Hi, 

I use two monitors and when I started syncthing, I couldn't recognize the Folder ID and the Path (see screenshot) (because of the bad contrast and different angle of my second monitor). Is it possible to get the same font color as the other texts in one of the next releases?

![kontrast](https://cloud.githubusercontent.com/assets/4138869/13553640/24982f36-e390-11e5-9a2c-16b9f6c9fc11.png)

The same problem appears in the field of the api key and the Show ID Dialog, where the QR-Code can be found .

Thank you very much.

### Version Information
Syncthing Version: v0.12.19
OS Version: Windows 10

**Comment by Getron** [comment]
@merlinuwe it should be implemented the dark-grey theme, on #1925, i have done the css files, and it looks great, i have work hard to make it looks great, but, unfortunatly, i don't known to implement this on git, and the devs seems not to have enough time, to implement it.

Maybe, someone do it, and implement this theme i have done, all text are great to see and recognize, and it looks very modern, but, yea... waiting to someone to implement it...
