### ISSUE TITLE
.stignore invalid pattern error - mix of square brackets and dash

### ISSUE THREAD

**Issue by GitHubGeek** [syncthing/syncthing#2822]
The following ignore pattern `[Foo-bar] foo bar [bar - foo].zip` triggers an error.

```
[XXXXX] 13:52:20 INFO: Stopping folder MyFolder due to error: loading ignores: invalid pattern "[Foo-bar] foo bar [bar - foo].zip" in ignore file
```

It seems to be a mix of `-` (dash character) and `[]` (square brackets) that are causing problems.

[The doc](https://docs.syncthing.net/users/ignoring.html) provides no clue on why this is invalid.

### Version Information
Syncthing Version: v0.12.20
OS Version: Ubuntu 14.04

**Comment by calmh** [comment]
The brackets set up a character range; `foo[a-z]bar` matches `fooabar` through `foozbar`. Your range is invalid in that sense. To get brackets as brackets, you need to escape them: `\[foo - bar\]`. Escaping is not supported on Windows. The docs should indeed be improved to reflect this.
