### ISSUE TITLE
Systemd.services invalid domains

### ISSUE THREAD

**Issue by vconnat** [syncthing/syncthing#2824]
When : 

systemctl start syncthing@syncthing.service, this happened : 

![kitty_portable_2016-03-07_23-55-55](https://cloud.githubusercontent.com/assets/11770752/13586320/70441a9a-e4c0-11e5-98db-95b2801d793c.png)

With this systemd configuration : 

![kitty_portable_2016-03-07_23-57-38](https://cloud.githubusercontent.com/assets/11770752/13586321/70489fca-e4c0-11e5-8ee7-429fb8127246.png)

**Comment by canton7** [comment]
Sanity check: do you actually have a network interface with the address 192.168.0.5?

**Comment by rumpelsepp** [comment]
Have you tried omitting the quotes? There is sth. strange happening with the error message...

**Comment by vconnat** [comment]
When I run the command from the shell, it works fine, so, I guess the problem doesn't come from the command

**Comment by rumpelsepp** [comment]
Again, have you tried omitting the quoted within the service file? They seem to get escaped and are part of the address in your example.

**Comment by calmh** [comment]
That quoting would work in a shell (although it's unnecessary). Systemd apparently treats it entirely differently, to my utter lack of surprise.

**Comment by rumpelsepp** [comment]
Yeah, crappy stuff... @vconnat: which systemd version are you using? I believe that there was a discussion about this some time ago.
