### ISSUE TITLE
Clients cant connect to each other

### ISSUE THREAD

**Issue by bigretromike** [syncthing/syncthing#2831]
Client 1: (aka server)
Debian with Syncthing v0.12.20, Linux (64 bit)
Shear name: android
Global Discovery enabled, Local Discovery enabled/disabled (tested on both), UPnP enabled/disable (tested on both)
No firewall - VPS
Knows: Client 2, 3

Client 2: (aka phone)
Android 6.0 (CM13) with Syncthing v0.12.20 (Syncthing-Android v0.7.10)
shear name: android
Global Discovery enabled, Local Discovery enabled/disabled (tested on both), UPnP enabled/disable (tested on both)
home: WiFi Firewall enabled, Nat enabled, Upnp enabled
work: WiFi Firewall enabled double NAT, upnp disabled
and 
3G no software firewall
Knows: Client 1, 3

Client 3: (aka pc)
Windows 7 x64 Pro with Syncthing v0.12.20, Windows (64 bit)
shear name: android
Global Discovery enabled, Local Discovery enabled/disabled (tested on both), UPnP enabled/disable (tested on both)
work: WiFi Firewall enabled double NAT, upnp disabled
Knows: Client 1, 2

From what I read only 1 machine need to be outside NAT and firewall is disabled anyway.
From Home I was able to sync 'android' folder from server to phone.
I'm unable to sync anything in work - even if server is outside NAT, without firewall etc.
I try to play with discoveries but didn't achieve anything.

Inside logs (Im checking the LOG files next to manifest one?)
server - nothing about errors. MANIFEST-000024
pc - nothing about errors, MANIFEST-000023
phone -  nothing about errors,, MANIFEST-000058

Anyway to make it work? Because I was hoping for solution to replace GDrive ;-) and not big one like oC

**Comment by AudriusButkevicius** [comment]
Please use the forums, given it's more of a support question than a bug.

**Comment by bigretromike** [comment]
After clean install and leaving settings on default it started to work. Thanks - just wanted to close
