### ISSUE TITLE
Do not put apt.syncthing.net behind cloudflare

### ISSUE THREAD

**Issue by steelman** [syncthing/syncthing#2838]
Putting apt.syncthing.net repository makes it inaccessible from certain locations (IP addresses) the list of which neither I (or any other user for that matter) nor you can control. Depending on my ISP (mobile or land-line) I get HTTP 403 while trying to access http://apt.syncthing.net/dists/syncthing/release/binary-i386/Packages. apt-get due to its non-interactive nature is unable to cope with this problem.

**Comment by calmh** [comment]
Yeah we should deal with this

**Comment by calmh** [comment]
Done
