### ISSUE TITLE
Outdated security information

### ISSUE THREAD

**Issue by steelman** [syncthing/syncthing#2839]
The security page mentions D26E6ED000654A3E as the key used for signing package releases. Apparently apt-get reports it is not true. 

~~~
W: GPG error: http://apt.syncthing.net syncthing InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 2B9FAE4C37C86D31
~~~

Please provide the current key at https://syncthing.net/security.html

**Comment by calmh** [comment]
Yes, the packages are actually signed by a subkey of 00654A3E; we should fix the ID in the text. The key is available on https://www.syncthing.net/release-key.txt though, as linked to from http://apt.syncthing.net/.

**Comment by calmh** [comment]
That said, the "packages" referred to on that page are those on the download tab here on Github, and they are signed as documented there. The APT packages are signed by a different subkey, that is available as described above. I'm not sure this requires correcting, although it can obviously be a source of confusion.

**Comment by steelman** [comment]
For sure all this should be explained on the security.html page. Its purpose is to enable user to establish trust so it should clearly explain: which and how keys are being used and ensure the integrity of this information.

**Comment by lkwg82** [comment]
@steelman How would you like it described there?

**Comment by calmh** [comment]
I don't actually see a problem here (any more, at least):

```
jb@web:~ $ curl https://www.syncthing.net/release-key.txt | gpg --import
gpg: directory `/home/jb/.gnupg' created
gpg: new configuration file `/home/jb/.gnupg/gpg.conf' created
gpg: WARNING: options in `/home/jb/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/home/jb/.gnupg/secring.gpg' created
gpg: keyring `/home/jb/.gnupg/pubring.gpg' created
gpg: /home/jb/.gnupg/trustdb.gpg: trustdb created
gpg: key 00654A3E: public key "Syncthing Release Management <release@syncthing.net>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: no ultimately trusted keys found
jb@web:~ $ gpg --list-keys
/home/jb/.gnupg/pubring.gpg
---------------------------
pub   2048R/00654A3E 2014-12-29
uid                  Syncthing Release Management <release@syncthing.net>
sub   2048R/F614F575 2014-12-29
sub   4096R/37C86D31 2015-05-11 [expires: 2025-05-08]

jb@web:~ $ gpg --verify /var/www/apt-dists/dists/syncthing/InRelease 
gpg: Signature made Mon 03 Oct 2016 11:32:40 PM UTC using RSA key ID 00654A3E
gpg: Good signature from "Syncthing Release Management <release@syncthing.net>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 37C8 4554 E7E0 A261 E4F7  6E1E D26E 6ED0 0065 4A3E
jb@web:~ $ 
```
