### ISSUE TITLE
Permission changing after scan

### ISSUE THREAD

**Issue by ramesh45345** [syncthing/syncthing#284]
Version v0.8.10, under Arch Linux, on an ext4 formatted drive.

I'm having a problem with permissions on files when using syncthing. I have a folder (about 26GB) which I want to sync. I have two computer scan the folders (but don't allow them to sync to each other yet. After they scan the folders, both computers change the permissions of the contents to disable read, write, and any other permissions. Here is a screenshot in Syncthing after it is done:

![image](https://cloud.githubusercontent.com/assets/6318224/3078298/888782b2-e469-11e3-948a-9874c9ad5f5b.png)

Here is a log of "ls -la" of the folder in question after Syncthing is done scanning it:

drwxrwxrwx 6 ramesh users    4096 May 25 19:33 ./
drwxr-xr-x 9 ramesh users    4096 May 25 17:09 ../
d--------- 4 ramesh users    4096 May 25 19:34 Applications/
drwxrwxrwx 5 ramesh users    4096 Apr 14 17:32 Media/
d--------- 4 ramesh users    4096 May 15 20:54 Podcasts/
drwxrwxrwx 2 ramesh users    4096 May 14 17:39 .SyncArchive/
-rwxrwxrwx 1 ramesh users      20 May 15 20:54 .SyncID*
-rwxrwxrwx 1 ramesh users     296 Feb 10 22:32 .SyncIgnore*

Within the folders, more objects of the 26GB of data have had their permissions removed, to the point where only 8mb can be read by Syncthing. This has the side effect of, when Syncthing goes back to sync, it will delete the files from the other computer. 

I don't see anything importnat in the syncthing message output (when running syncthing on the command line). Only information like:

[7HVBO] 20:05:45 WARNING: remove /mnt/Storage/Files/AndroidSync/Podcasts/BadVoltage: directory not empty
[7HVBO] 20:05:45 WARNING: remove /mnt/Storage/Files/AndroidSync/Podcasts/BadVoltage: directory not empty

This message it will display as it tries to delete content.

Is there anything you would like me to attach that would be helpful to you? In any case, thanks for the hard work in making this program. I'm excited to move to it from BitTorrent Sync.

**Comment by EmilioMoreno** [comment]
Hi, just experience the same behavior with  v0.11.20, Linux (64 bit) and Macos 64bits. Mac is the master and Linux is simply creating some dirs with permissions d--------- while others are created drwxr-xr-x as expected. Both dirs are owned by synching user. Once the permissions are fixed via chmod, everything goes smoothly.
