### ISSUE TITLE
Folder label change should not trigger restart prompt

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2840]
<img width="1158" alt="screen shot 2016-03-15 at 14 04 47" src="https://cloud.githubusercontent.com/assets/125426/13778579/fa161510-eab6-11e5-9da3-d5682b280d48.png">

**Comment by lkwg82** [comment]
This is a UX bug. @AudriusButkevicius  mentioned this in the [PR](https://github.com/syncthing/syncthing/pull/2668#issuecomment-195090737) . We lost it in the discussion.
