### ISSUE TITLE
Remote device "in sync" percentage should reflect partially downloaded files

### ISSUE THREAD

**Issue by dbkblk** [syncthing/syncthing#2842]
Hi,

I use Syncthing on Manjaro and Windows machines and the core works really good. However, the GUI could be more efficient when reporting the percent of sharing between two machines. Currently, it calculates the percent regarding to the number of files transfered but it should do that based on the size.

For example: If I share 3 files, 3go, 500mo and 100ko. If the 3go file is transfered first, the percent will show 0% until the file is fully complete.

Request: Get the size of the whole files to transfer first and calculate the progress based on what have been transfered instead of the number of files.

Thank you.

**Comment by calmh** [comment]
It is based on the total size, not the number of files. However a file is not "in sync" until it has been transferred, hence the delay in updating the percentage.

**Comment by AudriusButkevicius** [comment]
Not exactly true as tye progress emitter tracks the partial download bytes and adjusts the percentage.

**Comment by calmh** [comment]
I think this one is from the other side, i.e. what device A shows about device B's in sync status.

**Comment by calmh** [comment]
Your temp indexes changes might actually fix this one at some point?

**Comment by AudriusButkevicius** [comment]
Yes, it would, in which case I think this is a dup of some already existing ticket.

I am waiting for your change train to go in until I touch that again.

**Comment by calmh** [comment]
Yeah. Leaving this as is for the moment, without a milestone which means I'll get back to triaging it later and hopefully be able to determine if it's dup or not. :)

**Comment by AudriusButkevicius** [comment]
Fixed by #2252
