### ISSUE TITLE
maxSendKbps is not treating the input value as bits, but rather bytes

### ISSUE THREAD

**Issue by garypaduana** [syncthing/syncthing#2844]
I set `maxSendKbps` to 10000 because my home internet connection achieves about 13Mbps (which is 13000Kbps).  There was seemingly no change and Syncthing continued to max out my upstream bandwidth.  During troubleshooting I then set `maxSendKbps` to 300 and noticed that the transfer was then limited to 300KB / sec.

I searched the issues and saw one open discussing which units should be used, but it didn't seem to mention that the current label is incorrect.

The label is defined in kilobits per second but the value is treated as if it were kilobytes per second.

Syncthing Version: v0.12.20, WIndows 64 bit
OS Version: Windows 7 Professional x64

**Comment by wweich** [comment]
What's important is how it is in the UI, and there the unit is correct.
If you are editing the the config directly you already need to know what you are doing, and should have read the docs (which will soon have the correct units in the description).

**Comment by garymanifold** [comment]
it is incorrect in the UI.  it should say KBps.

**Comment by garymanifold** [comment]
Will the UI not be updated to `maxSendKBps`?  I understand that you're using camel casing but it's very confusing considering the case is very important in this situation.

it's a very common standard that lower case b denotes bits and upper case B denotes bytes.

**Comment by calmh** [comment]
Which UI are you talking about? The UI I think we're talking about documents these fields as `Incoming Rate Limit (KiB/s)` and the same for outgoing. The config variable is unfortunately camel cased (I think it was in fact intended to be kilobits per second but something happened along the way), but this should not be exposed to most users.

**Comment by garymanifold** [comment]
Yes, I was in the advanced configuration and didn't see the other option first in Settings.   Sorry for the confusion, I should have posted a screenshot from the start.  I understand now that it's more than just a label change, thanks.
