### ISSUE TITLE
Syncing an existing file will change its inode

### ISSUE THREAD

**Issue by fearenales** [syncthing/syncthing#2845]
When a file is synced from an origin, its inode changes.

This means if I'm running an `tail -f` on that file, it will break. If I'm running `tail -F`, the whole file content is prompted.

Is there any possible way to force Syncthing to preserve the file inode?

### Version Information

Syncthing Version: v0.12.20
OS Version: Mac OS X Yosemite (running Syncthing in a Docker container)

**Comment by wweich** [comment]
No. Syncthing always creates a new file, copies as much data from local and the rest from remote, and if it is sure the new file is correct, the old file is deleted and the new file is moved/renamed.

**Comment by canton7** [comment]
...  Which gives you atomic file updates.

**Comment by calmh** [comment]
Yes. This is as intended. We never alter a file in place, for good and bad. There's a discussion (somewhere, I can't find it right now) and an idea (https://github.com/syncthing/syncthing/wiki/In-Place-Updates) for how to do in place updates, but this is not in the roadmap for now. In any case it would seldom be as clean as a straight append of data to a file to make your `tail -f` happy. Sorry.

**Comment by AudriusButkevicius** [comment]
Why don't you just use -F, which follows file name and not inode?

**Comment by fearenales** [comment]
@AudriusButkevicius Please, don't get me wrong. I'm not asking for a change on Syncthing, I just wondered if there was an existing way to do that. Btw, I've pointed the downsides of using `tail -F`.

But that's a minor case for me, no worries. Syncthing is an awesome tool! Great job! :)

**Comment by fearenales** [comment]
Thank you all guys for the explanation! :smile:
