### ISSUE TITLE
Unix build status links to a 404

### ISSUE THREAD

**Issue by brianredbeard** [syncthing/syncthing#2856]
The build status image:
![](https://camo.githubusercontent.com/0c98e38f75d598ae2f0f8eac8c9f614209ce0bb4/68747470733a2f2f696d672e736869656c64732e696f2f6a656e6b696e732f732f687474702f6275696c642e73796e637468696e672e6e65742f73796e637468696e672e7376673f7374796c653d666c61742d737175617265266c6162656c3d756e69782532306275696c64)

consistently shows the build in a "building" status while the URL to the build (http://build.syncthing.net/job/syncthing/lastBuild/) displays a 404.  From the format of the naming one would assume this is from a Jenkins install which is currently broken.  Traversal of the URL path also continues to show 404 errors.

**Comment by brianredbeard** [comment]
And apparently `favicon.ico` shows it's Jenkins as well. :grinning:

**Comment by calmh** [comment]
Yeah I reorganized a little too much when migrating the build server yesterday. Fixed.
