### ISSUE TITLE
Automatic Docker builds

### ISSUE THREAD

**Issue by djtm** [syncthing/syncthing#2857]
I've written some build scripts to create docker scratch images for the files offered (all linux architectures). Feel free to include them into your build scripts using your own repository.

https://github.com/djtm/syncthing-docker-scratch.git

Users may use the run.sh:
https://github.com/djtm/syncthing-docker-scratch/blob/master/run.sh

**Comment by calmh** [comment]
Thanks. Looking at the Docker file, I suspect relaying and usage reporting doesn't work because there are no CA certificates?

**Comment by djtm** [comment]
Probably. How do I test that?

**Comment by calmh** [comment]
Relaying is easy, as it doesn't work and you get a red "0/1" on that in the UI :)

**Comment by djtm** [comment]
Yes I do get that. And oddly `-v /usr/share/ca-certificates/:/usr/share/ca-certificates/:ro` doesn't seem to help.
