### ISSUE TITLE
Syncing stuck at 0% for newly added device

### ISSUE THREAD

**Issue by cattledogit** [syncthing/syncthing#2858]
Two devices are syncing fine: 1.) Win 10 64-bit v0.12.20, 2.) Android v0.12.20 (Note 2)

Added a third device today, but it's stuck at "Syncing (0%)": 3.) Android v0.12.20 (Nook HD+ running cyanogenmod)

This problem was seen previously, but reported as resolved.

**Comment by AudriusButkevicius** [comment]
Please use the forums, as this is a support issue, and not a bug report.
