### ISSUE TITLE
Syncthing Android UI crashes on launch on Source method getMenu in Source class android.support.v7.widget.ActionMenuView

### ISSUE THREAD

**Issue by actinmyosin** [syncthing/syncthing#2861]
Syncthing Android UI immediately crashes on launch on Source method getMenu in Source class android.support.v7.widget.ActionMenuView

Per web searches for this topic, this can be addressed by using a try-catch statement around the menu call as documented at:
https://www.reddit.com/r/androiddev/comments/2lluck/appcompatv7_v2100_causing_crash_on_samsung/clwd14p

try {
        ((ActionBarActivity) activity).setSupportActionBar(toolbar);
    } catch (Throwable t) {
        // do nothing
    }

Other search results say that Proguard can also take care of the problem.

### Version Information

Syncthing Version: v0.7.11
OS Version: Android 4.2.2 on Samsung SCH-I435 aka serranoltevzw

**Comment by calmh** [comment]
Sorry, this needs to be opened in http://github.com/syncthing/syncthing-android/issues; we don't do Android here. :)

**Comment by actinmyosin** [comment]
Thanks. Re-opened as https://github.com/syncthing/syncthing-android/issues/591
