### ISSUE TITLE
Folder or file name with Unicode characters causing Out of sync

### ISSUE THREAD

**Issue by baddwin** [syncthing/syncthing#2863]
I got Out of sync status in the remote machine.

 - I added a folder which contains folders and files with unicode characters (Japanese kanji) in my local system (Fedora).
 - the remote machine (Raspberry Pi) occurs Out of sync allegedly due to unicode characters in the filename
 - I have tried renaming one folder to latin, and it was synced and pushed to Raspberry Pi

![syncthing-error](https://cloud.githubusercontent.com/assets/7449857/13975776/92ef6144-f0eb-11e5-9b59-36a2d3b239ce.jpg)

![syncthing-error1](https://cloud.githubusercontent.com/assets/7449857/13975782/a450192e-f0eb-11e5-9006-3d3a341f5235.jpg)

`EDIT`: The error log is "invalid argument" after unicode filename, just like [#415](https://github.com/syncthing/syncthing-android/issues/415)

### Version Information

Syncthing Version: v0.12.20
OS Version: Windows 7, Fedora 23, Linux ARM (Raspberry Pi)
Browser Version: newest Chrome and Firefox

**Comment by wweich** [comment]
Is the folder on RPi local or remote (smb, nfs, ...)?
What file system does the drive in `/mnt/data/Datadocs/` have?

**Comment by baddwin** [comment]
RPi is remote, and the folder is its local, in a USB flash drive, which is `vfat` formatted

**Comment by wweich** [comment]
AFAIK vfat / Fat32 does not support UTF-8.
And as NTFS has its issues with Linux, you should format the drive in ext4 or another Linux file system, to sync UTF-8 folder-/filenames.

**Comment by baddwin** [comment]
is that so? maybe I didn't add `utf8` option on the mounting of the drive then

**Comment by baddwin** [comment]
Okay, solved. Thanks @wweich for your comment. You pointed out the culprit. :grin:
I added `utf8` in the `/etc/fstab` in RPi, and just rebooted it, and the sync progress is moving.

![weberror2](https://cloud.githubusercontent.com/assets/7449857/13978474/fb2bebb6-f103-11e5-92c1-3f7b7fb3675b.jpg)
