### ISSUE TITLE
Clicking "Rescan" does nothing (because of 403 error)

### ISSUE THREAD

**Issue by hakakou** [syncthing/syncthing#2864]
When I click Rescan All or Rescan on an individual folder, nothing happens. I tried opening the console in firefox, and I see the following:

POST http://127.0.0.1:8384/rest/db/scan   -   403 Forbidden
(Response Tab):  CSRF Error

I just upgraded to v0.12.21, Windows (64 bit), although sometimes I saw this in the previous version also.

**Comment by calmh** [comment]
Your browser has forgotten the CSRF cookie, or we've screwed something up. Given that this doesn't happen to most people, some investigation is needed...

**Comment by AudriusButkevicius** [comment]
You just need to refresh the page. It seems your security token just expired.

**Comment by hakakou** [comment]
I'll give you some extra info: This error has been happening to me for the last 3 months. When syncthing starts producing this error, the only thing that can fix it is to kill the process and let it restart. This is because:
- The error does not fix if I close and reopen firefox.
- The error does not fix if I try in in chrome or edge.
- I cannot restart syncthing from the browser, because that also produces a POST command resulting in a 403 error.
- Only solution, as I'm running as a service, is to kill the process in task manager and wait till it restarts.

If you have any suggestions I'll try them.

**Comment by AudriusButkevicius** [comment]
Does this happen immediately after starting syncthing? Do you have some proxy/browser addon/network traffic interceptor?

**Comment by hakakou** [comment]
No, it happens only after hours of use. Basically at some point I go to the control panel to do a manual rescan, and I discover this, so I do a restart to continue.

**Comment by AudriusButkevicius** [comment]
Can you check what cookies/headers your browser is sending?
Also, can you copy the XHR for requests when this happens?

**Comment by lkwg82** [comment]
Plz provide some information.
