### ISSUE TITLE
Syncthing fails to sync a few remaining Gigabytes of Data

### ISSUE THREAD

**Issue by ekianjo** [syncthing/syncthing#2865]
I am maintaining between two computers a pretty big archive of files (more than 400 Gigabytes), and until recently there was no problem it seems, but now that I reach the end of the sync, I have a remaining 15 Gb of files that refuse to be synced. On the target machine for sync, the sync client aknowledges that it's missing those files, but all download stops and there no more progress. The source computer is set as "master" for that folder. Both machines run the latest version of syncthing (12.20) and both are on Linux, x86 architecture (64 bits processor). I cannot see any error messages in the terminal either.

Any idea what I can do to find out the source of this problem ?

**Comment by AudriusButkevicius** [comment]
Given this query is of a support nature, please raise this on the forums and provide screenshots from both sides. If there is an actual bug, we can reopen it later.
