### ISSUE TITLE
PDF files on releases are nginx error 301 web pages.

### ISSUE THREAD

**Issue by chdorb** [syncthing/syncthing#2873]
The files Getting-Started.pdf and FAQ.pdf are are nginx error 301 web pages in v0.12.21 releases for Linux. (I didn't check the other archives)

`$ pwd
/tmp/syncthing-linux-386-v0.12.21
 $ cat Getting-Started.pdf FAQ.pdf 
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
$
`

### Version Information

Syncthing Version: v0.12.21
OS Version: Linux 386 and amd64 (at least)

**Comment by calmh** [comment]
Heh. That's not awesome.

**Comment by calmh** [comment]
Resolved and rereleased. Thanks.
