### ISSUE TITLE
Feature Request: Selecting disable/enable ipv[4,6] or even filter ranges+protocol

### ISSUE THREAD

**Issue by monkz** [syncthing/syncthing#2879]
It would be nice to ignore IPv6 or IPv4 adresses per configurationfile or cli parameter.

Reason: In some situations i've a tunnel active that provides me with ipv6 - but is horribly slow.
In this case i would need to be able to tell syncthing what ip version it should prefer - to take a faster route.

**Comment by AudriusButkevicius** [comment]
You can already do that, by changing to a specific listen address.

**Comment by monkz** [comment]
Seems like this is prevented by "isUnspecified()".
My listenAdress is tcp://0.0.0.0:22000, but if my tunnel is active it still takes connections via IPv6

And if I may quote the documentation:
Wildcard and port (0.0.0.0:12345, [::]:12345, :12345)
    These are equivalent and will result in Syncthing listening on all interfaces and both IPv4 and IPv6

**Comment by AudriusButkevicius** [comment]
So I agree with your intuition, but it is the way it is, and you can go argue with Go developers about this.

This is essentially a dup of #1305

**Comment by monkz** [comment]
Yes, i'll have a look at Go's network routines, and no, as interfaces can have multiple adresses, choosing protocol is still a different request.

**Comment by monkz** [comment]
https://github.com/syncthing/syncthing/blob/8ff7531f89305f9184268a6fdc21dd03efab07bf/lib/connections/connections_tcp.go
If "tcp" would be replaced by "tcp4" in some places - ipv6 would be ignored. https://golang.org/pkg/net/#ListenTCP

**Comment by AudriusButkevicius** [comment]
Yes, but we don't want to ignore ipv6, as that makes no sense.

**Comment by monkz** [comment]
Not everytime, i agree. But in some situations a ignore-ipv6 or ignore-ipv4 is needed.
Even ssh has a -4 and a -6 switch.
In this case syncthing might need to check if listenAdress is tcp4://0.0.0.0:22000 and sets every "tcp" to "tcp4".
If i might have a 6-to-4-tunnel i would like to disable ipv6, so i would set tcp6://0.0.0.0:22000 and ignore ipv4 in a analog way.

**Comment by calmh** [comment]
Resolved by 690837d

**Comment by monkz** [comment]
Thank you very much!!!!! and Tack så mycket!
