### ISSUE TITLE
Performance regression in memory use

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2882]
My Syncthing used to require around 100-150 MB, sometimes peaking up close to 200 MB. Current master branch idles at around 650 MB, peaks at 1.2 GB. Something odd has happened, either due to the 1.6 GC or due to something else we've done. Merits investigation.

![image](https://cloud.githubusercontent.com/assets/125426/14043876/86fdfdf6-f289-11e5-8be7-a055a5d9d44a.png)

Step one would be to recompile with 1.5 and see if that makes a difference. If not, it's bisection time.

**Comment by calmh** [comment]
It's not the compiler - latest master compiled with Go 1.5.3 behaves the same.

**Comment by calmh** [comment]
Looks like index data kept alive during scanning and index reception...


https://nym.se/r/uhvs.svg

**Comment by AudriusButkevicius** [comment]
git bisect?

**Comment by calmh** [comment]
Yep. I'm first of all creating a reliable benchmark for resource usage during scan (initial + "fast") and then running that to narrow this down.

**Comment by lkwg82** [comment]
For the finish: Do you get that automated to have a regression test? (I know it can be hard.)

**Comment by calmh** [comment]
No, but it'll get us nice graphs of the data for every version since forever and into the future, which we can draw conclusions from.

I missed drawing any obvious conclusions so far because I see roughly the same numbers for the last version before the v0.13 split (i.e. before my db format change went in) and current master...

**Comment by calmh** [comment]
My tests didn't bring up anything unusual. This is from scanning ~50 gigs of data in 200.000 files; both full scan (no database) and quick scan (contents are already scanned) uses about the same amount of memory currently as in v0.12.0. Will dig deeper...

**Comment by calmh** [comment]
For what it's worth I've reproduced it with a bigger folder and narrowed it down to the scanning, and mostly the database walk after the directory walk. Here are some screenshots.

![screen shot 2016-03-29 at 17 11 36](https://cloud.githubusercontent.com/assets/125426/14113094/c0c7a104-f5d1-11e5-88df-f34791f079e7.png)
![screen shot 2016-03-29 at 17 11 42](https://cloud.githubusercontent.com/assets/125426/14113097/c5aee218-f5d1-11e5-9d77-c6b6f3aba1f6.png)

Correlating the times on the "memory in use" graph with the console log at the bottom we can see that it hits a minimum of 44M in use at 15:09:10 which is at

```
[I6KAH] 2016/03/29 17:09:10.686357 walk.go:167: DEBUG: Walk progress done /srv/foto/ [] 131072 &{[{0xc8203121e0 true} {0xc820312320 true} {0xc820312460 true} {0xc82008a0a0 true} {0xc82008a1e0 true} {0xc821cc4000 true} {0xc821cc4140 true} {0xc821cc4280 true}] true 0xc821cca0c0 dcf344213b95af5048d985e7b791f970 0xc8203cf680 0xc8207eb290}
[I6KAH] 2016/03/29 17:09:10.686385 model.go:1424: DEBUG: model@0xc82008c000 completed walk for default
[I6KAH] 2016/03/29 17:09:10.686431 verboseservice.go:49: VERBOSE: Scanning folder "default", 0% done (0.0 MB/s)
[I6KAH] 2016/03/29 17:09:10.686471 model.go:1442: DEBUG: model@0xc82008c000 starting database scan for  default
```

Then it balloons to almost 400M at 15:09:15, which is

```
[I6KAH] 2016/03/29 17:09:10.686471 model.go:1442: DEBUG: model@0xc82008c000 starting database scan for  default
[I6KAH] 2016/03/29 17:09:14.867862 model.go:1497: DEBUG: model@0xc82008c000 completed database walk for default
```

i.e. where we walk the database looking for deleted files.

Note also that this memory isn't *released* until the next scan, despite me having a `runtime.GC()` run in the background every five seconds. So something is being retained here that should not be...

**Comment by AudriusButkevicius** [comment]
Wild guess, disable scan progress reporting (though that was there before).

**Comment by calmh** [comment]
No, that's not the guilty party. Just now I've commented out the entire contents of the fs.WithPrefixedHaveTruncated() call and then usage is fine. I think something is getting retained somewhere there, combined with my XDR changes that keeps references to the underlying buffer, and so on. Haven't narrowed down what yet, though.

<img width="1630" alt="screen shot 2016-03-29 at 17 31 54" src="https://cloud.githubusercontent.com/assets/125426/14113646/2f406b32-f5d4-11e5-80cc-58d3f1317dcb.png">

**Comment by calmh** [comment]
Yep, found it. The guilty call is

```go
if ignores.Match(f.Name) ...
```

because this causes the string `f.Name` to be inserted into the ignore cache, but that string is just a reference to a part of the buffer we deserialized the FileInfo from, which then gets retained.

**Comment by calmh** [comment]
With this:

```go
if ignores.Match(string([]byte(f.Name))) ...
```

it looks as normal:

![screen shot 2016-03-29 at 17 44 10](https://cloud.githubusercontent.com/assets/125426/14114079/f5b01b40-f5d5-11e5-9939-ac98c2c1ff4b.png)

but that "fix" feels a little too magical...

**Comment by calmh** [comment]
(And yes that's a neat performance tracing tool I've hacked together that I'll publish at some point :)

**Comment by plouj** [comment]
Maybe we should have a NameCopy() method on those objects (or just Name()
that does a copy)?

**Comment by calmh** [comment]
Sure, naming and commenting can explain what's going on, it's just a bit scary as I wonder in how many other places we may have issues like this that are currently not plainly visible by just looking at the code... The XDR changes I did to cause this may be a little dangerous.

**Comment by lkwg82** [comment]
In this situation static code analysis comes to my mind. Sth  like findbugs or sonarqube (with rules of easy pitfalls). Is there sth for go, you know of?

**Comment by plouj** [comment]
Then why did you do it? :)

Perhaps using getters and making the default behaviour to copy while allowing to use direct references to original buffers possible via alternative getters (... C++ anyone?)

**Comment by calmh** [comment]
@lkwg82  I'm not sure how that would catch this. This isn't a bug, this is just strings being larger than they look because we do something unsafe in another place. I think a  manual audit of places were was pass the f.Name and it doesn't go out of scope would be the best way.

@plouj We save doing a shitload of allocations by not copying all strings and `[]byte`s at deserialization time.

**Comment by AudriusButkevicius** [comment]
Would it make sense to have many more small buffers potentially capped at //max? Or some other annotation to use a separate buffer pool for one of the attributes?

**Comment by calmh** [comment]
IlI think the proper solution to this one is to remove the unsafe optimization for strings in the XDR deserializer. The thing we juggle the most is the FileInfo and it only has the one string. Copying that one directly at deserialization time is bearable. The big win is in keeping the optimization for []byte as that affects the potentially large block list.

Then we get rid of the risky and unexpected behavior of strings. Byte slices are already something you *expect* to have this behavior so won't bite us like this.

**Comment by AudriusButkevicius** [comment]
Agree
