### ISSUE TITLE
generate api documentation from code

### ISSUE THREAD

**Issue by lkwg82** [syncthing/syncthing#2886]
I've seen some issues in the docs which request updating api documentation.

Can we add some inline api documentation in the code?

As of today we need discipline to add/update the documentation. I think of streamlining some pieces of the docs. 

This can be extended to the manpage.

When we solve this, some tickets would never been arised. I'm really new to the go ecosystem. So I lack examples what to use.

**Comment by calmh** [comment]
:+1:

**Comment by lkwg82** [comment]
How does this looks like?

- http://engineroom.teamwork.com/generate-api-from-annotations-in-go/
- https://github.com/betacraft/yaag

**Comment by lkwg82** [comment]
too old, seems not needed
