### ISSUE TITLE
Syncthing isn't as good at reconnecting as it once was

### ISSUE THREAD

**Issue by jpjp** [syncthing/syncthing#2899]
Using v0.12.21 on Linux right now.

I noticed that when the gateway goes down, syncthing doesn't reconnect (very fast). I have to restart syncthing to make things work again. e.g. all remote devices right now are showing as down, but they aren't, and the gateway was rebooted 24 hours and 15 minutes again. Also occurs on another node when the vpn server is restarted.

I'll debug this a bit more when I have a chance.

**Comment by AudriusButkevicius** [comment]
I think it's the DNS issue since 0.7.12

**Comment by calmh** [comment]
0.7.12?

**Comment by AudriusButkevicius** [comment]
Android version

**Comment by calmh** [comment]
Why would that affect Linux? Is there some Android here? @jpjp `STTRACE=discovery,connections` please :)

**Comment by AudriusButkevicius** [comment]
Probably replied while drunk with one eye closed.

**Comment by calmh** [comment]
:) Regardless, there is some merit to the complaint. I have two of my devices that have real difficulties connecting to each other. What looks to be happening now is some race condition in the "switching connection" logic.

- Connection is established via relay for some reason related to connection attempts in one direction timing out
- A real connection is established later
- Device `A` closes the relay connection and begins negotiating on the real connection
- Device `B` removes the relay connection as it was closed, then hits the "switching connections" logic and closes the *real* connection
- Devices end up disconnected, `goto 10`

**Comment by AudriusButkevicius** [comment]
I'd like to see the logs from both sides.

**Comment by calmh** [comment]
https://gist.github.com/calmh/220cbbdceb4c7788b075707ac7732127

It's unfiltered so there's some other crap. You want to look at the connection attempts between 4OODC and AFQDM. When the log begins they are connected via relay and I have just fixed a firewall that prevented a direct connection over IPv6 from one direction to the other.

At 10:16:53 the connection gets established AFQDM->4OODC and the switching logic happens, but the newly established connection gets dropped as well for some reason, by 4OODC at 10:16:56 from the looks of it, which is where I suspect a bug in the switching stuff.

Then things get successfully established on the next try, maybe since there wasn't already at relay connection at that point so no switching troubles. But I'm just guessing.

**Comment by jpjp** [comment]
...and I can't reproduce the problem any more, despite being hit by it lots recently :/

**Comment by AudriusButkevicius** [comment]
So you are right, s.connType never goes through a delete() statement, so it probably always thinks it's connected.

Also there is a race between model.AddConnection and s.connType[deviceID] = newConnectionType.

**Comment by jpjp** [comment]
I just had this happen again, and without debugging on, again :-/

If my public ip changes, syncthing permanently loses its connection to external nodes. All nodes on the local network continue to work.

**Comment by AudriusButkevicius** [comment]
Well that's probably todo with discovery breaking at that point.

**Comment by calmh** [comment]
If those connections are incoming only, yeah. It'll reannounce to the discovery server in half an hour or so - is "permanently" longer than that?

**Comment by jpjp** [comment]
It got to 12 hours before I restarted it.

**Comment by calmh** [comment]
That's odd. The connections that do succeed, are the incoming our outgoing (from the perspective of the thing behind the changed IP address)? Sounds like there could be an actual issue there somewhere.

**Comment by jpjp** [comment]
The nodes on the internet also lost connection to this machine that changed ip.

So both machine on the lan routing through this gateway machine with a changed ip lost all connection to outside nodes, and all outside nodes connecting directly to the gateway machine lost connectivity.

**Comment by AudriusButkevicius** [comment]
I think it will be something todo with discovery.
