### ISSUE TITLE
Devices keep reappearing when using "Introducer" devices

### ISSUE THREAD

**Issue by OscarS** [syncthing/syncthing#2900]
My current setup consists of 5 devices that have been configured to introduce added devices to each other as to simplify adding in new devices when the need arises. The problem with that is that as soon as I try to delete a device it is being reintroduced from one of the other devices. 
Ideally I expect that deletions of devices propagate in a similar fashion as adding new ones - meaning that on devices where I am configured as "Introducer" device the deleted device should be deleted too. 

### Version Information

Syncthing Version: v0.12.21
OS Version: Ubuntu 15.04 (64 bit)
Browser Version: /

**Comment by AudriusButkevicius** [comment]
No, it's working as intended.

**Comment by AudriusButkevicius** [comment]
There are other tickets which rage with "this is not how I expect it to work", so we can consider this a duplicate.
