### ISSUE TITLE
Some settings lost

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#2906]
Setting the whole from the GUI, some settings are lost on restart if the bunch of changes included switching from http to https for the GUI.

Maybe related to canton7's https://github.com/syncthing/syncthing/issues/2788

### Version Information

Syncthing Version: v0.12.21, Linux (64 bit)
OS Version:  Ubuntu 14.04
Browser Version: FF38

**Comment by calmh** [comment]
> switching from http to https for the GUI

Possibly the GUI needs a reload at this point to work properly, assuming that you mean that changes made after this point don't take effect?

**Comment by bugith** [comment]
No calmh, I'm aware I have to reload the GUI and create a certificate exception for the self signed cert. This shows this very setting at least was not lost.
I have to setup new clients so I'll be careful about the behaviour and which parameters are lost.

**Comment by calmh** [comment]
Something to reproduce this would be good, then. The "save" button pushes a blob containing all of the settings, so for some of them to take and not others would be odd. But I could see there being problems of some kind just around the http/https transition...

**Comment by lkwg82** [comment]
plz describe a procedure to reproduce this issue. Else I suggest to close it.
