### ISSUE TITLE
Consider if ignore caching can be refactored to use less RAM

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#2910]
On my current "production" setup, with just a single folder with 140k files in it, ignore caching represents half of Syncthing's RAM usage. This is the resource profile when doing a periodic scan with cacheIgnoredFiles=false:

![screen shot 2016-03-29 at 18 53 00](https://cloud.githubusercontent.com/assets/125426/14116411/e8159dde-f5df-11e5-886e-f06c42d6ba5f.png)

This is the exact same test with cacheIgnoredFiles=true:

![screen shot 2016-03-29 at 18 55 26](https://cloud.githubusercontent.com/assets/125426/14116420/efe076ba-f5df-11e5-9cf5-1d0c57ab9592.png)

Note that approximately twice as much memory has been allocated from the OS, 100M vs 50M. The actual CPU time to perform the scan looks about equivalent in both cases, too. But this is on a fairly fast box - the CPU gains may be much higher on lower end devices so we should at least verify that before drawing the conclusion that it's pointless. Regexp processing may have gotten faster in the later Go releases, though.

**Comment by calmh** [comment]
Indeed, on darwin/amd64 at least the uncached matching code is about twice (!) as fast on Go 1.6 as it was in Go 1.3. Nice work, Go team.

```
jb@syno:~/s/g/s/s/l/ignore $ go version
go version go1.6 darwin/amd64
jb@syno:~/s/g/s/s/l/ignore $ go test -bench . -benchmem
PASS
BenchmarkMatch-8      	  100000	     16881 ns/op	      12 B/op	       0 allocs/op
BenchmarkMatchCached-8	10000000	       150 ns/op	       0 B/op	       0 allocs/op
```

```
jb@syno:~/s/g/s/s/l/ignore $ GOROOT=/usr/local/go1.3 /usr/local/go1.3/bin/go test -bench . -cpu 8
PASS
BenchmarkMatch-8	   50000	     32166 ns/op
BenchmarkMatchCached-8	20000000	       118 ns/op
```

**Comment by calmh** [comment]
Also relevant is that my patterns are very simple.

```bash
jb@zlogin4:/s/foto $ cat .stignore 
Lightroom
Not These
```

This means evaluating them is cheap, hence no real difference in the amount of CPU time above, and no value added by the cache. If I had a hundred complex regexps the situation would be vastly different...

**Comment by AudriusButkevicius** [comment]
It's off by default, so I guess case closed.
