### ISSUE TITLE
Show a progress bar when running `syncthing -upgrade`

### ISSUE THREAD

**Issue by xuhdev** [syncthing/syncthing#2911]
It would be a nice feature.

**Comment by canton7** [comment]
Does this normally take more than about a second for you? It's not a large download

**Comment by xuhdev** [comment]
@canton7 Depends on the connection, sometimes it can be a long time. Also consider people living in development countries...

**Comment by marrie** [comment]
I agree. It took about 2 seconds for the upgrade to happen, however, I was at a developed country where the best I could get was about 512kbps down. things took a while there and a 2kb document took about maybe 10 seconds. If the user does not want the progress bar maybe make it a toggle in the settings.

**Comment by calmh** [comment]
A progress bar would be somewhat contrary to our usual log based interface. However a progress report every few seconds along the lines of "downloading upgrade, x KB of y, z seconds remaining" would be fine. As an added bonus this would be invisible on a fast enough connection as the download would complete before the first report.

**Comment by xuhdev** [comment]
:+1:
