### ISSUE TITLE
syncthing-inotify + syncthing causes full rescan of folder instead of subs

### ISSUE THREAD

**Issue by pandian912** [syncthing/syncthing#2915]
touched a file named "s" inside test dir which is synced
then started syncthing-inotify and touched another file named "t"
```
[OK] 07:03:55 Watching test: /opt/syncthing/test/
[OK] 07:03:55 Syncthing is indexing change in test: [.stfolder]
[OK] 07:03:59 Syncthing is indexing change in test: [t]
```
now syncthing does a full scan and syncs both files "s" and "t"
```
[KDIZB] 2016/03/30 07:03:59.914405 walk.go:100: DEBUG: Walk /opt/syncthing/test/ [] 131072 &{[] true 0xc821bc4700 d41d8cd98f00b204e9800998ecf8427e 0xc820c4b680 0xc8207bc548}
[KDIZB] 2016/03/30 07:03:59.914443 walk.go:488: DEBUG: checkDir /opt/syncthing/test/ &{test 4096 2147484141 {63594918239 405156197 0x11308a0} {51713 524403 2 16877 501 501 0 0 4096 4096 8 {1458645326 27682714} {1459321439 405156197} {1459321439 405156197} [0 0 0]}}
[KDIZB] 2016/03/30 07:03:59.914568 walk.go:246: DEBUG: ignored: .stfolder
[KDIZB] 2016/03/30 07:03:59.921951 walk.go:304: DEBUG: rescan: File{Name:"", Flags:00, Modified:0, Version:[], Size:0, Blocks:[]} 1459321423 -rw-rw-r--
[KDIZB] 2016/03/30 07:03:59.921981 walk.go:319: DEBUG: to hash: s File{Name:"s", Flags:0664, Modified:1459321423, Version:[{KDIZBWU 1}], Size:0, Blocks:[]}
[KDIZB] 2016/03/30 07:03:59.922032 walk.go:304: DEBUG: rescan: File{Name:"", Flags:00, Modified:0, Version:[], Size:0, Blocks:[]} 1459321439 -rw-rw-r--
[KDIZB] 2016/03/30 07:03:59.922056 walk.go:319: DEBUG: to hash: t File{Name:"t", Flags:0664, Modified:1459321439, Version:[{KDIZBWU 1}], Size:0, Blocks:[]}
[KDIZB] 2016/03/30 07:03:59.922091 walk.go:189: DEBUG: real to hash: s
[KDIZB] 2016/03/30 07:03:59.922129 walk.go:189: DEBUG: real to hash: t
[KDIZB] 2016/03/30 07:03:59.922352 walk.go:167: DEBUG: Walk progress done /opt/syncthing/test/ [] 131072 &{[] true 0xc821bc4700 d41d8cd98f00b204e9800998ecf8427e 0xc820c4b680 0xc8207bc548}
```

**Comment by pandian912** [comment]
syncthing-inotify version 0.6.8
syncthing 0.12.21

**Comment by AudriusButkevicius** [comment]
And whats the issue?

**Comment by AudriusButkevicius** [comment]
inotify aggregates changes, and scans a directory layer up if it finds it more appropriate to.

**Comment by calmh** [comment]
Probably the root cause here is that `t` is unknown, so a scan request of that will result in a scan of the containing directory. This is necessary and by design, but could possibly be optimized somehow...

**Comment by AudriusButkevicius** [comment]
Not sure what that would bring to the table though. If a file is already scanned, it should only be a stat() call which is cheap. If it's not scanned, you probably want it scanned anyway.

**Comment by calmh** [comment]
I think currently, for all unknown entries, we scan the (closest known) parent instead. We need to that when asked to scan foo/bar/baz if we don't know about foo/bar (must scan foo/bar before foo/bar/baz), but if we know about the parent we should be fine just scanning the unknown file directly... Needs some  investigation.

**Comment by pandian912** [comment]
yeah scanning just the unknown file was the expected behaviour, atleast thats what I understood from the doc.

The scenario is I have a huge directory where files get added often. I want the newly added files synced across to other boxes. I don't want a full scan for every new file added.

In this case full scan is very costly potentially taking several minutes, so I would prefer if just the new file is added to index and synced across.

Even if inotify missed notifying about a new file, those files will be eventually handled via the periodic scan which is done every 2/3 hours. But doing a full scan for every new file added is not what is expected.

The doc does not clearly say what happens when a new file is requested to be scanned.
https://docs.syncthing.net/rest/db-scan-post.html
atleast this qualifies as a documentation bug/improvement.

**Comment by pandian912** [comment]
@AudriusButkevicius inotify makes a scan api call with the required sub filled in.
I dont see any issue with inotify.
rather syncthing does a full scan instead of scanning just the files in the sub list

**Comment by AudriusButkevicius** [comment]
So improving the docs/functionality etc is a fair point hence reopening, though I don't understand how scanning a specific file will help you skip some large directory which is under the watched tree.

**Comment by plouj** [comment]
I think this can only happen if you do something like the following:
- start syncthing and let it do a full scan
- create a new huge directory
- start syncthing-inotify
- touch a file within the huge directory

So my suggestion is just to wait and let syncthing scan all of the new
files so that it knows about them. Afterwards further new files won't cause
ST to rescan everything. This doesn't seem like a typical use case and it
will be handled better once inotify is integrated into ST, which will have
the effect of starting syncthing-inotify as early as possible.

**Comment by pandian912** [comment]
@plouj  All files are created and scanned previously with syncthing.
To add more details, syncthing root has 25000+ files which are already scanned and synced and inotify is started.

Now when a new file is created
1) inotify sends a scan api call with the sub containing only the new file.
2) syncthing does a full scan of the root which takes 5 to 10 seconds and a spike in cpu utilisation (http://pastebin.com/YP0jT4Fj) whenever a new file is added.

The above happens whenever a new file is created.
I agree its not a typical use case but i see no reason why syncthing shouldn't handle this.
Syncthing recieves an api call with file list specified with sub, syncthing should limit itself to scanning the list of files provided in the api call and scan the parent directory only if its not already scanned as pointed by @calmh

**Comment by plouj** [comment]
Ah, I was a little confused before, but I get it now. Yeah, we definitely
should only scan the new items in this case. I can work on it. This should
be easy to test with an integration test as well.

**Comment by pandian912** [comment]
I think the change needs to go into 
lib/model.go 
func unifySubs()

The function should recursively go through the file path removing one hierarchy per recursion till it finds the already scanned directory or till it finds the filepath.Separator and then return the filepath in the previous recursion.

AFAIK it should not return nil unless the sub list is nil

This is based on the assumption that scanner.Walker can accept Subs which are not already indexed.

**Comment by calmh** [comment]
@plouj No need to be that heavy handed, there are unit tests on unifySubs. I think the rule should simply be that we can scan whatever asked for as long as we know of the parent already.
