### ISSUE TITLE
notify if a remote device has been unseen for x days (feature request)

### ISSUE THREAD

**Issue by mikp** [syncthing/syncthing#2919]
Hi Syncthing community, 

I use Syncthing for many remote devices to stay in sync with a master and collect files from them changed on a regular basis. To see if everything works correctly, I currently have to check on last seen time and transmission status manually. 
One idea would be to parse the logs for this information. However, I would like to suggest a new feature that highlights devices in the GUI that have not been available for some time. This could be a value defined per remote device on the "master" or one-for-all. This way, one would easily see where there are connection problems without any additional work or tools. 

What do you think about this?

**Comment by AudriusButkevicius** [comment]
I think this is too specific to your needs to become a mainstream feature. All of the information in the UI is available via the rest API, including last seen time. I think you should build something external on top of that instead.

**Comment by lkwg82** [comment]
I agree with @Audrius, this is something for a third party tool. There is an Rest Api. So go on!

**Comment by AudriusButkevicius** [comment]
The discussion, if any, can continue under a closed ticket.

**Comment by mikp** [comment]
Thanks, REST API will do!

**Comment by lkwg82** [comment]
If you hack something runnable please consider sharing with twitter under hashtag #synchting with a link to your github repo.
