### ISSUE TITLE
Endless restart

### ISSUE THREAD

**Issue by MischenkoAleksandr** [syncthing/syncthing#2920]
### Version Information

Syncthing Version: v0.12.21
OS Version: Linux Mint 17.3 Rosa
Browser Version: Firefox 45.0

Trying to sync a folder between 3 machines on:
- Win 7 Pro,
- Win Server 2008 and
- Linux Mint 17.3 Rosa
and Syncthing on Mint falls in endless restart with messages like:

panic: leveldb/table: Writer: keys are not in increasing order: "\x02Семейный фотовидеоархив\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa5U}\x05\x1f\nL\xf5\x9e_\x04\xe3\xca\xeb\xef\xc5\xe3\u007f \x15\xd2uM\xfccY\xcaa\xe9\xb4$\x002011.10.08 Крестины/08.10.2011_140530.mpg\x00\x9c7\xd7\x00\x00\x00\x00", "\x02Семейный фотовидеоарх\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x82C\xaa&݈^\u007f@\xb0U\x1f\x8b\xc1B\r\xf5\x80\xe1\xf86\v@\x95\x158\xa2\a\xd0\r2015.03.05/Видео/00221.MTS\x01\x17T\xbb\x00\x00\x00\x00"
[monitor] 19:48:32 WARNING: Panic detected, writing to "/home/user/.config/syncthing/panic-20160331-194832.log"

[panic-20160331-194832.log.zip](https://github.com/syncthing/syncthing/files/198201/panic-20160331-194832.log.zip)

**Comment by AudriusButkevicius** [comment]
So to recover, remove the index directory from syncthings home directory, and see if it happens again. Any ideas what lead to this?

**Comment by MischenkoAleksandr** [comment]
Tnx, but I’m already fix it.
I noticed that with every restart the number of files here grows:
/home/user/.config/syncthing/index-v0.11.0.db
Have a look at LOG file and found that error at the end of a file again.
Well, i just stop Syncthing, del all files from there and start Syncthing.

I don't know what lead to this, but may be i can be more helpful if i can understand what's this means:
"\x02Семейный фотовидеоархив\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa5U}\x05\x1f\nL\xf5\x9e_\x04\xe3\xca\xeb\xef\xc5\xe3\u007f \x15\xd2uM\xfccY\xcaa\xe9\xb4$\x002011.10.08 Крестины/08.10.2011_140530.mpg\x00\x9c7\xd7\x00\x00\x00\x00", "\x02Семейный фотовидеоарх\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x82C\xaa&݈^\u007f@\xb0U\x1f\x8b\xc1B\r\xf5\x80\xe1\xf86\v@\x95\x158\xa2\a\xd0\r2015.03.05/Видео/00221.MTS\x01\x17T\xbb\x00\x00\x00\x00".

**Comment by AudriusButkevicius** [comment]
That's what I meant by deleting the index.
The error message just explains which keys have issues.

**Comment by calmh** [comment]
This feels like a leveldb bug though, at the very least?

**Comment by AudriusButkevicius** [comment]
Maybe, but the key contains folder label rather than an int ID which is strange.

**Comment by calmh** [comment]
That's expected for v0.12 though. You live in the future. :)

There has been a number of changes and fixes to the leveldb package lately that we have not merged though, so perhaps we should disregard this for the time being and see if it comes back after upgrading that package and with the new database format...
