### ISSUE TITLE
use root for access user folder

### ISSUE THREAD

**Issue by goldalworming** [syncthing/syncthing#2923]
Hi, I use centos in my OS

I have folder /app/a that owned by user a, and /app/b owned by user b
how to sync both folder?

can I run it from root to sync all folder or I have to use syncthing in every user?

**Comment by lkwg82** [comment]
yes you can.

**Comment by lkwg82** [comment]
you dont need to run for every user a separate instance.

Please use the forum @ https://forum.syncthing.net to ask questions.

**Comment by wweich** [comment]
Just as a warning: If you run Syncthing as root, all files it creates will be owned by root, so the users (a, b) will potentially not be able to access them.
