### ISSUE TITLE
Feature request: Show me the most recently synced files, both globally, and per share/device.

### ISSUE THREAD

**Issue by seansimonanimation** [syncthing/syncthing#2924]
Syncthing Version: v0.12.21
OS Version: Windows 7/WIndows 10
Browser Version: SyncTrayzor browser

I love the flexibility that Syncthing provides me. It allows me to manage files between my team members, and the freedom that nested sharing allows lets me set up my organization the way I want.

There is one bit of functionality that Dropbox provides that I would like to see: When you click on the Dropbox tray icon, you get a list of the 30 or so most recently updated files. I haven't seen anything like this in Syncthing, and I haven't seen it as a feature request here on the Github, but would it be possible to add in a row to remote devices and shared folders that allow me to see the most recently updated files, and when they were updated?

I feel like this is something that is already most of the way there, it's just a matter of logging it, and showing the log.

Adding it into the GUI would make it an even better feature.
Thanks :)

**Comment by AudriusButkevicius** [comment]
It already shows the last file. 
Anyways, I think there already exists a ticket like this, but I am not in a position to find it over the phone.

**Comment by exokkk** [comment]
I would support to see more than only the last file.

**Comment by AudriusButkevicius** [comment]
If you want to support something, make a pull request.

**Comment by rmarskell** [comment]
I noticed that when I single-click on the icon in my taskbar, it shows a recently updated file list. It would be great to have a full log somewhere, but this is a great start.

**Comment by AudriusButkevicius** [comment]
Syncthing does not provide task bar icons, so its probably some wrapper you are using.

**Comment by rmarskell** [comment]
Ah, touché. I found this on a Google search for SyncTrayzor and assumed it was the same repo. Anyone looking for this feature should check it out: https://github.com/canton7/SyncTrayzor

**Comment by AudriusButkevicius** [comment]
Closed by #3694
