### ISSUE TITLE
UPnP could not setup

### ISSUE THREAD

**Issue by fanthos** [syncthing/syncthing#2926]
Syncthing Version: v0.12.21
OS Version: Windows 10

After I enable UPnP on my router, UPnP not working as excepted.

Failed to set UPnP port mapping: external port 0 on device ***.
Log shows upnp.go did not get my internal port correctly.
```
[2ERPN] 2016/04/01 13:28:28.117010 upnp.go:441: DEBUG: SOAP Request URL: http://192.168.101.1:5000/ctl/IPConn
[2ERPN] 2016/04/01 13:28:28.117010 upnp.go:442: DEBUG: SOAP Action: 
[2ERPN] 2016/04/01 13:28:28.117010 upnp.go:443: DEBUG: SOAP Request:

<?xml version="1.0" ?>
	<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
	<s:Body><u:AddPortMapping xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1">
	<NewRemoteHost></NewRemoteHost>
	<NewExternalPort>19894</NewExternalPort>
	<NewProtocol>TCP</NewProtocol>
	<NewInternalPort>0</NewInternalPort>
	<NewInternalClient>192.168.101.144</NewInternalClient>
	<NewEnabled>1</NewEnabled>
	<NewPortMappingDescription>syncthing-19894</NewPortMappingDescription>
	<NewLeaseDuration>3600</NewLeaseDuration>
	</u:AddPortMapping></s:Body>
	</s:Envelope>
```

**Comment by AudriusButkevicius** [comment]
You need to provide a bigger part of the log as you are only showing the request but not the response.

**Comment by fanthos** [comment]
That computer is not with me right now.
In the line `<NewInternalPort>0</NewInternalPort>`, 0 seems should be local port, like 22000.
I can upload full log later this week when I have physical access to the computer.

**Comment by AudriusButkevicius** [comment]
You should also post the content of your config.xml

**Comment by fanthos** [comment]
Thanks. I'll try it later
