### ISSUE TITLE
Syncthing UI shows "Connection Error" when connected

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#2932]
Syncthing UI shows "Connection Error" even though it is connecting to Syncthing without issue.

This appears to happen after a period of time, both in Chrome and in SyncTrayzor's embedded browser. Chrome's console shows that the standard requests (events, connection, status, error) are being made successfully, and `STTRACE=http` indicates that these are correctly responded to as 200's. 

Refreshing the browser clears the error.

Interestingly, with two browsers open showing the same problem simultaneously, refreshing one appears to clear the error on the other (?).

**Comment by AudriusButkevicius** [comment]
CSRF perhaps? Anything in the browser console?

**Comment by canton7** [comment]
I've using the API key, so it shouldn't be that.

The linked issue did have a console log which didn't display anything, but @dinosore seems to have deleted it for some reason so I can't double-check.

**Comment by canton7** [comment]
This *might* be being caused by Syncthing returning a 500, and the GUI getting into a funny state. Chasing that idea...

**Comment by canton7** [comment]
Well I've reproduced it in that I've hacked Syncthing to return a 500 for `/rest/system/status` a couple of times, then return 200's, and the "Connection Error" dialog never disappears.

**Comment by calmh** [comment]
500 return from there will indeed trigger a connection error dialog, although it's supposed to heal itself when it works again.

**Comment by canton7** [comment]
The only reference to that Connection Error dialog that I can find [is here](https://github.com/syncthing/syncthing/blob/3d71e686964ff254ff534ba6a4c843ef833269bb/gui/default/syncthing/core/syncthingController.js#L150), so there's no code that hides the modal after it's been shown.

**Comment by calmh** [comment]
I didn't know / had forgotten that we apparently differentiate between network errors and returned error codes. I guess in the general case this sort of makes sense as a sudden 4xx or 5xx error code indicates something is weirdly broken and GUI probably needs a reload.

**Comment by canton7** [comment]
Fair enough - that makes sense.

I *think* this issue will be resolved when #2854 is resolved, then, but I want confirmation from @dinosore to be sure.

**Comment by canton7** [comment]
Fairly sure this is the same as #2854, so closing.
