### ISSUE TITLE
update wikipedia article on syncthing

### ISSUE THREAD

**Issue by lkwg82** [syncthing/syncthing#2934]
To form a professional presentation of the syncthing tool, we should do some efforts in content marketing. With content marketing I mean clear and authentic introduction or overview articles, nothing dubious!

**Goals**
- Spread the word about this powerful project
- Attract more users / contributors

https://en.wikipedia.org/wiki/Syncthing
- [ ] update history of the project relationship with "pulse"
- [ ] describe or list core features
- [x] add a changelog history for the major version (0.1 ... 0.12), only end-user features
- [x] add some more external references of articles/blogs/comparisions etc.
- [ ] mention cross platform support
- [ ] describe how it works, starts here https://forum.syncthing.net/t/synchronization-algorithms/1143

Discussion on: https://forum.syncthing.net/t/please-help-us-to-renovate-wikipedia-article-about-syncthing/7108

**Comment by nrm21** [comment]
**The relaying performed is similar in nature to the TURN protocol, with the traffic TLS-encrypted end-to-end between nodes (thus even the relay server cannot see the data, only the encrypted stream)**

I just updated this on the wiki, can someone please verify this is true (Audrius I think you wrote the code for this).  If not factual feel free to remove/re-edit it.

**Comment by calmh** [comment]
Correct

**Comment by terrycloth** [comment]
I feel like this sort of thing should be discussed in the forum rather than a GitHub issue --- both because it has nothing to do with actually developing Syncthing itself or the protocol, and because Wikipedia articles about contemporary software require regular maintenance to keep up-to-date. Writing *about* Syncthing is sort of its own project.

**Comment by lkwg82** [comment]
This issue is about the current state and not about a regular update task. So you can see it as sth. that is big and unachievable or it is just this plain list of tasks. No task is specified which quality and depth is required. Just make it a little bit better.

This issue is about supporting the project with marketing and giving sth back.
