### ISSUE TITLE
Can't finish (master) folder sync

### ISSUE THREAD

**Issue by Kernald** [syncthing/syncthing#2940]
Hi,
I have a folder with 24999 items, ~561 GiB configured on a node (PNO7QTP) as a master folder. I added this folder to two nodes (XUHDX and another not mentioned in the later logs). Having only an ADSL connection at the time, uploading 500+ GiB took ages - that was expected. Now, I have a far better connection, and the upload finished on the XUHDX node. However, 8 files can't sync, I don't get why:
```
Apr 04 05:36:33 backup syncthing[17545]: [XUHDX] INFO: Puller (folder "musique", file "Explosions in the Sky/2016 - The Wilderness/01 - Wilderness.flac"): pull: peers who had this file went away, or the file has changed while syncing. wil
Apr 04 05:36:33 backup syncthing[17545]: [XUHDX] INFO: Puller: final: peers who had this file went away, or the file has changed while syncing. will retry later
Apr 04 05:36:33 backup syncthing[17545]: [XUHDX] VERBOSE: Finished syncing "musique" / "Explosions in the Sky/2016 - The Wilderness/01 - Wilderness.flac" (update file): peers who had this file went away, or the file has changed while sync
Apr 04 05:36:34 backup syncthing[17545]: [XUHDX] INFO: Folder "musique" isn't making progress. Pausing puller for 1m0s.
Apr 04 05:36:34 backup syncthing[17545]: [XUHDX] VERBOSE: FolderErrors events.Event{ID:2021, Time:time.Time{sec:63595359394, nsec:67815998, loc:(*time.Location)(0x110ebe0)}, Type:524288, Data:map[string]interface {}{"errors":[]model.fileE
Apr 04 05:36:34 backup syncthing[17545]: [XUHDX] VERBOSE: Folder "musique" is now idle
Apr 04 05:36:34 backup syncthing[17545]: [XUHDX] VERBOSE: Folder "musique" is now scanning
Apr 04 05:36:34 backup syncthing[17545]: [XUHDX] VERBOSE: Summary for folder "musique" is map[inSyncFiles:24991 version:182446 globalFiles:24999 globalDeleted:542 needFiles:8 localBytes:601824191946 inSyncBytes:601824212042 globalBytes:60
Apr 04 05:36:34 backup syncthing[17545]: [XUHDX] VERBOSE: Completion for folder "musique" on device PNO7QTP-BFL6I54-W5HOMWT-E2EJIEZ-5JQUEBO-U7UZEOE-NFRRKI5-JYDR5QS is 100%
Apr 04 05:36:36 backup syncthing[17545]: [XUHDX] VERBOSE: Scanning folder "musique", 0% done (0.0 MB/s)
Apr 04 05:36:37 backup syncthing[17545]: [XUHDX] VERBOSE: Folder "musique" is now idle
```

On the master node (PNO7QTP), everything is fine (the mentioned file is there, not modified in days).

The last node is running on a first-gen Raspberry Pi, so it's still synchronizing. I also have other folders shared between those three nodes, without any issue (synchronization is complete on all of them).

Is there anything I can do to have more information about why those files won't get synchronized?

**Comment by calmh** [comment]
Typically, for sound files, this is caused by something editing the file without updating it's modification time. Some metadata editors seem to do this. To fix, update the modification time of the file on the source, so that it is rescanned.

**Comment by Kernald** [comment]
Nice guess: it works fine! Thanks.

Would it be reasonable to consider the master as a reference, and automatically accept its changes? I guess it would be related to the auto-override changes on a master node.
