### ISSUE TITLE
Syncthing does not take care of network interface priority

### ISSUE THREAD

**Issue by therealmarv** [syncthing/syncthing#2941]
To reproduce the problem:
- Use a mac with WiFi connected to a home network and add a wired LAN connection to the same network.
- Configure OS X network priority order so that LAN connection is the preferred choice over WiFi.
- All internet connection and internal connections like SMB work over LAN now.
- Start syncthing and start synchronizing.
- Syncthing uses often WiFi connection although LAN is connected to same network.

Expected behaviour is that Syncthing recognizes both network cards but respects network card priority from the OS. It should try to connect with priority 1 network to the other clients before using second,third,..., priority networks as a fallback.
### Version Information

Syncthing Version: v0.12.21
OS Version: OS X 10.11.4
Browser Version: Chrome 50.0.2661.57

**Comment by AudriusButkevicius** [comment]
Your OS is supposed to do that (as in use the right interface when we ask to connect somewhere) and not us. There is no such thing as network interface priority exposed programatically as far as I can see.

**Comment by calmh** [comment]
I don't think this is cleanly implementable at the moment, but I'm keeping it as a feature suggestion for the future.

**Comment by AudriusButkevicius** [comment]
I am not sure how you'd implement this given it's the OS job to deal with routing.

**Comment by calmh** [comment]
There is probably an api to get route metrics that we could use to decide between two local discovery results.

**Comment by AudriusButkevicius** [comment]
The ticket does not say that this only relates to connections established in the local network.

**Comment by therealmarv** [comment]
Actually I have not tested with Internet->PC synchronization yet, this error report is based on phone&pc in local network behind a router. I will retest Internet sync that and report back. I use my phone to sync to my PC and only have seen that syncs often occur on the WiFi network card although normally it should be idle on that interface.

**Comment by calmh** [comment]
That's just my psychic powers. I bet it uses the correct interface over the internet, unless we get an incoming connection over UPnP to the wrong interface (which could still happen).

**Comment by therealmarv** [comment]
You're right ;) So I've retested over Internet and it uses the right interface (LAN).

I also thing this may also be important for the bug/feature: My LAN interface is not on my PC the whole time. It's a USB dongle, so priority one network interface can change at every time.

**Comment by Aranjedeath** [comment]
Also make sure you've not enabled (intentionally or not) AP Isolation on the router, which would prevent the wifi phone (I'm assuming it's wifi) from touching the ethernet plug on the laptop (only allowing wifi <-> wifi).

**Comment by therealmarv** [comment]
@Aranjedeath That is not active here. Phone Wifi<->LAN PC connection works flawless. Only syncthing wants my Wifi on my Mac :)

**Comment by dionorgua** [comment]
Just faced almost same issue.
Imagine that we've two machines (in same subnet) that shares data. Also both of them may be connected (sometimes) to certian VPN that allows client-to-client traffic.

And syncthing sometimes decides that it's better to sync over VPN, while direct connection is much faster).
