### ISSUE TITLE
Syncthing Owncloud App

### ISSUE THREAD

**Issue by locutus007** [syncthing/syncthing#2943]
Hello!

I am about to write a SyncThing app for owncloud. Since I am an experienced programmer, but new to both syncthing and owncloud, I would like to have a few questions answeared.
1: Is there something like a library for SyncThing, where I can, for example, specify what to do if a file changes, was created,...
2: how far does your API go? Can I configure versioning, specify what to do if a file changes,...
Do you have any further tipps for me?

Thanks,
locutus

**Comment by calmh** [comment]
There is no library as such. There is documentation of the API at https://docs.syncthing.net/dev/rest.html however.

**Comment by OliverKohlDSc** [comment]
Dear @locutus007 

sounds great!
That's exactly what I was looking for ...
If you need any help just let me know.

Cheerio
Oliver
