### ISSUE TITLE
java.lang.RuntimeException: Syncthing binary crashed with error code 9

### ISSUE THREAD

**Issue by plittlefield** [syncthing/syncthing#2949]
Hi Folks,

Syncthing is crashing several times a day.

http://pastebin.com/mArT55Fc

Syncthing v0.12.21
LG Google Nexus 5 (hammerhead)
CyanogenMod cm-13-20160407-NIGHTLY

**Comment by AudriusButkevicius** [comment]
Wrong repo, try syncthing-android.
