### ISSUE TITLE
protocol: Micro-Delta indexes

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#2951]
Currently, when we discover that a file has changed, we hash the file and send all of the blocks across to all devices.

If we know that the remote device we are sending the update to has the last version of the file (before current modification that we've detected) including all the blocks, we could send a partial update only containing the blocks that have changed, or that have been added.

This would be very useful for larger files.

I guess this is somewhat an alternative to variable block size, because if you have either one of them, the bandwidth usage should drop achieving the goal.

**Comment by lkwg82** [comment]
PLZ give some code links to Start with!

**Comment by AudriusButkevicius** [comment]
What exactly are you after?

**Comment by AudriusButkevicius** [comment]
The code that does the sending is in `model.go:func sendIndexTo`

Most of the optimization on the sending part could be done there (sending a non-0 flag to indicate this is a special type of index containing only blocks changed)

The receiving part is in `model.go:func (m *Model) IndexUpdate(`

**Comment by AudriusButkevicius** [comment]
I somewhat think that perhaps working on variable block size is better, as it's an optimization which potentially could remove the need for delta indexes (persistent indexes) all together, given the block size is small enough.

**Comment by AudriusButkevicius** [comment]
I raised this in order to have a discussion I guess.

**Comment by lkwg82** [comment]
Is this in any relation to 'temporary indexes' in #2252

**Comment by AudriusButkevicius** [comment]
No

**Comment by arneko** [comment]
> I somewhat think that perhaps working on variable block size is better, as it's an optimization which potentially could remove the need for delta indexes (persistent indexes) all together, given the block size is small enough

Well, this is only true for large files, eg having a large repo with very few files, that change comparatively often. (VMs) Not much help for large repos with many "small" files (Photos, Music, ....).
On the other hand, implementing variable block size seems to be a trivial task by comparison to delta indexing.

**Comment by calmh** [comment]
Nothing is quite as trivial as it seems when you start doing it between lots of different computers in a cluster. :)

**Comment by greyltc** [comment]
This would be a "killer feature."

**Comment by AudriusButkevicius** [comment]
Why, it's already pretty efficient.

**Comment by calmh** [comment]
I sincerely doubt this is worth it. The block list serializes to about 0.036% of the original file size (48 bytes per 128 KiB block). That's 360 KB for a 1 GB file that changed. Sure, the bigger the file the more blocks to send but also probably the more seldom the file changes.

**Comment by AudriusButkevicius** [comment]
This was raised pre large blocks, but I agree, that at this point it's not worth it.
