### ISSUE TITLE
gui: Connection error dialog not visible

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#2961]
Just the backdrop.

Chrome on Windows.

**Comment by calmh** [comment]
Yeah I noticed this as well today, Safari/Mac.

**Comment by calmh** [comment]
So this was broken by 3d71e68 (upgrading angular), but I can find no obvious cause. The network error dialog is broken, but for example the about and QR code modals work fine - and they all use our `modal` directive in about the same way. Looking at it in developer tools, the div with the modal contents in never get the `display: block` attribute that the `modal()` call is supposed to set, so it's invisible. Still no idea why this happens.

**Comment by calmh** [comment]
I can get this to work by tweaking the load order of javascript and directives in index.html, but I don't see a pattern or understand why...

**Comment by canton7** [comment]
>  but I don't see a pattern or understand why...

This sums up Angular pretty well.

**Comment by calmh** [comment]
:D Indeed. I don't know Angular well enough to understand what's going on here, but it feels like dependencies that are not loaded in time or something. Very non-obvious to me.
