### ISSUE TITLE
Allow to explicit include .stignore in sync

### ISSUE THREAD

**Issue by KopfKrieg** [syncthing/syncthing#2962]
Hi, I hope the question hasn't been answered somewhere else (if so I'm sorry to ask), but: Why can't I explicit include .stignore as a file that gets synced?

I know the documentation says that "The .stignore file itself will never be synced to other nodes", but is there a reason why I simply can't do the following (output of my .stignore file):

```
!/.stignore
```

That would be a pretty simple solution to sync .stignore to all devices (and yes, if there's no reason against it this shall be a feature request :grinning:)

**Comment by AudriusButkevicius** [comment]
This has been answered more than once in the tickets as well as in the forum.
Please use the search, or read about `#include`
