### ISSUE TITLE
BEP spec: FileInfo.FlagDirectory missing

### ISSUE THREAD

**Issue by xapantu** [syncthing/syncthing#2965]
In lib/protocol/protocol.go, in FileInfo flags, there is a FlagDirectory flag. It does not appear on this page https://docs.syncthing.net/specs/bep-v1.html, but it should!

**Comment by calmh** [comment]
Indeed! (Technically this should be filed on the docs repo as that's where the specs are, but I'll let it live here and fix it shortly.)

**Comment by calmh** [comment]
Fixed in https://github.com/syncthing/docs/pull/150
