### ISSUE TITLE
Unhelpful error message about Android not allowing syncing to external storage

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [syncthing/syncthing#2973]
I am afraid I can't reproduce the error message _verbatim_, because I have managed only just now to get rid of it and I don't want to break my seemingly fragile configuration in trying to get the error to appear again. Still: the error message was to the effect shown in my title. _The problem is that the message is not very informative, especially since (1) Syncthing lets the user try to set up folder syncs anyway, (2) syncing of Android's default *photo* sync does seem to work._

**EDIT (an addition)**: _Seemingly, on Android, **trying** to sync a folder other than the default photo folder with some other device, results in the Android device receiving an endless series of notifications_ asking for confirmation of the syncing / sharing (or at least _I think_ that the above problem is the cause of this stream of notifications).

What should happen: the aforementioned error message should be more informative; Syncthing should not defy the message and attempt the sync anyway; and certainly a whole stream of notifications should not appear.

### Version Information

Syncthing Version: latest one available in the Google Store. [Sorry, can't find the version number.]

OS Version: Android Lollipop 5.1.  [I recall dimly that there is a separate bugtracker for Syncthing-on-Android. However, I can't locate it, I am afraid.)

**Comment by AudriusButkevicius** [comment]
The tracker is in the same organization as this one.

But to be honest you should reword your issue if you decide to open a ticket there, because its totally not obvious what you are after
