### ISSUE TITLE
Syncthing-GTK 0.8.3: UI-settings -> 'Use traditional window header' sometimes ignored

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [syncthing/syncthing#2974]
**What happened, steps to reproduce, and what should happen**: I set the 'Use traditional window header' option and it worked; I reverted the change; I set the option again, such that the program should be back to using the traditional header - yet, it is not.

### Version Information

Syncthing Version: v0.8.3 (Syncthing -GTK) / 0.12.22 (daemon)
![screenshot-for-syncthing](https://cloud.githubusercontent.com/assets/9998846/14545360/452b3a16-0296-11e6-8704-13e2c89943f4.png)

OS Version: Linux Mint 17.3 x64 Cinnamon
Browser Version: not applicable

The attached is to screenshot of the situation (the situation that persists _after _I have pressed the 'save' button shown in the screenshot).

**Comment by AudriusButkevicius** [comment]
Wrong repo.

https://github.com/syncthing/syncthing-gtk
