### ISSUE TITLE
Android: Crash on startup

### ISSUE THREAD

**Issue by MStrecke** [syncthing/syncthing#298]
I've installed the Android client a few days ago and it worked fine... well - except the FAT permission bug.

When I wanted to use it today, I was told that it was not installed, even though I didn't uninstall it.
After re-installing (v 0.3.2) it crashes on startup (Syncthing reagiert nicht/ Syncthing does not respond).
I'm not sure if this is the right place raise the issue. I also did sent a bug-report via Google as well.

**Comment by arcusfelis** [comment]
It still occurs with version 0.5.15 and XPrivacy.
