### ISSUE TITLE
improvement suggestion for increase of sync speed

### ISSUE THREAD

**Issue by exokkk** [syncthing/syncthing#2983]
Hello,

I just started using syncthing together with a single 20gb container file. Well the sync (even if changing only 1byte) takes about 20 minutes to complete.

I know that it must scan the whole file and I appreciate the delta sync mechanism. Anyway I think that the sync time can be reduced by something like 5 minutes easily.

As far as I understand the process goes like this:
1. client detects new modTimestamp and scans through whole file
2. client notifies server
3. server scans his current file to detect deltas
4. client sends deltas

I think you could implement things like:
if large file then notify server directly, so that he can scan the file right now parallely 

Am I wrong? Sorry I just joined the syncthing-side of life just days ago ;)
regards
exokkk

**Comment by AudriusButkevicius** [comment]
You are wrong, the server does not scan anything.

The client detects a change, scans the file, sends the signature to the other side, other side works out what needs downloading by comparing it's local signature that's already in the database, and starts downloading.

Also, if you appended that 1 byte somewhere in the middle, if would have to redownload the remainder of the file after that one byte, as that would shift the block boundaries.
