### ISSUE TITLE
Improvement suggestion: file explorer integration

### ISSUE THREAD

**Issue by exokkk** [syncthing/syncthing#2984]
Hi,

I would like to have a kind of explorer integration within the webgui. At least showing all files with last modification timestamp would be a nice enhancement.

**Comment by AudriusButkevicius** [comment]
You have a file explorer on your machine, what's the point of duplicating functionality?

**Comment by exokkk** [comment]
well cross out the "at least".
but I would have to remote-login to my server in order to check the modification timestamp to verify that everything is fine. Maybe I am too concerned about if everything syncs fine...

**Comment by AudriusButkevicius** [comment]
There are other means to access the machine to check for files remotely, syncthing is not really meant for that.
