### ISSUE TITLE
[v0.13-beta] remote completion > 100

### ISSUE THREAD

**Issue by alex2108** [syncthing/syncthing#2993]
the folder is actually 100% in sync (checked in remote gui)
```
curl "127.0.0.1:8384/rest/db/completion?device=AGR6NY2...&folder=go-src"
{"completion":226.55250219942138}
```
Doing the same on other devices that share the same folders leads to similar results. Other folders on the same device, too

a folder that is not up to date shows the correct percentage (not sure if the value is exact but ~99% seems right)
```
curl "127.0.0.1:8384/rest/db/completion?device=AGR6NY2...&folder=bilder"
{"completion":99.64188929950149}
```

other devices show 100% completion on all folders as it should be

as soon as the folder "bilder" is synced completely all folders show 100% in `rest/db/completion`

### Version Information

Syncthing Version: v0.13.0-beta.3, 
OS Version: Linux (64 bit)

**Comment by AudriusButkevicius** [comment]
Steps to repro please?

**Comment by alex2108** [comment]
I have to try this in smaller setup (has to wait until tomorrow), I currently have 4 devices online but I can reproduce it by the following steps:
- (optional I assume) put some rate limit to have time to observe
- add file to any folder -> rescan 
- check completion on **another** folder and see how it increases over time until the file is synced, then completion drops to 100%

**Comment by alex2108** [comment]
Reproduced with smaller setup using only 2 devices and 2 folder.
- in my case devices `test1` and `test2` both shared the folders `default` and `testfolder1`
- `test2` had rate limit of 50 kB/s for up and download
- `default` has one file `asdf.txt` with some random stuff in it (seems to be needed, first test with empty folder did not work)
- `testfolder1` started with `test.txt` with some randoms stuff in it (those small files were synced then)
- add big file `test.mp4` to folder `testfolder1` on device `test1` (was some video I had with ~50MB)
- test `curl "[ip and port of device test1]/rest/db/completion?device=ID-OF-TEST2&folder=default"`
- get `"completion" : 395837540` or something similar

not checked the code but could it be that temporary index stuff is added to the completion of all folders even if it does not belong to that folder?

**Comment by AudriusButkevicius** [comment]
So there are a few issues here I think. First is probably a race between deregistering a file from temp index and getting an update from a remote device, plus aggregating temp indexes for ignored files.
