### ISSUE TITLE
Incorrect completion percent shown

### ISSUE THREAD

**Issue by bencook** [syncthing/syncthing#2999]
After connecting a remote (Android) device, I synced a folder of photos.  All files correctly synced, and can be viewed in the local folder.  The "Folders" section of the dashboard correctly lists the folder as up to date, with the same number of items on both locations.  

However, even though this sync is complete, the "Remote Devices" section is stuck at 50%.  Restarting each device several times does not resolve this issue.

### Version Information

Syncthing Version: v0.12.22
OS Version: Debian 8
Browser Version: 45.0.2

Remote device:  v0.12.20
OS Version: Android 6.0.1

**Comment by wweich** [comment]
You have shared another folder with that device, which is not synced.

**Comment by bencook** [comment]
I have no unsynced folders.

**Comment by AudriusButkevicius** [comment]
For clarity, please provide screenshots from both sides.

**Comment by bencook** [comment]
Here are the screenshots from my computer and phone.

![screenshot_20160422-124632](https://cloud.githubusercontent.com/assets/6708462/14748648/e3e9d9ee-0888-11e6-94d0-3f4869229d28.png)
![screenshot from 2016-04-22 12-46-07](https://cloud.githubusercontent.com/assets/6708462/14748649/e3f32792-0888-11e6-8a7c-cb39f7007978.png)

**Comment by AudriusButkevicius** [comment]
So do both sides share only a singlr folder with each other? Can you actually screenshot that single folder that is being shared on both sides? Also, a screenshot from the web ui on the phone would be prefered as it has more information.

**Comment by bencook** [comment]
Correct, both sides only share a single folder.  It appears to be resolved now.  On the webui of the phone, I was presented with an option to force resolve inconsistencies, and now everyone shows up to date.

![screenshot_20160422-141203](https://cloud.githubusercontent.com/assets/6708462/14750766/7c3980ae-0894-11e6-9aa0-9da37c33c99c.png)
![screenshot from 2016-04-22 14-11-44](https://cloud.githubusercontent.com/assets/6708462/14750767/7c3bbe6e-0894-11e6-8aee-5bbd268e4039.png)

**Comment by AudriusButkevicius** [comment]
This is because you modified the files on the desktop (or their metadata) and the folder is set as master on the phone.

**Comment by bencook** [comment]
Well _I_ didn't modify the files in any way.  My operating system might have done so automatically.
