### ISSUE TITLE
Add proxy option that won't be bypassed

### ISSUE THREAD

**Issue by Nutomic** [syncthing/syncthing#3006]
It is already possible to use Syncthing with Tor on Android with the following environment variable:
`all_proxy=socks5://localhost:9050 syncthing`

However, if Tor is not running, Syncthing will just connect to other devices directly. Instead, it should be so that no connections are made without the proxy. The idea is to have a setting "use tor", that forces the app to do all connections only over Tor.

Also, I couldn't find a way to make sure that Syncthing is using a proxy. The logs only show "INFO: Proxy settings detected". It would be good to have some info if the proxy is actually used, and maybe have the address logged, too.

Edit: This is for syncthing/syncthing-android#589

**Comment by AudriusButkevicius** [comment]
STTRACE=dialer will print info, also remote addresses will be pointing to the proxy.

**Comment by calmh** [comment]
Seems valid. I preliminarily agree that we should fail rather than fallback when told to use a proxy and the proxy doesn't work.
