### ISSUE TITLE
License issue, incompatible with secondary licenses

### ISSUE THREAD

**Issue by rodneyrod** [syncthing/syncthing#3008]
Currently as it stands, the MPLv2 license that Syncthing uses is technically incompatible with other licenses e.g. GPL due to the inclusion of Exhibit B at the end of the license file.

>Exhibit B - "Incompatible With Secondary Licenses" Notice
>---------------------------------------------------------
>
>  This Source Code Form is "Incompatible With Secondary Licenses", as
 > defined by the Mozilla Public License, v. 2.0.

Removing this notice will enable other projects not licensed under the MPLv2 to use Syncthing's source code without issue.

**Comment by calmh** [comment]
No. The text you quote describes what would need to be added to the copyright notice to be incompatible with secondary licenses. If you look at our actual source code, you'll notice there is no such wording added there.

**Comment by rodneyrod** [comment]
Quoting the license file:
>If You choose to distribute Source Code Form that is Incompatible With
>Secondary Licenses under the terms of this version of the License, the
>notice described in Exhibit B of this License must be attached.

You still have Exhibit B present in the license file, therefore it is attached and in effect. I can diff the changes you need, but pretty much all you need to do is drop the 'Exhibit B' section.
