### ISSUE TITLE
unrecoverable error during startup - compacting database - corruption detected

### ISSUE THREAD

**Issue by andrewufrank** [syncthing/syncthing#3010]
when restarting syncthing (automatically - reboot) syncthing starts and stops immediately again with error message 

Compacting database: leveldb/table: corruption on data-block (pos=0): checksum mismatch, want=0x785e3822 got=0x152c5e25 [file=042122.ldb]

in the log i see an entry 

15:11:36.385123 table@build created L1@47935 N·32249 S·2MiB "\x02Mo..avi,v19358704":"\x02Mo..mkv,v17732440"
15:11:36.706691 table@build error I·540422 "leveldb/table: corruption on data-block (pos=0): checksum mismatch, want=0x785e3822 got=0x152c5e25 [file=042122.ldb]"
15:11:36.706779 table@build exiting (corruption detected)
15:11:36.706817 table@build revert @47903

and then syncthing restarts, repeating the same loop. 
the error message is always the same (including the same checksum; the file system is checked and i restarted the processor to avoid hitting the same bad memory spot).  suspicious is the fact that the checksum error is on pos=0, but i do not know much about internals of syncthing.

the loop stopped after i deleted the index and it rebuilds it now. 
i have kept the old index tables, if they are of any use (they may be confused, because i did not stop syncthing before i renamed them, thus i may have interrupted the process of redoing the log tables).

### Version Information

Syncthing Version: v0.12.22
OS Version: armbian - odroid xu4 
Browser Version: (if applicable, for GUI issues)

**Comment by AudriusButkevicius** [comment]
Check for existing closed issues or forum threads for explanation.
Essentially you've managed to corrupt the database, and there is not much we can do.

It can because by power loss, or bad hardware, there is not much we can do.

**Comment by andrewufrank** [comment]
i understand that corruption could be caused by powerloss and that this is not under control of syncthing code and this is not what i ask to change. what happens here is 
- the corruption is occuring during syncthings recovery effort - neither powerlos not anything else is heppening, and the error (checksum error in block 0) is not pointing to "other influences"
- syncthing has no recovery from a failed recovery effort and the start is repeated within a minute indefinitely. 
(i did check for the closed issue and read the related entries and used the information from there to recover; what i observed is not the same as the closed issue relates)

users would imho expect that 
- syncthing recovers from a corruption effectively (and not reproducing the corruption again)
- if a recovery is not possible, it would produce an error message and not go to an infinite loop.

**Comment by AudriusButkevicius** [comment]
Corruption is not happening  as syncthing starts. Corruption has happened sometime before and the database is already toast. Automatic recovery is not something we should do, as it could potentially cause a lot of files to end up as conflicts, so it's better than user gets involved and is aware of that fact.


The fact that we restart in a loop is meaningless I think, we stop after 5 attempts, and it doesn'treally matter what we do, we're not going to get anywhere anyway.

**Comment by andrewufrank** [comment]
thank you for the explanation - i did not understand that the corruption is in the files and, in this case, recovery does not clean it. 
i had the impression that the recovery attempt did not stop after 5 cycles and i assume you produce at that time an error message and a hint what to do then. 

delete index files worked for me. it took several hours  to reconstruct them (for 400 GB), but i did not observe any conflicting files). 
now it works again! thank you for a very good tool!

**Comment by bigbear2nd** [comment]
> delete index files worked for me.
If the 2 (or more) devices where in sync before one database got corrupted, there is no problem to delete the index and rebuild it.
If you are not in sync when you delete it, conflicts or even data loss might occur. Make sure you are in sync and have a backup of your data (best case both (all) ends) before you delete the index on any device.

**Comment by AudriusButkevicius** [comment]
I don't think data loss can happen, because when yhere is a conflict between a deletion and non-deletion, the non-deletiom always wins.

**Comment by andrewufrank** [comment]
this is reassuring - thank you!
in my case, the error message indicated which index file is corrupted. should/could i have deleted just this one and recovered from the problem?

**Comment by AudriusButkevicius** [comment]
It doesn't work that way, a database if a setof files, deleting one file is deleting some undefined part of the data which might be in the middle.
