### ISSUE TITLE
Remote Device stops reconnecting

### ISSUE THREAD

**Issue by mccullerlp** [syncthing/syncthing#3011]
Between two Fedora 23 laptops running 
syncthing v0.12.22 "Beryllium Bedbug" (go1.5.3 linux-amd64) mockbuild@copr-builder-884982692.novalocal 2016-04-13 14:33:11 UTC

They seem to occasionally go into a state where they will not reconnect, even after all of the reconnect interval timescales I have configured. They are on the same local network, one inside a linux VM and I'm not certain the connection is over TCP-22000 or UPnP (although I think it should be configured to foreward 22000).

This seems to happen after one of the laptops goes out into the world of unreliable connections. It also seems to correlate with "unexpected EOF" messages in the log of the other machine. I notice that when this happens, one of the two machines will stop stating "Connected" or "Disconnected" for the remote in the web gui, as though that remote has been taken out of a list of remotes to connect to.

Restarting the machine with the missing Disconnected flag in the web gui fixes the issue (but is inconvenient as it requires an SSH connect).

Seems like the logic acting on "EOF" and "unexpected EOF" is different and affecting reconnects. I don't know if this is a bug or a design issue to prevent DoS or something, but making reconnect timout go to infinity is an issue for me.

Otherwise this software is pretty incredible.

**Comment by AudriusButkevicius** [comment]
Please set an environment variable STTRACE=connections and provide logs and screenshots from both sides (at the point it happens).

**Comment by calmh** [comment]
Timeout, please revive if reproducible
