### ISSUE TITLE
On app, synching only over WiFi will disable Syncthing

### ISSUE THREAD

**Issue by kalsan** [syncthing/syncthing#3018]
How to reproduce:
- go to settings
- enable the feature that runs Syncthing in the background
- check the box for synching only when having WiFi connection
- make sure WiFi is on and connected
- close Syncthing and reopen it
- it says that it's inactive and offers either close or changing settings.

### Version Information

Syncthing Version: v0.12.22 (Android version 0.7.15)
OS Version: Android 5.x

**Comment by AudriusButkevicius** [comment]
Wrong repo, plus duplicate.

**Comment by wweich** [comment]
Plus: fixed in 0.7.16

**Comment by kalsan** [comment]
Thanks, can confirm that it's working after the update.
And sorry for the wrong post location!
