### ISSUE TITLE
Syncthing Pull Order "Smallest First" is pulling largest first

### ISSUE THREAD

**Issue by bshafer** [syncthing/syncthing#3019]
What happened:
Syncthing was pulling the largest files first instead of the smallest.

What I expected:
The smallest files to be pulled first

Steps to reproduce the error:
1. Select "Smallest First" for the "File Pull Order" for a folder and restart Syncthing
2. Look at the list of "Out of Sync Items" for that folder: it is sorted from largest to smallest, and the items at the top of the list are syncing first.

### Version Information

Syncthing Version: v0.12.22
OS Version: Windows (64 bit)

**Comment by calmh** [comment]
Cannot reproduce. Smallest first:

<img width="953" alt="screen shot 2016-04-27 at 19 44 55" src="https://cloud.githubusercontent.com/assets/125426/14862185/a2882a06-0cb0-11e6-9ae1-4a47057b1977.png">

Largest first:

<img width="921" alt="screen shot 2016-04-27 at 19 45 13" src="https://cloud.githubusercontent.com/assets/125426/14862189/a8c9b68c-0cb0-11e6-8601-eb553c04c12b.png">

(with restart in between, as prompted)

**Comment by bshafer** [comment]
Hmmm.... Ok, it is more complicated than I thought at first (surprise!):

The first page of "Out of Sync Items" is sorted correctly (I'm not sure what the 128B entries are about, since they seem to stay there until the sync is complete), but the last page is out of order:

First Page:
![first page](https://cloud.githubusercontent.com/assets/904264/14865013/d5d8ff84-0c79-11e6-888c-77d70b66dfb4.png)

Last Page:
![lastpage](https://cloud.githubusercontent.com/assets/904264/14865030/e6a52c98-0c79-11e6-8a90-9a0f13416a5c.png)

It seems as though files are getting added to the end of a queue, and then sorted eventually, but when I go back to the first page, I see that it is all much larger files (but sorted properly on that page):
![first page again](https://cloud.githubusercontent.com/assets/904264/14865126/56569428-0c7a-11e6-9ca9-3b025fc4f3e7.png)

I failed to get a second screen shot of the last page, but it now had files around the 5 KiB size. However, if I then select 50 per page and then go back to 10 per page, it corrects itself (the screen shot wasn't taken until it had worked off all the really small files and has now made it up to the ~3MiB files, and the other pages are now in the proper order:
![after changing size of list](https://cloud.githubusercontent.com/assets/904264/14865162/958f567a-0c7a-11e6-8ed4-85de19072d23.png)

I can run the scenario again to get better screen shots if you want, now that I know what to expect.

**Comment by AudriusButkevicius** [comment]
Anything without the arrow is not yet scheduled to be downloaded, so it's not sorted.

**Comment by bshafer** [comment]
Oh, okay. So can I increase the number of items that get scheduled at a time? I was hoping to get the largest quantity of out of sync items downloaded quickly, so that I could see just a short list of the big files that take most of the time. If I have 150 items in the "Out of Sync" list, but only the first 20 or less have blue arrows, then that doesn't work I guess.

And why does clicking on "50" and then back on "10" sort them so they download in the order I want, even though most of them still do not have blue arrows?

**Comment by bshafer** [comment]
And don't you think it should sort the entire list of known "out of sync" items before adding them to the scheduler? Otherwise, "Smallest First" is kind of misleading.

**Comment by AudriusButkevicius** [comment]
No you cannot increase the number of items scheduled at a time.

Items are scheduled as they arrive. If you have a lot of items on another machine it can take seconds for the whole list to arrive, yet we start scheduling immediately after something arrives.

The reason clicking around helps is probably because the list gets refreshed, and it just happens to do another sweep of scheduling just before that.

**Comment by AudriusButkevicius** [comment]
@calmh  had some intentions to rewrite a big part of that code some time in the near future, which is potentially when we could address this.

**Comment by bshafer** [comment]
Ok, so it sounds reasonable that as items come in they get added to the scheduler; but it seems that there must be another queue that they sit in while they wait to get on the schedule, because I only ever see about 10-20 items with blue arrows, even with thousands of out-of-sync items in the list. That other queue doesn't appear to be sorted unless there is some user interaction. It appears that selecting a different number of items per page sorts that queue. Maybe a quick fix could be to perform whatever sort happens in response to the user action just after receiving new items in the queue? Either way, I'll be looking forward to a rewrite of that part. Thanks for all your work! Syncthing is great!

**Comment by AudriusButkevicius** [comment]
So there is only one queue, and that's the queue for items which have the blue arrows, this queue lives in memory.
The rest of the items are a pure dump from an on disk database, which happens to sort them alphabetically (because it's a key value store where iterator returns it ordered by key).

The reason you see stuff changing as you click around is due to the fact that the in memory queue which had partial list of items goes empty and we go to the disk to fetch items to schedule that have arrived from the remote device since we've produced the previous queue. At that point most/all of the items have arrived from the remote machine, and we happen to load them all into the queue and sort them in your selected order.

**Comment by AudriusButkevicius** [comment]
The right action here is to enqueue items as they arrive, resorting the queue after each batch.

This will potentially drive up memory usage though, especially for the people with 7 million files.

**Comment by bshafer** [comment]
Ok, so lets think of the database as a queue of sorts, but it makes sense that it is stored on disk to save memory. However, it looks like the list of non-scheduled items (i.e. non-blue-buttoned, which is most of them) is actually sorted by size when I change the items per page, so I guess the GUI must be sorting them based on the setting of "Pull Order"? Is it possible to make the key-value store keyed by size for appropriate Pull Orders, or is there a single store for all syncing folders? If it could be keyed by size for certain folders, that would get us pretty close to what I would expect from "Smallest First." Or I could just wait for that coming rewrite. I'm a 3-million-file user, so it would still be nice to keep the memory footprint low.

As to the right action: Why not keep the in-memory queue small, and go grab the next batch from an appropriately-keyed value store?

**Comment by AudriusButkevicius** [comment]
Keying by certain order doesn't work, as toggling the setting would mean a database rewrite.
Plus we rely on the alphabetical ordering for processing (always processing folders before files that are in the folders, etc.)

**Comment by calmh** [comment]
This is all rewritten anyway in my pending changeset code. That has disadvantage/advantage of queueing and sorting everything up front.

**Comment by bshafer** [comment]
Ok. Sounds good. Thanks again for all your work.
