### ISSUE TITLE
missing values in dropdown list

### ISSUE THREAD

**Issue by bartsmit1985** [syncthing/syncthing#3020]
I've noticed that the last couple of values (directory names) are missed off the folder path when setting up a new sync.

In this screenshot (https://goo.gl/photos/hTwwA1UEdcCDME1B7) you can see that the last value in the list is /private, but there are more directories, but not shown. Unless you know the name of the folder and you type the first letter, folders starting with a letter at the end of the alphabet are not showing.

### Version Information

Syncthing Version: v0.12.19, Linux (ARM) 
Server OS Version: OpenMediaVault 2.1
Desktop Details: Kubuntu16:04 (64bit), with Chrome 50. Same issue on Linux Mint 15.10 (64bit) and Chrome 47

**Comment by AudriusButkevicius** [comment]
This is intended, it shows the first 10 items by design.

**Comment by bartsmit1985** [comment]
Thanks AudriusButkevicius for clarifying. 
It's a pity that you can't go down the list by either scrolling the mouse or with the arrow keys to see other values.
