### ISSUE TITLE
unknown tls.Config field GetCertificate

### ISSUE THREAD

**Issue by florianos** [syncthing/syncthing#3026]
docker build .

/usr/bin/go get app/...
github.com/gorilla/websocket
vendor/src/github.com/gorilla/websocket/client.go:361: unknown tls.Config field 'GetCertificate' in struct literal
vendor/src/github.com/gorilla/websocket/client.go:370: unknown tls.Config field 'ClientSessionCache' in struct literal
vendor/src/github.com/gorilla/websocket/client.go:373: unknown tls.Config field 'CurvePreferences' in struct literal
make: *** [get] Error 2]

go version 2.1.2

**Comment by AudriusButkevicius** [comment]
Amazing. Syncthing doesn't use gorilla/websockets and Go 2.1.2 doesn't even exist. Is this a joke?

**Comment by florianos** [comment]
sry switched the tab :( in browser

**Comment by calmh** [comment]
:D
