### ISSUE TITLE
A great working CentOS and Fedora repo

### ISSUE THREAD

**Issue by jebofponderworthy** [syncthing/syncthing#3027]
Not sure this is the right place for this, but was not able to figure out the correct :-)  I just recently found this:

https://copr.fedorainfracloud.org/coprs/decathorpe/syncthing/

and would like to edit the contributed repo list, which I found once but am not able to find again :-)  What is the procedure to enable me to help edit this and other documentation?  I would like to "give back" to this project, y'all are doing wonderful things!

**Comment by calmh** [comment]
You want to add it to https://docs.syncthing.net/users/contrib.html which you can do by editing and opening a pul request on https://github.com/syncthing/docs/blob/master/users/contrib.rst :)
