### ISSUE TITLE
Incorrect behaviour of internalScanFolderSubdirs

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing#3028]
Syncthing Version: master
When two files are removed and the first path is a prefix of the second path, the local and global count are incorrectly updated. E.g. If Syncthing-inotify performs `scan?folder=default&sub=foo/bar&sub=foo/bar2` because the files `bar` and `bar2` are removed, the file count is reduced by 3 instead of 2. I traced it back to the fact that we use a [`batch`](https://github.com/syncthing/syncthing/blob/29fa05ae0580e9a707171af7f0b00de6b92a5be8/lib/model/model.go#L1486) array instead of a map, which means the array we pass to updateLocals can contain duplicates. This confuses the intermediate counting we do in sizeTracker.

This could cause a panic: in [set.go](https://github.com/syncthing/syncthing/blob/29fa05ae0580e9a707171af7f0b00de6b92a5be8/lib/db/set.go#L84)

**Comment by calmh** [comment]
We shouldn't scan foo/bar2 when asked to scan foo/bar, as it's not a proper prefix. That's a bug, yes.

**Comment by calmh** [comment]
Cannot reproduce, tried with the following test: https://github.com/calmh/syncthing/commit/7039edb02191900788065f397e8ddb97d2e391d2

What are you doing differently?

**Comment by calmh** [comment]
Hang on, test is bad.
