### ISSUE TITLE
Folder Master and Out of Sync status

### ISSUE THREAD

**Issue by EZarnosky** [syncthing/syncthing#3033]
I have several folder folder set on my main syncthing system to sync to 2 remote syncthing clients. I have the folder on my main system set to Folder Master. Everything replicates fine, but when anything is removed from the clients folders (which is done after the files get moved into their permanent location)  the Folder Master becomes Out of Sync and I get an override button on the Folder Master. Should I click that all missing data on the remote systems is then pushed again.

This makes no sense. If it is the folder master then it is the authority of what should be in the folders. The Folder master should always be in sync.

Overall issue
 - Files removed or changed on the clients  (by the clients) should not change the folder masters status to Out of Sync

### Version Information

Syncthing Version: v0.12.22, Linux (64 bit)
OS Version: Ubuntu 15.10

**Comment by AudriusButkevicius** [comment]
Please read the docs explaining what it does and how it works before opening issues.
