### ISSUE TITLE
Lots of "Syncing (100%)" nowadays

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3037]
This is now the norm in my setup. Need to investigate why it doesn't go to "up to date". Both for the folder and for the remote device. Possibly related to having ignores "leak" and then become ignored again a while back.

![screen shot 2016-05-04 at 22 15 10](https://cloud.githubusercontent.com/assets/125426/15027833/f9cace8c-1245-11e6-8261-98b0d6b09e5e.png)

**Comment by calmh** [comment]
Also,

<img width="571" alt="screen shot 2016-05-04 at 22 47 51" src="https://cloud.githubusercontent.com/assets/125426/15028673/47878ab2-124a-11e6-8f40-9f6620ff0a44.png">

**Comment by AudriusButkevicius** [comment]
Can't repro, any steps?

**Comment by calmh** [comment]
Nothing simple, it just happens in my setup by itself. I think it's more important to track down the >100% that we still have.

**Comment by AudriusButkevicius** [comment]
Both are equally important I think, yet they could also be related.

**Comment by MikeLund** [comment]
"Syncing (100%)" is the story of my life.

I have a few devices, folder master is Linux and one client getting stuck at 100% is a Windows client. Most likely caused by a symlink (and I am quite sure there is another bug about this).

But also happens occasionally on an OS X client. Any way to give more useful debug info? Restarting the client seems to fix it (in the non-Windows case), so strace isn't too useful. Could try ptrace and give more info later if I notice it. HTH and good luck :)

**Comment by TimboJones** [comment]
I can confirm that this Issue is definitely also Symlink related. I have three devices connected, one of them is a Win10 machine, both the Linux machines show the Win machine at __100%__, after deleting the symlinks it changes to __up to date__. I can provide further information if required.

**Comment by apuckey** [comment]
Hi there, 

I get this also using 1 master folder node and 2 slave nodes that only connect to the master and not each other. I have tried all manner of syncing/scanning/overriding but nothing works apart from restarting the node that has 100% and then doing another override on the master.

let me know if any debug info that would be helpful for this as i can readily reproduce it in my setup

I have no symlinks anywhere in the folders at all.

**Comment by apuckey** [comment]
One thing i have noticed. on the node that is @ 100% syncing the version from rest/db/status for the folder in question is lower than the master as if it doesn't get updated.

**Comment by calmh** [comment]
That's interesting. Can you post the output?

**Comment by apuckey** [comment]
sure currently slave2 is on {"completion":99.86253277366417}

Probably means nothing as i don't think the versions for folders is matched, I think versions are just on individual files right?.

master:
```
{
"globalBytes":59685499,
"globalDeleted":741,
"globalFiles":7680,
"ignorePatterns":false,
"inSyncBytes":59685499,
"inSyncFiles":7680,
"invalid":"",
"localBytes":59685499,
"localDeleted":741,
"localFiles":7680,
"needBytes":0,
"needFiles":0,
"state":"idle",
"stateChanged":"2016-05-22T14:36:08.14847964+10:00",
"version":103147}
```

slave1:
```
{
"globalBytes":59685499,
"globalDeleted":741,
"globalFiles":7680,
"ignorePatterns":false,
"inSyncBytes":59685499,
"inSyncFiles":7680,
"invalid":"",
"localBytes":59685499,
"localDeleted":741,
"localFiles":7680,
"needBytes":0,
"needFiles":0,
"state":"idle",
"stateChanged":"2016-05-22T14:36:18.07925616+10:00",
"version":64404
}
```

slave2 ( syncing @ 100% ):
```
{
"globalBytes":59685499,
"globalDeleted":741,
"globalFiles":7680,
"ignorePatterns":false,
"inSyncBytes":59685499,
"inSyncFiles":7680,
"invalid":"",
"localBytes":59685499,
"localDeleted":741,
"localFiles":7680,
"needBytes":0,
"needFiles":0,
"state":"idle",
"stateChanged":"2016-05-22T14:36:17.763417797+10:00",
"version":66885
}
```

**Comment by apuckey** [comment]
and the relevant log line from db/completion:

Completion(deviceid, "foldername"): 99.862533 (82048 / 59685499 = 0.001375)

**Comment by calmh** [comment]
That's quite odd as "need bytes" is zero in the rest output. Need to think about it...

**Comment by apuckey** [comment]
I'll keep digging to see what i come up with. will update if i find anything

**Comment by apuckey** [comment]
Ok im not sure if this helps.

I changed FileInfo.Size() to return 0 if f.IsDeleted() is true.

This made the master up to date but one of the slaves files are not up-to-date. i have to then restart syncthing and do another override to make that slave update its files. ( this happens even without the above change )
```
on master:
rest/db/completion?folder=folder&device=slave1
{"completion":100}

rest/db/completion?folder=folder&device=slave2
{"completion":100}
```

however if i now check the same folder against the master on the actual slave:

```
on slave1:
rest/db/completion?folder=folder&device=master
{"completion":99.99920122336333}

on slave2:
rest/db/completion?folder=folder&device=master
{"completion":99.00752972365804}
```

also bear in mind my slave machines are only connected to the master if this makes any difference
also files will get created on each slave in some folders which when synced need to be deleted. these files will have identical names and sizes but different create dates


```
master:
  folder:
    devices
       slave1
       slave2

slave1
  folder
    devices
      master

slave2
  folder
    devices
      master
```

hope this helps in some way

**Comment by apuckey** [comment]
More info:

If i do this:

initiate a scan on slave1 -> wait until its completed -> override changes 
initiate a scan on slave2 -> wait until its completed -> override changes

this actually now works properly and have not been able to reproduce the 100% syncing issue with that IsDeleted() change

note:
  after scanning slave1 and overriding only files that were deleted on slave1 get deleted on slave2. I then have to do the same thing to the other slave.

**Comment by apuckey** [comment]
reverted isDeleted() chagne and used the logic in the last post and it still works without having 100% syncing.

**Comment by calmh** [comment]
In my case this was user error, so closing. Classic mismatch of ignore patterns causing one device to expect another device to have files that it's ignoring.
