### ISSUE TITLE
Adding a new device and/or folder or toggling listen addresses or NAT settings should not require restart

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3038]
However it does, according to the UI, in v0.13.0-beta.4

**Comment by AudriusButkevicius** [comment]
Or even changing rescan interval.

**Comment by calmh** [comment]
You can create your own issue for rescan interval, as that actually does require handling that doesn't exist today. The remaining thing that should be fixed here for 0.13 is the NAT handling as that is correctly taken care of, we just incorrectly raise the "must restart" flag.

**Comment by calmh** [comment]
Fixed by #3098
