### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by wright546** [syncthing/syncthing#3049]
I'm running syncthing on a few Ubuntu 12 and 14 machines and have no problems with crashes.  But I have one Ubuntu 16 machine where syncthing is crashing at seemingly random times.  I'm including all the output from the crash that displayed in the terminal window.  If I need to provide any further information please let me know and I will get it.

[syncthing-0.12.23-crash.txt](https://github.com/syncthing/syncthing/files/253022/syncthing-0.12.23-crash.txt)

Syncthing Version: v0.12.23
OS Version: Ubuntu 16.04

**Comment by AudriusButkevicius** [comment]
Dup of an issue in the last 40 created.

**Comment by lkwg82** [comment]
dup of #3002
