### ISSUE TITLE
Easy to reproduct Android app crash

### ISSUE THREAD

**Issue by dunmatt** [syncthing/syncthing#3051]
- what happened,
 In Nexus Android 6.0.1, "Unfortunately, Syncthing has stopped."

 - what you expected to happen instead, and
 I expected it to not crash, perhaps it would tell me what stupid I told it to do?

 - any steps to reproduce the problem.
 1) Touch Syncthing icon to start app
 2) Touch "DEVICES" tab
 3) Touch + in the upper right corner of the screen
 4)  KABLOOEY!  App crashes.

### Version Information

Syncthing Version: v0.12.22
Syncthing-Android Version: 0.7.16
OS Version: Android 6.0.1

**Comment by wweich** [comment]
Wrong repo + dub of syncthing/syncthing-android#632.
