### ISSUE TITLE
Slow sync?

### ISSUE THREAD

**Issue by claytondukes** [syncthing/syncthing#3054]
Is there a way to specify the bandwidth (like unlimited)?
I have 1Gbps links and it is taking days to do the initial sync between 5 systems.
Conversely, if I use rsync it takes about one day.
Am I just doing it wrong?

**Comment by AudriusButkevicius** [comment]
Bandwidth is not limited, unless you are connected via a relay.
Also giving times without volumes is pointless.

**Comment by claytondukes** [comment]
It's about 5TB. But I've now used rsync to transfer to all servers and now syncthing is ok.

**Comment by claytondukes** [comment]
Hi, just wanted to follow up. I now have 5 servers syncing. I let it run 24 hours and can see that only 10GB of the ~5TB of data transferred in that time. I must be doing something wrong?

**Comment by AudriusButkevicius** [comment]
I've told you to check for using relays.

**Comment by AudriusButkevicius** [comment]
Otherwise check other things such as CPU usage and general network throughput.

**Comment by claytondukes** [comment]
One of the 5 servers is using a relay. All others are direct connect.  The system I am testing on has a 25Mbps connection (an no relay) and cpu for syncthing is at 117%.
Could it be the one relayed system in the mix causing this?

**Comment by AudriusButkevicius** [comment]
If that "one" is the source then yes, otherwise it should only affect that one server. At this point you seem to be capped by CPU. Also, check CPU on the source and the destination.
