### ISSUE TITLE
External File Versioning command not called on "add file"

### ISSUE THREAD

**Issue by bitrage** [syncthing/syncthing#3059]
The "External File Versioning" command is called on file-change and file-deletion. However it seems it is not called when a new file is created.

I'm trying to auto-commit to a Git repository located in .stversions with the following batch file (works on CHANGE and DELETE). It is not called on ADD.

```
setlocal EnableExtensionsS

set FOLDER_PATH=%~1
set FILE_PATH=%~2

echo "%FOLDER_PATH%\%FILE_PATH%" >> z:\sync.log
dir %FOLDER_PATH% >> z:\sync.log

if not exist "%FOLDER_PATH%\~syncthing~%FILE_PATH%.tmp" (
	if exist "%FOLDER_PATH%\.stversions\%FILE_PATH%" (
		goto DELETE
	)
)
if exist "%FOLDER_PATH%\~syncthing~%FILE_PATH%.tmp" (
	goto CHANGE
)

goto END

:DELETE
del "%FOLDER_PATH%\.stversions\%FILE_PATH%" 
echo DELETE >> z:\sync.log
goto END

:CHANGE
copy /Y "%FOLDER_PATH%\~syncthing~%FILE_PATH%.tmp" "%FOLDER_PATH%\.stversions\%FILE_PATH%"
echo CHANGE >> z:\sync.log
goto END

:END
del /Q "%FOLDER_PATH%\%FILE_PATH%"

D:\Git\bin\git.exe -C "%FOLDER_PATH%\.stversions" add --all
D:\Git\bin\git.exe -C "%FOLDER_PATH%\.stversions" commit -m Syncthing
exit /B 0
```

The log file shows every call of the batch file but is not updated when creating a new file. The file is synced across devices however.

### Version Information

Syncthing Version: v0.12.23, 
OS Version: Windows 7 (64 bit)
Browser Version: not applicable

**Comment by AudriusButkevicius** [comment]
Working as intended, there is no need to version a new file, as it's new, there are no other versions of it.
