### ISSUE TITLE
syncthing uses a lot of CPU

### ISSUE THREAD

**Issue by keltia** [syncthing/syncthing#3061]
Every 30s, syncthing wakes up and does its bookkeeping things and eats up a lot of CPU (around 102-105% most of the time). Sometimes it is using so much CPU that music and movie playing are affected.

```
roberto         47850   0.1  0.7 573447840  59492   ??  S    10:32AM 168:50.69 /usr/local/opt/syncthing/bin/syncthing -no-browser -no-restart
```

I know this is only the Virtual size and it is usual for OS X apps to have a big one but 546 GB?

In the following snapshot, all the peaks you see in CPU time are due to syncthing.  I also have Dropbox running and it is using less memory and less CPU.

![screenshot 2016-05-08 23 51 28](https://cloud.githubusercontent.com/assets/142030/15100646/dbad99ea-1577-11e6-936d-83adcd7a28b4.png)

I don't have that may files in the Sync directory:
```
354 [23:58] roberto@rron-2-1:~/Sync> find . |wc -l
   91851
```
### Version Information
Syncthing Version: v0.12.22
OS Version: OS X 10.11.4 on Macbook Air mid-2012, 8 GB, 512 GB SSD

Thanks.

**Comment by AudriusButkevicius** [comment]
I suggest you use syncthing-inotify together with syncthing

**Comment by keltia** [comment]
OK, aside from the fact that I never saw it mentioned before, it will help with better response time but that will not prevent the hogging every N seconds, will it?  I'm trying to run `syncthing-notify` and changed the rescan interval to 60s, will report.

**Comment by AudriusButkevicius** [comment]
inotify defers scanning via the APIs.

**Comment by calmh** [comment]
Well, we do a certain amount of filesystem walking and database calls, so it'll use 100% of CPU for a while (as anything that uses the CPU does), the only question is for how long. Usually this is a quick process - i.e. in my laptop it's usually done in a few fractions of a second. If the rescan does take a long time, due to being low on memory for caches or having slow CPUs etc it can certainly help to use inotify because it removes the need to periodic scans as often, as Audrius says.

**Comment by keltia** [comment]
I can certainly understand that.  My point is more that it is not mentioned anywhere in the documentation (except as a side-project — https://docs.syncthing.net/search.html?q=inotify&check_keywords=yes&area=default) while it is for me a rather important "plugin" that could even be incorporated in the core as enough systems have such a notification system (inotify, kqueue, kqueue64 and whatever in windows).  I have a 8 GB MBA and VSS is already 546 GB.  It is significantly slowing down my machine (even though it has an SSD) even with only one other device connected… The documentation of syncthing-inotify is also rather small and apart from freading the source, I don't know how it works (is it suspending the regular scanning or adding its notification and so on).
