### ISSUE TITLE
Ongoing panic crashes on Win 7 x64 running inside SyncTrazor

### ISSUE THREAD

**Issue by jemxpat** [syncthing/syncthing#3072]
Syncthing v0.12.23
OS Version: Windows 7 x64
I am running syncthing on about 50 machines, mostly Gentoo Linux boxes, but a large number of Macs and a few Windows machines. One of the Windows machines is having recurring problems. This is the latest crash message:

[R7AKL] 10:53:15 INFO: syncthing v0.12.23 "Beryllium Bedbug" (go1.6.2 windows-amd64) WIN-P6RP886TVDJ\Administrator@WIN-P6RP886TVDJ 2016-05-06 14:16:28 UTC
[...]
panic: xdr read: EOF
goroutine 133 [running]:
panic(0xb79760, 0xc085b28360)
	c:/go/src/runtime/panic.go:481 +0x3f4
github.com/syncthing/syncthing/lib/db.(*Instance).updateFiles(0xc082020068, 0xc088e92510, 0xa, 0x10, 0xc087878800, 0x20, 0x20, 0xc08aa46000, 0x26e, 0x26e, ...)
	c:/jenkins/workspace/syncthing-release-windows/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:211 +0x6e4

I have tested the system drives and done a deep memory check. All tests passed.

Any clues about what may be wrong? I have seen nothing like this in any other machine.

-jem

**Comment by calmh** [comment]
My best guess is that the index database has become corrupted for whatever reason, but we should be able to handle this a little bit more gracefully... I have a thing that may help with that somewhere, I'll look for it later today.

**Comment by jemxpat** [comment]
Yeah, I thought that also, and a couple of times removed and rebuilt the index db. The problem keeps returning.

-jem

**Comment by calmh** [comment]
That might still be the case, but it's interesting that it keeps happening on that box in particular. Anything else weird happening on it? Bad disk? Bad antivirus software? Keeps getting hard power cycled?

**Comment by jemxpat** [comment]
None of the above. Main use is running VLC. Error does not seem to be correlated to having VLC running or not.

-jem

**Comment by calmh** [comment]
No XDR reads remain in the code, so this is gone per definition.
