### ISSUE TITLE
Panic during startup: `fatal error: found bad pointer in Go heap`

### ISSUE THREAD

**Issue by exrook** [syncthing/syncthing#3073]
### The Issue
During startup syncthing panics during startup with the panic message:
```
runtime: pointer 0xc8213d6360 to unused region of spanidx=0x9eb span.start=0xc821a8e000 span.limit=0xc821a90000 span.state=0
runtime: found in object at *(0xc820010510+0x20)
object=0xc820010510 k=0x6410008 s.start*_PageSize=0xc820010000 s.limit=0xc820011fe0 s.sizeclass=4 s.elemsize=48
 *(object+0) = 0xc820066070
 *(object+8) = 0xc8207760a0
 *(object+16) = 0x0
 *(object+24) = 0xc820cfc3c0
 *(object+32) = 0xc8213d6360 <==
 *(object+40) = 0x0
fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)
```
###  Steps to reproduce
Start syncthing, note this panic only occurs some of the time, the rest of the time there is a less descriptive `fatal error: runtime: out of memory` panic, when I have 8GB memory + 8GB swap with 2.25GB usage

### Version Information

- Syncthing Version: v0.12.23
- OS Version: Arch Linux
- Browser Version: n/a
- [`bad pointer` panic log](https://gist.github.com/exrook/34debc00b3b0b4e085c9187378c97765)
- [`runtime: out of memory` panic log](https://gist.github.com/exrook/5ff25e95a8cd9b1490793ea445fb9135)

**Comment by calmh** [comment]
That's odd. Did it use to work in a previous version? Does it work with a build from github (the releases tab here)?

**Comment by exrook** [comment]
Yes, forgot to mention that I tested on every version of the package in my cache since 0.12 and they each exhibited similar behavior. Syncthing has worked very well for me in the past on this computer with over 20GB of files in my shared folders, and I've been using it across several devices since 0.11. I'm not entirely sure when the panic appeared, but it seems to have been sometime in the last month. I feel I should note that I have an unusual setup with synced folders inside other shared folders (I have a large private synced folder, and I add subfolders to syncthing to share with others), which could be related but seemed to be working fine before this started happening. My other suspicion would be it being related to updating syncthing and some process failing, possibly corrupting a file?

**Comment by AudriusButkevicius** [comment]
Are you using the releases from our repos/github or your distro repos?
They often compile using gccgo which is a compiler we don't support.

**Comment by calmh** [comment]
Panic log looks distribution compiled, go 1.6.2. No clues from me here. Wipe, reset, see what happens. Save a copy of the index for forensics...

**Comment by exrook** [comment]
I cleared the cache and started syncthing, then recieved this [new panic](https://gist.github.com/exrook/be91865aac919d16f340bb6ebf6c6785). Syncthing then appeared to run stably, then panic-ed again after 18 mintues, followed by another panic on the next restart, however the second restart seems to have succeeded so far.
I hypothesize that the panic may be being caused by a some symbolic links I have inside one of my folders, I have 1100 of them that all point to files within the same shared folder, as the creation of these links seems to roughly match when I noticed these crashes. This would also match the irregularity of the crashes, as I assume they happen as syncthing is scanning the folder in question which is 10GB with 330,000 files and I assume syncthing scans in a random order, so presumably when one of these links is scanned, the code panics. I figure that before clearing the cache all other files had already been scanned so syncthing would immediately look at the symlinks, causing the panic.

**Comment by exrook** [comment]
Hmmm, syncthing seems to have finished scanning all of my folders without an additional panic. I'm now at a uptime of 31m with all folders marked as up to date. However it is interesting to see that on the shared folder with symbolic links, there is a mismatch between the global state size and local state size
```
Global State 	363193 items, ~9.06 GiB
 Local State 	363193 items, ~8.95 GiB
```

**Comment by exrook** [comment]
I now realize that the symbolic links have been correctly replicated on other devices which do not exhibit the same panics, so I believe that my earlier guess is not entirely correct

**Comment by AudriusButkevicius** [comment]
I suggest you replace the binary you have with the one available on github and see if it happens.
I doubt if it's related to symlinks to be honest.

**Comment by AudriusButkevicius** [comment]
This is really suspicious. 0xb is 11, which is SIGSEV, which I thought only happens with cgo.

**Comment by exrook** [comment]
I installed syncthing v0.12.23 from github and syncthing seems to be exhibiting identical behavior to the distro release, following the pattern of seeming stability for a few minutes, then a panic, and 2 more panics following before a fourth launch seems to stabilize. 
[panic log](https://gist.github.com/exrook/0e68d8a565b7aa8e54c904458cbb9ef7)

**Comment by AudriusButkevicius** [comment]
So I think this is something that perhaps should be raised with Go devs.

**Comment by calmh** [comment]
Frankly, I think this is hardware error (bad memory, motherboard, CPU).

**Comment by exrook** [comment]
I have just completed running memtest86, which reported no errors. I haven't had any other issues like this in the past on this device, which I've been using for a few years now, but perhaps something could be going on that's only been triggered by syncthing.
I also just checked restoring the old index, and it seems to be reliably reproducing the `fatal error: out of memory` panic.

**Comment by AudriusButkevicius** [comment]
Out of memory is self explanatory tho.

**Comment by exrook** [comment]
That's the issue, I'm not out of memory


### /proc/memstat
```
MemTotal:        8123224 kB
MemFree:         3000136 kB
MemAvailable:    5792484 kB
Buffers:          480872 kB
Cached:          1652612 kB
SwapCached:            0 kB
Active:          3089468 kB
Inactive:        1031160 kB
Active(anon):    1988636 kB
Inactive(anon):    10120 kB
Active(file):    1100832 kB
Inactive(file):  1021040 kB
Unevictable:           4 kB
Mlocked:               4 kB
SwapTotal:       8347644 kB
SwapFree:        8347644 kB
Dirty:              1320 kB
Writeback:             0 kB
AnonPages:       1811184 kB
Mapped:           443208 kB
Shmem:             11620 kB
Slab:             821460 kB
SReclaimable:     751440 kB
SUnreclaim:        70020 kB
KernelStack:        6896 kB
PageTables:        21680 kB
KsmZeroPages:     139240 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    12409256 kB
Committed_AS:    4593672 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:    395264 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      246220 kB
DirectMap2M:     8097792 kB
```

**Comment by AudriusButkevicius** [comment]
Are you running a 32 bit build?

**Comment by exrook** [comment]
No

**Comment by calmh** [comment]
Just for fun, start with `GODEBUG=gctrace=1 syncthing -no-restart` and paste what it says from startup to crash somewhere

**Comment by exrook** [comment]
[Here you go](https://gist.github.com/exrook/994c7a402adbc104cf16b1cfb62c6fbb)

**Comment by AudriusButkevicius** [comment]
Why aren't you using official builds?

**Comment by exrook** [comment]
I am using the amd64 release downloaded from [this page](https://github.com/syncthing/syncthing/releases/tag/v0.12.23) with a sha256 hash of `e8c9f0a1f679bc49c3c1c64d748aed17864915b7e87109cad3f511ecb2a21682` If you recommend testing a different official build, I would be happy to do so. 
The sha256 of my `/usr/bin/syncthing` is `11bf01db5df01e16ea4cd2d33cd076fbf9afb5d6bab4ffe998b684a7ac1093ff`

**Comment by AudriusButkevicius** [comment]
Sorry, my bad, it seems that we build stuff differently than we used to.

**Comment by exrook** [comment]
No problem :)
So I ran strace and noticed a very peculiar pattern.
The second thread spawned exhibits this behavior. I'm not sure why it tries to allocate 192 GiB, and then in even stranger behavior tries to check if every page loaded by the failed call is active in memory or not, perhaps this portion is a go bug?
```
......

13700 pread64(11, "\254 $\0\221\1L\1XXXXXXXX"..., 869, 667462) = 869
13700 pread64(27, "\216 (\0\250\1\250\1\0YYYYYY"..., 824, 1982928) = 824
13700 pread64(27, "\217 (\0\253\1\254\1\0YYYYYY"..., 829, 1983752) = 829
13700 pread64(11, "\255 $\0\214\1L\1XXXXXXXX"..., 858, 668331) = 858
13700 pread64(27, "\361 (\0\255\1\254\1\0YYYYYY"..., 863, 1984581) = 863
13700 pread64(27, "\250 (\0\270\1\270\1\0YYYYYY"..., 867, 1985444) = 867
13700 pread64(11, "\237 $\0\230\1L\1XXXXXXXX"..., 866, 669189) = 866
13700 mmap(0xc822400000, 206158430208, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
13700 mincore(0xc822400000, 4096, 0x1193016) = -1 ENOMEM (Cannot allocate memory)
13700 mincore(0xc822401000, 4096, 0x1193016) = -1 ENOMEM (Cannot allocate memory)
13700 mincore(0xc822402000, 4096, 0x1193016) = -1 ENOMEM (Cannot allocate memory)
13700 mincore(0xc822403000, 4096, 0x1193016) = -1 ENOMEM (Cannot allocate memory)
13700 mincore(0xc822404000, 4096, 0x1193016) = -1 ENOMEM (Cannot allocate memory)

*snip* mincore is called on every page that would've been allocated if the mmap succeeded, 

0xf8223ff000 - 0xc822400000
13700 mincore(0xf8223fe000, 4096, 0x1193016) = -1 ENOMEM (Cannot allocate memory)
13700 mincore(0xf8223ff000, 4096, 0x1193016) = -1 ENOMEM (Cannot allocate memory)
13700 mmap(0xc822400000, 206158430208, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0 <unfinished ...>
13718 <... futex resumed> )             = -1 ETIMEDOUT (Connection timed out)
13718 futex(0x1176ca0, FUTEX_WAIT, 0, {0, 100000} <unfinished ...>
13700 <... mmap resumed> )              = -1 ENOMEM (Cannot allocate memory)
13700 write(2, "fatal error: ", 13 <unfinished ...>
13718 <... futex resumed> )             = -1 ETIMEDOUT (Connection timed out)
13718 futex(0x1176ca0, FUTEX_WAIT, 0, {0, 100000} <unfinished ...>
13700 <... write resumed> )             = 13
13718 <... futex resumed> )             = -1 ETIMEDOUT (Connection timed out)
13700 write(2, "runtime: out of memory", 22 <unfinished ...>

......
```

**Comment by AudriusButkevicius** [comment]
uname -a ?

**Comment by exrook** [comment]
`Linux george-arch 4.5.1-pf #1 SMP PREEMPT Tue May 10 19:03:50 EDT 2016 x86_64 GNU/Linux`
If you think it's necessary, I can test with a mainline kernel as well.

**Comment by AudriusButkevicius** [comment]
I don't think it's the kernel.
What about `getconf PAGESIZE`?

To be honest, I feel this one is for the Go team, as it's their runtime.

**Comment by AudriusButkevicius** [comment]
Also, did you try compiling it yourself?

**Comment by exrook** [comment]
```
$ getconf PAGESIZE
4096
```
I built syncthing from source, and it exhibits identical behavior with regards to panic-ing and strace

**Comment by calmh** [comment]
Still though. 192 megs isn't a super unreasonable allocation in my mind when it needs to grow the heap. Perhaps there is something large in the index it wants to allocate the block list for, etc. It does look like you're simply running out of memory?

**Comment by AudriusButkevicius** [comment]
I think it's GB not MB in tge mmap call?

**Comment by calmh** [comment]
Eh. 192 GiB is indeed a little bit excessive. My bad.

**Comment by AudriusButkevicius** [comment]
Right, I suggest you delete the index directory and let syncthing rescan.
This could be caused by a corrupt database.

**Comment by exrook** [comment]
Yes, I have already provided logs above of panics I get when I delete the index. I just tested again and it again exhibited similar behavior (with locally-compiled v0.12.23 syncthing)

**Comment by AudriusButkevicius** [comment]
Can you check if it panics if you run it without any folders?

**Comment by AudriusButkevicius** [comment]
Is this in a VM?

**Comment by exrook** [comment]
Nope, I will note though that the panic seems to have resolved itself recently and I haven't encountered it for a week or two, so I really have no idea what could be causing it.
