### ISSUE TITLE
Disabling relays is ignored

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3074]
```
jb@syno:~/s/g/s/s/test $ grep relay h1/config.xml
        <relayReconnectIntervalM>10</relayReconnectIntervalM>
        <relaysEnabled>false</relaysEnabled>
jb@syno:~/s/g/s/s/test $ syncthing -home h1 | grep relay
[I6KAH] 08:30:20 INFO: Joined relay relay://46.227.69.173:22067/?id=7ZBBJPN-D6LZI22-XYRSXC3-THRJHWO-6C62DOP-AADPIRH-EYXKFRB-JSAH5AR&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=4194304&statusAddr=:22070&providedBy=vet
^C
```

**Comment by calmh** [comment]
So apparently `relaysEnabled` was deprecated, but it's still present in the XML config (lacks `,omitempty` tag). However, what is the intention for how the user should disable relaying? By changing the `default` listen address to `tcp://0.0.0.0:22000`? That's hardly discoverable :(

The config upgrade code must also take this into account, whatever we do here, so that the existing preference is retained.

To me, it seems like the simplest and cleanest solution is to resurrect the `relaysEnabled` option, and just have `default` not mean relays in that case. In fact, I'll prepare a PR for that for discussion, and if some better idea comes up in the meantime we can do that instead. :)

**Comment by AudriusButkevicius** [comment]
The upgrade code does take that intonaccount

**Comment by calmh** [comment]
The upgrade code is a bit weird, I think it assumes you're upgrading from a previous beta. It looks for the dynamic+https stuff in listen addresses, which we didn't have in v0.12

**Comment by AudriusButkevicius** [comment]
Yes we did.

**Comment by calmh** [comment]
No, we really didn't. :)

**Comment by AudriusButkevicius** [comment]
We had it in the relay addresses, both relay:// and dynamic... The refactor just consolidated the two. If the problem is the obscurity involved disabling, then let's remove the "default" bit.

**Comment by calmh** [comment]
Actually that might be better...

**Comment by AudriusButkevicius** [comment]
Just because noe adding a relay into listen addresses and unchecking relays enabled, it will still connect.

**Comment by calmh** [comment]
Yeah, and that's crap. The downside with just having it in the text box directly is that once removed it's a weird string that must be added back to enable it again, but that could conceivably be taken from another box or a default config (ugh...)...

Another issue I see is that even when removing the relay listen address, I might still connect to other devices using the relay. What if I *really don't want to use relays*?

**Comment by AudriusButkevicius** [comment]
Or change it into default and default-relays

**Comment by calmh** [comment]
Frankly, I think explicit is better here. We can add it into the help or something...

**Comment by AudriusButkevicius** [comment]
Maybe we should have a separate config entry called blacklistedDialers for disabling dialing?

**Comment by calmh** [comment]
Or, reviving your idea from above, replacing the magic device address `dynamic` address with `dynamic-local-tcp, dynamic-global-tcp, dynamic-relays` ... Also ugly as hell though

**Comment by calmh** [comment]
Or just checkboxes per device, implementing the blacklistedDialers.

```
[X] Use TCP
[ ] Use relays
```

Unchecking both disables the device...

**Comment by AudriusButkevicius** [comment]
So I don't think anyone will ever need that level of control. Ghrr, all options so far feel like shit.

Maybe we add relaysEnabled back, and then return ErrDisabled which is handled gracefully from both dialer and lister and bring back "default" ?

**Comment by AudriusButkevicius** [comment]
I think there is value in "default" as deploying utp or whatever will have bigger adoption straight away.

**Comment by calmh** [comment]
That's true. In that case my first PR is quite close to the truth, except it doesn't handle dialers yet.

**Comment by AudriusButkevicius** [comment]
Agree
