### ISSUE TITLE
Deadlock when adding folder

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3077]
Backtrace in https://gist.github.com/apuckey/c58e71895cf24f04a2bd6cfc9996a0bc

- config.Wrapper holds its lock, calls model.CommitConfiguration which calls model.StartFolder which wants fmut.
- model.ConnectionStats is running which holds fmut, calls cfg.Devices which wants the Wrapper lock

**Comment by AudriusButkevicius** [comment]
Time to move to atomic.Value ? :D

**Comment by AudriusButkevicius** [comment]
Or move more locks to RWLocks?

**Comment by calmh** [comment]
Yeah, looking at it... It's actually fairly tricky. RWLocks don't help here as it's stuff that is concurrent with replacing the config. An atomic.Value might actually work.

**Comment by calmh** [comment]
Another option could be to say that code running in CommitConfiguration is not allowed to call back into cfg (the config.Wrapper) - it must use the provided now and old configs.

**Comment by AudriusButkevicius** [comment]
It seems that most of these issues happen when config is involved, just because of how unpredictable the code paths become in a callback based code. In this specific case there is no calling back to config fron CommitConfiguration, but rather some external mutex which screws us over.

**Comment by calmh** [comment]
Yes... And part of the problem is that CommitConfiguration calls all these things synchronously and locked, and they must all return before the config becomes unlocked etc. This is all to set the "must restart" flag, which is also a bit buggy - it only gets set when the config is changed through the JSON push, but we also update the config internally with SetDevice and so on.

One option here could be to remove the return value from CommitConfiguration, and run those asynchronously from the Wrapper. No locking, no waiting for the commit to complete. We could track the need to restart in some other way, and that should hopefully go away with time. It might even be a push in that direction...

**Comment by calmh** [comment]
Planned, but not necessarily v0.13 as this bug is present in v0.12 as well
