### ISSUE TITLE
Rejiggle the protocol for future extensibility

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3080]
Protobuf is current candidate.

**Comment by fdietze** [comment]
https://capnproto.org might be worth a look.

**Comment by canton7** [comment]
There's a discussion on the forum if you want the details (can't remember whether it's public actually...)

**Comment by calmh** [comment]
https://forum.syncthing.net/t/future-stability-of-the-protocol/7324/32

**Comment by calmh** [comment]
Directing discussion there

**Comment by calmh** [comment]
Done by #3276
