### ISSUE TITLE
Automatic upgrade: no version to select

### ISSUE THREAD

**Issue by jpjp** [syncthing/syncthing#3086]
INFO: syncthing v0.12.23 "Beryllium Bedbug" (go1.6.2 linux-amd64)
    INFO: Automatic upgrade: no version to select

**Comment by calmh** [comment]
Fuck, I broke upgrades :(

**Comment by jpjp** [comment]
That's going to mess up the stats :)

At least you broke people onto the fixed version!

**Comment by calmh** [comment]
The problem is that we're limiting the JSON response to less than what Github is actually returning. Fixing it is trivial (increasing the expected limit, should have checked that closer...). Workarounds include changing the upgrade URL in the config to return fewer releases, but that's not going to happen... We're going to have a lot of people on v0.12.23 for a long time, I think.

**Comment by jpjp** [comment]
What if you made Github return more releases?

**Comment by AudriusButkevicius** [comment]
Can we remove/hide older releases to reduce the page size?

**Comment by calmh** [comment]
Less releases, so the response is smaller and fits within our limits. I think we'd need to unpublish every release ever. Which we might want to do at some point, to move things forward for those poor users.

**Comment by AudriusButkevicius** [comment]
I wonder if we can just hide then temporarily?

**Comment by wweich** [comment]
According to the [official GitHub help](https://help.github.com/categories/releases/), we cannot hide releases.

I did some testing, and we would have to delete all but 3 releases for the auto upgrade to not log `no version to select`.

**Comment by AudriusButkevicius** [comment]
How much effort is it to recreate them back afterwards? I guess we could write some scripts that do this?

**Comment by calmh** [comment]
Yeah, we have scripts for it really, same as we use for normal releases. We would just need to actually download all of the assets first. We might not even need to put them back, we could just keep the assets in an archive of our own and call it spring cleaning. Not that many people need to download the old versions, and when those who do come around we can point to the archive...

**Comment by calmh** [comment]
Reopening for visibility as this still affects v0.12.23 until we work around it somehow.

**Comment by AudriusButkevicius** [comment]
Where will the archive be though?

**Comment by calmh** [comment]
upgrades.syncthing.net/oldcarp.html ?

**Comment by calmh** [comment]
I don't foresee a lot of traffic to it once it's downloaded, and there is we can cloudflare the crap out of it.

**Comment by calmh** [comment]
Except, as you were maybe implying, it doesn't actually fit on the disk of that little VM. I can host it myself on nym.se for the time being as I don't want to expand that disk.

**Comment by canton7** [comment]
Or you can just stick them on S3?

**Comment by calmh** [comment]
Potentially yeah, although that means signing up for that. :) Downloading to http://archive.syncthing.net currently, takes a while with non-infinite bandwidth.

**Comment by calmh** [comment]
We could even commit them to a repo and push it to Github. It's a 20 gig repo, but all of the files are less than 10 megs... :)

(That would probably get dropped fairly quickly with a stern warning from Github so let the protocol note that I'm just kidding here.)

**Comment by wweich** [comment]
I have a S3 account and could put the files there. I already tested it with the current version which is accessible via https://syncthing-old.s3.amazonaws.com/v0.12.23/{filename} (e.g. https://syncthing-old.s3.amazonaws.com/v0.12.23/syncthing-linux-amd64-v0.12.23.tar.gz)

**Comment by calmh** [comment]
This has now happened.

**Comment by uok** [comment]
Thanks for fixing! Maybe we should give the [newsletter idea](https://forum.syncthing.net/t/syncthing-newsletter-mailing-list/6038) another go to have a way to inform users directly, e.g. if Syncthing needs manual admin labor :beer:

**Comment by cdpb** [comment]
Is it really fixed?
```
journalctl --since today -u syncthing@syncthing

Jun 11 00:23:58 pir syncthing[431]: [KYDOH] INFO: Automatic upgrade: no version to select
Jun 11 12:23:59 pir syncthing[431]: [KYDOH] INFO: Automatic upgrade: no version to select

./syncthing-cli version

Architecture:	arm
Codename:	Beryllium Bedbug
Long version:	syncthing v0.12.23 "Beryllium Bedbug" (go1.6.2 linux-arm) unknown-user@9c88c96d5969 2016-05-06 14:16:28 UTC
OS:		linux
Version:	v0.12.23

./syncthing-cli upgrade

no version to select

./syncthing-cli status

Config in sync
```

**Comment by AudriusButkevicius** [comment]
It's impossible to fix it permanently.
We had a pretty large few week window where everyone could update to a fixed release, but you choose not to.

**Comment by cdpb** [comment]
oh that's a pitty. Okay I'll update manually. Thanks for clarification

**Comment by kricsek** [comment]
Workaround:
syncthing -upgrade-to=https://github.com/syncthing/syncthing/releases/download/v0.12.25/syncthing-<version>-v0.12.25.tar.gz
