### ISSUE TITLE
Syncthing refuses some connections after resume from sleep

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#3087]
I'm seeing an issue where:
 - The computer resumes from sleep. (Syncthing spots this, and schedules a restart for 1m00)
 - Syncthing is responsive to at least some API requests: I can fetch some events
 - However, a connection to `/rest/system/resume` fails with "No connection could be made because the target machine actively refused it".

Can you think of a reason why the events API may be working, but Syncthing refuses connections to `/rest/system/resume`?

Syncthing version 0.12.23.

Related to https://github.com/canton7/SyncTrayzor/issues/260.

**Comment by AudriusButkevicius** [comment]
It's the same webserver, so sounds like magic that other things are working.

**Comment by calmh** [comment]
Add info if reproducible, but sounds weirdly magic indeed
