### ISSUE TITLE
Large volume of index files

### ISSUE THREAD

**Issue by bshafer** [syncthing/syncthing#3094]
**What happened**
Syncthing started creating a large number of index files

**What you expected to happen instead**
Index files to remain relatively minimal

**Any steps to reproduce the problem**
Note: I haven't tried to reproduce the problem in a test environment, but it did occur to a lesser extent on my syncthing instances that are running as a service and not under SyncTrayzor.

1. Run syncthing v0.12.23 under SyncTrayzor v1.1.9 with 1.7 million files (582 GiB)
2. Let syncthing upgrade to v0.12.24
3. Come in the next morning and find your SSD boot drive almost full (22 GiB in 10k files found in C:\Users\<myUserName>\AppData\Local\Syncthing\index-v0.11.0.db\

### Version Information

Syncthing Version: v0.12.24
OS Version: Windows 10

**Comment by AudriusButkevicius** [comment]
Doesit go away if you restart?

**Comment by bshafer** [comment]
Yes.

**Comment by AudriusButkevicius** [comment]
Then it's potentially related to the volume of changes you have. It seems to fix itself after compaction.

**Comment by lkwg82** [comment]
what about having a threshold of x% relative to the beginning of scanning when to stop the scanning and compact the database. This can be iterative. I suggest a threshold of about 200%. But havnt thought long about that.

**Comment by AudriusButkevicius** [comment]
These things should be handled by the database to be honest, but you are not the first one reporting this. 

Dup #2400
