### ISSUE TITLE
Please move the debian folder

### ISSUE THREAD

**Issue by aviau** [syncthing/syncthing#3099]
Hello,

Can you please move the debian folder away? I am packaging syncthing for Debian and it interferes with my work.

See our [upstream guide](https://wiki.debian.org/UpstreamGuide)
> Some projects include a rough /debian directory among source files to ease bleeding-edge package compilation and installation on debian (and derived) systems. While this is a good effort, it is better to leave it out of the final tarball as it can interfere with debian's own packaging effort.

So, in other news, Syncthing is coming to Debian. :tada:

**Comment by lkwg82** [comment]
Hmm, I think for the time of transition, from current state to future state, it makes sense to have a workaround on your site. When the time is over, it is on us the move on and throw it away.

Does this makes sense to you?

**Comment by aviau** [comment]
You don't have to throw it away.  Just rename the folder with a different name,  like "contrib/debian", "packaging/debian" or "debian-syncany". 

I do have a workaround until you do that.

**Comment by calmh** [comment]
> So, in other news, Syncthing is coming to Debian. :tada:

That's great news! I'll make sure to move the folder out of the way soonish! Currently working on releasing v0.13, but as soon as that is out.
