### ISSUE TITLE
Missing license notices

### ISSUE THREAD

**Issue by aviau** [syncthing/syncthing#3100]
Hello,

The following files are missing a copyright notice and this makes distributing them illegal.

Just including the full license in the file headers would be perfect (and make me a very happy Debian Developer).
 
**MIT:**

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software

- [x] gui/default/vendor/angular/angular-dirPagination.js
- [x] gui/default/vendor/angular/angular-translate-loader-static-files.js
- [x] gui/default/vendor/angular/angular-translate.js
- [x] gui/default/vendor/angular/angular.js

**BSD-3-Clause:**
> Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

- [x] lib/osutil/mkdirall_windows.go
- [x] lib/upnp/igd_service.go
- [x] lib/upnp/igd.go
- [x] lib/upnp/upnp.go

I haven't looked at the whole repo yet (because I am sleepy!), so I'll update this issue as I go. Feel free to check check the boxes as the licenses are fixed.

**Comment by lkwg82** [comment]
Do we insert licenses in vendor files?

**Comment by calmh** [comment]
The ones mentioned above are manually copied. The otherwise vendored code includes it's licenses.

**Comment by aviau** [comment]
*assigning myself*

I'll prepare a pull request,
