### ISSUE TITLE
In sync percentage > 100%

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3102]
Due to temp indexes, somehow. Cosmetic, but ugly.

**Comment by calmh** [comment]
It would be nice to find this one and close it in an early v0.13 point release as well, because I bet we're going to get a lot of reports on it. :)

**Comment by AudriusButkevicius** [comment]
Yeah, still waiting for repro steps.

**Comment by calmh** [comment]
As far as I can tell, it's just to sync files. It's reproducible in my main setup, but I haven't tried to repro it yet with the small test configs, due to -ENOTIME

**Comment by AudriusButkevicius** [comment]
I tried with a basic test setup, and couldn't repro.

**Comment by bigbear2nd** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/7719800/15448632/aaae92d2-1f67-11e6-806c-01895984c210.PNG)
New record :)

**Comment by bigbear2nd** [comment]
As it is syncing, (no new files added), it is getting bigger:
![unbenannt](https://cloud.githubusercontent.com/assets/7719800/15448651/39b89cc0-1f68-11e6-8408-79bfab739211.PNG)

**Comment by canton7** [comment]
Nah, people on the forums have percentages in the millions (both positive and negative): you're nowhere close :wink:

**Comment by calmh** [comment]
Fixed by fc173bf supposedly
