### ISSUE TITLE
Shared folders and Remote devices disappeared after upgrade to Syncthing 0.13

### ISSUE THREAD

**Issue by mrbrahman** [syncthing/syncthing#3107]
Looks like all the shared folders suddenly vanished after upgrading to 0.13. Also, syncthing is not seeing other devices that are online (see attached screenshot)

![selection_001](https://cloud.githubusercontent.com/assets/16898939/15331244/6dc55266-1c2e-11e6-8ee4-15f7a3c5cb0f.png)

This is on Linux Mint. I use Syncthing GTK.

Any one else facing this issue? Any idea how I can restore the shared folders without having to manually re-share them again?

Thanks!

**Comment by biermeester** [comment]
I noticed the same thing on Windows. I hope it's because of this:

> The database format has changed. It will be migrated without rescan on first startup, but the first startup may take longer than usual.

**Comment by AudriusButkevicius** [comment]
Did you try syncthing without gtk just the web ui?

**Comment by biermeester** [comment]
My Syncthing is showing all folders and remote devices again, so I guess the delay was because of the migration.

**Comment by mrbrahman** [comment]
You're right! I'm seeing everything again. Guess I had to just wait...

However, I do notice that this Linux device is not seeing other devices (which are not on 0.13 yet), and vice versa. Do all devices have to be on 0.13 now?

**Comment by AudriusButkevicius** [comment]
It's clearly explained in the release notes.
