### ISSUE TITLE
Just updated and now Synthing borked (on Linux Mint)

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [syncthing/syncthing#3111]
[Screenshot here.](http://imgur.com/a/GGvPn)

Notice the missing folder pane and also how much - even the 'ok' and 'cancel' buttons in the foremost window - is greyed out.

Synthing (GTK) v0.8.3 (Daemon v0.13.0)
Linux Mint 17.3 x64. Kernel x86_64 Linux 4.2.0-36-generic.

**Comment by AudriusButkevicius** [comment]
Wrong repo. Try syncthing-gtk
