### ISSUE TITLE
连接类型被限制在Connection Type "Relay"并且速度受限

### ISSUE THREAD

**Issue by leang521** [syncthing/syncthing#3112]
更新最新的0.13版本后，连接速度发生变化。仔细观察状态发现和之前的区别在多了一个“Connection Type -Relay”，这在以前是没有的。
我现在的使用环境是两台主机都在内网中，一台可以UPnP，一台不能进行UPnP。
在0.12版本不存在这个问题，是可以直接连接的，但是在0.13版本就只能进行“Relay”。
目前已经严重影响同步速度。

**Comment by leang521** [comment]
此外，在使用过程中经常丢失连接，无法完成第一次完整同步就断开，陷入不断的死循环中

**Comment by calmh** [comment]
In English?

**Comment by calmh** [comment]
From google translate I get the gist of it to be "v0.13 can only connect via relay; v0.12 worked fine". Can you post your config, perhaps?

**Comment by AudriusButkevicius** [comment]
0.12 didn't report how it was connected, and 0.13 does, so it's likely you were always connected via relay just didn't know.

**Comment by fragtion** [comment]
For the record, I have all forms of relaying disabled on my syncthing instances since early v0.12 builds, and have noticed no problem with connections since upgrade to v0.13. My repos are connecting fine despite relaying & global discovery completely disabled. Sounds like an issue with network config? Coincidence?

**Comment by fragtion** [comment]
Is this not the same issue as #7388 ?

**Comment by AudriusButkevicius** [comment]
No, that one is about rapid connection switching.

**Comment by calmh** [comment]
I'm considering this one mysterious and abandoned. leang521, let us know if that's not the case.

**Comment by leang521** [comment]
- <configuration version="15">
- <folder id="default" label="" path="--------" type="readwrite" rescanIntervalS="60" ignorePerms="false" autoNormalize="true">
  <device id="----------" /> 
  <device id="----------" /> 
  <minDiskFreePct>1</minDiskFreePct> 
  <versioning /> 
  <copiers>0</copiers> 
  <pullers>0</pullers> 
  <hashers>0</hashers> 
  <order>random</order> 
  <ignoreDelete>false</ignoreDelete> 
  <scanProgressIntervalS>0</scanProgressIntervalS> 
  <pullerSleepS>0</pullerSleepS> 
  <pullerPauseS>0</pullerPauseS> 
  <maxConflicts>10</maxConflicts> 
  <disableSparseFiles>false</disableSparseFiles> 
  <disableTempIndexes>false</disableTempIndexes> 
  </folder>
- <device id="----------" name="leang-PC" compression="metadata" introducer="false">
  <address>dynamic</address> 
  </device>
- <device id="---------" name="FreeNAS" compression="metadata" introducer="false">
  <address>dynamic</address> 
  </device>
- <gui enabled="true" tls="false">
  <address>127.0.0.1:8384</address> 
  <apikey>----------</apikey> 
  <theme>default</theme> 
  </gui>
- <options>
  <listenAddress>default</listenAddress> 
  <globalAnnounceServer>default</globalAnnounceServer> 
  <globalAnnounceEnabled>true</globalAnnounceEnabled> 
  <localAnnounceEnabled>true</localAnnounceEnabled> 
  <localAnnouncePort>21027</localAnnouncePort> 
  <localAnnounceMCAddr>[ff12::8384]:21027</localAnnounceMCAddr> 
  <maxSendKbps>0</maxSendKbps> 
  <maxRecvKbps>0</maxRecvKbps> 
  <reconnectionIntervalS>60</reconnectionIntervalS> 
  <relaysEnabled>true</relaysEnabled> 
  <relayReconnectIntervalM>10</relayReconnectIntervalM> 
  <startBrowser>false</startBrowser> 
  <natEnabled>true</natEnabled> 
  <natLeaseMinutes>60</natLeaseMinutes> 
  <natRenewalMinutes>30</natRenewalMinutes> 
  <natTimeoutSeconds>10</natTimeoutSeconds> 
  <urAccepted>-1</urAccepted> 
  <urUniqueID /> 
  <urURL>https://data.syncthing.net/newdata</urURL> 
  <urPostInsecurely>false</urPostInsecurely> 
  <urInitialDelayS>1800</urInitialDelayS> 
  <restartOnWakeup>true</restartOnWakeup> 
  <autoUpgradeIntervalH>12</autoUpgradeIntervalH> 
  <keepTemporariesH>24</keepTemporariesH> 
  <cacheIgnoredFiles>false</cacheIgnoredFiles> 
  <progressUpdateIntervalS>5</progressUpdateIntervalS> 
  <symlinksEnabled>true</symlinksEnabled> 
  <limitBandwidthInLan>false</limitBandwidthInLan> 
  <minHomeDiskFreePct>1</minHomeDiskFreePct> 
  <releasesURL>https://upgrades.syncthing.net/meta.json</releasesURL> 
  <overwriteRemoteDeviceNamesOnConnect>false</overwriteRemoteDeviceNamesOnConnect> 
  <tempIndexMinBlocks>10</tempIndexMinBlocks> 
  </options>
  </configuration>

**Comment by calmh** [comment]
Nothing wrong with what I can understand from the visible parts of the config. :)

**Comment by leang521** [comment]
谢谢，升级到0.13.1后就好了
