### ISSUE TITLE
is 0.13 backwards compatible with 0.12?

### ISSUE THREAD

**Issue by daniel-lucio** [syncthing/syncthing#3113]
just a simple compatibility question.

**Comment by uok** [comment]
No. Please close this issue and check [forum](https://forum.syncthing.net/t/syncthing-v0-13-0-beta-4-last-chance-to-test-before-you-have-to-live-with-it-forever/7277) and [release notes](https://github.com/syncthing/syncthing/releases/tag/v0.13.0) for more info

**Comment by AudriusButkevicius** [comment]
Is it that hard to read the release notes?
