### ISSUE TITLE
Invalid IGD response: invalid device UUID

### ISSUE THREAD

**Issue by acmodeu** [syncthing/syncthing#3114]
Every 30 minutes I get
> INFO: Invalid IGD response: invalid device UUID UUID-bla-bla-bla (continuing anyway)

message in the log file. Is there anything I can do about it or should I just ignore it? I'm using syncthing 0.13 on a Windows 8.1 machine with UPnP port mapping behind Mikrotik router.

**Comment by AudriusButkevicius** [comment]
It's an info message. You can tell your router vendor to fix their software that does not adhere to standards.

**Comment by silversword411** [comment]
I'm getting this off a Mikrotik device. What RFC are they not adhering to?

**Comment by AudriusButkevicius** [comment]
If you read specs of upnp.org for BasicDevice it says the UDN field is supposed to be a UUID, and references the spec of UUIDs.

**Comment by silversword411** [comment]
Perfect thanks! I'll forward the info :)
