### ISSUE TITLE
Sharing Folders via Device menu not syncing with folder itself

### ISSUE THREAD

**Issue by snpalavan** [syncthing/syncthing#3120]
Interesting issue I just noticed.  There are two ways of sharing a folder with a device:  1) by editing the folder and selecting the device OR 2) editing the device and selecting the folder.

Method 1 works fine, the folder is shared and the list of shared folders shows up in the list on the device menu.  However, Method 2 does not work.  In fact, the folders that have been shared via Method 1 do not show up as selected in the device menu.  See this image:  https://imgur.com/TpKo87j

Further, when folders are added via Method 2, they do not update in the list.  I selected all of the folders to share via the device menu and there is no update.  See this image:  https://imgur.com/TpKo87j

Thus, there appears to be a syncing issue between folders shared and the device menu folder selection.

-Shea

Syncthing Version: v0.13.1
OS Version: Windows 10
Browser Version: Internet Explorer 11 (11.1000.14342.0) and Firefox 44.0.2

**Comment by canton7** [comment]
What Syncthing version does this apply to?

**Comment by AudriusButkevicius** [comment]
Hi,

The issue template is there for a reason, please fill stuff up as requested.

**Comment by snpalavan** [comment]
Whoops, apologies!  Forgot I deleted that part and forgot to put it back - original comment updated.

**Comment by calmh** [comment]
I can't reproduce this in current master, but I know there was some confusion around IDs and labels on these checkboxes at some point. Regarding as solved.
