### ISSUE TITLE
Include tray application

### ISSUE THREAD

**Issue by erikvanoosten** [syncthing/syncthing#3123]
https://github.com/sieren/QSyncthingTray contains a pretty good cross platform tray application. It can even properly install syncthing for you.

Please consider making QSyncthingTray (or an alternative tray app) part of the standard download.

Rationale: Having a friendly UI for syncthing can greatly expand the number of people that can use it.

**Comment by canton7** [comment]
There is an ongoing conversation about making a better downloads page, and promoting the major tray applications for different platforms. The forum is the right place to have this discussion.

**Comment by AudriusButkevicius** [comment]
Yet the list of supported architectures/OS'es is less than what we support.

**Comment by erikvanoosten** [comment]
Okay, if there is already an ongoing discussions then there is no need for this issue. Thanks!
