### ISSUE TITLE
Separate BlockInfo from FileInfo

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#3127]
Quite often we load the whole block list, even though we only need metadata about the file.
Yeah, FileInfoTruncated somewhat helps, but the value that gets loaded from the db still holds all blocks.

Or.... we move to variable block sizes so that this becomes less painful.

**Comment by calmh** [comment]
We can even do both. I was playing earlier with using unique ids for files, I.e not storing the fileinfo for every remote device but just an int64 identifying the file+version and then having that map to the actual file info. There was some issue...

But we could certainly store fileinfo a without block list and have a separate table for blockinfos, indexed on file+version. We will need reference counting or garbage collection or something to clean it out.

**Comment by AudriusButkevicius** [comment]
Why?

I'd think that it works the same way like now, when we set deleted flag, we delete the key from the database?

**Comment by calmh** [comment]
I was thinking we have file F version 42 in five places (local plus four remotes), all pointing to the same block list. When everyone is on F version 43 we will have updated all fileinfos but may still have the blocks laying around for F v42. Hence needing to ref count the block list, or store it once per device as for the fileinfos currently.

**Comment by AudriusButkevicius** [comment]
Thats actually quite clever.

**Comment by imsodin** [comment]
Fixed by https://github.com/syncthing/syncthing/pull/6283
