### ISSUE TITLE
Consider making folder IDs case insensitive

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#3128]
Casing is annoying when you're trying to copy a folder ID from one machine to another. We probably don't need case sensitivity for entropy reasons, so it might be worth making them case insensitive.

Some thoughts:

 - By default suggest an all-upper or all-lower-case folder ID, but still treat them as case sensitive.
 - Treat them as case insensitive when loading them (similar to device IDs)

**Comment by calmh** [comment]
> suggest an all-upper or all-lower-case folder ID, but still treat them as case sensitive

We should do that

**Comment by xor-gate** [comment]
I agree, they are unique anyway in both lower/upper and mixed case.
