### ISSUE TITLE
Error compiling in Centos7

### ISSUE THREAD

**Issue by daniel-lucio** [syncthing/syncthing#3131]
+ go run build.go -version 0.13.1 -no-upgrade -goarch amd64
GOPATH is /builddir/build/BUILD/syncthing-0.13.1
*** Go version 1.4 doesn't support the vendoring mechanism.
*** Ensure correct dependencies in your $GOPATH.
go run script/genassets.go gui > lib/auto/gui.files.go

Not a GO expert, what should I do?

**Comment by AudriusButkevicius** [comment]
It's explained in the error message: `Go version 1.4 doesn't support the vendoring mechanism.`
Upgrade to Go 1.6.

**Comment by daniel-lucio** [comment]
I was thinking there could be an optional patch.

It compiles in go 1.5. Strange, EPEL for Centos6 has go 1.5, but Centos7 go 1.4. I am porting forward go.

**Comment by AudriusButkevicius** [comment]
Go 1.5 works too.
Compiling with Go 1.4 needs setting up GOPATH to point at the vendor directory potentially (or copying stuff around).

**Comment by AudriusButkevicius** [comment]
Ideally you should compile with 1.6+, as there has been security fixes and many crypto improvements and so on, which you will miss out on.

**Comment by lkwg82** [comment]
Just a question, I remember there is a build to check compatibility with go 1.3 why?

**Comment by calmh** [comment]
Because 1.2 and earlier will fail with mysterious error messages, while the build script explains why instead. 

You may think go 1.2 sounds quaint but remember syncthing started life on go 1.1 and that check was added when we changed to require 1.3.
