### ISSUE TITLE
gui: CSRF/CORS preventing initial ajax calls (403 Forbidden)

### ISSUE THREAD

**Issue by norgeous** [syncthing/syncthing#3138]
in v0.13.2, I see this in the web page console (firefox)

![untitled](https://cloud.githubusercontent.com/assets/4681349/15449227/999a4592-1f6f-11e6-88d6-b4124147f89b.png)

`http://localhost:8384/rest/svc/lang`
`http://localhost:8384/rest/events?limit=1`
`http://localhost:8384/rest/system/browse?`

these `GET` requests are returning `403 Forbidden` with content `CSRF Error`. It happens fairly early on (soon after page refresh) so maybe they are calling before the API Key or CSRF token is setup? Subsequent calls to the same endpoints return `200 OK`.

It does not affect any function, everything looks like it still works - having briefly checked the language selector and folder browser suggestion thing (which i believe are related) and they function properly.

**Comment by calmh** [comment]
I think that first `lang` call may break language auto detection based on browser headers.

**Comment by Allaman** [comment]
Hello,
Are there any news? I am having a similar issue with the difference that all requests after login don't work. This means that the Web UI is not usable.

![selection_001](https://cloud.githubusercontent.com/assets/12184268/18218303/184e02fe-7162-11e6-9865-372361e0ee38.png)


I am running syncthing behind an apache proxy (a setup which used to work a while ago, dunno how long its not working anymore).

**System**
Debian 8 64bit
syncthing v0.14.5 "Dysprosium Dragonfly" (go1.7 linux-amd64) jenkins@build.syncthing.net 2016-08-23 08:42:09 UTC

**apache** 
```
<VirtualHost *:80>
        ServerName syncthing.domain.net 
        Redirect permanent / https://syncthing.domain.net
</VirtualHost>

<VirtualHost *:443>
        ServerName syncthing.domain.net

        SSLEngine on
        SSLCertificateFile     /...
        SSLCertificateKeyFile  /...

        ProxyPass / http://127.0.0.1:8384/ connectiontimeout=300 timeout=300
        ProxyPassReverse / http://127.0.0.1:8384/

        CustomLog /var/log/apache2/syncthing-access.log combined
        ErrorLog /var/log/apache2/syncthing-error.log

</VirtualHost>
```
**syncthing config**
```
<gui enabled="true" tls="false" debugging="false">
        <address>127.0.0.1:8384</address>
        <user>knecht</user>
        <password>....</password>
        <apikey>....</apikey>
        <theme>dark</theme>
</gui>
```

**Comment by calmh** [comment]
The ticket you're responding to was resolved ages ago. If you have an issue, I recommend first seeking help on the forum and if it's confirmed to be a big open a new ticket here.
