### ISSUE TITLE
Date and time of last scan

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#3143]
Sometimes it would be helpful to display date/time of last scan of each folder, especially if you have lots of data and long scan intervals

**Comment by calmh** [comment]
Reasonable

**Comment by majedev** [comment]
LGTM. I'm not fully familiar with the inner workings of syncthing, so thinking about storing last scan times right before `runner.setState(FolderIdle)` call in `model.go` (specifically, [here](https://github.com/syncthing/syncthing/blob/fc173bf679dbe4058c9a695933b13e7fd95af511/lib/model/model.go#L1605) and [here](https://github.com/syncthing/syncthing/blob/fc173bf679dbe4058c9a695933b13e7fd95af511/lib/model/model.go#L1752)). Let me know if that works.

**Comment by AudriusButkevicius** [comment]
I think its only the first case, the second case is there probably just to indicate that some work is happening, but is more of a reconcile than a scan.
