### ISSUE TITLE
New folder/device web message missing info

### ISSUE THREAD

**Issue by markwmuller** [syncthing/syncthing#3151]
I've just updated to 13.2, and the Web UI doesn't show me the correct info if I'm trying to add a device / folder. The output in the terminal seems OK though, so it's probably just not being parsed correctly. 
In the web interface I get the following message: 

{%device%} wants to share folder "{%folder%}". Add new folder?

In the terminal, instead, I get (where I've replaced any private info with "_redacted_": 
[_redacted_] 10:57:46 INFO: Unexpected folder ID "_redacted_" sent from device "_redacted_"; ensure that the folder exists and that this device is selected under "Share With" in the folder configuration.

Syncthing Version: syncthing v0.13.2 "Copper Cockroach" (go1.6.2 linux-amd64)
OS Version: Ubuntu 14.04, 64 bit
Browser Version: Firefox 46.0.1

Thanks for the great software!

**Comment by AudriusButkevicius** [comment]
Check javascript logs for errors.
Also if it's the first startup after upgrading to 0.13, the db migration can take a while causing this

**Comment by markwmuller** [comment]
I opened "Browser Console", and these are the JS entries:

no element found 1198:1:1
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:3:6598
TypeError: this.transport is null main.js:1391:5
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. 127.0.0.1:8080

I've restarted syncthing, am still seeing it.

**Comment by AudriusButkevicius** [comment]
What browser are you using?

**Comment by markwmuller** [comment]
Firefox 46.0.1, on Ubuntu 14.04, 64 bit

**Comment by AudriusButkevicius** [comment]
Right, please provide screenshot of the browser console.

**Comment by markwmuller** [comment]
![screenshot from 2016-05-22 11 28 46](https://cloud.githubusercontent.com/assets/3056063/15453278/65fff35c-2010-11e6-8136-8711031fe6c9.png)

Only showing JS

**Comment by AudriusButkevicius** [comment]
Can you check if this does this happen with 0.13.1?
We had a security fix in 0.13.2, so just want to make sure it's not that that's causing this.

**Comment by markwmuller** [comment]
OK, I downgraded to 0.13.1, and the problem is no longer there (folder & device names read OK). I still see the same message in the browser console.

**Comment by AudriusButkevicius** [comment]
0.13.1 has a security vulnerability, so I don't recommend running it.

The messages don't mean much, yet I am surprised there are no extra messages in 0.13.2

**Comment by AudriusButkevicius** [comment]
I feel this is related to and caused by #3138

**Comment by AudriusButkevicius** [comment]
Is the variable expansion only present in the prompt dialog or anywhere else?

**Comment by markwmuller** [comment]
I'm not sure I follow the question. Everything else looks OK in the interface (specifically, list of folders & list of remote devices).

**Comment by markwmuller** [comment]
As an aside, it's happening on all my devices, including win 8.1, and a raspberry pi (with remote GUI access). All PCs run latest firefox though.

**Comment by AudriusButkevicius** [comment]
Yeah I think it will be related to the issue I've referenced, given it's not broken in 0.13.1

**Comment by calmh** [comment]
> {%device%} wants to share folder "{%folder%}"

This is #3138, yes 

> no element found 1198:1:1
> Use of getPreventDefault() is deprecated. Use defaultPrevented instead. jquery.min.js:3:6598
> TypeError: this.transport is null main.js:1391:5
> Use of getPreventDefault() is deprecated. Use defaultPrevented instead. 127.0.0.1:8080

Don't recognize these though

**Comment by AudriusButkevicius** [comment]
This is just random "oh you are using old javascript api" bullshit from the browsers.

**Comment by markwmuller** [comment]
I just tested, and I get the same in Chrome (50.0.2661.102 m (64 bit)), on Windows 8.1 (64 bit)

**Comment by 3v1n0** [comment]
I'm getting the same between two syncthing 0.13.2 instances running in Linnux (ARM and x86_64).
