### ISSUE TITLE
GTK-v.0.9.0.1 - RunDLL message 

### ISSUE THREAD

**Issue by rbon44** [syncthing/syncthing#3153]
Installed syncthing-GTK  the full installer version: v0.9.0.1-win32 on two windows 10 boxes.
One box installed fine, the other during the install popped up a message box:
Title bar:  RUNDLL
There is a problem starting D:\Program
The specified module cannot be found.

The install completed and the app does run and work, but every time it is started it generates the same message box.

On both PCs the location I specified for the install was my 2nd SATA drive by substituting the appropriate drive letter in place of the standard C: in the dialog window and agreeing to creation of the new folder at that location.

I did uninstall and cleaned the registry, rebooted and retried the install with the exact same results both during the install and when running the app.  Would there be a particular log file that might help in troubleshooting this?  What other info would be helpful?

**Comment by AudriusButkevicius** [comment]
Wrong repo.

**Comment by uok** [comment]
Please check https://github.com/syncthing/syncthing-gtk

**Comment by calmh** [comment]
The right one being https://github.com/syncthing/syncthing-gtk/issues :)
