### ISSUE TITLE
Missing device name, folder name etc on the "Share Folder" dialogue

### ISSUE THREAD

**Issue by cbhushan** [syncthing/syncthing#3154]
I have started noticing this since v0.13.x upgrade. See the screenshot below. Basically whenever I add a new folder to one computer and share it to another trusted computer, syncthing shows a notification on the another computer to accept/share/add the connection. The details of names are missing on the notification -- most likely some string manipulation glitch. I have seen it on v0.13.2, Linux (ARM) and v0.13.2, Linux (64 bit).

![aab](https://cloud.githubusercontent.com/assets/3436053/15454281/644d594a-2002-11e6-9bb9-eff1fe73c484.png)

**Comment by AudriusButkevicius** [comment]
Dup of an already closed issue.
