### ISSUE TITLE
Expected behavior of the ignore pattern "dir/"?

### ISSUE THREAD

**Issue by favonia** [syncthing/syncthing#3155]
Syncthing Version: v0.13.2
OS Version: Arch Linux

I am not sure whether this is a bug or an intentional change, but I am reporting it anyways. In Syncthing 0.12 I discovered I could use
```
!/dir/file
/dir/
!/dir
```
to sync only ``/dir/file``. Now in 0.13 the files under ``/dir/`` do not seem to match the ``/dir/`` rule, and so I have to use the following instead:
```
!/dir/file
/dir/*
!/dir
```
The documentation is currently unclear about what would happen when a rule ends with ``/``.

**Comment by calmh** [comment]
I think the previous behavior was a bug or corner case and the current one is correct. `/dir` and `/dir/` should be equivalent, both matching the directory itself. Your latest set of patterns is more clear about the intention as well.

**Comment by favonia** [comment]
I agree the current one is arguably better. :thumbsup:

If the third line was missing, according to the documentation and my experiments against 0.12, Syncthing would not recurse into the directory and would not know the existence of ``/dir/file`` from the beginning, not to mention syncing it. Things might have changed in 0.13 but I do not know.

**Comment by calmh** [comment]
That would be the case indeed if "dir" is ignored, but with your latest iteration only the files inside it are.

**Comment by favonia** [comment]
You are right, but I have ``/*`` in the end, so it is still needed in my case.

Please feel free to close this issue if you feel there is no need to update the code or the documentation. I am merely reporting my observation that does not seem to be documented in the release notes.
