### ISSUE TITLE
Can't sync from Mac to Linux after upgrading to 0.13.x

### ISSUE THREAD

**Issue by gunwald** [syncthing/syncthing#3156]
### What happened
I upgraded my cluster to 0.13.2. It contains several Linux machines (Debian Jessie, and Ubuntu 16.04) and one Mac OS X machine.
Since then the latter can connect to all Linux machines, but can't sync. The progress bar gets stuck at 0%. All Linux machines do sync between each other as expected. 
I tired to delete the Mac OS X machine on all other devices and readded it later. But this didn't help. I reinstalled Syncthing on the Mac OS X machine, but still does not work

### Version Information

Syncthing Version: v0.13.2
OS Version: Ubuntu 16.04 / Debian Jessie / OS X 10.11.5

**Comment by AudriusButkevicius** [comment]
Read what the ticket template says:

```
f your issue is a support request ("How do I get my devices to connect?"
or similar), please use the support forum at https://forum.syncthing.net/
where a large number of helpful people hang out. This issue tracker is for
reporting bugs or feature requests directly to the developers.
```
