### ISSUE TITLE
Interface infelicity - which device is syncing?

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [syncthing/syncthing#3158]
[I am told by canton7 on the SyncTrayzor bugtracker that the following report of mine belongs here on this tracker.]

The attached screenshot shows, I think, that it's not always as clear as it should be which devices is syncing. (The red scribbles in the screenshot are for purposes of redacting personal information.)

![untitled](https://cloud.githubusercontent.com/assets/9998846/15455961/5cad5430-205a-11e6-879b-b8b79a88895b.png)

### Version Information

Syncthing Version: v0.13.2, Windows (64 bit)
OS Version: Windows 8.1

**Comment by AudriusButkevicius** [comment]
It's totally clear, it's the device with the blacked out name.

**Comment by ACinnamonUserInUK** [comment]
Thanks for your comment. To which my response is: well, if you think so. Myself, I'd add a bit more space between the two device panels.

**Comment by AudriusButkevicius** [comment]
Well it says "Syncting" in the status message, so I don't think it can be even more clear than that?
The space won't make you read the text if you choose not to?

**Comment by calmh** [comment]
Many parts of our UI has confused people, but this is the first I've heard of this particular confusion in the years it's been like this, so I'm tending to agree that this is as non-confusing as it needs to be at the moment.
