### ISSUE TITLE
{%device%} wants to share folder "{%folderlabel%}"

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [syncthing/syncthing#3161]
Something seems to have gone wrong here. 

![screenshot-area-2016-05-23-013236](https://cloud.githubusercontent.com/assets/9998846/15457742/f49a42a4-2086-11e6-9912-199da2b1f29b.png)

Syncthing Version: v0.13.2, Linux (64 bit)
OS Version: Mint 17.3
Browser Version: Firefox 46.0.1.

**Comment by calmh** [comment]
Yes, fixed in next release. #3138
