### ISSUE TITLE
{%device%} wants to share folder...

### ISSUE THREAD

**Issue by meztup** [syncthing/syncthing#3162]
When adding a new folder on one device, and selecting a second device to sync with, the prompt displayed in the second device contains untranslated variable placeholders.

{%device%} wants to share folder "{%folderlabel%}" ({%folder%})...

As you can see, the data is there in an attribute on the span--it's just not making it into the display text.

![untitled2](https://cloud.githubusercontent.com/assets/16569239/15461035/c145efde-207c-11e6-9274-5910d16bbce6.png)

### Version Information

Syncthing Version: v0.13.2
OS Version: Windows 7 x64
Browser Version: Both IE11 & Firefox 46.0.1

**Comment by AudriusButkevicius** [comment]
Please check closed issues.

**Comment by uok** [comment]
@meztup this will be fixed in next release (#3161, #3138)
