### ISSUE TITLE
The (?d) prefix on an ignored directory should delete directory contents

### ISSUE THREAD

**Issue by Tstassin** [syncthing/syncthing#3164]
Follow-up to [this](https://forum.syncthing.net/t/ignoring-d-prefix-eadir-folder/7437), have been asked by @AudriusButkevicius to raise an issue

---

Devices : 3 Synology NAS DS215j
Running Syncthing v0.13.2
Sharing a big folder of media files

Each subfolder containing one or more media files contains one hidden folder `@eaDir` containing subfolders and temporary files.

    BIGFOLDER\
    BIGFOLDER\SOME_MEDIA\
    BIGFOLDER\SOME_MEDIA\MEDIA_FILE.EXT
    BIGFOLDER\SOME_MEDIA\@eaDir\Random_temp_file.ext
    BIGFOLDER\SOME_MEDIA\@eaDir\Random_temp_subfolder\
    BIGFOLDER\SOME_MEDIA\@eaDir\Randem_temp_subfolder\Random_temp_file.ext

At the moment, .stignore contains on each node :
 
    (?d)@eaDir 

If I remove the `SOME_MEDIA` folder on one node, the other nodes display :

`[REDACTED] 10:52:45 INFO: Puller (folder "BIGFOLDER", dir "SOME_MEDIA"): delete: remove /volume/BIGFOLDER/SOME_MEDIA: directory not empty`

I thought that prefixing `@eaDir` with `(?d)` would allow deletion, but it doesn't seem to work.

I tried the `(?d)@eaDir/**` pattern too, but it doesn't seem to work too.

Any ideas on how to handle deletion of those ignored `@eaDir` subdirectories and their respective content when deleting directories ?

I can provide much more details if needed.

**Comment by Tstassin** [comment]
Here is the ignore file content, this file is synchronised by syncthing itself across devices and included in .stignore 

```
// Firefox downloads and other things
(?d)*.part
// Chrom(ium|e) downloads
(?d)*.crdownload

// Temporary / Backup Files
(?d)*~
(?d).*.swp

// OS-generated files (OS X)
(?d).DS_Store
(?d).Spotlight-V100
(?d).Trashes
(?d)._*

// OS-generated files (Windows)
(?d)desktop.ini
(?d)ehthumbs.db
(?d)Thumbs.db

// OS-generated files (UNIX)
(?d).directory
(?d).Trash-*


// BTSync files
(?d).sync
(?d)*.bts
(?d)*.!Sync
(?d).SyncID
(?d).SyncIgnore
(?d).SyncArchive
(?d)*.SyncPart
(?d)*.SyncTemp
(?d)*.SyncOld

// Synology files
(?d)@eaDir/**
```

Here is the output of 
`curl -H X-API-Key:MYAPIKEYREDACTED -s 'http://localhost:7070/rest/db/ignores?folder=BIGFOLDER' | python -mjson.tool `

```
{
    "expanded": [
        "(?d)(?d)*.part",
        "(?d)**/*.part",
        "(?d)(?d)*.part/**",
        "(?d)**/*.part/**",
        "(?d)(?d)*.crdownload",
        "(?d)**/*.crdownload",
        "(?d)(?d)*.crdownload/**",
        "(?d)**/*.crdownload/**",
        "(?d)(?d)*~",
        "(?d)**/*~",
        "(?d)(?d)*~/**",
        "(?d)**/*~/**",
        "(?d)(?d).*.swp",
        "(?d)**/.*.swp",
        "(?d)(?d).*.swp/**",
        "(?d)**/.*.swp/**",
        "(?d)(?d).DS_Store",
        "(?d)**/.DS_Store",
        "(?d)(?d).DS_Store/**",
        "(?d)**/.DS_Store/**",
        "(?d)(?d).Spotlight-V100",
        "(?d)**/.Spotlight-V100",
        "(?d)(?d).Spotlight-V100/**",
        "(?d)**/.Spotlight-V100/**",
        "(?d)(?d).Trashes",
        "(?d)**/.Trashes",
        "(?d)(?d).Trashes/**",
        "(?d)**/.Trashes/**",
        "(?d)(?d)._*",
        "(?d)**/._*",
        "(?d)(?d)._*/**",
        "(?d)**/._*/**",
        "(?d)(?d)desktop.ini",
        "(?d)**/desktop.ini",
        "(?d)(?d)desktop.ini/**",
        "(?d)**/desktop.ini/**",
        "(?d)(?d)ehthumbs.db",
        "(?d)**/ehthumbs.db",
        "(?d)(?d)ehthumbs.db/**",
        "(?d)**/ehthumbs.db/**",
        "(?d)(?d)Thumbs.db",
        "(?d)**/Thumbs.db",
        "(?d)(?d)Thumbs.db/**",
        "(?d)**/Thumbs.db/**",
        "(?d)(?d).directory",
        "(?d)**/.directory",
        "(?d)(?d).directory/**",
        "(?d)**/.directory/**",
        "(?d)(?d).Trash-*",
        "(?d)**/.Trash-*",
        "(?d)(?d).Trash-*/**",
        "(?d)**/.Trash-*/**",
        "(?d)(?d).sync",
        "(?d)**/.sync",
        "(?d)(?d).sync/**",
        "(?d)**/.sync/**",
        "(?d)(?d)*.bts",
        "(?d)**/*.bts",
        "(?d)(?d)*.bts/**",
        "(?d)**/*.bts/**",
        "(?d)(?d)*.!Sync",
        "(?d)**/*.!Sync",
        "(?d)(?d)*.!Sync/**",
        "(?d)**/*.!Sync/**",
        "(?d)(?d).SyncID",
        "(?d)**/.SyncID",
        "(?d)(?d).SyncID/**",
        "(?d)**/.SyncID/**",
        "(?d)(?d).SyncIgnore",
        "(?d)**/.SyncIgnore",
        "(?d)(?d).SyncIgnore/**",
        "(?d)**/.SyncIgnore/**",
        "(?d)(?d).SyncArchive",
        "(?d)**/.SyncArchive",
        "(?d)(?d).SyncArchive/**",
        "(?d)**/.SyncArchive/**",
        "(?d)(?d)*.SyncPart",
        "(?d)**/*.SyncPart",
        "(?d)(?d)*.SyncPart/**",
        "(?d)**/*.SyncPart/**",
        "(?d)(?d)*.SyncTemp",
        "(?d)**/*.SyncTemp",
        "(?d)(?d)*.SyncTemp/**",
        "(?d)**/*.SyncTemp/**",
        "(?d)(?d)*.SyncOld",
        "(?d)**/*.SyncOld",
        "(?d)(?d)*.SyncOld/**",
        "(?d)**/*.SyncOld/**",
        "(?d)(?d)@eaDir/**",
        "(?d)**/@eaDir/**"
    ],
    "ignore": [
        "#include SyncthingIgnore.txt"
    ]
}
```

**Comment by calmh** [comment]
This does not look correct, so I suspect there is a genuine bug here somewhere:

```
"expanded": [
        "(?d)(?d)*.part",
```

**Comment by AudriusButkevicius** [comment]
Yes, but we should also deal with removal of ignired directories with content in them.

**Comment by Tstassin** [comment]
@AudriusButkevicius but by writing `(?d)folder/**`doesn't it mean "can erase all content in `folder` ?

**Comment by AudriusButkevicius** [comment]
It should but it doesn't, hence this ticket.

**Comment by Tstassin** [comment]
@AudriusButkevicius I updated to v0.13.4, restarted, but sadly problem still happening.
Empty directory except for one ignored and deletable subdirectory still reports as unremovable because directory not empty.

I can provide you much more details if needed

**Comment by AudriusButkevicius** [comment]
Yep, found a small oversight.
