### ISSUE TITLE
Syncthing uses incorrect timezone for Last-Modified header

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#3165]
Syncthing sets the Last-Modified header on static assets to the time at which the config was last committed. However, it sets a local time, whereas the docs for `http.TimeFormat` specify that the time must be UTC.

This can result in a Last-Modified time in the future for timezones ahead of GMT, or a time before the config was committed for timezones behind GMT.

This is probably partially responsible for the reports of the UI showing "Unknown Device" with an empty folder list when people upgrade to 0.13. I say "partially" because I know there have been reports from people ahead of GMT, so something else is at play as well here....

See [here](https://github.com/syncthing/syncthing/blob/4bc2b3f3690c755a8ffb22862915e286bdc24702/cmd/syncthing/gui.go#L1257), [here](https://github.com/syncthing/syncthing/blob/4bc2b3f3690c755a8ffb22862915e286bdc24702/cmd/syncthing/gui.go#L1300), and [here](https://github.com/syncthing/syncthing/blob/4bc2b3f3690c755a8ffb22862915e286bdc24702/cmd/syncthing/gui.go#L301).

**Comment by calmh** [comment]
Need to add a UTC() call there, yes.
