### ISSUE TITLE
After updating to version 0.13.0, CPU usage increased significantly

### ISSUE THREAD

**Issue by mateusz-gozdek-sociomantic** [syncthing/syncthing#3166]
### What happened
After updating from version `0.12.24` to `0.13.0` I noticed, that CPU usage increase significantly. On version `0.12.24` it was about `~3%` and now it's `8%`. Also, number of context switches grown from `~1500` to `~3500`. I noticed this same behaviour on all my machines.

Interesting fact is, that memory usage decreased for about `50%`.

### Version Information
Syncthing Version: v0.13.2
OS Version: Ubuntu 14.04

**Comment by calmh** [comment]
While doing what - scanning? Do you have ignores?

**Comment by mateusz-gozdek-sociomantic** [comment]
I have a line to ignore one directory only. Looks like size of this directory doesn't matter, because it's different for each machine.

I also noticed from GUI now, that scanning of this directory is taking longer than before.

**Comment by calmh** [comment]
Could be the disabling of the ignore caching. Enable that in advanced config or the config.xml and see if it reverses the tradeoff.

**Comment by mateusz-gozdek-sociomantic** [comment]
You mean `cacheIgnoredFiles`?

**Comment by mateusz-gozdek-sociomantic** [comment]
I enabled it, let see if this help. I don't know if it's related, but request to `rest/events?since=2116113` returns 3MB of data. And it's called every few seconds, which generates pretty big network traffic. Is that correct behaviour?

**Comment by calmh** [comment]
It sounds like syncthing is generating a holyfuckload of events, which is probably not normal nor correct, no. Anything interesting in the logs?

**Comment by mateusz-gozdek-sociomantic** [comment]
It looks like, there is a huge amount of `LocalIndexUpdated` events for this ignored folder. And it's probably caused, because there is a lot of files `~350k` on one machine and even more on others. I also had a problem with initial indexing with that directory, but after some time, it stabilized.

**Comment by mateusz-gozdek-sociomantic** [comment]
As a quick fix, I can try to manually select subdirectories to sync instead of defining parent directory with ignore. But it's not a solution for an issue.

**Comment by calmh** [comment]
Those events mean some files were changed locally, due to them being synced or changed outside of syncthing. CPU usage makes sense in that context.

**Comment by mateusz-gozdek-sociomantic** [comment]
They might be changed locally, because it's cache directory. But anyway, shouldn't `syncthing` skip it from even indexing if it's marked to ignore?

Another thing is, that in version `v0.12.24` CPU usage was much lower in same configuration, so there is still some problem.

**Comment by canton7** [comment]
Sounds like Syncthing 0.12 thought you were ignoring the cache folder, and never scanned it. Syncthing 0.13 doesn't think you are (for some reason), so keep scanning it...

The ignores system did change between 0.12 and 0.13. What ignores do you have set up? Can you paste them?

**Comment by mateusz-gozdek-sociomantic** [comment]
It's just nginx cache directory, and `.stignore` file is:
```
cache
```

**Comment by mateusz-gozdek-sociomantic** [comment]
But as I said, when I started using syncthing, it was `0.12.2x` and initial sync took very very long. It creates database file of size about 2Gb and then removes it IIRC. And it happened few times. After that, database file is about 90 Mb and it was OK.

**Comment by AudriusButkevicius** [comment]
Are you using inotify?

**Comment by mateusz-gozdek-sociomantic** [comment]
No, I am not using `inotify`.

**Comment by AudriusButkevicius** [comment]
Did you try the ignore cache?

**Comment by mateusz-gozdek-sociomantic** [comment]
Yes, I got memory usage jump, and CPU usage remained the same.

**Comment by calmh** [comment]
Can't reproduce and haven't heard other reports of it. Any clear reproducer for this?

**Comment by mateusz-gozdek-sociomantic** [comment]
I made a workaround by adding subdirectory instead of main folder + ignore.

I think you should be able to reproduce it by creating a subdirectory with large number of files, which are constantly updated, adding this subdirectory to ignore list and that's it.

In my opinion ignored files shouldn't be indexed and scanned for changes at all. This would fix CPU usage and large number of events.

**Comment by calmh** [comment]
> In my opinion ignored files shouldn't be indexed and scanned for changes at all

Indeed they aren't, if they are in an ignored directory. But I'll try your setup and see what it says.

One question though: were these files at some point not-ignored, so that they might have been added to the index? There could possibly be a corner case there, which I might also have solved recently.

**Comment by mateusz-gozdek-sociomantic** [comment]
Hmm, IIRC, it might be, that I added a directory to Syncthing first, and after I notice, that indexing is taking so long, I added ignore rule. But I'm not 100% sure.

**Comment by calmh** [comment]
Not nailed down, not widely reported, tricky to get to the bottom of - sorry.
