### ISSUE TITLE
Add message when incompatible syncthing version hosts are found in the cluster

### ISSUE THREAD

**Issue by Dolganoff** [syncthing/syncthing#3168]
Hello,

As I've learned from the experience , the v13 hosts will not connect to v12 hosts and vice versa. Granted, this information exists somewhere in the docs on the site, however for both version's clients, nothing of the sorts  is found in the logs or GUI messages when, say, v13 client tries to connect to v12: they will just be shown as "disconnected" without any info hinting at the version mismatch. 

It could be of great use if such message was clearly presented to the user, at least in the log (even better in the GUI).

Another thing to consider is to not let the automatic upgrade proceed as soon as incompatible version change is expected, but still let it roll if there's none.

Regards.

### Version Information
Syncthing Version: v13 and v12
OS Version: Windows 7 , Ubuntu 14.04, ubuntu 16.4

**Comment by AudriusButkevicius** [comment]
Incompatible versions by default shouldn't even be able to discover each other (unless you configure addresses directly), so there is no way to know if there are incompatible versions in the cluster.

Automatic upgrades do not automatically upgrade you to an incompatible version, and you have to explicitly preas the red button in the web ui for that to happen. It also tells you that it's incompatible at that point.

**Comment by Dolganoff** [comment]
"shouldn't even be able to discover each other": maybe let them discover each other and detect the version diff then? The current behavior is really not helpful when dealing with hosts not connecting.

**Comment by Dolganoff** [comment]
ok for the "red button", I see there is a message there.

**Comment by AudriusButkevicius** [comment]
We can't let them discover, because the discovery protocol is incompatible.

**Comment by Dolganoff** [comment]
Sorry, but that is bad user interaction design decision... a very important roadblock is not at all communicated to the user through the GUI or the logs. Maybe something to take into account for the future incompatible releases? 

By the way, the message may be made more explicit too, currently it says "A new major version **may not be** compatible with previous versions"

You know for sure it will not be compatible between current (v12) and new (v13), so "may be incompatible" is a bit to weak a message I believe.

Regards

**Comment by AudriusButkevicius** [comment]
So we warn you when you upgrade, it's also in the release notes, forum and all other possible channels, so "not communicated" is a bald statement. I can't help if the user chooses not to read anything that we throw at him.

**Comment by calmh** [comment]
On a different note, the mechanism for doing exactly this was implemented in v0.13 (by none other than Audrius), but it's not spoken by v0.12. v0.13 to v0.14, when that happens *should* have this feature.

**Comment by AudriusButkevicius** [comment]
Subject discovery doesn't change again...

**Comment by Dolganoff** [comment]
Maybe this will work even if the discovery is impossible: 
Store in the config.xml the last device version along with the "id" and "name" properties. Make it read-only in the GUI/API.  Then after the upgrade the client could see the last version isn't the current one and send a warning.

**Comment by calmh** [comment]
Of course discovery will change, so we will get the usual "my device doesn't connect any more 😢" but that's not the point. :) For those that *do* connect, we should be able to actually say "Syncthing v0.13.47 not support - must upgrade to 0.14!".

**Comment by Dolganoff** [comment]
But this will do not work for the devices never connecting directly but joining exclusively through relays, right?  I think storing the "last seen" version could resolve both cases?

**Comment by Dolganoff** [comment]
Thinking about it, the "last seen" may not be the right version anymore, because that device may be already upgraded in the meantime...

**Comment by calmh** [comment]
By itself it works fine through relays, but relays are another question. And this isn't the forum for it. :)

**Comment by Dolganoff** [comment]
The ideal situation would be version-agnostic discovery when the devices with incompatible versions could at least be able to say each other "you're of the wrong version". Just showing "disconnected" isn't saying the truth, really.

**Comment by calmh** [comment]
Agreed. And at some point, we'll be there.
