### ISSUE TITLE
Missing interface features when creating a shared folder.

### ISSUE THREAD

**Issue by user514** [syncthing/syncthing#3169]
I'm missing some things from the first day I installed Syncthing. Really small improvements but important in my opinion.

  The order of fields and features of fields when entering a new shared folder, right now are like that:

1-FOLDER LABEL (you have to enter it manually and/or copypaste it from 3rd field)
2-FOLDER ID (could keep being automatic, you don't have to worry about it I think)
3-FOLDER PATH (you have to enter manually the full path. I know popup some options while you are typing the correct path, but...)

I think it will be much easier to enter a new folder as:

1-FOLDER PATH [BROWSE...]. In which you can enter a path manually or use the browse button and select it. Of course, when you enter browse you should fall into the 'Default path' feature commented at  issue #2157. For sure almost all of us have a SYNCTHINGshares (or whatever) folder in which we first create our new folder and copy things in, and then we jump to the web browser to share it. Falling directly into our SYNCTHINGshares, will be great.

2-FOLDER LABEL. It should be taken automatically right after you have selected the folder path, just by adding the folder name as the 'folder label' here. For example with the sample above SYNCTHINGshares\MyMusic, 'MyMusic' should be the auto-proposal of syncthing when filling the 'folder label' field. 99% times user will left folder label with that name.

3-FOLDER ID. This could be even greyed out and not editable, almost transparent for the final user, first time I enter a folder I didn't know if I should change the given name or not or what.

**Comment by canton7** [comment]
1. Browse buttons in web apps are somewhat hard to do: you need to create your own browser UI. There's probably something out there that we can steal and customise, but it's a not insignificant amount of work. Tools like SyncTrayzor also provide a proper browse button here.
2. Agreed. However the fact that the "Folder Label" box comes before the path box means that most people will probably fill it out first, and so will never see the auto-populating behaviour.
3. This absolutely needs to be editable, so that you can add a folder which exists on other devices (as opposed to creating a new folder). There may be a better flow here, where we have buttons for "Add Existing Folder" and "Add New Folder". Agreed that the wordage around it needs to be better.

**Comment by user514** [comment]
@canton7 
> (1). Browse buttons in web apps are somewhat hard to do

Ok, I'm not a developer, so don't know how hard it is to implement a certain feature. I thought the browse button would be easier to implement. Anyway, just mentioning...

> (2). Agreed. However the fact that the "Folder Label" box comes
> before the path box means that most people will probably fill it
> out first, and so will never see the auto-populating behaviour.

  ...that's why I swap 3 for 1 in my list of ordered fields :)

> (3). This absolutely needs to be editable, so that you can [,,,]. Agreed that
> the wordage around it needs to be better.

  I see. Then internally it's very important. I suppose that this way, two folders with the same folder label, but different folder id, could even coexist. Anyway, for me the most important will be to be able to share a folder faster and easier way and that's selecting it without having to type anything, and then getting the label for it automatically. Folder-id gets it's number automatically, so it's not a big problem anyway.

**Comment by norgeous** [comment]
I think for most people the `Folder Path` is the only important thing when adding a folder. Maybe the more drastic approach of hiding nearly everything away into the `Advanced settings` expandable and automatically taking the folder name as the label is the most user friendly. Then show expanded options when they later click `Edit` on the folder. 

![untitled](https://cloud.githubusercontent.com/assets/4681349/15630686/336236c6-253d-11e6-8969-7abcf0c1813a.png)

**Comment by user514** [comment]
@norgeous completely agree. That could be an advanced option. Normally we will create the folder first with the windows explorer and think about a proper name. Then, just selecting the folder from syncthing everything else should be done automatically when adding the folder from the syncthing interface.

  If somebody is crazy enough to have different names for a folder in the syncthing environment and in the file explorer and want to make a mess, that's up to them with the advanced tab.

  I think that, now, when somebody creates a shared folder, he will think... "Ok, I have already selected a folder, why the interface is asking me again to enter a name for the folder if I already gave it?, and whats the folder id and why are you asking me about it?.

**Comment by lkwg82** [comment]
I like the suggestion, but what I miss is the verification of a share request. How do I know a friend shares the folder he likes to share with me? So I miss the folder id. How would that fit into this UX proposal?

**Comment by uok** [comment]
I don't like the idea hiding the label, as people mostly share same named folders (e.g. photos, music)

**Comment by calmh** [comment]
This needs clarification to be actionable and gain a better subject. I'm not 100% sure of what is the proper action to resolve this one so leaving to the community to hash out - will be closed on the next bug sweep otherwise :)

**Comment by calmh** [comment]
Closed as not actionable
