### ISSUE TITLE
Internal Server Error in `/rest/system/upgrade`

### ISSUE THREAD

**Issue by vladipus** [syncthing/syncthing#3171]
Getting some nasty errors in 0.13.2, including:
`GET http://localhost:8384/rest/system/upgrade 500 (Internal Server Error)`

More:
![selection_22 15 01](https://cloud.githubusercontent.com/assets/468323/15481627/282496a8-2134-11e6-9510-142c172b8406.png)

### Version Information

Syncthing Version: v0.13.2
OS Version: Ubuntu 16.04 LTS

**Comment by AudriusButkevicius** [comment]
Are you sure this is 0.13.2?
What's in syncthings logs?

**Comment by vladipus** [comment]
What logs? Does ST do logs by default?

**Comment by AudriusButkevicius** [comment]
Yes, it logs to stdout by default.

**Comment by canton7** [comment]
Doesn't `/rest/system/upgrade` normally 500 if automatic upgrades have been disabled?

**Comment by AudriusButkevicius** [comment]
Actually, you are right.
You need to look at the body of the response to see if it's a 500 because it's disabled at compile time, or if it's 500 because there was an actual error.

The log will also show the actual error if any, yet the more worrisome thing is the 403's.

**Comment by calmh** [comment]
The 403s are fixed by my recent CSRF fixes which are not in 0.13.2
