### ISSUE TITLE
New device and new folder notification text not automatically formatted

### ISSUE THREAD

**Issue by tmlmt** [syncthing/syncthing#3173]
On server A (running Syncthing for a long time) I received a "new device" then a "new folder" notification as I added server A in server B (fresh install of Syncthing). Here is the screenshot:

![selection_001](https://cloud.githubusercontent.com/assets/10244927/15499274/9ea4e692-21a3-11e6-89cd-7997186f2bc6.jpg)

### Version Information

Server A:
Syncthing Version: v0.13.2
OS Version: Ubuntu 14.04
Browser Version: Firefox 46.0.1

Server B:
Syncthing Version: v0.13.2
OS Version: Windows 7 64 bits
Browser Version: Firefox 46.0.1

**Comment by AudriusButkevicius** [comment]
See closed issues.

**Comment by tmlmt** [comment]
OK. Weird to close an issue that's actually open ... 
Anyway, my bad for not looking at closed issues (default "is:open" option in the search bar be damned)

**Comment by AudriusButkevicius** [comment]
What do you mean actually open? This was already fixed, no new version was released yet due to this being a fairly small cosmetical issue.

**Comment by tmlmt** [comment]
Ah all right, that makes sense now. Well, I got up on the wrong foot today :s
Sorry about the fuss. Cheers
