### ISSUE TITLE
Ignore patterns with non-ASCII characters causes out of memory crash

### ISSUE THREAD

**Issue by vsandre** [syncthing/syncthing#3174]
After upgrading from 0.12-series to 0.13.2 syncthing does not start. After Starting it ends in a panic.

Output see: https://gist.github.com/vsandre/9cb8adaa57e1956aeca104d207d1bc03

### Version Information

Syncthing Version: v0.13.2
OS Version: Ubuntu 14.04
Virtual Machine: Strato.de V-Server Linux Level 1 (2cpu, min 2gb ram)

Usage: 3 Shares
- 37400 objects, ~31.3GiB
- 93735 objects, ~29.2 GiB
- 599 objects, ~283 MiB

**Comment by AudriusButkevicius** [comment]
Sounds like #3073, closing as dup for now, and let's continue the discussion there. Also providing strace loke the original author would be useful.

**Comment by calmh** [comment]
This log is cleaner though, as the gclog shows us progressively requesting more memory until it just plain does run out of memory. Unclear though with that folder setup why it would ever need to much RAM

**Comment by vsandre** [comment]
Syncthing 0.12.24 works fine with 61.4 MiB Ram at the moment. But 0.13.2 does not.

**Comment by AudriusButkevicius** [comment]
Can get a memory graph for 0.13.2?

@calmh I think the go version change is a potential culprit, no?

**Comment by calmh** [comment]
Both are compiled with 1.6.2 iirc.

STPERFSTATS=1 writes a log of memory usage with 250 ms granularity which may help. I have an awesome package I used to do some analysis of our previous leak at https://github.com/calmh/ev but Syncthing isn't compiled with it. I was planning to write something up about that and move Syncthing to it at some point. It neatly correlates output from for example -verbose with when allocations happened in a cool UI

**Comment by calmh** [comment]
But it must be something specifically weird triggering it, as we don't have higher memory usage on 0.13 *in general* than 0.12. Rather the opposite.

**Comment by vsandre** [comment]
Output with STPERFSTATS=1 and clean index-v0.13.0.db directory.
https://gist.github.com/vsandre/9434b2c10de7278ed0b534f8740a446b

@AudriusButkevicius Tell me a shell command to fullfill your request.

**Comment by calmh** [comment]
Out of curiosity, what do your ignore patterns look like?

**Comment by vsandre** [comment]
no ignore patterns set for the 2 smallest directorys. The biggest directory is user-directory with some config, temp and lock-files beeing ignored.

> *bu_last*
> *ä*
> *ö*
> *ü*
> *ß*
> *temp*
> *Temp*
> *tmp*
> .adobe
> .aladin
> .DCOPserver*
> .dm
> .jd
> google-earth
> Trash
> .thumbnails
> Cache
> .cache
> .dvdcss
> cache*
> socket*
> *-socket
> *fontconfig
> *akonadi*
> *bundle*
> *thumb*
> RecentDocuments
> eclipse-5.0.0
> .config/syncthing
> Local*Folders-2
> .cddb
> .macromedia
> .xsession-errors*
> .~lock*
> *~
> albumcovers
> .kde4/share/apps/knemo/
> .macromedia/Flash_Player/macromedia.com/support/flashplayer/sys/
> .gwenview_importer*
> .viminfo
> .recently-used
> *.default/*.sqlite*
> .Skype
> .mozilla/firefox/*.default/sessionstore-backups/recovery.*
> .mozilla/firefox/*.default/extensions
> .kde4/share/apps/konqueror/
> .kde4/share/config/konq_history

**Comment by calmh** [comment]
Fascinating! Any pattern beginning with asterisk and a non-ascii character (i.e. `*ä...` causes the glob pattern compiler to enter an infinite loop, allocating memory in the process. Time to file a bug report on that and see if we can fix it ourselves in the meantime. :)

**Comment by calmh** [comment]
Related to https://github.com/gobwas/glob/issues/15

**Comment by calmh** [comment]
Unfortunately not super trivial to fix from our side. I understand the problem, but not the code base well enough to see the cleanest solution.

**Comment by vsandre** [comment]
0.13 series works at the machine without non-ASCII charackters as ignore pattern.
