### ISSUE TITLE
New folder dialog shows "{%device%} wants to share folder "{%folder%}"

### ISSUE THREAD

**Issue by KevinBEvv** [syncthing/syncthing#3176]
v0.31.2 Windows 64-bit
A request to share a folder from a peer comes with variables in the banner request on the web GUI:
{%device%} wants to share folder "{%folder%}". Add new folder?
![bug1](https://cloud.githubusercontent.com/assets/15109939/15516082/bfb2fca8-21b6-11e6-9881-79ea3dcbaa17.jpg)

**Comment by AudriusButkevicius** [comment]
So I've closed around 3 tickets with the same report today, as nobody seems to check closed issues and always feel trigger happy when opening new ones.

Just so that people would stop opening these tickets, I'll leave this one open until the next release.

**Comment by KevinBEvv** [comment]
I did glance at them, but I wasn't sure I could identify the keywords.  Last time I report a bug, because this is the second time I've had a terse programmer response. bye

**Comment by KevinBEvv** [comment]
People who post redundant bug reports are simply trying to help out a project they believe in too.  Programmers need to remember this fact.

**Comment by KevinBEvv** [comment]
Audrius Butkevicius wrote on 2016-05-24
      02:37 PM:
    
    
      So I've closed around 3 tickets with the same report today, as
        nobody seems to check closed issues and always feel trigger
        happy when opening new ones.
      Just so that people would stop opening these tickets, I'll
        leave this one open until the next release.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub

**Comment by KevinBEvv** [comment]
Audrius Butkevicius wrote on 2016-05-24
      02:37 PM:
    
    
      So I've closed around 3 tickets with the same report today, as
        nobody seems to check closed issues and always feel trigger
        happy when opening new ones.
      Just so that people would stop opening these tickets, I'll
        leave this one open until the next release.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub
      
        
          
          
        
        
      
    
    People who post redundant bug reports are simply
              trying to help out a project they believe in too.
              Programmers need to remember this fact.

**Comment by AudriusButkevicius** [comment]
Sure thing, we appreciate your help, but in my perfect non-existing world everyone's a developer and know that they should check closed bugs before opening new ones, especially when last 5 out of 13 talk about this issue

It's also my fault that I've closed all of them, so I can only blame myself.
