### ISSUE TITLE
Add ignore list flag to force choosing the newest file

### ISSUE THREAD

**Issue by hashworks** [syncthing/syncthing#3181]
Some sync conflicts I get are files where I always want the latest file to be used on all devices, regardless of conflicts. An ignore list flag would be great for that, something like (?n).

**Comment by AudriusButkevicius** [comment]
Just set conflicts to 0 in advanced configuration, and you won't see any conflicts.

**Comment by hashworks** [comment]
Hm, I'm not seeing this setting in the v0.13.2 webinterface. Is this the <maxConflicts>10</maxConflicts> setting in the config file?

Also, this would mean it would ignore all conflicts instead of specific ones like I have in mind with the ignore list flag.

**Comment by AudriusButkevicius** [comment]
Thats global though. I personally don't think we will ever support per file conflict resolution strategies, as I am not aware of any other sync tool providing this level of granularity... hence I am inclined to close it.

**Comment by AudriusButkevicius** [comment]
I can imagine support an external conflict resolver where you can do wherever you want, but I think there already exists a ticket like that, and nobody cares enough about it to implement.

**Comment by AudriusButkevicius** [comment]
#1746
