### ISSUE TITLE
Sort out http caching strategy

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#3182]
Copied from IRC.

Reading everything I can find on http caching, I'm pretty sure that our caching headers are letting browsers cache anything they like for as long as they like (they'll make up some heuristic on when to revalidate based on the last-modified). I *think* we need max-age=0 and must-revalidate in order to force the browser to revalidate on every request (it will still send if-modified-since).

Alternatively, we could set / to never cache, and use cache busting from within angular...

... or maybe you should use no-cache, although apparently browsers have started treating that like no-store (i.e. no caching at all).

Also, it looks like chrome caches rest responses which result in an error (I've got some 403 CSRF errors here, which have been cached), as no headers were returned with them.

**Comment by lkwg82** [comment]
best is to use versioned resources and dont mess with caching. Let it cache old but always offer a uptodate version! This common rwcommended best practice.

versioned means /css/style.md5hashOrSthElse.css

**Comment by AudriusButkevicius** [comment]
Yeah but that means that we need HTML templating.

**Comment by AudriusButkevicius** [comment]
99.99% of the time the page is served locally, so to be honest, I'd just tell it to kill caching always.

**Comment by canton7** [comment]
> best is to use versioned resources and dont mess with caching. Let it cache old but always offer a uptodate version! This common rwcommended best practice.

This is the cache busting from within angular I referred to (since we'd probably want to let angular add the cache busting stuff, given that we don't want to go templating our otherwise-static `index.html` at build time.

> 99.99% of the time the page is served locally, so to be honest, I'd just tell it to kill caching always.

Tempting...

**Comment by calmh** [comment]
Note that we actually *do* have HTML templating now, in that at least the index.html file is actually processed before being sent. That's also where we link to all other things, so it would be possible to do.

But indeed, the effort may not be worth it and we should just serve very short lived cache headers instead.

**Comment by canton7** [comment]
Even with cache busting, we'd still have to force the index page to either always be revalidated, or not cached at all, so I don't think we're gaining anything by using cache busting: just use the same strategy for the assets as for the index page.

Aside: note that we're a bit different your typical website, in that we can't afford any delay in expiring old assets (think about switching themes, or upgrading, where the first request after the theme switch / upgrade determines whether or not the user thinks Syncthing is broken); however we fetch everything from localhost (almost all of the time, anyway), and we've got an SPA which loads all of its assets only once, so revalidating or fetching the entire asset is cheap anyway.

Therefore my personal preference is either to add the `noCacheMiddleware` to all requests (simple nuclear option, with few consequences in practice), or keep the `Last-Modified` approach but try and force browsers to always revalidate.
