### ISSUE TITLE
lib/model: "overwriting protected files" warning doesn't properly take ignores into account

### ISSUE THREAD

**Issue by hashworks** [syncthing/syncthing#3183]
### What happened

When I'm syncing my home directory I need to exclude the syncthing configuration files. So I add the following to my ignore list:
`/.config/syncthing`

However, this results in the following warning on start:

```
Mai 25 12:53:08 book syncthing[28921]: [6EVKI] WARNING: Some protected files may be overwritten and cause issues. See http://docs.syncthing.net/users/config.html#syncing-configuration-files f
or more information. The at risk files are: /home/hashworks/.config/syncthing/index-v0.13.0.db, /home/hashworks/.config/syncthing/config.xml, /home/hashworks/.config/syncthing/cert.pem, /home
/hashworks/.config/syncthing/key.pem
```

When I change the ignore list entry to the following the warning won't occur after a restart.
`.config/syncthing`
### What I expect

The warning shouldn't occur when I'm syncing `~` and I ignored `/.config/syncthing`, just as with `.config/syncthing`.
### Steps to reproduce
1. Sync your home directory
2. Watch the configuration sync warning appear
3. Stop syncthing
4. Add `.config/syncthing` to your ignore list
5. Start syncthing
6. Make sure the configuration sync warning doesn't appear
7. Stop syncthing
8. Append `.config/syncthing` with `/`
9. Start syncthing
10. Watch the configuration sync warning appear
### Additonal

I haven't testet if the configuration files actually get synced with `/.config/syncthing`, they won't with `.config/syncthing`. Could be that only the configuration sync check is missing a rule.
Edit: I've testet the `/.config/syncthing` entry, as I expected the rule works as it should, the folder isn't getting synced. It's just the warning message that is missing a rule for that case.
### Version Information

Syncthing Version: v0.13.2
OS Version: Archlinux

**Comment by AudriusButkevicius** [comment]
Ignore rule working you mean actually ignoring?

**Comment by hashworks** [comment]
Yeah, I updated the text. Actually not syncing the files. I'm currently creating a faked test folder to test that.

**Comment by hashworks** [comment]
I've testet the `/.config/syncthing` entry, as I expected the rule works as it should, the folder isn't getting synced. It's just the warning message that is missing a rule for that case.

**Comment by calmh** [comment]
Great report, thanks

**Comment by calmh** [comment]
The protected files list contains absolute paths, but the ignore matcher expects folder relative.
