### ISSUE TITLE
I am getting default placeholders instead of actual text.

### ISSUE THREAD

**Issue by KrunchMuffin** [syncthing/syncthing#3187]
I am getting default placeholders instead of actual text.

![image](https://cloud.githubusercontent.com/assets/1037197/15548461/7ab2906c-2276-11e6-95e5-715d716bae8a.png)

### Version Information

Syncthing Version: v0.13.2, Linux (64 bit) / v0.13.2, Windows (64 bit)

**Comment by lkwg82** [comment]
@KrunchMuffin If you wonder why this was closed without any comment, please search for many many duplicates.
