### ISSUE TITLE
Variable names appearing instead of their values; Firefox security warning

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [syncthing/syncthing#3191]
Is it unfair of me to say that this software, especially but also perhaps independently of its various implementations on various platforms, repeatedly breaks? Here's the latest non-functioning situation:

![screenshot-area-2016-05-26-032030](https://cloud.githubusercontent.com/assets/9998846/15561921/823b61e8-22f2-11e6-81b3-d83900aa5268.png)

I get errors like this as well:
![screenshot-area-2016-05-26-032636](https://cloud.githubusercontent.com/assets/9998846/15561844/fdff397c-22f1-11e6-83bd-fe667a453492.png)

Actually, I discover that that problem may be the cause of the previous error. Since I've found a way of correcting the latter (Firefox security) problem, perhaps I overreact. Yet, with Syncthing, it does seem to be one problem after another . . I do not mean to be ungrateful. Perhaps this software is not ready for widespread use, whilst somehow I got the impression that it was.

Syncthing Version: v0.9.0.2 (Daemon v0.13.2) [I think; the 'about' option in the web GUI doesn't seem to be working; I take the information from Synthing-GTK]
OS Version: Mint 17.3
Browser Version: Firefox 46.0.1.

**Comment by AudriusButkevicius** [comment]
If you are unhappy with it, feel free to ask for a refund.
The version number starts with a 0 for a reason you know.

Also, this issue you are reporting has been reported many times times this week, so it would be awesome if you'd check closed (or even already open...) issues before opening new ones.

**Comment by canton7** [comment]
The security "issue" is unavoidable. You simply cannot use anyrhing apart from a self-signed certificate: no authority will issue you a certificate for localhost, even if you could convince them to automatically issue a certificate for every syncthing user... 

It's also perfectly safe. You connection is encrypted.
