### ISSUE TITLE
Warn when using duplicate folder path or recursive structure

### ISSUE THREAD

**Issue by JohnMaguire** [syncthing/syncthing#3199]
At work, a few of us use 4 SyncThing shares to share different files with each other. However, one of our coworkers didn't understand that the name of the share would not be appended to the directory path he entered on the UI. This resulted in us deleting "duplicate" files from the incorrect shares, which caused his machine to sync them to all the other shares.

While I see how having the same path for different shares could be useful, a warning that you are doing it would probably be a good idea.

**Comment by AudriusButkevicius** [comment]
We already warn about nested folders, though from your explanatiom I am not sure I understand exactly what happened in your case.

**Comment by JohnMaguire** [comment]
Interesting, did that happen since v0.12? And it wasn't nested folders - they had identical paths.

**Comment by AudriusButkevicius** [comment]
I think that will warn you too, but I'd have to check.

**Comment by JohnMaguire** [comment]
I'll give it a shot on v0.13 shortly. :)

**Comment by AudriusButkevicius** [comment]
https://github.com/syncthing/syncthing/blob/master/gui/default/syncthing/core/pathIsSubDirDirective.js

Not obvious if it works for exact paths.

**Comment by AudriusButkevicius** [comment]
```
> isSubDir('/a', '/a')
< true
```

So it already warns you.

**Comment by JohnMaguire** [comment]
Thanks for looking into this @AudriusButkevicius, and I apologize for the waste of time.
