### ISSUE TITLE
 Failed to load vendor/bootstrap/js

### ISSUE THREAD

**Issue by timqha** [syncthing/syncthing#3200]
the image of what is happening
https://drive.google.com/file/d/0BzkOE11vGwMPcm44NlFWa1hQX2M/view?usp=sharing
I updated, this error appeared (version syncthing-linux-amd64-v0.12.21 to syncthing-linux-amd64-v0.13.4).
I tried to install from source,
across the apt-get...
**all led to the same result.**

Failed to load resource: the server responded with a status of 404 (Not Found)
**http://127.0.0.1:8384/vendor/bootstrap/css/bootstrap.min.css Failed to load** 
Failed to load resource: the server responded with a status of 404 (Not Found)
**http://127.0.0.1:8384/vendor/bootstrap/js/bootstrap.min.js Failed to load** 

**angular.js:9419 ReferenceError: $ is not defined**
    at new <anonymous> (syncthingController.js:58)
    at invoke (angular.js:3710)
    at Object.instantiate (angular.js:3721)
    at angular.js:6772
    at angular.js:6185
    at forEach (angular.js:310)
    at nodeLinkFn (angular.js:6172)
    at compositeLinkFn (angular.js:5636)
    at publicLinkFn (angular.js:5541)
    at angular.js:1304

### Version Information

Syncthing Version: v0.13.4
Linux Mint Rafaelo (base on Ubuntu 14.04)
Browser Version: (if applicable, for GUI issues)
GoogleChrome Version 50.0.2661.75 (64-bit)

**Comment by wweich** [comment]
Did you clear the browser cache? Syncthing doesn't use minified versions (anymore).

**Comment by norgeous** [comment]
try pressing `CTRL + F5`
