### ISSUE TITLE
Feature Request: Log collection

### ISSUE THREAD

**Issue by tbennett6421** [syncthing/syncthing#3208]
I'm not sure if any of this has been implemented or not.

I would love to have the ability to point my syncthing instances to be able to log to a server using SNMP or syslog, With a large number of endpoints it becomes troubling to verify on each one if they are having issues syncing

**Comment by canton7** [comment]
Logging is handled by whatever service manager started Syncthing: Syncthing juts outputs its log to STDOUT, and leaves it up to other tools to redirect that to whatever journalling system is appropriate.

If you have a tool which can take the STDOUT of a process and redirect it to SNMP, that will work fine. Most service managers can redirect STDOUT to syslog.
