### ISSUE TITLE
Occasional GUI 502 HTTP Error

### ISSUE THREAD

**Issue by ctlaltdefeat** [syncthing/syncthing#3209]
- what happened

HTTP 502 error when browsing to the GUI occasionally

 - what you expected to happen instead

HTTP 200

 - any steps to reproduce the problem.

Browsing to the GUI under unknown conditions

CPU isn't high or anything, so this is pretty weird.
Default logging doesn't report anything special.

Syncthing Version: v0.13.2
OS Version: Linux 64 bit

**Comment by canton7** [comment]
How does this actually appear? Does the red "An error occurred" dialog come up? If so, how do you know it's a 502? Are you looking at a particular request that failed using the developer tools? If so, which request failed?

**Comment by ctlaltdefeat** [comment]
Both things occur: if I leave the GUI running then eventually I will encounter the red "An error ocurred". Usually refreshing fixes it, but occasionally just "502 error occurred" is displayed in plaintext (or something along those lines).

**Comment by canton7** [comment]
Have you set up Syncthing so it's behind another server, like nginx or apache?

**Comment by ctlaltdefeat** [comment]
Yep, behind a reverse proxy.

**Comment by canton7** [comment]
Right, so the "502 Bad Gateway" means that your gateway received a response it wasn't expecting from Syncthing.

Make sure you've [read the docs](https://docs.syncthing.net/users/reverseproxy.html), and see what the log messages from your reverse proxy are. This isn't a Syncthing issue.
