### ISSUE TITLE
Syncing percentage passes 100%

### ISSUE THREAD

**Issue by ctlaltdefeat** [syncthing/syncthing#3210]
- what happened

Currently syncing is at 110% and is generally not a very good indication as to the progress of things.

 - any steps to reproduce the problem.

Not quite sure to be honest.

Syncthing Version: v0.13.4
OS Version: Linux 64 bit

**Comment by canton7** [comment]
See https://github.com/syncthing/syncthing/issues/3102 .

**Comment by ctlaltdefeat** [comment]
Sorry, I updated my post to reflect that this is happening in version v0.13.4 (GUI reports version 0.13.2, but "syncthing --version" reports version 0.13.4.

**Comment by canton7** [comment]
> (GUI reports version 0.13.2, but "syncthing --version" reports version 0.13.4.

Even after refreshing the GUI? Then you're not running the Syncthing binary you think you're running.

**Comment by ctlaltdefeat** [comment]
My bad, there seemed to be another process of syncthing running somehow. After forcibly killing it and restarting the appropriate service, everything seems fine.
