### ISSUE TITLE
Syncing progress over 100%

### ISSUE THREAD

**Issue by DEVoytas** [syncthing/syncthing#3213]
Sometimes I see synchronization progress (usually well) over 100%.
Unfortunately I don't have any particular steps to reproduce it.

I saw #1165 (and few other tickets about negative percentage), but it is already closed.

### Screenshot:
![syncthing_sync_over_100_perc](https://cloud.githubusercontent.com/assets/15203013/15633373/cc6688c2-25ab-11e6-9423-7edb38a931bc.png)

### Version Information

Syncthing Version: v0.13.2
OS Version: Linux Mint 17.3 Rosa
Browser Version: Firefox 46.0.1

**Comment by AudriusButkevicius** [comment]
Fixed in 0.13.4

**Comment by DEVoytas** [comment]
Well, I guess we are talking about this commit: fc173bf679db "lib/model: Fix wild completion percentages", correct ?
I had a brief look at recent changes before filing the new issue, but somehow had missed this one.
Anyway, good to know it has been fixed already.
