### ISSUE TITLE
gui: Mobile top bar is (still) crap

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3218]
<img width="446" alt="screen shot 2016-05-30 at 10 18 59" src="https://cloud.githubusercontent.com/assets/125426/15643879/fbb25e72-264f-11e6-9746-76e37d30e2d9.png">

![1000 yard stare tom lea](https://cloud.githubusercontent.com/assets/125426/15649073/0da9acb0-266f-11e6-85ef-95aca4f1dd93.jpg)

**Comment by uok** [comment]
welcome to the world of responsive webdesign :smile: 
we could maybe shrink the upgrade button to just the :arrow_up: icon on smaller devices

**Comment by norgeous** [comment]
Lucky for you I am a responsive specialist, Thoughts? https://github.com/syncthing/syncthing/issues/3240
