### ISSUE TITLE
Relay via SOCKS5 proxy doesn't work

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3226]
Possibly also other connections via proxy. One symptom is this on the client side, when it's *accepting* a relay connection (that is, it has joined the relay successfully, but when attempting to connect again to accept an incoming connection via the relay):

```
[I6KAH] 09:42:50 WARNING: Joining relay session (BEP/relay): proxy: failed to read connect reply from SOCKS5 proxy at localhost:3443: EOF
```

(removed some probably wrong info here)

**Comment by AudriusButkevicius** [comment]
I think it now works, following the slur of your commits?

**Comment by calmh** [comment]
I think it didn't, but it seemed on the forum like it did, so yes lets close and hope for the best.
