### ISSUE TITLE
File names ending in space should be filtered out as invalid on Windows

### ISSUE THREAD

**Issue by Photographix** [syncthing/syncthing#3227]
Hello, I have the following problem

sync a folder with space at the end ("Folder ") from OS X to windows client generate a error on windows client. the folder will be allowed under osx with space at the end.

[DKLHH] 12:29:54 INFO: Puller (folder "Home.TestUser", file "schützenfest \\P1060793.MP4"): dst create: open c:\SyncThing\TestUser\schützenfest \~syncthing~P1060793.MP4.tmp: Das System kann den angegebenen Pfad nicht finden.
[DKLHH] 12:29:54 INFO: Puller (folder "Home.TestUser", file "schützenfest \\P1060792.MP4"): dst create: open c:\SyncThing\TestUser\schützenfest \~syncthing~P1060792.MP4.tmp: Das System kann den angegebenen Pfad nicht finden.
[DKLHH] 12:29:54 INFO: Puller: final: open c:\SyncThing\TestUser\schützenfest \~syncthing~P1060793.MP4.tmp: Das System kann den angegebenen Pfad nicht finden.
[DKLHH] 12:29:54 INFO: Puller: final: open c:\SyncThing\TestUser\schützenfest \~syncthing~P1060792.MP4.tmp: Das System kann den angegebenen Pfad nicht finden.

### Version Information

Syncthing Version:  v13.4
OS Version: Windows 10 / OSX 10.10

is there a pattern for .ignore file to prevent sync from folders with ending space ("folder ") to other clients?

**Comment by calmh** [comment]
Files and folders on Windows cannot end with a space, indeed. Unfortunately I don't think literal spaces will work in the .stignore file (we strip them), but you can match for example `Folder?` as that matches `Folder` with any character afterwards. If you only have the one with a space in it, that would be the one matched.

**Comment by calmh** [comment]
We might filter this out earlier, we do check for invalid file names on Windows but this one doesn't get caught by that net.

**Comment by Photographix** [comment]
"Folder?" will not work, I do not know when someone so creates a folder.
I have a network with 10 clients which 3 are OSX.
when a friend with osx so create a folder accidentally have seven other people a problem on windows.
the folder with the blank on end is created under windows but files can not be copied into it from syncthing. also the folder can not delete on windows

**Comment by calmh** [comment]
Yes. So, syncing such a folder to Windows is never going to work. If you don't want to ignore it using that pattern, you'll need to wait for us to blacklist it earlier in the process. The end result there will be just a warning on the Windows side that the folder can't be synced, and then nothing more.
