### ISSUE TITLE
Syncthing Windows changes config directory

### ISSUE THREAD

**Issue by hardymark** [syncthing/syncthing#3233]
I've had this happen a few times, with both Syncthing 11 and Syncthing 13, on Windows 7 & 8.1:

Occasionally on my (multiple) computers, Syncthing starts up without a configuration, and I discover that it has created a new config.xml under a subfolder where I have placed the Syncthing executable directory. Normally, it stores its config and index under c:\users\myusername\appdata\local\syncthing, but sometimes at startup it creates a new directory under the application/executable directory and creates config.xml there (without any configuration of course). If I stop the processes and start again, it finds the configuration under appdata and works as expected.

I have Syncthing starting at computer startup using a Scheduled Task, running under my user account. 

It wasn't consistent, but it did recur several times on two of my three computers (the third never restarts so hasn't had much opportunity to reproduce there). After the last time, I just created directory junctions (Windows symbolic links) inside the application/executable directory which point to the correct paths under appdata on my three Windows boxes running Syncthing. Hopefully that will resolve the issue for me, but I wanted to report this behavior. 

### Version Information

Syncthing Version: v0.13.4
OS Version: Windows 7 64bit, Windows 8.1 64bit

**Comment by AudriusButkevicius** [comment]
It uses HomeDrive, HomePath and UserProfile env vars, if none are set, it will use cwd.

**Comment by hardymark** [comment]
So it must be a timing issue with profile initialization at Windows startup. I'll tinker with my scheduled task to resolve. Thanks!
