### ISSUE TITLE
gui: 'Unshared' folders do not show scanning percent

### ISSUE THREAD

**Issue by norgeous** [syncthing/syncthing#3235]
I added a large folder and did not choose to `Share With Devices`.
Gui displays `Unshared`.
Number of items increases from 0 onwards.
Expected to see `Scanning`.
Upon sharing the folder during this period, the gui correctly displayed `Scanning`.
Unsharing it again and it displays `Unshared` again, not `Scanning`.

Looks to me as if `Unshared` has priority over other states, effectively overriding them.

I think its important to show `Scanning` with percentage even for `Unshared` folders.

### Version Information

Syncthing Version: v0.13.4
OS Version: Windows 10 64

**Comment by AudriusButkevicius** [comment]
Agree, I think it's an oversight.

**Comment by norgeous** [comment]
I will have a go at fixing when the number of open PR goes to 7 or less ;]

**Comment by norgeous** [comment]
duplicate of #3068

**Comment by norgeous** [comment]
i guess i should close it then
