### ISSUE TITLE
gui: notice needs html link

### ISSUE THREAD

**Issue by norgeous** [syncthing/syncthing#3241]
![screenshot at 2016-06-02 05 13 39](https://cloud.githubusercontent.com/assets/4681349/15733765/48b44a7c-2881-11e6-9bd4-db0179bf893a.png)

Some protected files may be overwritten and cause issues. See http://docs.syncthing.net/users/config.html#syncing-configuration-files for more information. The at risk files are:

**Comment by norgeous** [comment]
This string is present in `lib/model/model.go`.
I take it that `l.Warnln()` is for console write and probably does not support just adding an `<a>` link, as this will render as html in the console/logfile?

**Comment by AudriusButkevicius** [comment]
Perhaps we could do url search in the strings and perform conversion.

**Comment by calmh** [comment]
Yeah. We do that for device IDs in such message if I remember correctly.

More generally we should probably avoid showing warning output in the GUI and instead base that on an event or something. Those strings aren't even translated properly.

**Comment by kwhite17** [comment]
Hi, I recently just implemented the fix that I believe addresses this issue. This is my first time contributing to an open source project so I want to make sure I'm in compliance with your contribution guidelines before submitting a PR. In particular, I'm a bit unclear as to what this section means:

> When drafting a pull request, please feel free to add commits with corrections and merge from master when necessary. This provides a clear time line with changes and simplifies review. Do not, in general, rebase your commits.

I assume this means don't merge master into my branch unless I need work from commits that were pushed after I created my branch. Is this correct? Sorry if this is the wrong place to ask. Thank you!

**Comment by calmh** [comment]
You can merge from master if you need to or want to, but once you've created a pull request it's easier to follow the evolution of it if you avoid the "git rebase" command. But it's not a huge deal either way, we can deal with however you choose to do it probably. :)
