### ISSUE TITLE
All files titled sync-conflict (My fault, Not a bug)

### ISSUE THREAD

**Issue by falsechicken** [syncthing/syncthing#3247]
I was rapidly changing permissions on a folder that has tons of files. Now every file in the folder has conflicted. This is reflected on both of my clients. So I cannot simply restore from the opposite one. No originals exist. I am sorta in a panic as my backup is a few days old and I did a lot of work in that time and since this folder has git repositories in it manually renaming is not feasible. Does anyone know of some bash fu to remove the sync-conflict-(date) on all the files? Thanks so much.

**Comment by AudriusButkevicius** [comment]
Please use the forum (search before you post). Issue tracker is for bugs.

**Comment by falsechicken** [comment]
Thanks for the info. I posted but the approval process is frustrating. I understand the need for it but while I am waiting I cannot get any work done. On the plus side I have learned (as the documentation states) that Syncthing is no backup solution. I need to be more vigilant in my backups.

**Comment by calmh** [comment]
For the record, the forum approval only kicks in for the first post of new users, where the post is written "too quickly" (in a few seconds, i.e. pasted in rather than written). That's a typical spam pattern.

**Comment by AudriusButkevicius** [comment]
The answer you are looking for is already in number of old posts of the forum, hence why I said use tye search.
