### ISSUE TITLE
pause sync for folder (not for devices)

### ISSUE THREAD

**Issue by Photographix** [syncthing/syncthing#3248]
Is there a way to pause one ore more folder from sync? 
I would like to suspend the synchronization for a folder time x with all devices to prevent space or other.
the other folders synchronize further

![pause](https://cloud.githubusercontent.com/assets/16647382/15750459/d47a17ca-28e6-11e6-8643-740d15233fe3.png)

**Comment by AudriusButkevicius** [comment]
Please search existing issues before opening new ones (dup #215)
