### ISSUE TITLE
cannot sync between 0.12.22 and 0.13.4

### ISSUE THREAD

**Issue by androclus** [syncthing/syncthing#3249]
hello, all,

sorry in advance if this is a FAQ, or well-known.

i have 3 devices - a desktop at home, a desktop at work, and a laptop.

i noticed lately that these were all reading 'Disconnected' after having been working well for some time.

After spending a few hours on it, diagnosing firewall, relays, etc., it turned out to be a simple issue:  The versions which were the same (0.12.22 with 0.12.22, or 0.13.4 with 0.13.4) could talk with each other (and without need for relays), but across these 2 versions, they cannot see each other.

I am guessing that these got out of sync with each other because my machines did not all get updated on their packages at the same time.

Neither the GUI nor the stderr log output gave me any warning that it was a cross-version issue.

I'd like to..

a) find out if others experienced (or knew) about this problem, and, if yes, then 

b) know if there is another bug posted on it (i could not find it in searching here), and

c) ask whether in future versions, it might be possible to -- in both the GUI and log output -- make a prominent message saying, "I see you have another device (device name) you'd like me to connect to, which you've connected to before, but now that machine has a version (version #) too far ahead or behind my own version (version #).  You should make sure that all devices are using the same version number of Syncthing.  For help on this issue, you can go (here)."

thanks, all!

### Version Information

Syncthing Version: v0.12.22 and v0.13.4
OS Version: Ubuntu v15.10 and 16.04
Browser Version: Firefox 46.0.1 (Mozilla Firefox for Ubuntu)

**Comment by AudriusButkevicius** [comment]
It was explained in the release notes, and in the promp you get when you press the upgrade button that 0.12 and 0.13 are incompatible.

**Comment by androclus** [comment]
okay, thanks. And I appreciate your quick response.  But that answers only a), but not b) or c).

I really do not remember getting any "upgrade button". I just have my apt set to automatic upgrades.

Furthermore, I can find nothing that says, "Release Notes" on either the [syncthing home page](https://syncthing.net/) or the [syncthing github home page](https://github.com/syncthing/syncthing).

Neither were these "release notes" brought to my attention when my system automatically upgraded my syncthing (via apt).

So I guess what I am requesting is better communication (i.e., through the GUI) with the end-user in the cases where automatic upgrades are made which will break previous connections.

**Comment by wweich** [comment]
See: https://github.com/syncthing/syncthing/releases/tag/v0.13.0
As of version 0.13, Syncthing will tell you, that if it cannot sync because of version mismatch.

**Comment by androclus** [comment]
thanks, wweich.

although i notice that that page does not say what you said -- that Syncthing will tell us when it cannot sync because of version mismatch.

So it might be nice to update that page so that it does have that information, which is helpful.

However, again, in my case (thus why I filed the bug) I unfortunately got no such communication from Syncthing 0.13.4 that it could not sync with my other 2 devices because they were back on 0.12.22.

**Comment by AudriusButkevicius** [comment]
Subject we don't kill discovery again...

I guess I'd say blame apt in this case, as we used all mediums available to us to inform you about this. Sadly apt is broken and does not provide a way to notify of anything.

As I said, your argument about notifying you about your old versions is invalid, as we cannot tell which version it's using until we connect, and they can't connect because they can't discover each other, and they can't discover because they are on incompatible protocol versions.

**Comment by androclus** [comment]
> we used all mediums available to us to inform you about this. 

i certainly appreciate that from your point of view you did what you could.

however, in the future, i would think another medium available -- as mentioned above -- would be to have prominent links to "Release Notes" on either of the 2 home pages.  Or, if you wanted to go even further, even a prominent/red-colored "Important!" on the two home pages might work, too.

> As I said, your argument about notifying you about your old versions is invalid, as we cannot tell which version it's using until we connect, and they can't connect because they can't discover each other, and they can't discover because they are on incompatible protocol versions. 

hmm.. so each time the protocol changes, all devices running previous versions are now invisible?

**Comment by AudriusButkevicius** [comment]
Depends on how big the change was.

**Comment by androclus** [comment]
okay, well, it's your project.  and i certainly thank you for how well it works in all other ways, to date. i really do love Syncthing -- it's awesome.  but i also think there is room for improvement in this area.  so all i guess i can ask for is a feature request: that the 'dependency' you mention be removed for future versions.  guessing from your last paragraph, there seem to be several places where this could be addressed.  but, up to you. thanks again!

**Comment by AudriusButkevicius** [comment]
There are tons of things that could be better, sadly just a limited number if hands to implement them.

**Comment by androclus** [comment]
yes, well, as a programmer, and as a volunteer for several non-profit projects, i can certainly understand that.

hey! i just thought of another idea (short of re-building the protocol)..  hopefully, this would take less code -- ideally, just an "if-then"..

Syncthing remembers the last address and connection time of another device, right?

Does it also remember the last _protocol_ or _version_ used by that device?

Or *could* it remember those?

Because if it can remember the protocol or version, then it would not be necessary to connect in order to give the user a "heads-up".  Syncthing's GUI could just see that the device is not connected, but that its "last known protocol/version" was incompatible, and then pop up a message (or a prominently-colored alert box inside that device's div) saying something like,

_"The last time I connected to device (devicename), it was using Syncthing version x.yy.z.  But I am now using Syncthing version x.yz.z and we are not compatible -- which probably explains why I cannot connect to that device.  Try upgrading Syncthing on that device."_

Would that be do-able in less programming time?

**Comment by AudriusButkevicius** [comment]
It's inevitable that everyone will get the warning, as nobody starts connected, so I think it's better to just have a syste for displaying one off messages, and keeping track which ones the user has seen.

**Comment by androclus** [comment]
sounds great.  even if it had been only a one-time message pop up, (or an alert under that device), saying to just double-check all devices have same St version number, it would have saved me a ton of time trying to figure it out.  it would be very much appreciated!
