### ISSUE TITLE
Conflicting file replaced losing data

### ISSUE THREAD

**Issue by kluppy** [syncthing/syncthing#3258]
Trying to create conflicts to check naming conventions but file on the laptop was replaced loosing changes.
Expected conflict files created and propagated.

Steps:
Pause android device in ubuntu device / Stop Syncthing on ubuntu device
Edit an in sync file on both devices making different changes.
Save both files.
Re-establish a connection between both devices.

The file on the laptop was replaced each time with the one on the phone, this could be a coincidence. I only tried 3 or 4 times.

Syncthing Version: v0.13.4
OS Version: Ubuntu 14.04

Syncthing Version: v0.13.0
OS Version: Android 6.1
Syncthing-Android 0.7.18

**Comment by calmh** [comment]
This could be an android specific issue as android doesn't track modification times sensibly so we do ugly workarounds. Needs more testing, specifically by someone with an android device.

**Comment by calmh** [comment]
Modtime handling has changed to the better, pretty sure this shouldn't happen now even on Android.
