### ISSUE TITLE
Status Favicon not showing when only device is syncing

### ISSUE THREAD

**Issue by kerko** [syncthing/syncthing#3261]
This maybe a misunderstanding on my part. But apparently the favicon change only happens on folder syncing. Shouldn't it also change if a device is syncing ? Since pausing all devices also changes the favicon.

See the screenshot for what i am referring to.

![screen shot 2016-06-03 at 14 01 17](https://cloud.githubusercontent.com/assets/4713073/15778126/7bc65aea-2994-11e6-88d7-bdf6a7f8664d.png)

### Version Information

Syncthing Version: v0.13.5
OS Version:  Mac OSX 10.11.5 (15F34)
Browser Version: 51.0.2704.79

**Comment by AudriusButkevicius** [comment]
It's there to represent local state, not remote state.

**Comment by kerko** [comment]
@AudriusButkevicius thanks for clarifying
