### ISSUE TITLE
Make syncthing "find your device" friendly

### ISSUE THREAD

**Issue by pauloandre2** [syncthing/syncthing#3264]
I think syncthing can be used to track your devices with minimal changes, especially if you have a main node that is always on.
The changes I propose are:

1- Create a link in the gui to open the logs
2- When relaying, still announce the public (internet) ip of each node to the others
3- Make the logs persistent, or create a separate persistent log for connections only

**Comment by AudriusButkevicius** [comment]
I have no idea what you are talking about and whats the point of what you are suggesting.

**Comment by pauloandre2** [comment]
Ok, I'll elaborate a little.
Imagine you have syncthing on your laptop, connected to your home server.
Now, you went on a trip and your laptop got stolen.
Syncthing is still running, and looking at the logs on your home server, you can see what IP the laptop is, call the police and recover your laptop.
This is already possible due to the good logging syncthing does, but could be improved with the changes I said above.

**Comment by AudriusButkevicius** [comment]
You can enable -verbose (or STTRACE=discovery) and you will see discovery messages and all addresses the device is on. The log is already persistent with -logfile flag, and opening logs link has little to no value, given you know where you specified to log to.
