### ISSUE TITLE
Windows Service

### ISSUE THREAD

**Issue by agowa338** [syncthing/syncthing#3265]
I would like to see a native implementation of a Windows Service for sync.
This would allow the following:
 - No console Window
 - Autostart on Systemboot
 - Dependencies (windows checks status of depending/dependent services)
 - Automatic crash handling (e. g. restart)

For now I programmed my own "[abstraction](https://github.com/agowa338/SyncthingWindowsService)".
I currently store syncthing in "C:\Program Files\Syncthing\syncthing.exe", but this breaks auto update...
The configuration files are stored in "C:\Windows\ServiceProfiles\NetworkService\AppData\Syncthing" as this is the profile of the user ("Networkservice") my service is using.
The Share needs to have NTFS permissions granted to the "Networkservice" user.
Also I implemented a way of accessing the console for debugging purposes using a udp socked.
It even has a simple installer, that runs if you Doubleklick it.

So tell me what you think about it and keep up the good work!

**Comment by AudriusButkevicius** [comment]
You can already do that using external tools, or OS service manager.
For no console window, juse -no-console option.

Also check Synctrayzor and syncthing-gtk, who do most of this already.

**Comment by ProactiveServices** [comment]
[Starting Syncthing Automatically](https://docs.syncthing.net/users/autostart.html#run-as-a-service-independent-of-user-login)
