### ISSUE TITLE
Improve local discovery reaction time at startup

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3278]
Once we refactor the local discovery protocol we should provide a reliable mechanism to detect a device that is restarting, and provide it with up to date local discovery information.

One idea on how to do this is to include a sequence number in our announcement packets. When a device receives an announcement from another device that it hasn't seen before, or an announcement with a lower sequence number that what it has previously seen for that device, it will respond with an announcement packet of it's own.

This resolves an issue where devices that restart would otherwise only have global discovery data for the first few moments and thus prefer external connections over local ones.

**Comment by calmh** [comment]
Relates to #3080.

**Comment by Getron** [comment]
@calmh Agree, this would be great for local discovery speeds. Great idea.
