### ISSUE TITLE
syncthing.exe -generate creating two <listenAddress> entries in a new config.xml

### ISSUE THREAD

**Issue by chrisshearing** [syncthing/syncthing#3290]
- what happened,

We create a new config file with -generate so we can customise before deploying a ready to go config to a client. Two <listenAddress> entries are created as follows:

`        <listenAddress>tcp://0.0.0.0:62713</listenAddress>`
`        <listenAddress>dynamic+https://relays.syncthing.net/endpoint</listenAddress>`

 - what you expected to happen instead

0.12 would create a single entry like:

`    <listenAddress>tcp://0.0.0.0:22000</listenAddress>`

after upgrading a 0.12 config to 0.13 it contains only the following entry

`        <listenAddress>default</listenAddress>`

I have not tried using a config file with 2 entries yet on a new client to see if it corrects the issue on loading the config.

I would have expected 0.13 to create the single entry below when using the -generate flag

`        <listenAddress>default</listenAddress>`

 - any steps to reproduce the problem.

`syncthing.exe -generate c:\path`

An instance of syncthing is running when calling the -generate command.

### Version Information

Syncthing Version: v0.13.5
OS Version: Windows Server 2012 R2

**Comment by AudriusButkevicius** [comment]
If port 22000 is taken this is expected.

**Comment by calmh** [comment]
"default" means "tcp://0.0.0.0:22000" plus the relay thing. In your case, port 22000 was apparently taken so it had to generate a config using something else. This means it can't use the "default" shortcut and you get both.

**Comment by chrisshearing** [comment]
What is the entry of `<listenAddress>dynamic+https://relays.syncthing.net/endpoint</listenAddress>` ? This wasn't present before

I understand getting a listenAddress with a different port as its in use

**Comment by AudriusButkevicius** [comment]
Relay addresses are now just normal listen addresses

**Comment by chrisshearing** [comment]
ah, ok so both are added when the default port can't be use,

Sorry then!

Thanks!
