### ISSUE TITLE
Log file grows too large

### ISSUE THREAD

**Issue by deterenkelt** [syncthing/syncthing#3293]
Tonight I’ve set up Syncthing and successfully synchronized three folders, summary size of which is around 156 GiB, as the web interface reports. The synchronization process wrote a log file `/var/log/syncthing/syncthing.log` of seven GiB, which has almost filled the free space on my root partition. I had to clean it fast in order to avoid out of space state, and, happily, it worked out. 

I’ve noticed, that the Gentoo package from the go-overlay has installed a logrotate file, and triggered the /etc/logrotate.d/syncthing which trimmed the log to 4 KiB. So I thought that would be a great idea to pull logrotate intermittently to trim the log.

Syncthing v0.13.4
OS: Gentoo

**Comment by AudriusButkevicius** [comment]
We log to stdout by default, if your distribution decided to do something else, follow up with them to fix rotation.
