### ISSUE TITLE
Syncing percentage appears to be bogus in some cases.

### ISSUE THREAD

**Issue by Ferroin** [syncthing/syncthing#3295]
Syncthing Version: v0.13.5
OS Version: Gentoo Linux (~amd64)

So, I just recently started using syncthing, and I've noticed at least a couple of times that the 'Syncing' percentage listed in a device's entry on a remote node is absolutely bogus by any measure I can think of more often than not.

In this most recent case, I'm syncing approximately 15.1 GB of data between two systems.  On the system the data is coming from, the system it's syncing to shows as 93% in sync, while on the remote system, the folder in question is 20% in sync. Based on the comparison of local state totals on both systems, the recieving system is roughly 50% in sync overall.  Further calculation based on just that folder in question indicates that the 20% in sync estimate is accurate for that folder.

Assuming no background  whatsoever, I'd expect the 'Syncing' percentage for a device to reflect how far the remote device is from the global state directly, and it's pretty obviously not doing so.

**Comment by AudriusButkevicius** [comment]
Device completion is based on total across all folders, where as folder completion is relative to the folder.

Also I am sure this is duplicate/covered by #1300 #623 #2652 or any other ticket that talks about this.

**Comment by Ferroin** [comment]
I understand it's an aggregate across all shared folders, I'm saying even that math isn't correct on my systems.  I really shouldn't have mentioned the folder completion at all, because that has absolutely nothing to do with the issue at hand, it was just intended to point out that that part of the calculations was exactly correct.

The total count of files in the local state for the whole device was 1273 out of 2562 in the global state of all the folders on that device.  Total data usage for local state on the device was roughly 10.4 GB out of 22.8 GB for the global state of all the folders.  Both comparisons give a roughly 50% sync between the devices, while the one which was sourcing almost all of the data reported the remote device at 93%..
