### ISSUE TITLE
Mismatch of border radius size in folder and device buttons

### ISSUE THREAD

**Issue by chris-thorn** [syncthing/syncthing#3299]
Following the update to v0.13.6 I've noticed a mismatch between the `border-radius` value of `div#folders.panel-group > div.panel.panel-default` which is set to 2px and `div#folders.panel-group > div.panel.panel-default > button.btn.panel-heading` which is set to 3px.

It looks like this applies to both the default theme and dark theme, although the issue is more pronounced in the dark theme.

![Border radius issue in default and dark themes](http://i.imgur.com/K4BFAuT.png)

### Version Information

Syncthing Version: v0.13.6
OS Version: Windows 10 64-bit, Ubuntu 14.04, ARM
Browser Version: all

**Comment by calmh** [comment]
That's attention to detail. :) Paging @norgeous to the surgery, stat! ;)

**Comment by norgeous** [comment]
Hi, I also noticed this, but was just a little too late (like 1 min) to add commit to the PR :'[
I will fix this soon (next day or so).

**Comment by chris-thorn** [comment]
Hah, always the way!

**Comment by norgeous** [comment]
setting it to zero...
