### ISSUE TITLE
Usage reporting prompt doesn't display properly, greying out the UI

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3301]
When the usage report prompt is displayed at startup, it fails to load the modal and just greys out the screen. Adding a delay seems to work around it:

```diff
diff --git a/gui/default/syncthing/core/syncthingController.js b/gui/default/syncthing/core/syncthingController.js
index f9214c9..3df90bd 100755
--- a/gui/default/syncthing/core/syncthingController.js
+++ b/gui/default/syncthing/core/syncthingController.js
@@ -221,7 +221,9 @@ angular.module('syncthing.core')
                     document.cookie = "firstVisit=" + Date.now() + ";max-age=" + 30 * 24 * 3600;
                 } else {
                     if (+firstVisit < Date.now() - 4 * 3600 * 1000) {
+                        setTimeout(function () {
                             $('#ur').modal();
+                        }, 0);
                     }
                 }
             }
```

What's going on here?

The javascript console shows nothing interesting.

(0.13.6)

**Comment by calmh** [comment]
I added a delay to temporarily work around it even though I don't understand the underlying issue. I also messed up the commit message (it's not disabled), but hey...

**Comment by calmh** [comment]
Paging @norgeous for understanding of the root cause here, when possible...

**Comment by norgeous** [comment]
hello, I will look now! sorry for the delay

**Comment by norgeous** [comment]
confirmed.

To explain what's happening:

1. `<ng-include>` loads `usageReportModalView.html`. This contains a `<modal>` element.
2. `modalDirective.js` sees the `<modal>` and converts it to a `<div>` with same id. At the same time `modalDirective.js` links event listeners to the modal, for multi-modal ability.

In this case `$('#ur').modal();` is being called before the event listeners are linked.
I checked this with the more specific selector `$('div#ur').modal();` - which can only fire after the `modalDirective.js` has applied and converted `<modal>` to `<div>`.

For me the timeout 0 thing didn't work, setting it to 1000 did.

I'll have a look to see if there is a way to prevent the trigger of `.modal()` until the directives have applied and get back to you.

**Comment by norgeous** [comment]
I think the best temporary solution is to revert `usageReportModalView.html` to not use `<modal>`
```html
<div id="ur" class="modal fade" tabindex="-1" ng-attr-data-backdrop="static" ng-attr-data-keyboard="false">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header alert alert-info">
        <h4 class="modal-title">
          <div ng-if="icon" class="panel-icon">
            <span class="fa fa-bar-chart"></span>
          </div>
          {{'Allow Anonymous Usage Reporting?' | translate}}
        </h4>
      </div>
      <div class="modal-body">
        <p translate>The encrypted usage report is sent daily. It is used to track common platforms, folder sizes and app versions. If the reported data set is changed you will be prompted with this dialog again.</p>
        <p translate>The aggregated statistics are publicly available at the URL below.</p>
        <p><a href="https://data.syncthing.net/" target="_blank">https://data.syncthing.net/</a></p>
        <button type="button" class="btn btn-default btn-sm" ng-click="showReportPreview()" ng-show="!reportPreview">
          <span class="fa fa-file-text-o"></span>&nbsp;<span translate>Preview Usage Report</span>
        </button>
        <pre ng-if="reportPreview"><small>{{reportData | json}}</small></pre>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success btn-sm" ng-click="acceptUR()">
          <span class="fa fa-check"></span>&nbsp;<span translate>Yes</span>
        </button>
        <button type="button" class="btn btn-danger btn-sm" ng-click="declineUR()">
          <span class="fa fa-times"></span>&nbsp;<span translate>No</span>
        </button>
      </div>
    </div>
  </div>
</div>
```
The best solution in the long run would be to init `syncthingController` after the `modalDirective` has completed, but I have tried a few methods and have no idea how to do this.

**Comment by norgeous** [comment]
i think win
