### ISSUE TITLE
Cannot access web interface

### ISSUE THREAD

**Issue by gsola96** [syncthing/syncthing#3302]
As you can see in the screenshot, I'm not able to set up nothing in the webGUI. I browse to the adress of my Syncthing Server but it turns instantly darker and I am not able to click anything in the GUI. FYI, it darkens just after appearing the message that I have not set up any password to access the web (of course, since I have recently installed it!)

Any help will be appreciated!

EDIT: have received update to 0.13.7. It is solved, now when I log to the GUI, a pop-up appears asking me if I want to send anonymous statistics (as it did when I installed Syncthing on other computers) so issue closed.

### Version Information

Syncthing Version: v0.13.6
OS Version: Debian 7 Wheezy (headless server)
Browser Version: Mozilla Firefox 47.0

![captura](https://cloud.githubusercontent.com/assets/19892655/16021842/126ebe1a-31b5-11e6-8343-57976e053543.PNG)

**Comment by canton7** [comment]
(Dup of https://github.com/syncthing/syncthing/issues/3301, in case anyone's wondering)
