### ISSUE TITLE
Normal == readwrite and Master == readonly ? 

### ISSUE THREAD

**Issue by lucendio** [syncthing/syncthing#3303]
### bug (maybe)
I am new to syncthing, so I have to excuse myself in advance for maybe holding something wrong. I played a bit with the Master/Normal config and notice that for *Master* in `Actions --> Advanced --> test folder --> type` the corresponding type was *readonly* - same goes for *Normal* but with *readwrite*. I was a bit confused, because I expected it to be the other way around: `Normal == readonly` and `Master == readwrite`. Or am I missing something here?

### feature request
Besides that, is there a working concept of setting a device readonly, which then cant get changed on that device, expect when the folder get removed and added again? In other words: am I able to prevent a *Normal* client from getting set to *Master*? (side note: what happens when more then one node are *Masters* in one cluster?)
If such concept does not exists, I could imagine this might be useful to do on the *Master* - changing such permissions for *Normal* nodes in the cluster. Or at least preventing them from granting themselves more permissions.

### Version Information

Syncthing Version: v0.13.6
OS Version: Mac OS X 
Browser Version: ff 27.0

**Comment by AudriusButkevicius** [comment]
So you misunderstanding is incorrect, normal = readwrite as others can read and write to the folder.
You can't prevent a client from being set into master as it's a decentralized system, and there is no authority for "prevention"

**Comment by ffflorian** [comment]
And what happens when you have two _Master_ set up? Who decides what will be synced?

**Comment by alex2108** [comment]
Both masters will ignore all remote changes, other devices will probably sync the latest change they got, where the override button probably counts as latest change. (never tried 2 masters, it's probably not something you want. Actually I have not even 1 master in my setup)

**Comment by wweich** [comment]
There was a long discussion how to better name the "master folder" setting.
"Master" doesn't mean in any sense, that this is enforced in the cluster or that it has any authority.
Master just means: "ignore any changes made on other nodes and give the user the option to override the changes made on other nodes".
