### ISSUE TITLE
syncthing process can result in an infinite hang when reading /proc/[pid]/cmdline

### ISSUE THREAD

**Issue by awangptc** [syncthing/syncthing#3304]
Do not report security issues in this bug tracker. Instead, contact
security@syncthing.net directly - see https://syncthing.net/security.html
for more information.

If your issue is a support request ("How do I get my devices to connect?"
or similar), please use the support forum at https://forum.syncthing.net/
where a large number of helpful people hang out. This issue tracker is for
reporting bugs or feature requests directly to the developers.

If your issue is a bug report, replace this boilerplate with a description
of the problem, being sure to include at least:

 - what happened,
 - what you expected to happen instead, and
 - any steps to reproduce the problem.

Also fill out the version information below and add log output or
screenshots as appropriate.

If your issue is a feature request, simply replace this template text in
its entirety.

### Version Information

Syncthing Version: v0.13.7
OS Version: Fedora 23
Browser Version: (if applicable, for GUI issues) N/A

At some point, the syncthing web ui stops responding.  Syncing appears to still be working based on the behavior of the other devices but I haven't confirmed it.

When attempting to do a ps to get a process listing on the system, the ps call hangs.  Following is the strace output leading to the hang:

stat("/proc/8026", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
open("/proc/8026/stat", O_RDONLY)       = 6
read(6, "8026 (syncthing) D 1 8026 8026 0"..., 2048) = 330
close(6)                                = 0
open("/proc/8026/status", O_RDONLY)     = 6
read(6, "Name:\tsyncthing\nState:\tD (disk s"..., 2048) = 1120
close(6)                                = 0
open("/etc/passwd", O_RDONLY|O_CLOEXEC) = 6
fstat(6, {st_mode=S_IFREG|0644, st_size=2558, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6e27264000
read(6, "root:x:0:0:root:/root:/bin/bash\n"..., 4096) = 2558
close(6)                                = 0
munmap(0x7f6e27264000, 4096)            = 0
open("/proc/8026/cmdline", O_RDONLY)    = 6
read(6, 

I can't even kill -9 the process.  Only solution I've found that works is a reboot.

**Comment by awangptc** [comment]
I'm not sure, but i think the issue corresponds to when syncthing auto updates.

**Comment by AudriusButkevicius** [comment]
Sure, but it's your kernels issue to be honest. This should never hang.

**Comment by calmh** [comment]
This makes no sense to me...

**Comment by awangptc** [comment]
https://rachelbythebay.com/w/2014/10/27/ps/
That actually sheds some light.  I'm launching syncthing in a systemd unit (to launch automatically).  I bet it has to do with the way a systemd unit defines it's cgroup and process members of the cgroup.  That probably explains it.  My initial gut was, what is syncthing doing that would fubar the /proc/[pid]/cmdline, but on further research agree that it's probably not a syncthing problem.  Thanks for making me think about this in a different way.
