### ISSUE TITLE
Increase time stamp granularity 

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3305]
We currently only track, store and compare file time stamps with second granularity. But ntfs, ext4, apfs and so on store much more fine grained time stamps. I suggest that we add a nanoseconds field to the time stamp, and set time stamps to the highest precision possible. We should still have a (configurable?) comparison window, to allower comparisons to succeed on lower precision systems. Or this could be handled by the mtimefs.

**Comment by DrSchnagels** [comment]
This would be a great change!
I'm a long term user of Microsoft robocopy. I just picked up ST to sync files and search for potential bit rot. 
I noticed if i sync folders and run robocopy again (command /MIR(ror)) then all files are transferred again.
I'm pretty sure this is a time stamp problem.
