### ISSUE TITLE
UI bug in "show items"

### ISSUE THREAD

**Issue by DmitryLyukov** [syncthing/syncthing#3306]
UI bug

![screenshot_2016-06-15_03-41-30](https://cloud.githubusercontent.com/assets/16157777/16064686/77711916-32b4-11e6-8b6a-28a0b1581255.png)

### Version Information

Syncthing Version: v0.13.7
OS Version: Xubuntu 16.04
Browser Version: Firefox 47.0

**Comment by AudriusButkevicius** [comment]
I don't understand what the bug is.

**Comment by calmh** [comment]
The progress bars are unaligned and weird

**Comment by canton7** [comment]
The tooltip looks like it might be for the wrong item, too? I'm not sure what happens if a tooltip is open when an item is removed from the list....
