### ISSUE TITLE
Discosrv - 429: Too Many Requests error

### ISSUE THREAD

**Issue by CoupeWare** [syncthing/syncthing#3312]
I'm running my own discosrv on a ARM system. I frequently get errors in Syncthing stating that there were too many requests.

Can I up the limit on how many requests my discosrv can handle or lower the number of of requests that my Syncthing systems make?

How do I monitor the discosrv to make sure I'm not getting outside requests? Could they be causing this problem.

Do I need better hardware? Will it make any difference?

Everything is up to date (0.13 latest for both Syncthing and discosrv).

**Comment by AudriusButkevicius** [comment]
I don't think this is a bug report, but more of a question, hence probably belongs in the forum and not the bug tracker.

**Comment by CoupeWare** [comment]
Does that mean there is a way to fix my problem with the existing software? If not I think it's a bug since my systems stop connecting all the time.

I submitted it to the forum. Funny the first bullet point is: Is this obviously a bug? Consider filing an issue directly at https://github.com/syncthing/syncthing/issues

**Comment by calmh** [comment]
On the discosrv, see the various `-limit-...` command line flags to adjust it. Although it's a bit odd that you see this as Syncthing itself is supposed to follow the directions given by discosrv on how often to retry etc.

**Comment by CoupeWare** [comment]
I have tried that. I upped them considerably but maybe I'm not going the right direction for some of them:

-limit-avg=500 -limit-burst=2000 -limit-cache=102400

**Comment by calmh** [comment]
That should allow 50 requests/s on average, which is a few magnitudes higher than what any syncthing produces, yes.

**Comment by CoupeWare** [comment]
I didn't start at 500:-) I will drop it down.

**Comment by CoupeWare** [comment]
So why am I getting the error? It happened with 0.12 also.

**Comment by calmh** [comment]
I don't know, check the suggested debugging above and run discosrv with -debug. We run the same code on the global servers without seeing this issue.

**Comment by calmh** [comment]
Ah, I see there is a forum post as well. Closing and moving there until a bug is uncovered. 

https://forum.syncthing.net/t/discosrv-429-too-many-requests-error/7640
