### ISSUE TITLE
Add field sync-state for REST endpoint /rest/system/connections

### ISSUE THREAD

**Issue by vlcty** [syncthing/syncthing#3313]
From time to time I have some clients which don't sync properly. In the Web-GUI the stuck device has a progress bar labeled "Syncing xx%" above it.

I'd like to have a field for the sync state in the REST endpoint /rest/system/connections. I suggest something like the following:

```
 "connections" : {
          "YZJBJFX-RDBL7WY-6ZGKJ2D-4MJB4E7-ZATSDUY-LD6Y3L3-MLFUYWE-AEMXJAC" : {
             "connected" : true,
             "inBytesTotal" : 556,
             "paused" : false,
             "at" : "2015-11-07T17:29:47.691548971+01:00",
             "clientVersion" : "v0.12.1",
             "address" : "127.0.0.1:22002",
             "type" : "TCP (Client)",
             "outBytesTotal" : 550,
             "sync-state": "the-state"
          }
}
```

The two possible values for "sync-state" could be:

-  in-sync -> Both folder are in sync and are currently idling
- syncing -> Folders are currently syncing

I think the state information is already there because the GUI is already displaying it.

**Comment by calmh** [comment]
The GUI uses https://docs.syncthing.net/rest/db-completion-get.html for the initial status (<100 means "syncing"), then listens for the event https://docs.syncthing.net/events/foldercompletion.html to get continuous updates on the completion status. If you're just checking periodically (every 5-10 minutes or so) polling the completion status in the REST interface should be fine. Does that cover your needs?

**Comment by vlcty** [comment]
Yeah. That cover's everything I wanted :-)
Should have checked the docs better. Sorry for the trouble.
