### ISSUE TITLE
Unknown version of the protocol

### ISSUE THREAD

**Issue by sargelavoie** [syncthing/syncthing#3314]
I have syncthing running on a Windows 10 PC (64 bit), and a Raspberry Pi 2 NFS mounted to a NAS. I recently had a problem with the NAS, so I changed successfully one of my RAID1 disk. Yesterday, I have update both syncthing, and since then, the windows node throw this error message:

"Connecting to ABCDEFG-HIJKLMN-OPQRSTU-VWXYZA-BCDEFGH-IJKLMNO-PQRSTUV-WXYZABC (123.456.789.1:0000): the remote device speaks an unknown (newer?) version of the protocol"

As a consequence, my raspberry pi sees my PC connected and synchronized, but my PC says that my raspberry pi is disconnected.

Any idea?

_Edit 1: Version_

Node A: Windows 10 64 bit
Syncthing version: v0.13.7

Node B: Raspberry pi 2, Linux 4.4.11-v7+ # 887 SMP Thu May 19 16:24:03 BST 2016 armv7l GNU/Linux
Syncthing version: v0.13.7

_Edit 2: Relay_

The previous problem was observed locally. Now that I am at work, my Node A PC seems connected to my node B raspberry pi through relay!!

**Comment by AudriusButkevicius** [comment]
Is the ID in the message of one of your devices?
Also, did you verify that the version is 0.13.7 in the web ui and that you don't have an old instance of syncthing orohaned and running?

**Comment by sargelavoie** [comment]
I have randomized the ID for the post, but since you asked, I have check if this ID corresponded to the actual raspberry ID, and they are not the same! I have thus checked in the log, and here is some additional information:

> Windows 10 ID: JXO3OBJ...
> Raspberry Pi ID: CJSK6U3...
> 
> "Using discovery server https://discovery.../?id=SR7AARM..."
> "Using discovery server https://discovery.../?id=DVU36WY..."
> "Using discovery server https://discovery.../?id=VK6HNJ3..."

> "WARNING: Connecting to VBAV6EC... (0.0.0.0:1234): the remote device speaks an unknown (newer?) version of the protocol

I have also randomized the IP address. In the original error message, the IP is the local raspberry pi address.

Also, both version are 0.13.7, as read from the "About" web ui. 

Thank you for helping.

**Comment by calmh** [comment]
That's something else talking to you then. You might have misconfigured a device to talk to the GUI port, or something else might be connecting to you. I'l reiterate what Audrius already said and point to the forum as this does not look like a bug.
