### ISSUE TITLE
Synology not hibernating

### ISSUE THREAD

**Issue by gpopesc** [syncthing/syncthing#3315]
Hi 

I am using Syncthing for Synology DS216play with latest version installed 0.13.7.
I made un upgrade on 3.06 for syncthing and since then the synology station has not been hibernating anymore. If I stop the service with syncthing, everything is back to normal.

Do you have any idea what might happened?

Gabriel

### Version Information

Syncthing Version: v0.13.7
OS Version: NAS, Synology, DS216play
Browser Version: (if applicable, for GUI issues)

**Comment by calmh** [comment]
You'll need to check what the synology thing uses for criteria for when to hibernate or not. Syncthing does periodic scans and holds network connections open which may be relevant. In either case it's not something we explicitly control in either direction.
