### ISSUE TITLE
When I want to remove a remote machine it returns to reboot of syncthing.

### ISSUE THREAD

**Issue by Lenglemetz** [syncthing/syncthing#3316]
Hi!

I have a strange bug. When I want to remove a remote machine it returns to reboot of syncthing.

Same when I take a shared folder. I restarts syncthing he returns ....

In more detail, I looked in the config.xml, when I do the action "folder or remove the remote machine." syncthing removes good lines in the config.xml until it's OK, but when I restart, syncthing the request, the lines back!

### Version Information

Syncthing Version: v0.13.7
OS Version: Debian Testing

**Comment by calmh** [comment]
I don't understand. Can you explain the steps, and what happens at each along the way?

**Comment by Lenglemetz** [comment]
OK

look > https://youtu.be/ItKkfQIAy3s

it does not matter for the machine ID is dead :-)

**Comment by norgeous** [comment]
yes thanks for the viddy! that helps...
do you have any 'introducer' enabled?
https://docs.syncthing.net/users/config.html#device-element

**Comment by calmh** [comment]
(Also, why do we show the connection error when restarting? That shouldn't happen.)

**Comment by Lenglemetz** [comment]
yes, I have two remote machines initiators, I disabled it and it works. The remote machine disappears well after having remove.

If I understand there will be sport to remove this dead remote machine :)

--------------------------------------

(The connection problem is to reboot a random error. In this video taken after the first I did not error

> https://youtu.be/gIV6dZEstkQ )
