### ISSUE TITLE
Remove call to Google on Syncthing website

### ISSUE THREAD

**Issue by Gitoffthelawn** [syncthing/syncthing#3317]
I apologize in advance if this is not the best place to report this issue.

The Syncthing website current makes a call to `google.com`.  Specifically, it accesses it for this badge: `play.google.com/intl/en-us/badges/images/apps/en-play-badge.png`.

Would it be possible to remove the external call to `google.com` and host that badge directly?

**Comment by calmh** [comment]
Sure. Someone needs to make the change and file a PR on the docs repo.

**Comment by Gitoffthelawn** [comment]
That looks great!  Thanks! :+1:
