### ISSUE TITLE
api: /rest/system/browse on Linux+Mac should return / for empty string

### ISSUE THREAD

**Issue by norgeous** [syncthing/syncthing#3321]
v0.13.7, Linux (ARM)
v0.13.7, Linux (32 bit)

When clicking in the empty `Folder Path` field of the `Add Folder` modal, I would prefer it if the autocomplete could return just '`/`' on linux.

I'm not sure, but I think that currently it provides options for folders that are relative (to the binary?), none of which start with '`/`'. I think it's better to default to absolute paths.

On windows calls to `http://127.0.0.1:8384/rest/system/browse?` returns a list of drives. On linux this should just return the single entry '`/`', or a list of folders in the root directory.

**Comment by calmh** [comment]
Agreed. Empty string should complete to / on non-Windows.

**Comment by norgeous** [comment]
@AudriusButkevicius can you make this happen? I ask bc you helped with the other one #3203...

**Comment by AudriusButkevicius** [comment]
You can probably make a pull request viagithubs web editor.
You need to remove the windows check here:
https://github.com/syncthing/syncthing/blob/master/cmd/syncthing/gui.go#L1137

And make the function return `[]string{"/"}, nil` here:

https://github.com/syncthing/syncthing/blob/master/lib/osutil/drives_unix.go#L12
