### ISSUE TITLE
Using blockstack and syncthing as zeronet - please validate

### ISSUE THREAD

**Issue by piotroxp** [syncthing/syncthing#3323]
Hello community,
I've been using syncthing almost since the start. I've recently come across Sir Tim Berner Lee's account on onename, which is based on blockstack https://github.com/blockstack/blockstack 

"Blockstack is decentralized DNS and identity.
With the Blockstack software, a network of computers collectively maintain a global registry of names."

The nice feature is:
"In the registry that makes up Blockstack, each of the names has an owner, represented by a cryptographic keypair, and is associated with instructions for how DNS resolvers and other software should resolve the name."

So I would propose a zeronet built around these two projects. I personally cannot maintain active coding due to my responsibilites as a designer for the defence industry. I would, however, be interested in helping you and resolving hard problems as I design high power microwave countermeasure devices which required me to explain dark matter (as a sideresult of research regarding). 

I think that such a free, open source, volatile and vibrant community as syncthing's and blockstack's  would mutually benefit from cooperation. 

So what say you, can we rebuild the web?

**Comment by AudriusButkevicius** [comment]
Whats the actual point and benefit?

**Comment by calmh** [comment]
I'm aiming a little lower than rebuilding the web... That said, something like blockstack sounds like it could be useful for a decentralized discovery mechanism. However involving the blockchain and bitcoin into the mix isn't something I think is a good idea so I'd suggest looking for something else for that.

Are you looking for ipfs perhaps? I think it might fulfill most of your requirements, including trying to rebuild the web.

**Comment by piotroxp** [comment]
The "rebuild the web" remark may be an overstatement, however I would definitely find applications for such a technology wrt. military applications. Not only that, but a scientific network of papers built ontop of such an infrastructure would be invaluable to researchers.

**Comment by calmh** [comment]
Syncthing isn't currently designed to scale to large scale deployments - think "circle of friends" rather than "every researcher". While it could be made to scale and maybe do the things you suggest I think it's out of scope for the foreseeable future.

**Comment by AudriusButkevicius** [comment]
Also, ipfs already solves most of this.
