### ISSUE TITLE
Device synchronization percentage doesn't accurately reflect ratio of local to global state.

### ISSUE THREAD

**Issue by Ferroin** [syncthing/syncthing#3325]
Syncthing Version: v0.13.5 and newer, probably on older versiosn too (I've not used anything older than 0.13.5).
OS Version: Appears to be OS independent (I've seen it on at least 3 different Linux distros, two versions of Windows, and Android)

In short, each folder currently counts towards a percentage of being in sync based on how many folders the devices share, and nothing other than the sync percentage of each folder and how many folders there are.  Or, to put it a bit differently, currently, the total sync percentage is an unweighted arithmetic average of the sync percentage of all the folders shared by the device.

Here are a few  examples based on personal observation (these are both situations I've seen, but with the numbers rounded to make the math easier to follow):
1. Assume you have two devices sharing 4 folders, with each folder consisting of 250 1MB files, all of which are completely in sync.  If you then add a new folder on both devices with 1000 1MB files in it, the device with the data will report the remote device as 80% in sync initially, even though it has only half of the global state that it should (measured by either files or data).
2. Similarly, assume you have 2 devices, each sharing a total of 9 folders, with the total global state in those folders being roughly 5 GB.  If you then add a new folder on both devices with 15 GB of data, the device with the data will report the remote device as 90% in sync, even though it only has 25% of the data in from the global state.  Once half the data from the new folder is copied, the device sourcing it will report 95% in sync, even though it actually only has 62.5% of the global state it should measured by data.

This leads to some rather annoying situations (along the lines of 'I'm syncing a big folder to a new device, and it's stuck at 97% synced').  It also means that the sync percentage can't be used as a reliable measure of how long synchronization will take, because the folders count for the same amount of the percentage regardless of how much data they have.

Ideally, this should be computed as a weighted average based on the total global state for each folder being synced between the devices.  If the weighting is based specifically on the total amount of data, then this would also make the sync percentage progress linearly proportionate to the rate of data transfer, which would in turn mean it could be used to get a rough estimate of how long it will take to finish synchronization.

**Comment by AudriusButkevicius** [comment]
There are like 4 older tickets talking about this.
Are you sure that what you are talking about is not covered by them?
