### ISSUE TITLE
GUI broken when deployed behind reverse proxy webserver - hardcoded URLs are not changed by Syncthing

### ISSUE THREAD

**Issue by conrad-heimbold** [syncthing/syncthing#3327]
### Problem

When deploying Syncthing behind a webserver (e.g. nginx or apache) which serves as a reverse proxy at the location <example.com>/syncthing, the 'home' html website of syncthing is displayed; but no extra URLs can be loaded, because these URLs are kind of **hardcoded** and **absolute** in the basic HTML website. 

So as a result, the **complete HTML GUI is broken** and javascript is also not working, so **no information at all can be displayed** and **no interaction is possible**. 

### Basic Problem: 
**syncthing does not know that it is being proxied**, so it **does not alter the hardcoded URLs** in e.g.  <a href="https://github.com/syncthing/syncthing/blob/master/gui/default/index.html">syncthing/gui/default/index.html</a>

### Proof / Evidence: 
In my config.xml file for Syncthing, I wrote (among others): 

    <gui enabled="true" tls="true">
       <address>127.0.0.1:8384/syncthing</address>
        <apikey></apikey>
        <theme>dark</theme>
    </gui>

It does not matter if I add "syncthing" at the end of the URL in between \<address\> and \</address\> or not, the URLs in the final HTML website stay the same. 

Here is an extract from the HTML website I opened when calling it via reverse proxy (it was the same no matter if a added /syncthing as mentioned above or not): 

    <!DOCTYPE html>

    <html lang="en" ng-app="syncthing" ng-controller="SyncthingController" class="ng-cloak">
    <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="assets/img/favicon-{{syncthingStatus()}}.png">
    <link rel="mask-icon" href="assets/img/safari-pinned-tab.svg" color="#0882c8">

    <title ng-bind="thisDeviceName() + ' | Syncthing'"></title>
    <link href="vendor/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="assets/font/raleway.css" rel="stylesheet">
    <link href="vendor/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="assets/css/overrides.css" rel="stylesheet">
    <link href="assets/css/theme.css" rel="stylesheet">
    </head>`

As you can see, there are many kind of hardcoded URLs, linking to folders such as "vendor" or "assets", which have not been accordingly changed by Syncthing...

### Workaround: 
I don't have the possibility to put syncthing into a sub-domain, which could workaround this problem. 

### My Configuration: 
As configuration for Nginx to pass the stuff to Syncthing, I took from https://docs.syncthing.net/users/reverseproxy.html : 

    location /syncthing/ {
      proxy_set_header        Host $host;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;
      proxy_pass              http://localhost:8384/;
    }

### 

### Solution: 
There should be a possibility to tell Syncthing the location to which it is being proxied (for example, in the config.xml file an option named "location" under the top "gui"), so that Syncthing can **alter** the URLs in the HTML files. And the **URLs  should have a placeholder at the beginning** to accomplish that, among others in <a href="https://github.com/syncthing/syncthing/blob/master/gui/default/index.html">syncthing/gui/default/index.html</a> for example. 

### Version Information

Syncthing Version: v0.13.7
OS Version: Raspbian 4.4.11+ ...
Browser Version: both in Firefox, Chrome, etc.

Please correct me if I am wrong with my assumptions!

**Comment by calmh** [comment]
All of our URLs are relative, not absolute as reported, and there are many successful deployments behind reverse proxies.

**Comment by conrad-heimbold** [comment]
But how can I achieve that the URLs are correctly altered?

**Comment by calmh** [comment]
I don't understand why you would need to alter URLs. Lets say you serve the GUI under http://example.com/my/syncthing/index.html. The proxy converts that call to http://127.0.0.1:8384/index.tml. The browser sees http://example.com/my/syncthing/index.html and will call for example http://example.com/my/syncthing/vendor/font/raleway.css, which becomes http://127.0.0.1:8384/vendor/font/raleway.css which works.

**Comment by conrad-heimbold** [comment]
How can I make that rewrite-rule in Nginx or Apache?

**Comment by calmh** [comment]
You nginx configuration does that already. I don't know about Apache.

**Comment by conrad-heimbold** [comment]
Well, let's see if I can find out more about rewrite rules

**Comment by calmh** [comment]
I tried it now to be sure, and your pasted nginx config fragment above works perfectly fine for me out of the box.

**Comment by conrad-heimbold** [comment]
I have got some more nginx configuration in there as well which might cause some problems. My complete nginx config is this, if you want to help me: 

    server  {
        listen                  443 ssl;
        ssl_certificate         /etc/ssl/certs/<...>;                                    
        ssl_certificate_key     /etc/ssl/private/<...>;                                 
        server_name             <...>;
        proxy_set_header     X-Forwarded-For                 $remote_addr;
        add_header              Strict-Transport-Security       "max-age=31536000;      includeSubdomains";
        server_tokens           off;

        location                /syncthing
                                {
                                        auth_basic_user_file    conf/syncthing-passwd;
                                        proxy_pass                  https://localhost:8384/;
                                        proxy_set_header        Host $host;
                                        proxy_set_header        X-Real-IP               $remote_addr;
                                        proxy_set_header        X-Forwarded-For       $proxy_add_x_forwarded_for;
                                        proxy_set_header        X-Forwarded-Proto       https;
                                }
        location                /sabredav
                                {

                                }
        location                /seafile
                                {       fastcgi_pass            127.0.0.1:8000;
                                        fastcgi_param   SCRIPT_FILENAME $document_root$fastcgi_script_name;
                                        fastcgi_param   PATH_INFO              $fastcgi_script_name;
                                        fastcgi_param   PATH_INFO               $fastcgi_script_name;
                                        fastcgi_param   SERVER_PROTOCOL   $server_protocol;
                                        fastcgi_param   QUERY_STRING            $query_string;
                                        fastcgi_param   REQUEST_METHOD          $request_method; 
                                        fastcgi_param           REQUEST_METHOD          $request_method;
                                        fastcgi_param           CONTENT_TYPE            $content_type;
                                        fastcgi_param           CONTENT_LENGTH          $content_length;
                                        fastcgi_param           SERVER_ADDR             $server_addr;
                                        fastcgi_param           SERVER_PORT             $server_port;
                                        fastcgi_param           SERVER_NAME             $server_name;
                                        fastcgi_param           HTTPS                   on;
                                        fastcgi_param           HTTP_SCHEME             https;

                                        access_log              /var/log/nginx/seahub.access.log;
                                        error_log               /var/log/nginx/seahub.error.log;
                                        fastcgi_read_timeout    36000;
                                }
        location                /seafhttp
                                {       rewrite                 ^/seafhttp(.*)$ $1 break;
                                        proxy_pass              http://127.0.0.1:8082;
                                        client_max_body_size    0;
                                        proxy_connect_timeout   36000s;
                                        proxy_read_timeout      36000s;
                                        proxy_send_timeout      36000s;
                                        send_timeout            36000s;
                                }
        location                /seafmedia
                                {       rewrite                 ^/seafmedia(.*)$ /media$1 break;
                                        root                    /var/www/seafile/seafile-server-latest/seahub;
                                }

        location                /
                                {       root                    /var/www/html;
                                        # autoindex             on;
                                        index                   index.html;
                                }
    }


At the moment, I am switching from Seafile to Syncthing; but I would like to use them at the same time...

**Comment by calmh** [comment]
You have a lot of auth stuff. I suggest you look at errors in the browser console and server logs and try to figure out what's going on.

**Comment by conrad-heimbold** [comment]
Thanks for the tip!

**Comment by wweich** [comment]
I use this successfully with apache:
```
ProxyPass /st/ http://127.0.0.1:8384/ retry=0
ProxyPassReverse /st/ http://127.0.0.1:8384/
```
