### ISSUE TITLE
"ACTIVE MALWARE DETECTED" (Kaspersky false alarm!)

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing#3329]
Kaspersky Total Security 16.0.1.445c detected a Trojan Horse inside \AppData\Roaming\Synctrayzor\syncthing.exe.

Trojan Program: Trojan.Win32.Ebowla.ab

**Comment by ProactiveServices** [comment]
False positive
https://forum.syncthing.net/t/kaspersky-treats-syncthing-as-virus/7659

**Comment by calmh** [comment]
I'm going to leave this open for a while for visibility. To be sure, I've built v0.13.7 on a clean Windows VM and binary compared it to the downloaded v0.13.7 from Github. There are a number of one byte differences along the way which is expected, and the sizes are exactly the same. There is no malware in the official v0.13.7 download.

**Comment by calmh** [comment]
Fixed from their side
