### ISSUE TITLE
Restore sequential numbering of event IDs

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#3335]
The new `LocalChangeDetected` event isn't exposed on the events API, but is assigned an ID. This means that events on the events API no longer have sequential IDs, which means it's impossible to detect when events have been skipped.

The wrappers need to hold a lot of local state, and mutate it based on events received. If an event is skipped, all data needs to be reloaded. (The GUI should be doing this as well, so I'm surprised it isn't affected). Therefore we need some mechanism of determining when an event has been skipped. 

Restoring the sequential number of events (by making the ID an API-only concept) would be a simple way of doing this.

**Comment by calmh** [comment]
Could be as simple as

```diff
diff --git a/lib/events/events.go b/lib/events/events.go
index 5d44bb4..8923aef 100644
--- a/lib/events/events.go
+++ b/lib/events/events.go
@@ -255,6 +255,7 @@ func NewBufferedSubscription(s *Subscription, size int) BufferedSubscription {
 }
 
 func (s *bufferedSubscription) pollingLoop() {
+       localID := 1
        for {
                ev, err := s.sub.Poll(60 * time.Second)
                if err == ErrTimeout {
@@ -267,6 +268,9 @@ func (s *bufferedSubscription) pollingLoop() {
                        panic("unexpected error: " + err.Error())
                }
 
+               ev.ID = localID
+               localID++
+
                s.mut.Lock()
                s.buf[s.next] = ev
                s.next = (s.next + 1) % len(s.buf)
```

but I don't have time to test and think it through at the moment.
