### ISSUE TITLE
Not able to delete a non-existent introducer device anymore

### ISSUE THREAD

**Issue by Getron** [syncthing/syncthing#3336]
I have a problem deleting a non-existent anymore introducer device ID.

I have created a new FreeNAS Server, and installing Syncthing on it, configured all ok, and on other FreeNAS Machines, and Desktop device, who has shared this device, i have selected it as introducer.

After a couple of days, i must reinstall the FreeNAS machine, because, i have screewing somthing else.

Reinstalled the FreeNAS, installed the Syncthing plugin, and the Syncthing has now an other Device ID.

But, the problem is, i'm not able to delete this old device ID from other machines. If i deleted it, it stay comming automaticaly on the list. I have tryed everything, but, stay apearing on every machine after couple of minutes, or after restarting the syncthing on this machines (including on Android and desktops)

Have tryed to deselect the synced folder (click on folder, and deselect this old ID), but, it still comming up, apearing.

Maybe we should add some way to be able to kill an old, unusabled, or non-existent device ID.

Any suggestion else, how to delete this non-existent introducer device ID?

**Comment by AudriusButkevicius** [comment]
Please use forum for questions/support requests.

**Comment by Getron** [comment]
@AudriusButkevicius It is a bug, not a question and support asking. It is not possible to delete the an introducer. I deleted it on every machine, and is still apearing, but, should not apearing, if i delete it.

**Comment by calmh** [comment]
It is most likely being re-introduced by another introducer.

**Comment by canton7** [comment]
If a developer tells you it's not a bug, saying "it is a bug" is unlikely to change anything... 

Have you searched the forum and closed issues? The only way this is going to go anywhere is if you find the previous issues, and describe exactly why they do not apply to you.

**Comment by Getron** [comment]
@calmh Yes, but, i have deleted it on every other machines. I have tryed to delete, and shutdown every machine where it was on the list, but, somehow still apearing, every time.

Maybe we should have an option, or somthing, to delete it, if this machine doesn't exist anymore, or this ID doesn't exist, because of reinstalling the PC or server.

**Comment by Getron** [comment]
@canton7 yes, i have searched, but not found anything about this, sorry.

**Comment by AudriusButkevicius** [comment]
It's very simple, just as explained in the numerous forum posts, but I'll repeat myself once again if you insist.

You have 2 or more nodes as introducers, if you remove it from A it gets added back by B, if you remove it from B it gets added by A. 
The only way to actually get it removed is to disable introducer on the peers that still have it. That is - disable A being introducer on B, remove it from B, then remove it from A, maybe reenable introducer.

In general having more than a single introducer makes little sense, as the idea behind it is to have a central node which others follow (for additions, not removals) not a everyone follows everyone and then its impossible to manage.

Also, even If you think it's a bug, next time use the forum, until asked to open a issue on the forum. Also, ideally search closed issues and forum before opening new threads as it's very likely your question was answered before and saves people from having to repeat themselves.

**Comment by Getron** [comment]
Ohh my god.... i have more than 20 introducers and nodes... If i should search all what is where introducer... ohhh...

Why we can not add just a simple "Block this ID" or "Block this device", or "Kill this device" option, and put it on black list, and it will never apear again on this machine this ID, or this device. Simple as that.

But, anyway, i will try to disable introducers, somehow.... and find if i can stop it from apearing again.

One more time, thanks @AudriusButkevicius for explain me this with introducers, i have found copule of posts with this problems, but, i don't think it is a good idea for people who are not "programers", to read all the posts first to be able to do somthing like a blocking, or deleting a device. Maybe, my idea to block, or have an litle check-box after a "Delete" button to block this device on this machine, would many people apreciate this. A simple checkbox can do the great thing.

Anyway, thanks again, and hope you understand the point of this terrible searching machines where is who and where introducers... and it is ok, if all machines are mine, but, if there are people, who share with other friends, family, and so on... oh dear.... it has no chance to stop reintroducing non-existent device ID.

**Comment by AudriusButkevicius** [comment]
Introducer is local, so if your all machines remove introducer from machines that are not yours, it's all good. I guess the strugle you have to go through is because you abused a feature you do not fully understand.

This whole block id business is not as easy, because people make mistakes, and then you are in eternal struggle where they can't add the node anymore. I guess the better option is to read the docs to understand what you are getting yourself into before making some blind assumptions about how a feature works.

**Comment by Getron** [comment]
@AudriusButkevicius i understand that the introducer send the full block with all devices shares the same folders, but, i don't understand, why we can't not add an block system, to set: "If this ID comming up, block it, no matter it comes alone, or in a block from an introducer", that's the point of my idea.

Anyway, i have succesfully deleted this dead ID, but, it take me the full day to figure out, how to do this. Ok, it is possible, but, not an easy step with many introducers, devices... People would appreciate an easy way to block somthing like this. I assume that i'm not the only one that reinstals the machines, and after that have new ID, and the old one keep living, from introducers.

But, ok, thanks for your help, maybe this my idea would implemented somewhere, somehow, like for example, the dark theme, and the people love now this dark theme.

Thanks to devs to helping me.
