### ISSUE TITLE
LTS release or similar

### ISSUE THREAD

**Issue by bosim** [syncthing/syncthing#3339]
I am using syncthing on openSUSE leap. I prefer to use the packages included in the distribution since they are very stable. The upgrade between 0.11 and 0.12 broke the protocol so I requested a update, 0.12 and 0.13 now breaks as well. I will file a bugreport but it is pretty much waste of time updating if you will break the protocol again in the next release. 

Would you consider making the protocol more stable or, providing some kind of LTS releases, making it easier for distributors of long term supported software?

Thanks for your efforts in creating syncthing.

**Comment by AudriusButkevicius** [comment]
The version starts with a zero for a reason. We move fast and break things because we are in beta. If you want stability, wait until 1.0.

**Comment by canton7** [comment]
(There is a currently a move towards better backwards compatibility between minor releases, and better handling of incompatibilities. Promising 100% backwards compatibility or LTS support at this point, where Syncthing is still evolving fast and doesn't have the resources to provide LTS support, would be a mistake however).
