### ISSUE TITLE
Listen address expansion does not respect specified scheme

### ISSUE THREAD

**Issue by xduugu** [syncthing/syncthing#3346]
Thanks to the new feature that displays the discovered addresses in the GUI in syncthing v0.13.8 I found strange addresses in this list for one of my devices.

```
dynamic
relay://<an IPv4 address>:22067
tcp6://<internal IPv4 address>:22000
tcp6://<external IPv4 address>:22000
tcp6://<global IPv6 address>:22000
tcp6://<link local IPv6 address>%<interface>:22000
```

Obviously, the IPv4 addresses with the tcp6:// scheme do not make sense. I checked against the STTRACE=discovery output of 0.13.8 and 0.13.7 and it does not look like an display issue.

The device only has a "dual-stack-lite" connection to the internet, so no direct IPv4 connections are possible (only in LAN). Because of this, the listen addresses of the device are configured as follows:

```
        <listenAddress>dynamic+https://relays.syncthing.net/endpoint</listenAddress>
        <listenAddress>tcp6://:22000</listenAddress>
```

**Comment by calmh** [comment]
What appears to be happening here is the following:

- The listen is correctly on v6 only interfaces
- A global announcement is made, the announced address is `tcp6://:22000` so the discovery server uses the source address as the device address

That works for the v6 case. But the client is apparently also able to access the v4 only discovery servers, presumably via nat64? Or, if it is DSLite as you're describing they will have v4 connectivity but tunneled and possibly NATed. Anyway, the v4 servers get a v4 announcement and dutifully insert the source address, getting a `tcp6://<v4 address>`. Maybe they should be smarter...

**Comment by xduugu** [comment]
Actually, the device is configured for DS-Lite, because it usually has only such a connection, but currently has a complete dual stack connectivity. I don't know if this really makes any difference.

> Anyway, the v4 servers get a v4 announcement and dutifully insert the source address, getting a tcp6://<v4 address>. Maybe they should be smarter...

So, we just need a check if the scheme matches the IP address type in the discosrv [here](https://github.com/syncthing/syncthing/blob/b7e186b370be862479c73bda6e0035eb2a809278/cmd/discosrv/querysrv.go#L333)?

**Comment by calmh** [comment]
Probably yes. Only for the unspecified case, as it's fine to announce an actual IPv6 address over v4 and vice versa.

**Comment by xduugu** [comment]
Just noticed, that this also requires a patch for syncthing, since the local discovery also returns these invalid URIs.
