### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nick-tech** [syncthing/syncthing#3348]
Since the last update to 0.13.8 at every start syncthing exits with this error message:

`root@xyz:/opt/syncthing/config# cat panic-20160626-134529.log
[YME2V] 13:45:13 INFO: syncthing v0.13.8 "Copper Cockroach" (go1.6.2 linux-arm) unknown-user@lx-buildslave.syncthing.net 2016-06-26 10:48:18 UTC
[YME2V] 13:45:13 INFO: My ID: XXXXX-XXXXXX-XXXXX-XXXXXXX
[YME2V] 13:45:14 INFO: Single thread hash performance is ~9.3 MB/s
...
Panic at 2016-06-26T13:45:30+02:00
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x4 pc=0x366bc8]

goroutine 1 [running]:
panic(0x62a920, 0x10d1a030)
        /usr/local/go/src/runtime/panic.go:481 +0x330
sync/atomic.addUint64(0x10dc52ac, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/sync/atomic/64bit_arm.go:31 +0x68
github.com/syncthing/syncthing/lib/db.readWriteTransaction.flush(0x11c0aae0, 0x10dc52a0, 0x11b8d400)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/leveldb_transactions.go:74 +0xbc
github.com/syncthing/syncthing/lib/db.readWriteTransaction.close(0x11c0aae0, 0x10dc52a0, 0x11b8d400)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/leveldb_transactions.go:59 +0x2c
github.com/syncthing/syncthing/lib/db.(*Instance).checkGlobals(0x10dc52a0, 0x10e320c0, 0x6, 0x8, 0x110b57a4)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:643 +0x870
github.com/syncthing/syncthing/lib/db.NewFileSet(0x110a73d8, 0x6, 0x10dc52a0, 0x1130f3d4)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/set.go:104 +0x268
github.com/syncthing/syncthing/lib/model.(*Model).AddFolder(0x10d5c370, 0x110a73d8, 0x6, 0x0, 0x0, 0x11125fe0, 0x1d, 0x0, 0x11095e80, 0x3, ...)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/model.go:1378 +0xf8
main.syncthingMain(0xbe822f0c, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0, 0x6a4088, 0x1, 0x0, ...)
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:688 +0x18f8
main.main()
        /home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:364 +0x748
root@xyz:/opt/syncthing/config#`

Syncthing is running on an arm-Nas machine and did not have any problems so far..

I downgraded manually to 0.13.7 and the error is gone. Is there a way to prevent syncthing from automatically updating? I couldn't find anything in the config file?

**Comment by xduugu** [comment]
I disabled the autoupgrade it in the settings and found this line in config.xml

`<autoUpgradeIntervalH>0</autoUpgradeIntervalH>`

**Comment by aamadorj** [comment]
Same issue described by @nick-tech. I disabled automatic updates for the moment.

**Comment by xduugu** [comment]
This apparently affects all 32-bit builds (see #3347).
