### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dsp77** [syncthing/syncthing#3349]
After upgrading syncthing to 0.13.8 via the `deb http://apt.syncthing.net/ syncthing release` repository I am getting the following panic error:

`panic: runtime error: invalid memory address or nil pointer dereference [signal 0xb code=0x1 addr=0x0 pc=0x8354d4c]`

### Version Information

Syncthing Version: v0.13.8
OS Version: LUbuntu 14.04 / Atom
uname -a: Linux bruegge 3.13.0-88-generic #135-Ubuntu SMP Wed Jun 8 21:10:37 UTC 2016 i686 i686 i686 GNU/Linux

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"

### Log of the panic error

<code>
[ZSKDZ] 13:36:28 INFO: syncthing v0.13.8 "Copper Cockroach" (go1.6.2 linux-386) unknown-user@lx-buildslave.syncthing.net 2016-06-26 10:48:18 UTC
[ZSKDZ] 13:36:28 INFO: My ID: 1234567-7PI35ED-FOR7WZ6-PYLYKU4-TSJ5BKK-JF3DRS7-UFDLYVY-JAFIAF
[ZSKDZ] 13:36:28 INFO: Single thread hash performance is ~35 MB/s
...
Panic at 2016-06-26T13:36:30+02:00
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x8354d4c]
goroutine 1 [running]:
panic(0x861a400, 0x18d0a038)
	/usr/local/go/src/runtime/panic.go:481 +0x326
sync/atomic.AddUint64(0x190aa3ac, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/sync/atomic/asm_386.s:112 +0xc
github.com/syncthing/syncthing/lib/db.readWriteTransaction.flush(0x19295710, 0x190aa3a0, 0x192b6f60)
	/home/buildslave/workspace/syncthing-release-debian/src/github.com/syncthing/syncthing/lib/db/leveldb_transactions.go:74 +0x96
github.com/syncthing/syncthing/lib/db.readWriteTransaction.close(0x19295710, 0x190aa3a0, 0x192b6f60)
	/home/buildslave/workspace/syncthing-release-debian/src/github.com/syncthing/syncthing/lib/db/leveldb_transactions.go:59 +0x31
github.com/syncthing/syncthing/lib/db.(*Instance).checkGlobals(0x190aa3a0, 0x19332f00, 0x7, 0x8, 0x18e975c4)
	/home/buildslave/workspace/syncthing-release-debian/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:643 +0x989
github.com/syncthing/syncthing/lib/db.NewFileSet(0x190c5348, 0x7, 0x190aa3a0, 0x18e3150c)
	/home/buildslave/workspace/syncthing-release-debian/src/github.com/syncthing/syncthing/lib/db/set.go:104 +0x273
github.com/syncthing/syncthing/lib/model.(*Model).AddFolder(0x190ba000, 0x190c5348, 0x7, 0x0, 0x0, 0x18e530c0, 0x13, 0x0, 0x18e92100, 0x5, ...)
	/home/buildslave/workspace/syncthing-release-debian/src/github.com/syncthing/syncthing/lib/model/model.go:1378 +0x11a
main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8698e04, 0x1, 0x0, ...)
	/home/buildslave/workspace/syncthing-release-debian/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:688 +0x18d2
main.main()
	/home/buildslave/workspace/syncthing-release-debian/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:364 +0x7d7
</code>
----

**Comment by AudriusButkevicius** [comment]
Dup

**Comment by calmh** [comment]
Wait, what? Now I'm confused
