### ISSUE TITLE
sleep/standby on gnomeshell

### ISSUE THREAD

**Issue by nattyebola** [syncthing/syncthing#3352]
on gnome shell 3.18/3.20:  when syncthing is started and That a transfer is in progress , it should disable the machine standby/sleep.

Syncthing Version: v0.13.7
OS Version: Ubuntu 16.04
Browser Version: N/A

**Comment by AudriusButkevicius** [comment]
It's for gnome shell to do that. Syncthing is cross platform, and we'll not wedge in desktop env specific stuff.
