### ISSUE TITLE
Upgrade unsupported

### ISSUE THREAD

**Issue by tarbib** [syncthing/syncthing#3359]
Hi,

I cannot upgrade syncthing on my VPS running 
~# syncthing -upgrade
21:45:57 FATAL: Upgrade: upgrade unsupported

Here are my vps info :
Linux 2.6.32-45-pve #1 SMP Wed Mar 30 12:22:08 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

And syncthing version
:~# syncthing -version
syncthing v0.13.7 "Copper Cockroach" (go1.6.2 linux-amd64) unknown-user@lx-buildslave.syncthing.net 2016-06-13 16:06:12 UTC

Thanks !

**Comment by wweich** [comment]
How did you initially install Syncthing?
It seems you are using the apt package or something like that. In that package the internal upgrade is disabled, because the package manager has to handle the upgrades.

**Comment by tarbib** [comment]
That was the reason!

I just used sudo apt-get install syncthing and it worked.

Then it would nice to have -upgrade-check to say that an "upgrade is
available but internal upgrade is disabled" not just say :
~# syncthing  -upgrade-check
00:48:54 FATAL: Upgrade: upgrade unsupported

Thanks!

On 28 June 2016 at 12:02, Wulf Weich <notifications@github.com> wrote:

> How did you initially install Syncthing?
> It seems you are using the apt package or something like that. In that
> package the internal upgrade is disabled, because the package manager has
> to handle the upgrades.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/syncthing/syncthing/issues/3359#issuecomment-228942427>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACJqSQ6YlLJ48q0zTQkbTGsiJqwjTm-4ks5qQJzXgaJpZM4I_qrF>
> .
>



-- 

Thomas Arbib

France : +33 (0)6 30 66 72 25
中国手机 : +86 150 6616 3405

Twitter : @tarbib <http://twitter.com/tarbib>
微信 (WeChat) ID : tarbib

http://about.me/thomasarbib

**Comment by calmh** [comment]
An upgrade may not be available, depending on the package system. And upgrade checking itself may be disabled for privacy reasons. I think it's ok as is.
