### ISSUE TITLE
Persistently removing remote devices?

### ISSUE THREAD

**Issue by ktaylora** [syncthing/syncthing#3361]
I have a few machines that I had previously installed syncthing on and added as devices to shared folders.  Those machines are no longer around or in use and I would like to remove them as remote devices.  However, when I remove them they are automatically being added back by other introducers using those same shared folders.  Is there a way to add a device ID to a blocklist so that syncthing client doesn't attempt to re-add a host that's been removed?

**Comment by calmh** [comment]
Currently, no. Remove them on the introducers first, and probably having only a single introducer is simplest.

**Comment by AudriusButkevicius** [comment]
So I am closing this as it's a question, and I think there already exists a ticket with the same idea.
