### ISSUE TITLE
TestGithubRelease fails on arm64

### ISSUE THREAD

**Issue by aviau** [syncthing/syncthing#3362]
TestGithubRelease fails on arm64.

See the log:
```
=== RUN   TestGithubRelease
--- FAIL: TestGithubRelease (0.01s)
	upgrade_test.go:83: Error retrieving latest version couldn't find a release to download
	upgrade_test.go:86: Invalid upgrade release: v0.10.0-alpha -> v0.10.30, but got 
	upgrade_test.go:83: Error retrieving latest version couldn't find a release to download
	upgrade_test.go:86: Invalid upgrade release: v0.10.0-beta -> v0.10.30, but got 
	upgrade_test.go:83: Error retrieving latest version couldn't find a release to download
	upgrade_test.go:86: Invalid upgrade release: v0.11.0-beta0+40-g53cb66e-dirty -> v0.11.0-beta0, but got 
	upgrade_test.go:83: Error retrieving latest version couldn't find a release to download
	upgrade_test.go:86: Invalid upgrade release: v0.10.21 -> v0.10.30, but got 
	upgrade_test.go:83: Error retrieving latest version couldn't find a release to download
	upgrade_test.go:86: Invalid upgrade release: v0.10.29 -> v0.10.30, but got 
```

[Full log](https://buildd.debian.org/status/fetch.php?pkg=syncthing&arch=arm64&ver=0.13.9%2Bdfsg1-1&stamp=1467204073) is available in the Debian CI website.

See the status of Syncthing builds on other architectures [here](https://buildd.debian.org/status/package.php?p=syncthing).

Related Debian bug: [#828808](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828808)

**Comment by calmh** [comment]
Yeah, it uses actual data from an old GitHub API response for the tests, and there were no arm64 releases at that point. I suggest just scrapping that test and the corresponding test data as I don't think it exercises anything relevant that TestSelectedRelease doesn't also.
