### ISSUE TITLE
Should folder labels be locally unique?

### ISSUE THREAD

**Issue by xduugu** [syncthing/syncthing#3367]
Currently, syncthing allows to use the same label for more than one folder. Since some [projects](https://github.com/syncthing/syncthing-inotify/issues/115) are thinking of using the label as folder identifier to improve usability, maybe it should be decided if the label qualifies as unique identifier or not.

The [documentation](https://docs.syncthing.net/users/config.html#folder-element) says:
```
label
    The label of a folder is a human readable and descriptive local name. Can be different on each device. (optional)
```

The goal of this issue is to either
* update the documentation and explicitly state that the folder label is not guaranteed to be unique or
*  add a check to syncthing which prevents the re-use of an existing folder label (empty folder labels should still be allowed).

I don't see an use-case that requires identical folder labels, but a source of possible confusion. Therefore, I would require them to be either locally unique or empty.

**Comment by calmh** [comment]
Folder labels can be empty, unique, non-unique, or consist entirely of emoji. We make no judgement here. Using the same label for every folder would indeed be confusing, but it's allowed by the protocol and config.

**Comment by AudriusButkevicius** [comment]
You can't type emoji on the console usually, so using labels for inotify is a bad idea to start with. I think they should not need to be unique.

**Comment by calmh** [comment]
Anything talking API with us needs to specify the folder ID of course, but how it's chosen on the other side is a UI decision for them I guess? I wouldn't recommend *saving* the folder label somewhere outside Synthing as the label can change at any time while the ID cannot, but presenting a list of folder labels to choose from and then saving the corresponding ID seems sane. If the labels are non-unique the UI should probably disambiguate them some way, or just complain that the user is being inconvenient and annoying.

Also, ye of little faith:

<img width="788" alt="screen shot 2016-06-30 at 13 09 40" src="https://cloud.githubusercontent.com/assets/125426/16486297/1e90492c-3ec4-11e6-8d5b-fe240b1b3033.png">

**Comment by xduugu** [comment]
This issue is just about the config, the protocol shouldn't be involved.

The question in the case of syncthing-inotify is if it is possible to always map a given folder label to a single folder id. According to your answers, this shouldn't be guaranteed. So, adding a sentence to the documentation should be enough.

> You can't type emoji on the console usually, so using labels for inotify is a bad idea to start with. I think they should not need to be unique.

I think it is not meant as a replacement for the folder IDs, just an addition.

**Comment by calmh** [comment]
Indeed there should be no expectation of the mapping between ID and label being neither unique nor consistent from one second to the next.
