### ISSUE TITLE
Proper font missing

### ISSUE THREAD

**Issue by Stemby** [syncthing/syncthing#3368]
Debian Bug: [#829090](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829090)

> I see only one issue, the web UI font is odd, some glyphs are missing.
> 
> Tracing reveals there are multiple calls to the path
> 
>  /vendor/font-awesome/fonts/fontawesome-webfont.woff2
> 
> ending with 404 Not Found. 

### Version Information

Syncthing Version: v0.13.9
OS Version: Debian Sid

**Comment by aviau** [comment]
Looking at it I think this is a Debian bug, not an upstream bug. I have probably forgot to copy the missing font from the debian-provided fontawesome package.

**Comment by calmh** [comment]
Cannot reproduce:

```
jb@syno:~ $ curl -I http://127.0.0.1:8082/vendor/font-awesome/fonts/fontawesome-webfont.woff2
HTTP/1.1 200 OK
Content-Length: 66624
Set-Cookie: CSRF-Token-MRIW7=3hodds9QwEfs4NzUaKyMuWnKhz2EFE6u
X-Syncthing-Id: MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC
X-Syncthing-Version: v0.13.9+11-g8907d4f-dirty-protobufs
Date: Thu, 30 Jun 2016 14:20:56 GMT
Content-Type: application/octet-stream
```

**Comment by calmh** [comment]
Ah. Allright.

**Comment by aviau** [comment]
This is fixed in syncthing_0.13.9+dfsg1-3 which I have just uploaded to Debian.
