### ISSUE TITLE
Select what files to download

### ISSUE THREAD

**Issue by LucasRoot** [syncthing/syncthing#3369]
When downloading a folder, would be nice to have a tool for me to select what files I want to download, instead of downloading the entire folder.

Thanks a lot!

**Comment by AudriusButkevicius** [comment]
There are three parts to this.

First if you just want to download a file once, syncthing is probably not the best tool.

Secondly, you can already pick what to sync using ignores.

Thirdly, there is already an old ticket for making a picker so you could visually select stuff, and if that is what you are after, it's a duplicate.
