### ISSUE TITLE
include the whole docs source in the release tarball

### ISSUE THREAD

**Issue by aviau** [syncthing/syncthing#3372]
The issue title is a suggestion, but maybe my problem could be fixed in another way.

I would like to ship a ```syncthing-docs``` package, I would build the rst docs to html and put them in /usr/share/docs/...

**Comment by calmh** [comment]
Pull the docs repo and do this?

**Comment by aviau** [comment]
I could, but then could we also tag the docs repo at the same time as syncthing? I want to make sure that they both match.

**Comment by calmh** [comment]
Yes, I can do that. I even did at some point previously, but then lapsed as it was unused.

**Comment by calmh** [comment]
I thought before that I wanted to include the docs repository in the main repo to get this automatically, but I currently don't want that.

**Comment by xduugu** [comment]
I don't think it makes sense to package anything other than the latest commit. Even if the docs repository would be tagged, a tag means nothing since the documentation currently lags behind the actual syncthing release.

**Comment by calmh** [comment]
Agreed that the latest docs are probably the best, much like the latest code is the best. But if you're packaging anything it's good to have a version number on it to know what was packaged and when. If the docs are to be packaged it makes sense for them to be packaged in lockstep with Syncthing proper, and it's no hardship to create corresponding tags on both repos in parallel.

**Comment by calmh** [comment]
I'm working under the assumption that @aviau would notice "hey, a new Syncthing release!" the day after we make it or so, and then grab v0.14.97 of both code and docs, which probably points to the latest master in both repos at that point.

**Comment by calmh** [comment]
Anyway. I commit to tag the docs repo. Done/done.
