### ISSUE TITLE
feature request. Partial backup options.

### ISSUE THREAD

**Issue by Losiara** [syncthing/syncthing#3373]
Would be perfect if it is possible to backup files with partial algorithm like git-bup or zbackup. So linked with git, it could be nicest backup system almostly out of the box. I suppose it shouldn't crush basic syncthing idea. Thanks.

**Comment by calmh** [comment]
What does a "partial algorithm" mean?

**Comment by Losiara** [comment]
From git bup description
"... providing fast incremental saves and global deduplication ..."

**Comment by calmh** [comment]
I think Synchting already does that, actually.

**Comment by Losiara** [comment]
I suppose that there simple file versioning(copies), but not deduplicating of for example changed binaries. What if i have 300 mb image and changed it a little, there would be two versions and 600 mb, but with dedupliction it would be 300 +- 1-3 mb. Or may I wrong?

**Comment by calmh** [comment]
No, you're right. But we're dealing with files directly accessible by the user, both the ones we sync and the ones we version away. Git uses a repository with a specific format that can only be accessed using the git tools. So I think that kind of deduplication is not for us.

**Comment by Losiara** [comment]
Suppose misunderstanding between us. We no need to integrate git format in syncthing. We just need to place some folder or files in special status. When remote comp changed file local syncthing not places all new file but just saves incremental(deduplicated) bitset in special "backup folder" and thats all. And with a help of git we can control these versions separatly. Would be perpect cross-platform backup tool. And not hard to implement I think.

**Comment by calmh** [comment]
Yeah, I understand you. But that deduplicated file wouldn't be accessible to the user without some special tool to piece it together from the data we saved. I don't want that.

However there is a potential extension in the future in #3058, which will improve the external versioner. The thing there is that the "versioning" is handled by an external command, which could be to move the file to a git repo and do the commit. You would then get versioning with deduplication into a git repo.

More than that, I don't think this is something we will implement.

**Comment by Losiara** [comment]
Ok. Thank you for syncthing.

**Comment by AudriusButkevicius** [comment]
Also, syncthing is not for backups, as deleting a file will delete it from the backup.
