### ISSUE TITLE
Transport-Mode

### ISSUE THREAD

**Issue by fablue** [syncthing/syncthing#3374]
Hey. I'm new here and not quiet sure if such a suggestion is placed right here. I'm sorry if not. 

I'm using Syncthing for quiet a while now and i love it. Since i'm using it to synchronize my home-servers i came to a problem because one of those servers is connected to a very slow internet connection while containing 1TB of data. Obviously this isnt a good condition for syncing to the other server (which indeed is connected to a very fast internet connection). So what i am doing now is using my laptop as some kind of intermediate. My laptop syncs to the slow server over lan (if i'm at home) and syncs those data to the other server if i'm in the second home network. This works great and is (so i guess) the only way to achieve this. 

Downside: I have to carry all the data on my laptops hdd (all the time). I would suggest a very cool solution with some kind of 'caching', 'transport mode'. Maybe the laptop could just sync the data, which aren't synced with all other computers. 

This would solve many problems for people having bad internet connections. 

For example:It would take days 'uploading' if adding a large file (say a Movie (6GB) or something) while having a slow internet connection. But it would be very cool if your smartphone might sync this file  from the local network and spread it to all other devices when connected to a faster network (university, work, etc). 

So i hope i could explain what this idea is.

**Comment by AudriusButkevicius** [comment]
I think this is out of scope of syncthing.
