### ISSUE TITLE
chmod and chgrp leads to "unknown user"

### ISSUE THREAD

**Issue by narcozen** [syncthing/syncthing#3391]
When I try to change the file-Permission (chmod) or the group (chgrp) in a syncronized directory, this leads to an unreadable direcory:  file-names remains visible, but user-group-and attributes are marked as "unknown" in the browser (nemo) and same with ls -l on the cmd-line. Even admin (root) can anymore handle the files.

This happens with 0.13.10 (and before)
on Linux Mint Debian Edition and Linux Mint Ubuntu Edition

**Comment by AudriusButkevicius** [comment]
Syncthing does not touch ownership, and does not modify ownership, so this is impossible.
i am sure chmod works as expected, as we'd have thousands complainong.

Also, I suggest you check things in the console, as syncthing cannot be held responsible for a broken file manager
