### ISSUE TITLE
Exception when trying to add a device.

### ISSUE THREAD

**Issue by avuton** [syncthing/syncthing#3392]
Bug: Crash when trying to add a device. This is broken in 0.7.21 from F-Droid, not broken in 0.7.20 from F-Droid. This can be reproduced every time.

### Version Information

Syncthing Version: v0.7.21
OS Version: Android
<pre><code>
07-06 10:45:13.809 13327 13327 D AndroidRuntime: Shutting down VM
07-06 10:45:13.810 13327 13327 E AndroidRuntime: FATAL EXCEPTION: main
07-06 10:45:13.810 13327 13327 E AndroidRuntime: Process: com.nutomic.syncthingandroid, PID: 13327
07-06 10:45:13.810 13327 13327 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.SettingsActivity}: android.view.InflateException: Binary XML file line #49: Binary XML file line #49: Error inflating class EditText
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5422)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #49: Binary XML file line #49: Error inflating class EditText
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at com.nutomic.syncthingandroid.fragments.DeviceFragment.onCreateView(DeviceFragment.java:203)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.app.Fragment.performCreateView(Fragment.java:2220)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.app.BackStackRecord.run(BackStackRecord.java:793)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.app.FragmentController.execPendingActions(FragmentController.java:325)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:6267)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	... 9 more
07-06 10:45:13.810 13327 13327 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #49: Error inflating class EditText
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	... 19 more
07-06 10:45:13.810 13327 13327 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_tag_text_outline_black_24dp.xml from drawable resource ID #0x7f020077
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2603)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.content.res.Resources.loadDrawable(Resources.java:2503)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.content.res.TypedArray.getDrawable(TypedArray.java:870)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.widget.TextView.<init>(TextView.java:881)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.widget.EditText.<init>(EditText.java:64)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.widget.EditText.<init>(EditText.java:60)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:60)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:56)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:112)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:1008)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1067)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	... 25 more
07-06 10:45:13.810 13327 13327 E AndroidRuntime: Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #4: <item> tag requires a 'drawable' attribute or child tag defining a drawable
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:182)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:115)
07-06 10:45:13.810 13327 13327 E AndroidRuntime: 	at androi
07-06 10:45:13.812  4425  6415 W ActivityManager:   Force finishing activity com.nutomic.syncthingandroid/.activities.SettingsActivity
07-06 10:45:13.814  4425  6415 W ActivityManager:   Force finishing activity com.nutomic.syncthingandroid/.activities.MainActivity</code></pre>

**Comment by AudriusButkevicius** [comment]
Wrong repo

**Comment by calmh** [comment]
Try the syncthing/syncthing-android repository.

**Comment by avuton** [comment]
apologies/thanks :+1:
