### ISSUE TITLE
Reloading ignores is hugely inefficient

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3394]
We reload the ignores before each folder scan. This involves parsing and compiling the ignore patterns. If there are a lot of patterns that can be expensive. If running with syncthing-inotify we might get a lot of scan requests.

We should just check the .stignore file timestamp and not do anything unless it's changed.

It's a mystery to me why we don't already do this. I must have been drunk when I wrote this (or reviewed it, if someone else is responsible. I forget.).

**Comment by DrSchnagels** [comment]
Hijacking this thread, sorry.
I often see that my android devices simply forget about the ignores. Everything gets synced and has to be manually deleted on the other devices.
And in the preferences of folders i cant save the ignore file. I get an access error.

**Comment by AudriusButkevicius** [comment]
Please don't highjack. The error is somewhat obvious and is related to android hence should be raised kn thr android repo. I suspect because you enabled running with root sometime ago, or because you are running on external storage to which syncthing doesn't have write access

**Comment by calmh** [comment]
For the record, it's not just

> We should just check the .stignore file timestamp and not do anything unless it's changed.

as we also have included files and included files in included files etc that need to be checked.

**Comment by hashworks** [comment]
I guess it would be sufficient to save the timestamp of all included files, as soon as one of them changes there could be new included files.

**Comment by guillaume-uH57J9** [comment]
Thanks for working on the idle performance! 
By default, scanning occurs every 60 seconds, so I'm guessing it'd improve a bit the idle performance of scanmem.
