### ISSUE TITLE
Supposedly "FATAL" messages in OSX about "no home directory found"

### ISSUE THREAD

**Issue by dotwaffle** [syncthing/syncthing#3395]
I recently noticed logs were being emitted, and I don't know why. I reinstalled syncthing and syncthing-inotify and it didn't change anything. Here's a quick rundown of what I did:

I looked in console and saw:

08/07/2016 12:44:08.424 com.apple.xpc.launchd[1]: (homebrew.mxcl.syncthing[5100]) Service exited with abnormal code: 1
08/07/2016 12:44:08.424 com.apple.xpc.launchd[1]: (homebrew.mxcl.syncthing) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.

Strange... I looked in the logfile and saw:
12:43:48 FATAL: No home directory found - set $HOME (or the platform equivalent).
12:43:58 FATAL: No home directory found - set $HOME (or the platform equivalent).
12:44:08 FATAL: No home directory found - set $HOME (or the platform equivalent).
12:44:18 FATAL: No home directory found - set $HOME (or the platform equivalent).
12:44:28 FATAL: No home directory found - set $HOME (or the platform equivalent).
12:44:38 FATAL: No home directory found - set $HOME (or the platform equivalent).

The service was installed with homebrew:

10:51:00 [mwalster@mwmbp:~] % brew info syncthing
syncthing: stable 0.13.10 (bottled), HEAD
Open source continuous file synchronization application
https://syncthing.net/
/usr/local/Cellar/syncthing/0.13.10 (6 files, 14.8M) *
  Poured from bottle on 2016-07-08 at 10:41:33
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/syncthing.rb
==> Dependencies
Build: go ✔
==> Caveats
To have launchd start syncthing now and restart at login:
  brew services start syncthing
Or, if you don't want/need a background service you can just run:
  syncthing
10:51:03 [mwalster@mwmbp:~] % brew info syncthing-inotify
syncthing-inotify: stable 0.8.2 (bottled), HEAD
File watcher intended for use with Syncthing
https://github.com/syncthing/syncthing-inotify
/usr/local/Cellar/syncthing-inotify/0.8.2 (3 files, 6.8M) *
  Poured from bottle on 2016-07-08 at 10:32:53
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/syncthing-inotify.rb
==> Dependencies
Build: go ✔, godep ✔
==> Caveats
To have launchd start syncthing-inotify now and restart at login:
  brew services start syncthing-inotify
Or, if you don't want/need a background service you can just run:
  syncthing-inotify
10:51:08 [mwalster@mwmbp:~] %

Both services were configured in launchd by using the homebrew "brew services start syncthing" method rather than configuring in launchctl directly.

Is this a homebrew fault, or something integral to syncthing that I've misconfigured somehow?

Happy to help debug where possible.

### Version Information

Syncthing Version: v0.13.10
OS Version: OSX 10.11.5
Browser Version: n/a

**Comment by AudriusButkevicius** [comment]
Well the error is obvious, and what needs changing is obvious too. I do not know if its your fault or brews fault, but it's definately not syncthings fault. I suggest you follow up with brew people or try running it from a fresh terminal.

**Comment by calmh** [comment]
This is a brew bug. Our launchd file [contains the setting](https://github.com/syncthing/syncthing/blob/master/etc/macosx-launchd/syncthing.plist#L19) for `$HOME`, [theirs doesn't](https://github.com/Homebrew/homebrew-core/blob/master/Formula/syncthing.rb#L30).

**Comment by dotwaffle** [comment]
Ah, thank you. Imagine my lack of surprise ;)

I'll see if I can figure out how to submit a change. Thanks for pointing out the specific section too!
