### ISSUE TITLE
Formatting issue in Anonymous Usage Reporting Preview

### ISSUE THREAD

**Issue by dzarda** [syncthing/syncthing#3397]
This is a trivial GUI issue.
In `Settings` -> `Preview`, the _Anonymous Usage Reporting_ modal view has a slight issue with not interpreting the `<a>` intended to show the link. The `<a href=...` construct is left visible and no clickable link is present.
The `<p>` in question is shown here.

`<p translate="" translate-value-url="<a href=&quot;https://data.syncthing.net&quot; target=&quot;_blank&quot;>https://data.syncthing.net</a>" class="ng-scope">The aggregated statistics are publicly available at &lt;a href="https://data.syncthing.net" target="_blank"&gt;https://data.syncthing.net&lt;/a&gt;.</p>`

It seems that the inner text content escapes the `<>` into `&lt;&gt;`

Syncthing Version: v0.13.10
OS Version: Debian stretch/sid
Browser Version: Both Chromium 51 and Firefox 45

**Comment by uok** [comment]
Thanks for reporting! Please close as this is fixed in v0.14 (see #3204)

**Comment by calmh** [comment]
That fix is in 0.13.5+ though.

**Comment by xduugu** [comment]
Commit 9d75652 fixed `gui/default/syncthing/usagereport/usageReportModalView.html`, but not the Preview in `gui/default/syncthing/usagereport/usageReportPreviewModalView.html`.
