### ISSUE TITLE
Syncthing in debian testing

### ISSUE THREAD

**Issue by Lenglemetz** [syncthing/syncthing#3403]
Hi,

syncthing just arrived in debian testing, but the debian release overwrites the syncthing version syncthing.net during an update.

For now ... the version of Debian is less successful than your version ...

- Change font
- No reboot of syncthing after the update

My question, are you there opportunities to improve that? renaming the package such syncthing-0.13.
This is an example, virtualbox proceeds like this

**Comment by wweich** [comment]
[Pinning](https://wiki.debian.org/AptPreferences#Pinning) the `apt.syncthing.net` version should fix that.
Something like this should work (not tested):
```
Package: syncthing
Pin: release o=apt.syncthing.net
Pin-Priority: 1000
```

**Comment by AudriusButkevicius** [comment]
There is not much we can do as it's decisions made by debian people and not us, hence the bug should be opened on the debian bug tracker.

Regardless, cc @aviau who worked on this.

**Comment by Lenglemetz** [comment]
@AudriusButkevicius So why have your repo debian if you know for a fact that it will be crushed by debian ...

**Comment by AudriusButkevicius** [comment]
I don't understand the question. The debian apt repo and how its built etc etc, is out of our control. Our own apt repo predates syncthing being availablr via standard debian channels. Yes, we should probably kill it once it makes it into stable, but for now it's staying as not everyone lives on the edge like you.

**Comment by Lenglemetz** [comment]
why not simply adapt? so that people can have a choice as virtualbox?

**Comment by AudriusButkevicius** [comment]
In our own case, we could, but our repo will be killed sooner or later so I am not sure it's worth the effort. Also, I am not sure if debian will automatically perform upgrades from let's say 0.13.11 to 0.13.12 if package names are actually different. I suspect it won't, essentially pegging which version the user has installed, and apt-upgrade never actually upgrading to the latest and greatest version (which is not what we want).

In debian's case, it's out of our control.

**Comment by Lenglemetz** [comment]
Therefore adapt your repo, it will pass it to you when syncthing (eg on debian stable server) will increase from 0.13 to 0.14. Debian will steady the update?

The windows / mac versions will be updated but perhaps not the debian / ubuntu server. As administrator what do we do, we wait until the next stable Debian?

**Comment by AudriusButkevicius** [comment]
So I am struggling to understand you, what do you mean by "it will pass it to you".

The stable branch does not change, but stable-updates and standard distribution updates still get delivered.

It's inevitable that brew on osx, debian etc etc will all have separate release cycles. If you want to avoid the gaps that will be created by different packagers, use github releases (potentially with your own upgrade server if you want to control when you upgrade).
If you

**Comment by Lenglemetz** [comment]
I am not sure that we understand well.

I wonder if the breaks between (for example) 0.13, 0.14 or 0.15 ... will be provided by Debian Stable

**Comment by Ferroin** [comment]
Alternatively, do like was originally done for all software on UNIX, and just build it locally.  Nothing depends on Syncthing in any package manager, and as long as you have the dependencies installed, it's not hard to do.

**Comment by Lenglemetz** [comment]
@Ferroin : I think I'll do this ....

**Comment by aviau** [comment]
Hey!

If there are any issues with the syncthing package, please let me know. The Debian bug tracker would be the right place for this.

AFAIK the fonts issue is fixed in the newest version.

Also, I agree that my package could/should reboot syncthing after an upgrade. I'll do that for the next release.
