### ISSUE TITLE
Interface irritation

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [syncthing/syncthing#3404]
On adding folders or devices (using the web UI for either of those functions) a window appears (on both Windows 8.1 and Linux Mint 17.3) that (1) has no close button, (2) closes when one clicks outside of it.

1 means that I can't close the window in the way to which I am used,
2 means that often I close the window by accident.

How about giving the window a proper close button and removing the close-on-click-outside feature?

Thanks.

Also: where does one find an explanation, please, for the icons shown next to the devices?

(I am using Firefox 47 on both systems.)

**Comment by AudriusButkevicius** [comment]
It has an X in the corner, and closing by clicking outside of a dialog is quite normal for bootstrap UI's and I believe even had an issue raised by someone requesting to enable that, so it's all a matter of preference.

**Comment by AudriusButkevicius** [comment]
Also, I have no idea what you mean by icons next to devices. If you mean the identicons, then look at your own github icon, and try finding where github explains what that means.

**Comment by ACinnamonUserInUK** [comment]
There is no 'x' in the corner for me, I am afraid. I attach a screenshot of (1) Windows 8.1, (2) Linux Mint 17.3.

(1)
![1 - screenshot windows](https://cloud.githubusercontent.com/assets/9998846/16816786/90fa1fb0-4937-11e6-9567-a81a3027321d.png)

(2) 
![2 - screenshot linux](https://cloud.githubusercontent.com/assets/9998846/16816870/f7a08ad8-4937-11e6-9b2b-b1e162acfe01.png)

As to the icons: I think they are called 'identicons'; I'll investigate. Thanks.

**Comment by AudriusButkevicius** [comment]
but there is a close button in the bottom though, so not sure I understand your point.

**Comment by ACinnamonUserInUK** [comment]
Oh. So it does. When you said, before, that there's a close button 'in the corner', it was natural for me to look to the *top* of the window. So, OK, that functionality is there; it's just that I (and many others) are not used to it (and to the window closing when one clicks outside of the window).

So I've been hasty - though I note that had the window conformed to my expectations, there'd have been no difficulty at all. (Also, had I managed to get Syncthing working once and for all, I wouldn't be spending so much time in its configuration windows - and perhaps it is that amount of time that gives me a short fuse with the interface! Anyhow, thank you for your help.)
