### ISSUE TITLE
Pause should be permanent 

### ISSUE THREAD

**Issue by tobiastom** [syncthing/syncthing#3407]
When I pause a device, and restart synching, the pause is removed and the devices are used to share files agin.

I would expect it to be permanent until I press the continue button.

**Comment by calmh** [comment]
Maybe. "Pause" feels temporary to me. "Disable" would sound more permanent?

**Comment by xduugu** [comment]
"Disable" is probably what we want. Is there anything than can be done with "pause", but not with "disable"?

The only use case I can think of is pausing all devices when changing to a "metered" connection. In this case the disable/pause flag should not persist. But I would consider this a hack to work around a missing "pause all connections" feature in syncthing.

Interestingly, there exists also the opposite behaviour to the reported one in syncthing. When syncthing is started using the `-paused` option and some devices are manually resumed before syncthing is restarted, all devices are paused again after the restart.

**Comment by tobiastom** [comment]
Disable is very fine with me. :)

**Comment by Revertron** [comment]
But if we use the word "pause" may be we could use the word "stop" for "permanent pausing"?

**Comment by tobiastom** [comment]
Sorry for the late reply. Works perfectly for me.

Thank you everyone.
