### ISSUE TITLE
Reset folder index from GUI

### ISSUE THREAD

**Issue by xduugu** [syncthing/syncthing#3408]
The REST API provides the possibility to erase the index data for a specific folder[[1]](https://docs.syncthing.net/rest/system-reset-post.html). There are issues where an index rebuild is the easiest option to solve these. I think a "Rebuild index" button in the edit folder modal or the advanced configuration (however, it is no configuration) could be useful sometimes.

The actual use case where I needed this functionality was an `Out of Sync` error because of editing .stignore. I've added an ignore pattern that matched already synced files, removed these files after a rescan which led to the `Out of Sync` error. Clearing the index for this folder fixed it.

**Comment by AudriusButkevicius** [comment]
Restarting fixes this too.

**Comment by calmh** [comment]
Regardless, we should fix whatever situation requires resetting the index rather than making it easier to do so. So I'm going to close this, but I welcome issues with steps to reproduce a situation that requires index reset, and will attempt to fix that as a bug.

**Comment by xduugu** [comment]
> Restarting fixes this too.

Good to know. Maybe that actually fixed it and not the rebuild. I couldn't find an issue that describes the problem above. Should I open one or is this behaviour well-known/expected?

@calmh 
What is the intention behind the REST endpoint then? Is it meant just for debugging/testing if you expect it never to be used?

**Comment by calmh** [comment]
I don't actually remember the real use case any more.
