### ISSUE TITLE
gui: Refresh loop can start twice

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3409]
I'm not sure how exactly this happens, but noticed it today. The web UI showed incoming and outgoing rates as 0 KiB/s when I knew there was data flowing. Investigating that shows that it does the refresh things (refreshConnections, refreshErrors etc) twice in lockstep, meaning that the diff after the second refresh is zero.

![screen shot 2016-07-18 at 08 05 11](https://cloud.githubusercontent.com/assets/125426/16906901/ad318eea-4cbe-11e6-998a-abfe99f0151c.png)

This was after just opening the UI, not restarting or other funny business,

**Comment by AkaZecik** [comment]
I was unable to reproduce it with neither a huge amount of small files nor a small amount of huge files. Is this still an issue or was it solved without getting closed? The only duplicate for me in the console was `recalcCompletion` for the same device, no of the 'refresh' logs were immediately duplicate.

**Comment by calmh** [comment]
Given the age I'm going to optimistically assume it's not an issue any more.
