### ISSUE TITLE
Enhancement: after-sync hook script

### ISSUE THREAD

**Issue by arximboldi** [syncthing/syncthing#3410]
Hi!

It would be nice to be able to easily set up a script (e.g. `.schook` on a sync folder) that is run whenever synchronization finishes.

### Use cases

**Example:** A user has a media server with MPD. She would like to update the music database (`mpc update`) whenever Syncthing is done synching files on my music folder.

**Example:** A user has a shared folder with pictures she shares with friends. She also displays them in a gallery on a server, to which she deploys via Syncthing. She would like to run a static photo gallery generator on the server whenever the photos folder is updated.

**Example:** A user would like to schedule a backup when-if Syncthing updates a folder.

### Workarounds

One may use a `inotify` based tool (e.g. `watchmedo`) to observe the folder and run a command whenever it changes. However, that might trigger too many updates and cause partial updates to be visible because some files have been synchronized, but some not. It would be better, to just run the script whenever the folder is back into synchronized state, something that only Syncthing knows.

**Comment by AudriusButkevicius** [comment]
Use the events API
