### ISSUE TITLE
Add folder option to follow symlinks

### ISSUE THREAD

**Issue by frispete** [syncthing/syncthing#3414]
While you have a global symlinksEnabled option, another per folder option to _follow_ symlinks would be great for syncing to smaller devices like smart phones, e.g. for syncing a subset of a music collection, a sync folder with symlinks to the real collection would do the trick...

**Comment by xduugu** [comment]
I guess it is handled by this pull request #3387?

**Comment by AudriusButkevicius** [comment]
There is already a ticket for this.
