### ISSUE TITLE
ARM64 | Setting GUI user/password has no effect.

### ISSUE THREAD

**Issue by Fourdee** [syncthing/syncthing#3415]
Hi All,

Setting the GUI username/password has no effect. Tested with ARMv6+ installation, thats fine.

Installation of Syncthing using 0.14.0 ARM64 binary (https://github.com/syncthing/syncthing/releases/download/v0.14.0/syncthing-linux-arm64-v0.14.0.tar.gz). I only use the binary from extracted files and move to ```/usr/bin/syncthing```.

![ani](https://cloud.githubusercontent.com/assets/7077026/16956821/cf1d13bc-4dd1-11e6-885c-0a1d328c2c46.gif)

Browser refresh has no effect (ctrl+f5). After restarting the service, API key and theme entries are reset in web interface.

Config procedure for DietPi https://github.com/Fourdee/DietPi/issues/422. (Identical to ARMv6+ installation, minus the binary arch):
```
# - run syncthing to create cert/config and exit
syncthing -generate="/$HOME/.config/syncthing"

# - Allow external access (LAN).
sed -i '/:8384<\/address>/c\        <address>0.0.0.0:8384<\/address>' "$HOME"/.config/syncthing/config.xml

# - Set default folder
sed -i '/label=\"Default Folder/c\    <folder id=\"0000-0000\" label=\"DietPi user data\" path=\"/mnt/dietpi_userdata/\" type=\"readwrite\" rescanIntervalS=\"60\" ignorePerms=\"false\" autoNormalize=\"true\">' "$HOME"/.config/syncthing/config.xml

# - Disable browser starting
sed -i '/<\/startBrowser>/c\        <startBrowser>false<\/startBrowser>' "$HOME"/.config/syncthing/config.xml

# service
cat << _EOF_ > /etc/systemd/system/syncthing.service
[Unit]
Description=Syncthing

[Service]
Type=oneshot
ExecStart=/bin/bash -c '/usr/bin/syncthing > /var/log/syncthing.log &'
ExecStop=/usr/bin/killall -w syncthing
RemainAfterExit=yes
User=root

[Install]
WantedBy=multi-user.target
_EOF_
systemctl enable syncthing.service
systemctl daemon-reload
```

Log
```
root@DietPi:~# cat /var/log/syncthing.log
[monitor] 16:41:55 INFO: Starting syncthing
[XLSCL] 16:41:55 INFO: syncthing v0.14.0 "Dysprosium Dragonfly" (go1.6.3 linux-arm64) unknown-user@lx-buildslave.syncthing.net 2016-07-17 21:45:22 UTC
[XLSCL] 16:41:55 INFO: My ID: XLSCLIU-WXPTKK3-BJG5DKV-KSKT4EW-XQNNEI3-EEJKZNK-EWS5TDF-ZBHXIA3
[XLSCL] 16:41:56 INFO: Single thread hash performance is ~7.6 MB/s
[XLSCL] 16:41:56 INFO: Ready to synchronize 0000-0000 (readwrite)
[XLSCL] 16:41:56 INFO: Completed initial scan (rw) of folder 0000-0000
[XLSCL] 16:41:56 INFO: TCP listener ([::]:22000) starting
#UUID/Keys removed
[XLSCL] 16:41:56 INFO: GUI and API listening on [::]:8384
[XLSCL] 16:41:56 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[XLSCL] 16:42:06 INFO: Joined relay relay://185.115.243.157:22067
[XLSCL] 16:42:07 INFO: Detected 0 NAT devices
```

**Comment by xduugu** [comment]
Does this only occur when setting the authentication values or for any configuration change? What I experienced on a raspberry pi was that folders I deleted in the WebGUI re-appeared after a restart. I assumed the config change did not reach the REST API because of high cpu load. The config.xml file was not modified, but the changed configuration seems to get cached by the GUI. However, I never saw this on any other device, but the raspberry pi is by far the weakest.

**Comment by Fourdee** [comment]
> Does this only occur when setting the authentication values or for any configuration change?

Doesn't effect folder creation. Changed the value ```<startBrowser>true</startBrowser>``` from web interface, seems to save it correctly. Looks limited to GUI user/password, API key and GUI theme.

Appears the ARM64 binary isnt creating these values in ```config.xml```:
```
        <user>root</user>
        <password>xxxxxxxxxxxxxx
```

ARM64 (Odroid C2):
```
    <gui enabled="true" tls="false">
        <address>0.0.0.0:8384</address>
        <apikey>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</apikey>
        <theme>default</theme>
    </gui>
```

ARMv6+ (Raspberry Pi 3):
```
    <gui enabled="true" tls="false">
        <address>0.0.0.0:8384</address>
        <user>root</user>
        <password>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        <apikey>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</apikey>
        <theme>default</theme>
    </gui>
```

**Comment by Fourdee** [comment]
ARM64:

Manually added the following to config.xml
```
        <user>root</user>
        <password>dietpi</password>
```
After restarting the service, the web interface now prompts me for login details.

**Comment by AudriusButkevicius** [comment]
Are you running inotify?

**Comment by Fourdee** [comment]
@AudriusButkevicius 

> Are you running inotify?

No idea, is this another binary or command line input for the existing binary? Only ```/usr/bin/syncthing``` is run.

ARM64 binary:
```
root@DietPi:~# ls -lha /usr/bin/syncthing
-rwxr-xr-x 1 1004 1004 16M Jul 19 09:58 /usr/bin/syncthing
```

**Comment by AudriusButkevicius** [comment]
Yeah it is a separate binary. But you are on linux so the argument I had does not apply anyway

**Comment by AudriusButkevicius** [comment]
Can you check JS console for errors and check the process environment in proc?

**Comment by Fourdee** [comment]
@AudriusButkevicius 

>  JS console 

How?

>  process environment in proc

```
root@DietPi:~# ps aux | grep [s]ync
root      5049  0.0  0.2  17672  4948 ?        Sl   18:56   0:02 /usr/bin/syncthing -no-browser
root      5060  0.4  1.3  36744 23244 ?        Sl   18:56   0:16 /usr/bin/syncthing -no-browser

root@DietPi:~# cat /proc/5049/environ
SHELL=/bin/shUSER=rootPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/binPWD=/LANG=en_GB.UTF-8SHLVL=1HOME=/rootLOGNAME=root_=/usr/bin/syncthing

root@DietPi:~# cat /proc/5060/environ
SHELL=/bin/shUSER=rootPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/binPWD=/LANG=en_GB.UTF-8SHLVL=1HOME=/rootLOGNAME=root_=/usr/bin/syncthingSTNORESTART=yesSTMONITORED=yes
```

**Comment by AudriusButkevicius** [comment]
So I am pretty sure there is no difference between ARM64 and ARM6, as it's the same code crosscompiled.

Perhaps you can compare strace output as you are saving the config (potentially filtering file operations) between the working and non-working version. I am sure it's something specific to your setup as we'd have many more users complaining.

You can google how to check the JS log as it varies between browsers.

**Comment by scienmind** [comment]
Just my 2 cents: 
I've faced similar problems with syncthing-android (Play Store / F-Droid) several times.
After few repeated attempts the setting eventually will stick, but setting up a new device is often a PITA.

**Comment by Fourdee** [comment]
> So I am pretty sure there is no difference between ARM64 and ARM6, as it's the same code crosscompiled.

Seems the issue is isolated to the Odroid C2, even on the official Ubuntu image. Pine A64 is fine. I'am thinking possible issue with missing kernel/cpu extensions that was compiled with Go?

I'll try a native compile on the C2 and test.

**Comment by calmh** [comment]
For something to affect a specific config options like this, you probably don't want to look at low level stuff like the CPU. If there was a problem with the instruction set or whatever it would have crashed. I suspect browser shenanigans.

**Comment by Fourdee** [comment]
> I suspect browser shenanigans.

Spot on :+1:  Tried Opera, works fine. 

In the tests I used Chrome. 
Clearing passwords did the trick. Now when loading the settings page, even the APi key and Theme values are loaded correctly, previous, these were blank.
![image](https://cloud.githubusercontent.com/assets/7077026/16993065/c7f187c6-4e99-11e6-96e0-887f88fcfe24.png)
