### ISSUE TITLE
Parallel scanning of folders slows down

### ISSUE THREAD

**Issue by joaofl** [syncthing/syncthing#3416]
Whenever I have to rescan all my folder which sum up to 500Gb (like for the new release), It takes a considerably big amount of time to do it, specially if you have a hard drive instead of an SSD.

But I've noticed that, if I add folders only after scanning the previous folder, this process may last much less, since I decrease the amount of "random access" to the hd, and yet increase the CPU utilization.

So, I would say that some sort of per-hard-disk scanning queue would be helpful, and would increase the performance on the first scan considerably (benchmark pending).

Editing: found similar issue https://github.com/syncthing/syncthing/issues/2760 

### Version Information

Syncthing Version: v0.14.x (any I would say)
OS Version: Ubuntu 16.04 (any)

**Comment by AudriusButkevicius** [comment]
I feel there is already an existing issue regarding this. Did you search before opening?

**Comment by joaofl** [comment]
Yes. There were 8 pages of results, with 180 results for scanning.
But anyway, I found it later, and mentioned it in my post already (if it answer your question).

**Comment by AudriusButkevicius** [comment]
It is the same issue, hence closing.
