### ISSUE TITLE
GUI still accessible after uninstall Syncthing and removing config files

### ISSUE THREAD

**Issue by mindstormer12** [syncthing/syncthing#3417]
GUI still accessible ((https://127.0.0.1:8384) after uninstall Syncthing and removing config files. On Arch, I did `pacman -Rns syncthing` then `rm -r ~/.config/syncthing`. It was only after a restart that the GUI was no longer accessible.

**Comment by wweich** [comment]
We don't provide arch packages. This problem is not with syncthing itself, but with how the arch package is configured.
Please report the issue to the arch package maintainers.

**Comment by canton7** [comment]
You didn't stop syncthing. Even though you uninstalled it, it was still running, and it kept running until you restarted.

**Comment by mindstormer12** [comment]
I did stop the services and terminated all instances of it. I was told the issue is I needed to clear my cache.
