### ISSUE TITLE
Inter-Version Knowledge of Versions (via the Notice)

### ISSUE THREAD

**Issue by snpalavan** [syncthing/syncthing#3418]
Not sure how long this has been implemented, i just noticed it in 0.14.0, but when there are incompatible versions, you get a notice like this:
![image](https://cloud.githubusercontent.com/assets/1146754/16990623/450a08be-4e5e-11e6-907e-7222c5651176.png)

If this isn't already in the works then ignore this, but if possible, i think it would be relatively simple and user friendly to implement a determination of which version the newer one is.  It already knows when looking from new to old:
![image](https://cloud.githubusercontent.com/assets/1146754/16990654/6116a940-4e5e-11e6-8f60-1c44ad7bbc81.png)

So the other way, from old to new, i think it would be helpful to know just which version the newer one is.  It doesnt really matter currently since versioning is relatively low and minimal, but let's assume i have a server that rarely gets modified, and it runs v0.13.0, the current version of syncthing is v1.0, and i have a client with a slightly older version v0.9.5. These versions would be incompatible (absent some conversion algorithm implemented), but only knowing that the client is "newer" but not which version would make it difficult to determine if the server should be upgraded to v0.9.5 or v1.0.

A simple version report from new to old would work - maybe even a txt file list such that the older version can see just how old it is.  Something like:

Where the newer version is still not current:
"the remote device speaks a newer version of the protocol (v0.9.5), and the current version (v1.0). Please consider updating both devices."
Or, if the newer version is the current version:
"the remote device speaks a newer version of the protocol (v1.0), which is the current version. Please consider updating this device."

-Shea

**Comment by AudriusButkevicius** [comment]
You have to have a compatible protocol to communicate which version you are using, which by definition is not possible, as they afe incompatible.

**Comment by AudriusButkevicius** [comment]
New version knows the first few bits of the old version hencr why it knows how to handle, sadly old versions cannot travel into the future to know how the protocol will look like in the future.

**Comment by AudriusButkevicius** [comment]
You can always check which version of syncthing you are running on the other end to know which version to upgrade to.

**Comment by snpalavan** [comment]
I wasn't worried for me :) I was just thinking out loud if there were a way to not just say it was a newer version, but which version it was.  Obviously this would not be possible NOW since it isn't currently implemented.  The idea was to implement it so that, going forward, users would not only be notified the version was incompatible, but also tell them which version the other was using so they know which version to update to.

Just saying "newer" doesn't inform the user whether they should update to the newest version or one in between!

**Comment by calmh** [comment]
Yep. The intention with the latest protocol iteration is to make it flexible enough that we should hopefully not have to break compatibility very often in the future.

**Comment by AudriusButkevicius** [comment]
Regardless, we cannot implement safeguards now for what the code will look lke in a years time, as we have no idea what it will look like ourselves, so I think only informing of older versions is possible.
