### ISSUE TITLE
Syncthing for Windows won't sync with Android or ARM/Linux

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing#3419]
As soon as the new v.14 was released, synchronizing my Windows machines to Android or ARM Linux devices has been a nightmare, as for some reason the Android app does not see that there is an update to v.14.

Anyone know if this is a bug or if it is not yet released for Android and ARM/Linux?

> Here is a sample report Syncthing gives me on Windows:
> ```
> 2016-07-20 11:51:05: Connecting to "HTC 10" (syncthing v0.13.7, HTC 10): the remote device speaks an older version of the protocol (v0.13) not compatible with this version
> 
> 2016-07-20 11:51:25: Connecting to "localhost" (syncthing v0.13.7, Google Nexus 9): the remote device speaks an older version of the protocol (v0.13) not compatible with this version
> ```

**Comment by canton7** [comment]
Not yet supported by the Android version, see https://github.com/syncthing/syncthing-android/issues/696.

**Comment by wweich** [comment]
As the [release notes](https://play.google.com/store/apps/details?id=com.nutomic.syncthingandroid) of the most recent version of the Android App state, it uses Syncthing 0.13.7. And as the [release notes](https://github.com/syncthing/syncthing/releases/tag/v0.14.0) of 0.14 state, it is incompatible with older versions.

The Android App will be updated in the next days, as the main developer is currently busy with other things.

**Comment by calmh** [comment]
(Leaving this open for others to see, for a while)

**Comment by MikeLund** [comment]
As no one else explicitly stated it, the Linux version _is_ updated. It is only the Android version that is not ready yet.

So for your Linux problem, update syncthing using your package manager (or however you installed it in the first place). :)

**Comment by canton7** [comment]
> As no one explicitly stated it, the Linux version is updated. 

Really that depends on the distro: different package managers will update at different speeds. Arch linux, for example, is still in the process of updating to 0.14.
