### ISSUE TITLE
Windows binaries should be code signed

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3420]
Per subject. When we get round tuits.

Preferred implementation would be something added to the https://github.com/syncthing/release-tools/blob/master/sign-upload-release script to pick up a code signing certificate from an environment variable and use it. It should run on Linux.

Point me at where to purchase a certificate for a reasonable price and I'll get that sorted.

**Comment by AudriusButkevicius** [comment]
https://en.sklep.certum.pl/data-safety/code-signing-certificates/open-source-code-signing.html
https://sourceforge.net/projects/osslsigncode/files/osslsigncode/

**Comment by StrikerTwo** [comment]
Startssl.com does reasonably priced code signed certs.

**Comment by subscribernamegoeshere** [comment]
I think I have a lot of times visited this kind of problems with different kind of projects, bei it commercial or oss in the past. I think the conclusion always had been for oss, that there are in fact providers and places where they hand out personal or specially certificates (accounts) for oss developers and oss teams to be able to sign your stuff. Or there even was the reactos groups (project) that offered (but mostly kernel driver development people, see processhacker for windows) code signing services with their signing service. I dont remember too many details any more though but there are or ought to be places which offer signing capabilities or certificates for oss people such as you guys. Please do look it up, but this does no magic to that guy in the company with his antivirus trouble that is complaining in the syncthing forums these days about misdetection. even signed binaries get complained by lots of delusional and ill performing av vendors.

**Comment by calmh** [comment]
This is done, from 0.14.41 forwards.

<img width="421" alt="screen shot 2017-11-20 at 08 24 13" src="https://user-images.githubusercontent.com/125426/33006900-78b0af26-cdcc-11e7-9785-7b0c5de23829.png">

**Comment by subscribernamegoeshere** [comment]
Please dont forget about your x86 32bit windows binary build. that this binary is supposedly also running on still older e.g. winxp 32bit systems, which dont be compatible with sha256 signature and all that. I am not an expert of all the fancy tech details but please look at these issues thoroughly and in a more complete and responsible way.

a good example is e.g. the putty guys and development there, they have dual signature provided to their putty.exe binary, sha1 and sha256

please check their .exe file as an example for example at:
project page:
<https://www.chiark.greenend.org.uk/~sgtatham/putty/>

32bit windows x86 binary link at:
<https://the.earth.li/~sgtatham/putty/latest/w32/putty.exe>

64bit x64 windows binary link at:
<https://the.earth.li/~sgtatham/putty/latest/w64/putty.exe>

thanks for taking these matters seriously. ty.

**Comment by calmh** [comment]
The obvious dual signing instructions didn’t work for me. In the end I’m not super concerned about whether the signature can be validated on XP as long as the binary works.

**Comment by subscribernamegoeshere** [comment]
its not only validation fail but sometimes the explorer.exe aka the desktop system blocks or error popups such failed signed binaries for the end user and can have weird effects. and as I reported it is also up until early win7 or noncompletely patched systems, xp, vista, win7.

how are you code signing the stuff? what commandline or other tools are you using? I am only kind of a layman or theorizing here sorry to be not very much of a help but I like well engineered and thorougly thought trough proceedings and situations. Thanks for taking care. Greetings.

**Comment by calmh** [comment]
https://github.com/syncthing/syncthing/blob/c2/build.go#L1099

**Comment by calmh** [comment]
OK I sorted it out

**Comment by subscribernamegoeshere** [comment]
Hey cool that looks great. Will test the final (or rc3 already?) binaries when they get released. Thanks a great deal and many greetings go to you for your work and making this possible. Im very glad. Thank you again. Regards.
