### ISSUE TITLE
Can i sync with some cloud service as google drive/Onedrive ...?

### ISSUE THREAD

**Issue by thanhngvpt** [syncthing/syncthing#3421]
Dear Author.
Your job is great i am looking for a tool can help me sync local file with google drive/One drive and found your project, i just installed but i wonder does it can help me? 
Many thanks.

**Comment by canton7** [comment]
No, only the Google drive / onedrive applications can sync to Google drive / onedrive. You can if course have syncthing sync to a folder, and have Google drive / onedrive also sync to that folder...

**Comment by jsdecker10** [comment]
I'm gonna assume you're probably running a Windows machine. . . What you're looking for sounds to me like you'd be able to benefit from the software called "[Syncdocs](http://www.syncdocs.com/)."

(I'm not sure if I'm allowed to link to other projects/sites, so if this isn't allowed, mods feel free to edit my post.)
