### ISSUE TITLE
Execute permissions on .js files

### ISSUE THREAD

**Issue by chrisveness** [syncthing/syncthing#3422]
I've just had a rather strange issue.

Syncthing has reported a large number of conflicts (discovered through _git status_) for no obvious reason, and apparently at the same time changed the permissions of (I think all) .js files to have the execute bits set (files that were previously -rw-r--r-- have become -rwxr-xr-x).

This may be connected to the v0.14 update; my Unix machine updated, then complained the Windows machine was behind.

The sync-conflict files I can handle, but it seems very strange the execute permissions should be changed on .js files!

I'm using v0.14.0 64-bit on Linux Mint 17.3 (built on Ubutu 14.04) and (now) v0.14.0 64-bit on Windows 7 (using Synctrayzor).

**Comment by canton7** [comment]
Shouldn't the Windows install be ignoring permissions? Where did it get them from in that case?

**Comment by canton7** [comment]
Sounds like it might be related to https://forum.syncthing.net/t/v0-14-previously-deleted-files-re-appear-ignore-permission-bits/7814/11?u=canton7 ?

**Comment by calmh** [comment]
We pick up permissions as usual on Windows, which usually yield either 0644 (I think) or 0444 depending on whether read-only is set. For executable extensions (exe, com, bat, ...) we set the execute bit as well. I don't see that this *should* have changed, but I guess it could. It sounds more like something related to the wipe-and-rescan maybe.

**Comment by chrisveness** [comment]
I suspected it wouldn't mean much to you. I might not have noticed the permissions changing had git not been choking on them. I think there are two aspects here:

- spurious `sync-conflict` files: I'm sure this is well covered elsewhere, there are probably many possible explanations
- execute permissions on `.js` files: as far as I've noticed (I've not had time to check systematically), it's only `.js` files which are affected, and it's only ones with matching `sync-conflict` files; something somewhere must recognise JavaScript can be executed ... but who knows what or where

I don't have time to provide anything more constructive, but I thought I'd let you know, just in case it was a helpful piece of a jigsaw somewhere.

**Comment by calmh** [comment]
The set of executable file extensions come from an environment variable set by Windows. If your system is configured so that js files are double clickable I would expect Syncthing to also see them as executable and then pass that bit on elsewhere.

**Comment by crobarcro** [comment]
I've also found a lot of files, of any extension having their execute permissions changed by syncthing. At least, I'm pretty sure it's syncthing. None of my nodes are windows, all are linux. I'm using one node purely as a backup server (a raspberry pi running raspbian) and never changing files on this server. The other node is a laptopt running Mint Linux. 

In case it is relevant, on the raspberri pi, the files are actually stored on a USB ssd drive on an NTFS formatted partition. I'm also getting lots of sync conflicts where I _know_ I have not modified the files.

**Comment by calmh** [comment]
You will have to set "ignore permissions" on that setup, as NTFS doesn't keep the Linux set of permissions. We compensate for this when running on Windows, but when running on Linux we expect a fully working Linux filesystem.

**Comment by calmh** [comment]
Closing as this is now in support territory - forum is open for future discussion.
