### ISSUE TITLE
"Last seen" device lost

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#3423]
when upgrading to 0.14

**Comment by xduugu** [comment]
What do you mean? It's still there, just reset to "never" until the first connection using syncthing 0.14.

**Comment by canton7** [comment]
Indeed: the database was rebuilt in the 0.14 format. The "last seen" field was likely part of the database.

**Comment by bugith** [comment]
Sorry, maybe I wiggled my brain with some inexistant "First seen" feature. Close this no-bug.

**Comment by bugith** [comment]
Although, xduugu told it well : the field is reset to "never". Shouldn't the value survive an upgrade ?

**Comment by AudriusButkevicius** [comment]
Maybe, but nobody cares.

**Comment by canton7** [comment]
As I said:

> Indeed: the database was rebuilt in the 0.14 format. The "last seen" field was likely part of the database.

Therefore it probably got lost in the migration. Since it's for information only, and pretty minor at that, I don't think it's significant enough to warrant the reasonable amount of effort it would probably take to fix it.

**Comment by xduugu** [comment]
Is the database actually migrated? I thought it is just recreated from the files. Any data that cannot be extracted from the filesystem should get lost, but maybe "Last seen" is currently the only one.

**Comment by canton7** [comment]
I used the term "migration" in a very loose sense... Yes, recreated.
