### ISSUE TITLE
Show data remaining to be synced for remote devices

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3425]
One of my devices has looked like this a for a few days:

<img width="568" alt="screen shot 2016-07-21 at 19 48 46" src="https://cloud.githubusercontent.com/assets/125426/17032987/41408a2c-4f7c-11e6-926f-ce76f34581a1.png">

It's "100%" because it's like 99.7% or so in sync, which still means there are several GiB to transfer. But I don't know how many or how long it will take. We could, at the very least, show how much data remains to be synced because we know that. For bonus points we could extrapolate the remaining time, but that's trickier.

**Comment by balihb** [comment]
I'm seeing the same thing. It will never be fully synced for me (stays the same). Might this be caused by ignore patterns? The missing percent looks about right in size for me.

**Comment by imsodin** [comment]
@balihb Please use the forum for support questions (the short answer is yes).

The remaining data is shown in the meantime. The time gimmick isn't there, but I guess that was dismissed in the PR where this changed happened. I assume this error was just somehow missed -> closed.

**Comment by balihb** [comment]
I misunderstood this issue. I'll open a new one.

**Comment by AudriusButkevicius** [comment]
There is no need to open new issues, you need to go to the forum and there are plenty of threads that answer your question.
