### ISSUE TITLE
unknown address scheme

### ISSUE THREAD

**Issue by DavidFi1** [syncthing/syncthing#3426]
Hi.
I want to sync my win 7 ip: 192.168.0.101 and my nexus 5 ip: 192.168.0.104 .
I am new to syncthing so it could be very simple issue.
I want to sync 2 directories whatsup\media & camera
This is the problem reported on the terminal window : 

[MNZIT] 07:21:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 07:53:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 07:53:50 INFO: UPnP parse: unrecognized UPnP device of type upnp:rootdev
ice
[MNZIT] 07:53:50 INFO: UPnP parse: unrecognized UPnP device of type upnp:rootdev
ice
[MNZIT] 07:53:50 INFO: UPnP parse: unrecognized UPnP device of type uuid:0000000
0-0000-1000-0000-6466b3f53520
[MNZIT] 07:53:50 INFO: UPnP parse: unrecognized UPnP device of type uuid:0000000
0-0000-1000-0000-6466b3f53520
[MNZIT] 07:53:50 INFO: UPnP parse: unrecognized UPnP device of type urn:schemas-
wifialliance-org:device:WFADevice:1
[MNZIT] 07:53:50 INFO: UPnP parse: unrecognized UPnP device of type urn:schemas-
wifialliance-org:device:WFADevice:1
[MNZIT] 07:53:50 INFO: UPnP parse: unrecognized UPnP device of type urn:schemas-
wifialliance-org:service:WFAWLANConfig:1
[MNZIT] 07:53:50 INFO: UPnP parse: unrecognized UPnP device of type urn:schemas-
wifialliance-org:service:WFAWLANConfig:1
[MNZIT] 07:54:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 07:55:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 07:56:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 07:57:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 07:58:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 07:59:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:00:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:01:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:02:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:03:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:04:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:05:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:06:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:07:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:08:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:09:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:10:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:11:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:12:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:13:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:14:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:15:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:16:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:17:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:18:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:19:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:20:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:21:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:22:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:23:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:24:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:25:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:26:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:27:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:28:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:29:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:30:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:31:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:32:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:33:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:34:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:35:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:36:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:37:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:38:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:39:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:40:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:41:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:42:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:42:51 WARNING: Connecting to GZG2NXC-5RMJS66-746FKDN-VN2NOP6-XXPWXQU-
EUF35UC-JDASJ6K-XDDSGAG (31.31.75.186:22067): the remote device speaks an unknow
n (newer?) version of the protocol
[MNZIT] 08:43:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:44:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:45:16 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:45:28 INFO: Restarting
[MNZIT] 08:45:28 INFO: Exiting
[monitor] 08:45:36 INFO: Syncthing exited: exit status 3
[monitor] 08:45:37 INFO: Starting syncthing
[MNZIT] 08:45:44 INFO: syncthing v0.13.10 "Copper Cockroach" (go1.6.2 windows-38
6) WIN-P6RP886TVDJ\Administrator@WIN-P6RP886TVDJ 2016-07-03 11:29:32 UTC
[MNZIT] 08:45:44 INFO: My ID: MNZITOH-KEUBI5M-WL4VLLT-YWH444T-TUVNYL2-RZUO53E-MQ
TNJJT-I3QC5AP
[MNZIT] 08:45:45 INFO: Single thread hash performance is ~130 MB/s
[MNZIT] 08:45:46 INFO: Ready to synchronize WhatsupID (readwrite)
[MNZIT] 08:45:46 INFO: Ready to synchronize nexus_5-photos (readwrite)
[MNZIT] 08:45:46 INFO: Using discovery server https://discovery-v4-1.syncthing.n
et/v2/?id=SR7AARM-TCBUZ5O-VFAXY4D-CECGSDE-3Q6IZ4G-XG7AH75-OBIXJQV-QJ6NLQA
[MNZIT] 08:45:46 INFO: Using discovery server https://discovery-v4-2.syncthing.n
et/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[MNZIT] 08:45:46 INFO: Using discovery server https://discovery-v4-3.syncthing.n
et/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[MNZIT] 08:45:46 INFO: Using discovery server https://discovery-v6-1.syncthing.n
et/v2/?id=SR7AARM-TCBUZ5O-VFAXY4D-CECGSDE-3Q6IZ4G-XG7AH75-OBIXJQV-QJ6NLQA
[MNZIT] 08:45:46 INFO: Using discovery server https://discovery-v6-2.syncthing.n
et/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[MNZIT] 08:45:46 INFO: Using discovery server https://discovery-v6-3.syncthing.n
et/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[MNZIT] 08:45:46 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:45:46 INFO: TCP listener ([::]:22000) starting
[MNZIT] 08:45:46 INFO: Device GZG2NXC-5RMJS66-746FKDN-VN2NOP6-XXPWXQU-EUF35UC-JD
ASJ6K-XDDSGAG is "DudusPhone" at [192.168.0.104]
[MNZIT] 08:45:46 INFO: Device MNZITOH-KEUBI5M-WL4VLLT-YWH444T-TUVNYL2-RZUO53E-MQ
TNJJT-I3QC5AP is "Home" at [dynamic]
[MNZIT] 08:45:46 INFO: Starting usage reporting
[MNZIT] 08:45:46 INFO: GUI and API listening on 127.0.0.1:8384
[MNZIT] 08:45:46 INFO: Access the GUI via the following URL: http://127.0.0.1:83
84/
[MNZIT] 08:45:46 INFO: Completed initial scan (rw) of folder WhatsupID
[MNZIT] 08:45:46 INFO: Completed initial scan (rw) of folder nexus_5-photos
[MNZIT] 08:45:47 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:45:49 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:45:53 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:45:57 INFO: New NAT port mapping: external TCP address 77.139.221.7:5
6934 to local address 0.0.0.0:22000.
[MNZIT] 08:45:57 INFO: Detected 1 NAT device
[MNZIT] 08:46:01 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:46:02 INFO: Joined relay relay://138.201.156.90:22067
[MNZIT] 08:46:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:47:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:48:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:49:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:50:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:51:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:52:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:53:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:54:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:55:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:56:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:57:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:58:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 08:59:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:00:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:01:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:02:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:03:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:04:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:05:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:06:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:07:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:08:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:09:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:10:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:11:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:12:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:13:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:14:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:15:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:16:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:17:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:18:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:19:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:20:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:21:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:22:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:23:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:24:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:25:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:26:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:27:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:28:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:29:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:30:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:31:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:32:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:33:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:34:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:35:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:36:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:37:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:38:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:39:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:40:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:41:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:42:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:43:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:44:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:45:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:46:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:47:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:48:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:49:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:50:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:51:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:52:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:53:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:54:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:55:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:56:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:57:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:58:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 09:59:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:00:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:01:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:02:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:03:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:04:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:05:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:06:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:07:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:08:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:09:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:10:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:11:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:12:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:13:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:14:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:15:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:16:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:17:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:18:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:19:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:20:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:20:48 INFO: Disconnecting from relay relay://138.201.156.90:22067/?id
=XYWRY6J-I4PVS76-OYBJEK5-MMWAFOQ-4DFHD45-6WVDXVN-N63DPXD-CAZ56AD&pingInterval=1m
0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=300000&statusAddr=:22070
&providedBy=aucubin due to error: EOF
[MNZIT] 10:20:48 INFO: Disconnected from relay relay://138.201.156.90:22067
[MNZIT] 10:20:49 INFO: Joined relay relay://37.187.112.143:22067
[MNZIT] 10:21:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:22:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:23:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:24:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:25:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:26:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:27:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:28:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:29:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:30:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:31:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:32:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:33:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:34:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:35:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:36:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:37:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:38:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:39:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:40:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:41:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:42:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:43:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:44:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:45:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:46:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:46:31 INFO: UPnP parse: unrecognized UPnP device of type upnp:rootdev
ice
[MNZIT] 10:46:31 INFO: UPnP parse: unrecognized UPnP device of type upnp:rootdev
ice
[MNZIT] 10:46:31 INFO: UPnP parse: unrecognized UPnP device of type uuid:0000000
0-0000-1000-0000-6466b3f53520
[MNZIT] 10:46:31 INFO: UPnP parse: unrecognized UPnP device of type uuid:0000000
0-0000-1000-0000-6466b3f53520
[MNZIT] 10:46:31 INFO: UPnP parse: unrecognized UPnP device of type urn:schemas-
wifialliance-org:device:WFADevice:1
[MNZIT] 10:46:31 INFO: UPnP parse: unrecognized UPnP device of type urn:schemas-
wifialliance-org:device:WFADevice:1
[MNZIT] 10:46:31 INFO: UPnP parse: unrecognized UPnP device of type urn:schemas-
wifialliance-org:service:WFAWLANConfig:1
[MNZIT] 10:46:31 INFO: UPnP parse: unrecognized UPnP device of type urn:schemas-
wifialliance-org:service:WFAWLANConfig:1
[MNZIT] 10:47:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:48:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:49:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:50:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:51:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:52:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:53:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:54:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""
[MNZIT] 10:55:17 INFO: Dialer for 192.168.0.104: unknown address scheme ""

**Comment by AudriusButkevicius** [comment]
Read the docs on configuring direct IP addreesses.

**Comment by AudriusButkevicius** [comment]
Also, don't open support requests on the issue tracker. Use the forum, like explaimed in the issue template.

**Comment by DavidFi1** [comment]
* I am not able to find "the docs on configuring direct IP addreesses." - not in the docs's search and not in google
* I could not find the forum - by searching the docs.
Now that you say there is a forum - I foud it on google.
Please add links to the forum to the main page - in case an issue ect...

**Comment by AudriusButkevicius** [comment]
You are asked to use the forum in the issue template, no need for me to mention it here, but I guess you did not read it.

The explanation how to configure IP addresses for a device would surely be under configuration > device element?
https://docs.syncthing.net/users/config.html#device-element
