### ISSUE TITLE
Devices stuck in "Syncing 100%"

### ISSUE THREAD

**Issue by catkfr** [syncthing/syncthing#3428]
I have a three machine setup, all Macs. 
Two machines (using 10.11.6) show that everything is fine in the GUI folders synced and devices up to date.
One machine using 10.11.5, shows that everything is ok on the folders view (green "up to date") but in the remote devices view, the two other machines are stuck at "Syncing 100%".

Running in verbose mode on the machine showing the issue, it seems that the problem comes from the "Documents" share:

```
[N3EDA] 16:51:44 VERBOSE: Summary for folder "Documents" is map[localDeleted:7 localFiles:660 globalDeleted:8 needFiles:0 needBytes:0 state:idle globalFiles:660 globalBytes:590053622 localBytes:590053494 inSyncBytes:590053622 version:17105 inSyncFiles:660]
[N3EDA] 16:51:44 VERBOSE: Completion for folder "Documents" on device ID-1 is 99.98888643378245%
[N3EDA] 16:51:44 VERBOSE: Completion for folder "Documents" on device ID-2 is 99.98888643378245%

```

### Version Information

Syncthing Version: v0.14.0
OS Version: OS X 10.11.6 (2 machines) and OS X 10.11.5 (1 machine)
Browser Version: Safari (9.1.2 on 10.11.6 and 9.1.1 on 10.11.5)

The machine having the issue is the one on OS X 10.11.5

**Comment by AudriusButkevicius** [comment]
Please use forum for support requests, as explained in the issue template.
