### ISSUE TITLE
French translation for "Scan Time Remaining" in GUI

### ISSUE THREAD

**Issue by Anthony25** [syncthing/syncthing#3429]
Hello,
The GUI item "Scan Time Remaining" is translated as "Intervalle entre chaque analyse" in french, which means "Range between each scan" when it should be "Temps restant d'analyse" (or "Analyse terminée dans", which is more correct but closer to "Scan finished in").

### Version Information

Syncthing Version: v0.14
OS Version: ArchLinux

Thanks!

**Comment by canton7** [comment]
Translations are handled on Transfixe: https://www.transifex.com/syncthing/syncthing/dashboard/.

Please make any changes there.

**Comment by Anthony25** [comment]
Done, thanks

**Comment by aviau** [comment]
@Anthony25 +1 for "Temps restant d'analyse"
