### ISSUE TITLE
gui: Warning "path is a subdirectory of other folder" persists between dialogs

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#3433]
Seen in ubuntu firefox
Starting to create a new share, then giving a path through a yet shared one the warning (string 139) triggers OK. Then cancelling the creation and immediately starting a new creation, the warning still shows even though the path is empty. The warning definitively disappears OK when typing / ~ or double-clic the path field... until we type again a path through an existing share path, which is OK.

Seems to be some variable not reset by Close button. Same issue when validating with Save.

**Comment by calmh** [comment]
I tried fixing this by sprinkling some reset of `$scope.pathIsSubFolder = false` in the appropriate places, but that doesn't help. This warning is handled by a funky angular directive that I don't fully understand, and something is wrong about it. Needs help from someone better at Angular.

**Comment by AudriusButkevicius** [comment]
The part of code which checks if A is in B should check if B is in A at the same time, and I think that should be good enough and not require angular knowledge?

**Comment by calmh** [comment]
The problem I ran into is that the directive doesn't run at dialog open (which is correct) and manually falsing the attribute didn't hide the warnibg

**Comment by AudriusButkevicius** [comment]
Sorry, sleep walking, I thought it was a different issue.
We should set that back to false on dialog close.

**Comment by bugith** [comment]
In order to highlight the different warnings (subdir vs parent) maybe different color should be used, e.g. red for subdir, and orange for parent. Whatever that wouldn't solve this #3433 malfunction.

**Comment by canton7** [comment]
I thinking "randomly" (from a user's perspective) changing the colour of the error message does nothing to help clarify it.

**Comment by bugith** [comment]
I didn't say randomly : I said subdir related message could be red (and even bold), when parent related could be orange. These colors meaning are widely known by any not-impaired car drivers. I don't see any random therein, this is all but random.

**Comment by canton7** [comment]
You're trying to indicate that one's a warning, and one's an error? OK, that wasn't clear.

It's very rare to see a UI display warnings as field validation - field validations are almost always errors. If I saw an orange field validation message, I wouldn't think "Oh, this is more of an orange than a red, and therefore it must be a warning that I can ignore", I would think "Oh, an error". 

If you're trying to say that something is a warning rather than an error, I think a better way is tell the user that it's a warning in the message.

**Comment by AudriusButkevicius** [comment]
Both messages warn about the same underlying problem, so I am not sure why they should be different?

**Comment by bugith** [comment]
@AudriusButkevicius you're right as log as the user Saves the currently selected path, whether it is a parent or subdir, as it will end in (a) nested share(s), and for this **red** is **the** color and there is nothing to argue.
But : **as there is no popup** for validation in the end and 2 different dynamic messages may appear* in the step-by-step process of selecting a path, displaying easily eyes-catching distinguished message may be of some help. Whatever, for the translation I work on, I used this way : for subdir case I use uppercase "WARNING, blah blah...del or dups"(because there is more chances this is yet a **wrong** idea from the newb), and for the parent case I used the simple "Warning, bloh bloh,...del or dups, so you should create a new dir." because this message appears as soon as we are in the path field and hit a nux "/" or win "\" in selection process and ST can't know if we are going to a more precise independent path or if we will Save at this very step showing the "...is a parent..." message, in which case we'd rather know what we are doing (and again red would be the color too).
Trying to be more precise on what may puzzle people, I'll describe what happens to me when selecting a path : First of all click "Add folder" : the "Add popup"...pops-up...with either one or the other warning displayed as per this very #3433 (because puzzled by the warning I canceled to retry ;-) which leaves as is the previous warning, Okay, let's admit and go on, there also may be no weird message at all): ~, hit "/" or ArrowDown, the "...parent..." warn message appears under the droplist full of my hidden .dirs in ~, then hit S (as I know my main dir is Sync), the drop-list with same 4 lines length gets nearly empty (single line for me as I have here a single dir with initial S) but still hidding the helper text that is no more followed by a warn (I can check this by hitting ArrowRight), complete "Sync" (either with letters or ArrowDown+ArrowRight), I see a new warning (must be about "parent" but still hidden by the drop-list now showing the list of my first 4 shares).... well now I understand better what was over-puzzling me : I zoomed-out firefox (Ctrl+- five times) so that I have a global  view of devices and folders, and this zoom also applied to "Add folder" popup, so the path drop-list was hiding the warnings :confused:
Okay. No even sure putting the warning above the field would be a good idea as message appearing/disappearing would make the field jump down and up... or would it be possible to have the ~drop~list expand to the top instead of the bottom?
Wouldn't a confirmation popup be welcome for the cases when the warnings are displayed ? This may appear as belt and braces, but "Are you really sure to create a nested share?" would be the last thing ST can do to prevent ignorant users to run in trouble. This is mainly because with the new 0.14.20 "...parent..." warning, the users will mostly see warnings all the time... until* they do things the right way ... well... after all that's not so bad... no warning means no soucy... and warning means warning. Okay.
 
*a funny thing is that the messages are often hidden by the path droplist
** but the warning may stall them... that's what I wanted to say since the very beginning of this post :1st_place_medal:

**Comment by wweich** [comment]
I think a better way would be to validate on blur instead of keydown (or keyup, I don't know what angular uses by default). Since Angular 1.3 you can set e.g. `{ 'updateOn': 'blur'}` in the `ng-model-options`.

That way, the "error" will only show, when the input is invalid after leaving the field.

**Comment by calmh** [comment]
That. We should do that.

**Comment by AudriusButkevicius** [comment]
Actually reopening this as the blur thing is not addressed.

**Comment by imsodin** [comment]
I should have mentioned that: I tried using it, but I didn't get it to work (very useful information, I know...).
Anyway I think the current behaviour of displaying the error while typing is actually a good thing. Imagine the case where the user enters the path and then directly clicks save. Currently the warning is already there, with validation on blur there never is a warning.

**Comment by AudriusButkevicius** [comment]
Fine.
