### ISSUE TITLE
syncthing trashes permissions on homedir

### ISSUE THREAD

**Issue by thePalindrome** [syncthing/syncthing#3434]
I'm running syncthing as a service, and would like for my unprivileged user to access specific shares. The permissions work out swimmingly, except for one small issue.

syncthing changes the permissions to 700 on the homedir, preventing any other user from accessing the subfolders within. The only fix I found was to change the owner to root, preventing syncthing from modifying permissions.

For an example setup, simply chmod the homedir 770, and then start syncthing. It will change the permissions back to 700, although everything inside the folder is still accessible.

Syncthing Version: v0.14.0
OS Version: Gentoo ~amd64

**Comment by calmh** [comment]
What is the "homedir" here - your home directory, the root of the synced folder, or the place where Syncthing stores it's configuration and database (`-home`)? I don't quite follow.

**Comment by thePalindrome** [comment]
In this case, I'm referring to the configuration folder specified with -home, I apologize for the ambiguity.

**Comment by calmh** [comment]
Right. We set that one 0700 on startup, yes, specifically to prevent other users from accessing it as it contains confidential information.

**Comment by thePalindrome** [comment]
I find that behaviour interesting, since it placed the default share within the homedir, meaning that only syncthing could actually read and/or write to the share. In this particular instance I find it counter-intuitive seeing as why have files synchronized if the user who should own the files isn't able to access it!

The Web UI also allows you to use ~ to auto-fill the homedir,  which seems to imply that shares would belong within the homedir, which puts everything in a rather curious state of not having normal users refer to it.

I suppose a good deal of these issues are because I'm running syncthing as a service, rather than a startup file under my user. Perhaps some -daemon flag would be of use here?

**Comment by canton7** [comment]
> I suppose a good deal of these issues are because I'm running syncthing as a service, rather than a startup file under my user.

Yes indeed. It is not recommended to run Syncthing as root (there are a whole host of security considerations for anyone doing this). All of the included service files (that I know of) are geared towards running Syncthing as specific users also, either on startup or on login.

**Comment by thePalindrome** [comment]
My apologies, I am not currently running syncthing as root.

Syncthing is currently running under a dedicated 'syncthing' user, with the homedir set as /var/lib/syncthing

The startup file I'm using starts it on boot, and for the moment I've had to modify it such that root owns /var/lib/syncthing, with 770 permissions, in order to have my normal user read the shares within.

**Comment by canton7** [comment]
You're supposed to run Syncthing as the user whose files it's syncing - that's the only way that makes sense from a permissions point of view.

The shares are supposed to be located in your normal home directory. That way both you, and Syncthing (which is running as you) can access them.

Syncthing's database directory ("home") is in a separate location to the shares, typically in `~/.config`.

**Comment by thePalindrome** [comment]
That may still be the case, but I would imagine another solution works well:

Instead of marking the entire homedir 700, preventing anything from being read within it, why not just mark the sensitive files 700, leaving the homedir's permissions alone?

That way the database remains secure, and shares are still placed within it.

**Comment by canton7** [comment]
> Instead of marking the entire homedir 700, preventing anything from being read within it, why not just mark the sensitive files 700, leaving the homedir's permissions alone?

As calmh said, Syncthing does NOT modify your home directory's permissions. It modifies the permissions of the folder which contains its database (perhaps confusingly set with the `-home` flag) - but this is NOT the home directory of the user which Syncthing is running as).

**Comment by thePalindrome** [comment]
I know, I'm using the term 'homedir' to refer to the directory specified as -home, which in this case also refers to the $HOME of the syncthing user.

So it is recommended in any syncthing setup to not have a system daemon restricted to the folder it has as home, but instead grant syncthing access to any and all personal files? Running it as a normal user introduces more security implications than a daemon user would.

**Comment by canton7** [comment]
> I know, I'm using the term 'homedir' to refer to the directory specified as -home, which in this case also refers to the $HOME of the syncthing user.

That will be why Syncthing is changing the permissions on its `$HOME` then. Please don't do this - put the database away in a subfolder of `$HOME` somewhere.

> So it is recommended in any syncthing setup to not have a system daemon restricted to the folder it has as home, but instead grant syncthing access to any and all personal files?

Since Syncthing is supposed to access your files, yes, this is the recommended setup. You could run Syncthing as a daemon user and use group permissions / ACLs to give it access to particular directories of yours if you want.

**Comment by calmh** [comment]
There is an unfortunate confusion of terms between `-home` and `$HOME` for historical reasons. I see where you're coming from now. The default setup assumes something like the following:

- $HOME=/home/jb
- Config dir, AKA `-home`: `$HOME/.config/syncthing`, that is `/home/jb/.config/syncthing` for example
- Default sync folder, `$HOME/Sync` that is `/home/jb/Sync` for example.

Your sync folders should never live under the config directory (`-home`)
