### ISSUE TITLE
0.14 stuck syncing

### ISSUE THREAD

**Issue by Gibbz** [syncthing/syncthing#3435]
- what happened,
Gets stuck syncing, with no progress after many days

 - what you expected to happen instead, and
should sync, or continue past whatever it in error?

 - any steps to reproduce the problem.
seems random, depends on the folder. Some work, some get stuck...

### Version Information

Syncthing Version: v0.14.y
OS Version: Ubuntuy 16.04

**Comment by calmh** [comment]
Check the logs for what's going on. "Gets stuck" is not something we can troubleshoot as is.

**Comment by Gibbz** [comment]
Attatched.
Database is about 800mb atm, which seems large?

[LOG.txt](https://github.com/syncthing/syncthing/files/380858/LOG.txt)

**Comment by calmh** [comment]
That's the database log, which doesn't help unfortunately. Syncthing logs to stdout, or wherever the installation might have pointed that.

**Comment by AudriusButkevicius** [comment]
Also, this is not really a bug until proven otherwise, so just open a thread on the forum with the logs as requested.

**Comment by Gibbz** [comment]
ah its just nuked my file system so i cant get a log for this :(
