### ISSUE TITLE
Database rebuild causes trouble

### ISSUE THREAD

**Issue by retsifp** [syncthing/syncthing#3441]
Since it's really hard for me to update all devices at the same time, I just updated one device a couple of days after the other ones. In the meantime, I deleted and modified some files.
The database-rebuild led to a problem: The files were just synced back, because the new client didn't know about all this.

I think this is clearly a bug and even #3430 won't fix this, since not all devices are online at the same time.

I didn't find a better headline, feel free to modify it :wink:

### Version Information

Syncthing Version: v0.14
OS Version: Debian Stretch

**Comment by calmh** [comment]
It's an unfortunate effect of the upgrade to an incompatible version. It's best to do that when the cluster is in sync.

**Comment by retsifp** [comment]
Well, but then all clients have to be online at the same time. That's nearly impossible for me  :hushed:

**Comment by calmh** [comment]
Yeah. We're hoping to minimize incompatible upgrades for the future.
