### ISSUE TITLE
Android client doesn't recognize connections when using VPN

### ISSUE THREAD

**Issue by CR0CKER** [syncthing/syncthing#3444]
When using VPN, the client acts as if it was on 3G, and since I have sync over 3G deactivated, it doesn't sync. This wasn't an issue until a recent update. Now, the client almost never recognizes an existing wifi connection when the VPN is turned on.

**Comment by CR0CKER** [comment]
Sorry, latest update seems to fix it.

**Comment by CR0CKER** [comment]
Unfortunately this problem still exists.

**Comment by calmh** [comment]
You probably want to talk to the Android people at https://github.com/syncthing/syncthing-android
