### ISSUE TITLE
Symlinks are ignored since 0.14.1

### ISSUE THREAD

**Issue by xduugu** [syncthing/syncthing#3445]
I have to following setup:

Device 1 - Folder A configured as `Master` - Linux amd64
Device 2 - Receives Folder A from Device 1 - Linux arm

Today, I ungraded Device 1 to 0.14.1 while Device 2 was still at 0.14.0. Since then, I get lots of info messages like:

```
[XYZXYZ] INFO: Puller: final: symlink  <path of symlink>: no such file or directory
```

on the receiving device (Device 2). Upgrading Device 2 to 0.14.1 didn't made any difference.

All of these symlinks already existed on Device 2, but for some reason were removed from it. This seems to affect all symlinks, independently if they point to an existing source or not. Although, the symlinks were remove on Device 2, they still exist on Device 1 and the `Master` Folder is not marked as `Out of Sync`.

### Version Information

Syncthing Version: v0.14.1

**Comment by xduugu** [comment]
I've build a syncthing binary for commit https://github.com/syncthing/syncthing/commit/2a6f164923580c0b12bf0456c6d5a49f7cca9b62. When using this binary on the scanning side (Device 1), the symlinks reappeared at Device 2 (still using 0.14.1).

Therefore, the issue seems to be caused by commit https://github.com/syncthing/syncthing/commit/7aaa1dd8a3a2b8e6b9c69b5e147858cefbb4e708.

**Comment by calmh** [comment]
Sounds reasonable :(
