### ISSUE TITLE
Global discovery servers not retried for 5xx class HTTP errors

### ISSUE THREAD

**Issue by cdhowie** [syncthing/syncthing#3447]
It appears that if a global discovery server responds with a 5xx class error (possibly only the first time, when Syncthing starts up -- I did not test to see what happens if a 5xx happens after a successful registration) then Syncthing will never retry registration with that server.  One of my nodes ran into a 500 error on all of the IPv4 discovery servers and has been undiscoverable for a few days, resulting in a relay being unnecessarily used for this duration for connections to all of its peers that can't themselves accept incoming connections.

Restarting the node resolved the problem.

Since the 5xx class of errors represent a problem with the server, it makes sense to me that this entire class be treated as a temporary failure, not a permanent one.

**Comment by AudriusButkevicius** [comment]
That's not true, looking at the code at least:
https://github.com/syncthing/syncthing/blob/master/lib/discover/global.go#L222

Did you try to repro it with STTRACE=discovery enabled?

**Comment by cdhowie** [comment]
Since the server isn't returning 500 errors now, I haven't been able to reproduce it.  I will have to set up a reverse proxy that can inject errors to test.

When I checked the UI, it showed 2/8 global discovery servers operational, both IPv6.  (The nodes trying to connect do not have IPv6 connectivity.)  The failed servers showed "500 Internal Server Error", and they stayed that way for several minutes as I was watching.  None of my other nodes reported this error for the IPv4 discovery servers, so I can only assume that this error was old -- especially considering that one of my other nodes could not connect (without using a relay) for over a full day.

The other nodes trying to connect reported a "negative cache entry" when I ran with STTRACE=discovery on them.  Immediately upon restarting the node reporting the 500 errors, it was able to register with the IPv4 discovery servers and after a few seconds my other nodes were again able to connect without a relay.

**Comment by AudriusButkevicius** [comment]
Negative cache entry is something that is controlled by the discovery servers, but I think it's fairly short.

 Failed announcement actualky defers announcements by a shorter period than successful announcement.

**Comment by cdhowie** [comment]
> Negative cache entry is something that is controlled by the discovery servers, but I think it's fairly short.

Right, to me this means simply that the discovery server doesn't know about the node at all.  This situation persisted for over a day, which is what leads me to the conclusion that the node wasn't trying to register anymore, especially given that a restart of the node immediately fixed the problem.

**Comment by AudriusButkevicius** [comment]
Can you actually reproduce this and then provide steps of reproducing this?

**Comment by cdhowie** [comment]
I will try to set up a test environment in the next few days and see if I can't get it to happen again.

**Comment by calmh** [comment]
Not reproduced, @cdhowie holler if you actually can and I'll reopen!
