### ISSUE TITLE
Index sorting should spill in home dir.

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#3449]
Why not?

If we are afarid we'll leave trash, we can clean up on start up.

**Comment by xduugu** [comment]
The current implementation probably also doesn't work as intended, at least on linux. As far as I understood, syncthing will sort in memory (inMemoryIndexSorter) and switch to disk (onDiskIndexSorter) after exceeding a size threshold. The onDiskIndexSorter creates a temporary directory in the default TempDir, which is /tmp on linux.

Nowadays, many linux distributions mount a tmpfs on /tmp, which is a RAM-based filesystem. So, the onDiskIndexSorter will in this case also sort in memory.

`ioutil.TempDir(syncthingHome, "syncthing-db.")` could be a good option to get this right.

**Comment by calmh** [comment]
`~/.config` nor `~/Library/Application Support` nor the roaming profile dir on Windows are really for temp files? The temporary directory is for temp files. I don't see why this is wrong.

**Comment by capi** [comment]
Since it panics if the directory indicated by `TMPDIR` is not present, it could at least fall-back to the home directory in case the parent directory does not exist.

**Comment by calmh** [comment]
It shouldn't panic, but I think a fatal error is legitimate. Things usually fail hard when told to use a temp directory that does not exist. There is no real Unixy system I'm aware of where /tmp does not exist...

```
jb@syno:~/s/g/s/syncthing $ TMPDIR=/nonexist go build ./cmd/syncthing
mkdir /nonexist/go-build611161318: no such file or directory

jb@syno:~/s/g/s/syncthing $ TMPDIR=/nonexist gcc test.c
error: unable to open output file '/nonexist/test-730b95.o': 'No such file or directory'
1 error generated.
```

**Comment by calmh** [comment]
Maybe the space issue is a good enough reason to do it in our normal config/db dir though:

https://forum.syncthing.net/t/syncthing-0-14-2-crashes-after-minutes-while-talking-with-peer/7894


... :/

**Comment by wweich** [comment]
`/tmp` doesn't exist in Android and NAS Boxes seam to somtimes have small `tmp` mounts.

**Comment by calmh** [comment]
Yeah. Android is supposed to be handled otherwise anyway, but the space issue seems prevalent enough. Lets keep it in our regular database dir.

**Comment by Tstassin** [comment]
I authored this post : [](https://forum.syncthing.net/t/syncthing-0-14-2-crashes-after-minutes-while-talking-with-peer/7894)
Can confirm that my /tmp is in memory
Can confirm that by exporting TMPDIR to some tmp folder on disk works, no more crash.
Have 512Mb RAM for memory, which is 32% full before starting syncthing on my NAS.

**Comment by xduugu** [comment]
> ~/.config nor ~/Library/Application Support nor the roaming profile dir on Windows are really for temp files? The temporary directory is for temp files. I don't see why this is wrong.

There is nothing wrong, it was just an unfortunate choice (which I also only noticed today) in this case as using a RAM filesystem as fallback in case there is too little memory, will not work. tmpfs uses half of the RAM as filesystem size by default, so chances are that the disk fallback will have even less storage space as the InMemorySorter.

I think using the syncthing home is the easiest option, but if someone is interested these are the cache directories for the different OS according to [appdirs](https://pypi.python.org/pypi/appdirs):

```
OS X: /Users/trentm/Library/Caches/SuperApp
Windows: C:\\Users\\trentm\\AppData\\Local\\Acme\\SuperApp\\Cache
Linux: /home/trentm/.cache/SuperApp
```

**Comment by calmh** [comment]
Mmm. Let's stick to our config dir for now as we're anyway misusing it for the database.
