### ISSUE TITLE
panic: leveldb: internal key 0x03 len invalid length

### ISSUE THREAD

**Issue by Xeenych** [syncthing/syncthing#3455]
Syncthing starts and immediatelly shuts down in panic 
[panic-20160728-100714.log.txt](https://github.com/syncthing/syncthing/files/387844/panic-20160728-100714.log.txt)

### Version Information

Syncthing Version: v0.14.2
OS Version: Windows 7

**Comment by calmh** [comment]
Looks like the database is corrupt on disk. You'll probably need to remove it and rescan. Typical suspects are bad memory and bad disks.

**Comment by Xeenych** [comment]
But how to remove database? GUI is not accesible

**Comment by scienmind** [comment]
@Xeenych : When syncthing is closed, remove/rename the index folder, and run syncthing again.

**Comment by Xeenych** [comment]
Thanks. ST started succesfully and began reindexing
