### ISSUE TITLE
Syncthing keeps re-adding devices to folders

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing#3456]
Even when I do not have a device set as an Introducer, I keep having this exact same issue, over and over and over x10000 again: No matter how many times I go into a folder's Edit properties and remove a remote device from synchronizing it, sooner or later the device will be checkmarked all over again without me touching a thing. I have reboot the Syncthing server as prompted every time and have even gone further to go on each device individually and remove the one device I want to not synchronize from that same folder's Edit properties.

See the attached log file - I removed folder "Passkeep" from synchronizing with my "Work" pc and my "OLD.Nexus 9" tablet at 8:33am EST, in which the remote computers added themselves back to the folder around 8:36am EST. (Syncthing.tar.zip) 

[syncthing.tar.zip](https://github.com/syncthing/syncthing/files/388369/syncthing.tar.zip)

**Comment by calmh** [comment]
```
[K4LKB] 08:36:09 INFO: Adding device J4UIFZM to share "Bnj&.aLH" (vouched for by introducer VIHHVWG)
[K4LKB] 08:36:09 INFO: Adding device SSQSFBG to share "Bnj&.aLH" (vouched for by introducer VIHHVWG)
```

**Comment by jebeld17** [comment]
Well, I see it on my screen. I don't know what to tell you.

**Comment by calmh** [comment]
... what? You're back now to revive this half a year later? :D
