### ISSUE TITLE
Delta indexes doesn't play well with changing ignores

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3457]
We process incoming index updates according to the ignore patterns, to filter out unwanted entries. When ignore patterns changed to allow files that were previously filtered out things would be OK on the next index exchange / reconnect. Currently, there is no new index exchange so the new ignore patterns don't get matched against the remote index data.

We need to either save all the data and process it differently, or as a workaround drop the delta index data when ignore patterns change.

**Comment by plouj** [comment]
Is it potentially a lot of data to keep that may never be used? Do people
change ignores very often?

**Comment by canton7** [comment]
Would it make sense to always accept (and never filter) incoming index entries, but to make ones we don't care about as "ignored" in the database (and not try and pull them)?

I have a suspicion that would also help solve the "my folder's out of sync because I have ignore patterns" issue...

**Comment by calmh** [comment]
Yes, I think something like that.

**Comment by AudriusButkevicius** [comment]
We could also scan (as in walk, and mark as invalid with no blocks) files that are ignored locally be of any benefit? And potentially advertising them?

**Comment by canton7** [comment]
Does it make subsequent scans cheaper, as you're not having to match ignored files against the ignore rules each time?

**Comment by scienmind** [comment]
Is there any way to work around it manually for now? 
(i.e. force an index exchange for a certain repo)

I had to exclude few subfolders from syncing, now all related repos are stuck on "Out of sync" due to excluded folders. And it seems that this issue is the cause.
(the exclusion done via `#include...`+`.stglobalignore`)

**Comment by AudriusButkevicius** [comment]
Remove the folder ans readd it, which will force a rescan.
