### ISSUE TITLE
Odd behaviour when syncing a folder ending with a space on Windows

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#3458]
Interesting issues with syncthing folders which containing a trailing space between Linux and Windows.

Setup is one Linux machine running Syncthing, and one Windows machine, both running 0.14. Assume a rescan after each command.

#### Linux
Create a folder called "test " (with the trailing space), with a file (called "file") inside

#### Windows
```
[UAL5T] 20:27:59 WARNING: File name "test " (folder "Docs") contains invalid characters; marked as invalid.
[UAL5T] 20:27:59 INFO: Resurrecting directory \\?\C:\<Path>\Docs\test 
```
... but the folder is created with a trailing space anyway.

Rename the folder to "test" (with no trailing space) - I had to use bash to do this, but there are probably neater ways.

#### Linux

Folders "test" and "test " both exist now.

Remove "test "

#### Windows

Syncthing tries to delete "file", but that fails with the error `GetFileAttributesEx \\?\C:\<Path>\Docs\test : The system cannot fine the file specified.`

There is a way to get Syncthing to delete the contents of that folder, but I haven't managed to reproduce it. It probably has something to do with two Windows computers and a Linux computer, all being on at different points.

I've also had an issue where Syncthing kept resurrecting the folder with a space in on the Windows side, but again, not (yet) reproducible.

Thanks!

**Comment by AudriusButkevicius** [comment]
There was a patch marking files with trailing spaces as invalid. Looking at the log it seems to be the case, not sure where the resurrecting thing comes from.

**Comment by AudriusButkevicius** [comment]
Ah ok, I see how this happens.

**Comment by calmh** [comment]
Right. If the folder is invalid, so should the files inside be...
