### ISSUE TITLE
Document the architecture of Synching!

### ISSUE THREAD

**Issue by aadrian** [syncthing/syncthing#3459]
Please document the architecture of Syncthing (and the design decisions).

I'm aware that the used protocols: BEP, Global Discovery, Local Discovery, and Relay are documented (the "RFC" style :) ), and I've red the "For Developers" section of the docs, but it would really help more users get up to speed and to contribute if there were some architecture docs and design decision and trade-off explanations.

Just "look at the source code" does not help IMHO.

Thanks in advance.

**Comment by AudriusButkevicius** [comment]
Define architecture. It's totally not clear what you are asking for.

**Comment by calmh** [comment]
I have a start on "how syncthing syncs" that talks about indexes and blocks and stuff that would probably be useful, just haven't had the time/energy/drive to finish it.

**Comment by aadrian** [comment]
@calmh IMHO anything could help, even if not "final" yet.  The Github WIKI section of this project might be a good place. 

I found allot of information in the forums, especially the team's explanation on various themes, but unfortunately is very hard to put the pieces together, but also to qualify if the information is not already obsolete, or it's already implemented, or it was just a hypotheses.

**Comment by calmh** [comment]
I agree (although I don't think the wiki here is the place for it, as we have the docs site). That said, is this an issue that is actionable enough that we can say "solved!" and close it at some point? If so, we should narrow down what the requirement is.

**Comment by aadrian** [comment]
> I don't think the wiki here is the place for it, as we have the docs site

I was just suggesting the WIKI since the docs site seem more "final" or "published" :).

> is this an issue that is actionable enough that we can say "solved!" and close it at some point?

IMHO it is. It's just that new developers and users can't help you since this is needed to get new developers in the project in first place :) .

**Comment by AudriusButkevicius** [comment]
You still haven't explained what you are after, and I have a habbit of closing tickets without measurable goals.

**Comment by calmh** [comment]
Yes. I'm asking "what document satisfies this ticket, so that it may close it when written"?

**Comment by aadrian** [comment]
@AudriusButkevicius 

> Define architecture.

https://en.wikipedia.org/wiki/Software_architecture  :)

> You still haven't explained what you are after

I think I did, but here's one more time with other words: Create missing (since the are some docs for the protocols) architecture documents for new developers to be able to get up to speed with the development of Syncthing. 

It should contain the minimal required information to be able to understand how and why it's architected and coded the way it is, so for the new developers to not be required to painfully "reverse engineer" the know-how by trial and error of an the existing system.

To have a better "feeling" for what's needed, consider that for whatever reasons you need to hire other new developers to take over the project and implement the long list of outstanding issues, fix the bugs, maintain and support. From the know-how you have now, what needs to be written down (since it's only in your brain) so that the above task is successful, considering the you can only expect the average Golang developer. 
This is quite a typical scenario in most software companies :).

**Comment by calmh** [comment]
Yeah. I think we're all roughly aware of what software architecture means. However I also think I can say with some confidence that such an architecture document that you're envisioning won't be written while there's still code to write. That's not to say some overview material can't be written.
