### ISSUE TITLE
discosrv is not reproductible

### ISSUE THREAD

**Issue by aviau** [syncthing/syncthing#3460]
It looks like the discosrv binary is not reproductible.

I haven't investigated much yet, but here is a diff:
 - https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/syncthing/diffoscope.html

Edit: 

ha, it looks like its because of the BuildStamp? https://github.com/syncthing/syncthing/blob/master/cmd/stdiscosrv/main.go#L28

We should do something like https://github.com/syncthing/syncthing/commit/80fd6c2400868a24ffd104babd2ddf35c3ff9f0e

**Comment by calmh** [comment]
Should use the same value and be as reproducible as the regular Syncthing build?

**Comment by aviau** [comment]
Yeah, that would be great.

**Comment by calmh** [comment]
I mean that since it's built by the same script it should already be as reproducible as Syncthing is.

**Comment by aviau** [comment]
Right, I just tested and it looks like stdiscosrv indeed uses the the ```main.<property>``` build flags. So it must be something else that makes it unreproductible.

**Comment by aviau** [comment]
Looking at the diff, zappy might be responsible. I'll forward the bug there until proven otherwise:
 - https://github.com/cznic/zappy/issues/6

**Comment by calmh** [comment]
I'm not sure you're barking up the right tree. The linker output (and that looks like debug symbols) is hardly controlled by the package author. Also I see the two builds are done in different directories which will always cause diffs as the source file paths are encoded into the binaries.

**Comment by aviau** [comment]
> I see the two builds are done in different directories which will always cause diffs as the source file paths are encoded into the binaries

I wonder why that would only affect stdiscosrv's deb then?

That looks like its related to https://bugs.debian.org/824806

**Comment by aviau** [comment]
This was fixed in golang 1.7 but it looks like https://tests.reproducible-builds.org still build with 1.6.

You were right, its not in zappy's control.

**Comment by calmh** [comment]
Ah, I see. The random paths are chosen by the go compiler during cgo processing. That makes sense.

**Comment by aviau** [comment]
> I'm guessing you're cowboying the build on your own here

Yes, as always.

I'm uploading a version of Syncthing with ``-tags purego``. We will see if that fixes the issue.

Thanks for the tip.
