### ISSUE TITLE
Rename "local version" to "sequence number"

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3461]
The name "local version" stems from when there was a single integer version per file that was cluster-global, and then this "local" version number beside it. Nowadays the versioning is much more advanced than just an integer, and the local version isn't really a "version" in any real sense of the word.

It is however a sequence number that is incremented on every change, and lets devices know where in the sequence to resume index sending and so on. So renaming it to that would make more sense to me.

```diff
--- a/lib/protocol/bep.proto
+++ b/lib/protocol/bep.proto
@@ -68,7 +68,7 @@ message Device {
     repeated string addresses    = 3;
     Compression     compression  = 4;
     string          cert_name    = 5;
-    int64           max_local_version = 6;
+    int64           max_sequence = 6;
     bool            introducer   = 7;
     uint64          index_id     = 8 [(gogoproto.customname) = "IndexID", (gogoproto.customtype) = "IndexID", (gogoproto.nullable) = false];
 }
@@ -102,7 +102,7 @@ message FileInfo {
     bool         invalid        = 7;
     bool         no_permissions = 8;
     Vector       version        = 9 [(gogoproto.nullable) = false];
-    int64        local_version  = 10;
+    int64        sequence       = 10;
 
     repeated BlockInfo Blocks = 16 [(gogoproto.nullable) = false];
 }
```

**Comment by AudriusButkevicius** [comment]
Agree

**Comment by scienmind** [comment]
It might be also worth changing the version variable to `uint64` to push wraparound chances even further.

**Comment by calmh** [comment]
I think I prefer keeping it an int64 with an explicit panic on negative sequence numbers. No-one will ever reach 2^63 index changes.

**Comment by scienmind** [comment]
Yeah, you're right.

At first I saw `mlv` jumping into 100K after a day... 
But doing the actual calculation: assume a file update is done every nano-second, then the counter will overflow after > 30 tera-years. So it's actually quite safe for (somewhat) near future.

**Comment by scienmind** [comment]
**Correction: It'll overflow after 293 K years...
(probably still OK though)

**Comment by calmh** [comment]
Yeah, 293k years for a million updates per second. If that's your use case Syncthing is not the thing. :)
