### ISSUE TITLE
panic: leveldb/table: corruption on data-block (pos=0):

### ISSUE THREAD

**Issue by nick-tech** [syncthing/syncthing#3465]
Since 0.13.7 or so I have to deal with the same problem with syncthing on my mac, I always hoped it would disappear with the next version but as it is still here with 0.14.3, I think I should report it:

Syncthing just crashes after every start. When I delete the database (syncthing -reset), syncthing starts normally and scans the folders. Afert about 50% scanning it crashes again. Here ist the log-File:

`[D6TNX] 17:25:19 INFO: syncthing v0.14.3 "Dysprosium Dragonfly" (go1.6.3 darwin-amd64) brew@elcapitanvm.local 2016-07-28 11:15:14 UTC
[D6TNX] 17:25:19 INFO: My ID: XXXX-XXXX-XXXX
[D6TNX] 17:25:19 INFO: Single thread hash performance is ~122 MB/s
[D6TNX] 17:25:21 INFO: Ready to synchronize B**(readwrite)
[D6TNX] 17:25:22 INFO: Ready to synchronize M** (readwrite)
[D6TNX] 17:25:22 INFO: Ready to synchronize c**(readwrite)
...
Panic at 2016-07-31T17:25:23+02:00
panic: leveldb/table: corruption on data-block (pos=0): checksum mismatch, want=0x222c5c3a got=0x6676beb6 [file=004278.ldb]

goroutine 1 [running]:
panic(0x7911e0, 0xc821838b40)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:481 +0x3e6
github.com/syncthing/syncthing/lib/db.(*Instance).checkGlobals(0xc82024b080, 0xc8202e67a0, 0x13, 0x20, 0xc82023a5c8)
	/private/tmp/syncthing-20160729-93441-1nw7357/.syncthing-gopath/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:600 +0x803
github.com/syncthing/syncthing/lib/db.NewFileSet(0xc8202cd880, 0x13, 0xc82024b080, 0xc8201fabf0)
	/private/tmp/syncthing-20160729-93441-1nw7357/.syncthing-gopath/src/github.com/syncthing/syncthing/lib/db/set.go:108 +0x2fb
github.com/syncthing/syncthing/lib/model.(*Model).AddFolder(0xc82018a000, 0xc8202cd880, 0x13, 0x0, 0x0, 0xc8202e6e80, 0x1b, 0x0, 0xc82023af00, 0x3, ...)
	/private/tmp/syncthing-20160729-93441-1nw7357/.syncthing-gopath/src/github.com/syncthing/syncthing/lib/model/model.go:1426 +0x14a
main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8c7250, 0x1, 0x0, 0x0, ...)
	/private/tmp/syncthing-20160729-93441-1nw7357/.syncthing-gopath/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:687 +0x1d41
main.main()
	/private/tmp/syncthing-20160729-93441-1nw7357/.syncthing-gopath/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:364 +0x95a
 `

**Comment by AudriusButkevicius** [comment]
Search the forum or closed issues.
It's most likely a hardware problem.

**Comment by 5chdn** [comment]
#2734 has the best fix description so far.

> There is no way to recover from this apart from nuking index directory in syncthings home directory (check -help).

And, the best snippet: 

> I deleted only the corrupted file and it is working again.

See also #987 #1853 #1949 #2479 #3157 and so on.
