### ISSUE TITLE
Linux build crashes Netgear WNCE2001 when using Ubuntu

### ISSUE THREAD

**Issue by Forceu** [syncthing/syncthing#3475]
Somehow my Netgear WNCE2001 crashes when Syncthing is actively syncing.

The WNCE2001 is a wifi-lan bridge that is currently connected to a switch which is connected to my desktop computer and several other devices. If I am syncing my desktop with a wifi device I experience very low speeds (around 100 KB/s) and the WNCE2001 starts indicating poor wifi reception. After around 30 seconds it reboots.

Interestingly enough, this does not happen with any other programs. I get around 8 MB/s when I download files and also SSH/SCP connections between devices are full speed and do not cause any problems. Regular torrents don't impact the connectivity in any way either.

Also this only happens when using Ubuntu, the Windows build on the same computer receives all items with full speed and does not crash the Netgear bridge. I also just tried it with the Knoppix LiveCD, and it doesn't seem to happen on there.

I am using Ubuntu 16.04 and Syncthing v0.14.3, the problem exists with the 32 and 64 bit build and the static build as well as with the DEB-installation. Also this problem existed for at least a year now with earlier versions. 

I realize it will be really hard to find the problem without more detailed information / logs, but maybe someone has an idea what could cause the problem?

**Comment by AudriusButkevicius** [comment]
Firstly software should never be able to crash hardware unless the hardware is not meant to be used for the thing it's being used for, which honestly seems to be the case here.

Furthermore, it doesn't look like syncthing bug, but rather hardware or OS bug, hecen I am closing this, as there is nothing actionable from our side.

If you want to pursue this, I suggest you open a forum thread, and potentially provide kernel logs of the embedded device. 

I suspect that Ubuntu TCP stack is configured differently from other OSes and simply spits out many more packets.

Another thing which you might want to try is applying rate limits.

**Comment by Forceu** [comment]
I do realize that it is a problem with the hardware, however it is used as being intended and even setting a rate limit to very low values like 10 KB/s does still trigger it. And like I said, it only happens with Syncthing, not even with torrent applications and up to 500 connected peers, therefore the problem must partly lie with Syncthing as well :/
I'll try to open up the wifi bridge and see if there is a serial port, maybe that way it is possible to get concrete information about the problem.
