### ISSUE TITLE
Constant crash on macOS Sierra beta 4 with Syncthing 0.14.3

### ISSUE THREAD

**Issue by deadbird99** [syncthing/syncthing#3487]
Everything's in the title.

Here's a part of the log:

[O5AB7] 00:10:43 INFO: Device AEX3GGH-QTQQVIZ-ZX5ZF4P-ENZ3MZH-PCWSWES-TB4OCS5-M2Y5MJK-OPCBVAJ is "NAS" at [dynamic]
[O5AB7] 00:10:43 INFO: Device O5AB7XU-RAPTCJS-6AEHQBU-WURGA5D-Q5PEPHY-26ZCMWT-LOETNEN-AMOLWQ4 is "iMac.local" at [dynamic]
[O5AB7] 00:10:43 INFO: Starting usage reporting
[O5AB7] 00:10:43 INFO: GUI and API listening on 127.0.0.1:8384
[O5AB7] 00:10:43 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[O5AB7] 00:10:43 INFO: Established secure connection to AEX3GGH-QTQQVIZ-ZX5ZF4P-ENZ3MZH-PCWSWES-TB4OCS5-M2Y5MJK-OPCBVAJ at 192.168.1.11:64419-188.165.197.41:22000 (TCP (Client))
[O5AB7] 00:10:43 INFO: Device AEX3GGH-QTQQVIZ-ZX5ZF4P-ENZ3MZH-PCWSWES-TB4OCS5-M2Y5MJK-OPCBVAJ client is "syncthing v0.14.3" named "NAS"
[O5AB7] 00:10:43 INFO: Device AEX3GGH-QTQQVIZ-ZX5ZF4P-ENZ3MZH-PCWSWES-TB4OCS5-M2Y5MJK-OPCBVAJ folder "sync" is delta index compatible (mlv=3)
[O5AB7] 00:10:43 INFO: Automatic upgrade (current "v0.14.2" < latest "v0.14.3")
[O5AB7] 01:00:14 INFO: Could not connect to relay relay://172.110.20.244:22067/?id=UCB73TW-U7PECMW-OFBZDU3-ISKIEDE-NZXDAKY-YWDFSXJ-VADBLOW-3LUHLQR&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=0&statusAddr=:22068&providedBy=lorvent - New York, US: dial tcp 172.110.20.244:22067: i/o timeout
[O5AB7] 01:00:14 INFO: Could not connect to relay relay://51.254.126.115:443/?id=47APV67-F6L6GNB-DYINKSI-CNF5ENG-BOQFYTJ-S5MGNRW-YSWOZPN-VILSFAI&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=0&statusAddr=:22070&providedBy=RhyeWorld - IT: dial tcp 51.254.126.115:443: i/o timeout
unexpected fault address 0x14b6c200b8f1
fatal error: fault
[monitor] 01:00:14 WARNING: Panic detected, writing to "/Users/deadbird/Library/Application Support/Syncthing/panic-20160809-001052.log"
[monitor] 01:00:14 WARNING: Please check for existing issues with similar panic message at https://github.com/syncthing/syncthing/issues/
[monitor] 01:00:14 WARNING: If no issue with similar panic message exists, please create a new issue with the panic log attached
[monitor] 00:10:52 INFO: Syncthing exited: exit status 2
[monitor] 00:10:53 INFO: Starting syncthing
panic: sync: inconsistent mutex state

goroutine 1 [running]:
panic(0x6873e0, 0xc8201a2800)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
sync.(*Mutex).Lock(0xc82000fb98)
	/usr/local/go/src/sync/mutex.go:75 +0x16d
main.monitorMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8e4478, 0x1, 0x0, 0x0, ...)
	/Users/jb/jenkins/workspace/syncthing-release-mac/src/github.com/syncthing/syncthing/cmd/syncthing/monitor.go:104 +0xccf
main.main()
	/Users/jb/jenkins/workspace/syncthing-release-mac/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:366 +0x977
iMac:syncthing deadbird$

**Comment by AudriusButkevicius** [comment]
Check closed issues.

**Comment by deadbird99** [comment]
Why are you closing the issue? Has it already been solved or something?

**Comment by AudriusButkevicius** [comment]
There is nothing we can do from our side.

**Comment by deadbird99** [comment]
But the trace states that the issues is on syncthing's side, no?

**Comment by AudriusButkevicius** [comment]
No, this is a go runtime issue for which release hasn't been released.

**Comment by MoOx** [comment]
For future users like me https://forum.syncthing.net/t/syncthing-not-running-in-macos-sierra-beta/7762/25
