### ISSUE TITLE
segfault on macOS 10.12 beta (16A270f)

### ISSUE THREAD

**Issue by cloudkucooland** [syncthing/syncthing#3488]
scot@Origami:/Users/scot/Library/Application Support/Syncthing % /Users/scot/Applications/syncthing/syncthing
[monitor] 17:23:44 INFO: Starting syncthing
[OXEU3] 17:23:44 INFO: syncthing v0.14.3 "Dysprosium Dragonfly" (go1.6.3 darwin-amd64) jenkins@build.syncthing.net 2016-07-28 11:15:14 UTC
[OXEU3] 17:23:44 INFO: My ID: OXEU3TM-5LGA6DW-G2HQ4EP-VQVXNHM-HXUMWCV-KMPY2I4-YKXBQ3C-ZCOCEQH
[OXEU3] 17:23:44 INFO: Single thread hash performance is ~144 MB/s
[OXEU3] 17:23:44 INFO: Ready to synchronize caring (readwrite)
[OXEU3] 17:23:44 INFO: Ready to synchronize Scot_Documents (readwrite)
[OXEU3] 17:23:44 INFO: Ready to synchronize default (readwrite)
[OXEU3] 17:23:44 INFO: Using discovery server https://discovery-v4-1.syncthing.net/v2/?id=SR7AARM-TCBUZ5O-VFAXY4D-CECGSDE-3Q6IZ4G-XG7AH75-OBIXJQV-QJ6NLQA
[OXEU3] 17:23:44 INFO: Using discovery server https://discovery-v4-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[OXEU3] 17:23:44 INFO: Using discovery server https://discovery-v4-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[OXEU3] 17:23:44 INFO: TCP listener ([::]:22000) starting
[OXEU3] 17:23:44 INFO: Using discovery server https://discovery-v6-1.syncthing.net/v2/?id=SR7AARM-TCBUZ5O-VFAXY4D-CECGSDE-3Q6IZ4G-XG7AH75-OBIXJQV-QJ6NLQA
[OXEU3] 17:23:44 INFO: Using discovery server https://discovery-v6-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[OXEU3] 17:23:44 INFO: Using discovery server https://discovery-v6-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[OXEU3] 17:23:44 INFO: Completed initial scan (rw) of folder caring
[OXEU3] 17:23:44 INFO: Device 7FROVNV-WNLDGJ6-2VX5H7Q-6UCCCBX-SKPDUG3-66FC35P-ECB6FS5-ZSIKEAM is "Lilith" at [dynamic]
[OXEU3] 17:23:44 INFO: Device AQQMJRQ-3XO4XM2-DPPTI6Q-I23PDLT-UMR4B6M-U3SCQ22-B4G6K4N-SXFUFAP is "SCOTB" at [dynamic]
[OXEU3] 17:23:44 INFO: Device BRXPXRX-FZTXJNW-G3XCZF4-U3N3B5R-LCV2JGE-E7ZB4CY-7N7VNUL-E3VO3QZ is "Etheriel" at [dynamic]
[OXEU3] 17:23:44 INFO: Device OXEU3TM-5LGA6DW-G2HQ4EP-VQVXNHM-HXUMWCV-KMPY2I4-YKXBQ3C-ZCOCEQH is "Origami" at [dynamic]
[OXEU3] 17:23:44 INFO: Device X7N533J-Q7ZMXOL-4YOGA3F-WAKRBDG-XKMZUO3-5TS3QOO-VRQS6CK-WYLIHAW is "scar" at [dynamic]
[OXEU3] 17:23:44 INFO: Device 3T22QJH-MT3PB4X-BK2URDC-25DFR7Q-R6JREFL-HLTFNEK-SWQ33RY-CEPXOQ3 is "covert.indievisible.org" at [dynamic]
[OXEU3] 17:23:44 INFO: Starting usage reporting
[OXEU3] 17:23:44 INFO: GUI and API listening on 127.0.0.1:8080
[OXEU3] 17:23:44 INFO: Access the GUI via the following URL: http://127.0.0.1:8080/
[OXEU3] 17:23:44 INFO: Completed initial scan (rw) of folder default
[OXEU3] 17:23:55 INFO: Detected 1 NAT device
[OXEU3] 17:24:00 INFO: Established secure connection to BRXPXRX-FZTXJNW-G3XCZF4-U3N3B5R-LCV2JGE-E7ZB4CY-7N7VNUL-E3VO3QZ at [fe80::821:2293:1936:a97%en1]:50885-[fe80::ae87:a3ff:fe01:a6ad%en1]:22000 (TCP (Client))
[OXEU3] 17:24:00 INFO: Device BRXPXRX-FZTXJNW-G3XCZF4-U3N3B5R-LCV2JGE-E7ZB4CY-7N7VNUL-E3VO3QZ client is "syncthing v0.14.3" named "Etheriel"
[OXEU3] 17:24:00 INFO: Device BRXPXRX-FZTXJNW-G3XCZF4-U3N3B5R-LCV2JGE-E7ZB4CY-7N7VNUL-E3VO3QZ folder "Scot_Documents" is delta index compatible (mlv=1935)
[OXEU3] 17:24:00 INFO: Device BRXPXRX-FZTXJNW-G3XCZF4-U3N3B5R-LCV2JGE-E7ZB4CY-7N7VNUL-E3VO3QZ folder "default" is delta index compatible (mlv=1650)
[OXEU3] 17:24:02 INFO: Joined relay relay://43.239.250.13:443
[OXEU3] 17:24:03 INFO: Established secure connection to X7N533J-Q7ZMXOL-4YOGA3F-WAKRBDG-XKMZUO3-5TS3QOO-VRQS6CK-WYLIHAW at 192.168.1.87:50898-69.164.210.237:22067 (Relay (Client))
[OXEU3] 17:24:03 INFO: Device X7N533J-Q7ZMXOL-4YOGA3F-WAKRBDG-XKMZUO3-5TS3QOO-VRQS6CK-WYLIHAW client is "syncthing v0.14.3" named "scar"
[OXEU3] 17:24:03 INFO: Device X7N533J-Q7ZMXOL-4YOGA3F-WAKRBDG-XKMZUO3-5TS3QOO-VRQS6CK-WYLIHAW folder "caring" has mismatching index ID for us (0x4C75BF47E632A1CB != 0x80E694D1EC66995B)
[OXEU3] 17:24:03 INFO: Device X7N533J-Q7ZMXOL-4YOGA3F-WAKRBDG-XKMZUO3-5TS3QOO-VRQS6CK-WYLIHAW folder "caring" has a new index ID (0xCC4E96605CD5453D)
[OXEU3] 17:24:03 INFO: Device X7N533J-Q7ZMXOL-4YOGA3F-WAKRBDG-XKMZUO3-5TS3QOO-VRQS6CK-WYLIHAW folder "default" has mismatching index ID for us (0x3134C993E136922A != 0xB3B2CCAA57569816)
[OXEU3] 17:24:03 INFO: Device X7N533J-Q7ZMXOL-4YOGA3F-WAKRBDG-XKMZUO3-5TS3QOO-VRQS6CK-WYLIHAW folder "default" has a new index ID (0x  81AFF4CB9D1D7A)
[OXEU3] 17:24:08 INFO: Established secure connection to 3T22QJH-MT3PB4X-BK2URDC-25DFR7Q-R6JREFL-HLTFNEK-SWQ33RY-CEPXOQ3 at 192.168.1.87:50907-192.168.1.253:22000 (TCP (Client))
[OXEU3] 17:24:08 INFO: Device 3T22QJH-MT3PB4X-BK2URDC-25DFR7Q-R6JREFL-HLTFNEK-SWQ33RY-CEPXOQ3 client is "syncthing v0.14.3" named "covert.indievisible.org"
[OXEU3] 17:24:08 INFO: Device 3T22QJH-MT3PB4X-BK2URDC-25DFR7Q-R6JREFL-HLTFNEK-SWQ33RY-CEPXOQ3 folder "default" has mismatching index ID for us (0x3134C993E136922A != 0xB3B2CCAA57569816)
[OXEU3] 17:24:08 INFO: Device 3T22QJH-MT3PB4X-BK2URDC-25DFR7Q-R6JREFL-HLTFNEK-SWQ33RY-CEPXOQ3 folder "default" has a new index ID (0x806F957BE0B3FD2A)
[OXEU3] 17:24:08 INFO: Device 3T22QJH-MT3PB4X-BK2URDC-25DFR7Q-R6JREFL-HLTFNEK-SWQ33RY-CEPXOQ3 folder "Scot_Documents" has mismatching index ID for us (0xAF1766523DA8CF5C != 0xEEEBE524CD80E9D6)
[OXEU3] 17:24:08 INFO: Device 3T22QJH-MT3PB4X-BK2URDC-25DFR7Q-R6JREFL-HLTFNEK-SWQ33RY-CEPXOQ3 folder "Scot_Documents" has a new index ID (0x A85BD2066FCCA79)
panic: sync: inconsistent mutex state
[monitor] 17:24:12 WARNING: Panic detected, writing to "/Users/scot/Library/Application Support/Syncthing/panic-20160808-172412.log"
[monitor] 17:24:12 WARNING: Please check for existing issues with similar panic message at https://github.com/syncthing/syncthing/issues/
[monitor] 17:24:12 WARNING: If no issue with similar panic message exists, please create a new issue with the panic log attached
[monitor] 17:24:12 INFO: Syncthing exited: exit status 2
[monitor] 17:24:13 INFO: Starting syncthing
[OXEU3] 17:24:13 INFO: syncthing v0.14.3 "Dysprosium Dragonfly" (go1.6.3 darwin-amd64) jenkins@build.syncthing.net 2016-07-28 11:15:14 UTC
[OXEU3] 17:24:13 INFO: My ID: OXEU3TM-5LGA6DW-G2HQ4EP-VQVXNHM-HXUMWCV-KMPY2I4-YKXBQ3C-ZCOCEQH
[OXEU3] 17:24:13 INFO: Single thread hash performance is ~142 MB/s
[OXEU3] 17:24:13 INFO: Ready to synchronize caring (readwrite)
[OXEU3] 17:24:13 INFO: Ready to synchronize Scot_Documents (readwrite)
[OXEU3] 17:24:13 INFO: Ready to synchronize default (readwrite)
[OXEU3] 17:24:13 INFO: Using discovery server https://discovery-v4-1.syncthing.net/v2/?id=SR7AARM-TCBUZ5O-VFAXY4D-CECGSDE-3Q6IZ4G-XG7AH75-OBIXJQV-QJ6NLQA
[OXEU3] 17:24:13 INFO: Using discovery server https://discovery-v4-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[OXEU3] 17:24:13 INFO: Using discovery server https://discovery-v4-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[OXEU3] 17:24:13 INFO: TCP listener ([::]:22000) starting
[OXEU3] 17:24:13 INFO: Using discovery server https://discovery-v6-1.syncthing.net/v2/?id=SR7AARM-TCBUZ5O-VFAXY4D-CECGSDE-3Q6IZ4G-XG7AH75-OBIXJQV-QJ6NLQA
[OXEU3] 17:24:13 INFO: Using discovery server https://discovery-v6-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[OXEU3] 17:24:13 INFO: Using discovery server https://discovery-v6-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[OXEU3] 17:24:13 INFO: Completed initial scan (rw) of folder caring
[OXEU3] 17:24:13 INFO: Device OXEU3TM-5LGA6DW-G2HQ4EP-VQVXNHM-HXUMWCV-KMPY2I4-YKXBQ3C-ZCOCEQH is "Origami" at [dynamic]
[OXEU3] 17:24:13 INFO: Device X7N533J-Q7ZMXOL-4YOGA3F-WAKRBDG-XKMZUO3-5TS3QOO-VRQS6CK-WYLIHAW is "scar" at [dynamic]
[OXEU3] 17:24:13 INFO: Device 3T22QJH-MT3PB4X-BK2URDC-25DFR7Q-R6JREFL-HLTFNEK-SWQ33RY-CEPXOQ3 is "covert.indievisible.org" at [dynamic]
[OXEU3] 17:24:13 INFO: Device 7FROVNV-WNLDGJ6-2VX5H7Q-6UCCCBX-SKPDUG3-66FC35P-ECB6FS5-ZSIKEAM is "Lilith" at [dynamic]
[OXEU3] 17:24:13 INFO: Device AQQMJRQ-3XO4XM2-DPPTI6Q-I23PDLT-UMR4B6M-U3SCQ22-B4G6K4N-SXFUFAP is "SCOTB" at [dynamic]
[OXEU3] 17:24:13 INFO: Device BRXPXRX-FZTXJNW-G3XCZF4-U3N3B5R-LCV2JGE-E7ZB4CY-7N7VNUL-E3VO3QZ is "Etheriel" at [dynamic]
[OXEU3] 17:24:13 INFO: Starting usage reporting
[OXEU3] 17:24:13 INFO: GUI and API listening on 127.0.0.1:8080
[OXEU3] 17:24:13 INFO: Access the GUI via the following URL: http://127.0.0.1:8080/
[OXEU3] 17:24:13 INFO: Completed initial scan (rw) of folder default
[OXEU3] 18:00:14 INFO: Could not connect to relay relay://176.31.181.189:22067/?id=3NWGDQV-2LIQVXO-PCZRZ5B-67MYR2T-XHQ64VD-6H4BLR7-XFKOLOI-C2XIVQ2&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=0&statusAddr=:22070&providedBy=: dial tcp 176.31.181.189:22067: i/o timeout
[OXEU3] 18:00:14 INFO: Could not connect to relay relay://199.15.254.138:443/?id=IJSA5SD-XD4QYF6-OQ4QSAC-MUVN3BE-SZZNDQS-CENSEUC-AJVJZSJ-DCDLLAR&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=0&statusAddr=:22070&providedBy=value for value: dial tcp 199.15.254.138:443: i/o timeout
unexpected fault address 0x4c10ee496e3
fatal error: fault
[monitor] 18:00:14 WARNING: Panic detected, writing to "/Users/scot/Library/Application Support/Syncthing/panic-20160808-172415.log"
[monitor] 18:00:14 WARNING: Please check for existing issues with similar panic message at https://github.com/syncthing/syncthing/issues/
[monitor] 18:00:14 WARNING: If no issue with similar panic message exists, please create a new issue with the panic log attached
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x4c10f288602 pc=0x524db]

runtime stack:
runtime.throw(0x9efec0, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0xebcd80)
	/usr/local/go/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0xebcd80, 0x1, 0x2000000000a, 0x16001e0)
	/usr/local/go/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7000025d8d40)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0xebcd80, 0x1, 0x1000000000a, 0x5217f)
	/usr/local/go/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0xebe4b0, 0x0)
	/usr/local/go/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0xebe4b0, 0x16001e0)
	/usr/local/go/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0x1054960, 0xc80000000a, 0x16001e0)
	/usr/local/go/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/usr/local/go/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0xc820019500)
	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1051

goroutine 14 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc82003da30 sp=0xc82003da28
runtime.mallocgc(0x90, 0x0, 0xc800000003, 0x8b)
	/usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0xc82003db08 sp=0xc82003da30
runtime.rawstring(0x8b, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/string.go:284 +0x70 fp=0xc82003db50 sp=0xc82003db08
runtime.rawstringtmp(0x0, 0x8b, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/string.go:111 +0xb7 fp=0xc82003db88 sp=0xc82003db50
runtime.slicebytetostring(0x0, 0xc8201fdef0, 0x8b, 0x8b, 0x0, 0x0)
	/usr/local/go/src/runtime/string.go:93 +0x6f fp=0xc82003dc20 sp=0xc82003db88
bufio.(*Reader).ReadString(0xc82003dea0, 0xc8201f7a0a, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:447 +0x9e fp=0xc82003dc78 sp=0xc82003dc20
main.copyStderr(0x10a99d0, 0xc82002c150, 0x10a81e8, 0xc82002c010)
	/Users/jb/jenkins/workspace/syncthing-release-mac/src/github.com/syncthing/syncthing/cmd/syncthing/monitor.go:173 +0xd2 fp=0xc82003df58 sp=0xc82003dc78
main.monitorMain.func1(0x10a9968, 0xc82002c150, 0xc82019a450, 0x10a9998, 0xc82019a840)
	/Users/jb/jenkins/workspace/syncthing-release-mac/src/github.com/syncthing/syncthing/cmd/syncthing/monitor.go:113 +0x69 fp=0xc82003df88 sp=0xc82003df58
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82003df90 sp=0xc82003df88
created by main.monitorMain
	/Users/jb/jenkins/workspace/syncthing-release-mac/src/github.com/syncthing/syncthing/cmd/syncthing/monitor.go:115 +0xe8b

goroutine 1 [select]:
main.monitorMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8e4cd8, 0x1, 0x0, 0x0, ...)
	/Users/jb/jenkins/workspace/syncthing-release-mac/src/github.com/syncthing/syncthing/cmd/syncthing/monitor.go:130 +0x1a08
main.main()
	/Users/jb/jenkins/workspace/syncthing-release-mac/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:366 +0x977

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 8 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 9 [chan receive]:
main.trackCPUUsage()
	/Users/jb/jenkins/workspace/syncthing-release-mac/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0xe7
created by main.init.3
	/Users/jb/jenkins/workspace/syncthing-release-mac/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x2b

goroutine 10 [select, locked to thread]:
runtime.gopark(0xa6c308, 0xc820024728, 0x8ed868, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820024728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820024728)
	/usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:279 +0x32c
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 15 [syscall]:
syscall.Syscall(0x3, 0x6, 0xc8201ea000, 0x1000, 0x131, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.read(0x6, 0xc8201ea000, 0x1000, 0x1000, 0x131, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:972 +0x5f
syscall.Read(0x6, 0xc8201ea000, 0x1000, 0x1000, 0x131, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:161 +0x4d
os.(*File).read(0xc82002c160, 0xc8201ea000, 0x1000, 0x1000, 0x131, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:228 +0x75
os.(*File).Read(0xc82002c160, 0xc8201ea000, 0x1000, 0x1000, 0x131, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x8a
bufio.(*Reader).fill(0xc820038ea0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc820038ea0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadBytes(0xc820038ea0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:406 +0xa9
bufio.(*Reader).ReadString(0xc820038ea0, 0xc8201ee60a, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:446 +0x4d
main.copyStdout(0x10a99d0, 0xc82002c160, 0x10a81e8, 0xc82002c010)
	/Users/jb/jenkins/workspace/syncthing-release-mac/src/github.com/syncthing/syncthing/cmd/syncthing/monitor.go:215 +0xbd
main.monitorMain.func2(0x10a9968, 0xc82002c160, 0xc82019a450, 0x10a9998, 0xc82019a840)
	/Users/jb/jenkins/workspace/syncthing-release-mac/src/github.com/syncthing/syncthing/cmd/syncthing/monitor.go:119 +0x69
created by main.monitorMain
	/Users/jb/jenkins/workspace/syncthing-release-mac/src/github.com/syncthing/syncthing/cmd/syncthing/monitor.go:121 +0xf07

goroutine 16 [semacquire]:
sync.runtime_Semacquire(0xc82019a84c)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc82019a840)
	/usr/local/go/src/sync/waitgroup.go:127 +0xb4
main.monitorMain.func3(0x10a9998, 0xc82019a840, 0xc820062c60, 0xc820086f00)
	/Users/jb/jenkins/workspace/syncthing-release-mac/src/github.com/syncthing/syncthing/cmd/syncthing/monitor.go:126 +0x27
created by main.monitorMain
	/Users/jb/jenkins/workspace/syncthing-release-mac/src/github.com/syncthing/syncthing/cmd/syncthing/monitor.go:128 +0xf71
scot@Origami:/Users/scot/Library/Application Support/Syncthing % 

[panic-20160808-172412.txt](https://github.com/syncthing/syncthing/files/407867/panic-20160808-172412.txt)
[panic-20160808-172415.txt](https://github.com/syncthing/syncthing/files/407868/panic-20160808-172415.txt)

**Comment by AudriusButkevicius** [comment]
See closed issues.

**Comment by MoOx** [comment]
For future users like me https://forum.syncthing.net/t/syncthing-not-running-in-macos-sierra-beta/7762/25
