### ISSUE TITLE
Cross platform path name

### ISSUE THREAD

**Issue by Elyjax** [syncthing/syncthing#3491]
Currently I use syncthing on a computer with both Windows and Linux installed. I think it would be cool to have a single syncthing config/database shared between the 2 OS. The only problem I see is that folder path are not the same. A simple solution that I propose is to add a checkbox below the folder path. If checked it would ask a second path for the other OS. Then you need to make syncthing load the correct path depending on the current OS. It's not a big feature but I think it would be convenient for those like me with multiple OS :).

**Comment by AudriusButkevicius** [comment]
Just use symlinks/hardlinks to solve the witchcraft you are trying to achieve .

**Comment by calmh** [comment]
The database contains folder-relative paths in slash format, so it should already be compatible.

**Comment by calmh** [comment]
The config may be difficult to have the same on both sides, but you can have separate configs and symlink the database.

**Comment by Elyjax** [comment]
I'm not sure symlinks can solve it. I'll try to explain with an example. I've got a folder Music shared between Windows and Linux. The windows version of config.xml (located at C:\User\...\AppData\Local\Syncthing) contains this line : folder id="uluyk-zyaod" label="Music" path="D:\Music" whereas the linux version (located at /home/.../.config/syncthing) contains this line : folder id="uluyk-zyaod" label="Music" path="/media/Data/Music". It's not only a difference of slash or backslash but the path is not the same.
My goal is to have a single config.xml (thus a single syncthing id for windows and linux). How can I tell syncthing that on windows my Music folder is at D:\Music and on linux at /media/Data/Music ? It's why I proposed to store both path in config.xml and then load the correct one. I thought it could be convenient but you're the devs so do as you want :).

**Comment by calmh** [comment]
Yeah, no. I agree that the goal of a single config.xml isn't possible today, but I also don't think it's something we should implement. The complexity isn't worth it. Sorry.

**Comment by AudriusButkevicius** [comment]
Syncthing ID is not in it's config, the exact same dual booting problem has been solved in the forums.

**Comment by Elyjax** [comment]
I have found the thread on the forum. I should have look at it before opening an issue, sorry. The best solution seems to only share the certificate file. I'll try that so.
Thank you for this amazing software !

**Comment by Ferroin** [comment]
For what it's worth, I'm actually running with a single config.xml on a multi-boot system.  The trick is to use ~ as the start of the paths and put a link in your user directory/home directory pointing at the shared storage.

**Comment by Elyjax** [comment]
The ~ trick doesn't seem to work with my Windows... Anyway I achieved it with a index-db symlink, copy/paste the certificate and 2 different config.xml. One last thought : maybe it could be useful to add a command argument to choose the config.xml file ? Then you can specify -config=/.../linux-config.xml in linux and -config=D:\...\windows-config.xml in Windows. Thus you can share the same syncthing folder (cert, db) and only manage two config files.

**Comment by AudriusButkevicius** [comment]
you have -home which is the directory that config.xml lives in.

**Comment by Elyjax** [comment]
Yes I know that but if you share a single syncthing folder with -home, you can't separate the windows/linux config.xml file. The purpose of -config would be to override the default location of the config.xml.

**Comment by AudriusButkevicius** [comment]
No, you can symlink the certificate, the index, etc.

**Comment by Elyjax** [comment]
Yes sure, it's what I do currently. I'm only saying that it would be simpler for those with dual boot config to use -home=... to locate the syncthing shared folder and -config=... to specify the OS config.xml file. At the end of the day it's not very important (nor difficult to implement) so it's up to you to decide if it would be more elegant/convenient to add this argument or not.

**Comment by AudriusButkevicius** [comment]
What you are doing is is out of the ordinary, and adding an argument to make life easy for the few, and confusing for the rest is not something we will do.
