### ISSUE TITLE
Doesn't start after wake up (via NSSM)

### ISSUE THREAD

**Issue by redmanmale** [syncthing/syncthing#3494]
I'm using Syncthing on Windows and I like it always running as a background service. For this purpose I use [NSSM](http://nssm.cc/) (it mentioned in Syncthing [docs](https://docs.syncthing.net/users/autostart.html#run-as-a-service-independent-of-user-login)). Also I use NSSM for several other applications. And this bunch works just fine: it starts after reboot every time without any flaw.

The problem is that it does not start after **wake up** (resume). All other applications start just fine with NSSM, but not Syncthing. Once I put laptop to sleep and wake it up again - Syncthing service doesn't start. The service is set to automatic start mode and runs under my user (not Local System) and if I manually start it - it running.

I'm not sure where the problem is - with Syncthing or NSSM, but I'll really appreciate it if this would be fixed.

The same problem was with OpenVPN ([ticket](https://community.openvpn.net/openvpn/ticket/71)) for several years and was fixed it just recently.

v. 0.14.4, Win 8.1, x64.

**Comment by AudriusButkevicius** [comment]
Check the logs.

**Comment by ProactiveServices** [comment]
Also if you could post the config for NSSM it would be helpful. I have a few Syncthing instances under your use case and they resume fine.

**Comment by redmanmale** [comment]
I tested for several days now and it seems all works fine. Sorry for bothering.
