### ISSUE TITLE
Connect ports

### ISSUE THREAD

**Issue by acmodeu** [syncthing/syncthing#3495]
I've got 2 devices connect in LAN, both have "Local discovery" option turned on and both have
`<listenAddress>default</listenAddress>` port setting in config.xml which is supposed to be tcp/22000. Why is it displayed as something else on one to the devices?
![1](https://cloud.githubusercontent.com/assets/17564574/17605292/6bc23384-6022-11e6-8c55-cf94d1096784.JPG)
![2](https://cloud.githubusercontent.com/assets/17564574/17605293/6bca96a0-6022-11e6-8776-546c8017e7f4.JPG)

**Comment by AudriusButkevicius** [comment]
Once side is listening, the other one is connecting.
Please use forum for questions.
