### ISSUE TITLE
Percentage shown parenthetically after the word 'syncing' can be a very large negative number

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [syncthing/syncthing#3496]
Please see screenshot.
![untitled](https://cloud.githubusercontent.com/assets/9998846/17606438/6998e91e-6017-11e6-91f6-2de6b8f4c7f7.png)

I apologise if this problem - which will be, in part, a symptom of a more basic problem - has been reported before.

Windows 8.1 x64
Syncthing v0.14.4, Windows (64 bit)

EDIT: perhaps the problem owes to something shown in the screenshot, namely, that two different versions of Syncthing are in play (one on one device, the other on another).

**Comment by calmh** [comment]
I think this may be #3492

**Comment by calmh** [comment]
It's not, it's another thing.
