### ISSUE TITLE
Fatal runtime panic

### ISSUE THREAD

**Issue by jasonwryan** [syncthing/syncthing#3497]
Since moving to the 0.14.x series of releases, I have experienced periodic crashing on one box, a laptop. It has become markedly more pronounced with 14.4

Syncthing starts, syncs with the other nodes and runs happily enough for ~30 mins to an hour and then crashes hard. Crash log is attached.

[crash.txt](https://github.com/syncthing/syncthing/files/414543/crash.txt)

None of the other nodes exhibit this behaviour. All, bar one, of the nodes are x86_64 using the same binary, the other one is an armv6h build.

### Version Information

Syncthing Version: v0.14.4
OS Version: Arch Linux

**Comment by calmh** [comment]
Looks like a sigsegv during GC... are you running out of memory?

**Comment by jasonwryan** [comment]
I wouldn't think so; the machine has 4GB and I don't run anything heavier than dwm, tmux and mutt. I'm currently using .5GB all up.

**Comment by jasonwryan** [comment]
Just died again. `free` reports only using 540.

Error message in the log:

```
Aug 12 18:06:08 Shiv syncthing[545]:         /usr/local/go/src/net/textproto/reader.go:36 +0x40
Aug 12 18:06:08 Shiv syncthing[545]: net/http.readRequest(0xc8201cce40, 0xecf3f5e00, 0xc8201b09a0, 0x0, 0x0)
Aug 12 18:06:08 Shiv syncthing[545]:         /usr/local/go/src/net/http/request.go:721 +0xb6
Aug 12 18:06:08 Shiv syncthing[545]: net/http.(*conn).readRequest(0xc8218a8500, 0x0, 0x0, 0x0)
Aug 12 18:06:08 Shiv syncthing[545]:         /usr/local/go/src/net/http/server.go:705 +0x359
Aug 12 18:06:08 Shiv syncthing[545]: net/http.(*conn).serve(0xc8218a8500)
Aug 12 18:06:08 Shiv syncthing[545]:         /usr/local/go/src/net/http/server.go:1425 +0x947
Aug 12 18:06:08 Shiv syncthing[545]: created by net/http.(*Server).Serve
Aug 12 18:06:08 Shiv syncthing[545]:         /usr/local/go/src/net/http/server.go:2137 +0x44e
Aug 12 18:06:08 Shiv syncthing[545]: goroutine 8060 [IO wait]:
```

**Comment by calmh** [comment]
Then I'm not sure. Hardware error?

**Comment by jasonwryan** [comment]
I'm not sure either. Nothing else is misbehaving (at this point)...

Thanks for looking at it. I'll update if I find anything else.

**Comment by calmh** [comment]
To be reopened if the issue becomes easier to narrow down
