### ISSUE TITLE
Folder created in Android fail to sync

### ISSUE THREAD

**Issue by ebillen** [syncthing/syncthing#3498]
Folder created in Android sometimes fail to sync to windows platforms.
I found that this is due to a trailing blank in the folder name (which happens sometimes, if you use swift key as keyboard input).

Steps to recreate:
Use a file manager (OI File Manager for example) on Android to create a new directory inside a syncthing folder. Use swift key autocompletion to enter the folder name. Depending on your input method, a blank will be added at the end of the folder name.
Result:
This folder fails to sync to syncthing running on windows. Removing the blank at the end of the directory name resolves the issue.

### Version Information

Syncthing Version: v0.14.4
OS Version: Windows 7 + Android 6
Browser Version: (if applicable, for GUI issues)

**Comment by AudriusButkevicius** [comment]
Windows does not support folders with blank spaces at the end, so don't create them.
