### ISSUE TITLE
Out of Sync ".o" Files - Won't Sync Anymore.

### ISSUE THREAD

**Issue by davidpgil** [syncthing/syncthing#3501]
I had downloaded and extracted a folder that had files named "common.o, wipe.o, fwip.o". This folder is one of my sync folders.

The syncthing http://127.0.0.1:8384/ page now shows that folder as "Out of Sync" and even if I remove the files, the sync process no longer seems to sync anything else.

### Version Information

Syncthing Version: v14.4
OS Version: Ubuntu 14.04
Browser Version: Abrowser

**Comment by AudriusButkevicius** [comment]
Please use the forum for support.
