### ISSUE TITLE
Simplify configuration: folder based sync

### ISSUE THREAD

**Issue by brenthuisman** [syncthing/syncthing#3512]
At the risk of repeating an old point and bikeshedding about the obvious competitor, I'd like to discuss the point anyway because I could not find a serious discussion, open or closed, here in the issue tracker and I would like to establish, even though I suppose the change won't happen, if there is any interest or not in the community. The feature I'd like to see is the possibility of changing or extending the way Syncthing is configured. I'd like the option to add shares on a folder-by-folder basis, without the need to configure device connections.

Although I've been a happy user, currently I synchronize files with BTSync. For me, the tool serves two purposes: keeping my own devices in sync, for which Syncthing is an excellent choice, and sharing files with others, for which switched back to BTSync. The issue is basically that Syncthing is a) complex to setup for many laymen and b) a tad laborious, because both nodes need to shake hands, which means adding a device can't be done from one machine in a single action, both nodes must be online and after adding the codes and the handshake, both must add the other on their whitelist, which is the second action.

Let me go into point b) first. I live in another country than my family, and we use the tool to share stuff such as photos and document scans. With my girlfriend we share some music, photos, documents, and so on. She in turn uses it to share scientific data with collaborators, who are spread all over Europe or even in other timezones. In practice, setting up Syncthing, one end will send their code, the next day the other adds it and sends theirs and then perhaps in another day all is setup. This in contrast to everyone adding their folder-key whenever they want and then having it sync when another node is online as in BTSync. 

A) is a consequence of b), but not only. Consider first of all that the number of actions of setting up Syncthing is simply larger than BTSync. Even Dropbox, another tool I see people use here in my lab, has fewer steps when sharing a folder. On to Syncthing. Currently, it's easy to accidentally share all your shares to a new machine for instance, which is not good UX. This is probably a consequence of most people using it using it for their own devices and their own devices only, where it makes sense to share multiple folder. When sharing with other, it almost never does. On top of that, I use many one-of folder shares with friends, just to transfer a few particular files. Easy in BTSync, other tools, not Syncthing.

Because of both a) and b), I need to arrange a sitdown with $other_person_far_away, which may take a few days/weeks due to agenda incompatibilities and takes more steps that are not nearly as easily explained as BTSync 1-folder-1-key metaphor.

Concluding: when it comes to sharing, Syncthing has a prohibitively complex setup which rules out it's use by a) laymen and b) to those that share files with laymen. I've had great success using sync tools that are configured with 1-folder-1-key metaphors, apparently that is much more natural to many than the device handshake and then select which folders you wan to share that Syncthing is based on. I greatly would prefer to use Syncthing over other tools, because it is open source, has verifiable security features and a great community.

Now, I know that many are quite satisfied with the way Syncthing is configured right now, so perhaps folder sharing is simply a mode that could be adding. We could generate a device-key-like-key but not actually tied to a device but is coupled to a single folder, and we then we must be able to add multiple of such keys. Perhaps we could call the extra mode 'Shared Folders' or somesuch, as that seems to be the unsolved case.

I'd love to hear what your opinions are. I hope there is interest in making Syncthing the obvious tool for sharing, in addition to syncing.

**Comment by AudriusButkevicius** [comment]
Please use the forum for discussions.

**Comment by brenthuisman** [comment]
It is a feature request.

**Comment by calmh** [comment]
At the very least it needs discussion before ending up in an actionable feature request.

**Comment by brenthuisman** [comment]
I believe the forums have had discussions off and on related to this topic, but I've not seen it been followed-up or discussed by the project members. Various features have been requested and even accepted related to the issue of sharing, such as friendly share names.

I was probably way to wordy: the feature I'd like to see, and some others in the forum as well, is the ability to reduce ux complexity of sharing. Concretely, I think this can be achieved by implementing it as a separate concept from syncing, and taking the 1-folder-1-key approach.

**Comment by AudriusButkevicius** [comment]
Still, a fact that you'd like it does not mean that others would, hence I suggest starting a discussion on the forums to get a consensus.

Furthermore, if it's a separate concept, I am not sure why the issue should be even filed under syncthing.

**Comment by brenthuisman** [comment]
I figured calling it a separate concept would add to clarity, but I never wanted to imply I see sharing and syncing as very different. It's just the ux around it that is now very much geared toward one of the two, while Syncthing in principle is more than capable of both. Can you agree with that?

If you search https://forum.syncthing.net/ for public sharing, sharing of btsync you'll see quite a few posts related to easing up setting up shares. I think that constitutes discussion. Furthermore, there's plenty of PRs open right now that are basically discussions, and since I have a concrete feature, share-folder-by-key, I figured this is the correct place.

**Comment by AudriusButkevicius** [comment]
I believe there already exists a ticket "make sharing easier" or whatever, which probably satisfies the UX part, yet I am fairly certain share folder by it's key will never happen, as most of security of syncthing revolves around the trust of the device, and I don't see us trusting all the devices on the internet that know some 32 character code any time soon.

**Comment by brenthuisman** [comment]
If it's the same (type of) key that Syncthing has now, it would be equally secure or insecure, wouldn't it?

**Comment by AudriusButkevicius** [comment]
No it's not, as there is a "key" (which potentially consists of device id and folder id) from each side, so the relationship is mutual. What BTSync does is not mutual, once it's leaked, there is no way back.

**Comment by brenthuisman** [comment]
I see your point, I hadn't considered that. However, it could be implemented alongside the current mechanism, leaving user who're happy as Syncthing is alone. It's then up to the user to be aware of the security implications. Alternatively, a more Syncthingy way of sharing is a 'device-folder'-id, which would function identically as it does now, with the difference that you can have multiple, each corresponds to exactly a single folder. It would fit the mental model, but ensure the safety issues you mention. Not sure if this would improve matter, other than mapping to the 1-folder-1-key metaphor.

Do you use Syncthing for the purpose of sharing rather than syncing? I hope we can find a way to make it easier to use for this use case.

**Comment by calmh** [comment]
I'm all for improving the user experience of tying together devices. I haven't yet seen a concrete working proposal to do that in a way that doesn't completely undermine the security, and in particular I don't like the "share secret key that can escape into the walk" mechanism.

I've seen proposals that could work, given some technical fleshing-out: both sides entering a simple, secret word chosen on the spot (`banana`) and pressing enter within the same 60 second window, for example. That requires secure communication between the two parties (such as a phone call), but not exchanging cryptic numbers.

I'm sure there are other ways.

But that's why I think this is a wider discussion. :)

**Comment by AudriusButkevicius** [comment]
I had in mind one off codes which are protected by a second factor, which essentially auto-add the device and auto-share the given folder.

Something like:

1. You click "Share" button on a folder
2. Select if it's a one off share code, N time share  code or a permanent share  code (debatable)
3.  Default expiry time for the share code is 2 hours (you can increase that to let's say 72 hours)
4. You enter a pin code for the share code
5. You email the share  code to the user
6.  You send a SMS with the pin code
7. The person on the other end enters the share code and the pin code
8. The syncthing at the other end connects to you by looking up who advertised the share code, and in the hello message presents the code and proves that it has the pin code, we auto-add the device and auto share the folder

share code being totally random not attached to any share of course.

Anyways, but this belongs in the forum regardless, so I am locking this.
If any discussions to be had, they should be on the forum.

**Comment by AudriusButkevicius** [comment]
If any discussions to be had, let's have them on the forum where it's accessible to the wider public.
