### ISSUE TITLE
Tests fail on Windows with Go 1.7

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3513]
```
--- FAIL: TestInWritableDirWindowsRemove (0.00s)
	osutil_test.go:105: Expected error testdata/windows/ro/readonly
	osutil_test.go:105: Expected error testdata/windows/ro
	osutil_test.go:105: Expected error testdata/windows
	osutil_test.go:112: Unexpected error testdata/windows/ro/readonly: GetFileAttributesEx testdata\windows\ro: The system cannot find the path specified.
	osutil_test.go:112: Unexpected error testdata/windows/ro: GetFileAttributesEx testdata\windows: The system cannot find the file specified.
	osutil_test.go:112: Unexpected error testdata/windows: GetFileAttributesEx testdata/windows: The system cannot find the file specified.
FAIL
FAIL	github.com/syncthing/syncthing/lib/osutil	0.155s
```

Needs fixing before next release. Was regular os.Remove fixed to behave as on Unix, perhaps?

**Comment by AudriusButkevicius** [comment]
So they fail for me pretty much in every version of go, if the files happen to be created by a different user for example.


And yes, os.Remove has been made to remove readonly files in go 1.7

**Comment by calmh** [comment]
Well it's the first time this fails on the build server. But that looks like the cause then as the first three lines are unexpected success returns from os.Remove and the next three are unexpected failures because the files have already been remove.

Annoyingly, I think we need to support Go 1.5+ for a while so we should move osutil.Remove to a file with a build constraint for that and have modern compilers just see it as `osutil.Remove = os.Remove`.

**Comment by AudriusButkevicius** [comment]
I don't think there are any builds that are not 1.7 that are not ours.
