### ISSUE TITLE
Syncthing upgrade can end up with no config.xml when there is not enough space on device

### ISSUE THREAD

**Issue by kozec** [syncthing/syncthing#3525]
Hello there,

I somehow managed to completely fill up my /home drive on one server. I noticed it too late and as result, syncthing failed to write to `config.xml` somewhere in the process and truncated it to 0b.
Config was then replaced with default one upon next start.

Luckily, following is not my case, but this could be rather unpleasant for someone without backups.

Usual way how to _not_ end up with invalid config is to write `config.xml.tml` and mv it only after successful write.

### Version Information

Syncthing Version: syncthing v0.14.4 "Dysprosium Dragonfly" (go1.6.3 linux-amd64) builduser@svetlemodry 2016-08-10 19:32:43 UTC
OS Version: Manjaro Linux, fully updated as on Fri Aug 19 07:38:46 CEST 2016
(It's headless machine, so I'm not using any browser nor Syncthing-GTK there)

**Comment by calmh** [comment]
> Usual way how to not end up with invalid config is to write config.xml.tml and mv it only after successful write.

We do exactly this...

**Comment by kozec** [comment]
> We do exactly this...

And is there any chance that 0b .tmp file is created and then moved over config.xml?

I'll try to reproduce problem just to be sure I didn't assumed something incorrectly in my description.

**Comment by kozec** [comment]
... ok, sorry, there is one more condition that needs to be thrown in: Syncthing upgrade.

How to reproduce:
```
# create 100MB image with filesystem and mount it
dd if=/dev/zero of=file.out bs=1MB count=100
mkfs.ext3 file.out
sudo mount file.out /mnt/a -o loop
# (get permissions)
sudo chown -R user:user /mnt/a
# start syncthing and configure anything
HOME=/mnt/a syncthing
# now fill-up a 'drive'
dd if=/dev/zero of=/mnt/a/fillme
# Upgrade syncthing and restart it
^C
apt-or-something install syncthing
# start syncthing again
HOME=/mnt/a syncthing
```

Now syncthing will respond with

> [76AYV] 09:12:13 FATAL: Cannot open database: write /mnt/a/.config/syncthing/index-v0.14.0.db/000010.ldb: no space left on device - Is another copy of Syncthing already running?

... and there is either 0b long or no config.xml at all in `.config/syncthing`. Original got renamed to `config.xml.v15`, so there is no data loss, but it will still create default/empty config next time syncthing is started.

**Comment by calmh** [comment]
I can reproduce that to get no config.xml at all:

```
jb@syno:~/s/g/s/syncthing $ df /Volumes/Untitled/
Filesystem     Size   Used  Avail Capacity iused ifree %iused  Mounted on
/dev/disk4s1   95Mi   95Mi    0Bi   100%   24408     0  100%   /Volumes/Untitled
jb@syno:~/s/g/s/syncthing $ syncthing -home /Volumes/Untitled
[monitor] 09:23:13 INFO: Starting syncthing
[XE7ET] 09:23:13 INFO: syncthing v0.14.4+10-g04dad84 "Dysprosium Dragonfly" (go1.7rc6 darwin-amd64) jb@syno.nym.se 2016-08-18 17:38:15 UTC
[XE7ET] 09:23:13 INFO: My ID: XE7ET75-XUA3TYO-VQGD5V2-FE2KBS3-2MWLBUP-NLVHHYM-I5HCCWV-EM3A6QW
[XE7ET] 09:23:13 INFO: Single thread hash performance is ~379 MB/s
[XE7ET] 09:23:13 INFO: Archiving a copy of old config file format at: /Volumes/Untitled/config.xml.v15
[XE7ET] 09:23:13 FATAL: Config archive: open /Volumes/Untitled/.syncthing.tmp.838411590: no space left on device
[monitor] 09:23:13 INFO: Syncthing exited: exit status 1
...
jb@syno:~/s/g/s/syncthing $ ls -l /Volumes/Untitled
total 189624
-rw-r--r--  1 jb  staff       615 Aug 19 09:20 cert.pem
-rw-------  1 jb  staff      2942 Aug 19 09:23 config.xml.v15
-rw-------  1 jb  staff        99 Aug 19 09:22 csrftokens.txt
-rw-r--r--  1 jb  staff  97062912 Aug 19 09:23 foo
-rw-r--r--  1 jb  staff      1074 Aug 19 09:21 https-cert.pem
-rw-------  1 jb  staff      1679 Aug 19 09:21 https-key.pem
drwxr-xr-x  8 jb  staff       272 Aug 19 09:22 index-v0.14.0.db/
-rw-------  1 jb  staff       288 Aug 19 09:20 key.pem
jb@syno:~/s/g/s/syncthing $ 
```

I cannot get it to create an empty config.xml though.

The above case I think is corner case enough that I'm not super worried about it to be honest...

**Comment by calmh** [comment]
Or, we could make the archiving step a *copy* operation instead, which would fail earlier and this should be safe.

**Comment by kozec** [comment]
> The above case I think is corner case enough that I'm not super worried about it to be honest...

Yeah, I agree, after realizing there is no data loss involved.

> Or, we could make the archiving step a copy operation instead, which would fail earlier and this should be safe.

If copy occurs only if there is no `config.xml.v15` already there, that sounds like perfect solution.
