### ISSUE TITLE
Win32 0.14.4, paste + rename a file results to file deletion after X secs

### ISSUE THREAD

**Issue by galileolajara** [syncthing/syncthing#3526]
Happens multiple times, to reproduce:
- paste a file (preferrably around 2MB) to any synced syncthing folder then rename it quickly
- after X secs, the renamed file will be deleted

Thanks in advance

**Comment by calmh** [comment]
More setup details please. Versions, Synctrayzor plain installation, other devices involved?

**Comment by canton7** [comment]
What is 'X'?

**Comment by galileolajara** [comment]
Synctrayzor 1.1.11
Syncthing 0.14.4

not sure about other devices though, but I'm certain that I can reproduce it too often

**Comment by calmh** [comment]
I suspect inotify interaction shenanigans in combinations with updates on some other device, but 😕

**Comment by galileolajara** [comment]
I actually, by chance, saw a scenario where after renaming A to B, after a few seconds, A file reappears, making both A and B co-exists.

Maybe it's because of inotify of Synctrayzor (we use 0 in Rescan Interval), however, we never experienced missing files when we're in 0.13

Thanks for listening

**Comment by calmh** [comment]
I still want to know what your other devices are (OS, mostly).

**Comment by canton7** [comment]
Might be worth disabling inotify in SyncTrayzor and seeing if you can still repro.

**Comment by nrm21** [comment]
I just tried v0.14.5 on Win10 (sync to => v0.14.3 on Android).  Paste 2MB file, then quick rename file and... nothing, it just sat there.

It did manage to sync tho.  :)

**Comment by seansimonanimation** [comment]
A while ago, I did  have an issue where Syncthing deleted a file from the share when a particular share existed in two different directories on the same workstation. Like if I had a share in c:\share\, and that share also pulled from data in a share in h:\root\share\, the shares would disagree and delete the file from the share I put it in.

For instance, say I put file.jpg in c:\share
Syncthing would check it against h:\root\share\file.jpg and see that the file isn't supposed to exist.
Then Syncthing would delete c:\share\file.jpg without even sending it to the recycle bin, rendering the file more or less unrecoverable (even attempts with 3rd party undelete software failed), and the file.jpg didn't even make it into c:\share\.stversions\file.jpg It was simply gone.

I fixed the issue (I think) by removing one of the shares, So issue fixed, but at the same time, it would be nice to be able to use Syncthing to do automatic redundancies within a single workstation, like a live backup to an external HDD.

**Comment by nrm21** [comment]
Maybe some app was constantly touching the file in H: drive, causing it to always have a newer last mod time?  Or maybe H: was configured to be master?

Also what versioning were you using?  On windows ST cannot send to recycle bin (that's why I use external versioning to a batch file that calls an exe that does it for me instead).  Because I don't personally like the .stversions folder.

You should be able to sync things from one dir to another on the same computer with ST.  But ONLY if you run 2 instances of syncthing on 2 different ports (NOT how it was originally intended, but still works fine IIRC).  You can't, of course, do that running only instance one per PC.

**Comment by calmh** [comment]
> Syncthing deleted a file from the share when a particular share existed in two different directories on the same workstation

If you had NTFS deduplication enabled, that could explain it. When it does deduplication the file ceases to be a normal file from our point of view, instead becoming a very funky type of symlink that we don't support.

**Comment by calmh** [comment]
Not enough info / not reproducible
