### ISSUE TITLE
Relax Syncthing interface timeout

### ISSUE THREAD

**Issue by vocatus** [syncthing/syncthing#3528]
I am in Antarctica and administer a Syncthing server across a satellite link. There is sufficient bandwidth (3 Mb/s), but due to the satellite connection the latency is very high (500-750ms constant). 

The Syncthing web interface consistently times out with this error message:

> Syncthing seems to be experiencing a problem processing your request. Please refresh the page or restart Syncthing if the problem persists.

Is it possible to include a "high latency connection" option, or have Syncthing automatically detect a high latency connection and relax the GUI timeout counters accordingly? 

Thank-you!

![blackmill syncthing - timeout](https://cloud.githubusercontent.com/assets/5703764/17838088/caf0a064-679a-11e6-8a1c-37e6f7979124.png)
![blackmill syncthing](https://cloud.githubusercontent.com/assets/5703764/17838087/cae56c30-679a-11e6-8b47-2f5672885ea4.png)
### Version Information

Syncthing Version: v0.14.4
OS Version: Linux Mint 17.3 Rosa 64-bit (server); Windows 7, 10 and Linux Mint 17.3 (client accessing the web GUI)
Browser Version: Multiple browsers. Primarily Palemoon 26.3.3 and Firefox 41+. Have also replicated the issue with whatever the latest Chrome was a week or so ago.

**Comment by AudriusButkevicius** [comment]
Feel free to make a pull request.

**Comment by vocatus** [comment]
Thanks @AudriusButkevicius. Being a common peasant (read: non-programmer) I don't have the skill to do the code myself or I'd do a PR. Is this the right channel to ask about this?

**Comment by AudriusButkevicius** [comment]
It needs a new line here:
https://github.com/syncthing/syncthing/blob/89a29946f96c63795ca5d3da062316c375604961/gui/default/syncthing/app.js#L23

```
$httpProvider.defaults.timeout = 5000;
```

potentially. I am not sure what the default is, yet try to build it yourself and verify that that fixes the issue.

**Comment by calmh** [comment]
I see no issue with us bumping that up to a higher value, say 15 seconds, in the standard build.

**Comment by vocatus** [comment]
Thanks @calmh, really appreciate it!

**Comment by calmh** [comment]
On closer inspection, we do not appear to set an explicit timeout and the default should be "no timeout" - this seems reasonable given that the event system does calls block for up to 60 seconds. However, those do send out a response header first...

@vocatus Is it possible for you to open the debug/javascript console in your browser and capture the output when this problem appears? I'm hoping that would give some more info about what causes the error.

**Comment by vocatus** [comment]
@calmh, sure thing, can do. What output would be helpful?

**Comment by vocatus** [comment]
@calmh OK I ran the debugger and captured a screenshot when the interface timed out. I couldn't figure out a way to save the raw log file; I'll keep poking around. [Screenshot here](http://imgur.com/a/oDpOy)

**Comment by calmh** [comment]
I don't know that browser and some of the http gets don't show any status, but there's nothing in there that looks like an error. :/

**Comment by uok** [comment]
[Pale Moon](https://en.wikipedia.org/wiki/Pale_Moon_(web_browser)) is a fork of Firefox
@vocatus: These could be normal HTTP timeouts, maybe try changing these settings in the browser itself?

**Comment by vocatus** [comment]
@calmh @uok  I did test with multiple browsers and experienced the same issue across all of them. Interestingly enough though I haven't been able to replicate the issue since updating v0.14.5, even though the changelog doesn't say anything about HTTP timeouts.

**Comment by cfinnberg** [comment]
I suffer from the same problem, although in my case is just a simple VPN connection (not as cool as being in Antartica 😄 ).  I have made a screenshot of the errors.
<img width="1363" alt="nayttokuva 2016-08-27 kello 8 32 59" src="https://cloud.githubusercontent.com/assets/2817326/18025435/cc72e014-6c31-11e6-8835-9f0614750446.png">

It seems that some of the REST petitions get timeouted, even if after that there are more petitions that work as expected. The error window appears with the first timeout. Is it possible to change this behaviour? A connection can be unreliable but can work as a whole. Maybe some updates are lost but only some. I can use remote desktop, copy files (even big ones), ssh linux boxes over the same connection and I don't notice any other problem (than the one on syncthing web).

Instead of firing the error status with the first lost petition, syncthing could be more "flexible" and wait to see if consistently the update petitions are lost (or at least a big part of them). Not sure anyway how this behaviour should be. Not being a Go programmer myself, I'm not confident enough to make a PR over this issue.

**Comment by vocatus** [comment]
Thanks @cfinnberg, good to hear someone else is experiencing it. Oddly enough the issue came back on my end, and has been timing out again pretty regularly, even with low network traffic. I'm the station network engineer and so am able to monitor the traffic pretty closely, and it seems to happen regardless of congestion on the link.

**Comment by calmh** [comment]
There's definitely something interesting going on in your trace @cfinnberg - even the successfull requests that take almost exactly 20s to complete are suspicious. Is there any possibility you could run syncthing with `STTRACE=http` during the same time period and see what it logs - if it sees the requests, and sees the same latency or not?

**Comment by cfinnberg** [comment]
Ok. Here are a few screenshots of the browser and the logs from Syncthing. What It seems to me is that requests didn't make it to the Syncthing web server.
[Issue_3528.zip](https://github.com/syncthing/syncthing/files/448164/Issue_3528.zip)

Thanks for your time.

**Comment by iperi** [comment]
Hi, I was just reading this thread and decided to post my thoughts. I don't know the @cfinnberg's VPN server configuration, but are you using tcp protocol? If yes then maybe connection gets into some infinite retransmission loop. For more info see: [http://sites.inka.de/sites/bigred/devel/tcp-tcp.html](url). 

I hope it's not off-topic.

**Comment by calmh** [comment]
Much as I'd like to have solved this, it seems to be a one off case without an obvious cause and possible out of our control (browser timeouts).
