### ISSUE TITLE
lib/model: Temp index sorting databases remain on disk

### ISSUE THREAD

**Issue by arneko** [syncthing/syncthing#3529]
I just noticed my backup program (attic/borg backup) backing up a number of syncthing folders, which are called tmp-index-sorter.##### and live in the config directory. I understand these are db files enabling the delta-indexing algorithm. In the past I would ignore folders by placing a "cachedir.tag" file into folders I don't want backed up.
In this case I was puzzled by their naming scheme though- they are called "tmp*" -something , but don't seem to be more temporal than the actual database-folder. My initial thought was thus not to place the cachedir.tag -files there, since "tmp"-folders tend to get cleaned up at times (?!)
Also, there are quite a number of "tmp-index-sorter"-folders, and it looks untidy. O:-) At least much less tidy than I am used to from syncthing.
Wouldn't it make more sense to at least put all the index-related db-folders into an extra subfolder say $st_home/index/ ?

So I guess I am proposing both a naming-scheme change and a location change...
EDIT: Just saw this related https://github.com/syncthing/syncthing/issues/3449 closed issue, so I guess you guys are somewhat aware of the issue

**Comment by wweich** [comment]
These folders were initially placed in the system temp folder (e.g. `/tmp/` on most Linux systems). But as they can grow large and small systems like NASs mount /tmp as tmpfs (ram disk), they were relocated to the Syncthing config dir.

AFAIK they are used, if the sorter needs more space than fits in RAM and should be removed when done.

--

Just saw your edit, so you already know whats in the last two paragraphs ;)
The Ticket you refer to was the reason those folders were placed inside the Syncthing config.
Those folders are only temporary, but seem to be not cleaned up immediately. If you restart Syncthing, they should be removed (and replaced with new once, as soon as index sorter needs more space),

**Comment by calmh** [comment]
They should be removed automatically as soon as they are done with. Maybe there is a bug in the cleanup...

**Comment by arneko** [comment]
I see. I got folders older than a week and there are about 10 of them - so yes, there's something wrong. 
I might have had syncthing crashing because of full disks at the time, so that might be related. Though the creation dates stretch over 3 days, and that souds too long to live with a full root partition...

**Comment by wweich** [comment]
In #3449 AudriusButkevicius suggested to cleanup / remove all tmp index dirs on startup, which seems to not have been implemented, if the dirs are older than your last Syncthing restart (after the crash).

**Comment by arneko** [comment]
...I know this discussion is old (for the indexes), but why don't we place these files into .cache? Just because that's considered a desktoppy thing can't be a reason, since .config is just as much used for desktop programs only (at least on my machines/my installed software)

**Comment by AudriusButkevicius** [comment]
Because it's not a cache, these are persistent and need to stay. Temp indexes for sorting are probably caches, yet we'll not get involved in the game of every OS and distro using a different path for caches.

**Comment by calmh** [comment]
It's entirely possible that they get left behind if there is a crash. I'll add code to clean them out on startup.
