### ISSUE TITLE
Add Email notifications with secure email config

### ISSUE THREAD

**Issue by Co0olCat** [syncthing/syncthing#3531]
Hi,

Great product.

We are thinking to use it in production for web files synchronization.

It would be great to have email reporting functionality: Daily, Weekly, instant on error. 
Secure email would be great.

Thank you.

Kind regards,
TY

**Comment by AudriusButkevicius** [comment]
Use tye APIs/log scraping to produce whatever reports you are after. Sending emaila is out of scope.

**Comment by canton7** [comment]
> We are thinking to use it in production for web files synchronization.

This is probably a bad idea.

When you deploy files to production, that operation should be atomic. Everything should be updated together, in one go, not file-by-file. There should be no scope for the operation to partially complete or partially fail.

Syncthing is not a good fit for this. It does not report sync errors except on that one device, it does not notify you when synchronization has finished, etc. Look into using a proper deployment tool: there are plenty of them around.
