### ISSUE TITLE
Config tests fail with recent d4l3k/messagediff version

### ISSUE THREAD

**Issue by aviau** [syncthing/syncthing#3533]
Hello!

It seems like tests are failing on armel and armhf:

 - https://buildd.debian.org/status/fetch.php?pkg=syncthing&arch=armhf&ver=0.14.4%2Bdfsg1-1&stamp=1471367979
 - https://buildd.debian.org/status/fetch.php?pkg=syncthing&arch=armel&ver=0.14.4%2Bdfsg1-1&stamp=1471367078

**Comment by calmh** [comment]
Works for me, and those tests don't look particularly architecture specific. I think your build setup is broken. Yell if you can reproduce this with our source, unmodified.

```
jb@pi2:~/src/github.com/syncthing/syncthing$ go run build.go test
ok  	github.com/syncthing/syncthing/lib/auto	0.238s
ok  	github.com/syncthing/syncthing/lib/beacon	0.041s
ok  	github.com/syncthing/syncthing/lib/config	0.300s
ok  	github.com/syncthing/syncthing/lib/connections	0.058s
ok  	github.com/syncthing/syncthing/lib/db	0.336s
ok  	github.com/syncthing/syncthing/lib/dialer	0.036s
ok  	github.com/syncthing/syncthing/lib/discover	3.159s
ok  	github.com/syncthing/syncthing/lib/events	0.919s
ok  	github.com/syncthing/syncthing/lib/fs	0.041s
ok  	github.com/syncthing/syncthing/lib/ignore	1.597s
ok  	github.com/syncthing/syncthing/lib/logger	0.046s
ok  	github.com/syncthing/syncthing/lib/model	14.606s
ok  	github.com/syncthing/syncthing/lib/nat	0.069s
ok  	github.com/syncthing/syncthing/lib/osutil	0.071s
ok  	github.com/syncthing/syncthing/lib/pmp	0.089s
ok  	github.com/syncthing/syncthing/lib/protocol	0.424s
ok  	github.com/syncthing/syncthing/lib/rand	3.776s
?   	github.com/syncthing/syncthing/lib/rc	[no test files]
ok  	github.com/syncthing/syncthing/lib/relay/client	0.135s
ok  	github.com/syncthing/syncthing/lib/relay/protocol	0.052s
ok  	github.com/syncthing/syncthing/lib/scanner	0.155s
ok  	github.com/syncthing/syncthing/lib/signature	2.803s
ok  	github.com/syncthing/syncthing/lib/stats	0.058s
ok  	github.com/syncthing/syncthing/lib/symlinks	0.037s
ok  	github.com/syncthing/syncthing/lib/sync	0.680s
ok  	github.com/syncthing/syncthing/lib/tlsutil	0.024s
ok  	github.com/syncthing/syncthing/lib/upgrade	0.062s
ok  	github.com/syncthing/syncthing/lib/upnp	0.098s
ok  	github.com/syncthing/syncthing/lib/util	0.041s
ok  	github.com/syncthing/syncthing/lib/versioner	0.097s
?   	github.com/syncthing/syncthing/cmd/stbench	[no test files]
?   	github.com/syncthing/syncthing/cmd/stcompdirs	[no test files]
?   	github.com/syncthing/syncthing/cmd/stdisco	[no test files]
?   	github.com/syncthing/syncthing/cmd/stdiscosrv	[no test files]
?   	github.com/syncthing/syncthing/cmd/stevents	[no test files]
?   	github.com/syncthing/syncthing/cmd/stfileinfo	[no test files]
?   	github.com/syncthing/syncthing/cmd/stfinddevice	[no test files]
?   	github.com/syncthing/syncthing/cmd/stgenfiles	[no test files]
?   	github.com/syncthing/syncthing/cmd/stindex	[no test files]
?   	github.com/syncthing/syncthing/cmd/strelaypoolsrv	[no test files]
?   	github.com/syncthing/syncthing/cmd/strelaypoolsrv/auto	[no test files]
?   	github.com/syncthing/syncthing/cmd/strelaysrv	[no test files]
?   	github.com/syncthing/syncthing/cmd/strelaysrv/testutil	[no test files]
?   	github.com/syncthing/syncthing/cmd/stsigtool	[no test files]
?   	github.com/syncthing/syncthing/cmd/stvanity	[no test files]
?   	github.com/syncthing/syncthing/cmd/stwatchfile	[no test files]
ok  	github.com/syncthing/syncthing/cmd/syncthing	9.377s
jb@pi2:~/src/github.com/syncthing/syncthing$ go version
go version go1.7 linux/arm
jb@pi2:~/src/github.com/syncthing/syncthing$ uname -a
Linux pi2.nym.se 4.1.18-v7+ #845 SMP Thu Feb 18 19:45:28 GMT 2016 armv7l armv7l armv7l GNU/Linux
jb@pi2:~/src/github.com/syncthing/syncthing$ git describe
v0.14.4-11-g00a6548
```

**Comment by aviau** [comment]
Looking into it, I found out that the tests are failing with a recent d4l3k/messagediff.

This can be reproduced by updating the vendored d4l3k/messagediff version.

**Comment by AudriusButkevicius** [comment]
Well then don't update it?

**Comment by aviau** [comment]
The vendor directory of Syncthing is excluded from the tarball we use in Debian. Instead, we build Syncthing with libraries that are packaged separately.

For obvious reasons, I won't downgrade the version of messagediff that we have in Debian.

**Comment by calmh** [comment]
Still though, this is the reason we vendor. If you don't, we recommend the versions of the dependencies specified in the manifest file. Yes, depending on a specific commit is a bit crap, but this is the current state of the Go ecosystem. Of course, a pull request to update a vendored dependency to a newer version is fine.

**Comment by AudriusButkevicius** [comment]
Sounds like a Henny Youngman problem.

**Comment by calmh** [comment]
I'm going to close this again for the simple reason that we cannot be compatible with every future version of our dependencies. This is illustrated by the fact that one of our dependencies has apparently changed in an incompatible manner. In the Go ecosystem this is handled by revision pinning and versioning, although this is a situation many are unhappy with and currently under fervent discussion...

A failure to build with some other version of a dependency than the ones we recommend is not a bug on our side, it's a build issue that needs resolving on the builder's side.

**Comment by canton7** [comment]
> Distributions don't allow programs to ship their own version of every library they use. That would be a nightmare to manage.

Note that dependencies in Go are compiled in. It's not like Syncthing requires version x of a library to be installed on the end user's machine, where it might conflict with version y. 

So Syncthing doesn't "ship" with its own versions of its dependencies, in the usual sense of the word. It doesn't even require that that particular version is installed in the build machine: the vendoring takes care of that. Therefore I don't understand how it can be a "nightmare to manage". While Debian's policy is what it is, I don't think that Syncthing is breaking the spirit of the policy here: it won't cause the problems that the policy was made to prevent. Therefore I can't help but think that Debian is responsible for the consequences of their actions here.

**Comment by aviau** [comment]
> A failure to build with some other version of a dependency than the ones we recommend is not a bug on our side, it's a build issue that needs resolving on the builder's side.

Upstream should always strive to be compatible with updated libraries. So it might not be a "bug", but definitely something that should be on your roadmap.

> Note that dependencies in Go are compiled in. 

Almost all languages support that. We still choose not to allow it.

> Therefore I don't understand how it can be a "nightmare to manage".

 The fact that Syncthing is in Go and that it embeds dependencies changes nothing to the issues we are trying to avoid. If we have 25 programs that embed a different version of a library that contains security issues, it is impractical for distributions to fix it everywhere. And its not just security, its also features and other bugfixes that could be done in your vendored libs

**Comment by calmh** [comment]
Look, you're welcome to argue against vendoring and I'll even agree with you, but this is not the forum. If you want us to use a newer version of a package, file the pull request. I wager the effort would be dwarfed by the effort put into this discussion.

In the meantime, saying essentially "some other package changed their API and things break when I  use my special build process and drop in that version instead of the one you vendor - you have a bug" is not the way we do things. When you use a build process that differs significantly from the one we support and document, you get to fix the breakage when it happens. If the fix can be merged we'll gladly take the patches to simplify for everyone in the future. 

I track the development of our important dependencies and upgrade as appropriate. This package isn't one of them.
