### ISSUE TITLE
Feature Request: email on out-of-sync

### ISSUE THREAD

**Issue by thutex** [syncthing/syncthing#3536]
situation :     
I don't often check the status of my backups, and just today i noticed that due to a corrupt syncthing index (how did that happen?) my backup was out of sync on 1 host.
no clue how long it's been that way....

suggestion/request: 
I would suggest an option where you can set a "master", which, when one of it's "slaves" is out of sync for more than x time, it would send you an email stating "slave x has been out of sync for over x time".
that way we can be informed about possible problems with the backups without checking in on the gui.

**Comment by AudriusButkevicius** [comment]
No, emails are out of sync.

**Comment by thutex** [comment]
the API depends on the web ui, which i have disabled on most nodes (the less you have active, the more secure... and since there is no need for the gui once configured/when using the config file...)
i guess it is possible through the logs, but does syncthing log when a directory is out of sync?

**Comment by AudriusButkevicius** [comment]
You can make the GUi listen on the loopback address which is as secure as your machine is. Also try launching with -audit -verbose and see. I think there might be a completion event that gets printed. 

Sadly even if there is none, the stance on sending emals is not going to change.
