### ISSUE TITLE
Sync not working

### ISSUE THREAD

**Issue by thutex** [syncthing/syncthing#3537]
problems with sync between nodes since upgrade

- on 0.13.x : no problem
- upgraded to 0.14.4 : folders are no longer syncing

setup:
1 master, readonly,  2 folders, syncing to 2 nodes that are readwrite, and only syncing from the master node.
all 3 nodes are linux (debian based), all on 0.14.4

what happened: syncing stops at 43% for node 1 and 63% for node 2
additionally: node 1 was at 100% sync, but dropped to 43% when i added some more ignore patterns, so in theory node 1 only has to remove files...

after removing the index file, it rebuilds index and gives the same problem
after removing the backed up folder and the index file, it syncs partially again but still stops before finishing.

none of the nodes gives an error and all files used to be synchronized flawlessly.
### Version Information

Syncthing Version: v0.14.4
OS Version: 3 nodes on debian-based distro's

**Comment by AudriusButkevicius** [comment]
Please use the forum for support issues, just as it's explained in the issue template.

**Comment by thutex** [comment]
i will do so, i just found it strange that this issue popped up after an upgrade and so assumed it might be a bug  (no config changes were done and it's been working flawlessly since i started using syncthing at version 0.11
in any case, sorry for the useless report
