### ISSUE TITLE
re install older version

### ISSUE THREAD

**Issue by pede0** [syncthing/syncthing#3538]
Hi ,
i#m new here.

I'm not really able in coding and so may this is a stupid question bit please help me.

I heard about syncthing i love it. 
I use an other syncing server called Protonet with Protosync working with the same app=syncthing in background.

I thought great so it suites perfect to me and i installed syncthing , and it works perfect.
But now I have a problem with the version on my mac and that of the Protonet server.
Protonet use v12 and on my mac installed automatically v14.

How can I get back to v12 ?

Thanks for your help

### Version Information

Syncthing Version: v0.14.5, Mac OS X (64 bit)
v0.14.5, Mac OS X (64 bit)

Browser Version: safari 9.1.2 (11601.7.7)

**Comment by AudriusButkevicius** [comment]
Please use the forum for support, just like it's explained in the issue template.

**Comment by pede0** [comment]
sorry , 
thanks
