### ISSUE TITLE
gui: Delay refresh after saving theme.

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#3539]
I'm too lazy to write a description.

**Comment by calmh** [comment]
Mind doing it now though? I'm not sure what the issue is here.

**Comment by AudriusButkevicius** [comment]
So I am not sure what the issue is myself anymore.
I thought that config.save() causes the GUI service to restart to change the theme, and we happen to refresh at the same time essentially hitting a webserver that is down, hence wanted to delay refresh after the save for a few seconds, but not sure if how to repro this anymore.

**Comment by calmh** [comment]
Which reminds me of another issue I should file!
