### ISSUE TITLE
Incorrect sync percentage

### ISSUE THREAD

**Issue by vdmkenny** [syncthing/syncthing#3542]
While syncing today, I noticed the percentage reach 101%, then go down to 97, before finally reaching 100%. I'm not sure what triggered this or how to reproduce it, my guess it that somewhere, something gets incorrectly rounded.

[Here is a screenshot.](http://imgur.com/a/UfFm3)

### Version Information

Syncthing Version: v0.14.5
OS Version: Arch Linux [testing repo]
Browser Version: Firefox 48.0.1

**Comment by vdmkenny** [comment]
I just realized that I was syncing with a device still on 0.14.4, and since the changelog talks about "improving" this algorithm, the version conflict might have caused it.

**Comment by AudriusButkevicius** [comment]
I am closing this. Drop a message if you can reproduce on the latest version.
