### ISSUE TITLE
Files in .stignore propagate deletions

### ISSUE THREAD

**Issue by fsateler** [syncthing/syncthing#3543]
I have a relatively large sync folder. I have a `Pictures` folder, which contains several GB of pictures. In my work laptop I sync this folder (and I use syncthing-inotify here). Since to work I do not need to look at my pictures, I decided to ignore the Pictures folder. My .stignore looks like this:

```
Pictures/

```

I then proceeded (as a test) to delete a couple of subfolders there. The deletion propagated to the other syncs. Luckily I have a NAS where I use file versioning so no data is lost. But this was very unexpected.

The logs from the receiving end looked like this (for all the subdir tree):

```
INFO: Puller (folder "felipe", dir "Pictures/Viejas/$subfolder"): delete: remove $base/Pictures/Viejas/$subfolder: directory not empty
```

Unfortunately I did not capture logs on the sending side.

I am not sure if syncthing-inotify is at fault for watching on ignored folders, but still syncthing should not propagate changes to ignored folders.

### Version Information

Syncthing Version: v0.14.4 (sender) v0.14.3 (receiver)
OS Version: Windows 7 (sender) / Debian sid (receiver)

Sender uses syncthing-inotify (installed via syncthing-gtk v0.9.1-win32).

**Comment by AudriusButkevicius** [comment]
Dup #3502
