### ISSUE TITLE
Full File Versioning - keep X versions and auto-delete after Y days

### ISSUE THREAD

**Issue by go2null** [syncthing/syncthing#3544]
Currently, there is no way to have Syncthing backup all file versions AND automatically delete old versions.

**Trash Can File Versioning** keeps only `1` version, but can automatically delete versions older than `Y` days.  However, the auto-delete-old-version can be turned off.
**Simple File Versioning** only keeps `X` versions and doesn't automatically delete any.
**Staggered File Versioning** automatically deletes versions older than `Y` days, but doesn't backup all file versions. (It only keeps the *last* version per *interval*.)

This request is basically to have a File Versioning mode with both **Keep Versions = X** and **Until Maximum Age = Y**, where both `X` and `Y` can be set to `0` to turn them off.  *I understand that this can lead to running out of storage space if not used properly.*

This could also be implemented by incorporating functionality from *Trash Can File Versioning* and  *Staggered File Versioning* into *Simple File Versioning*:
1.  **Until Maximum Age**:  this will automatically delete old versions older than `Y` days.  Setting to `0` disables this functionality thus retaining the current behavior.
2.  **Keep Versions = 0**: this disables deleting files based on number of versions kept thus effectively keeping all versions.

Another way is to be able to override the *keep-1-version-per-interval* in *Staggered File Versioning* to keep all versions.  However, extending the *Simple File Versioning* per above gives the additional flexibility to only keep `X` versions.

**Comment by AudriusButkevicius** [comment]
Use external versioner to satisfy whatever criteria you want.
Yes, we won't satisfy everyone's usecase, as there will be people who want deletes every full moon, but that's why external versioner is there.

**Comment by Ferroin** [comment]
I was actually planning on bringing this up on the forums later today as I'd rather like to have such functionality, but apparently it's too hard to implement something in Syncthing for which most of the code already exists.

Looks like I'm writing a generic external versioning script then, I'll post a link here and in a forum thread when I've got it working.
