### ISSUE TITLE
Feature request: virtual folders 

### ISSUE THREAD

**Issue by kefir-** [syncthing/syncthing#3545]
In some cases it's useful to sync multiple folders that are not in the same location. For example, if I want to sync media from an android phone, I have to set up a sync folder for the photos (DCIM), and another one for every other photo app. It'd be handy if I could reduce the administrative overhead by configuring a "virtual folder" that contains all the folders I want to sync. This would then be a result in a single folder on the other devices in the cluster. 

This probably only makes sense together with master mode. The other devices probably shouldn't know it's a virtual folder.

**Comment by calmh** [comment]
I can sort of see the utility, but there is indeed trickyness in the bidirectionality. I'm not sure that I like a special different kind of folder that can only be used in read only mode, what with the whole point of Syncthing being that it's normally bidirectional.

**Comment by AudriusButkevicius** [comment]
You are syncing multiple folders so it's natural you need to have multiple of them. I don't think we should polute syncthing with workarounds just because you are able to store all of your content in a single folder.

I say we close this as won't fix.

**Comment by calmh** [comment]
Agreed, for the moment, as this is in fact possible with the current feature set and has undesirable complications if implemented. Sorry.

**Comment by kefir-** [comment]
Fair enough :-) As mentioned I'd imagine this would only be useful for master devices, in that case I'm not sure the bidirectionality would be a big problem. Anyway, perhaps this can be solved outside syncthing with symlinks? I haven't read any documentation on how syncthing handles symlinks.

**Comment by wweich** [comment]
Symlinks are synced as is: https://docs.syncthing.net/users/faq.html?highlight=links#what-things-are-synced
