### ISSUE TITLE
Stealth wrong warning on Trash Can file versionning setting

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#3547]
### Version Information

Syncthing Version: v0.14.5
OS Version: Ubuntu 14.04 / ...
Browser Version: FF38 & FF48

Case to reproduce:
Change File versionning from none to Trash Can and change the keep days from 0 to any other number, or if already set to Trash Can, just change the keep days to any other 0/+num value. Apply
What happens: you brefly see the warning intended for non 0/+num input, plus also red, the help text below file versionning type.  Although, the keep days is correctly set.
What should happen : correctly set and don't see the warn.

**Comment by calmh** [comment]
I can't reproduce this. How do you "Apply"? Just changing the number from zero to five or using the arrows to change it doesn't trigger any warning for me. Deleting the number triggers the red "must not be blank" which disappears when a number is entered again, but that's by design.

**Comment by bugith** [comment]
Hi Jacob. This a stealth display. I apply with the Save button. Maybe my PC or video card is not quick enough (or too fast). This happens while the Edit window closes.
Would you want a video capture ?

**Comment by calmh** [comment]
I'm interpreting this as the same or similar to #3433
