### ISSUE TITLE
[OpenBSD] Default config causes lynx to crash on startup

### ISSUE THREAD

**Issue by mmcco** [syncthing/syncthing#3548]
I and a few other OpenBSD port developers noticed that the file `/var/syncthing/lynx.core` was mysteriously but consistently appearing. We then noticed that lynx was crashing immediately upon Syncthing startup. It Frederic Cambus shared the following lynx failure message reported from cron:

```
  Your Terminal type is unknown!

  Enter a terminal type: [vt100]
TERMINAL TYPE IS SET TO vt100
^[[0;7m^OMaking HTTP connection to www.openbsd.org^[[m^O7m^OGetting http://www.openbsd.org/^[[m^O

^[[?1l^[>Abort trap (core dumped)
```

He suggested that this was because lynx is not launched in an interactive tty. I don't know much about these problems, but that seems reasonable to me. I can't imagine what the expected behavior would be; lynx certainly can't occupy the default tty because no user has logged in yet, and would that be reasonable behavior anyway?

OpenBSD don't patch Syncthing in any substantial manner or integrate lynx, so I suspect that this problem is present in other operating systems.

Thanks for your time,
Michael

### Version Information

Syncthing Version: v0.14.3
OS Version: OpenBSD 6.0 (development snapshot - Aug 23, 2016)
Browser Version: lynx  2.8.9dev.9 (10 Apr 2016)

**Comment by wweich** [comment]
Do you have Lynx set as you default browser? Syncthing (in the default setting) starts the browser with its WebUI on startup.
The file `/var/syncthing/lynx.core` isn't created by syncthing, though.

**Comment by mmcco** [comment]
I certainly haven't changed any config files to make Lynx my default browser. What API does Syncthing use to choose which browser to launch?

**Comment by calmh** [comment]
xdg-open, in the background so yes without a try. 

I think in your case simply disable "start browser" or explicitly start with `-no-browser`.
