### ISSUE TITLE
Lots of Mobile Data used Despite Setting

### ISSUE THREAD

**Issue by smithdtyler** [syncthing/syncthing#3550]
I installed Syncthing on my Android 6.0 LG G3 this morning. I immediately went to settings and selected "Sync only when charging" and "Sync only on wifi".

A couple of hours later, I checked my data usage and saw that Syncthing had used 1.6GB!

I disabled mobile data for Syncthing via the Android mobile data settings.

I restarted Syncthing several times during the initial setup as I added new folders to sync, but otherwise didn't do anything fancy (that I'm aware of). 

### Version Information

Syncthing Version: v0.14.5 (Installed from Google Play)
OS Version: Windows 7, Raspbian Linux

**Comment by wweich** [comment]
Wrong repo. Please post issues with the Android App in he Syncthing Android Repo: https://github.com/syncthing/syncthing-android
