### ISSUE TITLE
Slow syncthing speed

### ISSUE THREAD

**Issue by locutus007** [syncthing/syncthing#3553]
Dear Syncthing developers.

After finally switching from BitTorrent Sync to Syncthing, one thing annoyes me:
BitTorrent Sync could sync up to 11 MB/s between the two devices described below. Syncthing is stuck with about 1,7 MB/s. The CPU-load is constantly low (about 10% each).
From time to time, my devices do not sync at all.
I have also tried to install Linux on my Laptop too, but this doesn't make a difference.
Compression is also turned off(helped a little bit).
From what I have read in the forums, this is a widely seen issue(Raspberry Pi (2/3) does have this issue, too, possibly an ARM issue?).

If I can help you by providing logs, etc, please let me know. it would be great if you can fix this.

Yours faithfully,
TheJack

### Banana Pi M3:
 - Syncthing Version: v0.14.5
 - OS Version: Linux Ubuntu 16.04.1

### Laptop:
 - Syncthing Version: v0.14.5 x64
 - OS Version: Windows 10 x64/Linux Fedora 24

### Additional Information:
 -  ~87600 objects
 - ~262 GiB

**Comment by AudriusButkevicius** [comment]
Use forum for support, exactly as it's explained in the issue template.
