### ISSUE TITLE
Better distinction between actual transfers, vs local cloning

### ISSUE THREAD

**Issue by fragtion** [syncthing/syncthing#3555]
Hey all,

It is my understanding that Syncthing retains checksums for all files within a given repo/"Folder" as part of normal functionining

This means that if I have at least two Devices sharing a Folder which is 100% in sync, and then I create a copy of an existing file inside that Folder on any one of the Devices in the cluster, the expected behaviour from Syncthing is that it should Recognize that the Copied file is the same as the Original file which already exists on the Remote Devices, resulting in those Remote Devices creating a LOCAL copy of the file from the Original, based on the identified checksums. Instead what I am seeing is that it transfers the whole copied file to the remote devices

In my test case, I was using a Windows and Linux machine (both running v0.14.5) for the two Devices, and doing the "copying" on the Windows machine resulted in the "full transfer" of the copied file over to the Linux Device

Evidently, something seems to be bugging out? Surely the remote Device should create a "shortcut copy" (ie: prefer local copy of existing file with identical checksum rather than re-transfer) in ALL cases where the existing file can be found on that Device in the given Folder (in fact, I would argue that this functionality should span ALL folders, so that even if the file exists in 'another' Folder on that Device, it could still benefit from local copying rather than internet transfer for the same file.... Would this be too CPU intensive? Otherwise the potential benefits seem to be quite compelling?)

Thanks in advance

**Comment by canton7** [comment]
> Instead what I am seeing is that it transfers the whole copied file to the remote devices

What is your evidence for this?

**Comment by fragtion** [comment]
Well that's an easy one :P
On the "Remote"/Destination Device, it shows 1 items in "Out of Sync Items". If I click on that "1 items, ~750 MiB", I can see the file in question being slowly transferred

**Comment by canton7** [comment]
Are you sure that it's being transferred, not just that it's being copied on-disk?

**Comment by calmh** [comment]
FWIW I can't immediately reproduce this using the obvious test, so something differs. In the test setup, two instances on the same computer with one having a folder in `s1` and the other in `s2`:

```bash
# Start state, connected, almost no data transferred:

jb@syno:~/s/g/s/s/test $ curl -sH x-api-key:abc123 http://localhost:8082/rest/system/connections|json 'connections.I6KAH76-66SLLLB-5PFXSOA-UFJCDZC-YAOMLEK-CP2GB32-BV5RQST-3PSROAU'
{
  "address": "127.0.0.1:22001",
  "at": "2016-08-30T14:41:24.263334375+02:00",
  "clientVersion": "v0.14.5",
  "connected": true,
  "inBytesTotal": 391,
  "outBytesTotal": 344,
  "paused": false,
  "type": "TCP (Client)"
}

# Copy in the syncthing binary so there is something to transfer:

jb@syno:~/s/g/s/s/test $ cp ../bin/syncthing s1

# Check the amount of data shuffled:

jb@syno:~/s/g/s/s/test $ curl -sH x-api-key:abc123 http://localhost:8082/rest/system/connections|json 'connections.I6KAH76-66SLLLB-5PFXSOA-UFJCDZC-YAOMLEK-CP2GB32-BV5RQST-3PSROAU'
{
  "address": "127.0.0.1:22001",
  "at": "2016-08-30T14:41:44.442594399+02:00",
  "clientVersion": "v0.14.5",
  "connected": true,
  "inBytesTotal": 12269199,   # <-- yep
  "outBytesTotal": 11018,
  "paused": false,
  "type": "TCP (Client)"
}

# It's been transferred:

jb@syno:~/s/g/s/s/test $ ls -l s2
total 23960
-rwxr-xr-x  1 jb  staff  12263660 Aug 30 14:41 syncthing*

# Make a copy of it on the s1 side:

jb@syno:~/s/g/s/s/test $ cp s1/syncthing s1/other

# It gets synced to s2:

jb@syno:~/s/g/s/s/test $ ls -l s2
total 47920
-rwxr-xr-x  1 jb  staff  12263660 Aug 30 14:41 other*
-rwxr-xr-x  1 jb  staff  12263660 Aug 30 14:41 syncthing*

# Check the amount of data transferred:

jb@syno:~/s/g/s/s/test $ curl -sH x-api-key:abc123 http://localhost:8082/rest/system/connections|json 'connections.I6KAH76-66SLLLB-5PFXSOA-UFJCDZC-YAOMLEK-CP2GB32-BV5RQST-3PSROAU'
{
  "address": "127.0.0.1:22001",
  "at": "2016-08-30T14:42:09.061629529+02:00",
  "clientVersion": "v0.14.5",
  "connected": true,
  "inBytesTotal": 12273029, # <-- roughly same as before
  "outBytesTotal": 14848,
  "paused": false,
  "type": "TCP (Client)"
}
jb@syno:~/s/g/s/s/test $ 
```

**Comment by wweich** [comment]
> in fact, I would argue that this functionality should span ALL folders, so that even if the file exists in 'another' Folder on that Device, it could still benefit from local copying rather than internet transfer for the same file

This is already the case.

**Comment by fragtion** [comment]
OK you are right. I tried again with ifstat this time and it in fact copying on disk. I suppose the GUI is a bit deceptive in that it says "Sync" with a progress bar, and the rate of copy "seems" slower than it would if copying the file directly using file explorer. I suppose this is part of the illusion though. Could we not perhaps then shift the direction of this issue thread towards improving details/clarity in the transfer details popup, so that when copying from local disk copy it rather says "Cloning" than "Syncing"? I guess you can just look at the bandwidth, but this is bound to trick someone else. I think that intuitively, people don't expect to see a "Sync" progress bar if the file already exists on the target device. If hardlinking is out of the question there should be another way of knowing that the file is copying from disk I think

**Comment by calmh** [comment]
Doesn't it say "copied locally" or something like that in the transfer details window?

It is a bit slower than a local copy as we do it block by block and verify the SHA256 checksum of each of them against the expected as we go along.

**Comment by wweich** [comment]
The "Out of Sync Items" dialog already says if it was reused (from former partial transfer) or copied from original (on file changes), copied from elsewhere (from another file) or downloaded.

**Comment by AudriusButkevicius** [comment]
The ticket was opened without doing any homework and I think it's full of false claims. I suggest the original author goes back, to explores the UI better before making new claims or opening new tickets.

Syncing does not imply downloading, atleast to me, so your suggestions so far are subjective.
