### ISSUE TITLE
Syncthing freezing ubuntu

### ISSUE THREAD

**Issue by Gibbz** [syncthing/syncthing#3559]
Bug:
- what happened,
syncthing freezes ubuntu about 2 minutes after starting

 - what you expected to happen instead, and
no freeze, be warm :)

 - any steps to reproduce the problem.
no, it just started happening. Im not sure if there was a recent update this week or not?

### Version Information
Syncthing Version: v0.14.5
OS Version: ubuntu 16.04

Is there a log file i can access without having to run syncthing?

**Comment by Gibbz** [comment]
ive formatted my file system and it looks like its fixed the issue. Must have been some unaccessable files causing it to freeze the system

**Comment by AudriusButkevicius** [comment]
A program should never freeze a system, if it does, its the systems fault. Also, you should have used the forum as there is no obvious bug here and it's more like a support request
