### ISSUE TITLE
Master sure it's not finished, peer sure it is

### ISSUE THREAD

**Issue by AntonD-mobilmir** [syncthing/syncthing#356]
Master:
![image](https://cloud.githubusercontent.com/assets/7845465/3228346/e3d33c4c-f085-11e3-8c0b-552b1af67faa.png)
Peer:
![image](https://cloud.githubusercontent.com/assets/7845465/3228348/e77f7a2c-f085-11e3-931b-6909d76c614f.png)

I compared directories with another tool, and they're completely identical currently.

Restarting of both Master and Peer changed nothing.

**Comment by cihadturhan** [comment]
I can confirm this bug exists on v0.10.17. I have windows and linux. Linux says everything is synced but windows is stuck at 99%.

If it helps, I checked web dev tools and observed the network data. It's not about the web interface, it's about the data from localserver which says it's `99.45755720634898` percent.

**Comment by AudriusButkevicius** [comment]
If some files are ignored on some device, non 100% completion is expected, as that device doesn't have the full set of files.
