### ISSUE TITLE
feature request: Add option to sync .stignore

### ISSUE THREAD

**Issue by onodera-punpun** [syncthing/syncthing#3561]
Yes, I know I can reference another file in .stignore and sync that, but

  a - That's kinda messy
  b - Easy to forget  acutally creating the .stignore with reference when adding a new machine
  c - Just really, kinda annoying and not user friendly.

I think a simple checkbox or something would do the trick :)

**Comment by AudriusButkevicius** [comment]
If you wish to provide the code for it, sure, otherwise I feel this is just another one in the pile of things that are unlikely  to happen just because workarounds exist.

**Comment by calmh** [comment]
#2491
