### ISSUE TITLE
Files that could not sync because Syncthing disliked their filenames continue to' out of sync' error when deleted

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [syncthing/syncthing#3562]
The files in question have been deleted from the machines on which they were shared, viz. (1) a Windows 8.1 machine and (2) a Linux Mint laptop; I use only the web interface on both devices.

The 'out of sync' error shows on the Windows machine (not the Linux one) and I can find no way of removing it. I've tried restarting SyncThing (on both machines), and I've sought, and failed to find, the option - that appears sometimes - to force acceptance of changes. I've tried the 'rescan' option too.

Syncthing Version: v0.14.5 (on both machines)
OS Version: Windows 8.1 and Linux Mint 18.1

I apologise if this bug is a duplicate of another one.

**EDIT (an addition)**: The filenames with which the problem began were the names of files generated by the 'UnMHT' extension for Firefox - and this is not the first time I have had trouble with those names. So, you might want to look into that.

**Comment by calmh** [comment]
Screenshot or at least verbatim of the actual error, maybe?

**Comment by ACinnamonUserInUK** [comment]
I am afraid that I cannot provide either of those things, because (for not for the first time) I deleted most of my Syncthing config and started again. However, having done that, I now have other problems concerning a device showing its syncing progress as a negative number and now - for that situation did not persist - other problems. I'll try to fix them on my own.
