### ISSUE TITLE
Deleted files are pushed back to the "deleter"

### ISSUE THREAD

**Issue by gerroon** [syncthing/syncthing#3563]
I regularly delete and move files around. These changes are reflected across online devices . The issue is that I also have some Android clients and naturally they can be offline sometimes, ranging from a day to a week or so. When an android client gets back online sometimes they send the deleted/moved/renamed files back to the Linux box that managed those folders in the first place.

Unfortunately I do not have a concrete step to produce the issue because I find these cases after the fact even sometimes couple days later. So all I can say is that I regularly hit these edge cases and I have to manually delete those files that were not supposed to be there in the first place.

I am prettry sure that this is an issue with the offline clients because I do not remember online clients getting confused about the state of the files. 

I feel like the offline clients do not get the true state of the current state of the repos and start pushing back their versions of the files. Maybe they are too late to the party? Maybe ST is loosing changes after a while, or forgetting them after a while so by the time the Android client is back, there is no past memory of the changed files.

My ST farm is mix of Linux and Android clients. 
Linux 
Debian Testing 64 bit (0.14.5)
Debian Wheezy 32bit (0.14.5)

Android
Lollipop 5.1 (latest F-droid build)
Marshmallow (latest F-droid build)
Kitkat 4.1 ((latest F-droid build))

thanks

**Comment by calmh** [comment]
Most likely this is because the files changed in some way on the android side - could be just th modification time or other metadata. What kind of files is it?

**Comment by gerroon** [comment]
@calmh 

No they did not change at all. For instance I made some changes last night in a repo. Couple hours later I made one offline client online and those files are back. That particular client is just an Android ereader I never mess with files on it. But the issue can be repeated by other offline clients.

**Comment by AudriusButkevicius** [comment]
Can you repro this with no android involved?

**Comment by gerroon** [comment]
@AudriusButkevicius 

Based on my experience, I never had issues with non android clients but the thing is that I only have 2 non android clients (both are linux desktop) and they are always online. 

I cant try  this particular scenario because both are my servers that are needing to run 24/7.

**Comment by calmh** [comment]
"latest f-droid build" is what version of Syncthing underneath? That should be visible in the web ui, if not anywhere else

**Comment by capi** [comment]
Latest Android release is at v0.14.5. That's also the one available from F-Droid.

**Comment by calmh** [comment]
Then I have no idea what's going on here, barring random android shenanigans or this happening during upgrade from pre-0.14.5 to 0.14.5 while offline with deletes pending

**Comment by calmh** [comment]
Not enough info / not reproducible / needs Android guru to narrow down
