### ISSUE TITLE
GET to /rest/syste/config returns 403 Forbidden (CSRF)

### ISSUE THREAD

**Issue by khaledkbadr** [syncthing/syncthing#3566]
I'm trying to do GET to /rest/syste/config `curl -v http://127.0.0.1:18384/rest/system/config`
but all I get in return is 
```
Trying 127.0.0.1...
Connected to 127.0.0.1 (127.0.0.1) port 18384 (#0)
> GET /rest/system/config HTTP/1.1
> Host: 127.0.0.1:18384
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< X-Syncthing-Id: D6HDBHS-GVJMKYH-MPK6FGF-2A22ZTP-HVDRI6W-N53UNCP-DDMGP7N-JVF5QAV
< X-Syncthing-Version: v0.14.5
< Date: Mon, 05 Sep 2016 13:29:11 GMT
< Content-Length: 11
< 
CSRF Error
Connection #0 to host 127.0.0.1 left intact
```
I'm using `GET` request so I don't think I need to use API-Key

**Comment by calmh** [comment]
No, you do. The docs are a little out of date, I'll try to remember to fix them.

**Comment by calmh** [comment]
Docs fixed, thanks for bringing it to our attention!

https://github.com/syncthing/docs/commit/1b4602d058a48f35f174f4106e14739feeb6f6ad
