### ISSUE TITLE
Wrong status shown on gui

### ISSUE THREAD

**Issue by biels** [syncthing/syncthing#3568]
The gui shows that the device is "Up to date" while it knows that it isn't and it is in fact syncing files. Maybe this could be a result of bad network conditions. I don't know the exact steps to reproduce the problem since it appears only in some cases in spite of apparently doing the same. I cannot determine if it is a gui problem or a core problem.
![image](https://cloud.githubusercontent.com/assets/5158960/18288143/7fbd5c3a-747a-11e6-8d91-c286d00734e8.png)

### Version Information

Syncthing Version: v0.14.6
OS Version: Windows 10
Browser Version:  Chrome 52.0.2743.116

**Comment by calmh** [comment]
It looks as if you're just downloading data from that device. That means that device is up to date, and you are not.
