### ISSUE TITLE
Bug: Exit Codes

### ISSUE THREAD

**Issue by NenePerez** [syncthing/syncthing#3570]
The exit code returned by syncthing when you upgrade is 0. Should be 4

### Version Information

Syncthing Version: v0.14.5
OS Version: Windows 7

**Comment by AudriusButkevicius** [comment]
4 is returned when you run without a monitor process

**Comment by AudriusButkevicius** [comment]
And it's only returned to signal the monitor process the reason for the exit.

**Comment by NenePerez** [comment]
My project is to make an installer for windows with Inno Setup
[Syncthing_innosetup.zip](https://github.com/syncthing/syncthing/files/458714/Syncthing_innosetup.zip)

**Comment by NenePerez** [comment]
When syncthing updated, the service doesn't restart

**Comment by AudriusButkevicius** [comment]
It does restart if its running with a monitor process, if it's running without one, then it's your job to restart it when you see exit code 4

**Comment by canton7** [comment]
People have written installers for Syncthing before. Check the community contributions doc page and the forums.
