### ISSUE TITLE
Prioritising relay ports

### ISSUE THREAD

**Issue by tomtaylor** [syncthing/syncthing#3571]
I'm often running my syncthing client inside a corporate network that filters permitted outbound ports. The relays that my client often tries to connect to (currently `relay://163.172.132.71:990` `relay://37.187.57.69:22067`) are port blocked. Port 443 is permitted on my network, but my client hasn't selected a relay which uses those ports, so isn't currently able to access a relay.

Given port 443 is likely to have the highest compatibility, as well as comparing latency and other things, I think it would be helpful to prioritise some relays that use port.

**Comment by AudriusButkevicius** [comment]
It tries all relays available until is succeeds
