### ISSUE TITLE
Sync error: filename is invalid

### ISSUE THREAD

**Issue by Stellar7** [syncthing/syncthing#3572]
I am syncing a folder from my Android phone (Galaxy Note 5, Sprint, latest software).  I am getting the following error:

Failed Items
The following items could not be synchronized. They are retried automatically and will be synced when the error is resolved.

2016.06.06 Lowes 5 yr extended warranty	filename is invalid
2016.06.06 Lowes 5 yr extended warranty .pdf	filename is invalid
201606081421431000.jpg	filename is invalid
201606081421431001.jpg	filename is invalid
201606081421431002.jpg	filename is invalid
201606081421431003.jpg	filename is invalid
201606081421431004.jpg	filename is invalid

### Version Information

Syncthing Version: v0.14.6, Windows (64 bit)
OS Version: Windows 7 
Browser Version:  Chrome

**Comment by wweich** [comment]
Please use the [forums](https://forum.syncthing.net/) for support. GitHub is for bugs.

The pdf cannot be synced to Windows, because windows doesn't allow spaces at the end of a file name.
