### ISSUE TITLE
Not possible to listen on randomly chosen port

### ISSUE THREAD

**Issue by stuartlangridge** [syncthing/syncthing#3574]
I'm starting up multiple instances of syncthing. For this reason, I'd like to tell them to listen on port 0 (which means "the operating system chooses an unused port"), rather than hardcoding a port into each one. This is possible, but as far as I can tell if I do that, there's no way of having syncthing tell me which port got chosen. Perhaps there could be some sort of output of this in some way? Or maybe there is a way and I just don't know what it is?

**Comment by AudriusButkevicius** [comment]
it tells you in the log, also, /system/status endpoint lists listen addresses.

**Comment by stuartlangridge** [comment]
`/system/status` does list addresses, but the GUI would also have to be started on port 0, so I don't know where that is. I can, if desperate, programmatically parse the log, but that's a bit nasty...

**Comment by AudriusButkevicius** [comment]
So how do you expect to contact syncthing if everything is started on a random port? Telekinesis?

**Comment by stuartlangridge** [comment]
An option to write the port out somewhere where it can be read. Tor, for example, implements this that way (you can specify a file to write the control port to) for exactly this reason. I was hoping such a thing already existed; understood that it does not. It would be useful for this use case, though, and would allow automating syncthing startup.

**Comment by AudriusButkevicius** [comment]
I am fairly certain this is niche enough that it will never happen.
Content written into files is just as dodgy as pid files, and can go stale very fast.

I suggest you find a free port yourself, and pass it to -gui-address.

**Comment by stuartlangridge** [comment]
That's, unfortunately, racy -- someone might grab the port in between me dropping it and starting syncthing. It looks like I should be able to parse the log though, which is rather prone to breakage but may get me going. Thank you for listening.

**Comment by calmh** [comment]
This is printed on startup:

```
jb@syno:~/tmp $ grep address asdasd/config.xml 
        <address>dynamic</address>
        <address>127.0.0.1:0</address>
```

(the latter one is the GUI address)

```
jb@syno:~/tmp $ syncthing -home asdasd | grep listening
[M7NJU] 21:48:39 INFO: GUI and API listening on 127.0.0.1:63162
```

**Comment by stuartlangridge** [comment]
Yup; I'm now parsing it out of the log. (This is suspect behaviour because you might, perfectly legitimately, change what the log prints there and break my code, and I wouldn't blame you a bit, but it'll do me for now :))

(Extra bug: It also prints `Access the GUI via the following URL: http://127.0.0.1:0/`, which is not true :))

**Comment by calmh** [comment]
Yeah. Note though that in general services do require a known port number and this does work perfectly fine in almost all setups. Syncthing even does auto detection of this on initial setup and will use other ports if 8384 and 22000 are taken at that time.

**Comment by stuartlangridge** [comment]
Really?? So I don't need to specify port 0, I can just hardcore whatever I want and read the actual port out of the log anyway? Nice :)

It'd still be nice to have some reliable way of getting it rather than parsing human readable log lines with code, but... parsing the log works, so I'm cool

**Comment by AudriusButkevicius** [comment]
The random value only gets picked on the first startup, so you'd have to make sure the ports picked stay available. After that you can probably just grep the config.
