### ISSUE TITLE
Upnp Issue

### ISSUE THREAD

**Issue by AlroneRhyn** [syncthing/syncthing#3575]
Hi Guys !

I've got a bad issue with my new ISP : my discosrv seems to annouce the private router address instead of the public router address (192.168.1.254). I can't find why !

Architecture : arsenic (1.50) and kipsi (1.2) are syncthing devices on the same LAN. arsenic and the discosrv are on the same debian. Arsenic and kipsi doesn't have the Local Discovery activated, but NAT yes. They both can talk to my discosrv through its nated public ip thanks to a port redirection.

When i activate relay, it's working, but i shouldn't need it.

Here is my syncthing upnp debug start :
c@a:~$ syncthing upnp
[monitor] 20:21:14 INFO: Starting syncthing
[...] 20:21:14 INFO: syncthing v0.14.6 "Dysprosium Dragonfly" (go1.7 linux-amd64) jenkins@build.syncthing.net 2016-09-04 21:06:30 UTC
[...] 20:21:14 INFO: My ID: TADA
[...] 20:21:14 INFO: Single thread hash performance is ~59 MB/s
[...] 20:21:14 INFO: Ready to synchronize FOLDER (readwrite)
[...] 20:21:14 INFO: Ready to synchronize FOLDER (readwrite)
[...] 20:21:14 INFO: Using discovery server https://foo.bar:8443/v2/
[...] 20:21:14 INFO: TCP listener ([::]:22000) starting
[...] 20:21:14 INFO: Completed initial scan (rw) of folder FOLDER
[...] 20:21:15 INFO: Device TADA [dynamic]
[...] 20:21:15 INFO: GUI and API listening on 192.168.1.50:port
[...] 20:21:15 INFO: Access the GUI via the following URL: https://192.168.1.50:port/
[...] 20:21:15 INFO: Completed initial scan (rw) of folder FOLDER
[...] 20:21:25 INFO: New NAT port mapping: external TCP address PUBLIC_IP:port to local address 0.0.0.0:22000.
[...] 20:21:25 INFO: Detected 1 NAT device

Here is my disco server debug :
b@a:~/# /usr/local/bin/discosrv -cert /var/discosrv/certs/cert.pem -key /var/discosrv/certs/key.pem -debug
stdiscosrv v0.14.5 (go1.7 linux-amd64) jenkins@build.syncthing.net 2016-08-23 08:42:09 UTC
Server ID ID is TADA
[...] GE[...] T /v2/?ID=$ID1
[...] GET /v2/?ID=$ID1 completed in 435.996µs 
[...] POST /v2/
[...] updateID in 162.328µs
[...] insertID in 250.917µs
[...] commit in 9.825µs
[...] POST /v2/ completed in 1.161886ms 
[...] GET /v2/?ID=$ID2
[...] GET /v2/?ID=$ID2 completed in 1.079609ms 
[...] GET /v2/?ID=$ID3
[...] GET /v2/?ID=$ID3 completed in 452.659µs 
[...] GET /v2/?ID=$ID4
[...] getAddresses in 1.868088ms
[...] GET /v2/?ID=$ID4 completed in 3.327429ms 
[...] POST /v2/
[...] updateID in 741.453µs
[...] commit in 29.726µs
[...] POST /v2/ completed in 5.103378ms 
Stats: 0.01 announces/s, 0.01 queries/s, 0.00 answers/s, 0.00 errors/s
[...] GET /v2/?ID=$ID4
[...] getAddresses in 1.70056ms
[...] GET /v2/?ID=$ID4 completed in 3.437106ms 

You can see here that my UPnp is working :

![upnp](https://cloud.githubusercontent.com/assets/8383459/18324027/b2e778d2-753a-11e6-9ccf-e65bf1b4250a.png)

And that my Syncthing is get from the discovery server the private ip :

![upnp_syncthing](https://cloud.githubusercontent.com/assets/8383459/18324045/cf0c56cc-753a-11e6-8358-015e619bb389.png)

Is there something i'm missing ?
Thanks a lot for your help, i'm struggling.

**Comment by AudriusButkevicius** [comment]
Use the forum for questions.
