### ISSUE TITLE
Syncthing ID reset on server reboot can we get an export and import backup feature?

### ISSUE THREAD

**Issue by NIXOYE** [syncthing/syncthing#3576]
I run syncthing on a server i use as a backup but when i logged on today syncthing was completely blank and the device id is different. Now I have to manually add my devices and folders again. On the android app there is an export and import configuration feature that would be amazing for the syncthing webui and syncthing-gtk versions.

Also any idea why syncthing forgot everything after i rebooted the server?

edit: realized everything was reset because i launched as root user by accident. Relaunched as normal user and everything is fine again. Still think a import and export backup feauture in the web ui and gtk ui is very important so ill keep this issue up

**Comment by calmh** [comment]
You can just copy the files in ~/.config/syncthing/{*.xml, *.pem}. But there is a ticket somewhere for config export in the GUI, I think.
