### ISSUE TITLE
UPnP not doing port mapping on all discovered routers

### ISSUE THREAD

**Issue by lugrinder** [syncthing/syncthing#3578]
I've two routers in the network to access internet with UPnP (NAT) enabled and Syncthing, and most of the times it adds the port mapping to the incorrect router.

The mapping will be added to the default gateway used by the interface.

### Version Information

Syncthing Version: v0.14.6
OS Version: Windows 10 (64 bit)

**Comment by calmh** [comment]
I believe it should add them to any and all routers it finds?

**Comment by AudriusButkevicius** [comment]
Yes, run with STTRACE=nat,upnp and provide logs.

**Comment by lugrinder** [comment]
Yes, scan for all but one of them (my default gateway) does not add the port mapping some times. Attached two logs: working and not working..
[syncthing.both.txt](https://github.com/syncthing/syncthing/files/461454/syncthing.both.txt)
[syncthing.one.txt](https://github.com/syncthing/syncthing/files/461453/syncthing.one.txt)

**Comment by calmh** [comment]
I see discovery responses from both .52 and .59 in both traces, but we appear to only talk to .52 in one of them. Not sure why.

**Comment by AudriusButkevicius** [comment]
There is something funky happening with the duplicate check I think. If you grep and look at the code for:
`with services` I cannot explain how it suddenly becomes a duplicate

**Comment by calmh** [comment]
Sounds like a bonafide bug then

**Comment by AudriusButkevicius** [comment]
Can you do the grepping and starting at the code to confirm that you agree with my analysis?

**Comment by calmh** [comment]
Yeah I see it, it's broken. We append the pointer to result

```go
results = append(results, &result) // L123
```

but `result` is reused in every iteration of

```go
for result := range resultChan { // L112
```

so on the next iteration it'll point to the *current* result, being a "duplicate".

**Comment by lugrinder** [comment]
I've tested the new version 0.14.7 that includes the fix, but now I have another problem in the UPnP NAT process and I don't know if is the same issue (not fully resolved) or another one (caused by two UPnP gateways on the network), so I've attached the log to determine this. 
Now detects the second gateway and process the UPnP messages, but it does not detect a valid gateway..
[syncthing.log.txt](https://github.com/syncthing/syncthing/files/505959/syncthing.log.txt)

**Comment by AudriusButkevicius** [comment]
This fix is 10 days old, last release is 13 days old...

**Comment by lugrinder** [comment]
Sorry, small mistake.. Now v0.14.8 works fine..
