### ISSUE TITLE
[UX] No clear or easy way to change the path of the folder to sync to

### ISSUE THREAD

**Issue by balmyBanzai** [syncthing/syncthing#3579]
How do I change my Sync folder from %USERPROFILE%\Sync to something else?

I don't see it in the getting started guide.

I don't see it in the FAQs.

I see where I can change my _configuration_ path, but not my sync path, or at least not stated that way. When I went to use syncthing.exe -home"E:\something_else" it did a fine job of dumping a bunch of config files there, which is not what I wanted.

Is this even _possible_?

If it is then the UX is _**terrible**_. This is such a fundamental setting!

**Comment by calmh** [comment]
The ui for this would be tricky to get right, because it's a fundamentally very dangerous operation. Hence it is currently not possible, no. 

(You can of course do it by editing the config, and in the edvanced config dialog, but significant caveats apply.)

**Comment by AudriusButkevicius** [comment]
Essentially, you can suddenly point syncthing at an empty folder, which would nuke all files on the remote site, hence why this is not possible, and removing and adding is required.

**Comment by balmyBanzai** [comment]
@AudriusButkevicius & @calmh Can you please add the instructions _somewhere_ easy to find _with_ those caveats? Closing a UX issue for a non-UX reason with no action taken doesn't help me, you, Syncthing, or its community.

I edited the config, and re-ran the service, and it still was not pointing to the updated folder, thus why I came here to report this in the first place. It was the first thing I tried, but as I could not locate any instructions on how to do this, I did not feel like it was a valid bug, as no expectations for behavior were even established via documentation.

**Comment by AudriusButkevicius** [comment]
I've explained how you do this in my last comment. 

We are closing this as this is a foot gun, and we are not going to add a foot gun for people to loose all of their files no matter how unhappy you are about the UX.

**Comment by balmyBanzai** [comment]
You're more than welcome to. I will not be using software, then, nor will I recommend it. Adios.

**Comment by chucic** [comment]
Stop Syncthing, move folder, edit config file. start Syncthing. I've done it many times.

**Comment by canton7** [comment]
> and removing and adding is required

Like he said, remove the folder and add it again with the same ID but a different path.

**Comment by balmyBanzai** [comment]
Thanks @chucic & @canton7 -- It's easy to forget what it's like to be a newbie when you're a contributing member, so even basic steps like this can be taken for granted. If I had known that @AudriusButkevicius meant, 

> "Add a new Syncthing folder pointing to the path you want to your list of folders, then if want to you can delete the original default, making your new folder the new default"

when they said, 

> "...hence why this is not possible, and removing and adding is required,"

it would have been very clear.

To be fair I had tunnel-vision when I started this. I wasn't thinking of workarounds but a direct step to change the existing config. It's a perfectly respectable workaround and even calling it a workaround may not be too fair since it's such a snap to do.

Thanks to _all_ for helping me out :) It's working like a charm, now. Apologies for the miscommunication. Please consider trying to be more specific with non-contributors when pertinent.

**Comment by Ferroin** [comment]
It may be worth putting something in the FAQ about how to do this, I've had friends who I've told about Syncthing ask me about how to do this, so while it may seem obvious to some people, it obviously isn't to everyone.

**Comment by AudriusButkevicius** [comment]
Well then be the good citizen and make a pull request.

**Comment by balmyBanzai** [comment]
@AudriusButkevicius -- please consider how your words will affect someone. Do you think @Ferroin would feel inclined to contribute after that remark? Most would not. Maybe you don't care, which is a fine philosophy to have, but you affect Syncthing's reputation, and you're not helping that reputation right now.

**Comment by ProactiveServices** [comment]
balmyBanzai: Submitting a PR to merely add an FAQ entry is entirely within the realm of anyone smart enough to ask the sort of questions that the OP has made. Syncthing's devs' "reputation" has always been "to the point".

**Comment by calmh** [comment]
Tone is tricky in written communication. You yourself have less than optimally subtle wording in your initial report, possibly setting the tone for the discussion in this issue. Audrius means to say that the FAQ is editable by anyone with a github account, and to my knowledge this hasn't been asked frequently enough to have been addded yet - yet you're all very welcome to help us improve the FAQ.

I'm closing this discussion here as I don't see it being constructive any more.
