### ISSUE TITLE
Clearly visible version number on web GUI

### ISSUE THREAD

**Issue by hally9k** [syncthing/syncthing#3580]
I think the current version number should be clearly visible on the GUI.
I had an updating issue before with 0.14 / 0.13 not talking the same version of the protocol and it would have been good to be able to clearly see the version numbers on the GUI.
Thanks for all the great work by the way! Awesomeness of the highest!

**Comment by calmh** [comment]
It's visible by default, at the bottom of "this device" on the right, which is expanded by default.

**Comment by hally9k** [comment]
Oh geez apologies, I must be blind! Thanks for your prompt assistance 👍

**Comment by hally9k** [comment]
I can see that both my devices are on 0.14.6 but I'm still getting the `Incompatible (v0.13) local discovery packet from 192.168.X.X:53026 - upgrade that device to connect`
Any Ideas?

**Comment by AudriusButkevicius** [comment]
There is a device on the network that is using an old version.

**Comment by hally9k** [comment]
Oh yes I see the process now, (having a slow morning here in NZ) my launchd seems to be spinning up the old binary aswell as the new one. Didn't see it in ps before but have delayed start for some reason... Thanks for your logical assistance!
