### ISSUE TITLE
feature request: Silent or Mass upgrade syncthing client?

### ISSUE THREAD

**Issue by kokojie** [syncthing/syncthing#3583]
I would like a "silent upgrade" feature similar to Chrome/Dropbox, when this option is turned on, the client upgrades itself without user intervention.

If that is not possible, then I'd like a "mass upgrade" feature, where all connected clients gets upgraded simultaneously if I click "upgrade" at one client. 

When you have 10+ clients connected, upgrading quickly become a chore to go to each one and upgrade.

**Comment by AudriusButkevicius** [comment]
It already does that,if automatic upgrades are enabled.
