### ISSUE TITLE
Continuous relay disconnects flood the app output

### ISSUE THREAD

**Issue by ssg** [syncthing/syncthing#3585]
I don't know if it's normal to constantly connect to and disconnect from a relay. But if it's normal, I'd rather not see it in the log continously. It almost feels like seeing every TCP packet transferred.. Is there a way to avoid this pattern in the output? It makes me miss other important issues because this fills up the scrollback buffer.

<pre>
[SOMEID] 22:11:06 INFO: Established secure connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE at some.ip:34448-relay.ip:22067 (Relay (Client))
[SOMEID] 22:11:06 INFO: Device SOME-OTHER-IDOF-SOME-OTHER-DEVICE client is "syncthing v0.14.6" named "ComputerName"
[SOMEID] 22:11:06 INFO: Connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE closed: reading length: EOF
[SOMEID] 22:21:32 INFO: Established secure connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE at some.ip:34514-relay.ip:22067 (Relay (Client))
[SOMEID] 22:21:32 INFO: Device SOME-OTHER-IDOF-SOME-OTHER-DEVICE client is "syncthing v0.14.6" named "ComputerName"
[SOMEID] 22:21:32 INFO: Connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE closed: reading length: EOF
[SOMEID] 22:31:58 INFO: Established secure connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE at some.ip:34580-relay.ip:22067 (Relay (Client))
[SOMEID] 22:31:58 INFO: Device SOME-OTHER-IDOF-SOME-OTHER-DEVICE client is "syncthing v0.14.6" named "ComputerName"
[SOMEID] 22:31:58 INFO: Connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE closed: reading length: EOF
[SOMEID] 22:42:23 INFO: Established secure connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE at some.ip:34635-relay.ip:22067 (Relay (Client))
[SOMEID] 22:42:23 INFO: Device SOME-OTHER-IDOF-SOME-OTHER-DEVICE client is "syncthing v0.14.6" named "ComputerName"
[SOMEID] 22:43:53 INFO: Connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE closed: reading length: EOF
[SOMEID] 22:52:45 INFO: Established secure connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE at some.ip:34692-relay.ip:22067 (Relay (Client))
[SOMEID] 22:52:45 INFO: Device SOME-OTHER-IDOF-SOME-OTHER-DEVICE client is "syncthing v0.14.6" named "ComputerName"
[SOMEID] 22:52:45 INFO: Connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE closed: reading length: EOF
[SOMEID] 23:03:08 INFO: Established secure connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE at some.ip:34750-relay.ip:22067 (Relay (Client))
[SOMEID] 23:03:08 INFO: Device SOME-OTHER-IDOF-SOME-OTHER-DEVICE client is "syncthing v0.14.6" named "ComputerName"
[SOMEID] 23:03:08 INFO: Connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE closed: reading length: EOF
[SOMEID] 23:13:51 INFO: Established secure connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE at some.ip:34821-relay.ip:22067 (Relay (Client))
[SOMEID] 23:13:51 INFO: Device SOME-OTHER-IDOF-SOME-OTHER-DEVICE client is "syncthing v0.14.6" named "ComputerName"
[SOMEID] 23:13:51 INFO: Connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE closed: reading length: EOF
[SOMEID] 23:24:17 INFO: Established secure connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE at some.ip:34884-relay.ip:22067 (Relay (Client))
[SOMEID] 23:24:17 INFO: Device SOME-OTHER-IDOF-SOME-OTHER-DEVICE client is "syncthing v0.14.6" named "ComputerName"
[SOMEID] 23:24:17 INFO: Connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE closed: reading length: EOF
[SOMEID] 23:34:36 INFO: Established secure connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE at some.ip:34944-relay.ip:22067 (Relay (Client))
[SOMEID] 23:34:36 INFO: Device SOME-OTHER-IDOF-SOME-OTHER-DEVICE client is "syncthing v0.14.6" named "ComputerName"
[SOMEID] 23:34:36 INFO: Connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE closed: reading length: EOF
[SOMEID] 23:44:54 INFO: Established secure connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE at some.ip:35003-relay.ip:22067 (Relay (Client))
[SOMEID] 23:44:54 INFO: Device SOME-OTHER-IDOF-SOME-OTHER-DEVICE client is "syncthing v0.14.6" named "ComputerName"
[SOMEID] 23:47:24 INFO: Connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE closed: read timeout
[SOMEID] 23:55:17 INFO: Established secure connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE at some.ip:35063-relay.ip:22067 (Relay (Client))
[SOMEID] 23:55:17 INFO: Device SOME-OTHER-IDOF-SOME-OTHER-DEVICE client is "syncthing v0.14.6" named "ComputerName"
[SOMEID] 23:55:17 INFO: Connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE closed: reading length: EOF
[SOMEID] 00:05:47 INFO: Established secure connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE at some.ip:35125-relay.ip:22067 (Relay (Client))
[SOMEID] 00:05:47 INFO: Device SOME-OTHER-IDOF-SOME-OTHER-DEVICE client is "syncthing v0.14.6" named "ComputerName"
[SOMEID] 00:05:47 INFO: Connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE closed: reading length: EOF
[SOMEID] 00:16:12 INFO: Established secure connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE at some.ip:35190-relay.ip:22067 (Relay (Client))
[SOMEID] 00:16:12 INFO: Device SOME-OTHER-IDOF-SOME-OTHER-DEVICE client is "syncthing v0.14.6" named "ComputerName"
[SOMEID] 00:16:12 INFO: Connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE closed: reading length: EOF
[SOMEID] 00:26:30 INFO: Established secure connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE at some.ip:35250-relay.ip:22067 (Relay (Client))
[SOMEID] 00:26:30 INFO: Device SOME-OTHER-IDOF-SOME-OTHER-DEVICE client is "syncthing v0.14.6" named "ComputerName"
[SOMEID] 00:26:30 INFO: Connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE closed: reading length: EOF
[SOMEID] 00:36:55 INFO: Established secure connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE at some.ip:35306-relay.ip:22067 (Relay (Client))
[SOMEID] 00:36:55 INFO: Device SOME-OTHER-IDOF-SOME-OTHER-DEVICE client is "syncthing v0.14.6" named "ComputerName"
[SOMEID] 00:36:55 INFO: Connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE closed: reading length: EOF
[SOMEID] 00:47:13 INFO: Established secure connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE at some.ip:35363-relay.ip:22067 (Relay (Client))
[SOMEID] 00:47:13 INFO: Device SOME-OTHER-IDOF-SOME-OTHER-DEVICE client is "syncthing v0.14.6" named "ComputerName"
[SOMEID] 00:47:13 INFO: Connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE closed: reading length: EOF
[SOMEID] 00:57:33 INFO: Established secure connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE at some.ip:35421-relay.ip:22067 (Relay (Client))
[SOMEID] 00:57:33 INFO: Device SOME-OTHER-IDOF-SOME-OTHER-DEVICE client is "syncthing v0.14.6" named "ComputerName"
[SOMEID] 00:58:18 INFO: Connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE closed: reading length: EOF
[SOMEID] 01:07:54 INFO: Established secure connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE at some.ip:35491-relay.ip:22067 (Relay (Client))
[SOMEID] 01:07:54 INFO: Device SOME-OTHER-IDOF-SOME-OTHER-DEVICE client is "syncthing v0.14.6" named "ComputerName"
[SOMEID] 01:07:54 INFO: Connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE closed: reading length: EOF
[SOMEID] 01:18:14 INFO: Established secure connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE at some.ip:35552-relay.ip:22067 (Relay (Client))
[SOMEID] 01:18:14 INFO: Device SOME-OTHER-IDOF-SOME-OTHER-DEVICE client is "syncthing v0.14.6" named "ComputerName"
[SOMEID] 01:20:44 INFO: Connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE closed: read timeout
[SOMEID] 01:28:37 INFO: Established secure connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE at some.ip:35609-relay.ip:22067 (Relay (Client))
[SOMEID] 01:28:37 INFO: Device SOME-OTHER-IDOF-SOME-OTHER-DEVICE client is "syncthing v0.14.6" named "ComputerName"
[SOMEID] 01:28:37 INFO: Connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE closed: reading length: EOF
[SOMEID] 01:38:56 INFO: Established secure connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE at some.ip:35676-relay.ip:22067 (Relay (Client))
[SOMEID] 01:38:56 INFO: Device SOME-OTHER-IDOF-SOME-OTHER-DEVICE client is "syncthing v0.14.6" named "ComputerName"
[SOMEID] 01:38:56 INFO: Connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE closed: reading length: EOF
[SOMEID] 01:49:21 INFO: Established secure connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE at some.ip:35748-relay.ip:22067 (Relay (Client))
[SOMEID] 01:49:21 INFO: Device SOME-OTHER-IDOF-SOME-OTHER-DEVICE client is "syncthing v0.14.6" named "ComputerName"
[SOMEID] 01:50:51 INFO: Connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE closed: reading length: EOF
[SOMEID] 01:59:39 INFO: Established secure connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE at some.ip:35804-relay.ip:22067 (Relay (Client))
[SOMEID] 01:59:39 INFO: Device SOME-OTHER-IDOF-SOME-OTHER-DEVICE client is "syncthing v0.14.6" named "ComputerName"
[SOMEID] 01:59:39 INFO: Connection to SOME-OTHER-IDOF-SOME-OTHER-DEVICE closed: reading length: EOF
</pre>

### Version Information

Syncthing Version: v0.14.6
OS Version: Windows 10 Pro

**Comment by calmh** [comment]
This looks less related to relays than the other device disconnecting you for some reason (paused?).

**Comment by ssg** [comment]
No it's not paused in the given timeframe.

**Comment by AudriusButkevicius** [comment]
What do the logs say from the other side

**Comment by calmh** [comment]
Could also be a crappy, malfunctioning or misconfigured relay of course. However for the logging issue, I feel it's appropriate to do the logging we do. Three lines every couple of minutes to highlight what is apparently an actual problem that should be fixed seems fine to me.
