### ISSUE TITLE
Normal node aware that a folder has been (manually) deleted from the Normal node folder, but Master node not aware. No Out of Sync / Override changes on Master!

### ISSUE THREAD

**Issue by Smallous** [syncthing/syncthing#3588]
Hello,

**Scenario**,

**Host PC**
Folder set to Master, No File Versioning, Compression off.
**Destination PC**
Folder set to Normal, No File Versioning, Compression off.
**Other**
Both PCs are connected successfully over LAN and have been syncing OK. Both PCs have remained successfully connected throughout testing. 

**Test 1**
1. Manually added an additional folder (via Explorer) in the Destination PCs backup folder.
2. This was detected on the Host PC and the changes were then manually overridden via the Host PCs GUI.
3. This is the expected behaviour.

**Test 2**
1. Manually deleted one of the folders (via Explorer) in the Destination PCs backup folder (note the .stfolder file was not deleted).
2. The Destination PC GUI reported that the Remote Device (the Host) was Syncing 95%. All other status on both PCs reported as Up To Date. The deleted folder on the Destination PC has not been re-synced.
3. The .exe on the Destination PC was restarted. The Destination PC GUI reported that the Remote Device (the Host) was Syncing 95%. All other status on both PCs reported as Up To Date. The deleted folder on the Destination PC has not been re-synced.
4. The .exe on the Host PC was restarted. All status on both PCs reported as Up To Date. The deleted folder on the Destination PC has not been re-synced.
5. Both PCs were re-booted and the .exe restarted. The Destination PC GUI reported that the Remote Device (the Host) was Syncing 95% (and has remained 95%). All other status on both PCs reported as Up To Date. The deleted folder on the Destination PC has not been re-synced.

**What I expected to happen**
The manually deleted folder on the Destination PC should have been re-synced from the Host PC as the Host PC has the Master folder.  

### Version Information
Syncthing Version: v0.14.6, Windows (64 bit) 
OS Version: Windows 10 Home 64bit.

**Comment by wweich** [comment]
Did you actually hit "Override changes" on the master node, after deleting the folder on the other node? For your first test you wrote that you did it, but for the second you did not.
95% is used if the only thing left are deletes, so this is expected (if you did not hit "Override changes").

**Comment by Smallous** [comment]
wweich, 

Thank you for your reply, to clarify,

1. After deleting the folder on the Normal node no "Out of Sync" message has been received on the Master node, so I have not had the option to "Override changes".
2. The Master node is reporting "Up to Date" for both the Folders & Remote Devices.
3. The only indication that there is a discrepancy is that the Normal node is still displaying  "Syncing (95%)" for the Remote (Master) Device. I have re-checked that the deleted folder is still missing on the Normal mode.
4. It seems to be that the Normal node is aware that a folder has be deleted, but the Master node is not aware.

**Comment by Smallous** [comment]
Hello,

In addition to the above:

1. After 2 hours, several new files were manually added to the Master node folder.
2. Folders & Remote Devices were Syncing & updating for both nodes.
3. Eventually the Normal node reported that the Remote (Master) Device was Syncing 95% (and has remained 95%). All other status on both nodes reported as Up To Date. The deleted folder on the Normal node has not been re-synced.

If I understand Syncthing correctly the above would appear to be a bug.

**Comment by wweich** [comment]
The discovery server are public ([see the code](https://github.com/syncthing/syncthing/blob/7fb53ec9544b73f1f7567fbe1f3cdf3f381600f6/lib/config/config.go#L44)), so no worries :)

The logs don't show anything relevant to your problem.

@calmh I think this could be a side effect of the recent changes how the puller handles deletes.

_Please use code blocks for your log excerpts: https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks_

**Comment by calmh** [comment]
Ah, could be
