### ISSUE TITLE
Failed to discover gateway no gateway found

### ISSUE THREAD

**Issue by lugrinder** [syncthing/syncthing#3589]
I'm runing two syncthing intances in the same network, one in a Windows 10 machine and another in a RPi2, both with the same 0.14.6 version. The RPi2 works fine (at the moment), but the Windows machine previously worked with the "same conditions" (consciously I've not changed anyting) but now is not able to find the router gateway (log attached). I've restarted all devices in my network (from the computer to the router) with the same results. I've disabled Windows 10 firewall and my antivirus/firewall with the same results (previously works fine without disabling firewall). RPi2 opens NAT in the router without any problem and Windows machine in the past too, but not now.

Log file with **nat**, **pmp** and **upnp** debug enabled:
[syncthing.txt](https://github.com/syncthing/syncthing/files/467116/syncthing.txt)

### Version Information

Syncthing Version: v0.14.6
OS Version: Windows 10 (64 bit)

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
