### ISSUE TITLE
Incorrect (with recommended) translation

### ISSUE THREAD

**Issue by lugrinder** [syncthing/syncthing#3590]
Please, for Spanish of Spain (es_ES) translations, refer to 'items' as 'elementos' and 'item' as 'elemento'.

[`"The following items could not be synchronized.": "Los siguientes elementos no pueden ser sincronizados."`](https://github.com/syncthing/syncthing/blob/7fb53ec9544b73f1f7567fbe1f3cdf3f381600f6/gui/default/assets/lang/lang-es-ES.json#L210)

 
### Version Information

Syncthing Version: v0.4.16
OS Version: Windows 10 (64 bit)

**Comment by uok** [comment]
please close this issue and register at [transifex](https://www.transifex.com/syncthing/syncthing/) to help with translations

**Comment by wweich** [comment]
https://www.transifex.com/syncthing/syncthing/
