### ISSUE TITLE
https://forum.syncthing.net -> SEC_ERROR_OCSP_SERVER_ERROR

### ISSUE THREAD

**Issue by jedie** [syncthing/syncthing#3593]
Can't open the forum with Firefox. Get the error:

> An error occurred during a connection to forum.syncthing.net. The OCSP server experienced an internal error. Error code: SEC_ERROR_OCSP_SERVER_ERROR

**Comment by wweich** [comment]
That has nothing to do with the Syncthing forum server (i think).
As the error states, the [OCSP](https://de.wikipedia.org/wiki/Online_Certificate_Status_Protocol) server, which is used by Firefox, has an error.
I can visit the forum in Firefox without problems.

**Comment by jedie** [comment]
Yes, not it works.
