### ISSUE TITLE
stdiscosrv: Doesn't build on Solaris

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3595]
81d19a00aa2b9afe9327fb8a6cfe4850908badca broke the Solaris build. Not even I run it there anymore so I doubt anyone cares, but filing it anyway for completeness.

**Comment by john-tho** [comment]
Hi,

With this patch for vendor/github.com/edsrzf/mmap-go
https://github.com/john-tho/mmap-go/commit/f91a7ed232dfa05af88d3b09937b3709f7b6fa43
and fresh vendor/golang.org/x/sys/unix/
https://github.com/golang/sys/commit/b8ca6dd53df6c69d408877591c00f9ff76e8df88

I was able to build stdiscosrv on SmartOS

I have no idea how valid my changes to mmap-go are though.

**Comment by calmh** [comment]
@john-tho can you try upstreaming your changes to mmap-go?

**Comment by john-tho** [comment]
Okay, see:
https://github.com/edsrzf/mmap-go/pull/15
