### ISSUE TITLE
Syncthing should split static and runtime configurations

### ISSUE THREAD

**Issue by L-P** [syncthing/syncthing#3598]
Hi,

Syncthing is currently a bit tricky to deploy in a stateless manner (ie. using Ansible) because its "static" configuration (`/configuration/{options,gui}`) is in the same file as its "runtime" configuration (`/configuration/{device,folder}`).

The dynamic nature of the folders/devices configuration makes it complicated to handle, you need to regularly ensure you have the latest version in your playbook.
If you forget to fetch the configuration before running Ansible, it will _erase_ device associations and folder configurations. This is quite an annoying behavior.  
If you automate fetching the latest `config.xml` you then need to rewrite the options/gui part of it; it forces you to use regexes to parse and edit the config, which is b͏̗a̻̕d̬͉̗͓̞̀.

Were the `config.xml` file split into an additional `devices_and_folders.xml` you could safely ensure you have the configuration you want and handle changes to the devices/folders automatically.  
The point here is having a way to fully restore a Syncthing instance in case of a catastrophic hardware failure.

A complementary setting to have the GUI in read-only mode could also be a great addition for security and ease of deployment, but it's another idea for another issue.

**Comment by calmh** [comment]
I'm not sure what criteria exactly you use to separate "static" and "runtime" here?

**Comment by Ferroin** [comment]
I think I can kind of clarify.

In Syncthing's config, there are a number of things that are reasonably expected to not change except maybe once during setup and likely be the same between all devices.  Examples include things like the GUI access settings, and a lot of the stuff under the options tag (local discovery, relay usage, etc). These are what I believe @L-P is referring to as static config.

In contrast, in the same file, there are a number of things that can be expected to change somewhat dynamically at runtime and be relatively unique to the particular device, namely the folders and devices.  This would be what is being referred to as dynamic config.

Having the two in the same config file makes automated deployment of Syncthing and synchronization of the static options between devices in a network more difficult.

**Comment by AudriusButkevicius** [comment]
I think you are using the wrong tools for the job (that involves regexp parsing rather than altering the xml tree), and make mistakes along the way (forget to provide UI options) and are trying to blame syncthing for it. All configuration is dynamic by definition as it's configurable, so your argument only makes sense in your own usecase. I don't want people asking for a separate file for the password only as that's the only thing that is dynamic in their usecase.

I say we close this.

**Comment by Ferroin** [comment]
@AudriusButkevicius OK, find a deployment orchestration tool like Ansible then that allows for direct manipulation of XML trees in config files.  Manipulating the config is not what he wants (I think), but is what he has to do because all the config ended up in one file despite there being a logical and functional split between devices/folders and the rest of the config.

**Comment by AudriusButkevicius** [comment]
In my case the folders and devices are static. I create them one, share them once, end of story. Just as static as any other setting. Let's drop the biasness of the specific usecase and think on the larger scale. I think 99% of users will be worse off with two configs.

**Comment by AudriusButkevicius** [comment]
I am sorry but the fact that ansible and other tools are unable to alter xml correctly, is not really syncthings problem. I suggest you raise a ticket with ansible instead.

**Comment by L-P** [comment]
1. options and gui are informations about how the node operates, it's
   "low-level" stuff you set once during setup. This is traditionnaly what you
   want to set in stone in `/etc` and manage via Puppet/Ansible/Whatever
   This is the sysop job.

2. devices and folders are about what the node does and are set by the user,
   this is what we usually see in `/var` and belongs in backups rather than
   a configuration management tool because it is supposed to change often.

The issue here is not with Ansible not handling XML right now, it's about
working on a "live" file and having to transfer the configuration
back-and-forth between the managed node and the manager.

I can't help feeling that having those two different things in the same file is
not the friendliest thing for admins.  
Having a single file is still the way to go for simplicity, and I value that.

I solved this on my end so this is not a feature request but something I wanted
to discuss.

**Comment by AudriusButkevicius** [comment]
I think you are going a step too far. Syncthing is for people and is to be managed by people, not by teams, sysops or anisibles. I am fine that you have to pay extra to get it done, as all in all, you are the non-standard case.

This whole argument about transfering stuff is somewhat moot, as you'll have to transfer some file anyway, it doesn't matter if its a few hundered characters longer as it contains the UI stuff.

Again and the friendlyness argument is relative to the individual, as I prefer a clear picture of everything in a single file.

Therefore I think the suggestion is biast to the usecase, which is not a common one, and probably annoy the majority and require substantial effort from the community to be even adapted and not break older tools that rely on the current format.

**Comment by L-P** [comment]
I'm fine with this.  
(And more than fine with not breaking BC.)

But I don't think I'm going a step too far. Syncthing may not be for admins and
teams right now but good tools are always hacked and repurposed, and I think
that Syncthing is a _great_ tool and that we haven't seen all its uses yet.

Having a one-click install for the user _and_ a cleaner install process for
admins would be a plus.

I'll let you decide if you want to close this.

**Comment by calmh** [comment]
I think the discussion is valid, but as pointed out I think the distinction between what you think is static (same for every device) vs dynamic will differ. I can understand the use case for mass deploying syncthing to a bunch of machines using ansible (even though that's not our target user). But I can equally well see that in many such cases, the folder and device configuration will be identical for each device in the cluster (what you think of as dynamic or runtime config), while API key and credentials might differ for each device (your "static" config). As such I don't think this it's sound in principle to do the separation you ask for.

Even so, (our, limited) XML is fairly simply parsed even by regexp and can be massaged to suit in either case.

So yes, I don't think we should do this in the absence of some obvious philosophical principle to separate the two kinds of configuration.

(There is already a sort of separation of this kind, in that the local device ID is determined only by the certificate files and not the config.)
