### ISSUE TITLE
gui: Percentage can still get infinitely large in some situations with deletes

### ISSUE THREAD

**Issue by skylarmt** [syncthing/syncthing#3600]
I decided I didn't need ~5GB of stuff on my desktop, so I deleted some of it while Syncthing was uploading to a remote backup server.

![This is what I saw on the remote's Syncthing GUI.](https://cloud.githubusercontent.com/assets/6668965/18539881/e218418e-7ad7-11e6-9df9-d6bbeb237e93.png)

It got over 830%, and refreshing didn't fix.  It's done syncing now, and is back to normal.  Usability doesn't seem to be impacted, except for the horizontal scrollbar.

Viewing on Firefox 48.0 on Linux Mint 17.3 (Ubuntu 14.04).  Remote server running Ubuntu 16.04.1.

**Comment by calmh** [comment]
Actually calculating a percentage correctly seems to be one of those unsolved problems in computer science... At least by this bunch of programmers. :/

**Comment by skylarmt** [comment]
if (percentsynced > 100) {
      percentsynced = 100;
  }

**Comment by wweich** [comment]
Then it would show "up to date" even though it still has much to do.

**Comment by AudriusButkevicius** [comment]
Isn't this a duplicate?

**Comment by calmh** [comment]
Well there's #2652 but I think the others were closed as I fixed them. "Fixed" them, apparently.

**Comment by calmh** [comment]
We'll let 2652 represent this.
