### ISSUE TITLE
"Out of Sync" on only one computer, files appeared to be in sync

### ISSUE THREAD

**Issue by dwrz** [syncthing/syncthing#3601]
Issue: I am getting an Out of Sync warning despite the fact that it seems both folders are fully synced.

Background:

I am trying to sync a folder on my desktop with one on my netbook. 

The folder is ~700 MiB, 2500 files, 500 sub-folders. 

On my desktop, the folder is located something like:
`/media/USER/EXTERNAL-DRIVE/FOLDER`

On my netbook, the folder is located as:
`/home/USER/FOLDER`

Prior to the sync, the two paths shared a subfolder (but no other contents), which was synced with git. Git folders were removed prior to sync.

Desktop: `/media/USER/EXTERNAL-DRIVE/FOLDER/SUBFOLDER`
Netbook: `/home/USER/FOLDER/SUBFOLDER`

Among other things this folder contained my emacs config and some pdf and plain text files. These are the files that seem to be failing.

What I should have done: (1) had coffee, (2) deleted the subfolder on my netbook, and allowed the sync to come in from the desktop.

What I did: 
I set-up sync for FOLDER on both my desktop and my netbook, with the SUBFOLDER still in place on both systems.

What happened: 

I got a few sync-conflicts, which were pretty easy to fix. 

On my netbook, the GUI says "Up to Date".

On my desktop, the GUI says "Out of Sync".

33 files are listed as failing, with the error "operation not permitted".

I have not checked all of the files, but I can confirm the vast majority seem to be synced on both computers, with no conflicts.

What I expected to happen (and would like to have happen now):

"Up to Date" on both systems.

### Version Information

Syncthing Version: v0.14.6
OS Version: Kubuntu 16.04 / Lubuntu 16.04
Browser Version: Chromium 52.0.2743.116 / Qupzilla 1.8.9

**Comment by wweich** [comment]
Please use the [forums ](https://forum.syncthing.net/)for support (as stated in the issue template).

---

Nonetheless, if the folder on both devices show the same number of items and size, try to shutdown both (so both are down at the same time) and then start both up again.
