### ISSUE TITLE
Feature Request: Option to Stop Deletion

### ISSUE THREAD

**Issue by c0fe** [syncthing/syncthing#3602]
I would like to propose a feature, in which specific files and folders can be selected that are protected against accidental deletion. Meaning, that a file would be synced to a specific node but it doesn't deleted on that particular node even if it is deleted on the others.

**Comment by canton7** [comment]
There's already an option for ignoring deletions to all files and folders within a particular folder.

**Comment by calmh** [comment]
https://docs.syncthing.net/advanced/folder-ignoredelete.html
