### ISSUE TITLE
GUI accessibility : polish Folder & Device creation popups

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#3604]
1 - what happened,
Just following the Add new (Folder/Device), the focus is not in the first field.
- what I expected to happen instead.
  Get the focus in first field.

2 - what happened,
Parsing the fields in Add new folder popup with the keyboard Tab key, the focus won't hoover the Advanced settings section, preventing selection of items like Folder or Versionning types.
- what I expected to happen instead:
  Be able to reveal advanced settings with the keyboard.

3 - Also, maybe more difficult or not feasible, the "Ignore patterns" button doesn't show in folder creation popup. Because the creation processes was not yet ran to its end. One way could be: Save Folder creation, then popup "Do you wan't to add Ignore patterns?" yes|no , only on creation, as the button shows OK on Edit mode.
### Version Information

Syncthing Version: v0.14.6
OS Version: Ubuntu 14.04.5
Browser Version: FF38/48

**Comment by AudriusButkevicius** [comment]
Unless you want to provide the changes yourself, I feel this will go into the "nobody cares enough about this" pile.

**Comment by bugith** [comment]
Nice ;) I was writing a tuto for friends, digressing how to throw the mice away with help of [shift] tab, space, arrows & Enter, when I hit the 2nd "What happened" in this issue report (unselectable Advanced settings section), which is really the one that drove me whistling the "no-mouse lesson pause", writing/posting this issue report, and linking it in my tuto. No matter : as the persian carpets weavers say when one points them a small flaw, "it's intended, only Allah do perfect things" (and I think in myself, "a chance for Allah they don't forget to introduce the flaw"). Bye Aud.

**Comment by calmh** [comment]
Someone apparently cares enough to write this up, and it sounds valid to me, so saying noone cares is unnecessary.

The third point also has the extra merit that if you don't want the files scanned at all, creating the ignore patterns at folder creation time is necessary. I don't think we should prompt for them, but it would be nice to have the editor. I understand there is a trickiness here as the folder to save the patterns in may not exist yet.

**Comment by calmh** [comment]
I broke that out into #3608, keeping this for the general polish of the first two points.

**Comment by MikeLund** [comment]
Something maybe to add onto this, is there some sort of a way to get the "glow" around elements when using the dark/black theme?

My mouse stopped working and I wanted to open up folder info, and I had to just guess which element I was on when pressing the tab key. On the default theme it gets the glow around it, which works good in that way.

**Comment by bugith** [comment]
Since editing ignores at folder creation time is solved by #3608 and edit folders dialog is now tabbed, I believe this bug should be reworded, or even closed. Against what I first proposed, it appears to me that it may not be such a bad thing remembering the latest tab/field within one syncthing GUI session, e.g. we want to change same setting on different folders. For casual adjustments, ST can't guess what we want to do so opening on first tab (new session) or previous one is not a real issue (only an arbitrary timer (15mn?) would reset behaviour to "open first tab").
About my point 2, it is solved by the bugfix above, but related @MikeLund comment is also relevant to not only black theme but also to dark one.

Take care of you guys, thanks once more so much for that such great soft.

**Comment by tomasz1986** [comment]
I have just tried to create both a device and a folder using only a keyboard, and all the interactive elements seem to be perfectly focusable. As such, I would say that the issue has been resolved, kind of naturally with time following various other changes to the GUI.

I think that it can be closed, right?
