### ISSUE TITLE
German vowels in .stignore not possible (ü ä ö)

### ISSUE THREAD

**Issue by theincogtion** [syncthing/syncthing#3607]
Y7IWD] 07:34:04 INFO: syncthing v0.14.6 "Dysprosium Dragonfly" (go1.7 windows-amd64) jenkins@build.syncthing.net 2016-09-04 21:06:30 UTC

[Y7IWD] 09:22:57 WARNING: Loading ignores: include of ".stsurfaceignore": invalid pattern "m?ndliche noten 2015-16" in ignore file (could not read rune)

[Screenshot](http://abload.de/image.php?img=2016-09-1709_23_5086s3x.png)

the folder is named "mündliche noten 2015-16" and if I try to ignore it I get an error.

Even replacing the ü with an ? in the .stignore was not successfull. I didn't get any error but the folder is synced (It shouldn't)

**Comment by wweich** [comment]
Which encoding did you use for the `.stsurfaceignore` file?

**Comment by theincogtion** [comment]
UTF-8 without BOM

**Comment by wweich** [comment]
Hmm. I cannot repro this problem.

I just tested this (on Linux).
Added `mündliche noten 2015-16` to my `.stglobalignore` file and got no error in the gui and nothing in the logs.
Then created the files `mündliche noten 2015-16` and `mündliche noten 2015-16-1`.
As expected, only `mündliche noten 2015-16-1` got synced.

_My `.stglobalignore` file is utf-8_

**Comment by calmh** [comment]
Inxded "could not read rune" sounds like it is not in utf8 encoding.
