### ISSUE TITLE
Feature request: Command-line options to enable "Use HTTPS for GUI" and to set the SSL certificate

### ISSUE THREAD

**Issue by jokogr** [syncthing/syncthing#3612]
In the current version of Syncthing, one can enable HTTPS via the web interface and the SSL certificate has to be placed at specific paths (AFAIK, it has to be `https-cert.pem` and `https-key.pem` at the configuration directory).

I would propose to expose those two options in the command-line interface, so that the service could start without the need of doing the additional configuration.

**Comment by AudriusButkevicius** [comment]
You can enable https via the -gui-address, and you just need to place certificates in the right place.
