### ISSUE TITLE
v0.14.7 crashes on Arm64

### ISSUE THREAD

**Issue by rkburnside** [syncthing/syncthing#3613]
- what happened: Syncthing automatically updated from 14.6 to 14.7 on an Arm64 SOC and now syncthing won't start/crashes whenever I try to start version 14.7 (see log file below).

- what you expected to happen instead: I expected this update to start normally like all the other versions

- any steps to reproduce the problem: I downgraded to 14.6 and everything runs normally. I updated to 14.7 through the GUI and the same issue happens (see log file below). I rebooted and downgraded again to 14.6 and everything runs normally. I manually installed 14.7 from CLI and the same issue happens again. I have once again downgraded to 14.6 and will be running 14.6 until the issue can be resolved. Thanks for your help.

### Version Information
---------------------------

Syncthing Version: v0.14.7
OS Version: 
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Board: Odroid C2
Processor: Arm64 -> Amlogic ARM® Cortex®-A53(ARMv8) 1.5Ghz quad core CPUs

Browser Version: n/a

Log Output
---------------------------
```
root@omv-c2: syncthing
[monitor] 07:13:16 INFO: Starting syncthing
SIGILL: illegal instruction
PC=0x368ebc m=0

goroutine 1 [running, locked to thread]:
github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd.blockArm(0x442003bbb8, 0x8, 0x8, 0x4420130000, 0x20000, 0x20000, 0xbb67ae856a09e667, 0xa54ff53a3c6ef372, 0x9b05688c510e527f, 0x5be0cd191f83d9ab, ...)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd/sha256block_arm64.s:59 +0x5c fp=0x442003bb80 sp=0x442003bb80
github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd.blockArmGo(0x442003bd50, 0x4420130000, 0x20000, 0x20000)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd/sha256block_arm64.go:32 +0xd8 fp=0x442003bc20 sp=0x442003bb80
github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd.block(0x442003bd50, 0x4420130000, 0x20000, 0x20000)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd/sha256.go:79 +0x108 fp=0x442003bc60 sp=0x442003bc20
github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd.(*digest).Write(0x442003bd50, 0x4420130000, 0x20000, 0x20000, 0x20000, 0x0, 0x0)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd/sha256.go:125 +0x1b8 fp=0x442003bcf0 sp=0x442003bc60
github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd.Sum256(0x4420130000, 0x20000, 0x20000, 0x0, 0x0, 0x0, 0x0)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd/sha256.go:100 +0xc4 fp=0x442003bdc0 sp=0x442003bcf0
github.com/syncthing/syncthing/lib/protocol.init()
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/protocol/bep_extensions.go:25 +0xadc fp=0x442003be40 sp=0x442003bdc0
github.com/syncthing/syncthing/lib/config.init()
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/config/wrapper.go:360 +0x88 fp=0x442003beb0 sp=0x442003be40
main.init()
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/verboseservice.go:187 +0xb0 fp=0x442003bf40 sp=0x442003beb0
runtime.main()
	/usr/local/go/src/runtime/proc.go:172 +0x280 fp=0x442003bf90 sp=0x442003bf40
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:983 +0x4 fp=0x442003bf90 sp=0x442003bf90

r0      0x442003bbb8
r1      0x4420130040
r2      0x1ffc0
r3      0x881100
r4      0x8
r5      0x8
r6      0x442003bbb8
r7      0x4420130000
r8      0x10e
r9      0x10
r10     0x8776e0
r11     0x0
r12     0x8
r13     0x0
r14     0x0
r15     0x10
r16     0x442003bdb8
r17     0x87ae78
r18     0x0
r19     0x0
r20     0x0
r21     0x0
r22     0x0
r23     0x0
r24     0x0
r25     0x0
r26     0x87ad50
r27     0xb2dd19
r28     0x44200001a0
r29     0x0
lr      0x3684c8
sp      0x442003bb80
pc      0x368ebc
fault   0x0
```

**Comment by AudriusButkevicius** [comment]
This is us moving to the new faster hashing library, stick with an older version on that device for now.

**Comment by calmh** [comment]
Yeah, unfortunately I'm fairly unsurprised by this. :/

**Comment by CoupeWare** [comment]
It killed 4 of my systems (Odroid-C2) so I was very surprised. I have been looking forward to the hashing improvements so it's worth a little pain.

I rolled back to 0.14.6 by copying syncthing.old and turned of auto upgrades (<autoUpgradeIntervalH>0</autoUpgradeIntervalH> for anyone editing their config.xml).

Looking forward to 0.14.8.

**Comment by calmh** [comment]
Filed upstream. Luckily this should be fairly limited impact as we've currently got around 0.05% of the population on arm64, and hopefully not all of those on this specific CPU.

**Comment by aviau** [comment]
I'll upload 14.7 on Debian with ```crypto/sha256``` instead.

**Comment by calmh** [comment]
Be sure to note that in your release notes, as you're removing an improvement for the vast majority that is mentioned our release notes.

**Comment by Zeitwaechter** [comment]
I'm also having those troubles on a Odroid C2 (v0.14.10).
Running Arch Linux (Linux hostname 3.14.79-11-ARCH #1 SMP PREEMPT Thu Nov 3 19:23:19 MDT 2016 aarch64 GNU/Linux)
As a workaround you need to start it manually by running the `syncthing` command as the specific user you want it to run with.
Fails hard via `systemctl` and won't regenerate.

The following will happen but it runs anyways afterwards:
```
SIGILL: illegal instruction
[monitor] 11:59:22 WARNING: 
*******************************************************************************
* Crash due to illegal instruction detected. This is most likely due to a CPU *
* incompatibility with the high performance hashing package. Switching to the *
* standard hashing package instead. Please report this issue at:              *
*                                                                             *
*   https://github.com/syncthing/syncthing/issues                             *
*                                                                             *
* Include the details of your CPU.                                            *
*******************************************************************************

[monitor] 11:59:22 INFO: Syncthing exited: exit status 2
[monitor] 11:59:23 INFO: Starting syncthing
[AZEB3] 11:59:23 INFO: syncthing v0.14.10 "Dysprosium Dragonfly" (go1.7.3 linux-arm64) builduser@leming 2016-11-02 01:30:49 UTC
```
