### ISSUE TITLE
sycnthing deleting random files and directories since 0.14.7

### ISSUE THREAD

**Issue by onodera-punpun** [syncthing/syncthing#3615]
See title, for some reason it removed all my wallpapers in `rootshuf/dark`, all x11 configs in `x11`, and my xdg config `xdg`, oh, and also the directory where I save my syncthing dotfiles... Luckily I made a backup yesterday, so I tried copying the files back in, but syncthing just deleted these files *again*. I'm not using syncthing with another person, just me and my laptop & vps.

Syncthing Version: 0.14.7
OS Version: CRUX Linux

**Comment by AudriusButkevicius** [comment]
Please use the forum for support requests.
Nothing has changed in the last version that would have caused this.
You are probably having some home directory encryption or mount issues that is causing this.
