### ISSUE TITLE
Disable GUI and make API available on unix socket

### ISSUE THREAD

**Issue by spectras** [syncthing/syncthing#3616]
Context: running syncthing as a service on a headless server.

The GUI should not be started as it is not used at all. Syncthing is controlled through `systemd` and its configuration is managed with `ansible`. Every user account has its own instance of syncthing handling its files. All was great until I wanted to enable syncthing-inotify.

```
Sep 21 06:36:24 staging syncthing-inotify[529]: [WARNING] Cannot connect to Syncthing: Get https://localhost:8384/rest/404: dial tcp [::1]:8384: getsockopt: connection refused
```

It turns out services communicate with syncthing using the same channel as user's browsers. This means I cannot disable the GUI or I cannot enable any additional tool that talks to syncthing. I thought no problem, let's enable the GUI and mitigate the issue by only listening on a unix socket, which I can restrict access to through filesystem permissions. Alas, the GUI is hardcoded to use a tcp port.

Thus the feature request:
1. allow dissociating API and GUI channels. Or at the very least start a stripped down version with just the API available.
2. allow `unix://`-type address for GUI.

I believe those would be great steps towards allowing syncthing to work flawlessly in a traditional daemon style.

**Comment by AudriusButkevicius** [comment]
Or set up authentication on the UI and use authenticated channels via the tools via loopback adapter.

**Comment by AudriusButkevicius** [comment]
Furthermore, none of the tools support access via unix socket.

**Comment by AudriusButkevicius** [comment]
I am honestly failing to see the benefit of a unix socket versus a normal socket when authentication is used.

**Comment by calmh** [comment]
I sort of like the idea of unix sockets, except they don't exist on windows (something similar does) and no browsers speak it. If it were contributed and clean I'd probably accept it anyway, as a way for tools to talk to the API without exposing it to all local users.

**Comment by Ferroin** [comment]
That's easy, a UNIX socket doesn't require authentication (because you can set permissions on the socket itself), and it's more efficient than running over the loopback interface (because you don't need to marshal all the ancillary data for TCP and IP).  It's also a lot easier to audit that a UNIX socket is secure, because it's impossible to have one exposed to the network.  Additionally, not requiring in-band authentication simplifies writing alternative front-ends.  In the OP's case, there's also the issue of port contention, which is pretty much non-existent in the case of a UNIX socket.

As far as support for the tools, that should be pretty trivial to add (literally the only difference should be the address used, provided your using a library that doesn't depend on running over a specific connection type).

**Comment by spectras** [comment]
Indeed, there are multiple points that unix sockets improve over loopback interface.
 * security is handled at the OS level. Socket is a simple file with regular file permissions. TLS handshake and application-level authentication can be removed completely.
 * setup and administration are much simpler. The socket can just be put in syncthing's directory next to its other files, this will make it available to all processes of the user and nobody else. No api key to pass around, no ssl certificates to mess with, no port conflict.
 * no firewall rules to setup as unix socket is not exposed on the network. 
 * much simpler codepaths (no encryption, no authentication) means less attack surface.
 * As a side benefit, performance is better as data does not go through the tcp/ip stack and overall data flow involves less context switches. Numbers vary but figures of ~30% more throughput [come up](http://zaiste.net/2015/05/postgresql_unix_socket_vs_tcpip_loopback/) regularly.

The main drawback is browsers cannot access it. That's why it's not good as a default on end-user's machines.
On the other hand, it's irrelevant when syncthing is deployed on a server. Even if the gui was to be made accessible, the typical production path in this case would be to go 3-tier, with a webserver such as nginx or apache working as a frontend to syncthing gui. Those [can use unix sockets](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass) to communicate with backends.

**Comment by spectras** [comment]
Example of problematic scenario on multi-user environment with loopback. Let's say I have two users.
  - Let's say User A is assigned TCP port 10001 for his gui and User B is assigned TCP port 10002 for his gui.
  - Now, User A simply waits for User B to turn his syncthing off. For instance when he logs off or at next reboot.
  - User A starts his own customized copy of syncthing on User B's port, 10002.
  - User A waits for User B to be back.
  - User B fires his browser and opens his GUI bookmark (either he forgot to start his own syncthing or does not notice his own syncthing fails to load due to busy port).
  - User A collects User B's credentials with his customized copy of syncthing.

Syncthing is vulnerable to this attack right now, as API key is plain text and authentication uses the Basic scheme. And the GUI's TLS certificate cannot be authenticated by the browser as it is self-signed.
Sure, it can be worked around by manually installing syncthing GUI's certificates into every users' browsers on every one of their devices, but configuration just became a nightmare.

**Comment by xduugu** [comment]
I have the addition of unix sockets also on my list. Docker has a library ([go-connections](https://github.com/docker/go-connections)) that uses unix sockets and for windows named pipes.

The biggest issue is the WebUI, which will not work with sockets. It could either be converted to an electron app or temporarily provide access to the unix socket over TCP. Of course this tcp socket needs to be secured by the WebUI.

**Comment by kozec** [comment]
> Furthermore, none of the tools support access via unix socket.

Adding such support is pretty easy, I already tested that on my other project :)

**Comment by conrad-heimbold** [comment]
I can't find this issue in bountysource, so I can't put a bounty in it. Am I stupid or could anybody tell me where to find it? Thanks a lot!

**Comment by uok** [comment]
Just past the url of the page into search field
