### ISSUE TITLE
Apt repository installation instruction missing "-k" parameter 

### ISSUE THREAD

**Issue by mrozo** [syncthing/syncthing#3621]
Hi, while installing syncthing on odroid c1+ with debian minimal image i had to change the command from http://apt.syncthing.net/

from
curl -s https://syncthing.net/release-key.txt | sudo apt-key add -
to
curl -s -k https://syncthing.net/release-key.txt | sudo apt-key add -

Note the -k parameter. It may be related to the odroid minimal debian image lacking a proper certificates.

**Comment by calmh** [comment]
Yes. The site has a proper certificate and that should not be needed. I don't want to recommend people disbale certificate checks.
