### ISSUE TITLE
Rename "Add Remote Device" to "Connect to Remote Device"?

### ISSUE THREAD

**Issue by Nutomic** [syncthing/syncthing#3622]
I think it would be clearer if the "Add Remote Device" button in the devices section was renamed to "Connect to Remote Device".

**Comment by caluc** [comment]
Agreed, it's clearer to me too.

**Comment by calmh** [comment]
Why, when I just "connected a remote device", does it appears as "disconnected" in the UI?

**Comment by AudriusButkevicius** [comment]
Exactly.

**Comment by Nutomic** [comment]
Good point, I hadn't thought of that.

**Comment by MikeLund** [comment]
If you really wanted something different "Link Remote Device" sounds okay to me. But the current one makes sense already to me.

**Comment by bugith** [comment]
Even more simple, "Add a device" : it's like a kind a addresses book. We don't care the device is remote or local: It's just ... another

**Comment by AudriusButkevicius** [comment]
Sadly, I think we close this, this whole substitution of 'Add' with 'Connect' doesn't actually explain anything better.

**Comment by Nutomic** [comment]
Yeah that's fine by me. Just wanted to bring up the idea :)
