### ISSUE TITLE
Local state should match global when in sync

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3623]
This is a puzzling summary:

<img width="565" alt="screen shot 2016-09-25 at 20 06 12" src="https://cloud.githubusercontent.com/assets/125426/18817213/9ad505e6-835b-11e6-9309-4c136aa3a9c5.png">

I suspect deletes accounted in one but not the other, or ignores.

**Comment by calmh** [comment]
Right, global size does not take ignores into account. We used to filter out ignored files when receiving indexes, so then it didn't matter. Now it does... Document/clarify/fix?

**Comment by canton7** [comment]
So global does not include ignored files, but local does include ignored files? My (perhaps naive) assumption would be that the local state would not include ignored files - I ignored them so that they don't become part of the local state...

**Comment by scienmind** [comment]
I think calmh meant by " global size does not take ignores into account" - that global count the ignored items as legitimate (hence the bigger number), while local is "ignores aware" and knows to subtract/not count them

**Comment by calmh** [comment]
Yes, the opposite. See screenshot. Lots more stuff in global than local - stuff that is ignored by the device where I took the screenshot.

**Comment by AudriusButkevicius** [comment]
We could provide 2 numbers or a tooltip witg tge secind number for the global state saying "after ignores: xyz".


Also, I am suspicious sizes match.

**Comment by calmh** [comment]
Mmm. The stuff I'm ignoring is mac resource fork metadata crappery which are thousands of super tiny files, so the size difference just isn't visible.
