### ISSUE TITLE
cmd/strelaypoolsrv: Deal with statusAddr having more than just a port

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#3625]
GET http://23.94.50.9710.250.0.6:22070/status net::ERR_NAME_NOT_RESOLVED
GET http://167.88.120.159thespecter.net:22070/status net::ERR_NAME_NOT_RESOLVED

https://github.com/syncthing/syncthing/blob/master/cmd/strelaypoolsrv/gui/index.html#L328

**Comment by calmh** [comment]
I think we should always talk to the same address as the relay, and strip away or reject the rest of the stuff. We don't want people to be able to ask the pool server to make http requests to arbitrary places.

**Comment by smeggysmeg** [comment]
One of these was my relay, which at the time was improperly configured. It has since been corrected. I would assume the other is also improperly configured.

**Comment by xordspar0** [comment]
Is this still valid? If so, we might need more information recorded here so someone could pick it up. For one thing, the link to the source code isn't valid anymore (that line is just a closing brace).

**Comment by AudriusButkevicius** [comment]
It's invalid, go code now deals with this.
