### ISSUE TITLE
"folder path missing" after network share is offline for a few minutes

### ISSUE THREAD

**Issue by beatschubser** [syncthing/syncthing#3631]
One of my syncthing-installations has mounted a network share ("Z:\...") under Windows. The machine that hosts this share reboots every night a 4am. After this time the folder won't come back and syncthing says "folder path missing".

Restarting syncthing in the GUI does not help. I need to shut it down and then start it manually. Then the folder is working fine again.

### Version Information

Syncthing Version: v0.14.7
OS Version: Windows 7

**Comment by AudriusButkevicius** [comment]
Please read the issue template. Support is handled on the forums.
