### ISSUE TITLE
License / Question: Syncthing icon in Android icon pack?

### ISSUE THREAD

**Issue by conrad-heimbold** [syncthing/syncthing#3632]
Can I use Syncthing's icon for an icon pack on Android? The icon pack, for which I would like to use the icon (and which I have forked), is https://github.com/1C3/ICEcons/ . 

As far as I know, the Mozilla Public License is quite restrictive concerning icons (e.g. just think at debian's "Iceweasel" as replacement for Firefox). 

I do not want to change the icon very much, but the icon should become white on transparent. 
Of course, my changed icon will be open-sourced as well. 

Thanks for an answer!

**Comment by AudriusButkevicius** [comment]
Use tye forum for questions.

**Comment by calmh** [comment]
@conrad-heimbold yes, go ahead
