### ISSUE TITLE
Error: File name ... is not in UTF8 encoding; skipping.

### ISSUE THREAD

**Issue by dschrempf** [syncthing/syncthing#3635]
Observed behavior: I had some files not encoded with UTF8.  Syncthing complains about those.  So I renamed them.  However, the error is still shown (even after expicit rescan).

Expected behavior: remove error/warning after rename.

BTW, the UTF error does not show the full path but only the last part starting at the folder name.  This may lead to confusion, especially when many folders are synced.

Thanks for this great piece of software :-)!

### Version Information

syncthing v0.14.7 "Dysprosium Dragonfly" (go1.7.1 linux-amd64) builduser@svetlemodry 2016-09-21 18:31:42 UTC

Linux arbeitsbaer 4.7.5-1-ARCH #1 SMP PREEMPT Sat Sep 24 13:04:22 CEST 2016 x86_64 GNU/Linux

Mozilla Firefox 49.0.1

**Comment by calmh** [comment]
`ls | do -t ax1` on those files please

**Comment by canton7** [comment]
I suspect this is the warnings boxes at the top of the screen?

@dschrempf can you provide a screenshot of what you're describing, please?

**Comment by calmh** [comment]
Right, I'm assuming we're talking about the same error popping up again here, not that the old warning doesn't disappear immediately when the file is renamed?

**Comment by canton7** [comment]
My assumption was that the old error remained...

**Comment by calmh** [comment]
The warning is time stamped, like the log entry it is, and has an ok button that dismisses it. If the assumption is that it should disappear on its own then I think that's an odd assumption. :) @dschrempf please clarify

**Comment by dschrempf** [comment]
Thanks for your answers.
- Yes, I meant the warning boxes at the top of the screen.
- Yes, the warning popped up again after rename, rescan and restart of Syncthing (but maybe the old error remained, that I cannot tell).
- I do not assume that the error disappears on its own.  I assumed that it will not show up again after rename, rescan and restart.  However, it disappeared after about another hour.

**Comment by calmh** [comment]
Sounds odd indeed. However I can't reproduce it, please yell if you can.
