### ISSUE TITLE
ARM64 binary: sigill on startup

### ISSUE THREAD

**Issue by oleid** [syncthing/syncthing#3637]
On my odroidc2, the arm64 binary is broken for me after the last update (0.14.7) :

	SIGILL: illegal instruction
	PC=0x368ebc m=0

	goroutine 1 [running, locked to thread]:
	github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd.blockArm(0x4420037bb8, 0x8, 0x8, 0x442010a000, 0x20000, 0x20000, 0xbb67ae856a09e667, 0xa54ff53a3c6ef372, 0x9b05688c510e527f, 0x5be0cd191f83d9ab, ...)
		/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd/sha256block_arm64.s:59 +0x5c fp=0x4420037b80 sp=0x4420037b80
	github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd.blockArmGo(0x4420037d50, 0x442010a000, 0x20000, 0x20000)
		/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd/sha256block_arm64.go:32 +0xd8 fp=0x4420037c20 sp=0x4420037b80
	github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd.block(0x4420037d50, 0x442010a000, 0x20000, 0x20000)
		/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd/sha256.go:79 +0x108 fp=0x4420037c60 sp=0x4420037c20
	github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd.(*digest).Write(0x4420037d50, 0x442010a000, 0x20000, 0x20000, 0x20000, 0x0, 0x0)
		/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd/sha256.go:125 +0x1b8 fp=0x4420037cf0 sp=0x4420037c60
	github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd.Sum256(0x442010a000, 0x20000, 0x20000, 0x0, 0x0, 0x0, 0x0)
		/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/minio/sha256-simd/sha256.go:100 +0xc4 fp=0x4420037dc0 sp=0x4420037cf0
	github.com/syncthing/syncthing/lib/protocol.init()
		/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/protocol/bep_extensions.go:25 +0xadc fp=0x4420037e40 sp=0x4420037dc0
	github.com/syncthing/syncthing/lib/config.init()
		/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/config/wrapper.go:360 +0x88 fp=0x4420037eb0 sp=0x4420037e40
	main.init()
		/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/verboseservice.go:187 +0xb0 fp=0x4420037f40 sp=0x4420037eb0
	runtime.main()
		/usr/local/go/src/runtime/proc.go:172 +0x280 fp=0x4420037f90 sp=0x4420037f40
	runtime.goexit()
		/usr/local/go/src/runtime/asm_arm64.s:983 +0x4 fp=0x4420037f90 sp=0x4420037f90

	r0      0x4420037bb8
	r1      0x442010a040
	r2      0x1ffc0
	r3      0x881100
	r4      0x8
	r5      0x8
	r6      0x4420037bb8
	r7      0x442010a000
	r8      0x11f
	r9      0x10
	r10     0x8776e0
	r11     0x2
	r12     0x8
	r13     0x0
	r14     0x0
	r15     0x10
	r16     0x4420037db8
	r17     0x87ae78
	r18     0x0
	r19     0x0
	r20     0x0
	r21     0x0
	r22     0x0
	r23     0x0
	r24     0x0
	r25     0x0
	r26     0x87ad50
	r27     0xb2dd19
	r28     0x44200001a0
	r29     0x0
	lr      0x3684c8
	sp      0x4420037b80
	pc      0x368ebc
	fault   0x0

# cat /proc/cpuinfo 
	processor	: 0
	BogoMIPS	: 48.00
	Features	: fp asimd evtstrm crc32
	CPU implementer	: 0x41
	CPU architecture: 8
	CPU variant	: 0x0
	CPU part	: 0xd03
	CPU revision	: 4

	processor	: 1
	BogoMIPS	: 48.00
	Features	: fp asimd evtstrm crc32
	CPU implementer	: 0x41
	CPU architecture: 8
	CPU variant	: 0x0
	CPU part	: 0xd03
	CPU revision	: 4

	processor	: 2
	BogoMIPS	: 48.00
	Features	: fp asimd evtstrm crc32
	CPU implementer	: 0x41
	CPU architecture: 8
	CPU variant	: 0x0
	CPU part	: 0xd03
	CPU revision	: 4

	processor	: 3
	BogoMIPS	: 48.00
	Features	: fp asimd evtstrm crc32
	CPU implementer	: 0x41
	CPU architecture: 8
	CPU variant	: 0x0
	CPU part	: 0xd03
	CPU revision	: 4

	Hardware	: ODROID-C2
	Revision	: 020b

# uname -a
	Linux odroidc2 3.14.74-odroidc2 #1 SMP PREEMPT Sun Aug 7 08:59:34 CEST 2016 aarch64 GNU/Linux

# MD5 sums

For reference: 
67a4b255a8160efd5f5753b9f235b42d  broken version
498065c612f6bb688efb15d8ada9546b  last known working version

**Comment by calmh** [comment]
Yep. Try the last dev build: https://build.syncthing.net/job/syncthing/lastStableBuild/artifact/

**Comment by oleid** [comment]
That works - it switches back to fallback mode and then starts up:

   *******************************************************************************
    * Crash due to illegal instruction detected. This is most likely due to a CPU *
    * incompatibility with the high performance hashing package. Switching to the *
    * standard hashing package instead. Please report this issue at:              *
    *                                                                             *
    *   https://github.com/syncthing/syncthing/issues                             *
    *                                                                             *
    * Include the details of your CPU.                                            *

**Comment by calmh** [comment]
Cool. To enforce that permanently, set `STHASHING=standard` before starting up.

**Comment by calmh** [comment]
(Reopen to double check that this is the same CPU we've already filed this for)

**Comment by calmh** [comment]
https://github.com/minio/sha256-simd/issues/6

**Comment by elopio** [comment]
Same thing happens in the dragonboard 410c.
The sigkill and crash message appear, but it starts successfully.

```
elopio@localhost:~$ cat /proc/cpuinfo 
processor       : 0
BogoMIPS        : 38.40
Features        : fp asimd evtstrm crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 0

processor       : 1
BogoMIPS        : 38.40
Features        : fp asimd evtstrm crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 0

processor       : 2
BogoMIPS        : 38.40
Features        : fp asimd evtstrm crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 0

processor       : 3
BogoMIPS        : 38.40
Features        : fp asimd evtstrm crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 0

elopio@localhost:~$ uname -a
Linux localhost.localdomain 4.4.0-1032-snapdragon #36-Ubuntu SMP Wed Oct 19 14:37:43 UTC 2016 aarch64 aarch64 aarch64 GNU/Linux
```
