### ISSUE TITLE
German Localisation - Missing Folder Names

### ISSUE THREAD

**Issue by Dpunkt** [syncthing/syncthing#3638]
When creating a new share, the folowing message appears:
"-PC-- wants to share folder "--Name--" (default).  Add new folder? "
In the German localisation
"--PC--> möchte das Verzeichnis "" (default) teilen.  Neues Verzeichnis hinzufügen? "
One of the most important Information is missing.

**Comment by uok** [comment]
what exactly is missing?

**Comment by Dpunkt** [comment]
Sorry, forget GitHub is using "Markdown", it replaced my tags with nothing

**Comment by uok** [comment]
@calmh I think I found the cause for this: 
in [Transifex](https://www.transifex.com/syncthing/syncthing/translate/#de/gui/39247396?q=wants%20to%20share%20folder)there are too almost similar strings:
No. 248: {{device}} wants to share folder "{{folder**L**abel}}" ({{folder}}).
No. 249: {{device}} wants to share folder "{{folder**l**abel}}" ({{folder}}).
which is the correct one? please delete the other one
