### ISSUE TITLE
[FEATURE REQUEST] Allow relay to be run after a firewall

### ISSUE THREAD

**Issue by adam900710** [syncthing/syncthing#3641]
I tried to run a relay to help the community, while it just fails with the following error message, even port foward is enabled for default relay port.
```
https://relays.syncthing.net/endpoint failed to join due to IP address not matching external address. Aborting
```

While this is quite annoying, and something even impossible for normal user to run relay, as most (if not all) users are behind NAT firewall.
And even for a lot of VPS, they don't assign external IP to VMs, so such requirement is quite annoying.

Thanks

**Comment by GodUseVPN** [comment]
You can start relay server with parameter -ext-address to announce an address differ from listen address. See more settings start relay server with -help parameter.
