### ISSUE TITLE
Feature suggestion: Make share and device list organizable

### ISSUE THREAD

**Issue by seansimonanimation** [syncthing/syncthing#3642]
Would it be possible to make it so that the share page is a little more customizable? Like maybe give us the ability to either arrange the visual structure of the shares on the homepage or just make it look kind of like a customizable virtual AD but with Syncthing shares? It would be nice to, instead of hunting for a particular share out of the massive list of shares I have, to be able to say "Oh, it's dropboxes>Foobar" or something along those lines.

It's not that big a deal, just an organizational nuisance when dealing with a large number of shares (20+) on one device. Thanks!

![untitled](https://cloud.githubusercontent.com/assets/14866679/19017830/233845fe-87ff-11e6-8e55-9a9cf5a68648.png)

**Comment by AudriusButkevicius** [comment]
I think this is a duplicate.

**Comment by AudriusButkevicius** [comment]
Also, they are alphabetically sorted so you already have a way to define the order.

**Comment by calmh** [comment]
I think this is not something we will fix in the close future. The vast majority of users have 10 folders or less, where a tree view is not essential to make sense of the UI.
