### ISSUE TITLE
`Host check error` when connecting from localhost

### ISSUE THREAD

**Issue by zetok** [syncthing/syncthing#3643]
>Syncthing since version 0.14.6 does an extra security check when the GUI/API is bound to localhost - namely that the browser is talking to localhost.

Yes, browser **is** taking to the localhost.

* connected from localhost, got `Host check error`
* expected to see syncthing

Steps to reproduce:
* connect from localhost

### Version Information

Syncthing Version: v0.14.7
OS Version: Gentoo
Browser Version: FF 45.4

**Comment by zetok** [comment]
https://en.wikipedia.org/wiki/Localhost there you go. Don't forget to read the RFCs linked from the wiki article.

**Comment by calmh** [comment]
Cannot reproduce.
