### ISSUE TITLE
Problem syncing unmounted encrypted container

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing#3645]
Hello,

I've tried to sync a truecrypt container with syncthing. I noticed the container does not change its size when its mounted and files are edit within the container nor does ist chane its last modification or creation timestamp. I am on Windows 7 x64, Syncthing 0.13.5 and 0.14.7 tested - problem occurs. Using Chrome or Firefox ESR 45.3.0 Browser.

I expected the container files (I used multiple for testing with different sizes) 256 MB, 512 MB, 8 GB to sync correctly but they didnt. In the target folder files with the prefix ~syncthing~....tmp were created. Windows ProcMon showed syncthing continously reading out the temp files from beginning to end, each having the size of the original file on the master node. Sync mode: Master => Normal. Ignore list is set to ignore Windows Recycle Bin and System Volume Information. For, it seems, the synchting on the target machine locks up continously rereading the temporary files without creating the duplicate with final filename. Task Manager CPU is fine on the master, target shows constantly 100% when container files are processed the way I described.

Reproduce:
- Create TrueCrypt container e.g. 512 MB
- Mount & fill with test data
- Unmount container, so its just a file to the os
- Let syncthing start on both machines and sync over : Master => Target (works perfectly like all other files)
- Disconnect target
- Stop Target syncthing
- Mount container & change some files, Unmount container
- Let syncthing rescan source
- Connect target, start syncthing on target
- Container was detected as changed file (I dont know how this happened, because I thought without size oder modification date changing syncthing could not detect the file changed? is it notifying through windows? I have bare syncthing windows x64 installed without addons.)
- The target falls in infinite loop creating just a size-correct temp file and CPU 100%
- Force Sync does not help
- Restart syncthing on both nodes does not help

Log on target shows:
- Completed index ....
- File or resource went away while syncing. Will retry later.

Thanks for your help.

**Comment by AudriusButkevicius** [comment]
There are certain requirements in order for syncthing to work, namely being able to detect changes, which are impossible to do in the environment you've described, hence you should not expect syncthing to work., It just tries to download a file that does not exist (as the hashes do not match) in a loop hence end up hogging the CPU.

If you searh the forums or the issue tracker however, you might find a workaround in truecrypt that might make it work.

**Comment by canton7** [comment]
There's an option in the TrueCrypt settings to bump the modification timestamp of the container on save. There's a screenshot in a forum post somewhere.
