### ISSUE TITLE
Feature Suggestion: Adding torrents and torrent trackers

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing#3646]
Something that I can really see being useful for Syncthing is addition of torrent and torrent tracker support, along with automated hash-checking of new files I add to currently synchronized directories so that if a hash does match up with a currently known torrent, it will automatically begin downloading via a known torrent, making speeds quicker for everyone and adding another useful feature.
I also would really like to use this as a one-stop-shop, so I don't have to use BitTorrent or Transmission, ever again.

**Comment by AudriusButkevicius** [comment]
No, this is not what syncthing does. Syncthing syncs files, literally nothing todo with torrents.
