### ISSUE TITLE
GUI does not show "Failed Items" (just a loading icon) if the puller isn't running?

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#3647]
The GUI shows me two Out of Sync items, but the "Failed Items" list is loading, and never loads.

![screenshot](https://cloud.githubusercontent.com/assets/568104/19054170/03431f9a-89b6-11e6-973b-bfa6ad2c7104.png)

Looking at the source, it looks like this should be populated by the FolderErrors event, but requesting `/rest/events` gives me no FolderErrors events. I can see StateChanged events for it, where it starts scanning, then stops again, but that's it. Grabbing the scope for that folder, and looking at `failed` also returns an empty object.

The computer which the files were being synced from is currently offline, and Syncthing was restarted since (in order to upgrade from 0.14.5). Could this be related - Syncthing isn't trying to fetch the file, and so can't remember why it failed?

If so, showing 'Out of Sync' and the 'loading' icon is somewhat misleading - it implies that more information is going to appear soon. Would it make sense to record the reason for failure in the database? At the very least, better indicate that no devices are online, and so details about the files items aren't going to be available for a while.

### Version Information

Syncthing Version: v0.14.7
OS Version: Linux StorageDroid 3.10.103-1-ARCH #1 SMP PREEMPT Mon Aug 29 20:27:51 MDT 2016 armv7l GNU/Linux
Browser Version: FF 49.0.1

**Comment by calmh** [comment]
Yeah this is an effect of the delta indexes, where we can be out of sync but have no valid source for the files, so there is no error really. That used to be different before.

**Comment by MoOx** [comment]
I am also affected of this bug on one machine. Not that in my case, machines are all online, I just have one computer that is saying "Out Of Sync" (with some difference between Global & Local State) + spinner for "Failed Items".

**Comment by kirichkov** [comment]
@MoOx check if you've recently deleted folders on one machine - the one that shows it is in Sync. I have ignored files (.DS_Store) and this was causing a removed folder to not be removed, and staying in "Out of Sync" state.

Start syncthing from the command line and look for similar lines:
````
INFO: Puller (folder "aaa", dir "bbb/ccc"): delete: remove /aaa/bbb/ccc: directory not empty
````

Look for hidden files in those folder that you might have excluded from syncthing.
