### ISSUE TITLE
Anti-Introducer Flag

### ISSUE THREAD

**Issue by fti7** [syncthing/syncthing#3648]
As far as i understand, for a specific Folder, all Devices (Which are this Folder is shared to) are announced to the other Devices as well. 
(The Introducer Function will use this Data when enabled)

In (Privacy)Sensitive Environments like Sharing over Tor, NGOs, Journalism etc. -> this could leak critical data/information of the "neighbor nodes".

I would like to see some kind of "Anti-Introducer" Flag, which simply removes all Devices from the ClusterConfig/Folder before sending it (except of the local and the remote device, which are needed i assume)

I know, its an Edge-Case. But Syncthing stands for Strong Privacy and Crypto and this would be a nice Enhancement.

**Comment by AudriusButkevicius** [comment]
Explain how is this data critical?

**Comment by fti7** [comment]
Sorry for my late Response
Im only concerned about Identification/Anonymity of "neightbor nodes". Not that they somehow exist or store the actual Data.
For example if the Nodes are using Tor to communicate -> (Leakage of Public Adresses etc)

What exactly is stored in the File Records/Versions? Does it include the ID of the device which does the change?
Then its of course not easily possible to ensure some kind if Anonymity :-(

**Comment by AudriusButkevicius** [comment]
It contains the first 64 bits of a device ID, but I do (personally) have plans to store full device ID identifying who last modified the file, hence I think what you are asking is a no go.

**Comment by calmh** [comment]
Syncthing is not at all focused on maintaining privacy between devices that share the same folder, to the extent that device IDs and/or addresses are private. Given that I don't think this issue is something we can resolve.
