### ISSUE TITLE
Documentation in .deb package has HTML content in PDF files

### ISSUE THREAD

**Issue by fheinle** [syncthing/syncthing#3651]
Turns out, ``/usr/share/doc/syncthing/FAQ.pdf`` and ``/usr/share/doc/syncthing/Getting-Started.pdf`` only contain HTML content:
    
    $ cat FAQ.pdf 
    <html>
    <head><title>301 Moved Permanently</title></head>
    <body bgcolor="white">
    <center><h1>301 Moved Permanently</h1></center>
    <hr><center>nginx/1.10.0 (Ubuntu)</center>
    </body>
    </html>

    $ cat Getting-Started.pdf 
    <html>
    <head><title>301 Moved Permanently</title></head>
    <body bgcolor="white">
    <center><h1>301 Moved Permanently</h1></center>
    <hr><center>nginx/1.10.0 (Ubuntu)</center>
    </body>
    </html>

I expected to, well, find PDF files. 

### Version Information

```
LANG=C apt-cache policy syncthing
syncthing:
  Installed: 0.14.8
  Candidate: 0.14.8
  Version table:
 *** 0.14.8 500
        500 http://apt.syncthing.net syncthing/release amd64 Packages
        100 /var/lib/dpkg/status
     0.14.7 500
        500 http://apt.syncthing.net syncthing/release amd64 Packages
     0.14.6 500
        500 http://apt.syncthing.net syncthing/release amd64 Packages

```
Syncthing Version: v0.14.8
OS Version: ElementaryOS 0.4 Loki (Ubuntu 16.04) with syncthing repo added

**Comment by MikeLund** [comment]
Thanks for noticing this! I assume the syncthing server config was recently changed to require https, so the old http urls would give that response. https://github.com/syncthing/syncthing/pull/3652 should be a quick fix for it.
