### ISSUE TITLE
False conflicts after wakeup from suspend

### ISSUE THREAD

**Issue by rialpamu** [syncthing/syncthing#3653]
I often get wrong conflicts, when one of the computers involved, wakes up after a suspend.

Both Syncthing instances are started by autostart of my user (rapm):
### Computer A (denklage, Ubuntu 16.04):

`~/.config/autostart/start_syncthing.desktop`:

```
[Desktop Entry]
Type=Application
Exec=/home/rapm/rapt/denklage/bin/start_syncthing
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_US]=Syncthing
Name=Syncthing
Comment[en_US]=
Comment=
```

`/home/rapm/rapt/denklage/bin/start_syncthing`:

```
#!/bin/bash
cd
exec /home/rapm/sw/syncthing/syncthing \
    -no-browser \
    -home=/home/rapm/.config/syncthing
```
### Computer B (pannacotta, Lubuntu 16.04):

`~/.config/autostart/syncthing.desktop`:

```
[Desktop Entry]
Type=Application
Name=Syncthing autostart
Comment=Start Synchting on login
NoDisplay=true
Exec=/home/rapm/rapt/pannacotta/bin/start_syncthing
NotShowIn=GNOME;KDE;XFCE;
```

`/home/rapm/rapt/pannacotta/bin/start_syncthing`:

```
#!/bin/bash
cd
exec /home/rapm/sw/syncthing/syncthing \
    -no-browser \
    -home=/home/rapm/.config/syncthing
```
### Version Information

Syncthing Version: syncthing v0.14.8 "Dysprosium Dragonfly" (go1.7.1 linux-amd64) jenkins@build.syncthing.net 2016-10-03 23:12:55 UTC
OS Version: Ubuntu 16.04.1 LTS
(same OS and Syncthing versions on both computers)

**Comment by calmh** [comment]
What is a wrong conflict?

**Comment by rialpamu** [comment]
- Both computers start with a synchronized file in the same state
- The file is changed on one computer (e.g. some data appended to the end of the file)

Expected state after synchronization:
Both computers have the file with the changes.
What I got (sometimes, after wakeup from suspend):
Both computers have the file with the changes, but there is an additional syncthing conflict file
(`<filename>.sync-conflict-<date>-<time>.<ext>`) that contains the old data of the file.

If the file had been changed on *both* computers, I would expect a conflict, but not
if the file had been changed on one computer only.

If I am allowed to guess: Can there be a problem with system time synchronization:
That syncthing starts synchronization before ntpd has finished his work, and the difference
between the system times on both computers is too big?

**Comment by calmh** [comment]
We don't really care too much about what the system time is, as we only look at the on disk time stamps. If that changes, it'll be seen as a conflict.

**Comment by calmh** [comment]
To debug this, please run the following build:

https://build.syncthing.net/job/syncthing-branch/305/artifact/

Ensure that you capture the logs from it somehow. Running it manually with `-logfile somelog.txt` or just piping the output somewhere is fine.

Reproduce the issue. :)

Grep for `Conflict` in the log output. You'll see something like:

```
[MRIW7] 15:28:10 INFO: Conflict: new: File{Name:"file", Type:FILE, Sequence:6, Permissions:0644, ModTime:2016-11-23 15:28:00 +0100 CET, Version:{[{I6KAH76 5} {MRIW7OK 1}]}, Length:23, Deleted:false, Invalid:false, NoPermissions:false, Blocks:[Block{0/23/88879981cc8fcef9b8f11dfc19e36843392775fc8b3a07be6d132e43efc9f862}]}
[MRIW7] 15:28:10 INFO: Conflict: old: File{Name:"file", Type:FILE, Sequence:6, Permissions:0644, ModTime:2016-11-23 15:28:00 +0100 CET, Version:{[{I6KAH76 4} {MRIW7OK 2}]}, Length:23, Deleted:false, Invalid:false, NoPermissions:false, Blocks:[Block{0/23/6d9556f5d7175bde212eb4da68fa04bf0dd27340dba75b0c8e8940782ae01882}]}
```

Paste that info, and we should be able to narrow it down.

**Comment by calmh** [comment]
Timeout
