### ISSUE TITLE
Syncthing has Problems when files are renamend from upper case to lower case.

### ISSUE THREAD

**Issue by mogoh** [syncthing/syncthing#3654]
I have Syncthing on Ubuntu 16.04 and Android.

I rename some files from upper case to lower case with rename.
`shopt -s globstar`
`rename -v 'y/A-ZÄÖÜ/a-zäöü/' **`

I expect Syncthing to recognize, that the files got renamed.

Instead some files get duplicated (upper and lower case) and some files get deleted completely.

I can't reproduce it 100% of the time but it happens fairly often.

**Comment by canton7** [comment]
Duplicate of #3654, I think?

**Comment by mogoh** [comment]
This is #3654 ...

**Comment by AudriusButkevicius** [comment]
Its definately a duplicate. Please use the search next time.

**Comment by mogoh** [comment]
Duplicate of which bug?

**Comment by AudriusButkevicius** [comment]
Of the one you can find by using the search.

**Comment by mogoh** [comment]
Wow, so helpful.

**Comment by mogoh** [comment]
Would you be so kindly to provide the search treams to find the issue, I am searching for?

**Comment by AudriusButkevicius** [comment]
#1787 found by looking for "case rename"

**Comment by canton7** [comment]
> This is #3654 ...

Bleh copied the wrong issue number, sorry. #1787 is the one I meant to copy.

**Comment by mogoh** [comment]
Thank you!
