### ISSUE TITLE
suggestion: ability to have users pick  what folders they want if a folder with sub folders is shared

### ISSUE THREAD

**Issue by marrie** [syncthing/syncthing#3655]
I often get asked if there is a way to select what folders the user can dl after I share with them a folder. Let's say I have.

*folder A
* Folder B
*  b1 (subfolder))
* b2 (subfolder
* folder C
* folder D

Let's say I share folder B with Joe. He only wants b1. Would there we a way for this user to select just b1 under folder B  so I don't have to do anything? I'm thinking like dropbox here and its selective sync, but a bit more fancy.

Thanks.

**Comment by AudriusButkevicius** [comment]
There is already a master ticket for new ignores/selective sync etc etc, which somewhat addresses this case.

**Comment by marrie** [comment]
So the user will  be able to pick the folders that he/sje wants to sync  After I share them via check boxes? Or how will this work exactly.

**Comment by AudriusButkevicius** [comment]
It's not implemented, and we don't know how it will work exactly (or if will ever get don at all), but the usecase you mentioned is covered by that ticket.

**Comment by marrie** [comment]
Hmm, It would be a good idea, as sometimes I use this thing like a dropbox. I'm also working on some other projects that might involve a selective sync. Let's hope it can be implemented accessibly accessibly.

Blessings and happy Thursday
