### ISSUE TITLE
Mac OS El Capitain Master folder synching on Linux generates "out of sync"

### ISSUE THREAD

**Issue by rdarioc** [syncthing/syncthing#3657]
### Version Information
On Mac OS (Master folder)
Syncthing Version: v0.14.8
OS Version: Mac OS X 10.10.0

On Ubuntu
Syncthing Version: v0.14.8
OS Version: Lubuntu 16.04

I am trying to have a backup copy of Mac OS Picture folder on my Linux machine, everything included, pictures and database and whatever else is into the Mac OS folder ( /Home/<user>/Pictures )

Currently this folder holds about 50 thousand entries.

Every time I start syncthing to perform the syncing, on Mac OS I have a rescan of the entire folder with 50 thousand elements and about the same number of out of sync elements.

What I would expect is just to have the new pictures to be out of sync and maybe the thumbnails and the databases.

What other kind of logs can I provide you to diagnose and fix this issue?

Thanks

**Comment by AudriusButkevicius** [comment]
There is nothing to fix in this case, one side or the other is modifying files (perhaps some image indexer updating metadata).
