### ISSUE TITLE
Android - sync interval and ignore permissions options not saving

### ISSUE THREAD

**Issue by dimm0k** [syncthing/syncthing#3658]
after setting the sync interval to 0 and unchecking the ignore permissions options in the advanced portion for the shared folders, they reset back to 60 and checked respectively for the two options after exiting syncthing. expected the options to stick.

### Version Information

Syncthing Version: v0.14.8
OS Version: Android Marshmallow 6.0 / LGV10

**Comment by calmh** [comment]
This should be on the Android tracker, https://github.com/syncthing/syncthing-android/issues, unless it's narrowed down to be a problem with Syncthing itself.

**Comment by wweich** [comment]
You cannot not ignore permissions on Android. So The Android App will always set that option automatically. As the Android App uses inotify, it manages the scan interval (not sync interval) on its own.
