### ISSUE TITLE
panic: SIGSEGV in netpoll.go

### ISSUE THREAD

**Issue by abs0** [syncthing/syncthing#3659]
May well be a go or OS issue

Panic at 2016-10-07T09:14:20+01:00
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45f1e6]

runtime stack:
runtime.throw(0xa64c5e, 0x2a)
        /usr/pkg/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
        /usr/pkg/go/src/runtime/sigpanic_unix.go:12 +0x2cc
runtime.netpollunblock(0x0, 0x100000072, 0x0)
        /usr/pkg/go/src/runtime/netpoll.go:352 +0x26
runtime.netpollready(0x7f7ff67fd3d0, 0x0, 0x7f7f00000072)
        /usr/pkg/go/src/runtime/netpoll.go:285 +0x5b
runtime.netpoll(0xebfd01, 0x0)
        /usr/pkg/go/src/runtime/netpoll_kqueue.go:94 +0x21e
runtime.findrunnable(0xc420014000, 0x0)
        /usr/pkg/go/src/runtime/proc.go:2003 +0x28c
runtime.schedule()
        /usr/pkg/go/src/runtime/proc.go:2120 +0x14c
runtime.park_m(0xc420001040)
        /usr/pkg/go/src/runtime/proc.go:2183 +0x123
runtime.mcall(0x0)
        /usr/pkg/go/src/runtime/asm_amd64.s:240 +0x5b

goroutine 1 [chan receive, 664 minutes]:
main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0xa4c6e4, 0x1, 0x0, 0x0, ...)
        /var/obj/pkg/net/syncthing/work/gopath/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:812 +0x1810
main.main()
        /var/obj/pkg/net/syncthing/work/gopath/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:373 +0x239
[panic-20161007-091420.log.zip](https://github.com/syncthing/syncthing/files/515712/panic-20161007-091420.log.zip)

**Comment by AudriusButkevicius** [comment]
It seems you are not using the official builds. This was built it seems with cgo enabled  thats causing this.

**Comment by calmh** [comment]
I'm not certain why you think this is a cgo issue, but it certainly appears to be a Go-on-netbsd issue rather than something on our side...

**Comment by AudriusButkevicius** [comment]
It's not a cgo issue per-se, yet these happen more often when cgo is involved.
