### ISSUE TITLE
[feature request] Sync once and exit

### ISSUE THREAD

**Issue by ximanex** [syncthing/syncthing#3660]
Hello! I have PC and a laptop and I use Syncthing to sync data between them. I cannot keep Syncthing running on my laptop all the time, because internet usage consumes battery power, and in fact I only need to sync data twice - when I turn my laptop on and when I turn it off. So, I launch Syncthing and kill it after a couple of minutes. It would be great if we had an option, which would make Syncthing launch, look for available devices, sync all available folders and exit. Could you please implement it? Thanks in advance.

**Comment by canton7** [comment]
Syncthing is designed as a continuous synchronization program - it's hard to tell when it's "finished" synchronizing, as that term doesn't really make sense when it's running all the time.

It sounds like you're after SyncToy, rsync, or Unison?

**Comment by AudriusButkevicius** [comment]
Yes, out of scope.
