### ISSUE TITLE
Syncthing systemwide service panic.

### ISSUE THREAD

**Issue by kakoskin1** [syncthing/syncthing#3661]
I have installed syncthing using https://copr.fedorainfracloud.org/coprs/decathorpe/syncthing/. After an update to version 0.14.8 I can not start syncthing as system wide service. Starting a service will cause continuous loop of crashes and restarts. 

After downgrading to 0.14.7 official binaries, I get the same panic.

Starting official binaries from the command line I get following panic log:

[G2ZOX] 16:13:40 INFO: syncthing v0.14.8 "Dysprosium Dragonfly" (go1.7.1 linux-amd64) jenkins@build.syncthing.net 2016-10-03 23:12:55 UTC
[G2ZOX] 16:13:40 INFO: My ID: G2ZOXAK-S7U5YEQ-GE3V3SQ-YQ44WDW-RSKIXNV-XNKF26C-VIYEGWX-GI3YOQC
[G2ZOX] 16:13:41 INFO: Single thread hash performance is 354 MB/s using minio/sha256-simd (334 MB/s using crypto/sha256).
[G2ZOX] 16:13:41 INFO: Ready to synchronize qjznw-3vhhp (readwrite)
[G2ZOX] 16:13:42 INFO: Ready to synchronize jey7w-du9rp (readwrite)
[G2ZOX] 16:13:42 INFO: Ready to synchronize ywapn-gtqar (readwrite)
[G2ZOX] 16:13:42 INFO: Ready to synchronize 5ffek-hpqfq (readonly)
...
Panic at 2016-10-08T16:13:44+03:00
panic: proto: VersionList: illegal tag 0 (wire type 0)

goroutine 1 [running]:
panic(0x99bb40, 0xc420ec64c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/syncthing/syncthing/lib/db.(*Instance).checkGlobals(0xc420173bf0, 0xc421dd7c90, 0xb, 0x10, 0xc4219e61c8)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:582 +0x97c
github.com/syncthing/syncthing/lib/db.NewFileSet(0xc420169c90, 0xb, 0xc420173bf0, 0xc420616618)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/set.go:109 +0x282
github.com/syncthing/syncthing/lib/model.(*Model).addFolderLocked(0xc4215c57c0, 0xc420169c90, 0xb, 0xc420169cb0, 0xc, 0xc42016a7e0, 0x1a, 0x0, 0xc420098400, 0x2, ...)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/model.go:304 +0xd2
github.com/syncthing/syncthing/lib/model.(*Model).AddFolder(0xc4215c57c0, 0xc420169c90, 0xb, 0xc420169cb0, 0xc, 0xc42016a7e0, 0x1a, 0x0, 0xc420098400, 0x2, ...)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/model.go:298 +0xa1
main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa49ec4, 0x1, 0x0, 0x0, ...)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:705 +0x1172
main.main()
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:373 +0x239

goroutine 20 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 21 [chan receive]:
main.trackCPUUsage()
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0xf9
created by main.init.3
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x35

goroutine 22 [select, locked to thread]:
runtime.gopark(0xc15a28, 0x0, 0xa4b8da, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc420022f30, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc420022f30)
	/usr/local/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:304 +0x2f3
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 23 [chan receive]:
main.setupSignalHandling.func1(0xc42006a8a0)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:841 +0x40
created by main.setupSignalHandling
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:843 +0xfa

goroutine 24 [chan receive]:
main.setupSignalHandling.func2(0xc42006aa20)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:851 +0x40
created by main.setupSignalHandling
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:853 +0x1f5

goroutine 25 [select]:
github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).Serve(0xc420106380)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:338 +0xe61
created by github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).ServeBackground
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:297 +0x43

goroutine 26 [select]:
github.com/syncthing/syncthing/lib/events.(*Subscription).Poll(0xc4200d8f60, 0xdf8475800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:239 +0x3f8
github.com/syncthing/syncthing/lib/events.(*bufferedSubscription).pollingLoop(0xc420093ae0)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:293 +0x55
created by github.com/syncthing/syncthing/lib/events.NewBufferedSubscription
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:287 +0x22f

goroutine 27 [select]:
github.com/syncthing/syncthing/lib/events.(*Subscription).Poll(0xc4200d8fc0, 0xdf8475800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:239 +0x3f8
github.com/syncthing/syncthing/lib/events.(*bufferedSubscription).pollingLoop(0xc420093b30)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:293 +0x55
created by github.com/syncthing/syncthing/lib/events.NewBufferedSubscription
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:287 +0x22f

goroutine 4 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc420106000)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x247
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x1bc

goroutine 33 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc4202b4780)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:106 +0x544
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:141 +0x620

goroutine 34 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc4202b4780)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:96 +0x249
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:142 +0x642

goroutine 35 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).compactionTransact(0xc4202b4780, 0xa4e66a, 0xb, 0xe87240, 0xc42023a0a0)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:225 +0x53a
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).tableCompaction(0xc4202b4780, 0xc420270800, 0x0)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:577 +0x6ce
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).tableAutoCompaction(0xc4202b4780)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:633 +0x5b
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc4202b4780)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:824 +0x362
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:148 +0x7c8

goroutine 36 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc4202b4780)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:751 +0x263
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:149 +0x7ea

goroutine 37 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc4202b4780)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x1ad
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:150 +0x80c

goroutine 49 [select]:
github.com/syncthing/syncthing/lib/model.(*ProgressEmitter).Serve(0xc421698550)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/progressemitter.go:57 +0x586
created by github.com/syncthing/syncthing/lib/model.NewModel
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/model.go:164 +0xb6f

### Version Information

Syncthing Version: v0.14.8 (and after downgrade also 0.14.7)
OS Version: Fedora 24

**Comment by AudriusButkevicius** [comment]
It seems you database is corrupt, search the forum how to fix it.
