### ISSUE TITLE
Folder path select menu drops off screen without a scroll bar to reach all the options.

### ISSUE THREAD

**Issue by ldwoolley** [syncthing/syncthing#3662]
When a folder has lots of folders to choose from the drop down input select drop down method only displays the first several that fit between the folder path select item and the bottom of the monitor screen.  This was experienced while using "+add folder", dialog and trying to select a folder path using the <input> list.  When the list is longer than the display screen space, the remaining folder options are not accessible. Scrolling the browser window does not move the drop down select window. 

I would expect a scroll bar in the select window to allow the form to be scrolled to the desired folder that is presently off the displayed area. 

This is reproducible on Chrome Version 53.0.2785.143 m (64-bit) whenever the number of selectable folders in the select path, exceed the number of folders that fit in the space between the folder path select and the bottom of the monitor screen.  I saw this on the windows C:\ and on the C:\Users\xxxxxxx\ folders.  Internet Explorer  Version 11.187.14393.0 displayed a scroll bar for the same function.

Below is the HTML code that describes the folder path input list path.
<input name="folderPath" ng-readonly="editingExisting" id="folderPath" class="form-control ng-dirty ng-valid ng-valid-required" type="text" ng-model="currentFolder.path" list="directory-list" required="" path-is-sub-dir="">

### Version Information

Syncthing Version: v0.14.8, Windows (64 bit)
OS Version: Windows 10: version 1607
Browser Version: Chrome Version 53.0.2785.143 m (64-bit)

**Comment by AudriusButkevicius** [comment]
Sadly this is a limitation of the browser as that drop down element is provided by the browser, not much we can do about it apart from changing for something much more funky.

You can start typing the letters of the subfolder to reduce the list that is shown.

**Comment by ldwoolley** [comment]
Digging a little further reveals that this has been a problem for two years, and according to this page on the Chromium bug tracker, as of September 2016 it will not be addressed until at 2017.  Just wanted a time frame and confirmation of the problem attached to the issue response.  Thanks,  https://bugs.chromium.org/p/chromium/issues/detail?id=375637.
