### ISSUE TITLE
syncthing 0.14.8 fails on f23/Go 1.5

### ISSUE THREAD

**Issue by azrdev** [syncthing/syncthing#3664]
d5a0f91cb47edffacad759d75eb7ea048b969ec8 in v0.14.8 broke the build on Go 1.5 (e.g. fedora23), for full log see decathorpe/fedora-pkgs#5

### Version Information

Syncthing Version: v0.14.8
OS Version: Fedora 23

**Comment by AudriusButkevicius** [comment]
I might be wrong but I think we now require go1.7

**Comment by calmh** [comment]
Well, we should still compile on 1.5+, even if those versions suck for various reasons. The SetTraceback should be conditional on being compiled on a version that requires it, i.e. 1.7+.

**Comment by azrdev** [comment]
thx!
