### ISSUE TITLE
Deletion of synced backup of sync folder

### ISSUE THREAD

**Issue by dschrempf** [syncthing/syncthing#3666]
OK, this is a hard one :-).

I have a synced folder; lets call it `watch_folder`.  I create backups of my `watch_folder` within another synced folder (let's call it `backup_folder`).  If I delete old backups of the `watch_folder` within my `backup_folder`.  Then, I get the following error on another device (not the one where I delete the folders).

```
Oct 12 15:26:17 hostname syncthing[3506]: [ABCDE] INFO: Puller (folder "backup_folder", dir "path/to/watch_folder"): delete: remove /path/to/watch_folder: directory not empty
```

If I look at that folder, I find a `.stfolder` file.
### Version Information

syncthing v0.14.8 "Dysprosium Dragonfly" (go1.7.1 linux-amd64) builduser@svetlemodry 2016-10-04 16:51:21 UTC
Linux schwarzbaer 4.7.6-1-ARCH #1 SMP PREEMPT Fri Sep 30 19:28:42 CEST 2016 x86_64 GNU/Linux

**Comment by AudriusButkevicius** [comment]
Yeah these filea are ignored so most likely not deleted yet ideally you should exclude that file from the backup.

**Comment by calmh** [comment]
I don't think we should ever delete the .stfolder file, regardless of where we find it.
