### ISSUE TITLE
 syncthing can not synchronize the forder's timestamp

### ISSUE THREAD

**Issue by swordyang** [syncthing/syncthing#3667]
I have an old server that needs to synchronize the above files to the new server. But I found that syncthing can synchronize the file's timestamp but folder.

![20161013210746](https://cloud.githubusercontent.com/assets/4026598/19350151/353390f4-9189-11e6-8048-52d3e4ba07ac.png)

### Version Information

Syncthing Version: v0.14.8 "Dysprosium Dragonfly" (go1.7.1 windows-amd64)
OS Version: Windows 10
Browser Version: Chrome 53.0.2785.143

**Comment by AudriusButkevicius** [comment]
Read the docs explaining what is synced ans what is not. It does not sync folder timestamps because it's a mess and folder timestampa have dofferent meanings between different operating systems.
