### ISSUE TITLE
Syncthing icon for Windows binaries.

### ISSUE THREAD

**Issue by damajor** [syncthing/syncthing#3668]
Hi,

I just noticed that there is no SyncThing icon to the Windows binary.
Will it be added ?

**Comment by AudriusButkevicius** [comment]
If you want to contribute additions to the build script, sure why not.

**Comment by damajor** [comment]
I'll try to look into this new thing for me :)

**Comment by damajor** [comment]
I look quickly for a way to do that and it appears that there is no easy solutions.

- use some kind of resource patcher to embed the icon, I do not recommend this method as it requires external executable to be run and patch the SyncThing binary.
- use rsrc https://github.com/akavel/rsrc, it is pretty similar to the other but generate a resource used by the Go compiler at link time when it bundles all binaries into a single executable.
- use https://github.com/josephspurrier/goversioninfo, it is almost the same as the previous one but include the full structure used by Windows to show file details when you show its properties.

The last two seems good, but I dislike the fact that it is not portable across operating systems...

So you can leave the ticket open for tracking purpose, but at this time I think it is too much work for a such little enhancement.

**Comment by AudriusButkevicius** [comment]
What makes you think they are not portable? I think you can run them on any OS as long as you are targeting a Windows binary.

**Comment by damajor** [comment]
You are right. The last two should be portable.

**Comment by calmh** [comment]
That said, is there a point to having a nice icon when double clicking it just results in an ugly terminal window? This feels to me like something that should be solved by a wrapper or a hypothetical future version that actually has a GUI...

**Comment by AudriusButkevicius** [comment]
It's a low hanging fruit. Clicking on an icon that looks like a .com file is much worse, despite the fact it opens an ugly window.

**Comment by AlexIljin** [comment]
I run Syncthing occasionally, when I backup my phone to my laptop once a week. I run it from the Total Commander toolbar. It would be nice to at the very least have an ico-file somewhere in the Syncthing folder so I could manually associate it with the toolbar button.

An icon embedded in the exe would be a convenience, but it can be seen as a second step.

**Comment by AudriusButkevicius** [comment]
The ico files are available on the github repo.

**Comment by calmh** [comment]
Implemented
