### ISSUE TITLE
Syncthing and Virtualbox don't play nicely together

### ISSUE THREAD

**Issue by Deleetdk** [syncthing/syncthing#3669]
OS: Windows 8.1, 64bit.

I'm running [Virtualbox](https://www.virtualbox.org/) to host a linux system for coding related work. I have multiple computers where I need to access the same Virtualbox image file, so naturally I set up syncthing to share the folder with the image file (.vdi). The trouble is that this image file is very large, think 50 GB. Whenever syncthing rescans this file, it causes massive CPU and harddisk use. This issue can be partially solved by setting the rescan frequency to a large value, say, every third hour.

The trouble is that sometimes the rescan will happen while the virtual system is running. Of course, while it's running, the image file is constantly changing due to file operations on the system (e.g. database update). This seems to cause a kind of feedback loop between syncthing and Virutalbox that causes an even larger spike in CPU and harddisk use. Very annoying. Often I end up pausing syncthing entirely while working, but this is an error-prone solution because I forget to turn it on again, so my other folders do not get synced.

Is some there way to prevent syncthing from trying to rescan the Virtualbox file when it is open?

There doesn't seem to be a way to pause a particular folder only. That would be an improvement even if not a full solution.

**Comment by AudriusButkevicius** [comment]
I don't really see a bug here and everything sounds like working as intended. If you want to have a generic discussion about things, use the forum.

**Comment by Ferroin** [comment]
General advice:  You don't need the whole VM synced.  At most, you need parts of /etc and /var, plus the package list (which is trivial to manually sync), and any user data.  Your best option is probably to create a virtualbox shared folder, store your home directory there, and sync that on the Windows side with Syncthing (and even that may have issues).

**Comment by Deleetdk** [comment]
@Ferroin It's one file (50 GB), not a directory. I don't see how you want to split it up.

**Comment by Ferroin** [comment]
Do you mean it's exactly one file _in_ the VM that you need synced, or are you missing the point that you can sync stuff from _inside_ the VM itself?

I'm not talking about trying to split up the disk image, I'm talking about what inside the VM you need to keep in sync to keep the systems functionally identical.  On Linux, the list of directories inside the VM that you need to actually keep in sync is:
* /etc (you may need to exclude some files)
* /var/lib (only some parts of it, which ones depends on what you're using)
* /home
* Any secondary user data directories (/var/www for example).
As long as you keep those the same between systems and make sure the packages installed on the systems are the same, the systems will be functionally identical.

The simplest way to achieve this is to create a shared folder in VirtualBox itself (check here for details: https://www.virtualbox.org/manual/ch04.html#sharedfolders), store all your user data there (which will put it on the host system), and then point Syncthing at the directory being shared by VirtualBox as the folder to synchronize.

**Comment by Deleetdk** [comment]
I thought of that and decided it would be a real hassle. There are lots of installed system-level packages (e.g. MariaDB + dependencies, RStudio + dependencies) to sync, it's not just a few folders with Python `virtualenv`'s that can be easily synced.

It seems that I will have to do the stop/start syncthing for this task. Or maybe try rsync which may be able to handle this task better.

**Comment by Ferroin** [comment]
If you're using versions from your distro's package manager, you just need a list of manually installed packages (On Gentoo, you need `/var/lib/portage/world` and the contents of `/etc/portage`, on Debian based systems (including Ubuntu) you can use Aptitude and pull out the package state info from that (I think it's in /var somewhere), on Fedora, you can get a direct dump of all the RPM's installed on the system and feed that to dnf on another system), and the package manager will handle all the dependencies for you.

If you're using local builds of everything, there's a bunch of options (install to a home directory, put build directories in the shared folder, etc), but you should be seriously looking at what's involved in the eventual deployment of whatever you're developing (local builds make this much harder).

Rsync really would be better though if you're looking just to sync the VM image, although make sure to use `--checksum` so you get incremental transfers.
