### ISSUE TITLE
The total items syncthing scaned different with widnows folder display?

### ISSUE THREAD

**Issue by swordyang** [syncthing/syncthing#3670]
1. Syncthing scaned my folder have 809968 items, but on windows, my folder contains 728,399 files, 81,538 folders, in total 809937 items. What are the extra 31 items?

2. Can syncthing WebUI displays the number of files and folders separately?

3. Is synchintg use multithreading to transfer files?

![untitled](https://cloud.githubusercontent.com/assets/4026598/19373977/be26a60a-91fa-11e6-9990-337dbb8d0413.png)

### Version Information

Syncthing Version: v0.14.8 "Dysprosium Dragonfly" (go1.7.1 windows-amd64)
OS Version: Windows 10
Browser Version: Chrome 53.0.2785.143

**Comment by AudriusButkevicius** [comment]
1. It probably includes Thumbs.db and others which windows is potentially excluding.

2. There is no option for that.

3. Yes, but next time use the forum for generic questions.
I don't see a bug per-
