### ISSUE TITLE
Web ui not loading and not updating

### ISSUE THREAD

**Issue by VynDragon** [syncthing/syncthing#3671]
What happened:
Was setting up syncthing on a new computer, when I noticed all the other's gui were at first not loading at all, and after a restart of the services, only showing 'unknown' on all folders (they were mostly synced already), as well as most of the time not loading at all if I tried to refresh the page.

What you expected to happen: 
Web gui showing the status of syncing.

Steps done:
- Setup syncthing on 3 computers for a large data set (> 1.5 TB)
- Let it sync for one night
- Notice all the non-fonctional uis in the morning.

These screenshot were taken after restarting the services (after all the uis stopped loading) on the morning. Uptime isn't updating either. All folder show 0 items, 0 bytes.
![screenshot_20161014_115310](https://cloud.githubusercontent.com/assets/3176238/19383555/4044ae34-9205-11e6-957a-4302f73f297f.png)
![screenshot_20161014_115328](https://cloud.githubusercontent.com/assets/3176238/19383553/4043346e-9205-11e6-8f5e-18dcee8aed67.png)
![screenshot_20161014_115454](https://cloud.githubusercontent.com/assets/3176238/19383554/40447cb6-9205-11e6-9768-fd479290f4bc.png)

### Version Information

Syncthing Version: v0.14.8
OS Version: Windows server 2008 r2 / Centos 6.8
Browser Version: Chromium 53.0.2785.143 (64-bit)

**Comment by AudriusButkevicius** [comment]
Please use forum for support.

**Comment by 5chdn** [comment]
> Please use forum for support.

@AudriusButkevicius if this is not a bug, please link the correct support forum thread. I am affected by the same problem and it seems we are not alone, #3685

**Comment by VynDragon** [comment]
take a look at this one @5chdn : https://github.com/syncthing/syncthing/issues/3634

**Comment by 5chdn** [comment]
thanks, will subscribe.
