### ISSUE TITLE
 Temporary files are not cleaned up

### ISSUE THREAD

**Issue by swordyang** [syncthing/syncthing#3677]
I tried synchronize a large files more than 4.45GB, and found temporary files are not cleaned up when synchronize finished. It very easy to reproduce.

![bigfile](https://cloud.githubusercontent.com/assets/4026598/19549227/b2223556-96d5-11e6-9fcc-68be9be1023b.png)

### Version Information

Syncthing Version: v0.14.8 "Dysprosium Dragonfly" (go1.7.1 windows-amd64)
OS Version: Windows 10
Browser Version: Chrome 53.0.2785.143

**Comment by AudriusButkevicius** [comment]
Its on purpose, so that we don't have to redownload stuff if the file reappears, they grt cleaned up after 24h

**Comment by ProactiveServices** [comment]
[Understanding Synchronization - Temporary Files](https://docs.syncthing.net/users/syncing.html?highlight=tmp#temporary-files)

**Comment by calmh** [comment]
... given that the synchronization failed. If it succeeded, the temp file would become the new real file and hence not be left around.
