### ISSUE TITLE
strelaysrv should be able to bind a to a specific address

### ISSUE THREAD

**Issue by grinapo** [syncthing/syncthing#3682]
strelaysrv does have a "listen" option but it does not bind to that address for _outbound_ traffic, but uses whatever default address through a default way is available. This won't cut it when a box have multiple addresses with multiple outbounds and the address to be used is not the default.

The result is that while "listen" have address2, the server goes out using address1, and the relay registry rejects with 

> https://relays.syncthing.net/endpoint failed to join due to IP address not matching external address. Aborting

which is obviously true. 
### Version Information

strelaysrv v0.14.9+11-g7c37301 (go1.7.3 linux-amd64) jenkins@build.syncthing.net 2016-10-21 07:33:40 UTC

**Comment by AudriusButkevicius** [comment]
Did you try -ext-address?

**Comment by grinapo** [comment]
I have tried everything listed in _-help_.

**Comment by AudriusButkevicius** [comment]
Yeah, I see the issue
