### ISSUE TITLE
suggestion: remove standard webkit focus

### ISSUE THREAD

**Issue by steebchen** [syncthing/syncthing#3684]
As you can see in the picture attached at the bottom, Chrom(e|ium) has a standard outline for focused elements. I personally hate this outline and I think it would be good to simly set `outline: none` to buttons, especially because there is a custom box-shadow active effect and it's obvious that the section in the screenshot is currently active. 

EDIT: This only occurs in the light theme, I don't see any blue outline in the dark theme.

![selection_999 557](https://cloud.githubusercontent.com/assets/5013932/19627902/2dd3e75c-9952-11e6-84a5-bf5d2689ecc0.png)

Syncthing Version: v0.14.9
OS Version: Linux Mint (64 bit) (Ubuntu 16.04)
Browser Version: Chromium v52

**Comment by AudriusButkevicius** [comment]
I think it has some accessibility implications?

**Comment by AudriusButkevicius** [comment]
Outlinenone.com
