### ISSUE TITLE
Lastest version fail to start after try for 3 time

### ISSUE THREAD

**Issue by ptksoft** [syncthing/syncthing#3688]
### Version Information

Syncthing Version: v0.14.9
OS Version: Windows 7 x64
Browser Version: Firefox 49.0.2

Cannot start after trying 4 restart message as below:

[monitor] 19:19:02 INFO: Log output saved to file "C:\Users\PITAK\AppData\Local\Syncthing\syncthing.log"
[monitor] 19:19:02 INFO: Starting syncthing
[U6GQS] 19:19:02 INFO: syncthing v0.14.9 "Dysprosium Dragonfly" (go1.7.1 windows-amd64) jenkins@build.syncthing.net 2016-10-17 07:21:58 UTC
[U6GQS] 19:19:02 INFO: My ID: U6GQSR7-XD677CF-RQUGLFF-LJFJRQP-Z65TSOD-WHTNVCA-YDZIDEM-ZRGB5AW
[U6GQS] 19:19:03 INFO: Single thread hash performance is 142 MB/s using minio/sha256-simd (123 MB/s using crypto/sha256).
[U6GQS] 19:19:03 INFO: Ready to synchronize Mobile.Gallery (readwrite)
[U6GQS] 19:19:04 INFO: Ready to synchronize PTKSOFT (readwrite)
[U6GQS] 19:19:04 INFO: Ready to synchronize default (readwrite)
panic: leveldb/table: corruption on data-block (pos=1272452): checksum mismatch, want=0xe8ce8b04 got=0x17ea3ddd [file=000085.ldb]
[monitor] 19:19:04 WARNING: Panic detected, writing to "C:\Users\PITAK\AppData\Local\Syncthing\panic-20161026-191904.log"
[monitor] 19:19:04 WARNING: Please check for existing issues with similar panic message at https://github.com/syncthing/syncthing/issues/
[monitor] 19:19:04 WARNING: If no issue with similar panic message exists, please create a new issue with the panic log attached
[monitor] 19:19:04 INFO: Syncthing exited: exit status 2
[monitor] 19:19:05 INFO: Starting syncthing
[U6GQS] 19:19:05 INFO: syncthing v0.14.9 "Dysprosium Dragonfly" (go1.7.1 windows-amd64) jenkins@build.syncthing.net 2016-10-17 07:21:58 UTC
[U6GQS] 19:19:05 INFO: My ID: U6GQSR7-XD677CF-RQUGLFF-LJFJRQP-Z65TSOD-WHTNVCA-YDZIDEM-ZRGB5AW
[U6GQS] 19:19:06 INFO: Single thread hash performance is 142 MB/s using minio/sha256-simd (122 MB/s using crypto/sha256).
[U6GQS] 19:19:06 INFO: Ready to synchronize PTKSOFT (readwrite)
[U6GQS] 19:19:06 INFO: Ready to synchronize default (readwrite)
panic: leveldb/table: corruption on data-block (pos=1272452): checksum mismatch, want=0xe8ce8b04 got=0x17ea3ddd [file=000085.ldb]
[monitor] 19:19:06 WARNING: Panic detected, writing to "C:\Users\PITAK\AppData\Local\Syncthing\panic-20161026-191906.log"
[monitor] 19:19:06 WARNING: Please check for existing issues with similar panic message at https://github.com/syncthing/syncthing/issues/
[monitor] 19:19:06 WARNING: If no issue with similar panic message exists, please create a new issue with the panic log attached
[monitor] 19:19:06 INFO: Syncthing exited: exit status 2
[monitor] 19:19:07 INFO: Starting syncthing
[U6GQS] 19:19:07 INFO: syncthing v0.14.9 "Dysprosium Dragonfly" (go1.7.1 windows-amd64) jenkins@build.syncthing.net 2016-10-17 07:21:58 UTC
[U6GQS] 19:19:07 INFO: My ID: U6GQSR7-XD677CF-RQUGLFF-LJFJRQP-Z65TSOD-WHTNVCA-YDZIDEM-ZRGB5AW
[U6GQS] 19:19:08 INFO: Single thread hash performance is 142 MB/s using minio/sha256-simd (122 MB/s using crypto/sha256).
[U6GQS] 19:19:08 INFO: Ready to synchronize Mobile.Gallery (readwrite)
[U6GQS] 19:19:09 INFO: Ready to synchronize PTKSOFT (readwrite)
[U6GQS] 19:19:09 INFO: Ready to synchronize default (readwrite)
panic: leveldb/table: corruption on data-block (pos=1272452): checksum mismatch, want=0xe8ce8b04 got=0x17ea3ddd [file=000085.ldb]
[monitor] 19:19:09 WARNING: Panic detected, writing to "C:\Users\PITAK\AppData\Local\Syncthing\panic-20161026-191909.log"
[monitor] 19:19:09 WARNING: Please check for existing issues with similar panic message at https://github.com/syncthing/syncthing/issues/
[monitor] 19:19:09 WARNING: If no issue with similar panic message exists, please create a new issue with the panic log attached
[monitor] 19:19:09 INFO: Syncthing exited: exit status 2
[monitor] 19:19:10 INFO: Starting syncthing
[U6GQS] 19:19:10 INFO: syncthing v0.14.9 "Dysprosium Dragonfly" (go1.7.1 windows-amd64) jenkins@build.syncthing.net 2016-10-17 07:21:58 UTC
[U6GQS] 19:19:10 INFO: My ID: U6GQSR7-XD677CF-RQUGLFF-LJFJRQP-Z65TSOD-WHTNVCA-YDZIDEM-ZRGB5AW
[U6GQS] 19:19:11 INFO: Single thread hash performance is 142 MB/s using minio/sha256-simd (122 MB/s using crypto/sha256).
[U6GQS] 19:19:11 INFO: Ready to synchronize PTKSOFT (readwrite)
[U6GQS] 19:19:11 INFO: Ready to synchronize default (readwrite)
panic: leveldb/table: corruption on data-block (pos=1272452): checksum mismatch, want=0xe8ce8b04 got=0x17ea3ddd [file=000085.ldb]
[monitor] 19:19:12 WARNING: Panic detected, writing to "C:\Users\PITAK\AppData\Local\Syncthing\panic-20161026-191912.log"
[monitor] 19:19:12 WARNING: Please check for existing issues with similar panic message at https://github.com/syncthing/syncthing/issues/
[monitor] 19:19:12 WARNING: If no issue with similar panic message exists, please create a new issue with the panic log attached
[monitor] 19:19:12 INFO: Syncthing exited: exit status 2
[monitor] 19:19:13 WARNING: 4 restarts in 10.484375s; not retrying further

**Comment by AudriusButkevicius** [comment]
Please search the forums for the error message and use the forums for support requests.

**Comment by ProactiveServices** [comment]
Should Syncthing be asking users to report this to the issue tracker if the database is detected as corrupt?

**Comment by AudriusButkevicius** [comment]
Good point, we should capture the corrupt message and point to a FAQ. Can we haz new issue for that?
