### ISSUE TITLE
cmd/syncthing: Extra parameters on command line should trigger failure and usage message

### ISSUE THREAD

**Issue by dinosore** [syncthing/syncthing#3690]
For some unknown reason, I entered `syncthing /paths` instead of `syncthing -paths` at the command line for a user not currently running syncthing.

It seems that st ignores any arguments other than options, and started normally, creating files and certificates and launching the gui.

Options appear to be validated as expected. `syncthing -paths` and `syncthing --paths` are accepted and show the expected information.  `syncthing ---paths` and `syncthing -junk` respond as `syncthing -help`.

However, there seems to be no validation that the rest of the command line is empty apart from comments.

No great harm happened - just a few files to delete.

I consider this a minor, embarrassing bug.
### Version Information

Syncthing Version: v0.14.9
OS Version: Debian stretch...
Browser Version: n/a

**Comment by calmh** [comment]
Yeah, should trigger the usage message.
