### ISSUE TITLE
Sign git commits & releases

### ISSUE THREAD

**Issue by rugk** [syncthing/syncthing#3693]
You should consider signing git commits & releases.

* [onionshare#221 (comment)](https://is.gd/7vU4oK)
* It is also displayed on GitHub: https://github.com/blog/2144-gpg-signature-verification
* Here is GitHub's help for this: https://help.github.com/articles/generating-a-gpg-key/
* And here is how you can properly sign releases: https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by AudriusButkevicius** [comment]
Releases are already signed, so are the binaries.
As for signing commits, maybe, but that doesn't mean that unsigned commits can't be wedged in, making me doubt usefulness.

**Comment by calmh** [comment]
Yes. I see nothing obvious here for us to consider that we're not doing, apart from signing commits. If so please help me by pointing it out. 

I'm unconvinced of the utility of signing commits. What would it be?

**Comment by AudriusButkevicius** [comment]
I guess we could verify that all commits are signed since X in the release process.

**Comment by rugk** [comment]
You can also combine code review and code singing, so you can verify who signs what. See https://is.gd/7vU4oK for more details.
