### ISSUE TITLE
Having a large number of files to sync causes a long time to pause a device

### ISSUE THREAD

**Issue by guddimon-** [syncthing/syncthing#3697]
I have three devices in use where two of them sync folders to the third one.

Sometimes there are a lot of files (currently more than 60000) to sync on one of the two devices, so I use "pause" on the third one. This process tooks up to two hours until the folders on the third device are marked as "out of sync". The folders are only shared between the two devices, so I would expect that they are marked instantly as "out of sync".

As I read from the console output it is tried to sync each file that was not synced, but this fails because the device was set to pause.

EDIT:
Looks like it is the same when having only a few files with a big size. Does the puller try pulling each filepart from the device that was set to "pause"?

**Comment by guddimon-** [comment]
Sorry, I forgot to add the message from the log file:
`[ABCDE] 00:11:19 INFO: Puller: final: peers who had this file went away, or the file has changed while syncing. will retry later`

**Comment by AudriusButkevicius** [comment]
This is not really a bug report but rather a support ticket given there is nothing immediately actionable here.
The more appropriate place for this would be the forum.

Pause effectively disconnects the device, so sometimes there is no way of knowing that you are out of sync because you potentially disconnected before being informed about it, and potentially you discover that via some third party which comes online later.

It does not try to pull each block individually and fails on the first one missing, yet it tries to download every file that it's aware of that has changed, which involves reading current state of every file from the database, which potentially could be slow due to slow disk.

**Comment by guddimon-** [comment]
But if the puller was informed about the pause state it could stop working and just start again when the device is unpaused.

Please see this as an enhancement that could be done.

**Comment by guddimon-** [comment]
BTW:
syncthing does not wait for any I/O but just uses the CPU up to 100%. On both cores. So the slow disk should not cause this issue.

**Comment by AudriusButkevicius** [comment]
Pausing a device does not imply there are no other devices available to serve files for a given puller of a given folder.

Futhermore, the puller is not informed about anything, all it knows is that there no longer exists a place where to get the file from, yet there could be multiple reasons for that, one of them being that the file for example has changed.

Sure, CPU bottleneck is still a bottleneck however, so you database reads are probably bound by the CPU.

**Comment by guddimon-** [comment]
So you suggest I should upgrade to the future coming hexacore with 10GHz? ;)

Please just have a look at this as a user and not as a developer. I know that it is technically correct what you say. But as a user it is  very annoying to wait for hours until a folder gets its current state shown. And it does not make any sense to try each block when a device is not available. In web frontend it is clearly marked as paused.

**Comment by AudriusButkevicius** [comment]
It does not try each block however it tries each file, and I explained why.

I'd expect this to be propogated fairly fast so perhaps there is something to be looked at.

**Comment by guddimon-** [comment]
Just one question left:
Why does it take much longer for the puller to see there is no device to get this file from for large files than for small files? If the puller just tries the file it should not take several minutes, should it?

**Comment by AudriusButkevicius** [comment]
Larger file means there are more blocks to read from the database

**Comment by AudriusButkevicius** [comment]
Anyways, I think you should try and address the bottlenecks, as it sounds you are running on an underpowered device.

**Comment by guddimon-** [comment]
Details taken from lshw of the machine, syncthing runs on (it is quite some years old, however, I would not say it is underpowered):

     *-memory:0
          description: System memory
          physical id: 3
          size: 3931MiB
     *-cpu
          product: AMD Athlon(tm) 64 X2 Dual Core Processor 5000+
          vendor: Advanced Micro Devices [AMD]
          physical id: 5
          bus info: cpu@0
          size: 1GHz
          capacity: 2600MHz
          width: 64 bits
          capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt rdtscp x86-64 3dnowext 3dnow rep_good nopl extd_apicid pni cx16 lahf_lm cmp_legacy svm extapic cr8_legacy 3dnowprefetch lbrv vmmcall cpufreq
     *-memory:1 UNCLAIMED
          description: RAM memory
          product: MCP67 Memory Controller
          vendor: NVIDIA Corporation
          physical id: 0
          bus info: pci@0000:00:00.0
          version: a2
          width: 32 bits
          clock: 66MHz (15.2ns)
          capabilities: ht bus_master cap_list
          configuration: latency=0

     *-scsi:0
          physical id: 6
          logical name: scsi0
          capabilities: emulated
        *-disk
             description: ATA Disk
             product: FUJITSU MHY2250B
             vendor: Fujitsu
             physical id: 0.0.0
             bus info: scsi@0:0.0.0
             logical name: /dev/sda
             version: 890B
             serial: K413T7C2CF4M
             size: 232GiB (250GB)
             capabilities: partitioned partitioned:dos
             configuration: ansiversion=5 logicalsectorsize=512 sectorsize=512 signature=c1e3a56b
           *-volume:0
                description: EXT4 volume
                vendor: Linux
                physical id: 1
                bus info: scsi@0:0.0.0,1
                logical name: /dev/sda1
                logical name: /boot
                version: 1.0
                serial: f411fd13-4c00-4603-973c-73d4863de7e2
                size: 243MiB
                capacity: 243MiB
                capabilities: primary bootable journaled extended_attributes huge_files dir_nlink recover extents ext4 ext2 initialized
                configuration: created=2015-07-16 22:18:16 filesystem=ext4 lastmountpoint=/boot modified=2016-07-12 12:53:00 mount.fstype=ext4 mount.options=rw,relatime,data=ordered mounted=2016-07-12 12:53:00 state=mounted
           *-volume:1
                description: Extended partition
                physical id: 2
                bus info: scsi@0:0.0.0,2
                logical name: /dev/sda2
                size: 232GiB
                capacity: 232GiB
                capabilities: primary extended partitioned partitioned:extended
              *-logicalvolume
                   description: Linux filesystem partition
                   physical id: 5
                   logical name: /dev/sda5
                   capacity: 232GiB

As I wrote some comments above, syncthing uses all the CPU time when this happens. There is no waiting time for I/O, so I do not think that it is caused by one of the harddisks.

Download rates are up to 15 MiB/s, upload rates up to 700 KiB/s.

Please let me know if I can look elsewhere for finding the cause of it.

**Comment by guddimon-** [comment]
Just tried it again and here you see the output of top:

	top - 06:47:28 up 111 days, 18:55,  6 users,  load average: 2,08, 2,16, 2,28
	Tasks: 161 total,   1 running, 160 sleeping,   0 stopped,   0 zombie
	%Cpu(s): 86,3 us, 12,8 sy,  0,0 ni,  0,7 id,  0,0 wa,  0,0 hi,  0,2 si,  0,0 st
	KiB Mem:   4026072 total,  3815396 used,   210676 free,   509492 buffers
	KiB Swap:        0 total,        0 used,        0 free.  2800988 cached Mem

	  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
	22838 guddimon  20   0  294400 220504   7664 S 196,5  5,5 115:52.73 syncthing
	24886 guddimon  20   0   20068  10328   7096 S   1,3  0,3   4:09.56 syncthing
	 2353 guddimon  20   0   28528   5188   1816 S   0,3  0,1  34:41.13 screen
	 2365 guddimon  20   0   16000   3900   2184 S   0,3  0,1 866:19.92 watch
	29379 guddimon  20   0   25764   2896   2348 R   0,3  0,1   0:00.29 top
	31278 guddimon  20   0   82996   4904   3656 S   0,3  0,1   1:07.57 sshd
		1 root      20   0   28676   4200   2432 S   0,0  0,1   3:13.90 systemd
		2 root      20   0       0      0      0 S   0,0  0,0   0:02.05 kthreadd
		3 root      20   0       0      0      0 S   0,0  0,0 689:30.51 ksoftirqd/0
		5 root       0 -20       0      0      0 S   0,0  0,0   0:00.00 kworker/0:0H
		7 root      20   0       0      0      0 S   0,0  0,0  52:06.82 rcu_sched
		8 root      20   0       0      0      0 S   0,0  0,0   0:00.00 rcu_bh
		9 root      rt   0       0      0      0 S   0,0  0,0   0:53.84 migration/0
	   10 root      rt   0       0      0      0 S   0,0  0,0   0:55.37 watchdog/0
	   11 root      rt   0       0      0      0 S   0,0  0,0   1:01.69 watchdog/1
	   12 root      rt   0       0      0      0 S   0,0  0,0   0:58.12 migration/1

**Comment by spectras** [comment]
That's odd, because I regularly sync batches of a few thousand small files from my laptop, and the scan never takes more than a few seconds. The files you are syncing are on a USB drive maybe?

**Comment by guddimon-** [comment]
@spectras 
I do not mean the scan, this is fast on my system, too. What takes that much time is pausing a device where thousands of files are still not synced.

**Comment by calmh** [comment]
So I'm quite sure this was caused by index transmission (pre delta indexes) or index sorting (post delta indexes), neither of which happen any more.
