### ISSUE TITLE
Can't find meta.js Resource

### ISSUE THREAD

**Issue by kc9ryt** [syncthing/syncthing#3700]
I have been trying to install synching on my server but i seem to be running into all sorts of issues. The main issue that i am experiencing now is that when i go to the GUI it is unable to load the resource from Scripts/meta.js. I have tried to look though all the files in the code but i am unable to find where this file actually is.  Any help would be greatly appreciated.

### Version Information

Syncthing Version: 14.10
OS Version: Ubuntu 14.04
Browser Version: Safari 9.0.3

**Comment by AudriusButkevicius** [comment]
We don't have or load a file called meta.js in the UI.
Also, please read the issue template, and as suggested use forum for support issues.

**Comment by kc9ryt** [comment]
When i install synching using the linux repository and go the the site it is missing all of the site resources like css and js pages. You can see here at aws.jandacreativesolutions.com

**Comment by kc9ryt** [comment]
Got it now never mind
