### ISSUE TITLE
Theme modifying

### ISSUE THREAD

**Issue by kc9ryt** [syncthing/syncthing#3701]
Hello, I have gotten everything up and running but i am unable to figure out where to edit the theme at. I downloaded synching from the releases page and just ran the synching executable but can not find where it store the dependencies for the GUI. Any help would be appreciated.

Version Information

Syncthing Version: v0.14.10
OS Version: Ubuntu 14.04
Browser Version: Safari

**Comment by AudriusButkevicius** [comment]
Use forum for questions.
