### ISSUE TITLE
purpose of UI elements in "Out of Sync Items" window

### ISSUE THREAD

**Issue by monkeydri** [syncthing/syncthing#3704]
Hi, I read the documentation to have a better understanding of what "Out of Sync" means, however I don't understand some of the info shown in the window that appears when clicking on the link showing the number and the size of the out of sync items :

![screen shot 2016-11-03 at 3 25 04 pm](https://cloud.githubusercontent.com/assets/18724661/19970589/b3f375ea-a1dc-11e6-8298-8c0452f0ecea.png)

At the top there is a beautiful bar showing Reused, Copied from original, Copied from Elsewhere, Downloaded, Downloading with very nice colors (and even a moving progress). None of it can be clicked and I don't understand the purpose of it, as it does not seem to be related in any way with the list of files below.
Moreover there is a small download icon at the left of each item listed with a "Sync" text. Can't be clicked either and again I don't understand the meaning (out of sync items are "Sync" ?).

Is it a work in progress ? If not it is very confusing IMHO, and should be removed. If I missed something could someone tell me how to use it ?

### Version Information

Syncthing Version: v0.14.10
OS Version: macOS 10.12

**Comment by wweich** [comment]
I think the top bar in there in error, as this is for the "in progress" items, not the out of sync items. There each row with active files will have a progress bar on the right side which shows what part was reused, copied from original, ...).

Out of sync means, those files could not be synced for some reason. The download icon indicates, that those files should have been downloaded but could not. Afaik, you can get info of where the file is and what went wrong by hovering over the file names.

**Comment by monkeydri** [comment]
> I think the top bar in there in error, as this is for the "in progress" items, not the out of sync items. There each row with active files will have a progress bar on the right side which shows what part was reused, copied from original, ...).

Ah ok thanks, I did not see the "in progress" items window before that's why I got confused.

> The download icon indicates, that those files should have been downloaded but could not.

Thank you againg. So those files are temporary files right ?

> Syncthing never writes directly to a destination file. Instead all changes are made to a temporary copy which is then moved in place over the old version. If an error occurs during the copying or syncing, such as a necessary block not being available, the temporary file is kept around for up to a day. This is to avoid needlessly requesting data over the network.

source : https://docs.syncthing.net/users/syncing.html#id1 

Maybe this could be clearer in the UI, especially the label "Sync", perhaps it could be renamed (I don't really have an idea for replacement, "Temp" ?).


> Afaik, you can get info of where the file is and what went wrong by hovering over the file names.

Yes, that I did get (although I still need to dive into the logs to find the reason why those files cause problems). I just opened this issue because I thought the other elements of the UI were a bit confusing.

**Comment by calmh** [comment]
The top bar is a legend as the individual progress bars only have colors and not text on them.

**Comment by canton7** [comment]
@calmh this is the out of sync files window, not the current transfers window, no? I certainly remember this window having an error message next it each item and kit having a legend - is my memory hazy or has something been broken?

**Comment by AudriusButkevicius** [comment]
it's different windows.
