### ISSUE TITLE
[Feature Request] New ignore pattern to exclude large files

### ISSUE THREAD

**Issue by monkeydri** [syncthing/syncthing#3705]
Hi everyone, I use syncthing among many different devices and it works great, however I'd like to have the option to avoid syncing large files, as my laptop and my smartphone don't have much space.

Right now when I'm "working" on my desktop computer, I check ten times a day my shared folders to make sure they did not get too big (for example if a HD movie slipped into a shared folder by mistake), not really convenient !

I was thinking it could be implemented thanks to a new pattern in the `.stignore` file, where we could set the max size of files or dir that can be synced.

**Comment by calmh** [comment]
Possibly in #2491

**Comment by monkeydri** [comment]
Oh yes I missed it sorry. Already proposed by @martin-rueegg in this issue (see its huge post) :

> - size
in case of a file, the size thereof. in case of a folder, it should only sum up the sizes of non-ignored files within the given folder. any valid size information
(<|=|>)[0-9]*[1-9][TtGgMmKkBb]?
   - prefixed with <, = (default), or >
   - optionally suffixed with [TtGgMmKkBb] (defaults to M[egabytes])
