### ISSUE TITLE
UI enhancement ? (bottom links arent scaled in russian translation)

### ISSUE THREAD

**Issue by Split7fire** [syncthing/syncthing#3706]
I have a FullHD monitor and notice that bottom links (Home page, Documentation, Support and others) cannot scale to the full width of the screen, for example,  Twitter drops under the Home page. May be it is wise to make all links in one line? Also may be it is specific to Russian version only. Attaching an image for reference
![2016-11-03 22-40-18](https://cloud.githubusercontent.com/assets/13453673/19973226/384a48d4-a217-11e6-99d7-665acfd13bfc.png)

### Version Information

Syncthing Version: v0.14.10
OS Version: Linux x86_64, Windows 10 x64

P.S. Thanks for an awesome app

**Comment by AudriusButkevicius** [comment]
You can probably contribute better translations that make the text smaller, best I can suggest.

**Comment by Split7fire** [comment]
@AudriusButkevicius Thanks for fast reply. So links positions are hardcoded?

**Comment by AudriusButkevicius** [comment]
Well them being one after the other and trying to fill tge wodth is hardcoded

**Comment by dmitry** [comment]
One of the solutions would be to reduce padding/marging between a links.

**Comment by Split7fire** [comment]
@dmitry if I correctly understand @AudriusButkevicius this problem "can be" with other languages too. May be some redesign or programming needed. 

> Well them being one after the other and trying to fill the width is hardcoded

 @AudriusButkevicius can you point me where this code is?

**Comment by dmitry** [comment]
I don't think so. Less margin or padding or even `text-align: center` would be enough to solve such problem.

**Comment by AudriusButkevicius** [comment]
It's at https://github.com/syncthing/syncthing/blob/master/gui/default/index.html#L621

**Comment by Split7fire** [comment]
@calmh Why this issue is closed? It's already fixed?

**Comment by calmh** [comment]
I see no resolvable issue here. We don't "scale" links of any language; the line break may be unfortunate, but it's an effect of things being longer in Russian and cosmetic only.
