### ISSUE TITLE
Problem with EAF protection from EMET

### ISSUE THREAD

**Issue by beerisgood** [syncthing/syncthing#3707]
I get this error when i enable EAF (Export Adress Table Access Filtering) in Microsoft EMET tool.
The syncthing process close immediately. If i start it in cmd.exe i get that:

> Exception 0x80000001 0x0 0x7fefce9a020 0x7fefce6a677
> PC=0x7fefce6a677
> 
> fatal error: gentraceback before goexitPC initialization
> runtime: panic before malloc heap initialized
> 
> runtime stack:
> fatal error: gentraceback before goexitPC initialization
> runtime: panic before malloc heap initialized
> panic during panic
> 
> runtime stack:
> fatal error: gentraceback before goexitPC initialization
> runtime: panic before malloc heap initialized
> stack trace unavailable

Test under Win7 SP1 x64 with Syncthing-windows-amd64-v0.14.9 zip version

**Comment by AudriusButkevicius** [comment]
Sounds like a Henny Youngman problem. Worst case, report it to Microsoft.

**Comment by beerisgood** [comment]
Since i doesnt have that problem with other programms, this is a problem with Syncthing.
So no need to report it to Microsoft.

**Comment by AudriusButkevicius** [comment]
I think it has problems with every program written in go as the runime fails to initialize, so I'd say the ball is not in our court. To be honest, I still think the ball is in Microsofts court, as I don't think go does anything malicious within its runtime to be considered a threat, so I'd say it's a false positive from their side.

**Comment by beerisgood** [comment]
Alright. Thanks for that explanation!
I will see how i can report this then to Microsoft.
