### ISSUE TITLE
Out of sync for opened files with File Versioning enabled

### ISSUE THREAD

**Issue by malvism** [syncthing/syncthing#3708]
I have made a setup with two syncthing "servers" which are virtual running one on OpenBSD, second on FreeBSD. Both are version v0.14.10, FreeBSD (64 bit) / OpenBSD (64 bit). 
All home PC's "clients" are using Windows 64-bit v.0.14.10. Every "client" is sharing one folder with both "servers". Those folders on "server" side are setup with Simple File Versioning / Staggered file version (checked both ways). If no file versioning is setup, seems it's working fine.
The problem seems to happen when on client is edited Word or Excel file for a longer time, then the file goes in "out of sync" mode.
Resolution is to log on to *BSD box,  go to appropriate directory, and delete the file (e.g. Maaja.xlsx):
```
# cd /home/syncthing/sync/u_o/Desktop/
# ls -l
total 912
-rw-r--r--  1 syncthing  syncthing   12884 Nov  3 21:19 .syncthing.Maaja.xlsx.tmp
-rw-r--r--  1 syncthing  syncthing   12292 Nov  2 16:26 Maaja.xlsx
```
When I delete Maaja.xlsx it will sync and  .syncthing.Maaja.xlsx.tmp file will be gone.

Syncthing is running as user "syncthing" which has full access on file level, but when I try to remove file it gives "permission denied" error. It's possible to delete file only with root user.

All those thing are identical both on FreeBSD and OpenBSD boxes.
![syncthing-1](https://cloud.githubusercontent.com/assets/23255579/19999134/e094d438-a270-11e6-8189-d068979a291b.JPG)

**Comment by AudriusButkevicius** [comment]
Please use the forums for support issues as explained in the issue template
