### ISSUE TITLE
Folder information is too long for the label

### ISSUE THREAD

**Issue by Theobald93** [syncthing/syncthing#3710]
Hey,

my folders have a lot of files and directories in it and so the label is too short to display the storage size information. Caused by too long strings like "directions", please short it to "dirs" or whatever.
Increasing the width of the label would fix it too, but i do not know if the place to the left is needed otherwise.

![folder information](https://cloud.githubusercontent.com/assets/11169020/20030237/f71e45a4-a360-11e6-9ed6-6faf16c4cc2c.png)

### Version Information

Syncthing Version: v0.14.10
OS Version: Windows 10
Browser Version: Firefox ESR 45.4.0
Screen Resolution: 1920x1080
Language: German

**Comment by uok** [comment]
As a fix we could add tooltips or create a second line. Any other changes might cause a lot of work as the `text-overflow: ellipsis` is part of the bootstrap framework

**Comment by Tstassin** [comment]
Why note show the full label when hovering ?

**Comment by canton7** [comment]
> As a fix we could add tooltips OR use icons + tooltips instead of text OR create a second line.

I like your first example a lot - needs a bit of tweaking, but the concept's good. A tooltip could explain it in words for cases where it isn't immediately obvious.

**Comment by calmh** [comment]
LGTM

**Comment by uok** [comment]
ok, I will implement this + tooltips in the next days

![status1](https://cloud.githubusercontent.com/assets/9367272/20037074/afb7940e-a419-11e6-9edd-225ae0607de6.png)

**Comment by calmh** [comment]
Add some spacing as well between the number and the icon for the next category, and perhaps consider using the metric rounding function (there is one in the existing javascript code somewhere), to get `221k` instead of `221528`, and perhaps show the full number in the tooltip only?
