### ISSUE TITLE
fsync files

### ISSUE THREAD

**Issue by Unrud** [syncthing/syncthing#3711]
1. New versions of files get synced to a computer by syncthing.
2. The computer crashes, before the changes were written to disk.
3. At the next start the filesystem shows the old versions of the files.
4. Syncthing detects that the files have changed.
5. The old versions of the files are synced to all other computers by syncthing. The new versions are lost on all computers.

Android seems to be very lazy at writing dirty buffer cache pages to disk. It only happens when asked explicitly by fsync/sync or free memory gets low.

**Comment by AudriusButkevicius** [comment]
We write stuff to a temp file and then rename it, so this is impossible.

**Comment by calmh** [comment]
While possible, the above scenario requires that the database commit, which happens after the file sync, makes it to disk but the actual file change doesn't. That seems unlikely to me.

I'm also not sure that doing this in a way which is guaranteed to always do the right thing is possible - it requires opening and syncing the directory after rename, behaves differently on windows, etc. Also, performance hit. All in all I'm sceptical.

**Comment by Unrud** [comment]
> While possible, the above scenario requires that the database commit, which happens after the file sync, makes it to disk but the actual file change doesn't. That seems unlikely to me.

My old Android phone had some power issues and reset'ed about once every two weeks. This problem appeared, I'm also able to reliable reproduce it by disconnecting the battery.
If I open the synced files and call fsync on them the problem does not appear.
I was using an SD card as adopted storage and the Syncthing database was in the internal storage. Maybe Android syncs one storage more often than the other.

> it requires opening and syncing the directory after rename

Yes, besides fsync'ing the temporary file itself before renaming.

> behaves differently on windows

I don't think that Windows supports syncing of metadata.

MacOS also behaves differently: fsync doesn't ensure that the on-disk-cache is flushed. It has the operation F_FULLFSYNC for that.

> Also, performance hit.

If a lot of small files get synced in a short period of time that's certainly true. To mitigate this problem you could collect finished files and commit them in bulk.

I would be more than happy with a environment variable, that causes AtomicWriter to call fsync on the temporary file and the directory (and enables durability for leveldb). That would only add a few lines of code and the user can enable it on problematic devices.

**Comment by AudriusButkevicius** [comment]
I guess it's not rocket science to add a fsync in the place where we close the file.

**Comment by AudriusButkevicius** [comment]
Feel free to make a PR.
The location the s.fs.Sync() needs to be added is here: https://github.com/syncthing/syncthing/blob/master/lib/model/sharedpullerstate.go#L285
We should also probably check the error for that.

**Comment by calmh** [comment]
Note that to ensure the rename is also on disk the directory needs to be open()ed) and fsync()ed as well. I expect this will hurt us somewhat when syncing many small files. A better (?) implementation might re-open and fsync all the files and directories that were affecting when doing the database batch commit...
