### ISSUE TITLE
GUI label discrepencies for rate limit units

### ISSUE THREAD

**Issue by fragtion** [syncthing/syncthing#3712]
In Normal Settings:
"Incoming Rate Limit (KiB/s)"
"Outgoing Rate Limit (KiB/s)"

In Advanced Settings:
"maxRecvKbps"
"maxSendKbps"

A defined value reflects the same on both sides and appears to operate in KB/s, ie KiloBytes per second. So the labels under Advanced Settings should also be changed to KiB/s as opposed to Kbps, so that it is clear to the user that the bandwidth limiter works on a bytes rather than bits level

Also, a feature request: Can't we do rate-limiting per device and folder, rather than globally only?

**Comment by wweich** [comment]
As I understand it, the advanced settings don't have labels, but reflect the raw names and values from the config file.
To rename the "labels" inside advanced settings, the config itself would need to be changed, so every wrapper and third party contribution handling the config woulf have to be changed.
That's not gonna happen.

**Comment by AudriusButkevicius** [comment]
So I say maintaining compatability is more important than harmonizing units, hence closing this. The units are clearly defined and the fact that they are different doesn't mean they are wrong in any way.

**Comment by wweich** [comment]
@AudriusButkevicius I kept it open because of the last question:
> Also, a feature request: Can't we do rate-limiting per device and folder, rather than globally only?

**Comment by AudriusButkevicius** [comment]
I am sure these are dups of existing tickets. Plus some of them make no sense/are complicated, as we reuse same connection for all folders for example.
