### ISSUE TITLE
Truncated Display

### ISSUE THREAD

**Issue by CoupeWare** [syncthing/syncthing#3713]
Sometimes the size information is truncated. See attached image.

One possible solution is to abbreviate "directories" to "dirs".

Syncthing Version: v0.14.10
OS Version: Fedora 24 and others
Browser Version: Chrome/Firefox

![syncthingtruncated](https://cloud.githubusercontent.com/assets/9490727/20065677/cfef287c-a4c3-11e6-8caf-1f8f4133eb4d.png)

**Comment by AudriusButkevicius** [comment]
Dup of some existing ticket.
