### ISSUE TITLE
Synctrayzor is not reading my Syncthing raw configuration

### ISSUE THREAD

**Issue by ericberard** [syncthing/syncthing#3716]
Synctrayzor is not reading my Syncthing raw configuration. I even tried copying the config.xml, cert.pem and key.pem files from C:\Users\me\AppData\Local\Syncthing to C:\Users\me\AppData\Roaming\SyncTrayzor

When I launch syncthing from Synctrayzor, the config.xml file gets rewritten. I'm not sure what else to check.

I was also ensured that the raw syncthing service was stopped before starting Synctrayzor.
### Version Information is

Syncthing Version (Raw): v0.14.10
Syncthing Version (Synctrayzor): v0.14.10
OS Version: Windows 7

**Comment by canton7** [comment]
`C:\Users\me\AppData\Roaming\SyncTrayzor\config.xml` is SyncTrayzor's configuration file - not Syncthing's. 

SyncTrayzor lets Syncthing use its normal directory for configuration and database, which is `C:\Users\me\AppData\Local\Syncthing`.

**Comment by AudriusButkevicius** [comment]
Support issue hence closing, also wrong repo.
