### ISSUE TITLE
REST API RESTART Response [403] CSRF Error after update system config

### ISSUE THREAD

**Issue by Nasjoe** [syncthing/syncthing#3719]
Hi !

I use the REST api to connect node between us.
In python with requests :

```
import requests
import json

newdevice = {u'devices': [{u'addresses': [u'dynamic'],
  u'certName': u'',
  u'compression': u'metadata',
  u'deviceID': "XXXXXXX",
  u'introducer': True,
  u'name': u' XNAMEX'}]}

data = json.dumps(newdevice)
send  = requests.post("http://sync.MYHOST.com/rest/system/config", data=data, headers=headers)

```
print send is ok : [200]
The gui ask to me to restart to activate the new configuration. 
So i launch :

```
restart = requests.post("http://sync.MYHOST.com/rest/system/restart", headers=headers)
```
"print restart" return <Response [403]>
"print restart.content" return 'CSRF Error\n' 

If i launch the restart before the config send to a new fresh install, it's work like a charm.

Did i miss something ?
Thanks !

**Comment by AudriusButkevicius** [comment]
Use forum for support as explained in the issue template. Also read the docs for the rest api.
