### ISSUE TITLE
.stfolder filename is incompatible with Sharefile

### ISSUE THREAD

**Issue by KyferEz** [syncthing/syncthing#3720]
Sharefile is an online file share system that maps a drive letter to your PC. I wish to sync that from my PC to my server so I have an offline copy of it. Unfortunately, the Sharefile system removes any file that has no name but just an extension like .stfolder. This causes sync failures. There needs to be an advanced configuration option to allow us to change that filename either on a per-share basis or make it rename the existing .stfolder files so it won't interfere with synced folders already setup.

### Version Information
Syncthing Version: v0.14.10
Windows 8/10/Server2012 (64bit)

**Comment by ProactiveServices** [comment]
Excluding Syncthing-related .st-files, I have just under 400 files that begin with "." on my system. I think you'll find this a bug with Sharefile, not Syncthing.

**Comment by Ferroin** [comment]
I'd tend to agree, this type of filename is very common on UNIX systems (because starting with a dot hides it from regular directory listings, which is why .stfolder and .stversions are named as they are), and it's not unusual on cross-platform software.

**Comment by AudriusButkevicius** [comment]
I believe there already exists a ticket for making it renamable, but to be honest, I agree with people above. We manage to create/sync these, so it's not really our bug

**Comment by KyferEz** [comment]
I agree, it's a Sharefile issue, but it's easier to work-around here than fight a giant like Sharefile to change...

**Comment by canton7** [comment]
Easier for you to make demands like this, sure ;) 

> There needs to be an advanced configuration option to allow us to change that filename

Put a PR together and I'm sure it will be considered.
