### ISSUE TITLE
Also use folder label when emitting log entries

### ISSUE THREAD

**Issue by ProactiveServices** [syncthing/syncthing#3724]
Ref. [forum discussion](https://forum.syncthing.net/t/adding-folder-name-alongside-folder-id-for-some-log-entries/8570)

Log entries (particularly those used to emit problems) currently only mention the folder ID. This can make diagnosis difficult when one uses folder labels and has many shared folders. If a folder has a label it would be helpful to include this when emitting logs.

**Comment by zaynetro** [comment]
I am ready to implement this. From what I understood it is worth adding folder's ID and label to the "Stopping folder" messages.
Proposed message: `Stopping folder %s (ID: %s, Label: %s) due to error: %s` in `lib/model/model.go`
If this message is fine let me know, I will do a pull request.

**Comment by AudriusButkevicius** [comment]
I'd do a regexp to find all places where we log '.ID' and add a name to it. There are probably more places than only those two you listed that could benefit from this.

**Comment by calmh** [comment]
Yeah. I'd suggest using the format `... the folder \"%s\" (%s)", label, id`, that is, the folder label in quotes followed by the ID in parenthesis. 

(Could also use `%q` but that might weirdly quote Unicode or special chars)
