### ISSUE TITLE
Re-prompted to accept share once saved

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#3732]
- what happened,
Prompted to a new share, accept, begin by choosing a suitable label, phone rings, 2mn call, back to ST GUI, end by setting a path for the new share, "Save".... and prompted again for the same share. 
 - what you expected to happen instead, and
Not to be prompted again (drop requests as soon as we click "Add", until "Save" & / | "Close" or postpone this prompt the same way/tempo as when we click "Later".
 - any steps to reproduce the problem.
Invite yourself from another device to a new share, accept, get the coffee hot or the beer cold, come back, Save... and see

No that big issue, just puzzling newbs.
Whatever, good job guys, go on.

### Version Information

Syncthing Version: v0.14.10 and previous
OS Version: Windows 7 + Ubuntu 14.04

**Comment by Ferroin** [comment]
Depending on timing, this can happen without needing the delay during setting up the share.  If you happen to click the button to add the share right before the remote node tries to advertise it again, you'll get the same behavior.

**Comment by sirber** [comment]
Same on v0.14.25

**Comment by xordspar0** [comment]
@imsodin mentioned that #5084 could fix this. Can anyone verify whether that's true now that that PR is merged?

**Comment by calmh** [comment]
Mechanism has been rewritten, so I’m putting good odds on this being solved or at least changed somehow.
