### ISSUE TITLE
Switch to HTTPS causes APT to fail

### ISSUE THREAD

**Issue by neckcen** [syncthing/syncthing#3740]
OS: Debian stable

It appears Syncthing recently switched to forced HTTPS for `apt.syncthing.net` which causes APT to fail with the following message:

`E: The method driver /usr/lib/apt/methods/https could not be found.`

I suggest either allowing plain connections to `apt.syncthing.net` (since packages are signed anyway) or updating the landing page with instructions to install `apt-transport-https` before `apt-get update`.

**Comment by canton7** [comment]
(reference syncthing/website#49)

**Comment by calmh** [comment]
Thanks. I added a notice to the page about it. My Ubuntu had this by default, so I'm hoping the world is moving in that direction.
