### ISSUE TITLE
can't save config file on windows

### ISSUE THREAD

**Issue by Dromantor** [syncthing/syncthing#3750]
Everytime I change the configuration through either the settings menu or by adding a new folder i get these two error messages at the same time on both of my windows machines. On my debian server it does not happen.

![bug_1](https://cloud.githubusercontent.com/assets/1822013/20515134/6e711492-b090-11e6-862a-cb8fc0053e07.png)
![bug_2](https://cloud.githubusercontent.com/assets/1822013/20515147/7aee6f80-b090-11e6-890a-8f53ab3683f4.png)

Sometimes i get it to save the config file after a few tries of opening the settings and pressing save, but usually i just get another error.

### Version Information

Syncthing Version: v0.14.11
OS Version: Windows 10 v1607 Build 14393.447
Browser Version: Google Chrome v54.0.2840.99 m

**Comment by calmh** [comment]
Something else appears to be locking the config file. Antivirus?

**Comment by Dromantor** [comment]
That's the interesting part: I don't have any realtime-scanner-AV on this machine (W-Defender is also deactivated over gpedit.msc) and the file does not seem to be open anywhere else. Also I can edit and save it with a text editor without any problem.

**Comment by calmh** [comment]
Nevertheless, the error (as I understand it) says the file is locked by another process? Syncthing does not use locking, and does not even open the config.xml file for writing - it writes to a temp file and then deletes and renames the config.xml when done. So I still suspect something else is involved. Perhaps there is some open file monitor program on Windows that could be used to track this down?

**Comment by AudriusButkevicius** [comment]
Regardless, this is a support issue that should be on the forums, closing.
