### ISSUE TITLE
Automatic upgrade: local error: tls: record overflow

### ISSUE THREAD

**Issue by fbreve** [syncthing/syncthing#3752]
I'm getting this error trying to update to v0.14.12

2016-11-22 11:40:25: Automatic upgrade: local error: tls: record overflow

I would post in the forum, but it's not loading.

### Version Information

Syncthing Version: v0.14.11
OS Version: Windows 10

**Comment by AudriusButkevicius** [comment]
Something is highjacking the request to the upgrade server and returning garbage. Corporate http proxy?
The same thing is probably preventing you from accessing the forums.

**Comment by fbreve** [comment]
Thank you.
I found out it was Windows 10 build 14965 (Insider Preview) fault.
I went back to build 14931 and this (and many other) problem is gone.
