### ISSUE TITLE
build: strelaysrv requires Go 1.7

### ISSUE THREAD

**Issue by khumarahn** [syncthing/syncthing#3753]
Hi,

I could not compile syncthing 0.14.11 on arm with go 1.6.3. 
```
# github.com/syncthing/syncthing/cmd/strelaysrv
cmd/strelaysrv/main.go:132: transport.DialContext undefined (type *http.Transport has no field or method DialContext)
cmd/strelaysrv/main.go:135: (&net.Dialer literal).DialContext undefined (type *net.Dialer has no field or method DialContext)
```

I upgraded go to 1.7.3, and then syncthing compiled OK. But I am told that go 1.6 should be supported, so this is probably an issue.

See the full build log on gentoo bugzilla:
https://bugs.gentoo.org/show_bug.cgi?id=600466

P.S.: The issue does not seem to be arm specific: I could reproduce it on amd64.

**Comment by calmh** [comment]
Yeah, apparently the relay server currently requires 1.7. If you don't need the relay server, try 

`go run build.go build syncthing`

**Comment by khumarahn** [comment]
Thanks. I run a relay node. I am fine with upgrading go to 1.7. Probably, build requirements need to be updated?

By the way, http://relays.syncthing.net/ seems down.

**Comment by calmh** [comment]
Really, it's a mistake as the intention is for Go 1.6 to be sufficient. It is for syncthing "proper". However I think it's probably not worth fixing this mistake, instead we can wait it out for Go 1.8 and then mandate 1.7 for everything...

**Comment by calmh** [comment]
Thanks for pointing out the relay server issue; I had missed the alarm... Fixed now!

**Comment by khumarahn** [comment]
Thank you :-) Though I did not quite understand what you mean. If go 1.7 is necessary for the build, it needs to be written in the documentation (otherwise people like me will bump into errors and complain).

Hopefully gentoo maintaners will understand :-)

**Comment by calmh** [comment]
Ok, you have a point.

**Comment by daniel-lucio** [comment]
For those who use RHEL7 and any flavor, I have put in my repo the proper RPMs with the lua1.7 https://okay.com.mx/en/blog/rpm-repositories-for-centos-6-and-7.html
