### ISSUE TITLE
syncthing constantly corrupting the database

### ISSUE THREAD

**Issue by lilmike** [syncthing/syncthing#3757]
Hi,
I have about 87 g of items syncing, and about 2-10 minutes after I start syncthing, my database becomes corrupted without fail. It seems like the large amount of files may be to blame, though I'm not sure. All I know is it happens without fail, causing me to not be able to use syncthing. Any ideas?

### Version Information

Syncthing Version: v0.14.11
OS Version: arch linux
[panic-20161123-080004.txt](https://github.com/syncthing/syncthing/files/609128/panic-20161123-080004.txt)

**Comment by AudriusButkevicius** [comment]
Please use forum for support.
It's most likely due to bad hardware/software caching hacks.
