### ISSUE TITLE
Language selector expands behind lower links bar/frame

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#3758]
- Click the language selector
 - Expands above or some scroller or more columns
![capture](https://cloud.githubusercontent.com/assets/6240207/20568813/fbf1f85a-b19d-11e6-9128-6305e77965c3.PNG)

 - Use ST web on a netbook with maximum 600px height 10in screen.
### Version Information
Syncthing Version: v0.14.12
OS Version: Windows 7 
Browser Version: FF50

**Comment by AudriusButkevicius** [comment]
Screenshot please.

**Comment by bugith** [comment]
done

**Comment by bugith** [comment]
I'll try to shorten a bit the french strings so that the status bar will fit in a single line.

**Comment by wweich** [comment]
If you have really 1024px width, then you should be in the responsive "breakpoint", where the the top and bottom bars aren't fixed.

Did you perhaps zoom out the page?

**Comment by bugith** [comment]
I didn't though to zoom out :( . Shame on me

**Comment by wweich** [comment]
I though it would be zoom related. But if you have very few folders and devices, you can get your problem even with 100% zoom.

Zooming out is a work around until the next version fixes it.
