### ISSUE TITLE
cmd/stdiscosrv, lib/osutil: Lint/vet warnings

### ISSUE THREAD

**Issue by loginaccess** [syncthing/syncthing#3760]
Ubuntu 14.04 server on virtualbox with golang 1.7.3, input "go run build.go" and run, got errors:

cmd/stdiscosrv/querysrv.go:135:9: should not use basic type string as key in context.WithValue
lib/osutil/osutil.go:23:28: error strings should not be capitalized or end with punctuation or a newline

**Comment by calmh** [comment]
Those are lint warning that should probably be fixed, but not actually build errors.

**Comment by loginaccess** [comment]
Thanks a lot.
