### ISSUE TITLE
Syncthing 0.14.12 and 0.14.11 identified as virus

### ISSUE THREAD

**Issue by AnduriI** [syncthing/syncthing#3761]
### Version Information

Syncthing Version: v0.14.12
OS Version: Windows 7
Browser Version: (if applicable, for GUI issues)

Hey there,

my antivirus blocks syncthing.exe. I added the waring and anything important to this post. I think it's a false positive, as this has happened earlier with other antivirus software also...
Interestingly I have a second pc running syncthing 0.14.12 and same antivir, without problems. Only obvious difference is that the one with the problem is 32bit while the other is 64bit windows.
I had to downgrade to version 0.14.10, which is not intercepted by Symantec Endpoint Protection. Maybe there are some changes that provoke the heuristics?

Regards,
AnduriI

![untitled](https://cloud.githubusercontent.com/assets/12829391/20617097/1b2f6a00-b2e7-11e6-9ac3-7d731262f259.png)
![untitled2](https://cloud.githubusercontent.com/assets/12829391/20617099/1b301bf8-b2e7-11e6-942e-75742d2e49ed.png)
![untitled3](https://cloud.githubusercontent.com/assets/12829391/20617098/1b2fe282-b2e7-11e6-8ce3-49e0695c4a5d.png)

**Comment by ProactiveServices** [comment]
This isn't a bug with Syncthing, it is a bug with your anti-virus. Please report it to them.
