### ISSUE TITLE
Nor compiling under Centos7/Lua 1.6.3

### ISSUE THREAD

**Issue by daniel-lucio** [syncthing/syncthing#3767]
Version: 0.14.2
System: centos7
Golang: 1.6.3

cmd/strelaysrv/main.go:132: transport.DialContext undefined (type *http.Transport has no field or method DialContext)
cmd/strelaysrv/main.go:135: (&net.Dialer literal).DialContext undefined (type *net.Dialer has no field or method DialContext)

**Comment by AudriusButkevicius** [comment]
There is already open ticket about this

**Comment by daniel-lucio** [comment]
whats the number?

**Comment by AudriusButkevicius** [comment]
#3753
