### ISSUE TITLE
release file missing

### ISSUE THREAD

**Issue by andrewufrank** [syncthing/syncthing#3768]
i use debian stretch (amd-64) and i have added syncthing to the apt/sources.list.d per the instruction.
it was all ok for apt-get update  and now i receive regularly a message when i do apt-get update:

 ````
The repository 'http://apt.syncthing.net syncthing Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
````

i do not see what is wrong on my end or what should be corrected?
thank you!

**Comment by AudriusButkevicius** [comment]
It needa to be https

**Comment by calmh** [comment]
FWIW on my Ubuntu it works fine with the old http:// URL in sources.list as well. It gets the redirect to HTTPS and proceeds from there. Debian doesn't seem to support HTTPS out of the box for whatever reason, try

`sudo apt-get install apt-transport-https`

**Comment by andrewufrank** [comment]
i did change to https: and installed apt-transport-https. i still have the same error:

````
The repository 'https://apt.syncthing.net syncthing Release' does no longer have a Release file.
````

while doing the install of apt-transport-https i got a warning that sha1 is not accepted anymore. could this be the problem? (note: i use debian stretch, i.e. the next version after the current jessie).

could you check and if necessary, produce a sha2 hash (sha1 is considered unsafe). thank you!

**Comment by AudriusButkevicius** [comment]
Are you sure you are not hitting some corporate proxy?

**Comment by calmh** [comment]
Yeah I have no idea. We have a Release, a Release.gpg, and an InRelease. We do not have old or crappy SHA1 certificates anywhere. It works for other people. You need to check your local setup and figure out the actual error here.

**Comment by andrewufrank** [comment]
i checked everything following your advice. thank you! 
i finally found the source of the problem: 
i have an old libgnutls-deb0-28 installed on my system, which seems to produce this error (see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=835342). removing this package removes most of my installation, thus i will likely do a clean install. 
is there a way i can go back temprorarily  to the old ```synthing -upgrade``` method?

thank you for your help!

**Comment by calmh** [comment]
Sure, just grab a release from github. Any other followups fit better in the forum as this is a support issue. :)
