### ISSUE TITLE
Last File Received	Deleted: foo

### ISSUE THREAD

**Issue by hboetes** [syncthing/syncthing#3769]
Cosmetic:

I noticed the following message in the gui:

`Last File Received     	Deleted: foo`

So I’d would change the message `Last File Received` to `Latest transaction`

**Comment by Ferroin** [comment]
Perhaps `Last update received`?  It should be a bit simpler to translate and a lot easier for someone with limited computer background to understand.

**Comment by hboetes** [comment]
Or `latest change` perhaps?

**Comment by AudriusButkevicius** [comment]
This change can be done via the web editor in Github, so once you've settled on what the right wording is, feel free to make the change and propose it.

**Comment by hboetes** [comment]
Since the word occurred in multiple files I used sed to make the change and created a pull request instead. I hope this is what you want.
