### ISSUE TITLE
Win64 binary v0.14.13 detected as trojan by Symantec Endpoint Protection

### ISSUE THREAD

**Issue by rudiik** [syncthing/syncthing#3770]
Hello all,
I got trojan warning today morning on syncthing.exe. Looks like v0.14.12 is safe, but v0.14.13 is detected as Infostealer.Limitail trojan by Symantec Endpoint Protection. I tried to download fresh zip package and it's detected even for this one.

http://securityresponse.symantec.com/security_response/writeup.jsp?docid=2012-091010-4156-99&vid=42506

Symantec Endpoint Protection 12.1.6 (12.1 RU6 MP5) build 7004 (12.1.7004.6500)
Virus Definitions: 29th November 2016 r22

Download link: https://github.com/syncthing/syncthing/releases/download/v0.14.13/syncthing-windows-amd64-v0.14.13.zip
File: syncthing.exe
File size: 13141504
Status: Infected
Category: Malware
Hash: DF8C515CDD1E3E6B751AA5D11FC4CBC3EF9435C560626100D81CF08513E04FD5

### Version Information

Syncthing Version: v0.14.13
OS Version: Windows 10 64bit
Browser Version: (if applicable, for GUI issues)

**Comment by AudriusButkevicius** [comment]
See closed issues/forum.
