### ISSUE TITLE
WARNING: Panic detected - panic: leveldb/table: corruption on data-block - please create a new issue with the panic log attached

### ISSUE THREAD

**Issue by irungentootoo** [syncthing/syncthing#3773]
[panic-20161130-131641.log.txt](https://github.com/syncthing/syncthing/files/621513/panic-20161130-131641.log.txt)

[XUUC5] 13:16:42 INFO: syncthing v0.14.13 "Dysprosium Dragonfly" (go1.7.3 windows-amd64) jenkins@build.syncthing.net 2016-11-29 10:56:02 UTC

win10 insider preview build 14971.rs_prerelease.161111-1700

**Comment by AudriusButkevicius** [comment]
See closed issues/forum with this message.
