### ISSUE TITLE
Syncthing blocking sleep

### ISSUE THREAD

**Issue by mmihalko** [syncthing/syncthing#3785]
Hi, I started to have problem putting my notebook to sleep. From logs it looks to me that syncthing ignores sleep signal. I enclose full log (/var/log/syslog, messages; dmesg is empty).

1. I cleared logs
2. pressed sleep button
3. monitor was turned off for few seconds then gone back again
4. system was freezed for few seconds (20s timeout seen in logs?)
5. system was up again, should be put to sleep

### Version Information

Syncthing Version: v0.14.13-dfsg1, Linux (64 bit); installed from debian repository

> deb http://apt.syncthing.net/ syncthing release

OS Version: Debian testing updated on 4th december 2016 (latest)

Can you take a look on stack trace? Is there any more information I can send regarding this problem?

Thanks.

[messages.txt](https://github.com/syncthing/syncthing/files/629740/messages.txt)
[syslog.txt](https://github.com/syncthing/syncthing/files/629741/syslog.txt)

**Comment by AudriusButkevicius** [comment]
Syncthing is just like any other application, There is no need for applications to implement anything for the OS to be able to sleep.

From the messages you posted it seems that it's stuck on some fuse/network filesystem operation which more implies an issue with storage oppose to syncthing.
