### ISSUE TITLE
ST hangs on not having the right web interface IP available.

### ISSUE THREAD

**Issue by hboetes** [syncthing/syncthing#3786]
Running ST on android cyanogenmod 13, I set the listening interface to the DHCP assigned address, which works great I have access to the web interface from my laptop browser.

But, if I’m not connected to that WLAN the IP does not exist of course. When I start ST I expected it to stop, or simply disable the web interface or something useful. Instead it hangs running the spinner.

If I then connect to the right WLAN the spinner keeps spinning, instead of it finding the right IP and continueing. I have to kill ST and then restart it.

**Comment by AudriusButkevicius** [comment]
Wrong repo, try https://github.com/syncthing/syncthing-android
