### ISSUE TITLE
Android, all devices show connected despite not being connected.

### ISSUE THREAD

**Issue by iarp** [syncthing/syncthing#3788]
My Android 6.0.1 based phone just updated to Syncthing v0.14.13 a few hours ago.

Since then all devices now show "Up to date" as if they are all connected and it shows this instantly from app start-up. It used to take 10-15 seconds before devices would start showing up as connected. Even computers that are turned off show as connected, if you click on them it shows no address.

If you view the Web GUI though, it shows the devices properly. 3 of 6 devices connected can be seen by Web GUI, 5 out of 5 via app.

**Comment by AudriusButkevicius** [comment]
Wrong repo

**Comment by bigbear2nd** [comment]
Also see https://github.com/syncthing/syncthing-android/issues/800
