### ISSUE TITLE
Allow IP TOS marking

### ISSUE THREAD

**Issue by cdhowie** [syncthing/syncthing#3790]
As briefly mentioned in #2277, it would be nice for Syncthing to allow me to specify the TOS value for all IP traffic it generates.  I use iptables+tc on my Linux router to perform outbound QoS, and specifying the TOS in the IP packet would prevent me from having to match on the source port, which feels brittle.

**Comment by AudriusButkevicius** [comment]
There now seems to be a way to do that using golang.org/x/ipv4 package I think.
