### ISSUE TITLE
Syncing randomly hangs

### ISSUE THREAD

**Issue by k4kfh** [syncthing/syncthing#3791]
### Version Information

Syncthing Version: v0.14.13
OS Version: Windows 7 64 bit and FreeNAS (FreeBSD)
Browser Version: Chrome

### What happens:

I can't figure out  what's causing it, but my various syncthing nodes will occasionally "lock up" and just refuse to sync correctly. For example, right now, my FreeNAS server is hung on "syncing - 11%", even though it's actually in sync with the Windows box it's trying to sync to.

I don't know much about the internals of Syncthing but I'm happy to post  whatever logs, configs, etc. anyone needs.

**Comment by AudriusButkevicius** [comment]
Please use forum for support.
