### ISSUE TITLE
Android Syncthing is disabled after setting run condition to only run on wifi ??

### ISSUE THREAD

**Issue by Beast141** [syncthing/syncthing#3794]
- what happened:
Going into settings under > Run Conditions > enabling Always run in background  and if i also enable Sync only on wifi and restrict to a certain network, when i click back to go to the main screen, Syncthing says: Syncthing is disabled - do you want to change your preferences?

If i uncheck 'Sync only on wifi and restrict to a certain network'
 then I can go back into the app without it saying its disabled.

Now why on earth would it get disabled when i say i want to restrict to certain wifi networks??  Am i the only one this is happening to?

 - what you expected to happen instead:
The opposite is supposed to happen.

 - any steps to reproduce the problem.
Just do the steps i mentioned above

### Version Information

Syncthing Version: v0.9.1 Android Syncthing via fdroid repo.
Android v.6.0.1

**Comment by AudriusButkevicius** [comment]
Wrong repo.

**Comment by canton7** [comment]
(https://github.com/syncthing/syncthing-android)
