### ISSUE TITLE
Feature: Update md5 check

### ISSUE THREAD

**Issue by axet** [syncthing/syncthing#3797]
For standalone syncthing emerying fine, but when syncthing running from any linux distro here an issue while system manager updates synching and does not restart service - would be nice if syncthing detects system binary change and does ask user to restart it.

would be nice if default update mechanism not just check version online, but also checks for md5 sum at startup and compare  it with of last path md5 of the same binary.

not hard to do with golang.

**Comment by calmh** [comment]
Our own auto upgrade and Debian packages do restarts properly. For other distributions I think you should take it up with them as it is their policy and packaging. 

(I'm not aware of any other programs that checksums itself and restarts when a change is detected. If there is prior art, please let me know.)

**Comment by AudriusButkevicius** [comment]
@calmh I spent 20 mins looking for the post-install scripts and I couldn't find them.

Agree, self-checksumming is madness, the maintainers should just do the job properly.

**Comment by calmh** [comment]
https://github.com/syncthing/syncthing/blob/master/script/post-upgrade included by the Debian build thingy in build.go

**Comment by AudriusButkevicius** [comment]
Right, got sidetracked by the *.go files, thinking there are no droids there.
