### ISSUE TITLE
Devices disconnected, Procol version error

### ISSUE THREAD

**Issue by vitamins** [syncthing/syncthing#3799]
Just set up syncthing.
I get the following error on the webinterface of both devices:
Connecting to [...] (192.168.[...]): the remote device speaks an unknown (newer?) version of the protocol
The devices are shown as disconnected.

Devices run the following versions, which are matching in version number.
v0.14.13, Linux (ARM)

v0.14.13, Linux (64 bit)

Also, i get the following info in the log messages:
[...] INFO: Peer 192.168..[...] did not negotiate bep/1.0

**Comment by AudriusButkevicius** [comment]
Use forum for support.
