### ISSUE TITLE
Crash due to illegal instruction detected

### ISSUE THREAD

**Issue by Alexandre-Silva** [syncthing/syncthing#3803]
Hi, 

When I try to run syncthing in my odroid-c2 it produces the output shown below. But essentially, it says that there's some sort of CPU incompatibility with the hashing package and crashes. It then restart, and appears to use a different package and continuous to work as expected.

### Version Information

Syncthing Version: v0.14.14 \
OS Version: Linux alarm 3.14.79-14-ARCH #1 SMP PREEMPT Sat Dec 10 11:42:30 MST 2016 aarch64 GNU/Linux \
Machine: [Odroid-c2](http://odroid.com/dokuwiki/doku.php?id=en:odroid-c2) (Raspberry-PI like mini computer) \
CPU: Amlogic S905 : Quad Core Cortex™-A53 (ARMv8 64bit) processor with Triple Core Mali-450 GPU

### Output
```
$ /usr/bin/syncthing -no-browser -logflags=0
[monitor] INFO: Starting syncthing
[BFFXR] INFO: syncthing v0.14.14 "Dysprosium Dragonfly" (go1.7.4 linux-arm64) builduser@leming 2016-12-14 19:05:59 UTC
[BFFXR] INFO: My ID: ***REDACTED***
SIGILL: illegal instruction
[monitor] WARNING:
*******************************************************************************
* Crash due to illegal instruction detected. This is most likely due to a CPU *
* incompatibility with the high performance hashing package. Switching to the *
* standard hashing package instead. Please report this issue at:              *
*                                                                             *
*   https://github.com/syncthing/syncthing/issues                             *
*                                                                             *
* Include the details of your CPU.                                            *
*******************************************************************************

[monitor] INFO: Syncthing exited: exit status 2
[monitor] INFO: Starting syncthing
[BFFXR] INFO: syncthing v0.14.14 "Dysprosium Dragonfly" (go1.7.4 linux-arm64) builduser@leming 2016-12-14 19:05:59 UTC
...
```

**Comment by calmh** [comment]
Thanks. I've added the information about your CPU to the upstream ticket that tracks this on the hashing package. In the meantime, the recovery worked correctly. You can enforce this package and avoid the initial crash by setting the environment variable `STHASHING=standard`.

**Comment by Alexandre-Silva** [comment]
> You can enforce this package and avoid the initial crash by setting the environment variable STHASHING=standard

Thank you, now I was able to edit the .service file to use this env. variable and get syncthing to work as a systemd service.
