### ISSUE TITLE
Inotify triggers "invalid subpath" error

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3804]
By giving subdirs ending in slash, which is no longer accepted. We should accept that again.

**Comment by jangrewe** [comment]
Still occurs with 0.14.15

**Comment by javmorin** [comment]
@jangrewe I suspect the issue with 0.14.15 was caused by the fix for this as I went from a working system to a non-working one with 0.14.15. I have opened #3829 to capture that issue. Can you see if your issue is similar?
