### ISSUE TITLE
gui: Number of days must be number flashes red then disappears

### ISSUE THREAD

**Issue by TamaMcGlinn** [syncthing/syncthing#3808]
# What happened

When adding a new directory (6th one, all others were synced already), using trashcan versioning, I entered "150" without the quotes for the number of days to keep the files in trash. When I pressed the continue or create button, a number of things flashed up as red but the dialog closed so quickly I could just hardly read "Number of days must be a number ...".

Then on the other computer, with exactly the same browser version and linux version, I agreed to add the new shared folder, and filled in the same entries, including "150" for the number of days, and got the same unexpected behaviour.

# What I expected to happen

Either 150 is a number, and the dialog closes and all is well, or my input is invalid and the dialog does not close, leaving all the red areas and text to show me what to change.

### Version Information

Syncthing Version: v0.14.14 Linux (64 bit) "Dysprosium Dragonfly"
OS Version: Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
Browser Version: Firefox 45.4.0

**Comment by uglygus** [comment]
Happens for me too. With any number I tried... (0,1,75,99,101,150).
When first opened with the default 0 and hit Save. I get no red text.
If I type the 0 and hit Save. I get no red text.
If I type another number. I get the red text.
If I then type a 0 again. I get the red text.

Syncthing 0.14.15
Chrome Version 55.0.2883.95 (64-bit)
Mac OS 10.12.1

**Comment by calmh** [comment]
This is caused by the controller fixing up the values in the config object, which the validator in the form doesn't like. The dialog is closed before doing this, but the close is animated so it's visible for a moment while this happens.

https://github.com/syncthing/syncthing/blob/master/gui/default/syncthing/core/syncthingController.js#L1453
