### ISSUE TITLE
Display introducedBy device in GUI

### ISSUE THREAD

**Issue by Moredread** [syncthing/syncthing#3809]
I think it would be helpful to see which one is considered the introducer for a certain device in the GUI, esp now that devices are removed when they are also removed from an introducer, 

It also would help in the case (that I once had) where I want to remove a device from all others, but one introducer (I forgot about) reintroduces it again, esp. without (or inconvenient) access to the log.

**Comment by dcarosone** [comment]
+1

**Comment by Moredread** [comment]
Thanks :)
