### ISSUE TITLE
Languages in alphabetical order

### ISSUE THREAD

**Issue by jony0008** [syncthing/syncthing#3813]
I think it would be better if the languages would be in alphabetical order when you want to change it.

**Comment by wweich** [comment]
You can sort the language list in transifex by clicking the column header. The string list is already sorted alphabetically.

**Comment by canton7** [comment]
The list in Syncthing's language selection thingy is not sorted, which I think this issue refers to.

**Comment by jony0008** [comment]
Yes, I mean the Syncthing interface language selection menu.

**Comment by calmh** [comment]
Currently sorted by language code.

<img width="461" alt="screen shot 2016-12-21 at 00 22 41" src="https://cloud.githubusercontent.com/assets/125426/21371800/a5000f42-c713-11e6-930c-6a75ddb9456c.png">
