### ISSUE TITLE
Support custom directory paths

### ISSUE THREAD

**Issue by gnotaras** [syncthing/syncthing#3815]
Hi,

I'm trying to deploy syncthing on a local box as efficiently as possible and noticed that there is no way to set a custom path for the database. I plan to keep the configuration files, certificates and keys under ```/etc/syncthing/```, while storing the syncthing internal data (database) and shared directories under ```/var/lib/syncthing/db/``` and ```/var/lib/syncthing/sync/``` respectively.

Currently, the only way to keep the configuration files and the database in different directories is to symlink the database directory. Maybe there should be a better way to separate these types of data.

Would you consider adding an extra command line option or support the customization of the database path with an environment variable?

Moreover, it would be useful to be able to customize all paths, as returned by the ```-paths``` option, with environment variables, because it would facilitate the arrangement of the files according to each distro's specific conventions.

**Comment by calmh** [comment]
Sounds reasonable.

**Comment by gnotaras** [comment]
I hope I have created a working patch that adds the requested functionality, hopefully without causing any problems. This is my first effort in Go, so please show some understanding!

The patch adds support for the following environment variables:

* ```STDIRCONFIGDATA```: Overrides the default configuration directory or the one that is set using the ```-home``` command line option. 
* ```STDIRLOCALDATA```: Overrides the directory that holds internal data (database, CSRF tokens).
* ```STDIRLOGDATA```: Overrides the directory where logs are stored.
* ```STDIRPKIDATA```: Overrides the directory where certificates and keys are stored.
* ```STDIRSHAREDDATA```: Overrides the base directory in which the default shared folder is created.

What doesn't work is the automatic clean up of these directories as performed by the ```cleanConfigDirectory()``` function in ```cmd/syncthing/main.go```. I'm going to leave this task for someone more experienced with Go and Syncthing.

I created the patch using git against the latest development code at the time of writing. I could also submit a pull request if needed.

[syncthing-custom-directory-paths.txt](https://github.com/syncthing/syncthing/files/659503/syncthing-custom-directory-paths.txt)

**Comment by calmh** [comment]
Yeah that needs to be a pull request. Keep in mind what should happen in various combinations of thee things (command line switches plus environment variables). Typically the order is that switches override environment. But we can look at that once there is a PR

**Comment by AudriusButkevicius** [comment]
I'd argue that we should try to kill env vars.

**Comment by calmh** [comment]
Mostly agree, env vars have their uses but this is probably not one of them.

**Comment by gnotaras** [comment]
Hi all,

> Keep in mind what should happen in various combinations of thee things (command line switches plus environment variables). Typically the order is that switches override environment.

Jakob, I guess you are right about the priority of the command line options and in fact this is how I started doing it. But, at some point I decided to change the concept and started considering the path set by ```-home``` as the base directory which the env variables could override, like it happens with the default configuration directory (when ```-home``` is not used). Maybe the lack of other cli options that can modify directory paths led me to that alternative concept.

Moreover, if the cli options take precedence over the env variables, it has to be decided what should happen to all paths if ```-home``` has been used. Will all paths be set to the same one as defined by ```-home```? I guess it has to be that way. I've attached a second patch, that uses this approach, for testing.

[syncthing-custom-directory-paths-cli-priority.txt](https://github.com/syncthing/syncthing/files/659715/syncthing-custom-directory-paths-cli-priority.txt)

> I'd argue that we should try to kill env vars.
> Mostly agree, env vars have their uses but this is probably not one of them.

I agree. In my case, I'm going to use env variables anyway in order to customize the systemd service (via the ```EnvironmentFile``` statement) that runs syncthing. Whether these env variables customize syncthing directly or customize the command line arguments as used in the ```ExecStart``` statement does not make a real difference. So, I have no opinion about this and as a user I'm going to agree with any decision the project takes.

Btw, I basically needed custom directory paths so as to create a generic RPM spec file and deploy Syncthing nicely in my local boxes running CentOS. At first, I had hard-coded the custom paths in ```cmd/syncthing/locations.go``` by patching it while building the RPM, but then thought it would be nice if there was a way to do it in a more "official" manner. Env vars seemed like an easy way to do this as their value can be retrieved from anywhere in the program, but cli options or settings in the configuration file are perfectly fine as well.

About the pull request, while I'd be happy to start a pull request for this feature, on a second thought I realize that it would be better if someone with greater experience with the Go language and the project did it.

Thank you all for your replies and for taking this request into consideration.

**Comment by wweich** [comment]
What's `STDIRLOGDATA` needed for? There is no default log dir, as there is no log by default.

**Comment by gnotaras** [comment]
Good point... Currently it seems to be useful for audit and panic logs only.

**Comment by calmh** [comment]
Stop discussing code in the issue. Discuss code in a PR where the code is.

**Comment by calmh** [comment]
This is fixed in 1.5.0
