### ISSUE TITLE
"missing port in address" error since v0.14.15

### ISSUE THREAD

**Issue by tonirug** [syncthing/syncthing#3817]
### Version Information
Syncthing Version: v0.14.15
OS Version: Ubuntu 16.04
Browser Version: (if applicable, for GUI issues)

Hello,
since update to v0.14.15 I get this error when trying to connect to other device:
2016/12/18 11:15:36.004319 service.go:391: DEBUG: dial failed TF2HZQ3-... tcp4://192.168.71.1 dial tcp4: address 192.168.71.1: missing port in address

The address in the configuration is actually missing the port number but as far as I know it should default to port 22000 in that case and it worked fine until last update.
It is not a big problem for me. I added the port and it works, but I have a lot of devices connecting to my server whose users are not able to edit the configuration. It would mean for to remotely connect to every device and fix the configuration.
I don't know if it is a bug or you changed it intentionally.
Please let me know.
Thanks in advance.

**Comment by calmh** [comment]
Probably a genuine bug related to compiling with Go 1.8beta2. Will look into it.
