### ISSUE TITLE
Should delete .stfolder when removing a share 

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#3819]
- .stfolder left behind on share removal
### Version Information

Syncthing Version: v0.x.y
OS Version: Windows 7 / Ubuntu 14.04 / ...

**Comment by calmh** [comment]
Yep, thanks.

**Comment by bugith** [comment]
Also removing other syncthing specific .files would be a must (.stignore, .syncthing.filename.tmp ...)

**Comment by uglygus** [comment]
What about .stversions? When removing a share should there be a popup warning asking if it should be removed? Maybe with the size and file count?

**Comment by bugith** [comment]
Ugly idea ;) . Not so ugly, but I may have a (better ?) one : without poping, just move (rename) .stversion to stversion[.something (if stversion already exists)]. Nicer ?

**Comment by Ferroin** [comment]
On Windows, you'd need to unset the 'hidden' attribute too.

Also, it would be nice to do the same for .stignore (and then possibly have syncthing rename that back if it exists when adding a share).

**Comment by AudriusButkevicius** [comment]
I don't see much point in renaming stuff around.

**Comment by Ferroin** [comment]
.stversions is a hidden folder.  It's got the hidden attribute on Windows, and starts with a . (which means the same thing on every other OS syncthing runs on).  Given that it's entirely created by Syncthing, that it can be pretty large, and that it's hidden (and therefore easy to forget), it's not unlikely that it will end up taking up space on the user's system that they may not be able to find.  Renaming it and unmarking it hidden makes it pretty obvious that it's there, thus making it harder to forget to remove it.

Personally, what I would really prefer is something in the UI when a folder gets removed offering to do one of the following:
1. Just delete it for the user (with confirmation of course).
2. Rename it to stversions and unset the hidden attribute (so the user can more easily find it to go through things and decide what to keep or get rid of.
3. Leave it as is.

As a general rule, programs are expected to at least offer to clean up after themselves, especially when not doing so is liable to waste resources.

**Comment by AudriusButkevicius** [comment]
If done with a prompt, sure, otherwise I don't think we should move stuff around.
We could unhide it, but that's about it.

**Comment by bugith** [comment]
> Also, it would be nice to do the same for .stignore (and then possibly have syncthing rename that back if it exists when adding a share).
This one is just a file created by ST (OK, filled by you - but is it worth overwaiting the code with back and forth renames... at most a popup warn should ask removal confirmation, stating "Your files won't be touched - If you created an Ignore-pattern list for this folder you'll loose this list"), it just should be deleted without prompt, like other syncthing.file.tmp and .stfolder

**Comment by bugith** [comment]
Well, unhide .stignore is the elegant way to keep the current no-prompt-at-all-for-share-removal.

**Comment by bugith** [comment]
... the problem is that on linux, unhide means rename

**Comment by AudriusButkevicius** [comment]
I am saying that it should have a prompt, which would then have checkboxes for ignores and versions.

**Comment by Ferroin** [comment]
@bugith No, it's a rename operation, there's a syscall called rename and that's what should be used since it's atomic, while a move isn't.  Also, the same semantics exist on all UNIX-like systems (including OS X).

@AudriusButkevicius Agreed, but it would be nice to have an option there to just delete them as well as having the option to rename them (with confirmation obviously).

**Comment by AudriusButkevicius** [comment]
There is no confirmation box at the moment, so I'd expect the checkboxes to be on the confirmation dialog.

**Comment by Ferroin** [comment]
I mean if we do have the option to delete the stuff instead of just renaming it, that deletion should have a confirmation.  .stignore isn't much of an issue in this respect, but .stversions could be a data loss risk (or a data leak risk depending on what you were storing in the share).
