### ISSUE TITLE
"disk has insufficient free space" althouth limit was set to 0%

### ISSUE THREAD

**Issue by peterjw** [syncthing/syncthing#3821]
I just upgraded syncthing on OS X to 0.14.15 (because I was prompted to)
Now all synchronisation are stopped  stating there would be insufficent free disk space.
As I only need some MB for configuration files beeing synced; i set the limit within the extended (? "Erweiter" in German) syncfolder configuration to 0.0 percent. The sync still is stopped and the error status is "home disk has insufficient free space" remains.
The synced folder is on the main disk containing the /Users folder where users home directories reside ion OS X.
(/home is kind of pseudo filesystem on OS X and reported to be 100% full by "df /home". Unmounting it does not change the picture )

### Version Information

Syncthing Version: v0.14.15, Mac OS X (64 bit)
OS Version: OSX Yosemite 10.10.5
Browser Version: Firefox 44.0.2

**Comment by wweich** [comment]
Wrong setting. You need to set `minHomeDiskFreePct` in the advanced settings. But I wouldn't do that. If you home is full and Syncthing tries to write to the index DB, it could crash and have a corrupted index, so everything needs to be scanned again and you may get conflics.

Please check what filles your home and free space on your home disk.

**Comment by peterjw** [comment]
Thanks for pointing to the right setting.
I just used "0%" for the sake of pointing out, that it is not a matter of how much free space is availabel.
I happen to know myself, that this is a bad idea for "production environments" ;-)
Actually I see a problem here in giving that value in _percent_, given that hard disks get bigger and bigger. I think an absulute value would fit better - but that's beyond this ticket.

**Comment by imsodin** [comment]
@peterjw That has already been proposed and accepted as a good idea here in #3307 but nobody picked it up and made a PR yet.
