### ISSUE TITLE
Custom address stopped working

### ISSUE THREAD

**Issue by hadogenes** [syncthing/syncthing#3824]
I use VPN to my home to connect and I can't use dynamic (local) discovery so I added custom address _tcp://hostname.domain.tld_ (I use _dnsmasq_ for lan dns).
It stopped working with version v0.14.15 (or maybe v0.14.14).
In my home (lan network) local discovery works fine.

I don't use global discovery and relaying.

### Version Information
Syncthing Version: v0.14.15
OS Version: Debian Stretch

**Comment by calmh** [comment]
This is #3817; we broke defaulting the port in .15. In the meantime, use `tcp://hostname.domain.tld:22000` as a workaround.
