### ISSUE TITLE
Syncthing refuses to begin synchronizing & 100% disk usage

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing#3826]
I have had several times on both my Windows 10 PCs in which Syncthing does not start to synchronize anything, but it does up in the Task Manager using quite a bit of HDD power, bringing the total HDD status to a 100% in-use state, slowing even my Core i5 Inspiron 13 (2016 model) down to a screeching halt. 
Any ideas?

**Comment by ProactiveServices** [comment]
For support please use the forum, and include some more details and screenshots of the GUI. The issue tracker is for bugs.
