### ISSUE TITLE
Receiving 'invalid subpath' errors on syncthing-inotify full folder sync trigger

### ISSUE THREAD

**Issue by javmorin** [syncthing/syncthing#3829]
I have been making some large scale file moves in one of my synced folders and this has caused syncthing to go **FAILED** indicating an **invalid subpath** error. 

### Current Behavior
- `syncthing-inotify` triggers scan of full sync path
- `syncthing` returns **invalid subpath** both to the `syncthing-inotify` request and shows same in the web UI

Looking at the logs for syncthing-inotify, I see the following:
```
[OK] Watching vc: /home/mikej/vc
[WARNING] Failed to perform request Post http://127.0.0.1:8384/rest/db/scan?folder=vc&next=3600&sub=.stfolder: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
[WARNING] Request to delay scanning of vc failed
[WARNING] http://127.0.0.1:8384/rest/db/scan?folder=vc&next=3600&sub=
[WARNING] Error: Status 500 != 200 for POST: vc, invalid subpath
[WARNING] Syncthing failed to index changes for  vc Invalid HTTP status code
[WARNING] http://127.0.0.1:8384/rest/db/scan?folder=vc&next=3600&sub=
[WARNING] Error: Status 500 != 200 for POST: vc, invalid subpath
[WARNING] Syncthing failed to index changes for  vc Invalid HTTP status code
...
```

### Expected Behavior
- `syncthing-inotify` triggers scan of full sync path
- `syncthing` completes the scan successfully.

I will also note that if I stop/disable `syncthing-inotify` and hit **Rescan** in the web UI, the sync completes successfully with no errors.

I checked at the recent issues and though I believe it may be the _result_ of #3805 - because the timing works and #3805 made adjustments to the subpath detection - the problem behavior is distinct from that issue. I unfortunately could not work out how to write a test that demonstrated the error (still very new to Go), so I will have to defer that to the syncthing devs.

### Version Information

Syncthing Version: v0.14.15
Syncthing-inotify Version: v0.8.4
OS Version: Arch Linux 64bit
Browser Version: N/A

**Comment by AudriusButkevicius** [comment]
The logs have not been modified, correct?

**Comment by jangrewe** [comment]
I can confirm this (#3804).

Here's my log:
```
Dec 20 21:41:39 blockbox syncthing-inotify[1230]: [WARNING] http://0.0.0.0:8384/rest/db/scan?folder=sSo6k-yeVTq&next=3600&sub=
Dec 20 21:41:39 blockbox syncthing-inotify[1230]: [WARNING] Error: Status 500 != 200 for POST: sSo6k-yeVTq, invalid subpath
Dec 20 21:41:39 blockbox syncthing-inotify[1230]: [WARNING] Syncthing failed to index changes for  sSo6k-yeVTq Invalid HTTP status code
```

**Comment by javmorin** [comment]
@AudriusButkevicius I removed the time/host/process marker prefix but otherwise I have not modified them and the lines are in-order with no lines removed

**Comment by wweich** [comment]
An existing but empty `sub` is an invalid sub path. I don't think that #3805 caused it, but that this has the same root cause as what #3805 fixed.

Either syncthing-inotify should remove the `sub` parameter, if it's empty, or syncthing needs another fix to ignore `sub`, if it's empty.

**Comment by javmorin** [comment]
I have submitted a pull request for syncthing-inotify (syncthing/syncthing-inotify#144) to (hopefully) resolve this issue from that end. Though given that syncthing has already made an exception for trailing slashes, I wonder if it would not still be appropriate to handle an empty subs list gracefully.

**Comment by calmh** [comment]
Oh. *Empty* sub. That's unexpected.

**Comment by calmh** [comment]
I'll fix and release this tomorrow some time.

**Comment by javmorin** [comment]
@calmh yeah it's because syncthing-inotify just iterates and adds each of the passed subs via url.Values.Add(). In the case of a complete folder sync, the subs list is just [""] which results in "&sub=" as the query parameter

**Comment by jangrewe** [comment]
Thanks for the quick fix, it seems to work fine now!
