### ISSUE TITLE
"always accept" configuration

### ISSUE THREAD

**Issue by Salamandar** [syncthing/syncthing#3832]
Well i'm trying to use ST on my Pi (remote, so without the web interface). 
ST complains first about unknown device, (solved by a manual editing of the config file), then about unknown folders. 
It would be easier to have some kind of "always accept new devices and folders" configuration. With a private API key that can be possible and secure.

**Comment by AudriusButkevicius** [comment]
There are plenty of issues discussing this subject.

**Comment by Salamandar** [comment]
Okay http://www.nocturnar.com/comunidad/attachments/okay2_kindledx-png.59679/
