### ISSUE TITLE
lib/config: TestReplaceCommit fails randomly

### ISSUE THREAD

**Issue by svetlemodry** [syncthing/syncthing#3834]
Hi!
Trying to build the package on an up-to-date Arch Linux system using these [PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/syncthing) instructions, the check test fails with the below output.
In v0.14.15 the tests went through without any errors.

### Version Information
Syncthing Version: v0.14.16
OS Version: Arch Linux

==> Starting check()...
ok  	github.com/syncthing/syncthing/lib/auto	1.287s
ok  	github.com/syncthing/syncthing/lib/beacon	1.008s
20:08:04 WARNING: Configuration version 1 is deprecated. Attempting best effort conversion, but please verify manually.
20:08:04 WARNING: Configuration version 2 is deprecated. Attempting best effort conversion, but please verify manually.
--- FAIL: TestReplaceCommit (0.00s)
	commit_test.go:77: Should require restart
20:08:07 WARNING: Configuration version 1 is deprecated. Attempting best effort conversion, but please verify manually.
20:08:07 WARNING: Configuration version 5 is deprecated. Attempting best effort conversion, but please verify manually.
20:08:07 WARNING: Configuration version 3 is deprecated. Attempting best effort conversion, but please verify manually.
20:08:07 WARNING: Configuration version 7 is deprecated. Attempting best effort conversion, but please verify manually.
20:08:07 WARNING: Configuration version 9 is deprecated. Attempting best effort conversion, but please verify manually.
20:08:07 INFO: bug: uncached path call (should only happen in tests)
FAIL
FAIL	github.com/syncthing/syncthing/lib/config	3.151s
ok  	github.com/syncthing/syncthing/lib/connections	1.014s
ok  	github.com/syncthing/syncthing/lib/db	1.111s
ok  	github.com/syncthing/syncthing/lib/dialer	1.010s
ok  	github.com/syncthing/syncthing/lib/discover	1.496s
ok  	github.com/syncthing/syncthing/lib/events	1.879s
ok  	github.com/syncthing/syncthing/lib/fs	1.515s
ok  	github.com/syncthing/syncthing/lib/ignore	1.667s
ok  	github.com/syncthing/syncthing/lib/logger	1.012s
ok  	github.com/syncthing/syncthing/lib/model	17.725s
ok  	github.com/syncthing/syncthing/lib/nat	1.048s
ok  	github.com/syncthing/syncthing/lib/osutil	1.078s
ok  	github.com/syncthing/syncthing/lib/pmp	1.010s
ok  	github.com/syncthing/syncthing/lib/protocol	1.343s
ok  	github.com/syncthing/syncthing/lib/rand	4.332s
?   	github.com/syncthing/syncthing/lib/rc	[no test files]
ok  	github.com/syncthing/syncthing/lib/relay/client	1.019s
ok  	github.com/syncthing/syncthing/lib/relay/protocol	1.009s
ok  	github.com/syncthing/syncthing/lib/scanner	1.055s
?   	github.com/syncthing/syncthing/lib/sha256	[no test files]
ok  	github.com/syncthing/syncthing/lib/signature	1.383s
ok  	github.com/syncthing/syncthing/lib/stats	1.009s
ok  	github.com/syncthing/syncthing/lib/symlinks	1.011s
ok  	github.com/syncthing/syncthing/lib/sync	1.667s
ok  	github.com/syncthing/syncthing/lib/tlsutil	1.008s
ok  	github.com/syncthing/syncthing/lib/upgrade	1.009s
ok  	github.com/syncthing/syncthing/lib/upnp	1.011s
ok  	github.com/syncthing/syncthing/lib/util	1.008s
ok  	github.com/syncthing/syncthing/lib/versioner	1.015s
?   	github.com/syncthing/syncthing/cmd/stbench	[no test files]
?   	github.com/syncthing/syncthing/cmd/stcompdirs	[no test files]
?   	github.com/syncthing/syncthing/cmd/stdisco	[no test files]
?   	github.com/syncthing/syncthing/cmd/stdiscosrv	[no test files]
?   	github.com/syncthing/syncthing/cmd/stevents	[no test files]
?   	github.com/syncthing/syncthing/cmd/stfileinfo	[no test files]
?   	github.com/syncthing/syncthing/cmd/stfinddevice	[no test files]
?   	github.com/syncthing/syncthing/cmd/stgenfiles	[no test files]
?   	github.com/syncthing/syncthing/cmd/stindex	[no test files]
?   	github.com/syncthing/syncthing/cmd/strelaypoolsrv	[no test files]
?   	github.com/syncthing/syncthing/cmd/strelaypoolsrv/auto	[no test files]
?   	github.com/syncthing/syncthing/cmd/strelaysrv	[no test files]
?   	github.com/syncthing/syncthing/cmd/strelaysrv/testutil	[no test files]
?   	github.com/syncthing/syncthing/cmd/stsigtool	[no test files]
?   	github.com/syncthing/syncthing/cmd/stvanity	[no test files]
?   	github.com/syncthing/syncthing/cmd/stwatchfile	[no test files]
ok  	github.com/syncthing/syncthing/cmd/syncthing	11.652s
exit status 1
exit status 1
==> ERROR: A failure occurred in check().
    Aborting...

**Comment by calmh** [comment]
Try again. I think there is a timing dependent issue with that test.

**Comment by svetlemodry** [comment]
Yep, your're right.
Wasn't expecting something like this. Thanks for the quick reply!

**Comment by calmh** [comment]
Well, it's still a bug.

**Comment by lkwg82** [comment]
Do we really need this test? It is ignored exactly one year?
