### ISSUE TITLE
Incorrect warning message

### ISSUE THREAD

**Issue by cedricpim** [syncthing/syncthing#3835]
Currently, on my logs I am getting the following WARNING message:
```
23:22:52 WARNING: Not sending symlinks to old client XXX - please upgrade to v0.14.14 or newer
```

Tracked the issue to this line https://github.com/syncthing/syncthing/blob/bab7c8ebbff24ab50326ead5693cfcabcc87ca0a/lib/model/model.go#L790.
The system is working fine, so this is just a minor detai.

### Version Information

Syncthing Version: syncthing v0.14.15 "Dysprosium Dragonfly" (go1.7.4 darwin-amd64)
OS Version: OS X El Capitan 10.11.6

**Comment by AudriusButkevicius** [comment]
Why do you think its incorrect?

**Comment by cedricpim** [comment]
Because it asks to update to version 0.14.14 or newer and I have version 0.14.15 (which qualifies as newer).

**Comment by AudriusButkevicius** [comment]
Read the message again. It suggests to update the old remote client.

**Comment by cedricpim** [comment]
Ohhh, sorry for wasting time :(
