### ISSUE TITLE
Syncthing may currently be slowing down Firefox

### ISSUE THREAD

**Issue by Nutomic** [syncthing/syncthing#3836]
The `about:performance` page in Firefox says that Syncthing may be slowing down Firefox. This is with an idle Syncthing (no transfers, only 2 devices connected). And I dont have any modals open.

![syncthing-performance](https://cloud.githubusercontent.com/assets/1044450/21419158/4f9635de-c869-11e6-98a0-d29ba5074ade.png)

### Version Information

Syncthing Version: v0.14.15
OS Version: Kubuntu 16.10
Browser Version: Firefox 50.1.0

**Comment by calmh** [comment]
OK?

**Comment by AudriusButkevicius** [comment]
I am sure if you go to bbc.co.uk you'll get worse. It sucks being a browser.

**Comment by Nutomic** [comment]
I thought this should be fixed. But no idea if thats doable.

**Comment by stonedbovines** [comment]
The real issue there is with `about:performance` (eg [ "addon might slow down browser" is inaccurate and annoying](https://bugzilla.mozilla.org/show_bug.cgi?id=1210770) which still appears to be overly aggressive in deciding that there may be an issue)

If you turn off `Refresh automatically` and then refresh manually, everything is likely to change to `currently performs well`, suggesting no real problem.

**Comment by Nutomic** [comment]
Okay I didnt know that. With manual refresh, it doesnt show Syncthing as problematic. But if I refresh a bunch of times, it comes up sometimes (with up to 10% cpu usage).

Anyway, feel free to close this issue.
