### ISSUE TITLE
Random dead-locks

### ISSUE THREAD

**Issue by scienmind** [syncthing/syncthing#3837]
(Splitting this from #3633 , maybe it's related to the crash there, idk...)

Either on startup or after few hours of successful running, ST would get stuck, UI is as follows:

![image](https://cloud.githubusercontent.com/assets/11633330/21450752/3c388aca-c902-11e6-8a92-10cf01c4dcff.png)

I don't have any specific way to reproduce this, but it has happened more than 5 times since 0.14.16 release....

Regarding logs - ST log shows nothing, last entry is from the moment it still was "alive"
ST log:
https://gist.github.com/anonymous/1b8391448818d56bfbfe7ec91d54f3b5
SyncTrayzor log:
https://gist.github.com/anonymous/9bc65295e027d5ee482bdc646a569dbc

### Version Information

Syncthing Version: v0.14.16
OS Version: Windows 10 x64

**Comment by scienmind** [comment]
Update: it made two of my nodes completely useless, it deadlocks all the time, so I decided to downgrade to 0.14.13 (before the sec. fix that broke few things)... and unfortunately it still happens...

I can't blame 0.14.16 now... Looking for other things changed recently on my side:
In anticipation of #3520 , I moved 3 folders (repos) from one ST instance to another (on the same PC). It was done properly:
- first "share" the repos with the destination instance (but not configure their acceptance there yet)
- then "detach" the repos from the source ST (to avoid them both messing with the same folders simultaneously)
- then "accept" the repos on the destination instance, configure, and let it roll.

It started OK, scanning, some conflicts, nothing special. Then before the last of the "new" folders finished scanning, i started getting deadlocks on this machine, and another one (which also shares those folders).
At the same time 0.14.16 rolled out, so i thought it was the cause....

**Comment by AudriusButkevicius** [comment]
Run with STTRACE=sync env var set and wait for it to spit out the deadlock panic.

**Comment by AudriusButkevicius** [comment]
If that doesn't work, run with STDEADLOCK=300 but try the initial option first. It should blow up after 10m of deadlocking.

**Comment by scienmind** [comment]
Here it goes:
https://gist.github.com/anonymous/79214facd55d3682a8a94fe4344c261f

**Comment by AudriusButkevicius** [comment]
Seems like a bug thats already fixed in master.

**Comment by AudriusButkevicius** [comment]
Try this build https://build.syncthing.net/job/syncthing-pr/3150/

**Comment by scienmind** [comment]
Glad to hear!

However, there are seems to be no windows builds there.... (unless i'm looking the wrong side :confused: )

**Comment by scienmind** [comment]
OK, now I'm running `syncthing-windows-amd64-v0.14.14+39-gf5a310a.zip` (from https://build.syncthing.net/job/syncthing-windows/)

So for at least a couple of hours it seems to be deadlock-free :)

**Comment by scienmind** [comment]
Few days later - seems like this bug is indeed fixed in master.

BUT in the meantime couple more machines in the cluster became "dead-locked" (most times they die to early to even finish booting and check for updates).
And once it goes this path, the only way out is to manually replace the binaries with ones from master and disable auto-update (or it revert's back to 0.14.16 and dies again). 

If the planned 0.14.17 is going to take some time, I think it may be a worth it to release a hot-fix for 0.14.16 (maybe without some unbaked features currently in master, if any) to avoid "loosing" more nodes...
