### ISSUE TITLE
Incorrect ignore patterns causing "parent not a dir", previously "resurrecting directory"

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3838]
Let's say I add a folder containing subdirectories with movies in them. It scans and all is fine. I then add ignore patterns:

```
!*.mp4
*
```

I intend this to mean only sync the mp4s in the subdirectories, but that's of course not how it works in Syncthing. Nonetheless the things were already scanned, and I have a hunch that when someone now connects we'll send them an index entry for `foo/bar.mp4` (because it matches the unignore at the top) but not the `foo` entry (because it's ignored), resulting in an orphaned file and an error on the destination.

In syncthing 0.14.13 and earlier, on the receiving side, we'd have said "huh, weird" and created the directory and synced the file. It would have appeared as working, sort of, except new additions wouldn't be added because they're correctly ignored on the source.

**Comment by saitoh183** [comment]
Yes i think that is the problem i am having since the new version

**Comment by calmh** [comment]
And now I wonder if it wouldn't be best and maybe even easiest to just make ignore patterns actually work this way by design instead. That is,

- When there are unignore-patterns, we also descend into ignored directories
- Unignored files are scanned and indexed, even in ignored directories

And then either,

- It is allowed and legitimate to send index entries for files without preceding directory entries. Missing directories are resurrected as needed with umask permissions. Or,
- We must take care to unigore and resurrect index entries for the otherwise ignore directories leading up to the unignored file.

The latter is cleaner but a tiny bit more difficult. The former is backwards bug compatible.

All in all, ignores become friendlier and we get rid of a common "how the actual fuck do it ..." query around unignoring stuff in subdirectories.

**Comment by AudriusButkevicius** [comment]
I am in favor of second option if anything.

**Comment by calmh** [comment]
https://forum.syncthing.net/t/un-ignore-subfolders-files-of-ignored-folder/1460/12

**Comment by rafaelsoaresbr** [comment]
I have a similar problem, I'm trying to sync files from Android with this .stignore:
> !/DCIM
 !/WhatsApp/Media
> *

Files in Media folder won't sync with this error: parent is not a directory

**Comment by calmh** [comment]
Resolved by 1a1e35d
