### ISSUE TITLE
ice: Failed service '(main.serviceFunc)(0x84e0270)' (1.000000 failures of 5.000000), restarting: true, error: leveldb/table: corruption on data-block (pos=630817): checksum mismatch

### ISSUE THREAD

**Issue by frank-github** [syncthing/syncthing#3841]
### Version Information
syncthing v0.14.16, Linux (32 bit)
OS Version: Ubuntu 14.04 32-bit

got this error, but syncthing looks like working

ice: Failed service '(main.serviceFunc)(0x84e0270)' (1.000000 failures of 5.000000), restarting: true, error: leveldb/table: corruption on data-block (pos=630817): checksum mismatch, want=0x0 got=0x48f806ff [file=000099.ldb], stacktrace: goroutine 118 [running]:
github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).runService.func1.1(0x18e4b680, 0x1)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:448 +0x84
panic(0x855d9e0, 0x1a6c9a60)
	/usr/local/go/src/runtime/panic.go:489 +0x22a
github.com/syncthing/syncthing/lib/db.(*Instance).withNeed(0x18fc89e0, 0x1a69c330, 0xb, 0x10, 0x1a52da84, 0x20, 0x20, 0x1, 0x19f24260)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:489 +0x102a
github.com/syncthing/syncthing/lib/db.(*FileSet).WithNeedTruncated(0x1a33ae00, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0x1ac3c1b0)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/set.go:206 +0x17a
github.com/syncthing/syncthing/lib/model.(*Model).NeedSize(0x18e62000, 0x18e41974, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/model.go:588 +0x3ac
main.folderSummary(0x8a19ee0, 0x18d9e180, 0x8a1ba80, 0x18e62000, 0x18e41974, 0xb, 0x3)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:643 +0x756
main.(*folderSummaryService).sendSummary(0x19d3c6c0, 0x18e41974, 0xb)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/summaryservice.go:190 +0x60
main.(*folderSummaryService).calculateSummaries(0x19d3c6c0)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/summaryservice.go:154 +0x1ee
main.(*folderSummaryService).(main.calculateSummaries)-fm()
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/summaryservice.go:50 +0x20
main.serviceFunc.Serve(0x190fa5a8)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/summaryservice.go:229 +0x1a
github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).runService.func1(0x18e4b680, 0x1, 0x8a158b0, 0x190fa5a8)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:454 +0x4f
created by github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).runService
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:457 +0x4b

**Comment by AudriusButkevicius** [comment]
Search closed issues or the forum.
