### ISSUE TITLE
Optional backup+notification of unusual file changes preventing unnoticed loss/changes

### ISSUE THREAD

**Issue by novoid** [syncthing/syncthing#3842]
Hi!

How about a feature (on per-folder basis) where the user is able to
define an amount (in kB/MB) and/or a number of files deleted/added
within a short period of time (10s?). If changes of the disk space
amount or the number of files is exceeded, Syncthings makes a backup
of the previous versions of files and notifies the user.

Example folder settings:

- [X] activate folder change notifications for this folder:
  - [X] save backup and notify when more than **1** files are removed
  - [ ] save backup and notify when more than _____ files are added
  - [X] save backup and notify when more than **300** kB are removed
  - [ ] save backup and notify when more than _____ kB are added

Why? 

I got a similar feature for my [Org-mode](http://orgmode.org/) (text-)files which are
maintained within a Git repository. The repository is watched by
[gitwatch](https://github.com/nevik/gitwatch) which does an automatically commit on each file change.

When a commit consists of more than 200 lines removed from a file, I
launch a notification.

This way, I get notified whenever I delete a collapsed Org-mode
heading by mistake without noticing it.

I'd like to get this kind of security net for arbitrary files within
Syncthing as well: whenever I delete a folder on mistake, the number
of files removed or the amount of data lost rings a bell.

This is probably not necessary for most shared folders but for some
(like my Org-mode folder) this seems really handy to me.

**Comment by AudriusButkevicius** [comment]
Sadly it's too specific to deserve a special case, so I am closing this as a "deal it with it".

**Comment by calmh** [comment]
That said, the external versioner gets called for each file replacement. It could keep a tally and act appropriately.
