### ISSUE TITLE
Schedule Pause

### ISSUE THREAD

**Issue by CoupeWare** [syncthing/syncthing#3844]
I would like to be able to schedule when devices and/or folders are paused.

I have some locations with limited bandwidth. I'd like to prevent them from syncing offsite when the bandwidth is likely to be needed by other users and only sync offsite at night.

It might also be useful to have the option for a one time pause for a specified amount of time.

**Comment by AudriusButkevicius** [comment]
Use the API and some external scheduling tool. There are no plans to add scheduling, just like all the previous issues have explained.

**Comment by calmh** [comment]
This might be a valid feature request on other things, like https://github.com/canton7/SyncTrayzor or https://github.com/syncthing/syncthing-gtk
