### ISSUE TITLE
Changing BW limits should not involve a restart

### ISSUE THREAD

**Issue by benshep** [syncthing/syncthing#3846]
Currently setting or unsetting bandwidth limits is a little cumbersome (Actions > Settings > set incoming/outgoing limits, and you have to remember what they were set to before - plus it involves a restart). It would be nice if bandwidth limits could be toggled on/off (to a preset level) from the Actions menu, and if Syncthing didn't have to be restarted.

(I'd previously asked for this on the [SyncTrayzor repo](https://github.com/canton7/SyncTrayzor/issues/328), but it's complex to implement at that level. I thought it might be easier to add as functionality in core Syncthing.)

**Comment by AudriusButkevicius** [comment]
There is an infinite number of things that would be nice to toggle immediately, but I think to keep the UI sane, first we have to understand that we can't fit everything, secondly unless there is a riot, and a avalanche of comments on this ticket, I'll say that this desire is specific to you, and it's probably just UI clutter to remaining 99% of users, hence I am closing this. If there actually is an avalanche of comments, we'll reopen.

**Comment by scienmind** [comment]
I wouldn't expect an avalanche here really :)
 
But: I do recommend implementing this (at least the framework for it) . 
Many torrent clients implement "dual speed state": normal and slow.
(I know the comparison is not completely fare: torrenting is much likely to choke the bandwith in average use case). One reason they do this in torrenting IMHO: is that machines today have lots of memory and people are more and more prefer to "leave stuff working quietly in the background" rather "exit and realunch".

In syncthing - a synchronization tool that mainly purposed to be used as "always ON, in the background" it would make even more sense in a way. If some large files are going through, choking everything else, to just slow it down for a while rather then exit, or set hard limits in the config "forever".

Now as far as UI clutter goes, backend support for "fast/slow" toggle would do most of the work. Then wrappers can use it to toggle the sate on without altering the config files for every toggle (and without restart).

**Comment by scienmind** [comment]
Yeah, but according to canton, in current form it requires config update and full application restart, which kinda defeats the purpose of it (promptly slow down for a while instead of exit and start later)

**Comment by AudriusButkevicius** [comment]
Agree, we could remove the need to restart, but thats not what this ticket is about.

**Comment by benshep** [comment]
OP here - it's kind of what it's about. Restartless toggling is a big part
of it. The UI stuff is more cosmetic.
