### ISSUE TITLE
Syncthing on Android - Case sensitivity issues

### ISSUE THREAD

**Issue by ion201** [syncthing/syncthing#3847]
Relevant issues: https://github.com/syncthing/syncthing/issues/439; https://github.com/syncthing/syncthing-android/issues/187. I'm creating this issue as per the last comment in the second issue here. It seems like these cases may have been unrelated and the android issue was not resolved.

Syncthing android/linux version: 0.14.16

What I did:

1. Create sync folder "myFolder" and sync across linux devices and an android phone. This contains a subfolder "myFolder/She" which contains misc files.
2. Turn off syncthing for android
3. Create new folder "myFolder/she" on a linux device and fill it with more unique misc files. This syncs across all other linux devices as expected.
4. Turn on syncthing for android; notice files unexpectedly being deleted from linux nodes.

**Comment by calmh** [comment]
#1787 #2739 duplicate
