### ISSUE TITLE
unicode folder name support on android

### ISSUE THREAD

**Issue by rezad1393** [syncthing/syncthing#3849]
adding folders with Persian (Unicode) filename in syncthing on linux then trying to sync to android.
this give the out of sync error.
the folders are on sd-card folder in data folder of syncthing app.
the sd card is formated in f2fs format but if I am not wrong the ext4 format had the same issue.
the OS is cyanogenmod 6.0.1

and the important part is that problem is with Unicode name of **folders**. the files with Unicode name but inside ASCII named folders work fine.

### Version Information

Syncthing Version: v0.14.16
Syncthing-android Version 0.9.3
OS Version: andoird 6.0.1
Browser Version: (if applicable, for GUI issues)

**Comment by AudriusButkevicius** [comment]
This is down to the OS and filesystem in question, nothing todo with syncthing. Also unicode is not a locale that any filesystem supports, unicode is just a way to express things that does not have a physical representation on disk.

**Comment by AudriusButkevicius** [comment]
If you can provide an actual error, that would also be useful.

**Comment by rezad1393** [comment]
the log on syncthing doesn't show anything

**Comment by rezad1393** [comment]
and the unicode IS something that some filesystem support and some dont.
like fat16.
but I dont think this is filesystem related.
cause as I said the file names can be in unicode but the folder names cant.

**Comment by AudriusButkevicius** [comment]
How do you know its failing tho? The ticket you pointed out talks about utf-8, the poster misunderstands about unicode too. See http://stackoverflow.com/a/5290266 for explanation on unicode.

**Comment by rezad1393** [comment]
I get the "out of sync" error and the failed files are inside the folder with unicode name.
this has happened before. and it messes with the DB of syncthing repo I think because if this happens even deleted the offending folder sometimes wont help and I have to reset the Database.

**Comment by AudriusButkevicius** [comment]
The out of sync usually has a reason why exactly its out of sync either in the stdout log or failed items in the web ui. It's more like you are hitting #3839 which a lot of people are experiencing.

**Comment by calmh** [comment]
Syncthing fully supports (requires, even) UTF-8 on all platforms. As long as names are in UTF-8 everything will be smooth. If they are in some other encoding, Syncthing will not successfully sync them.

**Comment by rezad1393** [comment]
so why if doesnt sync mine?

**Comment by AudriusButkevicius** [comment]
Well you haven't explained/showed what error you are getting, you are just making assumptions so far.
