### ISSUE TITLE
Rethink the UI

### ISSUE THREAD

**Issue by matejkramny** [syncthing/syncthing#385]
Hello, any comments appreciated.

![screenshot 2014-06-21 12 10 47](https://cloud.githubusercontent.com/assets/797608/3348543/ca163e1e-f934-11e3-9872-608f0bffef26.png)
- There is a list of repositories on the left. Initially only status of the repository is revealed
- Clicking on a repository will show you a list of nodes and repository details
  - Nodes which share the repository are listed at the top, showing their sync status

**Whats better:**
- Its easier to add share repositories with nodes, perhaps more intuitive
- Better structured

**Comment by lkwg82** [comment]
What is the current status of this issue?

**Comment by calmh** [comment]
I think this has passed its consume-before date.
