### ISSUE TITLE
Windows only downloads 2-3MB of a large file at a time and then stops

### ISSUE THREAD

**Issue by haburka** [syncthing/syncthing#3858]
My group is sharing a video file that's 14MB large. When I start syncthing, it connects to my friend's computer, downloads approximately 3 MB of it, and then stops pulling data completely. I have no problem with smaller files, so this is not a critical issue for me. 

What I have tried;
Changing upload/download rate limits, Changing minimum free space.
Running in administrator mode
Running in verbose mode:
I get the log message:
Connected to already connected device (device-id)
Updating to version 14.17 (My friend is on version 14.14)

Syncthing Version: v0.14.17
OS Version: Windows 10 Pro

**Comment by n86io** [comment]
My largest file, i synced, have 9,98gb. With Windows 10 Home.

**Comment by AudriusButkevicius** [comment]
Use forum for support

**Comment by calmh** [comment]
Even better, upgrade to 0.14.18 as this is probably the bug I just solved.

**Comment by haburka** [comment]
It disappeared when I tested it today after the update, and I felt like a fool. Thanks for letting me know that you fixed it!
