### ISSUE TITLE
Specifying -logfile has no effect when -no-restart used

### ISSUE THREAD

**Issue by Kudalufi** [syncthing/syncthing#3866]
### Description

Any time syncthing is run with the -no-restart switch, it also ignores the switch -logfile

### Reproducing
Command: `./syncthing -no-restart -logfile=testlog`
Expected result: log file written to file "testlog"
Actual result: log file sent to stdout

### Version Information

Syncthing Version: git master (0.14.18)
Go Version: 1.7.3
OS Version: Windows 10

**Comment by AudriusButkevicius** [comment]
Log file is always sent to stdout regardless of the command line options.

**Comment by calmh** [comment]
This is by design as it's the monitor process that writes the log.
