### ISSUE TITLE
Make "override changes" more explicit

### ISSUE THREAD

**Issue by jpjp** [syncthing/syncthing#3871]
Could the "override changes" button be more explicit by telling the user where the changes are going to be overriden?

**Comment by jpjp** [comment]
p.s. searching for "override changes" in quotes on the docs website does not find any matches (but google does).

**Comment by jpjp** [comment]
maybe "override changes on remote devices"

**Comment by Ferroin** [comment]
Given #3780, I'd agree that this could be made clearer (at least, the english translation, I don't know any other language well enough to render an opinion on any other localization).

**Comment by lichtamberg** [comment]
Yeah, please really rename it to "Override remote devices"...!!!
Didn't read it up carefully and lost data because of it (but had at least backups in the end...).

**Comment by AudriusButkevicius** [comment]
Suits you well for pressing buttons which you haven't checked in the docs what they are doing.

**Comment by lichtamberg** [comment]
Are you sure that this is the right answer to a not-clear-enough named button?

**Comment by AudriusButkevicius** [comment]
Well no, but I am just saying we are not the only ones at fault here.

**Comment by lichtamberg** [comment]
I didn't say anyone is guilty here, it's just about to make the button text a bit more clear. 
I'm sorry if my post was criminative and I also want to say thank you very much for your hard word - syncthing is a really great tool! 

I just wanted to help and point out that with a better button text, newbies like me are less endangered to lose data by their own mistakes.

**Comment by acolomb** [comment]
This should be fixed since #7522, where confirmation dialogs were added with a clearer explanation.
