### ISSUE TITLE
Web GUI Connection errors since 0.14.18

### ISSUE THREAD

**Issue by grinapo** [syncthing/syncthing#3877]
Web GUI pretty fast gets lost with "connection error: Syncthing seems to be experiencing a problem processing your request. Please refresh the page or restart Syncthing if the problem persists."

In the background all the XHR requests seem to go to and from and replies seem to be just fine. The GUI did such things in the past but recovered quick, but not anymore. In fact it seems that the stuff BEHIND the error dialog refreshes just fine.

Browser Version: firefox nightly; 53.0a1 (2017-01-03) (64-bit)

**Comment by canton7** [comment]
IIRC if the GUI gets a 500 back, then it shows that modal and will never remove it (until you refresh the page).

Can you log the XHR request which fails, and add it to this issue?

**Comment by calmh** [comment]
Interesting. There is a change that could possibly be related, but it's not super obvious to me how. That said, I've also seen the case where it does not remove the dialog when the connection is re-established, which it should do.

**Comment by calmh** [comment]
I think that's the case, yes.

**Comment by grinapo** [comment]
I can do anything (apart from world peace), so what do you want? Console, as far as I see didn't offer any obvious explanation for the dialog, and I did not remember seeing any 500s either, but I can log httpfox traffic if you want it. The main problem is that XHRs continue to flow so it's hard to spot where went wrong what. 
But it is absolutely repeatable, takes 3-6 minutes.

(Main problem is that lots of stuff gets lost on reload: permission requests, new folder share requests and possibly global changelog as well.)

**Comment by canton7** [comment]
If you've got the dev console open, ajax requests which result in a 500 should come up in red, and so be easy to spot.

**Comment by grinapo** [comment]
Now I have the proof that this is a spyware program. ;-) You probably have modified my machines: I am trying to get the error for _hours_ now, but nothing. On neither servers. It is rude to fix remotely the bugs I'm trying to trigger! :-)

I won't give up. (Maybe it's timing? Running the console and httpfox definitely slow down the browser.)

**Comment by AudriusButkevicius** [comment]
Yes, I think so.

**Comment by 5chdn** [comment]
I'm having the same issue for several weeks now. I'll continue where @grinapo stopped, here is the XHR 500 from my js console:

    GET [XHR] http://127.0.0.1:8384/rest/system/upgrade     [HTTP/1.1 500 Internal Server Error 0ms]

It comes every 2 seconds. Here's a screenshot:

![screenshot at 2017-01-30 12-12-59](https://cloud.githubusercontent.com/assets/15729797/22421310/bfab9936-e6e6-11e6-954b-eb71f2a1ab6f.png)

And here is the back trace from the client:

    2017/01/30 12:14:23 http: panic serving 127.0.0.1:54348: no versions?
    goroutine 35913 [running]:
    net/http.(*conn).serve.func1(0xc4208e6e80)
      /usr/bin/src/net/http/server.go:1491 +0x12a
    panic(0x9e1fe0, 0xc421238a20)
      /usr/bin/src/runtime/panic.go:458 +0x243
    github.com/syncthing/syncthing/lib/db.(*Instance).withNeed(0xc42018be00, 0xc4212383c0, 0x6, 0x8, 0xc42c6353d0, 0x20, 0x20, 0xa0f601, 0xc4212383d0)
      /build/syncthing/src/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:449 +0x17c8
    github.com/syncthing/syncthing/lib/db.(*FileSet).WithNeedTruncated(0xc421a18820, 0xe1db2cec7d0c59f1, 0x470706218a3bf454, 0xeb25ac313e359019, 0xe06fa343ce13599b, 0xc4297aad80)
      /build/syncthing/src/src/github.com/syncthing/syncthing/lib/db/set.go:206 +0x205
    github.com/syncthing/syncthing/lib/model.(*Model).Completion(0xc4218eec80, 0xe1db2cec7d0c59f1, 0x470706218a3bf454, 0xeb25ac313e359019, 0xe06fa343ce13599b, 0xc4208e6f66, 0x6, 0x0, 0xe, 0xc4208e6f04, ...)
      /build/syncthing/src/src/github.com/syncthing/syncthing/lib/model/model.go:528 +0x379
    main.(*apiService).getDBCompletion(0xc421ed2d00, 0xf4a540, 0xc4292408f0, 0xc42c101d10)
      /build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:616 +0x10b
    main.(*apiService).(main.getDBCompletion)-fm(0xf4a540, 0xc4292408f0, 0xc42c101d10)
      /build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:230 +0x48
    net/http.HandlerFunc.ServeHTTP(0xc4211af000, 0xf4a540, 0xc4292408f0, 0xc42c101d10)
      /usr/bin/src/net/http/server.go:1726 +0x44
    net/http.(*ServeMux).ServeHTTP(0xc423051f20, 0xf4a540, 0xc4292408f0, 0xc42c101d10)
      /usr/bin/src/net/http/server.go:2022 +0x7f
    main.getPostHandler.func1(0xf4a540, 0xc4292408f0, 0xc42c101d10)
      /build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:411 +0x18e
    net/http.HandlerFunc.ServeHTTP(0xc42104c120, 0xf4a540, 0xc4292408f0, 0xc42c101d10)
      /usr/bin/src/net/http/server.go:1726 +0x44
    main.metricsMiddleware.func1(0xf4a540, 0xc4292408f0, 0xc42c101d10)
      /build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:483 +0xd3
    net/http.HandlerFunc.ServeHTTP(0xc421ae3d20, 0xf4a540, 0xc4292408f0, 0xc42c101d10)
      /usr/bin/src/net/http/server.go:1726 +0x44
    main.noCacheMiddleware.func1(0xf4a540, 0xc4292408f0, 0xc42c101d10)
      /build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:506 +0x18d
    net/http.HandlerFunc.ServeHTTP(0xc421ae3d60, 0xf4a540, 0xc4292408f0, 0xc42c101d10)
      /usr/bin/src/net/http/server.go:1726 +0x44
    net/http.(*ServeMux).ServeHTTP(0xc42104c150, 0xf4a540, 0xc4292408f0, 0xc42c101d10)
      /usr/bin/src/net/http/server.go:2022 +0x7f
    main.csrfMiddleware.func1(0xf4a540, 0xc4292408f0, 0xc42c101d10)
      /build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/gui_csrf.go:77 +0x240
    net/http.HandlerFunc.ServeHTTP(0xc420267970, 0xf4a540, 0xc4292408f0, 0xc42c101d10)
      /usr/bin/src/net/http/server.go:1726 +0x44
    main.withDetailsMiddleware.func1(0xf4a540, 0xc4292408f0, 0xc42c101d10)
      /build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:514 +0x134
    net/http.HandlerFunc.ServeHTTP(0xc42157aa00, 0xf4a540, 0xc4292408f0, 0xc42c101d10)
      /usr/bin/src/net/http/server.go:1726 +0x44
    main.corsMiddleware.func1(0xf4a540, 0xc4292408f0, 0xc42c101d10)
      /build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:474 +0x68
    net/http.HandlerFunc.ServeHTTP(0xc4205f64e0, 0xf4a540, 0xc4292408f0, 0xc42c101d10)
      /usr/bin/src/net/http/server.go:1726 +0x44
    main.localhostMiddleware.func1(0xf4a540, 0xc4292408f0, 0xc42c101d10)
      /build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:521 +0x8c
    net/http.HandlerFunc.ServeHTTP(0xc4205f6500, 0xf4a540, 0xc4292408f0, 0xc42c101d10)
      /usr/bin/src/net/http/server.go:1726 +0x44
    main.debugMiddleware.func1(0xf4a540, 0xc4292408f0, 0xc42c101d10)
      /build/syncthing/src/src/github.com/syncthing/syncthing/cmd/syncthing/gui.go:423 +0xab
    net/http.HandlerFunc.ServeHTTP(0xc4205f6520, 0xf4a540, 0xc4292408f0, 0xc42c101d10)
      /usr/bin/src/net/http/server.go:1726 +0x44
    net/http.serverHandler.ServeHTTP(0xc421f55b80, 0xf4a540, 0xc4292408f0, 0xc42c101d10)
      /usr/bin/src/net/http/server.go:2202 +0x7d
    net/http.(*conn).serve(0xc4208e6e80, 0xf4b240, 0xc4204d6c80)
      /usr/bin/src/net/http/server.go:1579 +0x4b7
    created by net/http.(*Server).Serve
      /usr/bin/src/net/http/server.go:2293 +0x44d

It is independent from which browser I use.

**Comment by AudriusButkevicius** [comment]
Your database is somehow screwed up,nothing todo with this ticket, try resetting the database.
