### ISSUE TITLE
GUI: Wrong alignment of local state details when ignore patterns are used

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing#3878]
The values of the local state seem to have additional spacing in the GUI HTML. This results in poor alignment as seen here:

![8d285dd0-d39c-11e6-8eb4-e65058dc035e](https://cloud.githubusercontent.com/assets/125426/21699818/aa4c49ca-d39d-11e6-98b9-c64a81cb3bac.png)

This issue only pops up if 'ignore patterns' are used.

### Version Information

Syncthing Version: v0.14.18
OS Version: Windows (64 bit)
Browser Version: Chrome

**Comment by calmh** [comment]
FWIW it's fine on Safari

<img width="565" alt="screen shot 2017-01-05 at 23 21 50" src="https://cloud.githubusercontent.com/assets/125426/21699850/cc6de720-d39d-11e6-84b9-354f2aec2a55.png">

**Comment by calmh** [comment]
Also on Firefox and Edge. It's the `<br>` that changes the alignment of the line above it. Feels like a rendering bug in Chrome?
