### ISSUE TITLE
Default path

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#3880]
Not a real issue, a Windows enhancement perhaps
Windows specific, sorry, shame on me (but may apply if we see some special XDG_FOLDERS set in linux, maybe)
On shared folder creation, ~ strike in target field in the gui drives us to $home in linux and %userprofile% in windows.
Since some time, Windows offers users that have 2 drives the possibility to move **their data system folders** (docs, music, video...) to an alternative path, e.g. c:\users\Dave\Documents -> d:\users\Dave\Documents, the hidden Appdata\blablah remaining in c:\users\Dave\
Many 2 drives or Single drive partitionned OEM computers are supplied with this yet done and even a tweak in Windows so that all these folders for new users are created in D: or whatever the other drive letter.
Syncthing data being ... data ;) , wouldn't it be nice if both the default "Sync" share and the gui prompt on "~" were in the **path\\..** relative to the one we can read in regedit key [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders]:"Personal"="D:\\\Users\\\Dave\\\Documents" or, as they say in this branch : "!Do not use this registry key"="Use the SHGetFolderPath or SHGetKnownFolderPath function instead" ? Note here the "!" doesn't mean NOT ;)

**Comment by AudriusButkevicius** [comment]
https://sourcegraph.com/github.com/syncthing/syncthing@7a16dbd31d8fec23625b78cb5455f976c4518dfc/-/blob/lib/osutil/osutil.go#L117-118

**Comment by bugith** [comment]
Nice man, I still wandered if one day I could at least read the code. Today "It's Broadway!" (© Reiser- Gros Dégueulasse) as you point me straight to the related section.
I guess you are in a good mood and this is my new year gift for the usual DIY, isn't it ? ;) I love it and it incourages me to learn GO (and coding too as anybody can badly write any language).
I guess also my suggestion is difficult as there is no variable that exposes these custom paths, and I'm pretty sure their "SHGetFolderPath" & "SHGetKnownFolderPath" aren't GO things.
Happy new year to you and Jakob, and thanks for the job.

Bye bye

**Comment by wweich** [comment]
You don't need to know GO to understand the linked line.
To override the home (without overriding `%USERPROFILE%`) you need to set `%HomeDrive%` and `%HomePath%` before starting syncthing.
If you use SyncTrayzor, there is a setting to set env vars.

---

`~` always means `home`, not `home/Documents` or `home/Pictures`. In Windows, you can move the complete home dir to some other path (I have seen this setting somewhere, but don't remember where), but you used the function to only move the Documents, Pictures or some other paths to somewhere else.

**Comment by bugith** [comment]
> You don't need to know GO to understand the linked line.
To override the home (without overriding %USERPROFILE%) you need to set %HomeDrive% and %HomePath% before starting syncthing.
We can't without a batch (synthing.exe is a no-gui binary), but more, we don't care with %HomeDrive% nor %HomePath% which make %UserProfile%, as the "~Location~" function (I don't know the english title of the properties sub-tab) was used, as you say.

>~ always means home, not home/Documents or home/Pictures
I know. That's why I wrote path\.. ;) , path meaning Docs or Pics

> If you use SyncTrayzor, there is a setting to set env vars.
No I don't, but at least, then maybe Synctrayzor could do this or prompt user to select a default directory as parent for new shares. But this doesn't address the second part of my initial _should both_ ... ok, well my idea was **not** to redefine the ~ meaning (I didn't though somebody could read me this way, sorry). But I agree your comment wweich, then maybe the "Target" field should be prefilled this default parent... (still possibly overridden by ~ strike) ...
Personally using core st only, I use to create a DataDrive:\Users\Her\Documents\..\Sync folder in which I drop the .exe, then run st for the first time and as soon remove the Default share which I advise to use the target as default parent for further shares... both because the place is nice and the name is cool: User\Drive\Sync  
Even on computers were I need to manually* move users' system data folders, I always insert the \Users\ betweeen the root letter and the user folder so that the tree structure is the same on both system and data drive, at least down to the User own folder (never D:\User, this way D drive can also be used for something else than storing profiles, nor even simpliest D:\Documents for single user computer, for the same reason and because...who knows).
* I read somewhere that this can be done for all user and whole tree at install time, hitting Shift+F3 at the time Windows installer prompts for reboot for next step, or something like pushing power button at a certain moment of the install, then restart/repair or so and throw it this Shift+F3 to give him the path of the Users folder
