### ISSUE TITLE
gui: Differentiate between adding a new device to existing folder and adding a new folder in the prompts

### ISSUE THREAD

**Issue by novoid** [syncthing/syncthing#3882]
I found a subtle usability bug which most likely happens to most users of SyncThing. If necessary, I can give a real world scenario with two users and one share with more lines of text than the abstract scenario below.

# what happened

Host `alice` is sharing with host `bob` a folder. Now, host `eve` is also adding the same folder from `alice`. When `eve` is sending a share-invitation to `bob`, bob gets following message in his web interface:

> New Folder ___________________________ 2017-01-06 16:04:14
> eve wants to share folder "myfolder" (6cazj-4pcl3). Add new folder?

Therefore:

```
          alice   <------->   bob       
           |                                                
           `-->   eve     
```
... turns into either:
```
          alice   <------->   bob  
           |                  ^
           `-->   eve  ------'
```
OR: it is a completely new shared folder.

Here we go: host `bob` has no clue whether or not (a) this new folder resembles an already shared one or (b) this is a new shared folder.

For (a) the user just have to click on `Add` and he is done.

For (b) the user wants to locate (and probably create) a new directory in his folder hierarchy so that this shared folder can be used as a new directory containing a shared SyncThing folder.

Therefore, user of host `bob` has to click on `Add` to test if it is (a) or (b). For (a), he is finished because there is no further input dialog window. For (b), there is this edit folder window which he might Cancel in order to decide how he is using this new folder, re-doing old shares, and so on. 

# what you expected to happen instead

This usability bug can be fixed by changing the notification message so that the user clearly notices that this is going to be a new folder (b) or this is just an acknowledgement of adding a new host to an already existing folder (a).

Possible solutions:

case (a):
> New Folder ___________________________ 2017-01-06 16:04:14
> eve wants to be added to the existing folder "myfolder" (6cazj-4pcl3). Add eve?

case (b) works good with the existing message text:
> New Folder ___________________________ 2017-01-06 16:04:14
> eve wants to share folder "myfolder" (6cazj-4pcl3). Add new folder?

# Version Information

Syncthing Version: v0.14.16, Linux (64 bit)
OS Version: Xubuntu 1604 & Debian stable

PS: I'll never do ASCII art in Github markdown any more. It's broken/impossible. :-(

**Comment by AudriusButkevicius** [comment]
You have ID's which you can check, you are not forced to accept anything.

**Comment by novoid** [comment]
Yes, it is possible to check all my 42 obscure (i.e., hard to remember due to random strings) IDs manually to see whether or not any one of them is matching the new(?) one. This is correct.

But I expect SyncThing to spare me this annoying task and tell me right away what SyncThing already(?) knows: is this (1) a new source of data or is this (2) just adding a new "player" to an already existing shared folder. Those are two fundamental different things and SyncThing is now pretending that both things are the same. Maybe technical they are the same. However, certainly not for the users.

My concern is not about security, my concern is about usability.

**Comment by AudriusButkevicius** [comment]
You can choose your own ID's and by not doing so, the usability suffers.
Regardless it's a understandable feature request, but calling it a bug, is definately misclassifying.

**Comment by novoid** [comment]
I am sorry.

To my defense: In our software company we consider usability issues as bugs as well. This is a strategic decision how usability issues are handled.

Note to myself: I refrain from assuming that every software project has the same understanding related to usability and user experience.

**Comment by novoid** [comment]
> You can choose your own ID's and by not doing so, the usability suffers.

I do have some thoughts about this as well: when I share a folder with my brother "Bob", I tend to name the folder `share-bob`. Now my brother Bob gets an invitation to an ID named `share-bob` which does not make any sense at all to him.

But this is just a minor side-mark since I have no clue how to handle this usability issue given the fundamental principles how SyncThing is using IDs.

So: using my own perfectly fine IDs still does not keep usability (for peers) high.

My personal workaround so far: if possible, try to use IDs that describe the content and not the persons involved or devices.

**Comment by bugith** [comment]
@novoid, I already met your first point, in the sense I wondered how friends to who I send invitation to a share will deal with the Label I choose for me. Maybe the message could insist on the fact one can change this Label later. Currently, my workaround is to change my own Label so its name reflects what I want it reflects in my friends' mind so they are subliminally driven to create a well-name-path from scratch (can't be changed without redoing all), then when established, label-back mine (although this method brings some friendly first-use to beginners, it doesn't expose how artificial it is) - I think the new behaviour with random id plus label is far better that the previous id-only one which drove IDing folders like AliceBob and paths like .... hummm.
For your second point, an idea comes to me : well the message states the Label I choose and that fine. If the Label field was not yet populated on the new device, it would be a good thing (maybe a text comment below stating "Remote device xxxx labeled this ({{folderID}}) folder "{{folderLabel}}", but there is a big probability you want to change this now from your own PoV"

**Comment by piotr-dobrogost** [comment]
@bugith 
> I think the new behaviour with random id plus label is far better

What *new behavior* do you refer to here?

**Comment by bugith** [comment]
https://github.com/syncthing/syncthing/releases/tag/v0.13.0

**Comment by bugith** [comment]
There is a forum topic that also talks about the 3 cases : createNew|acceptNew|editYetExistingLocal (the case editYetExistingRemote being an other name for acceptNew, ie folderID is already set) about how the modal popup may be more simple in some cases : https://forum.syncthing.net/t/gui-polish-editfoldermodalview-html/11198/6
Also there is a discussion about more-than-2-possible-cases when coding html GUI that prevented me-unskilled-coder to even try to propose a PR : #4713 https://github.com/syncthing/syncthing/pull/4713#issuecomment-361057165 from @imsodin

**Comment by imsodin** [comment]
This is not about the edit-folder-modal (though somewhat related), so lets not mix it up. However in the web UI there is a [distinction between adding a new folder and sharing an existing folder with another device](https://github.com/syncthing/syncthing/blob/master/gui/default/index.html#L194). That seems to be the case since at least the beginning of 2016, so before this bug report was opened. @novoid Please reopen if you still have this problem.

**Comment by novoid** [comment]
I re-tested the issue today.

1. Create a share from my mobile (Android; ST v0.14.43)
2. Share folder with host A (Xubuntu; ST 0.14.44) and host B (Debian; ST 0.14.43)
3. Accept all share invitations so far
4. Now add host A to share the folder in the web interface of host B
5. Host A now gets the message "[...] Share this folder?" (instead of "[...] Add new folder?") 

So to my perspective, this issue is solved.
