### ISSUE TITLE
Add Remote Device does not work in lynx

### ISSUE THREAD

**Issue by PanderMusubi** [syncthing/syncthing#3887]
Add Remote Device does not work in lynx after starting from command line:

    lynx http://127.0.0.1:8384/

### Version Information

Syncthing Version: v0.14.18
OS Version: Raspbian 8 and Ubuntu 16.10
Browser Version: 2.8.9dev1-2+deb8u1

**Comment by AudriusButkevicius** [comment]
It probably doesn't work on Netscape either, but we have to pick our battles.

**Comment by PanderMusubi** [comment]
Fine. Follow-up question: how to easily configure a remote system that has no X? Is there an interactive interface such as curses?

**Comment by imsodin** [comment]
https://forum.syncthing.net/t/headless-ubuntu-vps/2892

**Comment by AudriusButkevicius** [comment]
There is a:
1. REST API
2. ~/.config/syncthing/config.xml 
3. stcli (which somewhat dead/broken and needs TLC)
4. Expose web UI on the public interface with a password and access from a different machine.

**Comment by PanderMusubi** [comment]
Thanks. For personal network, temporarily using number 4 is the most user friendly.
