### ISSUE TITLE
Failing lookup relays for ipv6

### ISSUE THREAD

**Issue by grinapo** [syncthing/syncthing#3888]
This originates in syncthing-android, https://github.com/syncthing/syncthing-android/issues/817

### Version Information

App Version: 0.9.2
Syncthing Version: v0.14.14
OS Version: Android 6.0.1 (samsung S7)

### description

Cannot discover devices. The log contains an unsettling comment:
dynamic.go:65 ... failed to lookup dynamic relays ... dial tcp: lookup relays.syncthing.net on 1111:2222:3333::33:53: dial udp: too many colons in address 1111:2222:3333::33:53:

(It's the DNS server's ipv6 address.)

Probably the reason behind **no sync** at all unless ipv6 is shut down completely.

**Comment by AudriusButkevicius** [comment]
Now I've realized it's something else, it's failing to do DNS lookups over IPv6. I'll reopen the one on android as that's where the problem is.
