### ISSUE TITLE
Also offer folder setting Receive Only ?

### ISSUE THREAD

**Issue by PanderMusubi** [syncthing/syncthing#3889]
At the moment one can select Sent Only or Sent & Receive for a folder. For some situation, I would like to make the destination folder Receive Only. Support, at the master a mistake gets made (for example thick fingers in the app on a smartphone) and it is set by accident to Sent & Receive, then the destination can push to the master.

When offering a Receive Only option, is is prevented form the side of the destination, making it double save, and the destination never has to concern itself about sending.

### Version Information

Syncthing Version: v0.14.18
OS Version: Ubuntu 14.10
Browser Version: (if applicable, for GUI issues)

**Comment by canton7** [comment]
See #3780.

**Comment by PanderMusubi** [comment]
Thanks, had trouble finding it.

**Comment by canton7** [comment]
It's the 6th result down in a search for "receive only": https://github.com/syncthing/syncthing/issues?utf8=%E2%9C%93&q=receive%20only

**Comment by tdbe** [comment]
I believe the behaviour of "write-only folder type" #3780 is not what common users would expect from a Receive Only folder. What most non-advanced users would expect is that a Receive Only folder does not delete or revert anything or make any changes to the contents already there. Instead it should pull the files from the remote folder(s) only if the files don't already exist (in a modified state or original state) OR the files didn't already get specifically deleted by the user in the Receive Only folder.

Usecase example: You want to sync your phone photo library. Your phone is Send Only. Your laptop is Receive Only. You want new photos from your phone to be backed up to the laptop. You want deletions on the phone to NOT be synced. You want modifications or additions or deletions on the laptop to NOT be synced with your phone's DCIM folder.

**Comment by PanderMusubi** [comment]
Personally, I sync folder with pictures on my smartphone in read-write mode with a folder on my computer. From both sides I can delete and add pictures. Just as I want it. but for me that is another use case. The receive only for me is for devices that play music. They receive only MP3 files from a central device.
