### ISSUE TITLE
Syncing certain individual files

### ISSUE THREAD

**Issue by PanderMusubi** [syncthing/syncthing#3890]
In some cases, users need to sync only a certain file from a directory, all other files are not allowed to be synced at all. This can be because they are large and irrelevant or they are not allowed to get distributed.

This could be solved by supporting syncing of individual files, or by adding a filter (exclusive or inclusive) that supports regular expressions for a folder. Perhaps a depth or non-traverse function could also solve this. This all will probably not be the most simple feature to use, unfortunately. Curious what the plans are from syncthing regarding this.

### Version Information

Syncthing Version: v0.14.18
OS Version: Ubuntu 16.10
Browser Version: (if applicable, for GUI issues)

**Comment by canton7** [comment]
Syncthing already has the ignores system which does this. Also see #2491.

**Comment by calmh** [comment]
Indeed. Currently, to sync only `nicefile.txt` in `foo/bar` and nothing else in that directory, plop the following in .stignore:

```
!foo/bar/nicefile.txt
foo/bar/*
```

**Comment by AudriusButkevicius** [comment]
Also please read the docs, search open issues and the forum, as so far 3 of your issues got closed immediately just because you haven't done your homework. If you need help or have questions, use the forum, and not open issues.

**Comment by PanderMusubi** [comment]
Yes, sorry about that. Normally I am pretty thorough about this and I did search the open and closed issues. Not my sharpest day.

**Comment by AudriusButkevicius** [comment]
I suggest you refer to the docs first as we have quite extensive documentation

**Comment by PanderMusubi** [comment]
Will do. As a token of my appreciation for the work you all do on Syncthing, I just made a financial donation to the project.
