### ISSUE TITLE
There should be a setting to disable the weak hash while scanning

### ISSUE THREAD

**Issue by wweich** [syncthing/syncthing#3891]
Currently, we can disable weak hash for pulling by setting `weakHashThresholdPct` to 101 (I think).
But there is no way to disable it completely (e.g. for scanning).

There should be an (advanced) option to disable the weak hash.

### Version Information

Syncthing Version: v0.14.19
OS Version: Manjaro / Ubuntu 16.04

**Comment by DrSchnagels** [comment]
Does that mean that a full rescan of 4 TB of data would be quicker because only the real hashing is done and not the intermediate, weakhash which looks for changes-only?!
A fresh rescan, or a new setup of Syncthing, would scan fastest with all other devices disabled?

**Comment by AudriusButkevicius** [comment]
Its nothing todo with that. Its exactly like the old behaviour, just that we are using two hash functions instead of one.
