### ISSUE TITLE
Add arm64 package to apt repository

### ISSUE THREAD

**Issue by PanderMusubi** [syncthing/syncthing#3894]
Please add a deb package build for arm64 to the apt repository. See also https://forum.syncthing.net/t/add-arm64-build-to-ppa/8991/2

**Comment by calmh** [comment]
This is done.

**Comment by janost** [comment]
The repository still doesn't contain arm64 deb packages for `stable` and `candidate`.
I may have missed something or some other configuration might be required.

**Comment by calmh** [comment]
Erh, yeah, I fucked something up.

**Comment by calmh** [comment]
How about now.

**Comment by janost** [comment]
Thanks, the `syncthing` package is now there, although `syncthing-inotify` seems to be still missing.

**Comment by calmh** [comment]
yeah there is no arm64 build for syncthing-inotify currently

**Comment by janost** [comment]
Oh, I see. I'm going to add it if that's alright.
