### ISSUE TITLE
Improve Global Changes's "Time" column formatting

### ISSUE THREAD

**Issue by scienmind** [syncthing/syncthing#3895]
Right now the "time" column of "global changes" report is of (very narrow) fixed length, resulting in date being split into 4 lines, regardless of the window's width.
![image](https://cloud.githubusercontent.com/assets/11633330/21858860/40dcb570-d833-11e6-9e50-a59fba06fea9.png)

Expected behavior:
"Time" info spans into a single line (or at least 2 lines: date and time) if enough window width is available.
### Version Information

Syncthing Version: v0.14.19
OS Version: Windows 10 x64

**Comment by wweich** [comment]
Where did you get the info, that this column has a fixed width. There is no fixed width in the code.
You probably have a path with to many unbreakable characters, so the path column get wider and the time column shrinks to make space.
The path cell should be set to even break within words. (CSS `word-break: break-all;`). But in my experience browser than prefer to break within words, even if there are breakable characters and even if the resulting line count would be the same. That would mean ugly breaks for all of us, even if we don't need them.

My list has a optimal time column width:
![grafik](https://cloud.githubusercontent.com/assets/1026763/21859492/13a197f2-d82d-11e6-9b65-a1ca26ce0679.png)

**Comment by scienmind** [comment]
Yep, you are correct, your Time column indeed have optimal layout
(tried to find any hard-coded limit myself in the code prior to opening this issue, eventually blamed the failure to find it on my ignorance;) )
And indeed i have some long paths down the list. That's probably the cause...

Maybe limit time lines to breaking into 2 lines max then? 
The width gain of placing "2017" and "AM" into separate lines isn't huge. And having it in 4 lies all the time due to one long-path file is quite ugly.

Also maybe allow the whole pop-up to be wider if main window allows it?

**Comment by calmh** [comment]
(Bug, as the date can even get pushed outside of the modal)
