### ISSUE TITLE
Move TempNamer to ignores too

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#3899]
This is similar to #3779:
While fixing a race in the FS notification PR (fswatcher package), I stumpled over `TempNamer`, which is needed for its `IsTemporary` function. It is currently used in model and and scanner packages. It is passed as part of a struct from the model to the scanner package and for the case it is not passed, an interface and replacement type had to be implemented in the scanner package. The same would have to be done for the fswatcher package. However the whole thing is completely static: It is defined at init and then never changed.
Therefore I propose to move it to the ignores package, such that it is easily accessible without passing it around (ignores is imported in all places already).

What do you think about this - do I get the green light to do this?

**Comment by AudriusButkevicius** [comment]
Sounds fine to me. Yet see what @calmh says.

**Comment by calmh** [comment]
Doit
