### ISSUE TITLE
Document in Use

### ISSUE THREAD

**Issue by ingoglia** [syncthing/syncthing#3903]
- what happened: I attempted to open one of my documents and received this message:
_'Document file 'XXX.odt' is locked for editing by:
Unknown User
Open document read-only or open a copy of the document for editing.'_
 
 - what you expected to happen instead : I expected to be able to open my document.

 - any steps to reproduce the problem: This problem seems to occur intermittently. I am unsure why. It seems not to occur on my android device, however it occurs on both my Lenovo Z570 and my other Lenovo machine which is a different model, both running the same version of Debian.  I have tried closing Syncthing and powering off both of my other machines. I still cannot access the file.

### Version Information

Syncthing Version: v0.14.18, Linux (64 bit)
OS Version: Debian 8.6 Jessie

**Comment by AudriusButkevicius** [comment]
Please use forum for support, like explained in the isaue template.
