### ISSUE TITLE
"Syncing (X MB to go)" instead of "Syncing (99%)"

### ISSUE THREAD

**Issue by benshep** [syncthing/syncthing#3908]
I have a number of folders with lots of data (pictures, music, documents), that I make frequent small changes to. The status line in the UI "Syncing (99%)" is then almost useless, since the 1% that is unsynced can represent anything up to 700MB. It would be much more useful if this could be replaced with something like "Syncing (50 MiB to go)".

**Comment by AudriusButkevicius** [comment]
Potato-potato. There will always be unhappy people with either, so I'd just be inclined to close.

**Comment by benshep** [comment]
Well, I would expect this to be a pretty common issue. Could we make it selectable perhaps?

**Comment by AudriusButkevicius** [comment]
You already have the 'Out of Sync -- N files, X bytes'  tho, is that not good enough?

**Comment by benshep** [comment]
Yes, if I go into the folder view. The status line is a good at-a-glance indicator of where everything is up to. But it's mostly useless for me, since most of the time it sits at "Syncing (99%)" or similar.

**Comment by AudriusButkevicius** [comment]
Sorry, but this is not good enough. The information you are after is already there, so I'd rather you back this up by a pull request making it switchable, oppose to a ticket which will never get closed as I suspect most people don't really have a preference over this and are probably not interested in solving this. Hence closing.

**Comment by benshep** [comment]
Fair enough, it's your project after all! I'd be happy to have a go at tinkering and maybe produce a PR. Is there any specific documentation I should look at? (Trying not to waste your time...)

**Comment by AudriusButkevicius** [comment]
I am one of the people dveloper community hates, where code is thw best documentation.

You can look at the HTML template howthe "Out of sync" numbers are produced, and replace it where the percentage is shown with that. Any UI changes you make need to be built, meaningthe build process is:
```
go run build.go assets
go run build.go
```

**Comment by calmh** [comment]
There is actual documentation, though.

https://docs.syncthing.net/rest/db-completion-get.html
https://docs.syncthing.net/rest/db-status-get.html
https://docs.syncthing.net/events/foldercompletion.html
https://docs.syncthing.net/events/foldersummary.html

**Comment by scienmind** [comment]
@benshep, if you gonna take a go a it, maybe something hybrid would possibly please everyone, like:

`Syncing (22% - 570 MiB to go)` 
or 
`Syncing (22%, 570 MiB to go)`

(although it may be too much clutter for the main view... idk... :thinking:)
