### ISSUE TITLE
Global changes button

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#3909]
The string for this new button isn't available for translation in Transifex

**Comment by calmh** [comment]
Thanks for the pointer

**Comment by calmh** [comment]
Thanks for the heads up

**Comment by bugith** [comment]
My pleasure is to help (a bit)

**Comment by HaleTom** [comment]
For other googlers like me, if you're wondering about the function of this button, see [here](https://github.com/syncthing/syncthing/issues/4326).
