### ISSUE TITLE
SD card in android cannot be writed

### ISSUE THREAD

**Issue by coolnik** [syncthing/syncthing#3910]
SD card in android cannot be writed 
despite the fact that the setting is activated and A) the SyncThing and B) the Android system.
SM-G930

### Version Information

Syncthing Version: 0.14.16
OS Version: Android 6.0.1

**Comment by wweich** [comment]
1. wrong repo: https://github.com/syncthing/syncthing-android/
2. dup of syncthing/syncthing-android#29
3. not fixable at the moment

**Comment by wweich** [comment]
Also, there is no setting in Android to allow Apps write access to external SD card. Just a permission to access the file system, which is the primary storage, not the secondary (external SD card / USB sticks).
You can use the adoptable storage and set the sd card to primary to let Syncthing write to your sd card.

**Comment by coolnik** [comment]
Why is it impossible? Many applications able to write to the SD card. 
For example ES File Manager. 
https://play.google.com/store/apps/details?id=com.estrongs.android.pop

**Comment by AudriusButkevicius** [comment]
Your questions are answered in the issue you've been refered to. Please read it.

**Comment by coolnik** [comment]
ok. thank you. it's a pity
otherwise the app is great
