### ISSUE TITLE
macOS Kernel Panic

### ISSUE THREAD

**Issue by cynicer** [syncthing/syncthing#3911]
I'm using syncthing for about a year now on my MacBook and my Linux devices. I'm always up to date with the newest version of syncthing released. Since 5.1.2017 I' experiencing some random macOS kernel panics which refer to an issue with syncthing.

My system crashed 5 times the last 12 days due to this error. Every time it occurred I had my MacBook in sleep mode and tried to wake it up in clamshell mode (2 external Monitors connected) with my external Bluetooth keyboard. After like 30 seconds of not waking up the MacBook reboots and displays the attached error message.

I know a macOS kernel panic is none of your business, but isn't it strange that syncthing should have caused it?

### Version Information
Syncthing Version: v0.14.19, Mac OS X (64 bit)
OS Version: macOS Sierra 12.2.2 16C67

<img width="1027" alt="screen shot 2017-01-05 at 13 57 56" src="https://cloud.githubusercontent.com/assets/5718282/22030505/1983284c-dcde-11e6-8516-db2ec28efeb6.png">
<img width="1010" alt="screen shot 2017-01-05 at 19 34 53" src="https://cloud.githubusercontent.com/assets/5718282/22030507/19a6feb6-dcde-11e6-9e2a-0a9bd1eea175.png">
<img width="1005" alt="screen shot 2017-01-12 at 15 42 14" src="https://cloud.githubusercontent.com/assets/5718282/22030509/19a90d82-dcde-11e6-9039-7203d9e50433.png">
<img width="1026" alt="screen shot 2017-01-13 at 10 38 40" src="https://cloud.githubusercontent.com/assets/5718282/22030506/19a60a88-dcde-11e6-9bf9-ed8d307a14c7.png">
<img width="1029" alt="screen shot 2017-01-17 at 17 40 04" src="https://cloud.githubusercontent.com/assets/5718282/22030508/19a8541e-dcde-11e6-8373-6499dd0093c1.png">

**Comment by calmh** [comment]
This is neat. Apparently Syncthing tickles something that crashes your system as it always crashes in the same place. I have no idea what that could be, and I run the same kernel as you (at least the same version, maybe not the same hardware) with no issue. It's sort of by definition that the bug is on the kernel side if that is what crashes, even if we trigger it, though... It's also fairly difficult to debug. :/

**Comment by cynicer** [comment]
And ist crashed again, I will try to capture the moment next time. The kernel panic occurred at 10:28 AM, but I also found logfile for syncthing at 02:37 AM. I wen't to bed at around 01:00 AM so I wasn't awake while this occurred. Maybe syncthing wakes up in powernap and somehow confuses the Kernel?

[log.zip](https://github.com/syncthing/syncthing/files/719020/log.zip)

**Comment by khaled** [comment]
I've seen the same exact crash several times, running 0.14.18.

**Comment by calmh** [comment]
There are no Syncthing logs here, and nothing actionable for us.

**Comment by cynicer** [comment]
I'm waiting for it to occur again. But you know, bugs don't like to be traced :D
