### ISSUE TITLE
The -logfile flag doesn't work together with -no-restart (STNORESTART=1)

### ISSUE THREAD

**Issue by DrStrangepork** [syncthing/syncthing#3912]
### Version Information

Syncthing Version: v0.14.19
OS Version: OSX

Running with the following command: `/usr/local/opt/syncthing/bin/syncthing -no-browser -no-restart -logflags=7 -verbose -logfile=/var/log/syncthing.log`

No log file is created, no matter what settings I use for `logfile` or `logflags`. Running the command from a shell shows the expected logging to stdout with the VERBOSE logging (when specified). It just never writes to the logfile. I have run this on multiple machines running El Capitan and Sierra with same results.

**Comment by calmh** [comment]
The `-logfile` flag is incompatible with `-no-restart`, as `-no-restart` disables the monitor process and it's the monitor process that implements `-logfile`. This is either a bug or a user interface issue or both.

**Comment by AudriusButkevicius** [comment]
On windows I can't get it to work at all, but maybe thats a cygwin thing.

**Comment by calmh** [comment]
Hopefully, as the option was added specifically to support Windows :D

**Comment by wweich** [comment]
If you are using a OS-level process management / service manager, that should have the ability to write a logfile from stdout.
Also, you could just replace `-logfile=/var/log/syncthing.log` with `2>&1 >>/var/log/syncthing.log`. Only downside I know of is a not so easy log rotate.

**Comment by calmh** [comment]
Syncthing doesn't do any sane log rotation on it's own either. The option was added mostly to aid in getting some logging running on Windows where syslog doesn't exist and piping wasn't always an option, IIRC.

**Comment by AudriusButkevicius** [comment]
Actually scratch that, I have STNORESTART=1 in my .profile.

**Comment by DrStrangepork** [comment]
IMO, log rotation is not a critical offering of logging for a service like syncthing. That can easily be handled by logrotate, et al.

Also, using redirection - `2>&1 >>/var/log/syncthing.log` - does not work, as redirection is a shell-level function. I tried that exact configuration in the OSX service configuration (`plist`), and the service just crashes immediately. Doing the same thing within a shell script should work just fine, but that should be considered only a work-around, IMO.

**Comment by calmh** [comment]
If you're using launchd like it sounds like, you can let it do the logging:

```
		<key>StandardOutPath</key>
		<string>/Users/jb/Library/Logs/Syncthing.log</string>

		<key>StandardErrorPath</key>
		<string>/Users/jb/Library/Logs/Syncthing-Errors.log</string>
```

**Comment by DrStrangepork** [comment]
Ah, that was my problem. Those paths are set to `/usr/local/var/log/syncthing.log`, and the proper logging settings are reflected in that file.

**Comment by ProactiveServices** [comment]
This hasn't quite made it to the live docs yet, but -no-restart means: `Disable the Syncthing monitor process which handles restarts for some configuration changes, upgrades, crashes and also log file writing (stdout is still written).`
https://github.com/syncthing/docs/pull/278/files

**Comment by ProactiveServices** [comment]
So I guess -logfile docs ought to have a mention about its evil twin -no-restart

**Comment by canton7** [comment]
Might be worth having syncthing tell you that those flags are incompatible if you try to use them together? Happy to do a PR of noneone else cares.

**Comment by calmh** [comment]
Please do. If we can't make it work (which may be a little bit tricky), the least we can do is reject the invalid combination.

**Comment by DrStrangepork** [comment]
This might be a procedural question, but shouldn't this be closed on merge rather than closed on Commit?

**Comment by canton7** [comment]
It was closed on merge.
