### ISSUE TITLE
protocol: error due to filename not in canonical format

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing#3913]
On my OSX machine I had some files that were (strangely) named as follows:
```
/Users/lhoste/Sync/Private/Huis/Hove/\home\lhoste\mnt\.Trash-1000\files\IMG_20160725_194802.jpg
```
These were synchronized to my Linux machine without problems.
Unfortunately, my Windows machine keeps reconnecting to my OSX and Linux machine due to a protocol error:
```
[3JWUT] 21:01:10 INFO: Connection to GJGNAO6 closed: protocol error: index update: "Private/Huis/Hove//home/lhoste/mnt/.Trash-1000/files/IMG_20160725_194654.jpg": filename not in canonical format
```

Running syncthing v0.14.19 on all hosts.

**Comment by calmh** [comment]
Hmm, yeah, it doesn't like that. It should fail incoming files with backslashes earlier and in some other way though. ..

**Comment by calmh** [comment]
Negatory, that's not the problem... Wonder what it is then.

**Comment by calmh** [comment]
So what's happened here is that these files were introduced into the system before the checks we added in 0.14.15 or thereabout. That caused some amount of chaos, that the checks in question prevent nowadays. Then everything was fine for a while. Now something about the files changed, causing them to get sent over the wire and **bam**.

**Comment by calmh** [comment]
Legacy, not going to get solved.
