### ISSUE TITLE
Syncthing running another process

### ISSUE THREAD

**Issue by AlexeyShirshov** [syncthing/syncthing#3914]
I set syncthing at startup on my windows server machine. Here is schedule
![12](https://cloud.githubusercontent.com/assets/5462866/22053891/5e6e03f6-dd64-11e6-93fd-bf5a691e3223.png)
here is action pane
![11](https://cloud.githubusercontent.com/assets/5462866/22053898/692c2b9c-dd64-11e6-898b-d67fe9a72069.png)
but after restart I see two syncthing process and webui doesn't show me my folders.
![10](https://cloud.githubusercontent.com/assets/5462866/22053962/97a1ffe2-dd64-11e6-8066-4c24678cbd38.png)
It seems like syncthing starts another child process. I think it's a bug. I need to stop my job, manually kill second syncthing and run job again.

**Comment by calmh** [comment]
https://docs.syncthing.net/users/faq.html#why-do-i-see-syncthing-twice-in-task-manager

See also `-no-restart` which you should probably be using when running under a service manager.

**Comment by AlexeyShirshov** [comment]
Think you, I'll try and let you know. But why I doesn't see my folders in webui?

**Comment by canton7** [comment]
What exactly do you mean, "I doesn't see my folders"? Do you mean there's only the 'default' folder? Are there no folders at all?

There are instructions for how to start Syncthing as a scheduled task [in the docs](https://docs.syncthing.net/users/autostart.html#windows).

**Comment by AlexeyShirshov** [comment]
Yes, I only see DefaultFolder, but when I run syncthing manually, there is no such folder, 'cause I remove it and create others. I setup startup according to manual and make all the steps. General tab is
![14](https://cloud.githubusercontent.com/assets/5462866/22056871/5376bb14-dd73-11e6-9c5f-71417f18c35b.png)
I suspect syncthing run under different user account, for this reason I can't see my folders, but as you see in screenshots it runs under corp\alex. This is my account.

**Comment by AudriusButkevicius** [comment]
This sort of stuff, including the initial question should live on the forum. Furthermore, I'd be awesome if people looked at the docs before opening issues.

**Comment by AlexeyShirshov** [comment]
-no-restart switch does not help. I still doesn't see my folders though there is only one process running now. Why?
Here is my general tab
![15](https://cloud.githubusercontent.com/assets/5462866/22137294/44b33156-deeb-11e6-8747-7535e4624e87.png)

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
