### ISSUE TITLE
Customize syncthing home page

### ISSUE THREAD

**Issue by acerdan4** [syncthing/syncthing#3916]
I was trying to be able to personalize a little the main page of the application, made for computer.
Could you help me?
Thank you

**Comment by AudriusButkevicius** [comment]
Read the issue template again.

**Comment by acerdan4** [comment]
i'm don't understand

**Comment by Ferroin** [comment]
This isn't a bug, it's a request for support, and thus should go to the Syncthing Forum, not here.
