### ISSUE TITLE
I was trying to be able to personalize a little the main page of the application, made for computer. Could you help me? Thank you

### ISSUE THREAD

**Issue by acerdan4** [syncthing/syncthing#3917]
I was trying to be able to personalize a little the main page of the application, made for computer.
Could you help me?
Thank you

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by canton7** [comment]
If you open one issue and it's closed, don't just go and open a duplicate issue.
