### ISSUE TITLE
Per device queue / Load distribution issue

### ISSUE THREAD

**Issue by arneko** [syncthing/syncthing#3919]
I am not sure how if this is out of scope or even technically feasible. But since I didn't find any similar reports, I'd at least like to mention this because it's been bugging me lately:
Say you have 3 devices, 2 of them in your LAN, the other one on a slow connection somewhere on the planet. One device in your LAN has a larger subset of your data than the other, the distant node has the complete set. 
What I frequently observe in these situations is, that syncthing is synchronizing at very low speeds, instead of quickly exchanging the available files available in your local network and then proceeding to start downloading the files from the slower connection. 
A workaround is to pause the distant device on the least "populated" device, that way you get your files at LAN speed while still downloading from the distant node. A better solution might be, to have a "per device queue", and having files downloaded depending on their origin.
In the end, you might argue, the time by which you receive your complete data set on your local network would be (about) the same. But keep in mind that your local machines are not always online at the same time, so you might end up downloading data twice from the distant node.
I actually hope that someday I'll manage to have a closer look at the sources of this awesome piece of software, but for now I'm afraid I have to content myself with bug reporting....

### Version Information

Syncthing Version: Any I guess

**Comment by arneko** [comment]
This issue also works in reverse, btw, which might even be more frustrating:
You have a complete device on your LAN and an empty one, and then there is a subset somewhere on the Internet. Syncthing will assume all the data is equally available and will start to download at random. Any file on a distant machine will take ages to complete -> your (empty) computer will spend most of the time downloading files from that subset, since they are takting so much longer to complete.  

If your empty machine happens to be a laptop, that you carry between the two locations you end up spending 90% of your time downloading files, that are already on the other side, and are no use once you get there...

**Comment by calmh** [comment]
Yeah, this is a tricky point. The current behavior, which I should document in a blog post or something, makes sense for the case where all devices are online and using the default "random" pull order. That should be fairly optimal, even when two devices share a slow connection to the third. They'll each pull different files from the slow device, and share those internally with each other. For large files there will be some duplication, despite the temp indexes exchanged between the local devices.

One could imagine a further pull sort order - by device availability. A device could have a manual or automatic priority of some kind, and we process the fastest / best available files first.

While pulling, there are a set number of "pullers" (parallel routines) that each fetch blocks from the others. They work by balancing requests from the available devices. That is, with for example 16 pullers and two devices, each device will usually have eight block requests outstanding. That means we will always request a few blocks from the slower device, even if they are available on a faster device. But the faster device will have time to serve much more requests in the same time.

**Comment by arneko** [comment]
You are really fast...
I noticed that many files seem to be stuck for a time at like 95%, which is what you are describing - but there must be times when all the pullers are occupied with one device, otherwise the described behaviour wouldn't happen I guess? And by "there must be times", I actually mean 95% of the time, which of course depends on the ratio of the available speeds...

**Comment by AudriusButkevicius** [comment]
The number of concurrent files dowloaded is set by increasing copiers in advanced config, which I suspect will simply remove the problem.

**Comment by AudriusButkevicius** [comment]
As in,  having as many copiers as devices, this way you know that you'll always have atleast one file being worked on by the fast device even if the rest of the devices are slow.

**Comment by AudriusButkevicius** [comment]
Also, I am not sure the heuristic @calmh described is correct, I am onthe phone so difficult to check but as far as I recall the puller prefered downloading from a device with the least requests outstanding, which in general should mean that this problem should not exist, as the slow device will always have stuff outstanding simply due to being slow. It could be that the lan device actually doesn't have the data you are after (as the pull order is random), so there is no other path apart from the slow path.

**Comment by calmh** [comment]
Ah, yes, increasing copiers may help. There will then be blocks for multiple files given to the pullers simultaneously, which may help distribute things. But as Audrius says, requests will always be given to the device with the fewest outstanding requests. That should mean that with two devices and 16 pullers (the default) we will keep both devices saturated with a queue of eight outstanding requests. We might still fetch 99% of the data from the faster device, but as soon as the slow device has finished a block it will have a shorter queue of outstanding requests, and get asked for another block...

**Comment by arneko** [comment]
I am taking your word for it and will not start arguing ;-) so, according to the docs:

>*copiers, pullers, hashers*  The number of copier, puller and hasher routines to use, or zero for the system determined optimum....

What is the "system determined optimum"? It sounds like it would/should be "number of devices sharing this folder" or "number of devices online" (if it can be changed dynamically) with a threshold. it says 0 on my machine -> what is the performance penalty for increasing this?

**Comment by arneko** [comment]
Actually, the more I read about this, the less I understand what is happening... what do the copiers have to do with this? Let's say we started 8 files with 16 pullers - the 8 pullers that were downloading from the faster device should quickly proceed to download the next files. Since the 8 slower pullers are still busy, they shouldn't get any new tasks. The single copier we have on the other hand... I assume it is responsible for "completing" the files, that have been downloaded from different sources. Or is it needed to just complete any file and is somehow stuck with files not completed? Can you give me pointers in the sources? I feel like I need to understand this...

**Comment by AudriusButkevicius** [comment]
Copiers = number of concurrent files
Pullers = number of concurrent blocks fetched at one potentially from different files.

**Comment by AudriusButkevicius** [comment]
If one of the copier is stuck with some blocks from the slow device the other one can continue pulling blocks from the fast device for some other file.

**Comment by nrm21** [comment]
> But as Audrius says, requests will always be given to the device with the fewest outstanding requests. That should mean that with two devices and 16 pullers (the default) we will keep both devices saturated with a queue of eight outstanding requests. We might still fetch 99% of the data from the faster device, but as soon as the slow device has finished a block it will have a shorter queue of outstanding requests, and get asked for another block...

What if the number of outstanding requests were not fixed (at say 8 for this argument) throughout the life of the request but a sliding scale based on speed.  Say for the first 10 seconds you request 8 blocks from all clients but thereafter you adjust your (per device) request queue up or downward based on how fast they were coming in.  Kinda like the TCP window size acts.  If your computer is slow... you start requesting fewer and fewer blocks at a time from it until your down to 1 block at a time.  Meanwhile your getting say 25 - 50 at a time from the fast client.

**Comment by AudriusButkevicius** [comment]
Why do you think that would be better? If you have only one device that is far away and has high latency, setting number of blocks to 1 would be very bad.

**Comment by nrm21** [comment]
Well then the number of devices could also be a function of the algorithm.  The fewer devices overall, the less effect queue length has.  Or maybe the algo is completely ignored if the number of unique devices available to serve a file drops below a point.

Obviously whatever algo is picked, there would always be some corner cases that make it suboptimal to work around.  Even current one.

**Comment by AudriusButkevicius** [comment]
I think this is addressed nowadays. In theory the two devices will pick a different source device to start downloads from.
