### ISSUE TITLE
Rate limiting is broken on ARM64

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3921]
Apparently the default rate limit of zero (no limit) breaks on arm64. The cause chain seems to be:

- [we create a zero rate limiter](https://github.com/syncthing/syncthing/blob/master/lib/connections/limiter.go#L68) (that `<` should be a `<=`, thanks to @AudriusButkevicius for noticing)
- [the zero rate is documented to drop all events](https://godoc.org/golang.org/x/time/rate#Limit)
- there is a bug (???) in the rate limiter package that makes this not actually happen, instead a zero rate limiter allows all events
- except, apparently on arm64 (???)

Last point to be confirmed, but seems to be the case...

**Comment by AudriusButkevicius** [comment]
```
marlin:/data/data/com.nutomic.syncthingandroid.debug $ ./main-arm64
false
false
false
false
false
false
false
false
false
false
false
false
false
false
false
marlin:/data/data/com.nutomic.syncthingandroid.debug $ ./main-armv5 # GOARCH=arm
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
```

**Comment by AudriusButkevicius** [comment]
https://github.com/golang/go/issues/18762
https://github.com/golang/go/issues/18763
