### ISSUE TITLE
UPnP port numbers backwards

### ISSUE THREAD

**Issue by as-com** [syncthing/syncthing#3924]
```
[EXBQL] 16:54:00 INFO: New NAT port mapping: external TCP address 71.248.165.187:28357 to local address 0.0.0.0:22000.
```
Expected result: Syncthing reachable from 71.248.165.187:28357.

Actual result:
![screenshot of PortMapper showing external port 22000 mapped to 192.168.1.30:28357](https://cloud.githubusercontent.com/assets/3819625/22224660/699dcbb2-e18d-11e6-9a1d-be2ac52bbf6c.png)
Syncthing is unreachable from 71.248.165.187:28357; folders take a very long time to start syncing from outside of the network.

Possibly related: https://github.com/syncthing/syncthing/pull/2980

### Version Information

Syncthing Version: v0.14.19
OS Version: Linux Mint 18.1 64-bit (Ubuntu 16.04)
Router: NETGEAR R6700

**Comment by calmh** [comment]
Mmhm

**Comment by calmh** [comment]
That should fix it I hope, thanks for the report!

**Comment by AudriusButkevicius** [comment]
Great detective work.
