### ISSUE TITLE
Add ability to ask for rescan of all folders via API

### ISSUE THREAD

**Issue by ProactiveServices** [syncthing/syncthing#3926]
I'd like to be able to send an API request to Syncthing asking it to rescan all folders.

The current API permits a rescan request only for a given folder ID. Whilst it's possible to send a request for the status of all folders, parse the output for the folder IDs, and then send individual rescan requests for each entry, it's a bit cumbersome.

**Comment by wweich** [comment]
You can already do that with `/rest/db/scan` without parameters. That's what the GUI does, when hitting "rescan all".

**Comment by uok** [comment]
Please update the [docs ](https://docs.syncthing.net/rest/db-scan-post.html) page which reads "Takes the _mandatory_ parameter folder (folder ID)"

**Comment by imsodin** [comment]
@uok Right above your comment there is a link to a pull request who does exactly what you are asking for.

**Comment by uok** [comment]
Thanks - I deleted my comment
