### ISSUE TITLE
The -logfile flag is no longer accepted

### ISSUE THREAD

**Issue by potentcocktail** [syncthing/syncthing#3931]
After updating Debian to Syncthing v0.14.20 "Dysprosium Dragonfly" (go1.8rc2 linux-386) jenkins@build.syncthing.net 2017-01-24 08:26:45 UTC

i can no longer start syncthing using the -logfile option.  I am not using it in conjunction with -no-restart or STNORESTART. Here is the complete output:

andy@smallfry:~$ syncthing -logfile=/tmp/syncthing.log
[monitor] 18:26:16 INFO: Log output saved to file "/tmp/syncthing.log"
[monitor] 18:26:16 INFO: Starting syncthing
18:26:16 FATAL: -logfile may not be used with -no-restart or STNORESTART
[monitor] 18:26:16 INFO: Syncthing exited: exit status 1
[monitor] 18:26:17 INFO: Starting syncthing
18:26:17 FATAL: -logfile may not be used with -no-restart or STNORESTART
[monitor] 18:26:17 INFO: Syncthing exited: exit status 1
[monitor] 18:26:18 INFO: Starting syncthing
18:26:18 FATAL: -logfile may not be used with -no-restart or STNORESTART
[monitor] 18:26:18 INFO: Syncthing exited: exit status 1
[monitor] 18:26:19 INFO: Starting syncthing
18:26:19 FATAL: -logfile may not be used with -no-restart or STNORESTART
[monitor] 18:26:19 INFO: Syncthing exited: exit status 1
[monitor] 18:26:20 WARNING: 4 restarts in 4.152652841s; not retrying further

### Version Information

Syncthing Version:  v0.14.20 "Dysprosium Dragonfly" (go1.8rc2 linux-386) jenkins@build.syncthing.net 2017-01-24 08:26:45 UTC
OS Version: Debian 8.7
Browser Version: N/A

**Comment by calmh** [comment]
Yeah, looks like we broke `-logfile` in .20. Sorry about that.
