### ISSUE TITLE
Can't delete files (they are redownloaded)

### ISSUE THREAD

**Issue by tkossak** [syncthing/syncthing#3934]
Hi,

I sync a folder between 3 devices (2 Linux PCs and 1 android phone). My problem is i can't delete a file, because syncthing redownloads it. When i delete file on 1 of these devices it just reappears later. I would expect that when i delete a file (eg. on my phone) the file is deleted on other devices too.
The folder is in the mode "Send and receive" on both PCs. On android the option "Folder Master" is turned OFF.

My devices:
Linux Manjaro 16.10 "Fringilla"
Linux Mint 18 "Sarah"
Android 4.4.2

Syncthing on Manjaro Linux: v0.14.19, Linux (64 bit) 
Syncthing on Mint Linux: v0.14.21, Linux (64 bit) 
Syncthing on android: v0.14.18
Syncthing-Android:  0.9.5

Maybe it's because i have different versions of Syncthing? I don't know why the app on Manjaro box didn't update itself to v0.14.21.

**Comment by AudriusButkevicius** [comment]
Please use the forum for support.
