### ISSUE TITLE
Leading and trailing spaces stripped from GUI password

### ISSUE THREAD

**Issue by lheckemann** [syncthing/syncthing#3935]
Steps to reproduce:

1. Start GUI
2. Actions > Settings
3. Set username, set a password with leading and/or trailing space
4. Reload
5. Try to use password with and without leading/trailing space; only works without.

### Version Information

Syncthing Version: v0.14.7
OS Version: NixOS 16.09

**Comment by calmh** [comment]
Apparently so

**Comment by lheckemann** [comment]
Thanks for the rapid fix!

**Comment by marclaporte** [comment]
In my experience, trimming leading and trailing spaces in usernames and passwords is better. End user will often copy/paste from other sources, and browsers tend to add a trailing space. Even if you see a password in a password manager, and you retype it, you won't expect the trailing space.

https://ux.stackexchange.com/questions/75686/why-do-some-websites-including-google-trim-whitespaces-in-passwords
https://ux.stackexchange.com/questions/8010/should-i-trim-spaces-in-passwords
http://stackoverflow.com/questions/7240869/should-i-trim-spaces-in-a-password-field
http://tonyshowoff.com/articles/should-you-trim-passwords/

**Comment by calmh** [comment]
I agree with the reasoning and doubt many people intentionally have space on the outside of their passwords. However, we don't have a password entry field - the browser does that, as part of basic auth. I think the browser usually does not strip spaces. It would be odd to have a different behavior when setting the password compared to when checking it.

**Comment by lheckemann** [comment]
FWIW this issue was discovered because of intentional leading/trailing space in a password.
