### ISSUE TITLE
Re-open logfile without restarting

### ISSUE THREAD

**Issue by sbraz** [syncthing/syncthing#3937]
Could it be possible to add some kind of command/signal trap to just re-open the log without restarting the whole service?
What SIGHUP does right now is fine for log rotation but we don't really need to restart the whole process to just rotate logs and I don't see a better way to do that right now.

**Comment by AudriusButkevicius** [comment]
It reopens the log file once a minute I think.
But as I said in my other post, log management is out of scope of syncthing, capture stdout and implement whatever you are after.

**Comment by wweich** [comment]
We do reopen the logfile, so it can be renamed while syncthing is running. See #2420. At most after 1 minute Syncthing will close the renamed file and create a new file with the old name.
