### ISSUE TITLE
Weak hashing is extremely slow on ARMv8 (Android)

### ISSUE THREAD

**Issue by Nutomic** [syncthing/syncthing#3938]
```
[ZYPSC] 03:41:31 INFO: Single thread SHA256 performance is 559 MB/s using minio/sha256-simd (10 MB/s using crypto/sha256).
[ZYPSC] 03:41:33 INFO: Actual hashing performance is 84.14 MB/s
```

Weak hashing slows the actual hashing down almost an order of magnitude. It seems there is no hardware acceleration for it. I'm not sure what the requirements for a weak hash function are, but it could be much faster if it's hardware accelerated.

According to  `/proc/cpuinfo`, these features are supported:
```
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
```

Maybe we can use one of those for the weak hash?

### Version Information

    Syncthing Version: v0.14.21
    Android Version: Android 7.0
    Device: LG G4 (Snapdragon 808)

**Comment by calmh** [comment]
You should definitely run without weak hashing on these devices. I think it's probably roughly as slow as expected, it's just that you've recently gained a great improvement on (hardware-supported) SHA256.

**Comment by Nutomic** [comment]
Wouldn't it make sense to disable weak hashes in Syncthing, based on the architecture? That would also cover Raspberry Pi etc.

**Comment by calmh** [comment]
Honestly I'm toying with the idea of removing it altogether. I know that would make some people sad, but it causes multiple problems and I'm still not sure of it's value. Unfortunately we have no data one way or the other, but it sort of went in on the premise that "at least it won't hurt" which has proven not really to be the case.

**Comment by Nutomic** [comment]
Alright, will wait on your decision then. I've also seen nothing but problems related to the weak hashing.

**Comment by AudriusButkevicius** [comment]
Fine lets disable it by default.

**Comment by Nutomic** [comment]
Will you do this for the next release? I want to release a new Android version soon, with this included.

**Comment by wweich** [comment]
In the meantime you can set the `weakHashThresholdPct` per folder advanced setting to 101, which will also disable it for scanning (since v0.14.20). #3891

**Comment by calmh** [comment]
It will be in the next release, but next release isn't scheduled until the 7th (next Tuesday).

If you want, I can build a custom v0.14.21b or something with just this change in it.

**Comment by Nutomic** [comment]
Okay that should be fine, seeing as no one has complained about it
