### ISSUE TITLE
syncthing-inotify service fails with exit code 1 when there are no folders

### ISSUE THREAD

**Issue by mindstormer12** [syncthing/syncthing#3944]
syncthing-inotify service fails with exit code 1 when there are no folders for the raspian package. I had to do some troubleshooting to realize this. Shouldn't it return exit code 0 even when there are no folders, so that subsequently, adding folders will automatically be `inotify`ed as opposed to needing to restart the service after the folders are added?

In my scenario, I typically configure all my settings and enable both syncthing and syncthing-inotify serivces before I actually add any folders for devices to sync so that they will be synced using proper settings.

**Comment by calmh** [comment]
Hi! This isn't the right repository for your issue. Please file it in https://github.com/syncthing/syncthing-inotify. Thank you.
