### ISSUE TITLE
Files not receiving

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing#3946]
Files in a folder with the "ignoredelete" advanced setting checked are not receiving on my device (Windows 10 Pro x64).
The files trying to be received on my Windows PC are coming from my Android phone's (HTC 10 on Android Nougat) camera share folder (HTC set as the Folder Master).

I am pretty stuck here in what to do guys. Can anyone help?

**Comment by imsodin** [comment]
Please use [the forum](https://forum.syncthing.net/) for support.
