### ISSUE TITLE
Show RemoteDownloadProgress in GUI?

### ISSUE THREAD

**Issue by nwf** [syncthing/syncthing#3947]
Definitely a "feature request" not "bug report", and not at all urgent, but I thought it'd be good to get it written down.

IMHO, It'd be nice to have a better mechanism for reading RemoteDownloadProgress events.  The log output is unsorted (which, I imagine, is just how go associative maps are dumped to strings), which makes attempting to understand how much progress has been made very difficult for my puny human brain. ;)

Could there be a GUI button ("Remote Downloads") per-folder that showed, per device, the most recent RemoteDownloadProgress message with its keys in sorted order?  I imagine the table headings would be {"File name", "File size", "Bytes downloaded", "Percent downloaded"} or something similar.

Thanks for syncthing. :)
--nwf;

**Comment by calmh** [comment]
Possibly. Currently it's reflected in that it bumps the completion percentage of the remote device appropriately.

**Comment by AudriusButkevicius** [comment]
How is this useful? This would just be confusing if anything as some devices might not even emit it.

**Comment by nwf** [comment]
How is the display of local transfers "useful", beyond the ability to bump things to the top of the queue?  It'd just be a display.  There's a lot of content in a RemoteDownloadProgress message beyond what would be needed for just completion percentages, and they're sent way more often than strictly needed for the GUI to display an updated percentage, especially in large folders.  I thought it would be nice to display that information in some way beyond dumping the map to the console, 's all.

**Comment by AudriusButkevicius** [comment]
Local transfer is useful because you know how far of you are.

RemoteDownloadProgress is usually sent exactly once every 10 seconds per device, but that does not signify much, files could be stuck, fail to complete etc. Also, they are completely ignored for master folders, as we don't care what progress others have made towards the downloads because we are not planning to download anything anyway.

So I am still trying to understand how this would be useful, given how unreliable it is.

**Comment by nwf** [comment]
So given that, why not simplify the contents of the RemoteDownloadProgress message to just be an aggregate byte count or something?  Just a copy of the inSyncBytes counter or something.  Why bother transmitting the per-file data at all?  I was assuming there was rationale for the per-file data, and I wanted to watch along, without having to do text processing on the debug message stream, that's all.  If you think it's not useful, there's no need to be barking at me about it, just close the issue.
