### ISSUE TITLE
PPC builds

### ISSUE THREAD

**Issue by K1773R** [syncthing/syncthing#3950]
I've seen you have ppc64 (le and be) builds, can you add ppc (be only) builds aswell?

**Comment by calmh** [comment]
No, unfortunately not. The Go compiler doesn't support anything less than ppc64.

**Comment by K1773R** [comment]
for those desperately needing syncthing on ppc (32bit, be):
get qemu-arm-static, get syncthing arm, have fun with it! it works reasonably well, even tough its a huge overhead.
