### ISSUE TITLE
syncthing run via systemd service crashes and does not restart when the database file cannot be opened

### ISSUE THREAD

**Issue by hiqua** [syncthing/syncthing#3951]
## What happened
syncthing (run through the systemd user service from this repo) crashes with "1/FAILURE" and does not restart when it fails because there is no free space on the disk where the database is stored.

## What did you expect to happen instead
* synchronization should indeed stop since the database cannot be opened
* but the combination of syncthing and its systemd service should not crash and should automatically resume the synchronization once there is some free space and the database can be opened again
* syncthing should especially distinguish between having another instance already running (in which case failing is fine), and just being temporary unable to open the database.

So either the systemd service file could be modified so that the service restarts when there is no free space (as is currently the case with some other exit codes), or the syncthing binary should pause the synchronization indefinitely until there is more space.
IMHO the latter makes more sense, since there are already some cases where syncthing is running but the synchronization is paused because of some issues with the folders.

## What operating system, operating system version and version of Syncthing you are running
* Debian Jessie
* 0.14.18+dfsg1-1 (current version on Debian Testing)

## Console log entries, where possible and relevant
`[LXPSW] FATAL: Cannot open database: write /home/hiq/.config/syncthing/index-v0.14.0.db/028098.ldb: no space left on device - Is another copy of Syncthing already running?
syncthing.service: main process exited, code=exited, status=1/FAILURE`

**Comment by AudriusButkevicius** [comment]
No, it's an error a user has to intervene to fix, hence the user should also make sure that all services are up and running. Us spinning retrying forever can only make things worse, as systemd has to log failures, syncthing has to lig failures etc.

**Comment by AudriusButkevicius** [comment]
Also it's very likely you'd end ip with a corrupt db in that case, making even more sense for the user to have to check things.

**Comment by hiqua** [comment]
Wouldn't sleeping (so logging one entry to say that there is no space left, and then remaining silent) being a decent workaround? I don't use other synchronization software, but dropbox seems to do that according to their documentation:
[https://www.dropbox.com/en/help/164](https://www.dropbox.com/en/help/164)

**Comment by AudriusButkevicius** [comment]
If you wish to produce code for that, sure, but to be honest, I think you should just take better care of your machines and have proper monitoring in place.

A lot of software will fail when there is no space, so I'd expect people will still have to check whats up and whats down after the disk fills up, as not every piece of software is idiot proof and goes into some sort of hibernate mode.

As I said the database might be completely corrupted due to the space shortage, so the hibernation might not help, hence I think crashing hard is the right thing todo.

**Comment by AudriusButkevicius** [comment]
Also the dropbox case I suspect only covers the folders that have the data you sync, not where dropbox keeps its database. I suspect dropbox would also hard crash if it ran out of space for it's database.
