### ISSUE TITLE
lib/events: TestBufferedSub fails spuriously

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3952]
Since the new buffered sub, but not super clear why. Is it a little bit slower?

```
Test with coverage
ok  	github.com/syncthing/syncthing/lib/auto	0.019s	coverage: 100.0% of statements
ok  	github.com/syncthing/syncthing/lib/beacon	0.004s	coverage: 4.9% of statements
ok  	github.com/syncthing/syncthing/lib/config	0.151s	coverage: 70.3% of statements
ok  	github.com/syncthing/syncthing/lib/connections	0.009s	coverage: 3.4% of statements
ok  	github.com/syncthing/syncthing/lib/db	0.486s	coverage: 57.2% of statements
ok  	github.com/syncthing/syncthing/lib/dialer	0.004s	coverage: 10.1% of statements [no tests to run]
ok  	github.com/syncthing/syncthing/lib/discover	5.290s	coverage: 46.1% of statements
--- FAIL: TestBufferedSub (0.08s)
	events_test.go:225: Incorrect ID; 92 != 71
FAIL
coverage: 66.7% of statements
```

**Comment by canton7** [comment]
I saw this while testing the TimeoutCond stuff. Fiddling with that sleep, or how often it's run, *appeared* to fix it.

**Comment by calmh** [comment]
Yeah. I'm just a bit curious about why it happens to begin with, as it didn't before.

**Comment by canton7** [comment]
Maybe making the channel and the timer, which happens inside the mutex, is enough to slow down the pollingLoop, since that also requires that mutex?

**Comment by calmh** [comment]
Maybe that fixed it. To close if it doesn't reoccur in a while.

Otherwise the next step could be for the Log() function to not immediately drop the event if the subscription isn't waiting for it - we could easily allow a (say) 15 ms timeout on the send given that it will almost never delay for that long anyway.

**Comment by calmh** [comment]
Didn't fix it; https://build.syncthing.net/job/syncthing-pr/3374/

```
ok  	github.com/syncthing/syncthing/lib/discover	5.251s	coverage: 46.1% of statements
--- FAIL: TestBufferedSub (0.36s)
	events_test.go:225: Incorrect ID; 512 != 487
FAIL
```
