### ISSUE TITLE
Enable mips build

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#3959]
This is now supported in Go 1.8

Previous requests for this: #1432 #394

**Comment by calmh** [comment]
(After 1.8 release)

**Comment by hbxntsxw** [comment]
Could you please build the mips and mipsle versions? Many thanks.

**Comment by calmh** [comment]
Yes, we can do this now that we have mips support in Go 1.8. Look for mips in the next release, unless something unforeseen happens.

**Comment by calmh** [comment]
@hbxntsxw @comtom @neoecos @davidak @solderzzc @swetoast

If you guys are still interested in the mips build, I'd appreciate if you gave the one here a spin to see if it runs/crashes/works/whatever:

https://build.syncthing.net/job/syncthing/lastSuccessfulBuild/artifact/

**Comment by swetoast** [comment]
ofc, appreciate the build

**Comment by hbxntsxw** [comment]
Thanks, but I think their is some thing wrong. The CPU of my router is mipsel, could you please build a mpisel one. 

[RT-N56U_B1 /opt/home/admin]# syncthing
/opt/bin/syncthing: line 1: syntax error: unexpected "("

**Comment by calmh** [comment]
So the arch options seem to be `mips`, `mipsle`, `mips64`, `mips64le`. Is `mipsel` == `mipsle` maybe?

**Comment by calmh** [comment]
Here's a mipsle build coming up, lets see if that runs: https://build.syncthing.net/job/syncthing-branch/429/

**Comment by solderzzc** [comment]
@calmh Thanks a lot for the release, I can hardly to find my board on mips, will try when get it.

**Comment by hbxntsxw** [comment]
I can run it on my router. But can not open the webpage(http://192.168.2.1:8384). The port 8384 is accepted.

[RT-N56U_B1 /opt/home/admin]# syncthing
[monitor] 12:27:29 INFO: Starting syncthing
[E4GKQ] 12:27:30 INFO: syncthing v0.14.24-rc.1+9-g328e679 "Dysprosium Dragonfly" (go1.8 linux-mipsle) jenkins@build.syncthing.net 2017-03-04 08:40:47 UTC
[E4GKQ] 12:27:30 INFO: My ID: E4GKQXN-3MCCT6P-PWBGTEP-WJJSD4R-RYG7MLO-3DRKXY3-P7KHJ25-HCNFBQ6
[E4GKQ] 12:27:32 INFO: Single thread SHA256 performance is 5.9 MB/s using minio/sha256-simd (5.8 MB/s using crypto/sha256).
[E4GKQ] 12:27:35 INFO: Hashing performance with weak hash is 5.39 MB/s
[E4GKQ] 12:27:39 INFO: Hashing performance without weak hash is 5.80 MB/s
[E4GKQ] 12:27:39 INFO: Weak hash enabled, as it has an acceptable performance impact.
[E4GKQ] 12:27:39 INFO: Starting deadlock detector with 20m0s timeout
[E4GKQ] 12:27:39 INFO: Ready to synchronize "Default Folder" (default) (readwrite)
[E4GKQ] 12:27:39 INFO: Send rate is unlimited, receive rate is unlimited
[E4GKQ] 12:27:39 INFO: Rate limits do not apply to LAN connections
[E4GKQ] 12:27:39 INFO: Using discovery server https://discovery-v4-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[E4GKQ] 12:27:39 INFO: TCP listener ([::]:22000) starting
[E4GKQ] 12:27:39 INFO: Using discovery server https://discovery-v4-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[E4GKQ] 12:27:39 INFO: Using discovery server https://discovery-v4-4.syncthing.net/v2/?id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
[E4GKQ] 12:27:39 INFO: Completed initial scan (rw) of "Default Folder" (default)
[E4GKQ] 12:27:39 INFO: Using discovery server https://discovery-v6-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[E4GKQ] 12:27:39 INFO: Using discovery server https://discovery-v6-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[E4GKQ] 12:27:39 INFO: Using discovery server https://discovery-v6-4.syncthing.net/v2/?id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
[E4GKQ] 12:27:39 INFO: GUI and API listening on 127.0.0.1:8384
[E4GKQ] 12:27:39 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[E4GKQ] 12:27:39 INFO: Device E4GKQXN-3MCCT6P-PWBGTEP-WJJSD4R-RYG7MLO-3DRKXY3-P7KHJ25-HCNFBQ6 is "RT-N56U_B1" at [dynamic]
[E4GKQ] 12:27:39 INFO: Anonymous usage reporting is always enabled for candidate releases.
[E4GKQ] 12:27:39 INFO: Automatic upgrade is always enabled for candidate releases.
[E4GKQ] 12:27:39 INFO: Starting usage reporting
[E4GKQ] 12:27:40 INFO: c.S.listenerSupervisor: Failed service 'dynamic+https://relays.syncthing.net/endpoint' (1.000000 failures of 2.000000), restarting: true, error: "{dynamic+https://relays.syncthing.net/endpoint dynamic+https://relays.syncthing.net/endpoint} returned unexpectedly", stacktrace: [unknown stack trace]
[E4GKQ] 12:27:40 INFO: c.S.listenerSupervisor: Failed service 'dynamic+https://relays.syncthing.net/endpoint' (1.989982 failures of 2.000000), restarting: true, error: "{dynamic+https://relays.syncthing.net/endpoint dynamic+https://relays.syncthing.net/endpoint} returned unexpectedly", stacktrace: [unknown stack trace]
[E4GKQ] 12:27:41 INFO: Entering the backoff state.
[E4GKQ] 12:27:41 INFO: c.S.listenerSupervisor: Failed service 'dynamic+https://relays.syncthing.net/endpoint' (2.970738 failures of 2.000000), restarting: false, error: "{dynamic+https://relays.syncthing.net/endpoint dynamic+https://relays.syncthing.net/endpoint} returned unexpectedly", stacktrace: [unknown stack trace]
[E4GKQ] 12:27:41 INFO: Automatic upgrade: couldn't find a release to download
[E4GKQ] 12:27:50 INFO: New NAT port mapping: external TCP address 0.0.0.0:4214 to local address 0.0.0.0:22000.
[E4GKQ] 12:27:50 INFO: Detected 1 NAT device

**Comment by canton7** [comment]
> GUI and API listening on 127.0.0.1:8384

Looks like it's only listening for connections from the router itself, not from other machines.

Edit the `config.xml`, change the GUI listen address to 0.0.0.0 from 127.0.0.1.

**Comment by hbxntsxw** [comment]
I can't find out the config.xml file. But it works by using this command "syncthing -gui-address 0.0.0.0:8384". Thank you very much. @calmh @canton7

**Comment by calmh** [comment]
Okay. So do we want both mips and mipsle builds, or is mipsle "the thing" for pretty much everyone?

I'll need to fix up the sha256 package with a pull request, but then we should be having mipsle builds in the future.

**Comment by hbxntsxw** [comment]
I think both mips and mipsle builds is better. @calmh

**Comment by canton7** [comment]
> I can't find out the config.xml file.

`synthing -paths` tells you where it is, IIRC.

**Comment by K1773R** [comment]
include mips builds aswell and not just mipsle

**Comment by calmh** [comment]
Done. mips & mipsle will be in v0.14.25.

**Comment by rdslw** [comment]
I still have error
> ./syncthing: line 1: syntax error: unexpected "("

I used mips version. mipsle (tested just to be sure) returns 'illegal instruction'.

My machine is gnubee (http://gnubee.org), 
`root@GnuBee:~# head /proc/cpuinfo
system type             : MediaTek MT7621 ver:1 eco:3
machine                 : GB-PC1
processor               : 0
cpu model               : MIPS 1004Kc V2.15`

**Comment by AudriusButkevicius** [comment]
You are not running syncthing but some script that doesn't work with your shell.

**Comment by calmh** [comment]
Or it is the binary but not recognized as such? If so, no help available from me unfortunately.

**Comment by rdslw** [comment]
It's syncthing binary, I just downloaded it and tried.
+x is set on the binary.

root@GnuBee:/flower/syncthing-linux-mips-v0.14.40# ls -la
drwxrwxr-x    5 1004     1004          4096 Nov 17 01:00 .
drwxr-xr-x    4 root     root          4096 Nov 17 01:00 ..
drwxrwxr-x    2 1004     1004          4096 Nov 17 01:00 .metadata
-rw-r--r--    1 1004     1004          6564 Nov  7 17:42 AUTHORS.txt
-rw-r--r--    1 1004     1004         16726 Nov  7 16:02 LICENSE.txt
-rw-r--r--    1 1004     1004          4924 Nov  7 16:02 README.txt
drwxrwxr-x    9 1004     1004          4096 Nov 17 01:00 etc
drwxrwxr-x    2 1004     1004          4096 Nov 17 01:00 extra
-rwxr-xr-x    1 1004     1004      14165550 Nov  7 17:43 syncthing
-rw-rw-r--    1 1004     1004           241 Nov  7 18:41 syncthing.sig
root@GnuBee:/flower/syncthing-linux-mips-v0.14.40# ./syncthing
./syncthing: line 1: syntax error: unexpected "("

**Comment by calmh** [comment]
I think the binary that gives you `illegal instruction` is the right architecture but for a newer CPU than you have. The one you are looking at now is for the wrong byte order so it's not even recognized as a binary.

**Comment by rdslw** [comment]
Hmmm, that might be it. This board is quite new, released this summer, but I'm not so sure about cpu used.

> system type: MediaTek MT7621 ver:1 eco:3
> cpu model: MIPS 1004Kc V2.15

Maybe go build is not supporting it. Any suggestions where I might look for solution?

**Comment by Ferroin** [comment]
Unless I'm reading the datasheet wrong, the 1004Kc core has no FPU.  I'm not certain if that's the problem, but it would not surprise me if it was.

**Comment by rdslw** [comment]
After short research, I think that missing FPU and and fact that currently golang does not support mips soft-float (https://github.com/golang/go/issues/18162) is a reason for this.

Just to be sure: which go version is used to build binaries?

**Comment by calmh** [comment]
Latest, Go 1.9.2

**Comment by rdslw** [comment]
That should be it, as golang 1.9 does not mention mips changes, while golang 1.8 mentioned:

> Go now supports 32-bit MIPS on Linux for both big-endian (linux/mips) and little-endian machines (linux/mipsle) that implement the MIPS32r1 instruction set with FPU or kernel FPU emulation. Note that many common MIPS-based routers lack an FPU and have firmware that doesn't enable kernel FPU emulation; Go won't run on such machines.

Looks like I need to wait for go 1.10

**Comment by calmh** [comment]
Or, as I read it, compile a kernel with FPU emulation.

**Comment by mrjk** [comment]
I would be very interested in running Syncthing on my gnu bee device ... If I understand well, we need to wait a future release of Go?

**Comment by rdslw** [comment]
@mrjk or use a kernel with FPU emulation. More about kernel option is here: https://github.com/gnubee-git/GnuBee_Docs/issues/47
