### ISSUE TITLE
File name ... contains invalid characters; marked as invalid.

### ISSUE THREAD

**Issue by davidak** [syncthing/syncthing#396]
````
10:02:47: File name "BSC-Share/Einmal neuer Server, bitte. Mit viel Salz… | 21x9.org.webloc" contains invalid characters; marked as invalid.
10:02:47: File name "BSC-Share/Bett/Polsterbett Catana dunkelbraun | massivum.de.webloc" contains invalid characters; marked as invalid.
10:02:47: File name "Bett/Betten, Polsterbett \"Seaside Richmond\" - Clever & Günstig kaufen.webloc" contains invalid characters; marked as invalid.
10:02:47: File name "BSC-Share/naeramarth7:clean-greader · GitHub.webloc" contains invalid characters; marked as invalid.
10:02:47: File name "BSC-Share/Onkyo | A-5VL.webloc" contains invalid characters; marked as invalid.
```

Filenames:

`Einmal neuer Server, bitte. Mit viel Salz… | 21x9.org.webloc`
`Polsterbett Catana dunkelbraun | massivum.de.webloc`
`Betten, Polsterbett "Seaside Richmond" - Clever & Günstig kaufen.webloc`
`naeramarth7/clean-greader · GitHub.webloc`
`Onkyo | A-5VL.webloc`

They are also deleted on other nodes but still on that node.

**Comment by sirlancelot** [comment]
I'm still getting this error, is there a new ticket tracking this bug or should this one be re-opened?

**Comment by AudriusButkevicius** [comment]
I think we forgot to reopen this.

**Comment by calmh** [comment]
What's the bug? My points from above are handled I think, and the presence of invalid file names is something we just have to log and live with.

**Comment by AudriusButkevicius** [comment]
Are they? From your message above it sounds that they aren't?

**Comment by calmh** [comment]
That's two years ago... But ah you may be right that we complain about deleted files maybe?

**Comment by sirlancelot** [comment]
I feel like files should still be copied, albeit with invalid characters encoded in a manner that the target filesystem supports. Since Windows and NTFS is likely the target to complain the most, maybe the filenames could have their invalid characters URL encoded; like `%2A` for `*`, `%3A` for `:` and others?

**Comment by calmh** [comment]
That's #1734 and unrelated to what's going on here.

**Comment by Ferroin** [comment]
Also, % is an illegal character in Windows filenames too, so URL encoding wouldn't work.

**Comment by Ferroin** [comment]
Correction, it's a shell metacharacter in both cmd.exe and PowerShell, so we could only use it once in a file name and have things accessible from the console reliably.

**Comment by calmh** [comment]
I've deleted comments that relate to the issue I linked above. I linked it for a reason.

**Comment by calmh** [comment]
This is now a proper sync error instead.
