### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by Vinz87** [syncthing/syncthing#3963]
I have elements not synchronized because of permissions issues ("Operation not permitted"). What about giving in some way root privileges to Syncthing?

### Version Information

Syncthing Version: v0.14.21
OS Version: OS X El Capitan
Browser Version: Safari

**Comment by AudriusButkevicius** [comment]
Run it as root if you want it to have root privileges, yet we do not recommend running services as root.
I am closing this as I do not think this is an actionable issue, as it's not syncthings job to work around ownership issues. If you want a discussion on how this could be better handled, please start a thread on the forum.

**Comment by Vinz87** [comment]
Ok, thank you
