### ISSUE TITLE
GUI: Add "Pause All Folders" and "Resume All Folders" buttons

### ISSUE THREAD

**Issue by scienmind** [syncthing/syncthing#3964]
Implement "Pause All Folders" and "Resume All Folders" buttons

Use cases:
https://github.com/syncthing/syncthing/pull/3520#issuecomment-263859409
https://forum.syncthing.net/t/pause-all-folders/9170

**Comment by imsodin** [comment]
Fixed in #3973 with https://github.com/syncthing/syncthing/commit/0c68e1e510e2e92beed870b3ea30fb047d6dabcf. Also relevant: #3982
