### ISSUE TITLE
lib/model: Duplicate scans can happen when folder is restarted

### ISSUE THREAD

**Issue by klockd** [syncthing/syncthing#3965]
If the folder takes too long to complete the fist scanning, a second process seems to kick in a while after.

**Comment by calmh** [comment]
There is an issue where a config change while the folder is scanning restarts the folder and kicks off another scan. I think this is a dup but on mobile so not searching.

**Comment by calmh** [comment]
So two separate user actions resulting in the same issue: pausing/unpausing, and reconfiguring to cause an internal restart.
