### ISSUE TITLE
New share mixed with another share already in place.

### ISSUE THREAD

**Issue by klockd** [syncthing/syncthing#3966]
This happens twice with me already.
I had a new share setup, and after setting it up normally, it some how joined to another folder already shared.

I made sure I didn't pick the same folder, as both contents end up mixed up on both folders.

This was like a security breach for us as the folder it mixed up was confidential.

**Comment by calmh** [comment]
I've never heard about such a thing happening. If you can reproduce this, pleas post the procedure. Otherwise the most likely explanation is a misconfiguration.

**Comment by klockd** [comment]
So far it happened twice, but with no apparent reason.
I will keep you posted.

The scenario was like this:
- User shared a folder to the server.
- Server added share and re-shared with backup servers. Synced was complete before proceeding.
- When adding to the 1st backup server the problem happened. 

It linked in a way as the two shares were actually acting as one. I had to remove the one of the shares in order to fix it. Both shares end up with the same mixed content. Deletes and new updates were sent to both shares too. 
Its like they both had the same ID of something.

**Comment by AudriusButkevicius** [comment]
I say we close this, until the user has a step by step reproduction case.

**Comment by wweich** [comment]
One Syncthing instance probably pointed the two Syncthing folders to the same directory on disk. Syncthing warns the user not to do this but doesn't prevent it.

**Comment by calmh** [comment]
Yep. Please yell for reopen if you get a reproduction of this.
