### ISSUE TITLE
Folders synced from Windows to Linux has no user write permission

### ISSUE THREAD

**Issue by danny0838** [syncthing/syncthing#3968]
Sync from **v0.14.21, Windows (64 bit) on Windows 7 SP1** to **syncthing v0.14.21 on Ubuntu 16.04.1 LTS**. Folders synced from Windows to Linux has permission `dr-xr-xr-x`, while the desired is `drwxr-xr-x`.

**Comment by AudriusButkevicius** [comment]
Set ignore permissions on the linux side, and use a umask.

**Comment by calmh** [comment]
The files are read only on the Windows side I guess?

**Comment by danny0838** [comment]
How to use a umask?

**Comment by AudriusButkevicius** [comment]
https://www.digitalocean.com/community/tutorials/linux-permissions-basics-and-how-to-use-umask-on-a-vps
