### ISSUE TITLE
Inconsistency in GUI strings ?

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#3969]
v14.21
For Staggered versioning we read : 

> The following intervals are used: for the first hour a version is kept every 30 seconds

What about these 30s when not using inotify and default scan interval is 60s ?
Also, the minimum _Maximum age_ is 1 day. So should we remove the quote above ? Or for the first hour in the first day starting when ST sees the first change ever for a file, we really could yet have 52 versions if the file changed 52+ times in the first hour and we set say 400 days Maximum age ?
This is a question to help in rephrasing for translation.
Thank you
[EDIT] : an eye to the documentation reveals the web site says "...**the most recent version is kept** every..." when the embedded strings all say "...**a version is kept** every...". Here lies the ambiguity : only **the most**, every previous being deleted until the /hour/day/month threshold are reached, or "**a version**" meaning "a new one and previous are kept until..." ?

**Comment by calmh** [comment]
We can get an incoming file update from somewhere else every five seconds regardless of our scan interval.

Maximum age is oldest it will keep any version, so not related to the 30s thing.

**Comment by bugith** [comment]
> We can get an incoming file update from somewhere else every five seconds

Oh, yes, my mistake, these are remote changes notifs through network isn't it, nothing to do with local FS? Sorry. But how can local instance be aware of a local FS change before next 60s scan interval end (without inotify) to notify remote peers every 30s if not even 5s? 

> Maximum age is oldest it will keep any version, so not related to the 30s thing.

Okay, well, but say
Max age=365 => Max versions =~52, right ? Then we do the very first change so original is kept as 1st version (said within 30s). Still right ? Then before an hour was elapsed, we do another change. What happens ? We keep the shared file again ? Yes, I did a test, changing a file every ~20s with Max age set to 365. I ended with 60 to 61 versions staggered roughly 50s-70s from each other. Going on for some minutes, I saw the number doesn't grow any more, previous versions being deleted as a new one comes in. A strange thing (maybe intended although?) is that the very first kept version is still there, deletions beginning from the 2nd oldest. As I go on, the hole between the oldest and next one grows.
I guess this is to keep a version from each of the week in the year... let's see which one are kept in some hours...
Bye Jakob

**Comment by calmh** [comment]
Remote peers may run inotify, or have a lower rescan interval than 60s, or be something other than syncthing that just happens to speak the same protocol.

On the second point, I think you know the behavior of this thing better than I do. :)

**Comment by bugith** [comment]
You're kidding man :) I just looked how it works because I found my first raw translation was a pain in the ass both to read and understand.
You run an incredible project man. Go on, and thanks for all that job.

**Comment by calmh** [comment]
Thanks, but no, I didn't write it and I never fully understood the clean out scheme it uses. :)
