### ISSUE TITLE
Syncthing "Server 1" web gui disconnected during first time synchronization, yet still running. help!

### ISSUE THREAD

**Issue by 2SI3NX** [syncthing/syncthing#3975]
- what happened,
Server 1 - Send only mode - was busy syncing for the first time terrabytes of data to Server 2.
Connected locally.
Server 1 web gui lost connection at some point, i refreshed the page and and does not resolve anymore. It says "Unable to connect"
Server 2 web gui is still working and did not disconnect. Global State and Local State is still counting.
I tried restarting syncthing on Server 1 but web gui still doesnt work.
I tried killing the process with sudo kill -9 pid on Server 1. It gets killed and immediately after gets a new pid. Process unable to be killed and restarted.
Servers have not been restarted yet.
I have not attempted to kill syncthing on Server 2 as yet.

Please help!! is this normal? is this still **really** syncing in the background??
Why is there no more gui on server 1? Why did the gui stop working or get disconnected, yet Server 2 is still counting local and global states?

### Version Information

Syncthing Version: v0.14.23
OS Version: Ubuntu 16.04
Browser Version: Firefox 51.0.1

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.

**Comment by 2SI3NX** [comment]
Isnt it possible that this could be a bug? Why else would the web gui on Server 1 stop working ?

**Comment by calmh** [comment]
Possibly, but lets sort it out in the support channel until shown to be a bug. Then we'll happily log the report and fix it.
