### ISSUE TITLE
Use https instead of http where possible

### ISSUE THREAD

**Issue by ghane** [syncthing/syncthing#3976]
For cases like:

  `cmd/syncthing/monitor.go:// You can obtain one at http://mozilla.org/MPL/2.0/.`

the URL redirects to https. By using the https link explicitly, we not only save a redirect, we (in some hand-waving way) are more secure.

Similar changes for other things we retrieve, where possible (eg Bootstrap)

**Comment by calmh** [comment]
That covers 99% of it. The few remaining links for things that don't redirect to https I'm leaving.
