### ISSUE TITLE
Sync to Network Drive does not work

### ISSUE THREAD

**Issue by etraff** [syncthing/syncthing#3980]
When Syncing to a folder which is on the Netwerk (so, not C:\local\bla - but a remote Server mapped to X:\server\bla) syncthing starts to work, but then only creates the folders, but does not create files (file count = 0) - left it running overnight, nothing happened.

Syncthing Version: v0.14.23, Windows (64 bit)
OS Version: Windows 10 1607

**Comment by canton7** [comment]
Please use [the forum](https://forum.syncthing.net) for support, as explained in the issue template.
