### ISSUE TITLE
Global changes should load when button clicked

### ISSUE THREAD

**Issue by canton7** [syncthing/syncthing#3984]
Currently the list of global changes is loaded when Syncthing finishes starting, or when an index change happens. This means that refreshing the Gui will clear the list, and it will remain cleared until another index change happens. 

(I'm writing this from memory on mobile: it's possible I'm wrong here.)

Instead, we should probably load the list when the user clicks the global changes button (using `?timeout=0`).

We may want to keep reloading it when index changes are detected and the list of global changes is open, so that it loads new entries in real time (or that may just be annoying behaviour). If we do, that should use a timeout of zero as well. 

I'm happy to do this: this issue is a reminder.

**Comment by nrm21** [comment]
On windows hitting refresh doesn't cause me to lose entries.

Or did you mean ST restart?  Restarting DOES clear out the entries.  This is known behavior as the list was never developed to be persistent... yet.

**Comment by canton7** [comment]
Ok i might be misremembering then. I'll check when I get back to a computer later this week

**Comment by grinapo** [comment]
At least in 0.14.23 it does _not_ lose the history by reloding only the GUI. 
But I guess to have an up to date and full audit trail is not an unusual requirenment.

**Comment by canton7** [comment]
Right I must have misremembered. No issue.
