### ISSUE TITLE
Sync permission changes?

### ISSUE THREAD

**Issue by mindstormer12** [syncthing/syncthing#3990]
I did a quick test on permissions with `chmod` and it turns out permissions are only synced when the file is changed. So if you `chmod` a file, the permissions are not synced--it is only synced when you update the file (e.g. if it was a text file, it updates when you edit the text file). I'm sure the fact that files are only synced when it is changed is obvious, but how about syncing even just changes in permissions?

At the moment, what is happening is if I just change the permissions on a machine A, then since the permissions alone do not cause a sync, the permissions are not changed on a machine B. If machine B then edits this file, then machine A will have its permissions reverted because the updated file of machine B is synced with its permissions. The ability to sync just changes in permissions eliminates this strange behavior and opens up many additional uses of syncing permission-oriented files, like sensitive files in /etc (which was what I was trying to accomplish with Syncthing), files in ~/.ssh, etc.

If I want the permissions to propogate, then currently, the file must be `chmod`ed then edited on the machine changing the permissions so that a sync is triggered.

**Comment by AudriusButkevicius** [comment]
It does sync permission changes (or it should).
Did you actually rescan?

If you use inotify, I suspect we simply do not get notified about permission changes.

**Comment by rieje** [comment]
Yup, I'm using inotify on all machines. Latest versions, one is Arch and the other is Raspbian.

**Comment by calmh** [comment]
Yeah this looks like an inotify bug. You can confirm by doing a permission only change somewhere and hitting "rescan" for that folder in the syncthing GUI.

**Comment by imsodin** [comment]
Yes, syncthing-inotify does not pick up permission chances in general. The used backend does not guarantee that attribute changes are picked up on all platforms and syncthing-inotify only subscribes to the guaranteed event types.
