### ISSUE TITLE
Upgrade notification after automatic upgrade

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#3994]
If user has activated automatic upgrades it would be great if there are a simple notifications like
"2017-02-20 01:15 : Syncthing has been automatically upgraded to v0.14.23 ([Changelog](https://github.com/syncthing/syncthing/releases/tag/v0.14.23))" 
"2017-02-19 00:11 : Syncthing has been automatically upgraded to v0.14.22 ([Changelog](https://github.com/syncthing/syncthing/releases/tag/v0.14.22))" 
that stay until the user confirms with "OK". This would be helpful to all users who run Syncthing without opening the GUI every day.

**Comment by calmh** [comment]
Honestly I'm not sure we want to attract too much attention to the auto upgrades. See for example how the browsers handle it.

**Comment by AudriusButkevicius** [comment]
Yeah, it would be more anoying than useful.

**Comment by uok** [comment]
Ok, I was suggesting this to keep users who run Syncthing on a server interested in new features that might be available after automatic update(s).
