### ISSUE TITLE
Virtual machine clone contains duplicate device ID and there is no well-documented fix

### ISSUE THREAD

**Issue by fortran77** [syncthing/syncthing#3997]
After installing Syncthing (v0.14.23, Linux (64 bit)) in a VM (virtual machine) (Ubuntu 16.04 within VMware Fusion running on OS X), and getting it working, I shut down the VM, cloned it by replicating its directory tree, and booted both the original VM and its clone. VMware Fusion detects a cloned VM and gives it a new MAC address and hence it gets a new IP address, so both VMs can function in parallel with no conflict.

Both instances of Syncthing had the same device ID. As a result, sync seemed to be failing on one of the VMs.

Looking to correct this, I searched and found no current open or closed issues about this. So maybe it's not very often that people using Syncthing clone VMs. Which is surprising, because cloud servers often get cloned by creating a snapshot and using that snapshot to create a new server instance.

On the documentation website [https://docs.syncthing.net/index.html](https://docs.syncthing.net/index.html) I entered “device id” (also “device ids”) and got no search results. Fortunately a Google search worked and led me to the pages at [https://docs.syncthing.net/dev/device-ids.html#description](https://docs.syncthing.net/dev/device-ids.html#description). 

But the documentation pages mentioned above do not address the question of how a device ID should be regenerated.

So I searched further and found in various places that the command `syncthing -generate=""` is supposed to generate a device ID. However, i found that this only works if no device ID has yet been generated. After a lot of guessing, I cd'd into ~/.config/syncthing, did `rm key.pem cert.pem`, then did `syncthing ‑generate=""`. This caused the device ID to be re-initialized, and syncthing started up again.

Here are the issues I'm reporting.

1. (Bug.) Search on the documentation website [https://docs.syncthing.net/index.html](url) is apparently not working correctly, as it fails to find a page that exists and contains matching text.
2. (Bug.) There is no clearly documented way to regenerate the device ID. I ended up guessing, and I am still not sure if what I did was correct.
3. (Feature request.) Duplicate device IDs should be detected and reported somewhere where the user will see them. Nothing in the web UI reported the duplicate. Only after I manually executed syncthing did i see error messages, and they mentioned failed connections but did not mention a duplicate device ID. The error messages were similar to: “Incorrect response code 2: already connected”, “read: connection reset by peer”, and “write: broken pipe”.

**Comment by AudriusButkevicius** [comment]
So I am closing this as if any issues should be open they should be open in the docs repo.
The feature request is noble, but not implementable in a reasonable way, as we can't destinguish between same device migrating between networks and two devices with same id in the same network.

**Comment by fortran77** [comment]
Any time we see interspersed incoming connections having the same device ID but differing IP addresses, we can be reasonably certain that these are cloned hosts. I'm guessing that Dropbox uses this algorithm, as it handles cloned hosts seamlessly.

This issue was closed so rapidly and with so much finality that I hesitate to tread on anybody's toes by saying too much more.

**Comment by AudriusButkevicius** [comment]
Sadly we can't, as devices have more than a single network card these days, or more than a single gateway... 3G modem + wifi modem etc...

**Comment by calmh** [comment]
We could have a documentation page that clearly describes where the device ID comes from and why it should not be duplicated (if that isn't already there, maybe some cleanup is required). The "connected to myself" error could be amended with an "... or a device was incorrectly cloned" part and a link to this page.
