### ISSUE TITLE
Transfer interruption breaks "oldest first" pull order

### ISSUE THREAD

**Issue by mikemol** [syncthing/syncthing#3999]
If your issue is a bug report, replace this boilerplate with a description
of the problem, being sure to include at least:

When faced with a number of large files that need to be transferred in order, an interruption to the connectivity between the two nodes will result in the files being transferred out of order. (In this case, the pulling node is configured to pull oldest first)

It is expected that the files will be transferred in the order specified.

On my sending side, I have a script that takes a large input file, splits it into 1GiB chunks, generates a manifest file, then moves these files into the folder Syncthing shares. On the receiving side, I have a script which watches for the manifest file to appear (it will be the final file transferred, since the chunk files are older), verify the manifest, and then move the chunks and manifest out of the folder Syncthing is sharing.

This works great, except that if the two nodes disconnect from each other during a transfer, then the manifest file will appear before some other files, causing my verification step to fail.

(I'm not certain, honestly, if it results in out-of-order transfer, or if the chunk is completely lost from the puller's perspective; the missing chunk(s) don't appear in the "out of sync" list on the pull side.)

### Version Information

Syncthing Version: v0.14.23
OS Version: CentOS 7

**Comment by AudriusButkevicius** [comment]
So this won't work for a number of reasons, because we start pulling as soon as we know we are missing something, and the rest of the items that we need might arrive in separate batch of notifications, breaking renames, pull order and other things. It's not trivial to fix, but I think it's a dup of an existing issue.

**Comment by mikemol** [comment]
Well, that's frustrating. Can there be at least a tentative, kick-it-in-the-pants mechanism wherein I could tell it to look at the global and local states, so that it would turn around and honor the pull order? Or, heck, if there were a way for me to manually tell it what file I want it to begin pulling immediately, that would be a fine workaround.

**Comment by AudriusButkevicius** [comment]
You can disable scans, and then spoon feed what to scan via the API

**Comment by AudriusButkevicius** [comment]
You need to scan on the sending side

**Comment by calmh** [comment]
Sounds like you just need to wait for the manifest file, then wait for whatever the manifest file describes?
