### ISSUE TITLE
Add "select all" tick box when adding new folder

### ISSUE THREAD

**Issue by aaronkjones** [syncthing/syncthing#4000]
Certainly low priority.

When sharing a folder you have the option to,
"Share With Devices
Select the devices to share this folder with."

There should be a "select all" tick box that selects all devices, in the event you wish to share the folder with all of them. Currently, if you have several devices, you have to tick each one.

**Comment by aaronkjones** [comment]
The file this section appears in is, editFolderModalView.html

I will attempt to add it myself.

**Comment by slytomcat** [comment]
Very good idea! Fully agree with **aaronkjones**.

I had want to report the same enhancement, but luckily found this issue.

**Comment by calmh** [comment]
Closed by #5307
