### ISSUE TITLE
API does not accept E notation in JSON

### ISSUE THREAD

**Issue by Martchus** [syncthing/syncthing#4001]
The Syncthing REST-API does not accept JSON containing E notation.

Steps to reproduce:

1. POST some JSON, eg. system/config:
    ```
    ...
            "pullers": 0,
            "rescanIntervalS": 1e+06,
            "scanProgressIntervalS": 0,
    ...
    ```
2. Receive error message:
    ```
    json: cannot unmarshal number 1e+06 into Go value of type int
    ```
    (HTTP status 400)

Expected: `1e+06` is interpreted as 1000000.

Note that the possibility to use the E notation is part of the JSON-RFC: https://tools.ietf.org/html/rfc4627

I tried with Syncthing version "v0.14.23, Linux (64 bit)".

I am aware that this is likely a bug in the underlying JSON library. Since I don't know which library you use I'll file the issue here, though.

Thanks for your help. I would try fixing it myself, but I don't know Go and this might involve decisions like changing the JSON library.

**Comment by AudriusButkevicius** [comment]
We use standard Go library. Please open the issue there.

**Comment by Martchus** [comment]
I actually wouldn't close it yet since from the user perspective Syncthing isn't operating correctly. Also it is not 100% sure whether the bug is actually in the library.

At least, the Go library seem to have test cases for this: https://github.com/golang/go/blob/master/src/encoding/json/number_test.go

I might file an issue there tomorrow. Before I want to add the problematic value to test cases and see what happens. Maybe it can even be fixed easily.

**Comment by AudriusButkevicius** [comment]
We're not going to keep a bug open that is out of our control. It needs to be fixed upstream.

**Comment by calmh** [comment]
For what it's worth, ES6 encodes all integers up to 2^64 as decimal numbers and not as exponentials. We're compatible with that, at least. The JSON spec is quite underspecified unfortunately.

**Comment by Martchus** [comment]
Just for the record, the problem is actually in the Go JSON library: https://go-review.googlesource.com/#/c/37438

But this is not going to be fixed: https://github.com/golang/go/issues/19288

I'll find a workaround on my side. Maybe this limitation of the JSON parser should be mentioned in the documentation of the REST-API.

**Comment by calmh** [comment]
Another workaround would be to not set the rescan interval to a million seconds. At that point you might as well disable scans by setting it to zero. Or set it to some values where rescans are likely to happen in reasonable time.
