### ISSUE TITLE
Does syncthing prefer weak hashes even when they're slower?

### ISSUE THREAD

**Issue by rbjorklin** [syncthing/syncthing#4010]
It is not completely clear to me from the log messages below if syncthing prefers weak hashes even if they are slower? Is the log message just slightly misleading? Does `Hashing performance without weak hash is 331.90 MB/s` refer to an even weaker hash than the one mentioned on the above line?

    [W6RVO] 07:48:06 INFO: Single thread SHA256 performance is 332 MB/s using minio/sha256-simd (204 MB/s using crypto/sha256).
    [W6RVO] 07:48:06 INFO: Hashing performance with weak hash is 284.59 MB/s
    [W6RVO] 07:48:07 INFO: Hashing performance without weak hash is 331.90 MB/s
    [W6RVO] 07:48:07 INFO: Weak hash enabled, as it has an acceptable performance impact.

### Version Information

Syncthing Version: v0.14.23
OS Version: Centos 7.3

**Comment by AudriusButkevicius** [comment]
If the performance hit is less than 20% it will support weak hashing.

**Comment by rbjorklin** [comment]
It seems I haven't expressed myself well enough. What I would like to have clarified is this:

Based on this message `Hashing performance with weak hash is 284.59 MB/s` it is not clear to me if the following message `Hashing performance without weak hash is 331.90 MB/s` means a stronger or weaker hash compared to the first. I'm reading it as if "without weak hash" means a stronger hash but this might be an incorrect interpretation on my part?

**Comment by AudriusButkevicius** [comment]
I still don't understand your question. We have a single hash (strong) and dual hash (strong + weak). If strong + weak is less than 20% performance penalty versus strong only, we use that which allows us better file reuse of blocks.

Regardless, this is not a bug, but a question, and if you follow the issue template, things like this go into the forum.
