### ISSUE TITLE
Syncing same folder to multiple paths on one machine

### ISSUE THREAD

**Issue by dbkaplun** [syncthing/syncthing#4012]
I propose that syncthing should support the functionality of syncing the same folder to multiple paths on the same machine. This is useful in the case of an external hard drive that can be used to back up a folder located on an internal hard drive. Thanks for considering and please let me know if you have any questions.

**Comment by calmh** [comment]
This has been considered, but there are other programs that does this well and without the overhead that syncthing would require.
