### ISSUE TITLE
Option to prefer local/home network IP range

### ISSUE THREAD

**Issue by seb-1204** [syncthing/syncthing#4014]
Feature request.
It would be nice to have a field where I can input my home IP range and the IPs in that rage are seached for peers first. 
Most of the time I do need to sync within devices within my own network and there no immediate need to look outside of it. Howver I do not want to disable/block the range outside my LAN.

**Comment by calmh** [comment]
Locally discovered devices are preferred. But even so, if you are at home and the other device is at home, there is no harm to looking elsewhere as long as they connect locally in the end?

**Comment by AudriusButkevicius** [comment]
I think we close this. Syncthing already prefers local discovery when possible, I don't think brute forcing a subnet makes sense. In the end, if you want you can always set up static IPs.
