### ISSUE TITLE
Connection Error occurs on Web GUI after about 1 minute

### ISSUE THREAD

**Issue by perqin** [syncthing/syncthing#4019]
### What Happened

Refresh the home page and wait for about a minute, and a red Connection Error dialog pops up saying "Syncthing seems to be experiencing a problem processing your request. Please refresh the page or restart Syncthing if the problem persists."

### Environment

My Syncthing server is running on a Debian 8 VPS behind Nginx. `insecureSkipHostCheck` is enabled. I try opening the Web GUI on local machine with:

*  Chrome, which is behind a HTTP proxy
*  Firefox, which is configured not to use any proxy

But the error occurs in both browsers.

### Some useful information

I open the Chrome Dev Tool and find the error output in console:

```
GET http://syncthing.my-domain.com/rest/events/disk?limit=25 net::ERR_INCOMPLETE_CHUNKED_ENCODING
(anonymous) @ VM654:2
(anonymous) @ angular.js:8016
sendReq @ angular.js:7838
serverRequest @ angular.js:7572
wrappedCallback @ angular.js:10968
wrappedCallback @ angular.js:10968
(anonymous) @ angular.js:11054
$eval @ angular.js:11974
$digest @ angular.js:11800
$apply @ angular.js:12080
done @ angular.js:7862
completeRequest @ angular.js:8045
xhr.onreadystatechange @ angular.js:8001
```

And in Firefox console:

```
Error: data.reverse is not a function
refreshGlobalChanges</<@http://syncthing.my-domain.com/syncthing/core/syncthingController.js:629:24
$http/promise.success/<@http://syncthing.my-domain.com/vendor/angular/angular.js:7597:11
qFactory/defer/deferred.promise.then/wrappedCallback@http://syncthing.my-domain.com/vendor/angular/angular.js:10968:31
qFactory/defer/deferred.promise.then/wrappedCallback@http://syncthing.my-domain.com/vendor/angular/angular.js:10968:31
qFactory/ref/<.then/<@http://syncthing.my-domain.com/vendor/angular/angular.js:11054:26
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://syncthing.my-domain.com/vendor/angular/angular.js:11974:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://syncthing.my-domain.com/vendor/angular/angular.js:11800:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://syncthing.my-domain.com/vendor/angular/angular.js:12080:13
done@http://syncthing.my-domain.com/vendor/angular/angular.js:7862:34
completeRequest@http://syncthing.my-domain.com/vendor/angular/angular.js:8045:7
createHttpBackend/</xhr.onreadystatechange@http://syncthing.my-domain.com/vendor/angular/angular.js:8001:11
```

Well, I also try `curl` directly on my VPS:
```
curl http://syncthing.my-domain.com/rest/events/disk?limit=25 -H "Authorization: header-extracted-from-chrome-dev-tool" -H "X-CSRF-Token-X7F6E: header-extracted-from-chrome-dev-tool"
curl: (18) transfer closed with outstanding read data remaining
```

### Version Information

Syncthing Version: v0.14.23
OS Version: Debian 8 x64 (Syncthing Server)
Browser Version: Chrome 56.0.2924.87 (64-bit) and Firefox 51.0.1 (64-bit) (Local machine)

**Comment by calmh** [comment]
Most likely nginx is timing out the connections and terminating them, which the GUI interprets as a Syncthing failure because it thinks it's talking to Syncthing. I don't think this is a bug.

**Comment by canton7** [comment]
Hmm, maybe the docs page for reverse proxy setup should have the necessary timeout directives.

**Comment by calmh** [comment]
I've added this to the nginx config. I don't know the correct things for Apache.

**Comment by perqin** [comment]
Thanks for reply. The error is gone now:)
