### ISSUE TITLE
Prevent binding the GUI to a privileged port

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4020]
It seems a fairly common mistake to set the GUI to port 80, after which it can't start and is inaccessible. The settings dialog should probably not allow setting ports below 1024. To do that anyway, the advanced settings dialog can be used.

**Comment by canton7** [comment]
Maybe (in addition) the gui should attempt to bind to a default port (and then keep attempting successive ports until it succeeds) if binding to the port the user specified fails? 

Preventing privileged ports cuts our one class of error, bur doesn't prevent them from doing things like specifying a port that is already in use. Making sure that we always bind to something (which is then printed to stdout) will at least meant they can still get to the gui.

**Comment by AudriusButkevicius** [comment]
I guess we can check if the user is running with privileged access, or probe if we can bind somewhere below 1024 as we start up.
