### ISSUE TITLE
[Feature Request] Add Option to write Connected Remote-Devices to DNS Server or /etc/hosts

### ISSUE THREAD

**Issue by Mannshoch** [syncthing/syncthing#4039]
Please add an Option to write detected Devices into DNS-Server or /etc/hosts.

The reason is. I support different Family PCs connected over different Internet connections with dynamic IP-Adress. Sometimes I also have to connect them to support their Device over ssh. Because Syncthing is always running and have the PCs connected it would be nice if it publish his knowledge about connected devices to the system. So I could connect them easy.
I would like to see if syncthing write Hostnames like "PC-Name.syncthing"  to the /etc/hosts or an installed DNS Server on Linux, Android (like AdAway does)  and Windows devices.

**Comment by fabienengels** [comment]
That would means that syncthing has root privileges ... sounds like a pretty bad idea. Instead, maybe you should consider to use a service like dyndns or to deploy a vpn IMHO

**Comment by AudriusButkevicius** [comment]
Use the API's to work out the IPs if you want. This is definately out of scope of syncthing.

**Comment by Mannshoch** [comment]
This point with root was out of my scope. sorry. This kind of advanced Bash scripting and also this Rest API thing is new for me. Is there somewhere an Example script how I get an Information from Rest into a variable?

**Comment by AudriusButkevicius** [comment]
The docs have some examples, also just googling around might help you.

**Comment by Mannshoch** [comment]
Seems that is to far for my actual knowledge. Getting an xml from hat curl command you pasted is easy ...the rest not really.
Thanks for your interests I'm looking also into other solutions like Dyndns as you said.

**Comment by canton7** [comment]
I threw together a quick ruby script. Edit API_KEY and HOST, of course (you can find your API key Actions -> Settings -> API Key

```ruby
API_KEY = 'YOUR API KEY HERE'
HOST = 'http://localhost:8384'

require 'uri'
require 'net/http'
require 'json'

uri = URI(HOST)
http = Net::HTTP.new(uri.host, uri.port)
headers = {
  'X-API-Key' => API_KEY
}

config = JSON::parse(http.get('/rest/system/config', headers).body)
connections = JSON::parse(http.get('/rest/system/connections', headers).body)

config['devices'].each do |device|
  address = connections['connections'][device['deviceID']]['address']
  puts "#{device['name']}: #{address}"
end
```

**Comment by Mannshoch** [comment]
Thanks! @canton7  that was really helpful. It would be nice If you put this code into the docs. So other could have also a point to start with REST scripting.

**Comment by canton7** [comment]
It's pretty trivial stuff - I'm not sure we should be in the business of teaching people how to program 😄

**Comment by Mannshoch** [comment]
I am. Such Software like Syncthing, easy to setup and use, well placed in a time where sharing get more and more important. This Software could be the first touch of many people with scripting their own Ideas. 
I do not wish a big "how-to do every thing". Examples for the basics should be enough. ...but Examples for a lower knowledge.

**Comment by Ferroin** [comment]
The problem about giving examples like that is that they're still not all that useful unless you already have some background with the chosen programming language or a similar language.  There are all kinds of existing examples for various other REST API's out there for any number of languages, and Syncthing's API documentation is to be quite honest absolutely amazing compared to quite a few FOSS projects I've seen.

Put a bit differently, it's not the job of the developers to teach you how to talk to a REST API, it's their job to document their API.  A REST API isn't supposed to be an end-user interface, just like you don't make direct system-calls when you're moving files around on your computer.  In both cases (REST API's and system calls), it's supposed to be a way for other _software_ to interact with it, which in turn means that it's perfectly reasonable to expect people who are using it to have some minimal understanding of programming before doing so.

**Comment by Mannshoch** [comment]
@canton7 After a some hours now I got a working [script](https://forum.syncthing.net/t/start-script-as-root-if-syncthing-establish-a-new-connection/9516) which do as I wished.

Thanks again.
