### ISSUE TITLE
Android web GUI does not launch

### ISSUE THREAD

**Issue by okinasevych** [syncthing/syncthing#4040]
Attempted to launch Web GUI in Android version of Syncthing. Web GUI does not launch. Message simply indicates "Waiting for GUI." This happens each time I attempt to launch the Web GUI. 

### Version Information
Syncthing Version: v0.14.22.rc.1+12-g5a1ee7f
OS Version: Cyanogen 13.0-20161105-NIGHTLY-m8 (Android v6.0.1)
Browser Version: No browser appears to be activated.

**Comment by imsodin** [comment]
Please post your bug report in the appropriate repository (syncthing-android).

**Comment by canton7** [comment]
https://github.com/syncthing/syncthing-android/issues/new
