### ISSUE TITLE
"Connected to already connected device" repeats on both nodes

### ISSUE THREAD

**Issue by blsz** [syncthing/syncthing#4041]
"INFO: Connected to already connected device" repeats ever minute indefinitely on both nodes.  The messages on each node refer to the other.

The 2 nodes are currently paired. They may have been previously paired, then unpaired, and then paired again.  The nodes are currently running the same version but a different OS.
v0.14.24, Linux (64 bit)
v0.14.24, Windows (64 bit) 

Everything works but is it possible to stop the message without completely deleting the configurations on both ends?  I already tried resetting the configuration on the Windows node but would like to avoid resetting the Linux node.

**Comment by AudriusButkevicius** [comment]
Please use the [forum](https://forum.syncthing.net/) for support.
