### ISSUE TITLE
Syncthing Android Does Not Load

### ISSUE THREAD

**Issue by nebutron** [syncthing/syncthing#4044]
**What Happened?**

When loading the application on Android 7.1.1 you get an endless loading animation. Nothing happens. I have to wipe it, kill the process 2 to 10 times before it actually loads and starts working again. During this time syncing does not work at all and my computer shows all devices offline. See screenshot - 

![screenshot_20170318-080121](https://cloud.githubusercontent.com/assets/22918986/24072360/bf88a2a0-0bbc-11e7-8008-789137f62592.png)

**What should happen?**

The app should open without issue. Load into the options and the folders etc. The app should be syncing at all times without problem.

**Steps?**

There are no steps. I am using a PureNexus ROM of 7.1.1 using the latest F-Droid version of Syncthing. The app randomly does this and will randomly fix itself really.

Syncthing Version: v0.14.24
OS Version: Android 7.1.1

**Comment by nebutron** [comment]
Forgot to ask if there is a way to grab log files? I can provide those but not sure how to get them or would I need to use an external service to grab logs for it.

**Comment by AudriusButkevicius** [comment]
This is the wrong repository, please reopen the issue [https://github.com/syncthing/syncthing-android](here)
