### ISSUE TITLE
Android, SD card: Large files fail to transfer with "truncate: invalid argument"

### ISSUE THREAD

**Issue by tsftd** [syncthing/syncthing#4046]
Related part from original post in forums:

Ok, so I'm using the Android app, and actually having less issues with it than most people.

However, after getting stuck at XX% and nothing getting it to finish syncing (restart Syncthing, reboot phone, etc), I took a closer look and realized what the problem is: apparently, it can't sync large files.

The file in question is a 3.53gb DVD ISO. Deleting it resolved the issue. Now, I'm not sure exactly what the problem is, but I can confirm that it's not a filesystem issue, as I've transferred the same exact file via both Resilio and FTP. It's really not a problem for me -- I can just stick it in another folder, as it's not something that's going to be deleted, but I figured that I'd point it out for the devs.

I can provide the file causing the issue if the devs want to recreate it exactly.

Log file shows:

[X75AK] 02:34:26 INFO: Puller (folder "phonefjdidekfg", file "School/Christmas DVD.iso"): dst truncate: truncate /storage/sdcard1/Android/data/com.nutomic.syncthingandroid/files/School/.syncthing.Christmas DVD.iso.tmp: invalid argument
[X75AK] 02:34:26 INFO: Puller: final: truncate /storage/sdcard1/Android/data/com.nutomic.syncthingandroid/files/School/.syncthing.Christmas DVD.iso.tmp: invalid argument
[X75AK] 02:34:27 INFO: Puller (folder "phonefjdidekfg", file "School/Christmas DVD.iso"): dst truncate: truncate /storage/sdcard1/Android/data/com.nutomic.syncthingandroid/files/School/.syncthing.Christmas DVD.iso.tmp: invalid argument
[X75AK] 02:34:27 INFO: Puller: final: truncate /storage/sdcard1/Android/data/com.nutomic.syncthingandroid/files/School/.syncthing.Christmas DVD.iso.tmp: invalid argument
[X75AK] 02:34:27 INFO: Puller (folder "phonefjdidekfg", file "School/Christmas DVD.iso"): dst truncate: truncate /storage/sdcard1/Android/data/com.nutomic.syncthingandroid/files/School/.syncthing.Christmas DVD.iso.tmp: invalid argument
[X75AK] 02:34:27 INFO: Puller: final: truncate /storage/sdcard1/Android/data/com.nutomic.syncthingandroid/files/School/.syncthing.Christmas DVD.iso.tmp: invalid argument
[X75AK] 02:34:28 INFO: Puller (folder "phonefjdidekfg", file "School/Christmas DVD.iso"): dst truncate: truncate /storage/sdcard1/Android/data/com.nutomic.syncthingandroid/files/School/.syncthing.Christmas DVD.iso.tmp: invalid argument
[X75AK] 02:34:28 INFO: Puller: final: truncate /storage/sdcard1/Android/data/com.nutomic.syncthingandroid/files/School/.syncthing.Christmas DVD.iso.tmp: invalid argument
[X75AK] 02:34:29 INFO: Puller (folder "phonefjdidekfg", file "School/Christmas DVD.iso"): dst truncate: truncate /storage/sdcard1/Android/data/com.nutomic.syncthingandroid/files/School/.syncthing.Christmas DVD.iso.tmp: invalid argument
[X75AK] 02:34:29 INFO: Puller: final: truncate /storage/sdcard1/Android/data/com.nutomic.syncthingandroid/files/School/.syncthing.Christmas DVD.iso.tmp: invalid argument
[X75AK] 02:34:29 INFO: Puller (folder "phonefjdidekfg", file "School/Christmas DVD.iso"): dst truncate: truncate /storage/sdcard1/Android/data/com.nutomic.syncthingandroid/files/School/.syncthing.Christmas DVD.iso.tmp: invalid argument
[X75AK] 02:34:29 INFO: Puller: final: truncate /storage/sdcard1/Android/data/com.nutomic.syncthingandroid/files/School/.syncthing.Christmas DVD.iso.tmp: invalid argument
2017/03/19 02:34:29 http: TLS handshake error from 127.0.0.1:49069: tls: client offered an unsupported, maximum protocol version of 300
[X75AK] 02:34:30 INFO: Puller (folder "phonefjdidekfg", file "School/Christmas DVD.iso"): dst truncate: truncate /storage/sdcard1/Android/data/com.nutomic.syncthingandroid/files/School/.syncthing.Christmas DVD.iso.tmp: invalid argument
[X75AK] 02:34:30 INFO: Puller: final: truncate /storage/sdcard1/Android/data/com.nutomic.syncthingandroid/files/School/.syncthing.Christmas DVD.iso.tmp: invalid argument
[X75AK] 02:34:30 INFO: Puller (folder "phonefjdidekfg", file "School/Christmas DVD.iso"): dst truncate: truncate /storage/sdcard1/Android/data/com.nutomic.syncthingandroid/files/School/.syncthing.Christmas DVD.iso.tmp: invalid argument
[X75AK] 02:34:30 INFO: Puller: final: truncate /storage/sdcard1/Android/data/com.nutomic.syncthingandroid/files/School/.syncthing.Christmas DVD.iso.tmp: invalid argument
[X75AK] 02:34:31 INFO: Puller (folder "phonefjdidekfg", file "School/Christmas DVD.iso"): dst truncate: truncate /storage/sdcard1/Android/data/com.nutomic.syncthingandroid/files/School/.syncthing.Christmas DVD.iso.tmp: invalid argument
[X75AK] 02:34:31 INFO: Puller: final: truncate /storage/sdcard1/Android/data/com.nutomic.syncthingandroid/files/School/.syncthing.Christmas DVD.iso.tmp: invalid argument
[X75AK] 02:34:31 INFO: Puller (folder "phonefjdidekfg", file "School/Christmas DVD.iso"): dst truncate: truncate /storage/sdcard1/Android/data/com.nutomic.syncthingandroid/files/School/.syncthing.Christmas DVD.iso.tmp: invalid argument
[X75AK] 02:34:31 INFO: Puller: final: truncate /storage/sdcard1/Android/data/com.nutomic.syncthingandroid/files/School/.syncthing.Christmas DVD.iso.tmp: invalid argument
[X75AK] 02:34:32 INFO: Puller (folder "phonefjdidekfg", file "School/Christmas DVD.iso"): dst truncate: truncate /storage/sdcard1/Android/data/com.nutomic.syncthingandroid/files/School/.syncthing.Christmas DVD.iso.tmp: invalid argument
[X75AK] 02:34:32 INFO: Puller: final: truncate /storage/sdcard1/Android/data/com.nutomic.syncthingandroid/files/School/.syncthing.Christmas DVD.iso.tmp: invalid argument
[X75AK] 02:34:32 INFO: Folder "phonefjdidekfg" isn't making progress. Pausing puller for 1m0s.
### Version Information

Syncthing Version: v0.9.7
OS Version: Android version 4.4.2 (Kernel version 3.4.0)

**Comment by calmh** [comment]
Your SD card is most likely formatted with FAT32, which does not support files larger than 2 GB.

**Comment by tsftd** [comment]
As denoted in the OP, "I can confirm that it's not a filesystem issue, as I've transferred the same exact file via both Resilio and FTP."

By that, I meant that I've transferred it onto the same SD card.

Also, FAT32 supports files of up to 4gb.  You are thinking of FAT16, which only supports up to 2gb.

**Comment by calmh** [comment]
You're right. In that case I suspect it's the truncate operation that's not supported on FAT (on Android, at least).

**Comment by AudriusButkevicius** [comment]
But that doesn't explain why it happens only for large files.

**Comment by calmh** [comment]
Yeah I don't know either, but that's what the error says. Needs someone with an Android to make progress, I think.

**Comment by AudriusButkevicius** [comment]
I don't think truncate is mandatory, could we just ignore it if it fails?

**Comment by calmh** [comment]
Mostly yes. There's the very rare condition where we start syncing a file, fail for whatever reason, leave the temp file, the global version the file shrinks, we retry the sync. If we're not doing truncate() the reused temp file will be larger than the desired end result, and we'll end up with a file successfully synced plus garbage at the end.

I don't think this has ever happened. It was the case before we implemented truncate() as well.

**Comment by calmh** [comment]
A workaround here is disableSparseFiles in the advanced folder config.

**Comment by calmh** [comment]
Given that, and the obvious rarity of this issue, I don't think it needs fixing at the moment?
