### ISSUE TITLE
How to make it work on CentOS?

### ISSUE THREAD

**Issue by Jckarlos92** [syncthing/syncthing#4047]
Hi! I'm setting this up for my enterprise distribution machine and I would like to know if anyone has a CentOS configuration manual or something like that?

Thanks,
Juan Carlos

**Comment by AudriusButkevicius** [comment]
Issue tracker is for issues (as the issue template explains), please keep it that way.
Docs have explanations for auto-startup etc, if you still have questions, use the forum.
