### ISSUE TITLE
Feature? Use relays for faster connection if possible

### ISSUE THREAD

**Issue by TruputiGalvotas** [syncthing/syncthing#4051]
First of all, I'd like to tell that I'm using syncthing not as intended, but since I've found all I've needed and it fits my current case I've decided to try it out for this task. In the process I've encountered a situation, which possibly can help users which are using it as intended.

The job I'm using syncthing for is simple - some people shoot some movies with a camera and at the end of the day they give me hard drive with data to be sent overseas (like from Europe to USA) for the editing people to start making edits of that footage.

Why syncthing - I've needed no confirmation unattended (from the receiving part) solution, and since I've found syncthing has Send Only and IgnoreDelete modes/properties, I've used those. It was not intended for syncthing to be used this way, so I do not expect to see when the data has been sent (except when syncthing traffic comes down to ~0), or that there are differences in OS reported size of the folder (actually whole hard drive) vs synthing reported local size (this is on sending part, I know that there are differences between Global and Local state, since Global basically is receiving end with all data and sending part is Local only), although a bit strange when you have >1GB different between what OS says and syncthing, but the receiving end never complained about missing some files.

Sorry for large introduction/discourse, on to the noticed situation.

The situation was that we expected to send uncompressed raw video camera data (not talking about syncthing lossless compression, talking about lossy video compression), since both receiving end and sending part has a connection of 1 gbps (promised by our ISP). It turned out, that receiving end ISP (Google Fiber, by the way, so be aware if you are a user or planing to become one) is kind of a lier and doesn't give the 1 gbps, actually, just around ~40mbps and that is not nearly enough to send raw footage, so we reverted to lossy compression to solve overnight sending problem.

At first, of course, I've googled whether this is a syncthing issue (turned out to be not, as mentioned - ISP problem) and one of the things I remember was to check whether you are connected to relay, because it might slow things down.

But here a week later an Idea came to my mind, that relays - instead of being a problem of slowness, in this situation could be a solution to solving network connection problems, but for that, syncthing should do something like this:

1. Test connection speed between X devices and store it somewhere - might start sending data at this point
2. While the data sending is happening, try testing relay within the same country of either the party (let's say.. can be something else, but in my experience usually ISP tend to have the speed limits they've promised with the limits of country, in my country, at least, ISP even have "national speed" and "international speed" (usually they are the same now, but still - proves the point))
3. Compare the speed in 1 step vs 2 step
4. If 2 is faster, switch to relay connection

Why that came to my mind - because their ISP had good connection within their national country USA, my ISP was better in this regard, since it had the ~1 Gbps connection to the USA (used speedtest.net for testing, Google Fiber wasn't in the provider list, so I've tested some other ISP (a couple) servers).

So in my case it could have:

1. receiver with ISP A connected to Relay on ISP B connected to sender ISP C

or maybe even this?

2. receiver with ISP A connected to Relay on ISP B connected to relay on ISP C connected to sender on ISP D

I understand that receiver can be connected to relay which has the same ISP as receiver (in other words receiver with ISP A connected to Relay on ISP A connected to sender ISP B) and then I would have the same situation - I don't suggest to check the ISPs of the receiver/relay/sender, just to measure connection speed and choose the faster one.

I won't pretend to know much of syncthing and how it works, so I don't know whether this is possible. But I think this could benefit for users that are syncing between different countries or continents

**Comment by AudriusButkevicius** [comment]
I don't think this is viable as relays are community provided resources which have varying utilization, so it's fast now, slow 5mins later as someone else started filling up the pipe. Furthermore they are provided based on people using them on good will and not abusing them, which is why most relays will run with per-session limits. Relays are not there for speed, relays are there in order to connect if you have firewalls/NATs on both sides.


To be honest, I suspect your speed issues could be due to crypto overhead oppose to ISP. I suggest you use iperf or something like that to benchmark the connections. Syncthing is definately be one of the slower point to point transfer mechanisms, as it's not meant for one off transfers.

**Comment by TruputiGalvotas** [comment]
Thanks for clarification. I don't know whether it's a thing now, but I saw some issues about private relays, if that is going to happen (or exists now) is there an option to force syncthing to use the private relay? It could solve this issue basically then.

As for ISP - we already tested (with different protocols, different servers, different ISP on our country (Lithuania, so labas Audriau:) and with a neighbour country Latvia as well, just to make sure it's ISP problem)

I understand that relays intended purpose is to get connected, and I'll understand if you'll close this, but think about what I wrote about (forcing syncthing to use a private relay), maybe at some point in the future this might happen?

**Comment by AudriusButkevicius** [comment]
Use of private relays is already supported. You can run your own relay with -pools=""" arg for it not to be publically advertised, and just put the relay address as one of the listen addresses in syncthing. If you want syncthing to use the relay only, then remove default from the listen addresses on both sides as that means both direct connections and  public relay, and we always prefer a direct connection over a relay.

I am pretty sure that as you solve the throughput problem, you'll hit syncthings inefficiency problems.

**Comment by AudriusButkevicius** [comment]
Given no further feedback, case closed.
