### ISSUE TITLE
Strange issue with deleted files with blocks

### ISSUE THREAD

**Issue by the-glu** [syncthing/syncthing#4053]
Hello,

I'm currently implementing a custom implementation of the syncthing protocol and I noticed something strange with deleted files.

I know this may be a bug in my implementation, but I don't think I broke the protocol, at least according to the documentation.

I create a file on my side. Everything is fine. Then I delete it. Everything is fine, but I send this index update:

```
name: "small_new_logo2 (copie 1) (copie 1).png"
modified_s: 1490123996
deleted: true
version {
  counters {
    id: 12341524340436289198
    value: 2
  }
}
sequence: 1256
modified_ns: 235634803
Blocks {
  size: 3814
  hash: "\264]\013_G\030\243\024njt\014K24\313w\010<\370\036\355\265\022\241\2770\240L\324\345|"
}
```
Remark: I send blocks. This seems stupid, but the variable wasn't cleanup on my side when the file was deleted.
Syncthing delete the file, no problem.

Then, I add the same file again, and syncthing is stuck. The file is not added back, and I have this errors in logs:

```
(...)
[XXX] 20:23:12 INFO: Puller (folder "synctest", file "small_new_logo2 (copie 1) (copie 1).png"): shortcut: chmod: chmod /home/XXX/SyncTest/small_new_logo2 (copie 1) (copie 1).png: no such file or directory
[XXX] 20:23:12 INFO: Puller: shortcut: chmod /home/XXX/SyncTest/small_new_logo2 (copie 1) (copie 1).png: no such file or directory
[XXX] 20:23:12 INFO: Folder "synctest" isn't making progress. Pausing puller for 1m0s.
```
Sending a correct index update for a deleted file, without blocks, fix the issue.

Again, I know it's stupid to send blocks of a deleted file, it doesn't make sense. But syncthing should be able to handle the case, no ? Or the protocol definition should be updated to prevent client to send blocks ?

If needed I can try to make a PR with one of the "fix".

### Version Information

Syncthing Version: v0.14.24
OS Version: ArchLinux

**Comment by AudriusButkevicius** [comment]
Yeah, sounds like we should null the blocks on receipt of deletes or panic if the client doesn't do so.

**Comment by calmh** [comment]
Your index update is a spec violation. If you look at the "deleted" attribute under FileInfo, it says

> The deleted field is set when the file has been deleted. The block list SHALL be of length zero

We might still want to handle this better.

**Comment by the-glu** [comment]
You're right, I didn't saw it, I checked only the blocks attribute definition :'(

**Comment by calmh** [comment]
I'm adding some checks on incoming messages. Given that Syncthing is supposed to be the reference implementation it might as well be fairly strict so it gives sane error messages to other implementers.
