### ISSUE TITLE
AVG identified syncthing.exe (Windows x64 build, 0.14.25) as infected with IDP.ALEXA.51.

### ISSUE THREAD

**Issue by bablat** [syncthing/syncthing#4054]
[Avast AV](https://www.avast.com)'s Behavior Shield (I guess it's their heuristics-based protection) has identified syncthing.exe (Windows x64 build, 0.14.25) as infected with IDP.ALEXA.51.

I assume it's a false positive, submitted the executable to Avast for review - but assume others will get this warning as well, with a suggestion to quarantine the file.

**Comment by calmh** [comment]
Noted, thanks, leaving open for a while.

**Comment by bablat** [comment]
They reviewed the sample, I got this back just now:

Our virus specialists have been working on this problem and it has now been resolved. The provided file won't be detected by Avast anymore.

**Comment by jedie** [comment]
Same with v0.14.31, Windows (64 bit): https://www.virustotal.com/de/file/1c9eca627aab34c13747a6d6db676054829def9b76cae0d6ea59d4f4b365f883/analysis/

**Comment by calmh** [comment]
You guys need to bring this up with your AV vendors, it's not something we can do something about unfortunately.

**Comment by AudriusButkevicius** [comment]
Report it to the vendor.
