### ISSUE TITLE
Default Folder

### ISSUE THREAD

**Issue by dtxl** [syncthing/syncthing#4055]
Using the latest syncthing version for Windows on two test devices. These devices are in a domain with a home folder on "X:" set to a file server via gpo.

Starting syncthing creates then the initial "Default Folder" as "X:\Sync" if the device is connected to the file server. Otherwise it fails with the notice

"Stopping folder "Default Folder" (default)-folder path missing"
"Creating folder marker: open \\?\X:\Sync\.stfolder: The specified network name is no longer available."
"Loading ignores: open \\?\X:\Sync\.stignore: The specified network name is no longer available."

This scenario can lead to different devices of a domain used by the same user using the same default sync folder of syncthing on a file server. If a device is then not connected to the file server syncthing can't work. This might, but must not be a desirable configuration.

Additionally, in "Edit Folder" the description "Path to the folder on the local computer: Will be created if it does not exist. This tilde character {~) can be used as a shortcut for X:\" is misleading, since "X:" in this scenario is not a folder on the local computer.

I've found no possibility to change the configuration of "~" from "X:" to some place local on the device which I would find helpful. Secondly, although, the folder "X:\Sync" can easily be changed afterwards, maybe this configuration can be made accessible in the config.xml file for the initial setup.

Thanks.

**Comment by Ferroin** [comment]
For the first start folder creation thing, you can get rid of that failure and the initial folder creation by having the `STNODEFAULTFOLDER` environment variable set.  There is no way however (and there should not be) to prevent Syncthing from throwing an error though if it can't get to one of it's configured folders.

Based on some personal experimentation, it looks like you can pre-load the `config.xml` file with the parts you need (assuming it still has the absolutely required stuff) and Syncthing will just use defaults for stuff you don't have listed there.  By doing this and disabling creation of the default folder, you can essentially create a custom default folder.

As for the 'Path to the folder on the local computer' message, it may not be intuitive, but it is still accurate.  It means that's the path that you use on the local system to access that folder, not that the data is necessarily stored on the local system.  In the case you described, `X:\Sync` is still the path on the local system to access the default folder, even if it isn't stored locally.

As for changing the meaning of `~`, I'm not certain on Windows, but I'm pretty sure you can change it on UNIX systems by having HOME set differently in the environment for Syncthing.

**Comment by AudriusButkevicius** [comment]
So I am closing this as this is mostly misconfiguration/unclear of how things work and not an actual fixable bug. Please use the forum to get help regarding this.

**Comment by dtxl** [comment]
Thanks for the answer.
Of course there should be no way to prevent an error message, it was for documentation of what happened in this case.
I've found the description of the STNODEFAULTFOLDER environment variable, thanks.
Concerning the 'Path to the folder on the local computer' message, I see. Still, could be made more intuitively.
The Windows equivalent of ~ is the HOMEDRIVE variable which is set in a corporate environment and cannot and should not be changed by a user. It's the choice of the software in question what variable to use. In the same issue, e.g. Resilio Sync or dropbox creates the default folder locally on a device.
Pre-loading a config.xml file with a changed default folder would be anyway a solution if it's possible and the use of HOMEDRIVE is not fix implemented.

Thanks again.
