### ISSUE TITLE
Feature Request: Integrated Remote Mgmt of Connected Nodes

### ISSUE THREAD

**Issue by a8ksh4** [syncthing/syncthing#4057]
Non-trivial feature request:  Add the capability to grant management access to connected nodes, and add functionality in the web interface to "click through" into another node and configure it as long as access is granted.  

I don't know how this would be implemented; maybe an ssh port forward is initiated to the remote node to forward web traffic for the management session? 

Thanks for your consideration.

**Comment by AudriusButkevicius** [comment]
This has been asked before and is still out of scope of syncthing as it stands now. 

There are some community contributions adding simillar functionality, check them out.
If anything, something should be written on top to provide this, as not everyone will want that out of the box and will potentially get scared by it and the complexity it adds to the UI.
