### ISSUE TITLE
A little bug in REST API

### ISSUE THREAD

**Issue by muzzy121** [syncthing/syncthing#4058]
I'm using REST API to get some data about actual sync process.
Sometimes, after proper synchronization, when I'm refreshing data by REST API /rest/db/need it shows me that I still have some unfinished files to sync. Funnies thing is that GUI and Event API informs that all of those files has done without any problems.
I have three remote devices with three different folders which are syncing between them. In all cases I see the same problem.
After ST restart files taken by REST API are missing.

### Version Information

Syncthing Version: v0.14.25
OS Version: Windows 2012 R2
Browser Version: All Web Browsers

**Comment by AudriusButkevicius** [comment]
/need calls are cached I think, as they are very expensive, so I guess this is a cache invalidation problem.

**Comment by muzzy121** [comment]
Maybe, but stange thing is that it is not refeshing that cache. I still see the file which was synced yesterday.

**Comment by calmh** [comment]
There is no cache on the /need call (I just checked). Is this reproducible somehow?

**Comment by muzzy121** [comment]
Sorry, I haven't seen your message. Yes, I still have this problem.
There is no key, files are sync proper but in rest api there are in the sync status and have 0 bytes size.
I'm working on the project, I want to give people possibility to check sync status of the folders.
This is the print screen from yesterday
<img width="883" alt="2017-04-11 08_40_36-cadelan_forelan sync check site" src="https://cloud.githubusercontent.com/assets/26625935/24895845/a1d9cf48-1e92-11e7-8a5f-6104090bfff0.png">

**Comment by calmh** [comment]
I don't know what that is a screenshot from. I mean, can you describe a method for us to reproduce this?

**Comment by muzzy121** [comment]
Of course. I'm getting those data from REST API. What I've send you those are those data but formated on my web site. Now, if I will use CURL i this case:
_curl -X GET -H "X-API-Key: abc123" http://localhost:8384/rest/need_
It will return the information that there are some file "in progress".
But if I will check syncthing GUI or shared folder this file exist and sync finished proper.
If I will restart syncthing instance information about this file (or files) disappears.

**Comment by muzzy121** [comment]
Maybe I can send you logs?
You will be able to check why this file stuck.

**Comment by calmh** [comment]
Sure, if you have logs that contain clues please do post them.

**Comment by muzzy121** [comment]
Qestion Is how do I get it? :)

**Comment by calmh** [comment]
If it can't be synced it remains on the list of files to be synced. This is not a bug as far as I can see, and also the folder should not be indicated as "up to date" at this stage. So I'm not sure what you mean here really?
