### ISSUE TITLE
Allow specifying a file bundling type

### ISSUE THREAD

**Issue by wrouesnel** [syncthing/syncthing#4060]
Suppose I'm synchronizing a folder full of git repositories.

In almost every case, file-level synchronization will simply corrupt everything - but what I'm trying to accomplish is not unreasonable - I want to move my git working state between machines.

Now although a file level sync is unreasonable for git, a folder level sync is not - i.e. provided I didn't edit files on both machines, then if syncthing syncs the repositories quickly enough it can seamlessly move the state between machines.

What I'd like to be able to do is define a rule which pattern matches on the `.git` folder existing (or better - does that, when runs git status or something to confirm it is what it looks like), and tells syncthing *not* to do a file by file level synchronization, but rather move the entire folder to a temporary folder, and then do an atomic replace once it's done (or flag a conflict if in the intervening time I've edited both copies).

**Comment by AudriusButkevicius** [comment]
Out of scope of syncthing I feel.
