### ISSUE TITLE
KCP doesn't reconnect after connection is broken

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4063]
Trivial to reproduce:

Start up s1 and s2 (`cd test; syncthing -home h1` etc) and let them connect. Restart one side. The other will time out the connection after ~ eight minutes - this is expected, as we don't have any `RST`-equivalent in this protocol (although I think the interval is unexpectedly long).

After that they never manage to connect again. To get them to be able to connect, the other side must also be restarted.

This has nothing to do with NAT etc as these are two devices with hardcoded addresses to each other on the same host. Presumably it's about some sort of connection state that is never cleared out.

0.14.26-rc.1

**Comment by AudriusButkevicius** [comment]
Cannot repro with the steps given.

I have s1 on listen only and s2 on dial only.

Tried the following:

1. Wait for s1 and s2 connect, repeat 5 times { kill s1, wait for timeout on s2, start s1, wait for s1 and s2 
connect } - works fine
2. Wait for s1 and s2 connect, repeat 5 times { kill s2, wait for timeout on s1, start s2, wait for s1 and s2 connect } - works fine
3. Wait for s1 and s2 connect, repeat 5 times { kill s1, start s1, wait for s1 and s2 connect } - works fine
4. Wait for s1 and s2 connect, repeat 5 times { kill s2, start s2, wait for s1 and s2 connect } - works fine

The only case which is not tested is mixed connections on each side.

Can you check if it's easily repro'ed on your side?

**Comment by calmh** [comment]
How long is the timeout supposed to be? This is my repro:

1. Start s1 and s2, let them connect (happens immediately)
2. Open the s2 gui and select "restart"
3. Wait for them to reconnect

The reconnect doesn't happen. Both sides mention i/o timeout as the reason why.

https://kastelo.net/t/s1.log
https://kastelo.net/t/s2.log

**Comment by AudriusButkevicius** [comment]
Its around 50 seconds.

**Comment by AudriusButkevicius** [comment]
Ok. one important detail, one side thinks it's connected, where as the other one doesn't.
