### ISSUE TITLE
Transfert_running file

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#4066]
not a bug - just feature suggestion

Many users need or want hidden files be hidden.
Many, often the same, don't even think to look at the GUI. 
What about making the temporary downloading files visible so that they know there is active synching running?
Also, in the same idea, but having sub-dirs currently populating in mind, we could have a visible temporary _000 syncthing_is_downloading_now !_ file in the shared folder root, whatever downloading files destination is share's root or sub-dir.

All related cleaning remaining the same as current.

Okay, feel free to discard, no worry

**Comment by calmh** [comment]
The Syncthing philosophy is to stay out of the way unless disturbing the user is necessary - keeping temp files hidden is one part of that. So I think no.

**Comment by canton7** [comment]
There are plenty of tray icons which will indicate when Syncthing is synchronizing, if that's what the user wants.

**Comment by AudriusButkevicius** [comment]
Agree, no.

**Comment by bugith** [comment]
You're the bosses. Excellent philosophy. I just though it was less disturbing to see temp files than wandering if a bunch of transfer is complete allowing to move a sub-dir out of syncthing scope. This was for users that don't use shared folders as repositories, but instead use them as kind of gateways.
Okay, it's time for me to teach them they have Ctrl+H toggle (happy linux ones).
Bye guys
