### ISSUE TITLE
fatal error: netpollinit: failed to create descriptor

### ISSUE THREAD

**Issue by tommishe** [syncthing/syncthing#4067]
When trying to run syncthing v0.14.23 "Dysprosium Dragonfly" (go1.8rc3 linux-arm)  on
Linux 3.0.35-rt56 PREEMPT armv6l GNU/Linux

I get the following:
(taken from panic log file):

[VLSFZ] 01:48:46 INFO: syncthing v0.14.23 "Dysprosium Dragonfly" (go1.8rc3 linux-arm) jenkins@build.syncthing.net 2017-02-07 20:25:33 UTC
[VLSFZ] 01:48:46 INFO: My ID: VLSFZSP-3FJNWK2-JS34JWX-24WPDXH-CWG2FMW-5NVUNZJ-OGGT2LI-QYSLRAV
[VLSFZ] 01:48:48 INFO: Single thread SHA256 performance is 3.6 MB/s using crypto/sha256 (3.6 MB/s using minio/sha256-simd).
[VLSFZ] 01:48:53 INFO: Hashing performance with weak hash is 3.17 MB/s
[VLSFZ] 01:48:58 INFO: Hashing performance without weak hash is 3.38 MB/s
[VLSFZ] 01:48:58 INFO: Default folder created and/or linked to new config
...
Panic at 2000-01-15T01:48:58Z
fatal error: netpollinit: failed to create descriptor

goroutine 1 [running]:
runtime.throw(0x5f9e19, 0x28)
	/usr/local/go/src/runtime/panic.go:596 +0x70 fp=0x10e3c4f0 sp=0x10e3c4e4
runtime.netpollinit()
	/usr/local/go/src/runtime/netpoll_epoll.go:36 +0xb0 fp=0x10e3c500 sp=0x10e3c4f0
net.runtime_pollServerInit()
	/usr/local/go/src/runtime/netpoll.go:86 +0x14 fp=0x10e3c50c sp=0x10e3c500
sync.(*Once).Do(0xa739b0, 0x77968c)
	/usr/local/go/src/sync/once.go:44 +0xb8 fp=0x10e3c524 sp=0x10e3c50c
net.(*pollDesc).init(0x10d15b3c, 0x10d15b00, 0x0, 0x0)
	/usr/local/go/src/net/fdpoll_runtime.go:35 +0x24 fp=0x10e3c53c sp=0x10e3c524
net.(*netFD).init(0x10d15b00, 0x80, 0x0)
	/usr/local/go/src/net/fd_unix.go:48 +0x28 fp=0x10e3c550 sp=0x10e3c53c
net.(*netFD).listenStream(0x10d15b00, 0xa26bf0, 0x10d0e6a0, 0x80, 0x0, 0x0)
	/usr/local/go/src/net/sock_posix.go:172 +0x15c fp=0x10e3c588 sp=0x10e3c550
net.socket(0xa256c0, 0x10d0ab40, 0x5dbd3a, 0x3, 0x2, 0x1, 0x0, 0x0, 0xa26bf0, 0x10d0e6a0, ...)
	/usr/local/go/src/net/sock_posix.go:79 +0x1a4 fp=0x10e3c5d8 sp=0x10e3c588
net.internetSocket(0xa256c0, 0x10d0ab40, 0x5dbd3a, 0x3, 0xa26bf0, 0x10d0e6a0, 0x0, 0x0, 0x1, 0x0, ...)
	/usr/local/go/src/net/ipsock_posix.go:154 +0xb8 fp=0x10e3c618 sp=0x10e3c5d8
net.listenTCP(0xa256c0, 0x10d0ab40, 0x5dbd3a, 0x3, 0x10d0e6a0, 0x10, 0x10, 0x10d0abec)
	/usr/local/go/src/net/tcpsock_posix.go:156 +0x70 fp=0x10e3c660 sp=0x10e3c618
net.ListenTCP(0x5dbd3a, 0x3, 0x10d0e6a0, 0x779680, 0xa236a0, 0x10d0e6a0)
	/usr/local/go/src/net/tcpsock.go:295 +0x78 fp=0x10e3c6ac sp=0x10e3c660
net.Listen(0x5dbd3a, 0x3, 0x10d0ab80, 0xe, 0x2, 0x10d0ab80, 0xe, 0x0)
	/usr/local/go/src/net/dial.go:558 +0x464 fp=0x10e3c708 sp=0x10e3c6ac
main.getFreePort(0x5e0df1, 0x9, 0x10e3c8e0, 0x1, 0x1, 0x375a5bb7, 0xa5a7312e, 0xe29218a2)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:1180 +0xe8 fp=0x10e3c760 sp=0x10e3c708
main.defaultConfig(0x10d0a390, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:1118 +0x254 fp=0x10e3cd40 sp=0x10e3c760
main.loadConfig(0x2, 0x20, 0x10)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:980 +0xbc fp=0x10e3cff8 sp=0x10e3cd40
main.loadOrCreateConfig(0x10d121e0)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:988 +0x18 fp=0x10e3d2cc sp=0x10e3cff8
main.syncthingMain(0xbef7cd21, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5db6a8, 0x1, 0x0, ...)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:667 +0x7bc fp=0x10e3de74 sp=0x10e3d2cc
main.main()
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:444 +0x3c8 fp=0x10e3dfbc sp=0x10e3de74
runtime.main()
	/usr/local/go/src/runtime/proc.go:185 +0x1e4 fp=0x10e3dfe4 sp=0x10e3dfbc
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:1017 +0x4 fp=0x10e3dfe4 sp=0x10e3dfe4

goroutine 7 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x154
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x30

goroutine 12 [chan receive]:
main.setupSignalHandling.func2(0x10e0e700)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:969 +0x2c
created by main.setupSignalHandling
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:971 +0x12c

goroutine 9 [chan receive]:
main.trackCPUUsage()
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0xdc
created by main.init.3
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x24

goroutine 10 [select, locked to thread]:
runtime.gopark(0x7799e8, 0x0, 0x5de641, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:271 +0xfc
runtime.selectgoImpl(0x10d1a7a0, 0x0, 0xc)
	/usr/local/go/src/runtime/select.go:423 +0x116c
runtime.selectgo(0x10d1a7a0)
	/usr/local/go/src/runtime/select.go:238 +0x10
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:434 +0x2bc
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:1017 +0x4

goroutine 11 [chan receive]:
main.setupSignalHandling.func1(0x10e0e600)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:959 +0x2c
created by main.setupSignalHandling
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:961 +0x90

goroutine 13 [select]:
github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).Serve(0x10d57290)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:338 +0xc0c
created by github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).ServeBackground
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:297 +0x2c

goroutine 14 [runnable]:
github.com/syncthing/syncthing/lib/events.(*bufferedSubscription).pollingLoop(0x10d13170)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:318 +0x48
created by github.com/syncthing/syncthing/lib/events.NewBufferedSubscription
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:313 +0x17c

goroutine 15 [chan receive]:
github.com/syncthing/syncthing/lib/events.(*bufferedSubscription).pollingLoop(0x10d131d0)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:318 +0x48
created by github.com/syncthing/syncthing/lib/events.NewBufferedSubscription
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:313 +0x17c

**Comment by calmh** [comment]
Interesting. Once, or every time? Anything odd in your Linux setup?

**Comment by tommishe** [comment]
Every time. Its an embedded system with a read only rootfs but I am pointing the home directory with the -home argument to a read/write area in the file system. I have been unable to find the function that calls epoll_create1() via netpollinit(). I *think* its coming from the setupSignalHandling() method, although I don't know what its trying to create the epoll fd for though? Any suggestions? I have had it running on this hardware with an older BSP running the 2.6.8 Kernel and accompanying FS.  Upgraded to the Linux 3.0.35 kernel and accompanying FS and it broke syncthing.

**Comment by tommishe** [comment]
I'm investigating if its a change in the glibc version that might be causing this?

**Comment by tommishe** [comment]
running syncthing under strace I see this :
epoll_create1(O_CLOEXEC)          = -1 ENOSYS (Function not implemented)
1069  epoll_create(0x400)               = -1 ENOSYS (Function not implemented)
1069  write(2, "netpollinit: failed to create ep"..., 46 <unfinished ...>
1051  <... read resumed> "netpollinit: failed to create ep"..., 4096) = 46

**Comment by AudriusButkevicius** [comment]
It seems your kernel does not have epoll enabled which go runtime relies on. Best I can suggest if to recompile the kernel with epoll enabled.

**Comment by calmh** [comment]
Fascinating. Yeah that counts as "odd setup" in this case. :)

**Comment by tommishe** [comment]
Thanks for the assistance. I guess this setup is quite normal for me, but does constitute an "odd setup"  compared to most normal  use cases :)
