### ISSUE TITLE
syncing Symlinks from Linux to Windows and back changes slashes around and breaks the symlinks

### ISSUE THREAD

**Issue by blubberdiblub** [syncthing/syncthing#4068]
### What happened

Today I noticed that I had symlinks with backslashes (obviously broken) on my Linux system in repositories I sync with windows. The symlinks were fine before, as they originated on the Linux system and I'm pretty sure they synced forth and back fine some time in the past (after all, symlink support is the very reason I switched my setup to Syncthing).

Creating a symlink to a file such as `testdir/testfile.txt` on the Linux system, syncing it forward to a Windows system and then waiting for or forcing a Rescan on the Windows folder syncs it back to Linux as `testdir\testfile.txt` instead. Creating the symlink on the Windows system in the first place results in the same behavior.

### What I expect to happen

  - A symlink `testdir/testfile.txt` on Linux should sync to Windows as `testdir\testfile.txt` (that works fine right now).
  - A symlink `testdir\testfile.txt` on Windows should sync to Linux as `testdir/testfile.txt` (that's broken right now).

(the same goes for relative symlinks that point to some parent directory, such as `../../foo/bar.txt` and `..\..\foo\bar.txt`, respectively)

### Way to reproduce

  - on a folder on Linux do this:
    * `mkdir testdir`
    * `echo foobar > testdir/testfile.txt`
    * `ln -s testdir/testfile.txt testlink.txt`
    * `cat testlink.txt`
  - let it sync to a Windows folder:
    * `type testlink.txt` shows the content fine
    * `dir testlink.txt` produces `testlink.txt [testdir\testfile.txt]`
  - force a sync back by rescanning the Windows folder (or wait until it does it automatically)
  - `cat testlink.txt` now fails on Linux
  - `ls -l testlink.txt` now produces `testlink.txt -> testdir\testfile.txt`

### Additional information

`stat`ing one of my now broken symlinks suggests that the problem likely started to show up on March 7 or before:
```
nboehm@eudora:/srv/storage/audio/sid$ stat r/Robocop_3.sid 
  File: r/Robocop_3.sid -> ..\..\C64Music\MUSICIANS\T\Tel_Jeroen\RoboCop_3.sid
  Size: 51        	Blocks: 0          IO Block: 4096   symbolic link
Device: fd02h/64770d	Inode: 8257713     Links: 1
Access: (0777/lrwxrwxrwx)  Uid: ( 1000/  nboehm)   Gid: (   29/   audio)
Access: 2017-03-07 11:32:27.568026851 +0100
Modify: 2017-03-07 11:32:27.568026851 +0100
Change: 2017-03-07 11:32:27.568026851 +0100
 Birth: -
```

### Version Information

Syncthing Version: v0.14.25 (on all my systems, Windows as well as Linux)
OS Version: Windows 10
OS Version: Ubuntu 16.10 (Yakkety Yak)
OS Version: Ubuntu 17.04 (Zesty Zapus)

**Comment by calmh** [comment]
This is solved in 0.14.26 which disables symlink support entirely on Windows.

**Comment by blubberdiblub** [comment]
Well ... the symlinks might now break anymore then, but that's not what I would call solved in my context, as I wouldn't be able to sync symlinks anymore ... and I would have to search for a different syncing solution again :(

**Comment by calmh** [comment]
Yeah I could see that. I'm amazed symlinks have appeared to work for you so far on Windows, as they have been consistently broken for many, many releases though.

**Comment by blubberdiblub** [comment]
Well, I had allowed normal users to create symlinks before I even set up Syncthing on the Windows box.
The reason is that I of course want my Git for Windows to create symlinks where there are symlinks in a repository instead of other hacky workarounds.

So that change in the Policy Editor might have made symlinks work fine for me with Syncthing, too, however, that's just an educated guess which I haven't verified.

**Comment by Ferroin** [comment]
Yes, it probably was allowing normal users to create symlinks that made Syncthing work with them.

FWIW, the whole 'Nobody but admins can create symlinks' crap started because Microsoft didn't want to make symlink attacks possible without having to beat vendors over the head to make them protect their own software from such attacks, which has of course resulted in a vicious cycle (nobody uses symlinks because normal users can't use them, normal users can't use them because nothing has reasonable protection against symlink attacks, nothing has reasonable protection against symlink attacks because nobody uses them).
