### ISSUE TITLE
Relays over IPv6

### ISSUE THREAD

**Issue by MikeLund** [syncthing/syncthing#4069]
Is there some technical limitation for having IPv6 relay servers on relays.syncthing.net ?
I see this forum post https://forum.syncthing.net/t/strelaysrv-ipv6-and-too-many-colons/8155/3 ; thus I assume there is something technically wrong.

So is it something that could be fixed in the future? Or is it an intentional thing that relays are only for IPv4, because v6 relays aren't very useful?
Other than me being an IPv6 zealot, the currently rare case of a IPv4-only client talking with an IPv6-only client could come to mind as being a useful case to allow dual-stacked relays. Thanks!

**Comment by AudriusButkevicius** [comment]
I don't think a v6 only and v4 only case is likely, as you'd end up being unable to use most of the internet.
Relays by definition are there to work around v4 nats on both sides, a problem that does not exist in v6 land.

This probably should be a discussion on the forum first, before this becomes an issue, hence closing.
