### ISSUE TITLE
KCP connection attempts block the connection service

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4072]
Well, not the entire service, but the connection loop. Basically, if the other side isn't responding the connection attempt will take "forever" (I don't know how long, but at the very least it stops at that point for minutes). This blocks connecting to other devices and addresses.

**Comment by AudriusButkevicius** [comment]
Do you know where exactly it gets stuck?

I suppose if the other side advertises kcp, but is not actually listening it will block?

**Comment by AudriusButkevicius** [comment]
```go
package main

import(
	"fmt"
	"os"
	"time"
	"net/url"
	"crypto/tls"
	"github.com/syncthing/syncthing/lib/config"
	"github.com/syncthing/syncthing/lib/connections"
	"github.com/syncthing/syncthing/lib/protocol"
)

func main(){
	os.Setenv("GOTRACEBACK", "all")
	cfg := config.Wrap("foo", config.New(protocol.LocalDeviceID))
	d := connections.KCPDialer{}
	d.SetConfigs(cfg, &tls.Config{InsecureSkipVerify: true})
	u, _ := url.Parse("kcp://google.com:445")
	go func() {
		fmt.Println("Setup timer")
		time.Sleep(time.Minute)
		panic("foo")
	}()
	n := time.Now()
	c, err := d.Dial(protocol.LocalDeviceID, u)
	fmt.Printf("%#v %#v %s\n", c, err, time.Now().Sub(n))
}
```

gives

```
Setup timer
error at tls handshake
connections.internalConn{Conn:(*tls.Conn)(nil), connType:0, priority:0} &smux.timeoutError{} 10.0083167s
```

So it must get stuck somewhere before that, but having checked the code, all parts seem non-blocking.

**Comment by calmh** [comment]
I think it is when the other side does speak KCP, but they are not "in sync". That is, let two devices connect, restart one of them.

**Comment by calmh** [comment]
No repro on this from me for the moment. Give me a moment and I might remember how it came to be.
