### ISSUE TITLE
Sync with intermediary

### ISSUE THREAD

**Issue by vacore** [syncthing/syncthing#4077]
Feature request: sync with intermediary (always online shop, e.g. Google Drive, Dropbox).

Since my syncing computers not always on at the same time (e.g. home and work), have updated files from computer 1 upload at the always-on intermediary with subsequent deletion after syncing with target computer (as there's not much space those services provide for free for permanent storage).

**Comment by AudriusButkevicius** [comment]
Have something that is always online, that's the intermediary.
Or just use Google Drive or Dropbox which essentially delivers exactly the same features and act as an intermediary.

**Comment by vacore** [comment]
Oh thanks for the advice. I'd never figured out that myself. 

They don't deliver the same feature as files don't get deleted from media after syncronization, and free amount of storage would become cluttered in no time.

**Comment by calmh** [comment]
It wouldn't be impossible to invent a folder type "cache" that deleted files when it sees everyone else has them. But it's niche enough and far enough out of scope that I doubt it's going to happen - unless someone with the skills to accomplish it takes to the idea. So "closed, not going to happen" is the most honest state here I think. Sorry.
