### ISSUE TITLE
Can't disable the automatic usage report on Syncthing 0.9.8 for Android

### ISSUE THREAD

**Issue by maiaftv** [syncthing/syncthing#4078]
The uploaded version at F-Droid does not allow for opting out the automatic usage report. The program displays a message informing about the restart necessity and, after confirming, it comes back with the usage report ticked again.

How can I disable it?

**Comment by calmh** [comment]
Hi! This is unfortunately the wrong repository / issue tracker for your issue. Please file it in http://github.com/syncthing/syncthing-android/issues to get the correct attention.

**Comment by wweich** [comment]
Also dup of syncthing/syncthing-android#872 .

---

Also

> The uploaded version at F-Droid

We don't upload to F-Droid. F-Droid uses our code from GitHub to build the app themselves. And for some reason they used the wrong syncthing version.
