### ISSUE TITLE
Erroneous "folder has insufficient free space" error.

### ISSUE THREAD

**Issue by hyperloop512** [syncthing/syncthing#4079]
Hi,
Thanks for syncthing, which I am using with syncTrayzor.
One bug keeps cropping up: I keep getting the following erroneous lack of free space error. The error periodically clears itself and then it starts rescanning. This is fine, but annoying.

The big issue is that I have added a new folder with a lot of items (140,000, 500Gb) and it never reaches the end of the scan.  

2017-04-04 16:38:31: Folder "-----------": insufficient disk space in \\?\F:\Fred\Work\~$17 PHYS101 Oscillations question v1.docx: have 0.00 MiB, need 0.00 MiB

2017-04-04 16:54:19: Stopping folder "Papers and seminars" (---------) - folder has insufficient free space

and another, different directory:
[4F7O5] 17:34:32 WARNING: Stopping folder "mainly photos" (----) - folder has insufficient free space
[4F7O5] 17:34:32 INFO: Stopping folder "mainly photos" (----) mid-scan due to folder error: folder has insufficient free space
[4F7O5] 17:37:49 INFO: Folder "----" error is cleared, restarting

The system is an always on desktop. No hibernation / sleep.
The data drive (F:) has 2.5Tb free. (>50%).
Windows partition (C:) has 6.2Gb free of 223Gb (a bit low but still plenty).
Both drives NTFS.

What can I do to resolve this issue, or help find the root cause?

Thanks!

### Version Information

Syncthing Version: v0.14.25 & also v0.14.26
OS Version: Windows 7 x64.
Browser Version: (if applicable, for GUI issues)

**Comment by calmh** [comment]
The errors are odd indeed, but every scan progresses from 0% to 100%. It does not mean it's forgotten the info it's already scanned.

**Comment by hyperloop512** [comment]
Thanks - I just update my comment to reflect that!
But I would love to not have all these error messages all the time, and I suspect there may also be a lot of CPU overhead in restarting scans all the time (not good on my laptops).

Is there anything I can do to help debug - it seems others have had this issue before...

Thanks.

**Comment by calmh** [comment]
It seems like we sometimes get an incorrect free space value back from the OS. You can work around it by setting the required free space to zero, in the advanced folder options I think.

**Comment by AudriusButkevicius** [comment]
We should probably stay silent if total space is 0...

**Comment by calmh** [comment]
I think the syscall code in calmh/du is subtly broken nowadays, since Go 1.7+ at least, and possibly other places where we do Windows DLL calls or syscalls as well.

In https://github.com/calmh/du/blob/master/diskusage_windows.go#L16 the call to syscall.StringToUTF16Ptr(path) is converted to an uintptr, at which point the actual pointed-to data is no longer alive and may be garbage collected. Before the syscall completes. If that happens we may pass garbage or an all-zeroes string there and get back something unexpected. I'd have expected an error code, but ...

**Comment by canton7** [comment]
Apparently `runtime.KeepAlive` exists (since Go 1.7), which can be used to fix the issue.

**Comment by AudriusButkevicius** [comment]
I am sure the escape analysis should be clever enough to figure out that the pointer is going to a syscall?

**Comment by calmh** [comment]
It looks scary so I added some KeepAlive and a test... Which runs fine both before and after the change, so I don't know.

**Comment by canton7** [comment]
@AudriusButkevicius The .NET GC, in its infinite wisdom, still requires you to be careful about the GC grabbing objects you've taken pointers to, so I wouldn't be surprised if Golang was the same.

**Comment by calmh** [comment]
Mmhm. The issue here is that "uintptr" is an integer type, not a pointer type, and thus invisible to both gc and escape analysis. So from that point of view the old code created an array, took the pointer to it, threw the pointer away, then never again referred to it. So yeah, the conversions are dangerous and the Call method required great care - which is why it literally says "unsafe" on every line of that code. :)

But if it's the root cause of this issue I'm not sure.

**Comment by calmh** [comment]
@hyperloop512 just for fun you could test 0.14.27-rc.1 to prove or disprove our theories above. If you still see the issue, it was not caused by the thing I just "fixed". :)

**Comment by blindchimp** [comment]
I noticed this on an old win7 laptop... it happens regularly and after some poking around, I seems that some process is causing the swap file to become huge (or at least, indicating it wants to reserve the swap space by possible allocating a huge chunk of VM?). I suspected that windows was probably being conservative and indicating a "full disk" despite it only being reserved... I'm not sure if it is syncthing, or some other process causing the issue...

**Comment by hyperloop512** [comment]
Thanks guys! 
For non-techs like myself, how should I install it -- it is syncthing that is changed, and I am running Synctrayzor on Win64. I've downloaded the zip file, and found an exe file, but am not sure what to do next.
Cheers...

**Comment by canton7** [comment]
@hyperloop512 See [the README](https://github.com/canton7/synctrayzor#portable-1), but use 0.14.27-rc.1 instead of a "Beta version".

I should probably update those instructions, since we don't really do beta versions any more...

**Comment by calmh** [comment]
(We'll probably do 0.15-betas at some point.)

**Comment by calmh** [comment]
Since this is now in a released version, any change? Otherwise we will need more data if we're ever to solve it, I think.

**Comment by blindchimp** [comment]
I fired up my old win7-64/4GB machine (plenty of free disk space), updated syncthing (64bit 0.14.27), and let it sit for awhile and the same "insufficient disk" errors came up after awhile. So, no change there.

But, I noticed #4112 had been closed and that issue looked suspiciously similar...

I fiddled around and removed some programs I thought might be hogging memory (like crashplan) and things settled down (the "insufficient disk" errors stopped). But, I'm still seeing syncthing using a lot of memory on a rescan of a modest sized folder, especially after some files have changed in it. I noticed one thing that might be of interest: it appears to happen more with a folder that has ignore patterns. Here is look at the memory usage:
![small](https://cloud.githubusercontent.com/assets/122083/25729058/cc502788-30e7-11e7-997d-6bd3f89648db.png)

It fills all of physical memory (looks like 2.5gb+) and starts paging, then backs off. Doing a similar test with a folder with a similar number of files, etc. but with no ignore patterns doesn't exhibit the same memory usage spike. So, reducing VM pressure fixed spurious "insufficient disk" errors, but maybe #4112 isn't quite all the way resolved?

**Comment by calmh** [comment]
Did you hit "Override changes" and running 0.14.28-rc.1? Otherwise I don't see the relevance to #4112.

But regardless of that, it seems that the insufficient disk space errors were caused by disk space being reserved for paging - which is reasonable. :)

**Comment by blindchimp** [comment]
oops, sorry... I updated to 0.14.28-rc.1 and tried override-changes and everything worked fine, so ya no-relevance to #4112. Memory usage for the rescan situation mentioned above is the same, but that is closer to #4099, which I know is an ongoing project...
