### ISSUE TITLE
Buffer the device/folder rejected messages so the GUI gets them even when connecting later

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#4084]
When launching the GUI, Accept/Refuse new device or folder won't show immediately although many other infos are displayed.
Could it be possible to have the core to store such requests in RAM (until the source stops its request) and have them passed to the GUI on launch (or have the GUI on launch to question the core for such recent requests)?

**Comment by calmh** [comment]
Yes, we should probably do something about that.

**Comment by calmh** [comment]
One way to solve this today would be to set up a separate subscription for the relevant events only and have the GUI poll that.

**Comment by AudriusButkevicius** [comment]
This should probably be turned into a persisted in config thing to survive restarts and add free deduplication.

**Comment by calmh** [comment]
Maybe. The separate subscription mentioned above is implemented(-able) today though.

**Comment by AudriusButkevicius** [comment]
Sure, yet it does not deduplicate (which all the clients have to implement), nor is it persisted between restarts, which it probably should be.

**Comment by imsodin** [comment]
Fixed by #5084
