### ISSUE TITLE
error: file with empty block list

### ISSUE THREAD

**Issue by ndeelstra** [syncthing/syncthing#4089]
Hi,

We use syncthing and suddenly these messages appear:
[LHKRJ] 14:01:07 INFO: Connection to PYKABJ7 closed: protocol error: index update: "CUTS/_OAX/40306.wav.oax": file with empty block list

Any idea how to solve?

**Comment by AudriusButkevicius** [comment]
What client are you using on the other side? It's probably not a vanilla syncthing implementation?

**Comment by ndeelstra** [comment]
Hi,

No, it is Synctrazor. I thought SyncTrazor is just a GUI around SyyncThing?

Kind regards / Met vriendelijke groet / Mit freundlichen Grüssen /
Salutations,

Norbert Deelstra
Caliope Broadcast Software

Tel: +31 (0)20 365 21 86
Mob: +31 (0)6 22 97 31 57
SkypeID: info_caliope
www.caliope.eu

[image: Facebook] <https://www.facebook.com/CaliopeBroadcastSoftware/>
<https://twitter.com/CaliopeSoftware>
<https://www.linkedin.com/company/caliope>

**Comment by AudriusButkevicius** [comment]
Interesting. @calmh?

**Comment by calmh** [comment]
Database corruption or old bug, I guess. To solve, touch the file on the source side so that it gets rescanned - update the timestamp, or rename it, or something similar. :/

**Comment by ndeelstra** [comment]
I just tried it, but found at that the file was not present on the source.
Anything else I could try?
Is it possible to re-index all the files?

**Comment by calmh** [comment]
Even more interesting. I'd love to get a look at the index database on that computer if you would care to share it.

Not present means deleted, in which case an empty block list is exactly expected and should result in no complaint. So apparently the file is in some sort of odd limbo.

**Comment by ndeelstra** [comment]
Hi calmh,

I guess it is no problem to give you access, I will let you know the teamviewerID later on.

**Comment by AudriusButkevicius** [comment]
I don't think he needs access, just the index-* directory zipped up from syncthings home directory

**Comment by ndeelstra** [comment]
Well, the error seems to be gone now.
We upgraded both pc's to the latest version and all seems Ok now.
So, that's great!
I will let you know when it happens again.
If you still like the index database please let me know.

**Comment by calmh** [comment]
Got it another way, resolved by e3e028c9
