### ISSUE TITLE
Log is getting very big when autoUpgradeIntervalH is set to zero

### ISSUE THREAD

**Issue by tquakulinsky** [syncthing/syncthing#4090]
### Version Information

Syncthing Version: v0.14.27-rc.2
OS Version: Windows 7 (64bit)
Browser Version: No GUI issue

I noticed today that the syncthing.log in Syncthing’s home directory was getting very big (> 15GB). I could not open the log anymore. Because of that I stopped Syncthing, deleted the log and started Syncthing again. Now I could see that the following messages was repeated very very often:
[FCKL4] 09:47:49 INFO: Couldn't fetch release information: Get https://upgrades.syncthing.net/meta.json: dial tcp 46.101.130.230:443: connectex: Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzulässig.

A few weeks or months ago I disabled automatic upgrades by setting autoUpgradeIntervalH to zero. After I changed the value to 999999 and restarted Syncthing the problem was gone.

**Comment by calmh** [comment]
Oh. Yeah. This is a bug.
