### ISSUE TITLE
toggle 'pause' button multiple times on share, seems to confuse synthings

### ISSUE THREAD

**Issue by lkwg82** [syncthing/syncthing#4098]
**bug**: progress is reported different alternating, seems to start multiple scan jobs (?)

**steps**:
 - have a share, which needs to be scanned
 - pause, unpause, pause, unpause multiple times (see gif)

![syncthing-pause-bug](https://cloud.githubusercontent.com/assets/1891171/25033591/ab2365c4-20df-11e7-9624-b30b96ecc116.gif)

### Version Information

Syncthing Version: v0.14.26
OS Version:Linux (64 bit)
Browser Version: (chrome)

**Comment by calmh** [comment]
Yeah, this is #3965

**Comment by lkwg82** [comment]
did not find it, sry
