### ISSUE TITLE
Latest Change is not updated for files created locally

### ISSUE THREAD

**Issue by jonathancross** [syncthing/syncthing#4101]
### what happened

The "Latest Change" field in the browser GUI does not show files created / modified locally.

### what you expected to happen instead

Expected to see my new file listed under "Latest Change" after the rescan interval.

### steps to reproduce the problem

1. Create a file locally.
2. Look at specific folder info in the browser GUI.
3. The "Latest Change" item does not show the new file. ("Global Changes" works as expected)

### Version Information

Syncthing Version: `v0.14.25`
OS Version: `Mac OS X (64 bit)` and `Linux (64 bit)`
Browser Version: Chrome, Safari (not browser-specific)

-------------------

Seems that only downloaded files are listed under "Latest Change", even when local changes are more recent.

### why this matters

This is disconcerting in cases where user is waiting for an important file to be synced remotely.

![slow-download](https://cloud.githubusercontent.com/assets/5115470/25052917/9cedb78c-2154-11e7-9261-f287c0a909c9.jpeg)

**Comment by AudriusButkevicius** [comment]
It was called last remote change before but I think we renamed as it was too long. This is actually expected

**Comment by calmh** [comment]
Yeah.

> user is waiting for an important file to be synced remotely

You want to wait for th other device to appear as 100% in sync instead.

**Comment by calmh** [comment]
That image is 💯 though :D

**Comment by jonathancross** [comment]
Would it be safe to say this is the "Last Downloaded File" then?

**Comment by calmh** [comment]
I wonder if that isn't what we called it first, but that was confusing because it also shows things that were deleted.

**Comment by jonathancross** [comment]
Okay, yeah, just would be nice to find a label that captures what this field actually is.
How about "**Last Remote Sync**" which, by itself is a bit vague, but because the value is clearly a file, I think it would capture the meaning a bit better.

PS: If we can find a label that works, I'm happy to submit a PR.
