### ISSUE TITLE
Folders with missing path are not restarted by "Rescan all"

### ISSUE THREAD

**Issue by bigbear2nd** [syncthing/syncthing#4103]
Dear Team

Usecase:
I share a few larger, slow changing folders from inside a truecrypt container. I use a high rescan interval, because I use to work with the data and I dont want to sync before I am done. (work is ususally below 10 min, like copying pictures inside and renaming them.) I set the other side to "versioning" and I dont want copies of all that renaming on that side.
After mounting, I usually click "rescan all" to get them from stopped to alive.

what happend:
With the change from v0.14.26 to v0.14.27, the functionality of the "Rescan all" Button changed.
Before: 
Stopped Folders would be checked if they are "alive" again
Now:
Stopped Folders are skipped during the "Rescan all" function

Folders can only get "alive" again, if the rescan interval is due.

what you expected to happen instead:
Stopped Folders would be checked if they are "alive" again

any steps to reproduce the problem:
unmount a shared folder 
start Syncthing
rescan the folder > status is "Stopped"
mount folder again
press "Rescan all" or "Rescan" on the individual folder. (Same effect: No effect)

### Version Information

Syncthing Version: v0.14.27 (rc2 and rc3)
OS Version: Windows 7 
Browser Version: Using Syncthing Trazor
![grafik](https://cloud.githubusercontent.com/assets/7719800/25055715/cd515572-2164-11e7-9ad8-e838611cb9da.png)

**Comment by calmh** [comment]
I can't reproduce this on v0.14.27-rc.2. By removing the .stfolder file and rescanning I get:

![screen shot 2017-04-14 at 23 03 04](https://cloud.githubusercontent.com/assets/125426/25056033/ae90c224-2166-11e7-8466-949576291e9a.png)

By touching that file and clicking "Rescan all" it resumes:

![screen shot 2017-04-14 at 23 03 14](https://cloud.githubusercontent.com/assets/125426/25056039/b87de7d0-2166-11e7-9fc0-609a648bef78.png)

But you don't show the actual stopped reason in the GUI. Is something more than this going on on your side?

**Comment by bigbear2nd** [comment]
Yes, I think it has to do with starting Syncthing after removing the .stfolder

Removing the file if everything is ok, and then "readding" is also working for me.

Here the error message:
![grafik](https://cloud.githubusercontent.com/assets/7719800/25056365/aa013d90-2168-11e7-835e-656d34cbd751.png)

**Comment by bigbear2nd** [comment]
Interesting is also the log message:

Line 8:
"[xxxx] 23:15:45 INFO: Ready to synchronize "xxxxxxxoid" (xxxxxxxxpüüoizg) (readwrite)"

and then
(after the discover infos)
Line 13:
[xxxx] 23:15:45 WARNING: Stopping folder "xxxxroid" (xxxxxxxxpüüoizg) - folder path missing
[xxxx] 23:15:45 INFO: Skipping folder xxxxxxxxpüüoizg scan due to folder error: folder path missing

**Comment by bigbear2nd** [comment]
> Is something more than this going on on your side?

I have 13 devices (mostly only 3 of hem online) and 14 folder with 250k items in total 500 GB size on this machine

Or are your asking something else?

**Comment by calmh** [comment]
OK, reproduced & confirmed. If the folder is missing at startup, rescan does not revive it. In 0.14.26, this does work. We should fix this before releasing 0.14.27.

**Comment by calmh** [comment]
Bisect points to #3996 as the smoking gun

**Comment by calmh** [comment]
I'm doing a 0.14.27-rc.4 without #3996 in it as I think we need more time to clean this up. The blame here isn't on #3996 really as at it's just a symptom of that whole piece of the program being way too complex and having low test coverage. This is something I'm going to work on fixing during the next cycle.
