### ISSUE TITLE
Initial sync of mostly synchronized folder

### ISSUE THREAD

**Issue by alexforencich** [syncthing/syncthing#4108]
Syncthing appears to have issues when adding a new node that's already mostly synchronized.  

Example: a relatively large folder is shared between several computers (say, ~500k files and folders, ~100 GB in total).  Now, another computer needs to be added to this set.  To speed the process, the folder is 'sneaker netted' to the new machine (cp -rp via flash drive, external hard drive, rsync -avP over LAN, FedEx'd hard drive, etc.) and then the shared folder is added on syncthing.  However, between the initial copy and adding the folder to syncthing, a few files have been changed (~10 files, ~10 MB).  

Expectation: syncthing will scan the folder and detect that just about everything is already synced, transferring only a handful of files after synchronizing the network state.  

Actual result: syncthing will scan the folder and then try to sync just about all 500k / 100 GB of files, negating the time savings of the offline transfer.  

Note that if no files are changed between the the offline transfer and the initial scan in syncthing, syncthing will correctly detect that the folders are identical and only the network state will be transferred.

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
