### ISSUE TITLE
Accessibility issue on chrome

### ISSUE THREAD

**Issue by derekriemer** [syncthing/syncthing#4109]
I just filed https://bugs.chromium.org/p/chromium/issues/detail?id=713159
This affects Syncthing, because there is a heading inside the button. This causes chrome to think that the accessibility tree should be flattened, and therefore, the accordian no longer has sections marked with headings.

It is not necessarily necessary to have a button here at all for accessibility purposes, because aria-expanded can directly be put on a heading. This will cause a screen reader to report something like "heading level three collapsed my device 1." If this was a feature request in the past, or a user has requested buttons be placed on each element which is to be expanded and collapsed, it should be noted that the heading should probably be placed outside the button to prevent issues such as this. 
Thanks

**Comment by calmh** [comment]
Thanks for the heads up

**Comment by tomasz1986** [comment]
This has been fixed on the Chromium side, so I think that the issue can be closed, right?
