### ISSUE TITLE
Cannot Access Server Computers Syncthing Web interface from Client Computer

### ISSUE THREAD

**Issue by davidpgil** [syncthing/syncthing#4110]
Using "ssh -L 9090:127.0.0.1:8080 user@server" to try to access my servers web interface for Syncthing, I get the error on the server side saying "channel 3: open failed: connect failed: Connection refused".

I am expecting to be able to access the web interface for syncthing of my server on my client computer via "http://127.0.0.1:9090" , however this isn't working.

Any ideas on what may be going on? How can I make this function properly?

Syncthing Version: v0.14.26
OS Version: My client device is running MacOS Sierra and the Server is running Ubuntu 16.04.
Browser Version: Firefox (latest version)

**Comment by calmh** [comment]
Probably it's listening on port 8384 and not 8080, the documentation may be old. Please use the forum for further support.
