### ISSUE TITLE
"Cannot open database" when home dir is on a USB stick

### ISSUE THREAD

**Issue by hrvstr** [syncthing/syncthing#4113]
Hi, I am trying to move my Syncthing home dir to a **USB drive** to get the HDD to spin-down when there is no user activity.

1. The drive (32gb kingston) is formatted with `ext4` and mounted by `fstab` with the _defaults_ option. I can create folders and files on the USB drive and write permissions are set to `777` . The syncthing user is the owner of the drive.

2. I copied the syncthing folder `~/.config/syncthing` to `/media/usb/syncthing` and tried to run syncthing with the _-home=_ argument.

3. The database seems to be locked although i checked multiple times with htop that syncthing is not running and the service is stopped and disabled. When I run syncthing without the home flag and identical home-folder contents it runs just fine.

Any clues how I can get this to start on a USB drive?

```
❯ syncthing -home=/media/usb/syncthing -no-browser -no-restart
22:27:45 WARNING: chmod /media/usb/syncthing: operation not permitted
[ZUXOT] 22:27:45 INFO: syncthing v0.14.26 "Dysprosium Dragonfly" (go1.8 linux-arm) deb@build.syncthing.net 2017-03-23 11:04:35 UTC [noupgrade]
[ZUXOT] 22:27:45 INFO: My ID: ZUXOT7N-2QXO5V2-3AGIFZU-B7F3WFL-3R2CDVC-BR6WANB-5Z7EYTZ-PAT4WQT
[ZUXOT] 22:27:46 INFO: Single thread SHA256 performance is 7.0 MB/s using minio/sha256-simd (7.0 MB/s using crypto/sha256).
[ZUXOT] 22:27:49 INFO: Hashing performance with weak hash is 6.27 MB/s
[ZUXOT] 22:27:51 INFO: Hashing performance without weak hash is 6.77 MB/s
[ZUXOT] 22:27:51 INFO: Weak hash enabled, as it has an acceptable performance impact.
[ZUXOT] 22:27:51 FATAL: Cannot open database: open /media/usb/syncthing/index-v0.14.0.db/LOCK: permission denied - Is another copy of Syncthing already running?
```

```
❯ syncthing                                                   
[monitor] 22:28:01 INFO: Starting syncthing
[ZUXOT] 22:28:02 INFO: syncthing v0.14.26 "Dysprosium Dragonfly" (go1.8 linux-arm) deb@build.syncthing.net 2017-03-23 11:04:35 UTC [noupgrade]
[ZUXOT] 22:28:02 INFO: My ID: ZUXOT7N-2QXO5V2-3AGIFZU-B7F3WFL-3R2CDVC-BR6WANB-5Z7EYTZ-PAT4WQT
[ZUXOT] 22:28:03 INFO: Single thread SHA256 performance is 7.0 MB/s using crypto/sha256 (7.0 MB/s using minio/sha256-simd).
[ZUXOT] 22:28:05 INFO: Hashing performance with weak hash is 6.21 MB/s
[ZUXOT] 22:28:07 INFO: Hashing performance without weak hash is 6.72 MB/s
[ZUXOT] 22:28:07 INFO: Weak hash enabled, as it has an acceptable performance impact.
[ZUXOT] 22:28:08 INFO: Ready to synchronize "ACD" (XYZ) (readwrite)
```

### Version Information

Syncthing Version: v0.14.26, Linux (ARM)
OS Version: Debian Jessie (CleanOS for WD MyCloud Gen1 3TB)

**Comment by AudriusButkevicius** [comment]
I am closing this as this should live on the forum in the beginning until we prove a bug. To me this seems like the drive/OS implementation does not support flock syscall, but I suspect running syncthing via strace can answer this.

**Comment by hrvstr** [comment]
Okay, sorry for posting in the wrong place.

For the record I fixed it by wiping all config files from the USB and starting from scratch (get new api key, adding and scanning all folders). Somehow the database must have went corrupt while copying or I had wrong permissions.
