### ISSUE TITLE
Automatically ignore nested folders synced otherwise

### ISSUE THREAD

**Issue by devurandom** [syncthing/syncthing#4115]
It would be great if Syncthing would automatically ignore folders that are already being synced otherwise.

Assume following folder layout:
* `parent`
  - `child-1`
  - `child-2`

Assume I have selected to sync `parent` and `parent/child-2`.

It would be nice if `parent` would automatically add `/child-2` (but not `/child-1`) to its `.stignore` file to prevent loops.

Related: syncthing/syncthing#2491

**Comment by AudriusButkevicius** [comment]
I think this would be wrong, because I might have parent shared with device A and child 1 with device B, and I want device A to have child 1 content (as he has no access to child 1 otherwise)
