### ISSUE TITLE
Unable to run syncthing as a daemon

### ISSUE THREAD

**Issue by panditarevolution** [syncthing/syncthing#4121]
### Version Information

Syncthing Version: v0.14.27, Linux (64 bit)
OS Version: Fedora 25

I asked the same question a while ago on [Stackoverflow](https://stackoverflow.com/questions/42883757/how-to-run-an-app-as-a-daemon-with-systemd).

I'd like to run syncthing as a daemon, trying to follow [this hint here from the syncthing manual](https://docs.syncthing.net/users/faq.html#how-do-i-run-syncthing-as-a-daemon-process-on-linux).

I'm running on Fedora 25 and syncthing 0.14.24.

The executable is pointed to via a symlink in /usr/bin/syncthing which can be executed by any user (tested this successfully).

To enable the service, I'm typing (myuser is replaced with my actual username in all of the below):
`
sudo systemctl enable sycnthing@myuser.service`

Which returns:
`
Failed to lookup unit file state: Invalid argument
`

I don't understand what the error message means. How could I get to run syncthing as a daemon?

syncthing@myuser.service:

```
[Unit]
Description=Syncthing - Open Source Continuous File Synchronization for %I
Documentation=man:syncthing(1)
After=network.target
Wants=syncthing-inotify@myuser.service  # I also commented this line out; didn't have an effect

[Service]
User=%i
ExecStart=/usr/bin/syncthing -no-browser -no-restart -logflags=0
Restart=on-failure
SuccessExitStatus=3 4
RestartForceExitStatus=3 4

[Install]
WantedBy=multi-user.target
```

I'm struggling with sydtemd unit files for quite a while so perhaps I'm doing this simply wrong?

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.

**Comment by panditarevolution** [comment]
OK, will do. I did search the issue tracker for systemd but nothing showed up.
