### ISSUE TITLE
Warn against running as a privileged user

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4123]
We should generally not run as a privileged user. We can't suddenly make that an error as that would break a lot of installations. But we could add a warning with similar behavior as the already existing one for unprotected GUI access. With a similar advanced config to tone it down. 

Practically, detecting uid 0 is trivial. I don't know how to detect SYSTEM on Windows.

**Comment by canton7** [comment]
There are a bunch of well-known SIDs for special Windows users.

**Comment by canton7** [comment]
Maybe it's worth being extra-loud if the user hasn't set a GUI password, and slightly loud if they have?

**Comment by calmh** [comment]
Went with constant loudness to begin with.

**Comment by maelcum** [comment]
Is there a way to turn this off? On my two NAS'ses ( NASsi? NAS Devices!) there is no other user than root. So whenever I log in to the GUI I am reminded. No need for that.

**Comment by AudriusButkevicius** [comment]
Create new users

**Comment by calmh** [comment]
It's a one time notice per restart.
