### ISSUE TITLE
Alternative folder name

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#4124]
It be would useful to have an additional field in folder config whose purpose would be to distinguish local folder name. So Folders would have 2 names fields, one for local, and the other that would be sent to pairs as a proposed name to remote pair. If either one is left blank, then the other is proposed. If both are blank then ID only is sent as of today.
Case : suppose I create a personal folder to share with Audrius. As of today I'd create it as _Audrius_, and when he is notified he would need to change this name that means nothing to him, to let's say _Bugith_.
As a workaround, today I create the Folder share with name _Bugith_ (so that the name is significant to Aud and he just can accept it as is), then when he has accepted, I change back the name for me to _Audrius_ ... so that it means something ... to me :) .
The additional field could be labelled "Remote name", could be left blank, and if non-blank its content would be proposed to pairs instead of current Folder Label as of today.

**Comment by AudriusButkevicius** [comment]
Adding a field permanently cluttering the UI versus  having to rename something once just does not add up. We didn't have any names at all and people survived so I think we are now crossing the line.
Alternatively you should be more inventive with your names.

**Comment by bugith** [comment]
I walked around this since I use ST, and I can say imagination is not the point here when it comes with a **general purpose** folder share between 2 devices : a label like DevID1-DevID2 would do job just more than the simple folderID, but having my folders list filled of list like
guy1-me
guy2-me
guy4-me
me-guy3
is just borring (although **I can** easily rename me-guy3 to guy3-me), not mainly for me, but over all for new users like guy5 that would receive "me wanna share guy5-me, OK?" which will end in a puzzled new user. OK, let's invite him to rtfm, but that isn't that friendly welcome.
To overcome this, **I have** to label the new share e.g. as _me-guy5_, and you'll agree I can't leave it as is on the long run (see list above) : **I have** to rename it some day to have a consistent looking list, and I'm not a newb user, and this is additional burden.  
When I proposed this, I had in mind the same kind of mechanism of this seldom used field one finds in mailers account settings that is called Reply address.
As you say, maybe we're crossing the line of unuseful gadgets, in fact I just did a little search in open/closed tickets and I must admit I didn't find such a request... that's why I posted.
Bye Aud-closed-this ;-)

**Comment by calmh** [comment]
The ID doesn't have to be random though. You can set the ID to "alice-and-bob" and the name to "Shared with Alice". Of course, if Alice gets the share request thing in the GUI she'll see both, but can twig on "alice-and-bob" and rename it to "Shared with Bob" when adding...

**Comment by bugith** [comment]
I know that calm. I posted this just to let devs know this need to twig can be ... let's say not optimal. Using the ID like before you introduced folderLabel won't remove the need for this twig on the Label when needed, mostly on new folder notification.
Please don't hurry to take this as a feature request. Instead, keep it <s>under the elbow</s> at hand for one day you fall/feel in terrifying idleness ;-)
Cheers
