### ISSUE TITLE
Path assistant in Windows should not be case sensitive

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#4126]
v0.14.27 FF38 windows 32bits / FF52 win64
The path assistant on folder creation is case sensitive so that it won't trigger warnings for Parent/Children of existing share. More it won't assist at all when one starts **typing** some path with c:\ or d:\ like it does on ~ followed either with arrows keys or typing matching head of path.

**Comment by AudriusButkevicius** [comment]
This is a duplicate of an issue that already exists I think.

**Comment by bugith** [comment]
Sorry for the noise

**Comment by uok** [comment]
see #1347
