### ISSUE TITLE
Theme change results in "Decoding posted config: unexpected EOF"

### ISSUE THREAD

**Issue by seb-1204** [syncthing/syncthing#4127]
Running Syncthing v0.14.27, Windows (64 bit) on Windows 7 I tried to change the GUI theme to Black.

Syncthing seems to restrart / the browser windows reloads and then shows the message (Notice)

`2017-05-03 13:07:27: Decoding posted config: unexpected EOF `

I can only click OK.
The theme does not change.

See also [in this forum thread](https://forum.syncthing.net/t/error-when-changing-theme/8091)

### Version Information
Syncthing v0.14.27, Windows (64 bit)
Internet Explorer 11

**Comment by calmh** [comment]
For what it's worth, I could reproduce this once (the first time) when testing now. Reloading and trying again worked. So something is odd, perhaps with keeping state in the GUI somewhere.

**Comment by AudriusButkevicius** [comment]
I think it's us restarting the api service midway through request. I raised this a while a go but it got closed as we couldn't repro.

**Comment by calmh** [comment]
Ah, yes, I remember your cryptic ticket or something and didn't understand the issue. But that doesn't explain why the change doesn't "take"...

**Comment by AudriusButkevicius** [comment]
I think we navigate away from the page (full refresh to pickup the theme) and the ajax request that is in flight gets axed by the browser.

**Comment by calmh** [comment]
Ah, of course. I can fix that.
