### ISSUE TITLE
Implement fast and reliable directory monitoring on Windows

### ISSUE THREAD

**Issue by baremetaldude** [syncthing/syncthing#4131]
The only right way to reliable monitor FS changes on Windows in notebook-friendly way is to write kernel-mode FS filter which log FS-level activity on monitored directories to file/named pipe even when syncthing not running. Syncthing then use it to replay logged actions. Also this replay file can be useful for testing.

**Comment by calmh** [comment]
There is an in progress pull request for fs notifications and other tickets on this in the system.
