### ISSUE TITLE
Large negative CPU utilization at startup (win7 64)

### ISSUE THREAD

**Issue by blindchimp** [syncthing/syncthing#4133]
- what happened
On initial startup, a large negative cpu utilization is displayed. It tends towards 0 and eventually corrects itself.

 - what you expected to happen instead
Non-negative CPU utilization

 - any steps to reproduce the problem.
Just start syncthing and watch it. It happens every time.

![screenshot 2017-05-05 06 10 53](https://cloud.githubusercontent.com/assets/122083/25747996/58116004-315e-11e7-8328-b14245a3d94c.png)

### Version Information

Syncthing Version: 0.14.28-rc.1
OS Version: Windows 7/64
Browser Version: chrome 58.0

**Comment by calmh** [comment]
Huh.

**Comment by calmh** [comment]
Thanks for noticing!
