### ISSUE TITLE
Request in unshared folder when paused on one side

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#4136]
I have no idea how I managed to produce this error in real usage, but it is easily reproducible:

1. Pause folder on instance A.
2. Add a big enough file into the folder on another instance B. Big enough as in you can do steps 4 to 5 before the file is finished syncing..
3. Scan folder on B and make sure it has finished.
4. Unpause folder on A and wait for index exchange to finish (i.e. sync starts).
5. Pause folder on B.
6. Wait.

Actual result:
Errors like
`May  7 07:52:45 homeserver syncthing[12224]: [BPDFD] WARNING: Request from [...] for file [...] in unshared folder [...]`
start appearing on device B.

Expected result:
At least don't complain that loudly and incorrectly about this non-erroneous situation. Ideally B should somehow tell A that the folder is paused, such that it can stop trying to get updates (or delay the next try).

**Comment by AudriusButkevicius** [comment]
I think this is #3906

**Comment by AudriusButkevicius** [comment]
Closing this, as I think it's a dup of the above.

**Comment by calmh** [comment]
I'm not convinced, especially I don't really think we are "leaking state" as much as just keeping one piece of state and having potentially race conditions in which actual connection it refers to... Nonetheless this sounds like a reasonable reproducer, but it's still linked to from #3906 so I guess that's fine.
