### ISSUE TITLE
Use a real login screen + sessions instead of HTTP basic auth

### ISSUE THREAD

**Issue by erikhagemeijer** [syncthing/syncthing#4137]
I would like to suggest to change the http login prompt with a form, so that I can use a password manager. 

I'm using 1Password which can't fill in login prompts.

**Comment by AudriusButkevicius** [comment]
You can bookmark urls with the username and password embedded.

**Comment by calmh** [comment]
That leaves the password in unprotected storage though.

**Comment by Ferroin** [comment]
If this gets implemented, it would be rather nice if it were optional.  The current basic authentication makes it really easy to punt authentication upstream when proxying Syncthing, which is particularly useful in some cases.

**Comment by canton7** [comment]
You can use the API key to authenticate, if that also fits your use-case.

**Comment by calmh** [comment]
Mmm. But I think we would still have to accept basic auth credentials for compatibility reasons. Possibly, in the long run, limiting it to localhost-bound or https.

**Comment by f5Qz** [comment]
I would like to see a real login page too!

**Comment by AudriusButkevicius** [comment]
Please refrain from "me too" comments as they add no value. You can use tye emote icons on the original post if you can't contain yourself.

**Comment by pjlewisuk** [comment]
What's the status of this feature request at the moment?
It would be really good to provide form-based login as well as HTTP basic auth, similar to how apps like sonarr/radarr allow this.

**Comment by AudriusButkevicius** [comment]
It's the same status as it wad 2 years ago, which is "sure, but we're not bothered about it, if you are, open PRs"

**Comment by STaRDoGG** [comment]
^--- this guy .... *eye roll*

**Comment by jdknox** [comment]
As a workaround, we can use a web extension that has partially solved this problem.  Bitwarden claims it can log automatically given you have only account on your localhost domain: https://github.com/bitwarden/clients/issues/116#issuecomment-327991012

I couldn't get it to work exactly as advertised, but it still lets me copy and paste the password from the extension without blocking the UI.

Other extensions exist, but I haven't tested them (e.g., passman and passifox).

**Comment by Sesshoumaru-sama** [comment]
A regular login page would really help. Login with that popup is really a distraction....
