### ISSUE TITLE
Bug in display width of global changes modal

### ISSUE THREAD

**Issue by samdmarshall** [syncthing/syncthing#4138]
This seems tangentially related to #3895 but causes a display/usability bug. Screenshot attached, should be obvious as to what the problem is: when the text in the item path column is unusually long, it causes the time modified column to be pushed off the edge of the modal window that is displayed when viewing the global changes list.

<img width="950" alt="screen shot 2017-05-09 at 09 19 27" src="https://cloud.githubusercontent.com/assets/1087718/25853032/59dad7b0-3499-11e7-98dc-f6d3f046f4f6.png">
  

### Version Information

Syncthing Version: `syncthing v0.14.27 "Dysprosium Dragonfly" (go1.8.1 darwin-amd64) brew@Sierra-2.local 2017-04-15 07:38:23 UTC [noupgrade]`
OS Version: `Mac OS X, 10.12.4 (16E195)`
Browser Version: `Safari Version 10.1 (12603.1.30.0.34)`

**Comment by AudriusButkevicius** [comment]
Seems like a dup of the same issue?

**Comment by samdmarshall** [comment]
I don't think so, the issue i mentioned is talking about the date being split into 4 lines, whereas my issue has it overflow the side of the modal.

**Comment by AudriusButkevicius** [comment]
Well I think the cause is the same

**Comment by wweich** [comment]
Jep, same cause. Your paths are just longer so even with 4 lines, there is not enough space, so the table is wider than the model.

**Comment by samdmarshall** [comment]
I see, should the original report be changed from an "enhancement" to "bug" as this causes a visual display issue?

**Comment by calmh** [comment]
Yeah. Reclassified.

**Comment by samdmarshall** [comment]
Cool, thanks!
