### ISSUE TITLE
Software Architecture Document

### ISSUE THREAD

**Issue by nov1n** [syncthing/syncthing#4141]
Hey there!

We ([@lidiagarces](https://github.com/lidiafgarces), @sacheendra, @jayachithra and I) did an analysis of Syncthing for our Software Architecture course at Delft University of Technology. It is available [here](https://delftswa.gitbooks.io/desosa-2017/content/syncthing/chapter.html) and may be of interest to some of you. It was a pleasure writing about and contributing to such an elegant system, best of luck to all contributors!

Cheers!

**Comment by AudriusButkevicius** [comment]
https://forum.syncthing.net/t/interesting-third-party-look-at-syncthing-by-delft-students-on-software-architecture
