### ISSUE TITLE
automatically add new devices

### ISSUE THREAD

**Issue by dipenpatel235** [syncthing/syncthing#4142]
hello ..
in past you have given info using introducer you  automatically add new devices.
i have try to understand but not understand or something wrong .
so can you please help me as per my below structure ?

i have setup syncthing on centos 7 server and it is work as server.
now i provide my all user to my server device ID
then they will add that device ID in its syncthing software.
Now I get request in server syncthing so instead of that i want to auto add thoes all requested user with default folder.
So what steps i need to do ?

Thanks

### Version Information

Syncthing Version: v0.14.27
OS Version: Centos 7

**Comment by canton7** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread.
