### ISSUE TITLE
Missing slash between folder path and file path in "failed items" dialog

### ISSUE THREAD

**Issue by johze** [syncthing/syncthing#4143]
I am getting the following error when trying to sync certain files: 

Error:  The following items could not be synchronized. They are retried automatically and will be synced when the error is resolved.

When I look at the folder path it shows it with a missing slash between the sync directory and the remaining path.

Path should be:  
F:\Creative\0 Portfolio 2017\2017_portfolio_march\hush hush x \IMG_20150430_135405103.jpg	

Path displayed:  
F:\Creative\0 Portfolio 20172017_portfolio_march\hush hush x \IMG_20150430_135405103.jpg	

Note; I think the failure has to do with the file name rather than the missing slash, it seems to work when I fix the file name, however the missing slash gave me a hiccup. I saw someone else had posted about this bug recently and not reported it.

**Comment by nrm21** [comment]
Unable to duplicate myself.  I created a blank file of same path (cept using C: instead since I dont have F drive on my test machine).  I also put a space after "hush hush x" since it looks like that folder name ends in space.  And it synced right away.

**Comment by calmh** [comment]
Names on Windows can't end in space, so that's the cause of the sync failure. The bug here is just the missing slash between the folder path and the file path, in the GUI dialog.

**Comment by hhycon** [comment]
> Names on Windows can't end in space, so that's the cause of the sync failure. 

Have a similar error, but no space in filename and the file was synced successfully.
After a rename the error is was gone and another rename to original name, still no error.
So can't duplicate it again, too 

C:\Users\x\MAscreenshots\mkdir_dif.PNG
which should be
C:\Users\x\MA\screenshots\mkdir_dif.PNG
