### ISSUE TITLE
symlinksEnabled = false: symlinks are still syncing

### ISSUE THREAD

**Issue by jdcapa** [syncthing/syncthing#4144]
For my setup I did *not* want syncthing to sync symlinks. After some searching I found some advise that symlinks can be disabled through the GUI via:
Actions -> Advanced -> Options -> symlinksEnabled

Unfortunately, this option doesn't exist any more.
I then manually added
`<symlinksEnabled>false</symlinksEnabled>`
to the configuration/options in ~/.config/syncthing/config.xml.

After restarting the syncthing services on both the server and client, symlinks were still synced.

### Version Information
Syncthing Version:Syncthing v0.14.27, Linux (64 bit) "Dysprosium Dragonfly"
Server: Arch Linux 4.9.24-1-lts
Client: Linux Mint 4.8.0-51-generic
Browser: Firefox 53.0.2 (64-bit)

**Comment by calmh** [comment]
There is no symlinksEnabled option any more. Symlinks are always synced, just like files and directories.
