### ISSUE TITLE
Index database should not be stored in ~/.config directory

### ISSUE THREAD

**Issue by guillaume-uH57J9** [syncthing/syncthing#4147]
What happened: I looked into the content of ~/.config/syncthing and saw a large database named index-v0.14.0.db

What you expected to happen instead: I expected to only see configurations files in ~/.config/syncthing, and database file(s) stored elsewhere. 

The correct location for a user database probably is ~/.local/share/syncthing, unless this is non-essential data (ie some cache that can be silently regenerated if deleted) in which case it would be ~/.cache/syncthing

### Reference documents

>  $XDG_DATA_HOME defines the base directory relative to which user specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.
> 
> $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used. 

>  $XDG_CACHE_HOME defines the base directory relative to which user specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used. 

[XDG Base Directory Specification](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html)

### Version Information
Syncthing Version: v0.14.27
OS Version: Debian jessie 64/bit

**Comment by wweich** [comment]
This was discussed in the past on the [forums](https://forum.syncthing.net/t/syncthing-and-xdg-base-directory-specification/2023?u=wweich), but nobody cared enough to implement it.

Also bare in mind that changing it now will introduce problems for third party wrappers and such, as the command line flag or env var used to place the config and index db somewhere else won't work anymore.

**Comment by guillaume-uH57J9** [comment]
Interesting forum discussion. 

This XDG specification helps for instance with backups/migration, you can save time if non-essencial data is neatly placed in ~/.cache so you can exclude it. 
It also keeps your $HOME directory a little cleaner since it avoids having each application create is own ~/.app directory at the root of your $HOME. 

I understand nobody may care about this specification, since not following it doesn't cause any big issue. 

This should be considered next time there's a breaking change related to the index database. If that database gets renamed/moved, might as well move it to the right place (probably ~/.local/share).

**Comment by calmh** [comment]
I think using `~/.config/syncthing` instead of just `~/.syncthing` on unixes was the initial mistake. The XDG specification is not really *for* things like Syncthing config and databases, but about where to place things like menu items and autostart  triggers. This summarizes it somewhat nicely I think: https://lists.debian.org/debian-user/2014/11/msg01817.html

As it is, I don't see us splitting up the contents of the config dir into multiple locations. You can of course use the various flags and environment variables available to move the location of the entire config dir as you please.

**Comment by guillaume-uH57J9** [comment]
Thanks for the clarification, I assumed the XDG Base Directory Specification was aimed at developer, but it seems I was mistaken.
