### ISSUE TITLE
json: cannot unmarshal array into Go struct field VersioningConfiguration.params of type 

### ISSUE THREAD

**Issue by dipenpatel235** [syncthing/syncthing#4152]
Hello.
i am tring to GET and POST config from PHP using below steps

1. using GET method store json responce in "$response" variable  https://my.host.com:8384/rest/system/config
2. then trying to decode json using below syntax and store into $json variable
$json = json_decode($response, true);

3. now just same decoded $json variable again encoding using below syntax without any change in decoded variable
$json_string = json_encode($json);

Now when i am post $json_string data using POST method so getting below error
https://my.host.com:8384/rest/system/config

ERROR:
json: cannot unmarshal array into Go struct field VersioningConfiguration.params of type map[string]string

### Version Information

Syncthing Version: v0.14.27, Linux (64 bit)
OS Version: Centos 7

**Comment by calmh** [comment]
You are sending a JSON array to a part of the config that expects an object. Please refer to https://docs.syncthing.net/rest/system-config-get.html (although versioning isn't very well specified there) and follow up with any questions on the forum please, as I don't think this is a bug.
