### ISSUE TITLE
local folder sync

### ISSUE THREAD

**Issue by jlmalet** [syncthing/syncthing#4153]
Hi!
thanks for writing syncthing
I would like to use it to sync two local folders (ie a usb attached drive and a local folder) however there is no option to connect to the same host... 
would be nice to allow it (rsync allow it, but rsync can't efficiently sync huge drives since it need to parse all files before beginning actual file synchronisation)
thanks and regards

**Comment by AudriusButkevicius** [comment]
This was brought up before and I believe it was deemed out of scope of syncthing. There are tools that do that already such as csync and unison.
