### ISSUE TITLE
unable to compile syncthing (core) 0.14.28 with go 1.6

### ISSUE THREAD

**Issue by decathorpe** [syncthing/syncthing#4154]
syncthing 0.14.28 introduces code that can't be built with go 1.6. The following error occurs:

```
+ go run build.go -no-upgrade build syncthing
WORK=/tmp/go-build095818036
cmd/syncthing/usage_report.go:11:2: cannot find package "context" in any of:
	/usr/lib/golang/src/context (from $GOROOT)
	/builddir/build/BUILD/syncthing/_build/src/context (from $GOPATH)
	/usr/share/gocode/src/context
```

The [Go 1.7 Release Notes](https://golang.org/doc/go1.7#context) mention what might be the cause of the issue:
> Go 1.7 moves the golang.org/x/net/context package into the standard library as context.

The new import style for the "context" package is used unconditionally, even though it's not available as "context" prior to go 1.7 (but as "golang.org/x/net/context").

**Comment by wweich** [comment]
We only support building with the latest stable version of Go. See the dev guide: https://docs.syncthing.net/dev/building.html

**Comment by AudriusButkevicius** [comment]
Firstly, these type of questions should go on the forum, as it's not actually a bug or feature and was most likely done with intention. Secondly we've spent significant effort documenting everything and trying to have good useful docs. 
Given this question could have been answered by them, going forward please check the docs first

**Comment by decathorpe** [comment]
I understand that it's not "officially supported".
Nonetheless, building syncthing with go 1.6 worked fine up to (and including) the 0.14.27 release, and bumping the "effective" compiler requirement from go 1.6 to 1.7 (or, officially, even to 1.8) between **stable bugfix releases** only seems like bad practice.
That's why I reported this here as a bug - because I thought the dependency bump was the unintended result of an oversight during development.

**Comment by AudriusButkevicius** [comment]
That's true, yet our version still starts with a 0, which sadly means we can do breaking changes out of cycle. I agree it's not ideal. Also, there might have been security fixes that the older versions did not receive, so being on the bleeding edge usually works for everyone's benefit.

**Comment by calmh** [comment]
In this case, intentional. We switched the minimum required compiler to 1.7 a couple of months ago, among other things to be able to use `context`: https://forum.syncthing.net/t/minimum-supported-go-compiler-is-now-1-7/9361

**Comment by decathorpe** [comment]
Fair point.

Still, this means that I won't be able to provide syncthing packages for EPEL7 and fedora 24 anymore.

**Comment by AudriusButkevicius** [comment]
Is there a reason the toolchain is so old EPEL7? Could you not compile a newer toolchain using the existing toolchain?

**Comment by decathorpe** [comment]
RHEL7 stuff is a bit dated sometimes, but I can't do anything about that.

Building a newer go compiler for my syncthing package builds is beyond what I am able (or willing) to do to support EPEL7 packages (beside the fact that it might cause incompatibilities with other packages). On the other hand, fedora 24 isn't a big problem, since it will be EOL in a few months anyway.

Maybe the go stack on RHEL7 will get updated at some point.

**Comment by lkwg82** [comment]
Just for my understanding: do you need to compile on a provided infrastructure with a given set of tools or dont you have a go compiler on ur machine?

**Comment by decathorpe** [comment]
I'm building "proper" RPM packages for fedora (and EPEL for RHEL7) - which means I have to build the packages from source and can't use the provided pre-built binaries (for legal, security, etc. reasons).

So, when building a package for a particular distribution, I MUST use the appropriate build infrastructure (package builds are done in a container) AND I can only use the packages that are made available by that distribution (since they run isolated from the host system, and in fact, without internet access). In this case, I can only use a go 1.6 compiler for building "proper" syncthing packages, since that is the latest version of the go compiler that is available in fedora 24 and RHEL7 build environments.

And just for the record, I have go 1.8.1 on my machine (as that's what is shipped with fedora 26 alpha). But that is irrelevant here, because - for the same reasons as above - I can't just build the binary on my system and package it up for older distributions.

**Comment by AudriusButkevicius** [comment]
Can you not build go 1.8 as part of the syncthing build process offline?

**Comment by calmh** [comment]
Yes, this is unfortunate, but such is often life with distributions. Debian stable ships Go 1.3.3... Go has a relatively quick development pace.

**Comment by piotr-dobrogost** [comment]
> Can you not build go 1.8 as part of the syncthing build process offline?

I think this was already answered:

> Building a newer go compiler for my syncthing package builds is beyond what I am able (or willing) to do to support EPEL7 packages (beside the fact that it might cause incompatibilities with other packages).

**Comment by calmh** [comment]
Indeed. Lets move any general discussion of development and distribution practices to the forum instead of the bug tracker, please.

**Comment by calmh** [comment]
@decathorpe for what it's wort, I just built using Go 1.6 by just

`sed -i 's/"context"/"golang.org\/x\/net\/context"/' cmd/syncthing/*.go lib/*/*.go`

(while trying to build with gccgo for an unrelated experiment)

**Comment by decathorpe** [comment]
That works! Thank you for sharing!

**Comment by h1z1** [comment]
@decathorpe thanks for opening this, I was going nuts trying to compile it.   Fact is while Go may be at 1.9.facebookLatestInternal, it's _not_ anywhere near that in distros.     From an end user, hell even developer perspective there is NOTHING warning about Go versions.  Breaking backward compatibility in such a bizarre manner is asinine.

**Comment by ProactiveServices** [comment]
@h1z1 This bug is closed and it has been stated several times that the forum is the place for discussion, not a bug report. You'll also find that insulting the developers will curry you no favour; please keep discourse civil.

**Comment by calmh** [comment]
![img_0169](https://user-images.githubusercontent.com/125426/28544804-d49f9d8e-70c4-11e7-93cb-9bdf6a9524cb.PNG)
