### ISSUE TITLE
Web interface keeps opening (Mac)

### ISSUE THREAD

**Issue by kenthinson** [syncthing/syncthing#4156]
Hello. I followed the information here on how to install synching on the Mac.
https://forum.syncthing.net/t/keeping-syncthing-running-mac-os-x-launchdaemon/407
The problem I'm having is the web interface keeps opening on it's own. Very annoying when I'm in the middle of typing something. Can anyone help me figure out whats going on? thanks!

**Comment by calmh** [comment]
That thread even discusses it: uncheck "Start browser" in settings. (And use the forum for support, not the bug tracker, please.)
