### ISSUE TITLE
Show "nearby devices" in add device dialog

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing#4157]
Please add an option to easily share publicly across my network subnet and search my network subnet for these Syncthing shares.
This would make rapid deployment much more possible and effective in both a business or homegroup setting.

**Comment by calmh** [comment]
"Publicly" is probably never going to be a thing in Syncthing, for philosophical reasons. Some sort of quicker centralized deployment (for use in businesses etc) might be a thing.

**Comment by AudriusButkevicius** [comment]
This goes again syncthings security model where things have to be acknowledged​ and agreed by both sides. I don't think syncthing will ever support the concept of anything public.

**Comment by imsodin** [comment]
The philosophy point is clear, so sorry for flogging an already dead horse:
I think the suggestion is not to automatically add other devices, but to broadcast some kind of "I am here" message, resulting in every other instance hearing this to prompt the user whether he wants to accept this device or not.

**Comment by AudriusButkevicius** [comment]
I think we do that already, or used to do that, as you add a device it suggests the device ids that are on the local network. I don't think "I'm here" prompts would work in a corporate/university environment where there are potentially multiple users you are unaware off.

**Comment by calmh** [comment]
Yeah it's browser dependent but the discovery broadcasts serve this purpose and the "add device" dialog will autocomplete device ids with that knowledge. But it's not especially discoverable.

**Comment by calmh** [comment]
If that is the issue here, we should probably just be clearer in that dialog. Show the list of detected but not added devices explicitly, allowing click to add or something.

**Comment by AudriusButkevicius** [comment]
"nearby devices"

**Comment by imsodin** [comment]
Cool, I didn't know about that feature - I would wager to guess neither do most other users. In a quick look at the documentation I didn't find this feature either. So making this easier to discover and/or documenting it would certainly be nice, as it is definitely a useful feature (meaning I can start spying on my colleagues :D ).

**Comment by canton7** [comment]
That's really nice, but I'm another person who was completely unaware of this!

**Comment by calmh** [comment]
Yeah, so clearly that's crap and we should fix that. I'm just waiting for OP to chime in with "exactly, that's what I mean" (so we can clarify the issue) or "no dudes, I'm saying you need public shares" or whatever.

**Comment by jebeld17** [comment]
@imsodin you're right. 
(Sorry folks I can't respond any more right now, I'm driving 🚘)

**Comment by jebeld17** [comment]
PS: How is it a security problem if a feature like this would be an optional feature disabled by default? And I'm not looking to automatically add devices... I'm looking to automatically find devices that are publicly saying the same "I'm here" message.

**Comment by calmh** [comment]
Retitling for clarity

**Comment by jebeld17** [comment]
Has anyone seen this implemented yet? Just curious. :(

**Comment by imsodin** [comment]
> Has anyone seen this implemented yet? Just curious. :(

Yes? The commit implementing this is linked just above your post and the feature also made it into the latest stable release ([v0.14.32](https://github.com/syncthing/syncthing/releases/tag/v0.14.32)).

**Comment by AudriusButkevicius** [comment]
It depends on the definition of "this". We implemented what we interpreted would be useful from your ticket, not necessarily what you expected.
