### ISSUE TITLE
syncthing + syncthing-android, stuck on blue "100%", android CPU on 100% permanently

### ISSUE THREAD

**Issue by Apfelgriebs** [syncthing/syncthing#4159]
**Issue**: Synchronizing between desktop and syncthing-android.
On the computer, the Android device in the "Remote Devices" section stays at a blue "Syncing (100%)". 
On the smartphone, the "Remote Devices" section lists a green "Up to date". On the smartphone, syncthing-android permanently uses a CPU core with 100%, causing the device to heat up and drain battery. On the PC, syncthing does not take any relevant CPU usage.
As far as I see, the actual syncing of all files in the folder is working without errors.
Removing and re-adding folders, devices and removal and re-installation of syncthing-android doesn't solve the problem.

On the android device, one specific folder is often (but not always!) permanently displayed as "Syncing (100%". However, the "Remove Devices" are listed as "Up to date". 

**Expected behavior**: No permanent "Syncing 100% on any device, no excessive CPU usage

**Steps to reproduce the problem**: Use syncthing and syncthing-android.

### Version Information

Syncthing Version: desktop (v0.14.29-rc.1, Linux 64 bit)
OS Version: Ubuntu 17.04

Syncthing-android version: (v0.14.26, latest version via F-Droid Repo)
Android version: 5.1.1
### Screenshot

![screenshot-localhost 8080 2017-05-19 15-30-45](https://cloud.githubusercontent.com/assets/28807937/26249821/46876ffe-3ca8-11e7-8caa-f1a260ffad78.png)

![screenshot_2017-05-19-15-36-50](https://cloud.githubusercontent.com/assets/28807937/26250122/5a6f2100-3ca9-11e7-8371-2f80a60f36e0.png)
![screenshot_2017-05-19-15-36-59](https://cloud.githubusercontent.com/assets/28807937/26250121/5a648bdc-3ca9-11e7-958c-deecca2066ec.png)

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.

**Comment by allefeld** [comment]
@AudriusButkevicius I don't understand why you would claim that this (and the related #1443) is not a bug. There is clearly something happening that shouldn't happen, and there is no indication that it is related to a user mistake.

In any case, the same occurs for me, too, all the time, while syncing between two Linux machines. Under "Remote devices" it says "Syncing (100% ...)" for a long time, the same on both sides. Both machines are online and connected, and there are no unsynchronizable items. Syncthing version on both machines is v0.14.36.

Please fix this? I'm happy to provide any additional information the developers might need.

**Comment by Apfelgriebs** [comment]
@allefeld 

In my case, removing and re-creating the folders (and remote devices) in syncthing didn't solve the problem. However, when I moved the folders content into a new folder on one machine and deleted it on the others and tried syncing this, it worked. Filesystem on all machines is ext4.

I have no idea how this actually solved anything, but so far the issue didn't occur again.

IMHO syncthing should at least tell the user what file (it suspects) is causing the incomplete sync.

**Comment by AudriusButkevicius** [comment]
What you suggested doesn't explain the problem, and could still be due to user error (ignores, unidirectionally shared folders etc etc), until we have a concrete reproducer, there is nothing to fix.
