### ISSUE TITLE
Make Syncthing portable

### ISSUE THREAD

**Issue by arneko** [syncthing/syncthing#416]
Hi there,
I love how well Syncthing works so far. This is a feature request, that should (?) be fairly simple to integrate:

It would be cool if Syncthing would look for config files in the directory it's running from first and then ideally accept relative paths (not sure if that requires any modification), so that you could put it on a thumb-drive and run it from any computer, thereby updating a shared folder, or creating a backup of said drive. This is working nicely in my head. Don't know if there are any issues to be expected though...

Keep up the great work!

**Comment by heX16** [comment]
Just for information.
I use this bat file for portable start:

    @echo off
    %~d0
    cd "%~d0%~p0"
    IF %ERRORLEVEL%==0 GOTO PATH_IS_OK
    exit
    :PATH_IS_OK

    rem set AppData=D:\Data\syncthing\
    set AppData=%~d0%~p0
    set LocalAppData=%AppData%
    start "syncthing" /B /LOW syncthing.exe

**Comment by AceXare** [comment]
I used this on my USB Stick wherever i go, but on the work I am using Linux.
Is it possible for Linux to run portable, too?

**Comment by rumpelsepp** [comment]
You can just start the binary. But please switch over to the forum, there's a lot of helpful people over there. :)

https://forum.syncthing.net/c/support

**Comment by AceXare** [comment]
okay thank you :)
