### ISSUE TITLE
Deletion of directory containing ignored files is not synchronized to other devices

### ISSUE THREAD

**Issue by tzok** [syncthing/syncthing#4162]
### Description
My `.stignore` file contains entry `*.class` useful for Java projects which have the following hierarchy:
```sh
project/
project/src
project/src/Test.java
project/target/
project/target/classes/
project/target/classes/Test.class
```

With this setup, only my source code is synchronized. 

However when the main directory `project` is moved/deleted, then this is not reflected on other devices. Syncthing running on them deletes all not-ignored files (`src/`) and then stops the synchronization with message "directory not empty" on `target/classes/`. 

### Expected behaviour
If I decide to delete `project` I want it deleted on all devices.

### Version Information

Syncthing Version: v0.14.27
OS Version: Arch Linux x86-64

**Comment by AudriusButkevicius** [comment]
Read the docs:

https://docs.syncthing.net/users/ignoring.html#patterns

```
A pattern beginning with a (?d) prefix enables removal of these files if they are preventing directory deletion. This prefix should be used by any OS generated files which you are happy to be removed.
```
