### ISSUE TITLE
Changed system name requires restart to take effect in outgoing hello messages

### ISSUE THREAD

**Issue by ASmith-** [syncthing/syncthing#4164]
Synchthing ignores user Device Name change and advertises user System Name. A Security Risk

The synchthing user can change their device name from what appears to be the coding pulling that directly from the system platform name. However the system platform name is still shown to all remote peers your ID is shared with. That's a real problem. 

Urgent suggestion, when the synchthing user changes the Device Name in the Webui, that is the Device Name that shows to any and all remote peers you share your ID with downstream.

**Comment by AudriusButkevicius** [comment]
What risk does this actually impose?
It requires a restart for the name change to be picked up.

**Comment by AudriusButkevicius** [comment]
Also, if you would have read the template, it clearly states that security issues (yet I don't think this is one) should not be reported on the bug tracker.

**Comment by calmh** [comment]
This is a bug, in that name change doesn't prompt for restart and also doesn't apparently get set in new outgoing connections. Whether it's a security issue or not is moot as it is now public. Thankfully, I agree it's not a very serious one if it is.

**Comment by calmh** [comment]
Note though, that what other devices show as your name is set in *their* configuration. It gets set at first connection time to whatever you advertise, which indeed defaults to the system name. Changing your name in your Syncthing config will not affect what they see after that point.

**Comment by ASmith-** [comment]
Advertising your unique system platform name downstream is a problem and completely destroys the very reason why you would use a Socks5 proxy to add another layer of anonymous content regarding flying your IPv4 location downstream. This can also be used to remotely attempt a root level entry on that system. There's no sound reason to hand such ability to downstream peers when any pseudo-name would suffice in that field.

Solution
Leave the Device Name field Blank for the user to fill in whatever nicname they chose to manually add there. I suspect the Device ID is incorporating the initial borrowing of the System platform name which henceforth hardcodes it downstream preventing any upstream Device name changes to correspondingly be directly echoed downstream.

**Comment by calmh** [comment]
If you are using proxies to add anonymity and stuff, you should indeed set your device name to something anonymous. You can even set it to the device ID if you like. The default is reasonable and friendly for most users.

**Comment by ASmith-** [comment]
You...cannot...change...the...syncthing device name once its installed. It appears to then be hard coded. The unique system platform name is generated when installing a unix system. What synchthing needs as a Device name has nothing to do with needing the unique system platform name installed onto a OS kernel and advertising that downstream to Synthing peers known and unknown.

**Comment by calmh** [comment]
I'm not sure what you mean is hardcoded, nor really what you mean by a unique system platform name. Perhaps you need to explain clearer what you mean. Syncthing devices have a "name", which defaults to the hostname. You can change it in the settings. It's included in the connection handshake sent to other devices.

**Comment by ASmith-** [comment]
One of my friends is listed as Device ID 'bill-Latitude-D630'. That is the Linux platform system name he recieved upon installing his linux system. Syncthing provides bill's Ipv4 also as its not proxied. I now have his platform system name and Ipv4 address to remotely attach to his specific system on the east coast which is entirely unique from all other linux systems with that distro.

Bill has repeatedly changed his device name, to no avail whatsoever in changing the open downstream display of bill-Latitude-D630 to everyone that is his peers. After changing his Device ID name rebooted Synchthing no change (I'm obviously repeating this over and over here) , shut-down Synchthing and rebooted Synchthing resulting in no change whatsoever with bill-Latitude-D630 still openly advertised downstream to anyone he peers up with.

**Comment by calmh** [comment]
That was Bill's computer's hostname when he installed Syncthing. He didn't change that name before connecting to you. His Syncthing then told your Syncthing that name. It is now set as the name corresponding to that device ID in your configuration. He cannot effect it any more as it is a parameter in your configuration. You can set it to what you like to remind you that it's Bill on the other end.

**Comment by ASmith-** [comment]
It seems like you understand hard coded and describe it also yet don't understand it at the same time? I changed my device ID long before I added bill the peer. However Bill the Peer also sees my system platform unique name also. 

This after I had changed the Device ID name immediately after installing Syncthing then Multiple reboots plus 24 hrs passed since I changed the Device ID name on Syncthing and only then gave Bill my ID string to add me whereupon to my surprise and anguish it displayed my unique system platform name to Bill. Which you are telling me supposedly would change?? Is someone telling you that?

**Comment by scienmind** [comment]
I think there is a point to be made about "downstream device name update":

I agree that it is useful to be able to set a "custom alias" for the remote device, and store it in a local config.
By default, this "custom alias" is set to the remote device's name as it was advertised during the initial connection. However, UX-wise, IMO it is expected that if remote device's name will be updated later, and no local "customization" was made, this "update" will propagate.

In simpler words - if the remote  name was not locally customized - let it accept remote name updates.

It'd help a lot in organizing stuff once you have plenty of nodes, as well as calming down folks like ASmith.

**Comment by ASmith-** [comment]
Openly advertising a unique system users platform name is pretty taboo, I fail to understand how you refuse to remotely understand that. Not able to change that and then suggesting peers downstream can simply rename it further appears to indicate there is a clear inability to understand the problem that presents and I have yet to even see a single person adopt my suggestion to leave that field blank for the user to fill in. Was this even thought of before adding a socks5 proxy addition, this seems to entirely collapse most security models and yet its just marching on?

**Comment by canton7** [comment]
Be polite, please.

**Comment by AudriusButkevicius** [comment]
@scienmind there is already an advanced configuration option for "following" device names.

**Comment by calmh** [comment]
> if the remote name was not locally customized - let it accept remote name updates.

Yeah, we should probably do this. I think this might even have been the intention at some point. If the device name is left blank in the config, it will show whatever the other side calls themselves (while connected) and not adopt it into the config. It's just that when initially accepting a connection it is set to the value announced by the other side, and then kept that way as it's non-blank. This could be improved.

> Was this even thought of before adding a socks5 proxy addition, this seems to entirely collapse most security models and yet its just marching on?

No I don't think we considered this at all in relation to socks proxies. I don't think we considered proxies a part of the security model either. I'll say this though - if your security model depends on keeping this information secret and it's important to you, it doesn't hurt for you to actually test things before deploying in the wild.

**Comment by scienmind** [comment]
> Openly advertising a unique system users platform name is pretty taboo...

That's not true, while it may not be the perfect practice, it's certainly not "taboo". On the contrary, it is quite common for SW to use hostname as a public identifier for a given machine.


> I have yet to even see a single person adopt my suggestion to leave that field blank for the user to fill in

Doing so would add setup complexity to already not-so-simple process. And as noted above, hostname is not to be treated as a "unique & secret system ID"

**Comment by calmh** [comment]
> there is already an advanced configuration option for "following" device names

Ah, so there is. But it's not default and not particularly discoverable. It would probably be better to turn this on it's head, always follow the other side by default, and in the folder configuration have an explicit "[X] Override device name: ________________" thing.

**Comment by ASmith-** [comment]
I would push the code to reboot or prompt to reboot syncthing if the user changed the Device ID name. 
And I fail to understand how folks would add the ability of Tor and I2P via a socks5 proxy while providing your unique system platform name right out there for anyone to see.

As long as the device ID name is unique, that is all that is needed for syncthing isn't it? Its not dependant on nabbing that from the system platform name itself.

**Comment by calmh** [comment]
Apart from everything else, I think there is a misunderstanding about what the name is. There is no such thing as a "unique system platform name". And if there is, it's not what we're using. The *host name* is a friendly name given to a computer because humans are bad at long, unique IDs. It's typically something like "Jakob's MacBook" or "syno". It's not typically unique, other than as a fully qualified domain name. And we send it because when you get the question of whether CMW4EHH-Z7PP3GC-XC3MGD7-Q7BEXKI-NLAADPD-AKNMAEF-QB4CTIB-TKIMPA7 should be allowed to connect it's easier to answer that question if we also tell you that that's "Jakob's MacBook".

> Openly advertising a unique system users platform name is pretty taboo

... and while the tabboo-ness is a matter of opinion, please note that "openly" here means "to the person you've given your device ID in order to establish a mutual trust relationship".

**Comment by scienmind** [comment]
>  It would probably be better to turn this on it's head, always follow the other side by default, and in the ~~folder~~ device configuration have an explicit "[X] Override device name: ________________" thing.

I think that'd be the best way to go about it 👍 

Also, unrelated to syncthing, as far as hostnames go - taking into account the vast amount of sw that uses it as a device's alias it would be a good practice in general to keep it not-too-unique.

**Comment by ASmith-** [comment]
On a local area network, folks are generally aware of one anothers hostnames. Unknown peer's 3,000 miles away however generally do not unless the partys wish to make that known. Remote logon tools use the unique system platform name, their ipv4 and a less than creative means to seriously compromise a system. If the unique system platform hostname is not entirely essential, it shouldn''t be openly advertised. How much effort would it be to simply run anything in that field through a md5 hash sum and using that as the device ID ?

On Retroshare a secure, encrypted, global decentralized communications platform we run into the issues and problems of establishing a mutual trust system and a friend to friend modeling. I'm impressed by what syncthing offers and hope to present this to Retroshare peers when I am able to mask the Device ID name. My thanks for your feedback and attention on this issue.

**Comment by canton7** [comment]
> Unknown peer's 3,000 miles away however generally do not unless the partys wish to make that known

Why is the peer unknown, if you've specifically told Syncthing that you want to establish a mutual trust relationship with them? Syncthing won't tell random PCs your hostname - only devices which you have told Syncthing you want to trust.

> it shouldn''t be openly advertised

Again, it is not "openly advertised". It is *only* given to devices which you have told Syncthing should be trusted.

**Comment by calmh** [comment]
> How much effort would it be to simply run anything in that field through a md5 hash sum and using that as the device ID ?

The device ID has nothing whatsoever to do with the hostname. The host name, or the name that you configure, is sent to the other side only to be informative and let them know who is trying to talk to them.

**Comment by AudriusButkevicius** [comment]
@canton7 that's not strictly true, you could potentially probe for that, as the name is sent to everyone who connects regardless if its known or not.

**Comment by canton7** [comment]
I was rephrasing @calmh: 

> ... and while the tabboo-ness is a matter of opinion, please note that "openly" here means "to the person you've given your device ID in order to establish a mutual trust relationship".

If anyone can get the hostname for a given Device ID then that's a different matter entirely...

**Comment by calmh** [comment]
It is unnecessary for the responding side to send this data before the calling side has proven themselves worthy. I have a proposal to fix that somewhere, also doing the same for the device ID (which is somewhat trickier). The *real* problem is exposing a unique identifier to a portscan, and the device ID is that (not the device name). I don't think the OP is susceptible to portscan though, what with being behind the proxies and stuff.

**Comment by AudriusButkevicius** [comment]
@canton7 well it exposes your configured name, not necessarily the hostname, which could be complete gibberish, but you need that to have some sort of indication of who the other side is. Perhaps we should use current username oppose to the hostname as the default (yet root is not an ideal name to advertise either)

**Comment by canton7** [comment]
@AudriusButkevicius wouldn't it be easier to do what @calmh suggested above, and only expose the configured name to devices it has been told to connect to (rather than to devices trying to connect to it)?

**Comment by AudriusButkevicius** [comment]
Yeah, that would be a trivial fix I guess.
