### ISSUE TITLE
BUG: Changing the Device Name does not change Remote Device Name peers see

### ISSUE THREAD

**Issue by ASmith-** [syncthing/syncthing#4165]
BUG: Changing the Device Name does not change Remote Device Name peers are shown.

Synchting Version v0.14.28 Ubuntu Xenial amd64, Browser Firefox 53.02 64bit.

Actions -- Setting --> Device Name changed from xyz to abc and saved.
Remote Peer Device ID added, they add my Device ID and are shown for Remote Device xyz, NOT abc.
This BUG should properly show the users changed Device Name downstream as well to the peers which should properly show the changed Device Name on their Webui.

**Comment by AudriusButkevicius** [comment]
This change requires a restart as I've explained in the other ticket.

**Comment by ASmith-** [comment]
I'll try that 'again' here. I changed the Device name immediately late last night, rebooted synchthing repeatedly since then and just now added a remote peer who I was able to discern saw my system platform name here, NOT the changed device name.

**Comment by calmh** [comment]
Dup of #4164
