### ISSUE TITLE
Webui doesn't work on the current Tor Browser Firefox but does on regular Firefox

### ISSUE THREAD

**Issue by ASmith-** [syncthing/syncthing#4166]
The syncthing latest stable version on Ubuntu/Mint Xenial/Serena 18.1 LTS doesn't pull up on the Tor Browser Firefox, it does on my regular memory sapping Firefox. 

I prefer to leave my Tor Browser Firefox running 24/7 as it uses a whisper of resources compared to the regular Firefox and my Tor Browser readily pulls up multiple apps Webgui 127.0.0.1:xxxx local screens on it but I am unable to with Syncthing. I've already tried shifting from https to http without any success.

**Comment by calmh** [comment]
This sounds like a browser issue?

**Comment by ASmith-** [comment]
I was hoping someone had some similar findings and possible suggestions on fixing this problem. Both browsers are Firefox. The Tor Browser firefox supports Webui local gui displays from multiple applications without issue, the Syncthing WebUI however doesn't connect nor display. I was hoping for something other than bouncing back and forth between Syncthing and Mozilla and Tor on this issue with Syncthing WebUI.

**Comment by calmh** [comment]
I suggest using the developer console to figure out what the problem is. I assume the Tor browser has disabled all kinds of functionality for privacy reasons, and our GUI depends on some of the disabled functionality.

**Comment by alex2108** [comment]
works for me after adding 127.0.0.1 to "No Proxy for" in connection settings. Security is on low (default). Higher settings lead to disabled javascript so the page loads but does not work.

**Comment by ASmith-** [comment]
Thanks a lot alex2108, that was what was missing and once I added the following functionality returned on my Tor Browser with the Syncthing WebUI. In the Tor Browser Firefox these steps were followed:
'Edit' -- Preferences -- Advanced -- Network -- Settings --> No Proxy for: 127.0.0.1:8384
