### ISSUE TITLE
Allow globs in include directive for .stignore

### ISSUE THREAD

**Issue by nwmcsween** [syncthing/syncthing#4167]
This allows cloning [gitignores](https://github.com/github/gitignore) and then just including the repo e.g. `#include ./gitignore/*.gitignore`

**Comment by AudriusButkevicius** [comment]
I personally would say no. 
Supporting includes is already stretching it.

Plus I think our ignores are different from git ignores, so I wouldn't expect this to work in general.

**Comment by calmh** [comment]
Yes, negatory on this unfortunately. Even if it would be technically feasible and make sense, the long term plan is to move _away_ from .stignore files towards having the patterns in the config instead, possibly synced between devices.
