### ISSUE TITLE
Folder Pairs

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing#4171]
When creating new ST Folders in the GUI under Folders < Add Folder < Folder Path, I would love to have an option that lets me select several source folders rather than selecting one and only one folder at a time.

This can supply the end-user with an easy, graphical way to manipulate what is excluded and what is included.

**Comment by imsodin** [comment]
I guess this depends on #2958 and is related to, if not a dup, of #2491.

**Comment by canton7** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for similar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.

**Comment by AudriusButkevicius** [comment]
I don't understand what is being asked here.

**Comment by calmh** [comment]
I think this is selective sync stuff, i.e., select five folders all under a common parent, and sync just those?

**Comment by AudriusButkevicius** [comment]
I think so, in which case I close it as a duplicate. Op can make a case for reopening.

**Comment by jebeld17** [comment]
Sorry, I forgot to get back.
I would like to have an ability to select a set of folders that are under one parent and sync those in the exact same fashion and hierarchy that is on the origination machine.

Let's say I want to sync my User folder under the C:/Users/<username> part of my drive, but I only want to sync "Desktop", "Contacts", "Documents", and "Searches" without having to go in and add exceptions into the .sync file. 
This would allow the user (me) to do this through a rather simpler GUI fashion.

**Comment by AudriusButkevicius** [comment]
Which is what #2491 talks about.
