### ISSUE TITLE
Pause with timer

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#4172]
As suggested in the [forum](https://forum.syncthing.net/t/pause-sync-timer/9822/7) add a timer to the pause functionality. Unpause after N hours, N days, etc. Helpful if you are on a slow connection or need more bandwidth for a certain time for other applications.

**Comment by AudriusButkevicius** [comment]
No, soon you'll want a full blown scheduler with sunrise dates and moon phases. The rest API is easy enough to use.

**Comment by calmh** [comment]
Out of scope for the moment, potentially implementable in a wrapper or external tool
