### ISSUE TITLE
Syncthing needs more socks5 proxy support

### ISSUE THREAD

**Issue by ASmith-** [syncthing/syncthing#4174]
Syncthing needs more socks5 proxy support

Syncthing not running and issued the following in the environmental variables:
$ export all_proxy=socks5://127.0.0.1:9150
$ export ALL_PROXY_NO_FALLBACK=1

Then started Synchthing and found via a remote peer syncthing which I later installed and setup my raw IPv4 was fully disclosed, not the Tor Proxy exit server address. This borrowed my Socks5 Proxy from the existing, running Tor Browser Tor Network connection. 

I checked the LOG in the /home/.config/syncthing folder and didn't see anything at all in regards to the proxy being recognized nor the fallback was disabled. Perhaps that only happens if the 'Debug' is enabled?

I repeated the above steps using another Socks5 Tor Proxy I had been using on another application and shut it down to use on proxying Syncthing via socks5 127.0.0.1:9058 and again issued the export 
proxy environment variables

$ export all_proxy=socks5://127.0.0.1:9058
$ export ALL_PROXY_NO_FALLBACK=1
and restarted syncthing.

Syncthing Version v0.14.24 Linux amd64 Ubuntu/Mint Xenial/Serena 18.1 LTS
Again the naked, raw personal, local IPv4 address is being displayed on the new remote peer system I had setup rather than assume anything such as this anonymous socks5 proxy support feature was working properly. I rebooted the remote peer syncthing and again the local IPv4 from that peer system which was I thought proxied was still showing the raw IPv4 address.

Items which are needed for Syncthing 
1) Show in settings what your external IPv4 is being shown to your peers whenever the proxy environmental variable is set or perhaps regardless if set or not. If a string comparison between local Ipv4 and proxied Ipv4 are identical then obviously there's a problem.
2) Show in settings that the socks5 proxy is enabled, don't force the user to dig through /home/.config/syncthing/LOG searching simply to see if that is in fact activated like you thought it was.
3) Show in settings that the NO_FALLBACK variable is enabled, don't force the user to dig through /home/.config/syncthing/LOG searching simply to see if that is in fact activated like you thought it was.

I generally use this link https://check.torproject.org/?lang=en_US
to determine if that connection is being routed via the Tor Network and what that current IP is. Other applications such as Qbittorrent might use another method in its C++ source to display what that application is externally displaying as your IPv4 be it the tor exit servers IPv4, i2p exit server, VPN exit server or your raw IPv4 address.

Currently these items are needed at a glance, not forcing users to dig through various separate folders attempting to see if the proxy is in fact enabled nor the need for a user to setup a remote syncthing peer to verify if the proxified syncthing is in fact functioning properly or not.

**Comment by calmh** [comment]
The discovery servers cache addresses for an hour or so. What does the remote device show after a couple of hours of socks only connectivity?

**Comment by ASmith-** [comment]
Thank you for your time and suggestion calmh, I'll give it acouple hours to see if anything changes regarding the displayed IPv4 address. Not seeing anything in the LOG seems to indicate something isn't correct. I didn't see any errors generated during entering the terminal environmental variable settings. I've since turned Debug On but haven't checked the log again, I'll reboot syncthing after another hour and re-check the LOG. I might close it and then reboot syncthing in a terminal to see if there are additional clues as to what is happening.

I wanted to also inquirer in my parent thread which introducers are needed or could be problematic using a socks5 proxy. Its essential the downstream peers see only a proxied IPv4 not the raw users IPv4 in this series of tests. The default of also use a relay is left unchanged, I recall reading a relay would be essential for this setting to function properly.

**Comment by calmh** [comment]
> On 24 May 2017, at 05:19, A.Smith <notifications@github.com> wrote:
> 
>  Its essential the downstream peers see only a proxied IPv4 not the raw users IPv4 in this series of tests.

You should not count on this being the case without taking significant precautions, such as ensuring that device's only internet connection is via a router that tunnels everything through Tor, and doing significant tests and audits on your setup after upgrades. This is not something that we guard against, and we will be adding things like UDP based protocols (which will not go through proxy), "discovery gossiping" (one device assisting another in finding it's peers by sharing it's knowledge of their addresses), etc.

**Comment by ASmith-** [comment]
Yes, inside Retroshare we use UDP for the custom KAD DHT lookup and we also have a enhanced additional Discovery tool. These are decentralized. Both are basically disabled when routing via a Socks5 Proxy to the Tor, I2P Anonymous Networks. As you noted, Tor doesn't normally support UDP/DHT lookups and calls, I2P however does however we at Retroshare do not use that.

What we do is run a Retroshare regular node via a Socks5 Proxy such as Tor or i2P to connect to a Retroshare hidden node inside the Tor or I2P Network running as a hidden service. What we do in this case in aleiu of UDP/DHT or our Discovery 2.0 tools to locate the remote peer is to use their .onion or .i2p address which is fairly secure, encrypted and encoded. Flagging a .onion or .i2p address downstream has far less consequences than the same with the users raw IPv4 address.

Starting Syncthing inside a terminal ./syncthing displays the notices the initial Proxy info:
[monitor] 22:48:26 INFO: Proxy settings detected
[monitor] 22:48:26 INFO: Proxy fallback disabled
[AMAXV] 22:48:26 INFO: Proxy settings detected
[AMAXV] 22:48:26 INFO: Proxy fallback disabled

Sadly, however the display also includes a series of centralized servers which are being used as discovery servers. 

[AMAXV] 22:48:29 INFO: Using discovery server https://discovery-v4-2.syncthing.net/v2/?id=id=user-id-string
[AMAXV] 22:48:29 INFO: Using discovery server https://discovery-v4-3.syncthing.net/v2/?id=id=user-id-string
[AMAXV] 22:48:29 INFO: Using discovery server https://discovery-v4-4.syncthing.net/v2/?id=id=user-id-string
[AMAXV] 22:48:29 INFO: Using discovery server https://discovery-v6-2.syncthing.net/v2/?id=id=user-id-string
[AMAXV] 22:48:29 INFO: Using discovery server https://discovery-v6-3.syncthing.net/v2/?id=id=user-id-string
[AMAXV] 22:48:29 INFO: Using discovery server https://discovery-v6-4.syncthing.net/v2/?id=user-id-string

I recall early networks which used a similar array to help bootstrap new connections. This moves trust over to unknown centralized servers for users. The proxy inclusion seems to be at a crossroads, to work as a anonymous proxy the coding would need to allow Syncthing to optionally operate as a Tor, I2P hidden service, episite which adds an additional virtual port. Regular syncthing peers would then be able to connect to those using the hidden service / episite .onion / .i2p address using the appropriate Socks5 proxy via Tor / I2P.

The other direction would be to eliminate the Proxy support as that is fairly misleading at this stage. I think most users would readily believe that would represent an anonymous proxy support, not a transparent or forwarding proxy which is very common and does nothing to strip the http headers.

Dependance on UDP/DHT enters application users into a ever more aggressive battlezone as the network grows so do the numbers of people that attack those networks masquerading as other users and causing all kinds of grief to its users. I hope we can add additional DHT security enhancements to Retroshare in the months ahead having gone through this ourselves last year and our custom KAD DHT is only moderately large, not huge like mainline-DHT or perhaps some other UDP/DHT discovery lookups.

**Comment by calmh** [comment]
Mkay. So does it still seem to bypass the proxy and announce it's real address, after a couple of hours?

**Comment by ASmith-** [comment]
Yes, I was finally able to obtain a proxy address across both systems. Currently I'm borrowing the socks5 127.0.0.1:9150 from the Tor Browsers on both local and remote systems and running Syncthing via a terminal. I'll continue evaluating this as what might have happened was after issuing the exports of the proxy variables and using the 'open' gui command flushed out those variables. While directly running it via a terminal is proving successful. I'll write a quick, short bash file to issue the needed commands and bring Syncthing up via a Tor proxy without the need for borrowing the socks5 proxy from the tor browser. 
On the remote system:
[D2STJ] 02:55:29 INFO UPnP parse: Get http://192.168.1.1:5000/Public_UPNP_gatedesc.xml: proxy: SOCKS5 proxy at 127.0.0.1:9150 failed to connect: general failure.

However the remote system went on to connect to the relays and proxy its IP to my local system.

**Comment by calmh** [comment]
I'm not sure what you mean about borrowing, but it sounds like it functions as desired then
