### ISSUE TITLE
Proxy use displays full Raw IPv4,Relay and TCP Ipv4's for entire circuit to remote peers

### ISSUE THREAD

**Issue by ASmith-** [syncthing/syncthing#4176]
This looks like a BUG, in the least a coding oversight which displays all the IPv4's of the users raw IPv4, tcp users, relays Ipv4 in the circuit to and from a socks5 proxied via the Tor network to and from another Syncthing Peer also using a socks5 proxied Tor network connection. When a relay in the syncthing routing breaks and resets there's a cascaded compiled history of the IPv4 locations all the way back to the raw IPv4 of the sender.

Its likely the coding is loading up the http headers with all kinds of meta-data which indicates every hop and location that data packet travelled through and from beginning to the end of the entire circuit. Then openly displaying this compendium of meta-data to the remote peer whenever a relay operator disconnects or the network rearranges itself. This is an issue which should be addressed and patched.

**Comment by calmh** [comment]
I have literally no idea what you're saying. Please clarify what you did, what results you expected, and what results you see instead. Exemplify with logs or screenshots.

**Comment by ASmith-** [comment]
Perhaps someone else can interact with my issue here?

**Comment by AudriusButkevicius** [comment]
I am in the same boat as @calmh. The issue template is there for a reason.

**Comment by canton7** [comment]
Yeah, I'm having a lot of trouble with your description as well.

>  IPv4's of the users raw IPv4, tcp users, relays Ipv4

What's a "raw IPv4"? What's a tcp user, specifically (which differentiates them from someone using IPv4)? What's a "relays IPv4"?

>  in the circuit to and from a socks5 proxied via the Tor network 

The "circuit"? I'm assuming "a socks5" is supposed to be "a socks5 proxy"?

> When a relay in the syncthing routing breaks and resets

"The syncthing routing"?

> here's a cascaded compiled history of the IPv4 locations all the way back to the raw IPv4 of the sender.

"Cascaded compiled"? What's the "sender"? Where is this shown? I've never seen it...

> Its likely the coding is loading up the http headers with all kinds of meta-data which indicates every hop and location that data packet travelled through and from beginning to the end of the entire circuit. 

Again, "circuit"? Syncthing doesn't speak HTTP (except to the discovery servers which aren't being discussed here), so I'm not sure where HTTP headers come into it.

Describe the problem that you're seeing, with screenshots. Don't try and guess what's happening under the hood, and please only describe the issue using terms that you're comfortable using.

**Comment by Ferroin** [comment]
From what I can tell, he's trying to say that there's enough data in communications between Syncthing instances to figure out each one's real IP address even if it's been proxied.

Also:
* 'Raw IP' is one of the common terms among Tor users for the actual IP address of a node.
* At a high-level, Tor behaves as a switched network (routing decisions are persistent per-connection), so a connection through Tor is usually called a circuit.
* From the perspective of non-Tor-aware applications, Tor is a SOCKS5 proxy.
* 'Syncthing routing' almost certainly refers to the path between devices (which is technically a routed connection since you may or may not be bouncing off of a rely).

**Comment by AudriusButkevicius** [comment]
So the issue here is most likely due the fact that we do not listen via the socks proxy, so the incoming connections come through the internet and not tor, plus we announce local address to discovery regardless if proxy is setup or not, so even if you have two nodes with tor proxies setup, the incoming connections are coming through standard internet which exposes the ip address. The only way to make both peers use tor in this case is to statically configure two devices to connect to the same relay and disable discovery,

**Comment by ASmith-** [comment]
I could take a week, perhaps even 10 days to detect a network collapsed Synchthing peer disconnect scenero I saw and explained above for a opportunity for me to capture a 'screen-shot' to display the values being shown when the networked circuit collapses and in the dynamic address of the remote peer you are shown a list of all of the Ipv4's from the relays through the tcp's all the way to the sources Ipv4 location addresses.

This being on a Socks5 Proxied Syncthing on both ends which a user would use to mask their raw Ipv4 address location in the first place. Instead the entire litney of actual IPv4's is being displayed all the way from A through Z.

There's multiple http header meta-data that could be the culprit that is doing this. Generally anonymous proxied Socks5 proxys strip out all the relay, via etc. meta-data. If they didn't then obviously to nearly everyone they aren't anonymous proxys.

Looking over the replies, it also appears many do not realize this and know how http headers could cause this problem nor what they can be filled with in regards to transport meta-data. So I'll show you the most common ones.

REMOTE_ADDR : 108.162.XXX.XXX
HTTP_X_FORWARDED_FOR : 78.32.XXX.XXX
HTTP_CLIENT_IP : 159.147.149.18
HTTP_VIA :  211.75.35.54

This meta-collection of the forwarding http headers not being properly cleaned out could account for the open display of the entire list of Ipv4 addresses for each single party from A through Z. It definitely should not show the peer sources raw Ipv4 location IP address when they are using a Socks5 Proxy which strips out all mention of their raw IPv4 location IP address and should only show the last known proxied Ipv4 as to the Source IPv4 location address.

**Comment by AudriusButkevicius** [comment]
I think the flux capacitor is at fault, not the meta collection circuits.

**Comment by ASmith-** [comment]
![syncthing-list-dynamic-addresses-proxy-test copy 2](https://cloud.githubusercontent.com/assets/8520894/26475958/1447f640-4170-11e7-8c33-49efbbf2ca4c.png)
Three Ipv4's showing are the raw Ipv4 Peer's regardless of the fact they were proxied via a socks5 tor connection when the connection died.
One Ipv4 shows my raw Ipv4 address regardless of the fact I have continuously used Syncthing proxied via a socks5 tor connection 24/7 for days now.

The above image shows full laundry list of meta-data containing the IP addresses of each person, each relay along the entire network connection points from my source to this peer even though both Source and remote Peer are running a socks5 tor proxy.

![syncthing-remote-devices1 copy 2](https://cloud.githubusercontent.com/assets/8520894/26475964/2404890e-4170-11e7-87ef-50c8ed9de7a5.png)
Three Ipv4's show the peers raw IPv4 address location regardless of the fact there were proxied via a socks5 Tor proxy connection when the connection died and this pile of Ip addresses are openly displayed.

This meta-data dump when the network connection is interrupted and temporarily disconnects appears to be left-over from the developers early on wanting to see if the network was being formed correctly and not eliminating that display in the later production coding.

**Comment by calmh** [comment]
Those are the addresses announced and found using global discovery. Given that a couple of them use non-22000 ports I'm guessing the source is UPnP or PMP port mappings on your router. You should probably disable UPnP and PMP in Syncthing if you don't want this. The port 22000 one and the IPv6 seem to be announcements made directly, not going through a proxy. Or it could be the Tor exit node, which would make sense, I can't say.

**Comment by AudriusButkevicius** [comment]
https://github.com/syncthing/syncthing/blob/master/lib/discover/global.go#L111 says that shouldn't happen, unless fallback is not disabled or there is an http proxy that exposes the address.

Anyways, the socks functionality is there for connectivity, not annonimity, atleast from my perspective.

**Comment by AudriusButkevicius** [comment]
Also, the fact that we don't listen via the proxy by definition makes it possible to have both nodes connect through tor as I've explained above.

**Comment by calmh** [comment]
Yeah I don't think we bypass the proxy. But Syncthing may have been (re)started without proxy env, or the proxy may have made direct requests if Tor was down, or the address may be the Tor exit node, or something.

**Comment by ASmith-** [comment]
The Socks5 Proxy coding on Syncthing appears to need additional support coding added to it in order to function with expected anonymity. Currently its very likely Syncthing's Socks5 Proxy ability is being confused by a user as providing anonymous files transfers which at this stage of development it clearly does not provide. Syncthing at times while operating with an anonymous socks5 proxy openly displays all the active IPv4's in the routed circuit to the remote peer as shown in the images above including the users non-proxyed raw IPv4 location. I can try to encourage peers to use Syncthing without the socks5 proxy ability making it clear their Ipv4 location is openly advertised to their remote peers. I wouldn't try to explain Syncthing's pseudo-anonymous socks5 proxy ability which needs a lot of additional support at this stage of development however.

I might as well close out this comment. If Syncthing developers add additional socks5 proxy support which deals with the multiple issues raised in this series of posts, I hope someone then re-opens this issue leading it to a successful conclusion.
