### ISSUE TITLE
Separate bind address and actual server address

### ISSUE THREAD

**Issue by Avamander** [syncthing/syncthing#4189]
I would like if it was possible to tell Syncthing that it should listen to [address 1]:[port] but it should also be able to update all the links, CSRF policies and everything else to match actual server address at [address/domain 2]:[port2].

For example this simple config for nginx should already work, currently it doesn't (throws CSRF errors because it doesn't know it's behind a proxy): 

(It should also be able to detect if it's behind htaccess or similar password protection but that's another topic)
```
    upstream syncthing{
        server localhost:8384 fail_timeout=0;
    }
[...]
    location / {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade"; #$connection_upgrade;
        proxy_pass           http://syncthing;
    }
[...]
```

**Comment by AudriusButkevicius** [comment]
Please read the docs before opening issues.

https://docs.syncthing.net/users/reverseproxy.html

**Comment by Avamander** [comment]
I have to inform you that following that thing exactly still causes errors for me and it shouldn't need that much configuration.

**Comment by AudriusButkevicius** [comment]
So I am sure plenty of people are already doing it. I suggest you start by searching on the forums.

**Comment by calmh** [comment]
All Syncthing links in the GUI are relative, so you can relocate it as you wish. Any CSRF error has nothing to do with the forwarding itself.

**Comment by Avamander** [comment]
Then what causes it then? Maybe more detail would be nice in that error message?

**Comment by AudriusButkevicius** [comment]
I am locking this, as this should belong on the forum, for educational purposes if anything else.
