### ISSUE TITLE
Empty file when deleting file on the other device

### ISSUE THREAD

**Issue by redmanmale** [syncthing/syncthing#4190]
### Steps to reproduce are not working always, though.

Delete a file from one device.

### Expected behavior

File is removed from every other linked device as well.

### Actual behavior

Sometimes on other devices file is not removed, but its size is 0 bytes, it's empty.

### Version Information

Syncthing Version: v0.14.29, 
OS Version: Windows 7, 8.1 (64 bit)

**Comment by AudriusButkevicius** [comment]
Please search the forums, this was answered before.
