### ISSUE TITLE
renaming reupload the entiere subfolder

### ISSUE THREAD

**Issue by chmol** [syncthing/syncthing#4191]
I'm not sure it's by design or not and couldn't find any info while researching so here is the issues I run into from time to time:

 ### what happened
Renaming a directory the entire content is re-uploaded to the others devices. It's really inefficient and a waste a bandwidth. 

### what you expected to happen instead
some clever way for syncthing to rename the folder on all the other devices.

### any steps to reproduce the problem.
rename folder.

### Version Information

Syncthing Version: v0.9.2.4
OS Version: Manjaro latest upgrade.

**Comment by DrSchnagels** [comment]
Syncthing Version: v0.9.2.4
Really?
We have v0.14.29 now.

**Comment by AudriusButkevicius** [comment]
Check existing closed issues and the forum.
