### ISSUE TITLE
Build Debian packages of extra targets (stdiscosrv, strelaysrv, strelaypoolsrv)

### ISSUE THREAD

**Issue by flurischt** [syncthing/syncthing#4193]
Hi

The repo syncthing/discosrv points to an invalid "latest builds link" to download it. Also for the sourcecode this repository here is reference but I couldn't find a build of discosrv under releases. 

What's the best way to download discosrv builds? I found https://build.syncthing.net/job/stdiscosrv/lastSuccessfulBuild/ but unfortunately those links cannot be used for an automated setup because the links/filename regularly change. Is there any way to have a donwload link for discosrv where I could point my docker file to?

**Comment by AudriusButkevicius** [comment]
So I'd say this should live on the forum.

**Comment by calmh** [comment]
There is not, currently, but it changes very infrequently. (There is also no such link for syncthing itself either, etc.)

**Comment by flurischt** [comment]
OK thx. But for synching itself there's the apt repository and (recent) GitHub releases. Both easy for an automated install where for the discovery server I only found the manual way by looking for the latest build.

**Comment by calmh** [comment]
The build process knows how to build a deb package of stdiscosrv, so there is no good reason we don't have a package published, really.

**Comment by calmh** [comment]
OK I lied it doesn't actually do a very good job of building a deb for it, but I can fix that and make sure to add it to the apt archive in next release.

**Comment by flurischt** [comment]
That'd be awesome! :)

**Comment by calmh** [comment]
So expect this when 0.14.31 is out (not 0.14.30)

**Comment by flurischt** [comment]
:+1: Thank you!
