### ISSUE TITLE
suggestion: add to the prefs a way to push notifications to the system when a file in a folder you are sharing is modified, added, deleted etc.

### ISSUE THREAD

**Issue by marrie** [syncthing/syncthing#4195]
Hello. This is just a suggestion, but is there a way to have notifications appear in apple's notifications center or windows system tray  to notify a user when a file has ben added, removed, modified etc? Me and a buddy were using this and we both thought this would be a good idea. Over all we got the program set up on their computer in a matter of a few hours This is the only thing that we would both recommend in case let's say I'm on the network and can't see if a file has ben modified at the other computer,. 

Using the latest v0.14.30-rc.1, Mac OS X (64 bit)

hope that helps.

Thanks.

**Comment by calmh** [comment]
It would only be possible when the GUI is open, which would defeat the purpose I think. There are several native GUI wrappers that you might want to look into instead though, i hint those have this feature.

**Comment by marrie** [comment]
Thanks. I already took a look and don't see anything for mac os as of yet.  I normally keep my gui closed but I was thinking dropbox like as that has notifications and I don't have the app open at all, it is sitting in my extras menu. Thanks.

**Comment by imsodin** [comment]
@marrie Look at the tools in the [Community Contribution](https://docs.syncthing.net/users/contrib.html) part of the documentation. There is several mac os specfic or cross-platform wrappers providing notifications.
