### ISSUE TITLE
FR: Better version naming

### ISSUE THREAD

**Issue by gerroon** [syncthing/syncthing#4197]
Hi

At the moment the simple file versioning versions the file along wiht dates which is fine but not enough to know what really happened to the file that required versioning. 

So I am proposing that the version naming should include couple additional clues like deletes, modifies, moves etc (when possible).

For instance a file like 

```
myfile~20161212-214528.txt can be more informative if  we use something like this 

myfile~del-20161212-214528.txt (the file is versioned because it was deleted)
myfile~mov-20161212-214528.txt (the file is versioned because it was moved)
myfile~mod-20161212-214528.txt (the file is versioned because it was modified)
```

I think that keeping the abbreviation at 3 chars can be useful for future restores. 

This way one can really know what happpened to the file, and when restoring the user gets a better picture that can help with restoring strategies.

One other benefit of this kind of naming is that the user can search for deletes, moves etc in the .stversions folder or only rsestore deletes when needed.

thanks

**Comment by AudriusButkevicius** [comment]
It's fairly trivial, if the original file is still there, it's modified, otherwise it's deleted. We do not know about moves and such so it's not something we could indicate.

**Comment by gerroon** [comment]
Well even if we get the deletes versus modifies, that is great.

**Comment by AudriusButkevicius** [comment]
You already get that, essentially by checking if the original file is there or not.

**Comment by gerroon** [comment]
Well the issue is not that I cant check it, the issue is that when dealing with alot of files this is a very very tedious process. For couple files, sure I can manually check it and I see no reason for a feature but when one needs to comb through alot of files in .stversions things get faily complex very quickly.

**Comment by AudriusButkevicius** [comment]
Sure, but I think for something more than a few files I'd expect you to have something that makes your life easier and automates it.

Also, you have the global change log and verbose command line options which says who does what which you can aggregate into a log.

**Comment by AudriusButkevicius** [comment]
My point is, you can already achieve this in other ways. The fact that you'd find it useful doesn't necessarily mean it would be of use to others.

I personally don't care if its a modification or deletion, and would be more fussed having to fix restoration scripts, synctrayzor and other many other tools that people have developed over the years to work with the new convention versus one person writing a script to help himself out. 

If we had a ton of people screaming for this, it would be a different story.

**Comment by gerroon** [comment]
It is just a feature request.

**Comment by AudriusButkevicius** [comment]
Sure, but we should evaluate the pros and cons and decide if this is something worth breaking compatibility for, and if not, close it, hence I am pointing out my views on the matter.

**Comment by calmh** [comment]
I could go either way on this. One thing though, the date is (unless I remember incorrectly) that of the last timestamp, not the action we took. This makes sense as a marker of the age of the file that we archived. But it if we add an action before it it will look very much like the time we took that action.

**Comment by canton7** [comment]
Also bear in mind that we've adding the short ID into this filename as well: it's starting to become a cryptic bag of all sorts of information which is going to be hard for the user to tease out, and will become increasingly likely fall foul of path length limits on Windows.

**Comment by AudriusButkevicius** [comment]
I think we are adding that only to conflicts.

**Comment by canton7** [comment]
Aah misread the issue. Ignore me.

**Comment by calmh** [comment]
I'm going to close this because I think it's something we don't want to do. We want to pollute the file name as little as possible, in my opinion. The date is required as a disambiguator.
