### ISSUE TITLE
Feature request: RUNONSTART and RUNONEXIT startup parameters

### ISSUE THREAD

**Issue by klockd** [syncthing/syncthing#4199]
Hi

I would like to request a feature to allow running a command ONSTART and ONEXIT.
Something like using a "subst" command to map a drive or a script to notify the user that the syncthing is up/down.

**Comment by calmh** [comment]
You could do this fairly simply with a shell script or batch file:

#!/bin/bash
# your on start command here
syncthing -no-restart
# your on exit command here
