### ISSUE TITLE
Repository stops permanently

### ISSUE THREAD

**Issue by arneko** [syncthing/syncthing#420]
Hi there,
I am running into a small issue on my linux machine when I include a repo that is not mounted at startup. Syncthing will stop that particular repo, but never tries to restart it. Is that expected behaviour? I think it would be nice if syncthing would recheck at the next scan interval. Might also be useful for usb-sticks.
The only way I see right now to get around this is adding my drive to fstab. 

Thanks!

**Comment by AudriusButkevicius** [comment]
Fixed by https://github.com/syncthing/syncthing/commit/7406176fadf277e714e91ad97d462bebc2a7db8d
