### ISSUE TITLE
Search in .stversions for available chunks

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#4205]
I can't find were we talked about that (forum / bug tracker ?) so I create this issue : 
If I remember correctly, we agreed that ST could search in local .stversions for chunks of files that were changed/deleted to limit the amount of data to be transferred from device to device in this use case : 
Use case: file A is in some folder. Now I do a copy in same or other folder, then I delete file A. Sometimes, deletion synchronisation is performed before the copy then remote device can't "Copied from elsewhere" or "Copied from original" (I'm not sure I understand the difference, so I don't know if it is worth mentioning both the 2 status).
As long as there is no way to make sure copies are performed before deletions, it should be nice if files in .stversions were added to the database or an auxiliary DB, so that ST eventually has local chunks available.

**Comment by AudriusButkevicius** [comment]
This can be worked around by adding an un shared folder rooted at .stversions. also I think this is a dupe.

**Comment by calmh** [comment]
I don't think we want to index and track .stversions which would be required to do this.

**Comment by bugith** [comment]
Nice, in the end did you find a way to have all pending deletes pushed down to tail of queue before any move is proceeded ?

**Comment by AudriusButkevicius** [comment]
Its always done like this,but it's racy if deletes appear mid scan.
