### ISSUE TITLE
inability to edit folder path once a folder is shared

### ISSUE THREAD

**Issue by marrie** [syncthing/syncthing#4209]
I've made my share of mistakes in entering folder paths. I've tried to edit said paths. No joy. Can editing a path once you click edit for a folder be implemented? What if I change drives and need to edit the mount point. I don't want to reshare the folder or ask a user/client to reshare a folder just so I can redo the path to the new location. I also don't want to re-add a folder and reshare with users/clients/machines just because I goofed or changed drives etc. Is there a way to do this. I'm using safari and chrome and voiceover on the mac.

**Comment by AudriusButkevicius** [comment]
Remove and add again.

**Comment by marrie** [comment]
That would be an issue though.  I would have to reshare the folders with my users/ clients, and not all of them have the web interface open at all times to reaaccept the invite to the folder.

**Comment by AudriusButkevicius** [comment]
Changing the path of a shared folder (even if its accidental) is dangerous and could delete all your files.

If the folder id is the same (which you can set as you add a folder) nothing would need to be reshared.

**Comment by marrie** [comment]
which again  leads to the problem  or resharing the folder with the user/client/machine. Not all of us will be around to  reaccept the invite, and not all of us have the browser open all the time to either except  or decline the invite. I already had this issue with a user. They had to remove the folder I had shared with them as they messed up on the path. They the had to be around to except the invite again. Same happened to me actually. I messed p in creating a folder path and the user had to re-add me and I had to be around to reaccept the invite.

I realize why this can be dangerous. However most of my folders are send only so for me it won't really matter at least on those.

**Comment by AudriusButkevicius** [comment]
Reshared locally, remote sides have already accepted that share, so you shouldn't need to do anything, as the folder would just disappear and reappear.

Regardless, you should have started a discussion on the forum before opening  an issue, as the issue ticket explains, and this discussion should happen on the forum (for educational purposes for others in the future if anything).

**Comment by marrie** [comment]
Woops, my bad, actually we they had to re-accept the invite for some reason, I was on the phone helping them and they did have to do everything again from scratch, this includes accepting the folder to reentering the path, they messed up so I re-added their computer to the folder, they could not modify the path on their end and when I messed up I had to redo everything as they had to remove the folder and then re-add it. What concerned me was the folder id was different so the person and I had two dupes of everything we had  done. We got it working but it took 4 hours to get it straightened. I'll post more on the forums, maybe someone there has an idea.

**Comment by jebeld17** [comment]
I agree with @marrie 's original stance:
Folder paths should be editable. If I can delete and re-add a folder in Syncthing, why can't that process just be (at least) automated as an "edit path" option?
This would bring the amount of steps for the user to take down and helps new users take advantage of a feature otherwise unknown by common folk users.

**Comment by AudriusButkevicius** [comment]
Feel free to make a pull request.

**Comment by jebeld17** [comment]
Thank you, @AudriusButkevicius
