### ISSUE TITLE
Syncthing not restarting after auto-update [Windows]

### ISSUE THREAD

**Issue by unfa** [syncthing/syncthing#4212]
I'm managing a bunch of Syncthing-synced clients at my work office. The host is running Linux and it's fine (I use that machine all the time) but sometimes the Windows clients don't go up after auto-update and I need to restart them manually.

I have installed it manually in C:\Syncthing\syncthing.exe on these machines, and added a shortcut to Windows' **shell:startup** folder.

This usually works, but every once in a few weeks (or months) I need to go, hit Meta+R key, type in shell:startup, and run that shortcut manually. I suspect automatic Syncthing updates to be the cause.

This isn't a huge problem as long as all the machines are in my reach and I can manually restart it, but soon I'll be also installing it on remote machines I will never have physical access to, and calling these people in foreign countries to say "open this, click that and you'll be good" isn't going to be a nice thing to do. I'd like to make sure it will "just work" no matter what. If i't's even possible. Maybe I'll have to leave that shortcut in their menu aswell and just instruct them to run it if things don't work.

It's hard for me to pinpoint the problem. Have anybody had similar experience?

### Version Information

Syncthing Version: below v0.1.3
OS Version: Windows 8 and 10.

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.

**Comment by unfa** [comment]
Thank you. Sorry for misplacing my question.
