### ISSUE TITLE
Feature: Improve syncthing behaviour after wake from sleep

### ISSUE THREAD

**Issue by tytgatlieven** [syncthing/syncthing#4214]
Dear

It has come to my attention that syncthing seems to restart entirely when my (linux) system wakes from sleep. The problem is that this consumes a significant amount of time and battery on my laptop (about 10 min. of high cpu while doing a full rescan of my files (about 3 million files in about 600GB using inotify in order to avoid rescans). Hence my laptop consumes more energy when going to sleep then remaining awake when sleeping for less than 30min, which kind of beats the purpose ;-).
I was wondering if something can be optimised here, and think the following.
My feeling says that the full rescan shouldn't be needed since the last state before sleep is identical to the state when awaking. However, all connections will need to be restarted.
So most likely we need the following infrastructure in place:
1) Detection of resume from sleep
2) Restart all connections to other syncthing devices (ideally the moment network connectivity returns)
3) Do not restart the database and database scan.

I have no idea about the implementation complexity of this feature, nor it's priority. 
Hence feedback is certainly welcome!

**Comment by AudriusButkevicius** [comment]
There are other things that just that, discovery caches, upnp and potentially a ton of other things

**Comment by scienmind** [comment]
@tytgatlieven  I've been having a similar problem - ST restart is very heavy process, and it's very inconvenient for mobile devices. 
There has been some [discussion](https://forum.syncthing.net/t/question-about-restartonwakeup-setting/2222/8) about this on the forum. Long story short, you can disable ST from restarting on wake-up by unchecking `Advanced Configuration -> Options -> restartOnWakeup`. 

There are some stability risks with it, I'm using it on one of my laptops for about a year now, and haven't had any major issues related to it so far.

**Comment by AudriusButkevicius** [comment]
Actually, I am closing this as the option not to do this is already there. You can deal with the consequences of choosing not to restart.
