### ISSUE TITLE
Feature to Ignore certain files or folder

### ISSUE THREAD

**Issue by azzamsa** [syncthing/syncthing#4222]
it would be nice if syncthing has a feature like .gitignore, so we can exclude certain files inside sync folder to be syncronized

**Comment by canton7** [comment]
https://docs.syncthing.net/users/ignoring.html

**Comment by AudriusButkevicius** [comment]
It's also visible/editable from the UI.

**Comment by azzamsa** [comment]
I just realize that the fist time creating folder, I immediately have .stignore file.

maybe I am too motivated to give ideas without fully reading manuals.
sorry, and thanks lot for your contribution.

 thanks lot.
