### ISSUE TITLE
Wrong port forwarding causes ID issues

### ISSUE THREAD

**Issue by Efinr** [syncthing/syncthing#4223]
I have 2 Syncthing Nodes on my internal private network (let's call them 'A' and 'B') and 1 somewhere on the internet ('C').
'A' is internally linked to 'B' and only 'B'.
Node 'C' is supposed ask to link to 'B', but is not yet linked.
'B' has relaying turned off and the Syncthing-Port (22000/TCP) is forwarded. However it is forwarded to 'A', not 'B'.
'C' now tries to link to 'B' (with 'B's ID) but the message instead appears on the WebGUI of 'A' (who can see 'C's ID and accept it as a known device). 'B' does not show any message.

And when 'B' is asking to link to 'C', it is appearing as 'A'. (The WebGUI of 'C' shows the ID of 'A'.)
The two ('C'->'B' & 'B'->'C') can happen at the same time with 'B' showing up as 'A' and 'A' snatching the link requests for 'B'.
I have not tested, wether 'A' could actually start syncing data while "impersonating" 'B'.

The versions are: v0.14.29 (for 'A' and 'C') & v0.14.30 (for 'B' and 'C')

**Comment by AudriusButkevicius** [comment]
Sounds like the Henny Youngman problem.
No, impersonating is not possible as the ID comes from the certificates that are used for encryption.
