### ISSUE TITLE
Recreate missing folder marker and rebuild folder content

### ISSUE THREAD

**Issue by BengaloBongali** [syncthing/syncthing#4225]
I haven't found a way to recover a Syncthing setup in a convenient way. As far as I can tell, I'd need to restore the Syncthing config and all synced folders _with their content_. Does this really make sense as they're still present on devices I shared them with? Wouldn't it make more sense to restore the Syncthing config, create new folders and have Syncthing say "Folder marker missing", "Rebuild folder from devices x, y, z?", "Are you sure? This will overwrite all the content of /path/to/folder/!"?

**Comment by AudriusButkevicius** [comment]
Removing and readding (or just adding depending on what you botched) the folder is enough.

**Comment by AudriusButkevicius** [comment]
Also, please read the issue template. Discussions belong on the forum.

**Comment by BengaloBongali** [comment]
What would I restore the config for, if I set up all folders configurations again manually?

**Comment by AudriusButkevicius** [comment]
If you want to have a discussion, use the forum.

**Comment by AudriusButkevicius** [comment]
For those who care about this going forward: https://forum.syncthing.net/t/recreate-synced-folders-after-data-loss/10423
