### ISSUE TITLE
gui: Show device completion in bytes

### ISSUE THREAD

**Issue by dschrempf** [syncthing/syncthing#4227]
Hi,

this might have been discussed already somewhere here, but various searches did not give anything useful.

When uploading data to another (e.g., headless) machine, it is very hard to find out how much data (e.g., in MB) is still out of sync. Especially, when a lot of data is being synced and more data is added. Then, the `Remote Devices` panel shows `Syncing (99%)` or `Syncing (100%)` for hours (especially when the connection is slow). It may be much more informative to write the percentage and also the amount of data, e.g., `Syncing (99%), 100 MB out of sync`, or something better.

Thanks,
Dominik

**Comment by calmh** [comment]
We added this to the folders on the left side when receiving data so I see no particular reason not to do it for remove devices as well. 👍
