### ISSUE TITLE
Sync through NAT without upnp?

### ISSUE THREAD

**Issue by Readon** [syncthing/syncthing#423]
btsync could sync even when one of server is behind a NAT without upnp.
upnp is not always available under some circumstances.
As btsync's alternatives it seems that syncthing could not sync server behind NAT.
Is that possible to support this feature in near future?

btw, DHT or KAD are stable method applied in many freeware, which seems promising.

**Comment by daniele-athome** [comment]
That's sad to know... I have a notebook behind corporate router (free outgoing access, but no UPnP) and a mobile phone in a 4G network apparently behind router too (network interface shows a different IP address than the one shown from whatismyip.com). Port forwarding isn't possible in both cases. I had to use a "mid-way server" which can be reached by both devices to make them sync, but whatever...
I see how TCP hole punching isn't very easy and doesn't always work... but in such situations (which is very common) it would be of great help.

**Comment by jzupka** [comment]
I have same problem with connection behind routers which are not under my control. It would be nice to have this possibility. I really like syncthing ;-) It looks like very promising project.

**Comment by invernizzie** [comment]
Hi. Is this supported now? I just installed syncthing at home and at work. The latter is under NAT, I have no power over port forwarding. I think UPnP at work should be enabled, will troubleshoot later. But if it isn't, are there any hopes of syncing that box somehow?

**Comment by jpjp** [comment]
Try the beta. It supports proxying :)

**Comment by invernizzie** [comment]
Thanks! I just found out about 0.12 after writing this comment, but
wouldn't know where to download a build from...

2015-09-28 8:34 GMT-03:00 jpjp <notifications@github.com>:

**Comment by wweich** [comment]
No need for proxying / relay, if at least one router is under your control.

For two Syncthing nodes to be able to connect, at least one needs to be able to connect to the other.
So if your work router has no UPnP, no problem. Setup UPnP or manual forwarding at home and use global discovery so the two nodes can find each other. The office node will then connect to the home node and they both can sync.

**Comment by jpjp** [comment]
@invernizzie You can download it from https://github.com/syncthing/syncthing/releases You will need to upgrade all your nodes.
