### ISSUE TITLE
Sync a single file

### ISSUE THREAD

**Issue by abueide** [syncthing/syncthing#4230]
It would be nice if I could sync one off configuration files like my ~/.vimrc file with other devices.

**Comment by AudriusButkevicius** [comment]
Please read the docs or use the forum if you still have questions.

**Comment by abueide** [comment]
@AudriusButkevicius "Add a folder which has only one file, or use ignores." Isn't an acceptable solution because I have many files in my home directory, yet I only want to sync one configuration file. Is there some reason this isn't doable?

**Comment by AudriusButkevicius** [comment]
This is doable in the ways you already explained, and I don't see why this solution is not acceptable.
Anyways, I am locking this as discussions about features, being able to do things etc should happen on the forum.

Issue tracker is for bugs and features which have been fleshed out.
