### ISSUE TITLE
New "Archive" folder type.

### ISSUE THREAD

**Issue by grheard** [syncthing/syncthing#4231]
A folder that will send new and changed items to be sync'd, but not delete. Example: I have photos on my phone and they get sync'd, but if I delete some on the photos to free up space, the delete action does not get sync'd. Its more or less like 'Send Only' except the delete is ignored. This would allow for space limited devices like phones to continuously send new/changed files without the need to hang on to the item once sync'd.

I apologize if this can already be done. I couldn't find out how to make it happen.

**Comment by imsodin** [comment]
You can do it on the receiving side:
https://docs.syncthing.net/advanced/folder-ignoredelete.html

Please use the forum for support as the issue template suggests.
