### ISSUE TITLE
Bandwidth throttling appears to see NATed addresses as local

### ISSUE THREAD

**Issue by duk3luk3** [syncthing/syncthing#4235]
(Syncthing version 0.14.31-1 in arch linux)

I have set max send bandwidth to 50kB/s.

I enable a device and it connects via relay and adheres to the 50kB/s.

Some time later, it manages to use STUN / NAT-PMP / UDP to punch through / use the NAT and the connection changes to "tcp-server" type with the address of my home router. At that point, it stops adhering to the 50kB/s and goes over it (to 100 or 200kB/s).

If I set the `limitBandwidthInLan` option to `true`, this no longer happens, and the bandwidth restriction is respected.

This looks, walks and quacks like syncthing interprets the address as local and therefore ignores the max send bandwidth.

**Comment by calmh** [comment]
If the connection is from your home router, and your home router is in your LAN (obviously the case), then the connection is local. But I'm not sure what's going on here - I've never seen a NAT router rewrite the source address when doing port forwards in the incoming direction. Do you actually have a proxy? Or what's the thing?

**Comment by duk3luk3** [comment]
I have no idea, all I know is this is what I'm seeing:

```
Jun 29 12:53:37 Max syncthing[10929]: [LV3KP] INFO: Established secure connection to YR7SRPT-7QA4DBN-TXDXM5C-DGZX2YA-KOJUKLP-QAB6JWQ-RGM3FJG-V2GREAZ at 10.0.0.71:56700-103.247.154.59:22067 (relay-server) (TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305)
Jun 29 13:07:29 Max syncthing[19016]: [LV3KP] INFO: Established secure connection to YR7SRPT-7QA4DBN-TXDXM5C-DGZX2YA-KOJUKLP-QAB6JWQ-RGM3FJG-V2GREAZ at 10.0.0.71:22000-10.0.0.138:52966 (tcp-server) (TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305)
```

First line is using the relay, second line is using "the router". There's no proxy and the device is definitely not on my LAN.

**Comment by AudriusButkevicius** [comment]
That's definately a lan address so I don't see us doing anything wrong. I think its for you to work out how the address provided to us gets screwed up.
