### ISSUE TITLE
.stglobalignore file to be synced between nodes

### ISSUE THREAD

**Issue by kattunga** [syncthing/syncthing#424]
Add a new .stglobalignore file that works the same maner that .stignorefile but in this case the file is synced to other nodes.
The ignored patters are the concatenatios of both .stignore ans .stglobalignore files.

discussion 
https://discourse.syncthing.net/t/syncronize-stignore-file/557

**Comment by Hout** [comment]
For osx users, [mackup](https://github.com/lra/mackup) could help.
