### ISSUE TITLE
Error message not cleared, when error is cleared

### ISSUE THREAD

**Issue by bigbear2nd** [syncthing/syncthing#4240]
Hi!

I use SyncTrayzor with the start with windows option enabled.
I usually mount my (encrypted) drive after i start my pc, but that is mostly after syncthing finished its startup procedure. 

 - what happened:
I open SyncThing and see this notice:
![unbenansnt](https://user-images.githubusercontent.com/7719800/27701449-23dbe286-5d01-11e7-81f7-5cc65d145d22.png)
 - what you expected to happen instead:
See no error message, because there is no error.
 - any steps to reproduce the problem:
See above

### Version Information

Syncthing Version: v0.14.32-rc.1
OS Version: Windows 7 
Browser Version: SyncTrayzor

**Comment by AudriusButkevicius** [comment]
It's a notification, I think its working as expected and needs to be dismissed.

**Comment by calmh** [comment]
This is as designed, yes. If nothing else, seeing historic warnings may be of interest when you log in, to be aware that some funkiness has happened while you were away - even if the situation has been resolved.
