### ISSUE TITLE
Angular Error on load?

### ISSUE THREAD

**Issue by Haskaalo** [syncthing/syncthing#4241]
Hi I just installed syncthing via apt.syncthing and i replaced the ip in config file to 0.0.0.0 and now when i go to the url it show a blank page and multiple error about angular being not defined.

I figured out the first error that happen in the page is 

```angular.js:228 Uncaught SyntaxError: Unexpected identifier```

and after just some angular is not defined.

I've tried destroying cache and everything else. nothing happen. even in incognito mode.

**Comment by Haskaalo** [comment]
![chrome_2017-07-01_17-54-03](https://user-images.githubusercontent.com/7819295/27765684-6972496c-5e86-11e7-8e0a-190bf1cadd8c.png) this is the image

Also at angular.js:228 ![the line that is causing the error is that.](https://user-images.githubusercontent.com/7819295/27765689-94e8dbce-5e86-11e7-82d9-70673474452c.png)

**Comment by calmh** [comment]
Looks like a browser or connection issue. Proxies or antivirus on the machine where you do the browsing causing assets not to load? Please turn to the forum for the support as this is unlikely to be a bug; we’ll reopen here if that turns out to be the case.

**Comment by Haskaalo** [comment]
@calmh even tried in incognito mode, new browser and another computer.  It's just angular.js that seem to not work.

**Comment by calmh** [comment]
Nonetheless, I can't reproduce this, and judging from the lack of flood of identical complains neither can most other people. Which leads me to think it's something local to your setup.
