### ISSUE TITLE
relay server eats ram

### ISSUE THREAD

**Issue by khumarahn** [syncthing/syncthing#4245]
Hi, 

continuing https://forum.syncthing.net/t/relay-server-ram-memory-usage/10086/6 here.

I stopped the relay server with -SIGQUIT and here is the log file:
https://163.172.132.71/strelaysrv.log

**Comment by AudriusButkevicius** [comment]
The relevant leaking bit:

```
goroutine 465377 [IO wait, 309656 minutes]:
net.runtime_pollWait(0xb31ea2c8, 0x72, 0x131af000)
	/usr/lib/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).wait(0x1422f8f8, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).waitRead(0x1422f8f8, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x1422f8c0, 0x131af000, 0x1000, 0x1000, 0x0, 0x4f2a20, 0x10872004)
	/usr/lib/go/src/net/fd_unix.go:243 +0x1f0
net.(*conn).Read(0x10abfc30, 0x131af000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:173 +0xb8
bufio.(*Reader).fill(0x14d40510)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1c4
bufio.(*Reader).Read(0x14d40510, 0x11b2f400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:209 +0x22c
github.com/syncthing/syncthing/lib/tlsutil.(*UnionedConnection).Read(0x1537c4c0, 0x11b2f400, 0x400, 0x400, 0x244, 0x0, 0x0)
	/var/tmp/portage/net-p2p/syncthing-0.14.11/work/syncthing-0.14.11/src/github.com/syncthing/syncthing/lib/tlsutil/tlsutil.go:153 +0x6c
crypto/tls.(*block).readFromUntil(0x1453d260, 0xb5545218, 0x1537c4c0, 0x5, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:476 +0xc8
crypto/tls.(*Conn).readRecord(0x1186f600, 0x16, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:578 +0x20c
crypto/tls.(*Conn).readHandshake(0x1186f600, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:929 +0xa0
crypto/tls.(*serverHandshakeState).doFullHandshake(0x143658e0, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/handshake_server.go:447 +0xa74
crypto/tls.(*Conn).serverHandshake(0x1186f600, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/handshake_server.go:86 +0x280
crypto/tls.(*Conn).Handshake(0x1186f600, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:1262 +0x3b0
main.protocolConnectionHandler(0x4f5588, 0x1537c4c0, 0x1089aea0)
	/var/tmp/portage/net-p2p/syncthing-0.14.11/work/syncthing-0.14.11/src/github.com/syncthing/syncthing/cmd/strelaysrv/listener.go:62 +0xdc
created by main.listener
	/var/tmp/portage/net-p2p/syncthing-0.14.11/work/syncthing-0.14.11/src/github.com/syncthing/syncthing/cmd/strelaysrv/listener.go:52 +0x420
```

**Comment by khumarahn** [comment]
Thanks a lot! I updated, and will let you know if I see something is wrong :-)

**Comment by khumarahn** [comment]
@AudriusButkevicius 

I have been running the version with the patch for some time, and I see a steady increase of consumed ram. I logged RES every hour for around 300 hours, and plotted a graph:
![st r](https://user-images.githubusercontent.com/5206045/29671731-301d3632-88e2-11e7-864d-0b58882e4e54.png)


(every data point is RES in megabytes, each hour there is a new point)

**Comment by AudriusButkevicius** [comment]
Great. Can you send a SIGQUIT and capture the stacktraces again?

**Comment by khumarahn** [comment]
Sure. I have put it again here: https://163.172.132.71/strelaysrv.log

**Comment by AudriusButkevicius** [comment]
So I can't see any go routines leaking.
There are around ~1k subscribers in the relay (allowing things to connect to) and around ~300 active sessions (where exchanges are actually happening), so perhaps the growth is just an effect of more people using your relay, or are you seeing memory growth without client growth?

**Comment by calmh** [comment]
Maybe we could add http/pprof to the build, if it's not already there, so we can take a memory profile.

On 24 Aug 2017, at 23:36, Audrius Butkevicius <notifications@github.com<mailto:notifications@github.com>> wrote:


So I can't see any go routines leaking.
There are around ~1k subscribers in the relay (allowing things to connect to) and around ~300 active sessions (where exchanges are actually happening), so perhaps the growth is just an effect of more people using your relay, or are you seeing memory growth without client growth?

**Comment by AudriusButkevicius** [comment]
If the OP can chart clients + sessions, I think that would be easier. Adding a second http server/third socket to this thing sounds a bit sad.

**Comment by khumarahn** [comment]
I did not do any analysis, only logged the consumption of ram.

Now I restarted the relay and started a script which will collects every hour `bytesProxied`, `numActiveSessions`, `numConnections`, `numPendingSessionKeys`, `numProxies`.

Expect a graph in a week or two :-)

**Comment by khumarahn** [comment]
A graph for the first 4 days after the restart:
![st](https://user-images.githubusercontent.com/5206045/29874814-cab8fc56-8d8f-11e7-8909-8d6413a8d14b.png)
To be continued.

**Comment by AudriusButkevicius** [comment]
The correlation looks good to me?

**Comment by khumarahn** [comment]
yes, very good. I will keep it running for at least a couple of weeks, as intended. Probably, indeed, the RAM consumption is high just because of the number of clients served.

**Comment by calmh** [comment]
So as a very rough estimate we have about 100 MB / 700 sessions ~= 146 KiB with 100% GC overhead => ~70-75 KiB per session. I'm guessing most of that is buffers, maybe 2 * 4 KiB goroutine stacks or so. It's possible we can reduce the buffer usage somewhat for idle connections.

**Comment by AudriusButkevicius** [comment]
Tbh, I think its fine. We could do better by not spawning stuff right left and center, but imho this is good enough. I am closing this (as I suspect I will forger in the future), as I don't think this needs actioning now, but I'd love to see more charts from OP in the future to see if the trend persits.

**Comment by AudriusButkevicius** [comment]
H

**Comment by AudriusButkevicius** [comment]
God damn mobiles

**Comment by calmh** [comment]
>D

<img width="636" alt="screen shot 2017-08-30 at 15 54 33" src="https://user-images.githubusercontent.com/125426/29875903-8f1b866c-8d9b-11e7-9b1a-82c20a717398.png">

**Comment by calmh** [comment]
I'm actually going to keep this open and think a little bit about it. The resource usage above isn't insane but it's nice to keep it at a minimum so that the relay server can run "everywhere". At the minimum I'd like a real memory profile of where the usage is. Maybe it's all in the TLS stack and then we're done here.

**Comment by calmh** [comment]
@khumarahn Would you mind grabbing an strelayserv from here? https://build2.syncthing.net/viewLog.html?buildId=9909&buildTypeId=RelayServer_Build&tab=artifacts&guest=1

Then run it with `--pprof` to enable the built in profiler. Make sure the status server is also enabled (on `:22070` by default).

After a day or two, `curl -O http://localhost:22070/debug/pprof/heap` to grab a heap profile. Grab a couple. Post here or somewhere convenient?

**Comment by khumarahn** [comment]
I would really like to see the RAM consumption decrease. I am running the relay on scaleway's arm server with 2GB of ram, and the relay ends up using a significant portion of it. Popularity of syncthing grows, and the relay's load goes up...

**Comment by khumarahn** [comment]
@calmh sure! I did as you say and restarted the relay. 
http://163.172.132.71:22070/debug/pprof/heap 
will return in a couple of days

**Comment by AudriusButkevicius** [comment]
Hmm, yeah, that might store session keys and stuff. It won't be a problem as relays don't need to be secure, but someone might do denial of service by consuming all pending session keys.

**Comment by calmh** [comment]
@khumarahn Here's an update with one minor leak fixed, and one buffer sized tweaked, based on your profiling data. Please try it, and keep it running as before. :)

https://build2.syncthing.net/latest#Relay-Server (easier url)

**Comment by khumarahn** [comment]
just restarted with the new version

**Comment by calmh** [comment]
I think we're about done with this. After the fixes yesterday it looks quite reasonable to me:

```
jb@unu:~/s/g/s/syncthing $ curl -s http://163.172.132.71:22070/status | grep numConn
    "numConnections": 266,
jb@unu:~/s/g/s/syncthing $ go tool pprof http://163.172.132.71:22070/debug/pprof/heap
Fetching profile over HTTP from http://163.172.132.71:22070/debug/pprof/heap
Local symbolization failed for strelaysrv: open /usr/libexec/syncthing/strelaysrv: no such file or directory
Some binary filenames not available. Symbolization may be incomplete.
Try setting PPROF_BINARY_PATH to the search path for local binaries.
Saved profile in /Users/jb/pprof/pprof.strelaysrv.alloc_objects.alloc_space.inuse_objects.inuse_space.010.pb.gz
File: strelaysrv
Type: inuse_space
Time: Aug 31, 2017 at 8:26am (CEST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 4615.18kB, 100% of 4615.18kB total
Showing top 10 nodes out of 23
      flat  flat%   sum%        cum   cum%
    2050kB 44.42% 44.42%     2050kB 44.42%  crypto/tls.(*block).reserve /usr/local/go/src/crypto/tls/conn.go
    1028kB 22.27% 66.69%     1028kB 22.27%  bufio.NewReaderSize /usr/local/go/src/bufio/bufio.go (inline)
     513kB 11.12% 77.81%      513kB 11.12%  main.(*session).proxy /opt/buildagent/temp/buildTmp/syncthing-7adb0302/src/github.com/syncthing/syncthing/cmd/strelaysrv/session.go
  512.14kB 11.10% 88.91%   512.14kB 11.10%  crypto/cipher.NewGCMWithNonceSize /usr/local/go/src/crypto/cipher/gcm.go
  512.03kB 11.09%   100%  3074.17kB 66.61%  main.protocolConnectionHandler /opt/buildagent/temp/buildTmp/syncthing-7adb0302/src/github.com/syncthing/syncthing/cmd/strelaysrv/listener.go
         0     0%   100%     1028kB 22.27%  bufio.NewReader /usr/local/go/src/bufio/bufio.go
         0     0%   100%   512.14kB 11.10%  crypto/cipher.NewGCM /usr/local/go/src/crypto/cipher/gcm.go
         0     0%   100%  2562.14kB 55.52%  crypto/tls.(*Conn).Handshake /usr/local/go/src/crypto/tls/conn.go
         0     0%   100%  1537.50kB 33.31%  crypto/tls.(*Conn).readHandshake /usr/local/go/src/crypto/tls/conn.go
         0     0%   100%  1537.50kB 33.31%  crypto/tls.(*Conn).readRecord /usr/local/go/src/crypto/tls/conn.go
(pprof) 
```

That is, it accounts four megs of "live" heap for 266 connections at the moment. My PR above will remove one more of those four megs (unnecessary buffering), the rest is essentially TLS state keeping and our connection structures, which are necessary.

**Comment by calmh** [comment]
@khumarahn Final-ish attempt: https://build2.syncthing.net/latest#Relay-Server (#40 or newer)

**Comment by khumarahn** [comment]
Looks very good, thanks a lot! I restarted with <span>#</span>41, will continue observations.

**Comment by calmh** [comment]
```
jb@unu:~ $ curl -s http://163.172.132.71:22070/status | egrep numConn\|uptime
    "numConnections": 379,
    "uptimeSeconds": 161393
jb@unu:~ $ go tool pprof http://163.172.132.71:22070/debug/pprof/heap
...
Type: inuse_space
...
Showing nodes accounting for 5634.80kB, 100% of 5634.80kB total
Showing top 10 nodes out of 44
      flat  flat%   sum%        cum   cum%
 2048.24kB 36.35% 36.35%  2048.24kB 36.35%  math/big.nat.make /usr/local/go/src/math/big/nat.go (inline)
    1025kB 18.19% 54.54%     1025kB 18.19%  crypto/tls.(*block).reserve /usr/local/go/src/crypto/tls/conn.go
 1024.44kB 18.18% 72.72%  2561.78kB 45.46%  crypto/tls.(*Conn).readHandshake /usr/local/go/src/crypto/tls/conn.go
  512.75kB  9.10% 81.82%   512.75kB  9.10%  encoding/pem.Decode /usr/local/go/src/encoding/pem/pem.go
...
```

I think we're done here. 👍 Usage from the outside looks reasoanble, mostly attributable to TLS stuff.

**Comment by khumarahn** [comment]
![st](https://user-images.githubusercontent.com/5206045/30030450-3985fb2c-9185-11e7-92b9-47ca7af7e4d6.png)

This is a new 4-day graph. The memory footprint is like 4 times less. A very good job!

**Comment by MikeLund** [comment]
"Relay server RAM usage has been reduced" is an understatement. strelaysrv can run very comfortably with just 256 MB RAM now, whereas before it started to swap :) Nice work!

**Comment by khumarahn** [comment]
Everything is well after three weeks, 1.4TB relayed. Here is the graph:
![st](https://user-images.githubusercontent.com/5206045/30749857-645afdf2-9fbd-11e7-8757-0e377a4509de.png)

**Comment by khumarahn** [comment]
![st](https://user-images.githubusercontent.com/5206045/32184065-fdce83ee-bd92-11e7-9e75-a825b4acc74c.png)
There has been something strange around two weeks ago, when the number of connections dropped. Other than that, everything is fantastic without a restart for 2 months already. I will stop monitoring soon.

**Comment by calmh** [comment]
I bet the connections drop is a new release, with auto upgrades rolling out.
