### ISSUE TITLE
Syncthing doesnt sync latest change in sync folder.

### ISSUE THREAD

**Issue by CaptainKhan** [syncthing/syncthing#4247]
Even though it works sometimes, other times when deleting a file from the sync folder and forcing a folder rescan does not result in synching indicating the last change, which was deleting a file.

In addition -rw owner permission file changes are not detected on SFOS file system. The file requires owner and group -rw permission rights which i believe to be an error.

**Comment by calmh** [comment]
Are you saying the delete is handled properly but just not shown somewhere? What's an SFOS filesystem?

**Comment by AudriusButkevicius** [comment]
Regardless, the OP should have read the issue template and started a thread on the forum first.

**Comment by calmh** [comment]
Lacks info
