### ISSUE TITLE
syncthing refuses to sync

### ISSUE THREAD

**Issue by sea-don** [syncthing/syncthing#4251]
I have a windows 7 PC that syncs fine with 7 other PC's in different geo-locations

I added a new windows 10 remote device to sync to

It sees the device, it connects... but it wont sync

i checked the firewall on the win 10 remote device its all OK

it shows the connection directories are shared I can rescan on both PC's but not sync.  It says its syncing but only gives 0%

cant figure it out... tried removing and adding the devices again, restarting syncthing, re-scanning directories... even reinstalled syncthing on the remote PC... just teh same issue wont sync no data going across

**Comment by sea-don** [comment]
tried turning off compression.. no change

**Comment by sea-don** [comment]
FYI both folders show the number of folders, files and amount of data so teh folder paths are correct also the file number varies slightly indicating they are out of sync

**Comment by calmh** [comment]
Please use the forum for support.
