### ISSUE TITLE
Feature: Reset Database, Reset Deltas next restart in GUI

### ISSUE THREAD

**Issue by DrSchnagels** [syncthing/syncthing#4254]
I often have to reset the delta database because my Android phone shows the 95% or the 100% problem.
It's not working properly to reset the database within the Android app (actually it does not work at all atm, even after reseting it, i still have the 95% problem).

So Id love to have a option to reset the whole database and the deltas for the next restart in the GUI.
I have to reset the deltas several times a month because there are always tiny inconsistencies between my pc and server at home.

Thanks!

**Comment by AudriusButkevicius** [comment]
Resetting anything shouldn't be required in general. The inconsistencies and what not are most likely caused by something else. I suggest you look at the causes of inconsistencies instead of asking for a nuclear option that doesn't fix the underlying issue.
