### ISSUE TITLE
Log file grows too large

### ISSUE THREAD

**Issue by MasterDimmy** [syncthing/syncthing#4255]
C:\Users\sync\AppData\Local\Syncthing\syncthing.log   takes over 212GIG of size!

restarting syncthing didnt help - it just add new lines to the end of it:
[WZN7G] 14:59:47 INFO: Connection to xxxx-xxxx-xxx
n existing connection was forcibly closed by the remote host.
[WZN7G] 15:00:00 INFO: Restarting
[WZN7G] 15:00:00 INFO: Disconnected from relay relay://......
[WZN7G] 15:00:00 INFO: Exiting
[WZN7G] 15:00:01 INFO: syncthing v0.14.31 "Dysprosium Dragonfl....
[WZN7G] 15:00:01 INFO: My ID: xxxx-xxx-xxx
[WZN7G] 15:00:02 INFO: Single thread SHA256 performance is 128....
[WZN7G] 15:00:02 INFO: Hashing performance with weak hash is 1....
[WZN7G] 15:00:03 INFO: Hashing performance without weak hash i....

It needs ability to rotate syncthing.log:
1. After restarting
2. During work! Because before it, server was uptime 4 month, so i got 212gigs of log during runtime!

Syncthing Version: v0.14.31
OS Version: Windows 7 
Browser Version: -

**Comment by calmh** [comment]
Sorry for the lack of response. This looks like a genuine bug. There is a lack of log rotation, but the log is supposed to start from zero on each restart.

**Comment by calmh** [comment]
Had this computer been running for a long time and without auto upgrades? Because I can't reproduce this, *but* the thing is that the log is only truncated when the monitor process restarts, which happens when syncthing is started for the first time from the outside (but not when "restart" is used in the GUI), or when the upgrade process does an upgrade...

**Comment by MasterDimmy** [comment]
Log becomes big because of many messages of this types:
1) Cant remove file\folder - because it is not present on the server
2) A lot of syncthing access errors because of symlinks in subpathes of sync directories.

I have 10 big (huge) folders with many files in it.
So Syncthing tries to do 1 & 2 again and again, so it fills its log with pretty good speed.

To reproduce this you should have large folders but in some access error or missed files, or symlinks in them, so it will be something that syncthing will write to log. It helps to reproduce.

**Comment by MasterDimmy** [comment]
How i solved it now? Just added to schedule kill syncthing, remove log, restart syncthing...

**Comment by MasterDimmy** [comment]
And there 2 separate runs of syncthing from one path
C:\soft\syncthing.exe , but with 2 windows users sync1 and sync2.
This helps to do local raid (backup) from 1 syncthing to other with single exe. Maybe this denyied one of them to erase log file because it was busy, but thye both can append data to it.

And yes, we need log  rotation.

**Comment by calmh** [comment]
Having recurring errors that aren't rectified one way or the other will cause a lot of log errors. This is expected. You should fix the cause of those errors to begin with.
