### ISSUE TITLE
Attempt TCP hole punching

### ISSUE THREAD

**Issue by Sepero** [syncthing/syncthing#4259]
Myth-
Two Nat'd devices can't directly communicate with each other.

Reality-
Most Nat'd devices can directly communicate over TCP or UDP, if given the proper instruction.

Test Example Run with Netcat:
On Nat'd System 1

    pc1$ nc -p 64000 $ip_of_pc2 64000

On Nat'd System 2

    pc2$ nc -p 64000 $ip_of_pc1 64000

Using this on most NAT networks, these two NAT'd computers will immediately be able to start communicating 100% directly with each other. (Test it for yourself.) The only thing they require is a discovery service to inform each of them what the others IP address is.

I'm asking this hole punching technique be implemented in the code of Syncthing (hopefully as a module, so that it can replicated easily in other OSS projects). This should dramatically lighten the load on relay's and boost network transfer speeds.

If Jakob (calmh) also believes this would be a good idea to implement, then I will immediately bountysource this for $200. And perhaps others will pitch in as well.

**Comment by AudriusButkevicius** [comment]
There is a ticket for reliable UDP which was closed after KCP support was merged. It's an experimental implementation that is not yet enabled by default yet, if you want to enable it, add kcp://0.0.0.0:22070 in listen addresses on both sides. It has the tendency not to reconnect after disconnection though, hence not enabled by default.

**Comment by calmh** [comment]
This is TCP simultaneous open and, while neat in theory, it's tricky to get to work well in practice with the timing requirements. However I would be very happy to be proven wrong and see this work well in the wild. A fairly simple test is to hack the source port selection in the dialer.

**Comment by AudriusButkevicius** [comment]
TCP hole punching is pretty much impossible in practice, as it's stateful, and routers costing more than 10$ are aware of handshake packets and state of the connection. NATs deliberately map different WAN ports to prevent this.

**Comment by Sepero** [comment]
> reliable UDP which was closed after KCP support was merged

That's great news, and definitely something for me to investigate further.

> TCP hole punching is pretty much impossible in practice, as it's stateful, and routers costing more than 10$ are aware of handshake packets and state of the connection

I believe that you wrong in your assumption here, but I don't want to debate or "win" on this point. I value your assessment AB, and I am completely open to criticism. Sure it probably won't work on expensive corporate networks, but my guess is that most people are using Syncthing on home networks. I personally own a $400 router, and the simple Netcat trick in top post is able to make TCP connection through it. I do part-time IT work, and every home router I've ever tested has been able to make connection with that simple Netcat trick.

Calmh is correct that there is a trick with TCP, that the timing on both ends need to attempt connect/communication within about 30 seconds of each other. If they don't make it in time, then the source port could be closed for a couple minutes by the router. (Another source port could be used while waiting)

Taking into consideration everything what's been offered here, it seems the best resolution to this issue might be to improve KCP so that it has reliable (TCP-like) functionality. Perhaps a sort of KCP "ping" every X seconds, to verify that the connection is still alive. Upon "ping" fail, then attempt discovery/reconnect.

Does this KCP "ping" sound like a good solution? I would be willing to close this issue, and reopen one for KCP improvement, and donate to that issue. In my humble opinion, the goal of reliable NAT2NAT connection is important, but the method to reach that goal should be whatever makes the most sense.

**Comment by AudriusButkevicius** [comment]
Kcp has pings and what not and it should mostly work. There is some problem that leaks state that causes the issue I've described, but I have not had a chance to look into it.


Every router I ever used never had predictable port assignment which is a prerequisite for tcp hole punching.

**Comment by ishitatsuyuki** [comment]
I think NAT traversal over TCP is indeed possible: libp2p (IPFS) has already implemented one: https://github.com/libp2p/go-libp2p-nat

Maybe we can incorporate libp2p over the time as IPFS and Syncthing use the same language (Go), and both aims at decentralized file transfer.

**Comment by AudriusButkevicius** [comment]
libp2p-nat does NAT traversal via UPnP and NatPNP which we already do

TCP hole punch through requires https://github.com/golang/go/issues/9661
I've looked what IPFS folks have for TCP punch through, and it's incredibly ugly, so I'd better wait for the above ticket to be closed before we attempt this.

**Comment by srados** [comment]
> libp2p-nat does NAT traversal via UPnP and NatPNP which we already do
> 
> TCP hole punch through requires [golang/go#9661](https://github.com/golang/go/issues/9661)
> I've looked what IPFS folks have for TCP punch through, and it's incredibly ugly, so I'd better wait for the above ticket to be closed before we attempt this.

@AudriusButkevicius fyi, I just checked and the golang issue is closed.

**Comment by AudriusButkevicius** [comment]
Yes, and there is already a PR fixing it syncthing side, but other maintainers are too lazy to review it so :man_shrugging:

**Comment by srados** [comment]
yeah, I see it now... :(
