### ISSUE TITLE
Local Versioning

### ISSUE THREAD

**Issue by Ivanca** [syncthing/syncthing#4261]
Without local versioning this is not an alternative to Dropbox and that should be stated up front in the website of both syncthing and synctraizor. That's the main feature I (and many) used Dropbox for.  I had to install it and configure just to realize after few weeks that "Staggered File Versioning" actually means "Staggered File Versioning **Of Remote Changes Only**".

**Comment by calmh** [comment]
We cannot do local versioning, as this would imply grabbing a copy of the file before you changed it, in response to you changing it.
