### ISSUE TITLE
Should auto-dismiss Warning notifications when no longer applicable.

### ISSUE THREAD

**Issue by taigrr** [syncthing/syncthing#4262]
- what happened,
I started Syncthing with one of my external drives unplugged, and got the notification saying "2017-07-17 18:57:15: Stopping folder "FNAME" (device-remFolder) - folder path missing. When I plugged the drive back in, the syncing notification showed it was up to date (after downloading a few changed files) but the notification remained
 - what you expected to happen instead, 
 Since the warning is no longer applicable, auto-dismiss this warning!
 - any steps to reproduce the problem.
It's pretty self explanatory.

It's possible that retaining a log of "folder path missing" events is a good feature, but this sort of thing is probably best kept in a database of logs somewhere and not shown in the GUI unless the user is looking for it specifically, as for the average user, seeing this notification persist after fixing the folder path error can seem confusing.

I can add a screenshot if it helps, but I think it's clear enough from my description.

### Version Information

v0.14.32, Windows (64 bit) 
"Dysprosium Dragonfly"
Google Chrome 
59.0.3071.115 (Official Build) (64-bit) (cohort: Stable)

**Comment by AudriusButkevicius** [comment]
An exact same issue was closed recently explaining that it's working as intended.

**Comment by calmh** [comment]
For clarity, #4240.

*All* Syncthing warnings are of the type "hey, you know, this happened" and not "this is an ongoing situation".

**Comment by bigbear2nd** [comment]
> All Syncthing warnings are of the type "hey, you know, this happened" and not "this is an ongoing situation

I want to point out, that only the first 5 issues are shown. Any more issues are never revealed. ( I have 10 shares like this. If i don´t dismiss the error early, I might never see the new issue) 
That behavior is ok for me, but might be irritating for others.

**Comment by calmh** [comment]
Pretty sure it's the *last* five, but yes.
