### ISSUE TITLE
Manually specified listen address in GUI still reported as dynamic in INFO log

### ISSUE THREAD

**Issue by danbo** [syncthing/syncthing#4267]
Not much more to say.. In the GUI, I changed the "Sync Protocol Listen Address" from

**default** 

to

**tcp://0.0.0.0:22000**

because I didn't want 

**dynamic+https://relays.syncthing.net/endpoint** as part of **default**

yet the INFO log still shows

... INFO: Device BLAH-BLAH-KEY is "DEVICE_ID" at [**dynamic**]

It wasn't until I changed it in the **advanced settings** under device "**addresses**" option that it finally started showing

... INFO: Device BLAH-BLAH-KEY is "DEVICE_ID" at [**tcp://0.0.0.0:22000**]

**Comment by calmh** [comment]
The two settings are different. You changed your listen address, but the log entry talks about the address configured *for that device*, which was still `dynamic` until you changed that as well.
