### ISSUE TITLE
Stale state info with "Send only" changes?

### ISSUE THREAD

**Issue by danbo** [syncthing/syncthing#4268]
Android client C
Ubuntu Syncthing server S

1. C syncs an empty folder F to S with option **Send Only**
2. Two files appear in F on C- file1.txt and file2.txt
3. Files are **correctly synced** to S
4. C deletes file1.txt and renames file2.txt to new_file.txt
5. Files are **correctly synced** to S (file1.txt deleted and file2.txt renamed) - Global changes in UI on S correctly reflects this as well.

**Issue: Metadata appears to be stale**
1. Native Android GUI on C under folders for F still shows 2 / 2 Files and xx KiB/yy KiB
2. **Web Gui** on C under metadata for F's **Global** and **Local** State shows 2 files
3. **Web Gui** on S under metadata for F's **Global** and **Local** State shows 2 files

Why has the state info not been updated to show 1 file in all three places? Even after I've hit rescan multiple times and restarted C and S instances?

**Comment by calmh** [comment]
Are you sure there isn't a second file, possibly a hidden one?

**Comment by danbo** [comment]
Good call, there was an unexpected hidden file in the folder.
