### ISSUE TITLE
Make use of filesystems that can handle copies efficiently. 

### ISSUE THREAD

**Issue by lemmi** [syncthing/syncthing#4271]
## Context

Copy-on-Write filesystems like btrfs, aswell as some network filesystems (smb, nfs, probably more, s3 has apis aswell,) can make copying more efficient with

1. only referencing data instead of copying (deduplication)
2. "Server side copies" (no need to roundtrip the data to the client and back to the server).

The first case will usually result in instant copies since it's only a metadata operation. The filesystem will take care that changes made to one copy won't affect the other. These are not to be confused with hardlinks!
The second case will benefit those that run syncthing on a network storage. The fileserver can be instructed to do the copy operation locally. Additionally the server can make use of the first case aswell.

Making use of deduplication (first case) has the potential to make file versioning very cheap in the sense that only new data will be written to disk. This is a common scenario if only metadata in image or music files is changed. Usually these types of files locate the data at the beginning of a file, then append the metadata (Exif, ID3 tags,...).

## Why?

I use staggered versioning and recently freed up about 100G of disk space by making use of this capabilities. There are tools like [duperemove][dupe] that can identify common datablocks and then rewrite the metadata of files to share common blocks. However this process involves scanning and hashing all files in question, comparing them and applying the metadata transformation afterwards. In my case this took several hours.

To make this work, almost every filesystem capable of such functionality needs to be instructed to do so.
Since syncthing already knows which blocks are shared by files and when files are copied, I'd like to make use of this knowledge right away.

## How?

For this to work seamlessly, it needs to be integrated in some form with the new Filesystem Interface #4228. This is currently WIP and I'd like to arrange for a compatible solution.
 
One option is to add another method that will mimic the syscall [copy_file_range(2)][CopyFileRange] to the Filesystem interface. But this will require every backend to actually implement this Method.

Another possibility is to have convenience function test for the capabilities and handle the fallback:

Add an interface filesystem backends should implement if they are capable of handling efficient copies:
```go
type FileRangeCopier interface {
    CopyFileRange(src File, srcoff int64, dst File, dstoff int64, length int) (n int, err error)
}
```
Then provide the function outside the Filesystem interface:
```go
package fs
// ...
func CopyFileRange(fs Filesystem, src File, srcoff int64, dst File, dstoff int64, length int64) (n int, err error) {
    // backend can do fast copy for us and do we want it?
    if frc, ok := fs.(FileRangeCopier); ok && cfg.Options.UseCopyFileRange {
        // Make use of the filesystem functionality
        return frc.CopyFileRange(...)
    }
    // Fallback to normal Copy
}
// Maybe add a shortcut if we want to copy a whole file
func Copy(fs Filesystem, src, dst File) (n int, err error) {
    return CopyFileRange(fs, src, 0, dst, 0, src.Size())
}
```

## Conclusion

As long as we can coordinate 

1. the addition of those convenience functions or the methods the the Filesystem interface
2. implementing all necessary fallbacks first
3. using them consistently throughout the code

I think this could be worthwhile for a couple of users right now and seeing how more filesystems adopt the CoW strategy ([XFS][xfs], [ReFS][refs], [AFS][afs]) this almost could reach almost everyone in a couple of years.

[dupe]: https://github.com/markfasheh/duperemove "Tools for deduping file systems"
[CopyFileRange]: https://manpages.debian.org/unstable/manpages-dev/copy_file_range.2.en.html "CopyFileRange"
[xfs]: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0cbbc422d56668528f6efd1234fe908010284082
[refs]: https://en.wikipedia.org/wiki/ReFS
[afs]: https://en.wikipedia.org/wiki/Apple_File_System

**Comment by calmh** [comment]
I think a `fs.File` probably only makes sense within it's `fs.Filesystem` and carries an implicit reference to it's creating `fs.Filesystem`, meaning that the `CopyFileRange` function doesn't need to take a parameter for the `fs`. Apart from that I think it's the proper solution. The `fs.File`s as currently envisioned in the other PR support both `io.ReaderAt` and `io.WriterAt` meaning `CopyRange` has a simple, generic implementation. It can then also check for the possibility of the source file supporting a `CopyFileRangeTo(...)` method or something like that.

**Comment by Ferroin** [comment]
FWIW, if someone can get a PR put together with this implemented, I can do cross-architecture testing of it on XFS and BTRFS (unfortunately, I don't have access to an NFS server that supports server-side copies, or any SCSI hardware that supports the XCOPY command).

Also, on the note of Linux specifically, I _think_ that copy_file_range(2) just works, even if the FS doesn't have specific handling for accelerating the copy, but I'm not certain about that.

**Comment by lemmi** [comment]
@Ferroin copy_file_range(2) handles the fallback, given the right flags (or just using the default 0). It will copy the file, but without moving everything through userspace. But we need to make sure to test for kernel versions 4.4+.

**Comment by calmh** [comment]
Note that when copying blocks we anyway read and hash the block to make sure we get what the database says we should expect, so any "not moving through user space" advantage doesn't apply to us at all. Don't expect this to be a win other than in the cases where you get space savings in the file system, and in those cases count on having to do both a read plus as a copy-range per block.

**Comment by Ferroin** [comment]
It would also probably be a win in cases where the files are on an NFS share that supports server side copies (one of the two required round trips to the server would be much smaller) or where the kernel takes advantage of data copy commands at the block device level (I'm pretty sure that copy_file_range(2) can translate to a SCSI XCOPY command if the block device supports it, which ends up avoiding not only userspace, but also kernel operations).  Both cases are of course not likely usage for normal users, but they will still likely see better performance.

The performance boost when reflinks are supported should still be significant though, even with the need to read and hash the block anyway, especially when dealing with devices that take longer to write than to read.

**Comment by tlhonmey** [comment]
Note also that NTFS supports a similar type of deduplication, but only via whole-volume sweep operations (as far as I can find anyway.)  As such integrating a call to the deduplicate mechanism would require a slightly different strategy (call when sync completed instead of per-file probably) and provide no noticeable speed benefits, but if the code can be structured to make doing so feasible then users could at least get the space-saving benefits when duplicate chunks are detected without having to regularly grovel over the whole file system looking for them when they don't exist.

**Comment by dmkoppelman** [comment]
Unpatched RHEL 8.1 has a dataloss problem using copy_file_range. I don't know whether syncthing will trigger it, but the potential damage is serious enough that one of the syncthing devs should look at https://bugzilla.redhat.com/show_bug.cgi?id=1803162 .

**Comment by calmh** [comment]
Noted. That's a kernel bug, so the solution seems to be to not enable this entirely optional Syncthing feature on such a system, or to upgrade the kernel.

**Comment by dmkoppelman** [comment]
> Noted. That's a kernel bug, so the solution seems to be to not enable this entirely optional Syncthing feature on such a system, or to upgrade the kernel.

Any user aware of the problem would have upgraded their kernel. The easiest thing for ST to do is to avoid using copy_file_range on RHEL 8.1 (the current version is 8.2). I would not take chances with silent data corruption.

**Comment by AudriusButkevicius** [comment]
We are going to start targeting and working around distro specific bugs.

Go itself will start using copy_file_range unconditionally in the next version, so sadly users will have to suck it up.

**Comment by AudriusButkevicius** [comment]
For people finding this ticket in the future.
This is now implemented as an optional configuration, but the default behaviour remains the same, copy data into application memory.

You can find the docs for the feature here: https://docs.syncthing.net/advanced/folder-copyrangemethod.html
