### ISSUE TITLE
0.14.33 noupgrade option attempts to escape Homebrew sandbox

### ISSUE THREAD

**Issue by ilovezfs** [syncthing/syncthing#4272]
```
==> ./build.sh noupgrade
runtime/internal/sys
go install runtime/internal/sys: mkdir /usr/local/Cellar/go/1.8.3/libexec/pkg/darwin_amd64_noupgrade: operation not permitted
exit status 1
exit status 1
```

The install method is
```
  def install
    ENV["GOPATH"] = buildpath/".syncthing-gopath"
    mkdir_p buildpath/".syncthing-gopath/src/github.com/syncthing"
    cp_r cached_download, buildpath/".syncthing-gopath/src/github.com/syncthing/syncthing"
    ENV.append_path "PATH", "#{ENV["GOPATH"]}/bin"
    cd buildpath/".syncthing-gopath/src/github.com/syncthing/syncthing"
    system "./build.sh", "noupgrade"
    bin.install "syncthing"
  end
```

See
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/5303/version=sierra/console
https://github.com/Homebrew/homebrew-core/pull/16034

No such issue with 0.14.32.

**Comment by AudriusButkevicius** [comment]
That happens only if no GOPATH is set I think.

**Comment by ilovezfs** [comment]
@AudriusButkevicius as you can see in the install method above, we explicitly set GOPATH:
```
ENV["GOPATH"] = buildpath/".syncthing-gopath"
```

**Comment by calmh** [comment]
This is not Go path, this is building the standard library with an install suffix based on tags. This is the go compiler wanting to write object files.

**Comment by DeX77** [comment]
I have a similar issue:

```
go run build.go -no-upgrade -version v0.14.33 build
runtime/internal/sys
go install runtime/internal/sys: mkdir /usr/lib/go/pkg/linux_amd64_noupgrade: permission denied
```
GOPATH is set

```
export GOPATH="$Fsrcdir"
```

**Comment by AudriusButkevicius** [comment]
@calmh it seems the noupgrade tag propagates to runtime somehow as `linux_amd64_noupgrade` doesn't look right.

**Comment by JoshStrobl** [comment]
I can also reproduce this using fakeroot in solbuild for Solus (Linux). We set a GOPATH (GOPATH=/home/build/YPKG/root/syncthing/build), this has worked in prior releases of syncthing, however now I get the identical issue to @DeX77:

```
+ go run build.go -no-upgrade -version v0.14.33 build                                                                                                                                                  
runtime/internal/sys                                                                                                                                                                                   
go install runtime/internal/sys: mkdir /usr/lib64/golang/pkg/linux_amd64_noupgrade: permission denied
```

**Comment by gasinvein** [comment]
I can reproduce it on Linux, and presence of `-no-upgrade` option doesn't matter.

**Comment by AudriusButkevicius** [comment]
Try removing this line:

https://github.com/syncthing/syncthing/blob/master/build.go#L428

**Comment by AudriusButkevicius** [comment]
Seems to be broken by https://github.com/syncthing/syncthing/commit/7c8418f493398aea5d5c3c4cdbd3b4e46762b56a

@calmh

**Comment by ilovezfs** [comment]
Still
```
==> ./build.sh noupgrade
runtime/internal/sys
go install runtime/internal/sys: mkdir /usr/local/Cellar/go/1.8.3/libexec/pkg/darwin_amd64_noupgrade: operation not permitted
exit status 1
exit status 1
```
with 428 deleted

**Comment by DeX77** [comment]
There is also https://github.com/syncthing/syncthing/blob/master/build.go#L407

Will try if removing both of them helps.

**Comment by calmh** [comment]
I intentionally add the tags as install suffix as this means two successive build server builds can retain and reuse the object files. Unfortunately this apparently also means stdlib needs to be built with that install suffix. I'll change this to an explicit flag instead so it doesn't happen for unaware builders.
