### ISSUE TITLE
Feature: Add "initial seeding mode"

### ISSUE THREAD

**Issue by asdil12** [syncthing/syncthing#4276]
When I add some files to a Syncthing instance **A** that is paired with **B** and **C** (**B** and **C** are paired to each other as well) the upload speed from **A** will be distributed over **B** and **C**.

It would be more efficient if **A** would send each file only once to either **B** or **C** until all files are uploaded. **B** and **C** can in the meantime exchange the missing files and save some upload bandwidth of **A**. It would be much like the *initial seeding mode* of Bittorrent.

**Comment by calmh** [comment]
Given that the default pull order on B and C is `random` this is essentially what happens today. On top of that, progress updates mean that B and C can share blocks of a file they are both pulling at the same time. So, are you not seeing this happening?

**Comment by asdil12** [comment]
How will B decide, if it should pull from A or from C?

**Comment by AudriusButkevicius** [comment]
It will pull from everyone it possibly can.

**Comment by AudriusButkevicius** [comment]
I am closing this, as I think we already do this. If you have more questions, use the forum.
