### ISSUE TITLE
Port 0 listen address gets announced to discovery servers

### ISSUE THREAD

**Issue by vision57** [syncthing/syncthing#4278]
# what happened

I am trying to specify port 0 in sync protocol listen addresses, hoping sync starting to bind on a random available port and it does work. However, it announces port 0 to the global discover service 
directly without retrieve the random port.

Here is log that shows a success binding on random port:

```
[H6BLN] 11:55:03 INFO: TCP listener (10.99.22.141:41837) starting
```
And from `https://discovery-v4-2.syncthing.net/v2/?device=*****` I get:

```javascript
{
  Seen: "2017-07-28T01:25:07.16771Z",
  addresses: [
    "tcp4://10.99.22.****:0"
  ]
}
```

# what you expected to happen instead

The random port on which sync listen actually is announced to the global discover.

# steps to reproduce the problem

Simple specify port 0 in sync protocol listen addresses, and maybe restart sync. After that checkout the global discover service to see the announced port.

# Version Information

Syncthing Version: v0.14.32
OS Version: Fedora 25 (Linux 64 bit)

**Comment by AudriusButkevicius** [comment]
So this is an oversight from our end, but in general its a bad idea, as over multiple restarts it will accumulate a long list which will take a while to expire, and prolong connection establishment.

**Comment by vision57** [comment]
Thank you!

I still wonder why not choose to overwrite device's original address list on discover server each time client re-register?

**Comment by AudriusButkevicius** [comment]
Because discovery happens not that often and if a device is flip flopping between wifi and 4g,the likeliness of connecting would be low.

**Comment by viric** [comment]
I've seen in the beacon packets an announcement for port 0 too, and that makes clients want to connect to tcp destination port 0, which alerts the firewall.

The beacon packet looks this way here:
```
17:39:04.027909 IP6 fe80::xxxxxxxxxxxx.48859 > ff12::8384.21027: UDP, length 108 
         ....
        0x0060:  8b50 6136 1213 7463 703a 2f2f 302e 302e  .Pa6..tcp://0.0.
        0x0070:  302e 303a 3232 3030 3012 0f74 6370 3a2f  0.0:22000..tcp:/
        0x0080:  2f30 2e30 2e30 2e30 3a30 1214 7175 6963  /0.0.0.0:0..quic
        0x0090:  3a2f 2f30 2e30 2e30 2e30 3a32 3230 3030  ://0.0.0.0:22000
        0x00a0:  1880 d3c8 f4c2 bdf4 fb39                 .........9
```

There is a tcp listener in :0. I don't know where it comes from, as I use simply the default port.

**Comment by viric** [comment]
AH! Here it is, what announces tcp port 0 in the beacon, causing clients to attempt connecting to port 0.
https://github.com/syncthing/syncthing/blob/main/lib/connections/tcp_listen.go#L171-L177

**Comment by imsodin** [comment]
That code is from https://github.com/syncthing/syncthing/pull/5753, long after this issue report. And announcing port 0 is on purpose. The discovery server replaces a zero port with the port the announcement is made from:  
https://github.com/syncthing/syncthing/blob/main/cmd/stdiscosrv/apisrv.go#L422

So the original issue is not an issue anymore: announcing zero ports is on purpose. If you (@viric) see zero ports announced from the discovery server or have other problems, please write on https://forum.syncthing.net to debug it - we can open a new bug if one is discovered.

**Comment by viric** [comment]
I'm not using the discovery server, so :0 stays forever.
