### ISSUE TITLE
Devices "auto-unpause" after restart

### ISSUE THREAD

**Issue by scienmind** [syncthing/syncthing#4279]
Paused devices behave strangely:

1. Pause device B -> it is paused, connection stopped, config set "paused" to "true"
2. Restart ST several times -> device B **sometimes** auto resumes at some point (both in UI and in config)

Also, sometimes UI show device B as "Paused", while seemingly transferring something:
![image](https://user-images.githubusercontent.com/11633330/28729100-e4846dda-73d3-11e7-92d7-c7bc288a608e.png)
(screenshot taken after pausing a device, and restarting)

### Version Information

Syncthing Version: v.0.14.33
SyncTrayzor v.1.1.16
OS Version: Windows 10 x64

**Comment by AudriusButkevicius** [comment]
Steps to repro would be nice. The rate moving could be caused by a connection attempt.

**Comment by scienmind** [comment]
>  The rate moving could be caused by a connection attempt
I thought so, but 72 + 39 MBs for connection attempt? I doubt that...

And unfortunately i don't have a 100% way to reproduce it, just pause the device, then restart ST several times (fat sharing config probably helps...) and at some point the device will become unpaused, in UI as well.

**Comment by AudriusButkevicius** [comment]
Fat sharing?

**Comment by scienmind** [comment]
I mainly notice it on two devices: one has one device + one folder, but shares around 3TB, and another device has ~20 devices connected + ~40 folders, sharing around 2TB in total.

Than again, those are the two i mostly use pausing with, so the sampling isn't evenly distributed...

**Comment by scienmind** [comment]
Last few times it happened consistently on one of the devices:
1. Pause the device (pausing printed to log)
2. Exit ST
3. Open ST
The log is as follows:
```
[IDIDIDID] 08:44:20 INFO: syncthing v0.14.33 "Dysprosium Dragonfly" (go1.8.3 windows-amd64) DESKTOP-V6RD4NK\Admin@DESKTOP-V6RD4NK 2017-07-13 06:55:12 UTC
[IDIDIDID] 08:44:20 INFO: My ID: IDIDIDIDID1
[IDIDIDID] 08:44:21 INFO: Single thread SHA256 performance is 225 MB/s using minio/sha256-simd (141 MB/s using crypto/sha256).
[IDIDIDID] 08:44:21 INFO: Hashing performance with weak hash is 216.41 MB/s
[IDIDIDID] 08:44:22 INFO: Hashing performance without weak hash is 257.89 MB/s
[IDIDIDID] 08:44:22 INFO: Weak hash enabled, as it has an acceptable performance impact.
[IDIDIDID] 08:49:27 INFO: Ready to synchronize shared_folder (readonly)
[IDIDIDID] 08:49:27 INFO: Send rate is unlimited, receive rate is unlimited
[IDIDIDID] 08:49:27 INFO: Rate limits do not apply to LAN connections
[IDIDIDID] 08:49:27 INFO: Using discovery server https://discovery-v4-2.syncthing.net/v2/?id=DVU36WY
[IDIDIDID] 08:49:27 INFO: Using discovery server https://discovery-v4-3.syncthing.net/v2/?id=VK6HNJ3
[IDIDIDID] 08:49:27 INFO: Using discovery server https://discovery-v4-4.syncthing.net/v2/?id=LYXKCHX
[IDIDIDID] 08:49:27 INFO: Using discovery server https://discovery-v6-2.syncthing.net/v2/?id=DVU36WY
[IDIDIDID] 08:49:27 INFO: Using discovery server https://discovery-v6-3.syncthing.net/v2/?id=VK6HNJ3
[IDIDIDID] 08:49:27 INFO: Using discovery server https://discovery-v6-4.syncthing.net/v2/?id=LYXKCHX
[IDIDIDID] 08:49:27 INFO: TCP listener ([::]:22011) starting
[IDIDIDID] 08:49:27 INFO: Device IDIDIDIDID1 is "This Device" at [dynamic]
[IDIDIDID] 08:49:27 INFO: Device IDIDID_2 is "A-PC-HT-Service" at [dynamic]
[IDIDIDID] 08:49:27 INFO: GUI and API listening on [::]:8081
[IDIDIDID] 08:49:27 INFO: Access the GUI via the following URL: https://127.0.0.1:8081/
[IDIDIDID] 09:11:13 INFO: Established secure connection to IDIDID_2 at <local-ip>:port-37.187.5.177:22067 (relay-client) (TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305)
[IDIDIDID] 09:11:13 INFO: Device IDIDID_2 client is "syncthing v0.14.33" named "Remote Device"
[IDIDIDID] 09:34:01 INFO: Completed initial scan (ro) of shared_folder
```
So, about an hour after boot, the device is paused in config: `<paused>true</paused>`
The UI shows it as paused, but:
![image](https://user-images.githubusercontent.com/11633330/28812806-27d2a6c4-769f-11e7-80c3-b5eb99640bb1.png)
So, seemingly paused, but constantly transferring data (120 MB total during this hour).

Clicking "resume", changes the UI label to "Up To Date", but the transfer continues fluently, same rate, same address; nothing printed to the console; in config "paused" sets to "false".

Then, clicking "pause" will finally properly pause the device.
Printed to the console:
```
[IDIDID1] 09:53:39 INFO: Pausing IDIDID_2
[IDIDID1] 09:53:39 INFO: Connection to IDIDID_2 closed: reading length: read tcp <local-ip>:port->37.187.5.177:22067: use of closed network connection
```
In config "paused" sets to "true". And UI shows:
![image](https://user-images.githubusercontent.com/11633330/28813091-6d2fabf8-76a0-11e7-86c0-8ff935fb5b4d.png)

**Comment by calmh** [comment]
This looks like a bug so I'm tagging it as such, but I have no idea how it could happen.

**Comment by scienmind** [comment]
The redacted connected address was relay's address (i blacked it out of habit...) you can see it on the last screenshot.

**Comment by calmh** [comment]
Yeah. I don't see how any kind of connection could get past the paused check. One explanation would be if you had something other than the GUI that makes config changes, perhaps not being aware of the pause option's existence, thus inadvertently unpausing? Otherwise I'm clueless.

**Comment by scienmind** [comment]
The only other thing that may touch it is SyncTrayzor that wraps it...

**Comment by scienmind** [comment]
One thing that comes to mind is that SyncTrayzor does have functionality to pause devices if they are connected via "metered network" (which are reported as such by the OS). However metered networks weren't involved in this case.

Maybe @canton7 have some insights on this...

**Comment by scienmind** [comment]
Digging into SyncTrayzor's logs, I found this:
(as seen by the time, happens in between the lines of ST logs posted above)

```
 2017-08-01 08:50:25.2531 #3744 [Info] SyncTrayzor.Services.Metering.MeteredNetworkManager: Resuming device IDIDIDID-8-FULL-ID 
 2017-08-01 08:50:25.2951 #3744 [Info] SyncTrayzor.Syncthing.ApiClient.SyncthingApiClient: Resuming device IDIDIDID-8-FULL-ID 
```

I'll open issue in SyncTrayzor's repo

**Comment by AudriusButkevicius** [comment]
Why is the UI out of sync in that case though?
