### ISSUE TITLE
stdiscosrv devices on same network report LAN IP

### ISSUE THREAD

**Issue by schnappijedi** [syncthing/syncthing#4280]
Running a discovery server on WAN accessible device on local network causes devices within LAN to report a LAN IP to the discovery server. No bug since software doing as intended. However this causes problems if trying to run and use a private global discovery server.

Would it be possible to implement change in stdiscosrv such that if device reports LAN IP (192.168,* 172.*, 10.*) then query device for WAN IP?

stdiscosrv Version 0.14.34-rc

**Comment by AudriusButkevicius** [comment]
In most cases devices have no idea what their WAN address is and they can't trivially figure it out, hence we rely on the discovery server to discover the WAN address. Obviously when you run that in local network, it doesn't work, but there isn't an awful lot we can do about this, so running discovery server in a separate subnet/external network is a prerequisite for discovery to work.

**Comment by calmh** [comment]
This behavior is typically *why* you would run an internal discovery server - to get it to understand and report internal addresses (between subnets).

**Comment by schnappijedi** [comment]
Good point that didn't think of. Another reason for running discovery server is running a completely self-sufficient/internal/self-hosted Syncthing infrastructure.
