### ISSUE TITLE
Enhancement: Allow ignoring of parent directory, or, support git and other VCSs in subdirectories

### ISSUE THREAD

**Issue by deGravity** [syncthing/syncthing#4281]
When a directory under a different version control system (i.e. git) exists in a syncthing shared directory, conflict files frequently arise and make using version control difficult. I propose either a new ignore pattern or feature to fix this.

If a directory matches the pattern of a VCS system, then it is ignored.

In the example of git, if a directory contain a .git folder, it is not synced.

This could be enable by a new prefix to the .stignore rules. As a proposal, (?p) before a rule means that when the pattern is matched, the parent directory is ignored.

Alternatively, version control compatibility could be more feature rich. In the git example, this would mean indexing the .git folder the first time it is seen (but nothing else), and syncing that .git folder only if it does not exist. This would properly set up remotes when a machine first accepts a shared folder, but would not override which branch is being worked on in the future.

**Comment by AudriusButkevicius** [comment]
Please open a thread on the forum first. I think this is not baked enough to live on the tracker.
