### ISSUE TITLE
Web Upd8 PPA has old v13

### ISSUE THREAD

**Issue by 408314** [syncthing/syncthing#4283]
installed syncthing from  Web Upd8 PPA. 
Contains v13 which is kind of old I guess, because it cant communicate with other versions ("the remote device speaks an unknown (newer?) version of the protocol")
please update the repository

**Comment by AudriusButkevicius** [comment]
We don't maintain that, contact whoever maintains it.

**Comment by kozec** [comment]
> contact whoever maintains it.

That would be @hotice, but I've noticed that Web Upd8 site was not updated for almost two months...
