### ISSUE TITLE
Machine impossible to use during Syncthing Scan

### ISSUE THREAD

**Issue by nicgentile** [syncthing/syncthing#4287]
Now, this has left me deeply disappointed. I'm running Syncthing on Debian 9. I need to move around 12TB to 5 machines, our first chance to replicate after a year. Four times already the machine serving the files has stalled and crashed. Its a production machine.

I have tried nice, running it on one core, but at some point, the load is greater than 500 and the machine dwindles out, as it should. Surely, there has to be a way to tame Syncthing from running amok. Doesn't it have a throttle down or a control consumption feature? Feels like it should have one. It says that we have to wait 4 days for the scan to complete, but we can't be offline for 4 days.

What can I do to make this less painless? We have suspended the whole thing while we debate if this is the tool for us in the first place.

**Comment by calmh** [comment]
Please use the forum for support, not the bug tracker. There are a couple of things you can tweak, among them `progressUpdateIntervalS` and `hashers`. Search the forum or documentation for details.
