### ISSUE TITLE
All symlink disappeared from shares

### ISSUE THREAD

**Issue by koma85** [syncthing/syncthing#4288]
All symlinks in our shares disappeared:

https://gist.github.com/koma85/8901a0f56fa26196bacb5b1fed7b46ea

This happened after the automatic update as you can see from our log

**Comment by koma85** [comment]
Introduced by https://github.com/syncthing/syncthing/issues/4286

**Comment by AudriusButkevicius** [comment]
I've pulled the release for now, as it's causing data loss, but I can't fix it at the moment.

**Comment by calmh** [comment]
Looks like I fucked up that one royally, despite testing.

**Comment by AudriusButkevicius** [comment]
We can probably recover from this. Walk the index for removed symlinks after release date and restore them.

**Comment by calmh** [comment]
I wonder. That would depend on some other device still having it, and our update about it being deleted not having propagated. We drop the symlink target from the index when we delete the symlink.

**Comment by calmh** [comment]
While it's possible some people may have caught this just after upgrade and before it managed to connect to anywhere else it seems fairly far fetched. There are also risks to mucking about with the index. I'd rather avoid digging myself into a deeper hole due to this.

**Comment by koma85** [comment]
Mayibe instead of removing links crash or send an ALERT or insert an --insecure option or better an --strictlysecured .
Anyway I've disabled the autoupgrade and restored the old binary.
Thank you for your collaboration.

**Comment by AudriusButkevicius** [comment]
So we're done here I think, we screwed it up and we're past that point I guess.
