### ISSUE TITLE
Reverse send only (accept only) sync option

### ISSUE THREAD

**Issue by theonetoday** [syncthing/syncthing#4291]
I want to be able to send files from my phone to my computer then have them deleted on my phone without having it affect the files on my computer. Something opposite to send only.

**Comment by AudriusButkevicius** [comment]
Please search existing issues before opening new ones. There is a ticket about non-master slave folders.

**Comment by AudriusButkevicius** [comment]
Also, what you want to achieve is already achievable with send-only, but this is not tye right medium for explanations or discussions. Use the forum if you have any more questions.

**Comment by theonetoday** [comment]
Issue 2170? I still can't find it

**Comment by AudriusButkevicius** [comment]
#62
