### ISSUE TITLE
gui: Show remote device completion for partial transfers

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#4295]
Since #4227 Syncthing also displays remaining bytes to sync for remote devices, which is very helpful.

But if Syncthing is transferring a large file (e.g. 10 GB) and the upload rate shows that 3 GB have already been transferred, then the remaining bytes still show 10 GB and percentage does not change until the transfer is completed.

**Comment by AudriusButkevicius** [comment]
That is for the remote device or for the local device?

**Comment by AudriusButkevicius** [comment]
I think this not happens as we take the temp indexes into account these days.

**Comment by imsodin** [comment]
I can confirm that this works: Every 5 seconds when the download progress message is sent, the amount remaining data is updated.
