### ISSUE TITLE
Default path set when editing existing folder without label

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#4297]
Discovered in:
https://forum.syncthing.net/t/data-path-vanished-error-box-appearing-folder-stops-sync-ing-megabug/10340/5

To reproduce, just edit any folder without a label and the default path will appear instead of the previous one.

**Comment by calmh** [comment]
Good find. I think this warrants a new release as it's hard to see and harder to fix (impossible in the GUI).

**Comment by tuxcomputers** [comment]
I thought I was going insane.... cancels appointment with therapist.
