### ISSUE TITLE
Syncthing start a conhost.exe but dont close it

### ISSUE THREAD

**Issue by beerisgood** [syncthing/syncthing#4299]
I use SyncTrayzor Portable and when it start Syncthing a conhost.exe opens from Syncthing. If i close the conhost.exe (CMD) still all works so it would be nice if Syncthing can exit the opened conhost.exe after launch.
See https://github.com/canton7/SyncTrayzor/issues/394

**Comment by AudriusButkevicius** [comment]
This is most likely the console that it's attached to. We don't control this, windows starts it for us. We could compile it without console support but then you'd have the other problem where it wouldn't have a window for users to look into for the logs.

**Comment by beerisgood** [comment]
I make now my own fix with that cmd:
`@echo off
start SyncTrayzorPortable-x64\SyncTrayzor.exe -minimized
ping localhost -n 5 >nul
taskkill /IM conhost.exe /F`

**Comment by canton7** [comment]
Don't do that. That will kill conhost processes that are unrelated to Syncthing.
