### ISSUE TITLE
"no buffer space available" most prominent stdout entry

### ISSUE THREAD

**Issue by backstube** [syncthing/syncthing#4302]
Hi,
this is, after several hours into operation, the most prominent output line of syncthing v0.14.36:

<pre>[CZ64L] 05:19:08 INFO: write udp4 0.0.0.0:20297->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 05:19:08 INFO: write udp4 0.0.0.0:18114->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 05:49:18 INFO: write udp4 0.0.0.0:46855->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 05:49:18 INFO: write udp4 0.0.0.0:22860->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 06:19:28 INFO: write udp4 0.0.0.0:16087->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 06:19:28 INFO: write udp4 0.0.0.0:14053->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 06:49:38 INFO: write udp4 0.0.0.0:45771->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 06:49:38 INFO: write udp4 0.0.0.0:33853->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 07:19:49 INFO: write udp4 0.0.0.0:61271->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 07:19:49 INFO: write udp4 0.0.0.0:65096->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 07:49:59 INFO: write udp4 0.0.0.0:65356->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 07:49:59 INFO: write udp4 0.0.0.0:30537->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 08:20:09 INFO: write udp4 0.0.0.0:62777->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 08:20:09 INFO: write udp4 0.0.0.0:65127->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 08:50:19 INFO: write udp4 0.0.0.0:44910->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 08:50:19 INFO: write udp4 0.0.0.0:14159->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 09:20:29 INFO: write udp4 0.0.0.0:51407->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 09:20:29 INFO: write udp4 0.0.0.0:29500->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 09:50:39 INFO: write udp4 0.0.0.0:17056->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 09:50:39 INFO: write udp4 0.0.0.0:35164->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 10:20:49 INFO: write udp4 0.0.0.0:39141->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 10:20:49 INFO: write udp4 0.0.0.0:50708->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 10:50:59 INFO: write udp4 0.0.0.0:17328->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 10:50:59 INFO: write udp4 0.0.0.0:37339->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 11:21:09 INFO: write udp4 0.0.0.0:58599->239.255.255.250:1900: sendto: no buffer space available
[CZ64L] 11:21:09 INFO: write udp4 0.0.0.0:17473->239.255.255.250:1900: sendto: no buffer space available</pre>

Syncthing is connected to one peer to sync data with. All connections run via relays, there are no LAN-based connections.

If syncthing happens to run long preriods of time (while complaining a lot as seen above), the OS won't answer external requests anymore. No new ssh connections, no web, only ICMP. Previously established connections like ssh sessions remain working, though. The OS is not suffering heavy load. It has, compared to it's job, plenty of memory: 16 GB.

This issue is not a one-off, it happens every time. It has happened with earlier syncthing versions, too.

The platform this syncthing instance is running on is FreeBSD 10.3-STABLE. Syncthing is not running inside a jail.

Syncthing has been compiled locally a few days back ...
<pre>[monitor] 11:35:53 INFO: Starting syncthing
[CZ64L] 11:35:53 INFO: syncthing v0.14.36 "Dysprosium Dragonfly" (go1.8.3 freebsd-amd64) root@radon 2017-08-10 15:31:25 UTC
</pre>

... with no issues at all.

The mode of operation at the moment is to stop syncthing manually when it is complaining buffer space and start it again. This helps to avoid the OS to become irresponsible. However, it's not a proper way to run a service.

Other than that, syncthing is working just fine. Thanks for providing syncthing, and thanks for looking into this.

### Version Information

Syncthing Version: v0.14.36  and earlier
OS Version: FreeBSD 10.3-STABLE
Browser Version: -

**Comment by AudriusButkevicius** [comment]
Why do you think its syncthing causing it? I think syncthing just suffers alongside everything else. The problem seems to be your network buffers filling up, but that implies a problem with the kernel/OS, as software should not be able to cause issues like these.

**Comment by calmh** [comment]
FWIW it looks like the complaints are on the multicast sends. Perhaps multicast doesn't work in your setup. FreeBSD has also had several kernel issues around multicast, historically, that Syncthing tickles. Disable local discovery if that's the case.

**Comment by backstube** [comment]
> Why do you think its syncthing causing it?

I do because Syncthing is the one complaining. It doesn't tell the reason, nor am I deep enough into kernel space things to debug this issue.

> Disable local discovery if that's the case.

Will do that a bit later and come back w/ results. Thanks for your comments.

**Comment by AudriusButkevicius** [comment]
Well I am sure SSH/ curl et all are also complaining, you just don't get to see the error messages.

**Comment by backstube** [comment]
> Well I am sure SSH/ curl et all should also be complaining, you just don't get to see the error messages I suspect.

Might be, for what I can say they do not complain into the log files, which I happen to inspect regularly.

**Comment by backstube** [comment]
Your comments yesterday reg. historical issues w/ FreeBSD kernels finally pushed me to take the effort to upgrade the FreeBSD box to 11.1. This system is not isolated from others, so it was a bit more to do than just the sysupgrade itself, but it was worth it.

The above mentioned issue is gone. After 17 hrs no buffer space complaint anymore. I did not touch the local discovery settings (for now).

So, thanks again for your help.
