### ISSUE TITLE
Partial Sync with BitTorrent folder and inotify

### ISSUE THREAD

**Issue by jcnoir** [syncthing/syncthing#4303]
I use syncthing and syncthing-inotify (in docker containers from tianon/syncthing and tianon/syncthing-inotify) to sync a folder between two computers.
This folder receives files downloaded with a bitorrent client (transmission 2.92).
The inotify works great for other folders but not for this one: even a long time (minutes) after the end of the bitorrent download I can see in the syncthing web UI that the bitorrent folder appears as "Up to date" on both sides.
But if I check the folder on the other machine (synced with syncthing) some files are missing.
I need to manually hit the rescan button in the syncthing web UI for this folder to be completely synced.

I expect this folder to be completely synced with syncthing without having to manually hit the rescan button. 

### Version Information

Syncthing Version: v0.14.36
OS Version: Linux Debian 9 (64 bit)

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.

**Comment by jcnoir** [comment]
Maybe I miss something but I do not understand your point: 
In short, the folder is not synced correctly with syncthing because the sync status is just wrong until I click the rescan button. Looks like a bug to me ?

**Comment by AudriusButkevicius** [comment]
Not really, atleast not with syncthing, as once the scan is done, it works as expected. Anyways, forum is the right place to start talking about this.
