### ISSUE TITLE
0.14.36 doesn't respect global outgoing bandwidth limit

### ISSUE THREAD

**Issue by Moonbase59** [syncthing/syncthing#4306]
It seems to that in version 0.14.36 the global outgoing bandwidth limit isn’t respected correctly (which worked before). I’ve tried with 0.14.36 on both 64-bit Linux (Ubuntu 14.04.5) and 64-bit Windows 7.

On my side, the linux machines are limited to 210 KB/s. When watching the outbound data rate to another system, it stays at 0 B/s for a while, jumps to 445 KB/s and transfers data, then VERY shortly jumps to 210 KB/s and back to 0 again. In earlier versions, using the same machines, it steadily transmitted around 210 KB/s, maybe +/- 5 KB/s.

On a colleague’s (Windows 7) machine, it does the same. We limited him to around 35 KB/s since he has only an upload of 444 kbit/s and needs some headroom, say for streaming to an internet radio and/or using Mumble. In earlier versions, this worked fine, i.e. no interruptions when streaming/talking, now we hear interrupts whenever Syncthing starts using the full bandwidth.

Any ideas?

**Comment by AudriusButkevicius** [comment]
Rate limiters are not exact, they have a burst capacity as well.
Also, the rates might not be harmonized, so double check the units, as it might be kb in one place, Kb in the other.
Also, by default we do not limit connections in local networks, so if you have some local devices connected they could be contributing to the rate you are seeing.

Nothing has changed in that area of code for tens of releases now, so if you still want to talk about this, forum is probably the right place.

**Comment by Moonbase59** [comment]
Hm. The settings haven’t been changed, all participating (all remote) machines are in use between one and two years now, over many versions, and syncing about 1.2 mio files over the internet. And I’m looking at the single remote machine’s transfer rates in the GUI.

Well, let’s see if anyone else gets this problem, or it mysteriously vanishes again with a coming version …
