### ISSUE TITLE
Router is recognized as an invalid device

### ISSUE THREAD

**Issue by dakarf** [syncthing/syncthing#4307]
When starting syncthing, the console reads an error (abcd and efgh are just placeholders for privacy):
> [abcd] 15:11:58 INFO: Invalid IGD response: invalid device UUID UUID-MIKROTIK-INTERNET-GATEWAY-DEVICE-abcd-efgh (continuing anyway)

Mikrotik is the manufacturer of the router. The router has nothing to do with syncthing beyond what you'd expect from a router (it doesn't run a syncthing instance or anything).

Syncthing Version: v0.14.36
OS Version: Windows 8.1

**Comment by AudriusButkevicius** [comment]
It's an informational message that has no effect informing that your router does not comply with standards.

**Comment by dakarf** [comment]
The message says there's an invalid device, and the device isn't a (syncthing) device to be considered a device to begin with.
What standards are we talking about?
What is the information I'm supposed to be getting from the message?

**Comment by AudriusButkevicius** [comment]
Please use the forum for support discussions and questions.
