### ISSUE TITLE
lost config.xml.v16 with lots of device id and folder path

### ISSUE THREAD

**Issue by dipenpatel235** [syncthing/syncthing#4308]
Some How lost config.xml.v16
in that file i have added lots of Device id and folder path .
i have lost all so how i get back.
 it is possible get back old config with device id and folder path ?

Thanks
### Version Information

Syncthing Version: "v0.14.30"
OS Version: Centos 7 64 bit
Browser Version: (if applicable, for GUI issues)

**Comment by calmh** [comment]
Support is done on the forum. Thanks.
