### ISSUE TITLE
fs regression: spurious "insufficient space" in folders

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4314]
Suddenly, five out of seven of my folders on the FreeBSD/ZFS box are "out of space", which is a lie. I haven't investigated why yet, but it seems correlated to upgrading to .37-rc1.

<img width="1171" alt="screen shot 2017-08-21 at 13 09 48" src="https://user-images.githubusercontent.com/125426/29516799-2e63a550-8672-11e7-8688-75c5fb516808.png">

The actual error is along the lines of `insufficient space in basic /data/lightroom/: 0.018349 % < 1 %`.

```
jb@pseudo:~ $ zfs list -o space data/lightroom
NAME            AVAIL   USED  USEDSNAP  USEDDS  USEDREFRESERV  USEDCHILD
data/lightroom  5.16T  2.84G     1.88G    992M              0          0
jb@pseudo:~ $ df -h /data/lightroom
Filesystem        Size    Used   Avail Capacity  Mounted on
data/lightroom    5.2T    992M    5.2T     0%    /data/lightroom
```

For reference, one of the folders that are *not* seen as out of space:

```
jb@pseudo:~ $ zfs list -o space /data/foto/2017
NAME            AVAIL   USED  USEDSNAP  USEDDS  USEDREFRESERV  USEDCHILD
data/foto/2017  5.16T   151G     1.48G    149G              0          0
jb@pseudo:~ $ df -h /data/foto/2017
Filesystem        Size    Used   Avail Capacity  Mounted on
data/foto/2017    5.3T    149G    5.2T     3%    /data/foto/2017
```

Did we confuse used vs free? Since ZFS reports the space used *by the dataset* vs the total amount of free space, these all look like they have >99% free space, as they each make up a small part of the full pool.

**Comment by AudriusButkevicius** [comment]
I did touch that code, so it's perfectly possible I've botched it.
