### ISSUE TITLE
Phython script ImportError on start up

### ISSUE THREAD

**Issue by tobiasschuerg** [syncthing/syncthing#4319]
I set SyncThing to start the daemon on start up but now every time I'm getting the following error screen:

![image](https://user-images.githubusercontent.com/1324555/29550326-804d8066-870d-11e7-82ef-619d0ff98c58.png)

### Version Information

Syncthing Version: v0.9.25- win32
OS Version: Windows 10 64
Browser Version: (if applicable, for GUI issues)

**Comment by canton7** [comment]
That's a problem with Syncthing-GTK. Open an issue in the Syncthing-GTK repo.

**Comment by kozec** [comment]
Hello there.

This is (almost) known problem with W10, check [syncthing-gtk#385](https://github.com/syncthing/syncthing-gtk/issues/385#issuecomment-315603169) for workaround.
