### ISSUE TITLE
allow "root user" nag to be disabled

### ISSUE THREAD

**Issue by oskapt** [syncthing/syncthing#4324]
Syncthing Version: v0.14.36
OS Version: Docker

I maintain [a repo](https://github.com/oskapt/docker-syncthing) that runs syncthing under Docker, specifically targeted at running under [Rancher](https://www.rancher.com). Because this is used to replicate production data with a myriad of owners (e.g. an NFS share between two cloud instances where an NFS container makes that data available to Rancher-NFS for use as Docker volumes across the entire environment), the container runs the syncthing process as `root` and uses [syncthing-acl](https://github.com/oskapt/docker-syncthing-acl) to manage file ownership.

Recently syncthing started nagging on restart that syncthing "shouldn't run as the root user." That might be true under _most_ circumstances where a user is running syncthing locally as a standalone service, but it's not true under _all_ circumstances.  Also, it's presented as a suggestion, but a single acknowledgement does not persist between restarts of the service.

I would like to ask that the logic around that nag be changed to either recognize that the user said OK and stop presenting the dialog on every restart/upgrade, or else allow the nag to be permanently disabled by a config option or touching a file in `/srv/config`. 

I understand that security is your primary objective here, but you may not have realized that a use case such as my own exists.

Thank you for your consideration.

**Comment by calmh** [comment]
This is currently on the same level as the "web gui has no authentication" nag, which is also not possible to disable. I do not think we should disable it.

In your case, I think a better workaround is to give the binary the `CAP_DAC_OVERRIDE` capability and run it as a normal user?

**Comment by oskapt** [comment]
@calmh - sorry that i didn't see your reply a month ago. i just saw the notification that you closed this. i'll see if it works well enough with `CAP_DAC_OVERRIDE`, and if so, update my docs for users to deploy it that way.
