### ISSUE TITLE
"Global Changes" button is confusing. Retitle to "Show Change Log"?

### ISSUE THREAD

**Issue by HaleTom** [syncthing/syncthing#4326]
### What happens

In the GUI, I see a button with a unwinding clock and the text `Global Changes`. I hover the mouse over it hoping for pop-up explanatory text, _but nothing appears_.

I have no idea what this button does, but I'm too scared to press it as:
* I don't know what it does
* It may may be irreversible

[I enter the search terms in the wiki and no results appear.](https://docs.syncthing.net/search.html?q=global+changes&check_keywords=yes&area=default#) 

### What I expect to happen instead

I see a button with a unwinding clock and the text "Global Changes". I hover the mouse over it hoping for pop-up explanatory text, _and explanatory text appears_.

Ideally, the explanatory text has a link to a page with detailed explanation. 
A page exists in the wiki, such that a search for the phrase "global changes" brings up the page.

### Background
I remember having difficulty finding the explanation of this button before. _\*months pass\*_. I've forgotten what it does and have interrupted my (so far unfruitful) repeated search for the answer to raise this issue.

### Version Information
`syncthing v0.14.32 "Dysprosium Dragonfly" (go1.8.3 linux-amd64) builduser@svetlemodry 2017-07-11 09:25:28 UTC [noupgrade]`
Browser: `Google Chrome | 60.0.3112.90 (Official Build) (64-bit)`

**Comment by calmh** [comment]
Hi,

Thanks for the report. I'm going to close this as it's formulated as a bug report on the lack of popup explanatory text on the button, but we don't have any popups on *any* buttons in the UI and I'm not convinced that we should, either. Rather, the buttons should be self explanatory.

It might be legitimate to retitle the button if it causes confusion or looks scary. Generally speaking are buttons with scary actions are scary-colored.

Perhaps we could retitle this button to "Show Change Log" to make it clearer what it does.

In the meantime, please don't be afraid to press it.

**Comment by calmh** [comment]
Actually, lets retain and make this actionable.

**Comment by Moonbase59** [comment]
Hm. Being a developer, I’d expect to see the _software’s change log_ when activating a link/button that’s labelled »Change log«, so I’d rather _not_ call it that. The icon looks scary to me, kinda »Undo« or »Rollback« something.

Since it shows _some_ of the latest changes only, why not use an »info« icon like U+1F6C8 (letter »i« in a circle) and label it something like »Latest actions«? (Maybe _not_ »Latest changes«—I’d again assume it told me about _program changes_.)

**Comment by Ferroin** [comment]
I agree about the icon being scary looking and not helping with clarity here.

I also think that 'Global Changes' is a rather ambiguous name, but I don't think 'Latest Changes' is as ambiguous for most people as you think.  Very few pieces of software embed changelogs , and when they do, it's almost always in some help menu (in the Syncthing UI, I would expect such a link to be in the footer, not grouped with the device entries).  I think perhaps 'Recent Changes' might be a bit better (for me at least, 'recent' tends to have a more spatially local connotation than 'latest'), but I don't think using 'actions' as the second word helps at all (and in fact, I'd argue that it makes the button even more mysterious).

**Comment by nelsonkhan** [comment]
Just submitted a pull request that fixes this issue, at least in the browser. Let me know if it's sufficient!
