### ISSUE TITLE
Syncthing only syncing folders (not files)

### ISSUE THREAD

**Issue by kevroy314** [syncthing/syncthing#4328]
I've been testing Syncthing for potentially replacing using CrashPlan for multiple devices. I was very happy with the setup and feature set, but after setting it up on two machines and leaving them over night, I've noticed a strange behavior. Syncthing appears to only be Syncing folders.

![image](https://user-images.githubusercontent.com/301111/29680459-3d98a1e2-88ca-11e7-87ab-e435d37477ab.png)

Some special notes about the configuration:

- Machine A is set up to Send and Receive a folder (User folder on Windows) from Machine B
- Machine B is set up to Send Only and is on the same LAN as Machine A
- The connection is direct (not Relayed)
- Machine A is set up to have the received folder saved to a network folder (addressed via a UNC path)
- Both machines are running Syncthing via Task Scheduler

Neither machine seems to be spitting out errors and no data is being transferred (other than folders, which are being created on the network drive). The Network drive is a NAS that I can typically get ~30Mb/s via Machine A (which has a wired connection to the NAS).

I'm wondering if the issue has to do with the size of the file tree (lots of small files spread out through a big hierarchy).

### Version Information

Syncthing Version: v0.14.36 (Windows 64bit)
OS Version: Windows 10 64bit
Browser Version: Google Chrome Version 60.0.3112.101 (Official Build) (64-bit)

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
