### ISSUE TITLE
Stopping folder.... - Folder path missing Notification

### ISSUE THREAD

**Issue by schnappijedi** [syncthing/syncthing#4330]
When an external device, or really any situation in which a Syncthing folder is disconnected the GUI will show a time stamped message stating "Stopping folder "location" - Folder path missing." This message will continue to be visible even after the folder comes back online. Was this done on purpose or should this message automatically go away after the folder comes back online?

Given many other (correct) choices for Syncthing leaning towards mass adoption and simplicity would the program be better served if this message were to automatically go away if a given missing folder comes back online?

Syncthing Version: v0.14.36

**Comment by AudriusButkevicius** [comment]
There was a ticket like this not long ago. This is done on purpose so that you know this has happened.
