### ISSUE TITLE
discosrv: -nat flag

### ISSUE THREAD

**Issue by aviau** [syncthing/syncthing#4333]
It looks like strelaysrv and stdiscosrv do not use upnp. It would be great if they did. They would just work out of the box in more situations.

Edit: ahh. There is ``-nat``. Sorry :)

**Comment by aviau** [comment]
Hmm

**Comment by AudriusButkevicius** [comment]
The fact that you are behind a NAT is probably not ideal, as your external IP will change which is is a bit crap for discovery server to disappear

**Comment by aviau** [comment]
But you are testing the servers, no? Also, my IP hasn't changed in months (years?).

**Comment by AudriusButkevicius** [comment]
The thing is NAT mapping is only useful when you advertise something. 

The port we might be given is random, so starting a discovery server on a random NAT port is not very useful (especially as the port might change every restart).

I think a one off manual port mapping is the right answer here.

**Comment by aviau** [comment]
Right, makes sense.

**Comment by aviau** [comment]
Somewhere in the future of syncthing I might be able to advertise my discovery server using dht. However in that future I guess discovery servers won't even make sense anymore ;)
