### ISSUE TITLE
Document behaviour of `-reset-database`

### ISSUE THREAD

**Issue by HaleTom** [syncthing/syncthing#4334]
The only documentation in the [wiki](https://docs.syncthing.net/users/syncthing.html?highlight=#cmdoption-reset-database) on `-reset-database` is:

> Reset the database, forcing a full rescan and resync.

[This forum post](https://forum.syncthing.net/t/recreate-synced-folders-after-data-loss/10423/5?u=ataraxy) shows that `.stfolders` are created.

Given that this has implications for unmounted disks, I suggest that this (and any other behavour) be documented.

**Comment by HaleTom** [comment]
\[Linking to Recreate missing folder marker and rebuild folder content #4225 as the resolution for that issue.\]

**Comment by AudriusButkevicius** [comment]
We have a separate docs repo that is maintained by the community, so feel free to contribute.
