### ISSUE TITLE
Folder deletion is not synced, if folder contains ignored files.

### ISSUE THREAD

**Issue by nalt** [syncthing/syncthing#4336]
Folder deletions are not synced, if there are ignored files in a folder.

- Have some ignore patterns, e.g. ignore *.bak
- Create a folder on host A, wait until it is fully synced
- Add a file *.bak into the folder on host B
- Delete folder on host A
- Host B will delete all files in the folder except the .bak-file. It logs:
syncthing:INFO: Puller (...): delete: remove ...: directory not empty
syncthing:INFO: Folder ... isn't making progress. Pausing puller for 1m0s.

The user needs to intervene and perform the sync manually, i.e. delete the folder on host B. If the user does not notice, syncthing will retry every minute and fail.

Other sync tools ran into the same issue. Often, there is a rule to delete folders, if there are only ignored files preventing the deletion.

### Version Information
Syncthing Version: v0.14.29
OS Version: Ubuntu 16.04

**Comment by AudriusButkevicius** [comment]
The documentation explains this.

**Comment by AudriusButkevicius** [comment]
Actually, nowadays even the ignore dialog explains this, but perhaps not enough emphasis if people still open issues.

**Comment by nalt** [comment]
Sorry for asking and thanks for your quick help! The hint wasn't in the ignore dialog in 14.29 yet.

What about a checkbox in the UI to make this the default option for all patterns? For normal users, this would make syncthing more usable than adding a cryptic prefix to already cryptic ignore patterns.

**Comment by AudriusButkevicius** [comment]
I think once we have a major release we should invert the behaviour etc, but there is a big ticket talking about an overhaul of the whole system in general so perhaps this falls under that.

**Comment by calmh** [comment]
I think the error message that happens when ignored files are present in a deleted directory sucks. It's not obvious at all what to do to fix it unless you understand the underlying issue, especially since the files that are in the way are often hidden.

That said I'm unconvinced that deleting them by default is the right / expected thing to do. I'd want to see some empirical data (prior art; surveys; whatnot) in order to change it.

**Comment by AudriusButkevicius** [comment]
I think inverting is the right thing, or splitting it into two lists.

**Comment by calmh** [comment]
Splitting is nice in that it completely sidesteps the issue - there is no default and the user must implicitly make the choice when writing the ignore patterns.

But it sucks to then merge the lists and have them in a single file on disk.

**Comment by AudriusButkevicius** [comment]
I don't think its rocket science to find things with a prefix, we already do that when computing the match result.

**Comment by canton7** [comment]
>  especially since the files that are in the way are often hidden. 

I hate to suggest even more magic, but maybe clear out hidden files by default, leave non-hidden ones by default?
