### ISSUE TITLE
Usability: confirmation before deleting everything

### ISSUE THREAD

**Issue by 0-wiz-0** [syncthing/syncthing#4345]
A couple months ago I had the following problems:
One of the syncers of a >100GB share had it on an external hard disk. That disk had problems starting up from sleep and showed up empty (in Windows; it was fine once dis- and reconnected). syncthing decided that that user had emptied out the whole sync area, and proceeded to delete everything on all connected hosts, leading to 100GB needing to be synced from zero. 

It's arguably correct. However, for usability I think it would be better if syncthing asked for confirmation when everything would be deleted, or would ignore such a host by default (perhaps optionally), because I think it's a rare occurrence where you really want this to happen.

**Comment by wweich** [comment]
That's what the `.stfolder` file is for. Had the folder been really empty, the ` .stfolder` file would have been missing and Syncthing would have stopped the folder with an error message like "folder marker missing".
