### ISSUE TITLE
Hashing Benchmarks slow down Startup Considerably

### ISSUE THREAD

**Issue by Nutomic** [syncthing/syncthing#4348]
I just did some tests to see how we can speedup the Syncthing start on Android. For that, I added log statements around the following code block in main.go:
```
sha256.SelectAlgo()
sha256.Report()
perfWithWeakHash := cpuBench(3, 150*time.Millisecond, true)
l.Infof("Hashing performance with weak hash is %.02f MB/s", perfWithWeakHash)
perfWithoutWeakHash := cpuBench(3, 150*time.Millisecond, false)
l.Infof("Hashing performance without weak hash is %.02f MB/s", perfWithoutWeakHash)
```

According to the logs, this takes more than 3 seconds to run on my Nexus 5. When I commented these lines out and hardcoded `weakhash.Enabled = false`, the app was available almost instantly.

From what I can see, there is no way to disable the benchmarks via parameters or config. So there are a few options:
- add an option, to disable all benchmarks (via environment variable or parameter)
- run the benchmark only on first start, and cache the result as long as the CPU doesn't change (but that will still slow down the initial start)
- optimize the benchmark, so that it runs much faster
- run the benchmark asynchronously, so it doesn't block startup (but that would still be a waste of cpu/battery)

### Version Information

Syncthing Version: v0.14.32
OS Version: Android 6

**Comment by Nutomic** [comment]
Time from first log output of Syncthing to web gui becoming available, with hash benchmarks:
```
12:20:58.157 I/SyncthingNativeCode: [G5OLB] 03:20:58 INFO: syncthing v0.14.32 "Dysprosium Dragonfly" (go1.8 linux-arm) felix@p50 2017-06-29 13:47:42 UTC [noupgrade]
...
12:21:01.620 I/SyncthingService: Web GUI has come online at https://127.0.0.1:8384
```
-> 3.463s

without hash benchmarks
```
12:04:48.846 I/SyncthingNativeCode: [G5OLB] 03:04:48 INFO: syncthing v0.14.32-dirty "Dysprosium Dragonfly" (go1.8 linux-arm) felix@p50 2017-06-29 13:47:42 UTC [noupgrade]
...
12:04:49.159 I/SyncthingService: Web GUI has come online at https://127.0.0.1:8384
```
-> 0.313s

Relevant issue: https://github.com/syncthing/syncthing-android/issues/517

**Comment by calmh** [comment]
There is an `STHASHING` environment variable to select the sha256 code, which when set to `standard` disables *one* of the benchmarks but not the other. I could imagine disabling all benchmarking when that is set, as it's only used to print something during startup in that case and we can just skip that.

Similarly we could add a `STWEAKHASHING` that could be set to on or off to enable or disable weak hashes without benchmark.

("optimizing" the benchmarks doesn't work unfortunately, they need to run for roughly as long as they do to give anything reliable. Which is currently 3 * 150 ms per test, and there are four tests, so the total should be about two seconds.)

**Comment by calmh** [comment]
Ah, there is already a config options for the weak hashing. We can just skip the benchmark when it's not set to "auto".

**Comment by Nutomic** [comment]
So I need to set `STHASHING=minio` as environment, and `<weakHashSelectionMethod>never</weakHashSelectionMethod>` in the config, correct? Btw an environment variable would be nicer, then I wouldn't have to handle the same thing in two places.

**Comment by calmh** [comment]
The weak hash thing is legitimately a config option as it affects behavior and that's what the config is for. :) The STHASHING thing is a bit more oddball as it's something that doesn't affect what the user sees but also needs to be handled before we load our keys and stuff (as we need a working sha256 at that point)...

**Comment by Nutomic** [comment]
Okay fair enough.

**Comment by wweich** [comment]
Just updated to 0.9.13 and still get this log lines:

```
[ZKOVT] 18:44:02 INFO: syncthing v0.14.37 "Dysprosium Dragonfly" (go1.8 linux-arm64) felix@p50 2017-08-24 04:26:12 UTC [noupgrade]
[ZKOVT] 18:44:02 INFO: My ID: ZKOVTDG-......
[ZKOVT] 18:44:03 INFO: Single thread SHA256 performance is 885 MB/s using minio/sha256-simd (74 MB/s using crypto/sha256).
[ZKOVT] 18:44:04 INFO: Hashing performance with weak hash is 456.48 MB/s
[ZKOVT] 18:44:05 INFO: Hashing performance without weak hash is 767.91 MB/s
[ZKOVT] 18:44:05 INFO: Weak hash disabled, as it has an unacceptable performance impact.
```

Also tried setting the ENV var in the debug settings of the app, but that didn't help either.

**Comment by calmh** [comment]
The PR isn't yet merged Syncthing-side, never mind included in an actual release.
