### ISSUE TITLE
TestTrashcanCleanout fails randomly (v0.14.37)

### ISSUE THREAD

**Issue by decathorpe** [syncthing/syncthing#4351]
I tried building the new syncthing release on fedora, but I hit this error in the tests - which hasn't been happening with earlier versions. Since it's only happening on the armv7hl build VM (which is the slowest), I suspect it is timing related / a race condition.

```
+ go test -compiler gc -ldflags '' github.com/syncthing/syncthing/lib/versioner
--- FAIL: TestTrashcanCleanout (0.01s)
	trashcan_test.go:69: empty directory should have been removed
FAIL
FAIL	github.com/syncthing/syncthing/lib/versioner	3.063s
```

Syncthing Version: v0.14.37
OS Version: fedora rawhide/28
go version: 1.9beta2

**Comment by calmh** [comment]
This doesn't look like a timing related test. It could fail if there's something else creating files in the directories under test though.

**Comment by decathorpe** [comment]
I just ran the builds again, and now - in addition to armv7 - the same test also failed on x86_64 and i686. So there's definitely something going wrong, but I'm not sure what or why.

Also, it shouldn't be possible for something else to create files in the build directories during the tests, since "go test" is the only thing running in the build containers at that time.

**Comment by calmh** [comment]
The order shouldn't matter, so I can't see why the test might fail. You'll have to debug it. The code is in lib/versioner/trashcan.go#cleanoutArchive

**Comment by decathorpe** [comment]
Looking at the diff of `lib/versioner/trashcan.go` between v0.14.36 and v0.14.37, the refactoring from `os` to `fs` looks pretty straightforward - and since I'm pretty new to go myself, I don't have the capability (or time) to debug the newly used `fs` abstraction code itself.

So, if you think the test failure is not indicative of a real bug in the `fs` code but only a fluke that results from brittle tests, I'll just skip this test and push 0.14.37 to fedora. However, if it might be a real bug, I'll hold off from shipping v0.14.37 for the time being - or until this problem can be resolved.

**Comment by calmh** [comment]
I don't think it's a brittle test - it should work always as far as I'm concerned. But the test passes on all our environments so I can't debug it without a reproducer.

**Comment by lfam** [comment]
I'm seeing the same issue with 0.14.39 while building in GNU Guix, but not on all my machines. I'll try to find time to learn how to add the error checks and bring more information here.

**Comment by decathorpe** [comment]
I was trying to reproduce this with syncthing v0.14.44, but I can't trigger the error on any architecture anymore. I'll close this issue for now (since the issue isn't manifesting anymore, AFAICT). If it pops up again, I'll re-open this issue.
