### ISSUE TITLE
Add receive-only mode to folders

### ISSUE THREAD

**Issue by dhs-rec** [syncthing/syncthing#4355]
Hi,

in its current form, using send-only mode on a folder, effectively limits possible setups to one master which doesn't accept changes to that folder from other nodes. OTOH, using read-write on every node makes them equal peers where all changes on all nodes are propaged to every other node. What's missing here is a receive-only node to allow a setup with a handful of master nodes and lots of slaves, which are not allowed to send anything to the masters, for example to roll out changes to all nodes of a web server cluster.

There could also be options to define what should happen with local changes on such nodes (ignore, discard).

**Comment by AudriusButkevicius** [comment]
Please search existing issues before opening new ones #62

**Comment by dhs-rec** [comment]
I did, but #62 was about devices, not folders.
