### ISSUE TITLE
GUI Listen Adress IP Range

### ISSUE THREAD

**Issue by fransozen** [syncthing/syncthing#4356]
As of v0.14.37, the only two options for accessing the GUI is either to allow everybody (0.0.0.0) or allow a single IP adress. 

Since syncthing is often running on servers it would be nice to reduce (or increase, depending on your point of view) the number of allowed IPs, allowing only some subnets to access the interface, decreasing by the same way the attack surface of the application.

This would also be intresting for companies who's IT management often reside on a specific subnet/vlan that average joes and janes are not allowed to access.

**Comment by AudriusButkevicius** [comment]
Your firewall can do that.

**Comment by canton7** [comment]
This is what firewalls are for. 

I'm also kit sure how you made Syncthing accept connections from a single IP only: I've never seen that option. If you put an IP address in the "Listen Address" field, that specifies the IP of the interface that Syncthing should listen on (as opposed to 0.0.0.0, which means "all interfaces", or 127.0.0.1, which means the loopback interface).
