### ISSUE TITLE
XSS-related HTTP headers

### ISSUE THREAD

**Issue by leonyu** [syncthing/syncthing#4360]
Syncthing does not appear to produce XSS-related HTTP headers that are designed to prevent some basic browser-side attacks. ([Clickjacking](https://en.wikipedia.org/wiki/Clickjacking), [XSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery)) Those should probably be added to prevent RFC1918-style attacks. 

ref: 
* https://www.owasp.org/index.php/Security_Headers
* https://securityheaders.io/

**Comment by calmh** [comment]
Sure
