### ISSUE TITLE
Folder marker failsafe doesn't work for paused folders

### ISSUE THREAD

**Issue by CyberFoxHax** [syncthing/syncthing#4362]
A couple of times I've lost my data because i hooked up Syncthing to an empty folder and instead of pulling the latest copy of what's in the cloud everything gets wiped from the cloud... Why would this happen? Well if you're relocating to a new directory. Syncthing provides no function to do this, so i cook it up by editing the XML. (So yeah it's really my own fault and now I'm here)
So i change the old path to the new path and then restart Syncthing. Synthing then proceeds to wiping the data across all devices.

You could argue that deleting everything is subjective to the users decisions.
Plis "rm –rf /" said no one ever.

The failsafe is simple. If Syncthing detects that your "new change" includes deleting everything from the root. Simply stop pushing updates and await a user response from the control panel. Mark the folder in yellow saying "Confirmation Required"."Please confirm whether you would like to download latest copy or, clear out the directory [Download All] [Delete All]"

That is all, thanks for a great project!

**Comment by calmh** [comment]
It doesn't do this unless you both misconfigure it (i.e., point it to a suddenly empty directory inadvertently) *and* create the `.stfolder` marker to indicate that the directory is valid and not empty, etc. The latter is intended as the failsafe against exactly this.

**Comment by AudriusButkevicius** [comment]
I think this can happen for paused folders, I recall CreateRootMarker being wedged in the unpause code, which probably should not be there.

**Comment by CyberFoxHax** [comment]
@calmh Ok. I thought the `.stfolder` would only appear if you had file versioning enabled. Which i usually didn't (Unwise, I've learned). Anyway, The destination folder has been newly created. So nothing inside.

@AudriusButkevicius Yes. I have been pausing it before shutting down Syncthing if that helps.

**Comment by calmh** [comment]
OK that's a bug then

**Comment by AudriusButkevicius** [comment]
I checked the code, the pause code does CreateRoot() not CreateMarker(), so I claim this is impossible, unless OP provides a repro case.
