### ISSUE TITLE
Option to allow deletion of ignored files in an empty folder?

### ISSUE THREAD

**Issue by DarwinAwardWinner** [syncthing/syncthing#4365]
Sometimes when I delete a directory on one device, another device can't delete that directory because there's an ignored file present in that directory. This results in an "out of sync" status on that directory until I manually delete the offending ignored file. It would be nice to have a per-folder option to tell Syncthing that it's safe to delete ignored files in order to delete the directory that contains them.

### Version Information

Syncthing Version: v0.14.37
OS Version: Android

**Comment by AudriusButkevicius** [comment]
Read the docs before opening issues please.

**Comment by DarwinAwardWinner** [comment]
I've had another look through the documentation at https://docs.syncthing.net/index.html, and I cannot find any information relevant to the issue I've described. The closest sections I could find were https://docs.syncthing.net/users/ignoring.html#effects-on-in-sync-status and
https://docs.syncthing.net/advanced/folder-ignoredelete.html, but both are describing unrelated features/problems.

**Comment by AudriusButkevicius** [comment]
It's even described in the ignore dialog in the newer versions.

**Comment by AudriusButkevicius** [comment]
https://docs.syncthing.net/users/ignoring.html#patterns
```
A pattern beginning with a (?d) prefix enables removal of these files if they are preventing directory deletion. This prefix should be used by any OS generated files which you are happy to be removed.
```

**Comment by DarwinAwardWinner** [comment]
Ok, I found it. I missed the fact that that ignore file syntax had been changed recently, (and I edit the ignore files on the command line, so I didn't see the updated dialog help text). Sorry for taking up your time on this.
