### ISSUE TITLE
Retrieving empty folders

### ISSUE THREAD

**Issue by Baklap4** [syncthing/syncthing#4367]
I have a server A, Client B and Client C. All running syncthing v0.14.31 on Ubuntu 17.04 (Client's) and Debian Jessie (Server).
Server A has a folder which is shared among client B and C so server A is set to send / receive. All with the default scanning set to 60 secs and pulling in random order.

The issue i'm having right now is that when my shared folder contains folders which contain around a 500mb of data are added on client B it gets perfectly synced to server A but whenever i connect client C which retrieves from server A in random order (and scans every 60 secs) it may occur syncthing makes an empty folder, throws a dice, and sees the empty folder on client C and wants to 'share' that one with server A while on server A there's content within that folder.

I expected client C would first get in sync with server A and then send his (client b) updates to server A, however i find that it removed files from my server..

**Comment by AudriusButkevicius** [comment]
No, syncthing doesn't do that, you've botched something potentially by adding/removing folders, moving them around or modifying config manually. I suggest you try and produce a repro, once you have that we can reopen.

**Comment by calmh** [comment]
Syncthing only considers a file deleted when it's first present locally, present in the database, and then no longer present. It does not consider a file deleted just because it hasn't been synced yet.
