### ISSUE TITLE
Syncthing won't sync a file and I can't find which one

### ISSUE THREAD

**Issue by kalsan** [syncthing/syncthing#4368]
I'm having 3 machines which sync the same directories. In the left side ("Directories"), no sync activity is being shown (all are "up to date"). However on the bottom right, under "remote devices", there is constant sync activity shown and it doesn't go away, even across reboots, updates and several weeks of other activity, as follows:

- Machine A says: B up-to-date, C synching 99% 10.4KiB
- Machine B says: A up-todate, C synching 99% 10.4KiB
- Machine C says: A and B both synching 99% 10.4KiB

I'd love to get rid of this behavior, but I can't find out which file(s) is/are not being synched across A and C and across B and C. There are thousands of files that could be the cause.

How can I find out which file(s) is/are causing this problem?

**Comment by AudriusButkevicius** [comment]
If I had a dollar for every time someone didn't read the issue template...

Use the forum for support.
