### ISSUE TITLE
Files get emptied on Sync

### ISSUE THREAD

**Issue by DaCoolboy** [syncthing/syncthing#4371]
Since a couple of months, when I sync new files, sometimes, some specific files get modified by other devices (that were about to get updated/transmitted) which just reduces the filesize to 0 bytes and syncs that empty husk of a file instead of my actual updated files. The change is visible in the Global Changes window,
this has come from different devices but the heaviest offender is my Android as a Syncthing device.
This happens to files I update very frequently.

This is difficult to reproduce, let alone diagnose I suspect, but I am willing to help from providing logs to letting one of the devs get a hands on look via SSH or other means.

If I can assist somehow, let me know.

### Version Information

Syncthing Version: v0.14.37
OS Version: Debain Sid/ Debian Stretch / OSMC Stable / Windows / Android

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.

**Comment by calmh** [comment]
This is typically something else that interacts with the files beside Syncthing. Android does a lot of magic with photos, for example.

**Comment by DaCoolboy** [comment]
Alright, migrated it to [here](https://forum.syncthing.net/t/files-get-emptied-on-sync/10562)
