### ISSUE TITLE
SyncThing refuses to sync to sdcard even with availible permissions. 

### ISSUE THREAD

**Issue by ViperZer0** [syncthing/syncthing#4373]
I am running Android 4.4.4 on CyanogenMod CM11. My phone is rooted and has the infamous sdcard write permissions fixed. The problem, I believe, comes from the app. I might be wrong, but both Resilio Sync and SyncThing both seem to just sort of assume that write permission to the SD card is restricted, even though it isn't. At no point am I given an option to sync to the SD card, the app won't even let me try it. I think this fault lies with the app, though again, I could be wrong. I would very much appreciate seeing an option to at least try to sync to SD card.

**Comment by AudriusButkevicius** [comment]
This is the wrong repository, please reopen the issue [https://github.com/syncthing/syncthing-android](here)
