### ISSUE TITLE
Odd info message after fs change

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4375]
```
Sep 18 12:07:41 pseudo syncthing: [ITZRN] INFO: Puller (folder "lightroom", file "Lightroom
  Catalog.lrcat-journal"): pull: peers who had this file went away, or the file has changed while
  syncing. will retry later
Sep 18 12:07:46 pseudo syncthing: [ITZRN] INFO: Puller (folder "\"Lightroom\" (lightroom)", dir
  '\x00'): {Lightroom Catalog.lrcat-journal peers who had this file went away, or the file has changed
  while syncing. will retry later}
Sep 18 12:07:46 pseudo syncthing: [ITZRN] INFO: Folder "lightroom" isn't making progress. Pausing
  puller for 1m0s.
```

(line breaks for clarity)

Odd one in the middle. Folder description is double quoted. The `dir '\x00'` part is nonsense.

**Comment by imsodin** [comment]
The folder problem was introduced by me in #4338, see #4376, and the `dir '\x00'` I do not understand and I don't think it is due to these changes.

**Comment by koppor** [comment]
The thing is that the synchronization is also not working anymore. Is it really about changed logging or is there something deeper hidden in that logs?

My next log lines are:

```
4QJNC] 09:13:20 INFO: Folder "BTSync" isn't making progress. Pausing puller for 1m0s.
[4QJNC] 09:13:26 INFO: Folder "BTSync" error is cleared, restarting
[4QJNC] 09:13:32 INFO: Folder "BTSync" error is cleared, restarting
[4QJNC] 09:13:37 INFO: Folder "BTSync" error is cleared, restarting
```

The sync really does not make any progress: I don't see the new files on this machine.

**Comment by AudriusButkevicius** [comment]
Please use forum for support. This is purely a cosmetical change.
