### ISSUE TITLE
Chromium: don't show the shared folder in popup (on device)  

### ISSUE THREAD

**Issue by slytomcat** [syncthing/syncthing#4377]
When I move mouse pointer over Shared folders in Device section I got pop-up with some code but not a list of folders (see screenshot https://itmages.ru/image/view/6106162/da0219e7).

All the rest pop-ups works as expected.

### Version Information

Syncthing Version: 0.14.37, Linux (64 bit) 
OS Version: Xubuntu 16.04 
Browser Version: Chromium 60.0.3112.113 Built on Ubuntu, running on Ubuntu 16.04 (64 bit)

**Comment by slytomcat** [comment]
It seems that code is fro this line
https://github.com/syncthing/syncthing/blob/1088eb12ea4982f7402feb603b0914c1406a45e9/gui/default/index.html#L648

But I can't see what's wrong with it.

**Comment by AudriusButkevicius** [comment]
https://stackoverflow.com/questions/18230868/how-do-you-get-angularjs-to-bind-to-the-title-attribute-of-an-a-tag

Feel free to make a pull request fixing this (and potentially other cases of the same problem).

**Comment by imsodin** [comment]
@AudriusButkevicius The weird thing is the same syntax e.g. for shared with on folders works:
https://github.com/syncthing/syncthing/blob/1088eb12ea4982f7402feb603b0914c1406a45e9/gui/default/index.html#L397

**Comment by slytomcat** [comment]
@AudriusButkevicius, unfortunately AngularJS - is not the one tool that is I familiar to.
I'll try to look through and understand it but if somebody else can do it, I'm sure that it can be faster and better than I can do.

**Comment by AudriusButkevicius** [comment]
I think because it's a plain expression, but it seems that the right way is using ng-attr anyway.

**Comment by slytomcat** [comment]
Hah! I've cloned the source, changed 'title' too 'ng-attr-title' in lines 397 and 648, compiled the source and it fixed the issue!
I'm not sure about other browsers/platforms, but it works as expected on my computer at least.
