### ISSUE TITLE
lib/model: Incorrect "Unexpected folder" messages when folders are paused locally

### ISSUE THREAD

**Issue by scienmind** [syncthing/syncthing#4380]
When connecting to remote devices that share a folder paused locally, the following is printed to the console:
```
[IDIDID1] 21:01:08 INFO: Unexpected folder PAUSED_FOLDER sent from device "IDIDIDID2"; ensure that the folder exists and that this device is selected under "Share With" in the folder configuration.
```

It may be that it's just a log message from pre-folder-pause era - in that case the message is incorrect in this context and may confuse users.

When un-pausing the folders back, warnings pop up (yellow message boxes on top of WebUI, prompting to share the just-resumed folders with Device 2 (while it is already shared with Device 2).

(The warning messages are not always popping up, seems like it is related with ST being restarted while the folders are paused.)

### Version Information

Syncthing Version: v.0.14.38
SyncTrayzor Version: v.1.1.18
OS Version: Windows 10 x64

**Comment by AudriusButkevicius** [comment]
Actually this is not true, there is a paused check just above the line that prints the error.
Do you have a repro? To me this seems like a genuine, shared one way kind of thing.

**Comment by AudriusButkevicius** [comment]
Other log messages that do have this message and do not check for a paused folder are in debug level, not info.
