### ISSUE TITLE
Hide temporary files on Windows

### ISSUE THREAD

**Issue by schnappijedi** [syncthing/syncthing#4382]
Version 0.14.38 unhid hidden folders on multiple Windows 10 64-bit machines. After the automatic update to 0.14.38 .stfolder, .stignore (when applicable), .stversions (when applicable) were all unhidden in Syncthing folders. Other hidden files in operating system also became unhidden after upgrade. Although unsure if this spread across operating system or just in Syncthing folders because became aware of this when saw lots of ".tmp" files (which were unhidden) in Syncthing folders. Not sure if . (dot) files that found in user profile folder were already unhidden or not.

Not entirely bad thing because learned a new windows command as a result. Running below commands in administrator command prompt solved issue.

ATTRIB +H /s /d C:\.*
ATTRIB +H /s /d C:\*.tmp

A backslash needs to come after C: in above command but is being edited out. Not sure how to force what is written verbatim to be shown.

This occurred on three Windows 10 64-bit machines so expect can be replicated.

### Version Information

Syncthing Version: v0.14.38
OS Version: Windows 10 Professional 64-bit

**Comment by ProactiveServices** [comment]
Since upgrading to 0.14.38 I've noticed new .stfolders being created, without the Hidden attribute, but have not come across any existing files or folders being un-Hidden.

**Comment by schnappijedi** [comment]
This makes sense. There has to be a ".stfolder" in every folder being shared for Syncthing to function. Unless viewing hidden files this folder would not have been visible.

**Comment by calmh** [comment]
There's a bug in the stfolder conversion code that creates the new folder marker unhidden.

I don't think this affects anything else?

**Comment by schnappijedi** [comment]
The only other item confirmed effected is .tmp files within Syncthing folders (they were also unhidden).

**Comment by calmh** [comment]
Reopening to remember to investigate that

**Comment by calmh** [comment]
As far as I can tell we have never actually hidden the temp files, except on Unixes where the hiding is implicit based on the file name. As such this is not a regression, although it seems a valid thing that we might want to do.

**Comment by schnappijedi** [comment]
Made assumption that they were already hidden. Thanks.

**Comment by Diapolo** [comment]
I'm also seeing a .stfolder folder, which was hidden before AFAIK. I have to say, that I have the option to see hidden files activated all the time, so something else changed? Using v0.14.38, Windows (64 bit) here.

**Comment by schnappijedi** [comment]
Don't totally understand GitHub but it appears that this has been fixed and will be included in the next release if the fix has been accepted into the project (think this is called accepting a pull request). At that point the .stfolder will become hidden again

https://github.com/syncthing/syncthing/commit/a365ae51c47fa2bad19a0500c277b22f799bf85e
https://github.com/syncthing/syncthing/commit/3ee12464b4fec0eb7d9fc250d1fad933ef86c91b

Still its interesting that you had the option to see hidden folders activated but only now started seeing the .stfolder. If viewing hidden files the .stfolder should always have been visible.
