### ISSUE TITLE
Can't remove paused folder

### ISSUE THREAD

**Issue by sferra** [syncthing/syncthing#4385]
I seem unable to remove a directory while it is paused. The action causes a panic message and syncthing to restart.

panic: runtime error: invalid memory address or nil pointer dereference  
[...]  
[monitor] 10:26:07 INFO: Syncthing exited: exit status 2  
[monitor] 10:26:08 INFO: Starting syncthing 

[panic-20170920-102607.log.txt](https://github.com/syncthing/syncthing/files/1317110/panic-20170920-102607.log.txt)

### Version Information

Syncthing Version: v0.14.38
OS Version: Ubuntu 17:04

**Comment by AudriusButkevicius** [comment]
Please check existing closed issues before opening new ones.

**Comment by sferra** [comment]
i did and couldn't find any. please add a reference to the respective issue

**Comment by calmh** [comment]
Duplicate of #4357

**Comment by sferra** [comment]
thank you
