### ISSUE TITLE
can't access web gui since version 0.14.37 (windows)

### ISSUE THREAD

**Issue by user514** [syncthing/syncthing#4386]
- what happened,

  Since version 0.14.37 I can't access my web gui through my personalized port 127.0.0.1:XX84 or <mylocalIP>:XX84 or even setting config.xml to default with:
`<address>0.0.0.0:8384</address>`

- any steps to reproduce the problem.

  Sure. Just pressing the blue button to upgrade to 0.14.37 (or later to 0.14.38) and the syncthing log start saying:

syncthing log with the listenerSupervisor error:

`[X23LE] 18:51:37 INFO: syncthing v0.14.38 "Dysprosium Dragonfly" (go1.9 windows-amd64) teamcity@build.syncthing.net 2017-09-07 09:40:46 UTC
[X23LE] 18:51:37 INFO: My ID: XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXQ

[X23LE] 18:51:38 INFO: Single thread SHA256 performance is 224 MB/s using minio/sha256-simd (167 MB/s using crypto/sha256).
[X23LE] 18:51:39 INFO: Hashing performance with weak hash is 201.12 MB/s
[X23LE] 18:51:39 INFO: Hashing performance without weak hash is 220.63 MB/s
[X23LE] 18:51:39 INFO: Weak hash enabled, as it has an acceptable performance impact.
[X23LE] 18:51:39 INFO: Ready to synchronize "xxxx1" (xxxxc-xxxxp) (readwrite)
[X23LE] 18:51:39 INFO: Ready to synchronize "xxxxxxxxxxxx2" (xxxxc-xxxxg) (readwrite)
[X23LE] 18:51:39 INFO: Send rate is unlimited, receive rate is unlimited
[X23LE] 18:51:39 INFO: Rate limits do not apply to LAN connections
[X23LE] 18:51:39 INFO: Using discovery server https://discovery-v4-2.syncthing.net/v2/?id=XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXC
[X23LE] 18:51:39 INFO: Using discovery server https://discovery-v4-3.syncthing.net/v2/?id=XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXZ
[X23LE] 18:51:39 INFO: Using discovery server https://discovery-v4-4.syncthing.net/v2/?id=XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXW
[X23LE] 18:51:39 INFO: Using discovery server https://discovery-v6-2.syncthing.net/v2/?id=XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXC
[X23LE] 18:51:39 INFO: Using discovery server https://discovery-v6-3.syncthing.net/v2/?id=XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXZ
[X23LE] 18:51:39 INFO: Completed initial scan of readwrite folder "xxxx1" (xxxxc-xxxxp)
[X23LE] 18:51:39 INFO: Completed initial scan of readwrite folder "xxxxxxxxxxxx2" (xxxxc-xxxxg)
[X23LE] 18:51:59 INFO: Using discovery server https://discovery-v6-4.syncthing.net/v2/?id=XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXMIAW

**[X23LE] 18:52:09 INFO: c.S.listenerSupervisor: Failed service 'dynamic+https://relays.syncthing.net/endpoint' (1.000000failures of 2.000000), restarting: true, error: "{dynamic+https://relays.syncthing.net/endpoint dynamic+https://relays.syncthing.net/endpoint} returned unexpectedly", stacktrace: [unknown stack trace]**`

 ...overwrite the .exe with version 0.14.36 and work like a charm.

I have upgraded two other machines with linux to 0.14.37 without issues. Only happen this in my windows machines (more than one, different geolocations, same problem)

I have been upgrading syncthing for windows and linux since version 0.14.8 without any problem.

### Version Information

Syncthing Version: when updating 0.14.36 to v0.14.37 (also fails with 0.14.38)
OS Version: Windows 8.1 64b / (linux no problems, same update)
Browser Version: Google Chrome 60.0.3112.113 (Official Build) (64-bit)

**Comment by calmh** [comment]
Works fine for me. Local firewall?
