### ISSUE TITLE
Feature Request: Add -node-id command line switch

### ISSUE THREAD

**Issue by tobiastom** [syncthing/syncthing#4387]
I'm trying to setup syncthing in an automated way and I want to write the configuration myself. This would include all devices and all folders I want to share.

For this I need the node ID of each host. It would be very helpful to have access to the node ID through the command line interface. 

Would it make sense to add

    syncthing -node-id

which will read the configuration it currently has, get the node ID and just print it out.

**Comment by AudriusButkevicius** [comment]
There was multiple posts on the forum explaining how to compute it manually.

**Comment by calmh** [comment]
Nonetheless I think this is valid-ish
