### ISSUE TITLE
Android: forever 'Loading...'

### ISSUE THREAD

**Issue by Ploppz** [syncthing/syncthing#4388]
I just updated Syncthing for Android, and when I try to start it, it just says 'Loading...' indefinitely.

### Version Information

Syncthing Version: v0.14.38 (according to the description on the Google Play page)
OS Version: Android 5.0.2

**Comment by AudriusButkevicius** [comment]
This is the wrong repository, please reopen the issue [https://github.com/syncthing/syncthing-android](here)
