### ISSUE TITLE
Case conflict results in file deletion

### ISSUE THREAD

**Issue by hungrywolf27** [syncthing/syncthing#439]
Steps to reproduce:
- Create a repository shared between a Linux node and a Windows node
- On the Linux node, create two files: TESTFILE.txt and testfile.txt, and give them different contents and modification times
- Let the nodes sync. One of the two files will sync to the Windows node.
- After a cycle or two of restarting the Windows node (without modifying the file), one of the two original files will be deleted from the Linux node.

This occurred on 0.8.21. I would appreciate if others can verify this.

**Comment by victorsegall** [comment]
For this issue and #1355 I want to warn you that, [per the BTSync Hacks blog](http://blog.bittorrent.com/2013/07/23/sync-hacks-how-to-deploy-web-projects-with-bittorrent-sync/), people will try to treat ST as a RAID-like NAS for their personal networks. They'll do things like pipe assets to an HTTPd straight out of an ST-synced tree. Wrong tool for the job not withstanding.

How conflict resolution for this type of file name collision is handled could become very important to someone down the line.

Magically overcoming case-sensitivity differences between NTFS and EXT, to cater to that or any other reason, seems dangerous. I agree with warn the user. It will be less destructive.

I believe that the Windows node should receive a Notification Area message to warn about the problem, which is also reported in the web GUI. The Linux node probably shouldn't be notified, as that could spam it for every node it fails to sync its conflicting files to.

Alternatively, you could pack the conflicting files with tar, name that how you like, and go ahead with the sync while also warning the Windows node. In that way, you have at least both prevented the collision and also given the data to the whole network.

**Comment by 101100** [comment]
> We now need to remember the mapping "FILE_conflict1" <-> "FILE" and "file_conflict2" <-> "file" so that we can send and interpret index updates from other devices correctly.

While this is a tricky situation, this same system could potentially handle filename encoding issues and characters that are illegal on certain OSes but not on others.  Having both `FILE.txt` and `file.txt` is similar to having a filename with "big omega" and another with "ohm sign".

**Comment by t184256** [comment]
I have a strange idea of how to solve the problem of storing those files, FILES and FiLeS on a case-insensitive host until the user comes to solve the problem. How about packing all of those into some popular case-sensitive archive format and point the user to extract whatever he needs whenever he needs from it? Sounds way cleaner than exposing all your hashing fantasies to the end-user.

"Syncthing conflicted file 46494c45" looks awful to me, but "conflict detected, please unpack the right version from ~/documents/unlucky.odt.conflict.7z", which has the conflicting files along with their origins, like "windows_pc/unlucky.odt" and "linux_pc/Unlucky.odt", sounds more adequate.

**Comment by devurandom** [comment]
@t184256 FiLeS-46494c45.ext FILES-54c49464.ext ?

**Comment by Zillode** [comment]
I think this was solved by introducing conflict resolution and https://github.com/syncthing/syncthing/commit/67f0c9bef0d1c311e577cbcf8293020d2dcd7013 ?

**Comment by calmh** [comment]
Possibly; unsure, requires testing.

**Comment by Zillode** [comment]
(manual test)
1. Create testfile.txt and TESTFILE.txt on linux
2. Sync with Windows
3. either testfile.txt or TESTFILE.txt is shown on Windows but the GUI says that we have 2 global and 2 local files.
4. Add TeStFiLe.txt to linux, this is synced to Windows and now shows TeStFiLe.txt as the only file (3 files tracked globally and locally for both platforms)
5. Add content to TeStFiLe.txt on Windows
6. This is synced to linux in the correct TeStFiLe.txt file
(Both Syncthing instances show an 'up to date' status in all steps)

Therefore I conclude that files are no longer destroyed on the linux platform, but you'll only see one of them on Windows. If you have other findings, please reopen.

**Comment by Nutomic** [comment]
So [this](https://github.com/syncthing/syncthing-android/issues/187) should also be fixed now?
