### ISSUE TITLE
panic: leveldb: internal key "\x01", len=1: invalid length

### ISSUE THREAD

**Issue by CONSULitAS** [syncthing/syncthing#4391]
> - what happened,

* Syncthing panics on start
```
Panic at 2017-09-22T12:53:05+02:00
panic: leveldb: internal key "\x01", len=1: invalid length
```
* `brew remove --force syncthing` followed by `brew install syncthing` didn't help

> - what you expected to happen instead, and

* just work 😄 

> - any steps to reproduce the problem.

* unknown, panic log attached:
[panic-20170922-125305.log.txt](https://github.com/syncthing/syncthing/files/1324274/panic-20170922-125305.log.txt)

### Version Information

Syncthing Version: `INFO: syncthing v0.14.38 "Dysprosium Dragonfly" (go1.9 darwin-amd64) brew@Sierra.local 2017-09-07 09:40:46 UTC [noupgrade]`
OS Version: Mac OS X 10.12.6, installed with brew
Browser Version: na

Thanks for any support!

**Comment by CONSULitAS** [comment]
Hmmm...

Worked around it by removing folder `index-v0.14.0.db` in `/Users/USERNAME/Library/Application\ Support/Syncthing/` 😄 

But it seems to be a bug.

**Comment by AudriusButkevicius** [comment]
It's not a bug, it's plain and simple database corruption.
