### ISSUE TITLE
windows: Crash.

### ISSUE THREAD

**Issue by HaoZeke** [syncthing/syncthing#4396]
The log is attached. The binary never runs and always exits.
This works even when administrative access has been granted.

[syncthing.log](https://github.com/syncthing/syncthing/files/1326598/syncthing.log)

### Version Information

Syncthing Version: v0.14.38
OS Version: Windows 7

**Comment by AudriusButkevicius** [comment]
Please read the docs on how it works before throwing miner claims around.

**Comment by AudriusButkevicius** [comment]
Are you using some special filesystem for C:\<User>\Documents\Sync?

**Comment by calmh** [comment]
For posterity and searchability;

```
Exception 0xc000001d 0xffffa9011ad79080 0xffffa9011ad79080 0x18000890c
PC=0x18000890c

syscall.Syscall(0x7ff806e9dc40, 0x2, 0x15e2b40, 0x2, 0x0, 0x1e0, 0xaf71e0, 0x1)
	C:/Go/src/runtime/syscall_windows.go:163 +0x69
syscall.SetFileCompletionNotificationModes(0x15e2b40, 0x2, 0xb784af, 0x3)
	C:/Go/src/syscall/zsyscall_windows.go:1727 +0x6f
internal/poll.(*FD).Init(0xc0423761e0, 0xb7846d, 0x3, 0xd22a28, 0xc04202dc38, 0x4c9fa0, 0xc04216e560)
	C:/Go/src/internal/poll/fd_windows.go:346 +0xf9
os.newFile(0x15e2b40, 0xc04216e560, 0x18, 0xb7846d, 0x3, 0xc04202dcb4)
	C:/Go/src/os/file_windows.go:57 +0x138
os.openDir(0xc04216e560, 0x18, 0x0, 0xc0000001ff, 0x0)
	C:/Go/src/os/file_windows.go:145 +0x2d5
os.OpenFile(0xc04216e560, 0x18, 0x0, 0xc0000001ff, 0x18, 0x0, 0x0)
	C:/Go/src/os/file_windows.go:163 +0x198
github.com/syncthing/syncthing/lib/fs.(*BasicFilesystem).DirNames(0xc04241a540, 0xb77e95, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/lib/fs/basicfs.go:214 +0xb9
github.com/syncthing/syncthing/lib/fs.(*walkFilesystem).walk(0xc04241a550, 0xb77e95, 0x1, 0x10a4280, 0xc04241a110, 0xc04216a3c0, 0x0, 0xc04217aa20)
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/lib/fs/walkfs.go:53 +0x1d2
github.com/syncthing/syncthing/lib/fs.(*walkFilesystem).Walk(0xc04241a550, 0xb77e95, 0x1, 0xc04216a3c0, 0xc04216a3f8, 0xc04216a3c0)
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/lib/fs/walkfs.go:88 +0xe4
github.com/syncthing/syncthing/lib/fs.(*MtimeFS).Walk(0xc04222a180, 0xb77e95, 0x1, 0xc04216a3c0, 0xc04217ad20, 0xc04216a3c0)
	<autogenerated>:1 +0x64
github.com/syncthing/syncthing/lib/scanner.(*walker).walk.func1(0xc042144090, 0x10a0b20, 0xc042030fc0, 0xc04217aa20, 0xc04217ad20)
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/lib/scanner/walk.go:116 +0x12d
created by github.com/syncthing/syncthing/lib/scanner.(*walker).walk
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/lib/scanner/walk.go:113 +0x216
```

**Comment by calmh** [comment]
Exception 0xc000001d is supposedly illegal instruction. Are you on an old or odd CPU?

**Comment by HaoZeke** [comment]
Sorry about the miner crap... My bad...

No there isn't anything special... Regular NTFS. (I have a dual booted majaro but this is on the windows only segment)

Also it's a pretty standard Core i3...
I'm using a Thinkpad Yoga to be exact.

**Comment by calmh** [comment]
I don't think that would do any good. Not that I have any idea what's wrong here. Hardware error maybe? Antivirus is the usual culprit in anything unexplainable in Windows.

**Comment by HaoZeke** [comment]
That's probably not it either... it's just running windows defender...
I also tried the 32-bit binary... same issue.

**Comment by bugith** [comment]
Did it ever worked (e.g. previous release) in this very machine ?
Would you think giving st a different homepath than default is worth a try (I thought about something wrong with your %userprofile% or %homepath% or the relevant variable name on Windows)
PS : not a coder I am

**Comment by bugith** [comment]
Or as Audrius said, something special on ACL for either your Docs or profile folder ?

**Comment by calmh** [comment]
Not reproducible / lacks data - reopen if this becomes actionable
