### ISSUE TITLE
Feature request: Collections a.k.a virtual folders for media libraries

### ISSUE THREAD

**Issue by steelman** [syncthing/syncthing#4397]
I find one particular usage scenario for syncthing possible but not very efficient: Media Library.

Let's say I've got a file server where I keep all my media (music, films, pictures) and several devices (smartphones, laptops) I use to watch and listen. The library is equipped with much larger storage than the "playback devices", so from time to time, I remove files form the devices and download new from the library. I would like to use syncthing to push desired media to my devices. However, I'd like to
meet several conditions:

1. Different devices store different sets of files.
2. A file need not to be copied around the library to push it to a device.
3. It is possible to remove a file from a device (to free storage).
4. Removal from a device does not remove a file from a library.
5. After a file is removed from a device it won't be pushed there until a I explicitly decide to.
6. New files are not pushed from devices to the library.

Condition 1. means there is a repository for each device.

Although the library has a lot storage I don't feel it should be necessary to have more than one copy of each media file, hence condition 2. Symlinks might do the trick, if copied to devices as regular files. (I know symlinks are unsupported, please read on.) Hardlinks might be even better but they don't work with directories.

When I am away from home and I don't want to listien to a particular track/album any more and I need some more free space on my storage I can remove files from a device, which doesn't mean I remove them from the library. I remove them only from the repository for that particular device. After I get back home, the removal of the file from the device is propagated to the library as a removal of a "symlink" from the repository rather than a removeal of the file containing media. These are conditions 3, 4 & 5.

If I want to add new media to the library I upload it out-of-band rather than putting in a collection (a.k.a virtual directory on a playback device). Condition 6.

Because symlinks are not supported by syncthing in any way I propose to store the metadata of collections (a.k.a virtual folders) in a database rather than a directory tree on a filesystem. Entries in the database should point at files in the library. The content of the files would be sent to a device along with metadata (e.g. path relative to the root of the repository).

If anything above is not clear, I will be glad to clarify it.

**Comment by AudriusButkevicius** [comment]
I hear ya. I suspect what you want is the 'next gen ignores" ticket which has a more friendly UI for selecting folders you want to sync. Closing this as dupe as I suspect that would cover your usecase.

**Comment by AudriusButkevicius** [comment]
You can already achieve something with ignores, but it's clunky for selecting things you want to listen to.

**Comment by steelman** [comment]
Theoratically, I guess so. But I am afraid not in practice.

With the library of hundreds GiB and devices capable of storing few GiB, the ignore list have to be huge.

Second, if I understand correctly the [documentation](https://docs.syncthing.net/users/ignoring.html#ignoring-files) I need to maintain .stignore on each device rather than in the library. syncthing can run on pretty much anything, including devices that do not provide convenient tools to manipulate ignore lists. In fact you need to keep twice as much data on devices: large ignore lists, full listing of the content of the library to choose files to add to or remove from the ignore list. 

Third. With ignore lists maintained on devices it is very cumbersome to add anything to the library. If you just add new files they will be pushed to all devices. If you add new content to .stignore in the library, you need to keep the entries until all devices have updated lists.

While point 1 and 2 may be considered as UI problems, the third one is definitely inherent to the distributed nature of the system and it is a problem syncthing is supposed to solve.

**Comment by dcarosone** [comment]
You can do all of this today, if your file server is zfs with dedup=on.

Just copy files to the per-device shares and remove them when done, no
extra space consumed on the server.

You could (I assume) also use hard links on the server, if they're all in
the same filesystem, but I've not tested this.

**Comment by AudriusButkevicius** [comment]
Ignore lists support inversion, so you can ignore everything apart from the content you listed. Furthermore you can have centralised ignores by using include directive and just including a normal file that is synced. That means ignores will be the same across on all devices.

**Comment by steelman** [comment]
@dcarosone, the assumption that my NAS a 64-bit machine is wrong, therefore I can't use ZFS. In fact it is rather small Marvel ARM SoC, which probably can't perform any deduplication without a huge performance hit. If you have read my first post, you know why hardlinks a are not enough for me.

@AudriusButkevicius, I must haven't been clear enough. Syncing ignore lists among different devices is not my goal. I want to have different media files on different devices served from a single library. Let me try to recreate your idea:

Ignore everything in the library except for *.stignore files, that are going to be pushed to devices.

```
!*.stignore
*
```

For each devices create _device-name_.stignore that unignores desired content, e.g. first-device.stignore

```
!First Album/Song 1.mp3
!First Album/Song 2.mp3
```

On each device include respective _device_.stignore into its .stignore, e.g.

```
#include first-device.stignore
```

Let's try it… No, it does not work. first-device.stignore makes it to the device but none of unignored media files. It seems the `*` in the library is definitive.

**Comment by AudriusButkevicius** [comment]
Well you ignored everything in the library, so the devices can't access any files, as the library is not sharing any.
You want to keep everything unignored on the library, and ignore (or unignore whatever you prefer) things on the devices. The device ignore file can just point to and include file, which then can be managed from the library machine.

**Comment by steelman** [comment]
True. So when I attach a new device, I need to add the following ignore rules not to end up receiving all the library.
```
!*.stignore
*
```
In the new-device.stignore I write
```
!/First Album/Song 1.mp3
!/First Album/Song 2.mp3
!/Second Album
```
to receive two files from the first directory and the whole second one. Fine.

However, removing files from a device does not seem so straightforward . To do it, while syncthing is running, I need to:
1. Edit `.stignore` on the device, to ignore files I am going to remove.
2. Remove the files.
3. Edit `device.stignore` in the library (as soon as possible).
4. Clean up `.stignore` on the device.
Doable, but not first class. Points 1 and 4 may be omitted if syncthing isn't running. What might improve UX, IMHO, is automatic removal of locally ignored files, so only point 3 is required.

If you think this is how it should be done, then I have got no choice but to kindly thank you for your support.

**Comment by AudriusButkevicius** [comment]
Yes, that's how yo do it (it's actually worse than that, as you have to unignore the root directory the files reside in), but the only reason it's ugly is because you use syncthing not in it's standard way. It's meant to sync files, not do media library management.

The next gen ignores would probably have an option to delete ignored files etc, but again, the core problem is that you are using a piece of software what is not a library manager as a library manager.

**Comment by steelman** [comment]
As much as I am not in a position to tell what syncthing is designed for, from reading of some of the issues I can see, that people often use it to download photos from their mobile devices, which also seems a non-standard use case of syncthing. Maybe my use case is another such non-standard case of file distribution.

Anyway, once again thank very much you for your help.

PS. How about "(?D)" prefix to delete ignored files? (just a thought)

**Comment by AudriusButkevicius** [comment]
I agree there are many non-standard usecases that the ignore system struggles to satisfy, but I think we should stop beating a dead horse, as in trying to improve something we know doesn't work, and just wait for some hero who has the time to implement the next gen ignore system.
