### ISSUE TITLE
Keep enough counters and state in the database to avoid initial database traversal

### ISSUE THREAD

**Issue by Nutomic** [syncthing/syncthing#4400]
The initial traversal of the database to build up counters and verify state can take a long time. It would be neat to have all the data available up front and, if necessary, do a consistency scan in the background instead.

// edited by @calmh

---

This is related to #4348. When I created that issue, I was only testing startup times for Syncthing without any folders. Now that I'm using the released version on my phone, I was surprised that startup is still relatively slow. Turns out that this seems to be caused initial folder scan, which is run before the GUI port is opened.

On my LG G4, startup with ~15 GB data (~6500 files) takes around 5 seconds. If I remove all folders, startup only takes around 1 second.

Startup log with folders:
```
09-25 15:14:00.491 INFO: syncthing v0.14.38 "Dysprosium Dragonfly" (go1.8 linux-arm64) vagrant@jessie64 2017-09-07 09:40:46 UTC [noupgrade]
09-25 15:14:00.495 INFO: My ID: 3FNAXCD-EZX3HBW-CPBD3DB-2UFFG5W-KDTG7FE-XK74CYU-JYJHTP3-7UYTNQC
09-25 15:14:00.498 INFO: Disabling weak hash
09-25 15:14:00.919 INFO: Ready to synchronize "Whatsapp Backup" (uzrbq-phjza) (readonly)
09-25 15:14:03.333 INFO: Ready to synchronize felix_sync (readwrite)
09-25 15:14:04.175 INFO: Ready to synchronize g4_music (readwrite)
09-25 15:14:04.324 INFO: Ready to synchronize g4_pictures (readwrite)
09-25 15:14:04.325 INFO: Send rate is unlimited, receive rate is unlimited
09-25 15:14:04.326 INFO: Rate limits do not apply to LAN connections
09-25 15:14:04.327 INFO: Using discovery server https://discovery-v4-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
09-25 15:14:04.328 INFO: Using discovery server https://discovery-v4-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
09-25 15:14:04.331 INFO: TCP listener ([::]:22000) starting
09-25 15:14:04.479 INFO: Completed initial scan of readwrite folder g4_pictures
09-25 15:14:04.897 INFO: Completed initial scan of readonly folder "Whatsapp Backup" (uzrbq-phjza)
09-25 15:14:05.250 INFO: Completed initial scan of readwrite folder g4_music
09-25 15:14:05.365 INFO: Using discovery server https://discovery-v4-4.syncthing.net/v2/?id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
09-25 15:14:05.371 INFO: Using discovery server https://discovery-v6-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
09-25 15:14:05.372 INFO: Using discovery server https://discovery-v6-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
09-25 15:14:05.376 INFO: Using discovery server https://discovery-v6-4.syncthing.net/v2/?id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
09-25 15:14:05.474 INFO: Device xyz is "xyz" at [dynamic]
09-25 15:14:05.480 INFO: Device xyz is "xyz" at [dynamic]
09-25 15:14:05.481 INFO: Device xyz is "xyz" at [dynamic]
09-25 15:14:05.482 INFO: No automatic upgrades; STNOUPGRADE environment variable defined.
09-25 15:14:05.483 INFO: Starting usage reporting
09-25 15:14:05.485 INFO: GUI and API listening on 127.0.0.1:8384
09-25 15:14:05.490 INFO: Access the GUI via the following URL: https://127.0.0.1:8384/
```
Startup log without any folders:
```
09-25 15:36:24.484 INFO: syncthing v0.14.38 "Dysprosium Dragonfly" (go1.8 linux-arm64) vagrant@jessie64 2017-09-07 09:40:46 UTC [noupgrade]
09-25 15:36:24.485 INFO: My ID: 3FNAXCD-EZX3HBW-CPBD3DB-2UFFG5W-KDTG7FE-XK74CYU-JYJHTP3-7UYTNQC
09-25 15:36:24.486 INFO: Disabling weak hash
09-25 15:36:24.505 INFO: Send rate is unlimited, receive rate is unlimited
09-25 15:36:24.506 INFO: Rate limits do not apply to LAN connections
09-25 15:36:24.507 INFO: Using discovery server https://discovery-v4-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
09-25 15:36:24.508 INFO: Using discovery server https://discovery-v4-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
09-25 15:36:24.509 INFO: TCP listener ([::]:22000) starting
09-25 15:36:24.543 Using DNS servers: [168.126.63.1:53 168.126.63.2:53]
09-25 15:36:25.441 INFO: Using discovery server https://discovery-v4-4.syncthing.net/v2/?id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
09-25 15:36:25.442 INFO: Using discovery server https://discovery-v6-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
09-25 15:36:25.446 INFO: Using discovery server https://discovery-v6-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
09-25 15:36:25.453 INFO: Using discovery server https://discovery-v6-4.syncthing.net/v2/?id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
09-25 15:36:25.575 INFO: Device X4NSCQK-47ZCRF4-DKSFSDY-3AALZCG-QNXQQDG-KUBQL7T-V4IPFIU-UGKBAQP is "P50" at [dynamic]
09-25 15:36:25.576 INFO: Device xyz is "xyz" at [dynamic]
09-25 15:36:25.577 INFO: Device xyz is "xyz" at [dynamic]
09-25 15:36:25.578 INFO: No automatic upgrades; STNOUPGRADE environment variable defined.
09-25 15:36:25.579 INFO: Starting usage reporting
09-25 15:36:25.587 INFO: GUI and API listening on 127.0.0.1:8384
09-25 15:36:25.588 INFO: Access the GUI via the following URL: https://127.0.0.1:8384/
```
I don't see why the initial folder scan should prevent the web GUI from starting. Instead, the scan should run in the background while the web GUI is running.

### Version Information

Syncthing Version: v0.14.38
OS Version: Android 7.1

**Comment by calmh** [comment]
It's not actually the initial scan - that does happen in the background.

It is however an initial database traversal to figure out what we have in the folder (supposedly, etc, since it's before the scan) so that we can answer questions about it relevantly in the API. We've discussed it back and forth a couple of times before, but the short of it is that if we don't do this you'll have a bunch of API methods that return 500 or bad data until this is done.

**Comment by Nutomic** [comment]
Right, I wasn't sure what exactly is going on, I was only going by the log messages.

So if I understand you correctly, Syncthing needs to have this information while it's running. So it should be enough to store it in the database when Syncthing is stopped. Then you just need to handle the case where Syncthing crashes (you could probably do that by saving timestamps for last start/stop and comparing them.

It definitely seems worth the effort, considering how much time is spent on this calculation on every start.

**Comment by MasterDimmy** [comment]
this is not a bug. its normal behaviour.

**Comment by calmh** [comment]
I intend to fix this one.

**Comment by AudriusButkevicius** [comment]
Hah...

**Comment by calmh** [comment]
"hah"?

**Comment by AudriusButkevicius** [comment]
Getting rid of initial scan seems like a hard problem, so I just hope this doesn't end up a 'I have a branch (TM)'.

**Comment by calmh** [comment]
Yeah it’s nontrivial but totally doable. Lets try to keep the snark to a minimum in the issue tracker though and I think we’ll all be happier.

**Comment by AudriusButkevicius** [comment]
This doesn't get rid of the scan though, just makes the ui available faster, right?

**Comment by AudriusButkevicius** [comment]
Or perhaps doesn't even do that, just avoids updating the database after the initial scan?

**Comment by calmh** [comment]
It avoids the *database* scan most of the time, so I think it does get rid of it for all practical purposes.

@Nutomic this is for you. test the shit out of it :D

**Comment by Nutomic** [comment]
Okay thanks :D

**Comment by Nutomic** [comment]
Pretty cool, startup takes around 1 second on my tablet now.

However, it seems that sometimes (around every 5 starts), it still performs an initial scan of the folders. Maybe it has something to do with the fact that one of the folders is stuck "syncing" because of ignores, and because a file is too large for FAT32. Nothing unusual in the logs, even with STTRACE=all.
