### ISSUE TITLE
[Feature request] Single run

### ISSUE THREAD

**Issue by rqcy** [syncthing/syncthing#4404]
Hi, I would like to be possible for Syncthing to run once, scan dirextories, sync what's possible, and exit?

**Comment by calmh** [comment]
It's tricky to define what's "once". It takes time to connect to peers, syncing from them may require retries, etc. As it is, you can start it up and take the decision to shut down yourself based on the information available over the API.

**Comment by AudriusButkevicius** [comment]
Once is pretty much what rsync does.
