### ISSUE TITLE
contribute kcp-go changes/features and/or fix tests

### ISSUE THREAD

**Issue by aviau** [syncthing/syncthing#4407]
Hello!

Syncthing is now using a fork of [xtaci/kcp-go](https://github.com/xtaci/kcp-go) at [AudriusButkevicius/kcp-go](https://github.com/AudriusButkevicius/kcp-go).

I would have opened the issue on that repository, but issues are disabled. I am sorry if this is the wrong place to discuss my concerns.

Have you tried contributing your changes/features to upstream? Will Syncthing always use the fork?

If you decide to keep using the fork, would you please consider fixing the tests? They won't build:

```
src/github.com/AudriusButkevicius/kcp-go/sess_test.go:473: cannot use fakeaddr (type *net.UDPAddr) as type string in argument to l.closeSession
```

If the plan is that Syncthing keeps using the AudriusButkevicius/kcp-go fork, I will have to package it for Debian.

Cheers,

**Comment by AudriusButkevicius** [comment]
Sadly we can't, we were told to fork :(

**Comment by AudriusButkevicius** [comment]
If you do have to package it, as a minimum we should move it under syncthing.

**Comment by calmh** [comment]
Might as well make it `lib/kcp` if it's irrevocably different from its upstream. Is it, though?

**Comment by AudriusButkevicius** [comment]
Not that much different, you can see the few commits on my fork.

**Comment by aviau** [comment]
It would be less work for me if you moved it to ``lib/kcp`` but I can live with both solutions.

**Comment by AudriusButkevicius** [comment]
Let me try and run the changes against the original repo once more, and see what the guy says.

**Comment by AudriusButkevicius** [comment]
So this is merged, waiting for a small fix/improvement PR to be merged before swapping.

**Comment by aviau** [comment]
It looks like AudriusButkevicius/kcp-go is still in use.

**Comment by AudriusButkevicius** [comment]
I'll try and raise the PR, but I am 99.99% sure it won't be accepted.

**Comment by calmh** [comment]
Status?

**Comment by AudriusButkevicius** [comment]
Needs me at a computer to wrap up.

**Comment by aviau** [comment]
Thank you!
