### ISSUE TITLE
Can't disable Anonymous Usage Reporting in Syncthing Android v0.9.15

### ISSUE THREAD

**Issue by downloaderfan** [syncthing/syncthing#4409]
I just updated to Syncthing v0.9.15 on my Android Phone & found that Anonymous Usage Reporting has been ticked "On". I had set it to Off before. I tried to uncheck it again, but it doesn't work. Syncthing asks me to restart after I uncheck Anonymous Usage Reporting & after it's done restarting, Anonymous Usage Reporting is checked again.

Steps to reproduce : Go to Syncthing Settings --> Syncthing options --> Anonymous Usage Reporting, uncheck & restart.

Here's a video --> https://streamable.com/5k063 

### Version Information

Syncthing Version: v0.9.15
OS Version: MiUI 8.0.5.0 based on Lollipop 5.1.1

**Comment by AudriusButkevicius** [comment]
This is the wrong repository, please reopen the issue [https://github.com/syncthing/syncthing-android](here)
