### ISSUE TITLE
Kaspersky Total Security Reporting Syncthing as Malicious, but Not A Virus.

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing#4411]
Kaspersky Total Security, version 18.0.0.405(c) running database release "October 10, 2017 4:59AM" is seeing Syncthing v0.14.39-rc.1, Windows (64 bit) as malicious (though not a virus).
[**Kaspersky diagnosis:  not-a-virus:NetTool.Win32.TorJok.gb**](https://threats.kaspersky.com/us/en/threat/not-a-virus:UDS:NetTool.Win32.TorJok)

I am not entirely sure if this is a false-positive or not, maybe Syncthing has malicious code in it previously unknown, which is why I am reporting this via the GitHub.

I've reported the problem to Kaspersky on my end and have requested they double-check the "positive" scan.

[Link to scan performed via Jotti's Malware Scan](https://virusscan.jotti.org/en-US/filescanjob/smo4gghvay,3rz48j7xuu)
![capture](https://user-images.githubusercontent.com/9492083/31399898-c8d5ae9c-adbb-11e7-8540-19c206a68525.PNG)

Two "syncthing.exe" files were scanned, showing the same "positive" results from Kaspersky:
MD5: | cf5a7ca39f76df0ec676c7424cb479ba
SHA1: | 30a8d4c8de5d4e5d89d61504e9dc3e73bb9017a4
+
MD5: | 49070a1d98bcadbfaf22ae1e3da63287
SHA1: | 593448b08a11109f8c8f5bd9bd7445092554cb5c

Syncthing.exe files in question, attached:
[Syncthing-SFX.zip](https://github.com/syncthing/syncthing/files/1372744/Syncthing-SFX.zip)

Note: Issue similar, but not exact, to #3329.

**Comment by calmh** [comment]
Kaspersky does this for every release of Syncthing since a while back, unknown why. Discussion of it on the forum.
