### ISSUE TITLE
No Global Discovery without Sync Protocol Listen Address

### ISSUE THREAD

**Issue by FiloSottile** [syncthing/syncthing#4418]
When setting "Sync Protocol Listen Address" to a blank value, Syncthing starts without listening ports, as intended. This is a laptop always behind NAT anyway, and it feels more secure this way.

However, all Discovery servers fail with `nothing to announce`, which seems unexpected, as it should still be possible to use Global Discovery to connect to reachable servers or via relay.

### Version Information

Syncthing Version: v0.14.38
OS Version: Mac OS X (64 bit)

**Comment by AudriusButkevicius** [comment]
The warning is about the announce part, not lookup, so it might still work.

**Comment by calmh** [comment]
I don’t think this is a config we’ve tested or considered/verified. Clearly it’s valid and should work; potentially the discovery warning is spurious, it should indeed work without listening ports.
