### ISSUE TITLE
Webhook support for Syncthing

### ISSUE THREAD

**Issue by jamsheer-thottathil** [syncthing/syncthing#4419]
Is there any webhook available in Syncthing?
I found there is an event API in Syncthing, but now I need to get same events through the webhook. IS Syncthing support webhook?

**Comment by AudriusButkevicius** [comment]
No, and there is no plan to do that, as events async API is close enough, and serves a simillar purpose.

**Comment by jamsheer-thottathil** [comment]
Thank you @AudriusButkevicius
