### ISSUE TITLE
Local network classification doesn't always work

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#4421]
Firstly, we check these once on startup, which is not ideal.
Secondly, they are only checked if rate limiting is enabled, yet if rate limiting is enabled post startup, lans are never resolved.

**Comment by calmh** [comment]
I'm sure this worked great when changing rate limits required a restart...

**Comment by snugghash** [comment]
If I understand correctly, we'd want to resolve lans when rate limiting is enabled - i.e. do the same thing we do at startup if rate limiting is enabled. 

I'm interested in working on this, but can't find the relevant code (Only found rateLimit related stuff in cmd/session.go, and nothing about resolving lans). Anybody want to give me some pointers?

**Comment by AudriusButkevicius** [comment]
Lans get resolved here: 
https://github.com/syncthing/syncthing/blob/master/cmd/syncthing/main.go#L729

which is once on startup, and get passed to the connection service. The connection service should resolve Lans itself every N minutes or so (or perhaps on every connection, if it's not expensive, yet I don't recall what exactly that does)
