### ISSUE TITLE
Inconsistent tool-tip styling for "Shared With" field

### ISSUE THREAD

**Issue by scienmind** [syncthing/syncthing#4424]
Tool-tips all over the WebUI are styled as follows (white text on black background):

![image](https://user-images.githubusercontent.com/11633330/31588340-1cd791d6-b1f9-11e7-96c4-fed54d95a3eb.png)

 However, tool-tip for "Shared With" field is black text on grey background:

![image](https://user-images.githubusercontent.com/11633330/31588354-3f0c62b8-b1f9-11e7-8764-c7b14db8e5b3.png)

Syncthing v.0.14.39
OS: Win10x64

**Comment by AudriusButkevicius** [comment]
One is bootstrap tooltip, the other one is alt-text and not an actual tooltip.
We only use bootstrap tooltips when there is significant content usually, as alt tooltips are more friendly when it comes to accessibility.

**Comment by calmh** [comment]
I think this is fine as is
