### ISSUE TITLE
fsync on directories fails if directory is located in a samba share

### ISSUE THREAD

**Issue by tehrengruber** [syncthing/syncthing#4432]
Since samba does not support fsync on directories the syncthing daemon gives a lot of "invalid argument" error. It would be great if fsync could be disabled/ignored for directories. 
I think this behaviour is already the default case for windows (5ec1490), but I would like to use it on Linux.

Syncthing Version: v0.14.39
OS Version: Linux / Ubuntu 17.04

**Comment by AudriusButkevicius** [comment]
It will be ignored in the next version.

**Comment by AudriusButkevicius** [comment]
Actually false, it will only be ignored on Windows.

**Comment by tehrengruber** [comment]
Jap. My request is to make this configurable, such that I can use it on linux for samba shares.

**Comment by calmh** [comment]
How about we just never complain about this

**Comment by tehrengruber** [comment]
I agree. However we should only ignore `EINVAL` errors.
