### ISSUE TITLE
"Out of Sync" folder status can be misleading

### ISSUE THREAD

**Issue by nekr0z** [syncthing/syncthing#4434]
Here comes the case, aka "steps to reproduce":

1. Have a folder in sync on at least 2 machines, where machine A has filename lenght limit significantly higher than that of machine B (one common example might be machine B using ecryptfs).
2. Create a file X on machine A with filename long enough to hit the limit on machine B.
3. Observe folder status in Web GUI of machine B.
RESULT: Folder status will be "Out of Sync", since there are errors in this forder, particularly file X can't be synced due to filename being too long.
4. Add some more files with short filenames to the said folder or otherwise change the folder contents from either machine.
RESULT: All changes, new files, deleted files, etc. will be propagated. In fact, folder gets synced just fine except for that one file X.

While this behaviour is nice and desired, folder status "Out of Sync" is a bit misleading, especially in translations where it usually is close to "No Synchronization" (Russian and German are the ones I've shecked) and implies no further synchronization is done on the folder in question.

SyncthingGTK shows "Synchronized" status with an error in such cases, which seems to be more appropriate.

Syncthing Version: v0.14.39
OS Version: any
Browser Version: any

**Comment by AudriusButkevicius** [comment]
Do you have steps to repro/screenshot? Stopped only happens if fatal error occours, in this case it should be out of sync and not stopped.

**Comment by nekr0z** [comment]
That's true, my bad. It is "Out of Sync" indeed. The problem was, I don't usually use WebGUI in English, and I looked for possible status translation in official documentation where "Out of Sync" is not listed so only "Stopped" looked like an option.

**Comment by nekr0z** [comment]
Here's how WebGUI treats this. Notice that "Out of Syncs" in other languages is "No synchronization" (Russian) "Not synchronizing" (German, Dutch)
![screenshot_20171019_121053](https://user-images.githubusercontent.com/1515080/31763348-ae915b3c-b4c6-11e7-8cc6-318d98d8005e.png)

And here's SyncthingGTK's take on this:
![screenshot_20171019_121121](https://user-images.githubusercontent.com/1515080/31763349-aebd366c-b4c6-11e7-964c-d9c71de49912.png)

**Comment by AudriusButkevicius** [comment]
So whats the actual issue here?

**Comment by nekr0z** [comment]
I think the actual issue would be translation. What is "Out of Sync" in English becomes "Not synchronized" in Russian, Polish and Swedish, "Not synchronizing" in German and Dutch, maybe close to that in other languages that I'm not that good in.

The secondary obvious issue is discrepancy between how WebGUI and SyncthingGTK present this. These cases are shown as "Synchronized" in SyncthingGTK and "Out of Sync" in WebGUI.

**Comment by AudriusButkevicius** [comment]
Well GTK issues belong on the GTK repo, translations are managed via transifex, but the translations look fine to me?

**Comment by nekr0z** [comment]
I agree that GTK issues don't belong here. My point is GTK is doing a better job of presenting these cases than WebGUI.

**Comment by AudriusButkevicius** [comment]
Its arguable. The status bar is green, in our case it's red, yet it has X icon which we don't, but I wouldn't say it's immediately better. It depends on the taste I guess.
