### ISSUE TITLE
Private relay - unexpected certificate count

### ISSUE THREAD

**Issue by nmaggioni** [syncthing/syncthing#4437]
### Version Information

Syncthing Version: v0.14.38 (Linux x64)
OS Version: Ubuntu 16.04

---

When I try to use a private relay server I get an `unexpected certificate count: 2` error in the web UI, in to the "Listeners" row.

![error](https://user-images.githubusercontent.com/3594528/31790653-75318740-b516-11e7-86a5-63a733dbc419.png)

I am deploying a [Relay + Discovery](https://github.com/t4skforce/syncthing-relay-discovery) combo on Docker. A valid certificate issued by LetsEncrypt is used for both - the same certificate is in place for other uses on the same domain and is correctly being renewed.

No reverse proxy or load balancer is in place, ports are exposed directly on the host.

Logs (with debug enabled) report repeated instances of this pattern (restarting a Syncthing client produces three of them) - `10.0.1.1` is the upstream router and _{SYNCTHING_CLIENT_ID_HERE}_ is a placeholder for the client's ID:

```
19/10/2017 21:30:442017/10/19 19:30:44 listener.go:48: Listener accepted connection from 10.0.1.1:49458 tls true
19/10/2017 21:30:442017/10/19 19:30:44 listener.go:215: Closing connection {SYNCTHING_CLIENT_ID_HERE}: EOF
```

Running `openssl s_client --connect MY_DOMAIN:22027` returns:

```
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = MY_DOMAIN
verify return:1
CONNECTED(00000003)
---
Certificate chain
 0 s:/CN=MY_DOMAIN
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
... (certificate contents) ...
-----END CERTIFICATE-----
subject=/CN=MY_DOMAIN
issuer=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
---
No client certificate CA names sent
Client Certificate Types: RSA sign, ECDSA sign
Requested Signature Algorithms: RSA+SHA256:ECDSA+SHA256:RSA+SHA384:ECDSA+SHA384:RSA+SHA1:ECDSA+SHA1
Shared Requested Signature Algorithms: RSA+SHA256:ECDSA+SHA256:RSA+SHA384:ECDSA+SHA384:RSA+SHA1:ECDSA+SHA1
Peer signing digest: SHA384
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 2920 bytes and written 281 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: ... (master key here) ...
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1508442013
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
closed
```

**Comment by AudriusButkevicius** [comment]
We use certificate pinning anyway, so having a valid CA chain is a bit pointless.
The same code that we use for syncthing (for IDs) is used for relays, which expects exactly 1 certificate in the chain.

Easy option would be for you to swap relay certificate for a self signed one, and update the ID it's pinned to in the relay URL.

Technically, there isn't a reason why we couldn't support certificate chains, and just pick the first certificate in the chain, yet practically nobody does that, and it provides no extra guarantees.

If that answers your question, and you are fine to close it, please do.
Otherwise, this can go into the "nobody ever cared to implement enhancement" pile.

**Comment by nmaggioni** [comment]
Thanks for the explanation! I let them generate their own certificates, updated the URLs in the clients and everything went fine.

I instinctively went with signed certificates for no specific reason - most applications just usually don't like self-signed ones, so I thought that I was preventing a problem to come up in the future.

I'll see if I can brush up my Go enough to help with a PR for supporting certificate chains - I suppose that there may be some modifications to do [here](https://github.com/syncthing/syncthing/blob/38d28c3f4ab47ddcb8a1c0069964b723c86abc8f/lib/relay/client/static.go#L316).

**Comment by calmh** [comment]
For relays we always go by the device ID afaik, meaning we could very well accept certificate chains and just check the leaf certificate, for the same effect as there just being one certificate to begin with.
