### ISSUE TITLE
Folder puller ignores rescan interval when not making progress

### ISSUE THREAD

**Issue by Phoenix616** [syncthing/syncthing#4442]
When the puller is failing for some reason it will rescan every minute (`Folder "asdf" (abcde-fghij) isn't making progress. Pausing puller for 1m0s`) even though the rescan interval was set to a different value. (600s in my case)

This is especially annoying when having items in the folder that will always fail (like symlinks) as that will resultin a CPU spike every minute even though syncthing isn't doing anything at all.

### Version Information

Syncthing Version: v0.14.39
OS Version: Windows 7 (64 bit)
Browser Version: SyncTrayzor 1.1.18

**Comment by imsodin** [comment]
The puller does not scan and is thus not related to the rescan interval. If there was no error, it would run every 10s, that's why it says "Pausing puller".
