### ISSUE TITLE
"Smallest first" order doesn't work

### ISSUE THREAD

**Issue by Vinz87** [syncthing/syncthing#4457]
Setting "smallest files first" as pull order doesn't work for me, I have on top of the stack a file of ~2 GB and after that several files of tens of kB.

### Version Information

Syncthing Version: v0.14.39 - v0.14.38
OS Version: OS X El Capitan 10.11.6

**Comment by AudriusButkevicius** [comment]
It's relative to the order the changes are discovered as they are scanned, as changes are split into size limited messages, so we might get notified about smaller files after we started downloading the bigger ones. This is a known issue and I think we already have am issue for this.

**Comment by uok** [comment]
looks like https://github.com/syncthing/syncthing/issues/3019

**Comment by AudriusButkevicius** [comment]
Yeah it's supposed to be rewritten(TM) by @calmh sometime before he dies. This also relates to renames being missed and stuff like that (which I think still has an open ticket hence this one closed), so I guess we just have to wait. 💀

**Comment by Vinz87** [comment]
ok thank you
