### ISSUE TITLE
Syncthing fails to sync files with different filename case in Windows.

### ISSUE THREAD

**Issue by Lywx** [syncthing/syncthing#4462]
Hi.

When I modified existing file names' case, syncthing would fails to download related changes, say I have a file named A.url. A.url is synced between two clients, folder synchronization mode are both send / receive. Two clients both run on Windows 10.

The setup of this issue is, I had previously fine synchronization between these clients. I reinstalled OS in PC 1 so all syncthing configuration is reestablished after OS reinstallation. Then I changed filename A.url in PC 1, to a.url. Then I reestablish sync folder option.

PC 2 would display Out of Sync all the time. syncthing would detect the file a.url is Out of Sync, but failed to download it. 

Normally, in Windows, you would expect to treat those files with different cases as same file. But obviously, syncthing could not work in Windows in this case.

Syncthing Version v0.14.39, Windows (64 bit).

**Comment by Lywx** [comment]
In fact, syncthing even has problem dealing with renamed filename case in two established synchronization. If I renamed A.url in PC 1 to a.url, the PC 2 would fail to download the update unless I manually delete previous A.url in PC 2.

**Comment by AudriusButkevicius** [comment]
Check existing issues (I suspect on the last issue page).
