### ISSUE TITLE
blank settings

### ISSUE THREAD

**Issue by edcerwin** [syncthing/syncthing#4467]
This is the first bug report ive done so bear with me...Ive been having a problem trying to limit the upload bandwidth to my sisters pc in another town.  In doing so ive been concerned that these settings that are dissapearing after i set and save are the cause of my issue.  My internet upload speed is 1 megabit/s and i have been trying to set it down to 500kbit/s.  Whatever i do in the settings it Always uploads at full speed.

Another thing to mention is when i do save these settings the gui does not show dialog to "restart server to take effect"  like my sisters same version.  although i have ubuntu proper 1604 she has mint.  

im using ubutnu mate 1604
synthing 1439 64bit

not too sure where and how to get log files???  Im not an expert with linux but i am dangerous! :)

![screenshot_20171026_082608](https://user-images.githubusercontent.com/33125296/32055432-698af5e6-ba27-11e7-9ce7-b6fa314b0463.png)

**Comment by Nutomic** [comment]
Have you tried if using a different browser fixes the problem? For the logs, it depends how you installed Syncthing.

**Comment by imsodin** [comment]
As you use Ubuntu, I assume you use syncthing either from our or the official repo and you use systemd to start it. In this case you can access logs via `journalctl -u syncthing@whateverUsernameYouUse`.

Also you can check the actual config file at `~/.config/syncthing/config.xml` whether the rate is present there.

**Comment by edcerwin** [comment]
It does in fact show the correct settings in the config.xml.  Switched to firefox and all the correct parameters were shown as they should.  Chrome must be the issue.  I did notice that the settings stay until the tab closes, but then when the syncthing site is reopened, the settings are blank again.

**Comment by AudriusButkevicius** [comment]
Check for errors in the js console.

**Comment by edcerwin** [comment]
js console just has one error.....VM72:1 GET http://192.168.1.100:8384/rest/system/upgrade 500 (Internal Server Error)


and journalctl returns  --no entries--

**Comment by AudriusButkevicius** [comment]
Try ctrl+f5 to force clearing caches.

**Comment by edcerwin** [comment]
ctrl+f5 did not work...still blank in chrome

chrome 62.0.3202.75 (Official Build) (64-bit) manjaro kde
          firefox  56.0.1 64 bit    (works perfect)

**Comment by AudriusButkevicius** [comment]
Did you try clearing browser cache etc?

**Comment by edcerwin** [comment]
same blank output windows 7(64) chrome 62.0.3202.75 (Official Build) (64-bit)

clearing browser cache did not work

**Comment by calmh** [comment]
Odd unexplained browser issue, not sure what to do here other than close, sorry
