### ISSUE TITLE
Deleted empty folders aren't moved to staggered .stversions

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#4468]
v0.14.39 Ubuntu 14.04.5
Just as titled.

**Comment by AudriusButkevicius** [comment]
Why would you ever want that. Directories hold no content.

**Comment by Ferroin** [comment]
An empty directory still has metadata, which may be relevant (although software that considers the metadata of empty directories relevant for anything other than backups is arguably poorly designed).

**Comment by AudriusButkevicius** [comment]
I don't buy that. We don't sync mtimes of directories so there is nothing that is lost.

**Comment by Ferroin** [comment]
The very presence of a file or directory is metadata in and of itself, and even if Syncthing doesn't sync mtimes, it still updates them (so you can still tell from looking at an empty directory when it was last changed by Syncthing).

As I mentioned in my first reply though, I would say that any software which depends on this is arguably broken to some degree (I also feel this way about the new directory style folder markers, but debating that is off-topic here), so the only practical value is to a person seeing if it's there or not (and _possibly_ knowing when it was last changed), but if presence is all that's needed, an empty file is a better option, and if it has to be a directory, an empty hidden file in that directory to cause it to be tracked properly by sane software is a better option.

I'm not  trying to argue for supporting this, just point out why some people may want it.

**Comment by calmh** [comment]
Understood. However, contrary to the OP it is by design that we do not version directories by themselves. We even make sure to remove empty directories from the versioning archive when we clean out versioned files.

**Comment by bugith** [comment]
This was not an issue for me. I only wanted to make you aware in the case you were not. I just noticed this behaviour.

Great job that Syncthing guys, really great job !!!!
