### ISSUE TITLE
strange weak hash benchmark results

### ISSUE THREAD

**Issue by DrSchnagels** [syncthing/syncthing#4470]
v0.14.40-rc.3, Windows 10 Fall Creators Update (64 bit), Dell XPS 9360 with 2/4 Intel 7th gen CPU (7500U 2.7 GHz) gives me this result in the console:

```
[OGKQU] 23:08:20 INFO: Single thread SHA256 performance is 431 MB/s using minio/sha256-simd (363 MB/s using crypto/sha256).
[OGKQU] 23:08:20 INFO: Hashing performance with weak hash is 354.24 MB/s
[OGKQU] 23:08:21 INFO: Hashing performance without weak hash is 417.51 MB/s
[OGKQU] 23:08:21 INFO: Weak hash enabled, as it has an acceptable performance impact.
```

Shouldn't weak hash be disabled since it gives a worse performance?

Furthermore (sorry): What does weak hash do anyway?
It makes me silly-like think that my files might get weakly hashed. I would prefer to have them perfectly super good hashed and super secured ;). I'm a civil engineer and I just did calculations with 90 tons of force.
Weak is a mean word for me ;). Why not rename it to quick hash?

I used to set Weak Hash Selection Method to never but I really don't understand what it does.
And why is it always disabled on Android (forced?) ?

Thanks a lot for your help!

**Comment by imsodin** [comment]
Please search existing issues and forum - there were already several inquiries about this. And in general, please use the forum for support.
https://forum.syncthing.net/t/incorrect-info-message-about-weak-hash-in-v0-12-25/9462
https://forum.syncthing.net/t/hashing-performance-for-bears/10013
