### ISSUE TITLE
Invalid filepath detection on windows uses incorrect path separator

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#4484]
This came up in the following report about a puller error:
https://forum.syncthing.net/t/folder-isnt-making-progress-2017/10915/5

The relevant log lines are:

```
[KFH2Y] 2017/11/04 15:35:56.235376 progressemitter.go:225: DEBUG: progress emitter: deregistering qjznm-pqohs Giornale di Diritto Amministrativo\2007_7.pdf
[KFH2Y] 2017/11/04 15:35:56.247387 rwfolder.go:1435: DEBUG: sendReceiveFolder/qjznm-pqohs@0xc0421a2b40 closing Giornale di Diritto Amministrativo\2000_2.pdf
[KFH2Y] 2017/11/04 15:35:56.247888 rwfolder.go:1367: DEBUG: file modified but not rescanned; not finishing: 
```

The file with "\" in its name made it past the `fileValid`/`windowsInvalidFilename` test. This test is partly broken, as it splits the path by "\", while db/protocol uses "/" as path separator regardless of os. The following test shows the problem:

```go
func TestWindowsInvalidFilenames(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("only relevant on windows")
	}

	type testcase struct {
		path   string
		result bool
	}
	testcases := []testcase{
		{"test//this", false},
		{"test /this", true},
		{"test/foo\bar", true},
		{"test\foo\bar\baz", true},
	}

	for _, test := range testcases {
		if invalid := windowsInvalidFilename(test.path); invalid != test.result {
			t.Errorf("windowsInvalidFilename(\"%v\") == %v, expected %v", test.path, invalid, test.result)
		}
	}
}
```

As a (relevant) side-effect, the test currently doesn't fail when encountering backslashes in filenames.

I will post a PR shortly.

**Comment by AudriusButkevicius** [comment]
Backslashes are just escape characters

**Comment by AudriusButkevicius** [comment]
Also, the test passes as you skip it on windows, not the other way around.

**Comment by imsodin** [comment]
Yeah, I shouldn't copy paste the stuff before testing, will work in the PR :)

**Comment by imsodin** [comment]
I will open a new issue about the backslash issue, it would be confusing if I completely edited this issue to get rid of all the incorrect stuff.
