### ISSUE TITLE
Different sha512sums value in version 0.13.10

### ISSUE THREAD

**Issue by rgdoliveira** [syncthing/syncthing#4492]
Alpine Linux builds syncthing and it downloads the 0.13.10 source from github

We are rebuilding all the Alpine packages for 3.7 release but syncthing failed to build when comparing the sha512sums. It was before:
sha512sums="199c38644a7e5d43777ca2e497d5304d8e77485d21aeed9a00efc74dd98bfb0c473dd0bf3230b8e1e9742315915419f198bb8d0a9b294d2f6fe918b6e0175812  syncthing-0.13.10.tar.gz

And now:
sha512sums="1bb433624d9875076cad1cab371fe6ba1b07e1fdfa7b91c178fde5476d6162653d66c8744cbda2bb9430bd5bfebb61baa0e46366db7c9296ee8c9fb90d9c4419  syncthing-0.13.10.tar.gz

Does this tar.gz got any changes or it was uploaded again (or something like that)?

**Comment by AudriusButkevicius** [comment]
Do you have the old and new binary?

**Comment by rgdoliveira** [comment]
I don't have the old archive, just the new one. 
I just want to know if the tarball was generated again to make any change on it or maybe some issue in github that recreated it?

**Comment by AudriusButkevicius** [comment]
I know there was some form of change log rewriting which happened to nuke all releases, so it could be related to that. Does the archive hash match with the one specified in the sum file that is part of the release?

**Comment by calmh** [comment]
What file are you actually talking about? Our `syncthing-source-v0.13.10.tar.gz` (which is a *really* old version) available here on github has the sha256 sum cb37abf303876e17f1ef068052edc0fc3a5158f41cd59d9221d0cea8176867c9ffd1f446638a9eb0346e06d8980422acc9e5ce15afbb3cab82327a156a5dc132 and matches the GPG signature from July 2016:

```
jb@unu:~/Downloads $ gpg syncthing-source-v0.13.10.tar.gz.asc 
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
gpg: assuming signed data in 'syncthing-source-v0.13.10.tar.gz'
gpg: Signature made Sun Jul  3 14:20:38 2016 CEST
gpg:                using RSA key D26E6ED000654A3E
gpg: Good signature from "Syncthing Release Management <release@syncthing.net>" [ultimate]
```

**Comment by calmh** [comment]
Ah. Going by the file name you mentioned you are using the github auto generated tarball. I don't know how that is generated and we can't affect how it looks or make any guarantees about the contents. Use our own tarballs and you'll be good.
