### ISSUE TITLE
Random files not synced

### ISSUE THREAD

**Issue by ttr** [syncthing/syncthing#4494]
Hi,

I've got random files that are not being synced from send only directory (not sure if matters)
![image](https://user-images.githubusercontent.com/1327295/32516192-6e71718e-c3fa-11e7-8580-c345672ff03e.png)

![image](https://user-images.githubusercontent.com/1327295/32516175-5bc169d6-c3fa-11e7-9764-da546b19021b.png)

There is no stignore files. Permission on source are fine, disk space (also inode wise) are also fine.
Did diff on file list form both directories and I can confirm that target system is missing almost 100 files.
New files are being synced, but those ones are not.
On source host, status of remote device shows 99% synced (missing 862Mb, which is correct) while remote one thinks it's in sync with source.

Relevant lines from audit log
Source:
`{"id":111,"globalID":111,"time":"2017-11-07T20:36:24.655727856Z","type":"FolderSummary","data":{"folder":"rxz5c-....","summary":{"globalBytes":331790784102,"globalDeleted":0,"globalDirectories":326,"globalFiles":44233,"globalSymlinks":0,"ignorePatterns":false,"inSyncBytes":331790784102,"inSyncFiles":44233,"invalid":"","localBytes":331790784102,"localDeleted":0,"localDirectories":326,"localFiles":44233,"localSymlinks":0,"needBytes":0,"needDeletes":0,"needDirectories":0,"needFiles":0,"needSymlinks":0,"sequence":88936,"state":"idle","stateChanged":"2017-11-07T20:35:03.711052711Z","version":88936}}}
{"id":112,"globalID":112,"time":"2017-11-07T20:36:24.716666241Z","type":"FolderCompletion","data":{"completion":99.72748656342364,"device":".....","folder":"rxz5c-....","globalBytes":331790784102,"needBytes":904174468}}`
Target:
`{"id":44,"globalID":44,"time":"2017-11-07T20:36:29.957628938Z","type":"FolderSummary","data":{"folder":"rxz5c-...","summary":{"globalBytes":330886609634,"globalDeleted":0,"globalDirectories":326,"globalFiles":44135,"globalSymlinks":0,"ignorePatterns":false,"inSyncBytes":330886609634,"inSyncFiles":44135,"invalid":"","localBytes":330886609634,"localDeleted":0,"localDirectories":326,"localFiles":44135,"localSymlinks":0,"needBytes":0,"needDeletes":0,"needDirectories":0,"needFiles":0,"needSymlinks":0,"sequence":88936,"state":"syncing","stateChanged":"2017-11-07T20:36:29.909707392Z","version":88936}}}
{"id":45,"globalID":45,"time":"2017-11-07T20:36:30.000131523Z","type":"FolderCompletion","data":{"completion":100,"device":".....","folder":"rxz5c-....","globalBytes":330886609634,"needBytes":0}}
`

### Version Information

Syncthing Version: v0.14.39
OS Version: Devuan 2.0 Ascii (Debian fork)
Browser Version: (if applicable, for GUI issues)

**Comment by ttr** [comment]
did reset database on remote and full re-scan - did not helped, however did reset deltas on source and after short while, all remaining files where synced.

**Comment by calmh** [comment]
Odd. It would have been nice to figure out what the destination thought about the missing files, if anything. As it is I'm not sure how to debug unless it's reproducible.

**Comment by ttr** [comment]
Yup.

This is why I've did enable audit but it did not point to anything (and with 44k files, was even harder to see anything out of ordinary)
It was weird, because remote server saw it's in sync and global bytes to its local bytes value is same, but comparing to local (source) host, it was off.
Few things but they might not be related but will point them out just as it might sparkle some thoughts:
- local is on ext4, remote on zfs file system
- sync was terminated half way (reboot of local node)
- in background I've had some app (other sync tool) that was reading files, it was running during initial scan of directory

I do not think there is any debugging possible now. I cannot reproduce this (I've spend few hours to copy this data and set up new pair of folders and it synced OK (including having other apps reading those files, killing sync thing process, etc).

One possible enhancement would be to create some sort of self heal. Since one of nodes (local) was seeing that remote is out of sync (missing data) but remote was thinking it's OK, those nodes could compare their global sizes values on each shared folder (so they will know which ones are out of sync) and give option for user to reset deltas on those folder (via UI). In this situation information about out of sync would show op on both sides, so regardless where human is looking she/he can make action to fix it.
(LMK if above does not make sense)

**Comment by AudriusButkevicius** [comment]
I am closing this as we need a repro, next time this happens we can explain what we need on order to debug. Audit logs is not enough, there are a few API calls you'd have to make.
