### ISSUE TITLE
Android Syncthing App only using Google's 8.8.8.8 DNS server.  Cannot resolve names on local LAN.

### ISSUE THREAD

**Issue by Joeviocoe** [syncthing/syncthing#4496]
There must be something hardcoded in the Android app 0.9.17 (I am running Android 8.0.0).
When any peer is configured with a host name instead of an IP, the DNS Lookup goes to 8.8.8.8 udp/53 (checked with tcpdump on my router).
My Router hands out the OpenDNS servers via DHCP, and even when my Android is not on my local wifi, and on LTE, it gets my Carrier's DNS.  There should not be anything in my phone telling apps to resolve using 8.8.8.8

**Comment by AudriusButkevicius** [comment]
This is the wrong repository, please reopen the issue [https://github.com/syncthing/syncthing-android](here)
