### ISSUE TITLE
Syncthing has stopped with an panic error.

### ISSUE THREAD

**Issue by andriishyba** [syncthing/syncthing#4501]
Syncthing has stopped with an panic error.

Log is included.
[log.txt](https://github.com/syncthing/syncthing/files/1459359/log.txt)

### Version Information

Syncthing Version: v0.14.40, Windows (64 bit)
OS Version: Windows 7

**Comment by AudriusButkevicius** [comment]
Dup #4170

**Comment by calmh** [comment]
That old one... Long time no see

**Comment by andriishyba** [comment]
It will be great if SyncTraysor has an option to force restart Syncthing after crash. The software works on server and there is no opportunity to always monitoring it.

**Comment by AudriusButkevicius** [comment]
That should be raised in the synctrayzors issue repo.

**Comment by canton7** [comment]
SyncTrayzor isn't really suited to running on a server, since it will only ever start on login. You can raise an issue for trying to start a few times though.
