### ISSUE TITLE
Logging at info level and above should always include context

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#4510]
This is very low importance, it just came up with a recent report of connection issues:

Logging like `l.Infoln(err)` leads to errors like 

```
[NPNSQ] 22:22:01 INFO: set tcp 192.168.178.24:6736->192.168.178.20:22000: protocol not available
```

whose origin and context are not immediately clear. As this is user facing information, it should contain a minimum of information. In the example of the tcp listener this could be in line with existing logging:

```
			l.Infoln("Listen (BEP/tcp): failed to set options:", err)
```

The alternative is to downgrade it to debug logging level, where the context is evident from file names and line numbers. In the case of the tcp listener, [similar failures are on different levels](https://github.com/syncthing/syncthing/blob/master/lib/connections/tcp_listen.go#L105). Is this on purpose or should all of them be either debug or info level?

**Comment by AudriusButkevicius** [comment]
That function should be improved in general, to try setting all options before returning errors.

**Comment by calmh** [comment]
Yeah, no, we should pretty much never just Infoln(err). Either a sane, descriptive message if it’s something we think the user should know and act on, or just debug level if it’s not actionable.
