### ISSUE TITLE
-home command line param does not accept trailing slash

### ISSUE THREAD

**Issue by kirillkovalenko** [syncthing/syncthing#4512]
### Version Information

Syncthing Version:  v0.14.40 x86
OS Version: Windows 10 x64

### Problem

If I try running syncthing using home parameter with a trailing slash like this
```
 .\SyncThing\syncthing.exe -home="C:\Program Files (x86)\SyncThing\Config\"
```
I get the following error:
```
FATAL: mkdir \\?\C:\Program Files (x86)\SyncThing\Config"\: The filename, directory name, or volume label syntax is incorrect.
```

### Expected Behavior

The program understands trailing slashes and does not fail.

### P.S.

You may argue that I should just pass this parameter without slash, but the problem is that we install syncthing with an MSI installer and use MSI properties (such as [INSTALLPATH]) to provide this parameter, which leads to always having a trailing slash, and this situation is non trivial to fix on the MSI side.

The current workaround that we have is to supply the path with the dot at the end, e.g. `-home="C:\Program Files (x86)\SyncThing\Config\."`. It allows program to start, but this leads to https-cert.pem file loading error (which is non-critical for us).

**Comment by calmh** [comment]
I don't think this is a slash issue, it's quoting issue. Command lines in Windows don't work like command lines in Unix - there is no common handling of quoting or word splitting, and the program gets all arguments a single string and applies it's own processing. In this case it looks like the Go flags package interprets the `\"` at the end like an escaped quote and keeps it at the end of "Config":

`\\?\C:\Program Files (x86)\SyncThing\Config"\`

I'm not sure what the proper solution is. Experiment with quoting, like Audrius suggests.

**Comment by kirillkovalenko** [comment]
I've just tried single quotes and it makes no difference
```
[8:16:27 AM] C:/Program Files (x86)/SyncThing> .\syncthing.exe -home 'C:\Program Files (x86)\SyncThing\Config\'
08:16:47 FATAL: mkdir \\?\C:\Program Files (x86)\SyncThing\Config"\: The filename, directory name, or volume label syntax is incorrect.
```

**Comment by calmh** [comment]
The following works for me, in Windows 10:

```
> syncthing -home "foo\bar\\"
```

The extra trailing backslash makes that the escaped character instead of the quote. Single quotes are no good, using `'foo\bar\'` actually gives me a directory called `bar'` inside a directory called `'foo`. (As opposed to what happens to you, so YMMV I guess.)
