### ISSUE TITLE
Make countRestarts and loopThreshold configurable

### ISSUE THREAD

**Issue by pzduniak** [syncthing/syncthing#4513]
https://github.com/syncthing/syncthing/blob/161326c5489d000972a6846564f0ce12779bd8f2/cmd/syncthing/monitor.go#L31-L32

When there are too many config updates in my software, Syncthing just stops. These constants should be somehow configurable (I don't want to anyhow fork syncthing in my deployments).

**Comment by AudriusButkevicius** [comment]
Most config updates these days do not require restarts, what exactly are you doing?

**Comment by calmh** [comment]
If you have some system that requests restarts more than four times a minute, I suggest fixing that system. I doubt it's something you're doing manually. You can also simply run without the monitor process and take charge of this yourself.

**Comment by pzduniak** [comment]
Does adding / removing folders require restarting or is that something that
has changed since 0.12?

**Comment by AudriusButkevicius** [comment]
Adding removing folders now does not require restarts.

A lot of stuff has changed since 0.12.
The changelogs are in the release page.

**Comment by pzduniak** [comment]
I made a stupid typo in my code, it was restarting Syncthing every time ConfigSaved was triggered and `configInSync` was `true`... Oops!

Thanks for the info, it indeed seems reasonable to keep the functionality as it is.
