### ISSUE TITLE
Should understand “socks” in addition to “socks5” in proxy URLs

### ISSUE THREAD

**Issue by grdshch** [syncthing/syncthing#4515]
It works fine if I set `all_proxy=socks5://server:port` environment variable and doesn't work if `all_proxy=socks://server:port`.

When I set global proxies in Ubuntu I can't set its protocol as `socks5` because the protocol is added by Ubuntu. So, if I set proxy as `socks5://server:port` then Ubuntu creates `all_proxy=socks://socks5://server:port` variable.

So, I have to set syncthing-specific all_proxy variable manually.

Syncthing Version: v0.14.40 "Dysprosium Dragonfly" (go1.9.2 linux-amd64)
OS Version: Ubuntu 17.10 64-bit

**Comment by calmh** [comment]
Looks like the Go std library only understands socks5, but we could register socks as a synonym before calling FromEnvironment. I doubt there is anyone using a socks proxy of a lower version, and if they are it already didn’t work anyway.

**Comment by AudriusButkevicius** [comment]
Sorry, but I think we should close this. We only support socks5, the fact that ubuntu does something else with the variable values is their issue not ours.

**Comment by calmh** [comment]
Okay so I'm unable to find an official list of URL schemes that should be supported here. Curl however does not seem to like `socks` either, which is a point in that direction:

https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html

**Comment by AudriusButkevicius** [comment]
Case closed.

**Comment by calmh** [comment]
If it's an easy fix and it makes things easier for some subset of users I don't see that it hurts, though. Given that there isn't an obvious standard to follow we wouldn't be in the wrong there either.

**Comment by qepasa** [comment]
I'd like to give this one a shot
