### ISSUE TITLE
Bandwidth throttling per remote device

### ISSUE THREAD

**Issue by priyadarshan** [syncthing/syncthing#4516]
We use syncthing in many controlled situations, where we could use bandwidth throttling per remote device, beside the already available global throttle setting.

It would be quite useful to have something like "maxRecvKbps" and "maxSendKbps" _per remote device_ in the advanced configuration, beside as a global option for the local device.

Thank you for giving us syncthing, it is a wonderful tool.

**Comment by calmh** [comment]
This could probably be done.

**Comment by priyadarshan** [comment]
Thank you for considering this. Let me know if there is anything I can do to help (mainly testing).

**Comment by Ferroin** [comment]
Just my 2 cents, but it would be nice if this gets implemented to have a way to set a default value in the global configuration that would be applied to devices with nothing set for this.

Also, I'd be more than happy to help with testing this too.

**Comment by qepasa** [comment]
I'd like to work on this.

**Comment by priyadarshan** [comment]
Thank you!
