### ISSUE TITLE
KCP gets confused which side it's on

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#4528]
From  https://forum.syncthing.net/t/stun-nig-party-with-paused-devices/10942/6 (https://gist.github.com/anonymous/e3ed65b57bd91fb9e4623ffc0a53127f)

```
[IDID_0] 2017/11/18 15:03:45.861803 service.go:400: DEBUG: dial IDIDID_9 kcp://IPv4_16:PORT_8
[IDID_0] 2017/11/18 15:03:45.861803 kcp_dial.go:42: DEBUG: dial kcp://IPv4_16:PORT_8 using existing conn on [::]:PORT_8
[IDID_0] 2017/11/18 15:03:45.863808 service.go:405: DEBUG: dial failed IDIDID_9 kcp://IPv4_16:PORT_8 tls: received unexpected handshake message of type *tls.clientHelloMsg when waiting for *tls.serverHelloMsg
```

Yet not sure how it happens.

**Comment by calmh** [comment]
Huh. Isn't one of the thing with KCP that it handles the mutual dial, by necessity, and then we don't really know who ends up being the "server" and "client"?

**Comment by AudriusButkevicius** [comment]
Mutual dial doesn't have much todo with this. When you dial somewhere, you pick a random number for your conversation ID, so you know you are dialing.

When you accept you don't pick anything, you just accept what is being sent to you, so you know you are accepting. 

This whole thread there is something suspicious, yet we don't log accepts so I have no idea where it's coming from.

**Comment by calmh** [comment]
#4737
