### ISSUE TITLE
GUI folder/device status rows should handle longer values nicer

### ISSUE THREAD

**Issue by sisu4syncthing** [syncthing/syncthing#4531]
Hi,
in the WebGui, can we have the full view on IPV6 adresses?

They are unreadable because of the "..." at the end of each adress.

Steps to reproduce:

Open the WebGUI and open Remote Devices to see some IPs

 - what you expected to happen instead

The whole IP Adress, so I can compare or textcopy them.

Versions:
Syncthing Version: v0.14.40, 64Bit on Mac/Linux/Windows
OS Version: Windows 7 / Mac OSX Sierra
Browser Version: FireFox / Safari 

Screenshots:
<img width="511" alt="bildschirmfoto 2017-11-19 um 21 19 43" src="https://user-images.githubusercontent.com/12977080/33028735-f684abf6-ce16-11e7-88f7-1445b38c2f48.png">

<img width="583" alt="bildschirmfoto 2017-11-19 um 21 30 30" src="https://user-images.githubusercontent.com/12977080/33028725-edc8ccea-ce16-11e7-86c7-0f255fcc609b.png">

**Comment by calmh** [comment]
The more general problem is that the table layout requires giving the columns fixed space, which is currently 50/50.

**Comment by alyandon** [comment]
I have on occasion needed to fish out IPv6 addresses from Syncthing's web UI and it'd be nice to not have to use the DOM inspector to do it.  I can't say that I've had to do it often enough that it is really a big deal to me though.  Maybe a click handler to copy addresses to the clipboard feature would be better?

**Comment by calmh** [comment]
Could be. Most browsers show he truncated value as a tooltip, but that probably doesn’t help much for copy and paste. They are also in the log.

**Comment by bugith** [comment]
I also meet this kind of difficulty. I worked around temporally with zoom out (Ctrl+- and Ctrl++|Ctrl+0 in FF)

**Comment by generalmanager** [comment]
+1 for the clipboard feature

**Comment by AudriusButkevicius** [comment]
Please stop bikeshedding and +1'ing random feature requests that do not relate to the original issue.

**Comment by generalmanager** [comment]
Sure, I'll refrain from +1'ing and use the reaction emojis instead, I also didn't notice that there hasn't been any activity for over a month and I apoligize for that.
I really didn't intend to bikeshed or nitpick, and I don't get how the idea to offer a "copy to clipboard" functionality could seem unrelated to the original issue. The title is literally about nicer handling, with part of the authors intention beeing to be ably to copy the IPv6. As the most simplistic approach (show it in full) appears infeasible/unneccessarily complicated, this seemed like the best alternative.

**Comment by otbutz** [comment]
Just fiddled a bit with the CSS using Firefox page inspector. It seems that setting `table-layout: auto;` for `table.table-condensed` fixes the display of long IPv6 addresses without noticeable visual regressions. I'm going to test it a bit further later.

Before:
![grafik](https://user-images.githubusercontent.com/22315436/53499030-d17b9f00-3aa7-11e9-83f6-a2b29f62c049.png)

After:
![grafik](https://user-images.githubusercontent.com/22315436/53499039-d6d8e980-3aa7-11e9-9387-7ef80e3a91ef.png)

https://github.com/syncthing/syncthing/blob/88b0ce892d1643bda592a898072a5147e0c8ea6c/gui/default/assets/css/overrides.css#L108-L110

**Comment by imsodin** [comment]
Check a few modals at various window sizes - I have fiddled with those table layouts as well in the past and I seem to remember that auto has some very undesirable effects. If my memory is correct, but auto is nice for this particular element you might consider adding a subclass or just locally changing the properties (no idea what the "proper way" is, I have hardly any CSS/HTML knowledge).
