### ISSUE TITLE
Unexpected network traffic for relaying when relaying is disabled

### ISSUE THREAD

**Issue by TraceyC77** [syncthing/syncthing#4536]
**What happened**
After checking my firewall logs I noticed a lot of entries for blocked traffic from Syncthing that were unexpected. I have "Enable Relaying" disabled. This did not used to happen on previous versions of syncthing

Syncthing version: v0.14.40, Linux (64 bit)
OS: CentOS 7 64-bit

This has also been reported by others on the Syncthing forums:
https://forum.syncthing.net/t/3478-udp-network-traffic-after-upgrade/10937

**What you expected to happen instead**
When discovery is disabled via settings no discovery network traffic is sent from syncthing

**Additional Information:**
Some example entries with sensitive information removed (SRC IP is my server's IP):
```
Nov 21 07:51:40 cp kernel: Firewall: *UDP_OUT Blocked* IN= OUT=eno1 SRC=xx.xx.xx.xx DST=77.72.xx.xx LEN=72 TOS=0x00 PREC=0x00 TTL=64 ID=60601 DF PROTO=UDP SPT=22020 DPT=3478 LEN=52 UID=32011 GID=32011 
Nov 21 07:51:40 cp kernel: Firewall: *UDP_OUT Blocked* IN= OUT=eno1 SRC=xx.xx.xx.xx DST=77.72.xx.xx LEN=72 TOS=0x00 PREC=0x00 TTL=64 ID=60602 DF PROTO=UDP SPT=22020 DPT=3478 LEN=52 UID=32011 GID=32011 
Nov 21 07:51:40 cp kernel: Firewall: *UDP_OUT Blocked* IN= OUT=eno1 SRC=xx.xx.xx.xx DST=217.10.xx.xx LEN=72 TOS=0x00 PREC=0x00 TTL=64 ID=47889 DF PROTO=UDP SPT=22020 DPT=3478 LEN=52 UID=32011 GID=32011 
Nov 21 07:51:40 cp kernel: Firewall: *UDP_OUT Blocked* IN= OUT=eno1 SRC=xx.xx.xx.xx DST=216.93.xx.xx LEN=72 TOS=0x00 PREC=0x00 TTL=64 ID=6161 DF PROTO=UDP SPT=22020 DPT=3478 LEN=52 UID=32011 GID=32011 
Nov 21 07:51:40 cp kernel: Firewall: *UDP_OUT Blocked* IN= OUT=eno1 SRC=xx.xx.xx.xx DST=212.227.xx.xx LEN=72 TOS=0x00 PREC=0x00 TTL=64 ID=57372 DF PROTO=UDP SPT=22020 DPT=3478 LEN=52 UID=32011 GID=32011 
```

**Comment by AudriusButkevicius** [comment]
This is not relaying, this is KCP traffic, which is direct, just over UDP.
There are some port lookups that happen to IPs you might not recognize however, as it's part of the STUN protocol.
