### ISSUE TITLE
Panic in "pfilter" package on 32 bit architectures

### ISSUE THREAD

**Issue by xjtdy888** [syncthing/syncthing#4537]
Panic at 2017-11-21T16:45:01+08:00
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4012cc]

goroutine 571 [running]:
sync/atomic.AddUint64(0x2059a13c, 0x1, 0x0, 0x5dc, 0xb8)
	/usr/local/go/src/sync/atomic/asm_386.s:112 +0xc
github.com/syncthing/syncthing/vendor/github.com/AudriusButkevicius/pfilter.(*PacketFilter).loop(0x2059a120)
	/usr/local/gopkg/src/github.com/syncthing/syncthing/vendor/github.com/AudriusButkevicius/pfilter/filter.go:132 +0x105
created by github.com/syncthing/syncthing/vendor/github.com/AudriusButkevicius/pfilter.(*PacketFilter).Start
	/usr/local/gopkg/src/github.com/syncthing/syncthing/vendor/github.com/AudriusButkevicius/pfilter/filter.go:90 +0x33

**Comment by calmh** [comment]
I think this is an alignment problem on 32 bit archs. Counters need to be at the top of the struct.
