### ISSUE TITLE
upnp: windows 32bit UDP ReadFrom never return 

### ISSUE THREAD

**Issue by xjtdy888** [syncthing/syncthing#4538]
On the windows 32bit arch UDPConn SetDeadline Did not work
in upnp package block at ReadFrom for  responses
Cause upnp does not work

```
goroutine profile: total 84
8 @ 0x42af38 0x4255d2 0x424cde 0x49fad3 0x4a0a08 0x4a2423 0x52e1df 0x547eef 0x546006 0x81d55e 0x8220f9 0x451ff1
#	0x424cdd	internal/poll.runtime_pollWaitCanceled+0x2d		/usr/local/go/src/runtime/netpoll.go:189
#	0x49fad2	internal/poll.(*pollDesc).waitCanceled+0x32		/usr/local/go/src/internal/poll/fd_poll_runtime.go:101
#	0x4a0a07	internal/poll.(*ioSrv).ExecIO+0x1c7			/usr/local/go/src/internal/poll/fd_windows.go:235
#	0x4a2422	internal/poll.(*FD).ReadFrom+0xd2			/usr/local/go/src/internal/poll/fd_windows.go:591
#	0x52e1de	net.(*netFD).readFrom+0x3e				/usr/local/go/src/net/fd_windows.go:157
#	0x547eee	net.(*UDPConn).readFrom+0x3e				/usr/local/go/src/net/udpsock_posix.go:47
#	0x546005	net.(*UDPConn).ReadFrom+0x55				/usr/local/go/src/net/udpsock.go:118
#	0x81d55d	github.com/syncthing/syncthing/lib/upnp.discover+0x9bd		/usr/local/gopkg/src/github.com/syncthing/syncthing/lib/upnp/upnp.go:182
#	0x8220f8	github.com/syncthing/syncthing/lib/upnp.Discover.func1+0x48	/usr/local/gopkg/src/github.com/syncthing/syncthing/lib/upnp/upnp.go:99
```

**Comment by calmh** [comment]
UPnP discovery seems to work fine (although not find any devices, because I don't have any) on my 32 bit Windows XP.

**Comment by xjtdy888** [comment]
I do not know the specific reasons for the occurrence of the above debugging is in windows 32 xp, debugging has been found to be blocked here, in addition there are some circumstances windows 32 bit MulticastUDP can not receive any data, also led to upnp failure.
Another machine windows 8.1 or windows 10 is working properly.
In the paralles desktop virtual windows xp 32 is working

**Comment by calmh** [comment]
It sounds like it's something specific to your system, or specific to some variants of Windows XP. That's unfortunately not something we can debug here. Windows XP support in Syncthing is on the level of if it works, that's great but nu guarantees.

**Comment by xjtdy888** [comment]
Yes, this problem is not very friendly debugging, but has not worked  on many machines,
Today in the debugging process I can only locate the ReadFrom has been blocked can not get back, but I do not have the ability to debug golang core

**Comment by AudriusButkevicius** [comment]
It sounds to me like a runtime bug not a syncthing bug regardless, so perhaps you should raise it with them.
