### ISSUE TITLE
Catastrophic sync: sync-conflict files larger than originals 

### ISSUE THREAD

**Issue by tomachinz** [syncthing/syncthing#4541]
During a big cleanup of sync-conflict files, prior to deleting them on-masse using a bash script I discovered some of the sync-conflict files are larger than originals, and the originals corrupted:

![sync-conflict issue](https://user-images.githubusercontent.com/1026291/33158488-3863ff40-d06f-11e7-8a33-da1319da5d58.png)

I now have to manually delete the originals and rename the all files with this sync-conflict to be the original file:

Tiefschwarz - Essential Mix (2006-05-28).sync-conflict-20170409-192607.mp3
--> Tiefschwarz - Essential Mix (2006-05-28).mp3

I have a large music drive (two of them mirrored) that is synced between two computers, and likely due to an interupted initial sync, followed by swapping the drives between different machines running syncthing, 

I'm planning to resolve this using a batch rename that first DELETES the original file, then RENAMES the conflict file to be the same as the original but don't know enough regular expressions to make it do the rename:

find . -name '*.sync-conflict-20*' -exec mv -v  {} \;

I assume something like:
(*).sync-conflict-20(*)
then I need to join the two capture groups eg:

find . -name '*.sync-conflict-20*' -exec mv -v  {$sync-conflict-file} {$original-filename} \;

like mv $a $b$c

But not sure how to formulate the mv command to then output the old filename as the destination. 

Syncthing Version: v0.14.40, Mac OS X (64 bit) 
OS Version: 10.12.6 (16G1036) Sierra

**Comment by calmh** [comment]
I can't even speculate as to the cause of this, but

> and likely due to an interupted initial sync, followed by swapping the drives between different machines running syncthing

will certainly confuse Syncthing. I don't believe it would make up new content and sizes on it's own, though. As such I don't think this is an actionable issue unless the problem can be reproduced.

**Comment by calmh** [comment]
Not reproducible.

**Comment by tomachinz** [comment]
I too have seen catastrophic data loss.



Tom Atkinson - Director
The Tomachi Corporation
M: 021 257 6422 <+64212576422> | Web: tomachi.co
<http://tomachi.co/?utm_source=TomsEmailSignature&utm_medium=email&utm_campaign=TomsEmailSignature>
|
backup phone: 021 262 2096
<http://tomachi.co/?utm_source=TomsEmailSignature&utm_medium=email&utm_campaign=TomsEmailSignature>

<http://www.funk.co.nz/?utm_source=TomsEmailSignature&utm_medium=email&utm_campaign=TomsEmailSignature>

____________________________________
____________________________________
Subscribe
<http://www.funk.co.nz/amu/?utm_source=TomsEmailSignature&utm_medium=email&utm_campaign=TomsEmailSignature>
to
Auckland Music Update
Bands: tomachi.tv | triptonites.com
<http://www.triptonites.com/?utm_source=TomsEmailSignature&utm_medium=email&utm_campaign=TomsEmailSignature>
<http://www.facebook.com/tomachinz>  <https://twitter.com/tomachi>
<http://www.youtube.com/playlist?list=PL4C4799FDA135D2FE>
<http://soundcloud.com/tomachi>  <http://tomachi.tv/>

**Comment by tomachinz** [comment]
Hi CalmH this is I agree hard to reproduce. And yeah moving the disk to another machine and then "adding" the huge 3TB folder prior to the first machine finishing it's initial sync was fairly insane, but I didn't think it would take longer than 24 hours, I think perhaps i decided to move it to a dedicated laptop so I could move my main laptop around more often. **I'm very keen to understand the internal structure of the syncthing database.** Is that safe to delete? The ~/Library/Application Support/Syncthing/ folder is 5.38 GB. The largest folder (its called "4TB" but is 3TB: 2,969,022,413,970 bytes (2.97 TB on disk) for 1,661,103 items ) HFS+.

 The files inside 
However, since the damage is done (3TB folder now contains X files with 'sync-conflict' in the name)... I'm wondering what I should do long term. Currently reading up on "find" and "rename" :) 

![image](https://user-images.githubusercontent.com/1026291/34401113-24c1d526-ebfd-11e7-953e-ce4580617073.png)

**Comment by AudriusButkevicius** [comment]
Please use the forum for support. Issue tracker is the wrong medium for random questions.
