### ISSUE TITLE
Confirmation on Remove Folder Button

### ISSUE THREAD

**Issue by AtoxIO** [syncthing/syncthing#4543]
Three times already I've deleted a folder by accident trying to click on Advanced settings. It takes hours for the reindex, which really is a pain. So I want to suggest adding a simple "Are you sure? Yes/No" confirmation on the folder remove button, as is pretty much an industry standard.

**Comment by calmh** [comment]
We've deliberately placed the button well away from other things for this reason, but I guess we could do this as well.

**Comment by qepasa** [comment]
I'd like to work on this issue

**Comment by AudriusButkevicius** [comment]
Go for it
