### ISSUE TITLE
sync while file changes

### ISSUE THREAD

**Issue by eskornev** [syncthing/syncthing#4546]
Hello!
Is it by design that while file changes (grows) it doesn't sync?
If sending server disappears while writing data we will lose some.
My test shows that linux inotify subsystem shows changes in file while service writes to it.

Versions:
- syncthing v0.14.40 "Dysprosium Dragonfly" (go1.9.2 linux-amd64)
- ubuntu 16.04.2

**Comment by calmh** [comment]
Yes, we need the file in a consistent state to be able to hash it. This is as intended.
