### ISSUE TITLE
"Latest Change" field ignores local changes on desktop clients.

### ISSUE THREAD

**Issue by mtfurlan** [syncthing/syncthing#4550]
When I update files locally, the "last change" does not update to the file that was updated.
The changes are propagated to other devices.
When I update a file remotely, "Last Change" is updated.

I've been manually pressing the "sync" button, not assuming the filesystem notify stuff works.

This happens on both debian stretch and windows 7.
This does not happen on the android client's web view, v0.10.0. As far as I can see the non-web view doesn't show "Last Change".

stdout in windows doesn't look to contain any useful information, and I can't easily get at it from debian till monday cause I've been too lazy to write a systemd service for it.

Syncthing: v0.14.40 on platforms: win7, debian stretch, and android.
OS: Win7, debian stretch with a newer kernel `Linux boethiah 4.9.0-2-amd64 #1 SMP Debian 4.9.18-1 (2017-03-30) x86_64 GNU/Linux`
Browser:
* Testing windows syncthing:
** Firefox 52.5.0 on windows
** Chrome 61.0.3163.100 on windows
** qsyncthing tray 0.5.2 on windows
* Testing debian syncthing
** Firefox 52.5.0 on windows
* Testing android syncthing:
** whatever internal browser it has

What other information would be sueful?

**Comment by AudriusButkevicius** [comment]
This is intended, it shows last remote change.

**Comment by calmh** [comment]
That's not true, it shows local changes as well. This works for me.

**Comment by mtfurlan** [comment]
Okay. So I would advocate to change the name then, as I noticed that it hadn't updated one of my files in two months that I know was changed more recently, and was trying to debug why syncthing wasn't noticing changes before I finally started trying on a different host and noticed the test files were showing up.

Maybe "Latest Remote Change"?

**Comment by calmh** [comment]
But it's not a remote change, we applied it locally.

(Yes, playing devils advocate, but we've had a lot of these naming discussions and people generally don't agree or interpret things exactly the same way. But I think having two different things in the two places is probably not the right thing.)

**Comment by AudriusButkevicius** [comment]
It used to be called "Last Received", but then people started complaining that `"Last Received"; "Deleted xyz"` doesn't make any sense.

This is why I hate people.

**Comment by mtfurlan** [comment]
What's the rationale behind "Latest Change" only showing changes made remotely?
I think "Last Received" makes far more sense than "Latest Change", as it's still clear what it does even if it doesn't always read quite properly.

I hadn't actually seen the "Global Changes" box, though now that I've looked at it, it seems like the most useful thing would be a per-directory "recent changes" list of that style.
