### ISSUE TITLE
Announcing a given address

### ISSUE THREAD

**Issue by cy18** [syncthing/syncthing#4557]
I think it would be useful if syncthing could announcing a given address. For example:
1. When Syncthing is running in a docker container.
2. Reversing proxy, such as [frp](https://github.com/fatedier/frp) is used.

**Comment by calmh** [comment]
Possibly, but this already works in the case when the external port is the same as the one Syncthing listens on. We rely on this for manual NAT port mappings for example.

**Comment by cy18** [comment]
When the port is the same, it also need the external IP to be the the same as the NAT gate IP. It is usually true when running in a docker container, but not when a reversing proxy is used.

**Comment by AudriusButkevicius** [comment]
Reverse proxy has nothing todo with this, as you can only put that in front of web ui but not proticol or discovery ports.

**Comment by cy18** [comment]
@AudriusButkevicius Why not?

**Comment by AudriusButkevicius** [comment]
Because these are either outward connections which don't care about reverse proxy or not even using HTTP. If your discovery server is behind a reverse proxy, I think discovery server respects X-Fordwarded-For

I am closing this, it seems you have some generic support issue, hence this should be handled on the forum.

**Comment by cy18** [comment]
Maybe you mean the HTTP reverse proxy? What I meen is a tcp reversing proxy. I think it works in this case.

**Comment by AudriusButkevicius** [comment]
Sorry, but I see this will be a lengthy discussion, as I am not sure I understand what you are doing, why and what issues you are having, hence it's best if this moves on the forum.

**Comment by AudriusButkevicius** [comment]
Also, what you are doing is essentially replicating what relay servers are for.
