### ISSUE TITLE
"Unlinked" devices try to connect (Laptop <-> smartphone)

### ISSUE THREAD

**Issue by klausenbusk** [syncthing/syncthing#4558]
Syncthing running on my Android phone is getting a (kcp) connection from a unknown device, which match my laptop (and vice-versa). As the smartphone and laptop doesn't contain each other as `remote device`, this shouldn't happen.

Log line (on my Android phone):
> Connection from <id of syncthing running on my laptop> at <ip of my server, where syncthing is running> (kcp-client) rejected: unknown device

Network overview:
Smartphone: Local 192.168.xx.xx ip
Laptop: Local 192.168.xx.xx ip
Server: Local 192.168.xx.xx ip and external xx.xx.xx.xx ip

I'm not sure why this is happening from time to time, but I think local discovery and the fact that my server is available through both a internal and external ip has something to say.

### Version Information

Syncthing Version: v0.14.40 (laptop, smartphone and server), 0.10.0 (Syncthing android UI)
OS Version: ArchLinux (laptop + server), Android 7.1.2 (LineageOS)

**Comment by AudriusButkevicius** [comment]
Support is handled on the forum.

**Comment by klausenbusk** [comment]
> Support is handled on the forum.

So it is expected that Syncthing sends packets to the wrong device?

**Comment by AudriusButkevicius** [comment]
No, but nor does that doesn't mean it's a bug, and could be down to network topology.
