### ISSUE TITLE
Windows - External File Versioning Command path requires \\ instead of \

### ISSUE THREAD

**Issue by yukinakato** [syncthing/syncthing#4560]
### What happened

On Windows, an external versioning command path requires \\\\ (two backslashes) instead of single \\.
This sounds a bit unnatural and the instruction in [the doc page](https://docs.syncthing.net/users/versioning.html#example-for-windows) doesn't work.

### Any steps to reproduce the problem.

For example, if the command is set like this:

![iss](https://user-images.githubusercontent.com/22708232/33383288-47d8731a-d566-11e7-91f6-c5bfbede64c9.png)
then I get this error log:
`[VQZ3H] 2017/11/30 00:25:31.724302 rwfolder.go:1675: INFO: Puller (folder "\"sttest\" (vu3ga-eo2y9)", file "test.txt"): delete file: exec: "C:UserstestusrDesktopext.bat": file does not exist`

OK the path isn't recognized correctly with single \ for some reason.

I found two workarounds:
- use \\\\ instead of \\
- use / (this is uncommon for windows)

### Version Information

Syncthing Version: v0.14.40
OS Version: Windows 10 x64
Browser Version: Edge

**Comment by Kropekk** [comment]
I'll try to fix this in the following days.

**Comment by AudriusButkevicius** [comment]
I suspect it's due to the shell escaping library, which might not be needed at all, as we are not parsing external input.

The purpose of it was to handle cases where folder path contains spaces.
I guess we need a test case there.

**Comment by calmh** [comment]
Or, possibly, different treatment just on Windows where backslash is not to be interpreted as an escape.
