### ISSUE TITLE
Crash after PC wake-up - panic: interface conversion

### ISSUE THREAD

**Issue by scienmind** [syncthing/syncthing#4561]
ST crashed after waking the system from sleep with this error:
`panic: interface conversion: *errors.errorString is not net.Error: missing method Temporary`

The setup is rather unremarkable, no altered advanced config.; restart on wake is set to default (enabled)

Log:
https://gist.github.com/anonymous/0a4582c93581903cb79c1a76d6d3b07e

### Version Information

Syncthing Version: v0.14.40 running under SyncTrayzor v.1.1.18
OS Version: Win10x64

**Comment by AudriusButkevicius** [comment]
Thanks.
