### ISSUE TITLE
After declining a folder share, is it not possible to accept a share for that same folder

### ISSUE THREAD

**Issue by edi9999** [syncthing/syncthing#4565]
### Version Information

Syncthing Version: v0.14.41-rc.6
OS Version: Ubuntu 16.04
Browser Version: Chrome

I have shared a folder called "Music" from my device "server" with a local device "dell". At the time I did this, I had not enough space on the "dell" device, so I declined the share.

I have now cleaned up my computer and have enough space to share my "Music" folder, however, if I go to  the folder "Music" on my "server", if I uncheck the device "Dell", restart both synchthing instances, then check the device "Dell" for sharing the folder again, no notification appears on my "Dell" device.

I have tried to add an other folder which I never shared before called "modules", this shows up in the notification on the "Dell" device.

How can I fix this problem ?

**Comment by AudriusButkevicius** [comment]
You should press later and not reject, as reject explicitly blocks the folder from ever showing up again.
You'll have to manually clean up the config to undo this.

**Comment by AudriusButkevicius** [comment]
Also, support is handled on the forum like the issue template explains.

**Comment by edi9999** [comment]
Sorry for the noise. Thanks that helps
