### ISSUE TITLE
Arguments to fs.CreateSymlink are mixed up

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#4567]
In the interface and everywhere else, it is name then target, except for basicfs on unix, where it is the other way around:

```
lib/fs/errorfs.go:func (fs *errorFilesystem) CreateSymlink(name, target string) error                     { return fs.err }
lib/fs/basicfs_windows.go:func (BasicFilesystem) CreateSymlink(path, target string) error {
lib/fs/logfs.go:func (fs *logFilesystem) CreateSymlink(name, target string) error {
lib/fs/filesystem.go:   CreateSymlink(name, target string) error
lib/fs/basicfs_unix.go:func (f *BasicFilesystem) CreateSymlink(target, name string) error {
```

I guess the basicfs on unix version is correct, as it is consistent with the os library.

**Comment by AudriusButkevicius** [comment]
We should call it source and target and correct everywhere I guess.

**Comment by calmh** [comment]
So does this mean we do it wrong when creating symlinks on Unix...?

**Comment by AudriusButkevicius** [comment]
I am pretty sure the end result works, as we'd have people complaining.

**Comment by imsodin** [comment]
Yes it is correct there, I would have complained in a different manner if it wasn't :)  
It's "just" the arguments in the interface and dummy/wrapper functions which are wrong. Apparently go interfaces only care about argument types, not argument names. Any naming involving "target" (thing the link will be pointing to) seems clear to me.
