### ISSUE TITLE
Negative percentage and data to sync

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4570]
Again/still/always... This time when adding a new device and doing the initial sync. I think this makes it relatively easy to reproduce. This is a long lived folder, so the first million or so index entries are for sure for deleted files. While these are processed it looks like this:

![screen shot 2017-12-05 at 11 53 45](https://user-images.githubusercontent.com/125426/33604363-f935841a-d9b5-11e7-9ea2-763093407833.png)

Note both length of the progress bar and the bytes remaining to sync. Once it starts processing actual missing files it becomes normal.

**Comment by sisu4syncthing** [comment]
can we reopen?

I just had this with  v1.2.1-rc.5, macOS (64 bit)

<img width="898" alt="st Bildschirmfoto 2019-08-01 um 23 26 37" src="https://user-images.githubusercontent.com/12977080/62336758-17fb7c80-b4d2-11e9-9831-32484115ff2c.png">
<img width="609" alt="st Bildschirmfoto 2019-08-01 um 23 26 27" src="https://user-images.githubusercontent.com/12977080/62336759-17fb7c80-b4d2-11e9-9287-e4ef6e8981b3.png">
