### ISSUE TITLE
download only from local devices if available

### ISSUE THREAD

**Issue by Hello71** [syncthing/syncthing#4571]
my upstream connectivity is metered, so I want syncthing to download only from "local" devices if missing data can be acquired there, even if synchronization is slower that way. on my networks, defining "local" as either "discovered using local discovery" and/or "on the same local subnet" is sufficient, whichever is easier to implement. a fixed list of preferred peers also works, but would probably be clunky to set up.

### Version Information

Syncthing Version: v0.14.40

**Comment by AudriusButkevicius** [comment]
Just pause the peers that are external.

**Comment by calmh** [comment]
Or set a very low rate limit, since rate limits do not by default apply to LAN connections

**Comment by imsodin** [comment]
Hello71 probably wants this to happen automatically, probably knowing about pausing devices. Same for rate limiting: When offsite, this is probably undesired and would need to be manually disabled. In principle a device from a specific subnet (or just LAN) could always (if available) be picked when checking the availability during pulling. To me this is more a case of "fine, but probably never going to happen" than something definitely out of Syncthing's scope.

**Comment by calmh** [comment]
I think device priorities would be somewhat annoying to implement, be of limited utility (the "local" thing is your request, I'm sure there are other reasons), and increase the amount of support issues with devices not connecting for some unexplainable reason (because the other side has decided to prioritise someone else).

**Comment by hzulla** [comment]
I'd like to add a very big +1 to this request. Synthing should automatically detect if there are sync peers in the local network and only use these - unless, of course, there are files on the remote peers that the local peer(s) haven't synced yet.

In my case, the DSL isn't metered, but still it is annoying to watch the connection clog up and waste bandwidth when local network peer(s) already have all the files available.

I'm aware that I can achieve this manually by pausing remote peers, as described by @AudriusButkevicius, but I'd prefer to see an implementation to do this automatically as described by @imsodin. Thanks!

**Comment by AudriusButkevicius** [comment]
It's most likely using local peers for most of the traffic anyway, as local peers are much faster to respond than remote ones, naturally getting more data from local peers.

**Comment by hzulla** [comment]
True.

But here's my scenario. I have a large media archive (hundreds of gigabytes of data) on my Syncthing setup. When I add a new, empty peer, it begins to aggressively pull files from all peers it finds, including remote peers, even if all the files are already present on the local network's NAS. This clogs the internet connection for me and wastes bandwidth for the rest of the internet, yet it's totally unnecessary.

Syncing from all peers is usually justified as it speeds up sync completion. But in my case, the sync takes several hours, adding sync from the remote peers only adds a miniscule "speedup" while clogging the internet connection for the sync until completion.

Yes, all of this can be handled by tweaking the settings manually, but having a complete peer on the local network is probably such a common scenario that this should benefit many users (and reduce global bandwidth waste of Syncthing).

**Comment by imsodin** [comment]
If the problem is that other services in your network suffer, Syncthing has bandwidth limiting and  supports QoS (see trafficClass config param).

**Comment by hzulla** [comment]
Reducing global bandwidth use is a useful goal for P2P and helps the internet as a whole.

All of this can be done manually, but a user-friendly P2P software benefits from having sensible automatic settings for common cases like this.

Other, real world scenario, which I encounter frequently.

- I have a work computer (rarely on), a work NAS (always on), a home NAS (always on) and a home computer (rarely on).
- If I add a (large) file to my work computer, it gets synced to the work NAS and the home NAS. As desired.
- The sync is completed before I finish my day at the office. As desired.
- I turn off my work computer, go home.
- I turn on my home computer.
- The home computer starts syncing the new file from the home NAS. As desired.
- The home computer pulls bits from the work NAS at the same time, using up internet bandwidth.

This imho isn't the desired behaviour. The complete file is already synced to the home NAS, there is no need to pull bits from the work NAS at the same time. This is wasted bandwidth, for me and for everybody else on the internet.

**Comment by hzulla** [comment]
(P.S.: Yes, I could setup my home computer to sync with the home NAS, only. But my home computer is a laptop. I take it to the office, often. So of course it's configured to sync with all three other devices, not just the home NAS. The strong point of P2P is that it can handle changing network layouts automatically without requiring the user to change the settings whenever the device travels.)

**Comment by AudriusButkevicius** [comment]
Anyways, I personally don't feel a strong need to have this.
If you are that concerned about it, feel free to propose a pull request with the implementation.

**Comment by hzulla** [comment]
Can try, but can't promise much.

My naive assumption would be that given a list of peers for a missing block, Syncthing should always choose a local peer if one exists.

Given my total ignorance of the syncthing code, please give me a brief initial hint at what to look at. Which part of the code is responsible for choosing a peer to download a block from?

**Comment by AudriusButkevicius** [comment]
You probably need to modify 

https://github.com/syncthing/syncthing/blob/master/lib/connections/structs.go#L24

and expose IsLAN() for each connection. The classification is already done somewhere in service.go where we decide to wrap connections with rate limiters.

Then in 

https://github.com/syncthing/syncthing/blob/master/lib/model/model.go#L2379

you probably need to tap into m.conn[device] to get your hands onto the connection and enrich Availability with Lan bool = c.IsLan().
Also, I guess it should sort the availabilities putting LAN ones first.

And then modify:

https://github.com/syncthing/syncthing/blob/master/lib/model/rwfolder.go#L1327

to be something like preferred(), and the implementation in:

https://github.com/syncthing/syncthing/blob/master/lib/model/deviceactivity.go#L29

to take into account the busyness and locality somehow, yet I am not sure how you force not go to the internet if the local device has a lot of requests outstanding.

 I'd put this behaviour behind a config flag and keep the default as it is, as I think it's not making things better in general, as you are potentially queueing up a lot of local requests which might not be getting any data, instead of going proper P2P and getting the data as fast as you can.

**Comment by hzulla** [comment]
Thanks a lot for the hints! Will have a look.

> as I think it's not making things better in general, as you are potentially queueing up a lot of local requests which might not be getting any data, instead of going proper P2P and getting the data as fast as you can.

As the cows aren't home yet, I strongly disagree here.

**Comment by hzulla** [comment]
Oh wow, thanks again. You laid out everything needed to understand the parts of the code I wanted to find.

**Comment by calmh** [comment]
FWIW I would much rather see a smarter general queueing algorithm that doesn’t need switches and knobs. We could for example track the latency from requesting a block to getting the data for it, and thus get a somewhat dirty bandwidth metric per remote device. Then let the busyness selector take this into account and weight accordingly, maybe with a constant multiplier of some kind so vastly faster devices get the significant majority of all requests.
