### ISSUE TITLE
Inaccessible files during scan are marked as deleted

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#4573]
Repro:

1. Create `dir/file` and make sure they are synced between devices A and B.
2. Change ownership/permission for `dir` on device A such that the user syncthing is running as is no longer able to access `dir` (e.g. `sudo chown root:root dir && sudo chmod 700 dir`).
3. Hit the rescan button on device A and wait for "changes" to propagate to B.

Result: `dir/file` gets deleted from device B.

Expected: Some kind of error or at least "nothing" (see #4480), but certainly not deletion of the file on the remote.

Origin of bug:  
Lstat returning any error is considered equal to file having been deleted: https://github.com/syncthing/syncthing/blob/master/lib/model/model.go#L1989

Possible solutions:  
Maybe this can be handled with stricter checking of the error returned by Lstat. If we do this, I believe we need to add `IsNotExist(err) bool` to the filesystem interface to make sure all filesystem implementations are compatible with this check.  
The following idea doesn't actually work (we also detect "ordinary" deletes this way).<strike>It might be both more consistent and performant to drop these lstat checks and replace them by comparing the new file info with the one it has replaced. Thus cases like replacing a dir with a file can still be detected and handled, while the case described here wont result in data loss.</strike>  
Another possibility would be to implement #4480 and skip the current lstat tests on paths that failed to be scanned.

**Comment by calmh** [comment]
This is mostly deliberate, as it's kind of hard to decide which errors mean the file doesn't exist. One typical case (that might be solved by your new stuff) is when a directory becomes a file, for example. Stat of the files inside the (previous) dir doesn't return IsNotExist.

Deliberate or not it may still be wrong, so feel free to improve it. :)

**Comment by imsodin** [comment]
> Similarly, your test case (we lose permissions to a directory) means to me that we should propagate this as a delete, as it might be deliberate.

I guess that's the only thing to be discussed then, because if this is to be expected, this bug report is invalid. For me it is unexpected that something gets deleted when it becomes unavailable for any other reason than being deleted (e.g. permissions changed), and thus falls under our 1. goal against data loss. I tried to find arguments, but I don't have any. It just feels wrong to "delete" files by changing permissions: In my opinion changing permissions should prevent Syncthing from accessing something, but isn't simultaneously a sign to get rid of it...

**Comment by calmh** [comment]
Well I can agree with that. Question then is just how to handle it. I think we were discussing somewhere else what do about scanning errors; currently they're sort of invisible. And we need to make sure we cover stuff like dir-to-file conversions, which you're already on top of.

**Comment by tedbacc** [comment]
Hi, I absolutely agree with the OP, it's tragic when something goes wrong and a mass of files is unintentionally deleted. 
I would suggest a modal popup message before syncing say anything over 100 recognised deletions asking user to confirm before deleting. Yes I know that might be inconvenient in some instances, but honestly wayyyy less inconvenient than say an entire direcory being deleted due to user error....
Thanks, guys, love syncthing it's the best bar none. I have 1363449folders   93891dirs   ~20292GB being synced perfectly across 2 Synologies... Cheers!!!

**Comment by scienmind** [comment]
If you're go for changing stuff there, please mind the "Case-only renames" mess (https://github.com/syncthing/syncthing/issues/1787). Fast case-renames caused unwanted deletes few times for me.

**Comment by AudriusButkevicius** [comment]
We don't have enough people solving the problems, yet we have more than enough project managers telling what needs to be solved.

**Comment by scienmind** [comment]
Hey, I'm not telling anyone what needs to be solved and what isn't. 
Obviously I'm not in any position to do such a thing.
The great majority of work here done by only few core contributors, to whom I'm very thankful.

I occasionally chime in to give some feedback and/or rise a point I consider relevant. I apologize if you find my comment contrary to helpful. You are free to ignore my input as you like.

**Comment by AudriusButkevicius** [comment]
Code fixing this would have close to no overlap with an code fixing case only renames, so I am not sure "hey while you're at it - fix this too" is useful input.

The only thing this has with case only renames is the fact that the end result is the same - which is under some circumstances files end up deleted.

We are well aware of what the annoying pain points are, so no need to cross reference and convolute issues and give pointers what we should fix, same way like you did in #4551.

**Comment by calmh** [comment]
Cross linking otherwise not related issues is somewhat unhelpful. It makes them permanently connected, increasing clutter and causing potential confusion for readers of either who might expect there to actually be some relation now.

Sarcasm in the issue tracker is also unhelpful.

Each and every comment by anyone in the issue tracker becomes an email and/or a notification to each and every contributor or watcher. This is one reason we try to keep the forum style discussion in here to a minimum. In short, all of you: cease bickering, you're harshing my mellow. :) Bicker all you want on the forum or somewhere else.

**Comment by swt2c** [comment]
Sorry to jump in here, but I wanted to add another situation where this is problematic.  Say, for instance, that there is an I/O error while trying to Lstat() a file (perhaps filesystem corruption or failing hard drive?).  Now, syncthing is going to delete the good copy of the file from the remote.

**Comment by Ferroin** [comment]
There's a handful of very specific error codes that should probably not be treated as deletion, namely whatever the Go equivalents are to EIO, ESTALE, EAGAIN, all of which aren't indicative of the file being gone, just not being accessible for reasons other than permissions (I do agree that lack of access permissions makes sense to trigger deletion though).

**Comment by imsodin** [comment]
This is already solved, see #4765. It will not remove anything unless we know for sure it has been deleted (parent is file/symlink or IsNotExist from Go's os package is true).
