### ISSUE TITLE
Web GUI - (unknown device) - CSRF Error

### ISSUE THREAD

**Issue by LogIN-** [syncthing/syncthing#4580]
I am using syncthing for some time now without any issues
Today I wanted to check something on the server in syncthing GUI.

Issue was following basically GUI was mostly empty, and by checking Network Requests via Developer Tools I noticed that each of those requests have the response: "CSRF Error"

![web_gui_2](https://user-images.githubusercontent.com/4036277/33745740-8bb90a92-db6d-11e7-8f42-7989fc0d5531.png)

Anyway I couldn't see any Folders, Devices or other configuration because of that. 

![web_gui_1](https://user-images.githubusercontent.com/4036277/33745729-7ff45db0-db6d-11e7-81a7-33da73852efd.png)

I tried to clear cookies in Firefox and all other cache data, also tried Incognito window but without success. 

syncthing is running on https subdomain with following nginx config:

```
location / {

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://127.0.0.1:8384;

        proxy_connect_timeout       600s;
        proxy_send_timeout          600s;
        proxy_read_timeout          600s;
        send_timeout                600s;
    }
```
For me, the solution after some debugging time was simply to use Chromium as a browser to access GUI than magically everything works as intended without issues. I must notice that I did not had this issues before.

### Version Information
Server OS
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

syncthing version
```
syncthing:
  Installed: 0.14.41
  Candidate: 0.14.41
  Version table:
 *** 0.14.41 500
        500 https://apt.syncthing.net syncthing/stable amd64 Packages
        100 /var/lib/dpkg/status
     0.14.40 500
        500 https://apt.syncthing.net syncthing/stable amd64 Packages
     0.14.39 500
        500 https://apt.syncthing.net syncthing/stable amd64 Package
```
my firefox:
```
Name            : firefox
Version         : 57.0.1-1
Description     : Standalone web browser from mozilla.org
Architecture    : x86_64
URL             : https://www.mozilla.org/firefox/
Licenses        : MPL  GPL  LGPL
Groups          : None
Provides        : None
Depends On      : gtk3  gtk2  mozilla-common  libxt  startup-notification  mime-types
                  dbus-glib  ffmpeg  nss  hunspell  sqlite  ttf-font  libpulse
Optional Deps   : networkmanager: Location detection via available WiFi networks [installed]
                  libnotify: Notification integration [installed]
                  pulseaudio: Audio support [installed]
                  speech-dispatcher: Text-to-Speech
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 155.68 MiB
Packager        : Bernhard Landauer <oberon@manjaro.org>
Build Date      : Thu 30 Nov 2017 05:17:42 AM PST
Install Date    : Wed 06 Dec 2017 01:35:36 PM PST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

```

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
