### ISSUE TITLE
Doesn't build on Darwin with Go 1.10

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4581]
Cgo strictness is increased, resulting in Zillode/notify#9. Needs to be fixed for Go 1.10 release, preferably sooner rather than later.

**Comment by AudriusButkevicius** [comment]
What's the actual issue though?

**Comment by calmh** [comment]
You can follow the link at a take a look.

**Comment by AudriusButkevicius** [comment]
Ah, my bad, didn't see that.

**Comment by calmh** [comment]
Basically a type went from being pointer shaped to being integer shaped so `nil`s need to be `0`s. I've filed a PR.

**Comment by calmh** [comment]
https://github.com/Zillode/notify/pull/10 which then became https://github.com/rjeczalik/notify/pull/136

**Comment by calmh** [comment]
Resolved in 57eb1710
