### ISSUE TITLE
macOS gui is in "Unknown device" state

### ISSUE THREAD

**Issue by ptomblin** [syncthing/syncthing#4582]
The syncthing gui on my local machine shows "(unknown device)" and doesn't show any folders, files, etc. It works fine on Safari. All I can see in the Firefox console is "loadFormIntoScope deviceEditor" twice. In the Network browser, it shows a whole bunch of 403s on things like http://localhost:8384/rest/events?limit=1. The same calls are getting 200s on Safari.

### Version Information

Syncthing Version: v0.14.41
OS Version: macOS High Sierra 10.13.2 (17C88)
Browser Version: Firefox 57.0.1, but not Safari 11.0.2

**Comment by calmh** [comment]
This doesn't happen for me with Firefox 57.0.2 on Sierra (no HS here yet, but I doubt that the issue). Given that it works for you with Safari and that we don't have a deluge of reports from other Firefox users I'd suggest troubleshooting your Firefox, disable extensions, etc. If I'm wrong and it's a general problem we'll reopen.
