### ISSUE TITLE
Versioner file tagging is inconsistent

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#4586]
Simple uses `file.ModTime()`, staggered uses `time.Now()`.

**Comment by calmh** [comment]
I think this is intentional. Simple just keeps a number of versions, and names them based on when the file was modified. Staggered tracks when the versions were created so it can keep x amount of them in a certain time interval etc.

**Comment by AudriusButkevicius** [comment]
Sure, but for purposes of restoring, it's confusing and not obvious that/why it differs.

**Comment by calmh** [comment]
So for clarity for future readers (because I had to go looking) we now always use the existing file modtime for the timestamp in the version name.

**Comment by calmh** [comment]
This was changed in v1.2.0, so that the timestamp in the *name* is when we archived the file; the mtime is unchanged.

The trashcan versioner doesn’t alter the name, so instead it *does* change the mtime to when we archived the file. This inconsistency will persist.
