### ISSUE TITLE
Tens of thousands of DNS queries per day from a single instance

### ISSUE THREAD

**Issue by vsviridov** [syncthing/syncthing#4587]
I've installed syncthing on my raspberry pi and even though it's currently not syncronizing anything, my PiHole instance logs tens of thousands of DNS requests to discovery servers originated from the Syncthing instance.

It looks similar to an issue described in #2718, but it's closed for comments.

`syncthing v0.14.39 "Dysprosium Dragonfly" (go1.9 linux-arm) deb@build.syncthing.net 2017-09-25 06:05:21 UTC [noupgrade]`

`Linux raspberrypi 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l GNU/Linux`

`Raspbian GNU/Linux 8 (jessie)`

**Comment by calmh** [comment]
Syncthing makes discovery requests. Those require DNS lookup. This is as designed.

**Comment by vsviridov** [comment]
25000 of them a day? How often do IP addresses for discovery servers are supposed to change?
What happens when I deploy this to all viable machines on my network?

TTL for syncthing default discovery records seems to be set to 24 hours.

Is there any way to affect the caching behaviour for these?

**Comment by calmh** [comment]
The staticly linked binary uses it’s own resolver as part of the Go runtime, which afaik does not cache. Your local resolver, or 8.8.8.8 or whatever, does however so in practice this is not an issue. Does it cause a practical problem for you?

**Comment by vsviridov** [comment]
It drowns out all meaningful logs from my local DNS caching server, but it's not that big of a deal.
