### ISSUE TITLE
Path completion in new folder dialog does not work anymore

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#4590]
Previously directories matching the current input were displayed in a dropdown box below the entry field when creating a new folder in the web UI. This does no longer work in general (it does e.g. work when entering just "/").

**Comment by calmh** [comment]
Mine

**Comment by grandchild** [comment]
There is a minor bug left, that often makes the completion not appear, only on backspace.
Notice how I typed `opencl` in full, then backspaced the final `l` after which the autocomplete appeared.

![untitled](https://user-images.githubusercontent.com/770029/34692659-241b8f28-f4c1-11e7-8e3b-7b25e410c53f.gif)

Syncthing Version: v0.14.43-rc.1+9-g1c880340-makepkg, Linux (64 bit)
OS Version: ArchLinux, latest
Browser Version: FF 57.0.4 (64-bit)
