### ISSUE TITLE
Fd leak when temp file cannot be truncated

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4593]
If the truncate call fails after we've opened a temp file we will return with an error, leaving the temp file fd open.

**Comment by imsodin** [comment]
Don't we do that for all kind of errors in the shared puller state? That state then gets sent to the finisherChan and thus the fd is closed in `finalClose`.

**Comment by calmh** [comment]
Nope, because in this specific case we error before we store the fd on the puller state, thus there is nothing to close later.
