### ISSUE TITLE
Feature request ACL

### ISSUE THREAD

**Issue by Recown** [syncthing/syncthing#4595]
Dear developers! This great and spectacular application not compatible with ACL right scheme on unix. It will be very helpfull to add some kind of compatibility.

**Comment by AudriusButkevicius** [comment]
There have no representation on other filesystems so I don't think it will ever happen.

**Comment by Recown** [comment]
Thanks for the fast answer, but i found a great option like Ignore File Rights.
The problem was, that syncthing tried to apply chmod for the hiden .tmp files after downloading. I use Windows ACL on FreeBSD, thats why all chmod attempts get Permission denied.
When i activated Ignore File Rights - problem has go away! Thanks, application already has what i wanted :)
P.S. Delete this thread please, it's useless in issue tracker.

**Comment by AudriusButkevicius** [comment]
We already have an issue on syncthing ownership which I guess acls fall under, so I am closing this.
