### ISSUE TITLE
Add support for portable disk as sync device

### ISSUE THREAD

**Issue by lweberk** [syncthing/syncthing#4596]
Hi,

it would be lovely if syncthing could support an external storage device as synchronization target/device. The use case can be described as an offline backup drive that gets plugged in upon sitting down at a workstation and unplugged once done working on it. Currently I'm using unison for the disk syncing part every time I leave the workstation and syncthing for sync over network. Fundamentally both cases are the same, with the difference that the disk comes and goes at any given node of the sync network. So any networked device can suddenly become the provisioner of the external storage drive.

Any ideas on the possibility of adding such a feature?

Best regards,
lwk

**Comment by AudriusButkevicius** [comment]
This was asked for before, and was deemed out of scope. There are other tools that do this, unison, csync et all, that can be triggered by when usb device gets plugged in.

**Comment by AudriusButkevicius** [comment]
You can also work around this by running two syncthing instances.

**Comment by calmh** [comment]
Easiest way to support this would be to colocate the index database with the folder, I think. Which I've actually considered since I'm sort of also carrying around a synced folder on an USB SSD, but I'm also not sure it's worth the work.

**Comment by AudriusButkevicius** [comment]
It's perhaps worth the work, yet who cares enough about this to implement it. Plus the UI train wreck, wanting to do one way sync, etc, etc. It's a can of worms I'd rather not open given there are other tools that do the job

**Comment by lweberk** [comment]
Agree on the point of "being worth the work".

As for the UI part, an external storage device is essentially the same as a remote/networked one. The difference is that it is not coupled to the network like a device in syncthing parlance, but conceptually closer to a "folder".

**Comment by calmh** [comment]
Yeah. The only relevant difference from any other folder (IMHO) is that it might validly move from one Syncthing installation to another and should preferably retain its index data. Folders on network drives already work perfectly fine. (And index on network drive probably doesn't, in many cases, due to how the database works).
