### ISSUE TITLE
Add hooks to dump and restore some binary files

### ISSUE THREAD

**Issue by baby-gnu** [syncthing/syncthing#4597]
Hello,

I would like to properly synchronise my home directory which requires doing a dump/restore for some binary databases.

For example I want to dump and restore the dconf database since `~/.config/dconf/user` can not be manipulated directly while I'm connected:

To configure it, I need to:

1. define a `Folder` for `~/.config/dconf/`
2. define an _extractor_ command to execute when a change is detected
3. define a directory to synchronise when the command exit successfully
4. define an _injector_ command to execute when I receive a synchronisation of that directory

This way

* when I change a Gnome setting locally syncthing:
  1. detect a change on `~/.config/dconf/user`
  2. call the _extractor_ command `dconf dump '/'` to handle the data extraction
  3. synchronise the directory containing the extracted data
  4. store the new timestamp for `~/.config/dconf/user`
* when I need to update my local Gnome settings:
  1. synchronise the directory containing the extracted data
  2. call the _injector_ command `dconf load '/'`
  3. store the new timestamp

Regards.

### Version Information

Syncthing Version: v0.14.37-ds1
OS Version: Debian Sid
Browser Version: Firefox 57

**Comment by AudriusButkevicius** [comment]
Events API notifies you as files get synced, build whatever you want.

**Comment by calmh** [comment]
Apart from that, hooks are not the right tool here in my mind. You want a hook to create a dump that syncthing would then sync. But syncthing reacts to changes that it detects on the filesystem, so there is a chicken and egg problem.

I suggest a cron job to create the dump and another one to pick up the changes when the dump has been updated.
