### ISSUE TITLE
Device stuck at 99%

### ISSUE THREAD

**Issue by Cephel** [syncthing/syncthing#4599]
I have a device pairing that is mutually stuck at 99%. All involved folders are reported as "up to date". No useful log information is being displayed in the console window (it looks like everything is working as intended). The GUI yet reports this:
![image](https://user-images.githubusercontent.com/6716857/33978694-4719c19a-e0a1-11e7-9ecb-aebac25bb52a.png)

The issue is mirrored on the Laptop, where the Device stuck at 99% appears to be the Desktop PC instead. The byte amount at the end is identical.

The only shared folder between those two devices is a folder called "Videos", screenshots for it below:
![image](https://i.imgur.com/L668unO.png)
![image](https://i.imgur.com/MKSUyPw.png)

One note, not sure if it's related, the "latest change" field is displaying very outdated information about a file that was deleted weeks ago.

### Version Information

Syncthing Version: v0.14.41
OS Version: Windows 10
Browser Version: Not applicable

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.

**Comment by calmh** [comment]
I think this is a valid bug report. This is not supposed to happen with the new sending-ignored-files stuff, and especially not in both directions. The 128B indicates this is a delete both sides consider missing.

**Comment by AudriusButkevicius** [comment]
This can just be some file actually failing to be deleted...

**Comment by Cephel** [comment]
@calmh By outdated I mean the "last changed file" is not actually the last file that was changed. In fact, even the "recent changes" list disagrees with the field. I'm wondering though if that's related at all. The changes in the folder pair _are_ being synced, just today I synced some files, the program works correctly, apart from that annoying incomplete statement and it being stuck at 99%.

I do not have ignore patterns on either side in any folder, unless Syncthing sets up something by default.

**Comment by AudriusButkevicius** [comment]
Last change means last remote change, not last local change, which might confuse you.

**Comment by Cephel** [comment]
Oh that explains that, I guess this part was false positive then.

**Comment by calmh** [comment]
Closing anyway as without reproducer this will not be actionable... If we can reproduce this just let me know and we'll reopen and hopefully fix.
