### ISSUE TITLE
Unfinished downloads get detected as changes and propagated as conflicting versions

### ISSUE THREAD

**Issue by petko10** [syncthing/syncthing#4600]
I have had some files be replaced with reduced versions of themselves while the full versions were renamed as conflicting files. More specifically I moved some files around on computer1 and computer2 started syncing them. The space on computer2 was not enough though (in this particular instance because it kept versions of all moved files) and the syncing stopped (which at first I did not know about). I have a computer3 syncing the same folder and I'm not sure if that affected the situation. The next thing I knew was that there were a lot of conflicting files (I made a little script to detect them) on computer1. Stupidly the first time this happened to me I deleted all the conflicting files assuming they were the corrupted ones, and I have a music library to mend from kept versions and backups but that's my bad. So, in these cases the conflicting files were the not-corrupted ones. There might've been restarts on comuputer2 and computer3 after the space on computer2 was used up and the sync stopped, I'm sorry I can't account for those since I realized for the problem when I restarted computer1 and my checker script executed.
 I suppose the expected behavior is to have ST mark unfinished downloads properly and to not index them as changes, though I'm not entirely sure that's the problem.

### Version Information

Syncthing Version: v0.14.40-1
OS Version: Manjaro (stable)

**Comment by calmh** [comment]
I'm initially skeptical towards this, as Syncthing keeps the downloaded file under a temporary name and only replaces the file once it's completely downloaded and passes the hash check. In other words, this should not happen and I can't see how it would. If you can reproduce it, that would be useful.

**Comment by petko10** [comment]
Thanks for the fast response. I really just made an assumption for what happened. Since the downloaded files get renamed in the process - yes , it's unlikely that's the reason. I'll try to find a way to reproduce it. What's sure is that I've had ST replace files with corrupted (reduced) versions and rename the full versions as sync-conflicts. It may have something to do with the three way sync. I didn't find similar issues, so if anyone knows what I should look out for it would be appreciated.

**Comment by calmh** [comment]
I can't see what would cause this, and without a reproducer I don't think we can progress. I'm more than happy to debug this backwards and forwards if it can be reproduced though; just let us know and we'll reopen.
