### ISSUE TITLE
Upload and Download speeds stuck at 0 B/s

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing#4606]
Syncthing is currently stuck synchronizing my files with a 0 B/s upload and download speed between a NAS connected to my PC and my Android phone. Scanning also tends to get stuck at 0%. Both devices are online and functional.
See attached logs.
[Logs.zip](https://github.com/syncthing/syncthing/files/1571267/Logs.zip)

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.

**Comment by jebeld17** [comment]
Hey, this started happening again, but I did some digging around and I believe it has to do with the way ST Folders on NAS devices are scanned. If I have 2+ (rather large) ST Folders on a NAS being scanned at a time, even if I have other folders which are smaller and local that need to be synced, the "scan" process holds everything else up. If I "pause" one of the (rather large) NAS ST Folders, the other processes begin to resume and I'll see some (little, but still measurable) synchronization happen to the rest of my Syncthing. If I "pause" both NAS ST Folders holding everything up, ST continues as normal. If and/or when I "continue" or 'unpause' my NAS-connected ST Folders, SyncThing again begins to slow down to a screeching halt.

**Comment by calmh** [comment]
It sounds like your disk I/O is slow. It also sounds like you should discuss this on the forum if you want to shoot ideas, like Audrius already noted above.
