### ISSUE TITLE
Enhancement: treat directory as a single file, updated atomically, like Mac OS packages

### ISSUE THREAD

**Issue by rrnewton** [syncthing/syncthing#4608]
There are discussions all over the internet about putting `.git` folders in Syncthing/Dropbox/etc. Unfortunately, none of the ones I've read really get at what I think is the semantic issue, which has to do with directories that should be treated **atomically**.  This is a broader issue applicable in many contexts *other* than `.git` directories.

Synchronization softwares almost all pick file granularity to serve the indivisible atoms of the system.  That is, Syncthing reports conflicts to the user in files, not conflicts in blocks, bytes etc.  There are good reasons for the atoms to not be *smaller* than a file, but I don't see why an atom can't be *bigger*.  IMHO it would be great to mark a directory `foo` as atomic (via a similar mechanism to specifying ignores), which would mean:

 * normal, non-conflicted updates to `foo` propagate as usual, and thus setting atomic makes no observable difference; BUT,
 * changes are applied "all or nothing", so conflicting changes create a `.sync-conflict-foo-..` directory, not a bunch of little conflict files buried inside it.

Bringing it back to the `.git` use case -- because there are internal invariants that the git directory satisfies, it is much easier for me the user to deal with a `.sync-conflict-.git..` folder than to deal with a corrupted repository with a mess of opaque conflicted object files and indexes.

Other example applications of such a feature include:

 * directories that represent suites of related settings.  For example, my KDE configuration contains lots of little config files, updated automatically.
 * directories that really represent a single logical files, such as Keynote presentations.
 * Mac OS package files in general (those things you right click to "Show Package Contents").

Furthermore, I think that a solution to this problem would be of modest complexity and would certainly be more straightforward than a baroque system designed to whack the `.git` problem specifically.

**Comment by calmh** [comment]
This requires building a temporary copy of the entire directory when syncing, and gets rather tricky and inefficient when there are multiple simultaneous modifications. I'll think about it for a while but my gut reaction is "ugh no".

**Comment by DrSchnagels** [comment]
Maybe a little help would be  a per directory/folder database reset and full rescan of this single particular directory?

**Comment by AudriusButkevicius** [comment]
So I say no, because this is an absurdly racy can of worms, which would require pretty much rewriting how syncthing works and potentially changing what the protocol looks like.

**Comment by calmh** [comment]
Yeah. Try again next year. :)
