### ISSUE TITLE
v0.14.41 breaks compatibility with OS X 10.7.5

### ISSUE THREAD

**Issue by m-a-t** [syncthing/syncthing#4610]
Background: The auto-update function updated syncthing v0.14.40 to v0.14.41 on my Mac OS X 10.7.5. Effect: Since syncthing v0.14.41 doesn't run on Mac OS X 10.7.5, syncthing silently failed to boot and I wonder why my files aren't synced anymore. Very bad user experience.

Please:
- Above all: Please favor compatibility over fancy function in new frameworks. If possible, make fancy function optional for newer OS, but let the core be available for a wide range of OS. 
- Clearly state OS compatibility changes in the changelog
- Do not automatically update if the updated version is known to not work on the system
- Clearly state OS compatibility on the download page

**Comment by m-a-t** [comment]
Ups, sorry for the funny formatting. I can't edit the issue...

**Comment by AudriusButkevicius** [comment]
This version of os x is no longer supported by Go, not us, you can probably still build it yourself with an older version.

**Comment by AudriusButkevicius** [comment]
Yet other arguments are fair.

**Comment by calmh** [comment]
@m-a-t I assume this is the 32 bit version you're running?

The reason for the breakage is that we require linking to the system libraries for filesystem notifications, and that's apparently different enough that it doesn't work with <10.8, which is what Go supports.

With the statically linked binary it seem like 10.6+ works. This is not guaranteed in any way though - it's officially unsupported by Apple, the Go team, and us.

Nonetheless we could perhaps drop FS notifications from the 32 bit build and keep that as a minimally functional compatibility thing.

**Comment by lkwg82** [comment]
I suggest a clear hint and leave as it is. Agree?

**Comment by calmh** [comment]
This is what it is.
