### ISSUE TITLE
Update vendored x/sys/unix for dragonfly

### ISSUE THREAD

**Issue by markuspf** [syncthing/syncthing#4615]
### Version Information

Syncthing Version: v0.14.42
OS Version: DragonFly BSD 

Building syncthing on DragonFly is currently broken, because you ship an outdated `syscall_dragonfly.go` in `vendor/golang.org/x/unix`, see also here https://github.com/golang/sys/commit/9f30dcbe5be197894515a338a9bda9253567ea8f

Would it be possible to cherry-pick that change (if you have reasons to keep that vendor stuff around), or update it?

**Comment by AudriusButkevicius** [comment]
Feel free to make a pull request.

**Comment by markuspf** [comment]
Do do which thing?

**Comment by AudriusButkevicius** [comment]
Update the vendor dependencies I guess

**Comment by AudriusButkevicius** [comment]
We use gvt tool for that.
