### ISSUE TITLE
Send only folder out of sync due to ignored items

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4616]
Something is buggy here. Two machines, A and B. A is receive only and has ignore patterns:

<img width="317" alt="screen shot 2017-12-27 at 21 55 00" src="https://user-images.githubusercontent.com/125426/34393164-c69539f4-eb50-11e7-9961-6458cd486c91.png">

B is newly set up and has no ignore patterns. I browse a few files on B, creating .DS_Store files. Now, on A:

<img width="577" alt="screen shot 2017-12-27 at 21 55 47" src="https://user-images.githubusercontent.com/125426/34393167-c9776db8-eb50-11e7-9f1e-4d3ce240596e.png">

<img width="1053" alt="screen shot 2017-12-27 at 21 55 54" src="https://user-images.githubusercontent.com/125426/34393169-cbcf28f8-eb50-11e7-8917-64330f889acc.png">

Hitting "override changes" deletes the ignored .DS_Store files...

v0.14.42, gut feeling says #4460 is to blame somehow.

**Comment by AudriusButkevicius** [comment]
the fact it deletes the files sounds bad.

**Comment by calmh** [comment]
Yeah it seem the ignore patterns do not apply in this case

**Comment by imsodin** [comment]
Yes #4460 is to blame for the out of sync stuff: As index updates for invalid files are now sent, but not pulled by send-only folders, they can show up as needed. This could never happen before, that's probably why override does not check ignore patterns. I will fix this.

**Comment by imsodin** [comment]
A solution is at https://github.com/imsodin/syncthing/tree/ignRO
It introduces another minor problem (when ignores are removed and file is not present (i.e. not scanned), it wont picked up as out of sync for SO folders). I am not at a computer the next two days, so I will look at it after that.

**Comment by calmh** [comment]
@imsodin did you make any headway on this?

**Comment by imsodin** [comment]
@calmh I now have a fix for this. It builds on top of #4584 and is rather big in itself and certainly will need "a bit" of discussion. If I just push to that PR there will be reviews of two separate concerns happening in one PR, that seems like a bad idea. So I propose to just wait until that PR gets finalized. If you need convincing, this is the diff: https://github.com/imsodin/syncthing/compare/scanDirDel...imsodin:scanDirDel-ign :P

**Comment by calmh** [comment]
mkay
