### ISSUE TITLE
Syncthing update not allowed due to permission issues with files in /usr/ directory.

### ISSUE THREAD

**Issue by CaptainKhan** [syncthing/syncthing#4623]
Syncthing Files are stored in root: 
~/usr/bin
~/usr/share/ (syncdings fork)

When updating through the browser it cant uodate due to permission errors, so with root priviliges i have to manually change each syncthing file to allow read/write 777 and then the uodate through syncthing browser GUI (little error in top bar) works. Would there be another way to install Syncthing? using the native sailfish user folder ~home/nemo/.local/share instead, or something like it.

Syncthing: v0.14.42, Linux (ARM) "Dysprosium Dragonfly"
OS Version: mobile OS, Sailfish 2.1.3.7 amrv7hl
Browser Version: https://github.com/sailfishos/sailfish-browser/blob/b5ac97072d7af6f9880f4f0eee7341b1af1d0024/README.md

**Comment by calmh** [comment]
Yes, there are other ways. Please use the forum for support.
