### ISSUE TITLE
In-GUI restoration should be possible from trashcan versioner

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4631]
Currently (#4602) it's not because it doesn't follow the filename tagging scheme. I propose that,

- GetFolderVersions, when seeing a file without a tag, uses the filename as is and the modtime as the time

- RestoreFolderVersions, when being asked to restore a file with a given tag and not finding it, checks to see if there is a file without the tag (and only that file?). If so, use it and don't care what the tag says. (Avoids trying to match modtimes with varying precision.)

The modtimes in the trashcan versioner are the time of archiving, so already make sense as is. We just need to pick them up and allow restoration of the files. There will never be more than one version of a file, but the date selection can still make sense to restore any files changed yesterday and yesterday only, for example.

**Comment by AudriusButkevicius** [comment]
Why can't we just tag files in the trashcan versioner and get on with our lives?
