### ISSUE TITLE
Syncthing attempts to remove .stversions directory with trashcan versioning

### ISSUE THREAD

**Issue by mateusz-gozdek-sociomantic** [syncthing/syncthing#4638]
In my setup, syncthing user has read-only privileges to data directory, as it's holding a master copy of data and distributes it to other instances.`.stfolder` and `.stversions` directories are created manually, not by syncthing. I think because of d6130164c1b0f5196a8f0da29d51e529246000a5, syncthing now throws an error, because it's attempting to remove `.stversions` as well, when using `trashcan` versioning.

In my opinion, it should leave top level directory in this scenario.
I haven't tested other versioning modes.

### Version Information

Syncthing Version: 0.14.42
OS Version: Ubuntu 16.04

**Comment by AudriusButkevicius** [comment]
There is no point to have an empty stversions directory.

**Comment by calmh** [comment]
If a read only / send only setup there is no need for versioning because no changes happen. Disable it.

**Comment by mateusz-gozdek-sociomantic** [comment]
>In a read only / send only setup there is no need for versioning because no changes happen. Disable it.

That sounds reasonable. But maybe there should be some kind of warning then, that versioning is enabled on sendonly folder, as I missed it, when I was setting up syncthing, as it is not effective.

**Comment by AudriusButkevicius** [comment]
We could force disable versioning in config cleanup on save I guess.

**Comment by calmh** [comment]
That would be wrong as it's reasonable to for example temporarily toggle a folder to send only to avoid issues in some cases, and you want to retain other settings in that case. I think the only case where this matters is the OP one - the folder is read only on disk, it's set to send only, there is an .stversions directory for whatever reason, and versioning is incorrectly enabled. This is rare enough that I don't think this is an issue in practice.
