### ISSUE TITLE
Free space requirement should be set to something other than 1% by default

### ISSUE THREAD

**Issue by cjrobe** [syncthing/syncthing#4640]
I have a 40 GB SSD for my boot drive and when I sync to that, it requires 400 MB of free space. Sync to my 3 TB internal drive on that same computer and it requires 30 GB.

While I discovered this instantly due to the fact my 3 TB hard drive only has 20GB of free space on it at the moment, discovering this default 1% free space requirement when that computer is remote would be less fun.

I think the free space requirement should be a lot lower by default as I think most users would rather have their files reliably sync in more circumstances. Really, I'd say 1 GB or 1% - whichever is smaller.

Also, I think the error message should specify it can be changed in the settings with a link. Just for ease of use.

Thanks for the great software, Resilio Sync just keeps getting worse and worse and I'm happy to be free from them.

**Comment by AudriusButkevicius** [comment]
Whichever value we go for, there will be someone for who the value will not work, as there will be RPI's where 1GB is 50% of their available storage.

This is adjustable, so I think we leave it as it is.

**Comment by cjrobe** [comment]
> Whichever value we go for, there will be someone for who the value will not work
That's why I was suggesting a multifacted approach. Quote me:

> Really, I'd say 1 GB or 1% - **whichever is smaller.**

While plenty of people are using syncthing on ultra small devices, there are also plenty of people using it on larger hard drives. This kind of function would take care of both.

And without the multi-faceted approach, having one setting across hard drives is troublesome. Like in my original example with the 40 GB SSD boot and the 3 TB storage drive. True it's an extreme example - a 120 GB boot drive and a 2 TB storage drive might be more common. In either case, there's no percentage that would satisfy both drives in a reasonable way.

I've used plenty of sync software and I've never had to configure one in this way. It is nitpicky but I feel anything that increases reliability in a sync software is a good thing.
