### ISSUE TITLE
enhancement idea - shutdown and close

### ISSUE THREAD

**Issue by Diapolo** [syncthing/syncthing#4643]
I'm missing an entry to say shutdown and close in the Synchting actions menu. It saves me a click and should be rather easy to implement?

Thanks for working on such a great program and keep it up!

Dia

**Comment by AudriusButkevicius** [comment]
That's yet another button cluttering the already complicated UI. Pressing a button to close the tab is not rocket science. This would also make no sense in UI wrappers that don't have tabs and potentially require them to ship a custom build of syncthing just to remove the confusing button.

**Comment by calmh** [comment]
I don't think closing the window is allowed from many browsers either. So, no, sorry.

**Comment by Diapolo** [comment]
@calmh Would it be possible to add some sort of destructor in the webpage, so that closing the tab is closing a running Syncthing :)?

**Comment by AudriusButkevicius** [comment]
It's a continuous sync tool, if you want one off sync, use rsync.

**Comment by Diapolo** [comment]
I just use it when I need it... and I don't intend to switch ;). You didn't even try to answer my question, right?

**Comment by AudriusButkevicius** [comment]
I can tell you now, this won't happen.

As for your question, you can detect unload events, but these happen and not happen in various conditions. Browser crash would remain undetected, accidentially navigating away or pressing back will be detected and cannot be distinguished between a tab close etc.
