### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by acidicX** [syncthing/syncthing#4652]
This is a bug report.

## What happened

Started ST, panic appears. ST then restarts. 
Mostly in between initial folder scanning, or shortly after.

Note: this happens on two machines I have, both running arch x64. One Intel, one AMD; so it seems not to be hardware-related.

One of the many panic logs (redacted):
[panic-20180106-135013_desktop.log](https://github.com/syncthing/syncthing/files/1608785/panic-20180106-135013_desktop.log)

## What I expected

No crashes ;-)

## Connected devices
I tried with several client versions (0.14.40, 0.14.41, 0.14.42) on the other devices I connected to - nothing made a difference. My arch clients with .42 just keep panicking.

### Version Information

Syncthing Version: v0.14.42
OS Version: Arch Linux x64, completely up2date
Browser Version: n. a.

**Comment by calmh** [comment]
This is #4605, fixed in 0.14.43 (and the RC that is out)

**Comment by acidicX** [comment]
Thanks. That GitHub issue search is really useless...

**Comment by calmh** [comment]
Yep. No worries.
