### ISSUE TITLE
Upgrade system shows an error on RCs in some cases

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4654]
```
jb@unu:~ $ syncthing 
[monitor] 22:43:40 INFO: Starting syncthing
[SYNO4] 22:43:40 INFO: syncthing v0.14.43-rc.1+8-gdb03562d "Dysprosium Dragonfly" (go1.9.2 darwin-amd64) jb@unu.kastelo.net 2018-01-05 18:11:09 UTC
...
[SYNO4] 22:43:42 INFO: Automatic upgrade is always enabled for candidate releases.
...
[SYNO4] 22:43:43 INFO: Automatic upgrade: couldn't find a release to download
```

That last error shouldn't happen.

![screen shot 2018-01-07 at 22 46 00](https://user-images.githubusercontent.com/125426/34654475-a3bfa810-f3fc-11e7-9115-d44204236909.png)

That 500 error shouldn't happen either.

There is at the time of writing no newer version, which is what the upgrade check should return.

**Comment by AudriusButkevicius** [comment]
Uhh, the rc is borked forever then?

**Comment by calmh** [comment]
The problem is when you are on an RC release but configured to not upgrade to RCs. The latest version fetcher then filters out RC:s (which is the latest release) and releases that are older than what you're running (which is everything else), finds nothing, and returns an error.

What *should* happen is that the latest version fetcher should not care whether the version returned is older than we are already running, just that it's the latest that matches our current criteria. Whether it's an *upgrade* or not is checked in a later stage anyway.
