### ISSUE TITLE
GUI notif not available as string for localization

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#4655]
0.14.43-rc1

 2018-01-08 14:10:07: Request from Bécassine for file 201712 30-31 New year/20171231_203801-....jpg in unshared folder "aaaaa-zzzzz" 

\+ folderLabelName should be great

**Comment by AudriusButkevicius** [comment]
These come from Go, and Go code is not localized.

**Comment by AudriusButkevicius** [comment]
I am not sure if we have localize go ticket. I guess this could be it.

**Comment by bugith** [comment]
Happy new year Audrius, 
That is not a real problem : notif should last long as user what is needed. Thanks for your jab man

**Comment by imsodin** [comment]
This is about translatable console messages: #4062
