### ISSUE TITLE
Spurious "é" in GUI

### ISSUE THREAD

**Issue by Lenglemetz** [syncthing/syncthing#4663]
in the last stable version, I have on the bottom left a strange "é"

he is present on all my instances syncthing

![selection_141](https://user-images.githubusercontent.com/4600528/34773562-7012f5f0-f60c-11e7-82df-8f8011af856e.png)

**Comment by calmh** [comment]
Reported several times, already fixed in the code, will be in the next release. Leaving open for visibility.
