### ISSUE TITLE
incorrect error message on the android interface

### ISSUE THREAD

**Issue by ArnaudCZ** [syncthing/syncthing#4667]
Hello,

 - what happened,
all shared folders on the internal storage of my Android phone were showing error 'no compatible file manager found', and were not thinking

 - what you expected to happen instead, and
the error message should have been '.stfolder missing'
This error message was displayed in the web gui but not in the mobile gui, which was confusing

 - any steps to reproduce the problem.
remove the .stfolder from a shared folder on the internal storage

I'd like to point the reason why it happened: 
Unberknown to me, Ccleaner for Android was erasing empty folders as part of its cleaning process. 
The .stfolders were removed and the above error message shown.

### Version Information

Syncthing Version: v0.14.42
OS Version: Android 5.0.2 

Thank you (love the product)

**Comment by AudriusButkevicius** [comment]
This is the wrong repository, please reopen the issue [https://github.com/syncthing/syncthing-android](here)
