### ISSUE TITLE
Panic: fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by breadcat** [syncthing/syncthing#4676]
I have 3x computers synced using syncthing:
Windows 7 32bit - work, installed manually
Windows 10 64bit - home, installed via just-install
Void Linux 64bit - server, run via docker linuxserver/syncthing

On startup, work computer produces the attached panic log. This panic happens every start I start syncthing and I felt reporting the issue was better than re-installing the application in the hopes it would resolve but I'm willing to try.

Yesterday I added a number of sqlite databases (baikal, selfoss, etc) from the 'server' install, but my Windows 10 install gives me no issues.

Attached a redacted panic log.

### Version Information

Syncthing Version: v0.14.44-rc.1
OS Version: Windows 7 32bit

[panic-20180117-091638.log](https://github.com/syncthing/syncthing/files/1638379/panic-20180117-091638.log)

**Comment by calmh** [comment]
Thanks. I'm not clear on the root cause, but I see from the panic trace that this is related to a new feature added in the latest RC, which we should fix.

```
Panic at 2018-01-17T09:16:38Z
fatal error: unexpected signal during runtime execution
[signal 0xc0000005 code=0x1 addr=0x3b0000 pc=0x452e91]

runtime stack:
runtime.throw(0xa4e151, 0x2a)
	c:/go-386/src/runtime/panic.go:605 +0x7c
runtime.sigpanic()
	c:/go-386/src/runtime/signal_windows.go:155 +0x15e
runtime.asmstdcall(0x0, 0x0, 0x0, 0x1211849c, 0x760aeb, 0x1210b810, 0xffffffff, 0x1210b810, 0x8ec2f9, 0x0, ...)
	c:/go-386/src/runtime/sys_windows_386.s:25 +0x21

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x452e70, 0x120e0688, 0x12118480)
	c:/go-386/src/runtime/cgocall.go:132 +0xd5 fp=0x12118468 sp=0x1211844c pc=0x402795
syscall.Syscall(0x75f1f5f2, 0xffffffff, 0x4000, 0x0, 0x0, 0x0, 0x1211849c, 0x760aeb)
	c:/go-386/src/runtime/syscall_windows.go:163 +0x4f fp=0x1211847c sp=0x12118468 pc=0x44378f
github.com/syncthing/syncthing/lib/osutil.SetLowPriority(0x0, 0x0)
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/lib/osutil/lowprio_windows.go:41 +0x95 fp=0x121184ac sp=0x1211847c pc=0x74d275
main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x120cc340, 0x35, 0x0, ...)
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:919 +0x1799 fp=0x12119e34 sp=0x121184ac pc=0x8ec2f9
main.main()
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:440 +0x2b7 fp=0x12119fc4 sp=0x12119e34 pc=0x8e88c7
runtime.main()
	c:/go-386/src/runtime/proc.go:195 +0x201 fp=0x12119ff0 sp=0x12119fc4 pc=0x42b001
runtime.goexit()
	c:/go-386/src/runtime/asm_386.s:1635 +0x1 fp=0x12119ff4 sp=0x12119ff0 pc=0x452481
```

**Comment by calmh** [comment]
Try the just released -rc.2, by manual download or possibly `syncthing -upgrade` from the command line.

**Comment by breadcat** [comment]
Upgrading to -rc.2 has resolved this issue.

Thank you.
