### ISSUE TITLE
Ignore pattern beginning with "#" does not match subpaths

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#4680]
See: https://forum.syncthing.net/t/ignore-patterns-that-start-with/11173

E.g. `#snapshots` does not match `#snapshots/foo`.

**Comment by imsodin** [comment]
While fixing this I get a test failure for the following patthern, which is supposed to result in an error during parsing:

```"!#include makesnosense```

My new implementation only checks for lines starting with `#include`, in that sense the above is a correct pattern that unignores the literal string `#include makesnosense`. The current test only passes due to the "side-effect" that `"!#include makesnosense/**` is parsed and the file at `makesnosense/**` fails to be opened. I see three options:
1. Treat `#include` no different than any other string when not at the beginning (i.e. `"!#include makesnosense` is allowed).
2. Don't allow `#include` anywhere in the pattern except at the beginning.
3. Allow `#include` in the pattern except when it is prefixed by our special patterns `(?d)`/`!`/... (i.e. `"!#include makesnosense` is an error, but `this#includeIsAllowed`).

I favor 1, what do you think?

**Comment by calmh** [comment]
I agree with option 1
