### ISSUE TITLE
"file busy" upon synchronisation

### ISSUE THREAD

**Issue by agharbeia** [syncthing/syncthing#4683]
A bash script that has just been received causes the following error when run:
```/usr/bin/bash: bad interpreter: Text file busy```

I researched the cause and what I found was in the context of NFS and attribute the issue to the file not having been closed by a process, but I imagine it could be a similar case here.

I overcame this by overwriting the file with another with the same name and content.

### Version Information

Syncthing Version: v0.14.43, Linux (64 bit) on both ends

**Comment by AudriusButkevicius** [comment]
How do you know its syncthing that has that file open?

**Comment by calmh** [comment]
Lack of info
