### ISSUE TITLE
basicfs_watch_tests are flaky

### ISSUE THREAD

**Issue by aviau** [syncthing/syncthing#4687]
Hello!

I am getting failing builds on mips64el for 0.14.43.

```
--- FAIL: TestWatchIgnore (2.50s)
	basicfs_watch_test.go:231: Timed out before receiving all expected events
=== RUN   TestWatchRename
--- FAIL: TestWatchRename (2.50s)
	basicfs_watch_test.go:231: Timed out before receiving all expected events
=== RUN   TestWatchOutside
--- PASS: TestWatchOutside (0.00s)
=== RUN   TestWatchSubpath
--- PASS: TestWatchSubpath (0.00s)
=== RUN   TestWatchOverflow
--- FAIL: TestWatchOverflow (2.50s)
	basicfs_watch_test.go:231: Timed out before receiving all expected events
```

Any idea what might cause this? Are they time-based tests?

Maybe they should be a little bit more forgiving?

Debian builds syncthing and runs tests on all kind of architectures, and our machines sometimes have heavy load.

[Full log](https://buildd.debian.org/status/fetch.php?pkg=syncthing&arch=mips64el&ver=0.14.43%2Bds1-1&stamp=1516323710&raw=0) (link may die, sorry)

**Comment by aviau** [comment]
I have queued a build with a five second delay.

```
--- a/lib/fs/basicfs_watch_test.go
+++ b/lib/fs/basicfs_watch_test.go
@@ -135,7 +135,7 @@

    backendChan <- fakeEventInfo(filepath.Join(abs, "file"))

-   timeout := time.NewTimer(2 * time.Second)
+   timeout := time.NewTimer(5 * time.Second)
    select {
    case <-timeout.C:
        t.Errorf("Timed out before receiving an event")
```

I will report back.

**Comment by calmh** [comment]
Yeah we see the same, these tests are flaky. Increasing the timeout is a bandaid.

**Comment by aviau** [comment]
5 seconds was not enough.

30 seconds was enough either.

I ended up disabling the tests.

**Comment by aviau** [comment]
I am still getting this issue on mips64el. Could this be architecture-specific?

**Comment by calmh** [comment]
Possibly; however we're unable to investigate without the hardware in question. I'm going to go ahead and close as there's no chance this will be solved and we have to my knowledge no actual mips64el users. If it's debuggable and fixable in the environment in which it fails a PR is welcome.

**Comment by aviau** [comment]
If you are interested, I could give you shell access to a mips64el machine, Debian has machines for this purpose.
