### ISSUE TITLE
Rearranging files doesn't fully adapt to number of file copiers

### ISSUE THREAD

**Issue by lblblb** [syncthing/syncthing#4691]
When syncthing downloads files, there are blue arrows allowing to place certain files to the top of the queue. By default, syncthing downloads 2 files at once, hence any file manually moved up will take the third position. Now, I changed the number of "copiers" to 1 in the advanced settings:
![2018-01-20 10_32_44-start](https://user-images.githubusercontent.com/12690798/35182068-1391f99c-fdce-11e7-99a5-c53c2f7e3fa0.png)

And expected to now be able to move files up in the queue to the second position. Instead, files moved up with the arrow still only get to third position. Please make this behaviour flexible to the number of copiers for the current sync folder. Note that the blue arrows seem to follow the number of copiers, as third place has an arrow as well.

![2018-01-20 10_31_57-start](https://user-images.githubusercontent.com/12690798/35182087-65c0a4e8-fdce-11e7-8a8b-e8a6dcc09239.png)

### Version Information

Syncthing Version: v0.14.43
OS Version: Windows 10

**Comment by AudriusButkevicius** [comment]
This is an implementation ion detail, the second file is already off the queue, blocked on being passed to the worker routine.
