### ISSUE TITLE
[Feature request] Archive mode for file versioning

### ISSUE THREAD

**Issue by LoveIsGrief** [syncthing/syncthing#4695]
I made the mistake of assuming Syncthing would archive stuff by default, since my phone was setup as read-only and my other machines we supposed to keep backups should my phone die.  
Well, I deleted stuff on my phone and they were deleted from my "backups". [MRW](https://media.tenor.com/images/64c2d7497cc81f343af29b8e21457105/tenor.gif)

So, I think it would be great if there were an archive mode, since I don't want my backups to be "trash cans".

**What exactly**

This mode would follow movements of files on the source, but when the file is deleted on the source, it would simply stay put in the archive; possibly marking the file as remotely deleted (although, that might be unnecessary).

P.S I might sound salty, but it's my fault for just assuming and not reading the documentation. 🤷‍

**Comment by imsodin** [comment]
https://docs.syncthing.net/users/versioning.html ?

**Comment by LoveIsGrief** [comment]
@imsodin 


>This mode would follow movements of files on the source, but **when the file is deleted on the source, it would simply stay put in the archive**

This is what I seek

> This versioning strategy emulates the common “trash can” approach. When a file is deleted or replaced due to a change on a remote device, it is a **moved to the trash can in the .stversions folder.**

Not what I seek

> With “Simple File Versioning” files are **moved to the `.stversions` folder** (inside your shared folder) when replaced or deleted on a remote device.

Not what I seek either

> With “Staggered File Versioning” files are also **moved to a different folder when replaced or deleted** on a remote device (just like “Simple File Versioning”)

Not that either

> # External File Versioning

> This versioning method delegates the decision on what to do to an external command (program or script). Just prior to a file being replaced, the command will be run.

That might work a little, but there is information missing on what power the script has and if more information is provided than just the file path and name. It would be nice to know which operation is being done and what were to happen if the script returned a non-zero code.

**Comment by imsodin** [comment]
I must admit I didn't read to closely, I just triggered on versioning. You might be after https://docs.syncthing.net/advanced/folder-ignoredelete.html

**Comment by LoveIsGrief** [comment]
Indeed, that's what I'm looking for. It's somewhat hidden, so I'll rename the feature request.

**Comment by AudriusButkevicius** [comment]
I am closing this. There is an advanced ignoreDeletes option, versioning, etc.

**Comment by LoveIsGrief** [comment]
Should I create a new request to move it out of the advanced settings? I doesn't seem like a very advanced setting to me and versioning is the first place I naturally looked.

**Comment by AudriusButkevicius** [comment]
The option is there for those who read the docs. It might not seem advanced to you, but the way it's implemented has other implications on out of sync state, hence advanced.

**Comment by AudriusButkevicius** [comment]
If @calmh or @imsodin feels otherwise we can reopen
