### ISSUE TITLE
Lots of "out of sync" files with "Mod. device" unknown

### ISSUE THREAD

**Issue by rkfg** [syncthing/syncthing#4700]
I'm having a lot of out of sync items, the device hasn't been in use for several months. They're not being synced despite some files being identical on the available devices. There's no "Override" button in this situation, it just sits there at 61.9% forever. I checked the out of sync list and the actual files that are on the devices. Some of them are identical, some missing (were deleted on the newer devices).

Tried: restarting, rescanning, pausing/resuming. What to do now? Deleting the database is not an option, it would take forever to manually clear the duplicates and unneeded files from the devices (many files were moved/renamed/deleted since the device has been online the last time).

### Version Information

Syncthing Version: v0.14.43
OS Version: Ubuntu 14.04 / Debian stable (server)

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.

**Comment by rkfg** [comment]
It looks like a bug because this shouldn't happen, no? It's hard to discern support requests from bugs that are related to the main program function, synchronizing files. I have several devices online but the state is not resolved nor there are any error messages or ways to force the state. I don't have any ignored files or permission issues. This is how it looks:
![2018-01-25_14-58-45](https://user-images.githubusercontent.com/184066/35387329-4d9b7ef4-01e0-11e8-9ca6-35b9d1e76585.png)

Of course, I searched the issues and found nothing like this.

**Comment by AudriusButkevicius** [comment]
So I am not going to reply here in any meaningful way as this should be handled on the forum until proven to be a bug. Any reply on the thread causes every watcher of the git repo to be notified for no reason.
