### ISSUE TITLE
Should clean out generated testdata in lib/model/testdata

### ISSUE THREAD

**Issue by aviau** [syncthing/syncthing#4706]
Hello!

Could syncthing clean syncthing/​lib/​model/​testdata after tests?

This makes the syncthing package unreproductible in Debian.

I could work around it by deleting it myself, but it would be best if it was deleted automatically by the tests as I won't have to maintain a list of things to clean after tests are run.

for example, it leaves the following folder:
 - lib/​model/​testdata/​iUeiKzWR/

It is not really possible for me to predict the name of these folders, too.

**Comment by imsodin** [comment]
I believe this was fixed in #4639 which will be in the upcoming 0.14.44 release.

**Comment by aviau** [comment]
Okay, I will report back and close this bug when it is released
