### ISSUE TITLE
High CPU usage by child process of a Syncthing service

### ISSUE THREAD

**Issue by michalbielejewski** [syncthing/syncthing#4709]
### What happened

Syncthing service child process is causing high CPU usage:
```
syncthi+ 28429  0.0  0.7  46212 29728 ?        Ssl  Jan25   2:06 /usr/bin/syncthing -no-browser -no-restart -logflags=0
user1     2591 61.0  0.3  21392 12404 ?        Ssl  11:37   0:00  \_ /usr/bin/syncthing -no-browser -no-restart -logflags=0

syncthi+ 28429  0.0  0.7  46212 29728 ?        Ssl  Jan25   2:06 /usr/bin/syncthing -no-browser -no-restart -logflags=0
user1     2709 46.0  0.3  19920 12408 ?        Ssl  11:37   0:00  \_ /usr/bin/syncthing -no-browser -no-restart -logflags=0
```
### What you expected to happen instead
I'd expect normal CPU usage like this:
```
syncthi+  4069  3.0  0.9  42788 36240 ?        Ssl  11:42   0:02 /usr/bin/syncthing -no-browser -no-restart -logflags=0
```
Also, Syncthing should be run by user `syncthing_user` - like the parent process

### Additional information:
- Restarting the Syncthing service usually resolves the issue.
- Child processes have a short lifetime (as seen above in the PID column)
- 

### Version Information

Syncthing Version: v0.14.43, Linux (64 bit) 
OS Version: Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-112-generic x86_64)
GUI Screenshot:
![chrome_2018-01-27_11-46-14](https://user-images.githubusercontent.com/11682584/35471433-7858208a-035b-11e8-9cd8-e50e050ad279.png)

### Configuration info:
- Syncthing is running as a service (using default service template):
```
[Unit]
Description=Syncthing - Open Source Continuous File Synchronization for %I
Documentation=man:syncthing(1)
After=network.target
Wants=syncthing-inotify@.service

[Service]
User=%i
ExecStart=/usr/bin/syncthing -no-browser -no-restart -logflags=0
Restart=on-failure
SuccessExitStatus=3 4
RestartForceExitStatus=3 4

[Install]
WantedBy=multi-user.target
```
```
● syncthing@syncthing_user.service - Syncthing - Open Source Continuous File Synchronization for syncthing_user
   Loaded: loaded (/etc/systemd/system/syncthing@.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2018-01-27 11:42:33 CET; 35min ago
     Docs: man:syncthing(1)
 Main PID: 4069 (syncthing)
   CGroup: /system.slice/system-syncthing.slice/syncthing@syncthing_user.service
           └─4069 /usr/bin/syncthing -no-browser -no-restart -logflags=0
```
If necessary I can provide a process strace and Syncthing logs.

**Comment by calmh** [comment]
I don't know what's going on here, but Syncthing doesn't launch child processes when started with `-no-restart` and has no code to change owner. I'm guessing topmost process is some sort of systemd shenanigan and syncthing itself can't start for some reason. Check the log.

**Comment by michalbielejewski** [comment]
Unfortunately I didn't grab the log before restarting the service (so now they're gone), but next time this situation occurs I'l save the logs and post them.

**Comment by AudriusButkevicius** [comment]
FAQ covers why syncthing uses so much CPU.

**Comment by michalbielejewski** [comment]
@AudriusButkevicius I don't thing that's not the case. When this bug occurs there are:
- no file changes
- device connections/disconnections 

Also in _normal_ conditions Syncthing is using 0.2% CPU:
```
syncthi+  4069  0.2  0.6  44900 23904 ?        Ssl  11:42   0:10 /usr/bin/syncthing -no-browser -no-restart -logflags=0
```

**Comment by calmh** [comment]
Yeah this is something else, I'm guessing "already running" or something in combination with systemd oddness, resulting in restart loop. Anyway, I don't think it's a bug so I'm going to close this. If you can reproduce and think it *is* a bug, feel free to let us know. Otherwise hit up the forum for support.
