### ISSUE TITLE
add "last synced" info

### ISSUE THREAD

**Issue by voxspox** [syncthing/syncthing#4718]
feature request:

I want to suggest the following feature:
Add a "last synced" info to the "shared folder" info box. I want to know how old my local data is. The "last synced" value could be given as an absolute timedate and/or as a timedelta p.ex. "last synced 2 hours 12 minutes ago".

**Comment by AudriusButkevicius** [comment]
There is already last changed

**Comment by voxspox** [comment]
Could you please leave a hint to the guys from syncthing-gtk how to get the "last changed" info. thx.

**Comment by AudriusButkevicius** [comment]
He can look at the web ui code.
