### ISSUE TITLE
Package syncthing-cli as Debian package, if/when it's deemed functional

### ISSUE THREAD

**Issue by leonyu** [syncthing/syncthing#4719]
Is it possible to get the CLI in the apt/debian package? 

I would like to script against syncthing for remote use cases.

**Comment by calmh** [comment]
The CLI isn't currently functional. If/when it becomes functional we could package it.

**Comment by leonyu** [comment]
Seems to work pretty well, at least for read operations. 

![screenshot](https://user-images.githubusercontent.com/304902/35541677-ef2bcd90-0529-11e8-8fe4-92fc1f90e260.png)
