### ISSUE TITLE
Enable synchronising the targets of Linux symbolic links

### ISSUE THREAD

**Issue by agharbeia** [syncthing/syncthing#4725]
Currently, in v0.14.43, Linux (64 bit), symblic links are always synchronised as symbolic links. This works fine on Linux, and has been several issue reports on their non-functionality on Windows destinations, with various resolutions.

However, it would be great to have a share-level option to synchronise the targets of symlinks instead of the symlinks themselves. This is useful in various scenarios and already the case with several popular synchronisation services, a la Dropbox et al, thus somewhat expected behaviour by some users.

### Version Information

Syncthing Version:  v0.14.43, Linux (64 bit)
OS Version: Ubuntu 16.04.

**Comment by imsodin** [comment]
This is not going to happen, see the calmh's last comment on the existing issue about this: https://github.com/syncthing/syncthing/issues/1776#issuecomment-311612569

If you want to get ideas about how to solve your use case, ask about it [on the forum](forum.syncthing.net]).
