### ISSUE TITLE
build embeds hostname

### ISSUE THREAD

**Issue by bmwiedemann** [syncthing/syncthing#4726]
When building the openSUSE syncthing package on different hosts, I get slightly different results because it embeds the hostname of the build machine into the resulting binary:

/usr/bin/syncthing differs in ELF section .rodata
--- /tmp/tmp.8Erco8kwCR/tmp.HucBlaPRVb  2018-01-31 17:48:51.136716125 +0000
+++ /tmp/tmp.8Erco8kwCR/tmp.0v1Y019dN1  2018-01-31 17:48:51.636711254 +0000
@@ -233130,7 +233130,7 @@
  dc5a50 00020000 00000000 00000000 00000000  ................
  dc5a60 00000000 00000000 00000000 00000000  ................
  dc5a70 00000000 00000000 26000000 00000000  ........&.......
- dc5a80 736c6573 31326100 04000000 00000000  sles12a.........
+ dc5a80 736c6573 31326200 04000000 00000000  sles12b.........

### Version Information

Syncthing Version: syncthing-source-v0.14.43
OS Version: openSUSE Tumbleweed

See https://reproducible-builds.org/ for why this matters.

**Comment by AudriusButkevicius** [comment]
It's controlled via BUILD_HOST env var

**Comment by bmwiedemann** [comment]
OK. should then be fixed for openSUSE with https://build.opensuse.org/request/show/571706
