### ISSUE TITLE
Android app constantly pops up "anonymous usage report" message, prompts for restart

### ISSUE THREAD

**Issue by Natanji** [syncthing/syncthing#4730]
Today when I opened Syncthing on my Android, it popped up a message about sending an anonymous usage report - despite me disabling the sending of such reports in the settings. That however is not the problem in itself. The problem is that no matter whether I press "Yes" or "No" in the dialogue, it will *immediately* pop up again. If I click fast enough I can *sometimes* use the UI for a bit before the next one pops up, and tried to just *enable* the anonymous usage reports in the settings. However, when I do that and restart Syncthing afterwards, the setting will be "off" again upon restart.

Also, the first dismissal of the popup message will always open another prompt that asks me to restart Syncthing to enable the changes (in which way sending or not sending such a report would change the settings is beyond me). Upon restart, the same popups happen, making the UI quite unusable really.

### Version Information

Syncthing Version: v0.14.43
Syncthing-Android-Version: 0.10.3
OS Version: Android 8.0

**Comment by AudriusButkevicius** [comment]
Wrong repo, this was addressed in the latest release.
