### ISSUE TITLE
SPDY protocol error causes blocking modal prompt

### ISSUE THREAD

**Issue by deed02392** [syncthing/syncthing#4731]
#  what happened

> Syncthing seems to be experiencing a problem processing your request. Please refresh the page or restart Syncthing if the problem persists.

Chrome console output:
`GET https://hostname/rest/events/disk?limit=25 net::ERR_SPDY_PROTOCOL_ERROR`

The above modal error pops up and prevents me from interacting with the web GUI. This is really annoying as it usually then prevents me from responding to the 'folder found' message which is behind the modal. The problem is a one off connection issue and if I remove the HTML that represents the modal I can still successfully respond to prompts but it's quite a nuisance that it happens at all (we should be able to dismiss this error modal and not be forced to refresh).

 - any steps to reproduce the problem.
Just leave the web console open for some time. Eventually a SPDY error occurs and the blocking prompt appears.

# Solution?

Even if the SPDY protocol error cannot be easily fixed (I suspect it can't) can we at least make the error modal not block the page and require a refresh to easily dismiss?

# Version Information

Syncthing Version: v0.14.43
OS Version: linuxserver/syncthing Docker container
Browser Version: Chrome Version 63.0.3239.132 (but it has happened over many versions)

**Comment by AudriusButkevicius** [comment]
This never happens for me on Chrome. Why does Chrome assume by default that everyone talks SPDY?

**Comment by deed02392** [comment]
At this risk of you not even caring about the usability impact of the error modal design, it is probably related to my use of nginx-proxy in front of Syncthing.

**Comment by AudriusButkevicius** [comment]
Right, but the modal is telling you we are failing to connect, which is genuinely the case, so I am not sure what does this have to do with usability if the UI is unusable due to connection errors?

Clearly, the issue is that SPDY/your proxying breaks long polling endpoints, hence the issue.
I suggest you address the cause, not the symptom.

**Comment by AudriusButkevicius** [comment]
```
proxy_http_version 1.1;
```
in your nginx config should disable SPDY/http2 and other things that we currently do not use.

**Comment by deed02392** [comment]
Yeah see I knew this would happen. 

The reason it affects usability is because even errors for REST API connections that are simply updating minor statistics on the UI, cause the entire interface to require a refresh, which in turn causes you to have to wait again for a new peer to connect and the UI to offer to share a folder with them.

A minor REST API call should not 'crash' the entire UI when it fails. This will be problematic even for people on lossy networks. Again, the blocking modal prompt is an issue in my opinion.

**Comment by AudriusButkevicius** [comment]
Perhaps, but I'd rather have a pull request than an issue in that case.

**Comment by calmh** [comment]
If i remember correctly we only throw up the error dialog on 5xx error codes from the backend, which legitimately means Syncthing is in trouble. If there is a proxy in between injecting error codes that is an issue, but not one the GUI can anticipate.

**Comment by deed02392** [comment]
@AudriusButkevicius Fair enough! Happy to oblige if I know it will not be in vain.

@calmh yes the error is a 5xx code one, but we can still have a button in the critical error modal that lets you dismiss it (we can make it difficult to use if you really want to avoid people dismissing it and still trying to use the UI anyway, but I can't see there being much danger in people doing that).

So if @calmh is on board with a PR I will get around to writing it (although I am also investigating how to fix this in the nginx-proxy container, thanks @AudriusButkevicius for the specific help there).

**Comment by calmh** [comment]
If we want a PR we definitely want an issue to be closed by that PR as well. But this might be a proxy misconfiguration.

We have templates in the docs that handle long polling correctly, have you looked at those?

**Comment by deed02392** [comment]
I suppose the issue if we were to need one to close would be that the 'something went wrong' modal should be dismiss-able. 

However, you were of course right about it being an issue with the proxy. I first set about trying to disable SPDY but the way the container works meant that it is enabled in the `listen` directive which cannot be easily overridden. 

That said, the awesome guys at freenode#nginx helped me determine this SPDY protocol error occurs due to a timeout from the upstream server. You can spot this by looking at the NGINX error log (funnily enough) which warns about a timeout from the upstream server (whereas Chrome itself at chrome://net-internals/#events tells you that the remote server reset the stream). So, unfortunately NGINX does not handle upstream server timeouts well, and this translates to a SPDY error in Chrome.

I have since set `proxy_read_timeout 5m;` which I notice corresponds to your docs (which I did not know about). Great job @calmh.

**Comment by calmh** [comment]
One other thing to keep in mind is that the GUI keeps state and is even driven. Once we get back a 500 from the backend we really don’t know what the status is any more. Closing the dialog just means we show something that is not accurate any more. A full reload is the only sane way out of it imho.
