### ISSUE TITLE
What's that lonely character 'é' doing on the GUI?

### ISSUE THREAD

**Issue by TheVento** [syncthing/syncthing#4736]
In the GUI main-page, like http://127.0.0.1:8384, there is a nasty character 'é' showing up, just before the footer...

View HTML-source shows: (it's right there, after the first '<span class="ng-scope">')

----------------
<ng-include src="'syncthing/transfer/remoteNeededFilesModalView.html'" class="ng-scope"><span class="ng-scope">é</span><div class="modal fade ng-isolate-scope" tabindex="-1" ng-attr-data-backdrop="{{ closeable == 'yes' ? true : 'static' }}" ng-attr-data-keyboard="{{ closeable == 'yes' ? true : false }}" id="remoteNeed" status="info" icon="exchange" heading="Out of Sync Items - " large="yes" closeable="yes" data-backdrop="true" data-keyboard="true">
.......
----------------

Syncthing Version: v0.14.43, Mac OS X (64 bit)
Mac OS X 10.13.3 (17D47)
Apple Safari 11.0.3 (13604.5.6)

**Comment by canton7** [comment]
#4663
