### ISSUE TITLE
Skip index updates to minimize overhead in send only setups

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4739]
There are setups with central devices connected to *lots* of remote clients, typically in a send only fashion. That is, some data is periodically updated on the central server and should be distributed to the clients, but there are never updates in the other direction.

Currently this puts some load on the central device, because for each update accepted by the thousand remote devices it gets a thousand incoming index updates to process and store. These index updates provide no value by themselves other than giving us an opportunity to know the other side progress.

If we had a flag to say that we don't actually care, we could set this in the cluster config and the other side can avoid sending any index updates. Index updates we get anyway we can just drop on the floor. Our database I/O and size gets reduced to almost nothing.

Remote devices would display as unknown in sync status. A possible extension is to instead send progress update messages, letting the other side know your status but they don't have to hit the database for it.

**Comment by AudriusButkevicius** [comment]
Don't we need that for completion info of remote devices?

**Comment by AudriusButkevicius** [comment]
And also to know when to override changes?

**Comment by calmh** [comment]
I mentioned completion above, but yeah overrides would require index data.

**Comment by AudriusButkevicius** [comment]
I think this is a no-go.

**Comment by calmh** [comment]
Never mind this for the time being
