### ISSUE TITLE
Configure changes to keep the connected devices

### ISSUE THREAD

**Issue by xjtdy888** [syncthing/syncthing#4743]
I saw that if the folder configuration changes, all the devices associated with the folder will be disconnected and reconnected, which will cause the file transfer to be temporarily broken. maye we can optimize the logic 

Reconnection is mainly used to exchange folder index information, maybe we can re-exchange but do not disconnect

**Comment by acolomb** [comment]
I think this might be fixed already? We're now sending config messages without tearing down the connection. @imsodin could you confirm please?
