### ISSUE TITLE
Files in directory named .stversions (not at folder root) cannot be synced

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing#4751]
Error message "Peers who had the file went away" popping up on read-write 'target' syncthing device for files within ".stversions" folder.

 - what happened
I have node A (read only master) syncing the folder 1 to node B (read write node).
Folder 1 contains a subfolder 2 synced read-write betweem node A and node C (both read write nodes).
node C <=> node A : Sync okay and idle.
node A => node B : node B shows message "Peers who had the file went away /subfolder/Folder-2/.stversions/..."

 - what you expected to happen instead
node C <=> node A : Sync okay and idle.
node A => node B : Sync finished without errors about .stversions files from subfolder-2.

 - any steps to reproduce the problem.
Create a folder 1. Sync it node A => readonly => node B.
Create a subfolder 2 in folder 1: Sync it node A <=> read-write <=> node C. Turn on file versioner recycle bin 90 days on node A for subfolder 2. Wait until .stversions of subfolder 2 fills up on node A. Turn node B on and wait for it to sync node A's new contents > Error.

- workaround to solve this problem:
add "(?i).stignore" pattern to ignore list on node A.

Remark: I've read the docs and that nested folders are not supported. I don't want to force nested folders to be supported but I think it is a problem with ".stversions" not ignored by hard-coded syncthing defaults. So I'd suggest to fix this danger by hard-ignoring ".stversions" like ".stfolder" and ".stignore".

Syncthing Version: v0.14.44
OS Version: QNAP Linux FW 4.3.x amd64 / Debian 8.8.x Linux amd64
Browser Version: (if applicable, for GUI issues)

**Comment by calmh** [comment]
.stversions at any other point than the folder root should just be a directory like any other. I’m not fully following your reproduction steps to determine if this is the case, or you mean things will fail as soon as a folder is called .stversions?

**Comment by calmh** [comment]
Hm. Probably the request gets incorrectly dropped for referring to an “internal” file name, which it isn’t.

**Comment by calmh** [comment]
I can't reproduce this. Using the test setup in the repo (two device), I create `s1/foo/.stversions/<lots of files>` where `s1` is the folder root for device one. These get synced to `s2/foo/.stversions/...` just fine, where `s2` is the folder root on the other device.

**Comment by Catfriend1** [comment]
Ok, thanks for taking time to investigate this issue. In the meantime, I had a lot of devices showing as "Synced" with mismatching global file count and - just on one side of a sync pair - local file count. I've read about on another issue here and tried -reset-deltas. That did not fully solve the problem, so I decided to clear all index-14.0-db folders on all my nodes one after another and now every device shows "Synced" with the correct file count. I'm hoping for 14.45 to solve this problem. It was looking weird, with all nodes of a folder pair having the same content and .stignore's setup, showing "Synced" and always the same "6 normal files" were not synced (comparing with Total Commander). But thats too much for this issue.
I am going to retry the ".stversions" issue reproduction with a test VM later and report back as my "live   cluster" does no longer have problems with this.

**Comment by calmh** [comment]
Yeah... There were some changes to how we handle ignores in .43 or thereabout that I think might not have played well with the delta indexes and stuff. Your deleting the indexes probably cleared that out.

**Comment by Catfriend1** [comment]
Hmm... strange. @Nutomic just updated the android app to v0.14.45 and I'm seeing this for a folder root on my mobile:
![grafik](https://user-images.githubusercontent.com/16361913/37224583-39ffca2e-23d4-11e8-9ddc-e3be24fc2272.png)
I did not activate the experimental "run as root user" yet (but will soon). The storage is my internal sd card (where android framework allows write access properly). Which logs (of those many) are useful to collect on reproduction of the problem to help fixing it? Before this came up, I saw the other side (linux amd64 running v0.14.45) disconnected unexpectedly. At a first glance, there are no network issues. It worked fine with android app 0.10.4 using syncthing v0.14.43.
Log of linux amd64 node:
2018-03-09 18:57:34 Connection to VHDYK6X-*** at 192.168.1.XX:XXXXX-192.168.1.XX:56560/tcp-server closed: writing message: write tcp4 192.168.1.XX(=mobile phone):XXXXX->192.168.1.XX:56560 (=linux node): write: connection reset by peer
Maybe @Nutomic can assist because this issue is more android specific.

**Comment by calmh** [comment]
That is .stversions at the folder root, which is the versioning directory and cannot be synchronized. Your issue speaks of .stversions *not* at the folder root.

**Comment by Catfriend1** [comment]
Youre right. Something strange is going on. I deleted database, thought it was rebuild already because of the 0.14.45 changelog "on upgrade reindex". Now I got a new hint. I think it is android specific and trying to reproduce it grabbing full syncthing.log. Then I will reopen with a clear description how to reproduce at the syncthing-android issue tracker. What I've discovered until now is, the folder on mobile phone gets scanne twice (database cleared, it scans the folder, file count matches for 10 seconds after reaching 100%... then it triggers a rescan itself seconds later and after that boom... i have twice the files and the folder says idle). For better reproduction, I deleted stversions folder from my sdcard and the problem persisted - so I guess its NOT related to stversions.

**Comment by Catfriend1** [comment]
https://github.com/syncthing/syncthing-android/issues/1032

**Comment by Catfriend1** [comment]
Ok I'll close this because imsodin already works on the issue rhat caused my above screenshot and problem unrelated to this issue.

**Comment by imsodin** [comment]
Ah yeah, that's caused by the same thing (https://github.com/syncthing/syncthing/issues/4799), I didn't realize that at first.
