### ISSUE TITLE
Don't scan when there are no devices to sync with

### ISSUE THREAD

**Issue by jruere** [syncthing/syncthing#4752]
I sync between 3 devices: desktop, laptop & phone. They don't all share the same.

The desktop is normally on, the laptop is occasionally on and the phone syncs only when charging.

This means that the desktop scans unnecessarily a lot of the time since any difference it finds cannot be sync'ed.

I'd like for scanning to be suspended until a device wanting that folder appears (or maybe also when the UI is on). This would make the app lighter since disks are the slowest component of my computers and the sync'ed content changes often.

**Comment by calmh** [comment]
Detecting changes as they happen (roughly) is the key to conflict detection and resolution. We'd have to make sure to do the scan and process the results before accepting the connection (or at least starting any processing on it). It's probably technically possible but I'm not sure it's desirable. Will think on it.

(I wonder how common it is to have devices that are not connected to anyone else at a given moment. Don't think we have data on this.)

**Comment by jruere** [comment]
I suppose that for the PC + phone use case, it would be pretty common since keeping syncthing running constantly on the phone has many disadvantages.

I would consider this an optimization which should not change sync results. If there's a problem I cannot see, please disregard.

**Comment by canton7** [comment]
With filesystem notifications on the way, which will reduce scanning anyway, it might not be worth it.

**Comment by calmh** [comment]
Might also increase scanning significantly, if there are a lot of changes.

**Comment by jruere** [comment]
If filesystem notification is possible for large directory trees, it would be the right solution.

It should not scan more often than configured so it should never be worse.

**Comment by calmh** [comment]
Declining this for the time being
