### ISSUE TITLE
v0.14.45-rc eats files

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4756]
As reported in https://forum.syncthing.net/t/files-deleted-after-update-to-v0-14-45-rc-2/11282

Potentially multiple issues, almost surely related to #4584.

Off the top of my head I can see one issue with directories that have been renamed case-only on case insensitive systems: whereas previously we would see the files just fine, we would now lockstep-walk the database vs the filesystem, potentially note that the directory we expected didn't happen, and mark everything below as deleted. That is, we see `foo/` when walking and conclude that`Foo/**` which is in the database has been deleted. This propagates to some other device where the deletes happen, and it's a self fulfilling prophesy.

**Comment by JonasT** [comment]
Is there a mechanism to automatically revert release candidates on affected machines as well? It might be worth putting one in: I just randomly saw odd messages and thought "huh I might try the older version to fix it", and if I hadn't looked at it, that version would have run forever even though you guys seem to already be aware that it's broken. (and deleted whatever in the long run)

**Comment by calmh** [comment]
The switch we can throw is to release a newer version. I don't think we want a central kill- or downgrade-switch.
