### ISSUE TITLE
Rescan All by signal from Linux console

### ISSUE THREAD

**Issue by alex73** [syncthing/syncthing#4766]
It would be great if syncthing could catch signals in Linux. In this case, user will be able to force rescan from remote console by command like:

killall -SIGHUP syncthing

**Comment by AudriusButkevicius** [comment]
We'll run out of signals for all the things people might want to do. Use the rest API.

**Comment by Ferroin** [comment]
Direct from the API docs:

    curl -X POST http://127.0.0.1:8384/rest/db/scan

Will trigger a full rescan.  You can find more info [here](https://docs.syncthing.net/rest/db-scan-post.html).
