### ISSUE TITLE
Some of Ms office .xls files are in "out of sync" both master and backup systems.

### ISSUE THREAD

**Issue by lfacomputersin** [syncthing/syncthing#4768]
Hi Techies,

I am using syncthing  v0.14.44, Windows (32 bit) . I configured to backup a folder from a master system to backup system. some of Microsoft .xls files (not all the .xls files)  are not synchronised. 
Please provide me solution to solve this issue. 
Thanks for read and think about this issue techie.

### Version Information

Syncthing Version: v0.14.44
OS Version: Windows 7 Pro SP1 2009
Browser Version: (Google Chrome) Version 64.0.3282.167 (Official Build) (64-bit)

**Comment by calmh** [comment]
Please use the forum for support.
