### ISSUE TITLE
Consistency checks on-demand (Rescan /w checksums)

### ISSUE THREAD

**Issue by Jarno-P** [syncthing/syncthing#4771]
It would come handy if Syncthing could rescan checksums too when doing "Rescan" and thus check file consistency. 

An automated version of this feature was discussed (and rejected) in [#1315](https://github.com/syncthing/syncthing/issues/1315), but as a _manual_ option to the GUI's "Rescan" feature it would be useful and the resource consumption would not be an issue. 

Otherwise one needs to use 3rd party tools to run consistency checks to verify the copies Syncthing has created. Syncthing has all the basic components in it already. 

I am fighting with potential bit flips on Win 10 NTFS machine and using Unison now to verify the checksums...

**Comment by calmh** [comment]
Related: #4488

**Comment by Jarno-P** [comment]
You are right. This would require additional logic and UI. One option would be to utilize mtime instead of ignoring it and define bitrot as "different checksum with unchanged mtime". This can be risky on Windows platforms though. More complex approach would be to have Syncthing to review sync results of its peers and provide an UI to resolve the conflicts. The first option should not be unreasonable effort, but it might be an risky approach on operating systems where the mtime cannot be relied on.

**Comment by calmh** [comment]
I think this is a no-go for the same reason as the old linked issue
