### ISSUE TITLE
Logging debugging flags stay after disabling all debug facilities in the web UI

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#4780]
This is something in between a bug and a feature request: When no debug env vars are set, but some facilities are enabled and then disabled in the web UI, the debug logging flags (filename, precise timestamps) persist. Only way to reset it is to restart syncthing. This is a bit annoying e.g. on my homeserver when temporarily testing something and then reverting to "business as usual", as logcheck filters don't work anymore with the different format.

**Comment by AudriusButkevicius** [comment]
I think we should show these always, as I had cases where I just asked people to enable debugging something just to get the line numbers. K8s does this for example.

**Comment by calmh** [comment]
We have flags to do that. For the vast majority of users the line number stuff is just meaningless noise.

I agree with imsodin though - if we set flags when we enable debug facilities we should clear them again when all are unset.
