### ISSUE TITLE
Error message after update of SyncTrayzor

### ISSUE THREAD

**Issue by sergueikp** [syncthing/syncthing#4784]
- what happened:
After update of SyncTrayzor to version 1.1.20
when shutting down windows 7 there is next error message:
"syncthing.exe - erreur d'application
L'application n'a pas réussi à démarrer correctement
(0xc0000142). Cliquez sur OK pour fermer l'application"

 - what you expected to happen instead, and
I expect that it shutts down without error message
 
- any steps to reproduce the problem:
Update SyncTrayzor to version 1.1.20 and shut down the Windows 7. 

### Version Information
Syncthing Version: v0.14.44
OS Version: Windows 7
Browser Version: SyncTrayzor v.1.1.20

Screen shot of the error message is joined.

Best regards.
![error_message](https://user-images.githubusercontent.com/9844780/36939846-7a071442-1f38-11e8-8afa-73e8b0b9c36d.JPG)

**Comment by AudriusButkevicius** [comment]
This is the wrong repository, please reopen the issue in SyncTrayzor's repository

**Comment by canton7** [comment]
This isn't my error either -- Windows is showing that dialog.

**Comment by AudriusButkevicius** [comment]
Yeah, probably you want to reinstall synctrayzor.

**Comment by canton7** [comment]
Looks like it's a dup of https://github.com/canton7/SyncTrayzor/issues/438, which was opened 9 hours ago by the same person. I'll investigate it in there.

**Comment by sergueikp** [comment]
I've got three computers with SyncTrayzor + syncthing, all of them display same error message after the last update.

**Comment by AudriusButkevicius** [comment]
Anyways, I'll lock this, as this is clearly the wrong place to talk about this.
