### ISSUE TITLE
Building Syncthing mac dmg or .app 

### ISSUE THREAD

**Issue by dipenpatel235** [syncthing/syncthing#4787]
i want to generate syncthing app in .dmg or .app related for mac book.
now i am only able to generate binary file so it is not look like installable version.

so how we can make it dmg or .app ?

### Version Information

Syncthing Version: v0.14.45
OS Version: Centos 7 64 bit

**Comment by calmh** [comment]
Please use the forum for Q&A. There is also a relevant contribution: https://github.com/xor-gate/syncthing-macosx

**Comment by dipenpatel235** [comment]
yes but in that issue is we have did change in code for related user interface and using this all os related binary generate .

and as per suggested by you in that special mac developer skill required right ?

Thanks
