### ISSUE TITLE
Add ignoreCreate folder setting

### ISSUE THREAD

**Issue by emersion** [syncthing/syncthing#4790]
Syncthing already has `ignoreDelete`, which is useful when one instance should keep copies of deleted files and many instances should delete files. But Syncthing is missing the opposite flag, useful when one instance should not download files from others, and should only upload. I called it `ignoreCreate`, but it may be a misleading name - it's actually "ignore everything that isn't delete".

**Comment by calmh** [comment]
Not "ignore everything that I don't already have a version of"? (The difference being in the handling of updates, as there is no specific "create" event in the protocol.)

**Comment by emersion** [comment]
Yeah, you're right.

**Comment by Catfriend1** [comment]
Hmm I do not understand properly... An instance that does not download but only upload is a send-only folder type.

**Comment by Ferroin** [comment]
The suggested semantics of ignoring things the local node doesn't have a version of would actually not be the same as not downloading, it would still get updates for files the node already has, it just wouldn't create any new files (which would make sense if the flag was actually named `ignoreCreate`).

**Comment by calmh** [comment]
Thinking more about it, I think this would be unintuitive and/or a conflict magnet. Declining, for the time being.
