### ISSUE TITLE
Upload and Download Rate at 0 B/s

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing#4792]
Syncthing tends to not upload or download much, if not at all, when I have a sync directory on a NAS storage device. 

Upload and Download rates are stuck at 0 B/s on both my server at home (v0.14.45, Windows (64 bit)) and my Android phone.

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
