### ISSUE TITLE
pfuuu

### ISSUE THREAD

**Issue by gurussia** [syncthing/syncthing#4794]
Hi guys.
git clone https://github.com/syncthing/syncthing.git
syncthing is downloaded

after that it is unknown what command to be writed to work for syncthing. So we try to try build.sh and it comment go not found so we install golang and when we try again build.sh it comment exit status 1 and exit status 2 it start do something commenting github.com thub.com/syncthing/syncthing/vendor/github.com/prometheus/client_golang/prometheus/promhttp
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/memdb
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/opt
github.com/syncthing/syncthing/vendor/github.com/golang/snappy
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/table
github.com/syncthing/syncthing/vendor/golang.org/x/net/context
github.com/syncthing/syncthing/cmd/stevents
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb
github.com/syncthing/syncthing/vendor/github.com/chmduquesne/rollinghash
github.com/syncthing/syncthing/vendor/github.com/chmduquesne/rollinghash/adler32
github.com/syncthing/syncthing/vendor/github.com/rcrowley/go-metrics
github.com/syncthing/syncthing/cmd/stdiscosrv
github.com/syncthing/syncthing/vendor/github.com/gobwas/glob/util/runes
github.com/syncthing/syncthing/vendor/github.com/gobwas/glob/util/strings
github.com/syncthing/syncthing/vendor/github.com/gobwas/glob/match
# github.com/syncthing/syncthing/cmd/stdiscosrv
/tmp/syncthing-bedf3e9d/src/github.com/syncthing/syncthing/cmd/stdiscosrv/database.go:248: undefined: sort.Slice
/tmp/syncthing-bedf3e9d/src/github.com/syncthing/syncthing/cmd/stdiscosrv/database.go:251: undefined: sort.Slice
github.com/syncthing/syncthing/vendor/github.com/gobwas/glob/syntax/lexer
github.com/syncthing/syncthing/cmd/stfinddevice
github.com/syncthing/syncthing/vendor/github.com/gobwas/glob/syntax/ast
github.com/syncthing/syncthing/vendor/github.com/gobwas/glob/compiler
github.com/syncthing/syncthing/vendor/github.com/gobwas/glob/syntax
github.com/syncthing/syncthing/vendor/github.com/gobwas/glob
github.com/syncthing/syncthing/lib/ignore
github.com/syncthing/syncthing/lib/scanner
github.com/syncthing/syncthing/cmd/stfileinfo
github.com/syncthing/syncthing/cmd/stgenfiles
github.com/syncthing/syncthing/lib/db
github.com/syncthing/syncthing/vendor/github.com/golang/groupcache/lru
github.com/syncthing/syncthing/vendor/github.com/oschwald/maxminddb-golang
github.com/syncthing/syncthing/vendor/github.com/oschwald/geoip2-golang
github.com/syncthing/syncthing/cmd/strelaypoolsrv/auto
github.com/syncthing/syncthing/lib/relay/protocol
github.com/syncthing/syncthing/cmd/stindex
github.com/syncthing/syncthing/lib/relay/client
github.com/syncthing/syncthing/vendor/golang.org/x/time/rate
github.com/syncthing/syncthing/cmd/strelaypoolsrv
github.com/syncthing/syncthing/lib/nat
github.com/syncthing/syncthing/vendor/github.com/AudriusButkevicius/go-nat-pmp
github.com/syncthing/syncthing/vendor/github.com/jackpal/gateway
github.com/syncthing/syncthing/lib/pmp
github.com/syncthing/syncthing/lib/upnp
github.com/syncthing/syncthing/cmd/strelaysrv/testutil
github.com/syncthing/syncthing/cmd/strelaysrv
github.com/syncthing/syncthing/cmd/stsigtool
github.com/syncthing/syncthing/cmd/stvanity
github.com/syncthing/syncthing/cmd/stwatchfile
github.com/syncthing/syncthing/lib/auto
github.com/syncthing/syncthing/lib/connections
github.com/syncthing/syncthing/lib/stats
github.com/syncthing/syncthing/lib/watchaggregator
github.com/syncthing/syncthing/lib/weakhash
github.com/syncthing/syncthing/vendor/github.com/vitrun/qart/gf256
github.com/syncthing/syncthing/vendor/github.com/vitrun/qart/coding
github.com/syncthing/syncthing/vendor/github.com/vitrun/qart/qr
github.com/syncthing/syncthing/lib/model
github.com/syncthing/syncthing/vendor/golang.org/x/crypto/blowfish
github.com/syncthing/syncthing/vendor/golang.org/x/crypto/bcrypt
github.com/syncthing/syncthing/cmd/syncthing
exit status 2
exit status 1

It is unknown why it again download when we git clone syncthing. DOcumentation http://docs.syncthing.net/ it comment Unable to connect

can’t establish a connection to the server at docs.syncthing.net.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that  is permitted to access the Web.

We don't know what for what is syntching but it is inhuman 1. documentation is unrecheable. 2. there is no humankind how to. 3. build.sh comment error exit 1 and exit 2.   3. why there is no auto installation. So newbie peoples. Only git clone and open browser and install. 4 And more important if you make install make too uninstall. Becouse much INHUMAN women developers only make installation, it install in some other unknown directory and when person want to delete it, it is unknown where it install it. Now we are gonna delete syncthing untill there is no humankind things.

**Comment by AudriusButkevicius** [comment]
So I am just closing this as you don't seem like a nice guy. If you want help, please open a post on the forums without discriminating/demoralizing phrases explaining your problem, rather that your life problems.
