### ISSUE TITLE
WebUI: Device's "Folders" field tooltip should wrap into multiple lines if exceeds certain length

### ISSUE THREAD

**Issue by scienmind** [syncthing/syncthing#4797]
1. Open WebUI
2. Expand info for a remote device that shares a lot of folders 
3. Hover above "folders" field of this device's info
4. Tool-tip appears listing all the folders shared with this device

Actual result: with many shared folders this tool-tip just lists everything in one line of monitor's width (and it's still not enough to list all folders)

Expected result: the tool-tip should be limited in width and break into multi-line if above curtain line length.

The tool-tip is underlined with red:
![image](https://user-images.githubusercontent.com/11633330/37215438-9a4d3b0a-23c0-11e8-9039-beb5f147d3c9.png)

### Version Information

Syncthing Version: v0.14.45
OS Version: Windows 10x64

**Comment by Ferroin** [comment]
Which web browser are you using?  It looks like it's wrapping correctly here in Chrome.

**Comment by scienmind** [comment]
Thanks for the info! 
The screenshot is from the chrome embedded framework that comes with SyncTrayzor
Seems to be working fine in Firefox as well...

Probably SyncTrayzor should update it's embedded browser, I'll reopen the issue there.
