### ISSUE TITLE
Use HTTPS for GUI checkbox not updated correctly

### ISSUE THREAD

**Issue by JEGBergqvist** [syncthing/syncthing#4801]
**Priority:** Low
**Date tested:** 2018-03-10
**OS:** Mac OS X High Sierra (latest update at the date above)
**HW:** MacBook Pro 2017
**Browser:** Safari (latest update at the date above)
**Syncthing version:** brew list syncthing gives /usr/local/Cellar/syncthing/0.14.44/bin/syncthing
**Syncthing nodes:** Windows Server 2016, Synology DS1815+, 2 x Mac OS X Hight Sierra, Windows 10

**Issue:** I had to check the "HTTPS for GUI" checkbox many times before it finally "stuck" (a few reboots involved, as well as "pause all" and "low priority", "limit bandwidth", etc). It seems it was only the GUI that was not updated, https://127.0.0.1:8084 worked as usual the entire time regardless of the state of the checkbox (if this is not relevant, then perhaps I have misunderstood what the HTTPS checkbox affects? - Then please just delete this bug report!)

**Comment by calmh** [comment]
Odd. The checkbox is somewhat vestigial though. The GUI / API always listens on both http and https. The checkbox only enforces https in that when enabled it makes Syncthing redirect from http to https.

**Comment by calmh** [comment]
Cannot reproduce, not sure what the original issue was exactly. Yell if you have a method to reproduce.
