### ISSUE TITLE
Bug and/or feature: Rebuild of index uses unacceptable amount of CPU and disk resources at startup/reconnect

### ISSUE THREAD

**Issue by JEGBergqvist** [syncthing/syncthing#4802]
**# Bug and/or feature: Rebuild of index uses unacceptable amount of CPU and disk resources at startup/reconnect**

**Priority:** Medium
**Date tested:** 2018-03-10
**OS:** Mac OS X High Sierra (latest update at the date above)
**HW:** MacBook Pro 2017
**Browser:** Safari (latest update at the date above)
**Syncthing version:** brew list syncthing gives /usr/local/Cellar/syncthing/0.14.44/bin/syncthing
**Syncthing nodes:** Windows Server 2016, Synology DS1815+, 2 x Mac OS X Hight Sierra, Windows 10
**Number of files:** Approx. 250,000 files in approx 35,000 (sub-level) folders, divided into 3 syncthing (top-level) folders.

**Issue:**
Although quite powerful for a notebook, my 13-inch (with "max everything" in terms of SSD, CPU, RAM, etc) MacBook Pro 2017 get completely bogged down by syncthing re-building the index. Of course, this is a transient state, but it is really annoying when it happens. Ideally, I would expect syncthing to just do its thing without hindering my working. I have selected "low prio" and capped the bandwidth. I found many others on the web having similar problems on Mac OSX with syncthing. The solution proposed generally seems to involve a separate tool called cputhrottle. However, that tool repeatedly terminates when applied to syncthing (at least for me). Would it be possible to include a hard limit on CPU and disk access?

Mac OSX is not perfect when it comes to high loads of CPU and disk. Actually, the disk queue is often a worse problem than CPU bursts. Recently Mac OSX got better in terms of disk handling, but it is still far from perfect. Hence, an app like syncthing must take care not to use the resources too greedily on Mac OSX, or the user is at loss.

**Comment by AudriusButkevicius** [comment]
Syncthing can't really tell the OS to schedule it differently other than what it already does. I am closing this, as I feel this belongs in the forum as there is no clear way to address this., so the potential solutions should be discussed in the forum.

**Comment by JEGBergqvist** [comment]
Just an idea, please let me know if it would be possible:
Could the re-index task be throttled? Maybe it would go a long way if the task could use only every other second (or whatever frequency would suit such a cpu-throttling). In essence, would a checkbox ("Cap CPU usage") controlling an "if(cpu_capping){sleep(x);}" or similar at the right spot in the code would do the trick? Best regards :-)
