### ISSUE TITLE
Add support to sync (single) files

### ISSUE THREAD

**Issue by jonazc** [syncthing/syncthing#4803]
It looks like it is not possible currently to sync files, just directories. I could work with ignore filters of course, but I guess there could be more often than once the need to sync only specific files and not folders.

**Comment by cdpb** [comment]
You could symlink the single file to a new empty directory and sync

**Comment by calmh** [comment]
It's a design desicion to work with folders that we are not going to change. You can however sync a single file in that folder using ignore patterns.

```
!myfile.ext
*
```

**Comment by jonazc** [comment]
You could think about solving this by UI: when someone wants to add a file to sync, inform the user and propose to automatically write an ignore pattern.

**Comment by AudriusButkevicius** [comment]
Or we could not, as that's simply not our target usecase.

**Comment by jonazc** [comment]
Of course you could not. But maybe someone else could like to implement and contribute it to this open source tool. And maybe, there are (new) users with this usecase who would appreciate it.
