### ISSUE TITLE
Panic in FS watcher in FreeBSD 8.3

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4806]
```
panic: function not implemented

goroutine 1 [running]:
github.com/syncthing/syncthing/vendor/github.com/zillode/notify.newWatcher(0xc42001e300, 0x80, 0xc42001e300)
        /tmp/syncthing-e02d0de3/src/github.com/syncthing/syncthing/vendor/github.com/zillode/notify/watcher_trigger.go:109 +0x1e8

github.com/syncthing/syncthing/vendor/github.com/zillode/notify.newTree(0xb5029d, 0x17)
        /tmp/syncthing-e02d0de3/src/github.com/syncthing/syncthing/vendor/github.com/zillode/notify/tree.go:17 +0x4d
```

FreeBSD 8.3 is end of life since years back. Not sure, without investigation, if that is the root cause though.

**Comment by imsodin** [comment]
Either that or Go deprecated it, as  since 1.10 only >=10.3 is supported.  
The error is coming from some `syscall` function: https://github.com/syncthing/syncthing/blob/master/vendor/github.com/Zillode/notify/watcher_kqueue.go#L89

**Comment by calmh** [comment]
Right, make sense. So it's not implemented in either the Go runtime for OldBSD or not implemented in the OS itself.

**Comment by calmh** [comment]
Actually, panicking is not the right response anyhow so the bug remains.

**Comment by calmh** [comment]
https://github.com/rjeczalik/notify/issues/149
