### ISSUE TITLE
request for android version - 14.46rc1

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing#4810]
Hi,

Can we please have a 14.46rc1 containing the current commits since 14.45? Then we could start beta testing a new android syncthing Version earlier before the final release probably comes out of the blue containing untested 14.46. @Nutomic : Whats your opinion on that? Should we start early by pushing a rc release, for example in the middle of the month, to gplay beta channel?

**Comment by calmh** [comment]
Today is indeed 0.14.46-rc.1-day, I'm releasing it currently. The rest is up to the android devs. (I suggest not just pushing out the rc, as that forces usage reporting on everyone.)

**Comment by Catfriend1** [comment]
Thanks for your quick answer. 👍

**Comment by calmh** [comment]
There is now a 0.14.46-rc.1

**Comment by Catfriend1** [comment]
@Calmh: I made a debug build and tested it myself on my phone - the android problems are solved and I can sync again properly. Many thumbs up!
