### ISSUE TITLE
Syncthing 0.14.45 on three sides, Android folder red with "Interrupted system call"...

### ISSUE THREAD

**Issue by LabradorLasse** [syncthing/syncthing#4812]
Two different sync folders that have worked normally up until 14.44 in a three way sync (2 of x64 Linux and one Android 7 respectively) today failed, presumably after Android upgrade to 14.45.
On Android the folder has a red status symbol and the log that pops up on the Android Web GUI states "Interrupted system call".
Same folders syncs fine between two Linux machines. 
I have not tried to revert to 0.14.44, I first wanted to try to provide any info you might need before doing that.
I'd be fine with providing logs or try a test build if you want, just tell me what to do and what you need! ;-)

### Version Information

Syncthing Version: v0.14.45 (on all)
OS Version: Ubuntu 17.10/Arch Linux/Android 7 (the one that stops)

**Comment by imsodin** [comment]
Chances are you are seeing a strange symptom of a known bug in 0.10.5. To say for sure we need to see those logs - the linux side would have lines regarding dropped connections which contain "the prove".

**Comment by LabradorLasse** [comment]
Could that be this line (somewhat redacted):
`INFO: Failed to exchange Hello messages with (Android Device ID) at [ (Arch IPv6 Address) %wlp3s0]:22000-[ (Android IPv6 Address) %wlp3s0]:51788/tcp-server: EOF`
...by any chance?

**Comment by LabradorLasse** [comment]
Well, yeah, but the strange thing is that on the Linux end I find an error like that, but on a folder that (at least appears to) sync correctly:
`2018-03-13 18:23:07 Connection to (Android)  at [ (Linux IPv6) %wlp3s0]:22000-[ (Android IPv6) %wlp3s0]:52896/tcp-server closed: protocol error: index update: "/100ANDRO": filename is invalid`
So it sounds like the same bug. Does the error on the first share make the following share(s) to fail?

**Comment by imsodin** [comment]
It is the same. And yes, it closes the connection, so all folders are affected.
