### ISSUE TITLE
can't create folder inside synced folders

### ISSUE THREAD

**Issue by 2anyone** [syncthing/syncthing#4814]
- what happened: 
sync 'pictures' folder from mobile to ubuntu, add new folder 'gif' to pictures, which lists as out of sync items, and never sync.

 - what you expected to happen instead, 
new folder 'gif' (for example) should be sync within 'pictures' folder.

 - any steps to reproduce the problem.
nothing special, used didn't have any problem, till I update to android version: 0.10.5, still happens in 0.10.6.

### Version Information

Syncthing Version: Syncthing Version 0.10.6  com.nutomic.syncthingandroid
OS Version:  Ubuntu 16.04 and android n

**Comment by Catfriend1** [comment]
Can you please post the logs?

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.

**Comment by 2anyone** [comment]
@Catfriend1 here is the log, sorry to reply you late.

`--------- beginning of main
03-15 15:35:41.629 I/SyncthingNativeCode(32053): [FIVAM] INFO: Puller (folder "pictures" (zkc6j-gx182), file "Gifs/id51384346_635a50efgw1eez0l3965bg208c04p000.gif"): finisher: file modified but not rescanned; will try again later

[.... every file have same log repeatly....]

03-15 15:35:42.020 I/SyncthingNativeCode(32053): [FIVAM] INFO: Puller (folder "pictures" (zkc6j-gx182), file "Gifs/1421147032_278881.gif"): finisher: file modified but not rescanned; will try again later
03-15 15:35:43.047 I/SyncthingNativeCode(32053): [FIVAM] INFO: Folder "pictures" (zkc6j-gx182) isn't making progress. Pausing puller for 1m0s.`

**Comment by 2anyone** [comment]
@Catfriend1 finally I figure out myself with old style:

move 'gif' folder out of synced 'picture', syncthing will sync both side to delete gif, 
clean up the 'tmp' files left in 'gif' folder, and move back in the 'picture'

seems syncthing redo the scanning without problem, and sync both side.

for someone have the same problem, try this.

**Comment by Catfriend1** [comment]
Can you link me to your forum post, please? I'd like to avoid double split posting ...

**Comment by 2anyone** [comment]
@Catfriend1 im not sure if you were talking to me, but what's "link me to your forum post" meant? ha, I am totally newbie in github. :P
