### ISSUE TITLE
Different size of sync files between nodes

### ISSUE THREAD

**Issue by Dekart0** [syncthing/syncthing#4818]
I sync large directory (50Gb) by local network between 2 nodes (Mac OS X Sierra and Mac OS X Hight Sierra) and noticed different sizes on each node (**50.5 Gb vs 49.92 Gb**).

Then I find differents between some files (jpg, png) on each node (for ex.: **631 Кb on main node vs 510 Kb on synced node)**. Hash is identical of both.

What's wrong?

**Syncthing Version**: v0.14.45, macOS (64 bit)
**Syncthing nodes**: Mac OS X Sierra, Mac OS X Hight Sierra (latest update at the date above)

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
