### ISSUE TITLE
Folder's default min-size is overriding global min-size 

### ISSUE THREAD

**Issue by JaCoB1123** [syncthing/syncthing#4820]
Syncthing stops synchonizing with the following message:

```
2018-03-15 17:19:11: Error on folder uiae: insufficient space in basic /files/Synced/uiae/: 0.954750 % < 1 %
```

I've already found the setting in the config and set it to "1 GB" via the UI and after retrying changed it directly in the config File to:

```
<minHomeDiskFree unit="MB">1024</minHomeDiskFree
```

UPDATE:
I just found out this setting exists for each Folder. So it would be nice to have a less "breaking" default on folder level or maybe just not have the default override the system-wide setting? i.e. if I never set a min-space on any Folder use the global setting.

### Version Information

Syncthing Version: v0.14.46-rc.1
OS Version: Ubuntu 16.04

**Comment by JaCoB1123** [comment]
Just to make it clear: My problem is already fixed. It might bite other users though.

**Comment by calmh** [comment]
The two are different. The "global" setting is for where the index and configuration lives; the per folder settings are for the folders.

**Comment by JaCoB1123** [comment]
Ok, then the default might need a bit of rethinking? Maybe 1 GB makes more sense than 1%. In my case, 1% is about 800GB.
In a similar issue for https://github.com/minio/minio/issues/2780 minio moved from 5% to 1GB.

**Comment by AudriusButkevicius** [comment]
1GB is a lot on a rasberry PI. There is no silver bullet, someone will suffer from this.

**Comment by calmh** [comment]
The default is just a default. If it doesn't suit you, that's why it's configurable.

**Comment by Paxa** [comment]
Btw how to configure it? I can't find it on https://docs.minio.io/docs/minio-server-configuration-guide.html

**Comment by AudriusButkevicius** [comment]
What does minio have to do with this?

**Comment by Paxa** [comment]
sorry
