### ISSUE TITLE
Filter the global change log UI

### ISSUE THREAD

**Issue by xgdgsc** [syncthing/syncthing#4823]
### Version Information

Syncthing Version: v0.14.45
OS Version: Windows 10
Browser Version: chrome  65.0.3325.162

# Request
I noticed previous discussions on showing recent changes for folder or global like https://github.com/syncthing/syncthing/issues/2924  https://github.com/syncthing/syncthing/pull/3694 . But the current global change log displays a lot of `ignored`  which isn' t useful for me to see what actually happend. How to filter this?

And recent change for a folder would also be very useful, just need to extend the current `last changed file` to a clickable expandable list of files.

**Comment by Catfriend1** [comment]
> forum.syncthing.net please ?

**Comment by AudriusButkevicius** [comment]
What do you mean by ignored?

Last changed works differently, so extending that means a rewrite, you can use the global change list for that.

**Comment by xgdgsc** [comment]
I mean sometimes the full list of global recent changed files would include `ignored` files. I want to filter these out and only see the `modified` `deleted` `added` files.

**Comment by AudriusButkevicius** [comment]
This should not happen, as you sure the files are ignored?

**Comment by xgdgsc** [comment]
They are ignored correctly.

**Comment by imsodin** [comment]
Yes, it does happen - I introduced that when changing the way ignores work, that was probably a mistake: https://github.com/syncthing/syncthing/blob/master/lib/model/model.go#L1798  
I mean it can be helpful to see that a change was ignored, but this happens whenever the global version of an ignored file changes. With lots of ignored files, it drowns other stuff out. I think we shouldn't log a disk change event in case of ignored files (but eventually implement an option to display ignored files, not sure whether there is a ticket for that already).

**Comment by AudriusButkevicius** [comment]
Yeah, we should just skip invalid updates, as they don't signify anything meaningful in terms of local state changes.

**Comment by calmh** [comment]
I think this was addressed by #4837 (but that PR tagged the wrong issue)
