### ISSUE TITLE
'Latest Change' does not show the latest change

### ISSUE THREAD

**Issue by mvglasow** [syncthing/syncthing#4825]
### To reproduce:

I’ve shared a folder and synced it with another device. The folder held three files at one point, of which I have since deleted two, and later updated the remaining file.

To reproduce, presumably:
* Share a folder from one device with a second device
* On the second device, point it to a folder which already exists and has some content
* Sync
* Stop Syncthing or disconnect
* Delete some of the files
* Start up Syncthing again and sync
* Stop Syncthing again (or disconnect)
* Modify one of the existing files on the first device
* Start up Syncthing again and sync, then check the folder status on the first device

### Expected behavior:

I would expect 'Latest Change' for that folder to show the change to the one file still left in that folder.

### Actual behavior:

'Latest Change' shows the deletion of one of the two other files with its timestamp (which was four days ago). Last Scan has today’s date. When I check on the other device, the changes are there; it’s just the display that does not reflect it.

### Version Information

PC:
Syncthing Version: v0.14.45, Linux (64 bit)
OS Version: Ubuntu MATE 16.04
Browser Version: Firefox 59.0.1

Smartphone:
Syncthing Version: v0.10.4 (com.nutomic.syncthingandroid), obtained from F-Droid
OS Version: Android 7.1.2 (LineageOS 14.1)
Browser Version: n/a

### Additional Information

The file was modified on the PC, which is also where I noticed the GUI behavior described, and then synced to the phone.

**Comment by wweich** [comment]
The "Latest Change" on the folder only shows incoming changes. That's by design.

**Comment by mvglasow** [comment]
Good to know, but it wouldn’t hurt to point that out somewhere (e.g. by renaming the entry to 'Latest Incoming Change'). Otherwise I guess I’m not the last person expecting to see changes detected during the local scan here.
