### ISSUE TITLE
Global change log does indicate folder

### ISSUE THREAD

**Issue by dinosore** [syncthing/syncthing#4828]
[I have posted about this in the forum. ](https://forum.syncthing.net/t/gui-recent-changes/11373), but don't seem to have explained well enough.

I have reproduced the bug, and it does seem to be solid.

1. I noticed a misspelled filename while editing (o instead of p).
2. save as.
3. rm the old one.
4. rescan as delete not immediately picked up by syncthing.

Everything seemed to work fine, except for the recent changes list (so bug is minor).

Please note **trash can versioning** on device 3.

**Device 1 my laptop**
Debian stretch amd64
Syncthing v0.14.46-rc.1
Simple file versioning
```
Device | Action | Type | Path | Time
monocerus | deleted | file | recaotchalib.php.new | 2018-03-20 14:17:28
monocerus | added | file | recaptchalib.php.new | 2018-03-20 14:16:10
```
**Device 2 local server**
Raspbian stretch
Syncthing v0.14.45
Simple file versioning
```
Device | Action | Type | Path | Time
monocerus | deleted | file | recaotchalib.php.new | 2018-03-20 14:17:39
monocerus | added | file | recaptchalib.php.new | 2018-03-20 14:16:28
```

**Device 3 remote server**
Raspbian stretch
Syncthing v0.14.45
Trash Can File Versioning
```
Device | Action | Type | Path | Time
pie | added | file | recaotchalib.php.new | 2018-03-20 14:18:29
T23BC6D | deleted | file | recaotchalib.php.new | 2018-03-20 14:17:42
T23BC6D | added | file | recaptchalib.php.new | 2018-03-20 14:16:29
```

**Comment by calmh** [comment]
So is the file resurrected on `pie` or what?

**Comment by dinosore** [comment]
Files on pie are fine

```
root@pie:/mnt/stik1/st/phhg# ls reca*
recaptchalib.php  recaptchalib.php.new
root@pie:/mnt/stik1/st/phhg# cd .st
.stfolder/   .stversions/ 
root@pie:/mnt/stik1/st/phhg# cd .stversions/
root@pie:/mnt/stik1/st/phhg/.stversions# ls reca*
recaotchalib.php.new
```
Just a guess, but it might have something to do with the "deleted" version having the same name as the  main one.

The only thin wrong I've seen is the extra line in the recent changes list on pie (remote server).

**Comment by AudriusButkevicius** [comment]
What type of device is pie, rasberry? Which of the devices is pie? 2?

**Comment by dinosore** [comment]
```
dev1     laptop             pc                     moncerus            T23BC6D
dev2     local server      raspberry pi zero w     pi                  3YBZSGE
dev3     remote server     raspberry pi zero w     pie                 B3IQ5IL
```
So pie is dev3.

dev1 <--> dev2 <--> dev3

**Comment by AudriusButkevicius** [comment]
I suspect it's some sort of time skew on a device with questionable capabilities.

I think the third device (device 1) is sort of irrelevant here, are you able to repro with 2 devices?

**Comment by dinosore** [comment]
I agree that dev 1 is irrelevant.  It was, however, a real-world example and not contrived.

As to time skew, I don't agree.  OK, the pis don't have an rtc   After a reboot, the time is slow until synchronised with a time server when it adjusts by about half a minute.  The cron entry to start the syncthing service starts with sleep 60.

Internet-connected pis keep good time except immediately after boot when they start at the time saved at shutdown.

OK, I'll give it a go.

**Comment by dinosore** [comment]
Preparing to do a test as requested, I found out that the problem doesn't just arise for deletes, it happens with modifies too.  I stripped trailing whitespace.

dev1
monocerus | modified | file | recaptchalib.php.new | 2018-03-20 21:01:25

dev2
monocerus | modified | file | recaptchalib.php.new | 2018-03-20 21:01:38

dev3
pie | added | file | recaptchalib.php.new | 2018-03-20 21:01:42
T23BC6D | modified | file | recaptchalib.php.new | 2018-03-20 21:01:40

root@pie:/mnt/stik1/st/phhg# ls -l recapt*
-rw-r--r-- 1 david david 9910 Feb 10  2014 recaptchalib.php
-rw-r--r-- 1 david david 9869 Mar 20 21:01 recaptchalib.php.new
root@pie:/mnt/stik1/st/phhg# ls -l .stversions/recapt*
-rw-r--r-- 1 david david 10133 Mar 20 21:01 .stversions/recaptchalib.php.new
root@pie:/mnt/stik1/st/phhg#

**Comment by dinosore** [comment]
Test with just dev2 (pi) and dev3 (pie)

```
david@pi:/mnt/u/st/phhg$ date;ls -l testfile
Tue 20 Mar 23:13:56 GMT 2018
ls: cannot access 'testfile': No such file or directory
david@pi:/mnt/u/st/phhg$ date;touch testfile
Tue 20 Mar 23:14:34 GMT 2018
david@pi:/mnt/u/st/phhg$ date;ls -l testfile
Tue 20 Mar 23:14:39 GMT 2018
-rw-r--r-- 1 david david 0 Mar 20 23:14 testfile
david@pi:/mnt/u/st/phhg$ date;nano testfile
Tue 20 Mar 23:15:40 GMT 2018
david@pi:/mnt/u/st/phhg$ date;nano testfile
Tue 20 Mar 23:18:28 GMT 2018
david@pi:/mnt/u/st/phhg$ date;nano testfile
Tue 20 Mar 23:20:01 GMT 2018
david@pi:/mnt/u/st/phhg$ date;rm testfile
Tue 20 Mar 23:22:14 GMT 2018
david@pi:/mnt/u/st/phhg$ 
```

pi recent changes

```
Device | Action | Type | Path | Time
-- | -- | -- | -- | --
pi | deleted | file | testfile | 2018-03-20 23:22:33
pi | modified | file | testfile | 2018-03-20 23:20:38
pi | modified | file | testfile | 2018-03-20 23:19:07
pi | added | file | testfile | 2018-03-20 23:16:45
```

pie recent changes

```
Device | Action | Type | Path | Time
-- | -- | -- | -- | --
pie | modified | file | testfile | 2018-03-20 23:23:27
pi | deleted | file | testfile | 2018-03-20 23:22:35
pie | modified | file | testfile | 2018-03-20 23:21:24
pi | modified | file | testfile | 2018-03-20 23:20:46
pie | added | file | testfile | 2018-03-20 23:19:26
pi | modified | file | testfile | 2018-03-20 23:19:09
pi | added | file | testfile | 2018-03-20 23:16:50
```

```
david@pie:/mnt/stik1/st/phhg$ ls -l testfile
ls: cannot access 'testfile': No such file or directory
david@pie:/mnt/stik1/st/phhg$ ls -l .stversions/testfile
-rw-r--r-- 1 david david 21 Mar 20 23:22 .stversions/testfile
david@pie:/mnt/stik1/st/phhg$ cat .stversions/testfile
line 1
line 2
line 3
david@pie:/mnt/stik1/st/phhg$
```
Note that the actions by pie on its recent changes list should not be there, but there is no other ill effect.

**Comment by AudriusButkevicius** [comment]
Thanks, I'll try to look into it tomorrow.

**Comment by dinosore** [comment]
I've tried it the other way round.

**pie**
```
david@pie:/mnt/stik1/st/ddocs$ ls -la
total 20
drwxr-sr-x  4 david david 4096 Jan  3 13:45 .
drwxrwsr-x 15 david david 4096 Nov 13 10:05 ..
-rw-r--r--  1 david david  749 Jan 21  2016 .ignore
drwxr-sr-x  2 david david 4096 Sep 21 04:15 .stfolder
drwxr-sr-x  3 david david 4096 Jan  4 04:00 .stversions
david@pie:/mnt/stik1/st/ddocs$ ls -l .stversions/
total 0
david@pie:/mnt/stik1/st/ddocs$ ls /mnt/data/stvers/ddocs
current HHGmembership.docx  My PaperPort Documents      Scans
gparted_details2.htm        Presentation throwaway.ppt
david@pie:/mnt/stik1/st/ddocs$ date; nano testback
Wed 21 Mar 12:05:00 GMT 2018
david@pie:/mnt/stik1/st/ddocs$ cat testback
line 1back

david@pie:/mnt/stik1/st/ddocs$ date; nano testback
Wed 21 Mar 12:08:44 GMT 2018
david@pie:/mnt/stik1/st/ddocs$ cat testback
line 1back
line 2back

david@pie:/mnt/stik1/st/ddocs$ date;rm testback
Wed 21 Mar 12:10:44 GMT 2018
david@pie:/mnt/stik1/st/ddocs$ ls -l testback
ls: cannot access 'testback': No such file or directory
david@pie:/mnt/stik1/st/ddocs$ ls -l .stversions/testback
ls: cannot access '.stversions/testback': No such file or directory
```

**pi**
```
david@pi:~$ cd /mnt/u/st/ddocs
david@pi:/mnt/u/st/ddocs$ ls -l testback*
-rw-r--r-- 1 david david 23 Mar 21 12:08 testback
david@pi:/mnt/u/st/ddocs$ ls -l testback*
ls: cannot access 'testback*': No such file or directory
david@pi:/mnt/u/st/ddocs$ ls -l .stversions/testback*
-rw-r--r-- 1 david david 12 Mar 21 12:05 .stversions/testback~20180321-120538
-rw-r--r-- 1 david david 23 Mar 21 12:08 .stversions/testback~20180321-120859
david@pi:/mnt/u/st/ddocs$ 
```

**pie**
```
Device | Action | Type | Path | Time
-- | -- | -- | -- | --
pie | deleted | file | testback | 2018-03-21 12:16:55
pie | modified | file | testback | 2018-03-21 12:09:43
pie | added | file | testback | 2018-03-21 12:05:52
```

**pi**
```
Device | Action | Type | Path | Time
-- | -- | -- | -- | --
pi | added | file | testback~20180321-120859 | 2018-03-21 12:18:00
pie | deleted | file | testback | 2018-03-21 12:16:57
pi | added | file | testback~20180321-120538 | 2018-03-21 12:10:59
pie | modified | file | testback | 2018-03-21 12:09:59
pie | added | file | testback | 2018-03-21 12:06:08
```
The intention was to show all was ok the other way round, but it isn't
.
There's a rescan on pi between 12:10:59 and 12:16:57.

And we have two versions created.

So, there's a problem this way round too.
xxxxxxxxxxxx

**Comment by AudriusButkevicius** [comment]
So I can't reproduce it between my windows and linux machines on master.

**Comment by AudriusButkevicius** [comment]
Right, I know what this is.

You have your .stversions directory added (and potentially unshared) for the purpose of block reuse from .stversions folder.

Global change log is a bit shit as it doesn't tell you which folder the change happened in, just the filename, and you are getting confused as to where the change is coming from.

**Comment by dinosore** [comment]
> You have your .stversions directory added as and unshared folder, probably for the purpose of block reuse from .stversions.

Spot on.

There are 13 main folders and for each of these the .stversions directory is an unshared folder for the reason you give.
