### ISSUE TITLE
Auto merge text files instead of creating conflict file

### ISSUE THREAD

**Issue by felixwiemuth** [syncthing/syncthing#4831]
It would be convenient that if a text file is modified by two devices at different positions (such that a diff tool can identify the changes as non-conflicting) a sync would run a merge tool to combine the versions into a single new version. This would make the routine merging one has to do when editing files on multiple devices superfluous or, in other words, adds the flexibility that one can edit a file at different positions without causing a sync conflict. A log should keep track of auto merges. Having versioning enabled could keep both original versions.

To avoid unwanted auto-merges, one could select MIME types, file extensions and/or paths for which this should apply.

There is some discussion about merging in #1746 but it focusses on external tools to handle conflicts in general but does not really consider the special case where a conflict can be solved automatically.
Looking at git's ability to merge two versions of a repository it seems that quite a lot can be done automatically. It also won't merge files categorized as "binary". I guess one can simply reuse the diff/merge tools and/or procedures git uses.

**Comment by calmh** [comment]
Sorry, this is not going to happen. To do merges, use a specific merge tool.

**Comment by felixwiemuth** [comment]
Could you explain the reasons? I don't really see the problem for it as an optional feature. The alternative is of course running the mergetool as a sort of hook but surely an integrated solution would be more user-friendly. If it's lack of developing resources, s.o. else might want to implement it.

**Comment by AudriusButkevicius** [comment]
Syncthing syncs files, regardless if its text, binary or whatever. We are not going to specialize into caring about file types.
