### ISSUE TITLE
sha256 could use faster implementation where available

### ISSUE THREAD

**Issue by fingon** [syncthing/syncthing#4832]
[github.com/minio/sha256-simd](github.com/minio/sha256-simd) has SIMD instruction using sha256 that is much faster than Go 1.10 builtin:

mstenber@poro ~/go/go-tfhfs/fs>go test -bench '^BenchmarkShaBase256'
goos: darwin
goarch: amd64
pkg: github.com/fingon/go-tfhfs/fs
BenchmarkShaBase256/builtin-50-12         	 3000000	       392 ns/op 127.44 MB/s
BenchmarkShaBase256/builtin-1000-12       	  200000	      6117 ns/op 163.47 MB/s
BenchmarkShaBase256/builtin-20000-12      	   10000	    108678 ns/op 184.03 MB/s

BenchmarkShaBase256/simd-50-12            	 5000000	       295 ns/op 169.17 MB/s
BenchmarkShaBase256/simd-1000-12          	  300000	      3858 ns/op 259.15 MB/s
BenchmarkShaBase256/simd-20000-12         	   20000	     74677 ns/op 267.82 MB/s

builtin = crypto/sha256
simd = the above link.

applicable in all testcases (50 bytes to 20 kb) on my machine.

**Comment by calmh** [comment]
We've been using the minio implementation for like two years.
