### ISSUE TITLE
[FR][0.14.44] Master should always override changes on clients

### ISSUE THREAD

**Issue by dembach** [syncthing/syncthing#4834]
Request:
Master Folder is read-only
clients are read-write and syncing in between them (thats good, because its faster than top-down)
One client is adding a file and also syncs it to the other rw-nodes, though the master (ro) node does not have this file.

i manually have to override changes on master node (ro) to get the files deleted on the client nodes (rw)
Is it possible to add a feature to have the override changes from master node beeing automated (always) and to be executed before any filetransfer starts to ensure the files are the same and nothing more on the client nodes ?

My repository is about 1TB and about 100 nodes connected.

### Version Information

Syncthing Version: v0.14.44
OS Version: Windows 7 / QNAP NAS Linux / Windows 10

**Comment by AudriusButkevicius** [comment]
There is a ton of threads on the forum, and in the issue tracker about this, please do your research before opening new tickets.
