### ISSUE TITLE
can not connect service

### ISSUE THREAD

**Issue by peach5460** [syncthing/syncthing#4855]
today i use syncthing,Remote Devices can't connnect...

log:
[WM4S4] 06:37:23 INFO: GUI and API listening on 127.0.0.1:8384
[WM4S4] 06:37:23 INFO: Access the GUI via the following URL: http://localhost:8384/
[WM4S4] 06:37:31 INFO: kcp://0.0.0.0:22020 detected NAT type: Symmetric NAT
[WM4S4] 06:37:33 INFO: New NAT port mapping: external TCP address 10.0.0.2:24087 to local address 0.0.0.0:22000.
[WM4S4] 06:37:33 INFO: Detected 1 NAT device
[WM4S4] 06:37:42 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) shutting down
[WM4S4] 06:37:42 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting
[WM4S4] 06:37:42 INFO: c.S.listenerSupervisor: Failed service 'dynamic+https://relays.syncthing.net/endpoint' (1.000000 failures of 2.000000), restarting: true, error: "{dynamic+https://relays.syncthing.net/endpoint dynamic+https://relays.syncthing.net/endpoint} returned unexpectedly", stacktrace: [unknown stack trace]
[WM4S4] 06:37:44 INFO: Couldn't fetch release information: Get https://upgrades.syncthing.net/meta.json: dial tcp 46.101.130.230:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
[WM4S4] 06:37:44 INFO: Automatic upgrade: no version to select
[WM4S4] 06:37:46 INFO: Couldn't fetch release information: Get https://upgrades.syncthing.net/meta.json: dial tcp 46.101.130.230:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
[WM4S4] 06:38:03 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) shutting down
[WM4S4] 06:38:03 INFO: c.S.listenerSupervisor: Failed service 'dynamic+https://relays.syncthing.net/endpoint' (1.615130 failures of 2.000000), restarting: true, error: "{dynamic+https://relays.syncthing.net/endpoint dynamic+https://relays.syncthing.net/endpoint} returned unexpectedly", stacktrace: [unknown stack trace]
[WM4S4] 06:38:03 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting
[WM4S4] 06:38:24 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) shutting down
[WM4S4] 06:38:24 INFO: c.S.listenerSupervisor: Failed service 'dynamic+https://relays.syncthing.net/endpoint' (1.994046 failures of 2.000000), restarting: true, error: "{dynamic+https://relays.syncthing.net/endpoint dynamic+https://relays.syncthing.net/endpoint} returned unexpectedly", stacktrace: [unknown stack trace]
[WM4S4] 06:38:24 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting
[WM4S4] 06:38:45 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) shutting down
[WM4S4] 06:38:45 INFO: Entering the backoff state.
[WM4S4] 06:38:45 INFO: c.S.listenerSupervisor: Failed service 'dynamic+https://relays.syncthing.net/endpoint' (2.226438 failures of 2.000000), restarting: false, error: "{dynamic+https://relays.syncthing.net/endpoint dynamic+https://relays.syncthing.net/endpoint} returned unexpectedly", stacktrace: [unknown stack trace]
[WM4S4] 06:41:31 INFO: GUI and API listening on 127.0.0.1:8384
[WM4S4] 06:41:31 INFO: Access the GUI via the following URL: http://localhost:8384/
[WM4S4] 06:48:45 INFO: Exiting backoff state.
[WM4S4] 06:48:45 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting
[WM4S4] 06:49:06 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) shutting down
[WM4S4] 06:49:06 INFO: c.S.listenerSupervisor: Failed service 'dynamic+https://relays.syncthing.net/endpoint' (1.000000 failures of 2.000000), restarting: true, error: "{dynamic+https://relays.syncthing.net/endpoint dynamic+https://relays.syncthing.net/endpoint} returned unexpectedly", stacktrace: [unknown stack trace]
[WM4S4] 06:49:06 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting
[WM4S4] 06:49:27 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) shutting down
[WM4S4] 06:49:27 INFO: c.S.listenerSupervisor: Failed service 'dynamic+https://relays.syncthing.net/endpoint' (1.615290 failures of 2.000000), restarting: true, error: "{dynamic+https://relays.syncthing.net/endpoint dynamic+https://relays.syncthing.net/endpoint} returned unexpectedly", stacktrace: [unknown stack trace]
[WM4S4] 06:49:27 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting

### Version Information

Syncthing Version: v0.14.43
OS Version: WIN10(64 bit)/WIN2008R2(64 bit)

**Comment by Xyphex** [comment]
The [website](https://syncthing.net/) appears to be offline as well.

**Comment by AudriusButkevicius** [comment]
See https://github.com/syncthing/website/issues/54
