### ISSUE TITLE
Enhancement. Force sync button in the Android app

### ISSUE THREAD

**Issue by grwlf** [syncthing/syncthing#4861]
Hi! Thanks for the beatiful project! I'd like to place an enhacement request for the Android Syncthing app. Currently there is an 'sync only on wifi' option which is usually 'on' on my devices to lower power consumption. But sometimes I really need to sync my data now and this requires me to move through all the menu option to turn 'sync on wifi' off, wait, and re-enable it again.

Could you please consider adding 'Force sync' button with the following actions associated:
1) Disable the 'sync on wifi' mode
2) Wait for the first non-empty sync
3) Restore the 'sync on wifi' mode

Regards,
Sergey

**Comment by uok** [comment]
Please close this issue (wrong repo). Check in the [Syncthing Android](https://github.com/syncthing/syncthing-android) repo for existing issues.
