### ISSUE TITLE
Option to wipe remote folder when un-sharing a folder

### ISSUE THREAD

**Issue by edgimar** [syncthing/syncthing#4862]
Note, this is more or less similar to the closed (for reasons I don't understand) issue #798.

Here's one use-case demonstrating the value of this feature:  I have a folder X with some personal data in it shared across 5 devices.  One of the devices (say a laptop or phone) is stolen.  I want the ability to un-share folder X with the stolen device, and when un-sharing it, have a checkbox that says "wipe remote folder".  When this checkbox is enabled, it will cause the syncthing client on the stolen device to wipe the folder when it next attempts to sync.

While this may technically be possible by deleting all of the contents of folder X on a device, and having them be deleted on all devices, this is less than ideal if I regularly need to use and continue to synchronize the files in folder X.  This is why having a device-specific wipe makes sense.

**Comment by AudriusButkevicius** [comment]
You cannot target a specific device, as this makes the image of what the "latest" state inconsistent. If you say X delete all content, X will forward that to Y (as that is how syncthing works) causing a cascading effect deleting content everywhere. Also, even if you tell X to delete all content, X can still get it from Y, and you might not even know Y exists as Y might be only talking to X and having the copy of the data.


The referrenced ticket already explains how to do this, which involves moving the content away from the folder, make sure ALL (and this is the hard part, as you only control your own device) devices unshare the folder and add it back.

Closing this, as in a distributed "everyone is equal" system this is pretty much impossible to implement sanely.

**Comment by edgimar** [comment]
I'm not quite convinced -- is it not possible to modify the client so that when it receives (from another device) a "machine-specific wipe" message, the targeted client will disconnect from all other devices it was syncing the folder with, and then proceed to remove the folder's content?

I'm not asking about what's currently possible with the existing code, but what could be possible by adding a feature to the client to handle this case.

Of course to avoid abuse, it should also be possible for a particular client/node to be configured to select which other nodes are allowed to send it a "wipe" command for a particular synced folder.

**Comment by calmh** [comment]
Even if this were trivially implemented, it’s a destructive feature that goes against the stated goals of the project. The technical feasibility is moot. Sorry.

**Comment by edgimar** [comment]
Technically, no data would ever be _lost_ (in the sense that there is no way to recover it, and no copies of it exist anywhere any more) by such a wipe operation, because the wipe command would need to be issued from a node (A) where the data already exists to another node (B) where it would be removed from.  It would still exist on node A, and of course one could build in as many safeguards/confirmations as necessary to prevent someone from accidentally wiping a node.  It would only happen if (1) the receiving node explicitly authorized the sending node, and (2) the user at the sending node intentionally wished to issue the operation.

I guess the question is whether it is more important to allow a syncthing user to be safe against abuse of personal information (privacy concerns in the case of a stolen machine / etc.), or to require that all nodes will never "willingly" remove data.

If the "willing removal" of data is to be avoided, then why do we allow a user to remove a synced folder via the web-interface?  Isn't that also to be considered "data loss"?

Anyway, that's my (maybe more than) two cents. ;)

**Comment by Ferroin** [comment]
Your proposed use case listed in the first post invalidates your proposed implementation.  If a remote system has to choose to opt-in, then it's trivial for someone to prevent that data wipe by doing any of the following:

1. Modify the config on the stolen node with Syncthing not running to deauthorize all remote nodes from wiping the device's folders (or you know, just disable sync with all remote nodes completely).
2. Just copy the data off the disk without ever booting the system.
3. Boot the system without a network connection and look at the data from there.

Note also that any of these will work to keep that stolen data _regardless_ of whether a feature like you are proposing exists or not.  if you care that much about your data, you either need to wait for untrusted node support, or you need to just properly secure your system (which if it can be stolen means using some for of disk encryption, be it FDE, a SED, or per-file encryption as provided by all major operating systems.
