### ISSUE TITLE
Snap package could use removable-media slot

### ISSUE THREAD

**Issue by dylanmccall** [syncthing/syncthing#4863]
At the moment, it is difficult to give the syncthing snap access to removable media. If the snapcraft.yaml file included [the removable-media plug](https://github.com/snapcore/snapd/wiki/Interfaces#removable-media), it would be easy to do `snap connect syncthing:removable-media :removable-media` :)

**Comment by dylanmccall** [comment]
For anyone that finds themselves here, by the way, it's not too bad. I did this:

Add a systemd mount unit named something like /writable/system-data/etc/systemd/system/home-USERNAME-syncthing.mount:

    [Unit]
    Description=Mount unit for USERNAME-syncthing

    [Mount]
    What=/media/data1/syncthing/USERNAME
    Where=/home/USERNAME/syncthing
    Type=none
    Options=bind

    [Install]
    WantedBy=multi-user.target

Make sure /media/data1/syncthing/USERNAME is owned by the user running syncthing.

Next, allow syncthing to access your home folder:

    snap connect syncthing:home :home

Note that you could mount the data directory in /home/USERNAME/snap/syncthing/common, but then you have this really huge name for the mount unit as well. But if you do that, you don't need to grant syncthing any other permissions, which is nice.

**Comment by imsodin** [comment]
@dylanmccall If you know your way around snap, you are welcome to file a PR. There is also #4015. None of the regular contributors is well acquainted (or at all) with snap, so help is appreciated.
