### ISSUE TITLE
Feature Request: "rolling" synchronisation limits

### ISSUE THREAD

**Issue by spacekookie** [syncthing/syncthing#4865]
I've done some searching in the tracker and couldn't find anything so I'm suggesting it here.

I use Syncthing to move pictures from my phone to a server and also to my laptop. However, I take a *lot* of pictures and the sync folder is reaching a size that my laptop can't handle anymore.

So I would propose being able to set some limits on what is being synchronised, based on some parameter and specific to each device. i.e. my server or desktop computer gets all of the picture while my laptop only synchronises (say) the last 1000 items or the newest 10GB of files.

There could be a few different parameters to change the behaviour of the "rolling" sync. I think this would make Syncthing a lot more useful to a lot of people with photo upload as a common use case

**Comment by AudriusButkevicius** [comment]
This is something you should roll out yourself.
Set ignore deletes on the originating device (or master), and on the receiving device have a cron job that deletes all items apart from last 100 latest ones (or by name, whatever the criteria is).

**Comment by spacekookie** [comment]
That's really not very convenient, especially considering that it would still try to sync items to my computer just for me to delete them again, right?

I get that syncthing is supposed to follow a very UNIX philosophy. But I don't think this feature would be at all out of scope for a program that handles synchronisation of files :confused:

**Comment by AudriusButkevicius** [comment]
> That's really not very convenient, especially considering that it would still try to sync items to my computer just for me to delete them again, right?

If send only or ignore deletes is enabled on the source, then no, it would not try to push back the content you deleted nor would it delete it off the source.

**Comment by adamralph** [comment]
My solution for this is to only sync the firehose (incoming photo stream) with those machines that can handle it. Other machines with smaller storage get a curated "Pictures" folder.

**Comment by spacekookie** [comment]
@adamralph See, I want to get the latest pictures on my laptop but don't care about older pictures anymore at some point. So that wouldn't really work for me

**Comment by dcarosone** [comment]
How about a folder per (year/month/week, depending on the firehose volume),
and then each device can keep a window of however many past folders it has
storage for?

I use this scheme, and match each syncthing folder to an underlying zfs
dataset. Old folders change rarely (if at all), and can have longer scan
intervals, be moved to removable devices, etc.

I also have a 'live' sync folder for each device that can run syncthing
(phones, screenshot destination on laptops, etc). My photo import tool
copies from those to the consolidated date-based folders. These copies get
deduped by syncthing. Then I can delete images from the live folders to
make space on the smaller devices.
