### ISSUE TITLE
Docker Documentation

### ISSUE THREAD

**Issue by alcheagle** [syncthing/syncthing#4868]
Can you please add more documentation on how to start, run and configure Syncthing with docker? If there is something about I missed it.

**Comment by calmh** [comment]
Coming

**Comment by calmh** [comment]
https://github.com/syncthing/syncthing/blob/master/README-Docker.md

We should have something on the docs site as well.

**Comment by alcheagle** [comment]
Thank you. In the mean time I come to configure with the following ssh tunneling 
``ssh remote_ host -L 9999:docker_container_ip:8384`` I hope this could also be useful.

**Comment by alcheagle** [comment]
The problem is that the container by default doesn't bind to the interface 0.0.0.0:8384 port unless you set it manually and stays bound to 127.0.0.1:8384.
