### ISSUE TITLE
Folder modes are insufficiently granular

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4873]
So we currently have "send-recv" and "recv-only". That's fine as far as it goes, but doesn't cover a number of real world deployment scenarios I've run into. Specifically, it's not super uncommon to want to have a tree like structure with one device on top, several distribution devices for load sharing or redundancy, and clients at the bottom:

```
[source] -> [x × distribution] -> [y × clients]
```

We want the `source` to be `send-only` and the clients to only receive changes. What's the folder type on the distribution devices? Ideally it would be `send-recv` towards the source and `send-only` towards the clients, but that's not possible. We can hack around it a bit by using multiple folders sharing the same on disk files, but it's ugly and you get strange effects when the distribution devices talk to each other. The problem with having the distribution device be `send-recv` is that we then cannot protect against failure, admin problems, mishandling, etc on the clients, causing changes to propagate back up to the distribution and then down to other clients when it should not.

(Had we had the fabled `recv-only` folder type we could use that on the clients and let the middle layer be `send-recv`. But it would be cleaner still to enforce the rejection of changes on the receiving side.)

Another option would be for the folder mode to apply not to the folder as a whole but to a `(folder, device)`-tuple. We could then say that the distribution device should accept changes from the source but not from the clients.

**Comment by AudriusButkevicius** [comment]
You're using it wrong #close #wontfix 

I think the answer here is receive only as that has more generic application.

**Comment by calmh** [comment]
Yeah I'm getting a strong feeling that I will have to implement that sucker

**Comment by AudriusButkevicius** [comment]
Or not I guess :D

**Comment by calmh** [comment]
Yeah but this is not that ticket
