### ISSUE TITLE
Zeroed local/global "state" (local files untouched) and remote file deletion with root Windows symlink

### ISSUE THREAD

**Issue by PrototypeNM1** [syncthing/syncthing#4875]
When specifying a sync directory as a symlink to another drive and using the filesystem watcher I receive the following error on Windows:

Failed to start filesystem watcher for folder "Documents" (mqanr-z452q): GetFileAttributesEx /S:\Documents: The filename, directory name, or volume label syntax is incorrect.

The path provided in Syncthing's config is "~/Documents", I suspect the / is not being stripped given GetFileAttributesEx **/S:\...** I verified the ~ is not related to the issue by also specifying the absolute path and verifying the error persists.

Also triggered by this is that after a seemingly successful scan of the directory and it's contents (e.g. the number of files and folders look correct) the files and folders drop to 0, and remote devices empty their drives resulting is data loss on remote devices (note the local sync folders are unaffected).

### Version Information

Syncthing Version: v0.14.46
OS Version: Windows 10

**Comment by imsodin** [comment]
The filesystem watcher failure indeed seems to be the fixed symlink problem. The part about file/dir counts falling to 0 sounds troublesome, but the error message you posted means that the FS watcher was never started, so it can't be caused by the FS watcher directly (in general a "bad" scan request should in no way be able to wipe a folder). If you can reproduce that part, please post logs.

**Comment by calmh** [comment]
No, that was just my script not handling that this was cherry picked to .47 from master.

**Comment by calmh** [comment]
Thanks for noticing

**Comment by bugith** [comment]
Then is it intended this 4875 shows in 48-rc.2 bufixes list and disappears from 48-rc.3? Sorry if this is noise.

**Comment by calmh** [comment]
Yeah. I'm not retroactively fixing the rc2 tag message, but it's not supposed to be mentioned so in rc3 (and the real release in the end) it's not.
