### ISSUE TITLE
Panic loop with fswatcher enabled in syncthing v0.14.47-rc.1

### ISSUE THREAD

**Issue by alyandon** [syncthing/syncthing#4877]
Windows 10 x86_64

Syncthing gets stuck constantly restarting itself in a panic loop and it appears to be related to a particular folder on a non-OS drive.  When I manually disabled the fswatcher for that folder, syncthing appears to start working normally.

Here is an excerpt from the logs:
```
[XPQFK] 09:23:00 INFO: Completed initial scan of readwrite folder "Curse" (2g7rh-swpeu)
Panic at 2018-04-12T09:23:00-05:00
panic: bug: Notify backend is processing a change outside of the watched path: \\?\d:\minecraft\curse\Minecraft\Instances\Undiscovered\config\ruins_config\Gilly\GillyDCG2.tml
```

Full log (ip address and hostnames are obfuscated):

[panic-20180412-092300-redact.zip](https://github.com/syncthing/syncthing/files/1903640/panic-20180412-092300-redact.zip)

**Comment by imsodin** [comment]
Thanks for your report. What is the folder root path? Are there any symlinks/junctions involved?

**Comment by alyandon** [comment]
Root path for the problematic folder is `d:\minecraft\curse`

**Comment by imsodin** [comment]
Could you run the following build: https://build.syncthing.net/repository/download/Syncthing_BuildWindows/19250:id/syncthing-windows-amd64-v0.14.47-rc.1%2B4-g8b5421a.zip
It is equivalent to v0.14.47-rc1 except for adding some info to the panic message (see #4878).

**Comment by calmh** [comment]
Case difference...

**Comment by alyandon** [comment]
Yeah, this is one of the very first machines I installed syncthing on and the folder path recorded in the config definitely does not match the NTFS filename case.

**Comment by thieber** [comment]
Same problem here. Disabling fswatcher seems to calm it down.

**Comment by imsodin** [comment]
> Side note: Which is interesting. Is EvalSymlinks a way to get the real casing...?

@calmh Depends on what "real" is, but `EvalSymlinks` requires unique path names, and therefore does uppercase drive letters (while `Clean` does not). But it isn't document, had to look into the code. They even misleadingly state that `Clean` is called on the result - prob just to mess with my head.

Fix incoming.
