### ISSUE TITLE
Ignore Patterns ignored

### ISSUE THREAD

**Issue by nosliwneb** [syncthing/syncthing#4879]
- what happened
edit the Ignore Patterns in various versions of the GUI (in Windows)
save
open again, nothing there
 - expected:
edits should have worked/persisted
 - steps to reproduce:
Create a new folder /foo with this sitting in it (can't upload a file named .stignore, you'll need to rename it): 
[example.stignore.txt](https://github.com/syncthing/syncthing/files/1904301/example.stignore.txt)
initiate a share from a different machine
point the share to /foo
from the GUI, edit the file, save
access it again from the GUI, nothing is there (and likely the line endings are swapped around if you go to the actual file)

I feel like may have something to do with line endings... the original .stignore file was made on Linux and saved alternately with Unix and Windows line endings while debugging the problem, at various times it works, other times the line endings swap around. Haven't pinned it down exactly yet.

Syncthing Version: v0.14.46
OS Version: Windows 7 and 10
Browser Version: synctrayzor, at least one browser

**Comment by calmh** [comment]
I don't think I understand the issue. On the one hand you're saying your edits do not take effect, on the other hand you're saying the file is empty, on the third hand you're saying we convert line endings? It's quite possible that we convert line endings. But what is the actual problem you're seeing?

Does Syncthing (as the user you are running it under) have permissions to write to the file and directory?

**Comment by nosliwneb** [comment]
The actual file is affected by the edits.
The representation of the file as seen in the GUI goes from "stuff" to blank (usually). And then noting gets ignored.

**Comment by AudriusButkevicius** [comment]
Closing thoa as it seems this belongs on the forum as it's nore of a support/misconfiguration issue rather than an actual bug. Please reopen a thread on the forum explaining what you tried to do, what you expected to happen and what actually happened.
