### ISSUE TITLE
Use webcam to grab barcode of other device in web interface

### ISSUE THREAD

**Issue by apnewberry** [syncthing/syncthing#4881]
When adding another device from the web interface, it'd be nice to use the webcam to grab the barcode of the other device. I was able to do this using `zbarcam` from `zbar-tools` in Ubuntu 17.10, but an in-app button would be nice.

![image](https://user-images.githubusercontent.com/31109952/38773705-4a09532c-4008-11e8-9979-cebbe7620546.png)

**Comment by calmh** [comment]
Duplicate of #2054
