### ISSUE TITLE
Default defaultPullerPendingKiB size need to increased to 16M?

### ISSUE THREAD

**Issue by xjtdy888** [syncthing/syncthing#4883]
Now we have a maximum block size of 16M, but the default pull defaultPullerPendingKiB size is 8M, this will lead to the default configuration can not be pulled 16M file block

`
defaultPullerPendingKiB = 8192 // must be larger than block size
...
...
bytes := int(state.block.Size)
requestLimiter.take(bytes)
`

**Comment by calmh** [comment]
Yeah, it gets adjusted upwards later in the code but it's still an oversight.
