### ISSUE TITLE
[Feature Request] Adding of /mnt/media_rw/ path to facilitate ExSDCard Access Enabler

### ISSUE THREAD

**Issue by XIncognito10** [syncthing/syncthing#4890]
Magisk has a module called ExSDCard Access Enabler that allows programs to write to the sd card using a custom path "/mnt/media_rw/SDCARD_ID" I've tested it by adding a folder using the web gui using this path and its syncing beautifully. I was wondering if its possible for the native application to add support for this path if it exists so one doesnt need to use the web ui to add using this path

### Version Information

Syncthing Version: v0.14.46
OS Version: Windows 7 / Ubuntu 17.10

**Comment by calmh** [comment]
*handwaves* This is not the repo you're looking for. The repo you are looking for is [over there](http://github.com/syncthing/syncthing-android/issues).
