### ISSUE TITLE
Feature request: Thousand separator

### ISSUE THREAD

**Issue by kalsan** [syncthing/syncthing#4896]
In the device view, under local status, Syncthing shows the total amount of files, folders and the size of the data, like this:

![image](https://user-images.githubusercontent.com/7618650/39087063-4da4a8fe-459b-11e8-8d78-86998156c6e4.png)

With this many files and folders, it becomes pretty hard to get an idea of their number (is it hundreds of thousands or tens of thousands?). A thousand separator would help: `312'441` (EU) or `312,441` (US).

BTW the screenshot shows a real scenario, the host is a Raspberry Pi 3! With that much data on an external HDD, it still runs perfectly smooth. Syncthing never ceases to impress me.

**Comment by calmh** [comment]
Should be easy enough. To avoid locale controversies I suggest a simple half width space.

**Comment by imsodin** [comment]
What do you think about limiting the displayed numbers to 4 digits, using prefixes (e.g. here ~312k files ~46k dirs ~1009 GiB) and displaying the exact number in a tooltip? I'd think that the latter digits aren't relevant anymore in general with such high counts (and for debugging there is the tooltip).

**Comment by kalsan** [comment]
> To avoid locale controversies I suggest a simple half width space.

@calmh Sounds good to me, probably also looks quite tidy and modern

> What do you think about limiting the displayed numbers to 4 digits

@imsodin Even though your suggestion makes sence for file sizes, it might not be best for the amount of files and folders. I sometimes check the last digit(s) in order to see if Syncthing has detected the new file I just added. Say, the number is ...65 and I copy something from a USB stick to a shared folder, I wait for the number to increase. It's lazier than looking for the right shared folder on the left hand side (I have dozens in the list) and opening it.

**Comment by stonedbovines** [comment]
> To avoid locale controversies

Would it not be _better_ displayed as locale specific?

**Comment by uok** [comment]
I agree with @kalsan, please don't limit the digits. 
Also `.` would be the (another) correct separator for the EU. 
I think we could get away with just a space or a field where people could enter what they want.

**Comment by wweich** [comment]
JavaScript numbers have the `.toLocaleString([locale])` method. We should use that.

**Comment by calmh** [comment]
If you're going to localeify things, note all the other numbers as well: sizes and so on.

<img width="569" alt="screen shot 2018-04-22 at 09 59 30" src="https://user-images.githubusercontent.com/125426/39092698-fa191c8c-4613-11e8-8edc-8c38ae57b2d6.png">

**Comment by kalsan** [comment]
> Also . would be the (another) correct separator for the EU.

@uok Not in Switzerland IIRC :rofl: I overly simplified when I wrote "EU", things are much more complicated than that I'm afraid. We should be happy there is no imperial Kilobyte.

**Comment by imsodin** [comment]
Switzerland isn't in the EU, so...

I am ruing having started the bike shedding. Lets remember calmh's first foresighted comment:

 > Should be easy enough. To avoid locale controversies I suggest a simple half width space.

**Comment by jowimuc** [comment]
A space or a half width space follows the international conventions introduced in 2003 and IMHO would be the best option (https://en.wikipedia.org/wiki/Decimal_separator#Current_standards and f.)

**Comment by Ferroin** [comment]
+1 on use of a partial-width space, both `.` and `,` are used in at least some locales as a decimal separator, so they should be avoided for use for digit grouping if you're not going to be localizing it.

Ideally, it would be some form of space that prevents a line break, but the only options I know of that might work are U+00A0 (no-break space) and U+202F (narrow no-break space).  The first one is full-width, and the second doesn't have a consistent width across font-families (and is usually different from a half-width space).
