### ISSUE TITLE
API returns empty response if non-existing files are #included

### ISSUE THREAD

**Issue by ProactiveServices** [syncthing/syncthing#4901]
- Create a file for use as an ignore pattern `#include` file e.g. `global-ignores`
- Edit ignore patterns and add `#include global-ignores`
- Save changes
- Observe that #include file is not used for ignores and that Ignore Patterns GUI pane is empty.

Syncthing Version: v0.14.46
OS Version: Windows 7 SP1 x64, Debian Stretch 9.4
Browser Version: SyncTrayzor, Firefox 59

**Comment by calmh** [comment]
I can't reproduce this, #include works as advertised for me and as you describe. Side one:

```
$ echo foo > global-ignores
$ echo '#include global-ignores' > .stignore
$ echo foo > foo
$ echo bar > bar
```

Side two:

```
$ ls -l
total 16
-rw-r--r--  1 jb  staff  4 Apr 23 08:48 bar
-rw-r--r--  1 jb  staff  4 Apr 23 08:48 global-ignores
```

UI on side one:

![screen shot 2018-04-23 at 08 53 08](https://user-images.githubusercontent.com/125426/39111038-c4e0d9fe-46d3-11e8-9006-95b2067e7181.png)

**Comment by ProactiveServices** [comment]
Having done some more thorough tests the behaviour only triggers if the #include'd file does not exist. The docs do specify that this configuration is erroneous, but it ought to stop the folder (arguably) and still let the user edit the ignore patterns.

**Comment by AudriusButkevicius** [comment]
This is a bug, it seems it the ignores can't be parsed, the data we return from the API is gibberish, so we swallow the error somewhere.
