### ISSUE TITLE
Syncthing recreates the directories for deleted/missing "Folders"

### ISSUE THREAD

**Issue by kbtombul** [syncthing/syncthing#4903]
As the title says, Syncthing recreates or tries to recreate the directories for deleted or missing Folders. I have two examples below. They are similar in the sense that the Folder path and folder marker are gone when the issue happens.

### What happened
- I had a Folder added to Syncthing residing at path `/Volumes/foo/bar/baz` which is on an external hard drive. Just to clarify, the folder marker is `/Volumes/foo/bar/baz/.stfolder`.
- I decided to move it to somewhere else but also decided to deal with updating the path of the Folder later.
- I paused the Folder in Syncthing UI.
- I moved the folder to its new location. `foo` directory doesn't exist in `/Volumes` anymore.
- [issue] When I restart Syncthing it creates the `/Volumes/foo/bar/baz` directory structure while the Folder is still paused.
- [expected] If I resume the Folder I get `folder marker missing` error

### What I expected to happen
- Syncthing should not create `foo/bar/baz` directories in `/Volumes`.

### Steps to reproduce
- Create a few directories inside each other on an external drive (I am not sure if the drive being external is necessary, that is just how my setup is)
- Add the deepest directory to Syncthing as a Folder
- Pause the Folder
- Delete the whole directory structure up to the root of the external drive
- Restart Syncthing
- Observe. Sometimes Finder doesn't update itself so closing/reopening the Finder window might be necessary.

### Screen recording (8.1 MB)
![folder recreation bug](https://user-images.githubusercontent.com/732128/39232569-9305e974-4822-11e8-8f28-825bae7b7874.gif)

### What happened
- I have an encrypted directory that I mount to /Volumes/EncFS, which is also added to Syncthing. Just to clarify, the folder marker is `/Volumes/EncFS/.stfolder`.
- When I restart my computer, that encrypted directory is not mounted automatically.
- [issue] Syncthing start automatically and gives me `Creating directory for foobar: mkdir /Volumes/EncFS: permission denied ` error. (`foobar` is a directory that is in `/Volumes/EncFS` when the encrypted directory is mounted.)
- [expected] I also get `folder marker missing` error

### What I expected to happen
- Syncthing should not try to create `EncFS` or `EncFS/foobar` directories in `/Volumes`.

### Steps to reproduce
- Create an encrypted directory
- Mount the encrypted directory
- Add some files/directories in the mount point
- Add the mount point to Syncthing as a Folder
- Share that Folder with other Syncthing instances and make sure they are synched
- Restart computer.
- Open Syncthing UI and observe the errors.

#### Version Information
Syncthing Version: v0.14.46, macOS (64 bit)
OS Version: macOS High Sierra 10.13.4 (17E202)

**Comment by calmh** [comment]
I can reproduce this for a paused folder, but in the non-paused case. My steps to reproduce:

- Have a folder
- Pause it
- Shut down syncthing
- Delete the folder from disk
- Start syncthing
- Directory is recreated (folder still looks paused)
- Resume folder (it gets stopped due to missing marker)

Without the pausing I get the expected 

```
[MRIW7] 10:30:12 WARNING: Error on folder default: folder path missing
[MRIW7] 10:30:12 INFO: Failed initial scan of readwrite folder default
```

on startup.

**Comment by calmh** [comment]
What we used to do was create missing directories when starting/adding a folder *if the index for it is empty*. That should still be the case imho, paused or not. I suspect that the paused case just skips that check.

**Comment by imsodin** [comment]
We still do that, but paused folders are neither added nor started in the model, but skipped in `CommitConfiguration`. That's where I added the creation of the folder root, such that `SetIgnores` doesn't fail. I'll propose a PR shortly  that removes that and checks the folder path in `SetIgnores` (when I have written tests for this and the old issue).

**Comment by kbtombul** [comment]
I am still experiencing this issue on the same device with the updated Syncthing and macOS versions below. Is there anything I can provide to help getting to the bottom of this?

#### Version Information
Syncthing Version: v0.14.48, macOS (64 bit)
OS Version: macOS High Sierra 10.13.5 (17F77)

**Comment by AudriusButkevicius** [comment]
Experiencing what exactly?

**Comment by kbtombul** [comment]
Example #2 in the original issue (I have not tested #1 since I upgraded to v0.14.48).

Syncthing tries to create directories for paused folders when those directories were on external drives that are no longer mounted.

**Comment by vext01** [comment]
The test case for this issue is failing on OpenBSD and Syncthing 0.14.50:
[test.log](https://github.com/syncthing/syncthing/files/2441392/test.log)

```
--- FAIL: TestIssue4903 (0.00s)
    model_test.go:3760: expected path missing error, got: <nil>
```

Full test log attached.

**Comment by AudriusButkevicius** [comment]
What version of bsd?

**Comment by brycied00d** [comment]
@AudriusButkevicius OpenBSD -current aka 6.4-beta.

**Comment by AudriusButkevicius** [comment]
Given it's different users replying I am not sure if this answers the question correctly.

**Comment by brycied00d** [comment]
Apologies for the confusion, @AudriusButkevicius, I'm working on this with @vext01. His response in a separate issue (5077) made this detail clear. I was just "cross-posting" to help out.

And now that 0.14.51 has been released, we'll be retesting with that.

**Comment by AudriusButkevicius** [comment]
Looking at the logs it seems that inotify on bsd has issues, yet I suspect this is not related to this issue, so let's stop polluting here and move over to #5077

**Comment by vext01** [comment]
(#5077 is for a different test failure)

Here's some more info on this.

 * This test only fails when the test suite is run as a whole.

```
fremen% STRACE=model go test -v -run TestIssue4903
=== RUN   TestIssue4903
2018/10/07 12:49:55.767658 model.go:2688: INFO: Paused folder folder1
2018/10/07 12:49:55.768013 folderconfiguration.go:99: INFO: bug: uncached filesystem call (should only happen in tests)
2018/10/07 12:49:55.768077 folderconfiguration.go:99: INFO: bug: uncached filesystem call (should only happen in tests)
--- PASS: TestIssue4903 (0.01s)
PASS
```

```
$ go run build.go test
...
--- FAIL: TestIssue4903 (0.00s)
```

 * I can only reproduce this failure on one of my two OpenBSD machines. They are both running the same version of go (1.11) and they both are using syncthing `f528923d1ef224a07d58fea21b0dca14ca18ba78`.

Odd.. Maybe a race? (Note that I can't use `-race` on OpenBSD).

**Comment by vext01** [comment]
> Looking at the logs it seems that inotify on bsd has issues

I don't think OpenBSD has inotify(7) by the way.

**Comment by AudriusButkevicius** [comment]
When we say inotify, we mean the functionality, not the implementation. I suspect it would be using kqueue on bsd. Anyways, I don't have a bsd machine to test this. Perhaps there is some some test that leaves something behind that causes other tests to fail. I guess logs would be useful but given they are convoluted it might be hard to understand what happens. You could also binary search if some subset of tests cause this issue.

**Comment by vext01** [comment]
> When we say inotify, we mean the functionality, not the implementation. I suspect it would be using kqueue on bsd.

Ah I see. OpenBSD certainly has kqueue.
