### ISSUE TITLE
html select options for folder advanced settings broken on linux

### ISSUE THREAD

**Issue by 5x3** [syncthing/syncthing#4907]
use folder adv. settings

Folder Type
try to change from Send & Recieve to Send Only - you will fail.

same with
File Versioning
sometime it works for change particular version option sometimes not..

Syncthing Version: all till current
OS Version: Fedora
Browser Version: Firefox 55.0.3

**Comment by wweich** [comment]
Did you try another browser, or a recent version?

I have no problems on Manjaro (Arch) with Firefox 59.

**Comment by 5x3** [comment]
I am not going to change browser version just because of this bug.
looks like some web standards are broken here.
this may affect much more browsers and/or its versions.

the problem also persist for v0.14.47.

**Comment by AudriusButkevicius** [comment]
Well not really, if other browsers or other versions of the same browser work not much todo with standards.

**Comment by 5x3** [comment]
what?

**Comment by b3nson** [comment]
same here! 
I am not able to successfully change **any** of the settings in the "Edit Folder"-GUI!
As soon as i hit "Save", there appears a javascript error in the console:
```
TypeError: Cannot read property 'trim' of undefined
    at Scope.$scope.saveFolder (syncthingController.js:1608)
    at angular.js:10223
    at angular.js:17859
    at Scope.$eval (angular.js:11974)
    at Scope.$apply (angular.js:12074)
    at HTMLButtonElement.<anonymous> (angular.js:17858)
    at HTMLButtonElement.dispatch (jquery-2.2.2.js:4755)
    at HTMLButtonElement.elemData.handle (jquery-2.2.2.js:4567)
```
Syncthing v0.14.47
Tested on 
* OS X with Chrome/Firefox/Safari
* Android with Chrome/Firefox/MIUI-Browser
* Debian with Firefox

**Comment by b3nson** [comment]
The error seems to come from the "Ignore Patterns"-GUI...
`Error: undefined is not an object (evaluating '$('#editIgnores textarea').val().trim')`
The IgnorePatterns-Textarea is empty in all my Folders, even though the `.stignore` is not!

**Comment by b3nson** [comment]
On another machine (also OS X) it (changing anything in "Edit Folders") works on the same "Folders" not working on 3 other machines?!??
Identical up-to-date Firefox-Version!

**Comment by AudriusButkevicius** [comment]
Do you have an invalid/non-existing #include file in your ignores?

**Comment by b3nson** [comment]
ok....problem solved!

It came from a **custom GUI-Theme**, that worked without problems before.
Changing back to one of the "default"-themes (Actions > Settings > GUI > GUI Theme) does not produce the error anymore.

@5x3 does this solve your problem too?

**Comment by AudriusButkevicius** [comment]
Custom as in custom shipped with syncthing?

**Comment by b3nson** [comment]
a slightly changed version of the default theme. (shows the the "recent changes" as a permanent list under the folders etc)
