### ISSUE TITLE
bug: custom Windows icon missing in latest release

### ISSUE THREAD

**Issue by harrisonhjones** [syncthing/syncthing#4909]
# What Happened

- Got Syncthing update on my Windows machine
- Noticed that the custom icon was **not** set for the binary (added in [this commit](https://github.com/syncthing/syncthing/commit/8208bfa2b9146e13772667bcc28b903ce6e24152))

# What I Expected to Happen

- New Windows binary to have syncthing icon

# Steps to Reproduce

1. Download latest Windows version of Syncthing
1. Extract on a Windows machine
1. Observe that the `syncthing.exe` binary has the default icon and not the custom icon

# My Guess

The update Windows build wasn't run (doubtful) or somehow failed to embed the file details (likely).

# Version Information

Syncthing v0.14.47, Windows (64 bit)
OS Version: Windows 10 (64 bit)
Browser Version: N/A

# Misc

It's not a big deal but my name also doesn't show up in the [AUTHORS](https://github.com/syncthing/syncthing/blob/master/AUTHORS) file. Maybe my change was too small?

**Comment by calmh** [comment]
I forgot to install the required stuff on the build server, will take care of it. The lack of credit is an oversight as well, made possibly by the fact that the scripts don't enforce it for the build scripts and stuff. I'll take care of that as well.

**Comment by calmh** [comment]
Fixed, and tested that it actually works. 👍
