### ISSUE TITLE
SyncThing for backups [Feature Request]

### ISSUE THREAD

**Issue by RasmusKallas** [syncthing/syncthing#4912]
SyncThing syncs things. I get it.
I am requesting a BackupThing: an option to compress all files on one end (for example offsite backup server could compress to save storage)

### Version Information

Syncthing Version: v0.14.47

**Comment by AudriusButkevicius** [comment]
Please read the issue template.

**Comment by RasmusKallas** [comment]
The template says delete everything, I now removed the version what I am using.

**Comment by AudriusButkevicius** [comment]
Right, I guess my previous comment does not make sense as we changed the issue template to raise feature requests before discussing them on the forum.

Anyways, this is syncthing, not backupthing, so what you are talking about is more or less out of scope of what the tool is trying to achieve.

You can already find plenty of explanations on why synching should not be used for backups.

**Comment by RasmusKallas** [comment]
Well I wouldn't of even requested it, if I would have better choice: I don't want a monthly subscription and that means no backup.. almost. It means you need to buy your own offsite machine and then backup to that. The ransomware thing can be prevented by acronis free thing Windows Defender and Malwarebytes weekly or daily scan does it for computer germs. Also you offer file history also.
Now only thing is to actually get the files to an offsite machine. That's where SyncThing comes in (not yet)..
Crashplan.. Crashed.
Only alternative to that is BuddyBackup, **what has experienced loads of outages lately** and latest update to anything is 2014, parent country not answering, tutorial with WinXP.

Now there is 3 options (what I could find)
1. Do your own solution: probably others have better ones
2. Resilio
3. SyncThing

1. is certainty not an option. Now Resilio is directly paid and not extendable from crashes (if it closes or something). SyncThing is open and free (tough if I stay to use it, I see donating as paying or like that).

SyncThing has loads of features. I am trying to start to use it (since others have too for backup), **that's why I am here requesting a feature to compress**.

I will probably use ST for intended use too actually, so I will probably stay anyways.
Also I find it a problem (tested 2x, with fishy machines), that it takes a long time to find partnered machine to start syncing to it, if at all, if it is connected trough the spiderwebs.

**Comment by uok** [comment]
@RasmusKallas please move your ideas and problems to the [forum](https://forum.syncthing.net/) so they can be read and discussed by a bigger audience. 

May I also suggest to create a separate topic for Crashplan with title "CrashPlan alternative" where you describe the features that Crashplan used to have. It's clearly out of scope for the current Syncthing but I think the underlying software could be used for this. I think the closer the Crashplan deadline comes (afaik October) the more people will look for alternatives and maybe we find good developers who take on this task and contribute both to Syncthing and "Backthing"

**Comment by RasmusKallas** [comment]
[Offtopic] How do I become not a new user in forums? I have many links in my not made thread, can't post it.

**Comment by AudriusButkevicius** [comment]
To be honest, I am not sure this is going to get any traction as I don't see anyone raising hands or caring about implementing this. Sure, we can discuss, but I question the value of that.

**Comment by adamralph** [comment]
Ultimately, this will have some cost associated with it, since the data has to live somewhere. Someone has to pay for the server or cloud storage where the backup will live. It may be easier (and cheaper) to use a backup service. I use https://www.backblaze.com/ and I'm very happy with it. USD 50 per year for _unlimited_ backups is very cheap in my book.

**Comment by RasmusKallas** [comment]
@adamralph sure you can pay for offsite, but the key thing is (with encryption) you can backup to your friend's machine, making a deal that friend can do same or just buy drives to their pc

Also I would move to Forum.

**Comment by adamralph** [comment]
It still seems simpler and cheaper to pay for backblaze. Also remember that
backblaze is unlimited. I back up a lot of data, so maintaining my own
multi-TB drive somewhere would have significant cost.

**Comment by RasmusKallas** [comment]
Also it's not cheap for me, since I have 3 or sometimes more pcs + family + some other families. Also I change all but 1 pcs(desktop) on my side, so the per pc thing for blackblaze is not for me...
For me the BackupThing wouldn't change much besides the compression, what will make the data about 60% original size. I guess I can just buy more drives then.
For more normal people friend's pc factor (why crashplan got so popular)

**Comment by RasmusKallas** [comment]
Well it would certainly depend from person to person. If it is under TB/pc, then it is managable (also considering most people have 500gb drives in laptops or 1tb+ssd(128 or 256 usually)

**Comment by adamralph** [comment]
I use SyncThing to gather all my data on one machine (and I also use it all
from that machine) and then just back up that one machine.

**Comment by RasmusKallas** [comment]
Oh the syncthing backblaze coop is pretty clever, tough you need to have the storage on the main machine...
If someone is willing to help me learn Go (basically ready to respond to some questions, I can google) I could try to do it myself.
For me tough, it's just cheaper to get drives and a 60€ win machine (have the drives from everyone, what they have bought + I work in a laptop place, we have loads of spare spinning, I can buy 500gb for 20€ and 320 and 250 for 5-10€) Considering I already have needed drives, it would be 2 locations for 3-4 families (how you take it) for cost of 1yr of backblaze.

**Comment by uok** [comment]
Please continue discussion [this forum thread](https://forum.syncthing.net/t/back-up-thing-an-alternative-to-crashplan-and-buddybackup/11535)
