### ISSUE TITLE
Windows folder name case change, leads to Out of Sync with continous tmp files being recreated and not syncing

### ISSUE THREAD

**Issue by dandar** [syncthing/syncthing#4916]
Windows folder name is case insensitive, but leads to Out of Sync with continuous tmp files being recreated and not syncing.  This happens if one changed the folder name in windows, but only changing the case (for example changing the first letter of the folder name to Capital).  It seems to create duplicate folders in other Devices, and leads to inability to Sync.  This is likely an issue if one changes the folder name letter case in the middle of synchronizing.     

It was resolved (folder updated correctly) when I manually changed the folder name on each device to match exact letter case, and manually deleted the tmp files within that folders that were Out of Sync.

### Version Information

Syncthing Version: v0.14.47, Windows (64 bit)
OS Version: Windows 10, Version 1709, OS built 16299.371
Browser Version: (not applicable, not a GUI issues)

**Comment by AudriusButkevicius** [comment]
Dup of #1787, please search issues before opening new ones.
