### ISSUE TITLE
Stuck at Out of Sync Items 

### ISSUE THREAD

**Issue by neobie** [syncthing/syncthing#4917]
Syncthing Version: v0.14.47, Linux (64 bit)
OS Version: Ubuntu 14.04

Recently keep having "Out of Sync" items, and the files are not syncthing properly to other ubuntu servers. Has been using Syncthing for years and working fine, until recently. Is the update has serious bug?
Has been changing permission, pause, edit, remove and add back server still same.

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.

**Comment by laoyur** [comment]
same issue here, v0.14.54 on both sides
tried restarting Syncthing on both sides, does not help. just stuck and the file number of Out of Sync Items never changes.

**Comment by pitlochry** [comment]
same issue here, v0.14.54 windows on both sides (both send and receive folders), no ignored items.
the folders on both sides are "up to date", but on one device the other device is stuck at "syncing 99%" with 176 "out of sync items" (nothing is syncing, down- an upload rate at 0B/s; and checking the alleged out of sync items in file manager on both devices, they seem to be in sync)
same issues can be found e.g. here https://forum.syncthing.net/t/out-of-sync-items-issues/11866 and on various other threads in the forum, none with a solution.
