### ISSUE TITLE
Deleted folders come back (Again)

### ISSUE THREAD

**Issue by TomyCesaille** [syncthing/syncthing#492]
Hello,
Issue "deleted folders come back #364" (https://github.com/syncthing/syncthing/issues/364) is now well working on 0.9 release when .stversion folder is present.
Unfortunately, this issue still occur in case of having a .syncthing.fooFile into the deleted folder.
Having the Log [GSJRT] 04:58:47 WARNING: remove /Tada/Bar : directory not empty

Here is the scenario : 
-Put a new (big) file into a folder (PC A)
-Let remote computer syncthing this new file (PC B) so the remote file have its .syncthing preposition 
-Remove the folder while in process of syncing (PC A)

regards,
Tom

**Comment by gunwald** [comment]
I have the same problem with v0.12.19. When I delete a folder A on a machine, that is part of a bigger cluster, it uses to appear again. Even if I delete it on, say 5 of six machines, if the sixth comes online after a while (say after two weeks), the folder appears again and gets spread over all machines (consuming all my bandwidth for some hours).
As unfortunately in my case the folder has the name of my former girlfriend this really hurts!

**Comment by AudriusButkevicius** [comment]
Unless you reset the index or have a master folder setup, that shouldn't happen. You'll have to provide an isolated reproducion case if you want this investigated.

**Comment by gunwald** [comment]
There is no master and I don't delete any index files. 

>  …provide an isolated reproducion case

What do you mean exactly by that? How would I do this? Thanks for the fast reaction!

**Comment by AudriusButkevicius** [comment]
Well, I suggest you create a new syncthing folder on the nodes, and try to reproduce the case in an empty clean environment. Then try reducing the number of nodes involved, to see if you can find the culprit.

It might also be due to the underlying type of filesystem one of the nodes uses.

**Comment by gunwald** [comment]
Ok, I'll try this. The file system is EXT4 on all machines.
