### ISSUE TITLE
unable to shutdown under linux-arm (WD-MyPassport Drive)

### ISSUE THREAD

**Issue by moxou** [syncthing/syncthing#4920]
I'm trying to sync a big folder (~10 000 files / 315GB) with my Passport drive.
Syncthing seem to hang down - Cycling in infinite loop
`[HRK6B] 00:59:05 INFO: Exiting backoff state.

[HRK6B] 00:59:05 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting

[HRK6B] 00:59:05 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) shutting down

[HRK6B] 00:59:05 INFO: c.S.listenerSupervisor: Failed service 'dynamic+https://relays.syncthing.net/endpoint' (1.000000 failures of 2.000000), restarting: true, error: "{dynamic+https://relays.syncthing.net/endpoint dynamic+https://relays.syncthing.net/endpoint} returned unexpectedly", stacktrace: [unknown stack trace]

[HRK6B] 00:59:05 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting

[HRK6B] 00:59:05 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) shutting down

[HRK6B] 00:59:05 INFO: c.S.listenerSupervisor: Failed service 'dynamic+https://relays.syncthing.net/endpoint' (1.998907 failures of 2.000000), restarting: true, error: "{dynamic+https://relays.syncthing.net/endpoint dynamic+https://relays.syncthing.net/endpoint} returned unexpectedly", stacktrace: [unknown stack trace]

[HRK6B] 00:59:05 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting

[HRK6B] 00:59:05 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) shutting down`

Then when I want to shutdown, I'm unable to access via GUI and API http address but 2 syncthing process still exist and unable to kill them.

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
