### ISSUE TITLE
Syncthing should have guard against running old versions with new .config/* files

### ISSUE THREAD

**Issue by ssergiienko** [syncthing/syncthing#4921]
Problem:
I have latest release of Syncthing (v0.14.47) and during development & debugging I accidentally run older version of Syncthing v0.14.(4 or 17) and it was successfully started in background because config paths are the same (defaults).
Now, my _config.xml_ becomes a mix of old-style and new-style options but still has version=28 and who knows what can happen to other files if version will be even older(e.g. db format incompatibility).

For example:
```diff
 <configuration version="28"> # both files

-        <minDiskFree unit="%">1</minDiskFree>
+        <minDiskFreePct>0</minDiskFreePct>
-        <pullerMaxPendingKiB>0</pullerMaxPendingKiB>
+        <pullers>0</pullers>
```

What's expected? One of this:
- it should fail to start early with appropriate message unless some special option is used like `--allow-downgrade` (or whatever)
- or at least start in read-only mode for everything

### Version Information

Syncthing Version: Any
OS Version: Any

**Comment by AudriusButkevicius** [comment]
I don't see an actual problem though. If something was incompatible, I guess I would expect it to fail. If it didn't, it's probably ok.

**Comment by calmh** [comment]
It can be a problem as it’ll (re)write attributes in an old format that is no longer understood by newer Syncthings and won’t be converted again. I think it would be sane to refuse to load a config from the future by default.

**Comment by bahadir60** [comment]
@calmh, @AudriusButkevicius, @ssergiienko Hi there,
I wanna work on this ticket. As I understand the problem, besides the different Syncthing versions, they have different GUI Configuration versions (28 and 25). So that don't let loading config.xml for older Syncthing versions and logged "Version Conflict" with Exit code is appropriate to solve the problem. Any suggestions or comments?? 
Thxs.

**Comment by calmh** [comment]
Mmm, yes. There's a current config version, defined somewhere in config.go I think. If the config on disk has a higher number than that, it has a newer schema that we by definition don't understand.

There's a place in main.go where we check if the config was *upgraded*, which might be a good place to also check if the config version is too high and abort.

Alternatively the check could happen already in the config loader, but it would be nice to be able to force a start with `--allow-downgrade` or something, in which case having the config loader throw an error might be annoying.

**Comment by bahadir60** [comment]
@calmh Thanx, I will work on it and implement ASAP
