### ISSUE TITLE
fsWatcher is not reinstated after a syncthing folder reappeared on the filesystem

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing#4923]
Reproducer
1. Create a syncthing folder on the filesystem with the file watcher enabled as it is default now.
2. Stop Syncthing
3. move the folder away (alternatively unmount the device representing the folder)
4. Start Syncthing
5. Open Web UI
6. Error message appears (folder marker missing)
7. Move the folder back in the original place (or mount the device thats representing the folder)
8. Syncthing continues working on that folder (shows "current" instead of "error" again)
9. Web UI now displays the notice "file watcher could not be installed"

Workaround solution
Restart Syncthing, file watcher and folder is okay then.

Syncthing Version: v0.14.47
OS Version: Windows 10 x64
Browser Version: Chrome 63

**Comment by imsodin** [comment]
The warning in the web UI and logs should have looked like:
> Failed to start filesystem watcher for folder *yourfolder*: *specific error message*
Did you get that, and if yes, what was your "specific error message"?

**Comment by imsodin** [comment]
That's a good point. Logging a warning on setup failure was introduced when there was no periodic retrying. It's a separate issue though, right?

**Comment by AudriusButkevicius** [comment]
Yeah just pointing it out.

**Comment by Catfriend1** [comment]
Yeah I'll head for grabbing logs tomorrow after I got lazy on todays nonbusiness holiday in germany:)

**Comment by Catfriend1** [comment]
Ok, Step 6 I'm getting this:
`2018-05-11 13:48:55 Error on folder "Kamera" (lg-h815-Bilder): folder marker missing
2018-05-11 13:48:55 Failed initial scan of readwrite folder "Kamera" (lg-h815-Bilder)`

Step 8: (I hit the rescan button)
`2018-05-11 13:50:30 Cleared error on folder "Kamera" (lg-h815-Bilder)`

![image](https://user-images.githubusercontent.com/16361913/39923380-9ecbd6e8-5523-11e8-9fc9-5f3a3a4a1646.png)

I enabled model and watchaggregator logs.

**Comment by Catfriend1** [comment]
Even with fs log enabled, no more error messages. Could it be that fs watcher is not notified to continue working after a "cleared error on folder" state change?

**Comment by imsodin** [comment]
The relevant debug facility is model. On clearing an error, starting the fs watcher is scheduled. If no scanning/pulling is in progress, it should happen right after. The "not started" thing in the UI means it did not do that. Please provide logs with model debug facility in the period around (mostly after) `2018-05-11 13:50:30 Cleared error on folder "Kamera" (lg-h815-Bilder)`.

**Comment by imsodin** [comment]
Actually, I just noticed the 10s full rescan interval. It's completely useless to have fs watcher enabled in that case (it delays by 10s too) and entirely possible, that the fs watcher is not started because the folder is scanning all the time. So change that first before doing any further debugging.

**Comment by Catfriend1** [comment]
Okay scanning was one hour before I chose 10 secs for debugging on the test folder. Ill set 60s and model log next time and report back.

**Comment by Catfriend1** [comment]
Ok, again with log ... (model)

PASS 1 - I did NOT follow the reproducer and just rename and rename back the folder and did NOT restart syncthing in stopped state. > No problem occured.
The folder is in its normal place and idle:
![grafik](https://user-images.githubusercontent.com/16361913/40319181-85ae8dde-5d27-11e8-9df5-24d4051ce518.png)
I renamed the folder, so syncthing cannot find it and waited until syncthing noticed it on the next regular full rescan:
![grafik](https://user-images.githubusercontent.com/16361913/40319185-8be94f18-5d27-11e8-8eeb-503dc1238492.png)
I put the folder back in place and waited until syncthing detected it again on next full scan:
![grafik](https://user-images.githubusercontent.com/16361913/40319224-b0414abe-5d27-11e8-8e37-8b31961c4fff.png)
[pass1.zip](https://github.com/syncthing/syncthing/files/2023393/pass1.zip)

**Comment by Catfriend1** [comment]
PASS2 with model log enabled:
I exactly followed the reproducer. Started syncthing with model log on step 4.
It says "1m error setting up ... not started" for the fswatcher in the web UI.
![grafik](https://user-images.githubusercontent.com/16361913/40319463-8ac59ac8-5d28-11e8-82ce-4e61a3f6b2a3.png)
I then renamed the folder back and waited ~ 30 secs until the next full rescan occured regularly. syncthing cleared the folders error state looking like this:
![grafik](https://user-images.githubusercontent.com/16361913/40319548-c5251784-5d28-11e8-9c91-ae8f7b668c7f.png)
As you can see, the fswatcher is still showing as "error on setup ... retrying in 1 min... not started".
Log attached - This is the problem my ticket is about.
[pass2.zip](https://github.com/syncthing/syncthing/files/2023416/pass2.zip)

**Comment by Catfriend1** [comment]
To summarize:
PASS 1 showed the fswatcher is correctly reinstated if a folder root got moved away while syncthing is running and then put back while syncthing "is still running" while all that happened.
PASS 2 shows my problem this issue is about. If a folder is fine, then syncthing is shut down, the folder gets moved away, sycnthing started up again, the folder is moved back in place, the fswatcher is not reinstated correctly.

**Comment by Catfriend1** [comment]
@imsodin Thanks for providing a fix
