### ISSUE TITLE
syncthing 是否支持“增量备份”功能 ‘Support for incremental backup functionality’

### ISSUE THREAD

**Issue by wxhnizy** [syncthing/syncthing#4933]
这几天一直在研究syncthing ，目前可以实现同步备份，但是我发现了一个问题，例如：我手机上删掉一张已经被同步的照片，服务器中也会把这个文件删掉，但是我不想那么做。
我想实现，服务器增量备份，例如：我把手机中的某一张照片删除后，服务端并不对这个文件做任何处理，只是一个简单的 照片备份功能。由衷的感谢

我的英文很烂 下面是机器翻译得来

I've been studying syncthing for a couple of days now, but I've found a problem, such as deleting a photo that's been synchronized on my phone and deleting it from the server, but I don't want to do that.
I want to implement a server incremental backup, for example: When I delete one of the photos on my phone, the client does not do anything with the file, just a simple photo backup function. Heartfelt thanks

My English sucks.

**Comment by wxhnizy** [comment]
我查阅了文档，似乎没有什么有价值的信息，希望得到你们的帮助，谢谢
I looked up the document, there seems to be no valuable information, I hope to get your help, thank you

**Comment by calmh** [comment]
https://docs.syncthing.net/advanced/folder-ignoredelete.html

https://forum.syncthing.net
