### ISSUE TITLE
Enforcing hidden file attribute in the Windows world

### ISSUE THREAD

**Issue by cmarsura** [syncthing/syncthing#4935]
I have to sync several Windows machines where some directory have many files that have the HIDDEN attribute bit set.

On the destination machines, after the synchronization is done, the attribute is lost, so I must resort to use some scripts to keep the files synced with this attribute.
I see that the HIDDEN attribute is already used in the Windows version of Synchthing, for hiding the temporary files under sync, but then it is removed on final rename.

Having this attribute enforced in this platform will be very beneficial, at least for who use this very useful tool in this os platform that is very popular.

Using v0.14.47, Windows (64 bit)

**Comment by cmarsura** [comment]
Well, while you are in a hurry, is best to take 30 instead of 29.
👍 
Thank you.
cm

**Comment by Kropekk** [comment]
I'll try to fix it in the following day(s).

**Comment by cmarsura** [comment]
Good to hear.
Thank you.
:)

**Comment by kakra** [comment]
Windows attributes could be stored as xattr data in Linux so it could be synced back.

**Comment by calmh** [comment]
Given we have no way to properly store this attribute on other platforms, in a way that survives edits, renames etc., I think this is just something that we will have to live with not implementing.
