### ISSUE TITLE
"Watching for Changes" dialog undismissable

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4941]
The prompt to upgrade to fs watcher is undismissable. Pressing either yes or no does nothing, no errors in the Javascript console. Likely to be Angular fallout...

v0.14.48-rc.3-4-g9e696a15

Safari

**Comment by imsodin** [comment]
Did you check for multiple `unackedNotifications` in the config? I had that once after doing the transitions a ton of times for testing without opening the UI or resetting the config, but it turned out that clicking `No` repeatedly dismissed one notification after the other until done.

**Comment by uok** [comment]
On one computer I had two notifications: 1st - fs watcher, 2nd - insecure admin. I clicked "No" on 1st and "OK" on 2nd and then 1st reappeard. I closed it with "No" and it didn't show again. So I guess stacked notifications in background.

**Comment by calmh** [comment]
Yeah there's a problem when there's multiple ones, because it seems the directive sets a dismiss function on the parent scope, so two of these will override each other. And now there are two - because two are included in the page. That the first one is invisible doesn't matter, that's the dismiss function that gets (uselessly) called. I'll tweak.
