### ISSUE TITLE
Windows/Linux/Solaris cluster problematic names with directories and duplication

### ISSUE THREAD

**Issue by whorfin** [syncthing/syncthing#4956]
I had a syncthing directory containing many directories, this particular branch being problematic:
`books/0purchased/`
   [many files, subdirectories, etc under here]

I have a cluster of Mac, Windows, Linux RHEL 7 machines, and one Solaris [OmniOS CE] box.
After wondering why synchronization was taking so long, I noticed that some of the linux/solaris machines were also maintaining a `0PURCH~1` directory, which was a sort-of duplicate of `0purchased`.
Windows and Mac clients only ever say the `0purchased` directory
A back-and-forth sync-storm caused changes in `0purchased` to bounce back and forth through the `0PURCH~1` copy, as far as the non-unixy systems saw it.

On the Windows box, I renamed the `0purchased` directory to `_purchased`.
This resulted in `_purchased` being added to all the unixy systems [with no further weird named subdir copies], but `0purchased` began to be pushed back to the Windows box, presumably from the `0PURCH~1` copy.

The whole experience was spooky, and raises the question as to whether normalization for windows-style names [the `blah~1` thing smells a lot like 8.3 SFN naming nonsense] is missing some cases...

Cheers

### Version Information

Syncthing Version: v0.14.47
OS Version: Windows 10 / RHEL 7.2 [linux] / OmniOSCE-r151022 [Solaris]

**Comment by calmh** [comment]
I have no idea how the synthesized 8.3 name popped up in there, but it's correct that we do not attempt to normalize this and figure out what the "actual" name is.

**Comment by AudriusButkevicius** [comment]
There is already a ticket for 8.3 name resolution.
I think we get those names from the watcher.

**Comment by calmh** [comment]
That's kind of bad though? It would be good to know under what circumstances that happen, because it fucks things up pretty royally.

**Comment by AudriusButkevicius** [comment]
My guess is that the kernel bubbles up whatever path the underlying apllication has written to. So if your midnight commander used 8.3 path, this is what you get notified about. There are some win32 api calls to resolve these paths I think.

This is just a theory, yet this ticket is no way different from the existing 8.3 ticket, so I don't see why this should stay open.

**Comment by AudriusButkevicius** [comment]
This doesn't fuck things any worse than the case difference nonsense.

**Comment by calmh** [comment]
No, it's equally bad however/whenever it happens of course. But if the notification stuff changes the frequency from "pretty much never" to "whenever another application uses an old api" that makes the problem more frequent and hence worse.

**Comment by whorfin** [comment]
It’s more complicated than that
Under some circumstances _ was allowed, and the number can be up to 7 digits 
https://staff.washington.edu/dittrich/misc/fatgen103.pdf
https://en.m.wikipedia.org/wiki/8.3_filename
![Image](https://i.imgur.com/uo1Zre8.jpg)
![Image](https://i.imgur.com/rhe6mz2.jpg)
![Image](https://i.imgur.com/GjYuWLo.jpg)
