### ISSUE TITLE
API is unclear for terms like 'folder'

### ISSUE THREAD

**Issue by paulhargreaves** [syncthing/syncthing#4959]
e.g. https://docs.syncthing.net/rest/db-browse-get.html?highlight=folder#

This states 
"The call takes one mandatory folder parameter and two optional parameters."

It's unclear that 'folder' means 'folder id'. if there is a folder id. If there is no folder id, then it's just the folder.

There is a sort of hint at https://docs.syncthing.net/rest/db-scan-post.html  - e.g. 'Takes the optional parameters folder (folder ID)', but even that isn't as clear as it should be since if there is no folder id, then it's just the folder name.

**Comment by canton7** [comment]
I suspect you meant to open this issue in the docs repo? 

Anyone can edit the docs, improvements welcome!
