### ISSUE TITLE
Getting tons of "The system cannot find the path specified." in the log

### ISSUE THREAD

**Issue by vladipus** [syncthing/syncthing#4961]
Getting just tons of
`[RQWCQ] 20:35:47 INFO: Puller (folder "My Folder" (*****-*****), file "folder\path"): dir mkdir: CreateFile C:\sync\folder\path folder\path: The system cannot find the path specified.`

 - what happened,
Deleted a folder.
 - what you expected to happen instead, and
Re-create the missing directory structure or not sync the deleted folder at all.
 - any steps to reproduce the problem.
Use Syncthing in a real multi-user environment.

### Version Information

Syncthing Version: v0.14.47
OS Version: Windows 10

**Comment by vladipus** [comment]
This error is pursuing me for ages in all sorts of Syncthing versions, on all sorts of folders I'm using at home and at work. Nothing helps, including the rescans. Recreating the directory structure by hand is too cumbersome.

**Comment by calmh** [comment]
> any steps to reproduce the problem.
> Use Syncthing in a real multi-user environment.

While flippancy is nice and all and understandable in frustration, we have >150k users and this is the first report of this exact nature. Some steps would be good.

**Comment by vladipus** [comment]
Great respect for the software, no doubt, but this really drives me nuts.

We are not doing anything particular, actually. We just regularly delete and add tons of different files and folders. As a programmer, to date, I can't understand why Syncthing won't re-create a directory tree in a `mkdir -p` way, if it needs to.

**Comment by vladipus** [comment]
For example, I just deleted a Music folder and see:
`
Music\iTunes\Album Artwork\Cache\5C0ADFAFE000EA85\11\08\11 | The system cannot find the path specified.
-- | --


`

**Comment by canton7** [comment]
> If it cannot find the path specified, why doesn't it just CREATE it??? 

Please help us figure that out 🙂 

Reading [this](https://github.com/syncthing/syncthing/blob/6802505dda3451804a8790b00c13161a782bf5f0/lib/fs/basicfs_windows.go#L36), it looks like it fails if the folder's parent's parent doesn't exist? It looks like MkdirAll has now been fixed upstream, but not yet released.

**Comment by vladipus** [comment]
Right now I'm doing he same thing by hand with:
user@DESKTOP-USRPNKK MSYS /z/FFZ-RW/Branding
$ mkdir -p "Music/iTunes/Album Artwork/Cache/5C0ADFAFE000EA85/11/08/11"

user@DESKTOP-USRPNKK MSYS /z/FFZ-RW/Branding
$ mkdir -p "Music/iTunes/Album Artwork/Cache/5C0ADFAFE000EA85/10/15/01"

user@DESKTOP-USRPNKK MSYS /z/FFZ-RW/Branding
$ mkdir -p "Music\iTunes\Album Artwork\Cloud Purchases\5C0ADFAFE000EA85\01\14\08                                                                   "

user@DESKTOP-USRPNKK MSYS /z/FFZ-RW/Branding
$ mkdir -p "Music\iTunes\Album Artwork\Cloud Purchases\5C0ADFAFE000EA85\01\14\08                                                                   "

user@DESKTOP-USRPNKK MSYS /z/FFZ-RW/Branding
$ mkdir -p "Music\iTunes\Album Artwork\Cloud Purchases\5C0ADFAFE000EA85\01\14\08                                                                   "

user@DESKTOP-USRPNKK MSYS /z/FFZ-RW/Branding
$ mkdir -p "Music\iTunes\Album Artwork\Cloud Purchases\5C0ADFAFE000EA85\02\00\03                                                                   "

user@DESKTOP-USRPNKK MSYS /z/FFZ-RW/Branding
$ mkdir -p "Music\iTunes\Album Artwork\Cloud Purchases\5C0ADFAFE000EA85\02\02\00                                                                   "
And it actually HELPS. =)

**Comment by canton7** [comment]
Can you confirm that this issue occurs when there are 3 levels of directories which don't exist (e.g. it occurs when "Music/iTunes/Album Artwork/Cache/5C0ADFAFE000EA85" exists but "Music/iTunes/Album Artwork/Cache/5C0ADFAFE000EA85/11" doesn't exist), but does **not** occur when only 2 levels of directories don't exist (e.g. it does **not** occur when "Music/iTunes/Album Artwork/Cache/5C0ADFAFE000EA85/11" exists, but "Music/iTunes/Album Artwork/Cache/5C0ADFAFE000EA85/11/08" doesn't exist)?

**Comment by vladipus** [comment]
If you need more info, it looks like this:

`[RQWCQ] 13:27:38 INFO: Puller (folder "Farm Frenzy Branding" (jskas-wspvm), file "Pictures\\Медиатека Фото.photoslibrary\\resources\\proxies\\derivatives\\02\\00\\2ee"): dir mkdir: CreateFile \\?\Z:\FFZ-RW\Branding\Pictures\Медиатека Фото.photoslibrary\resources\proxies\derivatives\02\00: The system cannot find the path specified.
[RQWCQ] 13:27:38 INFO: Puller (folder "Farm Frenzy Branding" (jskas-wspvm), file "Pictures\\Медиатека Фото.photoslibrary\\resources\\proxies\\derivatives\\02\\00\\2ef"): dir mkdir: CreateFile \\?\Z:\FFZ-RW\Branding\Pictures\Медиатека Фото.photoslibrary\resources\proxies\derivatives\02\00: The system cannot find the path specified.
[RQWCQ] 13:27:38 INFO: Puller (folder "Farm Frenzy Branding" (jskas-wspvm), file "Pictures\\Медиатека Фото.photoslibrary\\resources\\proxies\\derivatives\\02\\00\\2f0"): dir mkdir: CreateFile \\?\Z:\FFZ-RW\Branding\Pictures\Медиатека Фото.photoslibrary\resources\proxies\derivatives\02\00: The system cannot find the path specified.
[RQWCQ] 13:27:39 INFO: Puller (folder "Farm Frenzy Branding" (jskas-wspvm), file "Pictures\\Медиатека Фото.photoslibrary\\resources\\proxies\\derivatives\\02\\00\\2f1"): dir mkdir: CreateFile \\?\Z:\FFZ-RW\Branding\Pictures\Медиатека Фото.photoslibrary\resources\proxies\derivatives\02\00: The system cannot find the path specified.
[RQWCQ] 13:27:39 INFO: Puller (folder "Farm Frenzy Branding" (jskas-wspvm), file "Pictures\\Медиатека Фото.photoslibrary\\resources\\proxies\\derivatives\\02\\00\\2f2"): dir mkdir: CreateFile \\?\Z:\FFZ-RW\Branding\Pictures\Медиатека Фото.photoslibrary\resources\proxies\derivatives\02\00: The system cannot find the path specified.
[RQWCQ] 13:27:39 INFO: Puller (folder "Farm Frenzy Branding" (jskas-wspvm), file "Pictures\\Медиатека Фото.photoslibrary\\resources\\proxies\\derivatives\\02\\00\\2f3"): dir mkdir: CreateFile \\?\Z:\FFZ-RW\Branding\Pictures\Медиатека Фото.photoslibrary\resources\proxies\derivatives\02\00: The system cannot find the path specified.
[RQWCQ] 13:27:39 INFO: Puller (folder "Farm Frenzy Branding" (jskas-wspvm), file "Pictures\\Медиатека Фото.photoslibrary\\resources\\proxies\\derivatives\\02\\00\\2f4"): dir mkdir: CreateFile \\?\Z:\FFZ-RW\Branding\Pictures\Медиатека Фото.photoslibrary\resources\proxies\derivatives\02\00: The system cannot find the path specified.
[RQWCQ] 13:27:40 INFO: Puller (folder "Farm Frenzy Branding" (jskas-wspvm), file "Pictures\\Медиатека Фото.photoslibrary\\resources\\proxies\\derivatives\\02\\00\\2f5"): dir mkdir: CreateFile \\?\Z:\FFZ-RW\Branding\Pictures\Медиатека Фото.photoslibrary\resources\proxies\derivatives\02\00: The system cannot find the path specified.
[RQWCQ] 13:27:40 INFO: Puller (folder "Farm Frenzy Branding" (jskas-wspvm), file "Pictures\\Медиатека Фото.photoslibrary\\resources\\proxies\\derivatives\\02\\00\\2f6"): dir mkdir: CreateFile \\?\Z:\FFZ-RW\Branding\Pictures\Медиатека Фото.photoslibrary\resources\proxies\derivatives\02\00: The system cannot find the path specified.
[RQWCQ] 13:27:40 INFO: Puller (folder "Farm Frenzy Branding" (jskas-wspvm), file "Pictures\\Медиатека Фото.photoslibrary\\resources\\proxies\\derivatives\\02\\00\\2f7"): dir mkdir: CreateFile \\?\Z:\FFZ-RW\Branding\Pictures\Медиатека Фото.photoslibrary\resources\proxies\derivatives\02\00: The system cannot find the path specified.
[RQWCQ] 13:27:41 INFO: Puller (folder "Farm Frenzy Branding" (jskas-wspvm), file "Pictures\\Медиатека Фото.photoslibrary\\resources\\proxies\\derivatives\\02\\00\\2f8"): dir mkdir: CreateFile \\?\Z:\FFZ-RW\Branding\Pictures\Медиатека Фото.photoslibrary\resources\proxies\derivatives\02\00: The system cannot find the path specified.
[RQWCQ] 13:27:41 INFO: Puller (folder "Farm Frenzy Branding" (jskas-wspvm), file "Pictures\\Медиатека Фото.photoslibrary\\resources\\proxies\\derivatives\\02\\00\\2f9"): dir mkdir: CreateFile \\?\Z:\FFZ-RW\Branding\Pictures\Медиатека Фото.photoslibrary\resources\proxies\derivatives\02\00: The system cannot find the path specified.
[RQWCQ] 13:27:41 INFO: Puller (folder "Farm Frenzy Branding" (jskas-wspvm), file "Pictures\\Медиатека Фото.photoslibrary\\resources\\proxies\\derivatives\\02\\00\\2fa"): dir mkdir: CreateFile \\?\Z:\FFZ-RW\Branding\Pictures\Медиатека Фото.photoslibrary\resources\proxies\derivatives\02\00: The system cannot find the path specified.
[RQWCQ] 13:27:41 INFO: Puller (folder "Farm Frenzy Branding" (jskas-wspvm), file "Pictures\\Медиатека Фото.photoslibrary\\resources\\proxies\\derivatives\\02\\00\\2fb"): dir mkdir: CreateFile \\?\Z:\FFZ-RW\Branding\Pictures\Медиатека Фото.photoslibrary\resources\proxies\derivatives\02\00: The system cannot find the path specified.
[RQWCQ] 13:27:42 INFO: Puller (folder "Farm Frenzy Branding" (jskas-wspvm), file "Pictures\\Медиатека Фото.photoslibrary\\resources\\proxies\\derivatives\\02\\00\\2fc"): dir mkdir: CreateFile \\?\Z:\FFZ-RW\Branding\Pictures\Медиатека Фото.photoslibrary\resources\proxies\derivatives\02\00: The system cannot find the path specified.
[RQWCQ] 13:27:42 INFO: Puller (folder "Farm Frenzy Branding" (jskas-wspvm), file "Pictures\\Медиатека Фото.photoslibrary\\resources\\proxies\\derivatives\\02\\00\\2fd"): dir mkdir: CreateFile \\?\Z:\FFZ-RW\Branding\Pictures\Медиатека Фото.photoslibrary\resources\proxies\derivatives\02\00: The system cannot find the path specified.
[RQWCQ] 13:27:42 INFO: Puller (folder "Farm Frenzy Branding" (jskas-wspvm), file "Pictures\\Медиатека Фото.photoslibrary\\resources\\proxies\\derivatives\\02\\00\\2fe"): dir mkdir: CreateFile \\?\Z:\FFZ-RW\Branding\Pictures\Медиатека Фото.photoslibrary\resources\proxies\derivatives\02\00: The system cannot find the path specified.
[RQWCQ] 13:27:42 INFO: Puller (folder "Farm Frenzy Branding" (jskas-wspvm), file "Pictures\\Медиатека Фото.photoslibrary\\resources\\proxies\\derivatives\\02\\00\\2ff"): dir mkdir: CreateFile \\?\Z:\FFZ-RW\Branding\Pictures\Медиатека Фото.photoslibrary\resources\proxies\derivatives\02\00: The system cannot find the path specified.
[RQWCQ] 13:27:43 INFO: Puller (folder "Farm Frenzy Branding" (jskas-wspvm), file "Pictures\\Медиатека Фото.photoslibrary\\resources\\proxies\\derivatives\\03\\00\\300"): dir mkdir: CreateFile \\?\Z:\FFZ-RW\Branding\Pictures\Медиатека Фото.photoslibrary\resources\proxies\derivatives\03\00: The system cannot find the path specified.
[RQWCQ] 13:27:43 INFO: Puller (folder "Farm Frenzy Branding" (jskas-wspvm), file "Pictures\\Медиатека Фото.photoslibrary\\resources\\proxies\\derivatives\\03\\00\\301"): dir mkdir: CreateFile \\?\Z:\FFZ-RW\Branding\Pictures\Медиатека Фото.photoslibrary\resources\proxies\derivatives\03\00: The system cannot find the path specified.
[RQWCQ] 13:27:43 INFO: Puller (folder "Farm Frenzy Branding" (jskas-wspvm), file "Pictures\\Медиатека Фото.photoslibrary\\resources\\proxies\\derivatives\\03\\00\\302"): dir mkdir: CreateFile \\?\Z:\FFZ-RW\Branding\Pictures\Медиатека Фото.photoslibrary\resources\proxies\derivatives\03\00: The system cannot find the path specified.`

**Comment by vladipus** [comment]
Yup, there are three levels and even more, maybe.
I think it should re-create any depth it needs.
I'm not sure about Go, but there a python shutil methods to do such things for sure)

**Comment by canton7** [comment]
Can you confirm that the issue does **not** occur when only 2 levels of directories don't exist (e.g. it does not occur when "Music/iTunes/Album Artwork/Cache/5C0ADFAFE000EA85/11" exists, but "Music/iTunes/Album Artwork/Cache/5C0ADFAFE000EA85/11/08" doesn't exist)?

**Comment by canton7** [comment]
If you read the link to the code I posted, Go does have such a method but it (was) broken for UNC paths, so there's a hack in place (and it looks like the hack might be buggy).

**Comment by vladipus** [comment]
> Can you confirm that the issue does not occur when only 2 levels of directories don't exist
Even if I create `Music\iTunes\Album Artwork\Cloud Purchases\5C0ADFAFE000EA85\12` by hand, `Music\iTunes\Album Artwork\Cloud Purchases\5C0ADFAFE000EA85\12\06\05` is still not created.

**Comment by calmh** [comment]
What is `Z:` here anyway? Network share or something? I wonder if the unicode in the middle is misinterpreted somewhere.
