### ISSUE TITLE
Inconsistent Rate Limit Units between "Settings > Connections" and "Advanced > Options"

### ISSUE THREAD

**Issue by Athanasius** [syncthing/syncthing#4963]
This would be minor, if not for the factor of 8 confusion meaning limits might be ineffective, or cause files to sync far too slowly.

Using 0.14.47 installed on a Debian stable (Stretch) system using the 'deb' stanza in an /etc/apt/sources.list.d/ directory the "Settings > Connections" menu says "Incoming Rate Liimt (KiB/s)" (similarly for outgoing), but if I instead look at the "Advanced > Options" area I see "Max Recv Kbps"(and similarly for 'Send').  KiB/s and Kbps are not the same, the former being KiloBytes per Second, the latter Kilobits per second.

I'm assuming that lower case 'b' in 'Kbps' should be upper case.

Changing the value on either screen updates it on the other, so it would appear to be the exact same configuration value referred to on both.

**Comment by calmh** [comment]
The naming of the advanced config is unfortunate but follows the internal config variable name, which also cannot easily be changed as it's part of the config file and hence our external APIs. Use the regular settings dialog and avoid the confusion.
