### ISSUE TITLE
Syncthing overrides linux execute file mode when synching from Windows

### ISSUE THREAD

**Issue by almaasrawi** [syncthing/syncthing#4969]
### THE ISSUE
Syncthing erases the execute file mode from script files after syncing the file from Windows, making users always have to remember to chmod the file whenever it's changed in the Windows machine.

### REPRO STEPS
* Set up syncthing between a Linux machine and a Windows machine.
* On Linux, create a script file and chmod it to enable execute.
* Wait for the file to be sync'ed on Windows, and then edit the file's contents.
* When the file edits are sync'ed to the Linux machine, observe the file mode.

###EXPECTED
 The execute file mode remains.

###ACTUAL
The execute file mode is erased.

**Comment by radcool** [comment]
This matter is discussed here: https://forum.syncthing.net/t/win-to-linux-changes-permissions/10091

**Comment by AudriusButkevicius** [comment]
@calmh on windows, we could copy permission bits from curFile when scanning?

**Comment by calmh** [comment]
Ugh. Maybe if ignore permissions is set? This is painful.

**Comment by AudriusButkevicius** [comment]
I guess we could do it for the execute bit unconditionally, given it has no meaning on windows anyway?

**Comment by AudriusButkevicius** [comment]
Even if the file doesn't have permissions, they are recorded, and on Windows, se should still probably copy execute bits from the old file, that is execute bit can only be removed on Linux.

```diff
diff --git a/lib/scanner/walk.go b/lib/scanner/walk.go
index c77f243..7f9ffc3 100644
--- a/lib/scanner/walk.go
+++ b/lib/scanner/walk.go
@@ -321,13 +321,19 @@ func (w *walker) handleItem(ctx context.Context, path string, fchan, dchan chan
 }

 func (w *walker) walkRegular(ctx context.Context, relPath string, info fs.FileInfo, fchan chan protocol.FileInfo) error {
-       curMode := uint32(info.Mode())
-       if runtime.GOOS == "windows" && osutil.IsWindowsExecutable(relPath) {
-               curMode |= 0111
+       curFile, hasCurFile := w.CurrentFiler.CurrentFile(relPath)
+
+       newMode := uint32(info.Mode())
+       if runtime.GOOS == "windows"
+               if osutil.IsWindowsExecutable(relPath) {
+                       newMode |= 0111
+               }
+               if hasCurFile {
+                       newMode |= (0111 & curFile.Permissions)
+               }
        }

        blockSize := protocol.MinBlockSize
-       curFile, hasCurFile := w.CurrentFiler.CurrentFile(relPath)

        if w.UseLargeBlocks {
                blockSize = protocol.BlockSize(info.Size())
```

**Comment by calmh** [comment]
Possibly. There is already a hack for the execute bit on Windows, but not to cover this use case. The validity of which I’m not really convinced of either for that matter, given these are not executable files on Windows, Windows not having execute bits, etc.

**Comment by AudriusButkevicius** [comment]
Sure, but we have history wether the file was executable or not, the fact that it got modified on a platform that does not have the bits doesn't mean we should remove them.
