### ISSUE TITLE
Syncthing struggles copying symbolic links between Linux systems

### ISSUE THREAD

**Issue by jhwinters** [syncthing/syncthing#4972]
Syncthing Version: v0.14.47
OS Version: Debian GNU/Linux 9.4 (Stretch)

I have two Debian GNU/Linux boxes, both running 9.4.  I use Syncthing to back up a reasonable sized (5.4G) working directory between the two.  The source machine is set to send only, and the destination machine is then backed up nightly.

Variously spread through the working directory are some symbolic links, all pointing to files also within the tree.  The sending copy of Syncthing keeps reporting that it can't update these symbolic links, although it has successfully copied them to the destination.

If I delete one of them on the destination, then tell the sending end to "Override Changes" then the symbolic link is successfully recreated at the target end, but the sending end still insists that the propagation has failed.  As far as I can see, there is no error message associated with the individual symbol links - just a list of them.

![image](https://user-images.githubusercontent.com/345516/40624984-95068c70-62a7-11e8-8fca-9c739f751043.png)

Both source and destination filesystems are ext4, so no issue with symlinks not being supported.

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
