### ISSUE TITLE
Feature request: Set Rescan button to Disabled instead of Hidden while scanning

### ISSUE THREAD

**Issue by Nnnes** [syncthing/syncthing#4977]
A few times now, I've clicked the wrong button for a folder because it switched to/from the Scanning/Syncing state, hiding/showing the Rescan button and causing all the buttons to the left to shift over. It feels like a little bit of a dark pattern (though obviously not intentionally malicious). It makes sense to me to set the Disabled attribute on the button rather than hiding it entirely.

![rescan-disabled](https://user-images.githubusercontent.com/28599170/40779958-79c9bfc6-649c-11e8-8e02-908544a7c6f0.png)

**Comment by calmh** [comment]
Yes. We hide other buttons that are not commonly visible ("override" for example), but there is no reason to do this here and moving buttons around sucks.
