### ISSUE TITLE
Impossible to edit folder with path "/"

### ISSUE THREAD

**Issue by sss123next** [syncthing/syncthing#4983]
1. create  "/" share
2. edit
3. impossible to save change because path set to empty value

version: 	v0.14.48-rc.4+32-gd3a02a16-dirty,
OS Version: linux x86_64

**Comment by calmh** [comment]
Yeah as much as I think that's not a good idea, it's clearly a bug. I guess we strip the "trailing" slash somewhere in the presentation code.
