### ISSUE TITLE
Changed file (keepassxc) overwritten with previous version

### ISSUE THREAD

**Issue by hackel** [syncthing/syncthing#4987]
I'm using Syncthing to synchronize my KeepassXC database between 4 devices.  One is a server that is on all the time, and so should be updated immediately with any changes.  Today, I discovered that a change I had made was no longer there.  After some digging, I found an old copy of the file in my .stversions folder dated today, but last modified a week ago.  Apparently syncthing received an older copy of the database without the change from another device, and happily overwrote my changes.

KeepassXC saves access information on each entry, even when there are no changes, so the file/timestamp is constantly being updated.  I assume this somehow confused Syncthing, but I don't understand why this wouldn't have appeared as a conflict.  It was luck that I even realized anything was wrong.  

### Version Information

Syncthing Version: v0.14.47 (snap)
OS Version: Ubuntu 18.04

**Comment by AudriusButkevicius** [comment]
So I am going to close this as there is not much actionable here. 

Unless you have a reproducer, I'll throw a stone at KeepassXC and say that:
1. KeepassXC either had the file in memory, or read the file content in memory.
2. Syncthing downloaded the new file, updated the local version of the file.
3. KeepassXC wrote the version it just read on top of the newly synced file, essentially performing a rollback.

I can only assume that KeepassXC assumes exclusive access to the files and does not expect other applications to modify them underneath it's feet.

If you have evidence of it being our fault with a reproducer, start a thread on the forum.
