### ISSUE TITLE
Incorrect large block size chosen for large files on 32 bit archs

### ISSUE THREAD

**Issue by decathorpe** [syncthing/syncthing#4990]
I'm running the test suite for version 0.14.48 on fedora, and it fails on 32 bit architectures with the following error:

```
+ go test [.. snip ..] github.com/syncthing/syncthing/lib/protocol
--- FAIL: TestBlockSize (0.00s)
	protocol_test.go:381: BlockSize(2147483648), size=16777216, expected 2097152
	protocol_test.go:381: BlockSize(3221225472), size=16777216, expected 2097152
FAIL
FAIL	github.com/syncthing/syncthing/lib/protocol	0.457s
```

**Comment by Catfriend1** [comment]
Hmm this looks like its compared to int max corresponding to 2^31 on 32 bit systems....

**Comment by decathorpe** [comment]
Well, 2097152 = 2^21, and 16777216 = 2^24, so you might be on to something.

Forgot to mention more details: Using go 1.10.2, this test fails on i686 and armv7hl arches, and passes on x86_64, ppc64le, aarch64, s390x.

**Comment by calmh** [comment]
Yeah this is a totally legit problem in block size selection on 32 bit archs due to bad integer math / overflow.

**Comment by calmh** [comment]
So the effect here is that 32 bit archs would choose a 16 meg block size for files >= 2 GiB, as that is when the multiplication overflows and the `filesize < ...` test never succeeds. I think it's rare enough to have large files, have enabled large blocks, and be on a 32 bit arch that I don't think we need to panic-release this.

**Comment by decathorpe** [comment]
Sounds good, thanks for fixing this so quickly!
