### ISSUE TITLE
Database schema migrations should handle up/down/up-grades

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#4994]
Lets assume I'm on 0.14.45. I upgrade to 0.14.48 and two database migrations are applied. But 0.14.48 has some sort of bug that I can't tolerate and I roll back to 0.14.45. Things are fine.

Then 0.14.49 comes out and I upgrade. The migrations will be applied again, but there's already a bunch of new indexes and stuff in place. Some of those keys will probably be overwritten correctly, some will remain from the previous migration run and be totally wrong at this point. Chaos ensues.

We should wipe the key space for what we're creating in a migration, before creating it.

---

Not all migrations will be backwards compatible and then the downgrade step itself will fail. That's a different issue, and probably fine.

**Comment by AudriusButkevicius** [comment]
I think we only go up. If we see a newer version of schema we support, we nuke the db.

**Comment by calmh** [comment]
Yeah, I guess, since we can't know what funky future stuff the higher schema version implies. Take off and nuke from orbit. It's the only way to be sure.
