### ISSUE TITLE
iOS App

### ISSUE THREAD

**Issue by trymeouteh** [syncthing/syncthing#4995]
Are there plans to create an Syncthing iOS app which can be downloaded from the App Store. I know there is a Syncthing iOS app being developed but uses GO and will only work on jailbreak devices.

**Comment by calmh** [comment]
None that I’m aware of. I don’t think there’s any such app being developed.

**Comment by uok** [comment]
@trymeouteh please search the forum https://forum.syncthing.net/search?q=ios, maybe you can PM some users to check for current status.

**Comment by pbasov** [comment]
Last useful thread on this was this one, but i think it's dead:
https://forum.syncthing.net/t/on-syncthing-ios-port-again/8964

There's also fsync, but it's broken as far as i know.
https://itunes.apple.com/gb/app/fsync/id964427882?mt=8

**Comment by matkam** [comment]
A Syncthing iOS File Provider (https://developer.apple.com/documentation/fileprovider) would be fantastic
