### ISSUE TITLE
Folders with Windows short names appearing

### ISSUE THREAD

**Issue by fbreve** [syncthing/syncthing#4998]
It's the second time an issue like this is happening, so I decided to report it.
I have two subfolders on a subfolder of a shared folder. These are their names:
- Graduação
- Pós-Graduação

Suddenly, I found other two folders with the Windows short names (8 characters names from DOS times):
- GRADUA~1
- PS-GRA~1

Apparently these two folders had the same content from the other, so I deleted them, but later I found out the original folders (Graduação and Pos-Graduação) were removed from all the synced systems. So I lost the files and had to restore them from a backup.

Apparently, Syncthing is creating those 8-char folders as treating them as the real ones. Modifications from other systems are updated on the these 8-char folders instead of the original ones.

I don't know why this is happening, neither how to reproduce. Both times this happened inside the same shared folder, but in different subfolders. Both times it happened to folders with special characters like ç and ã.

**Comment by AudriusButkevicius** [comment]
Dup https://github.com/syncthing/syncthing/issues/3800
