### ISSUE TITLE
v0.14.48 panic: runtime error: index out of range

### ISSUE THREAD

**Issue by kpuc** [syncthing/syncthing#5002]
Syncthing Version: syncthing v0.14.48 "Dysprosium Dragonfly" (go1.10.2 linux-386) teamcity@build.syncthing.net 2018-05-14 06:53:06 UTC
OS Version: Slackware 14.2 32bit

Panics at irregular intervals; sometimes as soon as ~40s after startup, sometimes several hours.  Always the message is "panic: runtime error: index out of range".  
Presumably my machine acquired v0.14.48 within twelve hours of its release, which would put the first panic 24hrs or more since release.  

From the first log file:
[7JAPU] 16:16:31 INFO: Folder DABingeNeedRetire isn't making progress. Pausing puller for 1m0s.
Panic at 2018-06-08T16:17:16-08:00
panic: runtime error: index out of range

goroutine 247254 [running]:
[....]

Switching back to v0.14.47 (And turning off auto update in the config) fixes this problem.

**Comment by calmh** [comment]
So literally all the information we need is in the part you snipped to dot-dot-dot

**Comment by kpuc** [comment]
Trying to attach the file, but it's not working... 
[panic-20180610-161250.log](https://github.com/syncthing/syncthing/files/2098503/panic-20180610-161250.log)

**Comment by calmh** [comment]
Thanks.

```
Panic at 2018-06-10T16:12:50-08:00
panic: runtime error: index out of range

goroutine 673 [running]:
github.com/syncthing/syncthing/lib/model.(*Model).recheckFile(0x194d2420, 0xc326c38c, 0x79b45524, 0x9b71beeb, 0x4b0f3c16, 0x53a919b2, 0xe2119819, 0xc90f78a8, 0x112cf36c, 0x870fde0, ...)
	/opt/buildagent/work/src/github.com/syncthing/syncthing/lib/model/model.go:1410 +0xfd6
github.com/syncthing/syncthing/lib/model.(*Model).Request(0x194d2420, 0xc326c38c, 0x79b45524, 0x9b71beeb, 0x4b0f3c16, 0x53a919b2, 0xe2119819, 0xc90f78a8, 0x112cf36c, 0x1a6a9360, ...)
	/opt/buildagent/work/src/github.com/syncthing/syncthing/lib/model/model.go:1386 +0x10b0
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).handleRequest(0x1a54ad80, 0x8, 0x1a6a9360, 0xb, 0x1b03f2c0, 0x2d, 0x80000, 0x0, 0x181e8, 0x19570520, ...)
	/opt/buildagent/work/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:588 +0x148
created by github.com/syncthing/syncthing/lib/protocol.(*rawConnection).readerLoop
	/opt/buildagent/work/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:380 +0x586

```

**Comment by calmh** [comment]
A `>` on a line above should be `>=`...
