### ISSUE TITLE
Even with minDiskFree option syncthing crashes because of disk full

### ISSUE THREAD

**Issue by vsespb** [syncthing/syncthing#5004]
I have minDiskFree set up for each folder.
```
# grep minDiskFree config.xml 
        <minDiskFree unit="%">1</minDiskFree>
        <minDiskFree unit="%">1</minDiskFree>
        <minDiskFree unit="%">1</minDiskFree>
```
However, after syncronizing way too much items
syncthing crashed with:

```
Jun 12 17:51:30 li488-134 syncthing[5759]: [SYASK] FATAL: Cannot open database: write /home/syncthing/.config/syncthing/index-v0.14.0.db/MANIFEST-000170: no space left on device - Is another copy of Syncthing already running?
Jun 12 17:51:30 li488-134 systemd[1]: syncthing@syncthing.service: Main process exited, code=exited, status=1/FAILURE
Jun 12 17:51:30 li488-134 systemd[1]: syncthing@syncthing.service: Unit entered failed state.
Jun 12 17:51:30 li488-134 systemd[1]: syncthing@syncthing.service: Failed with result 'exit-code'.
Jun 12 17:51:30 li488-134 systemd[1]: syncthing@syncthing.service: Service hold-off time over, scheduling restart.
Jun 12 17:51:30 li488-134 systemd[1]: Stopped Syncthing - Open Source Continuous File Synchronization for syncthing.
Jun 12 17:51:30 li488-134 systemd[1]: syncthing@syncthing.service: Start request repeated too quickly.
Jun 12 17:51:30 li488-134 systemd[1]: Failed to start Syncthing - Open Source Continuous File Synchronization for syncthing.
Jun 12 17:51:30 li488-134 systemd[1]: syncthing@syncthing.service: Unit entered failed state.
Jun 12 17:51:30 li488-134 systemd[1]: syncthing@syncthing.service: Failed with result 'exit-code'.

```

so does it mean minDiskFree option does not work?

related https://github.com/syncthing/syncthing/issues/302

syncthing v0.14.47 on Debian 9
What I expected to happen: all folders stopped
What happened instead: syncthing crashed and minDiskFree option does not seem to be anyhow useful

**Comment by AudriusButkevicius** [comment]
Use forum for support as explained in the issue template. The location of where syncthing stores its database is full, nothing todo with the folders.

**Comment by vsespb** [comment]
But I have only one partition. So location of database and folders is the same. What I mean by this bug report - minDiskFree did not work. It ran out of disk, even when minDiskFree set, so minDiskFree is not working at all.

**Comment by AudriusButkevicius** [comment]
As I said, support is on the forum.

**Comment by vsespb** [comment]
Sorry, not get it - why it's considered support request, but not bug report?

**Comment by AudriusButkevicius** [comment]
Because we can't do much if the disk is full, and there is not much we can do if we weren't the ones who filled it up, unless you can prove it.

**Comment by vsespb** [comment]
Option minDiskFree exists and should do something. According to docs it should stop folder. But it did not. Bug report is about that.
If minDiskFree would work properly, it would stop folder and sync process stopped and syncthing would not crash because of disk full.

**Comment by vsespb** [comment]
Ok, now I get it - you don't see it as 100% proof that disk was filled up by Syncthing sync process. Ok, maybe will try to reproduce again.
