### ISSUE TITLE
"kiB" should be "KiB"

### ISSUE THREAD

**Issue by Nnnes** [syncthing/syncthing#5017]
Easy one. `kiB` is capitalized incorrectly in device download/upload rates. `MiB`, `GiB`, and `TiB` are fine.

https://github.com/syncthing/syncthing/blob/b3007c03bd8356b9052e5c957760d186ac8bfa2e/gui/default/syncthing/app.js#L238-L244

**Comment by kozec** [comment]
Unless we are talking about kelvinbytes, kilo is lowercase "k".

**Comment by uok** [comment]
Thanks for reporting!
Please edit the file on Github and submit a pull request.

**Comment by ealib** [comment]
Just for future searches:

- [International System of Units (SI)](https://en.wikipedia.org/wiki/International_System_of_Units) is a standard which defines the prefix "kilo" (symbol "k") as 1000 (10<sup>3</sup>);
- [ISO 80000, or IEC 80000](https://en.wikipedia.org/wiki/ISO/IEC_80000), is a standard which defines the prefix "kibi" (symbol "Ki") as 1024 (2<sup>10</sup>).
