### ISSUE TITLE
Very Very Large Files will not Sync

### ISSUE THREAD

**Issue by athendrix** [syncthing/syncthing#5018]
- what happened,
 - what you expected to happen instead, and
 - any steps to reproduce the problem.

Also fill out the version information below and add log output or
screenshots as appropriate.

Syncthing Version: v0.14.48
OS Version: Windows Server 2012 R2
As I understand it, this is a known bug, due to Jakob Borg acknowledging its existence here:
https://forum.syncthing.net/t/syncthing-lims-caps/10011/14
And as such, it should be in the bug tracker.

In short, files that are large enough (>~1.25 TB) to warrant an index larger than 500 MB will fail because the max message size is 500 MB (and that is hard coded into the official versions)

It also appears that the consensus is that there are three possible ways of fixing this:
1. Increasing the max message size.
To be a solution, this would need to be an advanced option so those needing large files to sync could change it as necessary.
Note that this is not considered a good solution, but may serve as a band-aid solution.
2. Delta block sync + handling edge cases.
Since the issue occurs when attempting to transfer messages larger than 500 MB, this solution simply ensures that messages larger than 500 MB aren't transferred.
With delta block sync, changes that don't actually cause 500 MB index changes (e.g. changes smaller than 1.25 TB) will never trigger this problem.

On the other hand changes that are greater than 1.25 TB or initial file transfers greater than 1.25 TB WILL cause larger messages, and so those one-time transfers of large block changes would need to be transferred in a different way. So why not sync them the same as other files? e.g. send the block meta-data as though it were actual data if it would warrant a message larger than the limit.

3. This may be the simplest solution, but simply implementing Variable Block Size so large files don't have such large indices would also solve this.

As it stands, this actually breaks Syncthing for me. I want to use it to help backup large VMs, and while I realize I could compile my own version with a larger message size, that seems excessive to band-aid a solution to this serious bug.
(I realize others may not consider this a serious bug, but having an entire class of files that are unable to sync at ALL is pretty bad.
If they synced, but didn't sync efficiently, that'd be one thing.
If Syncthing didn't sync files > 1 TB by choice and advertised that as a limitation, that'd be another thing.
Correct me if I'm wrong, but Syncthing intends to be a universal syncing solution does it not?
So even if having very very large file support might not be useful for everyone, it seems core to Syncthing's goal, and it wouldn't be complete without it)

**Comment by imsodin** [comment]
You came here at the right moment: This is fixed by variable block size / #4707 which is included since 0.14.48. It isn't enabled by default because it is not backwards compatible, i.e. all devices need to enable it for it to work. You find the setting in the advanced menu for each folder.

**Comment by athendrix** [comment]
Nice! Thank you very much!

**Comment by athendrix** [comment]
Sorry to double post, but since it seems to be on a per-folder basis, maybe it could be auto-enabled only if files greater than 1.25 TB or so are found in the sync folder.
That would probably help with it not being backwards compatible, since it wouldn't work anyway.

**Comment by AudriusButkevicius** [comment]
It will be enabled in some future version when most of the population has rolled off the versions that are not compatible.
