### ISSUE TITLE
Very slow download speed

### ISSUE THREAD

**Issue by Enelar** [syncthing/syncthing#5019]
I have two devices. On both of them internet works perfectly. But when i try to sync folders, downloading speed is around 64 Bit/sec.

First one - rented paperspace P4000 server
Windows 10
8 Xeon CPU cores
30GB Ram
~180-230 Mbit/sec connection
HDD ~15MB/sec read

Second one - my laptop
Arch Linux
2 i3 cores
12GB Ram
Connected through 4G
~35-42 Mbit/sec connection
SSD ~70MB/sec write

Actual download rate: 0.05 - 0.06 Mbit/sec

**Comment by AudriusButkevicius** [comment]
Please read the issue template. Support is handled on the forum.
