### ISSUE TITLE
Suspend fails on Linux when Syncthing is running

### ISSUE THREAD

**Issue by ajays-in** [syncthing/syncthing#5020]
Suspend sometimes fails on Linux when Syncthing is running. System suspends successfully after Syncthing is stopped. This does not happen always or on every machine. But is irritating enough to warrant filing a bug report. Log dump from a previsouly failed suspend attempt is pasted below version information

Syncthing version: 0.14.47
Syncthing Tray app: QSyncthingTray v0.5.8
OS version: Manjaro rolling release
Kernel Version: 4.14.48-2-MANJARO

Log Dump:

PM: suspend entry (deep)
[ 9838.531101] PM: Syncing filesystems ... done.
[ 9841.782280] Freezing user space processes ... 
[ 9861.789184] Freezing of tasks failed after 20.006 seconds (2 tasks refusing to freeze, wq_busy=0):
[ 9861.791238] syncthing       D    0  1301   1273 0x00000004
[ 9861.791242] Call Trace:
[ 9861.791255]  ? __schedule+0x286/0x890
[ 9861.791265]  ? fuse_request_init+0x96/0xc0 [fuse]
[ 9861.791270]  schedule+0x2f/0x90
[ 9861.791276]  request_wait_answer+0xaa/0x1f0 [fuse]
[ 9861.791282]  ? wait_woken+0x80/0x80
[ 9861.791289]  __fuse_request_send+0x61/0x80 [fuse]
[ 9861.791297]  fuse_simple_request+0xcd/0x190 [fuse]
[ 9861.791304]  fuse_do_getattr+0x109/0x2f0 [fuse]
[ 9861.791314]  fuse_permission+0xf1/0x150 [fuse]
[ 9861.791320]  __inode_permission+0x6c/0xc0
[ 9861.791324]  link_path_walk+0x29a/0x520
[ 9861.791328]  path_lookupat.isra.49+0x97/0x200
[ 9861.791336]  ? fuse_change_attributes+0xbb/0x120 [fuse]
[ 9861.791340]  filename_lookup.part.69+0xa0/0x130
[ 9861.791346]  ? __check_object_size+0x9f/0x18e
[ 9861.791352]  ? strncpy_from_user+0x4a/0x170
[ 9861.791357]  vfs_statx+0x73/0xe0
[ 9861.791362]  SYSC_newlstat+0x39/0x70
[ 9861.791368]  do_syscall_64+0x67/0x100
[ 9861.791373]  entry_SYSCALL_64_after_hwframe+0x3d/0xa2
[ 9861.791377] RIP: 0033:0x4abb10
[ 9861.791379] RSP: 002b:000000c42044b3d0 EFLAGS: 00000202 ORIG_RAX: 0000000000000006
[ 9861.791383] RAX: ffffffffffffffda RBX: 0000000000000000 RCX: 00000000004abb10
[ 9861.791384] RDX: 0000000000000000 RSI: 000000c4226c7bd8 RDI: 000000c421979b90
[ 9861.791386] RBP: 000000c42044b438 R08: 0000000000000000 R09: 0000000000000000
[ 9861.791388] R10: 0000000000000000 R11: 0000000000000202 R12: 0000000000000000
[ 9861.791390] R13: 0000000000000040 R14: 000000000000003f R15: 0000000000000049
[ 9861.791394] syncthing       D    0  1306   1273 0x00000004
[ 9861.791397] Call Trace:
[ 9861.791402]  ? __schedule+0x286/0x890
[ 9861.791409]  ? fuse_request_init+0x96/0xc0 [fuse]
[ 9861.791413]  schedule+0x2f/0x90
[ 9861.791419]  request_wait_answer+0xaa/0x1f0 [fuse]
[ 9861.791423]  ? wait_woken+0x80/0x80
[ 9861.791430]  __fuse_request_send+0x61/0x80 [fuse]
[ 9861.791437]  fuse_simple_request+0xcd/0x190 [fuse]
[ 9861.791444]  fuse_do_getattr+0x109/0x2f0 [fuse]
[ 9861.791454]  fuse_permission+0xf1/0x150 [fuse]
[ 9861.791458]  __inode_permission+0x6c/0xc0
[ 9861.791461]  link_path_walk+0x29a/0x520
[ 9861.791466]  path_lookupat.isra.49+0x97/0x200
[ 9861.791473]  ? fuse_change_attributes+0xbb/0x120 [fuse]
[ 9861.791477]  filename_lookup.part.69+0xa0/0x130
[ 9861.791481]  ? __check_object_size+0x9f/0x18e
[ 9861.791485]  ? strncpy_from_user+0x4a/0x170
[ 9861.791490]  vfs_statx+0x73/0xe0
[ 9861.791494]  SYSC_newlstat+0x39/0x70
[ 9861.791500]  do_syscall_64+0x67/0x100
[ 9861.791503]  entry_SYSCALL_64_after_hwframe+0x3d/0xa2
[ 9861.791505] RIP: 0033:0x4abb10
[ 9861.791507] RSP: 002b:000000c421055550 EFLAGS: 00000206 ORIG_RAX: 0000000000000006
[ 9861.791511] RAX: ffffffffffffffda RBX: 0000000000000000 RCX: 00000000004abb10
[ 9861.791512] RDX: 0000000000000000 RSI: 000000c421976c68 RDI: 000000c420f00000
[ 9861.791514] RBP: 000000c4210555b8 R08: 0000000000000000 R09: 0000000000000000
[ 9861.791516] R10: 0000000000000000 R11: 0000000000000206 R12: 0000000000000000
[ 9861.791518] R13: 0000000000000033 R14: 0000000000000033 R15: 0000000000000033
[ 9861.791577] OOM killer enabled.
[ 9861.791578] Restarting tasks ... done.
[ 9861.809630] video LNXVIDEO:00: Restoring backlight state
[ 9861.810481] PM: suspend exit

**Comment by calmh** [comment]
There's a lot of fuse stuff in that backtrace; I suspect you are barking up the wrong tree. Syncthing does nothing special to refuse or enable "freezing", so I don't see how this could be our issue. I'm going to close, but if there's something I don't understand that make me wrong please feel free to yell.

**Comment by ajays-in** [comment]
Thanks Jakob. Closing syncthing after the aborted suspend resolves the problem and machine is suspended sucessfully. So thought this could be a syncthing (driving fuse in the background ) issue. Meanwhile do let me know if there is anything else I can do to help narrow down the problem next time this occurs if this somehow relates to syncthing

**Comment by calmh** [comment]
Oh I don't doubt that Syncthing causes the issue, but all it does it normal file I/O. To me that means that FUSE is the likely root cause / culprit and where the bug report should go.
