### ISSUE TITLE
Generation of sync-conflict files, when only one side changes

### ISSUE THREAD

**Issue by DamienCassou** [syncthing/syncthing#5033]
I sometimes get sync-conflict files for files that are only modified in one device (I use Syncthing to regularly copy changing files to non-changing destinations as a initial first-level backup).

 - what happened: I got a sync-conflict file
 - what you expected to happen instead: no conflict file as just one device changed the file
 - any steps to reproduce the problem: don't know but it regularly happens

### Version Information

    App Version: 0.14.48-dirty (f-droid)
    Syncthing Version: v0.10.11
    Android Version: Android 8.1.0 / LineageOS 15.1 (nightly, updated today)

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
