### ISSUE TITLE
[Feature Request] Manual Sync button

### ISSUE THREAD

**Issue by BNolet** [syncthing/syncthing#5046]
I'd like to be able to manually initiate a sync session by pressing a "sync" button. The time it takes to do initial syncs between devices, and whatnot just isn't great if someone needs to quickly leave and are saving their stuff right before leaving.

**Comment by AudriusButkevicius** [comment]
See closed issues.

**Comment by BNolet** [comment]
@AudriusButkevicius I couldn't find anything related :confused:

**Comment by calmh** [comment]
Yeah me neither, nonetheless this is a "don't want" feature as Syncthing is designed around the concept of automatic, continuous synchronization. You can also use the pause feature.

**Comment by BNolet** [comment]
Ah no, I'm not asking for that to be the only way to sync, just a way to force a sync when pressed. I can understand why it wouldn't be wanted though
