### ISSUE TITLE
notify: intermittent test failures depending on system load

### ISSUE THREAD

**Issue by decathorpe** [syncthing/syncthing#5052]
The test suite for `github.com/syncthing/notify` fails non-deterministically. Since it looks like this depends on system load, it might be a race condition in either the library or the test code itself.

(I'm reporting this issue here since your `notify` repository doesn't have issues enabled :frowning_face:)

I get error messages like the following (reformatted for better legibility):

```
$ go test (.. snip ..) github.com/syncthing/notify

--- FAIL: TestWatcherInotify (0.56s)

testing_test.go:219: testing_test.go:464: ExpectAny received an event which does not match any of the expected ones (i=2):
	
want one of

[&notify.Call{F:"", C:(chan notify.EventInfo)(nil), P:"src/github.com/rjeczalik/fs/fs.go", NP:"", E:0x1, NE:0x0, S:interface {}(nil), Dir:false}
 &notify.Call{F:"", C:(chan notify.EventInfo)(nil), P:"src/github.com/rjeczalik/fs/fs.go", NP:"", E:0x20, NE:0x0, S:interface {}(nil), Dir:false}
 &notify.Call{F:"", C:(chan notify.EventInfo)(nil), P:"src/github.com/rjeczalik/fs/fs.go", NP:"", E:0x2, NE:0x0, S:interface {}(nil), Dir:false}
 &notify.Call{F:"", C:(chan notify.EventInfo)(nil), P:"src/github.com/rjeczalik/fs/fs.go", NP:"", E:0x10, NE:0x0, S:interface {}(nil), Dir:false}];
 
got

 notify.InCloseWrite: "/builddir/build/BUILDROOT/golang-github-syncthing-notify-0-0.2.20180708gitcdf89c4.fc29.aarch64/usr/share/gocode/src/github.com/syncthing/notify/testdata/199727849/src/github.com/rjeczalik/fs/fs.go"

FAIL
FAIL	github.com/syncthing/notify	22.038s
```

### Version Information

github.com/syncthing/notify commit: cdf89c4
OS Version: fedora rawhide

**Comment by calmh** [comment]
The notify package is a thin fork of https://github.com/rjeczalik/notify<https://godoc.org/github.com/rjeczalik/notify> which is where this issue should probably be reported, unless you are sure it is introduced in the fork?

**Comment by AudriusButkevicius** [comment]
I think these tests are timing sensitive and there is no way around it, as you can't force the kernel to deliver the events faster. Regardless, the previous comment is correct that you are barking up the wrong tree.

**Comment by decathorpe** [comment]
Okay, fair point. If this turns out to be a real issue I will report this "upstream". Thanks
