### ISSUE TITLE
Unignored file not considered needed

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#5053]
@AudriusButkevicius @calmh This is yet another issue introduced in https://github.com/syncthing/syncthing/pull/4958 and thus 0.14.49 material - I am really sorry about that disaster and slow piece-by-piece resolution. It also needs another db transition while there is already one on master, that's not in release - I will file separate PRs for master and release branches to address that. Regarding release schedules: May it be reasonable to delay 0.14.50, but already release 0.14.51-rc.1 as normal?

Originally came up in https://forum.syncthing.net/t/did-something-recently-changed-in-ignores-handling/11714/35

Steps to reproduce:

1. Share a folder between devices A and B.
2. Modify file F on A, wait for sync.
3. Modify file F on B, wait for sync.
4. Ignore F on A.
5. Edit F on A and B.
6. Unignore F on A.

Expected: Create and sync conflicts.

Actual: Nothing is synced and no conflicts are created.

**Comment by calmh** [comment]
I prefer to keep things linear, release a new 49 RC, and push the schedule forwards. There is no rush to get 50 out. (In the car, so not reviewing at the moment.)
