### ISSUE TITLE
Can't remove old inexistent device even after removing the inctroducer flag from every active device

### ISSUE THREAD

**Issue by jbmorgado** [syncthing/syncthing#5058]
I deleted an old device and I am trying to remove it from syncthing.

I followed the supposed procedure which is to remove the introducer flag from every active device (I have 3), but I still can't delete the old device since every existing one says that it will be reintroduced by one of the other devices.

### Version Information

Syncthing Version: v0.14.48
OS Version: Linux (64 bit)

**Comment by AudriusButkevicius** [comment]
Define "active devices". You need to disable introducer flag from the device that introduced that device, not just any "active" set of devices (whatever active means in this context). If memory serves me right, you can hover on the delete button it should tell you which device is the introducer.

Anyways, this should be on the forum until we get to the details and identify the bug, if any.
