### ISSUE TITLE
syncthing cannot delete directory that contains only an .stignored file

### ISSUE THREAD

**Issue by jpjp** [syncthing/syncthing#506]
On the Mac laptop I have:

```
$ cat .stignore
.DS_Store
```

Then I have a directory and some files:

```
blah/.DS_Store
blah/one
blah/two
blah/three
```

On the other side I have a Linux box, and I delete

```
rm blah/one
rm blah/two
rm blah/three
```

Then I delete

```
rmdir blah
```

Back on the Mac side, there is an error in the gui that blah/ cannot be deleted since it is not empty (it contains .DS_Store).

On the Linux side the blah directory gets recreated.

I understand why this all happens, but is this intended behaviour? :)

**Comment by ManuelSchneid3r** [comment]
Wait, this happens too if a .DS_Store is in the directory and they are ignored by the .stignore in the root.

**Comment by calmh** [comment]
No, see `(?d)` and don't revive several years old issues please
