### ISSUE TITLE
Backlog of 70000+ non-existing files being synced

### ISSUE THREAD

**Issue by bigbrotherfarm** [syncthing/syncthing#5061]
My setup:
- Security cameras upload photos to a server in a remote location.
- Server runs Syncthing and syncs the last hour of photos to other devices
- Server has a bash script that deletes any files older than an hour
- Four other devices receive these photos in another location.

The folder has always been "out of sync" with a few files according to the Syncthing dashboard, even though the last hour of images are there just like expected. Recently the amount on unsynced files has increased to 70000+. These are all 0 byte files from the last 30 days or so. This syncing process seems to go on eternally.

First it didn't really matter but now the amount of unsynced 0 byte files has rendered the folder unusable. No new files are being synced.

I suspect the file deleting bash script is the culprit but it shouldn't be. I have set the folder rescan on 30 seconds on all devices and the script on the server runs only every five minutes. Unfortunately the folder rescan seems to revert back to 3600 seconds anyway after a while.

I've also tried to exclude old files from being synced but that only causes all syncing to cease.

You can check out my on-going project with more comments here: https://bigbrotherfarm.github.io/

**Comment by AudriusButkevicius** [comment]
Please read the issue template explaining how support requests are dealt with.
