### ISSUE TITLE
panic: cannot start already running folder

### ISSUE THREAD

**Issue by JulienPalard** [syncthing/syncthing#5063]
Tried to add a third shared folder between my phone and my laptop. Initiated the share from my phone, Syncthing paniced on my laptop, and now synthings panics while starting.

### Version Information

- syncthing v0.14.48 "Dysprosium Dragonfly" (go1.10.2 linux-amd64) teamcity@build.syncthing.net 2018-05-14 06:53:06 UTC
- On Debian buster

### Error logs

```
[...]
17:47:03 INFO: Adding folder "Caméra" (nexus_6p-photos)
Panic at 2018-07-11T17:47:03+02:00
panic: cannot start already running folder nexus_6p-photos
[...]
```

**Comment by AudriusButkevicius** [comment]
Check your config, you probably have two folders with the same id.

**Comment by JulienPalard** [comment]
Hi @AudriusButkevicius and thanks for your prompt answer, greatly appreciated!

I though id were auto-generated, I just checked android-side and (if I get it right) I have 4 shares, which ids are:

- nexus_6p-photos
- default
- mv3sz-cniao
- 5z1xy-bg5iv

I don't know how to check the ids on my computer as the app won't start from now, but the app started to crash when I added a directory from my phone, and I have only two devices : my laptop and my phone.

I do not see an id conflict, please re-open.

(I'm new to syncthing, I don't expect a software to panic on an error you can make me fix by telling me a single simple line, please re-open the issue. It may not be an issue as you understand it, but it's at least an UX issue that needs to be fixed, I mean, my mother won't be able to use a software that crash and don't tell how to recover on simple errors, she won't be able to write english on a forum or whatever).

Bests

**Comment by AudriusButkevicius** [comment]
The discussion on this working out the issue should happen on the forum, so this will not be reopened until we work out the actual cause so there is a concrete thing to fix.

**Comment by JulienPalard** [comment]
Sorry to report issue.

**Comment by AudriusButkevicius** [comment]
Every potential bug should first be debugged and understood in the forum, unless you know exactly what the cause is and what has to be fixed.

**Comment by calmh** [comment]
I disagree; a panic is a bug, and we should have an open ticket on it regardless of not yet understanding the root cause.

**Comment by AudriusButkevicius** [comment]
Sure, lets leave this to rot eternally then. 

For all that I know the user might have edited the config by hand and caused this. Is it still a bug in that case? 

That's why this needs a conversation on the forum first, as this just talks about consequences, not the details how this happened.

**Comment by calmh** [comment]
I don't see how a manual config edit could possibly result in this. I've seen the opposite error (panic when starting non-existent folder) because one part of the code looks in the (a?) global config object and another uses the folder config passed from the change event. I wouldn't be surprised if this was similar.

**Comment by AudriusButkevicius** [comment]
That would be a one-off crash, not repeated after restart. 

This implies the config is screwed. 

It's perfectly possible that we screw the config, yet we need the config, potentially the logs, the user needs to try X then try Y then report feedback if it fixed issue etc, which potentially helps us understand the cause, for which the forum is a much more suitable medium until we understand whats happening and then can reasonably quantify the problem and raise a work item.

**Comment by pitlochry** [comment]
got exactly same error on syncthing v0.14.48 "Dysprosium Dragonfly" (go1.10.3 linux-arm) 
and i didn't edit the config by hand, every folder has different id.
now i search the forum for this bug.

**Comment by AudriusButkevicius** [comment]
Every folder has a different id in the current config with which it fails to start up?

**Comment by pitlochry** [comment]
yes, 
    <folder id="default" ...
    <folder id="hmq9d-srckx" ...
    <folder id="xr4sr-p5mkh" ...

**Comment by pitlochry** [comment]
I set syncthing (and the whole system) up from scratch yesterday on arch linux arm.
The only setting I changed in the web-GUI was: Remote Devices->Edit->Auto Accept.
And so I think "Auto Accept" is buggy which complies with [weird errors and crash, new folders dont sync on new simple setup](https://forum.syncthing.net/t/weird-errors-and-crash-new-folders-dont-sync-on-new-simple-setup/11720/10)

**Comment by AudriusButkevicius** [comment]
If you disable auto-accept in the config, does it fix itself?

**Comment by AudriusButkevicius** [comment]
RIght, can you re-enable, post full log from stdout and post your config?

**Comment by pitlochry** [comment]
Reenabled auto-accept, 
started syncthing -> stdout: [stdout_beforeaddingfolderviaautoaccept.log](https://github.com/syncthing/syncthing/files/2195780/stdout_beforeaddingfolderviaautoaccept.log)
added a folder ("test3" with folder id "cvdpz-luehs") -> stdout: [stdout_afteraddingfolderviaautoaccept.log](https://github.com/syncthing/syncthing/files/2195779/stdout_afteraddingfolderviaautoaccept.log)
line4 shows the bug: syncthing adds a folder which is already shared "Idstein..." (xr4sr-p5mkh) and not the folder it should add, i.e. "test3" (cvdpz-luehs), then panic is detected, cpu stays permanently at 100%.
line1: is it normal, that the connection between the two clients (the one which adds the folder and the one which should auto-accept it) is disconnected?

**Comment by AudriusButkevicius** [comment]
Can you run with this build:
(windows)
https://build.syncthing.net/viewLog.html?buildId=24061&buildTypeId=Syncthing_BuildWindows&tab=artifacts
(crosscompiled)
https://build.syncthing.net/viewLog.html?buildId=24060&buildTypeId=Syncthing_BuildLinuxCross&tab=artifacts

Once it completes, and provide full logs once more, thanks.

**Comment by pitlochry** [comment]
As far as I can see: Panic occurs from the second auto-accepted folder (like above 14.48 and like above tries to add already shared folder), but it panics only once for each auto-accepted folder, then it restarts and everything seems to work.
log: [stdout14.49-rc.4+5.log](https://github.com/syncthing/syncthing/files/2195990/stdout14.49-rc.4%2B5.log)

line42: adding test1 (no panic)
line97: adding test3 (panic) [panic-20180715-201212.log](https://github.com/syncthing/syncthing/files/2195992/panic-20180715-201212.log)
line258: adding test4 (panic)
line516: adding test5 (panic)

**Comment by AudriusButkevicius** [comment]
Please try the build from https://github.com/syncthing/syncthing/pull/5067 once it rolls off.
Please remove all extra folders, and just leave the one that was crashing, as it's getting hard to read.

**Comment by pitlochry** [comment]
Has #5067 already rolled off? I can't find the build, or do I have to built it on my own? Sorry I'm a github noob.

**Comment by AudriusButkevicius** [comment]
https://build.syncthing.net/viewLog.html?buildId=24078&buildTypeId=Syncthing_BuildLinuxCross

The build URL is in the collapsed checks section

**Comment by pitlochry** [comment]
I followed the links and took this [build](https://build.syncthing.net/viewLog.html?buildId=24078&buildTypeId=Syncthing_BuildLinuxCross&tab=artifacts)

Behaviour from last build didn't change. It panics only once from the overall fourth folder on (no matter if the first three folders were auto-accepted or manually), and it then always tries to add the second folder. 
This is a good workaround vs. 14.48, because panic only occurs once for each folder and not in an infinite loop. Best would be without panic (syncthing exits and restarts after each panic).
[20180716.log](https://github.com/syncthing/syncthing/files/2199258/20180716.log)

**Comment by AudriusButkevicius** [comment]
Thanks, I now understand what the problem is, and I have a hunch why it happens. Let me produce one last build to verify my idea.

**Comment by AudriusButkevicius** [comment]
You'll find a link to the latest build, in this pull request by expanding the checks section and clicking on the `Linux, Cross` build.

https://github.com/syncthing/syncthing/pull/5067

**Comment by pitlochry** [comment]
I'm sorry but panic occured from the sixth auto-accepted folder (with the default folder the seventh folder in total) onwards. [log](https://github.com/syncthing/syncthing/files/2200868/log.log) and first [panic-20180717-093608.log](https://github.com/syncthing/syncthing/files/2200871/panic-20180717-093608.log)

**Comment by AudriusButkevicius** [comment]
Can you try the build from https://github.com/syncthing/syncthing/pull/5069 and see if you can repro?

**Comment by pitlochry** [comment]
I tried #5069 and there is not a single panic-loop, not a single panic, not a single restart.
This bug seems to be fixed. I tried more than 10 auto-accept folder from linux, windows and more ... [(logs)](https://github.com/syncthing/syncthing/files/2201463/o1.log)

Thank you for fixing and for your patience. For me it was the first time on github. 
[I think I found another minor bug with send-only folders and versioning... perhaps on the forums]

Thanks for all your work.

**Comment by spicedreams** [comment]
I am finding that just 1 machine is suddenly getting these panics (of 4 machines all with 0.14.48 on Linux Mint 18.3).
The panic occurs with the last <folder ... > ... </folder> block in config.xml. If I remove that last block, then the panic occurs on the new last <folder>. I have removed 3 last folders sequentially now; the result is always the same, the new last <folder> is identified as 'already running' and syncthing panics.
I don't think I use auto-accept at all, so I don't know if this is the same problem as above. When I remove a <folder> block from config.xml, for the few minutes that syncthing stays running, it gets proposals to re-introduce the folder from a couple of other machines.
Hope this helps...

**Comment by calmh** [comment]
@spicedreams panic trace?

**Comment by spicedreams** [comment]
I am finding that just 1 machine is suddenly getting these panics (of 4 machines all with 0.14.48 on Linux Mint 18.3).
The panic occurs with the last <folder ... > ... block in config.xml. If I remove that last block, then the panic occurs on the new last . I have removed 3 last folders sequentially now; the result is always the same, the new last is identified as 'already running' and syncthing panics.
I don't think I use auto-accept at all, so I don't know if this is the same problem as above. When I remove a block from config.xml, for the few minutes that syncthing stays running, it gets proposals to re-introduce the folder from a couple of other machines.
sorry, got some more information and could not edit my first post so I have deleted and re-added it here...
When I re-added the <folder ...> blocks I had removed, the panic started ocurring in the second to last block. 
file:///home/graham/.config/syncthing/panic-20180722-184410.log

**Comment by spicedreams** [comment]
damn, drag & drop does not seem to have attached the panic log. Trying again...

**Comment by spicedreams** [comment]
[panic-20180722-184410.log](https://github.com/syncthing/syncthing/files/2216770/panic-20180722-184410.log)
here we go...

**Comment by spicedreams** [comment]
Additional information: I upgraded all my systems to Syncthing v0.14.49, The same computer as before has the same problem as before, ie panics trying to add a folder:
[JCQPR] 19:01:58 INFO: Adding folder "professional" (zcd6n-5g9pm)
panic: cannot start already running folder zcd6n-5g9pm
[monitor] 19:01:58 WARNING: Panic detected, writing to "/home/graham/.config/syncthing/panic-20180725-190158.log"
log attached...
[panic-20180725-190158.log](https://github.com/syncthing/syncthing/files/2226857/panic-20180725-190158.log)
