### ISSUE TITLE
/rest/db/browse does does not respect prefix

### ISSUE THREAD

**Issue by tsaridas** [syncthing/syncthing#5075]
After trying the get call as described here

https://docs.syncthing.net/rest/db-browse-get.html

I was unable to get the files located on a specific prefix.

curl -s http://localhost:8384/rest/db/browse?folder=default&prefix=directory/subdirectory

Instead I still get the files on the root of the directory (default).

levels parameter seems to be working fine though.

### Version Information

Syncthing Version: v0.14.48
OS Version: centos6

**Comment by imsodin** [comment]
I can't reproduce. It works as intended (only items below prefix) for me on both v0.14.48 and master on debian (I don't see any reason why the distro should matter). The only thing that comes to mind: Did you put the url in single brackets or did you escape the `&`?

**Comment by tsaridas** [comment]
I'm using curl as in the example I provided with & separator.

I might be doing something wrong. 

Just to confirm, prefix is a folder inside the shared folder and the get request should only return whatever is in that folder.

example 
folder1/file
folder1/directory

**Comment by calmh** [comment]
Do what imsodin suggests. Your shell is probably taking the ampersand as the backgrounding character, cutting off the command at that point.

**Comment by tsaridas** [comment]
@calmh I have also tried from a python script and have the url in single brackets with no success

as I said, other api calls that use '&' work fine and also levels in the same command works fine and I get a correct result.

**Comment by tsaridas** [comment]
I figured I need to have prefix as a first parameter and then add folder.

**Comment by calmh** [comment]
```
jb@kvin:~ $ curl -sH X-API-Key:... 'http://localhost:8385/rest/db/browse?folder=lightroom' | head
{
  ".com.apple.backupd.mdmv2592243": [
    "2017-10-24T12:49:20+02:00",
    548
  ],
  "Backups": {
    "2018-01-27 0115": {
      "Lightroom Catalog.lrcat.zip": [
        "2018-01-27T01:15:41.927278757+01:00",
        167961760
jb@kvin:~ $ curl -sH X-API-Key:... 'http://localhost:8385/rest/db/browse?folder=lightroom&prefix=Backups' | head
{
  "2018-01-27 0115": {
    "Lightroom Catalog.lrcat.zip": [
      "2018-01-27T01:15:41.927278757+01:00",
      167961760
    ]
  }
}
```

**Comment by tsaridas** [comment]
I dunno what to say .. 
anyhow, my problem is solved. 
Thank you all for the replies.
