### ISSUE TITLE
Why should the global size containing a receiveonly directory size?

### ISSUE THREAD

**Issue by xjtdy888** [syncthing/syncthing#5082]
https://github.com/syncthing/syncthing/blob/93fdd1c012ca64470829fbf68bb5bb6193907c35/lib/db/set.go#L270
```go
func (s *FileSet) GlobalSize() Counts {
	global := s.meta.Counts(protocol.GlobalDeviceID, 0)
	recvOnlyChanged := s.meta.Counts(protocol.GlobalDeviceID, protocol.FlagLocalReceiveOnly)
	return global.Add(recvOnlyChanged)
}
```

Each node shows the global size (containing some nodes'  receiveonly). This disturbs the correct information because we don't know why the local size is less than the global size

**Comment by calmh** [comment]
I'm sorry, I don't understand the question. "global" above is the size of the files without any flags. "recvOnlyChanged" is the size of files that have the receive only changed flag. The sum of things on disk is the sum of those.

**Comment by calmh** [comment]
Anyway, unless this is a bug report in disguise, please use the forum for questions and discussions.
