### ISSUE TITLE
lib/fs: Disable symlink support on Android internal storage

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#5083]
Because it's now compiled with GOOS=android and we know the root of the filesystem, we can check if symlinks are supported or not. There is a check `runtime. GOOS == "windows && file.IsSymlink()` which should probably be translated into `!fs.SymlinksSupported() && file.IsSymlink()`

**Comment by calmh** [comment]
I think Audrius is proposing that we probe it, maybe at folder startup. I’m not immediately clear on what the difference is between failing to sync a symlink because it doesn’t work and failing to sync a symlink because it’s not supported. The error message?

**Comment by AudriusButkevicius** [comment]
So the original user did not provide the error, but its possible that link syscall just fails on internal storage. Anyways, I'll actually close this, perhaps the original user reopen/comment with the actual error, as its not clear what we are fixing here.

**Comment by jpsutton** [comment]
I'm running Syncthing on Android and any time one of my laptops adds a symlink (example: I create a python virtualenv inside my sync folder), the Android phone goes to "Out of Sync" status.  Running "adb logcat" while adding a symlink on my laptop, I see the following error:

08-30 16:38:49.449  7090 20334 I SyncthingNativeCode: [OHVZF] INFO: Puller (folder "Default" (default), file "test.txt"): symlink create: symlink /home/jpsutton/test.txt /storage/emulated/0/Sync/test.txt: operation not permitted

The suggestion from the OP to check if the filesystem supports symlinks before attempting to sync a symlink would seem to make sense.

**Comment by calmh** [comment]
@jpsutton but the difference would be that you are then out of sync and see the following error:

```
08-30 16:38:49.449 7090 20334 I SyncthingNativeCode: [OHVZF] INFO: Puller (folder "Default" (default), file "test.txt"): symlink create: symlink /home/jpsutton/test.txt /storage/emulated/0/Sync/test.txt: symlinks not supported
```

That may be fractionally clearer, but not a huge difference imho.

**Comment by jpsutton** [comment]
That's a fair point, but I'm not going for changing the error message.  I'm attempting to improve the behavior of syncthing when it encounters a symlink. As of right now, it's attempting to replicate a symlink to an external entity (something outside the sync folder), which doesn't really make sense.

Perhaps my use case is uncommon, but it seems like symlinks should be treated differently depending on where the target of the link is AND whether or not the various remote devices support symlinks.  Example:

Psuedo-code:
```
if link target is inside the sync folder structure:
  if remote device supports symlinks
    sync the symlink natively
  if remote device doesn't support symlinks:
    don't sync the link
    report "out of sync"
    have an option on that remote device to ignore symlink errors
if target of the link is outside the sync folder structure
  ignore the symlink altogether
```

**Comment by AudriusButkevicius** [comment]
This does not make sense. Symlink target is just data, regardless of where it points to

**Comment by jpsutton** [comment]
@AudriusButkevicius Can you elaborate? What specifically doesn't make sense?  Are you suggesting that a symlink inside a syncthing share folder pointing to something outside the share folder should be treated the same as any other file?  If so, how do you deal with syncthing nodes that don't support symlinks (in this case, an Android phone using internal storage, which is very common)?  And even if it supports symlinks, do you create an invalid symlink on that system or replicate the target file's contents to the other node?

I don't believe that syncthing's current handling of symlinks makes sense, as simply expecting a user to be okay with "Out of sync" or having to manually intervene by excluding those files one-by-one is a terrible user experience.

**Comment by AudriusButkevicius** [comment]
Symlink target, where it points to, is just bytes of data, ala content. Syncthing should not behave differently because of different file content.

I don't see why a symlink pointing to something that does not exist on a different machine should not be synced. Rsync syncs it, so should we.

There are so many filesystems under the sun, we can't know ahead of time know if stuff is supported or not. 

I think out of sync is the right behaviour, as essentially the data that we are supposed to sync fails to sync, hence the user should do something about, the same way user has to deal with too long filenames, characters that are not supported and so on.

**Comment by Ferroin** [comment]
I would tend to agree with @AudriusButkevicius on this one.

It's important to realize that what the symlink is pointing at (even if it's dangling), or even the fact that it is a link, may have actual meaning independent of the content of the target, and thus the link does need to be preserved (because Syncthing can't tell if it's significant or not).  That in turn means that the folder being out-of-sync is correct, because not all the data that Syncthing needs to replicate is replicated.
