### ISSUE TITLE
Feature Request: Truncate and write instead of copy and new on config file schema updates

### ISSUE THREAD

**Issue by kael-shipman** [syncthing/syncthing#5086]
This is a somewhat esoteric request, but here's my scenario:

I keep syncthing config files for each of my machines in my own backed-up file hierarchy so that I can easily recreate my systems if necessary (for example, on hard drive failures, etc.). I _don't_ keep the whole syncthing config folder there because I consider the sync database to be runtime data that I don't need to back up.

To make this setup work, I symlink my config file into the syncthing config directory on machine setup like so:

```sh
cd ~/.config/syncthing
rm config.xml
ln -s ~/Runtime/Config/syncthing/home.config.xml config.xml
```

However, I just discovered today (tragically) that when syncthing updates config file schema, it _copies_ the current file to `config.xml.vX`, then _creates a new config file_ and merges the backed up config into it. That means that it silently unlinks itself from my backups, and I continue to use it as normal until my system goes down (which happened today) and I discover that the config file was unlinked after the very first update months ago and I have to go back and recreate all of my config.

**My proposal is that, instead of copying the old config file and creating a new one, we copy the old config file, _truncate_ the current file, leaving its inode in place, then write the new config over it using the same merge strategy already employed.**

I believe this change to be pretty minimal and pretty unoffensive. While I'm a total GoNoob, I'd be willing to try my hand at it and submit a PR if someone wants to approve my proposal or work with me on a better solution.

### Current Version Information

Syncthing Version: v0.14.48
OS Version: Raspbian 9.4

**Comment by AudriusButkevicius** [comment]
There is already an existing ticket talking about something like this. 

Essentially this is immensly complicated and I doubt will happen soon. We'd have to maintain a WAL to recover from being killed half way through a write, which would look a like a usee change next time we start up.

**Comment by calmh** [comment]
This speaks about the config file, not synced files. Regardless the answer is no. The current scheme accomplished a specific goal: at no point in time is there a broken config.xml in place. This is a property we want to preserve.

**Comment by kael-shipman** [comment]
Ok, thanks for the comments. I use syncthing daily and greatly appreciate your work on it. Keep fightin the good fight ;).
