### ISSUE TITLE
[Feature request] Split config into version control-friendly dotfiles

### ISSUE THREAD

**Issue by rieje** [syncthing/syncthing#5088]
It looks like Syncthing's config includes machine-specific information such as unique IDs. How about splitting the config into two files--one for actual settings that are not specific to one machine and another for containing information like unique IDs? Then you can version control the non-machine-specific settings. 

This would save a lot of time every time I set up Syncthing on different machines (especially on a Raspberry Pi where I would need to plug in mouse, keyboard, and HDMI in order to change the settings via the GUI. Ideally, I can simply clone the config, change the non-machine-specific settings if necessary, and edit the ID on (another?) file.

**Comment by calmh** [comment]
Can you provide an example of how you're thinking the split would look, exactly? It's not clear to me what distinction you're making.

**Comment by Ferroin** [comment]
Based on what he's saying, I believe he's talking about the `options` and `gui` sections.   Those rarely (if ever) change once the system is configured, and other than the API key, are rarely different between nodes.  In contrast, the `device` and `folder` entries may change for things that aren't even configuration from an end-user perspective, and each one is going to be slightly different between nodes, which makes it a pain in the arse to try and put the config file as a whole under any kind of centralized version control.

**Comment by Ferroin** [comment]
I think you mean that there are things in `options` that are machine specific for a typical deployment scenario.  If, however, you have a dozen identical systems (same hardware, same software, only differences are host names and network addresses), there's no reason that anything in the `options` section other than the `urUniqueID` tag needs to be any different (and if you have opted out of usage reporting, even that doesn't need to be different).

That said, I think configuration templating would probably serve the OP better based on what is being asked for, and that is decisively beyond the scope of Syncthing.
