### ISSUE TITLE
Problem with the servers!

### ISSUE THREAD

**Issue by BEdenhofer** [syncthing/syncthing#5091]
### DO NOT REPORT SECURITY ISSUES IN THIS ISSUE TRACKER

Instead, contact security@syncthing.net directly - see
https://syncthing.net/security.html for more information.

### DO NOT POST SUPPORT REQUESTS OR GENERAL QUESTIONS IN THIS ISSUE TRACKER

Please use the forum at https://forum.syncthing.net/ where a large number of
helpful people hang out. This issue tracker is for reporting bugs or feature
requests directly to the developers. Worst case you might get a short
"that's a bug, please report it on GitHub" response on the forum, in which
case we thank you for your patience and following our advice. :)

### Please use the correct issue tracker

If your problem relates to a Syncthing wrapper or [sub-project](https://github.com/syncthing) such as [Syncthing for Android](https://github.com/syncthing/syncthing-android/issues), [SyncTrayzor](https://github.com/canton7/synctrayzor) or the [documentation](https://github.com/syncthing/docs/issues), please use their respective issue trackers.

### Does your log mention database corruption?

If your Syncthing log reports panics because of database corruption it is most likely a fault with your system's storage or memory. Affected log entries will contain lines starting with `panic: leveldb`. You will need to delete the index database to clear this, by running `syncthing -reset-database`.

### Please do post actual bug reports and feature requests.

If your issue is a bug report, replace this boilerplate with a description
of the problem, being sure to include at least:

 - what happened,
 - what you expected to happen instead, and
 - any steps to reproduce the problem.

Also fill out the version information below and add log output or
screenshots as appropriate.

If your issue is a feature request, simply replace this template text in
its entirety.

### Version Information

Syncthing Version: v0.x.y
OS Version: Windows 7 / Ubuntu 14.04 / ...
Browser Version: (if applicable, for GUI issues)

When I launch syncthing, what happen's is, sometimes, I receive an error message saying, that I have no internet connection, or syncthing seems to be down! retrying, and then it connects. And when you go to sync big files, it doesn't get to 100 percent, it just hangs.

**Comment by AudriusButkevicius** [comment]
Read the issue template.

**Comment by BEdenhofer** [comment]
Send me the issue template then! let me politely explain something to you, I'm totaly blind, I do beta testing for NVAccess, the company that makes the free open source screenreader for NVDA for microsoft windows, and those guys take the time to help me.

**Comment by calmh** [comment]
It's at the top of your issue; perhaps it's not accessible for some reason. Nonetheless the point is that support requests are handled on https://forum.syncthing.net/ and not in the issue tracker. Thanks.
