### ISSUE TITLE
File watcher misses deletions if file is moved across shared folders

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing#5092]
Reproducer
I created the file mentioned on the screenshot below under path "D:/Dokumentation/Zutrittskontrolle" (share level is "D:/Dokumentation").
- File showed correctly as added during ~ 10 seconds.
I moved the file to "D:/Installationsdateien" (top level of another share). Both shared folders reside on the same disk.
- It showed correctly as added during ~ 10 seconds.
I expected the file to show up as "deleted" in "D:/Dokumentation" shared folder and this did not happen.
I waited for 3 minutes to make sure the file watcher has enough time but nothing happened.

Rescan interval of both shares is configures 3600 seconds. I hit the "Rescan now" button and the deletion notice appeared almost immediately. (compare to screenshot's top line)

Went to the syncthing menu and looked through the log, no clue where this bug came from as during testing with the reproducer no new log line came up. Restarted syncthing and again did the reproducer. Problem persists.

Screenshot of recent changes popup dialog
![image](https://user-images.githubusercontent.com/16361913/43511274-480600b4-9578-11e8-9a66-2e4b381c3c62.png)

### Version Information
Syncthing Version: v0.14.49
OS Version: Windows 10 x64
Browser Version: Chrome 63.0.3239 x64

**Comment by Catfriend1** [comment]
I again tried to do the reproducer, but now I only get "modified" instead of "file added". I deleted the "test file" beforehand but somehow it didn't get totally removed from the index? This time, I had more log facilities on:

![image](https://user-images.githubusercontent.com/16361913/43511606-186b284c-9579-11e8-9fd8-098b2c5c4544.png)


> 2018-08-01 10:50:43 aggregator/"Dokumentation" (cdaf2-v5ayb): No old fs events
2018-08-01 10:50:43 aggregator/"Dokumentation" (cdaf2-v5ayb): Resetting notifyTimer to 10s
2018-08-01 10:50:51 aggregator/"Installationsquellen" (n4q4z-ohpfz): No tracked events, waiting for new event.
2018-08-01 10:50:53 aggregator/"Dokumentation" (cdaf2-v5ayb): No old fs events
2018-08-01 10:50:53 aggregator/"Dokumentation" (cdaf2-v5ayb): Resetting notifyTimer to 10s
2018-08-01 10:51:03 aggregator/"Dokumentation" (cdaf2-v5ayb): No old fs events
2018-08-01 10:51:03 aggregator/"Dokumentation" (cdaf2-v5ayb): Resetting notifyTimer to 10s
2018-08-01 10:51:13 aggregator/"Dokumentation" (cdaf2-v5ayb): Notifying about 1 fs events
2018-08-01 10:51:13 aggregator/"Dokumentation" (cdaf2-v5ayb): Resetting notifyTimer to 10s
2018-08-01 10:51:13 sendonly/cdaf2-v5ayb@0xc0420b0480 filesystem notification rescan
2018-08-01 10:51:13 Walk [Zutrittskontrolle\Obertshausen] Matcher/[]@0xc0420961b0
2018-08-01 10:51:13 Walk progress done cdaf2-v5ayb [Zutrittskontrolle\Obertshausen] Matcher/[]@0xc0420961b0
2018-08-01 10:51:15 progress emitter: bytes completed for cdaf2-v5ayb: 0
2018-08-01 10:51:15 model@0xc042098900 NeedSize("cdaf2-v5ayb"): {0 0 0 0 0 0 []}
2018-08-01 10:51:23 aggregator/"Dokumentation" (cdaf2-v5ayb): No old fs events
2018-08-01 10:51:23 aggregator/"Dokumentation" (cdaf2-v5ayb): Resetting notifyTimer to 10s

**Comment by calmh** [comment]
Corner cases ❤️

**Comment by imsodin** [comment]
Can't reproduce on linux, so this is probably windows specific.

In your logs, only an event in Dokumentation is mentioned, none in Installationsquellen. In your description you are saying that it is correctly added on Installationsquellen but not removed in Dokumentation - the two contradict each other.

**Comment by Catfriend1** [comment]
@imsodin To be more precise: I moved the file in windows explorer, so it's gone in "Dokumentation/Zutrittskontrolle" and resides then in "Installationsquellen". The watcher says it was added to "Installationsquellen" but it does not recognize it was removed from "Dokumentation" as this was a move. I think the correct behaviour should be the watcher sees one add and one deletion event. (Better would be it could get a move event but I don't know if windows provides this).

**Comment by imsodin** [comment]
> The watcher says it was added to "Installationsquellen" but it does not recognize it was removed from "Dokumentation"

Well there is this line about an event in Dokumentation

```
2018-08-01 10:51:13 aggregator/"Dokumentation" (cdaf2-v5ayb): Notifying about 1 fs events
```

and nothing about Installationsquellen - i.e. the exact opposite of what you describe. That's the discrepancy that confuses me.

We don't handle moves specially at all, certainly not across different (Syncthing) folders.

**Comment by Catfriend1** [comment]
I used a clean VM fresh set-up to reproduce again. I made up two folders, one with data (source of the move) and one empty folder (target of the move). Both folders were created with syncthing's default settings and have the fsWatcher turned on.

Folder 1 (source): C:/Sync/Utilities
Folder 2 (target): C:/Sync/Second_Folder
I did not add a second device, so all of that happens "offline" on one machine running Windows 10 x64 1703.

Here's what I did:
Went into Folder 1, subfolder and made a copy of the selected file:
![image](https://user-images.githubusercontent.com/16361913/43530045-e8277558-95ac-11e8-857c-14a62d27efd8.png)

UI showed then: > Correct.
![image](https://user-images.githubusercontent.com/16361913/43530066-f173ca58-95ac-11e8-81c5-7bf309b95e6a.png)

I moved the file to folder 2:
![image](https://user-images.githubusercontent.com/16361913/43530088-01a88616-95ad-11e8-8af5-24aaa655fd5b.png)

UI showed then: > Correct.
![image](https://user-images.githubusercontent.com/16361913/43530100-0cd1ad4c-95ad-11e8-9c7f-6849d2bab549.png)

What's missing is a line in the UI "DESKTOP-... deleted file Utilities/ABC-Update/....-Kopie.zip".

I hit the rescan button on the UI of folder 1: then the expected line appeared. Notice that I have to manuelly hit rescan or restart whole syncthing or the change is not picked up by the file watcher.
![image](https://user-images.githubusercontent.com/16361913/43530165-330ded18-95ad-11e8-8ff0-f7ccdf1dbee7.png)

Again, grabbed a log with [model] [watchaggregator] [scanner] enabled:
> [OHAJQ] 2018/08/01 16:57:50.572912 service.go:61: INFO: Detected 0 NAT services
[OHAJQ] 2018/08/01 16:58:12.726433 aggregator.go:233: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): Creating eventDir at: ABC-Update
[OHAJQ] 2018/08/01 16:58:12.726433 aggregator.go:278: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): Tracking (type non-remove): ABC-Update\2017-12-11_ABC-Update_2.1.0.0 - Kopie.zip
[OHAJQ] 2018/08/01 16:58:12.726433 aggregator.go:297: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): Resetting notifyTimer to 10s
[OHAJQ] 2018/08/01 16:58:12.726433 aggregator.go:254: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): Already tracked (type non-remove): ABC-Update\2017-12-11_ABC-Update_2.1.0.0 - Kopie.zip
[OHAJQ] 2018/08/01 16:58:12.728386 aggregator.go:254: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): Already tracked (type non-remove): ABC-Update\2017-12-11_ABC-Update_2.1.0.0 - Kopie.zip
[OHAJQ] 2018/08/01 16:58:12.731283 aggregator.go:278: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): Tracking (type non-remove): ABC-Update
[OHAJQ] 2018/08/01 16:58:22.728985 aggregator.go:329: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): Notifying about 1 fs events
[OHAJQ] 2018/08/01 16:58:22.728985 aggregator.go:297: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): Resetting notifyTimer to 10s
[OHAJQ] 2018/08/01 16:58:22.728985 folder.go:165: DEBUG: sendreceive/f7imi-rqcgc@0xc0423e7680 filesystem notification rescan
[OHAJQ] 2018/08/01 16:58:22.728985 walk.go:101: DEBUG: Walk [ABC-Update] Matcher/[]@0xc04209e510
[OHAJQ] 2018/08/01 16:58:22.730879 walk.go:380: DEBUG: to hash: ABC-Update\2017-12-11_ABC-Update_2.1.0.0 - Kopie.zip File{Name:"ABC-Update\\2017-12-11_ABC-Update_2.1.0.0 - Kopie.zip", Sequence:0, Permissions:0644, ModTime:2017-12-11 16:13:35.6583159 +0100 CET, Version:{[{OHAJQU3 1}]}, Length:3622941, Deleted:false, Invalid:false, LocalFlags:0x0, NoPermissions:false, BlockSize:131072, Blocks:[]}
[OHAJQ] 2018/08/01 16:58:22.731885 walk.go:186: DEBUG: real to hash: ABC-Update\2017-12-11_ABC-Update_2.1.0.0 - Kopie.zip
[OHAJQ] 2018/08/01 16:58:22.748441 walk.go:164: DEBUG: Walk progress done f7imi-rqcgc [ABC-Update] Matcher/[]@0xc04209e510
[OHAJQ] 2018/08/01 16:58:22.753459 folder_sendrecv.go:154: DEBUG: sendreceive/f7imi-rqcgc@0xc0423e7680 pulling (ignoresChanged=false)
[OHAJQ] 2018/08/01 16:58:22.753459 folder_sendrecv.go:227: DEBUG: sendreceive/f7imi-rqcgc@0xc0423e7680 copiers: 2 pullerPendingKiB: 32768
[OHAJQ] 2018/08/01 16:58:22.754451 folder_sendrecv.go:181: DEBUG: sendreceive/f7imi-rqcgc@0xc0423e7680 changed 0
[OHAJQ] 2018/08/01 16:58:22.754451 progressemitter.go:240: DEBUG: progress emitter: bytes completed for f7imi-rqcgc: 0
[OHAJQ] 2018/08/01 16:58:22.754451 model.go:711: DEBUG: model@0xc042096360 NeedSize("f7imi-rqcgc"): {0 0 0 0 0 0 []}
[OHAJQ] 2018/08/01 16:58:32.729985 aggregator.go:316: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): No old fs events
[OHAJQ] 2018/08/01 16:58:32.729985 aggregator.go:297: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): Resetting notifyTimer to 10s
[OHAJQ] 2018/08/01 16:58:42.760719 aggregator.go:316: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): No old fs events
[OHAJQ] 2018/08/01 16:58:42.760719 aggregator.go:297: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): Resetting notifyTimer to 10s
[OHAJQ] 2018/08/01 16:58:52.791294 aggregator.go:316: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): No old fs events
[OHAJQ] 2018/08/01 16:58:52.806115 aggregator.go:297: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): Resetting notifyTimer to 10s
[OHAJQ] 2018/08/01 16:59:02.807066 aggregator.go:316: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): No old fs events
[OHAJQ] 2018/08/01 16:59:02.807066 aggregator.go:297: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): Resetting notifyTimer to 10s
[OHAJQ] 2018/08/01 16:59:12.822468 aggregator.go:316: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): No old fs events
[OHAJQ] 2018/08/01 16:59:12.822468 aggregator.go:297: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): Resetting notifyTimer to 10s
[OHAJQ] 2018/08/01 16:59:15.338386 aggregator.go:278: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): Tracking (type non-remove): ABC-Update
[OHAJQ] 2018/08/01 16:59:15.338386 aggregator.go:217: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): Parent ABC-Update (type mixed) already tracked: ABC-Update\2017-12-11_ABC-Update_2.1.0.0 - Kopie.zip
[OHAJQ] 2018/08/01 16:59:15.338386 aggregator.go:278: DEBUG: aggregator/"Second_Folder" (7tmxs-tsc6t): Tracking (type non-remove): 2017-12-11_ABC-Update_2.1.0.0 - Kopie.zip
[OHAJQ] 2018/08/01 16:59:15.338386 aggregator.go:297: DEBUG: aggregator/"Second_Folder" (7tmxs-tsc6t): Resetting notifyTimer to 10s
[OHAJQ] 2018/08/01 16:59:22.822585 aggregator.go:316: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): No old fs events
[OHAJQ] 2018/08/01 16:59:22.822673 aggregator.go:297: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): Resetting notifyTimer to 10s
[OHAJQ] 2018/08/01 16:59:25.354409 aggregator.go:329: DEBUG: aggregator/"Second_Folder" (7tmxs-tsc6t): Notifying about 1 fs events
[OHAJQ] 2018/08/01 16:59:25.354409 aggregator.go:297: DEBUG: aggregator/"Second_Folder" (7tmxs-tsc6t): Resetting notifyTimer to 10s
[OHAJQ] 2018/08/01 16:59:25.354409 folder.go:165: DEBUG: sendreceive/7tmxs-tsc6t@0xc0423e7180 filesystem notification rescan
[OHAJQ] 2018/08/01 16:59:25.354592 walk.go:101: DEBUG: Walk [2017-12-11_ABC-Update_2.1.0.0 - Kopie.zip] Matcher/[]@0xc04209e480
[OHAJQ] 2018/08/01 16:59:25.355367 walk.go:380: DEBUG: to hash: 2017-12-11_ABC-Update_2.1.0.0 - Kopie.zip File{Name:"2017-12-11_ABC-Update_2.1.0.0 - Kopie.zip", Sequence:0, Permissions:0644, ModTime:2017-12-11 16:13:35.6583159 +0100 CET, Version:{[{OHAJQU3 1}]}, Length:3622941, Deleted:false, Invalid:false, LocalFlags:0x0, NoPermissions:false, BlockSize:131072, Blocks:[]}
[OHAJQ] 2018/08/01 16:59:25.355367 walk.go:186: DEBUG: real to hash: 2017-12-11_ABC-Update_2.1.0.0 - Kopie.zip
[OHAJQ] 2018/08/01 16:59:25.374124 walk.go:164: DEBUG: Walk progress done 7tmxs-tsc6t [2017-12-11_ABC-Update_2.1.0.0 - Kopie.zip] Matcher/[]@0xc04209e480
[OHAJQ] 2018/08/01 16:59:25.375860 folder_sendrecv.go:154: DEBUG: sendreceive/7tmxs-tsc6t@0xc0423e7180 pulling (ignoresChanged=false)
[OHAJQ] 2018/08/01 16:59:25.375860 folder_sendrecv.go:227: DEBUG: sendreceive/7tmxs-tsc6t@0xc0423e7180 copiers: 2 pullerPendingKiB: 32768
[OHAJQ] 2018/08/01 16:59:25.375860 folder_sendrecv.go:181: DEBUG: sendreceive/7tmxs-tsc6t@0xc0423e7180 changed 0
[OHAJQ] 2018/08/01 16:59:25.375860 progressemitter.go:240: DEBUG: progress emitter: bytes completed for 7tmxs-tsc6t: 0
[OHAJQ] 2018/08/01 16:59:25.375860 model.go:711: DEBUG: model@0xc042096360 NeedSize("7tmxs-tsc6t"): {0 0 0 0 0 0 []}
[OHAJQ] 2018/08/01 16:59:32.823273 aggregator.go:316: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): No old fs events
[OHAJQ] 2018/08/01 16:59:32.823427 aggregator.go:297: DEBUG: aggregator/"Utilities" (f7imi-rqcgc): Resetting notifyTimer to 10s
[OHAJQ] 2018/08/01 16:59:35.370148 aggregator.go:305: DEBUG: aggregator/"Second_Folder" (7tmxs-tsc6t): No tracked events, waiting for new event.

**Comment by imsodin** [comment]
Do you have logs after this? I am asking because the missing change is picked up as a mixed event (looks like we receive a modification event for the parent directory)

meaning the scan will be delayed (by 60s by default). I.e. a line containing `Notifying about` should come up around 17:00:15.

**Comment by Catfriend1** [comment]
Ok sorry, I again started out fresh on VM environment and the move was detected correctly, took longer as you said ~ 60 secs.
![image](https://user-images.githubusercontent.com/16361913/43584603-1ef452ca-9663-11e8-8559-800a9fa8bd18.png)

**Comment by Catfriend1** [comment]
The issue is resolved for me, feel free to close it.
