### ISSUE TITLE
[ENHANCEMENT] Sync "Share With Devices" Settings

### ISSUE THREAD

**Issue by Joechim94** [syncthing/syncthing#5108]
### Scenario

I want to create a shared folder on my **Desktop** that syncs with my **Laptop**. It works, great!
I then decide that I want to sync this folder with my **Phone** such that the state between the three is always up-to-date as possible no matter which device has last been used.

## Problem

To add the phone, I need to go to every other device that I want to share the folder with and manually pair the phone to the desktop, laptop, etc.

## Solution

Include an option to sync the state of "Share with Device" across sharees; such that syncing the phone with the laptop will also allow syncing with the desktop automatically.

**Comment by AudriusButkevicius** [comment]
Introducer feature solves this.

**Comment by Joechim94** [comment]
I don't want special roles or hierarchy, I just want syncthing to have a list of peers to sync to in a text file that gets synced to all other guests.

**Comment by AudriusButkevicius** [comment]
I want a pony named Tony... 

You can achieve what you want by using existing features...

**Comment by Joechim94** [comment]
No, I want a text editable list of peers in the directory. I want .stpeers
"Introducers" is a convoluted hierarchal concept that's error prone and not very well thought out.

**Comment by AudriusButkevicius** [comment]
Sure, yet it's not going to happen, as we have introducers for this.
