### ISSUE TITLE
Password Auth to add Devices/Folders

### ISSUE THREAD

**Issue by Joechim94** [syncthing/syncthing#5113]
### Scenario

When pairing a virgin device with another established device, one must manually confirm the addition of the new device with the primary device.
Instead, it would be nice to be able to set a password on the primary device. Additional devices that report the password to primary device will automatically be added to the primary device without the need of the user manually approving the addition of the secondary device on the primary device.

**Comment by calmh** [comment]
This has the disadvantage that the password may leak and everything is compromised, and it's not clear what folders it would allow sharing.

**Comment by AudriusButkevicius** [comment]
I think this is mostly https://github.com/syncthing/syncthing/issues/2300

**Comment by calmh** [comment]
Somewhat yes. There's also discussion somewhere about a one time token thing, which is similar to this except the token also identifies what folders etc to use and expires after x uses or y hours.
