### ISSUE TITLE
Include systemd units in stdiscosrv/strelaysrv Debian packages

### ISSUE THREAD

**Issue by cromefire** [syncthing/syncthing#5115]
### Please use the correct issue tracker
syncthind-discosrv doesn't have one

### Does your log mention database corruption?
not important

### Please do post actual bug reports and feature requests.
The OS (Debian/Ubuntu) packages already include systemd files that help to let the services run in the background and restart them on reboot and failure. Please also include them in your packages.

### Version Information

Syncthing Version: v0.14.49
OS Version: `Ubuntu 18.04 LTS`
Browser Version: not applicable

### Files
The Debian/Ubuntu package service files (remove `.txt`, github constraints):
[syncthing-relaysrv.service.txt](https://github.com/syncthing/syncthing/files/2281093/syncthing-relaysrv.service.txt)
[syncthing-discosrv.service.txt](https://github.com/syncthing/syncthing/files/2281094/syncthing-discosrv.service.txt)

**Comment by cromefire** [comment]
And they also include the following defaults file under`/etc/default/` (remove `.txt`):
[syncthing-relaysrv.txt](https://github.com/syncthing/syncthing/files/2281100/syncthing-relaysrv.txt)

**Comment by calmh** [comment]
This is the correct issue tracker, yes.

**Comment by cromefire** [comment]
It _should_ be as simple, as including this files in the build.
These files require a `syncthing` user to be present on the system, is this handled by your packages or do I need to post the control files?

**Comment by cromefire** [comment]
Yes that's the idea I don't think it's a common case that someone wants to run multiple relay/discovery servers on one machine and if so he can simply create copies and can hard code the arguments (That's done via environment files in this case).

**Comment by cromefire** [comment]
If you want I can write documented environment files that show how to configure the services (if someone is not familiar with these).

**Comment by desbma** [comment]
This is what I use to run a public relay, note the hardening part to ensure nothing is writable except home:
```
[Unit]
Description=Syncthing relay server
After=network.target

[Service]
User=syncthing-relaysrv
ExecStart=/usr/bin/strelaysrv -global-rate=1048576
WorkingDirectory=~
Nice=15

# hardening
User=syncthing-relaysrv
PrivateTmp=yes
ReadOnlyPaths=/
ReadWritePaths=/home/syncthing-relaysrv
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
```

**Comment by cromefire** [comment]
I would change 2 things:
- Do not hardcode the options, but include them with `$RELAYSRVOPTS` an environment file like `/etc/defaults/syncthing-relaysrv`
- Do create the user as systemuser with home `/var/lib/syncthing-relaysrv`, because `/home` is for human users
Also we need to the Deb would need 2 things:
- A default file: `/etc/defaults/syncthing-relaysrv`
- Create a system user with home at `/var/lib/syncthing-relaysrv`

Also I don't know if we should hardcode the nice, but a nice of 15 seems reasonable

I don't know how the debs are handled by syncthing, but I might try adding a PR, if I find time for that.

**Comment by cromefire** [comment]
That means `/usr` read only? Plus somee subpath of `/etc`? 

To configure them in systemd I need the path

**Comment by calmh** [comment]
That depends on how it's run, which I think is not decided as there is no systemd unit already. I suggest you try this out, I don't have the answers ready.

**Comment by cromefire** [comment]
What do you use to generate the debs?

**Comment by calmh** [comment]
There is metadata on the files to include in the build script:

https://github.com/syncthing/syncthing/blob/ff2cde469e3b00259cd9b5ee89a06400bf7efd73/build.go#L124-L168

The actual package build done using the `fpm` tool with the binaries we just built:

https://github.com/syncthing/syncthing/blob/ff2cde469e3b00259cd9b5ee89a06400bf7efd73/build.go#L557-L613

**Comment by calmh** [comment]
In the end this is triggered by something like `go run build.go deb stdiscosrv`

**Comment by calmh** [comment]
"fpm" is this tool: https://github.com/jordansissel/fpm

**Comment by cromefire** [comment]
I'll look into it

**Comment by cromefire** [comment]
Well it has `--systemd`, `--default` and `--activate`. Where should I store additional files in this repo?

**Comment by cromefire** [comment]
Like the service files

**Comment by desbma** [comment]
> 
> 
> I would change 2 things:
> 
>     * Do not hardcode the options, but include them with `$RELAYSRVOPTS` an environment file like `/etc/defaults/syncthing-relaysrv`
> 
>     * Do create the user as systemuser with home `/var/lib/syncthing-relaysrv`, because `/home` is for human users
> 
> 
> Also we need to the Deb would need 2 things:
> 
>     * A default file: `/etc/defaults/syncthing-relaysrv`
> 
>     * Create a system user with home at `/var/lib/syncthing-relaysrv`
> 
> 
I agree with all your remarks, I wrote that service file quickly for myself, and I don't think it should be used as such.

The Arch Linux service files for `syncthing-relaysrv` are worth having a look: https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/syncthing

**Comment by cromefire** [comment]
Yes my files are base on the Ubuntu packages, if you need them in the arch files I'm afraid you will need to help me

**Comment by cromefire** [comment]
I just thought we could integrate them into the arch packages as well

**Comment by desbma** [comment]
I am using both Ubuntu and Arch Linux, and I am happy with the Arch systemd files, but they are downstream.
I am just saying maybe they could be reused partially or fully, in the upstream Ubuntu package files.

**Comment by desbma** [comment]
Sure, once they are in a release, the Arch package will most likely use them. We'll remind them if they don't.
Arch has a policy of "minimum change to upstream".

**Comment by desbma** [comment]
On a similar note, adding a ufw ruleset to open ports for the relay server (like for standard syncthing in `/etc/ufw/applications.d/syncthing`) would be a great in the Ubuntu package.

The equivalent of:
```
ufw allow 22067/tcp
ufw allow 22070/tcp
```

**Comment by desbma** [comment]
I forgot to add, if you need help with the systemd files or ufw addition, I am available to help, and I can do a pull request or review/test changes.
