### ISSUE TITLE
master branch windows watcher setup fails

### ISSUE THREAD

**Issue by xjtdy888** [syncthing/syncthing#5121]
today build master source, on win10 64b watcher setup fails
the error:
```
GetFileAttributesEx \\?\E:: The parameter is incorrect.
```
![qq 20180814181507](https://user-images.githubusercontent.com/622685/44086148-3cf10dce-9fee-11e8-9165-8ae03923020e.png)

and tested syncthing-windows-amd64-v0.14.50-rc.1 is be fine

**Comment by calmh** [comment]
Check if e20679af is the guilty commit?

**Comment by xjtdy888** [comment]
yep, e20679afe1dd06978770f270f8c0f4c641fa39ad guiltt!
@imsodin

**Comment by imsodin** [comment]
That's probably good :) Because it means the watcher silently didn't work before (or did, but just by chance).

Is `E:` some special windows storage thing?

Can you run this after adding your folder root path:

```golang
package main

import (
	"fmt"
	"path/filepath"
	"os"
)

func main() {
	fmt.Println(filepath.EvalSymlinks(`\\?\E:\*pathToYourFolder*`))
	fmt.Println(filepath.EvalSymlinks(`E:\*pathToYourFolder*`))
	fmt.Println(filepath.EvalSymlinks(`\\?\E:`))
	fmt.Println(filepath.EvalSymlinks(`\\?\E:\`))
	fmt.Println(os.Lstat(`\\?\E:\`))
	fmt.Println(os.Lstat(`E:\`))
	fmt.Println(os.Lstat(`E:`))
}
```

**Comment by imsodin** [comment]
The double colon looks weird. It's either a bug in `filepath.EvalSymlinks` or something weird about your `E:` or both. I don't have time right now to investigate. Is your E drive anything else but a "normal disk"?

**Comment by xjtdy888** [comment]
![qq 20180815185228](https://user-images.githubusercontent.com/622685/44145002-667222a4-a0bc-11e8-84b9-0d999df99232.png)

All drives are normal disk, I tested all partitions, CDE on disk 1, H on disk 2, all the same problem。
I built the version before e20679a and everything works fine.

![qq 20180815185840](https://user-images.githubusercontent.com/622685/44145220-4d8c3382-a0bd-11e8-8a5c-edcce124b2ff.png)
![qq 20180815185851](https://user-images.githubusercontent.com/622685/44145221-4dcb37e4-a0bd-11e8-8c64-c9233ab2b7fb.png)

**Comment by AudriusButkevicius** [comment]
The only way this would be true if it came from the go runtime, as this has the syscall name in it. I wonder if a driver letter without a trailing slash is a valid path.

**Comment by xjtdy888** [comment]
It seems that it should be a problem with the runtime library (go1.9.7). I compiled it on another machine go1.10 and sent it back to WIN10. Everything is fine. @AudriusButkevicius

**Comment by AudriusButkevicius** [comment]
So case closed? I guess its not nice it does not work on an older go version, but nor am I particularly fussed about it.

**Comment by xjtdy888** [comment]
Is there anything weird about this line? I tested the 1.9.7 and 1.10.3 results and it looks a bit strange.
```
fmt.Println(filepath.EvalSymlinks(`E:\RSYNC\qtox`))
```

go 1.9.7
```
 GetFileAttributesEx \\?\E:: The parameter is incorrect.
E:\RSYNC\qtox <nil>
 GetFileAttributesEx \\?\E:: The parameter is incorrect.
 GetFileAttributesEx \\?\E:: The parameter is incorrect.
&{E: {22 {3659431582 30523544} {2840709269 30684415} {1632349449 30684296} 0 16384} 0 {0 0} \\?\E:\ 0 0 0 false} <nil>
&{\ {22 {3659431582 30523544} {2840709269 30684415} {1632349449 30684296} 0 16384} 0 {0 0} E:\ 0 0 0 false} <nil>
&{. {16 {1870607188 30618303} {891634380 30684302} {2531088070 30684087} 0 0} 0 {0 0} E:\RSYNC\qtox 0 0 0 false} <nil>
```

go 1.10.3 result:
```
E:\RSYNC\qtox <nil>
E:\RSYNC\qtox <nil>
 GetFileAttributesEx \\?\E:: The parameter is incorrect.
E:\ <nil>
&{E: {22 {3659431582 30523544} {1149201007 30684415} {1632349449 30684296} 0 16384} 0 {0 0} \\?\E:\ 0 0 0 false} <nil>
&{\ {22 {3659431582 30523544} {1149201007 30684415} {1632349449 30684296} 0 16384} 0 {0 0} E:\ 0 0 0 false} <nil>
&{. {16 {1870607188 30618303} {891634380 30684302} {2531088070 30684087} 0 0} 0 {0 0} E:\RSYNC\qtox 0 0 0 false} <nil>
``

```
package main

import (
	"fmt"
	"path/filepath"
	"os"
)

func main() {
	fmt.Println(filepath.EvalSymlinks(`\\?\E:\RSYNC\qtox`))
	fmt.Println(filepath.EvalSymlinks(`E:\RSYNC\qtox`))
	fmt.Println(filepath.EvalSymlinks(`\\?\E:`))
	fmt.Println(filepath.EvalSymlinks(`\\?\E:\`))
	fmt.Println(os.Lstat(`\\?\E:\`))
	fmt.Println(os.Lstat(`E:\`))
	fmt.Println(os.Lstat(`E:`))
}
```

**Comment by imsodin** [comment]
In my opinion it's inconsistent on the side of Go's `os` and `filepath` libraries that in one case `E:` is valid, in the other case it is not and one needs to provide a trailing backslash (`E:\`). However we already make sure there is a trailing backslash when creating filesystems, so it's not a problem.

I think with go1.11 already being at RC stage this failure on go1.9 is acceptable. The alternative would be a `runtime.GOOS = windows` hack which is ugly or a custom implementation of `filepath.EvalSymlinks` which is annoying.

**Comment by calmh** [comment]
So yeah sounds like Go bug that is fixed and we can all move on.
