### ISSUE TITLE
Progress updates are ignored for send only folders

### ISSUE THREAD

**Issue by ellnic** [syncthing/syncthing#5131]
- what happened

When transferring a large file, the progress percentage often does not update. Other times it jumps to 98% until completion (rarer).

 - what you expected to happen instead

For the progress percentage to periodically update as the file transfers

 - any steps to reproduce the problem

Transfer a single large file, with or without large blocks enabled.

### Version Information

**Send Node:** 

Syncthing Version: v0.14.49 (64bit)
OS Version: MacOS 10.13.4
Browser Version: Chrome 68.0.3440.106 (Official Build) (64-bit)

**Receive Node:**

Syncthing Version: v0.14.49 (64bit)
OS Version: Ubuntu 18.04
Browser Version: Firefox 61.0.1 (64-bit)

**Other info:** Both Intel CPUs, a Xeon and an i3.

**Logs with STTRACE=model**

[syncthing-log-receive-node.log](https://github.com/syncthing/syncthing/files/2295418/syncthing-log-receive-node.log)
[syncthing-log-send-node.log](https://github.com/syncthing/syncthing/files/2295419/syncthing-log-send-node.log)

**Screenshots:**

Large blocks:
<img width="462" alt="1" src="https://user-images.githubusercontent.com/16370944/44238462-b6e97480-a1ac-11e8-9dbb-2f9ec8ff9573.png">

Without large blocks:
<img width="528" alt="screen shot 2018-08-16 at 23 10 33" src="https://user-images.githubusercontent.com/16370944/44238470-bd77ec00-a1ac-11e8-8744-e2c6b8b48cf4.png">

**Comment by ellnic** [comment]
Configs added.

[receive_config.txt](https://github.com/syncthing/syncthing/files/2305251/receive_config.txt)
[send_config.txt](https://github.com/syncthing/syncthing/files/2305252/send_config.txt)

**Comment by calmh** [comment]
There was a good reason for this, but I think it's simpler to act the same in all cases and let those who care disable temp indexes instead; => bug
