### ISSUE TITLE
Execution permission is ignored in Linux partition

### ISSUE THREAD

**Issue by geaplanet** [syncthing/syncthing#5133]
- What happened,
I'm synchronizing bash scripts with 3 linux machines. All files have execution permission. Files are in EXT4 filesystem (mount options in fstab: PARTUUID=fd969790-02  /   ext4  defaults,noatime  0 1)
Execution permission is ignored by Syncthing in all machines. No matter which machine creates the file (or user), when it is copied to the other machines, the execution bit is ignored. Of course, I have the option "no perm" for fat fylesystem disabled.

- What you expected to happen instead, and
Permissions should be maintained by Syncthing.

- Any steps to reproduce the problem.
I simply run Syncthing and tried to share files.

### Version Information
Machine 1: v0.14.49, Linux (32 bit) --> i3
Machine 2: v0.14.49, Linux (32 bit) --> i5
Machine 3: v0.14.48, Linux (ARM) --> rpi

I don't know how to report a log of my Syncthing, where I can get this info?

OS Version: Debian Linux Stable
Browser Version: Firefox 61

**Comment by geaplanet** [comment]
Here you are and thanks in advance:

```
MACHINE A:
minino@minino:~/COMPARTIDA$ ls -l testfile
-rwxr-xr-x 1 minino minino 0 ago 18 19:54 testfile
minino@minino:~/COMPARTIDA$ ls -l
total 12
-rw-r--r-- 1 minino minino  679 ago 17 19:10 listadoalumnos.txt
drwxr-xr-x 4 minino minino 4096 ago 18 11:59 programas
-rwxr-xr-x 1 minino minino    0 ago 18 19:54 testfile
drwxr-xr-x 5 minino minino 4096 ago 17 19:05 TRABAJOS
```

```
MACHINE B:
pi@raspberrypi:/media/pi/COMPARTIDA $ ls -l
total 12
-rw-r--r-- 1 pi pi  679 ago 17 19:10 listadoalumnos.txt
drwxr-xr-x 4 pi pi 4096 ago 18 11:59 programas
-rw-r--r-- 1 pi pi    0 ago 18 19:54 testfile
drwxr-xr-x 5 pi pi 4096 ago 17 19:06 TRABAJOS
```

**Comment by calmh** [comment]
Config files, `mount | grep /media/pi`?

**Comment by geaplanet** [comment]
`/dev/sda1 on /media/pi/COMPARTIDA type ext4 (rw,nosuid,nodev,relatime,data=ordered,uhelper=udisks2)`

**Comment by geaplanet** [comment]
What do you mean with "config files"? .config/syncthing/config.xml in all machines?

**Comment by calmh** [comment]
On the two relevant ones at least, yes. Feel free to redact API keys / password hashes of course.

**Comment by geaplanet** [comment]
[config.xml-i5.txt](https://github.com/syncthing/syncthing/files/2299836/config.xml-i5.txt)
[config.xml-rpi.txt](https://github.com/syncthing/syncthing/files/2299837/config.xml-rpi.txt)

**Comment by calmh** [comment]
```
<folder id="qbksr-pkxze" label="COMPARTIDA" path="/media/pi/COMPARTIDA/" ... ignorePerms="true" 
```

**Comment by geaplanet** [comment]
O_O! I'm ashamed, I really thought that I had reviewed those options on all the computers.
Thank you and sorry for the inconvenience.
