### ISSUE TITLE
Unparsed HTML in notification popup on Gnome

### ISSUE THREAD

**Issue by benruijl** [syncthing/syncthing#5134]
When a file is synchronized, the gnome notification popup contains an unparsed html link, as shown in the image below:

![popupbug](https://user-images.githubusercontent.com/280089/44308108-6f7f0600-a3af-11e8-9357-5ccd94138e77.png)

### Version Information

Syncthing Version: v0.14.48
OS Version: Arch Linux

**Comment by imsodin** [comment]
Please report the issue at https://github.com/syncthing/syncthing-gtk/issues
