### ISSUE TITLE
[Feature Request] Sync references to files, but not the files themselves

### ISSUE THREAD

**Issue by BNolet** [syncthing/syncthing#5135]
Imagine this: 

You have lots of photos you need to transfer to a remote machine, but you don't have remote access to said machine and your phone/laptop doesn't have enough room to actually store the files themselves. The remote machine isn't yet linked to your desktop in syncthing, where all the photos are stored. 

If one could sync to their phone/laptop that these files exist, but not actually sync the files themselves, the photos would easily be transferrable to the remote machine.

**Comment by AudriusButkevicius** [comment]
Sorry, but this makes no sense, the phone has to store the photos to be able to supply them.
If you don't want to store them on the phone, don't and just link desktop and remote machine.

**Comment by BNolet** [comment]
Don't you have to be on the same network to link two devices?

**Comment by AudriusButkevicius** [comment]
No, they just need to be able to connect, which can be done over the internet or even by using a relay.
