### ISSUE TITLE
Rate limit can be very bursty

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#5138]
Filing this to see if anyone thinks it's a problem...

We do rate limiting by delaying read/write operations until the amount of data in the read/write is allowed by the desired rate. The layer above this deals in messages. So at least for writes, a message will go out as a single write. Messages can be large, especially with large blocks. So, for example, a 100 KiB/s rate limit sending a 4 GiB file (4 MiB blocks) will result in one message every 40 seconds. That's 4 MiB sent infinitely fast, and then a long wait.

If the purpose of the rate limit is to avoid choking an ADSL link to avoid dropping VoIP packets (for example) this doesn't accomplish the desired effect at all.

If the purpose is just to limit the amount of data sent during any given hour or so, it's fine.

Solving this would involve making the LimitedReader/Writer smarter about the amount of data in relation to the limit and potentially chopping up the operations into smaller reads/writes.

**Comment by MagneticCursor** [comment]
I had this problem. After an upgrade, my routers QoS keeps my connection stable. I would bet there are many others who would be helped by this change.

**Comment by otbutz** [comment]
https://github.com/juju/ratelimit ?

**Comment by calmh** [comment]
We use that package, but that’s not relevant to the issue. What are you trying to say?

**Comment by calmh** [comment]
Oh, actually we don't, we used to but have switched to x/time/rate instead. Regardless, that is neither the problem nor the solution.

**Comment by mrVanDalo** [comment]
I have the same issue, and used FireQOS to throttle the syncthing output, and the first hour it looks like this issues is solved for me.
