### ISSUE TITLE
Symbolic links gets deleted on Linux when Windows syncs back

### ISSUE THREAD

**Issue by ilario** [syncthing/syncthing#5150]
### Setup

I **sync a directory between Linux and Windows 10**.
Versioning off, watching for changes enabled on both sides.

### What happened

When I **create a symlink on Linux**, and I wait for the **rescan** time (or I click rescan on Linux and then click rescan on Windows) the **symlink gets deleted on Linux side**.

The fact that the symlink doses not appear on Windows is expected, what is annoying is that it gets removed on Linux side when the Windows client syncs back.

### What was expected

The **symlink** created on Linux **should stay present on Linux**.

### For reproducing the bug

Sync a directory between Linux and Windows 10.
Create a symlink in the directory on Linux side.
Click on rescan button on Linux side.
Click on rescan button on Windows side.
Check if the symlink is still existing on Linux side.

### Version Information

Syncthing Version on Linux: v0.14.49 "Dysprosium Dragonfly" (go1.10.3 linux-amd64) builduser@svetlemodry 2018-07-29 16:37:02 UTC [noupgrade]

OS Version on Linux: Arch Linux

Syncthing Version on Windwos: v0.14.49 "Dysprosium Dragonfly" (go1.10.3 windows-amd64) teamcity@build.syncthing.net 2018-07-10 15:40:06 UTC

OS Version on Windows: Windows 10, version 1607, build 14393.1480

GUI on Windows: Synctrayzor 1.1.21

**Comment by AudriusButkevicius** [comment]
Check existing closed issues.

**Comment by ilario** [comment]
I did, maybe not carefully enough.
Now I see why, I was looking for "symbolic" string, that does not appear in #5125, that's why I missed it.

**Comment by calmh** [comment]
Thanks for making the effort, both for searching first and for making the report.

**Comment by ilario** [comment]
Thank you all for the amazing software :D
