### ISSUE TITLE
cmd/stdiscosrv: Should not allow localhost addresses

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#5151]
When running discosrv and syncthing on the same machine the source address seen by discosrv for announcements is typically ::1 or 127.0.0.1. These addresses have zero chance of being useful to anyone else and should be filtered out. (In contrast this setup *could* work if the Syncthing device also announces a valid, static IP.)

**Comment by AudriusButkevicius** [comment]
This doesn't solve the lan issue tho nor could it replace it in a meaningful way

**Comment by calmh** [comment]
Yeah that's still unavoidable due to the topology I think.
