### ISSUE TITLE
Shared Clipboard - copy and paste across devices

### ISSUE THREAD

**Issue by rainulf** [syncthing/syncthing#5157]
Context: https://thenextweb.com/microsoft/2018/05/11/windows-10s-new-clipboard-takes-the-pain-out-of-copy-and-pasting/

The problem with this is that I don't like the idea of having my clipboard uploaded to "the cloud". It would be great if this can be done directly between two devices.

**Comment by AudriusButkevicius** [comment]
Its file sync software, it syncs files, so no.
