### ISSUE TITLE
[docker] Failed to create folder root directory mkdir /Sync/: permission denied

### ISSUE THREAD

**Issue by lolouk44** [syncthing/syncthing#5159]
sorry if this is the wrong place, I can't seem to find a place for docker questions (the docker github appears to have been closed/archived)
I'm trying to get synthing to work on docker. I've see the comments on posts [11](https://github.com/syncthing/docker/issues/11) and [17](https://github.com/syncthing/docker/issues/17) and I've set the folders owner to `1000:1000` with `chown`, but I still get issues:
```
2018-09-03 22:37:20: Failed to create folder root directory mkdir /Sync/: permission denied
2018-09-03 22:37:20: Error on folder "Default Folder" (default): folder path missing
```
Not sure how to get this fixed...

**Comment by calmh** [comment]
The `/Sync` directory is not something the docker image does by default. Directories you create, you need to ensure correct permissions on. Further discussion on the forum please as this is support.
