### ISSUE TITLE
Implement feature to discard a subset of ignored files on folder deletion

### ISSUE THREAD

**Issue by kakra** [syncthing/syncthing#5161]
SyncThing already has the concept of ignoring files from the sync list which is nice. But here's a problem:

I thought it would be good to put desktop.ini, .desktop and other various directory meta data/information of different OSes into the ignore list. It stops SyncThing from syncing folder settings like sorting etc., and it stops SyncThing from starting a sync whenever I change one of those meta data.

But this creates a problem: If I delete a sub folder completely, this change can no longer be synced across my devices because SyncThing complains about ignored files being present. Of course this is correct and expected behavior - otherwise SyncThing could delete important user files.

But how about an option similar to how Samba implements it as veto files? In Samba I can specify hidden files which are completely visible to the user but Samba still knows about them - kinda like ignored files are not used (aka invisible) by SyncThing. Veto files are one concept further: Veto files are similar but not only they are hidden from users but they are also inaccessible which creates the same problem on folder deletion: Samba would refuse to delete a folder that still contains veto files - kinda like SyncThing refuses to delete folders containing ignored files. But I can instruct Samba to simply delete veto files in this case.

So I propose that SyncThing gets another set of ignored files (invention of a name still to do) that has this property: Upon folder deletion such files will be simply discarded, maybe along with a log entry about this event. Such files should also be put into the versions folder so they would be resurrected together with the folder that was deleted.

I also think it makes more sense to make such an option a global option and not a per-folder option (but having both would be best).

**Comment by ProactiveServices** [comment]
See the [documentation on ignore files](https://docs.syncthing.net/users/ignoring.html).

**Comment by calmh** [comment]
Specifically, look for `(?d)`
