### ISSUE TITLE
Create Unix dotfiles as hidden files in Windows

### ISSUE THREAD

**Issue by kakra** [syncthing/syncthing#5162]
I'm syncing between Windows and Linux hosts, and I'd prefer if SyncThing would mark newly created dotfiles as hidden automatically in Windows. If the user later decides to unhide the files, that's okay. The hidden attribute should only be applied upon creation of a file.

Maybe SyncThing could have an option like "hide-on-creation" which I could fill with patterns. It could default to a list like:

```
.*
desktop.ini
```

See also another report #4935 about storing Windows attributes in xattr data to preserve them across different file system architectures.

**Comment by calmh** [comment]
I think this would match how we try to handle execute bits from Windows files etc, so seems reasonable. (The dotfiles part; I'm less convinced about the configurable patterns thing. And the xattrs things is a totally different issue.)

**Comment by p0larstern** [comment]
I would like to work on this issue if this is still open, but I am new to this community and I may need help.

**Comment by calmh** [comment]
Per the discussion on the pull request this is not a desirable feature. Hence, based on feedback, I've decided we should not implement this.
