### ISSUE TITLE
Feature request: Reordering of pull order in web interface (out-of-sync items)

### ISSUE THREAD

**Issue by wiwie** [syncthing/syncthing#5166]
Currently one can only specify in the folder settings, how files should be pulled.

However, it would be nice if this order could be changed via the web interface.

For instance, having a large out-of-sync folder with a particular subfolder of (current) interest. Syncing the whole folder may take a long time, but maybe one is only interested in the subfolder.

Being able to assign this subfolder a higher priority than the rest could greatly reduce waiting times to be able to work with the subfolder.

**Comment by calmh** [comment]
You can click on the list of out of sync files and prioritize there, live.

**Comment by AudriusButkevicius** [comment]
You cannot reorder the download order of the remote device, you can only reorder local downloads so you should do it on the device downloading.

Reordering is only per file.
