### ISSUE TITLE
Versions newer than v0.14.48 trigger a trap on OpenBSD-current (amd64)

### ISSUE THREAD

**Issue by ckeen** [syncthing/syncthing#5167]
When starting v0.14.48 on OpenBSD-current it fetches an upgrade and upon restart this immediately segfaults. Starting this fetched binary manually immediately segfaults. No debug flags yield any output.
'syncthing --help' segfaults immediately without producing output.

The message in dmesg is:

```log
 trap [syncthing]60898/311985 type 6: sp c42003e7d8 not inside 7f7fffbda000-7f7ffffda000
```
Disabling auto upgrade is my current workaround to keep the service up.

### Version Information

Syncthing Version: v0.14.48+
OS Version: OpenBSD-current (amd64)

**Comment by AudriusButkevicius** [comment]
Probably a go runtime issue, suggest you check their issue tracker too.

**Comment by ckeen** [comment]
Which runtime is used to create the syncthing binaries? The golang package from OpenBSD ports works as expected which is 1.8.1...

**Comment by AudriusButkevicius** [comment]
1.10.4 or 1.11

**Comment by calmh** [comment]
- 0.14.47 was Go 1.10.1
- 0.14.48 was Go 1.10.2
- 0.14.49 was Go 1.10.3
- 0.15.50 will be Go 1.11

I think all of these are *supposed* to work on current OpenBSD. Go 1.11 release notes says 6.2 is required, whatever that is.

**Comment by calmh** [comment]
Both .49 and .50-rc3 work fine for me on an OpenBSD 6.3 VM I just spun for the purpose. So this needs more narrowing down by the OP I think.

**Comment by AudriusButkevicius** [comment]
I am going to close for now as it's not clear what the resolution for this should be hence its not cloaable by any action. Discussions can move to the forum I guess, until we know what needs to be fixed on our side.

**Comment by ckeen** [comment]
* Jakob Borg <notifications@github.com> [180908 12:46]:
> Both .49 and .50-rc3 work fine for me on an OpenBSD 6.3 VM I just spun for the purpose. So this needs more narrowing down by the OP I think.

I have been testing on -current which will be the next release 6.4, comming soon...
What additional info could I provide to help narrow this down?


-- 
May you be peaceful, may you live in safety, may you be free from
suffering, and may you live with ease.

**Comment by AudriusButkevicius** [comment]
You probably have to raise it with Go folks or BSD folks as this is a wider issue. I suspect if you install go and try running a hello world and see if it happens.
