### ISSUE TITLE
Show more entries in recent changes modal

### ISSUE THREAD

**Issue by Script-Mak3r** [syncthing/syncthing#5168]
On a semi-regular basis, I add >50 files to a synced folder. This, even before getting into the fact that those files are generated using a tool that resides in a _different_ synced folder, completely wipes out any other information in Recent Changes.

As such, it might be nice to have a number of pages in Recent Changes, so as to provide more information while not making the list require too much scrolling. How far back the changes go (both in time and quantity) could possibly be configured on a per-user basis.

**Comment by AudriusButkevicius** [comment]
It's limited to last 100 items, so adding pages will not make the list longer. If items you care about roll off after 100 items, you probably have a different problem, as I don't think there is a number that satisfies everyone, and we'll have people with 1k items complaining that it's not enough.

**Comment by Script-Mak3r** [comment]
On my end, it only shows the last 25 items.

**Comment by AudriusButkevicius** [comment]
Right, maybe I remember incorrectly and it is 25, but my point remains. This information is extra memory usage and is only gathered at runtime, so making it bigger is not for free, hence I think we should not do it.

**Comment by opusforlife2** [comment]
> so making it bigger is not for free, hence I think we should not do it.

Let the user configure how many entries they want to view? It could be a choice between 25 (default), 50, 100, all; or it could be a user entered value between, say 0, 1 and 100 (with 0 meaning all)?

Pagination could be done per 25/50 entries.

**Comment by dbogdanov** [comment]
Only 25 recent changes is really too low. Log at least 100 by default. It's not a heavy memory load. 

Ideally, the entire history should be browsable and searchable. Loaded with pagination from a log file.

**Comment by wavetro** [comment]
Any update on this? It's very frustrating when I forget to run syncthing as verbose and now I can't check my logs to ensure that all my items synced correctly

**Comment by AudriusButkevicius** [comment]
No, there is no update.

**Comment by wavetro** [comment]
Fair enough. Might as well some workflow workarounds for future readers after bumping this thread:

1. Rely on Trash Can File Versioning to list all updated files in the .stversions folder. I've had some edge cases where an old file was mistakenly prioritized over my new one (hence my inquiry to log more than 25 file changes by default) but this is my current workaround

2. For Windows users, use SyncTrayzor's tray icon. You can double-click it to see the full list of updated files instead of the last 25. No option for this is available on Linux sadly

3. Launch Syncthing with the verbose flag, but you will have to search the logs within the GUI to see all changed files

**Comment by opusforlife2** [comment]
@AudriusButkevicius Do you disagree with the idea of making it user configurable? It will not affect existing and new installations, where the current default can remain as it is. Only those users who want this will use the option.

**Comment by AudriusButkevicius** [comment]
I think that using audit logs is the right way here, all of this stuff is held in memory, so its easy for some user to set it to int.max and have a bad time.

**Comment by opusforlife2** [comment]
@AudriusButkevicius Is that not easily avoided by hardcoding lower and upper limits into the app?

**Comment by calmh** [comment]
Yeah, I'm deciding this is out of scope. We keep a small amount of entries in memory for the purposes of an overview in the GUI. For longer history or persistent history the correct solution is to use the audit log, the verbose log, or the event API to store it in some other system.
