### ISSUE TITLE
[question] What is the file transfer protocol used:TCP、UDP or others？

### ISSUE THREAD

**Issue by CodingOX** [syncthing/syncthing#5172]
I am a novice for syncthing，so i want to know something.
1. What is the file transfer protocol used:TCP、UDP or others？
2. How to ensure file integrity in syncthing? Especially in the case of poor network conditions!
thanks for your answer!

**Comment by canton7** [comment]
When you created this issue, you deleted some text which appeared by default. At the top, this said:

> ### DO NOT POST SUPPORT REQUESTS OR GENERAL QUESTIONS IN THIS ISSUE TRACKER
>
> Please use the forum at https://forum.syncthing.net/ where a large number of
helpful people hang out. This issue tracker is for reporting bugs or feature
requests directly to the developers. Worst case you might get a short
"that's a bug, please report it on GitHub" response on the forum, in which
case we thank you for your patience and following our advice. :)

As this text said, [the forum](https://forum.syncthing.net) is the best place for questions like this

**Comment by CodingOX** [comment]
@canton7 get it!
