### ISSUE TITLE
Symlinks are not followed

### ISSUE THREAD

**Issue by KingDuckZ** [syncthing/syncthing#5179]
Hello, I'm trying out syncthing and I ran into an issue with a shared directory that contains symlinks only.

 - I shared a ~/sync/mydir directory the whose content is just 2 symlinks
 - I expected the content of the files pointed by the symlinks to be sent over to the other devices; instead broken symlinks got created on the other devices, as their target doesn't exist (if the content was already there I wouldn't need syncthing here); I also expected to find a per-share or global option like "follow symlinks" but I couldn't find any
 - create a directory with a symlink and share it with other devices

Please note that reversing the links is not an option (ie: I can't put the actual files in the shared directory and the symlinks in the original directory) because the program that generates these two files might delete and re-create them, thus destroying the link each time.

Syncthing Version: v0.14.50
OS Version: SailFishOS (Linux, ARM)
Browser Version: w/e the default browser is on SFOS

**Comment by calmh** [comment]
Symlinks are not followed and will not be; this is a design decision. Sorry.

**Comment by KingDuckZ** [comment]
I won't hide my disappointment given how quickly my problem got dismissed. I'll look into other solutions, pity because syncthing looked promising.
