### ISSUE TITLE
Docker image fails when PGID set to existing group

### ISSUE THREAD

**Issue by nvllsvm** [syncthing/syncthing#5180]
The Docker image for 0.14.50 fails to start when the `PGID` environment variable is set to `100`

```
$ docker run --net=host -e PUID=1000 -e PGID=100 syncthing/syncthing
addgroup: gid '100' in use
```

### Version Information

Syncthing Version: v0.14.50
OS Version: Arch Linux, macOS High Sierra

**Comment by calmh** [comment]
Yeah there's brokenness
