### ISSUE TITLE
Remove pending folders if remote device no longer announces them

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#5187]
This is somewhat niche and not critical, but could be considered a minor bug - all in all I labeled it as enhancement. A folder that was announced by a remote, then got removed on the remote, keeps being displayed as a new folder. It would be nice if pending folders in the config would be checked when receiving the cluster config and no longer pending devices were removed. This issue is relevant to .51 RC, so if fixed soon it could be included, but I don't consider it a necessity.

**Comment by acolomb** [comment]
I have a draft of such functionality working locally.  It's based on #6443, so will continue once that is merged.

**Comment by acolomb** [comment]
Related PR #7205 is ready for testing, if anyone is interested.
