### ISSUE TITLE
Javascript error in connection with new device notification

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#5190]
I just added a new device on .50-rc.2 and noticed the javascript error line at the top. The browser console shows:

```
Error: $scope.devices[i].pendingFolders is undefined
$scope.syncthingStatus@http://localhost:8384/syncthing/core/syncthingController.js:976:17
$parseFunctionCall@http://localhost:8384/vendor/angular/angular.js:12493:15
expressionInputWatch@http://localhost:8384/vendor/angular/angular.js:12902:31
$digest@http://localhost:8384/vendor/angular/angular.js:14423:34
$apply@http://localhost:8384/vendor/angular/angular.js:14694:13
scheduleApplyAsync/applyAsyncId<@http://localhost:8384/vendor/angular/angular.js:14984:11
completeOutstandingRequest@http://localhost:8384/vendor/angular/angular.js:4959:7
Browser/self.defer/timeoutId<@http://localhost:8384/vendor/angular/angular.js:5347:7
```

I haven't investigated any further.

It happens after pressing the save button when adding the new device.

**Comment by calmh** [comment]
I think this happens with a new config, i.e. first start? It looks the relevant things (non null slices) are set in DeviceConfiguration.prepare(). I'd have expected that to be called from Configuration.prepare(), but it's not - it's called from Configuration.clean() which is only run on unmarshal.

I think the prepare step should be properly recursive, and run both on new and unmarshal...

**Comment by AudriusButkevicius** [comment]
nvm, it's garbage coming from JS land.

**Comment by calmh** [comment]
Ya I missed the call via clean apparently so my analysis was crap, ignore
