### ISSUE TITLE
Should exit with code zero when run with `-help`

### ISSUE THREAD

**Issue by cyberb** [syncthing/syncthing#5193]
./syncthing -help
Usage: ...

echo $?
2

This is not very convenient for build scripts, is it possible to fix?

**Comment by calmh** [comment]
I think the original thinking was that syncthing didn't start and start syncing stuff, so error exit is appropriate. Checking a bunch of other tools I have lying around it looks like exit 0 for --help is more common. So yeah, we should probably do that instead.

**Comment by cyberb** [comment]
https://github.com/syncthing/syncthing/pull/5197
