### ISSUE TITLE
multiple guiAddress and listenAddress not supported

### ISSUE THREAD

**Issue by jpjp** [syncthing/syncthing#52]
It'd be useful it multiple guiAddress and listenAddress values were supported.

e.g. say I have three network cards, and I'd like to listen on localhost and the internal device.

The info string would also need to support this.

**Comment by HaleTom** [comment]
I'd also vote to be able to listen only on localhost and on my zerotier (VPN) interface.

For people using multiple VPNs, @jpjp's "use one address for both" won't work.
