### ISSUE TITLE
.stignore file gets crapped upon folder properties editing

### ISSUE THREAD

**Issue by tonis143** [syncthing/syncthing#5205]
I experienced this issue twice yesterday but did not reproduce it intentionally. When I opened the Ignore Patterns tab in the Edit Folder dialog, the list did not load immediately. Instead, the textbox was grayed and displayed “loading...” (or similar in other UI languages). I guess that to reproduce the bug you have to click the OK button while it's still grayed.

The problem was that the contents of .stignore was totally wiped and replaced with “loading...” (in Russian in my case).

### Version Information

Syncthing Version: v0.14.49
OS Version: Windows 8.1 x64
Browser Version: Comodo Dragon 68 (Chromium)

**Comment by AudriusButkevicius** [comment]
Do you see any errors in the console as to why it doesn't manage to load the file?

**Comment by imsodin** [comment]
Sounds like #4915, which was fixed in #4930 and v0.14.48. That's weird, because that code didn't change in v0.14.49.

**Comment by AudriusButkevicius** [comment]
Also, are you sure ignores got overwritten on this version? Or you only notived on this version?

**Comment by tonis143** [comment]
Sorry, my mistake. That was v47. This is a duplicate of #4915 indeed. Will upgrade soon and try to make myself learn how to search :(
