### ISSUE TITLE
testing cmd/syncthing with race detection takes way too long

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#5206]
I always get test timeouts due to cmd/syncthing since a while. It takes over 2min on my computer to run them. Without race detection it takes just about 10s. Looking at the build server testing cmd/syncthing took ~10s before #5169 and also ~2min after.

before: https://build.syncthing.net/viewLog.html?buildId=26720&buildTypeId=Syncthing_BuildLinuxCross&tab=buildLog#_state=106  
after: https://build.syncthing.net/viewLog.html?buildId=26783&buildTypeId=Syncthing_BuildLinuxCross&tab=buildLog&_focus=124#_state=124  

I have no clue why, but it is definitely annoying.

**Comment by calmh** [comment]
Yeah I noticed the same locally. Go 1.11 regression?

**Comment by calmh** [comment]
Test list shows three auth tests taking 30s each. Did we increase the time on auth fail? Seems excessive.

https://build.syncthing.net/viewLog.html?buildId=26783&buildTypeId=Syncthing_BuildLinuxCross&tab=testsInfo

<img width="977" alt="screen shot 2018-09-17 at 21 11 04" src="https://user-images.githubusercontent.com/125426/45644527-36c17200-babe-11e8-99ae-8962c40bcd44.png">

**Comment by imsodin** [comment]
I checked with go1.10.3 - same thing. I don't think it's an coincidence that the testing duration on the build server changed at the same time as a PR altering cmd/syncthing was merged.

**Comment by AudriusButkevicius** [comment]
I think some of these are new tests which just do some bcrypt checks.

**Comment by imsodin** [comment]
They do indeed look fairly inconspicuous. What's particular about the entire situation is that it takes ~10s without `-race` and ~2min with `-race`. The only semi-notable thing I see is that the new test file is the only place where 	`golang.org/x/crypto/bcrypt` is imported in a test. However I fail to see how that should cause slow testing under race detection.
