### ISSUE TITLE
GUI listen on unix socket

### ISSUE THREAD

**Issue by cyberb** [syncthing/syncthing#5208]
I want to start GUI on unix socket.

It is useful when you are using reverse proxy like nginx with multiple apps on a single IP address/machine.

I could try adding that feature if that is ok.

**Comment by AudriusButkevicius** [comment]
I think there already exists an issue for this (supporting multiple gui listen addresses).

There was a half attempted pr (potentially closed) that discussed a lot of details how we evisioned this in case you want to have a stab at it.

**Comment by cyberb** [comment]
That incomplete pr still has no unix:
https://github.com/syncthing/syncthing/pull/4433/files#diff-08cb9d814d52dd7eb886f63a0fe1b847R199
I am not really interested in multiple guis, i need one with unix listener.
So will you consider a new pr with just unix support?

**Comment by AudriusButkevicius** [comment]
The promise to the community was that this will be delivered with multiple address support (as I agree having either one or the other only sucks), but I guess if unix file support comes first cleanly, there is no harm, but it would be very shitty as you couldn't access the web ui without a fronting proxy.

**Comment by cyberb** [comment]
As an admin you can enable unix socket if you have the need, if not you enable http.

**Comment by calmh** [comment]
Duplicate of #3616

**Comment by Ferroin** [comment]
@AudriusButkevicius I'd be willing to bet that the set of people who care about having UNIX socket support is a (most likely proper) subset of those who are already proxying the web UI through software which supports UNIX socket connections to backends.

**Comment by AudriusButkevicius** [comment]
Sure, but if your proxy is stuffed, you might want to be able to access locally. Most command line tools we have expect tcp too
