### ISSUE TITLE
Reconnecting over relays after interrupted connection fails

### ISSUE THREAD

**Issue by l-jonas** [syncthing/syncthing#5219]
When the connection over an relay is lost (no close message), then reconnecting over an relay again fails due to <https://github.com/syncthing/syncthing/blob/9e00b619abea1345487f2f1acb9877bf0fdac445/lib/connections/service.go#L242> (I get the message "device reconnected" in the log and it's only there in the source code). Reconnecting over a local network works (I assume that has got a higher priority). 

Eventually it would be possible to solve this by always switching connections if both are using an relay.

This is relevant for syncthing-lite. A clean shutdown would be possible but it would reduce the usability and is not always possible due to connection drops. And it's better if one does not have to wait for an timeout until reconnecting is possible.

**Comment by calmh** [comment]
I'm not with you. There's nothing in there about "device reconnected", and we don't typically rely on the Close message to detect lost connections. What's your *actual* log extract, from losing the connection to the problem showing up, whatever it is?

**Comment by l-jonas** [comment]
- Environment: 2 machines (called A and B)
- A and B use different internet entry points (B is using an hotspot from an smartphone)

Syncthing startup at machine A:

```
[monitor] 12:14:49 INFO: Starting syncthing
[GPBQC] 12:14:49 INFO: syncthing v0.14.50-ds1 "Dysprosium Dragonfly" (go1.10.3 linux-amd64) debian@debian 2018-09-15 02:39:24 UTC [noupgrade]
[GPBQC] 12:14:49 INFO: My ID: REMOVED
[GPBQC] 12:14:50 INFO: Single thread SHA256 performance is 357 MB/s using minio/sha256-simd (350 MB/s using crypto/sha256).
[GPBQC] 12:14:51 INFO: Hashing performance is 300.46 MB/s
[GPBQC] 12:14:51 INFO: Starting deadlock detector with 20m0s timeout
(once per folder) [GPBQC] 12:14:51 INFO: Ready to synchronize REMOVED (REMOVED) (sendreceive)
[GPBQC] 12:14:51 INFO: Overall send rate is unlimited, receive rate is unlimited
[GPBQC] 12:14:51 INFO: Rate limits do not apply to LAN connections
[GPBQC] 12:14:51 INFO: Using discovery server https://discovery-v4.syncthing.net/v2/?nolookup&id=REMOVED
[GPBQC] 12:14:51 INFO: Using discovery server https://discovery-v6.syncthing.net/v2/?nolookup&id=REMOVED
[GPBQC] 12:14:51 INFO: Using discovery server https://discovery.syncthing.net/v2/?noannounce&id=REMOVED
[GPBQC] 12:14:51 INFO: TCP listener ([::]:22000) starting
[GPBQC] 12:14:51 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting
[GPBQC] 12:14:51 INFO: Completed initial scan of sendreceive folder "Default Folder" (default)
[GPBQC] 12:14:51 INFO: GUI and API listening on 127.0.0.1:8384
[GPBQC] 12:14:51 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
(multiple times for different devices) [GPBQC] 12:14:51 INFO: Device REMOVED is REMOVED at [dynamic]
(multiple times for different folders) [GPBQC] 12:14:51 INFO: Completed initial scan of sendreceive folder REMOVED
[GPBQC] 12:15:02 INFO: Detected 1 NAT service
[GPBQC] 12:15:11 INFO: Joined relay relay://REMOVED
```

Then starting syncthing at machine B; A logs the following

```
[GPBQC] 12:19:34 INFO: Established secure connection to REMOVED at REMOVED/relay-server (TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305)
[GPBQC] 12:19:34 INFO: Device REMOVED client is "syncthing v0.14.50" named REMOVED at REMOVED/relay-server
```

Now disabling the hotspot of the smartphone which creates the hotspot and then shutting down syncthing at B; A logs nothing for that

Now enabling the hotspot of the smartphone and reconnecting to it from B and starting syncthing at B; A logs the following

```
[GPBQC] 12:24:22 INFO: Connected to already connected device REMOVED (existing: REMOVED/relay-server new: REMOVED/relay-server)
[GPBQC] 12:24:34 INFO: Connected to already connected device REMOVED (existing: REMOVED/relay-server new: REMOVED/relay-server)
```

and B continues to show not connected

Due to <https://github.com/syncthing/syncthing/blob/9e00b619abea1345487f2f1acb9877bf0fdac445/lib/connections/service.go#L222> I think that ``c.Close()`` cancels the connection attempt. And the same happens at <https://github.com/syncthing/syncthing/blob/9e00b619abea1345487f2f1acb9877bf0fdac445/lib/connections/service.go#L241> which was executed in my case (this is the only location in the source code with the string "Connected to already connected device").

**Comment by calmh** [comment]
You are still within the ping timeout, so the dead client hasn't been detected (even by the relay). This is how TCP works - just killing the network connection for a machine does not mean connections go down. They go down when some higher level detects they are down.

There is a comment saying essentially "maybe we should replace the old connection with the new, instead of dropping the new" which would solve your case, but that's not implemented.

**Comment by l-jonas** [comment]
I know that this is not implemented. That's why I suggest to change it. My first idea was to always use the new connection when the new and the old one were over an relay, but I've got an better one now: It would be possible to check how long the old connection existed and use the new one if the older one is older than 5 seconds. This should handle the case that two devices are connecting to each other parallel.

I created an issue and no pull request because I don't have any go knowledge.

**Comment by calmh** [comment]
Right, and that's a reasonable ask. However the initial issue description is confusing enough and far enough away from that goal that I didn't understand that. I'm going to close this issue and open a related one that is clear on that from the beginning; no offense intended. :)
