### ISSUE TITLE
Out of sync folders show negative size

### ISSUE THREAD

**Issue by Script-Mak3r** [syncthing/syncthing#5220]
Occasionally, when receiving files from a remote device, the relevant folder will be marked as out of sync, with a positive number of out of sync items with negative size. For example, I had been sent four files, which were marked as out of sync, with a total size of ~-68,999 B. Note, however, that this eventually goes away on its own.

I hypothesize that these files may, in fact, be synced, and Syncthing fails to properly recognize this, but I have not tested this.

### Version Information

Syncthing Version: v0.14.50
OS Version: Windows 10 (64 bit)
Browser Version: SyncTrayzor v1.1.21

**Comment by EserGozcu** [comment]
probably https://github.com/syncthing/syncthing/issues/4570
