### ISSUE TITLE
Docker container fails printing password prompt

### ISSUE THREAD

**Issue by tprk77** [syncthing/syncthing#5225]
Following the `README-Docker.md`, I run the command and get:

```
user@server:~$ sudo docker run --rm -p 8384:8384 -p 22000:22000 -v /path1:/var/syncthing/config -v /path2:/var/syncthing syncthing/syncthing:latest
Changing password for syncthing
New password: 
passwd: password for syncthing is unchanged
user@server:~$ 
```

Please let me know if I can provide any more details. (Sorry, I'm not really sure how to debug this myself.) If I run the command with `-it` it will actually prompt for a password and eventually work. But I'm guessing the password prompt shouldn't actually be necessary and it's a mistake of some sort.

**Comment by calmh** [comment]
Yeah, it's been fixed and will be in next release. In the meantime rebuild with the Dockerfile from master or see if the previous version image works better. Sorry.
