### ISSUE TITLE
Watcher fails due to filepath.EvalSymlinks error (FindFirstFile)

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#5226]
Original report in https://forum.syncthing.net/t/findfirstfile-error/12140

Apparently in specific situations `filepath.EvalSymlinks` fails when given a path with the `\\?\` prefix. One confirmed case is with a ram disk with IMDesk drivers.

**Comment by AudriusButkevicius** [comment]
This should be raised with Go folks.
