### ISSUE TITLE
Using Syncthing in Nextcloud as a NextcloudApp

### ISSUE THREAD

**Issue by JulienAMOURIQ** [syncthing/syncthing#5228]
Bonjour,
J'utilise Syncthing chez moi. Cela fonctionne à merveille !

J'ai également un serveur Nextcloud. Cela serait vraiment pratique de pouvoir synchroniser l'un des répertoire de mon Nextcloud en utilisant Syncthing. Est-ce que vous avez prévu une telle application pour Nextcloud? 

//

Hi,
I use syncthing.
It works great !

I also use nextcloud. It would be awesome to be able to sync one of my nextcloud folder using Syncthing . 
I would like to know if an app like that could be released in the future?

**Comment by imsodin** [comment]
Please post to the forum for support questions. There are already several discussions on nextcloud: https://forum.syncthing.net/search?q=nextcloud
