### ISSUE TITLE
Consider moving to Fork-Awesome or another free font

### ISSUE THREAD

**Issue by aviau** [syncthing/syncthing#5236]
Hello!

It has come to my attention that Syncthing has moved from Font-Awesome v4 to Font-Awesome v5.

While I am sure that the intention was simply to update to the latest and greatest, it comes at the cost of making Syncthing impossible to build from source.

As of v5, FontAwesome has switched to a proprietary build system and it is no longer possible to build the icons. Of couse, this was done silently and I am sure you were not aware of this when migrating. 

We have been in contact with Font-Awesome developpers (see #[902981](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902981#76)) and they have responded clearly:
 > the first question to get out of the way is: “Will Font Awesome open source their build tool?”
>
> And the answer is no for the time being.

This makes it impossible, for example, for Font-Awesome v5 to be included in Debian.

The community has already reacted to this, and the Fork-Awesome project was created, which is a fork of Font-Awesome v4, back when the build system was still available:
 - https://forkawesome.github.io/Fork-Awesome/
 - https://github.com/ForkAwesome/Fork-Awesome

I have gotten in touch with the guys at Fork-Awesome and they have been open consider a v5 compatibility layer, which they have already started working on, making it much easier to migrate to Fork-Awesome for Font-Awesome v5 users. See the following discussion: https://github.com/ForkAwesome/Fork-Awesome/issues/112

I have tested this compatibility layer with Syncthing and have gotten positive results. However, if Syncthing starts using icons that are not included in Fork-Awesome, then there is nothing that a compatibility layer will be able to do.

Would Syncthing consider migrating to Fork-Awesome?

**Comment by calmh** [comment]
I don't particularly care which icon set we use, so long as it looks reasonable and includes the basics we need. So yeah, sure.

**Comment by aviau** [comment]
Great. The guys at Fork-Awesome have completed their compatibility layer and I intend to open a pull request to Syncthing soon.
