### ISSUE TITLE
TestWatchIgnore test failure on OpenBSD

### ISSUE THREAD

**Issue by vext01** [syncthing/syncthing#5243]
As discussed in #5077, the `TestWatchIgnore` test is failing on OpenBSD.

```
fremen% STTRACE=fs go test -v -run TestWatchIgnore
=== RUN   TestWatchIgnore
2018/10/05 14:33:26.878085 logfs.go:73: DEBUG: basicfs_watch_test.go:363 basic /home/porter/go/src/github.com/syncthing/syncthing/lib/fs/testdata MkdirAll ignore 493 <nil>
2018/10/05 14:33:26.878817 logfs.go:133: DEBUG: basicfs_watch_test.go:371 basic /home/porter/go/src/github.com/syncthing/syncthing/lib/fs/testdata Watch ignore {ignore/ignored  true} false <nil>
2018/10/05 14:33:26.878887 logfs.go:73: DEBUG: basicfs_watch_test.go:339 basic /home/porter/go/src/github.com/syncthing/syncthing/lib/fs/testdata MkdirAll ignore 493 <nil>
2018/10/05 14:33:26.879139 logfs.go:43: DEBUG: basicfs_watch_test.go:342 basic /home/porter/go/src/github.com/syncthing/syncthing/lib/fs/testdata Create ignore/file {0xc00000c068 ignore/file} <nil>
2018/10/05 14:33:26.879189 logfs.go:73: DEBUG: basicfs_watch_test.go:339 basic /home/porter/go/src/github.com/syncthing/syncthing/lib/fs/testdata MkdirAll ignore 493 <nil>
2018/10/05 14:33:26.879387 logfs.go:43: DEBUG: basicfs_watch_test.go:342 basic /home/porter/go/src/github.com/syncthing/syncthing/lib/fs/testdata Create ignore/ignored {0xc00000c070 ignore/ignored} <nil>
2018/10/05 14:34:26.886073 logfs.go:103: DEBUG: basicfs_watch_test.go:386 basic /home/porter/go/src/github.com/syncthing/syncthing/lib/fs/testdata RemoveAll ignore remove /home/porter/go/src/github.com/syncthing/syncthing/lib/fs/testdata/ignore: directory not empty                                                    
--- FAIL: TestWatchIgnore (60.01s)
    basicfs_watch_test.go:382: Timed out before receiving all expected events
FAIL
exit status 1
FAIL    github.com/syncthing/syncthing/lib/fs   60.021s
```

OpenBSD-6.4-beta/Syncthing master.

Cheers

**Comment by vext01** [comment]
(I have more failures to file, but wanted to wait and see if I've run the test properly with all the required output. Please let me know -- I know nothing about go).

**Comment by imsodin** [comment]
I am a bit confused about your statement that the test is not failing in isolation (I assume this means running just that test, instead of all tests), but then it looks like you provide an example of that test failing when run alone?

Also, how is this new issue different from #5077? (no offense intended, I am just not getting it)

It looks like other `TestWatch*` functions are passing, right? Then it's not a total failure of the backend, but likely something weird about our testing. And again, that's a hard problem to debug (at least for me, it's not the first time I debug that part of the code) and I don't have the setup or time at the moment to do so. Just to be transparent in terms of likelihood of this getting fixed soon (from my side).

**Comment by vext01** [comment]
> I am a bit confused about your statement that the test is not failing in isolation

Oops, I was supposed to delete that line. There are two tests which exhibit this behaviour, but not this one!

To be clear, this test *always* fails.

> Also, how is this new issue different from #5077?

Gah, it's a duplicate. I'm not having a good day.

Shall I close this?

> I don't have the setup or time at the moment to do so.

This may not help with time restrictions, but if it helps I'm happy to throw up an OpenBSD VM with SSH access if that would help. If we do want to go down that route, then we should agree a date when someone is available to debug it, as I'd be paying for the VM.

> please always state the commit (or version) you are on

Sure, this is:
`f528923d1ef224a07d58fea21b0dca14ca18ba78`

**Comment by AudriusButkevicius** [comment]
Closing as dup
