### ISSUE TITLE
Impossible to change device name from web UI

### ISSUE THREAD

**Issue by Issam2204** [syncthing/syncthing#5249]
I'm not sure if I'm doing something wrong, but I'm trying to change the device name from the web UI and it looks like it ignores whatever device name I specify. By default it uses the hostname (fair enough), but changing it does nothing. 

I'm using Ubuntu 16.04.5 x64 server and Syncthing v0.14.51.

Thanks!

**Comment by calmh** [comment]
Can confirm, it just changes back immediately. (macOS / Safari here)
