### ISSUE TITLE
Upgrade SSL Certificate to use modern cipher

### ISSUE THREAD

**Issue by Jtasiu** [syncthing/syncthing#5256]
If you use install the SSL certificate to use HTTPS for the web GUI it uses an old cipher method. 

Please upgrade SSL Certificate to support modern TLS cipher method like ChaCha-Poly1305 or at least AES GCM.

**Comment by calmh** [comment]
This looks OK to me.

```
jb@kvin:~ $ ./test
tls1:	ECDHE-RSA-AES256-SHA
tls1:	AES256-SHA
tls1:	ECDHE-RSA-AES128-SHA
tls1:	AES128-SHA
tls1:	ECDHE-RSA-DES-CBC3-SHA
tls1:	DES-CBC3-SHA
tls1_1:	ECDHE-RSA-AES256-SHA
tls1_1:	AES256-SHA
tls1_1:	ECDHE-RSA-AES128-SHA
tls1_1:	AES128-SHA
tls1_1:	ECDHE-RSA-DES-CBC3-SHA
tls1_1:	DES-CBC3-SHA
tls1_2:	ECDHE-RSA-AES256-SHA
tls1_2:	AES256-SHA
tls1_2:	ECDHE-RSA-AES128-GCM-SHA256
tls1_2:	ECDHE-RSA-AES128-SHA
tls1_2:	AES128-SHA
tls1_2:	ECDHE-RSA-DES-CBC3-SHA
tls1_2:	DES-CBC3-SHA
[1]
jb@kvin:~ $ cat test
#!/bin/sh

for v in tls1 tls1_1 tls1_2; do
 for c in $(openssl ciphers 'ALL:eNULL' | tr ':' ' '); do
  openssl s_client -connect localhost:8384 -verify 0 -cipher $c -$v </dev/null 2>&1 | grep -q 'BEGIN CERTIFICATE' && echo "$v:\t$c"
 done
done
jb@kvin:~ $
```

(Also limited by what my openssl supports, which for example doesn't include the chacha stuff)

Generally speaking, we don't want or need to be bleeding edge on the GUI. We want something that's reasonably secure enough and supports a lot of browsers.

The sync connection is different.

**Comment by calmh** [comment]
I misremembered; I though we ran with the Go defaults which should be good enough, but we already have a hardcoded list to git rid of old RC4 stuff. So we should update that or, better, see if the defaults are now acceptable.
