### ISSUE TITLE
Stuck at 0%

### ISSUE THREAD

**Issue by TheDevKiller** [syncthing/syncthing#5265]
# Version Information

Syncthing Version: v0.14.49
OS Version: Manjaro 17.1.12 Hakoila
Browser Version: Firefox 62.0.3

# Bug
I have one only folder shared to my tablet and when I try to share it the PC says "Syncing (0%, 626 MiB)" and the tablet says the folder isn't synchronized

# Screenshots
### PC
![screenshot](https://user-images.githubusercontent.com/39555268/46832091-6d309b00-cda5-11e8-8a2f-34e5963a7b71.png)
### Tablet
![screenshot_2018-10-11-22-32-17](https://user-images.githubusercontent.com/39555268/46832179-af59dc80-cda5-11e8-870b-9ba11f0b9c74.png)

**Comment by calmh** [comment]
Support is [https://forum.syncthing.net/](over there).
