### ISSUE TITLE
Syncthing/SyncTrayzor appear to misreport (UNDERreport) sync status

### ISSUE THREAD

**Issue by ogrfnkl** [syncthing/syncthing#5269]
I am using SyncThing to mirror a 9.7GB folder structure from a laptop to an Android phone over WiFi. The folder on Android is a receive-only folder and the sharing request originated from the phone and was accepted on the laptop. The syncing seemed to be proceeding smoothly at first, but then I started seeing that the percentage was not advancing evenly, but rather would go up and down. I let the process continue until the data transfer came to a complete stop and re-scanning did not produce any further bursts. The syncing percentage indicator on SyncTrayzor ended up showing only 51% or 4.48 GB, as shown in the attached screenshot:

![2018-10-12 13_56_39 - synctrayzor](https://user-images.githubusercontent.com/20609845/46888655-b4ab3b80-ce26-11e8-8168-b39531712e4d.png))

When I checked the folder on the phone, however, I realized that 100% of the expected files were there. Clicking on the sync percentage in SyncTrayzor opens up a window where all the supposedly unsynced files are shown, but I have confirmed that those files did, in fact, get to their destination. Something is preventing SyncTrayzor from recognizing that the sync was completed successfully.

### Version Information

Syncthing Version: v0.14.51 (SyncTrayzor version: 1.1.22)
OS Version: Windows 10 Pro

**Comment by calmh** [comment]
This might be a bug, but until it's narrowed down it's a support issue which is handled [on the forum](https://forum.syncthing.net/), thanks.
