### ISSUE TITLE
Distributed integration test suite

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#527]
Currently the integration tests run on a single platform at a time, and only a unixy one at that. However there are a bunch of issues that only pop up when syncting Windows <-> Unix, mainly regarding thinkos in filename normalization. It would be good if there was an integration test suite that could be run automatically on at least two boxes that talk to each other. Possibly it would be easiest to make sure this runs on Windows and can remote control one or more unixy boxes over ssh... Since there is an ssh client library in Go, the integration could be a self contained program that one just "go run":s on Windows, with an ssh key in a file somewhere.

**Comment by Zillode** [comment]
What about letting Jenkins start the test suite on slaves with different OSes. Then, each slave sets up a reverse ssh tunnel to a 'main' server to make its port available to other slaves. When this is done we can run the integration tests whereby each `SyncthingProcess` is assumed to be running on another machine.
We can use an ordered argument list to the `go run` process to decide which SynchtingProcess should be running on a given machine (e.g. `['linux', 'osx', 'windows', 'android']` whereby the linux machine takes responsibility for `SyncthingProcess1`)
