### ISSUE TITLE
Wrong syncronization status

### ISSUE THREAD

**Issue by paolobenve** [syncthing/syncthing#5273]
From syncthing web I added a remove device which was offline: I had the device id and I put it in the proper place.

After that I defined a folder to syncronize with the remote device I had just created.

After a few seconds, the folder bar said (and still says) "Syncronized". But the device never went online.

### Version Information

Syncthing Version: v0.14.48, Linux (ARM)
OS Version: debian (Netgear ReadyNas)

**Comment by imsodin** [comment]
That's expected behaviour, please use forum.syncthing.net for support.

**Comment by paolobenve** [comment]
I think this is not the expected behaviour. I want to be sure that my files are syncronized on the remote device(s). I think syncthing should say "syncronized" when it's sure that it's so.

Suppose I have everything syncronized, but the remote device is offline. I modify a file on my device. Since the remote device isn't online, syncthing still says "syncronized", but the remote device isn't: the user is deceived; however, he/she can check the remote status, and see that it's offline. But if the day after the user checks syncthing again, and he/she see "syncronized", there is no way to know whether remote is syncronized or not, the user should know whether the remote has gone online.

**Comment by imsodin** [comment]
forum.syncthing.net please.
