### ISSUE TITLE
Debian instructions pulled in Debian's syncthing instead of Syncthing's syncthing

### ISSUE THREAD

**Issue by genpfault** [syncthing/syncthing#5275]
Just tried the instructions on [Syncthing's Debian package landing page](https://apt.syncthing.net) and the final install command:

    sudo apt-get install syncthing

...pulled in [Debian's `0.14.51+ds2-3`](https://packages.debian.org/buster/syncthing) instead of Syncthing's `0.14.51`.  I guess because Debian's version is "greater" somehow?  Unfortunately Debian's version has broken icon fonts :(

Using `-t syncthing` pulled in the correct version and fixed the font issue for me:

    sudo apt-get install -t syncthing syncthing

Syncthing Version: v0.14.51
OS Version: Debian 10/Buster/testing (amd64), up-to-date as of today
Browser Version: Firefox 62.0.3

**Comment by imsodin** [comment]
Can you move this issue to the appropriate repo please: https://github.com/syncthing/apt-web

**Comment by genpfault** [comment]
Whoops, sorry about that :(  Filed [#13](https://github.com/syncthing/apt-web/issues/13) over there.
