### ISSUE TITLE
Syncthing causing Asus router logs "miniupnpd: HTTP Connection closed unexpectedly"

### ISSUE THREAD

**Issue by KkOuuj9Z** [syncthing/syncthing#5285]
Syncthing Version: v0.14.50, FreeBSD (64 bit)

I have syncthing running on a machine behind an Asus RT-AC66U (running [John's fork](https://www.snbforums.com/threads/fork-asuswrt-merlin-374-43-lts-releases-v36e4.18914/)). Occasionally the router has memory issues and needs to be rebooted. In the Asus logs I see lines like
```
Oct 23 08:15:06 miniupnpd[4997]: HTTP Connection from 192.168.1.252 closed unexpectedly
Oct 23 08:15:06 miniupnpd[4997]: HTTP Connection from 192.168.1.252 closed unexpectedly
```
which correlate with logs in Syncthing:
```
2018-10-23 08:15:16 New NAT port mapping: external TCP address x.x.x.x:37759 to local address 0.0.0.0:22000.
2018-10-23 08:15:16 New NAT port mapping: external TCP address x.x.x.x:49290 to local address 0.0.0.0:22000.
2018-10-23 08:15:16 Detected 2 NAT services
```
When I stop syncthing the Asus router has no problems. If I disable NAT traversal in syncthing I get no problems.

Is syncthing sending bad upnp messages to the router and causing a memory leak?

**Comment by calmh** [comment]
We think we are not, and the issue is in too verbose logging in miniupnpd: #4891. Of there is data to the contrary I’ll be happen to reopen and fix whatever is deemed the problem.

**Comment by amatus-** [comment]
I think there is still some kind of problem.

On my server where miniupnpd is configured I see this in the logs:

```
Oct 15 00:47:35 *** miniupnpd[2040]: HTTP Connection from 192.168.2.2 closed unexpectedly
Oct 15 00:47:35 *** miniupnpd[2040]: HTTP Connection from 192.168.2.2 closed unexpectedly
```

And in the iptables I see the following port mapping:
```
Chain MINIUPNPD (1 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             192.168.2.2          tcp dpt:22000
ACCEPT     tcp  --  anywhere             192.168.2.2          tcp dpt:22000
```

**Comment by AudriusButkevicius** [comment]
I don't think there is nothing new (nor wrong) in what you've posted, it's still too verbose logging from miniupnpd side.
