### ISSUE TITLE
Security: systemd service hardening

### ISSUE THREAD

**Issue by Kriechi** [syncthing/syncthing#5286]
Feature request / request for comments:

systemd provides various options to increase security and control to the kernel and various filesystem paths:
https://gist.github.com/ageis/f5595e59b1cddb1513d1b425a323db04

I have used the following set in various other service / unit files:

```
      PrivateTmp=true
      ProtectSystem=strict
      # ProtectHome=true (probably would block syncthing from creating new folders et al)
      PrivateDevices=true
      ProtectKernelTunables=true
      ProtectKernelModules=true
      ProtectControlGroups=true
      NoNewPrivileges=true
```

strelaysrv already includes some of these options:
https://github.com/syncthing/syncthing/blob/7f55fbbe8415e9ff30db1aec02563590fa068650/cmd/strelaysrv/etc/linux-systemd/strelaysrv.service#L11-L14

syncthing does not include any at the moment:
https://github.com/syncthing/syncthing/blob/7f55fbbe8415e9ff30db1aec02563590fa068650/etc/linux-systemd/user/syncthing.service
https://github.com/syncthing/syncthing/blob/7f55fbbe8415e9ff30db1aec02563590fa068650/etc/linux-systemd/system/syncthing%40.service

There is an open PR for discosrv that includes similar options as strelaysrv:
https://github.com/syncthing/discosrv/pull/19/files
(stale PR, should be closed - at least in that repo)

---------

I would be interested in your thoughts or guidelines on improving service security by adding some of these options. Do you see a benefit? Would you recommend them - or even add them to the template service file included in the deb packages?

### Version Information

OS Version: Ubuntu / Debian / Linux

**Comment by calmh** [comment]
Some of these should be fine to enable (the kernel stuff) but also mostly irrelevant as syncthing should not run as root. Others I don't know. Needs someone who knows systemd, and some testing.
