### ISSUE TITLE
"Panic: Send on closed channel" on the receiving end of an distribution system

### ISSUE THREAD

**Issue by schneeemensch** [syncthing/syncthing#5287]
Hey everyone,

I am getting panics on a lot of my devices in a distribution setup. I do not get them on the master which is the only device set to "sendonly", but on many of the receiving devices.
In my setup the folder on the master is constantly changing until one point after which I collect the completion and unshare the folder after all devices are in sync.

Sometimes the sync gets stuck on several machines with the same amount on missing files over long periods of time >>1h. 
The panics are almost exclusively "Send on closed channel" panics.

I have sanitized a panic log of one of the receiving machines.
[syncthing_panic.log](https://github.com/syncthing/syncthing/files/2510972/syncthing_panic.log)

### Version Information

Syncthing Version: v0.14.50
OS Version: different Linux distributions: CentOS 6.(6/9), 7.(1/3) / Ubuntu 16.04.(1/2), 14.04.(0/5) / Suse 11.4/12.2 / RedHat 6.(6/7/8) /

**Comment by imsodin** [comment]
Is the stacktrace part of the log complete?

I can't make any sense of it: The first stack shows the panic when sending to `scanChan` during `performFinish`/`finisherRoutine` started from `pullerIteration`. The last stack shows the same folder happily working away in `processNeeded`/`pullerIteration`/`pull`. `scanChan` is closed in a function deferred in `pull`, i.e. I see no reason why it should be closed at the time of the panic.

**Comment by schneeemensch** [comment]
Oh sorry. I see that I only got the shorter version of the trace. I had two versions laying around.
I will post the first one tomorrow from work. I do not have access from here.

**Comment by schneeemensch** [comment]
[syncthing_panic.log](https://github.com/syncthing/syncthing/files/2513933/syncthing_panic.log)

Here is the full one

**Comment by imsodin** [comment]
There's multiple db updater/finisher/puller routines for the same folder instance, and just one pull/pull iteration. This smelled like #5233 to me at first, but that's about multiple folder instances. A puller iteration can't return unless all routines have finished, so that's just another mystery. I somehow suspect I am making a blatant oversight, maybe @AudriusButkevicius or @calmh can see it.

**Comment by schneeemensch** [comment]
Today I received lots of "Panic: bug: ClusterConfig called on closed or nonexistent connection" panics on several devices including one of the distributing ones.

I currently have 3 sendonly masters which share their distinct folders over an partially overlapping set of receiving devices. All 3 of these clusters are fully connected to each other. Due to an error on my side one cluster was bigger than before and contained 20 machines. 
 
I can share a log about the ClusterConfig panic as well if necessary. I have 202 panic logs just from today. Write me which could be interesting and I will sanitize them

**Comment by imsodin** [comment]
Ah, the suture panic recovery stuff happened in 0.14.51. Just to be sure that this is not some weird side effect of those cluster config panics, could you update and see whether it still happens (not the cluster config panics, but the send on closed channel ones)?

**Comment by schneeemensch** [comment]
Ok, I will update and probably report tomorrow. I am not sure if I can reproduce it during the day. 

The "Send on closed channel" and ClusterConfig panics appear on different machines. While looking for similar timestamps I noticed that almost all "send on closed channel" panics appeared at the same time over different machines, but they did not overlap with the ClusterConfig panics.

Could you point me in a direction to solve the ClusterConfig panics?

**Comment by schneeemensch** [comment]
[syncthing_panic_logfiles.log](https://github.com/syncthing/syncthing/files/2514329/syncthing_panic_logfiles.log)

These are all the logfiles and the panic reasons for tonight's sync. 
The Windows and Linux machines are not connected with each other. 
As you can see the majority of panics were due to ClusterConfig tonight.

**Comment by imsodin** [comment]
Unfortunately I can't point you at a solution, just at another open issue: https://github.com/syncthing/syncthing/issues/3906

And as cluster config and closed channel panics are not on the same machine, my hypothesis about interactions is wrong (unfortunately). Updating is still always a good idea.

**Comment by schneeemensch** [comment]
After updating to 0.14.51 I have not gotten any ClusterConfig or "send on closed channel" panics anymore.

But unfortunately I am now stuck with "panic: runtime error: index out of range" errors. But the sync performance was much better today and I did not get stuck during the sync. 
I do not know if this panic is just a different symptom of the same underlying problem or if its unrelated.

**Comment by schneeemensch** [comment]
Our use case is certainly very challenging, but so far I am really happy with the performance of Syncthing. Now the system just has to be stable enough to allow enrolling onto a wider use. But most stability issues are definitely in my scripts and not in Syncthing. I am just good in provoking.

I will open a thread about the new panic traces. I am close to start writing a log parser already :-)

Thanks for the quick support

**Comment by imsodin** [comment]
As far as I understood the problems in this issue were either fixed or disappeared - please feel free to reopen if that's not the case.
