### ISSUE TITLE
Errors running "ip" and "route" as snap package

### ISSUE THREAD

**Issue by popey** [syncthing/syncthing#5288]
On my Ubuntu machine where syncthing is running (from the snap) I was running `snappy-debug.security scanlog` (a tool snap packagers use to identify confinement problems) for another program, and noticed it complain about syncthing. Full log below.

It looks like the syncthing application is trying to call out to the /bin/ip and /sbin/route commands. These are not bundled in the snap, and confinement prevents them from running. You may need to bundle them via a `stage-packages` stanza in the snapcraft.yaml. `ip` appears to originate in the `iproute2` package and `route` is in the net-tools package. Hope that helps.

Syncthing Version:  v0.14.51, Linux (64 bit)
OS Version: Ubuntu 18.04

```
= AppArmor =
Time: Oct 24 19:50:59
Log: apparmor="DENIED" operation="exec" profile="snap.syncthing.syncthing" name="/sbin/route" pid=18198 comm="syncthing" requested_mask="x" denied_mask="x" fsuid=1000 ouid=0
File: /sbin/route (exec)
Suggestions:
* adjust snap to ship 'route'
* adjust program to use relative paths if the snap already ships 'route'

= AppArmor =
Time: Oct 24 19:50:59
Log: apparmor="DENIED" operation="exec" profile="snap.syncthing.syncthing" name="/bin/ip" pid=18199 comm="syncthing" requested_mask="x" denied_mask="x" fsuid=1000 ouid=0
File: /bin/ip (exec)
Suggestions:
* adjust snap to ship 'ip'
* adjust program to use relative paths if the snap already ships 'ip'
```

**Comment by calmh** [comment]
This is the `github.com/jackpal/gateway` package that uses these commands to figure out the current default gateway, which we use in `lib/pmp` to know which gateway to talk to.

**Comment by lhernanz** [comment]
Do you have any plans to fix this? Even if the call is made by one of the libraries that you are using, it is still generating noise in your application package. The errors are showing up in syslog so if you are monitoring apparmor violations, you find these coming up all the time.

It is interesting that the application seems to be ok even if this library is not working at all inside of the snap package. Therefore, an alternative might be that you detect that you are running inside snap and you completely skip the gateway detection.

**Comment by calmh** [comment]
It's an open issue so it's as planned as anything else. Contributions welcome as always. :)

**Comment by albertodonato** [comment]
FWIW it seems the library now parses `/proc/net/route` on linux, instead of running `ip` and `route`: https://github.com/jackpal/gateway/commit/4f6544a9d185ac5b5ed63252c91ca29ba1d353e7

So this is probably just a matter of updating the dependency.
