### ISSUE TITLE
Syncthing "read-only" Windows folder(s) to / through Linux servers

### ISSUE THREAD

**Issue by TigersWay** [syncthing/syncthing#5297]
Windows folders can be customized, which normally leads to the creation of 
- the desktop.ini file inside each folder
- and the "read-only" attribute set for the same folder.

But even "Microsoft" tells it's not really a read-only folder, just a special one. This is an image from @calmh comment on #3744, `Read-only (only applies to files in folder)`

Trying to sync that attribute or the change of that attribute from Windows to or through Linux will set the **real** read-only Linux features. 
Changing files in a "Windows read-only folder" is possible. But versioning in a Linux read-only folder is not.

From Syncthing Windows to Syncthing Linux with versioning, customizing a folder and changing anything inside it will lead to "permission denied" problems, which can only be solved manually. 

Syncthing Version: v0.14.51
OS Version: Windows 10 / Debian 9.

**Comment by AudriusButkevicius** [comment]
Not really sure what this issue is about. It doesn't follow any reasonable template, just a blob of text talking about something random that you seem have stated can be fixed by yourself.

**Comment by calmh** [comment]
I think they're trying to say that read only acts different on Windows and Linux, but when we sync permissions we copy one to the other. That is, setting a custom icon on a folder Windows-side will make the folder "read only", and we will do a chmod -w on the Linux side. It's not clear to me that this is the wrong behavior though. For better or worse we copy attributes when syncing, and we can't change how each OS/FS interprets that. If we didn't do this we would lose attributes along the way.

**Comment by TigersWay** [comment]
I would gladly follow a template, but could not find one.
I stated what is going wrong, in exactly what situation and environment. And added the syncthing errors could only be corrected by a manual intervention on the server file(s).
Please tell me what you would like me to add.

**Comment by calmh** [comment]
Audrius is referring to the issue template you are presented with when creating the issue. I think the relevant part in this case is

> If your issue is a bug report, replace this boilerplate with a description
> of the problem, being sure to include at least:
> 
>  - what happened,
>  - what you expected to happen instead, and
>  - any steps to reproduce the problem.

**Comment by TigersWay** [comment]
Sorry @calmh I sent my comment before I saw yours

You are right about copying attributes when syncing, of course. But the attribute called read-only on windows folder has nothing to do with the read only feature on linux.

Thanks for the template... I thought I did.

**Comment by TigersWay** [comment]
>  setting a custom icon on a folder Windows-side will make the folder "read only", and we will do a chmod -w on the Linux side

But as soon as that is done, versioning is not working anymore. Renaming/moving the file to the .stversions folder will be "permission denied"

**Comment by calmh** [comment]
That would be an entirely different problem not related to Windows "read only" directories at all. Versioning in Linux is supposed to work fine regardless of the permission bits on the directory. If this isn't the case, that merits an issue.

**Comment by TigersWay** [comment]
I hope someone else is going to confirm the issue then, because - as of now, for me - it only happens only inside a "read-only" windows folder. But there's maybe something else I cannot see yet.

Thanks anyway for taking the time.
