### ISSUE TITLE
Panic: found bad pointer in Go heap

### ISSUE THREAD

**Issue by ProactiveServices** [syncthing/syncthing#5306]
The device was syncing with another device at the time of the panic. RAM utilization peaked at 83% at the time of the panic. Once Syncthing had restarted and resumed syncing it peaked at 65% and completed the sync, dropping down to 26%.

Syncthing Version: v0.14.51
OS Version: Synology DS214+, DSM 6.2.1-23824. It's a dinky NAS.
go1.11 linux-arm
[Panic log](https://gist.github.com/ProactiveServices/822f8d6da99133206703580591298827)

**Comment by calmh** [comment]
This basically means random memory corruption and honestly I think the most likely cause is flaky hardware or cosmic rays. I think we don't build with fs notifications for the ARM cross builds, so there shouldn't be any cgo code running with the possibility of memory corruption coming from there...

As such I think this is impossible to debug and will close. Do yell if it happens again (especially on different hardware), or seems reproducible.

**Comment by ben-utzer** [comment]
I get this error very often lately. Happens a few time a day and is a arm (RaspberryPi as well)

Sorry for reopening the issue, but for me it looks like the exact same problem. @ProactiveServices did you have this problem again? 

Log:
`Nov 29 03:31:20 syncpi syncthing[26164]: runtime: pointer 0x2437bf5d to unallocated span span.base()=0x2e8a000 span.limit=0x2e8c000 span.state=0
Nov 29 03:31:20 syncpi syncthing[26164]: fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)
Nov 29 03:31:20 syncpi syncthing[26164]: runtime stack:
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.throw(0x69199f, 0x3e)
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/panic.go:608 +0x5c fp=0x1e39f84 sp=0x1e39f70 pc=0x3d0ac
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.findObject(0x2437bf5d, 0x0, 0x0, 0x487b140, 0x66d1edfc, 0x45)
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/mbitmap.go:399 +0x324 fp=0x1e39fa8 sp=0x1e39f84 pc=0x22854
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.wbBufFlush1(0x1c21300)
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/mwbbuf.go:252 +0xb0 fp=0x1e39fe0 sp=0x1e39fa8 pc=0x38f98
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.wbBufFlush.func1()
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/mwbbuf.go:195 +0x20 fp=0x1e39fe8 sp=0x1e39fe0 pc=0x6a538
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.systemstack(0x1e4e000)
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/asm_arm.s:354 +0x84 fp=0x1e39fec sp=0x1e39fe8 pc=0x6c100
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.mstart()
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/proc.go:1229 fp=0x1e39fec sp=0x1e39fec pc=0x4199c
Nov 29 03:31:20 syncpi syncthing[26164]: goroutine 80621 [running]:
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.systemstack_switch()
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/asm_arm.s:298 +0x4 fp=0x3d53a2c sp=0x3d53a28 pc=0x6c070
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.wbBufFlush(0x2020554, 0x0)
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/mwbbuf.go:194 +0x3c fp=0x3d53a38 sp=0x3d53a2c pc=0x38e78
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.gcWriteBarrier(0x2020554, 0x0, 0x2020540, 0x1, 0x0, 0x5df278, 0x8c96cd, 0x8, 0xee27b65, 0x2637400, ...)
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/asm_arm.s:966 +0x48 fp=0x3d53a38 sp=0x3d53a38 pc=0x6de48
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.deferreturn(0xee27b65)
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/panic.go:363 +0xa0 fp=0x3d53a58 sp=0x3d53a38 pc=0x3c7a4
Nov 29 03:31:20 syncpi syncthing[26164]: runtime: unexpected return pc for runtime.deferreturn called from 0x8
Nov 29 03:31:20 syncpi syncthing[26164]: stack: frame={sp:0x3d53a58, fp:0x3d53a78} stack=[0x3d53000,0x3d54000)
Nov 29 03:31:20 syncpi syncthing[26164]: 03d539d8:  00000f80  00001f80  66811901  00001000
Nov 29 03:31:20 syncpi syncthing[26164]: 03d539e8:  66a0fa9c  0002fe68 <runtime.gcmarknewobject+76>  66a0fa9d  00000010
Nov 29 03:31:20 syncpi syncthing[26164]: 03d539f8:  0001ae28 <runtime.mallocgc+1188>  66a0fa9d  66a0fa10  0000036c
Nov 29 03:31:20 syncpi syncthing[26164]: 03d53a08:  0000036c  0001b4b8 <runtime.newobject+44>  0ee27b60  00000008
Nov 29 03:31:20 syncpi syncthing[26164]: 03d53a18:  00000008  005df278  000196d4 <runtime.unlock+40>  00d27b02
Nov 29 03:31:20 syncpi syncthing[26164]: 03d53a28:  00038e78 <runtime.wbBufFlush+60>  0006de48 <runtime.gcWriteBarrier+72>  0082883c  0000036c
Nov 29 03:31:20 syncpi syncthing[26164]: 03d53a38:  0003c7a4 <runtime.deferreturn+160>  02020554  00000000  02020540
Nov 29 03:31:20 syncpi syncthing[26164]: 03d53a48:  00000001  00000000  005df278  008c96cd
Nov 29 03:31:20 syncpi syncthing[26164]: 03d53a58: <00000008  0ee27b65  02637400  0082888c
Nov 29 03:31:20 syncpi syncthing[26164]: 03d53a68:  0011ea8c <context.WithDeadline+616>  0925f4d4  0925f4d0  0011ea50 <context.WithDeadline+556>
Nov 29 03:31:20 syncpi syncthing[26164]: 03d53a78: >02020540  0082888c  0ee27b60  00000001
Nov 29 03:31:20 syncpi syncthing[26164]: 03d53a88:  0014ea40 <net.(*Dialer).DialContext+2044>  0487bb88  0ee27b60  0ee27b58
Nov 29 03:31:20 syncpi syncthing[26164]: 03d53a98:  0925f4d0  00d253a0  540bc0cd  00000002
Nov 29 03:31:20 syncpi syncthing[26164]: 03d53aa8:  0000074e  00d253a0  00000000  00000000
Nov 29 03:31:20 syncpi syncthing[26164]: 03d53ab8:  00000000  540bc0cd  00000002  0487bb80
Nov 29 03:31:20 syncpi syncthing[26164]: 03d53ac8:  0487bba4  0487bb88  00000000  00000000
Nov 29 03:31:20 syncpi syncthing[26164]: 03d53ad8:  00000000  00000000  00000000  00000000
Nov 29 03:31:20 syncpi syncthing[26164]: 03d53ae8:  00000000  00000000  00000000  00000000
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.deferreturn(0x82888c)
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/panic.go:363 +0xa0 fp=0x3d53a78 sp=0x3d53a58 pc=0x3c7a4
Nov 29 03:31:20 syncpi syncthing[26164]: created by github.com/syncthing/syncthing/lib/connections.dialParallel
Nov 29 03:31:20 syncpi syncthing[26164]:         /opt/tcagent/syncthing-work/src/github.com/syncthing/syncthing/lib/connections/service.go:775 +0x2a0
Nov 29 03:31:20 syncpi syncthing[26164]: goroutine 1 [chan receive, 133 minutes]:
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.gopark(0x8287dc, 0x3d66030, 0x170d, 0x3)
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/proc.go:302 +0xd8 fp=0x1f76f8c sp=0x1f76f78 pc=0x3f108
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.goparkunlock(0x3d66030, 0x170d, 0x3)
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/proc.go:308 +0x3c fp=0x1f76fa0 sp=0x1f76f8c pc=0x3f1a4
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.chanrecv(0x3d66000, 0x1f77144, 0x1, 0x6634)
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/chan.go:520 +0x2c8 fp=0x1f76fe8 sp=0x1f76fa0 pc=0x14f18
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.chanrecv1(0x3d66000, 0x1f77144)
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/chan.go:402 +0x20 fp=0x1f76ffc sp=0x1f76fe8 pc=0x14c20
Nov 29 03:31:20 syncpi syncthing[26164]: main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x666f78, 0x1, 0x0, ...)
Nov 29 03:31:20 syncpi syncthing[26164]:         /opt/tcagent/syncthing-work/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:917 +0x1714 fp=0x1f77e44 sp=0x1f76ffc pc=0x53b5f0
Nov 29 03:31:20 syncpi syncthing[26164]: main.main()
Nov 29 03:31:20 syncpi syncthing[26164]:         /opt/tcagent/syncthing-work/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:446 +0x2e4 fp=0x1f77fc4 sp=0x1f77e44 pc=0x537f4c
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.main()
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/proc.go:201 +0x204 fp=0x1f77fe4 sp=0x1f77fc4 pc=0x3ec98
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.goexit()
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/asm_arm.s:867 +0x4 fp=0x1f77fe4 sp=0x1f77fe4 pc=0x6ddb8
Nov 29 03:31:20 syncpi syncthing[26164]: goroutine 2 [force gc (idle), 95 minutes]:
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.gopark(0x8287dc, 0xd24e88, 0x61410, 0x1)
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/proc.go:302 +0xd8 fp=0x1c2afc0 sp=0x1c2afac pc=0x3f108
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.goparkunlock(0xd24e88, 0x1410, 0x1)
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/proc.go:308 +0x3c fp=0x1c2afd4 sp=0x1c2afc0 pc=0x3f1a4
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.forcegchelper()
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/proc.go:251 +0xb0 fp=0x1c2afec sp=0x1c2afd4 pc=0x3ef88
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.goexit()
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/asm_arm.s:867 +0x4 fp=0x1c2afec sp=0x1c2afec pc=0x6ddb8
Nov 29 03:31:20 syncpi syncthing[26164]: created by runtime.init.3
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/proc.go:240 +0x24
Nov 29 03:31:20 syncpi syncthing[26164]: goroutine 3 [GC sweep wait]:
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.gopark(0x8287dc, 0xd25048, 0x6140c, 0x1)
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/proc.go:302 +0xd8 fp=0x1c2b7c0 sp=0x1c2b7ac pc=0x3f108
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.goparkunlock(0xd25048, 0x8c140c, 0x1)
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/proc.go:308 +0x3c fp=0x1c2b7d4 sp=0x1c2b7c0 pc=0x3f1a4
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.bgsweep(0x1c48000)
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/mgcsweep.go:71 +0x114 fp=0x1c2b7e4 sp=0x1c2b7d4 pc=0x30308
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.goexit()
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/asm_arm.s:867 +0x4 fp=0x1c2b7e4 sp=0x1c2b7e4 pc=0x6ddb8
Nov 29 03:31:20 syncpi syncthing[26164]: created by runtime.gcenable
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/mgc.go:216 +0x40
Nov 29 03:31:20 syncpi syncthing[26164]: goroutine 4 [finalizer wait, 102 minutes]:
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.gopark(0x8287dc, 0xd389a0, 0x140f, 0x1)
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/proc.go:302 +0xd8 fp=0x1c2bf8c sp=0x1c2bf78 pc=0x3f108
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.goparkunlock(0xd389a0, 0x140f, 0x1)
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/proc.go:308 +0x3c fp=0x1c2bfa0 sp=0x1c2bf8c pc=0x3f1a4
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.runfinq()
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/mfinal.go:175 +0x90 fp=0x1c2bfec sp=0x1c2bfa0 pc=0x25cb4
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.goexit()
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/asm_arm.s:867 +0x4 fp=0x1c2bfec sp=0x1c2bfec pc=0x6ddb8
Nov 29 03:31:20 syncpi syncthing[26164]: created by runtime.createfing
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/mfinal.go:156 +0x60
Nov 29 03:31:20 syncpi syncthing[26164]: goroutine 5 [syscall]:
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.notetsleepg(0xd27b2c, 0xbd537b72, 0x0, 0x0)
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/lock_futex.go:227 +0x24 fp=0x1c2c78c sp=0x1c2c774 pc=0x19cc0
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.timerproc(0xd27b18)
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/time.go:288 +0x438 fp=0x1c2c7e4 sp=0x1c2c78c pc=0x5e5b8
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.goexit()
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/asm_arm.s:867 +0x4 fp=0x1c2c7e4 sp=0x1c2c7e4 pc=0x6ddb8
Nov 29 03:31:20 syncpi syncthing[26164]: created by runtime.(*timersBucket).addtimerLocked
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/time.go:170 +0x134
Nov 29 03:31:20 syncpi syncthing[26164]: goroutine 6 [chan receive]:
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.gopark(0x8287dc, 0x1c162b0, 0x170d, 0x3)
Nov 29 03:31:20 syncpi syncthing[26164]:         /usr/local/go/src/runtime/proc.go:302 +0xd8 fp=0x1c2a73c sp=0x1c2a728 pc=0x3f108
Nov 29 03:31:20 syncpi syncthing[26164]: runtime.goparkunlock(0x1c162b0, 0x170d, 0x3)`

**Comment by ben-utzer** [comment]
Forgot the to give the version I am running:
v0.14.52, Linux (ARM) 
This is the latest build in the repository for Linux Arm I think. 

I can try the RC if anyone thinks that would help to troubleshoot or if anyone says it was fixed there.

**Comment by AudriusButkevicius** [comment]
It's most definately hardware corruption, so new rc won't help.

**Comment by ben-utzer** [comment]
I have another RaspberryPi that has the same thing in the log.
Version is v0.14.52, Linux (ARM) 

`Nov 25 16:42:57 benpi syncthing[6582]: runtime: pointer 0xc1ecc43 to unused region of span span.base()=0xad52000 span.limit=0xad64ec5 span.state=1
Nov 25 16:42:57 benpi syncthing[6582]: fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)
Nov 25 16:42:57 benpi syncthing[6582]: runtime stack:
Nov 25 16:42:57 benpi syncthing[6582]: runtime.throw(0x69199f, 0x3e)
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/panic.go:608 +0x5c fp=0x2863f44 sp=0x2863f30 pc=0x3d0ac
Nov 25 16:42:57 benpi syncthing[6582]: runtime.findObject(0xc1ecc43, 0x0, 0x0, 0x0, 0x0, 0x0)
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/mbitmap.go:399 +0x324 fp=0x2863f68 sp=0x2863f44 pc=0x22854
Nov 25 16:42:57 benpi syncthing[6582]: runtime.wbBufFlush1(0x2823900)
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/mwbbuf.go:252 +0xb0 fp=0x2863fa0 sp=0x2863f68 pc=0x38f98
Nov 25 16:42:57 benpi syncthing[6582]: runtime.gcMarkDone.func1.1(0x2823900)
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/mgc.go:1449 +0x1c fp=0x2863fa8 sp=0x2863fa0 pc=0x69930
Nov 25 16:42:57 benpi syncthing[6582]: runtime.forEachP(0x82873c)
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/proc.go:1443 +0x158 fp=0x2863fe0 sp=0x2863fa8 pc=0x41f40
Nov 25 16:42:57 benpi syncthing[6582]: runtime.gcMarkDone.func1()
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/mgc.go:1448 +0x1c fp=0x2863fe8 sp=0x2863fe0 pc=0x69970
Nov 25 16:42:57 benpi syncthing[6582]: runtime.systemstack(0x2852000)
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/asm_arm.s:354 +0x84 fp=0x2863fec sp=0x2863fe8 pc=0x6c100
Nov 25 16:42:57 benpi syncthing[6582]: runtime.mstart()
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/proc.go:1229 fp=0x2863fec sp=0x2863fec pc=0x4199c
Nov 25 16:42:57 benpi syncthing[6582]: goroutine 33 [running]:
Nov 25 16:42:57 benpi syncthing[6582]: runtime.systemstack_switch()
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/asm_arm.s:298 +0x4 fp=0x2d2e778 sp=0x2d2e774 pc=0x6c070
Nov 25 16:42:57 benpi syncthing[6582]: runtime.gcMarkDone()
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/mgc.go:1442 +0xec fp=0x2d2e798 sp=0x2d2e778 pc=0x297f4
Nov 25 16:42:57 benpi syncthing[6582]: runtime.gcBgMarkWorker(0x2821300)
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/mgc.go:1909 +0x268 fp=0x2d2e7e4 sp=0x2d2e798 pc=0x2ac20
Nov 25 16:42:57 benpi syncthing[6582]: runtime.goexit()
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/asm_arm.s:867 +0x4 fp=0x2d2e7e4 sp=0x2d2e7e4 pc=0x6ddb8
Nov 25 16:42:57 benpi syncthing[6582]: created by runtime.gcBgMarkStartWorkers
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/mgc.go:1720 +0x68
Nov 25 16:42:57 benpi syncthing[6582]: goroutine 1 [chan receive, 2199 minutes]:
Nov 25 16:42:57 benpi syncthing[6582]: runtime.gopark(0x8287dc, 0x496c030, 0x170d, 0x3)
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/proc.go:302 +0xd8 fp=0x2a50f8c sp=0x2a50f78 pc=0x3f108
Nov 25 16:42:57 benpi syncthing[6582]: runtime.goparkunlock(0x496c030, 0x170d, 0x3)
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/proc.go:308 +0x3c fp=0x2a50fa0 sp=0x2a50f8c pc=0x3f1a4
Nov 25 16:42:57 benpi syncthing[6582]: runtime.chanrecv(0x496c000, 0x2a51144, 0x1, 0x19b6)
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/chan.go:520 +0x2c8 fp=0x2a50fe8 sp=0x2a50fa0 pc=0x14f18
Nov 25 16:42:57 benpi syncthing[6582]: runtime.chanrecv1(0x496c000, 0x2a51144)
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/chan.go:402 +0x20 fp=0x2a50ffc sp=0x2a50fe8 pc=0x14c20
Nov 25 16:42:57 benpi syncthing[6582]: main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x666f78, 0x1, 0x0, ...)
Nov 25 16:42:57 benpi syncthing[6582]:         /opt/tcagent/syncthing-work/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:917 +0x1714 fp=0x2a51e44 sp=0x2a50ffc pc=0x53b5f0
Nov 25 16:42:57 benpi syncthing[6582]: main.main()
Nov 25 16:42:57 benpi syncthing[6582]:         /opt/tcagent/syncthing-work/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:446 +0x2e4 fp=0x2a51fc4 sp=0x2a51e44 pc=0x537f4c
Nov 25 16:42:57 benpi syncthing[6582]: runtime.main()
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/proc.go:201 +0x204 fp=0x2a51fe4 sp=0x2a51fc4 pc=0x3ec98
Nov 25 16:42:57 benpi syncthing[6582]: runtime.goexit()
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/asm_arm.s:867 +0x4 fp=0x2a51fe4 sp=0x2a51fe4 pc=0x6ddb8
Nov 25 16:42:57 benpi syncthing[6582]: goroutine 2 [force gc (idle), 80 minutes]:
Nov 25 16:42:57 benpi syncthing[6582]: runtime.gopark(0x8287dc, 0xd24e88, 0x61410, 0x1)
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/proc.go:302 +0xd8 fp=0x282afc0 sp=0x282afac pc=0x3f108
Nov 25 16:42:57 benpi syncthing[6582]: runtime.goparkunlock(0xd24e88, 0x1410, 0x1)
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/proc.go:308 +0x3c fp=0x282afd4 sp=0x282afc0 pc=0x3f1a4
Nov 25 16:42:57 benpi syncthing[6582]: runtime.forcegchelper()
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/proc.go:251 +0xb0 fp=0x282afec sp=0x282afd4 pc=0x3ef88
Nov 25 16:42:57 benpi syncthing[6582]: runtime.goexit()
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/asm_arm.s:867 +0x4 fp=0x282afec sp=0x282afec pc=0x6ddb8
Nov 25 16:42:57 benpi syncthing[6582]: created by runtime.init.3
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/proc.go:240 +0x24
Nov 25 16:42:57 benpi syncthing[6582]: goroutine 3 [GC sweep wait]:
Nov 25 16:42:57 benpi syncthing[6582]: runtime.gopark(0x8287dc, 0xd25048, 0x6140c, 0x1)
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/proc.go:302 +0xd8 fp=0x282b7c0 sp=0x282b7ac pc=0x3f108
Nov 25 16:42:57 benpi syncthing[6582]: runtime.goparkunlock(0xd25048, 0x8c140c, 0x1)
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/proc.go:308 +0x3c fp=0x282b7d4 sp=0x282b7c0 pc=0x3f1a4
Nov 25 16:42:57 benpi syncthing[6582]: runtime.bgsweep(0x2848000)
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/mgcsweep.go:71 +0x114 fp=0x282b7e4 sp=0x282b7d4 pc=0x30308
Nov 25 16:42:57 benpi syncthing[6582]: runtime.goexit()
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/asm_arm.s:867 +0x4 fp=0x282b7e4 sp=0x282b7e4 pc=0x6ddb8
Nov 25 16:42:57 benpi syncthing[6582]: created by runtime.gcenable
Nov 25 16:42:57 benpi syncthing[6582]:         /usr/local/go/src/runtime/mgc.go:216 +0x40
Nov 25 16:42:57 benpi syncthing[6582]: goroutine 17 [finalizer wait, 6 minutes]:`

I have another arm device, but ssh access to it is not so easy.

**Comment by calmh** [comment]
Can you run `memtester` on these devices, just for fun?

**Comment by ben-utzer** [comment]
> Can you run `memtester` on these devices, just for fun?

You mean `sudo memtester 200M 2` or so? I can vary the parameters, just let me know. I did one for both, but only 100M and 300M with 10 cycles. If you mean memtest during boot I would have to check how to do that with a Pi, generally if that is possible I can do it. 

Remember it is two Pi in different places, yes those are not high quality computers, but so far both devices (different types, one 3 with wifi and one without) did not show any problem.

**Comment by ben-utzer** [comment]
> Can you run `memtester` on these devices, just for fun?
I did not have the time yet to try to use the Linux Bootmanager to run a full memory test. I can easily run memtester from cli if that will help. One of the Raspberry Pi Syncthing clients keeps restarting every 8h, then it starts synching the one big file that changed (20GB) but before it finishes Syncthing already has the error again. 
Just some information from my side. 

What I wanted to know, do you want to have a memtester run on cli, I can stop syncthing, then the machine is mostly idle, so I could run memtester with 80% memory? Should I do this or did you in fact mean memtest86 before booting Linux?

**Comment by calmh** [comment]
I meant something to test the memory. Google said memtester. I have no Pi and no experience, please apply yours.

**Comment by AudriusButkevicius** [comment]
Also, memtesting might not be enough. I've seen cases where memory corruption only happens past a certain temperature threshold. Given these devices are "System on chip" it's perfectly plausible that you need temperature induced by hashing to reproduce the corruption.

**Comment by AudriusButkevicius** [comment]
It is also possible that your sd card is corrupt and just has a corrupt binary which causes the GC to panic. Try redownloading the binary.

**Comment by ben-utzer** [comment]
I did run memtester (which you run starting after the OS is booted), it did not find any problems, but as the OS is running some memory is occupied by some processes and can not be tested. 

I did install an update of Syncthing yesterday and maybe this soles the problem too. So I will see what happens the next days. 

Thanks for the help.
