### ISSUE TITLE
Feature request. The logger to log dates and times at normal log levels.

### ISSUE THREAD

**Issue by yb66** [syncthing/syncthing#5309]
When I read my logs there are only times and not dates for each entry. I'm not a user of golang but [these lines in the logger code](https://github.com/syncthing/syncthing/blob/406bedf1e3cd2ec986e721a66579a78cc9d94e27/lib/logger/logger.go#L32) appear to indicate that this is by design.

I can't fathom why this is, perhaps there's a good reason. Regardless, a date next to the time would be helpful. It shouldn't need to hit DEBUG levels to get this kind of info in a log.

Regards,
iain

**Comment by calmh** [comment]
You don't, see `-logflags` (or just `-help`).

**Comment by yb66** [comment]
I do, I just wonder why any logger would only output the time *as default*. It implies that the devs are using a log rotation of one day. That's great, but I'm not sure why your set up is the default - is it too many bytes to write to the file? ;-)

**Comment by calmh** [comment]
Use something like syslog and it'll be timestamped for you, making the correct choice `-logflags 0`. The defaults are fine for running in the console and keeping an eye on what's going on.

If you're just opening issues to argue, feel free to head over to the forum instead.
