### ISSUE TITLE
Use urfave/cli instead of AudriusButkevicius/cli

### ISSUE THREAD

**Issue by Ambrevar** [syncthing/syncthing#5310]
AudriusButkevicius/cli does not pass `go test` on Go 1.11:

https://github.com/AudriusButkevicius/cli/pull/1

The output:

```
> go test -v
# github.com/AudriusButkevicius/cli_test
./app_test.go:211:6: parsedOption declared but not used
./app_test.go:211:20: firstArg declared but not used
vet: typecheck failures
FAIL	github.com/AudriusButkevicius/cli [build failed]
```

It's a very outdated fork of https://github.com/urfave/cli.  Maybe it's the right time for an update?

**Comment by AudriusButkevicius** [comment]
PRs welcome

**Comment by imsodin** [comment]
Fixed by https://github.com/syncthing/syncthing/pull/5487
