### ISSUE TITLE
This doesn't meet your code of conduct

### ISSUE THREAD

**Issue by yb66** [syncthing/syncthing#5312]
I don't expect to be met with [outright disrespect](https://github.com/syncthing/syncthing/issues/5309#issuecomment-436165301) by one of the lead developers for opening a valid issue. ***Defaults matter***. It's not the first time - not by a long way - I've seen the same developer make decisions based on what suits him with flimsy rationale, but to be told I'm opening issues simply to argue is absurd and disrespectful.

- The issue was closed before discussion.
- Further discussion was met with explicit disrespect.

Try reading your own [code of conduct](https://github.com/syncthing/syncthing/blob/master/CONDUCT.md).

As for the work I've been doing to write things to make it easier for Mac users to use Syncthing, I won't be sharing them with this community.

**Comment by calmh** [comment]
Opening issues to complain about defaults, which are by definition a matter of opinion, stating that you already know and use the suggested workaround, and suggesting that we have the current default for silly reasons (to save bytes in a log file) is in my book "opening issues simply to argue". We have enough other issues that I don't have the patience for arguing about defaults any more.

Clearly, I'll let someone else handle the rest of this as it's a CoC complain against myself, so stepping out of the thread.

**Comment by yb66** [comment]
I'm going to guess you didn't read the code of conduct at all then.

I'm only back because I knew you wouldn't be able to help yourself, and at least you gave me a chuckle with your lack of self awareness. Anyone with an ounce of it would've at least apologised.

I'm unsubscribed, get on with your day, you've shown your CoC means nowt.

**Comment by AudriusButkevicius** [comment]
So I was about to write a meaningful reply, but given this has turned into a circus, I am just closing this.
