### ISSUE TITLE
Feature Request: Receive only directories with send/receive files

### ISSUE THREAD

**Issue by Script-Mak3r** [syncthing/syncthing#5315]
Sometimes folders get moved around when they aren't supposed to due to user error, which can cause significant issues, and take a while to sync the fix if the contents of the moved folders are large enough, which is bad if the issues need to be resolved quickly.

This would all work much more smoothly if changes could be blocked from happening if those changes involve creating or deleting a folder, with a master computer to handle the addition of new folders and deletion of defunct folders.

If this is unreasonable to implement, feel free to close this, but such a feature would have made my job significantly easier this morning.

**Comment by calmh** [comment]
I think it would be weird to treat files and directories differently in this way. You'd also have odd corner cases if the directory was then *also* created on the other side, having to merge or conflict contents etc. So from my point of view - no, sorry.

One possible workaround could be to ignore everything except the specific directories you want to allow.

**Comment by Script-Mak3r** [comment]
Unfortunately, every computer needs to be able to edit all of the files. The issues arise when someone is navigating the directories and accidentally drags a folder into another one.
