### ISSUE TITLE
Manually set mtimes in past not propagated

### ISSUE THREAD

**Issue by bensums** [syncthing/syncthing#5316]
I manually set the modification times of some files in a "send only" folder to some times in the past. Then no sync occurred. The folder is shared with a single other host which has the folder as "receive only".

I expected the new mtimes to be synced.

Not tried, but I imagine minimal steps to reproduce would be to set up a synced folder, then from the source machine run
```
touch test-file
```
Wait for sync. Then run
```
touch -d "2010-01-01 01:01:01" test-file # or some other time in the past and before the first touch
```
The new mtime won't propagate to other machines.

This seems related to https://github.com/syncthing/syncthing/issues/61 but that's about changed files having an earlier mtime. This is about just setting the mtime without changing the file contents.

### Version Information

Source:
Syncthing Version: v0.14.50 (Syncthing Android 0.10.14)
OS Version: Android 8.1.0

Destination:
Syncthing Version: v0.14.52, Linux (64 bit) 
OS Version: Synology DSM 6.2.1

**Comment by AudriusButkevicius** [comment]
Did you click the rescan button in the web ui?
Android does not allow modifying mtimes in general, so I am surprised you somehow managed to do it. Anyways, if you want to continue discussing this, please move this to a forum thread as it's potentially a limitation on android rathet than a bug we can fix.

**Comment by bensums** [comment]
Huh? No. The bug was that it didn't happen automatically.

To change the mtime, I just logged in with adb shell and ran a touch command similar to the above, e.g. `touch -d "2010-01-01 01:01:01" test-file`. It updates the mtime fine. Are you saying if I do the same on a non-Android source, I won't see this bug?

So you're closing because it's "potentially" not a bug?

**Comment by AudriusButkevicius** [comment]
It still does not explain whether a scan fixed it.
Anyways, there are many questions around this, so I'd rather those happened on the forum so we could compile an exact definition of the problem, under what conditions it happens, and whether it's an android only quirk or not etc, and then reopen it.
