### ISSUE TITLE
Feature Request; new end point at REST interface for number of file types for statistics purposes.

### ISSUE THREAD

**Issue by EserGozcu** [syncthing/syncthing#5318]
Would it be possible to have an end point for file types statistics?  Example: Number of .jpg files per shared folder etc.

**Comment by AudriusButkevicius** [comment]
Why? Who cares?

**Comment by uok** [comment]
I also don't understand the use case - if it is your computer just list or search the files.
E.g. if you are on linux, use `find . -type f | sed 's/.*\.//' | sort | uniq -c` and you get
````
 16 avi
 29 jpg
136 mp3
  3 mp4
````

**Comment by calmh** [comment]
I think Audrius' "who cares" is not rhetorical, but rather an actual question that should be answered for any feature request. That is, what is the practical use case that this resolves, and for whom? I don't see that info here either, other than a vague "someone might find it interesting" which isn't really good enough imho.
