### ISSUE TITLE
Consider setting "LimitNOFILE" on systemd service

### ISSUE THREAD

**Issue by njam** [syncthing/syncthing#5319]
I started experiencing errors "too many open files" - not sure what change on my system caused it.

How about setting `LimitNOFILE=infinity` in the systemd service configuration?
See [docs](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Process%20Properties).

Syncthing Version: v0.14.52
OS Version: Linux 4.18.16-arch1-1-ARCH

**Comment by calmh** [comment]
I don't think that should be necessary. What are the default limits imposed by your system?

**Comment by njam** [comment]
The systemd unit has a nofile limit of 4096:
```console
$ systemctl --user show syncthing | grep LimitNOFILE
LimitNOFILE=4096
```

I don't have a default [`DefaultLimitNOFILE`](https://www.freedesktop.org/software/systemd/man/systemd.directives.html#DefaultLimitNOFILE=) set, which seems to be upstream default ([ref](https://github.com/systemd/systemd/blob/v239/src/core/system.conf.in#L55)).
When I query `DefaultLimitNOFILE` I get 4096:
```console
$ sudo systemctl show -p DefaultLimitNOFILE
DefaultLimitNOFILE=4096
```

Systemd says about those limits ([source](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Process%20Properties)):
> For system units these resource limits may be chosen freely. For user units however (i.e. units run by a per-user instance of systemd(1)), these limits are bound by (possibly more restrictive) per-user limits enforced by the OS.

And `ulimit` also reports a limit of 4096:
```console
$ ulimit -n     
4096
```

I'm not sure where this value of 4096 is coming from, but it might be coming from Linux itself ([ref](https://github.com/torvalds/linux/blob/v4.18/include/uapi/linux/fs.h#L30)).

I never experienced this error with syncthing before, so there might be something fishy going on. I'm happy for any feedback.

Why do you think it's _not_ necessary to set it on the unit definition? Because the OS-level default should be high enough, or because syncthing increases it by itself?
I remember in the sysvinit days many script increased ulimits before starting the process. But not sure either if this is good practice with systemd units.

**Comment by AudriusButkevicius** [comment]
I don't thing user processes can increase the hard limits, just soft limits which I think (not sure), I think we already raise. I suspect systemd just picks whats in /etc/limits and this is what you should modify.

**Comment by calmh** [comment]
4096 or thereabouts is what everyone else also defaults to and it should be plenty for our purposes. If we’re running out of fd:s at the 4096 limit it’s a bug and we should fix that.

**Comment by njam** [comment]
> I don't thing user processes can increase the hard limits

You're right. Increasing `LimitNOFILE` in a _user_ service above system limit is not possible..

> If we’re running out of fd:s at the 4096 limit it’s a bug and we should fix that.

Makes sense. Probably I experienced an "unlucky" startup of syncthing. It's the first and only time I experienced this. If it happens again I will report it again.

---

For anyone who wants to increase their NOFILE limit, a way to do it is in `/etc/systemd/system.conf` to set:
```
DefaultLimitNOFILE=99999
```

**Comment by njam** [comment]
Just for the record: one of my machines errored with "too many files" when trying to accept a TCP connection twice. I've never seen this before, so maybe a change in Syncthing leads to more files being opened at the same time.
![screenshot from 2018-11-19 17-11-45](https://user-images.githubusercontent.com/360800/48719752-81767c00-ec1e-11e8-86b9-7c4149b01150.png)

**Comment by AudriusButkevicius** [comment]
You can check `ls -lah /prod/(pid)/fd` to see what handles it has open, and see if you find a pattern.
