### ISSUE TITLE
gui: Display rate limit

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#5320]
Currently a rate limit (global or per device) is nowhere displayed in the GUI. To find out which device is rate limited you need to edit one device after the other to check the settings. 
Here are some ideas how to display it:

Text note
![limit-text](https://user-images.githubusercontent.com/9367272/48348332-5d94c280-e681-11e8-879a-3873e9b4df2b.png)
Icon
![limit-icon](https://user-images.githubusercontent.com/9367272/48348342-61284980-e681-11e8-8941-b3e40db82979.png)
Text line
![limit-line](https://user-images.githubusercontent.com/9367272/48348346-64233a00-e681-11e8-8179-fb563e35adce.png)
Text info
![limit-muted](https://user-images.githubusercontent.com/9367272/48401520-b0c25000-e729-11e8-9b1c-0e6a49995ca1.png)

If no rate limit is set the icon/texts are hidden. 
My preference is icon version

**Comment by calmh** [comment]
Haven’t looked yet, just to note that there is a precedent in the comment on ignore patterns reducing the local state. We might want to make the two things look roughly the same.

**Comment by AudriusButkevicius** [comment]
Agree, we should just have the grey text beneath displaying the limits, both global (on "self" device) and per device.

**Comment by uok** [comment]
Text info
![limit-muted](https://user-images.githubusercontent.com/9367272/48401296-15c97600-e729-11e8-8513-a9f759d75d3c.png)

**Comment by uok** [comment]
ok, I added grey text version

**Comment by AudriusButkevicius** [comment]
The Capalised Sentences look weird, but otherwise looks ok.

**Comment by uok** [comment]
I copied the text from settings. If the writing is changed I guess it needs to be translated again? 
We could just go with a general "Rate limit: 123 KiB/s" in both cases, as it should be clear what it means.

**Comment by AudriusButkevicius** [comment]
I guess if we are reusing an existing string is has to stay this way. Anyways, I'll let someone else chip in.

**Comment by calmh** [comment]
Existing translations are good enough imho

**Comment by calmh** [comment]
Woops

**Comment by clintmoyer** [comment]
I submitted a change that details the rate limit in a tooltip.

https://github.com/syncthing/syncthing/pull/5327

**Comment by uok** [comment]
@clintmoyer thanks for contributing
Please implement as it was agreed in this issue (grey text and wording). Tooltip is not needed.
Thanks!

**Comment by uok** [comment]
I will work on PR

**Comment by uok** [comment]
Please check PR #5328

**Comment by clintmoyer** [comment]
My original change includes a tooltip for every device, as well as the global configuration. It seems like the original suggestion here introduces a new "sub-row" of text to each configuration. Is that what we want? No other widget in the GUI has that offset right now.

**Comment by AudriusButkevicius** [comment]
Ignore patterns dk that.

**Comment by AudriusButkevicius** [comment]
Agree
