### ISSUE TITLE
Incorrect warning when --home and path on same directory level

### ISSUE THREAD

**Issue by wwwutz** [syncthing/syncthing#5324]
ST incorrectly opens a warning window, when config and shared folder have the same string prefix.

How to reproduce

1. `syncthing --home=/tmp/ABCCONFIG`
2. add folder `/tmp/ABC`
3. enjoy warning

### Version Information

Syncthing Version: v0.14.52, Linux (64 bit)
OS Version: LFS Linux

Source hint: 
`lib/model/model.go:273 warnAboutOverwritingProtectedFiles()`

**Comment by calmh** [comment]
Path prefixes are Hard&trade; :)

**Comment by wwwutz** [comment]
confirm:: fixed
