### ISSUE TITLE
Windows client console or taskbar icon showing quickly even with syncthing.exe -no-console -no-browser

### ISSUE THREAD

**Issue by josephernest** [syncthing/syncthing#5331]
On Windows 7, I tried to create a shortcut for:

    syncthing.exe -no-console -no-browser

When launching it, it still displays a console window during 1 sec and then closes quickly, this is a bit glitchy on every computer startup...

Using `Run > Minimized` as suggested in https://github.com/syncthing/syncthing/issues/1635 half solves it. 

But still, the taskbar icon is quickly displayed, and then disappears 0,5 seconds after.

**Question: Is there a way to have a 100% invisible Syncthing startup on Windows?** Sorry, but I'm a bit extreme about UI details ;)

PS: syncthing.exe should maybe use a tray icon instead (something like this is in the API: `BOOL Shell_NotifyIcon( DWORD dwMessage,PNOTIFYICONDATA lpdata);`)

**Comment by AudriusButkevicius** [comment]
This is expected

**Comment by Catfriend1** [comment]
https://github.com/syncthing/syncthing/pull/4999

**Comment by josephernest** [comment]
@AudriusButkevicius 
What do you mean by 

> This is expected

To be more precise: this behaviour causes a taskbar icon "flickering" on each Windows startup, and it is clearly not something we want.

I think [this could fix it](https://stackoverflow.com/a/5340098/1422096):

> If you set the WS_EX_TOOLWINDOW extended style for your window, it won't be shown in the task bar or Alt+Tab list.

**Comment by AudriusButkevicius** [comment]
There is no window, syncthing does not create one, the OS creates a console for a windowless process before it's started, which means we can only hide after we started up, hence the flicker.

We could compile syncthing as a windowed application so console does not get created, but then I could not find a way to create a console on the fly that gets wired to stdout and what not (as some people might actually care about the logs).

To be honest, most people on Windows use synctrayzor anyway. If you feel strongly about such detail as a millisecond flicker, I suggest you implement a solution and open a PR fixing it, as I don't see anyone investing hours of time fixing a flicker.

This might get addresses when tray icon support is added, if that actually happens.
