### ISSUE TITLE
Duplicate Files Names in Out of Sync List

### ISSUE THREAD

**Issue by CoupeWare** [syncthing/syncthing#5332]
One of my shared folders shows one item out of sync on the Syncthing web interface. When I click through to see the list of out of sync items it shows 7 files with the same name. They are all syncing and showing the exact same level of progress and they increment at the same time. On a second identical backup system there are 3 of the same file name shown.

There is only one copy of this file on the source computer with this name that should be syncing. The path shown for all 7 or all 3 are identical.

Everything appears to be working as expected, this appears to be a display issue that I caught because the file is large and takes a long time to sync.

In case it provides a hint the backup system with 7 names in the list is on the LAN while the one with 3 names is remote and syncing at about half the rate.

All systems are running 0.14.52 on Linux. The source running Fedora 29, the two backup computers are running Ubuntu 18.04.1 LTS on Odroid-HC2 computers.

![syncthingduplicateitems](https://user-images.githubusercontent.com/9490727/48666816-2447c280-ea86-11e8-9aaf-96dfb999021d.png)

![syncthingduplicateitems2](https://user-images.githubusercontent.com/9490727/48666818-29a50d00-ea86-11e8-8095-fb8a80330221.png)

**Comment by CoupeWare** [comment]
I turned on events in the logs and it appears that a group of 22 errors are written when the progress is updated. Half are "DownloadProgress map" and half are "RemoteDownloadProgress map".

**Comment by calmh** [comment]
Can we see those errors?

**Comment by CoupeWare** [comment]
Attached
[DuplicateOutOfSync.log](https://github.com/syncthing/syncthing/files/2592998/DuplicateOutOfSync.log)

**Comment by CoupeWare** [comment]
While I don't think this is a high priority bug it does appear to be blocking other small files from syncing with so many of the same file shown as syncing ahead of them.

**Comment by AudriusButkevicius** [comment]
Not really, syncthing syncs a file at a time, so this is purely cosmetic.

**Comment by noodle-** [comment]
I've got the same issue on multiple machines, Windows, Linux and Android, since about a week or something like that, but I haven't researched how/when/what happens exactly so I can't add any useful info to this issue yet.

If you have any specific questions let me know and I'll try to help!

**Comment by CoupeWare** [comment]
I frequently see more than one (different) file sync at the same time. If there is one big file many other files appear to sync while the big file is taking much more time than each of the small files. There appear to be 3 or 4 or more slots available and many files seem to fill the available slots while the one big file is blocking one of the slots. I haven't looked into it in any detail but the number of slots appears to vary. Sorry if I'm using the wrong terminology.

In this case the small files are sitting there waiting for days since the big file is 49 GB and it's going to a slow backup computer (Odroid). Using my terminology, the big file appears to be taking up all of the slots even though it should only be taking up one.

**Comment by AudriusButkevicius** [comment]
What you are talking about is completely unrelated to the UI bug that is seen here.

**Comment by noodle-** [comment]
![image](https://user-images.githubusercontent.com/812565/52282243-40118500-2960-11e9-9cb2-f86f2e37139d.png)
Additional screenshot to show some more variations of this bug.

**Comment by SerVB** [comment]
I also experience this on Syncthing 1.1.0 and Windows 10 x64:

![image](https://user-images.githubusercontent.com/20105593/53904207-930d5380-4056-11e9-844b-24ead75b4915.png)

Don't know how to reproduce...

**Comment by SerVB** [comment]
@calmh, is it really fixed? Can't check now, but there is an uncertainty in #5626 description.

**Comment by imsodin** [comment]
@SerVB Just reopen if you encounter it with v1.1.2.
