### ISSUE TITLE
Devices should remember shared folders

### ISSUE THREAD

**Issue by RandomReaper** [syncthing/syncthing#5333]
Once you have refused an incoming shared folder request, the only way to accept it later is to manually add the folder.

I therefore propose to store a list of received shared folder in the client, so it's possible to add the folder later. It could be displayed in the "Share Folders With Device/Select the folders to share with this device." list.

**Comment by AudriusButkevicius** [comment]
The ignored list of folders is already visible in settings. You can remove the ignored folder and the prompt will reappear on reconnect.

**Comment by RandomReaper** [comment]
Thank you for your fast response and for the tip, I was not aware this list was in the settings.
