### ISSUE TITLE
New chmduquesne/rollinghash breaks tests

### ISSUE THREAD

**Issue by aviau** [syncthing/syncthing#5334]
Hello!

Apparently we have a newer version of rollinghash in Debian (4.0.0) and it broke syncthing tests:
```
ok  	github.com/syncthing/syncthing/lib/relay/protocol	0.281s [no tests to run]
=== RUN   TestBlocks
--- PASS: TestBlocks (0.00s)
=== RUN   TestAdler32Variants
--- FAIL: TestAdler32Variants (0.01s)
	blocks_test.go:160: At i=128, sum2=5ea93e99, sum3=5ea93e99
	blocks_test.go:160: At i=256, sum2=2cf17ba3, sum3=80683d0b
	blocks_test.go:162: Mismatch after roll; i=256, sum2=2cf17ba3, sum3=80683d0b
```

This may be a misdiagnosis, I have only spent little time on this for now.

Let me know if you think the problem is related or not.

Cheers,

**Comment by calmh** [comment]
I looked at it and this looks very much like a test that should pass, and *must* pass for our rolling hash support to work. Spontaneously it looks like a regression in the rollinghash/adler32 package. If you can narrow down the breaking commit I can look closer at it.

**Comment by calmh** [comment]
Oh, strike that. They changed the API:

```
Write has become fully consistent with hash.Hash. As opposed to previous versions, where writing data would reinitialize the window, it now appends this data to the existing window. In order to reset the window, one should instead use the Reset method.
```

We need to adapt when upgrading.

**Comment by calmh** [comment]
Oh, and we're in luck, because we already do that, just not in the test. So we can just update the test.

**Comment by aviau** [comment]
:tada:
