### ISSUE TITLE
Version restore not possible with custom versioning path set

### ISSUE THREAD

**Issue by pedrojvaz** [syncthing/syncthing#5338]
Syncthing cannot find previous versions when using _Staggered File Versioning_ using the option to define a folder path for the versioning. 
While syncthing correctly saves versions in the defined folder, when clicking "Versions", it display "No Data.", making it impossible to restore previous versions.

### Version Information

Syncthing Version: v0.14.52, Linux (ARM)
OS Version: Raspbian GNU/Linux, 9 (stretch)
Browser Version: Firefox Dev Ed, 64.0b12 (64-bit)

**Comment by canton7** [comment]
See discussion [on the forum](https://forum.syncthing.net/t/file-version-no-data/12488).
