### ISSUE TITLE
Incorrectly out of sync, sequence number oddness.

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#5340]
It seems there might be an occasional issue with the index sending. I noticed this in my home setup. Two devices, "kvin" and "pseudo"; kvin thinks pseudo is out of sync missing one file, pseudo thinks it has everything, but the file is missing.

kvin side:

<img width="1164" alt="screen shot 2018-11-29 at 09 15 05" src="https://user-images.githubusercontent.com/125426/49208702-c20d8c80-f3b8-11e8-87ed-22de4bab7431.png">

<img width="1174" alt="screen shot 2018-11-29 at 09 15 13" src="https://user-images.githubusercontent.com/125426/49208713-c9349a80-f3b8-11e8-8601-b03af85b3f9f.png">

(note 2702 files locally, pseudo missing one pdf)

pseudo side:

<img width="1175" alt="screen shot 2018-11-29 at 09 15 20" src="https://user-images.githubusercontent.com/125426/49208739-dbaed400-f3b8-11e8-8894-f1bb9e264a3c.png">

(2701 files locally)

Checking the file via rest shows it present on kvin but not pseudo, which matches the above:

```
jb@kvin:~ $ curl ... 'http://localhost:8384/rest/db/file?folder=documents&file=Kastelo/Ekonomi/2018+Bokföring/INV04871726_A00552008_11252018.pdf'
{
  "availability": null,
  "global": {
    "deleted": false,
    "ignored": false,
    "invalid": false,
    "localFlags": 0,
    "modified": "2018-11-26T07:03:54+01:00",
    "modifiedBy": "SYNO4VL",
    "mustRescan": false,
    "name": "Kastelo/Ekonomi/2018 Bokföring/INV04871726_A00552008_11252018.pdf",
    "noPermissions": false,
    "numBlocks": 1,
    "permissions": "0644",
    "sequence": 902,
    "size": 71947,
    "type": 0,
    "version": [
      "SYNO4VL:1"
    ]
  },
  "local": {
    "deleted": false,
    "ignored": false,
    "invalid": false,
    "localFlags": 0,
    "modified": "2018-11-26T07:03:54+01:00",
    "modifiedBy": "SYNO4VL",
    "mustRescan": false,
    "name": "Kastelo/Ekonomi/2018 Bokföring/INV04871726_A00552008_11252018.pdf",
    "noPermissions": false,
    "numBlocks": 1,
    "permissions": "0644",
    "sequence": 902,
    "size": 71947,
    "type": 0,
    "version": [
      "SYNO4VL:1"
    ]
  }
}

$ curl ... 'https://pseudo.int.nym.se:8384/rest/db/file?folder=documents&file=Kastelo/Ekonomi/2018+Bokföring/INV04871726_A00552008_11252018.pdf'
No such object in the index
```

The sequence number 902 is suspiciously low for this folder though; it's been around for a long time. Spot checking a couple of other files doesn't reveal anything conclusive though. One from Nov 14 (two weeks ago) has sequence 850 while another from Now 27 (one day after the affected one above) has sequence 49569. The latter seems more reasonable, and I'm not sure what would cause the large amount of updates between the 26th and 27th otherwise. (I mean, there are 2700 files in the folder, and they only change very occasionally.) This file is very recent, and a sequence < 2700 should be impossible.

Restarting kvin with `-reset-deltas` resolved.

**Comment by mietzen** [comment]
I wanted to open up an Issue and found this ticket, I think I might have the same Problem.
Home Server (send only) says Backup (receive only) is out of sync Backup says everythin is fine:

![untitled](https://user-images.githubusercontent.com/31704359/50449136-8a492480-0925-11e9-9a00-356daea5b591.png)

![untitled2](https://user-images.githubusercontent.com/31704359/50449135-8a492480-0925-11e9-874c-ffc5059956ba.png)

Home-Server and Backup Server are both running on a Synology NAS. The files claimed to be out of sync are present on both NAS systems and haven't be changed.

@calmh  If you have a fix for this I'm happy to test it on my system.

**Comment by vortigont** [comment]
Got the same issue. One of the peers report that some of the "remote devices" is not in full sync while there is nothing to sync actually, all files are in place with checksums match and all folders are reported in full-sync too.
