### ISSUE TITLE
Changing Device Name in Settings Doesn't Change Device Name (Android)

### ISSUE THREAD

**Issue by mondele** [syncthing/syncthing#5341]
When changing the Device Name in Syncthing for Android (using the Web GUI, as I know no other way) it has traditionally been possible to use the **General** tab in the **Settings** dialog.

Now, however, (not sure which version broke this) the name instantly reverts.

Instead, one now needs to open the **Advanced Configuration**, scroll to the bottom and find the **Device** entry for this device (not trivial if multiple devices have been connected/configured) and change it there. This results in the name changing and staying changed, which is the desired outcome.
 
![screenshot_20181129-102256](https://user-images.githubusercontent.com/25468552/49300088-59451380-f48f-11e8-9e72-9b5dd44f73b7.png)

![screenshot_20181129-102532](https://user-images.githubusercontent.com/25468552/49300102-5f3af480-f48f-11e8-8809-f25aec2cb603.png)

### Version Information

Syncthing Version: v0.14.51-dirty (from F-Droid)
OS Version: Android 6.0
Browser Version: n/a (Using Web GUI within Android app)
Device: Lenovo Pad A10-70F

**Comment by mondele** [comment]
Apparently this also happens with Syncthing Version 0.10.15, from Google Play.

**Comment by wweich** [comment]
It seems, the app enforces the name entered in its settings. So this is a syncthing-android issue, not a syncthing issue.

**Comment by calmh** [comment]
I think this is #5249 which is a legit Syncthing bug, albeit a fixed one.

**Comment by Catfriend1** [comment]
@calmh is right on this

**Comment by mondele** [comment]
Sounds like it will be fixed when Android updates to 52.
