### ISSUE TITLE
Syncthing does not respect nice/ionice value it is started with

### ISSUE THREAD

**Issue by desbma** [syncthing/syncthing#5344]
On Linux, currently Syncthing does not respect the nice value (priority) it is started with, and instead changes the nice value to 11 if it is anything lower than that.

I believe the code responsible for this is in this file: https://github.com/syncthing/syncthing/blob/406b394704c658751d6863bb5d240cc6838c24e2/lib/osutil/lowprio_linux.go

However only the user is able to choose the priority he/she wished to run Syncthing with. For example on my desktop system, I am OK with the default nice value of 11, but on a standalone (ie: NAS) system I definitely want a higher priority, and the current behavior will discard my choice and lower the priority.

The only way I have found to set a higher priority, is to forbid syncthing to do any syscall related to scheduling, using [systemd syscall filtering](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#System%20Call%20Filtering). 

`/etc/systemd/system/syncthing@syncthing.service.d/priority.conf`:
```
[Service]
Nice=-5
IOSchedulingPriority=0
SystemCallFilter=~@resources:EPERM
```
In addition to changing the CPU and IO scheduling priorities for my preference, this will make Syncthing effectively get a EPERM error [here](https://github.com/syncthing/syncthing/blob/406b394704c658751d6863bb5d240cc6838c24e2/lib/osutil/lowprio_linux.go#L70), and force it to give up.

However I believe a better way to handle things, would be to let systemd, or whatever init system the user is running set the priority, and don't change it in the go code.

Thank you

**Comment by calmh** [comment]
You want to set the config option [setLowPriority](https://docs.syncthing.net/users/config.html#set-low-priority) to false, in the advanced config editor -> options, or in the config file.

**Comment by desbma** [comment]
Ah sorry, I missed that option.
