### ISSUE TITLE
Version Number Link to Syncthing Release Page

### ISSUE THREAD

**Issue by CoupeWare** [syncthing/syncthing#5345]
It would be nice if clicking on the Syncthing Version number on the web page would take you to the Syncthing Release Page.

Even better if it took you to the release page for the version that you are running. For example, my systems just updated to v0.14.53 so linking to this page woud be helpful since I like to review the changes after every update.

https://github.com/syncthing/syncthing/releases/tag/v0.14.53

**Comment by calmh** [comment]
There are some corner cases (releases not made by us and with a version number not matching any release, for example Debians 0.14.53-dfsg1 or whatever). But in principle this sounds reasonable.

**Comment by calmh** [comment]
Given the proliferation of different packagings I don't think we should do this.

**Comment by AudriusButkevicius** [comment]
I still think having a changelog in the application would be nice.
