### ISSUE TITLE
Systemd synthing unit starts too early

### ISSUE THREAD

**Issue by Rocco83** [syncthing/syncthing#5346]
Currently, systemd unit must start after network.target. https://github.com/syncthing/syncthing/blob/7203ccb73d110eb91ff9000726591d731cfa44ad/etc/linux-systemd/system/syncthing%40.service#L4 

This is sometimes too early, e.g. in case of sssd (ldap, ...) users.

IMO, unit must be started after multi-user.target.

### Version Information

Syncthing Version: v0.14.53
OS Version: Debian 9
Browser Version: N/A

**Comment by calmh** [comment]
Sounds reasonable.

**Comment by calmh** [comment]
The fix was incorrect and causes a circular dependency (multi-user.target wants syncthing, syncthing must start after multi-user.target). If the problem remains, it must be fixed in a different manner.

**Comment by calmh** [comment]
Reopened by #5676 / e2470c8bc89ae7ce96aa71401f3127795893474f

**Comment by Rocco83** [comment]
Why after multi-user?
What's the purpose?
Or at least a valid use case :-)

**Comment by calmh** [comment]
I'm completely confused by your followup questions , as it seems you are questioning your own premise. Thinking more about it however I think it's fine as is. We are started as part of multiuser. If there are odd things that need to start  before Syncthing they can declare a wanted-by or you can edit to Syncthing unit to add a dependency.

**Comment by Rocco83** [comment]
ooops, sorry, too late in the evening and too fast typing.

I have checked https://www.freedesktop.org/software/systemd/man/systemd.special.html
Another possible way is to depend on:
nss-lookup.target <- lookup for host/service
nss-user-lookup.target <- lookup for user
network.tarkget <- lookup for network
remote-fs.target <- lookup for remote filesystem (nfs, to say)
local-fs.target <- lookup for local filesystem (/home, to say -- some corner case are existing like btrfs not starting "by time" for very large filesystems)

Again, it is a possibility...

**Comment by mir06** [comment]
Thanks @Rocco83 for this hint. I also use sssd with an LDAP backend. Just added `After=network.target nss-user-lookup.target` to `/etc/systemd/system/syncthing@.service` and syncthing is now starting fine for all users.

**Comment by grandchild** [comment]
I think the correct dependency is `After=network-online.target`. This fixes the startup for me on Ubuntu18. The `network-online` target is described here.
Pull request is here: #6328

**Comment by grandchild** [comment]
Disregard my previous comment, what @mir06 says sounds like it should do the trick. I think this could be included in the official `@`-user-service file.
