### ISSUE TITLE
POST to /ignores and /config getting no response

### ISSUE THREAD

**Issue by SkyLined** [syncthing/syncthing#5352]
When using the WebUI to update folder settings, I see POST requests being sent to the server at "/ignores" and "/config" to update the settings. However, it takes up to 17 MINUTES for the server to process these requests, and reports HTTP 500 errors (body = "context canceled"). Other requests are handled almost instantly (<1s) before and after.

### Background
I am running Syncthing on a raspberry-pi to back up data from other machines. Even though this is the only thing the pi does, it appears to be under-powered for this task. It appears that Syncthing spends a lot of CPU, RAM and I/O on scanning folders, making the WebUI very slow to load. It often displays incorrect or outdated information, such as reporting Remote Devices as "Disconnected" while they are online and on the same local network. Those devices report my pi as "Disconnected" too. The weird thing is that syncing appears to happen regardless. Unfortunately, I cannot seem to pinpoint/debug the exact issue, so it's hard to file a bug for that. It might make sense to run a WebUI server process at a higher priority than the scanning process, so the scanning would affect the WebUI responsiveness less.

I was hoping that by setting the folder to "Receive Only", removing the "Watch for Changes" flag and setting "Full Rescan Interval" to 1 day, I could get it to stop using so much CPU while still using it as a way to back-up my data. However, I am having trouble changing the settings on all my folders because of the above issue. Also, Syncthing appears to re-scan the folders every time it is started, regardless of whether the folder was scanned recently (i.e. withing 1 day in my case). I'll file a separate bug for that shortly.

### Version Information

Syncthing Version: v0.14.54, Linux (ARM)
OS Version: Linux 4.14.69+ on Raspberry PI
Browser Version: Tested with Firefox and Chrome; issues appears to be server-side.

**Comment by calmh** [comment]
The config post (and I assume ignores, though I didn't check) is completed when the config changes have been applied. For folder changes that means telling the folder to stop what it's doing and restart with new options. I don't know why this takes ages on your setup. Clearly it's underpowered somehow, but I think you need to narrow down what specifically is the bottle neck. Using the various trace options and potentially profiling to figure out what it's doing durin those 17 minutes would be a good start.

**Comment by SkyLined** [comment]
Can you explain what "the various trace options and potentially profiling" are? I would love to help you find out what the issue is but I am not a Syncthing developer or expert.

**Comment by calmh** [comment]
There are trace things that can be set: https://docs.syncthing.net/dev/debugging.html

Easiest way nowadays is to open the log in the web UI and you'll get checkboxes. You probably want to start with `model` (central to everything, quite verbose), `config`, maybe `scanner` if the thing seems to be that folders don't stop scanning when asked to.

**Comment by SkyLined** [comment]
So, I should set `STTRACE=model config scanner` and restart? Then what should I be looking for in the log file that would hint at the cause of this issue?

**Comment by calmh** [comment]
Or, more conveniently, use the in-GUI log viewer like I mentioned. I'm not sure what to look for, I guess gain an understanding for what's going on and see if there's something unexpected. I can't hand-hold that, sorry.

**Comment by SkyLined** [comment]
>  I'm not sure what to look for, I guess gain an understanding for what's going on and see if there's something unexpected.

That's unfortunate as from a cursory glance it appears you need to have a good understanding of how Synthing works in order to interpret the logs and determine if anything is out of place. I do not have time to learn how Syncthing works in depth.

**Comment by SkyLined** [comment]
... and ironically, the WebUI log viewer makes a GET request which also does never gets a response in my case :(

**Comment by SkyLined** [comment]
I appears that the browser is sending 4 HTTP requests (`/error`, `/status`, `/discovery`, `/connections`) every 8 seconds or so. The server only responds to `/status` immediately with a HTTP 200, the rest appear to be blocked by previous requests; every now and then a a bunch of responses is sent as if one was causing the others to block. But then it hits another that blocks.

**Comment by AudriusButkevicius** [comment]
I'm closing this as this is a support request and should be on the forum. Op is running syncthing on a weak device and sadly your fleet is as slow as your slowest ship, so yes, if something is slow,  everything will be slow due to lock contention. If you want to dig deeper and understand whats causing this, I suggest you move to the forum where this can be debugged and understood before being deemed an issue.
