### ISSUE TITLE
"Uncomplicated FireWall" (UFW) Integration broken

### ISSUE THREAD

**Issue by CottonEaster** [syncthing/syncthing#5355]
### Version Information

Syncthing Version: v0.14.54
OS Version: Mint 19 x64
Browser Version: (if applicable, for GUI issues)

Contrary to [this document](https://docs.syncthing.net/users/firewall.html?highlight=firewall),

sudo ufw allow syncthing

yields

ERROR: Could not find a profile matching 'syncthing'

I had syncthing installed via the GTK version and as a binary in .local/bin. The aforementioned doc seemed to say I needed the apt package for the firewall command to work. So I installed the apt package. Same error.

**Comment by calmh** [comment]
This works on my Ubuntu, so I suspect this is somehow local to your installation, or Mint specific. 

```
root@acro:~# apt install syncthing
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  syncthing
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 8,104 kB of archives.
After this operation, 18.4 MB of additional disk space will be used.
Get:1 https://apt.syncthing.net syncthing/stable amd64 syncthing amd64 0.14.54 [8,104 kB]
Fetched 8,104 kB in 0s (9,757 kB/s)
Selecting previously unselected package syncthing.
(Reading database ... 119358 files and directories currently installed.)
Preparing to unpack .../syncthing_0.14.54_amd64.deb ...
Unpacking syncthing (0.14.54) ...
Processing triggers for ufw (0.35-0ubuntu2) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1.1) ...
Setting up syncthing (0.14.54) ...
Processing triggers for ufw (0.35-0ubuntu2) ...
root@acro:~# ufw allow syncthing
Rules updated
Rules updated (v6)
root@acro:~#
```

As such as I'm going to close as unreproducible. If you figure out the specific problem, and it's something we can fix on our end, please holler.
