### ISSUE TITLE
illegal instruction (sigill) on raspberry Pi 3

### ISSUE THREAD

**Issue by hase-berlin** [syncthing/syncthing#5356]
### Version Information

Syncthing Version: [LUHQH] 01:24:39 INFO: syncthing v0.14.52 "Dysprosium Dragonfly" (go1.11.1 linux-arm) deb@build.syncthing.net 2018-10-11 10:09:44 UTC [noupgrade]
OS Version: Raspbian stretch
Browser Version: n/a? But I was connected with a firefox on MacOS.

Syncthing asked me to report the issue here, so I did.
I was trying to recover from an earlier power loss and resulting DB corruption when this occured.
Which was hard to detect, btw: no hint in the gui and syncthing somewhat working....
Also running syncthing as syytemd service made thing a bit harder: systemd constantly restarts syncthing while it is still hashing: the service start runs into a timeout; but this can be worked around (stop systemd service, start syncthing in a terminal => no timeout issue).
And then the illegal instruction hit...

**Comment by AudriusButkevicius** [comment]
Search existing closed issues. If you still have problems, use the forum.
