### ISSUE TITLE
Provide way to shut down Synthing from command-line.

### ISSUE THREAD

**Issue by SkyLined** [syncthing/syncthing#5368]
I was unable to find a way to cleanly shut down Syncthing from the command-line; please create a way to do so.

Background: I am running Syncthing from a scheduled task on multiple machines. Syncthing binaries are stored in a folder on each machine and this folder is periodically updated from a central source. This allows me to update Syncthing on all machines by updating the binary in the central source.

When Syncthing is running, it keeps a lock on the binary which prevents me from overwriting it. This means I have to shut down Syncthing on each machine before I can update the folder on these machines. At this time, the only option I have is to forcefully terminate Syncthing. Obviously I would like to cleanly shut down Syncthing to prevent data corruption but there does not appear to be a way to do this.

**Comment by imsodin** [comment]
There's plenty of options:

 - sigterm: Nothing unclean about stopping that way.
 - rest api: https://docs.syncthing.net/rest/system-shutdown-post.html
 - Use a dedicated service manager.

**Comment by calmh** [comment]
For what it's worth, it's not Syncthing holding a lock on the binary, that's just how running programs work. To replace it, you can rename over it instead of attempting to open the file itself for writing.

**Comment by SkyLined** [comment]
None of the provided options provide sufficient details to resolve this issue. It appears I forgot to mention I am running Syncthing on Windows; some, if not all, of your answers appear to be Linux specific. Can you please elaborate and expand your answer to address this on Windows?

1) `sigterm` does not exist on Windows and there is no equivalent. `WM_QUIT` would be helpful but since Syncthing does not have a window when it is running as a service, I don't think it can be used here. And even if it can, there is no easy to use command-line tool to send a WM_QUIT message to Syncthing AFAIK. Using `taskkill.exe` does not work; it will report that the process can only be terminated forcefully, which I am trying to prevent.
2) AFAIK Windows does not come with a command-line tool to access REST APIs. Please let me know how I would go about making a REST API request from the command-line on a default Windows install.
3) I have no idea what you mean by "a dedicated service manager", but I suspect that is a Linux specific thing; please explain in more details where I might find that in Windows.

**Comment by imsodin** [comment]
Yeah, sorry - I am indeed a tiny bit linux-centric. However this still falls under

> ### DO NOT POST SUPPORT REQUESTS OR GENERAL QUESTIONS IN THIS ISSUE TRACKER
> 
> Please use the forum at https://forum.syncthing.net/ where a large number of
> helpful people hang out. This issue tracker is for reporting bugs or feature
> requests directly to the developers. Worst case you might get a short
> "that's a bug, please report it on GitHub" response on the forum, in which
> case we thank you for your patience and following our advice. :)

- so please open a thread there.

**Comment by Ferroin** [comment]
> AFAIK Windows does not come with a command-line tool to access REST APIs. Please let me know how I would go about making a REST API request from the command-line on a default Windows install.

In PowerShell, `Invoke-RestMethod` and/or `Invoke-WebRequest`.  Not sure if it would work here or not.  Also, cURL does have Windows versions.

**Comment by SkyLined** [comment]
This was filed as a feature request, not a support request: it is currently missing and I expect people other than me will want this as well.

Invoking a REST API through Powershell might work but is a convoluted work-around for a missing feature IMHO: is not obvious or user friendly. Creating a command-line switch that can be used to shut down Syncthing seems like a very natural thing to have, hence the feature request.

**Comment by calmh** [comment]
What's the typical way to shut down other applications from the command line, in Windows?

**Comment by SkyLined** [comment]
...and using `Invoke-RestMethod` requires using the `-SkipCertificateCheck` flag because the certificate is self-signed; without it the certificate will be considered invalid and no request will be made. Unfortunately, that flag is only available in PowerShell 6+ and Windows 10 stable currently has 5.1.

**Comment by SkyLined** [comment]
It does not need to; this is a request for a useful feature that does not exist.

...but to answer your question: most applications are run on-demand by the user on one machine and accessed through the GUI and that machine. Syncthing can be run in the background and accessed trough the web-interface from other machines. This is a different use-case and thus requires a different way of shutting it down.

Ideally Syncthing should implemented the Windows Service API (https://docs.microsoft.com/en-us/dotnet/framework/windows-services/introduction-to-windows-service-applications), so it can be added as a service rather than run as a scheduled task. That would allow me to shut it down using that API (and existing command-line tools to do so). I could file a feature request for that if you think that makes more sense. I wrote a program that ran as a service myself some ten years or so ago and IIRC it does not require a lot of code to implement the API.

**Comment by calmh** [comment]
There is a nice Go API even for running things as a service. I think it would make a significant deal of sense to support that use case. Much more so than adding things which are odd even on Windows, to support the fact that we're already odd on Windows.

**Comment by canton7** [comment]
(There are instructions on running Synching with NSSM in the docs btw)
