### ISSUE TITLE
hinterlandy.github.io

### ISSUE THREAD

**Issue by diolwe** [syncthing/syncthing#5371]
Syncthing Webgui contacts hinterlandy.github.io. I have signed out of reports!
Using up to date PPA Version on Kubuntu 18.04 

![syncthing](https://user-images.githubusercontent.com/907156/49865471-4cb4a980-fe05-11e8-966a-c1e266e92988.png)

**Comment by calmh** [comment]
There is nothing related to this anywhere in Syncthing. I suspect you are looking at the effect of some firefox plugin or whatnot.
