### ISSUE TITLE
api: Reload TLS certs if they changed on disk

### ISSUE THREAD

**Issue by Zerorigin** [syncthing/syncthing#5375]
I found that when I changed the "Cert Name", and upgraded the “https-cert.pem” & "https-key.pem" for the new "Cert Name".
Syncthing do not automatically load the new certificates  unless I restart it manually.
This means that the Syncthing loads the certificate only at each boot.  It looks like a bad design.
I think Syncthing should check the cert name regularly and reload the certificate file.

In addition, it would be even better if it could provide the ability to automatically issue a Let's Encrypt certificate for Web GUI HTTPS and renewable.

### Version Information
Syncthing Version: v0.14.54, Windows (64 bit)
OS Version: Windows Server 2019
Browser Version: Microsoft Edge 18.17763

**Comment by AudriusButkevicius** [comment]
> In addition, it would be even better if it could provide the ability to automatically issue a Let's Encrypt certificate for Web GUI HTTPS and renewable

This would mean that you'd have to provide a hostname, which does not make sense in 99.9% of cases as users run it on localhost.

**Comment by Zerorigin** [comment]
I agree with you. I can issue and renew certificates automatically with other tools such as ACME.sh, Posh-ACME, etc.
I think if the user provided a hostname and has TLS encryption enabled (for Web GUI HTTPS), Syncthing should periodically check hostname and reload the certificate file, Just like Nginx did.
It avoids state (current connections, etc.) loss issues caused by restart Syncthing, It's more friendly.

**Comment by calmh** [comment]
I could see us periodically checking if the certs have changed; but this is rather low prio for our normal use cases. In the meantime you're probably better off fronting Syncthing behind Caddy or something else that speaks letsencrypt.

**Comment by canton7** [comment]
I'm fairly sure that nginx only loads its certificates on startup, and I don't think it's unreasonable that Syncthing does the same.

**Comment by Catfriend1** [comment]
Sidenote: Sophos Home offers a complete firewall that can automatically manage LetsEncrypt for your https hosts and it's free for private use.

**Comment by Zerorigin** [comment]
>           I could see us periodically checking if the certs have changed; but this is rather low prio for our normal use cases.

That sounds good news, thank you and the syncthing team members.

**Comment by Zerorigin** [comment]
> I'm fairly sure that nginx only loads its certificates on startup, and I don't think it's unreasonable that Syncthing does the same. Certbot has hooks to solve precisely this problem.

I re-checked the official Nginx document, which is really the same as you said. I'm sorry for my mistake.

**Comment by calmh** [comment]
Closing as I think it's acceptable to require a restart to reload certificates.
