### ISSUE TITLE
Feature Request : Select folder or subdirectory to sync or download

### ISSUE THREAD

**Issue by woam** [syncthing/syncthing#5382]
Syncthing Version: v0.14.54
OS Version: Windows 10 1809 

The feature might be 

1. to allow from remote devices to select which files or subfolders to sync from a shared folder.
2. to allow to choose between downloading or syncing the selected files/subfolders 

It's the first time i post a request on git, i hop i did it well and i have not asked for something i didn't see.
thx for your work.

**Comment by AudriusButkevicius** [comment]
Please search existing issues before opening duplicates.
