### ISSUE TITLE
gui: Impossible to change upgrade policy on an RC

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#5400]
- When on an RC, go into settings and change upgrades to "No upgrades". 
- Press save.

The following hilarious things happen:

1. A "discard your changes?" dialog pops up... (it should not)
2. A "must restart for changes to take effect" dialog simultaneously pops up *under* the other dialogs...
3. The only way out is to click "discard".
4. Click "restart". Syncthing restarts and comes back up with *another* "must restart" dialog.
5. Click "restart". Syncthing restarts and comes back up with the settings unchanged from step zero...

Now, we should enforce upgrades on RCs. But in some cleaner way than this... I had a vague feeling that we ignored the config setting and always upgraded to the next version when on an RC, and then started following the setting when back on a stable version. But I guess that's not the case.

If this is somehow the intended behavior we should instead grey out the selection when on an RC.

**Comment by ProactiveServices** [comment]
#4216 is related

**Comment by calmh** [comment]
Yeah not even "related", this is a precise duplicate.
