### ISSUE TITLE
sync mechanism of syncthing as a library or service

### ISSUE THREAD

**Issue by seniorivn** [syncthing/syncthing#5406]
Hi everyone, i'm interested in implementing serverless sync mechanism for task list and thought that syncthing is pretty neat, so maybe it could be separated as a library or service?

**Comment by imsodin** [comment]
https://github.com/syncthing/syncthing/issues/4085 is related and for further discussion, of what you want to do and how this might be possible with the current state of Syncthing, please start a discussion on https://forum.syncthing.net/.
