### ISSUE TITLE
Selection of time in versions GUI not possible without editing the string inside the textfield

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [syncthing/syncthing#5408]
Steps to reproduce:
- Create a folder with versioning 
- Click on the folder and click the versions button
- click on the date textfield
- select Custom Range
- click on one of the drop down selectors for time
- The list of numbers appears and disappears a very short time after it --> no time for choose an other time

I'm using the latest Firefox and ST v0.14.54 on Linux

**Comment by sisu4syncthing** [comment]
I can reproduce it on Mac with Safari Version 12.0.2 (12606.3.4.1.4) and Waterfox 56.2.6 (64-bit) with Syncthing  v1.0.0, macOS (64 bit)

**Comment by phuckstepp** [comment]
Does the same thing on Windows in Opera, Vivaldi and Chrome.

I temporarily fixed this by adding top:200px in the dev console to move it down. I then discovered that the date picker doesn't work at all and is stuck on 1969 and 1970!

![figure-1](https://user-images.githubusercontent.com/25500388/55552365-11502a80-56d5-11e9-952f-aa5a996bf1a0.png)

**Comment by AudriusButkevicius** [comment]
There is also a ticket for that but the later is I think browser related.

**Comment by grinapo** [comment]
Yep, still broken, firefox nightly.

**Comment by tomasz1986** [comment]
Is this actually a bug?

I mean, this only happens if there are no files in `.stversions` (as you can by the "No data." string in the screenshots). Obviously, the date picker does not work in such a case. I guess that maybe the input fields should be disabled if there are no files to restore?
