### ISSUE TITLE
Feature request: prioritize download or upload

### ISSUE THREAD

**Issue by innerspacepilot** [syncthing/syncthing#5409]
Hello.
It would be nice for syncthing to have an option to prioritize download or upload.
For example, when I sync my phone, I want files to be downloaded fast, uploading is less important.

Thank you.

**Comment by calmh** [comment]
You can set upload and download rate limits. Set a low upload limit and you have a prioritization of sorts.

**Comment by innerspacepilot** [comment]
Limit is not what I want.
I want downloads at full speed, then uploads at full speed :)

**Comment by calmh** [comment]
Well. The other side also wants downloads at full speed, so will request them as such. Given that we don’t control the other side the prioritization you’d like isn’t possible in the current design. The various rate limits you can set are the way to control this, unfortunately.
