### ISSUE TITLE
Illegal characters in folder name on auto accept

### ISSUE THREAD

**Issue by jj-uk** [syncthing/syncthing#5411]
Syncthing Version: v0.14.54
Linux 64bit (unRAID docker)

The "folder name" should be restricted to only allowable characters for folder names on all systems. Using disallowed characters creates folders in incorrect locations and with corrupt folder names.

For example, if a destination server is set to auto-accept folders, creating a folder on the source with the folder name "a/b/c/d" will create a bunch of nested folders. Similarly, creating a folder named
 "Hello / World : *|" causes issues when the destination auto-created folder is viewed in windows.

EDIT:
I do not know what will happen if the folder is named "../../../FOLDER" and i'm not prepared to try it :D

**Comment by calmh** [comment]
IMHO, the folder name should not be restricted like this. Potentially the auto accept directory name generation thing could be improved.

**Comment by jj-uk** [comment]
The auto-accept destination doesn't honour the versioning setting from the source. This may be another bug. It needs to be set in the destination server.

**Comment by calmh** [comment]
There are lots of folder settings. None of them propagate from one device to another. This is by design. There is another issue for having configurable defaults, though.
