### ISSUE TITLE
GUI theme stuck on dark

### ISSUE THREAD

**Issue by jj-uk** [syncthing/syncthing#5412]
### Version Information

Syncthing Version: v0.14.54
OS Version: Linux 64bit (unRAID docker)
Browser Version: Chrome WIn10

I changed the GUI theme to Dark, but cannot change it back. Changing the theme, doesn't appear to work at all. 
I have tried to change it to "Default" in advanced config but the setting is not applied.

Restarting the server and deleting cookies does not resolve this.

Settings -> GUI -> Theme - shows blank
Advanced Config -> Theme - shows "Default".

**Comment by wweich** [comment]
The advanced config value needs to be lowercase. That's why the select box value is blank.

Did you try `Ctrl`+`F5` (reload without cache)? (After settings the correct value of course)

**Comment by jj-uk** [comment]
OK, after entering "default" lowercase and reloading without cache, it's working again.
