### ISSUE TITLE
File versioning across drives

### ISSUE THREAD

**Issue by Xylobol** [syncthing/syncthing#5419]
I set Syncthing running on Windows to do Staggered File Versioning from D:\Synced\Music to H:\Syncthing History\Music, and it fails with "The system cannot move the file to a different disk drive." displayed in the Web GUI's Could not Sync dialog.

I expected it to perform the versioning across the two drives without hassle.

To reproduce..
 1. Create a synced folder on one drive (let's call it Drive A)
 2. Configure Syncthing on a Windows host to do Staggered File Versioning, with the Versions Path set to a different drive (let's call this one Drive B)
 3. Delete a file or folder from the synced folder on a different computer
 4. Syncthing on the Windows host will attempt to copy the files, but fail with "The system cannot move the file to a different disk drive."

### Version Information

Syncthing Version: v0.14.54
OS Version: Windows 10 Pro for Workstations, build 1809
Browser Version: N/A

**Comment by calmh** [comment]
This is known, but I didn't find an existing ticket for it. Versioning uses renames, which indeed don't work across drives. It's only "staggered" that allows a custom path, and it's not clear that that wasn't a mistake to begin with...

**Comment by Ferroin** [comment]
> I think we should disable custom versioning directories all together and force people to use symlinks.

While I'm all for simplifying things, this will lead to some pretty serious complications for Windows users who aren't power users unless Syncthing itself creates the symlinks.  I'm also pretty sure it won't work reliably (if at all) on Android.

**Comment by calmh** [comment]
It’s not rocket science to have a move operation that renames or copies/deletes as necessary though.

**Comment by AudriusButkevicius** [comment]
Sure, I am not disputing that we should support versioning across devices. I am however oppose to allowing people to specify arbitary paths. It should always be a symlink if they wish to point it to another device.

**Comment by Catfriend1** [comment]
I like the idea of symlinks very much, but yes, Android doesn't support symlinks unless one hacks and modifies a device a lot to use ext4 for external storage cards.
