### ISSUE TITLE
WebGui: Locally Changed Items vanish when clicking 10|25|50

### ISSUE THREAD

**Issue by sisu4syncthing** [syncthing/syncthing#5421]
Syncthing v1.0.0, macOS (64 bit)
using Safari on a Mac Version 12.0.2 (12606.3.4.1.4) and some older WaterFox on Win/Mac too.

Please see screenshots and description here:

https://forum.syncthing.net/t/webgui-locally-changed-items-vanish-when-clicking-10-25-50

When I open the "Locally Changed Items" window some files are shown, when I click on 10|25|50 buttons, the files disapear.
When I close the "Locally Changed Items" window and reopen it, the files are shown, but lost  if I click the  10|25|50 buttons.

I expect the files not to vanish, but display as usual when clicking on 10|25|50.

Can anyone reproduce?

**Comment by MoisieSyncthing** [comment]
Hello:

Same happening here - Syncthing 1.1.1, macOS 10.14.4, Safari 12.1.

Additionally (for me) only the first page of Locally Changed Items is shown - there are no Page 1, 2, 3, etc buttons shown:

<img width="888" alt="image" src="https://user-images.githubusercontent.com/43971157/55872800-cd05d400-5b85-11e9-8c42-e9a9b0aef918.png">
