### ISSUE TITLE
Folder Types ignored

### ISSUE THREAD

**Issue by hub101** [syncthing/syncthing#5424]
Have folder on 3 devices:

Send only (1.00 Win64) - Windows machine
Send & Receive (1.00 Linux64 / on Synology) - My Server
Receive Only (Android 0.14.51 / 0.10.15) - Mobile
(No versioning, Newest first)

1. Have sync problems on my server with some files, cant sync. (Permission denied and etc - this also bug, but not discussed here)
2. Okay, I delete out of sync files on Send only Win machine and Server manually, and command Win machine Override changes on Server to get sync done finally.
3. Server dont override changes, and still looking for files, writing to log:
```
2019-01-03 00:26:48 Puller (folder doc, file "-справочники/IMG_20181111_180819.jpg"): pull: no connected device has the required version of this file
2019-01-03 00:26:48 Puller (folder doc, file "-справочники/IMG_20181108_181114.jpg"): pull: no connected device has the required version of this file
```
4. Last copies of problems files still on Mobile (in Receive Only mode!). I start ST on Mobile and... Server gets this files from Mobile. Sync done ;-(

So, there is 2 problems:
1. Override dont work on deleted files.
2. ST req and gets deleted files from Receive Only device.

**Comment by hub101** [comment]
Finally Windows asks to Override again, and its works fine, files deleted everywhere and folders up to date.

**Comment by AudriusButkevicius** [comment]
Support is handled on the forum.
