### ISSUE TITLE
Allow editing ignore patterns texterea in GUI's folder dialog even when #include fails

### ISSUE THREAD

**Issue by Tstassin** [syncthing/syncthing#5425]
If an #include directive in the .stignore file references a wrong filename, the folder dialog's textarea for ignore patterns is greyed out with message "Failed to load ignore patterns".
The folder then has state "Stopped", urging the user to correct the situation.

The only workarounds are :

- Removing and readding the folder (which can be a heavy/costly task)
- Manually editing the .stignore file (which can be tricky for non tech savvy users who only use the GUI, why can I edit .stignore file with the GUI only when everything is ok with file parsing ?)

A good way to allow this re-editing would be to allow to edit ignore patterns' textarea when in state stopped or paused, triggering a rescan when saving options.

Syncthing Version: v1.0.0
OS Version: Mac OS, Ubuntu 16.04, Synology DSM 6.2
Browser Version: Firefox and Safari

**Comment by fiechr** [comment]
This seems still to be an issue, at least on Android with Syncthing v1.6.1?

Error message tells me there is an error, but I can't correct anything because the text area is greyed out.
