### ISSUE TITLE
Speed up file watcher

### ISSUE THREAD

**Issue by sveinugu** [syncthing/syncthing#5431]
As explained in https://github.com/syncthing/syncthing/issues/4953, the current integrated file system watcher has a lag of 10s before syncing. The previous inotify solution was almost instantaneous, in my experience.

It would be awesome if you would speed up the new watcher to be as good as instantaneous (e.g. 1s instead of 10s), or at least make this configurable.

Our setup that makes this important:

We are running a web based development platform off a central server (for reasons too complicated to explain here), with the possibility of on-the-fly changes to the GUI. In order to be able to develop using IDEs, we are using Syncthing to propagate code changes from code base on the developers laptop onto the server, which is then served on the web.

Previously, we could make some changes in the IDE, and in the time it took to change into the browser and refresh the page, the code change would have been propagated. Thus, we had real-time GUI programming even though the code was edited on a laptop and the web server was running on a separate server.

Now, however, the 10s lag in the new file watcher creates annoying small breaks in the development cycle, where we have to wait to make sure the changes have been propagated.

I suppose a 1s lag is too demanding on the CPU / disk for most users, but to make this configurable would be great for users like us!

**Comment by imsodin** [comment]
It is configurable: See `fsWatcherDelayS` in https://docs.syncthing.net/users/config.html#folder-element (available through actions->advanced).

**Comment by sveinugu** [comment]
Thanks. I misunderstood the discussion in the other threads. Sorry for the bother.
