### ISSUE TITLE
Minify Syncthing's JavaScript and CSS files

### ISSUE THREAD

**Issue by whalehub** [syncthing/syncthing#5432]
I ran my Syncthing site through [GTmetrix](https://gtmetrix.com/) earlier today and noticed that the site's loading time could greatly improved by minifying Syncthing's JavaScript and CSS. It should be fairly easy to implement this feature request because there are numerous tools out there that do it for you automatically, such as this one: https://www.minifier.org/

Here's the report from GTmetrix with all the relevant details: https://gtmetrix.com/reports/syncthing.datahoarder.xyz/csYS04j6

**Comment by calmh** [comment]
We could, potentially, but it would complicate the build pipeline. As the GUI is very cacheable and generally loaded from a physically close machine (often localhost) I don't really think it's worth it.

**Comment by whalehub** [comment]
@calmh Thanks for your feedback. I'll just make a fork of Syncthing in that case and maintain my own minified version.

**Comment by whalehub** [comment]
@calmh Just in case you're curious, you can find some benchmarks on the performance difference between the regular version of Syncthing and my minified Syncthing fork over here: https://github.com/whalehub/syncthing-minified/releases

**Comment by whalehub** [comment]
@calmh That's a fair point. I still want this feature for myself though and will be maintaining my own patched version of Syncthing for that purpose.
