### ISSUE TITLE
MultiArch for Docker

### ISSUE THREAD

**Issue by dargmuesli** [syncthing/syncthing#5436]
I'd like to feature-request Docker image releases of the same [binary release variety](https://github.com/syncthing/syncthing/releases). There will soon be a stable [docker manifest command](https://docs.docker.com/edge/engine/reference/commandline/manifest/) that allows the creation of image lists that allow automatic distribution of platform and architecture specific image variants. [All official docker images now use manifests](https://blog.docker.com/2017/09/docker-official-images-now-multi-platform/) and I think that would be a great addition to syncthing, which currently only serves the default linux/amd64 variant. I know that in #2591 linuxserver mentioned their release of such variants, but an official release is always more appealing.

**Comment by calmh** [comment]
Reasonable. Someone just needs to figure out how to do it.

**Comment by Dargmuesli** [comment]
Where can I find information about syncthing's build process for Docker? I found your TeamCity instance, but wasn't able to work out usable information from it.

**Comment by Dargmuesli** [comment]
I'm working on it and have already made good progress. One question though: why doesn't

https://github.com/syncthing/syncthing/blob/1e71b0093626a00867725813bebc733e967f5353/build.sh#L71-L75

match the [released platforms and architectures](https://github.com/syncthing/syncthing/releases)?

Can I update the script's list? And if yes to what: to the current release variety or to this [support grid](https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63#support-grid)?

**Comment by calmh** [comment]
It’s not used and can be removed. The exact list of archs to build is dependent on what the builder in question can do, so it doesn’t really make sense to have it in a build script here at all. I suggest you leave it alone for the purposes of any Docker related PR though.

**Comment by Dargmuesli** [comment]
Windows images do not seem to be currently supported, but the DockerHub guys wanted to [get this running in 2017](https://forums.docker.com/t/automated-windows-builds/24192). Seems like we'd need an AppVeyor-Build for that. Would you approve something like this or would you rather stay with DockerHub only and no Docker Windows builds?

**Comment by calmh** [comment]
Baby steps. Preference towards `docker/*` rather than a bunch of stuff at the root. Negatory on the AppVeyor - I can't see any reasonable rationale for running Syncthing under Docker in Windows to begin with, maybe there is one, but we certainly don't need to support that on day one.

**Comment by Dargmuesli** [comment]
I managed to get everything to build on [my DockerHub](https://hub.docker.com/u/dargmuesli). If you want you can already have a look into my fork's [docker folder](https://github.com/Dargmuesli/syncthing/tree/master/docker) including a README (but nvm the commit messages, I won't PR from there). I'll try to collapse those separate DockerHub repositories into one as I guess that's what you'd prefer. When I'm home, I'll try to run one container on my Rock64.
Another idea is to provide images from scratch to make the image size even smaller, following [traefik's example](https://github.com/containous/traefik-library-image), which is another Go application. One won't be able to debug those though.

**Comment by dargmuesli** [comment]
[DockerCon#315862](https://dockercon19.smarteventscloud.com/connect/sessionDetail.ww?SESSION_ID=315862)  looks very promising for this to be a thing soon :heart:

**Comment by qinghon** [comment]
In docker 19.03+, buildkit can build multiple architecture docker images at once and push all images to dockerHub
like

**Comment by rynr** [comment]
Can I do something to support this?
@qinghon, does running your build and verifying it works help?

**Comment by calmh** [comment]
From my side I'd like to see this happen, but it needs to happen with either a reasonably clear Docker hub setup (because that's where we build currently) or a build method based on a released version of Docker without preview features and weirdness (because that's our own build server). So far the ways to build this have been very involved or just plain didn't work on the Docker installations I have available.

**Comment by qinghon** [comment]
@calmh You can do it with github action, maybe you can use this.
[https://github.com/marketplace/actions/docker-buildx](https://github.com/marketplace/actions/docker-buildx)

**Comment by calmh** [comment]
PR's welcome :)

**Comment by qinghon** [comment]
@calmh Done! You can pull the **test** tag to test, but action only run as `push tag` event
```
docker pull qinghon/syncthing:v1.8.0-rc.7
```

**Comment by glensc** [comment]
looking for arm (v7) docker image

```
syncthing    | standard_init_linux.go:211: exec user process caused "exec format error"
```

**Comment by calmh** [comment]
This is now solved on the build server, images will be on Docker Hub from version 1.11.0 / 1.10.1 (whichever happens first). Until then there is an "edge" test build that tracks the `main` branch:

```
root@felicia-srv:~# docker run -it --rm syncthing/syncthing:edge --version
syncthing v1.10.0-rc.2.dev.1.gaa65c6f2 "Fermium Flea" (go1.15.2 linux-arm) docker@syncthing.net 2020-09-15 17:38:23 UTC
```

(That's my Raspberry pi.)
