### ISSUE TITLE
3 Advice and request

### ISSUE THREAD

**Issue by hktalent** [syncthing/syncthing#5439]
Advice and request
# 1、suport: command line interface    (CLI)
# 2、how p2p tunnel socks5, for anywhere, in private LAN，In case you cannot connect to the internet？
#  3、how use CLI fast send file or dir in LAN，in private network（LAN）?

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
