### ISSUE TITLE
panic: Should never get a deleted file as needed when we don't have it

### ISSUE THREAD

**Issue by lfam** [syncthing/syncthing#5443]
### Version Information

Syncthing Version: v1.0.0, built from Guix commit 9fb5771 (Jan 2 2019)
OS Version: Debian stretch (stable), up to date

I noticed that Syncthing had crashed on a headless Debian system, with this panic message:

```panic: Should never get a deleted file as needed when we don't have it```

The full backtrace as captured by journald is attached. Please let me know what other help I can provide.

[panic.log](https://github.com/syncthing/syncthing/files/2742953/panic.log)

**Comment by imsodin** [comment]
Unfortunately the trace only shows that it happened, not how. The actual "mistake" occurred earlier. Logs before the panic might contain something, but likely not (unless you had model or db debug facilities enabled). If the crash happens every time Syncthing is started (I think it should), please set `STTRACE=model,db` and post the log until the panic.

**Comment by lfam** [comment]
I don't see anything unusual in the logs preceding the crash.

The crash hasn't reoccured since the last time, which was also the first time it's crashed like this for me. I've enabled the debug logging and will post the logs here if it crashes like this again.

**Comment by AudriusButkevicius** [comment]
Closing until reproduced with better logs, as there is not much to cling onto for now.
