### ISSUE TITLE
User/group ownership following parent dir

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#5445]
Syncing ownership is an oft requested feature (#1329). It's also complex to do it right, which is why that issue languishes without action.

One common use case is to synchronize user home directories, or similar structures where a single *folder* might contain multiple directory hierarchies of files, each with a specific user/group owner. A simple way to handle such a case is to enable copying of user/group from the parent directory. That is, if we are creating `foo/bar/baz`, at the final stage where we set the permissions etc we look up the ownership of `foo/bar` and apply those to `foo/bar/baz`. This means that assuming `/home/jb/` is already in place and we are syncing `/home/`, anything under `/home/jb` will get the right ownership.

This scheme becomes just a checkbox similar to "ignore permissions"; no protocol changes are required. There is no need to have the same uid/gid across systems. The setting is device local only.

Creating a new user in this scheme requires doing it on both sides, to get the ownership info propagated. I'm OK with that. If this is missed, one can simply do a `chown -R` on the destination side, and the ownership will be preserved from that point onwards.

The situation on Windows might be more complex, but on the other hand the whole ownership issue is less important to begin with as ACLs are inherited and contain much of the same information.

On linux the process will need `CAP_FOWNER` (I think) which is something we should document that the user needs to sort out.

**Comment by Ferroin** [comment]
This is a wonderfully simple solution that should cover a vast majority of use-cases that people would want to sync ownership for.

It also happens to greatly simplify some less conventional use-cases, such as using Syncthing to keep data up to date on a website without running Syncthing and the web server as the same user (you can do this now, but you need to do a lot of work to get it working correctly and securely).

**Comment by incansvl** [comment]
Hopefully, lots of benefit in return for a small change. I'll try it out now. Good stuff!

**Comment by bdunncompany** [comment]
It might be helpful to be able to execute a command or script immediately following the successful sync of a file. For example, instead of having to use inotify or a crontab job, just have an advanced option to execute a chmod/chown immediately following each successful transfer. Is that something that would be difficult to implement?

**Comment by abePdIta** [comment]
Hi! Thank you for this feature! People may need also CAP_DAC_OVERRIDE (if some files is not readable by other users) and CAP_CHOWN. At least this is what I have found. Am I wrong?

**Comment by illwieckz** [comment]
Note that `group ownership following parent dir` is a file permission itself (group suid), this is something you can implement at filesystem level with `chmod` tool and, if syncthing was able to just sync metadata, not handle in syncthing at all (let the system rely on it).
