### ISSUE TITLE
Synology client creates folders with incorrect permissions

### ISSUE THREAD

**Issue by mxdpeep** [syncthing/syncthing#5448]
Receiving client creates folders with correct user but zero permissions, must chmod 0770 manually, pause and start the folder sync then.

drwxrwx---+ 10 root         syncthing  4096 Jan 11 12:12 .
drwxr-xr-x  40 root         root      12288 Jan 12 11:54 ..
d---------   3 sc-syncthing syncthing  4096 Jan 11 12:14 Android-Downloads

### Version Information

Syncthing Version: v0.14.49-15
OS Version: DSM 6.2.1-23824 Update 4, Synology DS414

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker. If it turns out to be an actual bug, this issue can be clarified and reopened.

Thanks!

**Comment by mxdpeep** [comment]
https://forum.syncthing.net/t/new-folder-permissions/11708

I consider this as a package bug, the package should create new folders with correct umask

**Comment by calmh** [comment]
That depends on your umask, your syncthing configuration, and how your NAS launches syncthing, which until that is determined makes this a support issue. Especially since there isn't a horde of Synology users reporting the same issue, which makes me think this is local to your setup.

**Comment by mxdpeep** [comment]
https://github.com/SynoCommunity/spksrc/issues/2140

> I don't think there's much we (SC) can do here. We have to use busybox' start-stop-daemon, seeing as Syncthing does not provide a daemon itself (as opposed to BTSync), and there are no available alternatives that allow us to manage the package otherwise.
> All the other options you mention should be built into the software itself. The only option that Syncthing has is Ignore permissions. Have you tried using that?

**Comment by mxdpeep** [comment]
as I am using official Synology DSM and no third-party setup, it's how SynoCommunity package works

**Comment by mxdpeep** [comment]
BTW BTsync worked out-of-the-box so the issue is the same - incorrect umask for the runtime

**Comment by calmh** [comment]
That makes it sound even more like a Synology setup issue, if it does not set umask and you depend on umask. I'll repeat it once more: this is a support issue. Discuss it all you want in the forum, until a bug is confirmed at which point we can fix it.

**Comment by mxdpeep** [comment]
oki, thanx!

**Comment by mxdpeep** [comment]
issue fixed by forced "chmod 0770" of the PARENT FOLDER
