### ISSUE TITLE
Folder marked as "Up to Date" with failed items

### ISSUE THREAD

**Issue by ProactiveServices** [syncthing/syncthing#5456]
Using v1.0.0, Windows 7 SP1 amd64

The folder has three items which can't be scanned because access is denied, which is accurate. If I hadn't happened to expand the folder's entry in the GUI accidentally I wouldn't have noticed. Presumably the desired behaviour is to mark the folder as "Out of Sync".

 The database is clean; it was freshly created yesterday and I have just run stindex on it.

**Comment by calmh** [comment]
I'm not sure what the desired state is, tbh. It's up to date in relation to the other devices, and not out of sync with them either. But there is of course some sort of error state present...

**Comment by ProactiveServices** [comment]
I'm sure I've never come across this state before. I've always been notified of things being broken and finding this came as a bit of a surprise. If Syncthing cannot read a folder inside a share, it may not be aware that say, there's a sync conflict. Or would a remote change to such a folder trigger an Out of Sync error?
