### ISSUE TITLE
avahi/zeroconf support

### ISSUE THREAD

**Issue by legrostdg** [syncthing/syncthing#5460]
This is a feature request for avahi/zeroconf support.

I did look at the doc for local discovery, but if I understood well, I have to deal with multiple firewalls, which is cumbersome:
https://docs.syncthing.net/users/firewall.html#local-firewall
https://docs.syncthing.net/specs/localdisco-v4.html?highlight=local%20discovery

My use case is a local network with several wifi and ethernet subnets, where multiple devices using syncthing should be able to communicate directly (without using a remote server): for example, my laptop is connected to 192.168.1.45, my smartphone to 192.168.2.99, my router has avahi-daemon installed with `enable-reflector` set to `yes`. It would be great to be able to just run syncthing and let avahi do its magic...

**Comment by calmh** [comment]
Yeah that'd be neat. I'd have liked to use dns-sd as local discovery to begin with. However, we can't listen for it ourselves (which would otherwise be easy) but need to integrate with whatever the local zeroconf daemon is on all platforms we support, and break totally if it's not installed. So unfortunately this seems like much more trouble than it's worth from my point of view.

**Comment by AudriusButkevicius** [comment]
There are various discovery protocols around. Why this over something else etc?

What we have works for mosr cases, hence I think this is a won't fix.

**Comment by calmh** [comment]
The advantage of following a standard is quite clear, but when I looked at it it would be disproportionally cumbersome to actually do it. Hence I agree with the OP, yet I also agree this is a "won't fix". Unless someone actually fixes it, in which case I'll happily merge.

**Comment by legrostdg** [comment]
OK.

Maybe some doc with simple avahi config would help. An user just need to add `/etc/avahi/services/syncthing.service` with:

```<?xml version="1.0" standalone='no'?><!--*-nxml-*-->
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">

<service-group>

  <name replace-wildcards="yes">%h</name>

  <service>
    <type>_syncthing._tcp</type>
    <port>8384</port>
  </service>

</service-group>

```

The other thing which would help a lot would be dns-sd support in the android app, where simple config like this one does not apply...

**Comment by legrostdg** [comment]
see https://github.com/syncthing/syncthing-android/issues/1266

**Comment by legrostdg** [comment]
Please note that adding this for a specific platform (ie android) would not break anything for the other platforms... The amavis config file seems a good enough solution for linux platforms, but we don't have the same solution for android.

**Comment by calmh** [comment]
I think there are two different things in play here.

Using dns-sd for local discovery would be tricky, although I'd like to do that, and can't be done by adding some config to avahi.

Announcing the GUI over dns-sd so that a suitable browser picks it up can indeed be done by adding some avahi conf. But I wonder what the overlap is between people comfortable adding config to some linux system daemon and not easily able to type in or bookmark the URL...

**Comment by legrostdg** [comment]
Mmh, I guess I mixed the GUI announce and the local discovery... Sorry about that, I really meant local discovery. Announcing the GUI could be interesting, too, but it's a lot less appalling ;).

Why couldn't the local discovery use the same mechanism? https://docs.syncthing.net/users/firewall.html mentions 21027/UDP, couldn't we just configure amavis to announce this?

**Comment by calmh** [comment]
You can configure amavis as you like, but Syncthing runs on everything from Windows to Android via macOS and a dependency on avahi is not on the cards.

**Comment by AudriusButkevicius** [comment]
Avahi as far as I understand is essentially the same as Bonjour/mDNS/dns-sd. Regardless, bonjour is just multicast unicast bla bla thingy, same like we do with local discovery, the only difference is that bonjour/mDNS/dns-sd etc has support in the routers to forward the service announcements to other subnets, which they won't do for syncthings local discovery. 

Also, perhaps Bonjour et al are more likely to go past firewalls and things like that.

Regardless, the case of "I have two subnets, and some thingy inbetween that forwards bonjour, and devices on each subnet for which I want to use local discovery" is not that common, so it seems like the TCP QOS setting request, that was used by a single user at some point and is no longer used.
