### ISSUE TITLE
Unexpected "filename too long"-error on ecryptfs / encfs 

### ISSUE THREAD

**Issue by mlechner** [syncthing/syncthing#547]
While syncing a repo from a NAS (ext4) to a private-home (ecryptfs on ext4 on ubuntu), I get the following error:
puller.go:474 INFO: create: error .... filename too long. And the whole repo stops syncing (not just the single file).
1. Neither filename (152 characters incl .syncthing. and spaces) nor path (214 characters) come up to the limits of ext4. Is this a ecryptfs poblem? But thn the following should not happen:
2. When the erroneous file is copied by hand, the sync goes on and syncy all the other files that have not been synced before.

Request: syncthing should not "All remaining files failed to sync. Stopping repo" (puller.go:211) if one file can not be synced.
2. Request/Bug(?): Syncthing shpuld be able to sync this file - any idea (or how should I test) why it does not?

**Comment by dpc** [comment]
I have 5 systems where the synced directory have exactly same path and one is not able to sycc due to "file too long". And the paths are less than 200, so I don't think they can be hitting 255 limit.

**Comment by AudriusButkevicius** [comment]
Check the config.for differences. File too long is an os error, we don't limit that. Also, different OSes might have different limits. Linux has a limitation for a single path component, windows has a limit for a total length.

**Comment by shenya123** [comment]
try long path tool.

**Comment by dpc** [comment]
This turned out to be encryptfs problem. https://github.com/vgough/encfs/issues/7

**Comment by calmh** [comment]
Yep
