### ISSUE TITLE
Indicate how long until the sync is finished

### ISSUE THREAD

**Issue by leafcutterant** [syncthing/syncthing#5472]
I propose two new indicators which informs the user about the progress of the sync.

1. Display the percentage progress of the sync compared to the *data added/modified since the last fully synced state*. Reason: when you have a 10 GB folder, and add 10 MB, "99%" it doesn't serve any useful information. When a sync is on-going, I as a user am not interested in the full size of the folder, but the progress compared to recently changed data. I'd say this could even replace the present percentage indicator.

2. The above lead me to an even more important indicator: an estimate of how much time is left until the sync is finished, based on the data left to sync and the recent network speed.

**Comment by AudriusButkevicius** [comment]
We can't, as we don't know if we will find the data locally avoiding a download, if not, who we will download the data from (as there might be multiple candidates having the data, each with different network throughput), etc.
