### ISSUE TITLE
[Enhancement] Backup Current Configuration

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing#5477]
I would love to see a new feature to Syncthing for PC added that allows me to backup my current Syncthing configuration and user data within a simple, easy wizard.

**Comment by uok** [comment]
You can simply backup the folder - please see documentation on [Syncthing configuration](https://docs.syncthing.net/users/config.html) for more information

**Comment by AudriusButkevicius** [comment]
Yes, just backup the folder. Also, I am not sure what you mean by "user data", but I would not recommend backing up the database, as restoring the backup into empty folder structure would nuke the data. In which case I suggest backing up config and the certificates.

**Comment by AudriusButkevicius** [comment]
What would the wizard do? Allow you to download a file to your disk which is already on your disk?

**Comment by jebeld17** [comment]
Yes. Put everything, including configuration information, into one file that can be re-imported on a new machine.
