### ISSUE TITLE
Docker: Exposed Volumes

### ISSUE THREAD

**Issue by Dargmuesli** [syncthing/syncthing#5480]
The [README-Docker.md](https://github.com/syncthing/syncthing/blob/master/README-Docker.md) references two exposed volumes. But the Dockerfile does not expose the first (`/var/syncthing/config`). Shouldn't the README get corrected?

**Comment by calmh** [comment]
Probably. Only /var/syncthing is a volume by default, although the user can of course map as they wish

**Comment by Dargmuesli** [comment]
But if they do thay receive a `chmod` error. Certificates cannot be generated, ... I just tried and wondered for an hour why it isn't working. Volumes inside default volumes seem not to work.

**Comment by jordanpotter** [comment]
I attempted to create a data volume for `/var/syncthing/config` and came across the same issue. Ubuntu 18.10 running Docker 18.09.2

**Comment by calmh** [comment]
I don't think this has anything to do with volumes as such. If you *do* use extra modules you need to make sure Syncthing has write permissions on them. If it doesn't, and cannot create certificates in its config dir, then it obviously cannot work.
