### ISSUE TITLE
minHomeDiskFreePct is still present in fresh configs

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing#5482]
Hi,

when I start syncthing on a fresh installation it creates the config on first launch. There, "minHomeDiskFree" and "minHomeDiskFreePct" tags are both present in the generated xml while "minHomeDiskFreePct"  is deprecated and unused. Relevant PR was #4087 .

Can "minHomeDiskFreePct" please be removed (after checking if the issue is valid)?
`Location: <options> Tag`

Kind regards
Catfriend1

### Version Information
Syncthing Version: v0.14.28+ (until current v1.0.0)
OS Version: all OS

**Comment by calmh** [comment]
Might be worth it to clean up and remove old config migration code. Version 25 is from 2017-10, we could remove all the older variants and their corresponding deprecated fields. (MinHomeDiskFree stuff is version 20.)

**Comment by calmh** [comment]
The user gains by getting happier and thus more efficient developers who have to carry less old baggage. (In addition to bugs like these becoming solved.)

**Comment by imsodin** [comment]
I don't disagree in principle, but this issue seems to be so minor as identified by Audrius, that dropping config migration seems to me like a bit of a disproportionate response: https://github.com/syncthing/syncthing/pull/5484

**Comment by calmh** [comment]
Fine, fixing this is trivial and doesn't require dropping everything else I suggested. I still think we should do that, but maybe with a cutoff of two years or so, just to keep from accumulating baggage in infinity.

**Comment by canton7** [comment]
It's not baggage in the sense that it needs to be maintained over time, though. It's like a database migration: you write it once, then you put it somewhere out of the way and you forget about it forever.

**Comment by calmh** [comment]
Except here we have a bug in the code we could have removed a year ago. But yes, sort of, and I'm just worsening the issue by continuing to discuss it. :)
