### ISSUE TITLE
stall after running live qemu image

### ISSUE THREAD

**Issue by capocasa** [syncthing/syncthing#5483]
- what happened

Reporting a bit of an edge case, mostly just to document the behavior, with the understanding that it might or might not be worth fixing, except perhaps if it also helps with other bugs, or to increase robustness in general.

On my up-to-date arch linux laptop, I placed a qcow2 hard drive image containing Windows 7 into 20GB synced folder with many files and watching enabled, launched qemu, and used the virtual Windows 7 system for browsing the web and installing desktop software (synctrayzor among others, but did not connect it). The folder is shared with a raspberry pi running raspbian stretch on the local network, and nothing else.

Shortly after, there were random disconnects between the pi and the local computer, and there was no longer any sync traffic until I moved the disk image out of the folder and restarted syncthing on the pi.

I placed the image into another synced folder with no watch and it worked fine.

 - what you expected to happen instead, and

I would expect a large file that is modified many times per second to be synced just as well as a file that is modified less frequently, and for the network to continue to operate normally.

 - any steps to reproduce the problem.

Place any virtualized disk image into a shared folder and launch it. The command line I used was:

qemu-system-x86_64 \
	-m 2048\
	-enable-kvm\
	-display sdl\
	-hda myimage.qcow2\
	-net nic -net user,smb=$HOME/Public\

There was no relevant log output on either device.

My theory is that there was an overload of inotify events that bogged down the pi, my local system, or both.

If this is true, I suspect it would be good for the stability of the platform to implement something along the lines of a 500ms debounce to inotify events, perhaps combined with an escalating throttle.

I suspect the behavior could be appropriately simulated for development purposes by using a script to continuously write random data at random locations into a large file while constantly opening and closing it.

### Version Information

laptop: Arch Linux, up-to-date, running syncthing 1.0.0 from package manager

server: Raspberry pi running up-to-date raspbian stretch, running syncthing 1.0.0 from package manager

**Comment by AudriusButkevicius** [comment]
Only a single scan is allowed to happen at a time, and events are summarised and dispatched once every 10s. I suspect your PI was just melting having to scan large files with a crypto hash, and failed to respond to pings on the network. Weak devices as weak.

If you want to entertain this further, use the forum.
