### ISSUE TITLE
TestIssue2571 failure on OpenBSD

### ISSUE THREAD

**Issue by vext01** [syncthing/syncthing#5489]
Hi again,

Continuing with the OpenBSD test failures, TestIssue2571 non-deterministically fails on my laptop using today's master.

Here's a log showing a fail and then a pass:
https://gist.github.com/vext01/251072b273fc8037be5a5f347946a7c7

After seeing the failure, I ran `git status` and saw an un-tracked dir, which I then removed.
```
$ rm -rf testdata/internalScan/
```

Re-running that test on it's own, I can now no longer repro. Running the top-level test suite, I can get it to fail again (`go run build.go test`).

After doing that, I have some other untracked dirs:
```
        lib/model/testdata/delDir/
        lib/model/testdata/replaceDir/
```

Is there perhaps some racy teardown?

**Comment by imsodin** [comment]
There shouldn't be, but who knows. These are tests that operate in the same directory instead of a temporarily generated one, so one not cleaning up affects the other. Can you test with this commit (probably not yet PR ready): https://github.com/syncthing/syncthing/commit/158b054e7890d028025d0aa410181e8966b03373

**Comment by vext01** [comment]
After applying your patch I'm unable to get TestIssue2571 to fail.

Were you expecting to fix other tests too? There are other failures.

**Comment by imsodin** [comment]
Potentially, yes. I mostly looked at the stuff that you mentioned at one point, not "everything" (whatever that would mean :) ). Can we move this debugging to the forum? I am grateful for your help, but it's a bit noisy and trying to keep issues separate (as appropriate for an issue tracker) is a bit of a hindrance at this stage: https://forum.syncthing.net/t/openbsd-test-debugging/12799

**Comment by vext01** [comment]
> Can we move this debugging to the forum?

Yes, that's fine. I'm starting to feel quite bad about junking up the tracker too!

**Comment by imsodin** [comment]
This was fixed by one of the commits resulting from the debugging in https://forum.syncthing.net/t/openbsd-test-debugging/12799
