### ISSUE TITLE
Create share folder error

### ISSUE THREAD

**Issue by nonetracer** [syncthing/syncthing#5497]
Hello, i have an error, and i don't konw where is wrong.

My system is CentOS7 and installed syncthing v1.0.0. After initialed, i create a share folder,but show a error "Saving .stignore: open /usr/tomcat/webapps/ROOT/temp/ueditor/.syncthing.tmp.921541731: read-only file system".
then, i set ueditor folder right to 777, but is error still.

Do you konw what's wrong? 
Very Thinks!

**Comment by calmh** [comment]
The default harding options in the systemd unit will prevent writes to /usr. You will need to remove the `ProtectSystem=full`. Apart from that,

This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by nonetracer** [comment]
Thank you
