### ISSUE TITLE
lib/model: suspicious calls to strings.HasPrefix

### ISSUE THREAD

**Issue by Quasilyte** [syncthing/syncthing#5504]
https://github.com/syncthing/syncthing/blob/c75cfcfd06d09b5b2f7c242cfe86a7751d231587/lib/model/model.go#L2332

The `strings.HasPrefix(prefix, f.Name)` call looks suspicious.
There is a chance that `strings.HasPrefix(f.Name, prefix)` was meant instead.

**Comment by AudriusButkevicius** [comment]
I think it's ok, as the comment explains, we try to avoid the directory that is equal to thw prefix.
