### ISSUE TITLE
Leaking goroutines through model and leveldb

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#5505]
While running a model test with `-count 1000` I ran into OOM. Looking at a stacktrace I found these culprits:

```
    340 github.com/syncthing/syncthing/lib/model.(*ProgressEmitter).Serve
    340 github.com/syndtr/goleveldb/leveldb.(*DB).compactionError
    340 github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction
    340 github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain
    340 github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction
    340 github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain
```

The progress emitter is straight forward: It should be added to the supervisor not manually run in a goroutine. The leveldb stuff is because we do not close the the database, both in tests and in cmd/syncthing's `main`. In `main` the database is manipulated before passing it to the model, but not concurrently with the model. So there's two options

1. Close the db on `model.Close`: Nice because we don't need to think about it in all the tests.
2. Close the db where it is created, meaning in cmd/syncthing's `main` and every single test that uses a db. The "cleaner" approach because the same function that opens it also closes it but it's tedious.

Opinions? @AudriusButkevicius @calmh

**Comment by AudriusButkevicius** [comment]
I think the db should be closed where it was opened.

**Comment by imsodin** [comment]
Actually, looking at your `locations` package, I wan't to open and close the db in `model` - `main` has no business handling the database. And `locations` allows for that to happen.

**Comment by calmh** [comment]
I don't think the model package should carry the responsibility for opening, upgrading, etc the database. If nothing else that's quite late in the startup, and it's least *one* thing that isn't under the jurisdiction of `model`. I think open+defer-close, in main and in tests.

**Comment by imsodin** [comment]
Ok, got it - also `db.OpenMemory` for tests...

**Comment by imsodin** [comment]
And obviously this is more complicated than I thought: `leveldb.DB` panics when any function is called on it after `Close` (except `Close` again). It's in no way assured that after `model.Stop` there won't be any such calls (exported functions on `Model`, `go sendIndexes`, probably more). Now I could add some `closed` channel to `Model` and try to check for that wherever necessary, but that's both tedious and error prone. A bit less error prone but just as or even more tedious would be to  make `leveldb.DB` a named member of `db.Lowlevel` and add such a close condition on `db.Lowlevel`, which then protects all functions on `leveldb.DB`. And all of that just for tests, as otherwise we never create multiple models.  
Any ideas for elegant solutions?

**Comment by calmh** [comment]
I'm removing the bug tag (for release notes) because as far as I understand this wasn't an issue in actual production (since we don't restart the relevant components there).
