### ISSUE TITLE
[Feature] Use Ed25519 for update signing

### ISSUE THREAD

**Issue by pipboy96** [syncthing/syncthing#5506]
Ed25519 would be a better choice for update signing algorithm than ECDSA with a current [less-than-perfect curve choice](https://safecurves.cr.yp.to/) (the same concerns that apply to P-256 and P-384 also apply to P-521).

**Comment by pipboy96** [comment]
@calmh I understand that such attack would most likely not be based on breaking the underlying crypto, but why use substandard crypto in 2019?

**Comment by calmh** [comment]
Because it's vastly sufficient for purpose and changing it is unnecessary work & risk, including managing a transition for existing versions out there.
