### ISSUE TITLE
"Fatal error: unexpected signal during runtime execution"

### ISSUE THREAD

**Issue by dorearendil** [syncthing/syncthing#5516]
Syncthing Version: v1.0.1
OS Version: MacOS 10.8.6

Since Syncthing automatically updated to the newest version, it stopped working on my old Mac.
I get a "fatal error: unexpected signal during runtime execution" error now, and Syncthing soon exits after failing to start.
It works fine on my Android phone and on my Ubuntu laptop though.
Please see the attached log output.
[panic-20190207-110641.log](https://github.com/syncthing/syncthing/files/2840085/panic-20190207-110641.log)

**Comment by calmh** [comment]
Unfortunately your macOS is too old. 10.10 is the oldest officially supported version. You can use the newest Syncthing that still works for you and disable auto upgrades.

**Comment by dorearendil** [comment]
Understood, thanks.
Could you kindly point me to the right location to download the previous version of Syncthing?

**Comment by calmh** [comment]
They are all here on GitHub; https://github.com/syncthing/syncthing/releases

**Comment by dorearendil** [comment]
Thanks!
I tried downloading several previous versions that all used to work.
However, none of them work now -- I get the same issue as with the latest version...
Do I need to uninstall/replace any file to be able to properly downgrade?
Or could my issue originate from something else than the automatic upgrade?

**Comment by imsodin** [comment]
Can you please open a thread on forum.syncthing.net for further investigations, as this is where support happens - thanks.
