### ISSUE TITLE
Error while traversing

### ISSUE THREAD

**Issue by jopels** [syncthing/syncthing#5519]
### Version Information
Syncthing Version: v1.0.1 
OS Version: FreeBSD (64 bit)

### The error
I created a share on which I withdrew write permissions afterwards and then I get the following error message:
![error](https://user-images.githubusercontent.com/16117940/52537448-4d1ae380-2d67-11e9-9177-c889f2a9f194.png)

I would expect that Syncthing still scans the folder and still syncs files to other devices.
But this is not the case. Syncthing actually stops scanning and syncing the folder. 

### How to reproduce
1. Create a "Send Only" shared folder
2. Reduce the permissions in the file system to "read-only" for the syncthing process

**Comment by calmh** [comment]
Syncthing should indeed not need write permissions to scan, nor does it stop the entire folder in your screenshot above. (It does however stop subscribing to notifications.)

So lots more info needed here - screenshots of the permissions etc at the very minimum. As that'll be a bit of back and forth and looks like support please do it on the forum, until the existence of a bug is determined.

**Comment by jopels** [comment]
Sorry I should have been more specific. The folders needed "execution" permissions. Now everything is working as expected.
