### ISSUE TITLE
[ ] (space) character at the end of folder name generates an error

### ISSUE THREAD

**Issue by bacomino** [syncthing/syncthing#5522]
### DO NOT REPORT SECURITY ISSUES IN THIS ISSUE TRACKER

Instead, contact security@syncthing.net directly - see
https://syncthing.net/security.html for more information.

### DO NOT POST SUPPORT REQUESTS OR GENERAL QUESTIONS IN THIS ISSUE TRACKER

Please use the forum at https://forum.syncthing.net/ where a large number of
helpful people hang out. This issue tracker is for reporting bugs or feature
requests directly to the developers. Worst case you might get a short
"that's a bug, please report it on GitHub" response on the forum, in which
case we thank you for your patience and following our advice. :)

### Please use the correct issue tracker

Problem is about a sync from Syncthing Android (original files) to SyncTrayzor (syncked files).

### Does your log mention database corruption?

No.

### Please do post actual bug reports and feature requests.

If your issue is a bug report, replace this boilerplate with a description
of the problem, being sure to include at least:

 - what happened,
[ ] (space) character at the end (auto-generated by Android keyboard) if folder name generates an error : 

[XXYAU] 16:43:27 INFO: Puller (folder "_Bacquet" (_Bacquet), file "__Mes photos\\__photos\\_2019\\Carnaval des enfants St Raphaël \\IMG_20190209_163711.jpg"): pull: filename is invalid
[XXYAU] 16:43:27 INFO: Puller (folder "_Bacquet" (_Bacquet), file "__Mes photos\\__photos\\_2019\\Carnaval des enfants St Raphaël \\IMG_20190209_163713.jpg"): pull: filename is invalid
[XXYAU] 16:43:27 INFO: Puller (folder "_Bacquet" (_Bacquet), file "__Mes photos\\__photos\\_2019\\Carnaval des enfants St Raphaël \\IMG_20190209_164219.jpg"): pull: filename is invalid

Then I deleted the [ ] character and everything goes all wright...

 - what you expected to happen instead, and
Win10 should create the file :)

 - any steps to reproduce the problem.
Just try to sync a file in a folder named with a [ ] at the end

Also fill out the version information below and add log output or
screenshots as appropriate.

If your issue is a feature request, simply replace this template text in
its entirety.

### Version Information

Syncthing Version: v1.0.1
OS Version: Windows 10
Browser Version: SyncTrayzor

Excuse me for my bad English :P

**Comment by nekr0z** [comment]
As far as I know, Windows does not support (or at least did not, up until Win8) file/directory names ending (or beginning) with space. If that is still true for Win10, then this behaviour of syncthing is expected and correct.
