### ISSUE TITLE
Force Relay for Specific Devices

### ISSUE THREAD

**Issue by agent0404** [syncthing/syncthing#5530]
I am sorry if this is already possible. I have not seen anything in the docs about it

I would like to be able to force the use of a relay for specific devices

This will prevent my home IP address from being leaked to people I have shared folders with

This could be an option under "Edit Device"

**Comment by calmh** [comment]
Set the device address to a relay address, and make sure that device also listens on this specific relay. 

(Further discussion to the forum :)
