### ISSUE TITLE
Sharable syncthing updates [ENHANCEMENT]

### ISSUE THREAD

**Issue by MrDarius125** [syncthing/syncthing#5533]
a feature where the updates of syncthing could be shared between peers that may not have a constant internet connection would be nice to have, it would also save bandwith for people who use syncthing on all their devices and have limited data (files shared within the network).

**Comment by uok** [comment]
Thanks for sharing your idea!
This feature has been suggested before (#1085) and will not be implemented.
You can set up a [Custom Upgrade Server](https://docs.syncthing.net/users/custom-upgrades.html) where updates are handled from a local webserver. Or you can copy an up-to-date syncthing file at regular intervals to a network drive and distribute it from there in your local network,
