### ISSUE TITLE
resurrecting parent dir: mkdir /path/to/myfolder/on/sd/somefolder: invalid argument

### ISSUE THREAD

**Issue by timakro** [syncthing/syncthing#5538]
### Version Information

Syncthing Version: v0.14.51-dirty (Syncthing-Android-Version 0.10.15)
OS Version: LineageOS 14.1 (Android 7.1.2)

I'm trying to sync from Linux to an external SD card of an Android device with the experimental root option enabled. I get this log message repeatedly until Syncthing gives up:

```
DATE TIME I/SyncthingNativeCode( 4630): [U7TGJ] INFO: Puller (folder "Myfolder" (FOLDERID), file "somefolder_containing:colon/my_file_with_japanese_utf8_symbols"): resurrecting parent dir: mkdir /path/to/myfolder_containing:colon/on/sd/somefolder: invalid argument
```

**Comment by imsodin** [comment]
Most likely the filesystem on your external SD card doesn't support filenames with colons, nothing Syncthing can do about that. Please use the forum for support.
