### ISSUE TITLE
Implement Electron web app for manage Syncthing settings

### ISSUE THREAD

**Issue by MurzNN** [syncthing/syncthing#5542]
At now Syncthing have good web interface for managing config, but for many regular users it's hard to understand why it must open web page in browser for manage config.

For solve this problem will be good to implement easy Electron app, that will open Syncthing settings web page in separate window, like native app.

**Comment by wweich** [comment]
Have a look at the syncthing homepage (https://syncthing.net). There are already GUI Wrappers.

**Comment by AudriusButkevicius** [comment]
Electron is a cow, it requires 80mb binary size increase just to show a browser tab.
