### ISSUE TITLE
new version android app not work

### ISSUE THREAD

**Issue by wienna11** [syncthing/syncthing#5549]
hello, your new android version 0.10.17 not work on android 4.4.4 at all and not connect to your servers.
i get tls handshake error
![screenshot](https://user-images.githubusercontent.com/47794344/53042613-91e8fd80-347e-11e9-8dcf-c04cc3d757c2.png)

**Comment by AudriusButkevicius** [comment]
Wrong repo, same issue as https://github.com/syncthing/syncthing-android/issues/1255
