### ISSUE TITLE
ignoreDelete on receiver breaks sync on sender.

### ISSUE THREAD

**Issue by crocket** [syncthing/syncthing#5550]
### What happened

Sender reports a folder is permanently out of sync until ignoreDelete is disabled on receiver.

[android.log](https://github.com/syncthing/syncthing/files/2882676/android.log)
[syncthing.log](https://github.com/syncthing/syncthing/files/2882677/syncthing.log)
![screenshot_20190220-105657](https://user-images.githubusercontent.com/748856/53060794-05caea80-34ff-11e9-85af-6ec9e4a509b0.png)
![screenshot_20190220-105734](https://user-images.githubusercontent.com/748856/53060795-05caea80-34ff-11e9-9c48-2cc94ce377e6.png)
![screenshot_20190220-105740](https://user-images.githubusercontent.com/748856/53060797-06638100-34ff-11e9-86ab-cb4412e79065.png)
![screenshot_20190220-105800](https://user-images.githubusercontent.com/748856/53060799-06638100-34ff-11e9-8f9a-a71828600031.png)

### What I expected to happen

Sender doesn't report that a deleted file is out of sync with receiver.

### Steps to reproduce the problem

Receiver is a desktop computer. Sender is nexus 5.
On receiver, ignore delete for a folder.
On sender, delete a file in the folder.

### Version Information

Syncthing Version: v1.0.1 on both sender and receiver
OS Version: LineageOS 14.1 on sender. Gentoo Linux on receiver

**Comment by AudriusButkevicius** [comment]
This is expected, because it refuses to delete hence it is not in sync with the global state. This was answered in many issues before and on the forum so I suggest you check existing issues oppose of just increasing the ticket counter.

**Comment by imsodin** [comment]
This is expected, and part of why this is an advanced config not found in the regular folder settings. The receiving device just doesn't act on the delete update and correctly reports that it still has the file, i.e. is on a lower version of that file and this out of sync.
