### ISSUE TITLE
fsWatcher and periodic scanning ignore new camera photos and new screenshots on android.

### ISSUE THREAD

**Issue by crocket** [syncthing/syncthing#5551]
### What happened

New camera photos and new screenshots are ignored by fsWatcher and periodic scanning on android.
I have to manually trigger full rescan in order to make them recognized by syncthing.

It seems periodic scanning doesn't work on time because uptime grows very slowly.

### What I expected to happen

They are captured by fsWatcher and periodic scanning.

### Steps to reproduce the problem.

* Take a photo with LineageOS camera app
* Take a screenshot of android screen by pressing volume down button and power button together.

### Version Information

Syncthing Version: v1.0.1
OS Version: LineageOS 14.1

**Comment by imsodin** [comment]
Can you please move this to the forum. At this stage it is not clear whether there is a bug at all, whether the two things are related and whether (parts) are relevant only to syncthing-android.
