### ISSUE TITLE
0.14.48 No password update

### ISSUE THREAD

**Issue by daniel-lucio** [syncthing/syncthing#5552]
I know its kind of an old release, (I will update soon).
For now, using 0.14.48, I can't set up a password.
I put the admin/XXXXX password, and it says it is set up correctly. Then, I go to incognito mode and try it, and it won't work. I have restarted the daemon.
The config.xml file shows the admin and password with the $2a$ hash (blowfish?)

Any suggestion besides upgrading?

**Comment by AudriusButkevicius** [comment]
Read the issue template again please.
