### ISSUE TITLE
Need help to pack RPM without downloading packages

### ISSUE THREAD

**Issue by daniel-lucio** [syncthing/syncthing#5553]
Some distributions won't allow the go get command to download packages on build time. They need to unpack the tar with them. I am working to make syncthing 1.x available in Mageia (currently 0.14 is there)

So, If i want to tar the 1.0.1 or 1.1.0, what would the commands to download all dependencies and build without internet access?

**Comment by AudriusButkevicius** [comment]
Support happens on the forums, but essentially check help of "go mod".
