### ISSUE TITLE
Change "Introduced by" icon

### ISSUE THREAD

**Issue by otbutz** [syncthing/syncthing#5560]
Just nitpicking but the introducer symbol doesn't fit IMHO.

Current symbol:
https://forkaweso.me/Fork-Awesome/icon/meh-o/
![grafik](https://user-images.githubusercontent.com/22315436/53410168-4e811880-39c3-11e9-9b4f-6cc506e126a5.png)

Suggestion:
https://forkaweso.me/Fork-Awesome/icon/handshake-o/
![grafik](https://user-images.githubusercontent.com/22315436/53410079-11b52180-39c3-11e9-9b31-1186e8bd13fa.png)

**Comment by AudriusButkevicius** [comment]
Make a pr if you want it changed, not an issue.

**Comment by calmh** [comment]
That's unfair. They can of course create a PR, but an issue is never wrong regardless.

**Comment by AudriusButkevicius** [comment]
Well, perhaps I like it the way it is, and don't want it changed. Who's right in that case?

**Comment by calmh** [comment]
Then you can argue for that, but that's different from "don't file an issue, fix it yourself".

**Comment by otbutz** [comment]
> Well, perhaps I like it the way it is, and don't want it changed. Who's right in that case?

I'd say form follows function. A mildly disappointed smiley doesn't really fit the bill here IMHO.

**Comment by AudriusButkevicius** [comment]
My point is that such petty issues would overflow the issue count integer real quick, especially when these are all down to personal preference and can be argued about. Hence it's probably better to throw a PR and see if it sticks oppose to a ticket that nobody will ever close.

**Comment by calmh** [comment]
I understood that that was your intention, but I disagree.

**Comment by nekr0z** [comment]
> Hence it's probably better to throw a PR and see if it sticks oppose to a ticket that nobody will ever close.

I see your point and totally understand your pain, but in that case it's you who should be fixing [contribution guidelines](https://docs.syncthing.net/dev/contributing.html). ;)

> Make sure there is an issue that describes the change you want to do. If the thing you want to do does not have an issue yet, please file one before starting work on it.
