### ISSUE TITLE
Folder sync "stalled" due to "no such file" error

### ISSUE THREAD

**Issue by fragtion** [syncthing/syncthing#5562]
Hi,

I ran into a strange issue this morning that I haven't seen before

One folder (synced between two nodes, let's call them "System A" and "System B") stopped syncing due to the following error:

[FMTE6] 10:10:15 INFO: Puller (folder "normarkza" (gpledg-sync), file "cur/1551253440.M280094P11491V0000000000000831I0000000002180988_0.rapalasa-fw,S=21800"): finisher: pull: no such file

The file was generated on "System A"

When I checked the GUIs, both sides showed blue text messages for this folder. If I remember correctly, one side was reporting  "Syncing" and the other side was reporting "Scanning". But maybe I'm wrong and both sides said "Syncing".   It remained unchanged like this for about 5 hours before I decided to take action, as there were other changes which were not syncing as a result.

What is strange is that when I decided to investigate, I found that the file now existed on System B, but not on System A, even though it was created on System A.

I manually paused the folder, and used rsync (-avh) to ensure that the file exists on both sides, and then unpaused the folder.  It did a quick scan of the folder and then the backlog of unsynced files began to propagate again and the folders are now back in sync.

 I Just found it really strange that this missing file caused the folder to get stuck in a syncing state. Usually when this happens, other changes continue to sync fine and the error goes away after a while

Admittedly, this happened on my fork (fragtion/syncthing) which I'm using to sync maildirs - but until this point everything has been working beautifully for over 50 users mailboxes on this setup which I've had going for several months now

Fortunately not a train smash but just alluding you guys to the potential of a bug that could stall a folder indefinitely, mid-sync.
Thank you.

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Also, failure of a file to sync regardless of reason doesn't block other files from syncing, so "stalling" should not happen I think.

Thanks!
