### ISSUE TITLE
Windows XP not working with 1.1

### ISSUE THREAD

**Issue by devisbal** [syncthing/syncthing#5575]
### Version Information

Syncthing Version: v1.1.0
OS Version: Windows XP

...
Panic at 2019-03-05T12:25:48-05:00
panic: Failed to find GetFileInformationByHandleEx procedure in kernel32.dll: The specified procedure could not be found.

goroutine 1 [running]:
syscall.(*LazyProc).mustFind(0x11c459e0)
	C:/Go/src/syscall/dll_windows.go:287 +0x42
syscall.(*LazyProc).Addr(0x11c459e0, 0x1240e60)
	C:/Go/src/syscall/dll_windows.go:294 +0x21
internal/syscall/windows.GetFileInformationByHandleEx(0x768, 0x9, 0x11ccb0b4, 0x8, 0x3, 0x11c2a048)
	C:/Go/src/internal/syscall/windows/zsyscall_windows.go:353 +0x27
os.newFileStatFromGetFileInformationByHandle(0x11c23040, 0x1a, 0x768, 0x0, 0x11c23040, 0x1a)
	C:/Go/src/os/types_windows.go:52 +0x135
os.(*File).Stat(0x11c06ff8, 0xc9fa9c, 0x11c06ff8, 0x0, 0x11c06ff8)
	C:/Go/src/os/stat_windows.go:55 +0x133
io/ioutil.ReadFile(0x11c23040, 0x1a, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Go/src/io/ioutil/ioutil.go:62 +0xac
crypto/tls.LoadX509KeyPair(0x11c23040, 0x1a, 0x11c22e40, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	C:/Go/src/crypto/tls/tls.go:189 +0x48
main.syncthingMain(0x11c22326, 0x11, 0x0, 0x0, 0x0, 0x0, 0x10001, 0x11c22f40, 0x1f, 0x0, ...)
	C:/BuildAgent/work/174e136266f8a219/cmd/syncthing/main.go:583 +0x299
main.main()
	C:/BuildAgent/work/174e136266f8a219/cmd/syncthing/main.go:388 +0x245

goroutine 6 [select]:
github.com/syncthing/syncthing/lib/events.(*Logger).Serve(0x11c76090)
	C:/BuildAgent/work/174e136266f8a219/lib/events/events.go:260 +0xde
created by github.com/syncthing/syncthing/lib/events.init.1
	C:/BuildAgent/work/174e136266f8a219/lib/events/events.go:234 +0x4e

goroutine 7 [chan receive]:
github.com/syncthing/notify.(*recursiveTree).dispatch(0x11c47140)
	C:/BuildAgent/work/pkg/mod/github.com/syncthing/notify@v0.0.0-20181107104724-4e389ea6c0d8/tree_recursive.go:125 +0xa7
created by github.com/syncthing/notify.newRecursiveTree
	C:/BuildAgent/work/pkg/mod/github.com/syncthing/notify@v0.0.0-20181107104724-4e389ea6c0d8/tree_recursive.go:119 +0x115

goroutine 9 [sleep]:
runtime.goparkunlock(...)
	C:/Go/src/runtime/proc.go:307
time.Sleep(0x1dcd6500, 0x0)
	C:/Go/src/runtime/time.go:105 +0x15b
github.com/syncthing/syncthing/lib/dialer.init.0.func2()
	C:/BuildAgent/work/174e136266f8a219/lib/dialer/internal.go:55 +0x2d
created by github.com/syncthing/syncthing/lib/dialer.init.0
	C:/BuildAgent/work/174e136266f8a219/lib/dialer/internal.go:54 +0x1ff

goroutine 12 [syscall]:
os/signal.signal_recv(0x453226)
	C:/Go/src/runtime/sigqueue.go:139 +0x12f
os/signal.loop()
	C:/Go/src/os/signal/signal_unix.go:23 +0x1a
created by os/signal.init.0
	C:/Go/src/os/signal/signal_unix.go:29 +0x37

goroutine 13 [chan receive]:
main.setupSignalHandling.func1(0x11c46fc0)
	C:/BuildAgent/work/174e136266f8a219/cmd/syncthing/main.go:881 +0x29
created by main.setupSignalHandling
	C:/BuildAgent/work/174e136266f8a219/cmd/syncthing/main.go:880 +0x9f

goroutine 14 [chan receive]:
main.setupSignalHandling.func2(0x11c47000)
	C:/BuildAgent/work/174e136266f8a219/cmd/syncthing/main.go:891 +0x29
created by main.setupSignalHandling
	C:/BuildAgent/work/174e136266f8a219/cmd/syncthing/main.go:890 +0x149

goroutine 15 [select]:
github.com/thejerf/suture.(*Supervisor).Serve(0x11ca2000)
	C:/BuildAgent/work/pkg/mod/github.com/thejerf/suture@v3.0.2+incompatible/supervisor.go:454 +0x2d9
created by github.com/thejerf/suture.(*Supervisor).ServeBackground
	C:/BuildAgent/work/pkg/mod/github.com/thejerf/suture@v3.0.2+incompatible/supervisor.go:407 +0x33

goroutine 16 [chan receive]:
github.com/syncthing/syncthing/lib/events.(*bufferedSubscription).pollingLoop(0x11c8c420)
	C:/BuildAgent/work/174e136266f8a219/lib/events/events.go:441 +0x56
created by github.com/syncthing/syncthing/lib/events.NewBufferedSubscription
	C:/BuildAgent/work/174e136266f8a219/lib/events/events.go:436 +0x125

goroutine 50 [chan receive]:
github.com/syncthing/syncthing/lib/events.(*bufferedSubscription).pollingLoop(0x11c8c480)
	C:/BuildAgent/work/174e136266f8a219/lib/events/events.go:441 +0x56
created by github.com/syncthing/syncthing/lib/events.NewBufferedSubscription
	C:/BuildAgent/work/174e136266f8a219/lib/events/events.go:436 +0x125

**Comment by calmh** [comment]
Windows XP is unfortunately not supported. You can stay on an older release or try to build yourself with an older Go.

**Comment by Rakasa** [comment]
I have the same failure, but not on XP; my failing host is 32 bit Windows Home Server (I believe Windows Server 2003 base for its core)

Same answer, or expected to work on mine?

~ Rakasa

**Comment by AudriusButkevicius** [comment]
Minimum versions described in:
https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-getfileinformationbyhandleex#requirements

**Comment by Rakasa** [comment]
This is listed on that page "Windows SDK on Windows Server 2003 and Windows XP" 

does that mean I can install something to add that function on the existing platform?

~ Rakasa

**Comment by Rakasa** [comment]
... looks like yes, if I can find the SDK, which does not appear to be available for download in general anymore...  time to hit MSDN archives

~ Rakasa

**Comment by devisbal** [comment]
Still there is for Windows Server 2003, not sure it can be used for Windows XP:
https://www.microsoft.com/en-us/download/details.aspx?id=15656
https://www.microsoft.com/en-us/download/details.aspx?id=12261
https://www.microsoft.com/en-us/download/details.aspx?id=6510

**Comment by Rakasa** [comment]
It is probably the same SDK under different header pages, I've seen Microsoft do that a lot.

Attempting the install now on my Windows Home Server

~ Rakasa

**Comment by AudriusButkevicius** [comment]
I think this is a lost cause, sure, you might fix this, but I suspect the next thing will crop up, and you'll be wasting your time again, scrambling for some patch. 

Your effort would be better spent upgrading from the 18 year old OS.

**Comment by devisbal** [comment]
From: Windows SDK and emulator archive
https://developer.microsoft.com/en-us/windows/downloads/sdk-archive

Released in June 2010, this SDK can be used to develop applications for Windows 7, Windows XP, Windows Server 2003, Windows Vista, Windows Server 2008, and .NET Framework versions 2.0, 3.0, 3.5 SP1, and 4.0.

Supported Operating System
Windows 7, Windows Server 2003 R2 Standard Edition (32-bit x86), Windows Server 2003 R2 Standard x64 Edition , Windows Server 2008, Windows Server 2008 R2, Windows Vista, Windows XP Service Pack 3
https://www.microsoft.com/en-us/download/details.aspx?id=8279
https://www.microsoft.com/en-us/download/details.aspx?id=8442

**Comment by Rakasa** [comment]
Philosophically, I agree; however, my finances currently do not allow me to.  If they did, I would not still be using the hardware this host is on.

~ Rakasa

**Comment by devisbal** [comment]
@AudriusButkevicius : Well .. We do have 100 Windows XP with an old specific program that is not supported on newer Windows Versions, and that still are doing what it's required to do.  We added syncthing for those and we can keep those on 1.0.1, but as always looking for improvements,
Those do not have auto-update, but I'm wondering that those that do have auto update active will suffer. There should be something to be done with the auto-update server to avoid this happening when there is an stop on supporting some OS.

**Comment by AudriusButkevicius** [comment]
It's not us who decided to stop support the OS, it's Microsoft themslves, and now Go people.
I don't think we should do anything for people who sit on a deprecated OS, and however evil that might sound, I am actually happy that things are breaking, which perhaps will be a wakeup call to some.

**Comment by AnthonyPrepress** [comment]
Same trouble on Win Server 2003 R2 SP2 (can't switch to higher version).
Downloaded Syncthing 1.1.0 RC2 -- it works, but trying to automaticaly update (and Panic), so I put wrong address in Advanced, Options, Releases URL, then Save and Restart.

**Comment by otbutz** [comment]
@Rakasa why don't you switch to Linux?

**Comment by AnthonyPrepress** [comment]
Linux doesn't support old RIP and old hardware :)

**Comment by Rakasa** [comment]
I have no way I know of to install Linux on the current hardware, and can't afford to replace the hardware.  It is a headless server, to the extent that there is not even a video port to connect a monitor to.  Everything except plugging in power and network is remote.

If I could afford to replace the hardware, I would have done so already, and probably be running Linux on the new hardware.  Ironically, the main reason I use syncthing on this chassis is to replicate the data to someplace I can back up.

~ Rakasa

**Comment by calmh** [comment]
I'm sure those still running XP have good reasons, including just "because I like XP". Windows XP support was deprecated in Go 1.11 (aug 2018), however things continued to mostly work, apparently. Now we are building with Go 1.12 and things don't. Options for XP people include:

- Remain forever on our 1.0.1 binary which works.
- Compile newer Syncthing yourself with older Go (this will work up to a point).
- Migrate to a different OS (Windows or otherwise).

These are all reasonable choices. What will not happen is for us to revert from using Go 1.12 and thus release working-on-XP binaries again.
