### ISSUE TITLE
Avoid anti-aliasing artifacts for svg device icons

### ISSUE THREAD

**Issue by fdietze** [syncthing/syncthing#5579]
In many icons lines between the squares are visible. These are anti-aliasing artifacts and can be avoided with:
```html
<svg shape-rendering="optimizeSpeed">
```
(https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering)

### Version Information

Syncthing Version: v0.14.50
Browser Version: Chrome

**Comment by calmh** [comment]
It sounds from that page like crispEdges or geometricPrecision might be closer to what we really want. (We don't actually care about the rendering speed.)
