### ISSUE TITLE
Configuration option "autoAcceptFolders" for devices isn't documented

### ISSUE THREAD

**Issue by dhs-rec** [syncthing/syncthing#5580]
Reading the configuration via REST API call (and also in the UI), I see in the output that each device has an "autoAcceptFolders" option, set to false. However, I couldn't find it in the documentation.

So what exactly happens if I set this to true?
- Where are automatically accepted folders stored?
- What are their names?

### Version Information

Syncthing Version: v1.0.1, v1.1.0

**Comment by AudriusButkevicius** [comment]
Use the docs repo.
