### ISSUE TITLE
White tab in black Interface ?

### ISSUE THREAD

**Issue by borrougagnou** [syncthing/syncthing#5583]
Hi !
I don't know if it's a normal or not:

White tab color in Dark and Black theme (see screen below)

thx for your work ! this app is very helpfull for a lots of thing !

### Version Information

Syncthing Version: v1.1.0
All version, all browser

![image](https://user-images.githubusercontent.com/10796546/54004713-e9fa5200-4156-11e9-8c5b-ad94f0c0f79c.png)

**Comment by calmh** [comment]
Looks like the black theme needs an update.

**Comment by blackfoxsar** [comment]
<img width="447" alt="スクリーンショット 2019-05-15 14 40 32" src="https://user-images.githubusercontent.com/15705262/57751252-0cdd4f80-7720-11e9-9ab5-74c71b406447.png">

me too, and not changed at v1.1.3

### Version Information

Syncthing Version: v1.1.3
Browser Version: <All Browser>
