### ISSUE TITLE
Hello - Syncthing has been working fine for months on my Windows XP installed as a guest (with the host being Linux Mint), using KVM (kernel based virtual machine).  I have 7 computers set up this way for my business.  Suddenly, Syncthing will start, and within a few seconds, stop.  I've tried to capture a couple error messages, which include:

### ISSUE THREAD

**Issue by charlesnewland** [syncthing/syncthing#5589]
Hello - Syncthing has been working fine for months on my Windows XP installed as a guest (with the host being Linux Mint), using KVM (kernel based virtual machine).  I have 7 computers set up this way for my business.  Suddenly, Syncthing will start, and within a few seconds, stop.  I've tried to capture a couple error messages, which include:

syncthing failed to find GetFileInformationByHandleEx procedure in kernel132.dll
syncthing exited: exit status 2

Can anyone help?
Thank you,
Charles

_Originally posted by @charlesnewland in https://github.com/syncthing/syncthing/issues/5588#issuecomment-471248384_

**Comment by charlesnewland** [comment]
The current version of Syncthing I had been using is v1.0.1.  This issue occurs when a forced upgrade (not optional) moves it to version 1.1.0.  As soon as the upgrade happens, Syncthing stops running.

**Comment by imsodin** [comment]
Use the forum for support and see my previous comment on your own issue #5588 for a duplicate issue/relevant forum thread. Stop spamming the issue tracker.
