### ISSUE TITLE
Does not exit on GUI shell logout

### ISSUE THREAD

**Issue by justpusher** [syncthing/syncthing#5590]
When syncthing is run on GUI shell startup, it does not exit on shell logout. 
If syncthing is run by Syncthing-GTK, Syncthing-GTK exits on shell logout but syncthing doesn't. 
Syncthing does not react on SIGHUP - I think this is a possible reason. 

### Version Information
syncthing v1.1.0 "Erbium Earthworm" (go1.12 linux-amd64) deb@build.syncthing.net 2019-02-25 18:25:08 UTC
OS Version: Ubuntu 16.04.5 LTS, XFCE version 4.12

**Comment by AudriusButkevicius** [comment]
Wrong repo, syncthing-gtk is a separate repo

**Comment by AudriusButkevicius** [comment]
I gues this could be syncthing, but not sure, why would syncthing have to react to SIGHUP?

**Comment by imsodin** [comment]
Both the monitor process (without `-no-restart`) as well as the main process have some signal handling and Syncthing reacts to SIGHUP by restarting, which according to wikipedia is a common thing to do for daemons. If you think there's a good reason to handle it otherwise, please open a discussion on the forum about it.

**Comment by justpusher** [comment]
This is indeed a syncthing issue. 

I mentioned syncthing-gtk just as additional information. 
The issue occurs even syncthing-gtk is not used. 

syncthing does not exit on logout if it was started by GUI shell. 
I've just tested in clean Ubuntu with Gnome 3, syncthing does not exit on logout. 

SIGHUP was just a suggestion. I don't know how exactly GUI shell notifies processes on logout. 

I'd like syncthing to exit on logout. The reason is security: I don't want my crypted home to remain mounted.
