### ISSUE TITLE
Default folder in v1.1.0 isn’t created with useLargeBlocks = true 

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing#5599]
https://forum.syncthing.net/t/default-folder-in-v1-1-0-isnt-created-with-uselargeblocks-true/13003

**Comment by calmh** [comment]
The forum post talks about folder default values. These do historically live in the Javascript in the UI. None are applied at the API level. The same goes for auto normalization, minimum free space, etc. I'm skeptical that this is an issue or, if it is, then it's a more general issue.

**Comment by calmh** [comment]
I may have misunderstood what the issue was about.
