### ISSUE TITLE
Watcher not working properly on Windows 10

### ISSUE THREAD

**Issue by mhbates** [syncthing/syncthing#5602]
### Please do post actual bug reports and feature requests.

Using Syncthing v1.1.0 via SyncTrayzor v1.1.22 on Windows 10, with Syncthing's file watcher. I created several txt files, spread around, with varying file sizes, some 0kb, some 100kb, etc. They are not detected by the watcher. Over time I went in and modified the files, but still no detection. I deleted some of them, also not detected by the watcher. This is over the course of 30 minutes. Folder changes are detected immediately.

Is this normal behavior? It would be bad if I created or changed a file, shut down the computer two minutes later, and the changed file is not synced. Please advise.

### Version Information

Syncthing Version: v1.1.0
SyncTrayzor Version: v1.1.22
OS Version: Windows 10

**Comment by mhbates** [comment]
Quick update. It seems this is fixed by restarting SyncTrayzor. Based on that, the bug may be that Syncthing/SyncTrayzor requires a restart after initial installation/setup/linking on Windows 10.

**Comment by calmh** [comment]
Might also be #5578 if you're watching to root of a drive. I don't *think* SyncTrayzor does the watching. Regardless, if you find a reproducer please let us know.
