### ISSUE TITLE
syncthing does not work as automatic start in the centos6

### ISSUE THREAD

**Issue by cool-delete** [syncthing/syncthing#5604]
When I used syncthing as automatic start in the centos6....with `chkconfig --add syncthing  `

after reboot syncthing does not work

I can't see "syncthing" in the list given by the  `ps -aux` command. or can't visit ip:8384

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by cool-delete** [comment]
![$H%_FEFK@(Q_HXLLFPC2PR6](https://user-images.githubusercontent.com/13638610/54623299-35d9bf00-4aa6-11e9-893b-d8f648b12666.jpg)
