### ISSUE TITLE
Crosscompiling fails : fork/exec exec format error

### ISSUE THREAD

**Issue by zyxmon** [syncthing/syncthing#5606]
I am trying to crosscompile syncthing 1.1.0 for Entware project - https://github.com/Entware/Entware

The command used to build is

```
PATH="/media/ware4/Entware.2018.02/staging_dir/host/go/bin:$PATH"  \
GOPATH=/media/ware4/Entware.2018.02/build_dir/target-arm_cortex-a9_glibc-2.23_eabi/syncthing-hf/syncthing-1.1.0 \
GOARM=7 go run build.go -goos linux -goarch arm -version v1.1.0 -no-upgrade

```

It fails with (last output lines)
```
fork/exec /media/ware4/Entware.2018.02/tmp/go-build002760824/b001/meta.test: exec format error
FAIL	github.com/syncthing/syncthing/meta	0.002s
exit status 1

```
What is wrong? Are there instructions for crosscompiling syncthing?
PS Building version 0.14.54 had no errors.

**Comment by zyxmon** [comment]
I have removed GOPATH assignment - it is not needed now. My go version is 1.12.
Now building ends with
```
....
gopkg.in/ldap.v2
github.com/syncthing/syncthing/cmd/uraggregate
github.com/syncthing/syncthing/cmd/ursrv
github.com/syncthing/syncthing/cmd/syncthing
fork/exec /media/ware4/Entware.2018.02/tmp/go-build267253210/b001/meta.test: exec format error
FAIL	github.com/syncthing/syncthing/meta	0.002s
exit status 1

```

**Comment by zyxmon** [comment]
I have "disabled meta in build.go" with a patch and now syncthing builds OK. But this does not look as a correct solution.

**Comment by calmh** [comment]
Add a "build" at the end of the command line.

`go run build.go -goos linux ... build`

The build script with no command (just -args) will by default do a couple of quick lint tests etc which won't work when cross compiling. This is documented here: https://docs.syncthing.net/dev/building.html

**Comment by zyxmon** [comment]
Thanks!
