### ISSUE TITLE
.stignore rules are ignored/buggy for existing/synced files

### ISSUE THREAD

**Issue by pascalfree** [syncthing/syncthing#561]
Hi,

I have 2 nodes:
1. v0.9.8 on linux armv5
2. v0.9.5 on android (syncthing for android 0.4.8)

I synced the camera folder from my android device to the linux box (setting the "master repo" on android). Then I realized, that the two folders `cache` and `thumbnails` had been synced as well and wanted to remove those off the linux box while keeping them on android. So I created a `.stignore` on both nodes (just to be sure) like this:

```
cache
thumbnails
```

However the folders (+contents) where not ignored by syncthing (file count did not decrease on either node). I went on deleting the folders on the Linux box. This resulted in the conflict showing up on the android device: It wants to delete the folders but can't, because it has the master repo. When using "Override Changes", the folders will be resynced (despite the rule in `.stignore`).

The problem seems to be, that `.stignore` rules are ignored, if they where created after the respective files have been created/synced, i.e. when the file already has been scanned.

I reproduced the problem the other way around (linux box has the master repo). In general:
1. Set up a repo synced between node A and B.
2. (optional) Enable the option "Master Repo" on A
3. Create a file on A. e.g. `testfile.txt`. Let it sync to B
4. Create `.stignore` on A containing `testfile.txt`

**Expected**: The file count in syncthing will be reduced (on the local repo with the .stignore file) and deleting the file on one node will have no effect on the other node.
**Actual**: No change in file count and deleting the file on B will delete the file on A (or leave a conflict if A has the master repo). And deleting the file on A will also delete it on B.

Additionally, I tried editing the file `testfile.txt` after the procedure described above.
When editing it on A, nothing is synced. I assume this is the `.stignore` working correctly.
When editing on B, the changes will be synced back to A. This also seems correct from the way `.stignore` works but may not be expected by the user, i.e.: "I told it to ignore the file, why is it still changing?"

So the question finally is: How to remove a file from the repo that has already been scanned by syncthing (without actually deleting it)?

btw: I'm very excited about syncthing and totally looking forward to use it for automated backups once it's stable. Thanks for making this and for making it open source.

**Comment by daviddelikat** [comment]
I think the best solution would include tracking the items that this client ignores, likely just filename and size.  I prefer a simple total ignorance feature where this instance ignores any file local or remote which matches the patterns in .stignore.  Perhaps syncthing needs to have an 'alarm protocol' where it creates status files near files that are causing issues.  For instance a file called junk.doc could cause junk.doc.ST_status when there is an issue...  the file would contain some diagnostic info.  the user can see that there is a problem and deal with it.
