### ISSUE TITLE
commands take a long time

### ISSUE THREAD

**Issue by sedlund** [syncthing/syncthing#5624]
running simple info commands takes a long time.

root@openwrt:/mnt/bin/syncthing-linux-mips-v1.1.1-rc.2# time ./syncthing --version
syncthing v1.1.1-rc.2 "Erbium Earthworm" (go1.12.1 linux-mips) teamcity@build.syncthing.net 2019-03-25 11:43:21 UTC
real    0m **31.01s**
user    0m 12.05s
sys     0m 2.68s

root@openwrt:/mnt/bin/syncthing-linux-mips-v1.1.1-rc.2# time ./syncthing --help > /dev/null
real    0m **27.99s**
user    0m 11.92s
sys     0m 3.02s

---

compare with other go cli apps that use spf13/cobra

root@openwrt:/mnt/bin# time ./caddy -version
Caddy (untracked dev build) (unofficial)
real    0m 0.26s
user    0m 0.10s
sys     0m 0.06s

root@openwrt:/mnt/bin# time ./rclone version
rclone v1.46
- os/arch: linux/mips
- go version: go1.11.5
real    0m 0.46s
user    0m 0.21s
sys     0m 0.09s

root@openwrt:/mnt/bin# time ./rclone --help >/dev/null
real    0m 0.79s
user    0m 0.33s
sys     0m 0.06s

**Comment by calmh** [comment]
Interesting. See you can use strace or similar to figure out what's going on during that time. (Obviously, this doesn't happen for me on computers I have access to, but they're not mips.)

**Comment by sedlund** [comment]
[strace-syncthing-version.txt](https://github.com/syncthing/syncthing/files/3012803/strace-syncthing-version.txt)

hope this helps

**Comment by calmh** [comment]
Can't say that it does. Maybe you can narrow it down by commenting out init() functions or such to narrow it down, I unfortunately have no idea.

**Comment by sedlund** [comment]
I'm not sure its mips related.  It's markedly slower than other apps on a RaspberryPi as well:

pi@raspberrypi:~/Downloads $ time rclone version
rclone v1.46
- os/arch: linux/arm
- go version: go1.11.5

real    0m0.110s
user    0m0.094s
sys     0m0.017s

pi@raspberrypi:~/Downloads $ time ./syncthing-linux-arm-v1.1.1-rc.2/syncthing --version
syncthing v1.1.1-rc.2 "Erbium Earthworm" (go1.12.1 linux-arm) teamcity@build.syncthing.net 2019-03-25 11:43:21 UTC

real    0m1.773s
user    0m1.816s
sys     0m0.051s

pi@raspberrypi:~/Downloads $ time ./syncthing-linux-arm-v1.1.1-rc.2/syncthing --help >/dev/null

real    0m1.779s
user    0m1.769s
sys     0m0.081s
pi@raspberrypi:~/Downloads $ time rclone --help >/dev/null

real    0m0.114s
user    0m0.095s
sys     0m0.022s

 I think the single slow core of the mips makes it more pronounced

**Comment by calmh** [comment]
One thing that happens at init time is that we calculate sha256 sums of the zero blocks. Is that mips thing slow to the tune of 1 MB/s hashing perf? If so it would make sense. Quick check to see if that's the thing: comment out this line and compile: https://github.com/syncthing/syncthing/blob/0cff66fcbc9dea1f0409b4585eb77deba9d8c2f3/lib/protocol/protocol.go#L49

We could hardcode those values instead.

**Comment by sedlund** [comment]
Very nice:

root@openwrt:/mnt/bin# time ./syncthing --version
syncthing v1.1.1-rc.2+15-gfb906f37-dirty "Erbium Earthworm" (go1.12 linux-mips) sedlund@cs-6000-devshell-vm-66668f1a-425b-4dd9-990b-16ee9a59d035 2019-03-27 14:11:36 UTC

real    0m0.211s
user    0m0.150s
sys     0m0.050s

Thanks for your help!
