### ISSUE TITLE
Stalled scans need better UI representation

### ISSUE THREAD

**Issue by nekr0z** [syncthing/syncthing#5627]
Currently, a stalled scan keeps increasing Remaining Time on a folder, which leads to ridiculous amounts displayed: 
![](https://forum.syncthing.net/uploads/default/original/2X/6/68838752b28fcacea5a922f154f93fe6d9f84471.png)

Should be `Unknown (stalled)` instead.

Also, for scans not completely stalled but really too slow `> 1 year` should suffice. Suggested in [this forum thread](https://forum.syncthing.net/t/remaining-time-ui/13086/5).

**Comment by uok** [comment]
or maybe display "∞" if more than 1 year

**Comment by nekr0z** [comment]
> or maybe display "∞" if more than 1 year

That would technically be inaccurate (although admittedly not to the point of user misunderstanding).

**Comment by nekr0z** [comment]
I'm finally giving this one a shot, but I'm a little confused as to how slow is effectively "stalled". The scanning rate is currently internally calculated in B/s and never actually reaches 0, but how slow is too slow? 10 B/s? 1 B/s? 0.1 B/s?

**Comment by Ferroin** [comment]
I think what matters here is not so much the exact speed, but how long the scan is expected to take proportionate to how long it normally takes.

If we can track (somehow) how long it takes on average to scan the folder, then I'd say that anything less than 1% of that normal value is stalled.  For the case of a 'new' scan (that is, we don't have enough data to say what normal scan speed is), probably list it as stalled if scan speed is less than 10 B/s.

If that's not a possibility, I think just defaulting to 10 B/s and letting the user set a threshold through the config is probably the best option.

**Comment by nekr0z** [comment]
> If that's not a possibility, I think just defaulting to 10 B/s and letting the user set a threshold through the config is probably the best option

We don't store previous scan times, and I doubt it's worth it. As for user-defined thresholds, that's a nice touch, but seeing as how this only affects GUI, and we currently don't have any GUI-specific settings, I'm reluctant to even introduce the whole concept of it for such a minor case.

What I think I'll be doing is make it show '> 1 year' for lengthy scans, and in case it's > 1 year AND slower than 10 B/s, 'Unknown (stalled)', that should do it.

**Comment by AudriusButkevicius** [comment]
Do we really need to clearly identify stalled? The problem is that scan is slow and the large number is ugly, I think if we go past 30 days, we just say "> 1 month" and thats it. Do we really need the term stalled?
