### ISSUE TITLE
Panic Log

### ISSUE THREAD

**Issue by Smyrski** [syncthing/syncthing#5628]
I setup my laptop with syncthing and was trying to setup the folders to sync between them, they started to sync but then the instance running on my desktop started to constantly restart. I had it running in the background so I started it again and just ran it in console with `syncthing` and I saw a panic. The panic file is 9000 lines long, but the panic was caused by "slice bounds out of range."

[panic-20190329-013757.log](https://github.com/syncthing/syncthing/files/3021335/panic-20190329-013757.log)

### Version Information

Syncthing Version: v0.14.43-ds1
OS Version: Ubuntu 18.04
Browser Version: N/A

**Comment by calmh** [comment]
You're running a very old version; please upgrade. (Yes, I realize this is just what Debian packages; you can grab newer versions from https://apt.syncthing.net/ directly.)
