### ISSUE TITLE
Corrupted files

### ISSUE THREAD

**Issue by dhaavi** [syncthing/syncthing#5629]
I know this will be a pretty vague bug report, but I still wanted to file it, because this makes me want to move away from Syncthing, but I really like it.

I run Syncthing on about a dozen devices and move a lot of important data around. A couple weeks ago I noticed a PDF file that I created two years ago. It was corrupted.

Then I noticed another corrupt PDF file this week on _another device_ in _another folder_ shared by _another group of devices_. This file was only 1-2 months old.

With this second occurrence of a corrupted file in a seemingly unrelated environment I became suspicious.

In both cases, the files were much smaller than they should be - as if only a small first part of the file was present, and the rest missing.

I, of course, cannot reproduce the problem, as I also don't know when it occurred.
The second time this happened, there luckily was a sync-conflict file of the file in question that was OK.

As far as I understand, Syncthing writes files to a temporary location and then moves the file into place when finished. And as these files have been in the repo for some time and were perfectly fine, I wonder how this could have happened.

I am sorry that I can't be more specific about this, as this is all the information I have.

What worries me, is that there could be more corrupted files - but I don't know how to even efficiently find them, as I don't want to go through all my files and try to open them.

I'd really love to have Syncthing with integrity checks, sadly this feature request (#1315) has already been denied.

### Version Information

Syncthing v0.14.51, Linux (first occurrence)  
and  
Syncthing v0.14.51, MacOS (second occurrence)

**Comment by AudriusButkevicius** [comment]
There is nothing actionable here, it's not clear where the bug is, how to reproduce it, or what needs fixing, hence closing, I suggest you pursue help on the forums, and at a point there is something actionable, we can open a issue on github.

**Comment by dhaavi** [comment]
Posted on forum: https://forum.syncthing.net/t/corrupted-files/13096
