### ISSUE TITLE
Syncthing crashes multiple times and exits when scanning a specific folder

### ISSUE THREAD

**Issue by guismoale** [syncthing/syncthing#5630]
syncthing v0.14.43-ds1 "Dysprosium Dragonfly" (go1.9.3 linux-amd64) debian@debian 2018-02-06 04:01:09 UTC [noupgrade]
OS Version: Ubuntu mate 18.04.2

What happen: Syncthing crashes multiple times and exit while trying to sync a folder.
The folder have many files started on windows, synced with a main ubuntu 18.10 computer and then this problem is happening on the 18.04.2 ubuntu mate computer. I can't figure out what file is giving me the problems and I have no idea reading the log.

Since it's crashing syncthing, nothing gets synced. I have to delete the folder and restart. But if it starts syncthing again at some point is stops working again.

I'm attaching the log.

[panic-20190330-090937.log](https://github.com/syncthing/syncthing/files/3024717/panic-20190330-090937.log)

**Comment by AudriusButkevicius** [comment]
support happens on the forums

**Comment by AudriusButkevicius** [comment]
actually, looking for existing closed issues would have answered your question, so I suggest you start there.
