### ISSUE TITLE
Dockerfile ENTRYPOINT doesn't pass along extra arguments from "docker run"

### ISSUE THREAD

**Issue by tomjakubowski** [syncthing/syncthing#5631]
When I'm running syncthing from the Docker image, I would often like to pass it additional command line arguments. My expectation, based on other "application" images I've used (pdal is one example), is that extra arguments to `docker run` would be passed on to `syncthing` in the container.

To reproduce:

```
docker run --pull syncthing/syncthing -help
```

Expected behavior: help text is printed, as with `syncthing -help`.

Actual behavior: `syncthing` starts like nothing was passed:

```
% docker run syncthing/syncthing -help
[monitor] 01:23:27 INFO: Starting syncthing
[start] 01:23:27 INFO: Generating ECDSA key and certificate for syncthing...
[BRLLT] 01:23:27 INFO: syncthing v1.1.0 "Erbium Earthworm" (go1.11.6 linux-amd64) docker@syncthing.net 2019-02-25 18:25:08 UTC
[BRLLT] 01:23:27 INFO: My ID: BRLLTIP-EZSBBHZ-OZJLDQH-SPQWQGD-VT7UQWK-MFFNRSM-5G72AVM-XOEXYA7
[BRLLT] 01:23:28 INFO: Single thread SHA256 performance is 380 MB/s using crypto/sha256 (377 MB/s using minio/sha256-simd).
[... truncated]
```

Docker image version: 61de83be0df4

- - -

I believe this can be addressed through some combination of using the _exec form_ of `ENTRYPOINT` and, optionally, `CMD` for "default" arguments that would be thrown away if the user provides any. See https://docs.docker.com/engine/reference/builder/#entrypoint

**Comment by calmh** [comment]
We do some chowning and stuff in the entrypoint so I think the easiest way to make this work correctly is have a small wrapper script that does its thing and then exec:s syncthing, along with any optional arguments.

**Comment by tomjakubowski** [comment]
Pull request submitted here: https://github.com/syncthing/syncthing/pull/5635
