### ISSUE TITLE
Local and global states are different but are the same in all nodes

### ISSUE THREAD

**Issue by entonio** [syncthing/syncthing#5632]
I'm sorry for bringing back an issue that seems to be repeatedly opened and closed.

Background:
- I have shared a folder among a handful of computers (some macOS, some Windows).
- From the beginning, I have set up a shared ignore file. Every node has an equal .stignore, that does nothing except including the shared file.
- At some point, all folders were in sync and global and local values were the same.

Question 1:
- With all the ignored files, shouldn't global and local be different?

Then:
- I have deleted a number of folders and files (some 5000 in a total of 18000). All were deleted everywhere, as expected.
- The local state is now about 13000, identical in in all nodes.
- The global state is now about 13100, identical in in all nodes, but different from the local state by a small difference (100 files, much less that those that were deleted).

Question 2:
- Given that, at the time of question 1, global and local were the same, shouldn't they remain the same?

I understand that the expected behaviour is either that of question 1 or of question 2, so only one of them really needs an answer.

It would be most helpful if there were some way I could see what are the different files between global and local, is there some database query for that?

I've tried to set one of the nodes as 'Send only' in order to use 'Override Changes', but it doesn't show any changes, so no button to override either.

All my nodes look like this:
![state](https://user-images.githubusercontent.com/5048472/55339499-b4693000-549a-11e9-893b-230aa5d71758.png)

**Comment by AudriusButkevicius** [comment]
Questions go on the forum.

**Comment by entonio** [comment]
- 1 is inconsistent with 2. That's an issue, not a question. If it's normal behaviour, then the documentation should illustrate it.
- I found no way to tell what's responsible for the difference. That's either a UX or documentation issue.
- There are similar questions on the forum and never a conclusive answer. Once it was a an issue that ended up being corrected, another time the user just ended up rebuilding everything, yet another time the issue went away by itself.

**Comment by AudriusButkevicius** [comment]
The answer is as usual "It depends". Over different versions the classification of what went into the database and what didn't changed. Also, the way ignores are handled has changed over time as well, which is most likely what lead to inconsistencies.

If you want to have a meaningful discussion about this, it should happen on the forum.

**Comment by entonio** [comment]
OK, I understand.
(Just for completeness I should, however, point out that this is a new install (1.1.0) on every node.)
