### ISSUE TITLE
Windows: Crash at 6th restart via REST if time between restarts < 15 seconds

### ISSUE THREAD

**Issue by dhs-rec** [syncthing/syncthing#5634]
I've written a Puppet class for configuring SyncThing. When adding multiple devices/folders, the config is posted after each and a restart is issued. On Windows, doing the 6th config change (and thus issuing the 6th restart) reliably lets ST crash. If I add a delay of 15 seconds between two restarts, the problem disappears.

You can use the following Ruby code to reproduce the issue:
```
#!/usr/bin/env ruby

require 'rest'

rest    = Rest::Client.new()
headers = {
  'Content-Type' => 'application/json',
  'X-API-Key' => 'YOUR API KEY HERE'
}

baseURL = 'http://HOSTNAME:8384/rest/system'
delay = 5 # Change to 15 to avoid the crash
begin
  sleep(delay) # make sure it has run at least delay seconds before first restart
  count = 1
  while true
    puts 'Restart number ' + count.to_s
    res = rest.post(baseURL + '/restart', :body => {}, :headers => headers)
    puts res.code
    puts res.body
    sleep(delay)
    count += 1
  end
rescue Rest::HttpError => he
  puts he.message
end
```

### Version Information

Syncthing Version: v1.1.x
OS Version: Windows

**Comment by calmh** [comment]
Logs on the crash?

By default Syncthing runs with a monitor process that manages restarts. It gives up with an error if there are continuous rapid restarts. This might be what you're seeing. If so, run without the monitor process or do less rapid restarts.

**Comment by AudriusButkevicius** [comment]
This should be a question on the forum as I believe OP is doing something wrong. Furthermore, restarts are no longer needed when adding folders or devices.

**Comment by dhs-rec** [comment]
Thanks for clarifying. However, the REST API docs say something different.

**Comment by AudriusButkevicius** [comment]
They are just outdated.
