### ISSUE TITLE
File Versions date picker obscured and non-functional

### ISSUE THREAD

**Issue by phuckstepp** [syncthing/syncthing#5637]
Just installed SyncThing and I've been playing around with the File Versioning feature. I have found though on Windows in any browser I try the date picker is out the top of the browser display.

I temporarily fixed this by adding top:200px in the dev console to move it down. I then discovered that the date picker doesn't work at all and is stuck on 1969 and 1970! It is also not possible to just change the values in the text field as those are reset when the picker closes.

![figure-1](https://user-images.githubusercontent.com/25500388/55551784-87ec2880-56d3-11e9-8dce-2f813ce05980.png)

**Comment by AudriusButkevicius** [comment]
There is a ticket about this already, so dup of some ticket I am too lazy to find.
