### ISSUE TITLE
Building without git no longer works

### ISSUE THREAD

**Issue by swills** [syncthing/syncthing#5638]
The [docs on building](https://docs.syncthing.net/dev/building.html#building-without-git) say that you can build syncthing without git, but with "go mod" support this seems to no longer work:

```
# go run build.go -version v1.1.1 -no-upgrade tar                                                    
go: github.com/calmh/xdr@v1.1.0: git init --bare in /root/go/pkg/mod/cache/vcs/e485bff6bf20d8ff2e03b9eeb1bb343f7f88f22e6656b664efc1c73f07ab0abe: exec: "git": executable file not found in $PATH
```

Am I missing something or doing something wrong?

**Comment by calmh** [comment]
You might need to check with the Go team as that is the tool eroding out...  I suspect building in non-module mode or with `-mod=vendor` might work.

**Comment by swills** [comment]
Hmm, well, if i remove go.mod from the source, I get a different error:
```
# go run build.go -version v1.1.1 -no-upgrade tar
can't load package: package github.com/syncthing/syncthing/lib/auto: cannot find package "github.com/syncthing/syncthing/lib/auto" in any of:
        /usr/local/go/src/github.com/syncthing/syncthing/lib/auto (from $GOROOT)
        /root/go/src/github.com/syncthing/syncthing/lib/auto (from $GOPATH)
can't load package: package github.com/syncthing/syncthing/cmd/strelaypoolsrv/auto: cannot find package "github.com/syncthing/syncthing/cmd/strelaypoolsrv/auto" in any of:
        /usr/local/go/src/github.com/syncthing/syncthing/cmd/strelaypoolsrv/auto (from $GOROOT)
        /root/go/src/github.com/syncthing/syncthing/cmd/strelaypoolsrv/auto (from $GOPATH)
exit status 1
exit status 1
```

**Comment by calmh** [comment]
Yes, because then you need to actually be in a correct GOPATH.

I can confirm that `go build -mod=vendor ...` works, but the build script doesn't do that out of the box.

**Comment by swills** [comment]
Ok, thanks.

**Comment by calmh** [comment]
The following works for me and might for you too:

```
$ export GOFLAGS=-mod=vendor
$ go run build.go -version v1.1.1
```

That is, using modules mode exactly as in our build guide but with the additional environment var set because you want to use the modules vendored in the tar.gz

**Comment by swills** [comment]
Yep, that worked, thanks.

**Comment by calmh** [comment]
Sweet, I added a note to the build docs.
