### ISSUE TITLE
Add support for all_proxy on Windows

### ISSUE THREAD

**Issue by uperetz** [syncthing/syncthing#5640]
I am not 100%, but the `all_proxy` environment variable seems to  be ignored on Windows machine. I tested both as a user variable and a system variable.

The [help](https://docs.syncthing.net/users/proxying.html) uses Bash type syntax as well but it does not explicitly say Windows is not supported. 

If that's true, any chance it could be added? If not I will try and find the problem on my machine.

**Comment by calmh** [comment]
As far as I know it should be equally supported on Windows as anywhere else. However, setting environment variables is trickier on Windows.

**Comment by uperetz** [comment]
I set it normally (?), through `System Properties->Advanced->Environment Variables`.

Worth mentioning I get no info message in the log at all. If it is a bad configuration info, I would expect it to say something.

**Comment by calmh** [comment]
Yeah, I don't know about that, but it works in a command prompt:

<img width="934" alt="Screen Shot 2019-04-08 at 09 31 17" src="https://user-images.githubusercontent.com/125426/55706315-34ceea00-59e1-11e9-97ff-cd417603fbff.png">

I don't think there's any particular validation of the setting value itself though, beyond attempting to use it.

**Comment by Sigmun** [comment]
@calmh It looks like I still have an issue behind my proxy. As you can see, I don't have the same output (no mention of the use of proxy) and the host is not reachable by the others.
![Capture d’écran (3)](https://user-images.githubusercontent.com/396437/56962836-c13f7900-6b57-11e9-8274-cdd9e115d5ad.png)

Can you help me or reopen the issue ?

**Comment by calmh** [comment]
Please use the forum for help/support.

**Comment by AudriusButkevicius** [comment]
You are missing an equals, just setting two vars to empty value.

**Comment by canton7** [comment]
I don't think `set` works with env vars anyway
