### ISSUE TITLE
Add SEPA (IBAN & BIC) donation

### ISSUE THREAD

**Issue by beerisgood** [syncthing/syncthing#5647]
Using https://stripe.com isn't a option for me. They have very bad privacy!: https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fstripe.com

So if you can add SEPA, i would donate

**Comment by calmh** [comment]
I don't fully agree with that assessment of Stripe, at least not based on that report, but I see no harm in adding this extra method. Will do.

**Comment by beerisgood** [comment]
Why you don't agree with that report?

Anyway thanks for adding SEPA.
Is account name "Syncthing" okay for payment?

**Comment by beerisgood** [comment]
I totaly forget it, but today i wan't use SEPA for donation but sadly no IBAN and company name are listed on https://syncthing.net/

**Comment by calmh** [comment]
Correct. It may come back, but at the moment it's intentionally missing.
