### ISSUE TITLE
Enable TLS1.3 for for non-test builds

### ISSUE THREAD

**Issue by otbutz** [syncthing/syncthing#5653]
It's currently not enabled by default: https://github.com/syncthing/syncthing/blob/master/lib/tlsutil/tlsutil.go#L73-L76

**Comment by calmh** [comment]
We're not going to do this. I like new features as much as anyone else, but given that the Go project considers this to be testing level stability at the moment (requiring a debug environment variable to be set) we're not going to force enable it on stable builds. 

You can do so yourself though by setting `GODEBUG=tls13=1` before starting Syncthing.
