### ISSUE TITLE
undesired renames of folders when using auto-accept

### ISSUE THREAD

**Issue by lkwg82** [syncthing/syncthing#5656]
### Does your log mention database corruption?

no

### Please do post actual bug reports and feature requests.

From time to time the folders are reseted to the folder-id names, instead of the previous accepted labels.

I use a central server which auto-accepts from at least two different devices.

in the logs are multiple versions of
```
Failed to auto-accept folder "lars_private-share" (mvjac-usmh7) from XXX due to path conflict
```

 - folders are re-accepted with folder-id instead of labels
 - keep the folder labels as folder names
 - not yet

I already fixed this by renaming the folders in the config and on the system, but it happened again.

### Version Information

Syncthing Version: v1.1.1
OS Version: centos + ubuntu (quite latest)

Thx in advanced.

I guess it is related to auto-accept feature.

**Comment by imsodin** [comment]
What are you doing when that happens? This error can only come up, if the folder doesn't exist in the first place, so it shouldn't just happen again. In any case, please provide either logs (not just excerpts) or steps to reproduce.

**Comment by lkwg82** [comment]
I did once cleaned up the mess.

Maybe it happens after a restart.

I try to reproduce it.

**Comment by lkwg82** [comment]
How can I send logs confidentially?

**Comment by imsodin** [comment]
You could e.g. send them to me at freisim93@gmail.com or via PM in forum.syncthing.net.

**Comment by AudriusButkevicius** [comment]
This would not happen if you deleted the folder. As far as I am concerned this is working as intended, we don't want to blindly merge existing content of some folder with something that is being auto accepted.

**Comment by lkwg82** [comment]
I will try to create for all affected shares new ones.
