### ISSUE TITLE
Sometimes file renames cause a retransmit

### ISSUE THREAD

**Issue by jasom** [syncthing/syncthing#5660]
### What happened:

1. I renamed several dozen large files in a relatively short period of time (a minute or two)
2. Most of the files were synced with just a rehash, but a few were sent over the wire

### What I expected to happen

I expected all files to be properly synced after a rehash without the files being sent over the network

### Steps to reproduce:

I have not yet intentionally reproduced this on purpose

### Other notes

Looking at my current list of out-of-date items right now, if this list is in order for when the files will be synced, most items show the new file name being added before the old file name is being deleted, but some do not; again, if this list is in-order of syncing, it makes sense that the files are resent

### Version Information

Syncthing Version: v1.1.0, Linux (64 bit)
OS Version: Gentoo Linux
Browser Version: (Probably N/A, but firefox 66.0.3)

**Comment by AudriusButkevicius** [comment]
This is a tradeoff between transmitting changes as fast as we notice them versus delaying to discover renames, so this is expected for large number of files being moved around.

**Comment by madduck** [comment]
This seems to be an issue even if single files are renamed: the entire file contents needs to be retransferred. Due to #5978, this just forced me to retransfer 760Gb…
