### ISSUE TITLE
Connection Error from fresh install on Ubuntu 18.04

### ISSUE THREAD

**Issue by SeanDHeath** [syncthing/syncthing#5661]
Syncthing Version:
```
> syncthing --version
syncthing v0.14.43-ds1 "Dysprosium Dragonfly" (go1.9.3 linux-amd64) debian@debian 2018-02-06 04:01:09 UTC [noupgrade]
```
OS Version:
```
> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```
Browser Version:
![image](https://user-images.githubusercontent.com/6528011/56390791-d7197980-61fa-11e9-90c5-7aad7ded7a8c.png)

I installed Syncthing from the default repos:
```
syncthing/bionic,now 0.14.43+ds1-6 amd64 [installed]
  decentralized file synchronization
```

Set up the GUI for remote https access:
```
    <gui enabled="true" tls="true" debugging="false">
        <address>0.0.0.0:8384</address>
```

Started syncing files but within 30s of logging in to the web GUI started getting this error message almost immediately (~10s) after refreshing the page:
```
Connection Error
Syncthing seems to be experiencing a problem processing your request. Please refresh the page or restart Syncthing if the problem persists.
```
![image](https://user-images.githubusercontent.com/6528011/56390509-3034dd80-61fa-11e9-9979-3230d589f4f1.png)

I checked my Chrome logs:
```
GET https://3.91.19.156:8384/rest/events/disk?limit=25 net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)"
```
![image](https://user-images.githubusercontent.com/6528011/56390544-46db3480-61fa-11e9-86d4-eb9c0842eaa7.png)

I saw an issue that looked similar:
[https://github.com/syncthing/syncthing/issues/1394](https://github.com/syncthing/syncthing/issues/1394)

The solution listed says:
![image](https://user-images.githubusercontent.com/6528011/56390664-899d0c80-61fa-11e9-972f-18a133e3479e.png)

I am not sure how to adjust the "Server Timeout" or otherwise fix this problem. Let me know if I can provide any other details! Thanks.

**Comment by AudriusButkevicius** [comment]
I suggest you re-read the issue template on where support is provided.
