### ISSUE TITLE
Systemd circular dependency prevents startup

### ISSUE THREAD

**Issue by LSenf** [syncthing/syncthing#5676]
The current systemd service file prevents startup on some systems.
Since 84fe2856591a204fcbba096cd405c9ccaef48c06, syncthing depends on multi-user.target to be finished. However, multiuser-target in turn depends on syncthing. That leads to a hanging systemctl start, at the very least when enabling syncthing via

`$ sudo systemctl enable syncthing@MY_USER.service`

[As discussed on the forums](https://forum.syncthing.net/t/systemd-trouble-after-v1-1-1-upgrade/13201/5), a revert may be necessary (or a better solution).

### Version Information

Syncthing Version: v1.1.1 from https://apt.syncthing.net
OS Version: Ubuntu 18.04 (desktop and server seem affected)

**Comment by calmh** [comment]
I'm actually pulling this into 1.1.2 even though it's very late in the cycle. I think this is justified by 1) it being a serious issue that blocks startup of syncthing and 2) the fix being a revert to a previously tested and known good (enough) setup.
