### ISSUE TITLE
Bug in recvonly comparing local and global after changing sendrecv to recvonly

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing#5677]
Ref.: https://forum.syncthing.net/t/ignore-pattern-with-special-chars-not-working-v1-1-1-windows-amd64/13222/7?u=catfriend1

### Version Information

Syncthing Version: v1.1.1
OS Version: Windows 10 amd64
Browser Version: Chrome 73.0.3683.103 64-bit

**Comment by calmh** [comment]
The forum thread is inconclusive speculation. This needs an actual description to be actionable.

**Comment by Catfriend1** [comment]
Yes, I've tested to rebuild the database and the problem was gone.

**Comment by calmh** [comment]
I don't doubt there is/was an issue, but I don't see a way to progress on this.
