### ISSUE TITLE
Panic on Windows 10 with filesystem watching

### ISSUE THREAD

**Issue by FomalhautWeisszwerg** [syncthing/syncthing#5695]
## Problem

Syncthing v1.1.2 that runs on Windows 10 cause panic during synchronizing files with the other node.

### Node 0
OS: Debian GNU/Linux
Syncthing version: v1.1.2

### Node 1
OS: Windows 10 Pro (version 10.0.18362 N/A Build 18362)
Syncthing version: v1.1.2

## Steps to reproduce the problem

1. Run Syncthing on the Node0 (Debian) with command `syncthing 2>&1`

2. Run Syncthing on the Node1 (Windows10) with command `syncthing`

3. Syncthing on the Node1 always causes panic.

## Log

The file [panic-20190508-223555.log](https://github.com/syncthing/syncthing/files/3157632/panic-20190508-223555.log) was recorded on the Node1 (Windows10).

Do you have any ideas?

**Comment by calmh** [comment]
Hello from the future!

<img width="716" alt="Screenshot 2019-05-08 at 17 39 47" src="https://user-images.githubusercontent.com/125426/57388368-4f4edb80-71b8-11e9-91a7-129b4d1d7603.png">

**Comment by calmh** [comment]
I’ve dropped a v1.1.3 release to fix the panic. Filesystem watching of whole disks still won’t work properly though (#5578, same as in v1.1.1).

**Comment by calmh** [comment]
Wow the time warp on the comments here...

**Comment by uok** [comment]
a glitch in the Github matrix... If you see a Windows 10 agent... RUN
