### ISSUE TITLE
Subfolder wrapped in square brackets is not ignored when added to ignore patterns

### ISSUE THREAD

**Issue by mstgrv** [syncthing/syncthing#5698]
I'm trying to share a folder between 2 computers (both Macs, running Syncthing 1.1.3).

On 1 of the computers, the folder I want to share contains a subfolder named "[OLD]", which is named that way so that it appears at the top in Finder when sorting by name. I want to exclude from syncing to the other computer, so I added "/[OLD]" to the ignore patterns for the shared folder on that computer.

The result was that the subfolder wasn't actually ignored at all, and was shared to the other computer. 

The workaround was to rename the subfolder to "!OLD" - this also makes it appear at the top in Finder when sorting by name, and adding "/!OLD" as an ignore pattern worked correctly.

So there seems to be something about folders wrapped in square brackets that's causing issues with ignore patterns.

**Comment by AudriusButkevicius** [comment]
Please refer to the manual for ignores.
