### ISSUE TITLE
INFO: Puller (folder "X" (...), file "Y"): insufficient space in basic J:\Syncthing\X

### ISSUE THREAD

**Issue by zommuter** [syncthing/syncthing#5723]
Recently I started getting errors such as

    [N5CDO] 09:37:20 INFO: Puller (folder "X" (...), file "Y"): insufficient space in basic J:\Syncthing\X

Why is this `INFO` only? I temporarily managed to fix this by changing the `minHomeDiskFree` setting, but now it reappeared and doens't even work with `<minHomeDiskFree unit="%">0</minHomeDiskFree>`. Possibly related to #4079, #2580, #2255. Both my home SSD and the HDD J: have at least 10 GBs free each (not too much, I know, but definitely >0, so at the very least the log message is misleading or `minHomeDiskFree` is ignored somewhere.

Syncthing Version: v1.1.3, Windows (64bit)
OS Version: Windows 10

**Comment by AudriusButkevicius** [comment]
There are two minFreeSpace things, one for database one for the foldee, you are probably tweaking the wrong one.

Anyways, this should be on the forum as it's clearly supporty

**Comment by zommuter** [comment]
I beg to differ - it took me forever to find the second per-folder setting, and there seems to be no way to globally set this to a sensible value. So please at least consider this a feature request.

**Comment by imsodin** [comment]
That feature request already exists: https://github.com/syncthing/syncthing/issues/4224
