### ISSUE TITLE
stdiscosrv mipsle report "out of memory"

### ISSUE THREAD

**Issue by actg** [syncthing/syncthing#5730]
[root@KMS_Server:/root]#/sbin/stdiscosrv 
stdiscosrv v1.0.1 (go1.11.5 linux-mipsle) teamcity@build.syncthing.net 2019-01-18 10:34:18 UTC
Server device ID is QF3MBN6-JB3RJO7-GLY7VS5-LA7PTVW-ESJJLDO-H7KCZJ6-LA6UMGT-DL4TYQF
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x59a232, 0x16)
        /usr/local/go/src/runtime/panic.go:608 +0x60
runtime.sysMap(0x3800000, 0x2000000, 0x95cbf8)
        /usr/local/go/src/runtime/mem_linux.go:156 +0xf0
runtime.(*linearAlloc).alloc(0x950d84, 0x2000000, 0x400000, 0x95cbf8, 0x391b8)
        /usr/local/go/src/runtime/malloc.go:1230 +0xd0
runtime.(*mheap).sysAlloc(0x9502c0, 0x2000000, 0x0, 0x3933c)
        /usr/local/go/src/runtime/malloc.go:525 +0x78
runtime.(*mheap).grow(0x9502c0, 0x1000, 0x0)
        /usr/local/go/src/runtime/mheap.go:920 +0x4c
runtime.(*mheap).allocSpanLocked(0x9502c0, 0x1000, 0x95cc08, 0x7ff8b5e4)
        /usr/local/go/src/runtime/mheap.go:848 +0x3ac
runtime.(*mheap).alloc_m(0x9502c0, 0x1000, 0xffff0101, 0x8a2)
        /usr/local/go/src/runtime/mheap.go:692 +0x14c
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:759 +0x5c
runtime.(*mheap).alloc(0x9502c0, 0x1000, 0x77010101, 0x94b480)
        /usr/local/go/src/runtime/mheap.go:758 +0x90
runtime.largeAlloc(0x2000000, 0x70101, 0x77d10000)
        /usr/local/go/src/runtime/malloc.go:1019 +0xa0
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:914 +0x58
runtime.systemstack(0x76e1c)
        /usr/local/go/src/runtime/asm_mipsx.s:207 +0x9c
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1229

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_mipsx.s:159 +0x8 fp=0x1439978 sp=0x1439974 pc=0x76ef8
runtime.mallocgc(0x2000000, 0x5179e0, 0x1, 0x1441ac0)
        /usr/local/go/src/runtime/malloc.go:913 +0x9a0 fp=0x14399cc sp=0x1439978 pc=0x1c3ac
runtime.makeslice(0x5179e0, 0x0, 0x2000000, 0x6fbb4000, 0x1410600, 0x11b01)
        /usr/local/go/src/runtime/slice.go:70 +0xa4 fp=0x14399e0 sp=0x14399cc pc=0x5e08c
github.com/syndtr/goleveldb/leveldb/memdb.New(0x625890, 0x140c900, 0x2000000, 0x1439b20)
        /opt/tcagent/syncthing-2-work/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20171214120811-34011bf325bc/leveldb/memdb/memdb.go:470 +0xfc fp=0x1439a2c sp=0x14399e0 pc=0x3d22dc
github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal(0x145e200, 0x145e200, 0x3613240)
        /opt/tcagent/syncthing-2-work/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20171214120811-34011bf325bc/leveldb/db.go:508 +0x44c fp=0x1439b98 sp=0x1439a2c pc=0x3ec2c8
github.com/syndtr/goleveldb/leveldb.openDB(0x147a280, 0x0, 0x0, 0x147a280)
        /opt/tcagent/syncthing-2-work/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20171214120811-34011bf325bc/leveldb/db.go:124 +0x558 fp=0x1439c20 sp=0x1439b98 pc=0x3eb8d0
github.com/syndtr/goleveldb/leveldb.Open(0x62bd80, 0x14421c0, 0x945520, 0x0, 0x0, 0x0)
        /opt/tcagent/syncthing-2-work/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20171214120811-34011bf325bc/leveldb/db.go:196 +0xfc fp=0x1439c40 sp=0x1439c20 pc=0x3ebbbc
github.com/syndtr/goleveldb/leveldb.OpenFile(0x595b8f, 0xe, 0x945520, 0x140c890, 0x3612e80, 0x14180b0)
        /opt/tcagent/syncthing-2-work/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20171214120811-34011bf325bc/leveldb/db.go:218 +0x90 fp=0x1439c74 sp=0x1439c40 pc=0x3ebd90
main.newLevelDBStore(0x595b8f, 0xe, 0x0, 0x0, 0x0)
        /opt/tcagent/syncthing-2-work/174e136266f8a219/cmd/stdiscosrv/database.go:45 +0x50 fp=0x1439c9c sp=0x1439c74 pc=0x4af060
main.main()
        /opt/tcagent/syncthing-2-work/174e136266f8a219/cmd/stdiscosrv/main.go:172 +0x838 fp=0x1439fcc sp=0x1439c9c pc=0x4b6d24
runtime.main()
        /usr/local/go/src/runtime/proc.go:201 +0x250 fp=0x1439fec sp=0x1439fcc pc=0x453cc
runtime.goexit()
        /usr/local/go/src/runtime/asm_mipsx.s:660 +0x4 fp=0x1439fec sp=0x1439fec pc=0x792a0

goroutine 20 [runnable]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x14b2210)
        /opt/tcagent/syncthing-2-work/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20171214120811-34011bf325bc/leveldb/util/buffer_pool.go:202
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
        /opt/tcagent/syncthing-2-work/pkg/mod/github.com/syndtr/goleveldb@v0.0.0-20171214120811-34011bf325bc/leveldb/util/buffer_pool.go:237 +0x198

**Comment by calmh** [comment]
Maybe you have too little memory?

**Comment by actg** [comment]
Yes,the memory of system 20MB free space to suitable stdiscosrv?

**Comment by calmh** [comment]
No, you’ll need a bit more.
