### ISSUE TITLE
100% CPU every minute on watch setup retry

### ISSUE THREAD

**Issue by dugwood** [syncthing/syncthing#5731]
What happened: syncthing, for some folders, get stuck at 100% CPU for hours (state is `idle`)
What you expected to happen instead: CPU drops after a few minutes (when state is `idle`)
Any steps to reproduce the problem:
- set inotify limit too low
- use FSwatcher

The main issue is that there's no way to know the inotify limits to use. For instance:
- `sysctl.conf` has `fs.inotify.max_user_watches = 204800`
- directory (root folder) has `379320` directories (but only `103917` directories not ignored) and `1970011` files (but only `41029` files not ignored)

Increasing the inotify limit to 1M+ fixes the issue.

## Questions/thoughts/ideas

- does the inotify limit need to be higher than all directories (ignored + not ignored)?
- is there a way to list all files/directories to be watched? This way, we could prevent this issue by determining a correct value before increasing it with random values (here `204800` as stated in the docs doesn't help). Or perhaps just give the information in the error: `inotify limit was hit, XXX directories are to be watched (see ...)`.
- using `strace`, I've seen a lot of calls to `inotify_rm_watch`. I don't understand why? Is it because I've reached the inotify limit? After increasing the limit, there's no more calls.
- hitting the inotify limit should be reported as `INFO` or `WARNING` in the logs. I've searched a lot before understanding why my files were not in sync, enabling verbose helped a lot, because the message was clear: inotify issue (+ link to how to deal with the issue).
- I've used `sysctl -p` to update the limit right now, after editing `/etc/sysctl.conf`, perhaps it would be useful to update your docs for this very command, I think it's better as it uses the real configuration file (`/etc/sysctl.conf`), so no bad surprises on reboot.

## Thanks

Thank you for this tool, used alongside of Unison for other purposes, it's really great!

### Version Information

Syncthing Version: v1.1.3
OS Version: Debian stable (Stretch), using https://apt.syncthing.net/ repository

**Comment by dugwood** [comment]
Same issue today, with version 1.3.1.

- Directories in repository: `208277`
- Directories in repository that are ignored in `.stignore`: at least `148350` (difficult to determine this with `find` and `.stignore` syntax). So at most there's `59927` directories to watch
- inotify limit: `fs.inotify.max_user_watches = 204800`

Setting inotify limit to 209k fixes it. So there's clearly an issue with inotify, listening to directories that are ignored. Perhaps it's because we can't define exactly what directories are to be ignored, for example with subdirectories that would be included when created.

So the good call would be to increase level of error, from `DEBUG` to `WARN` (and perhaps limit error logging to one every 1 minute, so that we don't flood the logs). I've looked at the code, but I clearly don't understand `go` :smile:

**Comment by AudriusButkevicius** [comment]
If you have excluded ignore patterns, all paths are watched, because things like `!**.mp3` requires us to watch everything.

**Comment by calmh** [comment]
Bug here seems to be too insistent retries to set up the watcher. It should not be frequent enough to cause persistent high CPU.

**Comment by imsodin** [comment]
We retry watching once a minute - I wouldn't expect that to create any significant resource usage.

Please enable `model` and `watchaggregator` debug log facilities and share those logs.

> * hitting the inotify limit should be reported as `INFO` or `WARNING` in the logs. I've searched a lot before understanding why my files were not in sync, enabling verbose helped a lot, because the message was clear: inotify issue (+ link to how to deal with the issue).

Watch errors at setup are logged at info level, watch errors after setup at warning level but just once.

**Comment by dugwood** [comment]
@imsodin I've tried with `model` and it seems that the issue wasn't linked to the inotify issue. I can confirm what you said, once every minute there's an INFO log:

> 2020/04/16 16:24:21.489330 folder.go:716: INFO: Error while trying to start filesystem watcher for folder "xxx" (xxx), trying again in 1min: failed to setup inotify handler. Please increase inotify limits, see https://docs.syncthing.net/users/faq.html#inotify-limits

My remark about INFO and WARNING was the need to see that a new problem arise: if first setup is good, but after a while the directory may have many more files, hence the issue isn't visible (as it's an INFO level, which isn't the default log level AFAIK).

I can see CPU spike just after the watcher's start. So every minute, watcher tries to run, get the inotify limit, and stops after a few seconds:

> 2020/04/16 16:43:05.084726 folder.go:180: DEBUG: sendreceive/xxx@xxx Delaying scan
> 2020/04/16 16:43:05.084792 folder.go:172: DEBUG: sendreceive/xxx@xxx Scanning due to timer
> 2020/04/16 16:43:11.115586 folder.go:247: DEBUG: sendreceive/xxx@xxx next rescan in 29h28m40.855753856s

Here there 2 timestamps: 16:43:05 to 16:43:11, during which the CPU is 100%. So every minute, there's a 100% CPU spike. And the next one is run at 16:44:05, so exactly 1 minute after the previous try. It should start 1 minute after the end of spike.

But in the end, the whole issue is that it's hard to find out that the 100% CPU is linked to inotify limit... To me it boils down to:
 - increasing level for «Error while trying...» from INFO to WARN
 - increasing the 1 minute delay (not essential, and perhaps first retry after 1 min, then after 2 min, ...)

**Comment by imsodin** [comment]
Actually the logging is fine: The warning only occurs on the error that was previously a panic: If an event is registered outside of the shared folder (which should never happen). Otherwise it is info logs (which is the normal level) and the notification in the UI - I think that's enough given it's not an essential component.

For the increasing setup delay, see https://github.com/syncthing/syncthing/pull/6544

**Comment by dugwood** [comment]
Thanks @imsodin I'll close this as soon as the increasing delay is committed. You may do it right now if you like.

**Comment by imsodin** [comment]
No need to do anything manually for closing, the issue gets closed automatically (well by commit keyword) once the linked PR is merged.
