### ISSUE TITLE
How to running  stdiscosrv or strelaysrv with daemon mode in linux platform?

### ISSUE THREAD

**Issue by actg** [syncthing/syncthing#5740]
It seems like not have correspond start options to perform daemon running?

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
