### ISSUE TITLE
Capital letters are not syncing and causing "Not synced status"

### ISSUE THREAD

**Issue by Oriann** [syncthing/syncthing#5747]
Hello
I have this problem still from ver.1.0.0

Problem:
PC A - folder containing file foo.bar
PC B - folder containing file foo.bar
PC A - changes file and rename it to Foo.bar
PC B - out of sync file foo.bar
So capital letters are causing this and its very annoying because I cannot change letters when I want to make a changes to my files and therefore I have not synced folders.

Is somebody working on this ?

Thanks in advance

**Comment by AudriusButkevicius** [comment]
Please search for existing issues before opening new ones: https://github.com/syncthing/syncthing/issues/1787

**Comment by Oriann** [comment]
Oh sorry overlooked this issue alredady open.
My bad
