### ISSUE TITLE
[Feature] Support I2p

### ISSUE THREAD

**Issue by ghbjklhv** [syncthing/syncthing#5748]
**Feature/Question**: Add i2p proxy option.

**Comment by calmh** [comment]
Syncthing supports SOCKS and HTTP(S) proxies. I don't think we need to do anything specific here.

**Comment by asddsaz** [comment]
@calmh So, just pointing to proxy to "127.0.0.1:4444" should make it use I2p?
Wouldn't it need more than this? Like start individual eepsite or b32.i2p sites?

I think this issue might need to be reopened, I2p isn't like TOR.
It generally, only connects to other sites using I2p.
