### ISSUE TITLE
Time to add fanotify support?

### ISSUE THREAD

**Issue by infectormp** [syncthing/syncthing#5755]
Hello,

Linux Kernel 5.1 released and now it can handle all FS events via fanotify  https://github.com/amir73il/fsnotify-utils/wiki/Super-block-root-watch, so maybe it;s time to add support for fanotify?

**Comment by AudriusButkevicius** [comment]
We just us a library, so it would have to land in that library.

**Comment by infectormp** [comment]
Thanks for your very helpful answer!

**Comment by AudriusButkevicius** [comment]
Namely https://github.com/rjeczalik/notify
