### ISSUE TITLE
Dead link in README.md

### ISSUE THREAD

**Issue by GermanCoding** [syncthing/syncthing#5760]
Minor things are minor, but I'm somehow good at finding those dead links.

The very first link in the [README](https://github.com/syncthing/syncthing/blob/master/README.md) `latest|downloads` is a 404.

![readme_snap](https://user-images.githubusercontent.com/4279661/58767549-0c9cdb00-858d-11e9-954d-edddf3f990e7.PNG)

The link could either point to GitHub releases, but since the adjacent links all point to the build server it might also make sense to leave it as-is and just update the path. Whatever feels right for you.

**Comment by calmh** [comment]
Old irrelevant link is irrelevant. :) Thanks!
