### ISSUE TITLE
[Feature] Syncthing over I2p

### ISSUE THREAD

**Issue by asddsaz** [syncthing/syncthing#5764]
**Objective**: Enable utilization of Syncthing over I2p (+documentation)

**Description**: Is it possible for Syncthing devices to sync over I2p using the main 
Syncthing GUI? If so, how?

**Why?**: Many reasons, mainly to promote privacy and security but also to support decentralized web communications.

________________________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/75170793-feature-syncthing-over-i2p)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

**Comment by AudriusButkevicius** [comment]
There are plenty of tunneling software out there, I don't think we should do anything special to support them.

If you choose to use this type of software, it's down to you to figure out how to get syncthing to run in that environment, as we are not going to write documentation for every piece of tunneling software under the sun.

The basic concepts of how syncthing works are described in the docs, so you need to translate those concepts in your tunneling software and make sure the same concepts are available for syncthing to use.
