### ISSUE TITLE
Scan failure blocks "Rescan" button

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#5770]
I had some things that could not be scanned (permission denied). I fixed those permissions and want to rescan. I cannot, manually:

<img width="570" alt="Screen Shot 2019-06-10 at 09 38 55" src="https://user-images.githubusercontent.com/125426/59179891-b834c500-8b63-11e9-9b04-f93abd4a79ad.png">

(The `Rescan` button is disabled, presumably because the folder is not in one of the pre-approved scannable states?)

**Comment by imsodin** [comment]
Yeah, most likely due to the new failed state I added with displaying the scan errors - I wasn't aware of this behaviour of the rescan button. Are you already on it or should I have a look?

**Comment by calmh** [comment]
Please, if you have the inclination :)
