### ISSUE TITLE
Panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by dankh** [syncthing/syncthing#5773]
# What happened ?

Syncing :
- Ubuntu 18.04 PC with Syncthing installed from the repository
- Android 9 phone with Syncthing installed from F-Droid

Devices connected, 1 folder from the phone is set to be synced on the PC (photos). The folder is 12GB. The sync client on the phone is running.

When I start the sync client on the PC the sync starts and exits in couple of seconds then restarts. After 4 attempts the client on the PC stops.

![syncthing-panic](https://user-images.githubusercontent.com/1543727/59187522-ede2a980-8b75-11e9-8e7c-74751926b50a.jpg)

On the console I have :

```
[7JCHJ] 11:36:52 INFO: Device OQAAKVE-MJR6NDZ-T6TEIS6-VWWSYDW-A2L4QMD-FKW6KL6-NKOQ3VM-N57IFAW client is "syncthing v1.1.4" named "phone"
panic: runtime error: slice bounds out of range
[monitor] 11:37:00 WARNING: Panic detected, writing to "/home/me/.config/syncthing/panic-20190610-113700.log"
[monitor] 11:37:00 WARNING: Please check for existing issues with similar panic message at https://github.com/syncthing/syncthing/issues/
[monitor] 11:37:00 WARNING: If no issue with similar panic message exists, please create a new issue with the panic log attached
[monitor] 11:37:00 INFO: Syncthing exited: exit status 2
[monitor] 11:37:01 WARNING: 4 restarts in 28.260067146s; not retrying further
```
[panic-20190610-113700.log](https://github.com/syncthing/syncthing/files/3271530/panic-20190610-113700.log)

# What you expected to happen instead ?

Folder to sync.

# Version Information

## Ubuntu PC

- Syncthing Version: v0.14.43-ds1
- OS Version: Ubuntu 18.04
- Browser Version: Firefox 67.0.1 (64-bit) 
- Connection to LAN

## Android Phone

- Syncthing Version: v1.1.4
- OS Version: Andoird 9
- Connected to WiFi router on the same LAN

**Comment by calmh** [comment]
This issue was fixed in 0.14.46, you just need to upgrade. If Debian doesn't provide anything newer consider https://apt.syncthing.net.
