### ISSUE TITLE
Consider always running the monitor process

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#5786]
The monitor process handles multiple different concerns:
- Restarts, in that the main syncthing process can exit with a certain exit code and get restarted
- Crashes, in that the main syncthing process will get restarted
- Crash reporting, both storing the crash from above and sending it to the mothership when enabled.

If the restart behavior is undesired the monitor process can be disabled by env var or startup switch.

However, we *could* just always use the monitor process for crash tracking and when given one of the flags as above exit afterwards, letting whoever is monitoring us see the restart happening.

**Comment by AudriusButkevicius** [comment]
It breaks killing the proccess tho, as in most cases the child will get disowned.

**Comment by imsodin** [comment]
Not if the monitor handles signals and terminates the child correctly (except SIGKILL, but when you use that you asked for it). It already does that today I think.

**Comment by calmh** [comment]
We handle a normal (soft) kill correctly. For a SIGKILL, yeah, you need to target all the processes. (Or the process group that we set up.)

**Comment by AudriusButkevicius** [comment]
I know for a fact android uses sigkill after some time, and having runaway processes there would be terrible as they would kill the battery. There is prctl P_DEATHSIG on linux tho, or we could just poll for ppid and blow up when it changes.

**Comment by calmh** [comment]
Why do you think Android would only send sigkill to the monitor process, if this is something it does to kill off background things and save battery? But even if that's the case, then Android can be a special case and run without monitor...

**Comment by AudriusButkevicius** [comment]
Android wrapper sends term, if that doesn't exit in 10s, then sends a kill.

**Comment by canton7** [comment]
The reason that SyncTrayzor doesn't use the monitor process is upgrades. When Syncthing upgrades itself, the monitor process spawns the new version of the monitor process and then exits. SyncTrayzor then loses control of the monitor process.

I'm good with anything so long as this problem isn't re-introduced.

**Comment by calmh** [comment]
I guess with a hypothetical mandatory monitor process, automatic upgrades, and setting STNORESTART=1 like you do now, both the real syncthing process and then then monitor process would simply exit when it wants to restart after upgrade. So from my point of view you should not notice any difference.

Audrius, for the sigkill case I guess it would break if you are indeed the one sending sigkill to just the child. I don’t think it’s possible to solve this from the child process (presumably it’s already wedged hard for whatever reason or we wouldn’t be in sigkill land). The solution would be to send sigkill to the entire process group, like the shell does. (I don’t know offhand how to do that.)

**Comment by AudriusButkevicius** [comment]
I am not arguing for sigkill, I am declaring how it works, and arguing that there might be other cases like that.

**Comment by calmh** [comment]
Yeah, OK. I guess my point is that once you start sending SIGKILL it's all in the senders responsibility to clean up properly because agency is removed from the receiver. This goes for everything from separate processes to lock files and whatnot. In the Android case, if this is something that needs to happen, we can tweak the wrapper to accomodate.
