### ISSUE TITLE
[doc] list the ports to be opened in the firewall (22000)

### ISSUE THREAD

**Issue by kdupke** [syncthing/syncthing#5789]
This is just for the documentation, where the ports should be listen to be opened in the firewall.

Might be under security, or specs?

**Comment by imsodin** [comment]
This is the wrong repo: https://github.com/syncthing/docs

And it already exists: https://docs.syncthing.net/users/firewall.html

**Comment by kdupke** [comment]
Thank you for pointing me to this. However, it was not obvious place for me to find this information.
