### ISSUE TITLE
Update iOS App

### ISSUE THREAD

**Issue by CaptainKhan** [syncthing/syncthing#5790]
iOS app from 2014 defaults to Send Anonymous data, basically tracking you. Which is sort of the opposite that security minded users want. 

Please fix and update. Also on the 4SE Phone the app crashes on sync yang the newest available iOS. Please fix.

**Comment by calmh** [comment]
There is no iOS app. I don't know what you're talking about.

**Comment by CaptainKhan** [comment]
Well there is an iOS app, and even if there isn't you should develop one!

The iOS app is called fsync() and is the only functioning client for syncthing. How do you not know that?

**Comment by AudriusButkevicius** [comment]
We know that, but it's closed source so there is nothing we can do about it.

Nobody gets paid for the work that we do, so bossing us around telling us where we should spend our time does not give any motivation to do anything.

How about YOU develop the app?
