### ISSUE TITLE
Unable to update Web

### ISSUE THREAD

**Issue by canadianschism** [syncthing/syncthing#5797]
Whenever I try to update the online version of Syncthing to 1.1.4 (so that it matches my Windows installation), I get a whole bunch of perms denied errors and it never actually updates.

I've tried through the WebUI and also through my seedbox site. Neither do anything.

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
