### ISSUE TITLE
Connection Error and GUI almost unusable

### ISSUE THREAD

**Issue by ghigo** [syncthing/syncthing#5800]
When connecting to the GUI, the alert "Connection Error - Syncthing seems to be experiencing a problem processing your request. Please refresh the page or restart Syncthing if the problem persists." consistently pops up in within 20 seconds or so.
If I make any config change very fast, as soon as I refresh the page, I sometimes manage to have the config changed, otherwise when I refresh the browser, I can tell the edit wasn't saved.

I'm running Syncthing in two very similar machines running FreeNAS (more details below) and I'm experiencing the same issue in both machines.
I had the same issue in v1.1.1 but once I stopped watching the directories, the frequency of this issue drastically decrease up to the point that I rarely saw it.
I'm now not watching any directory and I have a refresh of 1h in one machine and 10h in the other.

I rebooted the jail multiple times with no improvement. Let the jail run for a day, same issue.

I'm connecting to the GUI over a local network, so the connection between the laptop and the NAS should be quite reliable.

### Version Information

Syncthing Version: v1.1.2, FreeBSD (64 bit)
OS Version: FreeBSD (64 bit) - FreeNAS-11.2-U4.1
Running Syncthing as a FreeNas plugin - in one machine it's a fresh installation of the latest version, in another machine I installed v1.1.1 then upgraded.
Browser Version: Chrome and Firefox (latest stable)

**Comment by imsodin** [comment]
When the error occurs, open the browsers console (development tools, usually press F12), there should be a message with details about the error. And check resource usage when this happens.

**Comment by lieryan** [comment]
I have the same issue on a fresh install in Ubuntu 19.04. This is using the latest syncthing that is available from the Ubuntu repository (which I am aware is a bit behind): syncthing=1.0.0~ds1-1

From what I can observe from the Browser Network tools, the error popup seems to coincide with the web client receiving HTTP 500 error when trying to access URL: http://127.0.0.1:8384/rest/system/upgrade. The response body says: upgrade unsupported.

**Comment by imsodin** [comment]
Is there are trace in the console with that http error? If in doubt just copy the entire thing.

**Comment by lieryan** [comment]
I tried running `STTRACE=http,upgrade,event,config,dialer,discover,main,model syncthing -verbose` ([server logs around the time of the message pops up](https://pastebin.com/9Kj4P9Eu)), I can't see anything that looks like a trace or anything that looks obviously out of ordinary other than the 500 from the server.

**Comment by imsodin** [comment]
I am asking about the browser console where the http 500 error occurs, not Syncthing logs.

**Comment by ghigo** [comment]
Here is a screenshot of the console when the error occurs:

[image: Screen Shot 2019-06-17 at 8.22.15 PM.png]

**Comment by ghigo** [comment]
Here is a screenshot of the console when the error occurs:

<img width="555" alt="Screen Shot 2019-06-17 at 8 22 15 PM" src="https://user-images.githubusercontent.com/185571/59651302-32ee7900-913e-11e9-899e-b5006b169a86.png">

**Comment by ghigo** [comment]
@imsodin , please let me know if/how I could further help with debugging this issue.

**Comment by imsodin** [comment]
No idea. These are generic timeout errors, nothing generated by Syncthing's own code. The only reason I can imagine is total system overload.

**Comment by AudriusButkevicius** [comment]
Or a proxy

**Comment by ghigo** [comment]
@imsodin By looking at the GUI dashboard, it seems like the highest peak of CPU was ~30% when running the syncthing UI. I feel this error comes up more frequently when I sync up many big directories. But I don't really have numbers to support this feeling.
@AudriusButkevicius I'm not using a proxy

**Comment by AudriusButkevicius** [comment]
I suggest you start a thread on the forum, because having an issue on github without an explanation what needs fixing is not very useful.
