### ISSUE TITLE
Staggered ver: WARNING: versioner: lstat … no such file or directory 

### ISSUE THREAD

**Issue by grinapo** [syncthing/syncthing#5807]
### version info
Syncthing: 1.2.0-rc.1, Linux (64 bit)
OS: Debian/sid
Browser: Firefox/Nightly

### Problem
Since first RC (first error was logged at 1.2.0-rc.1 update) every restart gives lots of
```
[ZILLL] 2019/06/18 14:13:21.144061 DEBUG: Versioner: Expiring versions [{kkk/IP 2015.pdf {0 63600387389 0x164dc20}}]
[ZILLL] 2019/06/18 14:13:21.144064 DEBUG: Versioner: File over maximum age -> delete  kkk/IP 2015.pdf
[ZILLL] 2019/06/18 14:13:21.144072 WARNING: versioner: lstat /path/syncthing/data/qwz/.stversions/kkk/IP 2015.pdf: no such file or directory
```
for various directories containing Staggered versions. 

I have not switched versioning method. Trying to restore gives
```
Restore Versions
Some items could not be restored:
teszt/read.me 	version not found
```

The files exist, as
```
  File: /path/syncthing/data/wmm/.stversions/kkk/IP 2015~20180802-100304.pdf
  Size: 48092           Blocks: 96         IO Block: 4096   regular file
Device: fd0ch/64780d    Inode: 270277611   Links: 1
Access: (0640/-rw-r-----)  Uid: ( 1000/    grin)   Gid: ( 1000/    grin)
Access: 2016-06-01 16:16:29.000000000 +0200
Modify: 2016-06-01 16:16:29.000000000 +0200
Change: 2018-08-02 10:03:04.284463709 +0200
 Birth: -
```

### More details
...at https://forum.syncthing.net/t/warning-versioner-lstat-no-such-file-or-directory/13390/3

**Comment by AudriusButkevicius** [comment]
Seems there are multiple bugs here.
One is the staggered expire grouping happens on untagged file name, but version does not include the tagged file name.

Restoration function takes a version timestamp, yet the filenames have modtime of the original file embedded, meaning we potentially need to do multiple globs to find it (old style glob, new style glob, and without a timestamp potentially).
