### ISSUE TITLE
GUI theme not changing on WebKit-based/like browsers

### ISSUE THREAD

**Issue by CharmsyPone** [syncthing/syncthing#5810]
Hi there! I'm having an issue when it comes to changing the GUI theme on Vivaldi/Midori, that is not replicable in Firefox. When I attempt to change the GUI theme on either of my Syncthing instances, it does not actually change, even when the page is refreshed, browser closed down entirely, or Syncthing is restarted.

However in Firefox, the change immediately takes affect and is shown. I am not sure what causes this, however I have isolated it to be a WebKit bug due to it happening on Midori and Vivaldi, of which Midori uses WebKit, and Vivaldi is based on a modified version of Chromium. 

Notably, when the theme is changed on Vivaldi, Firefox reports the theme as being the incorrect one. And changing the theme on Firefox corrects it for Firefox, but not Vivaldi. 

Version Information
Syncthing Version: v1.1.4, Linux (64 bit) & v1.1.4, Linux (ARM)
OS Version: Arch Linux (Anarchy Linux, 64-bit) / Arch Linux ARM (Raspberry Pi 3 Model B) 
Browser Version: Vivaldi 2.6.1566.40 (Stable channel) (64-bit)/Midori Web Browser 8.0/Firefox 67.0.3 (64-bit)

Provided below are two screenshots; the first one shows Vivaldi connected to the Raspberry Pi 3 Syncthing instance, and it showing the wrong theme. The next one shows Vivaldi connecting to the local instance of Syncthing, and it also showing the wrong theme.

![Screenshot from 2019-06-20 14-37-52](https://user-images.githubusercontent.com/8446547/59873000-0a969280-9369-11e9-88ba-e0e70ce245fe.png)
![Screenshot from 2019-06-20 14-39-01](https://user-images.githubusercontent.com/8446547/59873320-b809a600-9369-11e9-834a-29aceba9d75e.png)

**Comment by iwittkau** [comment]
I can replicate the behavior on Safari Version 12.1.1 on macOS. However, when I empty the cache and reload the page, the GUI theme changes take effect.

**Comment by CyberFoxHax** [comment]
I confirm this too. @iwittkau Thanks for the workaround.
