### ISSUE TITLE
Web interface: download progress of folders do not get updated

### ISSUE THREAD

**Issue by iwittkau** [syncthing/syncthing#5811]
### Version Information

Syncthing: v1.1.4, macOS (64 bit)
macOS: 10.14.5 (18F132)
Browsers:
- Safari: 12.1.1 (14607.2.6.1.1)
- Firefox: 67.0.3 (64-Bit)
- Chrome: 75.0.3770.100 (Official Build) (64-Bit)

### Expected Behavior

- Download progress of remote folders get updated automatically

### Actual Behavior

- Download progress of remote folders do not get updated and are stuck to size and percentage values of when the web interface was loaded.
- Local status like download/upload rate do get updated
- A `DownloadProgress` object is logged periodically in the browser's console
- No errors are logged in the browser or syncthing
- Same behavior on all browsers listed above
- Progress is displayed correctly when the users refreshed the web interface by reloading

**Comment by AudriusButkevicius** [comment]
Remote folders are not visible in the UI, so not sure what this refers to.

**Comment by iwittkau** [comment]
@AudriusButkevicius ok, scratching "remote", just "folders" then.

**Comment by imsodin** [comment]
Can we get screenshots please and move this discussion to https://forum.syncthing.net until it's clear what the problem is and then reopen if applicable.

**Comment by iwittkau** [comment]
<img width="1347" alt="Bildschirmfoto 2019-06-25 um 08 22 41" src="https://user-images.githubusercontent.com/6094090/60074519-5c516b00-9723-11e9-90c4-6429553ceff2.png">

The "Folders" section, marked red, does not get updated. The "This Device" section, marked green, does get updated.

**Comment by imsodin** [comment]
Ok, for once the roundtrip to the forum was really not needed :)

Problem is that we do account for download progress in folder summaries, but don't trigger generating one on download progress events (which is good in my opinion, folder summaries aren't cheap). And in the web UI there is code parsing download progress messages, but that information is only used for the out of sync modal, not the sync percentage. I'll change that.
