### ISSUE TITLE
Potential bugs on old cores: using 64-bit functions sync/atomic

### ISSUE THREAD

**Issue by lzhfromustc** [syncthing/syncthing#5813]
### Bug Report
I noticed that there are usages of atomic.LoadInt64, atomic.AddInt64, etc.
These 64-bit functions in sync/atomic can cause errors on old cores. Please see: https://golang.org/pkg/sync/atomic/#pkg-note-BUG
I am not sure if some users are running syncthing on these old cores.

Usage Position: (There may be more)
        File:lib/protocol/counting.go
	Line:24,25
	File:cmd/strelaysrv/status.go
	Line:52,53
	File:cmd/strelaysrv/session.go atomic.LoadInt64 atomic.AddInt64
	Line:254

### Version Information

Syncthing Version: master. 
Latest commit: bf744ded311cdeac6234bce95a8a4871baaefcc0

**Comment by AudriusButkevicius** [comment]
The issue should be fixed in golang, we will not limit ourselves to using certain language features just to support old hardware.

**Comment by calmh** [comment]
No this is legit, we should ensure placement of those variables so they get 64 bit aligned according to the current rules. As-is it seems they get 64 bit aligned by chance.

**Comment by AudriusButkevicius** [comment]
I don't think this is about that?

**Comment by calmh** [comment]
I dunny, the report is unclear, but that’s my charitable reading. It flags a couple of uses of atomic where the pointed-to variable is not in a guaranteed-aligned place in a struct, and that’s one of the bugs mentioned on the linked page and something we can actually fix. 🤷‍♂

**Comment by lzhfromustc** [comment]
Thank you for your reply! I reported this bug because I saw grpc-go developers viewed the usage of atomic64 functions as a bug and they easily fixed it in this [pull](https://github.com/grpc/grpc-go/pull/1411).
Maybe it is not a problem for syncthing if users rarely use [those old cores](https://golang.org/pkg/sync/atomic/#pkg-note-BUG) mentioned by golang. Feel free to close this issue if you want.

**Comment by calmh** [comment]
Ok, so that clarifies the report, thanks. We will continue to use 64 bit atomics I think, but we can be more strict about ensuring alignment. So I’m repurposing the report for that purpose instead.

**Comment by arl** [comment]
Hi, I'd like to work on that issue, if nobody is planning to do so.

**Comment by AudriusButkevicius** [comment]
Sure

**Comment by arl** [comment]
Ok. I'll first look for all sync/atomic usages in the codebase (deps included) and fix the faulty ones, if any.

**Comment by lzhfromustc** [comment]
@arl Thank you! Maybe reading how grpc contributors fixed this bug can help: https://github.com/grpc/grpc-go/pull/1411/files

**Comment by arl** [comment]
FYI: there's a new go vet check named `atomicalign` on which I'm currently
working that checks the alignment of atomic variables.

It's not currently part of the released go vet, is still in development and
currently misses many cases.
To be able to check your code, this analyser must run on one of the
affected platforms.

See https://godoc.org/golang.org/x/tools/go/analysis/passes/atomicalign

>
