### ISSUE TITLE
Build OpenBSD-arm64 request

### ISSUE THREAD

**Issue by jungle-boogie** [syncthing/syncthing#5814]
Hi All,

This is a request to have a build of `syncthing` built for arm64. Currently it looks like there are three builds available on OpenBSD:
* i386
* x64
* arm

There is only one build of arm64 available now: Linix-arm64.
Please consider dropping OpenBSD arm and replacing it with arm64.

FWIW, OpenBSD arm64 can't be built natively on arm64, since the ports maintainers don't have a build of go available for arm64. I'm assuming your build server is cross compling everything on one machine and not executing on each OS and each architecture.

**Comment by AudriusButkevicius** [comment]
There is no OpenBSD arm64 support in the toolchain:
https://golang.org/doc/install/source#environment
So we can't cross-compile to that target.

**Comment by jungle-boogie** [comment]
yeah, after carefully reading that doc as well, it seems I was mistaken. That's too bad. :(

**Comment by 0xf10e** [comment]
Looks like there will be support for OpenBSD/arm64 in the next release of Go though:
[all: add openbsd/arm64 port #31656](https://github.com/golang/go/issues/31656#issuecomment-491380889)

Maybe @jungle-boogie wants to try out Syncthing with golang after [commit dbab0cf9d9b9](https://github.com/golang/net/commit/dbab0cf9d9b9a705cb7fd9e6e80cf6859663688b) ; )

**Comment by jungle-boogie** [comment]
Wow, this is great news! Thanks for pointing me at the patch, @0xf10e
