### ISSUE TITLE
Consider SHA-512 or SHA-512/256 for any overhaul of syncing

### ISSUE THREAD

**Issue by davidstrauss** [syncthing/syncthing#582]
I noticed that there's an entry in the FAQ for why SyncThing takes so much CPU initially [1]. SHA-512 is 10-50% faster on modern 64-bit processors. If SHA-512 produces too long of a hash, it's still better to use SHA-512/256 (half of the hash output of SHA-512) than using SHA-256.

[1] https://discourse.syncthing.net/t/why-does-syncthing-consume-so-much-cpu/446

**Comment by AudriusButkevicius** [comment]
The only good alternative seems to be `blake2`, but the Go implementation is still slower than SHA256, and C implementation kills cross-compiling.
SHA256 seems to be the best option given we want to support low end devices.
Can we close this?

**Comment by generalmanager** [comment]
Why not keep it open? The situation on arm might change and the implementations will improve over time. If this occurs, it would be good to have an open issue about it.
It's a lot easier to find and people are unlikely to open a new issue if they remember that an issue existed but was closed for some reason they don't remember.

Am 7. April 2015 11:36:46 MESZ, schrieb Audrius Butkevicius <notifications@github.com>:

**Comment by davidstrauss** [comment]
It is sort of open; the hash and truncation in use are explicitly
specified. It's just that the only option right now is SHA-512 or some
prefix of it.

**Comment by AudriusButkevicius** [comment]
Well SHA512 performance is very poor on phones and other ARM devices, hence it's not an option as far as I understand.

**Comment by davidstrauss** [comment]
> Well SHA512 performance is very poor on phones and other ARM devices, hence it's not an option as far as I understand.

Whoops, thought I was replying to a different thread on container image hashing that uses SHA-512 as the standard. Nevermind.

**Comment by lambdaupb** [comment]
@imraro http://www.gamasutra.com/view/feature/4111/dirty_coding_tricks.php read section 4 "identity crisis"
