### ISSUE TITLE
YARFFBA (Yet Another Request For a Forms Based Authentication) ;)

### ISSUE THREAD

**Issue by STaRDoGG** [syncthing/syncthing#5821]
[Looks](https://forum.syncthing.net/t/forms-based-gui-authentication/10775). [Like](https://forum.syncthing.net/t/http-login-screen/9752). I'm not the first to request this.

I use LastPass to store/fill everything, and having the old skool login popup makes it so I have to manually search for and copy my ST credentials every time I need to login to it. Any chance this could be added soon? Looks like the first time it was requested was around 2 years(!) ago. lol

(Before anyone says to do a PR, I've just got way too many projects on my plate right now.)

**Comment by AudriusButkevicius** [comment]
PRs welcome

**Comment by STaRDoGG** [comment]
@AudriusButkevicius Awesome. Send one in.

**Comment by calmh** [comment]
#4137
