### ISSUE TITLE
Usage Reporting prompt displays immediately

### ISSUE THREAD

**Issue by ProactiveServices** [syncthing/syncthing#5823]
When starting a new syncthing instance the Usage Report prompt is immediately displayed, rather than waiting for urInitialDelayS in the config file. Tested on v1.1.4.

**Comment by calmh** [comment]
This is the case if you already have the cookie that remembers the initial time you saw the GUI, for example from a different instance of Syncthing that you've also accessed on localhost. I think this is fine; you're already aware of the basics of Syncthing so we don't need to give you the extra time to acclimatize. :)
