### ISSUE TITLE
Sync Protocol Listen Address in Actions behaves badly

### ISSUE THREAD

**Issue by ProactiveServices** [syncthing/syncthing#5824]
When changing the Sync Protocol Listen Address, and clicking "Save" in the browser GUI, a prompt opens confirming if the user fishes to discard the changes. Whichever option is chosen, the changes are applied.

If  anything other than `default` the behaviour is the same, but the console also outputs errors:
```
INFO: Listen (BEP/tcp): listen tcp :22000: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
INFO: c.S.listenerSupervisor: Failed service 'tcp://:22000' (1.000000 failures of 2.000000), restarting: true, error: "{tcp://:22000 tcp://:22000} returned unexpectedly", stacktrace: [unknown stack trace]
```

Semi-relatedly: if the specification includes an IP address or port that cannot be bound, syncthing is aware of this but it's only reported in the console. Also if the "tcp://" prefix is missing, the input is saved but syncthing fails to listen. A GUI warning for these user errors might be helpful.

All tested with v1.1.4.

**Comment by calmh** [comment]
I noticed this too and was going to report but forgot. :) I think the discarding comes from either angular's handling of the comma separated list thing, or the sorting we do of the resulting values. If I remember correctly the discard warning doesn't pop up if the list of of addresses is correctly sorted when entered.

**Comment by calmh** [comment]
Reopen because this issue is actually a flurry of separate issues. Should probably be broken down into separate ones, really.

**Comment by imsodin** [comment]
As far as I understand the other issue in the OP is that an invalid listen address will only result in an info error in the logs, not a warning in the UI. However there is the listener status indication, which will show that the listeners aren't working in such a case and present the error message on hover - I think that's fair.
