### ISSUE TITLE
IPv6 interface suffix in remote device address doesn't work

### ISSUE THREAD

**Issue by ProactiveServices** [syncthing/syncthing#5827]
Similar discussion at #2709 

Windows 7, syncthing 1.1.4.

Interface index 11 is my WLAN adaptor. When configuring a remote device to use the URL `tcp://[fe80::f663:1fff:fe22:54ea%11]:22000` this error is generated:

`service.go:381: INFO: Parsing dialer address tcp://[fe80::f663:1fff:fe22:54ea%11]:22000: parse tcp://[fe80::f663:1fff:fe22:54ea%11]:22000: invalid URL escape "%11"`

If I use the interface suffix %2511 then the URL is correctly resolved. (%25 being an encoded %)

**Comment by calmh** [comment]
Also doesn't work with more obviously non-escaped stuff like `tcp://[fe80::12%en0]:22000` (I thought the problem might be that `%11` *looks* like an escape). I thought this was fixed and tested, but apparently not.

**Comment by jjakob** [comment]
Can confirm, exact same behaviour here.

**Comment by nekr0z** [comment]
> If I use the interface suffix %2511 then the URL is correctly resolved. (%25 being an encoded %)

According to [RFC 6874](https://tools.ietf.org/html/rfc6874#section-2), the `tcp://[fe80::f663:1fff:fe22:54ea%11]:22000` you are trying to feed it is actually not a valid notation, while the one with %25 escape is.

Not a bug.

**Comment by calmh** [comment]
Right. So re-reading this I think it's fine. The issue we had at one point, and that I was referring to as "fixed and tested", was that our internally produced URLs from discovery had this problem. That is indeed fixed - when we discover a device on IPv6 we create a properly escaped URL. So I agree that there is no bug here.

**Comment by jjakob** [comment]
So the issue is in SyncTrayzor then, which should be escaping the % to %25? Isn't syncthing auto-detecting the interface addresses on its own? A quick search through the synctrayzor source couldn't find any place where interfaces are parsed. I'll open an issue at Synctrayzor and see what they have to say.

**Comment by calmh** [comment]
I don't see any mention of Synctrayzor? The original description is `When configuring a remote device to use the URL tcp://[fe80::f663:1fff:fe22:54ea%11]:22000` where the problem is the URL, which *should* be `tcp://[fe80::f663:1fff:fe22:54ea%2511]:22000` to be a valid IPv6 address URL.

**Comment by jjakob** [comment]
Sorry, I didn't mention this in my first post since the OP's error message and address was exactly the same. I'll try to duplicate the issue on Windows with just syncthing on its own so I can see if it depends on SyncTrayzor or not.
