### ISSUE TITLE
Paused folder shows filesystem watcher error

### ISSUE THREAD

**Issue by sisu4syncthing** [syncthing/syncthing#5833]
Hello,
coming from here:
https://forum.syncthing.net/t/filesystem-watcher-errors-on-paused-folder/13467

Sadly, I couldn't reproduce it myself today, but hopefully someone here can, or find the part of code :-)

 - what happened,
When PAUSING a folder, a filesystem watcher error comes up, telling the user "folder is paused".

 - what you expected to happen instead, and
Nothing but a real error. Folder is paused is not an error IMHO.

 - any steps to reproduce the problem.
Well.... it happes from time to time, not on every try. 
Press the PAUSE button from a folder. Maybe some more often as usual. 
I'm sorry, it just happens when I don't think about it, so I cannot tell you how to click that button :-)

### Version Information

Syncthing Version: v1.4.1
OS Version: MacOSX Sierra

**Comment by GermanCoding** [comment]
I was able to reproduce a similar behavior on Syncthing v1.2.0-rc.4, Windows 10 v1809 (64 bit):

1. Pause a folder with watching enabled.
2. Resume the folder at any time - immediatly afterwards, a filesystem watcher error message appears in the GUI and disappears a ~second later on it's own. Nothing unusual is logged in the console (only "paused folder [...]" and "unpaused folder [...]").

I saw this behavior consistently even across restarts every time a folder is _resumed/unpaused._

**Comment by sisu4syncthing** [comment]
Hmm... 
OT: please can someone explain to me, if the tag "milestone v1.2.1" means, this bug should be fixed in the v1.2.1 rc2 already or if it is finally fixed when stable v1.2.1 comes out?

...because I could reproduce it in rc2 too and the bug was mentioned in the changelog.

The message came up, but vanished very fast (1 or 2 secs).

Thank you :)

**Comment by imsodin** [comment]
Indeed, there was two ways for this to come up, I just fixed one.

**Comment by sisu4syncthing** [comment]
So I can answer my question myself, thank you :-)
If an issue is mentioned in the changelog, it should be fixed for that paticular version.
