### ISSUE TITLE
Staggered File Versioning not always move all deleted files to .stversion directory.

### ISSUE THREAD

**Issue by sisu4syncthing** [syncthing/syncthing#5835]
Hello,

    Device-A Win7, 1.1.4
    Device-B Mac OSX Sierra, 1.1.4
    Both have Staggered File Versioning set up.
    Folder-F (pointing to C:\foo on Device A and //Users/user/bar on Device B)

Maybe related, Thread is from 2014: https://github.com/syncthing/syncthing/issues/994

I only describe shortly how to reproduce:

Step 1:

-Device A: I create a directory Test123 inside C:\foo and copy 5 files into it
-Rescan. 
-Result: Directory and files are synced to Device B completely

-Device B: I create a directory Test456 inside //Users/user/bar and copy the same files into it, I copied to C:\foo (via Samba)
-Rescan. 
-Result: Directory and files are synced to Device A completely

Step 2:

-Device A: I rename directory Test456 to Test456XXXXX
-Rescan. 
-Result: Directory Test456 is moved to .stversion on Device B with all the 5 files. Directory Test456XXXXX is created in //Users/user/bar on Device B with those 5 files.

-Device B: I rename directory Test123 to Test123XXXXX
-Rescan. 
-Result: Directory Test123 is moved to .stversion on Device A with only 1 file. Directory Test123XXXX is created in C:\foo on Device A with all 5 files.

No matter how long I wait or press the Rescan button, 4 files are missing in the .stversion directory of Device A

For Step 2, I expect 5 files to be moved to the .stversion directory, not only 1.

**Comment by AudriusButkevicius** [comment]
Try the RC, a lot of things were fixed related to that matter.

**Comment by sisu4syncthing** [comment]
Thanks! seems to work with 
v1.2.0-rc.4, Windows (64 bit)
v1.2.0-rc.4, macOS (64 bit)

**Comment by uok** [comment]
@sisu4syncthing thanks for testing and reporting back!
