### ISSUE TITLE
One way sync

### ISSUE THREAD

**Issue by bigbear2nd** [syncthing/syncthing#584]
Hello Everybody.
I really enjoy seeing this project grow and getting better.

I would like to request the feature "One way sync". I am thinking of a repo which is just collecting data, but is not repeating deletions on the other repos.

For example connecting the phone with the computer. I want to have all pictures on the pc in one directory, but i only have some pictures on the phone. So, if i delete a picture on the phone, it should stay on the pc. 

Best regards

**Comment by diedrichg** [comment]
This is the single reason I have not switched from BTSync to Syncthing. Make the one-way backup feature and I'll switch for good!

**Comment by netroby** [comment]
Syncthing should have the "Uploader" mode, that only send files to remote sync server, (Like archive only)
After send complete, the files can be deleted safe on source devices. 
But the sync server will have all the files you just uploaded.

**Comment by canton7** [comment]
Feature suggestions go on [the forum](https://forum.syncthing.net], please. 

In addition, using directives like "Syncthing should" is likely to start a confrontation: "it should do this", "no it shouldn't", etc. Instead, try phrasing your request as a suggestion.
