### ISSUE TITLE
When adding a new folder, using quotation marks around the path puts it in system32

### ISSUE THREAD

**Issue by Nnnes** [syncthing/syncthing#5843]
I tried adding a new folder, pasting in Windows's `Copy as path` from the Explorer shift-right click context menu for the path. This adds quotation marks around the copied path (`"D:\Test Folder"`), which I didn't expect to cause any problems, but —

```
17:52:06 INFO: Adding folder "Test Folder" (test-folder)
17:52:06 INFO: No stored folder metadata for "test-folder": recalculating
17:52:06 WARNING: Loading ignores: open \\?\C:\WINDOWS\system32\"D:\Test Folder"\.stignore: The filename, directory name, or volume label syntax is incorrect.
17:52:06 WARNING: Failed to create folder root directory CreateFile \\?\C:\WINDOWS\system32\"D:\Test Folder": The filename, directory name, or volume label syntax is incorrect.
17:52:06 INFO: Ready to synchronize "Test Folder" (test-folder) (sendreceive)
17:52:06 WARNING: Error on folder "Test Folder" (test-folder): CreateFile \\?\C:\WINDOWS\system32\"D:\Test Folder": The filename, directory name, or volume label syntax is incorrect.
17:52:06 INFO: Failed initial scan of sendreceive folder "Test Folder" (test-folder)
```

Thankfully, nothing was modified in `system32`. Removing the broken folder from Syncthing and re-adding it without quotation marks works as expected.

Syncthing Version: v1.2.0 [side note: the `v0.x.y` template is now obsolete]
OS Version: Windows 10

**Comment by AudriusButkevicius** [comment]
Sure, if you put invalid paths, bad things happen.
Especially when you run it as a windows service. 
But these are all your choices, syncthing just does as it's told.
