### ISSUE TITLE
index db too large and too old ldb files

### ISSUE THREAD

**Issue by amateo** [syncthing/syncthing#5844]
I'm running syncthing 1.2.0 on ubuntu 16.04 to sync a directory between three servers. Changes are always done in the same server, which replicated to the others (that are configured are read only).

In the _master_ server I have a large index db directory (about 5GB). In this directory I have a lot of ldb files (about 2600) some of the them older than a year.

Is there any way to compat this database? Can I delete this old ldb files?

**Comment by AudriusButkevicius** [comment]
Please use the forum for support.
