### ISSUE TITLE
Setting up *no* Ignore folder behave different on MAC / WIN if .stignore already exists in directory

### ISSUE THREAD

**Issue by sisu4syncthing** [syncthing/syncthing#5850]
Hi,

v1.2.0 on MacOSX 10.12.6 and Win7 64Bit

I'm using Waterfox Browser on Mac but Safari does the same here.

**Issue:**
Setting up a new folder on a Mac and a Win7 System and having already .stignore files in a pre-existing directory will do not the same. 

**What I do and how to reproduce:**

1.0. Open 2 private tabs in Browser (I do it on the Mac).  Tab1 for Win7-Syncthing-WebGui, Tab2 for Mac-Syncthing-WebGui.
2.0. Choose Add Folder on Tab1+2 
2.1. Folder Label and Folder ID: Test-Ignore  
2.2. Folder Path points to a directory containing some files of your choice, and:
```
.stfolder
.stignore
.stignore_global
.stignore_specific
```
content of .stignore
```
!.stignore_global
!.stignore_specific

#include .stignore_global
#include .stignore_specific 
```
.stignore_global and .stignore_specific only containing two slashes //
.stfolder is a 0 byte file
all files are set hidden (on windows via attributes)

2.3. click through every tab, from left to right now to set up your folder.
2.4. you can skip configuring the sharing tab, as we don't want to share something to another device.
2.5. you can skip configuring the versioning tab too
2.6. if you click onto the Ignore Patterns tab, you may or may not recognize a cursor in the textfield "Enter ignore patterns". _(This is the reason, I think different behaviour is triggered: If a cursor is seen, .stignore is configured, if no cursor is seen, no .stignore is configured)_
2.7. click to Advanced tab and activate up Watch for Changes and Ignore permissions.
3.0. now press SAVE on both tabs1+2 to save your settings.

On the Win7 syncthing, I now see the new folder with "Reduced by ignore patterns"
But not on the Mac syncthing.

4.0. If I EDIT the created folder and check the Ignore Pattern tab,
I see 
```
!.stignore_global
!.stignore_specific

#include .stignore_global
#include .stignore_specific
```
on the Win7 syncthing
and nothing on the Mac syncthing.

Maybe you can skip steps 2.3 - 2.5. and 2.7. and directly go to the Ignore Patterns tab.

**What do I expect?** 
_Same_ result from both the Win7 and Mac Browser tabs.

**Comment by imsodin** [comment]
So the short version of the problem is: A `.stignore` file in the folder root is not recognized by Syncthing on mac, correct?

**Comment by sisu4syncthing** [comment]
Sounds good to me :-)

**Comment by AudriusButkevicius** [comment]
I don't think its not not recognised. I suspect it's just a UI display bug of the "reduced by bla bla" not showing up.

**Comment by imsodin** [comment]
This part sounds like it is really not recognised:

> 4.0. If I EDIT the created folder and check the Ignore Pattern tab,
I see
[...]
on the Win7 syncthing
and nothing on the Mac syncthing.

It would be nice if someone with access to a mac could try to reproduce this.

**Comment by AudriusButkevicius** [comment]
To be honest, this doesn't seem possible, there is no platform specific handling of this, so it must be a UI issue.

**Comment by sisu4syncthing** [comment]
Maybe it is kinda OSX related, because the "bug" is browser related?

**Comment by calmh** [comment]
I can't reproduce this on Mac with Safari nor Edge -- as long as nothing is typed into the ignore patterns field on folder creation, the existing .stignore is left alone and loaded.
