### ISSUE TITLE
Hardlinks aren't maintained

### ISSUE THREAD

**Issue by LoveIsGrief** [syncthing/syncthing#5856]
Imagine this setup

System: Hard
```
root/
   unsynced/
      aFile    <=== hardlinked
   synced/
      subfolder/
         aFile  <=== hardlinked
```

System: Clone
```
root/
   synced/
      subfolder/
         aFile
```

## what happened

When moving `Clone::root/synced/subfolder` to `Clone::root/synced/newsubfolder`,  the hardlink on `Hard` wasn't maintained and `aFile` is now a separate file with a new inode.

## what you expected to happen instead

The hardlink on `Hard` to be maintained.

## any steps to reproduce the problem.

 - Create a sync folder on your source system
 - Create the folder and file to sync  
   `mkdir folderInSync && echo yahoo > folderInSync/hard`
 - Create the hardlink on source
    `cp -al folderInSync ../folderOut` 
 - Note the inodes  
   `ls -i folderInSync && ls -i ../folderOut`
 - Add the sync to your remote system
 - rename `folderInSync` on the remote system
 - Check the inodes on your source system again
   `ls -i folderInSync && ls -i ../folderOut`

They will now be different

## Version Information

Syncthing Version:  v1.2.0, Linux (64 bit)
OS Version: Ubuntu 18.04

**Comment by AudriusButkevicius** [comment]
This is working as intended and documented what is synced, what is maintained and what is not.

**Comment by LoveIsGrief** [comment]
@AudriusButkevicius I can't find the section nor can I find any mention of hardlinks

**Comment by AudriusButkevicius** [comment]
https://docs.syncthing.net/users/faq.html#what-things-are-synced

**Comment by LoveIsGrief** [comment]
Thank you. So this cannot be transformed into a feature request?

**Comment by AudriusButkevicius** [comment]
#3897 i think covers this

**Comment by LoveIsGrief** [comment]
It seems to me that that one is only concerned with modifications of the contents of the file and not the name thereof. Rename should however be atomic, so I don't think it's the same problem. If I'm correct I see these options:

 - add a mention in that issue to add moving files (without modifying their content) to the TODO list
 - separate the concerns and reopen this to handle only renaming/moving files (make that atomic and preserve the hardlink)
 - :man_shrugging:

**Comment by calmh** [comment]
Atomic renames would have been nice. However, we typically don’t “see” renames, we see that a new file has appeared and another file somewhere has disappeared. If the contents are identical we try to optimize this to a rename, but there is no guarantee. Perhaps there is room for improvement here. 

Retaining links in general is tricky because they are not universally supported and we eschew modifying files in place, instead always using a temp file.

**Comment by LoveIsGrief** [comment]
That's exactly what I'm looking for 🙂 It should be possible to batch events together and merge those that equal a move.
That would be the first step to maintaining hardlinks, since in place editing is way more difficult. -- 
 Veilig verzonden met Tutanota. Reserveer je versleutelde, advertentievrije mailbox: 
 https://tutanota.com

**Comment by calmh** [comment]
We do precisely that today.

**Comment by LoveIsGrief** [comment]
Then, as you said, there is room for improvement since simple move operations shouldn't create new inodes. The conditions that allow falling back to making a temporary file/copy might be too lax
-- 
 Veilig verzonden met Tutanota. Reserveer je versleutelde, advertentievrije mailbox: 
 https://tutanota.com
