### ISSUE TITLE
Duplicate local device (1.2.1-rc.1)

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#5859]
The local device appears as a duplicate in the GUI:

<img width="1163" alt="Screenshot 2019-07-16 at 22 01 13" src="https://user-images.githubusercontent.com/125426/61325621-70195a00-a815-11e9-912e-fe180f9c6914.png">

The hostname on the second entry is "wrong" because that's what the computer in question thinks it's named at the moment. That also indicates that these are two *different* device entries, not just a display bug.

There is indeed a device entry in the config, with a *blank* device ID:

<img width="1176" alt="Screenshot 2019-07-16 at 22 01 46" src="https://user-images.githubusercontent.com/125426/61325711-963efa00-a815-11e9-99dc-d617cd7b9567.png">

It is *not* present in the config on disk however.

**Comment by AudriusButkevicius** [comment]
This is fucked up

**Comment by calmh** [comment]
Guilty commit is ba056578ec2d9302919036920de515104a9b69c3 according to bisect, but I don't know why yet. (It's large and I'm supposedly doing other stuff than debugging this...)

**Comment by calmh** [comment]
It's in the JSON format "live" config;

```
{
  "version": 29,
  "folders": [
    {
      "id": "default",
      "label": "",
      "filesystemType": "basic",
      "path": "s2",
      "type": "sendreceive",
      "devices": [
        {
          "deviceID": "I6KAH76-66SLLLB-5PFXSOA-UFJCDZC-YAOMLEK-CP2GB32-BV5RQST-3PSROAU",
          "introducedBy": ""
        },
        {
          "deviceID": "MRIW7OK-NETT3M4-N6SBWME-N25O76W-YJKVXPH-FUMQJ3S-P57B74J-GBITBAC",
          "introducedBy": ""
        },
        {
          "deviceID": "373HSRP-QLPNLIE-JYKZVQF-P4PKZ63-R2ZE6K3-YD442U2-JHBGBQG-WWXAHAU",
          "introducedBy": ""
        },
        {
          "deviceID": "",
          "introducedBy": ""
        }
      ],
      "rescanIntervalS": 15,
 ...
}
```

**Comment by calmh** [comment]
Right, because in `loadConfigAtStartup` where the config is loaded, `myID` is not set...

**Comment by calmh** [comment]
OK, so there's two guilty commits. The suture service one does *something* that results in `myID` getting unset somewhere in the API, because the GUI shows the local device part as blank but otherwise doesn't add any odd devices. And the other part is the `lib/syncthing` refactor where we no longer set `myID` in the main package, so the config loader adds a blank device.

**Comment by imsodin** [comment]
I am taking care of the `lib/syncthing`, I haven't yet understood the service/API problem.

**Comment by calmh** [comment]
I just did... Will PR, can see if we did similar things.

**Comment by imsodin** [comment]
Ok, figured that might be the case but thought I'd take my chances that you're debugging the API. Lets see.
