### ISSUE TITLE
API endpoint to pause/resume folders

### ISSUE THREAD

**Issue by abs0** [syncthing/syncthing#5865]
Would it be possible to an an API endpoint to directly pause/resume a specific folder

I have syncthing running with various synchronised folders, one of which is periodically updated in a way that creates a bunch of temporary files which cannot practically be excluded via pattern matching (This is a cvs (no really) update of pkgsrc). I'd like a way from the commandline to pause syncthing on just that one folder, then resume it after the changes have completed)

**Comment by AudriusButkevicius** [comment]
You can already do it on the command line using the cli I think.

**Comment by AudriusButkevicius** [comment]
To be honest, you can already do it on the command line using curl and jq

**Comment by abs0** [comment]
> To be honest, you can already do it on the command line using curl and jq

Ahh great - so could this be a documentation issue? I could find calls to pause and resume based on device, but not by folder, though a quick inspection of the web client showed it used a full post of config to pause and resume individual folders

Thanks

**Comment by AudriusButkevicius** [comment]
Yeah, you can do that using jq

**Comment by abs0** [comment]
> Yeah, you can do that using jq

OK - could you point me at where in the docs it mentions an API call to pause/unpause a folder?

**Comment by AudriusButkevicius** [comment]
You get the config, mutate it using jq, post it back.

**Comment by AudriusButkevicius** [comment]
Or as I suggested, use the CLI.

**Comment by AdamBullen** [comment]
> You get the config, mutate it using jq, post it back.

For those of us who don't know what "jq" is; perhaps link to an example.

**Comment by uok** [comment]
jq as in https://www.google.com/search?q=jq+linux
for API documentation please read https://docs.syncthing.net/dev/rest.html
if you have any questions please use https://forum.syncthing.net/

**Comment by beerse** [comment]
There is also the marker-directory (.stfolder bij default). If you rename (or remove it) it has been reported that the directory will not be synced. Once it returns, the sync might be restored. I'm not sure what happens with running syncs.

On the other hand, some build or other sync systems (or backup-restore actions) can begin with (re-)moving this directory and end with restoring it.

In the end, if you manually start syncthing, removing and restoring the marker directory is the only thing you have.

**Comment by imsodin** [comment]
One can now do `PATCH` on `/rest/config/folders/*folderid*` with a `{paused: false/true}` payload: https://docs.syncthing.net/rest/config.html#rest-config-folders-id-rest-config-devices-id. That should cover this use-case.
