### ISSUE TITLE
No indication in GUI that Syncthing has been shut down

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#5866]
Minor cosmetic bug: 
There used to be a notification box to inform user that Syncthing has been shutdown. 
Since v1.2.0 it is gone and GUI looks like Syncthing still active.

Steps to recreate: click shutdown in GUI

**Comment by AudriusButkevicius** [comment]
I think there already is an open ticker about this (or there was a thread on the forum)

**Comment by uok** [comment]
you are correct, it was reported in the forum
