### ISSUE TITLE
Progress bar not visible [GUI][1.2.0]

### ISSUE THREAD

**Issue by BartQ76** [syncthing/syncthing#5867]
_Following by forum thread: https://forum.syncthing.net/t/progress-bar-missing-1-2-0/13512

I use few ST instances and noticed progress bars missing:
![obraz](https://user-images.githubusercontent.com/22952458/61433235-08593100-a933-11e9-9816-87cfe1e2f154.png)

I tracked it a bit with firefox’s buit in debugger and found something interesting:
![obraz](https://user-images.githubusercontent.com/22952458/61433253-13ac5c80-a933-11e9-95df-88e9a33a2c9d.png)

The sync process itself works normally, I don’t see any file issues. 
Moreover, I see that folder progress bar is updated only when I refresh the whole page:
![obraz](https://user-images.githubusercontent.com/22952458/61433976-fc6e6e80-a934-11e9-9b45-835b05b4ae07.png)

Even after page refresh percentage indicators next right to the progress bars remains the same:
![obraz](https://user-images.githubusercontent.com/22952458/61433822-9681e700-a934-11e9-8bc4-783e603dc0ce.png)

OS: Ubuntu 18.04.2 LTS
GUI: Firefox 68.0 @ Windows 10

**Comment by BartQ76** [comment]
I've observed that folder status is also updated when any file from the files currently processed in that folder has finished its sync.

**Comment by sisu4syncthing** [comment]
I can reproduce this in v1.2.1rc2 too.
files are showing up, but no progress bars.

**Comment by BartQ76** [comment]
Now, in version 1.2.1 I can see that progress bars are working properly again. 
Thanks and all the best to dev team.

**Comment by AndrewSav** [comment]
Still no progress bar on large files in 1.3.0

**Comment by AndrewSav** [comment]
Still an issue in 1.3.2
