### ISSUE TITLE
Pausing device no longer works

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#5873]
I paused this thing way back and it just keeps on syncing. New connections are prevented but existing ones are not terminated.

<img width="571" alt="Screenshot 2019-07-19 at 12 07 44" src="https://user-images.githubusercontent.com/125426/61527971-f607f180-aa1d-11e9-8eca-37b996c8298a.png">

**Comment by imsodin** [comment]
Regression from https://github.com/syncthing/syncthing/pull/5829, thus RC relevant. Will fix.
