### ISSUE TITLE
Folder Meta data inconsistent

### ISSUE THREAD

**Issue by xjtdy888** [syncthing/syncthing#5882]
https://github.com/syncthing/syncthing/blob/484fa0592e3579ed3ca1447a9cb87663c8ac49b4/lib/model/model.go#L468
```
if !to.Paused {
		// Creating the fileset can take a long time (metadata calculation)
		// so we do it outside of the lock.
		fset = db.NewFileSet(to.ID, to.Filesystem(), m.db)
	}
```

When we are scanning a folder with a large number of files, if we edit the folder property and trigger the folder restart, since the DB (maybe FileSet.Update) is being updated, the new NewFileSet here uses a new meta data object(load from db), At the same time, the unfinished GO thread writes the meta(Data lost, covered by new meta object). At this point our index exists, but the meta information is lost, which seems to be missing the file, and the file will never be scanned.

Reproduce:
1.  Add a very large number of directories
2.  In the scanning & indexing, modify the folder attributes such as the pull order.
3.  Maybe step 2 is repeated multiple times, each time a few seconds apart
4.  You can see that the number of files in the directory is inconsistent with the actual, and the lost files will never be synchronized.

**Comment by xjtdy888** [comment]
If we put it in the lock, it should solve the problem, but like the comment, ```Creating the fileset can take a long time (metadata calculation)```

**Comment by imsodin** [comment]
It's an easy fix, we just need to first tear the folder down, then create the fileset (outside of fmut). This is a regression from https://github.com/syncthing/syncthing/pull/5818, so RC material (sorry @calmh).

**Comment by xjtdy888** [comment]
If there is no lock, what happens to the restartFolder call multiple times, possibly generating multiple fileset instances and addingFolderLocked, and losing the previous fileset instance?
