### ISSUE TITLE
Database: consider Badger

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#5910]
It's come a long way in the years since we chose a database. The API is quite similar so a retrofit should be reasonably doable.

(This needs testing to see whether it performs better than what we have today, of course.)

**Comment by tezfair** [comment]
If you swap the database, could case sensitivity be incorporated?

**Comment by calmh** [comment]
That's almost completely unrelated, unfortunately.

**Comment by tezfair** [comment]
ok.

**Comment by AudriusButkevicius** [comment]
Do we have any conclusions on performance?

**Comment by calmh** [comment]
Nope, but I'm going to gather them now.

**Comment by calmh** [comment]
To be clear for onlookers not having seen discussion in other places, this is less about improved performance and more about potentially improved stability and using a more frequently maintained backend. I expect the performance to not be better than what we have today.

**Comment by AudriusButkevicius** [comment]
I think we're in for a shocker that it's our bugs after all on the stability front, hence looking for some performance gains as a justification :stuck_out_tongue_closed_eyes:
