### ISSUE TITLE
Limit folder parallelization, or otherwise figure out & solve performance for many folders

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#5914]
Assume two devices, 200 GIB of random data (`fakefs` on both sides), one side scanned and idle and the other one empty.

With one folder * 200 GiB it syncs in reasonable time (~30-60 minutes).

With 1000 folders * 200 MiB it takes unreasonable time (24 hours or more).

We should resolve this, either by figuring out what the problem is exactly or, as a quick fix, add a sync limiter similar to the scan limiter so that we only sync maybe 10 folders or so in parallel by default.

**Comment by blake5634** [comment]
+1
