### ISSUE TITLE
question: how to get up-to-date info via REST interface

### ISSUE THREAD

**Issue by ashmanskas** [syncthing/syncthing#5916]
I would like to run a daily cron job that will reassure me that Syncthing is still running on all three of my machines and that it is Up-to-date in the three places that I now see in the web GUI: local folders, remote device 1, and remote device 2.

I succeeded in using the REST interface to read various status information, but I was not clever enough to figure out (not quickly, anyway) how to get the basic summary information that most interests me:  is it running, and is it up-to-date.

Is there in fact a straightforward way to get this information either via the REST interface or by reading the contents of a log file?

I apologize in advance that I did not read through the GUI code before asking this question.  I did read through the REST API documentation.

**Comment by calmh** [comment]
https://docs.syncthing.net/rest/db-status-get.html

(further discussion in the forum please, not the issue tracker)
