### ISSUE TITLE
Windows defender does blocks SyncTrayzor - 02AUG2019

### ISSUE THREAD

**Issue by Kruszcontrol** [syncthing/syncthing#5923]
Apologies if this is not the correct avenue but I wanted to report that as of 02AUG2019 it appears that Windows Defender on Windows 10 (Up to date, build 17134.885) is currently blocking (or warning if it is set to warn) install of SyncTrayzor, just so people are aware.

Thanks,

**Comment by AudriusButkevicius** [comment]
Wrong repo, synctrayzor has its own repo.

**Comment by imsodin** [comment]
Also just report such false positives to Windows Defender (or whatever else is the culprit), nothing to do about it for Synctrayzor or Syncthing devs.
