### ISSUE TITLE
Upgrade server JSON generator

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#5924]
Currently the JSON served from upgrade.syncthing.net is simply the GitHub API response cached locally. This has disadvantages: it includes a shit-ton of attributes and is very large, hence we limit it to the last five releases. The last five releases are currently all RC:s, so old stable versions currently can't upgrade to anything newer stable.

We should have a tool that grabs the API data from GitHub, filters it through our structs (to remove attributes we don't understand and hence don't need to retain) and perhaps whittles it down to the last RC and the last stable. This should be a smaller response that is valid in more cases.

The end result is a JSON file that we can serve to clients (with gzip compression).

**Comment by uok** [comment]
https://forum.syncthing.net/t/automatic-upgrades-broken/13579
