### ISSUE TITLE
Web interface has connection issues

### ISSUE THREAD

**Issue by malnvenshorn** [syncthing/syncthing#5925]
The web interface has terrible connection issues with the backend. Sometimes this happens every few seconds and I have to reload the web interface. In the console of the browser I see a lot of `Failed to load resource: the server responded with a status of 403 (Forbidden)` errors.

Syncthing Version: v1.2.0
OS Version: Arch Linux
Browser Version: Vivaldi 2.6.1566.49 (Chrome/75.0.3770.145)

**Comment by AudriusButkevicius** [comment]
This looks situational to your environment, which is more of a support ticket than an issue, hence please use the forum. Usually these sort of things are caused by proxying or plugins in the browser that prevent cookies or headers.
