### ISSUE TITLE
syncing between two fast machines on a very fast lan is very slow

### ISSUE THREAD

**Issue by sneak** [syncthing/syncthing#5926]
What happened: lower than 10MiB/sec syncing between two devices

What I expected to happen: 100+MiB/sec syncing

Steps to reproduce: add new device to pool

I am syncing on a 10 gigabit lan between two machines, one macOS and one Linux, with a direct TCP connection between them, and 256GB ram and 20+ cores each.  I'm seeing approximately 5MiB/sec syncing between them.  Both have disks that can do several hundred MiB/sec in reads and writes.

Version: 1.2.0 on both
OS version: ubuntu 18.04 LTS and macOS 10.14.6 mojave

<img width="2560" alt="Screen Shot 2019-08-04 at 17 23 50" src="https://user-images.githubusercontent.com/408977/62431524-020dd780-b6dd-11e9-9619-87b68a03814d.png">

**Comment by sneak** [comment]
additional info: the linux process is running inside a docker container (syncthing/syncthing:1.2.0 from docker hub) on a zfs filesystem, very little else running on the machine.

**Comment by sneak** [comment]
it's syncing many small files, and it looks like there are only 2-4 in flight at any given time.  is there any way to tell it to download 40-50 at a time?

**Comment by calmh** [comment]
Many things can cause slowness, so some troubleshooting needs to happen. That means that at this point this is a support request and not a clearly actionable bug, hence please reopen on the forum for discussion. (My gut feeling is to double check that you're getting a TCP connection and not a QUIC one, given that docker is involved and the resulting potential lack of local discovery.)

**Comment by sneak** [comment]
It’s using `—net=host` and you can see the connection in the attached screenshot. Local discovery is working.
