### ISSUE TITLE
global@https://<domain>: Post https://<domain>: remote error: tls: illegal parameter

### ISSUE THREAD

**Issue by cromefire** [syncthing/syncthing#5938]
### Please use the correct issue tracker

Directly related to syncthing/stdiscosrv

### Does your log mention database corruption?

No

### Bug report.

I have my own private discovery server, but if I enter this into my clinet it erros with:

```
global@https://<domain>: Post https://<domain>: remote error: tls: illegal parameter
```

#### Reverse proxy

Apache reverse proxy (except):
```
Include includes/ssl.conf
Include includes/sec-headers.conf
SSLProtocol TLSv1 TLSv1.1 TLSv1.2
SSLCipherSuite "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA2$

ProxyPreserveHost On
ProxyRequests Off

RemoteIPHeader X-Forwarded-For

SSLVerifyClient optional_no_ca

RequestHeader set X-SSL-Cert "%{SSL_CLIENT_CERT}s"  # If one is available, send it pem encoded
RequestHeader set X-Forwarded-Proto "https"

ProxyPass / http://localhost:22068/
ProxyPassReverse / http://localhost:22068/
```

The apache docs describe `SSL_CLIENT_CERT`: https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#envvars

And it logs this:
```
<redacted> - - [09/Aug/2019:00:21:49 +0200] "GET /?device=<redacted> HTTP/1.1" 404 5424 "-" "Go-http-client/1.1"
```

So it seems to work

#### Inspecting the headers that the backend gets

With curl and random client cert:
```
User-Agent: curl/7.58.0
Accept: */*
X-SSL-Cert: -----BEGIN CERTIFICATE----- <redacted> -----END CERTIFICATE----- 
X-Forwarded-Proto: https
X-Forwarded-For: <redacted>
X-Forwarded-Host: <redacted>
X-Forwarded-Server: <redacted>
Connection: Keep-Alive
```

With syncthing:
```
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip
X-SSL-Cert: (null)
X-Forwarded-Proto: https
X-Forwarded-For: <redacted>
X-Forwarded-Host: <redacted>
X-Forwarded-Server: <redacted>
Connection: Keep-Alive
```

So it looks like syncthing doesn't send a client cert, but it is required to work correctly

### Version Information

Syncthing Version: v1.2.1 (latest deb)
Stdiscosrv Version: v1.0.1 (latest deb)
OS Version: Ubuntu 18.04
Browser Version: N/A

**Comment by cromefire** [comment]
Also interesting: The metrics recorded 4 inactive devices, so something seems to work

**Comment by AudriusButkevicius** [comment]
We require tls 1.3

**Comment by AudriusButkevicius** [comment]
Sorry this might be a "off the bat" closure, but we've moved past tls1.2 I think

**Comment by cromefire** [comment]
I'll try it again but I had tls 1.3 configured and just dropped it while trying, if I get it working

**Comment by AudriusButkevicius** [comment]
Regardless forum is the right media for this.

**Comment by cromefire** [comment]
But isn't it more like a bug? If I misconfigure it, it errors with `403 Forbidden` so the connection seems okay.

**Comment by calmh** [comment]
`remote error: tls: illegal parameter` is Apache telling us it doesn't like something. It may be a bug on our side, it may be a bug on Apache side, but it doesn't happen with "raw" discosrv and it doesn't happen with our public nginx setups, so it's definitely a support case until it's narrowed down.
