### ISSUE TITLE
TLS: Support x25519, reconsider elliptic curve priority in handshake

### ISSUE THREAD

**Issue by GermanCoding** [syncthing/syncthing#5940]
This issue is related to a post I created in the forums some time ago: https://forum.syncthing.net/t/android-and-tls1-2/12931/38

Foreword note: This feature request only talks about curves supported in the ECDHE handshake. This is **not** related to the elliptic curve used in the ECDSA certificate.

### Background and reasoning

With TLS 1.3 right around the corner - it will become on by default in Go 1.13 - it's time to reconsider some elliptic curves in the handshake.

Syncthing currently configures Go to support 3 curves, preferring them in the following order:

`CurvePreferences: []tls.CurveID{tls.CurveP521, tls.CurveP384, tls.CurveP256}` ([here](https://github.com/syncthing/syncthing/blob/f24676ba5ab294d3bd250479718564eb404b93b6/lib/tlsutil/tlsutil.go#L92))

Starting with TLS 1.3, clients connecting to syncthing - browsers, syncthing clients - will need to _guess_ the curves supported by the server. _(This is because the ECDHE handshake is done immediatly in the ClientHello)_. Right now, **many** [modern] applications are preferring `x25519`. I've already given examples in the forum post and I can give additonal info's if requested.

For example, in my tests Firefox guessed curves `x25519` (also known as `Curve25519`) and `P-256` as backup in the TLS 1.3 `key_share`. Chrome **only** guessed `x25519` in my test setup. If the server doesn't support at least one of the guessed groups/curves, the Server will send a `HelloRetryRequest` and the client will need to try again, this time choosing a server supported curve.

If Syncthing does not support `x25519`, this will likely cause `HelloRetryRequest`'s, which lengthen the TLS handshake and are totally unnecessary/avoidable by supporting x25519.

_Supplement: I just verified that enabling TLS 1.3 in Syncthing (via GODEBUG) and then opening the web gui with Chrome definetly caused repeated  `HelloRetryRequest`, because Chrome is convinced to use x25519._

From a security point of view, `x25519` is supposedly the "best" elliptic curve (note the quotation marks), because it was openly standardized (NIST curves are based on partly unknown values) and because it's implementation is said to be less affected by timing issues or other implementation errors. 

Additionally, it's supposedly faster compared to the NIST curves, but that is probably assuming no hardware acceleration is present.

### Go support

Major question is obviously, does Go support `x25519`? Browsing the source code of Go, it seems that support for this curve in TLS was added in Go 1.8 (see [here](https://github.com/golang/go/commit/8a11cb318f5c4c15b67ffe9ff9b2fa772bf1dd85)). So if Syncthing is fine supporting only Go 1.8 and newer, adding in `x25519` should cause _no (new) issues or compatibility problems_. Clients that do not know this curve will simply fall back to one of the three NIST curves.

### Curve priority

The last point of my feature request concerns the priority of the elliptic curves, because these affect what is used in most enviroments.

This is the current default curve preference, found in the latest Go source code:

`var defaultCurvePreferences = []CurveID{X25519, CurveP256, CurveP384, CurveP521}`

Syncthing currently misses x25519 and has the other curves exactly the other way around. There's also this comment in the syncthing source code:

> // We want the longer curves at the front, because that's more
		// secure (so the web tells me, don't ask me to explain the
		// details).

I, personally, disagree with this. I support curve priority order of the Go team - x25519 and P-256 are both very secure, together widely supported curves. The other two are (mostly) useless junk that hardly adds in any security benefit. The only real difference is the bit-level-security (number of operations required for a brute-force). Assuming you can break P-256, it's not because of the 128 bit security level, but because of some other weakness that will likely affect P-384 and P-521 too (because they were likely generated using the same unknown constants).

Having x25519 the curve at the front (= the preferred) would be my favored choice, because of the reasons above. And if a 128-bit-security curve is preferred, there's no real reason to place a 256-bit-curve (P-521) right behind it - bit-level-security is not the important factor here and if it were, an attacker could just break x25519. Therefore I totally favor the curve priority order that the Go team has choosen as default.

I understand that this is only my personal, half-informed opinion, but at least reconsider the current curve priority.

### Summary (TL;DR)

1. Add support for `Curve25519/x25519`, preferably putting it at the front.
2. Reorder the priority of the other three NIST curves.

I can _probably_ do a Pull Request with the needed changes in the next few days, altough I've zero experience in Go (changes should be minimal).

### Version Information

TLS tests performed with Syncthing Version: v1.2.1 (both with TLS 1.2 and TLS 1.3)
TLS tests performed with OS Version: Windows 10 v1903
TLS tests performed with Browser Version: Firefox 68.0.1, Chrome 76.0.3809.100

**Comment by calmh** [comment]
With TLS 1.3 the cipher suites are not configurable in Go. Thus this is either a non-issue or an issue on the Go standard library, but not something we can affect.

**Comment by calmh** [comment]
That said if we are missing out on curves today we should fix that for TLS 1.2, I suspect our settings are simply a left-over from an earlier time when further curves were not supported by Go.

**Comment by GermanCoding** [comment]
This is not related to cipher suites. In Go you can configure the preferred elliptic curves, which are used (or not used) in all TLS ECC operations. The preferred elliptic curve setting seems to affect **both** TLS 1.2 and TLS 1.3.

**Comment by lwilmen** [comment]
Since this patch has been applied, this has broken the directions as published in https://docs.syncthing.net/users/stdiscosrv.html with respect to connecting a Syncthing instance to a syncthing custom discovery server. Can this documentation be updated (I'm assuming it's the ssl_ciphers that needs to be revisited).

**Comment by GermanCoding** [comment]
The PR that matches this issue has changed nothing in that regard. Could you please explain what is broken specifically? The nginx config from the docs is slightly outdated, but I can't find anything there that needs an immediate change.

**Comment by lwilmen** [comment]
Apologies. After doing some more tracking, I found the bug responsible to be referred to by https://github.com/openssl/openssl/issues/10007 - an issue between Go TLS 1.3 and openssl < 1.1.1d. For those Googling through trying to find this - handshake issues similar to the following appear in the NGINX error log:

> 2019/10/20 05:24:45 [info] 16739#16739: *7 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking, client: 1.2.3.4, server: 0.0.0.0:443
> 2019/10/20 05:24:45 [info] 16738#16738: *8 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking, client: 1.2.3.4, server: 0.0.0.0:443

Hopefully this helps someone else in the future!

**Comment by GermanCoding** [comment]
Yeah no worries, that bug is known to me (the link to the issue you posted was actually created by me), gladly it's already fixed in openssl 1.1.1d. I know for a fact that debian ships a patched version in stable, but the Ubuntu repo suggests they're still shipping something outdated and I've no idea how it looks with other distributions.

I considered posting and advisory this in the forums to raise awareness about this bug, but only if other people are affected. I think I'm going to just do that.
