### ISSUE TITLE
how to use peer to peer network

### ISSUE THREAD

**Issue by linruiand** [syncthing/syncthing#5945]
As title , syncthing is a peer to peer file transfer tool,  now that it can be link peer to peer even though client is in diffent NAT network, so it is real that one client can use other client's network , and they can be proxyed  by each other. 
for example ,yours client is in american , my client is in china , I can use your network to access Internet

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
