### ISSUE TITLE
Experience on a NAS /w docker

### ISSUE THREAD

**Issue by willow512** [syncthing/syncthing#5946]
Hello, I have attempted to use syncthing on docker on a synology NAS, I thought I'd take the time to report back that isn't quite there yet. Consider this feedback I'm not looking for solutions.

My case was backup of a laptop with 5 separate folders together about 40k subfolders and 200k or 300k files. 

After a while I started receiving errors on the NAS about running out of free inode watchers. And the whole system just stopped responding, I would try to refresh the page but nothing would happen. Meaning that the page would reload but the ajax (?) refreshes stopped responding. I guess the http server is up but the syncthing engine has died. I'd need to restart the docker image. But it'd give the same error and die again. I tried telling it to stop watching the folders (As there really is no need for that in this specific case)  But either that isn't stored between sessions or the dead syncthing engine was no longer able to save those changes.

Ended up removing the docker container from my nas and uninstalling the software from my laptop.

Which is a shame because I thought we were really going to be great friends :(

**Comment by AudriusButkevicius** [comment]
Feedback happens on the forum.
