### ISSUE TITLE
Question: Millions of files?

### ISSUE THREAD

**Issue by aliensojurner** [syncthing/syncthing#5951]
I am currently using another bittorrent protocol system but their support is becoming more and more lacking. I'm wondering how this product would handle a system that has millions of files to index? While not constantly syncing millions of files, our needs would be that it's able to index millions of files but then sync probably only a few thousand a day. Does anybody have any experience with this?

**Comment by imsodin** [comment]
Please ask questions on [the forum](forum.syncthing.net).
