### ISSUE TITLE
Why did I open the software, only 8384 port display?

### ISSUE THREAD

**Issue by DoLolitingyu** [syncthing/syncthing#5963]
My OS is Windows Server 2012, software version is 1.1.1.It's only have 8384 port when I open the software.According to the document, there should be have 22000 and 21027 port.[图片][图片][图片]

Thank you......

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
