### ISSUE TITLE
Can't software be used only on the Intranet?

### ISSUE THREAD

**Issue by DoLolitingyu** [syncthing/syncthing#5964]
Can't software be used only on the Intranet? Can't they find each other on the Intranet?
Thank you！^_^

**Comment by DoLolitingyu** [comment]
Does the Intranet only open ports 22000, 21027, 8384?

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
