### ISSUE TITLE
Relay cannot be disable, or use specified relay site.

### ISSUE THREAD

**Issue by kuanyui** [syncthing/syncthing#5969]
### Please do post actual bug reports and feature requests.

For security and private concerning (Especially I definitely my data transmitted through some arbitrary countries, such as China), I want to totally disable relays on all my Syncthing nodes. So I setup all my Syncthing nodes by following steps:

Actions -> Advanced -> Options -> Uncheck "Relays Enabled"

Then restart Syncthing.

However, **I found Syncthing still can sync my files via Internet with the nodes behind a router**. I also cannot see any detailed information about "how were data transmitted" (NAT only? Relay?) except for public IP address.

### Questions
1. How to make my nodes to use some specified relays?
2. Or more simple: how to disable relays completely? (and use LAN only to sync)
3. Is any way to see transmission information (sync through which method (LAN or relay) / which relay / relay's domain) on Web GUI?

### Version Information

Syncthing Version: v1.2.1, Linux (64 bit) 
OS Version: Manjaro Linux (rolling upgrade)

**Comment by calmh** [comment]
Disabling relaying does indeed disable relaying; at least I can find no indication of the opposite. We have multiple other NAT penetration methods though. You can see the connection type in use by hovering on the address of the connected device. The rest is a support discussion, so far, so please use the forum.
