### ISSUE TITLE
identical files are marked as "Out of sync"

### ISSUE THREAD

**Issue by seidler2547** [syncthing/syncthing#597]
I have a PC and a NAS, and I wanted to sync a larger directory from PC to NAS. To speed up the initial sync, I rsync'ed the directory to the NAS. I set the PC to readonly (Master Repository). I added both directories to both nodes. Syncthing keeps complaining about ~90% "Out of Sync" on the master node.
 When I open the "Out of Sync Items", it shows Directories as "Update" and other files as "Sync with a downward arrow".

Just to make sure, here is one of the files that are marked as "out of sync":
#### PC:

```
[stefan@abraham Personal]$ ls -ln 'Church/Publicity/Organisation/Rotas/Rotas 2007/Service Rota July_Aug_2007.xls'
-rw-r--r-- 1 1000 100 19456 Jul  3  2007 Church/Publicity/Organisation/Rotas/Rotas 2007/Service Rota July_Aug_2007.xls
[stefan@abraham Personal]$ sha512sum 'Church/Publicity/Organisation/Rotas/Rotas 2007/Service Rota July_Aug_2007.xls'
cce7bb372c767ff4641351003d4740ecec45a845cca787881f603f479e92ee66cb7801bd7b2183f34167ea8ce6169f75fb42fc2ed541069e9ae2fecef7a475ce  Church/Publicity/Organisation/Rotas/Rotas 2007/Service Rota July_Aug_2007.xls
```
#### NAS:

```
root@marsboard:/media/data/Backups/BTSync/abraham.Personal# ls -ln 'Church/Publicity/Organisation/Rotas/Rotas 2007/Service Rota July_Aug_2007.xls'
-rw-r--r-- 1 1000 100 19456 Jul  3  2007 Church/Publicity/Organisation/Rotas/Rotas 2007/Service Rota July_Aug_2007.xls
root@marsboard:/media/data/Backups/BTSync/abraham.Personal# sha512sum 'Church/Publicity/Organisation/Rotas/Rotas 2007/Service Rota July_Aug_2007.xls'
cce7bb372c767ff4641351003d4740ecec45a845cca787881f603f479e92ee66cb7801bd7b2183f34167ea8ce6169f75fb42fc2ed541069e9ae2fecef7a475ce  Church/Publicity/Organisation/Rotas/Rotas 2007/Service Rota July_Aug_2007.xls
```

I tried restarting, removing and re-adding the repos, but nothing helps.

**Comment by janlimpens** [comment]
I am in a very similar situation and hitting the override button does not seem to do anything, The button also does not go away.

**Comment by xordspar0** [comment]
@calmh Did any part of this get implemented? What ideas do you have for handling this better? I would be happy to implement some or all of it.
