### ISSUE TITLE
Keep old verison in debian/ubuntu repository

### ISSUE THREAD

**Issue by aarnaud** [syncthing/syncthing#5974]
Hi,

Can you keep older version in the repository ? 
Our use case is to keep running our configuration with a specific version. 
We try to keep syncthing up to date but some time we don't have time.

Anyway for this time we upgrade to 1.2.1 because our config still working on this version.

### Version Information

Syncthing Version: v1.4.1
OS Version: ubuntu 18.04

**Comment by calmh** [comment]
We keep a few versions back available, but not all or forever. If you have a specific requirement it’s probably best you save the deb file yourself. It has hardly any dependencies and is easy to deploy on its own.
