### ISSUE TITLE
Large File Not Transferring

### ISSUE THREAD

**Issue by Jyt6Sham1** [syncthing/syncthing#5977]
I have Syncthing set up to sync photos and videos from my phone camera to my computer. It has so far transferred everything except a video I filmed a month ago. At first, I thought it was simply too large at 900 MB, but I see people transferring much larger 300 GB files just fine.

I'm using a BlackBerry Key2 and trying to transfer to a laptop running Linux Mint.

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
