### ISSUE TITLE
UNIX socket permission bits

### ISSUE THREAD

**Issue by andreymal** [syncthing/syncthing#5979]
I tried to use a UNIX socket with nginx, but the default permission bits for the socket are 644:

```
$ ls -l syncthing.sock 
srwxr-xr-x 1 syncthing syncthing 0 авг 27 15:32 syncthing.sock
```

Nginx uses `www-data` user, and that's why it can't use this UNIX socket and prints "Permission denied".

I can change these permission bits using umask 0007 to make it work, but this solution is not suitable in all cases.

It would be nice to have an option that controls socket permission bits (and maybe even a group).

**Comment by calmh** [comment]
API wise we'd need to chmod it after creating it by listening. I'd suggest doing the same from the outside, but that's of course not 100% stable as Syncthing will recreate it if the listening config is changed etc.

**Comment by ahmedaabouzied** [comment]
@calmh  Hey can I work on this ?

**Comment by calmh** [comment]
Please do, no permission required :)

**Comment by bjoe2k4** [comment]
@ahmedaabouzied any update on this?

**Comment by ahmedaabouzied** [comment]
@bjoe2k4 sorry for the late reply.
No, sadly I couldn't really figure it out

**Comment by kroppt** [comment]
Never contributed before, but I also took a look and was stumped. Some questions about implementation that come to mind are:
- how is the option implemented (how to decide which files to apply to, how to decide which mode to use)
- would the permissions need to change in the FileInfo database or only where we actually modify the permissions
- when @calmh mention "listening", are you referring to event subscriptions
- I could not find where the default permissions for a file were set, so I don't even know why they are 0644 in the first place

**Comment by calmh** [comment]
This is the listening part: https://github.com/syncthing/syncthing/blob/5823e7a5cea18e489928dd3055bbabc918a8a3ef/lib/api/api.go#L185

**Comment by kroppt** [comment]
@andreymal 
If you have any feedback on the implementation, now's the time; it's ready for review.

**Comment by andreymal** [comment]
@kroppt lgtm
