### ISSUE TITLE
(De)select all not working in add device dialog

### ISSUE THREAD

**Issue by Redsandro** [syncthing/syncthing#5980]
:information_source: The _"Select All"_  and _"Deselect All"_ buttons in **Share Folders With Device** are not working when adding or accepting a new _device_.

:warning: They _are_ working when adding or accepting a new _folder_.

![image](https://user-images.githubusercontent.com/1702193/63778020-6559e680-c8e4-11e9-9357-bc491e7e97fb.png)

### Version Information

Syncthing Version: v1.2.1
OS Version: Ubuntu 18.04.3
Browser Version: Google Chrome 76.0.3809.100

**Comment by GermanCoding** [comment]
Noticed the same behavior in the 'Edit Device' dialog just recently (tested up to v1.2.2-rc.3). Reproduced on SyncTrayzor's CEF and Firefox 68.0.2.
