### ISSUE TITLE
GUI doesn't connect with Syncthing Daemon while scanning in v1.2.1

### ISSUE THREAD

**Issue by Redsandro** [syncthing/syncthing#5981]
I'm scanning a big folder (~500 GB) that's already shared on a couple of other machines. The folder's contents are the same. It's just creating the indexes. This makes sense.

However, in the GUI, no connection info or status info is shown on the shared folders or devices.

No connection info:

![image](https://user-images.githubusercontent.com/1702193/63785324-7577c300-c8f0-11e9-872c-a96c3d91e52f.png)

No status:

![image](https://user-images.githubusercontent.com/1702193/63785216-3e091680-c8f0-11e9-9480-3e319fbe6fc8.png)

I cannot see what is scanning, how much is left, or pause the scanning to do some other maintenance.

This is new. With the other devices, I had no problem using the GUI to continue performing tasks or track the progress of the current scan(s), while a big scan was in progress.

These other machines run version 1.1.3 and (also) 1.2.1.

I have no other means of seeing the progress (correct?) but the `LOG` file shows syncthing is still enthusiastically creating and removing tables.

My guess is that I just need to wait for the massive scan to be done, and it will become responsive again. But I have not observed this issue before. It feels like a regression. I'm thinking the previous scans on the other devices might have been using a version <= 1.2.0, and they have automatically upgraded to 1.2.1 from the repo after the fact.

### Version Information

Syncthing Version: v1.2.1
OS Version: Ubuntu 18.04.3
Browser Version: Google Chrome 76.0.3809.100

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
