### ISSUE TITLE
Firewall UFW rule does not work

### ISSUE THREAD

**Issue by Redsandro** [syncthing/syncthing#5982]
Is this code uptodate with syncthing v1.2.1?
https://github.com/syncthing/syncthing/blob/0832285d79396ad26c2106423277c8bfb3c5405d/etc/firewall-ufw/syncthing#L1-L4

When [adding the rule](https://docs.syncthing.net/users/firewall.html#uncomplicated-firewall-ufw) to ufw, other devices in my network are (still) not able to accept incoming device pair requests from the new device. The "Add Device" dialog shows up, but adding is not possible. The device shows up in the list, but after a minute it disappears.

:information_source: Once I disable my firewall, connections are made successfully.

### Version Information

Syncthing Version: v1.2.1
OS Version: Linux Mint 19.2 Cinnamon x86_64 (Based on Ubuntu 18.04.2)
Browser Version: Google Chrome 76.0.3809.100

**Comment by calmh** [comment]
Your problem is something different and not related to the ufw file (which is correct). I suggest a forum thread if you want help narrowing it down.
