### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by G-zhanghao** [syncthing/syncthing#5983]
# github.com/syncthing/syncthing/lib/db
../../lib/db/lowlevel.go:55:3: unknown field 'BlockCacheEvictRemoved' in struct literal of type opt.Options
# github.com/syncthing/syncthing/lib/connections
../../lib/connections/quic_dial.go:97:34: cannot use &quicTlsConn literal (type *quicTlsConn) as type tlsConn in field value:
	*quicTlsConn does not implement tlsConn (wrong type for ConnectionState method)
		have ConnectionState() handshake.ConnectionState
		want ConnectionState() tls.ConnectionState
../../lib/connections/quic_listen.go:159:39: cannot use &quicTlsConn literal (type *quicTlsConn) as type tlsConn in field value:
	*quicTlsConn does not implement tlsConn (wrong type for ConnectionState method)
		have ConnectionState() handshake.ConnectionState
		want ConnectionState() tls.ConnectionState

**Comment by AudriusButkevicius** [comment]
Use the build instructions provided on the documentation site.
