### ISSUE TITLE
build.sh build error

### ISSUE THREAD

**Issue by G-zhanghao** [syncthing/syncthing#5984]
lib/connections/quic_dial.go:81:39: too many arguments in call to session.OpenStreamSync
	have (context.Context)
	want ()
lib/connections/quic_dial.go:91:34: cannot use &quicTlsConn literal (type *quicTlsConn) as type tlsConn in field value:
	*quicTlsConn does not implement tlsConn (wrong type for ConnectionState method)
		have ConnectionState() handshake.ConnectionState
		want ConnectionState() tls.ConnectionState
lib/connections/quic_listen.go:120:34: too many arguments in call to listener.Accept
	have (context.Context)
	want ()
lib/connections/quic_listen.go:130:38: too many arguments in call to session.AcceptStream
	have (context.Context)
	want ()
lib/connections/quic_listen.go:138:39: cannot use &quicTlsConn literal (type *quicTlsConn) as type tlsConn in field value:
	*quicTlsConn does not implement tlsConn (wrong type for ConnectionState method)
		have ConnectionState() handshake.ConnectionState
		want ConnectionState() tls.ConnectionState

**Comment by calmh** [comment]
You have the wrong versions of dependencies, which means you are not using modules -- too old Go or incorrect setup. Please follow https://docs.syncthing.net/dev/building.html in detail, and if that doesn't work provide all the information on your setup and what precisely you're doing and we'll look into it.

As the build works for us and many, many others I'm going to close this. Please feel free to discuss on the forum (https://forum.syncthing.net) for further help.

**Comment by G-zhanghao** [comment]
go run build.go
github.com/syncthing/syncthing/lib/db
github.com/syncthing/syncthing/cmd/ursrv
github.com/syncthing/syncthing/lib/connections
# github.com/syncthing/syncthing/cmd/ursrv
cmd/ursrv/main.go:185:20: undefined: pq.Int64Array
cmd/ursrv/main.go:218:27: undefined: pq.Int64Array
# github.com/syncthing/syncthing/lib/db
lib/db/lowlevel.go:110:3: unknown field 'BlockCacheEvictRemoved' in struct literal of type opt.Options
# github.com/syncthing/syncthing/lib/connections
lib/connections/quic_dial.go:81:39: too many arguments in call to session.OpenStreamSync
	have (context.Context)
	want ()
lib/connections/quic_dial.go:91:34: cannot use &quicTlsConn literal (type *quicTlsConn) as type tlsConn in field value:
	*quicTlsConn does not implement tlsConn (wrong type for ConnectionState method)
		have ConnectionState() handshake.ConnectionState
		want ConnectionState() tls.ConnectionState
lib/connections/quic_listen.go:120:34: too many arguments in call to listener.Accept
	have (context.Context)
	want ()
lib/connections/quic_listen.go:130:38: too many arguments in call to session.AcceptStream
	have (context.Context)
	want ()
lib/connections/quic_listen.go:138:39: cannot use &quicTlsConn literal (type *quicTlsConn) as type tlsConn in field value:
	*quicTlsConn does not implement tlsConn (wrong type for ConnectionState method)
		have ConnectionState() handshake.ConnectionState
		want ConnectionState() tls.ConnectionState
exit status 2
exit status 1

**Comment by G-zhanghao** [comment]
go version
go version go1.12.5 linux/amd64

**Comment by AudriusButkevicius** [comment]
Read what was written above, you need to use Go modules.
