### ISSUE TITLE
why on earth does a sync program not. sync. the. bloody. folder.

### ISSUE THREAD

**Issue by artlessknave** [syncthing/syncthing#5989]
set it up, and its "out of sync" well no flipping duh, you're supposed to sync it, that's the whole point.
that is so INFURIATING. i don't CARE that they are out of sync. make them in sync to whatever was the last modified, the contents don't matter, being in sync is what matters.

and while I'm already venting, why the hell does it make 1000's of "conflict" files. if its not the newest version frikking delete it and put the newest version.

the program *appears* like it should do what i want and then doesn't - that is, sync a folder.

**Comment by AudriusButkevicius** [comment]
It's even more infuriating when people don't read the issue template.
