### ISSUE TITLE
Usage-reported transfer stats are meaningless

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#5995]
The reported transfer stats use the unit of "blocks" which made sense at the time. Now, however, a block can be any size at all between 128k and 16M, and are slowly getting bigger on average as this is rolled out. Hence the graph is mysteriously shrinking:

<img width="1147" alt="Screen Shot 2019-09-04 at 09 32 40" src="https://user-images.githubusercontent.com/125426/64234819-5e8c2e80-cef7-11e9-8223-3ed1e8a966fe.png">

The ratio between the values *might* have some validity (but I'm not 100% sure), but in general for this to be useful we need to switch to byte counts instead.

**Comment by AudriusButkevicius** [comment]
:(
