### ISSUE TITLE
Unreal CPU usage

### ISSUE THREAD

**Issue by Prosecutor** [syncthing/syncthing#6002]
Hello!

I'm facing problem with CPU usage (http://prntscr.com/p3pcmr http://prntscr.com/p3pea7)

Is there any way to 'fix' it? I've increased the re-scan interval, increased the priority of mumble and adjusted hashers parameter in advanced settings to 1. Before those configurations, the load was increasing straight untill server is not reachable(150-200 CPU load), now it's shows 15-30 of CPU load). Maybe is there any way to make it lower?

Regards

**Comment by imsodin** [comment]
Please use https://forum.syncthing.net/ for support.
