### ISSUE TITLE
.stignore include non-existen file

### ISSUE THREAD

**Issue by SANSoft-ru** [syncthing/syncthing#6003]
Syncthing Version: v1.2.2
OS Version: Windows 10 x64
Browser Version: Google Chrome

Syncthing crashes while found in .stignore file #include clause with not yet existing file.
May you change behaviour for this case: if so, read this clause as comment (ignore it)?

Later this file is copyed by sync and all works fine. Error only in initial syncing

**Comment by calmh** [comment]
Crashes how? Backtrace?

**Comment by SANSoft-ru** [comment]
http-GUI blanked, then after refresh one its flickers some seconds, in console log too many lines with "file not found" string.

**Comment by calmh** [comment]
That does not sound like a crash to me, that sounds like some unrelated GUI issue (possibly?) combined with the folder stopping due to the error in loading ignore patterns...

**Comment by SANSoft-ru** [comment]
may be... I just asked You for change this behaviour: Ignore these lines in .stingnore file. After getting this file in #include clause, syncthing may do orders in it

**Comment by calmh** [comment]
Not syncing when the ignore patterns can't be loaded is the intended behavior. If you temporarily want to not load an #included file you can comment it out. We don't know the intention of the #include and it's absolutely not safe to just pretend there wasn't an include line if the file is missing, sorry.

**Comment by SANSoft-ru** [comment]
Also include file in Russian native code page (Win-1251) won't work. Only in UTF-8 codepage with BOM (Bite order mark). Please add this notice in documentation page. I spended about 10 minutes to understand this)))
