### ISSUE TITLE
1.2.2.2 persistent immediate crashing

### ISSUE THREAD

**Issue by bjmuld** [syncthing/syncthing#6006]
Previously, running 1.2.2 via F-Droid.  Updated to 1.2.2.2 via F-Droid, and now Syncthing is repeatedly crashing and Android is reporting the app's repeated failure and offering to kill it.

Tried uninstalling and reinstalling 1.2.2.2 via F-Droid to find the same problem.
Tried again uninstalling and reinstalling 1.2.2 via F-Droid and have a stable app again.

### Version Information

Syncthing Version: v1.2.2.2
OS Version: Android 9 (Motorola G7 Power/ Kernel 4.9.112-perf+)

**Comment by imsodin** [comment]
Wrong repo, see https://github.com/syncthing/syncthing-android/issues/1403
