### ISSUE TITLE
Changed file in receive-only folder cannot be ignored

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing#6008]
Hi, 

Currently on the phone, so I hope its good to start with the reference. Feel free to edit/add my post if necessary :).

Raised according to 
- https://forum.syncthing.net/t/problem-with-post-ignoring-a-file-sendonly-recvonly/13749/2

Thanks for your help on this.

**Comment by imsodin** [comment]
Steps to reproduce:

1. Create receive-only folder.
2. Create file therein -> revert button appears.
3. Create ignore patterns to ignore the created file.

Result: Revert stays.

Expected: File gets ignored, everything is back to normal, no revert.
