### ISSUE TITLE
Encoding issue with folder-label and folder-id

### ISSUE THREAD

**Issue by lkwg82** [syncthing/syncthing#6017]
I experience a wrong encoding in the logs

currently:
```
... Ready to synchronize "ordner-groÃ" (ordner-groÃ) 
```

it should be
```
... Ready to synchronize "ordner-groß" (ordner-groß) 
```

### Version Information

Syncthing Version: v1.2.2
OS Version: Ubuntu 18.04

**Comment by AudriusButkevicius** [comment]
What logs? Who creates the logs?

There is an issue template for a reason, and people are expected to follow it.

**Comment by lkwg82** [comment]
hi Audrius,

syncthing creates the logs. I have copied this line from the logs systemd is collecting.

What do think I missed from the template which is important to u?

**Comment by AudriusButkevicius** [comment]
I don't think syncthing creates files, it logs to the console. Are you talking about systemd units shipped together? Is your locale on your machine setup correctly?

I would not be surprised if its a systemd issue that cannot be worked around (judging by quick googling)

**Comment by calmh** [comment]
Syncthing log output is UTF-8. This should ideally also be the encoding in use by the system.

**Comment by lkwg82** [comment]
I did not consider and will check.

**Comment by lkwg82** [comment]
Not a bug with syncthing. Seems to be in systemd or further.
