### ISSUE TITLE
Suggest to add directory and file browsing

### ISSUE THREAD

**Issue by augar5** [syncthing/syncthing#6018]
#4988 # Suggest to add directory and file browsing
It is recommended to add directory and file browsing functions to the GUI client and support manual synchronization. Like a cloud storage service.

**Comment by AudriusButkevicius** [comment]
You can already do that by exposing that folder using other software. Syncthing is for syncing, not file management.

**Comment by augar5** [comment]
This is just a suggestion. Since it can't, forget it.

**Comment by augar5** [comment]
> 您可以通过使用其他软件公开该文件夹来实现此目的。同步是用于同步，而不是文件管理。

This is just a suggestion. Since it can't, forget it.

**Comment by augar5** [comment]
> You can already do that by exposing that folder using other software. Syncthing is for syncing, not file management.

This is just a suggestion. Since it can't, forget it.
