### ISSUE TITLE
[feature request] Downloading files on demand (like Syncthing Lite)

### ISSUE THREAD

**Issue by solarkraft** [syncthing/syncthing#6020]
Hey, 

So far I'm a huge fan of Syncthing. 
I would love to sync my complete library with it. But that includes many Gigabytes of data, which I would like to be able to access on the go, but not have on my phone and laptop permanently. 

My current planned "workaround" would be not adding folders with large files I don't want permanently synced and accessing those through another protocol like SFTP, but that will throw away a lot of the "all in one place"- and peer-to-peer elegance of Syncthing :(

Wouldn't it be amazing to be able to mark folders as "download on demand", so files are only pulled from a device that has them when you access them? 

I know such a feature would be a bit of a departure from the typical Syncthing model, but Syncthing Lite demonstrates that it is possible. Having it in Syncthing proper would ensure availability on all platforms and make me very happy.

**Comment by AudriusButkevicius** [comment]
Syncthing lite by definition is not compatible with all the platforms (because not all of them support virtual filesystems) hence you should keep using that.

**Comment by solarkraft** [comment]
The desktop operating systems all support virtual file systems via FUSE and both Android and iOS support have file provider APIs (while you can also mount FUSE file systems on Android). 

I get that this feature may be out of scope for the main project (it would involve the virtual file system implementations, after alll), but do you have pointers regarding implementing something like this on my own with the Go implementation (using both in combinations would be pretty terrible for reasons you can probably imagine)?

Would you be open to have some features added to the main program to handle on-demand file down-/uploading of files?

I'd be very happy to be able to use Syncthing for my use case, instead of having to resort to something proprietary like Resilio Sync.

**Comment by calmh** [comment]
I don't think it fits in Syncthing itself given how involved it will be to set up on the end users' computers. What I could imagine is some sort of aid for it via the API and an external tool. The API could be something to say "hold downloads for this folder" and then "now download this file". The could potentially be implemented by hooking into the pulling mechanism in folder_sendrecv.go to  add a filtering step where it already does queuing and filtering by ignores and such.
