### ISSUE TITLE
Percentage more than 100 % and too long blue line

### ISSUE THREAD

**Issue by merlinuwe** [syncthing/syncthing#6023]
It is possible, that I see percentages over 100 %. See screenshots.

Mentioned over a year ago ;-) , now the screenshot: The blue line is too long.

For both see screenshots.

### Version Information

Syncthing Version: v1.2.1 (and before; likely1.2.2. too)
OS Version: Android on Honor 10 with EMUI 9.1.0 (latest) but also seen on my further Wiko Robby Smartphone
Browser Version: (if applicable, for GUI issues)

![Screenshot_20190909_081706_com github catfriend1 syncthingandroid](https://user-images.githubusercontent.com/4138869/65390965-a9190200-dd63-11e9-8c6b-60b953edca82.jpg)
![Screenshot_20190906_075715_com github catfriend1 syncthingandroid](https://user-images.githubusercontent.com/4138869/65390966-a9b19880-dd63-11e9-848e-d8b26238261e.jpg)
![Screenshot_20190906_075731_com github catfriend1 syncthingandroid](https://user-images.githubusercontent.com/4138869/65390967-a9b19880-dd63-11e9-93e8-591cddb9f52d.jpg)
![Screenshot_20190906_075739_com github catfriend1 syncthingandroid](https://user-images.githubusercontent.com/4138869/65390968-a9b19880-dd63-11e9-8ea8-650530d62f20.jpg)
![Screenshot_20190906_075750_com github catfriend1 syncthingandroid](https://user-images.githubusercontent.com/4138869/65390969-a9b19880-dd63-11e9-9733-e03b4e783ce1.jpg)
![Screenshot_20190909_081652_com github catfriend1 syncthingandroid](https://user-images.githubusercontent.com/4138869/65390970-a9b19880-dd63-11e9-9cac-dd675a7ff6c6.jpg)
![Screenshot_20190909_081702_com github catfriend1 syncthingandroid](https://user-images.githubusercontent.com/4138869/65390972-aa4a2f00-dd63-11e9-9156-dd053ab1b778.jpg)

**Comment by AudriusButkevicius** [comment]
I am pretty sure this is a dupe. If a file which we are downloading gets deleted as we download it, this is what happens.

**Comment by uok** [comment]
https://github.com/syncthing/syncthing/issues/4570
