### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by augar5** [syncthing/syncthing#6024]
For failed items, add the ability to override local files with remote files.
![QQ截图20190923083711](https://user-images.githubusercontent.com/54491093/65396895-e8843480-dddd-11e9-83e1-28d0db35d243.png)

**Comment by augar5** [comment]
> For failed items, add the ability to override local files with remote files.
> ![QQ截图20190923083711](https://user-images.githubusercontent.com/54491093/65396895-e8843480-dddd-11e9-83e1-28d0db35d243.png)

This is due to the case of the file name

**Comment by AudriusButkevicius** [comment]
This shouldn't be an issue in the first place and there is an issue tracking that.
