### ISSUE TITLE
In fedora 31 syncthing does not start at sign in. 

### ISSUE THREAD

**Issue by tuxedotje** [syncthing/syncthing#6026]
try to open the GUI, in Firefox (on Fedora 31 beta)
Cannot open ...
start syncthing at command line, no mention of other instance of syncthing already running. 
Syncthing v1.2.2, Linux (64 bit)"Fermium Flea"

**Comment by AudriusButkevicius** [comment]
Please read the issue template. Issue tracker is not the place for support.

**Comment by tuxedotje** [comment]
this is not a question for support, it is a bug. on fedora 31 beta syncthing is not starting at login.

**Comment by AudriusButkevicius** [comment]
Even if it is, we are not the ones packaging the rpms, so reach out to your distribution.
