### ISSUE TITLE
Folder shows as "Syncing" when there is no data transfer

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#6027]
This issue is a companion to https://forum.syncthing.net/t/i-want-to-get-rid-of-the-syncing-status/13793/18. Basically every so often a user gets confused by Syncthing saying it's syncing, while they made sure manually that the data is already the same. The proposed solution is an additional state before "Syncing", while Syncthing is traversing the database to make a list of stuff it needs etc. Details in the forum or PR (incoming).

**Comment by AudriusButkevicius** [comment]
Just preparing?
