### ISSUE TITLE
Syncthing not detecting updates and new files from Cataclysm DDA

### ISSUE THREAD

**Issue by Nerdy314159265** [syncthing/syncthing#6030]
I use Syncthing to sync save data across multiple machines with various games. Recently I noticed that the service that detects file updates and new files being added to a synced directory isn't detecting updates in Cataclysm DDA for some reason.

I would expect that whenever I save the game that Syncthing would detect the mass of changed and new files, then immediately start syncing them.

I'm unsure if it's the volume of files (Cataclysm can update and create thousands per save) or how they interact in particular but it's not functioning like other games.

### Version Information

Syncthing Version: v1.2.2
OS Version: Windows 10

**Comment by AudriusButkevicius** [comment]
Support is handled in the forums.
