### ISSUE TITLE
Panic - runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by PierreRust** [syncthing/syncthing#6031]
# Description

While synchronizing, syncthing crashed with this error ( slice bounds out of range). It has been running fine for a few hours before, synchronizing several thousands of files.
Now, every time I restart it, it crashes after a few seconds with the same error.
Unfortunately, I have no idea of what lead to that state (and henc on how to reproduce) 

See attached panic log file

[panic-20190925-120146.log](https://github.com/syncthing/syncthing/files/3651890/panic-20190925-120146.log)

Let me know if you need further information or if I should test something.

Apart for the (unknow) root cause, is there anything I can do to get back to a working system ? 

# Version Information

Syncthing Version: v1.2.2 - latest stable from PPA
OS Version: Linux mint based on Ubuntu 18.04 / ...

**Comment by imsodin** [comment]
```
[75XTZ] 12:01:39 INFO: syncthing v0.14.43-ds1 "Dysprosium Dragonfly" (go1.9.3 linux-amd64) debian@debian 2018-02-06 04:01:09 UTC [noupgrade]
```

If you have sufficiently large files to sync this is a known problem in <v0.14.46 connected to >v1.2.0 (with default settings) - you need to upgrade the old Syncthing client (or downgrade, but I'd very much recommend the other way around).

**Comment by PierreRust** [comment]
Oops, sorry about that, I was sure I installed from the PPA but somehow I still ended with the (outdated !) version from ubuntu's bionic repo. 
I've upgraded and it works perfectly no, many thanks !
