### ISSUE TITLE
ajax retrieval of php table data created from a mysql query

### ISSUE THREAD

**Issue by andyjamesgreaves** [syncthing/syncthing#6032]
Issue:
Unable to retrieve data from a mysql query in a php file where the result is:
echo  $searchresult;

Expected to retrieve it in the form of a table from page file with script as shown below:
<script>
  function ajax_post(){
    alert("clicked.");
    // Create our XMLHttpRequest object
    var xmlhttp = new XMLHttpRequest();

    // Create some variables we need to send to our PHP file
    var url = "roomsearch.php";
    var fromdate = document.getElementById("fromdate").value;
    var enddate = document.getElementById("enddate").value;

    // Access the onreadystatechange event for the XMLHttpRequest object
    xmlhttp.onreadystatechange = function() {
      if(hr.readyState == 4 && hr.status == 200) {
        document.getElementById("roomslist").innerHTML = xmlhttp.responseText;
      }
    }
    xmlhttp.open("GET", url, true)
    xmlhttp.send(null); // Actually execute the request
    return false;
  }
</script>

Php file to retrieve data from:
$searchresult = '<table border="1"><thead><tr><th>RoomID</th><th>Room name</th><th>Room type></th><th>Beds</th></tr></thead>';
      while ($row = mysqli_fetch_assoc($result)) {
        $id = $row['roomID'];
        $searchresult .= '<tr><td>'.$row['roomID'].'</td><td>'.$row['roomname'].'</td><td>'.$row['roomtype'].'</td><td>'.$row['beds'].'</td>';
        $searchresult .= '</tr>'.PHP_EOL;

Windows 10 OS
UniServerZ is used to store the database and run the php pages.

**Comment by AudriusButkevicius** [comment]
Wrong project I think?
