### ISSUE TITLE
Clicking "Save" in options says "You have unsaved changes" when changing automatic upgrade setting

### ISSUE THREAD

**Issue by Lunarcelia** [syncthing/syncthing#6044]
This happens to three virtual machines running centOS 7 and syncthing 1.3.0 .
In the options, selecting **specifically** "No upgrades" when "Stable releases and release candidates" is selected and in effect, then saving causes the "You have unsaved changes" popup to appear, making it impossible to switch directly from "Stable and candidates" to "No upgrades".
It's as if clicking outside the window or "Close".
To select it, I had to switch first from "Stable and candidates" to "Stable only", save, then go back and select "No updates", then save.
Not a software-breaking bug but worth mentionning.

**Comment by calmh** [comment]
> In the options, selecting specifically "No upgrades" when "Stable releases and release candidates"

I can reproduce. The other paths seem fine. Odd.
