### ISSUE TITLE
Docker containers for discovery and relay servers

### ISSUE THREAD

**Issue by jyundt** [syncthing/syncthing#6046]
Similar to the existing [Docker Hub syncthing container](https://hub.docker.com/r/syncthing/syncthing), would it also be possible to add `strelaysrv` and `stdiscosrv` containers to the pipeline?

Quick and dirty diff as a possible example: 0b2811d8900d7d5d6884d06b34a4a599d6337bef

If someone can point me to the build process that produces the official Docker Hub `syncthing` image, I'd be happy to submit a PR.

**Comment by calmh** [comment]
Sure, why not. There is no build process apart from `docker build -t syncthing:latest .`

**Comment by jyundt** [comment]
@calmh 
Thank you for the quick response!

A few follow-up questions: What's the process to cut a relay and discovery server release vs cutting a syncthing release? Is the existing Docker Hub container image built using DH's automated builds? Or are containers pushed via some other pipeline?

Using my existing diff, both containers can be built with something like:

 ```
# docker build -f Dockerfile.strelaysrv -t strelaysrv:latest .
# docker build -f Dockerfile.stdiscosrv -t stdiscosrv:latest .
```

But this could definitely be DRY-ed out a bit using Dockerfile `ARG`s to reuse the same Dockerfile and variable-ize items like ports, binary names, homedirs, etc.

**Comment by chigix** [comment]
Both docker files for relay server and discovery server has been available in the repository, is this plan to add them to the pipeline still in progress ?

**Comment by calmh** [comment]
I think I just forgot to set up builds for them once it was release time, I'll do that now.

**Comment by calmh** [comment]
There are now builds for `syncthing/discosrv` and `syncthing/relaysrv`.

**Comment by chigix** [comment]
@calmh So it will be able to be seen on docker hub as another two docker images right?

Additionally, would it be necessary to update the usage descript in https://github.com/syncthing/syncthing/blob/master/README-Docker.md ?

**Comment by dalanmiller** [comment]
Was this effort abandoned? I don't see separate images on Docker Hub.

**Comment by AudriusButkevicius** [comment]
https://hub.docker.com/r/syncthing/discosrv
https://hub.docker.com/r/syncthing/relaysrv 

???
