### ISSUE TITLE
v1.3.0 is no longer support for Vista?

### ISSUE THREAD

**Issue by justwholegrain** [syncthing/syncthing#6052]
SyncTrayzor notification me to update to Syncthing v.1.3.0 and now after run SyncTrayzor doesn't start Syncthing because get error message. So downloaded separately Syncthing v1.3.0 (not SyncTrayzor) and tried run, however I get a message like 'syncthing.exe is not suitable application for system Win32" (I've non-english system, so I don't know is exactly such message). I've Vista 32, so downloaded syncthing-windows-386 for 32bit. 

Will you no longer support Vista :/ or is it only the bug?

**Comment by AudriusButkevicius** [comment]
Last go version to support vista was go 1.10, we've moved beyond that a while ago, so the fact that it worked was pure luck, and sadly it ran out.

You can still try and build it yourself with an old version of go.

**Comment by Quosimadu** [comment]
Sadly also affects Windows Server 6.0 (2008) which is only end of life in 3 months.

**Comment by coobic** [comment]
I think that autoupdate procedure should determine the OS version and does not update the application (if it`s incompatible with OS).

**Comment by AudriusButkevicius** [comment]
Well, it's too late now, we can't upgrade an old version to fix that.

**Comment by coobic** [comment]
Small note for users:
<autoUpgradeIntervalH>0</autoUpgradeIntervalH>
Install 1.2.2 (for Windows Server 2008), disable update and start.

**Comment by Catfriend1** [comment]
SETX /M STNOUPGRADE=0

**Comment by SaeX** [comment]
For those using SyncTrayzor: v1.1.24 comes with Syncthing 1.2.0; setting
`<SyncthingDenyUpgrade>true</SyncthingDenyUpgrade>` in `SyncTrayzor.exe.config` avoids auto-upgrade.
