### ISSUE TITLE
Improve sharing tab when there are no devices to share with

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [syncthing/syncthing#6056]
Screenshot:

![image](https://user-images.githubusercontent.com/47056543/66149872-e7d47500-e60b-11e9-81d0-8d686035b3e3.png)

This makes little sense, so far as I can see. How can one choose 'all' or 'none' from . . nothing? It is as if you are trying to confuse your users.

**Version Information**

Syncthing Version: v1.3.0
OS Version: Windows 10 1903
Browser Version: Firefox 69.0.1 x64

**Comment by gevlee** [comment]
Hello,
Can I try to fix that? :)
Proposition of implementation:
Instead displaying "Select the devices to share this folder with" + buttons, it will be "There is no devices to share this folder with" in case of empty list.

**Comment by AudriusButkevicius** [comment]
Sounds good.
