### ISSUE TITLE
"Nearby devices" links should look more like links (mouse pointer)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [syncthing/syncthing#6057]
Screenshot: 

![image](https://user-images.githubusercontent.com/47056543/66150113-67624400-e60c-11e9-8d37-a1c2199e88c8.png)

When one moves the pointer over the device - the device shown in blue - the pointer changes to a caret. Yet, one cannot edit the field. Except one can copy the string and paste it. Yet, is that what one is meant to do? It seems not . . For if one does, one see this:

![image](https://user-images.githubusercontent.com/47056543/66150320-cfb12580-e60c-11e9-8070-7213d7c9f546.png)

Syncthing Version: v1.3.0
OS Version: Windows 10 1903
Browser Version: Firefox 69.0.1 x64

**Comment by calmh** [comment]
Also, the "these nearby devices:" text remains when there are in fact no nearby devices, which looks bad.
