### ISSUE TITLE
After-icon line breaks in GUI

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#6058]
There are a lot of line breaks after the small icons in the GUI nowadays:

<img width="569" alt="Screen Shot 2019-10-03 at 19 47 32" src="https://user-images.githubusercontent.com/125426/66151014-bc0abc80-e616-11e9-9a03-9e2997756aa7.png">

Even when it seems like no line break ought to be necessary at all:

<img width="564" alt="Screen Shot 2019-10-03 at 19 47 43" src="https://user-images.githubusercontent.com/125426/66151065-d349aa00-e616-11e9-928f-3fac9cee1e05.png">

**Comment by wweich** [comment]
What browser do you use? I cannot reproduce this in Firefox or Chrome on Linux.
There is a non breaking space (`&nbsp;`) between the `span` for the icon and the one for the label, so there should be no line break between the Icon and the first word of the label

**Comment by nekr0z** [comment]
I fail to reproduce this on Safari or Konqueror either.

**Comment by calmh** [comment]
So this is with Edge beta on Mac, which is essentially Chrome so I thought would be representative and reasonable. Yet I don’t see it in safari and nobody else appears to either so I’m guessing browser or user error.

**Comment by nekr0z** [comment]
Started seeing the same in stable version of Chrome on Linux after last update. Still not seeing it in other browsers, though.

**Comment by vforge** [comment]
I can confirm that in latest Chrome on MacOS and Win10.

**Comment by calmh** [comment]
It's gone.
