### ISSUE TITLE
When one manages to get Syncthing working, bookmarking its browser tab in firefox results in an icon indicating an error

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [syncthing/syncthing#6059]
I've got Synthing working and I bookmarked its tab in Firefox onto the bookmark bar. On Windows - where I have a password setup for Syncthing - the browser icon shows a pause tab, thusly:

![image](https://user-images.githubusercontent.com/47056543/66157703-3ee24600-e61c-11e9-98e5-9ef17170feef.png)

On Linux, the browser icon shows an error state, thusly (and the icon is larger than for the Windows problem because on Linux I have HDPI; there is no problem with the _size_ of Syncthing's icons):

![image](https://user-images.githubusercontent.com/47056543/66157565-ef9c1580-e61b-11e9-9de6-44450bd70c3b.png)

Yet, on neither machine is Syncthing paused or in an error state. I infer that this is a bug.

Syncthing v1.3.0 (Linux (64 bit), Windows (64 bit))

**Comment by Ferroin** [comment]
I'm not sure that this is Syncthing specific.  From what I've seen, it's a pretty common issue with sites and web apps that use dynamic favicons.

**Comment by AudriusButkevicius** [comment]
Yeah, it captures the icon at the point its bookmarked, so not our bug, as wanting dynamic icons is not compatible with having sensible icons during bookmarking.
