### ISSUE TITLE
Wrong/misleading IP address shown for webGUI access

### ISSUE THREAD

**Issue by Fealthas** [syncthing/syncthing#6066]
I changed the web-gui from 127.0.0.1 to 0.0.0.0 so I could acess it from another computer. However, the info messages it gives are incorrect, it does not acknowledge that the access ip has changed, which made me think something was broken after I configured it and restarted:
![image](https://user-images.githubusercontent.com/25716039/66343483-bdd7c700-e919-11e9-8ed2-7b6263e7a4b8.png)

**Comment by Fealthas** [comment]
Note that I can access the webGUI with no problems.

**Comment by AudriusButkevicius** [comment]
0.0.0.0 is not an accessible address. It assumes that you are running syncthing and watching the console locally, in which case the correct address is still 127.0.0.1

**Comment by calmh** [comment]
The actual listening address is one line above your highlight. The highlighted line is to give you something to double click or copy/paste.
