### ISSUE TITLE
'Out of sync' items unintelligible: it displays what seems to be a key and also text that does not conform to the key

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [syncthing/syncthing#6067]
**What happened**

I saw this:

![image](https://user-images.githubusercontent.com/47056543/66354180-f0a2af00-e95b-11e9-9590-0b3bdc08ea90.png)

**What I expected to happen**

The multicoloured strip suggests that either: (i) its different parts are clickable; (ii) it is a key to some coloured output that will follow. That ambiguity would not be ideal. Worse, though: neither _i_ nor _ii_ seems to be the case - see the screenshot. Hence I am at a loss to interpret the error. Note that since it is an _error_ that is at issue, clarity really matters. Possibly I misunderstand what the UI is trying to tell me, but, if so, I am not at all sure that this is my fault.

**Steps to reproduce**

Unsure. Possibly: make Syncthing show any syncing error. [EDIT: fixed typo.]

### Version Information

Syncthing Version: v1.3.0, Windows (64 bit)
OS Version: Windows 10 (but the problem may be cross-platform)
Browser Version: Firefox 69.0.2

**Comment by LinuxOnTheDesktop** [comment]
Also: while this is a UI problem, and in that sense a bug, I'd like to know what actually to do about what syncthing is trying to tell me. Should I ask in the forum?

**Comment by AudriusButkevicius** [comment]
Sorry, I made a comment but forgot to submit it. I suggest you check the logs, I suspect it will be #1787

**Comment by AudriusButkevicius** [comment]
If its not, start a thread on the forum.

**Comment by LinuxOnTheDesktop** [comment]
Thanks Audrious. I had a look at the bug report ('remarkably terrible [. . .] results in data loss, which is unacceptable') that you mentioned. Here's a thing, though. The error message that I mentioned is so grossly unintelligible that I feel justified in asking, right here, how on earth I should interpret it. An answer will help me fix the problem.

**Comment by LinuxOnTheDesktop** [comment]
My previous comments did not make explicit the full extent of the problem. I do that now.

Not only does the bit of UI at issue give me a key that it then fails to apply to the data it displays. Additionally, the UI offers the user no actions to resolve the problem. I discover that, if I delete one of the items concerned, then, some ten minutes later, it disappears from the list of problematic files. The user needs to be told what she can do (even if it be the drastic step of deleting the item at issue from all - yes? - devices) and how long it will take for any such action to be reflected in the error message.

I appreciate that programming this stuff is hard. Yet, for a public release you need at least to make your error messages (1) comprehensible, (2) easily actionable (i.e. easily actable-upon). To not do those things is to express the attitude that you wish only professionals and hard-core amateurs to use your project and that other people - including those who have used Linux for several years - can get lost. Or so it seems to me.

**Comment by AudriusButkevicius** [comment]
At this point this issue is about the confusion of having no progress bars visible, oppose to errors or whatever you are after. I've already suggested to look at the logs to understand whats happening.

**Comment by imsodin** [comment]
I don't see anything actionable in here.

**Comment by LinuxOnTheDesktop** [comment]
Here is what is actionable. Stop it being the case that the program displays a key (a.k.a. legend) that it then fails to use in the output it provides. Or, if as I imagine may well be the case, actually the seeming key is not even a key at all but something else (but what?), then make it clear what it actually is.

You may want me to suggest something more positive, more concrete. I would, but the problem is that the UI is so baffling that . . I am baffled. But perhaps others understand the UI.

**Comment by AudriusButkevicius** [comment]
We are well aware that the UI is poor. PRs fixing it welcome.
