### ISSUE TITLE
Show hash of the file from api call 

### ISSUE THREAD

**Issue by tsaridas** [syncthing/syncthing#6071]
At the moment when you query the status of a file you do not get any information about the hash of the file. I believe that can be useful.

Can you please add this as a feature request ?

**Comment by AudriusButkevicius** [comment]
Files don't have hashes, blocks do. I think we don't expose those, but nor do I see a reason why we should. I think questions like this should land on the forum first, with an explanation why it would be useful, not just "can be useful".

**Comment by calmh** [comment]
At the moment we don't event calculate the whole-file hash, we just calculate hashes of individual blocks. We're reading the whole file and could feed the bytes to a second hasher but would increase CPU by about 100% during the hashing.

I've considered exposing a hash-of-hashes (think very wide Merkle tree) just to have something to quickly compare two files, but it's unclear if that would be useful for other consumers.

**Comment by calmh** [comment]
Ninja'd
