### ISSUE TITLE
Filesystem watcher: Permission errors in ignored folders

### ISSUE THREAD

**Issue by nalt** [syncthing/syncthing#6072]
Problem: I get Filesystem Watcher Errors like:
Folder1 | error while traversing .../.spam: permission denied
Folder2 | error while traversing /mnt/disk/lost+found: permission denied

As a result, the watcher does not even start.

The filesystem watcher should not even be in those locations, as they are in the ignore pattern. If it does not follow the ignore patterns, it also would request too many system resources. My pattern includes some folders with !/folder1, and then excludes everything else with /*. In the first case, .spam is deep inside an ignored folder. 
These files cannot be made rw for the user due to system constraints.

Expected: The filesystem watcher should not touch anything that is in the ignore pattern.

### Version Information

Syncthing Version: v1.3.0
OS Version: Ubuntu 16.04

**Comment by calmh** [comment]
This is, currently, expected. Ignore exceptions (`!`-patterns) means Syncthing will traverse the full tree regardless. You might, as a human, realize that this is unnecessary in your specific case. As a machine it's trickier, even for rooted patterns.

**Comment by nalt** [comment]
Ok. Is there any trick to tell the watcher where to go, or where not to go?

**Comment by AudriusButkevicius** [comment]
Inverting the patterns (to avoid !) Is the only way I think, or resolving permission issues.

**Comment by nalt** [comment]
Permissions are a fundamental feature of most file systems, used by many software packages. Its intended use should be handle more gracefully than fully breaking the notify feature. So I would suggest this is rather a bug.

**Comment by intelfx** [comment]
@calmh Will _any_ `!`-pattern cause syncthing to disable optimizations and traverse the full tree, or is there a way to force Syncthing to ignore specific subtrees finally and completely even in presence of `!`-patterns?

(See this support topic for context: https://forum.syncthing.net/t/completely-prevent-syncthing-from-traversing-a-directory-subtree/15060)

**Comment by calmh** [comment]
Closed in favor or the slightly newer duplicate, as that one is now a somewhat clearer description of the problem and expected solution.
