### ISSUE TITLE
Allow the user to disable automatic upgrades via a command line argument

### ISSUE THREAD

**Issue by scavet64** [syncthing/syncthing#6079]
Disabling automatic updates via the command line would be a nice to have feature. I know it would directly benefit the usage of syncthing that my setup requires.

Thanks!

**Comment by scavet64** [comment]
I plan on submitting a pull request shortly to resolve this issue

**Comment by AudriusButkevicius** [comment]
You can already do that with an env var.

**Comment by scavet64** [comment]
> You can already do that with an env var, I don't remember from the top of my head what it is tho, so check docs/forum/code.

Would it not be ok to allow for a secondary method for disabling the automatic upgrades? My code change is very minimal and provides the user with an alternative method in the case that environment variables cannot be used or is not ideal

**Comment by AudriusButkevicius** [comment]
There is already a way to do what you want, so adding yet another way in my opinion is not great, because it's easy to add stuff, but hard to remove when people start using it.
