### ISSUE TITLE
lib/connections: Quic error loop too tight

### ISSUE THREAD

**Issue by DaBozz** [syncthing/syncthing#6081]
Since i upgraded to SyncThing 1.3.0 (running on Windows 7 SP1 x64), the following warning appears continuously about 100 times A SECOND which quickly fills up my log and then crashes SyncThing completely: 

"WARNING: Listen (BEP/quic): Accepting connection: read udp 0.0.0.0:22000: wsarecvfrom: The connection has been broken due to keep-alive activity detecting a failure while the operation was in progress."

It does not start immediately, sometimes after three minutes, sometimes after a period of hours, but then, when it starts, it floods the command window, floods the log and finally kills SyncThing.

**Comment by AudriusButkevicius** [comment]
Can you try allowing syncthing through the firewall port 22000 via UDP and see if that fixes it?

**Comment by pyhedgehog** [comment]
I have same problem and I'm in corporate network where I have no control on firewall.

**Comment by pyhedgehog** [comment]
As a workaround I have changed "Sync Protocol Listen Addresses" from `default` to `tcp://0.0.0.0:22000, dynamic+https://relays.syncthing.net/endpoint`.
