### ISSUE TITLE
Default Folder uses different config than user-created folders

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#6086]
While setting up a new folders I noticed that there are different defaults for `maxConflicts`

https://github.com/syncthing/syncthing/blob/999d4a0e2397c44863c04f87596a484ab4f41c39/gui/default/syncthing/core/syncthingController.js#L69

https://github.com/syncthing/syncthing/blob/f6f696c6c51d0a5d27e548b814f6efb6e5af5e8d/lib/config/folderconfiguration.go#L53

https://github.com/syncthing/syncthing/blob/6b74cdc6138a0e07f1954eb03ad479438082a8b1/man/syncthing-rest-api.7#L130

Expected value
-1

**Comment by AudriusButkevicius** [comment]
Given you found the code, you might as well pitch a PR.

**Comment by calmh** [comment]
Frankly, I'm not sure this is a bug. These apply in different situations. The `10` is set as a reasonable default value when creating a new folder, and will be visible as such in the config. The `-1` (no maximum) applies if there is no value set at all in the config. I think it's reasonable to not apply a limit to the number of conflicts if the config value for the limit is not present.

**Comment by AudriusButkevicius** [comment]
I guess auto-introduced folders have it inconsistent, where we might went it fixed.

**Comment by calmh** [comment]
Well, the whole "where do defaults" come from situation is a bit nasty. My thoughts above are maybe just a rationalization, and it would be good with a central place for defaults that gets applied to new folders (and other config items) _however_ they are created...

**Comment by imsodin** [comment]
What about taking the defaults away from UI/JS and add a `/rest/system/defaultfolder` endpoint. As a first step just as a GET operation. And if anyone tackles #4224 they can add a SET operation too. Then if we want any different defaults displayed in the UI, we just override that specific item there. The GET only change should be fairly simple.
