### ISSUE TITLE
SyncTrayzor BOOT

### ISSUE THREAD

**Issue by snddzxb** [syncthing/syncthing#6089]
SyncTrayzor installation environment, windows server 2019, SyncTrayzor can not be started automatically after restarting the operating system, you must first log in to the operating system SyncTrayzor to start, otherwise you can not connect.

**Comment by calmh** [comment]
This looks like a [SyncTrayzor issue](https://github.com/canton7/SyncTrayzor/issues), to the extent that it is an issue and not simply a design decision, I'm not sure.
