### ISSUE TITLE
Building fails when host name includes spaces under macOS Catalina

### ISSUE THREAD

**Issue by Knapoc** [syncthing/syncthing#6095]
Under macOS Catalina building syncthing from source fails when the hostname contains spaces - at least that's my assumption.

I first encountered this issue while trying to install syncthing via MacPorts. I had similar issues with the port perl5.28.

My uname -a output: `Darwin xxxxxxx’s MacBook Pro 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64`

As soon as I changed the hostname via `sudo scutil --set HostName 'test'` the build was successful.

A short extract of the build log:
```
35 | :info:build github.com/syncthing/syncthing/lib/syncthing
-- | --
:info:build github.com/syncthing/syncthing/cmd/syncthing
:info:build # github.com/syncthing/syncthing/cmd/syncthing
:info:build usage: link [options] main.o
:info:build   -B note
:info:build             add an ELF NT_GNU_BUILD_ID note when using ELF
:info:build   -E entry
:info:build             set entry symbol name
:info:build   -H type
:info:build             set header type
( ..... removed for readability .....)
:info:build   -v        print link trace
:info:build   -w        disable DWARF generation
:info:build exit status 2
:info:build exit status 1
:info:build Command failed:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_syncthing/syncthing/work/gopath/src/github.com/syncthing/syncthing" && /opt/local/bin/go run build.go -version v1.3.0 -no-upgrade install syncthing
:info:build Exit code: 1
```

For the full build log please refer to my [macports-ticket](https://trac.macports.org/attachment/ticket/59255/main.log)

The issue persisted with different go versions (I tried 1.12.10, 1.13.1, 1.13.2) installed via MacPorts and also when I tried to build syncthing without MacPorts.

### Version Information

Syncthing Version: v1.3.0
OS Version: macOS 10.15 
go version: v1.13.1

**Comment by greatroar** [comment]
It looks like you should be able to set the environment variable BUILD_HOST to something not containing spaces to work around this.

**Comment by Knapoc** [comment]
I completely forgot about this issue. It seems I messed with the hostname settings.
