### ISSUE TITLE
Proposal: Support absolute include paths in .stignore

### ISSUE THREAD

**Issue by harrisonhjones** [syncthing/syncthing#6096]
I was setting up Syncthing again this week (old laptop died). I created `~/.stignoreglobal` on my new Windows machine and went to work adding all my existing folders. I was quickly reminded that there is no way to `#ignore` a file in each folder's `.stignore` using an absolute path. While not the end of the world it does make setting up the `.stignore` in folders with various degrees of nesting a huge pain. I know y'all have said, [in the past](https://github.com/syncthing/syncthing/issues/1176#issuecomment-68642501), that you would prefer not to reference files outside of the folder's scope but I figured I'd throw out this proposal and see what y'all thought.

### What it does
Allows users to include files in their folder's `.stignore` file using absolute paths.

### Why people might want it
Makes it easier to manage your "global" `.stignore` files. No more `../../../../` in your `.stignore` files.

### How it works
A new keyword `#includeabs` is available for use in your `.stignore`. When Syncthing processes your folder's `.stignore` and encounters `#includeabs` it treats the string after `#includeabs` as an absolute file path for another `.stignore`-formatted file to load.

### What it might break
If implemented correctly this should not break anything.

### Who will implement/test it
Me.

#### Setup

1. I have an ignore file located at `~/foo`
1. I have a Syncthing folder located at `~/Sync/Bar`
1. I have an ignore file at  `~/Sync/Bar/.stignore`

I want Syncthing, when processing my folder at `~/Sync/Bar`, to load the ignore patterns in `~/foo`.

Without this proposed change `~/Sync/Bar/.stignore` must contain the following line:

```
#include ../../foo
```

With this change an alternate version of that line could be:

```
#includeabs ~/foo
```

which is, imo, much more readable.

Thoughts?

**Comment by AudriusButkevicius** [comment]
I think we should go the opposite way and prevent including anything from external directories. We permit that file to be a symlink so people can use that. Supporting includes outside of the folder causes pain with filesystem abstraction.

**Comment by harrisonhjones** [comment]
Thanks for the response. I'm personally not a huge fan of symlinks; coming from a Windows background symlinks are still things I don't naturally understand and I would not be surprised if others felt the same way. Additionally, on Windows there is pretty aweful support for symlinks, at least at this point.

For my own understanding can you go into a bit more detail on

> Supporting includes outside of the folder causes pain with filesystem abstraction.

Why does it cause pain? How?

**Comment by AudriusButkevicius** [comment]
Every syncthing folder has a "filesystem" where the filesystem is rooted at the root of the folder. Meaning that accessing anything out of the folder should crash/fail and burn, this is to avoid various attacks such as breaking out of the folder by time based symlink traversal attacks and so on.

Supporting loading ignores from random parts of the filesystem suddenly makes this isolation code an unbearable mess that opens up potential attacks.

We do special magic

**Comment by calmh** [comment]
Yeah there's that thing, which is difficult to correct now for historical reasons. Regardless supporting absolutes in the stignore is indeed a step in the wrong direction so I'm going to veto it for that reason. Long term I still think we should get rid of ignore patterns in files as a concept and have some more elegant solution in the config/database with optionalish sync of patterns between peers.

**Comment by harrisonhjones** [comment]
Thanks for the feedback! Created [this post](https://forum.syncthing.net/t/proposal-support-absolute-include-paths-in-stignore/13949) so we could continue talking about it.
