### ISSUE TITLE
syncthing sync files md5 is identical

### ISSUE THREAD

**Issue by cedricbrx** [syncthing/syncthing#6097]
I have 2 servers, the two are Debian 10. The second i installed yesterday is with installed with snapraid. 
I synced the content of the first server to the second. Everything went well. Snapraid told me about  zero sub-second timestamp (https://www.snapraid.it/faq#subsecond) and touched some files.
After that a lot file were synced, despite they have the same md5 and the same creation time

xx@mars:~/Programs$ stat "./.stversions/MB WIS ASRA 11 2018-4DDL/MB WIS ASRA 11 2018-4DDL.part08~20191020-162127.rar"
  File: ./.stversions/MB WIS ASRA 11 2018-4DDL/MB WIS ASRA 11 2018-4DDL.part08~20191020-162127.rar
  Size: 525336576 	Blocks: 1026048    IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 129237020   Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/ xx)   Gid: ( 1000/ xx)
Access: 2019-10-20 16:52:39.985386455 +0200
Modify: 2019-03-05 18:35:40.000000000 +0100
Change: 2019-10-20 16:21:27.056549349 +0200
 Birth: -
xx@mars:~/Programs$ stat "./MB WIS ASRA 11 2018-4DDL/MB WIS ASRA 11 2018-4DDL.part08~20191020-162127.rar"
stat: cannot stat './MB WIS ASRA 11 2018-4DDL/MB WIS ASRA 11 2018-4DDL.part08~20191020-162127.rar': No such file or directory
xx@mars:~/Programs$ stat "./MB WIS ASRA 11 2018-4DDL/MB WIS ASRA 11 2018-4DDL.part08.rar"
  File: ./MB WIS ASRA 11 2018-4DDL/MB WIS ASRA 11 2018-4DDL.part08.rar
  Size: 525336576 	Blocks: 1026048    IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 129239964   Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/ xx)   Gid: ( 1000/ xx)
Access: 2019-10-20 16:49:49.966758381 +0200
Modify: 2019-03-05 18:35:40.528936260 +0100
Change: 2019-10-20 16:21:27.056549349 +0200
 Birth: -

xx@mars:~/Programs$ md5sum "./.stversions/MB WIS ASRA 11 2018-4DDL/MB WIS ASRA 11 2018-4DDL.part08~20191020-162127.rar"
067ad6ed2ba4722f834f562870dddf0d  ./.stversions/MB WIS ASRA 11 2018-4DDL/MB WIS ASRA 11 2018-4DDL.part08~20191020-162127.rar
xx@mars:~/Programs$ md5sum "./MB WIS ASRA 11 2018-4DDL/MB WIS ASRA 11 2018-4DDL.part08.rar"
067ad6ed2ba4722f834f562870dddf0d  ./MB WIS ASRA 11 2018-4DDL/MB WIS ASRA 11 2018-4DDL.part08.rar

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
