### ISSUE TITLE
Feature proposal to avoid syncing of corrupted files

### ISSUE THREAD

**Issue by smnthermes** [syncthing/syncthing#6098]
My proposal is a feature to set a folder to only sync changes coming from one or more specified application(s).

**Comment by AudriusButkevicius** [comment]
Hi,

I suggest you bring this to the forum with a more detailed description of what you are trying to achieve.

Syncthing has no concept of "applications making changes", as all it sees it files on the disk, not having an idea which application made the changes.

Thanks!
