### ISSUE TITLE
Implement user and group name:id mapping, NOT #1329

### ISSUE THREAD

**Issue by illwieckz** [syncthing/syncthing#6105]
This issue is to keep track of the need for this other feature multiple people expressed, to be sure the #1329 issue will not be hijacked anymore. THIS IS NOT DUPLICATE OF #1329.

Note that me and others in #1329 thread don't have a need for syncthing implementing a name/id mapping function because it's up to other tools to do this (like `winbind`) and they are already up and running to fulfill other needs. But I understand how it would be easier for some people to have a tool-to-rule-them-all, especially in heterogeneous scenarii.

So this issue is there to continue there the talk about the need for an name:id mapper, to properly redirect people there or properly mark related issues as duplicate of this one instead of #1329 which is not about implementing a name:id mapper but about syncing raw uid/gid.

For reference, some quotes by @Ferroin:

> If this gets implemented, it should ideally provide some means of mapping ID's and names. People don't use the same user name everywhere (especially if they've got different operating systems involved), and there are cases where neither syncing based on numeric ID or based on name will work correctly (in fact, by numeric ID won't work most of the time when multiple users are involved, and is pretty much guaranteed not to work if syncing between multiple operating systems).

> Why not just store the user and group names in the metadata, and have a local, per-device mapping that translates that name to a UID/GID/SID for Syncthing?

**Comment by AudriusButkevicius** [comment]
Again, I don't think I personally really want this as a feature. This would mean running syncthing as root, which is not really recommended. 

In my view (And I am only one of the maintainers, no all) Syncthing is not supposed to be some corporate user directory backup software. It's a personal tool for syncing your folders/files which should be owned by a single user.

This issue and the one your referenced are duplicate for me, as they are more of a "do we really want to do this" issues, oppose to "how do we do this to call this done".

You can't avoid uid/guid mapping/cleverness stuff as you will sync files to windows where these things make no sense, or devices where these uids/gids don't exist, so "just do it" issue bears no value.

If other maintainers feel there is substance to this ticket that is different #1329, feel free to reopen.

**Comment by Ferroin** [comment]
I'm not a maintainer, but I would tend to agree with @AudriusButkevicius, albeit with a slightly different reasoning:

I see exactly zero ways that #1329 could be implemented without some form of this type of functionality being involved.  If we're going to implement such a feature, it needs to work everywhere it possibly can, which means it needs to work in cases where you either have a completely different user ID mechanism (Windows) or functionally have none whatsoever (Android), which means that some form of mapping is going to be needed, even if it's between some internal representation and the local representation.

**Comment by AudriusButkevicius** [comment]
I think the problem is that OP wants a solution to solve his problems, and we want a solution that solves everyone's, meaning the solution has to be more complex as described in #1329. I don't think there is any functionality carry over between the two, so if we do decide to fix this, we should fix this in a way that solves it for everyone.

**Comment by illwieckz** [comment]
> Syncthing is not supposed to be some corporate user directory backup software.

No one talked about backup. To do backups there is plenty of tools saving uid/gid, to do backups there is no need for bidirectional replication, hence there is no need for syncthing. At least, syncing a directory is not backing-up (vulnerable to corruption, deletion, and ransomwares) so syncthing is not a backup tool. No one talked about backup there.

Syncthing is about syncing files. There is two ways to sync files, on a filesystem level (btrfs send/receive for unidirectional feature, ceph or glusterfs for bidirectional feature), on a file level (rsync, unison, syncthing). There is very good reason to not sync files on a filesystem level, to rely on advanced feature a non-decentralized fs has, like snapshotting for example. Also, some distributed filesystems are not good with geo-replication (glusterfs' one is unidirectional). That's part of why tools like syncthing exist in any way.

So to sum it up, this is what's available to people there to sync files at file level:

||rsync|unison|syncthing|
|---|---|---|---|
|**direction**|:x: unidirectional|:heavy_check_mark: bidirectional|:heavy_check_mark: bidirectional|
|**peers**|:heavy_check_mark: any|:x: 2|:heavy_check_mark: any|
|**inotify**|:x: no|:x: no|:heavy_check_mark: yes|
|**id syncing**|:heavy_check_mark: yes|:heavy_check_mark: yes|no :x:|

People asking for simple uid/gid syncing are just looking for an unison-like tool that works with more than two peers without hacks.

Syncthing with simple uid:gid syncing would supersede unison instantly. Syncthing is near to be the perfect tool for environment with third-party id mapping tools (those tools exist since ages and are very stable, a good example is ldap directories, they exist since decades).

Implementing uid/gid syncing is just there to make syncthing on par with rsync and unison on that level, while syncthing already outperforms other. Syncthing is then near to be the one to rule them all, it just lacks id syncing to be that one.

In any way, neither rsync neither unison has id mapping feature, so implementing this in syncthing would not make syncthing on par with something else. This would be cool to have, but that's clearly another gap.

The gaps are clearly defined and can be implemented as different steps:

- first gap, first step: id syncing
- second gap, second step: id mapping

What if id mapping never comes?

As far as I see #1329 is near to be 5 years old, what if this simple feature (id syncing) never comes because of the dream of a complex one (id mapping) no one feels himself strong enough to work on ?

**Comment by AudriusButkevicius** [comment]
Again, this is all mostly visible through your prism, how that one feature would make it a perfect tool for your use case. 
There are more than 4 features across the 3 products that make up these products and I am sure there are plenty of features that syncthing does not have that other tools do, that other users are asking for in other tickets.

The problem with #1329 is not the fact that it's complicated, hence we don't do it. In fact it's pretty straight forward atleast in my eyes.
The problem that there is nobody who wants to spend their uncompensated time on this. Nor is syncing ids, which as we've agreed would be the wrong solution in the first place.

If you feel strongly about this, roll up your sleeves, fork, add the 10 or so lines of code that are needed to support what you are after, and get on with your life.
