### ISSUE TITLE
Inconsistent folder name on creation: share initial vs share after deletion

### ISSUE THREAD

**Issue by TechupBusiness** [syncthing/syncthing#6112]
When a folder is created initially (on a remote peer) after I shared it, the folder name on that peer is based on the **label name** of my local peer. But when the peer deletes the syncthing-folder (via GUI), delete the filesystem folder and don't add it to the ignored folder list, it's getting recreated using the **folder-id** as folder name this time. Is this difference by intention?

### Version Information
Syncthing Version: v1.3.0
OS Version: Ubuntu 18.04 /

**Comment by AudriusButkevicius** [comment]
No, it uses folder id only if a folder with the name of the label already exists. There is a test to prove this, so I think you are not deleting the right folder.

**Comment by AudriusButkevicius** [comment]
If you can repro, open a forum thread with the steps.
