### ISSUE TITLE
Inconsistent behavior of path generation local vs remote

### ISSUE THREAD

**Issue by TechupBusiness** [syncthing/syncthing#6113]
When I create a new folder on my local instance and use a path separator in the title, it adds the separator to the path (automatically, which makes sense!):

![image](https://user-images.githubusercontent.com/38460054/67868064-a7ddb080-fb2b-11e9-8a43-367be045a1f8.png)

But when I share this folder to another machine, it gets the same label there, but the automatically generated path is different to the one added manually (local). 

![image](https://user-images.githubusercontent.com/38460054/67868084-ae6c2800-fb2b-11e9-9445-f82f5a4e8a44.png)

It would be great if the path would be the same remote, allowing the generation of sub-directories.

Otherwise (=workaround) I need to avoid sharing a folder until I created the folder manually on all other peers with the same folder ID, which is a non-handy work. If I forget it I need to delete and recreate these folders on the other machine.

VERSION:
Syncthing Version: v1.3.0
OS Version: Ubuntu 18.04

**Comment by TechupBusiness** [comment]
What could I do as an attacker on a remote peer? OK I see, the attacker could override an existing syncthing folder or subfolder (it's like a syncthing folder in syncthing folder then). Isn't this sync-folder in sync-folder by remotes something which could be prevented (maybe by configuration)?

Because the only thing else an attacker could do is to create a long chain of folders (limited by a max label length) under my syncthing default folder

And when you use syncthing together with an service to share specific files with third parties (e.g. nextcloud/owncloud), the structure on the introducer remote peer is also important.

**Comment by AudriusButkevicius** [comment]
I've explained in the forum, the attacker could have the label as `../../../etc/` to get /etc/passwd

**Comment by calmh** [comment]
I'm OK with this inconsistency for now.
