### ISSUE TITLE
Change Web UI based on prefers-color-scheme

### ISSUE THREAD

**Issue by mx-psi** [syncthing/syncthing#6115]
### What happens

The Web UI has the same theme regardless of the preferred color scheme the user has set on their browser.

### What I expected to happen

The Web UI is dark when the [`prefers-color-scheme` property](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) is set to `dark` or the default one when it is `light` or `no-preference`.

### Version Information

Syncthing Version: v1.3.0
OS Version: Linux Mint 18.1
Browser Version: Firefox 70.0 64 bit

**Comment by AudriusButkevicius** [comment]
Please file a PR for this, this would need some changes what "default" means, and add a white theme.

**Comment by Ferroin** [comment]
From the perspective of an end user, I would expect 'default' as the selected theme to follow what `prefers-color-scheme` specifies (and have `no-preference` behave like the current 'default' setting), and a manually set theme to override what the property says.

I don't think we would need a new 'white' theme though, the current light theme is perfectly acceptable for general usage with `prefers-color-scheme: light`.

**Comment by AudriusButkevicius** [comment]
I mean light when I say white, but this does need to change what default means and how asset overriding works.

**Comment by kinyyyy** [comment]
I also encountered this problem.
the same  wrong records writed in syncthing frequently.This caused my C disk to have no space 
Maybe create a control to limit the size of logs?

**Comment by mx-psi** [comment]
@AudriusButkevicius I was going to file a PR but I am not sure on how to proceed. I could implement it in either of two ways:

My first idea was creating a default theme that imports the appropriate theme depending on a media query, something like:
```css
@import "path/to/white/theme.css" (prefers-color-scheme: light);
@import "path/to/dark/theme.css" (prefers-color-scheme: dark);
```
I think that would require changing the way assets are served since there is no way to access an asset outside of the current theme folder. The advantage of this setup is that the default theme doesn't need separate maintenance, it just links to the existing themes.

The second way of doing it is just creating a new CSS default file by adapting the white/dark theme files. This would require no changes to the server code but it would entail maintaining separately a new file. 

Which way do you think would be best? Is any of these what you had in mind?

**Comment by AudriusButkevicius** [comment]
Not sure, ideally something that does not break people with custom themes now.

**Comment by AudriusButkevicius** [comment]
My gut feeling was to check current theme, if its default, pass the preferred (from css) scheme in the headers, which would then drive the asset serving.

**Comment by mx-psi** [comment]
I have followed the first approach in the end. There is a proposal for passing the preferred color scheme in the HTTP request so that the correct assets could be served at request time (see w3c/csswg-drafts#4162), but as far as I know nothing like this is possible as of now.
