### ISSUE TITLE
Add conflict hook

### ISSUE THREAD

**Issue by BartG95** [syncthing/syncthing#6121]
Use case: I want to get notified when a conflict happens.

Currently, I sometimes find a .sync-conflict file somewhere, or I find such a file in the recently changed files. 

As a workaround, I could set up a cronjob that searches for ".sync-conflict"-files, but that feels redundant since Syncthing already knows when a conflict happened.

It would be nice if the gui shows a warning when a conflict happened it a folder.

It would be even better if I could specify a custom hook when it happens, in a similar fashion as the external versioning option. I am thinking about something like "notify-send %FILE_PATH%".

**Comment by AudriusButkevicius** [comment]
You can subscribe to the events API and "LocalChanges" events that notifies about conflict file creation.

**Comment by calmh** [comment]
Also #5601
