### ISSUE TITLE
Web GUI requests password in an uncomfortable way

### ISSUE THREAD

**Issue by MPeti1** [syncthing/syncthing#6122]
I've set up the Syncthing web GUI to require username and password to open it. Syncthing Tray handles it quite well, but if I want to log in to the web GUI from by browser I'll quickly find myself troubled.

What I expect to happen?
1. I enter localhost:8384
2. A login page appears, so I can use the Bitwarden plugin in my browser to automatically fill in the credentials, or at least to be able to copy the username and password from the plugin's window and paste them manually.
3. I successfully enter the web GUI

What happens?
1. I enter localhost:8384
2. A new window opens requesting for credentials, which blocks the whole browser UI, so I can't open any plugin's window
3. I click cancel, and close the tab
4. Copy the credentials from the Bitwarden plugin to notepad
5. Re-enter localhost:8384
6. Paste the credentials from notepad
7. I successfully enter the web GUI

This is even more boring since Syncthing Tray wants to open the web GUI on every single reboot for some reason. But this should be an other issue in the appropriate project.

### Version Information

Syncthing Version: v1.3.0
OS Version: Windows 10 1903
Browser Version: Firefox 70.0.1

**Comment by AudriusButkevicius** [comment]
Sadly, I think everyone else is at fault other than us. We use standard browser APIs to request credentials, there is nothing special in what we do.

You should raise it with the browser vendors to not block the browser ui when an auth prompt appears, or ask the plugin to implement credential population for auth prompts, or use a different plugin that deals with this, or just not use plugins.

**Comment by AudriusButkevicius** [comment]
Also, I think there already exists a ticket for moving from a basic auth prompts to a proper login dialog.

**Comment by calmh** [comment]
Duplicate of #4137
