### ISSUE TITLE
apt.syncthing.net missing 1.3.1 release (discovery & relay)

### ISSUE THREAD

**Issue by GermanCoding** [syncthing/syncthing#6128]
I'm using the https://apt.syncthing.net repository to keep my Debian/Ubuntu machines up to date. I've noted that v1.3.1 was released today - for syncthing, discovery and relay, but the apt.syncthing.net repository seems to be missing the last two.

I've manually checked the apt release file for amd64 - https://apt.syncthing.net/dists/syncthing/release/binary-amd64/Packages - and it doesn't list the new 1.3.1 release, except for the main syncthing binary.

**Comment by calmh** [comment]
Fixed, thanks.
