### ISSUE TITLE
GUI fails to render in chromium due to ERR_CONTENT_DECODING_FAILED error.

### ISSUE THREAD

**Issue by jakkso** [syncthing/syncthing#6159]
### DO NOT REPORT SECURITY ISSUES IN THIS ISSUE TRACKER

Instead, contact security@syncthing.net directly - see
https://syncthing.net/security.html for more information.

### DO NOT POST SUPPORT REQUESTS OR GENERAL QUESTIONS IN THIS ISSUE TRACKER

Please use the forum at https://forum.syncthing.net/ where a large number of
helpful people hang out. This issue tracker is for reporting bugs or feature
requests directly to the developers. Worst case you might get a short
"that's a bug, please report it on GitHub" response on the forum, in which
case we thank you for your patience and following our advice. :)

### Please use the correct issue tracker

If your problem relates to a Syncthing wrapper or [sub-project](https://github.com/syncthing) such as [Syncthing for Android](https://github.com/syncthing/syncthing-android/issues), [SyncTrayzor](https://github.com/canton7/synctrayzor) or the [documentation](https://github.com/syncthing/docs/issues), please use their respective issue trackers.

### Does your log mention database corruption?
No

### Please do post actual bug reports and feature requests.

If your issue is a bug report, replace this boilerplate with a description
of the problem, being sure to include at least:

 - **what happened**
When opening the GUI in chromium, instead of the page, I get the error:

     This site can’t be reached The webpage at http://127.0.0.1:8384/ might be 
     temporarily down or it may have moved permanently to a new web address.
     ERR_CONTENT_DECODING_FAILED
  
  This error does not occur when opening the GUI in safari, and the page is rendered and is functional.  

 - **what you expected to happen instead**
  For the GUI to be rendered in chromium, instead of a ERR_CONTENT_DECODING_FAILED error being thrown.  Preliminary google-ing reveals that this error may be caused by a head incorrectly asserting that content is gzipped when it is not.

 - **any steps to reproduce the problem.**
  Open the GUI in chromium 70.0.3538.

Also fill out the version information below and add log output or
screenshots as appropriate.

### Version Information

Syncthing Version: v1.3.1
OS Version: macOS Catalina v10.15.1
Browser Version:  Chromium | 70.0.3538.77 (Official Build) (64-bit)
    Revision | 0f6ce0b0cd63a12cb4eccea3637b1bc9a29148d9-refs/branch-heads/3538@{#1039}

**Comment by AudriusButkevicius** [comment]
This seems more like a support issue than an actual bug, as it can be caused by many things, such as reverse proxy, antivirus, etc, hence please use the [forum](https://forum.syncthing.net/) for support.

If this issue is later proven to be a bug, we will reopen this issue or open a new one.
