### ISSUE TITLE
Syncthing is using too much memory

### ISSUE THREAD

**Issue by MikiGrit** [syncthing/syncthing#6161]
### Please do post actual bug reports and feature requests.

Syncthing is using very large amounts of memory when syncing large files. I'm syncing 1,6GB file and Syncthing is using about 800MB of RAM which is troublesome because my server only have 512 MB RAM and it is obviously swapping very heavily during the sync time. It happens either on local network where max speed is very high but also through the internet where it is limited to about 1MB/s. The high usage is on the source side, client (where the file is syncing to) is fine (RAM usage is about 100-180MB there). The GUI is showing high RAM usage even when there is small amount of data left to sync (less than 400MB but RAM usage is still above 800MB). When the sync is finished it drops to standard 100MB.

It is only sync currently happening, there are two other devices connected, but fully synced. The synced directory have about 8GB and 10k files, majority of them very small (less than MB). There are four other directories (variety of sizes and file counts). And four other disconnected devices.

I'm seeing this behaviour for some time already (couple of months mabye, I'm not entirely sure).

### Version Information

Syncthing Version: v1.3.1
OS Version: Linux ARM

**Comment by AudriusButkevicius** [comment]
Check closed issues.

**Comment by calmh** [comment]
Duplicate of #6160
