### ISSUE TITLE
Send files

### ISSUE THREAD

**Issue by notramo** [syncthing/syncthing#6172]
Syncthing could be used as a file sending application, similar to [ShareDrop](https://www.sharedrop.io/), or [FilePizza](https://file.pizza/).
This would be one-time sending, not continuous syncing.

**Comment by imsodin** [comment]
Generally: Please use https://forum.syncthing.net/ to discuss ideas for additional functionality - once they are clearly mapped out an issue can be created.

Specifically: There's a lot of things Syncthing could do, but for this there's other tools that already do it well. Syncthing is all about continuous sync.
