### ISSUE TITLE
Panic loop on startup - handling index for nonexistent folder -  v1.3.2-rc.2 

### ISSUE THREAD

**Issue by alyandon** [syncthing/syncthing#6174]
Syncthing auto-updated itself earlier this morning and entered a panic loop during startup on one of my Ubuntu 18.04 LTS hosts.  I have several other Ubuntu 18.04 LTS hosts that all appear to have updated and restarted without issue.

I've attached a sanitized copy of the crash log and the relevant error line in the log is:

```
[A6CDR] 08:34:48 WARNING: Index for nonexistent folder "default"
Panic at 2019-11-21T08:34:48-06:00
panic: handling index for nonexistent folder
```

Syncthing Version: v1.3.2-rc.2
OS Version: Ubuntu 18.04 LTS
Browser Version: n/a

I'll delay attempting to recover for a while if you'd like me to try troubleshooting further.

**Comment by alyandon** [comment]
[sanitized-panic-20191121-083448.reported.log.gz](https://github.com/syncthing/syncthing/files/3875252/sanitized-panic-20191121-083448.reported.log.gz)

**Comment by alyandon** [comment]
I used `-reset-database` to rebuild the database and that appeared to resolve the issue.  I have kept a copy of the old database if anyone is interested.

**Comment by Pavel8419** [comment]
is interested to me and who know me
--
Sent from Mail.ru app for Android Friday, 22 November 2019, 00:38AM +03:00 from Shelby Cain  notifications@github.com :

**Comment by calmh** [comment]
```
Panic at 2019-11-21T08:34:48-06:00
panic: handling index for nonexistent folder

goroutine 143 [running]:
github.com/syncthing/syncthing/lib/model.(*model).handleIndex(0xc0000ccf20, 0x8b18e3c43c52617, 0x66637a3234244fa0, 0xe61f2cfffe53f05e, 0x4a087c90203c550f, 0xc000bda090, 0x7, 0xc000af2000, 0xad, 0x133, ...)
	/opt/tcagent/syncthing-3-work/174e136266f8a219/lib/model/model.go:1025 +0xf7e
github.com/syncthing/syncthing/lib/model.(*model).Index(0xc0000ccf20, 0x8b18e3c43c52617, 0x66637a3234244fa0, 0xe61f2cfffe53f05e, 0x4a087c90203c550f, 0xc000bda090, 0x7, 0xc000af2000, 0xad, 0x133)
	/opt/tcagent/syncthing-3-work/174e136266f8a219/lib/model/model.go:993 +0x8c
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).handleIndex(0xc000089380, 0xc000bda090, 0x7, 0xc000af2000, 0xad, 0x133)
	/opt/tcagent/syncthing-3-work/174e136266f8a219/lib/protocol/protocol.go:543 +0x1ea
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).dispatcherLoop(0xc000089380, 0x0, 0x0)
	/opt/tcagent/syncthing-3-work/174e136266f8a219/lib/protocol/protocol.go:397 +0xbe7
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).Start.func1(0xc000089380)
	/opt/tcagent/syncthing-3-work/174e136266f8a219/lib/protocol/protocol.go:234 +0x2b
created by github.com/syncthing/syncthing/lib/protocol.(*rawConnection).Start
	/opt/tcagent/syncthing-3-work/174e136266f8a219/lib/protocol/protocol.go:233 +0x65
```

**Comment by alyandon** [comment]
@calmh Sounds like you have a good working theory and don't need a copy of the leveldb store then?

**Comment by calmh** [comment]
Yeah, this is recently introduced, no need for more data, thanks.

**Comment by imsodin** [comment]
Oh ..., this is a side-effect of https://github.com/syncthing/syncthing/pull/6135. Starting the folder is delayed due to metadata recalculating:

```
[A6CDR] 08:34:46 INFO: Stored folder metadata for "ara2x-rkjzr" is 821h9m19.750871738s old; recalculating
```

So connecting and exchanging cluster configs is faster than starting the folder. This can happen regardless of #6135, but it's much more likely now. Before that change folders were started before connection handling was even set up. So for 1.3.2 maybe just revert that one commit. For the next release, I still intend to fix the underlying problem (racyness of config changes vs connections/cluster configs).

**Comment by alyandon** [comment]
Just an FYI - this issue hit another host and it seems there is some problem with your crash reporting service:

`[monitor] 16:39:21 INFO: Reporting crash found in panic-20191122-153325.log (report ID 59a949c4) ...
[monitor] 16:39:22 WARNING: Reporting crash: upload: 500 Internal Server Error
`

**Comment by calmh** [comment]
I've backed out that change and will release a 1.3.3-rc.3.

The crash receiver had ran out of inodes... 😬 

```
root@data:~# df -i /dev/sdb
Filesystem      Inodes   IUsed IFree IUse% Mounted on
/dev/sdb       1638400 1638400     0  100% /mnt/crash_reports
```
