### ISSUE TITLE
Small UI enhancements

### ISSUE THREAD

**Issue by mateossh** [syncthing/syncthing#6178]
I am using Syncthing since two days and I already found some UI inconsistencies / bugs.

1. Textarea in "Logs" uses font called "Consolas", but when user don't have this font installed on device, browser will load other serif font instead of monospace.
2. In about view - Syncthing logo doesn't scale on mobile (e.g is way too big on my Motorola Moto G5)
3. In about view on mobile - text in "dependency list" sometimes overlap on each other.

Screenshots below for better visualization

![a](https://user-images.githubusercontent.com/17083034/69465989-1ad0f480-0d83-11ea-8f7e-1085f9934ffe.jpg)

![b](https://user-images.githubusercontent.com/17083034/69466002-20c6d580-0d83-11ea-8117-a2fa92a9836f.jpg)

I already prepared fixes for those "issues" and I have a question. Should I send all those 3 fixes as one PR, or should I create 2 PRs for "Logs" and "About"?

### Version Information

Syncthing Version: 1.3.1
OS Version: Arch Linux and Android 8.1.0
Browser Version: Firefox 68.0.2 and Google Chrome 75.0.3759.4 on Linux + Chrome 78.0.3904.108 on Android

**Comment by AudriusButkevicius** [comment]
It's up to you, you can send one big PR as mobile improvements, or separate PRs, whatever is easier for you.

Thanks for your time.
