### ISSUE TITLE
Deal with non-existing paths due to drive not mounted

### ISSUE THREAD

**Issue by halfgaar** [syncthing/syncthing#6179]
I want to create a Syncthing volume on a mounted drive. There is a good chance it won't be mounted, however, because it's encrypted (LUKS). It requires auto-unlock with a key server, or manual intervention.

Syncthing tries to recreate sync folders when the root is missing. This poses problems:

- It will try and fail, saying: 2019-11-23 11:59:28: Failed to create folder root directory mkdir /mnt/hddvolume/halfgaar: permission denied. 2019-11-23 11:59:28: Error on folder "inmountpoint" (wllp3-tpvb9): folder path missing 
- It will try and succeed, re-syncing the contents into the empty mount point.

I think re-creating the folder is not the best decision. It could be an option, but should require user intervention. There are any number of reasons drives are unavailable. They could be removable, for instance.

Expected behavior: folder is paused. Currently that's what happens, merely because it has no permission. It's marked as 'stopped' and it even starts again after a rescan. But, because of the permission issues, that's unintended behavior.

v1.3.1, Linux (64 bit)

**Comment by AudriusButkevicius** [comment]
It only recreates the folder if it has never seem anything in the folder. If it has any files in the index it will blow up with folder marker missing error and recover when the folder reappears.
