### ISSUE TITLE
Fantastic App

### ISSUE THREAD

**Issue by compusolve-rsa** [syncthing/syncthing#6182]
This app is most welcome, thank you to the devs. You guys rock for creating this.

A small issue on android fyi.

Android 6.0 has an external sdcard write restriction, and the-awesome-syncthing can't write .stfolder. As a work around, is it possible to have a "Syncthing" folder on the internal sd as a default where all .stfolder(s) are kept? This would provide a way to get around the write restriction on android 6 and still get external sdcard folders syncing.

Comments welcome.

Lee

**Comment by AudriusButkevicius** [comment]
This is the wrong repository, and support related matters are discussed on the forums.
