### ISSUE TITLE
Button for Lan ONLY

### ISSUE THREAD

**Issue by compusolve-rsa** [syncthing/syncthing#6184]
Hi Guys

I have noticed that when disabling relays to force lan use only, syncthing doesn't behave very well.

Is it possible to implement a button on the main interface to toggle exclusive lan use?

Typical usage is when I am logged into wifi at work, I don't want syncthing to use works data-bundle since we are capped and the boss does grumble about gigs usage.

**Comment by imsodin** [comment]
I believe this is a subset of https://github.com/syncthing/syncthing/issues/6130: That issue talks about scheduled or toggled rate limits. By default they apply to non-LAN only, so setting those limits to 0 and the toggling would also fulfill this need. In any way it makes sense to track both in one issue, such that whoever will implement either of those is aware of the full wishlist - thus closing in favor of #6130.

**Comment by compusolve-rsa** [comment]
awesome
