### ISSUE TITLE
[Feature Request] More complex ignore patterns

### ISSUE THREAD

**Issue by StevenDoesStuffs** [syncthing/syncthing#6195]
Currently, I develop with JS and Rust, and ignoring node_modules is easy enough, but I'd also like to ignore Rust's target folder (the build cache and results). The thing is, target isn't a rare or specific folder name like node_modules, and I'd like to only ignore the targets folder if the folder containing it contains a Cargo.toml. It'd be great if syncthing supported something like that

**Comment by calmh** [comment]
There are some things that could be improved with the ignore system. However, I can quite confidently say that we will not support ignoring based on parent-folder-also-has-file-like-this patterns. Apart from the niche-ness of the case, it's not technically possible. We need to be able to decide whether any given file or directory should be ignored directly when we see an update to it from a peer. That means the decision can be based only on that item itself. We can't wait to see if the peer is also going to announce another file at some other place in the hierarchy before processing it.

(When scanning files locally it would be technically possible, but that's only a part of where ignores are processed.)
