### ISSUE TITLE
Syncthing native startup crash with exitNoUpgradeAvailable on Android

### ISSUE THREAD

**Issue by cthu1hoo** [syncthing/syncthing#6196]
This happened on a latest Syncthing-fork (Catfriend1/syncthing-android) off play store which uses Syncthing native 1.3.2-preview1: https://github.com/Catfriend1/syncthing-android/releases/tag/v1.3.2.3

Here's the debug log:

[SyncthingNativeCode.txt](https://github.com/syncthing/syncthing/files/3896459/SyncthingNativeCode.txt)

I tried restarting the device to make sure there were no multiple syncthing binaries actually running but it didn't help.

Previous wrapper version which included Syncthing v1.3.1 works properly.

**Comment by imsodin** [comment]
Please report to https://github.com/Catfriend1/syncthing-android

**Comment by cthu1hoo** [comment]
I already did and he told me to report here.

https://github.com/Catfriend1/syncthing-android/issues/571#issuecomment-559030873

**Comment by AudriusButkevicius** [comment]
The log is partial and does not explain the reason for the crash.

**Comment by cthu1hoo** [comment]
https://github.com/Catfriend1/syncthing-android/issues/571#issuecomment-559045876

**Comment by imsodin** [comment]
Just for completeness also here: It's the problem fixed in v1.3.2-rc.3
