### ISSUE TITLE
Cache the disk state (avoid rescanning after every syncthing startup)

### ISSUE THREAD

**Issue by unfa** [syncthing/syncthing#6199]
I am syncing hundreds of gigabytes between two machines (desktop and laptop).

I've hit a performance problem however - every time I reboot one of the machines, Syncthing will perform a full scan of all these files to make sure nothing changed.

I wish Syncthing could cache it's scan results and initialize from that during the next startup.

I would manually rescan the directories if anything didn't latch on properly, but doing this scan from the ground up every time puts a big strain on my system and is very time consuming.

I realize it's very important for Syncthing to be aware of the filesystem status, but I think a cache would be a good option to have.

**Comment by calmh** [comment]
Yep. #5353.
