### ISSUE TITLE
Synching gets stuck at 99% - potentially due to ignore pattern and deleted files (?)

### ISSUE THREAD

**Issue by adam-ah** [syncthing/syncthing#6208]
I'm running 3 syncthing instances:
- Ubuntu 1.3.1
- MacOS 1.3.2
- Windows 10, 1.3.2

I wanted to sync across mainly from the MacOS to the other devices around 20Gb and 110k files.

During the initial sync, I noticed that I should remove the MacOs's crap (.DS_Store folders).
So first I deleted that recursively on the Mac, then added it to the Mac's ignore pattern (.DS_Store).

The Linux caught up just fine, but the Windows machine seems to be out of sync when viewed on Mac's browser, but in sync, when viewed from the Windows's browser.

Restarting syncthing on the Mac or the Windows box did not resolve the problem.
Adding .DS_Store to the Windows's ignore pattern also did not resolve the problem.

Other files are still synching fine from Mac to Windows.

The log files on the Mac seem to be okay, no errors reported.

The reported files that are out of sync are actually missing from the MacOS machine.

![Screen Shot 2019-12-03 at 8 42 23 pm](https://user-images.githubusercontent.com/3745745/70039812-a150c600-160e-11ea-8173-014f9f0668fb.png)

![Screen Shot 2019-12-03 at 8 42 17 pm](https://user-images.githubusercontent.com/3745745/70039871-b299d280-160e-11ea-8606-e723c73cee95.png)

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.

**Comment by adam-ah** [comment]
No problem, @AudriusButkevicius. I've uninstalled synthing and will use a different product. Cheers.
