### ISSUE TITLE
Discovery should announce v4 and v6 addresses, preferably over the relevant protocols itself

### ISSUE THREAD

**Issue by davidstrauss** [syncthing/syncthing#621]
I'm having trouble debugging why my laptop (at the office, IPv4 NAT and full IPv6) cannot find my cloud server (public IPv4 and full IPv6) -- or the other way around. Both are listed as "online" for discovery.

Having the following information in the logs (at the normal INFO level) would help a lot:
* List which addresses are being published for discovery
* List which addresses are found for remote nodes (and whether connection succeeds)

**Comment by AudriusButkevicius** [comment]
This is actually now fixed.

**Comment by hobarrera** [comment]
@AudriusButkevicius: Is there any issue for tracking that?

**Comment by AudriusButkevicius** [comment]
Not sure. I think tgis specific issue is solved only by announcing via ip6 subject the gateway doesn'tdo encapsulation.

**Comment by hobarrera** [comment]
@AudriusButkevicius Not for dualstacked hosts. For dualstacked hosts to announce themselves properly, we'll need two discovery servers (eg: `ipv4.discover.syncthing.com` and `ipv6.discover.syncthing.com`).
