### ISSUE TITLE
ppc64le Not appearing at data.syncthing.net

### ISSUE THREAD

**Issue by cwross** [syncthing/syncthing#6211]
OS: Debian 10.2
CPU/platform: ppc64el (OpenPOWER 9)
Syncthing version: v1.3.2, Linux (PowerPC (LE))

I have anonymous usage reporting turned on (v3), and have for some months now, but I never see ppc64le appear as a platform with users at the https://data.syncthing.net stats page. I see numerous other platforms/OSes with 1-5 users, so I'm wondering what's happening.

Troubleshooting: I have tried both v2 and v3 usage reporting. No difference. I have verified in the logs that usage reports are supposedly being sent:

01:10:53 INFO: Sent usage report (version 3)

I have also confirmed that my network is not blocking connections to *.syncthing.net at the DNS level (pi-hole).

Happy to do more troubleshooting if someone can nudge me in the right direction. Since ppc64le is a relatively obscure platform, I just want to make sure we get counted!

**Comment by calmh** [comment]
The platform summary shows up to five child items per operating system. I think we probably didn't have much more than five linux archs at the time. I can increase that limit.

**Comment by calmh** [comment]
There you go; you're the one. :)

<img width="567" alt="Screen Shot 2019-12-03 at 21 34 58" src="https://user-images.githubusercontent.com/125426/70087535-ce07dc00-1614-11ea-956e-357dbe5e7a18.png">

Together with your mips brethren.

**Comment by cwross** [comment]
Cool, thanks!
