### ISSUE TITLE
Bug report with Capitalization in Windows 10

### ISSUE THREAD

**Issue by glilienthal** [syncthing/syncthing#6218]
I delete a file "a.cfg" and replaced it with "A.cfg". - This caused a lot of problems, and stopped syncing. 

### Version Information

Syncthing Version: v1.3.2
OS Version: Windows 10

**Comment by glilienthal** [comment]
maybe additional input: the files were identical.

**Comment by glilienthal** [comment]
to be more precise: There were to files copies in the folder "a.cfg" and "A.cfg" and then they were deleted and "A.cfg" added. That caused the confusion.

**Comment by glilienthal** [comment]
This was originally caused by https://github.com/ec429/SPEngine/archive/master.zip

**Comment by AudriusButkevicius** [comment]
Please search the existing bug tracker before opening new issues

Duplicate of #1787
