### ISSUE TITLE
The 'Needed Files' modal doesn't display a progress bar

### ISSUE THREAD

**Issue by AkaZecik** [syncthing/syncthing#6219]
I'm downloading one huge file and when clicking on `Out of Sync Items`, the modal appears, but it doesn't show too much:

![bug](https://user-images.githubusercontent.com/22799031/70583619-8e199980-1bbe-11ea-8ad4-e840ff0662e5.png)

On the right side there is only a number `734MiB`. Looking directly into the code, there is a progress bar at that position that is shown only in some cases. I forced it to show up and it had meaningful data.

I found that the object describing the file has a property `f.type == 'rest'`. Indeed, querrying `/db/need` returns a single file marked as `rest`. The progress bar would show up only if it was `progress` instead of `rest`. Relevant code:
* [gui/default/syncthing/transfer/neededFilesModalView.html:39](https://github.com/syncthing/syncthing/blob/325c3c1fa7b8d4b59e3c16057756b679723971d6/gui/default/syncthing/transfer/neededFilesModalView.html#L39)
* [gui/default/syncthing/core/syncthingController.js:610](https://github.com/syncthing/syncthing/blob/325c3c1fa7b8d4b59e3c16057756b679723971d6/gui/default/syncthing/core/syncthingController.js#L610)
* [gui/default/syncthing/core/syncthingController.js:590](https://github.com/syncthing/syncthing/blob/325c3c1fa7b8d4b59e3c16057756b679723971d6/gui/default/syncthing/core/syncthingController.js#L590)

I made sure the file is being downloaded.

I suppose `/db/need` should return `progress` instead of `rest`, so this might be an issue with a backend.

Is this a bug? And if so, can I work on it?

---
Syncthing Version: `v1.3.2+33-g5e74e12b-dirty-6044, Fermium Flea`
OS Version: `Ubuntu 18.04 (64 bit)`
Browser Version: `Firefox 70.0.1 (64-bit)`

**Comment by calmh** [comment]
This is #5867 (so I'm going to close this as duplicate), and I'd be super happy if you would like to work on it. :)

**Comment by calmh** [comment]
It does sound like some internal confusion about the progress/queued/rest state. The distinction as far as I remember is that "progress" are things we are currently syncing, "queued" are things in the sync queue, and "rest" are needed files that we have not queued (because we (used to?) limit the size of the queue). So yeah this might be a bug not in the GUI but with how we report the data from the puller...

**Comment by AndrewSav** [comment]
@calmh @AkaZecik [processNeeded](https://github.com/syncthing/syncthing/blob/master/lib/model/folder_sendrecv.go#L309) is asynchronous function it start the puller but it resets the queue on exit, on the line linked. Naturally, jobQueue.Jobs won't return anything in progress, so [NeedFolderFiles](https://github.com/syncthing/syncthing/blob/master/lib/model/model.go#L964) clasiffy everything as "rest" and "rest" is what you are getting from that rest/db/need API call.
