### ISSUE TITLE
How about the performance of synchronizing large files, such as 500GB, and this file has been growing rapidly

### ISSUE THREAD

**Issue by xilutian** [syncthing/syncthing#6221]
How about the performance of synchronizing large files, such as 500GB, and this file has been growing rapidly

**Comment by xilutian** [comment]
How about the performance of synchronizing large files, such as 500GB, and this file has been growing rapidly. Can real-time synchronization and incremental synchronization be achieved, that is to say, only the added parts can be synchronized

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
