### ISSUE TITLE
Block sync

### ISSUE THREAD

**Issue by abidal3** [syncthing/syncthing#6229]
Please add ability to sync large files block by block.
So that when several blocks in file are changed then only these blocks are synchronized but not the whole file.
As it was in BitTorrent Sync.

**Comment by wweich** [comment]
We already do: https://docs.syncthing.net/users/syncing.html#blocks

**Comment by abidal3** [comment]
> We already do

do or done?

**Comment by AudriusButkevicius** [comment]
Please check the docs, it's all explained there.

**Comment by abidal3** [comment]
> Please check the docs, it's all explained there.

how can I check that only changed blocks are updated but not the whole file?

> Syncthing never writes directly to a destination file. Instead all changes are made to a temporary copy which is then moved in place over the old version. 

why create a full copy of large file if need to update only several blocks?
or is a copy created only at initial sync but not at the update?

**Comment by AudriusButkevicius** [comment]
This is not a place to ask question, Bug tracker is for reporting bugs.
The issue template (which you completely ignored) explains where you should ask questions.

**Comment by abidal3** [comment]
> This is not a place to ask question, Bug tracker is for reporting bugs.

in many projects all questions can be asked directly on Github
probably need to create a separate account on the forum

**Comment by uok** [comment]
@abidal3, please head over to https://forum.syncthing.net if you have any questions
You can also log in with your Github account.

**Comment by abidal3** [comment]
> @abidal3, please head over to https://forum.syncthing.net if you have any questions
> You can also log in with your Github account.

thanks :)
