### ISSUE TITLE
GUI/Usability enhancement: directory picker button for 'add folder' -> 'folder path'

### ISSUE THREAD

**Issue by shanks1337** [syncthing/syncthing#6242]
1. Open Syncthing
2. Add folder

actual:
When changing the sharing directory path, the user needs to type out the path from memory. Novice users might not know their own folder structure. 
![Sycthing dir picker](https://user-images.githubusercontent.com/8984284/71533521-80238280-28f9-11ea-93b2-a46070019fea.png)

expected: 
Syncthing offers a directory picker button on the right side which opens a dir picker dialog.

**Comment by AudriusButkevicius** [comment]
Dup of #2958.

This software has been around for a while, so if it looks like an obvious improvement, someone most likely already suggested it, therefore please search existing issues before opening new ones.
