### ISSUE TITLE
filename is invalid

### ISSUE THREAD

**Issue by icf20** [syncthing/syncthing#6243]
hi i was moving from resillio sync and now i have a issue with > 

in resillio sync those characters got replaced with _ in win machines while keeping > on linux

for some odd reason syncthing dont does that replacement, is there any solution other than renaming thousands of files?

**Comment by imsodin** [comment]
Please use https://forum.syncthing.net/ for support.

**Comment by AudriusButkevicius** [comment]
Sadly there is no solution for this. 

Please check for existing issues before opening new ones. Dup of https://github.com/syncthing/syncthing/issues/1734

**Comment by icf20** [comment]
@AudriusButkevicius 

1 that is closed

2 for send only folders much of the complaining there is irrelevant

**Comment by AudriusButkevicius** [comment]
It's not closed, it's just locked as people went to bike shedding territory. 
The issue is the same, invalid file names are invalid, regardless of which folder type we are talking about.

**Comment by icf20** [comment]
> It's not closed
i call BS on that

![image](https://user-images.githubusercontent.com/17784575/71545870-ba8c2e80-2990-11ea-9bbd-f32da7a54027.png)

**Comment by icf20** [comment]
btw if anyone cares about this _( since in the other duplicate discussion there was no discussion after the lock, it looks like only users actually cared )_

having a space at the end of a file also is invalid in windows so having a lock"space" file is impossible

**Comment by imsodin** [comment]
I am now also locking this. Again, if you want more information (than what can already be found in the linked duplicate), feel free to start a topic on https://forum.syncthing.net/.
