### ISSUE TITLE
Remove unnecessary RAM/CPU stats from GUI

### ISSUE THREAD

**Issue by gabriel-fallen** [syncthing/syncthing#6249]
As long as (big) files synchronization (especially initial one) is IO-intensive task I'd like to see IO (hard drive) utilization in the Web UI along the CPU and memory lines.

---

Subject edited from initial "add I/O stats" to "remove existing crap", adding note here as the initial post is otherwise rather confusing // @calmh

**Comment by calmh** [comment]
I’m very much in favor of doing the opposite and removing CPU/RAM from the UI instead. Every operating system has utilities to report on these things and there is no real reason we should be duplicating it I think?

**Comment by AudriusButkevicius** [comment]
Sort of agree, also, it's usually misreported.

IO in general doesn't even have an API for most OSes

**Comment by tomasz1986** [comment]
> I’m very much in favor of doing the opposite and removing CPU/RAM from the UI instead. Every operating system has utilities to report on these things and there is no real reason we should be duplicating it I think?

Being able to see how much CPU and RAM is used by Syncthing does come in handy when administering it remotely through a Web browser though.

**Comment by gabriel-fallen** [comment]
@calmh removing all the system stats altogether is an option too.

On the other hand being very well aware of `htop` and using it on a regular basis I still found it handy that Syncthing shows its own resource consumption right in the Web UI and I somewhat missed the IO stats.
