### ISSUE TITLE
Syncthing stops working when syncing 50k+ files

### ISSUE THREAD

**Issue by makdee88** [syncthing/syncthing#6251]
Syncthing stops working while replicating folders with 50k files over internet.

The folder is on network share. Windows 7 SP1.

Attaching logs. 
[syncthing_failing_error.txt](https://github.com/syncthing/syncthing/files/4022211/syncthing_failing_error.txt)

**Comment by imsodin** [comment]
The logs are truncated at the beginning, and thus miss the information about the actual crash. Without it there is unfortunately nothing to be done. If you do have the full log, you can reopen the bug and post it.

**Comment by AudriusButkevicius** [comment]
You should post in on the forums tho.
