### ISSUE TITLE
Data loss: Older file replaces new version without conflict file copy

### ISSUE THREAD

**Issue by nrbray** [syncthing/syncthing#6252]
# What happened,

'looked' at text file using Markor on Android device - saw was old version  
'looked' at syncthing on (same) Android device was working fine but may have been dormant / not synced for a while due to power saving or other Android 'feature' 
'looked' at text file using Markor on (same) Android device - not changed  
'looked' at text file on PC latest file is overwritten by old version and no conflict file present  

# What you expected to happen instead

 conflict detected with a copy of the latest text file  

# Any steps to reproduce the problem.  

I think this has happened before to me, I assume, but would need help to capture logs etc:  

1. Is Android Syncthing dormant and does not see the new version?
2. Does Markor 'write' to the old file when it is opened?
3. Perhaps Syncthing on Android treats the old file as a new change
4. Maybe Syncthing on PC does not 'know' that Android has not taken the latest version (but assumes if has)

# Comment  

If long time dormant syncthing devices come on line and offer 'touched' files since their last sync, do they by design overwrite without conflict detection other files more recently synced but older 'touch' times?

# Version Information

Syncthing Version: v1.3.2, 
OS Version: Linux (64 bit) 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Browser Version: n/a Android Syncthing  '1.3.2' 3 December 2019

# Related?

https://github.com/syncthing/syncthing/issues/3258

**Comment by AudriusButkevicius** [comment]
Can you come up with a reliable way to reproduce this? In a new isolated folder, with a step by step guide.

Also, on android, in the web ui rather than app, check what max conflicts is set to (as I don't think the app ui exposes that setting).

**Comment by nrbray** [comment]
I think I will be able to come up with a reliable way to reproduce this, with a step by step guide.  It may take me some time so hope you can bear with me until I get to it.

**Help!** Max conflicts are 10 on my PC from looking at config.xml.  I cannot find the value using the web ui and not found how to by searching the documentation.  It is a bit of a pain finding the config.xml inside Android but will look.

**Comment by AudriusButkevicius** [comment]
It's in advanced config in the web ui.

**Comment by nrbray** [comment]
Sorry no joy, feeling I am missing something!  I have 12 folders 15 devices, if I choose Actions - Advanced I see:
GUI
...
Options
Folder ...
... x12
Device ...
...x15
[Save] [Close]

Sorry, also not finding the location of config.xml in Android that quickly.. a find -name '\*syncthing\*' on the mounted folder (Internal storage) only gives ../Internal storage/Android/data/com.nutomic.syncthingandroid/files

**Comment by nrbray** [comment]
Android: <maxConflicts>10</maxConflicts>
Sorry but the version there is 1.3.1

**Comment by AudriusButkevicius** [comment]
If you expand one of the folders, there will be max conflicts somewhere there.

**Comment by AudriusButkevicius** [comment]
Ok then get the steps of reproduction

**Comment by lessneek** [comment]
I had the same issue, there could be a conflict but on my main PC my database of KeePass with a new password record was replaced with an old version of the database from other device (android or notebook). I have a simple file versioning and database file was replaced by old file and no version was created nor conflict file... wut is it? I don't know how to reproduce this. May be I shall try if someone will want to do some research of the bug with me. Looks like a serious bug, because I have completely lost my important data.

**Comment by AudriusButkevicius** [comment]
So android does not support adjusting mtimes, so we have virtual timestamps to try and work around that.
What's worse, when you create a file, android reports timestamps with 1s precision, but it's all fake and in memory, when you reboot, the precision drops down to 2s accuracy due to fat32.

I am almost willing to bet money android is the cause here.

If you can reproduce it reliably, we could have a look at this, but until then 🤷‍♂ , be angry at google.

**Comment by Umanoid1** [comment]
Buongiorno, ho provato il progamma ultima versione sia win che android, e fatto la singronizzazione tra win10 e android SD come invia e ricevi, i file e cartelle di android sono stati sinc nella cartella win ma in andoid non ci sono piu e neanche in windows, dove cavolo sono andati ha finire? che per me sono importanti e li vorrei recuperare, se qualcuno degli sviluppatori gentilmente mi puo aiutare ha risolvere il mio problema, non so se valutarlo disistallarlo dare una brutta recensione e neanche donazione puttroppo ho avuto una brutta esperienza, non e possibile che sono spariti i file non mi era mai capitato una cosa del genere essendo una connessione nella stessa mia rete lan, oppure sono stati dirottati saluti.

**Comment by imsodin** [comment]
@Umanoid1 The language used in this project is English, please don't post in any others. And most likely you want to post to https://forum.syncthing.net/ first to determine what exactly your problem is - when it is a bug, we can always open an issue on github.

**Comment by camgraff** [comment]
Was there any resolution / reliable reproduction steps reached for this?

I am having the same issue with Markor + syncthing. What is strange is that the old version of the file is ~very old~. I.e. all of my 3 syncthing devices will have the newest version. Then, overnight my Android will somehow overwrite back to a version that is several days old. And this is also only for one file in my shared folder.
