### ISSUE TITLE
can not delete repository 

### ISSUE THREAD

**Issue by jerome-diver** [syncthing/syncthing#6254]
# There is a "delete" item selection on repo right click menu...

 When user try to delete an existing repo, it should just remove it (without delete the linked directory but maybe ask for recovery storage directories to be deleted with or not). Instead, it doesn't do nothing.

![try to delete repo](https://user-images.githubusercontent.com/11176132/71805283-298b1680-3066-11ea-9fc4-2fae6f360a52.png "Delete repo or not ?")

Syncthing Version: v1.3.2-1
OS Version: archlinux
Browser Version: gtk or web ui the same

## How to reproduce:

1. create a repo to sync

1. add a remote computer to synch with from this new repo configuration

1. allow new repo to sync from remote computer defined one step before

1. define the directory linked with sync new repo on remote machine

1. let them sync...

1. during process, delete a repo from remote or from master machine doesn't delete repo (and that is to bad).

## How to remove it ?

1. open xml syncthing config file from local home directory .config/syncthing/config.xml

1. remove repos manualy does delete theml also on the gtk and web ui.

**Comment by AudriusButkevicius** [comment]
This is the wrong repo, gtk has it's own repo.

**Comment by jerome-diver** [comment]
@AudriusButkevicius Hi and happy new year...
What do you mean, it is not clear ? I create these repos from gtk GUI there, and i can not remove them from there ? Why, if this is "wrong repos" (what does it mean "wrong repo" ?) if they then exist inside .config/syncthing/config.xml file and then why when i remove them from there they disapear from GUI to ?
Please, try to be more clear instead of close so quickly this issue post.

**Comment by AudriusButkevicius** [comment]
Wrong git repo: https://github.com/syncthing/syncthing-gtk
