### ISSUE TITLE
apt.syncthing.net 404

### ISSUE THREAD

**Issue by Artanicus** [syncthing/syncthing#6257]
See title. apt.syncthing.net is a 404 which kills any package installation.

**Comment by Artanicus** [comment]
Example how people may see this on Debian/Ubuntu:
```
E: The repository 'http://apt.syncthing.net syncthing Release' no longer has a Release file.
```

**Comment by daprice** [comment]
Most documentation links in the readme to docs.syncthing.net also return 404

**Comment by AudriusButkevicius** [comment]
I'll check it in a sec.

**Comment by AudriusButkevicius** [comment]
Should be fixed.
