### ISSUE TITLE
Cannot open GUI on the server

### ISSUE THREAD

**Issue by simonwangtx** [syncthing/syncthing#6259]
Cannot open GUI in the browser after deploying  Syncthing into my server.

For example, my server's IP is 10.179.42.200, however I can't get access via 10.179.42.200:8384 although there are logs in the terminal: "Access the GUI via the following URL: http://127.0.0.1:8384/"

**Comment by simonwangtx** [comment]
I just wondering if the IP address is set to localhost or 127.0.0.1 instead of 0.0.0.0 ?

**Comment by simonwangtx** [comment]
WOW, I should use the -gui-address=<address> parameter to set the IP.

**Comment by AudriusButkevicius** [comment]
Also, the issue template explains the correct channels for support.
