### ISSUE TITLE
'Receive only', but still send conflict files?

### ISSUE THREAD

**Issue by maks-io** [syncthing/syncthing#6262]
### Version Information

Syncthing Version: v1.3.1
OS Version: Fedora 31

### Feature request
Hi everyone,
I am owning multiple devices with multiple folders, I call them clients - I want to keep all of them in sync, and every client is allowed to make changes (send & receive). Furthermore I have a server running, which I set to "receive only" - this server's purpose is to be the master, always being awake and ready to propagate changes of any client to all the remaining clients. So far, so good.
However, I just realized, that due to the fact, that the server is "receive only", it also won't send any conflict files to the clients, and this is where my feature request comes in:
It would be nice to set a machine to be "receive only" but with the exception of still allowing it to forward/send any conflict files.
Why? Well, I just spent 30 minutes trying to figure out why I cannot see any conflict files on any client, even though I edited the same file on two different clients, both while they were offline. At a later point in time, they both went online again, but non of them showed any conflict files. It really puzzled me, until I looked at the server's state, and there it was, the expected conflict file. Of course I would want those to be forwarded to all the clients.
As already said, if this is somehow possible already (without setting the server to "send & receive"), please tell me, and ignore this redundant feature request.

Thank you!

**Comment by AudriusButkevicius** [comment]
I am closing this as this should be on the forum. To me it seems you want a send receive folder on the server essentially.

**Comment by imsodin** [comment]
I believe there might be something to this, see https://forum.syncthing.net/t/conflicts-on-receive-only-folders/14321
