### ISSUE TITLE
folder marker could be removed by git stash and not re-created

### ISSUE THREAD

**Issue by msg7086** [syncthing/syncthing#6266]
1. Share a folder managed by git.

2. Run `git stash save --include-untracked`.

3. Run `git stash pop`.

4. `.stfolder` will be deleted and not re-created due to it's an empty folder.

Git is probably at fault for not recovering the empty folder, but it can be worked around by putting a placeholder inside the folder. For example, `.stfolder/.keep`.

### Version Information

Syncthing Version: v1.3.3

OS Version: Windows 10

**Comment by AudriusButkevicius** [comment]
As you say, not our bug.
