### ISSUE TITLE
Out of sync panel layout overflows

### ISSUE THREAD

**Issue by Xeenych** [syncthing/syncthing#6268]
Sometimes Out of sync List overflows.

![98b14f0f16c568817eff122ff38a830a087377ab](https://user-images.githubusercontent.com/11345848/72284035-1b825a80-3651-11ea-9eea-0b4107431394.jpeg)

Looks like the first filename is too long

v1.3.2, Linux (64 bit)
Chrome 79.0.3945.117 (64 бит)

**Comment by avignat** [comment]
Dup #5473
