### ISSUE TITLE
data.syncthing.net is not accessible from Russia

### ISSUE THREAD

**Issue by crazyh** [syncthing/syncthing#6269]
It looks like data.syncthing.net (165.227.145.99) is blocked in Russia on IP layer so Syncthing does not collect any statistics for users from Russia. It caused due to blocking by government of some of DigitalOcean subnets like 165.227.0.0/16.

```sh
$ ping -w 60 data.syncthing.net
PING data.syncthing.net (165.227.145.99) 56(84) bytes of data.

--- data.syncthing.net ping statistics ---
60 packets transmitted, 0 received, 100% packet loss, time 59794ms
```

Most other endpoints are accessible. At least the following ones:

- discovery.syncthing.net
- relays.syncthing.net
- stun.syncthing.net

### Version Information

Syncthing Version: v1.3.3

**Comment by calmh** [comment]
That's unfortunate, but seems to be a problem at the source rather than the destination. I'm not sure what you're suggesting we would do about it.

**Comment by crazyh** [comment]
@calmh data.syncthing.net could be pointed to other region or you can use . It seems that 198.211.0.0/16 (stun.syncthing.net) and 82.196.0.0/16 (relays.syncthing.net) subnets are accessible.

> That's unfortunate, but seems to be a problem at the source rather than the destination.
Yeah, but usage report is indeed to be useful for developers, not for end users. I just wanted to point that Syncthing does not count all active users.

**Comment by calmh** [comment]
So data.s.n is in their FRA1 dc because it was one of the first to offer extra block storage, while the other machines are in AMS2/AMS3. It’s not trivial to move but maybe we can CDN it. I’ll take a loon today.

**Comment by calmh** [comment]
Seems more trouble than I think it's worth, unfortunately. Despite that we still get enough data to put Russia as the #10 country, so it's not all lost.
