### ISSUE TITLE
REST API event filtering not working

### ISSUE THREAD

**Issue by DoruLa** [syncthing/syncthing#6271]
I am using postman with Syncthing's REST API to get the events and I am unable to filter the list to get only the events I want.

I am trying: 
http://127.0.0.1:8384/rest/events?events=ItemFinished

And after a long time, the list comes back empty, even though on a call with no parameters there is more than one ItemFinished event in the list.

This also happens if I add multiple event types separated by "," or if I use another type such as ConfigSaved.

Tested both on Windows and MacOS. Same results.

Syncthing Version: v1.3.3
OS Version: Windows 10/64 bit, MacOS Mojave

**Comment by calmh** [comment]
What is sort of mentioned at https://docs.syncthing.net/rest/events-get.html#events-get but not stressed or clearly described is that specifying a set of events creates a new subscription for those events. This means that you will not see events emitted before you made the first call with this event list, only events that happen afterwards -- when the subscription in question exists.

**Comment by DoruLa** [comment]
Thank you for the help. Indeed, it is not that clear that only new events will be fetched, but with a bit more testing I should have been able to figure that out. Sorry for the trouble. Closing the issue now.
