### ISSUE TITLE
INFO: Connected to myself (NBCMLIZ) at [::]:22000-【myIP】:54072/quic-client/TLS1.3-TLS_AES_128_GCM_SHA256 - should not happen

### ISSUE THREAD

**Issue by lzpswat** [syncthing/syncthing#6273]
Keep prompting this. How should i fix it？

[](url)
win10
v1.2.0, Windows (64 bit) 
syncTrayzor

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
