### ISSUE TITLE
Misleading GUI ip address in log for container image

### ISSUE THREAD

**Issue by tyll** [syncthing/syncthing#6275]
### Does your log mention database corruption?

no

### Please do post actual bug reports and feature requests.

When running the container image without setting the STGUIADDRESS variable, the container logs:

```
20:28:23 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
```

This looks like the socket is bound to localhost but it is not in the image by default. This is in my opinion misleading.

### Version Information

Syncthing Version: syncthing v1.3.3 "Fermium Flea" (go1.13.5 linux-amd64) docker@syncthing.net 2019-12-08 12:31:26 UTC
OS Version: CentOS 7
Browser Version: (if applicable, for GUI issues)

**Comment by calmh** [comment]
There's a line just above this one that says which address it's *bound* to. *This* line suggests an URL that might work to access the GUI. (Whether that actually works in the Docker case then depends on a port forward, but this behavior is the same whether it's in Docker or not.)
