### ISSUE TITLE
Synthing generates conflicts for identical files

### ISSUE THREAD

**Issue by torrbox** [syncthing/syncthing#6287]
I synced a large folder of 1TB between two devices.
I wanted to move the folder on one device, so I deleted it in syncthing on that device.
Syncthing browser GUI then notified me that the other device is sharing this folder.
I added the folder and this time selected the desired folder location, after having moved (drag+drop) all files from the old folder to the new folder.

Syncthing verifies 950GB correctly, which took an hour, and then says 50GB are out of sync and creates conflict duplicates.

However, the conflict duplicates are identical with the files it claims to be out of sync.  They have the same modified time (shown in Windows Explorer) and the same md5 hash.

edit: It seems as if the "duplicates" are just copies of the files? It only downloaded 15MB from the other device to determine that there is a conflict and to create all the "duplicates", now it's uploading them to the other device (which I know is intended, but where did it get the "duplicates" from??)

### Version Information

Syncthing Version: Newest for Windows and Ubuntu (from apt.syncthing.net)
OS Version: Windows 10 and  Ubuntu 18.04

**Comment by AudriusButkevicius** [comment]
I think you should start a thread on the forum as it's not clear whats happening here, what the cause or the bug is. Perhaps you just misconfigured something.

**Comment by torrbox** [comment]
> 
> 
> I think you should start a thread on the forum as it's not clear whats happening here, what the cause or the bug is. Perhaps you just misconfigured something.

I didn't configure anything. Just launched the original syncthing (browser GUI) on both devices and synced a folder. Then relocated the folder on one device by deleting it and re-adding it.

Both folders were identical on both devices, yet it claimed about 50GB are out of sync and created duplicates.

Could it be a hardware issue? File corruption? (I am using SSDs) If so, which device is at fault? The one that creates duplicates and uploads them to the other device?

**Comment by AudriusButkevicius** [comment]
As I said, issue tracker is not the right place to ask questions. Issue tracker is for tracking reproducible/quantified bugs, so don't expect answers.
