### ISSUE TITLE
But I only want that one file! (bump sync priority rfe)

### ISSUE THREAD

**Issue by jpjp** [syncthing/syncthing#629]
Tonight I opened my laptop, fired up the web gui for syncthing, and watched as all of my files were updated. Opening the out-of-sync items list I see the only file I need waiting to be synced across - behind everything else.

How great it would be, I thought, if I could bump that single file that I need right now, right to the top of the list.

**Comment by uok** [comment]
I noticed this in the source code, but I have never seen it in action. What needs to happen so that this feature becomes active?

**Comment by AudriusButkevicius** [comment]
there is now a arrow in the needed file list which allows bumping a file.

**Comment by uok** [comment]
That would be great, but somehow this arrow is never visible. I click on "out of sync (x items ~ x GB)" -> "needed files modal" opens (with list of items and progress bars in red, green, orange, etc.). I see the button in index.html but during runtime browser (and also firebug) does not show the line "<span ng-if="$index != 0"...." as active

**Comment by AudriusButkevicius** [comment]
Can you post a screenshot as I am not clear exactly.

**Comment by uok** [comment]
> If there are only two files, you won't see the arrow

ok, noted (this was the case) - after adding more files the button was displayed correctly.

Would you be so kind and change the `<span ... </span>` to `<a .... </a>` because currently the icon is only text and does not indicate that you can click it. Also a `title="{{'Move to top of queue' | translate}}"` attribute would help usability.

**Comment by AudriusButkevicius** [comment]
Please open a separate issue, as this will get lost forever. 
Also to be honest, you could make a pull request, given you know how to do it.

**Comment by uok** [comment]
ok, will do
