### ISSUE TITLE
Allow symlinks for https-cert.pem and https-key.pem

### ISSUE THREAD

**Issue by dhwalker** [syncthing/syncthing#6294]
It'd sure be nice if symlinks were allowed for https-cert.pem and https-key.pem in ~/.config/syncthing on Linux.  I keep an annually-renewed cert (and its private key) in a fixed placed on my home server and link to it for multiple services from wherever each services needs it.  Syncthing, however, requires the cert and key files to be stored in ~/.config/syncthing, which makes the annual updating harder.

**Comment by calmh** [comment]
We don't do anything special to prevent it, and symlinking them works fine when I tried now. What do you see that makes you think we don't allow it?

**Comment by AudriusButkevicius** [comment]
Closing this for now until OP responds.

**Comment by dhwalker** [comment]
My apologies; closing this is the right thing to do. I don't know why it didn't work for me at first, but it does now.  I was running a pretty old version of syncthing from the Linux Mint 19 repository at the time I had trouble, and I've switched to the repository for current releases since then.
