### ISSUE TITLE
Syncthing 1.3.3 fails to synchronize large files

### ISSUE THREAD

**Issue by adolfintel** [syncthing/syncthing#6296]
I have 2 devices, one called Normandy (my home server) and one called Neema (my laptop), I have several shared folders between them.
If I add a large (few GB) file to a folder, my laptop fails to synchronize with the home server. The logs show this:

###### Normandy (home server)
The log contains several of these entries
```
Jan 26 17:31:04 normandy syncthing[29562]: [] INFO: "LPG" (7fjia-dvsoh): Failed to sync 4 items
Jan 26 17:31:04 normandy syncthing[29562]: [] INFO: Folder "LPG" (7fjia-dvsoh) isn't making sync progress - retrying in 16m3.035038612s.
Jan 26 17:31:09 normandy syncthing[29562]: [] INFO: Folder "LPG" (7fjia-dvsoh) isn't making sync progress - retrying in 32m5.064967131s.
Jan 26 17:39:01 normandy syncthing[29562]: [] INFO: Established secure connection to __NEEMA'S ID__ at 192.168.1.197:22000-MY_EXTERNAL_IP:47724/tcp-server/TLS1.3-TLS_AES_128_GCM_SHA256
Jan 26 17:39:01 normandy syncthing[29562]: [] INFO: Device __NEEMA'S ID__ client is "syncthing v1.3.3" named "Neema" at 192.168.1.197:22000-MY_EXTERNAL_IP:47724/tcp-server/TLS1.3-TLS_AES_128_GCM_SHA256
```

###### Neema (laptop)
The log contains several of these entries
```
[] 17:29:46 INFO: Established secure connection to __NORMANDY'S ID__ at 192.168.1.199:47164-MY_EXTERNAL_IP:29319/tcp-client/TLS1.3-TLS_AES_128_GCM_SHA256
[] 17:29:46 INFO: Device __NORMANDY'S ID__ client is "syncthing v1.3.3" named "Normandy" at 192.168.1.199:47164-MY_EXTERNAL_IP:29319/tcp-client/TLS1.3-TLS_AES_128_GCM_SHA256
[] 17:29:46 INFO: Connection to __NORMANDY'S ID__ at 192.168.1.199:47164-MY_EXTERNAL_IP:29319/tcp-client/TLS1.3-TLS_AES_128_GCM_SHA256 closed: reading length: EOF
```

### Version Information

Syncthing Version: v1.3.3
OS Version: Ubuntu Server 18.04 (Normandy), Manjaro Linux (Neema)

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
