### ISSUE TITLE
Fix the "out of sync items" modal

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#630]
- It shouldn't be much longer than the screen. Scroll instead.
- Long filenames shouldn't screw it up.
- It should be keyboard closable. (#508, #498)

**Comment by marclaporte** [comment]
Also, it sometimes takes quite a bit of time to show the list of files. And thus, the user will think there is an error / bug. Suggestion: add a spinner until files are listed.

About the scroll: perhaps an "Infinite scroll" ?

Thanks!

**Comment by calmh** [comment]
Adding that the click targets for #629 shouldn't move around so that it's a game of luck and dexterity to prioritize the file you want... :)

**Comment by AudriusButkevicius** [comment]
Superseeded by #1509
