### ISSUE TITLE
Avoid thundering herd issue by global request limiter

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#6302]
We have a per-connection request limiter today to limit the number of concurrent requests we handle for any given connection. However, there's no global equivalent. This is a problem in large setups. For example, if I have 250 connected devices and announce a change to a new large file, I'll immediately get 250 (num clients) * 16 MiB (block size) * 2 (defaultPullerPendingKib) requests, requiring 8 GiB to buffer. Then we need to marshal, TLS encrypt and send these, getting us easily up 32 GiB or so of memory usage. Rate limits and such will only make this worse as we will hold on to the memory for a long time while we slowly send out the responses.

We should have some sort of global request limiter that limits the number of in flight requests we process, in total, at any given moment.

**Comment by xjtdy888** [comment]
Should we consider only requesting a small piece of each block at a time, for each block of data we can request different pieces from multiple devices at the same time, similar to bittorrent

**Comment by AudriusButkevicius** [comment]
We already do that. The problem here is not related to that, it's the fact that when someone advertises a file, every other device hits that one device because no other device has that file yet.

Over time this balances out, as other devices start having chunks of the file you can now fetch from them, but the initial big hit is still there, and this is what this ticket is about.

**Comment by uok** [comment]
I understand what @calmh means.
Maybe related: Torrent clients use "initial seeding" to send each chunk of a new file only once.
http://bittorrent.org/beps/bep_0016.html

**Comment by calmh** [comment]
We can't in general assume that other devices can or will talk to each other. We might be the one who will need to serve 250 copies of the data by ourselves. That's fine, we just need to not fall over while doing it.
