### ISSUE TITLE
Device name and other fields not shown in "New Device" message

### ISSUE THREAD

**Issue by midnightdim** [syncthing/syncthing#6307]
In #6304 I reported a part of my current configuration.

In the UI of device B which runs on Debian the UI shows the "New Device" messages like this:

![изображение](https://user-images.githubusercontent.com/6467552/73659440-d938c000-46c8-11ea-86c1-de08833839b8.png)

As far as I remember it displayed the full info previously but at some point started to show it like this. On other devices this issue doesn't occur.

**Comment by calmh** [comment]
Looks like I18N failed to apply. What does the javascript console say?

**Comment by midnightdim** [comment]
Doesn't seem to show anything suspicious.

![изображение](https://user-images.githubusercontent.com/6467552/73661496-bc9e8700-46cc-11ea-8b95-545b98ca1241.png)

**Comment by midnightdim** [comment]
Also, in Advanced settings on both devices A and B I see this:
![изображение](https://user-images.githubusercontent.com/6467552/73714143-93b8d900-4742-11ea-8306-397aa57ee802.png)

**Comment by imsodin** [comment]
That's unrelated: https://github.com/syncthing/syncthing/issues/4569

**Comment by AudriusButkevicius** [comment]
I suggest trying a different browser, I am fairly confident this is due to plugins/paranoia mode on the browser.

**Comment by midnightdim** [comment]
Tried on a different browser (Chrome) - worked fine indeed.
It's strange that on Firefox it worked with this issue on one device and without it on another.

**Comment by AudriusButkevicius** [comment]
Closing as it's clearly an issue with the browser and its configuration. Suggest you disable plugins one by one, or verify it works ok in safe mode.
