### ISSUE TITLE
Ignore deletes on files older than $AGE

### ISSUE THREAD

**Issue by tysonclugg** [syncthing/syncthing#6308]
**Feature request: Ignore deletes on files older than `$AGE`.**

I use Google Photos on my Android devices to share media with my family, and Syncthing to ensure I have an independent backup in case [something](https://techcrunch.com/2017/12/22/that-time-i-got-locked-out-of-my-google-account-for-a-month/) [happens](https://www.businessinsider.com.au/markiplier-youtube-fans-heist-lost-access-google-accounts-spamming-emotes-2019-11).  Google Photos has an option to "Free up space on your device" which results in [files older than 30 days being deleted](https://support.google.com/photos/answer/6128843).

Syncthing has an [ignoreDelete option](https://docs.syncthing.net/advanced/folder-ignoredelete.html) per folder, which is a binary flag.

Add an option that modifies the `ignoreDelete` behaviour to actually delete files within a specified `$AGE`, such that if I take an *unwanted* photo (ie: something I *don't want kept in backup*), then the photo can be deleted before it gets to `$AGE`, and my Syncthing backup of the file will be deleted.

**Comment by calmh** [comment]
Date based ignore patterns have come up before and have significant issues. This is slightly more limited in scope but I'm not overly enthusiastic. Keeping it open nonetheless to think about it for a while. :)

**Comment by AudriusButkevicius** [comment]
This would turn syncthing into some sort of backup oriented application, which it is not, it just syncs files with no questions asked, hence I think this sort of feature is out of scope for syncthing. You can always achieve similar behaviour by getting something external to delete the files.

**Comment by tysonclugg** [comment]
@calmh  Assuming you're referring to date based ignore patterns [as discussed in the forum](https://forum.syncthing.net/t/date-age-ignore-pattern/11475), are you suggesting that feature configured such that new files are ignored, only to be synchronised after they are at least `$AGE`?  If so, that's not what I want, since my data would be vulnerable for a period of time.  I'm instead suggesting that DELETE events could be ignored/filtered based on the age of the existing file.  I understand the DELETE event may arrive well after the file was actually deleted, but in the context of a 30 day window, that'd be fine.

@AudriusButkevicius Adding an option wouldn't change the core premise of what Syncthing is.  I consider file synchronisation to be a piece of the backup puzzle, and Syncthing does a great job of fulfilling the important task of copying between various devices.  I still use ZFS/BTRFS/DVD/... snapshots for backing up, but I need to get the files onto the relevant backup server first.  Having said that, sometimes sensitive information makes it onto disk and needs to be removed - that's what this feature request is all about.

An alternate solution would be to provide more context to the external file versioning tool, so that my tool would know the difference between a delete to make way for a new file version vs a plain old delete.  Is this a reasonable compromise?

**Comment by AudriusButkevicius** [comment]
Sure, cron scheduling and other things, is not against the spirit of file synchronization either, but it's against the spirit of simplicity. 

IgnoreDelete's is already an antifeature that makes things look out of sync/weird, I'd be against adding another one of these that screwup the view of the world for others.

External versioner supports templating, we could add a new template variable that declares the type of operation I guess, but I don't really see why you can't do this deletion from outside.

**Comment by AudriusButkevicius** [comment]
I am going to close this, as I think it doesn't really needs to be in syncthing and can be done externally.

**Comment by tysonclugg** [comment]
I don't see how this can be done externally for my use case, unless the external file versioning template variables are updated to provide more context to the external tool.  There is currently no context as to why the tool has been invoked (ie: delete to make way for new version, or delete entirely).

The only external solution I can think of would be to maintain a database of what has was archived by the external versioning tool, and periodically go back and delete files that didn't reappear after some defined period of time when we're confident that we're up to date and the file isn't going to be replaced.  At which point the daily backup would have already been taken, negating the point of the whole convoluted process.

Having the external versioning tool know the intent of the delete would make things much more straightforward.  Would you accept a pull request with the required template variable changes?

**Comment by AudriusButkevicius** [comment]
Yeah, additional template change seems fine, yet I suspect the surface area of the pr might end up big, but thats fine.
