### ISSUE TITLE
Relay high CPU usage correlating to GO GC-Cycle

### ISSUE THREAD

**Issue by 0xpr03** [syncthing/syncthing#6312]
I'm operating a syncthing relay openly and can see CPU-Spikes and massive open-sockets drops every 2 minutes. This seems to relate perfectly with GOs maximum GC-Cycle of 2 minutes.

It would be very good if we could reduce the CPU spikes as I can provision my resources much better for constant CPU usage than for spikes that will slow down other systems seemingly random.

46 Session with 559 connections.
strelaysrv v0.14.18-dfsg1
OS Version: Debian 9

![image](https://user-images.githubusercontent.com/1280209/74088494-6ac47b00-4a97-11ea-9c14-1cee7cec0fba.png)
![image](https://user-images.githubusercontent.com/1280209/74088503-79129700-4a97-11ea-93cd-a785d88a124e.png)

Purple is the syncthing relay.

**Comment by AudriusButkevicius** [comment]
Please try a new version, the one you are using is fairly old. If you still have issues, please open a thread on the forums.

**Comment by 0xpr03** [comment]
For anyone else having this problem and no chance of upgrading strelay on a system:
```
[Service]
# [. . .]
Nice=5
CPUQuota=100%
``` 
Add this to the service
