### ISSUE TITLE
Feature request: precomp for efficient transfer of compressed files

### ISSUE THREAD

**Issue by M-Gonzalo** [syncthing/syncthing#6314]
AFAIK syncthing uses the LZ4 algorithm to compress data transparently. Like any other general-purpose algorithm, it cannot compress several of the most used and synchronized file types, such as PDF documents, JPG images, MS Office's docs, Libreoffice's docs, *.tgz backups, MP3s and so on. It'll probably make them even bigger, adding overhead.

[Precomp](https://github.com/schnaader/precomp-cpp) is an open source program that takes care of exactly that, using several different algorithms to achieve a significant compression on otherwise incompressible files. It can even find re-compressible data inside an unknown or composite format. 

Please consider integrating it on syncthing, since it can lead to a faster experience (albeit at the cost of some CPU). It will also help a lot on mobile connections, making synchronisation noticeably cheaper.

I have vast experience using and testing it so I can help with that side of the integration should you need it.

**Comment by AudriusButkevicius** [comment]
Sorry, but I don't think this is worth the effort, for the marginal gains this would bring. Our bottleneck is hash verification using sha256, compression/decompression is negligible/meaningless in that context.

**Comment by M-Gonzalo** [comment]
@AudriusButkevicius 

Thanks for your quick reply! I don't believe the gains are marginal at all, on the contrary... Look at some stats here below. We're talking GBs of content that simply can't be compressed with the actual method, or with any other for that matter.

Hash verification times are negligible if we take into account transfer times on non-local networks. For me the bottleneck is actually uplink, and I suspect that is the case also for a lot of other people. Mind you, precomp _**is**_ slower than lz4 by all accounts, only the amount of data to transfer is reduced greatly so there's the speed-up. Moreover, compression time shouldn't even affect overall speed, because it can be done deferred on a buffer using a helper thread.

These numbers are from real folders with content from my mobile device and personal computer. I already optimized the files with [ect](https://github.com/fhanau/Efficient-Compression-Tool) and [other tools](https://nikkhokkho.sourceforge.io/static.php?page=FileOptimizer) so the gains should be greater, especially for DOCs, and about 22% for JPGs in average instead of 17%.


![image](https://user-images.githubusercontent.com/23223606/74107351-9ace5580-4b4d-11ea-8f54-3ef8a634f334.png)

**Comment by AudriusButkevicius** [comment]
So syncthing uses what one would call an open protocol. Open protocols are built on things that are available to many languages so they can be implemented by anyone, atleast that's the spirit behind most decisions.

Precomp is not even a library, it's a C++ command line application that does not seem reusable in any sensible way other than shelling out, whic

Furthermore, from what I am reading, it's decompressing and recompressing things multiple times, which seems like it's generally a terrible thing for people who have proper uplinks and want to send data fast, as most of the time

To add to that, syncthing compresses at the message level in the protocol, not at the file level, so even if we wedge in this magical thing it, at best, it would compress 128kb-4mb of files data (even if it's a large file). At that point, what the tool does doesn't even work, as it's decompresses whole files and re-compresses them, not protocol sized chunks.

Lastly, syncthing already tries to optimise and not send data when it does not need to.
For example if you append a new line to a text file, syncthing will only send the last few kilobytes of the file. Now when you start compressing them, small change in the uncompressed payload usually changes most of the compressed data, forcing syncthing to resend the whole file, even if it would not have needed to if the file was uncompressed. 
This is the reason why we compress at the message level, after we worked out which parts need sending, and compressing the individual parts.

**Comment by M-Gonzalo** [comment]
You're right, it was a library, now that's broken.

Now this, on the other hand, is not correct:
> At that point, what the tool does doesn't even work, as it's decompresses whole files and re-compresses them, not protocol sized chunks.

Precomp does process chunks of arbitrary size, and they don't need to be  complete files. I do understand the need of doing that inside memory, though, and that's where it falls short for now.

Anyways, I see it's not a good fit for the project at the current stage, so thanks anyway for the thorough reply!
