### ISSUE TITLE
Use `diff` to compare versions of text files and display in Web UI

### ISSUE THREAD

**Issue by bminer** [syncthing/syncthing#6332]
## Feature Request

It would be pretty cool to compare versions of files within the web UI, especially text files using the `diff` utility (or similar JS lib).  I don't really know how cross platform the feature could be, but perhaps Syncthing could scan the `PATH` for `diff` (or run `which diff`) and enable the feature wherever `diff` is available.  Or, like I mentioned previously, a JavaScript library to render file differences may already exist.

I foresee a few use cases:

- When you click "Versions" button, you can search for a prior version of a file and compare it to the latest global state using `diff`.
- When a folder is "Receive only" and you have local additions, being able to diff those against the global state would be neat

Thoughts?

Also, I am a huge fan of Syncthing, and I tell everyone about it.  What a neat tool!  Keep up the great work!

**Comment by AudriusButkevicius** [comment]
Sorry but no, we sync files without caring what they are. We're not going to start diffing files, providing editors for merging etc.

**Comment by bminer** [comment]
OK, no worries.  Thanks for your feedback!
