### ISSUE TITLE
Syncthing snap editing of ignore-file is blocked by apparmor

### ISSUE THREAD

**Issue by theHilikus** [syncthing/syncthing#6334]
I'm trying to one-way sync my home folder with another device (just as a kind of backup, not to really use the sync'ed version of the home folder in both machines) but there are some folders that I want to ignore. When I try to edit the "Ignore patters" in the web UI, they are never saved. If I edit them in the filesystem and then try to edit them in the web UI, it says that file cannot be read: `Failed to load ignore patterns.`
The problem is apparmor blocking that. In syslog I see

> Feb 12 18:57:50 foo kernel: [12348.484178] audit: type=1400 audit(1581551870.392:115): apparmor="DENIED" operation="open" profile="snap.syncthing.syncth
ing" name="/home/hilikus/.stignore" pid=3188 comm="syncthing" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000

Is this intended? I've used this same instance to sync things in my home folder before. What I have never done before is try to sync the *whole* home folder

Syncthing Version: v1.3.4 (snap)
OS Version: Ubuntu 19.10
Browser Version: Chrome 80.0

**Comment by calmh** [comment]
Snaps have some sort of sandboxing, but I think ours is supposed to be able to access the home directory.

**Comment by calmh** [comment]
Apparently this is intended, as the `home` plug only grants access to the non-hidden parts of `~`. So not only can't Syncthing create the .stfolder or read the .stignore, it also can't access any other dotfiles or dotdirs in there.
