### ISSUE TITLE
ignore local changes for "Receive Only" folders (feature request)

### ISSUE THREAD

**Issue by phloggu** [syncthing/syncthing#6338]
In some situations it would be desireable to not keep local changes in "Receive Only" folders. If local changes happen in a "Receive Only" folder in the current implementation manual intervention is needed: There appears a button "Revert local changes" to overwrite them. It is not possible to configure a "Receive only folder" that automatically overwrites all local changes without asking.
I would like to suggest a new option for "Receive Only" mode to always silently overwrite local changes. This could be a checkbox "overwrite local changes silently" appearing underneath "Folder type" if the type is set to "Receive only" (in edit folder -> advanced), defaulting to not checked. Another way to show the requested new feature in the GUI would be to define a new folder type of "Shadow Copy" or "Cloned Folder".

**Comment by calmh** [comment]
This is not going to happen, why has been discussed ad nauseum on the forum. You can script it: https://www.kastelo.net/blog/2018-08/syncthing-recv-only-folders/
