### ISSUE TITLE
Syncthing reports bad version, confusing other clients

### ISSUE THREAD

**Issue by georgespatton** [syncthing/syncthing#6340]
On Ubuntu 19.10 the package in the official Ubuntu repos report an unknown version, likely an issue with the build process.  Here is the issue from the Ubuntu bugzilla:

https://bugs.launchpad.net/ubuntu/+source/syncthing/+bug/1847018

Syncthing Version: syncthing unknown-dev "Erbium Earthworm" (go1.12.9 linux-amd64) unknown@unknown 1970-01-01 00:00:00 UTC
OS Version: Ubuntu 19.10 
Browser Version: N/A

**Comment by imsodin** [comment]
Right, and that's why the issue report is at the right place at the link you posted, not here. As the last comment there says: Our packages (apt.syncthing.net) work. If there's any questions about building, please ask them on the forum.

**Comment by georgespatton** [comment]
Understood, didn't know if you had control over that build process or not.
