### ISSUE TITLE
[Feature] Add Only folder

### ISSUE THREAD

**Issue by dzmitry-lahoda** [syncthing/syncthing#6345]
Current behavior of `Receive only` as per documentation is to replace, add, or delete files as source says.

Proposed behavior of `Add Only` is to add or replace only from source.

**Why?**

I have laptop from which I want to send files onto big storage. When I delete from laptop - big storage keeps files locally. I wan to keep these files on laptop for some time, before deleting. 

My case is torrents downloaded to laptop and propagated onto big torrent storage.

**Alternatives?**

A. `rsync` or other tools need more setup and configuration.

B. `rsync` from laptop to storage prevents using syncthing p2p discovery mechanics.

C. `rsync` from `Send & Receive` of storage to another folder on storage needs proper detection of syncthing ended upload, and I should not delete file before `rsync` did the work. Source of issues here.

D. drop `torrent` files into `syncthing` synced to folder tracked by `qbittorrent`. Will work, but only for torrent files. I have not only these.

**Comment by imsodin** [comment]
This is already possible (see below), however it is an advanced setting for a reason: Your device will look out of sync to others. Generally there's often a better solution to a use-case than (ab-)using Syncthing for this - please post to the forums to get help on this.

See `ignoreDelete` folder config (https://docs.syncthing.net/users/config.html#folder-element), which does what you want.

**Comment by dzmitry-lahoda** [comment]
>> ignoreDelete 
>>Your device will look out of sync to others

so the feature could be have ignoreDelete without out of sync issue. i.e. given we have  ignoreDelete sync type than non deleted files under this type of sync are still in sync state.
