### ISSUE TITLE
Feature request: Smart/Adaptative Resource Usage

### ISSUE THREAD

**Issue by rvalle** [syncthing/syncthing#6351]
# The Problem

I love syncthing but the truth is that I end up disabling it most of the time.
My laptop is often on heavy loads and syncthing seems to add up significantly and disproportionally.  
On 99% of the situations I really don't care how quick the Sync takes place, as long as it eventually gets there.

With regards to HD usage,  I backup my mobile with Syncthing and you end up with huge videos that can actually be deleted, however, my laptop will be drained right in the middle of the working day... which effectively forces me to stop my work and start watching and selecting videos before I can continue working.

I find these problems a real deal breaker in terms of user friendliness and could potentially have a lot of impact on mass adoption by the general public.

### New feature description

Syncthing should be capable to throttle the resource usage and adapt it to current system workload.

For example never go over 20% CPU and disable syncing when general system load goes over 50% CPU, things like that. Different rules could be applied if the user is present of if the computer is idle.

Similarly Syncing should not drain HardDisk down to 0 bytes left, but stop the sync on when fiesystem free space is less than a given %.

The order of the sync folders in the UI could also be used to give some sense of priority to the tasks. Even some tasks could be ticket as low priority.

I could be possible to boost resource usage for that 1% of situations in which you actually need a sync file to arrive. In that case the boost period could be automatically finished when sync is complete or after a given period. Boosting particular syncs could also be good.

### Version Information

Syncthing Version: v1.3.4
OS Version: Fedora 31
Browser Version: (if applicable, for GUI issues)

**Comment by imsodin** [comment]
You bring up quite a few related but different aspects, some of which are already possible currently, others clearly out of scope and probably also a few which need further discussion/clarification. Please open a discussion on https://forum.syncthing.net/. If a clearly scoped feature request emerges from that, a github issue can be opened.

**Comment by rvalle** [comment]
OK: https://forum.syncthing.net/t/feature-proposal-smart-adaptative-resource-usage/14531
