### ISSUE TITLE
Make receive timeout configurable

### ISSUE THREAD

**Issue by GermanCoding** [syncthing/syncthing#6357]
This is a feature request for a new advanced config setting.

Currently, the receive timeout for a syncthing connection is hardcoded to [five minutes](https://github.com/syncthing/syncthing/blob/40e1835927032e4232c75210ed31981281ebde1c/lib/protocol/protocol.go#L198).

In my (altough probably special) use case, I often find myself switching between VPN networks on my computer. This causes the interfaces, ip addresses, routing etc to change, thus killing all connections - including syncthing. The local syncthing instance gets notified immediatly - the OS reports that the connection is down and syncthing bails out.

However, my remote syncthing peers never get notified that the connection has been torn down and thus still think the connection is all fine and running. Only after the global read timeout times out the connection is finally closed on the remote side. In the meantime, my local syncthing instance attempts to reconnect 4-5 times (as the default reconnect loop is 60 seconds - note that this is in fact configurable), but gets repeatedly rejected by the remote peer, as that believes that there's already an existing connection (which is false).

So it takes 5 minutes after a VPN change before syncthing finally re-establishes connections. I sometimes roam between VPNs in about ~10 minute intervalls, which means that I'm disconnected about 50% of the time (or more) due to the long 5 minute timeout.

A smart solution would detect that the old connection is dead and accept the new connection, but a configurable receive timeout would already work for most scenarios I believe. For example, I could set the receive timeout to 60 seconds, which would cut down disconnect times from 5 minutes to  ~1 minute.

Changing the receive timeout may also require changes to the ping send intervall (haven't looked at the specific code yet), so that could either depend on the receive timeout or be configurable as well.

**Comment by calmh** [comment]
> A smart solution would detect that the old connection is dead and accept the new connection

I think this is the correct solution...

**Comment by calmh** [comment]
I think the connection suddenly breaking somewhere in the middle yet being able to reconnect would be quite rare. One endpoint moving to a new IP due to network roaming seems much more likely.

**Comment by MikolajTwarog** [comment]
I would like to take this issue. Do you want me to add an option to change receive timeout?

**Comment by GermanCoding** [comment]
This issue has two possible approaches:

1. My original thought, just add an advanced config option
2. Or, the (admittedly better) solution, "detect that the old connection is dead and accept the new connection" - which seems to be favored by calmh

I proposed the first point, because I thought that was easier to implement than the second option. However, if the maintainers want the better solution that's fine for me - both approaches solve (my) issue either way.

It's up to the maintainers to decide what they would accept, if needed I can reword the issue to reflect the other approach.

**Comment by GermanCoding** [comment]
Since https://github.com/syncthing/syncthing/issues/5224 is now closed, I'm not sure if this is needed anymore. I think I'm going to close this for now even though I haven't tested the new code yet.
