### ISSUE TITLE
Leveldb uses too much memory

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#6374]
This is a profile from a newly started device that is accepting index updates from other connected devices (long chain of red boxes omitted):

<img width="847" alt="Screenshot 2020-02-27 at 12 25 14" src="https://user-images.githubusercontent.com/125426/75440566-4bb15e80-595c-11ea-9f79-eb582e24a186.png">

<img width="292" alt="Screenshot 2020-02-27 at 12 25 34" src="https://user-images.githubusercontent.com/125426/75440571-4e13b880-595c-11ea-9b1b-7416da1d70bc.png">

There are 14 folders but many devices. The number of folders is relevant because `db.FileSet` locks on the `Update()` so regardless of the number of incoming index updates we can't have more than 14 in flight at any given time towards the database. This reflects in that the update blocks and we can see there are only 64 MB of buffers allocated for incoming index updates.

Nonetheless the db layer holds on to over a gig in mem buffers as a result of the updates. I struggle to understand why.

(1.4.0-rc.7 fwiw)

**Comment by imsodin** [comment]
> [...] we can see there are only 64 MB of buffers allocated for incoming index updates.

That's not how I interpret the screenshot: There seems to be one initial index (right) and lots of index updates (left, probably 13) going on. It doesn't match entirely, as 13*64=832 < 1166, but it's not off by much.

**Comment by calmh** [comment]
My bad, the 64 MB buffers thing was my misinterpretation and completely irrelevant. The observation that we have 14 transactions @ 64 MB plus overhead makes sense, that's probably very close to what's actually going on and comes down to the large database tuning thing.
