### ISSUE TITLE
"panic: Blocks is nil, but BlocksHash is not" during upgrade

### ISSUE THREAD

**Issue by Echsecutor** [syncthing/syncthing#6375]
# what happened

Syncthing apparently crashed on 2020-02-22 leaving a panic report. Since then, I am unable to start it since it panics during upgrade during startup.

# what you expected to happen instead

Normal startup

# any steps to reproduce the problem

In my case, just starting syncthing leads to the panic.

### Version Information

```
syncthing v1.4.0-rc.6 "Fermium Flea" (go1.13.8 linux-arm) teamcity@build.syncthing.net 2020-02-22 08:37:21 UTC
```

OS Version:
```
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie
```
[panic-20200222-103604.reported.log](https://github.com/syncthing/syncthing/files/4261528/panic-20200222-103604.reported.log)

[panic-20200227-125547.reported.log](https://github.com/syncthing/syncthing/files/4261523/panic-20200227-125547.reported.log)

**Comment by calmh** [comment]
Yeah, sorry about that. You need -rc.7 or -rc.8.

**Comment by Echsecutor** [comment]
```
syncthing -reset-database
```
fixes this issue.

**Comment by calmh** [comment]
It probably does, but it's not necessary to nuke the entire database.
