### ISSUE TITLE
'No upgrade' option missing in options

### ISSUE THREAD

**Issue by tezfair** [syncthing/syncthing#6383]
With the impending RC9 on the horizon I was going to turn off the upgrades for a while and have noticed that the option is no longer there. 

1.3.4
![image](https://user-images.githubusercontent.com/17702842/75532538-457abb00-5a0c-11ea-8e74-dff3c9e11594.png)

1.4.0
![image](https://user-images.githubusercontent.com/17702842/75533649-925e9180-5a0c-11ea-8370-48bae26dd4f2.png)

**Comment by calmh** [comment]
I think this reflects the fact that you can't actually disable upgrades on release candidates

**Comment by AudriusButkevicius** [comment]
Yeah, staying on a candidate forever makes no sense.
