### ISSUE TITLE
macos release should include installer

### ISSUE THREAD

**Issue by ssbarnea** [syncthing/syncthing#6388]
At this moment the macos release includes binaries and a complex directory structure for other platforms.

Ideally the release should have `dmg` or `pkg` file and avoid including files unrelated to the platform. 

Even having a bash installer would be great improvement over the time consuming README steps. 

The reality is that once you reach them, you decide that life is too short to follow them. This prevented me from adopting it, and I am a software engineer. Is not that I do not know how to follow these steps. Improving first-time experience would be key to make syncthing more popular.

**Comment by calmh** [comment]
There is some truth to that. In the meantime, https://brew.sh/ is your friend.

**Comment by calmh** [comment]
Or https://github.com/syncthing/syncthing-macos of course.

**Comment by xor-gate** [comment]
It seems Syncthing.app has been downloaded now for 81k and it bundles it with a tray icon so you don't even feel syncthing is a real unix daemon. People who directly hit the mainpage of syncthing can download the bundle and don't know the zip file with the complex structure even exists. Native (official) installers should be used by non-power users.

**Comment by calmh** [comment]
Right. So as of right now, no plans to macify the default distribution, while syncthing-macos and homebrow (for example) each handle making it more native in their own ways.
