### ISSUE TITLE
1

### ISSUE THREAD

**Issue by yyy33** [syncthing/syncthing#6394]
The upload and download speeds of the remote device and the current device are the same.My version number is 1.3.4
![2020-03-04-16-04-01](https://user-images.githubusercontent.com/51548147/75858073-612df900-5e32-11ea-9040-a0e5c9d5b72f.png)

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
