### ISSUE TITLE
Memory lock error on Debian 11

### ISSUE THREAD

**Issue by KrotosInuus** [syncthing/syncthing#6395]
Good day to you all.

Recently I updated live installation of debian from 10 to 11 (which is testing release but it's still an curious issue) ). And encounter this memory bug:

From OS journal:
```
syncthing[169627]: runtime: mlock of signal stack failed: 12
syncthing[169627]: runtime: increase the mlock limit (ulimit -l) or
syncthing[169627]: runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+
syncthing[169627]: fatal error: mlock failed
syncthing[169627]: [monitor] WARNING: Panic detected, writing to "/home/user/.config/syncthing/panic-20200305-153216.log"
syncthing[169627]: [monitor] WARNING: Please check for existing issues with similar panic message at https://github.com/syncthing/syncthing/issues/
syncthing[169627]: [monitor] WARNING: If no issue with similar panic message exists, please create a new issue with the panic log attached
systemd[1]: syncthing@user.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: syncthing@user.service: Failed with result 'exit-code'.
systemd[1]: syncthing@user.service: Scheduled restart job, restart counter is at 25.
systemd[1]: Stopped Syncthing - Open Source Continuous File Synchronization for user.
systemd[1]: Started Syncthing - Open Source Continuous File Synchronization for user.
```

And from panic log:
```
[CDCY4] INFO: Completed initial scan of sendreceive folder "Data: Pictures" (aaaaa-aaaa)
[CDCY4] INFO: quic://0.0.0.0:22000 resolved external address quic://11.11.11.11:5988 (via stun.syncthing.net:3478)
Panic at 2020-03-05T15:35:10+05:00
fatal error: mlock failed

runtime stack:
runtime.throw(0xdcb78c, 0xc)
	/usr/local/go/src/runtime/panic.go:1112 +0x72
runtime.mlockGsignal(0xc0006fa180)
	/usr/local/go/src/runtime/os_linux_x86.go:72 +0x107
runtime.mpreinit(0xc003bb8700)
	/usr/local/go/src/runtime/os_linux.go:341 +0x78
runtime.mcommoninit(0xc003bb8700)
	/usr/local/go/src/runtime/proc.go:630 +0x108
runtime.allocm(0xc00003e800, 0x0, 0x1)
	/usr/local/go/src/runtime/proc.go:1390 +0x14e
runtime.newm(0x0, 0xc00003e800)
	/usr/local/go/src/runtime/proc.go:1704 +0x39
runtime.startm(0xc00003e800, 0x1695100)
	/usr/local/go/src/runtime/proc.go:1869 +0x12a
runtime.handoffp(0xc00003e800)
	/usr/local/go/src/runtime/proc.go:1896 +0x52
runtime.retake(0xe575bffb6a8b, 0xc000041000)
	/usr/local/go/src/runtime/proc.go:4628 +0x157
runtime.sysmon()
	/usr/local/go/src/runtime/proc.go:4537 +0x138
runtime.mstart1()
	/usr/local/go/src/runtime/proc.go:1097 +0xc3
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1062 +0x6e
```
And full panic log: [https://pastebin.com/B90KFfwP](url)

Extending locked memory hard limits seems dont affecting this behavior at all.

Some searches leads only to this kerlel bugs which happens only with go written software: https://github.com/golang/go/issues/35777

Syncthing Version: v1.4.0-rc.10 "Fermium Flea" (go1.14 linux-amd64) deb@build.syncthing.net 2020-02-29
OS Version: Debian GNU/Linux bullseye x64 (Linux 5.4.0-4-amd64)
Browser Version: Rarely configured with Firefox 73

**Comment by calmh** [comment]
So...

1. Syncthing 1.4.0 shouldn't be built with Go 1.4, but apparently the deb is. I'll fix that.
2. The error message contains the solution: `syncthing[169627]: runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+` (your kernel has a memory corruption bug)

**Comment by imsodin** [comment]
@KrotosInuus Did you report an issue about this with Debian as well?

**Comment by calmh** [comment]
I'll push a 1.4.0-rc.10.1 just for Debian, built with 1.13.8 like every other variant.

**Comment by calmh** [comment]
@imsodin This is our build

**Comment by calmh** [comment]
There, `apt upgrade` to a new package that just gets silent memory corruption instead of a crash 🎈

**Comment by imsodin** [comment]
> @imsodin This is our build, just I screwed up which build image builds the debian + snap packages.

I know, but the message about updating the kernel suggests a (fixed) kernel bug and it would be nice (maybe just for me) to have an issue to track when that fix arrives in debian.

**Comment by KrotosInuus** [comment]
> 
> 
> @KrotosInuus Did you report an issue about this with Debian as well?
Writing it now. Even after phoronix write article about this bug, even kernel devs release the fix - debian branch still slow as a drunk owl)

> 
> 
> I'll push a 1.4.0-rc.10.1 just for Debian, built with 1.13.8 like every other variant.
Thanks mate, upgrading it on affected hosts and log is good again.
