### ISSUE TITLE
RC release v1.4.0-rc.10.1 in APT stable channel

### ISSUE THREAD

**Issue by gregd** [syncthing/syncthing#6396]
Latest v1.4.0-rc.10.1 release is available to upgrade in APT **stable** channel. I guess that is a mistake.

**Comment by calmh** [comment]
Ugh. Luckily we think it's fairly stable by this point...

(fixed)

**Comment by ProactiveServices** [comment]
This has forced on telemetry, ignoring my choice not to send telemetry, and presumably will opt me in to future RCs. How can I ensure that my data isn't being collected and sent against my express wishes?

**Comment by calmh** [comment]
You can downgrade it. The installed package itself has no bearing on future upgrades in the debian world.

**Comment by ProactiveServices** [comment]
Database migrations are fine, I'll set the URL to an invalid value. Thanks.
