### ISSUE TITLE
Loop migrating database

### ISSUE THREAD

**Issue by fbreve** [syncthing/syncthing#6397]
One of my machines is stuck in this loop:

[start] 19:23:49 INFO: syncthing v1.4.0-rc.10 "Fermium Flea" (go1.13.8 windows-amd64) teamcity@build.syncthing.net 2020-02-29 18:51:48 UTC
[start] 19:23:49 INFO: Using large-database tuning
[start] 19:23:49 INFO: Automatic upgrade is always enabled for candidate releases.
[CBEOV] 19:23:49 INFO: My ID: CBEOV4E
[CBEOV] 19:23:50 INFO: Single thread SHA256 performance is 216 MB/s using minio/sha256-simd (164 MB/s using crypto/sha256).
[CBEOV] 19:23:50 INFO: Hashing performance is 183.12 MB/s
[CBEOV] 19:23:50 INFO: Migrating database to schema version 9...
[CBEOV] 19:24:12 WARNING: Database schema: key not found
[monitor] 19:24:13 INFO: Log output saved to file "C:\Users\fbrev\AppData\Local\Syncthing\syncthing.log"
[start] 19:24:13 INFO: syncthing v1.4.0-rc.10 "Fermium Flea" (go1.13.8 windows-amd64) teamcity@build.syncthing.net 2020-02-29 18:51:48 UTC
[start] 19:24:13 INFO: Using large-database tuning
[start] 19:24:13 INFO: Automatic upgrade is always enabled for candidate releases.
[CBEOV] 19:24:13 INFO: My ID: CBEOV4E
[CBEOV] 19:24:14 INFO: Single thread SHA256 performance is 206 MB/s using minio/sha256-simd (138 MB/s using crypto/sha256).
[CBEOV] 19:24:15 INFO: Hashing performance is 192.41 MB/s
[CBEOV] 19:24:15 INFO: Migrating database to schema version 9...
[CBEOV] 19:24:36 WARNING: Database schema: key not found
[monitor] 19:24:36 INFO: Log output saved to file "C:\Users\fbrev\AppData\Local\Syncthing\syncthing.log"
[start] 19:24:36 INFO: syncthing v1.4.0-rc.10 "Fermium Flea" (go1.13.8 windows-amd64) teamcity@build.syncthing.net 2020-02-29 18:51:48 UTC
[start] 19:24:36 INFO: Using large-database tuning
[start] 19:24:36 INFO: Automatic upgrade is always enabled for candidate releases.
[CBEOV] 19:24:36 INFO: My ID: CBEOV4E
[CBEOV] 19:24:37 INFO: Single thread SHA256 performance is 218 MB/s using minio/sha256-simd (161 MB/s using crypto/sha256).
[CBEOV] 19:24:37 INFO: Hashing performance is 164.65 MB/s
[CBEOV] 19:24:37 INFO: Migrating database to schema version 9...
[CBEOV] 19:24:58 WARNING: Database schema: key not found
[monitor] 19:24:59 INFO: Log output saved to file "C:\Users\fbrev\AppData\Local\Syncthing\syncthing.log"
[start] 19:24:59 INFO: syncthing v1.4.0-rc.10 "Fermium Flea" (go1.13.8 windows-amd64) teamcity@build.syncthing.net 2020-02-29 18:51:48 UTC
[start] 19:24:59 INFO: Using large-database tuning
[start] 19:24:59 INFO: Automatic upgrade is always enabled for candidate releases.
[CBEOV] 19:24:59 INFO: My ID: CBEOV4E
[CBEOV] 19:25:00 INFO: Single thread SHA256 performance is 224 MB/s using minio/sha256-simd (168 MB/s using crypto/sha256).
[CBEOV] 19:25:00 INFO: Hashing performance is 198.79 MB/s
[CBEOV] 19:25:00 INFO: Migrating database to schema version 9...
[CBEOV] 19:25:22 WARNING: Database schema: key not found
[monitor] 19:25:22 INFO: Log output saved to file "C:\Users\fbrev\AppData\Local\Syncthing\syncthing.log"
[start] 19:25:22 INFO: syncthing v1.4.0-rc.10 "Fermium Flea" (go1.13.8 windows-amd64) teamcity@build.syncthing.net 2020-02-29 18:51:48 UTC
[start] 19:25:22 INFO: Using large-database tuning
[start] 19:25:22 INFO: Automatic upgrade is always enabled for candidate releases.
[CBEOV] 19:25:22 INFO: My ID: CBEOV4E
[CBEOV] 19:25:23 INFO: Single thread SHA256 performance is 218 MB/s using minio/sha256-simd (160 MB/s using crypto/sha256).
[CBEOV] 19:25:24 INFO: Hashing performance is 186.07 MB/s
[CBEOV] 19:25:24 INFO: Migrating database to schema version 9...
[CBEOV] 19:25:45 WARNING: Database schema: key not found
[monitor] 19:25:45 INFO: Log output saved to file "C:\Users\fbrev\AppData\Local\Syncthing\syncthing.log"
[start] 19:25:45 INFO: syncthing v1.4.0-rc.10 "Fermium Flea" (go1.13.8 windows-amd64) teamcity@build.syncthing.net 2020-02-29 18:51:48 UTC
[start] 19:25:45 INFO: Using large-database tuning
[start] 19:25:46 INFO: Automatic upgrade is always enabled for candidate releases.
[CBEOV] 19:25:46 INFO: My ID: CBEOV4E
[CBEOV] 19:25:46 INFO: Single thread SHA256 performance is 218 MB/s using minio/sha256-simd (162 MB/s using crypto/sha256).
[CBEOV] 19:25:47 INFO: Hashing performance is 194.89 MB/s
[CBEOV] 19:25:47 INFO: Migrating database to schema version 9...

**Comment by calmh** [comment]
IS it possible for you to zip up this database and share it for debugging, privately? I can provide scp/sftp upload if you don't have something handy...

**Comment by calmh** [comment]
I think we need to be more lenient towards preexisting conditions in the database when migrating...

**Comment by calmh** [comment]
You might also try this build to see if it resolves it: https://build.syncthing.net/buildConfiguration/Syncthing_BuildWindows/56774?buildTab=artifacts

**Comment by fbreve** [comment]
Thank you for your support.
This build fixed the problem.
If you still need the database I can upload it to Google Drive and send you the link.

**Comment by calmh** [comment]
Thanks for testing! no need, I think.
