### ISSUE TITLE
Master Repo has out of sync items

### ISSUE THREAD

**Issue by bigbear2nd** [syncthing/syncthing#640]
The Master Repo wants to accept changes from the node?

![1](https://cloud.githubusercontent.com/assets/7719800/4173717/f10d29aa-3562-11e4-910f-3d004ec40b12.PNG)

![2](https://cloud.githubusercontent.com/assets/7719800/4173718/f8e2ba14-3562-11e4-84fc-b0f7e0451def.PNG)

**Comment by corppneq** [comment]
Very confusing naming! Please call it "Änderungen auf anderen Geräten überschreiben".

**Comment by AudriusButkevicius** [comment]
You can propose translation changes on transifex
