### ISSUE TITLE
Wrong 30-days-interval in staggered versioning

### ISSUE THREAD

**Issue by mv1005** [syncthing/syncthing#6410]
### Problem
When using staggered versioning, syncthing deletes versions withing the 30-days limit that are NOT closer than 1 day.

### Steps to reproduce
- Setup a test folder with staggered versioning, leave default settings
- Create dummy version files in the .stversions-folder named `testfile~YYYYMMDD-000000` one for each day reaching back 30 days in the past starting from now
- Restart syncthing to trigger version cleanup
- Syncthing is cleaning versions which are older than 6 days, leaving one file per week

### Expected behaviour
Syncthing leaves all versions untouched, since documentation says:
> For the first 30 days, the most recent version is kept every day.

### Version Information
Syncthing Version: v1.3.4
OS Version: Ubuntu 19.10

I have investigated the situation by looking at the code in `lib/versioner/staggered.go`. There is one digit missing in the number of seconds specifying the 30-days-interval.

```
interval: [4]interval{
    {30, 3600},       // first hour -> 30 sec between versions
    {3600, 86400},    // next day -> 1 h between versions
    {86400, 592000},  // next 30 days -> 1 day between versions  // This line is causing the issue
    {604800, maxAge}, // next year -> 1 week between versions
},
```

The number saying `592000` actually is a time period of 6.8 days only instead of the intended 30 days. The correct number would be `2592000` (Note the leading 2 which is missing).

Furthermore, the tests implemented in `lib/versioner/staggered_test.go` do not cover the issue above.

I have fixed the interval number and updated the tests and could provide a patch for that.

**Comment by calmh** [comment]
Please do!

**Comment by mv1005** [comment]
[0001-lib-versioner-Fixed-staggered-intervals.patch.tar.gz](https://github.com/syncthing/syncthing/files/4335289/0001-lib-versioner-Fixed-staggered-intervals.patch.tar.gz)

**Comment by mv1005** [comment]
Sorry, closed by accident.

**Comment by uok** [comment]
@mv1005 nice catch!
you can use the built-in code editor from Github to create a pull request and submit your patch

**Comment by mv1005** [comment]
What is the best way to contribute code without using the built-in editor? I could fork the projetc and file a pull request, but is there some more lightweight way?

**Comment by AudriusButkevicius** [comment]
Sadly not. I think that's the only two ways to create PRs.

**Comment by uok** [comment]
I normally use [Github Desktop](https://desktop.github.com) but since this patch is just a few lines I'd use the web editor.
Just go to https://github.com/syncthing/syncthing, fork it and edit the files in the browser.
After that you can create a PR with one click.

**Comment by sa3dany** [comment]
I think there is a more lightweight way but it assumes that the maintainers here are open to it. Basically you fork and make your changes in a single commit, then a maintainer here can just append `.patch` to the end of the commit url in Github.  That patch can then be applied locally using git.

**Comment by calmh** [comment]
Please just file a pull request. We've already spent more effort just talking about it.

**Comment by mrienstra** [comment]
This error would've been significantly easier to spot if this format were used:
```30 * 24 * 60 * 60```
(or by using variables for an hour, a day, etc.)

**Comment by mv1005** [comment]
> This error would've been significantly easier to spot if this format were used:
> `30 * 24 * 60 * 60`
> (or by using variables for an hour, a day, etc.)

Also this error would have been detected if the tests cover all time ranges. See my PR above.
