### ISSUE TITLE
Improve device status for "unused" devices

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#6416]
Currently, when a device is configured but not folders are shared with it, it's displayed as `Unused`:

<img width="602" alt="Screenshot 2020-03-18 at 08 52 41" src="https://user-images.githubusercontent.com/125426/76937850-da7b2080-68f5-11ea-89b6-0f3d6a016b4c.png">

This takes precedence over the "connected", "disconnected", and "paused" states. This is annoying because I may have a device that for some reason doesn't share any folders for the moment, and I may want to pause it to indicate that I know and it's fine. I might also just want to add a device to see if it connects, but currently that's not obvious unless you expand it and look at the address field... So, I propose that we add "(Unused)" as an extra status modifier, so we'd have the usual status *plus* that:

- `Disconnected (Unused)`
- `Connected (Unused)` <- this would normally be "Up to date" or "Syncing", but neither of those apply, and is roughly what the current "unused" state should mean.
- `Paused (Unused)`

**Comment by tomasz1986** [comment]
What about the icon, which is displayed with no text on small screens?

Right now, it is the following.

![image](https://user-images.githubusercontent.com/5626656/76968160-c83bc980-696b-11ea-975b-bec4c093ce52.png)

**Comment by calmh** [comment]
I guess that can represent the `Connected (Unused)` state

**Comment by tuarrep** [comment]
I've tried an implementation in #6445 if you mind have a look
