### ISSUE TITLE
"fatal error: runtime: out of memory" after upgrade syncthing from version 1.3.2 to 1.4.0 on a QNAP NAS TS-419 II 

### ISSUE THREAD

**Issue by rlvargas** [syncthing/syncthing#6422]
### Version Information

Syncthing Version: syncthing v1.4.0 "Fermium Flea" (go1.13.8 linux-arm)
OS Version: QNAP firmware version 4.3.3.1161 Build 20200109
Browser Version: not applicable
NAS Model:      TS-419P II

 - what happened,
Syncthing service crashed after updating from v1.3.2 to v1.4.0. The log shows the problem happened after "Migrating database to schema version 9..." entry and the crash report describes a "fatal error: runtime: out of memory".  
see attached files: [sync.log](https://github.com/syncthing/syncthing/files/4349556/sync.log)
[panic-20200318-175040.reported.log](https://github.com/syncthing/syncthing/files/4349518/panic-20200318-175040.reported.log)

 - what you expected to happen instead, and
Indeed the system is an old QNAP NAS with only 512MB of RAM but it have never had problem with previous version updates. The problem persisted even after stopping all services to free up memory before performing the update.

 - any steps to reproduce the problem.
Execute the commands:

**[/share/MD0_DATA/.qpkg/syncthing] # uname -a**
Linux rv-nas 3.4.6 #1 Thu Jan 9 12:06:35 CST 2020 armv5tel unknown
**[/share/MD0_DATA/.qpkg/syncthing] # /etc/init.d/services.sh stop**
Stop services: Stop qpkg service: /etc/rcK.d/QK100QcloudSSLCertificate /etc/rcK.d/QK101opentftp /etc/rcK.d/QK101phpMyAdmin /etc/rcK.d/QK103HybridBackup /etc/rcK.d/QK103HybridBackup: line 296: /home/httpd/cgi-bin/backup/python_dir/bin/python: No such file or directory
/etc/rcK.d/QK104BackupVersion /etc/rcK.d/QK105helpdesk /etc/rcK.d/QK106QsyncServer Shutting down Qsync service: Shutting down Versioning services:.
stop db server
OK
/etc/rcK.d/QK107QVPN Shutting down QVPN services: 
/etc/rcK.d/QK108PhotoStation /etc/rcK.d/QK110SickBeard armv5tel
Shutting down SickBeard... 
SickBeard is not running?
/etc/rcK.d/QK111Entware-ng Disable Entware-ng/opkg
 Checking squid...              dead. 
/etc/rcK.d/QK112CloudDrive pidfile /var/run/clouddrive.pid does not exist. Daemon not running?
/etc/rcK.d/QK113git Shutting down git... 
/etc/rcK.d/QK114CloudLink /etc/rcK.d/QK115syncthing Stop services: syncthing
killall: syncthing: no process killed
/etc/rcK.d/QK116MusicStation /etc/rcK.d/QK117DownloadStation Shutting down DownloadStation services: 
/etc/rcK.d/QK118Syncrify Attempting to stop Syncrify Server: Not running.
/etc/rcK.d/QK119JRE Disable Java Runtime Environment... 
/etc/rcK.d/QK121SABnzbdplus SABnzbd is not running?
/etc/rcK.d/QK122CouchPotato2 CouchPotato2 is not running
/etc/rcK.d/QK123Optware Disable Optware/ipkg
/etc/rcK.d/QK124Python Removing Python file links... 
/etc/rcK.d/QK899QcloudSSLCertificate .
Stop service: ldap_server.sh antivirus.sh iso_mount.sh qsyncman.sh rsyslog.sh snmp lunportman.sh iscsitrgt.sh twonkymedia.sh init_iTune.sh ImRd.sh crond.sh StartMediaService.sh mariadb.sh mysqld.sh recycled.sh Qthttpd.sh atalk.sh nfs ftp.sh smb.sh qsyncsrv_install.sh .
**[/share/MD0_DATA/.qpkg/syncthing] # free**
              total         used         free       shared      buffers
  Mem:       515492       487300        28192            0        30376
 Swap:       530124        13508       516616
Total:      1045616       500808       544808
**[/share/MD0_DATA/.qpkg/syncthing] # ./syncthing.sh restart**
Stop services: syncthing
killall: syncthing: no process killed
syncthing is already in base of ssl proxy
Start services: syncthing
Moving sync.log.8 to sync.log.9
Moving sync.log.6 to sync.log.7
Moving sync.log.4 to sync.log.5
Moving sync.log.2 to sync.log.3
Moving sync.log to sync.log.1
Moving sync.log.7 to sync.log.8
Moving sync.log.5 to sync.log.6
Moving sync.log.3 to sync.log.4
Moving sync.log.1 to sync.log.2
Moving sync.log to sync.log.1
**[/share/MD0_DATA/.qpkg/syncthing] # tail sync.log**
[monitor] 20:51:45 WARNING: Uploading crash reports is taking a while, please wait...
[monitor] 20:51:46 INFO: Reporting crash found in panic-20200318-205134.log (report ID 3f2b7426) ...
[start] 20:51:55 INFO: syncthing v1.4.0 "Fermium Flea" (go1.13.8 linux-arm) teamcity@build.syncthing.net 2020-03-06 19:52:22 UTC
[CKUR5] 20:51:55 INFO: My ID: XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX ## edited ##
[CKUR5] 20:51:56 INFO: Single thread SHA256 performance is 15 MB/s using crypto/sha256 (15 MB/s using minio/sha256-simd).
[CKUR5] 20:51:58 INFO: Hashing performance is 13.74 MB/s
[CKUR5] 20:51:58 INFO: Migrating database to schema version 9...
[CKUR5] 21:13:55 INFO: Paused state detected, possibly woke up from standby. Restarting in 1m0s.
[monitor] 21:15:19 INFO: Syncthing exited: signal: killed
[monitor] 21:15:21 INFO: Signal 15 received; exiting

**Comment by imsodin** [comment]
Main answer: The database migration on upgrade just requires too much memory for your system. There might be workarounds, but that's better suited for https://forum.syncthing.net

"Internal" Implementation stuff: Looking at the migration, we do not `Checkpoint` the transaction, meaning it will only be committed when reaching 128MiB instead of the 1MiB in usual operations. That looks like an oversight, I doubt the fewer commits will speed the whole thing up by much, or does it? ( @calmh )

**Comment by calmh** [comment]
I doubt that as well, we should checkpoint here and there in the transition. Good 1.4.1 material.

**Comment by rlvargas** [comment]
Thank you both. I will try the forums. By the way, I really appreciate syncthing. Kudos on the great work!

**Comment by rlvargas** [comment]
The fix in version 1.4.1-rc worked! Thanks!

**[/share/MD0_DATA/.qpkg/syncthing] # tail sync.log**
[start] 11:04:22 INFO: syncthing v1.4.1-rc.1 "Fermium Flea" (go1.13.8 linux-arm) teamcity@build.syncthing.net 2020-03-18 19:33:43 UTC
[start] 11:04:22 INFO: Automatic upgrade is always enabled for candidate releases.
[CKUR5] 11:04:23 INFO: My ID: XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX ## edited ##
[CKUR5] 11:04:25 INFO: Single thread SHA256 performance is 8.3 MB/s using crypto/sha256 (7.8 MB/s using minio/sha256-simd).
[CKUR5] 11:04:27 INFO: Hashing performance is 13.73 MB/s
[CKUR5] 11:04:27 INFO: Migrating database to schema version 9...
[CKUR5] 11:06:14 INFO: Compacting database after migration...
[CKUR5] 11:08:57 INFO: Detected upgrade from v1.3.2 to v1.4.1-rc.1
[CKUR5] 11:08:57 INFO: Starting deadlock detector with 20m0s timeout
[CKUR5] 11:08:57 INFO: Overall send rate is unlimited, receive rate is unlimited
[CKUR5] 11:08:57 INFO: Anonymous usage reporting is always enabled for candidate releases.
[CKUR5] 11:08:57 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting
[CKUR5] 11:08:57 INFO: QUIC listener (0.0.0.0:22000) starting
[CKUR5] 11:08:57 INFO: TCP listener (0.0.0.0:22000) starting

**Comment by rdslw** [comment]
Just to confirm, my mipsle device (512MB ram) using 1.4.1-rc-3 was able to start now :-)
Migration took around 8 minutes, half of the time on compacting, db size before: 665MB, afterwards: 190MB  

Thank you guys. Also really helpfull was that on RC releases you provide builds for every platform (https://github.com/syncthing/syncthing/releases/). Kudos from mipsle arch users!
