### ISSUE TITLE
Unresolvable "Out of sync" after full disk

### ISSUE THREAD

**Issue by jluttine** [syncthing/syncthing#6423]
### Does your log mention database corruption?

No. The device which has "Out of sync" error, doesn't mention database corruption in logs.

### Please do post actual bug reports and feature requests.

I have device A, which has a folder in "Send Only" mode. Another device B is syncing this folder normally. (Device A is a phone and the folder is it's camera folder, so I'm syncing photos to my laptop B.)

I added a file to device A (took a photo). However, device B had too full disk so the syncing failed. I freed some disk space and lowered the threshold of free disk space that Syncthing requires. Now there's plenty enough disk space. However, the folder still stays "Out of sync":

![image](https://user-images.githubusercontent.com/2195834/76976695-feae2000-693c-11ea-8131-b0b9930ec40d.png)

![image](https://user-images.githubusercontent.com/2195834/76976858-361ccc80-693d-11ea-94fa-85a3ee25a25e.png)

I've restarted syncthing on both devices, tried pausing and unpausing and rescanning the folder on both devices. Nope, nothing helps. The folder stays "Out of sync" on device B, but still this device shows on "Remove devices" section that it's "Up to date" with that device.

Also, I thought there should be "Override changes" button visible on device A in this case, but there isn't. Device A is Android device and I looked both the normal Android view and web GUI.

How can I force sync? Device A still has this photo that device B hasn't received. Device A should just send it..

### Version Information

I couldn't see the version information from the web GUI on device B (laptop running NixOS).

Version on device A (Android phone) is 1.3.4

**Comment by imsodin** [comment]
Please open a thread on forum.syncthing.net about this. If later an actionable bug is found, an issue can be opened again.
