### ISSUE TITLE
Revert Local Changes red button does not work correctly

### ISSUE THREAD

**Issue by xarx00** [syncthing/syncthing#6436]
- what happened,
When a Syncthing folder contains locally-changed-items, the red "Revert Local Changes" button is shown. When this button is pressed, it seemingly does nothing. When it is pressed for the second time, the local changes are reverted.

Screenshot: https://ibb.co/Nx3VkqY

 - what you expected to happen instead
The red button should work on the first press.

In fact, it might be just a GUI refreshing problem. The first press may actually work, but the second press of the button might be needed to refresh the GUI. However, it may be a different problem, because when I reloaded the GUI at the beginning and then pressed the red button (once), it worked correctly.

### Version Information

Syncthing Version: v1.4.0
OS Version: Synology NAS DS416play (Linux x64)
Browser Version: Firefox 68.6.0esr

**Comment by AudriusButkevicius** [comment]
This is not a very useful bug report, as there is no steps to reproduce the issue, just a collection of observations and expectations.

**Comment by xarx00** [comment]
I just have a bunch of folders in the state Local Additions. I guess that one can make a folder into this state by e.g. inserting a file into it, but I haven't tried to simulate that.

Maybe an important remark was omitted - the folder should be of the Receive-only type, otherwise the local changes will be immediately propagated to its corresponding device.

**Comment by AudriusButkevicius** [comment]
Can you try to reproduce that in isolation in a new folder and post the steps to reproduce?

**Comment by imsodin** [comment]
They opened the issue at my request and i believe the screenshots shows pretty clearly what the initial state is, the two steps taken and what's wrong: essentially the states show that things really get reverted, however the local changed items and button stay.
