### ISSUE TITLE
Don't start browser when restarting after upgrade

### ISSUE THREAD

**Issue by tezfair** [syncthing/syncthing#6437]
On an update, Syncthing should suppress opening the web browser if the option in the GUI is enabled. On unattended endpoints, I find many browser tabs that have been opened due to St restarting programatically

**Comment by tezfair** [comment]
I have upgraded to 1.5.0 RC1 and i'm getting new browser tabs opening. As I was aware this release was coming out I ensured that only 1 tabs was visible. After the update a new tab had appeared.

![image](https://user-images.githubusercontent.com/17702842/79216342-eac6e280-7e44-11ea-8bfb-39ef25e0f6d6.png)

**Comment by calmh** [comment]
This fix is on the handing-off side, that is, the version you're upgrading from.

**Comment by tezfair** [comment]
ok thanks. Just something I spotted and asked.
