### ISSUE TITLE
file modified but not rescanned; will try again later

### ISSUE THREAD

**Issue by pauldurham** [syncthing/syncthing#6439]
I have noticed what I believe is a bug in Syncthing v1.4.0:

After I have successfully synced a pair of folders, I renamed 2 files.  The rename for both files involved changing an uppercase "I" to a lowercase "i".  This has resulted the folder now being out of sync in the destination, and an error permanently being displayed in the destination console as well as 2 temporary files being created by Syncthing in the destination folder.  Please can you investigate?

Original file names:
2017 WIndows 10 Gold Image - PC Build, applications, tweaks v1.17.xlsx
2019 WIndows 10 Gold Image - PC Build, applications, tweaks v1.19.xlsx

Renamed file names:
2017 Windows 10 Gold Image - PC Build, applications, tweaks v1.17.xlsx
2019 Windows 10 Gold Image - PC Build, applications, tweaks v1.19.xlsx

Temporary files created in destination folder:
~syncthing~2017 Windows 10 Gold Image - PC Build, applications, tweaks v1.17.xlsx.tmp
~syncthing~2019 Windows 10 Gold Image - PC Build, applications, tweaks v1.19.xlsx.tmp

Destination console errors:
[GASKN] 07:38:59 INFO: Puller (folder "OneDrive" (haque-zpr5j), item "EUC Repository\\PC Builds & Updates\\2017 Windows 10 Gold Image - PC Build, applications, tweaks v1.17.xlsx"): handling file: file modified but not rescanned; will try again later
[GASKN] 07:38:59 INFO: Puller (folder "OneDrive" (haque-zpr5j), item "EUC Repository\\PC Builds & Updates\\2019 Windows 10 Gold Image - PC Build, applications, tweaks v1.19.xlsx"): handling file: file modified but not rescanned; will try again later

Syncthing version on both sides:  v1.4.0
Wrapper on both sides:  SyncTrayzor 1.1.24
OS on side A:  Windows 10 Enterprise 64-bit
OS on side B:  Windows 10 Professional 64-bit

Thanks.

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.

**Comment by AudriusButkevicius** [comment]
Also, this is most likely #1787

**Comment by pauldurham** [comment]
Hi Audrius,

Thanks for reply.  I got caught by the ambiguity of the issue tracker
template.  It says both "This issue tracker is for reporting bugs" and
"that's a bug, please report it on GitHub".  Bugs seem to be able to be
reported in both places.

With reference to #1787 <https://github.com/syncthing/syncthing/issues/1787>,
I agree my issue appears related.  #1787 refers to renaming folders whereas
mine relates to renaming files, but essentially the same.

Issue #1787 has been open for almost 5 years and still affects many users,
based on the comments.  Various other Windows sync tools correctly handle
file & folders renames (although none of these tools are suitable to me in
the way Syncthing is).  I really enjoy Syncthing as a whole and appreciate
the effort put into developing it.  How are other tools trapping the file
renames & can Syncthing implement this?

Thanks,
Paul.

**Comment by AudriusButkevicius** [comment]
I agree it's a bug, but it's a known bug, and there are plenty of forum threads that would answer this.

Regarding the details, you can read the issue that's there for the details.

**Comment by pauldurham** [comment]
Noted.
