### ISSUE TITLE
Stat file before syncing to reduce chance of missed conflict

### ISSUE THREAD

**Issue by ProactiveServices** [syncthing/syncthing#6446]
If a file has been changed between syncs but the node is unaware it has been changed, all current versions of the file are in a conflict state but this is not detected.

Steps to reproduce:
1. Create a test file on two nodes
1. Ensure nodes are synced
1. Pause a node
1. Change the file on both nodes and immediately un-pause

What happens: One node wins, data is lost.

What "should" happen: Conflict file is generated.

Perhaps if Syncthing stat'ed a file before starting to sync, this corner case could be avoided in some instances.

**Comment by calmh** [comment]
We do precisely this to avoid precisely that scenario and I can’t reproduce it. More details on OS, filesystem, and what your change entails precisely, please.
