### ISSUE TITLE
[Feature request] Conditional ignores

### ISSUE THREAD

**Issue by ForsakenHarmony** [syncthing/syncthing#6447]
I know this is not really something other tools do, but it would still be nice

I'd like to sync some programming projects, but ignore output folders

For javascript projects, just ignoring `node_modules` everywhere *should* be fine, but for rust there's the `target` directory, which I'd like to ignore if there's a file called `Cargo.toml` in the same directory, in other cases `target` is probably not too rare to encounter so I would want to sync that

In general I'd like somewhat more "conditional" ignores, but from what I can tell you're closer to i.e. `.gitignore`

This might not be easy to implement in an ergonomic way, so feel free to ignore this if it's out of scope

**Comment by AudriusButkevicius** [comment]
Sorry, but no, we are not going to cater for some specific niche scenarios.

**Comment by calmh** [comment]
We happily cater for all kinds of niche scenarios. 

This one however is technically really hairy and we’ve discussed similar ones on the forum back and forth. Having ignored status depend on second factors like time of day or whether some other file exists or the size of a file doesn’t work in our architecture.
