### ISSUE TITLE
1.4.0 seemingly no longer respecting listen address

### ISSUE THREAD

**Issue by michaelsmoody** [syncthing/syncthing#6455]
### Version Information

Syncthing Version: v1.4.0
OS Version: CentOS 7
Browser Version: N/A

Good morning. First, let me again say thank you for this wonderful piece of software which is so incredibly useful.

Recently, as expected, all of my boxes upgraded to 1.4.0. Following this upgrade, it appears that the listen address is no longer respected.

In my particular environment, I have on off-site replica which has a limited bandwidth link (per-GB monthly) but which has unlimited transfer between the hours of midnight to 6am. For years, I have accomplished this by configuring nodes to listen on a particular address:port, and by disabling global discovery and relay, and it has worked great. We achieve connectivity between these nodes via a site to site VPN, and have configured certain policies to limit the times the policy is active according to the unlimited internet hours. Again, for years, this has worked great.

After the recent update to 1.4.0, I was getting high data usage notifications and it took me some time to track it to the Syncthing services. The Syncthing nodes are no longer respecting the listen address specifying a port, and are instead choosing the port randomly, it appears (no longer 22000). This of course has caused issues with the port specific time based VPN policies. I found one of the systems has the proper config in the config.xml, but the UI still claims "default". It has tcp4://192.168.100.130:22000, but is connected on 192.168.100.130:43567 on a remote node.

Please let me know what information I can provide in order to help track this down.

(Separately, it would be fantastic if Syncthing implemented a scheduling feature, to solve this exact situation!)

Thanks again,
Michael S. Moody

**Comment by AudriusButkevicius** [comment]
Please, if you are not sure its a bug, use the forum first to reduce churn in the issue tracker.

**Comment by michaelsmoody** [comment]
Good morning,

Please forgive me, but I did actually search forum posts in depth.

I did in fact use the forum, thoroughly read the documentation, and will also mention that I've been using this configuration for years. This behavior is new, at least to me. According to other systems I have running older versions, they bind to only the IP, and port specifically configured and only on IPv4 (due to my tcp4 setting). However, my 1.4.0 nodes are disregarding this. So, either there was a bug before, or a bug now. I have very reliably configured syncthing to listen only on port 22000 for transfers, and confirmed with netstat and ss. As of 1.4.0, netstat/ss

**Comment by calmh** [comment]
You don't say what version you upgraded from, but I guarantee no changes were made to the listening-on-port-22000 part in the 1.4.0 release. Outgoing connections are always from a random port so regardless one side will have a random port.

**Comment by michaelsmoody** [comment]
Good morning,

Yes, you're correct in that I need to track down the specific version that caused this, so I'll do some further testing on my side. I am aware that outgoing is random (which is expected and pretty standard behavior). I will attempt to test this going back a few different versions in a sandbox (which isn't ideal, but that's ok).

Slightly off topic, I've also noticed that a few of my syncthing nodes (I have on the order of 50 across different implementations), ended up with global discovery and relay getting re-enabled between upgrades, but unfortunately I don't know which versions that happened on.

Does syncthing maintain more than one config file version by default? It appears I'm currently on v30, with a backup of v29. I'd be curious to see older, if it exists? Alternatively in the logs?

**Comment by AudriusButkevicius** [comment]
As I've said, you should keep discussions here to the minimum.
Please open a thread on the forum, post your ss/netstat output.

But as @calmh said, you are probably seeing outgoing ports, not listening ports, similarly like somone was  confused on this thread: https://forum.syncthing.net/t/random-ports-without-upnp/5264/3
