### ISSUE TITLE
Panic loop after upgrade to 1.4.1-rc3

### ISSUE THREAD

**Issue by eiszfuchs** [syncthing/syncthing#6457]
I have tried to find a solution to this problem, but I couldn't find anything that matched my situation, within these issues nor with a Google search.
I noticed that my folders went out of sync a few days back. I thought something crashed again, as it did from time to time. I upgraded to 1.4.0 when the latest stable came out, but that's when the panics started. I pulled the latest Release Candidate instead, as it supposedly fixed the issue with rebuilding the database, so Syncthing started again just fine.

I then noticed another round of panics, just as the re-scans kicked in. One of the folders made it panic, so I paused all folders and unpaused them until I got to the folder that caused the panics.

This is what Syncthing does, over and over, piling up log files:

```
[P4WYR] 13:14:35 INFO: Connection to XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX at xxx.xxx.xxx.xxx:59442-xxx.xxx.xxx.xxx:22000/tcp-client/TLS1.3-TLS_AES_128_GCM_SHA256 closed: unpausing folder "FOLDER_NAME" (xvicV-6grJj)
[P4WYR] 13:15:54 INFO: Device XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX folder "FOLDER_NAME" (xvicV-6grJj) has a new index ID (0xAC706B84FF20D287)
Panic at 2020-03-26T13:15:57+01:00
panic: device present in global list but missing as device/fileinfo entry
```

I couldn't find anything that could explain the error. The folder ID is the same on both devices. Folders haven't changed and are still correct on both ends.

### Version Information

Syncthing Version: v1.4.1-rc3
OS Version: Arch Linux on Raspberry Pi

**Comment by imsodin** [comment]
In principle it's possible that the db repair on upgrade never happened for you if it failed the first time around (will file a PR fixing that). Can you please create a copy of your database (by default `~/.config/syncthing/index-v0.14.0.db`), then run Syncthing again with `STTRACE=db STRECHECKDBEVERY=1s` collecting the (possibly massive) log.

**Comment by eiszfuchs** [comment]
Okay, I'm assuming this does a database check. I performed these commands:
```
cp -R index-v0.14.0.db index-v0.14.0.db-copy
STTRACE=db STRECHECKDBEVERY=1s syncthing > issue-6457.log
```
I'll check if this panics. Given it might re-scan all folders (the whole lot of about 750 GB), this _may_ going to take a while. Some major upgrades made me re-build the whole index, which took up to a few days.

**Comment by eiszfuchs** [comment]
Alright, I gathered the logs from the debug log and the panic stack trace: https://gist.github.com/eiszfuchs/567bd0c8ca0e07bf4fd0d8b44de0b41d

I noticed that some of the `FILENAME` were familiar. I recognize them because I had trouble getting those in sync for months now. They would always show when an instance had "Synching (99%)" or something like that. I tried restarting and upgrading every instance, but I couldn't get rid of those. A few hundred files in some folders.

Do you think my index on the local master server might be broken? Can I rebuild the index (even if it takes some days) without losing data?

**Comment by imsodin** [comment]
The log shows that the db check happens, then (almost) nothing else happens until the panic. "Almost" because I can't be sure due to the log obfuscation - if you could provide the unaltered version per PN on https://forum.syncthing.net/ or to freisim93@gmail.com that would be appreciated. Something is indeed broken, and in a bad way: Either the index can break in a way I can't imagine or the code does not do what I think it does - either way I am at a loss right now and don't expect staring at the code more to bring any results xD

Fur further investigations there's two routes: You can (again privately) provide me your database for debugging. Or I create a PR with more debug logging and you would run the resulting binary from our build server and get me the log.

**Comment by eiszfuchs** [comment]
I will e-mail you the raw files then. My database is 1 GiB, though. I assume I shouldn't be e-mailing you that?

**Comment by imsodin** [comment]
:D I recently as part of a pre-corona VPN failure emailed a 80MB zip and already felt really bad about that, but surprisingly it worked.

You can upload it to a provide of your choosing and send me the link, you can send me your Syncthing device ID or just send me an email and I will provide you a link to a nextcloud provider I am using :)

**Comment by eiszfuchs** [comment]
Okay, just for my understanding; we're talking about extremely sensitive data; at least for me, as in, Not Safe For Work, Not Safe For Public, Highly Toxic Biohazard kind of data, and hundreds of gigabytes of it. Sharing any kind of detail is already problematic for me, how is the device ID alone helping instead of the index database? I'm trying to understand how Syncthing works.

**Comment by imsodin** [comment]
I asked for your device ID such that we can connect our Syncthing instances. If you do trust me enough, but not any cloud provider, that's definitely the best option then. Anyway send me an email please (freisim93@gmail.com), such that we can discuss the details of any db sharing (or not) outside of the issue tracker.
