### ISSUE TITLE
Update to gopkg.in/ldap.v3

### ISSUE THREAD

**Issue by Pfeil** [syncthing/syncthing#6479]
As pointed out [here] very nicely, there is a bug in the currently used version of the `ldap` dependency that affects ARM devices like Raspberry Pis.

[here]: https://github.com/YunoHost-Apps/syncthing_ynh/issues/28#issuecomment-596081317

Updating the dependency should fix this. It's not clear to me whether this will also fix the issue where the comment was made, but it's clear that there was a bug that was fixed in the newer versions affecting the mentioned devices, so updating should be considered.

**Comment by calmh** [comment]
If it helps, it helps. 👍
