### ISSUE TITLE
Unable to sync soft links

### ISSUE THREAD

**Issue by es20490446e** [syncthing/syncthing#6480]
HOW TO REPRODUCE:
- On Linux, create a soft-link inside a synced folder.

RESULT:
- The soft link fails to sync with an Android device.

SYSTEM DETAILS:
- Syncthing 1.4.0

**Comment by AudriusButkevicius** [comment]
I don't think they are supported on Android. 

Regardless, we don't treat android anyway special, the fact it does not work most likely means its a problem with the platform.

If you want to dig further in this, I suggest you open a thread on the forums

**Comment by es20490446e** [comment]
Opened a [thread on the forums](https://forum.syncthing.net/t/unable-to-sync-soft-links/14737).

Anyway I still think this is a bug, not something to post on a support forum.

**Comment by AudriusButkevicius** [comment]
It can't be a bug, as all unix platforms including android execute the same code.

**Comment by es20490446e** [comment]
That I reproduced it on Android doesn't mean that it only affects Android, it's simply because the two devices on sync happen to be using that system.

**Comment by AudriusButkevicius** [comment]
Sure, let's keep the discussion on the forum.
