### ISSUE TITLE
Change UI Message when waiting for a Device to accept a Share request

### ISSUE THREAD

**Issue by chrisfcarroll** [syncthing/syncthing#6485]
In the GUI of Device A, I add Device B. 
The GUI of Device A tells me that B is disconnected. In fact, Device B is waiting for me to manually accept Device A as a device to share with.

So:

Change the GUI message of Machine A to say “Waiting for Device B to accept my share request”

**Comment by AudriusButkevicius** [comment]
Thats not true. There is no difference between waiting to connect, disconnected and explicitly refused hence the generic message. 

You are either connected or not, any other state would be a lie.
