### ISSUE TITLE
Allow nodes to behave as transfer nodes only.

### ISSUE THREAD

**Issue by glogiotatidis** [syncthing/syncthing#649]
It would be nice if a node can act as transfer node only.

Example:
- RaspberryPI with limited disk space, e.g. a 32Gb SD
- Two laptops which need to be in sync but they meet online infrequently.
- Laptop 1 syncs with RaspberryPI
- Later RaspberryPi syncs with Laptop 2. 
- Once all nodes are in sync, the transfer node (i.e. RaspberryPi) deletes all files freeing the used space but still reports as being synced.

**Comment by unfa** [comment]
Hmm, why not? It seems like a very useful option.

**Comment by calmh** [comment]
#1364

**Comment by AudriusButkevicius** [comment]
Though that's something elae.
