### ISSUE TITLE
Perdita di file e cartelle

### ISSUE THREAD

**Issue by Umanoid1** [syncthing/syncthing#6491]
@ Umanoid1
 
Umanoid1 ha commentato 25 secondi fa
Buongiorno, ho provato il progamma ultima versione sia vin10 portabile che android, e fatto la singronizzazione tra win10 e android SD come inviare e ricevere, i file e le cartelle di android sono stati sinc nella cartella win ma in andoid non ci sono più e neanche in windows , dove cavolo sono andati ha finitire? che per me sono importanti e li vorrei recuperare, se qualcuno degli sviluppatori gentilmente posso aiutare ha risolvere il mio problema, non so se valutarlo disistallarlo dare una brutta recensione e neanche donazione puttroppo ho avuto una brutta esperienza, non è possibile che siano spariti i file non mi era mai capitato una cosa del genere essendo una connessione nella stessa mia rete lan, oppure sono stati dirottati, sto scrivendo con android quando sono con pc vi mando il log saluti.

**Comment by uok** [comment]
if you have questions please go to https://forum.syncthing.net (and if possible write in English)
Thanks!
