### ISSUE TITLE
Relay pool server TestRelay() sporadically failing

### ISSUE THREAD

**Issue by grandchild** [syncthing/syncthing#6492]
#### What happened
I noticed that the relay I run was not on relays.syncthing.net. So I looked and it said the pool server returns 400, about 53% of the time, seemingly at random.

I then patched `cmd/strelaysrv/pool.go`
```diff
--- a/cmd/strelaysrv/pool.go
+++ b/cmd/strelaysrv/pool.go
@@ -58,7 +58,12 @@ func poolHandler(pool string, uri *url.URL, mapping mapping) {
                                log.Println("Failed to deserialize response", err)
                        }
                } else {
-                       log.Println(pool, "unknown response type from server", resp.StatusCode)
+                       bs, err := ioutil.ReadAll(resp.Body)
+                       if err != nil {
+                               log.Println(pool, "unknown response type from server", resp.StatusCode)
+                       } else {
+                               log.Println(pool, "unknown response type from server", resp.StatusCode, string(bs))
+                       }
                }
                time.Sleep(time.Hour)
        }

```

to include the body message (which is "`connection test failed`") which points me to [cmd/strelaypoolsrv/main.go:498](https://github.com/syncthing/syncthing/blob/dd92b2b8f48d919326b4b8a36349610f17ac8c4e/cmd/strelaypoolsrv/main.go#L498) and to [lib/relay/client/methods.go:107](https://github.com/syncthing/syncthing/blob/dd92b2b8f48d919326b4b8a36349610f17ac8c4e/lib/relay/client/methods.go#L107) where I stopped because I cannot determine whether it's a timeout, or a wrong response. Actually I could check that by looking at incoming requests... will do this later.

See logs at the bottom.

The first failed connection test was on 2020/03/28 at 11:14:58 UTC.

#### What I expect to happen
100% relay join success

#### Steps to reproduce
There's two explanations I can imagine:
1. Either my network connection is really wonky (it's a hosted server at Hetzner, I wouldn't expect that to last for 2 days).
1. Relay pool server has network issues. Then every (or at least many) relays should experience the same issues.

#### What I would like to get out of this report
Could you guys have a look and see if anything is visible on the public relay pool server? My relay is `-provided-by` "effekthasch".

Maybe the `handleRelayTest()` timeout needs to be raised slightly?

Or other relay providers could chime in if they too see join failures.

### Version Information

Syncthing Version: v1.4.1
OS Version: Arch Linux, fully updated.

<details>
<summary>Logs</summary>

<pre>
# Mar 27 00:46:55 systemd[1]: Started Syncthing relay server.
2020/03/27 00:46:56 main.go:138: strelaysrv v1.4.0 "Fermium Flea" (go1.14 linux-amd64) builduser@svetlemodry 2020-03-17 17:54:09 UTC
2020/03/27 00:46:56 main.go:144: Connection limit 419430
2020/03/27 00:46:56 main.go:233: URI: relay://0.0.0.0:22067/?id=*****&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=4000000&statusAddr=:22070&providedBy=*****
2020/03/27 00:46:56 main.go:236: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2020/03/27 00:46:56 main.go:237: !!  Joining default relay pools, this relay will be available for public use. !!
2020/03/27 00:46:56 main.go:238: !!      Use the -pools="" command line option to make the relay private.      !!
2020/03/27 00:46:56 main.go:239: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2020/03/27 00:47:03 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
    [many normal "Joined..." lines omitted]
2020/03/28 10:26:58 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/28 11:14:58 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/28 12:14:59 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/28 13:14:59 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/28 14:15:00 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/28 15:15:00 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/28 16:03:00 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/28 17:03:01 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/28 17:51:01 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/28 18:39:02 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/28 19:39:02 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/28 20:27:03 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/28 21:27:03 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/28 22:27:03 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/28 23:15:04 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/29 00:15:04 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/29 01:15:05 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/29 02:03:05 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/29 02:51:05 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/29 03:51:06 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/29 04:51:06 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/29 05:39:06 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/29 06:27:07 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/29 07:15:07 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/29 08:03:07 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/29 08:51:08 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/29 09:51:08 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/29 10:39:08 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/29 11:27:09 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/29 12:27:09 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/29 13:27:09 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/29 14:15:10 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/29 15:03:12 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/29 15:51:12 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/29 16:51:12 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/29 17:39:13 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/29 18:39:13 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/29 19:27:13 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/29 20:15:14 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/29 21:03:14 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/29 22:03:14 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/29 23:03:15 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/30 00:03:15 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/30 00:51:15 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/30 01:51:16 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/30 02:51:16 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/30 03:51:16 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/30 04:39:18 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/30 05:27:18 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/30 06:15:18 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/30 07:03:19 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/30 07:51:19 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/30 08:39:19 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/30 09:39:20 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/30 10:27:20 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/30 11:27:20 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/30 12:27:20 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/30 13:27:21 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/30 14:27:21 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/30 15:15:21 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/30 16:03:25 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/30 16:51:26 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/30 17:51:30 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/30 18:51:30 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/30 19:39:30 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/30 20:39:31 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/30 21:27:31 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/30 22:27:31 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/30 23:15:32 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/31 00:03:33 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/31 00:51:33 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/31 01:39:33 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/31 02:39:33 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/31 03:39:34 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/31 04:39:34 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/31 05:27:35 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/31 06:27:35 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/31 07:27:36 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/31 08:15:36 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/31 09:15:37 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/31 10:15:37 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/31 11:15:38 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/31 12:03:38 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/31 13:03:39 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/31 14:03:43 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/31 15:03:43 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/31 16:03:44 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/31 17:03:44 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/31 17:51:44 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/31 18:51:45 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/31 19:51:45 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/31 20:39:46 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/03/31 21:27:46 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/31 22:27:46 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/03/31 23:27:47 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/01 00:15:47 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
# -- Reboot --
2020/04/01 01:10:39 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/01 02:10:39 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/01 02:58:40 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/01 03:58:40 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/01 04:58:42 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/01 05:58:45 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/01 06:46:45 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/01 07:34:46 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/01 08:22:46 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/01 09:10:47 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/01 09:58:47 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/01 10:46:52 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/01 11:35:01 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/01 12:23:01 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/01 13:11:02 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/01 13:59:03 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/01 14:47:03 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/01 15:47:03 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/01 16:35:04 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/01 17:35:05 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/01 18:35:05 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/01 19:35:06 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/01 20:23:06 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/01 21:11:07 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/01 22:11:07 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/01 23:11:07 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/01 23:59:08 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/02 00:59:09 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/02 01:59:09 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/02 02:59:09 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/02 03:59:10 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/02 04:59:10 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/02 05:47:10 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/02 06:47:11 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/02 07:35:12 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/02 08:23:13 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/02 09:23:13 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/02 10:23:14 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/02 11:23:14 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/02 12:11:16 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/02 12:59:18 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/02 13:47:19 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/02 14:47:19 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/02 15:47:20 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/02 16:47:22 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/02 17:47:23 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/02 18:47:25 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/02 19:47:27 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/02 20:47:28 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/02 21:47:29 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/02 22:35:31 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/02 23:35:31 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/03 00:23:31 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/03 01:23:32 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/03 02:23:32 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/03 03:23:32 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/03 04:23:33 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/03 05:23:33 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/03 06:23:33 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/03 07:23:34 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/03 08:11:34 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/03 09:11:34 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/03 09:59:34 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/03 10:47:35 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/03 11:35:35 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/03 12:23:35 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/03 13:23:36 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
2020/04/03 14:23:37 pool.go:61: https://relays.syncthing.net/endpoint unknown response type from server 400
    [patched output of cmd/strelaysrv/pool.go to include response body]
2020/04/03 15:01:20 main.go:138: strelaysrv v1.4.1-rc.3+45-gf69c0b55-dirty "Fermium Flea" (go1.14.1 linux-amd64) jakob@2020-04-02 14:18:41 UTC
2020/04/03 15:01:20 main.go:144: Connection limit 419430
2020/04/03 15:01:20 main.go:233: URI: relay://0.0.0.0:22067/?id=*****&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=4000000&statusAddr=:22070&providedBy=*****
2020/04/03 15:01:20 main.go:236: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2020/04/03 15:01:20 main.go:237: !!  Joining default relay pools, this relay will be available for public use. !!
2020/04/03 15:01:20 main.go:238: !!      Use the -pools="" command line option to make the relay private.      !!
2020/04/03 15:01:20 main.go:239: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2020/04/03 15:01:21 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/03 15:49:21 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/03 16:37:21 pool.go:65: https://relays.syncthing.net/endpoint unknown response type from server 400 connection test failed
2020/04/03 17:37:22 pool.go:65: https://relays.syncthing.net/endpoint unknown response type from server 400 connection test failed
2020/04/03 18:37:22 pool.go:65: https://relays.syncthing.net/endpoint unknown response type from server 400 connection test failed
2020/04/03 19:37:22 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/03 20:25:23 pool.go:65: https://relays.syncthing.net/endpoint unknown response type from server 400 connection test failed
2020/04/03 21:25:23 pool.go:65: https://relays.syncthing.net/endpoint unknown response type from server 400 connection test failed
2020/04/03 22:25:24 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/03 23:13:26 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
2020/04/04 00:01:29 pool.go:54: Joined https://relays.syncthing.net/endpoint rejoining in 48m0s
</pre>
</details>

**Comment by calmh** [comment]
This could be a too-short-timeout issue indeed. I looked in the server logs and all the probes of your relay are successful, including all the ones in your log above that apparently failed. So it seems the probe succeeds yet the relay pool server returns a failure...

**Comment by calmh** [comment]
So I'm finding various inconsistencies in the code along the way, which is good/bad. :) I made one change so that the actual test error gets propagated back into the body instead of the generic "test failed", so you could look at those as well now to see what's going on...

**Comment by grandchild** [comment]
And sure enough, since 2020/04/04 07:13:32 UTC(!) no more join trouble in the logs. Whatever you did it fixed it, although it sounded like you didn't try to fix it (yet) and simply improved the error logging?

That's sad, now we can't figure out what was wrong...

**Comment by calmh** [comment]
Yeah, so I couldn't find a cause for the issue or see a path where it would look successful in the logs yet return an error. I was hoping the actual error would clarify what was going on. Now it seems more like a resource issue / leak of some kind... Maybe it happens again, and then we'll be better equipped to figure it out.
