### ISSUE TITLE
Upgrade check at start is very aggressive

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#6513]
Since the new upgrade check (#6385) we're getting a significant flood of upgrade requests. The problem is that some clients are stuck in restart loops, for various reasons, and hammer the upgrade server. We can of course offload this in various ways (CDNs and whatnot) but it still seems like an oversight that we should handle better...

Server side rate limiting at the HTTPS level isn't enormously useful as the main cost is in the TLS handshake to begin with.

**Comment by marco-m** [comment]
For my curiosity, if you have this information/time to do this, could you please post a graph comparing the rate of upgrade requests before and after that change ? Otherwise don't worry.

**Comment by calmh** [comment]
With everyone on 1.4.0, we saw about 8-10 upgrade check requests/s. Once 1.4.1-rc was out this increased to about 15-20/s (nobody noticed). With 1.4.1 proper it became about 135/s. Now it's dropping since I published 1.4.2 to roll back the change temporarily.

**Comment by marco-m** [comment]
A spike indeed!

This made me think: did you consider instrumenting syncthing for feature toggles ? Then you could run experiments (same idea of canary deployments) and gradually introduce changes like this one.

Granted, it would require efforts and additional code complexity that might not be justified.

**Comment by AudriusButkevicius** [comment]
Please stay on topic. If you want to have some feature discussion, please move it to the forums.
