### ISSUE TITLE
Permission issue with docker (stat: permission denied although it's possible)

### ISSUE THREAD

**Issue by totti4ever** [syncthing/syncthing#6515]
I moved Syncthing from Ubuntu to Docker on Ubuntu and somehow can't get it to work:

Error shown in Web-UI:
`2019-12-13 08:07:05: Error on folder “FOLDER1” (xxxxx-yyyyy): stat /datapool1/backup/PATH/FOLDER: permission denied`

Error in syncthing log:
```
WARNING: Loading ignores: open /datapool1/backup/PATH/FOLDER/.stignore: permission denied
WARNING: Failed to create folder marker: stat /datapool1/backup/PATH/FOLDER/.stfolder: permission denied
```
But I can stat that folder without Problems, when I exec into the container as user syncthing:
`File: /datapool1/backup/PATH/FOLDER Size: 23 Blocks: 17 IO Block: 1536 directory Device: 2ch/44d Inode: 286875 Links: 22 Access: (0770/drwxrwx—) Uid: ( 1004/USERA) Gid: ( 1008/USERA)`

I can also ls that directory and the .stfolder within, and cat the .stignore

Fun fact, /datapool1/backup/PATH/FOLDER2 is working without a problem. Permissions are the same - and both are working fine using sycthing without docker

_Edit:_
When the files and folder are owned by the syncthing user I don't have any problems. I do have problems, when the permissions are granted via group. But as I said, I have full access to the files in the container!

**Comment by calmh** [comment]
Hi! This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
