### ISSUE TITLE
Mac OS X 32 bits build is not working

### ISSUE THREAD

**Issue by eutampieri** [syncthing/syncthing#6516]
Opening the binary I get a panic

Here's what happens
```
dyld: Symbol not found: _fdopendir$INODE64$UNIX2003
  Referenced from: /Users/username/Downloads/syncthing-macos-386-v1.4.1/syncthing
  Expected in: flat namespace

Trace/BPT trap
```
### Version Information

Syncthing Version: latest downloadable
OS Version: Mac OS X Snow Leopard 10.6.8
CPU: Intel Core Duo (32-bit)

**Comment by calmh** [comment]
Minimum OS for our binaries is 10.10 or 10.11 (I forget), but definitely > 10.6. Sorry.

**Comment by eutampieri** [comment]
Thank you!
