### ISSUE TITLE
Option to auto accept folders from introduced devices

### ISSUE THREAD

**Issue by Confuset** [syncthing/syncthing#6519]
Hi everyone,
this is a feature request for an option that enables the "Auto Accept" feature by default for all newly introduced devices.

Motivation:
In my setup I do have a central server that basically connects all devices. The idea of that server is to allow for mutual online/offline devices to sync my data.  Occasionally I add new devices to that network, but in order to fully function I would have to connect to that central server and enable "Auto Accept" for that new device in order to be able to sync new datafolders across.
If I could set that option on that server once, would be awesome and resolve my issue :-)

This could be improved by a simple "Auto Accept Default Option"-Option :-D

Cheers and stay healthy,
Confuset

**Comment by AudriusButkevicius** [comment]
My guy says no, as I think auto accept is a hack to start with which we never should have implemented. 

People should either set up remote management, or setup their own automation that does the management. 

We will never be able to cover every scenario people come up with, so we should stay lean let people work out their own problems.

**Comment by Confuset** [comment]
Well, the question is how am I supposed to add that feature by any means? I would have to react on that "Device added" event somehow and then fiddle with the config files to actually set "Auto Accept" for that new device. I can't use ssh here, because I can not ssh into that device and than open up the UI to set the option…

My main motivation is the attack surface. If I can set this option on the device itself, I can do that from a given trusted device. No remote access, no management what so ever, is needed here. And the code for that should just be suuper simple… As it is only a default option, which currently defaults to false…which than could be defaulted to true…

???

**Comment by AudriusButkevicius** [comment]
Yes, you can read the config every 30 seconds and set the device to auto accept. 
Heck, you can probably even do it with cron, cli/jq and 20 lines of bash.

Your motivation is you can't do it yourself, or it requires work from your side.
My motivation is tit's a dangerous bolt on feature that solves a problem specific to you.

A few months down the line, we'll have another user asking for some feature very specific to his circumstances, or worse, an extension to some feature we didn't want to have in the first place.

**Comment by Confuset** [comment]
Ok. Lets just turn this around. Would you accept a PR for this?

**Comment by AudriusButkevicius** [comment]
It's not just up to me.

I'd probably be against as I haven't seen strong argument for why this should be available to everyone, as it seems fairly niche to you  (yet ironically I mostly to blame for the introducer and the autoaccept features landing...)

@calmh @imsodin ?

**Comment by calmh** [comment]
This seems like a fairly natural extension of what we already have, so I think it would pass review by me if it weren’t too ugly. I’m more skeptical towards adding new magical auto accept features.

**Comment by acolomb** [comment]
This should be easy since #7131 added a template for new devices, which includes the `autoAcceptFolders` setting.  That should get applied as well when devices are introduced.

@Confuset can you confirm this solves the issue for you?

**Comment by Confuset** [comment]
Wow, I totally forgot about this..

I think that is basically what I requested, but in a much more sophisticated manner :-)
Thanks to everyone for the great work.

I close this request as resolved.
