### ISSUE TITLE
Feature Request: Advanced Introducer i.e. Admin Node

### ISSUE THREAD

**Issue by Confuset** [syncthing/syncthing#6520]
Hey folks,
this is a feature request for some sort of centralized managment of a syncthing network or some evolution of that Introducer feature that is already in place.

Motivation:
Imagine that you have a network of devices that are located offsite. In order to introduce them to each other you would have to travel to one, get that id, travel to the other one, add that id, travel back to first one, accept to add that new device (hopefully you didn't turn the first device off; otherwise you are in for another round of that trip).
This situation was improved by adding the Introducer-Option, BUT in order for that feature to work in this scenario, you would need a third device that shares a common folder with both devices.

So my proposel would be to have some sort of "controler" option besides that "Introducer" option, that would add all devices from that "controler" regardless of common shared folders.
This should be a pretty lightweight change, as it leaves only that part behind, that you have to share a common folder between devices to be introduced to each other.

With that feature in place:
Travel to A, add  your phone or laptop as controler, travel to B, add your phone as controler.
Thats it. A and B are introduced to each other. !Awesome!

If you want/need more fine grained options, its quite simple as you could use your "controler" (phone/laptop) to decide which devices you want to share to a given device.

This would allow to have a device (smartphone or laptop that you carry along) around which can be used to connect everything in your network.

Cheery yo and stay at home, its serious, take it serious!
Confuset

**Comment by AudriusButkevicius** [comment]
This already exists: https://www.kastelo.net/arigi/

Anyways, before opening new issues, I suggest you open threads on the forum for disususion.

**Comment by Confuset** [comment]
WELL.

That is a paid service. Am I wrong to ask the original vendor of an Open Source Software about a feature, before going for a paid service? That service could just misuse your hard work to get some dollars out of YOUR work without caring for you guys? Iam not aware of any affiliation between your work and kastelo.net.

Regarding the forum thingy (and yes, I should have read stuff with more dignity)
What about adding "Feature Request? -> Check the forum" to your README.md file?
(Just a side node: https://en.wikipedia.org/wiki/Don%27t_Make_Me_Think)

Cheers. I appriciate your hard work.

**Comment by Confuset** [comment]
And btw. in order to use your forum, i have to register AGAIN for another service…

**Comment by AudriusButkevicius** [comment]
Yes, I know suggestions as to where features should go are not mentioned in the README and we've discussed it recently that we should fix that. 

Usually feature requests are not very clear and well formulated, so we ask people to move them to the forum until it's clear what they are after and if that is the best way to do this.

Your other ticket is fairly clear in what it wants, this one is a bit more wishy washy, hence my suggestion.

You can use your Github as OAuth provider to log into the forums, yet not sure what you classify as registration.

Yes, it's a paid service provided by one of the maintainers, he runs/pays for all the infrastructure so it's note some baddies making money off the poor.

It's free up to 5 devices. If you want more than 5, then yeah ... well people have to put bread on the table somehow.

**Comment by calmh** [comment]
I guess it depends on the target audience. Who is it for? Syncthing in its plain form is for individuals, “consumers” if you will. They usually have a small handful of devices and folders and adding complexity to automate is probably not worth it. 

Enterprises have other needs, and I think those needs are better solved outside of Syncthing. There are lots of solutions - chef, puppet, ansible, home brew solutions, Arigi (owner of Kastelo here, so biases acknowledged). I wrote an “autoacceptd” in about 30 minutes a while back when I genuinely needed a device that would accept all peer connections automatically (for an experiment). These things can be driven by the api and that’s typically where it needs to happen for advanced users as you’ll have secondary requirements (only auto add when it matches a certain pattern/domain/etc).
