### ISSUE TITLE
Feature request: Send-only folders with deletion ("move" mode)

### ISSUE THREAD

**Issue by garyng** [syncthing/syncthing#6521]
A [send-only](https://docs.syncthing.net/users/foldertypes.html#send-only-folder) folder (the "master") will show its _local-view_ to the cluster, and any changes on this master folder will be propagated to the cluster. 

Is it possible to configure Syncthing to delete files on the master after all the changes have been propagated? Something like _moving_ files/folder. (But somehow those deletions would not be propagated...)

```
+------------------+                         +--------+
|                  | 1. new files, sync      |        |
|      local       +-------------------------> remote |
| send-then-delete |                         |        |
|                  +----------+              +--------+
+------------------+          |
                              v
                      2. sync completed,
                         delete local files
```

I found some relevant posts on the forum though:
1. https://forum.syncthing.net/t/delete-files-after-sync/13619
1. https://forum.syncthing.net/t/noob-question-one-way-sync-ignore-deletes-from-left/9958

And issues:
1. https://github.com/syncthing/syncthing/issues/6185

Motivation:
1. Syncthing on space-limited device

Possible "workaround":
1. ~Setup a `send-only` folder to a `receive-only` folder with ignore delete, and somehow setup a script that monitor Syncthing sync status and delete all those synced files on the `send-only` folder~ I really can't figure it out, it's really complex 😅

**Comment by AudriusButkevicius** [comment]
Hey,

Sorry but I don't think syncthing fits this scenario well, what you are after is more like `rsync && rm -rf`, which is unidirectional + a bit more where as syncthing's main use-case is bidirectional sync.

You can probably craft something up yourself, like monitoring remote device completion status and  once it's 100% delete the files, and on the other side enable the ignore deletes hack.

But to he honest, I'd just run rsync on a cron or something for this scenario.

**Comment by garyng** [comment]
_That was a quick close!_

I agree that this can be done by bunch of shell scripts (everything can be glued together with shell scripts! 😆), but it kinda feels like a "workaround" like I am fighting with syncthing...
It would be convenient to the users if this is integrated into syncthing itself right? 
May I know why such feature is not considered at all? Is it:
1. technical difficulties (I would like to know more! Sync is hard!)
1. or it doesn't align with syncthing's design philosophy (like what you said, syncthing is for bidirectional sync - but _send-only_ folder is there, the _move-mode_ folder, to me, seems like a natural extension of _send-only_ folder)

---

Another reason why I create this feature request is because it seems like I can't find any other sync tools (that are similar to syncthing, but what syncthing offers are just unparallel) that have this kind of feature... (except of course the commercial ones)

**Comment by AudriusButkevicius** [comment]
I explained why this is closed.

It would be useful is syncthing washed my dishes, but we have to draw the line somewhere.

**Comment by calmh** [comment]
More specifically Syncthing is a continuous, bidirectional sync tool. What you're looking for is not sync but one time transfer, and in one direction only. Getting Syncthing to do this will indeed feel like you're fighting it, because it's not what it's made to do. `rsync && rm` on the other hand seems like it *is* designed to do what you want, and will do so with less pain and using less resources.

**Comment by garyng** [comment]
This to me is a valid and reasonable explanation, I think I will have to wash these dishes by hand 😉

--- 

Jokes aside, integrating this into syncthing could leverage what syncthing has provided though (especially the ease of pairing devices via syncthing; `rsync` would definitely use less resources, but its just pita to setup everything properly) and the user has one less thing/tool/script to care about. But seems like this is kinda a weak, not-so-compelling argument.
