### ISSUE TITLE
Improve gui favicon status 

### ISSUE THREAD

**Issue by chadsmiley** [syncthing/syncthing#6522]
The status icon was not being determined correct.  Here are my findings:
1. The current device was always being included and it status is "disconnected"
2. The syncthingStatus function was passing the device id instead of the device object like other places.
3. Device status for disconnected was not valid, might be because of #1 finding
4. Folders that had been paused where not included
4. device status of "unused" had a dash at the end, seems unusual

Changes
1. Added check for devices of the current device, so it would be ignored
2. Passed the device object to syncthingStatus
3. Added disconnected status for devices
4. Added paused status for folders
5. Changed the syncthingStatus for unused status to unused-, so there would be no impact on the rest of the system.

Testing-
I pause and disconnected both devices and folders. Also caused folders to error and caused normal syncing.

**Comment by calmh** [comment]
Was this intended to be a PR?

**Comment by chadsmiley** [comment]
Yes, sorry.

**Comment by AudriusButkevicius** [comment]
Right, closing this as this is not it.
