### ISSUE TITLE
Clean up after days feature for Simple File Versioning

### ISSUE THREAD

**Issue by jolange** [syncthing/syncthing#6527]
Hi!

Thanks for this nice tool, I like it a lot :-)

I searched the forums and issue tracker, but could not find any discussion on this:
I would like to have a "clean" feature for *Simple File Versioning*. I think something similar to the feature for [Trash Can File Versioning](https://docs.syncthing.net/users/versioning.html#trash-can-file-versioning) would be useful:

> A configuration option is available to clean the trash can from files older than a specified number of days. If this is set to a positive number of days, files will be removed when they have been in the trash can that long. Setting this to zero prevents any files from being removed from the trash can automatically.

Is there any reason to not have this for *Simple File Versioning*? I.e., remove versioned files from `.stdversions` older than XY days?

If you think this would be a desired feature, I could try to implement this (although I'm not really familiar with go, so I might take some time).

**Comment by AudriusButkevicius** [comment]
I think if you want it time based, use trash can if you want it count based use simple, then there is also staggered which is the mix of the two, hence I think you just need to pick a different versioner.

**Comment by jolange** [comment]
Thanks for your answer!

I don't quite agree with the characterization of the *Trash Can* approach as time based per se. I think it is the same as *Simple File Versioning* with just one versioned copy. Only the optional cleaning makes it time based and I think this would also be reasonable for *Simple File Versioning*.

Maybe let me explain my use case a bit more: I'd like to have several versions of deleted/modified files for the case that there are several modifications (in a short time) that I'd like to undo. On the other hand, I'd like to have cleaning after some time, e.g., after a month, because I will probably no longer need the old files. The *Staggered File Versioning* approach potentially creates too many versions for me.

So, *Simple File Versioning* is just fine for me. But I'd like to save storage space and not backup things forever. For example, if I delete a file (intentionally, because I really don't need it any longer), the file(s) in `.stdversions` would never get deleted at the moment. Of course I can do some manual cleaning from time to time by finding files older than XY days. But since there already is this feature for the *Trash Can* approach, I feel it would be straight-forward to add this feature here.

**Comment by AudriusButkevicius** [comment]
I don't think the request is crazy, but my gut says that if the user wants something else than what is there, they should use external versioner and devise their own strategy. 

We will never have all the options to cater for everyone so I am inclined to push back unless you plan to contribute the code for this.

In this specific case I think its easier to setup a cron on the side with `find foo/.stversions -type f -mtime +30 -delete` (fake example check docs).

**Comment by jolange** [comment]
Sure, feature-bloat is certainly not desirable and if you think it should not be included, that's fine. There are reasonable other ways to achieve this, like your example.

But since this feature exists already for the *Trash Can* approach (where you could also use a workaround instead), I hope it should be quite easy to adapt it for *Simple File Versioning* and at the same time not really increase the feature complexity. So if you say this feature would be included if someone implements it, I'd try to do that.

**Comment by imsodin** [comment]
To me this is a reasonable feature and I don't see problems with accepting a contribution if complexity is low (which I suspect it is). In terms of feature bloat I also think this is ok, as it doesn't add a new kind of feature just repeats an existing feature, so I don't expect it to increase future feature bloat :)

**Comment by rjpruitt16** [comment]
I would like to give it a shot

**Comment by jolange** [comment]
@rjpruitt16 feel free to! It's on my list, but low prio...

**Comment by rjpruitt16** [comment]
This issue should be closed right?

**Comment by imsodin** [comment]
Yes. Fixed by https://github.com/syncthing/syncthing/pull/6884

**Comment by jolange** [comment]
@rjpruitt16 nice, thanks for implementing this!
