### ISSUE TITLE
Add "Pause All"/"Resume All" button for devices

### ISSUE THREAD

**Issue by Vo-Shay** [syncthing/syncthing#6530]
Can we get a button to pause "This Device"'s networking/comms please?

This has come up regularly for me in the last little while with the recent increase in video conferencing due to all the work from home stuff (hope everyone is doing well!). My upload bandwidth isn't the greatest, and I need to pause Syncthing's comm's to maximize it for my video. It's also come up sometimes before for other reasons, but less so. 

Before I would pause each of the Remote devices, but lately that's growing tedious as I have an increasing number of devices. There's also not a "Pause all" remote devices button, like for folders. 

I'm not looking for a "Pause All"/"Resume All" functionality on the remote devices either. If it were to follow the pattern used for the folders, it isn't quite right either because that doesn't keep the state of the which folders were paused before the Pause/Resume All. I'm not suggesting to change that behaviour however, just showing that it's not quite what's needed here.

I just want to sometimes pause my syncthing's comm's with other devices en masse from the GUI, without changing the individual remote device's paused/unpaused state, nor without stopping the folder watching/scanning. Shutting down syncthing does achieve the effect of "Pausing comms", but then there's no GUI available to resume it.

Thoughts?

### Version Information

Syncthing Version: v1.4.2
OS Version: Debian 10

**Comment by AudriusButkevicius** [comment]
Personally I think that shutting down and restarting when you are done with whatever is the right thing todo here.

**Comment by Vo-Shay** [comment]
I guess I can see the logic in that, though I would miss the convenience of being able to use the web GUI to bring its functionality back online. (I'm hitting it from another machine, so bringing it back up becomes a different work flow.)

If that's the consensus of others as well, that pausing "This Device" is meaningless, can applying the already established "Pause all"/"Resume all" pattern to the remote devices be considered instead?

**Comment by AudriusButkevicius** [comment]
I think there is definately an argument for having pause all for devices, like we have for folders.
