### ISSUE TITLE
Deadlock on folder unsubscribe

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#6559]
More information in https://forum.syncthing.net/t/14850.

```
Panic at 2020-04-21T07:10:46+09:00
panic: database is closed

goroutine 174 [running]:
github.com/syncthing/syncthing/lib/db.(*FileSet).Snapshot(0xc0003dd080, 0xc0159dd7c0)
	C:/BuildAgent/work/174e136266f8a219/lib/db/set.go:163 +0x164
github.com/syncthing/syncthing/lib/model.(*folder).scanSubdirs(0xc0009b0000, 0xc009733840, 0x2, 0x2, 0x0, 0x0)
	C:/BuildAgent/work/174e136266f8a219/lib/model/folder.go:363 +0x34b
github.com/syncthing/syncthing/lib/model.(*folder).serve(0xc0009b0000, 0x110ea00, 0xc000997180)
	C:/BuildAgent/work/174e136266f8a219/lib/model/folder.go:185 +0x734
github.com/syncthing/syncthing/lib/util.AsService.func1(0x110ea00, 0xc000997180, 0xc00144b1a0, 0xc0000d6d80)
	C:/BuildAgent/work/174e136266f8a219/lib/util/utils.go:183 +0x40
github.com/syncthing/syncthing/lib/util.(*service).Serve(0xc000993f20)
	C:/BuildAgent/work/174e136266f8a219/lib/util/utils.go:247 +0x149
github.com/thejerf/suture.(*Supervisor).runService.func1(0xc0003e1b30, 0xc000000002, 0x1e79530, 0xc0009b0000)
	C:/BuildAgent/work/pkg/mod/github.com/thejerf/suture@v3.0.2+incompatible/supervisor.go:600 +0x57
created by github.com/thejerf/suture.(*Supervisor).runService
	C:/BuildAgent/work/pkg/mod/github.com/thejerf/suture@v3.0.2+incompatible/supervisor.go:588 +0x62
```

[panic-20200421-071046.log](https://github.com/syncthing/syncthing/files/4507383/panic-20200421-071046.log)

### Version Information

Syncthing Version: v1.4.2
OS Version: Windows 10 Enterprise 2016 LTSB x64

**Comment by calmh** [comment]
Initial feeling is we're waiting for a folder that's scanning, not sure why that takes so long though.

**Comment by imsodin** [comment]
It's trying to get a db snapshot and there's some leveldb routines mentioning compaction - if that is an actual ongoing compaction I suspect that's the reason for the wait and no deadlock.

**Comment by tomasz1986** [comment]
The folder is shared between A and B. A is "Send & Receive", while B is "Receveive Only". No new files are being added to the folder on both sides. A is constantly sending its files to B at slow speed. The deadlock happens only on B.

Also, just for completeness, we are talking about the folder discussed in https://forum.syncthing.net/t/downloading-large-files-in-one-folder-prevents-pushing-changes-to-other-folders/14513.

**Comment by AudriusButkevicius** [comment]
It seems that the puller routine exits and the rest of stuff is hanging because of that:
```
Line 575: github.com/syncthing/syncthing/lib/model.(*sendReceiveFolder).pullerIteration.func4(0xc0009b0f00, 0xc000a18280, 0xc012a40d20, 0xc012a40d80, 0xc012a40c00, 0x110c580, 0xc00b2eac10)
Line 1193: github.com/syncthing/syncthing/lib/model.(*sendReceiveFolder).pullerIteration.func2(0xc0009b0f00, 0xc012a40cc0, 0xc012a40c60, 0xc012a40d20, 0x110c580, 0xc00b2eac00)
Line 1201: github.com/syncthing/syncthing/lib/model.(*sendReceiveFolder).pullerIteration.func2(0xc0009b0f00, 0xc012a40cc0, 0xc012a40c60, 0xc012a40d20, 0x110c580, 0xc00b2eac00)
Line 1209: github.com/syncthing/syncthing/lib/model.(*sendReceiveFolder).pullerIteration.func1(0xc0009b0f00, 0xc012a40d80, 0x110c580, 0xc00b2eac20)
```

Note there is no `pullerIteration.func3`

I suspect it exits because the context gets closed:
```
if err := requestLimiter.takeWithContext(f.ctx, bytes); err != nil {
	break
}
```

and the rest of the routines do not check the context.

**Comment by AudriusButkevicius** [comment]
The idea is that even failed stuff should flow through the finisher, to unregister progress listeners. It's not ok just to terminate the pull pipeline half way through.

**Comment by imsodin** [comment]
Thanks for detecting. That's a regression from #6343. Unless you want to I'll fix this tonight.

**Comment by calmh** [comment]
Good catch

**Comment by AudriusButkevicius** [comment]
I suspect something similar might be happening with protocol package, given the Request() hanging for 42mins in the first panic log provided in the forum thread.

**Comment by tomasz1986** [comment]
Thank you for such a quick investigation. Today, while trying to set a completely new device up, I started to get even more lockups of the UI, which became completely unusable, so I have downgraded to 1.4.0 on this machine for now. Strangely enough, 1.4.2 seems to be working fine on the other devices.

**Comment by AudriusButkevicius** [comment]
Please try the build from https://github.com/syncthing/syncthing/pull/6562

See if you can still reproduce the issue.

**Comment by tomasz1986** [comment]
Hmm, I have added the commit straight on top of v1.4.2, which I hope is okay, and now I seem to be able to pause and resume the folder with almost immediate effect.

However, the GUI keeps locking up every now and then, randomly, and then suddenly comes back to life after 5-10 minutes. When locked up, all folders are "Unknown", and commands like "Shutdown" and "Restart" do not work.

![image](https://user-images.githubusercontent.com/5626656/79956165-bee9d380-84ba-11ea-8847-0ce1d3361b8c.png)
![image](https://user-images.githubusercontent.com/5626656/79956194-c90bd200-84ba-11ea-81bf-274bcbe52633.png)

Logfile from D4DZU:
```
[D4DZU] 16:43:26 INFO: "XXX" (xxxxx-xxxxx): Failed to sync 13 items
[D4DZU] 16:43:26 INFO: Folder "XXX" (xxxxx-xxxxx) isn't making sync progress - retrying in 2m41.3363883s.
[D4DZU] 16:43:43 INFO: Established secure connection to TLFGVKC--XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX at [::]:22000-217.99.29.67:22000/quic-client/TLS1.3-TLS_CHACHA20_POLY1305_SHA256
[D4DZU] 16:43:43 INFO: Device TLFGVKC--XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX client is "syncthing v1.4.2+2-g3ab5a9ec-dirty-v1.4.2-tomasz86" named "XXX" at [::]:22000-217.99.29.67:22000/quic-client/TLS1.3-TLS_CHACHA20_POLY1305_SHA256
[D4DZU] 16:43:43 INFO: Device TLFGVKC--XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX folder "XXX" (xxxxx-xxxxx) has mismatching index ID for us (0x052ED47646115491 != 0xBEBB031BC8D4679D)
[D4DZU] 16:43:43 INFO: Device TLFGVKC--XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX folder "XXX" (xxxxx-xxxxx) has a new index ID (0x040EC1D08AD43DD5)
[D4DZU] 16:43:57 INFO: Completed initial scan of receiveonly folder "XXX" (xxxxx-xxxxx)
[D4DZU] 16:44:27 INFO: Puller (folder "XXX" (xxxxx-xxxxx), item "xxx"): pull: no such file
[D4DZU] 16:44:27 INFO: Puller (folder "XXX" (xxxxx-xxxxx), item "xxx"): pull: generic error
[D4DZU] 16:44:27 INFO: Puller (folder "XXX" (xxxxx-xxxxx), item "xxx"): pull: generic error
[D4DZU] 16:44:27 INFO: Puller (folder "XXX" (xxxxx-xxxxx), item "xxx"): pull: generic error
[D4DZU] 16:44:33 INFO: Puller (folder "XXX" (xxxxx-xxxxx), item "xxx"): pull: generic error
[D4DZU] 16:44:49 INFO: quic://0.0.0.0:22000 resolved external address quic://125.190.151.7:2498 (via stun.syncthing.net:3478)
[D4DZU] 16:49:59 INFO: quic://0.0.0.0:22000 resolved external address quic://125.190.151.7:2486 (via stun.syncthing.net:3478)
```

Logfile from TLFGV:
```
[TLFGV] 09:43:28 INFO: "XXX" (xxxxx-xxxxx): Failed to sync 9 items
[TLFGV] 09:43:28 INFO: Folder "XXX" (xxxxx-xxxxx) isn't making sync progress - retrying in 1h4m53.9626529s.
[TLFGV] 09:43:45 INFO: Established secure connection to D4DZUGP-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX at [::]:22000-125.190.151.7:2486/quic-server/TLS1.3-TLS_CHACHA20_POLY1305_SHA256
[TLFGV] 09:43:45 INFO: Device D4DZUGP-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX client is "syncthing v1.4.2+2-g3ab5a9ec-dirty-v1.4.2-tomasz86" named "XXX" at [::]:22000-125.190.151.7:2486/quic-server/TLS1.3-TLS_CHACHA20_POLY1305_SHA256
[TLFGV] 09:43:45 INFO: Device D4DZUGP-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX folder "XXX" (xxxxx-xxxxx) has a new index ID (0xBEBB031BC8D4679D)
[TLFGV] 09:48:04 INFO: Established secure connection to 7LDIBZ4-RB3PP6C-ECMWW6U-MXFT3QF-3F53E5P-G4LPOQA-XIWWI7L-VP4DVAD at 20.0.0.2:14508-160.16.88.249:22067/relay-client/TLS1.3-TLS_AES_128_GCM_SHA256
[TLFGV] 09:48:04 INFO: Device 7LDIBZ4-RB3PP6C-ECMWW6U-MXFT3QF-3F53E5P-G4LPOQA-XIWWI7L-VP4DVAD client is "syncthing v1.4.2+2-g3ab5a9ec-dirty-v1.4.2-tomasz86" named "TW86-VivoTabNote8" at 20.0.0.2:14508-160.16.88.249:22067/relay-client/TLS1.3-TLS_AES_128_GCM_SHA256
[TLFGV] 09:48:05 INFO: Connection to 7LDIBZ4-RB3PP6C-ECMWW6U-MXFT3QF-3F53E5P-G4LPOQA-XIWWI7L-VP4DVAD at 20.0.0.2:14508-160.16.88.249:22067/relay-client/TLS1.3-TLS_AES_128_GCM_SHA256 closed: reading length: EOF
```

The GUI was unresponsive for about 5 minutes, i.e. from 16:44 to 16:49 on D4DZU, and from 09:43 to 09:48 on TLFGV. This all happened at the same time, just the time zones are different.

I am not sure whether this is the same problem or a completely different one though. I had a similar lockup yesterday when D4DZU was on 1.4.0 and TLFGV was on 1.4.2. I do not recall having any of these lock ups in the past though, i.e. before 1.4.1 or 1.4.2.

**Comment by AudriusButkevicius** [comment]
That is probably a different issue, but we'd need stacktraces to understand what is happening from the device that gets stuck.

On Linux you can send a SIGQUIT, on Windows, I think you'd have to run with pprof enabled (https://docs.syncthing.net/users/syncthing.html STPROFILER) and then get the traces from `http://<address>/debug/pprof/goroutine?debug=2`

**Comment by tomasz1986** [comment]
I will do.

Thank you very much for a quick fix for the deadlock problem :slightly_smiling_face:.
