### ISSUE TITLE
Create versioning directory recursively (creating parents as necessary)

### ISSUE THREAD

**Issue by HaujetZhao** [syncthing/syncthing#6565]
This is the scene: 

I set a sync folder which enabled File Versioning and set the **versions path** to `/sdcard/Syncthing control/Desktop/Markdown` , but I didn't create this path manually, and when syncing, there would be conflict, when I check the logs, it says: 

```
Puller (folder "/sdcard/Documents/Markdown" (lziuh-l9bdv), item "test.pdf"): delete file: mkdir /sdcard/Syncthing control/Desktop/Markdown: no such file or directory
```

It seems the Syncthing tries to create the versioning folder. Because it's parent folder is not created manually, and it just used "mkdir" but not "mkdir -p", it can't create the parent folder of the versioning. 

So I suggest the solution is to use `mkdir -p` to replace the `mkdir` in unix like system when creating versioning folder.

**Comment by AudriusButkevicius** [comment]
We don't mkdir or mkdir -p, these are all bash commands, there is no bash involved in our case.

I think expecting the directory to exist us a fair expectation? It would catch cases where the user misstyped the path and stuff would appear in the wrong directory, hence I am inclined to close this as won't fix.

**Comment by calmh** [comment]
We try to create the versioning dir if it doesn't exist, we just don't try to create it recursively. I don't see a case where it would be a *problem* to just create it, and the opposite clearly applies, so ...
