### ISSUE TITLE
Ship stcli in main package

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#6566]
I can't see why we don't package it.

Alternatively, we could merge it into the main binary, potentially something like
```
syncthing cli <args to cli>
```

I can do the legwork if we deem this appropriate.

**Comment by imsodin** [comment]
I like merging. I'd even go with directly using "meaningful" keywords without the `cli` command. And use e.g. `start` for the current functionality (and make that the default, such that the current way of calling stays supported).

I think the main consideration for whether or not to do this is the additional maintenance work vs added benefit. I don't remember much, but I think the `stcli` implementation was lightish (?). And a simpler way to call the rest api is imo a very nice feature (e.g. I don't need to search for powershell instructions every time I try to debug something with a windows user :D ).

**Comment by AudriusButkevicius** [comment]
The api is all reflection based nowadays, so the cli changes automatically as the config changes.

https://github.com/AudriusButkevicius/recli

**Comment by coolaj86** [comment]
How is it presently expected that one get access to the CLI?

I don't see it on the downloads page or in the documentation.

**Comment by calmh** [comment]
Currently your best bet is to build it from source.
