### ISSUE TITLE
There is always a sync-conflict after changing a file in the sync path possibly caused by Time Locale problem

### ISSUE THREAD

**Issue by JackalZhao** [syncthing/syncthing#6568]
I set up the syncthing on a **Windows PC** and a **Android Phone** , both clients synced some folders. 

Everytime I edit a file on my Android, it would perfectly synced to the Windows PC. That's great. 

But in many times when I edit a file on Windows ( such as using Notepad++ editing a md file ), on next scan and sync, there would be a conflict file generated, it's like `demo-file.sync-conflict-20200423-060452-LFYGWTG.md` . 

Here is the example, I edited the file called **demo-file.md** on Windows on **2020/04/23_14:04:40** , it was created on **2020/04/9_08:12:27** , it's last modify and sync time is **2020/04/23_14:03:12** . but after rescan and syncing, a file called **demo-file.sync-conflict-20200423-060452-LFYGWTG.md** was created. 

And there is no log on windows client created, it's just the Android side has the log: 

```
2020-04-23 06:04:52 Puller (folder "/sdcard/Documents/Markdown 文档" (lziuh-l23dv), item "demo-file.md"): handling file: file modified but not rescanned; will try again later
2020-04-23 06:04:52 "/sdcard/Documents/Markdown 文档" (lziuh-l23dv): Failed to sync 1 items
2020-04-23 06:04:52 Folder "/sdcard/Documents/Markdown 文档" (lziuh-l23dv) isn't making sync progress - retrying in 1m0.148977291s.
```

The time on the Android Client on Termux seems went wrong. But when using `date` or `time`, the phone is showing the correct time. So wired. 

So after a while of thinking, I first ran `date`, and the output was: 

```
Thu Apr 23 14:34:27 CST 2020
```

And then I ran `syncthing` , the output was: 

```
[start] 06:34:42 INFO: syncthing v1.4.2 "Fermium Flea" (go1.14.2 android-arm64) builder@8c804f3d6f78 2020-04-14 13:14:24 UTC
[OJXUX] 06:34:42 INFO: My ID: KFGJXIR-EELKJGD-JGFHJIX-CZHJOD5-VTO7CPF-2Y7B55N-IFMIIS5-YYYFSQU
[OJXUX] 06:34:43 INFO: Single thread SHA256 performance is 1194 MB/s using minio/sha256-simd (1194 MB/s using crypto/sha256).
[OJXUX] 06:34:43 INFO: Hashing performance is 569.64 MB/s
[OJXUX] 06:34:43 INFO: Overall send rate is unlimited, receive rate is unlimited
[OJXUX] 06:34:43 INFO: Listener for dynamic: unknown address scheme ""
```

So the time locale seems to be wrong in the syncthing client, it didn't use the system time locale. 

So I'd like to ask how can I fix this?

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by JackalZhao** [comment]
> This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.
> 
> Thanks!

The simple expression is : Syncthing running on arm devices is not using the same time local with the system, causeing sync conflict with other devices. 

So it is a bug I suppose.

**Comment by AudriusButkevicius** [comment]
It's not todo with arm but todo with Android specifically. 

It can't use the same timestamps because android does not allow modifying timestampsxon files, so there is a workaround implemented for that.

Anyways, if you still want to discuss this, please use the forum as already explained.

**Comment by JackalZhao** [comment]
> It's not todo with arm but todo with Android specifically.
> 
> It can't use the same timestamps because android does not allow modifying timestampsxon files, so there is a workaround implemented for that.
> 
> Anyways, if you still want to discuss this, please use the forum as already explained.

Ok, thanks a lot! I'll check the forum.

**Comment by JackalZhao** [comment]
I see, the issue was caused by Android FAT format, time local has nothing to do with it. After checking the **ignore permissions** box in the advanced settings, the conflict problem solved. 

>  Android storage is usually formatted using vFat or something like that that does not support permissions, so I suspect every time you sync a file to android, it comes back with different permissions, causing these conflicts.

I suggest this special case could be added into the introduction page or mannual or some other help page that can be easily searched to notify the new users, I'm pretty sure there must be a bunch of Android who don't know this tip and being annoyed by the frequent conflict.  @calmh @AudriusButkevicius

**Comment by calmh** [comment]
This project that you are filing an issue on doesn't run on Android. The syncthing-android wrapper that *does* run on Android sets that flag by default, afaik. And if it doesn't, the place to fix or discuss that is syncthing/syncthing-android.

**Comment by JackalZhao** [comment]
> This project that you are filing an issue on doesn't run on Android. The syncthing-android wrapper that _does_ run on Android sets that flag by default, afaik. And if it doesn't, the place to fix or discuss that is syncthing/syncthing-android.

Actually I does not use  Android Syncthing app. 

I run syncthing on Termux ( which is a terminal tool on Android and has package manager ), it can run syncthing by `pkg install syncthing && syncthing` and run the arm-release. 

I guess that's why there is no much discussion about it. Most people just use the GUI App. haha

**Comment by calmh** [comment]
Many APIs are entirely different, so the regular Linux build is not for Android. The syncthing-android project builds it specifically for Android. And indeed manages settings like this that are essentially mandatory on Android. So use the Android build.
