### ISSUE TITLE
Renaming a file in windows actually triggers a copy

### ISSUE THREAD

**Issue by ulgonia** [syncthing/syncthing#6569]
Hello,

I just installed syncthing on a linux server and on my win10 computer. I set it up to sync a folder in c:\users\username\xxx on the windows machine. 

I copied a big file (300MB) in the synced folder.

When I rename the file on the linux machine, the name of the file on windows changes almost immediately (meaning that I can see the .syncthing.xxx.tmp file only for a very short time in the file explorer, then the filename is immediately changed).

When I change the name of the file in windows, and then do some 'ls' on the linux machine, I can see the .syncthing.xxx.tmp file much longer. I also see the size of the folder growing progressively, until it reaches twice the size of my big file, and only then the initial file (the one with the old name) is removed.

I deduced that the rename event is well catched by the filesystem watcher in linux, but it isn't correctly handled in Windows.

This is very disappointing as this would mean if I move or rename the files I want to sync, this will lead to very heavy copy load to get it synced, although it would have taken only a couple of seconds to appoy the correct changes. 

I tried this using SyncTrayzor or Syncthing-GTK integrations with exactly the same results.

Please help me understanding how to get it work on windows as well.

Thanks!

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.

**Comment by ulgonia** [comment]
Sorry, didn't know about the forum!
Thank you for the link.
