### ISSUE TITLE
Could not start syncThing

### ISSUE THREAD

**Issue by katit** [syncthing/syncthing#6571]
I am trying to run last setup but get popup and following log:

[YOKRK] 15:09:44 INFO: syncthing v1.2.0 "Fermium Flea" (go1.12.6 windows-amd64) teamcity@build.syncthing.net 2019-06-28 06:03:29 UTC
[YOKRK] 15:09:44 INFO: My ID: YOKRKJP
[YOKRK] 15:09:45 INFO: Single thread SHA256 performance is 599 MB/s using minio/sha256-simd (503 MB/s using crypto/sha256).
[YOKRK] 15:09:45 WARNING: Failed to initialize config: Config file version (30) is newer than supported version (29). If this is expected, use -allow-newer-config to override.
[YOKRK] 15:09:45 INFO: syncthing v1.2.0 "Fermium Flea" (go1.12.6 windows-amd64) teamcity@build.syncthing.net 2019-06-28 06:03:29 UTC
[YOKRK] 15:09:45 INFO: My ID: YOKRKJP
[YOKRK] 15:09:46 INFO: Single thread SHA256 performance is 601 MB/s using minio/sha256-simd (506 MB/s using crypto/sha256).
[YOKRK] 15:09:46 WARNING: Failed to initialize config: Config file version (30) is newer than supported version (29). If this is expected, use -allow-newer-config to override.
[YOKRK] 15:09:46 INFO: syncthing v1.2.0 "Fermium Flea" (go1.12.6 windows-amd64) teamcity@build.syncthing.net 2019-06-28 06:03:29 UTC
[YOKRK] 15:09:46 INFO: My ID: YOKRKJP
[YOKRK] 15:09:47 INFO: Single thread SHA256 performance is 604 MB/s using minio/sha256-simd (506 MB/s using crypto/sha256).
[YOKRK] 15:09:47 WARNING: Failed to initialize config: Config file version (30) is newer than supported version (29). If this is expected, use -allow-newer-config to override.
[YOKRK] 15:09:47 INFO: syncthing v1.2.0 "Fermium Flea" (go1.12.6 windows-amd64) teamcity@build.syncthing.net 2019-06-28 06:03:29 UTC
[YOKRK] 15:09:47 INFO: My ID: YOKRKJP
[YOKRK] 15:09:48 INFO: Single thread SHA256 performance is 603 MB/s using minio/sha256-simd (504 MB/s using crypto/sha256).
[YOKRK] 15:09:48 WARNING: Failed to initialize config: Config file version (30) is newer than supported version (29). If this is expected, use -allow-newer-config to override.
[YOKRK] 15:12:45 INFO: syncthing v1.2.0 "Fermium Flea" (go1.12.6 windows-amd64) teamcity@build.syncthing.net 2019-06-28 06:03:29 UTC
[YOKRK] 15:12:45 INFO: My ID: YOKRKJP
[YOKRK] 15:12:45 INFO: Single thread SHA256 performance is 604 MB/s using minio/sha256-simd (502 MB/s using crypto/sha256).
[YOKRK] 15:12:45 WARNING: Failed to initialize config: Config file version (30) is newer than supported version (29). If this is expected, use -allow-newer-config to override.
[YOKRK] 15:12:46 INFO: syncthing v1.2.0 "Fermium Flea" (go1.12.6 windows-amd64) teamcity@build.syncthing.net 2019-06-28 06:03:29 UTC
[YOKRK] 15:12:46 INFO: My ID: YOKRKJP
[YOKRK] 15:12:46 INFO: Single thread SHA256 performance is 605 MB/s using minio/sha256-simd (507 MB/s using crypto/sha256).
[YOKRK] 15:12:46 WARNING: Failed to initialize config: Config file version (30) is newer than supported version (29). If this is expected, use -allow-newer-config to override.
[YOKRK] 15:12:46 INFO: syncthing v1.2.0 "Fermium Flea" (go1.12.6 windows-amd64) teamcity@build.syncthing.net 2019-06-28 06:03:29 UTC
[YOKRK] 15:12:46 INFO: My ID: YOKRKJP
[YOKRK] 15:12:47 INFO: Single thread SHA256 performance is 602 MB/s using minio/sha256-simd (506 MB/s using crypto/sha256).
[YOKRK] 15:12:47 WARNING: Failed to initialize config: Config file version (30) is newer than supported version (29). If this is expected, use -allow-newer-config to override.
[YOKRK] 15:12:47 INFO: syncthing v1.2.0 "Fermium Flea" (go1.12.6 windows-amd64) teamcity@build.syncthing.net 2019-06-28 06:03:29 UTC
[YOKRK] 15:12:47 INFO: My ID: YOKRKJP
[YOKRK] 15:12:48 INFO: Single thread SHA256 performance is 602 MB/s using minio/sha256-simd (507 MB/s using crypto/sha256).
[YOKRK] 15:12:48 WARNING: Failed to initialize config: Config file version (30) is newer than supported version (29). If this is expected, use -allow-newer-config to override.

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
