### ISSUE TITLE
Error message:  scan: Time.UnmarshalBinary: invalid length

### ISSUE THREAD

**Issue by kricsek** [syncthing/syncthing#6582]
I get the following error message when sharing some JPGs taken by a drone and a digital camera:

scan: Time.UnmarshalBinary: invalid length

Here is one of those pictures.
https://drive.google.com/open?id=1BhmKsWee1sDvHwUk4B_JpHWMAteaSKWP

The pictures I take with my phone don't have this problem.
The sharing itself works well but the error message bugs me.
Maybe the problem has to do something with the YYYY/MM/DD date format that we use here in Hungary?

### Version Information

Syncthing Version: v1.4.2
OS Version: Ubuntu 19.10

**Comment by AudriusButkevicius** [comment]
Do you have the full log?

Looks more like a database corruption than anything else. You can probably rename that file to something else and it will work.

**Comment by kricsek** [comment]
If I rename that file then it will be alright, the error message disappears. However if I rename it back to its original name the same error message comes back.

There is only one line about this in the log:
ápr 27 15:48:41 hostname syncthing[7118]: [XXXXX] INFO: Scanner (folder foldername, item "project/DJI_0391.JPG"): scan: Time.UnmarshalBinary: invalid length

**Comment by AudriusButkevicius** [comment]
Yeah, you might have to remove the folder, restart and readd it back. Regardless, this points at database corruption so not much we can do here.

**Comment by AudriusButkevicius** [comment]
Or does this happen to every picture? Or just a single one?

**Comment by kricsek** [comment]
I redid the whole folder share setup and now there are no problems with any of the files.
Thanks.
