### ISSUE TITLE
A field in a structure is sometimes protected by Mutex, but sometimes unprotected.

### ISSUE THREAD

**Issue by BurtonQin** [syncthing/syncthing#6584]
**What happened**:
A field in a structure is sometimes protected by Mutex, but sometimes unprotected.
This may lead to data race.
There are 2 such cases:
- [ ] `e.SubscriptionID` is not protected by `s.mut` on L318. But for all the other 3 places, it is protected by `s.mut`.
https://github.com/syncthing/syncthing/blob/5e1cd0e71af02d73abca3e4ca81d2837b442e80e/lib/events/events.go#L310-L318
- [ ] `f.offset` is not protected by `f.mut` on L757. But for all the other 19 places, it is protected by `f.mut`.
https://github.com/syncthing/syncthing/blob/5e1cd0e71af02d73abca3e4ca81d2837b442e80e/lib/fs/fakefs.go#L756-L757

**What you expected to happen**:
Data race

### Version Information

master branch, commit 5e1cd0e71af02d73abca3e4ca81d2837b442e80e

**Comment by calmh** [comment]
A is static analysis confusion, B looks genuine although inconsequential

**Comment by BurtonQin** [comment]
For B, suppose there are two threads T1 and T2 that call Write() concurrently:

**Comment by calmh** [comment]
It's in an event struct that's passed around over a channel, I don't understand what you think is the race or the place where the field needs protecting.

**Comment by BurtonQin** [comment]
Oh, I see. The mutex and the field are unrelated and there is no race here. Thank you for your timely reply.
