### ISSUE TITLE
Turkish translation, willing to help

### ISSUE THREAD

**Issue by toktay** [syncthing/syncthing#6595]
I have recently discovered syncthing, this wonderfull software, but I have not seen Turkish translation. I would like to help for  that. Please let me know, what can I do or give directions how to do it for you.

**Comment by imsodin** [comment]
Nice to hear that you'd like to help. We use transifex for translation, as explained in our contribution guide: https://github.com/syncthing/syncthing/blob/master/CONTRIBUTING.md#contributing-translations
