### ISSUE TITLE
possible "context deadline exceeded" due to user misconfiguration

### ISSUE THREAD

**Issue by ljubomirb** [syncthing/syncthing#6601]
I got _i/o timeout_ and _context deadline exceeded_ error after a while like [on this forum](https://forum.syncthing.net/t/syncthing-devices-are-suddenly-disconnected-context-deadline-exceeded-and-i-o-timeout/13633) and was able to solve it (I think), but the issue is **why** I think it happen in the first place.
When I was adding machines, I used "local discovery", it worked, I added some machines, no problem.
But then, some of machines were expected to work out of local network, and I turned off all "local discovery..." and all on that page. I did it because I already set up one machine to be open to internet, and work sort of as "server".
Now, what I think happen is that - once I do turn off all this, nothing warns me that my server IP is still set to "dynamic", where as there is nothing to tell this machine IP of "dynamic".
What I suggest is just to somehow warn user that he, when he turns off local discovery, now MUST enter remote IP, OR, it may even be better to **move that "dynamic" field** up front to different window/page, so when "local discovery" and all that is off, that this field gets enabled for input.
Now, it could be that I'm wrong for the way I solved my error altogether, but, it makes sense.

**Comment by AudriusButkevicius** [comment]
I don't think this is true, even if local discovery is off, global discovery is still enabled, and dynamic would use global discovery to find other remote devices.

If you want to discuss this, I suggest you move this to the forum.

**Comment by ljubomirb** [comment]
Not with all that turned off.

> and I turned off all "local discovery..." and all on that page. I did it because I already set up one machine to be open to internet, and work sort of as "server".

It's just a matter of moving IP field to different page, nothing else.

**Comment by AudriusButkevicius** [comment]
Sure, if you turn everything off stuff is not going to work, I'd expect users to understand that?

If a device is disconnected, it shows the discovered addresses, and in your case it would not show any addresses, suggesting why it does not work.

**Comment by ljubomirb** [comment]
But you are a human as well. Sure you understand it, everybody does, it is logical, strait forward, it makes sense, one is stupid not to understand that. But think about it - we are humans, and everywhere in human world, in real engineering, and virtual, if you have something set to "automatic", and than switch to "manual", something always appears, be it window, field, red SCRAM button.
Anyway, thank you for your time. It is a great product anyway, and great to see Go in action!

**Comment by calmh** [comment]
Just one note, the issue here is that `dynamic` doesn't make sense when all discovery methods are disabled? There is one case where this does make sense, namely for devices which only expect incoming connections.
