### ISSUE TITLE
Can Linux/Debian installation be simplified?

### ISSUE THREAD

**Issue by ljubomirb** [syncthing/syncthing#6602]
Can Linux/Debian installation be simplified?

For example, I followed instructions, but end up with broken setup, that somehow works, and I have no clue how.
I created user "machine", and followed instructions on page for systemd. At first, all worked, but after a while I realised it does not _show_ that it works:
```
● syncthing@machine.service.service - Syncthing - Open Source Continuous File Synchronization for machine.service
   Loaded: bad-setting (Reason: Unit syncthing@machine.service.service has a bad unit file setting.)
   Active: inactive (dead)
     Docs: man:syncthing(1)

May 04 00:18:05 server1 systemd[1]: /lib/systemd/system/syncthing@.service:6: Invalid user/group name or numeric ID: machine.service
May 04 00:18:05 server1 systemd[1]: syncthing@machine.service.service: Unit configuration has fatal error, unit will not be started.
May 04 00:19:49 server1 systemd[1]: /lib/systemd/system/syncthing@.service:6: Invalid user/group name or numeric ID: machine.service
May 04 00:19:49 server1 systemd[1]: syncthing@machine.service.service: Unit configuration has fatal error, unit will not be started.
May 04 11:22:16 server1 systemd[1]: /lib/systemd/system/syncthing@.service:6: Invalid user/group name or numeric ID: machine.service
May 04 11:22:16 server1 systemd[1]: syncthing@machine.service.service: Unit configuration has fatal error, unit will not be started.
```

...however, everything does works fine. And htop shows it runs under "machine" user.
I consider myself average user, but I was not able to make this work as it should, so my wish is if Debian/systemd installation can be made so it works out of the box? If syncthing user is to be added by installation, let it be, so all the user needs to do is "sudo service syncthing start". If someone else, smarter and with more experience wants to do it work under some other user, by changing service file, let him have it, but out of the box, why not like this?

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
