### ISSUE TITLE
Docker healthcheck fails when run in host network

### ISSUE THREAD

**Issue by shaaraddalvi** [syncthing/syncthing#6604]
When syncthing is run in host network configuration as per guidance [here](https://github.com/syncthing/syncthing/blob/master/README-Docker.md#discovery), the container health check fails, however everything seems to work fine.

#### Configuration:
`STGUIADDRESS=` set as environment variable.
Container is behind a reverse proxy which overwrites host header to `localhost`.

Verified by running `nc -z localhost 8384 || exit 1` inside container. Same works fine when run on host.

**Comment by calmh** [comment]
I'm not 100% sure we have that healthcheck there. I think we should remove it.

**Comment by shaaraddalvi** [comment]
Hi @calmh, raised a PR here #6616, thanks!

**Comment by thedanbob** [comment]
I had the same issue, minus the reverse proxy. For the record, I was able to fix it by setting `STGUIADDRESS=localhost:8384` and changing the healthcheck to `nc -z 127.0.0.1 8384 || exit 1`. No other combination of localhost/127.0.0.1 works for some reason.

**Comment by shaaraddalvi** [comment]
I think reverse proxy is an external factor to the problem here. Thanks @thedanbob for checking, I will also try to verify it and maybe we can add it back. @calmh, thoughts?

**Comment by shaaraddalvi** [comment]
Interesting, @thedanbob I was also able to get the health endpoint to work by setting healthcheck to `nc -z 127.0.0.1 8384 || exit 1` as you suggested but keeping `STGUIADDRESS=`. So I guess we don't need to update the documentation [here](https://github.com/syncthing/syncthing/blob/master/README-Docker.md#gui-security) while making the health check change.

**Comment by calmh** [comment]
Reintroduced check in #6649
