### ISSUE TITLE
Incorrect sequence entries created spontaneously

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#6614]
Something is bad with our sequencing stuff. This is my log for the last couple of days:

```
jb@kvin:~ % egrep -i 'my id|sequence' Library/Logs/Syncthing.log
...
[SYNO4] 14:08:12 INFO: My ID: SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC
[SYNO4] 14:51:08 WARNING: Non-increasing sequence detected: Checking and repairing the db...
[SYNO4] 14:51:08 WARNING: Non-increasing sequence detected: Checking and repairing the db...
[SYNO4] 14:51:08 INFO: Repaired 2738 sequence entries in database
[SYNO4] 14:51:08 INFO: Repaired 29491 sequence entries in database
[SYNO4] 21:51:27 WARNING: Non-increasing sequence detected: Checking and repairing the db...
[SYNO4] 21:51:27 INFO: Repaired 72 sequence entries in database
[SYNO4] 22:12:31 INFO: My ID: SYNO4VL-TKVFF25-QKC2T3V-TTK4BGU-D2ZA5OT-PDKSI3R-3P4JQVS-BL4VXAC
[SYNO4] 20:37:01 WARNING: Non-increasing sequence detected: Checking and repairing the db...
[SYNO4] 20:37:01 INFO: Repaired 117 sequence entries in database
[SYNO4] 20:37:04 WARNING: Non-increasing sequence detected: Checking and repairing the db...
[SYNO4] 20:37:04 INFO: Repaired 4459 sequence entries in database
[SYNO4] 20:37:10 WARNING: Non-increasing sequence detected: Checking and repairing the db...
[SYNO4] 20:37:10 INFO: Repaired 47953 sequence entries in database
[SYNO4] 03:53:33 WARNING: Non-increasing sequence detected: Checking and repairing the db...
[SYNO4] 03:53:33 INFO: Repaired 3668 sequence entries in database
[SYNO4] 04:29:33 WARNING: Non-increasing sequence detected: Checking and repairing the db...
[SYNO4] 04:29:33 INFO: Repaired 9 sequence entries in database
[SYNO4] 04:29:33 WARNING: Non-increasing sequence detected: Checking and repairing the db...
[SYNO4] 04:29:33 INFO: Repaired 343 sequence entries in database
jb@kvin:~ %
```

("my id" lines to indicate when syncthing was or wasn't restarted)

There are no dates, but the latest bursts are yesterday (~20:37) and during the night (03:53 and 04:29). There are no changes to my files at those times. There were likely rescans. Currently, this computer is busy scanning a lot of "changes" in one of my larger folders; because the file entries were rewritten perhaps? Which is why I noticed this, because of the activity and notices.

<img width="1208" alt="Screen Shot 2020-05-08 at 10 46 48" src="https://user-images.githubusercontent.com/125426/81388906-479e7b80-9119-11ea-82cf-a107a1a680e0.png">

**Comment by calmh** [comment]
Oh and the local state is messed up too. There are ~ 1TB of things in that folder, not 7 TB. It seems like the metadata counter gains a new "copy" of the local files whenever this happens.

**Comment by calmh** [comment]
I added some debugging and all the corrections are here:

https://github.com/calmh/syncthing/blob/2373a9272731a2e5328d299f627673cb15343354/lib/db/lowlevel.go#L890

indicating that we're leaving old sequence entries around for some reason...

**Comment by calmh** [comment]
So the reason we're not dropping old sequence keys *and* the reason it's rescanning is because getting a file returns "nope, no such file" (so no old sequence key to delete), in turn because the indirected *block list* for that file is myseriously missing...

**Comment by AudriusButkevicius** [comment]
Let's not do ref counting, let's do gc they said, it will be great they said.

**Comment by calmh** [comment]
Uh huh.

**Comment by AudriusButkevicius** [comment]
that's the only way indirect block lists can disappear, right? (other than not being written at all)

**Comment by calmh** [comment]
I hope so.

**Comment by AudriusButkevicius** [comment]
I guess returning not found is probably not helping detect this, it's probably wise to return some more specific error in this case

**Comment by calmh** [comment]
So the one advantage to doing it this way is that apart from causing havoc it's self repairing in the long run... But we should probably at the very least yell warnings as this is something that should never happen in production.

**Comment by calmh** [comment]
```
[SYNO4] 2020/05/08 11:40:43.136499 lowlevel.go:599: INFO: gc: new bloom filter with capacity 100000
[SYNO4] 2020/05/08 11:40:43.136600 lowlevel.go:609: INFO: gc: iterating files
[SYNO4] 2020/05/08 11:40:43.300000 lowlevel.go:636: INFO: gc: added 230322 block entries to filter, skipped 0 empty ones
[SYNO4] 2020/05/08 11:40:43.300014 lowlevel.go:641: INFO: gc: iterating block lists
[SYNO4] 2020/05/08 11:40:43.516113 lowlevel.go:669: INFO: gc: matched 400 block lists, dropped 60874 unused ones
```

🙄

**Comment by AudriusButkevicius** [comment]
LOL

**Comment by AudriusButkevicius** [comment]
The whole block list map stuff in my other PR could be folded into the blocklist (filenames in the list) and we could move to refcounting.

**Comment by calmh** [comment]
We don't need refcounting (imho), we just need a bloom filter that doesn't lie...

**Comment by AudriusButkevicius** [comment]
Sure, what I am saying is that I am already adding refcounting in my PR, so we might as well do it here, and not need a gc.

**Comment by AudriusButkevicius** [comment]
Then we'd have blocklist that also acts as a "which files have this hash"

**Comment by calmh** [comment]
Right, right. This one is anyway easily fixable as is.

**Comment by imsodin** [comment]
Right now this is potential hot-fix release stuff, for which just fixing bloom is more suitable. Definitely need to check that PR though anyway, forgot about revisiting that (sorry).

**Comment by calmh** [comment]
We're cool on this, we don't have a release yet out with the bloom filter change. It's just me being bleeding edge.

**Comment by calmh** [comment]
It's not even that, it's just a mistake in using the changed bloom filter:

https://github.com/syncthing/syncthing/commit/44b0f0b4#diff-e4dc421e8157ba4e8ba69c47a592dd10R650

it tests for the existence of the database key in the filter, not just the block hash part of it.

**Comment by greatroar** [comment]
:frowning: Sorry about that.
