### ISSUE TITLE
stuck at 99%, 40 out-of-sync files even tho they are ignored.

### ISSUE THREAD

**Issue by NinoM4ster** [syncthing/syncthing#6622]
version 1.5.0, windows (Synctrayzor) is stuck at Syncing 99% and shows 40 out of sync files, which are all desktop.ini files that I specifically added to the .stignore file to avoid getting them synced over.

I deleted all previously synced desktop.ini files from the server manually (from before I added the ignore rules), restarted both instances twice, re-scanned them more times than I can remember. nothing got rid of the files.

![image](https://user-images.githubusercontent.com/8485761/81460864-66832900-917e-11ea-8ab8-a47371eb0e7d.png)

 (HC-PC is my workstation and Poseidon is my backup server running Ubuntu, also v1.5.0)

the .stignore looks like this:
![image](https://user-images.githubusercontent.com/8485761/81460853-566b4980-917e-11ea-8d5d-b63f0f0215eb.png)

 ...which basically ignores useless files and only syncs the important folders (inside the home dir)

I doubt the .stignore file is wrong, since I was using it for months now and this is the first time this has happened. but I'm open to suggestions..

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
