### ISSUE TITLE
Config.xml to keep same inode

### ISSUE THREAD

**Issue by keithy** [syncthing/syncthing#6628]
I was attempting to backup the config file without risking the sharing of private keys.
Attempting to create a hardlink of the config.xml to a folder that is backed up, did not work.
I figure that this would be a simple but useful feature.

**Comment by calmh** [comment]
It's actually the opposite of how we want things to work, unfortunately. What happens currently is that on change we write to a temp file, then rename that temp file over config.xml. To keep the same inode would mean truncating and overwriting the current file, thus having a window of a broken config file during which we might crash or exit. That would trash the config which would be bad.

**Comment by keithy** [comment]
In that case, can the config file be placed in a sub-directory that does not also contain private keys. So that that sub-directory can be a symlink to elsewhere, i.e. /etc/syncthing

**Comment by calmh** [comment]
Those are part of the config, essentially. The config is useless without the keys, and conversely the config includes the API key which is equally sensitive as the keys.

**Comment by keithy** [comment]
In that case one might suggest that the config could to be usefully split into confidential stuff (secrets), and config stuff, like folders and device ids. Some way of playing nice with being able to share the set of folders and devices configuration with your colleagues.

For example, many organisations the security guys set things up, and the environments/operations guys configure the actual use.

**Comment by imsodin** [comment]
That's possibly better handled by config deployment tools (ansible et al) and anyway sounds more like a support request at this point. At the very least it will require some discussion to flesh out the needs and potential ways to address it, so please move that discussion to https://forum.syncthing.net/. When in the end a concrete proposal for improved config handling on Syncthing's side emerges, we can open an issue for that again. Thanks!
