### ISSUE TITLE
LDAP: Support for Bind Credentials

### ISSUE THREAD

**Issue by jensrudolf** [syncthing/syncthing#6632]
It would be nice to have support for using Bind credentials for LDAP authentication as in our company we don't support anonymous LDAP access. It would be sufficient to have another field like "Bind Password" in the LDAP config section.

**Comment by calmh** [comment]
Syncthing binds with the username/password given, so the user that is logging in needs bind access but it doesn't need to be anonymous.

(A bind password sounds simple but raises questions of how/where to store it as we don't really want cleartext passwords in the config... :/)

**Comment by jensrudolf** [comment]
Hi,
thanks for the very quick response. I am seeing the following response on the log when trying to log in via ldap:
```
15:06:58 WARNING: LDAP Bind: LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580
15:06:58 WARNING: LDAP Bind: LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C090442, comment: AcceptSecurityContext error, data 52e, v3839
```
Just to be clear: the  bind password for LDAP is different from the user (Active Directory) password. Actually, the common user does not know it, as it is set up by the administrator. Could the private host key be used to store it in an encrypted way?

**Comment by jensrudolf** [comment]
Didn't want to close. Hit the wrong button :-(

**Comment by calmh** [comment]
That just means the user credentials entered was invalid, or you user name pattern does result in a valid AD username.

**Comment by calmh** [comment]
I suggest you look at the config example for AD, https://docs.syncthing.net/users/ldap.html , and if this doesn’t work for you perhaps open a forum thread to discuss. A bind password wouldn’t help with whatever you are running into as we anyway need to do the user bind to validate the credentials.

**Comment by jensrudolf** [comment]
OK, you're right. I messed up the bind DN setting. Got it working now. Thanks and sorry to bother.
