### ISSUE TITLE
user systemd file is broken

### ISSUE THREAD

**Issue by Commissar0617** [syncthing/syncthing#6636]
May 12 21:30:01 Syncthing2 systemd[1]: Started Syncthing - Open Source Continuous File Synchronization.
May 12 21:30:01 Syncthing2 syncthing[3104]: $HOME is not defined
May 12 21:30:01 Syncthing2 syncthing[3104]: panic: Failed to get user home dir
May 12 21:30:01 Syncthing2 syncthing[3104]: goroutine 1 [running]:
May 12 21:30:01 Syncthing2 syncthing[3104]: github.com/syncthing/syncthing/lib/locations.userHomeDir(0xc0000e1e90, 0x40d7cd)
May 12 21:30:01 Syncthing2 syncthing[3104]:         /opt/tcagent/syncthing-1-work/174e136266f8a219/lib/locations/locations.go:178 +0xd3
May 12 21:30:01 Syncthing2 syncthing[3104]: github.com/syncthing/syncthing/lib/locations.init.0()
May 12 21:30:01 Syncthing2 syncthing[3104]:         /opt/tcagent/syncthing-1-work/174e136266f8a219/lib/locations/locations.go:53 +0x34
May 12 21:30:01 Syncthing2 systemd[1]: syncthing.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 12 21:30:01 Syncthing2 systemd[1]: syncthing.service: Failed with result 'exit-code'.
May 12 21:30:06 Syncthing2 systemd[1]: syncthing.service: Service RestartSec=5s expired, scheduling restart.
May 12 21:30:06 Syncthing2 systemd[1]: syncthing.service: Scheduled restart job, restart counter is at 1.
May 12 21:30:06 Syncthing2 systemd[1]: Stopped Syncthing - Open Source Continuous File Synchronization.

this is on a fresh install on debian 10

**Comment by calmh** [comment]
How did you activate the unit file, and is there something particular about your user? Not setting `$HOME` seems bizarre

**Comment by calmh** [comment]
Closing since you also opened a forum topic on the same issue. To be reopened if the unit file is in fact broken.
