### ISSUE TITLE
Data should be cloned instead of copied when possible

### ISSUE THREAD

**Issue by koro666** [syncthing/syncthing#6643]
Syncthing should use the [FICLONERANGE](https://man7.org/linux/man-pages/man2/ioctl_ficlonerange.2.html) ioctl to clone data it already has instead of doing a dumb `read` + `write`.

This would improve performance and disk usage immensely on CoW filesystems.

I ran into this scenario today. I have one shared folder with the following structure:
```
root
    directory
        subdirectory{0..n}
```
It has about 360GB of stuff scattered amongst the subdirectories.

I decided to reorganize `directory` by adding one additional level of "category" directories and moving the original subdirectories into them:
```
root
    directory
        category{0..n}
            subdirectory{0..n}
```
Then I ran the folder rescan. Once the remote device started updating, it took a very long time. In total only about 120MB were transferred, so it clearly knew to get the data from the files it already had.

I did a cursory `find . -type f -exec stat -c '%w %i %n' | sort` in the directory on the remote side afterwards, and it seems that while it was able to do a file move for about half of the files, for some reason it decided to create new files and dutifully - but slowly - copy the contents over from the old files, over the course of about 2 hours.

If it had instead cloned the data from the old files, it would have been done much quicker and without extra disk usage.

**Comment by imsodin** [comment]
https://github.com/syncthing/syncthing/pull/5544

**Comment by AudriusButkevicius** [comment]
More like dup of #4271
