### ISSUE TITLE
panic: nil pointer dereference in leveldb.(*DB).isClosed()

### ISSUE THREAD

**Issue by mohe2015** [syncthing/syncthing#6653]
### Does your log mention database corruption?
No

### Include required information

Please be sure to include at least:

 - Syncthing https://github.com/syncthing/syncthing/commit/5c9dc4c8831566d1ff2ad8cf4047fbd02aff8867 (master)

# What I did
- reset everything on this side, reset database on other side, tried adding folders for this side

# What happened
Panic. https://gist.github.com/mohe2015/2db012669030f3b7c8a8f28f8ed0f445

# Steps to reproduce
I don't know I think the current master is just broken.

**Comment by calmh** [comment]
This crash happens because we use a db snapshot after releasing it, which is our bug and also a bug in the db package...

**Comment by calmh** [comment]
Try now.

**Comment by calmh** [comment]
Also relevant, https://github.com/syndtr/goleveldb/pull/320

**Comment by mohe2015** [comment]
Seems to work.
