### ISSUE TITLE
Syncthing on windows does not differentiate between letter cases, but on linux does

### ISSUE THREAD

**Issue by NKSHV** [syncthing/syncthing#6663]
On sender device there are 3000 files, on receiver - empty folder. I set everything up and 3000 files were correctly downloaded to the receiver device. Receiver device shows "idle". However, on sender device, it still shows "syncing 98%" and 26 out of sync items, even though they are on receiver device. Most or all of those 26 items were renamed at some point to change letter case, but I assume that wasn't registered by syncthing. So it successfully sends those files to linux, but shows that those items are out of sync. This is incredibly annoying because I don't know which items are actually out of sync and which are just different case filename.

**Comment by AudriusButkevicius** [comment]
This is known and there already exists an issue for this. I think it's also mentioned in the faq.

If you are looking for help, please use the forum.
