### ISSUE TITLE
FSEvents on macOS

### ISSUE THREAD

**Issue by svoop** [syncthing/syncthing#6667]
I know, this topic has been touched and dismissed in #9. But considering 6 years have meanwhile passed, it's maybe worth taking another look.

Context: I use Syncthing to sync large development codebases between a local Mac (editor, git) and a remote server (run tests on every save, async test builds etc). It's therefore important that changes in a large directory tree with currently >10'000 files are picked up ASAP.

Unfortunately, I don't do Go (yet :-), but I've had the same discussion "inotify vs FSEvents" years ago with autotest for Ruby: autotest monitors the filesystem for modifications and then fires the tests for the modified files. The default implementation uses inotify which is very slow and energy hungry on macOS. My very slim autotest-fsevent gem replaces inotify with FSEvents which is like night and day: Very quick and almost no measurable overhead.

Again, looking at it from my no-Go perspective, when implemented as OS-dependent backends with a unified way to communicate the changed files to the core, it shouldn't be impossible to support different FS monitors.

No need to start from scratch neither, I found at least one implementation: [FSEvents for Go](https://github.com/fsnotify/fsevents).

**Comment by imsodin** [comment]
It hasn't been dismissed, it has been implemented a long time ago.

**Comment by svoop** [comment]
Cool, thanks for the heads-up!
