### ISSUE TITLE
Creates directories on the other side of directories it lacks permission to read

### ISSUE THREAD

**Issue by gmelchett** [syncthing/syncthing#6670]
I run syncthing as my normal user. On one of the two computers running syncthing,
I have the following sub directory in a directory that gets synced:

`drwxr-x--- 1 root  root     2 May 20 19:01 .snapshots`

(I use snapper on that computer)

On the other computer, syncthing creates empty directory named `.snapshots` owned by the user running syncthing.

I was expecting syncthing to ignore directories it lacks access to.

Syncthing version: 1.5.0, Arch linux (both computers)

**Comment by AudriusButkevicius** [comment]
Syncthing tries to sync as much as it can. It knows the directory exists hence it creates it due to the "as much as it can".
