### ISSUE TITLE
Devices Out of sync but not really

### ISSUE THREAD

**Issue by LubosKolouch** [syncthing/syncthing#6671]
I have 2 devices syncing a folder "Maildir" between each other.
Both on Arch Linux 64bit, syncthing 1.5.0

On both devices the folder is shown as up-to-date.

But in the devices list, both show 
1: Out of Sync Items | 50 items, ~31.4 MiB
2: Out of Sync Items | 53 items, ~31.4 MiB

If I check what they are, seems they are waiting for each other:

dev1: 
Path | Size | Mod. Time | Mod. Device
-- | -- | -- | --
.Archive/tmp |   | 2020-05-15 10:12:30 | dev2

dev2:
.Archive/tmp |   | 2020-04-04 14:41:21 | dev1
-- | -- | -- | --

If I delete the folder .Archive/tmp, it does not help - it is correctly synchronized between the devices, but they stay out of sync.

Expected behavior:

The devices are not shown as out of sync.

**Comment by AudriusButkevicius** [comment]
Hi,

This looks more like a support issue, so I suggest you search the forums for prior art for solving this, and start a thread there if nothing helps.

Thanks.
