### ISSUE TITLE
password is "-p 8384:8384 -p 22000:22000",can not login

### ISSUE THREAD

**Issue by hktalent** [syncthing/syncthing#6672]
password is "-p 8384:8384 -p 22000:22000",

can not login
<img width="879" alt="image" src="https://user-images.githubusercontent.com/18223385/82562842-9a137980-9ba8-11ea-8798-c32af3a9f94e.png">

thanks

**Comment by imsodin** [comment]
This looks like a support request, please post on https://forum.syncthing.net for that.
