### ISSUE TITLE
Local discovery of 5 nodes only happens in one node

### ISSUE THREAD

**Issue by rht** [syncthing/syncthing#6675]
version: syncthing v1.0.0-ds1 "Erbium Earthworm" (go1.11.6 linux-amd64) debian@debian 2019-06-08 10:15:59 UTC [noupgrade]
OS: Debian Buster

I set up 5 syncthing nodes each listening to different GUI addresses. I set `globalAnnounceEnabled` and `relaysEnabled` to False. Then I let the nodes run so that they may discover each other. Almost immediately, 1 node (let's call this node 1) is fully connected to the rest of 4 nodes, with the remainder partially connected to each other. This keeps going indefinitely without extra pairing (I waited for half an hour) until I stop node 1, and also restart the remaining 4. Then another node becomes fully connected (say, node 3). I have to stop node 3 and restart the remainder again. Perhaps at any given time, a single node is absorbing all the multicast packets?

I expected the local discovery to happen immediately for the 5 nodes. But instead I had to manually restart the nodes.

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
