### ISSUE TITLE
File case renames create duplicate files on receive only end 

### ISSUE THREAD

**Issue by tezfair** [syncthing/syncthing#6677]
Only came across this today and have tried on different sending ends to check. (I have send/ receive only). I also have case sensitivity enabled on receiving end windows.

Make a file in the sending end, file type or size not important, type it in uppercase. It syncs correctly. Now rename the sending end to lowercase, a new file is created. But it now means the there is a file duplication

Send end before test

![image](https://user-images.githubusercontent.com/17702842/82762634-06d18280-9dfa-11ea-87c1-8eb2821a8026.png)

receive end before test

![image](https://user-images.githubusercontent.com/17702842/82762645-18b32580-9dfa-11ea-8319-f59ad843c034.png)

add test file in caps (ignore file is empty)

![image](https://user-images.githubusercontent.com/17702842/82762678-4a2bf100-9dfa-11ea-8af3-f98e6796c3d6.png)

received
![image](https://user-images.githubusercontent.com/17702842/82762672-40a28900-9dfa-11ea-9c3e-b556a927e9a8.png)

rename on sending end
![image](https://user-images.githubusercontent.com/17702842/82762707-6f206400-9dfa-11ea-9b04-00684b354eee.png)

duplication on receiving end
![image](https://user-images.githubusercontent.com/17702842/82762713-7a738f80-9dfa-11ea-8ce4-babe551a5858.png)

both ends says there's 2 files, when in fact there is only one at the sending end
![image](https://user-images.githubusercontent.com/17702842/82762727-95460400-9dfa-11ea-90b7-828e5c8d0ae9.png)

![image](https://user-images.githubusercontent.com/17702842/82762733-a0009900-9dfa-11ea-8109-ea4d8a791e8f.png)

rescanning doesn't seem to realign the count.

**Comment by AudriusButkevicius** [comment]
Duplicate #1787

**Comment by tezfair** [comment]
apologies,
