### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by rahrah** [syncthing/syncthing#6683]
Hi,

I'm getting:

```
# github.com/syncthing/syncthing/cmd/strelaypoolsrv
cmd/strelaypoolsrv/main.go:277:14: cannot use as (type string) as type assets.Asset in argument to assets.Serve
```
and
```
# github.com/syncthing/syncthing/lib/api
lib/api/api_statics.go:38:3: cannot use auto.Assets() (type map[string]string) as type map[string]assets.Asset in field value
```
after commit:
```
baa38eea7a848ce693d8187e1a7a3ddb6a7fa55a

lib/assets: Allow assets to remain uncompressed (#6661)

```
I'm on go version: `go1.14.3 linux/amd64`

Thanks,

===Rich

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by calmh** [comment]
```
git clean -fxd
./build.sh
```
