### ISSUE TITLE
panic: runtime error: invalid memory address on mac

### ISSUE THREAD

**Issue by maruthijr** [syncthing/syncthing#6698]
### Does your log mention database corruption?

No
### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using
syncthing v1.1.1 "Erbium Earthworm" (go1.12.1 darwin-amd64) teamcity@build.syncthing.net 2019-03-25 11:43:21 UTC on Mac OS Mojave
 - browser and version, if applicable
No
 - what happened,
Syncthing refuses to start.
 - what you expected to happen instead, and
 - any steps to reproduce the problem.
Syncthing is started with command: syncthing -home path-to-config> -logfile path-to-config/log -no-browser -verbose
Attaching the entire syncthing folder here
[syncthing.zip](https://github.com/syncthing/syncthing/files/4714430/syncthing.zip)

**Comment by calmh** [comment]
You have an old version, and a folder configured with an empty path (somehow). You should upgrade, and must fix that folder path (config.xml):

```
<folder id="wksp-15929-dev" label="wksp-15929-dev folder" path="" ...>
```
