### ISSUE TITLE
Error handling  types

### ISSUE THREAD

**Issue by artback** [syncthing/syncthing#6704]
Error reporting should be made by creating an Internal Error interface which implements the Error() string function. 

This would make it possible to put a code etc on the error message as well as a stack trace to the function of error. The messages would also be more consistent. 

For more info read article:
https://middlemost.com/failure-is-your-domain/

Each package could have it's own implemented error types that returns a top level error.

```
type Error struct {
	// Machine-readable error code.
	Code    string
	// Human-readable message.
	Message string
	// Logical operation and nested error.
	Op      string
	Err     error
}
type InvalidTokenError struct {
	Op  string
	Err error
}

func (err *InvalidTokenError) Error() string {
e :=   syncthing.Error{Code: EINVALID, Message: "missing or invalid user token", Op: err.Op, Err: err.Err}
 return e.Error()
}

```

**Comment by AudriusButkevicius** [comment]
We have no interest to show stack-traces to users, nor codes (as they are not interesting to users) and wherever we care about the type of error, we actually have 

```
var ErrThisIsSpecificTypeOfFailure = errors.New("specific failure")

...
err := operation()
if err == ErrThisIsSpecificTypeOfFailure {
   // handle the special case
} else if err != nil {
   // handle the general case
}
```




So it seems like "I read a cool article, now go do it" kind of thing.

Whats the value of this or the actual utility of this where this would be useful?



Furthermore, getting a stack trace is an incredibly expensive operation which has to completely stop the runtime, so doing that just to wrap `io.EOF` because the article said it's what the cool kids do, would be insane.

**Comment by calmh** [comment]
Or, less rudely, what tangible benefit does it bring?

**Comment by AudriusButkevicius** [comment]
Sorry, I know my reply is written in a snarky offensive way, apologies for that, but I am just allergic to re-architect everything you've done suggestions when they don't explain why.

It's hard to gauge if this is a serious suggestion or if it's just an article you want to point out which you think might be relevant in the future.

**Comment by calmh** [comment]
So the funny thing is Go nowadays supports arbitrarily complex error taxonomies with inheritance, if one so wishes (chaining with `%w` and `errors.Is()`). Introspection is possible in a quite fine grained manner without elaborate error types. Error codes have their use in certain applications, but I'm not sure Syncthing is one of them, so I'm not sure about the purpose of this proposal either. But there might be one.

**Comment by artback** [comment]
The Op in the example is not supposed to is just supposed to be a logical stack trace. `"packageName:FunctionName" `

Having logical stack trace or Error codes is not a must either the main part was using elaborate error types. Also some of the package have error types such as the db. 

One downside with having package level error variables is that they could potentially be reassigned. 

It is not a very serious and very time consuming fix.  Probably breaking a lot of test cases.

**Comment by AudriusButkevicius** [comment]
What other benefits are there other than protection from re-assignment?

It seems like a lot of low value (in terms of what it brings to the users) work if all we're getting is protection from re-assignment.

The logical stacktrace part we already achieve by chaining errors.Wrap("context", underlyingErr) on the way "up".

**Comment by artback** [comment]
I guess from a user perspective it is very little difference. More of a code style issue.

**Comment by AudriusButkevicius** [comment]
I mean refactoring is also low value from users perspective usually, so it's not that we never do the "low value from users  perspective" work, we do do it, but usually there needs to be some upside to it.

So far protection from reassignment is one, but that doesn't seem to be significant enough to warrant the work this would require.

What else would we gain from this? Which specific parts of the code would be simplified by this?
