### ISSUE TITLE
Updating to 1.6.1 killed the whole home network (unintended ARP poisoning?)

### ISSUE THREAD

**Issue by javierguerragiraldez** [syncthing/syncthing#6708]
I've been running Syncthing 1.5.0 on six machines (one Raspberry Pi 3B+ with raspbian Buster and a USB HDD, three laptops + 2 desktops all on Kubuntu 18.04) without issues.

yesterday, I updated to 1.6.1 on my main laptop and the whole network failed.  no machine could access internet, or ping any other, not even the router, or the wired raspberry.

At first I thought the router was faulty, then suspected a thermal issue because everything worked a few minutes when I power-cycled the router.  Finally noticed that everything worked until I opened my laptop.  Disabling the updated Syncthing process restored sanity.

I tried downgrading to 1.5.0 but the DB has been migrated.

I suspect the updated version is poisoning the ARP table of the other hosts, since shutting down my laptop wasn't enough to restore functionality; i had to reset the Wifi or wired connection of the other hosts to make them work again.

has there been any change in the automatic host detection between 1.5.0 and 1.6.1?

I can do packet captures if necessary, but I'd prefer not to bring the network down again.

**Comment by calmh** [comment]
We don't do anything low level enough to cause something like this I think. If you see something we shouldn't do, please do upload a pcap and we'll fix it. In the meantime I suspect something else is the root cause.
