### ISSUE TITLE
Add "ignore deletes" to folder edition

### ISSUE THREAD

**Issue by robsonsobral** [syncthing/syncthing#6712]
Hi!

I use Syncthing to backup mobile devices and "Ignore deletes" is an important part of the process. Is it possible to add this configuration to the "Advanced" tab of Edit Folder? Currently, the option is hidden into "Advanced configuration", together with all folders and devices.

**Comment by AudriusButkevicius** [comment]
It's not a feature that is well supported hence we really do not we want to encourage it's use, the opposite, I think we want people to stop using it, as I think we'd remove it, if we could, so I don't think this will happen.

**Comment by robsonsobral** [comment]
Thank you for your attention, @AudriusButkevicius .

IMHO, to remove it would make things confuse, since the existence of "sender only" and "receiver only" folders; and to remove them all would limit too much the functionality of Syncthing.

Thank you so much! Have a good COVID19 isolation. Thank you!

**Comment by AudriusButkevicius** [comment]
There is a huge difference between the folder types and the ignore deletes flag. Ignore deletes literally discards some protocol messages it receives leaving it in a permanently inconsistent state that needs magical steps to recover from.

**Comment by robsonsobral** [comment]
I was talking from user point of view. "Sender" and "receiver only" are unidirectional syncs. Without your dev of tool itself background, it's weird to see any difference from "ignore delete".

And, "receiver only" for you means "receiver of modifications". I doubt not many people think of it as "receiver of files".

I hope I gave something to think about, even if it's only to make you more certain of your opinion.

**Comment by AudriusButkevicius** [comment]
My point is that ignore deletes is a hack, it's literally a single 3 line if statement that leads to corruption of state.

Ignore deletes could be made into a feature that is done sensibly, and I don't mind exposing features, but I do mind exposing hacks.
