### ISSUE TITLE
Slash should not be replaced by space when auto accept

### ISSUE THREAD

**Issue by sheepduke** [syncthing/syncthing#6718]
### Does your log mention database corruption?
no.

### Affected versions/platforms:
- v1.3.1 Android (AArch64)
- v1.5.0 Linux

### When
1. The device B is configured to accept anything from A automatically.
2. The path of file synchronized contains slash `/`, e.g. `projects/config`.

### Expected
The device B should automatically accept and create a directory `projects/config`.

### Actual result
The slash in the path was replaced by space, i.e. `projects/config` -> `projects config`.

It makes it really hard to keep the exactly same hierarchy among multiple devices.

### Explanation

In my scenario, I have many folders under `projects`, but I just want to sync some of them among my PC, laptop and 2 Android phones.

I really appreciate it if you can fix this, or at least provide some work-around. :-)

**Comment by sheepduke** [comment]
Oh I see a discussion here: https://forum.syncthing.net/t/auto-accept-does-not-create-subfolders-changes-slash-to-space/13174/17

**Comment by sheepduke** [comment]
@calmh Why is it closed?
I suppose this is not fixed yet, right?

And I did not find it in the GitHub issues.

**Comment by calmh** [comment]
You yourself linked to the discussion explaining why this will not happen.

**Comment by sheepduke** [comment]
@calmh I undertand it now.

But is there any method to get rid of the filtering, i.e. make folder labels the path?

**Comment by AudriusButkevicius** [comment]
No.
