### ISSUE TITLE
Include Patterns

### ISSUE THREAD

**Issue by 5x3** [syncthing/syncthing#6720]
Please introduce the 'Include Patterns' like you already done with 'Ignore Patterns'.

I want to share whole disk partition but only .TXT files and other text files from it, adding all possible file suffixes in ignore patterns - is not sane. the right way is to introduce list of exact patterns you want to include.

Also you can follow apache httpd convention with 'Ignore before Include', and 'Include before Ignore' option.

**Comment by calmh** [comment]
You can do that. 

```
!*.txt
*
```
