### ISSUE TITLE
Not Syncing

### ISSUE THREAD

**Issue by JodieAnneInk** [syncthing/syncthing#6728]
Hi,

We recently ran a factory reset on the computer we have synctrayzor installed on. 
When re-launching it is telling us we have zombie processes still running - we did a full un-install and a full re-install and it's still giving us this error message.

I'm wondering if there is anywhere where files could of saved that would be causing this issue? Any help on getting back running would be greatly appreciated!
![synctrayzor](https://user-images.githubusercontent.com/66683472/84156816-e0e6e780-aa61-11ea-9024-df96b7d10c51.PNG)

**Comment by AudriusButkevicius** [comment]
This 
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
