### ISSUE TITLE
allowedNetworks from https://docs.syncthing.net has no value in .config. Does it sill exist?

### ISSUE THREAD

**Issue by lockywolf** [syncthing/syncthing#6731]
### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using
1.6.1
 - what happened,
I went to https://docs.syncthing.net and saw the parameter "allowedNetworks", and then opened `/var/lib/syncthing/config/config.xml` and didn't find such a parameter there.
 - what you expected to happen instead, and
I expected to find this parameter set to a default value.
 - any steps to reproduce the problem.
See above.

**Comment by calmh** [comment]
Certainly it exists. However, lists with zero items are represented as zero items in the config.xml. And please use the forum for questions, not the issue tracker.
