### ISSUE TITLE
Add a "Run Condition" to Syncthing Android to run on a tethering hotspot only.

### ISSUE THREAD

**Issue by lockywolf** [syncthing/syncthing#6732]
### Include required information

Please be sure to include at least:

 - what problem your new feature would solve

The most natural way to connect a laptop with a smartphone is to run a tethering hotspot on a smartphone. Indeed, creating a hotspot on a laptop requires painful manipulations with the Network Manager, and third-party wifi routers are not always available. However, almost every Android smartphone support tethering hotspots. It is very natural to restrict Syncthing usage to those tethering hotspots only.

 - how or why you think it is generally useful (i.e., not just for you)

Provides the most natural way to specify "only run local synchronization" without any other configuration, such as WiFi Network names.

 - what alternatives or workarounds you considered

Limiting connection to Laptop wifi only (tricky at best).
Limiting connection to a local wifi router (not always available).
Running on mobile data (extremely slow and expensive).
Running on a cable (not implemented).
Adding the tethering network to a list of "Run on specified Wi-Fi networks" (syncthing does not know about tethering networks at all).

**Comment by calmh** [comment]
Hi! This is unfortunately the wrong repository / issue tracker for your issue. Please file it in http://github.com/syncthing/syncthing-android/issues to get the correct attention.
