### ISSUE TITLE
sync file event notify

### ISSUE THREAD

**Issue by seamanm** [syncthing/syncthing#6738]
### Include required information
hope to be able to send information to the configured HTTP address when the file synchronization is complete, and have an external system take care of the rest of the business
Please be sure to include at least:

 - what problem your new feature would solve
 - how or why you think it is generally useful (i.e., not just for you)
 - what alternatives or workarounds you considered

**Comment by calmh** [comment]
Please see https://docs.syncthing.net/dev/events.html and followup with questions or discussion on the https://syncthing.community/ forum.

**Comment by AudriusButkevicius** [comment]
You can use the API to construct something like this.
