### ISSUE TITLE
"Nightly" release channel

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#6758]
The release candidates aren't generally broken enough for my taste, so I like to run the latest dev build. Currently this is a little bit annoying as I need to manually build and copy out the binary to my boxes, so I only upgrade them every now and then. This seems like a waste when we have a perfectly fine build available on the build server. There are several ways I could scratch my itch:

- Hack a script to pull the latest build from the server and upgrade to it. Advantage: I can do this now. Disadvantages: It depends on how the system is set up, how Syncthing runs and where Syncthing is stored. I don't want to make a Powershell variant for Windows.

- Make the build server sign the builds and create a separate upgrade feed for it, say https://build.syncthing.net/nightly.json. The Syncthing-side config then consists of 1) enabling upgrades to pre-releases, 2) changing the upgrade server URL. Advantages: Easy to do, no Syncthing code changes. Disadvantages: It's not just a dropdown selection in the config?

- As above but include it in the main feed and add a new option in Syncthing so you can choose "Nightly" where you currently choose between stable and release candidates. Advantage: everyone can now easily access this thing. Disadvantage: maybe everyone shouldn't? Requires writing actual code.

**Comment by calmh** [comment]
Imma start with option two as that is convenient for me and doesn't commit to anything onerous in the long term.

**Comment by AudriusButkevicius** [comment]
I'd prefer 3 over 2, as it's easier for users

**Comment by calmh** [comment]
I think we can move to 3 from 2 while the opposite is more breaking.

**Comment by calmh** [comment]
https://docs.syncthing.net/users/releases.html#nightly-builds
