### ISSUE TITLE
Run sync as superuser

### ISSUE THREAD

**Issue by morfikov** [syncthing/syncthing#6759]
I found out that syncthing has issues with syncing SD card files, which is formatted as portable storage. One solution to that was to run the sync process as root, which can be set via Experimental subconfig option. My phone runs android 7.0 and I rooted the device earlier via Magisk. When I check the experimental option, syncthing is detected by Magisk and I grant the superuser access. Then weird things happen. 

When I restart syncthing, on the bottom of the phone's screen I see the message "syncthing was granted superuser rights", but  it looks like the sync process is stopped and my phone can connect to any device it syncs files to/from -- it simply says disconnected in the device tab. Basically, I'm unable to turn the sync on when the root access is granted. When I uncheck the experimental option, then everything backs to normal.

Also when the experimental option is checked, I often see lots of the "syncthing was granted superuser rights" messages on the bottom of the screen. 

Syncthing Version: 1.6.1
Syncthing-Android Version 1.6.1
Downloaded via F-Droid

**Comment by calmh** [comment]
Hi! This is unfortunately the wrong repository / issue tracker for your issue. Please file it in http://github.com/syncthing/syncthing-android/issues to get the correct attention.

**Comment by morfikov** [comment]
Oh, I see, thanks.
