### ISSUE TITLE
Use BIP39 to represent device IDs as a 24 word list

### ISSUE THREAD

**Issue by jpmikkers** [syncthing/syncthing#6765]
Passing a syncthing device id to someone by phone or written down on paper is cumbersome and error-prone. BIP39 can encode 256 bit keys into a list of 24 common, easy to communicate English (or optionally Chinese, French, Italian, Spanish, Korean, Japanese) words. The last word also acts as a checksum to catch any mistakes.

[simple explanation of BIP39](https://medium.com/coinmonks/mnemonic-generation-bip39-simply-explained-e9ac18db9477)

**Comment by AudriusButkevicius** [comment]
This is not bitcoin, and the ID is not secret, so I can't see why you'd want to write it down on a piece of paper.

Also 24 words is a lot of letters, presumably more than the 56 characters you need to write down for the ID itself.
The ID is already "mistake friendly", where 0 and O have no difference.

Honestly, I am failing to see a real use-case for this, "communicating via phone" and "writing down on paper" both sound hypothetical cases that I'd bet never actually happen.

Also, in a day and age that we are in now, I can't see "over the phone" being used as a medium to share anything to he be honest.

**Comment by imsodin** [comment]
I agree: I too fail to see a compelling use case. I consider a situation where you can only communicate by phone as so niche that it's fair to expect people in this situation to use a third-party tool for the job or much easier just use the age-old (well telephone-aged) technique of spelling alphabets - that's a useful skill for anyone (call me old-fashioned) and especially for people in need of frequent secret verbal communication :)
