### ISSUE TITLE
Base uri support for Web GUI

### ISSUE THREAD

**Issue by potato1992** [syncthing/syncthing#6772]
The web GUI currently can be accessed only by ip:port, it could be better if the base uri function is supported.
I use apache2 to ProxyPass some services that support base uri on my nas, like:

```
#base uri: /jellyfin
ProxyPass "/jellyfin" "http://localhost:8096/jellyfin"
ProxyPassReverse "/jellyfin" "http://localhost:8096/jellyfin

#base uri: /transmission
ProxyPass "/transmission" "http://localhost:9091/transmission"
ProxyPassReverse "/transmission" "http://localhost:9091/transmission"
```

Then my jellyfin and transmission server could be accessed via:
**https://IP(domain)/jellyfin
https://IP(domain)/transmission**

In this way, not only the uri is very user friendly. but also the ssl connection with the certificate can be centralized to be managed by apache2/Nginx.

Also, base uri is helpful when user want to open multiple instance of the software, and manage them in a graceful way, instead of memorizing tedious port numbers.

**Comment by imsodin** [comment]
That's a question of webserver setup, not Syncthing capabilities though, right? Basic info on apache reverse proxy setup is available at https://docs.syncthing.net/users/reverseproxy.html. For further questions, please open a topic on the forum. If there's something missing in Syncthing itself, an issue can be (re-)opened.
