### ISSUE TITLE
Minor Doc change suggestion

### ISSUE THREAD

**Issue by TekBear** [syncthing/syncthing#6781]
Documentation bug on https://docs.syncthing.net/users/faq.html#how-can-i-exclude-files-with-brackets-in-the-name 

change "special characters such as **[ and ?** are not allowed in file names on Windows"  to 
to     "special characters such as **?** are not allowed in file names on Windows"

**Comment by AudriusButkevicius** [comment]
Documentation is open-source, and live in it's own docs repo:

https://github.com/syncthing/docs

So feel free to make the change using online github editor and open a pull request.
