### ISSUE TITLE
Primary ("master") node for folder, auto-override any conflicts and problems

### ISSUE THREAD

**Issue by icec102** [syncthing/syncthing#6788]
### Sorry for wall-of-text. TL&DR: I want more forceful options to solving sync-issues automatically. For details, below. This is such a central and show-stopper-level issue for larger installations, that I felt the below WOT was motivated to highlight the problem thoroughly.
 

# Basic Problem
I repeatedly have to spend time on handling insignificant file sync problems. And I don't like wasting my time.

# Specific problem case
As a user, I very much would like to cleanup any problems in some very simple yet forceful way, where SyncThing knows my preference to always trust that a specific computer (the "Primary node" for the Folder) has the "correct" (as in "overriding") state of everything even slightly smelling like a problem of any shape and form. 

# Suggested solutions
SyncThing admittedly is outstanding at always respecting that data loss is to be avoided at any cost. That being said, this strictness comes with quite substantial issues in sync-networks with more than a couple of nodes, especially if Windows is involved (but otherwise as well). I can see two reasonably simple solutions to this problem:

1) Add the possibility to select a "Primary node" for each Folder. Further add the option to have the Primary node always override other node's index deviations, much like if the sysop would have built up all databases from scratch again, given the state of the Folder on each node, plus handling any Conflicts wi a policy like "Select Primary's version, keep non-Primay-nodes' versions as conflict backup files".

2) A "Re-sync" button in the Advanced menu. Since the feature already exist (Both as through REST and CLI) I presume it is deemed too dangerous/unreliable for even the Advanced menu. Maybe it is and maybe it isn't. But in reality, it is already an essential function, necessary to maintain a reasonably large sync-network over time, as it stands now. So maybe we then need and Advanced Advanced menu? (Or just trust that system administrators / users don't mess around randomly in an Advanced menu, given all the warnings that already exist...) Preferably, a Re-sync, triggered at a Folder's Primary node should propagate through the sync-network, to avoid wasting the sys-admin's time as far as possible. Actually, I consider avoid wasting time to be just as important as avoiding data loss! - And "shallow data loss", in the sense that the data can be left untouched in some conflict folder, or kept in file history at a receive-only server, is indeed less important to avoid compared to wasting both sys-admins' and users' time, from my standpoint. Syncing should never be considered a backup, and backup is both very common in reality and a reasonable assumption in theory.

# Note on Windows
For paths and filenames that Windows cannot handle, either resort to the Linux sub-system in Windows, or add some "Legacy Windows policy" like "Just ignore any Windows machines for any objects that are not compatible with Windows + show option to auto-rename such objects". Today, I have found no better option than running some 3rd party tool, like "Better Rename", on the entire folder tree, which takes forever (plus I have to constantly update the rules when I find additional problem-cases for Windows). I just want a big fat red button "Do whatever you can with the nodes you find and stop complaining over tens of thousands of negligible issues". **Or just let the Windows SyncThing client create a virtual volume (vhdx) that actually can cope with "normal" (as in Linux, Unix, MacOS, Synology-linux, etc) filenames and paths to circumvent the entire problem area once and for all.**

# Rejected work-arounds
* Receive-only folders: Nope, the underlying assumption frequently does not hold, unfortunately. Both directions are of essence.
* Rebuilding the database / index: As it currently stands, this is the best work-around, but it is very time-consuming, and has to be done on all nodes individually, and preferably at the same time. Very heavy-weight solution for this kind of problem IMHO, and not practical where rarely-connected nodes exist.
* Conflict resolution: Most of the time, it is actually NOT about Conflicts, per se. It is rather some mismatches where files are deleted, covered by ignore rules, having too long paths/invalid filenames for Windows-based nodes, having permission issues, residing on unavailable nodes of low significance, etc.

**Comment by AudriusButkevicius** [comment]
So I see a bunch of proposed solutions, but really not a description of a concrete problem. "I spend time on sync problems" is not a really good problem description.

Syncthing is decentralised and data loss preventing, so I think "primary blast on top of everyones data" and always-override is definately off the table as these are.

Also, it seems you are after sort of "here is the data, everyone must have an copy" model, for which syncthing is not really a great tool.

I feel this is better suited for the forum atleast until it's clear what problems we're solving here and checking whether we agree that this is something we want to solve in general.

Also: https://docs.syncthing.net/users/faq.html#is-it-syncthing-syncthing-or-syncthing

**Comment by icec102** [comment]
**Clarification on the concrete problem:** 

SyncThing tends to accumulate sync-issues with files over time. There is no simple way of resetting this, afaik. Like I concluded above:

_"Rebuilding the database / index: As it currently stands, this is the best work-around, but it is very time-consuming, and has to be done on all nodes individually, and preferably at the same time. Very heavy-weight solution for this kind of problem IMHO, and not practical where rarely-connected nodes exist."_

I consider this to be a quite concrete problem. The proposed solutions are just ideas, feel free to address the problem in other ways. SyncThing is a great tool, which is applied to many different use-cases. Sometimes overriding makes sense, sometimes it does not. Hence my suggestion of making such features optional.

**Comment by calmh** [comment]
You should clarify what these sync issues are, and why auto override would help. If the sync issues are because syncthing can't sync something it will also be unable to override it.

**Comment by AudriusButkevicius** [comment]
I still feel the best place for this is on the forum at this stage, given lack of clarity.

Also, please check out the link I posted  as the last sentence in my initial reply.
