### ISSUE TITLE
0.9.15 Sync progress can still show negative percentages

### ISSUE THREAD

**Issue by bigbear2nd** [syncthing/syncthing#679]
Continued from #592 (Do you normally make an new issue or use the old one? I cannot reopen the old one..)

BlackDS: 0.9.15 linux-386 default
BigBear: 0.9.15 Windows 7 64 bit
During the initial sending of the index:
![during_sending_index3](https://cloud.githubusercontent.com/assets/7719800/4250044/139c68d4-3a7f-11e4-92cb-3d4f83f8d7f3.PNG)
Please also note the 235 % of CPU percentage. Is this normal?
Fine for me is the consumed RAM. 
Also the Windows side: there the 50% Sync Progress seems funny, one Repo 380 Kilobyte, the other 380 Gigabyte.. Still at 50%.. I guess this is by design.
![during_sending_index2](https://cloud.githubusercontent.com/assets/7719800/4250091/b5e58062-3a7f-11e4-894a-cefbdcf4cbcb.PNG)

**Comment by calmh** [comment]
Dup #1567

(letting the newer one live as a lot of water has passed under this bridge and the root cause may have changed)
