### ISSUE TITLE
"gzip: invalid header" error when upgrading to v1.6.1

### ISSUE THREAD

**Issue by Vinz87** [syncthing/syncthing#6792]
I'm on v1.3.0 on macOS High Sierra, Safari v13.0.2, when I click on the button Upgrade to v1.6.1 it shows the error message "gzip: invalid header".

**Comment by AudriusButkevicius** [comment]
Please search for existing issues before opening new ones

Dup of https://github.com/syncthing/syncthing/issues/6771

**Comment by calmh** [comment]
Since it's not mentioned in that issue specifically, the upgrade format for Mac changed due to notarization, and you need 1.3.4+ to understand it. You need to upgrade manually, once.

**Comment by Vinz87** [comment]
> Please search for existing issues before opening new ones
> 
> Dup of #6771

That issue mentions the installation through homebrew, which is not this case, and the solutions mentions to retry installing through homebrew, so I don't agree it's a duplicate. 
That issue is also closed, with a solution which fits for me, since I didn't use homebrew.
Moreover, I provide details my current version for reference in replicating the issue.

**Comment by Vinz87** [comment]
> Since it's not mentioned in that issue specifically, the upgrade format for Mac changed due to notarization, and you need 1.3.4+ to understand it. You need to upgrade manually, once.

Thanks, I'll try this solution.

**Comment by Vinz87** [comment]
> > Since it's not mentioned in that issue specifically, the upgrade format for Mac changed due to notarization, and you need 1.3.4+ to understand it. You need to upgrade manually, once.
> 
> Thanks @calmh, I'll try this solution. When upgrading manually, can I upgrade directly to 1.6.1 or should I upgrade specifically to 1.3.4 before?

Ok, I can confirm the solution is to manually upgrade to last version, in my case I directly replaced the old version binary with the one corresponding to v1.6.1.
