### ISSUE TITLE
Error status should take precedence over Local Additions

### ISSUE THREAD

**Issue by kbtombul** [syncthing/syncthing#6793]
I have a Receive Only folder that is the mount path of an encfs volume. When I reboot my device, I don't automatically mount them so I expectedly get "folder path missing" error. However, when I have local changes, that's the status I see. I believe the failure status ("Stopped" if I remember correctly) should be displayed instead of "Local Additions".

Steps to reproduce:
- Create a Receive Only folder
- Make local changes and wait for "Local Additions" to be displayed in the web UI.
- Delete the folder completely
- Restart Syncthing
- Observe that the folder status still shows as "Local Additions" and the error "folder path missing" is displayed in the folder details.

<img width="566" alt="Screen Shot 2020-06-24 at 1 26 02 PM" src="https://user-images.githubusercontent.com/732128/85624675-20dfca00-b61f-11ea-8be0-7476e57f0999.png">

Syncthing v1.6.1
macOS 11.0 (Big Sur) Beta

**Comment by KarthikNayak** [comment]
I tried to reproduce this issue, but I got `Stopped` which is the desired behavior in this case.

**Comment by imsodin** [comment]
I can't repro either - feel free to reopen if you still encounter this issue.

**Comment by imsodin** [comment]
Actually that closure was too rushed: I just discovered the same issue (just with send-receive folders/out-of-sync status) doing unrelated tests. The bug is in the model though, not the UI, and a bit elusive (requires pulling). Fix incoming.
