### ISSUE TITLE
Transferring many small files potential improvement

### ISSUE THREAD

**Issue by mxKaZVN** [syncthing/syncthing#6806]
I love this program and had some annoyances with transfer speeds with many small files. I had a light bulb idea occur to me. I don't know if it is exactly viable but the process goes like such:

device1 has many thousand small files that need to transfer to device(s)
device1 already knows which files need to sync to which device
it takes that list and performs a .tar operation on device1 with these small files, sending the .tar data over network in real time where
device2 receives the data and untars as it is received

With this the thought process is:
no .tar file needs to be made on device(s) disk
file sizes ranging to a few MiB are eligible
a big sequential transfer is sent

If and when a connection is cut off:
whatever progress is made with syncing would be faster than how it is implemented now
a full .tar operation on device1 would not be necessary when timed out
begin the cycle again, rinse, repeat

How good of an idea it may be is up to you. IDK, I just got here. :)

**Comment by AudriusButkevicius** [comment]
The slowness comes from having to fsync each file individually, which is 100s of milliseconds up to seconds on some filesystems.
You'd still have to do that after you untar'ed your archive, still incurring the same cost, so this would not help.
