### ISSUE TITLE
no connected device has the required version of this file

### ISSUE THREAD

**Issue by Zehelein** [syncthing/syncthing#6818]
### Does your log mention database corruption?

If your Syncthing log reports panics because of database corruption it is
most likely a fault with your system's storage or memory. Affected log
entries will contain lines starting with `panic: leveldb`. You will need to
delete the index database to clear this, by running `syncthing
-reset-database`.

### Include required information

which version of Syncthing and what operating system you are using
> Windows 10, SyncTrayzor 1.1.24, Syncthing 1.7.0

what happened,
> One file cannot be synchronized since > 2 month, it always shows that there is no device with that version of the file available

what you expected to happen instead
> I would expect that this error gets resolved automatically. Or if I create another copy of that file, edit it so it is newer it would use that file instead. Or any other way to resolve the issue. I am fine with deleting the file or anything. But I want to get rid of that error.

### Logs

```
[LIHPP] 07:58:53 INFO: Ready to synchronize "CG Sync" (hk5uf-khv2n) (sendreceive)
[LIHPP] 07:58:53 INFO: Completed initial scan of sendreceive folder "CG Sync" (hk5uf-khv2n)
[LIHPP] 07:58:53 INFO: Puller (folder "CG Sync" (hk5uf-khv2n), item "Protokolle\\2020\\Protokoll 2020-04-27.docx"): no connected device has the required version of this file
[LIHPP] 07:58:53 INFO: "CG Sync" (hk5uf-khv2n): Failed to sync 1 items
[LIHPP] 07:58:53 INFO: Folder "CG Sync" (hk5uf-khv2n) isn't making sync progress - retrying in 1m0s.
[LIHPP] 07:58:53 INFO: "CG Sync" (hk5uf-khv2n): Failed to sync 1 items
[LIHPP] 07:58:53 INFO: Folder "CG Sync" (hk5uf-khv2n) isn't making sync progress - retrying in 1m0s.
...
```

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
