### ISSUE TITLE
Cannot view versions if the versions folder contains alien, forbidden folder

### ISSUE THREAD

**Issue by mythsmith** [syncthing/syncthing#6819]
Syncthing version: 1.7.0.

OS: Ubuntu 18.04

Steps to reproduce:

1. Create empty folders A, B
2. Add to syncthing folder A, specifying staggered versioning and versioning destination folder B
3. If you click on the newly created folder Versions button, it correctly says "No data".
4. Create folder B/no_access, and, within this folder, create file B/no_access/do_not_delete
5. Set read-only and no execution o on both file and folder chmod -R 444 B/no_access
6. Versioner spits the error: 
``` 
2020-07-08 11:23:07: Versioner: error scanning versions dir lstat .../B/no_access/do_not_delete: permission denied 
```
7. Clicking on Versions button now prints "Loading data..." and nothing more.
8. If you change the B/no_access permissions to 555, everything works as expected.

The issue seems to solve itself by simply giving 555 to the no_access folder. I see not technical reason to require all subfolders of a versioning destination to be accessible to the syncthing process.

# Why do I expect this to work? 

Syncthing does versioning only for changes it receives from remote parties, but it has no way to properly do versioning on local files. if you activate versioning on one of the remote devices, versions will be safe on that remote storage. But to restore a version stored remotely, you should have some other means of connecting to the remote machine. The local syncthing instance does not allow any way of browsing and retrieving versions which are stored remotely.

So I came to the following solution, which allows to locally share versions which are produced remotely:

1. Local shares local/A with remote, SendOnly
2. Remote receives A in remote/A, ReceiveOnly, and stores versions in remote/B
3. Remote shares remote/B with local, SendOnly
4. Local receives remote/B in local/B, ReceiveOnly
5. Local specifies that the versions folder for local/A is local/B

This way, local can directly access to remote versions through the same syncthing interface, because they are shared back in local/B. In case of extreme damage, like crypto attack, you can always rever all local versions

The problem is the .stfolder marker. remote/B and local/B have dual meaning: they both are used as versioning destinations AND they are shared back with the other device. 

So they must have an .stfolder: something the Versioner does not expect. Infact, it will soon delete the .stfolder marker and this will in turn stop the sharing.

So I came to this solution: I protect the .stfolder by creating a read-only file inside of it, and making read-only also the folder. As this bug report discovered, the folder must be accessible (x). I hope alien folders/files will not stop the Versioner in the future.

**Comment by calmh** [comment]
I think .stversions is a Syncthing-internal structure and it's reasonable for Syncthing to expect to be able to access and manage the files therein.

A better solution to your problem might be to set the folder marker name to something custom.

**Comment by mythsmith** [comment]
> I think .stversions is a Syncthing-internal structure and it's reasonable for Syncthing to expect to be able to access and manage the files therein.
> 
> A better solution to your problem might be to set the folder marker name to something custom.

The folder marker name does not matter. The problem resides in the Versioner. If you set a folder as versions destination, then create an non-accessible and non-deletable folder within that, with *any* name, the Versioner will crash. In my example, that folder was named no_access.

**Comment by calmh** [comment]
Yes, I understand that. See my addition above.

> and/or use some script to keep the marker fresh, or disable automatic cleaning of the versions dir...

Or perhaps we need to find another solutions. But creating unreadable things in a space Syncthing expects to manage is not the proper solution.

**Comment by calmh** [comment]
Or if you insist, set the marker name to `.`. That should make it happy enough with the existence of the folder itself, not requiring a marker at all.

**Comment by AudriusButkevicius** [comment]
Yeah, I don't think we want to support readable things in our versions directory. It's our directory and we should be expected to have all control of it.

**Comment by mythsmith** [comment]
> Or if you insist, set the marker name to `.`. That should make it happy enough with the existence of the folder itself, not requiring a marker at all.

This is an excellent solution! I didn't expect '.' to be supported as a marker name, as it makes it totally useless. 

Out of curiosity, isn't it a little bit in contrast with the policy here exposed by @AudriusButkevicius, setting the marker name to something that cannot mark anything by definition?

**Comment by AudriusButkevicius** [comment]
Obviously it's not recommended, but given you're off piste syncing .stversions directories, I can't stop you from doing whatever you want.

Are we happy to close this given you have a workaround?

**Comment by calmh** [comment]
Yeah the dot is not so much a supported intended thing but just a consequence of being something that works when you give it to stat(). But it seems like a useful enough escape hatch that it can stay now that it’s known.
