### ISSUE TITLE
syncthing 1.6.1 -> 1.7.0 fails on "failed validating data"

### ISSUE THREAD

**Issue by andaag** [syncthing/syncthing#6827]
### Include required information

1.7.0 on both machines. Ubuntu 20.04. ZFS filesystem.

Keeps looping on trying to transfer a lot of (seemingly) random files. I've tried resetting databases on both sides, and neither helped.

If I grep on one failing file I can find a lot of these errors:
```
[EX3KG] 2020/07/10 22:40:35.363987 model.go:1526: DEBUG: model@0xc000500c00 REQ(in) failed validating data (<nil>): DEVICE_ID: "py2zx-sydjy" / ".kube/bin/kubectl-1.13.0" o=19791872 s=131072
[EX3KG] 2020/07/10 22:40:35.364247 model.go:1599: DEBUG: model@0xc000500c00 recheckFile: DEVICE_ID: "py2zx-sydjy" / ".kube/bin/kubectl-1.13.0"
[EX3KG] 2020/07/10 22:40:35.364309 model.go:1526: DEBUG: model@0xc000500c00 REQ(in) failed validating data (<nil>): DEVICE_ID: "py2zx-sydjy" / ".kube/bin/kubectl-1.13.0" o=19267584 s=131072
[EX3KG] 2020/07/10 22:40:35.364384 model.go:1599: DEBUG: model@0xc000500c00 recheckFile: DEVICE_ID: "py2zx-sydjy" / ".kube/bin/kubectl-1.13.0"
```

Sometimes these also show up in the log:

```
[EX3KG] 2020/07/10 22:40:31.469657 model.go:1453: DEBUG: model@0xc000500c00 REQ(in): DEVICE_ID: "py2zx-sydjy" / ".kube/bin/kubectl-1.13.0" o=19922944 s=131072 t=false
[EX3KG] 2020/07/10 22:40:31.469722 model.go:1453: DEBUG: model@0xc000500c00 REQ(in): DEVICE_ID: "py2zx-sydjy" / ".kube/bin/kubectl-1.13.0" o=20316160 s=131072 t=false
[EX3KG] 2020/07/10 22:40:31.469801 model.go:1453: DEBUG: model@0xc000500c00 REQ(in): DEVICE_IDF: "py2zx-sydjy" / ".kube/bin/kubectl-1.13.0" o=19529728 s=131072 t=false
```

I have a full debug log that I can send to someone in private if needed, but I'm not sure how safe it is to link all the debug info on github?

**Comment by calmh** [comment]
I suspect you're bitten by having old weak hashes and an inadvertent strictening of that check in a recent PR.

**Comment by xpavp03** [comment]
Touching the files didn't work for me. Is there something else I can try?

I'm getting `failed validating data` and endless `recheckFile` for files added very recently - last changes actually before auto-upgrade to 1.7.0. These files were not synced with other machines before the upgrade and now when any of them connects, the owning machine goes into a `recheckFile` loop.

**Comment by calmh** [comment]
Try the latest nightly or proposed hot fix at https://forum.syncthing.net/t/pull-no-such-file/15255/12

**Comment by xpavp03** [comment]
Replacing the owning machine's syncthing with 1.7.1 helped. Thank you!

(It did not help to move the offending folders out and then back after rescan with paused other boxes.)
