### ISSUE TITLE
v1.7.1 release note fetchable at same location as previous releases

### ISSUE THREAD

**Issue by swills** [syncthing/syncthing#6831]
Hi,

Previous releases were fetchable at https://github.com/syncthing/syncthing/releases/download/, but the v1.7.1 is not. Is this expected?

Thanks!

**Comment by AudriusButkevicius** [comment]
There is no 1.7.1

**Comment by swills** [comment]
GitHub seems to think there is:

https://i.imgur.com/snaDBWJ.png

**Comment by swills** [comment]
I guess I'm confused, sorry for the noise.

**Comment by AudriusButkevicius** [comment]
It's a draft tag that has not been published.

**Comment by swills** [comment]
Again, sorry for the noise. I think I was confused because a number of projects have picked it up as a "release" already:

https://repology.org/project/syncthing/versions

(At the moment, Alpine, KISS, MacPorts and Solus). Anyway, thanks for the explanation.
