### ISSUE TITLE
Support running syncthing Docker image as non-root user

### ISSUE THREAD

**Issue by HansK-p** [syncthing/syncthing#6832]
### Include required information

The generated Docker image doesn't allow running the the image as a non-root user. Running as a non-root user is useful as it reduces permission given to the container when eg running in Kubernetes. This will reduce the attack surface.

Currently I'm rewriting /bin/entrypoint.sh as a workaround for this issue, but it would be good if such a local workaround weren't needed.

What currently happens:
<pre>
$ docker run -p 8384:8384 -p 22000:22000 \
>   -v "$(pwd)/data":/var/syncthing \
>   --user 1000:1000 \
>   syncthing/syncthing:latest
su-exec: setgroups(1000): Operation not permitted
</pre>

**Comment by calmh** [comment]
Maybe have the entrypoint script skip the operations in question when running as non-root, assuming that everything is already correctly set up (as there is anyway not much to do about it).
