### ISSUE TITLE
Docker README link broken in main README and DockerHub

### ISSUE THREAD

**Issue by JoeHitchen** [syncthing/syncthing#6833]
Link points to: https://github.com/syncthing/syncthing/blob/master/README-Docker.md
Correct link now appears to be: https://github.com/syncthing/syncthing/blob/main/README-Docker.md
`master` -> `main`

**Comment by calmh** [comment]
The link is correct in our README. I expect Docker hub is just not updating very frequently.

**Comment by calmh** [comment]
Yeah, Docker hub takes the readme from the latest build, and that tag currently precedes the change. So it will resolve once newer releases happen.

**Comment by JoeHitchen** [comment]
I had missed that the link was actually corrected in the repository. My bad!
