### ISSUE TITLE
The Docker hub documentation points to a non-existing README-docker.md file

### ISSUE THREAD

**Issue by HansK-p** [syncthing/syncthing#6836]
The Docker hub documentation found at https://hub.docker.com/r/syncthing/syncthing points to https://github.com/syncthing/syncthing/blob/master/README-Docker.md and not https://github.com/syncthing/syncthing/blob/main/README-Docker.md.

Search for "To run Syncthing in Docker, see the Docker README" on the page in order to find the incorrect link.

**Comment by calmh** [comment]
I had this discussion literally 17 minutes ago #6833
