### ISSUE TITLE
Keep modification time

### ISSUE THREAD

**Issue by Avamander** [syncthing/syncthing#6839]
I only use systems that store modification date in file metadata, the modification time information has been incredibly useful for me numerous and numerous times.

Could it be added that modification times are (optionally) kept when syncing?

**Comment by calmh** [comment]
File mtimes are always synced unless you specifically disable it. So unclear what you're asking for?

**Comment by Avamander** [comment]
Folder mtimes don't seem to be synced, are they?

**Comment by AudriusButkevicius** [comment]
They are not, and I don't think we have any plans, because different filesystems/operating systems handle them vastly differently, and it's a complete can of worms trying to support it.

**Comment by Avamander** [comment]
I'm sure there's always a filesystem that doesn't support any specific feature even relatively modern you can think of, but I don't think everyone should be forced to live only on the feature set of FAT16. This is why I asked for an optional flag, for those platforms where this is not really an issue.

**Comment by AudriusButkevicius** [comment]
It's not about what's supported, it's about the behaviours, some filesystems update mtime of parent directory if you update mtime of child directory, some don't, at which point the implementation for handling this becomes absurd.

**Comment by AudriusButkevicius** [comment]
If you feel strongly about this, feel free to propose a PR addressing this.

**Comment by Avamander** [comment]
> some filesystems update mtime of parent directory if you update mtime of child directory, some don't

Update mtime on only those filesystems that don't do that? Alternatively update mtime as the last step, from top to bottom of the FS tree?

**Comment by AudriusButkevicius** [comment]
We don't know which filesystems do that which ones don't, we don't have file system behaviour specific code, and I don't think we want to have it.

Yes, there are ways around it, as you rightfully suggested, same way there are ways around following symlinks, syncing ownership, syncing extended attributes, syncing ACLs and other "can of worms" features, but I don't think it's a priority for us.

**Comment by Avamander** [comment]
> I don't think we want to have it.

Yeah, too bad this is like the fourth feature now for which I miss in Syncthing but is considered a can of worms. :D

Hopefully at some point this is reconsidered.

**Comment by AudriusButkevicius** [comment]
Don't get me wrong, I think we'd accept a well thought through PR implementing this.

**Comment by calmh** [comment]
Not syncing directory mtimes has been a documented issue since at least the last five years. We used to do it way back, but as Audrius explains it's technically tricky and *almost* nobody cares (including us maintainers). So we do don't do it. Though if someone who cares deeply about it contributes a patch that solves it nicely in a general way for everyone, I'm sure it would be accepted.

**Comment by calmh** [comment]
> Yeah, too bad this is like the fourth feature now for which I miss in Syncthing but is considered a "can of worms". :D

Well, we've been around for a few years and have implemented most of the easy ones. :) The ones remaining are often things we are philosophically opposed to or things which are genuinely tricky to get right.
