### ISSUE TITLE
Bandwidth limits do not work

### ISSUE THREAD

**Issue by hjri** [syncthing/syncthing#6840]
### Does your log mention database corruption?

If your Syncthing log reports panics because of database corruption it is
most likely a fault with your system's storage or memory. Affected log
entries will contain lines starting with `panic: leveldb`. You will need to
delete the index database to clear this, by running `syncthing
-reset-database`.

### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using `v1.1.4-ds1, Linux (64 bit)`
 - browser and version, if applicable
 - what happened, 
![image](https://user-images.githubusercontent.com/3514245/87863174-1506cf80-c961-11ea-9ebb-638f9ecdb168.png)

 - what you expected to happen instead, and **speed limits actually working**
 - any steps to reproduce the problem. **set up syncthing, set bandwidth limits, sync two device up. see speed go through the roof, experience network congestion and router/switch crashing**

**Comment by AudriusButkevicius** [comment]
Limits are not applied to connections that are deemed local network, unless you enable a flag in advanced settings, furthermore, limits are limits over some time (can't remember what it is), so it's perfectly possible that it spikes above the limit briefly.
