### ISSUE TITLE
Don't fail dirs in receive-only folders that were removed elsewhere but exist locally

### ISSUE THREAD

**Issue by nivranaitsirhc** [syncthing/syncthing#6873]
I have this scenario where I backup my pictures on my android to my PC. 
I have a "Send Only" folder on my android and "Receive Only" on my Desktop with file versioning enabled. Once a week/month I restore the deleted files (pictures) on my PC marking it as a local changes, and this is fine.

When a folder is deleted on my android I get this error "directory has been deleted on a remote device but contains locally changed files" which is fine for logging purposes but logical I think this should not be a major error.

From what I understand a "Receive Only" folder can have more file than the source but not less than.

**Comment by AudriusButkevicius** [comment]
It's not clear what warning you are talking about, but the idea is that folders should look identical on both sides, if they don't they are out of sync.


Deleting files on one side and expecting them not to be deleted on the other is not really syncing, it's more like file transfer which is not a scenario syncthing is made for.

Also, how did you manage to open an issue with no labels?

**Comment by imsodin** [comment]
I think the issue is that receive only items aren't synced, thus the remote can delete the directory containing the receive only files without touching them. it seems reasonable to mark the deleted dir containing receive only items as receive only item too instead of gaining to sync/delete it.

**Comment by nivranaitsirhc** [comment]
> 
> 
> It's not clear what warning you are talking about, but the idea is that folders should look identical on both sides, if they don't they are out of sync.
> 
> Deleting files on one side and expecting them not to be deleted on the other is not really syncing, it's more like file transfer which is not a scenario syncthing is made for.

The warning is in the title "Out of Sync" on the receive only folders. Let say my android is the remote and has folder set to **Send Only** and my on my PC has a clone of that folder set **Receive Only**. My setup is to clone a folder from the remote but retains the files deleted on the remote by restoring using the "Staggered File Versioning".

Now when a file is deleted on the remote but restored on the clone, It will appear as a "Local Changes" on the clone, but when a folder is deleted on the remote that contains file and restored on the clone, syncthing throws an "Out of Sync" warning.

> 
> Also, how did you manage to open an issue with no labels?

I was actually looking for that when I was opening this issue but github has been changing for me lately.

**Comment by nivranaitsirhc** [comment]
> 
> 
> I think the issue is that receive only items aren't synced, thus the remote can delete the directory containing the receive only files without touching them. it seems reasonable to mark the deleted dir containing receive only items as receive only item too instead of gaining to sync/delete it.

So this why the "Out of Sync" is thrown out on the "Receive Only" folders.

I would suggest a feature to be added to "Receive Only" folders, "Read-Only/Add-Only" sub-option to "Receive Only" Folders as this way folder/files can be modified if it exist but can never be deleted if it exist on the remote. Is this feasible or I am asking too much.

**Comment by AudriusButkevicius** [comment]
Sorry, but what you are describing is working as intended. If you restore files into a receive only folder, it will become out of sync, as it does not match what send only advertises.

What you are looking for is basic file transfer from A to B, where you can do whatever you want on B. Syncthing is not a tool that supports this sort of scenario.

**Comment by imsodin** [comment]
What's wrong with

> it seems reasonable to mark the deleted dir containing receive only items as receive only item too instead of gaining to sync/delete it.

**Comment by nivranaitsirhc** [comment]
I use syncthing for a lot of use case scenario and very grateful, it just happens that this automated "simple file transfer" (sync update) scenario would not be feasible and I would have to rely on another software to do this task.

I understand the core concept of syncthing is to sync files between locations and not all asked could be given, but I don't understand the scenario when you explicitly tell your application that you want to retain a folder with files locally on a "Received Only" config only to be told that you are out of sync because the sever has lost its copy. I am not saying its broken, I am just presenting a scenario where it exist and its annoying to get this warning all over the place.

Anyway I am only suggesting to have an config option to make this an exception to ignore this warning or to have this reconsidered and apply in core algorithm. 

As this is not feasible I would be just glad using sycnthing the way it is.
