### ISSUE TITLE
chmod permission after editing .stignore via WebUI not preserved

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing#6886]
Ref.: https://forum.syncthing.net/t/preserve-chmod-permission-after-editing-stignore-via-webui/15461

Reproducer:

chmod 0755 /path/to/folder/.stignore
Edit ignore patterns for “folder” from Syncthing’s Web UI
Syncthing always resets permission to 0600

What I like to suggest:

Keep the file permission if the user changed it. e.g. 0755 in my case.

Thank you.

Affects: all Syncthing versions since years (0.14.x ... current)

> imsodin
That might even qualify as a bug: Our atomic writer simply doesn’t care about permissions of the final product. In any case please file an issue on github

**Comment by imsodin** [comment]
Shut, I was too fast on the clickediclick on merging #6886: Final commit msg came from the commit message with "fixes #tbd" instead of the PR title...
