### ISSUE TITLE
Wrong SHA256  in sha1sum.txt.asc for currently latest version

### ISSUE THREAD

**Issue by Kyliathy** [syncthing/syncthing#6890]
Hello :). There's a mismatch between reported SHA 256 hashes for the latest release.

syncthing-windows-amd64-v1.8.0.zip

CertUtil -hashfile syncthing-windows-amd64-v1.8.0.zip SHA256
SHA256 hash of syncthing-windows-amd64-v1.8.0.zip:
cff900b5d2b0e70fd74e8180bcbc29a955b1ef55cbbd2737cd8e313231d0f484

Whereas your .asc file reports:

3242df1606972f1f5892d28200775a87ffaa31b9  syncthing-windows-amd64-v1.8.0.zip

**Comment by calmh** [comment]
You are comparing SHA256 hashes with SHA1 hashes. sha1sum.txt contains SHA1 hashes, sha256sum.txt contains SHA256 hashes.

**Comment by Kyliathy** [comment]
Whoops :(. Sorry.
