### ISSUE TITLE
Syncthing 1.8.0 trying to connect via wrong network route

### ISSUE THREAD

**Issue by stloewen** [syncthing/syncthing#6892]
Related forum thread with details: https://forum.syncthing.net/t/syncthing-trying-to-connect-via-wrong-network-route/15476

Affected: Syncthing 1.8.0

Summary:
Syncthing explicitly specifies the source-IP when connecting to a remote device which ignores the routes configured in the operating system and can lead to problems connecting. Syncthing v.1.7.1 works fine in the same configuration.

**Comment by calmh** [comment]
@AudriusButkevicius can you explain what the technical problem is? I don't understand why doing a dial from something bound to `0.0.0.0:22000` would act differently than a dial from an unbound socket.

**Comment by AudriusButkevicius** [comment]
I think it gets bound to interface which is the default gateway, as I think we "resolve" the unspecified address as we bind to it.

Also, people might specify a specific bind address.
