### ISSUE TITLE
Modification dates are wrong

### ISSUE THREAD

**Issue by anthonym01** [syncthing/syncthing#6897]
![Annotation 2020-08-15 175701](https://user-images.githubusercontent.com/57382365/90322994-c5e09a00-df20-11ea-90e1-5119e96eb28b.png)
Syncing between windows and linux, makes dates go co-co loko

**Comment by AudriusButkevicius** [comment]
We don't make up dates, we just copy what we've observed on the other side, and for files only, we do not sync mtimes for directories.

If you have any further questions or want to debug this, please open a thread on the forum, as am almost 100% certain it's not our bug.

**Comment by jamisonfcc** [comment]
The same thing is happening to me.  Random files are being given random future modification dates.  I have gone as far as removing all my devices but three, and all my folders but one.  I have removed a folder from the synced folder, fixed modification dates, waited until all devices are synced, put it back into the synced folder, and the dates will change to future dates.
