### ISSUE TITLE
Marker folder convenience improvement

### ISSUE THREAD

**Issue by HaujetZhao** [syncthing/syncthing#6903]
### Problem

Syncthing uses a **marker folder** to detect whether the synced folder is mounted correctly. The default **marker folder** name is **.stfolder**, and the newly created **marker folder** is hidden by default, ideally non-tech users won't see this **marker folder**. It is changeable in **Advanced** page: 

![image](https://user-images.githubusercontent.com/19181833/90595286-0f7dfd00-e21f-11ea-8365-f30e5e714755.png)

New users (even some amateur tech guys) usually don't know about the **marker folder** behavior, cause they've never seen such a name during adding and setting a sync folder, so they may not pay any attention to the **.stfolder**. 

After some accidently operation, such as a cleaning (especially non-tech users love cleaning using some cleaning softwares which delete empty folders by default), a script, the **.stfolder** might be deleted, and these users will come to ask the same, simple, stupid question: **My folder marker is missing, the syncthing stopped syncing, how do I do? Why syncthing need a .stfolder? I hate the .stfolder, can I delete it? ......** 

The reality is, few users really read the FAQ or search the same question before asking for help. Only a few users know they could change **marker folder** in advanced setting in WEB UI. 

### Solution

To decrease the possibility of meeting the problem described above, I propose 2 solution: 

1. add an option to the **Settings** panel: the file versioning is enabled, set the **folder marker** to be same as **versions path**, which is **.stversions**. And make the option on by default.

2. add an option to change the **marker folder** to the  **Advanced** tab in **Add Folder** dialog. Instead of only put it in **Advanced** setting page because it's too deep to open.

By doing so, users at least could have a glance at some information about **marker folder** while they config the syncfolder settings. 

And by setting the **marker folder** to the **versions path** when it's on could reduce the possibility the **marker folder** being deleted accidently. 

The whole idea is to reduce the chance that users get confused by **missing marker folder** and then asking the repeated question. That's all.

**Comment by AudriusButkevicius** [comment]
Sorry, but no.

We have a ticket to rename the folder and I think thats enough. People who delete what they don't understand are asking for trouble anyway.
