### ISSUE TITLE
NAT service fails to terminate during Shutdown

### ISSUE THREAD

**Issue by pop9119** [syncthing/syncthing#6908]
Since version 1.8.0, when-ever a device is told to shutdown syncthing, the process hangs for a bit and the log file prints out:

INFO: connections.Service: Service nat.Service@0xc000184600 failed to terminate in a timely manner.

Based on the logfiles, this takes about 9 secs to timeout. Aside from this slowing down the shutdown process, I am concerned with that service even running since I have NAT transversal disabled on all my syncthing devices. Perhaps this is likely a leftover bug from the 1.7 branch where the process was running even if not configured to.

I have this issue confirmed in Win7,10 & Linux, all running 1.8.0.

**Comment by AudriusButkevicius** [comment]
The service runs regardless if it's enabled or not, the enablement decides if the service does something or not.

I can't really see on the surface what would cause this.
Is this reliably reproducible for you?

**Comment by pop9119** [comment]
Yes it is reliably reproducible in that this happens 100% of time even if freshly installed system. I just checked and I don't get the error if I have NAT transveral enabled. (In that a shutdown of syncthing happens with no failure to terminate the nat.Service)

So the error only happens if NAT transveral is not enabled.

**Comment by imsodin** [comment]
I can reproduce, looking into it.
