### ISSUE TITLE
[Feature] Add button to backup/restore the config in parameter

### ISSUE THREAD

**Issue by borrougagnou** [syncthing/syncthing#6916]
### Include required information

Please be sure to include at least:

 - what problem your new feature would solve
Improve possibility to backup/restore config file after format in any device  (with compression folder)
(with maybe a big warning message if someone use the same config file in multiple device) +
(maybe with the choice of merging existent config or erase all config)

 - how or why you think it is generally useful (i.e., not just for you)
nobody need to know where they can found their syncthing config folder and don't know what file they need to backup

 - what alternatives or workarounds you considered
actually IDK, I tried to copy all the syncthing folder until the new destination but now I have  unable to connect to syncthing ...,
I found the solution in Syncthing forum about backup the  config file (and key/pem) but... I don't think it's the only thing I need to backup... + solution is for Linux, not Windows/Mac/Android/...

**Comment by AudriusButkevicius** [comment]
People use different backup solutions, which files need to be backed up is probably not well documented, but the backup itself needs to be specific to the users backup solution so I don't think we can have a generic backup solution.

We do backup configs as we migrate them, but that's for the purpose of being able to restore it if we screw up royally, not if the user screws up.
