### ISSUE TITLE
Reconsider db check on upgrade

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#6917]
It used to be quite quick and painless; seconds on my computer. Now up to about five minutes on my computer. Other setups are worse:

```
<sphalerite> Is there any way to make "Checking db due to upgrade" faster? It takes hours on my phone.
```

I think it's the block loading that now happens...

**Comment by imsodin** [comment]
I do believe it's been painfully slow even before loading blocks - checking all the global entries is terribly slow in itself. Until now there's not a single "device present in global..." panic in v1.9.0, so I am hopeful https://github.com/syncthing/syncthing/pull/6888 fixed that for good. Unconditionally repairing sequences feels unnecessary anyway, as when sequence problems do occur, we detect and fix those (only if necessary) both when loading the db and when sending indexes. Given weird metadata issues popping up all the time I'd keep the meta recalculation on upgrade for now.
