### ISSUE TITLE
UTF-8 filename conflicts when syncing from Windows NTFS

### ISSUE THREAD

**Issue by gamma** [syncthing/syncthing#6929]
- Syncthing v1.9.0 RC4
 - Windows Server 2019

Just as in #4649 I'm having erroneous files that are not being synced due to filename encoding issues. The filenames are literally like `%20äöü ÄÖÜ ß€#-%-&nbsp;.rpt.csv` - the same files exist on ext4.

The error is: `item has UTF8 encoding conflict with another item`. I hoped the merged code for the ZFS may fix this too, but it did not.

**Comment by AudriusButkevicius** [comment]
I don't think we can do much here, it seems the encoding on the filesystems are genuinely different, because I assume the files were there before syncthing was involved (as in, syncthing did not sync/create the files, they were there already there or pre-synced using something else).

Effectively, there is no way we can fix this because it's two separate files from our point of view that conflict in name, so you'll have to clean all of these up manually.

**Comment by gamma** [comment]
Ok, I see. Since the files have been created on windows I can probably just remove them from the ext4 drive and they should sync back successfully.

**Comment by gamma** [comment]
I have removed the files from the ext4 drive, so that the NTFS files can be synced back. For some files it worked perfectly, for some not. I thought this may fix the issue, but it looks like this still can not be detected as correct.

From my perspective this should now be fixed by syncthing. Any thoughts on this issue?

**Comment by calmh** [comment]
What, precisely, is the issue? The error you are getting occurs when a) Syncthing wants to create a file on disk but b) there is already a file on disk with the "same" name but a different unicode normalization form. This is a situation Syncthing can't rectify automatically without data loss.

**Comment by gamma** [comment]
I just might have resolved the issue. I had to upgrade the second server to the 1.9 RC as well. Since I'm using docker container on the second one I had to build it first. Would be nice to have either RC or upgradable releases on `hub.docker.com` as well.

Thanks anyway.

**Comment by calmh** [comment]
Nothing about unicode normalization has changed for years though, so the RC here should have no effect.

**Comment by gamma** [comment]
Wasn't there a fix for ZFS earlier this year? If I wasn't mistaken I tracked it down to being in the latest release, not the 1.8.0 see #4649

Since the NTFS umlaut file names were sent to the ext4 machine I was thinking it will then recover from this issue. It obviously does not ...

**Comment by calmh** [comment]
As you can see on that issue the fix was merged in 2018 and released in 0.14.44.

**Comment by gamma** [comment]
Yep, now I can see that now.
