### ISSUE TITLE
Can not add new folders on master.

### ISSUE THREAD

**Issue by aTosser** [syncthing/syncthing#6930]
I am running master because my system is on go 1.15, I pulled master this afternoon and everything launches fine but I can not add new folders on my linux system. The save button is unavailable (mouse cursor slashed circle) even if I use the default autogenerated directory and do not supply a label.

Gentoo Linux
Go 1.15
syncthing v1.9.0-rc.4.dev.4.gb19b5c95
qutebrowser (qtwebengine 5.15.0) and Firefox 79.0-r2

**Comment by AudriusButkevicius** [comment]
Seems to have been introduced in https://github.com/syncthing/syncthing/pull/6884 by @rjpruitt16 
If you specify the cleanout interval to 0 seconds in the versioner settings, it seems to work, so perhaps needs a default value.
