### ISSUE TITLE
local discovery announce messages do not include actual local IP addresses

### ISSUE THREAD

**Issue by faulesocke** [syncthing/syncthing#6933]
### Does your log mention database corruption?
Nope.

### Include required information
Syncthing version: 1.8.0
OS: Void Linux

When inspecting the local discovery udp packets sent from my machine (using wireshark), I noticed that it does not include a valid IP address of any of my local interfaces and instead contain a lot of bogus addresses. The packets only contain the following address strings:

- tcp://0.0.0.0:22000
- tcp://0.0.0.0:0
- quic://0.0.0.0:22000
- and my public internet connection address with port 22000

The first 3 entries are bogus. I don't know how syncthing obtained the public address but I guess it uses upnp for this. However, this address is, as well, entirely useless for local connections. I haven't checked the source code but the receiving end might still get the correct IP address when it parses the from-address field of the received packet.

**Comment by AudriusButkevicius** [comment]
0.0.0.0 gets replaced by the receiving side with the ip address from which it received the message.

If you have questions, please use the forum. If something is not as you expect doesn't mean it's a big, you might be just misunderstanding how it works.
