### ISSUE TITLE
footer in web too big.

### ISSUE THREAD

**Issue by sardigital** [syncthing/syncthing#6934]
in russian language footer too big, on other language all ok.
![sync_eng](https://user-images.githubusercontent.com/2103121/91384114-e53fc700-e83e-11ea-9917-578336d72c8a.png)
![sync_rus](https://user-images.githubusercontent.com/2103121/91384129-e83ab780-e83e-11ea-88bc-8b6c1922ae12.png)

**Comment by calmh** [comment]
Arguably, it's precisely as big as it needs to be...

**Comment by imsodin** [comment]
Adding a second row doesn't look broken to me. Truncating somehow would look worse in my opinion.

**Comment by tomasz1986** [comment]
The padding between each of the "text boxes" could be elastic though (e.g. by using percent values). Right now it is set in stone with pixels. The problem happens only with the Russian languages simply because the text there is longer than in the other languages.

**Comment by calmh** [comment]
Make the browser window slightly narrower to switch the medium layout and you get this for almost all the languages. I think this is not a serious enough issue to bother attempting to fix, really.
