### ISSUE TITLE
Modifying config during first scan corrupts folder state

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#6938]
I have seen this problem several times but have not been able to reproduce until now.

How to reproduce:

1. Add a new folder, preferably with a lot of files (so that it takes some time to scan it).
2. While the folder is being scanned for the first time, modify some of its configuration. I changed `Max Conflicts` from `10` to `0`.
3. The folder state is incorrect.

![image](https://user-images.githubusercontent.com/5626656/91457520-663ea300-e8bf-11ea-9683-810116949d88.png)

Below is the same folder, which was just left to scan, with no config changes in between. The state is correct here.

![image](https://user-images.githubusercontent.com/5626656/91457650-8b331600-e8bf-11ea-81c0-86f41b727c3d.png)

Rescanning does nothing. The only way to fix the problem seems to be wiping out the database.

**Comment by calmh** [comment]
Sorry, can you be more specific, what's the incorrectness?

**Comment by calmh** [comment]
That's ... interesting

**Comment by tomasz1986** [comment]
> That's ... interesting

My theory would be that the files, which were scanned before modifying the config, get excluded (?) from the database. Just for the record, I just use the Web GUI to modify the config (i.e. no manual `config.xml` editing, etc.).

**Comment by calmh** [comment]
This is (yet another) accounting-only issue I think. Restarting with `STRECHECKDBEVERY=1s` fixes the counts, meaning the data is correct in the database but the counters are not. Probably we do the wrong thing when aborting a scan somehow, saving files but not managing to update the counters for the last "batch" or so.

**Comment by calmh** [comment]
The folder config changes are also accompanied by 

```
...
[MRIW7] 17:04:08 INFO: Restarted folder "t3" (gg2wz-hdnme) (sendreceive)
[MRIW7] 17:04:22 INFO: Stored folder metadata for "gg2wz-hdnme" is 13.79s old; recalculating
[MRIW7] 17:04:23 INFO: Repaired 1849 sequence entries in database
[MRIW7] 17:04:23 INFO: Failed initial scan of sendreceive folder "t3" (gg2wz-hdnme)
[MRIW7] 17:04:23 INFO: Ready to synchronize "t3" (gg2wz-hdnme) (sendreceive)
...
```

(the "Repaired 1849 sequence entries" means badness happened)

**Comment by tomasz1986** [comment]
> This is (yet another) accounting-only issue I think. Restarting with `STRECHECKDBEVERY=1s` fixes the counts, meaning the data is correct in the database but the counters are not. Probably we do the wrong thing when aborting a scan somehow, saving files but not managing to update the counters for the last "batch" or so.

I have restarted with with `STRECHECKDBEVERY=1s`, but the result is not great.

![image](https://user-images.githubusercontent.com/5626656/91460475-caaf3180-e8c2-11ea-8d53-57b111784f1f.png)

**Comment by calmh** [comment]
That's odd and not something I see in my setup

**Comment by tomasz1986** [comment]
Restarting with `STRECHECKDBEVERY=1s` twice seems to have fixed the issue.

![image](https://user-images.githubusercontent.com/5626656/91461126-97b96d80-e8c3-11ea-8fd0-e04d2a9b4065.png)

Just for the record, I began to investigate this issue after having experienced the problem in my real systems today. The butchered folder state seems to have corrupted synchronisation of the folder with my two other devices.

This is how the situation looks on one of them.

![image](https://user-images.githubusercontent.com/5626656/91461879-81f87800-e8c4-11ea-8814-213d64227855.png)

The "Out of Sync Items" list above actually shows empty.

![image](https://user-images.githubusercontent.com/5626656/91461917-8d4ba380-e8c4-11ea-86be-7a675369f519.png)

This one does list some files from the folder in question, but they are just stuck like this forever.

**Comment by calmh** [comment]
Yeah I think I understand why that would happen.
