### ISSUE TITLE
TypeError: Object doesn't support property or method 'startsWith' in IE 11 / Windows 7

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#6940]
The Web GUI is spammed with the following JavaScript errors in Internet Explorer 11 under Windows 7.

The method seems to be completely unsupported in IE (see https://stackoverflow.com/a/30867255), but I do not have these errors in IE 11 under Windows 10. I am not sure what the difference is though.

![image](https://user-images.githubusercontent.com/5626656/91631188-bd08c180-ea12-11ea-8aeb-8bfc635662a7.png)

```
TypeError: Object doesn't support property or method 'startsWith'
   at $scope.isUnixAddress (http://127.0.0.1:8384/syncthing/core/syncthingController.js:2523:13)
   at $parseFunctionCall (http://127.0.0.1:8384/vendor/angular/angular.js:12492:7)
   at Scope.prototype.$digest (http://127.0.0.1:8384/vendor/angular/angular.js:14423:21)
   at Scope.prototype.$apply (http://127.0.0.1:8384/vendor/angular/angular.js:14694:13)
   at Anonymous function (http://127.0.0.1:8384/vendor/angular/angular.js:14984:11)
   at completeOutstandingRequest (http://127.0.0.1:8384/vendor/angular/angular.js:4959:7)
   at Anonymous function (http://127.0.0.1:8384/vendor/angular/angular.js:5347:7)
```

**Comment by wweich** [comment]
Honestly, I don't think we should make an effort to support a [soon to be officially dead](https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666) "browser" on an officially dead OS, if the user can just install a real browser.

**Comment by calmh** [comment]
This appears to be an IE thing. There are polyfills, but ... 🤷

![image](https://user-images.githubusercontent.com/125426/91631938-c88dc580-e9dd-11ea-98ba-cccaeabbe415.jpeg)‍

**Comment by tomasz1986** [comment]
The news is not about IE 11 support though. The browser itself is going to be supported until at least 2029 (as a part of Windows 10 Enterprise LTSC 2019 and Windows Server 2019), and probably longer than that if it stays a part of the future LTS Windows releases.

There are situations where the user is not allowed to install "a real browser", e.g. education, enterprise, various offices, etc.

I do not think that all functionality needs to be available in older browsers, but a constant spam of errors does not look good.

**Comment by calmh** [comment]
Fixing this won't hurt anything else, so if someone wants to do that it's all right.
