### ISSUE TITLE
Missing strings for translation

### ISSUE THREAD

**Issue by BouRock** [syncthing/syncthing#6943]
There are two missing strings untranslated which I noticed.

- In tooltips "0 files, 0 directories, ~0 B" string, "directories" string is missing for translation
- "Edit Folder" string in Edit dialog is missing for translation
- Hour and Minute strings translation for Uptime indicator (e.g. 1h 30m)

**Comment by imsodin** [comment]
I addressed the first two in https://github.com/syncthing/syncthing/pull/6944. The last one isn't practical the way we do duration strings: take a number of seconds and convert them to m, h, ... (we could go to SI units to remove any need for localisation, but I strongly doubt anyone wants Ms and the like :) ).

**Comment by BouRock** [comment]
- Also "Edit Device" string in Device Edit dialog is missing
