### ISSUE TITLE
problem syncing across a hotspot

### ISSUE THREAD

**Issue by LeoK987** [syncthing/syncthing#6946]
I connect my Mac to my Android phone's wifi hotspot.  On both devices, I set up Syncthing to sync on wifi.  But the two devices do not connect in this case.  I have to turn on sync on mobile data on the phone before the sync works between the two devices.  But since the two devices are connect back to back, I shouldn't have to use mobile data.

**Comment by AudriusButkevicius** [comment]
It will not work that way as discovery will not work u der these conditions. You can hardcode device ip addresses if you want I guess.
