### ISSUE TITLE
Visual eye sore on Advanced Configuration page.

### ISSUE THREAD

**Issue by akissz** [syncthing/syncthing#6949]
The lines above the check boxes make the Advanced Configuration page very difficult to see correctly; especially when viewing on a phone, but also bad on a computer. Also the check boxes are awkwardly far away from the words and the check boxes are huge, why so huge. Overall mainly the lines above the boxes make it very difficult to see clear on a phone browser, so if you fix something, fix the line confusion parts.

**Comment by tomasz1986** [comment]
Which lines do you mean exactly? Could you post a screenshot?

For the record, this is how the page looks for me.

![image](https://user-images.githubusercontent.com/5626656/92015863-68f03b00-ed8c-11ea-94a6-dc222761fd64.png)

**Comment by calmh** [comment]
Those checkboxes are an eye sore

**Comment by tomasz1986** [comment]
> Those checkboxes are an eye sore

Are they? I would say that this is subjective. I find them functional, and the large size actually helps on mobile, as it makes them easy to press on a touch screen. 

As for the look, they just follow the browser's native styles. The screenshot above comes from Chromium 84.

Below is IE 11:

![image](https://user-images.githubusercontent.com/5626656/92055458-4defec00-edc9-11ea-8957-53dea8f0fab5.png)

and Firefox 81:

![image](https://user-images.githubusercontent.com/5626656/92058351-454be580-edca-11ea-9a71-d60337868dd0.png).

**Comment by calmh** [comment]
Well, they're different from our checkboxes in other parts of the UI at least. :)

**Comment by Choongkyu** [comment]
would adding another column (or two? but probably one?) to be more stylistically consistent with, say, the settings modal be a worthwhile pursuit? 

<img width="866" alt="Screen Shot 2021-01-13 at 8 11 44 PM" src="https://user-images.githubusercontent.com/1592194/104544041-bd79b180-55db-11eb-915e-27777b0bb224.png">

**Comment by wweich** [comment]
It's even stranger in Firefox on Linux
![grafik](https://user-images.githubusercontent.com/1026763/104553517-14fb3a00-563b-11eb-853c-0eb9360fc6da.png)

This CSS will do the trick:
```css
#advancedAccordion input.form-control[type="checkbox"] {
    width: auto;
    margin: 0;
}
```
Result:
![grafik](https://user-images.githubusercontent.com/1026763/104553856-a5397f00-563b-11eb-8a77-1120faaa99b3.png)

After work, I will do a PR, if nobody beats me to it :). (no web editor commit possible, as more than one file needs to be changed)

**Comment by tomasz1986** [comment]
Would it not be better to have it left-aligned though? I have just tested the CSS, and I cannot see any advantage of having the checkbox centred, especially such a small one.
