### ISSUE TITLE
Fedora 33 (x86_64) - Syncthing crashes and fails to start

### ISSUE THREAD

**Issue by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [syncthing/syncthing#6955]
The issue I am exeriencing is that `syncthing` doesn't run at all, whereas it did on Fedora 32 (before the upgrade Fedora 32 ---> Fedora 33).
Not sure if it's more appropriate to contact the package maintainer, I am trying here first.

**Synthing:** `syncthing-1.8.0-2.fc33.x86_64`
that is according to `dnf`, `syncthing --version` crashes, too
**OS:** `Fedora release 33 (Thirty Three)` (it's a pre-release ATM though)

#### does your log mention database corruption?
no, no mentions of database corruption

#### any steps to reproduce the problem
- Fedora 33
- install `syncthing` and run it (does not matter if you run the `syncthing` command or have a systemd service run it, fails the same, because it runs the same binary)

```bash
sudo dnf install -y syncthing-1.8.0-2.fc33.x86_64
syncthing
```

I also tried to spin up a clean `fedora:33` Docker image to see if it occurs there, too, and - sure enough.
It fails to start just the same. :(
```bash
docker run --rm -it fedora:33
dnf install -y syncthing
syncthing
```
Here's the beginning of what it says before it gives me goodbye:
> `panic: qtls.ClientSessionState not compatible with tls.ClientSessionState`

![image](https://user-images.githubusercontent.com/61180606/92235826-9fc17080-eeb4-11ea-9746-fe88c12be647.png)

full dump [here](https://paste.centos.org/view/e6fadfad) or here: [syncthing_crash.log](https://github.com/syncthing/syncthing/files/5174642/syncthing_crash.log)

**Comment by AudriusButkevicius** [comment]
Your package maintainers built it with the wrong version of go, you should raise the issue with them.

**Comment by calmh** [comment]
In the meantime, use one of our binaries from syncthing.net/downloads or downgrade to 1.7

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> Your package maintainers built it with the wrong version of go, you should raise the issue with them.

Alright, thanks, I will.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> In the meantime, use one of our binaries from https://syncthing.net/downloads or downgrade to 1.7

Sure, thanks.
Or I can build it myself, too :)

**Comment by calmh** [comment]
Yes, using Go 1.14 for 1.8.0, or 1.15 as you like with current main branch / 1.9.0-rc.5.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> Yes, using Go 1.14 for 1.8.0, or 1.15 as you like with current main branch / 1.9.0-rc.5.

I managed to replace the binary in `/usr/bin/` without any issues and Syncthing now runs just fine again, I have troubles building from source though (main branch, go version `go1.15`).
```
go run build.go build
go: github.com/lucas-clemente/quic-go@v0.18.0 requires
	github.com/francoispqt/gojay@v1.2.13 requires
	cloud.google.com/go@v0.37.0 requires
	golang.org/x/build@v0.0.0-20190111050920-041ab4dc3f9d requires
	sourcegraph.com/sourcegraph/go-diff@v0.5.0: unrecognized import path "sourcegraph.com/sourcegraph/go-diff": https fetch: Get "https://sourcegraph.com/sourcegraph/go-diff?go-get=1": unexpected EOF
```

**Comment by carlwgeorge** [comment]
Here is the relevant Fedora 33 bug for this.

https://bugzilla.redhat.com/show_bug.cgi?id=1871425

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> Here is the relevant Fedora 33 bug for this.
> 
> https://bugzilla.redhat.com/show_bug.cgi?id=1871425

Appears to have been fixed now 🚀
