### ISSUE TITLE
Docker container increased memory usage

### ISSUE THREAD

**Issue by lps-rocks** [syncthing/syncthing#6967]
Version: 1.9.0 (Docker Container Build based off of: https://github.com/syncthing/syncthing/tree/39438736263206ab6dee58989ef09c9d220b5e32)

What Happened:
Memory usage increased 3x after updating to this build. For months prior the memory averaged around 300MB for 500K files, 31K directories, and 650 GiB of data. 

Previous builds (1.8.0) and earlier do not have this substantial memory usage increase.

**Comment by calmh** [comment]
Has it settled, or are you looking at the effect of running database checks and index exchanges on upgrade?

**Comment by lps-rocks** [comment]
It's been settled for a few hours. However it hasn't restarted since the upgrade. Could be left over artifacts not being cleared from memory after the upgrade. I just went through the commits and saw there was a schema change in 1.9.0. 

Daily
<img width="899" alt="Screen Shot 2020-09-08 at 06 20 02" src="https://user-images.githubusercontent.com/10893911/92466097-3633b180-f195-11ea-923c-7b2aff72acd8.png">

Weekly
<img width="896" alt="Screen Shot 2020-09-08 at 06 20 30" src="https://user-images.githubusercontent.com/10893911/92466103-38960b80-f195-11ea-9218-5b5fdafd0df1.png">

**Comment by lps-rocks** [comment]
Here's what im seeing. Syncthing was stable at ~ 600MB (already significantly above average) after boot and after performing any startup re-indexing. As soon as the first client connects, the memory usage doubled to ~ 1.0-1.1GB (where it sits).

**Comment by imsodin** [comment]
Can you grab a heap profile please. Ideally one before the usage increases and one after: https://docs.syncthing.net/users/profiling.html

**Comment by calmh** [comment]
What's the definition of "memory usage"?

**Comment by lps-rocks** [comment]
> Can you grab a heap profile please. Ideally one before the usage increases and one after: https://docs.syncthing.net/users/profiling.html

On it.

> What's the definition of "memory usage"?

Resident memory size.

**Comment by calmh** [comment]
1.9.0 comes with Go 1.15, I can't find it now but I have some vague memory about it changing some of the allocation strategies with GC and how it returns memory to the OS. Things can stick around as RSS even after deallocation if the OS hasn't found a reason to reclaim the pages yet...

**Comment by calmh** [comment]
Only related thing I can find is way back in Go 1.12:

> On Linux, the runtime now uses MADV_FREE to release unused memory. This is more efficient but may result in higher reported RSS. The kernel will reclaim the unused data when it is needed. To revert to the Go 1.11 behavior (MADV_DONTNEED), set the environment variable GODEBUG=madvdontneed=1.

You might try setting that just for fun, but otherwise it looks like I'm misremembering.

**Comment by lps-rocks** [comment]
> Only related thing I can find is way back in Go 1.12:
> 
> > On Linux, the runtime now uses MADV_FREE to release unused memory. This is more efficient but may result in higher reported RSS. The kernel will reclaim the unused data when it is needed. To revert to the Go 1.11 behavior (MADV_DONTNEED), set the environment variable GODEBUG=madvdontneed=1.
> 
> You might try setting that just for fun, but otherwise it looks like I'm misremembering.

This looks to plausibly be the cause. The heap profiles I dumped show only 367MB accounted for and while the RSS usage does change significantly over startup, that number stay the same after startup. 

Looks like syncthing 1.8.0 was targeting 1.13, so I would have expected the same behavior in 1.8.0. 

I was unable to get it to go above 1GB again. 

[syncthing-heap-linux-amd64-v1.9.0-105807-after-start.pprof.zip](https://github.com/syncthing/syncthing/files/5187932/syncthing-heap-linux-amd64-v1.9.0-105807-after-start.pprof.zip)

**Comment by calmh** [comment]
If you're running syncthing/syncthing from Docker hub, 1.8.0 was Go 1.14 and 1.9.0 is now Go 1.15. So *that* change should predate both by a lot. There's a fair amount from the new case sensitivity caching:

<img width="335" alt="Screen Shot 2020-09-08 at 13 20 55" src="https://user-images.githubusercontent.com/125426/92470087-31432200-f1d6-11ea-86cd-961b26d48116.png">

Since you're on Linux, if your filesystems are case sensitive you can set `caseSensitiveFS`: https://docs.syncthing.net/advanced/folder-casesensitivefs

**Comment by lps-rocks** [comment]
> Since you're on Linux, if your filesystems are case sensitive you can set `caseSensitiveFS`: https://docs.syncthing.net/advanced/folder-casesensitivefs on each folder (and then restart for a new baseline)

That did it. It's now starting up much quicker and is hovering around 300MB used memory. 

[syncthing-heap-linux-amd64-v1.9.0-112829.pprof.zip](https://github.com/syncthing/syncthing/files/5187989/syncthing-heap-linux-amd64-v1.9.0-112829.pprof.zip)

**Comment by calmh** [comment]
So... It looks like it's set for FS watching, but that probably doesn't work through docker (?), so I guess it falls back to scans every minute, which would cause the cache to swell and then release on a one minute interval. That won't be enough for Go to release unused memory back to the OS, so I guess this explains the increase in total RAM.

**Comment by lps-rocks** [comment]
It looks like inotify should work in Linux docker containers on a Linux system. However, LCOW does not. I'm not seeing scans kick off every minute. It sits pretty idle.

https://william-yeh.net/post/2019/06/inotify-in-containers/

**Comment by imsodin** [comment]
The reason for the memory increase is clear and https://github.com/syncthing/syncthing/pull/6974 improved the case filesystem memory usage - closing.
