### ISSUE TITLE
given name "~syncthing~xxx.tmp" differs from name in filesystem "~syncthing~XXX.tmp"

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#6973]
How to reproduce:

1. Share a folder with a lot of files from A to B. I used a folder with 10,000 of 0-byte-sized text files.
2. While still syncing, delete the files on A, and wait for the deletions to sync on B. I actually had to restart the folder on B to get the two in sync.
3. Two folders are reported as "Up to Date" at this point.
4. Create the same 10,000 files in the folder on A, but this time with a different case.
5. Some of the newly created files fail to sync to B, because the previously created `~syncthing~<filename>.tmp~` files are still present in the folder.

```
[NISVV] 2020/09/09 08:25:08.279993 folder_sendrecv.go:684: DEBUG: sendreceive/uqzch-bwmvk@0xc0000fea80 parent not missing 368test.txt
[NISVV] 2020/09/09 08:25:08.279993 folder_sendrecv.go:1108: DEBUG: sendreceive/uqzch-bwmvk@0xc0000fea80 need file 368test.txt; copy 1, reused 0
[NISVV] 2020/09/09 08:25:08.279993 folder_sendrecv.go:1554: DEBUG: sendreceive/uqzch-bwmvk@0xc0000fea80 closing 368test.txt
[NISVV] 2020/09/09 08:25:08.279993 folder_sendrecv.go:1790: DEBUG: sendreceive/uqzch-bwmvk@0xc0000fea80 new error for 368test.txt: opening temp file: given name "~syncthing~368test.txt.tmp" differs from name in filesystem "~syncthing~368TEST.txt.tmp"
```

![2020-09-09-08-16-36-0361920](https://user-images.githubusercontent.com/5626656/92537154-68691000-f276-11ea-988b-d3b50c54f0f9.png)

The obvious workaround is to manually delete the temp files, but I think that Syncthing should apply the case sensitivity detection logic to the temp files too.

**Comment by imsodin** [comment]
This is the case sensitivity kicking in and complaining that when creating the new temp file, there is already a file on disk with the same name except case. And we should indeed catch that error and just rename the tempfile to the new name. Thanks for reporting!
