### ISSUE TITLE
Out of memory since 1.9.0

### ISSUE THREAD

**Issue by voruti** [syncthing/syncthing#6981]
Since Syncthing 1.9.0 update randomly crashing (out of memory):
[panic-20200910-180540.reported.log](https://github.com/syncthing/syncthing/files/5205384/panic-20200910-180540.reported.log)

Qnap NAS:
```
# uname -a
Linux [Hostname] 4.2.8 #2 SMP Mon Aug 17 11:04:04 CST 2020 armv7l unknown
```

```
# grep memory panic*
panic-20200910-180540.reported.log:fatal error: out of memory
panic-20200910-205122.reported.log:fatal error: out of memory
panic-20200910-230048.reported.log:fatal error: out of memory
panic-20200911-000938.reported.log:fatal error: out of memory
panic-20200911-010855.reported.log:fatal error: out of memory
panic-20200911-012806.reported.log:fatal error: out of memory
panic-20200911-015900.reported.log:fatal error: out of memory
panic-20200911-023335.reported.log:fatal error: out of memory
```

No manual change anywhere on the NAS; Syncthing upgraded itself automatically.
I don't know the state of the RAM at the time of crash, but the NAS has 8GB RAM, I don't think this was completely filled up ...

Just now I reverted back to 1.8.0, I'll see if it's working at this version again ...

**Comment by calmh** [comment]
1.9.0 uses more memory in some cases, fixed #6974 (1.10.0)
