### ISSUE TITLE
Data loss during Android 11 upgrade

### ISSUE THREAD

**Issue by whs** [syncthing/syncthing#6984]
Application: Syncthing-fork 1.9.0.2. I believe it use syncthing v1.9.0-preview.5 from other device's connection log.

I upgraded my phone to Android 11. As per https://github.com/Catfriend1/syncthing-android/issues/704 the permission to read all files were revoked and I cannot use the Play Store version anymore.

At the same time, I found that all folders that were synced to the phone had all files removed, on all devices. Folders that weren't synced to the phone are intact. The synced files on the phone itself is also intact.

Sadly as the application block the main screen if you don't grant it write permission I cannot obtain logs from it.

**Comment by calmh** [comment]
Hi! This sounds rough, though for this forked app we don't know which version of Syncthing is used nor how it's run, and anyway can't really look at anything without logs. I suggest your report it in the app's bug tracker, and if troubleshooting points to an actual error with the underlying Syncthing then we'll be happy to take a look.

**Comment by Catfriend1** [comment]
Hi,

The fork uses the official release build tag 1.9.0 in its current apk release 1.9.0.2. I absolutely have no idea why the user claims the .stfolder protection wouldn't have worked to protect him from data loss, probably triggered by Google's Android 11 update write protecting folders. My view on this is that SyncthingNative wouldn't have started the folder in model if read access was denied?!

**Comment by imsodin** [comment]
Exactly. And until a problem has been debugged to the point that we there is a bug, that debugging/supporting belongs to forum.syncthing.net, not the issue tracker. So please open a topic there if you want to continue.
