### ISSUE TITLE
filename is invalid

### ISSUE THREAD

**Issue by huacangliang** [syncthing/syncthing#6987]
### Does your log mention database corruption?

2020-09-12 13:35:52 Puller (folder "文档" (6z48y-3th0o), item "印象笔记\\我的笔记\\通过代码执行系统指令后如何获取执行后结果 - Discussion | 技术讨论 - iOSRE.resources\\3397_2_1.png"): syncing: filename is invalid

### Include required information

files sync fail , it print "filename is invalid"

**Comment by tomasz1986** [comment]
If you are trying to sync this to a Windows device, then the character `|` is indeed invalid. Are you able to rename the file on the other device and remove `|` from it?

**Comment by huacangliang** [comment]
> If you are trying to sync this to a Windows device, then the character `|` is indeed invalid. Are you able to rename the file on the other device and remove `|` from it?

emmm,i use macbook sync file, , it so trouble

**Comment by calmh** [comment]
There is some confusion here. Please post the full log from the device seeing this problem.
