### ISSUE TITLE
RFC: tiny databaseTuning

### ISSUE THREAD

**Issue by Hello71** [syncthing/syncthing#6990]
I have a very small database (~600 files+directories, ~2M ldb). The small databaseTuning preset is still somewhat large for me: syncthing uses over 40 MB RAM, and according to pprof, 16 MB is occupied by the write buffer. While I am quite unfamiliar with LevelDB, a 16 MB write buffer for a 2 MB database seems excessive. I set `STDEBUG_WriteBuffer=262144`, which did in fact lower memory usage by a significant amount: along with disabling the GUI and setting `GOGC=20`, the RAM usage was reduced to under 30 MB. While this doesn't sound like a huge amount, it is fairly significant on a small VPS sharing with other services.

I think it could be valuable to provide an explicit databaseTuning setting for this. However, it might be an issue to include it in "auto", since the parameters are only set once at start. So, if someone starts with an empty database and then adds a lot of files (probably fairly common for new users), database performance would be slow until restart. I'm not sure how useful it would be to have this setting but require users to set it manually though... maybe syncthing could keep track of the database size and suggest alternative settings if the database stays below a certain size?

**Comment by AudriusButkevicius** [comment]
I suspect 99.99% of our users don't care about 40MB, as 40MB is nothing nowadays.

I think you are an exception not the norm, in which case I think it's fine for your to have to use additional flags, and I don't think having additional settings specially for you makes any sense.

**Comment by calmh** [comment]
I think the usage spectrum is so wide that we can't reasonably micro optimize for every setup. Keeping the debug knobs around for this case seems reasonable though. Memory usage will increase and fluctuate a lot during use as well, more than when idle.
