### ISSUE TITLE
Incorrect sorting on Statistics Page

### ISSUE THREAD

**Issue by AD-Wright** [syncthing/syncthing#6991]
This might not be quite the right place for reporting the bug, but I hope it will get to the right place.

I am using Syncthing version 1.9, congratulations on reaching v1.10!

However, when viewing the "Statistics" page (https://data.syncthing.net/) from the browser GUI, v1.10 is sorted incorrectly, i.e. between v1.1 and v1.2, not after v1.9.  This messes with the chart as well, resulting in a weird bump of what initially looks like a bunch of new users on an old version.

Illustration of incorrect sorting:
![image](https://user-images.githubusercontent.com/33293489/93514748-d0f26580-f8e4-11ea-93b0-db774a9515dd.png)

**Comment by calmh** [comment]
This is the right place, thanks.
