### ISSUE TITLE
Update "Reverse Proxy Setup" setup instructions for Caddy

### ISSUE THREAD

**Issue by MicahParks** [syncthing/syncthing#6992]
Having syncthing behind a reverse proxy with Caddy fits my use case perfectly. Unfortunately, the syncthing documentation's example Caddyfile seems to be out of date: [https://docs.syncthing.net/users/reverseproxy.html#caddy](https://docs.syncthing.net/users/reverseproxy.html#caddy).

Here is what the docs have currently:
```
proxy /syncthing localhost:8384 {
    transparent
}

timeouts {
    read none
    write none
    header none
}
```

Using the most recent version of Caddy, I think the equivalent would simply be:
```
reverse_proxy http://localhost:8384
```
But I could be wrong.

If this is incorrect, could someone recommend a `reverse_proxy` Caddyfile configuration for syncthing and possibly update the example in the documentation?

**Comment by AudriusButkevicius** [comment]
Does the old way actually not work?
If it works then what's the problem?

**Comment by MicahParks** [comment]
I cannot find any current Caddy documentation that has a directive for `transparent`. Using this directive also appears to give me an error. Additionally, I believe the top level `timeout` blocks have also been removed.

When I run Caddy with the current example config, here is the output:
```
$ cat Caddyfile 
proxy /syncthing localhost:8384 {
    transparent
}

timeouts {
    read none
    write none
    header none
}
$ docker run --rm -it -v $PWD/Caddyfile:/etc/caddy/Caddyfile caddy
2020/09/17 23:39:22.489	INFO	using provided configuration	{"config_file": "/etc/caddy/Caddyfile", "config_adapter": "caddyfile"}
run: adapting config using caddyfile: /etc/caddy/Caddyfile:2: unrecognized directive: transparent
```
___

I know this Caddyfile appears to work normally for my instance of syncthing (syncs files, presents web GUI):
```
syncthing.example.com {
    reverse_proxy http://syncthing.container.hostname:8384
}
```

What I do not know is if the `transparent` directive or `timeout` block have translated to anything for the most recent version of how to write a Caddyfile. I wouldn't want to submit a PR for an update to the docs that is missing a directive which causes syncthing to preform suboptimally.

For example: all of the files I am syncing are less than 500 KB, so if a directive of `flush_interval` needs to be defined in order for syncthing to behave normally for files greater than 500KB, then my current Caddyfile would be inadequate.

**Comment by calmh** [comment]
I think in Caddy 2 it's always transparent and the timeouts are global (they were in Caddy 1 as well, they just didn't look like it). We should probably retain both Caddy 1 and Caddy 2 samples, I personally for example haven't migrated to 2 yet.

**Comment by rjpruitt16** [comment]
detective @rjpruitt16 is on the case.

**Comment by imsodin** [comment]
Fixed by https://github.com/syncthing/docs/pull/576

**Comment by petwri** [comment]
I have tried exactly the config mentioned [here ](https://docs.syncthing.net/users/reverseproxy.html) for Caddy V2, but I get a 404 error. Anybody else experiencing this? I am on v1.12.0.

**Comment by imsodin** [comment]
Please use https://forum.syncthing.net/ for support.
