### ISSUE TITLE
Consider improving/simplifying case-conflict handling

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#6996]
User feedback after the change to detect case conflicts (https://github.com/syncthing/syncthing/pull/6717) showed that case-conflicts are not that rare. And it's not just the FS being case-insensitive, users really seem fully accustomed to it. I.e. the weird thing isn't that the same file exists with two different cases on two devices, but that Syncthing complains about it. In that light it would be useful to have a simplified or automated way of dealing with case conflicts.

One option to consider is to use the same mechanism as for sync-conflicts: When detecting case conflicts on pull, rename one of the files. I.e. when trying to pull `foo.txt`, but `Foo.txt` already exists, rename one to `Foo.case-conflict-*date*.txt` (with some policy to make it deterministic which to rename). Potentially making it configurable, for use-cases involving mixed clusters.

**Comment by tezfair** [comment]
Can you include an option where the send only side always wins. I have no interest in having St making case conflict files as I want what the receive only side to be a mirror of the sending end.

**Comment by imsodin** [comment]
I am closing this in favor of #6989, as I created this issue expecting that the other, more narrow one, gets solved quickly. However my current view is that doing any kind of automatic resolution is problematic/unsafe and/or very complex, as e.g. explained in this comment on an attempt at doing it: https://github.com/syncthing/syncthing/pull/7014#issuecomment-701277474.
