### ISSUE TITLE
Devices frequently can't communicate

### ISSUE THREAD

**Issue by dspacejs** [syncthing/syncthing#6998]
### Does your log mention database corruption?

No.

### Include required information

Syncthing version: syncthing unknown-dev "Erbium Earthworm" (go1.13.5 linux-amd64)
OS: Ubuntu 20.04 LTS / Android 10 (Graphene OS) on Pixel 2 XL

I've hooked up Syncthing between my phone and PC. It works fine sometimes, but most of the time each device says the other is disconnected when it's not. They both have an internet connection that works.

Both devices are also connected via a VPN, which I figured may be interfering with the local discovery network. So I tried using a public relay server instead (`167.179.185.133:22067`). This didn't work either, each device still thinks the other is disconnected.

I've tried restarting the daemon on each device and manually triggering a sync. I've also tried reconnecting the internet on each device. Sometimes messing around with this gets it to work and it syncs properly. But 90% of the time it doesn't and is extremely unreliable.

I'm not sure what I'm doing wrong, as as user I expected this work pretty seamlessly.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
