### ISSUE TITLE
Linux Windows incompatibility

### ISSUE THREAD

**Issue by JEdward7777** [syncthing/syncthing#6999]
Hello.  First off, I like Syncthing a lot.  I have been using it whole sale since Dropbox limited the free accounts to three computers.  
I have a problem which probably is related to the case rename problem.  But I don't know how to recover.
I have two Linux computers and two windows computers syncing a folder.  It contains all my projects and stuff I am working on.  I use python virtual env in the folder and it did something which upset both of the windows computers.  Like I said, it probably renamed a file by case only somehow.  Perhaps a pip update or something like that.
Anyways I thought I would fix it by renaming the root folder.  However this didn't work.  Now both windows computers are jammed complaining about the old path which doesn't even exist anywhere.  It doesn't exist on the Linux computers and it doesn't exist on the windows computers.  I am assuming I could meticulously create the file that it is complaining about and then delete it again, but there are hundreds of them and it is several folders deep.  
So then I thought perhaps I would just start over with the windows computers and hope that the python virtual environments would behave themselves and not do whatever they did again to any the windows computers.  But I am not sure how.  I thought that perhaps I would just change the path pointed to on the windows computers and then they could just do their init sync again, however with a bit of research I learned that that would delete all my files on all the computers! That would be tragic!  I probably should be backing up somehow...  But I would hate to lose all my projects.  https://github.com/syncthing/syncthing/issues/549  I am glad I didn't try that.  What should I do?

**Comment by acolomb** [comment]
When creating a virtual env on Linux, it uses symbolic links pointing to the python interpreter. Syncthing does not support those well, and they cannot be synced to Windows. I usually ignore the virtual env directories in Syncthing's .stignore file as they are not reusable between Windows and Linux boxes anyhow.

Hope that gives you a clue where to look further. Support requests should go to the forum, though, instead of this issue tracker. Make sure you include some meaningful error / log messages there.

**Comment by AudriusButkevicius** [comment]
> What should I do?

You should follow what is said in the issue template and head to the forum for support.

**Comment by imsodin** [comment]
1. Same as above, please use the forum to ask for help.

2. As case-renames only and clusters with both linux and windows devices were mentioned: The longstanding bug https://github.com/syncthing/syncthing/issues/1787 about that has been fixed in v1.9.0.
