### ISSUE TITLE
Connection error on web GUI after a while

### ISSUE THREAD

**Issue by Nutomic** [syncthing/syncthing#700]
After upgrading to v0.9.16, and running it for a while, the web GUI shows an connection error. Reloading it also fails.

 However, console output looks normal (which means syncthing is actually running):

```
[monitor] 22:22:00 INFO: Starting syncthing
[UE6TV] 22:22:01 INFO: syncthing v0.9.16 (go1.3.1 linux-amd64 default) jenkins@build.syncthing.net 2014-09-17 15:11:53 UTC
[UE6TV] 22:22:01 INFO: My ID: x-x-x
[UE6TV] 22:22:01 INFO: Starting web GUI on http://127.0.0.1:8080/
[UE6TV] 22:22:02 INFO: Performing initial repository scan
[UE6TV] 22:22:04 WARNING: Failed to create UPnP port mapping
[UE6TV] 22:22:04 INFO: Starting local discovery announcements
[UE6TV] 22:22:04 INFO: Starting global discovery announcements
[UE6TV] 22:22:04 OK: Ready to synchronize felix_music (read-write)
[UE6TV] 22:22:04 OK: Ready to synchronize felix_nexus_backup (read-write)
[UE6TV] 22:22:04 OK: Ready to synchronize felix_sync (read-write)
[UE6TV] 22:22:04 INFO: Node y-y-y is "n1" at [dynamic]
[UE6TV] 22:22:04 INFO: Node x-x-x is "n2" at [dynamic]
[UE6TV] 22:22:04 INFO: Node z-z-z is "n3" at [dynamic]
[UE6TV] 22:22:04 INFO: Starting usage reporting
[UE6TV] 22:22:22 INFO: Established secure connection to z-z-z at ip
[UE6TV] 22:23:07 INFO: Node z-z-z client is "syncthing v0.9.16"
[UE6TV] 22:23:07 INFO: Node z-z-z hostname is "n3"
```

**Comment by pguth** [comment]
I see a `Connection Error` in red on the webpage even though the script is still getting `refreshConnections` JSON objects from the server.

The dev console also shows `refreshErrors Objecterrors: null__proto__: Object syncthingController`:

<img width="536" alt="screen shot 2017-03-04 at 22 15 57" src="https://cloud.githubusercontent.com/assets/85259/23582312/32542fd8-0128-11e7-9ed5-cd7a6b74867e.png">

**Comment by canton7** [comment]
Please don't resurrect issues which are over 2 years old. Post in [the forum](https://forum.syncthing.net) instead.
