### ISSUE TITLE
Meshed syncthing devices synchronize very slowly

### ISSUE THREAD

**Issue by archtur** [syncthing/syncthing#7003]
# Environment

- 3 syncthing devices - 2 linux machines, 1 android device
- all devices have syncthing version 1.9.0
- I configured one folder, that is shared between all the three devices. This means each device shares this folder to each other connected device. This is what I call "meshed".
- Content of the folder: I used the current git master branch content of the linux kernel to test that (~70.000 files with about 912MiB)

# Steps to reproduce

1. On **[Device 1]**
	- Download the test content from https://github.com/torvalds/linux/archive/master.zip
	- Unzip the content
	- Add the folder to syncthing
	- Share the folder to **[Device 2]**

2. On **[Device 2]**
	- Allow the shared folder from **[Device 1]**
	- Look at the download rate: At my desk the complete folder was finished after ~15 minutes (not too fast, but one device has slow Wifi)
	- Wait until it finished

3. On **[Device 1]** and on **[Device 2]**
	- Share the folder to **[Device 3]**
4. On **[Device 3]**
	- Allow the shared folder from **[Device 1]** and from **[Device 2]**
	- **ISSUE**: Look at the download rate: This is now very slow, after half an hour I had synched only about 11% of the content

The sync inside this mesh costallation is always very slow, also after the initial full sync. The issue is not visible any more as soon as you disable all sync paths to one of the three devices.
The expected behavior is that the sync in this mesh is as fast as in a two device sync line.

In my opinion the issue could be that there is often a rescan in that "mesh" constellation. Maybe after getting content from one of the devices there is always a rescan to the second device or something like that. But that is only theory, I don't have a deep understanding of the syncthing internals.

Can you tell me if you officially support that "mesh" configuration?

If you have further questions, don't hesitate to contact me.

Thank you!

**Comment by AudriusButkevicius** [comment]
I don't think this is something specific with the application code, but rather specific to your setup, hence I don't think this is a bug.

It's an interesting case and I am happy to discuss this with more depth on the forum.

**Comment by archtur** [comment]
Do I have to do anything to get this discussion running?

**Comment by archtur** [comment]
> I don't think this is something specific with the application code, but rather specific to your setup, hence I don't think this is a bug.
> 
> It's an interesting case and I am happy to discuss this with more depth on the forum.

Do I have to do anything to get this discussion running?

**Comment by AudriusButkevicius** [comment]
Start a thread on the forum
