### ISSUE TITLE
GUI displays text (key value pairs?) at the bottom after conflict is detected

### ISSUE THREAD

**Issue by shanks1337** [syncthing/syncthing#7004]
Version Syncthing: v1.9.0, Windows (64 bit) 
Version OS: Windows 8.1 Pro N

GUI displays text (key value pairs?) at the bottom after conflict is detected that isn't supposed to be there. 

![syncthing visual bug 1](https://user-images.githubusercontent.com/8984284/94142591-d3b60300-fe6e-11ea-99f6-72df9ffebd9b.png)
![syncthing visual bug 2](https://user-images.githubusercontent.com/8984284/94142595-d4e73000-fe6e-11ea-886a-d1827ab778d5.png)

This is how the bug is reliable reproducible for me:
1) trigger conflict: change text in new.txt on device A and new.txt on device B before it's been synced
2) then go "actions" -> "restart" and wait untill window is reinitialized
3) close syncthing window [X] and open it again via double click from tray

**Comment by calmh** [comment]
This is not the Syncthing GUI. I think you need to report this at https://github.com/canton7/SyncTrayzor/issues. If it turns out to be our bug in the end we'll of course happily reopen and fix.
