### ISSUE TITLE
Windows 10  Detects PUA:Win32/CandyOpen

### ISSUE THREAD

**Issue by yogiberra** [syncthing/syncthing#7007]
![image](https://user-images.githubusercontent.com/24483459/94340586-e720b580-ffb7-11ea-81ac-504aa5b883c7.png)

After install Windows 10  identifies that SynThing contains Potentially Unwanted Software.    Is this software safe?

### Does your log mention database corruption?

If your Syncthing log reports panics because of database corruption it is
most likely a fault with your system's storage or memory. Affected log
entries will contain lines starting with `panic: leveldb`. You will need to
delete the index database to clear this, by running `syncthing
-reset-database`.

### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using
 - browser and version, if applicable
 - what happened,
 - what you expected to happen instead, and
 - any steps to reproduce the problem.

**Comment by tomasz1986** [comment]
Windows 10 is actually correct about PUP in that file, but you are downloading a completely different software. Please check https://syncthing.net if you want to download Syncthing.
