### ISSUE TITLE
Filenames containing dots lead to a "The system cannot find the file specified" sync error

### ISSUE THREAD

**Issue by cryobry** [syncthing/syncthing#7008]
v1.9.0 Linux syncing to v1.9.0 Windows

Any files containing dots in the path or filename causes a "the system cannot find the file specified" sync error on the Windows client.

See attached:
![Screenshot from 2020-09-26 16-13-11](https://user-images.githubusercontent.com/38270216/94349556-67c0cf80-0013-11eb-930e-8a4e0f8ccfad.png)

**Comment by calmh** [comment]
File or directory names on Windows cannot end with a trailing dot. Probably we should reject them with an "invalid filename" error at an earlier stage.

**Comment by tomasz1986** [comment]
> File or directory names on Windows cannot end with a trailing dot. Probably we should reject them with an "invalid filename" error at an earlier stage.

Hmm, I can sync such files/folders between my Windows and Android machines. They can be created using

```
md \\?\C:\testfolder.
echo>\\?\C:\testfile.
```

or even

```
echo>\\?\C:\NUL
```

Although more of a hack than anything else, all of them are happily synced.

**Comment by calmh** [comment]
You can *create* them, but you don't actually *get* a file named like that on the Windows.

**Comment by calmh** [comment]
Probably some of the APIs we use don't like them. They're not supposed to exist, after all. :)

**Comment by tomasz1986** [comment]
Yeah, but I am not sure if this is really the reason for the error described here though. I can synchronise them in my systems, and Syncthing does not complain at all.

**Comment by calmh** [comment]
I'm certain it's the reason, but whether it's because our mkdir does not work precisely the same way your shell `md \\?\etc` does or because the filesystem or OS or registry or something is different is unclear. It doesn't matter though because the root problem is that we're attempting to do something we shouldn't (create a directory with an unsupported name).

**Comment by tomasz1986** [comment]
Yes, but judging by what is going on in Android, I have a feeling that this is caused by the (ex)FAT system, and will be a problem regardless of the OS.

**Comment by calmh** [comment]
It's indeed also true that FAT does not support all the things you might wish of a filesystem even when running under non-Windows. That's a different sort of problem though.

**Comment by tomasz1986** [comment]
All right. The problem, I guess, will mostly be limited to Android, where FAT is common.

However, I have just seen that in the commit you included all the different reserved names like `NUL`, etc. but what about names followed by extensions? I mean `NUL.txt`, `NUL.exe` and similar. These are also considered "illegal" in Windows, i.e. Windows Explorer is unable to operate on them.

**Comment by calmh** [comment]
I didn't test the illegality, just went by the "is not recommended" which I felt was less strong than "do not use" for the rest of the description. Those should apparently also be removed, yes.

**Comment by tomasz1986** [comment]
I am very sorry for writing again, but I just wanted to say that there is a loophole in the current handling of the invalid filenames.

Basically, if an invalid file, e.g. `CON`, already exists in the folder on both sides, Syncthing will happily mark both "Up to Date". This can happen when sharing the folder for the first time with pre-existing files on both sides, or after copying the file manually to the other folder. Syncthing also accepts all invalid filenames when the folder is "Unshared".

Is this OK as it is, or should Syncthing also mark these as invalid?

**Comment by calmh** [comment]
I think that's fine. We try to prevent oddities. If you've managed to have pre-existing oddities you can keep them. :)

**Comment by Slender1808** [comment]
would you be able to mark a specific file to not be synchronized ?
example pet.notsync.jpg

**Comment by AudriusButkevicius** [comment]
Please use the forum for questions
