### ISSUE TITLE
Limit CPU usage or scanning rate for scanning activity

### ISSUE THREAD

**Issue by johnrix** [syncthing/syncthing#7016]
First off, SyncThing is a fantastic tool and continues to get better with time, so thankyou to all contributors.

It would be helpful to have a means of limiting the rate of scanning activity or otherwise limiting the CPU utilisation during scanning tasks. 

Background: I use a Dell XPS desktop computer which, while being an excellent development machine, does tend to get very noisy fans when CPU utilisation goes up for any extended period of time. SyncThing periodically causes such spikes while performing scanning activity, resulting in a fairly noisy and distracting work environment during this time. I have reviewed the Advanced Settings page but did not spot anything specifically to help in this regard - apologies if I missed it though!

(Just for additional context, I have my primary development folder hosted as a samba share from within a VirtualBox managed Ubuntu VM inside Windows 10. SyncThing is running on the Windows host rather than the Ubuntu guest at present. I have not tried running SyncThing inside the VM yet to see if this reduces system load, but will do so soon.)

**Comment by imsodin** [comment]
This has been discussed many times before and this is out of scope for Syncthing (generally resource limiting is a task for the OS not single applications, and there are tools to hard limit cpu usage, at least on linux). This is in my opinion a good starting point to get more background: https://forum.syncthing.net/t/feature-proposal-smart-adaptative-resource-usage/14531/27

**Comment by johnrix** [comment]
Thanks for the feedback and the quick response. I'll follow that path and see where it takes me!
