### ISSUE TITLE
Tests fail when building the Alpine pkg on aarch64

### ISSUE THREAD

**Issue by Eluminae** [syncthing/syncthing#7021]
I'm trying to add the aarch64 pkg on Alpine repositories but we're still stuck on tests that fail with this architecture.

Here the full log:
https://paste.sr.ht/~reedwade/18d36d4ed6dcb6c6d4696b3e0d6b28c880c2af89

Here the full recipe:
https://git.alpinelinux.org/aports/tree/community/syncthing/APKBUILD?id=5899f8a6a1300ca6814737ffce364eb81a766719

it seems I still can build with a second try : https://paste.sr.ht/~reedwade/6f26c06d1fd51bc9fd5685cfdb97edbff002b4ef

Is it a known issue ? Is it a real issue or only a test problem ? Should tests be fixed ?

**Comment by imsodin** [comment]
The failing `TestGlobalDirectory...` tests are racy, i.e. no real issue. Will post a PR fixing it.
