### ISSUE TITLE
panic: key not found when repairing DB

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#7026]
https://sentry.syncthing.net/share/issue/b29b701f48f64fcf8ce06ef60e3cc765/

```
github.com/syncthing/syncthing/lib/db/lowlevel.go in func1 at line 818
github.com/syncthing/syncthing/lib/db/lowlevel.go in getMetaAndCheck at line 833
github.com/syncthing/syncthing/lib/db/lowlevel.go in loadMetadataTracker at line 856
github.com/syncthing/syncthing/lib/db/set.go in NewFileSet at line 46
```

We can't know for sure where the error is occuring, as the panic happens in defer, but given it happens on 1.10.0 only it's most likely the code added in https://github.com/syncthing/syncthing/pull/6950. The only places I see where a `key not found` could occur are the `Delete` calls. However the deleted keys are keys we just got by iterating, so they should exist.

The github-sentry integration seems to be broken

**Comment by calmh** [comment]
(GitHub has been sending me angry emails about the sentry integration using some deprecated API. We may want to upgrade it at some point.)

**Comment by imsodin** [comment]
Me too. And the sentry integration itself is deprecated, in favor of global apps (but it looks like we are already using that?): https://github.com/getsentry/sentry/tree/master/src/sentry_plugins/github Can't look into it as I don't have sentry admin access.

**Comment by AudriusButkevicius** [comment]
The integration is only used to associate commits with reported events, which was always a hit and miss (mostly a miss), so I am not sure if it matters?

**Comment by imsodin** [comment]
This issue has now suddenly disappeared from sentry. The link above points to something completely different and a search turns up only old stuff: https://sentry.syncthing.net/syncthing/syncthing/?query=key+not+found No clue what's going on.

**Comment by calmh** [comment]
The reports are there in the original, so it wasn't just you hallucinating anyway.

https://crash.syncthing.net/reports/b4ef2d010bc68a3f674ab0833fb1a5054271a1a7da7585bc46563d04e5731cfe
https://crash.syncthing.net/reports/b49f60572e8984e2f96416d39db8fc225b71233f297ef318a045386b2ff0dd37
https://crash.syncthing.net/reports/b4e539b29889cccb80e72e97b9b77375e6270bcd93ece84dae1bd55bc10d7c48
https://crash.syncthing.net/reports/b436bbd7cd150b323c1758473381a4311fabdbf505f87a2f30dbb8859634e2f4
https://crash.syncthing.net/reports/b4e22a4638b602fbd97d9bff234d5b610266723907ef864f1cdcc74c6316d4eb
https://crash.syncthing.net/reports/b4b1d097babf8306a636cf9eff81b4550512b8e250d97fe56f919ae27b195ad1
https://crash.syncthing.net/reports/b4dee8b92a4de337a0dbb0287f86391f9cfd762edae479bc87bffa59c56cd20c
https://crash.syncthing.net/reports/b443ac9358a166dd951d226dd03c4336add2d7e70e40c2681c0a375621d3d829
https://crash.syncthing.net/reports/b4af16d6c5d388a9a342cd59f1fdb105fe718ac24ab57d3f018cd968d7f7d1a1
https://crash.syncthing.net/reports/68c34e99418d5e1e0102c4a31bfb1de11362de053e26ffbb36f6065541fc7fe8
https://crash.syncthing.net/reports/688e76262a2e0f0c33c49d03219eee8d67fc48f6e18916a7de9a2c592658a3a4
https://crash.syncthing.net/reports/68e192e740cf4d71bd4608df8728838abb30979af5182550f0efd260867349a5
https://crash.syncthing.net/reports/68cbab82e9896d3b3c07d1edb00dd916e30f3c22131e6e5d86aed3ac2aaa0ce9
https://crash.syncthing.net/reports/683d9925db6778a77657b496c25d7f698531f28283d5aec1663c70e29d4cbdc1
https://crash.syncthing.net/reports/683d2a40fc519b087b9793f1326c6e988093987f3a0829f8a2277636c727cd1c
https://crash.syncthing.net/reports/68f88cbdbe9ae16d6952cdcc003cd1f13a9749170a3feac7a5239795af130f4c
https://crash.syncthing.net/reports/68425f4c0835fe187fd4097def27830e12bec559805524bd070a8c8b80bb7855
https://crash.syncthing.net/reports/68ac1446a09618264939972c271946bb6b53000725248f5eefcc11cd407d16fa
https://crash.syncthing.net/reports/68389796fb0e90e2b6b7e48dea9c64fca78480ad9f82ac887d211aac7dc85712
https://crash.syncthing.net/reports/07b49a7ca5e4e32af17d845495e490971067d85b10da62d25ad02d38ab5b43b7

(then I stopped grepping)

**Comment by AudriusButkevicius** [comment]
So is sentry actually broken?

**Comment by imsodin** [comment]
I think mystery solved on the "disappeared" sentry issue:  
Database corruptions lead to the same trace and were matched together with the `panic: key not found` events. Those events can still be found when looking at the events list. Probably sentry matches on trace alone, not the panic message (which is bad), and uses the latest message to name the event.  
So yeah, issue reopened.

And yes the github integration is broken, but as said before that's not really important.

**Comment by AudriusButkevicius** [comment]
We control the fingerprint so could decide how we merge the events.

**Comment by imsodin** [comment]
I was about to include the message in the fingerprint, but it requires a bit more finesse. Otherwise a ton of new (-ly separate) issues of the form of `panic: filling Blocks: leveldb/table: corruption on data-block (pos=44628228): checksum mismatch, want=0xc0cf30b4 got=0x9904896c [file=059189.ldb]` will pop up. Same for out of range panics and possibly more.
