### ISSUE TITLE
The on-demand synchronization

### ISSUE THREAD

**Issue by Slender1808** [syncthing/syncthing#7031]
The on-demand synchronization function is a great function, which will open up more application scenarios of syncthing, and this function is not difficult to implement. I am sorry that there is no code capability, but it is viewed from the perspective of a user.  Although there is a file ignoring function, the above is the inappropriateness of Google Translate.

_Originally posted by @Qifcn in https://github.com/syncthing/syncthing/issues/6753#issuecomment-682433704_

**Comment by Slender1808** [comment]
I would like to know if someone is already returning this function

**Comment by imsodin** [comment]
Duplicate of the issue you linked yourselves.
