### ISSUE TITLE
Folders getting stuck in "Syncing" after a20c6ca after doing changes when folders are paused

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7034]
After a20c6ca868db44327575440bfa3501f96ba3afcd, there is no disconnect on config change anymore, but folders seem to get stuck in the "Syncing" state.

How to reproduce:

1. Pause local folders.
2. Do changes in local folders.
3. Unpause local folders.

![image](https://user-images.githubusercontent.com/5626656/95826070-c05ecf00-0d6c-11eb-918c-ea47faab0e11.png)
![image](https://user-images.githubusercontent.com/5626656/95826078-c359bf80-0d6c-11eb-9222-6ba281101fc7.png)

Once stuck, they seem to stay like that basically forever. There is also nothing in the logs.

I have to pause and resume the affected devices (and hence force a connection reset) in order to make the folders actually sync the changes.

Tested with `main` (`v1.10.1-dev.23.gd828adb6`).

**Comment by calmh** [comment]
The problem is that we create a new fileset when pausing/resuming the folder, but the index sender retains the old one which is no longer updated.

**Comment by calmh** [comment]
The problem is also slightly larger, because it applies when we remove a folder completely (index senders are left behind) and when we add a new folder (index senders are not started).

**Comment by imsodin** [comment]
Just from a second of thought, don't have time to consider wider implications/larger scope: Stopping index senders when stopping (pausing/removing) folders should solve this and is the right thing to do anyway.
