### ISSUE TITLE
Devices Announcing LAN addresses even with AnnounceLANAddresses set to off/false

### ISSUE THREAD

**Issue by pop9119** [syncthing/syncthing#7035]
Ever since the 1.10 update all of my devices are announcing their LAN addresses, even after I switch the config to turn that feature off. Despite this, devices are remembering or still discovering the LAN addresses of other devices.

I was expecting that turning off the LAN announcing would return the devices to pre-1.10 operations, but that is not the case. I do not want devices announcing their LAN addresses to either the Global Discovery servers or to each other if they are on completely separate networks.

**Comment by AudriusButkevicius** [comment]
Addresses take time to expire I think, so even if you set it to false, some time has to pass from them to roll off the discovery server.

**Comment by imsodin** [comment]
@pop9119 Can you confirm (or not) that LAN addresses did expire by now, i.e. are not announced anymore?

**Comment by pop9119** [comment]
Yes I can confirm this behavior.

This morning I turned on 2 machines that have been powered off for 5 days. Here is an example of the addresses that one machine discovered about the other:

quic://169.254.10.59:22000
quic://169.254.13.213:22000
quic://169.254.232.146:22000
quic://192.168.47.1:22000
quic://192.168.99.3:22000
tcp://169.254.10.59:22000
tcp://169.254.13.213:22000
dial tcp 169.254.13.213:22000:
tcp://169.254.232.146:22000
tcp://192.168.47.1:22000
tcp://192.168.99.3:22000


I took out the public addresses from that list, but those public addresses are the only way theses machines talk to each other, as they are not on the same LAN.

**Comment by AudriusButkevicius** [comment]
Are you sure these came through global discovery rather than local?

**Comment by pop9119** [comment]
These never use to come through until the LAN address announcing started. Was this changed to add theses addresses through local announcing?

**Comment by AudriusButkevicius** [comment]
I was about to put a snarky comment that it works for me, but there is a clear bug here. I've opened a PR fixing it.
