### ISSUE TITLE
Shutting Syncthing down while pushing files to multiple devices corrupts the database?

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7036]
Related to https://forum.syncthing.net/t/folders-up-to-date-but-stuck-in-syncing-with-empty-out-of-sync-items/15667.

How to reproduce:

1. Create and share an empty folder between 3 devices - A, B, and C. 
2. Add a few large files to the folder on A.
3. While the files are still being pushed from A to B and C, shut Syncthing down on A.
5. Restart Syncthing on A.
6. Wait for the previously interrupted synchronisation to finish.
7. C is stuck trying to sync the files to B, but they exist there already.

![image](https://user-images.githubusercontent.com/5626656/96167973-14c7a180-0f5b-11eb-89a4-7bc34b2dc7db.png)
![image](https://user-images.githubusercontent.com/5626656/96167983-1729fb80-0f5b-11eb-95e1-98916c717a51.png)
![image](https://user-images.githubusercontent.com/5626656/96167996-198c5580-0f5b-11eb-9a01-7c85d743bc28.png)
![image](https://user-images.githubusercontent.com/5626656/96168427-afc07b80-0f5b-11eb-8837-c25fa79bacf8.png)

**Comment by imsodin** [comment]
I can't reproduce unfortunately - does it work consistently for you? Can you enable model and db debug logging while reproducing and share those logs.

**Comment by tomasz1986** [comment]
You cannot reproduce this, because I have missed a few required steps, which I apologise for. This is actually a little bit crazy. I have just re-tested everything, and below is the actual way to reproduce the problem.

How to reproduce:

1. Create and share an empty folder between 3 devices - A, B, and C. 
2. Add a few large files to the folder on A.
3. **Let the files sync, then delete them on A, and let the deletions sync.**
3. While the files are still being pushed from A to B and C, shut Syncthing down on A.
4. **Replace the Syncthing binary on A with a newer/different version.**
5. Restart Syncthing on A.
6. Wait for the previously interrupted synchronisation to finish.
7. **B and C are stuck trying to sync the files to to each other, but they exist there already.**

Just in case, here are the logs with `db` and `model` enabled.

[syncthing1.log](https://github.com/syncthing/syncthing/files/5403680/syncthing1.log)
[syncthing2.log](https://github.com/syncthing/syncthing/files/5403681/syncthing2.log)
[syncthing3.log](https://github.com/syncthing/syncthing/files/5403682/syncthing3.log)

Perhaps there is a simpler way to reproduce this, but I have tried multiple times, and it seems that all these steps are required. Firstly, the files need to have been already present in the databases before, even if they do not exist now. Secondly, there needs to be an upgrade/replacement of the Syncthing binary in between the interrupted synchronisation. Lastly, more than 2 devices need to be involved for the error to occur.

**Comment by imsodin** [comment]
Thanks for the logs. After a bit of staring I noticed a smoking gun (after index reset of A, B suddenly needed two items instead of just the one) and now managed to reproduce it in a unit test. Now I can look into the cause and a fix :)
