### ISSUE TITLE
size limit

### ISSUE THREAD

**Issue by Slender1808** [syncthing/syncthing#7037]
I would like to know if it would be possible to set a size limit for a folder, so that when the limit was reached, the oldest files would be eliminated to make room for the new one.

**Comment by calmh** [comment]
There is no option to do this. It's also not really in Syncthing's nature (the "eliminate" part) so I don't think this is something that we'll put on the roadmap.

**Comment by Slender1808** [comment]
Would it be possible to synchronize a folder larger than free space?

**Comment by imsodin** [comment]
Please use the forum for general questions/support: https://forum.syncthing.net/
