### ISSUE TITLE
panic: proto: wrong wireType = 2 for field Deleted

### ISSUE THREAD

**Issue by skylarmt** [syncthing/syncthing#7039]
* Version: 1.10.0
* OS: Ubuntu Linux
* What happened: Syncthing had a panic when trying to start syncing a folder.
* [Panic log](https://github.com/syncthing/syncthing/files/5396402/panic-redacted.log)

**Comment by skylarmt** [comment]
Solution: running `syncthing -reset-database` seemed to fix it so far.

**Comment by AudriusButkevicius** [comment]
This is going to be hardware issues, most likely corrupt database.
