### ISSUE TITLE
Phone soft reboots continuesly when trying to write to sdcard

### ISSUE THREAD

**Issue by beatstick** [syncthing/syncthing#7043]
It worked well for several weeks, but now I get soft reboots on LOS17.1 while trying to sync via wifi to and from sdcard. (Superuser rights for syncthing granted by magisk). 
It might have to do with the card not having enough space left to sync all files. I cannot find the option to not write to disk when disk has less than 5% space left or something. That's available on windows/linux at least.

I use the latest version of Syncthing from f-droid.

**Comment by calmh** [comment]
Hi! This is unfortunately the wrong repository / issue tracker for your issue. Please file it in http://github.com/syncthing/syncthing-android/issues to get the correct attention.
