### ISSUE TITLE
Ignored files considered "Out of Sync Items" despite folder being "Up to Date"

### ISSUE THREAD

**Issue by KRMisha** [syncthing/syncthing#7046]
Files are being marked as "Out of Sync" in the device overview section, despite both folders being up to date. The files in question are files which were deleted from the device which is consired the "modifying device". The files are in the .stignore for both devices, and are not physically present anymore. Syncthing on the receiving device seems to be trying to sync the deletion of the files. May be related to: https://forum.syncthing.net/t/folders-up-to-date-but-stuck-in-syncing-with-empty-out-of-sync-items/15667/10

Receiving device ("dreamrunner-k"):
![image](https://user-images.githubusercontent.com/30484238/96644824-9d499780-12f7-11eb-88d8-2d67fe8be340.png)
![image](https://user-images.githubusercontent.com/30484238/96644860-af2b3a80-12f7-11eb-8a02-ae107b23a0aa.png)

Sending device ("Vault111"):
![image](https://user-images.githubusercontent.com/30484238/96644790-8e62e500-12f7-11eb-9c95-899ba5a15d92.png)

### Potential reproduction steps
> I have not verified these, but I suspect the strange combination of steps (or some slight variation of these) may have triggered the error. I am not sure these exact steps will be able to reproduce the error.
1. Prerequisites: 3 devices, all in sync with the files in question, nothing in .stignore.
1. Initially, all devices have the files. Both the receiving and sending device are synced, as well as the 3rd device. 3rd device is initially off.
1. Delete files from the sending device. Let receiving device sync.
1. Add files to .stignore on the receiving device.
1. Add files to .stignore on the sending device.
1. Turn off receiving device.
1. Turn on 3rd device. Since the deleted files are in the .stignore on the sending device, the files do not get deleted on the 3rd device (this is expected of course).
1. Remove files from .stignore on the sending device. Let the 3rd device sync, which will delete the files.
1. Add files back on the 3rd device. Let the sending device sync, and this will re-add the files to the sending device.
1. Add the files back to .stignore on the sending device.
1. Add files to .stignore on the 3rd device.
1. Delete files from the 3rd device directly (not through syncing).
1. Turn off 3rd device.
1. Delete files from the sending device directly (not through syncing).
1. Turn on receiving device. The bug may now appear (I'm not certain if these steps will be able to reproduce the error).

### Failed attempts to resolve the situation
- Restarting both sending and receiving devices.
- Pausing/unpausing the folder or devices.
- Removing the files from both devices' .stignore files.

### What does resolve the situation
- Turn on 3rd device while both receiving and sending devices are on.

This may be related to #7036, although I'm not entirely sure. Thank you everyone for all your hard work to make Syncthing a great piece of software!

**Comment by imsodin** [comment]
Please share screenshots of the involved folder on both devices. Are any folders configured as send-only or receive-only?

**Comment by KRMisha** [comment]
The folders are configured as send & receive on both devices. This is what they look *after* the situation was resolved, but they looked the same while it was an issue (i.e. both were marked as "Up to Date"). One setting which is to note is that "Case Sensitive FS" is enabled on the sending device (only), for performance reasons.

Receiving device:
![image](https://user-images.githubusercontent.com/30484238/96748460-8e1a2680-1397-11eb-909b-aa9af482b494.png)

Sending device:
![image](https://user-images.githubusercontent.com/30484238/96748382-75aa0c00-1397-11eb-85cb-76a2101d39ca.png)

HTH :)

**Comment by imsodin** [comment]
Actually with disconnected devices involved and it resolving when you reconnect it, it is likely that what you see is the same as in https://forum.syncthing.net/t/ignored-folder-is-out-of-sync/15757 If you encounter the problem again, could you please follow the debugging steps taken in that forum thread. If it turns out to be the same, things are working as expected (it's also explained on the forum, please ask there if you have further questions), if not, please post the rest output and re-open this issue.

**Comment by BerndErnst** [comment]
I have the same issue
