### ISSUE TITLE
Theme Names and Error Messages Localization

### ISSUE THREAD

**Issue by BouRock** [syncthing/syncthing#7048]
There are some strings to make more localize.

- Theme names: "Dark", "Black", "Light", and "Default"
- Error message: "Error on folder "Default Folder" (default): folder path missing", if there are more messages, it can be better to make localize them too
- Action: "modified", "deleted",  Type: "file" in Recent Changes dialog (I am not sure there are more actions and types)

**Comment by AudriusButkevicius** [comment]
Most of these come from go code, operating system errors or even folder names (theme names are just folder names), so I don't think they can be translated.

**Comment by BouRock** [comment]
Of course folder names come from OS. My OS is not English so error message comes from Syncthing, I guess. If need correction for error message:
"Error on folder "{{folderlabel}}" ({{folder}}): folder path missing"

I could not find theme names as a folder in Syncthing. Maybe they can be embedded as a string.

**Comment by imsodin** [comment]
I think this is a valid enhancement request: Strings we generate in go code that reach the user could be localized (and also theme directory names could be added to translation strings and replaced in JS). I don't see why it's impossible per se (there's https://godoc.org/golang.org/x/text/message and possible other frameworks) or anything that speaks against it, principally. Of course practically it's a lot of work (and I personally would rather work on users not seeing error messages in the first place xD ).

**Comment by tomasz1986** [comment]
Something to be very careful about when translating code error messages is that the translation needs to be 1) always full, 2) correct, and 3) understandable. If not, it is better to just use English. I am only saying this, because I have seen a lot of software with poor/amateurish/partial translation of error messages, which essentially made them useless to the user.

**Comment by AudriusButkevicius** [comment]
How is this different from #4062?

**Comment by imsodin** [comment]
It isn't.

**Comment by BouRock** [comment]
This topic is not only related with Error Messages. What about theme names and Recent Changes dialog?

**Comment by AudriusButkevicius** [comment]
Sure, make a comment there, but the "translate all the things" ticket is that one.

**Comment by acolomb** [comment]
Actually #4062 doesn't talk about theme names at all?  I've proposed #8006 to fix just that aspect, inspired by the first try by @tomasz1986.

Just in case we'd need an issue to show up in the change log, this one could be retitled and reopened.
