### ISSUE TITLE
"has mismatching index ID for us" on almost every restart

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#7051]
Detected by terry and reported in https://forum.syncthing.net/t/has-mismatching-index-id-for-us-on-almost-every-restart/15767:

> Just noticed I’m getting a new index id virtually every time I restart a folder or restart St.
> 
> 1.11 rc-2

Fix incoming.

**Comment by tezfair** [comment]
This appears to still be happening on 1.12.1 rc1

**Comment by imsodin** [comment]
I'll need more details than that, and please create a new issue or forum topic for that, because the issue here was fixed (while you get the same symptoms, it's not the same problem).

**Comment by tezfair** [comment]
Literally added it to the forum as the email came through
