### ISSUE TITLE
web interface: Latest Change line in Folders section isn't updated

### ISSUE THREAD

**Issue by paolobenve** [syncthing/syncthing#7054]
v1.10.0, Linux (64 bit), in google Chrome 69.0.3497.81

 - what happened,

after making some change in a synced folder, the Latest Change line in the Folder pane isn't updated: it keeps showing the change when syncthing was started.

Nothing changes if either the page is reloaded, or if a rescan is made.

![syncthing](https://user-images.githubusercontent.com/1417508/96986388-dbc29a80-1521-11eb-8143-75f781742f59.png)

**Comment by calmh** [comment]
This change is the latest change *Syncthing* performed, so if you did something on this device that's not what it's going to show, yes?
