### ISSUE TITLE
Browser folder type

### ISSUE THREAD

**Issue by Fade78** [syncthing/syncthing#7058]
Situation:
People wants to share stuff on many devices. Some of those devices are solid, grounded stores that participate to data retention (size of disk) and data availability (in case of failure, those nodes are replicated). Other devices just can't be connected all the time or are too small to get all the files but they have access to the user, like phones.

It would be awesome, and I mean that would be a **killer feature**, if you could have a _share_ that is in fact a browser of an already existing share. You could download the files like any regular client/server app. You'll have the convenience and security of Syncthing but with the optimization of the capacity of the nodes (disk size, online avaibility (ex:NAS), user reachability (ex: phone)). Syncthing would replace many other apps.

**Comment by imsodin** [comment]
There's a ton of existing issues and forum topics on this issue:

https://github.com/syncthing/syncthing/issues?q=is%3Aissue+selective+sync  
https://forum.syncthing.net/search?q=selective%20sync  

There have been (attempts at) implementations of selective sync as a fuse fileystem (https://github.com/burkemw3/syncthingfuse)  
and for android (https://github.com/syncthing/syncthing-lite). There have been attempts at improving the current ignore system, parts of what has been discussed would probably also apply to your use case. The issue containing most of the information on that is https://github.com/syncthing/syncthing/issues/2491.
