### ISSUE TITLE
Use default ignore rules to exclude version-control object directories

### ISSUE THREAD

**Issue by hyiltiz** [syncthing/syncthing#7060]
It is generally not recommended to use Syncthing on folders that are also managed by version-control systems, such as git. However, the default ignore rule does not reflect that. It would be ideal if the default ignore rule for *every* shared folder has something like the following:

```
.git/**
**/.git/**
```
and same for other popular version-control systems such as Mercurial etc.

This would keep the tip of the worktree synced across machines, but not the version history (which is better done through the version control system itself, such as through `git fetch`). This would also prevent corrupting a directory containing a project, e.g. I have `~/Documents/Github` (which is also the default when Github for Desktop is installed), and I pointed Syncthing at `~/Documents/` so I do not lose my work. However, this frequently breaks something inside `~/Documents/Github/*/.git/`. Without a default, it is also tricky since adding a new device means you have to also set up proper ignore rules, or risk corrupting the git project folder in *every other connected device*. 

This is a major usability issue with a very simple solution (setting a sane default). I really hope this could be adopted.

**Comment by imsodin** [comment]
That's part of this existing issue:    
https://github.com/syncthing/syncthing/issues/837

**Comment by hyiltiz** [comment]
Thx! I did check out the issues first, but still somehow missed it.
