### ISSUE TITLE
Do not sync where >% files have changed

### ISSUE THREAD

**Issue by tezfair** [syncthing/syncthing#7097]
Can Syncthing have the ability to pause / stop / not sync a folder where the number of changes are greater than a predefined limit (%). 

Reason is to protect my offsite backup from a ransomware hit at the sending end. Although not actually happened, in theory, if the files at the sending end were being encrypted, those same files would then get synced down. I do have simple file versioning, however they would then be time stamped, and if there's 1000's, that's not practical to recover from.

**Comment by AudriusButkevicius** [comment]
Sorry but no, this doesn't make much sense, because when you start with empty folders, all the files are "changed" etc.
Also, if you have one file and that file changed, that would mean 100% etc, hence this is complicated to implement sensibly.

You can use versioning to try and fight ransomware.

**Comment by tezfair** [comment]
I disagree. Syncthing could monitor how many files are syncing within a time frame, eg, 20 minutes. It knows that a folder contains x number of files. It counts the number of files changed in a period to give a % change. then it stops.

Sure, an empty folder is going to kick it off, however it's a feature that can be enabled by the user rather than automatically.

But as I said in the request, I use versioning, but it's flaw is that I am unable to bulk rename files. I have seen ransomware hit a hits server and I worked out it was encrypting 90 files a sec.

I would prefer this to be opened for further discussion. As a member of a team of devs to close this idea because you personally don't want to consider it is not fair on other people that may find this to be useful.

**Comment by imsodin** [comment]
Well, then let me second closing. Not only do I believe something like this is out of scope for Syncthing, it's also not clear what exactly such a feature would do. Thus it's more of a use-case discussion, and such discussions are supposed to happen on https://forum.syncthing.net.

**Comment by ProactiveServices** [comment]
Syncthing's core function is continuous, automatic file synchronisation. It is not designed to be a backup system or an anti-virus solution. The documentation explicitly states that [it is not a backup system](https://docs.syncthing.net/users/faq.html#is-syncthing-my-ideal-backup-application).

If you need an anti-virus or backup system then you need to use software designed for that purpose, there are plenty out there.
