### ISSUE TITLE
File deletions are not being synced in newly shared folders

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7098]
I am not sure whether this is something recent or not, but I do not think that I had encountered anything like it before v1.11.x.

How to reproduce:

1. Create an empty folder on Device 1.
2. Add 1000 small text files to the folder on Device 1.
![image](https://user-images.githubusercontent.com/5626656/98466566-a8675780-2213-11eb-8578-5c7c6b5532ac.png)
3. Share the folder with 1000 files from Device 1 to Device 2.
4. Accept the folder on Device 2 and let it sync.
![image](https://user-images.githubusercontent.com/5626656/98466577-bc12be00-2213-11eb-8aab-f7f604d18997.png)
![image](https://user-images.githubusercontent.com/5626656/98466578-bf0dae80-2213-11eb-8f2c-e19695e79b46.png)
5. Delete the 1000 files from the folder on Device 2.
6. The two folders are stuck in the following state.
![image](https://user-images.githubusercontent.com/5626656/98466606-e9f80280-2213-11eb-9056-e4bfe61fae62.png)
![image](https://user-images.githubusercontent.com/5626656/98466608-ec5a5c80-2213-11eb-95be-77fc5ee224d3.png)

Please make sure to follow the steps exactly as I have written above. If the folder was already being shared between the two devices before adding the files to it, then the synchronisation is successful. I have only managed to make this happen when the files were added to the folder in the "Unshared" state.

Restarting Syncthing does make the folders finish the synchronisation.

**Comment by tomasz1986** [comment]
Also, probably related so I am not creating a new issue, but even just sharing a folder with pre-existing 1000 text files on both sides between Device 1 and 2 leads to this state.

![image](https://user-images.githubusercontent.com/5626656/98467083-caaea480-2216-11eb-8c80-0284476210bb.png)
![image](https://user-images.githubusercontent.com/5626656/98467086-cf735880-2216-11eb-8025-7195845ac2b4.png)

**Comment by imsodin** [comment]
I can reproduce. The problem is that new/unshared folders aren't handled in the cluster config from an index point of view. And when you then actually add the folder, we do send a cluster config to the remote, but do not get one in return as nothing changed from the point of view of the remote. Thus we never start sending indexes. We need to handle that like paused folders.
