### ISSUE TITLE
Add a html message to GUI when javascript is disabled

### ISSUE THREAD

**Issue by markmcb** [syncthing/syncthing#7099]
If the browser loading the syncthing web GUI has something like noscript blocking javascript, the user is presented with a blank page. It would be helpful if a fallback html message stated that javascript is required for the page to load correctly.

**Comment by calmh** [comment]
Is there anyone with Javascript disabled who is actually surprised by this though?

**Comment by markmcb** [comment]
Yes

**Comment by markmcb** [comment]
Aside from the scenario of simply not connecting the dots that JS is being blocked, if the user is using a text-based browser like _links_ the lack of JS results in a far more cryptic view (see attached screen shot).

<img width="1228" alt="Screen Shot 2020-11-08 at 15 07 40" src="https://user-images.githubusercontent.com/54813/98486792-328fcb80-21d4-11eb-9faf-a9cb5910901c.png">

**Comment by tomasz1986** [comment]
> Is there anyone with Javascript disabled who is actually surprised by this though?

I think that this is useful maybe not necessarily for those that disable JavaScript on purpose, but there are cases where a non-tech-savvy person fiddles around with browser settings (or extensions) ending up disabling JS by mistake :sweat_smile:. This is one way to make them aware of that.

I will try to push a fix for this issue shortly.

**Comment by tomasz1986** [comment]
@markmcb 
> Aside from the scenario of simply not connecting the dots that JS is being blocked, if the user is using a text-based browser like _links_ the lack of JS results in a far more cryptic view (see attached screen shot).

In order for a Web site to be nicely displayed in text-based browsers, you would have to start with a clean HTML code that needs neither CSS nor JS to work. CSS should be only used to decorate the site or arrange its structure, and everything that relies on JS should also only be added with JS. This is called progressive enhancement.

However, such an approach is impossible for an interactive Web application like Syncthing's Web GUI that cannot work without JS. While technically you could have a HTML stub and only add the JS-dependent HTML code dynamically later, it would require a complete rewrite of the GUI as it is right now.

I have added the no-JS warning in a way that it would be displayed at the very top, so your text-based browser should at least clearly show it first. It will still print the non-functional HTML code seen in your screenshot, but I do not think that anything can be done about it right now.

**Comment by markmcb** [comment]
@tomasz1986 that makes perfect sense to me. I definitely didn't mean to imply reworking the entire page. I think the message at the top will make it clear that the current environment is not adequate for a functional experience. Thanks!
