### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by zhangyatao** [syncthing/syncthing#7103]
### v1.4 compile error

**using goland compile ，but happend error,Does anyone know how to solve it**
go: downloading github.com/shirou/gopsutil v0.0.0-20190714054239-47ef3260b6bf
go: downloading github.com/syndtr/goleveldb v1.0.1-0.20190923125748-758128399b1d
go: downloading golang.org/x/text v0.3.2
go: downloading golang.org/x/net v0.0.0-20190827160401-ba9fcec4b297
go: downloading golang.org/x/crypto v0.0.0-20190829043050-9756ffdc2472
go: downloading gopkg.in/ldap.v2 v2.5.1
go: downloading golang.org/x/sys v0.0.0-20191224085550-c709ea063b76
go: downloading github.com/thejerf/suture v3.0.2+incompatible
go: downloading github.com/syncthing/notify v0.0.0-20190709140112-69c7a957d3e2
go: downloading golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: downloading github.com/lucas-clemente/quic-go v0.12.1
go: downloading github.com/rcrowley/go-metrics v0.0.0-20190826022208-cac0b30c2563
go: downloading github.com/willf/bloom v2.0.3+incompatible
go: downloading gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: downloading github.com/willf/bitset v1.1.10
go: downloading github.com/calmh/murmur3 v1.1.1-0.20200226160057-74e9af8f47ac
go: downloading github.com/jackpal/gateway v1.0.5
go: downloading github.com/ccding/go-stun v0.0.0-20180726100737-be486d185f3d
go: downloading github.com/golang/protobuf v1.3.2
go: downloading github.com/marten-seemann/qtls v0.3.2
# github.com/syncthing/syncthing/lib/api
lib\api\api_statics.go:41:20: undefined: auto.Assets
lib\api\api_statics.go:49:20: undefined: auto.Assets

**Comment by calmh** [comment]
Hi! Please read and follow the build instructions: https://docs.syncthing.net/dev/building.html

**Comment by zhangyatao** [comment]
Hi! I have read this article.
but the generated EXE file cannot be run by double clicking

**Comment by zhangyatao** [comment]
> Hi! Please read and follow the build instructions: https://docs.syncthing.net/dev/building.html
Hi! I have read this article.
but the generated EXE file cannot be run by double clicking
