### ISSUE TITLE
"Out of Sync Items" for all files containing questionmarks or double quotes

### ISSUE THREAD

**Issue by novoid** [syncthing/syncthing#7111]
Files that contain question marks or double quotes within their file name do not get synced.

### Does your log mention database corruption?

No.

### Description

 - which version of Syncthing and what operating system you are using
    - host A: Debian GNU/Linux stable running `v1.11.1, Linux (64 bit)`
    - host B: Android 11, running `v1.10.0 Android`
 - browser and version, if applicable
    - I don't think that this is relevant here (A runs Debian Firefox)
 - what happened,
    - files on host A are not synced to B
    - they are listed on A as "Out of Sync Items"
    - restart A and/or B does not change anything
    - no suspicious log output, no ignore pattern matches the files on both sides
 - what you expected to happen instead, and
    - said files are synced from A to B
 - any steps to reproduce the problem.
    - generate files on A that contain question marks or double quotes -> files do not get synced

If this is related to Syncthing Android (wrong repo), please correct me and I will re-submit.
If you need further data, please ask me.

**Comment by calmh** [comment]
Look at failed items on the receiving side to see the actual cause of them not syncing?

**Comment by novoid** [comment]
> Look at failed items on the receiving side to see the actual cause of them not syncing?

Excuse me, I don't know how to do this on Android. Can you give me a hint or a link to a description to do so? Thanks!

**Comment by imsodin** [comment]
Looks more like android storage restrictions. In principle they shouldn't apply, as we target sdk 28 and

> requestLegacyExternalStorage
> [...]
> The default value is: - false for apps with targetSdkVersion >= 29 (Q). - true for apps with targetSdkVersion < 29. 

but you never know what is actually happening on android. We'll soon be targeting sdk 29 and thus setting `requestLegacyExternalStorage`, maybe that will fix the problem for you.

In any case, nothing wrong with Syncthing here.
