### ISSUE TITLE
Use CRLF instead of LF for new lines in config.xml and .stignore on Windows

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7115]
Right now, Syncthing seems to always use LF for line endings in `config.xml` and `.stignore`. This is a problem in Windows when trying to edit those using the built-in Notepad, which until very recently had no support for other line endings than CRLF. Support for them has only been added in the very recent versions of Windows 10.

The problem is that when opening those files in Notepad under older (<= 1809?) versions of Windows 10 or any other older version of Windows for that matter (including also the newest Windows Server 2019), the content of those files is displayed in a long single line. This makes it basically impossible to review and edit.

I would like to suggest that these files should automatically revert to CRLF line endings when Syncthing is being run under Windows.

Ref: https://devblogs.microsoft.com/commandline/extended-eol-in-notepad

**Comment by calmh** [comment]
In the meantime, Wordpad is the traditional editor for LF support pre-Win-10. :)

**Comment by tomasz1986** [comment]
Yeah, although I personally would be worried to use WordPad to edit critical files (like `config.xml`) in case it mangles something on save :smirk:.

**Comment by beerse** [comment]
While msWindows (and predecessors) have used other line-endings since their beginning of time, they (the microsoft notepad team) are working on support for other (unix like) line-endings: https://devblogs.microsoft.com/commandline/extended-eol-in-notepad/

**Comment by beerse** [comment]
The way I read https://devblogs.microsoft.com/commandline/extended-eol-in-notepad/, is that from now on, notepad on mswindows does handle unix like line endings better than before. Hence, the need to alter the line ending based on the os.

Be noted: If it is changed in the transfer, best to look at the ftp-protocol that has an ascii and a binary way for transfer. As far ars I have used ftp since I'm online (since 1991) I cannot recall any ascii transfer working as expected.

On the other hand: If the configuration file is generated from scratch, use the os-specific way is accepted. And expect both ways all over the system since they can be the result of a cross-os transfer.

**Comment by anurnomeru** [comment]
I have a similar requirement. Can I set the EOL for all synchronized files?

**Comment by anurnomeru** [comment]
Especially the code, it can’t run normally when syncing from windows to linux

**Comment by calmh** [comment]
Transforming content is not going to happen, no; Syncthing is based on ensuring identical block checksums. (But config files should be in the local flavour.)

**Comment by Catfriend1** [comment]
Hi,

is LF still supported , beside the new CRLF format on Windows? I'm asking because my scripts convertToLf after modifying the config.xml on Windows.

**Comment by calmh** [comment]
Sure, we should accept any line ending on any platform. This is just about what we write out.

**Comment by beerse** [comment]
As calmh reports: cross-os applications should accept both dos-based ascii and unix-based ascii.
For every text file that is transfered and needs to be converted: on unix/linux I use the tools 'dos2unix' and 'unix2dos'.

The best thing to ask for at syncthing is to be able to use them in the transfer, based on some file-filter-rule.
For the file-filter It would be nice to use an external command too: Then you can use the tool 'file' which can do a fair job on realy checking what kind of file it is.
