### ISSUE TITLE
Ignore fsync errors when saving ignore files

### ISSUE THREAD

**Issue by melmatsuoka** [syncthing/syncthing#7117]
### Does your log mention database corruption?

No

### Include required information

SyncThing version: 1.10.0
OS: macOS 10.14.6
Browser version: Safari 14.0 (14610.1.28.1.10)
NAS: [Studio Network Solutions EVO 16-Bay NAS](https://www.studionetworksolutions.com/evo/#16bay)
NAS OS Version: 5.8.1.88
NAS uname -a: "Linux M9-NAS-EVO 2.6.32.59-evo #88 SMP PREEMPT Wed May 10 11:11:56 GMT 2017 x86_64 Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz GenuineIntel GNU/Linux"

### What happened

I’m running SyncThing 1.10.0 on a Mac mini (macOS 10.14.6), trying to add a new shared folder, which is residing on my Studio Network Solutions EVO NAS (mounted via SMB).

Every time I click “Save” on the “Add Folder” window, I get [this “operation not supported” error](https://d.pr/i/YI1PTF), apparently when ST tries to save the .stignore file.

When I have the folder opened in Finder, I see the .stignore file being created, but then it immediately gets deleted, momentarily replaced by an “.smbdeleteXXXXX” file, then it disappears altogether.

The “.stfolder” folder does get created in the shared folder, though, but it remains empty after clicking “Save”

I tried manually touch'ing the .stignore file first via Terminal, then tried to add the Shared folder again, but I still get the error in ST.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by melmatsuoka** [comment]
I was specifically told to open a ticket for this on Github by Jakob, and so I did:

https://forum.syncthing.net/t/saving-stignore-operation-not-supported-errors/15878

**Comment by The-Jag** [comment]
Hi to all,

I can confirm this bug in a similar NAS setup on macOS when the shared volumes are mounted by smb: the .stignore file cannot be stored properly.

The same volumes work well using afp (instead of smb).

Kind regards,

Lukas
