### ISSUE TITLE
Wrong theme on selection

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#7138]
### Does your log mention database corruption?
No
1.12-rc3
Please be sure to include at least:

 - which version of Syncthing and what operating system you are using
 - FF 83 both
Win10 : select Default theme => autoDisplays Dark 
Linux : select Default theme => Displays Default (only after F5)
What would happen: Display selected theme

**Comment by imsodin** [comment]
I don't understand what exactly the problem is, could you elaborate please.

**Comment by bugith** [comment]
The main is in Windows : selecting Default theme from another being yet set will switch to Dark theme (auto reload on "Save"  works OK)
On Linux we have to manually refresh (F5) after "Save" to see the effect of our selection was correctly set.

**Comment by calmh** [comment]
The default switch supports auto switching between light and dark depending on the current OS mode. Windows and macOS supports this when configured appropriately, typically switching to dark themes after sundown and switching back to light at sunup. At least that's what my systems do. Perhaps this is not supported in your Linux setup.

**Comment by AudriusButkevicius** [comment]
It's effectively down to the browser caching behaviour, some require a refresh, some don't.
