### ISSUE TITLE
Quic spamming address resolving

### ISSUE THREAD

**Issue by Oriann** [syncthing/syncthing#7144]
Syncthing 1.11.1, Windows 10 20H2
Synctrayzor

Syncthing spamming too much of quic info and changing ports very quickly, is it desirable ?

[AZBII] 18:13:26 INFO: quic://0.0.0.0:22000 resolved external address quic://*.16.81.43:57040 (via stun.syncthing.net:3478)
[AZBII] 18:18:36 INFO: quic://0.0.0.0:22000 resolved external address quic://*.16.81.43:35084 (via stun.syncthing.net:3478)
[AZBII] 18:23:45 INFO: quic://0.0.0.0:22000 resolved external address quic://*.16.81.43:49193 (via stun.syncthing.net:3478)
[AZBII] 18:28:55 INFO: quic://0.0.0.0:22000 resolved external address quic://*.16.81.43:27501 (via stun.syncthing.net:3478)
[AZBII] 18:34:05 INFO: quic://0.0.0.0:22000 resolved external address quic://*.16.81.43:2900 (via stun.syncthing.net:3478)
[AZBII] 18:39:14 INFO: quic://0.0.0.0:22000 resolved external address quic://*.16.81.43:60660 (via stun.syncthing.net:3478)
[AZBII] 18:44:24 INFO: quic://0.0.0.0:22000 resolved external address quic://*.16.81.43:60229 (via stun.syncthing.net:3478)
[AZBII] 18:49:34 INFO: quic://0.0.0.0:22000 resolved external address quic://*.16.81.43:27051 (via stun.syncthing.net:3478)

**Comment by AudriusButkevicius** [comment]
Seems like every 5 minutes? Not sure if you can call that spamming?

**Comment by imsodin** [comment]
Agreed, every 5 minutes isn't that much. However is this information useful to the user in general? Seems more like a debug level information to me.

**Comment by Oriann** [comment]
So then its problem in my router if I get that correctly, its switching port every 5 minutes and without some sense ?

**Comment by tomasz1986** [comment]
> Agreed, every 5 minutes isn't that much. However is this information useful to the user in general? Seems more like a debug level information to me.

I get the same messages logged. Maybe not exactly every 5 minutes, but quite often (5 times per hour?). I would not say that they give any useful information to the user.

**Comment by AudriusButkevicius** [comment]
It's the same usefulness as nat port mapping messages. This message effectively indicates that the process is working.

**Comment by calmh** [comment]
Well, it also showcases that the process *isn't* working, in that we're filling the discovery server with useless addresses due to non-cone NAT mappings... I thought we detected non-viable NAT situations and stopped doing this. Perhaps that was only when the port changed on every check, and this is slightly slower than that?

**Comment by AudriusButkevicius** [comment]
s/that/whether/

**Comment by calmh** [comment]
Right! So I’m not saying remove the logging but rather I think this behavior could be improved, for make benefit great discovery infrastructure etc.

**Comment by AudriusButkevicius** [comment]
I think what's happening here is we detected an ok nat type but the port doesn't stay mapped for too long in the router.

I am not sure what we should do in this situation.

**Comment by Oriann** [comment]
Shame is that quic has problem to hold port open for more than 5 minutes. TCP opens port and as long as syncthing is running it does not change. Checked my router settings but nothing is tunable for quic at this moment. Using OPNsense software...

**Comment by AudriusButkevicius** [comment]
What nat type has it actually detected?

**Comment by Oriann** [comment]
Here is info from log:

> [AZBII] 10:13:39 INFO: Detected 0 NAT services
> [AZBII] 10:13:39 INFO: quic://0.0.0.0:22000 detected NAT type: Symmetric NAT

**Comment by AudriusButkevicius** [comment]
Actually that's not a punchable nat type, so you're just getting a message every 5 minues because we check if the nat changed for any reason.

I guess there is no point notifying of the external address if it's not punchable anyway.
