### ISSUE TITLE
QUIC writes directly to stdout

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#7146]
Running on main I get lines like this in the Syncthing log:

```
2020/11/24 10:52:01 Failed to sufficiently increase receive buffer size. Was: 208 kiB, wanted: 2048 kiB, got: 416 kiB.
```

Grepping my `$GOPATH/pkg/mod` puts the blame on quic. I haven't looked into it at any further at all, thus keeping `needs-trage` for now. Likely introduced in https://github.com/syncthing/syncthing/pull/7139, thus `skip-changelog`.

**Comment by imsodin** [comment]
https://github.com/lucas-clemente/quic-go/issues/2929

**Comment by RubenKelevra** [comment]
Well, this doesn't really fix the underlying issue. Better to include the real fix:

https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size

**Comment by imsodin** [comment]
I don't know what "this" you are referring to, but this issue is about QUIC logging to the standard logger, which ends up directly in stdout instead of in our logging system.

The particular line mentioned as an example is about udp buffer size indeed. The new version of QUIC even prints a link to the wiki page you posted in the error message. However that's not something Syncthing can control, as adjusting it requires root privileges.

**Comment by bt90** [comment]
> However that's not something Syncthing can control, as adjusting it requires root privileges.

Syncthing *could* package a sysctl config file to raise the buffer size. But that would only make sense if we get hit by this.

**Comment by bt90** [comment]
@imsodin https://github.com/bt90/syncthing/tree/sysctl_udp
