### ISSUE TITLE
Dose not allow duplicate sync !!

### ISSUE THREAD

**Issue by joni73** [syncthing/syncthing#7163]
Hi,

I have two directoryes at same device
where i wanna sync same entitity.

Entity: myfiles

to C;/files/myfiles

and to backup device

D:/myfiles

You can not create backup entity
twice at same server!!!!

**Comment by calmh** [comment]
Indeed a folder can only live in one place, and this is not something that will likely change, ever. The other way to do what you want would be to support sync between local directories, which is another ticket here somewhere. In the meantime, syncing a folder to one place and using some other program to do sync between local directories is your best bet, sorry.

**Comment by joni73** [comment]
Jacob, think twice ! IT could Be enogh that Lival Nick name should Be
difrent but same id could Be used localy twice at difrent directoryes.
Useing others program could replace syncthing, use rsync instead. I use
syncthing to share user Holder at serveri, backup serveri, Android, ma
Windows. Syncthing IS convinient due rsync has some limitations. Syncthing
can Be better.

pe 27. marrask. 2020 klo 12.21 Jakob Borg <notifications@github.com>
kirjoitti:
