### ISSUE TITLE
Syncing stops, leaving incomplete files for no apparent reason, had to remove and re-add the receiving folder to resolve.

### ISSUE THREAD

**Issue by Tekwizz** [syncthing/syncthing#7170]
Hi!

I am new to Syncthing, and am thrilled! I was testing it on about 50 GB of files, syncing between 2 remote computers. Sending from one and receiving on the other (one way sync.) Several folders synced perfectly without issues. However when I tried syncing some mp3 and wma files in several folders, with a total of about 6,435 files, (totaling about 40 GB) the sync process seemed to get stuck when there were about 150 files incomplete. (About 335 megabytes) They showed in the folders as temporary syncthing files, with their full sizes but were not completing. I tried pausing on both computers, restarting, rescanning, checked that the files were not corrupt, but just wouldn't continue... I finally solved the problem by removing the folder set on the receiving machine, and re-adding it again, then it completed within a few minutes with no issue!

So I don't understand why it wouldn't complete those "temp files" and trying to "coax" it to continue wasn't helping. At first I thought they files maybe corrupt or not fully readable, but obviously that's not the case. Why would removing and re-adding the folder on the target machine cause it to finally complete?

BTW, it was in the Remote Devices section that it showed the sync was not complete, and I could click and see all the incomplete files. I looked in the log but saw nothing saying there was any issue. It just didn't attempt to complete those files anymore.

Thank you!

Versions:
Sending computer:  Windows 10 Home, 1803, 17134.1246, SyncTrayzor Version: 1.1.24, Synthing Version: v1.11.1
Receiving computer: Windows 7 Enterprise SP 1, Syncthing Version: v1.11.1 Build 2020-11-03, Chrome version 86.0.4240.198 (Official Build) (64-bit)

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
