### ISSUE TITLE
Request:  add ability to ignore binary executables

### ISSUE THREAD

**Issue by jpxor** [syncthing/syncthing#7172]
I was looking for a way to add executable files to my .ignore list, but there doesn't appear to be a way to do this.

**- how or why you think it is generally useful (i.e., not just for you):**
I'm not sure it would be, but it's possible others don't want executable files sync'ed?

 **- what alternatives or workarounds you considered:**
My current work around is to ignore everything in the directories where the binaries are located, then exclude the Makefiles from being ignored: 

(?d)*nto/arm/*
(?d)*nto/x86/*
(?d)*nto/x86_64/*
(?d)*nto/aarch64/*
!*nto/arm/Makefile
!*nto/x86/Makefile
!*nto/x86_64/Makefile
!*nto/aarch64/Makefile

**Comment by AudriusButkevicius** [comment]
Similar requests were raised before, for pictures vs videos etc, and we decided to go against this, as it's unbounded complexity and requires syncthing to become content type aware which we so far managed to avoid.
