### ISSUE TITLE
Folder up to date, machine out of sync, temp files exists.

### ISSUE THREAD

**Issue by orena1** [syncthing/syncthing#7173]
I have two machines, a windows (which is mostly the sender) and a Linux (which is mostly the receiver).
I set up 3 folder sync (total ~1.2TB) and went to sleep, it mostly worked but for some reason, I still see out of sync in the `Remote Devices` panel, the folder panels are all ok.

![image](https://user-images.githubusercontent.com/8983713/100767855-e87cbd00-3402-11eb-975e-71c653ca240f.png)

The folder sync is all **Up to Date** on both devices.
![image](https://user-images.githubusercontent.com/8983713/100767728-c4b97700-3402-11eb-849a-438f990d028c.png)

I click on the details in the windows machine to see what files are out of sync, and when I searched them on the Linux machine this is what I see:

![image](https://user-images.githubusercontent.com/8983713/100766823-c0d92500-3401-11eb-85b6-1b0f5eec2a63.png)

Which again is strange, as the folder status says that it is up to date. I tried to restart both software and it does not work.

Thanks

### Does your log mention database corruption?
No

windows server 2012
Kubuntu-home 5.4.0-56-generic #62-Ubuntu

**Comment by imsodin** [comment]
The global states don't match at all - there's clearly something amiss here. Likely related to index transmission. There's been some related fixes on main that aren't in v1.12.0 yet. Any mention in the logs that it "Failed to sync" some of these files?

You can try to start syncthing with the `-reset-deltas` option set, which will hopefully fix the problem.

**Comment by AudriusButkevicius** [comment]
I think this should be handled on the forums tho?

**Comment by orena1** [comment]
There are some Failed to sync:
```
[G63UW] 07:03:49 INFO: "OAM3" (****): Failed to sync 2 items
```
No specific info on what failed to sync.
Anyway, I think `-reset-deltas`  fixed the problem. 
Thanks.

**Comment by AudriusButkevicius** [comment]
Maybe it is, but maybe it's a solved bug, hence the debugging and understanding of it should happen on the forum, until we know what exactly needs fixing and how, then we can raise an issue with a detailed description of what goes wrong internally and what needs fixing.

Now it's just a never closable issue where it's not clear what the cause is, or how to fix it. For all that I know, you might disappear tomorrow and this issue will be dangling forever with nothing actionable.
