### ISSUE TITLE
Systemd unit does not start due to hardening options SystemCallArchitectures

### ISSUE THREAD

**Issue by Salamandar** [syncthing/syncthing#7175]
I'm on Debian Buster, hardware is ARM64 (Helios64). The SystemD unit does not start due to the SystemCallArchitectures=native option in the unit file.

Commenting this option is enough to make it work correctly.
Is Syncthing doing system calls to check architecture ?

**Comment by calmh** [comment]
What's the precise error that prevents startup?

**Comment by Salamandar** [comment]
Syncthing receives `SIGSYS` as per systemd specification (https://www.freedesktop.org/software/systemd/man/systemd-system.conf.html)

```
Dec 02 21:52:26 salamandar.fr systemd[1]: syncthing.service: Main process exited, code=killed, status=31/SYS
```

**Comment by Salamandar** [comment]
Another issue on the subject was closed due to inactivity : https://github.com/syncthing/syncthing/issues/5449

**Comment by calmh** [comment]
That other issue is something else. Are you actually running an arm64 Syncthing? What does `uname -a` and `syncthing -version` say?

**Comment by Salamandar** [comment]
Yeah, I think you're right. I was using an arm64v7 binary on an arm64v8 hardware. Didn't think that would be a blocking point, as the arm ISAs usually are backward compatible.
