### ISSUE TITLE
Active connections min/max setting

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#7176]
This is a draft for a feature to handle the following two use cases.

1. I have a lot of low powered devices and want them to communicate in (something that feels like) a full mesh, but without the overhead of each device keeping a hundreds or thousands of connections running.

2. I have a lot of clients (>1000) connecting to a small number of servers (<10), for load balancing purposes. Clients should automatically balance connections over the servers in question so they can handle one going down, without ending up with too many clients connecting to any given server, potentially overloading it.

Currently this is difficult because while it's easy to configure full mesh it's difficult for Syncthing to scale to it. The client-server example requires some fancy configuration management to direct clients to specific servers, and possibly reconfiguring them once a server goes down.

Now lets assume we had two configuration options available:

- Minimum active connections (minC)
- Maximum active connections (maxC)

Where minC <= maxC and both default to unbounded / infinitely large. These control the connection service in terms of establishing outgoing and incoming connections. Specifically,

- The connection loop runs as usual to establish outgoing connections while the number of active connections is less than minC. Once minC has been reached we no longer attempt to establish further outgoing connections.
- Incoming connections are accepted as normal as long as we have fewer than maxC connections. Once maxC is reached we stop accepting further incoming connections. (Similar to a paused device.)

For some fairness to work out we also make one adjustment to the connection loop:

- Every time we run the connection loop, the order of devices we connect to is shuffled.

Our two use cases above then become quite simple.

For case one we configure all our devices for full mesh and set minC=10, maxC=20. Each device will end up connected to between ten and twenty other devices. (It's possible that this might result in partitioned sets of devices, but it doesn't seem especially likely. Some calculations could probably be done on how to set minC/maxC for a given cluster size to achieve a certain probability of it being fully connected...)

For case two with for example 1000 clients and 5 servers we want about 200 connections per server. We also want to handle one server going down, leaving us with 250 connections per remaining server. We can configure the servers to connect to all clients, and clients to connect to all servers. Clients get maxC=1 -- keep precisely one active connection. Servers get minC=200, maxC=250. Hence the servers will attempt to "grab" 200 clients each, clients will attempt to establish one connection to any server. Given randomization it's likely that the distribution ends up fairly even, but it's possible some servers get up to 250 clients and some other servers fewer than 200. If a server goes down there is "space" for the clients to migrate to another server.

**Comment by acolomb** [comment]
At first read: brilliant idea!

**Comment by AudriusButkevicius** [comment]
I don't think the number of active sockets is the scaling problem, I think managing the database per device is, and having randomly shuffled devices we connect to doesn't help in any way, so I am not sure what this really tries to solve.

**Comment by calmh** [comment]
Oh, connected devices is *absolutely* the scaling problem. Not the TCP socket itself obviously, but the need to shuffle metadata back and forth and the resulting database updates for any update. Stale data for unconnected devices take up some space on disk (but we've reduced it a fair bit with the dedup indexing stuff) but carries a very small cost at runtime, comparatively.

**Comment by AudriusButkevicius** [comment]
What exact "metadata shuffling" are we talking about? Which part of it doesn't scale?

**Comment by AudriusButkevicius** [comment]
What exact "metadata shuffling" are we talking about? Which part of it doesn't scale?

**Comment by imsodin** [comment]
Neat idea.  
I guess the second example is a case where external requirements say that it needs to be centralized/clients mustn't see each other. Otherwise there's no benefit in making it centralized, you could also go for full mesh and have clients with e.g. 10/20 and servers with 200/250 (assuming a beafyness differential between clients and servers). I'd expect this to improve load-sharing over a centralized solution.

> What exact "metadata shuffling" are we talking about? Which part of it doesn't scale?

I think it's mainly index updates from every device for every item that changes across the cluster. There's some other stuff (download progress (which is also kind of indexy), remote paused folders, ...) but that's less problematic (not involving db).

> [...] having randomly shuffled devices we connect to doesn't help, as over time we'll still hit most of them and store their index, so I am not sure what this really tries to solve.

That indeed reduces the effectiveness of the delta-index-machanism, probably by a lot if numC << totalDeviceNum. Might be alleviated by some mechanism to first try to connect to devices that have been previously connected, and only connect new devices if you can't reach `minC` otherwise. That will influence topology connection arguments though - which we haven't really dived into yet :)

**Comment by AudriusButkevicius** [comment]
So sure, accepting indexes is probably the most costly part of this, but how costly is it compared to the actual transfer? I guess I'd like to see the numbers justifying the benefit of this, as it feels like a foot gun and a crutch at the same time for people who don't want to think about topology.

Also, this can cause issues, where you have 4 devices, maxC is 2, you get two clusters of two, etc, or maxC is 3, you form a friendly circle of 3 and leave the last guy stranded by himself.

**Comment by calmh** [comment]
It's very, very costly and I've done both the benchmarking and the troubleshooting over the years. You can set up your own thousand device cluster to satisfy your curiosity. I can very much assure you that the people running thousand-plus device clusters *do* think about topology, but thinking is not always enough -- you also need the tools to be able to build the topology.

Of course someone can break their home cluster by misconfiguring it. As if that is different with any other config option.
