### ISSUE TITLE
Pending devices and folders should have an optional expiry date

### ISSUE THREAD

**Issue by acolomb** [syncthing/syncthing#7179]
Currently pending device or folder notifications stay active basically forever.  For folders no longer offered, there is #5187 to stop showing them.  In addition, there should be an option to set a maximum age for such notifications.  It would be an opt-in setting of the general configuration section, with zero as default value meaning "never expire" (similar to the watch interval setting).  Other values could be given in hours or days to enable the feature.  If the observed timestamp is older than the configured age, the notification just disappears.

Implementation wise, this could live in the backend, or just a check within the GUI - to be discussed.  The latter would need a separate endpoint to "dismiss" pending notifications instead of ignoring or accepting them (which is a useful thing in itself).

**Comment by AudriusButkevicius** [comment]
I agree for stuff that is no longer offered, we should not show it, but for everything else, the user should action these things, so I disagree.

You haven't actually explained why would anyone want this.

**Comment by acolomb** [comment]
> You haven't actually explained why would anyone want this.

Let me give an example: User A has several devices, and opens the GUI very seldomly on some of them.  User B wants to share something to A and gets told the wrong device ID W by accident.  They notice the mistake and B removes the wrong (not yet accepted) device W and adds the correct ID.  Now the notification "B's device wants to connect" stays forever on the wrong device W.  When User A looks at the GUI later, the notification shows a long outdated intention.

Arguably not many users will opt-in to the feature, but those who like cleanliness might welcome the timed automatic cleanup to more easily see what's still relevant.  I don't think it needs a very complex implementation, so I think it's still in proportion to the (small) benefit.

**Comment by AudriusButkevicius** [comment]
Both sides know there was some screw up, so there are no surprises there that need machine intervention.

I'd rather not have the code for this, as this only affects 0.01% of the user base, happens 0.01% of the time, yet the code will be there forever

**Comment by acolomb** [comment]
Part of my argument was that it's not a single click if you're not already signed into the GUI of some device.  I think many people almost never look at the GUI, be it on an unattended NAS for example or one of my colleagues who don't really get this whole Syncthing at all but are just happy the folders are always in sync.

But I see your point, let's just hear some other opinions if this would be desired.  I don't have any strong ambitions here, just that my planned solution to #5187 would already get us very close to allow this.  So more of a "what else could we do with this code" suggestion :-)

**Comment by AudriusButkevicius** [comment]
If you are not signed in, and not in the UI, whether the notification is there or not does not matter to you.

I think looking for "what else you could do" is not the right approach.

**Comment by acolomb** [comment]
FWIW, I think the amount of (non-advanced) options is perfectly fine and well organized.  IIRC it was studies by the US Air Force that, while searching for the perfect one-size-fits-all pilot seat, concluded that having knobs for personal preferences is the only way to accomodate for every possible user.  So striving for an absolute minimum of options is not constructive either.  Read this as a compliment, I don't want to convince you of anything.

**Comment by calmh** [comment]
I also don't think we need this.

**Comment by dhs-rec** [comment]
Just stumbled accross this as I've accidentally connected some devices to an 80+ device cluster yesterday (in an automated way, using Puppet). I now have those 2 or 3 devices show 80+ pending devices and there's now way to remove those requests from the GUI. Unfortunately, one now has to scroll all the way down to see the shared folders. Please reconsider this request.

Or, alternatively, provide REST API endpoints for clearing the lists and/or removing single devices/folders from the pending lists.

**Comment by AudriusButkevicius** [comment]
The dismiss button in the UI calls the rest API to do that, so the API os already there.

**Comment by acolomb** [comment]
IIRC there is no Dismiss button, only Ignore or Add.

Pending folders are removed automatically upon connection when no longer announced.  For devices we can only define an expiration interval.

I agree that a "Dismiss" action would be preferable as an alternative to "Ignore".  I don't want my config spammed with ignored device IDs that only tried to connect once.  If the same device tries to connect again a year later, one could wait for a notification because the ignore entry is long forgotten.

Do you think such an API action would make sense?  Possibly also for pending folders?  I can make a PR if the functionality is desired.

**Comment by dhs-rec** [comment]
I see "Add Device" and "Ignore" buttons. I also see no REST API endpoint in the documentation that would do this. The workaround I found so far is to send a `/system/reset`, but that also results in a complete rescan so it's suboptimal.

**Comment by imsodin** [comment]
Functionality to remove pending folders/devices in the rest api is definitely desirable.

**Comment by AudriusButkevicius** [comment]
I am fairly certain we have endpoints for this, they might be undocumented.

**Comment by acolomb** [comment]
> I am fairly certain we have endpoints for this, they might be undocumented.

You [once mentioned](https://github.com/syncthing/docs/pull/498#issuecomment-601084158) that endpoints to mutate the pending stuff would be nice, but we didn't discuss it further and AFAIK nobody added them.  I'll look into it as time permits.
