### ISSUE TITLE
Can I compile for mt7621 router

### ISSUE THREAD

**Issue by xiangfeigao** [syncthing/syncthing#7181]
### Include required information

Please be sure to include at least:

 - what problem your new feature would solve 
  Compile a bin that router can use
 - how or why you think it is generally useful (i.e., not just for you)
I have a ralink-mt7621-pbr-m1 with a hard disk. It is most convenient to use it as a backup disk
 - what alternatives or workarounds you considered
 I like   you

Please instruct me how to achieve it.Thank you.

**Comment by calmh** [comment]
Looks like a MIPS device so i expect our mips builds should work, or you can try yourself.

**Comment by xiangfeigao** [comment]
it is mipsel. I have done.

**Comment by calmh** [comment]
Please try the mips builds there are. If you run into a specific issue, please let us know.
