### ISSUE TITLE
Add a trouble-shot center

### ISSUE THREAD

**Issue by HaujetZhao** [syncthing/syncthing#7194]
### Include required information

In daily use, some troubles may appear: 

* Missing folder markor due to cleaning app deleting folder markor
* Filename too long so that it can't be synced to another device whose OS differs
* Lack of space due to to many backup files
* ...

When one of problem jars, the sync won't finish. 

Normally, users need to explore the log to know the exact problem, and the handle it by hand. Like: 

* If it is the name too long, locate the file, rename it. 
* If it is the folder markor missing, check out the sync folder, make sure it's mounted correctly, create the *folder markor* folder. 
* If it's the backup file filled the disk space, then clean some of the big backup files. 

If syncthing can provide a trouble-shot center page, providing convinient one-click tools like **Rename the long name file** ,**Open the sync folder to check** ,**Recreate the foldor markor** , users can decently shot these troubles.

**Comment by calmh** [comment]
I think in cases where we can automatically figure out the correct solution we can just do it. However the mentioned things are all cases without an obviously correct solution, where the user needs to take action on their own. And the issues are already shown in the gui...

**Comment by uok** [comment]
@HaujetZhao, users can look at the [documentation](https://docs.syncthing.net/) for more help. If they have additional questions, they can search the [forum](https://forum.syncthing.net/)

**Comment by HaujetZhao** [comment]
> I think in cases where we can automatically figure out the correct solution we can just do it. However the mentioned things are all cases without an obviously correct solution, where the user needs to take action on their own. And the issues are already shown in the gui...

Of course the actions to solve the problems varies. The trouble-shot center is not ment to provide a thorough solution center, it's just provide a decent, convinient one-click support to solve some easy problems, so that users won't need to do the trifles (things like locating file address in explorer) if they just want to perform the simple solution in the panel (like creating a folder markor, renaming a long name file, renaming a file with invalid characters). 

It's just like upgrading to electric-teethbrush from traditional-teethbrush. 



> @HaujetZhao, users can look at the [documentation](https://docs.syncthing.net/) for more help. If they have additional questions, they can search the [forum](https://forum.syncthing.net/)

I'm sure this can get things done, and I just expect the process could be more concise and direct (I'm jolly not fancy of checking problems using file explorers), because some fussy operation do can be done by one click.

**Comment by AudriusButkevicius** [comment]
I agree with @calmh, all of the things you listed need manual user interaction, the errors are clear and visible, and where the user performs the corrective action is irrelevant.

I feel this would be as useless as the windows troubleshooting guides, as all of these problems are contextual and you need to see the context to resolve it sensibly.

It's a `won't fix` and a `close` from me.

**Comment by imsodin** [comment]
I agree with the general sentiment that there's potential to make some states and their resolution more understandable and simple to the user. However that's not a simple matter of creating some "center", but of identifying and studying issues, possible resolutions and then UX considerations. This is way too broad a topic (respectively even only loosely connected topics) for a github issue. A forum topic is an appropriate venue to start the discussion and maybe end up with an actionable item: https://forum.syncthing.net/
