### ISSUE TITLE
In Recent Changes, the Device column is empty

### ISSUE THREAD

**Issue by davidtabernerom** [syncthing/syncthing#7197]
> Syncthing version: v1.12.0 "Fermium Flea"
> Browser version: Mozilla Firefox 83.0 (just updated, also happened in 82.x)

When I am syncing folders between my computers, in the `Recent Changes` window, the `Device` column is empty. Image:

![imagen](https://user-images.githubusercontent.com/16870364/102217112-65686600-3edc-11eb-9fe5-70368779c8d4.png)

This is happening only in the PC version, while it is still working as expected in my Android device.

I believe everything else is working properly, but I am not sure if there is any extra consequence.

I have no idea how this happened nor how to reproduce, it just suddenly happened. I have been using it for some months and that were shown back then.

Any idea how this happened or how to solve it?

**Comment by imsodin** [comment]
Already fixed by https://github.com/syncthing/syncthing/pull/7185

(As far as I am aware this has only been reported on the forum, not the issue tracker before, thus not a duplicate).
