### ISSUE TITLE
Removing a folder and re-adding it again (untrusted) makes it not sync until restart

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#7198]
Most likely because the other side has cached the fact that we already had index information and won't send it again, even though we've dropped our index data.

**Comment by imsodin** [comment]
I am unable to repro. What I did:

1. Have a folder with a few files and dirs in sync between devices A and B - connection active.
2. Remove the folder on A.
3. Readd the folder on A with same ID but pointing at a new, empty path.

Result: Files get synced.

What did I do differently?

**Comment by calmh** [comment]
So, in my case this was an untrusted folder, being removed and then rm-rf:ed on the untrusted side because it had become full of crap, then re-added. I don't think that should be matter? Will retest.

**Comment by BeayemX** [comment]
Maybe the problem is related to #7076 ?

**Comment by calmh** [comment]
(This happened again yesterday, again with an untrusted folder, so it's real and still there. Still requires investigation.)
