### ISSUE TITLE
Enhancement Idea:  Secure HTTP Tunnelling through SyncThing

### ISSUE THREAD

**Issue by EternityForest** [syncthing/syncthing#7203]
One very useful thing to be able to do, would be to remotely admin a SyncThing server in a secure way, without needing complex manual setup, domain names, or the like.  

It is slightly out of scope and tangentially related, but if SyncThing could act as an encrypted tunnelling HTTP proxy, a lot of interesting things become possible.

Instead of having to set up a domain name, static ip, or the like, or manage self-signed certificates, you would just use the UI to configure an HTTP service for sharing the same way you share a folder, and on a remote machine, access that service at  serviceName.<NODEID>.localhost, securely proxies through your local SyncThing service.

Alternatively, services could be independent of any particular NodeID, so you would just go to <SERVICEID>.localhost, but that sounds like it would require a bit more work on the discovery server.

One is that you could share the admin WebUI of SyncThing itself with specific other nodes.

but beyond this, you could also share any other service, like HomeAssistant, NextCloud, or Node.red.

This kind of VPN functionality isn't *directly* related to file synchronization, but it does use some of the same UI and network primitives, and is useful in a lot of the same scenarios, and benefits from the same kind of trust infrastructure you have by linking two nodes as SyncThing does.

It's easy to imagine, say, a web-controlled jukebox with a synced music folder, or a security camera with a synced pictures folder, or an old Android phone used as a smart display, which would need both remote control and remote file sync.

Beyond that, if it were possible without excessively loading down the discovery servers, a fully public "Share with the whole world" option, would allow for lots of other possibilities where you want to give a few people access to something, but don't need a proper web address.

This would also somewhat cover the use case of #2633, public sharing, as one could implement it themselves with their web server of choice.   

It's obviously not the same as "Real" public sharing, because it's not synced, but web browsers have their own caches and offline-first support anyway these days, so in practice this might be a little more powerful, especially since public uploads are possible.

It would also partially cover the now-closed "SyncThing Messenger" use case, as one could use it for any self-hosted messenger they wanted, especially now that WebRTC makes that easy to build as a simple web app.

Another alternative implementation which might be more on-target for SyncThing, without trying to support any "public" use cases, would be to directly proxy raw TCP sockets, with a configurable localhost port on the client side.

That would also allow XMPP, MQTT IoT, SSH, and the like to be tunneled, and would better support SyncThing's current focus on internal/private sharing, which is probably 99% of IRL uses for this.

**Comment by AudriusButkevicius** [comment]
This has been discussed before and the answer is the same.
Sorry but no, syncthing is not a proxy/tunnel, it's an application that deals with files.

You can already have a pretty safe tunnel using SSH.
