### ISSUE TITLE
Windows reserved names are still allowed (and created) in folder paths

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7210]
1. Open the Add Folder window.
2. Use an illegal name in the path, e.g. `C:\NUL`.

![image](https://user-images.githubusercontent.com/5626656/102609527-fc4c5100-416e-11eb-971e-e61eabea80f9.png)

3. Click "Save".
4. A new folder `NUL` has been created in `C:\`.

On the one hand, I think that it is fine for Syncthing to accept such a path if the "invalid" folder already exists in the system. However, I do not think that Syncthing itself should be allowed to create folders with reserved names. Right now, the reserved names are not allowed in folder names themselves, but they seem to still be accepted in the path.

Related: https://github.com/syncthing/syncthing/issues/7075

**Comment by imsodin** [comment]
I vote for "wont-fix" - this is just too much work for a tiny, if any improvement. If a user explicitly asks for an invalid path, it's fine to give it to them.  
If we just reject the config, saving the config will fail, a http error gets logged and the config reverted. What the user sees is that the folder they just created isn't there. So we'd have to have UI elements to explain the issue to the user and re-opening the folder edit modal with the previously added settings. All just for the case a user uses the one single thing, that windows hates but still allows.

**Comment by tomasz1986** [comment]
> I vote for "wont-fix" - this is just too much work for a tiny, if any improvement. If a user explicitly asks for an invalid path, it's fine to give it to them.

Yeah, but the same can be said about creating a folder named `NUL`. Even if explicitly named like that, Syncthing will not allow it to be created. What is the difference here? Why is there no need to block an "invalid" path, but there is a need to block an "invalid" folder?

**Comment by imsodin** [comment]
The thing I did recently was about auto-accepted folders, and I decided to do it there for two reasons:
1. There it is Syncthing that creates a file path from external input (folder id and label provided from remote) without user input.
2. The fix was less work than arguing about whether to fix it or not :)
