### ISSUE TITLE
Encrypted folder with password on untrusted device produces gui errors. Syncing not possible.

### ISSUE THREAD

**Issue by gnubytes** [syncthing/syncthing#7213]
# Does your log mention database corruption?
Before issue: No
After replicating issue: No
Anytime During or After Replcation: No

# Include required information

Syncthing Version: v1.12.0 64-bit
Operating System: Windows 10 Pro 64-bit (19.09 - build 18363.1139)
Browser and Version: Google Chrome, 87.0.4280.88 64-bit

# What Happened
When trying to encrypt a folder on an untrusted device ("Do-VPS" - a Digital Ocean VPS) syncthing produces the errors below. I followed guidance without luck at https://docs.syncthing.net/branch/untrusted/html/users/untrusted.html. This documentation appears to be outdated as the config.xml format has changed for the password field.  

**Screenshot A**
This screenshot is the error that is produced in the web browser (Chrome) by syncthing after going to device (DO-VPS) under Actions/Advanced/Device "DO-VPS" under Advanced Configuration and selecting checkbox "Untrusted".
![Screenshot A](https://imgur.com/y5oEsHg.png)

This screenshot is the error I receive after I leave the "Untrusted" selection from Screenshot A above and go into the syncthing configuration file (C:\Users\merlin\AppData\Local\Syncthing\config.xml) and add a password to the specific folder mentioned in the error for the appropriate device (DO-VPS) as denoted below:

**Screenshot B**
![Screenshot B](https://imgur.com/Vae0tER.png)

```
<folder id="abcde-00001" label="Bizzys" path="C:\Syncthing" type="sendreceive" rescanIntervalS="3600" fsWatcherEnabled="true" fsWatcherDelayS="10" ignorePerms="false" autoNormalize="true">
        <filesystemType>basic</filesystemType>
        <device id="TRUSTED-PEER-ID" introducedBy="">
            <encryptionPassword></encryptionPassword>
        </device>
        <device id="UNTRUSTED-PEER-"DO-VPS" introducedBy="">
            <encryptionPassword>password</encryptionPassword>
        </device>
        <minDiskFree unit="%">1</minDiskFree>
        <versioning>
            <cleanupIntervalS>0</cleanupIntervalS>
        </versioning>
        <copiers>0</copiers>
        <pullerMaxPendingKiB>0</pullerMaxPendingKiB>
        <hashers>0</hashers>
        <order>random</order>
        <ignoreDelete>false</ignoreDelete>
        <scanProgressIntervalS>0</scanProgressIntervalS>
        <pullerPauseS>0</pullerPauseS>
        <maxConflicts>10</maxConflicts>
        <disableSparseFiles>false</disableSparseFiles>
        <disableTempIndexes>false</disableTempIndexes>
        <paused>false</paused>
        <weakHashThresholdPct>25</weakHashThresholdPct>
        <markerName>.stfolder</markerName>
        <copyOwnershipFromParent>false</copyOwnershipFromParent>
        <modTimeWindowS>0</modTimeWindowS>
        <maxConcurrentWrites>2</maxConcurrentWrites>
        <disableFsync>false</disableFsync>
        <blockPullOrder>standard</blockPullOrder>
        <copyRangeMethod>standard</copyRangeMethod>
        <caseSensitiveFS>false</caseSensitiveFS>
        <junctionsAsDirs>false</junctionsAsDirs>
    </folder>
```

# What you expected to happen
Expected no Syncthing GUI errors preventing syncing. The untrusted device should accept an encrypted file and by SSH'ing into the DO-VPS server, I should see an encrypted file. 

# Steps to Reproduce the Problem
Begin with a trusted peer-to-peer syncthing connection. In web browser (latest chrome), go to syncthing GUI (http://localhost:8384). Then go to Actions/Advanced/Device "UNTRUSTED-PEER") scroll to bottom of selection list and select "Untrusted". 
Restart syncthing through web GUI. Wait for error. Click ok at error. Go to C:\Users\"user-name"\AppData\Local\Syncthing\config.xml and add password to the UNTRUSTED-PEER-ID device. This produces the second error - see Screenshot B. 

Thank you for your time.

**Comment by imsodin** [comment]
The untrusted feature previews is **not usable in v1.12.0**, and there's still known bugs in v1.12.0-rc.1. You still must use nightlies to test it. For more information and to get help/report problems, see https://forum.syncthing.net/t/early-testing-for-untrusted-encrypted-devices/15873
