### ISSUE TITLE
LAN sync throughput regression

### ISSUE THREAD

**Issue by PrototypeNM1** [syncthing/syncthing#7218]
### Does your log mention database corruption?

No.

### Include required information

Windows 10
Syncthing 1.12.0

Syncthing's LAN sync throughput has regressed. The throughput seems to be capped by the internet upload speed (5Mbps), but Syncthing is directly connected (confirmed by local IP) to the other device.

Previously Syncthing would transfer at a throughput closer to the LAN's limits (100s of Mbps).

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
