### ISSUE TITLE
make a hook on new sync 

### ISSUE THREAD

**Issue by angryjk** [syncthing/syncthing#7222]
Hello team! I am intrested in such feature like:
1 When new changes made in file hook to remote server.

**Comment by calmh** [comment]
Duplicate of #5601 maybe?

**Comment by angryjk** [comment]
> Duplicate of #5601 maybe?

Hi calmh! Thank you for fast responce. Have not tested windows cli! But almost yes. Maybe i should share more toughts. Will tr y to make it in next message.
