### ISSUE TITLE
Acer Spin 5 hangs up after hibernation when syncthing is running

### ISSUE THREAD

**Issue by npapnet** [syncthing/syncthing#7225]
##  Acer Spin 5 specific bug
 - Syncthing version: 1.12
 - operating system: Windows 10 home (fully patched)
 
For the past couple of months or so, I've been experiencing a strange problem with my acer Spin 5. I've noticed that when I let it go to sleep mode (or hibernate), **sometimes** it would not manage to boot up again. 

I've managed to track the issue when syncthing is up and running. 

## More details on how I came to the conclusion

Initially, I thought it was some sort of corruption through the updates of windows. I've had the Acer Sping 5 for 3 years, and it worked with syncthing without a problem all this time. I need to note that because the Spin5 is my carry around laptop, to save some time during boot, i've had it disabled at boot, and occasionally I start it up. However, I never had a problem before (I use syncthing to sync between at least 5 pc's and various operating systems without a problem).  That is the reason, why I didn't suspect syncthing earlier.

At some point about a couple of weeks ago, I decided to refresh the Windows 10 installation to see if that fixed things. I did the full refresh, and I slowly started to add things. Then last week the same problem happened  (I would try to boot windows from sleep mode, but nothing happened apart from the keyboard lighting up).  For the past week, I've avoided using syncthing, and the behaviour was as expected.  Then yesterday, I rebooted the computer, started syncthing, and then let it go to sleep mode, and I couldn't start it again (I have to use the power button to power down the pc and then restart it). 

I understand that this is not very insightful, but I'd be happy to provide any logs that might be helpful.

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by npapnet** [comment]
Thank you. I'll try that.
