### ISSUE TITLE
Conflict of files in different directories

### ISSUE THREAD

**Issue by Revertron** [syncthing/syncthing#7233]
### Does your log mention database corruption?

Nope

### Include required information

Syncthing 1.12.0 in SyncTrayzor on Windows.

Different files in different directories are considered by Syncthing as conflict. See screenshot:

![hRuSZG](https://user-images.githubusercontent.com/105154/103153263-a6d7fb80-478f-11eb-82dc-33ad57baec54.png)

**Comment by imsodin** [comment]
The conflict resolver is a feature of SyncTrayzor - thus issue reports about it go there: https://github.com/canton7/SyncTrayzor

**Comment by Revertron** [comment]
But is it Syncthing that sees that fantastic conflicts?

**Comment by imsodin** [comment]
No, Syncthing only creates conflict files, it does not link any files. And generally, for questions use https://forum.syncthing.net/ please.
