### ISSUE TITLE
Check if filesystem=BTRFS and change SQLite mode to WAL

### ISSUE THREAD

**Issue by zilexa** [syncthing/syncthing#7239]
With a CoW filesystem like BTRFS, performance can degrade. One workaround is to disable CoW for the Syncthing database folder for example `chattr +C $HOME/.local/syncthing`. But this way you also lose some BTRFS features. Plus the user needs to know about this setting, most don't.

A better solution, one that is also more performant would be to change the SQLite database mode to _Write-Ahead Logging_ (WAL).

A user can do this manually, by stopping Syncthing, opening the sqlite database and changing the mode. 
This request is to implement the following:

> 
> Condition:
> A. When starting Syncthing for the first time.
> B. When Syncthing is started and there is no database file.
> 
> IF:
> Check if filesystem is BTRFS.
> 
> Then:
> Create database with `PRAGMA journal_mode=WAL;`

Reference:
https://wiki.tnonline.net/w/Blog/SQLite_Performance_on_Btrfs

**Comment by wweich** [comment]
Syncthing doesn't use SQLite.

**Comment by zilexa** [comment]
OH! I thought it did. In that case, ignore this request. Not sure if I should use Chattr +C on the folder then, or if the database of Syncthing is already using some kind of method similar to Write Ahead Logging.

**Comment by AudriusButkevicius** [comment]
It's level db, so it creates new files for writes, and eventually merges them, similar to WALs.
