### ISSUE TITLE
Add an advanced configuration setting to define folder scanning order

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7240]
I think that it would be nice and useful to have an option to define folder scanning order.

What I mean is that I would like to be able to have my folders scanned from smallest to largest. The reason is that on slow hardware with a lot of folders, right now large folders "block" scanning of small ones. This is especially true when starting Syncthing, as all folders need to be processed in order to even begin the actual synchronisation. Depending on the implementation, other possible scanning order options could be folder type, number of shared devices, etc.

The only alternative right now is to set `MaxFolderConcurrency` to `-1` (or some other large number), but this has its own drawbacks, such as very high I/O load. I have personally experienced plenty of unresponsive Web GUI lockups due to this setting, so at the moment I am trying to keep `MaxFolderConcurrency` at default, which as a result leads to the main problem described in this feature request.

**Comment by AudriusButkevicius** [comment]
The core problem is that your folders take ages to scan for whatever reason.

I don't see any point of having tweaks that allow you to decide on how "ages" are spent, so I guess it's a no from me, as I simply don't see this being generally useful outside of your specific issue.

You are probably better of running a second instance of syncthing, with unlimited scanning for some small urgent folders, etc.

Also, I think, this would not be trivial to implement, because there is no concept of a priority in the semaphores we use for locking, so this would need a whole new locking mechanism, plus there are edge cases, like a newly added 100TB folder, which looks empty and innocent, or a 1TB file landing an existing small folder.

**Comment by tomasz1986** [comment]
> The core problem is that your folders take ages to scan for whatever reason.

While I understand the other points, I totally disagree on this one. Any folder with a large number of files (e.g. 100,000) will take forever to scan on a weak CPU and/or slow storage. There is nothing specific to my setup in this case.

**Comment by calmh** [comment]
Folders are essentially independent entities, with separate scanning intervals and other causes of scans (fs notifications, API, changes discovered during sync, ...). I'm having a hard time  envisioning what a an "order" would even *mean*, never mind how to implement it ...

**Comment by tomasz1986** [comment]
> I'm having a hard time envisioning what a an "order" would even _mean_, never mind how to implement it ...

While Syncthing is already running, it is probably meaningless. I was thinking mainly about what happens when Syncthing is starting or after being awoken from sleep/hibernation. Then, all folders need to scanned at the same time, and in that case it would be nice to be able to start with small ones.

I assume that the order would have to be determined by the previous state recorded in the database. Of course, there can be cases where tons of files have been added or removed while offline, but this cannot be known before scanning anyway.

**Comment by AudriusButkevicius** [comment]
It would be equally nice for people to get hardware that matches the performance expectations.

**Comment by tomasz1986** [comment]
I agree, but it would be also nice to have all the money that is required to buy such hardware too. Sometimes you just have to work with what you have got. Nowhere it is written explicitly that Syncthing should be used on high-end hardware only either.

Anyhow, however imperfect, the workaround of `<maxFolderConcurrency>0</maxFolderConcurrency>` is here, so if you feel that doing something to resolve the problem described here is too complicated or not "generally useful", feel free to close the issue.

**Comment by calmh** [comment]
So the only time when an order would be relevant is at startup, and even in that case it seems the benefits are marginal (I'm frankly not sure what they are exactly, other than some aesthetic reasons). To accomplish ordered scanning at startup you'd need either a much more complex queueing system for these operations, or delaying starting the folders until the previous ones are done -- which would mean the folder is unavailable for API and uploads in the meantime.

I'm not *opposed* to ordering folders on startup, but I don't think doing it is going to be worth the effort, and I'm going to reject a large and complex PR for doing it. If there's a small, elegant, solution that I'm not seeing then I'm happy to see someone implement that.

**Comment by tomasz1986** [comment]
Thank you.

> it seems the benefits are marginal (I'm frankly not sure what they are exactly, other than some aesthetic reasons).

Well, you easily reproduce this yourself, on any hardware really.

1. Set `GOMAXPROCS=1`.
2. Create 100 folders.
3. Add 100,000 files to one of them.
4. Start Syncthing.
5. Once the large folder starts being scanned, everything else has to wait until it finishes. The slower the hardware, the more noticeable to problem is.

**Comment by calmh** [comment]
> Once the large folder starts being scanned, everything else has to wait until it finishes. The slower the hardware, the more noticeable the problem is.

Here's the thing though, what is "everything"? The other folders are up and running and can respond to requests, even though they are awaiting scanning. If you mean that they can't start syncing then that's true, but the situation would be identical if they completed scanning as they would still block syncing due to max folder concurrency.

Hence my "margin benefits, mostly aesthetic" (you'd like to see the folders complete scanning, but it doesn't affect much practically).

**Comment by tomasz1986** [comment]
> Or are you seeing some practical effect of this that I'm not understanding?

You know what, that is actually true. I have not considered the next stage thoroughly enough. This would only make sense if max folder concurrency was split into two separate settings - one for scanning, one for syncing. As it is right now, there will be no benefits.

With this in mind. I will close the issue, at least for now, as without max folder concurrency changes there will be no practical benefits anyway.
