### ISSUE TITLE
Syncthing is not connecting to remote devices

### ISSUE THREAD

**Issue by simonhughcom** [syncthing/syncthing#7243]
Version: v1.12.0, Linux (64 bit)

I'm running syncthing on multiple machines and they all work fine apart from my desktop where for whatever reason syncthing will not connect to remote devices.

I have tried to reinstall syncthing, I have tried to build my config from scratch, I have tried to run it without a local firewall but nothing seems to work.

When I first started to notice the problem, syncthing says it did not connect to any of my other machines for over a week, even though they where connected to the same LAN for extended periods of time.

When running tcpdump I am sending packets to 192.168.0.255 or port 21027, weird thing is that when checking my router settings, the ip pool only goes from 192.169.0.100-199? So 192.168.0.255 does not exist.

On port 2200 I am sending and receiving packets to/from `discovery-3.syncthing.net.stun` but nothing else.

There is nothing weird in my log apart from maybe
`[RL7EO] 16:25:27 INFO: quic://0.0.0.0:22000 detected NAT type: Port restricted NAT`
But I am not sure if that is normal or not.

The really weird thing is that I have another machine (laptop) which has almost the same setup apart from trivial differences (different partitions etc) and there syncthing works perfectly fine?

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
