### ISSUE TITLE
Scanning / syncing with Syncthing Android is extremely slow - breaks the app

### ISSUE THREAD

**Issue by kusshaltestelle** [syncthing/syncthing#7245]
Please see also 
https://forum.syncthing.net/t/scanning-syncing-with-syncthing-android-is-extremely-slow-1570/15770

**What happened**
On a freshly installed Google Pixel 5 scanning of a folder with 8 GB of Data takes forever (after two days no progress). **The app becomes unusable.**

**What did you expect to happen instead of what did happen, if it's not crazy obvious**
Installed last Syncthing Android App via Google Play Store. Added a folder on a PC and synced it with the Android Phone. On the PC the folder syn direction was "Send only", on the phone it was "receive only".

**What operating system, operating system version and version of Syncthing you are running**
Google Pixel 5, last Android version 11.

This seems to be a bug that occurs mainly on Google Phones (maybe because the have the latest Android?). My phone and the people writing in the forum thread linked above are Google Pixels (3, 4, and 5).

**Downgrade to Syncthing App 1.9.0 downloaded from F-Droid-Store helped me to fix the problem (as well as the guy in the forum, Rudd-O)**

**Comment by kusshaltestelle** [comment]
I'm have not written in the forum-thread linked above, as it is already closes. I'm also none of the authors of the thread, but I can confirm the bug. When I tried to reply/open a new thread there was a suggestion to file a bug directly. I'm not very experienced in Github Bug-Reporting, so please excuse any wrongdoings. **Thank you for creating this amazing software and all your work!** I hope my bugreporting helps a bit to improve Syncthing! :-)

**Comment by AudriusButkevicius** [comment]
This is the wrong repo, and I don't think this belongs on the issue tracker in general. This should continue to be discussed on the forum.
