### ISSUE TITLE
~syncthing~xxx.tmp files are not hidden in nested folders in Windows

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7247]
1. Create a new folder "test" on Device A.
2. Create a new nested folder "test\test" on Device A.
3. Share both folders with Device B and replicate the nested structure there.
4. Add a new large-sized file to "test\test" on Device A.
5. While still syncing, pause the folders on Device B.
6. The `~syncthing~xxx.tmp` file in `test\test` on Device B does not have the hidden attribute.

Tested with Syncthing v1.12.0.

**Comment by calmh** [comment]
I don't think you nestedness has anything to do with this.

https://github.com/syncthing/syncthing/blob/0f8290485e54fb6c2197188c25d7a7971d18f9f6/lib/model/sharedpullerstate.go#L335-L339

**Comment by tomasz1986** [comment]
Hmm, but when not using a nested folder, the file remains hidden though, even after pausing the folder.
