### ISSUE TITLE
Out of Sync happens often

### ISSUE THREAD

**Issue by BerndErnst** [syncthing/syncthing#7248]
I checked Github Issues and the Forum and the Documentation and the FAQ.
There is no clear answer what to do if syncing won't continue due an "Out of Sync" error.
How to resolve it?
I have easy setups and still, for no recognizable reason, it randomly gets this issue over all places with different devices. What is a good way to resolve it without basically setting up everything again?

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
