### ISSUE TITLE
Does not remove folders on Mac-to-Android sync

### ISSUE THREAD

**Issue by johncoffee** [syncthing/syncthing#7252]
Hi! I have an annoying (but less critical) bug, on a possibly unsupported Android version(?) (sorry, couldn't find this info).
 
Setup:  
I have macOS running Syncthing 1.12.0 (64 bit) on Catalina, and a Nexus 5 running Syncthing 1.10.0 on Android 6.

Steps:  
1. Remove a folder on macOS
2. Let Android sync
3. Notice Syncthing on macOS saying "Syncing 95%, (1 items, ~0 B)" on the info box for the Android device
4. Notice Syncthing on Android saying "Out of Sync" on the folders screen

Expected:  
The folder should have been removed from Android.

Work around:  
recreate the folder (same name) on any of the devices, then delete it from Android. It will dissappear on macOS, and both devices will say Up to Sync.

cheers!

**Comment by imsodin** [comment]
This sound more like a support request (why is it out-of-sync) than a bug report. Please use https://forum.syncthing.net/ for that, there's more friendly eyes there to help with the problem. If an actionable issue turns up in the discussion, this or a new issue can be opened again.

**Comment by johncoffee** [comment]
Oh i realized it didn't make it clear what kind of "folder" i was referring to. It's a filesystem directory, not a Syncthing Folder i have the issue with. I've tried to update the issue...
