### ISSUE TITLE
add option to purge cache for folder (or all caches)

### ISSUE THREAD

**Issue by rpodgorny** [syncthing/syncthing#7253]
i've spent good two hours googling and searching the gui (with no success) to achieve the following:

situation:
throughout time, my synced folders have accumulated large .deleted subdirectories.
the files contained there are already deleted on all peers. all peers are synced.
no version control is enabled on any peer.
the files have been deleted months ago.
i won't be needing any of these files in the future (actually they were added by accident and deleted immediately).

i would expect some kind of garbage collector to clean them up after some time but it doesn't seem to be happenning.
i'm afraid to purge the .deleted directory (will it break syncthing's internal structures?)

...what should i do to reclaim the disk space? thanks!

**Comment by AudriusButkevicius** [comment]
.deleted is not something that syncthing creates, this looks more like a support request, so please raise an issue on the forums.
