### ISSUE TITLE
relaysrv system v init script for deb package

### ISSUE THREAD

**Issue by phloggu** [syncthing/syncthing#7254]
sysncthing-relaysrv debian package is missing a system v init script. Some Linux distros using DEB package manager rely on system v init. So please package an init script in your deb-package that in can be used  on those systems. Including support for logrotate and rsyslogd would be a bonus.

If have prepared a version of an init script, that works for me so far. It uses pipexec to start relaysrv, is easy configurable through /etc/default/syncthing-realysrv, is logrotate safe and provides a logrotate and rsyslogd config. 

You may [download it as a tar.gz](https://ente.limmat.ch/ftp/pub/software/bash/syncthing-relaysrv/syncthing-relaysrv.tar.gz) or just [browse the files](https://ente.limmat.ch/ftp/pub/software/bash/syncthing-relaysrv/). See the [README](https://ente.limmat.ch/ftp/pub/software/bash/syncthing-relaysrv/README) for more.

**Comment by calmh** [comment]
Hi! I think this is covered under #2990 so no separate issue required. You're more than welcome to open a PR to add the init scripts! :)

**Comment by phloggu** [comment]
Hi calmh, I do not feel to be in the position to open a pull request. Could please someone else take over now?

The work to do is to test and later incorporate the script and configs into the deb package, therefore pre- and post-install scripts need to be adopted.

**Comment by calmh** [comment]
I don't know, but if someone does and creates a PR we'll look at it then. 👍
