### ISSUE TITLE
Syncthing terminating connections, I/O timeouts

### ISSUE THREAD

**Issue by Oriann** [syncthing/syncthing#7255]
### Does your log mention database corruption?

NO

### Include required information

Please be sure to include at least:

Syncthing 1.12.1, Windows 10 20H2
Synctrayzor 1.1.27

Started application, using it.....

After 1 minute console start spamming this

> [AZBII] 14:28:33 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.2.69:22000->myexternaladdress:22000: wsarecv: The existing connection was forcibly terminated by the remote host.
[AZBII] 14:28:43 INFO: Failed to exchange Hello messages with ACFKGGJ at [::]:22000-myexternaladdress:22000/quic-server/TLS1.3-TLS_AES_128_GCM_SHA256: Application error 0x0: closing
[AZBII] 14:29:53 INFO: Failed to exchange Hello messages with ACFKGGJ at 192.168.2.69:22000-myexternaladdress:22000/tcp-server/TLS1.3-TLS_AES_128_GCM_SHA256: read tcp 192.168.2.69:22000->myexternaladdress:22000: wsarecv: The existing connection was forcibly terminated by the remote host.
[AZBII] 14:30:03 INFO: Failed to exchange Hello messages with ACFKGGJ at [::]:22000-myexternaladdress:22000/quic-server/TLS1.3-TLS_AES_128_GCM_SHA256: EOF
[AZBII] 14:31:23 INFO: Failed to exchange Hello messages with ACFKGGJ at [::]:22000-myexternaladdress:22000/quic-server/TLS1.3-TLS_AES_128_GCM_SHA256: Application error 0x0: closing
[AZBII] 14:31:23 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.2.69:22000->myexternaladdress:22000: i/o timeout
[AZBII] 14:32:33 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.2.69:22000->myexternaladdress:22000: wsarecv: The existing connection was forcibly terminated by the remote host.
[AZBII] 14:32:43 INFO: Failed to exchange Hello messages with ACFKGGJ at [::]:22000-myexternaladdress:22000/quic-server/TLS1.3-TLS_AES_128_GCM_SHA256: Application error 0x0: closing
[AZBII] 14:33:53 INFO: Listen (BEP/tcp): TLS handshake: read tcp 192.168.2.69:22000->myexternaladdress:22000: wsarecv: The existing connection was forcibly terminated by the remote host.
[AZBII] 14:34:03 INFO: Failed to exchange Hello messages with ACFKGGJ at [::]:22000-myexternaladdress:22000/quic-server/TLS1.3-TLS_AES_128_GCM_SHA256: EOF

EDIT: Discovered that ACFKGGJ device is just another peer connected to my home server, I don't get why its exchanging Hello when I have not allowed any sync between my device and this peer. I am exchanging data only with main syncthing server.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
