### ISSUE TITLE
v1.12.1 release: no native mac/arm64 binaries?

### ISSUE THREAD

**Issue by maxodoble** [syncthing/syncthing#7256]
hi,

i've seen some v1.12.1-rc builds for native mac/arm64 recently ([see closed issue 7128](https://github.com/syncthing/syncthing/issues/7128)) but the final release for v1.12.1 lacks these mac arm binaries.

any particular reason for this?

thanks,

max

**Comment by calmh** [comment]
Yes, it required changes to the build that went in after 1.12.1. Next release will have an arm build (even then slightly shady since it'll be built with a beta version of Go). In the meantime you can run the nightly if you like.
