### ISSUE TITLE
Rescan All button should be greyed out when all folders are paused.

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7257]
This is a very minor issue, but still…

The "Rescan All" button does nothing when all folders are paused. Therefore, I think that it should be greyed out (i.e. disabled) in such a situation.

**Comment by calmh** [comment]
Rather, I think it should rescan all folders that are not paused. (Why doesn't it?)

**Comment by tomasz1986** [comment]
It does 😉. I mean a situation where everything is paused, i.e. there is no folder to scan. Clicking the button then does nothing (but the button itself still reacts to clicks).

**Comment by calmh** [comment]
Ah, I missed the part about *all* folders, sorry.

**Comment by tomasz1986** [comment]
No problem 🙂. Another case has also come to my mind, and that is when all folders are already being scanned. The button could also be greyed out then, although this one is likely very rare, unless you have only huge folders that take long time to finish scanning.
