### ISSUE TITLE
Synology Support, take 2

### ISSUE THREAD

**Issue by sciurius** [syncthing/syncthing#726]
The Synology NAS servers form an excellent platform for tools like SyncThing. However, the choice for Go as implementation language makes it hard, if not impossible, to build SyncThing for several of Synology's popular server architectures like PPC and QoriQ. Similar problems will affect iPhone/iPad, I assume.

It is not helpful to say "that's a Go problem, not SyncThing's." To gain sufficiently wide acceptance SyncThing should support these platforms.

What steps can be taken to accomplish this?

**Comment by Dahaniel** [comment]
@sciurius maybe you can report back to this thread when you were successful. I am trying to move from btsync which is running on my MyBookLive NAS. Unfortunately the MBL's architecture is also PPC.

**Comment by sciurius** [comment]
No progress, unfortunately...

**Comment by Dahaniel** [comment]
@lertsenem was able to build a PPC binary which runs on my MyBookLive. Unfortunately I have the problem that it is eating a lot of the memory. Closing the GUI helps a bit but still shows ~50% (~128MB) in top, the GUI reports up to 500. I assume this includes swap as my NAS only has 256MB

**Comment by Lertsenem** [comment]
Dahaniel asked, so here is my recipe to build for ppc. It's probably not very clean, but it's fast and easy enough: https://store.lertsenem.com/syncthing-ppc/Xcompile_syncthing_for_ppc_recipe.html

I think there may be some gccgo options to use to optimize the memory usage, but I'm not the right man for the job.

**Comment by calmh** [comment]
@Lertsenem Minor error in the blog post is the build.go does not fetch any dependencies. The ones already present in the repository are used. :)

**Comment by Lertsenem** [comment]
Oh ? Did that change in the past ? Because I used an earlier version of Syncthing for my build, and I could swear I downloaded a bunch of projects when doing my first compilation. But maybe I'm mistaken.

**Comment by calmh** [comment]
Possibly a very long time ago. Or you may have run godep manually (`godep restore`) or similar?

**Comment by Lertsenem** [comment]
It's quite possible I messed around with godep, yes.

**Comment by The-MAD-Virus** [comment]
i have heard that go 1.5 will auto build (no more need of gcc) and will support ppc64, so there's still hope! (go 1.5 release date on July 31, 2015).

**Comment by sciurius** [comment]
On Mon, 18 May 2015 08:52:24 -0700
The-MAD-Virus <notifications@github.com> wrote:

> i have heard that go 1.5 will auto build (no more need of gcc) and will
> support ppc64, so there's still hope! (go 1.5 release date on July 31,
> 2015).

Good news, although still no support for QORIQ :( .

-- Johan

**Comment by roberttang30** [comment]
In case it's of any use to someone I have compiled an updated version of syncthing myself and written up the build procedure. Here is a link to the procedure and the binary http://blog.robertnash.org/2015/08/09/building-syncthing-for-my-book-live-duo 
This is based on Lertsenem's method but the build.go file has been updated due to changes made in recent versions of syncthing.

**Comment by vladimirromashkin1g** [comment]
@roberttang30 Thank you very much for the your guide.
Great work! I looked for it =)
I'd tried to build syncthing using the guide and run on my MyBookLive.
First run was successful. But after I've added a new folder to `config.xml` syncthing crashes with panic.
And I don't understand a reason: incorrect build, incorrect config or something else...
I used `master` sources. What did you use for your MyBookLive Duo?

**Comment by AudriusButkevicius** [comment]
Sadly it crashes somewhere in C land due to an unsupported compiler, so the trace is just gibberish.
Try disabling global discovery.

**Comment by vladimirromashkin1g** [comment]
By the way. I've just seen this after new build with stable sources:
```
# github.com/syncthing/syncthing/cmd/syncthing
/usr/lib/gcc-cross/powerpc-linux-gnu/5/libgo.a(net.o): In function `net.LookupPort':
/build/buildd/gcc-5-cross-5ubuntu1/gcc/build/powerpc-linux-gnu/libgo/../../../src/libgo/go/net/cgo_unix.go:83: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```
May this warning be the reason?
Also I'll try to disable global discovery.

**Comment by AudriusButkevicius** [comment]
You should try a dynamically linked build.

**Comment by vladimirromashkin1g** [comment]
Dynamic linking didn't help because syncthing can't locate `libgo.so.7`.
I had not found needed package for Debian (which boarded on MyBookLive) and tried to eat `libgo.so.7` from `powerpc-linux-gnu`. But I have the similar panic error as result.
What libs did you use on your MBL? How should I install it?

Statically linked syncthing run longer without global discovery and was killed by system (I think) during hashing of 150GB.

**Comment by roberttang30** [comment]
Sorry but I won't really be of much help as, while I was just about able to get this to work based on Lertsenem's instructions, I'm not particularly intimate with the build process. The only comment I have which might be somewhat related to your problem is that syncthing wouldn't connect to the global discovery server unless I gave it an IP address in the discovery server configuration setting.

**Comment by roberttang30** [comment]
One more thing, I used the master sources not a particular release and whilst I did get it to work with my own folder I haven't tested it extensively.

**Comment by vladimirromashkin1g** [comment]
I'm newbie in linux and sometimes ask strange questions.
It seems like I do something extra. You gave me food for thought. Thank you.
Please tell me you run syncthing on the original firmware without chroot and other tweaks, don't you? what version?

**Comment by roberttang30** [comment]
Not really any tweaks other than optware but I wouldn't have thought that
would make much of a difference. I am running quite an old version (
02.40.06-048), don't know if that will make a difference.

**Comment by kalsan** [comment]
There is a more recent Blog post (Sept. 2015) about the topic here: http://lookanotherblog.com/?p=527

**Comment by kalsan** [comment]
@calmh now that there have been at least two successful attempts to get syncthing running on ppc64, is there a chance for official support in the near future?

**Comment by AudriusButkevicius** [comment]
There are official ppc builds now, whether it works, no idea.

**Comment by sciurius** [comment]
Unfortunately, QoriQ is not PPC.
