### ISSUE TITLE
[Cosmetic] No favicon for bookmark

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#7260]
### Does your log mention database corruption? No

Latest Ubuntu/Firefox/New account
Although, syncthing icon displays OK in the tab.

Message in Firefox Inspector (translated): Cookie « CSRF-Token-E4YNY » will soon be treated as a cross-site cookie regarding « https://127.0.0.1:7374/assets/img/favicon-default.png » because the schema does not match.

Maybe this is only the name favicon-default.png that FF doesn't like for bookmarks.

**Comment by tomasz1986** [comment]
I can confirm that this is indeed the case. I have tried to investigate, and it seems that Firefox does not save the icon for the bookmark at all. You can verify this by exporting bookmarks into HTML. For Syncthing, the icon attribute is missing entirely.

**Comment by bugith** [comment]
@tomasz1986 
I'm not so sure : instead it seem there is something wrong, at least with FF : I notices the missing *bookmark-only* icon issue for a big while. Although a freshly installed ST (read: a very *first* open GUI + bookmark) ends in intended behaviour. BUT: If the bookmark come from FF-Sync icon is lost, even after instruction to FF to "Forget" the site+delete any :8384 in history + st password in FF pŵ db. I think I even tried to reconfigure ST with no pw + + no https.
Notice this may be a addon issue.

**Comment by AudriusButkevicius** [comment]
I think we should close this as I can't see anyone spending time on this, given on how minor and unimportant this is.
If you really want this fixed, I suggest you figure out why this is happening and propose a pull request.

**Comment by bugith** [comment]
Ok

**Comment by bugith** [comment]
Just to let you know.

**Comment by ajshea** [comment]
the bug is due to FireFox and forks not evaluating the scripted favicon when the page first loads. Chrome and forks do. 

See https://forum.syncthing.net/t/fixing-syncthing-favicons-in-firefox/15726

I suggest that the initial favicon not result in a 404, as noted by calmh at https://forum.syncthing.net/t/fixing-syncthing-favicons-in-firefox/15726/2

**Comment by ajshea** [comment]
See #7638
