### ISSUE TITLE
Different files in path, depending how I look for the files

### ISSUE THREAD

**Issue by Meresmata** [syncthing/syncthing#7261]
### Does your log mention database corruption?

I want to sync my Retroarch save files (windows, linux, Android). On my linux machine (Xubuntu 20.10 with Syncthing GTK):
~/.var/app/org.libretro.RetroArch/config/retroarch/saves
The path can be found at, but when I add it, only the global state is synced, but not the local state back to global state.
When I open the path in Syncthing GTK I can only see, the global state in Thunar I see the local state.
Both are installed via flatpak. Flatpak is upto date.

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
