### ISSUE TITLE
Close the CMD window faster when using -no-console in Windows

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7262]
Currently, it can take as much as 15-30 seconds for the console window to close when using the `-no-console` option in Windows. The slower the hardware or the OS, the longer it takes.

I am not sure if this is technically possible, but if yes, then I think that the console window should close much faster than it is the case right now. The main problem with the current behaviour is that the user may accidentally close the window either by a misclick or simply thinking that it has hanged, which as a result will prevent Syncthing from starting.

Below is a screenshot showing what the window looks like right now. It stays like this on the screen till it finally closes, but until then, there is no visible output.

![image](https://user-images.githubusercontent.com/5626656/104114194-e6344980-5344-11eb-88a4-824a04e78b02.png)

**Comment by calmh** [comment]
It's pretty much the first thing we do at the top of main after parsing command line flags.

https://github.com/syncthing/syncthing/blob/e6f0ed65be02d1ed278989f5d9fca948880e4ebd/cmd/syncthing/main.go#L301-L303

I don't know what it is that takes time for you. On the Syncthing side there are some things run at init time before main, but it's like setting up data structures and such so we should be talking about microseconds. In practice I don't think there's much more we can do here. (As always I suspect antivirus.)

You can compile a no-console Windows build, but that gives you literally no way to get console output if it fails to start so there are tradeoffs.

**Comment by AudriusButkevicius** [comment]
Agreed, there is not more we can do here.

**Comment by tomasz1986** [comment]
> I don't know what it is that takes time for you. On the Syncthing side there are some things run at init time before main, but it's like setting up data structures and such so we should be talking about microseconds. In practice I don't think there's much more we can do here. (As always I suspect antivirus.)

A think that it is a combination of system startup, low process priority, and possibly antivirus. What I mean is that once the system is up and running, Syncthing starts quickly and the console window only flashes for a second or so (even with AV). The problem is that when starting Syncthing on boot, e.g. by using the Task Scheduler, there are tons of other processes being started at the same time, and because Syncthing is lower priority, it has to wait for the rest to be processed. This causes the CMD window to hang and wait for its turn.

The hardware also makes a big difference. The longest ~30 second hang I have seen on a dual-core Celeron CPU.

Anyway, if nothing can be done, then nothing can be done :disappointed_relieved:.
