### ISSUE TITLE
Cannot install syncthing on Windows 7

### ISSUE THREAD

**Issue by sharadregoti** [syncthing/syncthing#7279]
### Does your log mention database corruption?
NO

### Include required information

Please be sure to include at least:

 - Operating System: Windows 7
 - Syncthing Version: v0.9.4.4
 - Syncthing Windows Installer: SyncthingGTK-v0.9.4.4-win32-full-installer.exe
 - After installing syncthing, when I click on the next button on the UI for configuration. I get the error Failed to download syncthing daemon package
 - any steps to reproduce the problem.
   download syncthingGTK installer for windows, Install the software. Open the app, it will ask for configuration click next, and you will get the error.

Image of the error
![image](https://user-images.githubusercontent.com/24411676/104547151-da51cb80-5653-11eb-8870-fcae2b91a44e.png)

**Comment by wweich** [comment]
1. there never was a version 0.9.4.4 of syncthing
2. wrong repo. your problem has nothing to do with syncthing itself, but with [syncthing-gtk](https://github.com/kozec/syncthing-gtk)
