### ISSUE TITLE
Stopped folder not synchronizing after a rescan

### ISSUE THREAD

**Issue by acolomb** [syncthing/syncthing#7280]
Seen on Syncthing v1.12.1, Windows 10 64 bit.

When a folder is not available when starting Syncthing (e.g. on removable storage), it will be in the "Stopped" state with an appropriate error message "folder path missing".  If the physical path becomes available again, a (manual or timed) rescan will usually suffice to get it back into a working state.

However, when a remote device made changes to the folder while it was stopped, the rescan will lead to an "Out of Sync" state and the changes are not pulled from a remote device.  They are correctly listed as out of sync items.  Further rescans do not help, only pausing and unpausing the folder makes it work again.

I expect it to become "Up to Date" again after triggering a rescan.  It used to be like that, so looks like a regression in the recently reworked remote index handling.

### Steps to reproduce

1. Stop Synchthing on the local device, which mutually shares a folder with a remote device.
2. Move the shared folder path somewhere else so ST won't find it anymoe.
3. Create a new file in the folder on the remote side.
4. Start local ST again and find the folder "Stopped" and a warning notification.
5. Wait for the remote device to be connected again.
6. Move the shared folder back into its original location.
7. Press the "Rescan" button on the local folder. (Optionally dismiss the notification first.)
8. Find the folder in "Out of Sync" state, with the new file listed among unsynchronized items.
9. To fix, pause and then unpause the folder.  Watch it syncing properly and pulling the new file.

**Comment by acolomb** [comment]
May be related to #7198.

**Comment by imsodin** [comment]
A pull is scheduled only if we detect a change during scan. I'd expect that if you added some random file to your folder, before pressing "Rescan", it would sync.

What we should do is to schedule both a scan and a pull unconditionally when a folder was in a stopped/errored state and becomes operational again.

I don't think this is a regression, that code hasn't changed in a long time as far as I remember.

**Comment by acolomb** [comment]
> I don't think this is a regression, that code hasn't changed in a long time as far as I remember.

My setup includes an encrypted drive which needs manual unlocking after each boot, with Syncthing starting before that.  Can't put my finger on a specific release, but roughly 3 or 4 months ago, the Rescan button used to be enough.  Muscle memory tells me for sure because that became part of the routine after unlocking the encrypted drive.
