### ISSUE TITLE
Do not touch .stignore on saving folder config when ignore patterns have not changed

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7284]
Right now, the modtime of `.stignore` gets changed every time we click on the "Save" button in the "Edit Folder" window. Even if there are no changes to the actual patterns, the modtime still gets updated. Is there any specific reason for this behaviour?

If not, then I would argue that when the patterns have not changed, the modtime should remain unchanged too.

Tested with Syncthing v1.12.1.

**Comment by calmh** [comment]
I think that's indeed the intended behavior (don't save if nothing changed), but I guess the identity comparison here doesn't do that.

https://github.com/syncthing/syncthing/blob/abfbd13f17a0511a92eff8fb59d4ee6b975b7979/gui/default/syncthing/core/syncthingController.js#L1985-L1987
