### ISSUE TITLE
Can the relay service be opened and organized? Individuals voluntarily join this, similar to syncthing relay service

### ISSUE THREAD

**Issue by talway** [syncthing/syncthing#7295]
Mainly because my current Microsoft remote desktop and the speed of fetching some files are too slow, the network environment in our area is not very good;

https://relays.syncthing.net/

https://data.syncthing.net/

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
