### ISSUE TITLE
tcp connection reset by peer on multi-core linux

### ISSUE THREAD

**Issue by vlalov** [syncthing/syncthing#7297]
Out of the half a dozen devices I've got in my network running Syncthing 1.12.1 on Linux x64 only one refuses to sync up. Index sync up is fine, but then files never complete. Instead I'm presented with consistent "connection reset by peer" errors on both devices. Every retry results in that error.

After some deliberation and debugging I think I know at least why it only happens on that machine. It's running a 12 core, 24 thread CPU. I've tried lowering the number of processors used and sure enough the issue disappeared.
Running `GOMAXPROCS=2 syncthing` results in successful synchronization. While if ran with no limitation there's a constant tcp4 connection reset by peer errors. I'm not sure if's a concurrency issue in syncthing or Go issue.

**Comment by calmh** [comment]
What does the log say on the other side?

**Comment by AudriusButkevicius** [comment]
I guess its also worth trying the latest development snapshot to see if that helps, as we have fixed a few lock contentions recently.

**Comment by calmh** [comment]
I don't see how reducing gomaxprocs could have any positive effect on that, frankly it sounds like voodoo or hardware error, but we'll never know without logs.
