### ISSUE TITLE
Building without internet access.

### ISSUE THREAD

**Issue by lockywolf** [syncthing/syncthing#7301]
My company considers using Syncthing for file synchronisation on the intranet. However, due to standard security requirements, internal computers are not connected to the Internet (a so-called "airgap"), and building Syncthing fails due to being unable to download dependencies. Please, consider implementing builds without internet access. (Presumably, by caching dependencies in a ./3rd_party directory).

**Comment by imsodin** [comment]
For reference (I assume @lockywolf discovered this and thus closed):  

The cloned repository cannot be built offline. The released source packages can be, as they do include a "vendor" directory with all the dependencies. These is the file named "syncthing-source-...", not github's auto-created "Source code (zip)", available at https://github.com/syncthing/syncthing/releases.
