### ISSUE TITLE
Force folder update

### ISSUE THREAD

**Issue by jjpe** [syncthing/syncthing#7307]
> Closing as I believe this is just a misunderstanding how syncthing works.
> If you have any comments, please let us know so that we could reopen it.

> _Originally posted by @AudriusButkevicius in https://github.com/syncthing/syncthing/issues/2019#issuecomment-118945519_

I've come across a situation where I believe a forced folder update is not just handy but crucial: 
I have a file in a folder that somehow got out of sync. I've tried deleting it on the target host, but so far it hasn't made syncthing automatically re-sync the file from source host to target host, even though I have set the syncing to be unidirectional (which also implies it was likely some kind of bit flip on the target host to make the file desync in the first place).

If syncthing would automatically correct this on its own then that would be great. As-is, however, I'm stuck with what looks like a permanently desync'd file, unless I perform some manual surgery and hope to the Great Flying Spaghettimonster that syncthing picks up on it.

**Comment by imsodin** [comment]
The comment still stands: This sounds more like a support request than a concrete bug report. Please describe your problem (with the steps you took, screenshots, ... - whatever might be helpful) on the forum: https://forum.syncthing.net  
The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
