### ISSUE TITLE
Sync algorythm is not efficient enough (v1.12.1)

### ISSUE THREAD

**Issue by antonakv** [syncthing/syncthing#7312]
I use v1.12.1 on macOS (64 bit)
I created Sync folder and put 36k files with summary size 13G. There is problem with 2 nodes setup. Sync speed is very slow and it's just stopping and doing nothing. It's not improved in v1.12.1 at all. 
Following FAQ: And Firewall is disabled, Relay is not used, Network is fast Gigabit ethernet one, switches have flow control. scp of tar.gz file does 100 M/sec.

Something is really wrong with Sync algorythm.

What about using Stream torrent like way ? Data flow should have constant max speed, a be pre-cached. 
It's ok to use more cpu as DropBox does, not a problem at all.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
