### ISSUE TITLE
better relay choice: "patch" suggested

### ISSUE THREAD

**Issue by phloggu** [syncthing/syncthing#7313]
Syncthing's mechanism of choosing a relay server is very simple and not very clever. It has been subject to many discussions already. With the change of one line of code, this could get improved, as discussed and described in the [forum](https://forum.syncthing.net/t/how-does-syncthing-choose-a-relay/16129/17). In short: I suggest not to have fixed buckets classes of 50ms latency for relay candidates, instead use smaller buckets for low latencies and bigger buckets for high latencies.

This change can get achieved by changing [line 159](https://github.com/syncthing/syncthing/blob/fbe52faf492619fd57a0dbe125c9f0c3bcceec19/lib/relay/client/dynamic.go#L159) of [/syncthing/tree/main/lib/relay/client/dynamic.go](https://github.com/syncthing/syncthing/blob/main/lib/relay/client/dynamic.go) to:
    `id := int(Sqrt(latency/time.Millisecond / 10))`
Please check, I’ve never written anything in golang, so regard this as pseudo code that means: _“Divide the latency in ms by 10, take the square root and round down”_.

Thanx for considering.

**Comment by calmh** [comment]
Please quantify in what way this is better and how you came to this conclusion.

**Comment by AudriusButkevicius** [comment]
Why does this need to be discussed here in general? There is already a thread on the forum, this should stay there until there is some buy in from our side, which I am not sure there is at the moment.

**Comment by calmh** [comment]
I suppose it's the presence of the suggested "patch".

But what I'm driving at is there first needs to be agreement on what "better" means and secondly some thought to "better for whom". The purpose of this patch is to get smaller buckets for low latency connections, thus increasing the chance that a lower latency relay is chosen. I can understand that as one definition of better. But it's only better for someone on a low latency connection, which is presumably the author here. The new bucket size is the same as the old in the range 40-89 ms, and larger than the old for greater latencies than that.

If I run Syncthing on my 4G connection from home my minimum latency to anywhere is 60 ms, so I'm actually in a situation with larger buckets in the proposed change than in the existing system.

So I think this needs more thought about what we're trying to improve and for whom, and what the effects will be for a large variety of setups and connection types. (And that should all happen on the forum.)

**Comment by AudriusButkevicius** [comment]
Also, if my memory is not wrong, the buckets used to be 10 or 20ms, initially I think, and we made them bigger, not sure I recall for what reason.

**Comment by phloggu** [comment]
@calmh 

>  first needs to be agreement on what "better" means
Have you read the whole thread in the [forum](https://forum.syncthing.net/t/how-does-syncthing-choose-a-relay/16129)? It's written there that there is not a straight correlation of latency and throughput, what's the assumption of the current code. But the current code does not well at all, as shown by my relay stats and by the example of "bra". The new code would. The old code even does no good for high latency/sparse regions as it lessens choice.

> If I run Syncthing on my 4G connection from home my minimum latency to anywhere is 60 ms, so I'm actually in a situation with larger buckets in the proposed change than in the existing system.
No, you are in the bucket 40-89ms instead of 50-100ms. So actually you get probably better latency.

> So I think this needs more thought about what we're trying to improve
We're trying to improve the current mechanism with a *very simple* suggestion, that doesn't change anything fundamental. We're trying to improve the choice of a relay by just taking latency into account. The current algorithm was criticized a lot, the only good thing about it is, it's very simple. The improvement is almost as simple but improves the situation for everyone. Think about, not just two minutes, please.

**Comment by phloggu** [comment]
> Also, if my memory is not wrong, the buckets used to be 10 or 20ms, initially I think, and we made them bigger, not sure I recall for what reason.

Probably because in regions with just a few relays there were just a few relays in the bucket and the higher buckets ids were often empty. And that's the crucial thing to watch after in time distance based approach: distribution of the relays. Some choice for equal good relays. With the suggestions you get exactly that for all users. To make the situation perfect we would need a better distribution of relays...

**Comment by phloggu** [comment]
> Why does this need to be discussed here in general? There is already a thread on the forum, this should stay there until there is some buy in from our side, which I am not sure there is at the moment.

Agree, much better than just closing the request.

**Comment by calmh** [comment]
It's totally unclear to me that this improves the situation for everyone; rather the opposite. Your assumption is that's smaller buckets are better and It's easy to see that with a high latency connection the buckets are in fact larger with your suggestion. So even accepting your assumption as given the solution is not an improvement for everyone.

I'm all for improving things, but your simple patch suggestion doesn't cut it. If you want to make an improvement, please define what that improvement is and show that it helps in a wide range of common scenarios, not just the one you happen to be in yourself. And please do it on the forum, not here.
