### ISSUE TITLE
Sharing a new folder results in remote out of sync (metadata tracking issue)

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#7314]
Today I did the following, in my existing smoothly running setup.

- On "pseudo", share existing older "foto-albums" with "lun0".
- On lun0, accept the folder as receive only.

Data started flowing, end result being the following, on pseudo (the source):

<img width="1163" alt="Screenshot 2021-01-31 at 11 47 14" src="https://user-images.githubusercontent.com/125426/106381583-1ad27880-63ba-11eb-9115-19d47a61ae3f.png">

On lun0 (the destination):

<img width="1161" alt="Screenshot 2021-01-31 at 11 48 00" src="https://user-images.githubusercontent.com/125426/106381593-3178cf80-63ba-11eb-89c3-d7f5de355c15.png">

The files that are supposedly out of sync are a large chunk of files "first" in the folder (alphabetically), possibly those with the lowest sequence numbers. They are correctly present on disk.

I took database snapshots.

Then, just for fun, I restarted pseudo, thinking this should have no effect. The problem went away and everything looks in sync, as it should. Looking at the logs from the restart I have this:

```
Jan 31 11:51:14 pseudo syncthing[901]: [PSEUD] INFO: Stored folder metadata for "smaoh-2qdsh" is 754h0m0s old; recalculating
Jan 31 11:51:15 pseudo syncthing[901]: [PSEUD] INFO: Ready to synchronize "foto/albums" (smaoh-2qdsh) (receiveonly)
```

so the folder metadata was recalculated, and was probably what was wrong to begin with. So somehow we missed updating some part of the metadata with the incoming index updates directly after sharing the folder...

**Comment by tomasz1986** [comment]
It is likely the same thing that I mentioned in https://github.com/syncthing/syncthing/issues/7263 (see the 2nd screenshot). The problem has existed since the behaviour was changed not to drop connections on config change. The files themselves are synced correctly though, and pausing and resuming the connection gets rid of the errors.

**Comment by bradmurray** [comment]
Pausing and resuming does not clear the "out of sync" for me. Many of the items are folders. The files are all in sync. Doing a dry-run rsync shows nothing to copy. I can even manually overwrite one folder with the other and it still shows as out of sync. For me one of the clients is a mac and the other is a windows server.
