### ISSUE TITLE
Unable to grant write permissions after upgrade to Android 11

### ISSUE THREAD

**Issue by mudeth** [syncthing/syncthing#7320]
App was working fine before upgrading to 11. Now it asks me to grant write permission and when I do the android dialog appears, but I'm unable to enable the permission (check screenshot).

Also, a toast saying 'Permission granted' appears (also captured in screenshot).

When I go back to syncthing fork it still recognizes that permissions aren't available and refuses to continue.

I understand there are permission issues with 11 but I believe this behaviour is not intended? My sync folders are all on the device memory, not on SD card.

Device: Asus ZenFone 6z
Android 11 vendor ROM, Jan security patch
SD card formatted as portable storage

![Screenshot_20210201-214856639](https://user-images.githubusercontent.com/17807145/106486536-c3c2c580-64d7-11eb-81e2-5262910f1c20.jpg)

**Comment by imsodin** [comment]
Wrong repo: https://github.com/catfriend1/syncthing-android
