### ISSUE TITLE
Official builds of v1.13.0 come with the Tech Ui, which is impossible to switch back from

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7324]
For details, see https://forum.syncthing.net/t/how-to-switch-back-to-default-ui-from-tech-ui/16297.

![image](https://user-images.githubusercontent.com/5626656/106757725-0e794480-6674-11eb-80eb-d13c9622e0b4.png)

It seems that the official builds of Syncthing v1.13.0 somehow come with the Tech Ui included by default, even though the theme itself is not a part of the official Syncthing repository. I have only checked the official Windows zips, so I cannot say whether everything is affected or not.

**Comment by AudriusButkevicius** [comment]
This is intended I think? 

What's the complaint here other than not being able to switch back?

**Comment by tomasz1986** [comment]
I do not think that this is intended. The UI is not included in the repository. If you compile from v1.13.0, there is no Tech Ui. The current official builds cannot be reproduced with self-compilation.

**Comment by calmh** [comment]
It's intended, to the extent that I did it intentionally for a reason. It may not be well thought through, in that switching back is problematic. The source is in a different repo, which is something that may change but is also not an unheard-of situation.

**Comment by tomasz1986** [comment]
Still, there is no commit, no mention in the changelog, and the zipped source code also does not include it…

**Comment by calmh** [comment]
Partly because we haven't yet decided on how to properly do that integration, if at all.

**Comment by tomasz1986** [comment]
I have no problems with the alternative UI, however, as it is right now, the binary and the attached source code do not match, which in many peoples' eyes will not be a good look.

**Comment by calmh** [comment]
Luckily they will likely find this issue and see the reasoning. We could include the compiled UI in the source zip, we could even do it retroactively, but it's still essentially binary. Nonetheless we do that with the README and getting-started PDFs, man pages, etc so we certainly could.

**Comment by tomasz1986** [comment]
Another problem that I can think of is that if this gets to the Android app, and then someone changes the UI there, then they will essentially be stuck, as the `config.xml` file there cannot be edited without root access.

**Comment by calmh** [comment]
Mmm, and it's already bad as-is. I think we should probably ship a 1.13.1 with it at least moved to be a subdir of the default theme rather than a theme of its own.

**Comment by calmh** [comment]
I'm retitling this for the practical problem at hand, and leaving the philosophical discussion for (ideally) the forum.

**Comment by imsodin** [comment]
We could just filter it out in the theme selector in javascript. Then one needs to choose it through rest/config.xml, and can also switch back to the normal UI there. And we don't need to do any workarounds otherwise, the theme just lives and is served from where it is supposed to be.

**Comment by calmh** [comment]
Moving it to underneath `gui/default` means one has to explicitly say `http://localhost:8384/tech-ui/index.html` in the address bar and otherwise everything works as usual. This seems like the quickest fix?

**Comment by tomasz1986** [comment]
> I'm retitling this for the practical problem at hand, and leaving the philosophical discussion for (ideally) the forum.

I am not going to continue the discussion here, but my main point in this issue was not about the inability to change the theme, but rather specifically about including an undocumented change to the binary. @Catfriend1 with his fork has been criticised so much for his push for quick changes without proper review process, but how is this different? I would say that this case is actually worse, as here there has been no standard review process at all (even if the UI is ultimately not to stay).

**Comment by calmh** [comment]
I'll be happy to discuss the above point, and I think you do have a point to discuss, but not in this issue.

**Comment by tomasz1986** [comment]
Just for the record, the new way to access the Tech Ui does not seem to work very well.

The icon is broken,

![image](https://user-images.githubusercontent.com/5626656/106792782-f3b9c680-6699-11eb-8182-1e4db5605e20.png)

but the main problem is that, at least in Chromium, entering the URL as

```
http://127.0.0.1:8384/tech-ui/index.html
```

automatically gets changed to

```
http://127.0.0.1:8384/tech-ui/index.html/
```

and then trying to refresh the page results in

```
404 page not found
```
.
