### ISSUE TITLE
Corrupted folder states and device stuck in sync after pausing and adding files during the initial sync

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7337]
I am sorry for the long title, but I am not sure how exactly to describe this.

How to reproduce:

1. Create and share an empty folder between 3 devices - A, B, and C.
2. Add one large file to the folder on A.
3. While still syncing, pause the folder on A.
4. Wait for B and C to mark the folder "Out of Sync".

![1](https://user-images.githubusercontent.com/5626656/107113860-0ce29300-68a5-11eb-8960-e67308241a53.png)
![2](https://user-images.githubusercontent.com/5626656/107113862-0eac5680-68a5-11eb-8468-bbd852b2e401.png)
![3](https://user-images.githubusercontent.com/5626656/107113864-0f44ed00-68a5-11eb-8e38-2130d11e4882.png)

5. Unpause the folder on A.
6. B and C are stuck trying to download the file.
7. In this state, add two more large files to the folder on A.
8. The two new files get properly pushed to B and C, but the first file gets "forgotten" in the process.

![1](https://user-images.githubusercontent.com/5626656/107113913-5d59f080-68a5-11eb-807c-199018121b28.png)
![2](https://user-images.githubusercontent.com/5626656/107113915-5f23b400-68a5-11eb-866b-715523336132.png)
![3](https://user-images.githubusercontent.com/5626656/107113916-60ed7780-68a5-11eb-92db-1aa864391dd3.png)

9. The folder is marked "Up to Date" on all three devices, but the states differ, and A is stuck trying to push the first file to B and C.

![1](https://user-images.githubusercontent.com/5626656/107113752-4c5caf80-68a4-11eb-9c23-910ed16f4846.png)
![2](https://user-images.githubusercontent.com/5626656/107113754-4e267300-68a4-11eb-8442-636c4ebb35fb.png)
![3](https://user-images.githubusercontent.com/5626656/107113756-4f57a000-68a4-11eb-9e99-756483bf73f3.png)

10. Restarting Syncthing on A, B, or C makes no difference.

Logs with `STTRACE=db,model`:

[syncthing1.log](https://github.com/syncthing/syncthing/files/5936514/syncthing1.log)
[syncthing2.log](https://github.com/syncthing/syncthing/files/5936515/syncthing2.log)
[syncthing3.log](https://github.com/syncthing/syncthing/files/5936516/syncthing3.log)

I also would like to add that the testing was done with v1.13.1, but I can reproduce this behaviour using the current `main` (`v1.13.2-dev.36.g6db8dc33`) too.

**Comment by imsodin** [comment]
Same cause as https://github.com/syncthing/syncthing/issues/7649, thus also fixed by https://github.com/syncthing/syncthing/pull/7671
