### ISSUE TITLE
"Introducer" should not automatically share nested folders if their parent is already shared between the same devices

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7338]
Let us say that we have the following folder structure.

```
Device A
  Folder 1
    Folder 2
Device B
  Folder 1
    Folder 2
Device C
  Folder 2
```

All devices are interconnected. Initially, Folder 1 is shared between A and B, and Folder 2 is shared between A and C, and between B and C. Now, if we enable "Introducer" for each of these devices, Syncthing will automatically share Folder 2 between A and B, even though its parent is already shared between the two.

This may be tricky to implement, but it would be really nice not to have such nested folders shared automatically if their parent is already shared between the same devices.

Related: https://forum.syncthing.net/t/problems-with-versioning-in-nested-folders/16192

**Comment by AudriusButkevicius** [comment]
Sorry but no, you should simply not have nested folders. Yes, they are supported and they sort of work, but we are not going to special case them and add hairy logic around them just because you chose to use them.

**Comment by tomasz1986** [comment]
Yeah, I understand that nested folders are not the recommended configuration, but there are cases where you simply cannot change the existing folder structure, and still need to share some of the subfolders. I can be super careful not to share both the parent and the child folders between the same devices, but Introducer does not care, and shares them anyway.

Because of this, I have now decided to completely stop using Introducer in my personal network, as I do not think that there is any workaround for this. Although, to be fair, even if both the child and the parent are shared, Syncthing is still able to work properly, with the exception of some temp files hanging around for longer than necessary.

I think that I will try to add some kind of a warning against mixing Introducer with nested folders to the Docs (maybe under https://docs.syncthing.net/users/faq.html?highlight=nest#am-i-able-to-nest-shared-folders-in-syncthing?), just to be more aware of the potential issues.
