### ISSUE TITLE
New folder type: "on-demand"

### ISSUE THREAD

**Issue by crsaracco** [syncthing/syncthing#7341]
I'm thinking of the possibility of a new folder type: "on-demand". Assuming something like #4729 ("overview of all included and/or excluded files" / file browser) is implemented, a user could select which files they would like to sync using this browser/overview.

Some thoughts:

 - By default, Syncthing shouldn't automatically sync any files from this folder. The list of files should be synced as normal, so any device sharing on this folder can see a list of all files available to them.
 - `ignoreDelete` should probably be the default for this folder type. See "use cases" section below.
 - To interact nicely with the above two bullet points: when a device deletes a file, it should revert that file back to "don't automatically sync" locally. This avoids the weird `ignoreDelete` scenario where that file re-appears if it's changed again on another device.
 - When unchecking the "sync this file" box on a device, the user may wish to automatically delete that file, or keep it around un-synced. Might be an option for that folder type in the settings.

Related issues: #81 ("Selective download") and #193 ("Selective Sync"), but those got closed in favor of #2491 ("Next gen ignores"). Unless #2491 is an implementation detail that enables this feature, I think it's overly-complex for this use case: I don't need pattern matching / file extension rules, nor inclusion/exclusion mode (that can be achieved by choosing a different folder type).

#### Use cases

The general idea of this folder type is that you can connect all of your devices together and have a large list of files that you *could* have locally, without actually taking up the drive space on any of those given devices that this collection would require.

Some specific scenarios I thought of where this folder type might be useful:

 - Whenever I travel, I like to load my phone and laptop up with a small subset of my movies/TV/music collection so that I can use them when offline. Instead of physically plugging my phone in to transfer the files, and using some janky SCP/SFTP setup to transfer from linux desktop --> windows laptop, it would be nice to just check some boxes on these devices and let Syncthing sync the files up for me the night before I leave. This would also be nice on the return trip home, where I can use the hotel wifi to get a different subset of files. If I am syncing a document that I'm working on while traveling, this doc will automatically sync back up to my desktop when I'm online again.
 - Even when my phone is online, since the phone's space is considerably more limited than my desktop's, it would be nice to have *access* to files on my other computers, but select only a subset of that collection that I think I'll use in the near future.
 - Can allow friends to share files without requiring everyone push everything in that folder to everyone else's computer. Avoids having to email around files, or find some dedicated hosting. Also, these files are synced, so this avoids emailing something like "artwork-v1.png", "artwork-v2.png", etc. multiple times.

**Comment by AudriusButkevicius** [comment]
So new features etc should probably discussed on the forum first, but I don't see how this is different from selective sync.

Closing for now, please use the forum for further discussion.
