### ISSUE TITLE
Leading spaces in file names should not be trimmed in log/error messages

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7356]
This is super minor, but still.

![image](https://user-images.githubusercontent.com/5626656/107650374-c5537100-6cc1-11eb-9887-8a8e2c242949.png)
![image](https://user-images.githubusercontent.com/5626656/107650903-4c084e00-6cc2-11eb-8772-b444d6ed8179.png)

The file is actually called " %&()" (with a leading space, which even the GitHub's code formatting ignores). However, Syncthing reports it as just "%&()", with no spaces. This means that if I have two files - one with a leading space, and one without one - they both will be reported using the same name.

Tested with Syncthing v1.13.1.

**Comment by AudriusButkevicius** [comment]
I don't think its trimmed, I think the space is just ignored by html, as its not escaped

**Comment by tomasz1986** [comment]
You are right. The spaces are still there in the code, but they are not displayed in the GUI. I guess that setting `white-space: pre` in CSS could work. I will try playing around with it and see if this can be easily fixed without breaking anything else.

**Comment by calmh** [comment]
I don't think this is worth the effort fixing, unless by adding quotes or so which would make it visible as-is.

**Comment by tomasz1986** [comment]
I have had a look at it, and it can be done be wrapping the filenames in a `span` with `white-space: pre-wrap` applied to it. Of course, this would have to be all over the HTML code.

I do not think that this is worth doing just for leading spaces, but there could be files with multiple spaces in the middle like

```
hello                      world.txt
```

which right now get trimmed to

```
hello world.txt
```

so there is that. I am going to leave this alone for now though, as I doubt that anyone uses multiple spaces like that consciously…
