### ISSUE TITLE
External versioning command does not save from the Web GUI

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7361]
1. Try to set File Versioning to external with any command, e.g.

   ![1](https://user-images.githubusercontent.com/5626656/107839651-ae5f6c80-6df0-11eb-97eb-8e66986193af.png)

2. Click "Save".
3. Re-open the "Edit Folder" window and go to "File Versioning" again.
4. The command is blank. It is missing from `config.xml` also.

   ![2](https://user-images.githubusercontent.com/5626656/107839669-cb943b00-6df0-11eb-89e8-81adb67a3b1b.png)

I though that it could be my change (https://github.com/syncthing/syncthing/commit/5e9c7bc022040555d56860148352e5862737889f), but no, even after reverting the commit, the problem is still here. Basically, v1.13.1 works, but `main` (`80fc238be`) does not.

What is interesting is that if we add the command through `config.xml` directly, then it does stick (until we try to save any changes to the folder, that is, as then it gets cleared again).

**Comment by acolomb** [comment]
May be caused by restructuring in #7327? Sorry I can't look into the code today.
