### ISSUE TITLE
Disable (grey out) the Recent Changes button if there are no changes

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7368]
I think that it would be useful to have the "Recent Changes" button disabled when there are no changes recorded.

I have tried to play around with JS to achieve this, but with no success so far, so if someone has an idea on how to do this easily, please give me some hints (or pull a PR if that is easier).

Mock-up screenshot:

![1](https://user-images.githubusercontent.com/5626656/107907651-970eb380-6f97-11eb-8e5f-1c7df826dac7.png)

**Comment by calmh** [comment]
I'm not sure this would be a good change. Greyed out seems to mean "can't show recent changes" which is different from "there are no recent changes". The dialog should simply state there are no recent changes when opened.

**Comment by tomasz1986** [comment]
Hmm, my idea was that you could know that there were no changes without even pressing the button. If you have to press the button anyway, then I am not sure if this is worth the effort :sweat_smile:.

**Comment by calmh** [comment]
My point is that someone who didn't write the button logic can't know that, they just see that we won't show them recent changes for some reason. Though if we wanted to add a "this page intentionally left blank" to the empty recent changes dialog, that seems fine.
