### ISSUE TITLE
junctionsAsDirs requires Syncthing restart to trigger

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7371]
1. Add a new folder to Syncthing under Windows.
2. Enable `junctionsAsDirs` for the newly added folder.
3. Create a new junction in the folder using `mklink /j`.
4. Rescan the folder.
5. The junction has not been detected.

It seems that enabling `junctionsAsDirs` requires Syncthing to restart in order to actually trigger. After the restart, new junctions continue to be properly detected, so the issue seems to be limited only to enabling the option for the very first time.

Is this expected? If yes, then I will add this information to the Docs. If not, then I think that this should classify as a bug.

Tested with `main` (`v1.14.0-rc.1.dev.133.gfb078068`).

**Comment by calmh** [comment]
This is because (case insensitive) filesystems are cached and the cache key doesn't include options such as this. Probably the cache should be updated to take all options into account, maybe by transferring them into the filesystem URI.
