### ISSUE TITLE
Cannot Visibly Fully Sync When Using Ignore Patterns

### ISSUE THREAD

**Issue by davidpgil** [syncthing/syncthing#7392]
I am currently using Syncthing to sync GOG (gog.com) local downloads between one Windows 10 computer and another Ubuntu 18.04 based computer and the following combination seems to always display that 100% of files are not synced eventhough when I check the folders it seems to have synced. I think this issue is that I have the following ignore pattern:

```
!**Downloads
**
```

What I think I am doing here is saying, inside of the folder only sync the contents of the folders (recursively) that match the name "Downloads" and nothing else.

This seems to cause the folder to be locked at a certain percent synced eventhough I was able to sync all of the files I intended to sync. It seems the percentage displayed doesnt take into consideration that the ingore files should not be included in the displayed total percentage (in my opinion). 

Note that I do NOT want to auto delete files that I don't intend to sync. I just thought I would report this issue because Syncthing does not seem to be displaying the correct sync percentage in this case.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
