### ISSUE TITLE
use a .stfolder to keep all syncthing related files inside...

### ISSUE THREAD

**Issue by ozburn** [syncthing/syncthing#7396]
### Include required information
     set the directory to root:root 750 ( Ex /mnt/sftp_share/)
     run syncthing as another user , not root user.! ( Ex User user_sync ).
     share this folder as a synchting shareable folder.
     
With the scenario above, if you configure chroot on SFTP(using SSH ) to the same root directory on the Example above, syncthing can't write anything on root( Ex /mnt/sftp_share/), but if all Syncthing needs is written inside .stfolder (/mnt/sftp_share/.stfolder/) , we can manually create the .stfolder and set to 770 to the same user running syncthing service, and everything will work without break sftp chroot needs... 

SFTP require no other group than root, and NO  write group permissions on this root director.

I mean, i manually create the .stfolder with Owner and Group to the same Syncthing running service user(770 too)  and it work, but as syncthing use the / Directory ( Ex. /mnt/sftp_share/)  for temporary files and the .stignore, i have problem and syncthing can't work to sync that specfic shared folder...

It will be very good , if All used syncthing control files for every shared folder , live inside the unique folder /.stfolder/

Hope its not so confusing, sorry my Bad English an synchting is Awesome.!! Thanks for the eternity for this peace of Art.

I know maybe this scenario is low on usage, but at the same time, i believe it will keep syncthing working files for every shared folder in a more organized way,

Please be sure to include at least:

 - what problem your new feature would solve
      Possible to use the same SFTP chroot folder to share over syncthing..

 - how or why you think it is generally useful (i.e., not just for you)
      Everyone that run another service using the same syncthing shared folder structure with group restrictions, like at the same time we sync ou folder wwith another syncthings peers, i can share the same folder as a SFTP service for this example.
       And i believe, using a subfolder to keep all syncthing needs for share a folder.. Is not a Bad ideia, because at last you can manually contro the access to this folder and block normal user, other programs, to access and delete inside thie .stfolder.
 
   
 - what alternatives or workarounds you considered
    can't find one yet :/

Thankyou again, you guys Rock...!

Cya Ozzy.

**Comment by AudriusButkevicius** [comment]
Dup of #6001 and #2208
