### ISSUE TITLE
Android Operation Not Permiited (setting perms on temp file)

### ISSUE THREAD

**Issue by Bietola** [syncthing/syncthing#7398]
I am using syncthing Android version 1.13.0 on an HUAWEII CRR-L09 (Android version 6.0).

I tried to sync a folder from my laptop and the process failed with the following error message:

![photo5884115190365140223](https://user-images.githubusercontent.com/22653028/108849989-1aa55180-75e3-11eb-870e-8926dd7e3bcf.jpg)

It might be important to point out that my phone is rather old (see the model info above) and also I am trying to sync on my phone's SD card.

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
