### ISSUE TITLE
Syncthing relay does not run according to command line options

### ISSUE THREAD

**Issue by joker349** [syncthing/syncthing#7401]
What happened: I am running syncthing relay on my VPS as a systemd service:

```
[Unit]
Description=Syncthing Relay Server
After=network.target
Documentation=man:strelaysrv(1)

[Service]
User=syncthing
Group=syncthing
WorkingDirectory=/var/lib/syncthing/relaysrv
EnvironmentFile=/etc/default/syncthing-relaysrv
ExecStart=/usr/bin/strelaysrv ${STRELAYSRV_OPTS} -provided-by 'Mumbai, India' -global-rate '52428800' -protocol tcp
Restart=on-failure
Nice=19

[Install]
WantedBy=multi-user.target
Alias=strelaysrv.service
```

Output of `therifleman.name:22070/rest/system/status`:  

```
{
    "buildDate": "2019-12-11T12:30:36+05:30",
    "buildHost": "debian",
    "buildUser": "debian",
    "bytesProxied": 11400,
    "goArch": "amd64",
    "goMaxProcs": 2,
    "goNumRoutine": 68,
    "goOS": "linux",
    "goVersion": "go1.13.5",
    "kbps10s1m5m15m30m60m": [
        0,
        0,
        0,
        0,
        0,
        0
    ],
    "numActiveSessions": 3,
    "numConnections": 24,
    "numPendingSessionKeys": 0,
    "numProxies": 5,
    "options": {
        "global-rate": 0,
        "message-timeout": 60,
        "network-timeout": 120,
        "per-session-rate": 0,
        "ping-interval": 60,
        "pools": [
            "https://relays.syncthing.net/endpoint"
        ],
        "provided-by": ""
    },
    "startTime": "2021-02-24T14:43:07.5398316+05:30",
    "uptimeSeconds": 506,
    "version": "v1.1.4-ds1"
}
```

Problem: as you can see, the values on cmd does not match from the output of status. I can confirm the same thing on `http://relays.syncthing.net/`

### Include required information

Please be sure to include at least:

 - syncthing-relaysrv `1.1.4~ds1-4ubuntu1` and Ubuntu 20.04.2 LTS
 - what happened (mentioned above)
 - what you expected to happen instead: syncthing should follow command line options and broadcast provider value on relay status page
 - any steps to reproduce the problem: you can refer my systemd service unit file

**Comment by AudriusButkevicius** [comment]
This is packaged by debian, not us, so it's not something we can fix. If you are looking for help how to fix this, I suggest you use the forum.
