### ISSUE TITLE
Mark sync-conflict files with both devices participating in the conflict

### ISSUE THREAD

**Issue by markwmuller** [syncthing/syncthing#7405]
Currently, when a file is in conflict, a new file is created with the name pattern `<filename>.sync-conflict-<date>-<time>-<modifiedBy>.<ext>`. This file is then synchronized across all devices. 

An issue comes up if there are many devices, and a user detects a conflict, but isn't sure why it is in conflict. The user can now debug and find out one of the parties involved in the conflict (`<modifiedBy>`) but cannot easily understand with whom that file conflicted. 

I suggest modifying the conflict naming to be `<filename>.sync-conflict-<date>-<time>-<modifiedBy>-<conflictsWith>.<ext>`, i.e. adding the device ID on which the conflict is detected. The user can then immediately look only at these two devices to try and debug their system for unexpected conflicts. 

The only downside I can see is that the files will have even more unwieldy names, but they're already pretty long. 

Background -- I keep having unexpected conflicts appearing, and it's very hard to debug. See forum post here https://forum.syncthing.net/t/debugging-sync-conflicts-appearing-on-an-android-device/16398/4

**Comment by calmh** [comment]
Is encoding this into the file name the best solution, or would it be equivalent or better to for example log something verbosely when a conflict is created, showing all the known file metadata at that point?

**Comment by calmh** [comment]
Is encoding this into the file name the best solution, or would it be equivalent or better to for example log something verbosely when a conflict is created, showing all the known file metadata at that point?

**Comment by markwmuller** [comment]
From my perspective, I like the file name solution, because it's right there when I notice the conflict. It also seems like a relatively minimal change to what exists now. 

Of course, having verbose logs to inspect is also great, but usually requires a little more know-how from a user. Perhaps both? 

Apologies if the logs already exist, and I'm just ignorant of them.

**Comment by AudriusButkevicius** [comment]
This info is already available in the api tho, so I'm more inclined to keep it as it is, and add an easy way to look this up via the cpi

**Comment by calmh** [comment]
Most regular users aren't going to go digging in the API though. Another option, adding some clutter, would be to add a metadata text file beside the conflict file, containing the information on both sides of the conflict (times, sizes, devices, versions) and the outcome of the resolution. Of course a lot of people are going to hate that so it would need to be very optional.

**Comment by AudriusButkevicius** [comment]
God no.

**Comment by tomasz1986** [comment]
I would really avoid creating additional text files or such. Regular users get extremely confused by any additional files appearing in their folders. Also, especially in Windows, if the files are sorted by type, then the two will not be displayed next to each other, so they may not even be able to realise the connection.

The API approach is great for programmers and such, but "normal" people have no idea how to use the command line, and it is good to remember that they may be using Syncthing, e.g. to sync files on mobile devices only, where accessing the CLI is a major headache (if possible).

Anyway, I would personally agree that having the two IDs included right there in the filename would be very helpful.

**Comment by ProactiveServices** [comment]
> Most regular users aren't going to go digging in the API though.

This would mean that wrappers could utilise it to present the info to the user in their preferred GUI, including with desktop notifications etc.

**Comment by ProactiveServices** [comment]
One potential problem with adding more data into the file name (and the way conflicts are shown now) is that it isn't very informative for the non-technical user. I like the idea of a verbose log but the log is a bit transient and may not be watched by the user.

There's been talk of `.stfolder` being used for more than just a marker. The "add a note into a metafile" could be dropped into .stfolder, and the GUI (and wrappers) could then check for existing metafiles in here and then display them in the GUI to make obvious that there's something to be read. This would also have the bonus of making such notes less transient than the current logs.

**Comment by KhalilSantana** [comment]
How about adding a xattr (extended attribute) in the conflict file instead? (Yes I'm aware syncthing currently doesn't sync xattrs, #2698)

This way we avoid using an extra file (which is clunky, albeit very cross-platform), but we still make the information more or less 'accessible' without making the file path even longer.

I know xattrs aren't supported everywhere, but this sounds like exactly the type of problem I'd use a xattr to solve.

Then we could either have a "Conflict solver" app, or ask nicely for the file browser apps (Dolphin, Thunrar, etc) to display this information in a more user-friendly way than getfattr(1)

**Comment by thomasmerz** [comment]
> This info is already available in the api tho, so I'm more inclined to keep it as it is, and add an easy way to look this up via the cpi

@AudriusButkevicius , I found nothing in detail about how to get more details about file conflicts. I also have sometimes some conflicts, but with files that only get written on my main linux system and are only synced for backup-purpose to some other linux/macOS machines. Therefore I really have no clue what and who caused such file conflicts 🤔

**Comment by calmh** [comment]
I think we'll not add more stuff to the filename, and anyway "both" is a slippery concept as it may be a conflict between me on the one side and twelve other devices on the other side...
