### ISSUE TITLE
Add UPnP support for IPv6

### ISSUE THREAD

**Issue by otbutz** [syncthing/syncthing#7406]
At the moment only IPv4 is supported via UPnP. It would be really helpful to also add UPnP pinhole support in order to control the firewall of the router and allow incoming traffic directly to the device.

Relying only on IPv4 is not an option for devices stuck behind a dualstack lite connection as incoming IPv4 connections are blocked by Carrier Grade NAT.

See http://upnp.org/specs/gw/UPnP-gw-WANIPv6FirewallControl-v1-Service.pdf

**Comment by ryannathans** [comment]
After troubleshooting all day, I have found this - no pin-holing support. +1 for this

**Comment by bt90** [comment]
https://app.bountysource.com/issues/96922831-add-upnp-support-for-ipv6

**Comment by calmh** [comment]
Fixed in #9010

**Comment by bt90** [comment]
@maxi0604 don't forget to claim your bounty :wink:
