### ISSUE TITLE
.stversions and Windows User AppData Syncthing folder equals amazingly huge drive waste

### ISSUE THREAD

**Issue by Xavron** [syncthing/syncthing#7411]
Latest or next to versions of Syncthing on Windows and Linux

1) Guess you enable versioning and then backup the Windows User folder to another computer.

2) Watch Syncthing folder in .stversions increase to ultra horrible size.

Currently the Syncthing folder in .stversions sits at 100GB after deleting maybe 17GB of .log files. The total of what I backup is only 76.6GB right now. Without the Syncthing folder, .stversions is ONLY 4.3GB!

Two possible ways to fix this.

1) Stop including /User/AppData/Local/Syncthing in the first place. User should not have to ignore it by default. Most likely there's no use case for including itself. This probably shouldn't be needed for restoring files especially since they're stored unencrypted anyway.

2) Stop making such huge files. Just many of the .log files were over a GB in size. That's nuts for a log file. That's debugging size. Debugging appears to be disabled so I wouldn't want to see what that turns into.

If you can think of another way, go for it.

But watching the drive space of the receiving computer deplete at a high rate from Syncthing being included in .stversions is ridiculous. I consider this requiring an immediate fix. In no way should Syncthing ever have itself be more than the total of what's including or anywhere even close to it. Its nuts ;-)

The other way to think of it is that you have eg the normal files. Then the versioning files includes far too much from Syncthing. Lets just says its the normal files then a duplicate of all the files. And its still more than that in size lol.

I tell you. Didn't know the drive has nearly as much free space as it should. Fix this, I think you will make a lot of people happy. They will get space they never knew they had. Can't imagine how much space some people will get back. Just can't.

By the way, I have versioning only set to 2 for that transfer. Even if half the files required 2 versions each at 40GB * 2 (and this isn't the case), Syncthing is creating more wasted space than that of itself.

Also that's a bad toll on ssd writes.

I just about can't recommend Syncthing to anyone for this at this time with versioning enabled without additional setup.

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by Xavron** [comment]
Syncthing is eating space and its not a bug? lol

**Comment by Xavron** [comment]
I'm not jumping through hoops here. Your users can continue to get space eaten. That's your problem not mine anymore.

**Comment by AudriusButkevicius** [comment]
I think whats happening here is you are asking syncthing to version its own database effectively. 

Every time there is a change, it produces a new version, which updates the database, which produces a new version of a database file, etc. Even if you set it to keep 2 copies, the files are uniquely named, so they sre effectively kept forever.

We already print a warning if user somehow manages to point syncthing at a directory tree that includes it's own files.

Also, syncing directories in AppData with versioning is mad in general, as tons of things create temporary uniquely named files there that will be versioned for no reason.

**Comment by Xavron** [comment]
That's a better response than the above anyway so at least for that you have a :-)

But, I can't use Syncthing like this. This use is too broken in my opinion and I view it as a bug. Its not usability. Its literally Syncthing itself. Users should have nothing to do with it.

I'm moving on from it as it will still have the excessive and meaningful disk writes on the sending computer.

All the best. Thanks for the better response.
