### ISSUE TITLE
GUI does not work with ipv6

### ISSUE THREAD

**Issue by digitalatigid** [syncthing/syncthing#7416]
### Include required information

This is `syncthing v1.13.1 "Fermium Flea" (go1.15.7 linux-amd64) unknown@unknown 1970-01-01 00:00:00 UTC` on void linux and firefox 85.0.1.  

I am having trouble connecting to the gui over ipv6. I started syncthing as `syncthing -gui-address="http://[::]:8384"` and went to http://[::1]:8384 in my browser. The site loads and I get prompted for my username and password. However, it does not find the device name, does not load statistics and I ca not go into the settings. The networking console shows many 200 and then 403 for http://[::1]:8384/rest/events?limit=. The ipv4 gui works fine, ipv6 data transfer works fine too. I'm using localhost here for testing purposes, but want to use a private ipv6 network if everything works.

syncthing log:
```
$ syncthing -gui-address="http://[::]:8384"
[start] 17:53:01 INFO: syncthing v1.13.1 "Fermium Flea" (go1.15.7 linux-amd64) unknown@unknown 1970-01-01 00:00:00 UTC
[7NYGG] 17:53:01 INFO: My ID: 7NYGGC2-QWP7WYG-T74TQFC-JTNZZBD-X56YYXB-TWZJW7S-3UYEXFB-LR7YFAS
[7NYGG] 17:53:02 INFO: Single thread SHA256 performance is 222 MB/s using minio/sha256-simd (174 MB/s using crypto/sha256).
[7NYGG] 17:53:03 INFO: Hashing performance is 190.53 MB/s
[7NYGG] 17:53:03 INFO: Overall send rate is unlimited, receive rate is unlimited
2021/03/01 17:53:03 connection doesn't allow setting of receive buffer size. See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
[7NYGG] 17:53:03 INFO: Ready to synchronize synced (sendreceive)
[7NYGG] 17:53:03 INFO: QUIC listener ([::]:22000) starting
[7NYGG] 17:53:03 INFO: TCP listener ([::]:22000) starting
[7NYGG] 17:53:03 INFO: Completed initial scan of sendreceive folder synced
[7NYGG] 17:53:03 INFO: GUI and API listening on [::]:8384
[7NYGG] 17:53:03 INFO: Access the GUI via the following URL: http://[::1]:8384/
[7NYGG] 17:53:03 INFO: My name is "orchid"
```

**Comment by calmh** [comment]
Looking at this, the reason is that when browsing `[::1]:8384` the browser or GUI Javascript doesn't set the `X-CSRF-Token` request header, so the request gets blocked with a CSRF error. When browsing `127.0.0.1:8384` it works as expected. I'm not sure where the actual problem is, though.

**Comment by calmh** [comment]
Looking at the developer console in Safari I can see that it does not consider any cookies set when visiting `[::1]`. When browsing `127.0.0.1` it shows cookies as expected. When looking with curl I see proper `Set-Cookie` headers from the server in both cases, so I dunno. 🤷

**Comment by calmh** [comment]
Looking around it seems to be a vague situation if cookies are ever expected to work on plain IP addresses. I don't think this is our bug, but I also don't really see anything authoritative in either direction.

**Comment by digitalatigid** [comment]
The gui works fine when using a domain name that points to an ipv6 address. This solves the issue for me. Since calmh established that this isn't a bug in syncthing either, I'll close this issue.

Thanks for the help!
