### ISSUE TITLE
Add file picker to set folder root path

### ISSUE THREAD

**Issue by breversa** [syncthing/syncthing#7418]
This is the continuation of https://github.com/syncthing/syncthing/issues/160 : as of v1.14.0, there is still no file picker to select the path.

Syncthing is not trivial to the everyday user, but they can eventually get around it. However, most of my users have pretty much no idea what is a path… though they totally can navigate a directory hierarchy with a graphical tool. :-)

**Comment by tomasz1986** [comment]
> However, most of my users have pretty much no idea what is a path…

This is 100% true. I would say that with the advent of smartphones, people seem to be actually becoming less computer-literate than before, and that includes even very basic terminology that seems obvious for more technical users.

**Comment by AudriusButkevicius** [comment]
Dup of #2958, please search before opening issues.
If it looks obvious, it probably is, and there already exists an issue for it.
