### ISSUE TITLE
PostScript type1 Font files do not sync properly. 

### ISSUE THREAD

**Issue by martinackerl** [syncthing/syncthing#7425]
- v1.13.1, macOS (64-bit Intel/AMD)
 - MacOS 10.14.6

Problem:
PostScript type1 Font files do not sync properly. The synced file on the target computer has 0 bytes.

 - what you expected to happen instead, and
The synced file should have the same byte size as the original file

 - any steps to reproduce the problem.
Try to sync a PostScript type1 Font file from one MacOS computer to another.

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by martinackerl** [comment]
Thank you for your quick answer.

Found this in the meantime:
> Type 1 PostScript fonts often use the MacOS Resource fork to store their data. This part of the filesystem isn't always handled well by Unix tools, unless they are explicitly written to cope with Mac resource forks.
> 

I thought the handling of MacOS Resource fork data could be a feature that is worth being implemented. 
From the user point of view it looks as if syncthing is damaging font files.
If it is your decision to not support it, I can live with it.

**Comment by calmh** [comment]
Yeah, resource forks are a documented "not synced" aspect and not something we're looking to implement.
