### ISSUE TITLE
add Ignore Patterns to Folder Defaults

### ISSUE THREAD

**Issue by Redsandro** [syncthing/syncthing#7428]
It would be nice to input a default set of Ignore Patterns for newly added folders that you would otherwise manually apply to every share you add. E.g.:

__Settings__ :arrow_right: __Default Configuration__ :arrow_right: __Edit Folder Defaults__ :arrow_right: __Ignore Patterns__

For example, I always add this by default. Sometimes I forget, causing certain peers to exceed their free disk space.

```
(?d).Trash-*
(?d).sync.ffs_db
(?d)tmp
node_modules
bower_components
lost+found
*.bak
*.delme
```

This template would then be copied to the added folder ignore patterns where it can be edited. A new installation of Syncthing could add some sane defaults for the user, or just leave it empty.

**Comment by Script-Mak3r** [comment]
Just an FYI, but not something that I would think invalidates this feature request.
You can use a separate, syncable text file that has your default ignore pattern, and reference that in the .stignore file using the `#ignore` syntax. For exact usage, see the [documentation](https://docs.syncthing.net/users/ignoring.html).

**Comment by bugith** [comment]
https://github.com/syncthing/syncthing/issues/7428#issuecomment-791442987
You meant "#include" isn't it ?

**Comment by bugith** [comment]
> ...
> ...and reference that in the .stignore file using the `#ignore` syntax...
You meant "#include" isn't it ?

**Comment by Script-Mak3r** [comment]
> You meant "#include" isn't it ?

Yes, it seems so; I don't know what I was thinking.

**Comment by bugith** [comment]
> ...I don't know what I was thinking.
I bet surely include exclusions ;-)
