### ISSUE TITLE
"Ignore Patterns" tab disappears after visiting "Folder Defaults"

### ISSUE THREAD

**Issue by Redsandro** [syncthing/syncthing#7429]
### Include required information

 - Syncthing v1.14.0, Linux (64-bit Intel/AMD)
 - Browser Chrome 88.0.4324.182 (Official Build) (64-bit)

### How to reproduce

* Go to __[any shared folder]__ :arrow_right: __Edit__ 
* Observe tab _"Ignore Patterns"_
* Go to __Settings__ :arrow_right: __Default Configuration__ :arrow_right: __Edit Folder Defaults__
* Observe _no_ tab _"Ignore Patterns"_ (by design I guess)
* Go to __[any shared folder]__ :arrow_right: __Edit__ again
* Observe previously visible tab _"Ignore Patterns"_ is now gone.

---

I found this bug when checking the proper names to mention in this feature request: https://github.com/syncthing/syncthing/issues/7428

**Comment by tomasz1986** [comment]
I have encountered the same, but was unsure where it had come from. As a workaround, refreshing the browser brings the tab back.

**Comment by Redsandro** [comment]
> As a workaround, refreshing the browser brings the tab back.

Confirmed

**Comment by Redsandro** [comment]
Thank you for the quick fix @imsodin :+1:

**Comment by imsodin** [comment]
Credit goes to @acolomb for the fix, I just merged it - apparently github attributes the latter.
