### ISSUE TITLE
Syncthing 1.14.0 crashes with error "Symbol not found: _clock_gettime" starting on OSX 10.10.5

### ISSUE THREAD

**Issue by tonirug** [syncthing/syncthing#7436]
Hi, since the last update Syncthing does start anymore on my Mac. The error is reported in the subject and details in the attachment.
I have temporarily downgraded to version 1.13.1, which works fine.
Details on OS X version and error in the attached files.
Thanks in advance for your help.

[Symbol not found  _clock_gettime.txt](https://github.com/syncthing/syncthing/files/6092176/Symbol.not.found._clock_gettime.txt)
![Schermata a 2021-03-05 18-22-56](https://user-images.githubusercontent.com/19492480/110151749-22ce6f80-7de1-11eb-82e9-0322f6c19d5c.png)

**Comment by imsodin** [comment]
Since go1.15 (a while ago) only mac >=10.12 is supported: https://tip.golang.org/doc/go1.15#darwin Apparently we got lucky for now and it was still working. Now it isn't anymore. In half a year with go1.17, the requirement will be >=10.13: https://tip.golang.org/doc/go1.16#darwin
