### ISSUE TITLE
Allow database to be an external volume

### ISSUE THREAD

**Issue by PaulCyberEngel** [syncthing/syncthing#7437]
I've been using Syncthing for a while, and I'm just now implementing a Docker solution.

While putting the default folder externally is documented, I want to be able to use a shared volume for the database as well. That way I can implement Syncthing in a swarm and have it restart on another node without having to reinitialize.

**Comment by calmh** [comment]
You can put the database where you like, as long as it behaves like a local filesystem.

**Comment by AudriusButkevicius** [comment]
I think if there is any follow up to this, it's best suited for the forum, as it will likely be a form of a question, hence closing.

**Comment by PaulCyberEngel** [comment]
Except the forum appears to deal with Syncthing issues and this is a question about this docker config.

The config & database are usually in a user directory, but there is nothing in the documentation that tells me what user is being used. Since I cannot open a console to inspect what's going on in the OS, it would be helpful if you documented where you put the config & database so they can be mounted externally.

**Comment by AudriusButkevicius** [comment]
Questions go on the forum.

This issue tracker is for verified bugs or for feature requests (ideally that have been agreed on the forum).
Requests for improvement to the documentation go in the https://github.com/syncthing/docs repository.
