### ISSUE TITLE
bind LocalAnnounceAddress to interface

### ISSUE THREAD

**Issue by drwulsen** [syncthing/syncthing#7438]
Running *syncthing v1.14.0 "Fermium Flea" (go1.16 linux-arm) teamcity@build.syncthing.net 2021-02-26 12:21:13 UTC* on an *OpenWRT OpenWrt 19.07.7, r11306-c4a6851c72 WRT 1200AC* router, I noticed some oddness.

Local announce is supposed to only announce itself on LAN, especially if "AnnounceLanAddresses" is disabled.
(Which would, afaik announce the local addresses to the global disosrv)

However, I get a lot of these messages on my firewall:
*Sat Mar  6 13:46:33 2021 kern.warn kernel: [86237.801884] DROP wan in: IN=eth1.2 OUT= MAC= **SRC=MY-ROUTERS-WAN-IP DST=MY-ROUTERS-WAN-255** LEN=148 TOS=0x00 PREC=0x00 TTL=64 ID=40795 DF PROTO=UDP SPT=59644 DPT=21027 LEN=128*

which indicates that syncthing is running the "local" discovery on my WAN interface too, besides the LAN interface.

Would it be possible to add a "bind" option or even better to add an input similar to the "ListenAddress",
which would allow me to enter something like:
**192.168.1.1:21027, 192.168.2.1:21027**
to send/listen on my LAN and WiFi addresses without sending/listening on the WAN interface?

By default it could be set to **0.0.0.0:21027** so it would work on all interfaces as it is doing now.

That would be a very nice thing to have :)

Thank you for your time and efforts, this is a great project and I love it!

**Comment by calmh** [comment]
Syncthing indeed sends local discovery on all local interfaces. Running Syncthing *on* a router is sort of a niche case, and at that point the interface towards internet is also a local interface, indeed. I don't think we want to do something to change this, really.

**Comment by drwulsen** [comment]
Well if that isn't the quickest reply I've ever had from a developer - that was blazing fast!
To the router, all interfaces are local, so it makes sense.
I'm also thinking about a case of a server with multiple LAN ports, on which different networks are connected.
But then again my guess is, that syncthing would be running inside a VM with a single physical interface linked to it, so the situation I have doesn't happen again.

Well, I can live happy and adjust my firewall to just not log the dropped packets on WAN:21027 so I can read my logs again with ease.

Thank you for your quick, informative and friendly response!
