### ISSUE TITLE
The no-console flag seems to have stopped working on Windows

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [syncthing/syncthing#7446]
### Does your log mention database corruption?

It does not.

### Required information

**Syncthing** v1.15.0-rc.1. (I am unsure how I have ended up on a release candidate.)

**OS**: Windows 10

**Browser**: Firefox 86.0

What happens:

```
> C:\Portable_apps\syncthing\syncthing.exe -no-console -no-browser
> syncthing.exe: error: unknown flag --no-console
```

[Edited.]

**Comment by tomasz1986** [comment]
Just a side note, but right now Syncthing refuses to start outright if it detects an invalid flag. Would it cause any harm to simply ignore such and continue executing anyway? This would at least allow to keep running the software in such situations without any manual intervention.

**Comment by imsodin** [comment]
I see why it would be nice in this case, but in general I don't think it's a good idea. Imagine e.g. `--home`: If you have a typo there, Syncthing will start with config and db in the default location, which would work but not be the thing the user wants, i.e. quite confusing. Generally it would do something else than what the user intended it to do. In that case I rather have it not start at all.

**Comment by tomasz1986** [comment]
Yeah, I guess that there are drawbacks to both approaches.

I'm just worried that this could happen to a less important or rarely used flag, such as `logflags` or `log-max-old-files` (which I happen to use), and those are much less likely to get caught in the RC as quickly as the flag discussed here (which is probably one of the most used flags).
