### ISSUE TITLE
Can't accept untrusted folder from Web UI

### ISSUE THREAD

**Issue by zenitraM** [syncthing/syncthing#7449]
Steps to reproduce:
- Enable untrusted feature flag on both devices A and B, restart them
- Create a shared folder from device A from the UI
- Share it with device B, enabling the untrusted checkbox and entering a password
- Go to device B on web UI, try and accept the request to add the new folder

The result is that the window closes, but the folder is not added due to the following Javascript error:

Firefox backtrace:
```
Error: folderCfg.versioning is undefined
$scope.saveFolder@http://127.0.0.1:8384/syncthing/core/syncthingController.js:2096:13
$parseFunctionCall@http://127.0.0.1:8384/vendor/angular/angular.js:12493:18
callback@http://127.0.0.1:8384/vendor/angular/angular.js:21719:19
$eval@http://127.0.0.1:8384/vendor/angular/angular.js:14589:28
$apply@http://127.0.0.1:8384/vendor/angular/angular.js:14688:23
ngEventHandler/<@http://127.0.0.1:8384/vendor/angular/angular.js:21724:23
dispatch@http://127.0.0.1:8384/vendor/jquery/jquery-2.2.2.js:4755:27
add/elemData.handle@http://127.0.0.1:8384/vendor/jquery/jquery-2.2.2.js:4567:28
```

Chromium backtrace:
```
TypeError: Cannot set property 'type' of undefined
    at Scope.$scope.saveFolder (syncthingController.js:2096)
    at $parseFunctionCall (angular.js:12493)
    at callback (angular.js:21719)
    at Scope.$eval (angular.js:14589)
    at Scope.$apply (angular.js:14688)
    at HTMLButtonElement.<anonymous> (angular.js:21724)
    at HTMLButtonElement.dispatch (jquery-2.2.2.js:4755)
    at HTMLButtonElement.elemData.handle (jquery-2.2.2.js:4567)
```

I have tried a couple times deleting and recreating the folder from device A but I get always the same result on the UI for device B, as well as when trying to add the folder manually specifying the device ID. 

Tested on Syncthing version `v1.15.0-rc2` running on both nodes and recent versions of Firefox/Chromium on Linux.

**Comment by imsodin** [comment]
Thanks for catching and reporting!

Affects any folder that has no versioning. Regression introduced in #7384, i.e. v1.15.0.
