### ISSUE TITLE
strelaysrv v1.14.0 failing to load

### ISSUE THREAD

**Issue by FFourtyTwo** [syncthing/syncthing#7451]
**Which version of Syncthing and what operating system you are using:**
**OS:** Debian Testing (Bullseye) with all latest updates
**GO:** tried 1.15.8 from testing or 1.16.0 from unstable, nothing changes
**strelaysrv:** v1.14.0 

**What happened:**
Freshly built strelaysrv v1.14.0 don't want to start thoroughly. Loading process freezes and don't show the connection link.

**Steps to reproduce:**
1. git checkout v1.14.0
2. go run build.go
3. systemctl start strelay.service - handmade systemd script with following command:
`ExecStart=/srv/syncthing/bin/strelaysrv -keys=/srv/syncthing/relay -pools="" -status-srv="" -protocol=tcp4 -listen=10.10.20.10:22067 -ext-address=xxx.xxx.xxx.xxx:22067 -debug`

4. tail -f /var/log/syslog:
```
Mar 11 12:17:17 ftpve systemd[1]: Started Syncthing Relay Server.
Mar 11 12:17:17 ftpve strelaysrv[32158]: 2021/03/11 12:17:17 main.go:140: strelaysrv v1.14.0 "Fermium Flea" (go1.16 linux-amd64) root@ftdebdesk 2021-02-26 12:21:13 UTC [purego]
Mar 11 12:17:17 ftpve strelaysrv[32158]: 2021/03/11 12:17:17 main.go:146: Connection limit 419430
Mar 11 12:17:17 ftpve strelaysrv[32158]: 2021/03/11 12:17:17 main.go:185: ID: HR3QXIF-HOMCBFR-UT2GZG4-QFQKAQ5-VVYH54F-6DVGSSX-XXXXXXX-XXXXXXX
```
5. netstat -tunap | grep str - empty output
6. That's all, it won't load further

**Steps to fix:**
1. git checkout v1.13.1
2. go run build.go
3. systemctl start strelay.service - handmade systemd script with following command:
`ExecStart=/srv/syncthing/bin/strelaysrv -keys=/srv/syncthing/relay -pools="" -status-srv="" -protocol=tcp4 -listen=10.10.20.10:22067 -ext-address=xxx.xxx.xxx.xxx:22067 -debug`

4. tail -f /var/log/syslog:
```
Mar 11 12:23:34 ftpve systemd[1]: Started Syncthing Relay Server.
Mar 11 12:23:34 ftpve strelaysrv[9370]: 2021/03/11 12:23:34 main.go:140: strelaysrv v1.13.1 "Fermium Flea" (go1.16 linux-amd64) root@ftdebdesk 2021-01-11 14:15:21 UTC [purego]
Mar 11 12:23:34 ftpve strelaysrv[9370]: 2021/03/11 12:23:34 main.go:146: Connection limit 419430
Mar 11 12:23:34 ftpve strelaysrv[9370]: 2021/03/11 12:23:34 main.go:185: ID: HR3QXIF-HOMCBFR-UT2GZG4-QFQKAQ5-VVYH54F-6DVGSSX-XXXXXXX-XXXXXXX
Mar 11 12:23:34 ftpve strelaysrv[9370]: 2021/03/11 12:23:34 main.go:237: URI: relay://xxx.xxx.xxx.xxx:22067/?id=HR3QXIF-HOMCBFR-UT2GZG4-QFQKAQ5-VVYH54F-6DVGSSX-XXXXXXX-XXXXXXX&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=0&statusAddr=&providedBy=
```
5. netstat -tunap | grep str:
`tcp        0      0 10.10.20.10:22067       0.0.0.0:*               LISTEN      9370/strelaysrv`
6. Working as expected

**Comment by calmh** [comment]
Thanks, good report, fixed. :)

**Comment by FFourtyTwo** [comment]
You welcome :)
