### ISSUE TITLE
Syncthing v1.15.0-rc.3 crashes instantly on Windows

### ISSUE THREAD

**Issue by Nnnes** [syncthing/syncthing#7455]
```
C:\Users\Main\Desktop\syncthing-windows-amd64-v1.15.0-rc.3>syncthing.exe
Exception 0xc0000005 0x0 0x7ff8f3090fff 0x20175650000
PC=0x20175650000

syscall.loadlibrary(0xc00012e5b8, 0x0, 0x0)
        runtime/syscall_windows.go:296 +0xe5
syscall.LoadDLL(0x14d5a29, 0x9, 0xd, 0xc000126920, 0x0)
        syscall/dll_windows.go:85 +0x3b8
github.com/go-ole/go-ole.init()
        github.com/go-ole/go-ole@v1.2.4/variables.go:12 +0x526
rax     0x7ff8f0fee398
rbx     0x7ff8f0fee396
rcx     0x41
rdi     0xffffffffffbadd11
rsi     0x0
rbp     0x0
rsp     0xfda91ff590
r8      0x0
r9      0x0
r10     0x0
r11     0x97c
r12     0xc000007a
r13     0x0
r14     0x7ff8f0fee398
r15     0x7ff8f2e90000
rip     0x20175650000
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b
```

Similar output for `syncthing.exe --version`. v1.15.0-rc.2 works normally.

**Comment by imsodin** [comment]
I cannot reproduce on win10 64bit.

What system are you on?

**Comment by Nnnes** [comment]
v1.15.0-rc.3 now runs normally on the same machine. I did not make any changes, only browsed some folders.

The machine is running 64-bit Windows 10 Pro 20H2 build 19042.867. I was also unable to reproduce on identical Windows builds.

**Comment by tomasz1986** [comment]
I can confirm that the current RC runs fine both in Windows 10 (x86/x64) and Windows 7 (x86).

You may want to check your hardware (CPU, RAM, disks) for any possible failures/defects.
