### ISSUE TITLE
Remove sub-second precision from the REST API rest/stats/device.

### ISSUE THREAD

**Issue by lockywolf** [syncthing/syncthing#7457]
### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using
1.14.0
 - browser and version, if applicable
curl 7.75.0
 - what happened,
```
curl -X GET -H “X-API-Key: mykey” -s ‘http://localhost:8384/rest/stats/device’ | sed ‘s/[^[:print:]]//g’ | jq -Mar -c ‘.“DEV-ID”.“lastSeen”’ | cut -c 2-36
```
returns strings like: `2021-03-11T21:10:02.48504855+08:00` or `2021-03-11T21:11:11.084428411+08:00`. (note the different lengths)

 - what you expected to happen instead, and
`2021-03-11T21:10:02+08:00`
It doesn't make sense to make "last seen" in nanoseconds, because tcp requests take longer. And some parsers choke on subsecond-precise dates. 
 - any steps to reproduce the problem.
https://forum.syncthing.net/t/what-is-the-easiest-way-to-find-out-the-last-seen-timestamp-for-a-device-without-a-browser/16484/4

**Comment by lockywolf** [comment]
Additionnally, there seem to be some non-printing characters in the output that break my terminal.  I sanitize them with the sed insert, but I think that it is syncthing's problem. But maybe not! (Maybe it's jq's problem, or I broke my setup myself, so I'm not reporting this.)

**Comment by tomasz1986** [comment]
Just a side note, but you have typographic quotation marks in your code, e.g. `“”` and `‘’` instead of `""` and `''`. This may or not may not be only a copy and paste related issue, but I would make sure that the code itself uses proper marks.

**Comment by lockywolf** [comment]
That's forum's behaviour. I copied the code from for forum.syncthing, not my terminal.

**Comment by calmh** [comment]
> there seem to be some non-printing characters in the output that break my terminal

I really don't think that's from the API.

**Comment by acolomb** [comment]
> Additionnally, there seem to be some non-printing characters in the output that break my terminal. I sanitize them with the sed insert, but I think that it is syncthing's problem. But maybe not! (Maybe it's jq's problem, or I broke my setup myself, so I'm not reporting this.)

`jq` outputs colored text by default on any kind of terminal. Try using the `-M` option to suppress that.
