### ISSUE TITLE
NonPaged memory leak

### ISSUE THREAD

**Issue by ilyr73** [syncthing/syncthing#7462]
I just noticed a NonPaged memory leak in Syncthing.exe v1.14.0. When the service is restarted it starts with 50k NonPaged memory pool usage, which goes up to 8000k within less than a day. The problem is easy to reproduce, just restart Syncthing service, wait a day and compare the NonPaged memory usage in Task Manager.

Using SyncTrayzor 1.1.28 with Syncthing 1.14.0 under Windows 10 version 2004 (Build 19041.804)

**Comment by AudriusButkevicius** [comment]
Why do you think its a leak? None paged memory is memory syncthing asked for but has been paged out.

**Comment by ilyr73** [comment]
Heya,

I am a bit more sensitive when checking NonPaged memory usage, because
despite normal memory usage, a high allocation of NonPaged pool can more
easly cause system instability. In some cases high allocation is normal,
but in case of Syncthing.exe the problem is not about the allocation
amount, but that it keeps increasing continuously and it does that when my
Syncthing client is sitting idle. If a memory usage is not stable and there
is only increase, no release, that's a pretty good sign of a memory
leaking... :) If you want, I can set up a performance counter to monitor
the process on my computer for a few days and make a diagram from the
NonPaged usage, but so far it seems to increase indefinitely.

Regards,

Csaba

**Comment by AudriusButkevicius** [comment]
8000k is not enough to even trigger GC in most cases I suspect, so it might not be a leak but just simply GC didn't run.

Once it gets into 100s of mbs to the point where it's am obvious leak, capture a memory profile (explained how in the docs) and start a thread on the forum.
