### ISSUE TITLE
Receive-encrypted fails after a while: file with empty block list

### ISSUE THREAD

**Issue by Z3r0byte** [syncthing/syncthing#7466]
### Does your log mention database corruption?
No

### Include required information
I have a setup of two machines and one untrusted server all running 1.14.0. I have enabled the untrusted feature flag on all machines.  
When syncing between the two trusted machines, everything goes fine and both machines indicate they're up to date. But, when syncing with the untrusted server using the receive-encrypted type, all connections start failing. I am syncing two folders and for both folders these kind of error messages start appearing on the untrusted server:
`[J47TR] 13:37:50 INFO: Connection to BWYS6XV-XXXXXXXXXXXXXXXXXXXXXXX-RP6EJAB at 141.xxx.xxx.xxx:22000-xxx.xxx.xxx.xxx:5068/tcp-client/TLS1.3-TLS_CHACHA20_POLY1305_SHA256 closed: protocol error: index update: "9.syncthing-enc/45/F31BH51JPLO2N7T7MJ03AQ56Q0IIM1CTNE9A38NRNAOIU19NB5LGKF093B6M6D4U6SP5LKTN5NFA9GHN1PK4SK8LFD0K1R9R9S0CQKQQ86T1D7P1HG415P20JD299GNPTJPD54QSP0DKMF9T9D4SRO116INLTOC7DMIKUN1F6AED4D2P27NG": file with empty block list`

I have tried pausing one folder to see if it was an error specific to one folder, but neither are able to fully sync after a couple of hundred MB's. I also tried changing the pull order of the folders, but to no avail. Removing and re adding the folders also did not work. Since the filename is encrypted, I also don't know what folder exactly it is getting stuck on. It does keep giving the same error with the same file name.

If there is any additional information needed, let me know and I'll try my best to give it to you.

**Comment by imsodin** [comment]
I think I know what the issue is: Do you have ignore patterns?  
I believe we drop the invalid flag from file infos sent, which results in a valid looking file without blocks. That then causes this error. Will repro and fix.

And general info on testing the untrusted feature:  
You should run release candidates, i.e. v1.15.0-rc.3 at the time of writing. As this issue shows, it is still in testing and there will be fixes for it, that you'll want to get promptly.

**Comment by Z3r0byte** [comment]
Thanks for your quick response. I indeed do have ignore patterns. I also thought of this and removed those patterns, but the issue persisted (but maybe I didn't give syncthing enough time to rescan). I will switch to rc builds and keep testing from there.
