### ISSUE TITLE
Improve UDP hole punching

### ISSUE THREAD

**Issue by bt90** [syncthing/syncthing#7471]
As discussed in https://forum.syncthing.net/t/a-few-questions-about-quic-hole-punching-and-stun we should turn up dialing frequency for QUIC endpoints to ensure that stateful firewalls keep our punched holes open.

I suggest that we aim for maxium delay between outgoing UDP packets of about 20s. This should be low enough for most firewalls to keep the port constantly open. e.g Linux netfilter has a default timeout of 30s. But i fear that consumer routers might even have lower limits so 20s should be a good compromise.

**Comment by AudriusButkevicius** [comment]
Have you verified if this has any effect at all? I mean changing the number with no evidence it actually helps, seems wrong.

**Comment by bt90** [comment]
See https://forum.syncthing.net/t/a-few-questions-about-quic-hole-punching-and-stun/16490/12?u=bt90

The connection could be established if the last UDP packet was not longer than about 30s ago transfered. This duration might be higher or lower for other cases but for me this guaranteed a successful connection.

For netfilter defaults: https://www.kernel.org/doc/Documentation/networking/nf_conntrack-sysctl.txt 

> nf_conntrack_udp_timeout - INTEGER (seconds)
	default 30

**Comment by AudriusButkevicius** [comment]
That doesn't say that you set the start delay and min delay to 30s and it magically worked.

**Comment by bt90** [comment]
No but i captured the traffic using Wireshark. In my case i could observe 10s off QUIC connection attempts followed by 70s of silence. With this pattern a regular Linux firewall would close the port for incoming traffic after 30s. So the port is open the 10s while the dialer tries to establish a connection and additional 30s until the timeout of conntrack kicks in. Following this pattern the port is actually closed for incoming traffic 50% of the time.

**Comment by AudriusButkevicius** [comment]
RIght, but we would observe that the external port has changed, and keep decreasing the time until we reach the 30s, so not sure what you want to change or why? Seems like a change just for the purpose to have a change.

**Comment by bt90** [comment]
We don't have have STUN for IPv6 connections so the hole punching solely relies on dialing attempts. I have yet to test this for IPv4 but i always get the same external port according to the STUN log. Which means that the test for changing ports would never fail and therefore we would always use the max interval of 180s. So i suspect that the situation regarding the firewall is not much better.

**Comment by AudriusButkevicius** [comment]
So what are you proposing?

**Comment by bt90** [comment]
We have to dial QUIC addresses at a higher frequency. This ensures that stateful firewalls keep the port open for incoming connections. Changing STUN paramerts doesn't help here as @calmh already explained in the forum.

STUN communication will only keep the port open for incoming packets originating from the STUN server itself. By dialing we send UDP packets to the other client which keeps the port open in the firewall for packets originating from the other client.

**Comment by AudriusButkevicius** [comment]
Do you have evidence that this would be helpful?

**Comment by bt90** [comment]
Most consumer routers nowadays ship with a stateful firewall. So the hole punching only works if you send packets to the other client. AVM(a very popular vendor here in Germany) uses SPI firewalls for its devices since 2012.  I would be a bit shocked to see a modern router without a stateful firewall to be honest.

**Comment by AudriusButkevicius** [comment]
Sure, but can you compile a custom version of syncthing and verify that it does indeed help?

**Comment by bt90** [comment]
Is there a setting i can modify to crank up dialing temporary? Should be enough to check if my phone can get a punched connection more reliably.

**Comment by bt90** [comment]
I can also test if packets sent from a thirdparty are able to pass my router while a device is connected via the punched hole. This should not be possible with a stateful firewall.

**Comment by imsodin** [comment]
Looking at the code I discovered we apparently do already have a knob for that: `reconnectionIntervalS`. It applies to all dials, which isn't what you want in the end, but for testing that should be fine.

**Comment by AudriusButkevicius** [comment]
Went digging through the code to find the same option.

**Comment by bt90** [comment]
> I can also test if packets sent from a thirdparty are able to pass my router while a device is connected via the punched hole. This should not be possible with a stateful firewall.

As expected. I can't send anything from an external server through the punched hole without prior dialing.

Code executed on the external server to simulate syncthing traffic:
````
echo -n "test" | nc -4u -w0 -p 22000 $SYNCTHING_EXT_IP 22000
````

Not a single packet shows up in Wireshark. But it works the moment i configured syncthing to dial the the IP of my external server.

**Comment by AudriusButkevicius** [comment]
Right, I guess I am more interested if it helps connect things or not.

Also, I guess what are you actually proposing we do here?
Set the redial interval to 25s?

**Comment by bt90** [comment]
Lowering the global pause between redials would solve it but only QUIC connections would profit from this. So if we want to avoid pointless dialing we should only dial QUIC connections at a higher frequency and don't change anything for TCP addresses.

If the current setting for `reconnectionIntervalS` is 60s why does Wireshark show pauses of around 70s in my IPv6 test scenario? 60s pause + 10s of preliminary dialing attempts to the IPv4 address? Is the number of devices and possible connections per device(tcp, quic) a factor here?

The overall goal should be to keep a flow of UDP packets to each client with a maxium pause suitable to keep the firewall open for incoming connections. For my hardware the upper limit seems to be 30s but i guess that there are consumer routeres out there with even lower timeouts. If it doesn't hurt we should aim a bit lower(20-25s) which would guarantee that the hole is open constantly.

**Comment by AudriusButkevicius** [comment]
Hole punching with TCP is also a thing that we attempt, so it might also benefit from this.
The extra 10s pause is because we dial protocols in order of preference, giving it 10s to connect, so 60s redial loop + 10s to realise tcp doesn't work, to try quic.

**Comment by AudriusButkevicius** [comment]
@calmh what's your feeling on this?

**Comment by calmh** [comment]
Each dialer can set their own next redial attempt, so this should be solvable for QUIC separately from TCP. If I remember correctly, even with a lower reconnection interval we only try the dialers that have requested a redial in the given timeframe. I think the damage from doing more frequent QUIC dials should be fairly small, we'll only do it when we're not connected to someone who's advertised a QUIC address.

I think TCP timeouts are generally much longer, even during the handshake phase, so perhaps we don't need to do anything there.

**Comment by AudriusButkevicius** [comment]
It would be interesting to check with wireshark what things look like for TCP.

**Comment by bt90** [comment]
I fear that holepunching won't work for TCP connections if a stateful firewall is involved. The dialing host would send `SYN` to initiate a TCP handshake and the firewall would only accept `SYN-ACK` coming from the other hosts.

**Comment by imsodin** [comment]
I might have missed it: Does it (quic conn in your ISP NAT) actually work with the lower reconnect interval? @bt90

**Comment by bt90** [comment]
I can establish a stable connection on IPv6 if the timing is correct. IPv4 is a different story as my mobile carrier uses symmetric NAT which combined with a stateful firewall seems to make a connection impossible.

**Comment by bt90** [comment]
Even if no stateful firewall is involved more frequent dialing should improve things for certain NAT types:

(Address)-restricted-cone NAT:
> An external host (hAddr:any) can send packets to iAddr:iPort by sending packets to eAddr:ePort **only if iAddr:iPort has previously sent a packet to hAddr:any**. "Any" means the port number doesn't matter.

Port-restricted cone NAT:
> An external host (hAddr:hPort) can send packets to iAddr:iPort by sending packets to eAddr:ePort **only if iAddr:iPort has previously sent a packet to hAddr:hPort**.

See https://en.wikipedia.org/wiki/Network_address_translation#Methods_of_translation
