### ISSUE TITLE
Better support for file moves across shares

### ISSUE THREAD

**Issue by kalsan** [syncthing/syncthing#7475]
Given the following three devices:
- Laptop
- Phone
- Tower PC

Given the following two shares on devices:
- Camera Roll (Phone, Laptop, Tower PC)
- Photo Archive (Laptop, Tower PC)

I now archive all pictures from 2020 by starting up the Laptop and moving them from Camera Roll to Photo Archive with the file manager. Through synchronization, the pictures are deleted from the phone and moved across folders on the Tower PC.

Assumption: the move is atomic, i.e. Syncthing did not detect the deletion before the creation and all files appear to it as moved from one share to another (from a file system point of view).

### Actual behavior

1. Photos are deleted from Phone and Tower PC
2. Photos are re-uploaded from Laptop to Tower PC (this time to the new share)

### Desired improved behavior

1. Syncthing detects that the photos that just appeared in the Photo Archive share are the same as those that disappeared in the Camera Roll Share
2. Pictures on phone are deleted as they would be today
3. However, the Syncthing instance on Tower PC calls a move (`mv`) operation on the files - the operation completes instantly and no files are transferred unnecessarily over the Internet.

That would be nice :-)

Cheers!
Kalsan

**Comment by calmh** [comment]
Folders are separate entities that run concurrently with separate modes, timing, versioning, sharing, whatnot. Coordinating moves between them requires synchronizing operations between separate folders, on both sides. I think doing that would have much wider reaching negative effects on the overall design than the slight positive of optimizing these moves.

**Comment by AudriusButkevicius** [comment]
As a workaround, if you have versioning enabled, you could add the versions directory as an unshared folder, and when downloading files, it would reuse content from the versions directory.

So data is reused between folders, but not renamed between folders.
This means that renames would effectively end up copies (on the remote side only) until the data in the versions folder is cleaned up.

**Comment by calmh** [comment]
That requires some very specific timing on when folders sync vs scan on the destination though.

**Comment by kalsan** [comment]
@calmh thank you for your reply!
@AudriusButkevicius that sounds interesting, have you done it in practice? What are your experiences?

**Comment by imsodin** [comment]
Please use the forum - https://forum.syncthing.net/ - for support and discussions like this. The forum has a lot more eyes and friendly people on it than the issue tracker. Thanks!
