### ISSUE TITLE
Syncthing not working on a Raspberry PI behind an nginx reverse proxy

### ISSUE THREAD

**Issue by MBurchard** [syncthing/syncthing#7479]
### Include required information
 - `cat /etc/os-release`
   ```
   PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
   NAME="Raspbian GNU/Linux"
   VERSION_ID="10"
   VERSION="10 (buster)"
   VERSION_CODENAME=buster
   ID=raspbian
   ID_LIKE=debian
   HOME_URL="http://www.raspbian.org/"
   SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
   BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
   ```
 - `uname-r`
   `5.10.17-v8+`
 - `syncthing -version`
   `syncthing v1.14.0 "Fermium Flea" (go1.16 linux-arm) deb@build.syncthing.net 2021-02-26 12:21:13 UTC [noupgrade]`
 - Firefox 86

### Nginx as reverse proxy

Because I have more services installed on the PI, I use Nginx as a reverse proxy.  
This is the configuration
```
server {
        listen 80;
        listen [::]:80;
        server_name sync.thing;
        autoindex off;

        location / {
                allow 192.168.178.0/24;
                allow fd00::/32;
                expires max;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_set_header Host localhost;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://localhost:8384/;

                proxy_read_timeout 600s;
                proxy_send_timeout 600s;
                deny all;
        }

        location ~ \.php$ {
                deny all;
        }

        location ~ /\.ht {
                deny all;
        }
}
```

### What happened?

- I'm able to access the url `http://sync.thing/`.
- It shows the expected page.
- I was able to setup a connection to an other Syncthing node.
- The choose folder was synced.
- Suddenly the display of all information disappeard.
- ![grafik](https://user-images.githubusercontent.com/4256302/111167762-b94d1e80-85a1-11eb-96aa-eaf9aa08bd17.png)
- In the Devtools I see thousands of requests
- ![grafik](https://user-images.githubusercontent.com/4256302/111168106-08934f00-85a2-11eb-8199-a85aecba0b85.png)
- When I open http://sync.thing/ in a private Browser tab everything works fine
- But also in the private Browser tab there are thousands of requests to `http://sync.thing/rest/events?since=19`

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by MBurchard** [comment]
@AudriusButkevicius  for me this thousands of request... a lot per second... look like a bug in the angular frontend

**Comment by AudriusButkevicius** [comment]
To me it doesn't, more like proxy/browser misconfiguration, especially it only happens in non-incognito, pointing at some browser plugin causing this.
