### ISSUE TITLE
Edit Folder Defaults dialogue opening instead of Folder Specific after opening Defaults

### ISSUE THREAD

**Issue by sembeeuk** [syncthing/syncthing#7480]
Title doesn't really explain it.
If I open Actions, Settings, and then under Default Configuration, select Edit Folder Defaults, then close it, then go to one of the specific synchronised folders and choose Edit, the same windows comes up - just with the paths changed to match the folder I am editing. Therefore missing the tabs for Ignore Patterns, and the Folder ID etc.

![SyncTrazor1](https://user-images.githubusercontent.com/25618369/111195703-7183c280-85b4-11eb-8e75-b7ff7c4844ba.PNG)

If I restart SyncThing from the menu, then it comes back as expected - and that is the only way I have found to reset it.

![SyncTrazor2](https://user-images.githubusercontent.com/25618369/111195719-78123a00-85b4-11eb-93f7-b8fa9cd5fc51.PNG)

I can repeat this on two different servers. 

Version: SyncThing: 1.14.0
OS: Windows Server 2019

**Comment by acolomb** [comment]
Looks like what was fixed in #7429. That only got into the v1.15.0 release, not the release candidates for v1.14.

**Comment by sembeeuk** [comment]
Didn't look at either the closed issues or the release candidates. I will close the bug and wait for v1.15.
