### ISSUE TITLE
1.15.0-rc.4 Crash on FreeBSD 12.2-RELEASE-p4

### ISSUE THREAD

**Issue by moviuro** [syncthing/syncthing#7486]
### Does your log mention database corruption?

No (?)

### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using : **v1.14 from https://github.com/syncthing/syncthing/releases/download/v1.14.0/syncthing-freebsd-amd64-v1.14.0.tar.gz** (which auto-upgrades to **1.15-rc.4**, see log below)
 - browser and version, if applicable : **N/A**
 - what happened, : **launching syncthing fails with the following trace**
 - what you expected to happen instead, and : **syncthing shouldn't crash**
 - any steps to reproduce the problem : **no idea** :disappointed:

```
% ./sync/syncthing-freebsd-amd64-v1.14.0/syncthing
[start] 14:04:10 INFO: syncthing v1.14.0 "Fermium Flea" (go1.16 freebsd-amd64) teamcity@build.syncthing.net 2021-02-26 12:21:13 UTC
[start] 14:04:11 INFO: Upgrade available (current "v1.14.0" < latest "v1.15.0-rc.4")
[start] 14:04:13 INFO: Upgraded to "v1.15.0-rc.4", exiting now.
[monitor] 14:04:13 INFO: Restarting monitor...
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.main()
	github.com/syncthing/syncthing/cmd/syncthing/main.go:218 +0x52f

goroutine 6 [syscall]:
syscall.Syscall6(0x16b, 0x6, 0x0, 0x0, 0xc000060740, 0x1, 0x0, 0x0, 0x0, 0x0)
	syscall/asm_unix_amd64.s:39 +0x5
syscall.kevent(0x6, 0x0, 0x0, 0xc000060740, 0x1, 0x0, 0x0, 0x0, 0x0)
	syscall/zsyscall_freebsd_amd64.go:202 +0x95
syscall.Kevent(0x6, 0x0, 0x0, 0x0, 0xc000060740, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	syscall/syscall_bsd.go:462 +0x71
github.com/syncthing/notify.(*kq).Wait(0xc000045ce0, 0x0, 0x0, 0x0, 0x0)
	github.com/syncthing/notify@v0.0.0-20210308121556-f45149b04939/watcher_kqueue.go:139 +0x8d
github.com/syncthing/notify.(*trg).monitor(0xc000045c80)
	github.com/syncthing/notify@v0.0.0-20210308121556-f45149b04939/watcher_trigger.go:404 +0x38
created by github.com/syncthing/notify.newWatcher
	github.com/syncthing/notify@v0.0.0-20210308121556-f45149b04939/watcher_trigger.go:112 +0x229

goroutine 7 [chan receive]:
github.com/syncthing/notify.(*nonrecursiveTree).dispatch(0xc0001089c0, 0xc000108900)
	github.com/syncthing/notify@v0.0.0-20210308121556-f45149b04939/tree_nonrecursive.go:36 +0xb6
created by github.com/syncthing/notify.newNonrecursiveTree
	github.com/syncthing/notify@v0.0.0-20210308121556-f45149b04939/tree_nonrecursive.go:29 +0xe5

goroutine 8 [chan receive]:
github.com/syncthing/notify.(*nonrecursiveTree).internal(0xc0001089c0, 0xc000108960)
	github.com/syncthing/notify@v0.0.0-20210308121556-f45149b04939/tree_nonrecursive.go:81 +0x58
created by github.com/syncthing/notify.newNonrecursiveTree
	github.com/syncthing/notify@v0.0.0-20210308121556-f45149b04939/tree_nonrecursive.go:30 +0x111

goroutine 9 [sleep]:
time.Sleep(0x1dcd6500)
	runtime/time.go:193 +0xd2
github.com/syncthing/syncthing/lib/dialer.init.1.func2()
	github.com/syncthing/syncthing/lib/dialer/internal.go:44 +0x2a
created by github.com/syncthing/syncthing/lib/dialer.init.1
	github.com/syncthing/syncthing/lib/dialer/internal.go:43 +0x15f
```

**Comment by tomangert** [comment]
Seeing the same on windows and RHEL. Tried -reset-database but no change.

**Comment by tomangert** [comment]
[start] 10:23:39 INFO: syncthing v1.15.0-rc.3 "Fermium Flea" (go1.16.1 linux-amd64) teamcity@build.syncthing.net 2021-03-11 10:21:35 UTC
[start] 10:23:39 INFO: Automatic upgrade is always enabled for candidate releases.
[start] 10:23:40 INFO: Upgrade available (current "v1.15.0-rc.3" < latest "v1.15.0-rc.4")
[start] 10:23:44 INFO: Upgraded to "v1.15.0-rc.4", exiting now.
[monitor] 10:23:44 INFO: Restarting monitor...
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.main()
        github.com/syncthing/syncthing/cmd/syncthing/main.go:218 +0x52f

goroutine 6 [chan receive]:
github.com/syncthing/notify.(*nonrecursiveTree).dispatch(0xc00009a9c0, 0xc00009a900)
        github.com/syncthing/notify@v0.0.0-20210308121556-f45149b04939/tree_nonrecursive.go:36 +0xb6
created by github.com/syncthing/notify.newNonrecursiveTree
        github.com/syncthing/notify@v0.0.0-20210308121556-f45149b04939/tree_nonrecursive.go:29 +0xe5

goroutine 7 [chan receive]:
github.com/syncthing/notify.(*nonrecursiveTree).internal(0xc00009a9c0, 0xc00009a960)
        github.com/syncthing/notify@v0.0.0-20210308121556-f45149b04939/tree_nonrecursive.go:81 +0x58
created by github.com/syncthing/notify.newNonrecursiveTree
        github.com/syncthing/notify@v0.0.0-20210308121556-f45149b04939/tree_nonrecursive.go:30 +0x111

goroutine 8 [sleep]:
time.Sleep(0x1dcd6500)
        runtime/time.go:193 +0xd2
github.com/syncthing/syncthing/lib/dialer.init.1.func2()
        github.com/syncthing/syncthing/lib/dialer/internal.go:44 +0x2a
created by github.com/syncthing/syncthing/lib/dialer.init.1
        github.com/syncthing/syncthing/lib/dialer/internal.go:43 +0x15f

**Comment by tomangert** [comment]
That workaround works for me
$ ./syncthing serve
   ... and it works

**Comment by imsodin** [comment]
Cause is clear, working on fix and rc.5
