### ISSUE TITLE
Syncthing publishes external IP with default port

### ISSUE THREAD

**Issue by bt90** [syncthing/syncthing#7488]
I have been investigating the origin of the following error that appears from time to time in my log:

```
Connected to myself (XXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX) at [::]:22000-79.XXX.XXX.XX:22000/quic-client/TLS1.3-TLS_AES_128_GCM_SHA256 - should not happen
```

The redacted IP is my external IPv4 address and the ports 22000 tcp+udp are manually forwarded to my NAS. The logs would indicate that some other device published this exact combination as its own address.

I could confirm that my phone is publishing this to the global discovery server:

```json
{
   "seen":"2021-03-17T18:26:51.297576905Z",
   "addresses":[
      "quic://192.168.178.20:22000",
      "quic://79.XXX.XXX.XXX:22000",
      "quic://79.XXX.XXX.XXX:61979",
      "quic://[2003:XXXXXXXXXXXXXXXXXXXXXXXXX]:22000",
      "tcp://192.168.178.20:22000",
      "tcp://79.XXX.XXX.XXX:22000",
      "tcp://79.XXX.XXX.XXX:61980",
      "tcp://[2003:XXXXXXXXXXXXXXXXXXXXXXXXX]:22000",
      "tcp://[2003:XXXXXXXXXXXXXXXXXXXXXXXXX]:22000"
   ]
}
```

The addresses `tcp://79.XXX.XXX.XXX:61980` and `quic://79.XXX.XXX.XXX:61980` are both correct and get logged by my phone as the result of the STUN lookup. But why does it also publish the external address combined with the default listening port?

The log output appears after the syncthing app stops. This causes my NAS to start dialing and in turn dial its own external address.

**Comment by calmh** [comment]
> But why does it also publish the external address combined with the default listening port?

So that things actually work if users set up the default, recommended, manual port forward. This is by design.

**Comment by AudriusButkevicius** [comment]
Stun is only meaningful for quic, it has zero effect for TCP.

People quite often setup external port mappings on the router, mapping 22000 to 22000, hence this is by design.

**Comment by bt90** [comment]
Could we reword the log output then? Because `should not happen` is a bit of an overstatement if we expect it to happen if multiple devices are behind the same NAT.

**Comment by calmh** [comment]
Yes. I think we should remove the warning entirely, as this is in fact something pretty much *guaranteed* to happen in a bunch of benign situatations.
