### ISSUE TITLE
javascript /rest/system/upgrade Error 500

### ISSUE THREAD

**Issue by JedMeister** [syncthing/syncthing#7504]
The error:
```
angular.js:9912 GET https://sync.jeremydavis.org/rest/system/upgrade 500 (Internal Server Error)
```
is displayed consistently within the Javascript console in Chrome developer tools.

(Note the server has since been stopped, but can be restarted if you want further info).

From what I can gather, this appears to be a benign/inconsequential AngularJS error, but I was hoping to get confirmation on that (or not as the case may be).

My internet searches didn't turn up many results, the 2 best ones (specifically related to Syncthing) appear to be in other bug reports (where there were other errors/actual problems). So I'm guessing that this is just noise in the js console?

My testing suggest that it's not causing any apparent problem.

----

**Syncthing versions tested:** v1.7.1 & v1.14.0 (installed via Syncthing apt repo - both displayed same behaviour)

**OS:** TurnKey Linux v16.0 (based on 64-bit Debian Buster/10)

**Config:**
Occurs when running directly, or when reverse proxied by Nginx (essentially as per [Syncthing docs](https://docs.syncthing.net/users/reverseproxy.html)) using the below conf snippet (full Nginx conf can bee seen [here](https://github.com/turnkeylinux-apps/syncthing/blob/master/overlay/etc/nginx/sites-available/syncthing)):
```
# reverse proxy for syncthing
server {
    listen 0.0.0.0:443 ssl;
    access_log /var/log/nginx/syncthing.log;
    error_log /var/log/nginx/syncthing_error.log;
    include /etc/nginx/include/ssl;

    location / {
         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;

         proxy_pass http://localhost:8383;

         proxy_read_timeout 600s;
         proxy_send_timeout 600s;

         proxy_redirect off;
    }
}
```

**Non default `config.xml` entries:**

`<insecureSkipHostcheck>true</insecureSkipHostcheck>` (within the `<gui .. > </gui>` section of the Syncthing `config.xml`) - as discussed recommended in https://github.com/syncthing/docs/issues/401#issuecomment-404088454

`<address>127.0.0.1:8383</address>` (i.e. bound to localhost on non-standard port) or (not behind proxy) `<address>0.0.0.0:8384</address>`

**Browser:** Google Chrome 89.0.4389.90 (Official Build) (64-bit) on Debian Buster/10 Linux 

I was able to consistently reproduce the issue both behind the Nginx reverse proxy and when accessed directly.

**Comment by AudriusButkevicius** [comment]
This is expected on builds that do bot self upgrade.

**Comment by JedMeister** [comment]
Thanks. I suspected something like that... :)
