### ISSUE TITLE
Default path points to a non-existing /tmp/syncthing/ and more newbie issues

### ISSUE THREAD

**Issue by mmokrejs** [syncthing/syncthing#7506]
I am a new user and I already have lost my synthing shared folder across restarts.

1. Users should be ideally instructed to first set their default folder prefix under Actions -> Settings -> "Default folder path". It will make them aware where the data shall be stored. Nt even the manual speaks of this, too bad. The `daemon` should immediately check it can write to the place and if not, write an error message to the web gui. I started to get `lstat /home/foo/blah` later during my "use" of syncthing.

2. If it is not possible to write there, syncthing should propose a solution. I did `chgrp syncthing /home/foo/blah; chmod g+rwx /home/foo/blah` but surprisingly it did not help. Weird, webserver is happy with `chmod a+x /home/foo` usually to traverse under `/home/foo/public_html/`. Initially syncthing was working for me under /home/foo/tmp/blah/ but who knows what happened to my setup that things stopped working.

```
2021-03-19 23:41:18 Unexpected folder "baz" (zvpeq-xtmay) sent from device "bar"; ensure that the folder exists and that this device is selected under "Share With" in the folder configuration.
2021-03-19 23:42:10 Adding folder "baz" (zvpeq-xtmay)
2021-03-19 23:42:10 No stored folder metadata for "zvpeq-xtmay"; recalculating
2021-03-19 23:42:10 Loading ignores: lstat /home/foo/syncthing/baz/.stignore: permission denied
2021-03-19 23:42:10 Failed to create folder root directory stat /home/foo/syncthing/baz: permission denied
2021-03-19 23:42:10 Ready to synchronize "baz" (zvpeq-xtmay) (sendreceive)
2021-03-19 23:42:10 Error on folder "baz" (zvpeq-xtmay): stat /home/foor/syncthing/baz: permission denied
```

I went through the `Getting Started` and `An Intro to the GUI` and I haven't seen a piece of text explaining what pers are needed here and there. I don't get the idea that a user should write stuff under `/var/lib/Sync/` to get propagated to remotes. I everybody expected to use ACLs on that directory tree? What is the recommended practice? I thought of my own `$HOME/blah` to be a default root folder with many sub-folder per "project" but somehow it does not work (see `lstat` issues above).

3. Loss of config data, aka keys. It is amazing that `/var/lib/syncthing/.config/syncthing/` were rewritten without my consent. yes, the remote folder did not get synced to my local directories so I paused and restarted folder syncing from within the web gui, like other. Then I restarted even the `deamon`. somehow, it happened there is `config.xml.v0` but evidently, my original `Device ID` is just gone, evidently with the keys. I can send you my formed device ID, maybe you can figure out from the logs what happened. The current XML files have a different ID now. This should have never happened that y XML files and db files were rewritten with a new ID, never.

4. The issues with non-synchronising folder and devices could be associated with the fact syncthing uses all interface the device has, actually all IP's it managed to figure out somehow based on outgoing packets. I have one physical eth0 device, I do have three vpn interfaces (tunX and vpnX)  but syncthing uses about 20 IP's per my device. Then, I am not surprised that the device is out-of-sync. All TLS connection to the same target will not succeed. I am not surpised I see "context .... exceeded" messages. 

5. It is not clear how to move the shared folder around a single computer. Obviously I shut down a daemon, moved a folder, changed default folder path, maybe after this shut and re-started the deamon and was hoping to be done. OK, I admit, I should have edited the XML config file, now I know. Now it is all gone. But how come?!

Please don't get my post too negatively, I writing it to emphasize how careless a user may be and that the software should be more fool-proof. I will be happy to re-test soon. Oh yeah, I am on v1.14.0 on all devices. Thank you. It is pleasing syncthing iis available on OpenWRT and on usual Linux desktop distros, Android and Win. ownCloud required too many PHP crap which did not fit on my OpenWRT partition so that was the reason `syncthing` received the chance. That's how one software could win over another.

Good luck!

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by mmokrejs** [comment]
I don't think so. If a user specifies a "default" directory which cannot be written the software should reveal that right away, The user may fix that by shutting down the deamon and fixing the directory perms, although myself haven't realized what's the culprit. and no way the software should keep under "Advanced settings" as a default path a path to a directory '/var/lib/syncthing/' which does not exist at all. But do as you wish. It was really meant for you to distill whatver you find useful from this message.

**Comment by AudriusButkevicius** [comment]
Some of these points/user experiences have open-ended discussions as to what the right thing to do is, or explanation why things are the way they are. 


Issue tracker is not the right place for that, the forum is.
