### ISSUE TITLE
Increase default strelaysrv network buffer size

### ISSUE THREAD

**Issue by arkkors** [syncthing/syncthing#7514]
### Does your log mention database corruption?

no

### Include required information

The default network buffer size is not a multiple of 64K per default, which is the maximum TCP packet size.
This causes unneccesary fragmentation, slowing down large file uploads when a relay is involved.
Changing this value to 64K (65536) significantly improves upload speed on fast connections.

- strelaysrv v0.14.49, linux amd64

**Comment by AudriusButkevicius** [comment]
Please define "significantly"

**Comment by arkkors** [comment]
Pushing 1GB of data over loopback yields values like this for me:

network buffer size = 2048:   9.12349009513855 seconds
network buffer size = 65536: 1.124870777130127 seconds

So an improvement of around 7-8x.

These are times without the client-server negotiation stuff (JoinRelayRequest+ConnectRequest chain), which are negligible.

**Comment by AudriusButkevicius** [comment]
I guess this does not take network latency into account which probably has an effect on this, but never the less, the syscall overhead probably is significant enough here regardless.

@calmh wdyt?

**Comment by calmh** [comment]
Moar buffer moar good I guess.

**Comment by calmh** [comment]
I changed my mind on this, as noted on the PR Audrius filed:

> Sorry, looking more closely at this I don't think this is appropriate. It's already a flag so the user can optimize as they like, lots of relays have a hundred sessions which by my mental count would cost 13+ gigs of RAM. So no, I think the current default is fine despite the better performance with a bigger buffer.
>
> I guess an alternative would be some sort of smarter shared buffer handling that only used buffer space when required, but that's not what we have.

This is not a default we should change in this manner.

**Comment by calmh** [comment]
Actually closed by f7929229c8c903d529df59aa3d83dffa25e17978, just messed up by some dumbassery of mine.
