### ISSUE TITLE
"Out of Sync Items" with Mod. Device that is not currently a remote of any peer, for files matching an ignore pattern.

### ISSUE THREAD

**Issue by xorgy** [syncthing/syncthing#7516]
I have several machines running Syncthing 1.14.0, one is a colleague's Mac, the other two are ArchLinux machines.

All of these machines have correct `.DS_Store` patterns in their `.stignore` for the folder in question.
There are three `.DS_Store` files listed in the "Out of Sync Items" list, causing the peers to be perpetually marked as Syncing.

We have tried un-ignoring the files, then writing files to those paths, waiting for them to sync, and then deleting them and re-adding the patterns to `.stignore` when all the peers say they are Up to Date; but when we add the `.stignore` patterns back, the phantom "Out of Sync Items" return.

This has been occurring for well over a year, the listings in the Out of Sync Items list are from October of 2019, so this has been happening for a few versions by now.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by xorgy** [comment]
I mean, I don't see how this can not be a bug. None of the peers want this file, it has been replaced, and there exist no peers who can transfer it.

**Comment by imsodin** [comment]
It's not about whether it's working as intended or not, it's about whether it is an actionable bug. There's a lot to be cleared up and investigated about your situation, before it even gets clear what your situation is exactly. Doing so might reveal an already known actionable bug, or a new one. At which point a github issue is appropriate. Until then we handle the investigation/support/debugging on the forum.
