### ISSUE TITLE
Ask for confirmation before reverting/overriding a folder

### ISSUE THREAD

**Issue by sebyte** [syncthing/syncthing#7520]
I lost work recently clicking the 'Revert local changes?' button on a receive only folder, expecting a dialogue box would list the affected files and seek my confirmation before reverting or deleting.  To my surprise, the file I'd mistakenly saved in the wrong folder was instantly deleted.  Everone's expectations are different of course but the potential for accidental data loss here is huge.

No versioning strategy was employed on this particular folder but even if it had been, I don't believe it would have helped since versioning strategies only apply to changes coming in from other devices.

**Comment by calmh** [comment]
Versioning does apply, and the files that will be reverted are listed in the "locally changed items" line before pressing revert. I'll give you that there could be a confirmation though...

**Comment by imsodin** [comment]
This discussion happened on the forum not too long ago, with a general agreement that a confirmation would be good. Just a single word (revert/override) and a the red color apparently isn't able to convey the consequences appropriately. I actually intended to take a stab at a short message based on your proposal, but never got around to it:

> I agree on the confirmation (though it needs to be much shorter and to the point, I think, maybe something like “Warning: the folder contents on OTHER devices will be overwritten to become identical with THIS device. Files not present here will be deleted on other devices.”?). 

https://forum.syncthing.net/t/do-not-click-override-changes/16081/6

**Comment by sebyte** [comment]
I see now that I overlooked the 'Locally changed items' line and expected to see the dialogue it would have shown me when I pressed 'Revert local changes?'  IMO, any confirmation dialogue should somehow draw the users attention to the list of locally changed items as well as soliciting an additional button press.

Also, I am surprised to learn that a versioning strategy would have protected me.  [The manual](https://docs.syncthing.net/users/versioning.html) strongly suggests otherwise.

**Comment by imsodin** [comment]
> Also, I am surprised to learn that a versioning strategy would have protected me. [The manual](https://docs.syncthing.net/users/versioning.html) strongly suggests otherwise.

What are you referring to? Maybe

> Versioning applies to changes received from other devices.

Reverting files is receiving changes from other devices, but I can see how that might not be obvious. Feel free to propose changes to the docs to make it more clear.

**Comment by sebyte** [comment]
> Versioning applies to changes received *from other devices*.

Yes, that's the line that suggests to me file versioning does not apply here.  It also happens to be the first line of an 'important note' box and the words 'from other devices' are italicised to provide additional emphasis.

> Reverting files is receiving changes from other devices, but I can see how that might not be obvious.

Yes, not obvious at all.  Without an in-depth understanding of the versioning machinery I can't be certain this is correct, but how about the following?

>Versioning applies to changes received *from other devices*, with one notable exception; locally introduced changes to receive-only folders are versioned when the changes are manually reverted using the UI.

**Comment by acolomb** [comment]
> > I agree on the confirmation (though it needs to be much shorter and to the point, I think, maybe something like “Warning: the folder contents on OTHER devices will be overwritten to become identical with THIS device. Files not present here will be deleted on other devices.”?).

How about moving the "Revert Local Changes" button to the "Locally Changed Items" dialog?  Just a quick idea, I'm not even sure whether such a dialog pops up or what it looks like.  But that would couple the "what will happen" preview directly to the opportunity of pressing the red button.

**Comment by sebyte** [comment]
> How about moving the "Revert Local Changes" button to the "Locally Changed Items" dialog?

Good idea.  That would have prevented me from losing my work.

> that would couple the "what will happen" preview directly to the opportunity of pressing the red button.

Yes it would, and coupling the list of changes with the option to revert those changes makes accidental or inadvertant data loss far less likely.
