### ISSUE TITLE
Syncthing completely resets on reboot

### ISSUE THREAD

**Issue by ElnuDev** [syncthing/syncthing#7521]
I have two Pop!_OS 20.10 (Ubuntu derivative) computers running Syncthing v1.14.0, and they're running into the exact same problem: Syncthing completely resets on reboot. Not just all my folders, (the files are still there) but it asks me if I want to send usage reports again, which makes me feel like everything was reset.

I have them added as startup applications running with the command `/usr/bin/syncthing -no-browser -home="/home/elnu"`, which is working just fine.

Any idea what is going on? It seems like all of Syncthing's data is only being stored temporarily.

Any help would be greatly appreciated, thanks in advance!

**Comment by calmh** [comment]
No concrete idea, though one usual suspect timing of startup in relation to encrypted home directories. However it's unlikely to be a Syncthing bug per se, and we do support and general discussion [on the forum](https://forum.syncthing.net/), so I'll point there for followups. :)

**Comment by ElnuDev** [comment]
I posted on the forum [here](https://forum.syncthing.net/t/syncthing-completely-resets-on-reboot/16563), thanks for the help! I really appreciate it.
