### ISSUE TITLE
syncthing.service failed result 'exit-code'

### ISSUE THREAD

**Issue by pal-wal** [syncthing/syncthing#7524]
### Version of Syncthing and the operating system I am using:
Syncthing version:1.14.0, Operating system:Arch linux

 ### what happened:
Syncthing fails when trying to set it up as a user service using systemd.

### Error log:
systemctl --user status syncthing.service
● syncthing.service - Syncthing - Open Source Continuous File Synchronization
     Loaded: loaded (/home/walid/.config/systemd/user/syncthing.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2021-03-26 16:21:21 IST; 2s ago
       Docs: man:syncthing(1)
    Process: 9650 ExecStart=/usr/bin/syncthing serve --no-browser --no-restart --logflags=0 (code=exited, status=2)
   Main PID: 9650 (code=exited, status=2)

Mar 26 16:21:20 palmachine syncthing[9650]:  upnp            - UPnP discovery and port mapping
Mar 26 16:21:20 palmachine syncthing[9650]:  ur              - Usage reporting
Mar 26 16:21:20 palmachine syncthing[9650]:  versioner       - File versioning
Mar 26 16:21:20 palmachine syncthing[9650]:  walkfs          - Filesystem access while walking
Mar 26 16:21:20 palmachine syncthing[9650]:  watchaggregator - Filesystem event watcher
Mar 26 16:21:21 palmachine systemd[806]: syncthing.service: Scheduled restart job, restart counter is at 62.
Mar 26 16:21:21 palmachine systemd[806]: Stopped Syncthing - Open Source Continuous File Synchronization.
Mar 26 16:21:21 palmachine systemd[806]: syncthing.service: Start request repeated too quickly.
Mar 26 16:21:21 palmachine systemd[806]: syncthing.service: Failed with result 'exit-code'.
Mar 26 16:21:21 palmachine systemd[806]: Failed to start Syncthing - Open Source Continuous File Synchronization.

 ### What I expected to happen instead:
I expected it to run as a user service

 ### Steps to reproduce the problem:
cp Syncthing/etc/linux-systemd/user/syncthing.service ~./config/systemd/user/
systemctl --user enable syncthing.service
systemctl --user start syncthing.service

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
