### ISSUE TITLE
Out of Sync Items is empty if files are locked by the OS

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7526]
1. Share a folder between two Windows devices - A and B.
2. On A, run a program that locks some files in the shared folder.
3. The locked files cannot be synced, and their number is listed under the remote device (B).

   ![1](https://user-images.githubusercontent.com/5626656/112724524-26c05e00-8f57-11eb-9cc7-8b5029c4a279.png)

4. However, the actual list is shown as empty.

   ![2](https://user-images.githubusercontent.com/5626656/112724538-363fa700-8f57-11eb-8212-e5233e0fb72a.png)

5. Only under the specific folder we can view the actual file names.

   ![4](https://user-images.githubusercontent.com/5626656/112724633-a3ebd300-8f57-11eb-81af-ea64887d538f.png)
   ![3](https://user-images.githubusercontent.com/5626656/112724559-49527700-8f57-11eb-9343-0eb8ccf7289a.png)

Tested with Syncthing v1.14.0.

**Comment by imsodin** [comment]
The files being locked is a red herring: Syncthing doesn't know anything about the error reason for remote devices (where the items are missing). That information is entirely based on database entries.

Things to check:
1. Browser dev tools/console for javascript errors.
2. `/rest/db/file` (or even better `/rest/debug/file`) endpoint for one of those files: https://docs.syncthing.net/rest/db-file-get.html

**Comment by tomasz1986** [comment]
I'm closing this one, as the errors have disappeared, and now I cannot reproduce the problem. I will write back if the issue ever reappears.
