### ISSUE TITLE
strelaysrv allows connecting to the node itself

### ISSUE THREAD

**Issue by arkkors** [syncthing/syncthing#7527]
`ConnectRequest`s to a device id which matches the originating connection are not rejected

**Comment by AudriusButkevicius** [comment]
I guess this is unexpected, but not completely invalid?

**Comment by calmh** [comment]
I don't think this is very unexpected nor really matters. The relay server gets an incoming connection from whomever asking for a device ID that's known to be available on that relay and just connects the two. It doesn't verify or care who makes the incoming connection, and I don't see why it should.

**Comment by arkkors** [comment]
It seemed like a mistake, as the shortest path from a node to itself never goes through a relay.

**Comment by calmh** [comment]
There is indeed never a reason for a path from a node to itself.
