### ISSUE TITLE
Files don't sync blocks until entire file is finished?

### ISSUE THREAD

**Issue by G2G2G2G** [syncthing/syncthing#7528]
Maybe I understand how syncthing works incorrectly but:

When you have several large files and add them all to your syncing folder at once, the order is randomized, the pull order for blocks is in bigger chunks and the,  the writers then write to the random files... When doing it this way, the files don't seem to upload to anything at all until an entire full file is finished.
Adding files to my "SENDONLY" big server, majority of the bandwidth goes to the secondary "big server" that has a gigabit connection up & down, this server sits idle on upload until an entire file is completed then it sends the whole file to the smaller servers in a few seconds. 

![1](https://user-images.githubusercontent.com/50514477/112746128-96901200-8f72-11eb-9f79-1dd3c4c45bf0.jpg)
"Secondary big server" is the one on the right, with gigabit up/down, no throttling, and send/receive 

When 10 files that are let's say 10GB are added to the "SENDONLY" because of the randomness, you'd expect a lot of the bandwidth to go toward the secondary big server, and then that to distribute the files due to no throttle of the links. However this doesn't work that way. Instead the secondary big server sits in download only mode, the entire time, until all the files are downloaded because of the randomness it doesn't finish any 1 file, it downloads them all equally and never uploads until it's done. I usually have about 30% of overall data uploaded from it, and 70% from the "SENDONLY" server, which shouldn't happen that way. The SENDONLY server should upload almost all of the data to the secondary server since there is no throttle, and then the sendonly should be distributing it to the small servers.

Results look something like this, 100% of the time when transferring any amount of files (in a sense that the servers aren't equal at all and the "SENDONLY" hub is doing 99% of the block syncing until the secondary server finishes completely):
![1](https://user-images.githubusercontent.com/50514477/112746260-4a919d00-8f73-11eb-8d1f-741923b944a1.jpg)
I've used syncthing for a bit over 3 years and it seems to have always done this. It seems to me that all of these should be equal? If my small mesh was correctly distributing chunks that is... Once the first one finishes (the secondary big server), it then uploads so much data that the two smaller servers max out their CPU (they are old raspberry pi) previously they are only receiving the 200kbps and their cpu is basically idle. 

I assume this is a bug because over the past few years I have reinstalled syncthing and use it on many other machines not just these 4, with different folders and different configs (mostly close to default). I've messed with every setting the only one that seems to really influence it are the 2 below and of course the "temp indexes" which I have default (on (false)) 

To fix that I changed these options:
        <blockPullOrder>inOrder</blockPullOrder>
        <order>alphabetic</order>

I'd rather not have to do this, I'd like it to distribute chunks of the files constantly as it gets them, but since it doesn't these settings make the secondary big server download 2 files entirely first. Then it distributes those.. and so on (since the writers are by default "2"). 

Thanks for any input

edit: 
In case it gets asked the big servers aren't capped by CPU or disk speed in any form (NVME and 24 core / 36 core respectively) They saturate their speed with ease if I do a netcat or SFTP link (sftp usually caps a single CPU core though, ssh seems to be single threaded in a transfer at least)

**Comment by imsodin** [comment]
There might indeed be a bug in all of this, however there's so many aspect to your detailed report (thanks) that either need clarification and further investigation, and we handle that on https://forum.syncthing.net. Please re-post this there - thanks. Once a well-contained or reproducible bug has been identified, an actionable issue can be opened here.
