### ISSUE TITLE
Sync git repository settings (remotes) without touching the content

### ISSUE THREAD

**Issue by EvilMav** [syncthing/syncthing#7531]
Consider the situation: you use syncthing to sync a project folder. In addition to all the documentation, there are also a 
couple of git repos associated with it. Currently, you will most likely put those in an ignored directory to avoid partial syncs messing up git. But this means you will have to manually clone those repos on each machine.

My proposal: make syncthing sync the repositories in therms of their remotes but not touch the files and state. This way a user can just clone on one machine and git pull on a synced directory and keep on working. I imaging this would make the common use patterns fast and still reliable for most git users.

**Comment by imsodin** [comment]
This is out-of-scope for Syncthing: It syncs files - it doesn't handle state of specific applications specially.
