### ISSUE TITLE
Chrome OS

### ISSUE THREAD

**Issue by chrboesch** [syncthing/syncthing#7540]
Syncthing v1.14.0  installed on Chrome OS and started, stops at key generation. No entry in the log file.

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
