### ISSUE TITLE
Ignore pattern with \[ and \] does not work

### ISSUE THREAD

**Issue by KainHaart** [syncthing/syncthing#7547]
- **version of Syncthing and operating system**: v1.14.0, Windows (64-bit Intel/AMD)
 - **browser and version**: Vivaldi | 3.7.2218.52 (Stable channel) (64-bit) // i guess it's irrelevant, but still

 - **steps to reproduce the problem:** 
   - add `\[myfolder\]` pattern to ignore patterns
   - add `[myfolder]` subfolder to shared forlder
   - press «Rescan» in web gui
 - **what happened**: syncthing is indexing (and syncing) files in to-be-ignored folder with [ ] in name
 - **what you expected to happen instead**: files ignored

**Comment by AudriusButkevicius** [comment]
See: https://docs.syncthing.net/users/ignoring.html

> Escaped characters are not supported on Windows.

**Comment by KainHaart** [comment]
@AudriusButkevicius thanks, missed that 😅
Are there plans to make them work on Windows?

**Comment by calmh** [comment]
No, but you can use various other wildcard characters to match your brackets.
