### ISSUE TITLE
Automatic "restart"

### ISSUE THREAD

**Issue by leatherneck111** [syncthing/syncthing#7554]
On Windows 10 Enterprise edition, even clicking "rescan" did NOT sync files from my Samsung Galaxy S20 Plus 5G.  The Syncthing icon spins showing that it's syncing, yet nothing actually gets synced.  I even forced stopped the app on my phablet and restarted the APK just to rule out a sync issue with my phablet.  I then realized as this isn't the first time that for some unknown reason I need to "restart" syncthing by right clicking in the system tray.  After which, Syncthing legitimately conducted "rescan" & this time it showed 5 files synced from my phablet.  There should be an option which would allow a user to click on "Auto Restart" Syncthing every 8 hours or 4 hours or 12 hours etc etc..  This way if there are any issues or bugs such as this which prevent a legitimate "rescan" then it'll completely refresh and overcome the bug.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
