### ISSUE TITLE
Cannot connect to a Synchthing peer unless I have an active SSH connection to it

### ISSUE THREAD

**Issue by JPenuchot** [syncthing/syncthing#7555]
## Config

- Syncthing v1.15.1 on ArchLinux (laptop, Azure VPS and 2nd computer) and ArchLinuxARM (Raspberry Pi)
- Firefox 87.0

## Issue

Syncthing instance on my laptop won't connect to Syncthing instances on my Raspberry Pi (same LAN) nor my Azure VPS (not the same LAN) unless I have an active SSH connection (with *no* forwarding) to my Raspberry Pi. However, I do have a 2nd computer running on the same LAN with Syncthing on Arch and the same configuration which can synchronize properly without opening an SSH connection to it.

NB: I have the same behavior with the HTTPS GUI. My Raspi's GUI isn't accessible unless I have an active SSH connection to it, again, with no forwarding.

## Expected behavior

I would expect my laptop to connect properly to my other Syncthing peers without needing an active SSH connection to them.

## How to reproduce

I don't know how to reproduce that bug. Both my Raspi, my VPS, and my 2nd computer are on the same LAN, they are running the same Linux distro, and share the exact same Syncthing configuration.

**Comment by Script-Mak3r** [comment]
To borrow a boilerplate response the devs use:

This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by JPenuchot** [comment]
I suspect it is an actual bug, unless Syncthing is intended to connect to my Raspi using IPv6 protocol using an IPv4 address:
`tcp6://192.168.1.165:22001`

**Comment by AudriusButkevicius** [comment]
Syncthing is probably setup as a user service, which means it gets shut down as you log out.

You should set it up as a system service.

If you have more questions, forum is the place.
