### ISSUE TITLE
DNS resolving problem

### ISSUE THREAD

**Issue by svsdval** [syncthing/syncthing#7556]
syncing set by server dns name, if the name resolving did not happen at first nameserver the syncing says: no connection to the devices... but if i swap the nameservers places (if i move 8.8.8.8 to the first nameserver place), syncing work fine. 

example resolv.conf:
search example.com 
nameserver 192.168.1.1
nameserver 8.8.8.8

**Comment by calmh** [comment]
This sounds like a problem with your sons server or setup rather than a Syncthing issue? If your first dns server returns "does not exist" then that's a valid answer.

**Comment by bt90** [comment]
The DNS entries can take quite some time until they are queryable on all DNS servers. More so if negative caching is involved. If the upstream server used by 192.168.1.1 is operated by your ISP i'd expect such things to happen.

**Comment by svsdval** [comment]
> This sounds like a problem with your sons server or setup rather than a Syncthing issue? If your first dns server returns "does not exist" then that's a valid answer.

the first DNS server (192.168.1.1) is temporarily turned off

**Comment by svsdval** [comment]
> The DNS entries can take quite some time until they are queryable on all DNS servers. More so if negative caching is involved. If the upstream server used by 192.168.1.1 is operated by your ISP i'd expect such things to happen.

if i try to connect the syncthing server via netcat, successful connection takes about 5 seconds when down nameserver (192.168.1.1) is first in resolv.conf, when i swap 8.8.8.8 to the first then successful connection takes less   than seccond... 
but both is successful. so i don't understand, why syncthing won't connect ?

**Comment by calmh** [comment]
Run it with `STTRACE=connections,dialer` and see what it says about trying to connect?

**Comment by svsdval** [comment]
hm, i can't catch this problem, tried several times... perhaps this was just a my provider problem...
