### ISSUE TITLE
Not replicating to second trusted device from untrusted

### ISSUE THREAD

**Issue by WillMorhler** [syncthing/syncthing#7558]
I have a problem with the new untrusted device feature.  I'm not asking for support - I'm happy to wait for updated versions, but offering this info if it helps debug.

Here is my set up:

Device A: Windows desktop
Device B: Windows laptop
Device C: RasPi

I have folder 1 shared among all three Devices.  That has been working for a long time.  (Thanks!)

I added folder 2 and shared it between Device A and Device C, configuring the folder on Device C as untrusted and providing password on Device A.  That works fine.  The encrypted information shows up on Device C, and when I run the command line decrypt facility I get back the original information.

I then added folder 2 on Device B, shared only with Device C.  On Device B I used the same password that was used on Device A.

At this point I had some issues with the encrypted versions of folder 2  appearing back on Device A, but I see other support questions related to Syncthing being running while adding encrypted folders, so I deleted and readded the folder with Syncthing shut down. This is not my issue, I mention it only to be complete.

After that detour, I have the connection for folder 2 between Devices A and C working.  (Clear text on A, encrypted on C, verified by decrypting to a non-syncthing folder.)  But NO data has appeared in folder 2 on Device B.  All three devices report "Up to Date" for folder 1 and folder 2 and for all three devices, but no data has been replicated to Device B for folder 2.

Again, I'm not asking for support but offering this in case it is useful.  Happy to provide screen shots and logs if desired.

**Comment by AudriusButkevicius** [comment]
I still think this should be on the forum.

Issues are things that have steps to reproduce and have a clear thing to fix. 

At this point this is just an experience report, it doesn't even include the versions involved, so I suspect this is many discussions/questions away from being a well formulated issue.


However, I am keeping it open in-case it's completely obvious to one of the other maintainers what's going on.
If not, it should still be closed and moved to the forum.

**Comment by WillMorhler** [comment]
Understood.  Just trying to be helpful.  FWIW, all three devices are on v 1.15.1

**Comment by WillMorhler** [comment]
I've recreated this in order to capture additional detail and have a different (but still problematic) result. Please close this and I'll post on the forum with updated information.  Apologies.
