### ISSUE TITLE
comm syncthing: No space for directory leaf checksum.

### ISSUE THREAD

**Issue by andrewufrank** [syncthing/syncthing#7562]
### Does your log mention database corruption?

LOG looks ok it says at end (after I stoped syncthing) 
````
14:32:12.486548 table@remove removed @9403
14:32:12.507755 table@remove removed @9404
17:04:07.137682 db@close closing
17:04:07.147223 db@close done T·9.53189ms
````
no indication of panic!

### Include required information

Please be sure to include at least:

````
frank@laufen:~/.config/syncthing/index-v0.14.0.db$ syncthing --version
syncthing v1.15.1 "Fermium Flea" (go1.16.3 linux-arm64) deb@build.syncthing.net 2021-04-06 08:42:29 UTC [noupgrade]

debian arm64 (on a raspi4)
````
I was "copying" set of 20 directories with total of 600GB data. The process was probably running for 10+ hours, perhaps accumulating something.

I got in syslog the entry: 
````
fcomm syncthing: No space for directory leaf checksum. Please run e2fsck -D.

and in the kernel log
kernel:[114279.437405] EXT4-fs (sda3): failed to convert unwritten extents to written extents -- potential data loss!  (inode 28574826, error -30)
````

 I cannot find any information for this error message.

when I apply fsck  to the disk I get 
`superblock has an invalid journal (node 8)` with the suggestion to clear. 

a bit later there is a reading error (input/output errro). the suggestion is ignore error and force rewrite. 

Now the disk is not initialized! (and no data can be found). The data lost are not a problem (it was to produce a copy), but I would like to understand the problem and see how to avoid it in future.

**Comment by AudriusButkevicius** [comment]
All of these errors are operating system errors, not syncthing errors, so I don't think we can help you here, hence closing.

The log you provided is not the syncthing log, it's the log of the database library we use, which is of no use to us.

If you want to discuss this matter further, I think it's best if you do that on the forum.
