### ISSUE TITLE
Define cross-folder priority

### ISSUE THREAD

**Issue by BenWiederhake** [syncthing/syncthing#7574]
Problem (simplified hypothetical):
- I have two folders, "Memes" and "Calendar". "Memes" is huge, contains many large files, "Calendar" contains very few, very small files.
- I have two devices: Laptop and Tower. Let's say they've been disconnected for a while, and on the Laptop I changed stuff in both folders.
- Now I connect them. The bandwidth is limited, and Syncthing makes a choice which files to pull/push first.
- Within a single directory, this decision is user-defined (Advanced > File Pull Order). Great!
- However, I want to be able to know that Syncthing always and predictably synchronizes my Calendar folder first.

How does Syncthing decide that? Can the user intervene?

I don't know about other use-cases, so I don't know how this feature should look like, but a simple "Folder Pull Order"-sorter would help in my case.

Workaround: Just wait for long enough :/

**Comment by AudriusButkevicius** [comment]
You can pause the folder you don't want to sync.

**Comment by BenWiederhake** [comment]
Duh! Yes, thanks, that is a workaround I should have seen earlier.

This feature request is about doing something like this automatically. Pausing unimportant folders is already quite good, so this feature request becomes unimportant (but not yet solved).

**Comment by AudriusButkevicius** [comment]
I  am not convinced this there is an easy way to implement this sensibly.

These things are not really serial, work for one folder might come and go etc, so stopping progress abruptly on the others seems a bit mad and wasteful, and not stopping it doesn't mean it will do the right, thing, as the file might be 100GB and take ages to complete.

**Comment by calmh** [comment]
Folders are inherently concurrent so I don't really see how to do this either. The one thing would be when `max concurrent folders` is set to something low one could imagine a queue for the waiting folders so that they come out of waiting in some kind of order, but that also gets tricky for several reasons. I think we will not attempt to do this.
