### ISSUE TITLE
syncthing out of sync file

### ISSUE THREAD

**Issue by rasen0** [syncthing/syncthing#7576]
syncthing out of sync file 
![image](https://user-images.githubusercontent.com/30561967/114643345-10acee80-9d08-11eb-88a7-fd9453fc29e4.png)
![image](https://user-images.githubusercontent.com/30561967/114643999-48686600-9d09-11eb-8d2f-2d39a144b036.png)

Please be sure to include at least:

 - Syncthing version 1.13.0 and 1.14.0
 - operating system: debian 9 and ubuntu18.04
 - Creating shared directory for the first time. The files in the software directory cannot be synchronized. Always in sync. Need to manually "pause" the remote device to synchronize normally after relinking

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
