### ISSUE TITLE
Unwanted connections from syncthing

### ISSUE THREAD

**Issue by Aikatsui** [syncthing/syncthing#7577]
**Steps to reproduce?**
Run `syncthing` through terminal

Syncthing v1.13.1 | Ubuntu 20.04.02

What for connect to those domains? i feel disappointed.
`docs.syncthing.net`
`syncthing.net`
`twitter.com`
`angularjs.org`
`fontawesome.io`
`forum.syncthing.net`
`forkaweso.me`
`getbootstrap.com`
`golang.org`
`gopkg.in`
`jquery.com`
`momentjs.com`
`prometheus.io`
`www.daterangepicker.com`
`github.com`

**Comment by AudriusButkevicius** [comment]
I'm equally disappointed in the quality of the issue raised.

**Comment by Aikatsui** [comment]
> I'm equally disappointed in the quality of the issue raised.

Sorry for that quick expression about problem, I guessed that is easy understandable for syncthing maintainers. As mentioned above once started syncthing from terminal then able to see above domains connectivity in network monitoring or DNS server softwares. I also edited issue however should i open new issue?

**Comment by calmh** [comment]
We don't connect to those places. There are links to them in the about page. Probably your web browser prefetches links.

**Comment by Aikatsui** [comment]
> We don't connect to those places. There are links to them in the about page. Probably your web browser prefetches links.

So i think this need to be fixed and isn't acceptable behavior //including footer links, not only about page

Browsers: any browser (chromium, brave)
Reproduce steps / OS / version: above mentioned

**Comment by calmh** [comment]
You should take that up with your browser vendor then.

**Comment by Aikatsui** [comment]
> You should take that up with your browser vendor then.

but this doesn't happen with other web-apps (and go apps) then you can be find way to fix it

**Comment by AudriusButkevicius** [comment]
I don't think you can, atleast not at the HTML level, unless you choose not to link to other sites at all, which I don't think we want, as we want to give software we use proper attribution.

In brave, seems even if you disable it, it still does that: 
https://community.brave.com/t/disabling-use-a-prediction-service-to-load-pages-more-quickly-doesnt-prevent-pre-connect-or-prefetch/81202

So I think you should go and talk to Brave/Chrome people, as we don't do anything else than "This is the software we use: <link to the website of the software>", and the browser itself decides to pre-resolve the DNS for the links, just in case you decide to click on them.
