### ISSUE TITLE
WebUI: Editing a folder after editing folder defaults broken.

### ISSUE THREAD

**Issue by jtagcat** [syncthing/syncthing#7583]
### Reproduction
1. Actions → Settings → (General → Default Configuration →) Edit Folder Defaults
2. Save
3. Save
4. Click on a folder and click edit.
5. [bug] Instead of editing the folder, the 'Edit Folder Defaults' dialogue is brought up with details populated from the folder being edited.

### Workaround
1. Refresh the page between 3. and 4.

### System info
 - Firefox 87.0
 - Syncthing 1.14.0
 - Fedora 33

**Comment by imsodin** [comment]
Duplicate of https://github.com/syncthing/syncthing/issues/7429, fixed in v1.15.1.
