### ISSUE TITLE
field in web ui doesn't account for long machine names

### ISSUE THREAD

**Issue by xristocodos** [syncthing/syncthing#7592]
Hi everyone, I've literally never reported a bug before on GH, so here goes...it's not urgent, but basically one of my machines is named after a quote from Elf ("You smell like beef and cheese, you don't smell like Santa!") and it spills over past the UI's name accommodations. Thought it might be helpful to write it up:

    What happened
      Web ui doesn't account for obnoxious(-ly long) machine names. In web UI, name runs over past field.
----------
    What did you expect to happen instead of what did happen, if it's not crazy obvious
      thought the name would be truncated with an ellipses (...) OR the font size changed to fit it all in there
----------
    What operating system, operating system version and version of Syncthing you are running
      Syncthing v1.15.1 on Ubuntu 20.10 x64
----------
    The same for other connected devices, where relevant
      n/a
----------
    Screenshot if the issue concerns something visible in the GUI
      apparently can't drag and drop from Ubuntu desktop into Firefox. ugh I'll do it from another machine and move the picture (using Syncthing!)
    (UPDATE: here!)
![20210422_0805h-screenshot](https://user-images.githubusercontent.com/10204266/115713103-a0275280-a343-11eb-82f6-5911b5122384.png)
----------
    Console log entries, where possible and relevant
      n/a

**Comment by AudriusButkevicius** [comment]
You can change the name of the device to work around this, but yes, there are a lot of ui elements that will look weird with long strings, I don't think it's worth spending chasing these

**Comment by calmh** [comment]
Probably every UI field should have something like `overflow: ellipsis` or something applied to it by default.

**Comment by wweich** [comment]
fixing this with overflow would mean setting the (max-)width of the label-span to a fixed size which accommodates the 2 floated spans (icon and status). That width had to be set according to the maximum possible status width for all languages, resulting in unneeded cut off and much white space for most languages.

I don't think we should fix this, as users clearly see that they can fix it themselves by shortening the device / folder label.

**Comment by calmh** [comment]
It saddens me that CSS apparently doesn't provide the tools to do this properly but if that's the case then I agree, we should not fix this.

**Comment by xristocodos** [comment]
Apologies, changing machine name to YSLBACYDSLC as aforementioned

**Comment by imsodin** [comment]
> Apologies, changing machine name to YSLBACYDSLC as aforementioned

No need for apologies - that was a nice, complete and clear bug report. It just happened to be not actionable.

In general visual web UI issues are a bit tricky and admittedly somewhat secondary in the project (there's no core contributor invested in it). If you want to bring up little issues or places for improvements, https://forum.syncthing.net might be a better place.

Thanks for taking the time to write this bug up and I hope you enjoy Syncthing ;)

**Comment by wweich** [comment]
turns out, my tests were flawed, I was thinking to complicated and we already have that for folders and the own device.
