### ISSUE TITLE
Consider removing support for TLS <1.3 on sync connections

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#7594]
Historically we've been fairly aggressive about adopting and then mandating secure crypto on the connection. TLS 1.2 is still alive and well, but we have a lot of cipher suite magic to ensure we get a secure connection. We could remove all that, simplifying our TLS config, and say that sync connections (*not* GUI/API connections) are now TLS 1.3 only.

The oldest Syncthing release that understands TLS 1.3 is 1.3.0 from October 1, 2019. By current data.s.n measurements we have ~94.6% of the population on 1.3.0 or newer. I would expect that those who do run old versions probably do that for a reason and probably do it somewhat consistently as well (that is, old talking to old rather than old talking to newest). Connections to older devices will be break with `Listen (BEP/tcp): TLS handshake: tls: client offered only unsupported versions: [303]`. ("303" is TLS 1.2, the other side will say the same but about "304" (TLS 1.3) instead.)

I'm not aware of any non-Syncthing BEP implementations we would need to be compatible with.

Nonetheless it would be the first intentional compatibility break for a long time, and in theory would require a Syncthing 2.0 release. (I *don't* think we should do a 2.0, because that would imply incompatibility with 1.3.0+ as well.) We could also retain the TLS 1.2 uglyness hidden behind a feature flag or environment var as a bailout for a while.

ref #7593

**Comment by GermanCoding** [comment]
Also potentially related: https://github.com/golang/go/issues/45430

**Comment by greatroar** [comment]
> I would expect that those who do run old versions probably do that for a reason

The reason might be just convenience: the Ubuntu Syncthing package is at 1.1.4 for the latest LTS release, 20.04.

**Comment by calmh** [comment]
Certainly there exist mixed setups for various reasons. But then getting a push to upgrade when running a mixed setup wouldn't be the end of the world. We could still simplify our lives and remove most of tweaks to the TLS 1.2 settings but keep it around with an `insecureAllowOldTLSVersions` flag as an escape hatch for those who really must run latest version on something together with an old version on something else. We could keep a static list of good cipher suites for 1.2, so not reducing security but just dropping the auto detection optimizations.

**Comment by greatroar** [comment]
I should have checked first. There are only 82 devices, .1%, on 1.1.4.

**Comment by savchenko** [comment]
> the Ubuntu Syncthing package is at 1.1.4 for the latest LTS release, 20.04.

For what it is worth, upcoming Debian 11 "Bullseye" will be shipped with Syncthing v1.12.1 (Go v1.15).
I have created a bug-report [#983500](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=983500), but there was not much traction with it.

> There are only 82 devices, .1%, on 1.1.4.

Syncthing asks user if they wish to enable telemetry. Many decline.

**Comment by jms19** [comment]
Just to add current versions are in my experience protocol incompatible with v1.11.0 which isn’t a year old

**Comment by imsodin** [comment]
> Just to add current versions are in my experience protocol incompatible with v1.11.0 which isn’t a year old

There is no protocol incompatibility between any v1.x.y. If you do have problems with such a version, please do ask about them on https://forum.synchting.net, not post to an unrelated issue on github.

And please don't comment on closed issues. The only reason to do so is if the issue isn't actually solved. Generally if in doubt don't post on a github issue, but write to https://forum.syncthing.net - thanks.
