### ISSUE TITLE
Fast connect to new devices following config update

### ISSUE THREAD

**Issue by gsaraf** [syncthing/syncthing#7600]
We are using syncthing as part of a larger system, as an end-to-end solution for file synchronization between two [or more] endpoints. It is working well for us, but we have encountered a problem with the time it takes syncthing to register that a new device was added and connect to it.

In our system, syncthing is running in the background, and at a random time we may change the devices to which we sync the folder[s]. We do this using the REST API - `/rest/config/devices`. Following that we listen on events that inform us that the connection has succeeded and initial content sync completed.

The problem is that after the config update it can take up to a minute (`stdConnectionLoopSleep`) for syncthing to actually reach out to the remote device, and in an interactive context that is a **long** time. This affects all users of the REST API - I think reducing the time it takes to implement config updates would be useful to everyone 😄 

From reading around the code, it seems a relatively simple solution of adding a "deviceConfigUpdated" channel to the select in the loop in `lib/connections/service.go:connect`, and sending a signal from the REST api handlers once the config is updated, should solve. I'd be happy to work on this 🙂

**Comment by AudriusButkevicius** [comment]
I don't think this is incredibly high priority for us, but given you seem to be able to navigate the code, I think the best way to approach this is to file a pull request.

I don't think the rest api needs to do anything. I think the connection service already reacts to config changes, so all we need to do is reset the sleep timer as the config gets updated (and new devices get added/addresses get updated)

**Comment by gsaraf** [comment]
Your suggestion makes sense - I'll take a look and submit a PR soonish.

Thank you! 🙂
