### ISSUE TITLE
Files ignored on one remote do not get synced

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#7608]
Came up in https://forum.syncthing.net/t/syncthing-lost-one-file-out-of-a-dozen-on-one-node/16721.

Reproducer:

Initial State: Devices A, B share a folder. A has file F, B ignores file F.

1. Connect additional device C to B, wait for index exchange and sync/pull to finish.
2. Connect C to A.

Expected: File F gets synced to C.

Result: File F does not get synced to C.

This is a regression introduced in https://github.com/syncthing/syncthing/pull/7476, which in turn fixes https://github.com/syncthing/syncthing/issues/7474.

**Comment by calmh** [comment]
I don't understand. Why doesn't C prefer the non-invalid version of F and pull that?

**Comment by imsodin** [comment]
Since #7476 C pulls the global invalid file in step 1, i.e. it has the newest version locally, just invalid. And having an up-to-date invalid file means being in-sync, not needing a file. Otherwise e.g. an ignored file would keep being "pulled", and marked as ignored.

**Comment by calmh** [comment]
Right.... We could react to the fact that the head of the global list goes from being invalid to being valid, but since we already have an in-sync (but invalid) entry we don't do anything, as this is the same situation as if we'd ignored it ourselves for example. A pickle, indeed.

**Comment by imsodin** [comment]
Exactly. I considered two options to solve this:

1. Just mark everything as needed when the global version changes from invalid to valid. Problems:  
Whether an item is needed is then based on transient information. When the item changes in the future, it's not clear whether it was needed or not before -> messed up accounting.  
And even worse: We'd then need more special cases in the puller: It needs to handle pulling stuff that we don't actually need (e.g. locally changed item is then suddenly needed, but we shouldn't actually override that with the global).  
A no-go.
2. Add a new local invalid flag `FlagLocalGlobalInvalid` and consider needed when that flag is set and the global is valid, regardless of version. Works, but means that we either need to do an additional file info lookup when updating a local file or store that local flag in the global version list. Seems doable, but still means lots of complexity.

**Comment by calmh** [comment]
I see now how the status quo becomes the more preferable option.
