### ISSUE TITLE
Warn/complain/stop if all files have disappeared

### ISSUE THREAD

**Issue by ged-nn** [syncthing/syncthing#762]
node 1 - repo test
node 2 - repo test
node 3 - repo test

On node 3 directory for repo not access - hdd disconnected.
All node make clear repo test . :-(

**Comment by ged-nn** [comment]
Thanks.
Now problems:
1. Disk mount and syncthing starting and run
2. I unmount disk and not stop syncthing.
All repo clear. :-(

Need control flag repo if path not found.

**Comment by AudriusButkevicius** [comment]
Yeah, we should check for the marker before each rescan.

**Comment by ged-nn** [comment]
My repo over 250GB and over 70000 files. 
Rescan this repo long time - if add 10GB over 20 min, may be disconnect hdd in progress.
May be need check flag on before start and apply scan after check flag after scan repo?

1. Check flag before scan
2. scan
3. Check flag after scan
4. Apply result scan.

**Comment by AudriusButkevicius** [comment]
to be honest, you should sort out your scripts to shut syncthing down before unmounting.

**Comment by ged-nn** [comment]
I do not specifically unmount. Accidentally disconnect cable. oops.

**Comment by AudriusButkevicius** [comment]
Also, we should perhaps allow reviving the folder every rescan interval, given the marker has reappeared.

**Comment by AudriusButkevicius** [comment]
Ref #420

**Comment by ged-nn** [comment]
It's all good.
But what if the disc is disconnected during a scan?
At this point syncthing considers that the files were deleted.
Although file .stfolder also becomes not accessible and repo should be stopped.

**Comment by AudriusButkevicius** [comment]
if it's there before, and there after, I guess we will have to assume success.
