### ISSUE TITLE
apt: installed syncthing package post-inst script returned exit status 1

### ISSUE THREAD

**Issue by andreymal** [syncthing/syncthing#7628]
Today I made apt-get dist-upgrade and got the error described in the title. I added `set -x` to `syncthing.postinst` and saw this result:

```
Setting up syncthing (1.16.0) ...
+ [ configure = configure -a -z 1.15.1 ]
+ [ configure = abort-remove ]
+ [ configure = configure -a -n 1.15.1 ]
+ upgradeFromVersion=1.15.1
+ after_upgrade 1.15.1
+ :
+ command -v deb-systemd-invoke
+ has_systemd=0
+ [ 0 -eq 0 ]
+ systemctl daemon-reload
+ [ 0 -eq 0 ]
+ systemctl list-units --plain --no-legend syncthing@*.service
+ [ -n  ]
+ pkill -HUP -x syncthing
dpkg: error processing package syncthing (--configure):
 installed syncthing package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 syncthing
```

It tries to HUP non-existent process because Syncthing is stopped at the time of the update.

I think this script should take into account that Syncthing can be stopped and ignore this error.

**Comment by imsodin** [comment]
Does the upgrade still go through or does it abort, staying at the old version?

**Comment by andreymal** [comment]
Syncthing is upgraded successfully and working fine, but dpkg thinks it's still not configured because of this error. It can be easily fixed by running `apt-get -f install` when Syncthing is started, but I think the post-inst script can just ignore this error regardless of the current status of Syncthing

**Comment by imsodin** [comment]
Sure, didn't mention that: It will of course be fixed (just PRed the tiny change). I was just wondering about the damage here: Whether it's still upgradable or not after encountering the error.

**Comment by GLLM** [comment]
Hi, 

thanks for the fix !

Just a quick remark : I encountered the same issue:  despite running `apt-get -f install`, i cannot run `apt dist-upgrade `anymore (ubuntu 20.04.2 LTS).
So the fix will be precious :)

Thanks
GLLM

**Comment by imsodin** [comment]
If apt/dpkg marked the package as broken/not configured, you can fix this regardless of whether Syncthing is running or not like this: In the `/var/lib/dpkg/info/syncthing.postinst` file append ` || :` to the pkill line such that it looks like this:

```
    pkill -HUP -x syncthing || :
```

Then run `apt install -f` to fix the broken install.
