### ISSUE TITLE
Failure checking encryption consistency

### ISSUE THREAD

**Issue by Schwefelholz** [syncthing/syncthing#7634]
Hello,

I tried to set up an untrusted/encrypted folder, but failed.

- The "trusted" device is v1.16.0 on Linux 64-bit, the "untrusted " one is v1.16.0-preview.2 on Android.
- The devices are already sharing an unencrypted folder.
- I tried to share an additional folder on the trusted device with a password and the untrusted device received the sharing request and accepted it.
- Afterwards I received following message on the trusted device: "_2021-05-05 09:21:01: Failure checking encryption consistency with device untrusted for folder "Default Folder" (default): folder is configured to be encrypted but not announced thus_"
- After that, the two devices do not connect to each other anymore.
- Once I unshare the folder on the trusted device again and remove the new folder from the untrusted, the devices connect again and commence syncing the already shared folder.

I'd be happy to provide any additional information required.

Best,
Thomas

**Comment by AudriusButkevicius** [comment]
I suspect Android wrapper prompt for accepting folders doesn't handle encryption and this would not happen if you accepted the folder via the web ui.

I suspect this should live in the android wrapper repo, and not this one.

**Comment by imsodin** [comment]
On the untrusted device (android for you), the folder needs to be configured as receive-only. Which the app most likely doesn't do. You need to go to the web UI, remove the folder, and then accept it there - then the folder type is set correctly automatically. Which isn't ideal, as the web UI doesn't know about the android file path restrictions.

**Comment by imsodin** [comment]
What Audrius said: https://github.com/syncthing/syncthing-android/issues/1650
