### ISSUE TITLE
encrypted sharing doesn't work 1.16

### ISSUE THREAD

**Issue by tauceti82** [syncthing/syncthing#7635]
Hi,

using latest 1.16 release on both clients I tested the encryption feature and added the password to both clients on a folder with Send&receive.

When putting a file in one folder I get syncing:pull:generic error and the files are not synced.

[IL2OU] 09:54:34 INFO: Puller (folder "encstorage" (uini7-azrs4), item "test.txt"): syncing: pull: generic error
[IL2OU] 09:54:34 INFO: "encstorage" (uini7-azrs4): Failed to sync 1 items
[IL2OU] 09:54:34 INFO: Folder "encstorage" (uini7-azrs4) isn't making sync progress - retrying in 1m0s.

I only do sharing with direct connections and relaying and discovery is off...it works with non encrypted folders

**Comment by imsodin** [comment]
Lets debug/discuss this on the forum to see what the actual root cause is - once that's established an actionable issue can be created again (and fixed :) ). Please post to https://forum.syncthing.net.

**Comment by tauceti82** [comment]
ok sry
