### ISSUE TITLE
favicon not working Firefox & derivative browsers

### ISSUE THREAD

**Issue by ajshea** [syncthing/syncthing#7638]
Firefox, Pale Moon, and similar browsers do not display the initial favicon (or at all) since the favicon link is dynamically created by evaluating javascript expressions. 

The bug is due to some FireFox forks not re-loading the scripted favicon link after the page first loading. Chrome and forks do, but this is non-standard behavior. 

See https://forum.syncthing.net/t/fixing-syncthing-favicons-in-firefox/15726 for description of cause and work around. 

I suggest that the initial favicon link not result in a 404, as noted by calmh at https://forum.syncthing.net/t/fixing-syncthing-favicons-in-firefox/15726/2. 

If it is desirable to have the favicon change based on status, the favicon link can be updated as at present. However, changing the favicon after page load does not appear to be standard behavior, so many browsers may not display the change.

**Comment by ajshea** [comment]
Suggested code fix from Pale Moon developer: 

```
const favicon = document.querySelector('[rel=icon]');

function eventHandler(yourEvent) {
  favicon.href = "https://link.to/yourdynamicfavicon.ico";
}
```
The main <link> element should have a valid temporary/generic icon listed.

That should be cross-browser compatible, but even so, there's no guarantee that anything will be updated dynamically because, as said, the GUI isn't part of page content.

**Comment by bt90** [comment]
Would be nice if the icon also loads without authentication. This is mandatory for it to show up in password managers like Bitwarden.

**Comment by ajshea** [comment]
It looks like for the favicon to load without authentication will require a default page -- at present the default page (which loads before authentication) is just a piece of text "Not Authorized". Once authentication takes place, the default.html page is loaded, which has the scripted favicon at issue above.

I"m not finding any html source to modify the "Not Authorized", so I suspect that it is direct output rather than served.

It seems that serving an initial unauthenticated html page would be the appropriate method for serving the initial favicon.
