### ISSUE TITLE
Some usage reporting stats missing since June 2020

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#7639]
All performance info (data transferred, memory used, ...) and users joined/left are missing on data.syncthing.net. That coincides with https://github.com/syncthing/syncthing/pull/6770. I only did a quick check in the JS console that it isn't a graph creation issue, .e. that the data is actually missing in the data obtained from `ursrv`. I haven't checked whether the data gets lost while aggregating incoming reports or when querying the db from the UI.

**Comment by AudriusButkevicius** [comment]
Every time I touch this, I die a little bit inside, because 75% of time is spent trying to work out how to start/stop services, figure out where the logs go because it's using some orthodox service manager.
