### ISSUE TITLE
Allow local announcements via REST

### ISSUE THREAD

**Issue by bt90** [syncthing/syncthing#7640]
This is an attempt to come up with a workable solution for https://github.com/syncthing/syncthing-android/issues/1628

My idea would be to let the wrapper determine the device IPs via the Android framework and pass them via a REST call to syncthing which publishes them.

**Comment by imsodin** [comment]
Generally I don't think there's much point having tickets for hypothetical android wrapper usage. If Catfriend or anyone else working on the app requires functionality, we can definitely work that out when it comes up.  
And in this particular instance: The app can already do local discovery itself and then set the found addresses in the config through rest, so the needed pieces should be there.
