### ISSUE TITLE
SystemD service not found after reboot

### ISSUE THREAD

**Issue by Densaugeo** [syncthing/syncthing#7642]
I have carefully followed the instructions in the SystemD section of https://docs.syncthing.net/users/autostart.html:

- Extracted the tarball to `/home/lunariel/syncthing-linux-amd64-v1.16.0/`
- Symlinked the `linux-systemd/system/syncthing@.service` file in `/usr/lib/systemd/system`
- Created a symlink to the Syncthing binary in `/usr/bin`

Enabling the SystemD service initially works:

~~~
[lunariel@morpheus system]$ sudo systemctl enable syncthing@lunariel
Created symlink /etc/systemd/system/multi-user.target.wants/syncthing@lunariel.service → /home/lunariel/syncthing-linux-amd64-v1.16.0/etc/linux-systemd/system/syncthing@.service.
Created symlink /etc/systemd/system/syncthing@lunariel.service → /home/lunariel/syncthing-linux-amd64-v1.16.0/etc/linux-systemd/system/syncthing@.service.
[lunariel@morpheus system]$ sudo systemctl start syncthing@lunariel
[lunariel@morpheus system]$
~~~

After doing this I confirmed it is running by visiting `http://127.0.0.1:8384/`.

However, after rebooting, the service does not start automatically and SystemD cannot find it:

~~~
[lunariel@morpheus system]$ sudo systemctl status syncthing@lunariel.service
Unit syncthing@lunariel.service could not be found.
~~~

The symlinks created in `/etc/systemd/system` are still present:

~~~
[lunariel@morpheus system]$ ls -l | grep syncthing
lrwxrwxrwx. 1 root root   88 May  8 16:09 syncthing@lunariel.service -> /home/lunariel/syncthing-linux-amd64-v1.16.0/etc/linux-systemd/system/syncthing@.service
[lunariel@morpheus system]$
~~~

Enabling the service again allows it to be started, but after rebooting SystemD can't find it again until the enable command is run.

**Comment by bt90** [comment]
Why would you create symlinks and not simply copy the files?

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
