### ISSUE TITLE
Automatically Ignore Files To Review Later

### ISSUE THREAD

**Issue by seniorm0ment** [syncthing/syncthing#7645]
When using Syncthing, I notice it sometimes gets stuck on files due to naming issues or permission issues, etc.
From what I can tell, there is no way to easily "ignore" the issue files automatically? maybe this is done on purpose. but my issue is, it doesn't continue syncing the rest of the stuff.
can it not be made so it syncs everything it can sync, and then offers a list of all the files it had trouble with and allows you to ignore or go manually modify that file?
currently it just gets stuck on that file, and doesn't sync the rest of the stuff, which is an issue imo.

**Comment by AudriusButkevicius** [comment]
That's not how it works, it syncs everything it can already, unless it's some directory that for example cannot be created due to name, which means the files inside of that directory cannot be created either.

If you are having issues, I suggest you use the forum first.
