### ISSUE TITLE
Incorrect local and global states after ignoring and unignoring files

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7649]
I'm sorry for the so-so title, but this is a little bit complicated. I have experienced the issue in my real network, and now I have managed to reproduce it.

1. Create a new Send Only folder on Device 1 with a few files in it, and share it with Device 2.
2. Accept the folder on Device 2 as Send & Receive, but set the ignore patterns to `*`.

   ![image](https://user-images.githubusercontent.com/5626656/117575240-f0602c00-b11b-11eb-88e9-5122a3aa6a38.png)
   ![image](https://user-images.githubusercontent.com/5626656/117575548-50a39d80-b11d-11eb-8aec-e397569fb36f.png)

5. Add a new file to the folder on Device 2, and unignore it with `!`.

   ![image](https://user-images.githubusercontent.com/5626656/117575256-04a42900-b11c-11eb-93f2-3e05547a46f6.png)

6. Change the folder type on Device 1 to Send & Receive.

   ![image](https://user-images.githubusercontent.com/5626656/117575311-31584080-b11c-11eb-8877-81065524a2b5.png)

7. Remove the `!` exclusion from the ignore patterns on Device 2, so that everything is ignored again with `*`.

   ![image](https://user-images.githubusercontent.com/5626656/117575379-77ad9f80-b11c-11eb-87e1-387e48a71b3c.png)

   As you can see in the screenshot, the global state on Device 2 has been broken.

8. Clear the ignore patterns on Device 2, so that there are no ignore patterns on both devices now.
9. The final state looks like this, i.e both folders seem to think that they are up-to-date, but the are not.

   ![image](https://user-images.githubusercontent.com/5626656/117575441-bf342b80-b11c-11eb-9a9a-d2023dad86a2.png)
   ![image](https://user-images.githubusercontent.com/5626656/117575457-d07d3800-b11c-11eb-85f9-bb2a269e692a.png)

**Edit**: Resetting deltas on Device 2 seems to get the folder states back to normal.

**Comment by imsodin** [comment]
Just tried to repro and everything went as expected, i.e. after 5. the global/local states report just what you'd expect. I created files 1 through 10 containing 1 through 10, and the additional file was alongside those.

If you can still repro, can you enable `model` and `db` debug logging and provide the logs please.

**Comment by tomasz1986** [comment]
I have tried with the current main, and the issue is still here.

Here are the logs:

[syncthing1.log](https://github.com/syncthing/syncthing/files/6458276/syncthing1.log)
[syncthing2.log](https://github.com/syncthing/syncthing/files/6458279/syncthing2.log)

**Comment by imsodin** [comment]
Thanks a lot. There is a race on the index sender involving the folder being paused in the beginning, and the timing of resuming it and receiving cluster config and incoming indexes. That's also why I couldn't repro - probably did something slightly different and thus triggered different timings.  
Anyway in addition to that race (well connected to it) there's also a hint in the logs at how the dreaded reoccurring problem of missing indexes can occur. Took a good bit of staring at logs and thinking along convoluted bits in the model code, but I do hope my working theory will prove correct and lead to a fix :)

**Comment by Zcehtro** [comment]
Hi.

I'm having a similar problem where the clients finished syncing but the folder contents are incomplete on both sides.
My folders were always set to Send & Receive, but I did use ignore patterns and had to quit Syncthing a couple times before it finished its initial sync.

**Comment by imsodin** [comment]
@tomasz1986 

Could you please repro and collect logs again with a build of the following PR:  
https://github.com/syncthing/syncthing/pull/7671
Direct link to download from CI (login as guest possible):
https://build.syncthing.net/buildConfiguration/Syncthing_BuildWindows/102828?buildTab=artifacts
The only change is added debug logging. As I wrote before, the logs you provided already contain a "smoking gun", however I still haven't managed to reconstruct the exact sequence of events to arrive at the same problem. And thus while I am reasonably sure how to prevent the problem from happening, I can't be fully certain that it does - which would be nice :)

**Comment by tomasz1986** [comment]
Here you are:

[syncthing1.log](https://github.com/syncthing/syncthing/files/6476253/syncthing1.log)
[syncthing2.log](https://github.com/syncthing/syncthing/files/6476260/syncthing2.log)

I did compile the build myself (with Go 1.16.3 under Windows 10), which I hope will not make a difference. Just got used to self-compiling Syncthing, so now it feels weird not to do it…

**Comment by imsodin** [comment]
Thanks a whole lot, this clears things up!  
My previous working theory was not the culprit here. And the fix I have prepared for that would have prevented the worst damage here, but it would have still been buggy (would have given a delayed index transfer instead of missing indexes like you are experiencing here).  
Anyway I updated the debugging PR with a small, targeted fix:  
https://github.com/syncthing/syncthing/pull/7671

**Comment by tomasz1986** [comment]
I can confirm that the problem is gone with the newest fix 👍.

**Comment by tomasz1986** [comment]
Just one last question, as I still have this issue in my real setup at the very moment. Is it enough to cherry-pick the commit, or do I need to do some manual resetting (`-reset-deltas` etc.) in addition to it?

**Comment by imsodin** [comment]
Just cherry-picking is enough - the first time a build is run with that commit the same operation as `--reset-deltas` is run automatically.

**Comment by AudriusButkevicius** [comment]
I think the title of the issue is not correct anymore? More like "database corruption caused by pausing and unpausing folders"?

**Comment by imsodin** [comment]
Ah, issue title/changelog entry bike-shedding initiating :D

The relevant bit is not the un-/pausing, but accepting a folder invite. The same bug manifested itself also in https://github.com/syncthing/syncthing/issues/7337. It's also by @tomasz1986, and it somehow slipped through the cracks - feel free to complain if you don't get any feedback on bug requests (not that it should be needed to).

What about "Index corruption after accepting a new folder from a remote"?  
In my mind "database corruption" is the thing due to memory/disk faults (or goleveldb bugs), but maybe that's just me.

**Comment by pagalba-com** [comment]
Global ignore should finally come #7311
