### ISSUE TITLE
data.syncthing.net site is super heavy

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7662]
The website source is a part of the Syncthing repo, so I hope that the issue does belong here…

Basically, the website is HEAVY. I have opened it today on an older laptop, running a Core 2 Duo / 8GB RAM / SSD, and the site takes ~1 minute to render. The problem is not with the Internet speed, but rather all the graphs and especially the map being extremely heavy to process. Once loaded, the graphs do seem to operate fine, but the map is still super laggy.

During the rendering phase, the CPU is pegged at 100%. The RAM usage for the tab in Chromium x64 totals at about 380 MBs.

I'm not sure if anything can be done about the generated code (i.e. graphs / map), but I just wanted to have this recorded somewhere.

**Edit**: Just to add, I remember opening the site on an older Android phone with limited RAM a few months ago, and there the whole browser crashed.

**Comment by calmh** [comment]
I think it is what it is... There's a lot of data in those graphs. My six year old computer and three year old phone both render the site in about a second, but I hear you on your 15 year old laptop... Nonetheless, I don't think this is something we should spend effort on.

**Comment by tomasz1986** [comment]
Yeah, this is not that important, but I thought that it might be useful to have a bug recorded in case someone does decide to step in and do something about it…

For the record, this is a profile from Chromium, where the site took ~37 seconds to load.

![image](https://user-images.githubusercontent.com/5626656/117789742-9a0dfd00-b283-11eb-9c09-47326586dff0.png)
[Profile-20210511T175233.json.txt](https://github.com/syncthing/syncthing/files/6457908/Profile-20210511T175233.json.txt)

> My six year old computer and three year old phone both render the site in about a second,

It also takes as much as ~12 seconds to render on Ryzen 4350G here…

![image](https://user-images.githubusercontent.com/5626656/117789977-dd686b80-b283-11eb-882d-e21b062d1d48.png)

**Comment by calmh** [comment]
Yeah... Safari on my i7-6700K, hitting reload. Supposedly rendering takes 4.5s, but most of that were stuff "below the fold", the first two graphs were done a lot quicker. 🤷 

<img width="1849" alt="Screen Shot 2021-05-11 at 11 15 02" src="https://user-images.githubusercontent.com/125426/117791331-7da19e80-b24a-11eb-8647-9bb4f6e71945.png">
