### ISSUE TITLE
OCI Runtime Failure With Docker Image

### ISSUE THREAD

**Issue by royaltongue** [syncthing/syncthing#7668]
### Include required information

Please be sure to include at least:

 - **Syncthing Version:** Docker syncthing/syncthing
 - **What Happened:** See error log below
 - **What You Expected To Happen:** Successful creation of Docker Container
 - **Steps To Reproduce:** Run `docker-compose up -d`

After running `docker-compose up -d` is am given the following error:
```
ERROR: for syncthing  Cannot start service syncthing: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"write sysctl key net.core.rmem_max: open /proc/sys/net/core/rmem_max: no such file or directory\"": unknown

ERROR: for syncthing  Cannot start service syncthing: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"write sysctl key net.core.rmem_max: open /proc/sys/net/core/rmem_max: no such file or directory\"": unknown
ERROR: Encountered errors while bringing up the project.
```

**Comment by bt90** [comment]
PR incoming: #7670

You can safely remove `sysctls` section from the compose file to fix this.
