### ISSUE TITLE
bug: cli subcommand is stuck on non-interactive shell

### ISSUE THREAD

**Issue by karlicoss** [syncthing/syncthing#7673]
Syncthing version: v1.16.1

I've been trying to use `syncthing cli` over SSH to configure my hosts (ansible-like provisioning software, but it's details). 
E.g. `ssh hostname 'syncthing cli config options local-ann-port set 1234'`.

**Expected**: it applies the configuration 

**Result**: it gets stuck with no output

**Investigation**: 

- sshing onto the host and running command in terminal seemed to work perfectly. I tried `strace` and it seemed that when running over ssh, the command is indefinitely waiting. After trying with `ssh -t` instead (which worked), I figured it had to do with TTY, searched in the code and it seems it's this bit to blame

https://github.com/syncthing/syncthing/blob/ef4b8a2cf86d067c59a31ab3de20ffc0dca6e877/cmd/syncthing/cli/main.go#L103-L106

I figured I could try providing stdin output instead and indeed: `echo 'config options local-ann-port set 1234' | ssh hostname 'syncthing cli'` -- that worked.

**Resolution**

- might be nice to write `waiting for commands input` to stderr or something like that before trying to read so at least it's clear to user what's happening
- might be nice to add something about it to `syncthing cli --help'? Since it's kind of unexpected, especially considering that it all works as expected when you test it in the terminal.
- not sure what was the intent of this stdin reading functionality (didn't find docs), so hard to tell what's the right way to actually solve it..
  I don't know Go apis, but wonder whether it could check that there is no stdin and skip the reading part? Seems wrong that it gets stuck on it

Happy to help with the former two if it's welcome, not sure about the latter since I don't know Go well. Thanks!

**Comment by AudriusButkevicius** [comment]
I think we should check the arguments, and only do this wizardry if after parsing all flags, we're just left with `syncthing cli`.
Otherwise it's going to be garbage anyway.

I also wonder if scanner.Err() is non-nill straight from the get-go (because presumably stdin is closed when running ssh?)

**Comment by AudriusButkevicius** [comment]
Before someone asks "why do we even need it", the idea behind it is that you could have a file/stream with multiple commands, and effectively apply all of them atomically in one swoop, without having to round trip to the http service for every command, causing a ton of things restarting/saving/doing things inside of syncthing.
