### ISSUE TITLE
Syncthing squashes UTF-8 combining characters in filenames

### ISSUE THREAD

**Issue by madduck** [syncthing/syncthing#7674]
I'm using Syncthing 1.16.1 on Debian unstable, and have UTF-8 throughout the filesystem.

UTF-8 has this concept of "combining characters". In a nutshell, this means that instead of the character `â`, two characters are combined, i.e. an `a`, and a "combining character", which is zero-width, "^", which is then overlayed. Pretty smart, but Syncthing does not seem to handle this properly, and squashes the combination to the target character, if such a target character exists. If such a single character does not exist, then it preserves the combination.

Here is a demo:
```
local% touch $'\u0061\u0302' $'\u0062\u0302'
local% ls
â  b̂
local% ls -1 | while read i; do echo $i | xxd; done
00000000: 61cc 820a                                a...
00000000: 62cc 820a                                b...
```
So far so good, but now Syncthing runs, and one of the files gets replaced:
```
local% ls
b̂  â
local% ls -1 | while read i; do echo $i | xxd; done
00000000: 62cc 820a                                b...
00000000: c3a2 0a                                  ...
```
This is inconsistent, and can lead to problems. For instance, if the file `â` with the combining characters in the name is now recreated, Syncthing will report "failed items"
![image](https://user-images.githubusercontent.com/195073/118205785-42ef6e80-b4b5-11eb-8f51-1bea4a87c4ad.png)

Unless there is a good reason, when normalising filenames, please do not squash combining characters.

**Comment by calmh** [comment]
Syncthing applies the system expected normalization form (NFD / NFC) on files it touches for consistency. macOS gets NFD (decomposed), everyone else gets NFC (composed).

**Comment by madduck** [comment]
@calmh Interesting! First time I hear about this. I don't think my system doesn't expect any normalisation. Is this a filesystem thing? Shell? File manager? Desktop environment?

**Comment by imsodin** [comment]
While I can't find anything official by mac, there's plenty of hits searching for it, e.g. https://duckduckgo.com/?t=ffab&q=mac+utf-8+normalization+nfd&ia=web

The basic idea is that it's a recipe for disaster to potential have two files on disk with the "same" name, just different normalization. And Syncthing being cross-platform, and platforms not agreeing on normalization, this is bound to happen. Thus we make sure that all names are in the default normalization form for a given platform (where it's clear that on a particular system, of a platform, circumstances may differ from the default - that's where manual configuration comes in).

Anyway this is working as expected, so lets move any further discussions to the forum please: https://forum.syncthing.net

**Comment by madduck** [comment]
I appreciate your stance, @imsodin, but I do not agree that this is "further discussion for a forum". Yes, it's a recipe for disaster to have two files on disk with the "same" name, but in this case, it's Syncthing that creates the second file, and then throws up its hands and says that it doesn't know how to proceed.

I could imagine at least three ways to remediate this:

1. Make it configurable whether normalisation should be in effect (advanced/expert option)
2. Record internally that normalisation took place, so when the original file re-appears, do something better than throwing up your hands. Ideas could include hardlinking, symlinking, etc..
3. Let the user override this on a per-file basis, as sometimes this is not in our control. In my case, it's `youtube-dl` writing a file, and I will file a bug with them to get them to NFD-normalise the file on Linux, but it's unreasonable to expect this from every possible tool while it's not standardised or otherwise enforced.

**Comment by AudriusButkevicius** [comment]
You can already disable it: https://docs.syncthing.net/advanced/folder-autonormalize.html
Hence this stays closed I think.
