### ISSUE TITLE
UTF-8 normalization doesn't work on macOS

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#7677]
When Syncthing sees a filename which is well formed UTF-8 but unexpected normalization form for the system it corrects the normalization form on disk. This currently doesn't happen on macOS, instead the file remains unscanned and "invisible" to Syncthing.

**Comment by calmh** [comment]
I added a test case, and with a normal `basicFs` it works, but when wrapped with a `caseFs` the normalization logic breaks.

**Comment by opensource21** [comment]
Unfortunately, this fix doesn't fix the original problem. See [Forum](https://forum.syncthing.net/t/german-umlaute-like-aou-seems-to-make-trouble/16804/32?u=opensource21) for further details.
