### ISSUE TITLE
Authenticated STUN

### ISSUE THREAD

**Issue by savchenko** [syncthing/syncthing#7682]
### Required information

> what problem your new feature would solve?

Let users use their own STUN servers with authentication (e.g. via `coturn`).

> how or why you think it is generally useful?

It would allow to keep the traversal functionality while ensuring that all traffic stays within a controlled perimeter.

> what alternatives or workarounds you considered?

Set `stunServer` to a private IP and wrap it in a tunnel. Latency predictably suffers, wouldn't recommend.

**Comment by AudriusButkevicius** [comment]
Coturn as far as I understand is a turn server. We don't use standard turn, we use relays.

We use stun purely for external address discovery which I am not sure authentication makes sense for, given nobody on the internet seems to be using it.

**Comment by savchenko** [comment]
I was thinking that Syncthing uses STUN for NAT traversal:
```
stunServer

stun.callwithus.com:3478, stun.counterpath.com:3478, stun.counterpath.net:3478, 
stun.ekiga.net:3478, stun.ideasip.com:3478, stun.internetcalls.com:3478, 
stun.schlund.de:3478, stun.sipgate.net:10000, stun.sipgate.net:3478, 
stun.voip.aebc.com:3478, stun.voiparound.com:3478, stun.voipbuster.com:3478, 
stun.voipstunt.com:3478 and stun.xten.com:3478 

(this is the default).
```

Perhaps I was wrong.

> We use stun purely for external address discovery

Not sure how it assists address discovery, but OK.

**Comment by AudriusButkevicius** [comment]
From Wikipedia:
```
STUN is a tool used by other protocols, such as Interactive Connectivity Establishment (ICE), the Session Initiation Protocol (SIP), and WebRTC. It provides a tool for hosts to discover the presence of a network address translator, and to discover the mapped, usually public, Internet Protocol (IP) address and port number that the NAT has allocated for the application's User Datagram Protocol (UDP) flows to remote hosts. The protocol requires assistance from a third-party network server (STUN server) located on the opposing (public) side of the NAT, usually the public Internet.
```

STUN is not the traversal part, it's the address discovery part for doing traversal.
