### ISSUE TITLE
remote devices always Disconnected

### ISSUE THREAD

**Issue by zhoudanbao** [syncthing/syncthing#7683]
### I use the gui SyncTrayzor at v1.16.1, Windows (64-bit Intel/AMD)
 ### I have a nas running syncthing as a file sync server, and a computer that is not on the same LAN with the nas. For the past few days the remote device appears to be  always "Disconnected". When I use my laptop on the same LAN,  I can synchronize

## Here is the running log：
[start] 21:30:30 INFO: syncthing v1.16.1 "Fermium Flea" (go1.16.3 windows-amd64) teamcity@build.syncthing.net 2021-05-05 07:37:23 UTC
[HASXT] 21:30:30 INFO: My ID: HASXTVZ
[HASXT] 21:30:31 INFO: Single thread SHA256 performance is 433 MB/s using minio/sha256-simd (372 MB/s using crypto/sha256).
[HASXT] 21:30:31 INFO: Hashing performance is 357.91 MB/s
[HASXT] 21:30:31 INFO: Overall send rate is unlimited, receive rate is unlimited
[HASXT] 21:30:31 INFO: Using discovery mechanism: global discovery server https://discovery.syncthing.net/v2/?noannounce&id=LYXKCHX
[HASXT] 21:30:31 INFO: Using discovery mechanism: global discovery server https://discovery-v4.syncthing.net/v2/?nolookup&id=LYXKCHX
[HASXT] 21:30:31 INFO: Using discovery mechanism: global discovery server https://discovery-v6.syncthing.net/v2/?nolookup&id=LYXKCHX
[HASXT] 21:30:31 INFO: Ready to synchronize "xxx" (syncphoto) (sendreceive)
[HASXT] 21:30:31 INFO: Using discovery mechanism: IPv4 local broadcast discovery on port 21027
[HASXT] 21:30:31 INFO: Using discovery mechanism: IPv6 local multicast discovery on address [ff12::8384]:21027
[HASXT] 21:30:31 INFO: GUI and API listening on 127.0.0.1:8384
[HASXT] 21:30:31 INFO: Access the GUI via the following URL: http://localhost:8384/
[HASXT] 21:30:31 INFO: QUIC listener ([::]:22000) starting
[HASXT] 21:30:31 INFO: TCP listener ([::]:22000) starting
[HASXT] 21:30:31 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting
[HASXT] 21:30:31 INFO: My name is "DESKTOP-HCE0JFC"
[HASXT] 21:30:31 INFO: Device TGOZNZC is "unraid" at [dynamic]
[HASXT] 21:30:33 INFO: Completed initial scan of sendreceive folder "xxx" (syncphoto)
[HASXT] 21:30:42 INFO: New NAT port mapping: external TCP address 113.54.152.xxx:9504 to local address 0.0.0.0:22000.
[HASXT] 21:30:42 INFO: Detected 1 NAT service
[HASXT] 21:30:42 INFO: quic://0.0.0.0:22000 detected NAT type: Symmetric NAT
[HASXT] 21:32:40 INFO: Joined relay relay://118.126.117.xxx:22067

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by zhoudanbao** [comment]
> This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.
> 
> Thanks!

Thanks! I will searching it on that forum.

**Comment by zhoudanbao** [comment]
> This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.
> 
> Thanks!

I found out what the problem is, I just updated my router. At the beginning of opening dhcp function randomly assigned 192.168.1.105, which occupying the 20000 port. upnp automatically bind 192.168.1.105:20000. subsequently I specify the nas address as 192.168.1.25, resulting in the 20000 port can not be used.
