### ISSUE TITLE
CLI: strconv.ParseInt error when adding new device via CLI

### ISSUE THREAD

**Issue by HectorMalot** [syncthing/syncthing#7685]
I tried adding a new device using the CLI and found that the command resulted in a strconv.ParseInt error. Odd, because the internal format is a DeviceID which I think is an array of bytes. Quoting the device-id in the cli results in the same error.

command: `syncthing cli config devices add --device-id=XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX --name="MyName"`

The error I get is: `Incorrect Usage: invalid value "XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX" for flag -device-id: strconv.ParseInt: parsing "XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX": invalid syntax` and the device is not added to Syncthing. 

Note: I've masked the device-id above.

### initial troubleshooting

Assuming I'm not making some obvious mistake in running the command: I suspect that [recli](https://github.com/AudriusButkevicius/recli) is mistakenly trying to convert the input from a string to an Int. But I haven't had time to further dive into it.

### Required information

* Version: 1.16.1
* installed via apt on Debian 4.19.152-1 (device is a intel NUC)

**Comment by AudriusButkevicius** [comment]
I think that part in general could do with some work. I suspect you'll end up with a device with no sensible defaults pre-configured.

**Comment by HectorMalot** [comment]
Impressed at how fast this was fixed. Thank you. I just made a donation.
