### ISSUE TITLE
Not sending symlinks to old client (...) - please upgrade to v0.14.14 or newer

### ISSUE THREAD

**Issue by mgw2013** [syncthing/syncthing#7691]
I've installed on several machines with LinuxMint  Linux Mint 20.1 Ulyssa  and Ubuntu 20.04.2 LTS all with latest update. One system is a brand new setup.
`$ apt show syncthing
 Package: syncthing
 Version: 1.1.4~ds1-4ubuntu1
`
Browser: Vivaldi	3.8.2259.40 (Stable channel) (64-Bit) or Opera latest stable

**Issue**: Upon sync all systems report several times 
`Not sending symlinks to old client (client id) - please upgrade to v0.14.14 or newer`

Frankly, I'm lost a bit.

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by mgw2013** [comment]
??? the installed version is 1.1.4 how comes the system is telling me that the installed version is 0.something?
