### ISSUE TITLE
#7691 - Not sending symlinks to old client (...) - please upgrade to v0.14.14 or newer

### ISSUE THREAD

**Issue by mgw2013** [syncthing/syncthing#7693]
What am I missing??? the installed version is **1.1.4** how comes the system is telling me that the installed version is **0**.something?

**Comment by imsodin** [comment]
As I wrote in the other issue, you are clearly having an issue with your setup and need help. That's what a very helpful community on https://forum.syncthing.net is doing and what that forum is for. Post your questions there and you will receive help.

As I have no interest in closing more issues from you, I have preventively blocked you from posting for a day on github - you can still post to https://forum.syncthing.net and are welcome to do so.
