### ISSUE TITLE
ursrv: unrealistic uptime data, likely due to unset RTC (1970-01-01)

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7698]
The 100% percentile currently lists 51.4 years as the uptime, which is obviously impossible. I guess that someone must have changed their OS date to the future or something…

![image](https://user-images.githubusercontent.com/5626656/118817372-1b9e0480-b8ee-11eb-9ba6-2ed50d7d8389.png)

**Comment by AudriusButkevicius** [comment]
Sure, who cares? It's not that some decisions are based on these numbers.

It's more like a relay running on RPi on startup, because it has no RTC, the relay starts up before the time gets set by ntp/chrony.

**Comment by bt90** [comment]
We could still filter any uptime which predates the project start :wink:

**Comment by AudriusButkevicius** [comment]
I'm going to close this.
It's cosmetic, a number that doesn't have much meaning. I am not bothered.

**Comment by tomasz1986** [comment]
I personally don't agree. This data is occasionally referred to in other places (e.g. see https://news.ycombinator.com/item?id=13856552). It would be good to make sure that the numbers presented there are actually real.

> It's cosmetic, a number that doesn't have much meaning. I am not bothered.

Yeah, but then the counterargument is - why collect/present it at all, if there is no meaning to it?

**Comment by imsodin** [comment]
To me the main point here is this is cosmetical, low(est) importance, no need for discussion and low effort to fix. Basically the kind of thing that sure, fix it if it annoys you, but having an issue lie around and involving (by now 4) people in it is a waste of time. A closed bug doesn't necessarily mean "everything needs to stay as is, don't touch it", it might just mean "this is not worth tracking".
