### ISSUE TITLE
Add rest endpoint(s) to dismiss pending folder/device invitations

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#7700]
See https://github.com/syncthing/syncthing/issues/7179#issuecomment-843853381 and following. Before moving pending folders/devices to the db, they could be dismissed by modifying the config. Now there's endpoints to get these (GET `/rest/cluster/pending/...`) but no way to dismiss. E.g. handling `DELETE` on the same endpoints (either with some payload or ID in the url to only dismiss specific entries) would probably do. However it's done, dismissing those should be possible through the api.

**Comment by AudriusButkevicius** [comment]
Are we saying that the dismiss buttons when the prompt comes up don't do anything as it stands?

**Comment by imsodin** [comment]
I am saying there is only an "ignore" button, which adds the folder/device to the ignored folders/devices, which in turn triggers removing the pending folder/device. So dismissing something now means: Ignoring it, waiting for dismissal, un-ignoring it. This issue is about a one-stop solution to just dismiss an invitation, without ignoring.

![image](https://user-images.githubusercontent.com/15955093/118947867-0cec3780-b958-11eb-8606-915701aa991e.png)

**Comment by acolomb** [comment]
Pull Request is #7712 is ready, anyone please comment there if you have suggestions regarding the GUI and / or wording.
