### ISSUE TITLE
Accepting a receive encrypted folder share should prompt the user to input a password

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7705]
1. On Device 1, create a new folder with some files and share it with Device 2.
2. On Device 2, accept the new folder as SR, and also share it with password with Device 3.
3. On Device 3, accept the new folder as RE, and also share it with Device 1.
4. On Device 1, the Share Folder pop-up shows.
   ![image](https://user-images.githubusercontent.com/5626656/119228861-f7d9f900-bb4f-11eb-91e4-8d50dba261e9.png)
5. However, clicking the "Share" button results in errors on Device 1 and Device 3.
   ![image](https://user-images.githubusercontent.com/5626656/119228893-2f48a580-bb50-11eb-812b-c3b2a80d7df1.png)
   ![image](https://user-images.githubusercontent.com/5626656/119228896-32439600-bb50-11eb-9108-63eaff8903a3.png)

For better user experience, I think that it would be nice to have Syncthing prompt the user on Device 1 to input the password, especially since s/he may not even know that the folder is set to RE on the remote device. I would also argue that the error message is way too technical for an average user to understand what is even going on :wink:.

**Comment by Ratio2** [comment]
1. Add folder to normal device.
2. Add folder with same id to untrusted device and share with normal device.
3. Click Share in popup on normal device. We successfully share folder without password with untrusted device.

Expect: We must deny adding normal folders from untrusted device.
