### ISSUE TITLE
Bad interaction between systemd unit and home directory encryption (Failure on home directory)

### ISSUE THREAD

**Issue by cpitclaudel** [syncthing/syncthing#7709]
Description of the issue: Syncthing's systemd unit fails to start if the user's home directory is encrypted with fscrypt.  To reproduce:

1. Set up home directory encryption with fscrypt: see e.g. https://wiki.archlinux.org/title/Fscrypt
2. Enable syncthing's systemd unit (on Ubuntu it's installed by default, so use `systemd enable syncthing@$USER.service`
3. Log out and back in

Expected: Syncthing starts in the background

Actual result: 

```
May 25 19:59:27 host systemd[1]: Started Syncthing - Open Source Continuous File Synchronization for user.
May 25 19:59:28 host syncthing[1050]: WARNING: Failure on home directory: mkdir /home/user/.config: required key not availab>
May 25 19:59:28 host systemd[1]: syncthing@user.service: Main process exited, code=exited, status=1/FAILURE
```

I guess this is a bug in the systemd unit definition?  Restarting the service from the command line works fine.

Version info:

```
$ syncthing --version
syncthing v1.16.1 "Fermium Flea" (go1.16.3 linux-amd64) deb@build.syncthing.net 2021-05-05 07:37:23 UTC [noupgrade]
$ lsb_release -d
Description:	Ubuntu 21.04
```

**Comment by AudriusButkevicius** [comment]
It can't start with an encrypted home directory, you should make it dependant on fscrypt unit if there is one.

Regardless, don't think its our bug, as its dependant on the stuff you use. If you want to keep talking about this, forum feels like the better place.
