### ISSUE TITLE
repos/protobuf/gogoproto/gogo.proto: File not found.?

### ISSUE THREAD

**Issue by zjsunzone** [syncthing/syncthing#7710]
$ go generate -x generate.go
go run scripts/protofmt.go .
2021/05/26 15:46:01 Formatting ext.proto
2021/05/26 15:46:01 Formatting lib\config\authmode.proto
2021/05/26 15:46:01 Formatting lib\config\blockpullorder.proto
2021/05/26 15:46:01 Formatting lib\config\config.proto
2021/05/26 15:46:01 Formatting lib\config\deviceconfiguration.proto
2021/05/26 15:46:01 Formatting lib\config\folderconfiguration.proto
2021/05/26 15:46:01 Formatting lib\config\foldertype.proto
2021/05/26 15:46:01 Formatting lib\config\guiconfiguration.proto
2021/05/26 15:46:01 Formatting lib\config\ldapconfiguration.proto
2021/05/26 15:46:01 Formatting lib\config\ldaptransport.proto
2021/05/26 15:46:01 Formatting lib\config\observed.proto
2021/05/26 15:46:01 Formatting lib\config\optionsconfiguration.proto
2021/05/26 15:46:01 Formatting lib\config\pullorder.proto
2021/05/26 15:46:01 Formatting lib\config\size.proto
2021/05/26 15:46:01 Formatting lib\config\tuning.proto
2021/05/26 15:46:01 Formatting lib\config\versioningconfiguration.proto
2021/05/26 15:46:01 Formatting lib\db\structs.proto
2021/05/26 15:46:01 Formatting lib\discover\local.proto
2021/05/26 15:46:01 Formatting lib\fs\copyrangemethod.proto
2021/05/26 15:46:01 Formatting lib\fs\types.proto
2021/05/26 15:46:01 Formatting lib\protocol\bep.proto
2021/05/26 15:46:01 Formatting lib\protocol\deviceid_test.proto
protoc -I ../ -I . --gogofast_out=Mgoogle/protobuf/descriptor.proto=github.com/gogo/protobuf/protoc-gen-gogo/descriptor,paths=source_relative:ext ext.proto
go build -o scripts/protoc-gen-gosyncthing scripts/protoc_plugin.go
go run generate.go lib/protocol lib/config lib/fs lib/db lib/discover
2021/05/26 15:46:02 lib/protocol returned: [lib\protocol\bep.proto lib\protocol\deviceid_test.proto]
repos/protobuf/gogoproto/gogo.proto: File not found.
lib/protocol/bep.proto:6:1: Import "repos/protobuf/gogoproto/gogo.proto" was not found or had errors.
2021/05/26 15:46:02 Failed generatinglib/protocol
exit status 1
generate.go:28: running "go": exit status 1

**Comment by imsodin** [comment]
Yup, that repository must be present to generate the protos. Generally there's a few particularities around the build process, that's why there's "build.go". To generate protos, use `go run build.go proto`.
