### ISSUE TITLE
LDAP auth fails with hardcoded bindDN

### ISSUE THREAD

**Issue by OffsiteGuru** [syncthing/syncthing#7717]
Syncthing Verison:
syncthing v1.16.1 "Fermium Flea" (go1.16.3 linux-amd64) deb@build.syncthing.net 2021-05-05 07:37:23 UTC [noupgrade]
Running on Debian 11, accessing with Google Chrome & Mozilla Firefox.

I think I've got a fairly simple one. I'm trying to create a Syncthing instance that can only be logged into by a single LDAP user.
After looking though the documentation it seemed simple enough, I'd just put the users full DN in the `<bindDN>` config option, and whatever they type in the user field would be ignored. Then as long as the password matched, they're in.

However I kept getting errors like this in the log:
```
[2JEUI] WARNING: LDAP Bind: LDAP Result Code 49 "Invalid Credentials":
[2JEUI] INFO: Wrong credentials supplied during API authorization from 127.0.0.1:49562
```
So I poked around and found that as long as there was an %s in the <bindDN> entry, I could get it to work. For example, here are some things I tried.
```
<bindDN>uid=%s,ou=People,ou=Department,dc=example,dc=com<bindDN>
Login as user.name works.
```
```
<bindDN>uid=user.name,ou=People,ou=Department,dc=example,dc=com<bindDN>
Login as user.name FAILS with code 49.
Login with only password, and leave the username blank, also fails with code 49.
```
```
<bindDN>uid=user.name%s,ou=People,ou=Department,dc=example,dc=com<bindDN>
Login with only password, and leave the username blank, it works!
```
```
<bindDN>uid=user.%s,ou=People,ou=Department,dc=example,dc=com<bindDN>
Login as 'name' and it works.
```

So it seems that if Syncthing doesn't have an %s to replace it's going to fail the login with 'Invalid Credentials'.
I'd like it to not fail if it doesn't have an %s to substitute, but at the very least this error doesn't make much sense.

For reference I'm setting up a multi-user Syncthing server for remote workers. I have everything worked out in an elegant way with the exception of this issue. For now I'm going to tell the users to leave the username blank when they log in, but it's going to cause a little confusion.

If there is another way to accomplish this, I'm all ears. The group membership search doesn't seem to help in this case, unless I was to create a group for each user, which would be silly. If there was a way to say that user must match uid=user.name, that would work, but it doesn't seem that the search field can bend that way.

EDIT: I'd like to clarify that it doesn't matter where the %s is in the `<bindDN>` string. As long as it's there, I can log in by leaving the username blank.

**Comment by calmh** [comment]
Yeah, it expects a placeholder in there so the generated string will be incorrect if there isn't one.

**Comment by calmh** [comment]
>  If there was a way to say that user must match uid=user.name, that would work, but it doesn't seem that the search field can bend that way.

I think `(uid=user.name)` should work fine, or something similar based on the CN or other attribute of the user.

**Comment by OffsiteGuru** [comment]
@calmh I'm kind of embarrassed. I didn't catch that the %s needs to be consumed in the search field as well, and that's why `(uid=user.name)` wasn't working as a search term.
I'm going to test this more, but it seems to be working just fine. I am seeing some errors in the log and on the screen when I log in, but that may be cruft from previous attempts. I'll make sure it's all clean and report back.
I'll also share my systemd script that makes this system possible.

**Comment by OffsiteGuru** [comment]
@calmh Yep! It's all working! Thanks!
Here's the systemd script I use for my multi-user sync server: https://gist.github.com/OffsiteGuru/609770b47a7cf83255d5d1117f31506a
