### ISSUE TITLE
Syncthing uses autodiscovered address when a static address is assigned

### ISSUE THREAD

**Issue by zhulik** [syncthing/syncthing#7718]
Hello amazing community,

I have 2 syncthing nodes(actually there are more in the cluster, but only these ones are affected) one is running on a local "home server" and the second is running on a "cloud server" which has a static ip address.

There is a wireguard tunnel between them. I don't want syncthing traffic to go through the tunnel to avoid it's overhead and reduce latencies. On the "home server" I assigned the "cloud server" a static address like `tcp://domain.name:22000` where `domain.name` points to the public ip address. However syncthing autodiscovered "cloud server"'s ip address in the wireguard tunnel and keeps using it. 

Since the "home server" is not exposed to the internet, it's only reachable from the "cloud server" using either public proxies or through the wireguard tunnel.

Is there a way to force both servers to use internet instead of the tunnel?

### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using
 - browser and version, if applicable
 - what happened,
 - what you expected to happen instead, and
 - any steps to reproduce the problem.

**Comment by calmh** [comment]
> I assigned the "cloud server" a static address like tcp://domain.name:22000 where domain.name points to the public ip address. However syncthing autodiscovered "cloud server"'s ip address in the wireguard tunnel and keeps using it.

If you set the remote device address as above (and not the default `dynamic`) then no automatic address discovery is used. Perhaps you did something other than I assume? I suggest opening a support thread on the forum, with screenshots of the setup to clarify.

**Comment by acolomb** [comment]
Each of the two servers try to connect to the other one. If you configured a static IP for cloud on home, but cloud still has "dynamic" for cloud, then cloud may find home through discovery and by chance establishes a connection before the opposite one succeeds. If I understand your setup correctly.

Easiest solution I see would be to block incoming traffic from the wireguard interface to port 22000 on the home server using its local firewall. But please, do head over to the forum for further analysis and advice. Thank you.

**Comment by zhulik** [comment]
@acolomb Thanks for the answer, now I get why it happens. Sorry for disturbing.

**Comment by AudriusButkevicius** [comment]
Also, going forward, please use forum for support.
