### ISSUE TITLE
Display down- and upload rates with bps per default

### ISSUE THREAD

**Issue by bt90** [syncthing/syncthing#7725]
Download and upload rates describe network bandwidth usage and should therefore use the appropriate unit by default. The current default of B/s is confusing for new users as they will compare the values with speedtest results or ratings of their network gear which all use bps.

Case in point: https://forum.syncthing.net/t/please-help-how-can-i-get-speed-higher-than-2-mb-s/16859/11

**Comment by calmh** [comment]
No. We used to do precisely this. It caused no end of complaints and confusion. #900 #934 and I'm sure all kinds of threads on the forum from way back.
