### ISSUE TITLE
Syncthing hanging

### ISSUE THREAD

**Issue by timaah** [syncthing/syncthing#7735]
No panic.db's in the Log. I have had a few of those in the past, generally recreating the index in %localappdata%\syncthing resolves any of those issues.

![WholeSyncthingHangs](https://user-images.githubusercontent.com/25911201/120392158-512eee80-c2ed-11eb-993d-87345811c735.png)

As you can see form the date the last input syncthing sends is that it is not making progress, that it has failed and then nothing else will update until syncthing is closed and rebooted. Trying to do a restart from the Browser has no effect.

I have had this happen a number of times, with a large number of folders, restarting currently is the solution to deal with the problem.

We are using syncthing to sync updates for games across our network (61 computers).
Syncthing Version - 1.17.0 - Chrome Browser

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
