### ISSUE TITLE
Update version of Jquery

### ISSUE THREAD

**Issue by ndgoodman** [syncthing/syncthing#7738]
Please update Jquery from 2.2.2 to 3.5.0 or later.
This is a helpful tool for updating
https://github.com/jquery/jquery-migrate
It will write console warnings any time a breaking change is encountered

**Comment by imsodin** [comment]
There's plenty of things that could be updated in the web UI - definitely no reason to keep open issues for all of those. If you are interested in web UI development of Syncthing open a topic on the forum to discuss what to approach and how.
