### ISSUE TITLE
Out-of-sync state of zero-byte files is not reflected on peers

### ISSUE THREAD

**Issue by James-Mat** [syncthing/syncthing#7741]
From [https://forum.syncthing.net/t/remote-stays-on-up-to-date-but-is-really-out-of-sync-when-looking-at-its-instance-directly/16852](https://forum.syncthing.net/t/remote-stays-on-up-to-date-but-is-really-out-of-sync-when-looking-at-its-instance-directly/16852)

I have two peers (A and B) in sync with each other, whereby one of the peers (B) has a filename length limit.
If a zero-byte file with a filename that surpasses this limit is created on peer A, peer B naturally can't sync it and displays 'Out of sync' in its gui. However, peer A will keep showing 'Up to date' for the remote device in its gui.
If now a byte is added to the problematic file, peer A will show 'Syncing (99%, 1 B)' as expected in its gui.

The expected behaviour for me would be that peer A reflects the out-of-sync state of peer B even when syncing zero-byte files, for example, as suggested by imsodin, by displaying 'Syncing (99%, 0 B)'.

Even though I discovered the behaviour due to a filename length limit on one peer, I'd expect it to occur with any issue that prevents the file from being synced on a remote.
I used 1.16.1 and also 1.17, both on Alpine and Windows, but imsodin was able to confirm the problem looking at the code, so I don't think this is relevant.

**Comment by James-Mat** [comment]
Great to see a fix on the way so fast!

**Comment by imsodin** [comment]
It will be.

**Comment by uok** [comment]
I'm seeing a "95%, 0 B" status on a computer with v1.18.0 - is this the same bug?
If I click on "out of sync items", there is just an empty list (JSON from XHR to /remoteneeded returns empty array for "files")

**Comment by imsodin** [comment]
That's something else. Respectively it might be a regression of the fix if I didn't consider some scenario. Lets debug this on the forum.
