### ISSUE TITLE
Show discovery and listener status when not failed

### ISSUE THREAD

**Issue by acolomb** [syncthing/syncthing#7743]
In the GUI, the listener and discovery status is displayed as a count of active mechanisms. In case of a failure, details can be seen in a modal on click. The modal should be available always and show non-error status details as well.

**Comment by acolomb** [comment]
This is missing from the change log for v1.18.0-rc.1?

**Comment by imsodin** [comment]
Yep, my blunder when merging: The commit message needs to reference the issue (`fixes #7743`) for it to be picked up. Will be in the next RC.
