### ISSUE TITLE
Syncthing unable to recognize files with some special utf8 char sequence

### ISSUE THREAD

**Issue by tcai793** [syncthing/syncthing#7744]
## Include required information
Version: v1.16.1, macOS (64-bit Intel/AMD)
Browser: Chrome

## What happened

There are 2 files in the directory, but syncthing only recognizes 1 of them. Clicking the rescan button has no effect.
```
$ ls -al
total 8000
-rw-r--r--@  1 tcai  staff  4084267 Jan 22  2020  1_ Intro, résumés • S20.pptx
drwxr-xr-x   5 tcai  staff      160 Jun  3 21:58 .
drwxr-xr-x+ 77 tcai  staff     2464 Jun  3 21:58 ..
-rw-r--r--@  1 tcai  staff     6148 Jun  3 21:14 .DS_Store
drwxr-xr-x   2 tcai  staff       64 Jun  3 21:00 .stfolder
```
![image](https://user-images.githubusercontent.com/16743408/120748136-1ed0ed00-c4b7-11eb-8fe4-79782179bc08.png)

It appears that .DS_Store is being recognized, but the pptx file is not being recognized.

However, open this folder in Finder, selecting that pptx file, press enter, and press enter again, then clicking rescan button causes syncthing to recognize this file. This operation changes the filename into what it was visually (but somehow different in encoding. See next section).
![image](https://user-images.githubusercontent.com/16743408/120748414-97d04480-c4b7-11eb-9339-96903950364a.png)

## Further Investigation

Checking the log files and examine the file names closely shows that the hexdump of those filenames are different for the letter "é." Before "modifying" the file name, the letter's hexdump is 65 CC 81, which is a LATIN SMALL LETTER E and a COMBINING ACUTE ACCENT placed back to back. After "modifying the file name", the letter's hexdump becomes C3 A9, which is a LATIN SMALL LETTER E WITH ACUTE. This difference might be the root cause of the problem.

## Log file
Please see lines 91 and 92 for an example of two different encodings for the same letter.

[log.log](https://github.com/syncthing/syncthing/files/6595933/log.log)

**Comment by imsodin** [comment]
I believe this has the same cause as https://github.com/syncthing/syncthing/issues/7677, and is fixed by https://github.com/syncthing/syncthing/pull/7678 in v1.17.0.
