### ISSUE TITLE
Running into "operation not permitted" errors due to filename

### ISSUE THREAD

**Issue by StephenFluin** [syncthing/syncthing#7746]
### Does your log mention database corruption?

It does not.

### Include required information

Please be sure to include at least:

 - Synthing Android 1.17.0 running on Galaxy S21 Ultra running Android 11.
 
I created a shared folder on my desktop (v1.17.0, Linux (64-bit Intel/AMD)) Build 2021-05-22
I then shared this with my mobile device.
Files started transferring.
Most files transfered perfectly, but 78 of them got stuck.
All of the files with a colon in the name (eg `1:56 Funhouse.mp3` or `test:colon.mp3`) fail, but any file name without a colon (`testcolon.mp3`) sync fine.

On the mobile devices, the files show as having failed.

> Syncing: opening temp file: open /storage/emulated/0/vlog/.syncthing.1:56 funhouse.mp3.tmp: operation not permitted

**Comment by AudriusButkevicius** [comment]
Colon is not a valid character on some (most?) filesystems.

Also, please use the forum going forward, given the nature of the question is support like, hence is usually handled there.

Thanks.
