### ISSUE TITLE
Adding new receive-encrypted folder drops connection with an error

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#7748]
Adding a folder, setting it as receive-encrypted, sharing it with another device (where it already exists and is shared):

```
Jun  5 14:24:59 lun0 syncthing: [D4SLA] 14:24:59 INFO: Adding folder "documents-untrusted" (bws2n-ewavx)
Jun  5 14:24:59 lun0 syncthing: [D4SLA] 14:24:59 INFO: No stored folder metadata for "bws2n-ewavx"; recalculating
Jun  5 14:24:59 lun0 syncthing: [D4SLA] 14:24:59 INFO: Ready to synchronize "documents-untrusted" (bws2n-ewavx) (receiveencrypted)
Jun  5 14:24:59 lun0 syncthing: [D4SLA] 14:24:59 INFO: Completed initial scan of receiveencrypted folder "documents-untrusted" (bws2n-ewavx)
Jun  5 14:24:59 lun0 syncthing: [D4SLA] 14:24:59 INFO: Index for nonexistent or paused folder "bws2n-ewavx"
Jun  5 14:24:59 lun0 syncthing: [D4SLA] 14:24:59 INFO: Connection to PSEUDOP-YLA5DBR-XO2HBNT-2FOG4AC-SWOW5EZ-H3QQY76-GISB7PG-E2SWOA2 at 81.88.12.150:22000-83.233.124.224:22000/tcp-client/TLS1.3-TLS_AES_128_GCM_SHA256 closed: handling index for bws2n-ewavx: no such folder
```

Then things work after reconnect so no real problem, but we're note supposed to do this I think.

**Comment by imsodin** [comment]
That's intended: When the receive-encrypted folder is added, it doesn't have the encryption token. Thus the connection is dropped to receive a new cluster-config with the token once the connection is re-established. We want the token in case another device connects, to ensure the password is the same so we don't have data with different passwords in a single folder. We could store tokens from rejected folders, and when adding a new receive-encrypted folder check if a token for that ID is present to evade this connection drop.
