### ISSUE TITLE
Folder Type of PC-A :Send Only,Console of PC_B shows directory is not null,can not delete

### ISSUE THREAD

**Issue by mrzhanzhanzhan** [syncthing/syncthing#7757]
System environment:Windows 10
Language:Simple Chinese

PC_A: Send Only
PC_B: Send And Receive

Files from PC_A **less than** PC_B's,Console of PC_B shows can not delete,because directory is not null
(That's roughly what it means in Chinese)

I want to PC_B synchronized from PC_A Only,How to make it right?
I would be very thankful.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
