### ISSUE TITLE
Android 11: netlinkrib: permission denied

### ISSUE THREAD

**Issue by bt90** [syncthing/syncthing#7763]
Switched to a Pixel 4a 5G with Android 11 and seem to get hit by Androids new restrictions regarding interface IPs:

Syncthing log:
```
21:10:27 [23O7L] INFO: Listing network interfaces: route ip+net: netlinkrib: permission denied
```

Syncthing fork log:
```
21:10:27W/libsyncthingnat type=1400 audit(0.0:2115): avc: denied { bind } for scontext=u:r:untrusted_app:s0:c101,c257,c512,c768 tcontext=u:r:untrusted_app:s0:c101,c257,c512,c768 tclass=netlink_route_socket permissive=0 b/155595000 app=com.github.catfriend1.syncthingandroid
21:10:27W/libsyncthingnat type=1400 audit(0.0:2116): avc: denied { read } for name="somaxconn" dev="proc" ino=875467 scontext=u:r:untrusted_app:s0:c101,c257,c512,c768 tcontext=u:object_r:proc_net:s0 tclass=file permissive=0 app=com.github.catfriend1.syncthingandroid
```

Could this prevent Syncthing from sending broadcasts/multicasts as mentioned in https://github.com/Catfriend1/syncthing-android/issues/801 ?

**Comment by imsodin** [comment]
Still something to be (and already is) tracked in the android repo as there isn't anything actionable from Syncthings point of view if the system simply rejects using basic/vital functionality: https://github.com/syncthing/syncthing-android/issues/1663
