### ISSUE TITLE
The initial "Scanning (%)" gets reset to 0% at every -unrelated- folder action

### ISSUE THREAD

**Issue by CarlosGS** [syncthing/syncthing#7768]
- Version of Syncthing and operating system:
v1.17.0, Linux (64-bit Intel/AMD)
 - What happens:
The initial "Analyzing (%)" gets reset back to zero every time a folder action is performed, even for actions that shouldn't affect scan progress.
For example -and I'm referring to the first scan right after setting up a new folder- let's say an hour has passed:
![Screenshot_20210614_203224](https://user-images.githubusercontent.com/1636266/121941485-a3412c80-cd4f-11eb-8db4-d2d7324047fa.png)
Then, i.e., going to "Edit->Share" and marking the checkbox to share with another device, clicking save:
![Screenshot_20210614_203355](https://user-images.githubusercontent.com/1636266/121941664-da174280-cd4f-11eb-8b77-ff56f6c97b0c.png)
The percentage goes back to zero, giving the impression that everything has restarted (while in fact 24% of the work _has_ been done, and the new percentage will just go faster).
Such reset also happens when changing other seemingly unrelated parameters such as folder label, versioning mode, resync interval, etc.
 - Why it matters:
This is a low priority visual bug. However, please note that it can be misleading for new users ("_oh wow it is restarting this slow scan every time_"). Due to this small visual issue, it took me a while to realize that the scan is only slow the first time. Initially I thought efficiency was low (sorry for opening #7761), which made me want to disable periodic scanning, etc. I don't want that to happen to other people ^^

Low priority. Relevant mostly for new users' experience. Thank you for this brilliant software!

**Comment by AudriusButkevicius** [comment]
So I think you've nailed it why it happens, but I don't really see a good way to solve this.

The percentage is always "for the work that is left to be done", so I don't think you could sensibly represent it differently.

For example, we could scan 50% of the files, you could pause the folder, remove that 50% of the files that we just scanned, add 50% of different files etc. In which case continuing from 50% would make no sense.

**Comment by imsodin** [comment]
One sensible thing I see to address this is not a UI change, but a pretty involved one: Let the folder take care of its own config changes, and only restart if anything changes that actually requires a restart (a label change hardly does). Besides solving lots of the cases mentioned here, it will have other small, but likely noticeable performance improvements. On the other hand it's a change with some scare potential, and a lot of work.

**Comment by CarlosGS** [comment]
I didn't use the pause feature at all, though I totally see the "restart upon pausing" problem.
In the case of only updating some of these settings/tabs and clicking Save:
![Screenshot_20210614_220158](https://user-images.githubusercontent.com/1636266/121952152-29637000-cd5c-11eb-87b9-083682714f63.png)
From your answers, I take that the folder is briefly paused/restarted internally in order to apply the changes?
It wouldn't be enough time for users to modify the folder contents though, so maybe this could be treated as a particular case.

The reset happens too when sharing the analyzing folder from the "Other devices" menu. So maybe @imsodin's proposal would be cleaner, rather than saving/restoring the percentage at each valid case.

**Comment by AudriusButkevicius** [comment]
Anything modifying folders configuration effectively results in a restart, especially things like sharing a folder, as that affects quite a lot in terms of the state the folder needs to store for the new device that it's sharing the folder with.

Any restart will cancel all operations, so this is still expected.

Personally I am in favour of closing this, as I don't see how this could be fixed.

Perhaps it could be fixed with a lot of engineering, somehow persisting the state of scans between restarts, but given the issue 
is so insignificant, I don't think it's worth it.

Besides, there are other ways to know the folder is making progress, namely the local item counts do get updated as the scan makes progress, so you'd see these numbers growing every time.

**Comment by CarlosGS** [comment]
Another option would be to use a remaining/decreasing number, rather than a percentage. i.e. "Analyzing 237 files". Currently looking into the code towards a PR, but it's my first time at go and can't promise anything.

I agree 100% that this issue is only relevant for new users, but felt really bad for thinking Syncthing wasn't being efficient, and didn't want that to happen to others.

I appreciate your super fast response and detailed explanations. Thank you!

**Comment by AudriusButkevicius** [comment]
It used to just say `scanning`, but people were not happy as it wasn't giving indication how much work if left, or how long this will take.

Saying scanning N files shows progress, but it's not of any use to understand how far you are or how much is left, because files are not of equal size.

**Comment by CarlosGS** [comment]
Ah - since file count is not currently available from the gui's javascript, the only simple option would be to have something like "_Scanning (~2h 32m left)_" or "_Scanning (327 GiB left)_".

I could make that PR; I would also respect your decision to discard this entirely. In any case: thanks!

**Comment by uok** [comment]
long ago I had the idea to display ETA on each folder giving the user a rough info how long e.g. sync will take:
https://github.com/syncthing/syncthing/issues/899
there was a good comment with design idea that neatly displays this:
https://github.com/syncthing/syncthing/pull/3928#issuecomment-274993674
