### ISSUE TITLE
Syncrhonization never ends and sync-conflict created

### ISSUE THREAD

**Issue by iranzo** [syncthing/syncthing#7777]
### Does your log mention database corruption?

No

### Include required information

Please be sure to include at least:

 ![image](https://user-images.githubusercontent.com/312463/122393492-3909d100-cf75-11eb-8ff3-e401f073410a.png) which version of Syncthing and what operating system you are using

Fedora with 1.16.1 and Raspbian with 1.17.0

 - browser and version, if applicable

Chrome

 - what happened,

I've a set of computers:
- Desktop 1
- Desktop 2
- Laptop 1
- Laptop 2
- Laptop 3
- NAS1
- NAS2
- Remote host 1
- Remote raspberry 1
- Local raspberry 2

I've a folder with 387 Gb of files, setup in the following way:

- Desktop 1, Desktop 2, Laptop 1, Laptop 2, Laptop 3 have R/W permissions
- All other hosts (NAS1, NAS2, Remote Host1, Remote Raspberry 1 and Local Raspberry 2) are 'receiving encrypted'.

Password is defined on the R/W hosts for the encrypted peers, all of them with the same password.

 - what you expected to happen instead, and

The hosts should sync, propagating changes from R/W devices between them and having remote copies on the encrypted-end ones
 - any steps to reproduce the problem.

Not sure about a reproducer, but what it happens:

- R/W hosts get to a final status of being 'Synced'
![image](https://user-images.githubusercontent.com/312463/122393614-576fcc80-cf75-11eb-9086-4e4472c96d99.png)

- Encrypted hosts, start creating lot of sync-conflict files, that, even if I remove them, will get new ones
![image](https://user-images.githubusercontent.com/312463/122393504-3ad39480-cf75-11eb-923b-0fd34b2aeaef.png)
![image](https://user-images.githubusercontent.com/312463/122393538-432bcf80-cf75-11eb-9d7b-50efc40b68bd.png)

From the R/W hosts, I can check details for the ENC hosts and it shows something like this:
![image](https://user-images.githubusercontent.com/312463/122393688-6e162380-cf75-11eb-876e-4fa99d347000.png)

As it can be seen on the first image, even  when starting with a clean folder (deleting form encrypted host, removing folder, adding the share and start syncing), it ends up with lot of local files that are nowhere else.

**Comment by imsodin** [comment]
Thanks for testing the new receive-encrypted/untrusted feature and reporting!

There have been relevant changes/fixes since v1.16.0. Please upgrade all devices to the latest release-candidate when encountering problems with receive-encrypted folders to make sure they aren't caused by something that is already fixed.

And then if the problem persists, lets debug this on https://forum.syncthing.net until we find out what's going on, such that an actionable bug report can be created (and there's less back-and-forth on the issue tracker) - thanks!
