### ISSUE TITLE
Folders status not accurate if/when corresponding remote service is paused

### ISSUE THREAD

**Issue by x80486** [syncthing/syncthing#7782]
Started using `Syncthing` recently...and I can't be happy enough for this marvelous piece of software. I haven't found any major issues so far, but I do know that this one can be improved upon.

To make it simple, if I'm on a Mac:

1. Add a remote device (`Linux` host)
2. Accept a share `some-folder@linux-host` location
3. Pause that (just added) remote device
4. Stop the `Syncthing` process (in the Mac)
5. Switch to the `Linux` host and add/remove/update some content on the aforementioned (shared) sub-directory/location
6. Switch to the Mac and start `Syncthing` again — it will have the `Linux` host device paused
7. Folders shared by the same shouldn't state they are `Up to Date` because something might have changed (as explained before) on that device, and since it's paused, the `Up to Date` is inaccurate

### Include required information

Please be sure to include at least:

 - Syncthing `1.17.0` (on both ends)
 - Firefox `89.0.1`
 - The status for the folder is innacurate
 - The interface to account for possible, unknown changes, until the sync finishes

**Comment by AudriusButkevicius** [comment]
I think this is working as intended.

They are up to date based on what was announced. 

If the device is paused/they can't change data, no new announcements can be received.

Showing as "out of date" would mean that things are out of date immediately as the device disconnects or is paused.

I think this would be more confusing than what we have currently.
