### ISSUE TITLE
cmd/ursrv: Further anonymize anonymous usage reporting results

### ISSUE THREAD

**Issue by datasyncer** [syncthing/syncthing#7787]
The data at [data.syncthing.net](data.syncthing.net) is fun to look at, but it's not fully anonymous.

For example looking at the country usage breakdown shows 1 user in Yemen (and more countries). With some additional info the user can be de-anonymized. Same with the one person with 105TiB of data in their largest folder.

At the least I suggest that groups with less than some number (e.g. 10) participants get a label `<10` rather than their actual number. Same with the percentiles. I find it reasonable to have up to 99th percentile, but 100th percentile is de-anonymizing for the outlier. Same goes for the heat map.

There is science on anonymizing data such as [differential privacy](https://en.wikipedia.org/wiki/Differential_privacy), [k-anonymity](https://en.wikipedia.org/wiki/K-anonymity), and more.

**Comment by datasyncer** [comment]
I would like to tackle this, if possible.
I'm not sure where to find the code for the `data` subdomain. Is it in the `website` repo?

**Comment by imsodin** [comment]
Cool!  
The usage data processing and presentation is in https://github.com/syncthing/syncthing/tree/main/cmd/ursrv. The relevant bits for you are some go code in https://github.com/syncthing/syncthing/blob/main/cmd/ursrv/analytics.go and the frontend stuff in https://github.com/syncthing/syncthing/blob/main/cmd/ursrv/static/index.html.

**Comment by datasyncer** [comment]
I've found the relevant parts in `index.html` but am confused as to _what templating engine/language you are using_ in the web code? Searching the docs gave no results.

I couldn't find any documentation about running the `data` subdomain. I managed to get it running with an empty database, nonetheless.

**Comment by imsodin** [comment]
That's https://golang.org/pkg/html/template/ - basically the stuff in curly braces corresponds to the return value of `getReport` in main.go.

The binaries are just pushed to the server and everything restarted on deploy - there isn't anything in place for testing/staging. However if the changes are simple enough that you can get to something, that should work, someone can just "test it" live, reverting is easy enough.

**Comment by calmh** [comment]
Closed per discussion in the PR.
