### ISSUE TITLE
Make defaults more privacy focused

### ISSUE THREAD

**Issue by cheribral** [syncthing/syncthing#7792]
I tested out syncthing not long ago for the first time and thought it was quite a useful tool.  As I went to install it on a few more devices in my home network and watched traffic on my router, I quickly realised that the default install talks to the internet conveying information about my network without asking.  It could even end up sending internal data over the internet!
There is no option on the command line which I can see to shut this off, and there doesn't seem to be a good way to disable this without first starting the server to get a web page where I can turn this off.  Even with command line options, it would likely be hard to set on mobile phones etc.

While I can understand the usefulness of a relay and global discovery servers in some cases, those options should be opt-in, not opt-out after it already did what you didn't want it to do.  This gives a really bad impression of the software, regardless of the usefulness.

Could the defaults be made so that these internet facing options are turned off initially?

**Comment by ProactiveServices** [comment]
This would be better off discussed on the [forum](https://forum.syncthing.net/). This wouldn't be an enhancement to the software as it's designed to be continuous and automatic, and for many users, it would not work without these features.

**Comment by imsodin** [comment]
Those are reasonable defaults aligning with e.g. our [goal no3: Easy to use](https://github.com/syncthing/syncthing/blob/main/GOALS.md#3-easy-to-use). And I don't think it's reasonable to assume that a tool designed to keep your data in sync continuously between all your devices will not connect "to the internet". There's a documentation page dedicated to what information can be inferred from running Syncthing: https://docs.syncthing.net/users/security.html#information-leakage

**Comment by cheribral** [comment]
I agree, a tool designed to continuously keep your devices in sync will need to connect to "the network" (implying words like "my" and "local").  You personally might not differentiate much between "my network" and "the internet", but there are a large number of people who do.  Indeed there are a large number of people for whom the distinction is critical.

This feature request would be an enhancement in that it be more respectful of my context.  You already ask about sending usage reports before sending them.  I do not see why having something similar before using untrusted servers for relays or presence detection.  All it would take is a message like "We would like to make connections to one of our servers which may possibly live outside your country to help find all your other devices, is this acceptable?"  Something similar could be done for the relays.  I don't see how ease of use has anything to do with it.  You already have to click through the interface to set up shares initially anyway.  A yes/no prompt is not hard to use.  

While I originally tagged this as a feature request thinking it was a small and reasonable change, I personally would say making connections to untrusted servers without asking is irresponsible and borders on being a serious bug in situations where it matters.

You aren't me, it's entirely your prerogative to dismiss this as a non issue.  We all get to decide how we affect and shape the world we live in.  For my part, I think it would be a shame for useful FOSS software not to consider this, and would still like to ask that this be opt-in at setup time.

**Comment by AudriusButkevicius** [comment]
I don't think we'll be able to cater for everyone.

Usually asking a question implies you have to legally ask it, otherwise you'd be in trouble, hence people assume that to be something bad you are asking for, and react to pressing "no", without even understanding what it is.  There was actually even some research done on the cookie banners that proved this, hence why companies started making hard to press no.

Asking the question you suggested will definately cause a lot of people to press "no", and end up with a non-working syncthing instance, simply because people don't understand how syncthing or the internet works, and what connecting to other servers even means. 

Hence "works by default" is the correct stance here.

People who are super concerned with privacy should always be prepared to "go the extra mile", because nothing on the internet caters for their needs. Syncthing is no different.
