### ISSUE TITLE
Syncthing does not optimize local copies

### ISSUE THREAD

**Issue by intelfx** [syncthing/syncthing#7801]
### Version/environment information

- OS: Arch Linux (Linux 5.12.13)
- Syncthing version: `syncthing v1.17.0 "Fermium Flea" (go1.16.4 linux-amd64) builduser@archlinux 2021-06-05 10:59:32 UTC [noupgrade]` 
  (installed from operating system package repositories)
- Filesystem used: btrfs

### Problem description

When syncthing performs a local copy ("Copied from elsewhere" in tht Web UI), reflink copy is not attempted (as one would expect from #4271 and #6746).

Specifically, when two devices are in sync and a large file is copied on one side (it does not matter whether the originating copy is reflink or not), data usage on the other side increases.

Also, no `ioctl(FICLONERANGE)` nor `copy_file_range()` system calls are made by Syncthing on the receiving side.

### Steps to reproduce the problem:

- set up two Linux machines with syncthing and a reflink-capable filesystem (e. g. btrfs)
- create some large files inside of a synced folder, wait for full sync
- check disk usage on both machines:
```
~/devel/ext/linux/.git/objects intelfx@stratofortress
$ compsize pack                
Processed 2 files, 2429 regular extents (2429 refs), 0 inline.
Type       Perc     Disk Usage   Uncompressed Referenced
TOTAL       95%      1.9G         2.0G         2.0G
none       100%      1.8G         1.8G         1.8G
zstd        40%       63M         158M         158M
```

```
~/devel/ext/linux/.git/objects intelfx@able
$ compsize pack
Processed 2 files, 7538 regular extents (7538 refs), 0 inline.
Type       Perc     Disk Usage   Uncompressed Referenced
TOTAL       94%      1.9G         2.0G         2.0G
none       100%      1.8G         1.8G         1.8G
zstd        40%       72M         176M         176M
```
- copy the large file on one side, wait for full sync:
```
~/devel/ext/linux/.git/objects intelfx@stratofortress
$ cp -a --reflink pack pack.old
```
- check disk usage again:
```
~/devel/ext/linux/.git/objects intelfx@stratofortress
$ compsize pack pack.old
Processed 4 files, 2429 regular extents (4858 refs), 0 inline.
Type       Perc     Disk Usage   Uncompressed Referenced
TOTAL       95%      1.9G         2.0G         4.0G
none       100%      1.8G         1.8G         3.7G
zstd        40%       63M         158M         317M
```

```
~/devel/ext/linux/.git/objects intelfx@able
$ compsize pack pack.old
Processed 4 files, 10447 regular extents (10447 refs), 0 inline.
Type       Perc     Disk Usage   Uncompressed Referenced  
TOTAL       95%      3.8G         4.0G         4.0G       
none       100%      3.7G         3.7G         3.7G       
zstd        40%      135M         336M         336M       
```

Note that the total disk usage on the receiving side increased two-fold, whereas it did not change on the receiving side (because a reflink copy was explicitly requested).

Additionally, it is possible to `strace` the receiving Syncthing and ascertain that no `ioctl` or `copy_file_range` system calls are made at all.

**Comment by AudriusButkevicius** [comment]
Please check the docs, specifically, the defaults: https://docs.syncthing.net/advanced/folder-copyrangemethod.html

**Comment by intelfx** [comment]
Ugh. Apologies, I was somehow under impression this was the default.

That said, why not make it the default?

**Comment by AudriusButkevicius** [comment]
Because things like this: https://bugzilla.redhat.com/show_bug.cgi?id=1803162

**Comment by intelfx** [comment]
I see. Is there any plan for making this the default in the future?

Major DEs (GNOME, KDE) and TUI programs like `mc` already do this transparently; even GNU coreutils `cp` decided to default to using reflinks back in 2020 in https://github.com/coreutils/coreutils/commit/25725f9d41735d176d73a757430739fb71c7d043 (although this commit is not yet part of any release).

**Comment by AudriusButkevicius** [comment]
I am not sure it matters. 
For people who care/know about this, they will can ask the question, be pointed at the configuration option and use it.

For the rest, which I suspect is probably >95% of user base, they most likely don't use a file system that would benefit from this in anyway in terms of data reuse, and copy speed/syscall overhead is not the bottleneck/concern anyway, as we still need the data in user space, to verify that it matches the hash.

Go itself uses copy_file_range since 1.15 (https://github.com/golang/go/issues/36817), but we don't implement the standard copy in the right way for us to go through the happy path.

There is a TODO suggesting this should be addressed: https://github.com/syncthing/syncthing/blob/main/lib/fs/filesystem_copy_range_standard.go#L22
