### ISSUE TITLE
Add scheduled time instead of random intervals 

### ISSUE THREAD

**Issue by Nbr1Sniper** [syncthing/syncthing#7802]
Hi,
I would like to have the ability to schedule the interval to happen at a certain time rather than based on seconds. This will normalize my backups and insure my system isn’t doing scans every time my device is off or out of the house (IE: if every 24 hours if it happens to fall at the same time my system is offline then it will never scan). This will also change constantly every time syncthing starts.
THANKS!!!

**Comment by AudriusButkevicius** [comment]
In most of the time you don't need to scan things at all, as we use file system notifications to be notified about changes, so the scans happen immediately.

I think anything other than that should be discussed on the forum, and might require automation from your side.

**Comment by Nbr1Sniper** [comment]
> Most of the time you don't need to scan things at all, as we use file system notifications to be notified about changes, so the scans happen immediately.
> 
> I think anything other than that should be discussed on the forum, and might require automation from your side.

Thanks! I assumed that the scan is what makes the system actually check for changes. I must be mistaken. (I do have check for updates checked)
