### ISSUE TITLE
syncthing says "up to date" but two clients without changes (kdbx)

### ISSUE THREAD

**Issue by leder11011** [syncthing/syncthing#7803]
Hello all,

please help me out here troubleshooting this issue.

I have one Windows PC on which I made the change in keepass2 kdbx entry and:
- one Linux PC that does not receive the change, though "up to date"
- one Android smartphone that does not receive the change, though "up to date", too

This is not the intended behaviour, right?!

Thanx all!

Best regards
Gerrit

P. S. the intended behaviour is keeping all keepass2 passwords in sync on those three machines!

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
