### ISSUE TITLE
"public key is not available" error

### ISSUE THREAD

**Issue by gatocinza** [syncthing/syncthing#7804]
Hello. I was trying to install Syncthing v1.17.0 in Bodhi 6.0.0 (focal) using the instructions given in the webpage for Ubuntu packages, but found this error when input `sudo apt-get update`:

```
W: GPG error: https://apt.syncthing.net syncthing InRelease: The following signatures couldn't
be verified because the public key is not available: NO_PUBKEY D26E6ED000654A3E
E: The repository 'https://apt.syncthing.net syncthing InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

I tried to install using the URLs with `http` instead of `https`, but didn't work neither.

Hope to get some help. Have a good day.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by dingzhw** [comment]
I manually download the `release-key.gpg` from [syncthing-apt](https://apt.syncthing.net/release-key.gpg) and move it to `/usr/share/keyrings` whith the name : `syncthing-archive-keyring.gpg` and it did wotk.
