### ISSUE TITLE
Support for wrapping the Sync port/protocol over HTTP protocol

### ISSUE THREAD

**Issue by adyanth** [syncthing/syncthing#7806]
Requesting to add support for wrapping the sync port/protocol over HTTP, maybe use websockets too.

Having a separate TCP/UDP port adds the complexity of having UPnP or port forwarding and has major disadvantages of having a public IP (not behind a CGNAT, or worse, double NAT) and poking holes in the firewall.

A major advantage of having the sync port over HTTP is that you can chuck it behind a reverse proxy without any issues. This is not just helpful for a local one, but something like [Argo Tunnel](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps) which uses reverse proxies on Cloudflare's network which makes it possible to host without even opening a single port.

If this is indeed provided, this can be made configurable to enter the IP/FQDN for the sync, so that it can work entirely locally, without needing a relay or a discovery server.

Combining UI and sync on the same port might be bad as discussed in many places, for reasons of security where you might not need the UI exposed to the internet. So, a separate port, like 22000 that can handle HTTP and work with HTTP reverse proxies like Traefik HTTP router (not TCP).

This would help many since many ISPs are moving to CGNAT making UPnP/port forwarding less useful. 

The only other workaround I can think of is to implement some kind of NAT-T strategy to keep the port open using the existing discovery/relay nodes, but again that would not work in every case (such as hairpinned NAT or hard/double NAT).

**Comment by AudriusButkevicius** [comment]
I don't think we'll be doing this.

We already have relays to work around situations where a direct connection is not possible.

Http does not lend itself well to something to asynchronous protocol like BEP, that has no HOL blocking.

**Comment by adyanth** [comment]
The main issue I find with relays are that they have bandwidth limitations, and owned by someone. Self hosting that hits the same problem as stated before.

Regarding tunneling software, yes, Tailscale is the one I use which does achieve that (for others who might end up looking at this issue). 

Still, not as seamless as not having to do that. But I get that implementing it might be a huge fall down the rabbit hole which you might not be looking at going on, at this point.

Thanks!

**Comment by AudriusButkevicius** [comment]
I bet that 90% of environments where you'd fallback to using an HTTP proxy as the only means of connecting would be running some version of squid from 1980's with no websocket support, not even talking about QUIC.

You can always run your own personal relay if the public ones are not sufficient, but I highly doubt that whatever hackery we come up with proxying stuff over HTTP would be any more performant than relays.


Effectively, this is so niche that I don't think it's worth it, and I'd rather we spent time on connection bonding rather than this.
