### ISSUE TITLE
@eaDir - Unexpected items

### ISSUE THREAD

**Issue by mikulik86** [syncthing/syncthing#7807]
Synology NAS is creating directories called **@eaDir**, which as far as I know can not be prevented. When used as a Untrusted device, Ignore Patterns can not be set and as a result Syncthing (v1.17.0) is complaining about Unexpected items.

Is there a way around it, or is it a bug?

**Comment by AudriusButkevicius** [comment]
I disagree this being a bug on syncthing side.
If anything, the bug is with synology for not being able to stop the creation of those directories.

**Comment by calmh** [comment]
I would suggest ignoring the unexpected items warning, or storing the folder in a subdirectory that doesn't have the eaDir.

**Comment by AudriusButkevicius** [comment]
Or check https://community.synology.com/enu/forum/17/post/9058?page=2&sort=oldest

**Comment by mikulik86** [comment]
> Or check https://community.synology.com/enu/forum/17/post/9058?page=2&sort=oldest

Already tried. Did not help. I spent a lot of time searching for a reliable way to prevent this. Did not find any.

**Comment by AudriusButkevicius** [comment]
```
First delete all @eaDir entries on for example the first mounted harddisc (/volume1)... don't worry about the "warnings/errors":
find /volume1 -name "@eaDir" -exec rm -rf {} \;
Stop the thumb service from creating @eaDir entries:
/usr/syno/bin/synomkthumb -stop
And remove the service from starting up again when rebooting:
rm /usr/syno/etc.defaults/rc.d/S77synomkthumbd.sh
Tested it on my bootstrapped DS211j.
```
seems promising.

**Comment by calmh** [comment]
I don't see something here to fix. Syncthing will warn about an unexpected item, because there is one, but that warning isn't critical.

**Comment by mikulik86** [comment]
Why can't be just Syncthing made to ignore those folders?
The way I see it, Syncthing was created to run on certain platforms, one of which is DSM. Normal operation of DSM includes creation of those folders. Syncthing shouldn't view it as something abnormal, because presence of the @eaDir in DSM Shares is to be expected.

Moreover if I'll just ignore the warning, then I'll not know, if there are some really unexpected items. Which kind of defeats the purpose of this functionality. And I'm sure everybody would agree, that opening the warning every day just to check what items are there is just stupid.

**Comment by AudriusButkevicius** [comment]
Syncthing was not created to run on some one specific platform.

It can run on thousands of different devices, platforms, operating systems.
We are not going to start adding workarounds/caveats around each and every one of them out there.

The offender here is your platform, creating directories where it should not, so best if you take this to Synology.

**Comment by tomasz1986** [comment]
Just a side note, but maybe it would just be better to just allow ignore patterns even in Receive Encrypted folders to have a workaround for these kind of issues?

I'm saying this, because I was the one, who proposed disabling them completely (see https://github.com/syncthing/syncthing/issues/7469). However, I didn't really consider this kind of automatic folder creation by the OS. Windows does it too (e.g. `desktop.ini` and `thumbs.db`), but only in special kinds of folders, and not everywhere, so it isn't really a problem there.

Will something actually break if ignore patterns are applied to a Receive Encrypted folder?
