### ISSUE TITLE
~ remains pointing to /var/lib/syncthing even if a different default folder is configured

### ISSUE THREAD

**Issue by Jesus-M** [syncthing/syncthing#7812]
### Does your log mention database corruption?

No

### Include required information

When ones configure a non-standard default folder, one would assume the new path would be used everywhere, but when adding a new folder, and using the wildcard ~, it remains being replaced by the standard default folder /var/lib/syncthing

Tested and reproduced in:
```
syncthing v1.18.0 "Fermium Flea" (go1.16.5 linux-amd64) teamcity@build.syncthing.net 2021-06-21 20:53:50 UTC
syncthing v1.18.0 "Fermium Flea" (go1.16.5 linux-arm) teamcity@build.syncthing.net 2021-06-21 20:53:50 UTC
```

**Comment by imsodin** [comment]
That's working as intended: `~` is your home path (on linux as in `$HOME`), not the default path. What changing the default path does, is changing what is already pre-filled in the folder path when you add a new folder.
