### ISSUE TITLE
Allow for auto-child addition to cluster

### ISSUE THREAD

**Issue by Mitch0S** [syncthing/syncthing#7813]
Hello,

I have a Syncthing cluster that consists of one Parent node, and ~10 child nodes.

It's quite an annoying task to manually go into the config file of the new child, change the GUI address to 0.0.0.0, and have to enter the new parent token into the GUI of the new child node to enter it into the cluster.

Is there any command that I can enter to automatically enter the new child into the cluster, so I only have to accept the new child from the Parent GUI?

Cheers,

Mitch, Ausguard.net

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
