### ISSUE TITLE
syncthing-windows-amd64-v1.18.0.zip download failed

### ISSUE THREAD

**Issue by CalebSpencer** [syncthing/syncthing#7815]
I can't download syncthing-windows-amd64-v1.18.0.zip.
I've tried with multiple browsers. I can download syncthing-windows-amd64-v1.17.0.zip and other 1.18 files.
Perhaps the .zip is corrupt?

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
