### ISSUE TITLE
"Override Changes" took a wrong turn

### ISSUE THREAD

**Issue by InQuize** [syncthing/syncthing#7818]
Hello,

I encountered some strange behavior. 
Got only 2 devices (NAS and PC) that share folder at question. Here are my recent actions with affected share: 
- some time ago added "desktop.ini" to "Ignore files" via GUI on PC;
- later I noticed alarmingly frequent scanning activity on that PC;
- checked both nodes for errors:
sure enough one of them (NAS ?) was out of sync with:
```
directory has been deleted on a remote device but is not empty; the contents are probably ignored on that remote device, but not locally
```
- quick search reveals pitfalls around `(?d)` prefix and the fact that ignore rules were not the same for nodes, added after years of sync, whatever caused this minor issue;
- played a bit with `(?d)` after the fact manually scanning folders on each side, did not manage error to go away;
- deleted Ignore patterns from both nodes, no change;
- decided to cleanse NAS copy with override by switching nodes to Send / Receive only modes;
- override fixed Out-of-Sync state on both, but stats (size, file/dir count) do not add up:

PC (Syncthing v1.18.0, Windows 10 64bit 19043.1083)
![PC](https://user-images.githubusercontent.com/12504278/125317028-58600800-e341-11eb-8974-e3c5f047707a.jpg)

NAS (Syncthing v1.18.0, FreeBSD 64bit 12.2-RELEASE-p8 jail, TrueNAS-12.0-U4)
![NAS](https://user-images.githubusercontent.com/12504278/125318142-42067c00-e342-11eb-9508-8ac8cf3ab4b8.jpg)

NAS actual fs from jail
![NAS-FS](https://user-images.githubusercontent.com/12504278/125318234-58143c80-e342-11eb-8a52-e1670a1d7eb5.jpg)

How is this possible? Is this a bug, corruption or my misuse that I am failing to notice?

I took a peak in logs, but I believe they are lost since I did restart both nodes a couple of times in the process and there was no dedicated log location option in startscript on NAS.

Folders seem to to sync at least new files. But feels like bad things are going on with NAS copy. I was unable to save GUI options for any folder. Had to use advanced settings to bring folder back to `sendreceive` mode. Though, after jail restart it went away, save button is usable again.

Should I delete NAS copy from Syncthing and filesystem manually and sync from PC?

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by InQuize** [comment]
Wow that was fast..
I do not need support, as I am capable of remedying the symptom on my own.
The choices were:
- either to provide as much info as possible because I did my research, apart from #2567 found no similar.
- or destroy the share that has such abnormal behavior before knowing how to reproduce it in a process of restoring the share operability as I require it in everyday use and need to fix fast.
I resorted to filing a report because issue seems complex enough to contact devs directly. Forgive me my misbelieve that friendly people from forum could provide more than speculation in this case.
I was more interested in pointers from you guys to when I should expect Syncthing to silently not recognize out-of-date state like that.

**Comment by tomasz1986** [comment]
> Edit: update your rules for bug section if you have no interest in unclear reports.
> It would have spared me more time to gather all the info that you spent on reading it for sure.

The reason for redirecting to the forum is that with the developers cannot really do anything with your report without further information, i.e. right now there are no steps to reproduce the problem and/or no logfiles that could give specific information on what has gone wrong. If I were you, I would just copy and paste the same content into a new forum post and continue the discussion there.

**Comment by AudriusButkevicius** [comment]
As Tomasz said, the problem with this report is that it's most likely just "things are in a bad state".
It doesn't explain how to get there for us to understand what needs fixing.

What's even worse is that there isn't even much actionable here. Namely, I don't think we can even recover any information that would explain how to get to this state, and other than the usual "run this API call, run that API call" on the forum, we'll end up recommending to just run `--reset-deltas` to perform a full index retransfer to plaster over this.

I do think we want bugs on the issue tracker, but ideally ones that are actionable.

As someone who has seen quite a few reports over the years, I usually have a sense of what is actually actionable, and what is just "things got weird, we don't know why, could be some bug in an earlier version", which will end up being a issue that we potentially will never close, as we're not even sure what the cause is, and sadly this is one of those.
