### ISSUE TITLE
Can not sync data with a raid1 NAS 

### ISSUE THREAD

**Issue by ltkun** [syncthing/syncthing#7822]
- which version of Syncthing and what operating system you are using
 v1.18.0, Linux (64-bit Intel/AMD)
 - what happened,
 I have about 200G+ photos  in a synology Moments. And I want to sync the data to a new NAS Hikvision Mage20 with two 4t  raid1 disks. After 4 days waiting the data is transfer to the new home. but I got noting but a lot of tmp file like this. 

>-rwxrw-rwx   1 postfix root 289908 Jul 15 00:17 .syncthing.IMG_20190909_114809.jpg.tmp
-rwxrw-rwx   1 postfix root 186044 Jul 15 14:45 .syncthing.IMG_20190909_115045.jpg.tmp
-rwxrw-rwx   1 postfix root 102832 Jul 15 08:09 .syncthing.IMG_20190909_144126.jpg.tmp
-rwxrw-rwx   1 postfix root  98493 Jul 15 07:14 .syncthing.IMG_20190909_144304.jpg.tmp

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
