### ISSUE TITLE
My brain is buggy because of this too much perfect software.

### ISSUE THREAD

**Issue by badrow** [syncthing/syncthing#7823]
Hello, I would like to say a huge thank you for syncthing. I don't know how many people originated and maintain this program, but it is so excellent in every way that my brain gets confused.

I have never seen a program so robust, fexible, elegant, compatible (I even managed to run it on an e-ink reader) and powerful, so stable powerful!!! It solved many problems I encountered when I had to synchronize astronomical amounts of data with small files, it got by where all cloud systems crash or are very slow. 

It runs on ONE BINARY which means that dependencies are minimal and it can run ABSOLUTELY ANYTHING. And all this OPEN SOURCE !
I'm so not used to seeing such high quality software that I can't get over it sorry!

So excuse me for posting this message in this section but I have to say it and I want to thank all the contributors for producing such quality software.

**Comment by AudriusButkevicius** [comment]
Thanks for the kind words, but please use the forum for content of this type. We try to keep the issue tracker exclusively for issues.
