### ISSUE TITLE
Bump quic-go for RFC9000 support

### ISSUE THREAD

**Issue by bt90** [syncthing/syncthing#7824]
quic-go v0.21.0 added support for the RFC 9000 version of the protocol. Not a big deal on its own but they already removed support for the draft protocol versions in master.

We should update to a release which offers RFC+draft support so we can update the library in future syncthing releases without breaking stuff. This way we can gradually phase out draft protocol usage.

**Comment by yan12125** [comment]
There is apparently an API change from quic-go 0.19.3 to 0.21.1. A possible patch is mentioned at https://github.com/syncthing/syncthing/pull/7779#issuecomment-865224492

**Comment by AudriusButkevicius** [comment]
There are other caveats, they moved to batch reads, our stun wrapping code does not support that, so I am not sure what would happen if we were to just try and use it.

**Comment by bt90** [comment]
IMHO, it's worth to look into batch support just for the better QUIC performance.

**Comment by bt90** [comment]
I've opened https://github.com/AudriusButkevicius/pfilter/issues/5 and added a small bounty. Feel free to chip in 😉

**Comment by bt90** [comment]
Fixed by #7862
