### ISSUE TITLE
The error message "given name ... differs from filesystem name ..." does not help users to resolve the issue

### ISSUE THREAD

**Issue by mlell** [syncthing/syncthing#7827]
I am running Syncthing on Android (1.18.0) and on Arch Linux (1.17.1) to sync my smartphone's storage to my notebook. On my smartphone, I get a lot of messages like

```
2021-07-18 10:27:29 Puller (folder "Speicher" (t66yq-r9o4p), item "Music/Einzel/The King's Singers/This Is The King's Singers"): syncing: checking file to be replaced: given name "Music/Einzel/The King's Singers/This Is The King's Singers" differs from name in filesystem "Music/Einzel/The King's Singers/This Is the King's Singers"
```

I don't know what to do with this information. What is the "given name"? How can a file have a different name than its file system name? Can this error message be reformulated to something that tells me as a user how to resolve this?

**Comment by tomasz1986** [comment]
The error message should probably be improved, but this error itself is supposed to show up when there is a case conflicts between the two files (e.g. `document.txt` vs `Document.txt`). However, in your case the name appears to be exactly the same of both sides, so it is unclear what the actual culprit is.

**Comment by calmh** [comment]
(There's a `the` vs `The` in there, but yes.)

**Comment by tomasz1986** [comment]
> (There's a `the` vs `The` in there, but yes.)

Ah, yes 😳. I got confused due to the (almost) same path being listed in the error message three times. I would personally add something to the message stating explicitly that there is a case difference between the two items.

**Comment by tomasz1986** [comment]
> so the "given name" is the name of the file on the remote device and the "file system name" is the local name? And it is an error because syncthing cannot decide which one should be applied? So this error message appears only when setting up sync for two folders that both have already some content? (Because else it would be clear which name has priority, that which has been changed after the last sync).

Yes in all cases 👍. You may want to check the unresolved https://github.com/syncthing/syncthing/issues/6989.
