### ISSUE TITLE
maxFolderConcurrency value not respected when more folders are already being scanned

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7830]
1. Add a few folders to Syncthing with some large files (so that it takes some time to scan them).
2. Pause all folders before the files have been hashed.
3. Set `maxFolderConcurrency` to `2`.
4. Unpause all folders, so that Syncthing starts scanning them.
5. Change `maxFolderConcurrency` to `1`.
6. Syncthing will keep scanning 2 folders at a time instead of just 1. It will start scanning a new folder once the previous has finished, even if yet another folder is still being scanned too.

Tested with Syncthing v1.18.0.

**Comment by calmh** [comment]
I can't reproduce this, it  does the right thing for me. 

(There's a corner case though, which isn't the one you describe, where if you already have three folders scanning and reduce concurrency to one, it will still allow three folders scanning until everyone is done. Including allowing a new folder to start whenever another one is done.)

**Comment by tomasz1986** [comment]
> (There's a corner case though, which isn't the one you describe, where if you already have three folders scanning and reduce concurrency to one, it will still allow three folders scanning until everyone is done. Including allowing a new folder to start whenever another one is done.)

You are right. It was my mistake :sweat:. I have experienced this in my real setup, and was quite sure that that was the case, but now I cannot reproduce using the steps described above.

The corner case is real indeed, even with just concurrency set to 2 initially, and then changed to 1. If the scanning was already going on when changing the value, Syncthing will then keep scanning 2 folders at a time, including new ones. I have changed the issue to be about the corner case instead.

**Comment by AudriusButkevicius** [comment]
I am not sure it is a corner case, given things were valid at the start of the operation, so the fact you changed the settings doesn't invalidate what was valid before?

**Comment by tomasz1986** [comment]
> I am not sure it is a corner case, given things were valid at the start of the operation, so the fact you changed the settings doesn't invalidate what was valid before?

I would agree when it comes the folders that are already being scanned (as otherwise they would probably have to forcibly paused and resumed to go into the "Waiting for Scan" state), but the fact that Syncthing keeps moving on to the other ones following the old concurrency value (that at the moment of changing the value are still in "Waiting for Scan") is unexpected. From a typical user perspective, it feels as if the setting hasn't been applied.

**Comment by calmh** [comment]
Yeah... This is tricky to fix. The change does take effect immediately, in both directions -- you can see this when raising it. The thing is, let's say we reduce the limit to one when there are already two folders scanning, several waiting. The limiter (bucket) gets size one, one folder completes scanning and returns a token to the bucket, the bucket now has one token so another folder gets that token and starts scanning. Then the other folder completes scanning, same thing happens, still two folders scanning.

To get precisely correct behavior: pause all, change limit, resume all.

I think this is just one of those things that we're not going to fix.

**Comment by acolomb** [comment]
Not having looked at the code, couldn't the bucket just keep a count of handed out tokens and refuse to re-issue a returned one if the number exceeds the configured concurrency? Just drop that token instead, keeping the counter value the same. That would approach the configured limit naturally after any previously concurrent tasks are done.

**Comment by calmh** [comment]
Maybe! Try it!
