### ISSUE TITLE
Limitation of GUI Authentication attempt times

### ISSUE THREAD

**Issue by TigerCubDen** [syncthing/syncthing#7831]
There are someone like me have own server running Syncthing for 24 hours. It brings convenience but also brings some potential security issues. The limitless attempt based on dictionary is.

It's better to provide a secure feature that automatically bans these clients for a period of time while the consecutive failure of verification reaching a certain number of times.

You can take some software like _qbittorrent_ for reference.

![Snipaste_2021-07-19_22-59-37](https://user-images.githubusercontent.com/55782476/126190952-01d3ce8b-68ba-4cb2-8bd8-caf019aa0cf2.png)

**Comment by AudriusButkevicius** [comment]
If you are exposing syncthing to the internet, you should front it with a proper reverse proxy, which I would hope has functionality you are talking about.

Alternatively, you can probably write your own fail2ban plugin for syncthing running off of audit logs/events api, but I don't think it's worth for us to build functionality like that into syncthing, as it's not written with exposing its http server to the internet in mind.
