### ISSUE TITLE
Repetition in strings in new folder id screen

### ISSUE THREAD

**Issue by StoyanDimitrov** [syncthing/syncthing#7834]
The repeated concept is that the folder id must be the same between all devices. Have a look at the screenshots

![folder-id-default](https://user-images.githubusercontent.com/10962709/126307782-9bb055de-14d2-4101-8071-66c577820962.png)
![folder-id-error](https://user-images.githubusercontent.com/10962709/126306981-5d0bbde2-220f-4661-aadb-096d7753a52b.png)

In both screenshots the string `When adding a new folder, keep in mind that the Folder ID is used to tie folders together between devices. They are case sensitive and must match exactly between all devices.` is repeated. It makes sense in the second but in the first it causes the said duplication.

**Comment by tomasz1986** [comment]
Yeah, there is some repetition in there. I would say that the whole string could probably be reworded and shortened a little bit. However, doing so would require to fix all the translations. Is this really necessary? I personally think that not really, but others may have different opinions.

**Comment by imsodin** [comment]
I agree that this help block with the various strings triggered on different conditions could likely be improved. As such I am open to contributions to improve it. I do also think the current state is adequate and thus don't see a need for a bug (we don't want to have a bug for every minor detail that might be improved in the web UI, there's a lot of that).
