### ISSUE TITLE
Wrong abbreviation of minute

### ISSUE THREAD

**Issue by StoyanDimitrov** [syncthing/syncthing#7837]
Minutes normally are abbreviated as `min`. Instead, `m` is used in several places. The abbreviation `m` means [`meter`](https://www.nist.gov/pml/weights-and-measures/si-units-length)!

> `Disabled periodic scanning and failed setting up watching for changes, retrying every 1m:`
> `Periodic scanning at given interval and failed setting up watching for changes, retrying every 1m:`

**Comment by tomasz1986** [comment]
Not an expert, and from a brief Google search, it does seem that "min" for  is technically the correct abbreviation of "minute", while "m" is non-standard (but still very common). Same as with https://github.com/syncthing/syncthing/issues/7834 though, changing the string will result in having to redo all the translations.

**Comment by calmh** [comment]
I agree, this is unfortunate and would be better expressed as `1 minute` with proper spacing and no need to be extremely terse. However it is what it is at this point, if we change these messages in some other fashion in the future we should fix it then.
