### ISSUE TITLE
Repetition of meanings

### ISSUE THREAD

**Issue by StoyanDimitrov** [syncthing/syncthing#7838]
Unless there is a subtle difference which I don't perceive, the words `periodic` and `interval` in the sentences below have the same meanings. As a side effect this lowers the score of the useful translation memory matches in Transifex.

>Periodic scanning at given interval and disabled watching for changes
Periodic scanning at given interval and enabled watching for changes
Periodic scanning at given interval and failed setting up watching for changes, retrying every 1m:

**Comment by tomasz1986** [comment]
What is exactly the problem with these strings? They do sound fine and make sense (at least to me 😉). Could give an example of how you would suggest to modify them?

**Comment by imsodin** [comment]
These messages are not meant to be as terse as possible, but to be as understandable as possible. Conveying the same info (regular scanning) with two different formulations helps the latter.
