### ISSUE TITLE
Manually configured addresses causes invalid and unexpected DNS queries

### ISSUE THREAD

**Issue by da2x** [syncthing/syncthing#7844]
Steps to reproduce:

1. Ensure you can log DNS requests from your system. E.g. using WireShark or using your favorite tool.
2. Edit a device connection in Syncthing. Go to Advanced: Addresses, and add a manual hostname lookup for it. E.g. `tcp4//example-computer.home.arpa:22000`. It doesn’t need to be an actual working address nor device.
3. Review your DNS logs.

Expected:
* One DNS `A` record lookup for the hostname `example-computer.home-arpa`.

Actual:

* One DNS `A` lookup for the hostname `example-computer.home.arpa`. (This the only expected lookup.)
* One DNS `AAAA` lookup for the hostname `example-computer.home.arpa`.
* One DNS `A` lookup for the invalid hostname `example-computer.home.arpa:22000`.
* One DNS `AAAA` lookup for the invalid hostname `example-computer.home.arpa:22000`.
* One DNS `A` lookup for the hostname `example-computer.home.arpa.localdomainname`.
* One DNS `AAAA` lookup for the hostname `example-computer.home.arpa.localdomainname`.
* One DNS `A` lookup for the invalid hostname `example-computer.home.arpa:22000.localdomainname`.
* One DNS `AAAA` lookup for the invalid hostname `example-computer.home.arpa:22000.localdomainname`.

Port numbers don’t belong in DNS queries.

Where `localdomainname` is your DHCP search domain name. The domain specified is a fully-qualified domain name, so it’s unexpected that Syncthing would combine it with the local domain name. Changing the domain name to `example-computer.home-arpa.` (with a trailing dot making it a DNS-root bound domain) still appends the search domain name. This is completely unexpected. Setting your DHCP search domain to `home.arpa.` will even duplicate the domain in queries like `example-computer.home.arpa.home.arpa`.

Tested with Syncthing v1.18.0 on Android, macOS, and Linux.

**Comment by AudriusButkevicius** [comment]
So the ones with the port, I agree, look wrong.
Others look right to me.

**Comment by da2x** [comment]
> Others look right to me

The search domain is only supposed to be used when the query domain is relative; e.g. it doesn't contain any dots. The stub resolvers in Windows and Linux assumes a query to be absolute when it contains one or more dots ([man resolv.conf](https://man7.org/linux/man-pages/man5/resolv.conf.5.html)). Any domain ending with a dot is definetly root-bound/absolute.

The example hostname `example-computer.home.arpa.` contains one or more dots, uses a know TLD, and ends with a dot. These are three reasons not to append the search domain, yet Syncthing does it anyway.

> Edit: actually the AAAA ones we could argue about, but I suspect that DNS resolution happens before stack selection.

I also assumed DNS resolution happen too early, but then again, Syncthing does have an address format where users can express a preference for IPv4 or IPv6. Choosing one over the other means it's only expected to resolve one of them.

**Comment by AudriusButkevicius** [comment]
I don't think, in practice, a domain having a dot avoids using a search paths.

Atleast that is not how it works in reality from my experience, namely you can use service.namespace instead of service.namespace.cluster.local in k8s and I've used service.prod without .company.internal in a commercial setting.

If its suffixed with a dot, then yes, I'd expect not to use search paths, but the reality is that we just use go standard library, so we don't have as much control as you imagine.

**Comment by calmh** [comment]
I tried to reproduce this, but I cannot. I configured a test device:

<img width="606" alt="Screenshot 2023-03-10 at 07 53 17" src="https://user-images.githubusercontent.com/125426/224244760-b58d4a49-7def-4d4f-b058-b5371891289b.png">

and tcpdumped DNS requests from syncthing. I see a fair amount of lookups, but none of them invalid.

```
    127.0.0.1.58657 > 127.0.0.53.53: [bad udp cksum 0xfe86 -> 0x8150!] 40054+ [1au] A? example-computer.home.arpa. ar: . OPT UDPsize=1232 (55)
    127.0.0.1.38110 > 127.0.0.53.53: [bad udp cksum 0xfe86 -> 0xa123!] 52427+ [1au] AAAA? example-computer.home.arpa. ar: . OPT UDPsize=1232 (55)
    127.0.0.1.42938 > 127.0.0.53.53: [bad udp cksum 0xfe92 -> 0x5d2d!] 26651+ [1au] AAAA? example-computer.home.arpa.kastelo.net. ar: . OPT UDPsize=1232 (67)
    127.0.0.1.44839 > 127.0.0.53.53: [bad udp cksum 0xfe92 -> 0x7fc0!] 15926+ [1au] A? example-computer.home.arpa.kastelo.net. ar: . OPT UDPsize=1232 (67)
    127.0.0.1.41132 > 127.0.0.53.53: [bad udp cksum 0xfe8d -> 0xf9c5!] 61585+ [1au] AAAA? example-computer.home.arpa.nym.se. ar: . OPT UDPsize=1232 (62)
    127.0.0.1.45160 > 127.0.0.53.53: [bad udp cksum 0xfe8d -> 0x415f!] 46140+ [1au] A? example-computer.home.arpa.nym.se. ar: . OPT UDPsize=1232 (62)
    127.0.0.1.37707 > 127.0.0.53.53: [bad udp cksum 0xfe86 -> 0x375e!] 14399+ [1au] A? example-computer.home.arpa. ar: . OPT UDPsize=1232 (55)
    127.0.0.1.59451 > 127.0.0.53.53: [bad udp cksum 0xfe92 -> 0x267d!] 24165+ [1au] A? example-computer.home.arpa.kastelo.net. ar: . OPT UDPsize=1232 (67)
    127.0.0.1.42249 > 127.0.0.53.53: [bad udp cksum 0xfe8d -> 0x5890!] 43114+ [1au] A? example-computer.home.arpa.nym.se. ar: . OPT UDPsize=1232 (62)
    127.0.0.1.54803 > 127.0.0.53.53: [bad udp cksum 0xfe86 -> 0xa3f7!] 35037+ [1au] A? example-computer.home.arpa. ar: . OPT UDPsize=1232 (55)
    127.0.0.1.54615 > 127.0.0.53.53: [bad udp cksum 0xfe92 -> 0x84cb!] 4859+ [1au] A? example-computer.home.arpa.kastelo.net. ar: . OPT UDPsize=1232 (67)
    127.0.0.1.58464 > 127.0.0.53.53: [bad udp cksum 0xfe8d -> 0x2820!] 39299+ [1au] A? example-computer.home.arpa.nym.se. ar: . OPT UDPsize=1232 (62)
    127.0.0.1.54444 > 127.0.0.53.53: [bad udp cksum 0xfe86 -> 0xd422!] 23038+ [1au] AAAA? example-computer.home.arpa. ar: . OPT UDPsize=1232 (55)
```
