### ISSUE TITLE
gui: Superfluous quotes

### ISSUE THREAD

**Issue by StoyanDimitrov** [syncthing/syncthing#7853]
Take a look at the end those two lines

https://github.com/syncthing/syncthing/blob/67b18569cfeb8f4f4fcd1417c9b81b3c983429ed/gui/default/syncthing/settings/settingsModalView.html#L81

https://github.com/syncthing/syncthing/blob/67b18569cfeb8f4f4fcd1417c9b81b3c983429ed/gui/default/syncthing/settings/settingsModalView.html#L97

There are double quotes but one is enough.

**Comment by tomasz1986** [comment]
Yes, this is technically invalid HTML. It still works, because Web browsers go out of their way to fix the incorrect code when rendering it.
