### ISSUE TITLE
renaming of source code sync conflict files breaks applications 

### ISSUE THREAD

**Issue by spicedreams** [syncthing/syncthing#7857]
I use a fair few Python applications which are distributed as source code (*.py). When Syncthing identifies a sync conflict it creates a new file like filestem.sync-conflict-{date}-{time}-{station}.extension so the sync-conflict file has the same extension as the original.
Python (perhaps not always) sees the sync-conflict file and compiles it into the applicatiion in place of the original. This breaks the application.

Could we have an option to create the sync-conflict filename like filestem.extension.sync-conflict-{date}-{time}-{station} instead? 

Or is there already a workaround for this that I have missed?

Thanks

**Comment by AudriusButkevicius** [comment]
You can set syncthing not to create conflicts, or you should probably adjust your workflow not to create them.

I think the discussion on this subject should happen in the forum first, as I am not sure we want to do that, as the naming scheme is deliberate for the purpose of being able to open the files with the same application as the original.

**Comment by spicedreams** [comment]
Thanks Audrius,
Sorry, but where is the option to not create conflicts? I currently use simple file versioning on the directory tree in question, should I be using something different?

**Comment by AudriusButkevicius** [comment]
Versioning has nothing todo with conflicts. In advanced configuration you can set max conflicts as per https://docs.syncthing.net/users/config.html
