### ISSUE TITLE
Synchronisation of encrypted folder stuck, high memory usage

### ISSUE THREAD

**Issue by cyplo** [syncthing/syncthing#7861]
Hello amazing people ! 

I've added an untrusted device (let's call it `U`) to my normally working setup and it's struggling to do the initial synch of all the folders.
It got around 80% of the data with no problem, synchronised full folders, but it's struggling with the last 2 of them.
The synchronisation rate dropped to 1 byte per second, syncthing uses around 8-14GiB memory on `U` now and 2 full CPU cores, but not on any of the other hosts.

```
    PID       TID    MINFLT    MAJFLT    VSTEXT    VSLIBS     VDATA    VSTACK    LOCKSZ     VSIZE    RSIZE     PSIZE     VGROW     RGROW    SWAPSZ    RUID        EUID         MEM    CMD        1/6
  10984         -     96015     60689    10376K        8K     14.1G      136K        0K     14.7G     6.7G        0K        0K     -0.1G      6.0G    syncthin    syncthin     88%    syncthing
```

This is an excerpt from the logs on `U`:
```
Jul 31 23:23:14 brix syncthing[8247]: [] 23:23:14 INFO: Puller (folder photos, item "8.syncthing-enc/DT/L03IHLC16JCGC2LDEHQFOLLD3RVBBO2L64OHKA1MHQ6M4Q1EIMEK5I6TV6OF2Q2VJSV77RBD1UTM0TKLKA7CMLECU4689"): syncing: pull: generic errorJul 31 23:23:14 brix syncthing[8247]: [] 23:23:14 INFO: photos: Failed to sync 136 items
Jul 31 23:23:14 brix syncthing[8247]: [] 23:23:14 INFO: Folder photos isn't making sync progress - retrying in 35m51s.
```

When restarted, the syncthing process on `U` seems to get better for a while, downloading at around 50KiB/s (normally it would be ~30MiB/s for that machine) but then deteriorates again quite quickly.

I'm on Linux (all devices that sync together, except one which is Android). `U` is an NixOS server,
 `U` and most of the other devices are running Syncthing 1.18.0.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by cyplo** [comment]
Hi, I will open up a topic as suggested.

My thinking here was that this is pretty unexpected and behaviour concerns a newly-added feature, that effectively does not work in my scenario, as in never finishes syncing, hence I thought it would be best to report as bug, as the untrusted devices support seems to be under active development.

**Comment by AudriusButkevicius** [comment]
So far it's a symptom, not a cause. 

I mostly try to keep issue tracker clear of symptoms, until we figure out the cause, so we know what to fix.

**Comment by cyplo** [comment]
Forum thread - https://forum.syncthing.net/t/untrusted-device-never-finishes-syncing-very-high-memory-usage/17187
