### ISSUE TITLE
Can't reach device from outside of my network

### ISSUE THREAD

**Issue by JonAnder83** [syncthing/syncthing#7863]
There's a certain device (which happens to be my "central" main node) that is unreacheable from outside my network and I cannot figure out why.
Inside my lan it appears as "connected", once I shift to mobile or go to a different location or place with wi-fi, that particular device never gets "connected" status and thus, is unreachable.
The system is a VM running arch linux: Other windows machines do get connected from inside or outside of my lan but THIS particular one does not.
Help?

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by JonAnder83** [comment]
https://forum.syncthing.net/t/discovery-failures-connection-refused-for-v4-and-v6/15553/5

This solved it.
Thanks and sorry for the trouble
