### ISSUE TITLE
SyncTrayzor: Can't disable desktop notifications

### ISSUE THREAD

**Issue by rmacyn** [syncthing/syncthing#7867]
Reference:
https://forum.syncthing.net/t/rest-api-how-to-auto-disable-desktop-notifications-in-synctrayzor/17133/3?u=rmacyn

Desktop notifications (Syncing finished, etc....) still occur even though the "Notifications" option is unchecked. 

Hint: It looks like the notifications checkbox is re-enabled when new folders area added.

Environment:
- Windows 10

**Comment by uok** [comment]
Please create your issue in https://github.com/canton7/SyncTrayzor
