### ISSUE TITLE
REST API: Incorrect completion status on remote device

### ISSUE THREAD

**Issue by rmacyn** [syncthing/syncthing#7868]
Getting the completion status of a  fully synced device folder returns incorrect values?

I'd expect "completion" to be 100 and "needBytes" to be 0 ??? (or am I missing something?)

Setup:
-----------------------------------------
Local device: Windows 10
Remote device: Ubuntu Linux

Output:
------------------------------------------
curl -H "X-API-Key: xxxxxx" localhost:8384/rest/db/completion?folder=b93fbbaa779af2169f541f421e05412c5_project&device=xxxxxx

{
  "completion": 0.006311530955027678,
  "globalBytes": 20280341,
  "globalItems": 403,
  "needBytes": 20279061,
  "needDeletes": 0,
  "needItems": 393,
  "sequence": 796
}

**Comment by AudriusButkevicius** [comment]
Based on the output, it doesn't look synced.

Anyways, I feel this is better suited for the forum, given the UI uses the same API call you are referring to, so there must be some misunderstanding.
