### ISSUE TITLE
UI non-friendly

### ISSUE THREAD

**Issue by midenok** [syncthing/syncthing#7871]
1. If I added device B on device A why I have to add devide A on device B as well? If this is some kind of security I don't need it.

2. When files are copied why they are all .tmp until the whole sync finishes? Please make each file usable as soon as it was copied 100%.

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
