### ISSUE TITLE
Delay Sync on modified file

### ISSUE THREAD

**Issue by ljlongwing** [syncthing/syncthing#7877]
https://github.com/syncthing/syncthing/issues/7590

I have a similar request to 7590.  I have a folder that I export videos from my DVR to.  An example might cause the file to be being written to for maybe 10 min's while it's being exported.  Once it's exported, I want it sync'd, but Syncthing starts trying to synchronize it almost immediately and throws an error regarding 'file changed during hashing' and the folder is marked as 'Failed Items'.  I tried using fsWatcherDelayS, but that only delays the sync for x seconds once a file change was detected.  I much like the other person am looking for an option to say 'don't sync till it hasn't been modified for x'.  For me, that would allow the file to finish exporting before it started syncing the file, and for him, it would stop his project from being synced during the day, but at the end of the day when he went home, the project would sync without issue.

**Comment by imsodin** [comment]
That's exactly #7590. And the reasoning against doing that is still valid: With such a setting, if a file gets modified sufficiently often, it will never get synced.
