### ISSUE TITLE
One-click installation for Windows 10>?

### ISSUE THREAD

**Issue by chulora** [syncthing/syncthing#7880]
### Include required information

Please be sure to include at least:

 - what problem your new feature would solve
 - how or why you think it is generally useful (i.e., not just for you)
 - what alternatives or workarounds you considered

**Comment by AudriusButkevicius** [comment]
You can use synctrayzor.
Or just download and run a binary, it's zero click installation, as no installation is required.

For questions like this, please use the forum in the future.

**Comment by Bill-Stewart** [comment]
Also see here:

https://github.com/Bill-Stewart/SyncthingWindowsSetup/
