### ISSUE TITLE
stcrashreceiver uses too much memory

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#7883]
It mostly just writes stuff to disk, it's not clear to me why it needs a whole GB of RAM to do it.

<img width="1108" alt="Screenshot 2021-08-12 at 08 56 20" src="https://user-images.githubusercontent.com/125426/129151827-d122d3c6-475c-4c63-a488-f0925cfa4261.png">

**Comment by sn01615** [comment]
1GB server directly stuck
