### ISSUE TITLE
Lock encrypted folder for untrusted device

### ISSUE THREAD

**Issue by psi5asp** [syncthing/syncthing#7885]
### Include required information
Request to have the option to prevent the ability to decrypt folders from the GUI on untrusted devices, and lock Folder Type to "Receive Encrypted" only. eg have a 'lock' option on the sending device when putting a password for an untrusted device. That way the untrusted device is unable to enter a password to decrypt the data.

**Overview**:
Control/management for trusted/untrusted defined devices should be done from the sender device (eg the content owner device). If an untrusted device has the ability to decrypt the folder content, then technically it is no longer an 'Untrusted' device, so no password is required anyhow. This can still be an option, however a requirement to perm-lock the untrsted device from decrypting via GUi is also required. This will mistake proof adding folders on devices that admins have little control over (ie untrusted devices).

**Details**:
Currently, Syncthing has the ability to decrypt folder data on the "Untrusted" device (when adding an encrypted folder, one can select "Folder Type" as 'Send/Receive/Send&Receive' then type the password to decrypt the incoming data). This defeats the purpose of classing the device as "Untrusted". If decrypted data is required on the receiving device, it can simply be done on the sending device by not having a password and saving cpu/resources.

It is possible the reason to encrypt-send-decrpt folders  is due to transport security. if this is a concern/requirement, then the transporting method should be revised and not be mixed in the the device statuss (Transport Encryption and Device Encryption 
are separate functions/features/requirements). Data that ends up on a device as "unencrypted" is technically classing that device as trusted device, so no password is required for the trust status of a device to start with.

Firstly, establishing if there is a legitimate concern about transport encryption is required. If the data transferred under normal (non device encrypted) use isn't securely encrypted, then perhaps using the Device ID to encrypt the data for ANY folder may be an option for the exta security conscious user.

**End result is to**:
1) Keep trusted Vs untrusted device function integrity by having the option to lock the folder as encrypted - once a device is classed as "trusted" only "Receive Encrypted" is allowed and no password can be entered on the untrusted device. The only way to make it trustworthy is to remove the password from the Sending device (where it was defined in the first place).
2) If the requirement for better security during transfer is required, then perhaps use the Device ID's or a computer genrated ID 
 (securely transferred with the Device ID as the encryption key, etc.) to transparently encrpt data while in transit (make it optional for each device/folder, etc. as a tickbox or something).
3) Perhaps look at reversing the dependencies ie instead of allowing Folder Types Send/Receive/ Send and Receice first then password can be entered, those 3 options require a password first to select the 3 folder types. ithout a password there is no way to select the 3 folder types. This will stop failure messages and ensure users have to add a password first to then access those folder type options that require it, rather the other way around.

This request mainly deals with Webpage/GUI management to allow additional option (via tick-box/lock-box?) to block the Folder Type dropdown and entering any possible password to 'decrypt' on an untrusted device.

The possible 'requirement" (if any) of encrypting over a transport protocol. is something for further review (in another request), as it may involve a re-design to do it properly.

**Comment by acolomb** [comment]
Regarding point 2. the transport is always sufficiently encrypted, whether or not sharing the folder with some device is marked trusted or untrusted. No requirements there.

And I think you are misunderstanding the encryption concept. If the decision is made solely on a device A that has the plaintext data, how would you add a third device B that should also have unencrypted access, but connects only to the untrusted node U (no direct connection to any other unencrypted device). With the current scheme, sharing from an encrypted device U to a trusted third party B is possible by just telling the password to B's owner over a separate channel and device U will not even know who considers whom trusted.

**Comment by acolomb** [comment]
Sorry I was replying to your post before you edited it. Also please use the forum for discussions like this.

**Comment by psi5asp** [comment]
Sorry, yea I had to make it clearer to get rid of the assumptions that I found in the forums ie justifying the current function is not what this request is about. I'm not asking to remove the existing function in this request. 
This request is about adding the option to block decrypting data on an untrusted device by having an option to block the Folder Type and password entering on the untrusted device.

**Comment by psi5asp** [comment]
For a 3+ devices, if untrusted - the same options and request applies.
For 3+ devices, if trusted, the same options and request applies.

**Comment by psi5asp** [comment]
Even using a "yellow" padlock symbol in the GUI when entering a password eg  clicking on the existing padlock and it locks as yellow or something (hover over to get the status = 'locked on untrusted device') or something similar would suffice, then javascript to block the folder type dropdown on the untrusted device would be suficient - ensuring the password block is also locked out on the untrsted device.

**Comment by psi5asp** [comment]
Ok this appears to be an oversight (allowing the selection of Folder Types other than 'Recieve Encrpted" for untrusted devices, when adding new folders with encrpted data). 

I tested this by selecting "Send & Recieve" folder type on the untrusted device, then entering the same password and the folder became "Out Of Sync".

Just blocking all folder types (Send, Receive, Send & Receive) and only having "Receive Encrypted") on untrusted devices will fix this

**Comment by AudriusButkevicius** [comment]
> Control/management for trusted/untrusted defined devices should be done from the sender device (eg the content owner device).

This is fundamentally wrong and not how syncthing works.


As explained on the forums, all "Untrusted" means, is that we never send plain text data to the device, what that device does with it, is none of our business.

I think in your head you think it means something else, or you'd like to to mean something else, but it won't.

Again, similar to your other ticket, you are looking at this through the eyes of a centralised system.

No device in syncthing can force another device to do something, hence this ticket js not going to happen.

**Comment by psi5asp** [comment]
Its clear you've made up your mind on what users 'appear to want'. The idea of encryption is clear - to protect sender data.

**Comment by AudriusButkevicius** [comment]
It's not about what someone wants, it's about how the application is designed, and what is possible within that design. What you described is simply impossible to do with the current design in a way that would not be security theatre, but the design brings many other benefits, so we're keeping it this way.
