### ISSUE TITLE
Auto Accept not working?

### ISSUE THREAD

**Issue by psi5asp** [syncthing/syncthing#7887]
### Does your log mention database corruption?
No DB corruption.

### Include required information
I have enabled "Auto Accept" to allow automatic folder adding on a device, but I keep getting new folder request prompt to add the new folder " **_XXXXXXXX wants to share folder "Test" (XXXXX-XXXXX). Add new folder?_**"

### Settings
On the Receiver device I enabled "_Auto Accept_" for the sender device, and get the prompt
On the Sender Device I enabled "_Auto Accept_" for the receiver device, and get the prompt
I enabled both as above, and still get the prompt.

### Expected Behaviour:
I would expect when enabling "Auto Accept" that the recieving device automatically add the folder o the default location as per its description: "Automatically create or share folders that this device advertises at the default path."

### System Info
Using (Sender) Syncthing v1.18.1, Windows (64-bit Intel/AMD) - Build 2021-07-30
Using (Receiver) Syncthing v1.18.1, Linux (64-bit ARM) - Build 2021-07-30
Browser: Opera v77.0.4054.277

H/D permissions are correct, because when I manually add the folder it works fine.

**Comment by tomasz1986** [comment]
This is working here on my end.

Starting from empty state, with all default settings:

1. Connect Device 1 and Device 2.
2. On Device 2, enable Auto Accept for Device 1.
3. Create a new folder on Device 1, and share it with Device 2.
4. The folder has been automatically added to Device 2.

Do you still have the problem when following these steps? If yes, I would suggest to enable `model` and `db` debug logging, repeat the operation, and then upload the logs here, so that the maintainers will have the required information to analyse.

**Comment by psi5asp** [comment]
I have the devices already connected and sync'ing many folders. Unfortunately I can't do step 1

...however it appears that the settings take a page refresh (or some thing) to be applied. I would have thought when I pressed "OK" on enabling the "Auto Accept" those settings would be applied immediately.

I did step 2, then 3....and it failed......so I re-did step 2, refreshed and waited 10-20secs (even paused/started the other device), then did step 3 and it worked. 

It also appears any prompts prior to changing settings, do not get applied to the settings of the prompt. eg if I have a "Add new folder?" prompt, i go and enable "Auto Accept', the "Add new folder?" prompt does not disappear when the setting change applies to it.

Anyhow, thanks for confirming. This appears to be some sort of syncthing sequence thing when applying settings and when they affect the prompts.

**Comment by tomasz1986** [comment]
You may be experiencing some GUI slowdowns. I get them all the time, especially when the OS is busy doing other I/O-heavy operations, and also very often on slow hardware in general. Syncthing by default runs on lower priority (which I personally set to even lower), so it has to wait for more important processes to finish their operations first.

**Comment by AudriusButkevicius** [comment]
Auto-accept happens when a connection is established.

If you already have a connection to a device, enabling that setting will not suddenly add the folders that were previously advertised on the connection that happened some time ago. You can pause/unpause the device to get that effect.
