### ISSUE TITLE
Hide Encrypted data on untrusted devices

### ISSUE THREAD

**Issue by psi5asp** [syncthing/syncthing#7888]
### Include required information
When sync'ing encrypted data to an 'untrusted' device, the encrpted data should be stored in a special folder like .stencrpted. This keeps encrpted data sperate to the normal (local) contents of the folder. This become relevant when the folder already exists and in use on the untrusted device (such as "Pictures", "Documents" etc.).

I guess if the folder doesn't already exist, it should still store encrypted data in a special folder to keep things consistent.

eg Sender folder called "Legal Documents", so an untrusted receiver would be "`/Legal Documents/,stencrpted/(device id?)/(Encrypted data).`..". This allows the untrusted device to still use "/Legal Documents" like a normal folder, and can sync it if also required (but not sync the `/.stencrypted/` contents as part of its own sync settings).

Since untrusted devices that have encprted data are really only used to store data (backup), this allows for the continued use of existing folders of untrusted devices.

**Comment by AudriusButkevicius** [comment]
No, if you want to have two copies of the folder, one encrypted, one not, create two folders.
