### ISSUE TITLE
High Availability Nodes

### ISSUE THREAD

**Issue by gt2416** [syncthing/syncthing#7889]
Hi, I run syncthing to backup to a NAS from a Windows Server. 
I have 2 Windows Servers that are configured as fail over/ HA nodes. They both use the same ISCSI storage but only one is connected to the storage at a time. If one windows server goes down (say when updating) the ISCSI storage is automatically mapped to the other windows server.
Both run syncthing, the problem is that since only one node has access to the storage at a time , the syncing process never finishes and stays in a stuck / out of sync state. It also causes errors like` directory has been deleted on a remote device but is not empty; the contents are probably ignored on that remote device, but not locally` because 1 node has a directory in their database but is unable to know that it is now deleted. 
I propose adding a feature that lets syncthing know that these 2 nodes are the same storage (HA Storage), so it should only sync with one of them at a given time. The node where the folders are "missing" should sync its database with the node that has the storage currently attached. This will also prevent the scenario that when 1 node goes down and the other takes over, syncthing has to rescan the entire filesystem again., which takes almost a day with the amount of data we have.

**Comment by AudriusButkevicius** [comment]
In general I think Syncthing is considered a consumer application, so these sort of scenarios sound like out of scope for syncthing.

Never the less, you can probably make it work by having two nodes that have the full set of data (without any fancy storage fail over shenanigans).

Regardless, I feel the best place to discuss this is the forum.

**Comment by gt2416** [comment]
Your right, this is a business use case. Ideally the nodes would have the same data but ISCSI doesn’t work like that. Anyway thanks for the reply.

**Comment by AudriusButkevicius** [comment]
I am not saying it's impossible to do, but as I suggested, the discussion of what is possible and what is not belongs on the forums.
