### ISSUE TITLE
golang 1.17  run panic

### ISSUE THREAD

**Issue by zhuxiujia** [syncthing/syncthing#7900]
```go
syncthing/notify@v0.0.0-20201109091751-9a0e44181151/watcher_fsevents_cgo.go:64 +0x33

syncthing/notify@v0.0.0-20201109091751-9a0e44181151/watcher_fsevents_cgo.go:72 +0x45
created by github.com/syncthing/notify.init.1

```

**Comment by AudriusButkevicius** [comment]
Doesn't look like its the full panic. There isn't even a panic message.

**Comment by zhuxiujia** [comment]
> Doesn't look like its the full panic. There isn't even a panic message.

You can update GO to the latest version 1.17. Syncthing does panic at startup and output the error

**Comment by calmh** [comment]
Our nigthlies are build with Go 1.17 and we've been running them since Go 1.17 was released. Today's final 1.18.2 RC will be built with Go 1.17. So we'll see how that goes I guess.

```
% syncthing --version
syncthing v1.18.2-rc.2.dev.9.g5711bacd "Fermium Flea" (go1.17 darwin-amd64) teamcity@build.syncthing.net 2021-08-22 18:04:47 UTC [stnoupgrade]
```

**Comment by imsodin** [comment]
Just provide the full panic please, along with details about your setup (OS, syncthing version, ...) - it just makes life easier for everyone. We do build and run tests with go1.17, maybe not with cgo enabled - not sure without checking.

**Comment by tomasz1986** [comment]
> You can update GO to the latest version 1.17. Syncthing does panic at startup and output the error

I have, and everything seems to be working fine, at least in Windows. The issue may be specific the your environment (e.g. OS, filesystem, etc.).

**Comment by zhuxiujia** [comment]
> Our nigthlies are built with Go 1.17 and we've been running them since Go 1.17 was released. Today's final 1.18.2 RC will be built with Go 1.17. So we'll see how that goes I guess.
> 
> ```
> % syncthing --version
> syncthing v1.18.2-rc.2.dev.9.g5711bacd "Fermium Flea" (go1.17 darwin-amd64) teamcity@build.syncthing.net 2021-08-22 18:04:47 UTC [stnoupgrade]
> ```



My environment is MacOS BigSur 11.5.2

. so....  is my os  Different?

**Comment by calmh** [comment]
We have no idea what you've built or what you're running, as you're not showing us. As such there is nothing to troubleshoot here. If you do want to provide details at some point, that would be fine.
