### ISSUE TITLE
QR Code functionality not working for ID

### ISSUE THREAD

**Issue by pawann-2000** [syncthing/syncthing#7901]
Version - 1.1.29
Syncthing Version 1.18.1

The issue is with QR code generation I think
![image](https://user-images.githubusercontent.com/59572141/130617811-15c7a6fb-13fd-46c8-b82f-9998f171215e.png)
when I click show ID it doesn't generate a QR code and leaves me typing the whole code which takes up time.

**Comment by tomasz1986** [comment]
This looks like a browser problem, perhaps due to an adblocker or similar. Could you try using a clean profile, or a completely different browser, and see if the issue persists there?

**Comment by AudriusButkevicius** [comment]
Yes, suggest you try with plugins disabled

**Comment by pawann-2000** [comment]
The issue is within the app

**Comment by tomasz1986** [comment]
> The issue is within the app

Just to confirm, do you mean the official Syncthing application for Android?

**Comment by pawann-2000** [comment]
> > The issue is within the app
> 
> Just to confirm, do you mean the official Syncthing application for Android?

No it's the issue with the windows app

**Comment by imsodin** [comment]
Please report to https://github.com/canton7/SyncTrayzor.
