### ISSUE TITLE
Custom relay - Excessive DNS lookups

### ISSUE THREAD

**Issue by GitHubGeek** [syncthing/syncthing#7904]
### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using - **1.18.1, Linux amd64, running in LXC containers (Proxmox)**
 - browser and version, if applicable **n/a**
 - what happened, **From Pi-hole's DNS query logs, I can see heaps of lookups to** `myrelay.example.com`
 - what you expected to happen instead, and **Reasonable caching of name lookups within Syncthing**

### any steps to reproduce the problem. 

1. Fresh minimal LXC container running Debian, install syncthing from official apt repo
2. Make sure `/etc/resolv.conf` in the container is pointing to a Pi-hole instance (Or any DNS server that lets you see the query logs)
3. Set up a relay and assign a domain name e.g. `myrelay.example.com`, reasonable TTL e.g. 1 hour
4. In Sync Protocal Listen Addresses, enter the relay - `relay://myrelay.example.com:12345/?id=...`
5. Look at the Pi-hole query log - Many lookups of `myrelay.example.com`

**Comment by GitHubGeek** [comment]
Following up this issue - Some more observation:

I went into some of my syncthing instances and changed `myrelay.example.com` to an IP address, then restarted syncthing. Interestingly, those instances are still performing lookups of `myrelay.example.com`, albeit less frequently. I wonder why?

BTW - Agreed that DNS requests caching is OS's job.

**Comment by AudriusButkevicius** [comment]
If we agree that caching is the job of the OS, why is this an issue?

**Comment by calmh** [comment]
I expect those resolves / connects come from considering remote devices that announce they are available on the relay in question.

**Comment by GitHubGeek** [comment]
Imagine syncthing running on a mobile device, the frequent resolves / connects may contribute to high battery consumption.

**Comment by calmh** [comment]
If we're now talking about reconnection intervals that's a different subject and there are settings for you to control it.

I'm not seeing anything buggy or immediately actionable here, so I'm going to close the issue. That doesn't mean it can't be further discussed on the forum for example, if there are things that can be clarified or improved.

**Comment by K2M74** [comment]
> If we're now talking about reconnection intervals that's a different subject and there are settings for you to control it.
> 
> I'm not seeing anything buggy or immediately actionable here, so I'm going to close the issue. That doesn't mean it can't be further discussed on the forum for example, if there are things that can be clarified or improved.


#7960 
When the relay is interrupted, it is normal to check and analyze regularly, but it is unreasonable to check and analyze again when the relay function of one party has been turned off and connected.
