### ISSUE TITLE
`/rest/system/connections` doesn't include `inbps`, `outbps`.

### ISSUE THREAD

**Issue by jtagcat** [syncthing/syncthing#7910]
https://docs.syncthing.net/rest/system-connections-get.html

The GUI does use `connectionsTotal.inbps`, `connectionsTotal.inbps` and `connections[devicefg.deviceID].inbps`, `connections[devicefg.deviceID].inbps`,  
which are regularly calculated by a diff in the WebUI (`data.outBytesTotal - connections.outBytesTotal`).

## Why?
 - If a packet to the WebUI is lost, the numbers jump to a higher number, than actual. This used to also make me question, why the inbps was higher than inbps limit.
 - It'd be neat for external stonks (monitoring).
 - Reusal of code.
 - I wanted to make a thing that should probably be built in to syncthing, but what the heck, do it with the API. (It'd be device groups, and bwlimit based on device groups with priority, and devices moving in and out of the groups, aka bwlimit that really should be done in the router, but I don't have access to the router, and placing a router in between isn't the best option, so groups would track where a device is (thus how much can I consume), and prioritize a device in a group. This is really engineering your way out of other humans (well, you could just break in to a few rooms and reset a bunch of routers, yes?), and covid (should've done a go-to-the-library/server for a day and transfer data physically, although syncthing is usually very picky about physical transfers, maybe due to modtime?).)

**Comment by AudriusButkevicius** [comment]
I don't think it should include that, as how you calculate that would be fixed, and would also require to store state internally. Exposing just the bytes gives the freedom to do whatever the caller wants to do with that.

**Comment by jtagcat** [comment]
> Also, the numbers can jump over the limit anyway, as the rate limiter allows short bursts above the limit.

Yeah, that of course. I meant 20Mbps (2.5MiB/s) connection showing 15MiB/s for fewty seconds while it resumes (GUI client from sleep state).

I guess calculating and tracking it isn't that hard. It took some time to track it down, where the number in the GUI was actually coming from. I think I'll add a snippet to the docs of connections, that this is done on the REST client side.
