### ISSUE TITLE
Improvements to Syncthing device management

### ISSUE THREAD

**Issue by Netherquark** [syncthing/syncthing#7913]
Currently, you have to add devices on an individual basis. This is kind of clunky for me because I have dual boot on both my PC and my laptop, and I also hop custom ROMs on my phone (ie I have 5 "devices" in Syncthing at any moment, and considering how finicky Windows is, and how many ROMs I switch between, and the amount of Linux distros in this universe, those 5 "devices" are changing quite often). I was thinking either:

- a "mesh" 
I was thinking one "host" which will always be running Syncthing, and you just connect between the host and your device, and then your device is automatically connected to the remaining devices in the mesh. For example, if I just flashed a new ROM, I'll just boot up my PC, say, with Linux. I'll add my phone. It will automatically get added to the laptop's Windows and Linux partitions when I boot them up. Maybe a token authenticating my phone's ID which is sent from the host to the other devices in the mesh? I don't know how the token method could authenticate Syncthing on the Windows partition of my PC, because the "host" would be my Linux partition, and both "devices" can't be running at once, but I digress. The token method is just one way I could think of. I'm sure there are way more efficient and/or secure and/or faster methods to go about doing this. [Clarification: the host does not need to have all the folders syncing to it from all the various devices, but it will make sure all the client devices are added to each other. The whole syncing process will still be decentralised, but the authentication part will be sped up by the host.]
- an option to automatically accept any and all device/folder requests
Sometimes the "do you want to add this device/folder" verification takes a long time to show up and it sucks looking at both of the devices trying to see what went wrong. Regardless, I feel there should be an option to atleast automatically accept folder requests automatically, because I don't think there's a high chance of anyone transferring malicious code or whatever via adding a new folder. At that point, they'll have cracked the login password/pattern and the user have greater concerns than getting malware via syncthing.

I hope whatever I said made sense.

 ## what problem your new feature would solve
Adding new devices isn't elegant and clean at the moment, especially when you use a lot of them with Syncthing
## how or why you think it is generally useful (i.e., not just for you)
This would help people set up redundant folders easily. For example, with Google Drive, I used to create spreadsheets on my PC, edit them while I had local access to my PC, and then I could also work remotely from my laptop and phone via Google Drive. Here, the equivalent is setting up my home folder to sync with all devices, which I have the storage and internet for, but setting up the sync in the first place isn't that intuitive. The mesh idea would help with that, and the always accept idea would be an alternative somewhat patchy "solution". Though it would definitely not be secure by any means.
## what alternatives or workarounds you considered
Manually adding devices and folders. Got very tiring very quick. I know this isn't exactly a mission critical problem, but I hope my issues are understandable.

PS. as of now, yes, you can do the thing where you add all devices to one "host" device manually, and then you set up syncing to and fro on the "host" as needed. Eg. I can link my phone and my laptop to my PC and tell my phone to sync my photos to my PC and tell my PC to sync those same photos to my laptop. But, the obvious flaw here, is that the files are bound to the host as well. What happens when I want my photos syncing with my laptop while I'm on the go? When my PC is shut down? It won't work. so I have to arbitrarily add all the devices to each other anyways. Either of the solutions I proposed could help with this. I'm sure other users who have multiple devices can relate.

PPS. Using Syncthing-GTK on Linux, SyncTrayzor on Windows, and the Syncthing app on Android. Don't think that's relevant but mentioning it anyways.

**Comment by AudriusButkevicius** [comment]
You should check the documentation. Introducer feature has been there for quite a while.

If you have any other comments, please use the forum.
