### ISSUE TITLE
Trying to run syncthing on a FreeBSD system with W^X enabled

### ISSUE THREAD

**Issue by igalic** [syncthing/syncthing#7915]
Hey folks,

I installed syncthing on a FreeBSD system with [W^X enabled](https://www.freebsd.org/status/report-2021-01-2021-03/#_vulnerability_mitigations) and for mysterious reasons the service just wasn't coming up.
running `syncthing --help` gives the following error:

```
exec_new_vmspace: mapping stack size 0x20000000 prot 0x7 failed mach error 2 errno 13
Abort trap
```

is this behaviour strictly necessary?
Can it be fixed on your end, or should we just recompile the software with `-Wl,-z,wxneeded`?

**Comment by calmh** [comment]
You can try that. Report back if it works. There may be some aspects to the Go runtime as well possibly.

**Comment by greatroar** [comment]
[rclone](https://forums.freebsd.org/threads/rclone-not-working-with-w-x.80279/) and dnscrypt-proxy (DNSCrypt/dnscrypt-proxy#1730) have the same problem. Looks like a Go linker/runtime issue.

**Comment by igalic** [comment]
given that this is a Go runtime issue, I've opened a ticket in Go: https://github.com/golang/go/issues/48112

**Comment by AudriusButkevicius** [comment]
Closing in favour of the runtime ticket.
