### ISSUE TITLE
Full CPU usage

### ISSUE THREAD

**Issue by LeNouveau** [syncthing/syncthing#7916]
Hi, 

Lately, Syncthing is using all my CPU. 

![image](https://user-images.githubusercontent.com/3670305/131460461-b1316854-69da-4b3c-a504-71479ea6b65e.png)

When starting Synctrayzor, it is empty. 

![image](https://user-images.githubusercontent.com/3670305/131460530-46c82469-19f3-4262-bd86-ea180b4c7649.png)

If I click on "Synchting > Stop all Syncthing processes", all processus are well stopped. 
If I start through the IHM, it runs smoothly. 

I had a file in conflict. 
I don't know if it is related. 

### Versions 

- Windows
- Synctrayzor : 1.1.28
- Syncthing : v1.18.1

### Sync folders

I have 2 folders, with a total of 200 files, for 1.5 Gb. 

### Does your log mention database corruption?

I don't have older logs, but current one does not have corrupted database; 

### Logs 

In `C:\Users\xxx\AppData\Local\Syncthing\syncthing.log`, I don't have error logs. 
(And content is complicated to anonymise) 

Where could I find more information ? 

Regards, 
LeNouveau

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
