### ISSUE TITLE
"Override changes" button on the "Receive Only" side

### ISSUE THREAD

**Issue by alex73** [syncthing/syncthing#7923]
I have synchronized folder with "Send Only" type on the first computer, and "Receive Only" type on the second computer.
Sometimes, user accidentally modified files on the "Receive Only" side. After that, I see "Override changes" button on the "Send Only" side. 

But it would be great to have the "Override changes" button on the "Receive Only" side to be able to user restore files himself.

**Comment by AudriusButkevicius** [comment]
The button should appear on both sides.

Suggest you start a thread on the forum if that is not the case.
