### ISSUE TITLE
Add cpu limit option since running "cpulimit" tool no longer works

### ISSUE THREAD

**Issue by ell1e** [syncthing/syncthing#7927]
Please add a cpu limit option to syncthing itself. I have been applying the "cpulimit" tool for some years, and previous feature requests for this have been denied pointing to that possibility. However, with auto updating this was always brittle since unless I write some sort of watchdog daemon (and is that really a reasonable thing to expect syncthing users to do??) any automatic update will remove the limit again. Now it appears since a recent update, the limit will *always* become ineffective minutes in, basically rendering the cpulimit use completely impractical.

On devices like the PinePhone, syncthing without cpulimit is simply unusable. It is not a minor specialty option. Even while charging, syncthing will slow down charging intensely and cause potential overheat issues even due to happily causing 300%+ cpu usage **when nothing is synced in regular idle** simply due to folder scans. Therefore, using cpulimit on phones on syncthing to make it usable is simply required, and on laptops I found it while not as essential still highly preferable to keep down both battery drain and fan noise.

It would therefore be really nice if this option could finally be added in properly, preferably into the regular (non-advanced) settings UI as well so people can actually find it. It's really badly needed on mobile, especially now that cpulimit is just plain broken.

**Comment by AudriusButkevicius** [comment]
The fact that it's not idle, means things are changing in the folder (potentially repeatedly), so I think you need to figure out what is making continuous change that ends up causing continuous scans, that end up using your battery, oppose to constantly consume 30% of your CPU which will still cause the same issues.

In general, I don't think our stance on this feature has changed. Operating systems have many ways nowadays to do prioritisation of process execution.

**Comment by ell1e** [comment]
@AudriusButkevicius I don't understand, I think you're wrong. You just need 1+ folder too big for the watch mechanisms. I have giant folders, so it just crawls them a lot.

> Limiting CPU use in general is not something that will ever help, because even if I am consuming 50% of the CPU, I'll have to consume it for double the time, leading to exactly the same power use, just over a longer period.

Actually it helps a giant amount with repeated scans. It will do less of them in the same time, also it won't *overheat* the phone. Even if I tweaked the scan times for all folders manually, did you miss the overheating part? I really don't get this simplistic view. And why does something as simple as annoying fan spin not count?

syncthing just behaves abysmally with large folders not all on inotify on battery devices. I think you should change your stance, especially now that you broke cpulimit use somehow. (Likely by the process restarting at some point, so it no longer applies). I was not exaggerating that it is close to unusable now, unless I want to heat damage my battery in a day or two.

**Comment by ell1e** [comment]
Just to be extra clear:

> Operating systems have many ways nowadays to do prioritisation 

None that help with this, other than cpulimit which broke in a recent syncthing update. And overheating a phone *is a really huge problem*. Why does it have to be ignored like that? Just why? This is not a minor issue
