### ISSUE TITLE
[Low Prio][Docu Bug] Systemd Autostart: No file copying required?

### ISSUE THREAD

**Issue by sgasse** [syncthing/syncthing#7941]
Hi,

I've been setting up a new installation of syncthing and wanted to enable it as a system service via systemd. The documentation mentions that we [have to copy the systemd unit template file first](https://docs.syncthing.net/users/autostart.html?highlight=autostart#how-to-set-up-a-system-service). However, on two of my systems, this was not required.

The `apt` package (version `1.18.2 `) already installs the template to `/lib/systemd/system/syncthing@.service` (checked with `dpkg-query -L syncthing`). Is this a lucky particularity on my system, or is the documentation out of date from a time when the template was not installed with the package?

Directly after installing syncthing, without any manual action, I was able to do:
```
$ sudo systemctl enable syncthing@myuser
Created symlink /etc/systemd/system/multi-user.target.wants/syncthing@myuser.service → /lib/systemd/system/syncthing@.service.
```
My operating system is Ubuntu 20.04.

**Comment by bt90** [comment]
This part of the documentation is ment for manual installs of syncthing e.g downloading the binary from Githubs release page.

**Comment by AudriusButkevicius** [comment]
Also, documentation has its own repo for issues. But mentioned above, I'm not convinced its a bug.

**Comment by sgasse** [comment]
Alright thank you for explaining! :+1:
