### ISSUE TITLE
Improve error message about folder marker outside of folder

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#7942]
A folder marker point at the folder root or even outside of it (e.g. `../foo/bar`) is accepted. This is unsafe, as it breaks the check against fully disappeared folder contents. *If* that check should be possible to be disabled, then that should be an explicit option (I don't think it should be).

**Comment by tomasz1986** [comment]
If I try to use things like `../foo` or `..` for the folder marker in Windows, I get the following errors.

![image](https://user-images.githubusercontent.com/5626656/133009279-07f74f29-3f52-41e8-b7df-f6429ed0aa64.png)
![image](https://user-images.githubusercontent.com/5626656/133009281-662e9d15-ec5e-4bef-b30e-5851ae9cf554.png)

This is with the current Syncthing release already. The only "funky" marker that is accepted here seems to be `.`, but the ones located outside of the folder are not.

Which operating system accepts `../foo/bar`?

**Comment by calmh** [comment]
(I haven't looked at this at all but I hope our FS implementation eats the dot-dots and so this isn't allowed.)

**Comment by imsodin** [comment]
Yeah right. The issue has been about ".", the rest was an afterthought. Still doesn't to explicitly reject it from config, the error message will be nicer than "not a relative path" for something that is technically a relative path.

**Comment by tomasz1986** [comment]
> Yeah right. The issue has been about ".", the rest was an afterthought.

No worries 🙂. How about changing the issue title a little bit to make it more about adding a proper error message instead?
