### ISSUE TITLE
unexpected items on receive only untrusted node

### ISSUE THREAD

**Issue by rburgst** [syncthing/syncthing#7946]
### Does your log mention database corruption?
no

### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using
    - synology: v1.18.2, Linux (64-bit Intel/AMD)
    - mac: v1.18.1, macOS (64-bit Intel/AMD)

 - browser and version, if applicable
    `Version 1.29.79 Chromium: 93.0.4577.63 (Official Build) (x86_64)`
 - what happened:  
     - I constantly see "unexpected items" on the synology side where I have a sync setup where the synology is a `Receive Encrypted` folder type, 
     - I already removed and re-added the sync folder on synology and did a complete resync but this did not help

 - what you expected to happen instead, and
     - I would expect the synology side to eventually sync up and be up to date with my mac version without seeing any errors
 - any steps to reproduce the problem.
     - set up a synced folder on the mac side which contains a bunch of git source folders (with deep nesting)
     - try to set up an encrypted sync from mac->synology

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
