### ISSUE TITLE
Possible virus report

### ISSUE THREAD

**Issue by Alex-0293** [syncthing/syncthing#7949]
### Include required information

Please be sure to include at least:

 - Syncthing v1.18.2, Windows
 - Possible Trojan.Cobalt.pu injection in  installer syncthing-windows-amd64-v1.18.2.zip. Other installers does not tested.
 - https://www.virustotal.com/gui/file/e70af91e992354d86f3bad996ace4324f15cc35d64f888a6a428cf4cf742162a

**Comment by imsodin** [comment]
The occasional false positive - it happens. Just report to the anti-virus that it isn't a virus so they can fix it, no need to open a ticket here - thanks.
