### ISSUE TITLE
Syncing does not start

### ISSUE THREAD

**Issue by CarlosU** [syncthing/syncthing#7952]
### Does your log mention database corruption?

If your Syncthing log reports panics because of database corruption it is
most likely a fault with your system's storage or memory. Affected log
entries will contain lines starting with `panic: leveldb`. You will need to
delete the index database to clear this, by running `syncthing
-reset-database`.

### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using
 - browser and version, if applicable
 - what happened,
 - what you expected to happen instead, and
 - any steps to reproduce the problem.

**Comment by CarlosU** [comment]
Connection works. Occasionally Download / Upload rates show up with 1-2 Byte/s. 
Rescan takes just half a second in both ends. 
Both machines on same LAN. 

Here screenshots of both ends.
https://mega.nz/file/26RQQT5K#khUcXMjZ8UockSJYwt9LM4GCqoxiH6IIX1gsQDL5R4o
https://mega.nz/file/izJw1R7I#oUT_neTOljuXQ5oMH-tV2yDc0y7NwsRNyYlO1G6uXxk

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
