### ISSUE TITLE
when i set username and password , it crashed

### ISSUE THREAD

**Issue by iceshu** [syncthing/syncthing#7955]
### Does your log mention database corruption?

![image](https://user-images.githubusercontent.com/6309056/133930199-7b63eb12-b6b4-4b6e-9e0b-e2f560a82e9f.png)
![image](https://user-images.githubusercontent.com/6309056/133930260-fe8ace49-b919-4e39-931a-7b9ad7508345.png)
if i set the username and password  it crash never can open ;
![image](https://user-images.githubusercontent.com/6309056/133930369-069bbf3d-d268-4923-a075-65bd74f73e61.png)
![image](https://user-images.githubusercontent.com/6309056/133930373-d4e0fe23-4a6b-4024-99c6-b70a0fca6fe4.png)

### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using    v1.17.0   synology ds218+
 - browser and version, if applicable   chrome
 - what happened,  it crash when i set username and password
 - what you expected to happen instead, and,  it should reload
 - any steps to reproduce the problem.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
