### ISSUE TITLE
Unable to sync config files between PulseEffects installs on two different machines via Syncthing

### ISSUE THREAD

**Issue by Netherquark** [syncthing/syncthing#7958]
### Include required information
 - Syncthing-GTK latest version
 - Manjaro(GNOME) on both laptop and PC

### What you expected to happen 
I wanted to sync the PulseEffects folder between my laptop and PC so that it would be easier to keep my audio config consistent between the too. PulseEffects was installed as a Flatpak on both, via Pamac, as was Syncthing-GTK. I could set up a shared folder from my laptop, but when accepting it on my desktop, I wasn't able to see `~/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects`. I could only see `me.kozec.syncthingtk` in the .var folder. Further, I tried just pasting `~/.var/app/com.github.wwmm.pulseeffects/config/PulseEffects` into the path entry, but that did basically nothing.
### Any steps to reproduce the problem.
Try syncing any two Flatpaks' configuration files I guess?

**Comment by AudriusButkevicius** [comment]
Support is handled on the forum, but in general, i think flatpaks run in jails, so I think syncthing might not be able to access its files.
