### ISSUE TITLE
syncthing crazy request DNS

### ISSUE THREAD

**Issue by K2M74** [syncthing/syncthing#7960]
syncthing v1.18.2
strelaysrv v1.18.0

My LAN is 10.0.0.0/24, and there are syncthing1 (10.0.0.1), syncthing2 (10.0.0.55), relaysrv (10.0.0.1) in the LAN.
Syncthing2 sets the Static relay address (relay://abc.com.....).
Syncthing1 turns off Relaying, while syncthing3 exists (not in the local area network, relay://abc.com.....)
My reason is that when syncthing2 can't directly connect to syncthing3 outside, connect to syncthing3 through relay://abc.com..... first.
But I found through DNS records that syncthing1 requests to resolve abc.com every 30 seconds. I was surprised because I did not set a Static relay address for syncthing1.
When the relay://abc.com of syncthing2 was removed, DNS became normal immediately, and the same was true when syncthing1 was turned off.

![2021-09-23_20-35-58](https://user-images.githubusercontent.com/50667472/134509263-333e54e7-4208-40b2-bf0f-9bdd8800bf43.png)

**Comment by AudriusButkevicius** [comment]
This probably happens when we inspect addresses advertised by other devices. I think this is expected and not really unusual.

Please open a thread on the forum if you want to discuss this further.

**Comment by bt90** [comment]
This also reads like a duplicate of https://github.com/syncthing/syncthing/issues/7904

**Comment by K2M74** [comment]
> This also reads like a duplicate of #7904

It seems that more than I have encountered this problem.

**Comment by K2M74** [comment]
This problem can be solved by turning off the local discovery function.
