### ISSUE TITLE
Improve filesystem detection

### ISSUE THREAD

**Issue by bt90** [syncthing/syncthing#7963]
https://forum.syncthing.net/t/syncthing-keeps-attempting-to-resync-files-that-have-not-changed/17359/10

The current implementation uses gopsutils `disk.Usage()` which tries to detect the filesystem using statfs on Unix systems. This has some quirks as noted by @tomasz1986 

Could we iterate over the mountpoints instead in order to get a better detection?

https://pkg.go.dev/github.com/shirou/gopsutil/disk#Partitions

**Comment by calmh** [comment]
Could we not remove it entirely and put the responsibility of detecting android quirks on the android wrapper?

**Comment by bt90** [comment]
I'm not even sure if this is a pure Andoid problem. Looks like statfs generally has some rough edges.

**Comment by calmh** [comment]
Probably; but we only do the autodetection on android.

**Comment by imsodin** [comment]
I agree: If there's something specifically useful/necessary for android, lets do that there. And if it's about generally improving fs detection, that should be a request in gopsutil - I don't think we want to start re-implementing that in syncthing.
