### ISSUE TITLE
Trash Can File Versioning always throws errors on restore (even when succeeded)

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#7965]
1. Add a new folder and share it between Device 1 and 2.
2. Add a new file to the folder on Device 1 and let it sync.
3. Enable Trash Can File Versioning on Device 1.
4. On Device 2, delete the file, and let it sync.
5. On Device 1, try to restore the file using the GUI.
   ![image](https://user-images.githubusercontent.com/5626656/134776671-be4ffd72-6b34-4328-9b2b-0786e5533bf3.png)
6. Despite the error, the file has actually been restored correctly.

**Comment by AudriusButkevicius** [comment]
Can you hover on the error and see what the rest of the message says?

**Comment by tomasz1986** [comment]
```
trashcan versioner: restore: rename \\?\R:\syncthing-test\folders\test1\.stversions\~syncthing~1.txt.tmp \\?\R:\syncthing-test\folders\test1\.stversions\1.txt: The system cannot find the file specified.
```

**Comment by tomasz1986** [comment]
The issue seems to actually be very old.

I've done more testing, and it is present as soon as at least Syncthing v1.2.0. In the earlier versions, the GUI doesn't actually list any files in the Restore Versions modal, so I cannot test there.

**Comment by tykisson** [comment]
New install of v1.18.4, Linux (64-bit ARM)
I can confirm that I receive the same error but then the file did appear on Device 1/2.

Going back to the versions list the file is no longer listed in version. Deleting the file from Device 1 does sync over to Device 2 and still does not appear on the versions list. The test file now appears to be lost.

**Comment by tomasz1986** [comment]
I think this issue may be a duplicate of https://github.com/syncthing/syncthing/issues/6253. I'm not 100% sure though, because the error messages seem to differ, yet the behaviour itself seems identical, i.e. error on the screen, but working in reality.

Are the two issues about the exact same thing, or just similar?

**Comment by AudriusButkevicius** [comment]
Seems they are about the same thing. I'll close the other one given this has more context.

**Comment by tomasz1986** [comment]
I think the problem here is related to the logic behind

https://github.com/syncthing/syncthing/blob/30fa462e33f025b46e32d18d4a31b640ed23fd71/lib/versioner/trashcan.go#L66-L91

Basically, the error only shows up if the original file no longer exists. In other words, it occurs only when trying to restore a deleted file. On the other hand, if we try to restore a modification of a file that still exists in its original location, then there are no errors.

I've tried to fix to the culprit myself, but I can't really navigate the code with my limited Go skills. I just hope that this clue may be useful for someone else when trying to work on the issue.
