### ISSUE TITLE
Publish container images to github's container repo, in addition to docker-hub

### ISSUE THREAD

**Issue by davralin** [syncthing/syncthing#7967]
Docker hub has switched to having rate limits on the docker hub, with payment options to skip rate-limits.
Github has it's own container repo, that has no rate-limits.

Normally, this could be fixed by using github actions, but [as I understand it](https://github.com/syncthing/syncthing/pull/6841#issuecomment-692871851) there's a dedicated build-server somewhere.

Would it be possible to also post updated container images to github's container repo, so that they are available somewhere that is not rate-limited - or at least have some redundancy to where the image is published.

**Comment by bt90** [comment]
I seriously doubt that a regular user will hit those ratelimits to be honest.

> Anonymous and Free Docker Hub users are limited to 100 and 200 container image pull requests per six hours.

**Comment by davralin** [comment]
I have no idea what is considered a regular user or not, I hit docker's ratelimits about once a month.

Not sure what kind of build-system is used here, but pushing the container to github in addition to docker hub should be fairly trivial to implement?

...if only as a backup location.

To be honest, I came here to create a PR to implement the change using github actions, sorry that I can't help with the build-server...

**Comment by calmh** [comment]
I don't think the question is "does anyone hit Docker hub's rate limits", obviously they do, that's what they're there for. The question is more "do these limits prevent a normal user from pulling & running Syncthing". I suspect the answer is mostly no.

We could quite easily push the image to ghcr as well. Once we do that though, that's one more thing we effectively have to maintain in perpetuity so it's not just a question of adding an url to a script once and be done with it.

**Comment by davralin** [comment]
> Once we do that though, that's one more thing we effectively have to maintain in perpetuity so it's not just a question of adding an url to a script once and be done with it.

Fully understand and agree.

I came here prepared to add the code myself - I didn't know there was a dedicated build server.

Do what you want with this FR, no need to keep it around if you don't want to prioritize publishing it to a different location. :-)
