### ISSUE TITLE
Copy: Warning message inaccurate: Web interface: "Remove folder"

### ISSUE THREAD

**Issue by Jonta** [syncthing/syncthing#7975]
### Setup

 - syncthing v1.12.1-ds1 "Fermium Flea" (go1.15.4 linux-amd64) debian@debian 2021-02-04 16:26:39 UTC
 - Firefox 92.0

### Steps

- Web interface
- Folders
- Add folder
- Folder label "st-test-create-and-remove-dot-stfolder"
- Save
- `$ ls -a st-test-create-and-remove-dot-stfolder`
- `.stfolder`
- Web interface
- Click [st-test-create-and-remove-dot-stfolder]
- [Edit]
- [Remove]
- [Yes]

### Actual result

> Are you sure you want to remove folder st-test-create-and-remove-dot-stfolder?
> 
> No files will be deleted as a result of this operation.

### Expected result

> Are you sure you want to stop syncing st-test-create-and-remove-dot-stfolder with this device?
> 
> The folder itself will still exist

Or similar

It removes `.stfolder`, so saying that no files will be deleted seems at best inaccurate. =)

(This kind of copy: https://en.m.wikipedia.org/wiki/Copy_(written))

### Code

Was added into [default/syncthing/folder/removeFolderDialogView.html](https://github.com/syncthing/syncthing/blob/main/gui/default/syncthing/folder/removeFolderDialogView.html) by https://github.com/syncthing/syncthing/commit/205426a9c6bb3b60a06f4aece95fd0562cd9910e#diff-a484dbffd054b295d5730b6d812ae1094e71d3a2db114c064b47669f699c7e90R7

**Comment by tomasz1986** [comment]
Talking about `.stfolder` and such is tricky, because a) non-technical users may have never even see the hidden folder, and b) technical users may be using different marker names, etc. I personally wouldn't mention it.

I've given this a shot at https://github.com/syncthing/syncthing/pull/7976. Please let me know what you think, and also if you'd prefer to change the wording to something better.

**Comment by Jonta** [comment]
I think adding a [more info]-button would be good in a situation like that

#7976 reviewed. =)

**Comment by tomasz1986** [comment]
I've addressed and tried to fix the issues. I've also updated the screenshots. Please let me know what you think of it now.

**Comment by imsodin** [comment]
As discussed in #7976: The only thing that gets deleted is an Syncthing-internal, empty directory. So the intent of the message (the users data is not deleted) is correct, and tt even is technically correct, as `.stfolder` is not a file :)
