### ISSUE TITLE
use IDs as label on untrusted clients

### ISSUE THREAD

**Issue by randombugs** [syncthing/syncthing#7979]
When sharing a folder or client with untrusted clients, the folder or client name is auto-configured to the name on the trusted source. This information is not necessarily needed on untrusted clients.

The [documentation](https://docs.syncthing.net/users/untrusted.html#technicals) mentions at least the folder label as "not protected".

I would like an option to change this behavior. The IDs are needed anyway, so why not use them as names on untrusted clients? It would "protect" the folder labels on the filesytem on shared server/storage. Or at least they arent human-readable anymore.

(Another possibility would be to encrypt the label, but that sounds like a ton of more work, and sadly Im no developer and cant help implementing this.)

Did I miss something (searched Issues / Forum) or is a similar feature planed?

Thanks for this great tool!

**Comment by AudriusButkevicius** [comment]
You don't explain why tho 

Labels are part of the protocol, so this would still not protrxt you against leaking them.

This is not planned and I'm not convinced we'd even want this.

**Comment by calmh** [comment]
We could, I think, redact labels when sending the cluster config. But I think the reasoning was that the label is under control by the user so they can decide how much or little info to leak there, and the alternative is that the receiving end only gets a set of cryptic folder IDs they may not know what to do with. In the current setup there is choice.

**Comment by AudriusButkevicius** [comment]
Right, I think the user has enough control here, hence close?

**Comment by bt90** [comment]
The folder label should IMHO be redacted. I want to name the folders on my client without having to care if or what might be visible for a thirdparty.

> Device "Desktop" wants to share new folder "My secret porn stash"

...is probably not something the user wants to pop up on an untrusted node.

**Comment by calmh** [comment]
I think we let this be as-is for now.
