### ISSUE TITLE
Show likely status of disconnected devices

### ISSUE THREAD

**Issue by benshep** [syncthing/syncthing#7981]
Feature request suggested first in the [forum](https://forum.syncthing.net/t/likely-status-of-offline-devices/17412/4).

Currently there’s a “Last Seen” status line for each device in the GUI. Would it be possible to implement a “Sync Status” line too? It would be ‘up to date’ just after the device disconnects, and as shared files are changed and the device stays offline, it would gradually get more out of sync. Obviously it’s not necessarily accurate (since the device I’m on may also go offline) but it would help see how up-to-date each device is even when they’re disconnected. If implemented, this could even be used as the status (i.e. not just ‘Disconnected’ but ‘Offline / 95% synced’ or something).

**Comment by tunbridgep** [comment]
Maybe when any file is changed in any sync folder, the "Disconnected" status on any devices which that device is shared with should show "Disconnected (Out of Sync)" or some equivalent.

I don't know the internal working of syncthing, but this seems like it wouldn't be too painful to implement.
