### ISSUE TITLE
Selective Sync

### ISSUE THREAD

**Issue by strider72** [syncthing/syncthing#7985]
This has been raised before, but the discussion always seems to turn to an inversion of the actual request.  Please take a look, and consider this feature.

I would love to see selective sync. This is *not* the same thing as an exclude list.  Yes, you could technically accomplish this with excludes, but approaching it from that direction makes it unusably clunky -- imagine going in to a grocery store to buy a gallon of milk, and having to tell the cashier everything you *don't* want to buy....

Here's the concept:  On the client app on my phone I could pull up a shared folder in the Syncthing client.  Browse files.  None of the files are actually on the phone, it's just an index.  I can select a file or folder, and toggle a switch to say "sync this".  Now it downloads to my device and stays synced.  If I flip that switch off, it's removed from my device.  By default, the Selective Sync switch is turned off for whatever directory I'm sharing (which maintains the way it works now -- "off" means everything is synced).

Why is this important?  There are a lot of scenarios where I might want to have access to a remote directory, but not actually have the entire thing loaded on my phone.  Maybe I have an old phone with limited space.  Maybe it's a really huge pile of data and I just never know what I'm going to need. I have a truly huge ebook library; I want to be able to access any book when I want it, but don't want to fill up my phone with every book I own.  Maybe it's videos.  Could be anything.

For a perfect example of this on other software, take a look at a system called Resilio Sync. (Yes, I could just use Resilio, but there are other advantages to Syncthing, and they rarely update. I fear the day that app dies and I'm left hanging.)

Original request (closed): #193

Current Issue covering the request (but doesn't really):  #2491

**Comment by strider72** [comment]
Clarification on the UI: Everything has a "Selective Sync" switch.  "Off" means that file (or folder and everything within it) is fully synced, the same as Syncthing works now. "On" basically means "don't auto sync this".  So a folder where it's turned On wouldn't sync, but within that folder you could selectively turn it Off for specific files or subfolders.

You could flip that, I guess, and make the switch say "Auto Sync". Take the above description and reverse "On" and "Off".

**Comment by AudriusButkevicius** [comment]
To me, this is exactly as https://github.com/syncthing/syncthing/issues/2491, so I am closing this, unless there is a good explanation how it's different.
