### ISSUE TITLE
HTTPS doesn't seem to work

### ISSUE THREAD

**Issue by hixcube** [syncthing/syncthing#7997]
v1.18.3, Linux (64-bit Intel/AMD) - "Fermium Flea" - Build 2021-09-28

The problem occurs on Synology NAS with DSM 7.0-41890  

with installed Syncthing 1.17.0-22 - developer Safire, acolomb - my first Syncthing install 06-10-2021

All Browser:  Chrome v94.0.4606.71 (Uff. Build) - Yandex (Chrome Based) V21.9.0.1044 64bit - Edge Versione 94.0.992.38 (Uff. Build) (64 bit) - Opera

HTTPS and GUI password are the first things I configured after installation (as also proposed by Syncthing). 
In fact they are now both enabled. 
Consequently, it is abnormal that even after several restarts of the Web GUI the browser continues to warn me that the site is in http version and not https.

**Comment by acolomb** [comment]
Did you restart the Syncthing service as well? Or just close and reopen the GUI in the browser?

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by hixcube** [comment]
> This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.
> 
> Thanks!

For me it would have been much easier to write on the forum, to which - moreover - I am subscribed, rather than using my time to report what I believe to be a defect.
