### ISSUE TITLE
Skip .tmp rename file option (write to final filename directly)

### ISSUE THREAD

**Issue by rawGH** [syncthing/syncthing#8003]
I'm using syncthing for video files between a couple of sites. 
Have no issues, love the thing, however a need has arisen, namely videos to be played immediately after sync starts.

eg like when files transferred manually via FTP, one can watch them while the file is being downloaded.
This considerably cuts the delay between file copy start and video being played.

Option to be added on a folder level. Could come in handy in other ways too, might be worth implementing.
Would appreciate if someone could comment on it, or at least point me in the right direction, might try to code it myself if not too hard.

**Comment by AudriusButkevicius** [comment]
The files in syncthing are not necessarily downloaded in order, namely its perfectly legal to download files backwards (download the end of the file first).

Also, we use temp files for a reason, to achieve atomicity and prevent data loss.

There already exists a ticket for in-place file updates, hence closing this.
