### ISSUE TITLE
Display status of folders for remote devices

### ISSUE THREAD

**Issue by alex73** [syncthing/syncthing#8005]
Each remote device has "Folders" field with list of synchronized folders. It would be great to display status also, i.e. status of each folder for each remote device.

Currently, for collect such statuses, I have to check syncthing UI on every remote computer, but it's not useful because there are many remote computers, and they are behind firewalls. Sometimes I know about issues after several weeks, because users don't pay attention for syncthing's messages. For example, user renamed folder, his local syncthing displays status "Stopped" but I don't know about it before user asking "why files are not updated?"

**Comment by AudriusButkevicius** [comment]
There is nothing in the protocol to be able to do that, and I am not sure we'd want to have that, as it leaks too much internal information.

We do not expect you to be able to do some sort pf remote support/debugging from your machine.
