### ISSUE TITLE
Request: support listing the discovered devices using the cli

### ISSUE THREAD

**Issue by jwatt** [syncthing/syncthing#8007]
When you click on "Add Remote Device" in the web GUI, it displays a list of discovered devices on the local network that can be added. As far as I can tell there is no equivalent for `syncthing cli`. Perhaps `syncthing cli show connections` could be made to support an optional `--show-discovered` argument?

**Comment by AudriusButkevicius** [comment]
That is discovery packets observed over time, so this would only be accessible from the running instance I guess.

**Comment by imsodin** [comment]
Do we really need to discuss anything here? We have a cli, this is an operation that exists in our API, it wouldn't hurt to have it, at least someone wants it -> lets keep it as a feature request. If we get a ton of such requests, we can create an umbrella ticket "Implement rest api methods in the cli" and redirect new issues to that - but I don't see that happening for now.

**Comment by jwatt** [comment]
@acolomb Sorry, I missed your reply.

Yes, I would then like to use the cli to add the device, I think. I should actually run through a full setup though and get back to you if there's other unavailable functionality that would seem to make sense. I've just been a bit busy but I'll try to get around to that soon and let you know!

**Comment by jwatt** [comment]
To follow-up on the above, the main issue for me is lack of CLI support for making settings changes to existing devices and folders. (For example, to pause a folder.) I've filed #8060 to track that.
