### ISSUE TITLE
Add an option to send SNI to relay server

### ISSUE THREAD

**Issue by hbielenia** [syncthing/syncthing#8014]
The SNI issue is briefly discussed here, but without conclusion: https://forum.syncthing.net/t/sync-routing-to-multiple-instances-in-kubernetes/17361

Sending SNI would make it possible to host relay server along with other processes using it's port, which naturally matters most when hosting it on port 443. Using relay server on HTTPS port helps with obfuscating the traffic since both protocols use TLS.

To me, it's a matter of choice between one solution or another where both potentially give up a (very little) part of user's privacy. Assuming I don't wanna spare a separate server on relay, either I choose to host relay server on different port - which will make the traffic more visible, or to host it under a separate hostname, which then needs SNI to distinguish it and forward the traffic. Currently, changing the port is only option, while I would prefer to use multiple hostnames setup. Thats because I can pick an innocent looking hostname and pretend it's just an HTTPS endpoint, while TLS-encrypted traffic on port other than 443 is immediate red light to anyone who's eavesdropping.

**Comment by calmh** [comment]
I don't think this needs an option even, we should just do it as it's a normal TLS connection to a server and there's no expectation I can see that the name used to resolve the server should be secret.

A notable thing here is that all relays handed out by the relay pool are IP addresses and thus don't get SNI regardless of what we do; this would only ever affect manually configured relays.
