### ISSUE TITLE
Provide a way to preset GUI credentials with password hashing

### ISSUE THREAD

**Issue by acolomb** [syncthing/syncthing#8021]
Syncthing's default configuration does not have GUI authentication set up.  As noted [on the forum](https://forum.syncthing.net/t/the-danger-zone-free-files-compliments-of-this-ignoramus/17378/7) and in https://github.com/SynoCommunity/spksrc/issues/4875, it would be advisable to set a user / password combination before first starting Syncthing.  Especially on headless systems (like NAS) which need to have a liberal GUI listen address and therefore just installing and starting Syncthing would open a big security hole without authentication.

Presetting the credentials is possible in principle through a barebones `config.xml`, but in practice turning a password into a bcrypt hash is not always easy.  Neither should any external tooling depend on Syncthing's internal config XML structure.

The suggestion is to add a new `syncthing cli` command, or a separate binary altogether, which accepts a user name and password from the command line or standard input.  It then patches that into a specified `config.xml` file, re-using the internal configuration handling code.  Ideally it should also indicate through its exit code whether the config file is valid and normalize it when writing.

The existing method through the REST API cannot be used for this, as it needs to happen before the background service is started.  At least with the SPK packages for a Synology NAS, possibly also in other deployment scenarios.

**Comment by AudriusButkevicius** [comment]
I'd be wary of passing passwords on the commandline, given things like bash history etc. Reading it from stdin would be better.

**Comment by acolomb** [comment]
> I'd be wary of passing passwords on the commandline, given things like bash history etc. Reading it from stdin would be better.

That is a first-class consideration I have already implemented in my prototype.  Will make a PR when it's cleaned up.

**Comment by acolomb** [comment]
I'm a little bit stuck in my implementation when trying to actually modify the config.  If there is no file yet, `syncthing.DefaultConfig()` gives us a `config.Wrapper`.  I would do the same when it does exist by calling `config.Load()`.  But that wrapper doesn't really work for modifications unless I start its `Serve()` method with a new context etc.  That seems overly complicated all in all, just to open an XML file, modify two tags, and write it back.  Note this subcommand is just a simple, single-threaded script context where there are no services running and thus no Committers to take care of.

Do you think using the `ReadXML()` / `WriteXML()` functions directly for the generate subcommand would suffice?  Or is there a simpler way to actually make use of the `config.Wrapper`?

**Comment by calmh** [comment]
Getting a wrapper, stating it's serve method and doing modification seem the cleanest solution to me.

**Comment by acolomb** [comment]
I'm waiting on #8028 to get merged so I can rebase my branch for this and make a PR.  Any chance that can happen before .rc1?
