### ISSUE TITLE
Please integrate the feature selective sync from resilio sync

### ISSUE THREAD

**Issue by dmuiX** [syncthing/syncthing#8026]
### Include required information

Would be so nice to have this feature. Selective sync enables to sync just a part of a folder to my device. I sync for example my documents folder from my notebook to my smartphone. There are many documents, that I just don't need every day on my smartphone, stuff thats just for the archive. But I want to be able to download it temporarily. 

This is the only feature I miss in syncthing, which resilio has.

Please be sure to include at least:

 - what problem your new feature would solve
 - how or why you think it is generally useful (i.e., not just for you)
 - what alternatives or workarounds you considered

**Comment by imsodin** [comment]
This is already possible based on patterns: https://docs.syncthing.net/users/ignoring.html

For a GUI representation/control and other improvements, see https://github.com/syncthing/syncthing/issues/4729 and https://github.com/syncthing/syncthing/issues/2491

**Comment by dmuiX** [comment]
Have you read what they wrote here?:
https://github.com/syncthing/syncthing/issues/7349

> totally agree @LoginByCall
> 
> IMO there's a fundamental disagreement on how "partial sync" (or "selective sync") should work. for me, it should work exactly how you outlined it. keep seeing comments from core maintainers pointing to ignore patterns. I can't wrap my head around how ignore patterns actually gives you partial or selective sync for the exact same reason you outlined above. it gives you "something" but not selective sync using the definition that I know
> 
> I guess better said: for anybody that has used dropbox selective sync OR resilio selective sync, I would dare say is really obvious that ignore patterns is NOT the solution to this problem, not even in the ballpark. but that assumes that one has used selective sync from other solutions and they would like to see something similar here.
> 
> now if one has NOT used selective sync before and they come fresh to the problem, yes...I can see you would think that ignore patterns would get you what you want.

I think it is like that. With ignore patterns I define what I want and what not. This is not really convenient as it is in resilio-sync. There I can click on the file and it is getting downloaded. How is this implemented in syncthing?

**Comment by imsodin** [comment]
> How is this implemented in syncthing?

It's not currently implemented, see my previous reply:

> For a GUI representation/control and other improvements, see #4729 and #2491

And just to pre-empt the question: There's no plans (I am aware of) to implement it - contributions highly welcome.
