### ISSUE TITLE
Syncthing fails to load javascript when using reverse proxy behind a uri path

### ISSUE THREAD

**Issue by nathanmerrill** [syncthing/syncthing#8032]
### Include required information

I have a reverse proxy setup so that `mywebsite.com/syncthing/` proxies to `localhost:8384`.

When I visit the webpage, the HTML request returns a 200.

However, in the HTML, many of the javascript assets have a path like `syncthing/core/module.js.  This causes the browser to attempt to access the assets at `mywebsite.com/syncthing/syncthing/core/module.js`.  This fails, and the entire page essentially fails to render.

Using Syncthing version 1.18.2 (no related bug fixes between this version an 1.18.3 as far as I can tell).
Firefox version 93.0
Caddy 2.4.5 as my reverse proxy.  Config below:

```
handle_path /syncthing/* {
    uri strip_prefix /syncthing
    reverse_proxy http://localhost:8384
}
```

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by nathanmerrill** [comment]
This is not a support request: Syncthing (as far as I can tell) does not support a custom uri path, as it makes requests to syncthing/syncthing/core/module.js
