### ISSUE TITLE
Syncthing stops synchronizing all changes when there is an invalid file character

### ISSUE THREAD

**Issue by thomasvs** [syncthing/syncthing#8033]
### Does your log mention database corruption?

If your Syncthing log reports panics because of database corruption it is
most likely a fault with your system's storage or memory. Affected log
entries will contain lines starting with `panic: leveldb`. You will need to
delete the index database to clear this, by running `syncthing
-reset-database`.

### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using
 - syncthing v1.12.1-ds1 "Fermium Flea" on linux
 - syncthing v1.18.3 on android

 - what happened,

syncthing stopped synchronizing all changes when it was stuck on one file with a colon in its name, which is invalid on Android

 - what you expected to happen instead, and

all other changes should still be synchronized, one error in one file shouldn't block everything else from syncing.

 - any steps to reproduce the problem.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by thomasvs** [comment]
Hm, why do you think that? I'm not asking for help on how to fix it - I changed the filename and things started syncing again.  I'm pointing out that it's most likely a bug or an unintended misfeature that everything stops syncing when one file has an unsupported name.

As a developer, I know the value of coding defensively and making sure that one error doesn't propagate to the rest of the system.

**Comment by AudriusButkevicius** [comment]
I don't think that there is anything in syncthing that stops everything because of one file, so this needs more understanding in the forum.
