### ISSUE TITLE
Files dissappear after renaming them from lowercase to uppercase

### ISSUE THREAD

**Issue by es20490446e** [syncthing/syncthing#8034]
### How to reproduce

Rename a file from lowercase to uppercase, or vice versa.

### Result

Sometimes the file will be deleted by Syncthing.

**Comment by AudriusButkevicius** [comment]
Can you reliably reproduce it? Again, there is not enough details here to be a useful ticket, no versions of syncthing on either side, filesystems, operating systems etc, hence I feel we should close this.

**Comment by tomasz1986** [comment]
Just in case Android is involved, this could be the same problem as https://github.com/syncthing/syncthing/issues/7974.

**Comment by AudriusButkevicius** [comment]
I assume that is the case, hence closing in favour of that one.
