### ISSUE TITLE
Hangs when syncing symbolic links

### ISSUE THREAD

**Issue by es20490446e** [syncthing/syncthing#8035]
### How to reproduce
On Unix, create a symbolic link with the command: ln -s [target] [linkName]

### Result
Sync will hang on that file.

**Comment by AudriusButkevicius** [comment]
What do you mean by hang? There is not enough details here to consider this a workable ticket. I suggest you start a thread on the forum to better explain your issue.

**Comment by es20490446e** [comment]
Hang means that the sync never finishes.

Syncthing 1.18.2.

I'm not interested in socializing on forums.

**Comment by es20490446e** [comment]
[computer.log](https://github.com/syncthing/syncthing/files/7498434/computer.log)
[mobile.log](https://github.com/syncthing/syncthing/files/7498435/mobile.log)

**Comment by rasa** [comment]
The mobile.log has
```
2021-11-08 16:07:40 sendreceive/mo9mp-yxlxk@0x4000b16a80 new error for Projects/up: symlink create: 
symlink ../ /storage/emulated/0/Documents/Projects/up: permission denied
```
Is the mobile system the one that 'never finishes'?

If so, the issue is one of file permissions. Is the "Ignore permissions" option set or unset on the computer and mobile systems?

What version(s) of ayncthing are you running on these systems?

**Comment by es20490446e** [comment]
If I do:
- Set the affected folder to ignore permissions in both devices.
- Restart Syncthing in both devices.

Syncthing is still incapable to sync the link.

Versions are:
- Computer: 1.18.2, Linux (64-bit Intel/AMD)
- Mobile: 1.18.1, android (64-bit ARM)

**Comment by imsodin** [comment]
As Audrius wrote, please open a topic on the forum. That has nothing to do with sozialising (unless you wanted to), but with forum having a lot more eyes and friendly people on it than the issue tracker.
