### ISSUE TITLE
Consider using reliable UDP for block transfers

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#804]
This is a long-shot, over-engineering and is not required, but a interesting topic nonetheless which could be a unique selling point to Syncthing.

Some interesting ideas can be found [here](http://stackoverflow.com/questions/107668/what-do-you-use-when-you-need-reliable-udp)

I seems that the easiest one to adopt would be [UDT](http://udt.sourceforge.net/) with bindings already available for most languages.

**Comment by dembach** [comment]
http://plan9.bell-labs.com/sources/plan9/sys/src/9/ip/rudp.c

**Comment by dembach** [comment]
i am really in need of a firewall hole punching solution , due to a bad companies firewall solution.

please consider this for a shorter term solution , please

**Comment by jpjp** [comment]
That file has a different license. Is it compatible? If not posting could be a bad idea.

**Comment by calmh** [comment]
RUDP isn't usable as is, unfortunately. However I've recently fixed https://github.com/calmh/dst to the point where it seems usable, so will be making some experiments with that soon.

**Comment by dembach** [comment]
Maybe I can try that also at my company to see if the hole punching works for me ,  too

Hope you are going to run the builds for Windows and Linux ...got no go on Linux yet

Cheers

Markus

**Comment by calmh** [comment]
@dembach What do you mean?

**Comment by dembach** [comment]
I would love to get a syncthing with the new protocol and test it

**Comment by Korkman** [comment]
@calmh +1 for the effort moving the protocol to UDP and hole punching. You're on the right track there, it will make connectivity far better, automagic for most people.

**Comment by patrickwolf** [comment]
+50 this would be awesome to get working!

**Comment by brenthuisman** [comment]
+1

**Comment by Janhouse** [comment]
+1

**Comment by michalliu** [comment]
+1 :+1:
