### ISSUE TITLE
Unable to scan /tmp

### ISSUE THREAD

**Issue by hflsmax** [syncthing/syncthing#8040]
### Include required information

I have `v1.18.4, Linux (64-bit Intel/AMD)`, and I add folder `/tmp`. Syncthing is not able to find any files in /tmp, but there're bunch of files there. I tried to create/delete files in /tmp but the log doesn't show anything.

I can confirm that other folders work fine.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
