### ISSUE TITLE
Missing healthcheck in official Docker image?

### ISSUE THREAD

**Issue by jwillikers** [syncthing/syncthing#8045]
On the latest v1.18.4 Docker image, should the healthcheck be enabled out-of-the-box?
When I try to run the official image from Docker Hub with Podman, the healthcheck doesn’t appear to be there.
I’m able to get the healthcheck by building the image locally from the Dockerfile, though.

Original Podman issue: containers/podman#12226

**Comment by calmh** [comment]
It looks active to me.

```
% docker run -it --rm syncthing/syncthing:1.18.4
...
[UHVJL] 20:55:27 INFO: My name is "0627293d6ccf"
```

```
jb@kvin:~ % docker ps | grep syncthing
0627293d6ccf   syncthing/syncthing:1.18.4                             "/bin/entrypoint.sh …"   40 seconds ago   Up 39 seconds (health: starting)   8384/tcp, 21027/udp, 22000/tcp, 22000/udp                                              agitated_kare
jb@kvin:~ % docker ps | grep syncthing
0627293d6ccf   syncthing/syncthing:1.18.4                             "/bin/entrypoint.sh …"   About a minute ago   Up About a minute (healthy)   8384/tcp, 21027/udp, 22000/tcp, 22000/udp                                              agitated_kare
```

I don't know what podman is.

**Comment by jwillikers** [comment]
Podman is a Docker-compatible container runtime, so it should behave the same as Docker does... but in this case I think it's a Podman issue.
Thanks for checking on this for me.
I probably shouldn't have been so lazy so as not to check in a VM myself in the first place.
Now that I have, I see its working with Docker the same as your output.
I'll close this issue once I confirm its an issue in Podman.

**Comment by AudriusButkevicius** [comment]
I'll close now, but ping if we need to reopen.

**Comment by jwillikers** [comment]
@calmh @AudriusButkevicius Would either of you or another member of the Syncthing project be able to respond to the Podman maintainers in containers/podman#12226, specifically [this question](https://github.com/containers/podman/issues/12226#issuecomment-963622762)?
They have some questions related to how the Docker image is built.
Much appreciated!

**Comment by calmh** [comment]
The build step is

```
docker buildx build \
	--platform linux/amd64,linux/arm64,linux/arm/7 \
    -f Dockerfile.buildx \
    ${tags[*]}
```

after doing some setup magic to get buildx up and running. I have no idea about the inner workings of Docker (or buildx) so I'll leave that for them to figure out. :)
