### ISSUE TITLE
syncthing uses too much memory on windows

### ISSUE THREAD

**Issue by qyloxe** [syncthing/syncthing#8048]
### Include required information

 - which version of Syncthing and what operating system you are using

![image](https://user-images.githubusercontent.com/467508/142372999-307e5115-f34a-4066-a43d-c219cf8d1485.png)

Windows 7 x64, 8GB RAM

 - what happened,

![image](https://user-images.githubusercontent.com/467508/142373077-e2051a3f-bc31-45a1-80ea-a9182e726a80.png)

![image](https://user-images.githubusercontent.com/467508/142373101-c5b2ad65-c564-439a-b6c1-bbdaa981202c.png)

![image](https://user-images.githubusercontent.com/467508/142373132-6e5b2188-9332-4f2d-8079-1b126db9ed66.png)

 - what you expected to happen instead, and

It should use no more than 200-300 MB of RAM. Maybe even 400 MB, but not 4 GB. When it tried to synchronize 50GB file, the system hung up even.

 - any steps to reproduce the problem.

The whole drive with lots of files is synced. At first, there were even files at 50GB range, but it caused system hangs.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by rasa** [comment]
So consuming 4+ GB of core is to be expected? If not, then I would argue this is a valid bug report, and not a support request.

**Comment by AudriusButkevicius** [comment]
This can be for a number of reasons, the cause first needs to be understood on the forums.

The report doesn't explain whats causing the usage so there is nothing immediate to address.

For all that I know the user might have tweaked the default settings and set syncthing to have 4gb buffers available.

**Comment by qyloxe** [comment]
This is preliminary report, I could help in diagnostics.

There were no tweaks in settings.

As this issue is closed, I will post more information on the forum as suggested. Hoping to find the root cause, because syncthing is one of the best piece of software I've seen in looong time.
