### ISSUE TITLE
SyncThing needs to drop unsupported files, especially after they've been deleted from the sync source...

### ISSUE THREAD

**Issue by colemickens** [syncthing/syncthing#8049]
Syncthing regularly gets stuck on weird unix-y files, which is fine. The frustrating part is that it keeps them in the sync queue, even after I've removed them from the source filesystem.

The only resolution is to remove the directory from the sync source and re-add it (this is fortunately non-destructive other than some read cycles).

**Comment by AudriusButkevicius** [comment]
Some.more information, i.e, versions, operating systems involved, examples of failures, etc, would be useful, as the current issue leaves a lot to the imagination of the reader.

**Comment by colemickens** [comment]
Repro (there are others, but this was today's):

1. Install `jj` from: https://github.com/martinvonz/jj
2. Create a git repo and then some jj repos backed by the git repo.
3. Do this inside a folder syncthing is configured to sync

You will start accumulating sync errors, but maybe not realize it.

Then decide you don't want mix experimental VCS and Syncthing and just delete every single thing you've added since the beginning of this process.

Then you finally check Syncthing and see there's a pile of sync errors that are all in directories that no longer exist.

In this case every machine involved in the sync process is running NixOS and SyncThing version v1.18.3.

I can repro later when I bounce back to `jj` and post a snippet of log after doing these steps again.

**Comment by colemickens** [comment]
I'm wondering two things:

- if SyncThing has not written a change to any destinations, and then the source of the change is deleted... do both of those changes "go out" or do they get coalesced and eliminated?
- same question, but maybe the write only hit one destination - that would certainly seem like a more contentious situation where you're sort of split brain and I can see maybe why Syncthing would want to replicate that write? But still, feels like it should be ultimately eliminated by the deletion of the original source dir.

**Comment by calmh** [comment]
I'm not seeing any actual errors or examples of stuck things here that we could fix. If you want to ask general questions about syncing mechanisms the forum is the better place for that.

**Comment by AudriusButkevicius** [comment]
Closing for now.

I think this should first be understood on the forums.

**Comment by colemickens** [comment]
I don't, that's why I filed an issue for a bug that I've seen repro multiple times across my machines, that I can repro at will again, that seems to generalize to a common enough issue that I thought it would pop out as an obvious gap in the syncing algorithm since it seems obvious to me to drop sync changes to a target that no longer exists or a dir that no longer exists.

But sure, I'll reopen with a log.
