### ISSUE TITLE
Display a warning when the ignore delete option is enabled

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing#8050]
A support request about weird behaviour just turned out to be caused by *the option that should not be used*, and the requested didn't think of that. Might happen a lot. I think we should have a column in the expanded folder with a warning like "Folder has the `ignoreDeletes` option enabled, which can result in inconsistent status indication. Using it is not recommended.".

**Comment by tomasz1986** [comment]
I'd personally suggest to keep the message short (i.e. similar to the current "reduced by ignore patterns"). I think even a simple one like "affected by ignoreDelete" (in red colour?) or something in this manner would be enough to indicate that something is up, and it would definitely be enough to diagnose the problem when the user uploads such a screenshot to the forum.

A lengthy message will likely be too annoying for those who use the setting on purpose.

**Comment by anurnomeru** [comment]
By the way, after the device has enabled the deletion protection, the synchronization progress of other devices will show that the remote progress is 95%, which is very strange。 =。 =

**Comment by tomasz1986** [comment]
> the remote progress is 95%, which is very strange. =。 =
This is normal. The "95%" is a hardcoded number. For example, the same happens with a receive only folder, when there are local additions on one side.

**Comment by imsodin** [comment]
Please use the forum thread for this discussion - thanks.

**Comment by 1024mb** [comment]
This may be offtopic but I want to ask.

> Using it is not recommended.

Why using the ignore delete option is not recommended? If I want to one-way sync a folder I need to use it. Why wouldn't you recommend using it? I'm missing something here?

**Comment by imsodin** [comment]
Please search the forum, there are already discussions about this. And if you still have questions then, open a new topic there: https://forum.syncthing.net
