### ISSUE TITLE
Syncthing silently rejects STGUIAPIKEY if it contains a newline

### ISSUE THREAD

**Issue by osilkin98** [syncthing/syncthing#8051]
## Version 
Syncthing version: 1.18.4
  
## Device
Red Hat Universal Base Image 8 running in Kubernetes
 
## What Happened
what happened: `STGUIAPIKEY` was passed a string which contained a newline character. Syncthing failed silently and generated its own API key (confirmed this by viewing requests to `/config` in the request log in my browser).
 
## What Should Happen
Syncthing should accept the key or error/warn that the key provided contained an invalid value, and that a new one was automatically generated.
 
## Reproducing The Error 
To reproduce the problem, `export STGUIAPIKEY="aHVudGVyMgo="'` and start syncthing. You can obtain the raw value of that base64 string by setting `var1=$(printf "%s" "aHVudGVyMgo=" | base64 -d)`, then running `curl -X GET -H "X-API-Key: ${var1}" --insecure https://localhost:8384`. This should result in a CSRF error. 

Note: The `config.xml` file that I am starting Syncthing with is a simplified file with many of the fields stripped out. I removed the `<apikey>` element from the `<gui>` config specifically so it could be parameterized using `STGUIAPIKEY`.

**Comment by calmh** [comment]
I think there are several misunderstandings here.

- Setting STGUIAPIKEY doesn't change what's in the config or what's visible in the GUI -- it effectively adds another API key that's also valid.
- You API key doesn't contain a newline, it's `aHVudGVyMgo=` verbatim -- Syncthing doesn't base64 decode the value. 
- Even if you did set STGUIAPIKEY to a value that actually contains a newline, you have no way of producing an X-API-Key header with a value that contains a newline, so it could never be matched. (Syncthing doesn't do entity expansion or similar on the header value.)
