### ISSUE TITLE
Allow for limiting number of simultaneous scans running

### ISSUE THREAD

**Issue by optoisolated** [syncthing/syncthing#8055]
Quite often, there will be multiple folders shared from the same volume, and simultaneous scans can overwhelm the underlying IO subsystem. Being able to limit scans to one shared folder at a time (or 2) or even limiting scans per underlying volume would be useful. 

At a minimum just being able to specify an integer of the number of scans to run at the same time would be great; just so it could be limited to one at a time, and then later on potentially controlling how many simultaneous scans per underlying storage location.

**Comment by imsodin** [comment]
There's `maxFolderConcurrency`, which limits the amount of folders in both scanning and syncing state: https://docs.syncthing.net/users/config.html#options-element

**Comment by optoisolated** [comment]
It might be worth while separating those two actions; scanning is entirely local and will be what overwhelms disk IO whereas the syncing will almost certainly be limited by bandwidth.
