### ISSUE TITLE
Syncthing changed modified times of whole folder 

### ISSUE THREAD

**Issue by clavelc** [syncthing/syncthing#8058]
Hi,

I used Syncthing to synchronize a large media folder between my laptop : 
`syncthing v1.18.4 "Fermium Flea" (go1.17.3 linux-amd64) syncthing@archlinux 2021-11-08 22:28:18 UTC [noupgrade]
`
and my android phone, running latest Syncthing from F-droid.

I had some trouble setting this up (I wanted the Android DCIM/Camera to be synced with an existing Images/Camera folder on the laptop), and ended up copying the files over to the phone first before setting Syncthing up. 
However on the first sync of two identical folders, Syncthing still did some syncing anyway, and ended up updating all last modified times on the computer... 

This is very inconvenient, as my backup script now recognizes the 20+ gb picture folder as new data and wants to copy them all over again to my backup storage..

Syncthing should not update modification times of files it does not copy. I am not even sure how this was even possible.

As a side note, I think my use case (synchronizing picture taken with a phone) seems hard to set up and is poorly documented for something that doesn't seem like a corner case.

Thanks very much for your work

**Comment by tomasz1986** [comment]
> I am not even sure how this was even possible.

I would bet you it's likely an Android's fault. The OS is known to mess timestamps.

Synching itself is supposed to preserve mtime.

**Comment by clavelc** [comment]
Very likely Android's fault, however the problem is that it was synced back to my laptop...

**Comment by calmh** [comment]
Syncthing copies modification times as well as content. If you set it up with existing data on both sides already it must consolidate those two views into one consistent set of data. If the only thing that differs are timestamps we'll pick the most recent. This seems as-designed to me.

**Comment by clavelc** [comment]
For anyone in the same situation, a quick fix is on the [Arch Forum](https://bbs.archlinux.org/viewtopic.php?pid=2005284#p2005284)
