### ISSUE TITLE
`syncthing cli config options uraccepted set -1` fails

### ISSUE THREAD

**Issue by jwatt** [syncthing/syncthing#8059]
Using syncthing v1.18.3 it doesn't seem to be possible to use the cli to disable usage reporting:

```
$ syncthing cli config options uraccepted set -1
Incorrect Usage: flag provided but not defined: -1

NAME:
   syncthing cli config options uraccepted set - Set the value

USAGE:
   syncthing cli config options uraccepted set [value]

CATEGORY:
   ACTIONS
flag provided but not defined: -1
```

**Comment by jwatt** [comment]
Looks like I can use `syncthing cli config options uraccepted set -- -1`. It seems like it would be helpful to mention that negative numbers will need to be passed in this way in the help output from `syncthing cli config -h`.

**Comment by jwatt** [comment]
Even more helpful would be if -1 would just be accepted. (Or if at least the error message could be customized for that case to help the user get it right.)

**Comment by calmh** [comment]
I think this is just how command line parsers work. It's not especially odd or different from how other programs work.

```
% touch -1
touch: illegal option -- 1
usage:
touch [-A [-][[hh]mm]SS] [-acfhm] [-r file] [-t [[CC]YY]MMDDhhmm[.SS]] file ...
% touch -- -1
% rm -1
rm: illegal option -- 1
usage: rm [-f | -i] [-dPRrvW] file ...
       unlink file
% rm -- -1
```
