### ISSUE TITLE
Conflict files are created when editing on only one client

### ISSUE THREAD

**Issue by t7ko** [syncthing/syncthing#8065]
I very often notice conflicts generated when I'm editing file on only one client -- another client is backup server, so definitely no edits happen there.

Saw this on different files -- plain text, images.  Examples:

* Open file in text editor, hit save, do some edits, hit save again => 'conflict' file is created.
* Folder creation using Explorer -- same problem: hit New Folder button, edit name, Enter => "New Folder" reappears.

Environment -- very basic setup, no fancy stuff:

* client 1 -- editor:
  * windows 10 on HP laptop
  * SyncTraizor 1.1.28.0
  * data stored on SSD
* client 2 -- backup server:
  * RPi 3B, Raspbian 10, headless
  * syncthing 1.18.3
  * data stored on USB-pluggable SSD, fs=vfat
* No other clients, only these two.
* Network -- both clients sit next to each other on one single router, so it quite fast.  Transfers go at 5+MB/s.

### Does your log mention database corruption?

No, it's not.  Sample conflict file name: plan.sync-conflict-20211128-182523-WWVXNPE.pdf

### Include required information

see above.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
