### ISSUE TITLE
Moving treated as deletion

### ISSUE THREAD

**Issue by github-account1111** [syncthing/syncthing#8066]
I'm using version 1.18.4 on Windows 10 in Edge Chromium and 1.18.3 on Android 12.

Moving files seems to be treated as copy with subsequent deletion.
If I enable IgnoreDelete on phone and move a file from one folder to another on computer, the phone will now have two copies of the file instead of mirroring the move, as if I copied the file first, then deleted it at the origin.

**Comment by bt90** [comment]
The ignore deletes option is a footgun. Turn it off and pretend that it doesn't exist.

**Comment by github-account1111** [comment]
But then how do I make it so I can delete stuff on my computer without it getting deleted on my phone?

Or the other around (aka Google Photos).

**Comment by AudriusButkevicius** [comment]
Thats not syncing, thats transfering from a to b.

That's not a usecase syncthing is made for.

**Comment by github-account1111** [comment]
That's also syncing, just one-way instead of two-way, because I still want deletes to propagate from the phone to the computer.

The problem is not with the ignoreDelete flag, but with how Syncthing treats moving.
As I said, it treats it like a copy-paste with subsequent delete, instead of actually moving the file.
The two are different, but are treated the same, and this is the side-effect.

**Comment by bt90** [comment]
The concept of an (atomic) move only exists if a single filesystem is involved. Everything else *is* copy&delete.

**Comment by github-account1111** [comment]
Oh if you're referring to the "move a file from one folder to another" part, I meant doing it within a synced folder. Like so:

Synced folder
|-Source folder
|   |-File
|-Destination folder

**Comment by AudriusButkevicius** [comment]
Syncthing doesn't do "one way". Its a hack we regret on supporting as it does not fit into the model.

Syncthing does moves as delete and create, if that doesn't work for you, there is not much that can be done.
