### ISSUE TITLE
New shared folder labels are displayed as empty in the Korean Web GUI

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#8067]
I'm not sure what the culprit may be, and I haven't got enough time for extensive testing at the moment, but I've had this issue since basically forever. Recently I've been setting Syncthing up on a lot of machines, and I must say that not being able to easily see the labels is quite cumbersome.

This only happens in the share folder popup. Once you click on the "Add" button, the label is present there. Also, it doesn't matter whether the label itself is in Korean or in Latin. It's the GUI language itself set to Korean that causes the issue.

![image](https://user-images.githubusercontent.com/5626656/144697197-49f374dc-2c04-4b82-b790-aa9cea0d921f.png)

**Comment by calmh** [comment]
The folder label placeholder has the wrong casing in the translated string, gui/default/assets/lang/lang-ko-KR.json line 440 (I can't easily get a permalink on mobile apparently).

**Comment by tomasz1986** [comment]
Wow. I should've check the translation strings first. I've now fixed it on Transifex, so I guess the issue can be closed.
