### ISSUE TITLE
Request: show pending devices/folders in CLI

### ISSUE THREAD

**Issue by DanielBarczyk** [syncthing/syncthing#8068]
Currently it is not possible to see pending devices and folders using the CLI, so users have to use the graphical interface.

It is already possible to add new devices and folders using only the CLI, so it would be convenient to add the option to list pending devices and folders in the CLI as well.

Since there is an API endpoint to show pending devices/folders, I see no reason not to have this functionality in the CLI.

Proposed solution: add subcommands
`syncthing cli pending devices`
`syncthing cli pending folders`

**Comment by acolomb** [comment]
Interesting addition.  Sorry I'm short on time right now but will review your PR as soon as possible.
