### ISSUE TITLE
`--reset-deltas` as an API method

### ISSUE THREAD

**Issue by jtagcat** [syncthing/syncthing#8070]
https://docs.syncthing.net/users/syncthing.html?highlight=reset%20delta#cmdoption-reset-deltas

as `/rest/system/resetdeltas` ~~/ `reset-deltas` / `reset_deltas`~~

I should be capable of implementing it, current blockers:
 - [ ] confirm `resetdeltas` as POST method is fine
 - [ ] is the operation possible after startup (or close issue)?
 - [ ] is it possible to partially reset? only a folder/device (like in [/rest/system/reset](https://docs.syncthing.net/rest/system-reset-post.html))
 - [ ] other things competing for time

**Comment by AudriusButkevicius** [comment]
This is not an operation that can be done while syncthing is running.

In general, this should be only run as a last resort and usually means we've got a bug or there is bad historic data in the index, and should only be used in a very specific set of scenarios, so should not be easily accessible.

**Comment by jtagcat** [comment]
notes to self for later debugging:
1. device a (send-only) and b (recv-only) are synced
2. dev b is nuked
3. dev c replacing dev b, using already downloaded data, rescan
4. pause midway right after adding the folder, global data is shown smaller on dev c as on dev a; `--reset-deltas` does not work, removing and readding folder works
