### ISSUE TITLE
Windows binary no longer signed

### ISSUE THREAD

**Issue by jho1670** [syncthing/syncthing#8072]
Using Windows binaries on Windows 10.

Previous Windows binaries were signed with "Kastelo AB" sha1/sha256 signatures.

My machines got an update to 1.18.5.0 - they appear to be SFX GZIP archives, and are no longer signed. Is this expected and working as intended?

A quick search didn't show any announcements on this change; I confess I'm not sure if this is a recent change or not.

Thank you for your help!

**Comment by calmh** [comment]
It's the classic "certificate expired while nobody was minding it" thing. I'll fix, for next release.

**Comment by HidYn** [comment]
Thanks for all the hard work. Just to bump as the latest release doesn't appear to be signed either.

**Comment by bt90** [comment]
https://forum.syncthing.net/t/syncthing-v1-18-5-windows-exe-not-signed/17702/4

**Comment by jho1670** [comment]
Is this wedged now? Each update causes all of my clients to drop offline until I allowlist - this is painful because the update happens silently each time.

**Comment by calmh** [comment]
Would you believe it's still in progress? If you think that's ridiculous I can only agree. The code signing CA business seems ripe fore some disruption.

**Comment by calmh** [comment]
Happy days, there is now a new certificate in place. Next release 1.19.2 will be signed properly again.

![Screenshot 2022-03-09 at 10 07 28](https://user-images.githubusercontent.com/125426/157409509-7361afa3-fcb7-403a-bbc2-d5d9aa07c7d2.png)

**Comment by hj-collab** [comment]
> Happy days, there is now a new certificate in place. Next release 1.19.2 will be signed properly again.
> 
> ![Screenshot 2022-03-09 at 10 07 28](https://user-images.githubusercontent.com/125426/157409509-7361afa3-fcb7-403a-bbc2-d5d9aa07c7d2.png)

Is it possible for you to share the compiled exe right away? We will whitelist the signature in WDAC/Applocker before the release of next version. Thank you!

**Comment by jho1670** [comment]
https://github.com/syncthing/syncthing/releases/download/v1.19.2-rc.1/syncthing-windows-amd64-v1.19.2-rc.1.zip doesn't contain a signed binary, so these screenshots must be from a different binary.
