### ISSUE TITLE
Advice：the identification of folder equivalence

### ISSUE THREAD

**Issue by polar01bear** [syncthing/syncthing#8073]
### Problems & why
when a subfolder is renamed in the monitored folder, the software will think that the **old subfolder and its content** are **deleted**, and the **new subfolder** with the same structure and content is **added**. This will not only consume a lot of traffic and bandwidth, but also be time-consuming and laborious, and introduce unnecessary pollution in file version management.

### advice
In view of the **renaming** phenomenon in the file structure, the **judgment of the equivalence** of the old and new file structures is added. If the equivalence judgment is difficult to achieve, the software can first provide the renaming function, and **mark** before the renaming, after the renaming of the marked file structure to perform the judgment **that the equivalence is true** .

**Comment by imsodin** [comment]
Efficient handling of renamed/moved files should happen, however there can be cases where it doesn't work. There's different mechanisms involved in detecting renames and "not re-transferring between devices", some background info can be found in the docs, more details may be found searching the forum:

https://docs.syncthing.net/users/faq.html#is-synchronization-fast
https://docs.syncthing.net/users/syncing.html

If you'd like to investigate what exactly happens in your case, please open a thread on the forum - https://forum.syncthing.net/. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
