### ISSUE TITLE
Add after-'Sync finished' function

### ISSUE THREAD

**Issue by Hemingway2003** [syncthing/syncthing#8075]
Hi,

I have 2 server and they need to sync data  seldom, but due to the big size of data, 
when syncing, I must take care and wait for finishing. It cost me a lot time.

So if it's possible to add a function: I can run a shell cmd after sync finished?

Thanks very : )

**Comment by AudriusButkevicius** [comment]
Sadly no.
You should just use the rest API to get this information/react to changes.

**Comment by imsodin** [comment]
See https://github.com/syncthing/syncthing/issues/7849
