### ISSUE TITLE
Stopped syncing / Disconnected Device

### ISSUE THREAD

**Issue by acressman** [syncthing/syncthing#8080]
Hello,

One of our Remote Devices recently became disconnected.  We have tried restarting the servers on both sides and also restarting SyncTrayzor.  On the disconnected Device's side they are getting the following error:

[Y5GOJ] 13:36:43 INFO: listenerSupervisor@dynamic+https://relays.syncthing.net/endpoint: service dynamic+https://relays.syncthing.net/endpoint failed: Get "https://relays.syncthing.net/endpoint": dial tcp 82.196.13.137:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

He pinged the IP, but did not get a response.  Any help with resolving this will be greatly appreciated.  Please let me know if there is something we should try.

Thanks,
Andy

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by acressman** [comment]
Thanks, my mistake.
