### ISSUE TITLE
Under linux, unable to share folders that are mounted on the root filesystem

### ISSUE THREAD

**Issue by damoclark** [syncthing/syncthing#8081]
### Include required information

Please be sure to include at least:

 - Software versions?
Syncthing v1.18.5, Linux (64-bit Intel/AMD) - Ubuntu 20.04 LTS & Centos 7

 - What happened? 
Getting errors in log indicating that it is unable to create directories or delete files with the message:  'read-only file system' when remote changes are being applied locally
 
- What you expected to happen instead?
Mount options along with file permissions and ownership confirm that syncthing should be able to write changes to the file system

 - Any steps to reproduce the problem
1. Create a folder share to a folder that exists on the root file system (i.e. mounted at / ).  
2. I shared the folder `/usr/local/src` which is part of the root file system.  
3. All files and directories are owned by my syncthing user process (including `/usr/local/src` itself)
3. On creating the shared folder, the first error will be that syncthing is unable to create the '.stfolder' directory citing that the file system is read-only.  
4. I created the '.stfolder' directory manually using the same user account at the command line.  
5. Then after indexing the directory structure, any remote changes that flow through and have to be written locally generate the same 'read-only file system' error message.

If I perform a bind mount to `/usr/local/src` and specify the target of that bind mount as my shared folder, everything works fine. (e.g. bind mount `/usr/local/src` to `/home/user/src` and share `/home/user/src`, everything works as expected:

```bash
sudo mount --bind /usr/local/src /home/user/src
```

If I share a folder mounted on any other file system mount point, everything works as expected.

I am wondering whether it is a bug in a go library that is being used by Syncthing, rather than a bug in Syncthing?  The error string that is output in the logs does not exist in the syncthing code-base (I searched on github).  But it does exist in the syncthing binary.  

```bash
strings syncthing | grep 'read-only file system'
```

I have seen other unresolved reports on the forum with this error message, and I suspect, at least for some of them, that this might be the underlying cause.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
