### ISSUE TITLE
Device ID should be read-only and "nearby devices" should be hidden when adding a new pending device

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#8083]
1. On Device A, add Device B as a new remote device.
2. On Device B, click the "Add" button on the pop-up asking to add a new device.
3. The ID of Device A is automatically filled in, but at the same time it is also listed below under "you can also select one of these nearby devices".

I think that either the language should be changed (as currently it suggests that the ID below and the ID above belong to different devices despite being actually identical), or the ID listed below should automatically be hidden if the exact same ID is already filled in in the input field above.

![image](https://user-images.githubusercontent.com/5626656/147229223-9a8fadee-440e-4d7f-9583-f50da0c73a91.png)

**Comment by imsodin** [comment]
I think the entire section should be hidden if the dialog was opened by clicking "Add" on an "device invitation banner".

**Comment by tomasz1986** [comment]
> I think the entire section should be hidden if the dialog was opened by clicking "Add" on an "device invitation banner".

I have changed the title to do just that (plus make the ID read-only).
