### ISSUE TITLE
Syncing to a folder with ACLs fails silently

### ISSUE THREAD

**Issue by myyra** [syncthing/syncthing#8085]
I'm running Syncthing on TrueNAS Scale (v1.18.5, Linux (64-bit Intel/AMD)), with the synced folder pointed to a dataset with NFSv4 ACL enabled. The error also seemed to happen on normal TrueNAS (FreeBSD based).

All the files sync fine to the temporary files, but sync progress is always at 0%, and when everything has been copied over, the sync is stuck without any error logs. Filesystem debug logs shows a bunch of `ItemFinished map[action:update error:0xSOMETHING` messages. I had a hard time telling whether they were errors because there was no message and only a pointer.

Setting the ACL type to "Off" fixes it, as did ignoring permissions (which is quite expected).

Maybe this is a case where I should set Ignore Permissions, but some errors would be nice, as I didn't think it was the case since there were no permission errors (I've had those as well).

**Comment by imsodin** [comment]
Are you saying the sync never finishes? It's normal that errors get reset and thus not displayed when a sync is ongoing. If there is an error syncing, it should be logged though. If that's indeed not the case, please enable `model` debug logging and provide the logs from an entire sync cycle.

Also I can't find any logging with `ItemFinished` except for the events debugging logging when emitting said event. Please post the full log line including the filename/linenumber.

**Comment by myyra** [comment]
Yes, the syncing does not finish even after copying all .tmp files. It toggles between Syncing at 0% and Preparing to Sync.

I tried to find some debug logging that would show something helpful, did not realize `model` was it, unfortunately. I have since switched off the ACL completely since I needed the instance running and didn't have time to debug it further, so I can't send better logs for now. Sorry about that.

**Comment by imsodin** [comment]
Ok, then lets close this as there's nothing to action here. If you need further assistance or discover more information, please don't hesitate to open a topic on https://forum.syncthing.net. Once there's enough information/a reproducer for a bug, a targeted/actionable github issue can be opened again. Thanks.
