### ISSUE TITLE
Add command line option to set initial state of setLowPriority config option

### ISSUE THREAD

**Issue by Bill-Stewart** [syncthing/syncthing#8087]
It looks like when Syncthing generates its initial `config.xml` file it defaults to `<setLowPriority>true</setLowPriority>`. It would be helpful if we could have a command-line option (e.g., `--no-process-priority`) to set an initial state of `false` so the launching process can decide for itself. Thanks!

**Comment by calmh** [comment]
There are many config options, I don't think this one is special enough to deserve it's own command line flag.

**Comment by Bill-Stewart** [comment]
So I think there is a valid use case for this. An installer could give the user the option to decide on a process priority, but right now it will be disregarded it by default. If we have a command-line option (or an environment variable) for Syncthing not to set priority by default, then the user's preference isn't ignored. As it stands now, the user must manually edit `config.xml` after running Syncthing at least one time and then stopping it. (An installer can't set the preference before starting Syncthing for the first time, because `config.xml` doesn't exist yet.)

**Comment by calmh** [comment]
An installer can do what it needs to, including generating a base config.xml. You're essentially arguing for every config default being command line configurable, which I don't think scales or is a good idea in general.

**Comment by Bill-Stewart** [comment]
Ah - so if `config.xml` doesn't already exist, we can do a `syncthing generate` and then modify `config.xml` right afterwards. That will work; thanks!
