### ISSUE TITLE
Error on folder tmp: folder marker missing (this indicates potential data loss, search docs/forum to get information about how to proceed)

### ISSUE THREAD

**Issue by NuoMinMin** [syncthing/syncthing#8088]
被同步机子重启后同步一半的文件没有继续同步，且弹出窗口提示：Error on folder tmp: folder marker missing (this indicates potential data loss, search docs/forum to get information about how to proceed)

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
