### ISSUE TITLE
Syncthing Version issue

### ISSUE THREAD

**Issue by liberodark** [syncthing/syncthing#8089]
Hi,

When try to run syncthing have this issue : 

```
syncthing 
2021/12/30 15:10:02 Invalid version string "batocera-5.24-11341-g82dd87b7-dirty";
	does not match regexp ^v\d+\.\d+\.\d+(-[a-z0-9]+)*(\.\d+)*(\+\d+-g[0-9a-f]+)?(-[^\s]+)?$
```
You have any idea how to fix this issue ?

Related to : https://github.com/batocera-linux/batocera.linux/issues/5306
MK file : https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/utils/syncthing/syncthing.mk

Best Regards

**Comment by bt90** [comment]
IMHO this is not an upstream issue and should be fixed by whoever packages this.

**Comment by AudriusButkevicius** [comment]
Agreed. Raise it with the distribution maintainers.
