### ISSUE TITLE
Add option to automatically update Device Name to advertised name (even if not empty)

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#8093]
Currently, device names are "updated to the name the device advertises if left empty". However, once filled in, it doesn't seem that the name is ever updated again, even if the remote device changes its own name. This is problematic in large setups, where a single device name change requires manual intervention everywhere else to update the old name to the new one.

Our real world use case is that several computers have been moved across different offices, and now we are forced to manually go to each computer's Syncthing GUI and change the name by hand. The transition would be much smoother if the name could be updated automatically (and without needing to empty the field first).

I haven't found any alternative to emptying the name on all remote devices manually. If there is any better method, I would be very pleased to know.

**Comment by AudriusButkevicius** [comment]
I think there id an advanced config flag?

**Comment by tomasz1986** [comment]
> I think there is an advanced config flag?

I've skimmed through all config options, but there doesn't seem to be anything like that.

**Comment by AudriusButkevicius** [comment]
https://github.com/syncthing/syncthing/blob/main/proto/lib/config/optionsconfiguration.proto#L43

**Comment by tomasz1986** [comment]
Thanks!

This will do the job in our use case, although if I were to use the option in my personal setup, it would be nice to have something similar on a per device basis instead.
