### ISSUE TITLE
problems with autoupdate and company firewalls

### ISSUE THREAD

**Issue by warichnict** [syncthing/syncthing#8096]
![image](https://user-images.githubusercontent.com/57467778/148241160-38b2ac9c-d041-49f6-a907-b0d89c280b74.png)

the download process is hindered by a pesky firewall

please handle it in a way that opens an iframed browser of it that allows me to click yes once and then download it or by giving me url and location to safe it manually (like %temp%\synctupdate\ ) and a continue button, of cause do sanity checks like with pgp at all steps ;)

thanks

**Comment by calmh** [comment]
Yeah... I rather think that if auto upgrade is not going to work in your environment you should disable it and manage it yourself. In a corporate setup, probably using some config management setup.

**Comment by bt90** [comment]
> i think if there is an EOF error and not a signature check error its a probable security risk in your implementation...

The EOF error is caused by the download being blocked. The download is done via an encrypted HTTPS connection. So no security risk. It either works or it doesn't.

@calmh we could improve the warning though and maybe link to the download page.
