### ISSUE TITLE
No free space results in permanent out of sync

### ISSUE THREAD

**Issue by poiNt3D** [syncthing/syncthing#8106]
### Does your log mention database corruption?

No.

### Include required information

Syncthing v1.18.6 "Fermium Flea", Synctrayzor, Windows 10.

### Steps to reproduce:

1. Have a device which is out of disk space.
2. Add a file on another device
3. Folder now is "Out of sync": no free space
4. Get some free space on the device
5. Folder is still out of "Out of sync": no free space, restarting, rescanning doesn't help.

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by poiNt3D** [comment]
But i don't need a support, i resolved the issue by deleting the file on another device. But this behavior is clearly a bug.
