### ISSUE TITLE
gui: Links to documentation should point to matching version

### ISSUE THREAD

**Issue by acolomb** [syncthing/syncthing#8107]
Original discussion on the forum: https://forum.syncthing.net/t/version-specific-documentation-proposal/17858

The documentation links in some places of the Web GUI currently point at the single URL `https://docs.syncthing.net/...`.  That is a moving target however, documenting stuff that might not yet be found in the currently running version or missing features that have been removed / reworked in a subsequent release and already was removed documentation.  The envisioned solution consists of these base components:

1. [x] Create an archive of the built HTML result for every version tagged on [the docs source repository](https://github.com/syncthing/docs/).
2. [x] Serve them (statically) under some version-specific URL, e.g. `https://docs.syncthing.net/v1.18.6/...` or `https://docs.syncthing.net/...?version=v1.18.6`.
3. [ ] Alter the links contained in the Web GUI to include (part of) the version string for the running instance.
4. [ ] Add fall-back logic on the server side to redirect any unavailable version URL to the generic, up-to-date "main" version as it is now.
5. [x] Keep a JSON file on the server listing all available deployed documentation version builds.
6. [ ] Embed the version tag in built HTML docs to easily see what one is looking at.

An optional future refinement would be to add a version selector on the docs site to quickly switch between versions, e.g. when comparing API evolution.  But that is out of scope for this request.

**Comment by acolomb** [comment]
Historic versions starting from v0.11.10 are now available from https://github.com/syncthing/docs-pre-rendered and deployed to the web server.  Thanks @calmh!  I really like the solution with a separate repository.

It allows to add some sugar to each release after the fact.  For example some short HTML snippet for a version picker.  We can develop that once on the now-and-future docs HEAD version, then just copy it to all previous pre-rendered directory in that repo.

One more idea which I think will come in handy: Can you add an action during the deployment of that repo to leave the list of available docs versions in a JSON file, top-level?  Basically a directory listing of the latest deployed commit.  That would be easy to consume from a client-side version picker / redirect code (in contrast to getting the directory listing from the web server, which is interleaved with the rendered "main" HTML files).

**Comment by calmh** [comment]
https://docs.syncthing.net/versions.json now :)

**Comment by acolomb** [comment]
> https://docs.syncthing.net/versions.json now :)

There are quite a few (non-rc) tags missing in that list.  Which raises the question what version should be used in that case.  How smart do we want to make the fallback algorithm?

For example, when `v1.3.1` is requested, should we redirect to `v1.3.0` or `v1.3.2` or just to `HEAD`?  It seems strange jumping to the current main branch just because a minor point release in between wasn't tagged.

Of course we could add all missing tags and inflate the docs-pre-rendered repo accordingly... But as I'm just doing the redirector in JavaScript currently, it's quite possible to implement some kind of smart logic.  Current draft would result in this mapping:

https://acolomb.github.io/test-redirect-js/?version=v0.12.11-foo

**Comment by acolomb** [comment]
There is now https://github.com/syncthing/docs/pull/713 with a JavaScript-based redirector that interprets the `?version=...` query parameter.  It contains some heuristics to fail somewhat intelligently.  Feedback on that is still welcome, see the mentioned demo page for what will be mapped.

**Comment by acolomb** [comment]
> https://docs.syncthing.net/versions.json now :)

@calmh the JSON file is missing the pre-built `v0.14`, which is available though.

**Comment by calmh** [comment]
Yeah that's not a valid version, just a bad tag. Will rename the dir and/or tag to fix at some point.

**Comment by acolomb** [comment]
Note although this is closed, the two tasks on the documentation / server side still remain.

Falling back to the main docs.syncthing.net URL is not done yet, but any invalid path leads to a 404 page, linking back to the main landing page.  It would be great if an automatic redirect could be configured in Netlify, leading back to the landing page, but keeping the query parameters intact.  That way the redirect logic from syncthing/docs#713 could kick in and do its thing.

**Comment by calmh** [comment]
I don't follow. What fallback is it that we're lacking?

**Comment by acolomb** [comment]
Just being cautious, in case we introduce broken docs links in the GUI or elsewhere.  Probably not a big deal, as any historically published links won't change and we can make sure that future links correctly use the `?version=` parameter (as in #8108).  Just that a broken link https://docs.syncthing.net/does/not/exist?version=v1.19.1 leads you to the 404 page, and when clicking the contained link, you get the main page without the version redirect applied.

**Comment by acolomb** [comment]
Another case would be https://docs.syncthing.net/v0.0.0/users/config for example.  Would be nicer to get the same treatment as for https://docs.syncthing.net/users/config?version=v0.0.0 , instead of showing the 404 page.  But since we now mainly use the query parameter for versions, such URLs should not be generated / stored anywhere.

I guess my thinking was largely based on the original idea of using a sub-path "officially".  So never mind if you don't see any valid concern here.
