### ISSUE TITLE
Syncthing downloaded only half of files in a folder and claims it's up to date

### ISSUE THREAD

**Issue by kuba-orlik** [syncthing/syncthing#8110]
Syncthing  1.18.6-2 on Arch linux

I've shared a 400k file folder from a VPS via syncthing with my fresh local machine. The client downloaded only ~200k files and claims it's "up to date"

On the server:

![image](https://user-images.githubusercontent.com/2697916/149339161-45b197a9-5fe2-44a3-9b2b-8a96612a5dd7.png)

On the client:

![image](https://user-images.githubusercontent.com/2697916/149339422-5342fcd6-ace3-46f8-8398-aced293f78d9.png)

It's the second time Syncthing has done this with that folder

**Comment by kuba-orlik** [comment]
The server, however, seems to be aware, that the client didn't yet download everything 
![image](https://user-images.githubusercontent.com/2697916/149340155-d03b6fb0-6ebc-4473-ad20-238bae24a6a1.png)

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
