### ISSUE TITLE
space before or after directory name = no sync to windows?

### ISSUE THREAD

**Issue by jaxankey** [syncthing/syncthing#8112]
I found a set of folders would not sync. On my linux (and osx) boxes, there was a space after one folder's name and before another's in the path chain, so something like 
```
/home/whatever/path/to / pants/stuff.jpg
```
I had to remove both extra spaces to get this to sync. Perhaps a `\` vs `\\` and `\ ` issue or maybe a windows issue I'm not aware of. Anyway, not a huge deal. Thanks for all your help!

**Comment by calmh** [comment]
Indeed; file names on Windows can't begin or end with space.
