### ISSUE TITLE
gui: Save settings broken since #7530

### ISSUE THREAD

**Issue by acolomb** [syncthing/syncthing#8116]
Something changed in #7530 that broke saving settings.  At least I cannot change the theme anymore, some JavaScript errors are popping up.

One obvious thing is in https://github.com/syncthing/syncthing/blob/21d04b895a7b3ee0803e36e4f0b3f5e8e6cf1379/gui/default/syncthing/core/syncthingController.js#L1516: `saveConfig.then()` is missing the parentheses to actually call the function and make the promise.

After fixing this, I encountered errors because `emitHTTPError()` is called with a null argument for data, from somewhere around `refreshSystem()` if I interpret it correctly.  Please have a look @imsodin what is going on there.  Sorry I didn't test this during review, and my experience with JS promises is too limited to notice.

To reproduce, open Settings, change the GUI theme, save.

**Comment by acolomb** [comment]
There's also some `Error: Promised response from onMessage listener went out of scope` messages sprinkled in between... That's where my JS debugging skills currently end :-(

**Comment by imsodin** [comment]
I can only repro the obvious bug, no problems with null emitHTTPError or out-of-scope listeners. Fix for that is here: https://github.com/syncthing/syncthing/pull/8117

If you can repro any of those again, please provide any info you have (what did you do, line numbers from the error, ...).
