### ISSUE TITLE
Request: add a subcommand to override the default identity.

### ISSUE THREAD

**Issue by woocash2** [syncthing/syncthing#8118]
There already exists a `generate` sub-command, that generates a new identity, which is stored in an external folder. It would be useful to have another sub-command that would override the default identity with the generated one. Currently, if one wants to do that they need to know where the config files are stored (`.config/syncthing`) and which files to replace (`key.pem`, `cert.pem`, `config.xml`), and it would be more convenient to do this with a sub-command.

An example use case would be a host-node network, where the nodes are gui-less devices hidden behind different NATs, that cannot communicate with each other directly over ssh. Then the host can generate identities for the nodes, which can then be downloaded by the nodes, and then used as their default identities.

This would make the syncthing identities work a bit more like the ssh keys, where we can directly override the default location with `ssh-keygen`, and currently it is impossible with `syncthing generate` (it refuses to override the files in the specified folders). Even if overriding was possible with `syncthing generate`, it would still require the user to know where the syncthing config files are stored (and generate is a safe command for a reason...).

Current workarounds:
replace files in `.config/syncthing` manually, which is inconvenient,
use `syncthing --home <generated dir>`, which is even more inconvenient and error-prone, as you need to remember which identity to use and use this every time you launch syncthing and in every script.

**Comment by acolomb** [comment]
If you want to know the path where the default config will be searched, there is the `--paths` flag on the command line. But why do you want to replace the certificate at all? Your setup sounds like you're trying to automate provisioning new nodes. In such a scenario, explicitly setting the home directory seems feasible. And if you want the default dir, why would you expect there to be an existing certificate?

We could add a force flag to generate, but I think it's too much of a footgun and having the user explicitly delete / overwrite the files on their own protects from that.

**Comment by AudriusButkevicius** [comment]
As I said on the PR, this makes no sense.

You can use -home for the same purpose, a command that does cp adds zero value. If you want to copy files, copy files, syncthing doesn't need a subcommand for that.

**Comment by imsodin** [comment]
As on PR and above: Unclear what is really needed/proposed here. Please open a topic on https://forum.syncthing.net if you want to further explore this.
