### ISSUE TITLE
The ignore pattern `*` always ignore the  `multiple directory levels`

### ISSUE THREAD

**Issue by ramwin** [syncthing/syncthing#8127]
version: v1.18.6, Windows (64-bit Intel/AMD)  and v1.18.6, Linux (64-bit Intel/AMD)
 - browser: chrome
 - what happened,
     the ignore pattern `*.test` ignore the file `directory/abc.test`
 - what you expected to happen instead

according to the documentation:

    * Single level wildcard (matches within a directory only)
    ** Multi level wildcard (matches multiple directory levels)

Is it better if the ignore `*.test` just ignore the file `a.test` and `b.test`, and track the file `directory/abc.test`

**Comment by imsodin** [comment]
The explanation with example is pretty clear on this point to me:

> Asterisk (\*) matches zero or more characters in a filename, but does not match the directory separator. `te*ne` matches `telephone`, `subdir/telephone` but not `tele/phone`.

If you have more questions about this or ignore patterns in general, please open a topic at https://forum.syncthing.net - thanks.

**Comment by ramwin** [comment]
Thank you for your explanation. It's very clear for me now.
