### ISSUE TITLE
item has UTF8 encoding conflict with another item

### ISSUE THREAD

**Issue by DavidPesticcio** [syncthing/syncthing#8128]
### Does your log mention database corruption?
No

### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using
    `v1.18.6, Linux (64-bit Intel/AMD)`
 - browser and version, if applicable
    `N/A`
 - what happened
    `Failed Items`
    `github.com/joplin/CliClient/tests/support/photo-åäö.jpg item has UTF8 encoding conflict with another item`
 - what you expected to happen instead
    `no conflict`
 - any steps to reproduce the problem
    `git clone https://github.com/laurent22/joplin.git` (then allow to sync elsewhere)

When using `ls` to list files, they look the same

    $ cd joplin
    $ ls -l CliClient/tests/support/photo*
    -rw-rw-r-- 1 dp dp 2720 Jan 18 20:27 CliClient/tests/support/photo-åäö.jpg
    -rw-rw-r-- 1 dp dp 2720 Jan 18 20:27 CliClient/tests/support/photo-åäö.jpg
    -rw-rw-r-- 1 dp dp 2720 Jan 18 20:27 CliClient/tests/support/photo.jpg
    -rw-rw-r-- 1 dp dp 2720 Jan 18 20:27 CliClient/tests/support/photo-two.jpg

Actual filenames are different according to git (and of course the underlying filesystem ext4 on luks)

    $ git ls-files CliClient/tests/support/photo*
    "CliClient/tests/support/photo-a\314\212a\314\210o\314\210.jpg"
    CliClient/tests/support/photo-two.jpg
    "CliClient/tests/support/photo-\303\245\303\244\303\266.jpg"
    CliClient/tests/support/photo.jpg

syncthing log entries:

    2022-01-18 20:25:12 Scanner (folder "repo-local" (ak2vy-pdpov), item "github.com/joplin/CliClient/tests/support/photo-åäö.jpg"): normalizing path: item has UTF8 encoding conflict with another item
    2022-01-18 20:27:56 Scanner (folder "repo-local" (ak2vy-pdpov), item "github.com/joplin/CliClient/tests/support/photo-åäö.jpg"): normalizing path: item has UTF8 encoding conflict with another item

**Comment by AudriusButkevicius** [comment]
Thats the whole point of the check, the file name, when 
normalized clashes with the other existing filename that is already normalized.

Syncthing does not sync files that do not use a normalized encoding because they could not be representable on other systems that do not use that encoding, so this is working as expected.
