### ISSUE TITLE
error #1215 can not add foreign key constraint

### ISSUE THREAD

**Issue by AyehsaAN** [syncthing/syncthing#8129]
- Syncthing Version: v0.x.y OS Version: Operating System: Windows 11 /  Browser Version: Firefox 96.0.1 
 - Uniform Server ZeroXIII - 13.3.2/phpMyAdmin

****>  - error #1215 can not add foreign key constraint comes up when try to establish Foreign key link 
> Error
> 
> SQL query:
> 
> CREATE TABLE IF NOT EXISTS Booking (
> Booking_ID int unsigned NOT NULL auto_increment,
> Checkin_date date NOT NULL,
> Checkout_date date NOT NULL,
> Contact_number varchar(20) NOT  NULL,
> Booking_extras text NULL,
> Type_of_breakfast varchar(20) NOT NULL,
> roomID int(10),
> PRIMARY KEY (Booking_ID), 
> FOREIGN KEY (roomID) REFERENCES room(roomID)
> )
> 
> MySQL said: Documentation
> #1215 - Cannot add foreign key constraint****

 - 
 - 
 - USE bnb;
-- Booking table  for the bed and breakfast
DROP TABLE IF EXISTS Booking;
CREATE TABLE IF NOT EXISTS Booking (
Booking_ID int unsigned NOT NULL auto_increment,
Checkin_date date NOT NULL,
Checkout_date date NOT NULL,
Contact_number varchar(20) NOT  NULL,
Booking_extras text NULL,
Type_of_breakfast varchar(20) NOT NULL,
roomID int(10),
PRIMARY KEY (Booking_ID), 
FOREIGN KEY (roomID) REFERENCES room(roomID)
)TYPE=INNODB;

INSERT INTO Booking(Booking_ID, roomID, Checkin_date, Checkout_date, Contact_number,Booking_extras, Type_of_breakfast) VALUES (1, 7, "2018-05-09", "2018-05-12", "064-2041561582", "Extra mattress", "cooked");
INSERT INTO Booking(Booking_ID, roomID, Checkin_date, Checkout_date, Contact_number,Booking_extras, Type_of_breakfast) VALUES (2, 5, "2018-05-10", "2018-05-11", "064-091234569", " ", "Continental style");
INSERT INTO Booking(Booking_ID, roomID, Checkin_date, Checkout_date, Contact_number,Booking_extras, Type_of_breakfast) VALUES (3, 4, "2018-05-10", "2018-05-13", "064-20456112356", "With an extra heater", "cooked");
INSERT INTO Booking(Booking_ID, roomID, Checkin_date, Checkout_date, Contact_number,Booking_extras, Type_of_breakfast) VALUES (4, 2, "2018-05-14", "2018-05-16", "064-091234568", " ", "cooked");
INSERT INTO Booking(Booking_ID, roomID, Checkin_date, Checkout_date, Contact_number,Booking_extras, Type_of_breakfast) VALUES(5, 6,  "2018-05-17", "2018-05-20", "093-07123564", "With an extra bed", "continental style");

**Comment by bt90** [comment]
This has nothing to do with Syncthing.
