### ISSUE TITLE
Upload/Download showing in different places

### ISSUE THREAD

**Issue by nuuSolutions** [syncthing/syncthing#8137]
Great stuff.

Just one counterintuitive thing:
I sync a _single folder_ between PC and Phone.
Changes on the Phone => "Syncing" shows only under "Folders", file shows in tray overview
Changes on the PC => "Syncing" shows only under "Remote Devices" and nothing shows in the tray overview

intuitively any change (PC or Phone side) should consistently appear under "Folders" _and_ in the tray.

**Comment by AudriusButkevicius** [comment]
Not really, as the local folder is not actually doing anything, it's up to date, it's just serving data.

Also, if you have more than 2 devices, syncing status would make no sense, as there are no guarantees that your folder is serving any data at all, the remote device might be getting it call from the other devices.

If you wish to have a further discussion on this subject, please use the forum, as the issue tracker is reserved exclusively for verified bugs and features that the maintainers are worth while.

All other forms of discussion (it doesn't work for me/i think should be doing something else/it would be great if...) happen on the forums.

Thanks.

**Comment by nuuSolutions** [comment]
Don't evade the point please.
When syncing a folder, syncing to either side should be displayed CONSISTENTLY.
Can't help you more than this.
