### ISSUE TITLE
Discovery server: AWS Fargate/ALB setup header issues

### ISSUE THREAD

**Issue by Digitum** [syncthing/syncthing#8140]
I have tried to setup discovery server on AWS Fargate with an AWS Application Loadbalancer as front.
It seems that this setup does not work with the discovery server, as the discovery server needs more headers than the ALB can provide.

The ALB provides following headers:

- `X-Forwarded-For`
- `X-Forwarded-Proto`
- `X-Forwarded-Port`

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/x-forwarded-headers.html

But the application needs following:

- `X-Real-IP`
- `X-Client-Port`
- `X-Forwarded-For`
- `X-Forwarded-Proto`
- `X-SSL-Cert`

Will this even be possible to get compatible with cloud services as Fargate?

I do not have the deep knowledge needed to handle this, or if it is even possible to solve with current protocol, but in my opinion, the SSL/TLS should be moved out of the service entirely and let implementers handle it instead.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
