### ISSUE TITLE
Syncthing sets hidden DOS bit

### ISSUE THREAD

**Issue by SvenVD** [syncthing/syncthing#8142]
## Setup
- A syncthing server (v1.18.6 "Fermium Flea" (go1.17.6 linux-amd64))on  Red Hat Enterprise Linux release 8.5 (Ootpa) server with a shared folder on a mounted samba share.
- syncthingv1.18.3 (google play) on android syncing to the server

## Result
All files have DOS hidden flag en archive flag enabled. Causing them to appear invisible when mounting the same samba share on a windows computer.
Manually writing a file on the server to the samba share does not set the hidden flag.

## Expected
synced files should not have the DOS hidden flag, what is causing this?

**Comment by calmh** [comment]
Syncthing running on Linux doesn't have code to manipulate the hidden attribute at all, as it doesn't exist on Linux. Maybe samba does something like set that attribute for dotfiles and then doesn't unset it when they're renamed. 

I don't see how this would be a Syncthing bug and invite you to discuss on the forum if you want help troubleshooting. (If it then turns out I'm wrong we'll of course reopen this issue.)

**Comment by SvenVD** [comment]
Manually writing the same file on the server to the samba share does not set the hidden flag. So I thought it must be something related to what Syncthing does in combination with a samba mount.

I found related forum posts https://forum.syncthing.net/t/some-files-show-up-as-hidden-in-file-explorer/17744/6

I created forum topic
https://forum.syncthing.net/t/syncthing-sets-hidden-dos-bit/17931

**Comment by nunnsby** [comment]
Hi, I am still experiencing this issue running on the latest, 1.20.1 version.

### Setup

- Syncthing (v1.20.1, Linux (64-bit Intel/AMD) | "Fermium Flea" | Build 2022-05-18 (noupgrade)) in Docker Container (https://docs.linuxserver.io/images/docker-syncthing) running on Proxmox. The Syncthing Docker instance has a Volume mapped a local folder on Proxmox.

- The Proxmox local folder is mapped using CIFS `//qnap/docker /mnt/qnap_docker cifs iocharset=utf8,credentials=/root/.smbcredentials,_netdev,uid=1000 0 0` to a SMB share on a Truenas server, running on an old QNAP device.

- UID 1000 maps to a user which is configured on both the Trunas and Proxmox server and has access to all shares and datavols.

### Result

- All files written by Syncthing that require using the .syncthing.filename.tmp method still remain as "hidden files" when viewing them in Windows Explorer from a Windows 11 machine connected to the share. (They are represented in Windows with half-coloured icons) 

- Smaller files that can be written without requiring the .syncthing.filename.tmp method show up as normal "unhidden files", such as text files, etc. Any larger files, jpgs, movies, executables, zips, etc remain "hidden" even thought they are completely synced. Windows explorer properties shows them as having the hidden flag still set, even though they are fully synced. 

### Expected
As mentioned before, this is purely a Syncthing issue when writing to a shared volume, and is causing the DOS hidden attribute bit to be remain set once it is set on the file that uses the .syncthing.filename.tmp method, even when that file has completed. Copying large and small files directly from the docker container, not through Syncthing to the Volume mapped local folder  work fine and not bits are set.

### Things I have tried

- I have tried adding the `hide dot files = yes` enabled on the samba server, but it has made no difference.
