### ISSUE TITLE
Password.kdbx file cannot be synced

### ISSUE THREAD

**Issue by TahirJalilov** [syncthing/syncthing#8158]
- v1.18.6, Linux (64-bit Intel/AMD)
 - password.kdbx file cannot be synced
 - password.kdbx file should be synced normally

![image](https://user-images.githubusercontent.com/43037294/151855070-6b932039-03c8-469c-a785-bfb81c566278.png)

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
