### ISSUE TITLE
crash at 'reset database' in splash screen of new 1.19.0 and android 6.0.1

### ISSUE THREAD

**Issue by progserega** [syncthing/syncthing#8164]
1. I update syncthing from f-droid
1. start syncthing, he said need "reset database"
1. press 'reset database'
1. syncthing crash

I white log by `adb logcat` - in attachments:
[logcat.txt](https://github.com/syncthing/syncthing/files/8012292/logcat.txt)

Syncthing 1.19.0 not crash at this situation at other my phone (android 11). But crash at phone with android 6.0.1.

Android 6.0.1
Phone Yotaphone2 
syncthing 1.19.0

**Comment by imsodin** [comment]
Thanks for the report and logs. This is android specific, i.e. belongs to the syncthing-android repo, and there's already a report here: https://github.com/syncthing/syncthing-android/issues/1753
