### ISSUE TITLE
High performance mode

### ISSUE THREAD

**Issue by bovesan** [syncthing/syncthing#8165]
## The problem
Hashing several TB's of data takes a long time and transfers seem to peak around 1Gbps (Just over 100MBps), even on a 10Gb connection.
## Usefulness
Even though our use case is for huge files between powerful workstations (Xeon 4114 and Xeon 6244 using AES_128), this could also apply to less powerful devices pushing large files on a good connection.
## Workaround
Our largest files are placed in specific subfolders, which are synced a->b and b->a each night by a [custom script](https://github.com/bovesan/mistika-hyperspeed/blob/master/Tools/Subcp/subcp.py). This relies on regular linux cp command over nfs, as neither rsync or scp seems able to saturate the connection. These files are seldom modified, which makes cp --update (checks file modification time) plenty.
## Proposal
- Disable hashing for these files and only rely on modification time (should probably make sure time is set correctly across devices).
- Allow unencrypted transfers for those files.
## References
https://forum.syncthing.net/t/choosing-cipher-for-data-transfer/9812/3
https://github.com/syncthing/syncthing/issues/1019

**Comment by bt90** [comment]
Did you measure that encryption and/or hashing are the culprits here? Those CPUs should be able to saturate a 10Gbps link if these two are the only potential bottlenecks.

It's probably better to discuss the in the forum.

Removing encryption has a 100% not-happening-guarantee :)

**Comment by AudriusButkevicius** [comment]
I don't think we'll do this.

Everything in syncthing relies on hashing, which is usually bottlenecked by the cpu.

If you want generic advice on improving performance, forum is the way, but perhaps if you want 10Gbit, syncthing is not the right software.
