### ISSUE TITLE
False-positives for changed files, when sideloading to speed up `Send Only` folders

### ISSUE THREAD

**Issue by OCRenkist** [syncthing/syncthing#8167]
False-Positives for Changed Files, when Sideloading to Speed up `Send Only` Folders

###### Operating Systems Tested
Mainly `GNU/Linux` (mostly version `19.3` of the `Linux Mint` distribution),  and `Android/Linux` versions `9` and `10`.

###### Syncthing Versions Tested
Most every version of Syncthing since the introduction of the `Send Only` `folder type`.

###### What Happens
1. Create a `Send Only` folder.
1. Share the folder with another device.
1. Synchronization begins.
1. Observe the network transfer rate is slower than that of USB.
1. Copy the files from the `Send Only` device to the target device via USB.
1. Syncthing on the both devices observes there are new files on the target device.
1. Syncthing on the target device checksums the new files.
1. Despite the new files being identical to the files on the `Send Only` device, 
   Syncthing on the target device offers to `Revert Local Changes` if 
   the target folder is `Receive Only` and moves the new files to a versioning 
   directory if `Send & Receive`, appending their names with a date-deleted timestamp.

###### Workaround
Setting the folder on both devices to `Send & Receive` appears to provide the expected behavior, but is a perilous solution when the files on the source device are supposed to be kept immutable.

###### Expected to Happen
Presumably, Syncthing would see during the checksum process upon detecting new files, that the new local files are identical to the remote files, and acknowledge this with an appropriate jump in percentage completed in the synchronization process. Ideally, Syncthing on the target device would `touch` the files with the correct `mtime` values from the `Send Only` device as well.

**Comment by AudriusButkevicius** [comment]
Thats expected. Override changes would resolve this without data transfers, or setting the folder to send receive as you suggested.

Please use the forum if you want to further discuss this.
