### ISSUE TITLE
`Offload Only` folder type

### ISSUE THREAD

**Issue by OCRenkist** [syncthing/syncthing#8168]
### What do you want?
Syncthing could introduce an additional folder type called `Offload Only` defined such that files found in the folder so established, are treated as `Send Only` until they have been confirmed to have checksum-verified copies present on at least a user-specified number of other devices in the network, at which point those particular files would be deleted from the source device to free up space for new files being created by its sensors, such as photographs.

Likewise, a user-specified usage target could be implemented, such that the deletion of confirmed files only takes place if the available storage on the device with the `Offload Only` folder, drops below a certain amount. Presumably this would target the oldest files first, thus allowing the user to examine recent work without having to physically return to, nor remote into, the distant data devices.

### What problems would your new feature solve?
* clogged storage on mobile devices
* [RAID][RAID]-style data protection (via storage on multiple devices)
* eliminating the risk of accidentally deleting files not yet backed-up

### How or why you think it is generally useful?
Mobile devices which have flash memory as their mass-storage solution, are used by almost everyone who has such portable devices, and as such are bound to fill up faster than laptop, desktop, or network-attached storage (NAS) devices with mechanical hard drives and solid-states drives.

Moreover, those same mobile devices tend to be those which have the sensors (video, photographic, geospatial, etc.) producing files of substantial data-storage size, at a faster rate than the very machines (laptops, desktops, NAS, etc.) which have the greater storage capacity.

Properly automating the process of verification and removal of files from mobile devices would save enormous amounts of human effort, and is a feature present in many proprietary file-synchronization software packages.

### What alternatives or workarounds you considered?
Currently using some sort of external directory-differentiation tool would be required as a workaround, very prone to human error (and thus data loss) compared to what Syncthing could do.

[RAID]: https://en.wikipedia.org/wiki/RAID

**Comment by imsodin** [comment]
I am not disputing the usefulness of any such solution, but this isn't what Syncthing does and is intended to do. This would be both a huge amount of work and against the spirit of "doing one thing, and doing that well".  
If anyone wants to work on solutions like this, one could either create a new application based on existing or new code that's BEP compatible or use Syncthing itself with the REST API (I believe existing endpoints already contain all the necessary information (events, file status and ignore patterns)). Please use the forum to discuss any such efforts (I'd be very happy to answer questions for such projects).

**Comment by OCRenkist** [comment]
Heheh, thank you, I trust you enjoy my English composition and simply wish that I would also write in `Go`. :wink: 
I shall have to open a forum topic and ask for people to point me in the general direction. :+1:
