### ISSUE TITLE
"Folder marker missing" on Ubuntu VPS

### ISSUE THREAD

**Issue by b3nd1k** [syncthing/syncthing#8173]
Hey! I installed Syncthing on my Ubuntu VPS using Portainer. Using portainer, under volumes, I mapped `/mnt/` in both the container and host field. I made sure to mark it as "bind" and "writeable". 

In Syncthing I created a folder with Folder Label: _Test_ and  Folder Path: `/mnt/volume/test.` The test folder excists in the location and contains a single file. However, I get a message telling me that "`folder marker missing (this indicates potential data loss, search docs/forum to get information about how to proceed)"`. How do I fix this? 

As long as I've this issue, it won't sync to another Syncthing instance.

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
