### ISSUE TITLE
Users shouldn't be forced to "reset database" after auto-update

### ISSUE THREAD

**Issue by creator1creeper1** [syncthing/syncthing#8174]
After auto-updating the Android mobile app, it should be possible for users to keep using the old filesystem API until they decide to actively switch to the new one and regenerate the hashes. As far as I can tell, this is not currently possible.

**Comment by acolomb** [comment]
This belongs to the https://github.com/syncthing/syncthing-android/ repository.  I don't think it will happen though, as the switch was pretty much an all-or-nothing decision forced by Google's rules for the Android platform.
