### ISSUE TITLE
CSRF token conflict because deviceID is generated from certificate

### ISSUE THREAD

**Issue by anurnomeru** [syncthing/syncthing#8179]
### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using

v1.18.0

 - what happened,

I started two syncthings with the same certificate, open their dashboard in the browser at the same time, one of them will not work properly due to CSRF token error because they have the same deviceID.

 - what you expected to happen instead, and

Can a unique identifier such as URI be added as key to store the value when saving CSRF token in the front-end, so that this problem can be avoided?

 - any steps to reproduce the problem.

Start more than one syncthings with same certificate, and open thier dashborad at same time.

******

Can I creating a pull request  to fix this?

**Comment by calmh** [comment]
You cannot run two syncthing instances with the same certificate; or if you do, this will likely be the least of your problems. Suggest discussing what you’re actually trying to accomplish on the forum (like, is this some HA attempt?).
