### ISSUE TITLE
Make error message upon reaching the free space quota more clear

### ISSUE THREAD

**Issue by itsTyrion** [syncthing/syncthing#8180]
I just spent 10 minutes going back and forth because Syncthing kept spitting "out of disk space" errors, which is quite confusing when `df` says otherwise. 
Turns out I was just below the quota of 10% set for just that folder. 

I think, something like `Folder quota of X%/kB/MB/GB/TB free space reached` would be more appropriate than `insufficient disk space`, which sounds like the disk is just 100% full.

**Comment by calmh** [comment]
Doesn't the error actually say something like "insufficient disk space (5 MB < required 1%)"? (Not in front of a computer right now.)

**Comment by itsTyrion** [comment]
@calmh 
> Puller (folder *folder name*, item "*file name*"): syncing: insufficient space in basic *path*
