### ISSUE TITLE
Problem with .stfolder

### ISSUE THREAD

**Issue by grubeli** [syncthing/syncthing#8181]
Syncthing `v1.19.0 "Fermium Flea" (go1.17.6 linux-amd64) syncthing@archlinux 2022-02-01 18:27:04 UTC [noupgrade]`   
OS: `Manjaro Linux x86_64`   
Kernel: `5.15.19-1-MANJARO`   

`.stfolder` is an empty folder used as a marker by Syncthing, also there is a `.thumbnails` folder, usually they are empty.

In my scenario, I have `rclone` syncing and encrypting from my disc to S3, I'm using `syncthing` to sync from my phones to the mounted disc, which by itself uploads data to S3. The problem is that S3 is unable to have empty folders, so every time I mount the disc there is no empty folders, hence syncthing have missing marker problem.

To avoid the issue, I created `.stfolder` file under `.stfolder` folder with content of `.stfolder`, it solved marker problem, but `.thumbnails` problem stays

**Comment by calmh** [comment]
You can indeed have files in .stfolder if that helps, Syncthing doesn't care. So this seems like not a Syncthing problem?

**Comment by grubeli** [comment]
kind of, maybe others also getting same problem, why not having this behavior by default to have a file in it?

Also when there is no thumbnails folder it complains about local changes

**Comment by bt90** [comment]
To be clear: `.thumbnails` is not created or receives special treatment by syncthing.

You could add an ignore pattern for it though.

For support questions head over to our forum :wink:
