### ISSUE TITLE
Consider shipping release tarball with vendored dependencies

### ISSUE THREAD

**Issue by illiliti** [syncthing/syncthing#8182]
For example, [dnscrypt-proxy](https://github.com/DNSCrypt/dnscrypt-proxy/tree/master/vendor) does this by simply maintaining vendor directory. You can also setup CI to vendor dependencies into release tarball without needing to keep vendor directory within repository. Here is the command that can be used for this: `go mod vendor`

With vendored dependencies, i can build syncthing from source without internet connection by using this command: `go build -mod=vendor`

**Comment by imsodin** [comment]
We already do that.

**Comment by illiliti** [comment]
Where? I only see binaries in release tab.

**Comment by illiliti** [comment]
Ah, i see. So deeply buried...My bad, sorry.
