### ISSUE TITLE
Muliti connection for improve speed.

### ISSUE THREAD

**Issue by jzh20042003** [syncthing/syncthing#8184]
Sometimes I use syncthing to transfer files between my computer and my linux server.But my computer and my linux server are not in the same country.They are very far and the connection is very unstable.My server have 1gpbs speed and my computer has 30mbits speed.But the speed between my server and my computer has only 0 -500kbyte/s.Usually the speed is under 100kbyte/s.

I have an idea:use muliti server and muliti connection to import speed.
I see there are many relay servers.But I can only use one at one time.
I wish syncthing can use more than one relay servers and ipv4,ipv6 together in one task.
For example,I can use 5 relay servers and my tcp-ipv6,tcp-ipv6 together.Then I can have 7 connection.Then the speed must be faster than 1 connection.
Sometimes I upload my files from my computer to linux server.The speed is really slow.Because I have very bad connection between my computer and linux server.I wish there can be some new transfer Protocol to imporve upload speed

**Comment by calmh** [comment]
You could try QUIC instead of TCP to see if that's faster for you. 

It's possible multiple TCP connections would be faster than a single one, but it would come at significant complexity, and ultimate speed is not one our goals. So I'm saying no to that as a feature for now.

**Comment by marclaporte** [comment]
Will be addressed soon: https://github.com/syncthing/syncthing/pull/8918
