### ISSUE TITLE
Answer to an issue where i cannot write anything: [Next Gen Ignores: Requirements](https://github.com/syncthing/syncthing/issues/2491#) #2491

### ISSUE THREAD

**Issue by dmuiX** [syncthing/syncthing#8185]
[Next Gen Ignores: Requirements](https://github.com/syncthing/syncthing/issues/2491#)
#2491

As its not possible to post anything under this issue i am opening a new one:

So how far is this whole implementarion of next gen ignore patterns/selective sync/on-demand folder type? 
philipbowser has posted something on december. Thank you. 

> [philipbowser](https://github.com/philipbowser) commented [on Dec 7, 2021](https://github.com/syncthing/syncthing/issues/2491#issuecomment-988038948)
So a GUI could translate all the checkboxes into specific include and exclude patterns and vice versa. An additional textbox could be provided for advanced patterns.
I think it should actually be possible to combine the two. So when I have whatever patterns in my list, I should be able to filter all the ones, that specify a specific file or directory (no wildcards) and translate them into a treeview and vice versa without losing anything.
So I could even show an advanced mode to edit all patterns and then switch back to treeview. Best of both worlds! :-)

This seems like the way to go. Have the tree view checkboxes just populate the ignore pattern text box with the specific include/exclude patterns, then advanced folks can still add their advanced patterns if they need it.

I think the most crucial elements of this, even if a tree-view with checkboxes isn't implemented, are the needs to see what files and folders have not been synced yet (so you don't have to download potentially hundreds of gigs of data just to find out what to ignore) and to have this be a per device setting. If you could see a representation of what you don't have on your computer, and check a box to start syncing only the folders you need, then Syncthing would be easy to deploy in a mixed skill level environment where not everyone who's using the share is a power user.

**Comment by calmh** [comment]
Noted, thanks.
