### ISSUE TITLE
If you delete the file without completing the sync, the .tm file will be left behind.

### ISSUE THREAD

**Issue by c469591** [syncthing/syncthing#8187]
Hello.
I have created a folder sync between computer a and computer b.
When I paste a file click in the folder of computer a, it will start scanning and then uploading the file click.
But if I delete the file click before the synchronization is completed, the file name.tm file will be left on computer b and will take up space.
If I try to re-scan or restart the gui page of the browser, the .tm file still exists and will not be cleared.
Can this problem be solved in a later version?
Is it possible to delete the .tm file after deleting the file, so that it will not take up my hard disk space?
Or can I add a function to scan and delete .tm files?
Thanks!

Translated with www.DeepL.com/Translator (free version)

**Comment by tomasz1986** [comment]
Leftover `.tmp` files are automatically deleted after 24 hours. The value can be tweaked by editing [keepTemporariesH](https://docs.syncthing.net/users/config.html#config-option-options.keeptemporariesh).

This is not a bug, so if you need more help or have additional questions, please open a new topic at https://forum.syncthing.net instead.
