### ISSUE TITLE
Bias in the CSPRNG

### ISSUE THREAD

**Issue by jvoisin** [syncthing/syncthing#8194]
Syncthing [makes use]( https://github.com/syncthing/syncthing/blob/48fd9d05b575fa71e6fceeef2f1c3c8337a551e7/lib/rand/random.go#L34) of `mathRand.New` with a buffered CSPRNG as a source:
Unfortunately, it's [using]( https://github.com/syncthing/syncthing/blob/48fd9d05b575fa71e6fceeef2f1c3c8337a551e7/lib/rand/random.go#L45) the `Intn` method, which is [slightly biased]( https://cs.opensource.google/go/go/+/refs/tags/go1.17.7:src/math/rand/rand.go;l=123-138;drc=refs%2Ftags%2Fgo1.17.7); see [this blogpost]( https://lemire.me/blog/2016/06/27/a-fast-alternative-to-the-modulo-reduction/) for details.

I *think* that it's a minor issue, but since it's crypto-code, better safe than sorry.

A possible solution would be to use something like [frand]( https://golangexample.com/a-fast-userspace-csprng-in-userspace/ ) or to implement an equivalent [fast-key-erasure rng]( https://blog.cr.yp.to/20170723-random.html).

**Comment by calmh** [comment]
Isn't the loop to avoid bias?

(I think our most security relevant Intn use is to generate random strings for CSRF tokens and the like, and even if it's biased there it's an exceedingly small bias as we're generating small random numbers...)
