### ISSUE TITLE
https://apt.syncthing.net/ incorrect

### ISSUE THREAD

**Issue by whitis** [syncthing/syncthing#8195]
- which version of Syncthing and what operating system you are using
   https://apt.syncthing.net/

 - browser and version, if applicable
   not applicable

 - what happened,
   due to incorrect use of sudo, the sudo logfile shows 
     tee /etc/apt/sources.listd/syncthing
  this is not useful.  This doesn't show you what was added and it does not help you reinstall the system, or another system, later.
  Also, the instructions are unclear about stable vs candidate channels and that you should only install one.

 - what you expected to happen instead, and
   sudo log should show something useful like:
    /bin/bash
    -c echo "deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg]
    https://apt.syncthing.net/ syncthing stable" >
    /etc/apt/sources.list.d/syncthing.list

    sudo/bash does lose the single quotes but the important information is there.  Just add sudo and the quotes and you are good to reproduce.

 - any steps to reproduce the problem.
 - 
   follow the instructions on the linked web page

Bad code:
echo "deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable" | sudo tee /etc/apt/sources.list.d/syncthing.list
echo "deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing candidate" | sudo tee /etc/apt/sources.list.d/syncthing.list

The installation instructions on https://apt.syncthing.net/ are incorrect.   They fail to create a proper log of the actions.
sudo curl -s -o /usr/share/keyrings/syncthing-archive-keyring.gpg https://syncthing.net/release-key.gpg
sudo bash -c 'echo "deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable" > /etc/apt/sources.list.d/syncthing.list'
#OR:
sudo bash -c 'echo "deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing candidate" > /etc/apt/sources.list.d/syncthing.list'
sudo apt-get update
sudo apt-get install syncthing syncthing-gtk

Feel free to use sh instead of bash.

**Comment by acolomb** [comment]
I think this is also about how easy it is to type the commands into a terminal manually. In such a case, the construct with nested quotes is rather fragile. IMHO the instructions should be as simple as possible and in that regard the `sudo tee` solution is pretty common.

About seeing what you did in them logs: I often install several similar systems as well, noting every entered command by copy-and-paste manually. If you want to avoid that, just log out temporarily and then copy the `.bash_history` file after the fact.

You are right about the channels not being quite clear that you only need one OR the other.
