### ISSUE TITLE
v1.5.0 not working on OS X 10.11.6 (15G22010)

### ISSUE THREAD

**Issue by SubZero5** [syncthing/syncthing#8209]
Synching v1.5.0 and later releases are not working on OS X 10.11.6 (15G22010)
Latest working version is v1.4.0

FYI: Disabled auto-update feature because it tries to upgrade to 1.19.1 but fails every time!

**Comment by bt90** [comment]
Not really something which can be fixed by the Syncthing project as golang pulls the plug on older OS X releases.

e.g go 1.17 only supports OS X 10.13 or later

This version of OS X has also reached EOL since December 2018(!).
