### ISSUE TITLE
Pausing upload leads to busy waiting loop (100% CPU) in star-shaped configuration

### ISSUE THREAD

**Issue by sdschulze** [syncthing/syncthing#8211]
I am using Debian stable, and the problem occurs both with the version provided by the distribution as well as the one from the syncthing repository (that is, 1.19.1).

I am operating three devices (A, B, C) in a star-shaped configuration.  That is, A and B know each other and so do B and C, but not A and C.  Initially, I put a rather large folder in the default directory (that is shared among A and B as well as among B and C) on device A, but because I noticed that B and C would not have enough disk space, I quickly paused it.  However, a few files were already shared.  Pausing the sync on device A caused device B to go into a busy waiting loop with 100% CPU usage.

On its web interface, B says that A is up-to-date, and it claims to be syncing with C, but no network traffic is flowing, and there is no progress in the sync process.  Device A obviously says that the upload is paused, while C thinks it's up-to-date.  Terminating syncthing on device C does not change anything, but when terminating syncthing on device A, it announces on device B:
`INFO: Folder "Default Folder" (default) isn't making sync progress - retrying in 1m25s.`
In that stage, it still uses a lot of CPU every few minutes, but at least it is not constantly up.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by sdschulze** [comment]
It's not a support request.  I don't think indefinite busy waiting at 100% CPU while doing nothing useful is intended behavior.

**Comment by AudriusButkevicius** [comment]
I agree, but there is not enough details to understand whats the cause as it stands.

The back and forth for that, debugging, logs etc, is best conducted on the forum.

Once the cause is understood and we are in agreement its a bug that we should fix, we can reopen this
