### ISSUE TITLE
Add option to ignore warning when admin gui is exposed without authentication

### ISSUE THREAD

**Issue by m00nwtchr** [syncthing/syncthing#8214]
I know it's normally a bad idea, but I'm running it behind a reverse proxy which handles the authentication. (and so i don't want the big box cluttering up the interface)

**Comment by calmh** [comment]
You have https://docs.syncthing.net/users/config.html#config-option-gui.insecureadminaccess.

If you mean the warning that's still displayed with that on, I think current thinking is that we'll not remove that.
