### ISSUE TITLE
Can't upgrade to 1.19.1 on Android 6.0.1

### ISSUE THREAD

**Issue by arkoort** [syncthing/syncthing#8221]
At the first start Syncthing 1.19.1 alerts about database format change and asks to press the button below to reset database and start Syncthing. But there's NO button below (except `BACK` and `FINISH`) and I don't know how I can continue.

Phone Asus ZB501KL with original Android 6.0.1. Screenshot: https://github.com/arkoort/temporary/blob/main/unnamed.jpg?raw=true

(Of course I've tried to scroll down. There's nothing to scroll there)

**Comment by tomasz1986** [comment]
You're supposed to scroll, but there was a similar issue some time ago, where the user also couldn't do it. Can you try either to switch to landscape mode, and if the scrolling still doesn't work, perhaps connect a Bluetooth mouse or keyboard and try using them to scroll?

**Comment by imsodin** [comment]
Yep, landscape was the workaround: https://github.com/syncthing/syncthing-android/issues/1767

If you have any more questions, please post on https://forum.syncthing.net

**Comment by arkoort** [comment]
Oh, thank you. I didn't guess to switch to landscape mode. It helped, it works now.
