### ISSUE TITLE
Reveal, and offer control over, what ports Syncthing attempts to communicate on

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [syncthing/syncthing#8228]
Some reverse-firewalls block or explicitly manage ports like `433 (https)` or `993 (imaps)`; and my firewall in particular interrogates me on every single usage of port `443 (https)`.

I understand that Syncthing's discovery 'falls back' to 443 to enable situations where the higher ports like `22000 (syncthing)` are inaccessible; but it'd be nice to be able to *disable* this behaviour when the desired ports are actually available!

<img width="561" alt="Screen Shot 2022-03-22 at 8 04 54 AM" src="https://user-images.githubusercontent.com/200/159488644-1e0daaf3-bea3-4282-965a-f98c8c16d08c.png">

<img width="904" alt="Screen Shot 2022-03-22 at 8 07 40 AM" src="https://user-images.githubusercontent.com/200/159488830-894b4481-1d83-452e-a754-8592d4a22141.png">

**Comment by AudriusButkevicius** [comment]
This is nothing todo with what syncthing is listening on, this is for outgoing connections.

This is basically asking you if you want to allow syncthing to use the internet.

If you have any more questions/suggestions, please use the forum.

**Comment by ELLIOTTCABLE** [comment]
(Why is there a "feature request" template for GitHub Issues if you don't want those filed here? Might be worth removing that!)

I'm aware that it has nothing to do with what ports Syncthing is *listening* on (well, it does; but Syncthing doesn't attempt to *listen* on 443; only 22000.) And, yes, I'm specifically talking about controlling the ports Syncthing attempts to make outgoing connections on.

Should I repost this on the forums?

**Comment by AudriusButkevicius** [comment]
I don't think I understand your request, so yes, getting clarity on the forum is the way forward.
