### ISSUE TITLE
Fedora 34 syncthing broken after v1.16.1

### ISSUE THREAD

**Issue by randombugs** [syncthing/syncthing#8230]
After updating syncthing on my system it wasnt working anymore. After having no idea what is going wrong, I tried a livecd and reproduced the issue there.

Syncthing not even prints the version when executing `syncthing --version`. It just consumes 100% of cpu and nothing happens.

Tried several versions of syncthing from fedora-packages and github. It stops working with v1.17...

On Fedora 35 its working without problems.

System: Fresh Fedora 34 Live-CD, only strace installed

uname -a: Linux localhost-live 5.11.12-300.fc34.x86_64 #1 SMP Wed Apr 7 16:31:13 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Steps to reproduce:

1. Start Fedora 34 Live-CD (f.e. https://mirror.netzwerge.de/fedora/linux/releases/34/Workstation/x86_64/iso/ )
2. Install syncthing (installs syncthing-1.19.1-1.fc34 atm): `sudo dnf install syncthing`
3. execute command in terminal: `syncthing --version`

There are several straces from different versions attached. The only one working was v1.16. I downloaded the versions from github and verified checksums. The command I used to generate these: `strace -o FILE ./syncthing --version` I killed the process after a few seconds

[syncthing-linux-386-v1.17.0-rc.1.strace.txt](https://github.com/syncthing/syncthing/files/8337074/syncthing-linux-386-v1.17.0-rc.1.strace.txt)
[syncthing-linux-amd64-v1.16.1.strace.txt](https://github.com/syncthing/syncthing/files/8337075/syncthing-linux-amd64-v1.16.1.strace.txt)
[syncthing-linux-amd64-v1.17.0.strace.txt](https://github.com/syncthing/syncthing/files/8337076/syncthing-linux-amd64-v1.17.0.strace.txt)
[syncthing-linux-amd64-v1.17.0-rc.1.strace.txt](https://github.com/syncthing/syncthing/files/8337077/syncthing-linux-amd64-v1.17.0-rc.1.strace.txt)
[syncthing-linux-amd64-v1.19.1.strace.txt](https://github.com/syncthing/syncthing/files/8337078/syncthing-linux-amd64-v1.19.1.strace.txt)
[syncthing-linux-amd64-v1.19.2-rc.2.strace.txt](https://github.com/syncthing/syncthing/files/8337079/syncthing-linux-amd64-v1.19.2-rc.2.strace.txt)

I also reported the issue to the Package Maintainer https://bugzilla.redhat.com/show_bug.cgi?id=2067343 and he asked my to post it here.

If you need anything - Im happy to help

.

**Comment by AudriusButkevicius** [comment]
Did you try downloading our package from github? I suspect that will just work.

**Comment by tomasz1986** [comment]
I've actually downloaded the linked ISO and have just tested following the aforementioned steps. Syncthing is running fine here (on a VM).

![image](https://user-images.githubusercontent.com/5626656/159822862-f7e05bbe-6caa-4605-add7-5097f7ea22dd.png)

I think there must be something else in your current system that is causing the problem. I'd suggest to create a new topic at https://forum.syncthing.net if you'd like to debug this further.

**Comment by imsodin** [comment]
What has been said above:  
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
