### ISSUE TITLE
Last Scan in WebUI displayed in UTC

### ISSUE THREAD

**Issue by drws** [syncthing/syncthing#8239]
### Include required information

This is happening in latest Syncthing 1.19.1 (and Firefox 98.0.2). The _Last Scan_ time is shown in UTC instead of client browser's set timezone or at least in server's locally-set timezone (such as in the case of log display).

**Comment by tomasz1986** [comment]
Have you tested in different browsers and/or using a clean Firefox profile? I'd suspect the culprit may be using some kind of anti-fingerprinting settings or extensions in the browser.

**Comment by drws** [comment]
You are spot-on and it's a problem on my end. Thanks to @tomasz1986 for solution, sorry to all for bothering you and have a great day!
