### ISSUE TITLE
Expose folders via WebDAV to allow syncing browser extensions and NextCloud apps

### ISSUE THREAD

**Issue by EternityForest** [syncthing/syncthing#8240]
Many things are file-like but cannot be synced because of platform restrictions, notably data items in some web extensions, and data created in Android apps designed to work with NextCloud that do not have proper local folder support.

This is a pretty big issue, as the usual solution is to just use the Google Docs mode that is usually there.

WebDAV, with a secure key(The app could only permit app-generated strong keys), can be more secure than folder-based sharing, on platforms like Android with strong sandboxing, with would be a great thing for apps storing highly sensitive data like Joplin notes.

One could use synced repos in SyncThing's protected folders, only giving access to a few specific apps.

Being able to easily sync browser bookmarks without a cloud provider would be a major advancement for the open source community.

It could also increase performance, as change notification would be instant, with no polling or scanning.

With how popular NextCloud seems to be as a backend, compatibility with all of those apps seems like a relatively easy win that would massively expand the usefulness, and give a path forward on platforms that severely restrict folder sharing.

**Comment by AudriusButkevicius** [comment]
This is not what syncthing does.
Syncthing syncs files, that's it.

We don't think it should be anything more than what it is. If you want something more, you probably want a different application.

**Comment by acolomb** [comment]
Or write some kind of wrapper that glues together synchronized folders of files with whatever protocol you would like to access them with. I don't really understand what you are trying to do / suggesting. But in any case, our forum is the right place for such ideas and discussions.
