### ISSUE TITLE
syncthing synology package does not start after update

### ISSUE THREAD

**Issue by zzlazz** [syncthing/syncthing#8246]
@acolomb 
### Does your log mention database corruption?

no

### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using: 
updates syncthing from 1.19.0 to 1.19.0-25
 - browser and version, if applicable: 
 no browser but Synology DSM version 7.01-42218 update 3 (recently updated from7.0.1-42218), on DS218+
 - what happened: 
syncthing briefly starts, then crashes. synthing.log shows: 

```
[start] 19:10:39 INFO: syncthing v1.19.0 "Fermium Flea" (go1.17.5 linux-amd64) root@publish 2022-02-03 19:51:15 UTC
[start] 19:10:39 WARNING: Failed to initialize config: config file version (36) is newer than supported version (35). If this is expected, use --allow-newer-config to override.
[monitor] 19:10:39 INFO: Syncthing exited: exit status 1
```

 - what you expected to happen instead: 
 syncthing to start and operate flawlessy as before!

 - any steps to reproduce the problem.
 try to update the syno package from 1.19.0 to 1.19.0-25, DSM update as above may also be relevant

**Comment by acolomb** [comment]
This is an issue mainly with the SynoCommunity package, already reported at https://github.com/SynoCommunity/spksrc/issues/5142.  You could help with testing the PR linked there, https://github.com/SynoCommunity/spksrc/pull/5181.
