### ISSUE TITLE
migrate away from unmaintained gogo-protobuf?

### ISSUE THREAD

**Issue by sten0** [syncthing/syncthing#8247]
Dear Syncthing maintainers,

A member of the Debian Go Packaging Team (not aviau) recommended that someone should ask you if you're willing to migrate away from the unmaintained gogo-protobuf.  1.19.x appears to still depend on it.  @aviau, would you care to comment?

Thanks,
Nicholas

**Comment by acolomb** [comment]
The package is only used when explicitly requested through `go run build.go proto`. The results of that command are check into the repository, so there should be no need for Debian to consider this dependency during package builds.

**Comment by sten0** [comment]
@acolomb,

> The package is only used when explicitly requested through `go run build.go proto`. The results of that command are check into the repository, so there should be no need for Debian to consider this dependency during package builds.
>

The package appears to be required within a Debian context:

`
dh_auto_build -- -ldflags "-X github.com/syncthing/syncthing/lib/build.Version=v1.18.6-ds1 \
                                   -X github.com/syncthing/syncthing/lib/build.User=debian \
                                   -X github.com/syncthing/syncthing/lib/build.Host=debian \
                                   -X github.com/syncthing/syncthing/lib/build.Stamp=1648854604" \
                           -tags 'noupgrade purego'
        cd _build && go install -trimpath -v -p 4 -ldflags "-X github.com/syncthing/syncthing/lib/build.Version=v1.18.6-ds1                                    -X github.com/syncthing/syncthing/lib/build.User=debian                                    -X github.com/syncthing/syncthing/lib/build.Host=debian                                    -X github.com/syncthing/syncthing/lib/build.Stamp=1648854604" -tags "noupgrade purego" github.com/syncthing/syncthing/cmd/stcompdirs github.com/syncthing/syncthing/cmd/stdisco github.com/syncthing/syncthing/cmd/stdiscosrv github.com/syncthing/syncthing/cmd/stevents github.com/syncthing/syncthing/cmd/stfileinfo github.com/syncthing/syncthing/cmd/stfinddevice github.com/syncthing/syncthing/cmd/stfindignored github.com/syncthing/syncthing/cmd/stgenfiles github.com/syncthing/syncthing/cmd/strelaysrv github.com/syncthing/syncthing/cmd/strelaysrv/testutil github.com/syncthing/syncthing/cmd/stsigtool github.com/syncthing/syncthing/cmd/stvanity github.com/syncthing/syncthing/cmd/stwatchfile github.com/syncthing/syncthing/cmd/syncthing github.com/syncthing/syncthing/cmd/syncthing/cli github.com/syncthing/syncthing/cmd/syncthing/cmdutil github.com/syncthing/syncthing/cmd/syncthing/decrypt github.com/syncthing/syncthing/cmd/syncthing/generate github.com/syncthing/syncthing/cmd/uraggregate github.com/syncthing/syncthing/lib/api github.com/syncthing/syncthing/lib/api/auto github.com/syncthing/syncthing/lib/assets github.com/syncthing/syncthing/lib/beacon github.com/syncthing/syncthing/lib/build github.com/syncthing/syncthing/lib/config github.com/syncthing/syncthing/lib/config/mocks github.com/syncthing/syncthing/lib/connections github.com/syncthing/syncthing/lib/connections/mocks github.com/syncthing/syncthing/lib/connections/registry github.com/syncthing/syncthing/lib/db github.com/syncthing/syncthing/lib/db/backend github.com/syncthing/syncthing/lib/dialer github.com/syncthing/syncthing/lib/discover github.com/syncthing/syncthing/lib/discover/mocks github.com/syncthing/syncthing/lib/events github.com/syncthing/syncthing/lib/events/mocks github.com/syncthing/syncthing/lib/fs github.com/syncthing/syncthing/lib/ignore github.com/syncthing/syncthing/lib/locations github.com/syncthing/syncthing/lib/logger github.com/syncthing/syncthing/lib/logger/mocks github.com/syncthing/syncthing/lib/model github.com/syncthing/syncthing/lib/model/mocks github.com/syncthing/syncthing/lib/nat github.com/syncthing/syncthing/lib/osutil github.com/syncthing/syncthing/lib/pmp github.com/syncthing/syncthing/lib/protocol github.com/syncthing/syncthing/lib/protocol/mocks github.com/syncthing/syncthing/lib/rand github.com/syncthing/syncthing/lib/rc github.com/syncthing/syncthing/lib/relay/client github.com/syncthing/syncthing/lib/relay/protocol github.com/syncthing/syncthing/lib/scanner github.com/syncthing/syncthing/lib/sha256 github.com/syncthing/syncthing/lib/signature github.com/syncthing/syncthing/lib/stats github.com/syncthing/syncthing/lib/stun github.com/syncthing/syncthing/lib/svcutil github.com/syncthing/syncthing/lib/sync github.com/syncthing/syncthing/lib/syncthing github.com/syncthing/syncthing/lib/testutils github.com/syncthing/syncthing/lib/tlsutil github.com/syncthing/syncthing/lib/upgrade github.com/syncthing/syncthing/lib/upnp github.com/syncthing/syncthing/lib/ur github.com/syncthing/syncthing/lib/ur/contract github.com/syncthing/syncthing/lib/util github.com/syncthing/syncthing/lib/versioner github.com/syncthing/syncthing/lib/watchaggregator github.com/syncthing/syncthing/lib/weakhash github.com/syncthing/syncthing/proto/ext
src/github.com/syncthing/syncthing/lib/discover/local.pb.go:8:2: cannot find package "github.com/gogo/protobuf/gogoproto" in any of:
        /usr/lib/go-1.18/src/github.com/gogo/protobuf/gogoproto (from $GOROOT)
        /<<PKGBUILDDIR>>/_build/src/github.com/gogo/protobuf/gogoproto (from $GOPATH)
src/github.com/syncthing/syncthing/lib/discover/local.pb.go:9:2: cannot find package "github.com/gogo/protobuf/proto" in any of:
        /usr/lib/go-1.18/src/github.com/gogo/protobuf/proto (from $GOROOT)
        /<<PKGBUILDDIR>>/_build/src/github.com/gogo/protobuf/proto (from $GOPATH)
src/github.com/syncthing/syncthing/proto/ext/ext.pb.go:9:2: cannot find package "github.com/gogo/protobuf/protoc-gen-gogo/descriptor" in any of:
        /usr/lib/go-1.18/src/github.com/gogo/protobuf/protoc-gen-gogo/descriptor (from $GOROOT)
        /<<PKGBUILDDIR>>/_build/src/github.com/gogo/protobuf/protoc-gen-gogo/descriptor (from $GOPATH)
src/github.com/syncthing/syncthing/lib/config/observed.pb.go:9:2: cannot find package "github.com/gogo/protobuf/types" in any of:
        /usr/lib/go-1.18/src/github.com/gogo/protobuf/types (from $GOROOT)
        /<<PKGBUILDDIR>>/_build/src/github.com/gogo/protobuf/types (from $GOPATH)
`

**Comment by AudriusButkevicius** [comment]
We rely quite extensively on the features gogo proto provides for custom code generation via extensions.

**Comment by calmh** [comment]
Yeah... I did this migration recently in a different project, because it was required to use newer gRPC and other libraries, and let me tell you it's a pain in the ass. And Syncthing does more custom stuff than that other thing did. So, I think this should be somewhere on our radar for the far future, as we're currently a little bit stuck in a dead end, but it's not a small or quick thing.

**Comment by acolomb** [comment]
@sten0 I'm trying to replicate this, but having trouble trying to build it under Ubuntu 20.04 LTS.  Shouldn't a `dpkg-buildpackage --no-sign -d` work from a checkout of your Salsa repo?

**Comment by calmh** [comment]
Underscore imports are generally done for side effects. I don't know the specifics, you'd have to check the package.

**Comment by greatroar** [comment]
That package has init functions that need to run:

https://github.com/gogo/protobuf/blob/226206f39bd7276e88ec684ea0028c18ec2c91ae/gogoproto/gogo.pb.go#L708-L787

**Comment by sten0** [comment]
Hi!

Thank you for discussion, reply follows inline:

greatroar ***@***.***> writes:

> That package has init functions that need to run:
>
> https://github.com/gogo/protobuf/blob/226206f39bd7276e88ec684ea0028c18ec2c91ae/gogoproto/gogo.pb.go#L708-L787

Audrius Butkevicius ***@***.***> writes:

> We rely quite extensively on the features gogo proto provides for custom code generation via extensions.
>

Yes, this is what it looks like to me too :-)

Jakob Borg ***@***.***> writes:

> Yeah... I did this migration recently in a different project, because it was required to use newer gRPC and other libraries, and let me tell you it's a pain in the ass. And Syncthing does more custom stuff than that other thing did. So, I think this should be somewhere on our radar for the far future, as we're currently a little bit stuck in a dead end, but it's not a small or quick thing.
>

Yeah, this kind of work is no fun.  I believe that the reason my
colleague asked me to contact the Syncthing project may be due to
concern that the currently-unmaintained gogo protobuf will break when Go
1.19 is released, similarly to how quic-go broke with 1.18; however, I'm
not sure how likely that is.  To be fair, there are also at least the
following two alternatives:

1. Perhaps form a team with other projects who use gogo protobuf, and
adopt its maintenance?

2. Perhaps form a team to work on a compatibility layer, similarly to
Marten Seeman's qtls-go1-18?

Speaking from a Debian context, this second option would become
nonviable if gogo protobuf itself fails to build with a future version
of Go.

Regards,
Nicholas

**Comment by imsodin** [comment]
> concern that the currently-unmaintained gogo protobuf will break when Go 1.19 is released, similarly to how quic-go broke with 1.18;

What's that concern based on? quic-go is not a good example, it's replicating internal go library code that needs to be adapted on every release, thus the qtls-<goversion> package. That has nothing to do with gogo-protobuf.

**Comment by sten0** [comment]
@acolomb 

> @sten0 I'm trying to replicate this, but having trouble trying to build it under Ubuntu 20.04 LTS.  Shouldn't a `dpkg-buildpackage --no-sign -d` work
 > from a checkout of your Salsa repo?

 Attempting to build Syncthing 1.18.6~ds1-1 (or newer) on Ubuntu 20.04
 will fail early during dependency resolution, at a minimum, because
 golang-github-marten-seemann-qtls-go1-18-dev exists exclusively in
 Debian sid/unstable as of two days ago.  If your interest is in
 providing a Debian-Policy-compliant package via PPA for Ubuntu 20.04,
 then I'd recommend the following general-case backporting strategy:

 1. Backport (or ask to have it backported) 1.18.6~ds1-1 to bullseye,
 making adjustments as necessary.  Some dependencies may also need to be
 backported.  At the moment I'm focused on sid/unstable, but when I have
 free time I'd be happy to help with this effort.  At this point you'll
 have a package that works on Debian 11 (bullseye).

 2. Branch 1.18.6~ds1-1~bpo11+1 to jammy-backports, make adjustments, and
 don't forget to use the Ubuntu `dch` options to generate the correct
 "~ubuntu" suffix.  Some dependencies may also need to be backported, and
 should be provided in the PPA.  If I remember correctly the state of
 Debian sid/unstable and testing is currently about 2.5 months newer than
 Ubuntu 22.04.  At this point you'll have a package that works on Ubuntu
 22.04, that will provide smooth upgrades when users upgrade to Ubuntu
 22.10 (fast stream) or Ubuntu 24.04 (LTS stream).

 3. "Sloppy" is a Debian convention that indicates the packages is not
 taken from stable_release +1, but from what will become stable_release
 +2.  Upgrades skipping stable distribution releases are not supported,
 and this convention helps users and admins identify packages that may
 cause a "failed to upgrade" state.  I believe this is also why Ubuntu
 upgrade instructions recommend removing packages installed via PPAs
 before upgrading between major versions of the distribution.  Create a
 focal-backports-sloppy branch by branching from either:

   a) jammy-backports (ideally the release tag), or
   b) 1.18.6~ds1-1~bpo11+1, and apply the same adjustments as the
   jammy-backports branch.

 4. The next step is to apply another round of adjustments that may be
 required to backport a package that works on Ubuntu 22.04 to Ubuntu
 20.04.

 Yeah, this method is a lot of work, but that's the cost of providing
 newer software with on LTS releases with verifiability, reproducibility,
 reusability by downstreams, etc--and without needing to provide a
 "upgrades unsupported" disclaimer.  This is the "how" of why upgrades
 between stable Debian releases go smoothly, and likely the reason why
 Ubuntu is based on Debian.

 If you're actually asking how I tested that protobuf was required, here
 is how to replicate my experiment.

```diff
 diff --git a/debian/control b/debian/control
 index b2f8931d3..b9cf9d708 100644
 --- a/debian/control
 +++ b/debian/control
 @@ -26,7 +26,6 @@ Build-Depends: debhelper-compat (= 13),
                 golang-github-d4l3k-messagediff-dev,
                 golang-github-golang-groupcache-dev,
                 golang-github-oschwald-geoip2-golang-dev,
 -               golang-github-gogo-protobuf-dev (>=1.2.1+git20190611.dadb6258),
                 golang-github-lib-pq-dev,
                 golang-github-minio-sha256-simd-dev,
                 golang-github-audriusbutkevicius-pfilter-dev,
 @@ -84,7 +83,6 @@ Depends: ${misc:Depends},
           golang-github-d4l3k-messagediff-dev,
           golang-github-golang-groupcache-dev,
           golang-github-oschwald-geoip2-golang-dev,
 -         golang-github-gogo-protobuf-dev (>=1.2.1+git20190611.dadb6258),
           golang-github-lib-pq-dev,
           golang-github-minio-sha256-simd-dev,
           golang-github-audriusbutkevicius-pfilter-dev,
```
 I saw no reason to make the Salsa project unbuildable, merely as an
 experiment, so didn't push this commit ;-)  'Hope this helps!

 Cheers,
 Nicholas

**Comment by sten0** [comment]
@imsodin

> > concern that the currently-unmaintained gogo protobuf will break when Go 1.19 is released, similarly to how quic-go broke with 1.18;
> 
> What's that concern based on? quic-go is not a good example, it's replicating internal go library code that needs to be adapted on every release, thus the qtls- package. That has nothing to do with gogo-protobuf.

Apologies for the bad example.  Please note in my initial post, "A member of the Debian Go Packaging Team (not aviau) recommended that someone should ask…"  The request took place on #debian-golang on OFTC.  I have requested that this colleague follow-up at this issue.

**Comment by zhsj** [comment]
Hi,

I asked this on IRC. The reason is that gogo/protobuf is unmaintained for 2 years, see https://github.com/gogo/protobuf/issues/691

This concern is not related to Debian packaging, but a general dependency concern.

**Comment by acolomb** [comment]
I don't intend to build a PPA version, no. Was just asking because I wanted to investigate why it's needed at all for a git checkout where the .pb.go files are already present. But that has been clarified.

**Comment by aviau** [comment]
Hey, I haven't read the whole thread but:

> @aviau, would you care to comment?

This issue isn't very Debian-specific. Ideally syncthing switches to a maintained version, and makes things easier for us.

Technically Debian can work around all kinds of vendoring issues, but they become heavier and heavier to maintain.

At the same time I understand syncthing wants the protocol to stay compatible so I don't know the details of the challenges for that.

**Comment by calmh** [comment]
Protocol wise it should fine. Our challenges are internal;

- We use specific naming of fields in generated structs, which we could no longer control. This is mostly cosmetic.
- Everything that isn't a built-in type becomes a pointer, so instead of `[]Block` we'd get `[]*Block` and similar. This means we need to use getters or nil checks when digging into structs, and need to take care when setting values that intermediate levels are initialized. This is annoying because our current way of doing it would mostly compile but panic at runtime.
- We can't control struct tags any more so API objects might get different JSON naming which might be annoying to fix.
- Given the above we can probably forget seralizing/deserializing XML properly, so we'd have to do something specific for the config handling, where the structs are currently generated from protobuf. Similarly our handling of defaults would need to change, maybe using protoreflect or something.
- The generated structs are bigger, containing unexported things like mutexes, which apart from being less efficient in some cases (large block lists) also means structs cannot be passed by value, they must be passed by pointer, which has further effects in some cases (requiring copies if we change values etc).

So it's a large change, with many of the changes being undesirable in general -- not just a question of annoying work but the end result being strictly better than what we have today.

**Comment by sten0** [comment]
@calmh

> Protocol wise it should fine. Our challenges are internal;
> 
> * We use specific naming of fields in generated structs, which we could no longer control. This is mostly cosmetic.
> * Everything that isn't a built-in type becomes a pointer, so instead of `[]Block` we'd get `[]*Block` and similar. This means we need to use getters or nil checks when digging into structs, and need to take care when setting values that intermediate levels are initialized. This is annoying because our current way of doing it would mostly compile but panic at runtime.
> * We can't control struct tags any more so API objects might get different JSON naming which might be annoying to fix.
> * Given the above we can probably forget seralizing/deserializing XML properly, so we'd have to do something specific for the config handling, where the structs are currently generated from protobuf. Similarly our handling of defaults would need to change, maybe using protoreflect or something.
> * The generated structs are bigger, containing unexported things like mutexes, which apart from being less efficient in some cases (large block lists) also means structs cannot be passed by value, they must be passed by pointer, which has further effects in some cases (requiring copies if we change values etc).
> 
> So it's a large change, with many of the changes being undesirable in general -- not just a question of annoying work but the end result being strictly better than what we have today.
> 

Hm, I see what you mean...

> Probably the simplest way, though not the most elegant, would be to revert to hand written structs for all internal data structures and "just" copy to/from proto-generated structs at serializing/deserializing time...

Well, that's a viable worst-case scenario plan for when things break ;) (as is vendoring a forked+patched version, but ew)  My hope is that it's not too late for a league of projects that don't want to migrate off of gogo-protobuf to form a team to either maintain it, or enhance compatibility of one of the alternatives noted at the thread @zhsj linked to (https://github.com/gogo/protobuf/issues/691).  It sounds like this might be ideal, after all...
