### ISSUE TITLE
Minimize the need to restart API server when changing GUI settings, refuse requests while restart is ongoing.

### ISSUE THREAD

**Issue by crazygolem** [syncthing/syncthing#8255]
### Does your log mention database corruption?

No

### Include required information

* Version: `syncthing v1.19.2 "Fermium Flea" (go1.17.7 linux-amd64) docker@build.syncthing.net 2022-03-21 03:47:47 UTC [noupgrade]`
    * on Archlinux running podman 4.0.1
    * on Debian 11 running docker 20.10.5
* Browser: N/A (Using `syncthing cli` from the container)

Using `syncthing cli` to modify parameters from a script, the server regularly becomes instable, making the CLI command fail for about 15-20 seconds before becoming responsive again.

It seems that only the GUI settings are affected, with the address having the highest chance of triggering the issue.

From the CLI I could see two different errors:

> Get "http://127.0.0.1:8384/rest/system/config": dial tcp 0.0.0.0:8384: connect: connection refused

> Post "http://127.0.0.1:8384/rest/system/config": EOF

and on the server's side, there is no correlated error in the logs (I have the "failed to sufficiently increase receive buffer size" one though at startup, might it be related?)

I think this is similar to what was reported in the forum post [Automating Syncthing Installation - Linux - Centos7](https://forum.syncthing.net/t/automating-syncthing-installation-linux-centos7/17118), but in this case I prepared a script that uses docker and executes commands directly inside the container, hoping it makes it easier to reproduce the issue reliably.

The script is stress-testing the CLI with an unreasonable amount of stupid config changes, but in practice I got the same issue with just switching the address once to localhost, then setting the username and password, then switching the address back to 0.0.0.0 (which would fail more often than not).

### Stress test script

The script requires bash, tee and docker, and accepts an optional parameter (`TEMPO`) that specifies a delay between consecutive CLI commands.

```sh
#!/bin/bash

TEMPO="${1:-1}"


log() {
    printf '%s (%s) %s -> %s\n' "$(date +'%M:%S')" "$1" "$2" "$3"
}

stcli() {
    docker exec -it syncthing syncthing cli --home=/var/syncthing/config/ "$@"
}


docker run -d --name syncthing syncthing/syncthing:1.19.2 --gui-address=127.0.0.1:8384
sleep 10

################################################################################

set_gann() {
    stcli config options global-ann-enabled set "$2"
    log "$1" "$2" "$?"
}

for i in $(seq 1 2 30); do
    set_gann $i false
    sleep "$TEMPO"

    set_gann $((i+1)) true
    sleep "$TEMPO"
done | tee test-0.log

################################################################################

set_user() {
    stcli config gui user set "$2"
    log "$1" "$2" "$?"
}

for i in $(seq 1 2 30); do
    set_user $i foobar
    sleep "$TEMPO"

    set_user $((i+1)) helloworld
    sleep "$TEMPO"
done | tee test-1.log

################################################################################

set_address() {
    stcli config gui raw-address set "$2"
    log "$1" "$2" "$?"
}

{
    for i in $(seq 1 30); do
        set_address $i 127.0.0.1:8384
        sleep "$TEMPO"
    done

    for i in $(seq 31 60); do
        set_address $i 0.0.0.0:8384
        sleep "$TEMPO"
    done
} | tee test-2.log

for i in $(seq 1 2 60); do
    set_address $i 127.0.0.1:8384
    sleep "$TEMPO"

    set_address $((i+1)) 0.0.0.0:8384
    sleep "$TEMPO"
done | tee test-3.log

################################################################################

docker logs syncthing >container.log

docker container kill syncthing
docker container rm syncthing
```

**Comment by AudriusButkevicius** [comment]
Switching the address kills the http server that is being used to respond to the request, so I am not really surprised by this?

Sure, the handling could be better, but I'd say its not really a bug?

**Comment by crazygolem** [comment]
In the abstract, no it is not that surprising. In practice though, the following points makes it actually quite surprising until you get what's going on:

* The server still processes a few config changes after the command that triggers the restart. This makes it really difficult to pinpoint what is causing the issue, and makes the whole thing look random.

   In facts, for the longest time it looked to me like the cli failed always only after the *second* GUI config change, i.e. I could change the GUI address, change any other settings, and then change the GUI address again and only *then* it would fail. I even checked manually repeatedly and could get consistent results. Very unfortunate timings.
* It not only happens for the GUI's address, but for the other GUI options too and in particular changing the username and password. Is the http server supposed to restart for those too?

   I had some issues too for other non-GUI options, and at the time introduced a sub-second delay between CLI commands to mitigate it, but it was not frequent. I have to say I forgot about it when preparing the script above, and didn't attempt to reproduce that.
* The restart takes a lot more time than it takes to start the whole thing from scratch, i.e. 15-20 seconds vs. less than 10 seconds from starting the container until it is ready to accept config changes from the CLI. I get that it might need some time for a proper shutdown before starting again, but in the moment that's not the first thing that jumps to mind.
* There is the `syncthing show config-status` subcommand that tells whether a restart is required for config changes to take effect. Since this is available, I would expect syncthing to not restart itself automatically for any config change.

So whether this is a bona fide bug or just a surprising behavior to the uninitiated, I'm not sure, and it's probably not for me to decide; that's why I opened the issue.

I still spent hours trying to figure out what was going on before giving up and wrapping every `syncthing cli` call in a retry loop, I think it would be nice to at least have a line in the documentation about this behavior that is specific to configuring the GUI.

**Comment by AudriusButkevicius** [comment]
Yes, any of these,, triggers a restart, except debugging:

https://github.com/syncthing/syncthing/blob/main/lib/config/guiconfiguration.pb.go#L26-L40

**Comment by crazygolem** [comment]
I was looking at ways to work around this, and it happens also with the REST API which surprised me because [the documentation](https://docs.syncthing.net/rest/config.html) explicitly mentions that only changes that don't require a restart are applied immediately:

> When posting the configuration succeeds, the posted configuration is immediately applied, except for changes that require a restart.

(on second thought the CLI client uses the REST API, so I should have expected this...)

I guess restarting the internal http server is not considered "a restart", in the sense that it's not "a restart of syncthing itself"?

**Comment by calmh** [comment]
Indeed. It's also supposed to be effectively instantaneous, so if you're seeing it taking 15-20 seconds I think there's some additional issue in play. Perhaps connections left in close_wait block listening on the port again, or something like that.

**Comment by calmh** [comment]
I don't think there's a bug here.
