### ISSUE TITLE
Use the latest source code compiled with go.mod in go1.18 error!!

### ISSUE THREAD

**Issue by zxlhhyccc** [syncthing/syncthing#8262]
![image](https://user-images.githubusercontent.com/45259624/162608585-bb5ad3ee-b839-42df-b048-dae4b47da57e.png)
````
Building targets
github.com/syncthing/syncthing/lib/api
# github.com/syncthing/syncthing/lib/api
../../lib/api/api_statics.go:38:25: undefined: auto.Assets
../../lib/api/api_statics.go:46:25: undefined: auto.Assets
``````

**Comment by calmh** [comment]
You're not building it properly. Please see https://docs.syncthing.net/dev/building.html and, ideally, use fewer exclamation points.
