### ISSUE TITLE
[copyRangeMethod] invalid cross-device link

### ISSUE THREAD

**Issue by da2x** [syncthing/syncthing#8271]
Syncthing version 1.19.1 on Fedora Linux 35. Any recent Linux kernel should behave the same.

## How to reproduce
1. You need two disk partitions or separate disks. Both need to be formatted as either XFS or BtrFS. Cloned extents must be enabled (default for disks formatted in the last four years or so.)
2. Create a folder on each disk device.
3. Add both folders to Syncthing.
4. Open advanced settings for both folders and set [copyRangeMethod](https://docs.syncthing.net/v1.19.1/advanced/folder-copyrangemethod.html) to `ioctl`.
5. Share the folders with another device.
6. Drop a file into one of the folders on the other device.
7. Wait for it to sync.
8. Drop **the exact same file** into the other folder on the other device.

## Actual
Syncthing will fail to write the file to the second directory. It tries to share the extents between devices and fail with `syncing: dst write: invalid cross-device link`. This is the expected result for sharing extends between devices. However, it’s not the expected results for Syncthing!

## Expected
Syncthing should indeed try to reuse the extents. However, it should also detect the error and handle it by duplication/copying the bytes instead of reusing extents. (So, the expected behavior is for Syncthing to behave like `cp --reflink=auto` (best effort or fallback to copy) whereas Syncthing currently behaves more like  `cp --reflink=always` which fails in the same way in this situation.

**Comment by AudriusButkevicius** [comment]
Sounds like a Henny Youngman problem to me.

It's not the default setting specifically for this reason, and "all" is exactly there for that reason.

**Comment by imsodin** [comment]
Would it make sense to always fall back to a "normal" copy? One might want to use ioctl and not all the others, as they don't apply for all the scenarios where it works (there may be 2 folders on the same device) - however syncthing should still work if there happens to be a copy between devices. Any downsides?

**Comment by imsodin** [comment]
What I meant is the scenario where you know that e.g. only ioctl might work, but none of the others ever do. Then I'd see why you'd expect Syncthing to try ioctl, and if it doesn't work try standard. Basically all the `CopyRangeMethods` would then be `...WithFallback`. Or put differently: What's the point/use of the "and only this" behaviour - testing maybe?

**Comment by AudriusButkevicius** [comment]
The point of only this behaviour is when you want to make sure we're not creating needless copies of the same data. Having a fallback prevents that.

Whats the downside calling methods that are not supported and fail immediately?

**Comment by AudriusButkevicius** [comment]
Its the always vs auto behaviour, where auto is "all" in our case, and always is ioctl/whatever mode.

**Comment by calmh** [comment]
I think the bug here, if there is a bug, is that the documentation mentions `all` last and it's unlikely to get chosen by the user (while it is usually the right choice). Maybe it should be called `efficient` and be the the first choice mentioned after `standard`.

**Comment by calmh** [comment]
Honestly I'm not sure why we wouldn't just always have the fallback. Under what circumstances is it preferable to have the sync fail rather than get a working copy of the data? Alternatively, if we think a fallback in general is bad for whatever reason, a fallback when copying *between* folders make even more sense. It doesn't seem like we should be able to do filesystem-local operations between folders. This is similar to how we try to move and otherwise fallback to copy when doing versioning.

**Comment by da2x** [comment]
> Under what circumstances is it preferable to have the sync fail rather than get a working copy of the data?


Playing the devil's advocate for a second: Maybe for a gigantic file? I could possibly see myself wanting it to fail rather than duplicate a multi gigabyte file.

However, I would definitely prefer if Syncthing fell back to giving me a working copy and fewer errors by default.

I actually ran into this issue after editing two files on another computer. The file contents became identical after editing, and sync started failing in one of the folders on my other computer afterwards. It took me a bit to figure out what the error message meant and why it happen.

After realizing what the error meant, I assumed it was a bug that Syncthing showed me the error instead of automatically handling it with a regular copy.

I'm happy to learn deduplicating works between folders. I had assumed it only worked within one folder. The only problem remains the issue as originally reported: it should fallback to a full copy when, for whatever reason, a cloned extent can't be used.

Another reason the cloning failed would be if I had turned off cloned extents for a specific file or folder in the file system. I've not tested this, but I assume Syncthing would fail in a similar manner whereas I'd expect it to fallback to a full copy.

**Comment by AudriusButkevicius** [comment]
> However, I would definitely prefer if Syncthing fell back to giving me a working copy and fewer errors by default.
...
> The only problem remains the issue as originally reported: it should fallback to a full copy when, for whatever reason, a cloned extent can't be used.

This is what "all" mode is there for.

**Comment by calmh** [comment]
> I use ioctl because copy_file_range causes the kernel to freeze the system in certain conditions. I’ve never had any problems with the ioctl calls.

^ `all` might be too blunt a tool, apparently. I think always having a fallback would be a reasonable choice, and if the user insist on never wanting a copy under any circumstances ... just ensure it's all on the same filesystem and that the copyrange method is reliable then :shrug:

**Comment by AudriusButkevicius** [comment]
> just ensure it's all on the same filesystem and that the copyrange method is reliable then 🤷

You could equally argue that by enabling that, you ensure/guarantee that you will not need copies across filesystems.
