### ISSUE TITLE
Make path where conflicting files are stored configurable

### ISSUE THREAD

**Issue by adnoh** [syncthing/syncthing#8276]
I'm using Syncthing syncing a data folder from a software which loads every file in that folder with a specific extension during runtime.
When I'm getting a conflict there will be two files in the same folder which leads to problems, as the software loads both, and
they define internally the same things (except of the changes of course) which leads to inconsistencies or crashes.
So I would really need an option to change the filename of conflict files or to specify a folder where all the conflict files are organized like the versions folder (better option imo, but way more work to implement I guess).

Looking forward for feedback - I don't have any workaround for my problem yet.
Thanks in advance

**Comment by AudriusButkevicius** [comment]
Where the file is stored is part of the information about the file. The file being in the same directory is currently the only way we have of signalling to the user that there are conflicts. If they landed in some other directory, the user might never observe them.

Also, every device then somehow need to have the setting set the same, as some of the features relies on all devices putting files in the same place, or the features would break.

I think in your case you might just want to disable conflicts.

**Comment by adnoh** [comment]
Thanks for your response. 
It would be still nice - imo - to have them in a separate folder with their original structure like the versions - then the only thing is to raise users attention which could be by - programmatically - watching that folder for changes or raising warnings on startup/scan.

Ok...but then I'll disable it simply.
I was not even aware of that maxConflicts option, it's not showing up in SyncTrazor which I use on the windows machines.
Is this option a "per share" global one or do I need to set it on every machine?

**Comment by AudriusButkevicius** [comment]
All syncthing settings are local, and whether its per share or not depends if you edit it in the folder config or application config.

**Comment by tomasz1986** [comment]
> it's not showing up in SyncTrazor

For the record, everything is available through SyncTrayzor too. You just need to open the Advanced Configuration (see https://docs.syncthing.net/users/advanced.html).

**Comment by adnoh** [comment]
ok thank you. then I guess we can close this
