### ISSUE TITLE
Mutual encrypted sharing doesn't work (both sides with password)

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#8277]
Please forgive me if I'm wrong here, but I remember this being mentioned on the forum as untested, but as something that "should still work". However, in my testing, it seems to always fail with a "generic error".

1. On Device 1, add a new folder filled with some files to Syncthing.
2. Share the folder with Device 2, setting a password on it.
3. On Device 2, accept the folder, but change the type to "Send & Receive", while also inputting the same password.
4. The two devices connect and try to sync the files, but the process fails with a "generic error".

The final result looks like this:

![image](https://user-images.githubusercontent.com/5626656/163138964-bf492b63-7915-4cac-a692-33b78b8a2a14.png)
![image](https://user-images.githubusercontent.com/5626656/163138972-a98cf008-3bcd-4117-b591-d32fa4b2c0c6.png)
![image](https://user-images.githubusercontent.com/5626656/163138979-06e875cf-c417-4f82-957e-8a2555a8f64b.png)

Below are logs with `db,model` enabled:

- [syncthing1.log](https://github.com/syncthing/syncthing/files/8479798/syncthing1.log)
- [syncthing2.log](https://github.com/syncthing/syncthing/files/8479800/syncthing2.log)

All testing was done under Windows 10, on two different PCs. The problem isn't limited to the latest code either, as I've tested Syncthing versions up to v1.18.6, and the same errors pop up on all of them.

**Comment by acolomb** [comment]
I think it's meant to disallow any other folder type as long as the password is empty. Maybe that logic is missing or broken in the GUI code. What would be the purpose for choosing other types without giving the password?

**Comment by tomasz1986** [comment]
Can you elaborate? I'm not sure I quite understand. Just to be clear, here we're talking about a situation where both sides have been given the password.

**Comment by acolomb** [comment]
I thought you were talking about a situation where the password is not given on one side. Aren't your first two examples the same, just backwards?

**Comment by tomasz1986** [comment]
> I thought you were talking about a situation where the password is not given on one side.

Oh no, when there is no password, the devices don't even connect displaying an error message. The problem happens only when there is the same password on both sides, yet neither of the two folder types is set to Receive Encrypted.

> Aren't your first two examples the same, just backwards?

Yeah, it's the same thing eventually, but I just wanted to point out the direction of sharing the folder in case there's any difference in relation to it.

**Comment by calmh** [comment]
> same password on both sides, yet neither of the two folder types is set to Receive Encrypted.

This is something that used to work, sort off, but it was never a designed feature as there is no point to it (?), so it may have been broken by subsequently added checks.

**Comment by tomasz1986** [comment]
> but it was never a designed feature as there is no point to it (?)

I was actually thinking about this as a possible short-term solution, e.g. when we've a local Receive Encrypted folder that was shared with us previously. One day we decide that we don't want to encrypt the files anymore and would rather prefer to have it set as SR or RO. However, the original device is located in a place that we've got no immediate access to. Then, at least temporarily we could just input the original password and sync the folder unencrypted.

**Comment by calmh** [comment]
Yeah I could see that being a use case.

**Comment by tomasz1986** [comment]
That's obviously true 😉. If too difficult or complex to implement, then at least having a useful error message would be nice regardless.

**Comment by calmh** [comment]
I don't think there's a good reason for it to *not* work, so it's probably just a question of figuring out why it doesn't. (And perhaps figuring out a way to add a test.)

**Comment by kuzaro** [comment]
Hi! I have occure this problem. I've got 2 devices with setting unsecure on both. Can't sync anything.

**Comment by imsodin** [comment]
> Hi! I have occured this problem. I've got 2 devices with setting "unsecured" on both. Can't sync anything.

Not sure what this means. If you need help with your setup resp. a problem you encounter, please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.
