### ISSUE TITLE
Simplify tests using `T.TempDir`

### ISSUE THREAD

**Issue by Juneezee** [syncthing/syncthing#8279]
Currently we are using `os.MkdirTemp` and `os.RemoveAll` to create and cleanup temporary directory in tests. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 

This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.

Reference: https://pkg.go.dev/testing#T.TempDir

**Comment by calmh** [comment]
Fix by #8280
