### ISSUE TITLE
Local discovery seems to be broken for me

### ISSUE THREAD

**Issue by camoz** [syncthing/syncthing#8284]
A few months ago, local discovery stopped working for me. The devices just won't connect to each other. Previously (some months ago) it was working flawlessly. This was also an issue with 1.19.1 already, I don't know when exactly it stopped working...

### My setup

- only two devices
- Syncthing 1.19.2 on Android 12
- Syncthing 1.19.2 on Archlinux
- NAT traversal, global discovery and relaying are disabled on all devices
- Local discovery is enabled on all devices
- `Sync Protocol Listen Addresses` is set to `tcp4://:22000, quic4://:22000` on all devices
- device address is set to `dynamic`

I did not change anything in my firewall; in my nft inet filter table I have this included in my input chain:

```
udp dport 21027 accept comment "syncthing discovery"
```
### Workaround

Removing `dynamic` from the device address and setting an explicit IP:port instead instantly fixes the issue. I noticed, that the issue is also there if I have an explicit IP:port configured but then also include the `dynamic` afterwards. Just everytime `dynamic` is included, it stops working.

Update: I forgot to mention that setting at least one device to a fixed IP:port without `dynamic` already fixes the issue for me. My whole setup only involves two devices; my laptop and my phone.

**Comment by bt90** [comment]
I'm pretty sure that this is caused by Android 12. see https://github.com/syncthing/syncthing-android/issues/1628

Enabling global discovery on both devices should fix this. If not, we should analyze this in-depth in the forum:

https://forum.syncthing.net/

**Comment by camoz** [comment]
Okay. For the record, it was already working with Android 12 - but maybe syncthing-android changed the API level in the meantime (if I understand that issue correctly)...

Once https://github.com/syncthing/syncthing-android/issues/1628 is resolved, I will test this again and report back. Thanks.

**Comment by camoz** [comment]
Just installed syncthing on another laptop, and there local discovery works fine (to rule out problems with my firewall etc.). So it seems to be related to Anroid.

Closing this now. I will re-open it in case I still have this issue after https://github.com/syncthing/syncthing-android/issues/1628 is fixed.
