### ISSUE TITLE
Healthcheck has hardcoded port 8384 and fails if you change the STGUIADDRESS to another port

### ISSUE THREAD

**Issue by Tupsi** [syncthing/syncthing#8300]
The latest docker image is using this for the healthcheck:

`HEALTHCHECK &{["CMD-SHELL" "nc -z 127.0.0.1 8384 || exit 1"] "1m0s" "10s" "0s" '\x00'}`

so when you change your env STGUIADDRESS to another port in cmd or docker-compose

the healthcheck fails.

So maybe make the healthcheck port configurable as well through another ENV or better separate the port into its own env variable?

**Comment by bt90** [comment]
Why would you change the port within the container? Just change the port mapping of your container.

**Comment by Tupsi** [comment]
> Why would you change the port within the container? Just change the port mapping of your container.

because I am putting that container in a different vlan and use the docker mac_vlan option for this stack. You can not use exposing ports with that option, but as the container gets its own ip address now, there is no need to move the gui away from 443.
