### ISSUE TITLE
Resync button on each Remote Devices tab

### ISSUE THREAD

**Issue by Willtech** [syncthing/syncthing#8304]
### Resync button on each Remote Devices tab

- [ ] Alongside the `Edit` and `Pause` buttons please create a `Resync` button feature
- [ ] The feature causes synchronisation between This Device and Remote Devices.
- [ ] The button shows up when Sync percentage is not 100% after using Override or Revert button on Folders tab
- [ ] The style of the `Revert local changes` button on the Folders tabs

This solves the problem of not correctly reporting synchronisation status on Remote Devices tabs.

![image](https://user-images.githubusercontent.com/1173622/164933682-209030ed-165c-4375-b34b-3e04eaf63ba6.png)

![image](https://user-images.githubusercontent.com/1173622/164933730-382aab6c-19df-48f2-9d6e-26e627e427ce.png)

**Comment by calmh** [comment]
Whatever you envision this button would do, Syncthing already does internally, or should do. You problem, whatever it may be, is not something solved by the addition of a button and you'd be better off discussing it on the forum.

**Comment by Willtech** [comment]
It was a suggestion on [liberia.chat.irc](https://web.libera.chat/#Syncthing) already.
