### ISSUE TITLE
Option to add multiple "Windows" folder to one folder of "Syncthing"

### ISSUE THREAD

**Issue by collital-coder** [syncthing/syncthing#8313]
I want to sync documents and pictures folder to syncthing and it's even done but when I make changes to the original document folder in PC it is not reflected into synthing and gets synced to all of my devices.
 

![image](https://user-images.githubusercontent.com/100809947/166133896-effb2179-dc6e-4bf1-87d4-7995df2f5283.png)
this is my sync folder with my another device

![image](https://user-images.githubusercontent.com/100809947/166133905-fb4ad3f8-3b02-4fd7-a2f9-b45db48e6d6c.png)
this is original folder

![image](https://user-images.githubusercontent.com/100809947/166133911-fa365588-c781-45bb-8b04-26d814261774.png)
this is sync folder

I mean you could just add a motion to add multiple folder under 1 category like
>PC FOLDER
     -DOCUMENTS
     -IMAGES
     -C://user/files/imp document/

>office clint sync'
       -c://user/clint files/
       - c://user/ clint images/project_xx/

**Comment by collital-coder** [comment]
sorry second image by mistake copied wrong 
![image](https://user-images.githubusercontent.com/100809947/166134043-8570c603-136a-4c09-93d7-63d5f47dbc5b.png)
my document folder

**Comment by tomasz1986** [comment]
It's not really clear what you're trying to do, but please open a new topic at https://forum.syncthing.net if you want to receive help with this matter. GitHub is used for tracking reproducible bugs and reasonable feature enhancements, while the forum is the place to go for other types of support.
