### ISSUE TITLE
Build errors with v1.20.0

### ISSUE THREAD

**Issue by aptalca** [syncthing/syncthing#8318]
Trying to compile v1.20.0 results in the following error:
```
go: golang.org/x/tools@v0.1.7 requires

	github.com/yuin/goldmark@v1.4.0: missing go.sum entry; to add it:

	go mod download github.com/yuin/goldmark
```

Thanks

**Comment by aptalca** [comment]
When that's preempted via `go mod download github.com/yuin/goldmark`, then there is another issue:
```
/root/go/pkg/mod/github.com/cpuguy83/go-md2man/v2@v2.0.1/md2man/md2man.go:4:2: missing go.sum entry needed to verify package github.com/russross/blackfriday/v2 (imported by github.com/cpuguy83/go-md2man/v2/md2man) is provided by exactly one module; to add:
        go get github.com/cpuguy83/go-md2man/v2/md2man@v2.0.1
exit status 1
```

**Comment by imsodin** [comment]
What are you doing? I just downloaded the source boundle, extracted it and ran `go run build.go install` as documented and that works for me.

**Comment by aptalca** [comment]
Here's the Dockerfile: https://github.com/linuxserver/docker-syncthing/blob/master/Dockerfile#L33-L36
And here's the build log: https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-syncthing/detail/master/367/pipeline

**Comment by aptalca** [comment]
ah, I was using go 1.16 that comes with alpine 3.14.
Tried alpine 3.14 with go 1.17.9 and that seems to build fine.

Sorry for the noise

**Comment by aptalca** [comment]
We'll switch to building with go 1.18 https://github.com/linuxserver/docker-syncthing/pull/56

Thanks for the heads up
