### ISSUE TITLE
Windows Symlink and Disk load point support

### ISSUE THREAD

**Issue by pdj9na** [syncthing/syncthing#8322]
To make a synchronization folder that can synchronize everything on Windows, you can load each disk partition into a blank folder that looks like a symlink, and then use the directory above the disk mount point as the synchronization folder to synchronize all files that can be synchronized.Use ignore lists to control files that do not need to be synchronized

**Comment by calmh** [comment]
We're not going to follow symlinks, on Windows or otherwise. Disk mount points sound like it should be transparent or already work -- is that not the case?
