### ISSUE TITLE
Cygwin version of Syncthing

### ISSUE THREAD

**Issue by pdj9na** [syncthing/syncthing#8326]
Request a Cygwin version of Syncthing to simplify symlink and disk mount point implementation

**Comment by Script-Mak3r** [comment]
To quote @calmh:

We're not going to follow symlinks, on Windows or otherwise. Disk mount points sound like it should be transparent or already work -- is that not the case?

**Comment by calmh** [comment]
I'm pretty sure we're also not going to build a Cygwin version, whatever that is, given that there is a native Windows version and a native Linux version that will run fine under WSL...

**Comment by imsodin** [comment]
Agreed. This sounds like a support question about "how to run Syncthing under Cygwin". Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
