### ISSUE TITLE
Could it support "Selective Sync",such as NAS?

### ISSUE THREAD

**Issue by ErDongChen1973** [syncthing/syncthing#8330]

**Comment by tomasz1986** [comment]
Probably a duplicate of https://github.com/syncthing/syncthing/issues/2491?

You can actually use ignore patterns (see https://docs.syncthing.net/users/ignoring.html) to do "selective" sync already. Yes, it's a little clunky, and you do still need to manually delete files from the disk after ignoring them, but it does the job nevertheless.

**Comment by ErDongChen1973** [comment]
> Probably a duplicate of #2491?
> 
> You can actually use ignore patterns (see https://docs.syncthing.net/users/ignoring.html) to do "selective" sync already. Yes, it's a little clunky, and you do still need to manually delete files from the disk after ignoring them, but it does the job nevertheless.

Thank u for your reply！
