### ISSUE TITLE
Default folder per shared device

### ISSUE THREAD

**Issue by robsonsobral** [syncthing/syncthing#8332]
I loved the idea of **Auto Accept** shared folders per device. Really useful! May I ask for an improvement?

If we could set the default sync folder for a shared device, the auto accepted folders could nest on it. I could be called, I don't know...., **root folder**? It would be available only in case the **Auto Accept** is enabled.

What do you think?

Thank you all!

**Comment by tomasz1986** [comment]
By "nest" do you mean that the folders would be nested according to their labels? Is your proposal by any chance similar to what was suggested in https://github.com/syncthing/syncthing/issues/6718? If yes, than that one was rejected with very clear reasons behind it, so what you want here isn't likely to happen.

**Comment by robsonsobral** [comment]
Thank you for your attention, @tomasz1986 .

No, my proposal isn't like that.

The interface says, at helper text for **Auto Accept**:

>Automatically create or share folders that this device advertises at the default path.

My suggestion is to offer a way to override the default path, which is by default `~/Sync`, for that specific remote device.

> If you're suggesting something else, please provide some more concrete examples, as it's difficult to deduct the exact behaviour that you're asking for 😉.

Like this?

![image](https://user-images.githubusercontent.com/931642/167317416-cfa5eab4-3981-45bc-999a-bf979e577799.png)

Better?

**Comment by imsodin** [comment]
Folders aren't per device. You can't have the same folder for Device A at a distinct path from the same folder for Device B. Now it might be in your case (you simply only ever share one folder with one device), but that doesn't hold true in general. So this could only apply to entirely new folders. And it seems weird (as in confusing) behaviour if a folder is created at different paths depending on which device happened to share it first.

I definitely don't want something like this personally (as in I won't implement it), but I am undecided whether it's more harmful (potential confusion) compared to useful (at least one person wants it) for the project. As in should it stay open as one of those "probably never going to happen" enhancements or closed as "undesired within the project".

**Comment by AudriusButkevicius** [comment]
I personally agree, and don't think this makes much sense. The whole auto-accept is a can of worms in itself from behaviour and security perspective and I somewhat think was a mistake to support.

**Comment by calmh** [comment]
Currently, when auto accepting a folder that doesn't exist yet, we generate a folder path based on the root and the folder name-or-label sanitized. If we allowed some configurability in how generated that folder path, say by having placeholders like `$folderID`, `$folderLabel`, `$deviceID`, `$deviceName`, we could allow the generated folder path to be `~/folders/$deviceID/$folderLabel`. We would of course apply sanitation.

I could see this being useful if there is a central server with auto-accept enabled and a number of clients who can just share their folders with it for backup purposes...

But as described, I think not.
