### ISSUE TITLE
"Out of Sync Items" report "0 items" when syncing 0-byte files

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#8334]
1. Share an empty folder between Device 1 and 2.
2. On Device 1, add a large number (e.g. 10,000) of 0-byte-sized files to the folder.
3. Wait for the files to start being pushed to Device 2.
4. During the synchronisation, Device 1 reports an incorrect number of "Out of Sync Items". It is stuck at "0 items", even though in reality there are 10,000 files being synced. If you click on the "0 items" link though, all the 10,000 files are displayed there correctly.

![image](https://user-images.githubusercontent.com/5626656/167316875-f53d715b-8683-4957-b69a-da00a2778568.png)

**Comment by BirdInFire** [comment]
I have the same problem when 2 system sync on the same file and the first delete a file the second was in queue to sync, the only way to fix this (i have found is to delete the sync and redo it)

**Comment by calmh** [comment]
That sounds like not the same problem at all.

**Comment by BirdInFire** [comment]
> That sounds like not the same problem at all.

the symptom are the same "out of sync 0 item 0byte", the only "difference" is in my case the sync never end

**Comment by vacari** [comment]
I have the same problem here. Several years ago.
In my case 4 Windows PCs sync some folders.
Sometimes one of them complains about syncing several files between 2 others.
Not all PCs are always online.

<img width="682" alt="image" src="https://user-images.githubusercontent.com/6704887/173265529-02ae8d8a-4598-419b-98d3-3492f4ff4c7e.png">

In this case, NNE0157 is the device that is out of sync with E7440__OFFICE and also with E7440__HOME.
In HOME it informs OFFICE as modified.
In OFFICE, it reports HOME as modified.

However, HOME and OFFICE devices do not report any sync errors. Not even on a 4th device.

If debug files are needed for debugging, I'd be happy to try and capture them to help. Just tell me how and where.

Thank you so much for reading and more, for this wonderful software.

**Comment by er-pa** [comment]
Is this issue still current?

I've been trying to reproduce it in several settings, without 'success'. In all cases, when creating a bunch of zero B files, the amount of 'Out of Sync Items' is being updated correctly (on Device 1, in the Remote Device screen of Device 2).

**Comment by tomasz1986** [comment]
> Is this issue still current?
> 
> I've been trying to reproduce it in several settings, without 'success'. In all cases, when creating a bunch of zero B files, the amount of 'Out of Sync Items' is being updated correctly (on Device 1, in the Remote Device screen of Device 2).

It is still relevant. I've just reproduced using the current `main` following the exact same steps as described originally.

Just in case, I'm attaching logs with `db,model` enabled.

- [syncthing1.zip](https://github.com/syncthing/syncthing/files/9613991/syncthing1.zip)
- [syncthing2.zip](https://github.com/syncthing/syncthing/files/9613993/syncthing2.zip)

**Comment by calmh** [comment]
Yeah, I can't reproduce, this works as expected for me with the described methodology. 

https://cdn.kastelo.net/rfi/gscnvt.mp4
