### ISSUE TITLE
Syncthing should stop assuming it is the only software running on a machine

### ISSUE THREAD

**Issue by wiwwo** [syncthing/syncthing#8336]
Syncthing should stop thinking it is the only software using the home directory.  `~/Default Folder` means nothing to me, and 99% of the times it already exists and has nothing to do with Syncthing.
At startup, as an optional step if you want, whether this is a new instance or another instance of an already existing "cluster", Syncthing should ask for a "base directory", so not just create the (shared) folder in my home, wherever he feels to, but (for example) have all folders in `[let_me_choose_where]` path, like `~/Syncthing/[.....]`.

By an user that loves your product.

**Comment by calmh** [comment]
All these things are settable via environment variables or command line switches though, and I'd be willing to bet that Syncthing is one-instance-only (per user) in a very large majority of installations...

**Comment by wiwwo** [comment]
Of course there is only one instance of shyncthing in my machine, but there is other software in my machine, and "Default Folder" does in any way make me thing "Oh, of course, Syncthing!", makes me thing "Eh, what is this?!?".

**Comment by calmh** [comment]
Again you seem to be talking about the default folder. You can disable that, or remove it once.

**Comment by wiwwo** [comment]
Giving up.
Sorry, just wanted to help.
Thanks! :-)

**Comment by tomasz1986** [comment]
> ~/Default Folder

Just for clearance, even though the label in Syncthing is indeed `Default Folder`, the actual folder name on the disk is not that, but `Sync`. It could probably be called `Syncthing` for better clarity, but I wouldn't say it's that bad either. There's been an issue somewhere about having a proper first run wizard that'd provide the user with instructions and basic settings, etc. in advance.
