### ISSUE TITLE
Syncthing should stop assuming it is the only instance in a Syncthing "cluster"

### ISSUE THREAD

**Issue by wiwwo** [syncthing/syncthing#8337]
First start of Syncthing is a complete mess when joining an already existing cluster/rung/whatever you want to call it..
Sorry to say so, but it is *extremely* painful, confusing, and still having 5 instances already, i *all the time* have to reset everything and re-start again.

Syncthing must change the first start as it is the only instance (which is true 1 out or n -with n>1- of the times) and it should have a "Am I joining some other instances you already have?" welcome screen, so that Default Folder is not created, and this new instance must just join the other instances, etc etc etc.

By an user that loves your product.

**Comment by calmh** [comment]
Please explain what the complete mess is in more detail. I hear you on "it creates a default folder which I don't want" (which you can disable) but I don't see anything else actionable here.

**Comment by wiwwo** [comment]
Syncthing starts, creates a "Default Folder", then it joins other instances and creates other "Default Folder" directories, and then asks, for every other instance, "Do you want to share stuff with instance X"? I have 5 instances, I have being asked 5 times to accept sharing Default Folder from the 5 different instances.
And, again, I ended up having the "local" Default Folder and the "shared" default folder.
Mess.

Please do not take this personal, but understand and believe me, UX is terrible.

**Comment by wiwwo** [comment]
Giving up.
Sorry, just wanted to help.
Thanks! :-)
