### ISSUE TITLE
Filename case renaming issue (sync between pc and android). File gets removed.

### ISSUE THREAD

**Issue by vcotu** [syncthing/syncthing#8338]
Issue:
- syncing a folder between two devices in local network: android phone + pc computer
- rename file "Health.txt" to "health.txt" in pc
- it renames correctly the filename in android, but 10 or so seconds later, syncthing says that the android side has removed health.txt
  which is not true, and then removes health.txt on pc and in the phone too.

Other info:  
- if I rename the file in android, then everything works ok, file is correctly renamed on pc and is not deleted anywhere.
- using nautilus (files) or using mv in a command line to rename the file = same results
- if I pause folder sync on android and then I rename in desktop, and then later I restart folder sync in android, it still removes the file.
- regular renames without changing filename case work ok.

I don't know if it's an issue with the desktop app of with the android app, so I posted here.

desktop computer:
OS: GNU/Linux 5.10.109-1-MANJARO x86_64 
syncthing linux version: v1.19.1 "Fermium Flea" (go1.17.7 linux-amd64) syncthing@archlinux

phone (Samsung):
OS: Android 11
syncthing android version: v1.20.1

[pc-log.txt](https://github.com/syncthing/syncthing/files/8668779/pc-log.txt)
[android-log.txt](https://github.com/syncthing/syncthing/files/8668771/android-log.txt)

**Comment by tomasz1986** [comment]
This is supposed to have been fixed in https://github.com/syncthing/syncthing/issues/7974. Can you still reproduce after upgrading your Linux version of Syncthing to v1.20.1?

**Comment by vcotu** [comment]
I did search for previous issues but didn't find that one... my fault.

I've just installed v1.20.1 in the pc, and I'm still having the same issue, though.

**Comment by imsodin** [comment]
You need it on android.

**Comment by vcotu** [comment]
On android I have already v1.20.1

**Comment by vcotu** [comment]
I'm still having the same issue.. please reopen issue, both linux pc and android using syncthing v1.20.1
After 20 seconds the file is removed on both sides.
I post updated logs.

desktop computer:
OS: GNU/Linux 5.10.109-1-MANJARO x86_64
syncthing v1.20.1 "Fermium Flea" (go1.18.1 linux-amd64) teamcity@build.syncthing.net

phone (Samsung):
OS: Android 11
syncthing android version: v1.20.1

[pc-log.txt](https://github.com/syncthing/syncthing/files/8670278/pc-log.txt)
[android-log.txt](https://github.com/syncthing/syncthing/files/8670282/android-log.txt)

**Comment by vcotu** [comment]
I'm still having the same issue.. please reopen issue, both linux pc and android using syncthing v1.20.1
After 20 seconds the file is removed on both sides.
I post updated logs, STTRACE=db,model,fs

desktop computer:
OS: GNU/Linux 5.10.109-1-MANJARO x86_64
syncthing v1.20.1 "Fermium Flea" (go1.18.1 linux-amd64) teamcity@build.syncthing.net

phone (Samsung):
OS: Android 11
syncthing android version: v1.20.1

[pc-log.txt](https://github.com/syncthing/syncthing/files/8670632/pc-log.txt)
[android-log.txt](https://github.com/syncthing/syncthing/files/8670634/android-log.txt)
