### ISSUE TITLE
'(Unknown device)'

### ISSUE THREAD

**Issue by J-MR-T** [syncthing/syncthing#8340]
# The Bug
For some reason, the web ui always shows 'unknown device' on one of my three devices:
![image](https://user-images.githubusercontent.com/40471097/168148330-ea09546d-153e-4dac-b3a7-ab9c82ab3b18.png)

The syncing itself is actually working fine, but only with what I have configured before this started happening, but now I need to add a new folder and need to access the web ui on my device.

- what happened: Nothing that I know of, this bug just started to appear at some point
- as I have no idea what caused it and haven't actively changed anything, I can't really be sure how to reproduce this

# Background/System Information
output of `syncthing cli show version`:
```json
{
  "arch": "amd64",
  "codename": "Fermium Flea",
  "date": "2022-05-03T17:47:09+02:00",
  "isBeta": false,
  "isCandidate": false,
  "isRelease": true,
  "longVersion": "syncthing v1.20.0 \"Fermium Flea\" (go1.18.1 linux-amd64) syncthing@archlinux 2022-05-03 15:47:09 UTC [noupgrade]",
  "os": "linux",
  "stamp": "1651592829",
  "tags": [
    "noupgrade"
  ],
  "user": "syncthing",
  "version": "v1.20.0"
}
```
- kernel: 5.17.5-arch1-1
- browser: unggogled chromium 95.0.4638.54 (I don't see how it could be the browser, but I thought it wouldn't hurt to include it)

**Comment by J-MR-T** [comment]
Something to note: `syncthing cli show system` seems to have all the right data about my device

**Comment by tomasz1986** [comment]
It seems that your Web GUI is simply unable to load. You should try using a different browser if you haven't yet, but before all, please open a new topic at https://forum.syncthing.net if you want to investigate this further. GitHub is only used for reproducible bugs and reasonable feature requests.
