### ISSUE TITLE
Copyright holders, licence, and year for both the png and svg variants of the Syncthing icon

### ISSUE THREAD

**Issue by sten0** [syncthing/syncthing#8347]
Hi,

I'm in the process of packaging [Syncthing Tray](https://github.com/Martchus/syncthingtray) for Debian, and I need to accurately represent the copyright for the Syncthing icon.  #998 indicates that the PNG variant is in fact MIT/Expat rather than MPL-2.0, and I'd like to confirm that this is in fact the case.

Is the SVG variant also under MIT/Expat license?

Finally, who holds the copyright for these files?  The same person?  My best guess right now is that it's a composite of
```
    2015 Jack Palevich
    2014 The Syncthing Authors
    2015 Audrius Butkevicius and Contributors
```
but I suspect that this list is too long.

Thanks in advance for a rapid response!  Ambiguity about copyright year[s], copyright holder[s], and licence for these two files is the only remaining issue blocking the upload of Syncthing Tray to Debian.  By the way, my motivation for packaging this software is to encourage wider adoption of Syncthing, and I believe that desktop integration furthers this goal :)  Thank you once again for your wonderful software!

Regards,
Nicholas

**Comment by sten0** [comment]
> It's under the same MPLv2 license, copyright The Syncthing Authors, as the rest of the code.

@calmh, by "It's" do you mean the SVG is MPLv2, or do you mean they've both been relicensed to MPLv2?  To be totally accurate, I need to know what the license for each of these files was in 2016.

> So the icon was there before we moved to GPL, which means you can still legally get it under MIT.
> @gillisig might have a SVG one, but there already is a pretty big one [here](https://github.com/syncthing/syncthing/tree/master/assets) plus the Adobe Illustrator file which might be vector graphichs?

_Originally posted by @AudriusButkevicius in https://github.com/syncthing/syncthing/issues/998#issuecomment-64080044_

/\ this is why MPLv2 isn't obvious ;)

**Comment by calmh** [comment]
Many things existed in the repo before licenses changed. I guess you can check it out at that point in time and use it with the license in effect at that time. Currently the license is MPLv2, as the icons that existed in the repo were included in the change and anything produced since then would have been created under the license of the time.

**Comment by gillisig** [comment]
I made the logo years ago and I think I gave the copyright away to the project itself if I remember correctly. So I guess in this case it makes it whatever the license for the project is.

**Comment by sten0** [comment]
@calmh You added `assets/logo-only.svg` in b322b527b3e1410d8f1a6aff73dd4c38cb2a61e1 (2015-03-10) when LICENSE was GPL-3+, thus this file would seem to be GPL-3+, while the preexisting PNG was still MIT/Expat.  For the purposes of simplicity it would also be permissible to interpret the PNG as GPL-3+ at this time, since Expat ->to->GPL-3+ is permitted.

The PNG ceased to be MIT/Expat in 9cc49aea7752a40f63011277bd1db4f85763b391 (2020-01-16) when it was regenerated from the SVG, and at this time LICENSE was MPLv2, except that GPL-3+ -> MPLv2 is not permissible, so I'm guessing this means that the SVG implicitly became MPLv2 at this time, which is permissible because "The Syncthing Authors" hold the copyright to this file?

Does that sound like an accurate assessment to you?
Thanks again!

@gillisig thanks for confirming, yes, that makes things simpler and helps a lot :)

**Comment by tomasz1986** [comment]
> The PNG ceased to be MIT/Expat in [9cc49ae](https://github.com/syncthing/syncthing/commit/9cc49aea7752a40f63011277bd1db4f85763b391) (2020-01-16) when it was regenerated from the SVG

Just for clearance, nothing was regenerated in that commit. I just processed the existing files through FileOptimizer, which compressed them losslessly using a variety of tools. The losslessly compressed files were then re-added to Syncthing.

**Comment by calmh** [comment]
We changed license a couple of times. Both me and gillisig signed off on those changes. If you check out the repo now and grab something from it, the current license applies.

If you check out the repo from some before the changes, some other license applies to the files from that time.

**Comment by sten0** [comment]
Thank you everyone for the help :)  With this I was able to write a clear picture of the history, with clear recommendations (including "the simplest and most reasonable" option) to Syncthing Tray maintainer.  Take care!

**Comment by sten0** [comment]
After months of waiting the ftpmaster review in Debian has occurred, and I was asked if the Adobe Illustrator file[s] for the icon could be provided--or if they were lost to time.  @gillisig, do you know?  It's not the end of the world if they were lost...  Thanks again for taking the time to reply!

**Comment by calmh** [comment]
It's right there in the repo.

**Comment by sten0** [comment]
Jakob Borg ***@***.***> writes:

> It's right there in the repo. 
>

Thanks for the quick reply and <facepalm> sorry for somehow missing
assets/logo.ai
