### ISSUE TITLE
GUI continually restarts with "Syncthing seems to be down" error if there are no new events

### ISSUE THREAD

**Issue by cincodenada** [syncthing/syncthing#8354]
Version info:
 - Syncthing v1.20.1, Linux (64-bit Intel/AMD) "Fermium Flea" Build 2022-05-04 (noupgrade)
 - Firefox 102.0a1 (2022-05-20) (64-bit) on Ubuntu Linux 20.04

After loading the GUI, every 30 seconds or so I get the "Syncthing seems to be down..." Connection Error box, and the GUI restarts. This happens continuously in a loop. I believe my connection is fine - looking at the network tab, I don't have any errors, and everything else is working fine otherwise.

I did some debugging and have traced it to the `/events?since=` longpoll in `eventService.js`:
https://github.com/syncthing/syncthing/blob/1eda82b95f4dc51cfa753e4763c865277509ce5b/gui/default/syncthing/core/eventService.js#L36-L38

My network tab in Firefox shows this request resolving with an empty 200 response after about 30 seconds:
![events-since](https://user-images.githubusercontent.com/479715/169670877-06dd2e60-dbdc-4069-a625-e29e5fd18515.png)
However the `.error()` callback is called, which results in the `OFFLINE` event being broadcast and the GUI restart.

Here are my logpoints and the output of them, which is how I arrived at my above conclusions:
![logging](https://user-images.githubusercontent.com/479715/169670978-2c36bccf-49f6-46ea-92a5-f4e4eba1e3c2.png)
![logs](https://user-images.githubusercontent.com/479715/169670982-f2a3dabf-8e7e-4e82-9e01-978920da386a.png)

I'm not sure when this started happening - I was able to reproduce it back to v1.13.0, past then my builds wouldn't start up due to a clientHelloInfo mismatch. I don't recall it happening before when I was on v1.1, but I can't say for sure, and I can't downgrade that far because my database requires v1.9.0 minimum.

I also saved an [HTTP Archive and pcap dump](https://github.com/syncthing/syncthing/files/8748544/network.tar.gz) of the network traffic for an example of it restarting twice - I'm a little rusty on my TCP, but it looks like the client is hanging up on the server, judging by the RSTs in there?

**Comment by AudriusButkevicius** [comment]
This looks more like a support request given its specific to you, as otherwise we'd have a lot of people with the same issue. Please use the forum - https://forum.syncthing.net/ - first by searching for any similar issues and then by posting a new one when required.

Thanks!
