### ISSUE TITLE
Upgrading from v1.19.2 to v1.20.x now requires chmod for syncing files

### ISSUE THREAD

**Issue by Chris3773** [syncthing/syncthing#8355]
After upgrading from v1.19.2 to v1.20.1 syncing of files fails with `syncing: chmod ...: operation not permitted` when trying to write data changes.

This was working in v1.19.2 with Restricted ACL mode for the data directory. I would rather not remove Restricted mode as it breaks other programs as it's a SMB share location.

Setup:
- Syncthing v1.20.1, Linux (64-bit Intel/AMD)
- Running on TrueNAS-SCALE-22.02.1 as a docker image
- The data directory is a ZFS dataset with Restricted ACL mode enabled
- The syncthing user account has read and write access to the data directory

**Comment by calmh** [comment]
Syncthing always chmods files as part of syncing them. Perhaps you want to set the "ignore permissions" option?

**Comment by Chris3773** [comment]
The "ignore permissions" option was and is set.

**Comment by calmh** [comment]
Interesting. Can you post a real log with more context?

**Comment by Chris3773** [comment]
The only thing that shows up in the log is `syncing: chmod ...: operation not permitted` and it trying after a few minutes.

**Comment by calmh** [comment]
Yeah I don't see how that can happen, so without a full log and ideally corresponding config I'm lost.

**Comment by tomasz1986** [comment]
Maybe related?

https://github.com/syncthing/syncthing/pull/8235

This seems to be the only recent change related to `chmod`.

**Comment by imsodin** [comment]
Yes, that's likely it @tomasz1986 . That mistakenly changed behaviour (error returned on chmod instead of only on the actual operation), while it's actual purpose was to change the permission bits. I'll revert those bits.
