### ISSUE TITLE
About custom certificate consultation

### ISSUE THREAD

**Issue by Ran-Xing** [syncthing/syncthing#8357]
### info
command: syncthing

- I am using a custom certificate, since I want to encrypt, users should be allowed to use their own certificate
- ...
- ...
- I tried using -cert / --cert and it didn't work
- I tried replacing cert.pem with no effect either
- If possible, I hope to generate a certificate based on cert.pem

**Comment by Ran-Xing** [comment]
中 English communication , come have come go
😅

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
