### ISSUE TITLE
relays endpoint isn't available

### ISSUE THREAD

**Issue by Quake4** [syncthing/syncthing#8360]
![image](https://user-images.githubusercontent.com/29517243/169973854-bec27dd3-83fb-4ca2-8610-5119f504c4c8.png)
![image](https://user-images.githubusercontent.com/29517243/169973921-893a2f97-1773-4e33-98d6-256d00f09aa3.png)

**Comment by serjevski** [comment]
> Seems like syncthing servers blocked by russian censorshop agency.

Yeah it's right. 
As a workaround, You may use own discovery and/or relay services

**Comment by azatsh** [comment]
Has anyone found any workaround ?

**Comment by Quake4** [comment]
I have a vpn network, I just entered `tcp://<ip>` in the address instead of dynamic
