### ISSUE TITLE
Catching Malware

### ISSUE THREAD

**Issue by Oscaramr** [syncthing/syncthing#8363]
If one of your devices are compromised and they want to mess with your files can you detect that and isolate that device and stop the changes from happening. I am running 3 different devices that could be hacked. Not that I know but they have malware. All running alot of software. I do keep everything up to date programs packages os, everything. I never had a ransom attack but i want to take that extra measure incase. One way i think i can solve this is a cronjob on my server that copies the files every 24hours to another folder and since i use my devices i can catch the files before the cron jon runs again.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
