### ISSUE TITLE
Syncthing caused blue screen

### ISSUE THREAD

**Issue by 411A** [syncthing/syncthing#8366]
Hi, I'm using Syncthing (v1.20.1) to sync the Obsidian folder to my Android phone (Samsung A71, Android 11, Syncthing v1.20.1).
After a couple of minutes of running Syncthing, I'm getting blue screen Window.
The first time it occurred when I tried to accept the anonymous data collection message; after the restart, I said no and it was working fine (synced flawlessly without any error on the log file); but then after minutes (~5-10) of writing into the Obsidian file, the blue screen happened.
Opening and working on Obsidian alone didn't cause blue screen.
Before Syncthing I was experiencing this when I was trying to debug my Python app on VScode (everytime)! So I switched to PyCharm. Don't know what's wrong with my laptop or Syncthing.

### Does your log mention database corruption?
**NO**.

### Include required information
**Device**: Surface Pro 2017
**OS**: Windows 10 Pro
**Version and OS Build**: 21H2, 19044.1706
**Browser**: Microsoft Edge, Version 101.0.1210.53 (Official build) (64-bit)

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
