### ISSUE TITLE
Shared device names are missing from "Edit Folder -> Sharing"

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#8369]
![image](https://user-images.githubusercontent.com/5626656/171147007-d6ff10ab-8311-40d1-aa1c-2a4546e49bd8.png)

This affects the current `main` and the current RC (`v1.20.2-rc.2`). I think the problem is quite serious. It will probably cause a lot of complaints and reports if `v1.20.2` is released in this state.

**Comment by acolomb** [comment]
Good catch. That was an oversight when renaming a function in #8286.  Sorry, my bad.  A fix is imminent.

**Comment by tomasz1986** [comment]
Should this issue be labeled with "skip-changelog"? The problem is present only in the RCs of v1.20.2.

**Comment by calmh** [comment]
Yeah. It's a bit late in the cycle, but the changes are small; I'll drop an .rc-3 tomorrow.

**Comment by Ratio2** [comment]
v1.20.2
Fixed in Edit Folder -> Sharing
But still not fixed in Edit Device -> Sharing
