### ISSUE TITLE
Syncthing on samba and hidden DOS bit issue - still an issue in 1.20.1 version.

### ISSUE THREAD

**Issue by nunnsby** [syncthing/syncthing#8370]
Hi, I am still experiencing this issue running on the latest, 1.20.1 version.

### Setup

- Syncthing (v1.20.1, Linux (64-bit Intel/AMD) | "Fermium Flea" | Build 2022-05-18 (noupgrade)) in Docker Container (https://docs.linuxserver.io/images/docker-syncthing) running on Proxmox. The Syncthing Docker instance has a Volume mapped a local folder on Proxmox.

- The Proxmox local folder is mapped using CIFS `//qnap/docker /mnt/qnap_docker cifs iocharset=utf8,credentials=/root/.smbcredentials,_netdev,uid=1000 0 0` to a SMB share on a Truenas server, running on an old QNAP device.

- UID 1000 maps to a user which is configured on both the Trunas and Proxmox server and has access to all shares and datavols.

### Result

- All files written by Syncthing that require using the .syncthing.filename.tmp method still remain as "hidden files" when viewing them in Windows Explorer from a Windows 11 machine connected to the share. (They are represented in Windows with half-coloured icons) 

- Smaller files that can be written without requiring the .syncthing.filename.tmp method show up as normal "unhidden files", such as text files, etc. Any larger files, jpgs, movies, executables, zips, etc remain "hidden" even thought they are completely synced. Windows explorer properties shows them as having the hidden flag still set, even though they are fully synced. 

### Expected
As mentioned before, this is purely a Syncthing issue when writing to a shared volume, and is causing the DOS hidden attribute bit to be remain set once it is set on the file that uses the .syncthing.filename.tmp method, even when that file has completed. Copying large and small files directly from the docker container, not through Syncthing to the Volume mapped local folder  work fine and not bits are set.

### Things I have tried

- I have tried adding the `hide dot files = yes` enabled on the samba server, but it has made no difference.

_Originally posted by @nunnsby in https://github.com/syncthing/syncthing/issues/8142#issuecomment-1142408368_

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by calmh** [comment]
For the record this was troubleshot on the forum at some point, there's a combo of samba setting that causes this. Syncthing doesn't ever set or manipulate the hidden bit.
