### ISSUE TITLE
Out of sync problem

### ISSUE THREAD

**Issue by Gourav1910** [syncthing/syncthing#8379]
I have synced five folders from my laptop to mobile. Out of those three folders are synced and other two are showing out of sync problem. Why is it happening?

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
