### ISSUE TITLE
NTFS -> VFAT Sync Issue: Folder that contains final space in name is supported by NTFS but not in VFAT

### ISSUE THREAD

**Issue by jorgeprediger** [syncthing/syncthing#8381]
In the NTFS file system there are directory names with trailing spaces. If the file system of the destination device is VFAT, a synchronization retry is generated that cannot be satisfied because the creation of the directory fails because VFAT does not support spaces at the end of the name.

This is not a bug of syncthing but said problem does not allow the completion of the synchronization.

```
root@ubuntu-desktop:/mnt/43C7-BE45# export LANG=C
root@ubuntu-desktop:/mnt/43C7-BE45# lsblk -o +FSTYPE /dev/sdb
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS    FSTYPE
sdb      8:16   0   3.6T  0 disk                
|-sdb1   8:17   0 931.3G  0 part                ext4
`-sdb2   8:18   0 931.3G  0 part /mnt/43C7-BE45 vfat
root@ubuntu-desktop:/mnt/43C7-BE45# mkdir 'test '
mkdir: cannot create directory 'test ': Invalid argument
root@ubuntu-desktop:/mnt/43C7-BE45# 

```

**Comment by AudriusButkevicius** [comment]
As you said, it's not a bug of syncthing, this is expected not to work and the solution is to fix your filenames.

**Comment by jorgeprediger** [comment]
Please do not close it, in any case they should add a validation and inform the user of the problem, I can determine it because I am an advanced user but someone without technical knowledge could not determine the cause of the problem.

**Comment by AudriusButkevicius** [comment]
It's not feasible validation, as there are hundreds of different filesystems with different requirements/restrictions.
There are cases where you can't even identify what type of filesystem is in use, as the filesystems lie (things like overlay filesystems etc).

I don't think there is any point leaving this open as this can't be actioned/closed in anyway.

**Comment by jorgeprediger** [comment]
Inform the user that directory synchronization with trailing space is not fully supported and add a pattern to ignore them.

I close it because I understand what it is asking me, even so it is an unwanted situation.

**Comment by rasa** [comment]
FYI, https://github.com/syncthing/syncthing/pull/7876#Windows-reserved-filenames would address this issue.

But I don't think you can add a pattern to your `.stignore` file to ignore filenames ending with a space, as trailing spaces are not considered part of the pattern, unless escaped, and the escape character, the backslash, is repurposed to be a path separator on Windows. See [here](https://docs.syncthing.net/users/ignoring.html#patterns).

**Comment by tomasz1986** [comment]
You can actually can ignore them by adding `*{ }` to the ignore patterns :wink:.
