### ISSUE TITLE
Ignore patterns with wildcard and non-ASCII characters don't work as expected

### ISSUE THREAD

**Issue by wuqiling97** [syncthing/syncthing#8386]
Syncthing: v1.20.2
OS: Windows 10 21h2 build 19044.1706
Browser: Synctrayzor 1.1.29 or Chrome 102

## What happened

Use ignore patterns with wildcard and non-ASCII characters won't exclude target files sometimes.

For example, I want to ignore `2019春`, the following patterns will work correctly:

```
20[12][0-9]?
201??
```

But these won't

```
20[12]9春
201?春
2019[春夏秋]
```

## Steps to reproduce

Create a folder with a file named `2019春`, and `.stignore` with one of the above patterns that don't work. Adding this folder in syncthing GUI, and "Global state" shows "1 file, ...", indicating the file is not excluded

**Comment by calmh** [comment]
```
func TestIntlWildcards(t *testing.T) {
	pats := New(fs.NewFilesystem(fs.FilesystemTypeBasic, "."), WithCache(true))

	stignore := `1000春
200?春
300[0-9]春
400[0-9]?`
	if err := pats.Parse(bytes.NewBufferString(stignore), ".stignore"); err != nil {
		t.Fatal(err)
	}

	cases := []string{
		"1000春",
		"2002春",
		"3003春",
		"4004春",
	}

	for _, c := range cases {
		if !pats.Match(c).IsIgnored() {
			t.Errorf("%q should be ignored", c)
		}
	}
}
```


```
=== RUN   TestIntlWildcards
    /Users/jb/dev/syncthing/syncthing/lib/ignore/ignore_test.go:1096: "2002春" should be ignored
    /Users/jb/dev/syncthing/syncthing/lib/ignore/ignore_test.go:1096: "3003春" should be ignored
--- FAIL: TestIntlWildcards (0.00s)
```
