### ISSUE TITLE
Allow disabling UDP/UDPv6 multicast

### ISSUE THREAD

**Issue by PoneyClairDeLune** [syncthing/syncthing#8391]
## Feature
Allow disabling UDP/UDPv6 multicast.

## Reason
The service provider asked us to stop sending UDP/UDPv6 multicast traffic, claiming the traffic was problematic to several other customers, which I suspect is used by Syncthing for some features. Seeing that there aren't an existing option to disable the related features, we tried to drop UDP packets from and to the current multicast address on port 22000, but unsure of the exact functions affected by disabling multicast traffic sending.

This feature is also useful to other people running Syncthing on servers, which their providers somewhat are not pleased to see customers sending UDP multicast traffic to their network.

**Comment by calmh** [comment]
You can disable local discovery, or set the multicast address to an empty value in the config.

**Comment by PoneyClairDeLune** [comment]
> You can disable local discovery, or set the multicast address to an empty value in the config.

Thanks! Although there should be some more explaining upon this issue, or have some built-in presets for Syncthing instances running on servers instead of regular clients, like IPFS.

**Comment by PoneyClairDeLune** [comment]
> You can disable local discovery, or set the multicast address to an empty value in the config.

Disabling local discovery still gets multicast packet sent to the network. Will try to nullify the multicast address.
