### ISSUE TITLE
Revisiting the CPU limit

### ISSUE THREAD

**Issue by ell1e** [syncthing/syncthing#8392]
There have been various tickets about a CPU limit: #2123 #3212

These were all closed with as far as I can see answers alike to:

1. syncthing will be prioritized less if there is anything else going on,
2. use cpulimit to avoid heat,
3. inotify and other mechanisms generally reduce CPU load anyway,
4. doing the same work at half the CPU usage will need double the time hence use the same overall power anyway (which isn't even really a counter-argument fwiw, since it also means there is no harm in limiting cpu usage if there are other reasons)

These solutions however seem to fail when

1. the problem is the overall heat spikes on mobile devices which can cause faster overall(!) battery capacity degradation, uncomfortable use, and also shorten effective battery runtime in occasional cases (see point 4),
2. the problem also is that nobody likes to update and handhold syncthing manually but this exactly is required for cpulimit to work since an automatic, unattended syncthing update breaks out of an applied cpulimit watchdog,
3. the problem also is that on low power enough devices with large enough data amounts, you'll just hit a limit with inotify especially when it's a lot of files (kernel memory use) and no matter how efficient you get it's still a lot of work with a lot of power drain,
4. the problem also is that you're trying to have a low enough in the moment power drain to reach the next charging time and not to reduce overall power consumption of the job/work to be done in total, so maybe you'd actually want to drag out the overall work done such that it ends up taking longer than the time until you reach the charger.

Therefore, I think an integrated cpu limit option would be useful. I get that it might be too much effort to implement for the people who would have a use of it though. But it might be worth leaving a ticket open, since I think the attempts to argue I've seen that it's not actually useful/not solving anything just fall a little short.

*(Also, for what it's worth, syncthing for Android seems to have some options to combat this by stopping sync on mobile data or when not connected to a charger. For some reason, these don't seem to be available in the Linux version either, even though there are Linux phones on the market now.)*

**Comment by imsodin** [comment]
As you nicely described, both what the cpu limit does and how it's done depends a lot on the underlying system, both OS, service manager and hardware. Syncthing at it's core is meant to be cross-platform - having something close to feature parity and flexibility to accomodate all use-cases on all systems is basically impossible. Thus I believe managing resources should be the job of wrappers, service managers or OSes (like your example with syncthing-android, or what's possible with cgroups on unixes with systemd).

So I am closing this, as it's either a support request how to setup cpu limits on a certain system (please post to https://forum.syncthing.net) or a feature request for a wrapper, but out of scope for syncthing.

**Comment by ell1e** [comment]
There is no useful syncthing compatible way to set a cpu limit on Linux. (Due to it interferring with its updates.)

It is a little sad that this problem seems to be a little ignored. A wrapper would solve the problem, yes, but maybe it would make more sense to just integrate it? inotify etc are also aren't cross-platform, so I'm not sure I understand that argument.

**Comment by ell1e** [comment]
By the way, I effectively have auto updates disabled right now due to this on all devices. Surely this can't be the intended way for users to work around this?

**Comment by imsodin** [comment]
> By the way, I effectively have auto updates disabled right now due to this on all devices. Surely this can't be the intended way for users to work around this? If alone for security reasons.

Indeed it's not and that's not necessary. That's what I meant with the following:

> it's either a support request how to setup cpu limits on a certain system (please post to https://forum.syncthing.net/)

Please use the forum - https://forum.syncthing.net/. The forum has a lot more eyes and friendly people on it than the issue tracker. Thanks!

**Comment by ell1e** [comment]
I did, I got no useful responses.

>  that's not necessary. 

It absolutely is if you use `cpulimit`. What other solution exists?

**Comment by imsodin** [comment]
Issue locked. As written above, discussions happen on https://forum.syncthing.net
