### ISSUE TITLE
Folder names invisible in edit device window

### ISSUE THREAD

**Issue by kiwichrish** [syncthing/syncthing#8400]
Version 1.20.2 on Windows (Syntrazor) Docker (syncthing/syncthing and linuxserver/syncthing) and Linux PPA.

Chrome and Firefox on windows and Linux.

1.18.0-ds1 from the Ubuntu 22.04 repo does not exhibit the issue.

Per the screenshot below.

In the Edit Device / Share dialog from the Remote devices list the folder names of folders that are shared / linked to a given device are hidden.  Checking the rendered HTML it appears they're not there.. For a folder named Temp:

```
<div class="col-md-6 checkbox">
  <label for="sharedwith-Temp">
    <input id="sharedwith-Temp" ng-model="selected[id]" type="checkbox" class="ng-pristine ng-untouched ng-valid">
    <span tooltip="" data-original-title="Temp" ng-bind-html="label" class="ng-binding"></span>
  </label>
</div>
```

In version 1.18 the Text for the link is within the span element above.

![missingsharename](https://user-images.githubusercontent.com/7635913/174905862-d1bd801b-4dd9-4a2d-9087-bf6db9de8648.png)

**Comment by AudriusButkevicius** [comment]
https://github.com/syncthing/syncthing/pull/8388 already fixed.

**Comment by kiwichrish** [comment]
Thank, my search foo failed me clearly. :-)
