### ISSUE TITLE
Access behind a CGNAT.

### ISSUE THREAD

**Issue by caralu74** [syncthing/syncthing#8402]
Thanks for this great software!
I´m as a lot of people behind a CGNAT, thanks to syncthing I can reach and share my files, but I can not share or reach my own cloud, I mean something like Owncloud or Nextcloud, or reach a webcam or an IP cam or a baby cam. So Could you please give to Syncthing a feature that can serve for this purpose?

**Comment by AudriusButkevicius** [comment]
There are other solutions for connectivity. Zerotier, hamachi and potentially others.

Syncthing syncs files, thats it, it has no plans to be anything else than that.
