### ISSUE TITLE
files synchronized from other devices have turned into hidden files....

### ISSUE THREAD

**Issue by a1037674173** [syncthing/syncthing#8403]
In ubuntu20.04, files synchronized from other devices have turned into hidden files. These files were not hidden files before synchronization. The shared folder was placed in a folder mounted through SMB on the Ubuntu system. The SMB service was provided by truenas. When I mounted the shared folder from the windows system, I saw that almost all its files had turned into hidden files.

Before synchronization：
![Snipaste_2022-06-25_09-34-57](https://user-images.githubusercontent.com/49946559/175753333-1d0deef6-39c5-4492-8396-723524b35f30.png)

After synchronization：
![Snipaste_2022-06-25_09-32-53](https://user-images.githubusercontent.com/49946559/175753256-ced73a8d-a267-42c8-89bd-8a2bf5153b47.png)

**Comment by calmh** [comment]
This is a samba bug, sometimes when a file is created as a dotfile and then quickly renamed (as Syncthing does) it doesn't clear the hidden bit. Syncthing can't and doesn't set the hidden bit itself when running under unix, because unix doesn't have it.
