### ISSUE TITLE
Special characters for matching sibling directory contents in .stignore

### ISSUE THREAD

**Issue by Eviepayne** [syncthing/syncthing#8405]
## What problem your new feature would solve

I would love to ignore the big red override button but I use that as a marker to resolve an issue when it happens.
Ignoring a false positive is not a habit I want to keep.

Consider the scenario

device 1 has these contents
```
.DS_Store
foo
foofoo
bar/
    baz
    quux
    quuz
bar2/
    baz
    frobble
```
Device 2 has these contents
```
dir/
    file
fol/
    der
    file
    ver
bar/
    too
    quuy
```

Device 1 should send all files to device 2, but ignore all the existing files in device 2
I don't believe this is currently possible (without ignoring the override button)

---
In my particular situation.
I have folders on both devices that are the same name, different files, and one device has a filesystem I can't write to via syncthing (stupid android restrictions)

If I could do this:
`![I4ROKU](**)`
That would resolve my issue.

---
## how or why you think it is generally useful (i.e., not just for you)

Being able to regex match the sibling devices directory structure would allow us to make ignore rules based on it.
I agree this would be for more technical users, but for ex.<br>
matching a sibling's file would likely look something like:<br>
\[first 6 chars of device id\]\(matching syntax\)<br>
as an example:<br>
`![I4ROKU](**)`
or
`[I4ROKU](*.config)`

I also consider the possibility of matching the own devices' contents
```
![self](**)
**
```
I surmise a situation where I might use a program and share certain files amongst a few people, but say I want to selectively sync something from a specific device (a configuration as an example)
Or I could set the ignore rules for a number of devices to set up a "parent" device.

This could be used both for sending and receiving from specified devices

---
## what alternatives or workarounds you considered?

When I use ** and !dirname I get what I'm looking for, but this is not ideal, as if I add things outside the ! matches, I will get the big red override anyway.

As well this would allow me to decide between devices for certain files, as opposed to deciding to share/unshare certain devices entirely

**Comment by calmh** [comment]
Hi! This seems interesting but quite hard to reason about. You suggest patterns for ignoring files based on whether they are present on other devices, but whether they are present on other devices depends also on whether they were ignored, so it's a bit circular.

For example, in `[I4ROKU](*.config)`. I add a config file, they don't have it so it's not ignored. They sync it. Now they have it, so I start ignoring it, it becomes out of sync in the end.

I really don't think we want to do this. More generally,

> Device 1 should send all files to device 2, but ignore all the existing files in device 2

I don't think this is a good use case for Syncthing. I understand that you want to do it, but it may be better to use a unidirectional tool like rsync to just push files from A to B while ignoring existing contents at B.
