### ISSUE TITLE
Impossible to start syncthing on docker: panic: Failed to get user home dir

### ISSUE THREAD

**Issue by MichaelBitard** [syncthing/syncthing#8408]
### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using (1.20.2, docker)
 - what happened
 I get some strange errors 
```
$HOME is not defined
panic: Failed to get user home dir
goroutine 1 [running]:
```
even when the variable is set just before:
```
HOME=/data
export HOME

syncthing --no-browser --home=/data/
```
You can see it here: https://github.com/agileek/hassio-addons/blob/master/syncthing/run.sh

Issue on the homeassistant addon: https://github.com/agileek/hassio-addons/issues/38

**Comment by tomasz1986** [comment]
I had the same problem in the past when running Syncthing on Android from the command line, which also doesn't come with HOME set by default, but doing

```
HOME=/data syncthing
```

did work.

**Comment by calmh** [comment]
I don't know what you're doing in your Docker precisely, but we do `env HOME=something syncthing ...` when starting Syncthing our Docker image and that works. Anyway, Syncthing needs to be able to find the home directory, so this is something that needs to be sorted out on the launching side. ($HOME and --home are unfortunately two entirely different things, although historical naming obfuscates this...)

**Comment by MichaelBitard** [comment]
Thanks I'll try that. the --home is confusing indeed :)
