### ISSUE TITLE
Tray: Open Folder: Unable to select folder when shown on left side of tray

### ISSUE THREAD

**Issue by RobMahn** [syncthing/syncthing#8410]
OS: Windows 11
SyncTrayzor: v1.1.29
Syncthing: v1.20.2

1.  Right click on the SyncTrazor Icon.  (Note that the icon must be close to the right of the screen to cause the problem.)
2. Fly over "Open Folder"
3. If the folder name expands to far to the right, it will display on the left.  This is the problem scenario.
4. Attempting to move the mouse to select a folder closes the folder selections before you can make a choice.

If you arrange the location of the SyncTrazor Icon further to the left, the choices will open to the right and you can make a selection.

**Comment by tomasz1986** [comment]
SyncTrayzor has its own repository at https://github.com/canton7/SyncTrayzor, so you'd better report the issue there, as nothing can really be done about it here.
