### ISSUE TITLE
Allow other apps to register sync folders

### ISSUE THREAD

**Issue by quaintdev** [syncthing/syncthing#8423]
I am currently working on a TODO list application. I already have desktop client saving TODO to a file. Now I want these TODOs on my Android too but the problem is how do I sync?

I can go traditional way implement a backend but it comes with it's own overhead and pricing or I can manually setup Syncthing to sync my TODO files. This is of course tedious if my users are newbie and don't  know anything about Syncthing.

I was  thinking if Syncthing provided an API where apps could register their folders to be synced by requesting user permission it would become whole lot easier. Now I understand that TODO is a small application but I can see a whole new paradigm of app development using syncthing.

What do you guys think?

**Comment by AudriusButkevicius** [comment]
The app is in maintenance mode, so no work is going on, especially on adding large radical features.

Also, syncthing is an application, not an API, so I don't think we'd want to provide this anyway. Having to have another application installed just for your application to function sounds like bad design to me.

Furthermore, what does this even mean, where would syncthing sync this data to, what folders, devices, do we trust devices, how do they get approved etc, how do the folders get accepted on the other side.

"Add an api" sounds pretty easy, but devil is in the details.

**Comment by imsodin** [comment]
Or coming from a different angle: This looks more like a support request respectively use-case discussion than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker. And using Syncthing to sync app data is a common thing to do also on android, no new features needed.

Thanks!
