### ISSUE TITLE
Syncthing Android shows that the device is updated while it is still syncing

### ISSUE THREAD

**Issue by reportxx** [syncthing/syncthing#8429]
Syncthing Android shows that the device is updated while it is still syncing. See attached image
![syncthing screenshot](https://user-images.githubusercontent.com/84130654/178676423-d95d540e-5d2d-473c-bc1e-65dacabacc3d.jpeg)
.

**Comment by reportxx** [comment]
I think Syncthing Desktop has the same issue.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
