### ISSUE TITLE
View and Limit Connections

### ISSUE THREAD

**Issue by holgerlembke** [syncthing/syncthing#8431]
Moin..

I use syncthing in two different situation: inhouse and outhouse. While using it outhouse I would like to limit the syncing to specific folders depending where I am. I might be connected via corporate wifi or 4g/5g wireless, so free or payed services.

My simple idea would be a check box in front of the folder name to activate/deactivate the syncing for a specific folder. this would be fast and easy to understand.

It goes a little bit into the same direction as https://github.com/syncthing/syncthing/issues/8078 . It would be very nice to see a simple window that shows what connection are used.

**Comment by AudriusButkevicius** [comment]
Not sure what the ask here is.

There is a pause button for each folder.

Syncthing doesn't and in many cases can't know if you are connected to wifi, 5g or wifi that is delivered via 5g, etc.

**Comment by holgerlembke** [comment]
sorry, i totally missed the pause button.
