### ISSUE TITLE
Option to delete local files when removing folder from share

### ISSUE THREAD

**Issue by XXXBold** [syncthing/syncthing#8436]
Currently, if you attempt to remove a folder from the list (Edit->General->Remove) you get a confirmation popup before the action is performed. The text in the popup says that "No files will be deleted as a result of this operation."
![remove-folder-dialog](https://user-images.githubusercontent.com/30773753/179308926-4f0a9e65-2420-4cbe-bfcb-fea65b310a06.png)

But why not give the option here to delete the files locally aswell? I can imagine having the situation when you want to remove e.g. old shares which are no longer needed. I'd suggest adding a checkbox to said dialog (opt-in) to make this possible, example:
![remove-dialog-proposal](https://user-images.githubusercontent.com/30773753/179309153-51fc9165-0905-42c2-afcf-00beaae62335.png)

As it is now, I always have to SSH into the remote machine/browse to the path and remove the stuff manually for cleanup.
I think this will benefit other users too, and probably won't break anything.

Let me know what you think :)

**Comment by tomasz1986** [comment]
I think one caveat here would be whether the whole folder should be deleted or rather only files indexed by Syncthing (e.g. when there are ignored files, or local additions in case of Receive Only). Also, what about `.stversions`?

**Comment by XXXBold** [comment]
Hm, I didn't really consider that, I thought about just deleting the whole folder. Maybe the wording should be a little different like "Also delete folder <name> from local filesystem"?
Or probably a 2nd option to just delete indexed files? I think this is a little over engineered.

I think if someone actively ticks the checkbox they know what they want (That's why to keep it opt-in, so such things won't happen by accident when in a hurry etc.).

**Comment by calmh** [comment]
> I think this is a little over engineered.

This. Better to take the safe approach, not delete the files, and let the user delete them as they please. Having a checkbox to nuke everything is a significant additional risk for minor additional convenience and hence not worth it in my book.
