### ISSUE TITLE
Ram usage sudden spike  (from ~200MB to 1000+)

### ISSUE THREAD

**Issue by Kylejustknows** [syncthing/syncthing#8437]
- Does your log mention database corruption?
 - : No
 - Please be sure to include at least:
 - which version of Syncthing and what operating system you are using
 - : 1.19 and 1.20

RAM 512MB + SWAP 512MB NAS Device. ARM version. Only Syncthing running. The device was super stable (heavily used and monitored for years) before Syncthing.

The Issue:
Syncthing was perfectly fine using ~200MB ram during busy syncing, for many hours for many days.

Then it suddenly eats ALL THE RAM and SWAP in seconds (could be 1000MB+).

The outcomes:

Scenario 1,  RAM usage spikes to 90% and SWAP disk runs crazy, struggles for ~2 seconds, then out-of-memory crashes. (Nothing useful in the OOM panic report and the syslog records nothing)

Scenario 2,  The whole system freezes to death. The "last moment before death" SSH screen shows RAM usage 90% SWAP 100%. The syslog records nothing unusual. (guessing kernel frozen before panic)

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by bt90** [comment]
The response of @AudriusButkevicius does not mean that your report is unjustified. It's just that the forum is the better place to diagnose the cause of such problems. The tracker is more for well understood problems.
