### ISSUE TITLE
tight folder restart loop after introducer removes remote device

### ISSUE THREAD

**Issue by edrex** [syncthing/syncthing#8438]
After removing a device from a folder on an introducer node, I'm seeing this in a tight loop (~3 per second), with 25% cpu usage across all 4 cores, on an introducee node:

```
Jul 19 13:04:00 chip syncthing[1778]: [SXOQY] INFO: Ready to synchronize "wiki" (wiki) (sendreceive)
Jul 19 13:04:00 chip syncthing[1778]: [SXOQY] INFO: Restarted folder "wiki" (wiki) (sendreceive)
Jul 19 13:04:00 chip syncthing[1778]: [SXOQY] INFO: Completed initial scan of sendreceive folder "wiki" (wiki)
Jul 19 13:04:00 chip syncthing[1778]: [SXOQY] INFO: Sharing folder "wiki" (wiki) with NPF7VMR-HY3Q5TY-WTZ2LNH-QEEHGHC-E4BCDDG-SDPB3OD-VKDHCAK-TPEULAS (vouched for by introducer U4I4RN4-6F22QMN-AV6UNVX-QYRUZ4A-RTFHWIY-362SXKC-C4CZMGJ-53TVUAU)
Jul 19 13:04:00 chip syncthing[1778]: [SXOQY] INFO: Unsharing folder "wiki" (wiki) with SRATA3D-GZARZBA-KVL2XEI-BJLARZH-5RONDTH-GJ6AW3N-U7OYGCP-B6ZIMQS as introducer U4I4RN4-6F22QMN-AV6UNVX-QYRUZ4A-RTFHWIY-362SXKC-C4CZMGJ-53TVUAU no longer shares the folder with that device
```

- The node that's spinning: `syncthing v1.20.1 "Fermium Flea" (go1.17.10 linux-amd64)` (nixos unstable)
- The introducer: `syncthing-fork v1.18.1.0` (android 11)

**Comment by edrex** [comment]
- looping persists after restarting syncthing on introducee
- looping stops after restarting syncthing on introducer

If this is a known issue with `v1.18.1` this can be closed.

**Comment by AudriusButkevicius** [comment]
Seems like this needs 3 devices to happen? And is probably caused by having more than a single introducer, that creates a circular share unshare rolling loop?

Granted this is not ideal, but I am not sure if its easily solvable and is caused by the way you have it configured.

In practice you should only ever have one introducer.

**Comment by edrex** [comment]
I checked the introducers on each node and they are reciprocal introducers (with no other introducers). I can see how reciprocal introducers could cause oscillation. I'll remove one direction. It would be nice if the messaging was somehow more robust to these disagreements about state. Maybe syncthing should do leader election ala etcd etc, so there can be more robust distributed state. :shrug:

**Comment by bt90** [comment]
See #8393

**Comment by edrex** [comment]
Thanks @bt90!

Duplicate of #8383
