### ISSUE TITLE
Get scan progress through the REST API

### ISSUE THREAD

**Issue by hach-que** [syncthing/syncthing#8439]
I'd like to be able to retrieve this progress value through the REST API when a folder is being scanned:

![image](https://user-images.githubusercontent.com/504826/179901611-b472b1f9-fc9f-4f52-b60c-54f593113796.png)

Currently it doesn't seem possible - I've tried the completion endpoint, but this just returns `100` as the value. None of the other endpoints, including folder status, seem to provide the progress value.

**Comment by AudriusButkevicius** [comment]
The UI does it, so it's clearly possible.
I believe it does it via the events API.

Regardless, this sounds like a support matter, so best dealt with on the forums.
