### ISSUE TITLE
unrelated ipv6 slaac privacy addresses are announced to the discovery service

### ISSUE THREAD

**Issue by ryannathans** [syncthing/syncthing#8443]
The same issue is occurring with 2 hosts

Syncthing v1.20.3

Pop!_OS 22.04

Ipv6 (dhcpv6 & slaac w/stable and temporary privacy addresses) + Ipv4

I have configured syncthing to listen on the following: `tcp4://0.0.0.0:22000, quic4://0.0.0.0:22000, tcp6://[my:slaac:stable:privacy:address]:22000, quic6://[my:slaac:stable:privacy:address]:22000`

Yet when I look at https://discovery.syncthing.net/v2/?device=MY_DEVICE_ID I see my temporary slaac privacy address in the list.

I expect to see only addresses I have bound syncthing to, and my NAT ipv4 address. I do not expect unrelated ipv6 privacy addresses to be broadcast.

I assume the slaac temporary privacy address is added to the list because that is the address used to connect to the ipv6 discovery service? Is this intended? IPv6 does not have NAT, so I expect only bound addresses to be announced.

**Comment by calmh** [comment]
There is currently no filtering on addresses being bound or not, all interface addresses are announced.

**Comment by ryannathans** [comment]
> There is currently no filtering on addresses being bound or not, all interface addresses are announced.

I am not sure if that is true - my dhcpv6 address did not get announced until I changed my listening address to it

**Comment by bt90** [comment]
Syncthing discovers all unicast IPs on all interfaces which are currently up. This should currently publish all globally routable IPv6 adresses.

It seems to be currently not possible to detect temporary IPv6 addresses(RFC4941) with go:

https://github.com/golang/go/issues/42694

Publishing non-temporary addresses obtained via SLAAC/DHCPv6 is IMHO fine.

**Comment by bt90** [comment]
@calmh Just checked my Windows client and i can confirm that not all interface IPs are published.

Looks like we filter out any non-IPv4 address for interface based IP discovery:

https://github.com/syncthing/syncthing/blob/a2c5d901f240eb83f3873988b06e03e72b49cccd/lib/connections/util.go#L74-L81

Only my temporary IPv6 address is reported to the global discovery server. This is bad as router firewalls only allow to open ports for the main IPv6 of a device. Or to paraphrase it: this likely degrades global IPv6 connectifity for clients with enabled IPv6 privacy extensions

A quick check with an online port scanner service confirmed this. The port is open for the regular IPv6 address of my device but closed for the temporary one. Within my LAN i can connect to the port via both addresses, so we can rule out any Windows firewall involvement.

**Comment by calmh** [comment]
It was never intended to publish all IP addresses to global discovery. We specifically exclude globally routable ones for privacy purposes, announcing only RFC1918 IPv4.

**Comment by ryannathans** [comment]
> It was never intended to publish all IP addresses to global discovery. We specifically exclude globally routable ones for privacy purposes, announcing only RFC1918 IPv4.
> 
> The v6 address the discovery server sees is the one you come from (same as for v4).
> 
> Arguably the reason you _have_ a temporary ipv6 address is so that we shouldn't know about the SLAAC one...

services cannot be hosted reliably on temporary ipv6 addresses, the address will either cease to exist by the time someone tries to connect and/or it cannot be opened on router firewalls in advance, plus syncthing does not support upnp ipv6 pinholing

the base (privacy stable) slaac address is no longer derived from your mac address as of [RFC8981](https://www.rfc-editor.org/rfc/rfc8981) and is safe/ideal to host services on

> If you specifically configure the listen address to be a certain interface address we should bind to only that and announce that address (only).

yes please

**Comment by bt90** [comment]
> We specifically exclude globally routable ones for privacy purposes

I don't really get the privacy argument here. The idea behind the IPv6 privacy extensions is to prevent tracking on the web. Otherwise website owners could track a single device/user just by his IP.

To obtain that information from the discovery server you already need the device ID which is a fingerprint by definition.

As we're publishing the IPs for incomming connections, we should use the address which is intended for that.

**Comment by calmh** [comment]
Just to make clear the current situation and what the historical reason for it is:

- We have local discovery based on LAN broadcasts (IPv4) and multicasts (IPv6). These discovery packets are of course LAN-local, and include *all* interface addresses -- including SLAAC, temporary, ULA, and link-local IPv6 addresses.

- We have global discovery which is used to provide an "external" address to connect to. Here Syncthing announces:
  - the address it's specifically bound to, if any, but if it is bound to the unspecified address (as it almost always is) the discovery server uses the source address instead,
  - any detected NAT-traversal addresses (UPnP, STUN), and
  - any local RFC1918 addresses.

The last point was added fairly recently to aid in the case where two devices are on separate subnets on the inside of some NAT gateway. When we added that we specifically excluded globally routable addresses for privacy concerns:

- MAC based IPv6 SLAAC enable more tracking than we necessarily need, though as you say these are being phased out in different ways,
- internal non-RFC1918 addresses potentially reveal company-internal address schemes and addresses which they might reasonably expect to be non-public if they are behind an internal NAT gateway,
- other reasons we didn't think of at the time, but which might be problematic because we don't make it clear that we dig through the system for every IP address we find and publish them to a public service...

So, yeah. There might be a case to make exceptions for certain classes of IPv6 addresses, but also if you have stable non-privacy-problematic IPv6 addresses, by all means just use them for outgoing connections and things will work as expected today.

**Comment by bt90** [comment]
> - We have local discovery based on LAN broadcasts (IPv4) and multicasts (IPv6). These discovery packets are of course LAN-local, and include *all* interface addresses -- including SLAAC, temporary, ULA, and link-local IPv6 addresses (I think! At least, the source address can be expected to be reachable if we got the packet from it.).

So the code i posted is only used for publishing LAN IPs to the global discovery server?

> - MAC based IPv6 SLAAC enable more tracking than we necessarily need, though as you say these are being phased out in different ways,

I think it's a valid assumption that random identifiers are the default. That's at least the case for Windows, Android, Mac and most Linux distributions.

> - internal non-RFC1918 addresses potentially reveal company-internal address schemes and addresses which they might reasonably expect to be non-public if they are behind an internal NAT gateway,

Fair point.

> if you have stable non-privacy-problematic IPv6 addresses, by all means just use them for outgoing connections

I'd argue that most users don't have a fixed prefix and will get a new one from their ISP once in a while.

> If you're specifically using temporary addresses because you want to hide your other routable IPv6 address, then we're doing what you're asking for?

Temporary addresses are opt-out. There are two different mechanisms at play which might be changed by the user and are usually enabled on nearly all platforms by default:

* Random identifiers which generates non-EUI64 based IPv6 for the device. So roughly the same as temporary addresses but with a longer lifetime
* Temporary addresses for outgoing connections

Windows:

    netsh interface ipv6 set global randomizeidentifiers=disable
    netsh interface ipv6 set privacy state=disabled

Publishing the main IPv6 with random identifiers enabled doesn't leak the MAC and offers still enough privacy.

If the user disabled this mechanism, we can safely assume that he wants his device to be publicly addressable.

**Comment by ryannathans** [comment]
> So, yeah. There might be a case to make exceptions for certain classes of IPv6 addresses, but also if you have stable non-privacy-problematic IPv6 addresses, by all means just use them for outgoing connections and things will work as expected today. If you're specifically using temporary addresses because you want to hide your other routable IPv6 address, then we're doing what you're asking for?

In my case two ipv6 addresses are being published, the manually specified bound listening address and my temporary slaac address *which syncthing is not listening on*. I expected only the bound address to be published. I assume the temporary address is published because that's what was used to contact the global discovery server? I assumed this to be a bug, if it is not a bug, I assume we can close the issue.

**Comment by calmh** [comment]
@ryannathans 

> I assume the temporary address is published because that's what was used to contact the global discovery server?

Yes. Though, it shouldn't use that address unless Syncthing also announces a wildcard/unspecified address, which you according to the initial post don't have for IPv6. This may a bug as the IPv6 announce shouldn't care about configured IPv4 listen addresses and you have separated them into `tcp4`, `tcp6` etc.

@bt90 

> > if you have stable non-privacy-problematic IPv6 addresses, by all means just use them for outgoing connections
> I'd argue that most users don't have a fixed prefix and will get a new one from their ISP once in a while.

Certainly. I'm just saying that if the device has a SLAAC address and a temporary privacy address and uses the temporary privacy address, this is in effect a policy asking for "don't show the SLAAC address to the outside world", which is what happens.

**Comment by bt90** [comment]
To expose ports for IPv6 without a fixed prefix you only need to disable random identifiers to get an EUI-64 generated IP. This allows the router deduce the IP of the device even if the prefix changes and keeps firewall rules in place. Otherwise the router isn't able to guess the IP of the device and any connections will be blocked by the router firewall - special cases like UDP hole punching aside.

Temporary addresses are a different topic and don't need to be disabled for this to work.

**Comment by ryannathans** [comment]
> Edit: it looks like it's trying to do that -- it would be interesting to know precisely how the announcement looks to cause this, `STTRACE=discover` should show it...

I see `2022-07-28 19:17:36 discover: Registering addresses for <me>` and a lot of accepting addresses from local discovery but it doesn't seem to show outgoing announce contents in log

**Comment by calmh** [comment]
@bt90 You seem to be talking about firewall configuration rather than our discovery. I'm not sure how it applies to the subject?

@ryannathans You should see something like this:

```
[MRIW7] 2022/07/28 12:10:39.262510 global.go:259: DEBUG: global@https://discovery-v4.syncthing.net/v2/ Announcement: {[tcp://127.0.0.1:22002 tcp://0.0.0.0:0]}
[MRIW7] 2022/07/28 12:10:39.262627 global.go:259: DEBUG: global@https://discovery-v6.syncthing.net/v2/ Announcement: {[tcp://127.0.0.1:22002 tcp://0.0.0.0:0]}
```

**Comment by bt90** [comment]
Global discovery only makes sense for addresses which are potentially dialable from other clients. By publishing only temporary IPv6 addresses clients will always end up hitting the firewall of the router.

The router can only setup rules for addresses which are built using EUI-64 or assigned via DHCPv6. And we publish neither of these.

**Comment by calmh** [comment]
> Disabling temporary IPv6 addresses is not a workaround as it allows for user tracking by website operators.

This is indeed the crux of the issue, as we are essentially a website operator attempting to track you. I don't think just publishing all IP addresses we find is a good solution either, for much the same reason.

**Comment by bt90** [comment]
It's a bit different as this tracking is opt-in. By enabling global discovery i want syncthing to do exactly that.

Even the temporary IPv6 is enough to identify a single internet access as all devices still share the same provider assigned prefix. Same goes for the public IPv4 if CGNAT is not involved.

We could still provide an option to *disable* this behaviour and send interface IPs by default.

**Comment by calmh** [comment]
> We could still provide an option to disable this behaviour and send interface IPs by default.

We could; I think that's a separate feature request that could be filed at this point.

On another note, even the temporary addresses might actually work fine to dial, depending on how smart and/or aggressive the firewall is, as we attempt both TCP and UDP (quic) punch through. :)

**Comment by bt90** [comment]
Holepunching with QUIC should work in most cases depending on the NAT type. TCP  holepunching is blocked by any stateful firewall. I'd be amazed to find a modern router which uses a stateless firewall.

But yes we should move this to a different issue.

**Comment by bt90** [comment]
When did you change the listening address? Those might be leftovers from previous calls to the discovery server.

**Comment by calmh** [comment]
Yeah this is expected, as we always announce `0.0.0.0:0`.

**Comment by calmh** [comment]
I'm going to go ahead and hide all the chatter in the middle of this issue to make it clearer -- not because there's anything wrong with it, just because it clutters the issue so we won't understand the cause and effect when looking at it in the future.

**Comment by ryannathans** [comment]
> When did you change the listening address? Those might be leftovers from previous calls to the discovery server.

days ago, the temporary slaac address is still valid - they only last a couple hours and don't persist across system boots so it's current behavior

**Comment by ryannathans** [comment]
> Yeah this is expected, as we always announce `0.0.0.0:0` ([above](https://github.com/syncthing/syncthing/issues/8443#issuecomment-1197942601)).

the announce string i posted doesn't have tcp://0.0.0.0, it has tcp4://0.0.0.0, is it expected that this announces all ipv6 addresses?

**Comment by calmh** [comment]
Yeah. So that results in the source address being recorded by the server, and then addresses live for some time (which accounts for the outdated ones.)

**Comment by ryannathans** [comment]
why is tcp6://0.0.0.0 announced but not quic6://0.0.0.0?

**Comment by calmh** [comment]
Because the quic listener doesn't include the same logic... That's probably an oversight.

**Comment by ryannathans** [comment]
if the 0.0.0.0 are intentional and it's supposed to be publishing the temporary slaac addresses that have nothing listening on them i guess we can close this issue?

**Comment by calmh** [comment]
Yes. The other issues spun off for the other stuff remain. :)

**Comment by ryannathans** [comment]
thank you for your time :)
