### ISSUE TITLE
syncthing scans ignored files

### ISSUE THREAD

**Issue by Thomas-Walker-Lynch** [syncthing/syncthing#8452]
v1.20.3, Linux (64-bit Intel/AMD)

The first thing in .stignore for the folder is `.ssh`.  We do not want the software scanning private keys, as there is no benefit for the added exposure.

Syncthing scans it anyway.  Then it gets a permission error.  It puts this in a big orange box at the top, and under the rescans section of the folder it says that it "failed to setup".  It refuses to do a rescan when the rescan button is pushed.

It is well known that Syncthing scans ignored files.  There are many posts and 'explanations' for this on the forums, so there is really no need to establish here that this happens.

It is a bug.  It should not be scanning ignored things.  There are good reason for asking Syncthing not to scan something.  Examples include: Security issues as mentioned above.  We must take into account that it is a program that has network access, and its file access in the directory tree and network usage are essentially unauditable.  Another example is due to performance, we might ignore a very very large file, such as a database file or a video.  Yet another reason can be due to side effects.  Opening an ignored file changes the access date on the file and every hour or more at that!  It might trigger other actions.  As Yet another reason, directories to be ignored might be remote mounts and it could trigger side effects such as forcing the mount.   This is not an exhaustive list of problems associated with ignoring the ignored files list.  

When this bug is fixed, I hope you will consider having separate ignore files per folder id, and separate ignore files for send and receive.

(Thanks, great program.)

**Comment by AudriusButkevicius** [comment]
It's not a bug. It's explained why it's done that way, it has do to that to support ignore patterns such as:
```
!**.jpg
*
```

There is no way to support that without walking the whole tree.

If you want to discuss this further, start a thread on the forum.
