### ISSUE TITLE
Harmonize address listing logic between TCP and QUIC

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#8455]
The TCP listener invents a 0.0.0.0 address for hole punching purposes and does other funky stuff, while the QUIC listener (which has the same requirement) does not. Probably these should use some common functionality which acts the same for both.

https://github.com/syncthing/syncthing/blob/a2c5d901f240eb83f3873988b06e03e72b49cccd/lib/connections/tcp_listen.go#L159-L192

https://github.com/syncthing/syncthing/blob/a2c5d901f240eb83f3873988b06e03e72b49cccd/lib/connections/quic_listen.go#L179-L187

ref #8443

**Comment by AudriusButkevicius** [comment]
I think that is only meaningful for TCP as we use the same socket to talk to discovery server, so discovery server actually sees the port bound by the NAT device, so discovery server acts as a "stun" server. Given tcp mappings on the nat are long lived, this is good enough.

For quic, we actually use stun.

**Comment by calmh** [comment]
as-designed then
