### ISSUE TITLE
Indexes get corrupted due to abrupt termination

### ISSUE THREAD

**Issue by wsw70** [syncthing/syncthing#8465]
*Note 1: this was [initially posted in the forum](https://forum.syncthing.net/t/syncing-pull-no-such-file-this-time-on-a-syncthing-file/18764) but after several more attempts to fix it, I am promoting it to a bug report. I will synchronize the two places in case there is a breakthrough.*

*Note 2: I found a [2019 discussion](https://forum.syncthing.net/t/pull-no-such-file-error/13139/2) on that topic, in my case the issue is with a Syncthing file.*

Context:

* `6ZDAKC` is a Windows 10 with SyncTrazor (1.1.29, Syncthing is 1.20.3)
* `AE2FSX` is a docker container with the latest image (1.20.3)
* `U34L32` is a Samsung Galaxy S22 with the latest app installed

This is a rather new installation of Syncthing, I am trying to put together a sensible synchronizing approach. Until an hour ago there were no problems - they appeared when I came back home and opened mty laptop (it has been rebooted, disconnected etc. many times so far).

The log I get on `6ZDAKC` is

```
[6ZDAK] 2022/07/27 18:11:02 INFO: Puller (folder "Passeport et Carte d'Identite" (cjorv-mw3ig), item ".stwritetest"): syncing: pull: no such file
[6ZDAK] 2022/07/27 18:11:02 INFO: "Passeport et Carte d'Identite" (cjorv-mw3ig): Failed to sync 1 items
[6ZDAK] 2022/07/27 18:11:02 INFO: Folder "Passeport et Carte d'Identite" (cjorv-mw3ig) isn't making sync progress - retrying in 8m0s.
```

When looking at the directory, I see that there is a file

```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          2022-07-27    18:11              1 ~syncthing~.stwritetest.tmp
```

When removing the file, it is recreated during sync.

Neither on `AE2FSX` nor `U34L32` there is anything that looks like `*.stwritetest*`.

All the other files in the directory are synchronized correctly.

**Comment by AudriusButkevicius** [comment]
Sounds like something has gone wrong with the index transfers. Potentially the application got shut down half way through an index transfer or something, and doesn't know that the file is not there anymore.

Effectively, remove the folder on both sides and add it back again.

**Comment by calmh** [comment]
Is .stwritetest something the android app does?

**Comment by AudriusButkevicius** [comment]
I believe so, to test if the app has write perms.

**Comment by wsw70** [comment]
> Effectively, remove the folder on both sides and add it back again

Thank you, this helped (just removing it on Android was enough).

I think this is still a bug, an interrupted transfer is an expected event and should fail gracefully for a known case (index transfer)

**Comment by AudriusButkevicius** [comment]
Agreed, and we've had issues of this sort for a while. I assumed there was a bug for this already, but given I can't find one, I'll let this one live.

**Comment by calmh** [comment]
This is too vague to be actionable, though there is likely a bug *somewhere*. There's another issue that cover potential index transmission issues during initial setup, which may be relevant.
