### ISSUE TITLE
syncthing to Pixel, delete files on target without resync

### ISSUE THREAD

**Issue by tangyue1** [syncthing/syncthing#8471]
I setup pc as send only and pixel phone as receive only. When the PC folder is too big for pixel phone’s internal storage, the sync will stop and show insufficient space. I then upload the synced files to google photos and delete the synced files from phone. How do I resume the sync for remaining files to pixel phone, without resyncing the already deleted files?

**Comment by tomasz1986** [comment]
This is the exact same text as posted on the forum at https://forum.syncthing.net/t/delete-files-on-target-without-resync/18777, isn't it? As explained there, Synching actually won't resync the deleted files unless you press the "Revert Local Changes" button. If you've got more questions regarding this, please continue the discussion on the forum.

**Comment by tangyue1** [comment]
Thank you.
