### ISSUE TITLE
Connection dropped in loop with "lz4: invalid source or destination buffer too short" when sending files to Syncthing i386 with "All Data" compression enabled

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#8484]
The problem seems to only affect specific files. I'm attaching a sample file that does it below.

1. Connect two devices together. Make sure Device B runs the i386 (32-bit x86) release of Syncthing. Not sure if all platforms are affected, as I've only tested this under Windows.
2. On Device A, enable "All Data" compression for Device B. Disconnect and reconnect the two devices for the setting to trigger.
3. Share a new empty folder between the two devices.
4. On Device B, add `libsyncthing.so` (download and unpack from https://github.com/syncthing/syncthing/files/9259401/libsyncthing.zip) to the folder.
5. Device B fails to sync the file and drops the connection with
   ```
   [IDWWV] 2022/08/04 13:50:27.520397 model.go:1770: INFO: Connection to DHK2GDE at 192.168.56.1:50440-192.168.56.1:51355/tcp-server/TLS1.3-TLS_CHACHA20_POLY1305_SHA256 closed: decompressing message: lz4: invalid source or destination buffer too short
   ```
7. From now on, the two devices keep trying to reconnect, but the connection keeps dropping immediately with the same error.

The only way to work around the the problem seems to be not using "All Data" compression.

Logs with `db,model,connections` enabled.

- [DeviceA.log](https://github.com/syncthing/syncthing/files/9259465/DeviceA.log)
- [DeviceB.log](https://github.com/syncthing/syncthing/files/9259466/DeviceB.log)

**Comment by calmh** [comment]
LZ4 package bug: https://github.com/pierrec/lz4/pull/191

**Comment by tomasz1986** [comment]
There's been no response on the LZ4 package repository (and no changes to the package itself since June). What do you think about simply downgrading the package to v4.1.13, which seems to work fine on i386 systems (at least when it comes to Windows)?

This can be done by just reverting https://github.com/syncthing/syncthing/commit/2e135d0c6540a911fa9f8912897151e716a567a1. I did that one month ago and I've been using v4.1.13 on my Windows x86 machine since then with no further issues, without any other changes to the configuration, etc.

**Comment by calmh** [comment]
Yeah. One "worry" is that we don't have a process for keeping dependencies locked at a lower version; dependabot will complain, `build.sh update-deps` will upgrade it, etc...

**Comment by greatroar** [comment]
Reverting the commit causes a regression. I've sent a better fix to lz4.
