### ISSUE TITLE
Sync hiccup & downloads deleted files back to the side that deleted it!

### ISSUE THREAD

**Issue by DeMoN100** [syncthing/syncthing#8494]
**_Does your log mention database corruption?_**
No

_Syncthing v1.20.4 Win7 SP1 & Syncthing Android version 1.20.3 Samsung A535G
Brave Browser 1.40.113_

I deleted a file in my syncthing folder on my pc when this happened it kept saying my pc was disconnected on my android and my pc kept saying the phone was disconnected. I restarted on both sides multiple times and the folders would not sync up-to-date. I even removed them then re-added them & still nothing was happening. I attempted this multiple times then even killed the process on my desktop then restarted it & still nothing was happening. An hour later all of a sudden it just worked it said the devices were connected & it just synced the folders automatically. I have it on watch for change so this shouldn't have happened unless I am mistaken.

My second issue once it started working was I deleted a bunch of files on my desktop side and the sync worked correctly on my phone deleting these files. Then afterwards I deleted one video and my phone instead synced to the desktop and made my desktop redownload the video I had deleted on my desktop.

**_What you expected to happen instead?_**
1. When I delete a file in the syncthing folder it should not hiccup and say devices are disconnected on both sides then take multiple restarts, deleting the folders & re-adding them to fix the issue.

2. When it does work I expect if I delete a file on one side it should delete it on the other. Not work one time then the next re-download the files I deleted on the desktop side from the phone.

**_Any steps to reproduce the problem?_**
1. My syncthing folder is located in my documents folder
2. I have 5 folders inside the syncthing folder
3. In Folder Number 5 I deleted a .zip and a .rar file (This is when the devices got disconnected and would not sync)
4. I removed the folders, deleted the .srt then re-added them
5. I restarted syncthing on pc and android
6. After nothing happened I repeated steps 4 & 5!
7. After nothing happened again I removed the devices from each other then re-added them
8. After nothing happened I repeated steps 4 & 5 again!
9. After an hour of waiting all of a sudden everything reconnected (please note folders were always set to watch for change this option was never unchecked)

_Deletion Replication_
1. I deleted a bunch of images & audio files in folder Number 5 in my syncthing folder on my pc (worked perfectly fine with deleting them on my phone)
2. I deleted one .avi video in folder Number 5 in my syncthing folder on my pc (my android phone did not delete the file & my desktop re-downloaded the video I had just deleted out of it)

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
