### ISSUE TITLE
Syncthing is spamming the browser console

### ISSUE THREAD

**Issue by kitswas** [syncthing/syncthing#8501]
### Does your log mention database corruption?

No.

### Required information

 - Environment: Syncthing "v1.20.4", Windows 10
 - Browser: Firefox 103.0.2 (64-bit). Also observed on Chrome
 - Actual behaviour: `refreshDiscoveryCache`, `refreshConnections`, `refreshErrors` and `refreshSystem` are being logged to the console over and over again.
 - Expected behaviour: The browser console should be as clean as possible.
 - Steps to reproduce: Turn on Syncthing, open the Web GUI and look at the console in the developer tools.

**Comment by AudriusButkevicius** [comment]
Why?

Seems like this is a "your opinion" vs "someone elses opinion". What is the console for if not logging?

I personally like to know that things are happening.

**Comment by acolomb** [comment]
In principle these log messages are fine IMHO. Just one thing I noticed with Firefox, one message especially seems to be "broadcast" somehow. I sometimes see a recurring message about "retrying in 500 ms" on whatever site that allows executing JavaScript examples and printing the result. It seems connected to having a tab with the Syncthing GUI open. Not any of the other mentioned messages though, so not quite sure this is the same issue as reported. May be an argument for tuning down on messages in general though if it cannot be avoided specifically.

**Comment by kitswas** [comment]
> Why?
> 
> Seems like this is a "your opinion" vs "someone elses opinion". What is the console for if not logging?

The console is for logging errors and warnings + executing javascript commands and seeing their output. 
The output of any command executed quickly gets lost in the deluge.
The way it currently is makes it look like someone forgot to comment out the `console.log()` statements they used for debugging. I'd like to know if this happened unintentionally or by design.

> I personally like to know that things are happening.

Me too. But that should be on request, not forced.

**Comment by AudriusButkevicius** [comment]
I think we prefer it as it is.
