### ISSUE TITLE
Typo in Russian translation

### ISSUE THREAD

**Issue by 3JlOy-PYCCKUi** [syncthing/syncthing#8505]
I found a typo in the Russian translation, I didn't understand how to properly format a pull request, so I'll just provide the patch
https://github.com/3JlOy-PYCCKUi/syncthing/commit/93764df7471b76d7b287cdcd95bc67cadc57bed4.patch

**Comment by tomasz1986** [comment]
Translations are handled by Transifex. You will need to go to https://transifex.com/syncthing, apply to become a translator for the Russian language, and then add the fixes there.
