### ISSUE TITLE
macOS Monterey 12.5.1 aliases break after sync

### ISSUE THREAD

**Issue by kcrmson** [syncthing/syncthing#8506]
### Does your log mention database corruption?

None found in the logs on either machines.

If your Syncthing log reports panics because of database corruption it is
most likely a fault with your system's storage or memory. Affected log
entries will contain lines starting with `panic: leveldb`. You will need to
delete the index database to clear this, by running `syncthing
-reset-database`.

### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using

macOS 1.20.4

 - browser and version, if applicable

Safari 15.6.1

 - what happened,

Aliases on the Desktop shared folder sync across but the file type breaks and appears as a generic document. Consequently this will be defaulted to open with TextEdit and is unusable.

 - what you expected to happen instead, and

The aliases sync properly and fully retaining their original file path.

 - any steps to reproduce the problem.

Unshared the folder, reshared, ignored the .DS_Store file, tried without ignoring the .DS_Store file, made sure Syncthing and the OS are up to date on each computer (each running macOS 12.5.1), all other normal files sync without issue, tried soft symbolic links but those did not work, tried originating the aliases on either machine, same issue occurs. Made sure the absolute path is identical on all machines (same short username).

**Comment by calmh** [comment]
It turns out that an alias is only an alias when there's a Finder extended attribute on it marking it as an alias. We currently don't sync extended attributes, so the alias breaks. This will be fixed by #8513
