### ISSUE TITLE
Dramatically decrease Scanning time on windows by using "NTFS USN Journal"

### ISSUE THREAD

**Issue by yehia2amer** [syncthing/syncthing#8507]
### Include required information

Syncthing is now taking a vast amount of time to Scan files in a windows machine (depending on the data and machine power).
Using something like [Everything SDK](https://www.voidtools.com/support/everything/sdk/c/)  could dramatically reduce this time in the initial scan or  when monitoring file system changes.

**Comment by AudriusButkevicius** [comment]
We use inotify to detect filesystem changes and only scan what has changed.

**Comment by yehia2amer** [comment]
This issue is about windows, inotify is linux only API !

**Comment by rasa** [comment]
> This issue is about windows, inotify is linux only API !

@yehia2amer I think @AudriusButkevicius is using inotify in the generic sense. Syncthing uses the https://github.com/syncthing/notify library, which has a Windows implementation in https://github.com/syncthing/notify/blob/main/watcher_readdcw.go

**Comment by yehia2amer** [comment]
Thanks a lot @rasa for your detailed reply. I think this covers the second aspect in my question regarding monitoring the file changes.

What about the first aspect which is dramatically reduce the time in initial scan ?
