### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by Natalia-Oreiro** [syncthing/syncthing#8512]
Hello,

I can't find information if there is a version/possibility of having syncthing on a USB flash drive in a portable version?

**Comment by tomasz1986** [comment]
This isn't documented separately, but if you check https://docs.syncthing.net/users/syncthing.html, then you will be able to see that Syncthing can indeed be run in a fully portable fashion. Also, please try searching the https://forum.syncthing.net for "portable" and you should be able to find quite a few helpful topics dealing with this question.
