### ISSUE TITLE
how to delete the Current file from the index folder? Can anyone expain it in steps?

### ISSUE THREAD

**Issue by amarjt** [syncthing/syncthing#8516]
Worked!

Thank you

On 10/06/2015 6:08 PM, Audrius Butkevicius wrote:

> Just delete the CURRENT file from the index folder in syncthings home 
> folder (check -help).
> This can be caused by a sudden power outage/reboot corrupting the 
> database.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/syncthing/syncthing/issues/1926#issuecomment-110679779.

_Originally posted by @bittorrenter in https://github.com/syncthing/syncthing/issues/1926#issuecomment-110695612_

**Comment by tomasz1986** [comment]
You literally need to go to the database folder and delete the file in there. Syncthing of course needs to be shut down before doing so. If you need more help with this, please open a new topic at https://forum.syncthing.net.
