### ISSUE TITLE
have to keep adding the same node and allowed share again and again after updates?

### ISSUE THREAD

**Issue by cottrell** [syncthing/syncthing#8520]
I assume this is something to do with updates and persisting the hashes? Does anyone know if this is expected or represents a bug?

Basically every once in a while (order weeks) I check a laptop and the old versions of my desktop node have disconnected and gone stale and there is a new request to join and share. And I have to delete the old stale, unused remote devices.

**Comment by tomasz1986** [comment]
Something sounds wrong, but it's unclear with the short description above. Please open a new topic at https://forum.syncthing.net if you'd like to investigate this further. Make sure to include as much details as possible to help others better understand the issue.

**Comment by cottrell** [comment]
> Something sounds wrong, but it's unclear with the short description above. Please open a new topic at https://forum.syncthing.net if you'd like to investigate this further. Make sure to include as much details as possible to help others better understand the issue.

Thanks unfortunately I have little detail other than "it happens over timescales of weeks ... which means any number of updates could trigger it".
