### ISSUE TITLE
Files with identical names except letter case (upper/lower) can't coexist

### ISSUE THREAD

**Issue by ghollisjr** [syncthing/syncthing#8521]
### Does your log mention database corruption?
There are no logs of the error due to no errors being raised.  The sync process hangs forever.

## Device information:

Syncthing: 1.20.4
Client 1 OS: Linux 5.18.16-arch1-1
Client 2 OS: Android 11

## Problem description
After setting up a share folder and configuring both client devices to keep the shared folder synchronized: If a file e.g. "Test.txt" exists in the shared folder and is already synchronized, and then one of the clients creates a file "test.txt" (identical except letter case) in the shared folder, the sync process will hang at X% progress (exact value depends on folder size).  If the file is renamed to something that is distinct when letter case is ignored, e.g. "test.txt" -> "test2.txt", then the sync process will succeed with "Test.txt" and "test2.txt" existing in the shared folder.

Steps to reproduce:
1. Setup folders to sync between two devices.
2. Create a file "test.txt" in the folder on the first device.
3. Create another file "Test.txt" in the folder on the first device.

Expected behavior: Two files "test.txt" and "Test.txt" should exist in the shared folder on both devices.
Observed behavior: The "Test.txt" file never exists on the second device, only "test.txt" exists on both and "Test.txt" is stuck never fully transferring to the second device.

**Comment by tomasz1986** [comment]
Android normally uses FAT filesystem for user files, which is case insensitive, so you this isn't going to work in this specific case. You'd need two Linux systems on both sides with case sensitive filesystems for case different files to be able to coexist like that.

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
