### ISSUE TITLE
ignore local changes for "Receive Only" folders

### ISSUE THREAD

**Issue by tdbe** [syncthing/syncthing#8527]
We absolutely NEED autonomous shadow copy folders. So I don't understand the (from a user perspective) seemingly fable-grade stubborn will to not include this feature deep under the advanced settings, I mean you DO have a "Revert local changes" button - just automate that.. ..But I won't bang against that brick wall. 

Instead, I want you to please provide a windows solution to this linux-only script workaround mentioned in the other closed issue [here](https://github.com/syncthing/syncthing/issues/6338).

What does this script mean and how do you script auto revert/ignore local changes in windows? Pls don't handwave this. It's a roadblocking pressure point. Thank you.

```
#!/bin/sh
host=https://localhost:8384
apikey=yourAPIkeyHere
folder=someFolderID

if ! curl -skH "X-API-Key: $apikey" "$host/rest/db/status?folder=$folder" \
  | grep -q 'receiveOnlyChanged.*": [1-9]' ; then
  exit 0
fi

curl -X POST -skH "X-API-Key: $apikey" "$host/rest/db/revert?folder=$folder"
```

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by tdbe** [comment]
yes I half agree, the only problem is that is 1000% removed from the eyes of the devs - the ones actually meant to understand the users' bubbling tensions

**Comment by tomasz1986** [comment]
This has been stated multiple times in many places already, but the main point here is that Syncthing isn't going to implement solutions that can potentially lead to automatic destruction of user files.

If you need a Windows-compatible script that would revert local additions in a more automated fashion, please open a new topic on the forum and I should probably be able to help you with this.

**Comment by imsodin** [comment]
Locking this issue. The forum is very much frequented by devs, and this is not the place to discuss why and how of limitations/workarounds.

**Comment by rasa** [comment]
Moved to the forum [here](https://forum.syncthing.net/t/the-need-will-never-die-ignore-local-changes-for-receive-only-folders/18955/1).
