### ISSUE TITLE
Nested shares

### ISSUE THREAD

**Issue by luturnai** [syncthing/syncthing#8535]
This feature suggestion describes multiple shares, nested in subfolders of a root folder which is a main share. The improvements this would bring is a reduction of complexity in steps taken and thus potential to make mistakes when manually setting up shares nested in an existing main share. It enables any device with a main share to participate in sharing data with devices that only have nested shares without having to manually set up nested shares in each device with a main share added to your network following the setup of the first one.

Ideas that have similarities were described in issues such as #940, #1167, #2456, which have been closed due to inactivity and duplicates. As they were generally relatively imprecise, I wrote up this enhancement proposal to enable a constructive discussion.

Here is an example of how main and nested shares could work from a user perspective:

DEVICE_1:
```
# FOLDERS		# SHARES	# SHARED WITH
ROOT_FOLDER_1 		SHARE_1		DEVICE_2
- SUB_FOLDER_2		SHARE_2		(DEVICE_2), DEVICE_3
- SUB_FOLDER_3
  - SUB_FOLDER_4	SHARE_3		(DEVICE_2), DEVICE_3
- SUB_FOLDER_5

```
SHARE_1 is a main share which include folders that are shared through it as well as the nested shares SHARE_2 and SHARE_3.
Main SHARE_1 is shared with DEVICE_2, and nested SHARE_2 and SHARE_3 with DEVICE_3.
DEVICE_2 automatically syncs SHARE_2 and SHARE_3 with DEVICE_3, as it has SHARE_1 in its entirety and thus knows about the nested shares (SHARE_2 and SHARE_3) within it.
DEVICE_3 has no knowledge of folders on other devices outside of SHARE_2 and SHARE_3, so it does not participate in syncing SHARE_1 or any of its contents other than SHARE_2 and SHARE_3. Those other contents are only shared between DEVICE_1 and DEVICE_2 which both have SHARE_1.

DEVICE_2:
```
# FOLDERS		# SHARES	# SHARED WITH
ROOT_FOLDER_1		SHARE_1		DEVICE_1
- SUB_FOLDER_2		SHARE_2		(DEVICE_1), DEVICE_3
- SUB_FOLDER_3
  - SUB_FOLDER_4	SHARE_3		(DEVICE_1), DEVICE_3
- SUB_FOLDER_5
```

DEVICE_3:
```
# FOLDERS		# SHARES	# SHARED WITH
ROOT_FOLDER_1		SHARE_2		DEVICE_1, DEVICE_2
ROOT_FOLDER_2		SHARE_3		DEVICE_1, DEVICE_2
```

When DEVICE_3 is offered SHARE_2 and SHARE_3, which originate from the same main share (SHARE_1), DEVICE_3 should be prevented from placing SHARE_3 in a folder of SHARE_2 (or SHARE_2 in SHARE_3), to avoid looping folder structures.

**Comment by AudriusButkevicius** [comment]
Why do you think this would bring reduction of conflicts? I think what is proposed would result in exactly the same behaviour as existing nesting of folders.


It's probably going to be less effort to write a new application like syncthing rather than implementing it in syncthing. 

The protocol does not allow this, the security model does not allow this. I don't even want to try and reason what this means for more advanced features.

**Comment by luturnai** [comment]
@AudriusButkevicius 
Good point about missing reasoning on why conflicts would be reduced - I will edit to remove that part.

Your question had me going back to the roots of what motivated the suggestion, and something I failed to mention is the difficulty and high probability of making mistakes that comes with manually setting up nested shares across multiple devices. I regularly have to deal with that in my setups and the pain from that is definitely part of my motivation here. I will add that as a clarification.

I can't really speak to whether this suggestion is technically feasible or not, as I am a user in this context and decidedly not a developer of anything as complex as syncthing. From my position the best I can do is tell you what kind of enhancement would be helpful to the problems I am trying to solve when I use syncthing. Thank you.

**Comment by AudriusButkevicius** [comment]
Maybe I'm missing something, but I don't see how what you proposed is different to what is already possible? (Albeit via having multiple folders for different parts of the tree)

**Comment by luturnai** [comment]
It is a perfectly valid stance to expect users to structure their folders in a certain way before sharing by use of syncthing.
However, I think there would be greater value for users if syncthing provided better support for nesting shares. Value in the form of stronger accommodation for the folder structures and share locations a user has decided on.

**Comment by AudriusButkevicius** [comment]
I still don't understand what this means in practice?

What are you trying to do that you currently cannot do?

**Comment by danielbaak** [comment]
The OP's usecase seems to match one of mine.

I have a large folder with date based (or any other kind of) subfolders on a pc named machine0:

```
.
└── 2022
    ├── 01
    │   ├── 01
    │   └── 02
    ├── 02
    │   ├── 01
    │   └── 02
    └── 03
        ├── 01
        └── 02
```

```mermaid
flowchart TD
m0["Machine0 : 2022"]
m0 -- "shares with" --> m1["Machine1 : 2022"]
m0 -- "shares with" --> m2["Machine2 : 2022/03"]
m0 -- "shares with" --> m3["Machine3 : 2022/03/02"]
```

* Machine1 has sufficient storage, so all of `2022` is shared with it,
* Machine2 has a moderate amount of storage and chooses to sync `2022/03`,
* Machine3 is very tight for storage and can only afford to sync the newest subfolder `2022/03/02`.

Essentially, the machine invited to receive a shared folder should be allowed granular control over which subdirectories of the shared folder it wants to or can sync.

**Comment by imsodin** [comment]
All these proposals talk about folders within a single root (well nested folders). That seems like the perfect use-case for a single folder with ignore patterns.

And generally this entire issue reads more like a (well written) support request for a specific use-case than a clear feature request. It's unclear what exactly the feature resp. app behaviour would be here.  
Please use the forum - https://forum.syncthing.net/ - to explore these use cases further. It has a lot more eyes and friendly people on it than the issue tracker. And if during the discussion a clear actionable improvement emerges, a ticket can be opened describing that - thanks!
