### ISSUE TITLE
introduction of generics breaks builds with Go < 1.18

### ISSUE THREAD

**Issue by decathorpe** [syncthing/syncthing#8541]
syncthing v1.21.0 started using generics in Go code, which is a feature limited to Go 1.18+.
It appears that the only place they are used was added in this PR:
https://github.com/syncthing/syncthing/pull/8496

Would it be possible to adapt these two lines of code to not use generics?
Limiting Syncthing to Go 1.18+ means that I'll no longer be able to support v1.21.0+ on Fedora 35 and RHEL 8 or RHEL 9, which all have golang < 1.18.

**Comment by calmh** [comment]
Our policy for at least the last five years or so has been that we target (and require) the current-minus-one version of Go. So now that Go 1.19 is current we target Go 1.18 which has generics. I don't think we plan to change this policy.

**Comment by decathorpe** [comment]
Ok, that's a shame then. I didn't know about the other uses of generics, since the build errored out with the first one. Thanks for the clarification. Looks like updates for syncthing 1.21+ for RHEL / Alma / Rocky Linux 8 and 9 will need to wait until golang is updated to 1.18+ there.

**Comment by ehdis** [comment]
> Ok, that's a shame then. I didn't know about the other uses of generics, since the build errored out with the first one. Thanks for the clarification. Looks like updates for syncthing 1.21+ for RHEL / Alma / Rocky Linux 8 and 9 will need to wait until golang is updated to 1.18+ there.

AFAIK the next minor release of EL will be in ~2 months ...
