### ISSUE TITLE
Means to reset/delete a single share from database

### ISSUE THREAD

**Issue by theodiem** [syncthing/syncthing#8554]
I would like to have the option to "reset" the database for a single share. Similar to `--reset-database` but for a single folder.

Usercase is: I have a small machine that acts as backup server, having a syncthing instance that syncs multiple folders with multiple computers (over 400Gb of data). If I would like to make 'advanced' changes to a single share (for example its location, or updated the ignores and would like to "refresh it" by deleting all its contents and re-syncying), I'm forced to use --reset-database, which takes really long time due the other folders.

Also deleting the share and re-adding it doesn't seems to work as It seems if I do it in a short period of time, the information on the database isn't excluded in the meanwhile, so if I delete de share, remove the folder, re-share the folder with the machine (so its ID is the same), it complains that folder doesn't exists instead of begining fresh.

So an option which says to the db "forget everything about this share (share ID)" and re-create the folder as if I just added a folder would really be helpful.

**Comment by acolomb** [comment]
You can do that selectively for only one folder through the API:
https://docs.syncthing.net/rest/system-reset-post.html

> Also deleting the share and re-adding it doesn't seems to work as It seems if I do it in a short period of time, the information on the database isn't excluded in the meanwhile, so if I delete de share, remove the folder, re-share the folder with the machine (so its ID is the same), it complains that folder doesn't exists instead of begining fresh.

That sounds strange. I think we need more clarification what happens exactly and where things supposedly go wrong. Please head over to the [forum](https://forum.syncthing.net/) if you want to troubleshoot this further.
