### ISSUE TITLE
Periodic connection losses to webui because docker image doesn't support upgrade

### ISSUE THREAD

**Issue by DonRichie** [syncthing/syncthing#8569]
### Environment
I am using the official syncthing/syncthing docker image in the latest version (v1.21.0).

### Problem
Every now and then the webui displays for a short moment <1s that the connection to the server is lost.

The reason is known. It is because the webui fails to call:
https://mybaseurl/rest/system/upgrade

This endpoint responds http status code 500 and the following text:
`upgrade unsupported`
(which is normal for the docker image)

The webui doesn't seem to understand the response and interprets it as server failure.

### Proposed changes
- Change the responded http status code to "501 Not Implemented"
- Accept code 501 as valid response for the call to the upgrade-check endpoint so that the webui doesn't display connection errors.

**Comment by calmh** [comment]
Interesting, I can see how this could happen, but I've never actually seen it in real life and I talk to Dockerized Syncthings all the time. I guess it may be timing related, as the upgrade check is done on startup (of the GUI) and a lot of other requests happen at the same time.

Nonetheless I agree that returning not-implemented is better and could be specially handled in the GUI!
