### ISSUE TITLE
Incorrect rescan interval on auto accepted encrypted folder

### ISSUE THREAD

**Issue by Ratio2** [syncthing/syncthing#8572]
Version: main

Rescan interval always change to 1 day, but gui only change 1 minute and 1 hour values to 1 day.

**Comment by acolomb** [comment]
I believe this works as designed? When accepting in the GUI, the same default rescan interval of 86400 seconds is preset, which you can change before saving though. 

Doing the same for auto-accepts was added recently in #8427. Since the user has no chance to adjust it, we simply use the default value. Note that rescanning is usually not necessary for receive-encrypted folders, as the locally encrypted files can not be edited reasonably.

**Comment by Ratio2** [comment]
@acolomb No, 86400 interval not changed in gui if we set 61 or 3601 in default folder configuration

**Comment by acolomb** [comment]
Right, the GUI code assumes that the interval should only change automatically with the other settings (watcher enabled / folder type) when it's value is still among the three possible defaults. Duplicating this logic in the backend for the auto-accept case is error-prone, as we can see there is already a slight difference in behavior.

This functionality predates the possibility to set defaults for the folder config, so I guess we really need to define what the desired behavior is. If someone deliberately sets the default interval to one day for example, it will be changed back to a minute or an hour depending on the folder type / watcher setting. That is unexpected and not transparent. Maybe we can come up with an approach to fix that as well, then mirror it to auto-accept?

**Comment by Ratio2** [comment]
I have taken your comments and made the necessary changes. These changes are minimal and do not require deepening the discussion. Now the scan interval cannot be less than the one set by the user. As a result, we have the following cases (the functionality has been tested):
1. Scan interval 0 - we use 0, since there is no point in scanning an encrypted folder if we do not scan a regular folder
2. Scan interval is less than 3600 - use 3600 to keep the current behavior
3. Scanning interval is greater than 3600 - we use the user setting, since it makes no sense to use a value less for an encrypted folder than for a regular folder

Note: pull-request auto checks failed because the problem is in the server, not in the code
