### ISSUE TITLE
Decrypt versions folder

### ISSUE THREAD

**Issue by Ratio2** [syncthing/syncthing#8575]

**Comment by AudriusButkevicius** [comment]
What does this even mean?

**Comment by Ratio2** [comment]
@AudriusButkevicius syncthing decrypt skip .stvertsions folder

**Comment by tomasz1986** [comment]
Somewhat a duplicate of https://github.com/syncthing/syncthing/issues/7914? This one is more generic though, but the same problem of not decrypting `.stversions` was discussed in the other issue as well.

**Comment by imsodin** [comment]
Yes, duplicate of https://github.com/syncthing/syncthing/issues/7914
