### ISSUE TITLE
Versioning the received encrypted folder

### ISSUE THREAD

**Issue by Ratio2** [syncthing/syncthing#8577]
I want to build a file storage system that provides data loss protection. To do this, I use encrypted folders to store data on devices not under my control.

In the current implementation, versioning is disabled both in the GUI (you can easily forget to enable versioning by hand), and when adding a folder automatically.

Without versioning the encrypted folder, it is not possible to build a data storage system that avoids data loss, since data is irretrievably lost when deleted on any device.

As a solution, we can add an option to the configuration file:
encryptedFolderVersioningDisabled=true

**Comment by calmh** [comment]
Versioning of receive-encrypted folders is supported and can be enabled. (Restoring is a bit of a pain though.)
