### ISSUE TITLE
WARNING: Error updating metadata for %q at database commit: %v - After Update to v1.22.0 (Windows and Linux)

### ISSUE THREAD

**Issue by Backi67** [syncthing/syncthing#8583]
Hi, 
Since Update to V1.22.0 I have the "updating metadata" error when Syncing a File.

History from log:
[WI6RE] 2022/10/04 11:12:29 INFO: Automatic upgrade (current "v1.21.0" < latest "v1.22.0")
..
[WI6RE] 2022/10/04 11:12:31 WARNING: Automatically upgraded to version "v1.22.0". Restarting in 1 minute.
[WI6RE] 2022/10/04 11:13:31 INFO: QUIC listener ([::]:22000) shutting down
..
[WI6RE] 2022/10/04 11:13:34 INFO: Exiting
[start] 2022/10/04 11:13:35 INFO: syncthing v1.22.0 "Fermium Flea" (go1.19.1 windows-amd64) teamcity@build.syncthing.net 2022-10-02 06:58:22 UTC
[start] 2022/10/04 11:13:35 INFO: Archiving a copy of old config file format at: C:\Users\xxxxx\AppData\Local\Syncthing\config.xml.v36
[start] 2022/10/04 11:13:35 INFO: Using large-database tuning
..
[WI6RE] 2022/10/04 11:13:37 INFO: Hashing performance is 439.99 MB/s
[WI6RE] 2022/10/04 11:13:37 INFO: Detected upgrade from v1.21.0 to v1.22.0
[WI6RE] 2022/10/04 11:13:37 INFO: Overall send rate is unlimited, receive rate is unlimited
..
[WI6RE] 2022/10/04 11:13:37 INFO: QUIC listener ([::]:22000) starting
[WI6RE] 2022/10/04 11:13:37 INFO: TCP listener ([::]:22000) starting
..
[WI6RE] 2022/10/04 11:15:43 WARNING: Error updating metadata for %q at database commit: %v 

Do I have to change something.. or is it a Bug?

Yours
Stephan

**Comment by imsodin** [comment]
It's definitely a logging error, that looks like a `Warnln` where it should be a `Warnf`: https://github.com/syncthing/syncthing/pull/8584

As to what is happening - hard to say as there actual error isn't printed. What failes is an `LStat` on a finished file in the puller. I don't really understand how that owuld happen, given the puller just created that file. Unless something else happened at the same time.

What system are you on?

**Comment by Backi67** [comment]
Hi,
It is not syncing anymore... The file mention in the line, is not written to the destination directory.

I have different machinetypes:
Windows: 10 (Running inside Synctraycor)
v1.22.0, Windows (64-bit Intel/AMD)
Synology NAS:
v1.22.0, Linux (64-bit Intel/AMD)
(My Android Clients all Running V1.21.0)

**Comment by Backi67** [comment]
[WI6RE] 2022/10/05 18:45:02 WARNING: Error updating metadata for %q at database commit: %v Radio\_Sync\2419\Regionaljournal-Zentralschweiz_05-10-2022-1730.1664985707556.mp3 CreateFile \\?\C:\CloudStation\RSSMobile\Radio\_Sync\2419\Regionaljournal-Zentralschweiz_05-10-2022-1730.1664985707556.mp3: Das System kann die angegebene Datei nicht finden.
[WI6RE] 2022/10/05 18:45:02 WARNING: Error updating metadata for %q at database commit: %v Radio\_Sync\2419\Regionaljournal-Zuerich-Schaffhausen_05-10-2022-1730.1664985848086.mp3 CreateFile \\?\C:\CloudStation\RSSMobile\Radio\_Sync\2419\Regionaljournal-Zuerich-Schaffhausen_05-10-2022-1730.1664985848086.mp3: Das System kann die angegebene Datei nicht finden.
[WI6RE] 2022/10/05 18:45:10 WARNING: Error updating metadata for %q at database commit: %v _Sync\1817\Regionaljournal-Zuerich-Schaffhausen_05-10-2022-1730.1664985848086.mp3 CreateFile \\?\C:\CloudStation\RSSMobile\Radio\_Sync\1817\Regionaljournal-Zuerich-Schaffhausen_05-10-2022-1730.1664985848086.mp3: Das System kann die angegebene Datei nicht finden.
[WI6RE] 2022/10/05 18:45:13 WARNING: Error updating metadata for %q at database commit: %v _Sync\2419\Regionaljournal-Zentralschweiz_05-10-2022-1730.1664985707556.mp3 CreateFile \\?\C:\CloudStation\RSSMobile\Radio\_Sync\2419\Regionaljournal-Zentralschweiz_05-10-2022-1730.1664985707556.mp3: Das System kann die angegebene Datei nicht finden.
[WI6RE] 2022/10/05 18:45:13 WARNING: Error updating metadata for %q at database commit: %v _Sync\2419\Regionaljournal-Zuerich-Schaffhausen_05-10-2022-1730.1664985848086.mp3 CreateFile \\?\C:\CloudStation\RSSMobile\Radio\_Sync\2419\Regionaljournal-Zuerich-Schaffhausen_05-10-2022-1730.1664985848086.mp3: Das System kann die angegebene Datei nicht finden.
[WI6RE] 2022/10/05 18:45:16 INFO: Puller (folder "Share-RSSMobile3" (RSSMobile3), item "Radio\\_Sync\\2419\\Regionaljournal-Zuerich-Schaffhausen_05-10-2022-1730.1664985848086.mp3"): syncing: delete file: file modified but not rescanned; will try again later

**Comment by calmh** [comment]
> syncing: delete file: file modified but not rescanned

I guess it tries to do the lookup for a deleted file. That's not great, and will of course fail...

**Comment by Backi67** [comment]
No that could not be:
WI6RE] 2022/10/05 19:17:06 WARNING: Error updating metadata for %q at database commit: %v Radio\09_Auto\36_Persoen__2022-09-18_Persoenlich_18-09-2022-1003.1663492383952.mp3 CreateFile \\?\C:\CloudStation\RSSMobile\Radio\09_Auto\36_Persoen__2022-09-18_Persoenlich_18-09-2022-1003.1663492383952.mp3: Das System kann die angegebene Datei nicht finden.

![image](https://user-images.githubusercontent.com/115099101/194121978-4c21b7ac-6a40-4057-9a75-caa12460d508.png)
The FIle is there :-)

**Comment by calmh** [comment]
Yeah, it shouldn't run for deleted files anyway. Can you enable `STTRACE=model` (available in the log screen in the GUI too) and see what it does prior to this error?

**Comment by imsodin** [comment]
Looking up that error gives a truck load of totally unrelated possible causes, with the possible extension of anti virus. So if you have that, could you check if disabling helps.

On a secondary note:  
I am not sure if warning on any lstat error is a good way of notifying users. Can become very noisy when e.g. something global failed and causes an entire batch to error. Maybe the ctime update should happen when we finish an item instead, and an error handled like any other pull error.

**Comment by calmh** [comment]
This is when we finish an item though, or I misunderstand you.

**Comment by Backi67** [comment]
I hope, this is what you asked for:

[WI6RE] 2022/10/05 21:16:17.394448 model.go:925: DEBUG: model@0xc000152ea0 Completion(KIR4WSN, "RSSMobile3"): map[completion:70.75188078450381 globalBytes:175133670728 globalItems:2224 needBytes:51223304801 needDeletes:173 needItems:224 remoteState:unknown sequence:5451]
[WI6RE] 2022/10/05 21:16:17.394448 model.go:925: DEBUG: model@0xc000152ea0 Completion(LLSRBK3, "RSSMobile3"): map[completion:100 globalBytes:175133670728 globalItems:2224 needBytes:0 needDeletes:0 needItems:0 remoteState:valid sequence:58974]
[WI6RE] 2022/10/05 21:16:17.394448 model.go:925: DEBUG: model@0xc000152ea0 Completion(XKWI2XJ, "RSSMobile3"): map[completion:100 globalBytes:175133670728 globalItems:2224 needBytes:0 needDeletes:0 needItems:0 remoteState:valid sequence:58251]
[WI6RE] 2022/10/05 21:16:17.394448 model.go:925: DEBUG: model@0xc000152ea0 Completion(ZGQCBS2, "RSSMobile3"): map[completion:100 globalBytes:175133670728 globalItems:2224 needBytes:0 needDeletes:0 needItems:0 remoteState:valid sequence:64571]
[WI6RE] 2022/10/05 21:16:23.959995 model.go:1126: DEBUG: Index update (in): XKWI2XJ / "RSSMobile3": 4 files
[WI6RE] 2022/10/05 21:16:23.961294 model.go:1126: DEBUG: Index update (in): ZGQCBS2 / "RSSMobile3": 4 files
[WI6RE] 2022/10/05 21:16:23.961294 folder_sendrecv.go:161: DEBUG: sendreceive/RSSMobile3@0xc0042cb400 pulling
[WI6RE] 2022/10/05 21:16:23.961812 folder_sendrecv.go:255: DEBUG: sendreceive/RSSMobile3@0xc0042cb400 copiers: 2 pullerPendingKiB: 32768
[WI6RE] 2022/10/05 21:16:23.961849 folder_sendrecv.go:1209: DEBUG: sendreceive/RSSMobile3@0xc0042cb400 taking shortcut on Radio\09_Auto\36_Persoen__2022-09-18_Persoenlich_18-09-2022-1003.1663492383952.mp3
[WI6RE] 2022/10/05 21:16:23.962958 folder_sendrecv.go:1209: DEBUG: sendreceive/RSSMobile3@0xc0042cb400 taking shortcut on Radio\9999_Sync\2022_10_05-DESKTOP-19_15.txt
[WI6RE] 2022/10/05 21:16:23.963473 folder_sendrecv.go:1795: WARNING: Error updating metadata for %q at database commit: %v Radio\9999_Sync\2022_10_05-DESKTOP-19_15.txt CreateFile \\?\C:\CloudStation\RSSMobile\Radio\9999_Sync\2022_10_05-DESKTOP-19_15.txt: Das System kann die angegebene Datei nicht finden.
[WI6RE] 2022/10/05 21:16:23.963473 folder_sendrecv.go:1209: DEBUG: sendreceive/RSSMobile3@0xc0042cb400 taking shortcut on Radio\_Sync\0218\Echo-der-Zeit_05-10-2022-1800.1664988694633.mp3
[WI6RE] 2022/10/05 21:16:23.964033 folder_sendrecv.go:1795: WARNING: Error updating metadata for %q at database commit: %v Radio\_Sync\0218\Echo-der-Zeit_05-10-2022-1800.1664988694633.mp3 CreateFile \\?\C:\CloudStation\RSSMobile\Radio\_Sync\0218\Echo-der-Zeit_05-10-2022-1800.1664988694633.mp3: Das System kann die angegebene Datei nicht finden.
[WI6RE] 2022/10/05 21:16:23.964033 folder_sendrecv.go:1209: DEBUG: sendreceive/RSSMobile3@0xc0042cb400 taking shortcut on TV\ZZ_Sync\2022_10_05-DESKTOP-20_15.txt
[WI6RE] 2022/10/05 21:16:23.964587 folder_sendrecv.go:1795: WARNING: Error updating metadata for %q at database commit: %v TV\ZZ_Sync\2022_10_05-DESKTOP-20_15.txt CreateFile \\?\C:\CloudStation\RSSMobile\TV\ZZ_Sync\2022_10_05-DESKTOP-20_15.txt: Das System kann die angegebene Datei nicht finden.
[WI6RE] 2022/10/05 21:16:23.973240 folder_sendrecv.go:194: DEBUG: sendreceive/RSSMobile3@0xc0042cb400 changed 4 on try 1
[WI6RE] 2022/10/05 21:16:23.973240 folder_sendrecv.go:255: DEBUG: sendreceive/RSSMobile3@0xc0042cb400 copiers: 2 pullerPendingKiB: 32768
[WI6RE] 2022/10/05 21:16:23.974365 folder_sendrecv.go:194: DEBUG: sendreceive/RSSMobile3@0xc0042cb400 changed 0 on try 2

**Comment by calmh** [comment]
@imsodin Well, putting the job on the dbUpdateChan is the last thing that happens in performFinish, and then the metadata update happens in the db updater before the update is batched, so I think it's functionally equivalent. There's not much of a delay from one step to the other. I think not everything goes through performFinish (shortcuts etc) hence the current placement.

@Backi67 yes, though it doesn't make it much clearer unfortunately. We have

```
[WI6RE] 2022/10/05 21:16:23.962958 folder_sendrecv.go:1209: DEBUG: sendreceive/RSSMobile3@0xc0042cb400 taking shortcut on Radio\9999_Sync\2022_10_05-DESKTOP-19_15.txt
[WI6RE] 2022/10/05 21:16:23.963473 folder_sendrecv.go:1795: WARNING: Error updating metadata for %q at database commit: %v Radio\9999_Sync\2022_10_05-DESKTOP-19_15.txt CreateFile \?\C:\CloudStation\RSSMobile\Radio\9999_Sync\2022_10_05-DESKTOP-19_15.txt: Das System kann die angegebene Datei nicht finden.
```

where we first "take a shortcut" (just adjust some permissions or time on an existing file on disk without altering content) and then one millisecond later it apparently doesn't exist. I can't explain it.

**Comment by calmh** [comment]
> I have this error also on Linux

Can we get some logs from there?

**Comment by tomasz1986** [comment]
Is this the same error here just from today?

```
2022-10-10 13:15:01: Error updating metadata for %q at database commit: %v xxx\locks\1_1_ace88ca3468c4ea39c8f455988117a7a.json CreateFile \\?\C:\xxx\locks\1_1_ace88ca3468c4ea39c8f455988117a7a.json: The system cannot find the file specified.
```

The file doesn't exist anymore. I can only add that these `json` files in the `locks` directory belong to Joplin (a note-taking application) and seem to be created temporarily only while Joplin is synchronising its state with the filesystem, and then they are deleted automatically.

Is there anything that I could provide to help with this? Unfortunately, I've got only the normal log from that time. Also, I'd never seen this error message before.

**Comment by calmh** [comment]
@tomasz1986 happening once because the file actually doesn't exist because Joplin deleted the file while we were syncing or scanning it is fine. Happening all the time while the file actually does exist on disk is not fine.

**Comment by chapmanjacobd** [comment]
I also get this error on Android for a few files. I don't see an error in the UI on Linux but I assume the same problem is causing Linux to Linux syncing to never complete (stuck at 97% the past couple days)

I don't use Windows anywhere

```
2022-12-05 09:39:31: Error updating metadata for 80_Now_Listening/81_New_Music/unsorted/Selected. at database commit: file does not exist
```

```
v1.22.2-preview.1, android (64-bit ARM)
"Fermium Flea" Build 2022-11-08 (noupgrade, stguiassets, stnoupgrade)

syncthing cli show version
{
  "arch": "amd64",                                     "codename": "Fermium Flea",
  "date": "2022-10-13T19:00:00-05:00",
  "isBeta": false,
  "isCandidate": false,                                "isRelease": true,
  "longVersion": "syncthing v1.22.0 \"Fermium Flea\" (go1.18.7 linux-amd64) mockbuild@fedora-koji 2022-10-14 00:00:00 UTC",                                      "os": "linux",
  "stamp": "1665705600",
  "tags": [],
  "user": "mockbuild",
  "version": "v1.22.0"
}

The other linux is openSuSe with v1.22.1
```

**Comment by calmh** [comment]
This looks not actionable any more to me. The error is improved, various metadata syncing things have been improved.

**Comment by tomasz1986** [comment]
I'm sorry for commenting on a closed issue, I seem to still encounter the error/notification from time to time. If this isn't a problem per se, is it really necessary to even notify the user about it?
