### ISSUE TITLE
File called ".syncthing.xxx" or "~syncthing~xxx" is ignored and not synced

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing#8595]
If you name a file `.syncthing` and then add any extension to it, e.g. `.syncthing.abc`, then it will be ignored and not synced. This isn't intended, is it? I assume that the problem is somehow related to https://docs.syncthing.net/users/syncing.html#temporary-files, which are ignored by default, but it doesn't make much sense, as those follow more complex patterns, i.e. `.syncthing.original-filename.ext.tmp` or `~syncthing~original-filename.ext.tmp`, and here there is no `.tmp` extension.

Is this an edge case? For the record, I wasn't looking for bugs specifically 😵. I had just created a PowerShell script called `.syncthing.ps1` for personal use, and then I realised that the file wasn't detected and synced by Syncthing. I then did some testing and found out the exact filename scheme that was the problem.

**Comment by calmh** [comment]
I would say this is absolutely intended, yes. `.syncthing.*` and `~syncthing~*` are our temp patterns.

**Comment by tomasz1986** [comment]
Is there any reason not to use `.syncthing.*.tmp` and `~syncthing~*.tmp` for the temp patterns though?

**Comment by calmh** [comment]
Nothing concrete that comes to mind, it's just not what we happen to do. If I were pressed to invent a reason on the spot I would claim that it's good that we've reserved the whole namespace up front so that we can use it for other purposes in the future, avoiding the issue where some unlucky user might have called a script `.sycnthing.ps1` and learnt to expect that this would work.

**Comment by tomasz1986** [comment]
What to do with this then :wink:?

The first option is to leave as is (although it would be nice if this was written clearly in the Docs), the second option is to limit the application to `*.tmp` files only. I'm not a fan of such a wide scope of potentially ignored files personally, but I can see the logic behind it. The situation was still very unexpected for me though, as I was basically sure that the temp pattern did include the `.tmp` extension, especially considering what is written in the Docs right now about the whole temp filename scheme.

**Comment by calmh** [comment]
Please feel free to update the docs. I see no reason to change the behavior here. `.syncthing.` is our namespace, you can have your script in `.tomasz86.ps1`.
