### ISSUE TITLE
MacOS + Android + Obsidian: Sync conflict on all file modification

### ISSUE THREAD

**Issue by Belphemur** [syncthing/syncthing#8604]
I'm encountering something similar to OP in #4305 where Android keep creating conflict for files modified from MacOS with Obsidian.

# Behavior
* Use Obisidian to manage note on MacOS (use markdown files)
* Obsidian modify a file
* MacOS Syncthing detect change file and sync it
* Android Syncthing get the changes but trigger a conflict
* MacOS Syncthing sync back the *.sync-conflict file 
* the sync-conflict contains the previous version of the file
* Android hasn't been used to modify the file
* I also have a linux machine with syncthing, no issue there, never create conflict, happy with the updated file.

# Unsuccessful workaround
* Disabled Watch for change on android
	* Sync conflict created on syncing from MacOS
* Pause the sync on android
	* Sync conflict created when unpaused

# System Info

## Android
Syncthing: v1.22.0-rc2
Hardware: Pixel 4a 5G
OS:  Android 13 (No custom rom, default from Google).
Configuration: Watch for changes, Ignore Permissions

## MacOS
Syncthing: v1.22.0-1
OS: MacOS 12.6
Hardware: Apple M1 Max 64Gb
Configuration: Watch for changes, Ignore Permissions

## Linux
Syncthing: v1.22.0-1
OS: Debian 11
Hardware: armhf

**Comment by tomasz1986** [comment]
This sounds like the problem I've experienced in https://forum.syncthing.net/t/keep-getting-conflicts-generated-on-android-device-for-files-modified-only-on-a-desktop-pc/19060, which is specific to v1.22.0 and unrelated to the old issue. This is currently being worked on by @calmh in https://github.com/syncthing/syncthing/pull/8603.

**Comment by steven52880** [comment]
I encountered the same problem when synchronizing on Windows and Linux with the ntfs hard disk attached.
There is a same text file on Windows and Linux, and I modify the text file on Windows, but SyncThing said file conflicts.

**Comment by uok** [comment]
I can confirm that since last version there are more out of sync situations because of “local additions” on receive only folders
(1 from Windows to Linux - ignore permissions is set, never had problem before; 1 from Android to Linux)

**Comment by rcsaquino** [comment]
I manage to fix this by ticking "Ignore Permissions" on the folder settings on all my devices using the folder. I don't know if it's intended, but it's working for now at least.

**Comment by Belphemur** [comment]
@calmh I'm still encountering the bug when I do this:
* Linux machine use a CIFS mount to store the synced folder
* MacOS make a change
* Linux machine trigger a conflict even when the file is synced, even when the Linux machine didn't touch it.

Currently, the MacOS is still running v1.22.0 but the Linux machine is running v1.22.1.
Also, all devices have the "Ignore Permissions".

**Comment by hamdav** [comment]
I had no issue when both of my devices, (one mac one raspberry pi), was on 1.22.0, but when my mac was upgraded to 1.22.1 while the pi was still on 1.22.0 I got conflicts on any edit from the mac. After upgrading both to 1.22.1 it seems to be solved though.

**Comment by aashish108** [comment]
So, to resolve this issue, all connected clients need to have the 1.22.1 version of synching? I guess I will have to wait then!

**Comment by tomasz1986** [comment]
> So, to resolve this issue, all connected clients need to have the 1.22.1 version of synching? I guess I will have to wait then!

There are still problems when it comes to Android (see the linked forum topics at https://github.com/syncthing/syncthing/issues/8636#issuecomment-1305494504). I'd suggest to upgrade to v1.22.1 everywhere but on Android actually downgrade to v1.21.0 (for the time being).

**Comment by fbanning** [comment]
I have both my Linux as well as my Android installations on v1.22.1 and still experience a lot of sync conflicts whenever I change any file. Will try to downgrade to v1.21.0, thanks for the tip, @tomasz1986.

**Comment by aashish108** [comment]
Using Syncthing is a bit of a nightmare now with Obsidian! Hoping it gets resolved quickly. Might look at alternatives, another hassle.

**Comment by fbanning** [comment]
Nah, Syncthing is awesome. Been using it for years without any issues at all. They'll get this sorted out in no time, I'm sure. :)

**Comment by aashish108** [comment]
> Nah, Syncthing is awesome. Been using it for years without any issues at all. They'll get this sorted out in no time, I'm sure. :)

No doubt, it is awesome! It was just an effort to figure out why everything was going upside down and its prob gonna be a month or so until all devices are on the same page etc.

**Comment by tomasz1986** [comment]
Just a little tip, if you don't feel like downgrading the Android app (which can be a little complex), you can also go to the Advanced Configuration in the Web GUI and set `Max Conflicts` to `0` for each folder. This should block Syncthing on Android from creating those conflicted copies.

If you need more help, I'd suggest to open a topic on the forum (or use one of the already existing ones) for a more detailed and extended discussion.

**Comment by cocoonkid** [comment]
Jut wanted to add that I am using the excellent to make working with the rare conflict more bearable.



I also started to close obsidian on one machine when starting to use the other so that makes it even better.

https://github.com/friebetill/obsidian-file-diff
