### ISSUE TITLE
Do not slow down syncing when using "newest first"

### ISSUE THREAD

**Issue by xeruf** [syncthing/syncthing#8605]
### Include required information

which version of Syncthing and what operating system you are using: v1.20.1 on android

When putting a big share (a few hundred GB) with many files on "newest first", syncing slows down considerably as it first tries to sort everything. But with the option I am only expressing a preference - until it has sorted everything, it should just sync in random order and then sync the rest in order. If it slows down syncing, the option is rather useless to me...

**Comment by calmh** [comment]
I can't imagine sorting being a significant factor here, really. We do approximately as much work in the default case because the list is explicitly shuffled. I think you're seeing something else, whatever it may be.

**Comment by xeruf** [comment]
you shuffle the list explicitly? I thought "random" means "unsorted" in this case, so there is no way to avoid sorting?

**Comment by calmh** [comment]
"Alphabetic" avoids sorting:

https://github.com/syncthing/syncthing/blob/ed588ce335877b31f864581bd130d9fa528fd36e/lib/model/folder_sendrecv.go#L431-L446

However, I can pretty much guarantee this step takes negligible time.

**Comment by imsodin** [comment]
If it's also a lot of items it is likely the age old problem of queue having to store all entries to be synced, which is heavy on low memory devices (most phones): https://github.com/syncthing/syncthing/issues/4976

For further debugging of your @xeruf's issue please open a topic on the forum. The forum has a lot more eyes and friendly people on it than the issue tracker, which we use for actionable issues/feature requests.
