### ISSUE TITLE
syncting sync ownership simply don't work (for newly added foledrs)

### ISSUE THREAD

**Issue by 5x3** [syncthing/syncthing#8608]
both PC with Fedora Linux, selinux disabled, set cap's as described, both PC have linux user owns data, dir added on 1st pc, and synced to 2nd, both PCs have syncthing runned under UID EUID GID EDIG = 0, 1ist pc file owner user named 'user' with UID 1011 , 2nd pc file have the same file owner by user 'root' and UID 0. so simply don't work.

**Comment by calmh** [comment]
If the files originate from a non-Linux system and you're then changing the ownership on Linux you may be suffering from a bug which is solved in 1.22.1-rc.1. If there are no non-Linux boxes involved it certainly does work and I'd suggest you hop on over to the forum and post with full configs and screenshots of the UI and we'll help sort it out there.

**Comment by 5x3** [comment]
non-linux system not related to this problem.
I found a bug! description following, please fix ASAP!:
PC1 - source PC - send only (no matter actually what mode selected).
PC2 - destination PC - recieve only (no matter actually what mode selected).
1. ON THE PC1  I SHARE directory with the PC2 (check PC2 in Share tab of the folder),
2. ON PC2 i Accept incoming folder.
3. syncthing start to syncronize WHOLE directory FIRST TIME - BINGO-2: and the owner IS 'root' UUID = 0 - which is WRONG! 
4. ON THE PC1 I add new file named 'testfile1.txt' to shared folder.
5. ON THE PC2 I see file 'testfile1.txt' appears with user named 'user' and UUID = 1011 - BINGO-2: works as expected.

The conclusion is obvious, there is NO CODE to keep UID\GID\\Ownership for folders that just added.
You JUST FORGET ABOUT IT, ADD CODE ASAP!
