### ISSUE TITLE
$FOLDER_PASSWORD is not read; consider adding a password prompt for folder decryption

### ISSUE THREAD

**Issue by lwbt** [syncthing/syncthing#8617]
I'm trying to sync a folder to an untrusted device and decrypt it. The help text [implies](https://github.com/syncthing/syncthing/blob/main/cmd/syncthing/decrypt/decrypt.go#L31) that I could use `$FOLDER_PASSWORD`, but that does not seem to work.

Sort of a feature request: other programs and maintainers (e.g. ecryptfs) warned users that passwords should not be submitted as parameters and instead be entered when the command is called through the respective password prompt. Syncthing does not seem to have a facility to ask for a password when the parameter or environment variable is missing and just fails. Could this be implemented? Yes I have read and understood that this feature is in beta state.

### Does your log mention database corruption?

No.

### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using: https://github.com/syncthing/syncthing/releases/download/v1.22.0/syncthing-linux-amd64-v1.22.0.tar.gz (Arch Linux/SteamOS)
 - browser and version, if applicable: not applicable since it's about CLI
 - what happened: it could not decrypt the folder
 - what you expected to happen instead: decrypt the folder
 - any steps to reproduce the problem:
   - setup a folder (`test`), and some sample files, protect it with a password (`test`) and sync it to another machine where it will arrive as encrypted
   - On the target machine run `read -rsp "Enter password: " FOLDER_PASSWORD; syncthing decrypt $folder`; the folder will not be decrypted and fail with authentication failed
   - On the target machine run `read -rsp "Enter password: " FOLDER_PASSWORD; syncthing decrypt --password=$FOLDER_PASSWORD $folder`; the folder will be decrypted

**Comment by calmh** [comment]
This works for me;

```
% FOLDER_PASSWORD=p4ssw0rd ~/bin/syncthing decrypt ...
```

**Comment by lwbt** [comment]
> This works for me;
> 
> ```
> % FOLDER_PASSWORD=p4ssw0rd ~/bin/syncthing decrypt ...
> ```

Hm, that works for me too. I checked again for typos and other mistakes, awkward.

In the meantime I'll be doing:

```bash
read -rsp "Enter password: " pw
FOLDER_PASSWORD="$pw" syncthing decrypt $folder
```
That works, wasn't what I had in mind.

Close and open as enhancement request?

**Comment by calmh** [comment]
Great. Yeah I think close as not really desired or required, given that prompting can be implemented from the outside and we don't really need to duplicate it.
