### ISSUE TITLE
Shared folder won’t discover files/folders

### ISSUE THREAD

**Issue by wallart1** [syncthing/syncthing#8629]
Here is my forum post where we went over the problem in detail but did not find a solution. (https://forum.syncthing.net/t/shared-folder-wont-discover-files-folders/19204)

### Does your log mention database corruption?

If your Syncthing log reports panics because of database corruption it is
most likely a fault with your system's storage or memory. Affected log
entries will contain lines starting with `panic: leveldb`. You will need to
delete the index database to clear this, by running `syncthing
-reset-database`.

No mention of anything about the database. Tried resetting it anyway, but no change in behavior.

### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using
 -  Please see the forum post.
 - browser and version, if applicable
 - Edge browser on Windows 10.
 - what happened,
 - Please see the forum post.
 - what you expected to happen instead, and
 - Transfer of files.
 - any steps to reproduce the problem.
 - I honestly don't know what led to this. I have a theory or two in the in the forum post, but that was just guessing.

Edit: I reset the databases on both sender and receiver devices. No luck.

**Comment by calmh** [comment]
Going over it further there is the right course of action. Given that this is not something everyone experiences it must be something specific to your system. I would suspect permissions, antivirus, odd remounts, or something similar. There's anyway nothing we can do here until the cause is understood.
