### ISSUE TITLE
Enabling rate limit drastically reduces network performance

### ISSUE THREAD

**Issue by marsch1975** [syncthing/syncthing#8630]
Hi,

I was wondering about this:

SyncThing without limitation reaches a transfer speed of 119MiB/s

SyncThing with limitation of 112MiB/s reaches only 58MiB/s as max.

![50 unlimited](https://user-images.githubusercontent.com/116442584/198989448-f631f34a-d3cc-4711-9d29-f400bce0d9fd.jpg)

![51 limited](https://user-images.githubusercontent.com/116442584/198989465-c8dc1fd8-11f5-4a0f-ad00-ad6ed311bab1.jpg)

**Comment by calmh** [comment]
So for what it's worth this doesn't reproduce easily for me, with two devices on the same machine talking over localhost. That just means the limiting isn't conceptually broken, I guess there may be timing effects or fragmentation or something that makes it perform less well over a real network with latency etc.


<img width="1173" alt="Screenshot 2022-10-31 at 12 36 37" src="https://user-images.githubusercontent.com/125426/198999689-681f12c7-83d6-4dcf-bbd4-ae1ff1adf376.png">


<img width="1179" alt="Screenshot 2022-10-31 at 12 37 55" src="https://user-images.githubusercontent.com/125426/198999729-a516a0f5-f84d-41a7-b9ea-e106c455a9a4.png">

**Comment by tomasz1986** [comment]
I've personally observed that if upload rate is limited with the limit maxed out, then download rate will drop too even though there should still be enough download bandwidth available. Judging by the screenshots, this doesn't seem to be the case here, but I'm putting this information here just in case.

**Comment by calmh** [comment]
@marsch1975 I filed a potential fix/improvement you could test ^

**Comment by marsch1975** [comment]
@calmh Where is this fix? Where do I get it from?

**Comment by marsch1975** [comment]
Why did you closed this topic?

**Comment by tomasz1986** [comment]
> What does that mean? I'm not a programmer...

The fix has been merged. Now you just need to wait for a new version to be released 🙂 (which should be in the beginning of December when it comes to stable releases).

**Comment by marsch1975** [comment]
Ah, ok, that's fab! I thought I had to do something with the code provided...
Thanks for all your help guys! :)

**Comment by calmh** [comment]
Or use the nightly build which will have it now

https://docs.syncthing.net/users/releases.html#nightly-builds
