### ISSUE TITLE
Sync only specific files, ignoring directories

### ISSUE THREAD

**Issue by TMDWU** [syncthing/syncthing#8634]
Hi!, is it possible to sync only specific files without the folder structure?, been reading the documentation and looking for more information, tried some commands but it never ignores directories.

Example: picture album that has lots of folders inside ("x year" folders with "x month" folders inside), so when I try to sync from my PC to my Android it **only sends the .jpg and .mp4 files**, without the folder hierarchy, so the result would be just 1 folder with all the pictures and videos.

If it's not possible, would submit it as a Feature Request, thanks!

**Comment by nekr0z** [comment]
Please consider using [the forum][https://forum.syncthing.net/] and not the bugtracker for discussions.

**Comment by calmh** [comment]
This is currently not possible, and that kind of transformation is not something that I think we should do in Syncthing, sorry.
