### ISSUE TITLE
Android List of Devices

### ISSUE THREAD

**Issue by marsch1975** [syncthing/syncthing#8642]
Hi, me again, sorry,

on my Android phone I have 4 devices in the device list and I'm connected with only one of them...

Why is there an "up to date" for a device I'm not connected with? You can see two times a green status in the screenshot...

Android 12 App Version 1.20.1 as F-Droid didn't released 1.22.1 so far. Desktop Version used while having this problem was 1.22.0 and 1.22.1.

![Screenshot_20221104-095719_Syncthing Android -aktuell- 2](https://user-images.githubusercontent.com/116442584/199957812-b6cd35ad-4576-496b-b6e8-09d977034844.jpg)

**Comment by tomasz1986** [comment]
Please open a topic on the forum if you need a more detailed explanation or more help, but basically the fact is that the app in many cases uses a different interface and wording than Syncthing proper. I'd suggest to open the Web GUI using the left slide-out panel and see what is going on there first.

**Comment by marsch1975** [comment]
OK, will do.

**Comment by nekr0z** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
