### ISSUE TITLE
macOS Ventura 13.0 sync fails due to com.apple.provenance metadata

### ISSUE THREAD

**Issue by luckman212** [syncthing/syncthing#8648]
Since upgrading one of my Macs to Ventura 13.0, my folder will no longer sync (getting stuck on a piece of undocumented metadata called `com.apple.provenance`

I have tried removing the xattr with `sudo xattr -d com.apple.provenance /path/to/file` but that isn't working either.

Google has nothing about this really... anyone else running into this? Using syncthing-macos 1.22.0-1

_see [related post on ST forum](https://forum.syncthing.net/t/com-apple-provenance/19262)_

**Comment by xor-gate** [comment]
Moved because it is not an `syncthing-macos` application bundle problem. But the Syncthing daemon itself with trying to sync xattrs between macOS Ventura 13.0 and macOS < 13.0. See also the [forum](https://forum.syncthing.net/t/com-apple-provenance/19262).

**Comment by calmh** [comment]
As noted on the forum, this can be disabled by configuration, unfortunately only by hand editing the config at the moment:

```
<folder id="..." ...>
  <xattrFilter>
    ...
    <entry match="com.apple.provenance" permit="false"/>
    <entry match="*" permit="true"/>
  </xattrFilter>
</folder>
```

We might want to look into some sort of default black list per operating system perhaps, in the future.
