### ISSUE TITLE
i get an error saying insufficient space in folder

### ISSUE THREAD

**Issue by user4302** [syncthing/syncthing#8649]
this happened after i paused syncthing, then moved local files (and kept the '.stfolder'  intact) and then turned on syncthjing again,

following the below mentioned step fixes the issue, but is it the best way to fix it?

        It seems like we sometimes get an incorrect free space value back from the OS. You can work around it by setting the required free space to zero, in the advanced folder options I think.

_Originally posted by @calmh in https://github.com/syncthing/syncthing/issues/4079#issuecomment-291423906_

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
