### ISSUE TITLE
Syncthing rescans whole folders when individual files change.

### ISSUE THREAD

**Issue by winrg** [syncthing/syncthing#8659]
Version: v1.20.3 on Archlinux 2022-06-26
### What happened
I use syncthing to backup large directories on my laptop to a server. When watch mode is turned on, editing a file leads to syncthing rescanning the entire directory, which leads to considerable CPU usage and fan spin-up. This is especially problematic in situations where the noise might be disruptive. Of these directories is my projects folder. Editing a project leads to my laptop taking flight.
### What I expected to happen
Only the changed files being checked, instead of a full rescan of large directories.

**Comment by imsodin** [comment]
Can you enable `watchaggregator` debug logging, reproduce and post logs please.
