### ISSUE TITLE
GUI editor for xattr filter patterns

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#8660]
The per-folder xattr filter is a complex object which is not by itself editable in the advanced config editor, and there's nothing custom built for it in the normal settings editor, so it's currently unavailable except for hacking the config file manually.

There should be an editor for it in the normal settings dialog, under the xattr enablement checkboxes. There is should be possible to add a list of patterns, each with an allow/deny checkbox.

The default is to allow all attributes if there are no patterns configured; this should be indicated in the GUI. When there are any patterns at all, the default (for things not matched by any pattern) becomes deny; this should also be indicated, especially if the user just adds one deny-pattern -- we should then suggest adding a `permit *` pattern at the end, maybe even add it by default and allow it to be removed or edited, or something like that.

**Comment by luckman212** [comment]
A note about recommended patterns based on the platform would be useful too. For example, on macOS, `com.apple.provenance` appears to be "untouchable" by any process and so should probably be part of a default exclusion list (or at least strongly suggested).

**Comment by luckman212** [comment]
@calmh Awesome! 🚀
