### ISSUE TITLE
webgui complains about not set password in ldap mode

### ISSUE THREAD

**Issue by cyberb** [syncthing/syncthing#8661]
Webgui says `Username/Password has not been set for the GUI authentication` in ldap mode.

Should not do this in ldap mode.

**Comment by calmh** [comment]
This is a notification that is set on first startup. Presumably you setup LDAP after first startup -- then just acknowledge the notification and it's gone. If you somehow set up authentication before first startup (because you generated an XML config) I don't think it should display at all.

**Comment by cyberb** [comment]
I am generating the config with ldap mode before the first start, but I still see this notification (which I ack and it goes away), maybe I am missing some config to not show it at all?

**Comment by cyberb** [comment]
If I understand this correctly auto dismissal happens only if login and password are set:
https://github.com/syncthing/syncthing/blob/5e384c918567c6b92b9ae63413639dcf9628b98e/gui/default/syncthing/core/syncthingController.js#L540

**Comment by cyberb** [comment]
Not to confuse with openNoAuth warning which is different and is handling ldap mode correctly

**Comment by cyberb** [comment]
Did not test this but it probably should look like this: https://github.com/syncthing/syncthing/pull/8663

**Comment by calmh** [comment]
If you're generating a config yourself I don't see how this could happen. Syncthing has a concept of notifications that need to be acknowledged, and adds this to the config when generating a new configuration without authentication:

```
<unackedNotificationID>authenticationUserAndPassword</unackedNotificationID>
```

If you generate a config and don't add that notification, I don't think Syncthing will either.
