### ISSUE TITLE
Windows startup --no-console

### ISSUE THREAD

**Issue by Fantini2002** [syncthing/syncthing#8664]
Hi!

### Problem
After the last Windows's update, when Synching opens with

```console
--no-console --no-browser
```
(in my case, at user log in) the Terminal window doesn't close but simply minimise itself.

#### Syncthing version
v1.22.1, Windows (64-bit Intel/AMD) 
#### Windows version
Edition	Windows 11 Home
Version	22H2
Installed on	‎11/‎10/‎2022
OS build	22621.819
### Additional informations
I've tried automatic run at startup with both the built-in solutions: Task Scheduler and Startup Folder.

**Comment by tomasz1986** [comment]
https://github.com/syncthing/syncthing/issues/8046

**Comment by Fantini2002** [comment]
> #8046

Sorry for duplication
