### ISSUE TITLE
Feature request: Folder option "Delete local copies after redundancy and time"

### ISSUE THREAD

**Issue by adapt-L** [syncthing/syncthing#8668]
For me, a limitation of syncthing is that every device sharing a folder must have enough storage for the entire folder. For example, if I have I have a low-storage device like a smartphone, I can't use syncthing to automatically sync files off of it onto a swarm of high-storage devices. I would need to extend the storage of the smartphone with a microSD card, which very few smartphones have these days.

My feature idea is to add to add an additional option to folders: "Delete local copies after redundancy". The idea is that low-storage devices running syncthing should delete local copies of files once they have been uploaded to a certain number of peers (that number would be a local, user selected option: the desired "redundancy"). After that, the folder becomes "Send-only" with respect to that file.

Additionally, I would imagine that this feature would be complimented by another feature that allows you to browse the metadata (thumbnails, filenames, etc.) of remotely-stored files and temporarily download them, becoming "Send and Receive" with respect to that file temporarily. In implementing this complementary feature, it would be useful to add a time-dependent condition to the first feature to prevent it from deleting the local copy too early.

An example use-case would be syncing the camera folder of a smartphone, setting the redundancy to 2 and the time-before-deletion to 1 hour. This would treat files in the camera directory as "Send-only" and wait until it has been uploaded to at least two other peers and at least one hour has passed before deleting it's local copy. Later, they could remotely browse the remotely stored photos/videos from their smartphone and download some of them; those local copies that they just downloaded would be deleted after an hour (assuming the redundancy has not changed in that hour). I hope my description here makes sense.

I imagine this feature would be quite useful because it allows users to use their computers with lots of storage (e.g. laptops, desktops, home servers) to extend the storage of their low-storage devices like smartphones in a way that would eliminate a major use-case for centralized cloud storage (icloud, google drive, others).

One of this feature's dangers is that if multiple clients are using the "Delete local copies after redundancy and time" feature, there might be a mixup in who is supposed to store the file. For example, imagine two clients have redundancy set to 1: once they both have the file, they will both delete their local copy because they know the other one has it. Because of this, it would be necessary to exclude peers where (their desired redundancy <= your desired redundancy) in the redundancy count. That would make sure that the redundancy is always >= desired redundancy.

What do others think about this? Is this something others would like to see? Should a patch request for such a feature be accepted here?

In any case, keep up the good work with syncthing!

**Comment by calmh** [comment]
> For me, a limitation of syncthing is that every device sharing a folder must have enough storage for the entire folder.

I hear you; nonetheless, this is the base assumption and purpose of Syncthing. Stepping away from that is a complexity jar I'm not prepared to open.
