### ISSUE TITLE
Print device-id in Linux in QRcode

### ISSUE THREAD

**Issue by dmiraj** [syncthing/syncthing#8677]
- When using `syncthing -device-id` a newline will be appended to the device id, making transforming device ID to QRcode result in incorrect device ID *because `\n` is appended*. QR code could be returned by piping device ID to utility `qrencode`. Look alike:
`syncthing -device-id | qrencode -t UTF8 -o -`
- Feature can be very useful, to avoid typing characters of device ID, when entering them amongst devices.

**Comment by acolomb** [comment]
This can be solved very easily, without breaking the output for all other cases (printed to console):

    syncthing -device-id | tr -d '\n' | qrencode -t UTF8 -o -
