### ISSUE TITLE
Bump quic-go

### ISSUE THREAD

**Issue by bt90** [syncthing/syncthing#8679]
Recent versions of quic-go reduced memory allocations quite a bit: https://github.com/lucas-clemente/quic-go/issues/3526

**Comment by rasa** [comment]
Perhaps this comment should be unwound:
https://github.com/syncthing/syncthing/pull/7832#issuecomment-882797618
as it's keeping dependabot from ever creating PRs to bump quic-go. See [here](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates#managing-dependabot-pull-requests-with-comment-commands) for more details.

Or if it really wanted to be ignored, it would be helpful to do it in dependabot.yml:
```yaml
    ignore:
      - dependency-name: "quic-go"
```
per [here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore) as then it's ignored in forks as well.
