### ISSUE TITLE
Use less memory when in idle with no recent UI requests and nothing synced for a while

### ISSUE THREAD

**Issue by ell1e** [syncthing/syncthing#8681]
I'm currently on the PinePhone with 3GB total RAM and looking into why I can't run a heavier chat client like Discord without somewhat frequent out of memory kills of it even though I'm not doing much in parallel.

In gnome-system-monitor, I see syncthing in in the 3rd top spot by total memory use with a somewhat chunky 220MB, and now here comes the problem: it's not even doing anything. I'm not copying things into watched folders, there is no syncing, I haven't touched its UI in hours and in fact there hasn't even been any other device connected in hours to possibly sync to.

For nothing in return (in practice) nearly 10% of system memory constantly being blocked is pretty hefty and kind of a harder sell for a service that seems kind of designed to keep running in the background if only so whenever there is a little sync work, I don't need to always remember to manually stat t(which would defy the concept of a semi-continuous automatic sync anyway).

So if this could somehow be improved when there really wasn't anything to do for hours, that would be cool.

**Comment by calmh** [comment]
Yeah... Syncthing isn't really mobile optimized, and this is unlikely to change. Using a reasonable amount of resources is always one of our goals, but without anything specific to improve I think this is not actionable, sorry.

**Comment by ell1e** [comment]
This affects Raspberry too, so unrelated to mobile. It should affect the Android version too which I assume is more official.

**Comment by tomasz1986** [comment]
How much data do you sync exactly? The RAM usage is correlated with that. You may also try to use the 32-bit version of Syncthing (if you're on the 64-bit one right now), which should drop the RAM usage quite a bit. For further discussion/help with reducing the RAM usage, I'd suggest to create a new topic at https://forum.syncthing.net (and search the forum too, as there have been at least a few topics discussing this problem there).

**Comment by ell1e** [comment]
I've had bad experiences with discussing such things on the forum tbh. It's a giant amount of data but the thing is, at the time I wasn't actually syncing it, that kind of was the point.

**Comment by calmh** [comment]
Take a couple of memory profiles; if something sticks out, file that. A general "be better when syncing giant amounts of data on tiny machines" isn't something we can do much with.

**Comment by ell1e** [comment]
Well I'm guessing this is more of a conceptual thing though? Memory profiles are great for improving when actually busy, this however was meant to be a suggestion to detect a special extra-idle situation and slim down what is kept in memory then (to immediately load it back in once there is actual work). If that makes any sense at all?

**Comment by calmh** [comment]
It really doesn’t, unfortunately. We don’t keep things in memory for fun that can be “slimmed” at will; things are a kept while required and then no longer. But go is a garbage collected language and the garbage collector has a few knobs for tuning. I suggest learning them, experimenting with them, and if you think we are holding things in memory we shouldn’t then the memory profile is the tool to use to see what and why.

**Comment by ell1e** [comment]
I'm really just an end-user sadly, I don't have any Go knowledge. I just noticed on something like a Raspberry, mem perf is pretty bad with more files. And other daemons like gnome file tracker or gnome software usually don't have this issue.
