### ISSUE TITLE
syncthing generate command writes the deviceId to stderr instead of stdout as INFO

### ISSUE THREAD

**Issue by MinaKhamesi** [syncthing/syncthing#8682]
- syncthing version v1.22.1
  -  ubuntu 18

I had a script in which I was running `syncthing -generate=my_dir` and I was grabbing the `DevideId` from the output, after upgrading to new version of syncthing, that part of code broke, because apperantly now the deviceId is getting printed to stderr instead of stdout and my code cannot capture it. I did fix it by redirecting stderr to stdout. But it would be nice if I didn't have to do that since that is not actually an error.

the output of `syncthing -generate` before:
```
16:28:02 INFO: Device ID: 6C4FCZ7-N2OUG4Y-YYNLDGP-FSRR6RY-SQUUGRH-TIV4AAK-C3SDB62-Q4QBDQC
16:28:02 INFO: Default folder created and/or linked to new config
```

and the output I am getting now:
```
2022/11/16 16:34:33 INFO: Generating ECDSA key and certificate for syncthing...
2022/11/16 16:34:33 Device ID: 3IPJSF4-TWXI57O-P64DONH-DRCPFEL-JRWFFJT-4MLAFUR-CTJNSQG-U2JFZAO
2022/11/16 16:34:33 INFO: Default folder created and/or linked to new config
```
the first and third are INFo and are in stdout, but the middle one, devideId, is getting printed in stderr

**Comment by calmh** [comment]
This changed between 1.18.4 and 1.18.5, inadvertently, as part of moving the `generate` command.

**Comment by calmh** [comment]
I added an alternate implementation.

**Comment by MinaKhamesi** [comment]
@calmh Thanks for quick reply and quick action 👍🏼 . I see the change is in main now, do you know roughly when can I expect a release with this new change?

Thank you so much @calmh
