### ISSUE TITLE
Revert Local Changes does nothing when file is not local

### ISSUE THREAD

**Issue by Tupsi** [syncthing/syncthing#8684]
### Does your log mention database corruption?
No

If your Syncthing log reports panics because of database corruption it is
most likely a fault with your system's storage or memory. Affected log
entries will contain lines starting with `panic: leveldb`. You will need to
delete the index database to clear this, by running `syncthing
-reset-database`.

### Include required information

Please be sure to include at least:

 - 1.22.1 Linux 64-bit Intel/AMD
 - happens in all browsers
 - I have a device A sending files which get replicated fine to device B. Device B is set to "receive only", Device A is set to "send only". All works fine until device A deletes a file. Now device B states "Local Additions" because it refuses to delete the file which got deleted on device A, although it is NOT a local addition but just a remnant from an earlier sync. Consequently I get the red "Revert Local Changes" button on the GUI, but if I hit that, the file still does not get deleted. I can only see the button dissapearing as long as the system does a rescan of the folder, then the button appears again. Checking the file syste, the file is still there. Now when I ADD a file on device B and do a rescan, the system now states that there are two files as "local changes". If I hat the red button again, my newly intered file gets deleted, but the old one (which was never a local addition in the first place but a deletion occuring on device A) is still present. 
 - what you expected to happen instead, and
 I would expect the device B to delete the file which gets deleted on device A without showing my "Local Additions" as the file was never added on B.
 - any steps to reproduce the problem.
device A with a "send only" folder
device B with a "receive only" folder
put some files in the folder on device A
wait for it to sync
delete a file on device A

Now I see some other issues regarding local changes or not properly synced devices here still open, but they all read a little different what I see here. Might be the same, might not. I leave  that to you guys to decide.

**Comment by calmh** [comment]
This might be fixed in 1.22.2-rc.2, as there was an issue with new timestamp handling.

(Generally speaking I don't recommend send-only plus receive-only because you get two places that implement the same controls; send-only plus send-receive, or send-receive plus receive-only are easier to reason about.)

**Comment by Tupsi** [comment]
I agree with your recommendation about setting the folder options. It was a hail mary option for me, as the described problem also occurs in a  Send-Only + Send/Receive situation, only without the red button showing and saying that there is a local addition, but in the generall sense that a file which gets deleted on the sending end does not result in deletion on the receiving end. But as you describing a bug which gets fixed in the next release it seems to match with my problem, so I will wait and report back once I upgraded.

**Comment by Tupsi** [comment]
I just made myself a fresh docker image from the current main branch and can report that my problems are all gone. So good job and thanks for the fix!
