### ISSUE TITLE
LAN detection via subnetmask

### ISSUE THREAD

**Issue by bt90** [syncthing/syncthing#8686]
IPv6 LAN connections currently show up as WAN connections because they use public IPv6 addresses. We should check if the other address is in the same subnet to determine if it's a LAN connection.

Apart from the wrong connection type in the UI, this might also affect bandwidth limitation logic.

https://forum.syncthing.net/t/towards-better-connection-type-icons/19333/23

**Comment by bt90** [comment]
We should also treat ULA IPs as LAN:

https://github.com/syncthing/syncthing/issues/7456

**Comment by calmh** [comment]
We do compare against all directly connected networks already. If there is extra logic in the GUI that should probably be changed to just look at an `isLAN` flag from the backend, which already has that flag (but maybe doesn't expose it).

**Comment by acolomb** [comment]
I've been poking around in the code, trying to expose that flag to the GUI. Not sure I've got the cleanest possible solution, but at least it does fix the wrong classifications in my tests. Will send a PR soonish to discuss the implementation.
