### ISSUE TITLE
Two Macs, once sharing, still connected, but one out of date by two months.

### ISSUE THREAD

**Issue by JESii** [syncthing/syncthing#8688]
I have two Macs which were connected for a while and now they're not. I went to both machines to review the status:
## EDP34 - first machine to be added
![CleanShot 2022-11-21 at 08 47 10@2x](https://user-images.githubusercontent.com/486/203170339-9cfb31cb-22d1-4997-9ab7-08e1a99f3bc2.png)

## EDP32 - added to the sync...
![CleanShot 2022-11-21 at 14 43 55@2x](https://user-images.githubusercontent.com/486/203173079-18c45f01-1aba-4441-9610-c4e425045460.png)

**Anomalies** 
1. The folder path for EDP34 is "/Users/jseidel/documents/Obsidian Vault" but the folder "documents" [lower case 'd'] is not present on this machine].
2. I went to EDP32 to rename that folder, but that field is not editable
3. The Folder ID is the same, and they both show as "connected".

So I'm guessing the folder connection is borked, but I don't know how to fix it.

AND NOW -- the older version (EDP34) has overlaid the more recent version (EDP32) and two months of work is gone.
Good thing I have TimeMachine and was able to recover this.

### Does your log mention database corruption?
No

### Include required information
Syncthing - V1.22.1
MacOS BigSur - EDP34 (11.7); EDP32 (11.6.8)
Chrome - EDP34 (Version 107.0.5304.110 (Official Build) (x86_64)); EDP32 - (same)

### Expectation
Wanted them to sync up so that both machines have the same content

### Reproduce?
Sorry; no idea what happened

Would like to find a way to recover... something like: merge EDP32 => EDP34 and then copy back to EDP32 (my work machine) and then have them stay synced.
Thanks...

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
