### ISSUE TITLE
Synchronization sorting

### ISSUE THREAD

**Issue by EmJotGeh** [syncthing/syncthing#8690]
I think you lose the overview as soon as you synchronize 25 or 30 directories. Therefore my idea would be to make the synchronization sorting  more clearly by fold-out elements.

![Syncthing_Idee](https://user-images.githubusercontent.com/16000642/203627716-4b620bad-14c2-4120-8449-bdb16c1dc559.jpeg)

**Comment by AudriusButkevicius** [comment]
Sounds interesting, yet not sure what you mean by this.
Suggest you start a thread on the forum, issue tracker is more for mature concrete ideas.

**Comment by EmJotGeh** [comment]
if you synchronize for example 25-30 different directories with 5 devices, isn't it wise to tidy up the view a bit and limit the view to 5 devices as well, which you can access through an expanding menu? This can not be so difficult to understand!

**Comment by AudriusButkevicius** [comment]
Sounds like the existing folder grouping proposal.

**Comment by EmJotGeh** [comment]
ok, I have searched for it and unfortunately found nothing on the subject. However, I am not surprised, because it is just logical. Thanks for your effort :-)

**Comment by AudriusButkevicius** [comment]
https://github.com/syncthing/syncthing/issues/2070

**Comment by tomasz1986** [comment]
I think this is a little different than the folder grouping, as it essentially proposes to have shared folders listed under each device separately. Not sure if really feasible though, as you will very likely end up with the same folder listed multiple times under each remote device it's shared with (and possibly slow the GUI down a lot). The shared folder list is already available on a per remote device level, but it's currently non-interactive.

**Comment by EmJotGeh** [comment]
I think we've got it wrong. I mean that the creation of these "rootfolders" should have more of a virtual character. It should only serve to facilitate the collection of directories that are synchronized with a device, for example.
