### ISSUE TITLE
Add arm64 architecture for syncthing/discosrv container

### ISSUE THREAD

**Issue by LoHub** [syncthing/syncthing#8691]
First of all, thank you for this awesome project that I discovered this week. It is very simple to use and very well documented.

I would like to deploy my own private discosrv on a RaspberryPi with the official image [`syncthing/discosrv`](https://hub.docker.com/layers/syncthing/discosrv). Unfortunately only amd64 architecture is available.

Is it possible to support arm64 architecture for discosrv images ? I think that arm64 is a popular platform for this kind of little self-hosted service.

**Comment by Migelo** [comment]
I see that both `syncthing/discosrv`  and `syncthing/relaysrv` are not being updated on dockerhub. I just recently updated a project and got the [relaysrv](https://github.com/Migelo/docker-syncthing-relay) up to date with automated `amd64` and `arm64` architectures using GithubActions. 
If there is an interest in getting any of the two building and publishing on dockerhub/github automatically, I am happy to give it a go.

**Comment by Migelo** [comment]
@LoHub in the meantime you can check out this repo I made for you:
https://github.com/Migelo/docker-syncthing-discosrv

**Comment by calmh** [comment]
The docker images are updated, it's just that those programs don't change very often and hence aren't released very often. A change to build and publish the docker images from GitHub actions would be welcome though.

**Comment by calmh** [comment]
Currently we do the latter, since it's manual, but I don't really see a problem with pushing new images on every Syncthing release. Partly it will reduce this confusion, and at least it updates to the current Go runtime.
