### ISSUE TITLE
step of check out where's the problem.

### ISSUE THREAD

**Issue by hyaray** [syncthing/syncthing#8697]
windows: `send only`,  this is the master.
Android: `receive only`
I don't want see `sync-conflict` files at both side
sync not worked, is this the step to check out the problem? thanks a lot!!
1. check both to ✅ share to each other.
2. check device is on connect: ①how to check this?
3. check `sender` has got the event of file updated: ②how to check? ③click `rescan` will make this step done?
4. check `receiver` has got the event from `sender`: ④how to check this step done?
5. check the log: [where-are-the-syncthing-logs](https://docs.syncthing.net/v1.22.0/users/faq.html#where-are-the-syncthing-logs)
6. other deal：⑤how to avoid of creating `sync-conflict` files.

I wish this step can be found at [faq](https://docs.syncthing.net/v1.22.0/users/faq.html#faq).
Best Regards!!

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
