### ISSUE TITLE
docker hub has old image tagged as 1.22.2

### ISSUE THREAD

**Issue by Tupsi** [syncthing/syncthing#8705]
you might want to reupload an image tagged as 1.22.2. The one up there is from a week ago and still has nc instead of curl as healthcheck. Seeing the 1.22.2 is only a few hours old on github it seems strange.
<img width="652" alt="image" src="https://user-images.githubusercontent.com/3730499/205926951-337cb0d7-8ff5-465b-b43f-bd61bfa3036c.png">

<img width="880" alt="image" src="https://user-images.githubusercontent.com/3730499/205927260-daa49076-7514-4b02-9ed7-714a915c37f1.png">

<img width="130" alt="image" src="https://user-images.githubusercontent.com/3730499/205927597-3eab843a-729a-4acc-988e-2e2ebd8d2ddc.png">

<img width="144" alt="image" src="https://user-images.githubusercontent.com/3730499/205927652-effc3ed7-131a-4381-af61-84f7f033f6b9.png">

**Comment by calmh** [comment]
Yeah, the image is actually correct however, unfortunately, the PR that changed the health check didn't update *both* places where it needs to change. I fixed that now in #8706 so it'll be in the next release.

**Comment by Tupsi** [comment]
You nee to add the run line (18)  as well, otherwise the image does not have curl.
