### ISSUE TITLE
GUI for excluding receiving certain subfolders on client (not just root folder)

### ISSUE THREAD

**Issue by t3dium** [syncthing/syncthing#8707]
currently only the root folders of shares show when trying to ignore receiving them on a specific client, and doesn't show folders/files within it. 

![librewolf_70wNmAaKNu](https://user-images.githubusercontent.com/83690012/206017570-18538a0c-f1c5-4ac8-9f8a-c0f4d9ca1698.png)

i know this is possible via an .stignore config, but i can't figure out how to get this working on android, and having it in syncthing's gui would be a lot more convenient.

**Comment by tomasz1986** [comment]
There seem to be quite a big confusion here. When you add a new folder to Syncthing pointing it a specific path, it includes everything under that path. Syncthing only allows to share full folders between devices, which is what the screenshot above shows.

Now, you can of course use ignore patterns to sync only specific subpaths (but at the same time you still technically share the whole folder). There is no difference between Syncthing on the desktop and Syncthing on Android here. However, the native Android GUI is quite limited, so you may want to use the Web GUI (available through the slide-out left panel) which offers the same interface as in Syncthing desktop.

If you've got more questions or need more help with the specific configuration, I would suggest to open a new topic at https://forum.syncthing.net.

**Comment by AudriusButkevicius** [comment]
Sounds like you need help setting up ignores on android, in which case yes, the forum is the right place for this. 
The general mode of operation in syncthing is by folder, so no, sharing parts of a folder is not possible unless you add a new folder pointing to that specific subpath.
