### ISSUE TITLE
(Mac) Icon resource file should not block directory delete

### ISSUE THREAD

**Issue by galund** [syncthing/syncthing#872]
Mac OS X sometimes write an icon file into a directory as a special resource link of some kind (see http://superuser.com/questions/298785/icon-file-on-os-x-desktop - the name is "Icon\r").

This caused a problem for me, when I deleted a folder from my PC, and it should have been removed from the Mac.

SyncThing could not remove the folder, because on the Mac side, it considered the directory "not empty", because it never deleted the icon resource.

If syncthing wants to treat these as files, it maybe should sync them to the PC side (if possible - they are strange zero-byte things). Otherwise, it will have to be prepared to delete directories that contain nothing but those files (auto-ignore, perhaps).

**Comment by Zillode** [comment]
Is this the same as https://github.com/syncthing/syncthing/issues/1631?

**Comment by calmh** [comment]
These are now handled by `(?d)Icon?` in ignore patterns
