### ISSUE TITLE
ignore old files

### ISSUE THREAD

**Issue by voxspox** [syncthing/syncthing#8724]
I want to suggest to extend the "ignore pattern" feature. It would be nice to include/exclude files by filtering by (file modification) date.

**what problem your new feature would solve**

I have photos on my mobile and shared (send only) this folder to my desktop computer. There I organize the photos by year. After that, I only want to sync files which are newer. Therefor it would be nice to have a *sync condition*, here: a minimum date.

**how or why you think it is generally useful (i.e., not just for you)**
Ignore old files.

**what alternatives or workarounds you considered**
My phone puts the year (date and time) in the filename, thus using a file pattern mostly works.

**Comment by calmh** [comment]
This has been discussed on the forum a lot; basing ignore decisions on file metadata is confusing and doesn't work well in Syncthing, and will very likely not be implemented; sorry.
