### ISSUE TITLE
Embedding Syncthing as a Server

### ISSUE THREAD

**Issue by lonnietc** [syncthing/syncthing#8729]
Hello,

In the old days, a person could setup use an FTP server and then came SSH that provided SCP/SFTP which was more secure for fileserver. Now it seems that QUIC, based upon UDP, has become available to a degree which is supposed to be significantly faster than TCP protocol while also being reliable.

To this end, I have come across Syncthing in Go which seems to be a good file synchronizing solution but for my project, I am considering something QUIC based for the low latency solution but am wondering if Syncthing could be used as an embedded library so that it could be used as a type of synchronizing fileserver in a type of P2P project.

Although I am still researching many other possibilities as well, I think that this could be viable solution if it were available.
Thanks, and have great day.

**Comment by bt90** [comment]
Syncthing already uses QUIC as an alternative protocol. TCP is still prefered though: #8626

**Comment by lonnietc** [comment]
Yea, I had understood that Syncthing had QUIC capabilities, but I was trying to investigate if Syncthinq could be used as an embedded library since what I need is a type of QUIC fileserver for client connections as well as a fileserver that can synchronize directories with other fileservers as well.

Was not sure if Syncthing could be used in this way and it seemed like a good idea for a core P2P system to be developed with Syncthing as a core library.

**Comment by calmh** [comment]
It can be; there's a C++ gui implementation that does this for example.
