### ISSUE TITLE
Syncthing services down?

### ISSUE THREAD

**Issue by sturgman** [syncthing/syncthing#8739]
Seems like syncthing's forum and website are down. I am also getting the following issues and failures in connecting my nodes:

> Some listening addresses could not be enabled to accept connections:

>    dynamic+https://relays.syncthing.net/endpoint: Get "https://relays.syncthing.net/endpoint": net/http: TLS handshake timeout

and

> Some discovery methods could not be established for finding other devices or announcing this device:

>    global@https://discovery-v4.syncthing.net/v2/: Post "https://discovery-v4.syncthing.net/v2/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
>    global@https://discovery-v6.syncthing.net/v2/: Post "https://discovery-v6.syncthing.net/v2/": dial tcp: lookup discovery-v6.syncthing.net: no such host

**Comment by acolomb** [comment]
I can't confirm this. All services are working for me (from Germany).

**Comment by sturgman** [comment]
Seems to be a new local policy at work. Apologies for the noise.
