### ISSUE TITLE
ACME support for GUI

### ISSUE THREAD

**Issue by awagner-iq** [syncthing/syncthing#8740]
I would like to re-open #2445. To be honest, I'm not sure why that issue was closed. The rationale at the time was that there is no point. But it seems to me the use cases for HTTPS and ACME are well-documented. The GUI takes usernames and passwords, so clearly it is useful for it to get transport level security. Additionally, more and more web APIs and browser features require an HTTPS connection to work. As for ACME, the benefit is the same as always, it allows to regularly rotate certificates without having to manually provision them.

In my particular setup, I have a private network with a dedicated domain (say `example.com`) and it is already set up so that every host is automatically resolvable as `<hostname>.example.com`. Further, there is an ACME server running which can provision trusted certificates for `example.com` and can verify the identity of the host by IP. So, if `syncthing` was able to use ACME, all I'd need is to tell it to ask `acme.example.com` for a certificate and I could expose the GUI securely to my private network.

In general, people might have the ability to make some or all of their hosts publicly routed (e.g. using `dynDNS`, or maybe they get a static IP from their provider) and would like to expose their syncthing GUIs remotely - and again, using HTTPS is basically a must and ACME (e.g. using Let's Encrypt) would make things easier for them.

I'd be willing to contribute this, using [x/crypto/acme](https://pkg.go.dev/golang.org/x/crypto/acme). But I first wanted to ask if this would be a welcome pull request.

**Comment by acolomb** [comment]
Why not just any off-the-shelf ACME client and simply replace the `https-cert.pem` / `https-key.pem` files, then trigger a Syncthing restart through the API?

**Comment by bt90** [comment]
Agreed. A proper reverse proxy is much more flexible in this regard, as you can host multiple services on different subdomains with LE certificates without the need to run an additional ACME server.

**Comment by awagner-iq** [comment]
> Why not just any off-the-shelf ACME client and simply replace the https-cert.pem / https-key.pem files, then trigger a Syncthing restart through the API?

Because that is significantly more operational effort than just have `syncthing` request the certificates itself.

> Agreed. A proper reverse proxy is much more flexible in this regard, as you can host multiple services on different subdomains with LE certificates without the need to run an additional ACME server.

But it requires me to run another service, with extra configuration for the proxy->syncthing connection.

The convenience factor is a) do a bunch of extra, manual provisioning of certificates and/or set up a proxy on every host I want to use `syncthing` for which does nothing but terminate TLS for `syncthing` or b) store `acme.example.com` in the `syncthing` config. To me, that convenience seems a pretty obvious and clear win in convenience.

TBQH I'm a bit befuddled by these arguments. For one, ISTM that there shouldn't be HTTPS support then, to begin with, as exactly the same arguments apply to the existing mechanism. Plus, self-signed certificates require the user to risk exposing ~every host they use `syncthing` on to MitM attacks for any service on the web by installing an untrusted CA certificate.

ACME gives a user-friendly, automatic way to provision trusted, secure certificates for hostnames they own and there is a Go package which is battle-tested, maintained by the Go team and allows to take advantage of ACME in a small handful of LOC. To me, it seems like a no-brainer to either not support HTTPS at all, or to support ACME directly.

**Comment by calmh** [comment]
I think you are in an exceedingly small minority, running the Syncthing GUI as the primary thing on port 443 on a FQDN. (Not to mention the whole my-own-ACME-server thing which I would guess is more os less unheard of). No disrespect intended, it's a cool setup, but I doubt the general utility and there is always the tradeoff between your operational complexity (which you seem well equipped to handle) and our development, maintenance, and support burden.

**Comment by Merovius** [comment]
(private account of @awagner-iq reporter here)

Hm. There is indeed some complication. FWIW I don't run the GUI on Port 443. But that's because I don't have to rely on the `tls-alpn-01` challenge (indeed, in my deployment there isn't any ACME challenge that needs solving by `syncthing`). Solving the `dns-01` challenge would be the other broadly useful option. But that's significantly harder to implement and configure and I can see why putting all of that complexity into `syncthing` is a bad idea.

I see now, that this is less broadly and obviously useful than I thought. I'd still really like the option :-/
Even if it is an expert setting not exposed in the GUI.

**Comment by calmh** [comment]
> FWIW I don't run the GUI on Port 443.

I don't blame you, I would think hardly anyone does, but that's the only reasonable way I see this could work (TLS SNI or TLS ALPN challenges). I sitll think that's out of scope and the few people who want this are better served by spinning up a Caddy or Traefik in front of Syncthing, though. DNS challenges are *way* out of scope though.

**Comment by calmh** [comment]
I'm going to close this again because I think that given the alternatives it's not something we want to do. Sorry.
