### ISSUE TITLE
If a file is renamed to its name without underscores it will be deleted at the next sync.

### ISSUE THREAD

**Issue by FriederHannenheim** [syncthing/syncthing#8741]
If a file is renamed to its name without underscores (in my case RESO_DRONE.mp3 to "RESO DRONE.mp3") it will be deleted at the next sync.

![image](https://user-images.githubusercontent.com/41985738/211209219-c690c511-f9c7-4a2b-bf64-082cb4220ff0.png)

**Comment by tomasz1986** [comment]
Android is likely the culprit. Please open a topic on https://forum.syncthing.net for the further investigation. Please make sure to include information about Syncthing version numbers on both devices.

**Comment by FriederHannenheim** [comment]
Here it is: https://forum.syncthing.net/t/if-a-file-is-renamed-to-its-name-without-underscores-it-will-be-deleted-at-the-next-sync/19626
