### ISSUE TITLE
Thoughts on the mutual Introducer problem.

### ISSUE THREAD

**Issue by paven** [syncthing/syncthing#8748]
- what problem your new feature would solve
I do not think I am alone as thinking of my Syncthing as one thing regardless of device it happens to present it self to.  Having multiple trusted devices that may be used to add more machines to the Syncthing hive without getting conflicts would be awesome
 - how or why you think it is generally useful (i.e., not just for you)
I think, the current way of introduction is exposing a bit to much of the underlying solution, and my adjusting it it would solve the problem for many people. I have not yet looked at any code, but on how it works for me as a user.
 - what alternatives or workarounds you considered
1: The first alternative keeps the current solution, and changes a bit on how to interact with it. An introducer gets a rank. Any introducer with better rank can introduce to introduces lower in the hierarchy. This is basicaly what you are asking me to do, by linking my intems to eachother, but presenting it as a rank it would simplify things.
2:  Create a blockchain of changes (like git) directed acyclic graph . Where the removal and introduction are added to the chaine and shared. Not the current state. That DAG could probably be trimmed in hive negotiations from time to time. This could remove the geting out of sync problem.
3: Have an level of introducer, where the new introduction is sent automaticaly, but must be accepted  manual,  with notification if possible. That would keep the simplicity of not having to manually trigger activiites, but in a smoth flow accept them.

I hope any of these sugestions sounds interesting to you. Let me know how if you want help.

**Comment by calmh** [comment]
Given these are thoughts for discussion, I think the correct place is the forum. Once a direction has been decided and there's something actionable to implement that will suit as a GitHub issue.
