### ISSUE TITLE
Connection Type shows TCP WAN for private IPv4 address

### ISSUE THREAD

**Issue by wolf-joe** [syncthing/syncthing#8751]
I have two device in same **LAN**:
1. nas
   * version: v1.23.0, Linux (64-bit Intel/AMD)
   * ip: 192.168.1.10 / 172.17.0.1
2. phone
   * version: v1.23.0, android (64-bit ARM)
   * ip: 192.168.1.94 (gateway: 192.168.1.10)

But the phone's syncthing web UI shows that `Connection Type` between the phone and the nas is **TCP WAN**, That's wired, because `172.16.0.0/12` is a private IPv4 address range.
![image](https://user-images.githubusercontent.com/58905296/212545066-d1d068f0-f84a-4b70-aba3-418b6ee13b5d.png)

Through [the source code](https://github.com/syncthing/syncthing/blob/v1.23.0/lib/connections/service.go#L717), we can see there is no private IPv4 address check in `isLan()`, I think this is the problem.

**Comment by calmh** [comment]
LAN/WAN in Syncthing parlance is about whether it's a directly connected network or not. In this case the phone has a 192.168-address as is connected to a 172.17-address, which is on a different network (one it doesn't have an address on). That makes it "WAN" from the point of the GUI.

**Comment by acolomb** [comment]
Correct, you basically said it yourself that there is a gateway involved, hence it is not the same local network by our classification.

**Comment by GermanCoding** [comment]
Isn't this configurable via https://docs.syncthing.net/users/config.html#config-option-options.alwayslocalnet? So if one wants specific subnets to be treated as LAN (for the rate limiter & GUI display), this is already configurable?

**Comment by calmh** [comment]
Yes.
