### ISSUE TITLE
Allow upload from web interface

### ISSUE THREAD

**Issue by wiwwo** [syncthing/syncthing#8752]
It happens everybody to use company hardware, where installing software is blocked.
It would be great to still have the opportunity to upload (and maybe download) stuff from the web interface, since web browsers are normally already installed on those machines, and tunneling to a owned syncthing instance might also be viable.

**Comment by er-pa** [comment]
This sounds like, at least to me, that you want to (mis)use Syncthing to solve a problem that is not even in the scope of this project:). Unless I understood your suggestion incorrectly.

There are plenty of ways to push files to or pull files from a device without having to install specific software to do so.

**Comment by calmh** [comment]
Yeah I'm not entirely sure what's being asked here, but Syncthing doesn't sync over any form of HTTP(s) and tunneling through some other web server isn't going to work. (Unless it's a pure TCP proxy, but then you can already do that.)
