### ISSUE TITLE
"no connected device has the required version of this file" due to race condition

### ISSUE THREAD

**Issue by tsbertalan** [syncthing/syncthing#8759]
- which version of Syncthing and what operating system you are using
   - 1.23.0 android (displaying the error), and
   - 1.23.0 linux (main server sending the data)
 - what happened
   - After a sync began but before it got to syncing the file in question, the file was modified on the server, so the planned sync couldn't go forward.
   - Subsequent syncs (even without modifications during the sync) still fail.
 - what you expected to happen instead, and
   - The error should only be given on the first attempt (the one with the racy sequence of events).
   - Subsequent syncs should clear the error.
 - any steps to reproduce the problem.
   - Set up a slow-to-execute sync and change a file in the middle as described above, I imagine.

Is there perhaps some sort of cache-clearing I can do to work around this error when it happens? It's usually triggered when my IDE is auto-saving a Python file frequently, but my tablet is slow to actually do those syncs.

**Comment by tsbertalan** [comment]
This may have been what was happening in #6818.

**Comment by calmh** [comment]
Can't reproduce, needs more info :/
