### ISSUE TITLE
Screensaver does not work when SyncThing is on

### ISSUE THREAD

**Issue by deathknightracer** [syncthing/syncthing#8765]
### Does your log mention database corruption?

If your Syncthing log reports panics because of database corruption it is
most likely a fault with your system's storage or memory. Affected log
entries will contain lines starting with `panic: leveldb`. You will need to
delete the index database to clear this, by running `syncthing
-reset-database`.

### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using
 - browser and version, if applicable
 - what happened,
 - what you expected to happen instead, and
 - any steps to reproduce the problem.

Operating System Info:
![image](https://user-images.githubusercontent.com/96958544/215359835-7465e917-a073-4e75-ad4d-9537e214e0ab.png)

Version Info:
![image](https://user-images.githubusercontent.com/96958544/215359869-be97c162-c2e4-4f6f-93c7-ef91ae4625cf.png)

What happens:
My screensaver will turn on, but then gets disabled even if I am not touching computer. Happens randomly, and only happens when synctray is in use in the background. I want the screensaver to stay even if I am using synctray in the background.

**Comment by calmh** [comment]
I think you need to look at the "synctray" app and maybe file an issue there. Syncthing itself has no integration with any screensaver, it's a background service that just talks over the network.
