### ISSUE TITLE
Sync sync progress

### ISSUE THREAD

**Issue by BartG95** [syncthing/syncthing#8773]
The double 'sync' is not a typo.

Suppose a cluster of three devices, Alpha, Bravo and Charlie.
They are all connected, but Alpha and Bravo are seldom simultaneously online. Charlie is almost always online.
When Alpha updates a file, it will sync to Charlie. Then Alpha goes offline, Bravo goes online, and Bravo receives the update from Charlie. Then Bravo goes offline, Alpha goes online. 
Alpha will show that is has pending updates for Bravo, while in fact, those updates are already on Bravo.

Maybe Charlie can sync this sync progress?

**Comment by nekr0z** [comment]
Charlie has no way of knowing that Alpha even knows that Bravo exists, unless there's a common introducer.

Syncing the sync status via a common introducer or a chain of introducers may be feasible, though. I think I could try to work on this, if maintainers think such a feature would be welcome.

**Comment by calmh** [comment]
This is not a trivial addition, I think, and I'm unsure it's worth it.

**Comment by BartG95** [comment]
> Charlie has no way of knowing that Alpha even knows that Bravo exists, unless there's a common introducer.

Well, sync that as well?

But yeah, I am aware of the complexity of this.

**Comment by nekr0z** [comment]
> Well, sync that as well?

That's potentially leaking information that may be private; not worth it for a convenience feature like this one.

**Comment by acolomb** [comment]
Actually the `ClusterConfig` message does include information about third parties sharing the same folders.  That is valuable and useful, though not currently getting exposed within Syncthing in any way.  Something I initially set out to improve, but didn't get to work on much lately.

**Comment by calmh** [comment]
I don't think we want to do this.
