### ISSUE TITLE
Syncthing panics when `HOME`-directory is empty

### ISSUE THREAD

**Issue by Martchus** [syncthing/syncthing#8785]
## Steps to reproduce
On GNU/Linux (but supposedly also on other platforms using the `HOME` environment variable):
```
$ export HOME=
$ syncthing --help
$HOME is not defined
panic: Failed to get user home dir

goroutine 1 [running]:
github.com/syncthing/syncthing/lib/locations.userHomeDir()
        github.com/syncthing/syncthing/lib/locations/locations.go:228 +0x7d
github.com/syncthing/syncthing/lib/locations.init.0()
        github.com/syncthing/syncthing/lib/locations/locations.go:56 +0x1d
```

I could reproduce this with v1.23.1 from openSUSE Tumbleweed but likely any version/build is affected.

## Expected behavior
I'm not sure what *should* happen. However, the current "panic" is likely unexpected as it makes it look like a programming error to the user. I suppose there are multiple options:

1. The user is instructed to set `HOME`. (The current error makes it looks like an internal error of Syncthing and not like the user has forgotten to set something up.)
2. Syncthing can cope with the fact that the home directory is empty (but maybe still prints a warning).
3. If 2. is not possible, then at least `--help` could without home directory. Maybe `serve` with `--home` could work as well without home directory from environment.

## Further notes
This issue was discovered by a user that tried to run Syncthing Tray's integration tests (which spawn Syncthing itself) in a build environment where `HOME` was not set. I'm not sure why he had no `HOME` directory set.

**Comment by calmh** [comment]
I think the reason it's a panic is that this runs as part of some very early initialization stuff (preparing default values for command line options and such), and it's easier to treat it as something that can't fail -- because it pretty much never does. I think the first two lines of the output are quite explanatory.

**Comment by Martchus** [comment]
The words "panic" and the trace just make it look like it is a developer-facing error message that I as a user probably shouldn't see. Hence I reported the ticket to you (the developers). I personally also don't have a problem making sense of the error message itself.

**Comment by calmh** [comment]
> The words "panic" and the trace just make it look like it is a developer-facing error message that I as a user probably shouldn't see.

I agree. And I haven't heard of a user who've seen it yet. :) You guys doing builds under unusual circumstances count as developers. If and when there's some common deployment scenario where Syncthing needs to run without a `$HOME` we can look at making it more user facing...

**Comment by Martchus** [comment]
> You guys doing builds under unusual circumstances count as developers.

That is true, indeed. Unfortunately under GNU/Linux mere users are often confronted with development tasks, e.g. building software from sources (like building AUR packages with questionable "helpers" to ease the pain). However, I don't think this problem of GNU/Linux should/can be solved by Syncthing. I'm just mentioning it as explanation why users see these messages when normally only developers are expected to see them.

**Comment by Martchus** [comment]
> I don't think it's “unusual” entirely, Arch/Manjaro/EndeavourOS are rather popular as a means of getting away from ancient, decrepit software libraries-based distros such as Debian, Mint, all that.

I was talking about the GNU/Linux ecosystem as a whole but I think following up on that further is out of scope here.

> Solved it by removing the tests …

`makepkg` supports the `--nocheck` flag. There's no need to patch-out anything. Note that I have also changed the test environment of Syncthing Tray to not rely on `HOME` being set in the build environment so tests should pass now regardless of that. (It is also generally considered best practice to actually run the upstream testsuite as part of a package build so I would not needlessly divert from that.)

**Comment by calmh** [comment]
It is unusual, because it's the first time in a decade anyone has reported running into this, at build time or otherwise.
