### ISSUE TITLE
Maximum amount of peer 

### ISSUE THREAD

**Issue by LeReverandNox** [syncthing/syncthing#879]
Hello,
We currently use Syncthing for an amateur project involving more than 60 users on the same shared master folder, from our server. (currently 66 peers)
Since that we exceed 63 users at she same time, nobody can synchronize anymore. We have to unselect some of their nodes, falling back to 63, so the others can keep synchronizing.

Is there a limit on the amount of peer that we can share with from a single client ?

Thanks
(Please excuse my awfull English...)

**Comment by selfuntitled** [comment]
Just to clarify - this is in theory fixed in the current 11.0 beta6 or 10.3?  I don't see this ticket number referenced in any of the release notes.

**Comment by rumpelsepp** [comment]
check this one: https://github.com/syncthing/syncthing/pull/886

**Comment by calmh** [comment]
This was fixed in v0.10.3.
