### ISSUE TITLE
Different ID after each reboot

### ISSUE THREAD

**Issue by everdrone** [syncthing/syncthing#8817]
- Syncthing 1.23.2
 - Windows 11

The device ID changes on every reboot, prompting on all other devices to accept the new one, losing the connection to the previous ID

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
