### ISSUE TITLE
some files mysteriously remain 'out of sync'

### ISSUE THREAD

**Issue by sandokanfirst** [syncthing/syncthing#8823]
### Does your log mention database corruption?
No

### Include required information

Please be sure to include at least:
version of Syncthing: 1.23.2, OS: DSM (Linux flavor Synology Disk Station)
browser: Chrome

My issue is that a few files would never synchronise from a  Send Only folder (on my DiskStation) to my phone. I will attach a screenshot here that only shows one file that's out of sync. The other files are gone, because of a work-around I found: when I rename the problematic file twice, once to something different and then back to its original name again, the file gets synchronized in the end.

I've looked at the permissions of the problematic files but they were exactly the same as the others. In this case there is a file that has been successfully synched, CD1.m3u, while CD2.m3u remains stuck. I can very easily force this file to sync too by changing its name and back. But it is rather annoying.

![nosync](https://user-images.githubusercontent.com/36963445/224504301-6e4e1523-1cdb-413c-a70a-183572e0576a.jpg)

**Comment by calmh** [comment]
IF it's out of sync that should be because it failed -- what does the GUI say about that? What do the logs?
