### ISSUE TITLE
Adding new features to a property folder type

### ISSUE THREAD

**Issue by aaakjt** [syncthing/syncthing#8829]
There is a problem on all operating systems.. namely.  
There are three types of folders. 
 It is send only.  reception only.  and sending and receiving.  as in the picture. 
![Screenshot_٢٠٢٣٠٣١٩_٢٠١٣١١_Syncthing](https://user-images.githubusercontent.com/55236360/226199816-4c888e16-e3b1-4b8e-9b72-05a35dedf868.jpg)

 It is very restrictive and very simple and is not suitable for anyone who wants to make an integrated synchronization or an integrated backup..
 If someone wants to make a backup of his phone on his personal computer 
while deleting the phone files just to increase the phone’s memory space, for example.  
The syncthing will delete the files that have been synced and that are on the computer as well..
if we can give more powers to sync as it is in one of the programs that you used previously as in the picture
![Screenshot_٢٠٢٣٠٣١٩_٢٠١٥٣٣_WhatsApp](https://user-images.githubusercontent.com/55236360/226199855-00ddcae5-a5cd-4c84-83d4-dcffe083c55a.jpg)

we will do a unique and professional sync

**Comment by AudriusButkevicius** [comment]
The clue is in the name.

Syncthing syncs things, i.e, synchronizes, makes them look the same on both sides.

What you want "upload and delete/download and delete" etc is not what syncthing does, or aims to do, or is interested in doing.

Syncthing is not backup software.
