### ISSUE TITLE
Device ID spontaneously changed, all connections dead, tries to make a new connection with new Device ID

### ISSUE THREAD

**Issue by Hard-Wired** [syncthing/syncthing#8837]
- Windows 10 21H2 (problems started shortly after March update) / Syncthing 1.23.2
 - SyncTrayzor 1.1.28
 - Primary device has spontaneously changed its Device ID. All devices that have had a connection for years now no longer connect.
   - Primary device shows "Failed to exchange Hello messages with XXXXXXX at [::]:22000-192.168.1.69:22000/quic-client/TLS1.3-TLS_CHACHA20_POLY1305_SHA256: EOF"
   - Shared to devices show "INFO: Connection from XXXXXXX at 192.168.1.14:22000 (tcp-server) rejected: device is ignored"
   - Shared to devices are all recieving a "New device / Device X-X-X-X-X-X-X-X wants to connect. Add new device?" message with Primary device's new Device ID.
   - Primary device had a Remote Device listed as itself, but with its old Device ID, never connected. (I removed it, but it did not fix the problem)
 - Rebooting all devices does not fix the problem.

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
