### ISSUE TITLE
Ability to disable warnings about insecure access

### ISSUE THREAD

**Issue by spantaleev** [syncthing/syncthing#8841]
I'm protected my Syncthing installation with HTTP Basic Auth at the reverse-proxy level (Traefik), so Syncthing complaining that its own HTTP Basic Auth protection is not enabled is annoying and not helpful.

Others may be using something like [Authelia](https://www.authelia.com/) to secure their Syncthing installation.

I've tried to hide the warning permanently by going to **Actions** -> **Advanced** -> **GUI** section and checking the **Insecure Admin Access** checkbox. The red warning message did disappear, but every once in a while it would show me an orange warning saying that insecure access is enabled.

It would be nice to be able to tell Syncthing "I'm securing this instance in another way, so.. be chill about it and don't bother me".

**Comment by imsodin** [comment]
That warning comes up on every restart.

I would like that too, but I think there have been previous discussions on this and the project consensus was that it should be kept (couldn't find them really quickly). As the annoyance to users like us that know what they are doing is less harm than the potential problems it causes to unsuspecting users. Though probably the reasoning was different, as an opt-out wouldn't really change that (as in only users like us will opt out, so unsuspecting users still get notified). Maybe it was that we actually don't know what we are doing, and it's still insecure and we shouldn't do it (resp. for a proxy, you should still have auth and let the proxy inject that). Again not my opinion (in a personal tool I like being able to get rid of complexity at the cost of security in depth), others that have that opinion can likely argue it better :) 

Also relevant, as it's suggesting something to the opposite effect that would also make the warning unnecessary: https://github.com/syncthing/syncthing/issues/3357

**Comment by calmh** [comment]
Can you add a static `Authorization` header in the reverse proxy? Then the GUI is protected, Syncthing is happy.

**Comment by calmh** [comment]
Closing as I don't see a compelling reason to change the current behavior and there is a workaround available.
