### ISSUE TITLE
Sync fails when tmp file name is too long to be created

### ISSUE THREAD

**Issue by endolith** [syncthing/syncthing#885]
```
[PFTGP] 10:37:25 INFO: Puller (folder "engineering_documents", file "long file name"): dst create: open path\~syncthing~.long file name.pdf.tmp: The system cannot find the path specified.
[PFTGP] 11:33:58 WARNING: Folder "engineering_documents" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.
```

When I try to manually create a file with the same .tmp file name manually, I can't, because the path+file name is too long for Windows.  Without the `~syncthing~.` and `.tmp` it's an ok length.

**Comment by freddy961** [comment]
Hey you can use LongPathTool to solve the problem of long paths of the files.

**Comment by AudriusButkevicius** [comment]
I believe you can work around the filepath limit if you specify `\\?\C:\Path\To\My\Folder` in the config.xml.

Though it's not tested.

**Comment by ropeladder** [comment]
Just tried the workaround (I was having the same problem as the OP) and it works for me.

**Comment by endolith** [comment]
I'm still having a lot of problems with this.

I create files on one computer (usually scientific papers with long names), and then when I go to my other location I get "Folder ... isn't making progress" and the files haven't synced because the filenames are too long for the local computer.  I don't care at all what the filenames are, I would happily shorten them, but I have no control over it now because the filename is being set by a computer I'm not sitting at, so I'm just stuck with no access to the files and syncing paused.

**Comment by AudriusButkevicius** [comment]
Check my last comment.

**Comment by endolith** [comment]
This?

> I believe you can work around the filepath limit if you specify \\?\C:\Path\To\My\Folder in the config.xml.

I don't understand

**Comment by AudriusButkevicius** [comment]
Replace `~\` with your full folder path, and prefix it with `\\?\` as explained.

**Comment by endolith** [comment]
It synced now, thanks!  What does that do though?

**Comment by jatubio** [comment]
Thanks a lot, the trick of `Replace ~\... with your full folder path, and prefix it with \\?\` worked for me! :)

I have doc them in wiki: https://github.com/syncthing/syncthing/wiki/Windows-Troubleshooting-Guide

(Sorry for my english.. if it's not very good hope some kind soul correct them ;) )

**Comment by Luisa456** [comment]
Resolve the Path Too Long error with the help of ‘Long Path Tool’.
