### ISSUE TITLE
Multiple new feature requests

### ISSUE THREAD

**Issue by hktalent** [syncthing/syncthing#8854]
### CLI
Well, what I want to say is that, like me, I am used to the CLI and don’t like the web UI, and it is more convenient and quick to use the CLI. Of course, the parameters can be configured through something like config.json

## I want to have permission configuration like this
Usually I don’t have enough local space, and I just want to synchronize some directories from a distance according to my settings. At the same time, I hope that the local modification can be synchronized to the remote server. However, I hope that after the local deletion, the remote server will not be deleted, unless I forcibly delete the data on the remote server through the displayed command or webui, which is also to ensure the security of files and data. Of course, several versions need to be kept for synchronizing past data. It would be more perfect if it can support version management like git

## distributed storage
Yes, the storage space on the server may not be enough. I hope that through configuration, the data can be distributed redundantly and distributed on multiple nodes, so as to avoid the loss of data caused by the failure of a single node’s equipment
Of course, some algorithms for redundant storage are needed here, as well as many technologies such as consistency, synchronization, and distributed storage.

**Comment by calmh** [comment]
I think, in order:

1. `syncthing cli --help`
2. The `ignoreDelete` advanced folder option
3. No; Synchting is a sync tool, this is not sync but something like a distributed filesystem. Those exist, and are outside of Syncthing scope.

**Comment by hktalent** [comment]
ok, thanks
