### ISSUE TITLE
Key is stored in legacy trusted.gpg keyring

### ISSUE THREAD

**Issue by morciej** [syncthing/syncthing#8855]
I get the following "error" (warning, really) from Update Manager when running Refresh:

`W: https://apt.syncthing.net/dists/syncthing/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.`

- My system is Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy.
- Syncthing version 1.23.4
- Steps to reproduce: have MintUpdate running, open from tray, click Refresh button.

I checked the apt-key manual. It should be an easy fix.

**Comment by bt90** [comment]
Did you follow an old guide by any chance?

https://apt.syncthing.net/ already follows the new approach

**Comment by morciej** [comment]
Probably happened with upgrade to Linux Mint 21. The system was complaining about a number of external repositories I had. No problem then.
