### ISSUE TITLE
Syncthing incorrectly deletes and create  a same direcotry on sync 

### ISSUE THREAD

**Issue by surandor** [syncthing/syncthing#8873]
I create two folder sync under sendreceive mode. When  i delete a directory and then recreate it , the other folder received changes can't sense any file change any more.

**Comment by surandor** [comment]
I test it on ubuntu os.

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
