### ISSUE TITLE
Renaming folder starts copying all files

### ISSUE THREAD

**Issue by azatsh** [syncthing/syncthing#8875]
I have a folder that is in sync (bidirectional) on two computers. 
When I rename the folder on one computer the second instance does not just rename the folder it creates a new folder and starts copying all files.

Exptected behaviour: 
don't copy files again, just rename the folder on second computer.

[Screenshot](https://ibb.co/DDdYmRH)

Version: v1.22.0, Windows (64-bit Intel/AMD)
OS: Windows 10
Browser: Chrome

**Comment by calmh** [comment]
This is unfortunately as intended, files are handling individually and there is no smarts to detect an entire tree move. Depending on the amount of files and timing you may see files being either copied-then-deleted or moved.

**Comment by azatsh** [comment]
So as a workaround I think we can 
1. Stop syncing 
2. Rename folder on both computers manually
3. Start syncing

This should save time and don't force Syncthing to download all files again. 
Am I right ?

**Comment by acolomb** [comment]
In fact it won't download the contents again over the network. As long as the same data blocks are available locally in any shared folder, Syncthing will copy from there, before deleting the original. What's transmitted over the net should be only metadata.

**Comment by azatsh** [comment]
> In fact it won't download the contents again over the network. As long as the same data blocks are available locally in any shared folder, Syncthing will copy from there, before deleting the original. What's transmitted over the net should be only metadata.
> 
> And yes, your proposed workaround should do the trick.

How can I prove for myself that it does not download but just copies ? It already took a whole day and still only half of the files have been copied/moved. Looks like it does download.
