### ISSUE TITLE
Ability to filter/query relay pools.

### ISSUE THREAD

**Issue by charlesomer** [syncthing/syncthing#8876]
At the moment it's possible to set specific relays via "Sync Protocol Listen Addresses", but it does not appear possible yet to filter relays based on certain requirements. For example, only those in a particular region/country and above a certain bandwidth.

Perhaps something like this:
`tcp://0.0.0.0:22000, quic://0.0.0.0:22000, dynamic+https://relays.syncthing.net/endpoint?location.country=gb`

It's possible to query `relays.syncthing.net/endpoint` to get the data and filter via a script manually but this won't keep updated when the data changes.

**Comment by pataquets** [comment]
+1 for `protocol=quic`, if possible now or in the future

**Comment by AudriusButkevicius** [comment]
Quic is not a protocol that is relayed, and it shouldn't need to be relayed.
Relay choice is based on latency, which is a good enough measure.

If you want something else, write your own script that updates your config etc.

From my perspective, close as won't fix, as I don't think we want to do that.

**Comment by calmh** [comment]
I don't think we want to do this, either, sorry.
