### ISSUE TITLE
cannot patch folder device list

### ISSUE THREAD

**Issue by phemmer** [syncthing/syncthing#8886]
### Does your log mention database corruption?

no

### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using
 1.23.4
 - browser and version, if applicable
 N/A
 - what happened,
 performing a PATCH request on `/rest/folders/foo` containing single device, and all other devices were removed
 - what you expected to happen instead, and
 expected to see that device added to the devices list
 - any steps to reproduce the problem.
`curl -H 'Content-Type: application/json' -H "X-API-Key: foo" http://localhost:8384/rest/config/folders/myfolder -X PATCH -d '{"devices":[{"deviceID":"a-b-c-d-e-f-g-h"}]}'`

This may not strictly be a bug, as [the documentation](https://docs.syncthing.net/rest/config.html#rest-config-folders-id-rest-config-devices-id) is ambiguous on this point:
> PATCH replaces only the given child objects

It could be interpreted as replacing all the top-level elements of the object (the observed behavior), and not the nested objects (expected behavior).

However if this is not a bug, then this issue should be a feature request to add such support. This is problematic when adding multiple devices to a folder, as to do so you have to fetch the folder config, add the device to the list, and then write the new folder config. If this happens concurrently, one operation may overwrite the other.  
Alternatively a check-and-set would also work. Something that returns either a config version number, or config hash as a header when reading, and then if provided during a write operation, and the value does not match, an error is returned and the caller has to start over and fetch a new config.

**Comment by imsodin** [comment]
That's working as intended, and I think the docs are also clear: The object is the thing the path refers to, here the entire config of `myfolder`, the child object you are changing is `devices`, i.e. the entire list.

The entire config api is definitely not safe or well suited to handle concurrency, that goes beyond this issue. Even if we add handlers for `config/folders/<folderid>/devices` to add a new device by `POST`, you can still have config modification races. That's currently needs to be handled entirely by whatever uses the API.

Anyway I can see the utility of being able to add a device without first getting the list of devices, so I think a feature request for handlers on `config/folders/<folderid>/devices` (probably only POST to add a device, maybe GET just in case) makes sense to me.

**Comment by phemmer** [comment]
What about a more generic solution such as check-and-set (or optimistic locking, whatever you want to call it)? From a brief glance at the code, the `Configuration` type already has a `version` field. A middleware can be added on the http handler that returns that version as a header on all requests. Then on put/post/patch requests, the client can optionally provided the version header, and if it is provided but doesn't match current config version, then the middleware will reject the request.

This would solve all concurrency issues, and not require syncthing to provide explicit patch support for every possible scenario (including deleting items, which is another concern of mine, but a lesser one).

**Comment by imsodin** [comment]
The version in `Configuration` is about the config format, not the content. Still, such a mechnism could be added I guess - probably shouldn't live in the config itself. The mechanism itself seems reasonable, but also a bit of work given how widely used this part of the code is.

**Comment by phemmer** [comment]
Ah, ok. Yeah didn't dig too deeply. I was thinking that was part of the mechanism which is used for adding the `.v00` suffix to the config.xml every time its changed.
