### ISSUE TITLE
Do not autoexpand tilde sign (~) to an absolute home directory path

### ISSUE THREAD

**Issue by ZoomRmc** [syncthing/syncthing#8890]
I'm using Syncthing in a dualboot environment, sharing the same keys/config between operating systems. Everything works great. Paths to the shared directories are unified through symlinking in the home directory. However, the GUI doesn't allow entering the tilde `~` on adding folders, autoexpanding it to absolute form, thus requiring manual config editing. If entered manually, the tilde persists and creates no issues with Syncthing.

At some moment my config was changed (may be after some upgrade?) and the path was expanded to the absolute form on Windows, leading to silent creation of the directory on GNU/Linux and redownloading of the contents. I didn't notice it right away so was a bit annoyed.

It would be nice if the GUI didn't have this behaviour and left the `~` untouched.

**Comment by acolomb** [comment]
It sounds strange that your Windows instance created the folder, if you shared the config and database between OSes. In that case, it should have noticed the folder marker missing and stopped the folder with an appropriate error message. So at least that shouldn't pose an immediate problem, but the other arguments still make a valid case for this enhancement.

**Comment by ZoomRmc** [comment]
> It sounds strange that your Windows instance created the folder, if you shared the config and database between OSes. In that case, it should have noticed the folder marker missing and stopped the folder with an appropriate error message. So at least that shouldn't pose an immediate problem, but the other arguments still make a valid case for this enhancement.

That's not exactly what happened. I suspect the path in the config was somehow changed while running Windows, and then Syncthing on GNU/Linux happily created a folder with a Windows absolute path for the name.
