### ISSUE TITLE
Uncontrollable memory usage (very high memory usage)

### ISSUE THREAD

**Issue by hohmd** [syncthing/syncthing#8891]
Version: [syncthing-linux-arm-v1.23.4.tar.gz](https://github.com/syncthing/syncthing/releases/download/v1.23.4/syncthing-linux-arm-v1.23.4.tar.gz)
Run as root user (to prevent any limits for testing purposes).

```php
        <copiers>1</copiers>
        <hashers>1</hashers>
        <disableSparseFiles>true</disableSparseFiles>
        <disableTempIndexes>true</disableTempIndexes>
	<disableFsync>true</disableFsync>
        <setLowPriority>false</setLowPriority>
        <maxFolderConcurrency>1</maxFolderConcurrency>
        <databaseTuning>small</databaseTuning>
```

Command line options:
gomemlimit 4 MiB, max processes 1.
```php
GOMEMLIMIT=4194304 GOMAXPROCS=1
```

This option unused (not clear how to set properly):
```php
        <maxConcurrentIncomingRequestKiB>0</maxConcurrentIncomingRequestKiB>
```

Hello. I am in need to use Syncthing on very low end machine. 1 cpu core, 1 GB ram, armv7 (x86). It has 6 TB of data to sync.

Above there are options i use but still Syncthing is using more than 2048 MB of ram. It grows forever until OOM takes an action. It uses RAM and SWAP.

Please suggest how can i hard cap Syncthing memory usage? What else can i use?

**Comment by calmh** [comment]
There is no way to set a hard limit. The queue of things to sync is built in memory, sorted etc, and then worked from.

> need to use Syncthing on very low end machine
> 6 TB of data to sync.

This may be two incompatible requirements. You may be able to work around it by splitting it up into smaller folders and not adding all of them at the same time. Sorry.

**Comment by acolomb** [comment]
That is actually what your operating system does. It's called swapping.

Please continue this discussion on the forum, first by searching for similar topics and if required, posting a new topic. The forum had a lot more eyes and friendly people on it than the issue tracker.
