### ISSUE TITLE
PullerMaxQueueLength implementation question

### ISSUE THREAD

**Issue by hohmd** [syncthing/syncthing#8892]
Is PullerMaxQueueLength planned to be included somehow in future releases?

https://github.com/calmh/syncthing/commit/82c5fc008ce82a02b5d5ad1bab124d4648dca724

**Comment by calmh** [comment]
No, no such plans. I wrote some stuff; apparently, it wasn't great, but I don't remember why: https://github.com/syncthing/syncthing/pull/4978

I'm closing this as it's a "question" and we don't really have those in the issue tracker. You maybe want to follow/subscribe to #4976
