### ISSUE TITLE
API /rest/events with "events" filter returns nothing and times out

### ISSUE THREAD

**Issue by phemmer** [syncthing/syncthing#8902]
### Does your log mention database corruption?

If your Syncthing log reports panics because of database corruption it is
most likely a fault with your system's storage or memory. Affected log
entries will contain lines starting with `panic: leveldb`. You will need to
delete the index database to clear this, by running `syncthing
-reset-database`.

### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using
   syncthing v1.23.4 "Fermium Flea" (go1.20.2 linux-amd64) deb@build.syncthing.net 2023-04-05 13:25:55 UTC [noupgrade]

 - browser and version, if applicable
   N/A

 - what happened,
   when calling `/rest/events?events=foo` I receive nothing, and the request eventually times out.

 - what you expected to happen instead, and
   I expected to receive "foo" events.

 - any steps to reproduce the problem.
```
# curl -H "X-API-Key: mykey" http://localhost:8384/rest/events?limit=1
[
  {
    "id": 785,
    "globalID": 1305,
    "time": "2023-05-12T02:44:49.851174247Z",
    "type": "RemoteDownloadProgress",
    "data": {
      "device": "A-B-C-D-E-F-G-H",
      "folder": "my_folder",
      "state": {}
    }
  }
]

# curl -v -H "X-API-Key: mykey" "http://localhost:8384/rest/events?limit=1&events=RemoteDownloadProgress"
*   Trying 127.0.0.1:8384...
* Connected to localhost (127.0.0.1) port 8384 (#0)
> GET /rest/events?limit=1&events=RemoteDownloadProgress HTTP/1.1
> Host: localhost:8384
> User-Agent: curl/7.74.0
> Accept: */*
> X-API-Key: mykey
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Cache-Control: max-age=0, no-cache, no-store
< Content-Type: application/json; charset=utf-8
< Expires: Fri, 12 May 2023 02:47:05 GMT
< Pragma: no-cache
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-Syncthing-Id: I-J-K-L-M-N-O-P
< X-Syncthing-Version: v1.23.4
< X-Xss-Protection: 1; mode=block
< Date: Fri, 12 May 2023 02:47:05 GMT
< Transfer-Encoding: chunked
< 
[]
```

It does not seem to matter whether "limit" is present or not, whether "since" is present, or whether it's one event or many. As soon as the "events" parameter is specified, it breaks.

**Comment by calmh** [comment]
This is as expected, though perhaps it could be more clear in the docs. Specifying a set of events creates a new subscription for that type of event the first time you ask for it. You will get that type of event from that point onwards, but not any of the historical events that might have happened in the past. In your case it's waiting for the default timeout period of 60s for a new `RemoteDownloadProgress` event, and since there apparently isn't one it returns the empty list after a minute, at which point you do a new event poll.

I'd be happy to see suggestions for improving [the docs](https://docs.syncthing.net/rest/events-get.html), or explaining the mechanics further on [the forum](https://forum.syncthing.net/).

**Comment by phemmer** [comment]
That does not seem to be true. And if it were, I can't see how the functionality could be effectively used. If the point is as you say for filtering new events, then that would indicate its for streaming. However to be able to effectively stream, you have to request all events since the last received event, which means you have to be able to retrieve any potential events which have already occurred. Otherwise you'll have gaps, and won't even know it.

But as I mentioned, the stated behavior does not seem to be how it actually behaves. I just tested again, with the exact same request, on the exact same host, with the exact same running process (has not been restarted) and it's now all of a sudden working.

```
# curl -v -H "X-API-Key: mykey" "http://localhost:8384/rest/events?limit=1&events=RemoteDownloadProgress"
*   Trying ::1:8384...
* connect to ::1 port 8384 failed: Connection refused
*   Trying 127.0.0.1:8384...
* Connected to localhost (127.0.0.1) port 8384 (#0)
> GET /rest/events?limit=1&events=RemoteDownloadProgress HTTP/1.1
> Host: localhost:8384
> User-Agent: curl/7.74.0
> Accept: */*
> X-API-Key: mykey
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Cache-Control: max-age=0, no-cache, no-store
< Content-Type: application/json; charset=utf-8
< Expires: Fri, 12 May 2023 12:20:54 GMT
< Pragma: no-cache
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-Syncthing-Id: I-J-K-L-M-N-O-P
< X-Syncthing-Version: v1.23.4
< X-Xss-Protection: 1; mode=block
< Date: Fri, 12 May 2023 12:20:54 GMT
< Transfer-Encoding: chunked
< 
[
  {
    "id": 3,
    "globalID": 1321,
    "time": "2023-05-12T03:07:50.423785989Z",
    "type": "RemoteDownloadProgress",
    "data": {
      "device": "A-B-C-D-E-F-G-H",
      "folder": "my_folder",
      "state": {}
    }
  }
]
```

**Comment by calmh** [comment]
Yes, because now there has been such an event, since you did the first call with that event filter and got the subscription. I'm happy to discuss this further, but on the forum -- we don't do general support chat here.

**Comment by phemmer** [comment]
> Yes, because now there has been such an event

Please see the original issue report, there was such an event. I included it specifically for that reason:

```
# curl -H "X-API-Key: mykey" http://localhost:8384/rest/events?limit=1
[
  {
    "id": 785,
    "globalID": 1305,
    "time": "2023-05-12T02:44:49.851174247Z",
    "type": "RemoteDownloadProgress",
    "data": {
      "device": "A-B-C-D-E-F-G-H",
      "folder": "my_folder",
      "state": {}
    }
  }
]

# curl -v -H "X-API-Key: mykey" "http://localhost:8384/rest/events?limit=1&events=RemoteDownloadProgress"
*   Trying 127.0.0.1:8384...
* Connected to localhost (127.0.0.1) port 8384 (#0)
> GET /rest/events?limit=1&events=RemoteDownloadProgress HTTP/1.1
> Host: localhost:8384
> User-Agent: curl/7.74.0
> Accept: */*
> X-API-Key: mykey
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Cache-Control: max-age=0, no-cache, no-store
< Content-Type: application/json; charset=utf-8
< Expires: Fri, 12 May 2023 02:47:05 GMT
< Pragma: no-cache
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-Syncthing-Id: I-J-K-L-M-N-O-P
< X-Syncthing-Version: v1.23.4
< X-Xss-Protection: 1; mode=block
< Date: Fri, 12 May 2023 02:47:05 GMT
< Transfer-Encoding: chunked
< 
[]
```

**Comment by calmh** [comment]
> now there has been such an event, **since you did the first call with that event filter**

Now, for the third time, less politely: this is a forum discussion. It will not continue here.
