### ISSUE TITLE
Sync malfunctions when re-adding folder if peer is Receive Only

### ISSUE THREAD

**Issue by vibs29** [syncthing/syncthing#8908]
Syncthing v1.19.2-ds1, Linux (64-bit Intel/AMD)

Two devices: Alice and Bob

The expectation listed at the following parameterised experiment's end is met if parameter `<T>` is "Send & Receive" but not if it is "Receive Only" or "Receive Encrypted".

Terminology: I'll use "directory" to mean the Linux directory and "folder" to mean the Syncthing object that is backed by a Linux directory.
```
Experiment(<T>):

Initial state: Alice and Bob know of zero remote devices and zero folders.
Alice and Bob add each other.
Bob creates a folder with ID f1 of type <T>, path ~/f1, sharing it with Alice.
Alice accepts and adds the folder in mode "Send & Receive".
After they have synced, Alice removes the folder and directory.
Alice adds a new folder with ID f1, type "Send & Receive", sharing it with Bob.
Once sync with Bob completes, Alice adds a new file y into f1.
Expectation: Bob's ~/f1 will get a plain or ciphertext file corresponding to y.
```

**Comment by calmh** [comment]
I ran through this "parameterised experiment" and cannot reproduce the issue.
