### ISSUE TITLE
Syncthing won't sync new shared folder

### ISSUE THREAD

**Issue by montanaviking** [syncthing/syncthing#8909]
syncthing v1.18.0-ds1, Linux (64-bit Intel/AMD)
Syncthing will not sync newly-shared folder.
Running on Ubuntu Linux versions 18.04 and 22.04 in firefox
Actions:
had to remove old folder due to syncing problems. 
share folder from machine A to B. Machine B accepts A's request to share.
empty folder recreated on B by Syncthing. New folder is completely empty
Syncthing will not sync new folder and reports error 
older marker missing (this indicates potential data loss, search docs/forum to get information about how to proceed)
Thanks,
Phil

**Comment by montanaviking** [comment]
Also, I've had issues that Syncthing won't sync existing folders between machines. In this case, Syncthing reports the folders as synced but checking the folder directories on each machine shows them out of sync, e.g. old file versions and new files not being transferred.
Unless I can find a reliable work-around this is a deal-breaker and I'll just go back to using nfs and mount the drives without syncing. Attempting to remove and re-install the synced folders on Syncthing lead to my earlier bug report. Sometimes I can get folders to sync and sometimes not.

**Comment by acolomb** [comment]
We'll need more information (e.g. screenshots of the Web GUI on both sides) to diagnose this.

This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
