### ISSUE TITLE
path exists, but folder marker missing, check for mount issues

### ISSUE THREAD

**Issue by MrClayPole** [syncthing/syncthing#891]
I have 4 folders shared from my file system that are not nested. 3 of the are on a read only file system and I get the errors below.

13:56:06 WARNING: Stopping folder "Share1" - path exists, but folder marker missing, check for mount issues
 13:56:06 WARNING: Stopping folder "Share2" - path exists, but folder marker missing, check for mount issues
[4XMC7] 13:56:06 WARNING: Stopping folder "Share3" - path exists, but folder marker missing, check for mount issues

The 4th is read write and there are no issues sharing the folder. All 4 shares worked with this configuration up to version v0.10.1 but as soon as I updated to v0.10.2 I get the errors above.

**Comment by JujuLand** [comment]
Hi,

I have similar problem :

2016-06-15 16:15:43: Stopping folder "cv2d3-pzjRv" - folder marker missing

I hay two computers, ordi1 with user1 and ordi2 with user2 and user3
user1 share folder1 with user2 and user3

When I put it in place, I first work with user1
Then I work with user2, and synchronize between user1 and user2 => ok (now user1 has folder1 and folder2
I disconnect user2, and connect user3
I work with user3 and synchronize between user1 and user3 => it beguns, but stop at 94%, and I have this message.
The message appears about a subfolder originally in folder2 of user2

Obviously, .stfolder exists in folder1 of user1

If you have an idea about my problem.

Thanks
A+

**Comment by ShawnMilo** [comment]
@JujuLand Do you have any scripts that automatically delete zero-byte files on one of your machines? That's what happened to me.

Also, as I mentioned above you could write a script that logs whether it sees the file and run it in a loop (or every minute), then see if you can use the knowledge of when in disappeared to backtrack to what event actually causes it.

**Comment by canton7** [comment]
Please don't comment on ancient issues: open a new issue.

I'm going to lock this issue now, so please copy your message into a new issue.

**Comment by AudriusButkevicius** [comment]
Or to be honest, use the forums.
