### ISSUE TITLE
Out of Sync after editing a file.

### ISSUE THREAD

**Issue by TheSloPro** [syncthing/syncthing#8910]
### Does your log mention database corruption?
No.
### Include required information

Version: Syncthing 1.23.4 Windows with SyncTrayzor

**What happened:**
I have set up sync with android phone and pc (windows, synctrayzor), so everything i have on my phone, gets backed up on pc. But when I edit a file (image) on my phone it wont sync it to pc, it just says out of sync and Access Denied. I figured out that if I delete the original on pc, it will be replaced by the edited copy, but when editing 100s of files I can't go through each and one of them on pc to delete them.

**What I expected to happen:**
The original gets replaced by the edited file.

**How to reproduce:**
1. set up syncthing on android with pc (send only, receive only)
2. wait for everything to sync - it should show Up to Date(DCIM folder in my case)
3. edit a file (image) on android
4. look at the pc and see red Out of Sync text

I already tried multiple settings (ignore permissions ...), with no success.

**Comment by TheSloPro** [comment]
This is one example from logs:
`[VFU33] 2023/05/19 10:08:06 INFO: Puller (folder "Galaxy S23+ DCIM" (dqcws-temku), item "Camera\\20230509_174018_test_s23.jpg"): syncing: finishing: setting metadata: Access is denied.
[VFU33] 2023/05/19 10:08:06 INFO: Puller (folder "Galaxy S23+ DCIM" (dqcws-temku), item "Camera\\20230509_174059_test_s23.jpg"): syncing: finishing: setting metadata: Access is denied.
[VFU33] 2023/05/19 10:08:06 INFO: Puller (folder "Galaxy S23+ DCIM" (dqcws-temku), item "Camera\\20230509_174151_test_s23.jpg"): syncing: finishing: setting metadata: Access is denied.
[VFU33] 2023/05/19 10:08:06 INFO: Puller (folder "Galaxy S23+ DCIM" (dqcws-temku), item "Camera\\20230509_174402_test_s23.jpg"): syncing: finishing: setting metadata: Access is denied.
[VFU33] 2023/05/19 10:08:06 INFO: Puller (folder "Galaxy S23+ DCIM" (dqcws-temku), item "Camera\\20230428_101834_javasabr_lmc16_s23_v6_sharp.jpg"): syncing: finishing: setting metadata: Access is denied.
[VFU33] 2023/05/19 10:08:06 INFO: "Galaxy S23+ DCIM" (dqcws-temku): Failed to sync 5 items
[VFU33] 2023/05/19 10:08:06 INFO: Folder "Galaxy S23+ DCIM" (dqcws-temku) isn't making sync progress - retrying in 8m0s.`

It copies the file but it gets stuck at metadata as the file is edited. If I change the file extension from .tmp to .jpg the whole image is there only no metadata...

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
