### ISSUE TITLE
Sync speed at 0B/s

### ISSUE THREAD

**Issue by elektrinis** [syncthing/syncthing#8911]
### Does your log mention database corruption?

no

### Include required information

Three devices on same LAN: 2 laptops and one android.
Mixed status being reported: device says it's at 53%, folder says it's at 100%.
I am noticing things like this very often. What's going on?

![syncthing](https://github.com/syncthing/syncthing/assets/15337792/a3eb2030-d05d-4a7f-a221-479b08bbcb1b)

**Comment by acolomb** [comment]
Questions like these belong on the forum please.

Your remote device hasn't accepted the share offer for one of the folders, that's why it's not progressing. Look at the small superscript 1 mark under shared folders for that device.
