### ISSUE TITLE
Ignore Symlinks?

### ISSUE THREAD

**Issue by DocMAX** [syncthing/syncthing#8912]
Is there a way to ignore symlinks for a specific path? Something like:

`(?s)/my/path`

would be great, meaning (?s) for symlinks only

**Comment by acolomb** [comment]
No, there currently isn't. There have been several similar feature requesta, to ignore files based on timestamp, size, etc. The common problem to all these is how to treat conflicts, e.g. if one device replaces the symlink with a regular file, does it get synced to their one which ignores symlinks?

Maybe if you can outline why exactly you need this and why there is no alternative, we could turn this into a feature request, although I doubt it will get implemented soon.

Please continue the conversation on the forum though, this is not the right venue to discuss potential features.

**Comment by ilil812** [comment]
Ignoring Files .stignore

*-|*

At the end of each link name: -|
