### ISSUE TITLE
potential leak in utils.go

### ISSUE THREAD

**Issue by hhheiaenia** [syncthing/syncthing#8917]
I notice the ctx.Done() needs a cancel function to unblock the statement of ctx.Done in https://github.com/syncthing/syncthing/blob/main/lib/util/utils.go#LL243C20-L243C20 , since the case may block forever if the case not met.
  I was wondering if this may leak the goroutine where the ctx.Done() locates?

Maybe what I said is not right, thank you for taking a look.

**Comment by calmh** [comment]
Looks to me that this is intended to be called with a context that has a deadline. I don't see a problem.
