### ISSUE TITLE
Out of Sync Items : .DS_Store

### ISSUE THREAD

**Issue by eromoe** [syncthing/syncthing#8927]
I am syncing between windows and mac,  this appear on windows side. 
Such files are just placeholder on mac, I don't understand why this error happen on windows.

![image](https://github.com/syncthing/syncthing/assets/3938751/87ae0638-f442-44b4-a5da-d0bc254c6850)

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
