### ISSUE TITLE
GPG signatures missing from 1.23.5

### ISSUE THREAD

**Issue by alerque** [syncthing/syncthing#8929]
Arch Linux packager here. I went to bump our packages to the latest version, but they are missing GPG signatures that have been standard on past releases. The 1.23.5 release has 38 asset files, most leading up to it have had 41, and notably the expected `syncthing-source-v1.23.5.tar.gz.asc` is missing.

**Comment by calmh** [comment]
Yeah that's #8897, sorry about that.

**Comment by calmh** [comment]
@alerque I'll generate them manually and upload shortly

**Comment by calmh** [comment]
@alerque there.
