### ISSUE TITLE
quic-go v0.36.0

### ISSUE THREAD

**Issue by bt90** [syncthing/syncthing#8930]
This requires some migrations as quic-go changed it's connection API in the v0.35.0 release: https://github.com/quic-go/quic-go/issues/3727

Edit: they published v0.36.0 which introduces GSO support. We need to call the new `OptimizeConn` function otherwise this will break our STUN implementation.

https://github.com/quic-go/quic-go/releases/tag/v0.36.0

**Comment by bt90** [comment]
> Users who are using the same net.PacketConn for QUIC and to send out non-QUIC packets now need to call the newly introduced OptimizeConn function before passing the connection to the Transport.

**Comment by bt90** [comment]
But we should wait for https://github.com/quic-go/quic-go/issues/3911 to get fixed.

**Comment by calmh** [comment]
Yes sending is not the issue

**Comment by bt90** [comment]
https://github.com/quic-go/quic-go/issues/3929

**Comment by yan12125** [comment]
Any news on this? [quic-go 0.37.0](https://github.com/quic-go/quic-go/releases/tag/v0.37.0) will be required for upcoming Go 1.21. New quic-go also drops support for Go < 1.20, though.

**Comment by imsodin** [comment]
Generally if there's no updates on a ticket or associated PRs, then there's no news: https://github.com/syncthing/syncthing/wiki/NoPlusOne

In this case there is some news on quic-go's side - if your interested in this follow the issue linked just above by qt90.

**Comment by bt90** [comment]
I think we're also waiting for https://github.com/quic-go/quic-go/pull/3992 in order to retire pfilter.

**Comment by yan12125** [comment]
Thank you for the information and sorry for the noise. I looked into relevant quic-go issues. One of them may be no longer an issue for Syncthing.

> But we should wait for https://github.com/quic-go/quic-go/issues/3911 to get fixed.

GSO is disabled by default in quic-go 0.37.0 (https://github.com/quic-go/quic-go/pull/3934)

**Comment by bt90** [comment]
Fixed by #9040
