### ISSUE TITLE
Suddenly my Windows PC cannot see my Android device

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [syncthing/syncthing#8932]
### Does your log mention database corruption?

No.

### Include required information

**Windows PC** : Windows 10; Syncthing _v1.23.5_; Windows (64-bit Intel/AMD); Firefox ESR 114.0
**Android phone**: Android 13;_v.23.4_ (newer version has not appeared via the Play Store), Android (64-bit ARM)

As of today - or at least it was today that I noticed the problem - my Windows PC cannot see my Android phone, and vice-versa. I have a Linux laptop that (Syncthing-wise) sees both the Windows PC and the phone. Things I tried to no avail:

1) disabling my Windows PC's firewall and VPN;
2) deleting the Windows device on the Android device, and recreating the former;
3) delete the Android device on the Windows PC, and recreating the former.

Except, ah: _now_ - some ten minutes after 1 and 2 - the Windows PC and the phone _do_ see each other. But, now, there seem to be some items that are stuck out-of-sync between the devices. I tried the 'override' option but files newly on the phone did not reach the PC. And - _even more recently_ - I find that the Windows PC says, of the phone, this: 'no recent network activity'; and, now, on the phone, the Windows device shows as disconnected.

I attach the Windows log, as it was when I first had problems. On Android, I managed to see the log but I don't know how to save it.
[Log_from_Windows_PC.txt](https://github.com/syncthing/syncthing/files/11698004/Log_from_Windows_PC.txt)

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
