### ISSUE TITLE
apt.syncthing.net inaccessible via current Internet Protocol a.k.a. IPv6

### ISSUE THREAD

**Issue by UnderEu** [syncthing/syncthing#8934]
### Does your log mention database corruption?
No

### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using
1.23.5 (apt.syncthing.net)
Ubuntu MATE 22.04.2

 - browser and version, if applicable
N/A

 - what happened
While trying to update my system packages in an IPv6-only connection, the connection to apt.syncthing.net fails because the server becomes unreachable

 - what you expected to happen instead
Packages list updates normally

 - any steps to reproduce the problem

```
$ dig AAAA apt.syncthing.net

; <<>> DiG 9.18.12-0ubuntu0.22.04.1-Ubuntu <<>> @2606:4700:4700::1111 AAAA apt.syncthing.net
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10136
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;apt.syncthing.net.		IN	AAAA

;; ANSWER SECTION:
apt.syncthing.net.	65	IN	CNAME	ams3-k8s.syncthing.net.

;; AUTHORITY SECTION:
syncthing.net.		557	IN	SOA	ns1.digitalocean.com. hostmaster.syncthing.net. 1685548811 10800 3600 604800 1800

;; Query time: 13 msec
;; SERVER: 2606:4700:4700::1111#53(2606:4700:4700::1111) (UDP)
;; WHEN: Sat Jun 10 22:10:22 -03 2023
;; MSG SIZE  rcvd: 136

$ sudo apt update
[...]
Ign:7 https://apt.syncthing.net syncthing InRelease
[...]
Err:7 https://apt.syncthing.net syncthing InRelease
  Could not resolve 'apt.syncthing.net'
[...]
```

**Comment by calmh** [comment]
Unfortunately, the services in front don't support it. 

https://docs.digitalocean.com/products/networking/ipv6/details/limits/#:~:text=Load%20balancers%2C%20Reserved%20IPs%2C%20and,to%20(like%20a%20Droplet).
