### ISSUE TITLE
Doesn’t sync files which names contain `:`

### ISSUE THREAD

**Issue by es20490446e** [syncthing/syncthing#8945]
Syncthing is unable to sync files if their names contain `:`

Which is what is happening to me while building Arch Linux packages that contains not only `pkgver` but `epoch`, for example:

`c++utilities-100:5.23.0-4-x86_64.pkg.tar.zst`

**Comment by es20490446e** [comment]
https://forum.syncthing.net/t/doesnt-sync-files-which-names-contain/20409

**Comment by bt90** [comment]
This is a filesystem restriction on the receiver as already pointed out by one of our forum users. There's nothing we can do about that.

**Comment by rasa** [comment]
See https://github.com/syncthing/syncthing/pull/7876 for a relevant PR.
