### ISSUE TITLE
System stalls when copying large files (8GB+) to my samba share

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [syncthing/syncthing#8947]
## Description

I am using Syncthing to synchronize files between my NAS, Desktop and Smartphone and this in itself works fine, but there is an weird issue on my desktop.

When I copy a large file from a smb share on my NAS to my desktop, everything is fine. But when I copy the file back to the smb share in a different folder, the desktop completely stalls (Desktop clock stops, mouse cursor cannot be moved) till the copy operation finished. This only happens with smb shares, nfs shares are unaffected. Another interesting thing is, that this behaviour is not triggered, when the smb share is mounted graphically via the file manager, but when using the fstab or an systemd mount (I use such a mount).

All syncthing folders are located on the device directly, so they are not on any network storage device and should not interfere in any way.

I am sure this is caused by syncthing as removing the config folder and/or disabling syncthing fixes the issue. Syncthing without configured folders does not trigger the issue.

I already created a bugreport at the redhat bugzilla some time ago suspecting an issue with samba, but this seems not to be a samba issue: https://bugzilla.redhat.com/show_bug.cgi?id=2165393

## Does your log mention database corruption?

No, it does not.

## Steps to Reproduce

1. Create a systemd mount like the one provided in the attached mnt-Nas.mount file (Remove the .txt file ending when using, github forces known file endings). [mnt-Nas.mount.txt](https://github.com/syncthing/syncthing/files/11859431/mnt-Nas.mount.txt)
2. Start the mount unit to mount the smb share.
3. Open a graphical file manager like nautilus.
4. Select a file on the share that has at least 8GB in size and was not used/referenced/copied already in the current session. If it was, reboot the system if the specific file should be used.
5. Copy this file from the smb share to an location on the desktop accessible to the user.
6. Copy this file now to a different location on the NAS. It should be a location where this file never was before.
7. Wait while the file gets copied.
8. Often, after 4-6GB being copied, the desktop will freeze till the copy operation is finished.

## Expected Result

The desktop should not freeze when a large file is copied to an smb share.

## Observed Result

The desktop freezes when a large file is copied to an smb share.

### Desktop PC

OS: Fedora 38
Desktop: Gnome 44.2
File Manager: Nautilus
Syncthing Version: 1.23.5
Browser: Firefox 114.0.2
Network Card: Chelsio T540 LP-CR

### NAS

OS: Openmediavault 6.4.5 (based on Debian 11)
Syncthing Version: 1.23.5 (Docker Container)
Network Card: Asus XG-C100F

### Smartphone

Device: Realme 6
OS: Android 11
Syncthing Version: 1.23.5 (App)
Network Connection: Wifi

**Comment by bt90** [comment]
> Often, after 4-6GB being copied, the desktop will freeze till the copy operation is finished

You're most likely hitting the `vm.dirty_background_ratio` or `vm.dirty_background_bytes` limits which forces the copy operation to block until the file is fully copied. The filemanager is probably circumventing this via userland.

I don't see how syncthing is involved here. Anyway, let's continue this in our forum as this is not the place for support topics:

https://forum.syncthing.net/

**Comment by Sebastian-Hirsch** [comment]
Then why are nfs shares not affected? They use the same dirty_background settings. But I can try the dirty_background settings.

**Comment by Sebastian-Hirsch** [comment]
I created a forum post:

https://forum.syncthing.net/t/system-stalls-when-copying-large-files-8gb-to-my-samba-share/20426
