### ISSUE TITLE
relaysrv and discosrv docker images haven't been updated for more than year

### ISSUE THREAD

**Issue by claudio4** [syncthing/syncthing#8960]
Both the Image for [relaysrv](https://hub.docker.com/r/syncthing/relaysrv) and the image for [discosrv](https://hub.docker.com/r/syncthing/discosrv) haven't been updated since version 1.18.6. Needless to say this isn't great for those who search a fully selfhosted Syncthing experience with the ease-of-use of Docker.

**Comment by calmh** [comment]
I've added build automation for this, there are now updated `:edge` images and on next release there will be updated `:latest`, `:1`, `:1.22` etc images.
