### ISSUE TITLE
One cause of Error modal displaying when events?since=lastID appears to timeout

### ISSUE THREAD

**Issue by johnmccabe** [syncthing/syncthing#8961]
Raising for visibility as a few others had reported the same/similar problem but I'd not see a conclusion in GitHub or the Forums.

### Does your log mention database corruption?

No

#### Version

v1.23.5, Linux (64-bit Intel/AMD Container)
"Fermium Flea"
Build 2023-06-06 (noupgrade)
Image: syncthing/syncthing@sha256:cb0a20d011488fd7d8c971708942889f767aecc7d0f5536ee0558cbd1008b0a9 (1.23.5 tag)

#### Browser

Firefox - 114.0.2 (64-bit) on Windows 11
Chrome - Version 114.0.5735.199 (Official Build) (64-bit) on Windows 11

#### Observed Behaviour

I had been seeing a "Connection Error" modal flash up when a call to `/events?since=<lastID>` would timeout

#### Apparent cause/fix

Looks like the problem had been on my side, I've been accessing the UI via a reverse proxy (on a Synology NAS) which had its default timeouts set to 60seconds, upping the timeout in the reverse proxy resolved the issue for me. I now get a 200 for all `/events` calls.

For example setting the following via the Synology DSM Login Portal/Advanced/Reverse Proxy

![image](https://github.com/syncthing/syncthing/assets/83862/1d51bb38-392c-451b-8b80-802e581179e1)

**Comment by calmh** [comment]
I don't see the bug here. That call is supposed to return 200, sometimes after a while. If something in between causes an HTTP error that is a connection problem and will be reported. The GUI assumes it's talking to syncthing, where an HTTP error on that endpoint would indicate a serious problem.

**Comment by johnmccabe** [comment]
@calmh its not a bug, just raised it so anyone else hitting the issue with a similar proxied setup would see the suggestion to up their timeouts. Closing.
