### ISSUE TITLE
Disable flag of  Syncthing admin interface password

### ISSUE THREAD

**Issue by finalparanoia** [syncthing/syncthing#8962]
### Include required information

Please be sure to include at least:

 - what problem your new feature would solve
 - how or why you think it is generally useful (i.e., not just for you)
 - what alternatives or workarounds you considered

how about allow user disable the warning of don't setting passwd.

it's usefule for the user who deployed reverse proxy authentication for sso.

**Comment by spantaleev** [comment]
Duplicate of https://github.com/syncthing/syncthing/issues/8841
