### ISSUE TITLE
Shared With list ends with comma on 1 device

### ISSUE THREAD

**Issue by luckman212** [syncthing/syncthing#8967]
## Versions

- Syncthing v1.23.6, macOS (64-bit ARM)
- Chrome 114.0.5735.198
 
## 2 old possibly related issues:

- https://github.com/syncthing/syncthing/issues/2626
- https://github.com/syncthing/syncthing/issues/362

I don't think this necessarily _began_ with 1.23.6 but I happened to notice it this morning when I upgraded my 2 systems. The "Shared With" line on my main computer has the name of the other Mac, but ends with a lone comma:

<img width="570" alt="screenshot_gEuS0Fdx_gh" src="https://github.com/syncthing/syncthing/assets/1992842/65577ed9-2048-41b8-97fa-16aaf562f21e">

I checked the config.xml and nothing jumped out at me as being incorrect / duplicate etc. I even diff'ed it against the other peer, and aside from the machine IDs, they are identical. Strangely, the other machine does not display this comma. Could it have to do with the hyphen in the computer name?

**Comment by tomasz1986** [comment]
This is probably caused by https://github.com/syncthing/syncthing/pull/8923.

I've managed to reproduce like this:

1. Add a new folder on Device 1 and share with Device 2.
2. On Device 2, accept the folder.
3. The "shared with" list now displays a trailing comma on Device 2 (but not on Device 1).

**Comment by calmh** [comment]
Yeah... When iterating over the list, if the last device ID is the local device, there'll be a spurious comma.
