### ISSUE TITLE
1.23.6 docker image  no longer available for linux/arm/v7

### ISSUE THREAD

**Issue by ofalvai** [syncthing/syncthing#8973]
### Include required information

I'm running a Syncthing instance on a Raspberry Pi 3, which is based on the armv7 architecture. I tried upgrading from 1.23.5 to 1.23.6, but this version is no longer available for this architecture.

- 1.23.5: https://hub.docker.com/layers/syncthing/syncthing/1.23.5/images/sha256-c0ab9ad0f10ccd71185e8d3cc0c74a3d56276050ce289c3f3baeed9ec95e4505?context=explore
- 1.23.6: https://hub.docker.com/layers/syncthing/syncthing/1.23.6/images/sha256-e84a00b83684b0d75b58ddc1ac5a5265629bcb07d28a7fd9b3874be00cc6279c?context=explore

**Comment by calmh** [comment]
Right, I didn't consider we used to produce that architecture when migrating the image build, sorry.

(For the record, the Raspberry Pi 3 is 64 bit and will run the arm64 version, but perhaps only with a 64 bit OS or at least kernel.)

```
jb@raspberrypi: $ sudo dmesg|grep -i machine
[    0.000000] Machine model: Raspberry Pi 3 Model B Rev 1.2
jb@raspberrypi: $ syncthing --version
syncthing v1.23.6 "Fermium Flea" (go1.20.5 linux-arm64) debian@github.syncthing.net 2023-07-03 09:51:12 UTC [noupgrade]
```

**Comment by calmh** [comment]
There, `:edge` contains an arm/7 build again, and releases will again as of the next one.
