### ISSUE TITLE
Allows automatic folder creation for missing paths.

### ISSUE THREAD

**Issue by 0x915** [syncthing/syncthing#8997]
When I try to delete a folder in the filesystem, the log shows a warning.

WARNING: Error on folder XXXXX: folder path missing

Then the synchronization will stop. Is it possible to add an option to allow the program to automatically handle this error, create the folder and resume synchronization?

Deleting folders doesn't happen in normal use, but if I want to resynchronize by erasing everything that was synced, I try to delete the folder directly in the file system and click on "rescan all", then the warning appears and the sync stops.

Creating folders manually brings up another warning:

WARNING: Error on folder XXXXX: folder marker missing (this indicates potential data loss, search docs/forum to get information about how to proceed)

Re-adding sync items solves this problem, but can be tricky when there are a lot of folders.

**Comment by imsodin** [comment]
Following this procedure until it syncs again is most likely not doing what you want to achieve: It will delete everything everywhere. And that's also the reason why automatically recreating directories wont be happening.

To get help to figure out what you actually want to achieve and how to get there, please use the forum - https://forum.syncthing.net/. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
