### ISSUE TITLE
Re-enable autoupgrade for custom builds

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing#901]
As per title.
Someone who makes a custom builds doesn't want our binary probably.

**Comment by calmh** [comment]
Can we reopen this for consideration? The original concern was that custom builds shouldn't try to upgrade, however I'm not sure which custom builds these are exactly. :) If they're custom enough to include custom code, I think it's not too much of a burden to add `-no-upgrade` to the build process or set `$NOUPGRADE` when running, or disable auto upgrade in the config. For regular dev builds, we now correctly interpret them as newer than the thing they come from, which may not have been the case earlier:

```
jb@syno:~/src/github.com/syncthing/syncthing git:(𝘮 88 ⇄ 15 v0.11) $ ./bin/syncthing -upgrade
08:48:34 INFO: No upgrade available (current "v0.11.24+1-g4b5c44b" >= latest "v0.11.24").
```

The reason I want to maybe revert this, is that I like to give people dev builds when they're suffering from a bug that's fixed but it's going to be another week until a release that includes it. But I don't want them to get stuck forever on that dev build...
