### ISSUE TITLE
Periodic disk activity prevents spindown

### ISSUE THREAD

**Issue by wkornewald** [syncthing/syncthing#9017]
I'm using Syncthing version 1.23.6 via Docker. Syncthing causes periodic disk activity in the background, preventing disk spindown.

When I run this (e.g. within the container via `docker exec` and installing `apk add inotify-tools` first):

```
inotifywait -mr --format '%w:%f:%e:%T' --timefmt '%F %T %Z %z' /var
```

I get a constant stream of file modifications at least every 60s, sometimes also more frequently

```
/var/syncthing/config/index-v0.14.0.db/:001148.log:MODIFY:2023-08-03 16:48:24 UTC +0000
/var/syncthing/config/index-v0.14.0.db/:001148.log:MODIFY:2023-08-03 16:48:24 UTC +0000
/var/syncthing/config/index-v0.14.0.db/:001148.log:MODIFY:2023-08-03 16:49:24 UTC +0000
/var/syncthing/config/index-v0.14.0.db/:001148.log:MODIFY:2023-08-03 16:50:24 UTC +0000
```

In parallel I get this log output exactly at the time of the file access:

```
[XXXXX] 2023/08/03 16:31:34.089026 service.go:446: DEBUG: Connection loop
[XXXXX] 2023/08/03 16:31:34.089356 device.go:48: DEBUG: stats.DeviceStatisticsReference.GetLastSeen: xxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx 2023-08-03 16:30:34 +0000 UTC
[XXXXX] 2023/08/03 16:31:34.089539 device.go:59: DEBUG: stats.DeviceStatisticsReference.GetLastConnectionDuration: xxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx
[XXXXX] 2023/08/03 16:31:34.089718 device.go:48: DEBUG: stats.DeviceStatisticsReference.GetLastSeen: xxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx 2023-08-03 16:30:34 +0000 UTC
[XXXXX] 2023/08/03 16:31:34.089832 device.go:59: DEBUG: stats.DeviceStatisticsReference.GetLastConnectionDuration: xxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx
[XXXXX] 2023/08/03 16:31:34.090391 device.go:64: DEBUG: stats.DeviceStatisticsReference.WasSeen: xxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx
[XXXXX] 2023/08/03 16:31:34.091197 device.go:64: DEBUG: stats.DeviceStatisticsReference.WasSeen: xxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx-xxxxx
[XXXXX] 2023/08/03 16:31:34.091489 service.go:476: DEBUG: Next connection loop in 1m0s
```

Is this critical for Syncthing to work properly or could the file system accesses be reduced to e.g. only happen together with actual changes to shared folders?

Is there any workaround I can apply for now?

**Comment by calmh** [comment]
No workaround that I'm aware of, though I can see we might want to improve this; it's come up before. What happens here is that Syncthing records a few stats about when devices were last seen, keeping them updated while a device is connected. We could do that instead when getting an actual database update (anyway touching disk) and otherwise defer it to just before we're about to exit. There'd be a risk of those values being inaccurate if there's a very sudden shutdown, but on the other hand we'd be more idle when idle...

**Comment by calmh** [comment]
AFAIK we don't update LastSeen on pings any more, merely on newly established and closed connections, which is much rarer and more reasonable.
