### ISSUE TITLE
Please accept the commit to fix special character error

### ISSUE THREAD

**Issue by slrgt** [syncthing/syncthing#9018]
Theres seems to be a commit submitted a year ago to fix the special character error from 8 years ago opened here #1734 

here is the commit https://github.com/rasa/syncthing/commit/7ef0b09e72fe3ea562b374ea9b70fce8ed83d670

**Comment by AudriusButkevicius** [comment]
Opening a new issue to just bump won't change the situation. 

(Meaningful) Discussions to be conducted on that PR.
