### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by 1005107255** [syncthing/syncthing#9020]
win10环境, 已经安装过基础版本, 现在想要安装带图形界面的.exe版本,提示 
If" FATAL: Cannot open database"appears, please close any otheropen instances of Syncthing If Synctrayzor crashed previously, theremay still be zombie Synching processes alive. Please use the menuoption "syncthing-kill all Syncthing processes"to stop them, thenuse"syncthing->Start "to start Synching again.

原基础版本已经关闭, 请问如何彻底卸载干净原基础版本?

**Comment by nekr0z** [comment]
请使用 https://forum.syncthing.net 寻求帮助和指示。
