### ISSUE TITLE
panic: bug: ClusterConfig called on closed or nonexistent connection

### ISSUE THREAD

**Issue by rasa** [syncthing/syncthing#9021]
While some builds are [succeeding](https://github.com/syncthing/syncthing/actions/workflows/build-syncthing.yaml), three recent builds:

https://github.com/syncthing/syncthing/actions/runs/5777466439/job/15660650363#step:7:1738 (Go 1.19, but not 1.20)
https://github.com/syncthing/syncthing/actions/runs/5778159436/job/15659077804#step:7:1798 (Go 1.19, but not 1.20)
https://github.com/syncthing/syncthing/actions/runs/5780780108/job/15664908391#step:7:1742 (**Go 1.20, but not 1.19**)

all panicked with
```
panic: bug: ClusterConfig called on closed or nonexistent connection
```
This panic is emitted at [lib/model/model.go:1176](https://github.com/syncthing/syncthing/blob/e09146ee0326e22bc967f7bdf33bfe988f79effa/lib/model/model.go#L1176).

It may be related to https://github.com/syncthing/syncthing/pull/9007 which touched the code [near](https://github.com/syncthing/syncthing/commit/9d21b91124d6465e77542768317e2b0a764fffa5#diff-e882cd3f44253874ec7412e2e30f7ba0fa7e42e74a964a33e3658bef5ee6f833) this panic call.

**Comment by imsodin** [comment]
Full failure:

```
--- FAIL: TestAutoAcceptEnc (0.00s)
panic: bug: ClusterConfig called on closed or nonexistent connection [recovered]
	panic: bug: ClusterConfig called on closed or nonexistent connection

goroutine 2647 [running]:
testing.tRunner.func1.2({0x13758c0, 0x16504d0})
	C:/hostedtoolcache/windows/go/1.20.7/x64/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	C:/hostedtoolcache/windows/go/1.20.7/x64/src/testing/testing.go:1529 +0x39f
panic({0x13758c0, 0x16504d0})
	C:/hostedtoolcache/windows/go/1.20.7/x64/src/runtime/panic.go:884 +0x213
github.com/syncthing/syncthing/lib/model.(*model).ClusterConfig(0xc0066dd040, {0x1664208?, 0xc000538600?}, {{0xc005c72ec0?, 0x0?, 0x0?}})
	D:/a/syncthing/syncthing/lib/model/model.go:1176 +0xfea
github.com/syncthing/syncthing/lib/model.TestAutoAcceptEnc.func2({0x2, 0x23, 0xe5, 0xbf, 0x3f, 0x57, 0x1f, 0x39, 0xd2, 0xf0, ...}, ...)
	D:/a/syncthing/syncthing/lib/model/model_test.go:1341 +0x125
github.com/syncthing/syncthing/lib/model.TestAutoAcceptEnc(0xc0066dcd00)
	D:/a/syncthing/syncthing/lib/model/model_test.go:1398 +0x168a
testing.tRunner(0xc0066dcd00, 0x153de38)
	C:/hostedtoolcache/windows/go/1.20.7/x64/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.20.7/x64/src/testing/testing.go:1629 +0x3ea
FAIL	github.com/syncthing/syncthing/lib/model	2.286s
```

**Comment by imsodin** [comment]
Also the referenced large refactor made it into 1.23.7-rc.2 - that's a kind of change that should likely go into an rc.1 for more testing. Lets revert it on the release branch - what do you think @calmh ?

**Comment by calmh** [comment]
Nah, you guys just haven't been paying attention, that test has been flaky in that way since forever. 

https://github.com/syncthing/syncthing/actions/runs/5041570783/job/13647239632

https://github.com/syncthing/syncthing/actions/runs/5169380956/job/13989027073

https://github.com/syncthing/syncthing/actions/runs/5190697258/job/14046864460

https://github.com/syncthing/syncthing/actions/runs/5239298682/job/14175027399

https://github.com/syncthing/syncthing/actions/runs/5388178770/job/14583993334

https://github.com/syncthing/syncthing/actions/runs/5429560194/job/14704372994

https://github.com/syncthing/syncthing/actions/runs/5443079498/job/14733656324

**Comment by calmh** [comment]
Incidentally I recently set up logging of test results to produce stats on test flakiness and actually do something about this.

**Comment by imsodin** [comment]
Ah good, I was actually having some doubts about the validity of that test/failure in the back of my head, but haven't yet looked at the actual issue at all. In retrospect I'd still have probably waited with shipping that for the next release but also ¯\_(ツ)_/¯

Just kicked off a loop of that test to see if I can repro locally, I am curious how/why that happens.
