### ISSUE TITLE
"Try first" IPs for devices

### ISSUE THREAD

**Issue by lucasew** [syncthing/syncthing#9030]
### Include required information

I am trying to use syncthing with tailscale. Tailscale works well and I can ping everyone in my network using their MagicDNS names but Syncthing still insists in using a WAN relay. It's not a firewall issue because I added the tailscale interface in the trusted interfaces list. What I am looking for is a "try first" IPs approach where I pass the MagicDNS names of my hosts then Syncthing can try to connect to these IPs first before relying in any relays or hole punching and stuff.

**Comment by bt90** [comment]
The problem is most likely that Syncthing isn't announcing the IP addresses of the interface to other nodes.

* IPv4: i couldn't find an issue but i doubt that we treat the CGANT range used by Tailscale as local: 100.64.0.0/10
* IPv6: https://github.com/syncthing/syncthing/issues/7456

**Comment by AudriusButkevicius** [comment]
Syncthing tries addresses in order specified, you can specify you addresses followed by default, etc. So it already works.
