### ISSUE TITLE
docker: Missing image for arm v7 platform on tag 1.23.6

### ISSUE THREAD

**Issue by rockstorm101** [syncthing/syncthing#9032]
The current [tag 1.23.6][1] in the docker repository does not contain an image for ARM v7 platforms as previous uploads did. Has it been deprecated? I guess not because the [edge tag][2] still builds for ARM v7?

[1]: https://hub.docker.com/r/syncthing/syncthing/tags?page=1&name=1.23.6
[2]: https://hub.docker.com/r/syncthing/syncthing/tags?page=1&name=edge

**Comment by calmh** [comment]
#8973

**Comment by calmh** [comment]
But a new release is coming ~now so this will be sorted soon :)
