### ISSUE TITLE
Build with Go 1.21 out of the box

### ISSUE THREAD

**Issue by vext01** [syncthing/syncthing#9034]
Hi folks,

OpenBSD just upgraded to Go 1.21 and this broke syncthing for us.

I assume work is under way to support Go 1.21?

```
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.32.0/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration
```

Thanks

**Comment by bt90** [comment]
Blocked by #8930

**Comment by bt90** [comment]
Which in turn is soft-blocked by https://github.com/quic-go/quic-go/pull/3992

**Comment by vext01** [comment]
Can syncthing be built without quic?

**Comment by imsodin** [comment]
Yep, with `-tags noquic`.

**Comment by vext01** [comment]
And that would work on the new version of go?

**Comment by nekr0z** [comment]
> And that would work on the new version of go?

One way to find out is to give it a try.

**Comment by imsodin** [comment]
Should. Also plesae use the forum - https://forum.syncthing.net/ - for further discussions/support for workarounds, ... I'll leave this ticket open as a hint that we don't currently build on go 1.21 and to track the resolution.

**Comment by marco-m** [comment]
@imsodin FYI looks like quick-go v0.37.4 fixed this, see https://github.com/quic-go/quic-go/releases/tag/v0.37.4 (although some of the mentioned issues in this thread are still open, so I might be missing something...).

**Comment by alerque** [comment]
This is blocking Arch Linux updating to the latest syncthing release as well. I'm following along here and will hope for a quick patch release as soon as the blockers are fixed.

**Comment by alerque** [comment]
I believe this issue alone should trigger a new point release as even the last release can't be packaged by many distros any more. There are also other regressions showing up as fixed in the 1.24.0 milestone and nothing marked as pending. Can we either get a 1.24.0 release or backport the fix for this issue into a 1.23.8 release?

**Comment by dlangille** [comment]
> Fixed as of #9040.
> 
> Conversely, it's no longer possible to build with Go 1.19.

Same problem here. I just tried building 1.24.0 and it fails.

:/

**Comment by bt90** [comment]
Syncthing v1.24.0 requires go1.20+

See https://docs.syncthing.net/dev/building.html#prerequisites

> The latest stable version of Go. The previous stable version should also work; **older versions will likely not work.**

**Comment by dlangille** [comment]
Success. Thank you.

**Comment by dlangille** [comment]
To be clear, https://docs.syncthing.net/dev/building.html#prerequisites just says "The latest stable version of Go." and below that mentions "This should output "go version go1.18" or higher."

**Comment by calmh** [comment]
Fixed, thanks for noticing.
