### ISSUE TITLE
Encrypt all content on one/multiple devices

### ISSUE THREAD

**Issue by msjsc001** [syncthing/syncthing#9052]
Hello developers.

Is it possible to add a feature that says, "Encrypt all content on one/multiple devices"?

Since I will be using syncthing to help sync other devices on a cloud server, I don't want to give the cloud server provider access to the content of the files I need to sync for privacy reasons.

I would like to have the option to have the encrypted content be fully encrypted and not be accessible by others when syncthing as a relay to sync content when using a third party server.

I know that I can use software like CRYPTOMATOR to encrypt the files before transferring them, but this is not convenient because some devices can't see the contents in time and don't support the installation of such software.

**Comment by AudriusButkevicius** [comment]
Questions like that should go to the forum. Issue tracker is for bugs.

The feature you are after already exists, suggest you refer to the documentation.
