### ISSUE TITLE
Proposal: add an endpoint to retrieve/modify the HTTPS certificate

### ISSUE THREAD

**Issue by LBF38** [syncthing/syncthing#9053]
### Problem
I have a problem to easily validate the self-signed HTTPS certificate from Syncthing. It provides better security across devices and when syncing. However, it is hard, for a plugin/client to make API calls to Syncthing when HTTPS is enabled. It needs to validate the HTTPS certificate in some way, to make it trusted in the user's browser/environment.

### Why could it be useful ?
Therefore, the solution would be to have a noauth endpoint in Syncthing that allows a client to get the HTTPS certificate and make it possible to add it to the user's browser/environment. This validation must be confirmed by a user action when configuring it the first time.
I think that it would be helpful for all projects making API calls to Syncthing when HTTPS is enabled.
Moreover, the solution could be a POST/GET endpoint to be able to provide our own HTTPS certificate or to register the HTTPS certificate generated by Syncthing.

The endpoint could also help on mobile and tablet devices where they have stricter security rules on the app's directory access. It is harder to access the certificates files that are hidden inside of the Syncthing's app folder.

### Alternatives / Workarounds
- Registering the certificates in the browser or in the device directly from `.pem` files.
- Adding Syncthing as a trusted certificate authority. (could lead to security issues I think, not sure).

What do you think about that ?

Thanks for considering it !

**Comment by acolomb** [comment]
When your browser tries to establish an HTTPS connection, it already receives the used certificate as part of the process. What do we gain by adding an endpoint to retrieve it?

**Comment by AudriusButkevicius** [comment]
As it was said, you get the certificate as part of the https request, so get endpoint is pointless. 

No auth things are for things that are no auth. Accepting certificates is not a noauth thing, you'd need to authenticate for that, and we are not going to accept authentication over a plaintext connection, so at the point you'd be able to swap out the certificates, you'd already should have worked out how to work around the fact that its self signed, as that would be the only way we'd even accept a request.

Certificate setup is mostly one off, I don't think it makes much sense to have an api for it.

**Comment by LBF38** [comment]
Yes, I understand that an endpoint wouldn't be as useful as I though. Therefore, how could I send an HTTPS request to Syncthing without having an issue with the certificate ?

As far as I know, after a lot of researches, the only way to make a `fetch` request to a Syncthing endpoint with HTTPS enabled is to have the self-signed HTTPS certificate accepted by the user, isn't it ?

What should I do to make this code snippet work ?
```typescript
const response = fetch("https://localhost:8384/rest/system/ping",{ // fetch or anything that can make requests.
	"X-API-Key": "<the API key>",
	// ...
	});
console.log(response.json);
```  
For now, when I make this call, it throws me a Certificate error. And especially on mobile where HTTPS/TLS is enabled by default.
However, app's files are protected by the device's policy.
Therefore, the suggestion to have an endpoint to get the certificate and allow to validate it.

If you have a workaround or solution to this problem, it would be really useful !

Thank you for your help !

**Comment by calmh** [comment]
> to have an endpoint to get the certificate and allow to validate it

Pretend you had an endpoint for getting the certificate in PEM format. What's your next step to "validate" it, by which I presume you mean get the browser to accept it?

**Comment by bt90** [comment]
Securing a connection by downloading a certificate from an unencrypted endpoint sounds strange.

**Comment by LBF38** [comment]
I don't know, I'm not an expert, just trying to figure out how could I make a request to an HTTPS endpoint without having certificate issues from the self-signed given by Syncthing.

I'm open to any ideas and suggestions. 

For more context, I'm building a plugin for Obsidian to integrate Syncthing and get relevant information about the sync process.
Here is a link to the repo : https://github.com/LBF38/obsidian-syncthing-integration

**Comment by calmh** [comment]
I don't know, but I'd start by answering that. When you've answered that, I think there are existing APIs you can use to get the certificate. Conversely, if there is no good answer to step two, there is no real reason to invest too much in solving step one.

**Comment by bt90** [comment]
It should be possible to ignore certificate validation.

**Comment by LBF38** [comment]
> It should be possible to ignore certificate validation.

Is it still a secure request ? If it ignores the certificate validation, then the request isn't secure anymore.

**Comment by LBF38** [comment]
> I don't know, but I'd start by answering that. When you've answered that, I think there are existing APIs you can use to get the certificate already; https://nodejs.org/api/tls.html#tlssocketgetpeercertificatedetailed looks like it has potential just from a quick search. Conversely, if there is no good answer to step two, there is no real reason to invest too much in solving step one.

Thanks for the reference. I didn't find this API when making my researches.

I think the second step would be to validate the certificate or make the user aware of the use of a self-signed certificate and he makes the choice about trusting it or not.
After that, the API calls shouldn't throw any errors

**Comment by calmh** [comment]
Right. So from my understanding, you can 1) tell Node's HTTP client (if that's what you're using) not to validate the server certificate, and 2) get the certificate from the connection, so there you already have step one without any changes on our side.

I could see there being a point to having an endpoint to update the certificate from the client side, but I can also see reasons to not do that, so I'm going to leave this unactioned for the time being unless more uses cases / needs arise.

**Comment by LBF38** [comment]
If I use `agent: new https.Agent({ rejectUnauthorized: false })`, as @bt90 said, it would ignore the certificate validation.

Therefore, would it still be a secured connection ? I mean, it would be an HTTPS request, so a TLS/SSL socket, and therefore not be exposed to any attackers.

I think that this makes the solution while not being too difficult to implement, even though it doesn't validate the self-signed certificate. The user will only request a baseUrl that he knows is his Syncthing instance, so it is not really unsecure, isn't it ?

```typescript
const options = {
	hostname: ip_address, // 127.0.0.1
	port: port, // 8384
	path: endpoint, // /rest/config for example.
	method: "GET",
	headers: {
		"X-API-Key": "<api_key>", // Syncthing API key
		Accept: "*/*",
		"Content-Type": "application/json",
		"Access-Control-Allow-Origin": "*",
		redirect: "follow",
	},
	agent: new https.Agent({
		rejectUnauthorized: false, // for not validating HTTPS request for self-signed certificates.
	}),
};
```

**Comment by LBF38** [comment]
As commented in the [related thread on Syncthing Forum](https://forum.syncthing.net/t/how-to-modify-the-https-gui-certificate/20775/7), I have issues to retrieve and change the HTTPS certificate on Android. 
Therefore, do you have any ideas on how I could achieve this ? How could I access the generated HTTPS certificate, modify it and make it trusted by the device ? (Manually)

Thx in advance for your help !
