### ISSUE TITLE
Wrong Size of Local State / Global State

### ISSUE THREAD

**Issue by gharlok** [syncthing/syncthing#908]
syncthing 0.10.3 on W7 

The size shown in the folder is just as double as the real size on disk. The wrong size is shown on all Nodes.
The Filecount is correct.

![repo](https://cloud.githubusercontent.com/assets/9392682/4779528/1c4543b0-5c36-11e4-852d-e3dcdb34ed02.PNG)
![disk](https://cloud.githubusercontent.com/assets/9392682/4779530/231ddc2e-5c36-11e4-8d6d-85dbd732f338.PNG)

**Comment by brandonegbert** [comment]
Mine says ~2.12GB for 254GB.  I think it's a bit off.

**Comment by AudriusButkevicius** [comment]
It probably hasn't finished scanning yet.

**Comment by brandonegbert** [comment]
Says it's done.  On closer look I think it may be reporting size on disk rather than actual size.  This is on a Server 2012 R2 machine running NTFS with deduplication.  Guessing that syncthing doesn't play well with Windows dedup?

**Comment by AudriusButkevicius** [comment]
No clue. It should report actual size, given STAT sycall returns the size of the file (rather than 0's or something due to data being duplicate).
Is all 254 GB actually there?
