### ISSUE TITLE
v1.24.0 Bug - Windows x86-32

### ISSUE THREAD

**Issue by pedroalbanese** [syncthing/syncthing#9084]
Greetings!

Today I came across a Syncthing bug consisting of "kernel32.dll not found". This occurred after the program automatically updated to version v1.24.0, which did not happen before. Now I can no longer run Syncthing on Windows because version 1.23.6 updates automatically.

syncthing-windows-386-v1.24.0
![Syncthing](https://github.com/syncthing/syncthing/assets/68971450/29f1e864-d1ef-42a2-a85a-4aefafb89ae1)

Thanks in advance.

**Comment by tomasz1986** [comment]
This isn't about the bits, this is Go dropping support for Windows older than 10.

See https://go.dev/doc/go1.20:

> Go 1.20 is the last release that will run on any release of Windows 7, 8, Server 2008 and Server 2012. Go 1.21 will require at least Windows 10 or Server 2016.

If you want to stay at your current OS, you will need to use the older version of Syncthing with upgrades disabled.

On a side note, I've got a feeling we're going to get many support requests in the near future regarding this.

**Comment by pedroalbanese** [comment]
@tomasz1986

I confess I hadn't realized that it's written in Go (which explains why it runs on all my devices). It makes me sad to hear that the Go team is dropping support for my operating system, even though I develop software in Go. Are there any settings I can use to prevent the binary from being overwritten when I start the software? I didn't find it in settings..

**Comment by pedroalbanese** [comment]
I confess I hadn't realized that it's written in Go (which explains why it runs on all my devices). It makes me sad to hear that the Go team is dropping support for my operating system, even though I develop software in Go.
