### ISSUE TITLE
Provide a launcher icon

### ISSUE THREAD

**Issue by o-alquimista** [syncthing/syncthing#9096]
Provide a launcher icon with the `.desktop` files. I couldn't find any Syncthing icon to use as a launcher icon.

**Comment by calmh** [comment]
Something in https://github.com/syncthing/syncthing/tree/main/assets ?

**Comment by o-alquimista** [comment]
Yes, [`logo-only.svg`](https://github.com/syncthing/syncthing/blob/main/assets/logo-only.svg) works. Thank you.
