### ISSUE TITLE
SyncTrazor and Sycthing do not work on windows

### ISSUE THREAD

**Issue by ayntk-ai** [syncthing/syncthing#9104]
Whenever I try to start synctrazor, I get the following error:
![image](https://github.com/syncthing/syncthing/assets/122374094/acb8a977-0dd3-46dc-8fe2-f3fea786410b)

I tried a few things to fix from an other issue, but none of them worked.
[start] 2023/09/12 14:45:27 WARNING: Error opening database: The process cannot access the file because it is being used by another process. (is another instance of Syncthing running?) This is in the log -> And I only have the one syncthing instace running.

I have this problem on 2 of my PCs.

How can I fix it?

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
