### ISSUE TITLE
Why is Syncthing so unreliable?

### ISSUE THREAD

**Issue by ClickClack7531** [syncthing/syncthing#9105]
It sometimes gets on my nerves when Syncthing works fine one day, then the very next day, I need to transfer a file over and realize that Syncthing broke. All of a sudden, an "Out of Sync" message comes up and since Syncthing doesn't like sharing errors, I have no clue what the problem is. Then I have to spent a good few minutes trying to find out what the problem is and fix it. This is extremely annoying. Why isn't Syncthing a setup once program? Why do I have to constantly keep going into the app to debug it over and over again? And Why does Syngthing not tell me what's wrong with it so I can fix it? It just says "Out of Sync" (like I don't know that already) and doesn't give any info on what the problem is. For Desktop it only gives some vague info on where the problem is coming from and on mobile, there's no error message. Only an extremely vague "Out of sync".

**Comment by nekr0z** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
