### ISSUE TITLE
plan to submit a fuzz driver to OSS-Fuzz

### ISSUE THREAD

**Issue by secsys-go** [syncthing/syncthing#9107]
We are developing a new technique to automatically transform your official unit tests into fuzz drivers. Now we plan to submit this fuzz driver to [OSS-Fuzz Project](https://github.com/google/oss-fuzz). We hope to obtain your approval. Thanks a lot.

The fuzz driver's source code is followed. We are appreciated if you could provide us with some suggestions to improve our fuzz driver's quality.

```go
package upnp

import (
         "testing"
         "encoding/xml"
)

func FuzzTestSoapFaultParsing(f *testing.F) {
	f.Add(`<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
	<s:Body>
			<s:Fault>
					<faultcode>s:Client</faultcode>
					<faultstring>UPnPError</faultstring>
					<detail>
							<UPnPError xmlns="urn:schemas-upnp-org:control-1-0">
							<errorCode>725</errorCode>
							<errorDescription>OnlyPermanentLeasesSupported</errorDescription></UPnPError>
					</detail>
			</s:Fault>
	</s:Body>
	</s:Envelope>`)
	f.Fuzz(func(t *testing.T, data1 string) {
            soapResponse := []byte(data1)
            envelope := &soapErrorResponse{}
            xml.Unmarshal(soapResponse, envelope)
	})
}
```

**Comment by bt90** [comment]
I checked the previous PRs created by this user in other repos. Highly dubious.

**Comment by secsys-go** [comment]
> Hello, is this is a chatbot? I'm not sure what precisely is being proposed but the above looks quite useless.

No, we are real human, not chatbot. We are security research group and now are developing a new technique to automatically transform unit tests into fuzz drivers. We hope to use fuzz to enhance open-source project's security. This fuzz driver is generated via our developing technique. We plan to submit this fuzz driver to [OSS-Fuzz](https://github.com/google/oss-fuzz), but OSS-Fuzz's contributors require project maintainer to approve it. So we invite maintainers of syncthing to review this fuzz driver. 

By the way, bug #8424 is found by our developing technique. We can provide fuzz driver code by which we found it if you need.

**Comment by secsys-go** [comment]
> I checked the previous PRs created by this user in other repos. Highly dubious.

Actually, we test our technique on multiple open-source projects not only syncthing. We are sorry to submit a part of PR without further check, but this time we have carefully reviewed this version to ensure it can work well in OSS-Fuzz. We are appreciated if you could point out possible errors we have not found in this version. Suggestions are welcome too.

**Comment by imsodin** [comment]
As I said on that bug you linked (which was closed), I do think there may be opportunities for beneficial fuzzing on syncthing, but the two examples you showed so far are not (the new one I don't understand at all, it doesn't seem to touch any syncthing code). Crashes based on incorrect usage of non-public APIs aren't very interesting. Crashes based on input on the public connections (protocol package), or the unauthenticated parts of the API would be interesting.
