### ISSUE TITLE
[.stignore] Ignore files under/over a certain size

### ISSUE THREAD

**Issue by Explosion-Scratch** [syncthing/syncthing#9119]
Currently you can't ignore files based on size but this would be very helpful. Here's a possible example syntax:

```
(?size>50MB)* // Ignore all files larger than 50MB
(?size<10kb)* // Ignore all files less than 10kb
!(?size>20MB)*.pdf // Include all PDF files larger than 20MB (but still 10kb < file < 50MB)
```

**Comment by tomasz1986** [comment]
This was rejected previously in https://github.com/syncthing/syncthing/issues/3565 and https://github.com/syncthing/syncthing/issues/6103.

**Comment by calmh** [comment]
Duplicate of #6103
