### ISSUE TITLE
Transferring the server connect address via QR

### ISSUE THREAD

**Issue by Smiley-k** [syncthing/syncthing#9122]
Hi everyone, thanks for the product.
Can you tell me if it is possible to configure the transmission of the connection server address also via QR code when the identifier is scanned? That it would also contain the connection server address 

To elaborate: when you click () show ID it shows only the device ID and when scanning it is sent to the phone, but you also need to send the url of the connection server (when only your server is used) only after that the cell phone will knock to your server. (now the server address has to be manually entered in the phone).

_(you can't imagine how I have already learned to type the connection address on touch screen phones with my eyes closed :-D)._

**Comment by bt90** [comment]
This is handled by global and local discovery. Android makes things a bit harder for us, but that should improve with the next release.

**Comment by calmh** [comment]
I don't think there is a stable, correct URL we can know to put in the QR Code.

**Comment by Smiley-k** [comment]
> I don't think there is a stable, correct URL we can know to put in the QR Code.

What if we take from global settings ?

**Comment by calmh** [comment]
I don't think we should do this.
