### ISSUE TITLE
Hashed passwords via API are hashed again

### ISSUE THREAD

**Issue by jluttine** [syncthing/syncthing#9123]
### Include required information

About 6 years ago, a support for pre-hashed GUI passwords via API was added by fixing the issue https://github.com/syncthing/syncthing/issues/4458 in commit https://github.com/syncthing/syncthing/commit/941c9f1531351091b707803bf456cdc68b151eba

However, it seems this doesn't work anymore. If I understood correctly, this commit broke it a few years ago: https://github.com/syncthing/syncthing/commit/f0f60ba2e74737f16c9fac5e9447d1835fa3deb5#r128163305

So, currently what happens is that the hashed password is taken as the literal plain-text password and hashed. That is, the hash becomes my password.

Is there supposed to be any way of providing hashed GUI passwords to the syncthing API?

Syncthing version 1.24.0 on NixOS.

**Comment by calmh** [comment]
It's supposed to work, indeed. Apparently we're missing a test for it though.
