### ISSUE TITLE
Admin interface listens on port 8080

### ISSUE THREAD

**Issue by attila-lendvai** [syncthing/syncthing#9134]
v1.23.7 running on Guix System.

Syncthing listens on port 8080, and as i understand it shouldn't.

the process is started pretty much with the defaults:
```
user   179  0.0  0.1 733000 26680 ?        Ssl  Sep25   0:00 /gnu/store/b2psppxrqncdmyb8drqvkylz01zjsgng-syncthing-1.23.7/bin/syncthing --no-browser --no-restart --logflags=0
```

this is a dual stack machine, IPv6 is probably part of the story because it only listens on 8080 on tcp6:
```
$ netstat -lnp | grep sync
tcp6       0      0 :::8080                 :::*                    LISTEN      278/syncthing       
tcp6       0      0 :::22000                :::*                    LISTEN      278/syncthing       
udp        0      0 0.0.0.0:52566           0.0.0.0:*                           278/syncthing       
udp        0      0 0.0.0.0:21027           0.0.0.0:*                           278/syncthing       
udp6       0      0 :::21027                :::*                                278/syncthing       
udp6       0      0 :::22000                :::*                                278/syncthing       
udp6       0      0 :::39570                :::*                                278/syncthing       
```

**Comment by bt90** [comment]
Could you check your config file?

**Comment by attila-lendvai** [comment]
bah! i assumed as per the usual Guix way, there's no ~/. config file, but an explicit one provided on the command line.

sorry about my confusion!

here is the relevant part:

```
    <gui enabled="true" tls="false" debugging="false">
        <address>0.0.0.0:8080</address>
        ...
    </gui>
```

this means that my bug can be closed, except... why is it only listening on tcp6? and only on localhost, when the config says `0.0.0.0:8080`?

**Comment by bt90** [comment]
A dual-stack host will bind to both IPv4 *and* IPv6 if `0.0.0.0` is provided. The IPv6 address `::` is the equivalent to IPv4 `0.0.0.0`. The listener on `:::8080` would accept both protocols.

**Comment by acolomb** [comment]
The fact that it chooses another port for IPv4 could be caused by some other software already hogging port 8080, but only bound to IPv4? Or can IP ports only be bound once, regardless of protocol version?

**Comment by bt90** [comment]
https://docs.syncthing.net/users/guilisten.html#port-numbers

**Comment by tomasz1986** [comment]
As far as I remember, the default GUI port used to be `8080` long time ago. @attila-lendvai is your Syncthing installation very old or have you used some kind of an outdated guide to set it up?

**Comment by attila-lendvai** [comment]
> As far as I remember, the default GUI port used to be `8080` long time ago. @attila-lendvai is your Syncthing installation very old or have you used some kind of an outdated guide to set it up?

i started using it about a year ago, but Guix may have had some lag of its own. so, i would guesstimate that i started with a version that was about 2 years old.

i don't remember editing the config file. i'm using `syncthing-gtk`, which has no setting for the port (but may have saved a default config with 8080 in it).
