### ISSUE TITLE
extended attributes do not sync between OSs, cause sync conflicts

### ISSUE THREAD

**Issue by sprig** [syncthing/syncthing#9138]
System A: syncthing v1.23.6 as well as 1.24.0 on gentoo linux, kernel 6.1.46-gentoo-dist-hardened, with the synced foleder sitting on zfs versions zfs-2.1.12-r0-gentoo zfs-kmod-2.1.12-r0-gentoo with `xattr=sa` set on the dataset.
System B: syncthing v1.24.0 on OSX Ventura 13.4.1 (c) on an M.2 MBP.

When "Sync extended attributes" is enabled;
1) They don't actually sync, at least not apple's extended attributes as set by tagging a file.
2) They cause syncthing to get stuck.

Steps to reproduce:
--------------------
1) Setup a synced folder as above.
2) Create a file `file` on system B.
3) Tag it in finder
4) copy `file` to the sync directory.
5) Once it is synced to system A, confirm that extended attributes did not sync: `getfattr -d -m '' file`
6) Delete the file from system B's sync folder.
7) Confirm that system A did not delete above file and is reporting a sync conflict.

At this stage manually deleting `file` from A's sync folder appears to bring everything back to shape.

What I would have expected to happen above is for the file attributes to map somehow between OSX and linux in step 5 above, rather than getting completely wiped.
Alternatively, if this is impossible/too difficult, I would have liked to not be able to enable syncing extended attributes between the OSs or get a warning that some attributes might not actually sync.
In either case, I would have liked syncthing not to have reached a state of conflict.

PS.
I looked at how samba and rsync map extended attributes between the OSs and they don't appear to be compatible. Thus I'm not sure there would be a canonical mapping between OSX and linux xattrs and this is likely a complicated issue.

**Comment by tomasz1986** [comment]
This is by design.

> Extended attributes are recorded and synced on a per-operating system basis. That is, if a file has an extended attribute on one operating system, it will not be synced to another operating system.

Ref: https://docs.syncthing.net/advanced/folder-sync-xattrs.html

**Comment by calmh** [comment]
> Confirm that system A did not delete above file and is reporting a sync conflict.

Can you be more detailed about what you're seeing here and how this sync conflict is reported?

**Comment by sprig** [comment]
> This is by design, at least when it comes to the attributes not syncing part.
> 
> > Extended attributes are recorded and synced on a per-operating system basis. That is, if a file has an extended attribute on one operating system, it will not be synced to another operating system.
> 
> Ref: https://docs.syncthing.net/advanced/folder-sync-xattrs.html

I've seen that page but somehow still managed to miss the prominent message. Valid design choice but I found the reasoning incoherent. Is it open for reconsideration? :-) Samba and rsync both implement extended attribute syncing, FWIW.

> > Confirm that system A did not delete above file and is reporting a sync conflict.
> 
> Can you be more detailed about what you're seeing here and how this sync conflict is reported?

B's web UI is showing A as `Syncing (95%, 0 B)`. A's webui is showing it as "out of sync". The file that was removed on B never gets deleted on A. A's syncthing logs show the following;

```
2023-09-29 17:07:30 Puller (folder "Default" (default), item "example"): syncing: delete file: file modified but not rescanned; will try again later
2023-09-29 17:07:30 "Default" (default): Failed to sync 1 items
2023-09-29 17:07:30 Folder "Default" (default) isn't making sync progress - retrying in 1h4m0s.
```

Manually clicking on "rescan" appears to do nothing. As far as I can tell, the file is synced but without the xattrs. Then, when it is deleted on B, something trips up with the deletion because the files are not actually identical due to the missing xattrs.

**Comment by sprig** [comment]
Hi,

Sorry for the delay. On the mac I get 
```
{
  "availability": [
    "<ID1>",
    "<ID2>"
  ],
  "global": {
    "blocksHash": "XHB5PbsC9glk7Hv5PyUmZPxG9BH1PZ/ZnRdcH8x0jmk=",
    "deleted": false,
    "ignored": false,
    "inodeChange": "2023-10-21T12:28:32.186829419-07:00",
    "invalid": false,
    "localFlags": 0,
    "modified": "2023-10-20T16:49:55.272591501-07:00",
    "modifiedBy": "456X2ET",
    "mustRescan": false,
    "name": "test",
    "noPermissions": false,
    "numBlocks": 1,
    "permissions": "0644",
    "platform": {
      "darwin": {
        "xattrs": [
          {
            "name": "com.apple.FinderInfo",
            "value": "AAAAAAAAAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
          },
          {
            "name": "com.apple.metadata:_kMDItemUserTags",
            "value": "YnBsaXN0MDChAVZUT0RPCjcICgAAAAAAAAEBAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAR"
          }
        ]
      },
      "freebsd": null,
      "linux": null,
      "netbsd": null,
      "unix": null,
      "windows": null
    },
    "sequence": 1,
    "size": 5,
    "type": "FILE_INFO_TYPE_FILE",
    "version": [
      "456X2ET:1697916522"
    ]
  },
  "globalVersions": "{{Version:{[{456X2ET 1697916522}]}, Deleted:false, Devices:{7777777, BC33PLA}, Invalid:{}}}",
  "local": {
    "blocksHash": "XHB5PbsC9glk7Hv5PyUmZPxG9BH1PZ/ZnRdcH8x0jmk=",
    "deleted": false,
    "ignored": false,
    "inodeChange": "2023-10-21T12:28:32.186829419-07:00",
    "invalid": false,
    "localFlags": 0,
    "modified": "2023-10-20T16:49:55.272591501-07:00",
    "modifiedBy": "456X2ET",
    "mustRescan": false,
    "name": "test",
    "noPermissions": false,
    "numBlocks": 1,
    "permissions": "0644",
    "platform": {
      "darwin": {
        "xattrs": [
          {
            "name": "com.apple.FinderInfo",
            "value": "AAAAAAAAAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
          },
          {
            "name": "com.apple.metadata:_kMDItemUserTags",
            "value": "YnBsaXN0MDChAVZUT0RPCjcICgAAAAAAAAEBAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAR"
          }
        ]
      },
      "freebsd": null,
      "linux": null,
      "netbsd": null,
      "unix": null,
      "windows": null
    },
    "sequence": 1,
    "size": 5,
    "type": "FILE_INFO_TYPE_FILE",
    "version": [
      "456X2ET:1697916522"
    ]
  },
  "mtime": {
    "err": null,
    "value": {
      "real": "0001-01-01T00:00:00Z",
      "virtual": "0001-01-01T00:00:00Z"
    }
  }
}
```
Whereas on the linux machine I get:
```
unexpected HTTP status returned: 403 Forbidden
Debugging disabled
```
When trying to run this command. I found [this page](https://docs.syncthing.net/dev/debugging.html), from which I gather that I need to run ST with STTRACE set to something, but I'm still not sure what.

**Comment by calmh** [comment]
It’s a checkbox: https://docs.syncthing.net/users/profiling.html#enable-debugging

**Comment by sprig** [comment]
I was able to enable debugging on linux by setting `debugging="true"` in the `gui` section of config.xml.

However, I was not able to reproduce the error on a new repository. I think I may have also enabled "sync ownership" previously, as that one does understandably  cause a sync conflict between OSX and linux, since the linux user has no permissions to change file ownership to align with the mac.
