### ISSUE TITLE
Usage reporting should include Google Play as a distribution channel

### ISSUE THREAD

**Issue by bt90** [syncthing/syncthing#9140]
Android accounts for 15% of our reported platforms:

![image](https://github.com/syncthing/syncthing/assets/1926175/3a0a6f87-3ce7-4546-8b52-6a89af1bc1e4)

Google Play is the biggest distribution channel for it, but is completely missing from our stats:

![image](https://github.com/syncthing/syncthing/assets/1926175/921f1e0c-6296-4da3-b1cb-12e029cce89f)

**Comment by bt90** [comment]
I wonder if the Regex is outdated?

https://github.com/syncthing/syncthing/blob/dcafd6ec72785cb8495ad59a95f8418ee9731224/cmd/ursrv/serve/serve.go#L67

**Comment by bt90** [comment]
My app reports `builder@github.syncthing.net` which would misclassify it as `GitHub`

**Comment by calmh** [comment]
Maybe set the build user to something else for the android build and add an entry accordingly.

**Comment by bt90** [comment]
Either that or also check the GOOS to determine the channel.

`builder@github.syncthing.net` + android -> Google Play

**Comment by acolomb** [comment]
But that would be a wrong assumption, no? If one bundles a build from GitHub with the app and distributes it over some other channel, this would be incorrect. I agree that the version extra string is the better way to achieve this.

**Comment by bt90** [comment]
I was under the impression that the Syncthing library for the wrapper needed some additional treatment, and you can't just bundle our regular arm binary?

**Comment by tomasz1986** [comment]
It's the regular binary, just compiled for Android. Syncthing proper doesn't offer Android binaries though.

**Comment by bt90** [comment]
Exactly. The chance of a thirdparty simply copy-pasting one of our prebuilt binaries into a wrapper is zero.

**Comment by bt90** [comment]
* App: https://github.com/syncthing/syncthing-android/pull/1978
* Ursrv: https://github.com/syncthing/syncthing/pull/9141

**Comment by bt90** [comment]
F-Droid is also outdated: `vagrant@bullseye`

**Comment by bt90** [comment]
`root@buildkitsandbox` looks like some kind of Docker environment?
