### ISSUE TITLE
traefik no longer url escape X-Forwarded-Tls-Client-Cert header

### ISSUE THREAD

**Issue by Aetf** [syncthing/syncthing#9143]
stdiscosrv has the ability to handle certificates passed by traefik proxy server in `X-Forwarded-Tls-Client-Cert` header.

Previously, traefik url encodes the content but it stopped doing so since version v2.9.4.
This becomes troublesome for setups where stdiscosrv sits behind newer traefik versions,
as now stdiscosrv tries to url [decode](https://github.com/syncthing/syncthing/blob/main/cmd/stdiscosrv/apisrv.go#L356) the header content when it is not encoded.

The symptom can be very confusing, as if some client's certificate's pem text happens to not contain `+`, etc, then it works perfectly, but other clients will always fail announcement with 403 error.

More details can be found at https://github.com/traefik/traefik/issues/9669.

I'm not sure what should be the best strategy here to support both old and new traefik versions... but wanted to at least raise attention.

stdiscosrv version: 1.24.0

**Comment by Aetf** [comment]
Hi @calmh, thank you so much for the fast fix! I can test it when I get time. But from reading the code, it doesn't seem to solve the issue.

Consider the following case:
```
X-Forwarded-Tls-Client-Cert: ABCDEFG+XYZ
```

URL unescape will complete without error, generating string `ABCDEFG XYZ`. The failure will happen down the line when try to do PEM decode on the string. This is actually no different from the behavior before the fix.

IMHO maybe a better fix is to check for the presence of `%` character, like what's done for `X-SSL-Cert` for nginx.

**Comment by calmh** [comment]
Lovely, I forgot that plus is a valid Base64 character.
