### ISSUE TITLE
apt.syncthing.net and other services are down

### ISSUE THREAD

**Issue by serpro69** [syncthing/syncthing#9160]
Tried to run apt update and getting 
```
Err:2 https://apt.syncthing.net syncthing InRelease
  Could not handshake: The TLS connection was non-properly terminated. [IP: 143.244.196.6 443]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
3 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Failed to fetch https://apt.syncthing.net/dists/syncthing/InRelease  Could not handshake: The TLS connection was non-properly terminated. [IP: 143.244.196.6 443]

```

Tying to open https://apt.syncthing.net/ give me "secure connection failed" error in firefox.

Not sure if this is an issue on my side or not though :/ But any help would be appreciated.

**Comment by alext** [comment]
This appears to be a server problem and not just you. I'm seeing the same thing.

https://downforeveryoneorjustme.com/apt.syncthing.net reports it as down, and opening it in Chrome results in a ERR_CONNECTION_RESET error.

**Comment by bt90** [comment]
Looks like one or more servers are down: https://status.syncthing.net/

**Comment by bt90** [comment]
https://status.digitalocean.com/incidents/fsfsv9fj43w7

**Comment by bt90** [comment]
The DigitalOcean guys are still clueless as to what exactly happened, but at least the problem seems to have been resolved.

**Comment by calmh** [comment]
And, again, unresolved -- unsurprisingly given the hilariously non-confidence-inspiring issue update. "Customers have rebooted stuff and that seemed to work for a while 🤷" 🤦 

<img width="1043" alt="Screenshot 2023-10-10 at 08 40 19" src="https://github.com/syncthing/syncthing/assets/125426/9a0d0221-923f-4f27-b565-18edf24cc29d">
