### ISSUE TITLE
If `config.xml` is a symbolic link, Syncthing replaces it with a regular file on config change instead of modifying the referenced file

### ISSUE THREAD

**Issue by an-ca** [syncthing/syncthing#9165]
Hello,

I observe this behavior in the following environment:
- syncthing 1.19.2 ;
- debian bookworm.

I hesitated to file as feature request, the choice is only reflecting my opinion and personal expectations.

I do believe, haven't confirmed, I have observed the same behavior with a more recent version of syncthing when I was using a different environment ; version of syncthing, I believe, was downgraded when migrating operating system and I was observing the same behavior in previous environment (other OS and believed newer version of syncthing).

Anthony

**Comment by AudriusButkevicius** [comment]
I think this is intentional. The config is "moved into place" to ensure the file write is atomic and the config cannot be corrupted by the application being killed at a bad time. 

You can't really do that with a symlink.

**Comment by an-ca** [comment]
I do not know what language Syncthing is written in and with what level of abstraction ; but in the memories of my programming days "high level" languages such as Java or C++ provided abstractions of files which allowed atomic writes.
If nobody confirms this, I may study the case myself at a later time.

Anthony

**Comment by calmh** [comment]
Yeah, that abstraction boils down to a temporary file moved in place over the target (atomically). We *could* detect that the config file is a symlink and follow it to do the operation on the target instead, but I don't want to do that. As far as I'm concerned Syncthing owns the Syncthing config file.

**Comment by an-ca** [comment]
The matter, to me, is not really about the file being a symlink ; the matter is Syncthing not modifying the file but writing a whole new file at each change.

This behavior, I find, is rather exotic.
My library is limited, but many config files tracked on my system are not erased and rewritten at each change, they are modified by the software ; which I find, on a larger view, to make more sense.

The matter resumes to the verb: Syncthing creates a file where I would expect it to modify it ; on the filesystem level, this boils down to modify a file — identified by its inode — rather than creating a whole new one — with all it implies e.g. allocation.

To insist on the point not being the file being a symlink, the behavior is the same if the config file is linked ("hard" link") somewhere else: on any config change, the link breaks.

I am most surprised, if I understand correcly, that the library, framework or more generally abstraction you use behaves as such — writing to a temporary file then writing over as a new file ; it is contrary to anything I've seen or heard of before, and, on a design level, different from anything I've seen or used ; as if the modify did not exist in the used abstraction ; or, does not complies with some specifications, for a reason unclear to me.

I have expressed my thoughts and hope I have made my case clear ; my point is not to push at all cost for something but rather to point to something, I feel, is questionable on a design level and point to a bahavior, I observe, is rather exotic in the realm of softwares I have encountered and file handling libraries I've used.

I remaing available for further discussion if you came round and gave more thought to the matter.

In any case, this particular point does not take anything from Syncthing's core job which it has been doing faultlessly for me for years.

Cheers,
Anthony

**Comment by calmh** [comment]
> This behavior, I find, is rather exotic.

Yeah, it really isn't, it's the only way to do atomic writes on Unix, and the only proper way to overwrite a config file. I can't speak to what other software you have that does it differently, but it's not a point in their favour.

**Comment by acolomb** [comment]
Remember that "most software" uses its config file to read preferences and instructions the user has given. If the options are to be modified from within the software (like, e.g. most GUI apps), they are likely using some kind of settings abstraction system like Dconf, gconf, xfconf, QSettings and the like. They often share storage between many applications and use some sort of database. At least not some plain text file that the user can modify directly. Atomic writing is then handled transparently in that abstraction.

In this way, Syncthing is kind of special, because it does what's needed (atomic writing) while looking like a regular plain configuration file accessible to the user.
