### ISSUE TITLE
New option: pause syncing a folder if its marker is missing, resume when the marker reappears

### ISSUE THREAD

**Issue by resolritter** [syncthing/syncthing#9169]
# Description

Introduce a new option: pause syncing a folder if its marker (`.stversions/`) is missing, but resume syncing when the marker reappears. This option could be added to the Advanced tab of the Edit Folder configuration popup.

# Use-case

I want to sync a folder, but it is sometimes empty because I use it as the mount path for one of my devices, so the folder becomes populated when I mount the device and becomes empty when I unmount the device. Here's what happens:

1. The folder is initially empty (i.e. the device is not mounted); Syncthing flags this as an error (`Error on folder "foo" (xxxx-xxxxx): folder marker missing`) and stops syncing the folder.
2. I use the folder as the mount path for my device, which populates the folder, thus adding the `.stversions/` marker to it.
3. When the next Full Rescan happens, or when I manually hit the Rescan button, Syncthing detects the `.stversions/` marker and resumes syncing.
4. I unmount the device, which empties the folder and goes back to Step 1.

I already am able to pause/resume syncing that way, but it unnerves me that this use-case is not actually supported, so it has some downsides:

1. The UIs and logs get polluted with unwanted errors
2. Since the use-case is not actually supported, I am not sure if I can rely on the current behavior

A solution would be to introduce the new feature proposed in this ticket, which is needed for the use-case above.

---

_Tags for future searches: conditionally, conditional, pause, resume_

**Comment by calmh** [comment]
Since you're describing precisely how Syncthing already works I don't think there's a new feature here. You would like it to show fewer errors, but there is no way for Syncthing to know that the storage being missing is intentional. The way to signal the intentionality is to pause the folder in Syncthing before yanking the storage.

**Comment by resolritter** [comment]
> Since you're describing precisely how Syncthing already works I don't think there's a new feature here

If Syncthing changes in the future, since the described workflow relies on the current behavior, it could break. There's nothing preventing it from breaking since the use-case is not supported as an actual feature, so maintainers do not have to care about not breaking it.

> You would like it to show fewer errors, but there is no way for Syncthing to know that the storage being missing is intentional.

That's precisely the point of the new option: to let Syncthing know that `.stversions/` missing is intentional (no errors) and to let it pause/resume **automatically** upon detection.

> The way to signal the intentionality is to pause the folder in Syncthing before yanking the storage.

I would prefer to have the option, such that Syncthing handles the pausing/resuming automatically, without the need for manual clicks or API calls. On that note, I did not find an endpoint on https://docs.syncthing.net/dev/rest.html for pausing/resuming a particular folder.

**Comment by calmh** [comment]
> I would prefer to have the option, such that Syncthing handles the pausing/resuming automatically, without the need for manual clicks or API calls.

Syncthing does precisely that today. It's a critical feature that the folder is stopped when the marker (`.stfolder`, typically) disappears. We're not going to break that behavior. 👍
