### ISSUE TITLE
Versions files not going to correct folder

### ISSUE THREAD

**Issue by Blive77** [syncthing/syncthing#9173]
Hi Im currently using syncthing version 1.25, on 3 Linux servers. And facing a big problem with versioning. It dosent mather what folder i set for versioning, or even no folder, That it is not creating the new versions files inside the folder it is supose to. The files are beeing created yes, but on same place of the edited file.
Some Times i change the folder and it did create the file inside the correct folder, but ONLY once, and then would continue creating the Next versions on same folder as the edited file.
This is a big problem. Please give me some feedback

**Comment by tomasz1986** [comment]
Are you sure you're talking about versions and not conflicts? Can you provide some examples of the filenames? A screenshot would be useful too.

**Comment by Blive77** [comment]
![image](https://github.com/syncthing/syncthing/assets/8531376/f2713b64-0c3c-4c69-a95c-a7cbbf5ddfa6)

maybe is some conflict but how can i fix this conflicts?
I have a SMB service and im editing the files in windows and syncthing are running as root in the machines.

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
