### ISSUE TITLE
Problem to upgrade

### ISSUE THREAD

**Issue by lucas-per** [syncthing/syncthing#9174]
What happened:
2023-10-14 08:10:03: upgrading: open C:\Program Files\Syncthing\syncthing1072001170: Access is denied.
2023-10-14 08:11:55: Automatic upgrade: open C:\Program Files\Syncthing\syncthing136737268: Access is denied.

What I expected to happen:
That Syncthing was updated without any problems.

Steps to reproduce the problem:
I just clicked on the blue button at the top of the screen.

 - Syncthing version: 1.24.0
 - OS: Windos 11 Home 22H2 22621.2428
 - Browser and version: Firefox 118.0.2

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
