### ISSUE TITLE
Problems with Send & Receive Only Servers

### ISSUE THREAD

**Issue by JD-aus** [syncthing/syncthing#9187]
I have been a keen user of Syncthing for many years and once setup in full-sync it just works, regardless of the OS used. 

I now have a situation where i need to create a read-only copy of an old windows server that the client hasn't felt needs to be replaced (until recently). These files will soon reside on a TrueNAS Scale system as he still wants to use mapped network drives.

All Shares are complaining about locally changed files and folders on the "recieve only" NAS. If i revert changes, this fixes the problem for a while (appears to be random amount of time) but eventually the local changes problem re-occurs again. The amount of time can be an hour to a few days.

Nobody currently has file access to the files on the NAS, so no local changes are possible without me SSHing into it.

I have SSHed into the NAS to check file sizes and dates of files reportedly changed on NAS, however no changes can be seen and everything appears to be equal on both systems.

Systems
1. Windows Server 2012R2 (yep OLD) running V1.25.0 as a service using the recommended NSSM setup with all Folder Types as "Send-Only" 
2. TrueNAS-SCALE-22.12.4.2 running Syncthing "enterprise" (V1.23.3) in a container (the enterprise version allows for the files to be saved into a custom dataset, rather than the container (ix-applications) dataset).

- These can probably change to "Send & Receive" in future, when ready to move all mapped drives to NAS shares, but at present i would prefer to keep as seperate send / receive machines just to be safe.

### Does your log mention database corruption?
Not that i can see.

### Include required information
 - which version of Syncthing and what operating system you are using
Above
 - browser and version, if applicable
N/A
 - any steps to reproduce the problem.
I have not tried another system setup, as it took many days to sync files from the old server, and im already limited on time for this project.

**Comment by JD-aus** [comment]
I am not overly concerned about this getting fixed, as it is more of a temporary measure for me at present, but as its the first time i have had an issue with Syncthing, i thought i should raise it, rather than just ignore it.

**Comment by JD-aus** [comment]
after some time, i think i have worked out that the issue I am seeing is only on the TrueNAS scale client. If i setup a windows client to "recieve only" it works without requiring the reverting of files each day. I wonder perhaps if it is to do with ZFS doing something strange with the filesystem handles, so that Syncthing thinks that the files have been changed when they are only being checked by ZFS. is there any debug settings i can turn on that will allow someone with more knowledge than me to shed some light on this ?

**Comment by calmh** [comment]
You can use `syncthing cli debug file` to look at the database record of a file it wants to revert. Then you can see what it think is the difference between old and new.

**Comment by JD-aus** [comment]
Thanks Calmh, unfortunately syncthing is running in a container on the NAS and im not familiar enough to run commandline args ...

I have stopped the problem by making the "Full Rescan Interval" to 0 ... perhaps this should be ignored when a recieve only sync is setup ? as this setting is not required when we only want to recive changes from an outside source ... and perhaps the Rescan Interval HTML field (id="rescanIntervalS") can be disabled when the "Folder Type" of "Recieve Only" is selected (and then returned to normal when changed to others)
