### ISSUE TITLE
Sync progress bar *below* folder/dir name, not above it.

### ISSUE THREAD

**Issue by jult** [syncthing/syncthing#9194]
This was proposed before;
https://github.com/syncthing/syncthing/issues/7882
but this issue was improperly closed with the 'conclusion' that a 'custom theme was the way to go'. Well it was, except this means I need to compile each binary anew at every update of syncthing. So it would be OK if that custom theme would be in the general binary distro, but nobody seems to want to see this change exist for the general public (for some strange reason), so I keep having to recreate my own binaries. So again: Make it optional. Or distribute a theme with the progress bar on the bottom, under the sync dir name, everybody happy.

**Comment by tomasz1986** [comment]
> this means I need to compile each binary anew at every update of syncthing

There is no need to do that. Please check https://docs.syncthing.net/users/faq.html#i-don-t-like-the-gui-or-the-theme-can-it-be-changed. This can even be done on Android (via the app settings).
