### ISSUE TITLE
Receive only folder init don't delete origin files

### ISSUE THREAD

**Issue by WoolenWang** [syncthing/syncthing#9206]
I try to add one Receive only folder in my client host which has the same struct data just as my server Send only Folder.
I see the client side syncthing just make all the Receive folder data as a localchange and ask to revert local change and sync the remote data. when i click the revert local change button, all of the local data will be delete, and then sync the serverside data.
Is that any way to make the Receive only folder don't try to delete all files in the disk in init state, just sync the different and make different data as change.

**Comment by calmh** [comment]
That is more or less what happens, though.

Initially, when you add a receive-only folder, all data is tagged as local additions and would be removed if you press revert. However, when it connects to another device that announces the same files they are automatically resolved to up-to-date instead, and only actual differences remain as local additions. Pressing revert then would only delete the things that should actually not be there any more.

**Comment by calmh** [comment]
I don't see the change to make, here. Possibly, documentation or UI-wise, something could be improved. If someone figures out what that is, that could be an actionable ticket.
