### ISSUE TITLE
"Windows Defender SmartScreen prevented an unrecognized app from starting" warning

### ISSUE THREAD

**Issue by noisemaker00** [syncthing/syncthing#9225]
When I try to execute the application Windows Defender block it and says it's unrecognized.
Maybe any signature/certificate missing?

 - Syncthing windows-amd64-v1.26.0
 - Windows 11

**Comment by calmh** [comment]
Signatures look good to me. Unfortunately, this is one of those things that are not really deterministic and I don't think we can do much about it. Sorry.

**Comment by noisemaker00** [comment]
I see... maybe you can try to submit the .exe file here (as developer) to allow MS review it and unflag as dangerous
https://www.microsoft.com/en-us/wdsi/filesubmission/

**Comment by ProactiveServices** [comment]
This isn't a problem for the developers, it's a problem for the users / customers of the faulty software. Feel free to submit the false positive to Microsoft and send them specific feedback about their software's flawed detection.
