### ISSUE TITLE
apt install doesn't work

### ISSUE THREAD

**Issue by alexander-potemkin** [syncthing/syncthing#9232]
### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using: Ubuntu 23.10
 - browser and version, if applicable: n/a
 - what happened:
 I followed the instructions from https://apt.syncthing.net/, but on `apt update`  I keep getting an error:
```bash
sudo apt update
Hit:1 http://en.archive.ubuntu.com/ubuntu mantic InRelease
Hit:2 http://en.archive.ubuntu.com/ubuntu mantic-updates InRelease
Hit:3 http://en.archive.ubuntu.com/ubuntu mantic-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu mantic-security InRelease         
Get:5 https://apt.syncthing.net syncthing InRelease [15,1 kB]             
Err:5 https://apt.syncthing.net syncthing InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D26E6ED000654A3E
Reading package lists... Done
W: GPG error: https://apt.syncthing.net syncthing InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D26E6ED000654A3E
E: The repository 'https://apt.syncthing.net syncthing InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

``` 
 
 - what you expected to happen instead: apt update to work properly.
 - any steps to reproduce the problem: install fresh Ubuntu 23.10, follow the steps from apt.syncthing.net

I did my googling and tried troubleshooting steps, but non of them helped. The only thing I've found was that `/usr/share/keyrings/syncthing-archive-keyring.gpg` contained 302 error - I replaced that with the content of https://www.syncthing.net/release-key.txt, but it didn't help.

**Comment by bt90** [comment]
You need https://syncthing.net/release-key.gpg as outlined in the description at https://apt.syncthing.net/

@calmh i think this is the problem that https://github.com/syncthing/apt-web/pull/32 tries to fix

**Comment by nextiny** [comment]
@alexander-potemkin, please try something like
```shell
sudo curl -Lo /etc/apt/trusted.gpg.d/syncthing-archive-keyring.gpg https://syncthing.net/release-key.gpg
echo "deb [signed-by=/etc/apt/trusted.gpg.d/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable" | sudo tee /etc/apt/sources.list.d/syncthing.list
printf "Package: *\nPin: origin apt.syncthing.net\nPin-Priority: 990\n" | sudo tee /etc/apt/preferences.d/syncthing
sudo apt-get update
sudo apt-get install syncthing
```
The main point here is to use curl's -L key to process HTTP redirects properly, downloading the key. Good luck.

**Comment by calmh** [comment]
Has this used to work without a redirect, but now it's GitHub pages and it serves a redirect from the apeks domain to www...

**Comment by calmh** [comment]
Fixed (in multiple ways).
