### ISSUE TITLE
[Interface improvement] Non-intuitive "folder type" transfer modes

### ISSUE THREAD

**Issue by sebbes333** [syncthing/syncthing#9233]
**PROBLEM:**
In the web interface, when adding a folder & selecting the "Advanced tab --> Folder type" (send/recieve/etc..)
It makes no sense & needs to be GREATLY improved.

**DESCRIPTION:** (somewhat long winded)
I have 2 devices (PC & Phone), I just want all my pictures to be sent from the Phone & stored on my PC, that's it, it SHOULD NOT be THIS COMPLICATED.
Firstly, the informational description in the [help file](https://docs.syncthing.net/v1.26.0/users/foldertypes) makes no sense.
The descriptions references each other (should be self-describing), so for me to be able to even UNDERSTAND what YOUR interpretation of a "Receive only folder" is, I FIRST has to read the description of the "Send only folder", mostly because the line: _"The receive only folder is the logical opposite of the send only folder."_ (WTF?) yeah, it kind of makes sense, but it is pointless, confusing & doesn't add any new USEFUL information.

Then in the "Receive only folder" there is the text _"In send only mode, all changes from other devices in the cluster are ignored."_ which again is a WTF? moment, as it does not help explain WHICH of my 2 devices would be considered to be "The Cluster"? (or is it Both? How would that even work? Ignores everything?) "the cluster" does not explain which device would be trying to send/receive the data, because it doesn't explain which device would be considered to BE "the cluster#.

The problem is also that "both" folders are kind of the "same" folder.
I'm (in one of the tries) sharing the picture folder from my phone, and need to add it to my destination folder on my PC, I get the notification in the web interface on the PC that my phone want to share a folder, I click Add & it is a it has a folder path to my destination folder, it is VERY un-clear which way the data will be transferred & therefore which mode I should use.
I could ASSUME that it sends the data from the phone to my PC, but IF I'm WRONG, it might delete my entire photo folder because the PC folder is empty, and it was in Send/Receive mode (whichever of them would be the wrong mode in this case) so it sends a command to "update" the phone folder to be empty... I REALLY do not want that.

**SOLUTION(?):**
This entire problem could be solved with a more intuitive interface, eg. something like this:
My_PC_folder  <---  My_Phone_folder // (backup transfer mode)
or:
My_PC_folder  <--->  My_Phone_folder // (sync transfer mode)

or multiple devices (& folders):
My_PC_folder  <----  My_Phone_folder_1 // (backup transfer mode)
..............................<--->  My_Phone_folder_2 // (sync transfer mode) 
..............................---->  My_Phone_folder_3 // (reference transfer mode, or some better description)
(ignore the dots, needed for structural formatting)

My_PC_folder_2  <--->  My_OTHER_Phone_folder_4 // (sync transfer mode)

Or something like this, where it is easy & intuitively to see what is going on & what device is trying to send what data to where.

Thanks.

**Comment by tomasz1986** [comment]
This really belongs to https://forum.syncthing.net, however just for clarification:

> I just want all my pictures to be sent from the Phone & stored on my PC

There is no such mode in Syncthing. This is assuming that you don't want to keep the files on the phone. There are hacks around the limitation but overall this is an unsupported use case of Syncthing. If you really need this, please search the forum for "one way sync" (https://forum.syncthing.net/search?q=one%20way%20sync).

> "the cluster"

The Docs are often written with more technical people in mind which unfortunately makes the language not really accessible to average computer users. "Cluster" is a technical term which here basically means all devices that share the same folder with one another.

**Comment by sebbes333** [comment]
> This really belongs to https://forum.syncthing.net, however just for clarification:

Thanks, I didn't know about that forum.

> > I just want all my pictures to be sent from the Phone & stored on my PC
> 
> There is no such mode in Syncthing. This is assuming that you don't want to keep the files on the phone. There are hacks around the limitation but overall this is an unsupported use case of Syncthing. If you really need this, please search the forum for "one way sync" (https://forum.syncthing.net/search?q=one%20way%20sync).

After a lot try & error I think it is actually working as I intend it to work, even if it is a "unsupported use case".
In short:
* Do NOT add the folder from the computer, add it from the phone (could maybe work in "reverse" too if you use "send only" mode?). 
* Firstly, set up SyncThing so all devices are connected & registered & on the same network (beware of 2.5 GHz & 5 GHz difference in network).
* In your phone, share the folder with your data you want copied to the computer.
* In the computers web-interface, you should get a notification about your phone wanting to send a folder to be synced.
* In "General > File path" add the path to your desired Destination Folder on your computer, 
BE AWARE: The "Folder Label" changes the destination of the "File Path" (kind of stupid design & leads to many unnecessary problems) but if you change the File Path AFTER the Label, i THINK it works, but preferably keep them EXACTLY the same, to the very letter.
* In "Sharing >" put a check-mark(s) to select the device(s) you want to share the PC folder (in this case) with.
* In "Advanced > Folder type" select: "Receive only" (ONLY NOW you can optionally "Receive with encryption" CAN NOT CHANGE LATER, but that brings more hassle).
* The rest of the settings should be good with default options.
* Save & exit those settings, make sure your device(s) are connected & running correctly, then you should be able to start the syncing, aka. "backup" process.
