### ISSUE TITLE
Problems with paths with `/dir.../`

### ISSUE THREAD

**Issue by o0nd7ots** [syncthing/syncthing#9239]
### Does your log mention database corruption?
no

### Include required information
I am running Syncthing 1.26.1 on Android and Linux.

On Linux I have set syncthing to send only, on Android to recieve only.
I have run into an issue when trying to synchronize a directory that ended with `...`:
```
[...]/SyncthingNativeCode(10438):
[HASH] Puller (folder "name" (ID), item "/path/to/folder.../file.foo"):
syncing: creating parent dir: file dies not exist
```
On Android i have a folder `/path/to/folder/` that is empty

Hf i change the name of `folder...` to `folder` on Linux, it works.

I think this something not obvious and Syncthing either needs a explicit pop-up or to handle such names

**Comment by tomasz1986** [comment]
Your Android device likely uses the FAT filesystem which doesn't allow trailing dots. That's why Syncthing can't create the `folder...`.
