### ISSUE TITLE
Versions path does not honor tilde (~) shortcut

### ISSUE THREAD

**Issue by SixFive7** [syncthing/syncthing#9241]
Hi,

It seems the folder path honors the ~ shortcut, but the versions path does not. This results in rather unexpected behavior. Should the ~ logic not be hooked on both places?

## Situation
Vanilla Syncthing running in a docker container.

## Folder config
Folder path: `~/myfolder/data`
Versions path: `~/myfolder/versions`

## Expected behavior:
- Synced data in `/var/syncthing/myfolder/data`
- Remote deleted data in `/var/syncthing/myfolder/versions`

## Observed behavior:
- Synced data in `/var/syncthing/myfolder/data`
- Remote deleted data in `/var/syncthing/myfolder/data/~/myfolder/versions`

## Additional information
- Syncthing version: v1.26.1 `Gold Grasshopper` (latest as of writing this ticket)
 - OS context: New Linux kernel + [official docker image](https://hub.docker.com/r/syncthing/syncthing/)

**Comment by calmh** [comment]
Probably should.
