### ISSUE TITLE
Please make the GTK client adjust to small screen sizes

### ISSUE THREAD

**Issue by agx** [syncthing/syncthing#9248]
With Linux based phones becoming more popular having the syncthing client be useful on those would be great. Here's how it currently look under e.g. [phosh](https://phosh.mobi) with syncthing-gtk's prefs dialog open:

![syncthing-gtk with prefs open](https://github.com/syncthing/syncthing/assets/2052773/18312629-2e95-467e-99a6-ef212941c164)

Porting to GTK4 and using [libadwaita](https://gitlab.gnome.org/GNOME/libadwaita)  would basically make it adjust to small and large screen sizes automatically.

**Comment by imsodin** [comment]
This is the wrong project: https://github.com/syncthing-gtk/syncthing-gtk
