### ISSUE TITLE
[Feature Request] Add a delay between change detection and scan

### ISSUE THREAD

**Issue by TOomaAh** [syncthing/syncthing#9263]
Hello,

First of all, I've searched and haven't found either the option or an open exit for this (and I apologize if I'm wrong).

When adding items to my folder which is synchronized, a number of automations are launched (renaming the file, assigning metadata, parsing the file...) as well as the detection and scanning of the file/directory by Syncthing.

I'd like an option to delay the scan after detection to limit I/O and CPU usage.

I know there's an option to scan a directory every X times and detect changes. I'd like to keep the real time and just delay the scan by one or 2 minutes so that the different tools can run freely without slowing each other down.

**Comment by calmh** [comment]
You're in luck!

https://docs.syncthing.net/users/config.html#config-option-folder.fswatcherdelays

**Comment by TOomaAh** [comment]
Oh! Has this been added to version 1.27?

In any case perfect ahah! Thank you very much!
