### ISSUE TITLE
Synchronize the same local path to the different folders, progress is show stop 

### ISSUE THREAD

**Issue by shenmingxing** [syncthing/syncthing#9268]
### Include required information

Please be sure to include at least:

 - what problem your new feature would solve
 - how or why you think it is generally useful (i.e., not just for you)
 - what alternatives or workarounds you considered

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
