### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by etsoft** [syncthing/syncthing#9277]
Hi, it would be very helpfull to have an option to clean up the folder keeping the last version of a certain month available. The rest of the files can be deleted then (only one will be available after the month has ended)

Regards
Erwin

**Comment by AudriusButkevicius** [comment]
Please have a read on external versioning, where you can plug in your own versioning scheme: https://docs.syncthing.net/users/versioning.html#external-file-versioning

It's there because we can't cater for every use case out there.
