### ISSUE TITLE
Unable to execute on WD My Cloud (armv7l)

### ISSUE THREAD

**Issue by gitviola** [syncthing/syncthing#928]
I wanted to install syncthing on my WD My Cloud but I get an error. I think this is related to #412 

The machine is:

```
SpaceShip:~# uname -a
Linux SpaceShip 3.2.26 #1 SMP Tue Jun 17 15:53:22 PDT 2014 wd-2.2-rel armv7l GNU/Linux
```

and the error is:

```
SpaceShip:~/syncthing-linux-armv7-v0.10.4# ./syncthing
unexpected fault address 0x38456c
fatal error: fault
[signal 0xb code=0x2 addr=0x38456c pc=0x38456c]

goroutine 16 [running]:
runtime.throw(0x753342)
    /usr/local/go/src/pkg/runtime/panic.c:520 +0x5c fp=0x414d1eb0 sp=0x414d1ea4
runtime.sigpanic()
    /usr/local/go/src/pkg/runtime/os_linux.c:240 +0xf8 fp=0x414d1ebc sp=0x414d1eb0
code.google.com/p/snappy-go/snappy.init()
    ?:0 fp=0x414d1ec0 sp=0x414d1ec0
github.com/syndtr/goleveldb/leveldb.init()
    /home/jenkins/.jenkins/jobs/syncthing/workspace/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/version.go:436 +0x74 fp=0x414d1ef0 sp=0x414d1ec0
github.com/syndtr/goleveldb/leveldb.init()
    /home/jenkins/.jenkins/jobs/syncthing/workspace/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/version.go:436 +0x74 fp=0x414d1f20 sp=0x414d1ef0
github.com/syncthing/syncthing/internal/files.init()
    /home/jenkins/.jenkins/jobs/syncthing/workspace/src/github.com/syncthing/syncthing/internal/files/set.go:231 +0x90 fp=0x414d1f4c sp=0x414d1f20
created by _rt0_go
    /usr/local/go/src/pkg/runtime/asm_arm.s:72 +0xb0

goroutine 19 [finalizer wait]:
runtime.park(0x484a0, 0x7584b4, 0x757039)
    /usr/local/go/src/pkg/runtime/proc.c:1369 +0x5c
runtime.parkunlock(0x7584b4, 0x757039)
    /usr/local/go/src/pkg/runtime/proc.c:1385 +0x40
runfinq()
    /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xa0
runtime.goexit()
    /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
    /usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x24
created by os/signal.init·1
    /usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x48
```

I tried to downgrade to a Firmware Version < 4 but it didn't work. Is it somehow possible to build a release that works on the infrastructure of WD My Cloud?

**Comment by schurig** [comment]
Are there any news on that problem? I saw that there was a generic ARM build introduces in `v0.10.19`, called just `syncthing-linux-arm`. It says that works on ARMv5 and higher. Will that also work on `armv7l`?

**Comment by AudriusButkevicius** [comment]
Well it seems that your device vendor is causing the problem, not syncthing, hence I am not sure we can help here unless we patch go's source code.

You can always try the generic arm build, but I have no clue if it work or not, as I don't own the device in question.

**Comment by fiam** [comment]
For anyone coming here from a Google search, the problem is that firmwares from version 4 onwards use 64K pages rather than 4K.  To build Go binaries for the WD My Cloud you need to apply the following patch go's source code, then build for linux/arm.

```diff
diff --git a/src/cmd/5g/gsubr.c b/src/cmd/5g/gsubr.c
index f091979..02f6f06 100644
--- a/src/cmd/5g/gsubr.c
+++ b/src/cmd/5g/gsubr.c
@@ -36,7 +36,7 @@
 // TODO(rsc): Can make this bigger if we move
 // the text segment up higher in 5l for all GOOS.
 // At the same time, can raise StackBig in ../../runtime/stack.h.
-long unmappedzero = 4096;
+long unmappedzero = 65536;
 
 void
 clearp(Prog *p)
diff --git a/src/cmd/5g/peep.c b/src/cmd/5g/peep.c
index 639f4c5..6f90acd 100644
--- a/src/cmd/5g/peep.c
+++ b/src/cmd/5g/peep.c
@@ -756,7 +756,7 @@ findinc(Flow *r, Flow *r2, Adr *v)
 			p = r1->prog;
 			if(p->as == AADD)
 			if(isdconst(&p->from))
-			if(p->from.offset > -4096 && p->from.offset < 4096)
+			if(p->from.offset > -65536 && p->from.offset < 65536)
 				return r1;
 		default:
 			return nil;
@@ -865,7 +865,7 @@ xtramodes(Graph *g, Flow *r, Adr *a)
 			   (p1->from.type == D_SHIFT && (p1->from.offset&(1<<4)) == 0 &&
 			    ((p->as != AMOVB && p->as != AMOVBS) || (a == &p->from && (p1->from.offset&~0xf) == 0))) ||
 			   (p1->from.type == D_CONST &&
-			    p1->from.offset > -4096 && p1->from.offset < 4096))
+			    p1->from.offset > -65536 && p1->from.offset < 65536))
 			if(nochange(uniqs(r1), r, p1)) {
 				if(a != &p->from || v.reg != p->to.reg)
 				if (finduse(g, r->s1, &v)) {
@@ -1625,5 +1625,5 @@ smallindir(Addr *a, Addr *reg)
 {
 	return reg->type == D_REG && a->type == D_OREG &&
 		a->reg == reg->reg &&
-		0 <= a->offset && a->offset < 4096;
+		0 <= a->offset && a->offset < 65536;
 }
diff --git a/src/cmd/5l/obj.c b/src/cmd/5l/obj.c
index c6f60ee..679a06c 100644
--- a/src/cmd/5l/obj.c
+++ b/src/cmd/5l/obj.c
@@ -91,7 +91,7 @@ archinit(void)
 		if(INITDAT == -1)
 			INITDAT = 0;
 		if(INITRND == -1)
-			INITRND = 4096;
+			INITRND = 65536;
 		break;
 	case Hnacl:
 		elfinit();
diff --git a/src/runtime/arch1_arm.go b/src/runtime/arch1_arm.go
index 6662eae..b2e84b8 100644
--- a/src/runtime/arch1_arm.go
+++ b/src/runtime/arch1_arm.go
@@ -9,7 +9,8 @@ const (
 	_BigEndian        = 0
 	_CacheLineSize    = 32
 	_RuntimeGogoBytes = 60
-	_PhysPageSize     = 65536*goos_nacl + 4096*(1-goos_nacl)
-	_PCQuantum        = 4
-	_Int64Align       = 4
+	//_PhysPageSize     = 65536*goos_nacl + 4096*(1-goos_nacl)
+	_PhysPageSize = 65536
+	_PCQuantum    = 4
+	_Int64Align   = 4
 )
diff --git a/src/syscall/syscall_linux_arm.go b/src/syscall/syscall_linux_arm.go
index b127345..2f912dd 100644
--- a/src/syscall/syscall_linux_arm.go
+++ b/src/syscall/syscall_linux_arm.go
@@ -6,7 +6,7 @@ package syscall
 
 import "unsafe"
 
-func Getpagesize() int { return 4096 }
+func Getpagesize() int { return 65536 }
 
 func TimespecToNsec(ts Timespec) int64 { return int64(ts.Sec)*1e9 + int64(ts.Nsec) }
```

Note that this will break ARM builds for 4K sized pages.

**Comment by MyPod** [comment]
I managed to build Go and SyncThing, if someone's interested, using flam's patch.

https://www.dropbox.com/s/jff3gvltfix4t5s/syncthing-wdmycloud-arm64k-01_feb_2015.tar.gz from git trunk in that date

I can try keeping up with releases, but I cannot grant that

I also leave here a link to the go build I made, in case it's useful to someone
https://www.dropbox.com/s/099s2w5b9u3drbm/go-1.4.tar.xz

**Comment by schurig** [comment]
@fiam @MyPod thanks for your help. I currently use an outdated firmware for my WD MyCloud and I don't want to risk updating and not being able to use the latest syncthing builds. In fact, I rather have syncthing updating on the WD MyCloud by itself - it is painful to always build a custom version as soon there is a new syncthing release; I really enjoy the auto-backup feature!

Does anyone of you have the WD MyCloud and runs version 4+ on it? I saw that there was a new go release but unfortunately I'm not that much into golang and system related stuff, so I don't know whether they now have a way to build for 64K pages without the need of a manual patch.

**Comment by cuberoot74088** [comment]
Yes, I am running WD MyCloud using the new 4+ firmware. Thanks to work and hints from @fiam and @MyPod I was able to compile the recent **syncthing v0.11.2** (using the modified go for linux arm).

If you are interested, the binary is found here:

https://www.dropbox.com/s/vi6otgm5m3ncmqt/syncthing-linux-arm-v0.11.2%2B26-gcb5ef26-noupgrade.tar.gz?dl=0

I might update the build from time to time if there is interest. 
BTW: is there another solution meanwhile?

Thanks for a lot to everybody for making this possible!

**Comment by MyPod** [comment]
@schurig I seriously doubt go will support customized platforms such as the one used by WD in its products as they're not in relevant amount. Probably, if someone gets it to work without breaking the normal, 4k allocation model, it could be integrated, but more probably it'll be left to those really interested to get things running. The true alternative not to be stuck with old, potentially buggy software would be to ditch WD's OS and get a proper debian running - either way, I don't feel that this is something Syncthing can do much about

**Comment by schurig** [comment]
@cuberoot74088 @fiam @MyPod is it somehow possible to automate that process of building syncthing for WD MyCloud as soon there is a new syncthing version? So that one could write a daily or weekly cronjob that auto-downloads the latest version and restarts syncthing

**Comment by MyPod** [comment]
@schurig you'd need to update a local git repo on the device and figure a way for which you checkout build only tagged versions if they're newer than the last build. I believe it can be done, but I lack enough knowledge of git and a 24/7 running box and connection atm. I may be able to do this manually, though.

**Comment by schurig** [comment]
@MyPod atm I am running a backup of my wd mycloud. After that I will update to the 4* firmware and install the latest version of syncthing on it. when this is done I will see that I find a way out to get the latest tagged version and trigger the build process

**Comment by Daedalus3** [comment]
Thanks for all your work, guys! Does anyone of you have a newer build than ver. 0.11.2? @cuberoot74088 @MyPod ? ;-)

**Comment by cuberoot74088** [comment]
Hi @Daedalus3,  

here is **v11.8**:

https://www.dropbox.com/s/n0xdpglv1me4ut8/syncthing-linux-arm-v0.11.8%2B2-g197bfa9-noupgrade.tar.gz?dl=0

have fun.

**Comment by Daedalus3** [comment]
Awesome, thanks @cuberoot74088 !

**Comment by eljojo** [comment]
Hi everyone, through some posts in [google groups](https://groups.google.com/forum/#!topic/golang-nuts/29RraQ-t3gc) I found that compiling with the flags ``-ldflags "-R 65536" `` also works great!

**Comment by prodigy7** [comment]
Hi cuberoot74088,

can u support us with a current fresh version (0.11.23) of syncthing?

Other question is: Can u support me with a short howto how you compile go and following syncthing? I try some things but how ever I'm not able to compile go for arm meeting the requirements for compiling syncthing.

**Comment by rmoriz** [comment]
This is still an issue. "Western Digital My Cloud" NAS have a pagesize of 32768 (`getconf PAGESIZE`), other arm NAS have 64k. Hacking the go source is undocumented, looks like upstream doesn't care. :-(

**Comment by MyPod** [comment]
@rmoriz It is WD to have adopted a nonstandard solution to improve the performance of the NAS. Complaints should go to WD, not to Syncthing or Go. afaik it's a rather uncommon solution, and not all the ARM-based NAS use it.
As a side solution, someone with time and proper knowledge could take on himself to maintain a version of Go and/or Syncthing that runs on this kind of architecture

**Comment by rmoriz** [comment]
@MyPod It's a Go issue. Yes it especially affects NAS users of syncthing, rclone and other go-based "file/cloud" utilities. No, it's not only a WD thing. It also affects Zyxel and part of Synology NAS.

How to address the issue? IMHO two possibilities:

1) Go should make it either dynamic or at least an option on "go build"
2) synthing binaries for arm could be provided in different armv7 flavors (different page sizes). This would require a build setup with modified go toolchains for each `PAGESIZE`

In the meantime, synthing could provide a hint in the manual/on the download section that armv7 binaries will not work on many off-the-shelf NAS due to the bug in Go itself.

**Comment by MyPod** [comment]
I disagree, but you may ask Go devs to see if they accept contributions in this sense. I'm fairly certain that if someone offers to do the work and maintain it there's not much reason to say no.
Considering this is a free project and that there's both a hardware and time cost (in my experience emulated system such as qemu-user didn't work) to implement either solution, I'd not expect it to happen on its own, but only if users contribute.

**Comment by rmoriz** [comment]
@MyPod are you involved in any of that projects? It looks like these two comments are the very first of you on Github?

**Comment by MyPod** [comment]
@rmoriz scroll up and you'll find a version of syncthing and Go I built and packed, that could be used to bootstrap a more recent version. I am not involved neither with Go nor with Syncthing, aside being an user of the latter.

**Comment by canton7** [comment]
@rmoriz github user activity only goes back something like a week.
