### ISSUE TITLE
file conflict resolution function

### ISSUE THREAD

**Issue by back-lacking** [syncthing/syncthing#9280]
I want there to be a way within the syncthing web gui to help resolve file sync conflicts. I think this will be useful since it gives the user a choice on how they want to resolve the conflict, and it would help get rid of the sync conflict file. A 3rd party syncthing client (SyncTrayzor on Windows) already does this. 
There could be a little notice for indicating conflicting files. Clicking on the notice can give you an dialogue or window asking whether you want to keep the current file on the device, or to keep the conflicting file. It can also display a list of conflicting files and the entries in the list can be mass selected and then you can do the action to all of the selected files. 

I will come back later with screenshots demonstrating when I have access to my Windows machine.

**Comment by AudriusButkevicius** [comment]
Just showing some filename, sizes and modification times is often probably not enough information to make a decision, hence why we don't do it.

We by default prefer to keep the "latest" (in terms of mtime) file without the conflict suffix, if you know that is always what you want, perhaps the right solution is to just disable generation of conflict files and accept data loss for non-latest ones.

If we did do this, we'd pretty quickly have requests for implementing diffing/viewer functionality etc, which is can of worms, hence I'm not sure we should go there.

This is just my personal opinion, not the stance of the project.

**Comment by calmh** [comment]
Yeah, I actually also think this is not one of the things we want to improve at the moment. Sorry.

**Comment by back-lacking** [comment]
Ah, well rip
