### ISSUE TITLE
High CPU load after update to 1.27.1 (Docker health check)

### ISSUE THREAD

**Issue by chinagaofeng** [syncthing/syncthing#9283]
run in docker on synology, high CPU load after upate to 1.27.1, a lot "curl" process
![2od7sZ3s7J](https://github.com/syncthing/syncthing/assets/30225503/40d64916-fc7c-4902-8349-3f7f62573c66)
![QZfmrBvSKx](https://github.com/syncthing/syncthing/assets/30225503/7b76468b-4522-4458-a93c-9bc98be8ca6c)
![TIqoDJM0ZQ](https://github.com/syncthing/syncthing/assets/30225503/f2879f2e-751b-453b-af63-f383d697a9b8)

**Comment by calmh** [comment]
Syncthing doesn't call curl. You're looking for something else.

**Comment by bt90** [comment]
https://github.com/syncthing/syncthing/blob/935a28c9612b4134d49e13a57e15aaa432f031a3/Dockerfile#L52

Syncthing itself not, but the healthcheck of our container

**Comment by chinagaofeng** [comment]
docker stats the running image, show this----

![5FtWeUwocX](https://github.com/syncthing/syncthing/assets/30225503/771621a6-c970-4b37-a2d8-c0bd2f8e3eca)

**Comment by calmh** [comment]
Aha!

**Comment by calmh** [comment]
Nonetheless, that works for me, so no real idea here. Troubleshooting needs to be applied.

**Comment by calmh** [comment]
(To be clear, we cannot troubleshoot this. @chinagaofeng you need to figure out what's going on and what and then we can see if it's a bug or something local to your setup)

**Comment by cliffordwhansen** [comment]
I am also experiencing this issue (on my Synology NAS, 1813+), I have found that when I `exec` into the container all curl commands seem to hang,

```
silenus [~]$ docker exec -ti syncthing sh
/ # ps aux
PID   USER     TIME  COMMAND
    1 1026      0:00 /bin/syncthing
   17 1026      0:14 /bin/syncthing
  231 root      0:00 /bin/sh -c curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
  238 root      8:10 curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health
  239 root      0:00 grep -o --color=never OK
  243 root      0:00 /bin/sh -c curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
  249 root      6:51 curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health
  250 root      0:00 grep -o --color=never OK
  251 root      0:00 /bin/sh -c curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
  257 root      5:57 curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health
  258 root      0:00 grep -o --color=never OK
  259 root      0:00 /bin/sh -c curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
  265 root      4:45 curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health
  266 root      0:00 grep -o --color=never OK
  267 root      0:00 /bin/sh -c curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
  273 root      3:38 curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health
  274 root      0:00 grep -o --color=never OK
  275 root      0:00 /bin/sh -c curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
  281 root      2:42 curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health
  282 root      0:00 grep -o --color=never OK
  283 root      0:00 /bin/sh -c curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
  289 root      1:59 curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health
  290 root      0:00 grep -o --color=never OK
  291 root      0:00 /bin/sh -c curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
  297 root      1:22 curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health
  298 root      0:00 grep -o --color=never OK
  299 root      0:00 /bin/sh -c curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
  305 root      0:52 curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health
  306 root      0:00 grep -o --color=never OK
  307 root      0:00 /bin/sh -c curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
  313 root      0:27 curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health
  314 root      0:00 grep -o --color=never OK
  315 root      0:00 /bin/sh -c curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
  320 root      0:01 curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health
  321 root      0:00 grep -o --color=never OK
  322 root      0:00 sh
  328 root      0:00 ps aux
/ # killall curl
/ # ps aux
PID   USER     TIME  COMMAND
    1 1026      0:00 /bin/syncthing
   17 1026      0:14 /bin/syncthing
  322 root      0:00 sh
  330 root      0:00 ps aux
```
When running this URL with wget it works
```
/ # wget 127.0.0.1:8384/rest/noauth/health -O -
Connecting to 127.0.0.1:8384 (127.0.0.1:8384)
writing to stdout
{
  "status": "OK"
}
-                    100% |************************************************************************************************|    21  0:00:00 ETA
written to stdout
```

I have also tried to replicate this on my laptop, and it runs fine which leads me to believe it is `arch` related, there might be something wrong with the `curl` that was included

**Comment by bt90** [comment]
Could you try to execute this from within the container?

```sh
curl -fkLsS -m 2 -vvv 127.0.0.1:8384/rest/noauth/health
```

**Comment by chinagaofeng** [comment]
> (To be clear, we cannot troubleshoot this. @chinagaofeng you need to figure out what's going on and why, and then we can see if it's a bug or something local to your setup)

I'm not very familiar to linux and docker cli, so sorry for no further or deeper description to this bug. 

I just know that pull 1.27.0 and run, everything is ok. But the latest(1.27.1) no good

**Comment by cliffordwhansen** [comment]
```
/ # time curl -fkLsS -m 2 -vvv 127.0.0.1:8384/rest/noauth/health
^CCommand terminated by signal 2
real	6m 27.34s
user	3m 16.21s
sys	1m 58.28s
```

Doesn't seem to be doing anything, so I canceled it.

**Comment by calmh** [comment]
And using a shitload of CPU while doing nothing, nonetheless. 😕

**Comment by calmh** [comment]
Can we get a `docker inspect` output from a running container with this issue?

**Comment by bt90** [comment]
@cliffordwhansen does it work for any other URL?

e.g:

```sh
curl -fkLsS -m 2 -vvv http://icanhazip.com/
```

If that also fails, that would qualify it as an upstream issue.

https://github.com/alpinelinux/docker-alpine/issues

**Comment by cliffordwhansen** [comment]
Yes it does seem to be an upstream issue, I am getting the same result for all URLs when use curl, but wget works.

**Comment by calmh** [comment]
Well it still works for me and I bet a lot of other people, so I'm interested in the environment etc.

**Comment by ProactiveServices** [comment]
Might be worth dropping the `fsS` from the command, as these cause cURL to be quiet(er). 
`curl -kL -m 2 -vvv http://example.com/`

**Comment by bt90** [comment]
The docker parameters or docker compose config file would be particularly interesting.

**Comment by cliffordwhansen** [comment]
As per the link above I have logged a bug upstream, you can follow along there.

For completeness sake: https://github.com/alpinelinux/docker-alpine/issues/365

**Comment by calmh** [comment]
> This seems to be specifically Synology devices

Aha. So given that, I suspect that the CPU is too old or different to work with the Alpine image we currently ship.

**Comment by cliffordwhansen** [comment]
For everyone not following all the upstream threads, there was an issue found in one of the upstream libraries, there is a fix in place that will make its way down the stack soon.

**Comment by k0gen** [comment]
> For everyone not following all the upstream threads, there was an issue found in one of the upstream libraries, there is a fix in place that will make its way down the stack soon.

Could you please provide more details or references about the issue and fix? Thanks!

**Comment by 101100** [comment]
> Could you please provide more details or references about the issue and fix? Thanks!

This is what I understand after a quick look: `curl` uses `c-ares` which had [this issue](https://github.com/c-ares/c-ares/pull/661) that came about because the host OS kernel was an earlier version than `curl` was compiled on. The earlier host kernel did not have a function that the library expected it to have which caused it hang.
