### ISSUE TITLE
Is syncthing affected by recent linux ext4 corruptions? 

### ISSUE THREAD

**Issue by dgudim** [syncthing/syncthing#9285]
Here is what I am referring to:
https://lwn.net/Articles/954285/
https://news.ycombinator.com/item?id=38589389
https://news.ycombinator.com/item?id=38585189

I was using the problematic kernel for several days and I am wondering if the syncthing uses O_DIRECT with O_SYNC

Sorry for cluttering your issues

**Comment by calmh** [comment]
Nope.
