### ISSUE TITLE
Poor performance: Very long delay for just one changed file

### ISSUE THREAD

**Issue by ell1e** [syncthing/syncthing#9286]
I really often run into this scenario:

- Multiple devices, among them device A and device B, share a common folder with a common file Z

- The devices are in sync, only device A and B online.

- Now device B gets a new version of file Z (I change local contents)

Now rather often this happens:

1. After less than a minute, device B shows in the UI that: 1. device A is online and connected, 2. device A is out of sync regarding exactly one file, that being file Z, 3. status of device A is shown by device B as syncing, 0%.

2. Then nothing happens or changes for 10+ minutes.

This makes syncthing a huge pain for work documents when I want to leave the house and expect just a single, quick one updated file to be brought along so I can access it later. I get a bunch of files can take a while to figure out deltas etc., especially when also other devices are online at the time, but for above simple scenario it's hard for me to understand how this is justified.

The expected behavior would be that data transfer starts in under 5 minutes.

### Does your log mention database corruption?

not that I know of

### Include required information

1.27.1 and Linux on all devices involved (some of the devices offline at the time are Windows)

**Comment by calmh** [comment]
Yeah, that's not supposed to happen, and doesn't happen to me. You'll have to look at the logs on the receiving side to see what's taking time, potentially enabling one or more of the tracing options if nothing seems obvious but start with `--verbose`. Generally we do troubleshooting in the forum, so if this drags out beyond a simple log extract with something obvious in it, lets move things there.

**Comment by ell1e** [comment]
Is there a way to enable logging in the UI at the point the problem happens? While it's often, it's only often because I use syncthing a lot. I can't just launch it and make it do that, sadly. And I probably got too much workload to keep logging enabled without quickly running into storage issues.

I'm happy to do troubleshooting elsewhere, but I tend to avoid discourse because I personally think it has too many anti features that I consider quite user hostile design.

**Comment by calmh** [comment]
Yeah, be that as it may, we don't do troubleshooting or general discussion in the issue tracker.

I recommend running the problematic side with `--verbose` always. That will at least give you log entries for the timing of incoming updates and when the change actually gets handled. When you see a smoking gone, yell here to reopen and we'll take it from there.

**Comment by ell1e** [comment]
There seems to be some integrated log viewer, what "Debugging Facilities" would I need to check as an equivalent of `--verbose`? Sadly, [some comment suggests it truncates a lot](https://github.com/syncthing/syncthing/issues/9252#issuecomment-1837620583), I'm not sure if that will be a problem.

**Comment by ell1e** [comment]
I have a log file now of the one folder making zero sync progress in any direction for over 40 minutes. Other folders synced fine. Initially just 3 files were out of sync that were added on one side (the side I logged on, the slow device that wouldn't send these files out) but then I added an entire subfolder on the other side (not logged) with way more files and those aren't syncing either. It's just sitting there confused. Other folders have had changes while this is ongoing and immediately synced.

Where should I send the log? (It seems to me from taking a look inside it's maybe not the best to publicly attach it with the full device id and all the folder names and everything, sorry if I'm overly cautious)

**Comment by tomasz1986** [comment]
> Where should I send the log? (It seems to me from taking a look inside it's maybe not the best to publicly attach it with the full device id and all the folder names and everything, sorry if I'm overly cautious)

Device IDs are generally safe to make public, with the only caveat being that someone may try to use them to try connecting to your devices, but then you still need to accept such a connection anyway. You may shorten them, leaving only the first part. As for folder IDs, as long as they've been generated by Syncthing and not manually input, it's totally safe to share them as they are just random strings with no user/device-specific information attached to them.

On the other hand, folder and file paths/names can and often do contain private information. You may obfuscate them, e.g. "file1", "file2", etc.

**Comment by ell1e** [comment]
All my folder ids are manual and fairly descriptive, sadly :open_mouth:

**Comment by ell1e** [comment]
I still have the log file, if it ever turns out to be interesting. Github doesn't have private attachments, does it? But I could e-mail it somewhere too.

**Comment by ell1e** [comment]
For what it's worth, I tested with a higher [cpulimit parameter that I used due to #8439](https://github.com/syncthing/syncthing/issues/8394) and now this happens more rarely, so I suspect the issues might at least be partially connected. Although I have a gut feeling it's only a contributing factor making this way worse, the log still looks suspicious to me.

But I can't use a higher cpulimit because the battery drain is really too bad in that case. This is in part because I have 12 folders of which many are really large (multiple hundreds of gigabyte with multiple ten thousands of files), so even with the conservative hourly scan default there probably is a scan every ~5 minutes and since for many folders it takes multiple minutes there is basically always a scan going on. With lower cpulimit this is manageable, but with higher it isn't.

So it would likely be possible to at least make this less bad if there was a built-in CPU limit option that disabled itself with a charger plugged in since usually I run into this issue here with things getting stuck while at home, not on the run. I could of course always disable/re-enable cpulimit manually, but it's just not practical to do.

**Comment by ell1e** [comment]
For what it's worth, this keeps happening that I'm staring at two sides showing both the known out of sync and that they are connected, and it's just 2-3 files in one folder out of sync on one side, and nothing is happening. Then i restart, and it syncs immediately. I've noticed that when this happens, syncthing is often also seemingly broken in other ways, e.g. the UI show all folder as "Unknown", or sending SIGTERM will only make it shut down 2-3 minutes later, etc.
