### ISSUE TITLE
Right-To-Left language support.

### ISSUE THREAD

**Issue by shetozz** [syncthing/syncthing#9291]
### Include required information

Support displaying RTL languages in the GUI.

*I'm not sure if mirroring the whole UI would be necessary, we can try without mirroring it first if it's easier.*

Please be sure to include at least:
 - what problem your new feature would solve
>  It allows the inclusion of RTL languages. e.g., Arabic, Farsi, Urdu...etc.
 - how or why you think it is generally useful (i.e., not just for you)
>  I'm sure I'm not the only one speaking one of these languages (sorry for the sarcastic response if it isn't appropriate in this context)
 - what alternatives or workarounds you considered
>  I don't know if any exists.

**Comment by acolomb** [comment]
What exactly is not working with respect to RTL? There certainly are some translations for these languages already. The translation platform supports them alright. Not sure about our GUI framework.

**Comment by shetozz** [comment]
> What exactly is not working with respect to RTL? There certainly are some translations for these languages already. The translation platform supports them alright. Not sure about our GUI framework.

Currently, there's no option to set the GUI language to any of them, so there's no way to test what's broken exactly, but I filed this issue after this conversation on the forum https://forum.syncthing.net/t/translating-syncthing-on-weblate/19772/15?u=shetozz

**Comment by tomasz1986** [comment]
I'm guessing that there at least will be issues with table columns, truncation, button placement, etc. but I would like to wait for an RTL language to actually be available in the GUI to do any real testing.

**Comment by tomasz1986** [comment]
The Arabic language is now available as of Syncthing v1.27.2. Can you check how the GUI looks and what possibly needs to be improved regarding better RTL language support?

**Comment by shetozz** [comment]
It looks fine so far, I'll give it more time in testing and fix some translation mistakes, but you can close this issue for now.

**Comment by acolomb** [comment]
Thanks for checking. Feel free to report any issues turning up.

**Comment by shetozz** [comment]
Some letters in Arabic go below the line, and that messes up with dropdown menus.
It's not a big deal, but it looks a little finicky.

![Screenshot from 2024-01-09 13-30-36](https://github.com/syncthing/syncthing/assets/93838524/106f505f-469e-436e-bccf-ad8e759ff745)

![Screenshot from 2024-01-09 13-30-47](https://github.com/syncthing/syncthing/assets/93838524/1c8438f9-f5c7-4e31-a16f-a5d5b25afa1b)

**Comment by calmh** [comment]
I guess see if there's some specific spacing things applied that would cause this. We might also consider trying to upgrade to a newer bootstrap... 😰

**Comment by tomasz1986** [comment]
> We might also consider trying to upgrade to a newer bootstrap... 😰

I actually did try to upgrade to Bootstrap 4 locally a few months ago, but it broke basically all our custom styling and also the whole GUI looked very different visually by default, so it would likely require quite a lot of work to make it look the same as the current one.

For the time being, it may be easier to just add some CSS hacks for RTL languages specifically 😉.

**Comment by acolomb** [comment]
@tomasz1986 Do you have any code from that experiment that you could publish?  I don't think we need to aim to "make it look the same as the current one", but I'd like some idea how much different it would be.

Upgrading looks would definitely be more worthwhile than manually fiddling with RTL tweaks, IMHO.  At least *if* the newer Bootstrap gives us better support in that area.  So far I've only seen font issues (not really RTL related), and of course the wrong alignment (should be right-justified by default I think, judging by how Weblate displays the strings).

**Comment by tomasz1986** [comment]
The code is long gone, but what I did was basically replacing the Bootstrap 3 assets with Bootstrap 4, opening the Web GUI, seeing how very different it was and realising how much time would be required to make it look decent, and then giving up on the idea for the time being.

I also don't really know whether Bootstrap 4 actually improves anything regarding RTL. It may very well not, because proper RTL support is usually something that is very hard to implement, especially if it wasn't taken into consideration from the very beginning (and with none of the developers speaking any RTL languages).

**Comment by shetozz** [comment]
> @shetozz Which dropdown menu is that specifically?

This specific one is the auto-update thing, but all dropdown menus behave similarly.

**Comment by shetozz** [comment]
Another broken part about RTL support is bidirectional lines that have English in the middle, it messes up the arrangement and terns the whole line to gibberish.
***
*This image is not the worst as it's still understandable, but it is the only one I can explain simply to non-Arabic speakers, `QR.` should be all the way to the right*
![Screenshot from 2024-01-11 19-23-10](https://github.com/syncthing/syncthing/assets/93838524/1655b187-0c07-455b-97e2-48b23556138a)
