### ISSUE TITLE
File names containing asterisk won't sync to other devices

### ISSUE THREAD

**Issue by siddAhmed** [syncthing/syncthing#9298]
### Does your log mention database corruption?
no

###  Which version of Syncthing and what operating system you are using
- Syncthing version: syncthing v1.27.0 "Gold Grasshopper" (go1.21.4 linux-amd64) debian@github.syncthing.net on Linux Mint 20.3 Una
### Browser and version, if applicable
- Version 120.0.6099.71 (Official Build) (64-bit)
### What happened
- A newly created note (file) in the obsidian app named **A\* Algorithm** wouldn't sync to my other device (android). Removing the \* from the file name worked.
### What you expected to happen instead
- I expected to see the new note created in my android device
### Steps to reproduce the problem
- Create a file containing the asterisk (\*) special character with `.md` extesion, check if it syncs to other devices

**Comment by calmh** [comment]
Syncthing handles the asterisk fine; Android, however doesn't allow it. So it's not possible to have a file named liked that on Android.
