### ISSUE TITLE
go runs main.go in syncthing and reports an error

### ISSUE THREAD

**Issue by linyjme** [syncthing/syncthing#9299]
![image](https://github.com/syncthing/syncthing/assets/49971305/a3c85070-7057-458f-b531-7ef029a78ebb)

Why do I use go 1.20 version and have run go mod tidy to download the go library, but when I run main.go in the syncthing directory, I get an error saying that the global variable l in debug.go is undefined. What is the reason?

**Comment by calmh** [comment]
Hi! That's not how you build or run a larger Go program. I suggest you read up on https://go.dev/learn/ or, for building Syncthing specifically, https://docs.syncthing.net/dev/building.html
