### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by DonQuiProgger** [syncthing/syncthing#9300]
syncthing v1.27.1 "Gold Grasshopper" (go1.21.5 linux-amd64) syncthing@archlinux 2023-12-11 07:43:23 UTC [noupgrade]

[panic-20231221-163416.reported.log](https://github.com/syncthing/syncthing/files/13743600/panic-20231221-163416.reported.log)

**Comment by calmh** [comment]
Duplicate of #9274

**Comment by calmh** [comment]
v1.27.2-rc.1 has a fix if this is recurring and painful

https://github.com/syncthing/syncthing/releases/tag/v1.27.2-rc.1
