### ISSUE TITLE
Reverse syncing partially synced file overwrites original file 

### ISSUE THREAD

**Issue by marwan4mr** [syncthing/syncthing#9304]
- which version of Syncthing and what operating system you are using -  v1.27.1 - latest windows 10 pro 
 - browser and version, if applicable - syncthing  tray 
 - what happened, - i was learning how to use the app and i wanted to share i big from pc to android but disconnected while syncing and by mistake i shared what i synced in my phone and with was 5% of the whole folder and everthing except the synced got deleted on the pc and replaced by the 5% that was synced on the phone 
 - what you expected to happen instead, and - i expcected that reverse sync  should not happen and there should be warning for such case 
 - any steps to reproduce the problem - partial sync then sharing the synced partial sync will overwrite the original file and deleted with no apparent way to  restore it .

**Comment by calmh** [comment]
I don't particularly follow what you say happened here. There's no "reverse sync of partial files", partial files are stored as (ignored) temp files until they're complete.

**Comment by marwan4mr** [comment]
it doesn't happen during normal flow but by mistake I shared the partially synced file from the destination to the source and it overwrite it and in both folders have only the 5% synced everything else got deleted.

**Comment by calmh** [comment]
What do you mean, "by mistake I shared the partially synced file", how did you do that exactly?

**Comment by marwan4mr** [comment]
1- I synced photos folder from my pc to my android which is 500gb
2- it went to 40gb then I stopped the sync
3- I removed the shared folder
4- I forgot how to (Add Folder) sync the file and by mistake went to the android and pressed create folder and added the partially synced folder from my phone storage 
5-the sync was complete very fast and showed only 40gb on pc and when I checked all other files except synced files are deleted 
6- I realized I needed to add the folder from the source (pc) not the destination, but all the data was already overwritten

(sorry if my explanation wasn't clear my English isn't my first language, also this happened right after installing the app when I was learning how to use it)

**Comment by calmh** [comment]
I think this is an effect of newly created folders on Android being set to send-only, and then an unfortunate sequence of button presses. I don't think it's a bug here.

**Comment by tomasz1986** [comment]
New folders, even though created through the app interface, default to Send & Receive actually. Only the default Camera folder is initially set to Send Only.

**Comment by imsodin** [comment]
There's not enough resp. clear information to recreate the issue or understand the exact sequence of events and their outcome. If you still have issues, please take them to the forum - https://forum.syncthing.net - so things can be clarified there. And if a potential bug is found, a ticket with the detailed and concise info from that can be created. Thanks.
