### ISSUE TITLE
Question: Cloud storage integration

### ISSUE THREAD

**Issue by seanstardev** [syncthing/syncthing#9307]
Preamble: I have just discovered Syncthing and I am amazed by the technology. Congratulations to all involved.

Would you consider adding the ability to sync files with Cloud services (DropBox, OneDrive, Google Drive) alongside the P2P setup that currently exists?

I believe this addition would expose Syncthing in the retro-gaming community. We are looking for ways to keep our saves, game screenshots, and playtime data uptodate across Windows, Linux and Android. We don't believe anything can get us closer to that dream than Syncthing :)

Thank you very much for reading this and for the incredible software you have delivered.

**Comment by nekr0z** [comment]
This has been discussed (and declined) numerous times. If you feel like adding a new perspective to the discussion, you're welcome, but please use [the forum](https://forum.syncthing.net) for that.

**Comment by seanstardev** [comment]
> This has been discussed (and declined) numerous times. If you feel like adding a new perspective to the discussion, you're welcome, but please use [the forum](https://forum.syncthing.net) for that.

I apologise. I thought I'd done a thorough search of this forum before posting, and was not aware of this other forum's existence. I will do exactly what you suggest. Thank you very much for your time.
