### ISSUE TITLE
IP networking via USB

### ISSUE THREAD

**Issue by RustoMCSpit** [syncthing/syncthing#9311]
I want to be able to plug a USB C between my phone and laptop and have Syncthing sync its files, even when I have no internet.

**Comment by calmh** [comment]
I'm sure you can, if you somehow set up an IP network over that cable. It is not in scope for Syncthing itself to run some sort of special protocol directly over USB, unfortunately.

**Comment by RustoMCSpit** [comment]
>I'm sure you can, if you somehow set up an IP network over that cable

would you have to do that each time you plug it in?

**Comment by RustoMCSpit** [comment]
>It is not in scope for Syncthing itself to run some sort of special protocol directly over USB, unfortunately.

Is it not the same concept somewhat, I mean have you ever been in a situation where you can't transfer wirelessly?
