### ISSUE TITLE
LAN only mode

### ISSUE THREAD

**Issue by RustoMCSpit** [syncthing/syncthing#9312]
Syncthing Android allows for the user to have it so that the files only transfer over LAN and never by WAN. Allow that for desktop too

**Comment by calmh** [comment]
You can set `allowedNetworks` for a device to 192.168.0.0/24 or whatever your LAN happens to be.

**Comment by RustoMCSpit** [comment]
> You can set `allowedNetworks` for a device to 192.168.0.0/24 or whatever your LAN happens to be.

LAN changes depending on what WIFI I'm connecting too, that's a workaround

**Comment by RustoMCSpit** [comment]
@calmh is this virtually a duplicate of https://github.com/syncthing/syncthing/issues/8394 ?
