### ISSUE TITLE
Different lengths used for short device IDs in UI

### ISSUE THREAD

**Issue by KeyWeeUsr** [syncthing/syncthing#9313]
### Does your log mention database corruption?
No

### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using
   - 1.27.1, but it's even in `main`
 - what happened
   - IDs are of different length from API and in client in specific sections
 - what you expected to happen instead
   - same-length IDs

https://github.com/syncthing/syncthing/blob/86a08eb87df2aa6cf1ab631120a0b918617a98b3/lib/protocol/deviceid.go#L18 says 7 and therefore from, let's say `/rest/system/connections` I get first 7 characters as if split on `-`
https://github.com/syncthing/syncthing/blob/86a08eb87df2aa6cf1ab631120a0b918617a98b3/gui/default/syncthing/core/syncthingController.js#L1476 and https://github.com/syncthing/syncthing/blob/86a08eb87df2aa6cf1ab631120a0b918617a98b3/gui/default/syncthing/core/syncthingController.js#L1493 however https://github.com/syncthing/syncthing/blob/86a08eb87df2aa6cf1ab631120a0b918617a98b3/gui/default/syncthing/core/syncthingController.js#L1463 has the matching one and https://github.com/syncthing/syncthing/blob/86a08eb87df2aa6cf1ab631120a0b918617a98b3/gui/default/index.html#L913 has even less than both - `5`

Shouldn't it be the same everywhere? Would you welcome a patch or is this something you are aware of and it's kept because of some backward compatibility reason?

**Comment by imsodin** [comment]
That very much looks unintentional indeed. And at first glance it's all "presentation" strings, so no other logic should depend on it. As in yes, a patch would be welcome.
