### ISSUE TITLE
Add go generated assets to git repository 

### ISSUE THREAD

**Issue by pdg** [syncthing/syncthing#9315]
Please consider committing go generated files to the git repo so they won't have to be generated on build time.  

I'm trying to use syncthing with [gokrazy](https://gokrazy.org/).  Currently this fails because of the asset generation step on build time. 
Following files get generated when running `go  run -v build.go assets`. It would be great if those could be included in the git repo:

* cmd/strelaypoolsrv/auto/gui.files.go
* lib/api/auto/gui.files.go

Syncthing is an amazing piece of software. Thank you so much for your work.

----

References

[Michael Stapelberg in gokrazy Issue 208](https://github.com/gokrazy/gokrazy/issues/208#issuecomment-1641525389):  
> "In Go, generation of any sort (typically with the go generate command) is supposed to be done by the developers, with the result committed to source control."   

[Stackoverflow: Should a developer commit Go generated code?](https://stackoverflow.com/questions/56415527/should-a-developer-commit-go-generated-code):
> "In general, yes"

**Comment by calmh** [comment]
Committing generated code is a sound principle; we do so where appropriate, like for all the generated protobuf stuff. However, we're talking about five megabytes of binary crap that changes in its entirety on every GUI commit. I'm quite sure we don't want to commit that, sorry. Running our generation step prior to whatever other thing you're doing is way forward here.

**Comment by pdg** [comment]
Thanks for your explanation.
