### ISSUE TITLE
folders identified as files fail to sync: puller, rename, directory

### ISSUE THREAD

**Issue by gerardbriscoe** [syncthing/syncthing#933]
Have been using synching for a while and it works very well, except for the following issue which I suspect is probably mac specific. Syncing a folder between two macs, some 'files' fail to sync, because they are actually 'folders/directories' which I think is causing confusion to syncthing. I am using the latest version, and sample output of the problem is shown below:

"14:16:56: puller: final: rename /Users/g/Desktop/Financial/InfoLoad/.syncthing.Edinburgh.numbers /Users/g/Desktop/Financial/InfoLoad/Edinburgh.numbers: is a directory

14:16:57: puller: final: rename /Users/g/Desktop/Financial/Synergize/.syncthing.Lancaster.numbers /Users/g/Desktop/Financial/Synergize/Lancaster.numbers: is a directory

14:16:57: puller: final: rename /Users/g/Desktop/Financial/Seasonal/.syncthing.Forres.numbers /Users/g/Desktop/Financial/Seasonal/Forres.numbers: is a directory

14:16:57: Folder "Financial" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.

The 'files' are Apple iWork Numbers spreadsheet files (as identified on the mac os x finder), but I have confirmed from the command line that they are in fact 'directories'. Is there a simple configuration change I can make to help synching recognise that they are folders are not files (assuming that is the problem)?

**Comment by MartinAyla** [comment]
I still get this error with .sketch files (which are actually folders/containers).

I'm using 0.10.21 on all my machines (OS X 10.10).

Any ideas?

**Comment by AudriusButkevicius** [comment]
Have you tried the posted workarounds?
