### ISSUE TITLE
File Path resets to Tilde instead of the specified one. (different drive letter)

### ISSUE THREAD

**Issue by thenotorious42** [syncthing/syncthing#9330]
Syncthing 1.27.2 running on Windows 10 Pro Version 1903.
Browser Firefox, newest version (sorry for impreciseness.)

I had the problem before and have it again after reinstalling Syncthing on both my Android Phone and my computer.
The problem is that Syncthing does not remember the filepath I specified for my folders, and thus cannot find them when I try to sync for the second time after some days. The exact time of occurence or reason of the bug is unknown to me.
Fact is, Snycthing looks for folder this way now: ~\Pictures which is C: drive), but I specifically set the file path when creating to H:\Syncthing. The web overlay shows my specified file path nowhere now.

Please inform me when the error is fixed, then I will gladly use Syncthing again!

**Comment by tomasz1986** [comment]
The issue isn't really clear at this point. Please create a new topic at https://forum.syncthing.net with the same content, and please also include screenshots of all the errors that you are seeing on the screen.
