### ISSUE TITLE
uses different upper or lowercase characters

### ISSUE THREAD

**Issue by a-reznic** [syncthing/syncthing#9338]
error 
syncing: finishing: checking existing file:
remote "DSC03540.JPG" uses different upper or lowercase characters than local "DSC03540.jpg"; change the casing on either side to match the other
 
 sync:  ubuntu -> windows

**Comment by calmh** [comment]
Yeah, you can't have both of those on Windows, you need to decide on one or the other.

This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
