### ISSUE TITLE
Set `GOMAXPROCS` quota aware in Linux containers

### ISSUE THREAD

**Issue by bt90** [syncthing/syncthing#9357]
We currently set `GOMAXPROCS` to the available number of CPU cores if nothing is explicitly configured by the user:

https://github.com/syncthing/syncthing/blob/35e153625ce5139e2d30b36a0557b5e7a1e81ba0/cmd/syncthing/main.go#L654-L656

This doesn't play very nice with CPU quotas. See https://github.com/golang/go/issues/33803

A possible solution might be https://github.com/uber-go/automaxprocs

```go
 if os.Getenv("GOMAXPROCS") == "" { 
 	maxprocs.Set(maxprocs.Logger(log.Printf))
 } 
```

We can even get away with a simple import, because automaxprocs [honors](https://github.com/uber-go/automaxprocs/blob/c9adbb9be700880d75fad74117eda9cf3ea6211a/maxprocs/maxprocs.go#L96-L103) `GOMAXPROCS` by default:

```go
import _ "go.uber.org/automaxprocs"
```

A blog post which covers this topic: https://www.riverphillips.dev/blog/go-cfs/

**Comment by calmh** [comment]
What we do is a no-op since many years since the default is to use all CPU cores. It should just be removed since it does nothing.

I honestly don't think we should be doing anything clever here. If the (obviously quite knowledgeable) user is deploying containers with CPU limits rust can also set GOMAXPROCS...

**Comment by bt90** [comment]
> If the (obviously quite knowledgeable) user is deploying containers with CPU limits rust can also set GOMAXPROCS...

Adding `--cpus="2"` isn't rocket science. And even a knowledgeable user might overlook that golang isn't cgroup aware. Point in case: I did

(even Java cgroup aware, wtf Google?)
