### ISSUE TITLE
Panic on RHEL 8.9 - opensslcrypto: invalid code execution

### ISSUE THREAD

**Issue by greenman1969** [syncthing/syncthing#9364]
Syncthing Version 1.27.1 on Hardened RHEL 8.9 server (SELinux and FAPolicyD are both disabled to ensure it wasn't them) and internet disconnected
Browser not applicable, not getting that far
What happened: on first startup syncthing panics and puts the below information in to the panic log:
[start] INFO: syncthing v1.27.1 "Gold Grasshopper" (go1.20.10 linux-amd64) mockbuild@fedora-koji 1970-01-01 00:00:00 UTC
[start] INFO: Generating ECDSA key and certificate for syncthing...
...
Panic at 2024-01-22T12:31:22-06:00
panic: opensslcrypto: invalid code execution

goroutine 1 [running]:
crypto/internal/backend.UnreachableExceptTests()
        /usr/lib/golang/src/crypto/internal/backend/openssl.go:51 +0x105
crypto/ecdsa.GenerateKey({0x55c372864b20, 0x55c372f61380}, {0x55c372855500?, 0xc00007c640})
        /usr/lib/golang/src/crypto/ecdsa/ecdsa.go:164 +0x1d2
github.com/syncthing/syncthing/lib/tlsutil.generateCertificate({0x55c3720929eb, 0x9}, 0x1c84)
        /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/tlsutil/tlsutil.go:91 +0x85
github.com/syncthing/syncthing/lib/tlsutil.NewCertificate({0xc00003cac0, 0x33}, {0xc00003c940, 0x32}, {0x55c3720929eb?, 0x55c3718f2ae6?}, 0xc000161e00?)
        /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/tlsutil/tlsutil.go:134 +0x87
github.com/syncthing/syncthing/lib/syncthing.GenerateCertificate({0xc00003cac0, 0x33}, {0xc00003c940, 0x32})
        /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/syncthing/utils.go:58 +0x12b
github.com/syncthing/syncthing/lib/syncthing.LoadOrGenerateCertificate({0xc00003cac0, 0x33}, {0xc00003c940, 0x32})
        /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/syncthing/utils.go:51 +0x138
main.syncthingMain({{{0x0}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0}, 0x0, 0x0, {0x0, ...}, ...})
        /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:547 +0x1ab
main.serveOptions.Run({{{0x0}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0}, 0x0, 0x0, {0x0, ...}, ...})
        /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:416 +0x898
reflect.Value.call({0x55c3728354e0?, 0x55c372fe0ee0?, 0x55c3726129f0?}, {0x55c3720899cf, 0x4}, {0xc0002d3bc8, 0x0, 0x55c3716d3cf4?})
        /usr/lib/golang/src/reflect/value.go:586 +0xb07
reflect.Value.Call({0x55c3728354e0?, 0x55c372fe0ee0?, 0x55c372701560?}, {0xc0002d3bc8?, 0x0?, 0x182?})
        /usr/lib/golang/src/reflect/value.go:370 +0xbc
github.com/syncthing/syncthing/vendor/github.com/alecthomas/kong.callFunction({0x55c3728354e0?, 0x55c372fe0ee0?, 0x1?}, 0x55c3720893cb?)
        /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/vendor/github.com/alecthomas/kong/callbacks.go:98 +0x445
github.com/syncthing/syncthing/vendor/github.com/alecthomas/kong.(*Context).RunNode(0xc000150180, 0xc00015a0f0, {0x0, 0x0, 0x0})
        /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/vendor/github.com/alecthomas/kong/context.go:765 +0x5df
github.com/syncthing/syncthing/vendor/github.com/alecthomas/kong.(*Context).Run(0x55c372679a20?, {0x0?, 0xc000110b28?, 0x55c37266a060?})
        /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/vendor/github.com/alecthomas/kong/context.go:790 +0x14e
main.main()
        /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:260 +0x3d6

goroutine 36 [chan receive]:
github.com/syncthing/syncthing/vendor/github.com/syncthing/notify.(*nonrecursiveTree).dispatch(0xc0002002a0, 0xc00011eba0?)
        /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/vendor/github.com/syncthing/notify/tree_nonrecursive.go:36 +0x45
created by github.com/syncthing/syncthing/vendor/github.com/syncthing/notify.newNonrecursiveTree
        /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/vendor/github.com/syncthing/notify/tree_nonrecursive.go:29 +0x16a

goroutine 37 [chan receive]:
github.com/syncthing/syncthing/vendor/github.com/syncthing/notify.(*nonrecursiveTree).internal(0xc0002002a0, 0xc000200240)
        /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/vendor/github.com/syncthing/notify/tree_nonrecursive.go:81 +0x53
created by github.com/syncthing/syncthing/vendor/github.com/syncthing/notify.newNonrecursiveTree
        /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/vendor/github.com/syncthing/notify/tree_nonrecursive.go:30 +0x1be

goroutine 41 [sleep]:
time.Sleep(0x1dcd6500)
        /usr/lib/golang/src/runtime/time.go:195 +0x137
github.com/syncthing/syncthing/lib/dialer.init.1.func2()
        /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/dialer/internal.go:43 +0x1e
created by github.com/syncthing/syncthing/lib/dialer.init.1
        /builddir/build/BUILD/syncthing/_build/src/github.com/syncthing/syncthing/lib/dialer/internal.go:42 +0x136

What I expect to happen: I wasn't expecting an error
Reproduce steps: Install via dnf and attempt to start via systemd.

**Comment by calmh** [comment]
Does the same thing happen with one of our binaries from Github?

**Comment by greenman1969** [comment]
That seems to have fixed it. I was hoping to be able to use RPM for easy updates in the future but I can make it work with the archive. I also tested the 1.27.2 RPM and it had the same error so it's either the rpm package or the system I'm installing it on.

Thank you!

**Comment by calmh** [comment]
The I guess redhat broke it, unfortunately.
