### ISSUE TITLE
File Drop mode

### ISSUE THREAD

**Issue by DanHolli123** [syncthing/syncthing#9373]
### Introduce a "File Drop" folder type

would function similar to the "Send Only" option but after file is successfully synced it gets deleted from the source but not from other devices effectively acting as a move operation from one drive to another

This would be useful for me as I host a Plex server for my family and they rip their own movies and I host for them. It can be useful for other applications especially when dealing with larger files on devices with limited storage (move into storage when complete) or as a cross device file drop

I tried looking for alternatives but I couldn't find any (especially since the typical name for something like this is a drop box, but most people are familiar with the cloud storage provider with the same name) except a feature of Google Drive, which isn't preferable for privacy reasons. a potential work around would be to use some script to check for sync status and when complete add the file to the ignore file and then delete the source file but I don't have the know-how to make it happen

**Comment by imsodin** [comment]
This comes up quite often - not that easy to search for though it seems. Only thing that reasonably applies that I could find was this: https://forum.syncthing.net/t/setup-from-seedbox-to-nas/18602 You can open a new topic on the forum and I am sure other's will remember better topics. Or just help you anew right there and then.  
The gist is that the behaviour you describe isn't what syncthing's intent is - it's continuous bi-directional sync. However you can still use syncthing as is for this use-case, and let something else do the managing/archival (here probably plex). Given this is a support request, please use the forum - https://forum.syncthing.net/ - to get more help with this. The forum has a lot more eyes and friendly people on it than the issue tracker.

**Comment by DanHolli123** [comment]
I found an Altenative solution:
use Syncthing to sync files both ways then use DropIt to move files from a "drop folder" to where it needs to be
so long as you don't need to deal with folders, it works well
