### ISSUE TITLE
Out of sync items not progressing

### ISSUE THREAD

**Issue by AndiDog** [syncthing/syncthing#9374]
### Does your log mention database corruption?

No

### Include required information

- Syncthing 1.27.2, Linux on Raspberry Pi 4, read-write mounted NTFS filesystem on external drive
- I had some file permission trouble with the badly-maintained ntfs3 filesystem on Linux where it wouldn't respect user/group/chmod flags and Syncthing failed to sync a few files (but not all). Therefore, I changed my disk mount back to ntfs-3g where permissions are much easier to handle.
- Now I have folders with thousands of "Out of Sync Items" shown, but that number doesn't go down. When looking at the state of one affected file with `curl --fail-with-body -s -X GET -H "X-API-Key: ${apikey}" "http://127.0.0.1:8384/rest/db/file?folder=xxx&file=foobar/whatever.jpg"`, the objects `global` and `local` are identical. So I wouldn't even expect that Syncthing transfers any changes.
- Restarting Syncthing didn't help. Toggling "Ignore file permissions" to force a rescan didn't help. Nothing in the logs.
- `touch`-ing an affected file makes its modification timestamp get actively synced and therefore reduces the total "out of sync" count by one. Not a great solution because I don't want to rewrite each file's timestamp. `touch -a` (only access timestamp) does nothing – I guess Syncthing only cares about modification timestamp which is reasonable.
- In the GUI (see screenshot below)

  - Lots of out-of-sync items shown for transfer to a macOS-based Syncthing peer of the same version. Clicking it shows a dialog listing affected files, but no further hints.
  - On the left-hand side (_Folders_ widget), no file transfers are shown.

![Screenshot 2024-01-28 at 13 50 03 - combined](https://github.com/syncthing/syncthing/assets/1376043/5d7bc01a-714a-4536-be41-e607e68bbf58)

Is there a way to reconcile the database/state, since both local and global files are already identical? I couldn't find a REST API endpoint to enforce that. [`FolderSummary`](https://docs.syncthing.net/events/foldersummary.html) of the Events API seems to contain the out-of-sync items but I have no idea how to change that state. My idea is to bump the files' sequence number in the Syncthing database, or fix the bug overall by having Syncthing mark files as synced once they're identical.

I have no way to create a reproducible issue, but maybe I can provide some API or database state if that helps.

**Comment by AudriusButkevicius** [comment]
Hi,

Please reopen this on the forum, under support section. Could be the infamous index exchage bug we've been tracking down forever. Or could be generally bad state due to perms changing and the other side not being able to handle them. Post screenshots from both sides on the forum.


Thanks.
