### ISSUE TITLE
why paush button Disappeared and the version is unknown-dev, Linux (64 bit)? 

### ISSUE THREAD

**Issue by 578321069** [syncthing/syncthing#9378]
![image](https://github.com/syncthing/syncthing/assets/73280585/f02920b0-7c4c-4c4f-9660-ea61f3261f4c)

**Comment by calmh** [comment]
You're using an odd build of some kind. Try one of our binaries: https://github.com/syncthing/syncthing/releases/tag/v1.27.2

**Comment by 578321069** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
