### ISSUE TITLE
Network monitoring tools show syncthing connecting to strange external domains?

### ISSUE THREAD

**Issue by dralley** [syncthing/syncthing#9381]
### Does your log mention database corruption?

No

### Include required information

Syncthing installed on Fedora 39

> Name         : syncthing
> Version      : 1.27.2
> Release      : 1.fc39
> Architecture : x86_64
> Size         : 25 M
> Source       : syncthing-1.27.2-1.fc39.src.rpm

Using the `bandwhich` tool shows that the syncthing process is making connections out to seemingly random domains that I've never seen before such as:

`monroe.tomsobecki.com`
`mail.1234000.xyz`

![Screenshot from 2024-01-31 14-44-13](https://github.com/syncthing/syncthing/assets/2751996/7aa3b2d2-e59d-4faa-b919-4471eaa66692)

![Screenshot from 2024-01-31 15-26-18](https://github.com/syncthing/syncthing/assets/2751996/da5376a8-92b6-447d-ab88-96e42e46e591)

Wireshark shows the same traffic but I'm not sure if you can show the process attribution - first time using Wireshark

![Screenshot from 2024-01-31 15-03-37](https://github.com/syncthing/syncthing/assets/2751996/a94bff40-2af9-45fa-a7bb-91928672d798)

And specifically what was interesting is that after restarting the process with `systemctl --user restart syncthing` it switched from the former to the latter address, I don't think I saw any further traffic to `monroe.tomsobecki.com` but `mail.1234000.xyz` which I had not previously got a TCP connection.

**Comment by bt90** [comment]
Most likely one or more of our relay servers:

https://relays.syncthing.net/

**Comment by dralley** [comment]
That does seem like a plausible scenario, the ip addresses do show up in the relay server list.  What are relay servers and exactly what kind of traffic do they handle?

**Comment by dralley** [comment]
nvm https://docs.syncthing.net/users/relaying.html
