### ISSUE TITLE
Local discovery broken on android

### ISSUE THREAD

**Issue by genevieve-me** [syncthing/syncthing#9382]
#### Does your log mention database corruption?

No.

### Include required information

Please be sure to include at least:

 - Laptop: v1.27.1, Linux (64-bit Intel/AMD)
 - Phone: v1.27.2, android (64-bit ARM)

Issue:
 - Other devices on my network are able to make local connections, but can only connect to my android device over "Relay WAN"
 - Since local connections work on my network, this seems to be an issue with syncthing on android. I know this was supposed to be fixed in https://github.com/syncthing/syncthing/pull/9087 (I believe that this fix came out in 1.25).

I reproduced by starting with a completely clean installation of syncthing on my phone and laptop (no configuration, fresh folder, etc.) and scanning the QR code for my laptop on my phone.

On my laptop, I see 3/3 listeners and 5/5 discovery. On my phone, I have 3/3 and 4/5 (missing: `ipv6 local: route ip+net: netlinkrib: permission denied`). However this shouldn't prevent local connection over ipv4.

Laptop log: 
[st-log-laptop.txt](https://github.com/syncthing/syncthing/files/14118690/st-log-laptop.txt)

Phone log: 
[st-log.txt](https://github.com/syncthing/syncthing/files/14118680/st-log.txt)

Thanks!

**Comment by bt90** [comment]
My gut feeling is that syncthing is running in some kind of container on your Linux host. Any kind of NAT breaks the workaround we came up with for the app.

As this id going to turn into a support topic, let's head over to our forum: https://forum.syncthing.net/
