### ISSUE TITLE
Support "push" style Prometheus metrics

### ISSUE THREAD

**Issue by lapo-luchini** [syncthing/syncthing#9405]
b9c08d3814685bc8c4a322756e042b9852e321b4 is super-nice to have, but since most Syncthing instances are listening to 127.0.0.1 by default (and it makes sense that they do, just to be sure) and moreover many instances can be roaming across different network (e.g. laptops) it is a bit difficult to scrape from any central Prometheus (or any compatible server, e.g. I prefer to use _Victoria Metrics_ myself).

It could make sense to add support for a "push gateway" server ([also supported by Victoria Metrics agent](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3745)), it would entail a single (opt-in) URL in the configuration with the server address and it would send the same format that is currently exposed.

Example given [in prometheus/client_golang sources](https://github.com/prometheus/client_golang/blob/main/prometheus/push/examples_test.go).

If it is a feature that would have a change at being included, I can try and produce a PR for it.

**Comment by calmh** [comment]
I'm sceptical. This is an unusual feature I think -- I have *lots* of things that expose metrics Prometheus style, none I've seen that support push out of the box. I would typically run something like Grafana Agent close the metric sources to collect them and push them to some Prometheus/Mimir/Thanos/whatever thing higher up...

**Comment by lapo-luchini** [comment]
Yeah, I'll probably install a local `vmagent` (and `node_exporter` as I want to know exact free space on disk).
Still, would be fairly easy to implement and could come in handy especially on laptops with limited resources.
But I see the "feature creep"…

**Comment by AudriusButkevicius** [comment]
Push metrics are horrible, because there is no notion of "the other end is gone", it leads to horrible dashboards where the metrics are incomprehensible.
