### ISSUE TITLE
Link to the main site on the description for the GitHub repo

### ISSUE THREAD

**Issue by alex-k-exe** [syncthing/syncthing#9415]
![Screenshot_20240213-064114.png](https://github.com/syncthing/syncthing/assets/101605664/e5af1eca-2cb2-4b4e-8653-f4fe52cf3889)

[https://syncthing.net/](https://syncthing.net/) instead of [https://forum.syncthing.net/](https://forum.syncthing.net/)

Would be less confusing for someone visiting the repo for the first time

**Comment by imsodin** [comment]
Yeah, why not IMO - I'll change it. Easily/chickly reverted @calmh or @AudriusButkevicius if you see any reason to keep the status quo.   

(Going through `needs-triage` tickets :) ).
