### ISSUE TITLE
In windows os, the accuracy of file modification time is 100ns，but in syncthing db,  the accuracy of file modification time is 1ns, I don't know if this is a bug ?

### ISSUE THREAD

**Issue by FaerieLee** [syncthing/syncthing#9423]
### Description
In func Lstat of file basifs.go, FileInfo.Modtime() is right and the  accuracy is 100ns. But when return from Lstat, the func walk in file walkfs,go, FileInfo.Modtime() is wrong, FileInfo.Modtime()(walkfs) = FileInfo.Modtime()(basicfs) + random number, and random number for same file is always same in different time when scanning. I don't understand why this happens. Looking forward to your reply. Thanks

**Comment by calmh** [comment]
Database times are stored with 1 ns precision regardless of the filesystem. We don't add anything random. Not sure what you're seeing that you think is a bug.

**Comment by FaerieLee** [comment]
I read the relevant code of mtimefs and I know the reason. Thank you. I have no doubts now
