### ISSUE TITLE
Custom folder locations for incoming shares

### ISSUE THREAD

**Issue by daxm** [syncthing/syncthing#9426]
# Custom Folder Path value for each Remote Device

## Issue
I have a situation where multiple computers have folders I wish to share with a "central" computer (basically my backup computer).  I'd like the ability to be able to set the destination for each shared folder to be its own custom target location on the central computer.

This is an issue because I have multiple "servers" that have the same folder naming structure but the contents of these folders are unique to that server.  (Think of multiple servers running the same docker container but the gathered data in said container's folders is unique to that server.)

I can see the Folder Path value when I edit the shared folder on the central computer but I don't see how I can adjust that location other than globally setting the Folder Path in Settings > Edit Folder Defaults > Folder Path; but that change is global to all incoming shares.

## Example
ComputerA and ComputerB have folders I wish to backup/sync to folders on ComputerC (my central computer).  I'd like the ability to set the target directory on ComputerC to be custom for each shared folder incoming from ComputerA and ComputerB.  Like, "~/shared_folders/ComputerA" for shares from ComputerA and "~/shared_folders/ComputerB" for shares from ComputerB.

## Workaround
By setting the Folder Label name in the source computer's Folders sharing options.  For now, I've been adding the source computer's name to identify this folder as being shared from this computer.

This works but seems tedious and redundant.  It seems wrong to be specifying something on the local computer that is for purposes of usage on a remote computer.

## Solution
The solution, I think, would be to have a "Folder Path" value that is associated to each Remote Device so that you can specify the target directory for each (defaulting to whatever the global Folder Path setting is).  Thus the configuration is how the "local" computer will store/organize the incoming shared folders.

**Comment by daxm** [comment]
I did have auto accept enabled.  Disabling that I was able to set the destination folder.  This was not obvious to me.  :-)

The only issue with the current setup is that the destination folder "Folder Label" will look the same from all incoming remote devices (since they all use the same folder name on their end).  Thus, I need to customize the Folder Label name locally to keep them unique.  Not a huge issue but might could be resolved with adding the remote device name into the Folder Label name?  Or maybe allow Folders to be organized/sorted by remote device?

I can live with it as is but I still think it would be nice to be able to set a default destination folder for all incoming shares from a particular remote device.  This way you could set up auto accept AND have them synced to a unique destination folder.

**Comment by acolomb** [comment]
The whole concept falls apart when you consider more than one remote device sharing the auto accepted folder. Which one's configured default path should be used then?

Thus I don't see this happening. If you want to automate something and still control some aspects, the API can be used for that.

**Comment by tomasz1986** [comment]
> Not a huge issue but might could be resolved with adding the remote device name into the Folder Label name?

Just an idea for a possible workaround, but how about configuring the label like that on the remote device itself? For example, `Device1-Folder`, `Device2-Folder`, etc. I'm talking only about the label, as the actual path can be different. This way, if you share the folder from the remote device and the local device has "Auto Accept" enabled, the folder should be created with the same label that already has a device name in it.

Please keep in mind though that folders shared this way will all be located in the same default folder root, and no, you cannot use slashes in the label to automatically put them into subfolders (as slashes are automatically converted into spaces when added via "Auto Accept").
