### ISSUE TITLE
Not possible to sync symlinks on certain Android devices

### ISSUE THREAD

**Issue by Havard-SL** [syncthing/syncthing#9432]
### Required information

 - which version of Syncthing and what operating system you are using:
     - v1.27.2 on Android 13 (Samsung A71, One UI version 5.1) (syncthing-fork)
 - browser and version, if applicable:
     - N/A
 - what happened:
     - Relative symlinks from computer won't sync over to Android
 - what you expected to happen instead:
     - Create a symlink on the Android phone
 - any steps to reproduce the problem:
     - Create a relative symlink on the computer, it will now hang on Android with the error message: `syncing: symlink create: symlink foo bar: permission denied `

### More information
     
This has been reported previously (https://github.com/syncthing/syncthing/issues/8035), but the previous issue has been closed without any solution or workaround presented.

_I think_ the reason the symlink failes to be created is because the filesystem (sdcardfs)  **in the folders one can choose (on my phone, at least)** does not support symlink creation. However, there are other parts of the filesystem where symbolic links can be made, such as in /data/data/(APP-ID)/, but those are not accessible in syncthing (at least I didn't manage it, but I have no clue what I'm doing).

This has created some confusion because if you open termux and create a symbolic link it just works. This is because termux drops the user into /data/data/com.termux/files/home/, where it is possible to create symlinks.

Therefore my suggestion (which might not be correct at all, I'm just speculating) would be to allow the user to choose a syncing folder in syncthings /data/data/(APP-ID) folder. This will most likely cause permission issues if one wants other apps to be able to read the synced data, but at least the symlinks will be created.

I hope any of what I wrote above makes sense, and thank you for creating such an amazing tool which I depend on every day :)

**Comment by tomasz1986** [comment]
As you've said yourself, Android simply doesn't support symlinks on the user storage. They are only supported on partitions like `/data`, `/system`, etc. which are normally inaccessible to the user.

> Therefore my suggestion (which might not be correct at all, I'm just speculating) would be to allow the user to choose a syncing folder in syncthings /data/data/(APP-ID) folder. This will most likely cause permission issues if one wants other apps to be able to read the synced data, but at least the symlinks will be created.

This is not a question of allowing something inside Syncthing or not. The OS simply restricts those paths from being accessed by the user. However, you should be able to access them if you run Syncthing as root. There is an option to do this in the app settings. The phone itself needs to be rooted first, of course.

Just to reiterate, there is no workaround other than running the app with root access.

**Comment by Havard-SL** [comment]
Thank you for a fast and concise answer :)

Just wanted to point out for anyone reading this in the future: It is in fact possible to select (at least on syncthing-fork) the /data/data/(APP-ID) folder from the UI (I just didn't see it when I wrote the issue), but it errors out with "folder marking missing". However that is another issue entirely.

**Comment by tomasz1986** [comment]
> Thank you for a fast and concise answer :)

No problem 🙂. We do need some proper documentation targeted at the Android app specifically, as there are many quirks and limitations that simply aren't covered by the current one…

> It is in fact possible to select (at least on syncthing-fork) the /data/data/(APP-ID) folder from the UI (I just didn't see it when I wrote the issue), but it errors out with "folder marking missing". However that is another issue entirely.

Do you mean from the app interface or from the Web GUI? If the former, I think this may be something the Samsung file picker allows, not a generic Android thing. If the latter, then yeah, you can input any path in the Web GUI, however, if there is no access, Syncthing won't be able to create the marker and sync the folder contents anyway.

**Comment by Havard-SL** [comment]
> Do you mean from the app interface or from the Web GUI? If the former, I think this may be something the Samsung file picker allows, not a generic Android thing. If the latter, then yeah, you can input any path into the Web GUI, however, if there is no access, Syncthing won't be able to create the marker and sync the folder contents anyway.

I think I might have been incorrect. It doesn't point to the /data/data/(APP-ID) folder, but rather the ~/Android/data/(APP-ID) folder which are not the same. I've attatched pictures below from my phone:

![Screenshot_20240223_174616_Syncthing-Fork](https://github.com/syncthing/syncthing/assets/55786766/c37646a1-5106-485e-a156-3cd7875c4483)
![Screenshot_20240223_174621_Syncthing-Fork](https://github.com/syncthing/syncthing/assets/55786766/edfc5cbf-5fc7-4c58-a051-a3a9428fb418)

I apologize for the confusion, I'll edit my previous response to clear this up.

**Comment by tomasz1986** [comment]
> It doesn't point to the /data/data/(APP-ID) folder, but rather the ~/Android/data/(APP-ID) folder which are not the same.

Yeah, there is a big different. In the former, you can create symlinks, but the latter is located on the user storage, so no symlinks allowed there.
