### ISSUE TITLE
Potential deadlock or goleak in lib/semaphore/semaphore.go#66

### ISSUE THREAD

**Issue by xuxiaofan1203** [syncthing/syncthing#9433]
In the case, s.Take(75) and s.SetCapacity(10) are called. At the moment, size = max = 10 and available = 0, if s.Take(75) is called again,
the goroutine will block at s.cond.Wait() even if s.Give(75) is called after that. I think the result is strange, the Wait() should block due to available = 0, but if there are enough available later, the Wait() should be signaled instead of causing a deadlock or goleak.

```
func TestByteSempahoreCapChangeDown2(t *testing.T) {
	// Things should make sense when capacity is adjusted down, different case
	s := NewSemaphore(100)

	s.Take(75)
	if s.available != 25 {
		t.Error("bad state after take")
	}

	s.SetCapacity(10)
	if s.available != 0 {
		t.Error("bad state after adjust")
	}
	s.Take(75)
	s.Give(75)
	if s.available != 10 {
		t.Error("bad state after give")
	}
}
```
![图片](https://github.com/syncthing/syncthing/assets/61485003/7596c78d-05bd-4895-98cc-e470084895a4)

**Comment by calmh** [comment]
This is a problem in your test case, you can't use the semaphore like this.
