### ISSUE TITLE
sync the data from one hard drive to the other hard drive

### ISSUE THREAD

**Issue by lingwu111** [syncthing/syncthing#9439]
For example, I have two hard drives on the same computer. How do I sync the data from one hard drive to the other hard drive?
Thanks~

**Comment by tomasz1986** [comment]
Duplicate of https://github.com/syncthing/syncthing/issues/4721.

In short, as of right now, this is impossible. You can only share folders between different devices. There is a clunky workaround by running multiple Syncthing instances, but there is other, more suitable software, which can very likely do the job much more efficiently.
