### ISSUE TITLE
Speed up scanning?

### ISSUE THREAD

**Issue by DocMAX** [syncthing/syncthing#9450]
### Feature description

Speed up scanning.

### Problem or use case

Slow scanning.

### Alternatives or workarounds

Is it possible to speedup the scanning process? I have a relatively large folder with ~400k files. My idea is to have some kind of cache file. I mean you probably already thought about it...

**Comment by tomasz1986** [comment]
Please check https://docs.syncthing.net/users/tuning.html.

Other than that, if you still experience problems, please open a new topic at https://forum.syncthing.net to discuss the matter further. Please include more information though, as with this much (e.g. no operating system, no file system, no storage type, etc.), no-one will likely be able to help.
