### ISSUE TITLE
Panic during startup on Illumos; github.com/jackpal/gateway.parseNetstatToRouteStruct

### ISSUE THREAD

**Issue by sot-tech** [syncthing/syncthing#9453]
### What happened?

Panic while starting after upgrade to v1.27.4 (manual build).
Used Go versions: 1.21, 1.22, build command: 
`CGO_ENABLED=1 CGO_LDFLAGS="-lumem" go run build.go -no-upgrade -cc gcc build`
and just `go run build.go -no-upgrade -cc gcc build` (wo flags, result the same, but `watching is not supported`).

Synced paths contain latin, cyrillic and greek symbols (if it might help).

(panic log is too long to place into form)
[panic-20240306-123313.reported.log](https://github.com/syncthing/syncthing/files/14508191/panic-20240306-123313.reported.log)

### Syncthing version

v1.27.4

### Platform & operating system

Solaris/Illumos x86 (omnios-r151046-d2b54a0125)

**Comment by calmh** [comment]
Relevant part FTR:

```
goroutine 77 [running]:
github.com/jackpal/gateway.parseNetstatToRouteStruct({0xc001226000, 0x3e9, 0xc0008f2000?})
	github.com/jackpal/gateway@v1.0.13/gateway_parsers.go:394 +0x605
github.com/jackpal/gateway.parseUnixGatewayIP({0xc001226000?, 0x6c2e313234373532?, 0x6264?})
	github.com/jackpal/gateway@v1.0.13/gateway_parsers.go:355 +0x1c
github.com/jackpal/gateway.discoverGatewayOSSpecific()
	github.com/jackpal/gateway@v1.0.13/gateway_solaris.go:22 +0x2a
github.com/jackpal/gateway.DiscoverGateway(...)
	github.com/jackpal/gateway@v1.0.13/gateway.go:46
github.com/syncthing/syncthing/lib/pmp.Discover.func1()
	github.com/syncthing/syncthing/lib/pmp/pmp.go:33 +0x1b
github.com/syncthing/syncthing/lib/svcutil.CallWithContext.func1()
	github.com/syncthing/syncthing/lib/svcutil/svcutil.go:231 +0x2c
created by github.com/syncthing/syncthing/lib/svcutil.CallWithContext in goroutine 111
	github.com/syncthing/syncthing/lib/svcutil/svcutil.go:230 +0xb5
```

Funky build you have there, but I don't think it's related to this issue. :)

**Comment by sot-tech** [comment]
> Funky build you have there, but I don't think it's related to this issue. :)

Hello. No, build is ok (CGO used to get work fs watch, `umem` - solaris' genuine memory allocator).
I already found an issue in [gateway library](https://github.com/jackpal/gateway/blob/9989e23f467a5f56a6c013ba49e5e2230b47eb4f/gateway_parsers.go#L394), it extects inteface name for default gateway line, but solaris' netstat don't produce it:
```
Routing Table: IPv4
  Destination            Gateway          Flags  Ref     Use     Interface 
-------------------- -------------------- ----- ----- ---------- --------- 
default              192.168.207.36          UG       49  681748414           
```

Anyway, it seems to be issue in specific library, downgrade it or wait for fix - it's your decision.

**Comment by calmh** [comment]
I suggest filing an issue on the package in question, then (if/when fixed) it'll end up here in the end.
