### ISSUE TITLE
Receive only folders do not honor ingore patterns

### ISSUE THREAD

**Issue by Peter-Harmann** [syncthing/syncthing#9456]
### What happened?

I have added a folder that I use for file versioning to ignore patterns in my receive only folder. However, the folder shows the files in this folder as local changes regardless.

### Syncthing version

v1.27.4

### Platform & operating system

Windows (64-bit Intel/AMD)

### Browser version

Firefox 123.0.1

**Comment by tomasz1986** [comment]
There is no difference in how ignore patterns are treated in a Receive Only folder specifically.

Please open a new topic at https://forum.syncthing.net and explain the problem there. Please make sure to include screenshots of the Syncthing Web GUI, and also some sample filenames and the ignore patterns that are supposed to match them. The more details, the better.
