### ISSUE TITLE
Local sync between directories

### ISSUE THREAD

**Issue by Willtech** [syncthing/syncthing#9468]
### Feature description

As initially suggested [4721](https://github.com/syncthing/syncthing/issues/4721) allow local sync useful for maintaining multiple local copies of folders, e.g. multiple local backups. Allow adding a folder multiple times connected syncing to another local folder.

### Problem or use case

Using R.A.I.D. to create mirrors of folders across different disks is not nearly a utility solution to a simple case of wanting one folder to backup onto multiple removable devices, and in the case some device is not present it does not allow recovery without rebuild.

### Alternatives or workarounds

A disk could be offline or temporarily on another purpose and reappear later at a time syncthing can resynchronise. This also allows one-way backups or configuration with different file versioning per folder.

**Comment by tomasz1986** [comment]
Is this feature request any different than https://github.com/syncthing/syncthing/issues/4721 though? If it is about the same thing, then there is no need to create a new issue, as the old one is still open and valid.

**Comment by Willtech** [comment]
Right, and there is no possibility to contribute to it since it only allows collaborators.

**Comment by imsodin** [comment]
And that's not an accident, the last comment there says why. Also https://github.com/syncthing/syncthing/wiki/NoPlusOne
