### ISSUE TITLE
Shared folder in another drive is added as duplicate twice to home directory

### ISSUE THREAD

**Issue by superbonaci** [syncthing/syncthing#9473]
### What happened?

I have Windows 11 and I've set up a shared folder, in `D:\Synthing-shared`. There's also a duplicate in `~\tfjng-wvhtp` which creates 2 directories: one in `~\utnhu-wvhtp` and another in `~\Synthing-shared`.

What I do is click Edit - Remove on the shared which is stored in C:, and I can safely remove the folders.
However after reboot, the 2 folders in C: are regenerated with the content.

How can I debug and fix this?

### Syncthing version

v1.27.4

### Platform & operating system

Windows 11 x86_64

### Browser version

Chrome 122.0.6261.129

### Relevant log output

```shell
No idea how to do this.
```

**Comment by superbonaci** [comment]
I've tried removing again the shared in C:, and changing Folder Defaults to 'D:' instead of `~`.
Now the folder `D:\tfjng-wvhtp` is created instead and the second shared is there after reboot.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
