### ISSUE TITLE
Could SyncThing be adapted to support local first software integration?

### ISSUE THREAD

**Issue by mofosyne** [syncthing/syncthing#9474]
### Feature description

Was reading up this article https://www.inkandswitch.com/local-first/ and got me thinking... couldn't we adapt certain part of the Syncthing infrastructure to support such use case? 

Especially for mobile apps like on Android. Imagine adapting Syncthing's setup to help apps find each other – it could make things a lot easier than setting up separate discovery servers for each app, right? 

Plus, it fits with the whole idea of keeping data under user control. Just a thought!

To implement this, it might just be adding some documentations if the syncthing codebase is modular enough. Else maybe you may need to create a separate library or document the syncthing api enough for developers to write their own app interface.

### Problem or use case

The idea is to simplify discovery of app data and to allow developers to create apps that do not need a centralized cloud to store user data. This would allow users to more easily trust that their data will be kept private much like why people would want to use syncthing

### Alternatives or workarounds

Alternative is the centralised cloud infrastructure used by most apps anyway.

**Comment by imsodin** [comment]
I don't see anything actionable here. If there's something concrete to do that is propose, we can judge whether that merits an open ticket or not. And contributions are of course welcome. As is I only see a general concept. If your intent is to discuss that, please take that to https://forum.syncthing.net/
