### ISSUE TITLE
Enhance #9339

### ISSUE THREAD

**Issue by nivranaitsirhc** [syncthing/syncthing#9478]
### What happened?

The old behavior and just like what is stated in the [documentation ](https://docs.syncthing.net/v1.27.4/users/ignoring) when a "!" directive was included for a pattern inside an ignored parent folder, the parent folder and the path matching the "!" should not be ignored. This was useful for my use case were my sync setup a `Master Device` (sendandreceive) will sync a `foomaster` with a bunch of files to multiple devices with each device has their unique specific folder inside.

Currently everything will be ignored inside including `foomaster` even if a "!" directive is included inside its directory and it is due to #9339. I understand where #9339 is coming from but could there be an exemption instead of  `(/foo is no longer skipped, because in the mind of the ignore matcher, we might find unignored stuff underneath it...)` we implement an opinionated pattern to "!" so that instead we say that `(/foo is no longer skipped, because the ignore matcher is sure that there is some unignored stuff underneat it..)`.

### opinionated (??) pattern for "!"
```
foomaster
!foomaster(??)somefiles_inside_foomaster
```

### Main Device Folder Structure
```
foomaster/
  unique_folder_inside_foomaster_for_device_a/
   ...some_other_files_and_folder

  unique_folder_inside_foomaster_for_device_b/
    ...some_other_files_and_folder
...some_other_files_and_folder
```

### .stignore `Device A`
```
(?d)foomaster
!unique_folder_inside_foomaster_for_device_a
```
### Expected folder structure for Device A
```
foomaster/
  unique_folder_inside_foomaster_for_device_a/
    ...some_other_files_and_folder
...some_other_files_and_folder
```
### Current folder structure for Device A
```
...some_other_files_and_folder
```

### .stignore `Device B`
```
(?d)foomaster
!unique_folder_inside_foomaster_for_device_b
```
### Expected folder structure for Device B
```
foomaster/
  unique_folder_inside_foomaster_for_device_b/
    ...some_other_files_and_folder
...some_other_files_and_folder
```
### Current folder structure for Device B
```
...some_other_files_and_folder
```

### Syncthing version

v1.27.4

### Platform & operating system

Windows, Android

**Comment by er-pa** [comment]
Are you sure you face an issue due to that change and not just an 'order' issue?

You ignore `foomaster` before you include the subfolder. The subfolder won't be checked, as the main folder is already being ignored.

**Comment by nivranaitsirhc** [comment]
> Are you sure you face an issue due to that change and not just an 'order' issue?
> 
> You ignore `foomaster` before you include the subfolder. The subfolder won't be checked, as the parent-folder is already being ignored.

It worked! I did not know it was an order issue.
