### ISSUE TITLE
Be more kind with non-normalized UTF-8 filenames

### ISSUE THREAD

**Issue by stkw0** [syncthing/syncthing#9483]
### Feature description

Currently, syncthing tries to normalize the UTF-8 filenames before syncthing, but that can be problematic in some use cases. I would like that syncthing could work and sync files even in the event of non normalized filenames (at least for the source part, the destination could be normalized if required). 

### Problem or use case

In my setup I use syncthing to sync a Music folder between my personal computer and a different computer. The Music files of that Music folder are music coming from torrent sites that I would like to keep seeding. In order to seed those torrents the filenames should not change as otherwise the torrent client will detect it as corrupt files as it would not match the original filenames. If I use syncthing with default settings, it would normalize the filenames, thus causing problems to the torrent client. But if they are not normalized syncthing would not sync the files

### Alternatives or workarounds

As I don't have much control over the source files I can not see any alternative. The only workaround would be to have two copies of the files, one for the torrents and another for syncthing, but that would not work as I wouldn't have enough disk space to hold two copies of the entire library.

**Comment by calmh** [comment]
Yeah I don't know what we'd do better here. You can of course disable normalisation, but the problem with running without it is that Syncthing could sync a file from another device that has the same name but just differs in normalisation, which is both confusing on disk and also something we don't support since file names over the wire are normalised...

**Comment by calmh** [comment]
Syncthing is bidirectional; we'd have to know that an incoming notification about a (normalised) filename somehow applies to a different non-normalised name on disk. Separate cache files and stuff is not a thing we do, for a variety of reasons (complexity and race conditions among them).

**Comment by stkw0** [comment]
Yes, if there are not enough use cases I understand it could be too complex to modify the core just for this. Thinking about a different solution. Would it work to have an option to create a symlink (maybe a hard symlink?¿) with the normalized name that points to the non-normalized name?

**Comment by calmh** [comment]
A hard link should work, possibly, if you disable the auto normalisation.

**Comment by stkw0** [comment]
I see. If syncthing could have two option to handle non-normalized filenames and in case of hardlinks could ignore the non-normalized filename if there exist also a normalized version it would be neat. Never tried to dig into the source code. I guess that it being a very special use case it would be of very low priority, but at some point I could try to open a PR if that's okay.

**Comment by calmh** [comment]
I think disabling auto normalisation should give you that behavior. If it does not, I think it's way too detailed and niche a knob for us to have and maintain, honestly. I hope this solves your issue!
