### ISSUE TITLE
Update DSM6 package from version 1.23.4 to version 1.27.4

### ISSUE THREAD

**Issue by masbicudo** [syncthing/syncthing#9488]
### Feature description

In my Synology NAS I have DSM6. In the package manager, I can find SyncThing 1.23.4, which is 1 year old by now.
Is it possible to update the package? Thanks for the great work!
![image](https://github.com/syncthing/syncthing/assets/1653710/67d0643e-659d-4cb7-9473-41947be9708c)

### Problem or use case

Have an updated SyncThing version running in Synology NAS.

### Alternatives or workarounds

The alternative is to use the somewhat outdated version.

**Comment by acolomb** [comment]
The Synology package installs Syncthing with its internal automatic update mechanism still active. So although the package version looks old, Syncthing itself will be kept up-to-date.
