### ISSUE TITLE
Didn't Launched Automatically

### ISSUE THREAD

**Issue by victorchor2868** [syncthing/syncthing#9491]
### What happened?

Every time I restarting my Mac, it wasn't auto launching your app, I need to launch it manually. 

### Syncthing version

1.27.4-1

### Platform & operating system

macOS Sonoma 14.4.1

### Browser version

Safari 17.4.1

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
