### ISSUE TITLE
files with specific naming pattern remain 'out of sync' 

### ISSUE THREAD

**Issue by sandokanfirst** [syncthing/syncthing#9492]
### What happened?

The pattern which sometimes gives problems is when filenames start with digits and there are spaces in paths it seems:
![image](https://github.com/syncthing/syncthing/assets/36963445/0915ef50-ba51-47dd-9a60-50494877d1df)

### Syncthing version

v1.27.4

### Platform & operating system

Linux arm 32

### Relevant log output

```shell
I don't see relevant output
```

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
