### ISSUE TITLE
remote uses different upper or lowercase characters than local "<filename>"; change the casing on either side to match the other

### ISSUE THREAD

**Issue by brokesc** [syncthing/syncthing#9500]
### What happened?

example: message (html code changed to text)

kindle\_wuxia\Rogue Pharmacist\Le Yi - Rogue Pharmacist_ volume 6.epub	syncing: finishing: checking existing file: remote "kindle\_wuxia\Rogue Pharmacist\Le Yi - Rogue Pharmacist_ volume 6.epub" uses different upper or lowercase characters than local "kindle\_wuxia\Rogue Pharmacist\Le Yi - Rogue Pharmacist_ Volume 6.epub"; change the casing on either side to match the other

background:
various files copied by syncthing (windows local machine set to receive only) from master source (linux box) are showing this message

question: Why, when syncthing creates the local file, is there a CASE issue in the file name? Is this really an issue or a bug?

possible solutions:
1. since the GUI uses html anyway, why not, on the source computer, have the file name be a local link that when clicked on brings up the file's home directory to make cleanup easier? IF the error message could HIGHLIGHT the problem it would make cleaning up issues easier.
2. If this isn't possible, how about adding a 'save errors to file' option down at the bottom of the failed items window? Just dump the file to text...maybe pipe delimited?  This would make programmatically cleaning up errors from the command line easier if nothing else...

### Syncthing version

v1.27.5

### Platform & operating system

Windows 11-Ubuntu Linux LTS

### Browser version

SyncTrayzor/Chrome/Firefox

### Relevant log output

```shell
From failed items link:

kindle\_wuxia\Rogue Pharmacist\Le Yi - Rogue Pharmacist_ volume 6.epub 	syncing: finishing: checking existing file: remote "kindle\_wuxia\Rogue Pharmacist\Le Yi - Rogue Pharmacist_ volume 6.epub" uses different upper or lowercase characters than local "kindle\_wuxia\Rogue Pharmacist\Le Yi - Rogue Pharmacist_ Volume 6.epub"; change the casing on either side to match the other
```

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by brokesc** [comment]
It's a feature request in that it includes program improvement suggestions.
That being said, if you don't agree please MOVE IT where it belongs.
