### ISSUE TITLE
gui: Favicon not working in Firefox bookmarks

### ISSUE THREAD

**Issue by medusalix** [syncthing/syncthing#9506]
### What happened?

Firefox doesn't show any favicon at all when adding a bookmark to the Syncthing GUI, even with the static favicon introduced by #8850. It looks like Firefox prefers the last favicon that is found in `<head>` which is the link to `favicon-{{syncthingStatus()}}.png`. Because that file is not available on initial page load, it is not considered for bookmarks. The favicon logic for Firefox can be found [here](https://searchfox.org/mozilla-central/rev/c09764753ea40725eb50decad2c51edecbd33308/browser/modules/FaviconLoader.sys.mjs#443).
Switching the order of the favicon links in `<head>` fixes the behavior for Firefox while breaking the dynamic favicon for Chromium-based browsers.
A proper fix for this issue was suggested by @ajshea in https://github.com/syncthing/syncthing/issues/7638#issuecomment-838888561.

### Syncthing version

v1.27.6

### Platform & operating system

Linux x86

### Browser version

Firefox 124.0.2

**Comment by LinuxOnTheDesktop** [comment]
I still have a problem with Syncthing bookmark icons, on Syncthing 1.27.8. Or rather I have the following two problems.

1) On Firefox 126.0.1 I get a Syncthing icon but it includes an exclamation mark even though so far as I can tell all is well with Syncthing.

2) On Firefox 1115.11esr, I get no icon at all.

In the case of each of cases 1 and 2 I deleted an existing Syncthing bookmark before, on Syncthing 1.27.8, adding a new one. It seems to make now difference _how_ I add the bookmark. In both cases (1 and 2) I tried only adding a bookmark to the bookmarks _bar_.

Perhaps I do something wrongly.
