### ISSUE TITLE
Show the version on the web GUI page

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [syncthing/syncthing#9510]
### Feature description

It would be nice to see Syncthing's version directly on the GUI - the GUI, I mean, that shows, 'Folders', 'This Device', and 'Remove Devices'. To that display one could add a 'Syncthing' tab and put the version number under it. Then in order to know the version, one would not have to find the right menu items.

### Problem or use case

Being able to see the version immediately - without navigating menus - will suit everyone. But it is of particular use when one wants to see whether Syncthing has got updated.

### Alternatives or workarounds

At present, one can find the 'Help' tab (though one might mistakenly instead go to 'Actions' first), click it, and then click 'About'.

**Comment by tomasz1986** [comment]
The Syncthing version should already by present under "This Device" (as can be seen in the screenshot at https://docs.syncthing.net/intro/gui).

Does this look different on your side? Can you post a screenshot? Please keep in mind that this applies to the official Web GUI only and not 3rd party wrappers like Syncthing-GTK, etc. which have their own UIs.

**Comment by LinuxOnTheDesktop** [comment]
This was my mistake. I'm sorry. I do see what you see. I did not notice the version display. Is there a case for having a separate 'syncthing' tab, of the sort that I suggested?
