### ISSUE TITLE
Make address field in remote devices panel clickable to open administration GUI

### ISSUE THREAD

**Issue by Xeenych** [syncthing/syncthing#9511]
### Feature description

Make address field in remote devices panel clickable to open administration GUI
![image](https://github.com/syncthing/syncthing/assets/11345848/dc14f26d-57d9-4728-bca5-e6d0bf2924a9)

### Problem or use case

A fast way to open admin panel on a remote device. No need to type ip address and port in browser

### Alternatives or workarounds

Type ip addres in url field of a browser

**Comment by tomasz1986** [comment]
The functionality is already in Syncthing. Please check https://docs.syncthing.net/users/config.html#config-option-device.remoteguiport.
