### ISSUE TITLE
Windows Listed Version Older Than Running Version

### ISSUE THREAD

**Issue by adamsmith34** [syncthing/syncthing#9513]
### What happened?

Installed Syncthing via winget. Set up to run automatically at start up.

Running `winget upgrade --all` failed on Syncthing.Syncthing with an error message:
"The process cannot access the file because it is being used by another process.: "...\AppData\Local\Microsoft\WinGet\Packages\Syncthing.Syncthing_Microsoft.Winget.Source_8wekyb3d8bbwe\syncthing-windows-amd64-v1.27.2"
Uninstall failed with exit code: 0x8a150003 : Executing command failed"

While looking to stop the Syncthing process, I discovered it was already at the latest version, 1.27.6, not 1.27.2 which Windows lists.

I do not know when or how the Syncthing client updated without the version in Windows being updated accordingly.

### Syncthing version

v1.27.6

### Platform & operating system

Windows x64

### Browser version

Edge 123.0.2420.81 (Official build) (64-bit)

### Relevant log output

```shell
> winget list syncthing
Name      Id                  Version Available Source
------------------------------------------------------
syncthing Syncthing.Syncthing 1.27.2  1.27.6    winget

> syncthing -version
syncthing v1.27.6 "Gold Grasshopper" (go1.22.2 windows-amd64) builder@github.syncthing.net 2024-04-08 09:14:27 UTC
```

**Comment by calmh** [comment]
I don't know either, but this sounds like something related to the winget repository, which is not managed by us. My guess would be that it installs the binary with auto upgrades enabled, which may or may not be proper depending on the circumstances.

**Comment by calmh** [comment]
Yeah, looks like it just downloads the binary from our GitHub builds here, and doesn't have an opinion how you then run that binary. https://github.com/microsoft/winget-pkgs/tree/master/manifests/s/Syncthing/Syncthing/1.27.6

If you want the version to be winget-managed you'd need to disable automatic upgrades in the settings.
