### ISSUE TITLE
add run on mobile data / run on wifi options to pc

### ISSUE THREAD

**Issue by RustoMCSpit** [syncthing/syncthing#9514]
### Feature description

on phone, i can turn off mobile data transfer. however, my computers will automatically join its hotspot and share data through it, wasting a lot of money for me. i want to be able to turn off their ability to work on mobile data like i can with my phone

### Problem or use case

computers being able to run on mobile data

### Alternatives or workarounds

?

**Comment by RustoMCSpit** [comment]
if this already is an option please tell me because i cant find it

**Comment by AudriusButkevicius** [comment]
Same as: https://github.com/syncthing/syncthing/issues/8394, pause on metered networks.
Not currently implemented.
