### ISSUE TITLE
meta.js is sent with the wrong MIME type

### ISSUE THREAD

**Issue by bt90** [syncthing/syncthing#9523]
### What happened?

The HTTP content-type seems to be wrong:

    content-type: text/plain; charset=utf8

Paired with `x-content-type-options: nosniff`, the request is blocked by the browser.

see https://forum.syncthing.net/t/cant-login-to-syncthing-gui-with-ngnix-proxy-manager/22030

### Syncthing version

v1.27.6

### Platform & operating system

Linux amd64

**Comment by bt90** [comment]
Something is fishy:

https://github.com/syncthing/syncthing/blob/6204670c663338be519d3cb96fd9232752e08294/lib/api/api.go#L722

![image](https://github.com/syncthing/syncthing/assets/1926175/afb8753d-0e2c-407c-9de7-51cd902d73bb)

**Comment by bt90** [comment]
Ah, this is apparently caused by `/meta.js` not being exempt from our authentication check. Maybe we need to add `/meta.js` here?

https://github.com/syncthing/syncthing/blob/6204670c663338be519d3cb96fd9232752e08294/lib/api/api_auth.go#L54

**Comment by calmh** [comment]
I don't follow. There's nothing wrong with the content type. It's behind auth, as many other things. The OP's issue seems to be some proxy problem together with trying to interpret a retuned 403 error.

**Comment by bt90** [comment]
The problem is that we're loading `meta.js` as regular frontend code:

https://github.com/syncthing/syncthing/blob/6204670c663338be519d3cb96fd9232752e08294/gui/default/index.html#L1080

Once strict MIME type handling is enforced via [X-Content-Type-Options: nosniff](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options#nosniff), this ends up as an error in the browser console.

Judging from a quick test, it doesn't break the UI even when `X-Content-Type-Options: nosniff` is added by a reverse-proxy. So it's more of an annoyance than a real bug and mostly not the cause of the problem observed by the user.

My proposal would be to exempt meta.js from authentication and instead populate its `authenticated` field dynamically:

https://github.com/syncthing/syncthing/blob/6204670c663338be519d3cb96fd9232752e08294/lib/api/api.go#L717-L721

**Comment by calmh** [comment]
It doesn't break the UI at all as far as I can tell. There's an error in the console about it when you're not logged in, that's all. Potentially this could be nicer, perhaps we don't try to load the resource when not logged in, but I don't see a bug or problem here...

**Comment by bt90** [comment]
> From what I can see in the forum thread the OP had some entirely unrelated problem with the proxy or their browser plugins and just latched onto this as the visible error in the console.

Aye. nginx-proxy-manager has some interesting config bits:

https://github.com/NginxProxyManager/nginx-proxy-manager/blob/v2.11.1/docker/rootfs/etc/nginx/conf.d/include/assets.conf#L8-L9

**Comment by voffch** [comment]
Well, the issue is closed, as far as I understand, because while it's ugly to have errors in your browser console when everything's good, if such behavior doesn't break anything, then it's OK.

However, I'd like to mention that it's definitely not only *that guy's issue with nginx proxy*, because my system (Debian 12, Apache 2.4.62 with the [recommended settings](https://docs.syncthing.net/users/reverseproxy.html)) behaves in exactly the same way, and I'm also getting `GET https://064329.xyz/sync/meta.js NS_ERROR_CORRUPTED_CONTENT` because of supposedly incorrect MIME-type.
