### ISSUE TITLE
Device connection state metric

### ISSUE THREAD

**Issue by DerRockWolf** [syncthing/syncthing#9527]
### Feature description

A new metric that exposes the connection state of each device as a gauge value (e.g., 0 = disconnected; 1 = connected, ...).

### Problem or use case

I have an android device where the operating system frequently kills the syncthing app.
I want to monitor, using prometheus, whether the device is connected with my central syncthing node and get alerted if it is disconnected for an extended period of time.

### Alternatives or workarounds

Create a custom exporter that uses the syncthing API.

---

If this is something you would be interested into having, I can try to open a PR for it.

**Comment by DerRockWolf** [comment]
> Sounds reasonable. I'd probably make it a gauge on the number of connections, so zero is disconnected and then positive numbers for connected devices.

Oh, then I probably didn't phrase it good enough :sweat_smile: 

My plan was to do it specific to the device ID, e.g.,
```text
# specific device connected:
syncthing_protocol_connection_state{device="DEVICE-ID"} 1
# specific device not connected:
syncthing_protocol_connection_state{device="DEVICE-ID"} 0
```

**Comment by calmh** [comment]
I agree, but a single device can have an arbitrary number of active connections nowadays. So, what you're proposing, but `1` can also become `3` or `28`.

**Comment by DerRockWolf** [comment]
> I agree, but a single device can have an arbitrary number of active connections nowadays. So, what you're proposing, but `1` can also become `3` or `28`.
> 
> ```
> syncthing_protocol_connections_active{device="DEVICE-A"} 28 # connected, large number of concurrent data connections
> syncthing_protocol_connections_active{device="DEVICE-b"} 0 # disconnected
> ```

Got it, thanks for clarifying.

I'll try to implement it and open a PR :slightly_smiling_face:

**Comment by DerRockWolf** [comment]
After looking around a bit I found `connections.accountAddedConnection` & `connections.accountRemovedConnection` as functions where I can add the `Inc` & `Dec` calls. The `connections` package currently doesn't have its own `metrics.go`, so I would add one.

I however don't know if this is the *best* location. I've also found `protocol.NewConnection` & `protocol.internalClose` and `model.AddConnection` & `model.Closed`.
It would be great if you could point me to the location you would consider to be suitable.

**Comment by calmh** [comment]
I think the accounting functions you found are a good place. There's probably some map or slice there that has the number of connections you can get the length of, or just pair the inc/dec as you say.

**Comment by LinuxOnTheDesktop** [comment]
So (if I may) how does one use this new functionality? I am not even clear whether the new feature is GUI or CLI.

**Comment by er-pa** [comment]
> So (if I may) how does one use this new functionality? I am not even clear whether the new feature is GUI or CLI.

Syncthing exposes a bunch of metrics on `.../metrics` (e.g. `127.0.0.1:8384/metrics`) which can be handled by some prometheus instance or alike. And this change simply exposes one more metric there.

https://docs.syncthing.net/users/metrics.html
