### ISSUE TITLE
Connect devices with XMPP (and also Ad-Hoc commands!)

### ISSUE THREAD

**Issue by sjehuda** [syncthing/syncthing#9531]
### Feature description

Due to the ability to login to a single XMPP account from multiple connections and due to the priority mechanism XMPP has, I would suggest that support for XMPP, in addition to random IDs (the default) would be highly beneficial.

_Note: If decentralization is a concern, then XMPP is indeed capable of connecting to decentralized networks like cjdns, Freenet, I2P, Nym, Tor, Yggdrasil etc._

### Problem or use case

Connecting to XMPP would allow more control to people who are fluent with XMPP.

It would also allow a strong authentication mechanism, as each account has ID and password.

Moreover, XMPP also allows the creation of UI which would allow advertising Ad-Hoc commands for Syncthing which would be promptly available in XMPP. Commands can be selective (i.e. commands can also be labeled by permissions: Owner, Guest, Privileged etc.).

See screenshots at https://github.com/jarun/buku/issues/719

In addition, XMPP also offers encryption using OMEMO, and many other features that are useful for transferring of files.

### Alternatives or workarounds

None

**Comment by calmh** [comment]
That all sounds nice, but it sounds like something else than Syncthing. The TLS integration and device IDs are quite ingrained to how things work.

**Comment by sjehuda** [comment]
TLS is mandatory in XMPP since a decade ago or so.

Albeit XMPP is used everywhere, be it in MySpace, ICQ, VK, Juick, Faceboogle and other brands I do not want to advertise, the industry does much to suppress it because it has all the best potentials of instant messaging, file sharing and content sharing (by content I mean documents such as HTML documents).

You may find libraries at:
https://mellium.im/
https://github.com/FluuxIO/go-xmpp

I highly encourage to be open to XMPP and to make it an additional mean of communication.

It will be beneficial to you and to me for the VERY longer term.

If XMPP was popular today, http/html (aka "web") browsers would be barely used today.

**Comment by sjehuda** [comment]
@calmh please join the discussion I have started at https://forum.syncthing.net/t/xmpp/22095 and I hope to better explain this matter.

**Comment by calmh** [comment]
That's probably the right place to discuss it, yes.

**Comment by sjehuda** [comment]
Thank you @Neustradamus. I have corrected my previous comment.
