### ISSUE TITLE
Interface without JS (HTML and Gemini)

### ISSUE THREAD

**Issue by sjehuda** [syncthing/syncthing#9534]
### Feature description

- HTML interface without JS (good).
- Gemini interface (ideal).

### Problem or use case

- Useful in general.
- Useful for Gemini clients.
- Useful in particular for text-mode software like ELinks, Lynx (Gopher support is included) and w3m.

### Note about Gemini

Gemini is VERY FAST and pages are loaded instantly which would make you smile from excitement at the first time you try!

### Alternatives or workarounds

It is might possible to use the current interface with Browsh but:
- It is not available on all computers.
- I do not trust the Fox and Red Lizard company nor the colorful 666 wheeler for my privacy.

Another one would be `syncthing cli`, but that might not alway be convenient with mobile devices, hence a Gemini and a non-JS HTML versions would be beneficial.

**Comment by calmh** [comment]
Many things might happen with the gui in the future, but I very strongly suspect this will not be one of them. Sorry.
