### ISSUE TITLE
Creation date gone after sync

### ISSUE THREAD

**Issue by martin1194** [syncthing/syncthing#9536]
### What happened?

I keep using SyncThing to sync my Hexo Mark Down file between laptop, desktop and Linux host server. I found that the creation date will keep changing after I add a new stuff in my Mark Down File.

### Syncthing version

v1.27.6 & v1.27.7

### Platform & operating system

ubuntu 23.1  and WIndows 10 HOME

**Comment by calmh** [comment]
Duplicate of #9191
