### ISSUE TITLE
Include an option in the GUI to run Syncthing on startup

### ISSUE THREAD

**Issue by jarble** [syncthing/syncthing#9537]
### Feature description

Syncthing's web GUI should include an option on the "Settings" page to run Syncthing automatically at startup.

### Problem or use case

Syncthing won't run at startup on Windows unless I manually create a shortcut to `syncthing.exe` in the Startup folder.

### Alternatives or workarounds

I can [manually create a shortcut](https://docs.syncthing.net/users/autostart.html) in the Startup folder.

**Comment by acolomb** [comment]
Syncthing's backend is portable among many different platforms, so there is no single way to "make it start on login" (or on boot?).  The variability and different setup needs are just too much to try handling in the backend.  And it would be technically hard to implement correctly I suppose.  It's not like the Web GUI is a fully integrated Windows application.  See https://docs.syncthing.net/users/autostart.html for some of the many different approaches to the problem.

What you might want to try is [Syncthing Windows Setup](https://github.com/Bill-Stewart/SyncthingWindowsSetup/), as that has an installer and includes the possibility to automatically make it start when Windows boots up.  Either as a system service, or as an autostart app for the logged in user.
