### ISSUE TITLE
syncOwnership skip parent folders of an included file

### ISSUE THREAD

**Issue by glaudano** [syncthing/syncthing#9540]
### What happened?

I'm synching users home directories running as syncthing user (with syncthing group) with CAP_CHOWN and CAP_FOWNER enabled by systemd unit override.
Almost everything  is running as expected but, using this exclusion schema:
!.ssh
!.config/gtk-3.0/bookmarks
.*

The .ssh folder and files inside the folder has expected ownership (glaudano:users)

The file .config/gtk-3.0/bookmarks has expected ownership (glaudano:users)

The folders .config and .config/gtk-3.0 keep syncthing:syncthing

### Syncthing version

1.27.7 

### Platform & operating system

Debian Linux 12.5

**Comment by tomasz1986** [comment]
I think this may be the same problem as https://github.com/syncthing/syncthing/issues/8735.

**Comment by glaudano** [comment]
Yep! The solution provided in #8735 makes the sync behave as expected. Many thanks
