### ISSUE TITLE
About Synology's fucking shit @eaDir and Thumbs.db caused problem

### ISSUE THREAD

**Issue by BeliefDawn** [syncthing/syncthing#9554]
### What happened?

In order to solve thins problem, I think it is possible to fuck it that ingore @eaDir folder, Like '(?d)@eaDir'. But it unuseful. It's worded if I write Ignore Pattern like as you see after this:
  (?d)(?i)/@eaDir/**
  (?d)(?i)Thumbs.db
BUT, I can't understand why it worked, and It's working in solve the problem or Just other It's not I writed the  "(?d)(?i)/@eaDir/**", It's others what working in solve problem and I dont konw.

### Syncthing version

v1.27.4

### Platform & operating system

Synology 7.2.1

### Browser version

Chrome latest in windows at 2024.5.21

### Relevant log output

```shell
syncing: delete dir: directory has been deleted on a remote device but is not empty; after power loss during initial sync
```

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
