### ISSUE TITLE
同步失败

### ISSUE THREAD

**Issue by xxl6097** [syncthing/syncthing#9555]
### What happened?

有部分文件同步失败，见图
![iShot_2024-05-22_11 12 22](https://github.com/syncthing/syncthing/assets/8170647/bc192ecd-e840-481d-8eb6-a5e5ec219f21)

### Syncthing version

v1.27.7

### Platform & operating system

Linux amd64

### Browser version

chrome

### Relevant log output

```shell
syncing: handling dir (setting permissions): chmod /Users/uuxia/Desktop/work/code/element/vue-admin-better/node_modules: operation not permitted
```

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
