### ISSUE TITLE
Received an error while running --reset-database.

### ISSUE THREAD

**Issue by XM-8JD2** [syncthing/syncthing#9557]
### What happened?

CMD`C:\Users\user>C:\Users\user\AppData\Local\Programs\Syncthing\stctl.exe --reset-database`

![Snipaste_2024-05-23_21-10-46](https://github.com/syncthing/syncthing/assets/133830244/b43ab03b-ccbc-4f98-b149-d877f83e22f1)

### Syncthing version

v1.27.7, Windows (64-bit Intel/AMD)

### Platform & operating system

win10 19044

**Comment by calmh** [comment]
This appears to be https://github.com/Bill-Stewart/stctl which probably doesn't take that flag.
