### ISSUE TITLE
Better handling when auto-accepting syncs of preexisting folders

### ISSUE THREAD

**Issue by betalars** [syncthing/syncthing#9566]
### Feature description

 - use empty folders of the same name to sync into when auto accepting new folders
 - add an "auto sync into folders with preexisting content" checkmark
 - ~~prompt users if a folder is almost named like this (Development and development or projects and prokects)~~ <-this would be a seperate issue

### Problem or use case

It is a nightmare to set up syncthing. And it is really annoying, as some folders such as "Music" and "Pictures" witch I would argue are some of the most common uses for syncthing are also almost always preexisting. 

### Alternatives or workarounds

Either
Remember to rename the preexisting folder to something else or delete it every time you set up a new device and then manually move all the pre existing files into it.

Or
1. realise you have a folder with a weird name created by syncthing
2. rename the preexisting folder
3. try to figure out if you can change the location of the accepted folder (I don't know how)
4. delete the synced folder in webui
5. delete the synced folder in system
6. re-accept the folder
7. move the components of the preexisting folder into the synced one

**Comment by calmh** [comment]
I don't think I understand the problem. There's a folder picker you can use when adding a folder, either from scratch or in the "accept share" dialog. If you pick an existing folder, there should be no naming confusion.

**Comment by betalars** [comment]
Oh wait ... this is only an issue with auto accepting.

I was really sure to have also had this issue with manually accepted folders. But I misremembered. Sorry.

Editing my bug report.

**Comment by acolomb** [comment]
Whatever you envision when you say "prompt the user", that won't work for auto-accepting.  That's why it's called automatic.  Without that (rather exotic) option, the user does get a prompt already.

**Comment by betalars** [comment]
> Whatever you envision when you say "prompt the user", that won't work for auto-accepting.

Yes. I rephrased the enhancement suggestion:

> add an "auto sync into folders with preexisting content" checkmark

**Comment by calmh** [comment]
What's the situation where you want auto accept and existing folders? It seems to me like there mostly a feature for servers with clients where the folders are not known beforehand. If there's a music folder and you want to sync it with someone, you could share that folder straight away when setting it up?

**Comment by betalars** [comment]
> What's the situation where you want auto accept and existing folders?

As described in the original bug report: setting up a new Device and syncing my music and pictures.

**Comment by imsodin** [comment]
I am closing this as I don't consider the use-case compelling enough to add a new option that has the potential to cause quite a big, unintended mess with user data. The upside is not having to accept a bunch of folders on first setup. The downside is carrying an option (complexity/clutter) and that option having the potential of inadvertedly sharing existing/outedated data on an existing folder when auto-accepted.
