### ISSUE TITLE
unsync files included ignore pattern when adding a new one

### ISSUE THREAD

**Issue by betalars** [syncthing/syncthing#9567]
### Feature description

Add a button that unsyncs all files when adding a new ignore pattern. The button would in the best case undo the most recent sync.

### Problem or use case

Sometimes you forget to add an ignore pattern and a bunch of stuff is being synced somewhere you do not want it to be synced to.

Having a way to undo that would be nice.

Having a button that just purges all files matched in an ignore pattern would also be good enough when the undo option is not theisable.

### Alternatives or workarounds

`rm -rf $ignore_pattern`

**Comment by pascalfleury** [comment]
Maybe related: adding an ignore pattern should also not flag unsync'd files as in-need-of-action anymore.

Example:
1. add a file that gets partially sync'd (I routinely use 10+ devices) 
2. add that file to the .stignore file
3. The UI on many machines will tell me this file is not sync'd properly. Indeed, but it should ignore that.

This is easy to reproduce when the .stignore file includes some patterns that are themselve syncd.

**Comment by imsodin** [comment]
Syncthing cannot unsync. It doesn't have a version history to revert to. Even if it did, this would have further complications. There were other discussions around ignored files, where a `syncthing cli` command to list ignored files was suggested as a helpful tool in the use-case - I guess that would help here too, if what you want to do is clean out directories.

Second comment doesn't seem related, nor do I understand it - I suggest bringing it up in the https://forum.syncthing.net/ for debugging/clarification.

**Comment by pascalfleury** [comment]
my problem is not about unsync per se, more that on a device, I get a warning about a file that is not in sync where it is actually losted in the .stignore file.
IMO rhis should either not show the warning, or given a more extensive info about which other peers know about the file and what they want.
