### ISSUE TITLE
Why can't  see the progress in upgrade

### ISSUE THREAD

**Issue by DearZack** [syncthing/syncthing#9568]
### Feature description

Why can't  see the progress in upgrade

### Problem or use case

Why can't  see the progress in upgrade

### Alternatives or workarounds

Why can't  see the progress in upgrade

**Comment by DearZack** [comment]
![image](https://github.com/syncthing/syncthing/assets/17618134/77f956d6-d11e-4e14-96c9-603889fe1032)
It took 8 minutes but make a mistake

**Comment by calmh** [comment]
This seems like a question and not a feature request.
