### ISSUE TITLE
Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification. [IP: 0.0.0.0 443]

### ISSUE THREAD

**Issue by thomasmerz** [syncthing/syncthing#9569]
### What happened?

I'm patching my Ubuntu 22.04 LTS on a daily base automatically by:
```
DEBIAN_FRONTEND=noninteractive apt-get update > /dev/null && DEBIAN_FRONTEND=noninteractive apt-get upgrade -y --with-new-pkgs > /dev/null
```
Since tonight this doesn't work anymore due to:
```
W: Failed to fetch https://apt.syncthing.net/dists/syncthing/InRelease  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification. [IP: 0.0.0.0 443]
```

### Syncthing version

v1.27.8

### Platform & operating system

Linux (64-bit ARM) as well as (64-bit Intel/AMD)

**Comment by bt90** [comment]
I get a perfectly valid LetsEncrypt certificate :shrug:

https://www.sslshopper.com/ssl-checker.html#hostname=apt.syncthing.net

**Comment by thomasmerz** [comment]
This is also a problem on my syncthing running on OpenSUSE (v1.27.8, Linux (64-bit Intel/AMD)) 🤷🏼‍♂️ 
```
INFO: listenerSupervisor@dynamic+https://relays.syncthing.net/endpoint: service dynamic+https://relays.syncthing.net/endpoint failed: Get "https://relays.syncthing.net/endpoint": tls: failed to verify certificate: x509: certificate is valid for nextwurz.mooo.com, not relays.syncthing.net
```


But d*mnit! You are right - this is a local problem with this blocklist in my adblocker:
```
Match found in https://big.oisd.nl/:
   ||syncthing.net^
```

I contacted/reported this ([False positive report](https://oisd.nl/report)) and will close this Issue. Thanks for helping.
