### ISSUE TITLE
Last version breaks syncthing on MacOS Mojave (10.14.6)

### ISSUE THREAD

**Issue by dazey77** [syncthing/syncthing#9579]
### What happened?

Updated to 1.27.8-1 and Syncthing repeatedly crashes.  Menu bar keeps going. dropped back to the syncthing I had in my download folder 1.23.6-1 and all is running again.

### Syncthing version

1.27.8-1

### Platform & operating system

MacOS Mojave 10.14.6

### Browser version

firefox

### Relevant log output

```shell
not coppied
```

**Comment by calmh** [comment]
This is unfortunately the case.

https://forum.syncthing.net/t/in-macos-high-sierra-syncthing-has-stopped-since-8th-may/22115
