### ISSUE TITLE
I need help / Firewall and ports / ips

### ISSUE THREAD

**Issue by dimitre** [syncthing/syncthing#9580]
### What happened?

First of all, thanks for the great project!
I'm using now in a secure environment where I have to specify ports and IPs for each application to be manually opened by the firewall administrators. 
I'm not much versed in firewall, but sent them this rules:
```
Port 22000/TCP: TCP based sync protocol traffic.
Port 22000/UDP: QUIC based sync protocol traffic.
Port 21027/UDP: for discovery broadcasts on IPv4 and multicasts on IPv6.
```
and syncthing service is not connecting there. Should I use some special configuration there, or maybe ask more specific things, like allow 22000 in IPv6 ? Or maybe whitelist some discovery domain?
No remote GUI is needed, 
Thank you

### Syncthing version

v.1.27.8-1

### Platform & operating system

macOS 14.5

### Browser version

Safari 17.5

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
