### ISSUE TITLE
Ignore specific folder to sync deletion

### ISSUE THREAD

**Issue by amuagarwal** [syncthing/syncthing#9582]
### Feature description

Its really good to have some way where user can igore some folder to ignore deletion 

### Problem or use case

Client: Send Only
Remote: Receive Only
On local system I created few files which got synced and after done process i deleted file on local machine and doing same force to remove file from remote i have 100 of sub folder to sync most of them need to sync deleted files but few need not to sync deletions

### Alternatives or workarounds

the best why which i can think of is having something ".stignoredelete" file in the folder which tell syncthing that this folder not need to sync deleted files.

**Comment by amuagarwal** [comment]
In my case i have 40k+ folders and need to ignore delete for around 3-4 filders

**Comment by calmh** [comment]
I think it's better to reachitect your solution to not require this, for example by moving files instead of deleting them, or using versioning. Syncthing will very likely not add the kind of granular filtering that you're looking for.

**Comment by amuagarwal** [comment]
> I think it's better to reachitect your solution to not require this, for example by moving files instead of deleting them, or using versioning. Syncthing will very likely not add the kind of granular filtering that you're looking for.

For me adding special file ".sitignoredelete" is far better over reachitect the solution as its on intranet with no internet access used to backup clients to external HDD which is connected on single machine in the network.

**Comment by calmh** [comment]
Too bad that doesn't actually work though. :)

**Comment by amuagarwal** [comment]
> Too bad that doesn't actually work though. :)

No issues will look for another option or may write small tool for my requirement.

Thanks
