### ISSUE TITLE
bittorrent?

### ISSUE THREAD

**Issue by stokebreakup** [syncthing/syncthing#9586]
### Feature description

[lg/murder](https://github.com/lg/murder) Large scale server deploys using BitTorrent and the BitTornado library (NOTE: project no longer maintained). Would it be possible to create a resource similar to the lg/murder software for syncthing?

### Problem or use case

Private, secure, encrypted, permanent and versioning.  In general, it means that my files can be downloaded and synchronized by my home servers.  

I'm thinking about helping, but I don't know how to start and whether this idea is a good idea, which is why I ask here directly. For example, "Open Development. Any bugs found are [immediately visible](https://github.com/syncthing/syncthing/issues) for anyone to browse — no hidden flaws."

### Alternatives or workarounds

- https://github.com/russss/Herd
- https://github.com/frimik/swarm

**Comment by calmh** [comment]
Syncthing is not BitTorrent. It's not clear to me what beyond that you're asking for, maybe discuss your use case on the forum.
