### ISSUE TITLE
A dot at the end of a folder name will cause sync error

### ISSUE THREAD

**Issue by hyzteric** [syncthing/syncthing#9589]
### What happened?

My folder was out of sync and I noticed that there was an error cause by the folder name.
Folder name : "Mes cousins pref." (with a dot at the end)
Error in log : I don't have the exact error because when I fixed it it disappeared but it was something saying that there was an argument error with "mkdir Mes couses pref."
The client is Android, the serveur is Ubuntu

### Syncthing version

v1.27.8

### Platform & operating system

Linux (64-bit Intel/AMD)

### Browser version

not relevant

### Relevant log output

```shell
I don't have the log anymore but it was something like it could not create the directory : argument error with "mkdir Mes couses pref."
```

**Comment by calmh** [comment]
Android doesn't allow folders to be named like that, because it generally follows FAT conventions. Syncthing can't do anything about that.

**Comment by hyzteric** [comment]
@calmh the folder named with a dot at the end is created on the Android device. The problem happens when Syncthing tried to create the copy on my linux server.

**Comment by calmh** [comment]
So maybe you're using FAT or NTFS or something on the Linux side? In any case, Syncthing does not have a restriction on dots in file names on Linux.

**Comment by hyzteric** [comment]
The drive is NTFS on the linux side indeed.
So I understand that Syncthing can't do much about it, but maybe it can report a more user friendly message for future people facing the same issue. Or propose to remove the offending dot automatically.
Thanks for your time anyway.
😊
