### ISSUE TITLE
syncthing repeatedly involved in soft lockups

### ISSUE THREAD

**Issue by oe1rsa** [syncthing/syncthing#9614]
### What happened?

After running for some time I receive a soft lockup message where always syncthing is involved. If I turn off syncthing the session runs fine. I have tried this for a week. Now when switching back on syncthing, again I receive the message.

Everything starts by the laptop showing erratic behaviour, by increasingly freezing programs. 

I am running Ubuntu 22.04 LTS on an Intel I9 CPU. And the bug hits me since a few months already. As a "work-around" I disable syncthing, but I would like to continue its usage continuously.

### Syncthing version

v1.27.9

### Platform & operating system

Linux Ubuntu 22.04 Intel I9

### Relevant log output

```shell
watchdog: BUG : soft lockup - CPU#7 stuck for 1280s! [syncthing:24406]
```

**Comment by calmh** [comment]
As far as I know this indicates a kernel or hardware issue. Syncthing is probably just triggering it by generating I/O or CPU usage.

**Comment by bt90** [comment]
> on an Intel I9 CPU

Is it an 13900K or 14900K?

https://forum.level1techs.com/t/intels-got-a-problem-13900k-ks-kf-14900k-ks-kf-crashing/213008

**Comment by oe1rsa** [comment]
> As far as I know this indicates a kernel or hardware issue. Syncthing is probably just triggering it by generating I/O or CPU usage.

Maybe, but why is syncthing the only program triggering such behaviour? I alread perfromed a memory test, but everything looks good.

> Is it an 13900K or 14900K?

No, it is an 9900K

**Comment by imsodin** [comment]
Lets continue troubleshoot this on the forum - https://forum.syncthing.net/. This is more like a support request than a clear bug or feature request. While syncthing is involved, as Jakob says the issue is likely elsewhere. If something tangible to change in syncthing is found there, an issue for that can always be created. The forum has a lot more eyes and friendly people on it than the issue tracker. Thanks!

**Comment by oe1rsa** [comment]
Ok, I respect your choice. I tried to sign up at said forum, but entered into a confusing logon loop. So, please forgive me I add my latest findings here: 

When I switched from using the lowlatency kernel to the standard kernel the problems went away. Next thing: I will try to switch to a low-atency kernel on a different machine and see what happens.
