### ISSUE TITLE
Changes in hard link file are not always detected

### ISSUE THREAD

**Issue by AnthillSudoku** [syncthing/syncthing#9617]
### What happened?

**sorry, debian stable does not provide an up to date syncthing version, please test this issue with a newer one**

I have synced debian with android, files are synced almost instantly expect this scenario with hard links:

# steps on debian

1. create a new file in a folder that is **not** synced
` touch /tmp/test.txt`
2. create a hard link to test.txt inside a synced folder
`cd ~/Sync/<folder>`
`ln /tmp/test.txt`
3. check that the file has been synced on the other device (android)
4. modify the original file writing inside the actual time and date
`nano /tmp/test.txt`
5. check the content or the property of the file on the other device (android)
**This modification will not be synced**
6. modify the hard linked file (the one created at point 2) adding a new line with actual date and time
`nano ~/Sync/<folder>/test.txt`
7. check the content or the property of the file on the other device (android)
**This modification will be synced instantly**
8. change filename of the hard linked file (the one created at point 2)
`mv ~/Sync/<folder>/test.txt    ~/Sync/<folder>/test_new.txt `
**This modification will be synced instantly**

So, if you modify the content of the original file syncthing does not detect the change. But, if you change the hard linked one inside the synced folder there is no issue, neither when changing the content nor the file name.

### Syncthing version

v1.19.2-ds1

### Platform & operating system

debian 12 (stable)

### Browser version

firefox 115.13.0esr

**Comment by AudriusButkevicius** [comment]
This should not happen, but I don't think this is a bug, more likely an issue when syncing with andoird.

Suggest you move this question to a support thread on the forum https://forum.syncthing.net/ and try to reproduce it on two devices none of which are android.
