### ISSUE TITLE
Please make Maxmind's geoipupdate an optional dependency (or call the command externally)

### ISSUE THREAD

**Issue by sten0** [syncthing/syncthing#9625]
### What happened?

While updating the Debian package to the latest release I noticed this new dependency: Maxmind's geoipupdate.  Unfortunately we can't use this in Debian because it's a non-free service (https://www.maxmind.com/) that costs money.

Would you please make this dependency optional, or better yet call the geoipupdate executable as an external command?

Making it optional will mean that all Debian users (including educational, commercial, scientific, etc) lose access to the feature--even subscribers to the paid service.  Making it possible to call the executable will mean that anyone can opt-in simply by installing the non-free software.

I hope this sounds reasonable to you :)
Thanks again for this wonderful software!

P.S. My team member @zhsj suggested the opt-in approach, which looks like the ideal solution to us

### Syncthing version

v1.27.9

### Platform & operating system

Debian

### Browser version

NA

### Relevant log output

```shell
NA
```

**Comment by sten0** [comment]
P.S. Sorry I forgot to mention this is a blocking issue to updating the package in Debian to--or beyond--the Syncthing version where the dependency was introduced.  There's no urgent need, since we need to wait for a new dependency to be accepted before uploading 1.27.7, but it would be nice to see in 1.27.10.

**Comment by calmh** [comment]
To be clear, this affects the relay pool server, which I expect we are approximately the only user of in the world (https://relays.syncthing.net) :) Syncthing itself, nor the relay server, don't have a maxmind dependency.

**Comment by imsodin** [comment]
> [...] Unfortunately we can't use this in Debian because it's a non-free service (https://www.maxmind.com/) that costs money. [...]
>
> Making it optional will mean that all Debian users (including educational, commercial, scientific, etc) lose access to the feature--even subscribers to the paid service. [...]

Can you expand on that please? The new dependency is client code dual licensed MIT and Apache 2, both are compatible with DFSG. I am not aware that interacting with non-free services makes a software non-free in debian. Especially the part about costing money/paid service confuses me - debian isn't about free as in beer, something can absolutely be compatible with DFSG and carry a price (not claiming maxmind's offering is that - we aren't packaging/shipping it).

I can see that it would be nicer if one could use other services or none at all, but that seems like a reasonable feature request not a problem for debian packaging. And as calmh said, barrying examples of actual users of the relay pool, a pretty low importance one.

**Comment by sten0** [comment]
Wow, thank you for such a quick reply!  (and once again sorry that
things are so slow moving in Debian

Jakob Borg ***@***.***> writes:

> To be clear, this affects the relay pool server, which I expect we are approximately the only user of in the world (https://relays.syncthing.net) :) Syncthing itself, nor the relay server, don't have a maxmind dependency.
>

:) That's a useful and cool site.

Unfortunately it currently appears impossible to build Syncthing 1.27.9
without github.com/maxmind/geoipupdate.  Couldn't a knob be added to
lib/build/build.go so that a build argument will either opt-in or
opt-out of the geoip feature?  Ideally it would be nice if the relay
pool server could call the standalone geoipupdate executable, but that's
not necessary.  Worst-case scenario (but easiest to implement): please
add a knob to disable building of the relay pool server.

Please see my next message (yet to be transmitted) for why bundling a
copy this module isn't an option in Debian.

```
src/github.com/syncthing/syncthing/lib/geoip/geoip.go:21:2: cannot find package "github.com/maxmind/geoipupdate/v6/pkg/geoipupdate" in any of:
        /usr/lib/go-1.22/src/github.com/maxmind/geoipupdate/v6/pkg/geoipupdate (from $GOROOT)
        /<<PKGBUILDDIR>>/_build/src/github.com/maxmind/geoipupdate/v6/pkg/geoipupdate (from $GOPATH)
dh_auto_build: error: cd _build && go install -trimpath -v -p 4 -ldflags "-X github.com/syncthing/syncthing/lib/build.Version=v1.27.9                                -X github.com/syncthing/syncthing/lib/build.User=debian                                    -X github.com/syncthing/syncthing/lib/build.Host=debian                                    -X github.com/syncthing/syncthing/lib/build.Stamp=1722380825" -tags "noupgrade purego" github.com/syncthing/syncthing/cmd/stcompdirs github.com/syncthing/syncthing/cmd/stdisco github.com/syncthing/syncthing/cmd/stdiscosrv github.com/syncthing/syncthing/cmd/stevents github.com/syncthing/syncthing/cmd/stfileinfo github.com/syncthing/syncthing/cmd/stfinddevice github.com/syncthing/syncthing/cmd/stfindignored github.com/syncthing/syncthing/cmd/stgenfiles github.com/syncthing/syncthing/cmd/strelaysrv github.com/syncthing/syncthing/cmd/strelaysrv/testutil github.com/syncthing/syncthing/cmd/stsigtool github.com/syncthing/syncthing/cmd/stvanity github.com/syncthing/syncthing/cmd/stwatchfile github.com/syncthing/syncthing/cmd/syncthing github.com/syncthing/syncthing/cmd/syncthing/cli github.com/syncthing/syncthing/cmd/syncthing/cmdutil github.com/syncthing/syncthing/cmd/syncthing/decrypt github.com/syncthing/syncthing/cmd/syncthing/generate github.com/syncthing/syncthing/lib/api github.com/syncthing/syncthing/lib/api/auto github.com/syncthing/syncthing/lib/assets github.com/syncthing/syncthing/lib/automaxprocs github.com/syncthing/syncthing/lib/beacon github.com/syncthing/syncthing/lib/build github.com/syncthing/syncthing/lib/config github.com/syncthing/syncthing/lib/config/mocks github.com/syncthing/syncthing/lib/connections github.com/syncthing/syncthing/lib/connections/mocks github.com/syncthing/syncthing/lib/connections/registry github.com/syncthing/syncthing/lib/db github.com/syncthing/syncthing/lib/db/backend github.com/syncthing/syncthing/lib/dialer github.com/syncthing/syncthing/lib/discover github.com/syncthing/syncthing/lib/discover/mocks github.com/syncthing/syncthing/lib/events github.com/syncthing/syncthing/lib/events/mocks github.com/syncthing/syncthing/lib/fs github.com/syncthing/syncthing/lib/geoip github.com/syncthing/syncthing/lib/httpcache github.com/syncthing/syncthing/lib/ignore github.com/syncthing/syncthing/lib/ignore/ignoreresult github.com/syncthing/syncthing/lib/locations github.com/syncthing/syncthing/lib/logger github.com/syncthing/syncthing/lib/logger/mocks github.com/syncthing/syncthing/lib/model github.com/syncthing/syncthing/lib/model/mocks github.com/syncthing/syncthing/lib/nat github.com/syncthing/syncthing/lib/netutil github.com/syncthing/syncthing/lib/osutil github.com/syncthing/syncthing/lib/pmp github.com/syncthing/syncthing/lib/protocol github.com/syncthing/syncthing/lib/protocol/mocks github.com/syncthing/syncthing/lib/rand github.com/syncthing/syncthing/lib/rc github.com/syncthing/syncthing/lib/relay/client github.com/syncthing/syncthing/lib/relay/protocol github.com/syncthing/syncthing/lib/scanner github.com/syncthing/syncthing/lib/semaphore github.com/syncthing/syncthing/lib/sha256 github.com/syncthing/syncthing/lib/signature github.com/syncthing/syncthing/lib/sliceutil github.com/syncthing/syncthing/lib/stats github.com/syncthing/syncthing/lib/stringutil github.com/syncthing/syncthing/lib/structutil github.com/syncthing/syncthing/lib/stun github.com/syncthing/syncthing/lib/svcutil github.com/syncthing/syncthing/lib/sync github.com/syncthing/syncthing/lib/syncthing github.com/syncthing/syncthing/lib/testutil github.com/syncthing/syncthing/lib/tlsutil github.com/syncthing/syncthing/lib/upgrade github.com/syncthing/syncthing/lib/upnp github.com/syncthing/syncthing/lib/ur github.com/syncthing/syncthing/lib/ur/contract github.com/syncthing/syncthing/lib/versioner github.com/syncthing/syncthing/lib/watchaggregator github.com/syncthing/syncthing/lib/weakhash github.com/syncthing/syncthing/proto/ext
```

**Comment by sten0** [comment]
Simon Frei ***@***.***> writes:

>> [...] Unfortunately we can't use this in Debian because it's a non-free service (https://www.maxmind.com/) that costs money. [...]
>>
>> Making it optional will mean that all Debian users (including educational, commercial, scientific, etc) lose access to the feature--even subscribers to the paid service. [...]
>
> Can you expand on that please? The new dependency is client code dual licensed MIT and Apache 2, both are compatible with DFSG. I am not aware that interacting with non-free services makes a software non-free in debian. Especially the part about costing money/paid service confuses me - debian isn't about free as in beer, something can absolutely be compatible with DFSG and carry a price (not claiming maxmind's offering is that - we aren't packaging/shipping it).

I'm happy to expand on this this time.

First, the part that isn't my call: Maxmind's geoipupdate has been part
of the "contrib" section of the archive for some time, and this section
is not part of Debian.
  https://www.debian.org/doc/debian-policy/ch-archive.html#the-contrib-archive-area

"Contrib" is for legalistically free-software that is useless without
non-free things (mandatory subscriptions, proprietary firmware or
databases, trade secrets, toxic candy, non-free EULAs etc).  My
understanding is that Maxmind's geoipupdate was relegated to "contrib"
because it is useless without a signing up for an account to gain access
to a nonredistributable and problematic proprietary database.

  https://maxmind.com
  https://dev.maxmind.com/geoip/geolite2-free-geolocation-data
    * Not free because of "Discrimination Against Fields of
      Endeavors" https://www.debian.org/social_contract.1.0
                 https://www.maxmind.com/en/geolite2/eula
    * Various other restrictions in the EULA (ie §10, the bait and
      switch clause for a notice many users would not ever see)
    * §6.c !  It should be clear to anyone who takes the time to read
      the EULA that this sort of thing has no place in FLOSS.
    * "for any conflicts among the above 4 documents, the priority and
      precedence of interpretation is DPA, PP, WT and Creative Commons
      License."  This is a huge red flag that means "call your lawyers,
      here be dragons"...which is the literal meaning of draconian.

Software in "main" cannot link with, Depend on, Build-Depend on, or
Recommend software in "contrib" or in "non-free"; however, software in
"main" can Suggest (ie: user-initiated opt-in run-time plugins, call
optional external executables, etc) software in contrib or in non-free.

> I can see that it would be nicer if one could use other services or none at all, but that seems like a reasonable feature request not a problem for debian packaging. And as calmh said, barrying examples of actual users of the relay pool, a pretty low importance one.
>

Please see my previous message; this is a hard-blocking issue.  Without
a fix, users of our package are stuck with 1.27.7 or maybe
1.27.8--I haven't investigated 1.27.8 yet.

**Comment by imsodin** [comment]
For a quick and simple unblock n debian, I was about to suggest dropping to build/ship the relay pool server, as it's pretty unlikely any debian user is running it. However I just noticed you don't build/ship the relay pool server now, so there's definitely no ramification to "dropping" it - whatever that means, fully patching out that directory or somehow tell the relevant systems/tools to disregard it as it's not packaged.

And to avoid any misunderstanding: I am not against having such a knob. I just don't want to spend time on it if there's no benefit.

**Comment by sten0** [comment]
Simon Frei ***@***.***> writes:

> For a quick and simple unblock n debian, I was about to suggest dropping to build/ship the relay pool server, as it's pretty unlikely any debian user is running it. However I just noticed you don't build/ship the relay pool server now, so there's definitely no ramification to "dropping" it - whatever that means, fully patching out that directory or somehow tell the relevant systems/tools to disregard it as it's not packaged.
>
> And to avoid any misunderstanding: I am not against having such a knob. I just don't want to spend time on it if there's no benefit.
>

Currently Syncthing >1.27.7 fails to build from source in Debian (see
previous build log and error).  The benefit is enabling upward of ten
thousand users to use newer than 1.27.7.  This is a pragmatic,
quantifiable, and shared objective.  While there are many users who run
a relay server, it sounds like the "relay pool server" has exactly one
site installation...

The benefit is clear: Support tens of thousands of users by making
geoipupdate optional, or make building the "relay pool server" opt-in.

**Comment by imsodin** [comment]
What about my suggestion to "drop"/ignore the relay pool server, that you aren't shipping now anyway? I see you are already carrying a few patches, adding the equivalent of `rm -r ./cmd/strelaypoolsrv` can't be much of a burden - no chance of conflicts arising.

**Comment by sten0** [comment]
Simon Frei ***@***.***> writes:

> What about my suggestion to "drop"/ignore the relay pool server, that you aren't shipping now anyway? I see you are already carrying a few patches, adding the equivalent of `rm -r ./cmd/strelaypoolsrv` can't be much of a burden - no chance of conflicts arising.
>

Oh, that's what you meant.  Would you have taken the time to open an
upstream issue and to investigate and explain a problematic EULA if
hitting the problem with a hammer was an option?

What's the real problem here?  A build-time config (say
"nostrelaypoolsrv" would have solved this in much less time than we've
contributed to this discussion.

**Comment by imsodin** [comment]
Yeah thanks for explaining the contrib vs non-free distinction, should have expressed that explicitly before.

And we have progress: Originally it was about patching out the maxmind library, now it's not using relay pool srv. That's already possible: `go run build.go build <target>`, where target corresponds to a binary/package name in `./cmd`.

**Comment by sten0** [comment]
Simon Frei ***@***.***> writes:

> Yeah thanks for explaining the contrib vs non-free distinction, should have expressed that explicitly before.
>
> And we have progress: Originally it was about patching out the maxmind
> library, now it's not using relay pool srv.

No, that was a preemptive compromise I was offering to make things
easier for you.

> That's already possible: `go run build.go build <target>`, where target corresponds to a binary/package name in `./cmd`.

This is from a developer perspective :)  It's not possible to do this
from a Debian packaging perspective.  You used to have a build system
that would iterate over targets, create a list, then build the list.  At
that time we used the following to skip unwanted (or prohibited
targets):

  export DH_GOLANG_EXCLUDES := cmd/strelaypoolsrv \
                             cmd/stcli \
                             cmd/stcrashreceiver \
                             cmd/stupgrades \
                             meta($$|/) \
                             cmd/ursrv
  https://salsa.debian.org/go-team/packages/syncthing/-/blob/master/debian/rules?ref_type=heads#L28

I'm not sure where in the Go ecosystem this broke, but Syncthing wasn't
the only one that lost support, even though most packages still fully
support it.

**Comment by sten0** [comment]
Jakob Borg ***@***.***> writes:

> Right, so, to summarise:
>
> - Debian doesn't like the maxmind package for whatever reason

Did you know that you're legally liable to Maxmind to provide written
proof that you've deleted all copies of out-of-date GeoIPLite data,
including purging this from long-term backups?  It's in the EULA, and it
also affects all users.

> - Syncthing (the user facing program) doesn't have that package as a
> dependency

Agreed.

> - The two programs that currently do have that as a dependency are `cmd/strelaypoolsrv` (the relay pool server) and `cmd/ursrv` (the usage reporting server), neither of which should be distributed by Debian imho, since they have almost zero utility for anyone but ourselves

They're not distributed in Debian, but for some reason your
configuration enforces them.  Please see the message I just sent.

> Building syncthing as we recommend (`go run build.go build syncthing`) doesn't build or require the maxmind package.

I'm sorry but this isn't possible within a Debian packaging context.
Please see my willingness to save you effort and time even if that means
compromising.  It's still the Golang team's position that it would be
best to make it possible to build strelaypoolsrv without maxmind (or
using an alternative geoipupdate implementation).

**Comment by zhsj** [comment]
>  It's still the Golang team's position that it would be
best to make it possible to build strelaypoolsrv without maxmind (or
using an alternative geoipupdate implementation).

strelaypoolsrv was already excluded in the Debian package before, why bother building them now?
You should fix the debian/rules to rightly exclude the geoip package which is only needed by strelaypoolsrv.

**Comment by calmh** [comment]
I'm not seeing much sense made here, sorry. However you do your build, building Syncthing *does not require* the maxmind/geoupdate package. It doesn't need to be present on disk, it doesn't get downloaded, it doesn't get parsed.

Even assuming we still somehow thought it was a problem that it's mentioned in the module requirements, I'm not sure what you're even asking. What is an "optional dependency" that you want us to make it, when it's already *not* a dependency?

**Comment by sten0** [comment]
> > It's still the Golang team's position that it would be
> > best to make it possible to build strelaypoolsrv without maxmind (or
> > using an alternative geoipupdate implementation).
> 
> strelaypoolsrv was already excluded in the Debian package before, why bother building them now? You should fix the debian/rules to rightly exclude the geoip package which is only needed by strelaypoolsrv.

@zhsj Wow, way to throw a team member under the bus...  I opened this issue because you asked me to, advocated for your approach, and I would not have opened this issue nor CCed you in the initial message were this not the case.

Yes, it also appears something upstream broke our clean `DH_GOLANG_EXCLUDES` opt-out approach, and I've heard Syncthing isn't the only affected package, so it's not worth wasting any more Syncthing devs time on this issue.

@calmh @imsodin thank you for taking the time to engage with this issue--I truly appreciate it.  For this issue to have not been a waste of time, please note that Maxmind expects all GeoLite2 users to keep records that prove that they always have the most up-to-date copy of the GeoIP database.  By using the Geolite2 you also agree to send them hardcopy papermail proof of compliance should they ever request it.  This is in their EULA.  For the record, I'm not a lawyer and this is not legal advice.  That said, I hope that this you can profit from discovery by preparing in advance :)

**Comment by zhsj** [comment]
> > strelaypoolsrv was already excluded in the Debian package before, why bother building them now? You should fix the debian/rules to rightly exclude the geoip package which is only needed by strelaypoolsrv.
> 
> @zhsj Wow, way to throw a team member under the bus... I opened this issue because you asked me to, advocated for your approach, and I would not have opened this issue nor CCed you in the initial message were this not the case.
> 

Because you didn't mention maxmind/geoipupdate is only used by strelaypoolsrv, which is not built by the Debian package previously.

> Yes, it also appears something upstream broke our clean `DH_GOLANG_EXCLUDES` opt-out approach, and I've heard Syncthing isn't the only affected package, so it's not worth wasting any more Syncthing devs time on this issue.
> 

No, it's just you didn't write right DH_GOLANG_EXCLUDES pattern in `debian/rules` file. There is no bug for syncthing upstream nor dh-golang (tools provide DH_GOLANG_EXCLUDES syntax support).

**Comment by calmh** [comment]
Aight guys, I really appreciate the work you're doing and have been running Debian on my boxes since the late 90s, but this is super tedious and you should probably continue this in a Debian packaging related venue since there doesn't seem to be anything actionable here for us.
