### ISSUE TITLE
Syncthing Relay: need some more examples for systemd script

### ISSUE THREAD

**Issue by esaulenka** [syncthing/syncthing#9636]
### Feature description

Would be better to have more detailed https://github.com/syncthing/syncthing/blob/main/cmd/strelaysrv/etc/linux-systemd/default config.
In particular, it doesn't clear how to set parameters with quotes.

### Problem or use case

In my case, 
```
# Default settings for syncthing-relaysrv (strelaysrv).
NAT=true
STRELAYSRV_OPTS=-ext-address=":443" -provided-by="my server"
```

in the `systemctl status strelaysrv` output became
```
     CGroup: /system.slice/syncthing-relaysrv.service
             └─2611 /usr/bin/strelaysrv -nat=true -ext-address=:443 "-provided-by=my server"
```
Looks like it works as expected, but I haven't tried more complicated strings.
I tried change `"` to `\"` and put whole string into single quotes, but it doesn't help.

If would be better if someone more experienced would write examples how to use systemd's `EnvironmentFile`. 

### Alternatives or workarounds

---

**Comment by imsodin** [comment]
That's a task/question for systemd's documentation. If you want help for a concrete issue, you can probably get it on https://forum.syncthing.net. I am not saying we definitely wouldn't accept an example if it was contributed, but there's no point having a ticket open for this.
