### ISSUE TITLE
.HEIC instead of .JPG

### ISSUE THREAD

**Issue by Milka4610** [syncthing/syncthing#9642]
### What happened?

When i do synchronisation between my android 13 device and Windows 10 desktop PC it saves most of the .JPG files as .HEIC files.  I´d like to have only .JPG .
Can anybody please help me in this issue ? Best regards

### Syncthing version

v1.27.3

### Platform & operating system

Windows 10 Home

### Browser version

no

**Comment by tomasz1986** [comment]
Syncthing only syncs files as they are, it doesn't convert them in anyway, and especially not by changing the image format like that. You may want to check the phone camera app's settings whether you can choose the file type photos are saved in. If, for some reason, it saves them both as JPG and HEIC and you want to sync only the former, then add `*.HEIC` to ignore patterns for the folder in question.

If you still need further assistance with this, please open a new topic at https://forum.syncthing.net, as this tracker is used for clear bugs and feature requests only.
