### ISSUE TITLE
syncthing generate --gui-address

### ISSUE THREAD

**Issue by gitbls** [syncthing/syncthing#9645]
### Feature description

I'm building a syncthing plugin for [sdm](https://github.com/gitbls/sdm) so that RasPiOS users can create their own customized IMGs with syncthing already installed. sdm's goal is to enable the user to customize the IMG such that it boots up as close to _ready to run_ as possible, with little-to-no post-boot customization work required.

The basic `syncthing` plugin is working, but one thing I can't do with a "formal" interface is set the GUI listen address.  I am currently `sed`-ing config.xml to configure the desired setting. This works, but it's the method of last resort.

**Request:** Since the `syncthing generate` command enables setting several other configuration items, please enable this command to also set `--gui-address`. 

### Problem or use case

Described above in the feature description. This makes it easier for people to build syncthing-enabled Raspberry PI systems with assurance that a future syncthing version won't break sdm's syncthing plugin.

### Alternatives or workarounds

As mentioned above, today I'm sed-ing config.xml. While this works, if config.xml ever gets another item added to it with `127.0.0.1:8384` in it, the plugin will break, causing pain and suffering.

OK, it won't be the end of humanity as we know it but would be annoying for sure!

Thanks for your consideration.

**Comment by imsodin** [comment]
One alternative that would likely scale better than adding arguments to generate, is to make `syncthing cli config` be able to read/write config from the file instead of going through the API. That way you can first generate a config, and then use `syncthing cli config` to adjust whatever you want.

That should definitely not be the default behaviour, just an option, as when syncthing is running modifying config on disk is obviously not a good idea. We could even make that command check if the api is up and if so, abort (or go back to read/writing through the api).

**Comment by gitbls** [comment]
That sounds perfect for the sdm use case! I didn't mention in the OP, but sdm configures syncthing in the context of a (systemd-nspawn) container so there will never be a syncthing service running. `syncthing cli config` going directly at the file would be perfect.

It's super-easy to add additional arguments/parameters to an sdm plugin, so once such a capability is available in syncthing I'd be keen on adding support for a broader set of customizations to the plugin, and would definitely appreciate your insight into which would be the most beneficial to syncthing users (both new, getting started users as well as long-time experienced users).

Thanks!

**Comment by acolomb** [comment]
Instead of using `sed` on the config file created during `syncthing generate`, you could just as well prepare a minimal `config.xml` with only the desired options included.  That will be respected by `syncthing generate` and any missing options added when it finishes IIRC.  The GUI authentication is a bit special because it needs to get the password hashing right, that's mainly why we included special options for it.

**Comment by gitbls** [comment]
> Instead of using `sed` on the config file created during `syncthing generate`, you could just as well prepare a minimal `config.xml` with only the desired options included. That will be respected by `syncthing generate` and any missing options added when it finishes IIRC. The GUI authentication is a bit special because it needs to get the password hashing right, that's mainly why we included special options for it.

Thanks @acolomb but I think that's what I'm doing. I currently do the following 3 steps, which I extracted from the code (first and second commands are separate b/c 2nd command only done if `gui-user` and `gui-password` both provided by the sdm user; could be combined of course).
```
syncthing --generate $homedir/.local/state/syncthing
syncthing generate --gui-user "$gui__user" --gui-password "$gui__password"
sed -i "s#<address>127.0.0.1:8384</address>#<address>$gui__address:8384</address>#" $homedir/.local/state/syncthing/config.xml
```
There's also a slight complexity b/c the plugin provides flexibility for specifying the user that syncthing runs under. In any event you can see the code at https://github.com/gitbls/sdm/blob/master/plugins/syncthing starting at line 63.

To be clear, I believe that this code works, and correctly sets the gui-user, gui-password, and gui-address in config.xml. I was not thrilled about using sed, but found no supported alternative to modify the gui-address without actually running syncthing in the container. I'd prefer not to do that, although I did verify that I could make that work if necessary with something like:
```
syncthing --gui-address 0.0.0.0:8384 &
syncpid=$!
sleep 3
kill -s kill $syncpid
```

**Comment by acolomb** [comment]
I think you misunderstood.  You can just put a minimal `config.xml` in the correct place before calling the first `syncthing generate` command:

```
<configuration version="35">
    <gui enabled="true" tls="false" debugging="false">
        <address>0.0.0.0:8384</address>
    </gui>
</configuration>
```

This is simple enough that you can use any sed magic, heredoc with substitutions, xml generator or similar on it to pre-fill the desired GUI address.  The settings will be preserved into to final generated `config.xml` after `syncthing generate ...`.

**Comment by calmh** [comment]
Or set `STGUIADDRESS` in the environment or environment file for systemd or something?

**Comment by gitbls** [comment]
> I think you misunderstood. You can just put a minimal `config.xml` in the correct place before calling the first `syncthing generate` command:
Yes, indeed, I misunderstood. I'll give that a go. Thanks!

**Comment by gitbls** [comment]
> Or set `STGUIADDRESS` in the environment or environment file for systemd or something?

Thanks for the suggestion!

Since I'm a syncthing newbie of sorts, I'll review those variables in detail to see if there is potential user value for any of them, and awaiting feedback from sdm users taking the syncthing plugin out for a spin, to get an idea of what else could be leveraged.

**Comment by gitbls** [comment]
> > I think you misunderstood. You can just put a minimal `config.xml` in the correct place before calling the first `syncthing generate` command:
> 
> Yes, indeed, I misunderstood. I'll give that a go. Thanks!

This works. Thanks so much for the suggestion!

**Comment by acolomb** [comment]
Then I guess we don't have an immediate need to add another option.

**Comment by gitbls** [comment]
> Then I guess we don't have an immediate need to add another option.

Yep, I'm totally good for now! Thanks again for your help.
