### ISSUE TITLE
Transcoding fes

### ISSUE THREAD

**Issue by WX580** [syncthing/syncthing#9649]
### Feature description

The ability for syncthing to automatically transcode files after or preferably during syncing

### Problem or use case

I have a collection of FLAC files on my PC and want to sync them to my phone and transcode them to a smaller file type to save storage space

### Alternatives or workarounds

Transcoding manually to a second folder and syncing that folder between the 2 devices but I'm hoping for a fully automatic option

**Comment by calmh** [comment]
Sorry, no.
