### ISSUE TITLE
Starting Syncthing manually or automatically has different configurations

### ISSUE THREAD

**Issue by SpringWhisper** [syncthing/syncthing#9650]
### What happened?

My Syncthing is installed on a non-system disk. After the installation is complete, start and set up. I only changed the folders that need to be synced. After that, Syncthing starts automatically when Windows starts, and everything works fine.
However, if I turn off Syncthing in the GUI and then manually go to the installation directory and run Syncthing.exe, I see a new syncthing in the GUI, all default and with the device ID changed.
Why is this happening?

### Syncthing version

1.27.4

### Platform & operating system

Windows 11

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
