### ISSUE TITLE
Encrypted Receive-Only Folders Syncing with Each Other

### ISSUE THREAD

**Issue by Accademia** [syncthing/syncthing#9654]
### Feature description

Would it be possible for "Encrypted Receive-Only Folders" with the same folder ID to automatically sync with each other?

### Problem or use case

I have deployed "Encrypted Receive-Only Folders" with the same folder ID across multiple different NAS devices. However, I’ve noticed that these "Encrypted Receive-Only Folders" do not automatically sync data with each other. A client with a decrypted folder is required to update these "Encrypted Receive-Only Folders" to the latest data.

### Alternatives or workarounds

Is this a missing feature? Would it be possible for "Encrypted Receive-Only Folders" with the same folder ID to automatically sync with each other? (The encrypted data should be the same, right?)

**Comment by imsodin** [comment]
Indeed this should already be working as is. Please use the forum - https://forum.syncthing.net - to describe and get help troubleshooting your issue. That's the better venue for the troubleshooting that the issue tracker, as it reduces noise and there are a lot of helpful people on the forum. If an actionable issue is discovered during that, an issue here with all the required info can be opened. Thanks.
