### ISSUE TITLE
UX/UI: Inconsistent information and inconclusive "override changes" action button in Out of Sync situation

### ISSUE THREAD

**Issue by cruftex** [syncthing/syncthing#9658]
### What happened?

I am trying to sync pictures from my mobile phone to the computer. Somehow, the folder got out of sync. The probable cause might be an out of disk space situation on the computer. However, the information shown now in the UI does not make any sense. I upgraded the phone to 1.27.10 and restarted syncthing on both devices.

The phone shows:

![Screenshot_20240821_091847_Syncthing](https://github.com/user-attachments/assets/1e052eff-72d4-43d7-bc54-870426dfa231)

The computer shows for the phone (phi42):

![image](https://github.com/user-attachments/assets/591506e6-8fbb-467a-bb31-b373db56e906)

And for the folder:

![image](https://github.com/user-attachments/assets/b9074ff2-ad4d-4703-83b2-7ae8ca263777)

Syncing is hard and all sort of things can happen that lead to an Out of Sync situation. However, whenever it happens with syncthing, I am feeling irritated and lost most of the time.

- The folder state on the computer says "Up to date" but the phone folder says "Out of sync". Probably, this is the case, because the computer knows it got all changes from the phone. However, the information that bidirectional syncing is disrupted right now is missing. A user seeing an "Up to date" and green might misinterpret this and think everything is synchronised. Which is not the case. Analysing the situation, the phone has an image which is not present on the computer. This is not resolved yet, the computer may or may not have all relevant files. So it cannot be Up to date at this time.
- The device information for the phone on the computer says "Syncing". That is not true. Nothing is happening at the moment. The state should say "Out of sync"
- On the phone the status shows "Out of Sync" and there is a button saying "override changes". What does that mean? Does it refer to local or remote changes? How can I find out about the changes that cause the problem? Given the situation, I would expect that I have two choices: "Accept changes from device XY and discard local changes", "Accept local changes and discard changes on remove devices". Besides, IMHO, "override" is technical terminology and not a good choice for the UI

So why are things out of sync, anyways? Let's click on the out of sync items on the computer:

![image](https://github.com/user-attachments/assets/2457c8ec-f81f-4143-89f1-ce3280534521)

I cannot find the file on the computer. Should "0 B" mean that it was deleted?

When I try the same via the Web GUI on the phone it is showing this:

![Screenshot_20240821_110001_Syncthing](https://github.com/user-attachments/assets/cac8bcd6-5bd3-467e-b097-c21887f3f00c)

This looks different to the same dialog on the computer and somewhat broken.

### Syncthing version

v1.27.10

### Platform & operating system

Ubuntu 22.04 / Android

### Browser version

-

**Comment by calmh** [comment]
My interpretation is that there is a file that was deleted on the computer but not applied on the phone, because the phone is send-only. Hence the phone is out of sync, but provided an override option to enforce its state on the rest of the world instead of applying (because it's set to be send-only).

**Comment by imsodin** [comment]
The bad UX of that button in the android app is known, an improvement is almost ready (though blocked by a combo of time-constraints and google play annoyances, don't expect a quick fix): https://github.com/syncthing/syncthing-android/issues/1769

As for the rest that looks more like a support request than a clear bug or feature request to me. If calmh's infos don't explain it yet, please use the forum - https://forum.syncthing.net/ - to get more help. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by cruftex** [comment]
@calmh I actually did not remember I put the phone in send only. Good catch.

@imsodin 
Thanks for the referral on the button issue! I do understand what had happened. It is good to see that there is an improvement on the way.

I would see the following things as bug or feature request with potential for an improvement:

- Out of sync item list on computer is not useful and wrong. There is no 0 B file anywhere. It should say deleted.
- Out of sync item list on the phone is confusing. There are colour codes shown that are not used. On the listed item is a symbol that is not explained.
- Device state on computer says "Syncing". This is wrong. It should be "Waiting for user input"

Also, I think, it would be more correct that the conflict is shown on the computer and not on the phone in this scenario.
Consider I am the owner of the phone and the computer is owned by another person. The folder on my phone is in "Send only" mode. By common sense, a "Send only" folder can never be out of sync. Ideally, the computer should say "I cannot send changes since peers are not in receive mode".

Should I open separate issues and try to be more clear?
