### ISSUE TITLE
Use BLAKE-3 hashing

### ISSUE THREAD

**Issue by yonas** [syncthing/syncthing#9682]
### Feature description

[It's very fast](https://www.infoq.com/news/2020/01/blake3-fast-crypto-hash/):

![BLAKE3-benchmark](https://github.com/user-attachments/assets/a5ca64ac-97d2-4b0f-b370-980c4e28f6e1)

### Problem or use case

File hashing.

### Alternatives or workarounds

Continue using SHA-256.

**Comment by imsodin** [comment]
I am closing this as not planned.

Changing the hash would be a huge task for a bunch of reasons, chief among them ensuring compatibilty. Also it means rehashing everything. I don't think this is a reasonable thing to do unless a major issue comes up with the hash we are using, and that's unlikely to ever happen with sha-256.

**Comment by yonas** [comment]
> Changing the hash would be a huge task for a bunch of reasons, chief among them ensuring compatibility.

Sorry, what follows is a bit of a rant.

I've heard this argument many times with regards to changing a hash. Why do developers write their code as though the hash they chose will never ever change...? This is more of a bad programming practice than an excruciatingly complicated programming problem.

There ought to be a software development pattern that would allow for extremely easy hash upgrades. Something as simple as versioning the file format would decouple the backend server and frontend clients.

> Also it means rehashing everything.

Not that big of a deal, especially when BLAKE-3 is as efficient as it is.

Anywho. Carry on.

**Comment by calmh** [comment]
You rant is also unfounded, missing the fact that the actual hash function is often just a fraction of the cost of the entire operation, plus the fact that hardware acceleration comes into the picture. For example, here's our HashFile benchmark with just replacing `sha256.New()` with `blake3.New(32, nil)` from https://github.com/lukechampine/blake3:

## Blake3

```
goos: darwin
goarch: arm64
pkg: github.com/syncthing/syncthing/lib/scanner
cpu: Apple M3 Pro
BenchmarkHashFile
BenchmarkHashFile-12                  40          28060036 ns/op         635.27 MB/s       98618 B/op        565 allocs/op
PASS
ok      github.com/syncthing/syncthing/lib/scanner      1.806s
```

## Sha256

```
goos: darwin
goarch: arm64
pkg: github.com/syncthing/syncthing/lib/scanner
cpu: Apple M3 Pro
BenchmarkHashFile
BenchmarkHashFile-12                 100          11551052 ns/op        1543.22 MB/s       80221 B/op        563 allocs/op
PASS
ok      github.com/syncthing/syncthing/lib/scanner      2.142s
```
