### ISSUE TITLE
Rename `/meta.js` request to `/meta` to avoid caching problems?

### ISSUE THREAD

**Issue by vladyslav2** [syncthing/syncthing#9699]
### Feature description

I usually do this to cache all static files:

```bash
  location = /favicon.ico { access_log off; log_not_found off; }
  location = /robots.txt { access_log off; log_not_found off; }
  location ~* \.(jpg|jpeg|png|tiff|gif|webp|xml|yml|ogg|ogv|svg|svgz|eot|otf|woff|woff2|mp4|ttf|rss|atom|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|ppt|tar|mid|midi|wav|rtf|pdf|txt|js|css|bmp|pnm|pbm|ppm)$ {
        access_log off;
        expires 30d;
    }
```

Cannot say it help much, and honestly usually brings more troubles. But I still keep doing this.
It does include caching for `.js` files

### Problem or use case

I was not able to understand why I cannot login (using 1.27). Found couple old issues connected with cookies but it seems like on my end issue was not about the cookie.

After trying everything I understood that `GET /meta.js` request keep failing and there is no meta.js file in the static folder.
trying to run syncthing locally and saw that `/meta.js` actually returns device-id / some important information.

Removing caching for js from nginx did the thing.

### Alternatives or workarounds

Maybe it make sense to rename request `/meta.js` just to `/meta` ?

**Comment by bt90** [comment]
It's a weird endpoint. Loosely related: #9523

**Comment by calmh** [comment]
It's not that weird; it's a javascript file. We even set an explicit HTTP headers to entirely forbid caching of it.

I don't see a problem here other than overly aggressive proxy configuration depending on assumptions, overriding our best efforts to communicate what is the appropriate behavior.

**Comment by vladyslav2** [comment]
@calmh Jakob I actually agree with you.

But perhaps its possible to add notification /  error log to have a clue whats wrong?
right now its just reloads so one would think there is a problem with credential / syncthing configuration itself
