### ISSUE TITLE
Unable to modify the default directory for creating folders

### ISSUE THREAD

**Issue by seajelly** [syncthing/syncthing#9703]
### What happened?

I hope that when creating a folder, the default path is no longer /root/, but /opt/syncthing/data.
Modification process:
1. Modify the config.xml file as shown below. I changed the default path to /opt/syncthing/data
![image](https://github.com/user-attachments/assets/8d440b20-1653-4b3c-9013-ba63cc4657bb)

2. Restart syncthing.service
3 When creating a folder on the web page, the default path is still /root
![image](https://github.com/user-attachments/assets/5b0ce8c1-3a6a-4e8b-94ad-ea280d22955a)

5. My syncthing.service configuration is as follows
![image](https://github.com/user-attachments/assets/c2c3d4e2-82d0-4f98-993c-2097a08d051f)

### Syncthing version

v1.27.10

### Platform & operating system

ubuntu22.04LTS

### Browser version

chrome

**Comment by calmh** [comment]
You appear not to have changed the default folder path, but the folder path for a folder called "default", which is not the same thing.

This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
