### ISSUE TITLE
Demote the level of " XXX already connected to this device" to DEBUG (is: INFO)

### ISSUE THREAD

**Issue by wsw70** [syncthing/syncthing#9715]
### Feature description

Lower the logging level for `XXX already connected to this device` messages in the log from `INFO` to `DEBUG`.

### Problem or use case

There are many lines in the logs coming from an expected race condition when two devices connect. See for instance https://forum.syncthing.net/t/connected-to-already-connected-device/13190 for an example of a related question.

Since they are expected and do not indicate an error they are not useful to see in a normal, production log. The sheer number of these messages makes it difficult to find actually useful ones.

### Alternatives or workarounds

Filter out the messages if the logging interface allows it - this will not help with `syncthing*.log` ones for instance on Windows.

**Comment by dev-saw99** [comment]
@wsw70 I would like to work on this issue. Could you please assign it to me ?

**Comment by tomasz1986** [comment]
Issues are not assigned here. If you've got a solution to the problem, just file a PR 🙂.

**Comment by dev-saw99** [comment]
I have raised a PR for this issue https://github.com/syncthing/syncthing/pull/9722
