### ISSUE TITLE
Ignoring symbolic links when syncing on android as well

### ISSUE THREAD

**Issue by Managor** [syncthing/syncthing#9725]
### Feature description

I wish to be able to set a device so that symbolic links are not synchronized onto that.

### Problem or use case

I'm unable to sync symlinks to my android phone so the syncing gets stuck at 99% and will never move. This annoys me and masks other issues that might cause the syncing to fail. 

### Alternatives or workarounds

I have not considered workarounds

**Comment by imsodin** [comment]
We already do this on windows. So it seems like a reasonable request to make that configurable (and ignore by default on windows, and probably also android). Technically it's not ignoring but marking it as unsupported, but the effect is the same.

**Comment by KapilSareen** [comment]
Hi @imsodin, I'm interested to work on this issue can you assign this to me?

**Comment by KapilSareen** [comment]
Hi @imsodin, I'm interested to work on this issue can you assign this to me?

**Comment by imsodin** [comment]
Updated the ticket title to reflect how the PR #9782 will address it, for the changelog.
