### ISSUE TITLE
Wrong documentation: receive-only is now receiveonly

### ISSUE THREAD

**Issue by bjo81** [syncthing/syncthing#9727]
### What happened?

Some time ago I wanted to download 120GB from a server to an empty folder, set type to `receiveonly` and it was unknown, so Syncthing defaulted to `sendreceive` and deleted 120GB on the server.
To prevent this issue again, I took a look into https://docs.syncthing.net/users/config.html and it still says `receive-only` - which was unknown now and it defaulted to  `sendreceive`. Oops, same issue again.

After switching in the webinterface Syncthing showed now:

```
Ready to synchronize "bjo" (bjo) (receiveonly)
```

So it seems it's `receiveonly` now, and not as mentioned in the docs `receive-only`.

### Syncthing version

v1.27.12

### Platform & operating system

Linux amd64

**Comment by bjo81** [comment]
Ok, it's `receiveonly` in https://docs.syncthing.net/users/config.html and https://docs.syncthing.net/users/foldertypes.html speaks of `receive-only`, so it seems I mismatched this.

**Comment by acolomb** [comment]
You really shouldn't be fiddling with config.xml directly unless you have the reference open (which lists the correct values).  Use the Web GUI instead, much less error-prone.

**Comment by ProactiveServices** [comment]
Would it be more appropriate for syncthing to fatal if it comes across a folder type that it doesn't recognise?
