### ISSUE TITLE
connections: point-to-point links should still be announced

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing#9730]
I'm afraid this has an undesirable side effect:

https://github.com/syncthing/syncthing/blob/8ff670c5643cefdcb26d841123e5b71523dcb4e8/lib/connections/util.go#L62-L81

We should still announce those IPs to the global discovery server.

_Originally posted by @bt90 in https://github.com/syncthing/syncthing/issues/9720#issuecomment-2366731067_

**Comment by bt90** [comment]
IMHO GetLans should have a parameter to control whether "virtual" LAN IPs should be ignored.
