### ISSUE TITLE
WebUI keeps disconnecting

### ISSUE THREAD

**Issue by enboig** [syncthing/syncthing#9733]
### What happened?

WebUI keeps warning about a disconnection and automatically reconnects.

I think it is related to #8569 (where I would post if I could). I want to add that I migrated from apt install to docker moving all my data; maybe some configuration has to be updated? WebUI reports automatic updates as disabled.

### Syncthing version

v1.27.12, Linux (64-bit Intel/AMD

### Platform & operating system

Linux/docker

### Browser version

Firefox

**Comment by calmh** [comment]
It's not related to that issue, because that was fixed two years ago. I think you need to use the browser console to figure or which HTTP call is failing and why. Currently this is not actionable.

**Comment by AudriusButkevicius** [comment]
Suggest you move this to the forums, as it feels like a support issue related to your setup.
