### ISSUE TITLE
I can't log in

### ISSUE THREAD

**Issue by fe2-Nyxar** [syncthing/syncthing#9739]
### Feature description

I tried to log in but i couldn't my credentials are saved on the browser and keepassxc so I'm pretty sure it's the correct password/username, and i tried every command on the wiki and in the documentation, and that's why i'm here.

os: linux (nixos)

### Problem or use case

login

### Alternatives or workarounds

N/A

**Comment by nekr0z** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
