### ISSUE TITLE
Run on mobile data, run on metered wi-fi desktop options

### ISSUE THREAD

**Issue by RustoMCSpit** [syncthing/syncthing#9745]
### Feature description

Android has these settings but not desktop

### Problem or use case

.

### Alternatives or workarounds

.

**Comment by RustoMCSpit** [comment]
similar / the same? https://github.com/syncthing/syncthing/issues/8394

**Comment by imsodin** [comment]
Indeed duplicate of https://github.com/syncthing/syncthing/issues/8394
