### ISSUE TITLE
Deletion and renaming of directories do not trigger synchronization.

### ISSUE THREAD

**Issue by d960124** [syncthing/syncthing#9749]
### What happened?

The directory structure is：
MainFolder/ 
  ├── SubFolder1/
  │   ├── TargetFolder/
  ├── SubFolder2/
  │   ├── TargetFolder/
  └── SubFolder3/
      ├── TargetFolder/

The rules are:
!**/TargetFolder/**
*

When renaming `SubFolder1` to another name, such as `Sub`, the new `Sub` directory does not get synchronized to other nodes.
When deleting `SubFolder2`, the `SubFolder2` directory on other nodes is also not removed.
According to the rules, I need to synchronize the `TargetFolder` directory under `SubFolderX`. When deletion or renaming occurs, the path of the `TargetFolder` directory should also be modified, which should trigger synchronization, right? (Each `SubFolderX` contains a `TargetFolder` directory.)

### Syncthing version

v1.27.12

### Platform & operating system

win10_64

### Browser version

EDGE

**Comment by tomasz1986** [comment]
`!/TargetFolder/` means that you are ignoring only what is inside directories called `TargetFolder` located in the **root** path of the main Syncthing folder. If you want to ignore `TargetFolder` that is inside yet another folder, then you need to modify your patterns to:

```
!TargetFolder/
*
```

Note that there should be no forward slash `/` before `TargetFolder`.
