### ISSUE TITLE
Firefox, dark theme: device ID is hard to read

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [syncthing/syncthing#9757]
### What happened?

Actions -> Show ID -> ID is slightly hard to read because it is printed in grey on black.

Screenshot:

![2024-10-05 20 10 50](https://github.com/user-attachments/assets/674df126-aea7-4fe7-a7cd-ba75b03e9689)

Cf. ##6115.

The remedy would be to use a whiter foreground font.

### Syncthing version

v1.27.12

### Platform & operating system

Two Linux PCs, one Windows PC

### Browser version

Firefox (release version) and Firefox ESR

EDIT: The theme set _within_ Syncthing is 'Default' on some of the affected PCs and 'Dark' on the other.

**Comment by acolomb** [comment]
There is an explicit override for text color `#666` on `#3B3B3B` in the dark theme.  That is indeed very low contrast.  #9758 just removes the theme override for the text color, so it matches the base text color.  And it sets the font weight to bold, to further improve readability.
