### ISSUE TITLE
new error messages on lost connection, not seen previously

### ISSUE THREAD

**Issue by rdslw** [syncthing/syncthing#9769]
### What happened?

I recently upgraded to 1.27.12 (from 1.26.x) on a MacOS machine. This is a laptop which goes frequently offline (as every laptop).

Since upgrade, I'm seeing new message about lost connection on other machines:
_"Lost connection: LAPTOPID reading length: remote error: tls: bad record MAC (0 remain)"_

(message on previous version was: _"Lost connection: LAPTOPID read timeout (0 remain)"_

Current message while more descriptive is probably too strong suggesting some problem with bad MAC record in TLS. Especially as it is repeated every time the device goes offline. 

Frequency of messages and them being INFO is fine IMO, but this is normal situation when one station goes offline, while message suggest some bigger problems.

**Would you consider some rewording ?** Of course detecting this would be perfect, but it is rather impossible due to the fact that machine going offline does it laptop-style (read: clam fast down ;).

### Syncthing version

v.1.12.12

### Platform & operating system

macos seqoia > linux

### Browser version

not relevant

**Comment by calmh** [comment]
"tls: bad record MAC" indicates something bad happened to the connection. It's not new, there are mentions of it on the forum going back a decade.

**Comment by rdslw** [comment]
Thank you kindly for checking. 

It definitely started appearing recently, under the same network situation(s), with two changes: syncthing (go stack) update, and macos update. 
Looking more into it, this message appears in relation only to macos syncthing station, yet this is the only one with laptop-type network, so is hard to narrow as macos only.
