### ISSUE TITLE
DNS not Resolving - DNSSec Validation Failed

### ISSUE THREAD

**Issue by luckylinux** [syncthing/syncthing#9771]
### What happened?

While attempting `apt dist-upgrade` on Ubuntu Noble, the Upgrade hangs since the new `syncthing` Package cannot be downloaded
```
Ign:1 https://syncthing-apt.svc.edge.scw.cloud syncthing/stable amd64 syncthing amd64 1.28.0                                           
Ign:1 https://syncthing-apt.svc.edge.scw.cloud syncthing/stable amd64 syncthing amd64 1.28.0
Ign:1 https://syncthing-apt.svc.edge.scw.cloud syncthing/stable amd64 syncthing amd64 1.28.0
Err:1 https://syncthing-apt.svc.edge.scw.cloud syncthing/stable amd64 syncthing amd64 1.28.0
  Could not resolve 'syncthing-apt.svc.edge.scw.cloud'
E: Failed to fetch https://syncthing-apt.svc.edge.scw.cloud/dists/syncthing/stable/binary-amd64/syncthing_1.28.0_amd64.deb  Could not resolve 'syncthing-apt.svc.edge.scw.cloud'

```

A quick `resolvectl query` shows that DNSSec has some Issues, thus the DNS does NOT get resolved correctly:
```
resolvectl query syncthing-apt.svc.edge.scw.cloud
syncthing-apt.svc.edge.scw.cloud: resolve call failed: DNSSEC validation failed: failed-auxiliary
```

An online [DNS Lookup](https://mxtoolbox.com/SuperTool.aspx?action=a%3asyncthing-apt.svc.edge.scw.cloud&run=toolpage) seems to suggest that there is actually some DNS configured for the Hostname.

So it's "just" DNSSec not working ...

EDIT 1: Repository Configuration in `/etc/apt/sources.list.d/syncthing.list`:
```
deb [signed-by=/etc/apt/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable
```

### Syncthing version

v1.27.12

### Platform & operating system

Linux AMD64 - Ubuntu Noble 24.04

**Comment by calmh** [comment]
That domain has no DNSSec as far as I can tell, and I'd be surprised if it had.

**Comment by luckylinux** [comment]
Then maybe it should NOT be a mirror ? Isn't it possible to put the .deb File on GitHub Releases so it could be downloaded manually ?

**Comment by talha5389** [comment]
This is also happening to me

**Comment by luckylinux** [comment]
> This is also happening to me. My `systemd-resolved` config is below
> 
> ```
> DNS=9.9.9.9 149.112.112.112 1.1.1.1 1.0.0.1 8.8.8.8
> DNSSEC=yes
> DNSOverTLS=yes
> ```

Apparently they do NOT care about those that use DNSSec. And we are expected to just disable it to get over the update :expressionless: 

Alternatively one can resolve the Host using a DNS Lookup online and set the required stuff in `/etc/hosts` for instance:
```
9406fdcf-bae6-48bf-8037-bf97d343cd6c.cf29f953-a070-47e1-b184-3f12efa567ca.cache01.edge.scw.cloud syncthing-apt.svc.edge.scw.cloud
51.159.80.27 9406fdcf-bae6-48bf-8037-bf97d343cd6c.cf29f953-a070-47e1-b184-3f12efa567ca.cache01.edge.scw.cloud
51.159.13.88 9406fdcf-bae6-48bf-8037-bf97d343cd6c.cf29f953-a070-47e1-b184-3f12efa567ca.cache01.edge.scw.cloud
```

But this is a dirty Hack at best.

**Comment by calmh** [comment]
We just use a cloud CDN service. If you're saying they've tried to set up DNSSec and done it wrong, that might be worth reporting to them. On the other hand, if you're just expecting there to be DNSSec when there isn't, then you need to adjust expectations. It looks to me like the latter, but I'm not an expert on DNSSec and don't want to be.

**Comment by luckylinux** [comment]
Well I can (kinda) see your point from the Point of View of the Project. You are not that mirror's Admin and you don't want to be. Fair enough.

Nevertheless it's quite inconvenient for end-Users to have to do manual fixes "just" because of one badly behaving Mirror.

DNSSec has been around for a while now. Same with DNS over TLS.

And yeah, there still are a lot of Quirks for both. Also the "Big" Players don't get it right sometimes.

Cloudflare `1.1.1.2` having the wrong Certificate thus DNS over TLS will fail.

Debian Mirrors over HTTPS also having the wrong Domain Certificate that obviously causes an Error as well.
