### ISSUE TITLE
在文件件共享时，如果用密码加密的情况下，会出现syncing: finishing: pull: generic error

### ISSUE THREAD

**Issue by 109car** [syncthing/syncthing#9772]
### What happened?

前置条件：
已经使用带密码共享文件夹工作了一年多。
window 10 pro x64 
鸿蒙4.2 兼容Android12

问题描述：

从10月17日开始突然出现generic error，同步不了文件。出问题的是win10 这边的软件端，无法从手机端拉取文件过来。

通过搜索Google，发现一个类似的问题

https://github.com/syncthing/syncthing/issues/8843

问题中提到使用了中文目录以及加密文件夹。管理员回复到跟中文没有关系，管理员是对的。
在我这个场景中并没有使用中文目录，这个bug应该是win10客户端这边的问题。

解决方法：
去掉加密的密码就能解决问题。

用中文描述的原因是，已经有个英文的类似bug描述了，用中文可以让更多使用者看到先规避掉bug而不影响使用。

### Syncthing version

v1.28.0 win10
1.27.12.1 Android

### Platform & operating system

windows 10 pro x64

### Relevant log output

```shell
[TMRIA] 2024/10/17 15:53:25 INFO: Puller (folder "Mx5-DCIM" (m5dc), item "Camera\\IMG_20241017_151623.jpg"): syncing: finishing: pull: generic error
[TMRIA] 2024/10/17 15:53:25 INFO: Puller (folder "Mx5-DCIM" (m5dc), item "Camera\\cache\\latest\\IMG_20241017_140502.thumbnail"): syncing: finishing: pull: generic error
[TMRIA] 2024/10/17 15:53:25 INFO: Puller (folder "Mx5-DCIM" (m5dc), item "Camera\\IMG_20241017_154146.jpg"): syncing: finishing: pull: generic error
[TMRIA] 2024/10/17 15:53:25 INFO: Puller (folder "Mx5-DCIM" (m5dc), item "Camera\\IMG_20241017_151611.jpg"): syncing: finishing: pull: generic error
[TMRIA] 2024/10/17 15:53:25 INFO: Puller (folder "Mx5-DCIM" (m5dc), item "Camera\\IMG_20241017_151614.jpg"): syncing: finishing: pull: generic error
[TMRIA] 2024/10/17 15:53:25 INFO: Puller (folder "Mx5-DCIM" (m5dc), item "Camera\\IMG_20241017_151545.jpg"): syncing: finishing: pull: generic error
```

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by 109car** [comment]
No, it is a bug, this is a bug that occurs when using a password, but it doesn't always happen
