### ISSUE TITLE
Disabled checkbox panels don't respect dark theme

### ISSUE THREAD

**Issue by Terrance** [syncthing/syncthing#9776]
### What happened?

A minor cosmetic issue which can be seen e.g. for introducer/auto-accept options of an untrusted device:

![image](https://github.com/user-attachments/assets/c18c0e64-4b81-46fb-9950-c513359bb34a)

These styles are defined in overrides.css, and could perhaps do with `@media (prefers-color-scheme: dark)` variants:

https://github.com/syncthing/syncthing/blob/cc09f0170df7df8775b6f9419c85d1faa7319599/gui/default/assets/css/overrides.css#L530-L540

### Syncthing version

v1.27.12

### Platform & operating system

Windows 10

### Browser version

Firefox 132.0

**Comment by tomasz1986** [comment]
The main problem here is that the `disabled` attribute used on a `div` in itself is invalid HTML.

> The disabled attribute is supported by `<button>`, `<fieldset>`, `<optgroup>`, `<option>`, `<select>`, `<textarea>` and `<input>`.

See: https://developer.mozilla.org/docs/Web/HTML/Attributes/disabled

However, it's used like that in the GUI all over the place, so it wouldn't be feasible to change the code in one place only. Even though adding those styles to other themes means basically expanding on the current hack, it's likely the easiest solution…
