### ISSUE TITLE
docker discovery server

### ISSUE THREAD

**Issue by iagonavel** [syncthing/syncthing#9780]
### What happened?

discovery server container don't start

### Syncthing version

v1.28

### Platform & operating system

linux/amd64

### Relevant log output

```shell
discosrv: error: unknown flag -t, did you mean one of "-h", "-d", "-v"?
```

**Comment by calmh** [comment]
It has updated a bit, including command line flags. I don't think there was ever a `-t` flag, but if you're passing `-http` which was accepted previously you'll want to express that as `--http` now.
