### ISSUE TITLE
File Versioning <any> does not creat .stversions Dir. Unable use Versioning on local Syncthing Instance running on Windows11 and Ubuntu

### ISSUE THREAD

**Issue by NEBELWAENDE** [syncthing/syncthing#9781]
### What happened?

.stversions Dir or alternate Dir is not been createt under Folder we like to synchronize - synchronization itself works fine.

### Syncthing version

v.1.28.0

### Platform & operating system

Ubuntu 22.04.3 and Windows11

### Browser version

Brave current

### Relevant log output

```shell
Dont see log Entries
```

**Comment by tomasz1986** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - [forum.syncthing.net](https://forum.syncthing.net/) - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

On a side note, please keep in mind that versions are only created for files that have been edited on a remote devices, not files edited locally.
