### ISSUE TITLE
Syncthing Docker container only listening on IPv6, unable to access Web GUI via IPv4

### ISSUE THREAD

**Issue by disanrencheng** [syncthing/syncthing#9787]
### What happened?

When running Syncthing in a Docker container, the Web GUI (port 8384) is only listening on IPv6 addresses, preventing access via IPv4. The netstat output shows:
tcp6       0      0 :::8384                 :::*                    LISTEN

### Syncthing version

v1.28.0

### Platform & operating system

Linux VM-4-8-centos 3.10.0-1160.108.1.el7.x86_64 #1 SMP Thu Jan 25 16:17:31 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Relevant log output

```shell
docker-compose.yml 配置：

syncthing:
  image: syncthing/syncthing:latest
  container_name: syncthing
  network_mode: host
  environment:
    - STGUIADDRESS=0.0.0.0:8384
  volumes:
    - /home/verus/syncthing:/var/syncthing
  restart: always
```
Docker version 26.1.3, build b72abbb
Attempted Solutions:
Modified GUI address setting in config.xml to 0.0.0.0:8384
2. Explicitly specified STGUIADDRESS environment variable in docker-compose.yml
3. Checked and temporarily disabled IPv6 on the host system
4. Cleaned Docker cache and re-pulled the image
5. Restarted Docker service and Syncthing container
None of the above methods resolved the issue; Syncthing still only listens on IPv6 addresses.
Assistance Requested:
1. Are there any known configuration issues with the Syncthing Docker image that could cause this behavior?
Are there any other configuration options or environment variables that can force Syncthing to use IPv4?
Would you recommend trying a different version of the Syncthing image?
Are there any other diagnostic steps that could help pinpoint the issue?
Additional Information:
If any additional logs, configuration files, or system information are needed, please let me know, and I will provide them promptly.
Thank you for your help and support!
```

**Comment by bt90** [comment]
I think you're getting confused by syncthing using a dual-stack socket here which supports IPv4 and IPv6.

Let's carry this over to our support forum: https://forum.syncthing.net/

**Comment by disanrencheng** [comment]
I made a mistake. The port listening abnormality was caused by a third-party operation and maintenance panel I installed, not a Syncthing issue
