### ISSUE TITLE
Backup from phone devices; functionality not really possible at present

### ISSUE THREAD

**Issue by tickerguy** [syncthing/syncthing#9795]
### Feature description

Syncthing considers devices connected to be "peers"; folders can be set to "send only" or "receive only", but there is no "archival source" setting, which is distinct from those two.  "Archival source" on a source folder (at the device) is defined as "any file in here is to be echoed to the connected peer(s) of this device, but deletions once sent are not to be propagated." 

This is quite useful for any source of data that you want synchronized, but once synchronized from an "Archival source" folder on a given device you want to be sure will not be removed from the destination if the source file on that device is removed.

### Problem or use case

A device (phone is most-likely but not necessarily) that creates content that needs to be archived at another location, but the copy needs to be one-way and write-only -- that is, removing the source file once the copy has been made does not result in it being removed from the destination end.  This gets more important if there is more than one source against a given repository.

If I set the repository folder on the connected "dump location" to "receive only" then I get half of it, but only half.  That is, if I set "receive only" then if the sending device (e.g. phone) deletes the files out of the camera folder that deletion will propagate to the receiving machine.  There appears to be way to avoid that happening other than extremely careful coordination (e.g. make sure they're on the receiving side, then move them OUT of the SyncThing folder, which will then automatically propagate the deletion back to the phone.)  This is fraught with serious risk, especially if there is more than one source device that might dumping into a single recipient location because in that case you have to set "send only" on the sending phones or the other device's content gets copied back, and once you do that then coordination without making a mistake and losing data becomes quite difficult.

### Alternatives or workarounds

Setting each phone to "send only" and the repository to "receive only" appears to be about the only way to sort-of do this, but it adds material danger because you have no clean indication whether sync is complete (since that will show the two "out of sync" because they are) and you must move the files on the destination and then, once done, remove them from the source.  If you remove a file on the source first it is removed from the destination since being set "receive only" it did receive the change.  (My current device, a Pixel 8, renames "trashed" images ".trashed" and the original is, when I do that with "receive only" set on the machine to which I dump them, is removed and the ".trashed" copy is sent over.)  I can prevent the ".trashed" copy from being sent with the "ignore patterns" option on the source but not the destruction of the archived copy.

The intent of "Archive Only" is to allow a user to, for example, keep the last year's images on the phone or other source device while, once they've been sync'd, know they will not be destroyed on the destination when they're removed from the source.  This is quite difficult to accomplish without a serious risk of error at present.

**Comment by calmh** [comment]
Seems to me like we support this with the ignore-deletes option to mark the archive _destination_, lacking only a tweak or two to make that nicer looking from the outside (not out of sync).

**Comment by tickerguy** [comment]
Uh, where is that in the folder options?  I don't see it either on the Unix side or on the Android client.

**Comment by tomasz1986** [comment]
You can find it in the Web GUI in the Advanced Configuration (see https://docs.syncthing.net/advanced/folder-ignoredelete).

**Comment by tickerguy** [comment]
Aha.  Yeah, this, other than the "out of sync" (cosmetic, but perhaps ought to be addressed) does appear it will do that.

**Comment by imsodin** [comment]
Some variants of this come up very frequently. And the outcome is always one of the following, or a combination:

- It's unclear what exactly the requirement is, what possibilities to address them already exist or if there's alternatives. Discussions to figure that out should happen on [forum.syncthing.net](https://forum.syncthing.net/). First by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.
- Parts of the proposal/idea might fit syncthing, however the there's no clear scope or task. And no intention from anyone to work on it. Making the ticket unactionable. 
- It's out of scope for syncthing.

Few examples of similar prior tickets:

https://github.com/syncthing/syncthing/issues/7171
https://github.com/syncthing/syncthing/issues/6966
https://github.com/syncthing/syncthing/issues/5060
https://github.com/syncthing/syncthing/issues/4912
