### ISSUE TITLE
High CPU Usage by ksoftirqd After Starting Syncthing on OpenWRT

### ISSUE THREAD

**Issue by reboot-system** [syncthing/syncthing#9798]
### What happened?

 am experiencing a significant issue with high CPU usage by the ksoftirqd process on my OpenWRT device, which runs kernel version 5.10.194.

Whenever I start Syncthing, the CPU usage of the ksoftirqd process consistently remains above 50%. Even after stopping Syncthing, the CPU usage does not return to normal levels. The only way to restore normal CPU usage is to reboot the device. When Syncthing is not started, the CPU usage remains stable.

Please let me know if you need any additional information or logs to diagnose this issue.

### Syncthing version

v1.28.0

### Platform & operating system

Linux amdx64

**Comment by calmh** [comment]
This does not seem to be a Syncthing problem, I suggest googling what ksoftirqd does and what can cause high usage of it.

**Comment by reboot-system** [comment]
Can you provide remote and technical support?

**Comment by calmh** [comment]
Absolutely, this is what https://forum.syncthing.net/ is for.
