### ISSUE TITLE
Advanced -> Folders -> JunctionsAsDirs doesn't work

### ISSUE THREAD

**Issue by Sky-seeker** [syncthing/syncthing#9805]
### What happened?

JunctionsAsDirs doesn't work when I upgrade syncthing from v1.27.12 to v1.28.0.NTFS directory junctions can be scanned when I back to v1.27.12.

### Syncthing version

v1.28.0

### Platform & operating system

windows amd64

**Comment by calmh** [comment]
#9775 fix is in next release
