### ISSUE TITLE
Option to change language

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing#981]
Currently Syncthing uses the browser locale settings to detect the correct language (see list at https://github.com/syncthing/syncthing/tree/master/gui/lang). As a workaround you can use https://127.0.0.1:8080/#?lang=fr to override. Please create option to change language from the web GUI for better usability.

**Comment by urza** [comment]
I would like to urge this issue. It is pretty bad to see language that you dont undertand and not being able to switch to English.

Please consider meanwhile:
1. adding somewhere "use gui in English"..it is completely sufficient, similarly like google has "use google.com in English" at bottom when you access if from different country and it defaults to different language

2. advertise somewhere the ability to add language parameter to adrress bar in browser...

**Comment by AudriusButkevicius** [comment]
It uses your OS/browser locale, hence I am not sure why you are seeing a language you don't understand.

**Comment by urza** [comment]
Because I am installing syncthing on someone else's computer that has, different locale, which I dont understand very much. I am sure there are plenty other valid reasons to want to see the GUI in english. Forcing some foreign language into GUI, that was not explicitly asked for, without option to switch it, is not good practice.

**Comment by wweich** [comment]
The query string `?lang=en` doesn't seem to work.
But if you want another language you can always temporarily change the requested language in your browser.

**Comment by AudriusButkevicius** [comment]
Yeah, true, it's broken. But #1510 should fix it.
