### ISSUE TITLE
Syncthing-Fork crashes few seconds after launch

### ISSUE THREAD

**Issue by SimonMter** [syncthing/syncthing#9815]
### What happened?

Syncthing crashes few seconds after the launch, only when syncthing runs on an unconnected Windows 11 PC.
For me it is with my Android 14 using my Galaxy Tab S6 2024

### Syncthing version

v1.18.0.0

### Platform & operating system

Android 14

**Comment by imsodin** [comment]
Please report that in the right place: https://github.com/Catfriend1/syncthing-android/
