### ISSUE TITLE
Access denied to all my folders for synthing

### ISSUE THREAD

**Issue by David55512345** [syncthing/syncthing#9816]
### What happened?

Suddenly syncthing is unable to get access to my folder and mention the access denied to my folder

### Syncthing version

v1.27.28

### Platform & operating system

windows 10

### Browser version

Microsoft edge

### Relevant log output

```shell
2024-11-12 01:10:15: Failed to create folder root directory: CreateFile \\?\C:\Users\David\Desktop\why: Access is denied.

2024-11-12 01:10:15: Error on folder "why" (v4ne6-pyau5): CreateFile \\?\C:\Users\David\Desktop\why: Access is denied.
```

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
