### ISSUE TITLE
Can one click installation be achieved

### ISSUE THREAD

**Issue by kcon0305** [syncthing/syncthing#9826]
### Feature description

Can one click installation of the version be achieved (without the need to enter the page for configuration), and subsequent association operations can be implemented through APIs, such as creating users, creating connections, creating shared folders, etc.Or if the above functions already exist, can you provide me with the corresponding API.

### Problem or use case

Solving the tedious configuration process, more suitable for private development.

### Alternatives or workarounds

Currently, I have reviewed the source code but have not been able to resolve the issue.

**Comment by calmh** [comment]
I believe this is a question for the forum, https://forum.syncthing.net/

**Comment by kcon0305** [comment]
> I believe this is a question for the forum, https://forum.syncthing.net/
Can you explain it in detail
