### ISSUE TITLE
Folder which i was syncing  all gone/removed Deleted

### ISSUE THREAD

**Issue by javeriarehamn** [syncthing/syncthing#9830]
### What happened?

I have a setup with multiple devices: one running Windows and the other a Kali VM. I was syncing a folder between them (from window machine to linux), but during the process, the entire folder was deleted, except for the files that were open at the time. The deleted files cannot be found anywhere. 

### Syncthing version

v1-28.0

### Platform & operating system

one is window 10 machine and kali linux 

### Browser version

edge

**Comment by tomasz1986** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - [forum.syncthing.net](https://forum.syncthing.net/) - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

Please make sure to include more details in the forum post though, as with this much information, it is not really possible to do anything concrete about the problem.
