### ISSUE TITLE
Syncthing APT repository signing key uses SHA1 self-signatures; fails verification with stricter OpenPGP implementation

### ISSUE THREAD

**Issue by julian-klode** [syncthing/syncthing#9831]
### What happened?

Replacing GnuPG with Sequoia for APT verification, the Syncthing repository fails to validate correctly:

$ sq verify --keyring /etc/apt/keyrings/syncthing-archive-keyring.gpg  /var/lib/apt/list/apt.syncthing.net_dists_syncthing_InRelease 
Signing key on 37C84554E7E0A261E4F76E1ED26E6ED000654A3E is not bound:
           No binding signature at time 2024-11-14T11:02:27Z
  because: Policy rejected non-revocation signature (PositiveCertification) requiring second pre-
image resistance
  because: SHA1 is not considered secure since 2023-02-01T00:00:00Z
1 bad checksum.
Error: Verification failed: could not fully authenticate any signatures

You can either migrate to a new signing key or resign the signing key; I think both the primary and sub key need to be resigned. In either case, manual work on end user systems will be required once the crypto backend switches. This means that you may want to take the opportunity to rotate to a stronger signing key and dual sign - for example, BSI in Germany already recommends 3000 bits at least, so 3072 keys may be nicer.

### Syncthing version

N/A

### Platform & operating system

Linux

**Comment by julian-klode** [comment]
To inspect your key you can use sq inspect:

```
$ curl -s https://syncthing.net/release-key.gpg | sq inspect
-: OpenPGP Certificate.

    Fingerprint: 37C84554E7E0A261E4F76E1ED26E6ED000654A3E
                 Invalid: No binding signature at time 2024-11-23T08:18:23Z: Policy rejected non-revocation signature (PositiveCertification) requiring second pre-image resistance, because SHA1 is not considered secure since 2023-02-01T00:00:00Z
Public-key algo: RSA
Public-key size: 2048 bits
  Creation time: 2014-12-29 08:50:39 UTC

         Subkey: 2A97724352D4CC67662B0B4E681C3CFCF614F575
                 Invalid: Policy rejected non-revocation signature (SubkeyBinding) requiring second pre-image resistance
                 because: SHA1 is not considered secure since 2023-02-01T00:00:00Z
                 Invalid: primary key: No binding signature at time 2024-11-23T08:18:23Z, because Policy rejected non-revocation signature (PositiveCertification) requiring second pre-image resistance, because SHA1 is not considered secure since 2023-02-01T00:00:00Z
Public-key algo: RSA
Public-key size: 2048 bits
  Creation time: 2014-12-29 08:50:39 UTC

         UserID: Syncthing Release Management <release@syncthing.net>
                 Invalid: Policy rejected non-revocation signature (PositiveCertification) requiring second pre-image resistance
                 because: SHA1 is not considered secure since 2023-02-01T00:00:00Z
 Certifications: 1, use --certifications to list

```

**Comment by calmh** [comment]
Yeah it's certainly time for a key rotation.

**Comment by calmh** [comment]
The key linked on the website is now a newer, stronger, key. The releases are signed with both the old and the new key.

We should probably add a package like `syncthing-signing-keys` to handle rotations in the future...

**Comment by julian-klode** [comment]
Thanks. We have a bunch of ways in APT to alert people of repository changes. I can figure out if there's a way for you to (ab)use that to notify people to refresh their key.

The convention for a keyring package would be `syncthing-archive-keyring` installing `/usr/share/keyrings/syncthing-archive-keyring.gpg`; but also just dropping the keyring into the main syncthing package works fine.


 I tend to like the Google model where they stuff the source file into the deb, given that its a single deb in the repo, i.e. ship

```
$ cat /etc/apt/sources.list.d/syncthing.sources
Types: deb
URIs: https://apt.syncthing.net/
Suites: syncthing
Components: stable
Signed-By: /usr/share/keyrings/syncthing-archive-keyring.gpg
```

But it's weird to migrate people by shipping a static file in an existing package. But what you can do:

1. Ship the keyring
2. ship the sources files in examples. 
3. On fresh installs, setup automatic updates from the deb postinst
```
if [ "$1" = "configure" ] && [ -z "$2" ]; then
    cp /usr/share/doc/syncthing/syncthing.sources /etc/apt/sources.list.d/
fi
```
4. Point people to download the deb

That's sort of the Google Chrome approach to packaging.
