### ISSUE TITLE
syncthing-debian (apt) should be hardened with compiler flags

### ISSUE THREAD

**Issue by leonyu** [syncthing/syncthing#9837]
### Feature description

syncthing-debian (apt) should be hardened with compiler flags

```
$ syncthing --version
syncthing v1.28.0 "Gold Grasshopper" (go1.23.2 linux-amd64) debian@github.syncthing.net 2024-10-04 19:47:57 UTC [noupgrade]
$ checksec --file=`which syncthing`
RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH	Symbols		FORTIFY	Fortified	Fortifiable	FILE
No RELRO        No canary found   NX enabled    No PIE          No RPATH   No RUNPATH   33808 Symbols	  No	0		0		/usr/bin/syncthing
```
vs
```
$ checksec --file=`which bash`
RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH	Symbols		FORTIFY	Fortified	Fortifiable	FILE
Full RELRO      Canary found      NX enabled    PIE enabled     No RPATH   No RUNPATH   No Symbols	  Yes	13		33		/usr/bin/bash
```

Reference:

* https://github.com/docker-library/golang/issues/231
* https://devdrivensecurity.substack.com/p/hardening-go-programs-1n

Some of the hardening features (e.g. PIE, RELRO) might require changing linker, so might not be worthwhile. 

### Problem or use case

Syncthing binary should be hardened with common compiler flags to minimize common security risks. 

### Alternatives or workarounds

n/a

**Comment by calmh** [comment]
If and when these things are added by Go they'll be used. I don't believe they add much value in Go as compared to for example C. Using an external linker is not an option for us.
