### ISSUE TITLE
Get "https://relays.syncthing.net/endpoint": EOF

### ISSUE THREAD

**Issue by misieck** [syncthing/syncthing#9841]
### What happened?

Cant connect some of my machines. Log says:
`listenerSupervisor@dynamic+https://relays.syncthing.net/endpoint: service dynamic+https://relays.syncthing.net/endpoint failed: Get "https://relays.syncthing.net/endpoint": EOF`

```
wget https://relays.syncthing.net/endpoint
--2024-11-28 23:13:25--  https://relays.syncthing.net/endpoint
Resolving relays.syncthing.net (relays.syncthing.net)... 51.159.86.208
Connecting to relays.syncthing.net (relays.syncthing.net)|51.159.86.208|:443... connected.
OpenSSL: error:0A000126:SSL routines::unexpected eof while reading
Unable to establish SSL connection.
```

To fix for now, I change address of the machine from dynamic to its ip anddress or hostname. (the machines are on two separate local networks, locally routable).

### Syncthing version

v1.18.0-ds1

### Platform & operating system

Linux-amd64

### Relevant log output

```shell
2024-11-28 23:19:45 listenerSupervisor@dynamic+https://relays.syncthing.net/endpoint: service dynamic+https://relays.syncthing.net/endpoint failed: Get "https://relays.syncthing.net/endpoint": EOF
2024-11-28 23:19:45 Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting
2024-11-28 23:19:46 Relay listener (dynamic+https://relays.syncthing.net/endpoint) shutting down
```

**Comment by AAdem479** [comment]
I'm on the same boat. Cannot find a fix as one of my devices is in a different country. Devices on the local networks work though.

**Comment by bt90** [comment]
https://forum.syncthing.net/t/general-services-down/23320

**Comment by AAdem479** [comment]
> https://forum.syncthing.net/t/general-services-down/23320

Thanks!
