### ISSUE TITLE
support for harmony next

### ISSUE THREAD

**Issue by walk143** [syncthing/syncthing#9844]
### Feature description

could install and run syncthing on harmony next system.

### Problem or use case

The number of Next users increases.
According to [news](https://view.inews.qq.com/k/20230806A043DS00?web_channel=wap&openApp=false)
,the number of Harmony Ecosystem devices exceeds 700 million. 2.2 million HarmonyOS developers have invested in the development of HarmonyOS. APIs are invoked 59 billion times daily, and more than 350 software and hardware products are used.

### Alternatives or workarounds

there is no alternative

**Comment by calmh** [comment]
This appears to be a somewhat proprietary Android fork. As such I think it primarily shares the Android app's fate, but if someone wants to take this up they'er welcome to it.
