### ISSUE TITLE
Syncthing update/upgrade overwriting edited service file.

### ISSUE THREAD

**Issue by storeilly** [syncthing/syncthing#9853]
### What happened?

This morning when I updated from 1.28.0 to 1.28.1 it appears the syncthing@.service file was overwritten to default.
I had previously edited the file in order to relocate the --home directory and lost the config. Panic set in when syncthing came up with default settings and a new ID refusing to connect to my other devices, until I remembered my edit. My system is back working now but would like to see if this can be avoided somehow in the future. I'm sure I've upgraded in the past without this happening.

### Syncthing version

v1.28.1

### Platform & operating system

Linux (32-bit ARM) on rPi

**Comment by bt90** [comment]
Never edit service files in place. Use this instead:

```sh
systemctl edit --full syncthing@.service
```
