### ISSUE TITLE
GUI address unix socket broken

### ISSUE THREAD

**Issue by PeterSurda** [syncthing/syncthing#9855]
### What happened?

syncthing used to work with a unix socket as a GUI address, e.g. when using a command line option like this:

`-gui-address=unix:///run/syncthing/syncthing.sock`

It worked until 1.28.0 (including), and then in 1.28.1. it broke and complains.

I think PR #9675 is the culprit, more specifically commit 65d0ca8aa96efa785fe9527de992e7efaabc22bd

### Syncthing version

v1.28.1

### Platform & operating system

Linux amd64

### Relevant log output

```shell
[start] WARNING: Failed to initialize config: failed to generate default config: get default port (GUI): address /run/syncthing/syncthing.sock: missing port in address
```

**Comment by calmh** [comment]
Yep, seems like that

**Comment by acolomb** [comment]
Will look into it, but I might need a couple of days...

**Comment by acolomb** [comment]
A workaround for this case is to pass the `--skip-port-probing` option, which is of course useless in case of a UNIX socket.

Still looking into the root cause of this failure.

**Comment by PeterSurda** [comment]
> A workaround for this case is to pass the `--skip-port-probing` option, which is of course useless in case of a UNIX socket.
> 
> Still looking into the root cause of this failure. It happens only when generating a new config, not when simply overriding an existing one's GUI address.

I confirm this workaround works, I tested it with an existing config file, and also without a preexisting config file. That's good enough for me.
