### ISSUE TITLE
Make it easier to disable 'relaysEnabled' option or ask first time before using relays

### ISSUE THREAD

**Issue by dionorgua** [syncthing/syncthing#9867]
### Feature description

I think `syncthing` should somehow warn users first time or add opportunity to disable relays if machine is used in corporate network. 

### Problem or use case

Our company IT security caught me using Tor network while connected to company guest network. I've told them that it's not true and we decided to analyze why it happens. 

So we found that `syncthing` in default configuration may use 'relays' . And a lot of them are hosted by community. The problem is that it's pretty common for volunteers to host multiple things at same time including Tor nodes. 

I think corporate firewall just scans public list of Tor nodes and warns if they are used. Tor is a red flag for companies. And it could happens that users are not aware that it's possible to just disable this feature. 

### Alternatives or workarounds

Maybe just add command line option like `--no-relays`? Or some how make it per-connection option.

**Comment by calmh** [comment]
Yeah... I don't think a command line flag is more discoverable than the existing checkbox in settings, and I'm pretty sure that relays enabled is the appropriate default. I also don't think we should warn about something that is a non-issue except in certain corporate policy situations.
