### ISSUE TITLE
When socket files are in a folder that needs to be synced on linux, some files were not synced until the socket files were removed

### ISSUE THREAD

**Issue by holgerfischerone** [syncthing/syncthing#9872]
### What happened?

OS Fedora 41 
folder to sync is a subfolder in user home containing some socket files of gpg agent (socket files mistakenly got there).

some other  files which were recently changed were randomly not synced until the socket files were removed. 

rescanning and restarting syncthing didn't help.

after removing the socket files the sync process sync all remaining files on 1st attempt.

my assumption is: when the socket files were accessed by the (not so randomly choosing) syncing process the syncing process crashed silently. 

the missing files would have been accessed by the syncing process in the order after the  socket files. since the process crashed silently the files could not get synced. 

- just an assumption -

### Syncthing version

v1.28.0

### Platform & operating system

Linux amd64

### Browser version

Firefox

**Comment by calmh** [comment]
Can you give an example of a file, or a way to create one, to reproduce this issue?

**Comment by holgerfischerone** [comment]
@calmh: I sent you an email.
