### ISSUE TITLE
Files locked on freebsd + samba

### ISSUE THREAD

**Issue by julianuu** [syncthing/syncthing#9873]
### What happened?

I am using syncthing on freebsd to synchronize a folder on a samba share. While syncthing is running I cannot remove any files in that folder; `rm some_file`  fails with `Permission denied.`

I can create files and even modify them, but not remove or rename them. The moment I turn off syncthing I have full access to the files again.

The issue does not occur if I disable the setting "Watch for changes".

This does not happen when synchronizing folders from the local drive. It also doesn't happen with exactly the same setup under arch linux instead of freebsd.

### Syncthing version

v1.27.12

### Platform & operating system

freebsd arm64

**Comment by calmh** [comment]
Watching a file for changes in BSD means having an open file descriptor, which I guess in your setup translates to a lock in Samba. I don't think this is anything specific to do with Syncthing really, it's just a consequence of the systems in use. Perhaps the behaviuor can be tweaked in Samba.

**Comment by julianuu** [comment]
Thank you for the advice. I don't know much about SMB, but I'll try to figure out if this is something that I can tweak in Samba.

It took me quite a while to realize what was going on, so I was wondering if it makes sense to change the defaults in syncthing so that it doesn't have open file descriptors in such a situation.

I'm running syncthing on a vps by hetzner, with my files on an external drive which I mount via smb.
