### ISSUE TITLE
issues with web ui on fedora 40 laptop

### ISSUE THREAD

**Issue by back-lacking** [syncthing/syncthing#9874]
### What happened?

So I have a machines running fedora 40. I start syncthing and the webui, and it would be fine, until I refresh the page or do any change (pause folder share, pause device share, changing ignore paterns, etc). Once i do any of the things mentioned, it would be stuck on this pop up saying "syncthing is saving changes" it would be stuck on there, and then i would have to refresh in my browser. after the refresh, the page would show `(unknown device)` and not properly show the host device data. I would either have to wait for a long time, or refresh and hope it works. 
not sure what is going wrong. journalctl doesnt show anything of note and would just not display anything past whatever my last action was. running syncthing with the `--verbose` flag also doesnt show anything of note. trying in a chromium based browser doesnt change anything. 
if log data need to be provided, i will provide it after i redact personal info from it

### Syncthing version

1.28.0

### Platform & operating system

Fedora 40, x86_64

### Browser version

Firefox 133.0.3

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
