### ISSUE TITLE
Global discovery: http without insecure not supported

### ISSUE THREAD

**Issue by robvanvolt** [syncthing/syncthing#9883]
### Feature description

When I have my syncthing discovery in the same docker compose as the syncthing client, I cannot set the discovery server in the syncthing client, as it first says http without insecure is not supported, and after adding the ?insecure tag it says http without noannounce not supported, so I also need to add ?insecure&noannounce after the local-ip-of-discovery-server:port.

So my question, is there the option to have a local discovery server running without having to add the noannounce tag? Because with the noannounce, it looks as if the client on the discovery server is always disconnected, despite the folders syncing nicely...

Other clients that are on different servers run fine with the reverse proxy to the discovery server.

### Problem or use case

Allow announce in insecure http environment.

### Alternatives or workarounds

Live with the "always disconnected" status.

**Comment by calmh** [comment]
> Allow announce in insecure http environment.

This is not a thing, because the announcement depends on the Syncthing device certificate in the TLS handshake. HTTP mode on the discovery server is for use behind a reverse proxy that does TLS termination. Insecure mode on the client is for TLS servers with self signed certificates.

**Comment by robvanvolt** [comment]
> > Allow announce in insecure http environment.
> 
> This is not a thing, because the announcement depends on the Syncthing device certificate in the TLS handshake. HTTP mode on the discovery server is for use behind a reverse proxy that does TLS termination. `?insecure` on the Syncthing side is for servers with self-signed certificates without using the `?id=...` specifier.

Hm, so what would be the best option for my usecase, so I can use the syncthing client on the same server (same docker compose file) as the syncthing discovery?

**Comment by calmh** [comment]
I don't think I understand why you'd want to talk to a discovery server on localhost, but regardless the option is to run the discovery server with its default settings and use the ID in the url Syncthing-side.

**Comment by robvanvolt** [comment]
even when specifying the id, i get the same noannounce warning...

server1: syncthing + syncthing-discovery
server2: syncthing
server3: syncthing

server 2 + 3 point to server 1 syncthing-discovery (through reverse proxy)
server 2 + 3 sync folders with server 1 syncthing

server 1 syncthing cannot connect to the server 1 syncthing discovery (neither the dns, nor the local ip address with specified id from the syncthing discovery start)

server 2 and server 3 syncthing see each other as connected.
server 1 and server 2 syncthing see each other as disconnected, despite successfully syncing folders
server 1 and server 3 syncthing see each other as disconnected, despite successfully syncing folders

Am I missing something? Is it not intented to work this way?

**Comment by calmh** [comment]
Possibly many things. Please take this to the forum instead.
