### ISSUE TITLE
Issues with scanning large directories

### ISSUE THREAD

**Issue by jimeh** [syncthing/syncthing#989]
I have a `~/Projects` directory, and as you can imagine it's rather large (~400k files). When I add it to Syncthing with default settings, after a while Syncthing eats up all spare CPU across all cores, and even stops responding correctly to HTTP requests. At one point I was getting a 404 response for `GET /`.

It seems changing the rescan interval of the directory from every 60 seconds, to every 3600 seconds seems to help. CPU is still being eaten alive, but Syncthing for the most part responds in a timely manner to HTTP requests. It does take 10-20 seconds to reload the page sometimes, but it works. Compared that to it taking minutes or just not responding with a rescan interval of 60 seconds.

So my question is, can scanning of large directories be improved? And does the rescan feature start a scan even if the previous scan hasn't finished yet?

Also, I'd be more than happy to re-add my Projects directory with any needed debug logging flags enabled :)

**Comment by EmilioMoreno** [comment]
Hi, quick question, i am now going through the initial scan of a large folder, 1TB of Data,  26.500 Files What would be the appropriate rescan settings? On one side i have a Sinology Nas, but unfortunately on the other i have a pi2 with a old Synology (ppc) NAS attached, so cpu is not one of the luxuries i have.
